### ISSUE TITLE
Settings per project

### ISSUE THREAD

**Issue by miguelamello** [atom/atom#8212] opened 2015-08-04 13:28 UTC
Hi There,

I have projects which encoding is utf8 and iso88591, and is annoying having to change the default encoding for reading and writing files in Core Settings, each time I switch from one project to another. I think besides Core Settings, the project folder itself should have a "Project Settings" that should overload the Core Settings. One of the setting in Project Settings should be Default Encoding for the project files. May be some other project specific settings could be present in Project Settings. Well, this is just an insight. You guys know what is better for Atom. Any way I love Atom as it is. 

Best regards,

Miguel Mello

**Comment by mnquintana** [comment] 2015-08-04 13:30
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/5168 though – please subscribe there for updates.

**Closed by mnquintana** 2015-08-04 13:30 UTC
