### ISSUE TITLE
error opening install  

### ISSUE THREAD

**Issue by axe-z** [atom/atom#16033] opened 2017-10-30 22:00 UTC
This looks bad , going in preference it does not fetch FEATURED PACKAGES
Version 1.21.1 latest 

# Fatal error in ../deps/v8/src/snapshot/deserializer.cc, line 811
# Check failed: false.
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::internal::Deserializer::ReadData(v8::internal::Object**, v8::internal::Object**, int, unsigned char*)
 3: v8::internal::Deserializer::ReadObject(int, v8::internal::Object**)
 4: v8::internal::Deserializer::ReadData(v8::internal::Object**, v8::internal::Object**, int, unsigned char*)
 5: v8::internal::Deserializer::ReadObject(int, v8::internal::Object**)
 6: v8::internal::Deserializer::ReadData(v8::internal::Object**, v8::internal::Object**, int, unsigned char*)
 7: v8::internal::Deserializer::ReadObject(int, v8::internal::Object**)
 8: v8::internal::Deserializer::ReadData(v8::internal::Object**, v8::internal::Object**, int, unsigned char*)
 9: v8::internal::Deserializer::ReadObject(int, v8::internal::Object**)
10: v8::internal::Deserializer::ReadData(v8::internal::Object**, v8::internal::Object**, int, unsigned char*)
11: v8::internal::Deserializer::ReadObject(int, v8::internal::Object**)
12: v8::internal::Deserializer::ReadData(v8::internal::Object**, v8::internal::Object**, int, unsigned char*)
13: v8::internal::Deserializer::ReadObject(int, v8::internal::Object**)
14: v8::internal::Deserializer::ReadData(v8::internal::Object**, v8::internal::Object**, int, unsigned char*)
15: v8::internal::Heap::IterateStrongRoots(v8::internal::ObjectVisitor*, v8::internal::VisitMode)
16: v8::internal::Deserializer::Deserialize(v8::internal::Isolate*)
17: v8::internal::Isolate::Init(v8::internal::Deserializer*)
18: v8::internal::Snapshot::Initialize(v8::internal::Isolate*)
19: v8::Isolate::New(v8::Isolate::CreateParams const&)
20: node::Start(int, char**)
21: start

/Applications/Atom.app/Contents/Resources/app/apm/bin/apm: line 46: 19353 Illegal instruction: 4  "$binDir/$nodeBin" "$cliPath" "$@"

**Comment by rsese** [comment] 2017-10-31 19:22
Thanks for reaching out!

As mentioned in https://github.com/atom/atom/issues/15893#issuecomment-336814876, can you use the issue template when reporting issues?  If you can update the issue body with the template information, that will help us take a look.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by mcfarke311** [comment] 2018-01-15 14:39
I have also hit this issue. I can't open atom because of this stack trace. It doesn't look like @axe-z is going to fill out the template though. I'll see what I  can do.

**Comment by mcfarke311** [comment] 2018-01-15 15:00
Prerequisites

[X] Put an X between the brackets on this line if you have done all of the following:
Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages
Description

This is day two of me trying the atom text editor. Day one, worked well and I installed atom-runner to run Javascript inside atom (I don't know if this could cause some issues). I installed Atom through the .deb package provided on the website and I am running on GalliumOS on a Samsung Chromebook 3. When trying to start atom, I'm receiving the following error in the terminal:

 /usr/bin/atom: line 129: 27834 Illegal instruction     nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1


#
# Fatal error in ../../v8/src/snapshot/deserializer.cc, line 853
# Check failed: false.
#

==== C stack trace ===============================

    /usr/share/atom/libnode.so(+0xb13c2e) [0x7f1b921e1c2e]
    /usr/share/atom/libnode.so(V8_Fatal+0xdf) [0x7f1b921e3ccf]
    /usr/share/atom/libnode.so(+0x4b9253) [0x7f1b91b87253]
    /usr/share/atom/libnode.so(+0x4b99f4) [0x7f1b91b879f4]
    /usr/share/atom/libnode.so(+0x4b8f44) [0x7f1b91b86f44]
    /usr/share/atom/libnode.so(+0x4b99f4) [0x7f1b91b879f4]
    /usr/share/atom/libnode.so(+0x4b8f44) [0x7f1b91b86f44]
    /usr/share/atom/libnode.so(+0x4b99f4) [0x7f1b91b879f4]
    /usr/share/atom/libnode.so(+0x4b7e21) [0x7f1b91b85e21]
    /usr/share/atom/libnode.so(+0x4b99f4) [0x7f1b91b879f4]
    /usr/share/atom/libnode.so(+0x4b7e21) [0x7f1b91b85e21]
    /usr/share/atom/libnode.so(+0x8f2509) [0x7f1b91fc0509]
    /usr/share/atom/libnode.so(+0x4b68ac) [0x7f1b91b848ac]
    /usr/share/atom/libnode.so(+0xa76c9d) [0x7f1b92144c9d]
    /usr/share/atom/libnode.so(+0xab2117) [0x7f1b92180117]
    /usr/share/atom/libnode.so(v8::Isolate::New(v8::Isolate::CreateParams const&)+0x15c) [0x7f1b91edef4c]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version() [0x1b81170]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version(atom::JavascriptEnvironment::JavascriptEnvironment()+0x22) [0x3b8e432]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version(atom::AtomBrowserMainParts::PostEarlyInitialization()+0xcf) [0x3b8a70f]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version() [0x17ee27f]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version() [0x17d76ff]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version() [0x164dde8]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version() [0x134fe04]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version() [0x1350210]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version(main+0x83) [0x3b82e73]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f1b8a77b830]
    /usr/share/atom/atom --executed-from=/home/kevin --pid=27821 version() [0x59a3b9]


Steps to Reproduce

[First Step] install Atom version 1.23.3 via .deb package installer
[Second Step] install nodejs
[Third Step] install atom-runner and set a runner for js to run with nodejs
[Fourth Step] Try to start atom
Expected behavior: Atom text starts up and I can use it.

Actual behavior: I get the stack trace pasted in description

Reproduces how often: once I hit this issue it is totally blocking 100% of the time

Versions

You can get this information from copy and pasting the output of atom --version and apm --version from the command line. Also, please include the OS and what version of the OS you're running.

Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-04-27 21:50
Sorry I missed your followup @mcfarke311 - based on this step:

> [Third Step] install atom-runner and set a runner for js to run with nodejs

It sounds like you're only having this issue specifically when using the [atom-runner](https://github.com/lsegal/atom-runner) package.  In this case we recommend filing the issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).  It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. 

---

Thanks again for your issue @axe-z!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16033#issuecomment-340879073. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-04-27 21:50 UTC
Labels: more-information-needed
