### ISSUE TITLE
Invisible top menu on Ubuntu after upgrade to 1.33.0

### ISSUE THREAD

**Issue by rzelnik** [atom/atom#18567] opened 2018-12-10 04:38 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After upgrade to 1.33.0, the letters in the top menu become invisible (dark letters on dark background). I use Ubuntu 18.10 with default Yaru desktop theme and Atom with One Dark UI theme, but it looks the same also with Atom's Light themes. The issue appears with focus on the Atom window only. With unfocused Atom the top menu letters become visible.

### Steps to Reproduce

1. Install Atom 1.33.0 on Ubuntu 18.10
2. See the top menu

**Expected behavior:** Visible top menu.

**Actual behavior:** Invisible top menu.

**Reproduces how often:** Always.

### Versions

atom --version
Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

Atom Theme: One Dark

apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.15+
git 2.19.1

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"

Desktop Theme: Yaru (default)

### Additional Information

![invisible-top-menu](https://user-images.githubusercontent.com/610651/49711092-be41fb80-fc3d-11e8-931b-ec00eb6db319.png)

**Comment by thomasjo** [comment] 2018-12-10 09:04
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #18535. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by thomasjo** 2018-12-10 09:04 UTC
