### ISSUE TITLE
Atom freezes when opening large binary files

### ISSUE THREAD

**Issue by mirosval** [atom/atom#14172] opened 2017-04-11 14:29 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have large binary files in the tree (JARs >1GB). I know I shouldn't open them in Atom, but sometimes I misclick and open one of these. In that case Atom freezes with `Loading Archive` message. If the file is not too big, it will eventually load, but editor is not usable during this time. If the file is too big it will eventually display a message where I can either _wait more_ or _close_. Unfortunately the _close_  closes the entire window.

### Steps to Reproduce

1. Open a directory containing a large (binary) file
2. (Mis)click the file in Atom
3. Atom freezes while the file is loaded 

**Expected behavior:** [What you expect to happen]

One or more of the following:

* Atom asks if I want to open this file (normally you don't open large binary files, for large text files you might want to say yes and wait a bit)
* Atom starts loading, but UI remains responsive so I can close the tab and continue working
* Atom displays a preview but requires additional action to actually open the file
* When Atom eventually asks if I want to kill the process, just close the tab, don't kill the whole window

**Actual behavior:** [What actually happens]

* Atom UI freezes, making it unusable for > 1 min
* Atom asks if I want to close the file, but this closes entire window

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always for a sufficiently large file

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Mac OS X 10.12.4 (16E195)

**Comment by rsese** [comment] 2017-04-13 17:29
> Expected behavior: [What you expect to happen]
> 
> One or more of the following:
> 
> Atom asks if I want to open this file (normally you don't open large binary files, for large text files you might want to say yes and wait a bit)

Atom will ask you to confirm if you want to open a large file before opening based on a Setting (`Settings > Core > Warn on Large File limit`) that defaults to 40MB, but it seems like you're saying you weren't prompted, can you confirm?    I tested by trying to open an Ubuntu .iso and I was prompted to confirm if I wanted to open the file or not.

**Comment by mirosval** [comment] 2017-04-18 15:41
I can indeed confirm that is the case. I see the setting in Core and it is set to the default of 40. I single click on a file that is larger than 40MB, Atom freezes for about a minute and then I get `Editor is not responding` and choices to either `Keep waiting` or `Close`.

The `Close` option will kill the window, and the `Keep waiting` option will eventually show a tree of all the files in the .jar. The jar is 66MB with ~45k files and so the scrolling is very slow, but I am able to close the tab, during which Atom freezes again and again asks if I want to `Keep waiting`. After about a minute it closes the tab and everything works.

**Comment by rsese** [comment] 2017-04-19 00:57
Ohhh sorry I missed this part of your initial report:

> with `Loading Archive` message.

There's an archive-view package that lets you open archive files like JAR files in Atom - it looks like it doesn't honor the `Warn on Large File limit` setting (seems like it should?) and I also see there's already an open issue about the UI blocking when opening a large archive file /cc https://github.com/atom/archive-view/issues/19.

So I think this  is basically a dupe of https://github.com/atom/archive-view/issues/19 and the fact that the `Warn on Large File limit` doesn't apply to archive files seems like a new issue - what do you think @mirosval?

**Comment by mirosval** [comment] 2017-04-19 06:53
No worries :) 

I can confirm that this happens for `.jar` and `.zip`, but I get warned and can abort the process for `.iso` for example.

**Comment by rsese** [comment] 2017-04-27 04:03
> I can confirm that this happens for .jar and .zip, but I get warned and can abort the process for .iso for example.

:+1:  So I'll go ahead and close this (the blocking UI when opening a large archive file handled by archive-view) as a dupe of https://github.com/atom/archive-view/issues/19) and did you want to open an issue about how the `Warn on Large File limit` setting isn't honored with large archive files?  If not I can do it :v:

**Closed by rsese** 2017-04-27 04:03 UTC
Labels: more-information-needed
