### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rgrigoriadi** [atom/atom#18473] opened 2018-11-21 11:14 UTC
Unfortunately I didn't do anything special to get that error

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Windows 10
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\...\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:1108109)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:1103819)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:89276)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:79025)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:69678)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:67306)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:92055)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by rsese** [comment] 2018-11-21 22:42
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16892 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-21 22:42 UTC
