### ISSUE TITLE
Text wiggling

### ISSUE THREAD

**Issue by mnpenner** [atom/atom#6183] opened 2015-03-31 07:29 UTC
The text on the tabs and certain panels (such as settings) wiggles around a bit as I mouse over and off it.

![](http://i.imgur.com/HOqeBsZ.gif)

Produced on Win8.1 running at 4K.

**Comment by thomasjo** [comment] 2015-03-31 07:56
Most likely sub-pixel rendering related, and as such likely to be an upstream Chromium problem.

/cc @zcbenz

**Comment by simurai** [comment] 2015-03-31 22:24
It looks like a dupe of https://github.com/atom/one-dark-ui/issues/27

I'll reopen that one and see if it can be fixed in the theme.

**Closed by simurai** 2015-03-31 22:24 UTC
Labels: bug, editor-rendering
