### ISSUE TITLE
A little problem when  click and press A to add a file

### ISSUE THREAD

**Issue by playgithub** [atom/atom#20095] opened 2019-11-01 06:42 UTC
![a](https://user-images.githubusercontent.com/3665590/68007057-7264ce80-fcb5-11e9-914e-04683476aaed.png)

my steps to add a file to a folder:
1. click a folder
2. press 'a'
3. enter file name and press Enter to save

The little problem is in step 1, when a folder is clicked, it is toggled (fold/unfold) automatically, this is not what I expected.

Thanks

**Comment by rfoldbirk** [comment] 2019-11-05 09:29
Same! I would also prefer if it only toggled when clicking the little arrow 👍

**Comment by rsese** [comment] 2019-11-11 01:26
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1222 so you can subscribe there if you'd like.

As mentioned in that issue, you may find https://atom.io/packages/dbclick-tree-view helpful.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-11 01:26 UTC
