### ISSUE TITLE
Markdown syntax highlighting works in pre-formatted blocks but should not be applied

### ISSUE THREAD

**Issue by slhck** [atom/atom#9083] opened 2015-10-08 12:00 UTC
When using 4-space indented blocks for pre-formatted text, styling syntax like `_` is interpreted directly, showing as italicized text in the editor. It also makes the formatting "leak" to the normal text, continuing into the next code block:

![image](https://cloud.githubusercontent.com/assets/582444/10365544/8a6d34e2-6dc4-11e5-9682-649780df581e.png)

Here, there should have been no formatting applied in the 4-space indented blocks, and the `Test` should have been non-italicized.

Atom version 1.0.19

**Comment by 50Wliu** [comment] 2015-10-08 13:37
Duplicate of atom/language-gfm#44, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-08 13:37 UTC
