### ISSUE TITLE
Atom Premature Not Responding Dialog

### ISSUE THREAD

**Issue by tjgerot** [atom/atom#11902] opened 2016-06-05 04:28 UTC
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom consistently, prematurely, opens a dialog alerting me "The editor is not responsive" and asks me to keep waiting or to close. I experience this dialog before preforming any major action (listed in the 'Steps to Reproduce' section) and as soon as I click keep waiting the action finishes. If the application had waited a second more, the action would have been finished loading and there would be no need for the dialog.

### Steps to Reproduce

Actions that can be reproduced to trigger this issue:
* Opening Atom
* Closing Atom
* Create a File
* Delete a File
* Save a File
* Open a File
* Make a Folder
* Delete a Folder

**Expected behavior:** The application should preform the action, load and display the contents, only displaying the dialog when it's very confident the editor has become truly unresponsive.

**Actual behavior:** The dialog shows up while the application is finishing loading.

### Versions

Atom version 1.7.4
Windows 10

**Comment by lee-dohm** [comment] 2016-06-05 06:20
Can you give us anything more to go on? Is this happening on a particular project? Are you opening a particularly large directory?

With the information given, I'm doubtful that we can reproduce the problem you're describing.

@damieng, any ideas?

**Comment by damieng** [comment] 2016-06-05 06:29
"The editor is not responding" has to be something in Atom rather than Windows as Windows doesn't know it's an editor.  I'm not familiar with what our code does around there yet.

**Comment by lee-dohm** [comment] 2016-06-05 06:37
Yes, this is the standard handling of the [unresponsive event](http://electron.atom.io/docs/all/#event-unresponsive). But if you haven't run into this kind of thing @damieng, I would believe that it is caused by something in @tjgerot's environment.

**Comment by damieng** [comment] 2016-06-05 06:51
I've seen a bunch of 'editor has crashed' but I was running an out-of-date
dev-built atom with newer packages/specs.  Not seen the 'not responding'
variant.

**Comment by JangoBrick** [comment] 2016-06-19 20:38
Note that the same dialog also appears when opening the tree view's context menu, and then keeping it open without touching mouse or keyboard for about 30 seconds (noticed it by coincidence, then searched for and found this thread). This is obviously not a very problematic issue, but possibly a sign of a generally weak implementation. Windows 10, Atom 1.8.0.

**Comment by lee-dohm** [comment] 2016-06-30 01:22
@tjgerot Are you still experiencing this problem? We haven't been able to reproduce it on our end. Can you give us more information about how you're using Atom?

**Comment by lee-dohm** [comment] 2016-07-06 16:03
@tjgerot Let us know if you have any more information you can supply. As things stand now, we can't reproduce the issue so we'll have to close it. If you can give us any more information, please let us know and we'll be happy to reopen it and investigate further!

**Closed by lee-dohm** 2016-07-06 16:03 UTC
Labels: more-information-needed, windows
