### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by LucaDev** [atom/atom#6924] opened 2015-05-23 18:09 UTC
[Enter steps to reproduce below:]

1. Start Atom

**Atom Version**: 0.201.0
**System**: LUCASPC
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\app.asar\src\window-event-handler.js:149:33)
    at HTMLDocument.handler (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\Luca\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-plus",
      "welcome",
      "wrap-guide",
      "jenkins",
      "hex",
      "atom-html-preview",
      "bower-install",
      "project-manager",
      "language-ejs",
      "todo-show",
      "npm-install",
      "minimap"
    ],
    "projectHome": "c:\\users\\luca\\Development\\Atom\\",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 17
  }
}
```

### Installed Packages

```coffee
# User
angularjs-snippets, v0.10.2
color-picker, v1.7.0
file-icons, v1.5.5
filetype-color, v0.1.4
javascript-snippets, v1.0.0
keyboard-localization, v1.3.1

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-05-23 18:56
This is a duplicate of https://github.com/atom/atom/issues/6548 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-23 18:56 UTC
