### ISSUE TITLE
Using atom as a background process fails sometimes on Mac

### ISSUE THREAD

**Issue by basarat** [atom/atom#9663] opened 2015-11-17 23:10 UTC
We use atom as a background process. It has started to fail on a Mac since version `1.2`. Refs https://github.com/TypeStrong/atom-typescript/issues/728

**Reproduction Steps:**

1. Install Atom-typescript
2. Open a TypeScript file
3. Wait 3-6 minutes

**Expected behavior:**

The background worker should continue to work

**Observed behavior:**

If fails with error : 

```ts
/Users/tomi/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:180 CHILD ERR STDERR: Atom Helper(63023,0x7fff74876000) malloc: *** error for object 0x7f923840ce20: pointer being freed was not allocated
```

**Screenshots and GIFs**

In dev console: 

![](https://cloud.githubusercontent.com/assets/376203/11227621/e7faab62-8d3b-11e5-89ba-c59d4e732bc0.png)

**Atom version:** 1.2
**OS and version:** Mac OSX 

**Installed packages:**

atom-typescript, linter

**Additional information:**

* Problem can be reproduced in safe mode: Only happens if you use the package
* Problem started happening recently, didn't happen in an older version of Atom: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by the-destro** [comment] 2015-11-19 17:23
Still occurs in 1.2.2

**Comment by JoshEngebretson** [comment] 2015-11-19 23:34
... and 1.2.3

**Comment by GabiGrin** [comment] 2015-11-30 12:25
+1. This is making atom-typescript useless

Any advice on a safe way to revert to 1.1.0 until this is fixed?

**Comment by thedaniel** [comment] 2015-11-30 13:54
@zcbenz what's the best way for these folks to provide debug info? I assume it's electron-related due to the malloc error from atom-helper

**Comment by adidahiya** [comment] 2015-12-02 01:24
+1

**Comment by paulcbetts** [comment] 2015-12-02 01:33
"Set a breakpoint in malloc_error_debug to debug"

**Comment by tomitrescak** [comment] 2015-12-02 07:16
@GabiGrin ... unfortunatelly the only solution (on Mac) is to keep 1.1.0 downloaded in a new folder and then copy over the Atom in /Applications folder before launch ;/ Hope that this gets fixed soon.

**Comment by paulcbetts** [comment] 2015-12-02 07:20
Wait, so why are you doing this at all? Just create a new `BrowserWindow`, don't show it, then use it as your background job processor

**Comment by basarat** [comment] 2015-12-02 22:47
@paulcbetts  sweet :candy: 

But how do I get access to it? 

Couldn't find it in atom docs : https://atom.io/docs/api/search/v1.2.4?utf8=%E2%9C%93&q=BrowserWindow

Also code from electron: https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindow didn't work in my atom console :

![image](https://cloud.githubusercontent.com/assets/874898/11546640/a3306a4e-99a2-11e5-91ef-62188ee12989.png)

**Comment by Narquadah** [comment] 2015-12-02 22:53
It seems to be fixes in Atom 1.3 Beta, I've been using it for a couple of days now without problems.

**Comment by paulcbetts** [comment] 2015-12-02 23:10
@basarat `var BrowserWindow = require('remote').require('browser-window')`

**Comment by paulcbetts** [comment] 2015-12-02 23:12
So, in your create settings, use the Preload script as the code you want to execute remotely (i.e. set up an IPC listener that will grab messages and respond back with the result)

**Comment by tomitrescak** [comment] 2015-12-04 11:39
I can confirm that with Atom 1.3 beta all is OK.

**Comment by 50Wliu** [comment] 2015-12-04 17:16
> I can confirm that with Atom 1.3 beta all is OK.

Ok, that's good to know.  I'm closing this then.

**Closed by 50Wliu** 2015-12-04 17:16 UTC
Labels: bug
