### ISSUE TITLE
UTF-16 files read incorrectly

### ISSUE THREAD

**Issue by ForNeVeR** [atom/atom#9190] opened 2015-10-17 14:18 UTC
Try to open any valid UTF-16 (with or without BOM) file in a freshly installed atom. It will open, but the cursor movement will be broken (it will move one character every two key presses).

It seems that Atom always opens UTF-16 files in UTF-8 mode and keeps `NUL` characters between "normal" ASCII letters. Non-ASCII letters will render in strange ways.

The problem can be solved if the user changes file encoding manually in the status bar.

I am using Atom 1.0.19 on Windows 10 x64. Let me know if you need any additional information or help with debugging.

**Comment by 50Wliu** [comment] 2015-10-17 23:42
Can you try opening a UTF-16 file without BOM?

Can you also elaborate on "the problem cannot be solved with changing the encoding"?  Does that mean clicking the encoding selector on the status bar and selecting UTF-16 doesn't help?

**Comment by ForNeVeR** [comment] 2015-10-18 09:59
> Can you try opening a UTF-16 file without BOM?
Yes, this issue can be equally reproduced with UTF-16 files with or without BOM. BOM itself renders as `��` in my editor window.
> Does that mean clicking the encoding selector on the status bar and selecting UTF-16 doesn't help?
I am sorry, it seems that I've mistaken here. Encoding selector in the status bar works okay for me and UTF-16 reads correctly after the switch. I'll edit the initial post to clarify that.

**Comment by 50Wliu** [comment] 2015-10-18 17:25
Ok, it looks like this is a duplicate of atom/encoding-selector#8 then.

**Closed by 50Wliu** 2015-10-18 17:25 UTC
Labels: more-information-needed
