### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 174Error: Cannot cal...

### ISSUE THREAD

**Issue by gurov86rus** [atom/atom#20074] opened 2019-10-27 10:22 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 19.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 174
Error: Cannot call function 'getPosition' on missing remote object 174
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 174
Error: Cannot call function 'getPosition' on missing remote object 174
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705395)
    at AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705810)
    at WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -3:41.2.0 Python run: run-f6 (input.hidden-input)
     -2:38.7.0 core:backspace (input.hidden-input)
     -2:36.6.0 core:save (input.hidden-input)
     -2:35.3.0 Python run: run-f6 (input.hidden-input)
  2x -2:15.5.0 core:backspace (input.hidden-input)
     -1:44.3.0 core:save (input.hidden-input)
     -1:43.8.0 Python run: run-f5 (input.hidden-input)
 11x -1:27.6.0 core:backspace (input.hidden-input)
  6x -0:58.4.0 core:move-right (input.hidden-input)
     -0:56.6.0 core:backspace (input.hidden-input)
  6x -0:53.6.0 core:move-left (input.hidden-input)
     -0:49.7.0 core:save (input.hidden-input)
     -0:49.2.0 Python run: run-f6 (input.hidden-input)
  5x -0:29 core:backspace (input.hidden-input)
     -0:13.8.0 core:save (input.hidden-input)
     -0:13.3.0 Python run: run-f6 (input.hidden-input)
```

### Non-Core Packages

```
atom-i18n 0.21.0 
atom-material-syntax 1.0.8 
atom-python-run 0.9.7 
highlight-selected 0.16.0 
kite 0.174.0 
linter 2.3.1 
linter-spell 0.15.0 
linter-ui-default 1.8.0 
pigments 0.40.2 
```

**Comment by rsese** [comment] 2019-11-04 04:48
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

If the error is reproducible for you, please us know the steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).  It would also be helpful to know if you can reproduce with the current stable [Atom release](https://atom.io/latest) which is running Electron 4.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-04 04:48 UTC
