### ISSUE TITLE
Atom freezing when opening minified JS files with all content on one line

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#8037] opened 2015-07-23 02:29 UTC
I have some minified JS files which are ~250kb in size, but all the code is concatenated onto one line. Opening files like this freezes up Atom and triggers the "Editor is not responding" window.

It's interesting, because I read in another issue that Atom had no problem opening files with millions of lines and tens of megabytes.

Is there something about all the content being on one line that makes performance suffer?

The google chrome developer console doesn't seem to have any issues displaying or even prettifying the minified JS files.

**Comment by mnquintana** [comment] 2015-07-23 02:47
Duplicate of https://github.com/atom/atom/issues/979 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-23 02:47 UTC

**Comment by adambuczynski** [comment] 2015-07-23 02:50
Ok thanks, will subscribe there. I think I couldn't find that issue because it was locked.

**Comment by erroid** [comment] 2016-10-29 11:08
same here, atom freeze on minified.js (278kb) -.-

**Comment by Dadaismu5** [comment] 2017-02-27 22:51
Solutions? :(

**Comment by 50Wliu** [comment] 2017-02-27 23:02
@Dadaismu5 Download Atom 1.15.0-beta3.

**Comment by rsese** [comment] 2017-02-27 23:02
> Solutions? :(

@Dadaismu5 - as mentioned in https://github.com/atom/atom/issues/979#issuecomment-280765029, this particular issue with minified JS files should be fixed in Atom 1.15.0 and the fix is also available now in the current beta 1.15.0-beta3.

**Comment by rflmyk** [comment] 2017-03-03 13:21
+1

**Comment by tinny77** [comment] 2017-03-06 08:48
+1

**Comment by aherman** [comment] 2017-03-09 23:18
+1

**Comment by ferrao** [comment] 2017-04-26 15:32
+1, i still have this issue with v1.16.0

**Comment by indrakaw** [comment] 2017-05-18 02:09
+1, same here.

I wish Atom has safe-mode startup so I can disable most of plugin then minimalize it. At least.

**Comment by 50Wliu** [comment] 2017-05-18 02:17
@indrakaw You are on a very outdated Atom version - the current Atom version is 1.17.0.  In addition, Atom _does_ have a safe mode: start Atom using `atom --safe`.

**Comment by indrakaw** [comment] 2017-05-18 02:21
@50Wliu I know, right. Here's my version after updated.
```
$ atom -v                              
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
Thanks for respond, btw.
