### ISSUE TITLE
Atom remove Projects folder when opening files from context menu

### ISSUE THREAD

**Issue by paper9oll** [atom/atom#9944] opened 2015-12-04 13:35 UTC
Atom keep removing my projects folder whenever i tried to open a files through context menu "Open with Atom" or by double clicking the file (associated with Atom, as in Atom is the default program for the particular file format).

**Comment by amytruong** [comment] 2015-12-04 16:24
Hi! Can you clarify if you're on Windows or Mac? And what version? I'd like to try and reproduce it if I can so I just need some more information. :smile: 
Also, can you reproduce the problem in safe mode by any chance?

**Comment by paper9oll** [comment] 2015-12-05 07:34
Oh Hi!
I'm currently using Mac, previously using Windows 10.
What version (not sure what you asking) - Atom is 1.2.4 and OS X is latest.
To try to reproduce you can open Atom > add some projects folder like 2 folder project (different directory will do) > open some openable files like .txt file or any other that can be view by Atom > head to desktop or anywhere create a .txt files or any files like .html etc. if you like > right click the file "Open with Atom" (for Windows) or double click to open it (for OS X, only with Atom is the default program to open the particular file).

I am not sure how to reproduce the problem in safe mode.

**Comment by 50Wliu** [comment] 2015-12-05 21:20
> I am not sure how to reproduce the problem in safe mode.

Open Atom from the Terminal using `atom --safe`.

**Comment by amytruong** [comment] 2015-12-07 18:46
I haven't been able to reproduce this on mac or windows. I am on Windows 8.1 however so I will grab a windows 10 machine later and try there as well.

**Comment by paper9oll** [comment] 2015-12-08 02:04
@amytruong when you reproduce this problem, did you close Atom before right click "Open with Atom" on Windows or double click to open the files on OS X?

**Comment by 50Wliu** [comment] 2015-12-08 03:00
I can reproduce this.  My previous project folder is removed and replaced with just the file itself that pretends to be a folder (though that's another bug - atom/tree-view#471).  When opening a folder through "Open with Atom" the previous project still gets removed and replaced by the new folder.

On the other hand, I'm almost 100% sure that this is a duplicate.

**Comment by paper9oll** [comment] 2015-12-08 03:38
@50Wliu may i know which issue this issue duplicate, can i have a link to that issue.

Thanks you

**Comment by 50Wliu** [comment] 2015-12-08 15:03
@paper9oll found it: this is a duplicate of #9643; please subscribe there for updates!

**Closed by 50Wliu** 2015-12-08 15:03 UTC
Labels: more-information-needed, needs-reproduction
