### ISSUE TITLE
atom binary: Open all folders in one window

### ISSUE THREAD

**Issue by jmagnusson** [atom/atom#5254] opened 2015-01-25 23:30 UTC
E.g. running:

```shell
$ atom /usr/local/etc/supervisor/conf.d/ /usr/local/etc/nginx/conf.d
```

Should open just one window with both these folders in one window, like sublime. At least I would love to see that.

(I also miss being able to use `Cmd-Shift-F` for searching the opened folder, even when it's not an actual project. Is there another way?)

**Comment by 50Wliu** [comment] 2015-01-26 00:38
Duplicate of #770, please subscribe there for updates.

**Closed by 50Wliu** 2015-01-26 00:38 UTC

**Comment by benogle** [comment] 2015-01-26 19:25
> (I also miss being able to use Cmd-Shift-F for searching the opened folder, even when it's not an actual project. Is there another way?)

Im not dont understanding this. Can you write out some steps to describe what it does, and what you want it to do? It would be best if you made an issue on https://github.com/atom/find-and-replace/issues/new explaining what you wanted cmd-shift-f to do.
