### ISSUE TITLE
Comment blocks indentation changes incorrectly on move line up/down command

### ISSUE THREAD

**Issue by Winters1260** [atom/atom#15098] opened 2017-07-26 12:59 UTC
When you have a standard code comment block like this:
```
/**
 * Some comment
 */

```
and then use the move line up/down command (CTRL + UP for me), it re-indents the lines but not correctly as it displays like this: 
```
/**
* Some comment
*/

```

I know this is a really small issue but it would be really nice if it could be fixed.

I'm using ATOM 1.19.05 beta on Windows 10

**Comment by rsese** [comment] 2017-07-26 22:04
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/10524 so you can subscribe there for updates if you'd like.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

---

On a separate note, the issue template is super helpful for us when going through issues so if you can fill that out for future issues, that would be great.

**Closed by rsese** 2017-07-26 22:04 UTC
