### ISSUE TITLE
Projects no longer in one window using separate tabs.

### ISSUE THREAD

**Issue by kopepasah** [atom/atom#15253] opened 2017-08-11 07:28 UTC
Prior to Atom 1.18, projects used to open in the same window, using tabs (not file tabs, but window tabs). While I did skip 1.18 version and went directly to 1.19, this feature also seems to have been removed. Was this an explicit removal or an unintended bug?

### Steps to Reproduce

1. Open a project. 
2. Using recent project (or the other package), try to open a another project.

**Expected behavior:**

Expected project to open in the same window, using window tabs.

**Actual behavior:**

Project opens in new window completely.

**Reproduces how often:**

100%

### Versions

Affects 1.18+

**Comment by yubaoquan** [comment] 2017-08-11 08:18
Here is a temp solution:  https://github.com/atom/atom/issues/15202#issuecomment-321714795

**Comment by Ben3eeE** [comment] 2017-08-11 08:25
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15202. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-11 08:25 UTC
Labels: duplicate
