### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/ash/src/xxx/xxx/project.json'

### ISSUE THREAD

**Issue by ashmckenzie** [atom/atom#4852] opened 2015-01-05 23:26 UTC
[Enter steps to reproduce below:]

1. Change git branch

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/ash/src/xxx/xxx/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/ash/src/xxx/xxx/project.json'
  at Error (native)

```

### Commands

```
     -5:00.1 find-and-replace:focus-next (atom-text-editor.editor.mini.json)
     -4:59.7 core:paste (atom-text-editor.editor.mini.json)
     -4:58.9 core:move-left (atom-text-editor.editor.mini.json)
  2x -4:58.6 core:backspace (atom-text-editor.editor.mini.json)
  2x -3:54.1 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
  2x -3:53.7 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode)
     -3:52.1 settings-view:open (atom-text-editor.editor.vim-mode.command-mode)
     -3:23.3 minimap:toggle-git-diff (li.active)
  2x -1:26.3 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode)
     -1:25.7 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode)
     -1:24.5 core:confirm (atom-text-editor.editor.mini)
     -1:24.5 open-in-sourcetree:open (atom-text-editor.editor.vim-mode.command-mode)
     -0:27.6 find-and-replace:show (atom-text-editor.editor.mini.json)
     -0:27.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:27.3 core:cancel (atom-text-editor.editor.mini)
     -0:00.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-spark-core"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "fontFamily": "DejaVu Sans Mono",
    "fontSize": 12,
    "lineHeight": 1.5,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
color-picker, v1.2.6
file-icons, v1.4.4
git-tab-status, v1.3.0
highlight-line, v0.9.2
highlight-selected, v0.7.0
jsonlint, v0.4.0
language-arduino, v0.2.1
linter, v0.9.1
linter-rubocop, v0.2.1
linter-ruby, v0.1.4
minimap, v3.5.0
minimap-color-highlight, v3.1.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.0
minimap-highlight-selected, v3.1.0
minimap-selection, v3.1.0
open-in-sourcetree, v0.1.0
pretty-json, v0.3.1
save-session, v0.11.2
vim-mode, v0.22.0

# Dev
No dev packages
```

**Comment by PavelVanecek** [comment] 2015-01-06 14:29
Same happens to me.
### Config

```json
{
  "core": {
    "disabledPackages": [
      "error-status"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 14,
    "showInvisibles": true,
    "showIndentGuide": true,
    "autoIndentOnPaste": false,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "scrollPastEnd": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.4.0
autoclose-html, v0.13.0
autocomplete-plus, v1.1.0
coffee-compile, v0.8.4
color-picker, v1.2.6
css-color-highlighting, v0.2.4
editorconfig, v0.2.3
emmet, v2.3.0
file-icons, v1.4.4
highlight-line, v0.9.2
highlight-selected, v0.7.0
language-ejs, v0.1.0
language-jade, v0.3.0
language-latex, v0.4.1
language-r, v0.1.1
minimap, v3.5.0
minimap-color-highlight, v3.1.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.0
minimap-highlight-selected, v3.1.0
monokai, v0.9.0
pretty-json, v0.3.1
preview-tabs, v0.1.6
save-session, v0.11.2
ssh-config, v0.10.0
view-tail-large-files, v0.1.6

### Commands 1

```
  3x -0:42.6 core:save (atom-text-editor.editor)
     -0:00.4 core:move-down (atom-text-editor.editor.is-focused)
     -0:00.0 editor:move-line-up (atom-text-editor.editor.is-focused)
```

### Commands 2

```
  3x -0:43.9 core:save (atom-text-editor.editor)
     -0:01.6 core:move-down (atom-text-editor.editor.is-focused)
     -0:01.2 editor:move-line-up (atom-text-editor.editor.is-focused)
     -0:00.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
```

### Commands 3

```
  3x -0:45.1 core:save (atom-text-editor.editor)
     -0:02.9 core:move-down (atom-text-editor.editor.is-focused)
     -0:02.4 editor:move-line-up (atom-text-editor.editor.is-focused)
     -0:01.2 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:00.0 editor:newline-below (atom-text-editor.editor.is-focused)
```

**Comment by kevinsawicki** [comment] 2015-01-06 17:56
I believe this is a duplicate of https://github.com/atom/atom/issues/4854

**Closed by kevinsawicki** 2015-01-06 17:56 UTC

**Comment by benogle** [comment] 2015-01-06 18:31
mpeterson2/save-session#43
