### ISSUE TITLE
[WHEN] Linux 32-bit ?

### ISSUE THREAD

**Issue by dogukanservi** [atom/atom#12224] opened 2016-07-23 23:26 UTC
**I'm waiting for Linux 32-bit version.**

# 

> WHEN ?

**Comment by 50Wliu** [comment] 2016-07-23 23:32
Duplicate of #6252.

**Closed by 50Wliu** 2016-07-23 23:32 UTC

**Comment by dogukanservi** [comment] 2016-07-24 11:39
@50Wliu "Thank you!"
