### ISSUE TITLE
Uncaught Error: spawn /Users/arash/Desktop/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/...

### ISSUE THREAD

**Issue by arashnamvar** [atom/atom#11100] opened 2016-03-08 15:09 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/arash/Desktop/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/arash/Desktop/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/arash/Desktop/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/arash/Desktop/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (/Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (/Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:15:15)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:170:22)
    at /Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at /Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:869:41
    at EventEmitter.<anonymous> (/Users/arash/Desktop/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -3:14.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -3:14.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:17.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:06.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:05.8.0 core:paste (atom-text-editor.editor.is-focused)
  3x -2:05.1.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -1:49.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:42.2.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  2x -1:41.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:41 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -1:39.4.0 core:undo (atom-text-editor.editor.is-focused)
     -1:38.5.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  3x -1:38 core:save (atom-text-editor.editor.is-focused)
     -0:26.3.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:10.9.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -0:08.9.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-03-08 15:37
This is a duplicate of #10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-08 15:37 UTC
