### ISSUE TITLE
Failed to activate the find-and-replace package

### ISSUE THREAD

**Issue by jeffdorchester** [atom/atom#7304] opened 2015-06-16 21:44 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the find-and-replace package

```
At ENOENT: no such file or directory, open '/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar'

Error: ENOENT: no such file or directory, open '/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar'
  at Error (native)
  at fs.openSync (fs.js:544:18)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:402:12)
  at Object.loadFile [as .js] (/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/src/babel.js:138:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at CommandRegistry.handleCommandEvent (/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Users/jeffdorchester/Library/Application Support/com.github.atom.ShipIt/update.VYADDCy/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:00.1.0 project-find:show (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "angularjs-snippets",
      "SFTP-deployment"
    ]
  },
  "editor": {
    "invisibles": {},
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-17 12:14
Thanks for the report, @jeffdorchester. :bow: 

@kevinsawicki Any ideas what happened here?

**Comment by kevinsawicki** [comment] 2015-06-17 15:26
> Any ideas what happened here?

No idea, the app running out of `/com.github.atom.ShipIt/` is pretty weird

**Comment by jeffdorchester** [comment] 2015-06-17 15:29
I was able to get it to work after a relaunch of atom.

Figured I would share the report when I saw the error.

Thank you for your support and great product!

**Comment by kevinsawicki** [comment] 2015-07-31 16:34
I believe this is a duplicate of https://github.com/atom/atom/issues/6604

**Closed by kevinsawicki** 2015-07-31 16:34 UTC
