### ISSUE TITLE
the sock isn't work

### ISSUE THREAD

**Issue by wggwcn** [atom/atom#14962] opened 2017-07-06 05:38 UTC
Uncaught Error: tunneling socket could not be established, statusCode=503
stream.js:74
Hide Stack Trace
Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (C:\Users\Administrator\AppData\Local\atom\app-1.18.0\resources\app\node_modules\tunnel-agent\index.js:166:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)

**Comment by rsese** [comment] 2017-07-20 23:13
Thanks for reaching out!

In addition to filling out the template as mentioned below, this also looks like a duplicate of https://github.com/atom/atom/issues/14008 based on the error and some people there have mentioned it's not reproducible.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Closed by rsese** 2017-07-20 23:13 UTC
