### ISSUE TITLE
[Keybindings] alt-g conflicts with osx qwertz keyboard

### ISSUE THREAD

**Issue by Badisi** [atom/atom#10908] opened 2016-02-19 21:16 UTC
Atom's keybindings prevents at sign (alt-g) to be used on osx qwertz keyboard (= switzerland)

![image](https://cloud.githubusercontent.com/assets/674862/13189175/17a7552c-d756-11e5-9db7-d6fbcd6e51c0.png)

**Comment by 50Wliu** [comment] 2016-02-19 21:20
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.  As a workaround you can try installing the [keyboard-localization](https://atom.io/packages/keyboard-localization) package.

**Closed by 50Wliu** 2016-02-19 21:20 UTC
