### ISSUE TITLE
Syntax highlighting taking 30+ seconds

### ISSUE THREAD

**Issue by mcanas** [atom/atom#8345] opened 2015-08-12 16:04 UTC
Atom hangs seemingly on application of syntax color scheme

To reproduce:
- On Atom v1.0.6 with no community themes or packages installed
- Download and open http://code.jquery.com/jquery-1.11.3.min.js

Timeline:
![screen shot 2015-08-12 at 11 59 37 am](https://cloud.githubusercontent.com/assets/1584732/9229142/ad516828-40e9-11e5-9105-3088213391f7.png)

**Comment by mnquintana** [comment] 2015-08-12 16:07
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/979 – mind commenting there with this Timeline screenshot?

**Closed by mnquintana** 2015-08-12 16:07 UTC

**Comment by mcanas** [comment] 2015-08-12 16:12
#979 is locked.

**Comment by mnquintana** [comment] 2015-08-12 16:21
@mcanas Sorry about that - I'll unlock it briefly so you can comment
