### ISSUE TITLE
Partial selection is left behind

### ISSUE THREAD

**Issue by demisx** [atom/atom#5243] opened 2015-01-24 19:44 UTC
_(I am able to reproduce this in safe mode in latest Atom 0.175.0)_

Not always, but quiet often, I have partial selection left behind when I select a portion of code on one line and then start typing hoping to replace the selected chars. When I type my first char, this causes selection jump to the characters on the right and they get deleted when I type the second char. For example, I have this `test.js` file:

```js
  var where = _.pick({
    classified_id: query.classId,
    section_id: query.secId,
    category_id: query.catId
  }, function(val, key) {
    console.log('  **** val:', val);
    console.log('  **** key:', key);
    return !_.isUndefined(val);
  });
```

To replicate:
1. Select a portion of code on any line with a mouse or a touchpad. Release the mouse button.
1.  Switch to keyboard and press the space bar
1. You should see that the selected chars were deleted, but some of the chars on the right are selected now too. 
1. Press space bar again, and those extra selected chars get deleted
1. Do steps 1 and 2 a few times if you can't replicate it on first time.

This is a real pain since I always have to do `Command + Z` to undo  these side effects. Sometimes, I don't notice it and my code no longer runs.

**Comment by mnquintana** [comment] 2015-01-24 20:09
I can reproduce it 100% of the time with these steps:
1. Select a portion of code on any line with the mouse, but don't release the mouse button
2. Press space bar
3. Extra chars get selected

Basically, this only seems to happen if you don't release the mouse button before you enter new text (which is probably why it was only sporadic for you).

(Related to or duplicate of #5200)

**Atom:** 0.175.0
**OS:** OS X 10.10.1
Reproduced in safe mode

**Comment by demisx** [comment] 2015-01-24 21:17
@mnquintana No, it has nothing to do with not releasing the mouse button. I do select the text first (via Mac touchpad, if that matters), then move on to my keyboard and start typing. So, there is plenty of time in between. I'll modify the original steps to make this more clear.

**Comment by stervo4ka** [comment] 2015-01-25 02:53
It's not exactly what I've observed (and described in #5200). Here's said that some text after the space becomes selected, while I got the space itself being selected. But probably these are some random variations of the same bug.
Also I'd like to confirm that typing while not releasing the mouse button is not the case.

**Comment by sethlopezme** [comment] 2015-08-13 16:22
It appears that this issue is still present in the latest version of Atom (1.0.7). I can confirm that this happens at random times, whether text was selected by the mouse or with the text cursor. It's a pretty annoying bug because there isn't really any way to predict when it is going to happen.

**Comment by demisx** [comment] 2015-08-13 19:29
Yes, and this issue is still present in the latest Chrome browser. Perhaps, Atom has inherited it?

**Closed** 2015-08-19 20:13 UTC
Labels: bug
