### ISSUE TITLE
Changing between Fuzzy File Opener & Command Palette puts cursor on editor

### ISSUE THREAD

**Issue by pixelarbeit** [atom/atom#16264] opened 2017-11-23 13:20 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Not sure whether this belongs to fuzzy file opener or command palette. But it appears in both plugins, probably because they are using the same function for displaying the overlay.

When changing between fuzzy file opener and command palette the cursor jumps into the editor.

![behaviour.gif](https://user-images.githubusercontent.com/22632550/33174929-4071512a-d05a-11e7-9e19-fb183303fd2b.gif)

### Steps to Reproduce

1. Open Fuzzy File Finder (Ctrl + P)
2. Without closing directly switch to Command Palette (Ctrl + Shift + P)

or vice versa

**Expected behavior:** Cursor appears in Command Palette Input.

**Actual behavior:** Cursor jumps into editor, writing text into your code.

**Reproduces how often:** 100%

### Versions

Atom    : 1.23.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.10
npm  3.10.10
node 6.9.5 x64
atom 1.23.0-beta1
python 3.6.3
git 2.13.0.windows.1
visual studio

OS: Windows 10

**Comment by rsese** [comment] 2017-11-24 08:59
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14325. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-24 08:59 UTC
