### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 108.171.129.13...

### ISSUE THREAD

**Issue by weud** [atom/atom#14069] opened 2017-03-27 05:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 108.171.129.132:8080

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 108.171.129.132:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:42.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-monokai.theme-monokai-tweaked-ui)
     -1:37.6.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -1:17.9.0 editor:move-to-previous-subword-boundary (input.hidden-input)
     -1:17.5.0 editor:move-to-next-subword-boundary (input.hidden-input)
     -1:14.7.0 intentions:highlight (input.hidden-input)
  7x -1:14.5.0 pane:show-next-recently-used-item (input.hidden-input)
     -1:11.4.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -1:11 intentions:highlight (input.hidden-input)
     -1:10.9.0 pane:show-next-recently-used-item (input.hidden-input)
     -1:10.8.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -1:10.3.0 intentions:highlight (input.hidden-input)
     -1:10.3.0 pane:show-next-recently-used-item (input.hidden-input)
     -1:10.2.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -1:09.8.0 intentions:highlight (input.hidden-input)
     -1:09.8.0 pane:show-next-recently-used-item (input.hidden-input)
     -1:09.6.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
atom-monokai 0.10.9 
atom-nodejs-snippets 1.5.0 
autoclose-html 0.23.0 
autocomplete-modules 1.6.8 
bezier-curve-editor 0.7.2 
busy-signal 1.3.0 
emmet 2.4.3 
file-icons 2.1.1 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-snippets 1.2.1 
linter 2.1.2 
linter-jshint 3.0.3 
linter-ui-default 1.2.1 
linter-write-good 0.8.0 
monokai 0.22.0 
monokai-slate 0.6.0 
monokai-tweaked-ui 0.3.0 
platformio-ide-terminal 2.5.0 
set-syntax 0.3.2 
terminal-plus 0.14.5 
```

**Comment by rsese** [comment] 2017-03-27 16:50
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14056 (the stack traces are identical). You may want to subscribe there for updates but if you could also answer a few questions in that issue, that could be helpful:

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-27 16:50 UTC
