### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.32.1\data.json'

### ISSUE THREAD

**Issue by Moosieus** [atom/atom#18410] opened 2018-11-08 20:10 UTC
Reproduction Steps:

1. Open a .zip file with WinRAR
2. Attempt to drag a file from within WinRAR to Atom's project folder view
3. Error thrown, file not copied, Atom requested issue be generated

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Education
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Cameron\AppData\Local\atom\app-1.32.1\data.json'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\Cameron\AppData\Local\atom\app-1.32.1\data.json'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:916506)
    at TreeView.t.exports.TreeView.onDrop (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:922390)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:896171)
```

### Commands

```
None
```

### Non-Core Packages

```
language-cpp14 0.6.2 (disabled)
language-graphql 0.11.0 (enabled)
language-vue 0.23.1 (enabled)
```

**Comment by rsese** [comment] 2018-11-08 20:37
Thanks for the report!

We noticed that based on the stack trace, this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

I'll copy over your repro steps however, thanks for those.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-08 20:37 UTC
