### ISSUE TITLE
Uncaught Error: target of repeat operator is not specified

### ISSUE THREAD

**Issue by vscosta** [atom/atom#5472] opened 2015-02-09 23:40 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: target of repeat operator is not specified

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:31

Error: target of repeat operator is not specified
  at Error (native)
  at Scanner.module.exports.Scanner.createScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:31:24)
  at Scanner.module.exports.Scanner.getScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:37:31)
  at Scanner.module.exports.Scanner.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:56:22)
  at Rule.module.exports.Rule.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:101:28)
  at Rule.module.exports.Rule.getNextTokens (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:143:21)
  at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:125:39)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:432:28)
  at TokenizedBuffer.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:380:31)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLinesForRows (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:388:10)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:340:32)
  at /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:56:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:594:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:74:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.abortTransaction (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:165:24)
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:122:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1181:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:141:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -6:27.3 editor:consolidate-selections (input.hidden-input)
     -6:27.3 core:cancel (input.hidden-input)
     -4:39.4 editor:newline (input.hidden-input)
     -1:49.4 core:backspace (input.hidden-input)
     -1:48.4 core:save (input.hidden-input)
     -0:57.7 application:open (input.hidden-input)
     -0:28.7 core:confirm (input.hidden-input)
  2x -0:24.9 core:paste (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter-clang"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "tabLength": 4,
    "softWrap": true,
    "useShadowDOM": false,
    "invisibles": {},
    "zoomFontWhenCtrlScrolling": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v2.5.5
atomic-emacs, v0.4.0
autocomplete-bibtex, v0.4.1
autocomplete-clang, v0.6.1
color-picker, v1.4.4
doxygen, v0.0.0
file-icons, v1.4.8
language-cmake, v0.1.1
language-latex, v0.4.1
language-llvm, v0.1.0
language-prolog, v0.9.0
latex, v0.18.0
linter, v0.11.1
linter-bootlint, v0.0.3
minimap, v4.1.3
tag, v0.2.3
term2, v0.9.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-02-10 00:56
Could you please try to reproduce this in safe mode (`atom --safe`)?

**Comment by benogle** [comment] 2015-02-10 18:44
What was the language of the file that was open? Looks like maybe an issue with the language grammar.

**Comment by vscosta** [comment] 2015-02-10 19:29
Hi

I am sorry I couldn't repeat it yesterday. It was Prolog.

**Comment by izuzak** [comment] 2015-02-11 10:45
The error is thrown from oniguruma:

https://github.com/atom/node-oniguruma/blob/bc9e854d8911187285cc5a6952fe8dcb1cca70b7/deps/onig/regerror.c#L98

I'm guessing a bad regex was constructed and passed to oniguruma for tokenizing a line, by one of the language packages you installed (language-prolog most probably, because you were editing a prolog file). Running Atom in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode) should fix this if you manage to reproduce it.

@benogle I'm not sure if it's possible that Atom somehow caused a bad regex to be created? Also, would we consider somehow catching these errors and throwing them again, but with more context (e.g. the regex or rule name which was caused the problem)?

**Comment by benogle** [comment] 2015-02-11 18:49
I assume it's a bad regex in from the grammar. 

> Also, would we consider somehow catching these errors and throwing them again, but with more context (e.g. the regex or rule name which was caused the problem)?

Yes, I like this idea.

@vscosta can you paste in the file you were working with so we can reproduce?

**Comment by vscosta** [comment] 2015-02-15 03:39
Sorry fir the delay. Try ypp.yap. Also, please notice I have made minor adjustments to the package (likr .yap)

=========================================================================
%
% YPP: Yap PreProcessing
%
% Author: Nuno Fonseca (nunofonseca@acm.org)
% Date: 2005-05-14
% $Id: ypp.yap,v 1.4 2006-03-07 17:30:47 tiagosoares Exp $
%
%====================================================================================

%====================================================================================
% Module declarations
%====================================================================================

:-module(ypp,[
	      ypp_state/1,	% ypp_state(on|off)
	      ypp_define/2,     % persistent defines  ypp_define(+NAME,VALUE)
	      ypp_undefine/1,   % persistent defines  ypp_undefine(+NAME)
	      ypp_extcmd/1,	% ypp_extcmd(?command)
	      ypp_consult/1,    % similiar to standard consult but with preprocessing
	      ypp_reconsult/1
    ]
    ).
%====================================================================================
% Public Predicates
%====================================================================================

ypp_state(State):-
	ground(State),!,
	set_state(State).

ypp_state(State):-
	get_state(State),
	!.

ypp_define(Name,Value):-
	ground(Name),ground(Value),
	store_define(Name,Value).

ypp_undefine(Name):-
	ground(Name),
	del_define(Name).

ypp_extcmd(Cmd):-
	ground(Cmd),!,
	eraseall('____ypp_extcmd'),
	recorda('____ypp_extcmd',Cmd,_).
ypp_extcmd(Cmd):-
	\+ ground(Cmd),
	recorded('____ypp_extcmd',Cmd,_).

ypp_consult(File):-
	(get_state(on)->ypp_file(File,NFile);NFile=File),
	consult(NFile).

ypp_reconsult(File):-
	(get_state(on)->ypp_file(File,NFile);NFile=File),
	reconsult(NFile).
%====================================================================================
% Private Predicates
%====================================================================================

set_state(on):-set_value('____ypp_state',1).
set_state(off):-set_value('____ypp_state',0).

get_state(State):-
	get_value('____ypp_state',Val),
	(Val==0->State=off;State=on).


store_define(Name,_Value):-
	recorded('___ypp',def(Name,_),Ref),     
        erase(Ref),     
        fail.
store_define(Name,Value):-
	system_variable( Name ),        
	environ( Name, Value ),
	fail.
store_define(Name,Value):-
	recordz('___ypp',def(Name,Value),_),
	fail.
store_define(_Name,_Value).

system_variable( Name ).        
system_variable( Name ).        
system_variable( Name ).        
system_variable( Name ).        


del_define(Name):-
	(recorded('___ypp',def(Name,_),Ref)->erase(Ref);true),
	!.

%defines2string(-DefineString)
defines2string(S):-
	findall(d(Name,Val),recorded('___ypp',def(Name,Val),_),AllDefs),
	mergedefs(AllDefs,'-D',S),
	!.

mergedefs([],_,'').
mergedefs([d(Name,Val)|RDefs],Pref,S):-
	mergedefs(RDefs,Pref,S1),
	atom_concat([Pref,Name,'=',Val,' ',S1],S).


ypp_file(File,PPFile):-
	% ppfile
	atom_concat([File,'.ypp'],PPFile),
	% Cmdline
	defines2string(Defs),ypp_extcmd(Cmd),
	atom_concat([Cmd,' ',PPFile,' ',Defs,' ',File],Cmdline),
	write(Cmdline),nl,
%	current_module(M1,M2),
%	write(M1:M2),nl,
	system(Cmdline),
	!.

% initialization
:-set_state(on),
	ypp_extcmd('cpp -P -E -w -o ').
%	ypp_extcmd('gpp -o').

**Comment by izuzak** [comment] 2015-02-18 15:43
@vscosta I'm still having trouble reproducing this. Here's what I did:

1. installed the language-prolog package: https://atom.io/packages/language-prolog
2. saved the content you provided as ypp.yap
3. opened the file
4. switched the grammar used to parse the file to prolog

This did not throw an exception. Are you still able to reproduce the issue by following those steps or can you clarify what you're doing differently to trigger the error?

**Comment by Smokyish** [comment] 2016-09-27 08:24
I'm getting this error every time i switch language to Wordpress.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Linux Mint
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: target of repeat operator is not specified

```
At /usr/share/atom/resources/app.asar/node_modules/first-mate/lib/scanner.js:31

Error: target of repeat operator is not specified
    at Error (native)
    at Scanner.module.exports.Scanner.createScanner (/usr/share/atom/resources/app.asar/node_modules/first-mate/lib/scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (/usr/share/atom/resources/app.asar/node_modules/first-mate/lib/scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (/usr/share/atom/resources/app.asar/node_modules/first-mate/lib/scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (/usr/share/atom/resources/app.asar/node_modules/first-mate/lib/rule.js:99:28)
    at Rule.module.exports.Rule.getNextTags (/usr/share/atom/resources/app.asar/node_modules/first-mate/lib/rule.js:141:21)
    at Grammar.module.exports.Grammar.tokenizeLine (/usr/share/atom/resources/app.asar/node_modules/first-mate/lib/grammar.js:150:44)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:494:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:482:19)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:287:43)
    at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:264:26
    at /usr/share/atom/resources/app.asar/node_modules/underscore/underscore.js:666:47
```

### Commands

```
  2x -4:56.7.0 grammar-selector:show (atom-text-editor.editor)
     -4:39.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:39.5.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:33.8.0 core:undo (atom-text-editor.editor.is-focused)
  4x -4:32.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.9.0 grammar-selector:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "sync-settings",
      "linter-csslint",
      "linter-phpmd"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 13,
    "invisibles": {},
    "softWrapHangingIndent": 50
  }
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0 (active)
atom-beautify, v0.29.13 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-ethereum-interface, v0.1.0-0 (inactive)
atom-wordpress, v0.3.0 (active)
atom-wp-customizer, v0.1.0 (inactive)
autocomplete-java, v1.2.5 (inactive)
autocomplete-paths, v1.0.2 (active)
autocomplete-php, v0.3.7 (active)
autocomplete-solidity, v0.3.3 (active)
autocomplete-wordpress-hooks, v0.2.2 (active)
color-picker, v2.2.2 (active)
duplicate-removal, v0.1.3 (inactive)
file-icons, v1.7.19 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
java-class-complete, v0.0.6 (active)
java-generator, v2.2.0 (inactive)
java-importer, v1.4.1 (active)
javascript-snippets, v1.2.1 (active)
jshint, v1.8.6 (active)
language-ethereum, v0.3.9 (active)
language-lua, v0.9.11 (active)
language-tcl, v0.1.2 (active)
language-tcltk, v0.1.3 (active)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (inactive)
linter-eslint, v7.3.2 (active)
linter-htmlhint, v1.3.0 (active)
linter-javac, v1.9.4 (active)
linter-js-yaml, v1.2.5 (active)
linter-jshint, v3.0.0 (active)
linter-phpmd, v1.5.1 (inactive)
linter-scss-lint, v3.0.4 (active)
linter-solidity, v0.5.0 (active)
linter-tidy, v2.2.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-highlight-selected, v4.4.0 (active)
php-cs-fixer, v2.5.9 (active)
pigments, v0.35.1 (active)
project-manager, v3.2.3 (active)
react, v0.16.0 (active)
run-command2, v1.12.2 (inactive)
script, v3.10.1 (inactive)
seti-ui, v1.3.2 (active)
sort-lines, v0.14.0 (inactive)
sync-settings, v0.7.2 (inactive)
terminal-status, v1.6.8 (active)
trailing-spaces, v0.3.2 (active)
wordpress, v0.2.0 (active)
wordpress-api, v1.2.2 (active)
wordpress-dictionary, v4.4.0 (active)
wp-dev, v0.3.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ugyballoons** [comment] 2017-02-27 12:51
Same issue as Smokyish above, when switching language to Wordpress.

Atom: 1.13.1 (x64)
OS X 10.11.6

**Comment by 50Wliu** [comment] 2017-02-27 15:52
This is a bug in whatever grammar is tokenizing the file, so I'm closing this.  @ugyballoons you should report this to whatever package you're using for Wordpress.

**Closed by 50Wliu** 2017-02-27 15:52 UTC
Labels: more-information-needed, uncaught-exception
