### ISSUE TITLE
Atom fails on startup

### ISSUE THREAD

**Issue by gerbsen** [atom/atom#11479] opened 2016-04-15 07:47 UTC
Hello,
The editor is not starting anymore. All I see is this:

![screenshot 2016-04-15 09 44 34](https://cloud.githubusercontent.com/assets/1186245/14554667/b388d72c-02ee-11e6-8d0c-7b2162a10993.png)

I'm running OS X 10.11.4 (15E65) and already tried to reinstall Atom but nothing changed. My "Application Deleter Helper" from ForkLift also tried to remove the following folders/files:

![screenshot 2016-04-15 09 45 58](https://cloud.githubusercontent.com/assets/1186245/14554722/f6041d3c-02ee-11e6-9d0c-9d83db1a46e9.png)

It work yesterday. Then sleep and back at the laptop and it was broke. 
Cheers,
Daniel

**Comment by hvdklauw** [comment] 2016-04-15 08:14
I have the exact same issue, as a temporary fix start Atom from your terminal.

If normal `atom` doesn't work try this:
`~/Applications/Atom.app/Contents/Resources/app/atom.sh`

**Comment by gerbsen** [comment] 2016-04-15 12:27
Okay this works.. but it's extremely uncool... Is there a plugin directory which I could delete? I mean it should be possible to launch a clean install shouldn't it?

**Comment by niieani** [comment] 2016-04-15 13:23
Confirming the same same problem.
It seems ATOM_HOME is not being set when starting Atom.app.

**Comment by jamtur01** [comment] 2016-04-17 22:13
Looks to be a duplicate of #11190 ?

**Comment by 50Wliu** [comment] 2016-04-17 23:57
Thanks @jamtur01.

**Closed by 50Wliu** 2016-04-17 23:57 UTC
