### ISSUE TITLE
When expanding a directory in the navigation tree, if the only child is another directory, expand that as well

### ISSUE THREAD

**Issue by alex** [atom/atom#6787] opened 2015-05-14 19:32 UTC
It'd be awesome if the navigation tree did basically the same thing as github, letting you easily skip through multiple levels of nested trees. (This turns out to be a super common thing with Java code)

Cheers! :heart:

**Comment by 50Wliu** [comment] 2015-05-14 21:04
Duplicate of atom/tree-view#125, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-14 21:04 UTC
