### ISSUE TITLE
Can't input and display chinese words

### ISSUE THREAD

**Issue by sunjiesh** [atom/atom#6749] opened 2015-05-12 10:09 UTC
I get the source code and build atom.I can't input chinese and display chinese.I search the issues history.The similar issue is No6214.I setup the font family and install the support-gbk package,but it didn't work.
OS is Ubuntu 14.10.
LANG=en_US.UTF-8.
The version is 0.198.0-4f5e9b1.

**Comment by izuzak** [comment] 2015-05-12 11:15
@sunjiesh Can you clarify what "can't input chinese and display chinese" means? Does that mean that when you press a key on your keyboard nothing shows up, or something else? Can you take a screenshot of what you see which clearly demonstrates the problem? 

Also, which keyboard layout are you using and how are you inputing chinese characters? Which font did you try using and have you tried using some of the fonts suggested here: https://github.com/atom/atom/issues/6214#issuecomment-93603774 ?

**Comment by sunjiesh** [comment] 2015-05-13 01:05
Sorry my poor English.I mean when I input a  chinese word in atom,the atom display a small square block.I tried to set up the font family like Droid Sans Mono,but it doesn't work.I open a file which contains the chinese words and it also has the same problem.The following picture is the screenshot.
![screenshot - 05132015 - 08 54 25 am](https://cloud.githubusercontent.com/assets/3637706/7601836/8060249a-f94e-11e4-8392-4d24edcaeec6.png)

**Comment by vipjeffreylee** [comment] 2015-05-13 01:08
in styles.less add

html, body, .tree-view, .tab-bar .tab,.bottom{
  font-family:Droid Sans Mono, Droid Sans Fallback;
}

2015-05-13 9:05 GMT+08:00 Tom <notifications@github.com>:

**Comment by 50Wliu** [comment] 2015-05-13 01:49
Thanks for the extra information @sunjiesh!  This looks like a duplicate of #6214, so if you subscribe there, you'll receive any updates for your problem.

**Closed by 50Wliu** 2015-05-13 01:49 UTC
Labels: more-information-needed

**Comment by sunjiesh** [comment] 2015-05-13 06:29
I add some configuration  in styles.less (The file is in the ~/.atom/styles.less),but it doesn't work.
It's my styles.less file.
![screenshot - 05132015 - 02 28 16 pm](https://cloud.githubusercontent.com/assets/3637706/7604925/676a03ec-f97c-11e4-984e-bdcb7007ea66.png)

**Comment by izuzak** [comment] 2015-05-13 06:37
Can you try changing your font in the settings, rather than in styles.less? Atom > Preferences in the menu:

![screen shot 2015-05-13 at 08 36 54](https://cloud.githubusercontent.com/assets/38924/7605041/4775f0ea-f94b-11e4-8302-caea31a46e95.png)

**Comment by vipjeffreylee** [comment] 2015-05-13 07:45
@Tom
~/.atom/styles.less

.tree-view {
  font-size: 18px;
}

// style the background and foreground colors on the
atom-text-editor-element
// itself
atom-text-editor {
  font-family:Droid Sans Mono, Droid Sans Fallback;
}

// To style other content in the text editor's shadow DOM, use the ::shadow
// expression
atom-text-editor::shadow .cursor {

}

html, body, .tree-view, .tab-bar .tab,.bottom{
  font-family:Droid Sans Mono, Droid Sans Fallback;
}

2015-05-13 14:38 GMT+08:00 Ivan Žužak <notifications@github.com>:

**Comment by sunjiesh** [comment] 2015-05-13 08:21
atom-text-editor {
  font-family:Droid Sans Mono, Droid Sans Fallback;
}
I set up in ~/.atom/styles.less and it works.If only setup Droid Sans Mono and it doesn't work.So I know why it didn't work before.Thanks.
