### ISSUE TITLE
Uncaught #<Object>

### ISSUE THREAD

**Issue by RhinoRudi** [atom/atom#6089] opened 2015-03-25 11:48 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught #<Object>

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:128

undefined
```

### Commands

```
     -0:35.5 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 17
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.3.0
rhino-python, v0.6.1

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-04-13 16:31
@RhinoRudi Can you share more information on this -- which steps reproduce the problem for you? Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by RhinoRudi** [comment] 2015-04-13 19:03
I cannot, I use Atom to run Python scripts in Rhinoceros3D and this error
was a red box in build 0.77.

I will try to be more diligent in keeping info if i see one of these errors
when using Atom

RhinoRudi

**Comment by kevinsawicki** [comment] 2015-07-21 00:02
This isn't going to be possible to reproduce and fix given the stack trace provided, it looks like maybe a library or package threw an `Object` instead of an `Error` which is causing the issue somewhere but the stack trace is unavailable.

So I'm going to close this out until further details are available.

**Closed by kevinsawicki** 2015-07-21 00:02 UTC
Labels: more-information-needed, uncaught-exception
