### ISSUE TITLE
Release Note doesn't update

### ISSUE THREAD

**Issue by Negaihoshi** [atom/atom#5161] opened 2015-01-20 17:14 UTC
Atom Version: 0.174.0
OS: Windows 7 x64

My Atom Version is  0.174.0, but release note is always 0.158
![screanshot 181](https://cloud.githubusercontent.com/assets/1733006/5821938/b78c6024-a10a-11e4-8c1e-90ac974f02f7.png)

**Comment by postcasio** [comment] 2015-01-20 17:16
Duplicate of #3757

**Closed by postcasio** 2015-01-20 17:16 UTC
