### ISSUE TITLE
Creating a text editor and adding it to active pane with a long text results in a tab without a scrollbar

### ISSUE THREAD

**Issue by nukeop** [atom/atom#16925] opened 2018-03-10 14:03 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This bug occurs when using Atom's API programmatically, not by using it normally.
Using setText on a TextEditor with text exceeding window height results in a text editor without a scrollbar with no way to access off-screen contents (unless you select off-screen text and deselect it causing the buffer to jump to it. 

### Steps to Reproduce

1. Try the following snippet in your init script:
```javascript
let pane = atom.workspace.getActivePane();
let fileEditor = atom.workspace.buildTextEditor();
let item = pane.addItem(fileEditor);
pane.activateItem(item);
fileEditor.setText(content);
```

Where content is some very long string.

**Expected behavior:**

The created text editor that's added to the pane should come with a scrollbar.

**Actual behavior:** 
It has no scrollbar, as described above.

**Reproduces how often:** 
Always

### Versions
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

OS: Mint 18

### Additional Information

N/A

**Comment by rsese** [comment] 2018-03-12 18:16
Thanks for the report!  I can reproduce but I thinks this is a duplicate of https://github.com/atom/atom/issues/14811?  See https://github.com/atom/atom/issues/14811#issuecomment-309467775 and the summary in https://github.com/atom/atom/issues/14811#issuecomment-311849256.

As mentioned in that comment, this can be fixed with:

```
fileEditor = atom.workspace.buildTextEditor({autoHeight: false});
```

If I mis-understood anything let me know.

**Closed by rsese** 2018-03-12 18:16 UTC

**Comment by nukeop** [comment] 2018-03-12 19:13
Yeah that fixes the issue.
