### ISSUE TITLE
TODO, XXX, FIXME, etc not being highlighted with the new tree-sitter parser

### ISSUE THREAD

**Issue by prati0100** [atom/atom#18379] opened 2018-11-01 12:17 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Without tree-sitter, TODO, XXX, FIXME, etc in comments are highlighted. This is a convenient feature (at least for me). With tree-sitter, they are not highlighted. If it is technically feasible to highlight them with tree-sitter, then I would appreciate them.

I have only tried them in C and I don't know if they work in other languages or not.

### Steps to Reproduce

1. Use TODO, XXX, FIXME, etc in a comment.

**Expected behavior:** TODO should be highlighted
![atom without tree-sitter](https://user-images.githubusercontent.com/8817931/47851060-7c7f9300-ddfd-11e8-82da-01c96c9616b7.png)

**Actual behavior:** TODO is not highlighted
![atom with tree-sitter](https://user-images.githubusercontent.com/8817931/47851071-8a351880-ddfd-11e8-94d4-f16123c5ae92.png)

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

`atom --version`:
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

`apm --version`:
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.12
git 2.18.0

OS:
Ubuntu 16.04

Kernel:
Linux 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Ben3eeE** [comment] 2018-11-01 12:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-todo/issues/82. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-11-01 12:20 UTC
Labels: duplicate, wrong-repo
