### ISSUE TITLE
how about improving the performance of opening compiled js/css file?

### ISSUE THREAD

**Issue by yzhen333** [atom/atom#8379] opened 2015-08-14 05:39 UTC
when open the compiled js/css file, it takes too long and often crash, 
because of it's one line and soft wrap takes lots of time,
even worse, hightlighting will take more time.

how about just like sublime 3, only break several lines and don't hightlight anymore, no one would need  it in this case anyway. :)

![xshot-0005](https://cloud.githubusercontent.com/assets/5233940/9267910/d1e8a90c-4289-11e5-8163-7a05a4a7f323.png)

**Comment by thomasjo** [comment] 2015-08-14 06:12
This is a duplicate of #979.

**Closed by thomasjo** 2015-08-14 06:12 UTC
