### ISSUE TITLE
open new project as a tab NOT a new window?

### ISSUE THREAD

**Issue by huberyh** [atom/atom#15568] opened 2017-09-07 03:13 UTC
reproduce steps:
1. File -> Reopen Project

expect:
![expert](https://user-images.githubusercontent.com/19680716/30144337-2e563ec6-93bd-11e7-9d8d-fee08d413e0e.png)

actual:
![actual](https://user-images.githubusercontent.com/19680716/30144343-38010406-93bd-11e7-8b3e-a5a07c3b857f.png)

ATOM version: 1.19.6

I think it can work until two days ago, I'm not sure what happen to it?
BTW, I also set the System Preferences to 
![sss](https://user-images.githubusercontent.com/19680716/30144404-940c0354-93bd-11e7-857e-5079606e0762.png)

**Comment by yubaoquan** [comment] 2017-09-07 04:29
See issue #15202

**Comment by lee-dohm** [comment] 2017-09-07 15:30
Thank you for contributing!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13277. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

-----

Additionally, repeatedly opening duplicate issues is considered a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is considered harassment. You may consider this an official and final warning. If you continue in this fashion, you will be banned from the Atom project as well as other GitHub open source projects.

**Closed by lee-dohm** 2017-09-07 15:30 UTC
