### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bigblind** [atom/atom#4775] opened 2014-12-27 12:36 UTC
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

Not sure, actually.

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/task.js:95

TypeError: undefined is not a function
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app/src/task.js:95:27)
  at Task.module.exports.Task.start (/Applications/Atom.app/Contents/Resources/app/src/task.js:86:12)
  at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app/src/task.js:21:18)
  at GitRepository.module.exports.GitRepository.refreshStatus (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:392:37)
  at /Applications/Atom.app/Contents/Resources/app/src/git-repository.js:81:26

```

**Comment by CyberShadow** [comment] 2015-01-01 15:20
Getting a different stack trace here:

```
c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\src\window-event-handler.js:153
Hide Stack Trace
TypeError: undefined is not a function
  at HTMLDocument.<anonymous> (c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\src\window-event-handler.js:153:20)
  at HTMLDocument.handler (c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\Vladimir\AppData\Local\atom\app-0.165.0\resources\app\src\window-event-handler.js:167:20)
```

**Comment by francodacosta** [comment] 2015-01-06 16:25
here is my stack trace

```
TypeError: undefined is not a function
  at Config.module.exports.Config.getAll (/usr/local/share/atom/resources/app/src/config.js:189:57)
  at LanguageMode.module.exports.LanguageMode.toggleLineCommentsForBufferRows (/usr/local/share/atom/resources/app/src/language-mode.js:33:39)
  at TextEditor._results.push._this.(anonymous function) [as toggleLineCommentsForBufferRows] (/usr/local/share/atom/resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at Selection.module.exports.Selection.toggleLineComments (/usr/local/share/atom/resources/app/src/selection.js:658:68)
  at /usr/local/share/atom/resources/app/src/text-editor.js:1054:26
  at /usr/local/share/atom/resources/app/src/text-editor.js:781:27
  at History.module.exports.History.transact (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/local/share/atom/resources/app/src/text-editor.js:1150:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/local/share/atom/resources/app/src/text-editor.js:774:19)
  at TextEditor.module.exports.TextEditor.toggleLineCommentsInSelection (/usr/local/share/atom/resources/app/src/text-editor.js:1053:19)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:toggle-line-comments (/usr/local/share/atom/resources/app/src/text-editor-element.js:585:19)
  at /usr/local/share/atom/resources/app/src/text-editor-element.js:291:34
  at History.module.exports.History.transact (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/local/share/atom/resources/app/src/text-editor.js:1150:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/usr/local/share/atom/resources/app/src/text-editor-element.js:290:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/local/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/local/share/atom/resources/app/src/window-event-handler.js:167:20)
```

**Comment by gstack** [comment] 2015-01-06 16:39
/Applications/Atom.app/Contents/Resources/atom/renderer/lib/web-view.js:380
Hide Stack Trace
TypeError: undefined is not a function
  at WebView.handleBrowserPluginAttributeMutation (/Applications/Atom.app/Contents/Resources/atom/renderer/lib/web-view.js:380:62)
  at browserplugin.proto.attributeChangedCallback (/Applications/Atom.app/Contents/Resources/atom/renderer/lib/web-view.js:598:23)

happens after switching out of a tab containing the webview.

& also keyboard backspace doesn't work (maybe related to the guy above me?)

**Comment by abe33** [comment] 2015-01-10 00:02
Guys, `undefined is not function` is probably one of the most common issues in javascript history. If the source in the stack is different it should be filled as different issues.

**Comment by michaeljcalkins** [comment] 2015-01-14 22:29
```
Uncaught TypeError: undefined is not a function
/c:/Users/Michael%20J.%20Calkins/.atom/packages/atom-color-highlight/lib/marker-element.coffee:81
Hide Stack Trace
TypeError: undefined is not a function
  at color-marker.module.exports.MarkerElement.appendRegion (c:\Users\Michael J. Calkins\.atom\packages\atom-color-highlight\lib\marker-element.coffee:45:26)
  at color-marker.module.exports.MarkerElement.updateDisplay (c:\Users\Michael J. Calkins\.atom\packages\atom-color-highlight\lib\marker-element.coffee:31:8)
  at c:\Users\Michael J. Calkins\.atom\packages\atom-color-highlight\lib\marker-mixin.coffee:35:61
  at Emitter.module.exports.Emitter.emit (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:114:32
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\emitter.js:155:30
  at Array.forEach (native)
  at Behavior.module.exports.Emitter.emitSlow (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\emitter.js:154:47)
  at Behavior.module.exports.Emitter.emit (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\emitter.js:107:30)
  at Behavior.module.exports.Behavior.emit (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\behavior.js:44:38)
  at Behavior.module.exports.Signal.emitValue (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\emissary\lib\signal.js:82:19)
  at DisplayBuffer.module.exports.Model.set (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\theorist\lib\model.js:166:21)
  at DisplayBuffer.accessor.set (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\theorist\lib\model.js:57:23)
  at DisplayBuffer.module.exports.DisplayBuffer.setScrollTop (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\display-buffer.js:466:31)
  at TextEditor.module.exports.TextEditor.setScrollTop (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:2875:33)
  at [object Object].module.exports.React.createClass.onMouseWheel (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor-component.js:721:16)
  at HTMLDivElement.boundMethod (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\react-atom-fork\lib\ReactCompositeComponent.js:1295:21)
```

I opened a css file and started scrolling.  Editor froze and got this.

**Comment by shingonoide** [comment] 2015-01-21 09:10
:+1: to @abe33 explanation

**Comment by izuzak** [comment] 2015-02-10 13:59
Noticed again in https://github.com/atom/atom/issues/5478.

@bigblind can you reproduce the problem if you start Atom in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by carlosh2k4** [comment] 2015-03-06 21:24
I just installed Atom for the first time and tried to install the "language-batch" package to get syntax highlighting for *.bat files.
I got an error message that says "Compiler tools not found" in a red box. I get the TypeError any time I try to copy text from the red box using Ctrl+Insert. 

```
TypeError: undefined is not a function
  at HTMLDocument.<anonymous> (C:\Users\caha\AppData\Local\atom\app-0.186.0\resources\app\src\window-event-handler.js:168:20)
  at HTMLDocument.handler (C:\Users\caha\AppData\Local\atom\app-0.186.0\resources\app\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\caha\AppData\Local\atom\app-0.186.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\caha\AppData\Local\atom\app-0.186.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\caha\AppData\Local\atom\app-0.186.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\caha\AppData\Local\atom\app-0.186.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\caha\AppData\Local\atom\app-0.186.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\caha\AppData\Local\atom\app-0.186.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\caha\AppData\Local\atom\app-0.186.0\resources\app\src\window-event-handler.js:182:20)
```

**Comment by CyberShadow** [comment] 2015-03-06 21:26
> Guys, undefined is not function is probably one of the most common issues in javascript history. If the source in the stack is different it should be filled as different issues.

FYI, the built-in bug reporter seems to look for existing GitHub issues with the same exception string, which is why it directed me to this one.

**Comment by jaygriz** [comment] 2015-03-21 17:26
All I did was try and use the clip board, just installed a few days ago and have no real idea what I am doing.
Nice program tho...

**Comment by jaygriz** [comment] 2015-03-21 17:27
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\jhgjr\AppData\Local\atom\app-0.187.0\resources\app\src\window-event-handler.js:168

TypeError: undefined is not a function
  at HTMLDocument.<anonymous> (C:\Users\jhgjr\AppData\Local\atom\app-0.187.0\resources\app\src\window-event-handler.js:168:20)
  at HTMLDocument.handler (C:\Users\jhgjr\AppData\Local\atom\app-0.187.0\resources\app\src\space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\jhgjr\AppData\Local\atom\app-0.187.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\jhgjr\AppData\Local\atom\app-0.187.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jhgjr\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:246:29)
  at CommandRegistry.handleCommandEvent (C:\Users\jhgjr\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\jhgjr\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:159:19)
  at EventEmitter.<anonymous> (C:\Users\jhgjr\AppData\Local\atom\app-0.187.0\resources\app\src\window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -8:43.6 window:toggle-dev-tools (atom-text-editor.editor)
     -6:25.7 markdown-preview:toggle (atom-text-editor.editor)
     -2:18.1 styleguide:show (atom-text-editor.editor)
     -0:19.4 core:copy (div.styleguide.pane-item.native-key-bindings.padded)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "followSymlinks": true,
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "showInvisibles": true,
    "showIndentGuide": true
  }
}
```

### Installed Packages
this is the error


```coffee
# User
minimap, v4.6.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-07-07 00:43
This is really strange, the `send` function is missing on the `ChildProcess` instance which should always be there since it is part of the official API. I wonder if a package or library deleted it somehow.

I'm going to close this out since we've upgraded several node/io.js versions since this was last hit and also the package listing is missing from the issue body so recreating it with the same packages won't be possible.

**Closed by kevinsawicki** 2015-07-07 00:43 UTC
Labels: more-information-needed, uncaught-exception
