### ISSUE TITLE
I can't use JSON in the app Atom

### ISSUE THREAD

**Issue by InTheAirMC** [atom/atom#19520] opened 2019-06-13 04:20 UTC
I am using a Macbook, and I installed version 1.38.0 of the app. And I can't use JSON in it. I can use anything else like txt or py, but I can't use JSON

**Comment by Arcanemagus** [comment] 2019-06-13 04:34
Thanks for taking the time to contribute!

You didn't fill out the template, part of that being the OS, but I'm assuming you are on macOS as this sounds like a duplicate of https://github.com/atom/atom/issues/19497. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-06-13 04:34 UTC

**Comment by InTheAirMC** [comment] 2019-06-14 06:59
Oh, apologies. But anyways, it is now working again, so thank you very much.
