### ISSUE TITLE
Folder search result is not displayed 

### ISSUE THREAD

**Issue by djds4rce** [atom/atom#5214] opened 2015-01-22 15:38 UTC
Although a Message (x) Results present is shown the search results are not shown. This is after the latest update. 
![atom bug](https://cloud.githubusercontent.com/assets/350933/5858626/a9604738-a27a-11e4-9cb3-e6b0d0432e99.PNG)

**Comment by benogle** [comment] 2015-01-22 17:15
Does this happen every time you search in project? Please quit atom completely and run `atom --safe`. Is the issue still there?

For the record, I am not able to reproduce.

**Comment by mthadley** [comment] 2015-01-22 23:52
I'm seeing the same issue, but not while running atom in safe mode. I'm running version 0.175 on Ubuntu 14.10.

**Comment by carlosliu** [comment] 2015-01-23 02:53
It works fine in safe mode or disable all community packages. But I can reproduce the bug if I enable either "command-logger" or "hex" package. Probably, there are other packages trigger the same problem. (Version 0.175 on Windows 7)

**Comment by zephraph** [comment] 2015-01-23 04:35
Oddly enough I'm seeing this issue as well. 

I'm on Windows 8.1 with Atom 0.175. I haven't noticed this with my work computer (windows 7). 

![image](https://cloud.githubusercontent.com/assets/3087225/5869853/5e4557dc-a286-11e4-92a5-24a778934d6e.png)

I've got these packages installed: 
- highlight selected
- minimap
- minimap highlight selected

It does not happen on safe mode though.

**Comment by zephraph** [comment] 2015-01-23 04:41
Update: it seems to only happen when I have the minimap package installed. It may be a direct issue with that package.

**Comment by djds4rce** [comment] 2015-01-23 05:56
@zephraph I had Minimap installed but have uninstalled it but the issue still does not go away.

**Comment by djds4rce** [comment] 2015-01-23 05:59
Closing this for now and will add a issue in Mini map. Thanks guys.

**Comment by grizzilus** [comment] 2015-01-23 18:10
The `merge-conflicts` package is another that triggers this behavior (atom 0.175 linux version). So this isn't isolated to the `minimap` package.

**Comment by benogle** [comment] 2015-01-23 18:32
I'm going to reopen this until we figure out what is happening.

**Comment by grizzilus** [comment] 2015-01-23 18:38
A bit more information on this:

When this behavior is present, performing a project find results in the `Project Find Results` pane displaying `No results found for ""` at the top and the background `No Results` in the center.

If pane is closed and the same search perform a _second_ time, the pane says `13 results found in 7 files for ...` (which is the correct count) and the `No Results` no longer appears on the background (the pane content are empty).

So something is happening once the `Project Find Results

**Comment by zephraph** [comment] 2015-01-23 18:58
Feel free to check my comments on the [minimap issue](https://github.com/fundon/atom-minimap/issues/237) for the things I was experiencing on this as well.

**Comment by grizzilus** [comment] 2015-01-23 19:02
Also, this is OS dependent. I tried the same steps I mentioned above on OS X 10.10.2 and the project find has no issues.

**Comment by benogle** [comment] 2015-01-23 19:14
Cannot reproduce in osx. Trying windows...

**Comment by benogle** [comment] 2015-01-23 19:24
Reproduced in windows. Looking into it...

**Comment by benogle** [comment] 2015-01-23 19:51
Ok, looks like the space-pen `attached` and `detached` hooks are not firing. Find and replace is requiring space-pen-views (2.0.0) while merge-conflicts is requiring space-pen (5.0.1). Not sure how these interact. It _should_be fine. But, nope.

**Comment by benogle** [comment] 2015-01-23 21:11
It's loading the wrong version of space-pen when some packages (e.g. merge-conflicts) are enabled. It's loading the atom bundled space-pen (3.8.2). Passing to @kevinsawicki as he is the module cache guy

**Comment by idenkov** [comment] 2015-01-24 19:22
I can reproduce it on Ubuntu 14.04 64 and Atom 0.175
Another package that cause this bug is <a href="https://atom.io/packages/git-history">git-history</a>
With either of git-history or minimap I am getting the same bug.

**Comment by Swistaku** [comment] 2015-01-25 13:00
[Merge-conflicts](https://atom.io/packages/merge-conflicts) package causes the same problem (Atom 0.175, Mint 17.1)

**Comment by kevinsawicki** [comment] 2015-01-26 19:06
So the issue here was that 0.175 release of Atom on Debian and Windows was missing some files.

This occurred because of #5176 which was never merged but still messed up the build machines enough to cause this.

Our build machines don't clean out the `node_modules` folders between builds, this is done to save time and since `npm install` updates the dependencies, it is almost always fine to do this.

The one case this doesn't catch is when a module is de-duped to the root `node_modules` folder.  Once at the root, `npm install` won't re-install new versions of the module into sub-dependencies if the root version exists, even when the root version isn't compatible with the version used by the sub-dependency. It instead just logs a warning which wasn't noticed.

So I've cleaned out the Debian and Windows CI machines completely and verified that the latest pre-release builds of 0.176 contain the proper files.

0.176 should be released in the next couple of hours.

**Closed by kevinsawicki** 2015-01-26 19:06 UTC
Labels: atom, bug, linux, windows

**Comment by benogle** [comment] 2015-01-26 19:08
Nice
