### ISSUE TITLE
Regression with C++ text buffer that can lead to data loss.

### ISSUE THREAD

**Issue by despairblue** [atom/atom#15622] opened 2017-09-12 14:59 UTC
I just want to cross reference this here, since the root cause seems to be in the C++ text buffer. I could not reproduce this with atom 1.18.

*Update:*

Forgot the link: https://github.com/atom/autosave/issues/80

**Comment by Ben3eeE** [comment] 2017-09-12 15:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/autosave/issues/80. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-09-12 15:28 UTC

**Comment by despairblue** [comment] 2017-09-12 15:31
@Ben3eeE wouldn't it make more sense to close atom/autosave#80 since the underlying issue is in atom's core codebase?
