### ISSUE TITLE
Failed to load the extract-method package

### ISSUE THREAD

**Issue by atalargo** [atom/atom#9678] opened 2015-11-18 17:19 UTC
[Enter steps to reproduce below:]

1. Launch atom...

**Atom Version**: 1.2.1
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the extract-method package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:6:3
    at Object.<anonymous> (<anonymous>:6:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "behat-atom",
      "ruby-block-converter",
      "tree-view-open-files",
      "w3c-validation",
      "compare-files",
      "my-utils",
      "rsense",
      "coffee-lint",
      "linter-coffeescript",
      "ruby-string-interpolation2",
      "ruby-string-interpolation",
      "copy-as-rtf"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "softWrap": true,
    "preferredLineLength": 120
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
extract-method, v0.1.0
git-log, v0.4.1
git-tab-status, v1.9.2
jshint, v1.8.3
jsonlint, v1.1.2
language-diff, v0.4.0
language-slim, v0.5.0
language-twig, v1.6.2
less-than-slash, v0.11.0
linter, v1.11.2
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-flow, v4.0.0
linter-haml, v1.0.0
linter-js-yaml, v1.2.1
linter-php, v1.1.1
linter-phpcs, v1.3.0
linter-rubocop, v0.4.4
linter-ruby, v1.2.0
linter-scss-lint, v2.4.0
linter-slim, v1.0.0
markdown-format, v2.5.1
php-twig, v4.0.0
phpunit, v1.2.0
phpunit-snippets, v0.1.0
preview-plus, v1.2.6
project-manager, v2.6.5
save-session, v0.15.7
symbols-tree-view, v0.10.1
symfony-snippets, v0.3.0
sync-settings, v0.6.0
text-manipulation, v0.6.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-18 20:46
The extract-method package no longer appears to be maintained.  I would suggest uninstalling it and finding an alternative.

(Also, this is a duplicate of chumpy/extract-method#6)

**Closed by 50Wliu** 2015-11-18 20:46 UTC
