### ISSUE TITLE
Uncaught Error: EEXIST, file already exists '/Users/blah/.atom/storage'

### ISSUE THREAD

**Issue by taylorlapeyre** [atom/atom#5276] opened 2015-01-27 17:53 UTC
[Enter steps to reproduce below:]

1. Open Atom
2. Update Atom
3. Crash

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EEXIST, file already exists '/Users/taylorlapeyre/.atom/storage'

```
At /Users/taylorlapeyre/.atom/packages/auto-update-packages/node_modules/fs-plus/node_modules/mkdirp/index.js:74

undefined
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontFamily": "inconsolata-g",
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.1
language-haml, v0.15.0
language-x86, v0.1.0
scroll-past-end, v0.1.9

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-01-27 17:55
I believe this is a duplicate of https://github.com/atom/atom/issues/4806

**Closed by kevinsawicki** 2015-01-27 17:55 UTC
