### ISSUE TITLE
The Atom has crashed when open one big text file

### ISSUE THREAD

**Issue by Hinsteny** [atom/atom#12788] opened 2016-09-27 01:12 UTC
### Description

I have a big text file. I could use sublime open it that will take few seconds. But there will occurred an crashed error when i open it with Atom. By the way, the size of file is 16M!

**Comment by 50Wliu** [comment] 2016-09-27 01:41
This is a duplicate of #8864 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-27 01:41 UTC
