### ISSUE TITLE
Mac context menu opens underneath cursor, breaking Apple OS X HIG

### ISSUE THREAD

**Issue by int3h** [atom/atom#12624] opened 2016-09-07 18:46 UTC
### Description

On Mac OS X, the context menu (i.e., the right click menu) in Atom opens directly under your cursor, rather than a few pixels to the right, as is standard in OS X. As a result, after you right-click, the first option in the menu is already selected, and left-clicking (without moving the mouse) will select this menu item, rather than dismissing the menu.

Apple's official [OS X Human Interface Guidelines](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/ContextualMenus.html#//apple_ref/doc/uid/20000957-CH30-SW1) specifically state:

> **Don’t set a default item in a contextual menu.** If the user opens the menu and closes it without selecting anything, no action should occur.

While this doesn't directly mention menu location in relation to the cursor, it's implied by saying that the user should have to take action to select a menu item, and without that, no action should take place. 

You can see the correct behavior in any number of other OS X apps. For example, in Safari, if you right-click on a page, the context menu appears a few pixels to the right of the cursor. This way, no menu item is selected until the user takes action and moves the cursor right. If you right-click, then click without moving the mouse, no action will be selected, and the menu will be dismissed. 
### Steps to Reproduce
1. In Atom, open some file to edit.
2. Right-click inside the editor _without moving the cursor_.
3. Left-click, again without moving the cursor.

**Expected behavior:** The context menu should be dismissed without any menu item being selected, or action being taken.

**Actual behavior:** The "Undo" action is selected/acted on.
### Versions

```
Mac OS X: 10.11.6

Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.0
```

**Comment by narrowtux** [comment] 2016-10-10 11:50
This issue is so weird because Electron, the underlying renderer does not have this issue. Which probably means that someone made the deliberate choice of adding this "feature".

**Comment by Ben3eeE** [comment] 2016-10-10 11:57
I can not reproduce this on Windows 7 Atom 1.10.2.

**Comment by narrowtux** [comment] 2016-10-10 12:31
Doesn't apply to Windows anyway.

**Comment by narrowtux** [comment] 2016-11-03 11:57
Any update on this? I'm infuriated because I constantly activate Undo even though I didn't mean to.

**Comment by narrowtux** [comment] 2017-11-06 15:28
Seems to be fixed now, so you can close the issue (I am running 1.21.2)

**Comment by Ben3eeE** [comment] 2017-11-06 15:30
Thanks for reporting back

**Closed by Ben3eeE** 2017-11-06 15:30 UTC
Labels: mac, needs-reproduction
