### ISSUE TITLE
File Name Gets Overlapped

### ISSUE THREAD

**Issue by sunel** [atom/atom#7955] opened 2015-07-18 08:16 UTC
<img width="342" alt="screen shot 2015-07-18 at 1 45 00 pm" src="https://cloud.githubusercontent.com/assets/1009777/8760909/65df498c-2d53-11e5-91d9-e5f789c4b9fa.png">

**Comment by mnquintana** [comment] 2015-07-18 11:32
Thanks for the report! This is a duplicate of #4924 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-18 11:32 UTC
