### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.26.0\res...

### ISSUE THREAD

**Issue by caoxiemeihao** [atom/atom#17170] opened 2018-04-19 01:04 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Administrator\AppData\Local\atom\app-1.26.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\Administrator\AppData\Local\atom\app-1.26.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.26.0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.26.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.18 
minimap 4.29.8 
```

**Comment by caoxiemeihao** [comment] 2018-04-19 01:05
我可怜的Atom (。>︿<)_θ

**Comment by lee-dohm** [comment] 2018-04-19 01:28
I'm assuming that you're launching from a location including the `\\?` or have a system path set to include that in order to relax the file path length limit. It looks like Node's module resolution system is choking on that path, not anything specifically in Atom. Is it possible for you to remove the `\\?` from the path to see if this will work?

**Comment by Bobcatprince** [comment] 2018-04-19 07:30
After deleting and reinstalling Atom the error stopped. I quess there was some sort of update error.

**Comment by QZSAMA** [comment] 2018-04-19 17:57
@caoxiemeihao are you getting the error from building atom from source? or you installing the execution file from release? i have a similar problem that i had solved last week is similar and the solution for that is i git clone the project to "/users/(name) /github"
translate:  你这个抛出错误是在安装exe文件出现的还是 源文件script/build 出现的，我之前从git clone之后，安装也出现过类似的问题。我当时的解决办法是直接clone在/users/(用户名) /github里面就解决了。

**Comment by 50Wliu** [comment] 2018-05-05 17:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14461. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-05-05 17:16 UTC
Labels: more-information-needed, windows
