### ISSUE TITLE
Uncaught Error: spawn rubocop ENOENT

### ISSUE THREAD

**Issue by radfahrer** [atom/atom#4995] opened 2015-01-11 18:07 UTC
Uncaught Error: spawn rubocop ENOENT

**Atom Version**: 0.154.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At events.js:85

Error: spawn rubocop ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by lee-dohm** [comment] 2015-01-11 18:55
Duplicate of #4591.

Please install the `rubocop` binary and ensure that it is on your `PATH`.
Please upgrade to the latest version of Atom as well. The errors for this kind of thing are much better!

**Closed by lee-dohm** 2015-01-11 18:55 UTC
