### ISSUE TITLE
Autosave to cache

### ISSUE THREAD

**Issue by Lillecarl** [atom/atom#9080] opened 2015-10-08 07:54 UTC
Like notepad++ does, load file once you open it, save hash somewhere to monitor file changes.
Once we start writing in the file we save to a cache somewhere, which means even after closing the editor (or just pulling the plug) we'll still have the files contents saved.

Then once we press save manually we overwrite the file we originally wrote.

Would be a nice feature i guess? :)

**Comment by mnquintana** [comment] 2015-10-08 13:45
Thanks for the suggestion! I think this is a duplicate of https://github.com/atom/atom/issues/942 though, so I'm closing this out in favor of that issue - let me know if I'm misunderstanding though!

**Closed by mnquintana** 2015-10-08 13:45 UTC

**Comment by Lillecarl** [comment] 2015-10-08 13:54
Yes and that description was probably better too, thanks! :)

2015-10-08 15:45 GMT+02:00 Machisté N. Quintana <notifications@github.com>:
