### ISSUE TITLE
Cursor moved one space to the right of where it should be.

### ISSUE THREAD

**Issue by Toltar** [atom/atom#9354] opened 2015-10-30 16:11 UTC
I have a quite annoying bug that makes it a bit more difficult to type in. I wonder if this is some key combination that I pressed to make it do this, but I keep opening & closing. atom and it reproduces this as shown:

**The First Reproduction**
![bugsmaller](https://cloud.githubusercontent.com/assets/6003536/10850716/1f9161d8-7ef5-11e5-8ede-614623e4f73b.gif)

**The Second Reproduction**

![bugreproduced](https://cloud.githubusercontent.com/assets/6003536/10850830/a3b0e38a-7ef5-11e5-8ab9-e304f77c5344.gif)

If anybody can help me, I would appreciate it. :+1: 

*I have made sure I read and followed the debugging guide before all of this. Please let me know if there is any more info anybody needs to help resolve this issue. Thank you.*

**Comment by Cronax42** [comment] 2015-10-30 16:15
I have the same issue and I remember having had it before. It was previously considered solved with the resolution of https://github.com/atom/atom/issues/6055 if I am correct. It seems something caused this to fall apart again.

**Comment by izuzak** [comment] 2015-10-30 16:17
Thanks for the report, @Toltar -- I think this is a duplicate of https://github.com/atom/atom/issues/9343. Can you take a look in there and let us know if your problem is not covered by that? Seems like a problem with the seti syntax theme after upgrading to Atom 1.1

**Closed by izuzak** 2015-10-30 16:17 UTC

**Comment by Toltar** [comment] 2015-10-30 16:44
@Cronax42 Thanks for the help.


@izuzak Sure thing I will check it out and report it to you as soon as I find out.

**Comment by Cronax42** [comment] 2015-10-30 16:54
@izuzak I can confirm this is a duplicate.

**Comment by Toltar** [comment] 2015-10-30 17:10
@izuzak I am happy to report that it seems to be just a problem with the syntax theme.
