### ISSUE TITLE
Freezes any time a minified file is opened.

### ISSUE THREAD

**Issue by viziionary** [atom/atom#13920] opened 2017-03-02 20:49 UTC
I'm aware of[ this past issue](https://github.com/atom/atom/issues/307#issuecomment-110065290) where the issue with big files was apparently fixed but when I accidentally click on minified files of significant size (even small-ish files like basic jquery plugins)  it freezes. Every time. And I'm working pretty a pretty good processor: Intel Core i5-6600K CPU @  5.50GHz.

Only packages I'm using are Atom Beautify and an FTP manager which shouldn't be affecting the process of displaying the file.

**Comment by Ben3eeE** [comment] 2017-03-02 20:51
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #979. And has been fixed in Atom 1.15.0-beta3.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-03-02 20:51 UTC
Labels: duplicate
