### ISSUE TITLE
OSX Atom Helper renderer type lock up with100% CPU utilization

### ISSUE THREAD

**Issue by cstockton** [atom/atom#10080] opened 2015-12-16 00:01 UTC
Over the past few weeks I've noticed every once in a while my atom will lock up.. I am usually caught off guard and am left unsure what action I did to cause it. Today I happened to narrow it down. I am not sure the best way to debug ATOM crashes, I tried to open developer tools and start CPU profiling but the profiler never responded once it was in the error state. XCode profiling was best I could think to give ya.

Steps:
1) Started atom with: `atom -d --safe -f -w`
2) Open any folder with a few files
3) Open at least 3 files (it may work with 2 didn't try)
4) Split pane on an open file
5) Make sure that file is open in both panes
6) Drag the file from the left pane into the right

Result:
Atom freezes, no output to console, no response from dev tools.

Expect:
Anything but crash. Maybe it just has two open copies? Not sure.

The process responsible was:
`/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper --type=renderer --js-flags=--harmony --no-sandbox --lang=English --node-integration=true --enable-delegated-renderer --num-raster-threads=4 --gpu-rasterization-msaa-sample-count=8 --content-image-texture-target=3553 --video-image-texture-target=3553 --channel=23160.1.347038967`

Hopefully this may give some sort of lead into the issue:
![screen shot 2015-12-15 at 4 50 56 pm](https://cloud.githubusercontent.com/assets/180184/11827943/5d26df9c-a34d-11e5-968f-050a5e977d9b.png)

**Comment by benogle** [comment] 2015-12-16 00:42
Appreciate the detail!

For the record, I am not able to reproduce. Splitting and dragging between panes does not cause a crash for me.

**Comment by benogle** [comment] 2015-12-16 00:42
Can you paste in the crash report from Console.app?

**Comment by cstockton** [comment] 2015-12-16 01:43
My report wasn't very clear but a specific detail that is important is that the file open in each pane is at the same canonical location. The file you you drag (from left lane to right pane) in my case must be that same file. I'll update this when in front of a PC with a crash report if one is produced. What happens is CPU pins 100% and eventually wait/close dialog pops and I close it out (not before trying to wait a few times to check for correction).

**Comment by lee-dohm** [comment] 2015-12-16 03:15
This sounds like a duplicate of https://github.com/atom/atom/issues/10043.

**Comment by cstockton** [comment] 2015-12-16 05:34
I was just able to get this to happen on my Windows PC, completely different setup.

1) I created the following folders and files on my Desktop.

```
Foo
  Bar
    Doc1.txt
    Doc2.txt
    Doc3.txt
```

2) Right clicked Foo and chose "open with atom"
3) Expanded Foo and Bar showing the 3 docs
4) Opened each doc using tree view, Double clicked Doc1, 2, 3..
5) Clicked inside doc3, not sure that mattered
6) Right clicked doc3.txt in tree view, "split right"
7) Have doc3.txt active in left pane, doc3.txt active in right pane
8) Try to drag doc3.txt in the left pane to the right
9) Editor stops responded when I release mouse click

I am not sure how to get any sort of crash / dump.. I got an error "Editor is not responding" then asked me to keep waiting or close. Checked the dir the atom icon lives in didn't see any logs modified today.

**Comment by mishak87** [comment] 2015-12-16 12:26
For me it happens when I have same file open in both panels and try to open file from different directory with same name in one of the panels.
`[/da/file|/da/file]` :arrow_forward: open `/eb/file` :arrow_forward: freeze

**Comment by ztolley** [comment] 2015-12-16 14:31
Same issue on mac.  Seems to be all file types, though the settings panel splits with no issue

**Comment by AriaFallah** [comment] 2015-12-16 16:58
Same issues here. When opening a file in a different directory with the exact same name in a split pane atom completely freezes.

**Comment by 50Wliu** [comment] 2015-12-16 17:05
The issue with similar filepaths and filenames has been fixed in the 1.4.0 betas.

**Comment by cstockton** [comment] 2016-12-16 22:35
Closing- I assume this has long since been fixed

**Closed** 2016-12-16 22:35 UTC
Labels: crash, needs-reproduction
