### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by creeloper27** [atom/atom#20138] opened 2019-11-11 07:50 UTC
[Enter steps to reproduce:]

1. create a folder named "test project" and open it as a project in Atom
2. create a folder named "test folder" inside "test project"
3. create a file named "Topics Nameofsomething pages 123 - 123 Name 0, Name 1, Name 2, Name 3, Name 4.txt" inside "test project"
4. from atom, try to move the file "Topics Nameofsomething pages 123 - 123 Name 0, Name 1, Name 2, Name 3, Name 4.txt" from "test project" to "test folder"

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Windows 10 Enterprise 2016 LTSB
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\My User\AppData\Local\atom\app-1.41.0\ Name 4.txt'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\My User\AppData\Local\atom\app-1.41.0\ Name 4.txt'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1008510)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1015439)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:989070)
```

### Commands

```
     -4:05.6.0 core:backspace (input.hidden-input)
     -4:04.1.0 core:confirm (input.hidden-input)
     -3:35.8.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -3:30.8.0 core:confirm (input.hidden-input)
     -2:54.4.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -2:52.3.0 core:confirm (input.hidden-input)
     -2:41.5.0 tree-view:add-folder (span.name.icon.icon-file-directory)
  2x -2:38.7.0 core:confirm (input.hidden-input)
     -2:34.5.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -2:33.4.0 core:backspace (input.hidden-input)
     -2:31.3.0 core:confirm (input.hidden-input)
     -2:12.2.0 tree-view:move (span.name.icon.icon-file-text)
     -2:11.2.0 core:move-right (input.hidden-input)
     -2:10.9.0 core:move-left (input.hidden-input)
     -2:10.5.0 core:move-right (input.hidden-input)
     -2:09.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
arduino-upload 1.5.1 
atom-beautify 0.33.4 
autocomplete-computercraft 1.0.0 
autocomplete-python 1.11.0 
ftp-remote-edit 0.17.0 
kite 0.174.0 
language-arduino 0.4.3 
language-computercraft 0.2.1 
language-systemd 0.1.1 
minimap 4.29.9 
palokai-dark-theme-syntax 0.0.0 
python-snippets-plus undefined 
symbols-tree-view 0.14.0 
teletype 0.13.3 
```

**Comment by darangi** [comment] 2019-11-14 16:04
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed** 2019-11-14 16:05 UTC
Labels: duplicate
