### ISSUE TITLE
ReferenceError: states is not defined

### ISSUE THREAD

**Issue by Valve** [atom/atom#9696] opened 2015-11-19 12:47 UTC
Atom 1.2.2, OSX: 10.10.5

Trying to open a directory and getting this error: 

```
ReferenceError: states is not defined
    at Project.module.exports.Project.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:98:9)
    at AtomEnvironment.module.exports.AtomEnvironment.loadStateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:906:22)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:51:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

```

**Comment by izuzak** [comment] 2015-11-19 13:52
Thanks for the report, @Valve  -- this looks like a duplicate of https://github.com/atom/atom/issues/9598 so I'm going to close this in favor of that issue.

**Closed by izuzak** 2015-11-19 13:52 UTC
