### ISSUE TITLE
multi-cursor click stopped working

### ISSUE THREAD

**Issue by DanFessler** [atom/atom#20918] opened 2020-06-11 08:32 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Randomly my ctrl+click for multi cursors stopped working.  I've tried running in safe mode, deleting (including cache) and reinstalling, and restarting my computer.  Nothing seems to fix it.  All other issues similar to this relate to hyperclick, but this doesn't appear to be the issue here.

### Versions
Atom 1.48.0 on MacOS 10.14.5

**Comment by Anyvie** [comment] 2020-06-11 08:36
Duplicate of #20916 / #20911

**Closed** 2020-06-12 15:49 UTC
