### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ Simran Singh 11.11 Talk Radio.mp3'

### ISSUE THREAD

**Issue by escofresco** [atom/atom#19312] opened 2019-05-12 05:16 UTC
[Enter steps to reproduce:]

1. A new directory was created
2. An audio file was placed into the directory

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ Simran Singh 11.11 Talk Radio.mp3'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/ Simran Singh 11.11 Talk Radio.mp3'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:914616)
    at TreeView.t.exports.TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:920370)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:895210)
```

### Commands

```
     -8:00.8.0 tree-view:copy (div.tool-panel.tree-view)
     -3:16 find-and-replace:show (input.hidden-input)
  6x -3:14.6.0 core:confirm (input.hidden-input)
     -1:31.5.0 editor:newline (input.hidden-input)
     -1:31.1.0 core:paste (input.hidden-input)
  5x -1:23.9.0 core:move-right (input.hidden-input)
  3x -1:21 emacs-plus:backward-kill-word (input.hidden-input)
     -1:13.8.0 core:save (input.hidden-input)
     -0:32 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:30 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-django 0.3.2 
autoclose-html 0.23.0 
color-picker 2.3.0 
django-templates 0.5.0 
emacs-plus 0.12.0 
gitkraken-glo 1.0.1 
highlight-line 0.12.0 
pigments 0.40.2 
project-manager 3.3.7 
python-indent 1.1.7 
```

**Comment by rsese** [comment] 2019-05-13 21:37
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-05-13 21:37 UTC
