### ISSUE TITLE
CPU and memory leak after installing v0.192.0

### ISSUE THREAD

**Issue by Yajo** [atom/atom#6441] opened 2015-04-20 09:34 UTC
When I open Atom, after updating to v0.192.0, it launches 7 processes, one of which runs this:

```
/usr/share/atom/atom --eval require('/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js').setCacheDirectory('/home/yajo/.atom/compile-cache/coffee');
require('/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js').register();
require('/usr/share/atom/resources/app/node_modules/coffeestack/index.js').setCacheDirectory('/home/yajo/.atom/compile-cache/coffee/source-maps');
require('/usr/share/atom/resources/app/src/task-bootstrap.js');
```

This process hangs my system eating all CPU and RAM available.

If I kill that process before it eats my computer, I can continue using Atom, but obviously it's not very comfortable.

I use Fedora 21 with the official RPM package from atom.io.

**Comment by 50Wliu** [comment] 2015-04-20 12:05
Closing as a duplicate of #6437, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-20 12:05 UTC
