### ISSUE TITLE
Issue pasting new file name when saving file to a directory

### ISSUE THREAD

**Issue by vsteve** [atom/atom#14316] opened 2017-04-27 18:59 UTC
I have been having an issue pasting file names as I save my documents. Is this a issue for anyone else?

**Comment by rsese** [comment] 2017-04-27 19:46
Hi @vsteve - assuming you're on macOS, the known issue is [here](https://github.com/atom/atom/issues/14145) as mentioned below.

For future issues, please completely fill out the issue template and if you have general questions about Atom, our message board is a great place to have those conversations:

https://discuss.atom.io/

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14145. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-27 19:46 UTC
