### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/06/5nxh98hj3ws9360dgwd47jr00000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by Darshit45** [atom/atom#20875] opened 2020-06-03 13:13 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/06/5nxh98hj3ws9360dgwd47jr00000gn/T/AppTranslocation/55F2CD8D-7DEF-4814-883A-5F4320B4F309/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/fs-admin/build/Release/fs_admin.node, 1): image not found

```
At electron/js2c/asar.js:138

Error: dlopen(/private/var/folders/06/5nxh98hj3ws9360dgwd47jr00000gn/T/AppTranslocation/55F2CD8D-7DEF-4814-883A-5F4320B4F309/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/fs-admin/build/Release/fs_admin.node, 1): image not found
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/private/var/folders/06/5nxh98hj3ws9360dgwd47jr00000gn/T/AppTranslocation/55F2CD8D-7DEF-4814-883A-5F4320B4F309/d/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at get_binding (/private/var/folders/06/5nxh98hj3ws9360dgwd47jr00000gn/T/AppTranslocation/55F2CD8D-7DEF-4814-883A-5F4320B4F309/d/Atom.app/Contents/Resources/app/static/<embedded>:14:18000)
    at Object.unlink (/private/var/folders/06/5nxh98hj3ws9360dgwd47jr00000gn/T/AppTranslocation/55F2CD8D-7DEF-4814-883A-5F4320B4F309/d/Atom.app/Contents/Resources/app/static/<embedded>:14:18967)
    at CommandInstaller.createSymlink (/private/var/folders/06/5nxh98hj3ws9360dgwd47jr00000gn/T/AppTranslocation/55F2CD8D-7DEF-4814-883A-5F4320B4F309/d/Atom.app/Contents/Resources/app/static/<embedded>:11:403300)
    at /private/var/folders/06/5nxh98hj3ws9360dgwd47jr00000gn/T/AppTranslocation/55F2CD8D-7DEF-4814-883A-5F4320B4F309/d/Atom.app/Contents/Resources/app/static/<embedded>:11:403229
    at /private/var/folders/06/5nxh98hj3ws9360dgwd47jr00000gn/T/AppTranslocation/55F2CD8D-7DEF-4814-883A-5F4320B4F309/d/Atom.app/Contents/Resources/app/static/<embedded>:11:403344
    at FSReqCallback.oncomplete (fs.js:150:20)
```

### Commands

```
  2x -0:12.4.0 window:install-shell-commands (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
```

**Comment by sadick254** [comment] 2020-09-18 03:55
Thanks for taking the time to contribute!

We noticed that even though this is a not a duplicate of https://github.com/atom/atom/issues/21285. It is very similar to it. You can try the fixes suggested on https://github.com/atom/atom/issues/21285.

**Closed by sadick254** 2020-09-18 03:55 UTC
