### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.49.0\res...

### ISSUE THREAD

**Issue by H117J** [atom/atom#21074] opened 2020-07-15 05:55 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\josep\AppData\Local\atom\app-1.49.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:138

Error: The specified module could not be found.
\\?\C:\Users\josep\AppData\Local\atom\app-1.49.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:1:735013)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:2676864)
    at get_manager (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:2676966)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:2677092)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:1022283)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1239383)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1237368)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:284830)
```

### Commands

```
     -2:58.5.0 application:open-file (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
```

**Comment by pdc2341** [comment] 2020-07-15 21:38
I encountered the same error:

The sequence of events preceding this error occurring on my computer were as follows on July 15 2020:
1) Open an html file with atom
2) Avast antivirus sends notification that the Behavior Shield found threat IDP.ARES.Generic in filepath C:\Users\...\AppData\Local\atom\Update.exe 
(note: this has never happened before on this computer)
3) after clicking send to Virus Chest atom opens and presents this error
4) future to open Atom by reopening the same file in Atom or simply opening Atom through the desktop shortcut failed to replicate error but the option to check for updates in the About page says "Your system does not support automatic updates"

Steps Taken:
Sent Update.exe to Avast for analysis as a possible false positive

**Comment by sadick254** [comment] 2020-09-16 15:09
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-16 15:09 UTC
