### ISSUE TITLE
Crashing when opening file inside large repository.

### ISSUE THREAD

**Issue by David-Polehonski** [atom/atom#9431] opened 2015-11-04 12:12 UTC
I have a large repo (7.5Gb) and atom crashes every time I attempt to open any file in the project. Could this be because of the large repo or because the index file is over 2mb ?

**Comment by ADobin** [comment] 2015-11-04 18:04
I'm guessing this is related to #9339.

**Comment by benogle** [comment] 2015-11-05 01:56
Closing as a dupe of #9339. The fix should be merged soon.

**Closed by benogle** 2015-11-05 01:56 UTC
