### ISSUE TITLE
Tab path tooltip does not update to new path on Save As...

### ISSUE THREAD

**Issue by nopejpg** [atom/atom#8638] opened 2015-09-02 15:20 UTC
Reproduce steps:
1. Create a new file, name is `blah.txt`.
2. Click *File* > *Save As...* and name it something else (`new_blah.txt`)
3. Hover over the tab of the file in Atom; it'll have the full path to the old file even though it's saving to the new one set in the above step.

The included image reflects that; I originally created this file as `hcheck.go` but did a *Save As...* to `haEIP.py`.

![screenshot_2015-09-02_11-17-00](https://cloud.githubusercontent.com/assets/7646510/9635419/643d6dfe-5164-11e5-9bb0-eb3e7374ef9b.png)

Atom 1.0.7 on Xubuntu 15.04.

**Comment by mnquintana** [comment] 2015-09-02 15:34
Thanks for the report! This looks like a duplicate of https://github.com/atom/tabs/issues/189 though - closing this out in favor of that issue.

Also, you might want to take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Closed by mnquintana** 2015-09-02 15:34 UTC

**Comment by nopejpg** [comment] 2015-09-02 15:52
Both issues are closed though? Has this been resolved?

**Comment by mnquintana** [comment] 2015-09-02 16:03
I'm not sure what you mean - I linked to one issue and it's open.

**Comment by nopejpg** [comment] 2015-09-02 16:54
Sorry, I feel dumb; I scrolled all the way down and seen "Closed"; so I thought it was closed.
