### ISSUE TITLE
Auto-indent misbehaviour (javascript): object inside of an array

### ISSUE THREAD

**Issue by afanasy** [atom/atom#5105] opened 2015-01-16 13:12 UTC
This auto-formatted incorrectly
```javascript
[
  'two spaces indent',
{} //object placed two spaces to the left, expected to have the same indentation as text
]
```

**Comment by kevinsawicki** [comment] 2015-01-16 17:37
I believe this is a duplicate of https://github.com/atom/language-javascript/issues/77

**Closed by kevinsawicki** 2015-01-16 17:37 UTC

**Comment by afanasy** [comment] 2015-01-17 05:56
Thanks!
