### ISSUE TITLE
Data loss when trying to save read-only file

### ISSUE THREAD

**Issue by EvanGoss** [atom/atom#11347] opened 2016-04-01 23:41 UTC
### Description

Trying to overwrite read-only file when closing a file results in the file closing without successfully saving.

### Steps to Reproduce

1. In Finder, right click a file, select Get Info
2. In the General section, checked the "Locked" box
3. Open file in Atom
4. Make a change to the file
5. Close the file
6. Select "save" when prompted to save changes

**Expected behavior:**

The file close should be paused until the write has been completed.  If the write fails, the file should remain open.

**Actual behavior:**

File will close, but save will fail and an error message will alert you that the save was not successful.

### Versions

Atom 1.6.1 & 1.6.2
OSX 10.10.5 (Yosemite)

I haven't tested in the Windows version or in safe mode.

**Comment by lee-dohm** [comment] 2016-04-02 00:10
This is a duplicate of https://github.com/atom/atom/issues/7708. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-04-02 00:10 UTC
Labels: bug, needs-reproduction

**Comment by EvanGoss** [comment] 2016-04-02 06:56
I was pretty surprised that it wasn't already reported so I should have known to keep looking.

Thanks.
