### ISSUE TITLE
macOS: Editor background is not uniform on non-Retina external screen

### ISSUE THREAD

**Issue by pavolmarkovic-serato** [atom/atom#14668] opened 2017-05-29 04:09 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When opening/editing a file in Atom on non-Retina external screen the editor background is made of blocks of varying colors. When moving the editor window to built-in Retina screen, the blocks disappear and editor has expected uniform color.

This seems to be  a regression in 1.17.x version as it does not happen in version 1.16.

### Steps to Reproduce

1. Attach external monitor to Retina enabled MacBook Pro
2. Open Atom 1.17 or later (including 1.18 beta 2) on external monitor
3. Open any file to edit

**Expected behavior:** [What you expect to happen]
The background color is uniform.

**Actual behavior:** [What actually happens]
Background consists of several blocks with different background colors based on length of the text. See attached pictures.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always.

### Versions
Version 1.17.0, Version 1.17.2, 1.18 beta 2 on macOS 10.12.5 (16F73)
Does not happen in version 1.16.0 and earlier.

`atom --version`:
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

MacBook Pro (Retina, 13-inch, Early 2015)
Intel Iris Graphics 6100 1536 MB

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Atom 1.17.2:
![atom 1 17 2](https://cloud.githubusercontent.com/assets/16377862/26536177/9cf50db4-4488-11e7-99f2-c8644af2f289.png)

Atom 1.16:
![atom 1 16](https://cloud.githubusercontent.com/assets/16377862/26536178/9cf78814-4488-11e7-9c94-1c161cf08264.png)

**Comment by thomasjo** [comment] 2017-05-29 07:54
Duplicate of #12634. Will be fixed once #12696 ships, which will most likely be Atom 1.19.0.

**Closed by thomasjo** 2017-05-29 07:54 UTC
