### ISSUE TITLE
fold glitches

### ISSUE THREAD

**Issue by Announcement** [atom/atom#15961] opened 2017-10-22 01:17 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

comment folding is broken

### Steps to Reproduce

1. have multiline comments and some functions
2. fold all
3. unfold all

**Expected behavior:** [What you expect to happen]
comments to be visible

**Actual behavior:** [What actually happens]

not only are the comments not visible, but trying to unfold them manually does not work, to make them visible you must fold them again (even though they are already hidden) with the gutter, and unfold them with the gutter as the ... tooltip next to them is now thoroughly broken.

**Reproduces how often:** [What percentage of the time does it reproduce?]

every time.

### Versions
1.22.0-beta1 x64
w10pro64

~~~
$ apm --version

apm  1.18.8                                
npm  3.10.10                               
node 6.9.5 x64                             
python 3.6.1                               
git 2.14.1.windows.1                       
visual studio                              

$ atom --version                           
                                           
Atom    : 1.22.0-beta1                     
Electron: 1.6.15                           
Chrome  : 56.0.2924.87                     
Node    : 7.4.0                            
~~~

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment] 2017-10-22 09:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15943. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-10-22 09:52 UTC

**Comment by maxbrunsfeld** [comment] 2017-10-23 19:22
@Announcement Thanks for the report and sorry for this poor experience. This has been fixed in https://github.com/atom/text-buffer/pull/269 and will go out in our next hotfix release.
