### ISSUE TITLE
Collapsed comment ignores softwrap on fixed size

### ISSUE THREAD

**Issue by freed00m** [atom/atom#9502] opened 2015-11-09 23:02 UTC
Hello, 

It might be an issue for people like me, it's only an esthetic issue. see a screenshot that demostrates what I have in mind.

![selection_004](https://cloud.githubusercontent.com/assets/9461698/11049399/3c5f9a2c-873e-11e5-8423-8daddc2e2db5.png)

Atom -v 1.1.0

**Comment by benogle** [comment] 2015-11-09 23:04
cc @as-cii @maxbrunsfeld

**Comment by izuzak** [comment] 2015-11-11 17:05
Thanks for the report, @freed00m -- I think this is a duplicate of https://github.com/atom/atom/issues/5740, so I'm going to close this in favor of that issue. If I misunderstood your report -- can you clarify the difference between this report and #5740?

**Closed by izuzak** 2015-11-11 17:05 UTC
Labels: bug
