### ISSUE TITLE
atom messy code

### ISSUE THREAD

**Issue by sunyonggang** [atom/atom#6277] opened 2015-04-07 02:47 UTC
i update atom to v0.189.0, then open a file with chinese code, and it's messy

**Comment by sunyonggang** [comment] 2015-04-07 03:18
when i set font family 'Loma' or others, it also didn't work, but i can open it normally with gedit

**Comment by thomasjo** [comment] 2015-04-07 05:00
Duplicate of https://github.com/atom/atom/issues/6214.

**Closed by thomasjo** 2015-04-07 05:00 UTC
