### ISSUE TITLE
Suddenly, Atom is dead

### ISSUE THREAD

**Issue by mikeytusa** [atom/atom#9071] opened 2015-10-07 17:33 UTC
As of today, when I open Atom, nothing really works.

https://drive.google.com/file/d/0By0MxtGl4s2YOW1ZaHBrck1JeFU/view?usp=drivesdk

That's all I get.  There's an option for Atom in the menu and that's it.  Eventually it  does this:

https://drive.google.com/file/d/0By0MxtGl4s2YTkJvd3ZMWTNfeGc/view?usp=drivesdk

I've uninstalled and deleted everything I could find in my AppData folders related to Atom.  Reinstalling does not fix the issue.

**Comment by mikeytusa** [comment] 2015-10-07 18:30
I loaded it in safe mode (for those wondering, add --safe to the end of Target on Windows) and now it seems to be working.

**Comment by benogle** [comment] 2015-10-07 18:45
Can you open the dev tools (cmd-option-i) when it's not working and paste in any messages?

**Comment by benogle** [comment] 2015-10-07 18:45
Def caused by some package, but the error messages might indicate which package.

**Comment by 50Wliu** [comment] 2015-10-07 18:53
@mikeytusa Have you tried clicking the "Keep Waiting" button?  Usually that'll load Atom for me if it's stuck like that (which reminds me, I need to make an issue for that...).

**Comment by mikeytusa** [comment] 2015-10-07 19:06
Arg.  Doing the same thing again.  The console has no info whatsoever.

https://drive.google.com/file/d/0By0MxtGl4s2YajkxcHhKdEdtdlE/view?usp=drivesdk

**Comment by mikeytusa** [comment] 2015-10-07 19:09
It finally loaded, lol. Window load time: 104851ms

Don't see anything useful in the dev tools though.

**Comment by mikeytusa** [comment] 2015-10-07 19:09
Pigments?  https://drive.google.com/file/d/0By0MxtGl4s2YVUUwZFpMVzdseTQ/view?usp=drivesdk

**Comment by mikeytusa** [comment] 2015-10-07 19:15
Yep, that must have been the issue.  Seems to be working fine now.

**Comment by benogle** [comment] 2015-10-07 19:27
Please open an issue on pigments and if you can link to your project. I
know pigments does some file analysis and your project may be hitting some
weird edge case.

**Comment by Charpeni** [comment] 2015-10-07 19:34
Same happened to me on Ubuntu 15.04 x64.
```
Close Atom
apm uninstall pigments
Open Atom
Fixed.
```

**Comment by benogle** [comment] 2015-10-07 21:07
Closing due to a package. cc @abe33

**Closed by benogle** 2015-10-07 21:07 UTC
Labels: more-information-needed
