### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by fusion809** [atom/atom#11744] opened 2016-05-13 01:36 UTC
[Enter steps to reproduce below:]

I saved a file and this error was thrown. 

**Atom Version**: 1.7.3
**System**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
     -7:13.9.0 tabs:close-all-tabs (div.title)
     -2:06.9.0 tree-view:add-file (li.file.entry.list-item.selected)
     -2:05.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:04.6.0 core:paste (atom-text-editor.editor.is-focused)
     -2:04.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:03.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:00.9.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -2:00.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:56.2.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -1:39.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:03.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.lisp": [
        ".emacs",
        ".spacemacs"
      ],
      "source.python": [
        "BUCK"
      ],
      "source.shell": [
        "install"
      ]
    },
    "disabledPackages": [
      "language-markdown",
      "browser-plus"
    ],
    "projectHome": "/home/fusion809/GitHub/mine",
    "themes": [
      "fusion-ui",
      "material-monokai-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
atomic-chrome, v0.3.0
build, v0.62.0
file-icons, v1.7.11
fusion-ui, v0.10.0
icon-fonts, v2.5.1
language-asciidoc, v1.1.0
language-gentoo, v0.9.0
language-gfm, v0.86.0
language-ini, v1.16.0
language-julia, v0.6.0
language-lisp, v0.2.0
language-lua, v0.9.4
language-matlab-octave, v0.1.1
language-patch, v0.1.0
language-rpm-spec, v0.9.0
language-sage, v0.3.0
language-scilab, v0.1.0
language-viml, v0.3.0
linter, v1.11.4
markdown-writer, v2.3.3
material-monokai-syntax, v0.1.1
pigments, v0.26.3
project-manager, v2.9.7
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-05-13 01:43
This is a duplicate of #11692 - feel free to subscribe there for updates.  Reliable repro steps would be awesome if you can figure them out.

**Closed by 50Wliu** 2016-05-13 01:43 UTC
