### ISSUE TITLE
Atom crashes when a firefox tab is moved over it

### ISSUE THREAD

**Issue by a-jamesregan** [atom/atom#7832] opened 2015-07-10 12:23 UTC
##### Atom crashes when I drag a firefox tab over it.  Here is the output of a terminal window when used to start atom from the command line:

[16948:0710/080707:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
App load time: 621ms
[16981:0710/080708:INFO:renderer_main.cc(212)] Renderer process started
[16948:0710/080710:INFO:CONSOLE(56)] "Window load time: 1595ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (56)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 1286 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

##### There's nothing much helpful in the x log, but in case you wanted to see it, here it is:
Script for ibus started at run_im.
Script for auto started at run_im.
Script for default started at run_im.
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd main process ended, respawning
init: at-spi2-registryd respawning too fast, stopped

##### And here is a video of the crash happening.  I think the issue is with handling a drag-drop operating.
https://www.youtube.com/watch?v=sdOWcSvH-1Q

**Comment by mnquintana** [comment] 2015-07-10 12:37
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/3593 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-10 12:37 UTC
