### ISSUE TITLE
`e` key stuck as causing backspace

### ISSUE THREAD

**Issue by zeigerpuppy** [atom/atom#18480] opened 2018-11-22 15:56 UTC
### Prerequisites

* [x]  Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

### Description

I am using the atom editor in a remote (X2Go) session and it has started causing the `e` key to enter `backspace`.  I'm not sure how it started but have tried everything to revert the behaviour.

### Steps to Reproduce

1. reinstall atom - `apt purge atom && rm - r ~/.atom && apt install atom`
2. start atom (safe mode also causes issue)
3. type some characters and then `e` and `e` will work as a backspace

Other programs (including text editors, e.g. Leafpad) type the `e` as normal.
I have tried rebooting, restarting the session and the X2Go connection.

**Expected behavior:** 
- `e` should type `e`!

**Actual behavior:** 
- `e` behaves as backspace

**Reproduces how often:** [What percentage of the time does it reproduce?]
- always

### Versions

Debian 9

Atom: 1.32.2
Electron 2.0.9
Chrome: 61.0.3163.100
Node: 8.93

apm 2.1.2
npm 6.2.0
python 2.7.12
git 2.11.0

**Comment by Ben3eeE** [comment] 2018-11-22 16:33
This is due to a bug in chromium when running X2Go. The only thing we can do to resolve this issue is to not rely on `KeyboardEvent.code` when resolving keystrokes. There is an open issue for this https://github.com/atom/atom-keymap/issues/222

In the meantime you can follow the instructions on discuss https://discuss.atom.io/t/e-key-acting-as-backspace/37075/16?u=ben3eee to work around this issue. If you have any questions ask there.

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom-keymap/issues/222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-11-22 16:33 UTC
Labels: duplicate, wrong-repo

**Comment by zeigerpuppy** [comment] 2018-11-22 22:45
thanks @Ben3eeE, the fix described there works well.
For anyone finding this issue, the fix is as following:

1. add the following to `~/atom.init.coffee`.  (you may need to create the file)

```
atom.keymaps.addKeystrokeResolver ({keystroke, event}) ->
  if event.code is 'Backspace' and (event.key is 'e' or event.key is 'E')
    keystroke.replace('backspace', 'e')
```
