### ISSUE TITLE
window focus issues

### ISSUE THREAD

**Issue by cjbarber** [atom/atom#3833] opened 2014-10-14 20:25 UTC
Firstly, thanks for making an awesome piece of software!

While using Atom, my computer (OSX 10.9.5) will switch windows randomly. If I then attempt to cmd-tab back into Atom, sometimes it will work, but other times it again switches off focus to a different window (i.e. finder, chrome).

Latest Atom 0.136.0

**Comment by kevinsawicki** [comment] 2015-08-07 00:34
I'm unable to reproduce this on Mac 10.10.3 and Atom 1.0.5.

Due to the age of this issue I'm going to close it out for now. Please comment if you are still seeing it on Atom 1.0.5+ and we'll reopen it.

**Closed by kevinsawicki** 2015-08-07 00:34 UTC
Labels: mac
