### ISSUE TITLE
[Bug] Duplicating Folder Does not Preserve Linux File Permissions

### ISSUE THREAD

**Issue by H8to** [atom/atom#18600] opened 2018-12-19 15:47 UTC
### Description

When I duplicate a folder with hotkey D or "Copy Folder" from within Atom, the file permissions will be set to the default umask.

### Steps to Reproduce

1. Create a project with a folder and an executable file.
2. Copy the folder which contains the executable file.
3. See permissions. Not executable any more. Also other attributes like group writable etc. are lost.

**Expected behavior:** 
Preserve original permissions like any OS copy function does.

**Actual behavior:** 
Sets default umask.

**Reproduces how often:** 
100% in production and safe mode

### Versions
OS : Arch Linux
Atom    : 1.33.0
Electron: 3.0.13
Chrome  : 66.0.3359.181
Node    : 10.2.0

**Comment by rsese** [comment] 2018-12-19 21:58
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1218 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-12-19 21:58 UTC
