### ISSUE TITLE
cmd/ctrl click URLs should open them in the default browser

### ISSUE THREAD

**Issue by marshall007** [atom/atom#5019] opened 2015-01-12 23:53 UTC
Similar to iTerm works, when you cmd+click a URL it opens in the default browser. Likewise, it would also be nice to have an "Open Selection as URL" in the right-click context menu.

Atom already underlines URLs in every language, so I imagine implementing this would be trivial.

**Comment by 50Wliu** [comment] 2015-01-13 01:25
I believe the shortcut right now is <kbd>ctrl</kbd> (or <kbd>cmd</kbd>)+<kbd>shift</kbd>+<kbd>o</kbd>.

**Comment by kevinsawicki** [comment] 2015-01-13 01:26
I believe this is a duplicate of https://github.com/atom/link/issues/6

**Closed by kevinsawicki** 2015-01-13 01:26 UTC

**Comment by marshall007** [comment] 2015-01-13 06:34
I was working on a PR for this but I couldn't figure out what the proper way to mock click events in the tests would be. The relevant lines are [`spec/link-spec.coffee#L43-L44`](https://github.com/marshall007/link/blob/661af5a49f715810578d89b1cf91de835e41cc8c/spec/link-spec.coffee#L43-L44). @kevinsawicki would you mind taking a look?

Also, is there a better way to bind click handlers than `atom.workspaceView.on 'click'` or do we just have to wait for #2256?
