### ISSUE TITLE
How to show text like '/u0001' in atom?

### ISSUE THREAD

**Issue by littlebeandog** [atom/atom#12792] opened 2016-09-27 11:40 UTC
It's fine to show invisible chars like 'SPACE' 'TAB' as there's an obvious setting.

But how could i make characters like 'CTRL-A' visible?

thx!!

**Comment by 50Wliu** [comment] 2016-09-27 15:26
This is a duplicate of #12157 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-27 15:26 UTC
