### ISSUE TITLE
Can't click on text in an editor tab when mouse cursor is immediately to the left of a gutter

### ISSUE THREAD

**Issue by WalterGR** [atom/atom#14707] opened 2017-06-02 19:16 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It is impossible to click on text in an editor tab when the mouse cursor is immediately to the left of a gutter.

### Steps to Reproduce

1. Open Atom.
2. Arrange two panes side-by-side (i.e. horizontally.)
3. Open text file(s) in both panes.
4. Create a line in an editor tab in the left pane that is longer than the tab is wide.
5. Click on text in that line just to the left of the gutter of the right pane.

**Expected behavior:** 

The text editor cursor is moved to where the mouse cursor is.

**Actual behavior:** 

Nothing.

**Reproduces how often:** 

Always.

### Versions

`atom --version`

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

`apm --version`

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0

OS: OS X 10.10.5.

### Additional Information

Screen capture:

![atom-clicking-text-to-left-of-gutter-doesnt-work-properly mov](https://cloud.githubusercontent.com/assets/380880/26741161/46906952-47a6-11e7-9620-71b0725bac2d.gif)

**Comment by rsese** [comment] 2017-06-02 23:52
Thanks for the report!  Is the file in your GIF long enough to scroll vertically?  If so, I can reproduce because I think that space is where the vertical scrollbar would be when you start scrolling.  If you can confirm, I think this might be a dupe of https://github.com/atom/atom/issues/14661.

**Comment by WalterGR** [comment] 2017-06-03 01:04
Ah, yes, you are correct.  This is a dupe of #14661 - "Scrollbar div still takes up space even if there's no scrollbar".

Closing.

**Comment by WalterGR** [comment] 2017-06-03 01:11
Reopening.

Sorry, I didn't read your comment vs. #14661 carefully.  While this could be _related_ to #14661, this doesn't seem to be a duplicate.

> Is the file in your GIF long enough to scroll vertically? If so, I can reproduce because I think that space is where the vertical scrollbar would be when you start scrolling.

Per repro step 4, yes.  However, as #14661 currently reads, the problem there is when a scrollbar _isn't needed at all_.  Per my issue here, the problem also exists when the scrollbar is needed but isn't being shown at the moment.

I can't edit #14661.  I could add a comment saying that the issue is more broad than stated.  But someone would need to update the issue text...

Let me know what you'd prefer I do.

**Comment by 50Wliu** [comment] 2017-06-06 01:05
> Per my issue here, the problem also exists when the scrollbar is needed but isn't being shown at the moment.

The issues might still be duplicates.  There is no option on Windows to hide scrollbars except when scrolling, and since I only have a Windows laptop I was unable to check the different scrollbar options on macOS.  Can you try using the developer tools to figure out if a scrollbar div is still there?

**Comment by rsese** [comment] 2017-06-06 19:06
Thanks @50Wliu :v:  Looks like the div is there for the vertical scrollbar:

![vertical-scroll-div](https://github-slack.s3.amazonaws.com/monosnap/untitled__sandboxhello-world_2017-06-06_13-55-44.png)

So I have a file that's long enough to need vertical scrolling and my scrolling setting is:

![scroll-setting](https://github-slack.s3.amazonaws.com/monosnap/General_2017-06-06_13-59-14.png)

**Comment by nathansobo** [comment] 2017-08-15 22:42
We handle mousedown events on the dummy scrollbar nodes just as we do on the content as you can see [here](https://github.com/atom/atom/blob/586b818bae9886649da7d3fbdb231d419b0fbe90/src/text-editor-component.js#L735). So I'm not sure we have the whole story here.

**Comment by nathansobo** [comment] 2017-08-15 22:44
@rsese @50Wliu Have you been able to reproduce this. I cannot.

**Comment by Ben3eeE** [comment] 2017-08-15 23:07
@nathansobo I think this issue got fixed without being closed. I saw it like last week when testing some PRs and thought it was odd. When I reproduced I was using Atom 1.18 and I was unable to reproduce on master.

**Comment by rsese** [comment] 2017-08-16 02:31
Just tried on 1.19.0 and can't reproduce anymore:

![gutter-click](https://user-images.githubusercontent.com/734194/29344936-f11bdaca-8200-11e7-8afd-f1d5cb021e09.gif)

**Comment by nathansobo** [comment] 2017-08-16 03:38
Okay. Unless we're all missing something I think we're good on this one. We can reopen if I'm wrong.

**Closed by nathansobo** 2017-08-16 03:38 UTC
Labels: more-information-needed
