### ISSUE TITLE
build problem?

### ISSUE THREAD

**Issue by JPRuehmann** [atom/atom#17113] opened 2018-04-11 06:45 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
If I run script/build since yesterday I get the following messages.
```
Installing script dependencies
Installing apm
../src/onig-scanner-worker.cc: In member function ‘virtual void OnigScannerWorker::HandleOKCallback()’:
../src/onig-scanner-worker.cc:37:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-scanner-worker.cc:43:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-v4.2.1-node-v57-linux-ia32.tar.gz
prebuild-install info looking for cached prebuild @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v57-linux-ia32.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v57-linux-ia32.tar.gz
prebuild-install info unpack resolved to /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
prebuild-install info unpack required /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!
(node:2557) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
../src/onig-scanner-worker.cc: In member function ‘virtual void OnigScannerWorker::HandleOKCallback()’:
../src/onig-scanner-worker.cc:37:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-scanner-worker.cc:43:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-v4.2.1-node-v48-linux-ia32.tar.gz
prebuild-install info looking for cached prebuild @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v48-linux-ia32.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v48-linux-ia32.tar.gz
prebuild-install info unpack resolved to /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
prebuild-install info unpack required /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!
...
LevelUPError: Failed to require LevelDOWN (The module '/home/ruehmann/atom/script/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).). Try `npm install leveldown` if it's missing
  at requireError (/home/ruehmann/atom/script/node_modules/levelup/lib/leveldown.js:37:10)
  at getLevelDOWN (/home/ruehmann/atom/script/node_modules/levelup/lib/leveldown.js:31:11)
  at LevelUP.open (/home/ruehmann/atom/script/node_modules/levelup/lib/levelup.js:112:34)
  at new LevelUP (/home/ruehmann/atom/script/node_modules/levelup/lib/levelup.js:84:8)
  at LevelUP (/home/ruehmann/atom/script/node_modules/levelup/lib/levelup.js:45:44)
  at Promise (/home/ruehmann/atom/script/node_modules/electron-link/lib/transform-cache.js:87:7)
  at new Promise (<anonymous>:null:null)
  at TransformCache._initialize (/home/ruehmann/atom/script/node_modules/electron-link/lib/transform-cache.js:86:12)
  at /home/ruehmann/atom/script/node_modules/electron-link/lib/transform-cache.js:18:19
  at Generator.next (<anonymous>:null:null)
  at step (/home/ruehmann/atom/script/node_modules/electron-link/lib/transform-cache.js:1:253)
  at /home/ruehmann/atom/script/node_modules/electron-link/lib/transform-cache.js:1:499
  at new Promise (<anonymous>:null:null)
  at /home/ruehmann/atom/script/node_modules/electron-link/lib/transform-cache.js:1:161
  at TransformCache.loadOrCreate (/home/ruehmann/atom/script/node_modules/electron-link/lib/transform-cache.js:29:7)
  at /home/ruehmann/atom/script/node_modules/electron-link/lib/index.js:10:17
  at Generator.next (<anonymous>:null:null)
  at step (/home/ruehmann/atom/script/node_modules/electron-link/lib/index.js:1:253)
  at /home/ruehmann/atom/script/node_modules/electron-link/lib/index.js:1:499
  at new Promise (<anonymous>:null:null)
  at /home/ruehmann/atom/script/node_modules/electron-link/lib/index.js:1:161
  at module.exports (/home/ruehmann/atom/script/node_modules/electron-link/lib/index.js:19:17)
  at module.exports (/home/ruehmann/atom/script/lib/generate-startup-snapshot.js:13:10)
  at binariesPromise.then.then.packagedAppPath (/home/ruehmann/atom/script/build:80:28)
  at <anonymous>:null:null
  at process._tickCallback (internal/process/next_tick.js:188:7)

```
What´s up?
### Steps to Reproduce
Run script/build

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
no messages

**Actual behavior:** [What actually happens]
see above

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
```
Node:   v8.9.3
Npm:    v5.3.0
apm  1.19.0
npm  3.10.10
node 6.9.5 ia32
atom 1.25.0-dev-26df68c
python 2.7.12
git 2.7.4
```

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information
I usualy Update Daily by that Script.
```
#!/bin/bash

ZIEL=$PWD
#BRANCH=master
BRANCH=master
#NODE=7.4.0
NODE=8.9.3
NODER=9.2.0

cd ~/
if [ -d "/usr/share/atom" ]
then
  sudo chown -R root:users /usr/share/atom/ 2> /dev/null
  sudo chmod -R g+w /usr/share/atom/ 2> /dev/null
  if [ -d "atom" ]
    then
      echo "Sourcen Updaten"
      cd atom
      ALTE_ATOM_VERSION="$(git describe --tags)" 2> /dev/null
      #git checkout $BRANCH
      GIT_PULL=$(git pull | grep -c "Already up-to-date.")
      NEUE_ATOM_VERSION="$(git describe --tags)" 2> /dev/null
        if [ $GIT_PULL -ge 1 ]
        then
          echo "Already up-to-date."
        else
          echo "Programm erzeugen & installieren"
          sudo -H n $NODE
          find ~/ -name package-lock.json -delete > /dev/null
	  script/build > /dev/null
	  packagedAppPath=$(echo ~/atom/out/atom-*)
	  sudo node -e "require('./script/lib/install-application')('$packagedAppPath', '')" > /dev/null
	  sudo -H n $NODER
        fi
    else
      echo "Aktuelle Sourcen Clonen"
      git clone https://github.com/atom/atom.git &>/dev/null
      cd atom
      echo "Programm erzeugen & installieren"
      sudo -H n $NODE
      find ~/ -name package-lock.json -delete > /dev/null
      script/build > /dev/null
      packagedAppPath=$(echo ~/atom/out/atom-*)
      sudo node -e "require('./script/lib/install-application')('$packagedAppPath', '')" > /dev/null
      sudo -H n $NODER
  fi
fi
MESSAGE="Das Tägliche Atom Update auf $(hostname) wurde durchgeführt.
alte Versionen:
atom $ALTE_ATOM_VERSION
--------------------------------------
neue Versionen:
atom $NEUE_ATOM_VERSION
--------------------------------------

Atom github Link: https://github.com/atom/atom/commits/$BRANCH"

cd "$ZIEL"

exit 0
```

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment] 2018-04-11 16:26
I can't reproduce this locally building 8cacc6b1f, could you answer the following questions?

Have you tried a clean build (`script/clean`)?
What commit is it breaking on?
What was the last working commit? (26df68c?)
What OS are you on?

**Comment by JPRuehmann** [comment] 2018-04-11 17:28
Have you tried a clean build (script/clean)?
No
What commit is it breaking on?
```
Sourcen Updaten
Von https://github.com/atom/atom
   8ef1a05..6dd878d  master     -> origin/master
 * [neuer Branch]    b3-bump-tree-view -> origin/b3-bump-tree-view
 * [neuer Branch]    deprecate-undo-skip -> origin/deprecate-undo-skip
 * [neuer Branch]    tt-update-tos-link -> origin/tt-update-tos-link
 * [neues Tag]       v1.25.1    -> v1.25.1
 * [neues Tag]       v1.26.0-beta1 -> v1.26.0-beta1
Programm erzeugen & installieren
/home/ruehmann/atom/script/lib/backup-node-modules.js:9
    throw new Error('Cannot back up ' + nodeModulesPath + '; ' + nodeModulesBackupPath + ' already exists')
    ^

Error: Cannot back up /home/ruehmann/atom/node_modules/github/node_modules; /home/ruehmann/atom/node_modules/github/node_modules.bak already exists
  at module.exports (/home/ruehmann/atom/script/lib/backup-node-modules.js:9:11)
  at module.exports (/home/ruehmann/atom/script/lib/transpile-packages-with-custom-transpiler-paths.js:25:33)
  at Object.<anonymous> (/home/ruehmann/atom/script/build:66:3)
  at Module._compile (module.js:624:30)
  at Object.Module._extensions..js (module.js:635:10)
  at Module.load (module.js:545:32)
  at tryModuleLoad (module.js:508:12)
  at Function.Module._load (module.js:500:3)
  at Function.Module.runMain (module.js:665:10)
  at startup (bootstrap_node.js:187:16)
  at bootstrap_node.js:607:3

fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/home/ruehmann/atom/out/atom-*'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (/home/ruehmann/atom/script/node_modules/graceful-fs/polyfills.js:297:22)
    at Object.copySync (/home/ruehmann/atom/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:21:84)
    at install (/home/ruehmann/atom/script/lib/install-application.js:19:6)
    at module.exports (/home/ruehmann/atom/script/lib/install-application.js:79:5)
    at [eval]:1:44
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
Apr 06 02:38:43 sakura sendEmail[29265]: Email was sent successfully!

```
What was the last working commit? (26df68c?)
```
Sourcen Updaten
Von https://github.com/atom/atom
   9a81957..8ef1a05  master     -> origin/master
   66852b3..cd30b79  1.26-releases -> origin/1.26-releases
Programm erzeugen & installieren
Packaging app for platform linux ia32 using electron v1.7.11
gtk-update-icon-cache: Cache file created successfully.
Apr 04 02:59:45 sakura sendEmail[5219]: Email was sent successfully!
```
After this daily changing messages.

What OS are you on?
Kubuntu 16.04 LTS (32Bit)

**Comment by Arcanemagus** [comment] 2018-04-11 17:47
Can you try a clean build (`script/clean && script/build`)? It looks like there are several issues with the current directory that should be cleared up by that.

Also, you may want to review the [Building Instructions](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#building), your script currently is hard coding some things that the script can take care of for you.

**Comment by JPRuehmann** [comment] 2018-04-11 18:17
a script/build after script/clean gives
```
Node:   v8.9.3
Npm:    v5.5.1
Installing script dependencies
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.9.0-node-v57-linux-ia32.tar.gz
prebuild-install info looking for cached prebuild @ /home/ruehmann/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v57-linux-ia32.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v57-linux-ia32.tar.gz
prebuild-install http 404 https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v57-linux-ia32.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.9.3 runtime=node arch=ia32 platform=linux)
../deps/leveldb/leveldb-1.20/db/version_set.cc: In member function ‘bool leveldb::Version::RecordReadSample(leveldb::Slice)’:
../deps/leveldb/leveldb-1.20/db/version_set.cc:436:27: warning: ‘state.leveldb::Version::RecordReadSample(leveldb::Slice)::State::stats.leveldb::Version::GetStats::seek_file’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       file_to_compact_ = f;
                           ^
../deps/leveldb/leveldb-1.20/db/version_set.cc:467:9: note: ‘state.leveldb::Version::RecordReadSample(leveldb::Slice)::State::stats.leveldb::Version::GetStats::seek_file’ was declared here
   State state;
         ^
Installing apm
../src/onig-scanner-worker.cc: In member function ‘virtual void OnigScannerWorker::HandleOKCallback()’:
../src/onig-scanner-worker.cc:37:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-scanner-worker.cc:43:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-v4.2.1-node-v57-linux-ia32.tar.gz
prebuild-install info looking for cached prebuild @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v57-linux-ia32.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v57-linux-ia32.tar.gz
prebuild-install info unpack resolved to /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
prebuild-install info unpack required /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!
(node:20007) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
../src/onig-scanner-worker.cc: In member function ‘virtual void OnigScannerWorker::HandleOKCallback()’:
../src/onig-scanner-worker.cc:37:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-scanner-worker.cc:43:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-v4.2.1-node-v48-linux-ia32.tar.gz
prebuild-install info looking for cached prebuild @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v48-linux-ia32.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v48-linux-ia32.tar.gz
prebuild-install info unpack resolved to /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
prebuild-install info unpack required /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```
I hardcoded it because of that Issue.
`Installing after build fails with a permission error #14848`

**Comment by Arcanemagus** [comment] 2018-04-11 19:06
Those are just warnings, did the build complete?

**Comment by JPRuehmann** [comment] 2018-04-11 19:14
yes
If that are only warnings, why are tey appear via stderr?
The stderr is reserved for errors!
warnings shoul use stdout.

I canged the Script.
```
#!/bin/bash

ZIEL=$PWD
#BRANCH=master
BRANCH=master
#NODE=7.4.0
NODE=8.9.3
NODER=9.2.0

cd ~/
if [ -d "/usr/share/atom" ]
then
  sudo chown -R root:users /usr/share/atom/ 2> /dev/null
  sudo chmod -R g+w /usr/share/atom/ 2> /dev/null
  if [ -d "atom" ]
    then
      echo "Sourcen Updaten"
      cd atom
      ALTE_ATOM_VERSION="$(git describe --tags)" 2> /dev/null
      #git checkout $BRANCH
      GIT_PULL=$(git pull | grep -c "Already up-to-date.")
      NEUE_ATOM_VERSION="$(git describe --tags)" 2> /dev/null
        if [ $GIT_PULL -ge 1 ]
        then
          echo "Already up-to-date."
        else
          echo "Programm erzeugen & installieren"
          sudo -H n $NODE
          find ~/ -name package-lock.json -delete > /dev/null
	  script/clean > /dev/null
	  script/build > /dev/null
	  packagedAppPath=$(echo ~/atom/out/atom-*)
	  sudo node -e "require('./script/lib/install-application')('$packagedAppPath', '')" > /dev/null
	  sudo -H n $NODER
        fi
    else
      echo "Aktuelle Sourcen Clonen"
      git clone https://github.com/atom/atom.git &>/dev/null
      cd atom
      echo "Programm erzeugen & installieren"
      sudo -H n $NODE
      find ~/ -name package-lock.json -delete > /dev/null
      script/clean > /dev/null
      script/build > /dev/null
      packagedAppPath=$(echo ~/atom/out/atom-*)
      sudo node -e "require('./script/lib/install-application')('$packagedAppPath', '')" > /dev/null
      sudo -H n $NODER
  fi
fi
MESSAGE="Das Tägliche Atom Update auf $(hostname) wurde durchgeführt.
alte Versionen:
atom $ALTE_ATOM_VERSION
--------------------------------------
neue Versionen:
atom $NEUE_ATOM_VERSION
--------------------------------------

Atom github Link: https://github.com/atom/atom/commits/$BRANCH"

cd "$ZIEL"

exit 0
```
Now it gives.
```
Sourcen Updaten
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 15 (delta 10), reused 13 (delta 8), pack-reused 0
Entpacke Objekte: 100% (15/15), Fertig.
Von https://github.com/atom/atom
   06c219c..282fd85  master     -> origin/master
 * [neuer Branch]    snippets-1.3.2 -> origin/snippets-1.3.2
Programm erzeugen & installieren
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.9.0-node-v57-linux-ia32.tar.gz
prebuild-install info looking for cached prebuild @ /home/ruehmann/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v57-linux-ia32.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v57-linux-ia32.tar.gz
prebuild-install http 404 https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v57-linux-ia32.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=8.9.3 runtime=node arch=ia32 platform=linux)
../deps/leveldb/leveldb-1.20/db/version_set.cc: In member function ‘bool leveldb::Version::RecordReadSample(leveldb::Slice)’:
../deps/leveldb/leveldb-1.20/db/version_set.cc:436:27: warning: ‘state.leveldb::Version::RecordReadSample(leveldb::Slice)::State::stats.leveldb::Version::GetStats::seek_file’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       file_to_compact_ = f;
                           ^
../deps/leveldb/leveldb-1.20/db/version_set.cc:467:9: note: ‘state.leveldb::Version::RecordReadSample(leveldb::Slice)::State::stats.leveldb::Version::GetStats::seek_file’ was declared here
   State state;
         ^
../src/onig-scanner-worker.cc: In member function ‘virtual void OnigScannerWorker::HandleOKCallback()’:
../src/onig-scanner-worker.cc:37:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-scanner-worker.cc:43:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-v4.2.1-node-v57-linux-ia32.tar.gz
prebuild-install info looking for cached prebuild @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v57-linux-ia32.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v57-linux-ia32.tar.gz
prebuild-install info unpack resolved to /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
prebuild-install info unpack required /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!
(node:24802) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
../src/onig-scanner-worker.cc: In member function ‘virtual void OnigScannerWorker::HandleOKCallback()’:
../src/onig-scanner-worker.cc:37:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-scanner-worker.cc:43:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/onig-scanner-worker.h:7:0,
                 from ../src/onig-scanner-worker.cc:1:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:30:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-v4.2.1-node-v48-linux-ia32.tar.gz
prebuild-install info looking for cached prebuild @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v48-linux-ia32.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /home/ruehmann/.npm/_prebuilds/https-github.com-atom-node-keytar-releases-download-v4.2.1-keytar-v4.2.1-node-v48-linux-ia32.tar.gz
prebuild-install info unpack resolved to /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
prebuild-install info unpack required /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!
Packaging app for platform linux ia32 using electron v1.7.11
gtk-update-icon-cache: Cache file created successfully.
Apr 11 21:13:28 sakura sendEmail[25864]: Email was sent successfully!

```

**Comment by Arcanemagus** [comment] 2018-04-11 19:34
> If that are only warnings, why are they appear via stderr? The stderr is reserved for errors! warnings should use stdout.

You would have to take that up with your platform's compiler that is doing the compiling 😉.

Since it seems like you have resolved your build issues I'm marking this as closed.

Thanks for reaching out!

----

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Closed by Arcanemagus** 2018-04-11 19:34 UTC
Labels: more-information-needed

**Comment by JPRuehmann** [comment] 2018-04-12 05:58
You would have to take that up with your platform's compiler that is doing the compiling wink.
I that is the point why it worked until some days ago???
Why it works with all other programms???

The failure is your script that seems to pull all messages to stderr you can see this by running script/build > /dev/null as in my script. then there should be nothing buit your script shows everything (normal, warnings and error) messages since for example script clean or the hardcoded part works normaly there must be a Bug in your build script. It is not the first time there were issues before in that the script has thrown warnings vie the stderr.

It would be helpfull for the overall useabilty of the automatic update if there are only errors on the stderr.

I don´t think it is a good Idea to put the blame on someone else so easy!

Thanks.

Since it seems like you have resolved your build issues I'm marking this as closed.

Thanks for reaching out!
