### ISSUE TITLE
Strange background-color artifacts in TextEditor in Atom 1.17-beta4

### ISSUE THREAD

**Issue by jgebhardt** [atom/atom#14337] opened 2017-05-02 10:00 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
In Atom 1.17-beta4, the text editor shows strange background color artifacts when Atom is shown on an external monitor:

![atom-1-17-screen-issue](https://cloud.githubusercontent.com/assets/632968/25613273/8c0502de-2f25-11e7-9673-e1cf9d09e69d.gif)

These artifacts don't show up on my macbook's retina display; only on the external monitor (In the gif above, you can see me dragging the Atom window from my retina screen to the external monitor.

The issue goes away if I remove either the `transform` or `background-color` properties of the 6-line `<div/>` element in the text editor. The artifacts also seem to be influenced by the cursor position. 

### Steps to Reproduce

1. Open Atom Beta on external monitor
2. text editor shows artifacts
3. Moving the cursor will change the artifacts

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% under the above conditions

**Comment by hultberg** [comment] 2017-05-02 10:43
Duplicate of #12634

**Comment by Ben3eeE** [comment] 2017-05-02 10:49
@jgebhardt Some users have reported that changing their color profile for their monitor has corrected the problem.

@hultberg Thanks :bowing_man: 

----

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12634. 
Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-05-02 10:49 UTC
