### ISSUE TITLE
Atom beta replaces stable version

### ISSUE THREAD

**Issue by ultimoamore** [atom/atom#13016] opened 2016-10-18 13:01 UTC
Installed 1.12.0-beta2 because "The Atom Beta runs side-by-side with the Atom stable release", yet I can't find my 1.11 stable anymore...

**Comment by michaelmano** [comment] 2016-10-18 13:56
What os are you on? 

If windows go to %localappdata% (type that into ur explorer.) 

Then you will see the atom folder. Go into that and see if there is the folder you mention. If it exists you only have to change the properties of the shortcut launcher.

Thats located at %appdata%\Microsoft\Programs\Start Menu\Github, inc  or the easy way is to right click on the short cut in the start menu and go to location.

Then right click it and select properties change the start in location to the correct folder.

**Comment by ultimoamore** [comment] 2016-10-18 14:22
It's Win7. In %localappdata%\Atom I have:

 app-1.12.0-beta2
 app.ico
 bin
 packages
 SquirrelSetup.log
 Update.exe

Bin is empty now; it contained the old 1.11 version, but has been removed by 1.12...

**Comment by lee-dohm** [comment] 2016-10-26 05:55
@Ben3eeE According to [this comment](https://github.com/atom/atom/issues/9247#issuecomment-233805496) this is supposed to now be available via the new System tab in the Settings View on Windows. Can you verify if it is there and if it is still working?

If it isn't working, please close this as a duplicate and reopen #9247.

**Comment by michaelmano** [comment] 2016-10-26 06:17
@lee-dohm he doesen't even have the old version in his folders. I believe he may have removed it or it was removed.

He will have to reinstall the current stable version and then it will show in the system tab i believe.

**Comment by Ben3eeE** [comment] 2016-10-26 09:03
@lee-dohm Thanks for reminding me. I did not close right away because I have seen similar behavior and wanted to test it out. It seems that #9247 should be reopened. Because I couldn't get them to install side by side. Installing beta after installing stable removed stable from my Windows 7 computer just as the original report claims.

I don't see any setting in the System tab enabling me to run beta and stable side by side. I see three options for shell integrations. I posted my experience in #9247.

Closing as a duplicate of #9247. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-26 09:03 UTC
Labels: windows
