### ISSUE TITLE
[bug?] Soft Wrap not works right with Chinese characters

### ISSUE THREAD

**Issue by flyisland** [atom/atom#8078] opened 2015-07-25 16:40 UTC
I narrowed the editor window to 10 English characters width, and enable "Soft Wrap".

Type 'abcedfghijklmn', it works well, the 'k' is wrapped to second line.

Type '一二三四五六七八九十', it now works right, nothing is wrapped and only the first five characters are displayed.

Type '一二三四五六七八九十一', then the eleventh character '一' is wrapped to second line.

**Comment by 50Wliu** [comment] 2015-07-25 18:44
This looks like a duplicate of #1783 - please subscribe there for updates.

**Closed by 50Wliu** 2015-07-25 18:44 UTC
