### ISSUE TITLE
Updating UI never indicates when the update is finished.

### ISSUE THREAD

**Issue by AustP** [atom/atom#7217] opened 2015-06-10 20:19 UTC
To reproduce:

1. Go to Available Updates.
2. Make sure you have packages that need updates.
3. Hit "Update All".

The Update button within the package cards will change to ":cloud: Updating..." with the stripes running right to left. Leave this page open and come back 5 minutes later. It will still say updating. But if you reload Atom, the packages will be updated.

This is in the latest version. (0.208.0)

**Comment by mnquintana** [comment] 2015-06-10 21:26
This is a duplicate of github.com/atom/settings-view/issues/532 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-10 21:26 UTC
