### ISSUE TITLE
Scrolling issue + Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by arnav-gudibande** [atom/atom#15340] opened 2017-08-16 18:19 UTC
1. Installed Remote-Edit on Atom

Now, I cannot scroll through remote files on Atom

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Invalid array length

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2818

RangeError: Invalid array length
    at TextEditorComponent.populateVisibleTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2818:45)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:363:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:266:16)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1516:43)
```

### Commands

```
     -2:33.6.0 core:confirm (input.hidden-input)
     -1:53.6.0 remote-edit:browse (input.hidden-input)
     -1:47.9.0 remote-edit:new-host-sftp (input.hidden-input)
     -1:40.9.0 core:paste (input.hidden-input)
  8x -1:38 core:backspace (input.hidden-input)
     -0:56.6.0 fuzzy-finder:toggle-git-status-finder (input.hidden-input)
     -0:50.3.0 remote-edit:browse (input.hidden-input)
  3x -0:47.6.0 core:confirm (input.hidden-input)
 12x -0:24.6.0 core:move-down (input.hidden-input)
  9x -0:22.4.0 core:move-up (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
color-picker 2.2.5 
hybrid-next-syntax 0.9.2 
minimap 4.27.1 
remote-edit 1.9.0 
turbo-javascript 1.4.0 
```

**Comment by Ben3eeE** [comment] 2017-08-16 18:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15247. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-16 18:28 UTC
Labels: duplicate
