### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 12Error: Cannot call...

### ISSUE THREAD

**Issue by cipherjai** [atom/atom#17024] opened 2018-03-24 13:34 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 12
Error: Cannot call function 'getPosition' on missing remote object 12
    at throwRPCError (C:\Users\Natasha\AppData\Local\atom\app-1.25.0\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\Natasha\AppData\Local\atom\app-1.25.0\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\Users\Natasha\AppData\Local\atom\app-1.25.0\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At C:\Users\Natasha\AppData\Local\atom\app-1.25.0\resources\electron.asar\renderer\api\remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 12
Error: Cannot call function 'getPosition' on missing remote object 12
    at throwRPCError (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.25.0/resources/app/src/atom-environment.js:691:40)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.25.0/resources/app/src/atom-environment.js:728:40)
    at WindowEventHandler.handleWindowResize (~/AppData/Local/atom/app-1.25.0/resources/app/src/window-event-handler.js:195:32)
```

### Commands

```
     -4:36 application:open-folder (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-03-26 17:28
Thanks for the report - this looks like a duplicate of #16630 so you can subscribe there for updates if you'd like.  If you remember what you were doing at the time of the error or if you can reproduce, please let us know in #16630.  Also, do you happen to remember if you tabbed out of Atom and then switched back when you saw the error?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-26 17:28 UTC
