### ISSUE TITLE
Atom always opens the chrome developer tools on startup.

### ISSUE THREAD

**Issue by ptnalexa** [atom/atom#9220] opened 2015-10-20 02:10 UTC
As you can see down below, atom has opened the Chrome Developer Tools on startup and has caused atom to display a white screen. When I close the Developer Tools pane, the white screen still remains.
While I'm not confused as to why the Developer Tools may open within atom, I am confused as to why this pane would open every time at startup. Take a look;
![devtoolsbug](https://cloud.githubusercontent.com/assets/8274204/10596082/8fda644c-76a5-11e5-967e-3c26bf899a52.jpg)

Thanks. :)

**Comment by mnquintana** [comment] 2015-10-20 02:25
Looks like there's an error on startup - can you click the error icon in the DevTools and paste the error you see here? Also, does this still happen if you quit Atom completely and then reopen it in safe mode? (`atom --safe`)

**Comment by MajikalPayton** [comment] 2015-10-20 02:26
1. It happens in safe mode

**Comment by MajikalPayton** [comment] 2015-10-20 02:27
A non-responding atom, that is. Let me get you that screen-shot. :)

**Comment by MajikalPayton** [comment] 2015-10-20 02:31
http://pastebin.com/Mv2NiWDM
This is the error message.

**Comment by MajikalPayton** [comment] 2015-10-20 04:47
Have you figured out what the problem is?

**Comment by benogle** [comment] 2015-10-22 00:39
It cant find git-utils. When did you download atom? How did you install it?

**Comment by benogle** [comment] 2015-10-22 00:40
Did this happen immediately after install? After some other event? Maybe after an update?

**Comment by MajikalPayton** [comment] 2015-10-22 03:13
This happened immediately after install. I had not installed anything before, after, or while I had installed atom.

**Comment by z3to** [comment] 2015-12-30 16:09
I’m having the same problem, however with a different error-message:

![Screenshott](https://photos-6.dropbox.com/t/2/AAAqtw5h-nMBr1oKcwZT2OUCdmlKde8tPRSvLDtCCpnrQA/12/2716098/jpeg/32x32/1/_/1/2/Screenshot%202015-12-30%2017.05.14.JPG/EMmQigIYxawcIAIoAg/_nPj6XZH2FNhBgQJKRWLXijJp6-FLJcBj6PTs8RJEds?size=1600x1200&size_mode=3)

```javascript
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at FileSystemBlobStore.load (/Applications/Atom.app/Contents/Resources/app.asar/src/file-system-blob-store.js:36:31)
    at Function.load (/Applications/Atom.app/Contents/Resources/app.asar/src/file-system-blob-store.js:10:14)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:18:39)
```

It happend after Atom crashed for no obvious reason. I reinstalled Atom, but it doesn’t help.

**Comment by 50Wliu** [comment] 2015-12-30 16:12
Hi @z3to, for your issue, please delete the `~/.atom/blob-store` folder.

**Comment by z3to** [comment] 2015-12-30 16:15
Thanks, @50Wliu! That indeed solved the issue for me.

**Comment by satya164** [comment] 2016-01-02 03:02
Happened for me too. @50Wliu 's solution fixed it. But why did it happen in the first place? I guess due to a corrupted update?

**Comment by 50Wliu** [comment] 2016-01-02 03:24
> I guess due to a corrupted update?

Kind of.  1.3.0 introduced a new cache to help speed up startup times, but there was a rare edge case when two very similar functions would get cached, and V8 couldn't tell the difference between the two, leading to this error.  I believe this has been fixed in 1.3.2, so you shouldn't experience this again.

**Comment by satya164** [comment] 2016-01-02 14:43
@50Wliu Cool. Thanks for letting me know.

**Comment by timhogenbirk** [comment] 2016-01-12 10:23
Thanks, @50Wliu!

**Comment by theorise** [comment] 2016-01-26 09:20
Just had this happen too, as above @50Wliu's solution fixed it, thanks.

**Comment by garug** [comment] 2016-03-02 19:25
![image](https://cloud.githubusercontent.com/assets/10871016/13472354/4915bdba-e093-11e5-9ec5-1dd4eb7b5d9b.png)


I have the same problem but many other errors. Anybody have solution?

**Comment by 50Wliu** [comment] 2016-03-02 20:51
Looks like one of your style files are corrupted.  An easy way to fix this is to remove `~/.atom/styles.less` and `~/.atom/packages/`, though that will remove your custom styles and all your installed packages.

**Comment by garug** [comment] 2016-03-02 21:38
I fixed error restoring a backup of yesterday. Idk, i not open the program since last week. Anyway, thanks.

**Comment by dan-conachi** [comment] 2016-03-24 14:02
After last update I'm also getting the dev tools on open. It seems like one on=f the module is `missing:
`Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:17:12)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository-provider.js:8:19)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository-provider.js:83:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)`

The problem is that even if I remove it with --purge and reinstall it again, I get the same problem.
I thought it's related to some saved config so I removed ~/.atom/ folder, but with no success, atom still loading dev tools on start.

Would be thankful for some suggestion to fix this.
Thank you

**Comment by 50Wliu** [comment] 2016-03-28 17:19
@dan-conachi Your issue is covered by #10819.

**Comment by damieng** [comment] 2016-04-13 19:38
There doesn't appear to be anything left unresolved in this issue.

If you get are getting this problem check the error by hitting the red circle with white x) and then check to see if there is an issue for that specific error text.

**Closed by damieng** 2016-04-13 19:38 UTC
Labels: more-information-needed, windows

**Comment by roshimon** [comment] 2016-04-16 06:44
Upgrading to atom 1.8.0-beta1 has fixed the issue for me. Working flawlessly now :)

**Comment by airtonix** [comment] 2016-08-05 02:24
Still happening: 
```
index.js:62 TypeError: Cannot read property 'PWD' of undefined
    at updateProcessEnv (update-process-env.js:9)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:11)
    at setupWindow (index.js:87)
    at window.onload (index.js:41)handleSetupError @ index.js:62
```

**Comment by mnquintana** [comment] 2016-08-05 02:29
@airtonix Sorry to hear you're running into that! You can track that one at https://github.com/atom/atom/issues/12328

Since this is a very broad, non-actionable issue, I'm going to lock this to keep noise levels down. If anyone runs into a specific uncaught exception that causes the DevTools to pop up, take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) first, then feel free to open a new issue.
