### ISSUE TITLE
Open Folder locking delete

### ISSUE THREAD

**Issue by rudarobson** [atom/atom#6682] opened 2015-05-07 14:34 UTC
I'm using Atom 0.196.0  on Windows,
when deleting a folder and this folder is open at atom folder explorer (enpanded on left bar) 
EPERM is thrown. 

Expected Behavior:
 1) Atom shouldn't lock the folder,allowing to delete it from another running program
 2) After the folder is deleted, atom must reload the file explorer and do not list that folder nor it's files

**Comment by 50Wliu** [comment] 2015-05-07 15:55
Duplicate of #3365, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-07 15:55 UTC
