### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.33.1\ChargeB...

### ISSUE THREAD

**Issue by Flawededge** [atom/atom#18663] opened 2019-01-08 19:42 UTC
1. I moved a file from one project folder to another
Both folders are network folders, which are mapped to the F drive. I don't have the issue when using local folders

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\ven.chris.diggle\AppData\Local\atom\app-1.33.1\ChargeBatt2.csv'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\ven.chris.diggle\AppData\Local\atom\app-1.33.1\ChargeBatt2.csv'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:916493)
    at TreeView.t.exports.TreeView.onDrop (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:922247)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:896158)
```

### Commands

```
     -1:24.3.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:07.7.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:50.5.0 core:paste (input.hidden-input)
     -0:50 core:confirm (input.hidden-input)
     -0:45.1.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2019-01-08 23:56
Thanks for contributing!

Based on the stack trace, this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

One additional thing to mention is that based on the path mentioned on the error message, it looks like you have files saved in Atom's installation directory?  I'd recommend moving the files elsewhere because that directory can be removed after Atom upgrades.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-01-08 23:56 UTC
