### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received ~

### ISSUE THREAD

**Issue by giibran** [atom/atom#14604] opened 2017-05-24 04:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Proxy.tildify (/Applications/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:71:1)
    at Workspace.updateWindowTitle (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:643:1)
    at Workspace.didChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:497:1)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:471:1)
    at Dock.subscriptions.CompositeDisposable.paneContainer.onDidActivatePane (/Applications/Atom.app/Contents/Resources/app/src/dock.js:57:1)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:260:1)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:875:1)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:269:1)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:51:25)
```

### Commands

```
     -0:50.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-05-24 17:29
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14227. You may want to subscribe there for updates - if you can share specific steps to reproduce as well, that would be super helpful.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-24 17:29 UTC
