### ISSUE TITLE
On Linux cannot navigate between menus with left and right

### ISSUE THREAD

**Issue by stuaxo** [atom/atom#18132] opened 2018-09-27 21:02 UTC
In Linux you cannot move from one menu to the next by pressing left and right.
Tested on Ubuntu 18.04, but also whatever version was current back a few years.

To reproduce:

Open any menu (e.g. alt-f to open file menu) press left and right and notice you stay on the same menu.

I've previously opened this with at least one downstream project + been directed here, I'll try and find the bug and link it.

**Comment by rsese** [comment] 2018-09-28 00:29
Thanks for contributing!

This is a duplicate of https://github.com/atom/atom/issues/5998 so we'll close in favor of that issue (it looks like you've commented there already).  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-09-28 00:29 UTC

**Comment by stuaxo** [comment] 2018-09-28 07:07
Thanks, I don't always remember where I've submitted bugs !
