### ISSUE TITLE
Fail uninstall package 

### ISSUE THREAD

**Issue by torn4dom4n** [atom/atom#11527] opened 2016-04-19 15:53 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I try to uninstall some packages in Atom editor and it show fail because: `Does not exist` look like:

![screenshot](https://cloud.githubusercontent.com/assets/16760489/14645583/6db219d0-0680-11e6-89ea-fe6d01a34ed9.png)

### Steps to Reproduce

1. Open setting
2. Uninstall a package

**Expected behavior:** Uninstall finish

**Actual behavior:** Uninstall fail because:`Does not exist`

### Versions
Windows 10, version 1511 build 10586

Atom: 1.7.2

**Comment by 50Wliu** [comment] 2016-04-19 16:15
This is a duplicate of #11464 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-19 16:15 UTC
