### ISSUE TITLE
Opened project folders are not persisted?

### ISSUE THREAD

**Issue by carloscarnero** [atom/atom#11972] opened 2016-06-13 15:08 UTC
### Description

One of the most useful features that I constantly use is adding a project folder. This effectively means that, on the same Atom instance, I can work on several projects at once (sometimes completely unrelated projects.)

As of 1.8.0 I can't remove a project folder. Well, it is removed when requested, but on the next Atom startup the folder re-appears. I have tried under safe mode and I observe the same thing.

### Steps to Reproduce

1. Add several projects to the running instance using the _Add Project Folder..._ menu item.
2. (optionally) Close Atom and start it up again. All the folders show up in the tree view.
3. Remove one of the above projects by right clicking on top of it, and then _Remove Project Folder_. At this moment the project is indeed removed from the tree view.
4. Close Atom and start it up again.
5. All the folders show up in the tree view, including the removed one.

### Versions

Running under Ubuntu Linux 16.04 `atom --version` yields

```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

and `apm --version`

```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11+
git 2.7.4
```

Note that **previous Atom versions, i. e., 1.7.x, worked as espected**. I started seeing this behavior after upgrading to 1.8.0. Unfortunately I have only access to Ubuntu, so I can't try to replicate under other OSes.

**Comment by feub** [comment] 2016-06-14 10:55
I have a slightly different behaviour since 1.8.0, the project folders are not persistent at all after restarting. Everytime I close and start Atom, I get a blank buffer, no Tree view, and all projects gone.
Running under Windows 10

**Comment by Nikki1993** [comment] 2016-06-14 15:53
I have a similar thing on OS X el capitan with atom 1.8.0

**Comment by not-an-aardvark** [comment] 2016-06-22 22:05
I'm also experiencing this issue on OSX. It seems like the list of project folders isn't getting saved.

As a workaround, I've been able to get around the issue by doing the following:

1. Open Atom
1. Add the project folders that you need
1. Open a file from one of the project folders
1. Edit that file somehow, and save
1. (Revert the edit if you want to)
1. Close Atom
1. Open Atom again

The project folders that you added should still be there.

**Comment by MartinNowack** [comment] 2016-08-12 08:16
I've got the same issues as described above.
One side note, I'm working with Atom in full screen mode on OSX.

**Workaround:** switch app focus in between.

1. Add/Remove one project folder (depending on what you want to do)
2. Switch to another application
3. Switch back to Atom
4. Now you can close it.

If you open it again, it will be in the state as when you closed it.

I guess, re-focusing atom forces it to finish the action (updating `~/.atom/storage/application.json`).

**Comment by carloscarnero** [comment] 2016-08-12 13:04
Wow, nice catch! Switching focus did the trick.

**Comment by Ben3eeE** [comment] 2016-10-06 16:35
Closing as a duplicate of https://github.com/atom/atom/issues/12495. This issue was reported before https://github.com/atom/atom/issues/12495 but the other has more discussion. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-06 16:35 UTC
Labels: needs-reproduction
