### ISSUE TITLE
Atom Helper burns CPU when checking packages

### ISSUE THREAD

**Issue by g13013** [atom/atom#10475] opened 2016-01-18 10:54 UTC
Everytime I open the preferences to check, install or update packages, the CPU reaches 100% ! also Atom becomes very slow

PS: I was having this problem with previous versions of Atom

Information:
OS: OSX Mavericks 10.9.5
Atom: 1.4

installed packages:
````
├── Handlebars@1.2.1
├── atom-autocomplete-php@0.18.4
├── atom-beautify@0.28.21
├── atom-ctags@4.4.2
├── atom-handlebars@1.3.0
├── atom-innerspace@0.1.5
├── atom-material-syntax@0.2.10
├── atom-material-ui@0.8.0
├── atom-snippets@0.1.1
├── atom-ternjs@0.12.2
├── auto-detect-indentation@0.4.2
├── autoclose-html@0.19.0
├── autocomplete-ctags@0.3.3
├── autocomplete-go@0.1.1
├── autocomplete-python@1.3.0
├── builder@0.0.1
├── change-case@0.6.0
├── color-picker@2.0.14
├── docblockr@0.7.3
├── dockerletion@0.1.0
├── editorconfig@1.2.2
├── environment@1.1.1
├── file-icons@1.6.13
├── filesize@0.4.2
├── git-blame@0.4.8
├── git-log@0.4.1
├── git-time-machine@1.2.3
├── go-config@0.3.1
├── highlight-nbsp@0.1.1
├── highlight-selected@0.11.1
├── indentation-jumper@0.1.2
├── language-babel@2.7.3
├── language-docker@1.1.6
├── language-haml@0.23.14
├── language-ini@1.14.0
├── language-json-comments@0.16.3
├── language-rspec@0.3.0
├── language-systemd@0.1.0
├── linter@1.11.3
├── linter-checkstyle@1.1.2
├── linter-csslint@1.2.0
├── linter-javac@1.5.0
├── linter-jshint@1.2.2
├── linter-markdown@1.3.0
├── linter-pep8@1.2.1
├── linter-php@1.1.6
├── linter-ruby@1.2.1
├── linter-tidy@1.0.1
├── linter-xmllint@1.3.0
├── log-console@0.2.0
├── minimap@4.19.0
├── minimap-linter@1.1.1
├── mixed-indent-warning@0.3.0
├── monokai@0.18.0
├── node-debugger@1.3.2
├── open-git-modified-files@0.2.1
├── open-in-browsers@0.0.7
├── pdf-view@0.39.0
├── php-cs-fixer@2.5.2
├── pigments@0.19.6
├── preview@0.16.6
├── preview-plus@1.2.6
├── project-manager@2.7.3
├── remote-sync@3.5.0
├── save-autorun@0.3.3
├── terminal-plus@0.14.5
├── toggle-quotes@1.0.0
├── trailing-spaces@0.3.2
├── tree-view-git-status@0.2.2
├── unity-ui@2.1.3
└── w3c-validation@0.3.0
```

**Comment by mnquintana** [comment] 2016-01-18 19:30
Thanks for the report! :smile: This looks like a duplicate of https://github.com/atom/settings-view/issues/546 – feel free to subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) for a guide on where to post issues, including searching for duplicates.

**Closed by mnquintana** 2016-01-18 19:30 UTC

**Comment by g13013** [comment] 2016-01-19 08:48
@mnquintana thank you and sorry for the inconvenience, I started by searching on this repo, i have totally forgotten the the settings is a separate module 😩.
