### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by matiasgg** [atom/atom#17173] opened 2018-04-19 09:48 UTC
[Enter steps to reproduce:]

1. Open any file type from network mapped drive
2. Try to save file. But any command will produce the error.
3. Open atom in safe mode also reproduces the error.
3. Error NOT produced when saving a file to C drive.

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at onEvents.events.map.event (~/AppData/Local/atom/app-1.26.0/resources/app/src/path-watcher.js:283:46)
    at Array.map (native)
    at handler (~/AppData/Local/atom/app-1.26.0/resources/app/src/path-watcher.js:276:34)
```

### Commands

```
  9x -1:56.5.0 core:move-right (input.hidden-input)
     -1:55 core:move-down (input.hidden-input)
  2x -1:54.5.0 core:move-left (input.hidden-input)
     -1:53.1.0 core:move-down (input.hidden-input)
     -1:50.1.0 core:move-up (input.hidden-input)
     -1:49.6.0 core:move-right (input.hidden-input)
  4x -1:43.3.0 core:backspace (input.hidden-input)
  3x -1:13.8.0 core:move-right (input.hidden-input)
     -1:12.5.0 core:backspace (input.hidden-input)
     -1:08.1.0 core:save (input.hidden-input)
     -1:06.3.0 latex:build (input.hidden-input)
     -0:30.7.0 core:save (input.hidden-input)
     -0:26.5.0 core:move-left (input.hidden-input)
     -0:26 core:backspace (input.hidden-input)
     -0:24.2.0 core:save (input.hidden-input)
     -0:19.3.0 latex:build (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
language-latex 1.1.1 
language-vhdl 0.7.2 
latex 0.50.0 
pdf-view 0.69.0 
typewriter 0.7.1 
```

**Comment by rsese** [comment] 2018-04-19 17:47
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14227 so you can subscribe there if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-19 17:47 UTC

**Comment by matiasgg** [comment] 2018-04-20 11:31
Hey, I don't think this is a duplicate of #14227, since it is reproducible in safe mode and the problem seems to be with my files being stored in a Network Drive.  I can't find any solution for that at #14227.

Best regards.

**Comment by rsese** [comment] 2018-04-20 19:15
Hmmm sorry about that, maybe I was thinking of a different issue - I did see this one though that sounds similar:

https://github.com/atom/atom/issues/17046

If you try the suggestion mentioned in https://github.com/atom/atom/issues/17046#issuecomment-377015435 does that help?

**Comment by matiasgg** [comment] 2018-04-23 07:30
Hey, thanks a lot, #17046 (comment) did it. Looked all day for this but couldn't find anything. Now Atom works smoothly.
Good riddance!
