### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Ruby on rails Full stack Developer/js...

### ISSUE THREAD

**Issue by hasandeveloper** [atom/atom#16850] opened 2018-02-27 20:21 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 16.04.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/hasan/Ruby on rails Full stack Developer/js//ajaxify'

```
At fs.js:902

Error: ENOENT: no such file or directory, lstat '/home/hasan/Ruby on rails Full stack Developer/js//ajaxify'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1542:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at atom.project.getPaths.map (/usr/share/atom/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:73)
    at Array.map (native)
    at Object.startTask (/usr/share/atom/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:56)
    at Object.startLoadPathsTask (/usr/share/atom/resources/app/node_modules/fuzzy-finder/lib/main.js:109:43)
    at get_process.nextTick (/usr/share/atom/resources/app/node_modules/fuzzy-finder/lib/main.js:25:45)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by hasandeveloper** [comment] 2018-02-27 20:22
Please Help me to come out of the error

**Comment by rsese** [comment] 2018-02-28 05:34
Thanks for the report - we'll go ahead and close this as a duplicate of https://github.com/atom/fuzzy-finder/issues/255 and you can subscribe there for updates if you'd like.

Are you seeing this error every time you start Atom?  And did you happen to delete the file mentioned in the error or was the project deleted?

**Closed by rsese** 2018-02-28 05:34 UTC

**Comment by mkemkevlla13** [comment] 2018-02-28 07:08
Hello sir my phone has been hacked into and I  am barley seeing this response now because all of my notifications were disabled,, my name is name is Michael Villa and I'll will be taking legal action,, any info or help you can provide me is much appreciated

Sent from my HTC

----- Reply message -----
