### ISSUE TITLE
Links within Package/Theme Notes do nothing

### ISSUE THREAD

**Issue by JasonTheAdams** [atom/atom#8044] opened 2015-07-23 14:18 UTC
First, Atom is awesome. Plain and simple. Just awesome.

I'm on Ubuntu 14.04 running Atom 1.0.2

The only issue I have, and it's small, is that when I click on links on the theme/package detail pages, nothing happens. While looking at a package, for example, if I click 'View on Atom.io', nothing happens; if I click the github url above, nothing happens; if I see a link within the description and click that, nothing happens; etc.. Basically, anytime a link should open up in Chrome, it doesn't.

**Comment by mnquintana** [comment] 2015-07-23 14:19
I think this is a duplicate of https://github.com/atom/atom/issues/6335 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-23 14:19 UTC
