### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by sozkaynak** [atom/atom#16909] opened 2018-03-08 22:47 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At C:\Users\Win\AppData\Local\atom\app-1.24.1\resources\app\src\pane.js:1001

Error: Pane has been destroyed
    at Pane.activate (~/AppData/Local/atom/app-1.24.1/resources/app/src/pane.js:1001:41)
    at NotificationElement.module.exports.NotificationElement.removeNotificationAfterTimeout (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/notifications/lib/notification-element.js:308:46)
    at NotificationElement.module.exports.NotificationElement.removeNotification (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/notifications/lib/notification-element.js:264:27)
    at NotificationElement.module.exports.NotificationElement.handleRemoveNotificationClick (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/notifications/lib/notification-element.js:269:18)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/notifications/lib/notification-element.js:148:30)
```

### Commands

```
  2x -6:19.3.0 core:backspace (input.hidden-input)
     -6:17.6.0 editor:newline (input.hidden-input)
     -6:07.3.0 autocomplete-plus:confirm (input.hidden-input)
     -0:29.6.0 tabs:split-down (div.title)
     -0:21.8.0 pane:close (div.item-views)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-eclipse-syntax 0.0.5 
atom-python-run 0.9.6 
atom-python-test 0.9.0 
autocomplete-python 1.10.5 
awesome-python-snippets 0.2.2 
docblock-python 0.3.0 
hey-pane 1.1.0 
Hydrogen 2.3.0 
ide-python 0.8.1 
linter 2.2.0 
linter-python 3.1.2 
python-debugger 0.2.0 
python-docstring 0.0.3 
python-indent 1.1.4 
python-isort 0.0.7 
python-line-profiler 0.3.2 
python-mrigor 2.1.3 
python-run-terminalnx 1.1.7 
python-runner 1.1.0 
python-suite 0.3.2 
python-tools 0.6.9 
python-yapf 0.14.0 
scroll-through-time 0.3.0 
teletype 0.9.0 
```

**Comment by rsese** [comment] 2018-03-09 07:16
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/notifications/issues/174 so you can subscribe there for updates if you'd like.  If you have any details about what you were doing at the time of the error, feel free to let us know in https://github.com/atom/notifications/issues/174.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-09 07:16 UTC
