### ISSUE TITLE
Atom "Save with encoding" feature

### ISSUE THREAD

**Issue by ol3gart** [atom/atom#12088] opened 2016-07-03 06:00 UTC
Greetings!

I have a file in Wondows-1251. I open it with Atom, and now i want convert & save it with UTF-8.

In Sublime Text i can do this with File -> Save with Encoding.

Can i do this with Atom?

**Comment by Ben3eeE** [comment] 2016-07-06 07:15
https://github.com/atom/encoding-selector/issues/7?

**Comment by lee-dohm** [comment] 2016-07-06 22:29
This is a duplicate of the Issue that @Ben3eeE mentioned. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-06 22:29 UTC
