### ISSUE TITLE
Atom crashes when duplicating a file

### ISSUE THREAD

**Issue by Vadlusk** [atom/atom#20301] opened 2020-01-07 16:10 UTC
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When duplicating a file by right clicking on the file in the file tree, atom crashes.
Similar behavior witnessed when trying to copy project path from same right click menu. 
Same issue as #4920

### Steps to Reproduce

1. Open file tree
2. Right click on any file
3. Click Duplicate (or copy project path)
4. Watch the program crash.

**Expected behavior:**

No crashing

**Actual behavior:**

Crashing

**Reproduces how often:**

about 50% of the time.

### Versions
Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.42.0
python 2.7.16
git 2.21.0
Mac OS Catalina: 10.15.2 (19C57)

**Comment by darangi** [comment] 2020-01-10 17:27
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20034. You may want to subscribe there for updates.

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by darangi** 2020-01-10 17:27 UTC
