### ISSUE TITLE
Editor stops respond when open a file with very long lines

### ISSUE THREAD

**Issue by xpol** [atom/atom#13793] opened 2017-02-11 10:43 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Editor stops respond when open a file with very long lines.

### Steps to Reproduce

1. `curl -O https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js`
2. `atom --safe bootstrap.min.js`
3. atom opens

**Expected behavior:** 

* Atom show all contents of bootstrap.min.js
* Atom response user input like mouse and keyboards.

**Actual behavior:** 

* Atom show partial contents of bootstrap.min.js
* Atom does not response any user input and show the follow dialog:

![screen shot 2017-02-11 at 6 36 58 pm](https://cloud.githubusercontent.com/assets/20248/22853166/e20a96b0-f089-11e6-9b63-976ac7354fa7.png)

**Reproduces how often:** 100% with or without Soft Wrap turns on.

### Versions

Atom    : 1.14.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.10.1

**Comment by Zireael07** [comment] 2017-02-11 11:02
Duplicate of #979

**Comment by xpol** [comment] 2017-02-12 13:25
#979 is locked.

RubyMine will force soft wrap when the lines are too long.

**Comment by 50Wliu** [comment] 2017-02-13 18:37
> #979 is locked.

This does not mean anything, this issue is still a duplicate of it.
Soft wrapping will not do anything in this case because it's still a single line on the disk.

**Closed by 50Wliu** 2017-02-13 18:37 UTC
