### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/usr/share/atom-beta/resources/app/usr/s...

### ISSUE THREAD

**Issue by thadjbullet** [atom/atom#14512] opened 2017-05-19 16:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-beta0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/usr/share/atom-beta/resources/app/usr/share/atom-beta/resources/app/usr/share/atom-beta/resources/app/usr/share/atom-beta/resources/app/usr/share/atom-beta/resources/app/node_modules/tree-view/styles/tree-view.less'

```
At /usr/share/atom-beta/resources/app/src/theme-manager.js:323

Error: ENOENT: no such file or directory, open '/usr/share/atom-beta/resources/app/usr/share/atom-beta/resources/app/usr/share/atom-beta/resources/app/usr/share/atom-beta/resources/app/usr/share/atom-beta/resources/app/node_modules/tree-view/styles/tree-view.less'
  at Error (native)
  at Object.fs.openSync (fs.js:640:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
  at Proxy.fs.readFileSync (fs.js:508:33)
  at Proxy.fs.readFileSync (ELECTRON_ASAR.js:501:29)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (<embedded>:20992:56)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (<embedded>:20964:27)
  at <embedded>:69243:60
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (<embedded>:69241:65)
  at <embedded>:68835:23
  at Package.module.exports.Package.measure (<embedded>:68797:21)
  at Package.module.exports.Package.finishLoading (<embedded>:68831:25)
  at PackageManager.module.exports.PackageManager.loadAvailablePackage (<embedded>:20349:38)
  at PackageManager.module.exports.PackageManager.loadPackage (<embedded>:20323:27)
  at PackageManager.module.exports.PackageManager.enablePackage (<embedded>:20014:25)
  at HTMLButtonElement.enablementButtonClickHandler (<embedded>:183197:31)

```

### Commands

```
  2x -8:07.9.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -0:17.6.0 nuclide-navigation-stack:navigate-backwards (div.tool-panel.tree-view)
```

### Non-Core Packages

```
arc-ui 0.1.7 
atom-beautify 0.29.24 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.3 
atom-typescript 11.0.3 
busy-signal 1.4.1 
dash 1.7.1 
emmet 2.4.3 
file-icons 2.1.6 
gulp-control 0.5.0 
intentions 1.1.2 
language-babel 2.61.0 
language-gitignore 0.3.0 
language-postcss 1.3.1 
language-pug 0.0.21 
linter 2.1.4 
linter-eslint 8.1.7 
linter-pug-lint 0.2.0 
linter-stylelint 3.10.0 
linter-stylint 2.2.7 
linter-tslint 1.4.0 
linter-ui-default 1.5.4 
nuclide 0.228.0 
platformio-ide-terminal 2.5.0 
prettier-atom 0.31.1 
react-snippets 0.7.2 
sync-settings 0.8.1 
```

**Comment by rsese** [comment] 2017-05-22 19:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14500. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-22 19:54 UTC
