### ISSUE TITLE
Atom crashes with unsaved file under MacOS

### ISSUE THREAD

**Issue by ospaarmann** [atom/atom#18558] opened 2018-12-07 15:37 UTC
### Description

Atom recently starts to crash randomly when working on unsaved files. This way I often loose work.

### Steps to Reproduce

1. Open a new file 
2. Take some notes or write a snipped that you don't want to save
3. See Atom crash and loose part of your work

**Expected behavior:** [What you expect to happen]

It should not crash.

**Actual behavior:** [What actually happens]

It crashes.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Recently almost every time when working on an unsaved file. 80%+

### Versions

Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.15
git 2.17.2

macOS Mojave 10.14.1

<img width="526" alt="screenshot 2018-12-07 at 16 33 02" src="https://user-images.githubusercontent.com/308086/49656750-62f5ea80-fa3e-11e8-99c8-cfe7f452fc30.png">

**Comment by lee-dohm** [comment] 2018-12-07 17:09
Have you reproduced this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? I notice you chopped off the part of the template that relates to that. I use unsaved files all the time on macOS 10.14.1 and do not experience this problem, so it could be a package that you're running that is causing the problem.

Additionally, if you are able to reproduce this in Safe Mode, please follow the instructions for [collecting crash logs](https://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs) and either attach them here or, if you'd prefer to share them privately, email them to atom@github.com.

**Comment by sidhyatikku** [comment] 2018-12-07 17:20
@lee-dohm I'm getting this issue. The app freezes and I'm not able to create an issue as well.
<img width="861" alt="screen shot 2018-12-07 at 10 48 37 pm" src="https://user-images.githubusercontent.com/33092447/49662610-555a5800-fa72-11e8-885f-876cff8897e9.png">

**Comment by lee-dohm** [comment] 2018-12-07 17:49
@sidhyatikku Please open a new issue and completely fill out the issue template so we can be sure that we have all the information we need.

**Comment by sidhyatikku** [comment] 2018-12-07 18:19
@lee-dohm The app is frozen and I’m not able to send an issue. I’m just a novice coder and I’ll not be able to provide detailed inputs.

**Comment by lee-dohm** [comment] 2018-12-07 18:34
@sidhyatikku You can click the "New Issue" button in the upper right of this web page though 😀

**Comment by lee-dohm** [comment] 2018-12-07 18:36
If you need help writing a bug report (something that anyone can do, no coding experience required), you can follow [this guide that I wrote to help](https://www.lee-dohm.com/2015/01/04/writing-good-bug-reports/).

**Comment by ospaarmann** [comment] 2018-12-18 11:13
@lee-dohm Yes, the editor also just crashed in safe mode.

This is the crash log when in safe mode: https://gist.github.com/ospaarmann/1bc96c38dbbfac1075ed0a1f04bf1c2a#file-crash_log_in_safe_mode-log

This is the crash log when not in safe mode: https://gist.github.com/ospaarmann/1bc96c38dbbfac1075ed0a1f04bf1c2a#file-crash_log_not_in_safe_mode-log

If you need any more information please let me know.

**Comment by rsese** [comment] 2018-12-18 20:58
Thanks @ospaarmann - do you happen to have multiple locales set in the spell-check packages settings?

**Comment by ospaarmann** [comment] 2018-12-18 21:31
Hey @rsese - yes. I have set the locales to `en-US, de-DE`.

**Comment by rsese** [comment] 2018-12-18 21:50
Ahh ok, thanks for confirming - since you're using multiple locales and since your crash log looks similar, we'll close this as a duplicate of https://github.com/atom/atom/issues/15912 and you can subscribe there for updates if you'd like.

**Closed by rsese** 2018-12-18 21:50 UTC
Labels: crash
