### ISSUE TITLE
Finder slow to show results

### ISSUE THREAD

**Issue by scottbarrow** [atom/atom#11518] opened 2016-04-18 21:52 UTC
### Description
* Typing `cmd+k`  produces the finder window
* Since the 1.7.1 update the results window has a slight delay in displaying the results

[Description of the bug or feature]

### Steps to Reproduce

1. Type `CMD+K`
2. wait

**Expected behavior:** [What you expected to happen]
* should display results instantaneously 

**Actual behavior:** [What actually happened]
* results show after around .5 delay

### Versions

1.7.1
![finder](https://cloud.githubusercontent.com/assets/5571736/14621057/16a2f184-0575-11e6-8eaa-7241985f5ddf.gif)

**Comment by 50Wliu** [comment] 2016-04-18 22:01
This is a duplicate of atom/fuzzy-finder#188 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-18 22:01 UTC
