### ISSUE TITLE
.gitignore file not adjusting the visual aid off the Tree View

### ISSUE THREAD

**Issue by viion** [atom/atom#14006] opened 2017-03-14 23:59 UTC
Similar to https://github.com/atom/atom/issues/3429#issuecomment-286594653

### Description

I have downloaded atom. Installed it. Opened up a project and the `.gitignore` is not being detected and the Tree View is not changing (reducing the opacity of the folder).

It used to do this in the past. I have tried several projects and all do not work. These projects all work in other applications/IDE so I do not believe it's a project issue. I feel like I'm doing something really silly..

### Steps to Reproduce

1. Have a fresh install of Atom with no setting changes
2. Set `tree-view.hideVcsIgnoredFiles` to `true`
3. Create a new directory `~/test`
3. Change to the `~/test` directory
3. Execute `git init` within `~/test`
3. Open Atom with the command `atom ~/test`
3. Create a folder named `should-be-ignored`
4. Create a `.gitignore` file
4. Add a line containing `should-be-ignored` to the `.gitignore` file

**Expected:** Folder named `should-be-ignored` to disappear

**Actual:** Folder named `should-be-ignored` remains and does not change color

### Original Repro Steps

1. Have a fresh install of Atom with no setting changes
2. Enable the VCS settings
3. Create a folder, name it eg: `should-be-ignored`
4. Create a .gitignore, add that folder to it
5. Nothing changes

**Expected behavior:** I expect it to tint/opacity change the folder in the Tree view so it's visibly different.

**Actual behavior:** Nothing happens, no visual que.

### Versions

- Windows 10, 64bit
- Downloaded Latest atom from https://atom.io/
    - Atom 1.15.0
    - Atom Beta 1.16.0 also doesn't work

No plugins.

### Additional Information

Screenshots

![](http://i.imgur.com/sFu4nhx.png)
![](http://i.imgur.com/vvOg6jH.png)

**Comment by 50Wliu** [comment] 2017-03-15 01:13
Just to be sure: both those folders are Git repositories, in the sense that they have a valid `.git` folder, correct?  In addition, does focusing the Tree View and pressing <kbd>i</kbd> twice do anything?  That should force a recomputation of the ignored files status.

**Comment by lee-dohm** [comment] 2017-03-15 01:28
I was able to reproduce this using Atom v1.15.0 on Mac OS X 10.12.3 using the following repro steps:

1. Have a fresh install of Atom with no setting changes
2. Set `tree-view.hideVcsIgnoredFiles` to `true`
3. Create a new directory `~/test`
3. Change to the `~/test` directory
3. Execute `git init` within `~/test`
3. Open Atom with the command `atom ~/test`
3. Create a folder named `should-be-ignored`
4. Create a `.gitignore` file
4. Add a line containing `should-be-ignored` to the `.gitignore` file

**Expected:** Folder named `should-be-ignored` to disappear

**Actual:** Folder named `should-be-ignored` remains and does not change color

Interestingly, if `should-be-ignored` is a file instead of a folder, it changes to the ignored style but does not disappear as expected.

**Comment by lee-dohm** [comment] 2017-03-15 01:30
A workaround for now is as @50Wliu mentions, that any action that forces a redraw of the affected items (such as toggling the VCS ignored setting or collapsing and expanding the parent folder) will make them update to the appropriate style.

**Comment by viion** [comment] 2017-03-15 01:33
Hi

I think what @50Wliu said with pressing `i` worked, I loaded a project with a valid `.git` directory. Re-opening Atom made the directories disappear and tint. **Adding new entries to `.gitignore` did nothing until toggled the option again to make it redraw.**

So I think that is the key issue I'm seeing.

**Comment by 50Wliu** [comment] 2017-03-15 01:40
> Interestingly, if should-be-ignored is a file instead of a folder, it changes to the ignored style but does not disappear as expected.

Yep I've noticed this quite a few times when switching branches with very different .gitignores, never got around to filing an issue for it though 😞.

**Comment by lee-dohm** [comment] 2017-03-15 01:43
Since we're all in agreement, I updated the repro steps in the original post.

**Comment by lee-dohm** [comment] 2018-05-29 21:41
If you can't reproduce the issue anymore with the given reproduction steps, I'm good with closing this. Thanks for the follow up!

**Closed by lee-dohm** 2018-05-29 21:41 UTC
Labels: bug, git, regression, triaged

**Comment by daviwil** [comment] 2018-05-29 21:42
I believe this may have been a side effect of an update we did in the git-utils package, taking a new version of libgit2.  Glad to hear it's been resolved!
