### ISSUE TITLE
Open dialog box does not dismiss or open selected item

### ISSUE THREAD

**Issue by feifanzhou** [atom/atom#8028] opened 2015-07-22 16:01 UTC
The Open file/folder dialog box allows me to navigate to a file or folder, but both the Open and Cancel buttons don't do anything. The dialog remains on screen. I can click through to the editor window, but the dialog does not disappear. The only way to get the dialog to disappear is by force-quitting Atom. 

https://www.dropbox.com/s/rbpigysa2h5k6b1/2015-07-22%2011.53.04.mov?dl=0

I am able to open files and folders by dragging them to the Dock icon. 

<img width="263" alt="screen shot 2015-07-22 at 12 00 45" src="https://cloud.githubusercontent.com/assets/3407996/8830271/584b2ac0-3069-11e5-99e2-65f225392393.png">

**Comment by mnquintana** [comment] 2015-07-22 16:08
This is a duplicate of https://github.com/atom/atom/issues/7811 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-22 16:08 UTC
