### ISSUE TITLE
atom CLI now opens empty atom window

### ISSUE THREAD

**Issue by jnunemaker** [atom/atom#6989] opened 2015-05-28 13:49 UTC
Previously if you were at the terminal and typed "atom" it opened the current directory in atom. As of a recent release, it now opens an empty window. To achieve the same result as before one must now type "atom .". I understand making changes and that relearning will be required, but it does seem like consistency across github CLI's should be important. GitHub for Mac opens the current directory if you simply type "github". This means one github product requires "." for the current directory and another does not. Now I'm left in a state of never getting it right for either of them. :)

**Comment by lee-dohm** [comment] 2015-05-28 14:17
This is a duplicate of #6873 among others. This was a conscious decision to enable restoring a previous session from the command line. There are a couple proposed workarounds to make it behave in the old way on the above linked Issue. Please continue the conversation there.

Thanks for reporting!

**Closed by lee-dohm** 2015-05-28 14:17 UTC
