### ISSUE TITLE
There is obvious delay of response when move focus back to Atom on Windows platform

### ISSUE THREAD

**Issue by wlmzfx** [atom/atom#10494] opened 2016-01-19 09:45 UTC
I have tried Atom1.2.4 and 1.4.0, both have this isssue.

I lunched Atom, open a project, open a file or not, then click on any free space of the desktop to make Atom lose the focus, then back to Atom with a click to any part of Atom, the Atom editor cannot response to my mouse click (or keyboard hit) immediately, there is about 3-5 seconds delay. (The Atom window does not freeze, but it just cannot allow me to edit open file immediately)

I am using Windows7 with i5 + 4GB Memory.

**Comment by mnquintana** [comment] 2016-01-19 13:13
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/9544 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-19 13:13 UTC
