### ISSUE TITLE
Orphan processes

### ISSUE THREAD

**Issue by alekmych** [atom/atom#10914] opened 2016-02-20 16:33 UTC
### Description

Atom leaves orphan `conhost` and `node` processes under Windows 10 Pro
### Steps to Reproduce
1. Launch Atom
2. Exit Atom

**Expected behavior:** Atom clean up correctly without leaving any process

**Actual behavior:** Atom leaves `conhost` and `node` processes
### Step 1

![step_1](http://i.imgur.com/ygT8Pz7.png)
### Step 2

![step_2](http://i.imgur.com/2FUEnYO.png)
### Versions

1.5.3

**Comment by dipyalov** [comment] 2016-02-20 23:13
I'm experiencing the same under Windows 8.1

Atom: 1.5.3
OS: Windows 8.1 Pro 64-bit

**Comment by lee-dohm** [comment] 2016-02-21 20:44
Can you reproduce the issue when running Atom in Safe Mode?

To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by alekmych** [comment] 2016-02-24 02:33
@lee-dohm already.  Results from safe mode.

**Comment by lee-dohm** [comment] 2016-02-24 02:36
How long from when you start Atom to when you exit Atom?

**Comment by alekmych** [comment] 2016-02-24 14:12
2 cases:

1. Opened file, edited it and closed **~20sec**
2. Opened large C++ project for review, closed it **~15min**

Hope it helps. Currently I'm using Atom as quick editor/review tool.

**Comment by albertosantini** [comment] 2016-02-25 08:28
I noticed that on Windows 10 64bit (with atom safe).

It seems it happens during the packages update process, started when Atom is launched.

I cannot reproduce it steadily: open the `Settings` tab and go to `Updates`.
However I noticed that, if there is some error (installation, network, etc.), sometimes there are node orphan processes.

(I don't know if it is related to this issue: when I switch from an app to Atom, I see in the task manager a spike of atom processes, about twenty; then the processes die until the usual four or five running. I don't see the same behaviour on Windows 8.1 64bit.)

**Comment by albertosantini** [comment] 2016-02-26 19:49
Using ProcMon [1] I worked out the command line of the orphan process:

```
C:\Users\icebox\AppData\Local\atom\app-1.5.3\resources\app\apm\bin\\node.exe"  --harmony_collections "C:\Users\icebox\AppData\Local\atom\app-1.5.3\resources\app\apm\bin\/../lib/cli.js" "outdated" "--json" "--compatible" "1.5.3" "--no-color"
```

The process is not terminated after a few minutes Atom is running (see my previous post to reproduce it, `Settings / Updates`) and it is not killed when Atom quits.

[1] https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx

**Comment by xitkov** [comment] 2016-09-08 20:56
I am on mac 10.10.5 and facing a similar issue.
I am seeing orphaned apm processes.

Steps:

1. Run atom `$ atom --safe`.
<img width="1438" alt="screen shot 2016-09-09 at 2 17 22 am" src="https://cloud.githubusercontent.com/assets/5154582/18366472/6c3071a0-7634-11e6-9d39-8adc150e2d69.png">

2. Close it
<img width="1440" alt="screen shot 2016-09-09 at 2 18 12 am" src="https://cloud.githubusercontent.com/assets/5154582/18366487/7c22a038-7634-11e6-865c-8f768bd95915.png">

Expected:
Clean exit.

Result:
I have got 3 orphaned apm processes, I guess this number matches the number of windows that atom opens, in my case it's 3 windows.

**Comment by laterz** [comment] 2017-02-08 08:03
I'm experiencing the same under Windows 7-64bit

Atom: 1.13.0 ia32

and i find that  : 
when click Settings->Updates OR search in the Install ,Atom will create one more orphan (conhost and node processes)

perhaps it has more way to create orphan,please fix it.love atom!

**Comment by damieng** [comment] 2017-05-05 22:08
Not able to reproduce this on latest Atom on Windows.  Apm process always cleanly shutdown according to process explorer even if I quit while it is searching.

**Comment by damieng** [comment] 2017-05-17 17:53
No longer actively tracking this issue given the inability to get a repro.  If you experience this problem feel free to comment on this issue and we can re-open as necessary.

**Closed by damieng** 2017-05-17 17:53 UTC
Labels: more-information-needed, needs-reproduction, windows
