### ISSUE TITLE
Not possible to write ">" using "Alt-Gr" + "."

### ISSUE THREAD

**Issue by pssgcsim** [atom/atom#7468] opened 2015-06-26 19:44 UTC
Hi,
I'm having trouble to write character ">" using keys "Alt-Gr" + ".". I think it might be a bug.
(Using Czech keyboard if it has any affect on this)

**Comment by mnquintana** [comment] 2015-06-26 19:45
Thanks for the report! This is a duplicate of https://github.com/atom/atom-keymap/issues/35 and/or https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-26 19:45 UTC
