### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by TakayukiOhgami** [atom/atom#19667] opened 2019-07-12 01:29 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1190071)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1185777)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:89970)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:79712)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:70365)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:92801)
```

### Commands

```
 12x -2:43.7.0 core:move-up (input.hidden-input)
 10x -2:40.2.0 core:move-left (input.hidden-input)
  2x -2:38.4.0 core:backspace (input.hidden-input)
  4x -2:36.8.0 core:move-right (input.hidden-input)
     -2:35.6.0 core:backspace (input.hidden-input)
  4x -2:35.2.0 core:move-right (input.hidden-input)
 18x -2:34.4.0 core:select-right (input.hidden-input)
  3x -2:31.7.0 core:backspace (input.hidden-input)
     -2:16.1.0 core:move-right (input.hidden-input)
     -2:15.2.0 core:move-left (input.hidden-input)
     -2:07.7.0 core:backspace (input.hidden-input)
 10x -2:06.7.0 core:move-left (input.hidden-input)
 10x -2:02.9.0 core:move-right (input.hidden-input)
     -2:00.2.0 core:move-left (input.hidden-input)
  3x -1:58.4.0 core:save (input.hidden-input)
     -1:07.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-file-icons 0.6.0 
atom-html-preview 0.2.6 
autocomplete 0.47.0 
export-html 3.1.0 
japanese-menu 1.14.0 
language-fortran 2.1.7 
minimap 4.29.9 
platformio-ide-terminal 2.9.1 
project-manager 3.3.7 
sync-settings 0.8.6 
```

**Comment by rsese** [comment] 2019-07-15 21:06
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/19108 so you can subscribe there for updates if you'd like.

Based on previous reports, it seems like the error isn't reproducible if you close and reopen the file or project that's giving you trouble.  But if you have specific repro steps with a minimal example or any additional details, please let us know in https://github.com/atom/atom/issues/19108.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-07-15 21:06 UTC
