### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 232Error: Cannot cal...

### ISSUE THREAD

**Issue by Scripts4BridgeIC** [atom/atom#16460] opened 2017-12-28 20:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 232
Error: Cannot call function 'getPosition' on missing remote object 232
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 232
Error: Cannot call function 'getPosition' on missing remote object 232
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:691:34)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:725:42)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:189:32)
```

### Commands

```
     -5:13.3.0 core:paste (input.hidden-input)
  2x -5:03.4.0 core:select-right (input.hidden-input)
     -5:02.5.0 core:paste (input.hidden-input)
     -5:00.9.0 core:save (input.hidden-input)
     -4:53.1.0 core:backspace (input.hidden-input)
  4x -4:52.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
color-picker 2.2.5 
compare-files 0.8.1 
editorconfig 2.2.2 
file-icons 2.1.15 
git-clone 0.2.0 
import 1.7.0 
remove-whitespace 0.2.1 
split-diff 1.5.1 
```

**Comment by rsese** [comment] 2017-12-29 05:34
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment] 2018-03-16 23:13
Thanks again for reporting this, I'm going to go ahead and close as a duplicate of https://github.com/atom/atom/issues/16630.  If you remember what you were doing at the time of the error or if you have steps to reproduce, feel free to let us know in #16630.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-16 23:13 UTC
Labels: more-information-needed, uncaught-exception
