### ISSUE TITLE
cpu usage kept high

### ISSUE THREAD

**Issue by qiluo** [atom/atom#5096] opened 2015-01-16 03:47 UTC
I'm on 0.174.0, Windows 7

I installed some 3rd party plugins, but disabled all of them

I'm behind of company firewall, so I set up proxy in .apmrc

However, cpu usage always kept high since 0.166.0, I've no idea what happened

**Comment by maxbrunsfeld** [comment] 2015-01-16 18:39
Can you post your list of installed plugins (`apm list`)? Also, could you open the developer tools and run `Collect JavaScript CPU Profile` under `Profiles`? You might be able to tell what code is using so much CPU time.

**Comment by kevinsawicki** [comment] 2015-01-16 18:40
> However, cpu usage always kept high since 0.166.0, I've no idea what happened

0.167 was when chrome 39 shipped, wonder if that could be related

**Comment by qiluo** [comment] 2015-01-19 03:53
Except for built-in plugins, I installed other 6

```
C:\Users\xxx\.atom\packages (6)
├── atom-beautifier@0.5.0
├── autocomplete-plus@1.1.0
├── line-ending-converter@0.4.0
├── markdown-pdf@1.2.11
├── minimap@3.5.5
└── monokai@0.9.0
```

From the profiling, looked like ThemeManager took much CPU time.
![atomcpuprofiling](https://cloud.githubusercontent.com/assets/1715517/5795733/bbed5f90-9fd1-11e4-87d1-d3e33893b93d.png)

Another found, every time I tried to save profiling file, it crashed...

**Comment by hindsholm** [comment] 2015-08-18 09:50
I have the same problem.
I am on a Windows 7 machine on a corporate network behind a firewall and with pretty agressive anti-virus running.
When **idle** and in safe mode, Atom is using 30% of my 4 cores.
I did a profile which shows that Atom is busy, constantly calling ThemeManager.loadUserStylesheet:
![profile](https://cloud.githubusercontent.com/assets/1001136/9327109/c65af92e-459e-11e5-8131-ebbec8ad9631.png)

Windows Process Explorer shows that styles.less is accessed heavily:
![processexplorer](https://cloud.githubusercontent.com/assets/1001136/9327137/f307be80-459e-11e5-9b13-2fc241df2115.png)

I definitely think this is Windows-specific since I haven't heard about the problem on other platforms and I also run Atom on Linux without any problems.

I would be more than happy to help fixing this bug. Is it perhaps possible to disable the user stylesheet feature?

**Comment by maxbrunsfeld** [comment] 2015-08-18 16:44
@hindsholm Thanks for the info; that's really useful. What version of Atom are you using?

**Comment by hindsholm** [comment] 2015-08-19 09:29
@maxbrunsfeld This is on version 1.0.7.

**Comment by hindsholm** [comment] 2015-08-28 11:28
Just upgraded to 1.0.8 - no change.
I then deleted `C:\Users\xxx\.atom\styles.less` and restarted Atom.
CPU usage was still high, but now because `C:\Users\xxx\.atom\snippets.cson` was accessed constantly.
After deleting `C:\Users\xxx\.atom\snippets.cson` and restarting Atom, CPU usage was finally at a very low level. :)
**However**: as soon as I open certain files, CPU usage again rises and stays high. This happens if I open e.g. .gitignore or any SCSSfile, but not when I open JS or HTML files. What happens is that Atom will constantly access the open file like if it was changing all the time:
![profile2](https://cloud.githubusercontent.com/assets/1001136/9545295/6910741e-4d88-11e5-9e47-3f923ee20450.png)
I am wondering if this could somehow be related to the corporate anti-virus (which I am not able to turn off, so I cannot verify)?

**Comment by hindsholm** [comment] 2015-08-28 11:34
I just debugged the issue, and indeed, the `handleNativeChangeEvent` function that I highlighted above is constantly receiving 'change' events even though the file (in this case .gitignore) does not change at all.

**Comment by hindsholm** [comment] 2015-08-28 14:44
I think I have found the cause of this problem. The bad guy is *McAfee VirusScan Enterprise*. According to [this knowledgebase post|https://kc.mcafee.com/corporate/index?page=content&id=KB65944&pmv=print] "Scanned files have their LastAccessDate changed, which can cause third party apps to think they were modified".
So whenever Atom gets a file changed event, it reloads the file, and that triggers VSE to scan the file, causing a new file changed event, etc etc.
The bad behavior by McAfee is fixed in patch 5, but we are running patch 4...

**Comment by qiluo** [comment] 2015-08-31 01:06
@hindsholm I'm running McAfee 8.8 patch 5, the issue gone somehow someday, no idea what's happened. Maybe you are correct

**Comment by izuzak** [comment] 2015-09-09 16:09
Closing this since @hindsholm and @qiluo can no longer reproduce this and there were no other reports. Sounds like McAfee was the problem here. Let us know if you notice this happening again. :v:

**Closed by izuzak** 2015-09-09 16:09 UTC
Labels: more-information-needed, performance
