### ISSUE TITLE
mysterious 'not responding' error

### ISSUE THREAD

**Issue by lewislepton** [atom/atom#8005] opened 2015-07-21 15:37 UTC
ive come across this several times now.
but when checking to see if something is be used in activity monitor, such as haxe or similar. i have spotted this error. screenshot is given.

now, i am not doing anything strange in particular. im working with the haxe packages, plus some others. also my own theme. im running/building the application from within atom itself, but can tfind what is causing this. just that i end up seeing mountains of memory being used with this error

<img width="301" alt="screen shot 2015-07-21 at 16 33 07" src="https://cloud.githubusercontent.com/assets/11299322/8804990/b6dd0ce6-2fc6-11e5-83d6-8d239b4ab194.png">

**Comment by lewislepton** [comment] 2015-07-21 16:01
also to add. there seems to be 2 atom helpers running, taking up memory. plus you already have the application itself as well.
seems like a lot being used up. though it is still quick, just more concerning

<img width="602" alt="screen shot 2015-07-21 at 16 59 56" src="https://cloud.githubusercontent.com/assets/11299322/8805621/232791c0-2fca-11e5-8085-85a4f1bd6d83.png">

**Comment by 50Wliu** [comment] 2015-07-22 01:15
Duplicate of #3928, please subscribe there for updates.

**Closed by 50Wliu** 2015-07-22 01:15 UTC
