### ISSUE TITLE
Uncaught TypeError: decorationIterator.getCloseScopeIds is not a function

### ISSUE THREAD

**Issue by tyrollins** [atom/atom#14383] opened 2017-05-09 23:23 UTC
Newly built Atom-Dev, upon first load I received `Uncaught TypeError: decorationIterator.getCloseScopeIds is not a function` for Autocomplete-plus, then notifications, then settings-view package, etc... 

**Steps**: 
1. clone repo [eea036750]
2. script/build --code-sign --install (node 6.10.2, npm 3.10.10)
3. open Atom

**Atom**: 1.18.0-dev-eea036750 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: decorationIterator.getCloseScopeIds is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:213

TypeError: decorationIterator.getCloseScopeIds is not a function
    at ScreenLineBuilder.emitDecorationBoundaries (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:213:1)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:121:1)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:630:1)
    at TextEditorPresenter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1371:1)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1378:1)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:123:1)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:266:1)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:198:1)
    at new TextEditorComponent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:172:1)
    at atom-text-editor.TextEditorElement.mountComponent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:203:24)
    at atom-text-editor.TextEditorElement.setModel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:147:12)
    at atom-text-editor.TextEditorElement.initialize (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:133:12)
    at TextEditor.module.exports.TextEditor.getElement (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3332:1)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:100:1)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:88:1)
    at atom-pane.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:198:25)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:53:55)
```

### Commands

```
 27x -9:49.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
N/A
```

**Comment by 50Wliu** [comment] 2017-05-10 01:00
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14381. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-05-10 01:00 UTC
