### ISSUE TITLE
Linux @ VirtualBox mouse problem

### ISSUE THREAD

**Issue by am-kantox** [atom/atom#6306] opened 2015-04-08 16:12 UTC
There is a [known issue](https://code.google.com/p/chromium/issues/detail?id=456222) with Chrome41 engine running on Linux in VirtualBox. It actually became a show-stopper for Chrome42. **TL;DR**: in VB Chrome41 engine _always_ runs in touch-screen mode, even on desktops.

Hotfix in Chrome41 is to pass `--touch-devices=123` to the chrome command line.

Is it possible to pass parameters to Atom’s command line so that chrome engine will understand them?

**Comment by hainesr** [comment] 2015-04-09 08:44
I am seeing this too. However, if I run Atom on a remote X display from my VB machine it works as usual. Given that Atom is unusably slow over an X connection, though, this isn't a good workaround!

**Comment by am-kantox** [comment] 2015-04-09 08:58
@hainesr Of course it works as usual, since chrome engine tries to figure out what screen mode to select on the target machine.

**Comment by izuzak** [comment] 2015-04-13 15:52
@am-kantox As far as I can tell, that should be possible, see https://github.com/atom/atom-shell/issues/978.

/cc @zcbenz

**Comment by am-kantox** [comment] 2015-04-13 16:52
@izuzak Unfortunately I was unable to force this option even by editing

    src/browser/atom-application.coffee:    app.commandLine.appendSwitch 'js-flags', '--harmony'

and rebuilding the app from the scratch.

**Comment by izuzak** [comment] 2015-04-13 16:59
@am-kantox You did try passing the flags when running atom, right (not editing the source)? Can you specify which Atom command you tried exactly and what you get if you try this: https://github.com/atom/atom-shell/issues/978#issuecomment-68948041? Also, you might want to continue this discussion over at atom/atom-shell#978.

**Comment by jpmn** [comment] 2015-04-16 20:27
It looks like it has been fixed in Google Chrome v42.0.2311.90. Any chance Atom will be updated soon too?

**Comment by am-kantox** [comment] 2015-04-17 07:05
@jpmn Hereby I confirm it was fixed in Chrome42. It works back like a charm since 42 version.

**Comment by izuzak** [comment] 2015-04-17 12:26
> It looks like it has been fixed in Google Chrome v42.0.2311.90. Any chance Atom will be updated soon too?

@jpmn Seem like it's going to happen soon. See https://github.com/atom/electron/issues/1424

**Comment by jpmn** [comment] 2015-05-01 17:50
The problem is still present in Chrome 42.0.2311.135 and makes both Atom and Chrome unusable (fixed with the flag --touch-devices=123).

**Comment by jpmn** [comment] 2015-05-11 20:49
I found a "pointing system" option in the VM configuration. When set to "Mouse PS/2" it started working again (Atom and Chrome).

**Comment by SlyDen** [comment] 2015-05-14 10:41
@jpmn Confirm that trick (I use __RCtrl-I__ shortcut to switch the mode) ... For now I just set --touch-devices=123 flag in Chrome's start up script and it works  ... and for Atom I'm switching mode (tried the same option in command line with no effect)

Atom: version 0.198.0
Crome: Version 42.0.2311.152 (64-bit)
VirtualBox: 4.3.26 r98.988

**Comment by rdnewman** [comment] 2015-05-21 16:12
With Chrome 43 now released with a fix for this in Chrome, this issue should no longer be tagged "blocked."

**Comment by jadbox** [comment] 2015-06-23 03:40
I'm having the same issue ><

**Comment by yuki-takei** [comment] 2015-06-23 07:25
I have compiled atom that is based on ['ks-electron-chrome-42' branch](https://github.com/atom/atom/tree/ks-electron-chrome-42) and merge master(v0.210.0).

You can download a deb package from [here](https://drive.google.com/folderview?id=0BwM_X0G2bjOjfmZRUUE3bDc2RkdFX1YwdktGcVdSU2tZdExIY0dTVUh0NXgzZ2JJTlpPVEE&usp=sharing), but it has some points to fix.
(see https://github.com/atom/atom/pull/6877)

Use it AT YOUR OWN RISK.

**Comment by heyyoyo** [comment] 2015-06-23 15:31
@yuki-takei your version fixed this problem as expected.
But some new bugs appeared as exepected too...
I hope the new version will be release soon.

**Comment by mrmanicou** [comment] 2015-06-26 16:22
This issue is a real showstopper for me. Any idea when this might be fixed?

**Comment by LeoK987** [comment] 2015-06-27 23:49
Just upgraded to Atom v1.0 and found this problem still exists.  Look forward for a fix soon.

**Comment by heyyoyo** [comment] 2015-06-28 08:01
Same as @LeoK987 upgrade to Atom v1.0.0.
Which version of Chrome has been used in last Atom 1.0.0 ?

**Comment by mnquintana** [comment] 2015-06-28 12:07
This is blocked until Atom upgrades to a version of Electron built on Chrome 43.

**Comment by yuki-takei** [comment] 2015-07-03 10:12
I fork [atom/atom](https://github.com/atom/atom) to build personal deb package using electron 0.26.1 (chrome 43.0.2357.65) at [here](yuki-takei/atom-using-electron-chrome-42).
I'm going to release continuously for a while.

direct link to binaly:
https://github.com/yuki-takei/atom-using-electron-chrome-42/releases/latest

Use it AT YOUR OWN RISK.

**Comment by yuki-takei** [comment] 2015-07-04 19:58
I fork [atom/atom](https://github.com/atom/atom) to build personal deb package using electron (>= 0.27.2, chrome 43.0.2357.65) at [here](https://github.com/yuki-takei/atom-using-electron-chrome-42).
I'm going to create releases continuously for a while.

releases page:
https://github.com/yuki-takei/atom-using-electron-chrome-42/releases/latest

Use it AT YOUR OWN RISK.

**Comment by vadviktor** [comment] 2015-07-10 09:34
I am using Xubuntu core on Ubuntu 15.04, running it in VirtualBox on Win8.1. I have disabled USB support and switched to PS/2 input but no use, Atom 1.0 is still unable to select text.

This is not a problem when I run Xubuntu on VMware Workstation, that VM reports mouse correctly.

**Comment by ricardopieper** [comment] 2015-07-20 00:13
@yuki-takei, I quoted you in some posts, I did the same thing as you did and also solved some other problem. If you want, you can provide some information here (https://github.com/atom/atom/issues/7974).

@heyyoyo, the other problems that appeared in Yuki's build, is that (https://github.com/atom/notifications/issues/85) one of them?

**Comment by yuki-takei** [comment] 2015-07-20 10:33
@ricardopieper
Hi. I'm happy to see your care about this problem.
Frankly speaking, I don't disgust against your quote, but I'm afraid you have some misunderstanding.

The [yuki-takei/atom-using-electron-chrome-42](https://github.com/yuki-takei/atom-using-electron-chrome-42) repos is based on [atom/ks-electron-chrome-42](https://github.com/atom/atom/tree/ks-electron-chrome-42). Those changes are not my own job, but committed by @kevinsawicki and @zcbenz.

\# What I did is only forking and merging :-P


In this two weeks, @thomasjo seems to attempt to upgrade to Electron. See https://github.com/atom/atom/pull/7877.

While I don't watch the progress of the official atom team,
I think your information about `command-register.coffee` might be helpful for them.

Why don't you comment to PR #7877 ? (or link to issues #7974)

**Comment by ricardopieper** [comment] 2015-07-20 12:38
Ah... I see. Thanks for clarifying that. I'll do that.

**Closed** 2015-09-08 15:41 UTC
Labels: blocked, bug, linux

**Comment by zl4bv** [comment] 2015-09-17 20:34
Looks like the fix has been released with Atom 1.0.12 - many thanks!

**Comment by jadbox** [comment] 2015-09-22 18:09
Seems like it's fixed for me too! Thanks so much folks.

**Comment by SlyDen** [comment] 2015-09-23 06:25
yes, it works now :) (VirtualBox 5.0.4 && Atom 1.0.15)

**Comment by LeoK987** [comment] 2015-09-23 07:15
Ubuntu PPA version stays at 1.0.11 (why?), which still has the problem.  I
just downloaded 1.0.15 from github and it works.

**Comment by 50Wliu** [comment] 2015-09-23 13:00
> Ubuntu PPA version stays at 1.0.11 (why?)

The Ubuntu PPA is a third-party PPA which isn't maintained by the Atom devs, so it can occasionally lag behind for a bit.
