### ISSUE TITLE
Uncaught TypeError: Cannot read property 'matchesParams' of undefined

### ISSUE THREAD

**Issue by geesche** [atom/atom#15243] opened 2017-08-10 17:53 UTC
[Enter steps to reproduce:]

/cc https://github.com/atom/atom/issues/15243#issuecomment-321791635

Error occurred while updating Atom.

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'matchesParams' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:197

TypeError: Cannot read property 'matchesParams' of undefined
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:197:28
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.findMarkers (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:193:23)
    at DisplayLayer.computeFoldsInBufferRowRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:1121:53)
    at DisplayLayer.updateSpatialIndex (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:845:30)
    at DisplayLayer.populateSpatialIndexIfNeeded (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:1064:18)
    at DisplayLayer.doBackgroundWork (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:140:16)
    at TextEditor.module.exports.TextEditor.doBackgroundWork (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:347:35)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3:65
```

### Commands

```
     -0:06.6.0 application:reopen-project (input.hidden-input)
  2x -0:04.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-compile-less 0.12.0 
atom-typescript 10.1.12 
block-selection-mode 0.3.0 
linter 1.11.18 
pretty-json 1.6.4 
```

**Comment by rsese** [comment] 2017-08-11 01:17
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by geesche** [comment] 2017-08-11 11:46
See answers below
Cheers

**Comment by rsese** [comment] 2017-08-11 21:42
Thanks @geesche, I tweaked the issue body to mention what was happening when you saw the error.  Not super straightforward to try and reproduce since it involves updating Atom versions but we can leave this open for a couple of weeks in case someone else runs into it.

**Comment by lee-dohm** [comment] 2017-08-24 18:55
Since this doesn't reproduce in Safe Mode and we haven't gotten any other reports of this happening, we're going to close this as not reproducible.

Please let us know if you get any new information on the problem.

**Closed by lee-dohm** 2017-08-24 18:55 UTC
Labels: more-information-needed, needs-reproduction, uncaught-exception
