### ISSUE TITLE
`!` pattern in .gitignore

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/atom#16204] opened 2017-11-16 07:22 UTC
".gitignore" file:

```
*.log
!/test/aaa.log
```

After you create the file "/test/aaa.log", you'll find the filename is displayed as ignored (gray), which is incorrect.

**Comment by rsese** [comment] 2017-11-16 18:48
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/196. You may want to subscribe there for updates.  Also, for future issues it would be super helpful if you can fill out the issue template since it helps us triage issues.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-16 18:48 UTC
