### ISSUE TITLE
Changes made using git not reflected in editor

### ISSUE THREAD

**Issue by arjunkrishnababu96** [atom/atom#17064] opened 2018-04-01 05:23 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The project does not sync with the git commands I use on my terminal.

### Steps to Reproduce

1. Create a new empty directory
2. Initialize git with `git init`
3. Create a new empty file and add it to git.
`touch foo.txt`
`git add foo.txt`
`git commit -m 'first commit'`
4. Open the file in Atom
`atom foo.txt`
5. Write some text, say "blah" onto the file. Save it using `Ctrl + S`.
6. Discard the changes you just made using git. 
From the terminal, type `git checkout -- foo.txt`
As expected, the changes to the file go away in atom.
7. Again make changes to the file. Type "blah" to `foo.txt` and save using `Ctrl + S`. **You might want to press `Ctrl + S` a couple or more times, even if the file was saved (this seems to be the key to reproducing the issue).**
8. Discard these changes using git
`git checkout -- foo.txt`

**Expected behavior:**
The changes made to the file should go away in the editor. The file should be back to how it looked like after the last commit. 

**Actual behavior:**
* The changes made to the file stays in that file. (ie., in this example, "blah" remains in that file; does not go away).
* On the tree view, the color of the file changes to grey from orange, which is as expected (on the default theme you get when you install Atom, orange indicates there are uncommitted changes, and grey indicates no uncommitted changes).
* If you close the file in Atom, and then re-open it, the file now appears as it should be (no "blah").
* It's not a problem with git, because the file is the way it should be when you view it using other tools, such as `vim`, `cat`, or even other text editors. 

I'm not sure, but I think it's a problem with how the file is *displayed*.

**Reproduces how often:**
All the time. Super consistent for me since I first noticed it about 6 hours ago (and I've been using Atom as my go-to editor for over 2 years now).

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
$ atom --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
```
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 3.6.4
git 2.14.1
```

OS: [Pop!_OS](https://system76.com/pop) 17.10 (based off of Ubuntu 17.10) (Linux)

I was able to reproduce this issue on both `atom` and `atom-beta`.

### Additional Information

As mentioned in **Steps to Reproduce** above, when saving the 2nd time, make sure you press `Ctrl + S` multiple times.

**Comment by rsese** [comment] 2018-04-02 21:21
Thanks for the report - I'm unable to reproduce with Atom 1.25 on Ubuntu 17.10.  Can you confirm that you installed Atom with one of the official installation methods?

https://flight-manual.atom.io/getting-started/sections/installing-atom/

And are there any error in devtools console?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools

Lastly, is this behavior new for you as of 1.25 and worked find in previous versions?

**Comment by JSifontz** [comment] 2018-04-12 04:37
Hello. 

I was unable to reproduce the error with atom 1.25.1 on Ubuntu 16.04 LTS.

**Comment by lee-dohm** [comment] 2018-04-21 16:01
Thanks for taking the time to contribute!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/17064#issuecomment-378050545. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by lee-dohm** 2018-04-21 16:01 UTC
Labels: more-information-needed
