### ISSUE TITLE
Uncaught Error: Cannot find module './load-config'

### ISSUE THREAD

**Issue by athanclark** [atom/atom#5008] opened 2015-01-12 16:04 UTC
1. Install `linter-jshint`
2. Try doing some javascript

For some reason, these errors aren't occouring in other javascript files in the same session. Also, this is the same session that I installed linter-jshint on, through the GUI package installer in `Edit > Preferences`.

**Atom Version**: 0.165.0
**System**: linux 3.13.0-43-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './load-config'

```
At module.js:346

Error: Cannot find module './load-config'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:380:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at /home/athan/.atom/packages/jshint/node_modules/lazy-req/index.js:6:43
  at lint (/home/athan/.atom/packages/jshint/index.js:156:34)
  at delayed (/usr/share/atom/resources/app/node_modules/roaster/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5408:27)

```

### Commands

```
  6x -6:52.9 core:backspace (input.hidden-input)
     -6:50.5 core:confirm (input.hidden-input)
     -6:44.8 core:undo (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
 13x -6:34.8 core:move-right (input.hidden-input)
  6x -6:33.8 core:backspace (input.hidden-input)
     -6:32.0 core:confirm (input.hidden-input)
     -6:10.6 editor:newline (input.hidden-input)
     -5:52.7 core:backspace (input.hidden-input)
     -5:44.8 core:save (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
  3x -2:42.2 core:move-down (input.hidden-input)
     -1:59.3 core:delete (input.hidden-input)
     -1:59.2 core:move-down (input.hidden-input)
     -1:56.9 editor:newline (input.hidden-input)
     -1:18.3 core:save (input.hidden-input)
     -0:59.3 core:confirm (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "fontSize": 25,
    "invisibles": {},
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
autocomplete-plus, v1.1.0
color-picker, v1.2.6
git-log, v0.2.0
ide-haskell, v0.3.0
javascript-snippets, v1.0.0
jsformat, v0.7.18
language-haml, v0.14.0
language-haskell, v1.0.0
language-javascript-semantic, v0.1.0
linter, v0.9.1
linter-csslint, v0.0.11
linter-erb, v0.0.3
linter-hlint, v0.3.1
linter-htmlhint, v0.0.8
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
minimap, v3.5.4
script, v2.16.0
seti-syntax, v0.2.1
seti-ui, v0.6.1
travis-ci-status, v0.11.1

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment] 2015-01-12 16:27
I think this is a duplicate of sindresorhus/atom-jshint#56. Please add any further debugging info that you find on that issue. Thanks!

**Closed by maxbrunsfeld** 2015-01-12 16:27 UTC
