### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.33.1\res...

### ISSUE THREAD

**Issue by 19card** [atom/atom#18615] opened 2018-12-22 21:33 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\me\AppData\Local\atom\app-1.33.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:166

Error: The specified module could not be found.
\\?\C:\Users\me\AppData\Local\atom\app-1.33.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:1:639369)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:3077425)
    at get_manager (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:3077505)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:3077631)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:996394)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1228483)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1226468)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:285213)
```

### Commands

```
     -1:00.7.0 atom-live-server:startServer (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
autocomplete 0.47.0 
autocomplete-java 1.2.7 
autocomplete-python 1.11.0 
busy-signal 1.4.3 
debug 0.0.1 
emmet 2.4.3 
file-icons 2.1.27 
go-debug 1.6.2 
highlight-selected 0.14.0 
Hydrogen 2.7.0 
ide-css 0.3.2 
ide-html 0.5.0 
ide-python 1.1.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
python-autopep8 0.1.3 
python-debugger 0.2.0 
script 3.18.1 
todo 0.6.0 
toggler 0.3.1 
```

**Comment by 19card** [comment] 2018-12-22 21:44
Never mind this issue.

I fixed it through taking the keyboard layout node from an older version, and copying the necessary files into "%LOCALAPPDATA%/atom/app-1.17.0/resources/app/node_modules/keyboard-layout/"

I got this idea through looking at similar issues, and you guys mentioned looking through that directory.  I dunno why it gets deleted.  It was fine before last time I opened Atom.

![image](https://user-images.githubusercontent.com/41201638/50378800-9329b580-0608-11e9-83d8-e6a03421056c.png)

**Comment by rsese** [comment] 2018-12-24 23:04
Glad you have things working - some other folks have mentioned that the issue seemed related to the anti-virus application running on their computer and reinstalling with anti-virus temporarily disabled fixed things up.

---

We noticed that this looks like a duplicate of #14461 so you can subscribe there for updates if you'd like.  Also, if you have an anti-virus program running you can try temporarily disabling it and then reinstall Atom to see if that helps.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-12-24 23:04 UTC
