### ISSUE TITLE
development package not joined to .atom directory

### ISSUE THREAD

**Issue by mrkeysh** [atom/atom#16292] opened 2017-11-29 03:08 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

the package i created as development created a folder locally as per the "Package Generator" Project Manager variable (C:\Users\XXX\Github\).  
Using the the "package generator", i saw the two sets of folders (one in Github and the other in .atom) synced.  They are no longer joined / synced.  How does this happen and how to resync them?

### Steps to Reproduce
Crtl-P --> Package Generator
Entered New package name
New package created in project manager directory in the github directory and joined directory created in .atom packages directory.
Make several changes to package.
Save
Reboot
???? not sure when this happens or truly how to recreate it, but sometime after reboot (and not every reboot and so far only 1 out of 1000000 times it has happened)

**Expected behavior:** [What you expect to happen]
.atom directory and github / dev / project manager directory should be synced

**Actual behavior:** [What actually happens]
Folder in .atom direcotry is empty and not synced with the same folder in the github / dev / project manager directory

**Reproduces how often:** [What percentage of the time does it reproduce?]
First and only time so far

### Versions
Windows 10 (64 bit) Home Version 1703 Build 15063.726
Atom 1.22.1
Electron 1.6.15
Chrome 56.0.2924.87
Node 7.4.0
apm 1.18.8
npm 3.10.10
node 6.9.5 x64
python 3.6.0
git 2.10.2.windows.1
visual studio 2015

### Additional Information
is there a command or package to "rejoin" two folders?

**Comment by rsese** [comment] 2017-11-29 22:21
Thanks for the report!

> Reboot

Do you mean restart your computer at this point?

> Using the the "package generator", i saw the two sets of folders (one in Github and the other in .atom) synced. They are no longer joined / synced. How does this happen and how to resync them?

Hmmm, that's odd - the directory under `.atom/packages/` is a symlink to your package directory under your `github/` directory, not sure how the link was broken based on your repro steps.

> is there a command or package to "rejoin" two folders?

In your package directory in your `github/` directory, run this command

```
apm link
```

> not sure when this happens or truly how to recreate it

Since there's no specific steps to reproduce we'll go ahead and close this issue but let me know if you still have trouble linking your package.

**Closed by rsese** 2017-11-29 22:21 UTC

**Comment by mrkeysh** [comment] 2017-11-30 17:20
Thank you for the command line.  I did some extensive searching on the Atom pages and couldn't find that command anywhere.  
I did find someone's blog who had that command in regards to using and updating the existing package from someone/somewhere else for development purposes. Can you possibly add this to the flight-manual or another section?  
My first thought when developing packages and having the two folders unlink/unsync/unjoin wasn't to go to the command line, though it seems more obvious in retrospect now.

As for "reboot", i did mean restart my computer, but also restart Atom.io.  

I will let you know if it happens again, thank you!
