### ISSUE TITLE
Cursor position problem

### ISSUE THREAD

**Issue by drnetInformatica** [atom/atom#9343] opened 2015-10-30 08:29 UTC
After the 1.1 upgrade I've a great problem with cursor position. It's not in the right position when I write.

I use Linux, Fedora 23

**Comment by Oustad** [comment] 2015-10-30 09:36
I'm having the same issue after upgrading to 1.1 on Windows 10.
As shown in the attached gif it is about one character to the right of where the actual position should be.

![atomcursor](https://cloud.githubusercontent.com/assets/319181/10842415/972d0c6e-7ef1-11e5-92c0-2d6603dc79c3.gif)

**Comment by RemiAWE** [comment] 2015-10-30 09:43
Same issue on Windows 10 and OSX El Capitan on Atom 1.1

**Comment by izuzak** [comment] 2015-10-30 10:04
Thanks for the report, everyone. Can all of you share which font you're using, which theme, and if you have anything if your styles.less file? Also, can you make sure that you can reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

Also /cc @as-cii for awareness.

**Comment by ghs** [comment] 2015-10-30 10:10
Same with me. Kinda strange end of line which from other side makes the jshint crash and burn.
<img width="287" alt="captura de pantalla 2015-10-30 a las 11 07 41" src="https://cloud.githubusercontent.com/assets/94248/10843046/921afca4-7ef6-11e5-9c56-129208105630.png">
<img width="240" alt="captura de pantalla 2015-10-30 a las 11 07 27" src="https://cloud.githubusercontent.com/assets/94248/10843052/996258cc-7ef6-11e5-8c9a-94a0c0742ed9.png">

I am on yosemite with atom 1.1.0 updated like 2 minutes ago.

**Comment by izuzak** [comment] 2015-10-30 10:11
Thanks, @ghs. Can you provide answers for the questions I posed in https://github.com/atom/atom/issues/9343#issuecomment-152479512 ?

**Comment by ghs** [comment] 2015-10-30 10:16
In save mode works fine. Started it once again as normal and problem continues. But then changed SETI UI and problem resolved. Looks like its from the theme.

**Comment by Oustad** [comment] 2015-10-30 10:17
@izuzak Looks like the problem on my end is Seti syntax theme, if I change that to for example One Dark, everything is fine.

**Comment by as-cii** [comment] 2015-10-30 10:17
This could be related to: https://github.com/jesseweed/seti-syntax/issues/106 where a weird padding-left and margin-left is being set.

**Comment by ghs** [comment] 2015-10-30 10:18
Yes, actually is the syntax, not the UI.

**Comment by izuzak** [comment] 2015-10-30 10:19
Hah, @as-cii beat me to it -- was just going to point to that issue in seti-syntax.

Thanks for confirming, everyone.

**Comment by jeekajoo** [comment] 2015-10-30 10:21
Had a problem with cursor position too, since 1.1.
Found that https://atom.io/packages/atom-innerspace was the cause, uninstalled, problem solved.

**Comment by ghs** [comment] 2015-10-30 10:30
@jeekajoo, I don't have innerspace and the problem still persists.

**Comment by as-cii** [comment] 2015-10-30 13:29
So, I had a second look at this and it seems like the syntax theme was using an hack in order to position the cursor properly in the previous versions of Atom. That hack shouldn't be necessary anymore, so I think we can close this.

Thanks everyone! :pray:

**Closed by as-cii** 2015-10-30 13:29 UTC
Labels: editor-rendering, more-information-needed, needs-reproduction

**Comment by covard** [comment] 2015-10-30 13:43
@as-cii so does that mean that it's resolved and we will have an update soon?

**Comment by as-cii** [comment] 2015-10-30 13:47
@covard: I have noticed there is a PR open to fix this, so as soon as https://github.com/jesseweed/seti-syntax/pull/107 gets :ship:ped you should get an update that fixes this.

In the meantime, you can comment out the hack [as described here](https://github.com/jesseweed/seti-syntax/issues/106#issuecomment-152369937).

**Comment by covard** [comment] 2015-10-30 13:51
@as-cii thanks I just noticed that and got a work around for it for the time being.
