### ISSUE TITLE
Filepath/name not visible when creating or renaming a file.

### ISSUE THREAD

**Issue by rubencausyn** [atom/atom#11725] opened 2016-05-10 08:11 UTC
### Description

When creating a new file or renaming a file in the dialog *Enter the new path for the file* there is no way of seeing the end of a filename/path when this path is longer than the dialog textbox.

<img width="521" alt="schermafdruk 2016-05-10 10 07 39" src="https://cloud.githubusercontent.com/assets/2344982/15139565/137aed44-1697-11e6-82d2-699325bb65df.png">

### Steps to Reproduce

1. rename a file with a long path or filename
2. try to modify the end of the filename
3. the cursor goes to the correct place in the text but there is no way to see this visually.

**Expected behavior:** [What you expected to happen]

The cursor moves within the text and the text becomes visible.

**Actual behavior:** [What actually happened]
The cursor moves withing the text but the text is not visible on screen in the textbox.

### Versions

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
OSX:  10.11.4

**Comment by Ben3eeE** [comment] 2016-05-10 08:29
This looks like a duplicate of https://github.com/atom/tree-view/issues/473 see comment https://github.com/atom/tree-view/issues/473#issuecomment-131388489 for a possible workaround.

**Comment by 50Wliu** [comment] 2016-05-10 11:58
Closing as a duplicate of atom/tree-view#473.

**Closed by 50Wliu** 2016-05-10 11:58 UTC
