### ISSUE TITLE
Cursor in unexpected position when moving between lines with CJK characters.

### ISSUE THREAD

**Issue by BurningLutz** [atom/atom#11733] opened 2016-05-11 03:19 UTC
When I move the cursor up and down, it is expected to be placed at the same 'visual' column.
![2016-05-11 11 10 38](https://cloud.githubusercontent.com/assets/15797639/15168991/41b28744-1769-11e6-896b-dfe6aff4d006.png)
![2016-05-11 11 10 55](https://cloud.githubusercontent.com/assets/15797639/15168990/41aeee0e-1769-11e6-930e-affcf945ba9f.png)

**Comment by Download** [comment] 2016-09-13 07:37
May be related: 
Cursor in unexpected position when moving it while selecting #12677

**Comment by 50Wliu** [comment] 2016-09-13 14:54
@Download #12677 is very different.  If you count the number of characters in each line in this example, you'll find that the cursor jumps to the same column, just not the same "visual" column.

**Comment by Download** [comment] 2017-09-16 17:00
@50Wliu I never said they were the same. I said that *maybe* they are related.

I find this stale bot a bit annoying. What activity are we supposed to add if no one responds to the issue??

**Comment by 50Wliu** [comment] 2017-09-16 20:37
@Download I never said you said they were the same either :wink:.

How I would respond to the stale bot is by confirming that the issue still reproduces in the latest version of Atom, and in safe mode.  That gives us the most useful information.

**Comment by Download** [comment] 2017-09-20 08:03
> How I would respond to the stale bot is by confirming that the issue still reproduces in the latest version of Atom, and in safe mode. That gives us the most useful information.

This is unreasonable imho. I am contributing my free spare time by reporting this issue. If you made no fixes in this area then it most probably is not fixed. If you just don't do anything with the report you cannot expect me to keep reproducing it in every new version.

If / when you guys decide to try to pick up this issue you can try the repro steps in just a couple of minutes.

If you decide this is all too much work, that's fine too. But it would probably mean I won't be reporting any new issues anymore.

**Comment by Download** [comment] 2017-09-20 08:04
(btw this is not my issue, but the general idea applies... your lack of action on an issue seems like a strange reason to declare it stale is all I'm saying. Not trying to pick a fight, just letting you know how the stale bot makes mee feel)

**Comment by 50Wliu** [comment] 2017-09-20 08:53
I understand your frustration.  However, you also have to understand that the Atom organization receives a flood of issue comments every day (for example, I have 200 unread notifications to get through).  Occasionally, issues get lost in the mix.  There have been many cases where a pull request is merged that fixes a bug, but we weren't aware that there was an open issue for it.  In other cases, some PRs like Electron upgrade PRs fix many issues, some of which we only become aware of months later.  In both those cases, the missed issues remain open, even though they have been fixed months, or even years, in the past.  That's why it's important to know whether the issue is still relevant, even if at a glance no work has been done to address it.

Now, with all that said and done, I can still reproduce this issue on Atom 1.22.0-dev-b269b2086.

**Comment by Download** [comment] 2017-09-21 10:04
Thanks for adding the triaged label. I understand you guys get flooded. I was never complaining about the fact that issues can linger around for a long time. I understand that. I have open source projects published as well and sometimes you just don't have time to look at them. I understand all that.

What I do not understand however is the stale bot 'threatening' to close the issue because of inactivity, when in fact the inactivity is coming from the Atom developers side.  I wrote my comment on the wrong issue (though it applies here as well), but I reported this (maybe related) issue almost a year ago:

https://github.com/atom/atom/issues/12677

I worked on that report. The repro steps are as clear as I can make them. It has been lying here collecting dust for all that time. No milestone, no one assigned, not triaged (no complaint, just observation) only to get marked as stale by some bot (complaint here!). Can you imagine what that feels like? I'm like why do I even bother? 

It would be very cool of you guys to just run through the repro once and add e.g. triaged label or dismiss it or whatever but at least acknowledge it exists. I estimate it will take somewhere around 5 minutes to triage it and determine whether it still applies to the current release or not, if info is missing etc. I am 100 percent sure it will take you guys a lot less work to triage it then it did for me to write it, because repro is basically pasting two lines of text and then moving the cursor with the arrow keys. If you decide that all this dealing with issues from random Github users is too much work, I can completely understand that as well (your issue list is scary long!). However in that case it would be fair to those random users to clearly state that, so we don't spend time writing reports that just don't get looked at.

I think one look at my report will show you it's well written and has the info you need to reproduce. I worked in IT development support and I've been on the other end of bug reports as my day job, which is why I would never submit crappy bug reports. And I know from experience it should be easy to distinguish reports like 'Atom dont work on my PC!!!' from actual well written bug reports. Quickly close the nonsense reports and quickly triage the reports that look well written. I bet you could clear out half your untriaged issues in a couple of days if you did that. And I seriously doubt the stale bot is actually helping you guys. But that's my view and I'm just some random Github user  :)

**Comment by Download** [comment] 2017-09-21 10:12
Sorry for the rant.  :)  I just saw that my bug has a label 'Bug'. Does that mean that it's triaged? If so, that would make me a very happy man!

**Comment by 50Wliu** [comment] 2017-09-21 12:24
`triaged` is a relatively new label that indicates that an Atom maintainer has reproduced the bug (if it's a bug) or confirmed that we want the enhancement (if it's an enhancement).  Adding `triaged` whitelists those issues from being marked as stale.  I'll take a look at #12677 now and see if I can reproduce it.

**Closed** 2019-02-11 02:25 UTC
Labels: bug, triaged
