### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/jllopis/Documentos/devel/docker/odoo-grupoesoc/addons/partner-contact/partner_gender/models.py'

### ISSUE THREAD

**Issue by Yajo** [atom/atom#6840] opened 2015-05-18 11:10 UTC
1. `git checkout branch-with-some-file`
2. Open that file in Atom.
3. `git checkout branch-without-that-file`

**Atom Version**: 0.199.0
**System**: linux 3.19.7-200.fc21.x86_64
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/jllopis/Documentos/devel/docker/odoo-grupoesoc/addons/partner-contact/partner_gender/models.py'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/home/jllopis/Documentos/devel/docker/odoo-grupoesoc/addons/partner-contact/partner_gender/models.py'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "editor": {
    "softWrap": true,
    "fontSize": 14,
    "tabLength": 4,
    "showIndentGuide": true,
    "invisibles": {},
    "preferredLineLength": 79
  }
}
```

### Installed Packages

```coffee
# User
atom-terminal, v0.7.0
editorconfig, v1.0.0
language-docker, v1.1.3
language-restructuredtext, v0.5.0
linter, v0.12.2
linter-flake8, v1.4.0
linter-rst, v0.0.3
linter-xmllint, v0.0.5
minimap, v4.9.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.3
minimap-selection, v4.2.0
rst-preview-pandoc, v0.1.7
sync-settings, v0.2.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-18 12:33
Duplicate of #6210, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-18 12:33 UTC
