### ISSUE TITLE
Restore Previous Windows on Start not working on fresh install

### ISSUE THREAD

**Issue by osouglob** [atom/atom#19558] opened 2019-06-18 12:59 UTC
Fresh install on Windows 2012
open Atom by doubleclicking on a file
or open Atom and drag and drop a few files
also tried editing this files and saving changes.
exit by exit button
reopen Atom, no previously opened files are open.

Fix:
Open Atom
Create new file and save this file somewhere
I think at this moment some hidden setting gets set
possibly projectRoots

after this, 
the setting works as expected, but a fresh install should work out of the box

**Comment by rsese** [comment] 2019-06-18 18:11
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/settings-view/issues/1129 so you can subscribe there for updates if you'd like.

For future issues, please use the issue template or your issues may be closed.  The information in the template is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-18 18:11 UTC
