### ISSUE TITLE
When close window, no alert me to save.

### ISSUE THREAD

**Issue by havthgem** [atom/atom#11193] opened 2016-03-18 02:10 UTC
1. New window and new empty file.
2. Type something.
3. Close current window. (`shift-cmd-w` or click red button of window top left)

**Expected behavior:** Alert me to save file.

**Actual behavior:** Window closed, no alert.

### Environment

System: Mac OS X 10.11.3
Atom Version: 1.6.0 ~ 1.5.x

**Comment by ArniPL** [comment] 2016-03-21 11:17
I believe this is intentional (#942).

I'm pretty sure it worked correctly in 1.6, **but** it's not working in 1.7.0-beta0. Nothing gets restored.

I thought that checking "Open Empty Editor On Start" option controls that behavior but I think it does nothing now (1.7.0-beta0). I tried looking between some issues (#942, #6605) and PRs (#8397, #9042) to get to know more. Could someone confirm expected behavior of closing unsaved buffers, restoring session and checking that "empty editor" option? Thanks!

**Comment by jhasse** [comment] 2016-03-24 15:19
Although it's intentional, it would be nice if there was an option to disable this new feature. In Sublime Text it was called "hotexit" IIRC.

**Comment by havthgem** [comment] 2016-03-25 01:42
I argee with @jhasse . Option is needed. If no, I was always uneasy.

**Comment by wimdeblauwe** [comment] 2016-04-08 19:03
I have 1.6.2 (on Mac OS X) and I was wondering why sometimes some text written in Atom was lost and sometimes it gets restored when opening Atom again. It probably has to do with what @ArniPL has written in his edit. Quite annoying. I thought it did not work ever, but #942 indicates that it is there since 1.4. It just doesn't always work. I have noticed that it always works if you open the "preferences" as well so that there are multiple tabs open.

**Comment by mjmasn** [comment] 2016-04-29 15:55
Running 1.7.x I have lost countless unsaved files because I'm used to the "hotexit" feature of Sublime Text which restores the state of all windows and tabs whether they are saved or not. Frankly most apps have this no-need-to-save behaviour these days.

It wouldn't be a problem if Atom actually asked if I wan't to save unsaved changes. If this is intentional it's a crazy decision...

**Comment by lee-dohm** [comment] 2016-05-01 06:11
If you have a project open (i.e. one or more "project root" folders set), then Atom saves the unsaved changes along with the other project information. When you reopen the same project (i.e. the same set of "project root" folders on initial launch as when Atom exited) the files and their unsaved changes will be restored.

There is currently a known Issue where unsaved changes are not restored when there is no project root set https://github.com/atom/atom/issues/10474. There is also an Issue (https://github.com/atom/atom/issues/10517) tracking that all of this is confusing and should be redesigned.

Since this is a duplicate of one or more of the above, I'm going to close the Issue. If there is anything I misunderstood, please let me know!

**Closed by lee-dohm** 2016-05-01 06:11 UTC

**Comment by umpirsky** [comment] 2017-04-01 09:33
I want this as a feature. :)

Sometimes, I just want to close all tabs without million prompts to save them. Is this possible?

**Comment by t3573393** [comment] 2017-04-08 12:49
I always forget to save the file , I want this feature, please add it.
