### ISSUE TITLE
Uncaught Can't find APP. file

### ISSUE THREAD

**Issue by nhytros** [atom/atom#18733] opened 2019-01-23 14:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.04.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find APP. file

```
At /usr/share/atom/resources/app/static/<embedded>:11

undefined
```

### Commands

```
     -2:29.4.0 core:paste (input.hidden-input)
     -2:28 intentions:highlight (input.hidden-input)
     -2:27.9.0 core:paste (input.hidden-input)
     -2:22.4.0 intentions:highlight (input.hidden-input)
     -2:22.2.0 core:paste (input.hidden-input)
     -2:20.5.0 core:move-left (input.hidden-input)
     -2:14.8.0 core:backspace (input.hidden-input)
 21x -2:14 core:move-right (input.hidden-input)
 16x -2:11.5.0 core:backspace (input.hidden-input)
  3x -0:26.7.0 core:move-left (input.hidden-input)
  3x -0:22.4.0 core:move-right (input.hidden-input)
     -0:20.8.0 intentions:highlight (input.hidden-input)
     -0:20.6.0 emmet:encode-decode-data-url (input.hidden-input)
     -0:18.8.0 core:backspace (input.hidden-input)
     -0:16.2.0 core:move-right (input.hidden-input)
     -0:16 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-bootstrap3 1.2.12 
autoclose-html 0.23.0 
browser-plus 0.0.98 
busy-signal 2.0.0 
color-picker 2.3.0 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.28 
ide-php 0.7.18 
intentions 1.1.5 
linter 2.3.0 
linter-php 1.6.0 
linter-twig 0.4.2 
linter-ui-default 1.7.1 
minimap 4.29.9 
php-twig 4.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
project-manager 3.3.6 
sort-lines 0.18.0 
spacegray-atom-dark-syntax 1.3.2 
```

**Comment by Arcanemagus** [comment] 2019-01-23 17:41
Thanks for contributing!

We noticed that this looks like a duplicate of issues like https://github.com/atom/atom/issues/18429 where it seems like the problem was narrowed down to https://atom.io/packages/emmet.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-01-23 17:41 UTC
