### ISSUE TITLE
Dragging a tab outside atom should open that tab in a new window.

### ISSUE THREAD

**Issue by delk0** [atom/atom#11987] opened 2016-06-16 00:49 UTC
Shouldn't it? It's a cool feature i'm missing since I switched from sublime. I'm using Windows 10 btw.

**Comment by Ben3eeE** [comment] 2016-06-16 06:01
Duplicate of https://github.com/atom/tabs/issues/39?

**Comment by delk0** [comment] 2016-06-16 12:59
Yep, but damn that one is old...

**Comment by 50Wliu** [comment] 2016-06-16 17:01
Closing as a duplicate of atom/tabs#39 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-16 17:01 UTC
