### ISSUE TITLE
Cursor offset right from Unicode content

### ISSUE THREAD

**Issue by mapmeld** [atom/atom#7529] opened 2015-06-29 06:22 UTC
Hi,

I'm editing some files which include Myanmar text. This includes diacritic characters (meaning char + char adding a diacritic (above / below / left / right) the previous char). Atom appears to give each char equal space, meaning that I need to click right of the text to select it, and the highlight appears offset right, too. Each string makes it more difficult to highlight text appearing after it on the line.

![screen shot 2015-06-29 at 3 16 43 pm](https://cloud.githubusercontent.com/assets/643918/8402027/e85fe6c8-1e71-11e5-92db-2fa52ebd3203.png)

Put the text နေပြည်တော် in the middle of a long line to see what this looks like. This problem will occur with many other scripts, for example Devanagari used widely in India and Nepal - use this text: देवनागरी. Can you use HTML5 Canvas measureText() ?

**Comment by izuzak** [comment] 2015-06-29 06:41
Thanks for the report -- I believe this is a duplicate of https://github.com/atom/atom/issues/1849, so I'm closing this in favor of that issue. You might also be interested in https://github.com/atom/atom/issues/6055 and https://github.com/atom/atom/pull/6083.

**Closed by izuzak** 2015-06-29 06:41 UTC
