### ISSUE TITLE
[Feature request] Dialog with unsaved changes should accept "Don't save all"

### ISSUE THREAD

**Issue by grabbou** [atom/atom#7906] opened 2015-07-15 10:03 UTC
Hey, when working on a large project I often find myself opening lots of files that I often forgot to close (and sometimes they are deleted from the filesystem while still being opened). When I am about to close the project, I need to click "Don't save" more than 30 times to close it. It would be really nice to have "No to all" option that I can just click (in my case, I am using source control so I am pretty sure all changes I wanted to save were already committed).

That's the dialog I am talking about:
<img width="350" alt="screen shot 2015-07-15 at 12 01 20" src="https://cloud.githubusercontent.com/assets/2464966/8696048/8a1cec76-2ae9-11e5-80f5-ef6eb1f6fc51.png">

**Comment by thomasjo** [comment] 2016-07-06 07:25
I'm closing this as a duplicate of #9957.

Although this issue was posted much earlier, the other one has more participants and a bit more info. Anyone subscribed to this issue, should subscribe to #9957 instead.

**Closed by thomasjo** 2016-07-06 07:25 UTC
Labels: enhancement
