### ISSUE TITLE
Crash on Ubuntu when dragging a Firefox window over Atom

### ISSUE THREAD

**Issue by arashpayan** [atom/atom#3593] opened 2014-09-21 01:41 UTC
Atom Version: 0.129.0
Video of me triggering the bug: http://ara.sh/private/atom-crash.ogv
Reproducible every time.

Environment:
Ubuntu 14.04 (all updates installed as of filing this issue)
Unity desktop environment

Repro steps:
1) Launch atom from the Terminal
2) Open a Firefox window (or use an existing one)
3) Drag the Firefox tab anywhere over the Atom window

Actual behavior:
It crashes

Expected behavior:
Not crash :-)

Additional Information:
The terminal prints out the following after the crash:
```
[7950:0920/180947:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[7950:0920/180947:ERROR:browser_main_loop.cc(189)] GTK theme error: Unable to locate theme engine in module_path: "pixmap",
ATTENTION: default value of option force_s3tc_enable overridden by environment.
App load time: 88ms
[7984:0920/180947:INFO:renderer_main.cc(227)] Renderer process started
[7950:0920/180948:INFO:CONSOLE(18)] "Window load time: 778ms", source: /opt/atom/resources/app/src/window-bootstrap.js (18)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 1360 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by oalexandersson** [comment] 2015-01-08 09:12
Atom version 0.158.0
OS: Ubuntu 14.10
Desktop: XFCE 4.10

100% reproducible. Definitely not Unity related. It's really annoying; when you move a tab out to create a new browser window with that tab, you have to be super careful to not move it over the atom window.

**Comment by cmtonkinson** [comment] 2015-02-08 12:47
Atom: 0.1770
OS: Arch Linux
Desktop: GNOME Shell 3.14.3

Same thing, every time. Note that reproduction has nothing to do with how Atom is started (e.g. by the terminal) it just affects whether you see this error.

```
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 764 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by bglass** [comment] 2015-02-25 08:45
Atom version 0.181.0
OS: Ubuntu 14.10
Desktop: KDE 4.14.1

Same behaviour (crash when dragging Firefox Tab) with KDE.

**Comment by slang800** [comment] 2015-03-23 23:30
Just found this on Ubuntu-GNOME 14.10 with Atom v0.187

**Comment by ptihiy** [comment] 2015-04-03 09:54
Same for me, Ubuntu 14.10 with Atom v0.187, every time.

**Comment by ptihiy** [comment] 2015-04-03 14:25
Moreover, it also breaks Firefox as well, if you try to drag just one tab from Firefox over Atom and then place it back, you'll see, that it will disappear also, and break tabs order.

**Comment by mattcollier** [comment] 2015-04-08 00:32
Debian Jessie x64 with iceweasel.  Atom just disappears if iceweasel tab is dragged over atom window.  This is in the console:
```
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 618 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by johnfraney** [comment] 2015-04-08 18:10
I've found that the crash happens when dragging even just an image. (Atom v0.190.0, Arch x64.)

**Comment by johnfraney** [comment] 2015-04-23 13:40
I can confirm that this issue is still present in 0.194.0 (Arch x64, Firefox Developer Edition 39.0a2).

**Comment by espace3d** [comment] 2015-04-26 06:41
what is the solution to prevent that ?

**Comment by JakobBerg** [comment] 2015-04-29 22:42
getting same crash the moment I hover a window from firefox over Atom User Interface

## running atom 
```
:~$ atom --safe
:~$ [8179:0429/182252:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 139ms
[8211:0429/182252:INFO:renderer_main.cc(212)] Renderer process started
[8179:0429/182253:INFO:CONSOLE(59)] "Window load time: 798ms", source: file:///opt/atom/resources/app.asar/static/index.js (59)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 586 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

```


## Command History

```
     -0:19.2 ready (#document)
     -0:19.0 pane:item-added (atom-pane.pane.active)
     -0:19.0 pane-container:active-pane-item-changed (atom-pane-container.panes)
     -0:18.9 editor:attached (atom-text-editor.editor.is-focused)
     -0:18.9 pane:active-item-changed (atom-pane.pane.active)
     -0:18.9 uri-opened (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.8 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 bug-report:open (atom-text-editor.editor.is-focused)
```

## Versions

* **Atom:**       0.194.0
* **Atom-Shell:** 0.22.3
* **OS:**         linux 3.16.0-33-generic
    * Ubuntu 14.04.2 LTS 64 bit (standard setup with unity)
* **Misc**
    * apm  0.161.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.6
    * git 1.9.1
    * firefox 37.0.2

---

**Comment by mauricioszabo** [comment] 2015-06-23 18:54
Same error with Enlightenment desktop environment.

**Comment by croaker000** [comment] 2015-07-01 09:43
My problem seems to be related to this. Atom seems to be receiving and acting on drag signals for anything that's dragged over it despite Atom not being the target of the drag and drop. 

Using Ubuntu. 

For example. If I have Atom open in the middle of the screen with an open file, open a Nautilus window on left and another Nautilus window on the right and then drag a file from the left to the right nautilus window, the open file in Atom closes. In a similar setup with an Archive Manager window on the left, Archive Manager traps an error reporting "Destination Folder 'null' does not exist".

Atom needs to ignore stuff dragged over it if Atom is not the target.

**Comment by muchweb** [comment] 2015-07-30 10:16
This still happens on version `1.0.3`. Dragging any Gecko tabs will crash Atom instantly. It can be reproduced with Firefox, PaleMoon and Thunderbird.

```
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 637 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by croaker000** [comment] 2015-07-30 11:45
In my experience (Ubuntu), dragging any drop candidate from anything to anywhere that passes over an open Atom window will cause the drag/drop to fail with varying fallout depending on how that failure is handled by the parent program. I've resorted to either minimising Atom or moving the source and target windows so that the drag does not pass over an Atom window.

**Comment by mnquintana** [comment] 2015-07-30 12:16
@zcbenz Is this still an issue with latest Electron?

**Comment by muchweb** [comment] 2015-07-30 12:24
>In my experience (Ubuntu), dragging any drop candidate from anything to anywhere that passes over an open Atom window will cause the drag/drop to fail

I am only experiencing crashes with Firefox/PaleMoon/Thunderbird. Any other drag&drop, including text, files and tabs from other programs work fine.

**Comment by croaker000** [comment] 2015-07-30 12:40
>> I am only experiencing crashes with Firefox/PaleMoon/Thunderbird.
Archive Manager (file-roller)? Nautilus? They're on my list...

**Comment by muchweb** [comment] 2015-07-30 13:46
>Archive Manager (file-roller)? Nautilus? They're on my list...

@croaker000, you are right, Archive Manager (`file-roller`) caused crash too. Although Thunar file manager worked fine.

**Comment by hookenz** [comment] 2015-08-05 23:37
I have the same issue on 14.04

**Comment by csouth** [comment] 2015-08-07 14:15
@mnquintana  I can confirm that the issue still exists with 0.30.2 of Electron. I can reproduce by just running Electron by itself and dragging a tab over it.

```
christian@laptop:~$ electron
[14195:0807/101135:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[14224:0807/101135:INFO:renderer_main.cc(200)] Renderer process started
[14213:0807/101135:ERROR:gles2_cmd_decoder.cc(11539)] [GroupMarkerNotSet(crbug.com/242999)!:D06658A9FA1A0000]GL ERROR :GL_INVALID_OPERATION : glTexStorage2DEXT: <- error from previous GL command
```
Then I drag a tab and the error occurs.
```
The program 'electron' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 390 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by mnquintana** [comment] 2015-08-07 14:19
@csouth Thanks for the update! Though that's a bummer :confused: - marking this as blocked on https://github.com/atom/electron/issues/2204 then.

**Comment by Haris1112** [comment] 2015-10-03 04:28
I'm having the same problem: Arch + GNOME.

Hovering a Firefox tab over Atom makes it crash! (instantly)

**Comment by forivall** [comment] 2015-10-03 07:00
Same here; also, dragging files from Dolphin (KDE SC file manager) crashes atom. It's likely the same issue. Manjaro (Arch based) + KDE.

**Comment by KeitIG** [comment] 2015-10-04 15:28
Fixed in atom/brightray#149 so

**Comment by 50Wliu** [comment] 2015-10-04 15:53
> Fixed in atom/brightray#149 so

Once @zcbenz releases a new version of Electron I'll remove the blocked tag.  Hopefully we can get it in #8779 as well :smile:.

**Comment by crsaracco** [comment] 2015-10-05 17:42
Same problem on Arch + Cinnamon.

**Comment by 50Wliu** [comment] 2015-10-05 19:20
This will be fixed when #8779 is merged.

**Comment by shantee** [comment] 2015-10-13 16:07
Same bug on Linux Mint 17.2

**Closed** 2015-10-16 21:59 UTC
Labels: bug, crash, electron, linux

**Comment by cmtonkinson** [comment] 2015-10-30 12:24
Just updated this morning and I still experience this error. Firefox 41.0.2, Atom 1.1.0, Node 4.2.1, Linux 4.2.5, NPM 3.3.9.

En/Disabling hardware acceleration does not make a difference.

```
[6042:1030/081415:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 191ms
[6100:1030/081416:ERROR:sandbox_linux.cc(340)] InitializeSandbox() called with multiple threads in process gpu-process
[6042:1030/081416:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081416:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081416:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081416:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6119:1030/081416:INFO:renderer_main.cc(200)] Renderer process started
[6042:1030/081416:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081416:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081416:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081416:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6130:1030/081416:INFO:renderer_main.cc(200)] Renderer process started
[6042:1030/081417:INFO:CONSOLE(46)] "Window load time: 1022ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (46)
[6042:1030/081417:INFO:CONSOLE(46)] "Window load time: 942ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (46)
[6042:1030/081417:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081417:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081417:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081417:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6100:1030/081418:ERROR:gles2_cmd_decoder.cc(11539)] [GroupMarkerNotSet(crbug.com/242999)!:D03810D4C5280000]GL ERROR :GL_INVALID_OPERATION : glTexStorage2DEXT: <- error from previous GL command
[6100:1030/081418:ERROR:gles2_cmd_decoder.cc(11539)] [GroupMarkerNotSet(crbug.com/242999)!:D0047CD4C5280000]GL ERROR :GL_INVALID_OPERATION : glTexStorage2DEXT: <- error from previous GL command
[6042:1030/081418:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081418:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081418:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[6042:1030/081418:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 928 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by mnquintana** [comment] 2015-10-30 12:27
@cmtonkinson I think this was fixed for Atom 1.2.0, not 1.1.0 - feel free to try out the 1.2.0 beta if you want to test this fix out for yourself!

**Comment by cmtonkinson** [comment] 2015-10-30 12:32
Not to be dense, but was the [release post] incorrect then?

Under the heading **Upgrade to Electron 0.34.x** near the bottom, it reads:

> This brings Atom up to the latest version of Electron and fixes a couple of [pretty][pretty] [bad][bad], long-standing bugs.

Note that "pretty" links to _this_ issue (#3593).

[release post]: http://blog.atom.io/2015/10/29/atom-1-1-is-out.html
[pretty]: https://github.com/atom/atom/issues/3593
[bad]: https://github.com/atom/atom/issues/7061

**Comment by xgdgsc** [comment] 2015-10-30 12:36
@cmtonkinson That' s in the "Available now in Atom 1.2.0-beta" section

**Comment by cmtonkinson** [comment] 2015-10-30 12:40
*D'OH!*

**Obviously** that's my bad. Apologies for the noise.

**Comment by carbsrule** [comment] 2015-12-18 00:10
Was experiencing this all the time dragging Iceweasel tabs (on Debian 8.1 with Cinnamon).
Upgraded from v1.1.0 to 1.3.2 and the problem seems to have gone away. Huzzah!
