### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by oblivionnewtonjohn** [atom/atom#8413] opened 2015-08-17 20:03 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Invalid string length

```
At C:\Users\SPCRAWFORD\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\pathwatcher\lib\file.js:310

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (C:\Users\SPCRAWFORD\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\pathwatcher\lib\file.js:310:43)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:163:7)
    at _stream_readable.js:891:16
    at process._tickCallback (node.js:357:13)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
language-log, v0.5.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-08-18 15:57
Thanks for the report. This seems to be a duplicate of https://github.com/atom/atom/issues/7417.

**Closed by izuzak** 2015-08-18 15:57 UTC
Labels: uncaught-exception

**Comment by PhilippePlagnol** [comment] 2016-02-19 15:14
RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (C:\Users\Philippe\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\pathwatcher\lib\file.js:317:38)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
