### ISSUE TITLE
Atom on ARM architecture

### ISSUE THREAD

**Issue by henrywright** [atom/atom#4823] opened 2015-01-01 22:37 UTC
My laptop runs Ubuntu Linux and uses a Samsung Exynos processor (an ARM chip). Is Atom available for me?

Thanks in advance

**Comment by lee-dohm** [comment] 2015-01-02 00:42
Essentially, I believe this is a duplicate of #3783 in that fixing it will (depending on how you define your Issue) fix this one.

**Comment by henrywright** [comment] 2015-01-02 00:48
@lee-dohm seems that way. It'd be great if Atom was runnable on non-Intel Chromebooks (like mine)

**Comment by kevinsawicki** [comment] 2015-01-06 18:00
Closing as duplicate of https://github.com/atom/atom/issues/3783

**Closed by kevinsawicki** 2015-01-06 18:00 UTC
