### ISSUE TITLE
Spell correction

### ISSUE THREAD

**Issue by patem** [atom/atom#7365] opened 2015-06-22 10:09 UTC
*Note: This is less an issue in the common sence than an suggestion to improve the ease of use.*

Software | Version
------------ | -------------
Atom | 0.210.0
Operating system | MS Windows 7 Enterprise
Google Chrome | v43.0.2357.124 m

To use the spell correction you've to set the cursor to the word (or mark it). Simply right-clicking on the word and click on "Correct Spelling" won't open the overlay menu.

**Comment by mnquintana** [comment] 2015-06-22 11:26
Would you mind moving this to https://github.com/atom/spell-check?

**Comment by izuzak** [comment] 2015-06-22 11:29
It's actually a duplicate of https://github.com/atom/spell-check/issues/32, I believe.

**Closed by izuzak** 2015-06-22 11:29 UTC
