### ISSUE TITLE
Minor rendering issue in editor where boxes are drawn around the code

### ISSUE THREAD

**Issue by mtimofiiv** [atom/atom#14318] opened 2017-04-28 10:11 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The div `atom-text-editor .lines` contains many children divs that contain the actual lines of the code being viewed in the editor. Strangely enough, I am seeing funky background colour behaviour here. Here's a screenshot:

<img width="1067" alt="screen shot 2017-04-28 at 11 41 32" src="https://cloud.githubusercontent.com/assets/428948/25524047/2e113748-2c09-11e7-901f-e3b456dd30ae.png">

So I went into the dev tools and checked out what is going on. Turns out each of the children divs's background colour only stretches to a bit past the line where the last character of code in that block is:

<img width="1083" alt="screen shot 2017-04-28 at 11 49 26" src="https://cloud.githubusercontent.com/assets/428948/25524100/6813db4e-2c09-11e7-8448-11f6036c09bf.png">

Now, this is the Seti UI theme and One Dark syntax, but I see it with any combination of ui/syntax themes. Here is the same issue, but in Safe Mode:

<img width="909" alt="screen shot 2017-04-28 at 11 58 46" src="https://cloud.githubusercontent.com/assets/428948/25524246/1e7ffd36-2c0a-11e7-8007-20d95d80a133.png">

Now, here's the interesting part - I have tracked down where this actually happens. The culprit is this CSS rule that overwrites the background for each of those containers of code lines:

<img width="1203" alt="screen shot 2017-04-28 at 12 00 56" src="https://cloud.githubusercontent.com/assets/428948/25524383/a6b4973e-2c0a-11e7-9020-f7950f13b923.png">

Before you say "@mtimofiiv, this is a theme problem, go ask them about it", **note that it does happen with all themes** and that **toggling this CSS rule on/off in the dev tools actually fixes the problem**, but only for that one block and only temporarily.

Unless I am wrong, it seems like a rendering issue.

### Steps to Reproduce

I am not sure what I am doing that perhaps others are not. I have a stock install of Atom which is up to date and even in Safe Mode I am seeing this, so it's not a plugin problem as far as I'm aware. I have not modded my config in any crazy way.

**Expected behavior:**

I expect the background colour of the code blocks to not have jagged box edges.

**Actual behavior:**

See above

**Reproduces how often:**

Always.

### Versions

Here is the output of `atom --version`:

```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

And `apm --version`:

```
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.11.0
```

My OS is macOS Sierra 10.12.3.

**Comment by 50Wliu** [comment] 2017-04-28 15:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12634. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-04-28 15:54 UTC
