### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by Izmargad** [atom/atom#15986] opened 2017-10-25 06:09 UTC
[Enter steps to reproduce:]

1. ... Selected a file to rename by adding .html as file-type extension.
2. ... Then this Uncaught TypeError 'error' showed up

**Atom**: 1.21.1 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At path.js:7

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at MoveDialog.module.exports.MoveDialog.onConfirm (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/tree-view/lib/move-dialog.js:41:36)
    at HTMLDivElement.Dialog.atom.commands.add.core:confirm (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/tree-view/lib/dialog.js:81:32)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:27.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:41.4.0 tree-view:move (span.name.icon.html5-icon.medium-orange)
     -0:36.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ide-ui 0.5.2 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.13 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-typescript 0.6.2 
intentions 1.1.5 
js-hyperclick 1.11.1 
json-schema 0.1.15 
language-babel 2.76.1 
less-than-slash 0.17.0 
lines 0.13.1 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-htmlhint 1.3.4 
linter-jshint 3.1.6 
linter-jsonlint 1.3.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-linter 2.1.1 
multi-cursor 2.1.5 
open-in-browser 0.5.2 
pigments 0.40.2 
todo-show 2.1.0 
```

**Comment by rsese** [comment] 2017-10-25 18:13
Thanks for taking the time to contribute!

Based on the stack trace, I think this is a duplicate of https://github.com/atom/tree-view/issues/700 so you can subscribe there for updates if you'd like.

---

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/700. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-25 18:13 UTC
