### ISSUE TITLE
1.60. System Faults/Crashes on Launch of Atom 

### ISSUE THREAD

**Issue by csharpee** [atom/atom#25650] opened 2022-10-09 22:25 UTC
```HTTP request sent, awaiting response... 204 No Content```

```[24330:1009/182824.494727:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye```

I tested on Ubuntu 22.04 with two different atom versions.

**Comment by icecream17** [comment] 2022-10-11 13:40
duplicate of https://github.com/atom/atom/issues/23036?

**Comment by csharpee** [comment] 2022-10-11 19:33
potentially, I have moved forward with a OG IDE called "Geany". Yall, had a cool name.

**Closed** 2022-10-11 19:33 UTC
