### ISSUE TITLE
Uncaught Error: error: 126/\?\~\AppData\Local\atom\app-1.42.0\resources\app.asar.unpacked\node_mo...

### ISSUE THREAD

**Issue by CaioLindao** [atom/atom#20261] opened 2019-12-20 22:07 UTC
[Enter steps to reproduce:]

1. Open atom normally
2. Press any key and get the error, except for the mouse ones

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 126\\?\C:\Users\caiod\AppData\Local\atom\app-1.42.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: error: 126\\?\C:\Users\caiod\AppData\Local\atom\app-1.42.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:1:728962)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:14:2779770)
    at get_manager (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:14:2779872)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:14:2779998)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:14:1083872)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1249484)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1247469)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:284591)
```

### Commands

```
  2x -1:58.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
emmet 2.4.3 
v-bootstrap4 0.2.2 
```

**Comment by sadick254** [comment] 2020-09-16 15:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-16 15:22 UTC
