### ISSUE TITLE
New Atom windows always opens on the first Desktop (Mac OS)

### ISSUE THREAD

**Issue by bbugh** [atom/atom#15967] opened 2017-10-22 16:54 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:

(I spent some time looking for existing issues but "atom" "mac" "desktop" and "space" are all pretty high match words. Sorry if this is a duplicate.)

### Description

Atom moves to and load on the first Desktop regardless of which one the user is on.

![image](https://user-images.githubusercontent.com/438465/31863848-377a61ba-b719-11e7-99e1-e7469e51b099.png)

If I start Atom here (either command line or with Spotlight) it will force me to the first desktop and open Atom. 

This happens whether Atom is freshly launched (no windows open) or if there are already existing windows open, even if they're on other desktops.

### Steps to Reproduce

1. Switch to a different Desktop on Mac
2. Open Atom
3. Observe

**Expected behavior:** Atom will behave like a typical Mac application and open on the current Desktop.

**Actual behavior:** Atom opens on and forces the user to the first Desktop.

**Reproduces how often:** 100%

### Versions

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.1

macOS 10.12.6 (16G29)

**Comment by rsese** [comment] 2017-10-23 19:17
Thanks for taking the time to contribute!

> (I spent some time looking for existing issues but "atom" "mac" "desktop" and "space" are all pretty high match words. Sorry if this is a duplicate.)

No problem, we have quite a few issues so there's a lot to go through as well, thanks for taking the time to search :v:

I think this is a duplicate of https://github.com/atom/atom/issues/11610 and the more general issue Lee describes in https://github.com/atom/atom/issues/11610#issuecomment-215265986 so you can subscribe there if you'd like.

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/11610. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-23 19:17 UTC
