### ISSUE TITLE
Scrollbars don't disappear on macOS

### ISSUE THREAD

**Issue by simurai** [atom/atom#18882] opened 2019-02-20 08:41 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Scrollbars don't disappear after scrolling stopped.

### Steps to Reproduce

1. Make sure that in macOS's "General" settings, the "Show scroll bars" is set to "Automatically" or "When scrolling".
2. Open Atom's "About" page
3. Resize the window so that a scrollbar appears

**Expected behavior:** 

The scrollbar disappears when not scrolling.

**Actual behavior:**

The scrollbar stays visible.

**Reproduces how often:**

100%. But not in all locations. For example the editor and tree-view is fine.

![scrollbar](https://user-images.githubusercontent.com/378023/53077685-ebf8ca00-3535-11e9-9376-d89331536821.gif)

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
macOS: Mojave 10.14.2 (18C54)

Atom    : 1.37.0-dev-41a180b9d
Electron: 3.1.3
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.37.0-dev-41a180b9d
python 2.7.10
git 2.20.1
```

### Additional Information

Something interesting: It also happens in the DevTools. Which makes me think it's Electron 3/Chromium related?

![scrollbar-devtools](https://user-images.githubusercontent.com/378023/53077902-67f31200-3536-11e9-836e-02678a1be57d.gif)

**Comment by lee-dohm** [comment] 2019-02-26 21:09
Possibly due to Electron 3? If we can reproduce on v2, we should attack this now, otherwise save for Electron v3 todo list.

**Comment by simurai** [comment] 2019-02-26 23:20
> Possibly due to Electron 3?

👍 Yeah, pretty sure it's Electron 3 related. Current Beta (Electron 2.0.16) is fine:

![about](https://user-images.githubusercontent.com/378023/53453770-6d85b600-3a68-11e9-81f8-5ad6c75cb46d.gif)

**Comment by lee-dohm** [comment] 2019-02-27 00:33
Awesome, thanks for the quick confirmation @simurai :bow:

**Comment by rsese** [comment] 2019-02-27 23:56
Also looks good on the latest nightly release that dropped down back to Electron 2:

![scrollbars-electron-2](https://user-images.githubusercontent.com/734194/53531458-e0b71880-3ab8-11e9-84ed-fbac16bd4277.gif)

**Comment by rafeca** [comment] 2019-05-15 10:02
@as-cii and me have tried to reproduce against the latest electron v3 version (the one we're currently working in https://github.com/atom/atom/pull/18916), and this seems to be fixed.

I'm gonna close it for now, but we can reopen if it re-appears.

**Closed** 2019-05-15 10:03 UTC
Labels: bug, electron-3, mac, triaged
