### ISSUE TITLE
binary payload inside shell script will break the whole file's syntax highlighting

### ISSUE THREAD

**Issue by TurnOffNOD** [atom/atom#12161] opened 2016-07-13 07:01 UTC
I opened a shell script (bash script), at the tail of the file, there is binary payload (An archive). However, the shell script at head of the script will also lose syntas highlighting.

Screenshot:
no syntax highlight of bash script
<img width="1067" alt="screen shot 2016-07-13 at 14 55 32" src="https://cloud.githubusercontent.com/assets/2140029/16794365/ff842fda-4909-11e6-9d51-13c34b131695.png">

binary payload at tail:
<img width="1065" alt="screen shot 2016-07-13 at 14 55 52" src="https://cloud.githubusercontent.com/assets/2140029/16794380/1a69547e-490a-11e6-8412-9b57d36d6feb.png">

As we can see, the minimap at right side and the main window together show that the whole file has no syntax highlighting.

My atom version is 1.8.0 stable, on Mac OS X 10.11.5, all the installed packages are latest:
<img width="679" alt="screen shot 2016-07-13 at 14 57 42" src="https://cloud.githubusercontent.com/assets/2140029/16794482/93b90ac2-490a-11e6-9e9f-90ff6307c41d.png">
<img width="603" alt="screen shot 2016-07-13 at 15 00 28" src="https://cloud.githubusercontent.com/assets/2140029/16794490/9b29247c-490a-11e6-9ec4-ecbfa4337ad4.png">

**Comment by thomasjo** [comment] 2016-07-14 07:41
This is basically a duplicate of https://github.com/atom/atom/issues/307. I'm assuming the binary payload is quite large in terms of bytes — Atom disables syntax highlighting of really large files due to performance issues.

**Closed by thomasjo** 2016-07-14 07:41 UTC

**Comment by TurnOffNOD** [comment] 2016-07-14 07:52
@thomasjo 
I am sure the syntax highlighting of the script part was quite good before, and I am sure that it's the same script file with same binary payload.

At that time, the syntax high lighting is only applied to script part, and the binary payload part has no syntax highlighting.

After some time, I opened the file again and I found the whole syntax high lighting was lost.

**Comment by thomasjo** [comment] 2016-07-14 08:10
Then you are going to have to fill in the [issue template](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md) (that we request you fill in when opening new issues), and provide the necessary information.

Additionally, if you could share a file that reliably reproduces your problem that would be great.

> I am sure the syntax highlighting of the script part was quite good before, and I am sure that it's the same script file with same binary payload.
Have you changed the file recently? Even if you only added a single character to the document, you might have pushed it above the file size threshold and thus disabling syntax highlighting. The size of the file is what matters, not the content therein.

I'll re-open the issue once the requested information is provided.

**Comment by TurnOffNOD** [comment] 2016-07-14 08:58
@thomasjo 
Just now I did a test, I removed about 500 lines of the binary payload part in the file, and the syntax highlighting become good again.
But I am sure that I didn't modified the file. The size of the file is not changed. 


I don't have a log for the time when it's good. And I can't remember which packages were installed or upgraded between my last good syntax-highlighting and now broken syntax-highlighting.

Will the issue template be useful at this situation?

**Comment by thomasjo** [comment] 2016-07-14 09:00
The most crucial information from the issue template is whether or not you're able to reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode).

**Comment by TurnOffNOD** [comment] 2016-07-14 09:30
@thomasjo 
OK

I am using atom on Mac OS X 10.11.5. 
Here is my issue template:
* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?

Yes, and also in the safe mode, the syntax highlighting will be back after remove 500 lines.



* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?

The latest atom, the latest packages.


* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?

After the original size file lost syntax highlighting, I completely uninstall my atom and ~/.atom directory, install a fresh one, and opened the file with no extra packages installed. The syntax highlighting of the file is still lost.

**Comment by thomasjo** [comment] 2016-07-14 11:59
@atom/feedback Has anything changed somewhat recently with regards to large file handling? If the referenced file hasn't changed, but highlighting went away, I can also assume the large size limit was tuned (or something similar).

**Comment by maxbrunsfeld** [comment] 2016-07-14 18:05
> Has anything changed somewhat recently with regards to large file handling?

I don't think so.
