### ISSUE TITLE
Under Windows 7 editor crashes if started in Atom directory.

### ISSUE THREAD

**Issue by dmc7337** [atom/atom#3848] opened 2014-10-16 02:56 UTC
Running under Windows 7 if i start the editor in the Atom (0.136.0) install directory it gives "The Editor has crashed window". There is an exception logged in the console output:
events.js:82
   throw er; // Unhandled 'error' event

All works OK if started in any other directory.

Is also odd that if produces console output if started in the Atom directory but nothing if started in other directories. Also failed with previous version.

**Comment by 50Wliu** [comment] 2015-05-11 13:41
@dmc7337 can you still reproduce this (in addition, are you using Chocolatey or the new Squirrel installer)?

**Comment by batjko** [comment] 2015-05-11 13:56
"still" as in "using the latest version", btw.

**Comment by kevinsawicki** [comment] 2015-07-27 22:57
Closing this out since it hasn't been reported using the installer or on Atom 1.0+

**Closed by kevinsawicki** 2015-07-27 22:57 UTC
Labels: bug, windows
