### ISSUE TITLE
Can't upgrade from non-admin account on OSX Yosemite

### ISSUE THREAD

**Issue by ghlecl** [atom/atom#7389] opened 2015-06-23 18:45 UTC
I setup my laptop so that my day to day work is not in an admin account.  For most software, when comes upgrade time, all I have to do is enter the admin account login and password when prompted and I can proceed.  This is not the case with Atom.  Everytime I want to upgrade, I have to manually download Atom and replace the executable.

I have tried completely unsintalling Atom and everything related to Atom in ~, ~/Library, /Library, etc, then rebooting my machine (twice) and then installing Atom to solve.  That did not change the situation.

**Comment by mnquintana** [comment] 2015-06-23 18:55
Thanks for the report! This seems like a duplicate of https://github.com/atom/atom/issues/2860 – does that about cover what you're experiencing?

**Comment by ghlecl** [comment] 2015-06-23 19:28
That is exactly the issue.  Sorry.  When searching, I did not come across it.  I found the ShipIt problem over and over, but that never solved it for me.  Thought I was going crazy, so decided to report my problem.  I guess we can close this one and +1 me on the other issue.  Again, sorry.

**Closed** 2015-06-23 19:30 UTC
Labels: more-information-needed
