### ISSUE TITLE
Atom Editor Bug Report For @ Symbol

### ISSUE THREAD

**Issue by atak946** [atom/atom#10370] opened 2016-01-11 09:26 UTC
Hi,
we can not write ' @ ' symbol in this editor; [CONTROL] + [ALT] + [Q] = @
any one can help us?

**Comment by mnquintana** [comment] 2016-01-11 13:49
What keyboard layout are you using?

**Comment by lee-dohm** [comment] 2016-01-12 01:00
This is very likely a duplicate of atom/atom-keymap#37.

**Comment by kaosterra** [comment] 2016-02-23 18:57
I have the same problem, my keyboard is using latinamerican layout (Colombia - Latinamerica)

**Comment by lee-dohm** [comment] 2016-02-23 19:37
@atak946 Can you confirm that you're using a non-English keyboard layout?

**Comment by Ben3eeE** [comment] 2016-12-15 14:42
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/10370#issuecomment-187862231. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2016-12-15 14:42 UTC
Labels: more-information-needed
