### ISSUE TITLE
Package doesn't work correctly after update when something new is added to atom.config

### ISSUE THREAD

**Issue by burodepeper** [atom/atom#11668] opened 2016-05-02 09:06 UTC
### Description

I updated my package [language-markdown](https://github.com/burodepeper/language-markdown) yesterday and I received the following issue report: https://github.com/burodepeper/language-markdown/issues/108

I haven't heard back from @MGallow yet, but I'm relatively certain that the issue is related to what I've mentioned in my initial response to the issue report. **The underlying issue** (I think): Whenever I add a new option to `atom.config` in an update, this causes the package to malfunction when it is updated.

I haven't experienced this issue on my development machine (because I think the new config item is already created during development), but I have seen it multiple times when updating on my secondary computer. Reloading Atom fixes the issue.
### Prerequisites
- I'm sure I can technically reproduce this, but it's quite the hassle. Each reproduction gives only a single opportunity to look at what's wrong. I'm also relatively certain (at least I hope so) my own code isn't the cause of these issues. See https://github.com/burodepeper/language-markdown/blob/master/lib/main.coffee (L22-26 for config, L50-51 for subscriptions, and L166-180 for execution)
- Atom v1.7.3 (detected on earlier versions too) on Mac OS X 10.11.4
- Haven't found any relevant issues; search terms are rather generic.

**Comment by burodepeper** [comment] 2016-05-02 12:53
Confirmed by @MGallow that reloading Atom resolves the issue, but I'm afraid something like this might remain unresolved for a lot of users.

**Comment by lee-dohm** [comment] 2016-05-03 00:12
@amytruong Can you see if you can figure out some repro steps for this? Let me know if you need help.

**Comment by burodepeper** [comment] 2016-05-03 10:05
Updated `language-markdown` to v0.13.0 on my secondary machine with the dev-tools open (not in dev-mode). As expected, this reproduces the problem. I checked the value of the new key in the config before and after the update via

```js
atom.config.get("language-markdown.emphasisShortcuts");
```

which should return `undefined` before, and `true` after installation (the default as defined by me in the update). It returns `undefined` in both scenarios. Apparently, new entries to the config are not added after updating and (re-)activating the package. The curious thing is that functionality that used to work just fine, and weren't affected by the update, starts to produce unexpected behavior too.

For example, my package has the option to append new list items, and after a faulty update, new list items are created, but with a double list-item marker.

**Normal behavior**: you have an item `1. One`, press enter, and new line contains `2. ` **Faulty behaviour** produces `2. 2. ` on the new line. Apparently as if the code is executed twice. Toggling a task also apparently fails, possibly because it's toggled twice, and negating itself. Indenting a list-item (by pressing tab, with your cursor anywhere on the line) doesn't work at all though.

I've looked through the Atom source for further clues, but I'm too unfamiliar with it. Hope this helps though.

**Comment by robbawebba** [comment] 2017-06-15 21:43
I know this issue has been stale for over a yer, but I am experiencing the same issue with my own package [night-light](https://github.com/robbawebba/night-light). The issue is that part of my package settings in `config.cson` disappear (two nested objects), while the rest of the settings remain untouched. Here's my `config.cson` file after the update. The data underneath the `day` and `night` keys disappeared:
```
"night-light":
    day: {}
    location:
      auto: false
      lat: 40.7772437
      lng: -74.38806989999999
    night: {}
    schedule:
      end: "5:26"
      start: "20:31"
```
One strange thing I'm noticing is that brackets appeared next to each key and those weren't there before. 

Here is the json configuration I'm using to create my package settings:

```
{
	"night": {
		"title": "Nighttime Appearance",
		"type": "object",
		"order": 2,
		"properties": {
			"ui": {
				"title": "UI Theme",
				"description": "UI theme to use at night.",
				"type": "string",
				"default": "one-dark-ui",
				"enum": [],
				"order": 1
			},
			"syntax": {
				"title": "Syntax Theme",
				"description": "Syntax theme to use at night.",
				"type": "string",
				"default": "one-dark-syntax",
				"enum": [],
				"order": 2
			}
		}
	},
	"day": {
		"title": "Daytime Appearance",
		"type": "object",
		"order": 1,
		"properties": {
			"ui": {
				"title": "UI Theme",
				"description": "UI theme to use during the day.",
				"type": "string",
				"default": "one-light-ui",
				"pattern": "/.*-ui$/",
				"enum": [],
				"order": 1
			},
			"syntax": {
				"title": "Syntax Theme",
				"description": "Syntax theme to use during the day.",
				"type": "string",
				"default": "one-light-syntax",
				"enum": [],
				"order": 2
			}
		}
	},
	"schedule": {
		"title": "Schedule",
		"type": "object",
		"order": 3,
		"properties": {
			"auto": {
				"title": "Auto-update Sunset and Sunrise",
				"description": "Automatically update the scheduled sunrise/sunset times daily. If this setting is disabled, then the themes will change based on the start and end times below.",
				"default": true,
				"type": "boolean",
				"order": 1
			},
			"start": {
				"title": "Manual Sunset",
				"description": "Night mode begins at this time. Must follow HH:MM format.",
				"type": "string",
				"pattern": "/.*:.*/",
				"default": "18:00",
				"order": 2
			},
			"end": {
				"title": "Manual Sunrise",
				"description": "Night mode ends at this time. Must follow HH:MM format.",
				"type": "string",
				"pattern": "/.*:.*/",
				"default": "05:00",
				"order": 3
			}
		}
	},
	"location": {
		"title": "Location",
		"type": "object",
		"order": 4,
		"properties": {
			"auto": {
				"title": "Auto-update Location",
				"description": "Automatically refresh the latitute and longitude based on your location. If this is disabled, then please update your latitude and longitude below. For best results, please use a location in the same time zone as this computer.",
				"type": "boolean",
				"order": 1,
				"default": true
			},
			"lat": {
				"title": "Latitude",
				"type": "number",
				"order": 2,
				"default": 40.714623
			},
			"lng": {
				"title": "Longitude",
				"type": "number",
				"order": 3,
				"default": -74.006605
			}
		}
	}
}
```

@burodepeper Have you had any luck since you last commented on this issue?

**Comment by burodepeper** [comment] 2017-06-15 22:22
@robbawebba My issue got 'fixed' with the update that prompted the user to restart Atom after a package update. The actual problem that caused my issue was that the old version of the package didn't to seem to unload, and well, restarting Atom resets whatever packages are loaded. So that fixed it.

I installed your package --neat idea by the way-- and it seems that whenever my own settings match the package's defaults in lib/config.json, then they are omitted from Atom's config.cson. So, if I set the night ui theme to one-dark-ui, it gets omitted. If I set it to anything else, it gets saved to my config.cson. Anyway, it seems to pick the correct themes for (after a quick test). Are you sure there's actually something going wrong?

On a side note, after a clean install, either packageDayThemesChange() or packageNightThemesChange() throws an error the first time the package is run. Forgot to copy the error, but I believe newTheme was undefined.

**Comment by robbawebba** [comment] 2017-06-15 23:06
@burodepeper Ahh, I see what you mean about the settings being omitted from the `config.cson` file when they match the default value. That was a bad way to demonstrate my issue. Before my update, my `config.cson` had the following values:
```
"night-light":
    day: 
      syntax:"solarized-light-syntax"
    location:
      auto: false
      lat: 40.7772437
      lng: -74.38806989999999
    night:
      syntax: 'solarized-dark-syntax'
    schedule:
      end: "5:26"
      start: "20:31"
```
After the update, the `night` and `day` settings did not persist unfortunately. This has happened every time I've updated my package (only twice lol). Do you know how I can simulate a package update? maybe manually install the previous version and have Atom tell me there's an update available? 

And thanks for letting me know about that other error! I haven't seen that error before, but I'll look into it.

**Comment by burodepeper** [comment] 2017-06-15 23:25
I have no idea how to easily simulate a package update. Manually installing an older version would do the trick probably. However, maybe the following might help.

When you call `atom.config.set("night-light.day.syntax", "invalid")` and set a value that doesn't exist in the enum from your config, then that key is removed from config.cson. It doesn't retain the old value.

After an update, the config.cson might get validated (or whatever), can't find the values in your package's config (because possibly the enum isn't populated yet, because it relies on the themes being loaded _before_ your package is initialized), and then invalidates and removes them from the config.cson.

No idea if that is exactly what happens, but it's the only thing I can think of at the moment that could delete stuff from config.cson.

**Comment by robbawebba** [comment] 2017-06-16 00:45
That makes a lot of sense! Thank you for the insight 😄 I'm unsure if that's exactly what's happening either, but it makes sense to me lol I'll begin working on an alternative route to persist the user's settings across an update. Thanks again for your help!

**Comment by burodepeper** [comment] 2017-06-16 00:59
Good luck!

**Comment by 50Wliu** [comment] 2017-06-16 01:14
It looks like the original issue has been fixed by the "Restart" prompt, so I'm going to close this issue.  @robbawebba if you think there's another bug present, feel free to open another issue :smile:.

**Closed by 50Wliu** 2017-06-16 01:14 UTC
Labels: bug, needs-reproduction
