### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'undefined' that has already been destroyed

### ISSUE THREAD

**Issue by youngjuning** [atom/atom#16108] opened 2017-11-06 02:29 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0-beta2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Adding a pane item with URI 'undefined' that has already been destroyed

```
At C:\Users\10037\AppData\Local\atom\app-1.22.0-beta2\resources\app\src\pane.js:608

Error: Adding a pane item with URI 'undefined' that has already been destroyed
    at Pane.addItem (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/src/pane.js:608:19)
    at Pane.moveItemToPane (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/src/pane.js:731:23)
    at Object.end (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/node_modules/tabs/lib/layout.js:63:22)
    at HTMLLIElement.TabView.element.ondragend (~/AppData/Local/atom/app-1.22.0-beta2/resources/app/node_modules/tabs/lib/tab-view.js:62:29)
```

### Commands

```
     -1:24 markdown-writer:indent-list-line (input.hidden-input)
     -1:24 docblockr:parse-tab (input.hidden-input)
     -1:24 snippets:next-tab-stop (input.hidden-input)
     -1:24 snippets:expand (input.hidden-input)
     -1:24 editor:indent (input.hidden-input)
     -1:21.1.0 source-preview:toggle (input.hidden-input)
     -1:15.3.0 tree-view:toggle (input.hidden-input)
     -1:13.8.0 about:view-release-notes (input.hidden-input)
     -0:42.4.0 find-and-replace:show (input.hidden-input)
     -0:40.2.0 core:confirm (input.hidden-input)
     -0:37 core:backspace (input.hidden-input)
     -0:36.4.0 core:save (input.hidden-input)
     -0:31.2.0 window:toggle-full-screen (input.hidden-input)
     -0:27.4.0 source-preview:toggle (input.hidden-input)
     -0:16.3.0 core:close (atom-pane.pane.active)
     -0:11.2.0 source-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
angular-2-typeScript-snippets 0.7.0 
api-docs 0.0.6 
atom-beautify 0.30.6 
atom-bootstrap3 1.2.12 
atom-hexo 1.1.1 
atom-ide-ui 0.5.4 
atom-material-ui 2.0.6 
atom-ternjs 0.18.3 
autocomplete-json 5.5.0 
autocomplete-paths 2.12.1 
build 0.69.0 
build-gulp 0.11.0 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
docblockr 0.12.1 
double-tag 1.1.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
expose 0.15.0 
file-icons 2.1.13 
flex-tool-bar 0.12.0 
gist-it 0.9.2 
git-diff-details 1.4.0 
git-log 0.4.1 
git-status 0.3.4 
git-time-machine 1.5.9 
gulp-snippets 0.6.2 
hexo-front-matter 0.3.5 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-head-snippets 0.2.0 
hyperclick 0.0.0 
hyperlink-hyperclick 1.3.4 
ide-css 0.2.0 
ide-haskell 2.2.0 
ide-html 0.4.1 
ide-json 0.1.0 
ide-php 0.6.9 
ide-typescript 0.6.2 
insert-timestamp 0.2.4 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-apache 1.7.0 
language-ejs 0.4.0 
language-html-swig 2.0.1 
language-markdown 0.25.1 
language-pug 0.0.21 
language-stylus 0.2.0 
linter-jshint 3.1.6 
linter-pug-lint 0.2.0 
markdown-preview-enhanced 0.14.11 
markdown-table-editor 0.6.4 
markdown-writer 2.7.3 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
one-dark-material-syntax 1.0.3 
open-file 1.4.0 
open-in-browsers 0.0.30 
pdf-view 0.59.0 
php-cs-fixer 4.1.1 
php-server 0.8.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
regex-railroad-diagram 0.19.4 
Remote-FTP 1.3.1 
simple-drag-drop-text 0.3.6 
simplified-chinese-menu 5.3.4 
source-preview 0.5.3 
source-preview-pug 0.2.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
sync-settings 0.8.3 
theme-switcher 1.1.0 
toggle-quotes 1.0.1 
toggler 0.3.0 
tool-bar 1.1.0 
tree-view-git-status 1.4.0 
zip-folder 3.2.0 
```

**Comment by rsese** [comment] 2017-11-07 22:04
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

Stack trace is a bit different but I wonder if this is a duplicate of https://github.com/atom/tabs/issues/444...

**Comment by rsese** [comment] 2018-01-26 20:23
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16108#issuecomment-342637890. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-01-26 20:23 UTC
Labels: more-information-needed, uncaught-exception
