### ISSUE TITLE
Help menu says no update available if update downloaded and installed but restart required

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#10152] opened 2015-12-22 07:07 UTC
The main menu option "Check for Update" doesn't seem to work. I'm on Windows 7 Professional, and Atom version 1.3.1, but I've noticed this at least since version 1.2 and have been 'updating' by downloading and running AtomSetup.exe each time. A dialog box is shown with:

	[Window Title]
	No Update Available

	[Main Instruction]
	No update available.

	[Content]
	Version 1.3.1 is the latest version.

	[OK]

Though https://atom.io/docs currently clearly states the current version 1.3.2

**Comment by damieng** [comment] 2016-04-13 19:30
Are you still getting this problem with newer builds? There were various changes to the installer.

**Comment by stijnsanders** [comment] 2016-04-14 16:08
Yes. Right now, for example. I have a long-running session of version 1.6.2, if I do 'Check for update' I get a response "No update available. Version 1.6.2 is the latest version." Which is not true. Even more, if I close and re-open atom, version 1.7.0 starts since it has been downloaded and installed in the background. I would appreciate it when Atom were able to detect this state and answer me with something like "Restart Atom now to start using the version _x_".

**Comment by damieng** [comment] 2016-04-14 16:53
This sounds like a slightly different problem.  When it has downloaded the next version ready for restart it doesn't tell you and the state it is in makes no sense?

**Comment by Ben3eeE** [comment] 2016-04-14 17:21
I had the exact same problem as @stijnsanders describe on my work computer today. Doing update check from the help menu returned that 1.6.2 was the latest version but the icon indicating that an update is available in the bottom right corner was visible, the little squirrel or what is it. The option in the help menu should have been Restart and install instead of Check for update.

Had a long running session of atom say few hours and I left the computer on over night with atom running, so the actual download probably happened automatically over night. Hours before I checked the help menu the first time.
Restarting atom installed 1.7.0.

I have never used the help menu before just did today cause I have read some issues about it and figured I could test it out and it did not work. So I can't comment on how it has been in previous versions. The icon in the the bottom corner has always been there correctly indicating that an update is available, I look at the status bar relatively often and keep up with releases so I would have noticed if it wasn't. My first atom version was 1.4.high or 1.5.low.

Windows 7.

**Comment by Ben3eeE** [comment] 2016-04-15 05:42
Happened again with 1.7.1 took screenshots, also found two other window related issues when taking screenshots but they are probably different issue(s).

##### Squrriel icon
![squirrle icon](https://cloud.githubusercontent.com/assets/1058982/14552173/e8170594-02db-11e6-9db4-ba469b2a958f.png)

##### Help menu
![help menu](https://cloud.githubusercontent.com/assets/1058982/14552184/f24c2620-02db-11e6-9cf0-11de3eac6963.png)

##### Help menu clicked
![help menu clicked](https://cloud.githubusercontent.com/assets/1058982/14552186/f8abc192-02db-11e6-9f81-1a33b5af0e72.png)

##### Other issue, window doesn't update with dialog open.
![window doesnt update with dialog open](https://cloud.githubusercontent.com/assets/1058982/14552189/00a32da4-02dc-11e6-88df-cf2edbc4862a.PNG)

###### Repro steps for window doesn't update with dialog open.
1. Check for updates.
2. Drag dialog around in atom window.

##### Other issue, title bar is not blue with window focused.
![title not blue](https://cloud.githubusercontent.com/assets/1058982/14552196/190a451c-02dc-11e6-98ce-677ecbf5383a.png)

###### Repro steps for title bar is not blue issue.
1. Open atom window
2. Click the "New" button in the windows snipping tool.
3. Click the "Cancel" button in the windows snipping tool, or take a snip.
4. Focus on atom window, title bar does not turn blue.

I'm pretty sure other things cause this as well since I see it quite often, but these steps seem to work reliably.

**Comment by Ben3eeE** [comment] 2016-04-19 10:56
Possible duplicte: https://github.com/atom/atom/issues/8265

**Comment by lee-dohm** [comment] 2016-04-22 21:31
This is a duplicate of #8265. Sorry to not catch this until now (thanks @Ben3eeE). You may want to subscribe to the original Issue for updates and further discussion.

**Closed by lee-dohm** 2016-04-22 21:31 UTC
Labels: auto-updater, more-information-needed, windows
