### ISSUE TITLE
Feature: "Open recent..." submenu in the "File" menu in the OSX menubar

### ISSUE THREAD

**Issue by mxstbr** [atom/atom#9839] opened 2015-11-26 17:57 UTC
OS X El Capitan, Atom v1.2.4

Sublime Text has an "Open recent..." submenu under the "File" menu in the menu bar

![screen shot 2015-11-26 at 18 53 26](https://cloud.githubusercontent.com/assets/7525670/11428754/4209c914-946f-11e5-998d-2bc4549421c0.png)

which looks like this when open:

![screen shot 2015-11-26 at 18 54 36](https://cloud.githubusercontent.com/assets/7525670/11428758/490e2de0-946f-11e5-8ae4-409679190b60.png)

Where the upper list is a list of recent files and the lower list is a list of recent projects that were open. I used this feature a lot, and I sorely miss it from Atom. Maybe there is a different way of doing this in Atom, but I haven't found it yet and would love to see this added.

Cheers!

**Comment by izuzak** [comment] 2015-11-27 14:10
Thanks for the suggestion, @mxstbr. This looks like a duplicate of https://github.com/atom/atom/issues/4241 so I'm going to close this in favor of that issue. For now, you might try some community packages, such as https://atom.io/packages/open-recent

**Closed by izuzak** 2015-11-27 14:10 UTC
