### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/bkrodg/Library/Application Suppo...

### ISSUE THREAD

**Issue by bkrodgers** [atom/atom#9706] opened 2015-11-19 23:18 UTC
Loaded a file from the command line using `open -a Atom <file>`

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/bkrodg/Library/Application Support/com.github.atom.ShipIt/update.WB0OHau'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/bkrodg/Library/Application Support/com.github.atom.ShipIt/update.WB0OHau'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/bkrodg/Library/Application Support/com.github.atom.ShipIt/update.WB0OHau/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (module.js:388:19)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-20 00:43
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-20 00:43 UTC
