### ISSUE TITLE
Uncaught Error: Requested measurement of a line that is not currently rendered

### ISSUE THREAD

**Issue by fcrisciani** [atom/atom#15025] opened 2017-07-14 16:20 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2150

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2148:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2141:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:382:16)
    at scheduler.readDocument (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:266:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:28.6.0 editor:delete-line (input.hidden-input)
  8x -0:28.2.0 core:move-up (input.hidden-input)
  2x -0:26.8.0 core:move-down (input.hidden-input)
  2x -0:20.4.0 core:move-up (input.hidden-input)
  3x -0:19.9.0 core:move-down (input.hidden-input)
     -0:18.9.0 editor:newline (input.hidden-input)
     -0:17.5.0 core:undo (input.hidden-input)
     -0:16.5.0 core:move-up (input.hidden-input)
     -0:15.7.0 editor:consolidate-selections (input.hidden-input)
     -0:15.7.0 core:cancel (input.hidden-input)
  2x -0:15.2.0 core:move-up (input.hidden-input)
  2x -0:14.6.0 core:move-down (input.hidden-input)
     -0:14.3.0 editor:consolidate-selections (input.hidden-input)
     -0:14.3.0 core:cancel (input.hidden-input)
  3x -0:13.8.0 core:move-right (input.hidden-input)
     -0:11.4.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
auto-update-packages 1.0.1 
busy-signal 1.4.3 
file-icons 2.1.8 
git-blame 1.1.1 
git-history 3.3.0 
git-time-machine 1.5.9 
go-debug 1.5.0 
go-outline 0.6.6 
go-plus 5.5.5 
go-signature-statusbar 1.2.1 
highlight-selected 0.13.1 
hyperclick 0.1.2 
intentions 1.1.2 
language-protobuf 0.7.1 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.6.2 
maximize-panes 0.2.0 
minimap 4.28.3 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.1 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
persistent-undo 1.2.0 
project-manager 3.3.5 
split-diff 1.4.3 
sync-settings 0.8.2 
```

**Comment by rsese** [comment] 2017-07-18 08:08
Thanks for the report!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14834. You may want to subscribe there for updates and if you have steps to reproduce in safe mode (`atom --safe`), feel free to share that in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-18 08:08 UTC
