### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by Jeremy0dell** [atom/atom#14978] opened 2017-07-09 23:43 UTC
[Enter steps to reproduce:]

1. right click cut and chunk of code from one file
2. command+v that chunk of code into another file

**Atom**: 1.19.0-beta2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /private/var/folders/83/n3mr3_dn30310lrf67gsr0wc0000gn/T/AppTranslocation/77D1842A-E571-4996-B5C1-F031F7F00B3E/d/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2138

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/private/var/folders/83/n3mr3_dn30310lrf67gsr0wc0000gn/T/AppTranslocation/77D1842A-E571-4996-B5C1-F031F7F00B3E/d/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2138:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/private/var/folders/83/n3mr3_dn30310lrf67gsr0wc0000gn/T/AppTranslocation/77D1842A-E571-4996-B5C1-F031F7F00B3E/d/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2134:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/private/var/folders/83/n3mr3_dn30310lrf67gsr0wc0000gn/T/AppTranslocation/77D1842A-E571-4996-B5C1-F031F7F00B3E/d/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:378:16)
    at scheduler.readDocument (/private/var/folders/83/n3mr3_dn30310lrf67gsr0wc0000gn/T/AppTranslocation/77D1842A-E571-4996-B5C1-F031F7F00B3E/d/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:263:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/private/var/folders/83/n3mr3_dn30310lrf67gsr0wc0000gn/T/AppTranslocation/77D1842A-E571-4996-B5C1-F031F7F00B3E/d/Atom Beta.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /private/var/folders/83/n3mr3_dn30310lrf67gsr0wc0000gn/T/AppTranslocation/77D1842A-E571-4996-B5C1-F031F7F00B3E/d/Atom Beta.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -4:02.8.0 editor:newline (input.hidden-input)
     -3:59.1.0 core:move-down (input.hidden-input)
     -3:52.5.0 autocomplete-plus:confirm (input.hidden-input)
     -3:47.2.0 core:move-left (input.hidden-input)
     -3:46.9.0 editor:newline (input.hidden-input)
     -3:46.6.0 core:move-up (input.hidden-input)
     -3:46.2.0 snippets:next-tab-stop (input.hidden-input)
     -3:46.2.0 snippets:expand (input.hidden-input)
     -3:46.2.0 editor:indent (input.hidden-input)
  2x -3:40.3.0 core:save (input.hidden-input)
     -0:51.1.0 core:cut (span.syntax--meta.syntax--brace.syntax--round.syntax--js)
     -0:49.3.0 core:backspace (input.hidden-input)
     -0:42.3.0 core:paste (div.lines)
  2x -0:25 core:undo (input.hidden-input)
  3x -0:19.3.0 core:copy (input.hidden-input)
 11x -0:10.9.0 core:backspace (atom-text-editor.editor)
```

### Non-Core Packages

```
busy-signal 1.4.3 
dark-side-of-the-moon-syntax 0.6.26 
file-icons 2.1.8 
file-type-icons 1.3.4 
hacking-the-kernel 1.6.2 
hacking-the-kernel-ui 1.6.2 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-babel 2.66.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
platformio-ide-terminal 2.5.3 
pristine-ui 1.0.15 
react-snippets 0.8.0 
script 3.15.0 
```

**Comment by rsese** [comment] 2017-07-11 20:21
Thanks for the report!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14794. You may want to subscribe there for updates and if you can let us know in that issue if you can reproduce the error in safe mode with your steps to reproduce, that would be helpful to know.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-11 20:21 UTC
