### ISSUE TITLE
Uncaught TypeError: fs.makeTree is not a function

### ISSUE THREAD

**Issue by ramslak** [atom/atom#15632] opened 2017-09-13 05:28 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: fs.makeTree is not a function

```
At /Users/rams/Documents/kindora/Atom Beta.app/Contents/Resources/app/src/command-installer.js:87

TypeError: fs.makeTree is not a function
    at fs.unlink (/Users/rams/Documents/kindora/Atom Beta.app/Contents/Resources/app/src/command-installer.js:87:16)
    at /Users/rams/Documents/kindora/Atom Beta.app/Contents/Resources/app/node_modules/fs-admin/index.js:153:30
```

### Commands

```
     -3:51.2.0 core:confirm (input.hidden-input)
     -0:14.6.0 window:install-shell-commands (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-ide-ui 0.3.1 
emmet 2.4.3 
ide-typescript 0.6.1 
```

**Comment by smashwilson** [comment] 2017-09-13 19:02
I can reproduce by running:

```bash
rm /usr/local/bin/atom
sudo chown root /usr/local/bin
sudo chmod 555 /usr/local/bin
```

Then running `window:install-shell-commands` from the command palette.

_[ 🔎 intensifies ]_

**Comment by smashwilson** [comment] 2017-09-13 19:23
@maxbrunsfeld It looks like `fsAdmin.makeTree()` was added [after fs-admin 0.1.5 was published](https://github.com/atom/fs-admin/compare/v0.1.5...master). Any reason not to just push a new version and :arrow_up:?

**Comment by maxbrunsfeld** [comment] 2017-09-13 19:30
:man_facepalming:

**Comment by maxbrunsfeld** [comment] 2017-09-13 20:13
Fixed in https://github.com/atom/atom/commit/d7520625121cc3c096975b034be98629cff51569

**Comment by smashwilson** [comment] 2017-09-13 20:14
Thanks @maxbrunsfeld!

**Closed by maxbrunsfeld** 2017-09-13 20:13 UTC
Labels: bug, mac, regression, triaged, uncaught-exception

**Comment by smashwilson** [comment] 2017-09-13 20:18
Cherry-picked to 1.21-releases as e8c38503e.
