### ISSUE TITLE
Global replace needs [Find] and [Replace] (in addition to [Replace All])

### ISSUE THREAD

**Issue by jcalfee** [atom/atom#8827] opened 2015-09-17 17:33 UTC
In Global search and replace (c+s+f) there only a `Replace All` button .. It really needs to also include `Find` and `Replace` buttons.

**Comment by mnquintana** [comment] 2015-09-20 01:59
Thanks for the suggestion. This looks like a duplicate of https://github.com/atom/find-and-replace/issues/297 and though - closing this out in favor of those issues.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Closed by mnquintana** 2015-09-20 01:59 UTC
