### ISSUE TITLE
Atom opens /usr/bin/atom and asks for unsaved changes.

### ISSUE THREAD

**Issue by ttxtea** [atom/atom#21223] opened 2020-08-27 07:11 UTC
### Description

Opon starting atom the file `/usr/bin/atom/` and the file `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT`  is opened. Once a project is opened one often wishes to close this window. But at least the `/usr/bin/atom` requires super user right. The file seems to be empty actually. Atom was installed using `snap` and the `which atom` yields `/snap/bin/atom`.

### Versions

`atom --version` yields nothing.

`apm --version` yields

~~~
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 
git 2.25.1
~~~

**Comment by PK-Patomsiri** [comment] 2020-09-08 23:40
> ### Description
> 
> 
> 
> Opon starting atom the file `/usr/bin/atom/` and the file `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT`  is opened. Once a project is opened one often wishes to close this window. But at least the `/usr/bin/atom` requires super user right. The file seems to be empty actually. Atom was installed using `snap` and the `which atom` yields `/snap/bin/atom`.
> 
> 
> 
> ### Versions
> 
> 
> 
> `atom --version` yields nothing.
> 
> 
> 
> `apm --version` yields
> 
> 
> 
> ~~~
> 
> apm  2.5.0
> 
> npm  6.14.5
> 
> node 10.20.1 x64
> 
> atom 1.50.0
> 
> python 
> 
> git 2.25.1
> 
> ~~~
> 
>

**Comment by ttxtea** [comment] 2020-09-30 11:12
This behaviour persist for newly installed atom (using snap) on `ubuntu` and `lubuntu`.

**Comment by temporallyaccount** [comment] 2020-10-03 23:10
confirm on 1.51.0 (64bit) snap. that's really a headache. can someone fix that quick and commit to master? not a take time task.

**Comment by Aerijo** [comment] 2020-10-04 04:48
Duplicate of https://github.com/atom/atom/issues/20942. TL;DR Atom doesn't provide a snap release so raising an issue here is pointless.

**Closed by Aerijo** 2020-10-04 04:48 UTC
Labels: triaged
