### ISSUE TITLE
Two icons in taskbar (Windows)

### ISSUE THREAD

**Issue by mittalyashu** [atom/atom#15104] opened 2017-07-27 13:53 UTC
I am not sure if other people face the same issue or not.
When I launch the atom it shows two icons.

Here is the image:
![image](https://user-images.githubusercontent.com/29014463/28673747-008a5df6-7301-11e7-9d7a-cf03672fcc76.png)

**Comment by mpboom** [comment] 2017-07-28 07:45
I beleive you can fix this problem by removing all icons from the taskbar, then open Atom and then pin the opened instace of Atom to the taskbar.

I’m not sure, but maybe the (in you screenshot) shortcut to the left is a shortcut to the updater (which has the same icon) and if you click that it updates Atom and then opens the “real” Atom. Windows thinks it is a different program and thus creates the extra icon. Again, I’m not sure about that but I know it works like that for some programs.

**Comment by mittalyashu** [comment] 2017-07-30 19:06
`I believe you can fix this problem by removing all icons from the taskbar, then open Atom and then pin the opened instace of Atom to the taskbar.`

I have tried this, but after trying this the problem still exists.

**Comment by mpboom** [comment] 2017-07-30 19:21
What are the locations of both executables? You can view them by right-clicking Atom, then right-clicking the "Atom" field again and then clicking `Properties` (in the picture `Eigenschappen`). There you will be able to see from which executable the item in the taskbar really is.

Can you post those two executable locations? Maybe that gives more insight in which executables those items on the taskbar are.

![viewproperties](https://user-images.githubusercontent.com/19948032/28756337-9589dd24-756c-11e7-9301-101d18af58e8.PNG)

**Comment by rsese** [comment] 2017-07-31 19:26
Feel free to keep discussing how to get rid of the duplicate pinned icon here @mittalyashu @mpboom (thanks again for lending a hand),  but I'm going to go ahead and close this since it's a duplicate of https://github.com/atom/atom/issues/14813.

**Closed by rsese** 2017-07-31 19:26 UTC

**Comment by mittalyashu** [comment] 2017-08-02 14:39
Sure, @rsese. But I was unaware of this (issue)[https://github.com/atom/atom/issues/14813]
