### ISSUE TITLE
Python2/3 syntax highlighting

### ISSUE THREAD

**Issue by kianxineki** [atom/atom#10902] opened 2016-02-19 11:57 UTC
I found an error when writing "DELETE" in """``````"""

"""
```
DELETE: example comment
```
"""

![python_syntax_color](https://cloud.githubusercontent.com/assets/3725538/13175006/bbc73d7e-d707-11e5-87c5-fae91ffa10f2.png)

**Comment by rbottema** [comment] 2016-02-19 12:40
Possible duplicate of atom/language-python#118

**Comment by 50Wliu** [comment] 2016-02-19 14:17
Thanks @rbottema - @kianxineki feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-19 14:17 UTC
