### ISSUE TITLE
Dropping multiple files into an empty atom window makes each file a root "folder"

### ISSUE THREAD

**Issue by nshtg** [atom/atom#7099] opened 2015-06-04 16:27 UTC
OS: Windows 7 x64, freshly build `atom-v0.206.0-e1514cf` in safe mode.

I made a gif to show:

![animation 0](https://cloud.githubusercontent.com/assets/5219415/7989076/6428ce62-0ae7-11e5-8d60-c76487570229.gif)

**Comment by mnquintana** [comment] 2015-06-04 16:47
I can't reproduce this with Atom 0.206.0-e1514cf and OS X 10.10.3 – maybe this is a Windows only thing? I'll try this with my VM to see.

**Comment by maschs** [comment] 2015-06-04 17:13
I can confirm it's not happening on OSX. Only windows. Don't know about linux.

**Comment by MadMac** [comment] 2015-06-27 11:59
Reproduced on Windows 8.1 32-bit. Atom version 1.0.0.

**Comment by 50Wliu** [comment] 2016-06-03 20:39
According to @ben3eeE this is no longer reproducible on Atom 1.9.0, so I'm going to close this.

**Closed by 50Wliu** 2016-06-03 20:39 UTC
Labels: needs-reproduction, windows
