### ISSUE TITLE
Clipboard does not copy ascii text from atom to firefox

### ISSUE THREAD

**Issue by GuerrillaWarfare** [atom/atom#6231] opened 2015-04-03 03:23 UTC
When attempting to copy text from atom to a different program such as a google search in firefox, the copy attempt fails and does not post any text at all.

**Comment by izuzak** [comment] 2015-04-03 17:13
@GuerrillaWarfare Which version of Atom are you using and which OS? Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by GuerrillaWarfare** [comment] 2015-04-03 19:19
I'm running atom 0.189.0 on Ubuntu 14.04 LTS.

**Comment by opennomad** [comment] 2015-04-03 20:59
Ubuntu 14.10 I have the same issue. I can not copy and paste to another app, but pasting in atom works. I also tried with `--safe` and it has the same behavior. Downgrading to 0.188.0 makes things work again.

**Comment by despairblue** [comment] 2015-04-03 23:10
Arch Linux here, everything up to date and having the same problem. In sublime text or chrome the context menu won't even show up if I have something in the clipboard from an atom buffer.

**Comment by despairblue** [comment] 2015-04-03 23:17
Copying stuff from a markdown preview works. Also trying to copy something from a buffer into chrome will crash the tab and copying into sublime will...well, the cursor stays put when I type: the characters appear but the cursor will just stay in its current position and will keep blinking.

Using the selection clipboard (selecting text and pasting it with middle mouse click) works  though... :confused:

**Comment by didrocks** [comment] 2015-04-05 16:46
Same here on ubuntu vivid, downgrading to 0.188.0 works.
To sum up:
- pasting in atom works with Ctrl+V
- copying from atom (to another atom instance or any other app) doesn't work with Ctrl+C (it's not in X window paste area)
Subcribing.

**Comment by pmros** [comment] 2015-04-05 19:08
Same problem here (Arch Linux).
Downgrading...

**Comment by 50Wliu** [comment] 2015-04-05 22:07
I'm going to close this as a duplicate of #6221.

**Closed by 50Wliu** 2015-04-05 22:07 UTC
Labels: more-information-needed
