### ISSUE TITLE
OS X: Atom can't update as a non-administrator, wastes bandwidth

### ISSUE THREAD

**Issue by csuhta** [atom/atom#11939] opened 2016-06-08 18:43 UTC
### Description

OS X El Capitan: Atom cannot update itself if you log in as a non-administrator. If you have automatic updates turned on, it will also re-download the update every few hours, wasting bandwidth.

### Steps to Reproduce

0. Log in as a non-administrator on OS X.
1. Install Atom anywhere, it doesn't matter if you use `~/Applications` or `/Applications`
2. Let Atom check for updates
3. Click "Restart and install" in the About dialog.

![swzuygqf](https://cloud.githubusercontent.com/assets/769083/15906276/24eb541e-2d86-11e6-80c1-d7c44712572a.png)

**Expected behavior:** Atom should close, and a dialog should prompt you for administrator credentials if necessary. The Atom.app bundle should be replaced.

**Actual behavior:** Nothing happens when you click the button. If you have automatic updates turned on, Atom will also re-download the update every few hours, wasting bandwidth.

![z2040ies](https://cloud.githubusercontent.com/assets/769083/15906335/5bdec348-2d86-11e6-8b09-a59853f4999c.png)

### Other Notes

Logging in as an administrator is not a solution. It's unwise to use OS X daily as an administrator, and many IT policies forbid it. Other apps correctly prompt you to provide administrator credentials when you want to make system changes.

Putting Atom in `~/Applications` doesn't fix this issue, but it's also not a long-term solution if fixes are made. Users should be able to install Atom in `/Applications`.

The GitHub Desktop app has this exact same problem, and I've reported it to them twice. It may be an issue with ShipIt.

### Versions

```
$ atom --version
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

![ae95mneo](https://cloud.githubusercontent.com/assets/769083/15906232/fe7c3f32-2d85-11e6-8f69-3589dda8b391.png)

**Comment by Nikki1993** [comment] 2016-06-08 18:56
Most likely duplicate of [#21](https://github.com/atom/about/issues/21)

**Comment by 50Wliu** [comment] 2016-06-08 19:12
This is a duplicate of #2860 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-08 19:12 UTC
