### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\C:\ProgramData\kmitch913\atom\app-1...

### ISSUE THREAD

**Issue by Zmmitch** [atom/atom#21770] opened 2020-11-28 22:21 UTC
I am a beginning student trying to learn web developement. After months of practice I have taken 5 months off and came back to this. Every time I open up atom and try to type code or make a new file I get this message.

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\ProgramData\kmitch913\atom\app-1.53.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:138

Error: The specified module could not be found.
\\?\C:\ProgramData\kmitch913\atom\app-1.53.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (C:/ProgramData/kmitch913/atom/app-1.53.0/resources/app/static/<embedded>:1:736531)
    at get_KeyboardLayoutManager (C:/ProgramData/kmitch913/atom/app-1.53.0/resources/app/static/<embedded>:14:2789479)
    at get_manager (C:/ProgramData/kmitch913/atom/app-1.53.0/resources/app/static/<embedded>:14:2789581)
    at Object.getCurrentKeyboardLayout (C:/ProgramData/kmitch913/atom/app-1.53.0/resources/app/static/<embedded>:14:2789707)
    at e.keystrokeForKeyboardEvent (C:/ProgramData/kmitch913/atom/app-1.53.0/resources/app/static/<embedded>:14:1057734)
    at KeymapManager.keystrokeForKeyboardEvent (C:/ProgramData/kmitch913/atom/app-1.53.0/resources/app/static/<embedded>:11:1227949)
    at KeymapManager.handleKeyboardEvent (C:/ProgramData/kmitch913/atom/app-1.53.0/resources/app/static/<embedded>:11:1225934)
    at WindowEventHandler.handleDocumentKeyEvent (C:/ProgramData/kmitch913/atom/app-1.53.0/resources/app/static/<embedded>:11:284919)
```

### Commands

```
  2x -7:18.4.0 application:open-folder (div.tool-panel.tree-view)
  3x -6:10.3.0 tree-view:add-file (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by darangi** [comment] 2020-12-09 17:40
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).a

**Closed by darangi** 2020-12-09 17:40 UTC
