### ISSUE TITLE
Atom window not focused when opening a file

### ISSUE THREAD

**Issue by Keith94** [atom/atom#13846] opened 2017-02-18 06:02 UTC
### Description

When opening a file with Atom, the Atom window does not get focus

### Steps to Reproduce

1. Right click a .txt file and open with Atom
2. Go back to the folder and open another .txt file

**Expected behavior:** The Atom window gets brought to the foreground

**Actual behavior:** The Atom window stays behind other windows, with the taskbar icon flashing

**Reproduces how often:** Always

### Versions

Atom 1.14.3
Windows 8

### Additional Information

Screencast:
![2017-02-17_21-51-22](https://cloud.githubusercontent.com/assets/5490615/23090839/537e2e3e-f55c-11e6-9ff9-c108282a10cc.gif)

**Comment by rsese** [comment] 2017-02-20 19:54
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/6201. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-02-20 19:54 UTC
