### ISSUE TITLE
Windows 7 - No any git related color highlighting, diff info

### ISSUE THREAD

**Issue by DJviolin** [atom/atom#7424] opened 2015-06-25 22:38 UTC
Seems like every git related functions of Atom not working for me. I used the official windows installer, but in the past I used the zip package, still the same. git is in my PATH, just like apm and atom.

For the records I'm in an actual .git repo and editing a file when this happens (or more accurate: not happening anything).

**Comment by DJviolin** [comment] 2015-06-26 10:10
I found the issue: I didn't opened the git repo folder, instead I opened my projects folder with every single .git sub-projects inside.

But this raise a serious question: why can't work by file by file? If I open a file from any subfolder, I want the git support for that particular file also.

**Comment by izuzak** [comment] 2015-06-26 10:30
I believe this is a duplicate of https://github.com/atom/atom/issues/2203. If I'm misunderstanding -- please let me know and provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and exact steps to reproduce. Thanks!

**Closed by izuzak** 2015-06-26 10:30 UTC

**Comment by DJviolin** [comment] 2015-06-26 10:43
Hi! The issue was I misunderstood how git integration works in Atom. I have always my projects folder open (C:/www) where Is tore my sub-projects. Some sub-projects has .git repos. If I open a file, the git highlighting not will work. But I open a git repo with File -> Open folder..., it will work. The problem is I don't want many open Atom windowses at the same time. That's why I organising everything under C:/www

**Comment by izuzak** [comment] 2015-06-26 10:55
> The problem is I don't want many open Atom windowses at the same time.

You don't need to have many open Atom windows -- you can have all in the same window: you can add multiple projects. Right click somewhere in the tree view on the left and select "Add project folder", and then select the root directory of the Git project you want to add.

**Comment by DJviolin** [comment] 2015-06-26 11:01
Happened with me many times during the beta, that Atom lost the opened tabs and folders state after reinstall. Adding manually folders to a project like this is good, but would be nice to see some Atom related project file for this. Like .gitignore or editorconfig format.

**Comment by izuzak** [comment] 2015-06-26 11:12
> Happened with me many times during the beta, that Atom lost the opened tabs and folders state after reinstall. 

If you can reliably reproduce this -- it would be great if you could open a new issue for this and list those steps.

> Adding manually folders to a project like this is good, but would be nice to see some Atom related project file for this. Like .gitignore or editorconfig format.

See #2203 and https://github.com/atom/atom/issues/6589

**Comment by DJviolin** [comment] 2015-06-26 11:24
Since 1.0.0 I use the installer version, but in the past I used the windows zip file. I placed my Atom installation into C:/Program Files (x86)/Atom and I deleted everything in the C:\Users\[Username]\.atom folder, except config files in the parent dir and packages folder, to maintain better compatibility with the new version.

**Comment by izuzak** [comment] 2015-06-26 11:31
>  I deleted everything in the C:\Users\[Username]\.atom folder, except config files in the parent dir and packages folder, to maintain better compatibility with the new version.

Well, that would explain things -- if you deleted files which contained relevant state information, then you've observed expected behavior.

**Comment by DJviolin** [comment] 2015-06-26 11:33
Can it be possible to move the opened folder and files state record into config.cson?

config.cson will be saved into a gist with the Synchronize Settings plugin.

**Comment by izuzak** [comment] 2015-06-26 11:36
> Can it be possible to move the opened folder and files state record into config.cson?

I suggest you open a new issue to discuss that, so that you can clearly explain the use-cases and problems with the current approach. Discussing 5 different problems in a single issue isn't helpful and makes it difficult to manage feature requests and bugs. Thanks.
