### ISSUE TITLE
Menu's do not show on secondary monitor

### ISSUE THREAD

**Issue by davittsm** [atom/atom#7089] opened 2015-06-03 18:10 UTC
When I click the 'File', 'Edit', etc menu items when atom is opened on a secondary screen, the menu items do not show up. I have to drag atom to my primary monitor to see the menu items expand. Depending on the location of atom on the secondary scree, you can see the menu items appear in the top right hand screen of my primary monitor (attached screenshot)

![atomissue](https://cloud.githubusercontent.com/assets/12735699/7967765/dea14ecc-09f1-11e5-9b51-78ac03dded60.png)

**Comment by mnquintana** [comment] 2015-06-04 01:07
This looks like a duplicate of https://github.com/atom/atom/issues/3415 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-04 01:07 UTC
