### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by darlanxw** [atom/atom#7608] opened 2015-07-01 02:02 UTC
[Enter steps to reproduce below:]

1. Right click on any folder.

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitO

**Comment by mnquintana** [comment] 2015-07-01 02:03
Duplicate of #6548 - this has been fixed for the next version of Atom.

**Closed by mnquintana** 2015-07-01 02:03 UTC
