### ISSUE TITLE
Reflowing paragraph in GFM starting with asterisk results in each line starting with asterisk.

### ISSUE THREAD

**Issue by Benjamin-Lee** [atom/atom#18214] opened 2018-10-09 04:42 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

Reflowing a paragraph starting with an asterisk (for bold first sentence) results in each new line starting with an asterisk.

### Steps to Reproduce

1. Start a paragraph with **something**
2. Write some more
3. Reflow

**Expected behavior:** [What you expect to happen]

```
**Bold text** this is my really long string which I want to be reflowed nicely
but it isn't
```

**Actual behavior:** [What actually happens]

```
**Bold text** this is my really long string which I want to be reflowed nicely
*but it isn't
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-10-14 02:39
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/18024 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-14 02:39 UTC
