### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by janlucaberger** [atom/atom#15213] opened 2017-08-09 14:58 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2168

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2168:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:385:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:27.5.0 snippets:next-tab-stop (input.hidden-input)
     -1:27.5.0 snippets:expand (input.hidden-input)
     -1:27.5.0 editor:indent (input.hidden-input)
     -1:26.5.0 snippets:next-tab-stop (input.hidden-input)
     -1:26.5.0 snippets:expand (input.hidden-input)
     -1:26.5.0 editor:indent (input.hidden-input)
  7x -1:21.5.0 core:backspace (input.hidden-input)
  3x -1:16 core:move-right (input.hidden-input)
  2x -1:12.9.0 core:backspace (input.hidden-input)
     -1:10.9.0 core:save (input.hidden-input)
     -1:09.8.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -0:54.7.0 core:backspace (input.hidden-input)
  3x -0:53.4.0 core:save (input.hidden-input)
     -0:42.2.0 find-and-replace:select-next (input.hidden-input)
     -0:39.3.0 find-and-replace:show (input.hidden-input)
 16x -0:38.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-monokai 0.10.9 
busy-signal 1.4.3 
file-icons 2.1.10 
intentions 1.1.5 
jshint 1.8.6 
linter 2.2.0 
linter-eslint 8.2.1 
linter-rubocop 2.1.1 
linter-ui-default 1.6.3 
monokai-seti 0.9.0 
pigments 0.40.1 
react 0.16.2 
rspec 0.3.4 
scope-inspector 1.0.1 
seti-ui 1.9.0 
```

**Comment by rsese** [comment] 2017-08-09 17:42
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15168. You may want to subscribe there for updates - if you have consistent steps to reproduce in safe mode, please let us know in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-09 17:42 UTC
