### ISSUE TITLE
Atom 1.28 doesn't work on OSX Yosemite 10.10.5

### ISSUE THREAD

**Issue by ggl** [atom/atom#17556] opened 2018-06-22 08:05 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom doesn't work on OSX Yosemite 10.10.5

### Steps to Reproduce

1. Start Atom

**Expected behavior:** Run

**Actual behavior:** OSX throws an wrror message

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

1.28, stock OSX download or 1.27.2 updated. I'm not installing the breakage again to run atom --version, stuck on 1.27.2 now.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Lax** [comment] 2018-06-22 10:34
macOS 10.13.2 (17C88)

An possible reason: atom don't work with shadowsocks https://github.com/atom/atom/issues/17552#issuecomment-399310476

**Comment by thomasjo** [comment] 2018-06-22 12:17
I'm closing this as a duplicate of #17557. Please subscribe there for updates.

**Closed by thomasjo** 2018-06-22 12:17 UTC
