### ISSUE TITLE
Currently remember application state isn't working in Windows

### ISSUE THREAD

**Issue by Goddard** [atom/atom#8164] opened 2015-07-31 05:25 UTC
If you have multiple windows open in Atom for multiple projects they don't open both windows when closing.  

It would be awesome if you could re-open the Windows or remember Project states and just re-open the projects to the existing states.  I read the news announcement that this was done, but it appears the feature was only done for OSX?  Not Linux or Windows?

**Comment by mnquintana** [comment] 2015-07-31 11:04
@Goddard How are you quitting Atom? If you're quitting by individually closing out windows, then this feature won't work, and that would be expected. You'd need to quit by going to File > Exit for Atom to remember all of your open windows.

**Comment by damieng** [comment] 2016-05-05 23:30
No response from originator and unable to reproduce. Please re-open if you have more information.

**Closed by damieng** 2016-05-05 23:30 UTC
Labels: more-information-needed, windows
