### ISSUE TITLE
Wrong .gitignore path on Windows

### ISSUE THREAD

**Issue by SebastianPozoga** [atom/atom#13712] opened 2017-01-29 19:37 UTC
### Description
When I save .gitignore file I take a fail . 

!!!! I have permissions to the file. The bug is by wrong path.

```
Unable to save file 'C:\.\work\src\github.com\goatcms\goatcms.gitignore'
EPERM: operation not permitted, open 'C:\...\work\src\github.com\goatcms\goatcms\.gitignore'
```

Path is:
C:\.\work\src\github.com\goatcms\goatcms.gitignore
and it should be:
C:\...\work\src\github.com\goatcms\goatcms\.gitignore
lost '\' char.
**Plase don't close without check.** 

![error-atom-gitignore](https://cloud.githubusercontent.com/assets/1093166/22395869/f0839466-e54a-11e6-812b-b7640c4a6c21.png)

[Description of the issue]

### Steps to Reproduce

1. create .gitignore file
2. open it in atom
3. save

**Expected behavior:** 
save file (without errors)

**Actual behavior:** 
it is fail

**Reproduces how often:**
Always

### Versions
Windows 10
atom 1.13.1 ia32

Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python
git 2.11.0.windows.3
visual studio

**Comment by 50Wliu** [comment] 2017-01-29 19:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #13706. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-01-29 19:38 UTC
