### ISSUE TITLE
Select Inside Brackets includes insides of parent html tag

### ISSUE THREAD

**Issue by filipesilva** [atom/atom#7383] opened 2015-06-23 12:00 UTC
I'm pretty sure this was not the behavior last week, but at least today in the new atom version it is.

![select-inside](https://cloud.githubusercontent.com/assets/4172079/8305507/a9c56920-19a7-11e5-9d1e-61ce449c9a63.gif)

System: Win8.1, Atom 0.211.0

**Comment by mnquintana** [comment] 2015-06-23 12:01
Would you mind moving this to https://github.com/atom/bracket-matcher?

**Comment by izuzak** [comment] 2015-06-23 12:02
This is a duplicate of https://github.com/atom/bracket-matcher/issues/117, I believe

**Closed by izuzak** 2015-06-23 12:02 UTC

**Comment by filipesilva** [comment] 2015-06-23 12:15
Apologies, I did not know there this functionality was in a different repo.
