### ISSUE TITLE
Autocomplete multi-edit shouldn't create new word

### ISSUE THREAD

**Issue by VanVeenGames** [atom/atom#7817] opened 2015-07-09 17:05 UTC
Looking at Sublime Text, they got this right. Scenario:
```
var b = false;
var c = false;\
```
Now we go to multi-edit:
```
var b = \;
var c = \;
```
If I type
```
var b = fal\;
var c = fal\;
```
The autocomplete shows "fal" as an option, because the popup for autocomplete scans back from the last cursor (which is fine), but because it looks back, it finds "fal", even though I'm typing there. So in the look back it should exclude all the identifiers/keywords I'm currently typing in. This makes sense because while you're typing it doesn't (nor should it) show autocomplete for exactly that which you typed.

**Comment by benogle** [comment] 2015-07-09 17:52
I think this is a duplicate of https://github.com/atom/autocomplete-plus/issues/467. Closing in favor of that one. This should be out in the next version of atom.

**Closed by benogle** 2015-07-09 17:52 UTC

**Comment by VanVeenGames** [comment] 2015-07-09 17:56
Agreed, that's a better description. Never came across it while I searching for autocomplete, must have missed it. Thanks!
