### ISSUE TITLE
atom gui error

### ISSUE THREAD

**Issue by locotron** [atom/atom#10790] opened 2016-02-12 10:25 UTC
![2016-02-12-112412_1280x800_scrot](https://cloud.githubusercontent.com/assets/14056306/13004339/3683ddde-d17b-11e5-9607-88d7bb1c6291.png)

## Os: Lubuntu 15.10 32 bit
After 3 days of try, and tons of errors. I get this.

npm -v: 2.14.12
node -v: v4.3.0

# Console

    

> Error: Cannot find module '../build/Release/onig_scanner.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/local/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/oniguruma/lib/oniguruma.js:65:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/first-mate/lib/grammar.js:10:16)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/first-mate/lib/grammar.js:365:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:12:13)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:261:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/first-mate/lib/first-mate.js:4:22)handleSetupError @ index.js:

i try reinstalling node and atom, but that dont take effect

Plase help i need atom :(!!

**Comment by locotron** [comment] 2016-02-12 13:11
i try reinstalling node and atom, but that dont take effect

**Comment by lee-dohm** [comment] 2016-02-12 20:36
Looks like a duplicate of this issue: https://github.com/atom/atom/issues/9220

Please try the workaround described there.

**Comment by locotron** [comment] 2016-02-12 20:42
i tried it, i used 

> Hi @z3to, for your issue, please delete the ~/.atom/blob-store folder.

and i get 

> bash: /home/ayman/.atom/blob-store: No such file or directory

**Comment by locotron** [comment] 2016-02-13 09:58
I remove all atom folders, and i install it again and i get a different error;

The webupd atom, (its the 1.4 version) its working without any error, but the 1.5.2 no

> Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/local/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:15:12)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-provider.js:8:19)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-provider.js:83:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)handleSetupError @ index.js:62

**Comment by lee-dohm** [comment] 2016-02-15 18:36
How did you install the v1.5.2 version?

**Comment by locotron** [comment] 2016-02-15 19:04
I get a solution.
I remove all The atom folders, and proceses and now its working.

**Comment by lee-dohm** [comment] 2016-02-15 19:25
I'm glad to hear that it is working for you. Thanks for following up!

**Closed by lee-dohm** 2016-02-15 19:25 UTC
Labels: duplicate
