### ISSUE TITLE
Uncaught Error: Setting active pane that is not present in pane container

### ISSUE THREAD

**Issue by dlfivefifty** [atom/atom#13410] opened 2016-12-08 23:03 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:195

Error: Setting active pane that is not present in pane container
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:195:17)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:835:14)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:240:21)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:50:23)
```

### Commands

```
     -0:28.8.0 core:cut (atom-text-editor.editor.is-focused)
     -0:27.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:20.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:19.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -0:19.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:18.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:17.8.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -0:17.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:08.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -0:06.2.0 julia-client:open-console (atom-text-editor.editor.is-focused)
     -0:02.8.0 editor:join-lines (atom-text-editor.editor.is-focused)
  2x -0:02.7.0 julia-client:open-console (atom-text-editor.editor.is-focused)
     -0:02.4.0 application:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "scrollPastEnd": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.6.1 (active)
julia-client, v0.5.10 (active)
language-julia, v0.10.0 (active)
latex-completions, v0.3.2 (active)
project-plus, v0.9.0 (active)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (active)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (active)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2016-12-23 20:30
Can you give some steps to reproduce the problem? It looks like this might be an issue with the [julia-client package](https://atom.io/packages/julia-client). If so, this should probably be reported on that package's repository.

**Comment by lee-dohm** [comment] 2017-01-28 22:51
Thank you for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13410#issuecomment-269042280. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by lee-dohm** 2017-01-28 22:51 UTC
Labels: more-information-needed

**Comment by frenchbread** [comment] 2017-04-13 11:16
Getting save issue and the tree view in not working in `atom-beta`. Possible steps to reproduce it using package `project-plus` and trying to open a project.

**Comment by sentience** [comment] 2017-04-23 01:53
Seeing the same thing in atom-beta when switching projects with the Project Manager package. After switching projects, the Tree View is blank, and clicking it produces this error.

**Comment by Etheryte** [comment] 2017-05-04 14:09
I can't reproduce the issue with local projects, but it happens constantly when opening the project takes some time (for example, the project is stored in a VM or on a remote filesystem). Steps to reproduce:
 * Install [Project Manager](https://github.com/danielbrodin/atom-project-manager)
 * Set up a project
 * Close all windows
 * Open a new window
 * Open a remotely-stored project from <kbd>CMD</kbd><kbd>CTRL</kbd><kbd>P</kbd>
 * Toggle the blank tree view twice (close & open) <kbd>CMD</kbd><kbd>\\</kbd>
 * Click on the tree view

**Comment by Yajo** [comment] 2017-05-22 09:28
I found exactly the same as you @Etheryte, except that clicking on *Project* fixes nothing.

**Comment by prostart** [comment] 2017-05-24 17:29
Same here. Clicking project fixes nothing.

**Comment by lee-dohm** [comment] 2017-05-24 18:38
If you are having a problem with the [project-plus](https://atom.io/packages/project-plus) or [project-manager](https://atom.io/packages/project-manager) packages, you'll need to file issues on those packages' repos.

**Comment by kaustubh12345** [comment] 2017-05-26 09:23
I found a way to reproduce the issue.

1. Open Atom 
2. Close all the tabs so that entire page is blank.
3. Now Click:- View --> Toggle Tree View
4. You will see empty tree view.
5. Now Open any Project:-  File --> Open --> {Your Folder}
6. The Tree View Is still blank.
7. Again Now Click:- View --> Toggle Tree View. 

You will get the warning with link to this issue.

NOTE:- If You Already Have A Project Open Just Do :- File --> New Window and follow the given steps.

**Comment by beefchimi** [comment] 2017-05-30 00:58
I am getting this issue constantly as of only a few days ago.

**Comment by neverthemachineforever** [comment] 2017-05-30 23:20
I started getting this today. It was triggered by me being curious about the tabs at the top of the tree view, and I right clicked on the tab and clicked "Split up":
<img width="311" alt="screenshot 2017-05-31 11 16 20" src="https://cloud.githubusercontent.com/assets/3262705/26609035/e72f095a-45f2-11e7-8dd6-51bcd228021e.png">

I now can't get the tree view to display anything, and receive the error described in this report.

**Comment by owendall** [comment] 2017-06-01 12:59
Yes, just happened for me as well.

**Comment by AshtonSBradley** [comment] 2017-06-02 08:06
Atom has stopped working altogether

**Comment by lee-dohm** [comment] 2017-06-02 16:16
In the interest of trying to get people help with the problems they're running into, I'm going to lock the conversation on this issue and leave some instructions for people to follow:

1. If you are having a problem with the [project-plus](https://atom.io/packages/project-plus) or [project-manager](https://atom.io/packages/project-manager) packages, you'll need to file issues on those packages' repos. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
1. If you are wanting to report an issue that you are experiencing with Atom that you can reproduce when running in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), please open a new issue and fill in the required template. This way we will have the information we need to help fix things.

Thanks everyone for your passion for and interest in Atom.
