### ISSUE TITLE
Display Problems with arabic numbers

### ISSUE THREAD

**Issue by Eschon** [atom/atom#8251] opened 2015-08-06 13:48 UTC
I have a logstash config with a long line of ruby code

```
code => "if event['appId'] then event['appFamily'] = event['appId'] % 1000; event['deviceFamily'] = (event['appId']/1000).floor.to_i; end; /_(?<cc>[A-Z][A-Z])_?/ =~ event['locale']; if cc then event['countryCode'] = cc; else event['countryCode'] = ''; end; if event['languageShort'] then event['languageShort'] = event['language'].split(/[-|_]/)[0]; end; if event['location'] then loc = {lon: event['location']['longitude'], lat: event['location']['latitude']}; event['location'] = loc; end; if event['timestamp'] then event['timestamp'] = event['timestamp'].split(' ')[0].tr!('٠١٢٣٤٥۶٧٨۹','0123456789'); end; if event['clicks'] then event['clicks'].each{|c| if c['timestamp'] then c['timestamp'] = c['timestamp'].split(' ')[0].tr!('٠١٢٣٤٥۶٧٨۹','0123456789'); end;}end;"
```

Somehow atom has a few problems with the arabic numbers. If I open the file with this line it isn't fully displayed and when I try to insert more code it ends up in the wrong place.

**Comment by Zireael07** [comment] 2015-08-06 14:35
It's not a problem with numbers, it's a problem with long lines. Forgot the issue number atm.

**Comment by Eschon** [comment] 2015-08-06 15:01
The strange thing is everything worked fine until I tried to add the arabic numbers.
Also if I remove about half of the line and leave the part with the arabic numbers in it still has the same problems.

So I guess the arabic numbers are at fault here.

**Comment by 50Wliu** [comment] 2015-08-06 16:28
Then this is a duplicate of #1849 - please subscribe there for updates.

**Closed by 50Wliu** 2015-08-06 16:28 UTC
