### ISSUE TITLE
dev-live-reload package overwriting arbitrary styles

### ISSUE THREAD

**Issue by griffinlqjones** [atom/atom#18472] opened 2018-11-21 09:11 UTC
### Prerequisites
Note: The problem has not been reproduced in Safe Mode for reasons that will become clear in the reproduction steps.
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I've been working on a ui theme called [cream-soda-ui](https://atom.io/themes/cream-soda-ui) and, after publishing an early version of it, issues have been opened up about some color problems making certain elements unreadable. After opening my theme in dev mode everything looked normal until the styles were reloaded. 

Upon styles reloading, either through saving whatever .less file I was working on or choosing "Reload All Styles" from the menu, various styles were arbitrarily overwritten with values whose source I can't isolate. As far as I can tell, only things to do with colors are overwritten. If I restart Atom (again in dev mode), everything goes back to normal until the styles are reloaded by dev-live-reload. 

I've inspected elements before reloading, noted their values (which were as expected compared to the default colors specified in the associated package's styles, settings-view or [deprecation-cop](https://github.com/atom/atom/blob/master/packages/deprecation-cop/styles/deprecation-cop.less) for example). Where the default styles on deprecation-cop's `.deprecation-cop` class are:
```
.deprecation-cop {
  overflow: auto;
  -webkit-flex: 1;
  background-color: @app-background-color;
}
/*
  In cream-soda's case, 
  @base-background-color: #1c0604; (a rather dark brown)
  @app-background-color: darken(@base-background-color, 5%);
*/
```
after reloading, the inspector shows:
```
.deprecation-cop {
  overflow: auto;
  -webkit-flex: 1;
  background-color: #fff !important;
}
```

The problem is, none of my theme's styles use `!important`, none of my ui variables have a value of `#fff`, and the deprecation cop package styles don't use either of these. As mentioned above, the background color of the deprecation cop div should be a rather dark brown but instead it's turned white and the only way to overwrite it is to use an `!important` rule to counter the one that seems to appear out of nowhere.

I have disabled all packages except those bundled with Atom and the problem persists.

The only package I have symlinked to -dev is my theme.

The most substantial, potentially relevant changes made to my Atom install are probably installing atom ide and nuclide, largely to address readability issues brought up by users that were specific to UI elements added by those packages.

I would very much like to make this theme generally better in every respect but I'm extremely hesitant to work on it when I can't be totally sure if I'm unnecessarily fighting with styles that only exist because of a bug. Any wisdom or insight would be most appreciated.

### Steps to Reproduce

1. Open a UI theme-in-progress in Dev Mode such that making changes to the files in the project folder should cause updates to the UI.
2. Open a non-editor tab. I noticed the problems in many places but to keep things simple look try deprecation-cop, GitHub, and settings-view.
3. Click: Packages > Dev Live Reload > Reload All Styles
4. Rub your temples firmly, but not so firmly as to cause any harm.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]
Arbitrary styles are overwritten; typically colors for text, backgrounds, and borders; typically with `#fff` or `#ffffff`.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Electron: 2.0.9
Chrome  : 61.0.3163.100
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 3.7.0b3
git 2.18.0.windows.1
visual studio 2013

#### The Deprecation Cop tab before:
![deprecationcop_onstartup](https://user-images.githubusercontent.com/31920334/48830308-479e9600-ed42-11e8-9a5c-1c91ca8440a5.PNG)
#### After:
![deprecationcop_stylereload](https://user-images.githubusercontent.com/31920334/48830348-600eb080-ed42-11e8-8de7-52c10adb9b2d.PNG)

#### The GitHub tab before:
![gittabinspected_onstartup](https://user-images.githubusercontent.com/31920334/48829827-3b660900-ed41-11e8-9aaf-997aa12b9cd3.PNG)
#### After:
![gittabinspected_stylereload](https://user-images.githubusercontent.com/31920334/48829831-3d2fcc80-ed41-11e8-8bf8-b2f738d0e06b.PNG)

**Comment by thomasjo** [comment] 2018-11-21 12:38
I'm unable to conclusively verify this since my machine is too fast for me to reproduce your issue, but I'm convinced you're hitting some undefined behavior due to invalid ordering of variables in your theme, which can be seen in your [styles/ui-variables.less#L52-L55](https://github.com/griffinlqjones/cream-soda-ui/blob/e3d287d763f146d2f1b452356dd6a1d686e7af8b/styles/ui-variables.less#L52-L55). You're referring a variable before you're defining it's value. The `@"app-background-color` tries to refer to a variable `@base-background-color` before it has been defined in your theme. However, `@base-background-color` already exists in the fallback colors defined in Atom https://github.com/atom/atom/blob/47c0a1451719980a0a6dc3ee31824c42878a8e74/static/variables/ui-variables.less#L25

You should be able to resolve the problem by ensuring your base variables are defined before you use them my moving them up a few lines in your stylesheet. The fact it works sometimes, and othertimes not, comes down to sheer coincidence and depends on CPU speed, and countless other factors. The order of variable definition is crucial and the root cause here.

Since this is seemingly not an error in Atom, I'm going to close this issue.

---
Changing the relevant part of your stylesheet to the following should resolve the problem

``` less
// Base colors
@base-background-color: @cola-dark;
@base-border-color:     darken(@base-background-color, 8%);

// Background colors
@background-color-info:    hsl(208, 100%, 50%);
@background-color-success: hsl(160,  70%, 36%);
@background-color-warning: hsl(32,   60%, 50%);
@background-color-error:   hsl(0,    70%, 50%);

@background-color-highlight: lighten(@base-background-color, 5%);
@background-color-selected:  lighten(@base-background-color, 10%);
@app-background-color:       darken(@base-background-color, 5%);
```

**Closed by thomasjo** 2018-11-21 12:38 UTC

**Comment by griffinlqjones** [comment] 2018-11-21 17:54
@thomasjo You have no idea how much I wish you were right about this but as far as I can tell this isn't the issue.
The screenshot below shows the variable definitions reordered in the fashion you specified and an adjacent panel still getting the wrong `background-color`.
![deprecationcop_stylereload2](https://user-images.githubusercontent.com/31920334/48858955-cc150700-ed8a-11e8-81b8-72760890bce5.PNG)

The same holds true for all the other panels and elements that previously had this problem.

Furthermore, I noted that the ordering of `@base-background-color` relative to `@app-background-color` was just a holdover from the Atom's ui-theme-template, and a similar ordering occurs in atom-dark-ui:
```
line 28:  @base-background-color: lighten(@tool-panel-background-color, 5%);
...
line 37:  @tool-panel-background-color: #1d1f21;
```

The order doesn't appear to be a problem for these themes.

And it's not that it works sometimes and other times it doesn't. It would be more accurate to say, it works on startup until the styles are reloaded and then it stays that way until Atom is restarted whereupon the cycle continues.

**Comment by lee-dohm** [comment] 2018-11-21 22:22
I just attempted to reproduce the problem described using Atom Nightly v1.34.0-nightly17 on macOS 10.14.1 but was unable to. Here's what I tried:

1. Launched Atom in Dev Mode using `atom --dev .` in my local copy of the atom/atom repository
1. Edited one of the One Light UI files to ensure that dev-live-reload works with the themes installed in the atom/atom repo
1. Opened the Settings View and executed "Packages > Dev Live Reload > Reload All Styles" but the suggested problem did not occur
1. Opened the Deprecation Cop view and executed "Packages > Dev Live Reload > Reload All Styles" but the suggested problem did not occur
1. Repeated the two previous steps using One Dark UI and One Dark Syntax themes but could not reproduce the problem

So are you able to reproduce this problem with any other theme than the one you've been working on?

**Comment by Ben3eeE** [comment] 2018-11-21 22:31
Things showing up in the wrong color is known to happen when switching themes. Perhaps it could be related to this issue? https://github.com/atom/atom/issues/9550

**Comment by thomasjo** [comment] 2018-11-22 00:30
@Ben3eeE Yeah, looks like the same problem. Could this by some freak coincidence be a Windows-only bug? I'm not able to reproduce this at all on Linux (using either GNOME or KDE) or macOS 10.14.1.

**Comment by griffinlqjones** [comment] 2018-11-22 01:59
There is a similarity between this and #9550, however instead of falling back to the previous theme's colors, they're apparently falling back to Atom's defined fallback values. It's sort of like certain color rules on certain panels are completely losing any value that might have been set, to the point that the only way to make the color appear is to explicitly target the relevant element.

I don't know why I didn't think to attempt to reproduce the issue with another theme but after opening a fork of the ui-theme-template and making some color changes to the ui-variables, the issue did not occur.

But this is fascinating. I replaced my index.less file and the entire styles folder with copies of the same from the ui-theme-template and this is what happened upon style reload.
![atomstylebreaks_ui-template-styles](https://user-images.githubusercontent.com/31920334/48877164-fc32c900-edcf-11e8-811b-ca7e7337670e.PNG)

So I think this rules out my theme's styles being at issue. Is it possible something about theme, external to the styles, could be involved?
