### ISSUE TITLE
Cannot select text with mouse when running Atom in a VM

### ISSUE THREAD

**Issue by Colinh84** [atom/atom#7704] opened 2015-07-04 03:38 UTC
Installed latest Atom from RPM package on Fedora 21 running in a VirtualBox VM on Windows 8.1, opened a project with default settings and cannot select any text by clicking and dragging with the mouse.

**Comment by mnquintana** [comment] 2015-07-04 03:45
This is a duplicate of https://github.com/atom/atom/issues/6306 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-04 03:45 UTC
Labels: duplicate
