### ISSUE TITLE
vertical scrollbar bug in windows 7

### ISSUE THREAD

**Issue by wlwl2** [atom/atom#11889] opened 2016-06-03 09:32 UTC
Sometimes, the scroll box on atom in windows 7 does not reach the bottom of the scroll bar and does not touch the bottom arrow of the scroll bar. When this happens you can also drag the scroll box by dragging the empty space below it. I tried this on v1.8.0-beta4 and v1.7.4. I thought that uninstalling 1.7.4 and clearing atom folders, and then installing the beta would fix it but it didn't.
![scroll-bug](https://cloud.githubusercontent.com/assets/11145398/15774820/07cf7b18-29b1-11e6-8074-4259494c35bd.PNG)

**Comment by Ben3eeE** [comment] 2016-06-03 10:31
This is a duplicate of https://github.com/atom/atom/issues/11484

**Comment by wlwl2** [comment] 2016-06-03 14:53
Thanks! I guess I'll just downgrade it for now.

**Closed** 2016-06-03 16:13 UTC
