### ISSUE TITLE
High Energy Impact

### ISSUE THREAD

**Issue by vjancik** [atom/atom#11660] opened 2016-04-30 11:52 UTC
### Description

Atom uses **8-10 times** as much energy as Chrome on average. I consistently get **Avg Energy Impact** from 180 to 250. Are we aware of this, and if we are, are we addressing it?

Can I profile it somehow to find out which components are responsible the most?

![screen shot 2016-04-30 at 1 47 36 pm](https://cloud.githubusercontent.com/assets/4226865/14935671/47f0b42e-0eda-11e6-966e-f10e45489c9a.png)

### Versions

Atom
```
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

Apm
```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4
```

**Comment by bj7** [comment] 2016-04-30 15:04
I think it depends mainly on what you're using Atom for and how many files you have open at a time vs Chrome with how many browser tabs you have open...If Atom has linters installed and you're dealing with large files or many files, you could have significant energy consumption; just as if you had half a dozen Chrome tabs open, each running javascript hungry web apps. 

![image](https://cloud.githubusercontent.com/assets/1395096/14936772/e5ad2c3c-0ec2-11e6-957b-a271b3cb545e.png)

If you could supply usage statistics of Atom and Chrome over a period of time, indicating which each was doing, plugins installed, etc, I think that would help clarify this issue, and point us in the right direction.

**Comment by vjancik** [comment] 2016-04-30 15:11
I have these packages installed: https://gist.github.com/vjancik/4e87eec3d2ba4e6dbbfa933f638d89f4#file-packages-json
And yes I use a linter, but I get the crazy high energy consumption even when I don't.
As for Chrome, I use Chrome to read documentation and such, and have over 50 tabs open.
Under 10 tabs in Atom, only one window, and my linters are configured to run only on current file.

**Comment by 50Wliu** [comment] 2016-04-30 16:18
@vjancik Can you see if the high energy impact still happens in safe mode (`atom --safe`)?  Thanks.

**Comment by Tobias-Conrad** [comment] 2016-04-30 20:01
Same here.: average power consumption 43 (Atom) to 23 (chrome). 10.11.4
[Analyse of „Atom“.txt](https://github.com/atom/atom/files/243794/Analyse.of.Atom.txt)
Call this bug atomic meltdown.

**Comment by 50Wliu** [comment] 2016-04-30 20:25
@Tobias-Conrad Can you follow my instructions in the comment above yours and report back?

**Comment by Tobias-Conrad** [comment] 2016-04-30 20:45
@50Wliu i am not able to use the terminal
problem is not all the time, i would gues it is connected with unsaved tabs.

**Comment by bj7** [comment] 2016-05-01 00:14
Is this during active use or idle? I currently have two different projects open, each with many files, and I haven't touched it all day, but my current highest energy user is Slack due to background updates. 

I will make edits to all my files, and not save any of them and measure the energy consumption so as to help determine the cause.

**Comment by lee-dohm** [comment] 2016-05-01 05:29
This is another facet of https://github.com/atom/atom/issues/1827. Yes, we know that Atom consumes a lot of resources, more than it should in some cases. Yes, we are working on it. Performance is a high priority for us.

[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). Since this is an Issue that doesn't have a specific goal, I'm going to have to close it. If you want to discuss the problem until specific excesses can be tracked down, please use [Discuss, the official Atom message board.](https://discuss.atom.io)

**Closed by lee-dohm** 2016-05-01 05:29 UTC
Labels: more-information-needed

**Comment by Tobias-Conrad** [comment] 2016-05-01 05:52
I work mobile, if you close this issues and did not find a solution for the #1827 ticket started 2 years ago, you are failing in my eyes.

**Comment by vjancik** [comment] 2016-05-01 13:01
I don't need to use `--safe` mode, I am fairly confident it's the extra packages. And yes it only happens when I'm using the editor, it's passive energy consumption is almost zero. Or when some process in Atom is running in the background.

But this needs to be addressed none the less, because people are using these plugins, that may or may not have rampant JS events / handlers and they reflect on the overall energy consumption of Atom.

So, here's some solutions to consider:

1. Either separate each installed package (outside of standard Atom ones e.g.) into it's own helper, so the user can easily see which package is causing the high energy consumption, and decide if they want to remove that package.
2. Or implement some sort of resource limiter runtime atop all of the plugins. Which would let the user / Atom itself monitor & throttle CPU / Memory usage of particular packages.

I know 2. is easier said than done because it's all JS, but it shouldn't be impossible.

**Comment by 50Wliu** [comment] 2016-05-01 17:02
@Tobias-Conrad There is no one "solution" for #1827.  We are constantly working on improving performance, as you can see in the release notes.  For example, we just merged a PR that improves performance when clicking on long lines.

@vjancik There's a feature request open to add a "task manager" to Atom to see which packages are using the most resources: you can subscribe to it [here](https://github.com/atom/atom/issues/4168).
