### ISSUE TITLE
My icons break when setting Atom to be a default program for files

### ISSUE THREAD

**Issue by OHQSaucey** [atom/atom#13100] opened 2016-10-29 21:04 UTC
### Prerequisites

* [ x ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ x ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ x ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ x ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ x ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When ever I associate Atom to a specific file, for instance a .txt file, the default icon for that file is broken. Any file I tell to make Atom its default progam the icon for that file shows up broken. When ever I change the default program to notepad, the icon changes to notepads associated file icon. The icon for notepad associated files show up fine and do not appear broken. I have uninstalled Atom and reinstalled. The issue still persists.

I do not remember exactly when this started happening, but it was a while back. I have always kept Atom up to date.

### Steps to Reproduce

1. Set Atom as the default file viewer.
2. Watch all your icons break before your very eyes.

- Image: http://i.imgur.com/MvUCBFT.gif

**Expected behavior:** For the files to display the Atom icon like it use to.

**Actual behavior:** Displays nothing but a broken icon instead.

### Versions

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

OS: Windows 7 x64 Ultimate SP1 (6.1, Build 7601)

**Comment by Ben3eeE** [comment] 2016-10-29 21:23
Thanks for contributing! This is a duplicate of https://github.com/atom/atom/issues/12974 and has been fixed in Atom 1.12 where the files will use the new icon.

**Closed by Ben3eeE** 2016-10-29 21:23 UTC
