### ISSUE TITLE
Selects are rendered unusable with HiDPI scaling

### ISSUE THREAD

**Issue by robhagemans** [atom/atom#7502] opened 2015-06-28 08:46 UTC
#### Summary
The theme chooser does not appear to work on my system. I cannot select a theme.

#### Setup
Ubuntu 15.04 with atom 1.0.0 amd64 freshly installed from .deb package. 

#### Observed behaviour
Themes show up in the list of Core Themes and Installed Themes. However, when I click the drop-down selectors for UI Theme and Syntax Theme, they only show an empty white box, with 'One Dark' remaining selected.
![screenshot from 2015-06-28 09 53 40](https://cloud.githubusercontent.com/assets/7723154/8395764/8a14958c-1d7c-11e5-91b7-4b53dd41e2b0.png)

#### Expected behaviour
I would have expected the names of installed themes to appear in the drop-down box so that I could select another theme.

#### Notes
Not sure if this is relevant or a separate bug, but searching for themes using the 'filter themes by name' box does not return any themes.

**Comment by batjko** [comment] 2015-06-28 08:55
Just for added detail, could you add a screenshot of what it looks like when you click the dropdown for a theme and only get that white box?

**Comment by robhagemans** [comment] 2015-06-28 08:59
Hi batjko, here's a screenshot:

![screenshot from 2015-06-28 09 53 40](https://cloud.githubusercontent.com/assets/7723154/8395758/4db0fa04-1d7c-11e5-8dd1-94cbe84e842b.png)

**Comment by patrys** [comment] 2015-06-28 09:41
Seems like a styling issue where white text gets displayed on a white background?

**Comment by robhagemans** [comment] 2015-06-28 10:02
Hi @patrys, I tried if I could select anything in the white box, but if I click on it it simply disappears and the default theme remains selected. So I'd say it's not (only) a styling issue.

**Comment by robhagemans** [comment] 2015-06-28 10:07
Further info: the same issue also happens on other drop-down selectors. For example, I cannot change the Tab Length setting as it shows an empty white box. 

The Encoding setting looks as follows:
![screenshot from 2015-06-28 11 06 35](https://cloud.githubusercontent.com/assets/7723154/8395911/dff8af2a-1d85-11e5-9c9d-4b4523effbeb.png)

**Comment by robhagemans** [comment] 2015-06-28 10:11
I've traced the issue to a screen setting (All Settings/Screen Display/Scale for menu and title bars). I'm using Unity desktop on a high-dpi screen with display scaling factor 2x to make Unity usable. 

If I set the scaling factor to 1x, the issue disappears.

**Comment by batjko** [comment] 2015-06-28 10:29
Ok, then this seems to a duplicate of https://github.com/atom/atom/issues/5130.

Note, 5130 was closed in favor of a different ticket, which I don't think lends itself to this case, though.

**Comment by robhagemans** [comment] 2015-06-28 10:33
OK - if it helps, I don't have any issues with the window menus as described in #5130, they are all the correct size. Most of the Atom UI actually works very well with the scale setting: all elements have a good usable size (unlike many native GTK apps!)

**Comment by batjko** [comment] 2015-06-28 10:36
Yes, but the issue seems to be the scaling under certain HiPDI settings, which messes with a bunch of dynamic views, as well as menus.

**Comment by robhagemans** [comment] 2015-06-28 10:40
Further info: `--force-device-scale-factor=1` does not make this issue go away.

@batjko, agreed that it seems to be a hiDPI scaling issue, in common with the linked bugs - you should merge and close as you see fit of course, I just wanted to give as much info regarding the differences with those specific bugs.

**Comment by batjko** [comment] 2015-06-28 10:51
Yup, and thanks for doing so. Any additional info will be helpful to the core devs.

**Comment by mnquintana** [comment] 2015-06-28 11:59
@robhagemans Thanks for the updates! I think I'm going to leave this open since this is a different "symptom" of HiDPI scaling issues than https://github.com/atom/atom/issues/3826, even if it ultimately has the same cause. Hopefully it will also be fixed when Atom upgrades to a version of Electron built on Chrome 43.

**Comment by robhagemans** [comment] 2015-06-28 12:28
Cheers! Let me know if there are further things you want me to find out about this issue.

**Closed** 2015-09-08 15:41 UTC
Labels: blocked, bug, linux
