### ISSUE TITLE
Pop-up message/warning when trying to open large files...

### ISSUE THREAD

**Issue by emveeoh** [atom/atom#11028] opened 2016-03-02 05:25 UTC
It would be helpful if Atom would show a pop-up message requesting confirmation upon opening large files.

I'm sure that I'm not the only one that has accidentally clicked on a very large file (mp3, mp4, etc) and watched Atom nearly halt while trying to load it.

Ideally, Atom would read the file size of the item to open and would pop-up a confirmation request for any file past a certain size. 

Thank you!

**Comment by Zireael07** [comment] 2016-03-02 13:46
Duplicate issue, even though I can't find the other one atm.

**Comment by zokker13** [comment] 2016-03-05 10:16
Atom 1.5.4 throws out a message that the file is too large and processing it would end in a slow Atom.

What kind of file do you try to parse?
What is your atom version?

**Comment by mnquintana** [comment] 2016-03-05 22:08
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/10086 though, so I'm going to close this out in favor of that issue.

**Closed by mnquintana** 2016-03-05 22:08 UTC
