### ISSUE TITLE
Cannot block comment code that starts with a comment

### ISSUE THREAD

**Issue by eddiemonge** [atom/atom#8512] opened 2015-08-26 00:45 UTC
Selecting all the following code and then trying to comment it out does nothing.  This only affects languages that specify a comment with a start and end component (eg CSS, HTML).  I would expect it to comment out the following css code:

``` css
/* General Overrides */

.codelab code.prettyprint {
  color: white; /* default color in case offline */
}
```

ref https://github.com/atom/language-css/issues/39

**Comment by mnquintana** [comment] 2015-08-26 00:54
I can reproduce this with CSS, but not with any grammar that uses single line comments denoted by a "start" but not an "end" (e.g. JS).

**Comment by eddiemonge** [comment] 2015-08-26 01:00
What about JS using `/* */` syntax?

**Comment by 50Wliu** [comment] 2015-08-26 02:04
JS does not repro this bug since it comments out code using `//`.  HTML however does.

**Comment by as-cii** [comment] 2015-08-27 15:30
I have checked out this behavior on Sublime Text and the result is kinda correct, but still weird:

![sublime](https://cloud.githubusercontent.com/assets/482957/9524749/d8b64300-4ce0-11e5-8a7f-7adc80b0cbe7.gif)

As you can see, code is not actually being commented out. Although I agree that not responding to the user action is bizarre, would the behavior shown in the screenshot be acceptable for Atom?

/cc: @atom/feedback

**Comment by lee-dohm** [comment] 2015-08-27 16:09
In any language that I know, block comments don't nest. So any selection that contains one or more block comments that is requested to be block commented cannot easily be honored. There are two solutions to *properly* block commenting the above example. Either:

```css
/**//* General Overrides *//*

.codelab code.prettyprint {
  color: white; *//* default color in case offline *//*
}*/
```

Or if we want to special case the "starting with a comment" situation:

```css
/* General Overrides */
/*
.codelab code.prettyprint {
  color: white; *//* default color in case offline *//*
}*/
```

There may be a number of other edge cases that I'm not seeing right now.

**Comment by eddiemonge** [comment] 2017-08-29 00:57
Further activity

**Comment by lee-dohm** [comment] 2017-08-29 01:06
This isn't something that we're going to spend time working on a fix for because it just has too many edge cases and it isn't clear what the right general solution is. If someone wants to take a stab at this, we would be open to reviewing a well-written pull request but it would have to be well-researched, documented, result in the entire selected region commented out, and include tests. I'm going to label this `help-wanted` and close it since the Atom maintainer team isn't going to be working on it.

Thanks for the ping @eddiemonge.

**Closed by lee-dohm** 2017-08-29 01:06 UTC
Labels: bug
