### ISSUE TITLE
Editor freeze on opening html file

### ISSUE THREAD

**Issue by sumanparia** [atom/atom#6830] opened 2015-05-17 04:32 UTC
Lenovo G550. 4gb ram. Intel graphics.
Atom 0.999.
Opening small html 41kb. On opening html editor freeze for for few minutes and showing one popup()
![error](https://cloud.githubusercontent.com/assets/6039696/7669052/b1b4188c-fc7b-11e4-88e6-cf2e8f156344.png)

**Comment by izuzak** [comment] 2015-05-27 13:59
@sumanparia Can you reproduce the problem in the latest version of Atom (0.201.0) in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If so, can you share a link to the file in question? Does the file perhaps have a very long line in it?

**Comment by izuzak** [comment] 2015-09-10 16:52
Closing since no information about reproducing this was provided in over 3 months, and I'm guessing this is a duplicate of https://github.com/atom/atom/issues/979. @sumanparia If you can still reproduce this with Atom 1.0.11 -- it would be great if you could provide the file which causes this for you.

**Closed by izuzak** 2015-09-10 16:52 UTC
Labels: more-information-needed
