### ISSUE TITLE
Zooming moves position in document

### ISSUE THREAD

**Issue by lczech** [atom/atom#7455] opened 2015-06-26 12:19 UTC
Just upgraded to atom 1.0 on Ubuntu 14.04, and realized that the zooming feature (`crtl +` either `+` or `-`, or using `ctrl` and the mouse wheel) changes font size, but also jumps to a different position in the document.

To me it looks like the position is maintained in form of pixels from the top of the document, but when for example zooming out (`crtl + -`), more text fits within those pixels, so that I end up way down in my document.

Would be cooler if instead of the pixel from top the current line was maintained.

**Comment by mnquintana** [comment] 2015-06-26 12:24
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/4084 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-26 12:24 UTC
