### ISSUE TITLE
Splitting/Closing panes results in crash

### ISSUE THREAD

**Issue by j-moeller** [atom/atom#10903] opened 2016-02-19 12:31 UTC
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [?] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

```
Error:Pane has been destroyed
    at Pane.module.exports.Pane.activate (C:\Users\XXXXXX\Atom\resources\app.asar\src\pane.js:631:15)
    at Pane.module.exports.Pane.focus (C:\Users\XXXXXX\Atom\resources\app.asar\src\pane.js:207:21)
    at atom-pane.<anonymous> (C:\Users\XXXXXX\Atom\resources\app.asar\src\pane-element.js:50:23)
```

### Steps to Reproduce

1. Start with only one pane
2. On the pane: Right click > Split Left
3. On the right pane: Right click > Split Down
4. On the left pane: Right click > Close Pane
5. On the upper pane: Right click > Split Down
6. On the lower pane: Right click > Close Pane

**Expected behavior:** [What you expected to happen]

1. After step 5: There are supposed to be three horizontal panes
2. After step 6: There are supposed to be two horizontal panes (the two upper ones)

**Actual behavior:** [What actually happened]

1. After step 5: There are (still) only two panes
2. After step 6: The pane is not closed properly (the tab bar remains or the "empty" background is shown)

### Version

1.5.3 (atom-windows.zip) on Windows 7

**Comment by robinki** [comment] 2016-02-19 13:07
I can confirm this error occurs on version 1.5.3 on Windows 7.

**Comment by arthur-e** [comment] 2016-02-25 19:43
Reproduced on 1.5.3 on Ubuntu GNU/Linux, 14.04-3, 64-bit, in safe mode. Atom did not crash but the "Actual behavior" was the same.

**Comment by 50Wliu** [comment] 2016-02-25 20:35
I'm currently looking into this.

**Comment by 50Wliu** [comment] 2016-02-26 00:04
So after some investigation here's some info I discovered:
The problems start occurring after closing the original pane, step 4.  Any new panes (including left, right, top, whatever) you try to add do not show up, but they *still are created*, just not added to the DOM (you can verify this by logging `atom.workspace.getPanes()` in the dev tools console, then looking at the current element structure).  Reloading Atom will cause the issue to correct itself.  Closing both panes will cause the third hidden one to suddenly show up.

Now all that's left to do is figure out *why* that's happening...

Here's my repro steps.
1. Start with one file in one pane.
2. Split the file in any direction.
3. Split any of the two file in a **perpendicular** direction to the other two panes (so if the first split was a horizontal one this one has to be vertical).
4. Close the pane that only has one tab in it.
5. Attempting to further split a pane in any direction in either of the two panes will not show the new pane.
6. Close one of the panes through the `Close Pane` command.
7. Note that the pane was not destroyed.
8. Attempt to close the pane by closing the blank tab and observe this error.

**Comment by 50Wliu** [comment] 2016-02-26 03:18
More info:
When in this setup, after closing the original pane (step 4), the subscriptions to `pane-axis-element.coffee` get disposed *twice*, compared to just once when in a parallel setup.  What ends up happening is we seem to also dispose of the subscriptions of the two remaining panes instead of just the closed one, so that we miss the `onDidAddChild` callback and don't get to add the new split pane to the DOM.

This could just be a red herring; I'm not confident that different subscriptions are being disposed each time.  I'll continue looking into it tomorrow.

**Comment by 50Wliu** [comment] 2016-02-27 01:28
I can now confirm that the subscriptions are being disposed for both the destroyed pane and the remaining panes when this bug occurs.  Since this only happens with the perpendicular pane structure my intuition tells me that there's a bug somewhere in `replaceChild` and friends.

**Closed** 2016-03-29 07:46 UTC
Labels: atom, bug, uncaught-exception
