### ISSUE TITLE
vim-mode o to open new line throws: Uncaught Error: No screen line exists when converting buffer row to screen row 

### ISSUE THREAD

**Issue by mikelyons** [atom/atom#4149] opened 2014-11-11 18:21 UTC
Using vim-mode, `o` usually opens a new line below the cursor but instead I am getting:

`Uncaught Error: No screen line exists when converting buffer row to screen row`

This happened on one tab only and I am not sure steps to reproduce.

**Comment by csnover** [comment] 2015-03-08 09:06
This is the issue that Atom is pointing me to when pasting a large chunk of content into the editor. Atom 0.186.0.

```
Error: No screen line exists when converting buffer row to screen row
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1012:17)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/marker.js:211:33)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app/src/marker.js:275:36)
  at /Applications/Atom.app/Contents/Resources/app/src/marker.js:56:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.resumeChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:559:24)
  at MarkerManager.module.exports.MarkerManager.resumeChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-manager.js:235:30)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:597:15)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:74:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.abortTransaction (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:165:24)
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:122:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1215:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:298:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)
```

Once this happens Atom will either not save the file again, or will save old data to disk. I’ve had to restart my work several times tonight because of this bug.

**Comment by Aedaeum** [comment] 2015-05-10 21:50
This may also have to do with this issue I just made: https://github.com/TypeStrong/atom-typescript/issues/339

**Comment by danqing** [comment] 2015-05-20 06:36
Just ran into possibly this issue with v0.200.

Was writing a Go function at the end of a pretty short file:

```go
func (s *Set) StoreWithoutReload() error {}
```

Atom autocompleted the `{}`, but when I try to press Enter between the `{}`'s, this error showed up.

Stack trace:

```
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:683
Hide Stack Trace
Error: No screen line exists when converting buffer row to screen row
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1030:17)
    at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:174:33)
    at new Marker (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:34:41)
    at DisplayBuffer.module.exports.DisplayBuffer.getMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1248:20)
    at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkerCreated (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1567:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.markerCreated (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1253:20)
    at MarkerStore.module.exports.MarkerStore.createMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:313:21)
    at MarkerStore.module.exports.MarkerStore.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:148:19)
    at TextBuffer.module.exports.TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:604:31)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1280:41)
```

**Comment by izuzak** [comment] 2015-05-26 11:58
@danqing I just tried reproducing that but failed. Are you able to reproduce this reliably? Do you have any community packages installed in Atom?

**Comment by danqing** [comment] 2015-05-26 13:47
Haven't see it in v0.201 but it did happen a lot in v0.200.

**Comment by davezuko** [comment] 2015-05-26 15:37
I just started getting this error in 0.201. Seems to happen whenever there's a set of braces at the end of a file.

```js
if (typeof exports === 'object') {

}
```

Stack trace:

```
/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1047
Hide Stack Trace
Error: No screen line exists when converting buffer row to screen row
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1047:17)
    at Marker.module.exports.Marker.getTailScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:192:33)
    at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:240:36)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:45:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:380:27)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:335:12)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:136:19)
    at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:170:32)
    at Marker.module.exports.Marker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:180:19)
```

**Comment by cdipaolo** [comment] 2015-05-28 00:36
Having the error rendering HTML with Angular syntax.

```html
<div class="thing-post row-no-padding">
  <div class="container">
    <div class="post-image">
      <img class="center-image" style="padding-bottom:20px;" ng-src="{{post.thing_url}}"></img>
    </div>
  </div>

  <div ng-if="!abbreviate" class="header" ng-click="detail(post.thing)">
    <p class="kitchen-name">{{post.thing.name}}</p>
    <p class="author">{{post.user.thing}} {{post.user.thing}}</p>
    <p class="timestamp">{{post.timestamp}}</p>
  </div>

  <div ng-if="abbreviate" class="short-header" ng-click="detail(post.thing)">
    <p class="author">{{post.user.thing}} {{post.user.thing}}</p>
    <p class="timestamp">{{post.timestamp}}</p>
  </div>

  <div class="post-text">
    <p>{{post.post_text}}</p>
  </div>
</div>
```

I did _not_ have the error before I moved the 'header' and 'short-header' class divs below the 'container' class div (were previously above.) This worked: 

```html
<div class="thing-post row-no-padding">
  <div ng-if="!abbreviate" class="header" ng-click="detail(post.thing)">
    <p class="kitchen-name">{{post.thing.name}}</p>
    <p class="author">{{post.user.thing}} {{post.user.thing}}</p>
    <p class="timestamp">{{post.timestamp}}</p>
  </div>

  <div ng-if="abbreviate" class="short-header" ng-click="detail(post.thing)">
    <p class="author">{{post.user.thing}} {{post.user.thing}}</p>
    <p class="timestamp">{{post.timestamp}}</p>
  </div>

  <div class="container">
    <div class="post-image">
      <img class="center-image" style="padding-bottom:20px;" ng-src="{{post.thing_url}}"></img>
    </div>
  </div>

  <div class="post-text">
    <p>{{post.post_text}}</p>
  </div>
</div>
```

**Comment by Skulli** [comment] 2015-05-28 11:17
Just got the error with 201 when i was working on a haml file

**Comment by izuzak** [comment] 2015-05-29 12:03
@davezuko I'm unable to reproduce the problem using your instructions. Can you still reproduce it if you start Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? I'm guessing it's related to a package somehow, which this would confirm, since you are able to reliably reproduce the issue with the snippet you mentioned. Also, can you share the list of packages you have installed?

@cdipaolo @Skulli Can any of you reliably reproduce the problem as well, and share the exact steps which reproduce it? And do you see the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by Skulli** [comment] 2015-05-29 14:19
Sorry, cant reproduce it (happened on MAC). I was creating a new haml file in split view and copying some haml code (yeah code smell ;)). Somehow the error popped up but disappeared after saving the file.

**Comment by davezuko** [comment] 2015-05-29 14:22
@izuzak I haven't been able to reproduce it since reporting the issue... if it reoccurs I'll try to boot in safe mode and pinpoint a potential package.

**Comment by izuzak** [comment] 2015-05-29 14:26
Cool, closing this again until we get more info. Also gonna cc @nathansobo just so that he's aware we're digging into this stuff, I know he likes to be aware of these things around rendering.

**Closed by izuzak** 2015-05-29 14:26 UTC
Labels: more-information-needed

**Comment by cdipaolo** [comment] 2015-05-30 02:21
@izuzak Also haven't been able to reproduce. Though it did happen again within an hour of the first time. Both times I was cutting a block of HTML and pasting it to another portion of the screen. Hasn't happened before then or since then but will look further if it happens again.
