### ISSUE TITLE
Cmd+up/down doesn't work with multi-line select

### ISSUE THREAD

**Issue by devonestes** [atom/atom#7669] opened 2015-07-03 01:58 UTC
When trying to select multiple lines that all have a particular string with cmd+D and move them up or down within the document, Atom will select the lines properly, but when trying to move them it de-selects the additional lines and only moves the originally selected line. If you select multiple lines with the mouse or with Cmd+L it works just fine, and It still deletes multiple lines properly when selected with cmd+D - it's just moving lines that fails. I've taken a screen capture of the bug to illustrate what happens, which is viewable here: https://slack-files.com/T024TD89T-F075EUW8K-1e3ac80187

**Comment by mnquintana** [comment] 2015-07-03 05:20
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/2470 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-03 05:20 UTC
