### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.21.1\res...

### ISSUE THREAD

**Issue by FLPellicer** [atom/atom#15879] opened 2017-10-12 20:28 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Lenovo\AppData\Local\atom\app-1.21.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\Lenovo\AppData\Local\atom\app-1.21.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:46.6.0 core:backspace (input.hidden-input)
     -1:45.5.0 core:move-right (input.hidden-input)
  6x -1:45.3.0 core:backspace (input.hidden-input)
     -0:09.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autocomplete-corona 1.1.4 
color-picker 2.2.5 
highlight-selected 0.13.1 
language-lua 0.9.11 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
```

**Comment by rsese** [comment] 2017-10-12 20:42
I think this might be a duplicate of recent issues like https://github.com/atom/atom/issues/15722.  If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled.  If you don't have any anti-virus software, let me know.

**Closed by rsese** 2017-10-12 20:42 UTC

**Comment by FLPellicer** [comment] 2017-10-12 23:05
I actually didn't expect a responde so quick! Didn't know what I was
getting into apparently haha.

I do have anti virus software (Nod32), however, I "solved" the issue by
closing Atom and opening up the foldee I was working on manually. That
seemed to do it.

**Comment by artem108** [comment] 2017-10-13 07:04
Cntrl+Shift+I in Atom -> found 'atom-notification' -> display: none = done
))

**Comment by rsese** [comment] 2017-10-13 19:51
> I do have anti virus software (Nod32), however, I "solved" the issue by
> closing Atom and opening up the foldee I was working on manually. That
> seemed to do it.

Yeah we've had a number of relatively recent reports lately with anti-virus false positives and keyboard-layout-manager.node in particular.  Glad you have things working though :+1:

**Comment by meetzaveri** [comment] 2017-10-14 05:01
@artem108 That solutions works. But is that a permanent solution or maybe I can say as temporary aid?

**Comment by artem108** [comment] 2017-10-14 08:41
@meetzaveri It was a joke, I do not think it's a good way, but it's just cool that it worked.
In fact, I have reinstalled Arom solved this problem

**Comment by theubaya** [comment] 2017-10-23 03:22
i have reinstalled Atom and solved this problem
