### ISSUE TITLE
Dependency libcurl.so.4(CURL_OPENSSL_3)(64bit) cannot be found in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by guoyunhe** [atom/atom#18230] opened 2018-10-14 16:51 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Install *.rpm package on openSUSE Tumbleweed failed with unsatisfied dependency libcurl.so.4(CURL_OPENSSL_3)(64bit).

### Steps to Reproduce

1. Download *.rpm package from atom.io (I downloaded is version 1.31.2)
2. Install atom.x86_64.rpm
3. Follow YaST installer instructions.

**Expected behavior:** 

Should be installed without errors.

**Actual behavior:**

Package manager prevent installation because dependency cannot be found: libcurl.so.4(CURL_OPENSSL_3)(64bit)

**Reproduces how often:**

Always

### Versions

Atom 1.32.2 (rpm)

openSUSE Tumbleweed 20181009

curl 7.61.1 (x86_64-suse-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.0h zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.3/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink

**Comment by rsese** [comment] 2018-10-15 01:58
Thanks for the report!  

I think this may be a duplicate of https://github.com/atom/github/issues/848 but just to clarify this part:

> Follow YaST installer instructions.

I haven't used openSuse so I'm not sure if it's the same thing but does it make any difference if you install by following the installation documentation?

https://flight-manual.atom.io/getting-started/sections/installing-atom/#suse-zypp

**Closed** 2018-11-12 02:30 UTC
Labels: linux, more-information-needed
