### ISSUE TITLE
Atom should provide a tabbed panel system

### ISSUE THREAD

**Issue by xpol** [atom/atom#11120] opened 2016-03-10 03:30 UTC
Currently atom does not have a panel (tool window) layout manager ( ref docs https://atom.io/docs/api/v1.5.4/Panel ).

I use follow packages they all provide a panel:
- https://github.com/noseglid/atom-build by @noseglid.
- https://github.com/jeremyramin/terminal-plus by @jeremyramin
- And there is also build-in search package.

When they show up together, I got follow panels stacked and takes up too much space of my screen (Picture 1).

How about a panel layout manager like android studio does (Picture 2), make every panel has its proper place, the features include:
1. Stack panels in tabs.
2. Have at least left and right group of panel tabs (like android studio does in Picture 2).
3. Drag move for manually manage panel group.
4. Panel size, group ... should be saved across atom sessions.

Picture 1: Atom panels are not managed

![panels](https://cloud.githubusercontent.com/assets/20248/13658366/4a238d30-e6b1-11e5-8e3e-813b9feff3d1.png)

Picture 2: Android Studio panels are managed well

![android-studio-panels](https://cloud.githubusercontent.com/assets/20248/13658490/53a2976a-e6b2-11e5-9cd6-dfdc428ea39b.png)

**Comment by sdinesh86** [comment] 2016-03-16 07:40
+1

**Comment by alflanagan** [comment] 2017-03-29 16:53
This seems to be a duplicate of #10897.

**Comment by 50Wliu** [comment] 2017-03-31 02:05
I'm actually going to close #10897 in favor of this issue as this one seems more popular.

**Comment by 50Wliu** [comment] 2017-04-13 01:28
I do believe that something like this is possible in the new Docks system.  See http://flight-manual.atom.io/hacking-atom/sections/package-active-editor-info/ and #13977 for more information.

**Closed by 50Wliu** 2017-04-13 01:28 UTC
Labels: enhancement
