### ISSUE TITLE
Atom corrupts open file on unplanned system shutdown.

### ISSUE THREAD

**Issue by FLamparski** [atom/atom#13658] opened 2017-01-19 11:09 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom will corrupt the currently open and focused file when restarted after an unplanned poweroff.

### Steps to Reproduce

1. Open a file in Atom. (I usually open atom from a folder in command line like `~/project $ atom .`)
2. Make some changes.
3. Save them(?)
4. Pull out the power cord/hard-shutdown the computer 😱
5. Reboot, open Atom.

**Expected behavior:** [What you expect to happen]

The file that was being edited appears undamaged, modulo any changes that may not have been flushed to disk.

**Actual behavior:** [What actually happens]

Lovely lovely soup of random bytes everywhere, gleefully persisted to disk. Hope you were using Git so you can roll back to the latest commit/stash (you do commit often, right?).

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time I had to hard-reboot the computer while Atom was open.

### Versions

`atom --version`:

```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

`apm --version`:

```
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12+
git 2.9.3
```

### Additional Information

Using Ubuntu 16.10 (`uname -a`: `Linux serenity 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`)

I'll try to update this report as I gather more information.

**Comment by FLamparski** [comment] 2017-01-19 11:17
Bug just reproduced in Atom safe mode. I created a new file which contained a string "The foo is bar and the bar is foo", then hard-rebooted my machine. For a comparison, I did the same thing with Gedit. I saved both files before the poweroff.

Atom: The strong "The foo is bar and the bar is foo" flashed on the screen for a split second, then this appeared:

![image showing corruption](https://cloud.githubusercontent.com/assets/912935/22104720/8c5e0516-de38-11e6-8fe9-eea5900d5377.png)

Mind you, Gedit did not fare much better - upon starting it, the file was truncated to 0 bytes.

Save means save. Please make sure you flush to disk when you save a file, and make provisions for something like this happening.

**Comment by 50Wliu** [comment] 2017-01-19 15:59
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #11406. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-01-19 15:59 UTC
