### ISSUE TITLE
Incorrect version shown on about page before update

### ISSUE THREAD

**Issue by matiaskorhonen** [atom/atom#13355] opened 2016-11-29 09:09 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

For some reason the wrong version number is shown for updates on the atom About page prior to restarting and updating. I've observed this through the last several Atom updates but I'm not sure when this started to happen.

I don't know if it's possible to reproduce this in safe mode since quitting and restarting Atom will trigger the update process, right?

**Before update:**

<img width="548" alt="2016-11-29 11-01-36 l6vh3" src="https://cloud.githubusercontent.com/assets/43314/20703148/584244b4-b623-11e6-8c9f-f28b284453ef.png">

**After clicking “Restart and install”:**

<img width="530" alt="2016-11-29 11-03-22 bi1p9" src="https://cloud.githubusercontent.com/assets/43314/20703177/732bd57e-b623-11e6-820d-8e24c234c7f3.png">

### Steps to Reproduce

1. The update squirrel appears
2. Click it
3. The about page opens

**Expected behavior:**

The about page shows the current version and the update version

**Actual behavior:**

The current version is shown twice, the update version is not shown

### Versions

```sh
$ atom --version
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.2
```

Running macOS Sierra 10.12.1

**Comment by Ben3eeE** [comment] 2016-11-29 09:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/about/issues/44. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-11-29 09:12 UTC
