### ISSUE TITLE
the editor has crashed

### ISSUE THREAD

**Issue by zyl54586** [atom/atom#11992] opened 2016-06-16 14:45 UTC
I opened a 100MB file, the editor display "atom will be unresponsive during the loading of very large files", then I clicked "proceed", the editor display "the editor has crashed"

**Comment by trusktr** [comment] 2016-06-28 17:52
Tracking all these large-file issues in #12065.

**Comment by Zireael07** [comment] 2016-06-28 18:43
"Large file" != "long line". And there's already an issue for large files.

**Comment by mnquintana** [comment] 2016-06-29 00:43
This seems like a duplicate of https://github.com/atom/atom/issues/8864 – let's keep the discussion going there.

**Closed by mnquintana** 2016-06-29 00:43 UTC

**Comment by krabbypattified** [comment] 2017-03-05 18:13
Hello from issue #12065. Atom Beta should fix this for many people.
