### ISSUE TITLE
charset error  , can't see correct chinese in markdown-preview

### ISSUE THREAD

**Issue by airclear** [atom/atom#7647] opened 2015-07-02 07:33 UTC
font family is : 

```
Monaco,Droid Sans Mono, Droid Sans Fallback
```

![deepinscrot-3111](https://cloud.githubusercontent.com/assets/4103690/8471948/9665208a-20cf-11e5-9c5c-919ba15714d2.png)

**Comment by izuzak** [comment] 2015-07-02 07:35
Seems to be a duplicate of https://github.com/atom/markdown-preview/issues/238.

**Closed by izuzak** 2015-07-02 07:35 UTC
