### ISSUE TITLE
MacOS - Only 1 launchpad icon when Atom & Atom Beta are installed side by side

### ISSUE THREAD

**Issue by chris-c-thomas** [atom/atom#15757] opened 2017-09-27 17:03 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When you install Atom & Atom Beta side by side on MacOS the version you installed last is the icon that shows up in Launchpad. Both show up in the 'Applications' folder but I find Launchpad is an easier way to open programs that are not in my dock.

### Steps to Reproduce

1. Install Atom
2. Install Atom beta
3. Open Launchpad

**Expected behavior:** 

To see a green Atom icon and a gold Atom Beta icon

**Actual behavior:**

The last version you install is the only icon that displays. So if I installed Atom and then Atom Beta all I see is the gold Atom Beta icon in Launchpad.

**Reproduces how often:**

Seems to be all the time.

### Versions

Atom: 1.20.1
Atom Beta: 1.21.0-beta2

### Additional Information

MacOS 10.13 High Sierra (although I noticed this happened on 10.12.x Sierra as well)

**Comment by rsese** [comment] 2017-09-27 18:38
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/10672. You can  subscribe there for updates if you'd like.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-27 18:38 UTC
