### ISSUE TITLE
brackets matching

### ISSUE THREAD

**Issue by camel-chased** [atom/atom#6580] opened 2015-04-30 15:50 UTC
try this:
```javascript
if(true){
	//}
}
```
![zaznaczenie_001](https://cloud.githubusercontent.com/assets/10367616/7416674/64150b6c-ef61-11e4-886f-b9e082f0c49f.png)

**Comment by izuzak** [comment] 2015-04-30 15:52
I think this is a duplicate of https://github.com/atom/bracket-matcher/issues/78 -- please subscribe to that for updates. Thanks for the report!

**Closed by izuzak** 2015-04-30 15:52 UTC
