### ISSUE TITLE
Inserting <style> tag in HTML document with long lines = Doom

### ISSUE THREAD

**Issue by Alhadis** [atom/atom#14856] opened 2017-06-21 06:39 UTC
### Prerequisites

* { 𝒳 }  Put a spiffy cross on this line if you have done all of the following:
    * Reproduced the problem in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)
    * Followed all applicable steps in the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)
    * Checked the [FAQs on the message board](https://discuss.atom.io/c/faq) for common solutions
    * [Checked](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom) that your issue isn't already filed
    * ~~[Checked](https://atom.io/packages) that there is not already an Atom package that provides the described functionality~~

### Description

Hanging hard in **Atom v1.18.0** (in safe mode, even).

### Steps to Reproduce

1. Download and open [this file](https://github.com/Alhadis/URW-Core35-Fonts/blob/master/preview.html)
2. Place editor's cursor at the end of [line 85](https://github.com/Alhadis/URW-Core35-Fonts/blob/edb2a24/preview.html#L85)
3. Press <kbd>Enter/Return</kbd>
4. Type `<style>`

<dl><dt>Expected behaviour:</dt><dd>Being able to type the closing <code>&gt;</code>.</dd><dt>Actual behaviour:</dt><dd>Atom freezes at <code>&lt;style</code></dd><dt>Reproduces how often:</dt><dd>Every time.</dd></dl>

### Versions

**Atom:** 1.18.0
**Electron:** 1.3.15
**Chrome:** 52.0.2743.82
**Node:** 6.5.0

~~~console
$ uname -v
Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64
$ sw_vers # It's macOS Sierra, folks.
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
~~~

### Additional Information
The HTML file is [being generated using a Perl script](https://github.com/Alhadis/URW-Core35-Fonts/blob/master/update.pl).

**Comment by rsese** [comment] 2017-06-21 19:58
Reproduced on the same versions, thanks @Alhadis :bow:

I had 1.14.4 installed on another computer with macOS and couldn't reproduce but then tried 1.15.0 and saw the same freezing there.

**Comment by Alhadis** [comment] 2017-06-21 20:26
Ah, you reckon it started at [`v1.15.0`](https://github.com/atom/atom/releases/tag/v1.15.0), then? That would make sense -  I'm wondering if this might've had an influence:

> Improvements to line tokenisation to improve editor performance when opening files with large,
> uninterrupted lines, like minified JavaScript. Opt out of this behaviour from certain grammars like `language-gfm`.

The generated lines *are* log enough to pop the maximum tokens-per-line limit, so... that may or may not be related, I don't know. :(

**Comment by 50Wliu** [comment] 2017-06-22 05:02
I'll also note that 1.15.0 was the first version to include atom/language-css#99.
Through lots of trial and error I've managed to narrow it down to approximately this:
```html
<!DOCTYPE html>
<!-- type style on this line -->
<body>
[}~ÁÂÃÄÅÆÇÈÊËÍÎsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfffffffffffffffffffffffffffffffffffffffffkeepwritinghereandeventuallyit'llslowdownandhang
</body>
</html>
```
The `[?~` seems necessary to trigger the catastrophic backtracking.  The effect gets a lot worse the more "special" characters there are.

**Comment by Alhadis** [comment] 2017-06-22 05:08
> I'll also note that 1.15.0 was the first version to include atom/language-css#99.

In my defence, the grammar now kicks ass. 😜 

My solution would be to screen the HTML-imported CSS grammar and maybe have it terminate at a `<` character, although that still feels very hit-and-miss... :S

**Comment by rsese** [comment] 2017-06-22 19:37
> Ah, you reckon it started at v1.15.0, then?

👍 yeah that's what I was thinking, it was lucky/random I had 1.14.4 installed on another computer so I decided to give it a try and it worked ok there.  Then I tried the next 2 release versions from there and they both hung with your steps to repro.

**Comment by nathansobo** [comment] 2017-08-12 20:43
I just saw this. @Alhadis, no matter how good the grammar is, if it hangs Atom it's a step backward. Can you please do something to remove the backtracking?

**Comment by Alhadis** [comment] 2017-08-12 21:55
[Recommended a fix](https://github.com/atom/language-css/pull/119#discussion_r132827636).

**Comment by Ben3eeE** [comment] 2017-08-13 06:52
Closed via https://github.com/atom/language-css/pull/119

**Closed by Ben3eeE** 2017-08-13 06:52 UTC
Labels: bug, regression
