### ISSUE TITLE
Text resize shouldn't change visible file section

### ISSUE THREAD

**Issue by bmhkim** [atom/atom#8218] opened 2015-08-04 17:46 UTC
Increasing/decreasing font size currently effectively scrolls you through a file. I imagine it's because the vertical scroll/offset is fixed, while the height of the rendered page is changing under it. It would be super fancy and helpful if Atom would scale text and automatically jump you back to wherever you were in the file.

**Comment by mnquintana** [comment] 2015-08-04 18:01
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/4084 – please subscribe there for updates.

**Closed by mnquintana** 2015-08-04 18:01 UTC
