### ISSUE TITLE
Manual updating breaks release notes page

### ISSUE THREAD

**Issue by cc941201** [atom/atom#8315] opened 2015-08-11 03:53 UTC
<img width="750" alt="2015-08-11 11 43 10" src="https://cloud.githubusercontent.com/assets/3082401/9189723/0d768fc4-401f-11e5-84ce-c73fc36228eb.png">

The button "Restart and update" will simply quit Atom without doing anything else.

**Comment by mnquintana** [comment] 2015-08-11 11:52
I think this is a duplicate of https://github.com/atom/atom/issues/5692 – closing in favor of that issue.

**Comment by cc941201** [comment] 2015-08-11 13:22
I have seen that issue, and I believe it's a different issue.

In that issue, the button is pressed and Atom is not updated.

In this issue, I have already updated manually by replacing Atom.app. However, the button on the release notes page is still there.

**Comment by schlamar** [comment] 2015-11-13 17:39
I'm seeing this issue on Windows after an automatic update to 1.2 via the help menu.

**Comment by benogle** [comment] 2015-11-13 18:33
Closing in favor of https://github.com/atom/atom/issues/9164

Sorry about this issue :(

**Closed by benogle** 2015-11-13 18:33 UTC
Labels: auto-updater, bug, needs-reproduction
