### ISSUE TITLE
Uncaught Error: spawn /Users/ganzobp/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Conte...

### ISSUE THREAD

**Issue by ganzo** [atom/atom#10615] opened 2016-01-29 04:51 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/ganzobp/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/ganzobp/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:15:15)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:170:22)
    at /Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Users/ganzobp/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:48.7.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:35.2.0 tree-view:remove-project-folder (div.header.list-item)
     -0:03.6.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-01-29 13:27
Thanks for reporting!  This looks like a duplicate of #9559, so please subscribe there for updates.

**Closed by 50Wliu** 2016-01-29 13:27 UTC
