### ISSUE TITLE
Blank white screen on startup

### ISSUE THREAD

**Issue by marcinmrotek** [atom/atom#11124] opened 2016-03-10 12:44 UTC
I've been using Atom 1.5.4 on Windows 10 for some time, and suddenly started getting a white blank screen on startup from time to time. Rebooting used to help, but no longer does. Upgrading to 1.6.0-beta8 didn't change anything. Running `atom -f --safe` printed:

> [7024:0310/134024:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[7024:0310/134024:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[7024:0310/134024:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[7024:0310/134024:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[3952:0310/134024:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[7024:0310/134026:INFO:CONSOLE(52)] "Window load time: 1047ms", source: file:///C:/Users/marci/AppData/Local/atom/app-1.6.0-beta8/resources/app.asar/static/index.js (52)
[7024:0310/134026:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)

EDIT: Okay, it's no longer reproducible after another reboot. `atom -f --safe` prints the same.

**Comment by morrisonbrett** [comment] 2016-03-14 01:58
I'm seeing this too now on Windows 10.  And after several reboots it is still persisting.  Uninstalled and reinstalled several times, remove ~/.atom folder.  White Screen of Death.

**Comment by morrisonbrett** [comment] 2016-03-14 02:01
Tried Beta Channel.  Same problem.

**Comment by damieng** [comment] 2016-03-16 02:57
I think this is a dupe of https://github.com/atom/atom/issues/11134 where Windows 10 has just plain stopped working for some people but not everybody.  We'll continue the discussion there and try and figure out what the common element is for people experiencing the problem.

**Closed by damieng** 2016-03-16 02:57 UTC
