### ISSUE TITLE
Cursor is missing when window focus is changed

### ISSUE THREAD

**Issue by gerep** [atom/atom#3278] opened 2014-08-15 01:04 UTC
I'm using Atom version: **0.121.0** for **Linux(Manjaro)**, this problem wasn't happening on the previous version.

I tried to run `atom --safe` but the problem persist.

The cursor is gone but I still have the line highlighted.

These are the steps I follow to reproduce the error:

* Change windows with `ALT+TAB` and set the focus to this other window, also using `ALT+TAB` go back to Atom, the cursor is gone.

* If I make this process but instead of `ALT+TAB` I click on the window button on my panel, it works because on each click I'm also setting the focus to the window.

**Comment by rustedwolf** [comment] 2015-01-11 19:53
Well I'm still experiencing this issue when I switching windows with ```Alt+Tab```. Well I can still type, but I don't see the blinking cursor. Have to reach out for my mouse and click in text every time to get it back.

Atom ver: v0.169
System: Linux Mint 13 (Maya, Ubuntu 12.4 based distro)

**Comment by bjornua** [comment] 2015-02-04 10:00
Atom ver: v0.177.0

I experimented with this in XMonad.

(Works) Cursor resumes blinking when:
* Switching window focus and come back, cursor resumes blinking (works fine).

(Broke) Cursor disappears when
* Switching windows in "full mode" cursor also does not resumes blinking.
* Switching workspaces and come back, cursor does not resume blinking.

Perhaps this is a bug related to when the window is gone (like minimized, other workspace, etc...)

**Comment by StatelessCat** [comment] 2015-02-08 22:08
Atom ver: v0.177.0
System :  ArchLinux 
Desktop Env : KDE 14.12 with Plasma5

I have the same issue when doing <ALT><TAB>, the cursor disappears.

**Comment by rthijssen** [comment] 2015-04-09 06:40
Issue appears on Xubuntu when switching windows using ALT TAB.

Distribution info:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```
Atom version:
```
Atom 0.190.0
```

Would be great if this could be fixed. It's mainly just really annoying...

**Comment by bjornua** [comment] 2015-04-09 06:42
+1
Den 09/04/2015 8.41 AM skrev "Ruben Thijssen (@rubenthijssen)" <
notifications@github.com>:

**Comment by dmbasso** [comment] 2015-05-05 17:26
This issue still occurs in Atom 0.196.0 running on Debian 8 with Gnome 3.14.
The cursor disappears when switching workspaces, regardless of the tree view state. Alternating between windows in the same workspace (alt+tab) makes it appear again.

**Comment by rustedwolf** [comment] 2015-05-08 10:27
I think this issue is being ignored since it's closed.

**Comment by seanCodes** [comment] 2015-05-26 03:52
Issue appears for me on Mac OS X 10.10 running Atom 0.201.0. Only happens when simply clicking from one tab to another. Cursor disappears and editor doesn't seem to be focused. However, switching tabs using Alt+Tab or keybindings (Cmd+Shift+[ or ]) works fine.

**Comment by rustedwolf** [comment] 2015-05-26 06:25
Then it has something to do with focus events.

**Comment by StatelessCat** [comment] 2015-05-31 23:21
Still the problem on plasma-desktop 5.3.1 :/
Even with CTRL TAB, Atom dont get back the focus.

Yes @rustedwolf I think it's related to focus event.

**Comment by knd775** [comment] 2015-06-02 23:58
This issue just started occurring for me after a recent update. Same version and env as @seanCodes.

**Comment by metalelf0** [comment] 2015-06-24 12:17
I have the same problem on OSX 10.10, atom version 0.211, but only when Atom is fullscreen.

Steps to reproduce:
---

* make atom window fullscreen
* cmd+tab to another open app
* cmd+tab back to atom
* typing works, but cursor is not on screen

Workaround:
---

* make atom window fullscreen
* cmd+tab to another open app
* cmd+tab back to atom, **but hold alt before releasing cmd and tab**
* cursor is now appearing on screen.

**Comment by apowers** [comment] 2015-07-02 17:31
I have this problem on Ubuntu 14.04 (xfce4) and Atom 1.0.0

Steps to reproduce:
--
Use CTRL+ALT+Left to switch to another workspace.
Use CTRL+ALT+Right to switch to workspace with Atom
Typing works but cursor is invisible.
Hiding the tree view reveals the cursor, unhiding the tree hides the cursor.

Workaround
--
Use CTRL+TAB or ALT+# to switch to another tab, cursor is revealed.

Workaround
--
Click anywhere in the editor window, cursor appears at that position

**Comment by wwwtyro** [comment] 2015-07-20 15:04
I also have this issue. I'm on XFCE. After switching desktops back to the atom editor, I can interact with atom via my keyboard, but the cursor has disappeared. Doesn't reappear until I click it with my mouse.

**Comment by krpovmu** [comment] 2015-07-21 19:43
Somebody knows how to fix it? the editor is really good but that little error make the coding really annoying.
Thanks

**Comment by krpovmu** [comment] 2015-07-21 19:50
When I add this to ~/.atom/styles.less, I can work normally

atom-text-editor:not(.mini)::shadow .cursor {
  opacity: 1;
}
atom-text-editor:not(.mini)::shadow .blink-off .cursor {
  opacity: 0;
}

**Comment by tiemay** [comment] 2015-08-02 15:54
@apowers 
> - Press ALT+TAB twice to switch to another application in the same workspace and switch back to Atom. This isn't a reliable fix, sometimes it works and sometimes it doesn't work unless you press F11 to toggle full screen first.

For me, if my mouse is over atom when switching back to it, the cursor disappears -- if my mouse is outside the atom window when switching back to it, the cursor appears.

Kubuntu 14.04
Atom 1.0.3

**Comment by mnquintana** [comment] 2015-08-12 11:45
This looks like the same issue as https://github.com/atom/atom/issues/3622 – closing in favor of that issue because it has more comments and helpful GIFs.

**Closed by mnquintana** 2015-08-12 11:45 UTC
Labels: bug, linux
