### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: .ts

### ISSUE THREAD

**Issue by Hushpar** [atom/atom#8551] opened 2015-08-28 08:48 UTC
Steps to reproduce below:

1. Start Atom
2. Watching

**Atom Version**: 1.0.8
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot redefine property: .ts

```
At c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\compile-cache.js:164

TypeError: Cannot redefine property: .ts
    at Function.defineProperty (native)
    at c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\compile-cache.js:164:10
    at Array.forEach (native)
    at Object.<anonymous> (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\compile-cache.js:161:24)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at new Task (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\task.js:32:26)
    at Function.module.exports.Task.once (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\task.js:19:14)
    at GitRepository.module.exports.GitRepository.refreshStatus (c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\git-repository.js:398:37)
    at c:\Users\All\AppData\Local\atom\app-1.0.8\resources\app.asar\src\git-repository.js:77:26
```

### Commands

```
     -0:34.1.0 application:add-project-folder (atom-pane.pane.active)
     -0:00.7.0 tree-view:toggle (a.btn-issue.btn.btn-error)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ruby, v0.1.0
emmet, v2.3.12
file-icon-supplement, v0.8.3
file-icons, v1.6.9

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-08-28 08:53
Hey @Hushpar -- can you share some steps which reproduce this for you? When does this happen and does it happen every time or randomly?

**Comment by basarat** [comment] 2015-08-28 10:09
Just started happening with latest atom release `1.0.8`

**Comment by basarat** [comment] 2015-08-28 10:10
> does it happen every time

Everytime. Close all atom instances ... then start `atom`.

**Comment by basarat** [comment] 2015-08-28 10:15
Similar to the `fuzzy-finder` issue atom just asked me to report it as an issue in `spell-check`

![image](https://cloud.githubusercontent.com/assets/874898/9544133/7431fd2a-4dc1-11e5-8224-c7a262b93238.png)

I think it might be packages that start a background process?

**Comment by basarat** [comment] 2015-08-28 10:16
To get a graceful error one needs to `atom --safe` (atom works!) and then `ctrl + shift + r` ... some package will fail and report the same error

**Comment by izuzak** [comment] 2015-08-28 10:18
Strange. I'm running Atom 1.0.9-ff93fdf and I don't see the problem you described when I quit Atom completely and start it again. Does this happen on specific projects or on all projects? 

Also, that screenshot doesn't show the full exception so not sure how that's related. 

cc @kevinsawicki @maxbrunsfeld you'll probably have a better idea about what's going on here

**Comment by devoxel** [comment] 2015-08-28 13:32
I'm on 1.0.8 and I just got something like this. Even `atom --safe` was giving me this error. I was trying to debug it and ran `apm link` and `apm unlink` and it fixed itself.

I have no idea why. I'll update after I run some more diagnostics.

**Comment by DanoDavid** [comment] 2015-08-28 15:23
On my Win7, this problem was fixed by update Git Bash to v2.5

**Comment by RangerMauve** [comment] 2015-08-28 15:39
This happens to me on Windows 10 with Atom 1.0.8 when I start it from the command line. (Using default windows CMD with clink and all the GNU utilities in my path). Starting it as a "desktop app" has no errors. Downgrading to 1.0.7 for now since that works fine.

**Comment by jugglingnutcase** [comment] 2015-08-28 15:42
i'm seeing the same error windows as well, on both the spell-check and the fuzzy-finder packages when running from Git Shell with `atom --safe`:

![image](https://cloud.githubusercontent.com/assets/238079/9550469/8be7bcb8-4d79-11e5-835d-08595a39050e.png)

i also only experience this error when launching Atom from GitHub for Desktop's Git Shell application link. Launching from the start menu works as expected.

i have GHfD set to launch the Powershell client when running Git Shell:

![image](https://cloud.githubusercontent.com/assets/238079/9550458/67094e52-4d79-11e5-93c2-04f502a6a344.png)

i'm running GHfD version "The Last Free Monad (3.0.3.2) 91d86c3".

**Comment by kevinsawicki** [comment] 2015-08-28 15:55
> you'll probably have a better idea about what's going on here

My guess would be that this is related to #8433, @maxbrunsfeld can you take a deeper look?

**Comment by RangerMauve** [comment] 2015-08-28 16:10
TO clarify, what's happening to me is that as soon as I start Atom in the command line, it crashes and shows the developer tools with the error while the main atom window is blank.

**Comment by huntertj** [comment] 2015-08-28 17:43
same issue, workaround right now for me is open atom from the start menu and keep it running, subsequent calls from the command line for files or folders open fine

**Comment by Hushpar** [comment] 2015-08-28 18:57
Strange. I have ran it from desktop and I'm not seeing any problems

**Comment by maxbrunsfeld** [comment] 2015-08-28 19:43
Thanks for the information everyone. It seems like a file is incorrectly getting loaded more than once. If you're interested in helping out, could you trigger the error, then report the output of this javascript?

```js
Object.keys(require.cache).filter(function(key) {
  return /src.(task.js|compile-cache.js)/.test(key);
})
```

**Comment by RangerMauve** [comment] 2015-08-28 19:54
@maxbrunsfeld Here's what I'm getting:
```
[
"C:\Users\Mauve\AppData\Local\atom\app-1.0.8\resources\app.asar\src\compile-cache.js",
"c:\Users\Mauve\AppData\Local\atom\app-1.0.8\resources\app.asar\src\task.js"
]
```

**Comment by maxbrunsfeld** [comment] 2015-08-28 19:56
Interesting that for `task.js`, the `C` drive is lower-case. I wonder if that has anything to do with it. Investigating...

**Comment by maxbrunsfeld** [comment] 2015-08-28 20:02
Could you also share the output of these expressions?

```js
atom.getLoadSettings().resourcePath
```

```js
require.main.filename
```

**Comment by RangerMauve** [comment] 2015-08-28 20:05
Yup!

```
atom.getLoadSettings().resourcePath
"c:\Users\Mauve\AppData\Local\atom\app-1.0.8\resources\app.asar"
require.main.filename
"C:\Users\Mauve\AppData\Local\atom\app-1.0.8\resources\app.asar\static\index.html"
```

**Comment by kevinsawicki** [comment] 2015-08-28 20:11
@RangerMauve can you run `window.location.pathname` as well and paste the results?

**Comment by RangerMauve** [comment] 2015-08-28 20:14
@kevinsawicki 

```
"/C:/Users/Mauve/AppData/Local/atom/app-1.0.8/resources/app.asar/static/index.html"
```

Kinda strange how it's got the leading slash when the other paths don't.

**Comment by RangerMauve** [comment] 2015-08-31 15:22
Still getting this in version 1.0.9. 😢

**Comment by basarat** [comment] 2015-08-31 23:51
> Still getting this in version 1.0.9

Basically `atom .` does not work. However just launch atom and then open a directory works. So at least I can do work using atom atm :rose:

**Comment by batjko** [comment] 2015-09-01 08:21
I am getting the same thing, but only since upgrading to v1.0.9, on WIndows 7 on this case.

As the others observed, this still happens in safe mode as well.

I have one running on a Windows 10 machine and there the issue doesn't appear, but that seems to be inconsistent, judging from what others have reported here.

Just to add another stack trace, since there seem to be slightly different ones:

```plain
**Atom Version**: 1.0.9
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot redefine property: .ts

At c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:164

TypeError: Cannot redefine property: .ts
    at Function.defineProperty (native)
    at c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:164:10
    at Array.forEach (native)
    at Object.<anonymous> (c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:161:24)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value (c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at new Task (c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\task.js:32:26)
    at Function.module.exports.Task.once (c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\task.js:19:14)
    at GitRepository.module.exports.GitRepository.refreshStatus (c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\git-repository.js:398:37)
    at GitRepositoryProvider.module.exports.GitRepositoryProvider.repositoryForDirectorySync (c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\git-repository-provider.js:56:14)
    at Project.module.exports.Project.addPath (c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\project.js:270:89)
    at EventEmitter.<anonymous> (c:\Users\tthpmx\AppData\Local\atom\app-1.0.9\resources\app.asar\src\window-event-handler.js:37:32)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

**Comment by bahamut45** [comment] 2015-09-01 19:59
:+1:

**Comment by bahamut45** [comment] 2015-09-01 20:02
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Unknown Windows Version
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v0.88.0


### Stack Trace

Uncaught TypeError: Cannot redefine property: .ts

```
At d:\Users\Bahamut\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:164

TypeError: Cannot redefine property: .ts
    at Function.defineProperty (native)
    at d:\Users\Bahamut\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:164:10
    at Array.forEach (native)
    at Object.<anonymous> (d:\Users\Bahamut\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:161:24)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value (d:\Users\Bahamut\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at new Task (d:\Users\Bahamut\AppData\Local\atom\app-1.0.9\resources\app.asar\src\task.js:32:26)
    at Function.module.exports.Task.once (d:\Users\Bahamut\AppData\Local\atom\app-1.0.9\resources\app.asar\src\task.js:19:14)
    at Object.module.exports.startTask (d:\Users\Bahamut\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\fuzzy-finder\lib\path-loader.js:15:19)
    at Object.module.exports.startLoadPathsTask (d:\Users\Bahamut\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:120:39)
    at d:\Users\Bahamut\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\fuzzy-finder\lib\main.js:40:24
    at process._tickCallback (node.js:357:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "fuzzy-finder": {}
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-ruby, v0.1.0
editor-stats, v0.17.0
emmet, v2.3.12
highlight-line, v0.11.0
highlight-selected, v0.10.1
indentation-indicator, v0.6.0
language-ansible, v0.1.3
language-batchfile, v0.4.0
language-docker, v1.1.3
language-powershell, v2.1.0
language-puppet, v0.14.0
language-twig, v1.6.2
language-viml, v0.2.0
linter-puppet, v1.0.0
markdown-format, v2.5.1
minimap, v4.13.2
minimap-highlight-selected, v4.3.0
project-view, v0.1.2
save-session, v0.15.7
tabs-to-spaces, v0.11.1
tool-bar, v0.1.8
tool-bar-main, v0.0.8
tree-view-git-branch, v0.0.2
tree-view-git-status, v0.1.2

# Dev
No dev packages
```

**Closed** 2015-09-01 21:15 UTC
Labels: atom, bug, uncaught-exception, windows

**Comment by maxbrunsfeld** [comment] 2015-09-01 23:46
Ok, sorry for this, everyone. I just released Atom 1.0.10, which I think fixes this problem. Could you upgrade Atom and report whether the problem is fixed?

**Comment by basarat** [comment] 2015-09-02 00:08
> I just released Atom 1.0.10, which I think fixes this problem

didn't make it to australia yet 

![image](https://cloud.githubusercontent.com/assets/874898/9620133/7c6cbf10-515a-11e5-9ce2-6cf8b6db6484.png)

**Comment by bahamut45** [comment] 2015-09-02 04:39
I am update my version 1.0.10 and fixed my problem, good job.

**Comment by basarat** [comment] 2015-09-02 04:51
Likewise. Fixed! Thanks! :rose:

**Comment by RangerMauve** [comment] 2015-09-02 13:38
Works! Except the releases mentioned "git bash", whereas I was having the issue in the Windows 10 command prompt.
