### ISSUE TITLE
Drag and Drop Files in File Tree

### ISSUE THREAD

**Issue by tylerFowler** [atom/atom#5141] opened 2015-01-18 23:29 UTC
It would be super handy if there was an interface for drag and drop on the file tree to move files around. I shouldn't think it would be too terribly difficult (I might actually have a crack at it if I can find the time) as it the action would just be an alias for a cut/paste action.

**Comment by lee-dohm** [comment] 2015-01-18 23:36
Duplicate of atom/tree-view#55. Please subscribe there for updates.

**Closed by lee-dohm** 2015-01-18 23:36 UTC
