### ISSUE TITLE
can not work with chinese typewriting

### ISSUE THREAD

**Issue by lenxeon** [atom/atom#12067] opened 2016-06-29 00:10 UTC
just see gif 

![bug](https://cloud.githubusercontent.com/assets/251825/16436493/de93e1ce-3dd0-11e6-8569-5baab6cdbabc.gif)

**Comment by lenxeon** [comment] 2016-06-29 00:12
![image](https://cloud.githubusercontent.com/assets/251825/16436538/2d628274-3dd1-11e6-8980-ff0184f31478.png)

**Comment by lenxeon** [comment] 2016-06-29 00:17
work good at 1.7.4

**Comment by Ben3eeE** [comment] 2016-06-29 05:42
Duplicate of https://github.com/atom/atom/issues/11988?

**Comment by lenxeon** [comment] 2016-06-29 06:06
@Ben3eeE  yes

**Closed** 2016-06-29 06:06 UTC
