### ISSUE TITLE
Total Commander - open with is very slow

### ISSUE THREAD

**Issue by nmat** [atom/atom#10016] opened 2015-12-11 13:18 UTC
Using total commander and to use open with or F4 to open a file takes a long time.

Other text editors it goes really fast.

**Comment by lee-dohm** [comment] 2015-12-12 08:47
What is "total commander"?

**Comment by nmat** [comment] 2015-12-13 17:18
http://www.ghisler.com/

A file manager if you have ever used norton commander or even split window file managers its the same thing.

The thing is that when you tell total commander to open text files using: atom.cmd "%1" the opening of file takes forever. Using other editors it opens within just a second.

**Comment by lee-dohm** [comment] 2015-12-13 18:36
Depending on what the active directory is when you open Atom, it could take a long time for Atom to open. This is almost assuredly a duplicate of one of the following:

* https://github.com/atom/atom/issues/2654
* https://github.com/atom/atom/issues/6437

**Closed** 2015-12-13 18:36 UTC
Labels: needs-reproduction, windows
