### ISSUE TITLE
Syntax Highlighting breaks after long lines of code

### ISSUE THREAD

**Issue by cronoklee** [atom/atom#17185] opened 2018-04-20 09:52 UTC
Syntax highlighting is capped at 100 characters per line and there is a [package](https://atom.io/packages/grammar-token-limit) to increase that limit. There should obviously be a way to change this naively but that is not so much a bug as an inconvenience... 

The **bug** is that regardless of what you increase this limit to, once you go over the limit, all highlighting below a line which contains a " or a ' is broken for the entire rest of the document. My company uses very long script files so this is a real problem for me.

For example take a mySQL query like this in PHP:

    $query = "SELECT ROUND(SUM(`organic`)) AS organic, ROUND(AVG(`organicRate`)) AS organicRate, ROUND(AVG(`organicConvRate`)) AS organicConvRate, ROUND(SUM(`direct`)) AS direct, ROUND(AVG(`directRate`)) AS directRate, ROUND(AVG(`directConvRate`)) AS directConvRate, ROUND(SUM(`referral`)) AS referral, ROUND(AVG(`referralRate`)) AS referralRate, ROUND(AVG(`referralConvRate`)) AS referralConvRate, ROUND(SUM(`cpc`)) AS cpc, ROUND(AVG(`cpcRate`)) AS cpcRate, ROUND(AVG(`cpcConvRate`)) AS cpcConvRate, ROUND(SUM(`visitors`)) AS visitors, ROUND(SUM(`support`)) AS support, ROUND(AVG(`supportRate`)) AS supportRate, ROUND(SUM(`login`)) AS login, ROUND(AVG(`loginRate`)) AS loginRate, ROUND(SUM(`potCust`)) AS potCust, ROUND(AVG(`potCustRate`)) AS potCustRate, ROUND(SUM(`conversions`)) AS conversions, ROUND(AVG(`conversionRate`)) AS conversionRate, ROUND(AVG(`conversionRateOrig`)) AS conversionRateOrig, ROUND(SUM(`deleted`)) AS deleted, ROUND(AVG(`deletedRate`)) AS deletedRate, ROUND(SUM(`noinstall`)) AS noinstall, ROUND(AVG(`noinstallRate`)) AS noinstallRate, ROUND(SUM(`dfa`)) AS dfa, ROUND(AVG(`dfaRate`)) AS dfaRate, ROUND(SUM(`goodexp`)) AS goodexp, ROUND(AVG(`goodexpRate`)) AS goodexpRate, ROUND(SUM(`payers`)) AS payers, ROUND(AVG(`payersRate`)) AS payersRate, ROUND(SUM(`cancels`)) AS cancels, ROUND(AVG(`cancelsRate`)) AS cancelsRate, ROUND(SUM(`renewed`)) AS renewed, ROUND(AVG(`renewedRate`)) AS renewedRate, ROUND(SUM(`retained`)) AS retained 
                FROM metrics WHERE DATE(day) BETWEEN '{$from}' AND '{$to}' LIMIT 1;";

The syntax highlight breaks somewhere in the middle (a minor issue) but the final `"` is read by Atom as an _**opening**_ quote and hence the entire document below this line (5000 more lines in my case!) has broken highlighting.

**Comment by melissaelopez** [comment] 2018-04-20 15:17
I was able to reproduce this same issue using your code from above. Here's a screenshot of what I'm noticing for more clarity. Hope someone will be able to assist you to fix this natively!

<img width="1111" alt="screen shot 2018-04-20 at 11 15 57 am" src="https://user-images.githubusercontent.com/16906897/39059356-4c748f22-448c-11e8-9fea-02c6b81ecfd5.png">

**Comment by rsese** [comment] 2018-04-20 18:35
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/1667 so you can subscribe there for updates if you'd like.

For future please use the issue template, the information in the template is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-20 18:35 UTC
