### ISSUE TITLE
Atom 1.21.1 high CPU usage

### ISSUE THREAD

**Issue by stefanb2** [atom/atom#16011] opened 2017-10-27 06:17 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After upgrading from atom 1.21.0 to 1.21.1 atom starts to use ~300% CPU at start and then falls back to 100% CPU. It is busy looping, i.e. at some point the CPU fan of the laptop starts to spin up.

The problem disappears after downgrading to 1.21.0.

### Steps to Reproduce

1. Upgrade to 1.21.0
2. `atom --safe --clear--window-state`
3. check CPU usage with `top`

**Expected behavior:** [What you expect to happen]

No CPU hogging

**Actual behavior:** [What actually happens]

Initial 300% CPU usage, drops to 100% after a short while.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

```
$ atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.2
$ inxi -SMCG
System:    Host: XXXXX Kernel: 4.13.6-300.fc27.x86_64 x86_64
           bits: 64
           Desktop: KDE Plasma 5.10.5
           Distro: Fedora release 27 (Twenty Seven)
Machine:   Device: laptop System: LENOVO product: 20F90058MS v: ThinkPad T460s serial: N/A
           Mobo: LENOVO model: 20F90058MS v: SDK0J40697 WIN serial: N/A
           UEFI: LENOVO v: N1CET60W (1.28 ) date: 09/26/2017
CPU:       Dual core Intel Core i7-6600U (-HT-MCP-) cache: 4096 KB
           clock speeds: max: 3400 MHz 1: 2800 MHz 2: 2800 MHz 3: 2800 MHz
           4: 2800 MHz
Graphics:  Card: Intel HD Graphics 520
           Display Server: x11 (X.org 119.5 )
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.02hz, 2560x1440@59.95hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2)
           version: 4.5 Mesa 17.2.2
```

### Additional Information

I also tried latest 1.22.0-beta1 but it didn't fix the issue.

I'm attaching a Javascript CPU Profile I recorded according to the instructions:

[CPU-20171027T085826.cpuprofile.gz](https://github.com/atom/atom/files/1420951/CPU-20171027T085826.cpuprofile.gz)

**Comment by Ben3eeE** [comment] 2017-10-27 06:20
Does your projects contain symlink loops? Does changing the watcher backend to "emulated" in your settings-view prevent the problem?

![image](https://user-images.githubusercontent.com/17565/32056956-f4de7710-ba33-11e7-81aa-cbab01f1156c.png)

**Comment by stefanb2** [comment] 2017-10-27 06:40
Switching File System Watcher to "Emulated with Atom events" and restarting Atom fixed the issue for me. Thanks. I don't see anything related to File System Watcher in the 1.21.1 release notes, though...


Looks like one of my projects (buildroot.org) creates file system loops during build:

```
$ find -type l | xargs -I {} find -L {} -type d | wc -l
find: ‘./buildroot-new/output/build/host-gcc-final-6.4.0/build/arm-buildroot-linux-gnueabihf/libstdc++-v3/include/bits/stamp-bits’: Too many levels of symbolic links
find: File system loop detected; ‘./buildroot-new/output/build/attr-2.4.47/include/attr/attr’ is part of the same file system loop as ‘./buildroot-new/output/build/attr-2.4.47/include/attr’.
find: File system loop detected; ‘./buildroot-new/output/build/host-attr-2.4.47/include/attr/attr’ is part of the same file system loop as ‘./buildroot-new/output/build/host-attr-2.4.47/include/attr’.
.... a few more....
```

After clearing the build area Atom 1.21.1 File System Watcher also works OK with native API.

**Comment by Ben3eeE** [comment] 2017-10-27 06:50
@stefanb2 Then this issue is a duplicate of https://github.com/atom/atom/issues/15966 you may want to subscribe there for updates.

Can you please add a comment there with the information in your [comment](https://github.com/atom/atom/issues/16011#issuecomment-339886618)? I think it would be helpful for everyone to know that buildroot.org creates these symlink loops. Also include the information about this only happening on Atom 1.21.1. Thank you :bowing_man: 

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15966. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-10-27 06:50 UTC
Labels: duplicate

**Comment by stefanb2** [comment] 2017-10-27 06:55
Thanks for handling this quickly. I was unaware that there were symlink loops in one of my projects, otherwise I would have connected the dots while browsing the open issues list...
