### ISSUE TITLE
[macOS] File->Reopen Project does not work when there are no open windows

### ISSUE THREAD

**Issue by karevn** [atom/atom#17530] opened 2018-06-17 16:07 UTC
Steps to reproduce:
1. Have Atom on macOS.
2. Open Atom app.
3. Open some project.
4. Close all the windows.
5. In File menu, click "Reopen Project".
6. Click some project in the list.
Expected behaviour: A new window with the selected project should open.
What happens: no visible response.

**Comment by 50Wliu** [comment] 2018-06-17 21:30
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by 50Wliu** [comment] 2019-03-17 18:15
#12508 has been fixed, but Reopen Project is still broken. Reopening.

**Closed** 2019-03-27 15:21 UTC
Labels: d ⬇️, i ⬇️, mac, triaged, v ⬇️
