### ISSUE TITLE
Please consider restoring multiple cursors on undo

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8518] opened 2015-08-26 12:17 UTC
Just what the title says :)

**Comment by mnquintana** [comment] 2015-08-26 12:19
I think this is a duplicate of https://github.com/atom/atom/issues/8178 and was just fixed via https://github.com/atom/atom/issues/8506 for the next release of Atom (1.0.8). Let me know if I'm misunderstanding though.

**Closed by mnquintana** 2015-08-26 12:19 UTC

**Comment by zyklus** [comment] 2015-08-26 12:20
:+1: sorry for the dupe!

**Comment by maxbrunsfeld** [comment] 2015-08-26 16:18
@zyklus No problem! Really sorry for this bug hung around for so long.
