### ISSUE TITLE
Can't open projects/files with all windows in minimized state

### ISSUE THREAD

**Issue by StefanWallin** [atom/atom#16596] opened 2018-01-19 12:49 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    *  [X] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/ 
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On OSX one cannot reopen projects, open new files and other window opening actions using the GUI, unless a currently open window is in a non minimized state.

### Steps to Reproduce

1. Start atom on OSX
2. Minimize window
3. Keep focus on the Atom.app
4a. Click `File` > `Open...`  in the menu bar
4b. Click `File` > `Reopen Project` > `Any project`  in the menu bar
**5. Nothing happens**

**Expected behavior:**
4a. I expect the open file dialog to appear.
4b. I expect previous projects to be brougth to foreground in a new atom window.

**Actual behavior:**
Nothing happens, no alerts, no errors. Just silence.

**Reproduces how often:**
100% - Every time

### Versions
```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
OSX     : 10.13.2
```
### Additional Information
I have not run `atom --clear-window-state` in the debugging guide.

**Comment by 50Wliu** [comment] 2018-01-19 13:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-01-19 13:38 UTC

**Comment by StefanWallin** [comment] 2018-01-19 14:01
I tried searching but didn't use enough alternate words. I'm so sorry for wasting your time! 🙈

**Comment by 50Wliu** [comment] 2018-01-19 16:13
No problem!  There are certainly a lot of issues to look through - sometimes finding the right combination of words can be tricky :).
