### ISSUE TITLE
Disable "Check for updates at startup"

### ISSUE THREAD

**Issue by greencopper** [atom/atom#12428] opened 2016-08-15 11:38 UTC
So I have "automaticallyUpdate: false" set in config.cson under "core", but this doesn't prevent Atom from using a lot of bandwidth going online to still search for updated packages and display the number in the bottom.

We need a clear options somewhere to **disable check for updates on startup**

Even on a fast line I like to be able to decide when to check for updates.

**Comment by 50Wliu** [comment] 2016-08-15 14:41
This is a duplicate of #11318 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-15 14:41 UTC
