### ISSUE TITLE
Atom crashes when opening a second window via command line

### ISSUE THREAD

**Issue by jjwon0** [atom/atom#12168] opened 2016-07-14 00:51 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When I already have one window of the editor open, I cannot open another window using `atom <folder_name>` in the command line.

### Steps to Reproduce

1. Open a editor window (doesn't matter if there are files, can be the default `untitled` one)
2. Try to open a folder using `atom <folder_name>`

It may be worth noting that in the dock, I see another instance of Atom opening and closing quickly after running the command.  Feels like the process opens, sees an existing Atom process, and kills itself.

**Expected behavior:** A new editor window opens, with the folder specified as the project folder.

**Actual behavior:** Nothing

### Versions

Using OSX El Capitan, 10.11.5 on a Macbook Pro, with the latest stable version of Atom.

```
~
❯ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

~
❯ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.9.1
```

**Comment by rk-development** [comment] 2016-07-14 03:51
for me nothing happens.
i have one window open and trying to open another instance by `atom .` or `atom folder_name` works as it should.
I'm using windows 10 pro.

**Comment by 50Wliu** [comment] 2016-07-15 01:04
Closing as a duplicate of #11712 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-15 01:04 UTC
