### ISSUE TITLE
Unnecessary "keep waiting" on startup

### ISSUE THREAD

**Issue by LunarLanding** [atom/atom#7002] opened 2015-05-29 08:42 UTC
Version: 0.204.0
OS: OSX 10.10
 Console.app log: 29/5/15 09:23:28.375 Atom[452]: App load time: 15037ms
Installed Packages (all up to date, no errors):
├── language-apache@1.3.0
├── linter@0.12.6
├── minimap@4.9.0
├── script@2.23.0
└── script-runner@1.8.3

Action: start atom (will open previously opened folder)
Expected behaviour: no need for interaction loading
What actually happens:  "Keep waiting?" dialog before a glitched canvas; if "yes" is chosen, the expected behaviour happens instantly, ie the editor and tree view load the most recent project instantly.
![Image of issue]
(http://i.imgur.com/pgJifLh.png?1)

**Comment by izuzak** [comment] 2015-05-29 08:44
Can you reproduce this behavior in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by Zireael07** [comment] 2015-05-29 14:00
I'm having the same issue on Windows. Doesn't seem to happen with --safe.

The only packages I have in common with @LunarLanding are linter and minimap.

**Comment by izuzak** [comment] 2015-05-29 14:04
@Zireael07 Can you try figuring out which one it is by disabling packages one-by-one?

**Comment by Zireael07** [comment] 2015-05-29 14:49
Funny, my atom updated itself in the meantime (203->204) and the problem no longer happens.

**Comment by LunarLanding** [comment] 2015-05-31 11:04
If it happens, it doesn't happen if I close Atom and then reopen. Plus, in safe mode it didn't happen. This makes me think that when there's high load on my OS, such as just after logging in, Atom takes more time than expected to load, leading to the "keep waiting" dialogue to show up. Since using safe mode takes some load off, this may not occur in that configuration.
I suppose that after showing that dialogue there is no checking if Atom loads any time later, and that's why it stays there even though Atom eventually loaded properly.

**Comment by Zireael07** [comment] 2015-05-31 11:52
I think it's related to RAM or processor use, too (safe mode, obviously, reduces the use, and 203-> 204 contained some performance fixes).

Windows shows the 'not responding' dialog if the program loop does not call for UI input in X seconds, therefore it doesn't care if it later loads properly :{

**Comment by izuzak** [comment] 2015-07-30 18:23
Closing this since the problem wasn't reproducible in safe mode. If you can reproduce this in safe mode -- please let us know and provide more information.

**Closed by izuzak** 2015-07-30 18:23 UTC
Labels: more-information-needed
