### ISSUE TITLE
Disappear the content of a file when using "> news.txt"

### ISSUE THREAD

**Issue by yerrysherry** [atom/atom#16416] opened 2017-12-20 13:38 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Disappear the content of a file 

### Steps to Reproduce

1. In a console/terminal session I make an empty file
\> news.txt

2. I open this file in atom. I put some text in it. And save the file.

3. I go back do my terminal and push enter

4. In atom all my text is disappeared.

**Expected behavior:** [What you expect to happen]

Nothing

**Actual behavior:** [What actually happens]

All the text in atom is gone/disappear

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% 

### Versions

I am using OS X EL Capitan Version 10.11.6

$ atom --version
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

I'am using atom on a Mac. I do not know what the behavior is on Windows, Linux, .... 

When using "touch news.txt" everything work fine, only with ">  news.txt" is a problem.

**Comment by lee-dohm** [comment] 2017-12-20 18:47
This is the intended behavior. When the file is saved the contents in memory match the contents on permanent storage. Until the contents in memory are changed again (thereby making the in memory version "dirty"), Atom keeps the version in memory in sync with the version on permanent storage. So when you change the contents on disk by pressing <kbd>Enter</kbd>, Atom updates the copy in memory.

Since this is the expected behavior. I'm going to close this. Let me know if I've misunderstood anything.

**Closed by lee-dohm** 2017-12-20 18:47 UTC

**Comment by yerrysherry** [comment] 2017-12-20 22:08
Hello Lee-dohm,

I send you a small movie ..

Regards,
Gerrit

[atom_strange.m4v.gz](https://github.com/atom/atom/files/1577158/atom_strange.m4v.gz)

**Comment by lee-dohm** [comment] 2017-12-21 19:30
That definitely is strange behavior. I can reproduce it on my machine using only `/bin/bash`. I don't know if this is a bug or just a strange interaction between bash, a possibly open file handle, and Atom though. Do you happen to know what bash is doing behind the scenes when you execute `> filename`? Because if it was exactly the same behavior as `touch filename` then Atom wouldn't behave differently.

**Comment by yerrysherry** [comment] 2017-12-23 06:58
I tried doing the same but then with vi. On a Mac, I got the same problem but doing on Ubuntu in a Virtualbox it works correctly. So, probably, Mac oriented. So, some minor bug, nothing to care about and not a problem with atom.
