### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 67Error: Cannot call...

### ISSUE THREAD

**Issue by mikebronner** [atom/atom#16968] opened 2018-03-17 01:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 67
Error: Cannot call function 'getPosition' on missing remote object 67
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 67
Error: Cannot call function 'getPosition' on missing remote object 67
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:691:40)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:728:40)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:191:32)
```

### Commands

```
     -0:30.7.0 application:add-project-folder (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-ide-ui 0.9.4 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
chestnut-light-atom-syntax 0.2.1 
close-on-left 0.9.2 
dash 1.7.1 
double-tag 1.1.0 
duotone-light-syntax 2.1.0 
file-icons 2.1.17 
highlight-selected 0.13.1 
ide-laravel 0.0.0-prerelease 
ide-php 0.7.13 
intentions 1.1.5 
language-blade 0.38.0 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-jsonlint 1.3.0 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-phpmd 2.0.0 
linter-sass-lint 1.8.3 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
pen-paper-coffee-syntax 0.14.9 
php-hyperclick 1.2.1 
platformio-ide-terminal 2.8.1 
pretty-json 2.0.0 
recent-files-fuzzy-finder 0.4.0 
sort-lines 0.18.0 
Sublime-Style-Column-Selection 1.7.4 
symbols-navigator 1.4.0 
sync-settings 0.8.5 
tag 0.5.0 
tester 1.4.0 
tester-phpunit 1.0.6 
wakatime 7.0.4 
zentabs 0.8.9 
```

**Comment by rsese** [comment] 2018-03-19 17:53
Thanks for the report - this looks like a duplicate of #16630 so you can subscribe there for updates if you'd like.  I'll go ahead and copy over your comments over but do you happen to remember if you tabbed out of Atom  and then switched back when you saw the error?

---

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by rsese** 2018-03-19 17:53 UTC
