### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by G2PCraft** [atom/atom#17079] opened 2018-04-05 06:40 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At C:\Users\user\AppData\Local\atom\app-1.25.0\resources\app\src\text-editor-component.js:2280

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:2269:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:2262:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:401:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:279:20)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.25.0/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -3:11.7.0 core:backspace (input.hidden-input)
     -3:08.5.0 core:move-right (input.hidden-input)
     -3:08.3.0 core:backspace (input.hidden-input)
     -3:07.4.0 core:save (input.hidden-input)
     -2:28.9.0 core:copy (input.hidden-input)
     -2:24.7.0 core:paste (input.hidden-input)
  8x -2:20 core:backspace (input.hidden-input)
     -2:15 core:save (input.hidden-input)
     -1:41.4.0 core:backspace (input.hidden-input)
     -1:39.5.0 core:save (input.hidden-input)
     -1:03.7.0 core:paste (input.hidden-input)
     -1:03.0 core:save (input.hidden-input)
  6x -0:58.8.0 core:backspace (input.hidden-input)
     -0:53.4.0 core:save (input.hidden-input)
     -0:32.9.0 editor:newline (input.hidden-input)
     -0:20.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by Ben3eeE** [comment] 2018-04-05 13:26
Thanks for the report! Looks like this is a duplicate of #15263 and the fix I believe is in 1.26, currently in beta. If you still see this error when you're on 1.26 please let us know.

**Closed by Ben3eeE** 2018-04-05 13:26 UTC
Labels: duplicate

**Comment by mbroedl** [comment] 2018-05-02 09:46
@Ben3eeE 
This still occurs for me on 1.26 (although not as frequently anymore as before).

```
Uncaught Error: Requested measurement of a line component that is not currently rendered
/usr/lib/atom/src/text-editor-component.js:2277
Hide Stack Trace
Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/usr/lib/atom/src/text-editor-component.js:2266:23)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/usr/lib/atom/src/text-editor-component.js:2259:39)
    at TextEditorComponent.measureContentDuringUpdateSync (/usr/lib/atom/src/text-editor-component.js:399:10)
    at scheduler.readDocument (/usr/lib/atom/src/text-editor-component.js:269:35)
    at ViewRegistry.performDocumentUpdate (/usr/lib/atom/src/view-registry.js:245:7)
```

```
Atom    : 1.26.0
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1
Manjaro Linux
```

Happens in my case when I'm starting Atom with a big markdown file highlighted (linewrap enabled). It looks like one error is thrown on loading (the file, I believe), the other one visually coincides with the grammar being applied.

Curiously, this does not happen when I load the file later.
The bigger the file, the more likely the errors are (>10k words regularly, >2k words sometimes). Sometimes more are thrown when I start scrolling in that end phase. When I start scrolling before the first error message, it is unlikely to still appear.

Hope that helps?

**Comment by 50Wliu** [comment] 2018-05-05 17:26
> Atom    : 1.26.0
> Electron: 1.8.4
> Chrome  : 59.0.3071.115
> Node    : 8.2.1
> Manjaro Linux

Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by mbroedl** [comment] 2018-05-06 10:41
Thanks, with an official distribution it worked all well!
And also thanks for the elaboration on why this is. Very interesting!
