### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('A...

### ISSUE THREAD

**Issue by nekokaido** [atom/atom#19194] opened 2019-04-22 00:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('Alice,
How') contains HTML space characters, which are not valid in tokens.

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('Alice,
How') contains HTML space characters, which are not valid in tokens.
    at SuggestionListElement.addClassToElement (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1969704)
    at SuggestionListElement.renderItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1970996)
    at SuggestionListElement.renderItems (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1967361)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:326703)
```

### Commands

```
  3x -1:40.8.0 core:backspace (input.hidden-input)
     -1:35.3.0 core:save (input.hidden-input)
  2x -1:34.7.0 platformio-ide-terminal:toggle (input.hidden-input)
     -0:59.8.0 core:move-down (input.hidden-input)
  2x -0:59.6.0 atomic-emacs:next-line (input.hidden-input)
  2x -0:58.2.0 core:backspace (input.hidden-input)
     -0:55.8.0 editor:newline (input.hidden-input)
  2x -0:55 atomic-emacs:previous-line (input.hidden-input)
  3x -0:54.2.0 atomic-emacs:next-line (input.hidden-input)
  3x -0:53.5.0 core:backspace (input.hidden-input)
  2x -0:52.2.0 editor:newline (input.hidden-input)
     -0:46.9.0 core:move-up (input.hidden-input)
 13x -0:45.9.0 core:backspace (input.hidden-input)
 11x -0:39.7.0 atomic-emacs:previous-line (input.hidden-input)
 16x -0:39 atomic-emacs:next-line (input.hidden-input)
 31x -0:30.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.33.4 
atom-hipster-ui 0.3.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-runner 2.7.1 
atomic-emacs 0.13.0 
auto-encoding 0.7.2 
autocomplete-paths 2.12.2 
autocomplete-python 1.14.0 
autocomplete-sql 0.5.0 
autocomplete-xml 0.11.0 
avengers-syntax 0.3.0 
busy-signal 2.0.1 
challenger-deep-syntax 0.17.0 
color-picker 2.3.0 
custom-xml-autocomplete 0.1.0 
editor-background 1.2.41 
ficus-dark-syntax 2.1.0 
ficus-syntax 2.1.0 
file-icons 2.1.31 
git-plus 8.6.2 
highlight-selected 0.16.0 
hipster-syntax 0.0.3 
intentions 1.1.5 
isotope-light-ui 2.3.0 
isotope-ui 2.8.5 
japanese-menu 1.14.0 
kite 0.154.0 
linter 2.3.0 
linter-autocomplete-jing 0.8.4 
linter-clang 4.1.2 
linter-flake8 2.4.0 
linter-gcc 0.7.1 
linter-javac 1.10.0 
linter-python 3.1.2 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
monokai 0.24.0 
monokai-neo-syntax 1.3.2 
ninja-atom-syntax 0.1.2 
ninja-ui-syntax 0.1.4 
pear-dark-syntax 1.0.9 
pear-syntax 0.1.8 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
project-manager 3.3.7 
pumpkin-swamp-dark-syntax 0.4.0 
pumpkin-syntax 0.1.0 
python-indent 1.1.7 
slime 2.4.0 
split-diff 1.6.0 
Sublime-Style-Column-Selection 1.7.5 
tag 0.5.0 
terminal-tab 0.5.7 
xml-common-schemata 0.0.3 
zenburn 3.1.0 
zenburn-theme 1.3.0 
```

**Comment by rsese** [comment] 2019-04-22 18:30
Thanks for the report! I'm guessing this isn't reproducible in safe mode (atom --safe)?

I think this is likely a duplicate of #16164 - based on that issue and #16305, my guess would be that autocomplete-python might be causing the error?

If you can reproduce in safe mode however, please let us know.

---

It appears that this is being caused by the [autocomplete-python](https://atom.io/packages/autocomplete-python) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Closed by rsese** 2019-04-22 18:30 UTC
