### ISSUE TITLE
[Windows] Pinned Atom icon disappears with every update.

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#8858] opened 2015-09-19 08:43 UTC
Currently when Atom updates, the previously pinned icon on the taskbar vanishes and you have to pin it again manually.

**Comment by jerone** [comment] 2015-09-19 10:28
Confirmed on Windows 7 and 8.1. Happens since a few versions before and just happened again on 1.0.14 -> 1.0.15.

**Comment by jonathandelgado** [comment] 2015-09-19 15:39
PR to resolve #8857

**Comment by 50Wliu** [comment] 2015-09-19 16:36
#7374 is still open so I'm going to close this.

**Closed by 50Wliu** 2015-09-19 16:36 UTC

**Comment by jerone** [comment] 2015-09-19 17:27
[**@50Wliu**](https://github.com/50Wliu) commented on [19 sep. 2015 18:36 CEST](https://github.com/atom/atom/issues/8858#issuecomment-141686215 "2015-09-19T16:36:09Z - Replied by Github Comment Enhancer"):
> [#7374](https://github.com/atom/atom/issues/7374 "Pinning Atom to the Windows taskbar duplicates the icon") is still open so I'm going to close this.

Actually this issue states that the taskbar icons **disappears**, while issue #7374 is about "Pinning Atom to the Windows taskbar **duplicates** the icon". I'm experience disappearing icons, not duplicate icons. Hoping that PR #8857 fixes this issue also.

**Comment by Stanzilla** [comment] 2015-09-19 18:00
Yeah not sure that is the same issue but we will see. Paul's response left some stuff open to imagination :)

**Comment by jonathandelgado** [comment] 2015-09-19 19:40
I think the disappearing is upstream in squirrel removing old symlinks, but perhaps not replacing them? Should have nothing to do with the AppID stuff.

**Comment by Stanzilla** [comment] 2015-09-24 21:33
Can confim fixed in .18

**Comment by mastazi** [comment] 2015-12-17 03:42
It's happening again for me as of today - while updating from 1.3.1 to 1.3.2.
Platform Win 8.1 X64
Could this issue be reopened?

**Comment by mastazi** [comment] 2015-12-17 04:08
Please disregard my comment above about reopening this one - it is already open under #9618

**Comment by gm3000** [comment] 2016-03-30 09:48
happens to 1.6.0 also

**Comment by Fania** [comment] 2016-04-25 14:14
This keeps happening to me too. I'm on Windows 10 - Atom 1.72.
Very annoying.

**Comment by rudygunawan** [comment] 2016-06-08 09:36
Happens to me also, I'm on Windows 7 , updated to Atom 1.8.0

**Comment by snorfalorpagus** [comment] 2016-07-11 09:04
I have the same issue. Windows 7. Atom 1.8.0.

**Comment by tmaila** [comment] 2016-08-01 02:47
This is broken because the shortcut on the taskbar actually links to Update.exe and the Update.exe does not have an icon. The Start Menu shortcut has an icon: 

`%appdata%\Microsoft\Windows\Start Menu`

However the user created pinned task bar shortcut won't inherit the start menu icon but instead Windows likely tries to fetch the icon of the application the shortcut links to (Update.exe). For details see the shortcut file in the following folder:

`%appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\Taskbar`

Easiest fix is to have Update.exe to have identical icon to atom.exe.

**Comment by siberianbear** [comment] 2016-08-19 02:17
Windows 7 x64, Atom 1.9.9:
Icon is exists at window of Atom, but in taskbar - NO. Happens after update.
