### ISSUE TITLE
1.56.0 don't show indent tabs correctly

### ISSUE THREAD

**Issue by nf-takahashi** [atom/atom#22202] opened 2021-04-15 01:52 UTC
### Description

In 1.56.0, tab don't show as indent in languages like STYLUS or PUG.

**Actual behavior:**
<img width="366" alt="atom_bug" src="https://user-images.githubusercontent.com/16251145/114802435-aa43d100-9dd8-11eb-834d-576f1f934ef0.png">

**Reproduces how often:**

### Versions

1.56.0

**Comment by sadick254** [comment] 2021-04-15 05:32
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see in Atom. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see the [How Can I Contribute? section of the Atom CONTRTIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by mquevill** [comment] 2021-04-21 20:00
Does this happen for all themes? If not, then what themes does it work with/not work with?

It looks like you might be using the Monokai theme. If so, there is a workaround discussed here: https://github.com/kevinsawicki/monokai/issues/111
There were some changes to the theme syntax in 1.56.0 that need to be ported over to themes. Unfortunately it broke how some themes currently appear, especially with invisibles shown.

**Comment by jonyyz** [comment] 2021-04-22 17:09
It's an issue with older themes.  It seems to be me that in 1.56, changes were made to the way theme templates such that, for example, this was working for [atom/monokai](https://github.com/kevinsawicki/monokai) in 1.55 but now causes invisibles to not render in 1.56:

https://github.com/kevinsawicki/monokai/blob/master/index.less#L192

I realize the argument to be made here is that themes like this were never updated to be based on the newer theme template but I think you could consider it a regression because it was working 1.55 and now no longer works in 1.56.

I modified my local stylesheet to work with the newer Atom CSS.  Personally, I'm fine with that workaround until the author(s) of the older themes update them.

**Comment by mquevill** [comment] 2021-04-22 17:15
According to the current setup for the default themes, they all have a `styles/syntax-legacy` directory, which is imported as well. This would imply that the "legacy" themes (without the new naming convention) should still work. It seems though that some things ended up broken along the way...

**Comment by leopons** [comment] 2021-04-29 08:36
@jonyyz Hi ! What do you mean by "I modified my local stylesheet to work with the newer Atom CSS." ? You managed to make it work with monokai ? What did you change ?

**Comment by jonyyz** [comment] 2021-04-29 11:53
@leopons Apply this change: https://github.com/kevinsawicki/monokai/pull/112/files

On Windows the path to `index.less` will be: `$USERPROFILE%\.atom\packages\monokai`

However, the update should be available now:
![image](https://user-images.githubusercontent.com/41442131/116546675-e8082580-a8bf-11eb-8bc5-f886380dc944.png)

**Comment by leopons** [comment] 2021-04-29 12:30
Thanks a lot :)

**Comment by nf-takahashi** [comment] 2021-04-30 12:06
monokai 0.28.0 solves the problem above.
Thanks!!

**Closed** 2021-04-30 12:07 UTC
