### ISSUE TITLE
File that is open in Atom and PhpStorm and gets modified in PhpStorm, does not automatically reload in Atom but closes

### ISSUE THREAD

**Issue by bwydoogh** [atom/atom#12353] opened 2016-08-07 06:18 UTC
### Description

When a file (in my case a _JAVA_ file) is opened in Atom and that same file is **edited and saved in PhpStorm**, **the file automatically closes in Atom**. I would expect that it automatically reloads the file, like other editors are doing well (_I tested with Sublime Text 3 and Notepad++: those applications automatically reload the file when edited in PhpStorm_).

It don't have this issue when editing a file in Sublime Text 3 that is also open in Atom: the file that was open in Atom, automatically reloads. So it seems to be a problem only when saving the file in PhpStorm.

Notice that the file is under version controlling (GIT).

### Steps to Reproduce

1. Open file in Atom
2. Open file in PhpStorm
3. Edit file in PhpStorm

**Expected behavior:** File is automatically reloaded in Atom, showing the latest version.

**Actual behavior:** File is automatically closed.

### Versions

Atom    : 1.9.6
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Running Windows 10.

**Comment by 50Wliu** [comment] 2016-08-07 14:58
In the future please completely fill out the provided issue template.  Does this happen in safe mode (`atom --safe`)?

**Comment by bwydoogh** [comment] 2016-08-07 15:02
Yes, also happening then. I already checked that before posting this issue.

Let me know if you need further information.

**Comment by maxbrunsfeld** [comment] 2016-08-08 16:53
I believe this is a duplicate of https://github.com/atom/atom/issues/7519. It is not reproducible on Mac OS. I don't know about linux.

**Closed by maxbrunsfeld** 2016-08-08 16:53 UTC
Labels: needs-reproduction, windows

**Comment by bwydoogh** [comment] 2016-08-08 18:18
@maxbrunsfeld Thanks. Indeed, you are right: it is caused by a so-called _atomic save_ performed by PhpStorm. I could disable this feature in PhpStorm (disable setting _Use "safe write"_) which made that I don't have the issue anymore in Atom.

**Comment by bwydoogh** [comment] 2016-08-08 18:19
@maxbrunsfeld Thanks. Indeed, you are right: it is caused by a so-called atomic save performed by PhpStorm. I could disable this feature in PhpStorm (disable setting Use "safe write") which made that I don't have the issue anymore in Atom.
