### ISSUE TITLE
Atom keeps crashing when I try to edit python files

### ISSUE THREAD

**Issue by thatVaddiguy** [atom/atom#16984] opened 2018-03-19 12:01 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When i try to edit python files the editor crashes 

**Expected behavior:** Not crash every 30s

**Actual behavior:** Crashes every 30s but only on python files

**Reproduces how often:** Happens every 30s

### Versions

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python
git 2.9.3.windows.1
visual studio

### Additional Information

I have tried safe mode, the crash still occurs.
I have tried reinstalling the editor and it still occurs 
I have disabled all the git packages still the error occurs

**Comment by maxbrunsfeld** [comment] 2018-03-19 16:33
Do you have the new experimental highlighting mode enabled? It's called `Use Tree-sitter Parsers` in the settings view.

**Comment by thatVaddiguy** [comment] 2018-03-19 16:40
no its not enabled

**Comment by Arcanemagus** [comment] 2018-03-19 17:37
Does this happen for _any_ Python file, or specific files? If you only see this on a specific file are you able to share it so we can attempt to reproduce this?

**Comment by thatVaddiguy** [comment] 2018-03-19 18:42
No, it does it for all python files and it crashes after I run the python file either externally or through atom

**Comment by Arcanemagus** [comment] 2018-03-19 18:54
Could you describe this crash? Are you getting any error messages? If you launch Atom from a CLI (like Command Prompt for example) using `atom --safe .`, do you get any messages printed when it crashes?

**Comment by thatVaddiguy** [comment] 2018-03-19 19:04
No message comes up

**Comment by Arcanemagus** [comment] 2018-03-19 19:54
Could you try changing the language Atom is considering the file to something else? You can do this by clicking "Python" in the lower right corner and selecting a different language (eg. "Plain Text").

**Comment by thatVaddiguy** [comment] 2018-03-19 20:13
Nope it still crashes does it have anything to do with the packages I have ?

**Comment by Arcanemagus** [comment] 2018-03-19 20:19
Can you try temporarily [Resetting to Factory Defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) to check if it is anything in your profile? You can easily move the folder back after testing to restore your current profile.

**Comment by thatVaddiguy** [comment] 2018-03-19 20:29
Nope, it still crashed :(

**Comment by Arcanemagus** [comment] 2018-03-19 20:45
Can you describe the crash you are seeing?

**Comment by thatVaddiguy** [comment] 2018-03-20 06:38
So I'll be editing the code after running the file, then the editor goes white and I get an error telling me the editor has crashed and that I could reload it, close it or keep waiting. If I choose to keep waiting the editor is white screen but, i can access the file options on the top navbar

**Comment by Arcanemagus** [comment] 2018-03-20 16:26
> Every time it reloads it opens a new python task which slows down my computer

Can you make sure that you are trying [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? Atom by itself doesn't launch any Python processes so that would have to be a community package.

**Comment by thatVaddiguy** [comment] 2018-03-20 18:40
Sorry i forgot to mention the python tasks issue doesn't occur in safe mode

**Comment by Zireael07** [comment] 2018-03-20 20:01
@thatVaddiguy: this means an issue is in a community package, what packages do you have?

**Comment by thatVaddiguy** [comment] 2018-03-21 14:36
I have all these packages
├── atom-beautify@0.32.2
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── atom-python-run@0.9.6 (disabled)
├── auto-detect-indentation@1.3.0
├── autoclose-html@0.23.0
├── autocomplete-modules@1.12.0
├── autocomplete-python@1.10.5
├── autocomplete-xml@0.9.4
├── busy-signal@1.4.3
├── emmet@2.4.3
├── highlight-selected@0.13.1
├── intentions@1.1.5
├── linter@2.2.0 (disabled)
├── linter-csslint@2.0.0
├── linter-htmlhint@1.4.0
├── linter-jshint@3.1.6
├── linter-ui-default@1.7.1
├── markdown-writer@2.7.3
├── pigments@0.40.2 (disabled)
├── python-indent@1.1.4
├── python-tools@0.6.9
├── todo-show@2.2.0
└── xml-formatter@0.11.0

**Comment by Zireael07** [comment] 2018-03-21 14:57
Python-indent and python-tools look like likely culprits, disable them first and see if it fixes the issue.

If it doesn't, keep disabling packages one by one to see which one is the problem.

**Comment by gnurush1** [comment] 2018-04-02 21:09
I could take a look into this issue if it hasn't already been assigned to someone else.

**Comment by Ben3eeE** [comment] 2018-04-05 13:25
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Closed by Ben3eeE** 2018-04-05 13:25 UTC
Labels: more-information-needed
