### ISSUE TITLE
Feature request: add a package.json config file

### ISSUE THREAD

**Issue by smaili** [atom/atom#8171] opened 2015-07-31 14:39 UTC
I think it would be very useful to have a `package.json` similar to Node for managing all additionally installed packages in Atom.  This way on new machines, rather than have to copy the `packages` folder, all we would need to do is provide the `package.json` file and Atom could read that and install any packages with their respective versions.  Very similar to Node and NPM, and seeing as how Atom is built on that I think it would only be fitting to incorporate the same structure :)

**Comment by mnquintana** [comment] 2015-07-31 14:45
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/5929 though – let's keep the discussion there.

**Closed by mnquintana** 2015-07-31 14:45 UTC
