### ISSUE TITLE
1.19.0-beta1 Shows incorrect colours for One Dark UI and syntax

### ISSUE THREAD

**Issue by josephmbeveridge** [atom/atom#14898] opened 2017-06-26 17:16 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The colours rendered from the One Dark syntax and UI themes have changed in 1.19.0-beta1 despite no changes to the repo in a year. This seems like an issue with rendering.

Red, green, violet and orange are all showing darker than they should.

### Steps to Reproduce

1. Turn on One Dark syntax and UI themes.
2. Observe colours on 1.18.0 stable
3. Observe colours on 1.19.0-beta1

**Expected behavior:**
<img width="626" alt="screen shot 2017-06-26 at 1 09 57 pm" src="https://user-images.githubusercontent.com/3857356/27551402-3954eed8-5a71-11e7-8ab7-f5f0508c7daa.png">
<img width="150" alt="screen shot 2017-06-26 at 1 15 22 pm" src="https://user-images.githubusercontent.com/3857356/27551474-8e4364f6-5a71-11e7-8dbe-0da744f63eec.png">

**Actual behavior:** 
<img width="626" alt="screen shot 2017-06-26 at 1 09 40 pm" src="https://user-images.githubusercontent.com/3857356/27551407-41b363b6-5a71-11e7-8d2c-927e832ca933.png">
<img width="158" alt="screen shot 2017-06-26 at 1 15 29 pm" src="https://user-images.githubusercontent.com/3857356/27551480-937b83cc-5a71-11e7-816d-37ba71287962.png">

**Reproduces how often:** 100%

### Versions

Atom: 1.19.0-beta1
OS: macOS 10.12.5

### Additional Information

N/A

**Comment by simurai** [comment] 2017-06-27 02:42
I can't reproduce the color changes, anyone else?

When using the macOS color picker (Digital Color Meter), for example the orange is `rgb(209, 154, 102);`:

![bitmap](https://user-images.githubusercontent.com/378023/27568408-8ee35342-5b2c-11e7-98bd-9930f7ba5a39.png)

Might be related to upgrading Electron/Chromium: https://github.com/atom/atom/pull/12696. And it now supports other color profiles? But maybe only for certain system configurations.

**Comment by rsese** [comment] 2017-06-27 04:45
Hmmm, it looks like I can reproduce?  I'm on macOS 10.12.5.

Beta:

![beta](https://github-slack.s3.amazonaws.com/monosnap/Digital_Color_Meter_2017-06-26_23-34-29.png)

And stable:

![stable](https://github-slack.s3.amazonaws.com/monosnap/Digital_Color_Meter_2017-06-26_23-38-59.png)

**Comment by simurai** [comment] 2017-06-28 05:08
Turns out, I **can not** reproduce it on my MBP's retina screen.

But I **can** reproduce it on my external Thunderbolt screen. Although the difference isn't that much:

![color](https://user-images.githubusercontent.com/378023/27618579-1d956460-5bf8-11e7-8043-4167a3179bcf.png)
![color 2](https://user-images.githubusercontent.com/378023/27618580-1d9b8bba-5bf8-11e7-9f8d-301baa83290d.png)

@josephmbeveridge What monitor and color profile are you using?

**Comment by thomasjo** [comment] 2017-06-28 13:40
This is an issue introduced in Chrome 56 (which we got as part of #12696);
https://bugs.chromium.org/p/chromium/issues/detail?id=687194

As reported in that issue, the problem is less prominent in newer versions of Chrome, albeit still not fixed. The reason all of you are seeing somewhat different results is simply caused by the fact this issue is directly affected by your configured color profiles.

**Comment by simurai** [comment] 2017-06-29 23:48
Just saw @intemperie's [tweet](https://twitter.com/pumpkin/status/880405991686373377), should be fixed in Chrome 61. Probably still takes a while till it lands in Atom tough.

**Closed** 2017-08-17 23:13 UTC
Labels: blocked, electron, regression
