### ISSUE TITLE
Not possible to write "@" (Alt-Gr + q)

### ISSUE THREAD

**Issue by 3c7** [atom/atom#5785] opened 2015-02-27 13:34 UTC
Hi,
with Atom Version 0.184.0, Windows 8.1 x64, no custom keymap, only the default keybindings and all community packages disabled:
I'm not able to write an "@"-Symbol in the editor using a German keyboard and Alt-Gr + q.

**Comment by 50Wliu** [comment] 2015-02-27 13:40
Duplicate of atom/atom-keymap#35, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-27 13:40 UTC
