### ISSUE TITLE
Uncaught Error: Cannot call function 'isFocused' on missing remote object 1006Error: Cannot call...

### ISSUE THREAD

**Issue by vboddui** [atom/atom#19082] opened 2019-04-01 07:41 UTC
[Enter steps to reproduce:]

1. I removed the removable that is acting as Storage for the folder that Atom open.
2. When I reconnected it back, it failed with this error.

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'isFocused' on missing remote object 1006
Error: Cannot call function 'isFocused' on missing remote object 1006
    at throwRPCError (C:\B\Apps\atom\app-1.35.1\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\B\Apps\atom\app-1.35.1\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\B\Apps\atom\app-1.35.1\resources\electron.asar\browser\api\web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At C:\B\Apps\atom\app-1.35.1\resources\electron.asar\renderer\api\remote.js:221

Error: Cannot call function 'isFocused' on missing remote object 1006
Error: Cannot call function 'isFocused' on missing remote object 1006
    at throwRPCError (C:/B/Apps/atom/app-1.35.1/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:/B/Apps/atom/app-1.35.1/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:/B/Apps/atom/app-1.35.1/resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at Object.exception (C:/B/Apps/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (C:/B/Apps/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (C:/B/Apps/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:125:16)
    at BackgroundTipsElement.shouldBeAttached (C:/B/Apps/atom/app-1.35.1/resources/app/static/<embedded>:11:644092)
    at BackgroundTipsElement.updateVisibility (C:/B/Apps/atom/app-1.35.1/resources/app/static/<embedded>:11:643906)
    at e (C:/B/Apps/atom/app-1.35.1/resources/app/static/<embedded>:11:642871)
    at CallbacksRegistry.apply (C:/B/Apps/atom/app-1.35.1/resources/electron.asar/common/api/callbacks-registry.js:47:25)
    at EventEmitter.ipcRenderer.on (C:/B/Apps/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:277:21)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
```

### Commands

```
     -3:16.1.0 core:move-up (input.hidden-input)
     -3:12.9.0 core:move-down (input.hidden-input)
  2x -2:35.7.0 core:save (input.hidden-input)
  3x -2:19.3.0 core:close (input.hidden-input)
     -2:08.8.0 core:save (input.hidden-input)
     -2:08.8.0 core:close (input.hidden-input)
     -1:41.4.0 application:open-file (atom-pane.pane.active)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2019-04-01 20:17
Thanks for contributing!

Based on the stack trace, I think this is a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-01 20:17 UTC
