### ISSUE TITLE
File search not working directly after restart, needs to index files every time first

### ISSUE THREAD

**Issue by jancborchardt** [atom/atom#7914] opened 2015-07-15 14:35 UTC
After every restart, the Ctrl+P search is not working immediately. All files have to be indexed first. For big projects this can take some time.

Instead the index should be cached to make the search immediately available instead of blocking it. Of course it can then index in the background.

**Comment by batjko** [comment] 2015-07-15 14:43
There is a comment to that effect on an issue that was opened on the Find-and-Replace package:
https://github.com/atom/find-and-replace/issues/145#issuecomment-100364667

**Comment by izuzak** [comment] 2015-07-15 17:04
I think this is a duplicate of https://github.com/atom/fuzzy-finder/issues/88. If I'm mistaken, please reopen this in the fuzzy-finder's issue tracker. :v:

**Closed by izuzak** 2015-07-15 17:04 UTC

**Comment by jancborchardt** [comment] 2015-07-15 18:35
@izuzak thank you! :) Continuing there.
