### ISSUE TITLE
Cannot delete project files on Windows 7

### ISSUE THREAD

**Issue by usoliveira** [atom/atom#10780] opened 2016-02-11 22:35 UTC
When clicking at "delete" button, it asks for moving file to trash. When confirming, it does nothing.

Can't use an editor that doesn't exclude files!! Too basic!!

**Comment by demhydraz** [comment] 2016-02-11 22:37
Dupe of atom/tree-view#666 (does that just work?)

**Comment by 50Wliu** [comment] 2016-02-11 22:39
Thanks @demhydraz.

**Closed by 50Wliu** 2016-02-11 22:39 UTC

**Comment by usoliveira** [comment] 2016-02-11 22:57
I know about that issue, but all solutions doesn't work yet for me. Even using Windows zip version... not working.

**Comment by 50Wliu** [comment] 2016-02-11 23:44
@usoliveira Have you tried the permanent-delete package?

**Comment by usoliveira** [comment] 2016-02-12 21:37
@50Wliu, using permanent delete pkg it works... but that's not a true solution!

I'm so excited about contributing with plug-ins for Atom and make it my default editor that I upgraded my Windows to 10, and now native delete works well!

Sorry for duping this, but this bug was really boring me! And thanks for your attention!

**Comment by 50Wliu** [comment] 2016-02-12 21:59
> Sorry for duping this, but this bug was really boring me!

We're working on fixing it :)

**Comment by LuckyTeng** [comment] 2016-03-08 02:55
it's really obviously bug, we need to delete the file in the window explorer XD

**Comment by 50Wliu** [comment] 2016-03-08 03:07
@LuckyTeng The fix will be available in Atom 1.7.0.
