### ISSUE TITLE
OSX: clicking "new file" should imply "new window"

### ISSUE THREAD

**Issue by matthdsm** [atom/atom#10669] opened 2016-02-03 08:01 UTC
Hi,

On OSX (10.11.3) in Atom 1.4.3 clicking "new file" or hitting cmd-n should open a new window by default if there are no windows open.

Currently you have to click "new window" first, which then open a new file. Should also work visa versa.

Thanks!
M

**Comment by lee-dohm** [comment] 2016-02-04 22:15
This is a duplicate of https://github.com/atom/atom/issues/7428 which was recently closed as fixed (though the fix probably hasn't made it to the Stable channel yet).

**Closed by lee-dohm** 2016-02-04 22:15 UTC
Labels: feedback
