### ISSUE TITLE
Find All links to file instead of lien in code

### ISSUE THREAD

**Issue by andrewclunn** [atom/atom#15755] opened 2017-09-27 14:06 UTC
The find all results no longer consistently link to the actual lines of code where the results were found (though the line numbers are identified).

![atom find all bug](https://user-images.githubusercontent.com/8753436/30918059-0f70e82a-a363-11e7-8e76-d80558e3c031.png)

**Steps to Reproduce:**
Press ctrl + shift + f to perform a search in all open files.
Do a search where an instance appears multiple times in a single file.
Click on a particular instance of the results.
Return to the results and click on another instance in that same file.

**Atom : 1.20.1 ia32**

**Comment by Ben3eeE** [comment] 2017-09-27 14:08
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/953. This issue has been fixed on Atom 1.21 beta.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-09-27 14:08 UTC
Labels: duplicate, wrong-repo
