### ISSUE TITLE
Navigation window too narrow

### ISSUE THREAD

**Issue by runningman84** [atom/atom#8361] opened 2015-08-13 08:48 UTC
I am using atom 1.07 on Xubuntu 14.04. The file navigation window is to narrow, that means I have to scroll to see the full filename. I cannot change the width of the navigation window. If move my mouse over the window border I do not see a resize icon.

This issue doesn't occur on Kubuntu 14.04 maybe it is related to the desktop environment?

**Comment by mnquintana** [comment] 2015-08-13 10:40
Are you running Xubuntu inside VirtualBox?

**Comment by runningman84** [comment] 2015-08-13 15:54
Yes


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: "Machisté N. Quintana" <notifications@github.com> 
Datum: 13.08.2015  12:41  (GMT+01:00) 
An: atom/atom <atom@noreply.github.com> 
Cc: runningman84 <phil@hellmi.de> 
Betreff: Re: [atom] Navigation window too narrow (#8361) 

Are you running Xubuntu inside VirtualBox?

**Comment by muloka** [comment] 2015-08-20 15:53
I'm having a weird issue with scrolling in Lubuntu inside Virtual Box. Not sure if this might be related. Just  Can not select and drag it.

**Comment by mnquintana** [comment] 2015-08-20 16:46
Thanks for the update! This looks like a duplicate of https://github.com/atom/atom/issues/6243 / https://github.com/atom/atom/issues/6219, and should be fixed with https://github.com/atom/atom/pull/7877.

**Closed by mnquintana** 2015-08-20 16:46 UTC
Labels: more-information-needed
