### ISSUE TITLE
Crash on Paste in Ubuntu 

### ISSUE THREAD

**Issue by lambdaburrito** [atom/atom#6328] opened 2015-04-10 12:29 UTC
I have a small project open and, if I paste from an external source (browser, etc), it will crash Atom and will have start a new Atom process. 

I'm on `v.0.189.0`

Let me know if you need any more detailed information if you cannot replicate it.

**Comment by mnquintana** [comment] 2015-04-10 12:38
Closing as duplicate of #6221 – try updating to Atom 0.190.0, which should have fixed this issue. Thanks!

**Closed by mnquintana** 2015-04-10 12:38 UTC
