### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by deepak-codisto** [atom/atom#20340] opened 2020-01-22 07:24 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 16.04.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /usr/share/atom/resources/app/static/<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/usr/share/atom/resources/app/static/<embedded>:11:76051)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.renderLineTiles (/usr/share/atom/resources/app/static/<embedded>:11:75983)
    at TextEditorComponent.renderContent (/usr/share/atom/resources/app/static/<embedded>:11:74509)
    at TextEditorComponent.renderScrollContainer (/usr/share/atom/resources/app/static/<embedded>:11:73969)
    at TextEditorComponent.render (/usr/share/atom/resources/app/static/<embedded>:11:72748)
    at Object.updateSync (/usr/share/atom/resources/app/static/<embedded>:14:132897)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/static/<embedded>:11:70606)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.didMouseWheel (/usr/share/atom/resources/app/static/<embedded>:11:92801)
```

### Commands

```
     -5:40.9.0 core:backspace (input.hidden-input)
     -5:39.7.0 core:save (input.hidden-input)
 29x -5:37 core:move-right (input.hidden-input)
     -5:32.1.0 editor:toggle-soft-wrap (input.hidden-input)
     -5:26 find-and-replace:show (input.hidden-input)
     -5:23.3.0 core:confirm (input.hidden-input)
     -5:22.8.0 editor:consolidate-selections (input.hidden-input)
     -5:22.8.0 core:cancel (input.hidden-input)
     -5:13.1.0 autocomplete-plus:cancel (input.hidden-input)
  2x -5:11.9.0 core:save (input.hidden-input)
     -0:26.8.0 core:copy (input.hidden-input)
     -0:14.2.0 editor:toggle-soft-wrap (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
atom-nodejs-snippets 2.1.1 
expressjs 2.2.0 
react 0.18.0 
remote-sync-pro 5.1.1 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
```

**Comment by AntoineInsa** [comment] 2020-02-20 11:09
1. Paste a json
`{"test":[{"test":"B2B testimonial videos","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"8156de35-27ec-4835-a872-46e6ecd1e485","test":"test","test":"test","test":"B2B testimonial videos","test":"test"},{"test":"Main [Spare parts]","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"080a6dd4-6f63-4b63-82a5-b781a9c879ef","test":"test","test":"test","test":"Spare parts","test":"test"},{"test":"test","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"786b4542-12c4-455a-bc82-7652cf26b222","test":"test","test":"test","test":"Main [Compatibility]","test":"test"},{"test":"Spare parts","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"e8659a6a-7950-4f8f-bbbf-4a27acf4a8ed","test":"test","test":"test","test":"Main [Spare parts]","test":"test"},{"test":"Star view","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"35cd2658-da0d-41d0-a188-dfa457a322ea","test":"test","test":"test","test":"Star view","test":"test"},{"test":"EPDB Images","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"3a0a3bc5-512b-433b-8c2f-770da4a756d2","test":"test","test":"test","test":"EPDB Associated products for Images","test":"test"},{"test":"test","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"ceec1352-799a-49f3-9122-98ca57ed3a08","test":"test","test":"test","test":"test","test":"test"},{"test":"test","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"69a7b898-d3c2-4add-a5e6-d9be7a87e939","test":"test","test":"test","test":"test","test":"35c69411-fccc-46c5-a797-1af3a0c0ddf1"},{"test":"Wiring drawing","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"31f5f8e9-23ae-4bca-a16b-9dbc20dd94aa","test":"test","test":"test","test":"Associated products","test":"test"},{"test":"EPDB Other Medias","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"fd3fff6d-aa61-419b-ba02-8cd24737414e","test":"test","test":"test","test":"EPDB Associated Products","test":"test"},{"test":"test","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"08361039-01f7-4433-94f1-8d7febb4ab89","test":"test","test":"test","test":"test","test":"test"},{"test":"B2C Videos","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"4bac0ad1-9476-47a4-b700-373a6dcb2bc3","test":"test","test":"test","test":"B2C Videos","test":"test"},{"test":"B2B Videos","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"b1b9baf5-dcbb-4d42-865b-9b9f4c010130","test":"test","test":"test","test":"B2B Videos","test":"test"},{"test":"Replacement Of","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"17b762b1-e69a-4e7f-a83a-8303c9ac53ad","test":"test","test":"test","test":"Replaced By","test":"test"},{"test":"test","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"02764055-7b36-49dc-a8e1-308c1d40c388","test":"test","test":"test","test":"Main [Accessories]","test":"test"},{"test":"Replaced By","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"ad048ad4-1ec9-43b5-9bb1-918827624308","test":"test","test":"test","test":"Replacement Of","test":"test"},{"test":"Wiring drawing","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"c43b2162-4e0b-4cba-a457-aeca9c7bad14","test":"test","test":"test","test":"Associated products","test":"test"},{"test":"EPDB Other Medias","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"2488a69c-5937-4508-a7f8-a0b57ea006b3","test":"test","test":"test","test":"EPDB Associated Products","test":"test"},{"test":"EPDB Other Medias","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"03f29284-d8bc-47f3-bfea-9f4e4afda1a1","test":"test","test":"test","test":"EPDB Associated Products","test":"test"},{"test":"3/4","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"93b60843-51c3-48e9-94b4-a0c4d941d097","test":"test","test":"test","test":"3/4","test":"test"},{"test":null,"test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"f2f264fe-45a4-49f6-a598-273a633548f5","test":"3ad37527-2b8c-49cd-9530-c8d4ff02cd3b","test":"test","test":null,"test":null},{"test":"DIY Installation tips","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"1df8e6e9-ce44-4917-99a1-14b779108584","test":"test","test":"test","test":"Associated products","test":"45666f52-93df-428c-aff3-7904f838f89a"},{"test":"test","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"60713950-81fe-4d5c-8fd4-3e6503c19cef","test":"test","test":"test","test":"test","test":"546e700e-bc8d-417a-8082-bd2e36a1b68f"},{"test":"Star view","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"a67c9881-a882-43d3-bc68-8ab68b7eed09","test":"test","test":"test","test":"Star view","test":"8c65f487-e16f-4e88-962d-e10b4081a21f"},{"test":"test","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"daa462a3-395d-46e7-80ef-8a357bd08e39","test":"test","test":"test","test":"test","test":"test"}],"test":[],"test":[],"test":[],"test":[{"test":"test","test":null,"test":{"test":{"test":"test","test":{},"test":null},"test":{"test":{},"test":[],"test":{}}},"test":"8c814336-f393-43bf-bfb8-9d4a560b8ee5","test":"3ad37527-2b8c-49cd-9530-c8d4ff02cd3b","test":"test","test":"test","test":"test"}],"test":[{"test":["test","test","test"],"test":"test","test":"NINA TIMER IO","test":"test","test":["test","test","test","test","test","test"],"test":{"test":{"test":null,"test":"<p><span style=\"color: rgb(147, 101, 184);\">19/02/2020 NL BE</span><br>NL-BE - ANGE - Nina Timer io is een eenvoudige en intu&iuml;tieve groepsbediening met een ergonomische vormgeving, een touch screen en een ingebouwde timer. 20200214</p>","test":"<p>NL-BE - ANGE - </p>","test":"null;°C","test":"NL-BE - ANGE -","test":"3.700;V","test":"999.00;EUR","test":"null;mm","test":"null;mm","test":"999.000;kg","test":"FR - BE - ANGE -","test":"NL-BE - ANGE - information","test":null,"test":"999.000;m2","test":"NINA TIMER IO","test":"999.000;cm","test":"999.000;mm","test":"68.000000;mm","test":"<p>FR - BE - ANGE -</p>","test":null,"test":"null;m","test":"999.00;EUR","test":null,"test":"19/02/2020 NL-BE 2\n Ange NINA TIMER IOV 20200214","test":null,"test":"null;W","test":"999.000;mm","test":"null;W","test":"999.000;°C","test":"test","test":"NINA IO & NINA TIMER IO","test":null,"test":"null;W","test":null,"test":"test","test":null,"test":"159.800;mm","test":"6ac2a024-cf01-47f6-9c15-2d09aa290d1f","test":"NL-BE - ANGE - Autonomy","test":null,"test":"<p><span style=\"color: rgb(147, 101, 184);\">19/02/2020&nbsp;</span>ANGE - NL-BE - ANGE - NINA TIMER IO is een groepsbediening, ideaal voor o.a. rolluiken 20200214</p>","test":"<p>NL- BE- ANGE-</p>","test":"test","test":"<p>NL-BE - ANGE -</p>","test":"999.000;mm","test":"<p>NL-BE - ANGE - NINA TIMER IO 20200214</p>","test":"null;W","test":"FR - BE - ANGE -","test":"999.000;mm","test":null,"test":"test","test":null,"test":null,"test":"2019-11-09 21:15:23.015","test":"test","test":"test","test":null,"test":"test","test":"<ul><li>19/02/2010 NL-BE<br>&nbsp;- ANGE -</li><li>Meer bedieningsgemak</li><li>Bedien verschillende toepassingen individueel, per groep of automatische via de timer</li><li>Personaliseer de interface</li><li>Pas hem aan aan de indeling van uw woning</li><li>Benoem verschillende kamers</li><li>Benoem verschillende scenario&rsquo;s</li><li>Nauwkeurige bediening</li><li>Met een eenvoudige beweging op het touchscreen</li><li>Het icoontje laat de exacte positie van de toepassing zien</li><li>Cre&euml;er automatische scenario&rsquo;s<br>Bepaal in enkele clicks hoe je wil leven...</li><li>De timer zal geprogrammeerde scenario&rsquo;s automatisch uitvoeren op de gewenste tijden</li><li>Scenario&rsquo;s kunnen ook manueel geactiveerd worden</li><li>Meer veiligheid</li><li>De aanwezigheidssimulatie laat toe de scenario&rsquo;s op wisselende tijden uitvoeren, zodat de woning steeds bewoond lijkt</li><li>Meer energiebesparing<br>Laat de geprogrammeerde tijden mee evolueren volgens zonsondergang voor een optimale isolatie van uw woning met uw rolluiken</li></ul><p>NL-BE - ANGE - 2</p><p>NL-BE - ANGE - 3</p><p>NL-BE - ANGE - 4</p><p>NL 20200214</p>","test":"<p><br></p><ul><li>19/02/2020 NL-BE - <br>ANGE -</li><li>Meer bedieningsgemak</li><li>Bedien verschillende toepassingen individueel, per groep of automatische via de timer</li><li>Personaliseer de interface</li><li>Pas hem aan aan de indeling van uw woning</li><li>Benoem verschillende kamers</li><li>Benoem verschillende scenario&rsquo;s</li><li>Nauwkeurige bediening</li><li>Met een eenvoudige beweging op het touchscreen</li><li>Het icoontje laat de exacte positie van de toepassing zien</li><li>Cre&euml;er automatische scenario&rsquo;s<br>Bepaal in enkele clicks hoe je wil leven...</li><li>De timer zal geprogrammeerde scenario&rsquo;s automatisch uitvoeren op de gewenste tijden</li><li>Scenario&rsquo;s kunnen ook manueel geactiveerd worden</li><li>Meer veiligheid</li><li>De aanwezigheidssimulatie laat toe de scenario&rsquo;s op wisselende tijden uitvoeren, zodat de woning steeds bewoond lijkt</li><li>Meer energiebesparing<br>Laat de geprogrammeerde tijden mee evolueren volgens zonsondergang voor een optimale isolatie van uw woning met uw rolluiken</li></ul><p>20200214 NL-BE - ANGE - 1</p><p>NL-BE - ANGE - 2</p><p>NL-BE - ANGE - 3</p><p>NL-BE - ANGE - 4</p><p>NL 20200214</p><p>FR-BE AC 2020-02-18 1634</p>","test":"69.900002;mm","test":null,"test":"null;Nm","test":"<p>FR - NL - ANGE -<br>FR - NL - ANGE -</p><p>FR - NL - ANGE -</p><p>FR - NL - ANGE -</p><p>FR - NL - ANGE -</p><p><br></p>","test":null,"test":null,"test":null,"test":null,"test":null,"test":null,"test":"999.000;mm","test":"null;m","test":"100.000;V","test":"test","test":null,"test":null,"test":"null;°C","test":"test","test":"NL-BE - ANGE - limit of use","test":"240.000;V","test":null,"test":"<p>FR-BE AC 2020-02-18 1634</p>","test":null,"test":"<p>NL-BE - ANGE - 4</p>","test":"<p>NL 20200214</p>","test":"<p>NL-BE - ANGE - 2</p>","test":null,"test":"null;mm","test":"2020-02-20 10:36:55.036","test":"45.000;°C","test":"<p>NL-BE - ANGE - 3</p>","test":"<p>NL- BE- ANGE-</p>","test":"FR - BE - ANGE -","test":"<p><br></p><ul><li>19/02/2020 NL-BE - <br>ANGE -</li><li>Meer bedieningsgemak</li><li>Bedien verschillende toepassingen individueel, per groep of automatische via de timer</li><li>Personaliseer de interface</li><li>Pas hem aan aan de indeling van uw woning</li><li>Benoem verschillende kamers</li><li>Benoem verschillende scenario&rsquo;s</li><li>Nauwkeurige bediening</li><li>Met een eenvoudige beweging op het touchscreen</li><li>Het icoontje laat de exacte positie van de toepassing zien</li><li>Cre&euml;er automatische scenario&rsquo;s<br>Bepaal in enkele clicks hoe je wil leven...</li><li>De timer zal geprogrammeerde scenario&rsquo;s automatisch uitvoeren op de gewenste tijden</li><li>Scenario&rsquo;s kunnen ook manueel geactiveerd worden</li><li>Meer veiligheid</li><li>De aanwezigheidssimulatie laat toe de scenario&rsquo;s op wisselende tijden uitvoeren, zodat de woning steeds bewoond lijkt</li><li>Meer energiebesparing<br>Laat de geprogrammeerde tijden mee evolueren volgens zonsondergang voor een optimale isolatie van uw woning met uw rolluiken</li></ul>","test":"null;mm","test":"<p>20200214 NL-BE - ANGE - 1</p>","test":"NINA TIMER IO","test":"<p><span style=\"color: rgb(147, 101, 184);\">19/02/2020 NL BE</span><br>NL-BE - ANGE - <strong>Nina Timer io is een eenvoudige en intu&iuml;tieve groepsbediening met een ergonomische vormgeving, een touch screen en een ingebouwde timer.</strong></p><ul><li>Bevelen kunnen afzonderlijk per dag ingesteld worden</li><li>Max aantal type dagen: 8</li><li>Max aantal bevelen per type dag: 12</li><li>Max aantal toepassingen: 50</li><li>Max aantal groepen: 30</li><li>Max aantal scenario&rsquo;s: 15</li><li>Eenvoudig in- en uitschakelen van de timer functie of van het activeren van de aanwezigheidssimulatie of van de zonsondergangcurve</li><li>Lader en laadstation standaard meegeleverd</li></ul><p><br></p><p>20200214</p>","test":"null;W","test":"null;mm","test":"999.000;cm","test":null,"test":null,"test":null,"test":"null;W","test":null,"test":null,"test":null,"test":"null;W","test":null,"test":null,"test":"null;m","test":"999.000;mm","test":"null;kg","test":null,"test":"NL-BE - ANGE - NINA TIMER IO","test":"250.000;m","test":"<ul><li>19/02/2010 NL-BE<br>&nbsp;- ANGE -</li><li>Meer bedieningsgemak</li><li>Bedien verschillende toepassingen individueel, per groep of automatische via de timer</li><li>Personaliseer de interface</li><li>Pas hem aan aan de indeling van uw woning</li><li>Benoem verschillende kamers</li><li>Benoem verschillende scenario&rsquo;s</li><li>Nauwkeurige bediening</li><li>Met een eenvoudige beweging op het touchscreen</li><li>Het icoontje laat de exacte positie van de toepassing zien</li><li>Cre&euml;er automatische scenario&rsquo;s<br>Bepaal in enkele clicks hoe je wil leven...</li><li>De timer zal geprogrammeerde scenario&rsquo;s automatisch uitvoeren op de gewenste tijden</li><li>Scenario&rsquo;s kunnen ook manueel geactiveerd worden</li><li>Meer veiligheid</li><li>De aanwezigheidssimulatie laat toe de scenario&rsquo;s op wisselende tijden uitvoeren, zodat de woning steeds bewoond lijkt</li><li>Meer energiebesparing<br>Laat de geprogrammeerde tijden mee evolueren volgens zonsondergang voor een optimale isolatie van uw woning met uw rolluiken</li></ul>","test":"NINA TIMER IO","test":"999.000;W","test":"null;A","test":"test","test":"0.999;kg","test":"NINA TIMER IO","test":"FR - BE - ANGE -","test":null,"test":"null;W","test":"https://www.somfy.it/","test":"null;mm","test":null,"test":null,"test":"<ul><li>1 Nina Timer io (including 1 Lithium battery)</li><li>1 dock station</li><li>1 Power cable</li></ul>","test":"null;mm","test":null,"test":"https://www.somfy.de/","test":"https://www.somfy.fr/","test":null,"test":null,"test":null,"test":null,"test":null,"test":"<p>NL-BE - ANGE - 4</p>","test":"<p>NL 20200214</p>","test":"<p>NL-BE - ANGE - 2</p>","test":"<p>NL-BE - ANGE - 3</p>","test":"null;mm²","test":"null;min","test":"0.300;A","test":null,"test":"999.000;mm","test":null,"test":null,"test":"null;mm","test":"null;mm","test":"2019-01-01","test":null,"test":"null;W"},"test":[],"test":{"test":["test"],"test":["test"],"test":[],"test":["test","test","test","test","test","test","test"],"test":["test"],"test":[],"test":[],"test":["test"],"test":["test"],"test":["test"],"test":[],"test":[],"tag_control_&_communication":["test"],"test":["test"],"tag_pet-friendly":["test"],"test":[],"test":["test","test"],"test":["test"],"test":["test"],"test":[],"test":[],"test":[],"test":[],"test":[],"test":["test","test","test"],"test":[],"test":[],"test":["test"],"test":[],"test":["test"],"test":["test"],"test":["test"],"test":[],"test":["test"],"test":["test"],"test":["test"],"test":[],"test":["test"],"test":[],"test":["test"],"test":["test"],"test":["test"],"test":[],"test":["test","test","test","test","test","test","test"],"test":[],"test":["test"],"test":[],"test":[],"test":[],"test":["test"],"test":[],"test":[],"test":["test"],"test":["test"],"test":[],"test":[],"test":[],"test":[],"test":[],"test":["test"],"test":[],"test":[],"test":[],"test":["test"],"test":[],"test":["test"]}}}]}`

2. Try to format the json with "atom-beautify:beautify-language-json"
3. See error

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\censan01\AppData\Local\atom\app-1.44.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'id' of undefined
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:105505)
    at Map.forEach (<anonymous>)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:105387)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:70978)
    at e.readDocument (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:68094)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:325951)
```

### Commands

```
     -2:15.8.0 core:backspace (input.hidden-input)
  3x -2:11.6.0 core:move-right (input.hidden-input)
     -2:02.6.0 core:backspace (input.hidden-input)
     -2:02.4.0 core:move-right (input.hidden-input)
  6x -1:57.6.0 core:backspace (input.hidden-input)
     -1:55.4.0 core:save (input.hidden-input)
     -0:53.1.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:52.4.0 core:paste (input.hidden-input)
     -0:51.3.0 command-palette:toggle (input.hidden-input)
     -0:50.3.0 core:confirm (input.hidden-input)
     -0:50.3.0 atom-beautify:beautify-language-json (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.33.4 
one-liner 0.1.3 
python-indent 1.2.3 
remote-ftp 2.2.2 
sort-lines 0.19.0 
split-diff 1.6.1 
vim-mode-plus 1.36.3 
```

**Comment by tetramin** [comment] 2020-04-01 19:18
I have the same issue in many cases.

**Comment by sadick254** [comment] 2020-09-18 09:59
@deepak-codisto Thank you for opening the issue. Am not able to reproduce this on the latest version of atom. `v1.51.0`. Am closing this for now but let me know if after upgrading to the latest version of atom you still have the same issue. Happy to reopen this on confirmation.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5238135/93584726-6148ad00-f9ae-11ea-83e6-3f5ec9f53344.gif)

**Closed by sadick254** 2020-09-18 09:59 UTC
