### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by vertextao** [atom/atom#14229] opened 2017-04-17 01:42 UTC
[Enter steps to reproduce:]

1. right click on a file
2. open with... -> Atom

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Windows version 14393.1066
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Invalid string length

```
At C:\Users\xtao\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\pathwatcher\lib\file.js:310

RangeError: Invalid string length
    at Array.join (native)
    at /app.asar/node_modules/pathwatcher/lib/file.js:310:38)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-ctags 5.0.0 
atomic-rtags 1.3.0 
busy-signal 1.3.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
language-cmake 0.3.0 
last-cursor-position 0.9.2 
linter 2.1.2 
linter-ui-default 1.2.2 
```

**Comment by rsese** [comment] 2017-04-17 07:40
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/7210. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-17 07:40 UTC
