### ISSUE TITLE
Uncaught Error: ENOENT, node_modules/keybinding-resolver/keymaps/keybinding-resolver.json not found in /usr/share/atom/resources/app.asar

### ISSUE THREAD

**Issue by denissonleal** [atom/atom#6524] opened 2015-04-27 01:39 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: linux 3.11.10-29-desktop
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, node_modules/keybinding-resolver/keymaps/keybinding-resolver.json not found in /usr/share/atom/resources/app.asar

```
At /usr/share/atom/resources/app.asar/src/workspace.js:457

Error: ENOENT, node_modules/keybinding-resolver/keymaps/keybinding-resolver.json not found in /usr/share/atom/resources/app.asar
    at createNotFoundError (ATOM_SHELL_ASAR.js:101:13)
    at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:156:25)
    at ReadStream.open (fs.js:1668:6)
    at new ReadStream (fs.js:1655:10)
    at Object.fs.createReadStream (fs.js:1610:10)
    at File.module.exports.File.read (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:286:27)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:948:61)
    at TextBuffer.module.exports.TextBuffer.load (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:974:19)
    at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app.asar/src/project.js:446:21)
    at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app.asar/src/project.js:416:63)
```

### Commands

```
  3x -1:02.2.0 editor:copy-path (atom-text-editor.editor.is-focused)
  2x -1:00.8.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:09.3.0 key-binding-resolver:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {
      "eol": "\\n"
    },
    "showInvisibles": true,
    "softWrap": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-04-27 12:01
Duplicate of #6511 which will be fixed in the next Atom version, 0.195.0.

**Closed by 50Wliu** 2015-04-27 12:01 UTC
