### ISSUE TITLE
Style tag commenting inside HTML file

### ISSUE THREAD

**Issue by pragnesh-farmin** [atom/atom#13053] opened 2016-10-23 06:50 UTC
### Prerequisites

* [Yes] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [Yes] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [No ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [No] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Yes ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Yes] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
Issue: While commenting style tag in HTML file it is getting commenting format(/* */) of CSS style sheet. 
Correct Flow: It should have commenting style of HTML() if comment has been applied to style tags inside html file.

### Steps to Reproduce

1. Have inline CSS content into html file
2.  Comment style tag inside html file using CTRL + /

**Expected behavior:** [What you expected to happen]
It should have commenting style of HTML() if comment has been applied to style tags inside html file.

**Actual behavior:** [What actually happened]
While commenting style tag in HTML file it is getting commenting format(/* */) of CSS style sheet.

### Versions
1.11.2

**Comment by 50Wliu** [comment] 2016-10-23 16:02
This is a duplicate of atom/language-html#120 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-23 16:02 UTC
