### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by despicablebapple** [atom/atom#5484] opened 2015-02-10 18:49 UTC
[Enter steps to reproduce below:]

1. ... Opened big file
2. ... Error Happened
![screen shot 2015-02-10 at 18 48 43](https://cloud.githubusercontent.com/assets/9384542/6133929/79b1bc44-b155-11e4-85a6-ec9d5ccee37f.png)

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Users/Archie/Applications/Atom.app/Contents/Resources/app/src/project.js:355

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Users/Archie/Applications/Atom.app/Contents/Resources/app/src/project.js:355:15)
  at Project.module.exports.Project.bufferForPath (/Users/Archie/Applications/Atom.app/Contents/Resources/app/src/project.js:332:63)
  at Project.module.exports.Project.open (/Users/Archie/Applications/Atom.app/Contents/Resources/app/src/project.js:286:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Users/Archie/Applications/Atom.app/Contents/Resources/app/src/workspace.js:485:29)
  at Workspace.module.exports.Workspace.open (/Users/Archie/Applications/Atom.app/Contents/Resources/app/src/workspace.js:412:19)
  at Ipc.<anonymous> (/Users/Archie/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Users/Archie/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-02-10 18:51
Duplicate of #307

**Comment by kevinsawicki** [comment] 2015-02-10 18:51
Please subscribe to #307 for updates on when this issue is resolved.

**Comment by benogle** [comment] 2015-02-10 18:52
Please update atom. The latest version has much a better message for this issue.

**Closed** 2015-02-10 18:51 UTC
