### ISSUE TITLE
Hide VCS Ignored Files not working when Git root is above project root

### ISSUE THREAD

**Issue by laurie71** [atom/atom#15123] opened 2017-07-29 05:21 UTC
With Hide VCS Ignored Files enabled in the tree-view package's settings (and Exclude VCS Ignored Paths disabled in the Core settings), files matching patterns in .gitignore in a parent directory  of the project directory are not hidden. The project root must also be the Git root for the feature to work.

In large projects, I commonly open a sub-project in atom if my work will only touch files in that sub-project. It would be nice if Atom would recognize that there is an enclosing git repository in a parent directory, and respect it and it's ignore file.

The files that should be ignored *do* get greyed out, but they are still visible. If I open the root directory of the larger project (where .git lives) though, the files are entirely hidden. I'd like them hidden when I open a sub-directory or the project root too.

**Comment by rsese** [comment] 2017-08-01 23:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/2203. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-01 23:47 UTC
