### ISSUE TITLE
Menu bar keyboard shortcuts conflict

### ISSUE THREAD

**Issue by medowlock** [atom/atom#5435] opened 2015-02-06 14:04 UTC
When the "Auto Hide Menu Bar" is enabled in the settings, some of the keyboard combinations to bring it up do not work, because they seem to conflict with other assignments eg Alt + f and Alt + h

To reproduce:
1. Check "Auto Hide Menu Bar" in settings
2. Have a file opened
3. Clicking Alt + f will behave like Ctrl + Right arrow, instead of opening the "File" popup from the menu bar

**Comment by 50Wliu** [comment] 2015-02-06 16:48
Duplicate of #4057, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-06 16:48 UTC
