### ISSUE TITLE
Possible to sort sidebar files by kind?

### ISSUE THREAD

**Issue by corysimmons** [atom/atom#13425] opened 2016-12-11 21:52 UTC
![image](https://cloud.githubusercontent.com/assets/224636/21083615/2211ab70-bfc2-11e6-8038-7b495f03a4ef.png)

Looked for settings/plugins, found nothing. Feature request if doesn't exist.

**Comment by 50Wliu** [comment] 2016-12-11 22:49
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/552. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-11 22:49 UTC
