### ISSUE TITLE
Mac os (El Capitan) crash all instances after closing window

### ISSUE THREAD

**Issue by Yontih** [atom/atom#9692] opened 2015-11-19 07:33 UTC
Attached dump.

[atom_dump.txt](https://github.com/atom/atom/files/38712/atom_dump.txt)

**Comment by joaosamouco** [comment] 2015-11-19 09:24
Same happens to me when I have three instances of Atom in full-screen mode and close one of them.

**Comment by izuzak** [comment] 2015-11-19 14:04
Thanks for the report, @Yontih 

cc @zcbenz -- there's a crash report attached.

**Comment by 50Wliu** [comment] 2015-11-19 22:06
Refs #9584.

**Comment by LexGear** [comment] 2015-11-19 22:42
Yes, same issue for me after Unity opens an atom window and I close it. Whole program crashes. El Capitan.

**Comment by LaurentGoderre** [comment] 2015-11-20 14:31
I have this behavior too but only when I close the config folder

**Comment by OmgImAlexis** [comment] 2015-11-22 03:12
Same for me, I closed a window and it instantly crashes. [Here's the crash report](https://gist.github.com/OmgImAlexis/f0dd94fa9ae539f191ca).

**Comment by chachan** [comment] 2015-11-23 16:09
Same here, seems to be happening only when one the the windows is in full-screen mode

**Comment by faceair** [comment] 2015-11-23 16:16
Same for me.

[atom_dump.txt](https://github.com/atom/atom/files/41767/atom_dump.txt)

**Comment by zcbenz** [comment] 2015-11-26 05:21
From the crash report, this is a duplicate of #9584.

**Closed by zcbenz** 2015-11-26 05:21 UTC
Labels: crash, mac

**Comment by Ecleptic** [comment] 2015-12-17 18:42
Mine still crashes. Full screen just one tab open or with 3, it doesn't matter. I Hit Cmd-Q and get a crash.
[Crashdump.txt](https://github.com/atom/atom/files/65805/Crashdump.txt)

**Comment by 50Wliu** [comment] 2015-12-17 20:27
@Ecleptic please update to the 1.4.0 betas.
