### ISSUE TITLE
Tree view and status bar show files with accented characters as new

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1890] opened 2014-04-22 14:53 UTC
Halp ticket:
- support/6c407d52c9f711e38a0cc47a4027f259

> Git support does not handle files with accented characters correctly, declaring them as new. See e.g spec/fixtures/subdir/áccéntéd.svg in atom/markdown-preview or lloeki/svg-preview plugins.

Steps to reproduce:

```
$ git clone  https://github.com/lloeki/svg-preview
$ cd svg-preview
$ atom .
```

Notice that there's a file marked as new in the tree view -- `spec/fixtures/subdir/áccéntéd.svg`.

![dbb695e0-ca24-11e3-9ef4-e37cbd560a08](https://cloud.githubusercontent.com/assets/38924/2766300/8021b38c-ca2d-11e3-95fc-973f0db52106.png)

However, I can't reproduce this issue with the markdown-preview repository which has a file with the same name.

**Comment by as-cii** [comment] 2015-02-12 14:49
Some updates on this. First some pieces of information about my machine:

**Git version**: 2.3.0
**Atom version**: master

I have cloned the mentioned repository and, even without explicitly setting `core.precomposeunicode true`, git correctly recognizes the file (e.g. `git status` is clean). However, libgit2 has a different behavior: in facts, without setting the config variable, it works as @izuzak illustrated earlier; in particular Atom detects two statuses:

```json
{
  "spec/fixtures/subdir/áccéntéd.svg": 128, 
  "spec/fixtures/subdir/áccéntéd.svg": 512
}
```

Those statuses indicate that such file was both new and deleted. I tried to see if [libgit2/rugged](https://github.com/libgit2/rugged) behaved the same way, and it does.

After that, I ran `git config —global core.precomposeunicode true` and rugged (both v0.21.4 and 0.21.2) stopped acting strangely, reporting the same results as git. The same goes for [libgit2/libgit2 (latest)](https://github.com/libgit2/libgit2): compiling it and using [status](https://github.com/libgit2/libgit2/blob/master/examples/status.c) behaves exactly as `git status`, so no weird behavior.

Analogously, I expected [git-utils (latest)](https://github.com/atom/git-utils) or [gitteh (latest)](https://github.com/libgit2/gitteh) or [nodegit (latest)](https://github.com/nodegit/nodegit) to do the same; unfortunately (and with my surprise) this is not the case. For some reason, all the aforementioned node bindings won’t detect the change in configuration, even though they use exactly the same functions as rugged (namely, `git_status_foreach`).

There must be something different between libgit2/libgit2 (or rugged) and git-utils (or gitteh, etc.): the most evident thing I could find out is the build system, but I am not sure how that could influence this specific behavior.

Ultimately, I believe this issue belongs more to git-utils rather than Atom core itself.

**Comment by morberg** [comment] 2015-02-18 07:15
As mentioned in the now closed duplicate #4637 it works fine under Windows, but not OS X.

**Comment by UnquietCode** [comment] 2015-06-17 17:48
I'm not sure if I'm experiencing this particular issue, but on OS X the untracked files in my repository show as new (green) in the tree view.

**Comment by javawizard** [comment] 2015-08-26 22:09
@UnquietCode I'm experiencing that as well, but I'm pretty sure it's a completely separate issue. I'm opening a new issue for it.

**Comment by yudai-nkt** [comment] 2015-10-12 11:38
In [atom/tree-view/issues/460](https://github.com/atom/tree-view/issues/460), which is a duplicate of this one, the opener says "oddly Japanese characters don't cause the issue", but I could reproduce the same problem with a directory whose name contains CJK characters. It occurs both in tree view and in status bar.

In my case, a certain directory becomes orange although there are no uncommitted changes. Files under the incorrectly colored directory are shown in white at first. However, if I open one of them, its color changes to green.

Running `git status` tells me that the directory is up-to-date, so I suppose this is a problem of Atom rather than of Git.

Just informing you.

**Comment by sh01ch1** [comment] 2016-04-15 03:00
For your information, I found the following behaviors and expectations:

* It's not about all the non-ascii characters:
    * áccéntéd.svg: NG
    * Webデザイン.md: NG
    * abcからの移行: OK

* I wrote a test code for the git-utils methods and found that:
    * `isPathNew(ng_filepath)` returns true; expected to be false
    * `getStatus(ng_filepath)` returns 512 or 128; I have no idea about this

Same as as-cli, I think that there's a problem in git-utils and/or libgit2.

#### Tested versions
* ATOM: 1.6.2
* apm: 1.6.0
* npm: 2.13.3
* node: 0.10.40
* python: 2.7.10
* git: 2.6.0
* OS: Mac OS X 10.10.5

**Comment by M0rtenB** [comment] 2016-05-09 11:16
I'm experiencing this issue as well (a file with an accent in its name shows up as new in Atom though 'git status' is clean). It might have to do with the fact that HFS+ stores Unicode filenames normalized to NFD? For what it's worth, GitKraken makes the same mistake.

**Comment by brunobord** [comment] 2017-04-27 20:39
as far as I can say, this bug is still there. :(

**Comment by z00m1n** [comment] 2018-03-21 11:39
I upgraded to version 1.25.0 this morning; the issue persists.

**Comment by sadick254** [comment] 2020-08-25 03:48
I am unable to reproduce this on the latest version of atom `1.50`. Incase someone on this thread is able to reproduce the issue I am happy to reopen this issue

```
OS: macOS Catalina 10.15.6
Atom    : 1.50.0 
Electron: 5.0.13
Chrome  : 73.0.3683.121
apm  2.5.0
npm  6.14.5 
node 10.20.1 x64
python 2.7.16 
git 2.24.3
```

**Closed by sadick254** 2020-08-25 03:48 UTC
Labels: bug, git, mac, triaged

**Comment by dd-ssc** [comment] 2020-08-28 11:50
Still occurs here.

From _About Atom_:

```
Atom: 1.50.0
Electron: 5.0.13
Chrome: 73.0.3683.121
Node: v12.0.0
```

Some more version info:

```
$ npx envinfo --system --binaries --browsers

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 2.29 GB / 16.00 GB
    Shell: 5.0.18 - /usr/local/bin/bash
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
    Safari: 13.1.2

$ apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 2.7.16
git 2.28.0
```
