### ISSUE TITLE
The workbench should remember the recently opened project

### ISSUE THREAD

**Issue by antonarhipov** [atom/atom#4833] opened 2015-01-03 00:33 UTC
Currently, if I close the editor and open it again, I have to go through the same steps to open the project again. Why not to remember the previously opened project and open it automatically once the user starts the editor?

**Comment by lee-dohm** [comment] 2015-01-03 01:16
This is a duplicate of #1603 and its related Issues. Please subscribe there for updates.

**Closed by lee-dohm** 2015-01-03 01:16 UTC
