### ISSUE TITLE
Writing """ `ALTER` """ breaks code highlighting 

### ISSUE THREAD

**Issue by sunnyakaxd** [atom/atom#17288] opened 2018-05-07 14:35 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Writing `` `ALTER` `` in triple quote (multiline string) renders highlighting of rest of the code as string in py files.

### Steps to Reproduce

1. Open a .py file
2. Type `` """`ALTER`""" ``anywhere

**Expected behavior:** Only ``"""`ALTER`"""`` should appear string like. (green)

**Actual behavior:** Rest of the code is highlighted as string.

**Reproduces how often:** Always

### Versions 
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

![before](https://user-images.githubusercontent.com/14350421/39707340-c30eb3bc-5231-11e8-9847-aab2ddc87100.png)

![after](https://user-images.githubusercontent.com/14350421/39707355-cec8dbf6-5231-11e8-8597-4b4769f0e5aa.png)
You can see that adding alter in backticks **`** causes rest of the code to become green.

**Comment by rsese** [comment] 2018-05-07 22:00
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/language-python/issues/143 so you can subscribe there for updates if you'd like.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-07 22:00 UTC
