### ISSUE TITLE
Failure in creating a New folder when Filename with same name exists

### ISSUE THREAD

**Issue by spiritson** [atom/atom#6159] opened 2015-03-30 05:42 UTC
![bugatomnewfolder](https://cloud.githubusercontent.com/assets/9888690/6890676/b74d6efc-d664-11e4-9e83-cdd673115e73.png)

When we try to create a New Folder, it results in a failure if there is already a file with same name in the corresponding folder.

The image attached should be self explanatory.

**Comment by 50Wliu** [comment] 2015-03-30 11:59
Could you please move this over to the atom/tree-view repository?  Thanks.

**Comment by izuzak** [comment] 2015-03-30 15:18
Looks like a duplicate of https://github.com/atom/tree-view/issues/31.

**Closed by izuzak** 2015-03-30 15:18 UTC
