### ISSUE TITLE
Error upon .coffee.md file opening

### ISSUE THREAD

**Issue by cesarBere** [atom/atom#9624] opened 2015-11-16 12:40 UTC
Hi, 

I get the following error when opening any `.coffee.md` file
I don't have any syntax coloration on the file
Used to run well 

[Enter steps to reproduce below:]

1. open atom
2. open any `.coffee.md` file

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: end pattern with unmatched parenthesis

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:31

Error: end pattern with unmatched parenthesis
    at Error (native)
    at Scanner.module.exports.Scanner.createScanner (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:99:28)
    at Rule.module.exports.Rule.getNextTags (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/rule.js:141:21)
    at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar.js:150:44)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:546:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:532:19)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:292:43)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:269:26
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Source Code Pro",
    "showIndentGuide": true,
    "scrollPastEnd": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
atom-jade, v0.3.0
highlight-line, v0.11.0
language-cjsx, v0.3.0
language-scala, v1.1.4

# Dev
No dev packages
```

**Comment by abe33** [comment] 2015-11-16 13:29
It looks like there's a faulty regular expression in coffee literate grammar, but I couldn't pinpoint it yet. I'll take some time to find it later.

**Comment by 50Wliu** [comment] 2015-11-16 13:45
Duplicate of atom/language-coffee-script#71, please subscribe there for updates.
Sorry about this.

**Closed by 50Wliu** 2015-11-16 13:45 UTC
Labels: bug

**Comment by cesarBere** [comment] 2015-11-16 13:49
Will do, sorry for the duplicate
