### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by iNegga** [atom/atom#7711] opened 2015-07-04 23:18 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
    at HTMLDocument.handler (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\abdou\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
  2x -9:56.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:39.3.0 editor:newline (atom-text-editor.editor.is-focused)
 20x -9:35.6.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -3:15.6.0 core:copy (atom-text-editor.editor.is-focused)
     -3:08.6.0 core:paste (atom-text-editor.editor.is-focused)
     -3:01.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:45.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:11.6.0 core:copy (atom-text-editor.editor.is-focused)
     -1:01.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:01.0 core:paste (atom-text-editor.editor.is-focused)
     -0:48.8.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:33 core:copy (atom-text-editor.editor.is-focused)
     -0:26.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:23.8.0 core:backspace (atom-text-editor.editor.is-focused)
  9x -0:22.2.0 core:delete (atom-text-editor.editor.is-focused)
  3x -0:09.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-07-04 23:19
Duplicate of #6548 - this has been fixed for the next version of Atom.

**Closed by mnquintana** 2015-07-04 23:19 UTC
