### ISSUE TITLE
markdown-preview can not display the Chinese

### ISSUE THREAD

**Issue by mengzyou** [atom/atom#6389] opened 2015-04-15 15:33 UTC
When write the markdown in Chinese, but display boxes in the preview, see below screenshot:  
![atom_markdown_preview_cn_issue](https://cloud.githubusercontent.com/assets/360603/7162513/a243b8de-e3c7-11e4-8bfc-0be52f0defe4.png)
  
The atom version is **v0.191.0**.  
Running on openSUSE 13.2 .

**Comment by 50Wliu** [comment] 2015-04-15 15:53
Duplicate of atom/markdown-preview#238, please subscribe there for updates.
Also see #6214 for a similar issue.

**Closed by 50Wliu** 2015-04-15 15:53 UTC
