### ISSUE TITLE
Atom does not show installed community packages after update to v1.0.2

### ISSUE THREAD

**Issue by weblogixx** [atom/atom#8022] opened 2015-07-22 06:02 UTC
Hi all,

I got a problem with displaying the installed community packages in my atom installation.
Before the upgrade to 1.0.2 (and much package upgrades...) I was able to see all installed packages in the atom gui. After the last upgrade, I only see 3 of them (see attached screenshot). This issue seems to have nothing to do with a skin (I resetted id and the problem persisted) or plugin (tested it without plugins, too), all plugins seem to run fine. If I search them in Settings -> Install I am able to configure their settings, too. Local apm does also list all installed plugins correctly, updates are retrieveable.

On the other side, I get a full listing of all installed Core Packages

Would be thankful for your suggestions.

![screen1](https://cloud.githubusercontent.com/assets/757613/8818927/31e93df8-3047-11e5-851f-313015981604.jpg)

**Comment by mnquintana** [comment] 2015-07-22 14:34
This is a duplicate of https://github.com/atom/settings-view/issues/591 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-22 14:34 UTC

**Comment by bantya** [comment] 2017-03-15 21:00
You may check console for further info.

It can be caused by cloning a package manually and not installing node dependancies.

If any such package exists which demands to install node dependencies, then do run `npm install` or `yarn`

I had the same problem but following above given steps it solved my problem..
