### ISSUE TITLE
Uncaught Error: ENOENT,  not found in /Users/BesmondFoong/Downloads/Atom.app/Contents/Resources/a...

### ISSUE THREAD

**Issue by besmond** [atom/atom#7727] opened 2015-07-06 07:09 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT,  not found in /Users/BesmondFoong/Downloads/Atom.app/Contents/Resources/atom.asar

```
At /Users/BesmondFoong/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:466

Error: ENOENT,  not found in /Users/BesmondFoong/Downloads/Atom.app/Contents/Resources/atom.asar
    at createNotFoundError (ATOM_SHELL_ASAR.js:101:13)
    at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:156:25)
    at ReadStream.open (fs.js:1668:6)
    at new ReadStream (fs.js:1655:10)
    at Object.fs.createReadStream (fs.js:1610:10)
    at File.module.exports.File.read (/Users/BesmondFoong/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:286:27)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (/Users/BesmondFoong/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1027:61)
    at TextBuffer.module.exports.TextBuffer.load (/Users/BesmondFoong/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1046:19)
    at Project.module.exports.Project.buildBuffer (/Users/BesmondFoong/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:456:21)
    at Project.module.exports.Project.bufferForPath (/Users/BesmondFoong/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:431:63)
```

### Commands

```
     -0:52.5.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "archive-view"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-07-06 17:44
Thanks for the report -- seems to be a duplicate of https://github.com/atom/atom/issues/6140.

**Closed by izuzak** 2015-07-06 17:44 UTC
