### ISSUE TITLE
Problem when pin to Win10 taskbar.

### ISSUE THREAD

**Issue by tinymins** [atom/atom#8169] opened 2015-07-31 10:28 UTC
![image](https://cloud.githubusercontent.com/assets/1808990/9005540/a54cccbc-37b1-11e5-9105-31c7cff2d69b.png)

There is always two icons here which are expected to be only one.

Version 1.0.0, Win10 x64 Enterprise

**Comment by paulcbetts** [comment] 2015-07-31 10:52
Dupe of #7374

**Closed by paulcbetts** 2015-07-31 10:52 UTC

**Comment by mnquintana** [comment] 2015-07-31 11:01
Also unrelated, but @tinymins the latest version of Atom is 1.0.3 - since a lot of issues have been fixed since 1.0.0, you may want to upgrade when you get the chance.

**Comment by tinymins** [comment] 2015-08-03 07:32
Thanks, I'll go to get the new version xD.
But
![image](https://cloud.githubusercontent.com/assets/1808990/9032793/cc1ae410-39f4-11e5-99a7-41b223208c05.png)
