### ISSUE TITLE
caught exception when selecting and deleting a line of text tracked with Github Desktop

### ISSUE THREAD

**Issue by smkatz** [atom/atom#16189] opened 2017-11-15 04:48 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Got an caught exception when deleting a line of text tracked with Github Desktop.

### Steps to Reproduce

Uncertain. But when it is existing, it exists reproducibly.

**Expected behavior:**  Allow me to edit the file.

**Actual behavior:** Deleting a string of text causes the error. Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Samk/Library/Caches/com.github.atom.ShipIt/update.urOd6Gt'

Clipboard icon copies "index.html" to the clipboard, which is not the correct filename. I copied and renamed it. It does appear to have imported the project and repository in the sidebar.
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2017-11-15 20:23
Thanks for taking the time to contribute!

Based on the error message, I believe you're hitting https://github.com/atom/atom/issues/9559.  I'll close as a duplicate for now but feel free to share more details if you come across steps to reproduce.

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/9559. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-15 20:23 UTC
