### ISSUE TITLE
autocomplete does not work with non-ascii words

### ISSUE THREAD

**Issue by juh2** [atom/atom#7674] opened 2015-07-03 06:45 UTC
I am not sure which package to blame for this but autocomplet does not work with non-ascii words. 

When I type eg. "Immat" I get the autocomplete proposal "Immaterialgut" but not "Immaterialgüter". I guess autocomplete does not work with non-ascii chars at all. Thatmay be ok for programmers but not for writers, because we have a lot of non-ascii words out there.

**Comment by kubetz** [comment] 2015-07-03 09:26
This looks like a duplicate of https://github.com/atom/autocomplete-plus/issues/76 .

**Comment by izuzak** [comment] 2015-07-03 09:29
Thanks, @kubetz -- closing in favor of https://github.com/atom/autocomplete-plus/issues/76.

**Closed by izuzak** 2015-07-03 09:29 UTC
