### ISSUE TITLE
Extra quote is added when backslash is present in a string

### ISSUE THREAD

**Issue by yihangho** [atom/atom#6569] opened 2015-04-29 12:12 UTC
Not sure how to actually put this in words, but see this:

![Animated GIF](http://i.imgur.com/DaZkgtj.gif)

On each line, right before the (original) last quote, I pressed on the key to insert a quote. A quote should not be added for lines 2 and 3, just like line 1, no?

**Comment by mnquintana** [comment] 2015-04-29 12:17
I can reproduce this on `master` (Atom 0.195.0-df2b066) with any grammar (or Plain Text).

**Comment by mnquintana** [comment] 2015-04-29 13:31
Duplicate of atom/bracket-matcher#80 - please subscribe there for updates.

**Closed by mnquintana** 2015-04-29 13:31 UTC
Labels: bug, duplicate
