### ISSUE TITLE
dragging a file in the editor cause black screen

### ISSUE THREAD

**Issue by Kerosene2000** [atom/atom#8303] opened 2015-08-10 15:43 UTC
When you drag-and-drop a file in the editor, this cause a "crash": the screen is black and the only thing you can do is to `cmd`+`q` (not forcing).

The file in question is a `c file`, `"norminette.c"`.
Atom is in `full screen` with just `one pane`.
`autocomplete-clang`, `linter`, `linter-clang`, `tab-control` are installed (and others, ...)

After this closing, Atom doesn't save my panes and my tree-view...

The file in question is from another desktop on my mac.

Macbook pro retina end 2013, 2,6 GHz Intel Core i5, 8Go of ram

**Comment by izuzak** [comment] 2015-08-11 14:33
@Kerosene2000 Strange, I'm having trouble reproducing that problem. Can you clarify which version of Atom you're using and if you can reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Also, can you reproduce the problem for any file or only just that one file?

You also said this:

> The file in question is from another desktop on my mac.

Can you clarify what this means and how it affects the report? If the file is not from a different desktop -- can you still reproduce the issue?

**Comment by jnelken** [comment] 2015-12-16 08:18
I was able to reproduce the same problem consistently, and it's only related to the `full screen` mode. If I open a fresh window (untitled), maximize it, and then close it directly from it's maximized state, I will get a crash notice from Apple "Atom quit unexpectedly." This results in your previously opened trees not reappearing upon reopening Atom (if I have more than 'untitled' open, it will not reopen with Atom).

The maximization on my laptop creates a new 'desktop' for my Mac (and hides the main Apple toolbar), meaning I can still swipe to swap my view back to the location I originally opened Atom. This is different than a typical 'maximize' that simply stretches the app across the current desktop with the Apple toolbar in view.

I believe this new desktop maximize that crashes Atom is set by default on all new Apple computers.

Atom 1.3.1
Mac OS X 10.11.1

**Comment by lee-dohm** [comment] 2015-12-17 07:35
@jnelken The full screen crashing issue is something separate (that I believe has been fixed in the recent beta versions).

Since there hasn't been a response to the request for more information, I'm going to close this. Please let us know if you can still reproduce the issue @Kerosene2000!

**Closed by lee-dohm** 2015-12-17 07:35 UTC
Labels: more-information-needed
