### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isComment' of undefined

### ISSUE THREAD

**Issue by mrkwse** [atom/atom#7260] opened 2015-06-13 00:06 UTC
Using the editor:move-line-up command while editing a markdown document caused the line highlighted to disappear and the following error to be thrown.

```
TypeError: Cannot read property 'isComment' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.isFoldableCodeAtRow (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:429:71)
    at TokenizedBuffer.module.exports.TokenizedBuffer.isFoldableAtRow (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:424:19)
    at TokenizedBuffer.module.exports.TokenizedBuffer.updateFoldableStatus (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:412:25)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:377:20)
    at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:62:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:624:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:789:16)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:753:14)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1136:26)
```

**Comment by izuzak** [comment] 2015-06-13 07:49
Thanks for the report, @mrkwse -- this looks like a duplicate of https://github.com/atom/atom/issues/5905 (see https://github.com/atom/atom/issues/5905#issuecomment-104222091).

Can you add a comment to that issue and provide a bit more information -- which version of Atom you're running, which OS, and which packages you have installed (`apm list`).

**Closed by izuzak** 2015-06-13 07:49 UTC
