### ISSUE TITLE
"snip" and all custom snippets not working

### ISSUE THREAD

**Issue by robmarston** [atom/atom#6660] opened 2015-05-05 23:58 UTC
After installing the last update the default snippets work as usual but none of my custom snippets work or are listed in the Available Snippets list. I've also noticed that the "snip" snippet does not work. I'm using Atom version 0.196.0 on OS X 10.10.3. Here is the custom snippet I mentioned earlier:
```
'.text.html':
    'HTML5 Skeleton':
      'prefix': 'html5'
      'body': """
      <!doctype html>
      <html>
      <head>
      <meta charset="utf-8">
      <title></title>
      </head>
      <body> 
      </body>
      </html>
      """
```
I've tried clearing the snippets.cson file in case there was some erroneous code but the "snip" snippet still doesn't work. Saving and closing also appears to have no affect. Thanks!

**Comment by lee-dohm** [comment] 2015-05-06 01:41
I was unable to reproduce this using Atom v0.197.0-1e99a21 on Mac OS X 10.10.3. I did not try the supplied snippet, but I have a few snippets of my own and they worked fine as well as the `snip` snippet.

**Comment by mnquintana** [comment] 2015-05-06 01:45
Can you try opening Atom in safe mode (`atom --safe`) and see if you still experience this issue?

**Comment by mnquintana** [comment] 2015-06-12 11:10
Gonna close this one out - feel free to reopen on https://github.com/atom/snippets if you experience this again.

**Closed by mnquintana** 2015-06-12 11:10 UTC
Labels: more-information-needed
