### ISSUE TITLE
Add printing option

### ISSUE THREAD

**Issue by wieczorek1990** [atom/atom#19599] opened 2019-06-26 07:56 UTC
## Summary

Add printing option.

## Motivation

Would like to use Atom as a normal text editor.

## Describe alternatives you've considered

No alternataives

## Additional context

I don't want to use textEdit anymore.

**Comment by rsese** [comment] 2019-06-26 19:48
Thanks for contributing!

This is a duplicate of https://github.com/atom/atom/issues/3525, this isn't something the team would work on, see Lee's comment here: https://github.com/atom/atom/issues/3525#issuecomment-324688942.  There are a couple of community packages mentioned but I'm not sure if they're currently maintained.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-26 19:48 UTC
