### ISSUE TITLE
Cannot use Cmd+V to paste in Save dialogue

### ISSUE THREAD

**Issue by tsaiid** [atom/atom#14145] opened 2017-04-06 05:33 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Environment: macOS Sierra 10.12.4.

Cannot use Cmd+V to paste text in Save dialogue. 

### Steps to Reproduce

1. Open a new file, and input some text. Select the text, and send Cmd+C to copy them.
2. Save the file or save as a new file. 
3. In the filename input of Save dialogue, I cannot use Cmd+V to paste the text just copied. But it works using right click of mouse, and then click Paste.  

**Expected behavior:** can paste the text

**Actual behavior:** nothing happens

**Reproduces how often:** every time

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.12.2

**Comment by 50Wliu** [comment] 2017-04-06 13:26
This will be fixed in Atom 1.16.0.

**Comment by tsaiid** [comment] 2017-04-13 03:24
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

However, this bug is still not fixed.

**Comment by kevinjelnl** [comment] 2017-04-19 14:39
also have this problem,
cannot use cmd-v or cmd-a, in the save dialog! halp please. its a bit annoying

**Comment by gringogidget** [comment] 2017-04-19 17:57
Came here to file this issue and see it's still an issue. That's all I have to say for now lol. <3

**Comment by theurge14** [comment] 2017-04-24 13:19
1.14.4 is the last version to properly support these features.

**Comment by theurge14** [comment] 2017-05-16 17:00
Appears to still be an issue in current beta 1.18.1

**Comment by rflagreca** [comment] 2017-05-19 15:12
Still an issue in release 1.17.0.  Very frustrating 😒

**Comment by latiina** [comment] 2017-06-19 13:17
Is there an ETA on when this will be resolved..?
Working off release 1.17.2 and unfortunately cannot see that it has been fixed.

**Comment by mcansh** [comment] 2017-06-21 18:50
1.19.0 and still occurring 😞

**Comment by xtianares** [comment] 2017-06-29 15:20
any updates on this annoying issue?

**Comment by mbdmbd** [comment] 2017-08-19 03:54
1.19.1 and the bug still exists. 

I'm aware this is free software, so can hardly be too petulant about it, but if offering a bounty will help encourage a smarter developer than me to fix the code I'm willing to contribute to the applicable cause. :-)

I'm on the verge of switching editors, because this bug impacts my ability to easily follow my naming convention for files.

**Comment by zeis** [comment] 2017-08-27 21:37
1.19.3 (safe mode), sadly the bug is still there.

**Comment by theurge14** [comment] 2017-09-06 13:57
mbdmbd this issue has been impacting me as well since earlier this spring of this year, I had to switch to Sublime Text because of this.  I'm sorry guys but this is way too long to wait.

**Comment by metasean** [comment] 2017-09-15 20:46
Bug still in Atom version 1.20.0

**Comment by lukeagsmith** [comment] 2017-10-07 08:55
Still an issue in 1.21.0

**Comment by chikoree** [comment] 2017-10-16 09:26
Still an issue in 1.21.1

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.2

**Comment by chikoree** [comment] 2017-11-02 08:55
Still an issue in 1.21.2

Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.15.0

**Comment by safetypins** [comment] 2017-11-06 16:30
Not sure if this helps, but it looks like we cannot use any CMD shortcuts (copy/paste) either.

**Comment by thatlizarddude** [comment] 2017-11-10 22:03
Still an issue on 1.22 - is this getting fixed anytime? It's been open for 7 months :/

**Comment by chikoree** [comment] 2017-11-13 09:05
Still an issue in 1.22.0

Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.15.0

**Comment by rsese** [comment] 2017-11-17 20:13
Sorry, there's no particular timeframe for this issue @thatlizarddude, the team hasn't been able to get to it with all the work on their plate. If there was a well-written community pull request with a fix, I could ask the team to take a look though I still couldn't make any promises about it.

**Comment by thatlizarddude** [comment] 2017-11-19 06:26
This is the source code of VS Code which works fine, hopefully I'm linking it to the right location: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts#L1340
Hope this helps anyone looking for how to fix the issue.

**Comment by as-cii** [comment] 2018-01-10 10:31
I can't reproduce this anymore after https://github.com/atom/atom/pull/16245 has been merged, so I believe it was a problem due to using the synchronous version of Electron's `showSaveDialog` API.

Thanks everybody for the report! The fix for this issue will ship as part of Atom 1.25.0-beta0. ⚡️

**Closed by as-cii** 2018-01-10 10:31 UTC
Labels: bug, mac, regression, triaged

**Comment by Semicolon42** [comment] 2018-02-23 19:17
Still seeing this issue with 1.24.0 on Mac

**Comment by thatlizarddude** [comment] 2018-02-23 19:22
@Semicolon42 like as-cii said:

> The fix for this issue will ship as part of Atom 1.25.0-beta0.

I haven't tested yet but try anything above that version, it should work.

**Comment by kevinjelnl** [comment] 2018-02-23 19:24
Can confirm, it is fixed in the beta
