### ISSUE TITLE
startup time

### ISSUE THREAD

**Issue by jsjain007** [atom/atom#6250] opened 2015-04-04 19:21 UTC
since the early versions on atom this version's start up time is very much i know all these features take some time to load but this is quite too much , which is not good for text editor . 
please fix this start up time issue. 
thanks in advance

**Comment by mark-hahn** [comment] 2015-04-04 19:24
Duplicate of https://github.com/atom/atom/issues/2654

**Closed** 2015-04-05 01:05 UTC
