### ISSUE TITLE
Texts become blurry on when they lose focus

### ISSUE THREAD

**Issue by erathostene** [atom/atom#13688] opened 2017-01-24 13:15 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Any text that lose focus for few secs (or the whole editor if idle),  become blurry. Happens everywhere in the atom editor (including menu bar).
![blur_text_atom](https://cloud.githubusercontent.com/assets/19215490/22249554/ccdc1b8c-e243-11e6-9b5c-e44f0bc11667.gif)

### Steps to Reproduce

1. Open file in atom
2. Type
3. Wait 1 or 2sec
4. All texts where no action (keyboard, mouse hover or click..) where performed become blurry (menu bar, left panel or lines inside the editor where the cursor is not)

**Expected behavior:** Texts always appear clear

**Reproduces how often:** Always

### Versions

- Atom : 1.13.0 ia32 (no custom package) NB Same occurs with atom beta version
- OS : Windows 10 build 14393 x64
- CPU : Intel i7-4700HQ 2.4GHZ, 
- GPU : Intel HD graphic 4600
- Screen : 1920x1080px / 17inches

(all drivers up to date, environment set for maximum performance, ClearType set)

### Additional Information

- Google chrome (55), and all other applications (including text editors)  are unaffected.
- Changing -webkit-font-smoothing or text-rendering to any option is ineffective.
- Antialiasing plugin is ineffective.

**Comment by damieng** [comment] 2017-01-25 19:26
Duplicate of https://github.com/atom/atom/issues/13341

Basically you'll need to go into the Intel drivers and turn the 'sharpness' setting off which also messes up Visual Studio and other hardware-accelerated applications.

**Closed by damieng** 2017-01-25 19:26 UTC

**Comment by erathostene** [comment] 2017-01-25 19:58
Sorry i didn't mentionned it but i saw  #13341 and set my intel drivers accordingly (which wasn't needed as they weren't turned on). I managed to fix it though by using the compatibility mode. IMHO was related to [Mixed-Mode DPI scaling](https://blogs.technet.microsoft.com/askcore/2016/08/16/display-scaling-changes-for-the-windows-10-anniversary-update/)
