### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by rayhendricks** [atom/atom#16600] opened 2018-01-20 02:22 UTC
1. Open Atom in safe mode from `cmd.exe` using `atom --safe`
1. Open a new untitled buffer and paste the following contents:
```
<html>
</html>
```
3. Change the language grammar to HTML
1. Place the cursor after the h on the first line
1. Press <kbd>Ctrl+Space</kbd> to run the command `autocomplete-plus:activate`
1. Press <kbd>Ctrl-Shift-P</kbd> to run the command `command-palette:toggle`
1. Search for the `autocomplete-plus:navigate-to-description-more-link` command
1. Run this command from the command palette

**Expected:** To navigate to the description more link. Or nothing to happen because opening the Command Palette closes autocomplete-plus.

**Actual:** This exception is thrown.

**Gif of reproduction:**

![style exception](https://user-images.githubusercontent.com/1058982/35213060-a5ac590a-ff5c-11e7-8a11-b1eb720eec51.gif)

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:241

TypeError: Cannot read property 'style' of null
    at HTMLElement.autocomplete-plus:navigate-to-description-more-link (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:241:39)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -9:39.9.0 application:add-project-folder (input.hidden-input)
     -1:53.9.0 application:open (input.hidden-input)
     -1:21.4.0 command-palette:toggle (input.hidden-input)
     -0:04.9.0 core:move-down (input.hidden-input)
     -0:03.9.0 core:confirm (input.hidden-input)
     -0:03.9.0 autocomplete-plus:navigate-to-description-more-link (input.hidden-input)
```

### Non-Core Packages

```
atom-soda-dark-ui 1.1.0 
monokai 0.24.0 
```

**Comment by lee-dohm** [comment] 2018-01-20 22:57
Can you give us any more information as to what you were doing when this occurred?

**Comment by Ben3eeE** [comment] 2018-01-22 09:13
1. Open Atom in safe mode from `cmd.exe` using `atom --safe`
1. Open a new untitled buffer and paste the following contents:
```
<html>
</html>
```
3. Change the language grammar to HTML
1. Place the cursor after the h on the first line
1. Press <kbd>Ctrl+Space</kbd> to run the command `autocomplete-plus:activate`
1. Press <kbd>Ctrl-Shift-P</kbd> to run the command `command-palette:toggle`
1. Search for the `autocomplete-plus:navigate-to-description-more-link` command
1. Run this command from the command palette

**Expected:** To navigate to the description more link. Or nothing to happen because opening the Command Palette closes autocomplete-plus.

**Actual:** This exception is thrown.

**Gif of reproduction:**

![style exception](https://user-images.githubusercontent.com/1058982/35213060-a5ac590a-ff5c-11e7-8a11-b1eb720eec51.gif)

## Version Information

**Atom**: 1.25.0-dev-3d8902d x64
**Electron**: 1.7.10
**OS**: Microsoft Windows 7 Professional

**Comment by Ben3eeE** [comment] 2018-01-22 09:14
I edited the body of the issue to include the steps to reproduce from https://github.com/atom/atom/issues/16600#issuecomment-359364458.

**Comment by victor-cordova** [comment] 2018-02-10 14:59
Hello, @Ben3eeE I think this should solve the problem https://github.com/atom/autocomplete-plus/pull/953. It looks like the problem was caused by that plugin. @lee-dohm the reference to this issue is in that pull-reques as well.

Demo
![video](https://user-images.githubusercontent.com/18427801/36063291-f129a7a2-0e48-11e8-8f86-93f4afe79130.gif)

**Comment by victor-cordova** [comment] 2018-02-13 23:53
cc: @lee-dohm

**Comment by Ben3eeE** [comment] 2018-02-26 21:50
Closed via https://github.com/atom/autocomplete-plus/pull/953

**Closed by Ben3eeE** 2018-02-26 21:50 UTC
Labels: bug, triaged, uncaught-exception
