### ISSUE TITLE
On opening a single file in atom, the tree view shows the file as a separate folder instead of separate file

### ISSUE THREAD

**Issue by kp25** [atom/atom#7568] opened 2015-06-30 04:13 UTC
Operating System: Windows 8.1 x64, Windows 7 x64
Atom Version: v1.0.0

Attached screenshot for reference.
![atom_bug](https://cloud.githubusercontent.com/assets/4737336/8423778/6c21fd94-1f0c-11e5-8a42-1cf827a067c4.PNG)

**Comment by kubetz** [comment] 2015-06-30 08:01
This seems to be a duplicate of https://github.com/atom/tree-view/issues/471 .

**Comment by izuzak** [comment] 2015-06-30 08:03
Yep, closing as a duplicate of https://github.com/atom/tree-view/issues/471 -- thanks, @kubetz.

**Closed by izuzak** 2015-06-30 08:03 UTC

**Comment by kubetz** [comment] 2015-06-30 08:19
@izuzak I now read all the comments in that linked issue and judging from them there is a high probability that the issue will be reopened here anyway :confused:.

**Comment by izuzak** [comment] 2015-06-30 08:21
@kubetz Yeah, I think that's fine if/when it happens. So, lets wait and see what happens, and until then -- having a single issue to track a specific problem is batter than having two. Sound good?

**Comment by kubetz** [comment] 2015-06-30 08:23
Yeah, it totally makes sense :+1: .

**Comment by kp25** [comment] 2015-06-30 10:47
@izuzak @kubetz thanks for pointing out guys, lot of issues in the repo & completely lost in finding out if a issue has already been raised or not. 
yep, having one issue to track a problem is better than having two. (Y)

**Comment by LMLB** [comment] 2015-08-27 08:53
I believe the root cause is that Atom's DefaultDirectoryProvider believes that paths on Windows are URLs (where the protocol is the drive letter) and therefore doesn't remove the filename from the path.
