### ISSUE TITLE
Uncaught Error: error: 126/\?\~\AppData\Local\atom\app-1.27.0\resources\app.asar.unpacked\node_mo...

### ISSUE THREAD

**Issue by cedricspitzer** [atom/atom#17347] opened 2018-05-17 16:34 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: LEO-RECHNER
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 126\\?\C:\Users\Leo\AppData\Local\atom\app-1.27.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: error: 126\\?\C:\Users\Leo\AppData\Local\atom\app-1.27.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.27.0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.27.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  4x -5:40.9.0 core:save (input.hidden-input)
     -3:40.8.0 welcome:show (input.hidden-input)
```

### Non-Core Packages

```
atom-eclipse-syntax 0.0.5 
autumn-highlighter-syntax 1.13.0 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
jackhammer-syntax 1.1.0 
remote-ftp 2.1.4 
styri-syntax 0.2.0 
teletype 0.13.2 
```

**Comment by steveward** [comment] 2018-05-17 17:01
Closing as a dupe of https://github.com/atom/atom/issues/17346.

**Closed by steveward** 2018-05-17 17:01 UTC
