### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/jP/Library/Application Support/c...

### ISSUE THREAD

**Issue by jpdevries** [atom/atom#10344] opened 2016-01-08 22:02 UTC
1. Do a Markdown Preview on the contents of [this gist](https://gist.github.com/jpdevries/76d32d9e7e9f975fb8de)

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jP/Library/Application Support/com.github.atom.ShipIt/update.KPWr0Ke/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -2:48.6.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
     -0:53.4.0 markdown-preview:preview-file (span.name.icon.icon-file-text)
     -0:43.3.0 tree-view:show-in-file-manager (span.name.icon.icon-file-text)
  2x -0:16.2.0 markdown-preview:preview-file (span.name.icon.icon-file-text)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-01-08 22:51
Hi @jpdevries, thanks for reporting!  It looks like this is a duplicate of #7399 though, so please subscribe there for updates.

**Closed by 50Wliu** 2016-01-08 22:51 UTC
