### ISSUE TITLE
Atom1.28.1 crash when it work with shadowsocks

### ISSUE THREAD

**Issue by hichenxinyu** [atom/atom#17653] opened 2018-07-09 02:58 UTC
Before opening the shadowsocks atom may crash. Now (1.28.1) is as long as opening shadowsocks, atom100% crashes

**Comment by victor1994y** [comment] 2018-07-09 04:10
Total same problem. I use ShadowsocksR. Atom with 1.28.1 crashed every time when ssr is open. At the beginning I can't find why I can't open atom. Now I know why.
And this problem didn't show when I rollback atom to 1.27.2.
(System: Win10 x64 Education ver1803)

**Comment by 50Wliu** [comment] 2018-07-09 04:11
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #17557. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-07-09 04:11 UTC
