### ISSUE TITLE
Uncaught Can't find   // { path: '/dashboard', title: 'Dashboard',  icon: 'dashboard', class: '' ...

### ISSUE THREAD

**Issue by Rajkamal1437** [atom/atom#17321] opened 2018-05-14 10:40 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find   // { path: '/dashboard', title: 'Dashboard',  icon: 'dashboard', class: '' },
  //  { path: '/user-profile', title: 'User Profile',  icon:'person', class: '' },
  //  { path: '/table-list', title: 'Table List',  icon:'content_paste', class: '' },
  //  { path: '/typography', title: 'Typography',  icon:'library_books', class: '' },
  // 
  //  { path: '/maps', title: 'Maps',  icon:'location_on', class: '' },
  //  { path: '/notifications', title: 'Notifications',  icon:'notifications', class: '' },
  //  { path: '/upgrade', title: 'Upgrade to PRO',  icon:'unarchive', class: 'active-pro' },
  //   { path: '/dashboard', title: 'Dashboard',  icon: 'dashboard', class: '' }, file

```
At C:\Users\rajkamal.m\AppData\Local\atom\app-1.26.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:959

undefined
```

### Commands

```
     -3:41.5.0 core:backspace (input.hidden-input)
  2x -3:38.2.0 core:save (input.hidden-input)
  2x -3:24.4.0 core:move-left (input.hidden-input)
     -3:23.5.0 core:move-right (input.hidden-input)
     -3:23 core:backspace (input.hidden-input)
  2x -3:21.7.0 core:save (input.hidden-input)
 13x -3:02.0 core:move-right (input.hidden-input)
     -2:53.3.0 core:move-left (input.hidden-input)
     -2:52.8.0 core:move-up (input.hidden-input)
 31x -2:52.4.0 core:move-left (input.hidden-input)
  2x -2:44.4.0 core:save (input.hidden-input)
     -2:16.6.0 editor:toggle-line-comments (input.hidden-input)
     -2:15.7.0 core:save (input.hidden-input)
     -1:26.9.0 editor:toggle-line-comments (input.hidden-input)
     -1:26.9.0 emmet:encode-decode-data-url (input.hidden-input)
     -1:11.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
emmet 2.4.3 
language-babel 2.85.0 
react-snippets 1.1.0 
seti-ui 1.10.0 
```

**Comment by rsese** [comment] 2018-05-14 18:17
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/17271 so you can subscribe there for updates if you'd like.  If you remember what you were doing at the time of the error, please let us know in https://github.com/atom/atom/issues/17271.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-14 18:17 UTC
