### ISSUE TITLE
Uncaught TypeError: Cannot read property 'PWD' of null

### ISSUE THREAD

**Issue by hamishmcneill** [atom/atom#12328] opened 2016-08-04 22:05 UTC
**Steps**

1. Initial launch of Atom application
2. Selected 'Open a Project' from the Welcome Guide
3. Selected to open a directory from `~/Sites/` before the following error was displayed in Atom

**Atom Version**: 1.9.3
**System**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'PWD' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/update-process-env.js:13

TypeError: Cannot read property 'PWD' of null
    at updateProcessEnv (/Applications/Atom.app/Contents/Resources/app.asar/src/update-process-env.js:13:16)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:41:16)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -0:16 command-palette:toggle (summary.welcome-summary.icon.icon-keyboard)
     -0:04.7.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.2 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by timdorr** [comment] 2016-08-04 22:21
Getting this too. Looks like #12317 broke it?

**Comment by timdorr** [comment] 2016-08-04 22:25
I can confirm downgrading to 1.9.2 fixes it. I was actually getting a more severely problematic startup behavior at first:

![screenshot 2016-08-04 18 17 17](https://cloud.githubusercontent.com/assets/17882/17420452/b337a2f6-5a70-11e6-9291-61072df301a0.png)

The console had the same PWD error.

**Comment by maxbrunsfeld** [comment] 2016-08-04 23:06
Really sorry everyone. This is fixed on master (https://github.com/atom/atom/commit/c0e94aac5e0aef19ca31abf029ff68531614152c), and we'll publish a release with the fix shortly.

**Comment by harryttd** [comment] 2016-08-05 00:09
How can I downgrade?

**Comment by maxbrunsfeld** [comment] 2016-08-05 00:10
@harryttd In the meantime, you can download `1.9.2` from https://github.com/atom/atom/releases/tag/v1.9.2.

**Comment by harryttd** [comment] 2016-08-05 00:12
Should I uninstall the current version first?

Thanks.

**Comment by harryttd** [comment] 2016-08-05 00:13
I'm somewhat of a beginner.
Do I download all of those links on the page you linked in your post?

**Comment by maxbrunsfeld** [comment] 2016-08-05 00:14
What OS are you using? You should only need to download one. Also, the new version should be out in less than an hour.

**Comment by harryttd** [comment] 2016-08-05 00:16
Im on a Mac with El Capitan.

Thanks a lot.

**Comment by maxbrunsfeld** [comment] 2016-08-05 00:17
Ok, so just download `atom-mac.zip` and extract it, and use that.

**Comment by harryttd** [comment] 2016-08-05 00:24
I got it to download.

Do you have any idea why terminal-plus won't work? I have it installed but it won't take any input into the shell.

**Comment by maxbrunsfeld** [comment] 2016-08-05 00:27
> Do you have any idea why terminal-plus won't work?

Not sure. You should probably ask about this on [the Atom forum](https://discuss.atom.io/t/join-us-on-slack/16638) or the [`#atom` slack channel](https://discuss.atom.io/t/discussion-join-us-on-slack/25406?source_topic_id=16638).

**Comment by harryttd** [comment] 2016-08-05 00:35
Ok.

Thank you.

**Comment by harryttd** [comment] 2016-08-05 01:27
How can I find out when the update will be available?

**Comment by guchenghao** [comment] 2016-08-05 03:04
I have the same problem
![image](https://cloud.githubusercontent.com/assets/13380685/17425109/5220718c-5afc-11e6-863e-6ed401a1712f.png)

**Comment by maxbrunsfeld** [comment] 2016-08-05 03:43
v1.9.4 is out.

**Closed by maxbrunsfeld** 2016-08-05 03:43 UTC
Labels: bug, uncaught-exception

**Comment by andrevenancio** [comment] 2016-08-05 05:11
this started happen since I upgraded to the new macOS Sierra dev build.

**Comment by braveforest** [comment] 2016-08-05 07:40
@guchenghao  how you set the background theme?

**Comment by Blackening999** [comment] 2016-08-05 19:10
so annoying and sad to hear :(

**Comment by maxbrunsfeld** [comment] 2016-08-05 19:15
> so annoying and sad to hear :(

@Blackening999 What are you referring to? Are you still seeing this error on v1.9.4?

**Comment by Blackening999** [comment] 2016-08-05 19:16
@maxbrunsfeld 
"And exciting, on other hand, how fast the update has been delivered."

**Comment by joshmedeski** [comment] 2016-08-05 20:02
I had the same problem. I updated to 1.9.4 by manually downloading the newest version of Atom from [the website](https://atom.io/) and everything is working again 😄

**Comment by maurocolella** [comment] 2016-08-06 16:06
I am impressed. Had a very similar issue (NULL instead of undefined) when working on Samba shares from a Linux virtual machine to Windows, eq. I am on Windows. Install the update, which brought me from version 1.9.3 to version 1.9.6, and it fixed the issue.

You've kinda jumped three minor versions in three days, and made my own day in the process.

**Comment by littlewrite** [comment] 2016-08-23 06:52
C:\Users\xxxx\AppData\Local\atom\app-1.9.3\resources\app.asar\src\update-process-env.js:13
Hide Stack Trace
TypeError: Cannot read property 'PWD' of null
    at updateProcessEnv (C:\Users\xxxx\AppData\Local\atom\app-1.9.3\resources\app.asar\src\update-process-env.js:13:16)
    at EventEmitter.<anonymous> (C:\Users\xxxx\AppData\Local\atom\app-1.9.3\resources\app.asar\src\initialize-application-window.js:41:16)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)

**Comment by maxbrunsfeld** [comment] 2016-08-23 16:48
@littlewrite Please update from Atom 1.9.3 to the latest stable version; this bug has been fixed.

**Comment by littlewrite** [comment] 2016-08-24 06:29
@maxbrunsfeld  Thanks, it's ok after updating.
