### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 423Error: Cannot cal...

### ISSUE THREAD

**Issue by chrispatterson** [atom/atom#16636] opened 2018-01-26 20:09 UTC
[Enter steps to reproduce:]

Unfortunately, I probably don't have good steps to reproduce, here. I'd just edited a method in my Rails app's application helper, saved it, alt-tabbed over to a browser to test, and was greeted with this error when I alt-tabbed back.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 423
Error: Cannot call function 'getPosition' on missing remote object 423
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 423
Error: Cannot call function 'getPosition' on missing remote object 423
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:691:34)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:725:42)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:189:32)
```

### Commands

```
 12x -9:51.8.0 core:backspace (input.hidden-input)
     -8:19 core:save (input.hidden-input)
     -8:11.8.0 core:backspace (input.hidden-input)
     -8:10.8.0 core:save (input.hidden-input)
     -7:51.1.0 core:undo (input.hidden-input)
     -7:45.2.0 core:backspace (input.hidden-input)
     -7:44.6.0 core:save (input.hidden-input)
     -7:00.4.0 core:undo (input.hidden-input)
     -6:58.7.0 core:save (input.hidden-input)
     -6:31.7.0 core:backspace (input.hidden-input)
  2x -6:30.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
behave-theme 1.7.0 
busy-signal 1.4.3 
git-blame 1.4.0 
github-atom-dark-syntax 0.5.0 
github-atom-light-syntax 0.5.0 
intentions 1.1.5 
language-slim 1.0.0 
linter 2.2.0 
linter-coffeescript 1.0.0 
linter-js-yaml 1.2.8 
linter-rubocop 2.2.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
minimap 4.29.7 
nucleus-dark-ui 0.12.3 
pigments 0.40.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
sync-settings 0.8.3 
tabs-to-spaces 1.0.3 
```

**Comment by rsese** [comment] 2018-01-26 22:46
Thanks for the report @chrispatterson - we'll go ahead and close as a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.  I'll also copy over your comment related to repro steps.

**Closed by rsese** 2018-01-26 22:46 UTC
