### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by ClemansJr** [atom/atom#19238] opened 2019-04-30 09:12 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:166

Error: dlopen(/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app/static/<embedded>:1:672940)
    at get_KeyboardLayoutManager (/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app/static/<embedded>:14:3157373)
    at get_manager (/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app/static/<embedded>:14:3157453)
    at Object.getCurrentKeyboardLayout (/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app/static/<embedded>:14:3157579)
    at e.keystrokeForKeyboardEvent (/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app/static/<embedded>:14:991868)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1209888)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1207873)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/yd/fdmzt0_504jbcnkr5xvldlwm0000gn/T/AppTranslocation/87BE3A2B-B442-4D87-B8BE-865C433DDFB6/d/Atom.app/Contents/Resources/app/static/<embedded>:11:285300)
```

### Commands

```
  2x -1:36.3.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2019-04-30 20:58
Thanks for contributing!

We noticed that this looks like a duplicate of #14461 so you can subscribe there for updates if you'd like.   To get past the error, I'd recommend running through the [installation](https://flight-manual.atom.io/getting-started/sections/installing-atom/) again and if you still have trouble, feel free to reach out on the [message board](https://discuss.atom.io/) and ping me there so we can take a look together.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-30 20:58 UTC
