### ISSUE TITLE
Uncaught Error: Setting active pane that is not present in pane container

### ISSUE THREAD

**Issue by ron-wolf** [atom/atom#14716] opened 2017-06-05 12:47 UTC
[Enter steps to reproduce:]

@ungb's repro steps from [below](https://github.com/atom/atom/issues/14716#issuecomment-322986916):

1. Open Atom with a project.
2. Rlight Click `Close pane` in the tree-view,  Notice nothing happens
3. right click and remove the project.
4. Tree-view disappears,  Toggle it back open
5. right click and click add folder back
6. Tree view remains empty and if you open dev tools you see error from https://github.com/atom/atom/issues/14454#issuecomment-322984675
7. close tree-view and open it back up and left click on the `tree view`.

---

1. Open Atom
2. Open a recently opened project folder
3. Open/reopen tree pane a few times
4. Click/right-click tree pane a few times

**Atom**: 1.18.0-beta2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:253

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:253:21)
    at Pane.module.exports.Pane.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:875:20)
    at Pane.module.exports.Pane.focus (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:269:25)
    at atom-pane.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/pane-element.js:51:25)
```

### Commands

```
     -0:36.7.0 window:toggle-full-screen (input.hidden-input)
     -0:32.2.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-one-dark-ui)
     -0:21.8.0 application:reopen-project (div.tool-panel.tree-view)
  4x -0:17.1.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-clock 0.1.8 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-terminal-tab 0.2.0 
build 0.68.0 
build-make 0.13.0 
clojure-indent 0.2.0 
django-atom 0.2.4 
file-type-icons 1.3.4 
fizzy 0.21.0 
git-time-machine 1.5.9 
hyperclick 0.0.40 
hyperlink-hyperclick 1.3.4 
improved-chester-atom-syntax 0.3.0 
ink 0.6.5 
language-crystal-actual 0.35.0 
linter 2.1.4 
linter-ruby 1.2.5 
linter-ui-default 1.6.0 
one-tab 0.10.0 
proto-repl 1.4.20 
release-notes 0.53.0 
scroll-through-time 0.2.0 
symbol-gen 1.3.1 
tab-title 0.3.3 
tree-ignore 0.6.2 
typewriter 0.7.0 
unfancy-file-icons 0.11.0 
wakatime 7.0.3 
```

**Comment by rsese** [comment] 2017-06-05 18:35
Thanks for the report!  Can you confirm if the error is consistently reproducible and if so, is it reproducible in safe mode (`atom --safe`)?

**Comment by epan** [comment] 2017-06-05 19:30
Preamble: I'm new to development and whatnot. Trying to help and get help but let me know if I'm just adding noise or how to improve 🙏 😄 

In case it helps, I re-encountered this error where the tree sidebar is missing **only for this one particular project** and even running in `atom --safe` and when I clicked `project` in the bottom left corner, I got a magical link to this issue. 

Oddly, all other projects seem to open fine with the tree sidebar intact. My [atom settings](https://gist.github.com/epan/e1fe12e577dd8dfe0f7d68754d223b09)

Screenshot of error and link that brought me here below

<img width="713" alt="screen shot 2017-06-05 at 12 21 00 pm" src="https://cloud.githubusercontent.com/assets/892749/26799368/3201a49c-49ea-11e7-9aa5-33ad40441c6e.png">

**Comment by epan** [comment] 2017-06-05 21:32
Alright so as an update, I got this sorted out on my end back to normal by doing the following

1. Close all open Atom projects
1. Run `atom --clear-window-state` saw on [this reference](http://flight-manual.atom.io/hacking-atom/sections/debugging/)
1. Run `atom --safe` on the repo that I had issues with (file tree now shows up)
1. Close that repo project in Atom
1. Run `atom .` on the same repo (file tree still shows up)
1. 🎉

**Comment by netmou** [comment] 2017-06-06 06:13
i meet it so

**Comment by rsese** [comment] 2017-06-06 19:24
Thanks for the info @epan :v:  Seems like some of the saved state maybe related to that one project was causing the trouble, good to know that clearing the saved state fixed things up for you.

If you still get the same error in safe mode @ron-wolf, clearing saved state is a good next step to try (make sure to save any unsaved work first).

**Comment by zbobyuan** [comment] 2017-06-07 14:54
I run into the same issue and @epan's solution works, thanks.

**Comment by a-laughlin** [comment] 2017-06-09 07:20
Having this same issue.  Closed the editor in the project I was having an issue.  Reopened atom with --clear-window-state.  Project fixed.  Opened another project that was working fine.  It had a couple tabs with unsaved content.  All that project's tabs are gone too, including the unsaved ones.  Posting because it isn't clear from the above solution that running `--clear-window-state` will destroy all content in all unsaved tabs in all projects with no warning.  Think I just lost a bunch of project-related phone call notes in other projects.

Posted a question about how to fix it or at least prevent it [here](https://discuss.atom.io/t/how-to-restore-your-previously-opened-tabs-even-non-saved-files/25035/6?u=a-laughlin).  If anyone knows plugins to get back untitled file contents after `--clear-window-state`, or a plugin to dump them to a file to prevent future loss, I'd greatly appreciate the help.

The launch stories underlying the issues are listed [here](https://github.com/atom/atom/issues/10517)

**Comment by 50Wliu** [comment] 2017-06-10 00:04
Sorry for the data loss @a-laughlin, but `--clear-window-state` [permanently destroys any saved state across all projects](http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state).

I tried reproducing this issue but was unable to.

**Comment by epan** [comment] 2017-06-10 05:04
sorry about that @a-laughlin and I've edited my original suggestion based on your experience

**Comment by AHL96** [comment] 2017-06-13 16:18
[Enter steps to reproduce:]

1. open atom
2. open a folder
3. open tree view 
4. click around empty tree view 

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:253

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:253:1)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:875:1)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:269:1)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:51:25)
```

### Commands

```
     -0:19.8.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-clock 0.1.9 
atom-django 0.3.2 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
auto-update-packages 1.0.1 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.64 
busy-signal 1.4.3 
color-picker 2.2.5 
django-templates 0.5.0 
emmet 2.4.3 
ex-mode 0.15.0 
file-icons 2.1.7 
git-control 0.9.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.65.1 
linter 2.1.4 
linter-eslint 8.2.1 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-pycodestyle 2.0.2 
linter-tslint 1.6.0 
linter-ui-default 1.6.1 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
monokai 0.24.0 
multi-cursor 2.1.5 
nucleus-dark-ui 0.12.3 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
project-manager 3.3.5 
Remote-FTP 0.10.7 
seti-syntax 1.1.3 
sync-settings 0.8.1 
todo-show 1.11.0 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
vim-mode-plus 0.93.0 
```

**Comment by MichaelA59** [comment] 2017-06-13 20:01
epan's quick instructions fixed the bug, thanks!

**Comment by rsese** [comment] 2017-06-13 21:24
@AHL96 - you mentioned you can't find a pattern for when it happens so just to clarify, is the error not reproducible for you?  Or do the steps you shared always recreate the error?

**Comment by netmou** [comment] 2017-06-14 00:28
@rsese reproduct steps like this:
open atom
open a project folder and open tree view 
remove the  project folder A
open project folder B
remove the  project folder B
at this time the tree-view panel is closed
open project folder A by menu command
at this time the project folder A is not present in tree-view,but the window title is normal
left/right click around  tree-view times


 my config like this:

"*":
  "atom-autocomplete-php":
    binComposer: "C:\\ProgramData\\ComposerSetup\\bin\\composer.phar"
  "atom-beautify":
    general:
      _analyticsUserId: "88fadf73-5736-4566-9b11-f75af24ee819"
    php:
      cs_fixer_path: "C:\\Users\\netmou\\AppData\\Roaming\\Composer\\vendor\\fabpot\\php-cs-fixer\\php-cs-fixer"
  "atom-terminal": {}
  "autocomplete-dcd": {}
  "autocomplete-php": {}
  "autocomplete-plus":
    autoActivationDelay: 300
    strictMatching: true
  "busy-signal":
    itemsToShowInHistory: 1
  "clipboard-plus":
    maximumTextLength: 32
  "color-picker":
    preferredFormat: "HEX"
  core:
    autoHideMenuBar: true
    closeDeletedFileTabs: true
    disabledPackages: [
      "language-clojure"
      "language-coffee-script"
      "language-csharp"
      "language-gfm"
      "language-go"
      "language-mustache"
      "language-objective-c"
      "language-perl"
      "language-property-list"
      "language-python"
      "language-ruby"
      "language-ruby-on-rails"
      "language-toml"
      "open-on-github"
      "wrap-guide"
      "timecop"
      "spell-check"
      "php-twig"
      "language-java"
      "language-make"
    ]
    openEmptyEditorOnStart: false
    projectHome: "e:\\"
    telemetryConsent: "no"
    themes: [
      "one-light-ui"
      "one-light-syntax"
    ]
  editor:
    backUpBeforeSaving: true
    fontFamily: "Source Code Pro"
    fontSize: 18
    invisibles: {}
    scrollPastEnd: true
    showCursorOnSelection: false
    showIndentGuide: true
    showInvisibles: true
    softTabs: false
    softWrap: true
    useShadowDOM: false
    zoomFontWhenCtrlScrolling: false
  emmet: {}
  "exception-reporting":
    userId: "94525e00-8cce-ee60-d3fc-3fdcd2da473d"
  "file-icons": {}
  "git-diff": {}
  "git-plus":
    commits: {}
    experimental:
      stageFilesBeta: false
    general:
      _analyticsUserId: "9ce739be-4a08-43fd-b4f9-cce53e5b6447"
  "highlight-selected": {}
  linter:
    lintOnChangeInterval: 800
  "linter-htmlhint": {}
  "linter-jshint": {}
  "linter-php": {}
  "linter-ui-default":
    panelHeight: 64
    useBusySignal: false
  minimap:
    displayPluginsControls: false
    plugins:
      "git-diff": true
      "git-diffDecorationsZIndex": 0
      "highlight-selected": true
      "highlight-selectedDecorationsZIndex": 0
      selection: true
      selectionDecorationsZIndex: 0
    scrollAnimation: true
  "one-dark-ui": {}
  "one-light-ui": {}
  "rest-client":
    tab_key_behavior:
      soft_tab_length: 4
  "simple-drag-drop-text":
    copyKey: "ctrl"
  "spell-check": {}
  "split-diff":
    diffWords: true
    ignoreWhitespace: true
    leftEditorColor: "red"
    rightEditorColor: "green"
    scrollSyncType: "Vertical + Horizontal"
    syncHorizontalScroll: true
  "status-bar":
    cursorPositionFormat: "%L 行：%C 列"
    selectionCountFormat: "(选中：%L 行，%C 字符)"
  "symbol-gen": {}
  "symbols-view": {}
  tabs:
    enableVcsColoring: true
    usePreviewTabs: true
  "terminal-plus":
    core: {}
  "tree-view":
    hideIgnoredNames: true
  welcome:
    showOnStartup: false
  whitespace:
    ensureSingleTrailingNewline: false
    ignoreWhitespaceOnCurrentLine: false
    keepMarkdownLineBreakWhitespace: false
    removeTrailingWhitespace: false
".babel.regexp.source":
  editor:
    tabLength: 4
".basic.html.text":
  editor:
    tabLength: 4
".d.source":
  editor:
    tabLength: 4
".diff":
  editor:
    tabLength: 4
".diff.source":
  editor:
    tabLength: 4
".html.php.text":
  editor:
    autoIndent: true
".js.jsx.source":
  editor:
    tabLength: 4
".source.sql":
  editor:
    tabLength: 4

**Comment by netmou** [comment] 2017-06-14 00:31
sorry this is the right step
1.open a project folder A and open tree view
2.remove the project folder A
at this time the tree-view panel is closed
3.open project folder B by menu command
4.remove the project folder B
5.reopen project folder A by menu command
at this time the project folder A is not present in tree-view,but the window title is normal
6.left/right click around tree-view times

**Comment by AHL96** [comment] 2017-06-15 01:48
Sorry for the confusion. When the error occurs, those steps are usually what i did. But idk if those steps are what is causing it to happen because it doesn't happen every time i do those steps,  So it seems

**Comment by daniandl** [comment] 2017-06-16 20:14
Using Project Manager package and Shift+Enter-ing into a package (open in same window) also makes this bug happen. Fixed after a restart of Atom.

**Comment by grex22** [comment] 2017-06-20 02:49
Same problem, same cause here -- Clearing the window state didn't work for me, but what finally did was removing the contents of the /storage directory in my user's Atom folder

**Comment by rsese** [comment] 2017-06-27 22:39
Thanks for confirming @AHL96 - if you do come across specific steps to reproduce let us know.

@netmou - thanks for sharing specific steps.  Can you confirm if you can reproduce in safe mode (`atom --safe`) and can you also share the specific commands for your steps?  If you can share the exact menu item names that you're using, that would be helpful when trying to reproduce.

**Comment by MichaelA59** [comment] 2017-06-28 22:25
I had a project open from the other day I was working in, and then wanted to reference another project from the past so I opened a new window and got this error - thought nothing of it. Restarted my computer and tried booting up my working project and I am getting the same error. I tried clearing window state in the past and it worked, but nothing this time.

**Comment by RNCTX** [comment] 2017-07-21 06:30
Fresh install, (deleted ~.atom folder) on OSX, working in a few files, did a global search and replace in a project folder (for '#!' ajax url functions if that matters), and closed atom with the search box still open.  Upon re-opening, tree-view is broken.  I can toggle it but not put **the same** project folder in it, it remains blank.

I can put a different folder in it and have it show up.

**Comment by rsese** [comment] 2017-07-21 17:30
Thanks @RNCTX - to confirm, what version of Atom are you running and where does the error show up in your steps?  Also, is the error reproducible in safe mode (`atom --safe`)?

**Comment by RNCTX** [comment] 2017-07-21 18:56
@rsese 1.18.0 on OSX Sierra.

The error is strange, after I posted that I was able to get the original folder to re-appear in the file tree by deleting it from the 'recents' history.

My steps were...

- fresh install without packages/configs
- toggle file tree
- open project folder from local drive
- search/replace from the root of that project folder
- close atom

Upon re-opening, I could open a _different_ project folder but opening the same one resulted in a blank file tree and the error that traces back to this bug report.

After clearing the offending project folder from the 'recents' I was able to open it again and everything seems normal.

So I would suspect this is somehow related to the recent projects list and/or the global project search/replace functionality.

**Comment by VadimDor** [comment] 2017-08-15 11:32
The same for me, but tracing refers line 257 instead of 253 on Win8.1 x64:
trying figure the steps out

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core
### Stack Trace
Uncaught Error: Setting active pane that is not present in pane container

```
At C:\Users\User1\AppData\Local\atom\resources\app\src\pane-container.js:257

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (~/AppData/Local/atom/resources/app/src/pane-container.js:257:21)
    at Pane.module.exports.Pane.activate (~/AppData/Local/atom/resources/app/src/pane.js:911:20)
    at Pane.module.exports.Pane.focus (~/AppData/Local/atom/resources/app/src/pane.js:290:25)
    at HTMLElement.<anonymous> (~/AppData/Local/atom/resources/app/src/pane-element.js:51:25)
```

### Commands

```
     -0:53 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -0:38.9.0 tree-view:toggle (input.hidden-input)
```

**Comment by ungb** [comment] 2017-08-17 07:05
I can repro this issue by doing the following:


Repro steps:
1. Open Atom with a project.
2. Rlight Click `Close pane` in the tree-view,  Notice nothing happens
3. right click and remove the project.
4. Tree-view disappears,  Toggle it back open
5. right click and click add folder back
6. Tree view remains empty and if you open dev tools you see error from https://github.com/atom/atom/issues/14454#issuecomment-322984675
7. close tree-view and open it back up and left click on the `tree view`.

**Comment by rsese** [comment] 2017-08-17 20:03
Thanks @ungb and thanks again everyone for the reports - added your steps to the issue body Bryant :bow:

**Comment by clement-bramy** [comment] 2017-08-25 00:43
Another way to reproduce it:

1. Open Atom (no project or folder select, just open it)
2. File | Add Project Folder | Select your project
3. Notice that no directory structure is shown on the left hand "Project" side bar/menu
4. Click on the left hand bar/menu/pane (not sure how it's called)
5. Hiding/showing the left hand tree view pane doesn't show anything/refresh content

Atom: 1.19.3
Windows 7 (sadly)

**Comment by gbittmann** [comment] 2017-10-10 15:34
How I came to this error.

Restart Atom after package update. 

Project pane is empty.
Attempt to load a project, pane is still empty.
Click in Project pane and error appears.

**Comment by IanWhyte** [comment] 2017-10-10 16:55
Yes, I encounter the issue under the same circumstances as gbittman.

**Comment by benyanke** [comment] 2017-10-10 19:54
This occurred to me when I opened two atom windows, clicked a file in tree view on one window, and dragged it's tab on to the second window.

**Comment by allentiak** [comment] 2017-10-13 00:54
> This occurred to me when I opened two atom windows, clicked a file in tree view on one window, and dragged it's tab on to the second window.

Same to me.
Atom version: 1.21.1

**Comment by MihaiTudorP** [comment] 2017-10-26 13:56
I got the same error on Windows 7 in version 1.21.1 x64. I managed to get the project back into view by starting Atom in Safe mode in the project folder (from cmd, run atom --safe), then closed it, then opened it normally. The error did not appear the second time and I could not make it occur again.
Steps taken when the error occurred: Opened Atom normally, from the Start menu. The window did not have the Project tree view. Split the main editor pane left. Opened a file in the left side of the pane. Closed the right half. On closing the right half of the pane, the error appeared and I could not make the project appear in the tree view upon loading it,

**Comment by truefusion** [comment] 2017-11-16 22:11
**Atom**: 1.22.1 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At %AppData%\Local\atom\app-1.22.1\resources\app\src\pane-container.js:257

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.22.1/resources/app/src/pane-container.js:257:21)
    at Pane.activate (~/AppData/Local/atom/app-1.22.1/resources/app/src/pane.js:1002:46)
    at Pane.focus (~/AppData/Local/atom/app-1.22.1/resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
     -4:25.6.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:00.6.0 tree-view:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
acid-syntax 1.0.0 
activate-power-mode 2.6.0 
acute-syntax 1.0.0 
aesthetic-ui 4.0.0 
afterglow-monokai-syntax 1.3.7 
align-regexp 0.4.0 
ample-syntax 0.3.0 
atom-beautify 0.30.6 
atom-material-syntax 1.0.7 
atom-material-ui 2.0.6 
atom-monokai 0.10.9 
atom-numbers 0.7.0 
atom-terminal 0.8.0 
autoclose-html 0.23.0 
ax-monokai-syntax 0.2.0 
bleen-syntax 0.3.1 
browser-plus 0.0.98 
cake-syntax 1.0.2 
classy-syntax 1.1.1 
cmyk-syntax 0.2.0 
color-picker 2.2.5 
dark-bint-syntax 0.10.0 
darya-syntax 0.2.0 
dawn-syntax 0.1.0 
doc-green-syntax 1.1.0 
edm-light-syntax 0.1.2 
emmet 2.4.3 
firewatch-syntax 1.1.1 
genesis-ui 0.5.0 
git-control 0.9.0 
gruvbox-plus-syntax 1.3.1 
html-entities 0.4.0 
html-to-css 0.2.2 
hugs-syntax 1.0.0 
idle-syntax 0.1.0 
juicy-syntax 1.0.5 
katana-syntax 0.1.0 
ker0x-syntax 0.1.3 
language-angelscript 0.1.1 
language-batch 0.4.0 
language-htaccess 0.1.1 
language-markdown 0.25.1 
language-vb 0.1.0-pre1 
language-vbscript 0.9.0 
leet-syntax 1.0.0 
line-ending-converter 1.3.2 
lines 0.13.1 
Lux-Syntax 2.0.0 
markdown-preview-plus 2.4.16 
minimap-git-diff 4.3.1 
monokai 0.24.0 
monokai-faded 0.0.4 
monokai-light 0.4.1 
monokai-plus 0.1.3 
monokai-seti 0.9.0 
monokai-syntax 0.6.0 
Neka-Syntax 1.0.1 
nerv-ous-syntax 1.0.0 
now-syntax 0.2.4 
one-sharp-syntax 3.0.0 
open-terminal-here 2.3.1 
php-cs-fixer 4.1.1 
pigments 0.40.2 
plain-syntax 0.3.0 
polymer-snippets 3.2.1 
power-effects 0.4.0 
prism-syntax 1.4.1 
rad-syntax 0.4.0 
revert-buffer 0.6.0 
sass-autocompile 0.13.3 
save-session 0.15.7 
sequential-number 0.5.0 
simple-align 0.2.0 
simple-drag-drop-text 0.3.6 
sub-monokai 1.4.0 
text-manipulation 0.6.0 
trailing-spaces 0.4.0 
valign 1.1.3 
vivid-syntax 2.1.0 
warm-syntax 1.0.0 
```

**Comment by arsenico13** [comment] 2017-11-19 22:30
I was having the same problem as @epan.
The steps in [his comment](https://github.com/atom/atom/issues/14716#issuecomment-306316518) fixed that issue!

Thank you!

**Comment by raptor235** [comment] 2017-12-18 16:08
Just ran into this issue as well

http://www.flowpress.com/screenshots/screenshot_2017-12-18_at_11.08.21AM.png

**Comment by alexander-ii** [comment] 2018-01-15 15:39
[Enter steps to reproduce:]

1. start atom
1. close window
1. reopen one of the previous projects
1. cmd+\ (the project was opened, but the tree view shows nothing)

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:257

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:257:21)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1002:46)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:393:23)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
     -1:26 find-and-replace:show (atom-pane.pane.active)
     -1:23.8.0 editor:consolidate-selections (input.hidden-input)
     -1:23.8.0 core:cancel (input.hidden-input)
  2x -1:23.2.0 tree-view:toggle (atom-pane.pane.active)
     -1:12.4.0 application:reopen-project (atom-pane.pane.active)
  7x -1:07.1.0 tree-view:toggle (atom-pane.pane)
```

### Non-Core Packages

```
sort-lines 0.18.0 
```

**Closed** 2018-01-23 01:27 UTC
Labels: bug, triaged, uncaught-exception
