### ISSUE TITLE
On OSX Atom freezes after editing any file that needs sudo permission.

### ISSUE THREAD

**Issue by pozgo** [atom/atom#9538] opened 2015-11-12 08:43 UTC
On OSX after editing for example `/etc/hosts` and saving the file. Straight after system asks for your password to be able to overwrite the file Atom is freezing and need to be killed and started again

System OSX 10.11.1
Atom 1.1.0

**Comment by maxbrunsfeld** [comment] 2015-11-19 00:47
This is a duplicate of https://github.com/atom/atom/issues/9360. I believe it's fixed in the latest version of Atom 1.2.0.

**Closed by maxbrunsfeld** 2015-11-19 00:47 UTC
Labels: bug, mac
