### ISSUE TITLE
Ask if we want metrics enabled on first start, rather than leaving it on by default and not asking

### ISSUE THREAD

**Issue by aoighost** [atom/atom#5045] opened 2015-01-14 01:45 UTC
While metrics can be useful, some of us would prefer not to send extra data over the wire. Could you please set it to ask us if we want to send analytics on start and disable it if we say no, rather than just assuming we do?

**Comment by kevinsawicki** [comment] 2015-01-14 01:49
This looks like a duplicate of https://github.com/atom/atom/issues/4966

This has been discussed before as well over on the metrics repo: https://github.com/atom/metrics/issues/16

**Closed by kevinsawicki** 2015-01-14 01:49 UTC
