### ISSUE TITLE
Feature request: cloud-stored editor configurations

### ISSUE THREAD

**Issue by rdnewman** [atom/atom#8274] opened 2015-08-07 18:55 UTC
I use Atom on multiple computers and VMs.  It'd be great if my package installations and configuration settings could be stored in one spot and applied to multiple atom installations.  I'm thinking of this like sync'd browser bookmarks being stored in the cloud.

The feature should be optional, but if implemented like Google does with Chrome, I could imagine creating different profiles with different settings (as a more advanced implementation).  In a simpler implementation, I'd get one profile on the cloud and could simply decide in a given installation whether or not I wanted it to use the stored settings.

**Comment by mnquintana** [comment] 2015-08-07 19:18
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/3572 though – please subscribe there for updates.

**Closed** 2015-08-07 19:20 UTC
Labels: duplicate

**Comment by rdnewman** [comment] 2015-08-07 19:29
Thanks @mnquintana, sorry for the dupe.
