### ISSUE TITLE
Uncaught TypeError: Patch does not apply

### ISSUE THREAD

**Issue by dhswo02** [atom/atom#15511] opened 2017-08-31 01:18 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Patch does not apply

```
At C:\Users\Administrator\AppData\Local\atom\app-1.19.4\resources\app\node_modules\text-buffer\lib\history.js:144

TypeError: Patch does not apply
    at History.module.exports.History.getChangesSinceCheckpoint (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/history.js:144:34)
    at TextBuffer.module.exports.TextBuffer.getChangesSinceCheckpoint (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/text-buffer.js:964:38)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/text-buffer.js:1579:36)
    at later (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/helpers.js:21:13)
```

### Commands

```
     -0:17.6.0 snippets:expand (input.hidden-input)
     -0:17.6.0 editor:indent (input.hidden-input)
     -0:17 core:move-up (input.hidden-input)
     -0:15.9.0 editor:move-to-end-of-word (input.hidden-input)
  2x -0:15.1.0 core:move-left (input.hidden-input)
  3x -0:14.4.0 editor:add-selection-below (input.hidden-input)
     -0:12 editor:consolidate-selections (input.hidden-input)
     -0:11.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
  4x -0:06.7.0 core:select-left (input.hidden-input)
     -0:05.8.0 core:copy (input.hidden-input)
     -0:05.5.0 core:move-down (input.hidden-input)
     -0:05.4.0 core:paste (input.hidden-input)
     -0:05.1.0 core:move-down (input.hidden-input)
     -0:04.9.0 core:paste (input.hidden-input)
     -0:04.7.0 core:move-down (input.hidden-input)
     -0:04.1.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.3 
aligner-javascript 1.2.0 
atom-ternjs 0.18.3 
emmet 2.4.3 
file-icons 2.1.8 
highlight-line 0.12.0 
highlight-selected 0.13.1 
linter 2.2.0 
linter-ui-default 1.6.2 
pigments 0.39.1 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by rsese** [comment] 2017-08-31 05:09
Thanks for taking the time to contribute!  Closing as a duplicate as mentioned below, but if you can share any more details about the error (e.g. do you have steps to reproduce, can you reproduce in safe mode, etc.), please let us know in https://github.com/atom/atom/issues/15480.

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15480. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-31 05:09 UTC
