### ISSUE TITLE
Cannot install package notational-velocity

### ISSUE THREAD

**Issue by zettler** [atom/atom#8279] opened 2015-08-08 00:56 UTC
> runas@2.0.0 install C:\Users\Franz\AppData\Local\Temp\apm-install-dir-11578-3736-1ci43cz\node_modules\notational-velocity\node_modules\pathwatcher\node_modules\runas
     > node-gyp rebuild

    C:\Users\Franz\AppData\Local\Temp\apm-install-dir-11578-3736-1ci43cz\node_modules\notational-velocity\node_modules\pathwatcher\node_modules\runas>node "C:\Users\Franz\AppData\Local\atom\app-1.0.5\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

    npm ERR! Windows_NT 6.2.9200
    npm ERR! argv "C:\\Users\\Franz\\AppData\\Local\\atom\\app-1.0.5\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Franz\\AppData\\Local\\atom\\app-1.0.5\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Franz\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Franz\\.atom\\.apmrc" "install" "C:\\Users\\Franz\\AppData\\Local\\Temp\\d-11578-3736-lajssw\\package.tgz" "--target=0.22.0" "--arch=ia32"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE
    
    npm ERR! runas@2.0.0 install: `node-gyp rebuild`
    npm ERR! Exit status 7
    npm ERR! 
    npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the runas package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls runas
    npm ERR! There is likely additional logging output above.

OS Windows 10, same error on Windows 8.1. Manual installation is failing as well, I've tested the solutions described in other issues with similar problems, none of them worked for me.

https://github.com/seongjaelee/notational-velocity

**Comment by thomasjo** [comment] 2015-08-10 10:53
Do you have Visual Studio 2013 Express (or equivalent and/or a newer version) installed? A VC++ compiler is required by node-gyp in order to compile native modules.

**Comment by batjko** [comment] 2015-08-10 11:50
I think this may be a duplicate of an issue already opened on this package's repository:
https://github.com/seongjaelee/notational-velocity/issues/17

**Comment by mnquintana** [comment] 2015-08-10 11:52
Thanks @batjko - that does look like the same issue. Closing in favor of that issue.

**Closed by mnquintana** 2015-08-10 11:52 UTC
Labels: more-information-needed, windows
