### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/paulryan/Library/Application Sup...

### ISSUE THREAD

**Issue by sharpred** [atom/atom#10721] opened 2016-02-07 11:36 UTC
[Enter steps to reproduce below:]

1. ... click on Atom menu item
2. ... click on preferences

**Atom Version**: 1.4.3
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/lib/parse.js:4:18)
    at Module._compile (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/paulryan/Library/Application Support/com.github.atom.ShipIt/update.Fv7Uumq/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "open-in-browsers"
    ]
  },
  "editor": {
    "fontSize": 16,
    "invisibles": {},
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by demhydraz** [comment] 2016-02-07 11:38
Dupe of #7399.

**Comment by 50Wliu** [comment] 2016-02-07 15:56
Thanks @demhydraz.  Feel free to subscribe there for updates @sharpred.

**Closed by 50Wliu** 2016-02-07 15:56 UTC

**Comment by demhydraz** [comment] 2016-02-07 19:21
o7
