### ISSUE TITLE
Atom freezes when installing packages (and 25% CPU load)

### ISSUE THREAD

**Issue by rugk** [atom/atom#8458] opened 2015-08-20 16:16 UTC
When I'm installing any package with Atom it freezes a short time while it's installing.
Additionally all 5 processes of Atom are causing 25% CPU load.

After the package is installed (so a few seconds) everything is normal again.

Atom 1.0.7
Windows 7

**Comment by mnquintana** [comment] 2015-08-20 16:48
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/7275 though - closing in favor of that issue.

**Closed by mnquintana** 2015-08-20 16:48 UTC
