### ISSUE TITLE
`console.log` in a plugin causes a "EPERM: operation not permitted, write"

### ISSUE THREAD

**Issue by sompylasar** [atom/atom#12504] opened 2016-08-23 17:19 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

The bug has since been reported in several places. The current use case that bothers is that `console.log` is used in the [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react) which is used in the widely adopted [`eslint-config-airbnb`](https://www.npmjs.com/package/eslint-config-airbnb) which is in turn consumed by [`eslint`](https://www.npmjs.com/package/eslint) and [`AtomLinter/linter-eslint`](https://github.com/AtomLinter/linter-eslint).

* https://github.com/AtomLinter/linter-eslint/issues/579 (closed because the AtomLinter team cannot do anything with that)
* https://github.com/yannickcr/eslint-plugin-react/issues/416#issuecomment-177119027 (closed because the issue was not stated properly, or simply comments on closed issues were ignored)
* https://github.com/airbnb/javascript/issues/978#issuecomment-241332995 (can't be fixed in eslint-config-airbnb yet because of other dependencies)
* https://github.com/yannickcr/eslint-plugin-react/issues/783#issuecomment-241778161 (looks like a won't fix because eslint-plugin-react "is a Node module, so using console is valid")

Here's the exception that pops up in Atom:
```
Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2064:6)
    at Console.log (console.js:39:16)
    at EventEmitter.Program (__CENSORED__\node_modules\eslint-plugin-react\lib\rules\require-extension.js:103:17)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (__CENSORED__\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (__CENSORED__\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (__CENSORED__\node_modules\eslint\lib\util\comment-event-generator.js:97:23)
```

Here's one of the faulty lines:
https://github.com/yannickcr/eslint-plugin-react/blob/v3.16.1/lib/rules/jsx-quotes.js#L52
```js
      /* eslint-disable no-console */
      console.log('The react/jsx-quotes rule is deprecated. Please use the jsx-quotes rule instead.');
      /* eslint-enable no-console */
      isWarnedForDeprecation = true;
```

There are more occurences of this pattern in `eslint-plugin-react`:
https://github.com/yannickcr/eslint-plugin-react/blob/e84af68a3bf48c9a34f14e73a8b4dc1ed7488bab/lib/rules/require-extension.js#L103
```js
        /* eslint-disable no-console */
        console.log('The react/require-extension rule is deprecated. Please ' +
                    'use the import/extensions rule from eslint-plugin-import instead.');
        /* eslint-enable no-console */
        isWarnedForDeprecation = true;
```

https://github.com/yannickcr/eslint-plugin-react/search?utf8=%E2%9C%93&q=console.log&type=Code

### Steps to Reproduce

1. Install `atom-linter`, `atom-linter-eslint` plugins, `eslint` and `eslint-plugin-react` modules.
2. Use a `.eslintrc` that uses one of the `eslint-plugin-react`'s deprecated rules; for example, the `eslint-config-airbnb` base config.
3. Run the linting on a JS file.

**Expected behavior:** No error.

**Actual behavior:** The exception mentioned above.

### Versions

Atom 1.9.9 on Windows 7 64bit

`atom --version`
```
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```
`apm --version`
```
apm  1.10.0
npm  2.13.3
node 0.10.40
python 3.5.0
git 1.9.4.msysgit.1
visual studio
```

**Comment by MrSauceman** [comment] 2016-09-01 17:13
+1 Just ran into this today

**Comment by henrikrudstrom** [comment] 2016-09-02 09:40
+1 same thing here

**Comment by elawad** [comment] 2016-09-02 15:02
Had the same issue in Atom. An interim solution was to use these eslint versions:
```
"eslint": "^2.13.1",
"eslint-config-airbnb": "^9.0.1",
"eslint-plugin-import": "^1.14.0",
"eslint-plugin-jsx-a11y": "^1.5.5",
"eslint-plugin-react": "^5.2.2",
```

**Comment by pcan** [comment] 2016-09-09 08:17
Same issue here with atom-typescript. I'm using a custom version of the compiler in atom-typescript that uses `console.warn` and I get the same error. I noticed that this issue happens only when using a child process for the compiler (atom-typescript uses `child_process` if you don't need debug on it). At the beginning I thought that it was a `runInContext` issue, but it works correctly when I disable child process creation. Hope this helps to fix it.

**Comment by mikecousins** [comment] 2016-09-11 17:12
Yup, this one is super annoying.

**Comment by knsakib** [comment] 2016-09-11 21:50
This is super annoying. But in windows, running the Atom as an administrator solves the issue for me.

**Comment by binygal** [comment] 2016-09-19 18:16
Annoying. And running Atom as administrator didn't helped.

**Comment by lee-dohm** [comment] 2016-09-19 22:19
@50Wliu Were you able to reproduce this? I haven't ever run into this when using `console.log` in any of my packages (though I haven't used it recently).

**Comment by Arcanemagus** [comment] 2016-09-19 23:02
I've only ever seen this when the `console.log` is in a Node.js process launched from the package.

**Comment by vdh** [comment] 2016-09-20 03:11
@lee-dohm What is `needs-reproduction` about this?

1. Install Atom on Windows
2. Install the AtomLinter plugin
3. Set up a project that makes a `console.log` call inside `eslint`:

```sh
npm init -y
npm install --save-dev eslint@3.5.0 eslint-config-airbnb@11.1.0 eslint-plugin-import@1.15.0 eslint-plugin-jsx-a11y@2.2.2 eslint-plugin-react@6.3.0
echo '{ "extends": "airbnb" }' > .eslintrc
echo "'foo';" > foo.js
$(npm bin)/eslint .
# Which gives you this on stderr:
# The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.
```

**Comment by 50Wliu** [comment] 2016-09-20 14:47
I *cannot* confirm this on Atom 1.12.0-dev-18089df, Windows 10 x64.

**Comment by MrSauceman** [comment] 2016-09-20 16:04
I reproduce it 15,000 times a day in Atom 1.10.2, Windows 7 and Windows 10.  Maybe it's fixed in dev?

**Comment by mikecousins** [comment] 2016-09-20 16:11
Same, it's definitely still broken in 1.10.2.

**Comment by mikecousins** [comment] 2016-09-20 16:12
![image](https://cloud.githubusercontent.com/assets/725614/18678861/b0d45c06-7f1a-11e6-911c-4e3943e9a1e9.png)

**Comment by saitonakamura** [comment] 2016-09-22 21:48
If anyone interested in a workaround, it's [here](https://github.com/AtomLinter/linter-eslint/issues/579#issuecomment-239143599)

**Comment by omerdn1** [comment] 2016-10-04 17:03
Same here.. Really annoying issue, should really be acknowledged.

**Comment by 50Wliu** [comment] 2016-10-04 20:10
Has anyone been able to reproduce this in the 1.11 betas or 1.12-dev?

**Comment by vdh** [comment] 2016-10-04 23:43
@50Wliu Has the version of the embedded node changed between 1.10.2 and 1.11? Also make sure that ESLint is generating the warning message on the CLI.

**Comment by 50Wliu** [comment] 2016-10-05 00:03
It has in 1.12.0; I can't recall whether or not it has in 1.11.0.

I tried reproducing this again just to be sure using @vdh's example.  However, I do not get any logging about `react/require-extension`; rather, I get the following error:
```
Configuration for rule "eol-last" is invalid:
        Value "always" must be an enum value.
```

**Comment by vdh** [comment] 2016-10-05 00:25
@50Wliu Apologies, it looks like it needs `eslint-config-airbnb-base` locked to an older version to re-create the scenario:
`npm install --save-dev eslint-config-airbnb-base@7.1.0`

**Comment by 50Wliu** [comment] 2016-10-05 19:54
Ok, thanks for the update.  I still can't reproduce this on Atom 1.12.0-dev-fcddf83.  The warning gets printed to the dev tools console as expected.

**Comment by Ben3eeE** [comment] 2016-10-05 20:29
Can reproduce on 1.11 beta but not on 1.12.0-dev-fcddf83.

**Comment by 50Wliu** [comment] 2016-10-05 23:14
Assuming fixed in Atom 1.12.0 or whenever Atom starts using Electron 1.4.1.

**Closed by 50Wliu** 2016-10-05 23:14 UTC
Labels: bug, needs-reproduction, uncaught-exception, windows

**Comment by Edge00** [comment] 2016-12-02 03:47
I fixed this problem by adding 
`"react/require-extension": 0,`
to .eslintrc.js . and my atom works fine now

**Comment by vdh** [comment] 2016-12-04 23:43
@Edge00 You don't need to do that anymore, later versions of `eslint-config-airbnb` have already solved the warning that triggers this Atom issue (by updating to a later version of `eslint-plugin-react`).

**Comment by Edge00** [comment] 2016-12-05 01:36
@vdh  thank you , got it

**Comment by Edge00** [comment] 2016-12-05 01:38
@mikecousins I want to know the name of your atom's fant-family, it's very good-looking

**Comment by mikecousins** [comment] 2016-12-05 02:02
It's called Operator Mono.

http://www.typography.com/blog/introducing-operator

On Dec 4, 2016 6:38 PM, ?? <notifications@github.com> wrote:

@mikecousins<https://github.com/mikecousins> I want to know the name of your atom's fant-family, it's very good-looking

-

**Comment by Edge00** [comment] 2016-12-05 02:20
@mikecousins  Thank you!
