### ISSUE TITLE
PHP Highlighting breaks

### ISSUE THREAD

**Issue by Joseph310** [atom/atom#17410] opened 2018-05-27 16:46 UTC
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

The highlighting does not seem to match the following PHP code.

It breaks completely. The code following these lines also display with the wrong color-coding. It interprets everything as a string.

```
  $sql  = 'INSERT INTO table (id, userId, locale, number, timestamp) VALUES (';
  $sql .= '\''.randomString(8).'\', \''.$userId.'\', \''.$locale.'\', \''.$number.'\', '.$timeStamp.')';
  $conn->query($sql);
```

[Description of the issue]

Simply add the code above to an existing php file. 

**Expected behavior:** 
correct color coding

**Actual behavior:** 
the following code gets colored as if it were a string.

**Reproduces how often:** 
each time

### Versions

Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.1
python 2.7.10
git 2.15.1

**Comment by rsese** [comment] 2018-05-28 18:51
Thanks for opening a new issue with the template details filled out :bow:

I believe this is a duplicate of https://github.com/atom/language-php/issues/331 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-28 18:51 UTC
