### ISSUE TITLE
Uncaught Error: dlopen(~/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keybo...

### ISSUE THREAD

**Issue by T357A** [atom/atom#21772] opened 2020-11-29 05:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.0.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/T357A/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At electron/js2c/asar.js:138

Error: dlopen(/Users/T357A/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Users/T357A/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:1:696929)
    at get_KeyboardLayoutManager (/Users/T357A/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2788409)
    at get_manager (/Users/T357A/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2788511)
    at Object.getCurrentKeyboardLayout (/Users/T357A/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2788637)
    at e.keystrokeForKeyboardEvent (/Users/T357A/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:1057732)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/T357A/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1227949)
    at KeymapManager.handleKeyboardEvent (/Users/T357A/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1225934)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/T357A/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:284919)
```

### Commands

```
     -4:19.8.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment] 2020-12-04 13:01
Duplicate of https://github.com/atom/atom/issues/21773

**Closed by sadick254** 2020-12-04 13:01 UTC
