### ISSUE TITLE
Atom starts with the same files every time, instead of the last files i had open

### ISSUE THREAD

**Issue by weidler** [atom/atom#10466] opened 2016-01-17 15:36 UTC
For some reason atom opens two specific unrelated files every time i start it. one of them doesnt even exist anymore. How can i solve this for now?

**Comment by 50Wliu** [comment] 2016-01-17 15:55
@weidler What Atom version are you on, and do you have `save-session` installed?

**Comment by weidler** [comment] 2016-01-17 16:31
Im on V 1.2.3 and i have not installed `save-sessions`, i thought this feature would be implemented to the atom core as indicated in the package `remember.session`

**Comment by mnquintana** [comment] 2016-01-17 16:41
@weidler You're on an old version of Atom – can you try updating to the latest version (1.4.0) and seeing if you can reproduce this issue?

**Comment by weidler** [comment] 2016-01-17 17:25
I updated, but still it opens the same two files :/

**Comment by mnquintana** [comment] 2016-01-17 17:34
You should be able to fix this by deleting the `~/.atom/storage` directory – can you try that and see if you still experience this issue?

**Comment by weidler** [comment] 2016-01-17 18:21
Hmm, thx, that worked, but now the project tree view doesnt notice git when it points to a non-local remote repository (Git Hub), but still notices git clones of local repositories. 
(doesnt notice = doesnt change the project folder icon and doesnt highlight changed files in the tree view)

**Comment by rsese** [comment] 2017-03-09 06:11
Trying to go through and cleanup some older issues - it looks like your initial issue was resolved after deleting the ~/.atom/storage` directory. 

About the second issue you described with git repositories and the tree view, it's been a while since this report and Atom is currently at release version 1.14.4. I'll go ahead and close the issue for now but if you're still seeing an error with the latest release version of Atom, please feel free to open a new issue and fill out the issue template @weidler :v:

**Closed by rsese** 2017-03-09 06:11 UTC
Labels: more-information-needed
