### ISSUE TITLE
Have to click twice on directory search result to get to the line

### ISSUE THREAD

**Issue by Yajo** [atom/atom#9170] opened 2015-10-16 07:30 UTC
When I do a directory search and click on a line result, it opens the file and leads me to the EOF. Then I have to go back to the results and click again on that line to go to that line. See screen record:

![bloggif_5620a6089f78a](https://cloud.githubusercontent.com/assets/973709/10535970/a7c9f560-73e7-11e5-91b5-c68ec58911c0.gif)

Using Atom 1.0.19 on Linux 64 bit (Fedora 22).

**Comment by 50Wliu** [comment] 2015-10-16 12:18
Duplicate of sindresorhus/atom-editorconfig#51, please subscribe there for updates.

If you don't in fact have editorconfig installed, please comment here!

**Closed by 50Wliu** 2015-10-16 12:18 UTC
