### ISSUE TITLE
Atom only opening from command prompt

### ISSUE THREAD

**Issue by wesleymg** [atom/atom#16965] opened 2018-03-16 19:15 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Earlier today, Atom said that the edit workspace wasn't responding, or something along those lines, I haven't yet been able to recreate the error, as my intent was to see if it just needed a quick restart because I'd left a window open. Atom now won't open from my desktop shortcut nor from the start pane on Windows 10, but it will open from the command prompt.
**Expected behavior:** [What you expect to happen]
Atom opens whenever desktop or star pane shortcut is opened.
**Actual behavior:** [What actually happens]
No response, there aren't any tasks in the task manager related to it either.
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

Atom: 1.25.0
Electron: 1.7.11
Chrome: 58.0.3029.110
Node: 7.9.0
Windows 10, Version 1709

**Comment by lee-dohm** [comment] 2018-03-16 19:16
Have you followed the instructions in the [debugging guide](https://flight-manual.atom.io/hacking-atom/sections/debugging/)? Specifically the part about [clearing saved state](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state)?

**Comment by wesleymg** [comment] 2018-03-16 19:18
I did try that, however, I just updated and the problem has seemingly gone away, because at the time I didn't have access to an internet connection

**Comment by lee-dohm** [comment] 2018-03-16 19:29
Since the original problem is not reproducing anymore, I'm going to close this. Please open a new issue for the new problem if the standard debugging and FAQ suggestions don't help.

**Closed by lee-dohm** 2018-03-16 19:29 UTC
Labels: more-information-needed
