### ISSUE TITLE
Syntax colouring of code blocks confused by language specifier

### ISSUE THREAD

**Issue by ilg-ul** [atom/atom#12166] opened 2016-07-13 18:24 UTC
### Description

The syntax colouring gets confused while editing markdown files containing code blocks with language specifier.

### Steps to Reproduce

1. create a markdown file
2. insert a code block with the three back tick syntax
3. inside the block enter a single asterisk in the middle of the code
4. insert a second code block with the three back tick syntax and follow them by a name (like cpp)
5. inside the block enter an asterisk
6. after the second block enter any text.

**Expected behavior:** 

the asterisk in the middle of the second code block should not affect the formatting.

**Actual behavior:** 

the asterisk switched formatting to italics, and this goes to the end of the file, including the final text.

### Versions

v1.8.0 running on macOS.

![screen shot 2016-07-13 at 21 10 27](https://cloud.githubusercontent.com/assets/362732/16814725/c00cd196-493f-11e6-9738-de439f97663a.png)

the GitHub syntax of highlighted code blocks is defined in

https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by thomasjo** [comment] 2016-07-13 18:28
Duplicate of https://github.com/atom/language-gfm/issues/44.

**Closed by thomasjo** 2016-07-13 18:28 UTC

**Comment by ilg-ul** [comment] 2016-07-13 18:47
the problem is not exactly a duplicate of https://github.com/atom/language-gfm/issues/44, but it might be related.

**Comment by thomasjo** [comment] 2016-07-13 18:50
It is caused by the same problem as the original report, but the issue contains multiple similar issues. The first of which is identical to your issue — see https://github.com/atom/language-gfm/issues/44#issuecomment-73679692.
