### ISSUE TITLE
Dock Handle for Git Tab (right hand dock) not available

### ISSUE THREAD

**Issue by jano23** [atom/atom#15728] opened 2017-09-23 21:05 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Windows 10 Pro 64ibt
Atom 1.20.1 x64
Dell 4K monitors

I don’t know the name of the UI element that shows up when you hover over the Tree View and Git Tab. It’s a half circle with > or < that allows one to toggle these panes. Dock Handle?

InTree View this UI element shows up when you have the pane open or close by hovering the pane when open and close to the edge of the window when closed. It’s working correctly when the Atom interface is anything else except Maximized

On the Git Tab it does not show up when the tab is closed and one hovers close to the edge or on the edge AND the app window is maximized. It worked as expected when this feature first came available but the last 4, or so, updates it has not worked correctly. If I don’t have the editor sized maximized I can use it by hovering over the right edge of the editor. The half circle slides into view.
### Steps to Reproduce

1. Open Atom > Window Maximized >Toggle Git Tab 

**Expected behavior:** I expect the tab handle to appear on mouseover

**Actual behavior:** Tab handle does not show up

**Reproduces how often:**  100% of the time

### Versions

Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![git-tab](https://user-images.githubusercontent.com/759023/30777443-dfffe3e0-a077-11e7-8532-e05549bc90e8.png)

**Comment by rsese** [comment] 2017-09-25 17:27
Thanks for the report - I'm unable to reproduce on Atom 1.20.1 on Windows 10 on my laptop.  Your screenshot seems to show a non-default theme so just to confirm, did you reproduce in safe mode?  Or do you have any custom styles?

**Comment by jano23** [comment] 2017-09-25 17:47
Yes it is there in safe mode.
I have tried several styles. Currently using Atom Light UI and Atom Light Syntax

**Comment by cengizhan** [comment] 2017-09-26 06:59
i also have this bug. it does happen in "atom dark" theme too. randomly right panel toggle button disappears when outlines is visible.

**Comment by rsese** [comment] 2017-09-28 03:58
@jano23 sounds like you're using multiple monitors?  I tested on my laptop with no external monitor connected.  @cengizhan do you also have a multiple monitor setup?

**Comment by jano23** [comment] 2017-09-28 14:40
@rsese Yes indeed. I have multiple monitors on my desktop PC. I typically have Atom open on my right monitor which is also the main one

**Comment by jano23** [comment] 2017-09-28 14:52
I checked one more thing:
The Tree View dock handle works fine on both monitors.

**Comment by cengizhan** [comment] 2017-09-28 17:18
i don't have dual montitor. i am using 1.21 beta on windows 10 x64

**Comment by jano23** [comment] 2017-10-04 02:26
After today's update I am still seeing the problem ~

**Comment by rsese** [comment] 2017-10-04 17:31
It sounds like @cengizhan sees this with a single monitor but curious if you do too @jano23 if you try with just a single monitor?  I'm still unable to repro on 1.21.0 on a Windows 10 laptop.

And do you remember the last version of Atom where this wasn't an issue for you?

**Comment by jano23** [comment] 2017-10-04 19:39
@rsese - I have multiple monitors - that is where the problem shows up. It started showing up in the last 2 versions including yesterdays update. So yes, last 2 updates.
I think it's a multiple monitor issue.

**Comment by rsese** [comment] 2017-10-05 05:43
@ungb @Ben3eeE - can y'all try reproducing this one?  I tried with another monitor but was still unable to repro, I think you mentioned that you had an idea about this one @Ben3eeE?

**Comment by jano23** [comment] 2017-10-31 23:24
The bug is still there on 1.21.2 x64

**Comment by jano23** [comment] 2017-11-08 13:45
Issue still there in ver 1.22.0 x64

**Comment by ungb** [comment] 2017-12-05 01:37
@jano23 I'm trying to understand this issue a bit better.  I know that the git panel has a way to remove the panel from the dock.  When this is done.  the dock is consider empty so no arrow will pop up.


![image](https://user-images.githubusercontent.com/5624870/33585337-8dd77a72-d918-11e7-9470-3598c1ea2de2.png)




I'm on windows x64 with duel monitors and haven't seen this issue.  

Is there any way you can provide a screenshot or gif of what you're doing?  
Also if you drag the tree-view over to the right side and toggle the right side, does it work?


I wasn't able to repro with the steps provided:

>Open Atom > Window Maximized >Toggle Git Tab

**Comment by jano23** [comment] 2017-12-13 14:04
@ungb 
What I am talking about is the toggle of the Git Tab (View > Toggle Git Tab)(Ctrl+Shift+9)
If the tab is open on the right and one mouses over the tab a handle slides out on the left edge of the tab. I'm including the image with a red circle around what I am calling a handle.
This handle allows one to toggle the tab. Click on it and the tab slides out of view to the right. Once out of view one is suppose to be able to mouse over the right most edge and have the handle slide back into view so it can be clicked.
The handle does not slide into view and today's update didn't fix the problem (1.23.0 x64)
By contrast, Toggle Tree View on the left (View > Toogle Tree View)(Ctrl+/) does work as it should.
Others are experiencing the same issue
![gitview](https://user-images.githubusercontent.com/759023/33942595-a8f7bc2e-dfd3-11e7-85e1-96a47f0ebc8f.png)

**Comment by jano23** [comment] 2017-12-13 23:38
1.23.1 x64 doesn't fix this issue either

**Comment by 50Wliu** [comment] 2017-12-16 17:32
I can repro this.  Your window _must_ be maximized.
Here's a gif - sorry for its large size as I had to capture the entire length of my window. (Also, ignore the ❄️)
![right-hand-dock-toggle](https://user-images.githubusercontent.com/2766036/34072870-03fdec52-e25d-11e7-853f-6c360674995a.gif)

Atom    : 1.25.0-dev-bba2c474c
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by ungb** [comment] 2017-12-19 20:28
@jano23 which theme / syntax are you using?  I wonder if that could be causing it.  I am unable to repro the issue on windows or mac as well.

**Comment by jano23** [comment] 2017-12-19 21:44
Doesn't seem to matter what theme or syntax is being used. I don't have a Mac with dual monitors so I can't speak to that.

**Comment by ungb** [comment] 2017-12-20 00:21
I'm on windows 10 using the default `One Dark` Theme and Syntax and don't see this issue.   I tried on a single and dual monitors and I am unable to see this issue.  

>Doesn't seem to matter what theme or syntax is being used. I don't have a Mac with dual monitors so I can't speak to that.

@jano23 you went back to `One Dark` and are still able to repro this issue? 

Do you have any custom keybindings in your keymap.cson?   The only time I know the arrow would be removed is if there is no item inside the dock item.  This could happen when the git pane is closed by clicking on the X button or if there was a custom keybinding to remove this.  

![image](https://user-images.githubusercontent.com/5624870/34184707-234c3886-e4d6-11e7-86b8-f21ff7f0fbf3.png)



Also, can you provide the github package version as well?  Just to ensure you're using the one bundled with Atom.  You can find this info in `Settings -> Packages` and search for github.

Atom 1.23.1 should be using `github package 0.8.3`.


One other thing you can try to see if it's the github package or the dock on the right hand side is move the `tree-view` to the right hand side.

Here's a gif of what I mean:

![movetree](https://user-images.githubusercontent.com/5624870/34184831-d4615a20-e4d6-11e7-8d7c-5491421fbc35.gif)

**Comment by 50Wliu** [comment] 2017-12-20 00:41
@ungb your Atom window isn't maximized.  As I mentioned, it _must_ be maximized in order to be able to repro this bug.

**Comment by jano23** [comment] 2017-12-20 03:02
github package 0.8.3 is what shows up on my PC.
The problem shows up with all the themes I have loaded including One Dark.
I don't have any custom keymap.cson file - it's blank.
If I drag TreeView to the right it does the same thing - with the window mazimized, and dragging the mouse over the right edge, nothing slides out.
Again, the window has to be mazimized - if it's not maximized it works as expected EXCEPT the cursor has to go all the way until it turns to a double arrow THEN it slides out. 
It almost feels like the target area for the mouse to hover is non-existant or is so thin (1pixel) that it won't show up till the mouse goes OVER or ON the edge.

**Comment by 50Wliu** [comment] 2017-12-20 03:36
Yeah, the div is 1px wide.  Changing it to 2px fixes it for me.  But that doesn't explain why it works for the left edge but not the right.

Also, @jano23 I noticed that you're using a 4K monitor.  What's your DPI scaling set to?  Mine's 150%.

**Comment by ungb** [comment] 2017-12-20 07:04
After further investigation I set mine to 150% and I'm able to repro the issue.


@jano23 I'll bring it up with a team now that we have a consistent repro.  

for now, if you add the following to your `styles.less`
```css
.atom-dock-inner.right {
  min-width: 2px; // increasing width for dock arrow to appear.
}
```

it should fix the issue for you if 2 doesn't work, try increasing it.  

/cc @simurai do you know if there would be any issues if we increase the pixel to 2px as it seems that if you maximize on Windows 10 with 150% scale this doesn't work currently.

**Comment by simurai** [comment] 2017-12-20 10:57
> with 150% scale

Using a 150% scale, does that make things look smaller? I can imagine that if `1px` gets scaled to something like `0.75px` or so, then it's too small for the mouse pointer? Or it gets pushed off the edge?

Anyways, I think increasing to 2px is fine. Just themes that cared about the 1px gap, would have to adjust it for 2px:

![screen shot 2017-12-20 at 7 52 19 pm](https://user-images.githubusercontent.com/378023/34203779-a41979b2-e5bf-11e7-94b5-1d9ca2053912.png)

I'll make a PR.

**Comment by jano23** [comment] 2017-12-20 12:53
Yes, mine display is set to 150% scale and YES, adding min-width: 2px fixes the problem!

**Closed** 2017-12-21 02:13 UTC
Labels: bug, triaged
