### ISSUE TITLE
focus problem with same doc open in two panes

### ISSUE THREAD

**Issue by rcrooks** [atom/atom#3441] opened 2014-09-03 01:31 UTC
To reproduce:
1. open two panes, with the same doc in both panes
2. select and cut lines from one pane
3. switch to the other pane, select a different location, press return to create a new line

Expected result: focus is on the new line, so I can paste the clipboard contents there to move them
Actual result: focus shifts back to original pane, so if I paste, I'm pasting the contents right back to same location

**Comment by kevinsawicki** [comment] 2015-07-27 23:08
Closing this out since it wasn't reproducible and hasn't been reported in the last 10 months or so, please comment if you still experience this on Atom 1.0+

**Closed by kevinsawicki** 2015-07-27 23:08 UTC
Labels: more-information-needed
