### ISSUE TITLE
Emoji image support

### ISSUE THREAD

**Issue by SoniEx2** [atom/atom#8006] opened 2015-07-21 16:18 UTC
Can we get the text editor to show emoji (the Unicode symbols more specifically, not markdown emoji) as images? I didn't see a plugin for it...

**Comment by 50Wliu** [comment] 2015-07-22 01:14
What Atom version are you running?  1.0.2 should support this already (#6027).

**Comment by SoniEx2** [comment] 2015-07-22 01:25
I mean like on Windows/Linux. I'm too cheap for a mac.

**Comment by paulcbetts** [comment] 2015-07-22 04:58
Windows emoji icons are garbage, you don't want to see them anyways

**Comment by SoniEx2** [comment] 2015-07-22 05:53
I never said anything about using native icons.

I thought "images" implied HTML \<img\> tags, mostly because atom *is* HTML after all. Apparently HTML coders don't think images mean, you know, images.

I know nothing about the HTML world tho so I'll probably be wrong quite often.

**Comment by batjko** [comment] 2015-07-22 13:45
Tried this package?
https://atom.io/packages/autocomplete-emojis

**Comment by SoniEx2** [comment] 2015-07-22 16:17
Yeah, but it requires an emoji font (which I do have, but I want the same emoji you can find on the commits for this repo, that is, actual image emoji, not plain emoji typefaces).

**Comment by denysvitali** [comment] 2016-06-29 20:42
Any update on this?
I can only display emojis in the "unicode way" 
In Firefox 47 I can see them without any problem (I do have installed the twemoji-color-font-1.0_beta1-4 package from AUR - Arch Linux)
## Firefox
![screenshot from 2016-06-29 22-40-31](https://cloud.githubusercontent.com/assets/4939519/16468122/ae130e56-3e4a-11e6-97e1-6952edf87e86.png)

## Atom
![screenshot from 2016-06-29 22-40-00](https://cloud.githubusercontent.com/assets/4939519/16468063/6fe77004-3e4a-11e6-994c-047d0460decd.png)

## Reference
http://emojipedia.org/objects/

**Comment by Jop-V** [comment] 2016-11-08 16:36
+1 Emoji's display fine in Chrome, but black and white in Atom.

**Comment by 50Wliu** [comment] 2016-11-08 17:39
I cannot reproduce this on 1.13.0-dev-09d56d6, Windows 10 x64.  Will close as soon as #12696 is merged.

**Comment by Jop-V** [comment] 2016-11-08 17:49
Looks like this is a Linux-specific issue then.

**Comment by langri-sha** [comment] 2017-04-27 18:37
I added "Noto Color Emoji" to my font list and I get this working nicely.

![image](https://cloud.githubusercontent.com/assets/77084/25498660/2ace6266-2b89-11e7-847c-85c03db0246e.png)

However, when I tried installing EmojiOne Color things just break, I have to remove it and then it renders nicely again 😕.

**Comment by damieng** [comment] 2017-05-05 22:25
Confirm this works on the forthcoming Electron 1.16 update branch 
![image](https://cloud.githubusercontent.com/assets/118951/25766372/0d9d805e-31a7-11e7-8646-f7e456c8517e.png)

**Closed** 2017-05-19 11:38 UTC
Labels: linux, more-information-needed, windows
