### ISSUE TITLE
incorrect line ending

### ISSUE THREAD

**Issue by neurobashing** [atom/atom#5384] opened 2015-02-03 22:08 UTC
When I updated to 0.177.0, line endings are incorrectly represented:

![screen shot 2015-02-03 at 17 04 49](https://cloud.githubusercontent.com/assets/59380/6030640/dee826aa-abc6-11e4-81aa-ed566decd461.png)

So in this pic, typing additional characters produces 
![screen shot 2015-02-03 at 17 07 32](https://cloud.githubusercontent.com/assets/59380/6030683/2c63ab66-abc7-11e4-8c42-72fb2f27f918.png)

This occurs in --safe mode as well.

**Comment by mnquintana** [comment] 2015-02-03 22:45
What OS?

**Comment by neurobashing** [comment] 2015-02-03 22:47
Mac OS X 10.10.2

**Comment by kevinsawicki** [comment] 2015-02-03 22:47
@neurobashing Can you share a link to a file that exhibits the behavior in that screenshot?

**Comment by neurobashing** [comment] 2015-02-03 22:49
I can recreate by simply typing a long string in an empty buffer; but here's a test file https://www.dropbox.com/s/hidyssinhm31v7w/broken_editor.txt?dl=0

**Comment by dasilvacontin** [comment] 2015-02-04 02:13
I couldn't reproduce.

**Comment by postcasio** [comment] 2015-02-04 11:55
What font are you using?

**Comment by neurobashing** [comment] 2015-02-04 14:19
Tried w/ Source Code Pro, Menlo, and Inconsolata (ranged from 12 to 16). Inconsolata 14 fixes the problem; the former 2 show either the same problem or a kind of opposite number - where, as in my screenshot, the trailing quote appears between 'un' as if placed there w/ a funny CSS z-index.

**Comment by mnquintana** [comment] 2015-02-04 14:29
Which syntax and UI themes do you have active?

**Comment by neurobashing** [comment] 2015-02-04 14:35
happens for me with any combination of theme and syntax; I went through a few (the ones Atom ships with) and it's always the font that triggers it.

FWIW I moved ~/.atom out of the way and started a new instance which did not exhibit this.

**Comment by muchweb** [comment] 2015-02-04 15:24
I have similar effect when using custom font that is missing some symbol. Atom will insert missing symbol from a different font, shifting the whole line a little bit, which will put cursor off the real position.

**Comment by miixit** [comment] 2015-02-07 15:17
Exact same issue on Windows 8.1 since v0.177. Changing font may help a little but don't totally resolve the issue for me...

**Comment by miixit** [comment] 2015-02-07 17:42
Reverted back to v0.176 to solve issue. Worked. Make a fresh install also resolve issue. Maybe an issue with updater or so...

**Comment by postcasio** [comment] 2015-02-07 18:11
There was a similar issue to this reported on discuss.atom.io where the culprit was `text-rendering: optimizeLegibility;` in the user styles.

**Comment by developit** [comment] 2015-02-08 20:13
@postcasio Thank you for that tip-off, that was my issue as well! It was causing strange things like overlapping single quotes.  FWIW, `-webkit-font-smoothing: antialiased;` seems to replicate the text rendering style without triggering the odd rendering.

**Comment by maqdev** [comment] 2015-02-16 10:11
For me the problem was with theme `trendy-light-ui` which also uses `text-rendering: optimizeLegibility` in it's styles. Removed it from sources and now everything is OK.

**Comment by willogden** [comment] 2015-02-25 09:08
Had the same issue and removing `text-rendering: optimizeLegibility;` from my user stylesheet fixed it for me.

**Comment by ebraminio** [comment] 2016-05-31 13:11
This should be closed as the upgrade to Chrome 49 on Electron 0.37 which atom uses now which has set optimizeLegibility default, AFAIK.

**Closed** 2016-05-31 13:22 UTC
Labels: bug, editor-rendering
