### ISSUE TITLE
Disabled package is enabled when updated

### ISSUE THREAD

**Issue by csholmq** [atom/atom#8725] opened 2015-09-09 09:10 UTC
Had the linter-clang package as disabled when prompted that a new update was out. When finalized, package was suddenly enabled.

Caused an issue as I already had linter-gcc installed which utilizes the same key commands, thus colliding.

**Comment by izuzak** [comment] 2015-09-09 09:12
Seems like a duplicate of https://github.com/atom/settings-view/issues/603

**Closed by izuzak** 2015-09-09 09:12 UTC
