### ISSUE TITLE
Packages, Install options under Settings lock up Atom

### ISSUE THREAD

**Issue by karai17** [atom/atom#7394] opened 2015-06-24 00:24 UTC
Since a few updates ago, I've noticed that loading the Packages or Install options in the Settings window completely locks up Atom. I have to click "Keep Waiting" up to several times before Atom becomes operable again. This happens every single time I go into these menu options.

Atom 211
Windows 7 x86_64

**Comment by WoodyWoodsta** [comment] 2015-06-28 13:14
Also having this issue. I'm finding the freezing is happening pretty randomly for me. If I find something that reproduces the hang, I'll post it here!

Atom 1.0.0
Windows 8.1 64bit

**Comment by batjko** [comment] 2015-06-28 13:35
Probably a dupe of this one: https://github.com/atom/atom/issues/7275

**Comment by WoodyWoodsta** [comment] 2015-06-28 16:56
@batjko - Noted!

**Comment by poci-hu** [comment] 2015-08-06 11:35
I also have this problem. First, on windows 8.1, now on Windows 10 too. I am running 64bit operating system, Started using Atom from 1.0.2, problem persist on 1.0.4 too

**Comment by batjko** [comment] 2015-08-06 11:45
@poci-hu Please also follow the previous issue I linked above (#7275), which seems to deal with this issue already and will likely be updated when a fix has been applied.

**Comment by mnquintana** [comment] 2015-08-06 11:56
Thanks @batjko! This does indeed seem like a duplicate of https://github.com/atom/atom/issues/7275, so I'm going to close this out in favor of that issue.

**Closed by mnquintana** 2015-08-06 11:56 UTC
