### ISSUE TITLE
atom is getting unresponsive while updating packages

### ISSUE THREAD

**Issue by mmmurf** [atom/atom#4404] opened 2014-12-05 13:36 UTC
also while installing other packages the search becomes unresponsive, as do the install buttons on other search results.

**Comment by 50Wliu** [comment] 2015-12-22 02:18
Closing this as a duplicate of atom/settings-view#519.  Sorry for the suuuuper-slow response time :(.

**Closed by 50Wliu** 2015-12-22 02:18 UTC
