### ISSUE TITLE
Default encoding state problem

### ISSUE THREAD

**Issue by lw1990** [atom/atom#10046] opened 2015-12-14 06:33 UTC
The core settings File Encoding does not have the option for "Default character set encoding to use when reading and writing..." to be set to "AUTO DETECT" which is the best option. you can find it in Ctrl+Shift+U

**Comment by 50Wliu** [comment] 2015-12-14 15:10
Thanks for the report - I'm pretty sure that this is a duplicate of atom/encoding-selector#24, so please subscribe there for updates.

**Closed by 50Wliu** 2015-12-14 15:10 UTC
