### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by Policy51** [atom/atom#13168] opened 2016-11-09 16:25 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description
The Open Config folder button and any other option that is highlighted in the setting tab has a graphical glitch

Video of UI bug: https://youtu.be/FUVDe-IkmAs

### Steps to Reproduce

1. Open Atom
2. Pin Atom to the right/left border on your screen
3. have the setting tab open
4. Moving cursor between the options inside the setting tab and the other tabs

### Versions
Atom 1.11.2
Windows 10 64bit

**Comment by Ben3eeE** [comment] 2016-11-09 18:01
This is a duplicate of https://github.com/atom/settings-view/issues/843 and should be fixed in Atom 1.12.

**Closed by Ben3eeE** 2016-11-09 18:01 UTC
