### ISSUE TITLE
Allow Saving in UTF-* with BOM

### ISSUE THREAD

**Issue by ender3** [atom/atom#5748] opened 2015-02-25 20:13 UTC
Leaving aside all arguments about whether a Byte Order Marker is a good thing or a bad thing (I don't much care) there are situations in which software which will be reading the files produced by atom require it to be there. This should be an option in the encodings menu.

Further if a Byte Order Mark is present in a file, it should not be displayed (it currently is), and should be kept in its current state when saving a file (it can be deleted by an unknowing user who thinks it is an extra space, or mangled by auto-indent).

**Comment by lee-dohm** [comment] 2015-02-26 01:20
This is a duplicate of atom/encoding-selector#18. Please subscribe to that issue for updates.

Thanks for reporting!

**Closed by lee-dohm** 2015-02-26 01:20 UTC
