### ISSUE TITLE
atom build failed

### ISSUE THREAD

**Issue by ZhangKejun** [atom/atom#19946] opened 2019-09-24 01:27 UTC
1、delete atom 
2、clone again
3、script/bootstrap

error logs:
bash-3.2$ script/bootstrap
Node: v10.16.2
Npm:  v6.11.3
Installing script dependencies
/Users/01388087/ZKJ/Github/Atom/script/node_modules/electron-mksnapshot/download-mksnapshot.js:19
  if (err != null) throw err
                   ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-mksnapshot@4.2.0 install: `node ./download-mksnapshot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-mksnapshot@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/01388087/.npm/_logs/2019-09-24T01_15_14_984Z-debug.log
child_process.js:650
    throw err;
    ^

Error: Command failed: npm --loglevel=error install
/Users/01388087/ZKJ/Github/Atom/script/node_modules/electron-mksnapshot/download-mksnapshot.js:19
  if (err != null) throw err
                   ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-mksnapshot@4.2.0 install: `node ./download-mksnapshot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-mksnapshot@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/01388087/.npm/_logs/2019-09-24T01_15_14_984Z-debug.log

    at checkExecSyncError (child_process.js:629:11)
    at Object.execFileSync (child_process.js:647:13)
    at module.exports (/Users/01388087/ZKJ/Github/Atom/script/lib/install-script-dependencies.js:9:16)
    at Object.<anonymous> (/Users/01388087/ZKJ/Github/Atom/script/bootstrap:37:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

what's the problem?

_Originally posted by @ZhangKejun in https://github.com/atom/atom/issues/19944#issuecomment-534347554_

**Comment by Arcanemagus** [comment] 2019-09-24 15:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/19944. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-09-24 15:56 UTC

**Comment by ZhangKejun** [comment] 2019-10-12 06:46
> Thanks for taking the time to contribute!
> 
> We noticed that this is a duplicate of #19944. You may want to subscribe there for updates.
> 
> Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.
> 
> For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

If it is a network problem, how to prove it?
Your answer did not help me.
