### ISSUE TITLE
Constantly crashes on Windows. Will not re-open until system is rebooted

### ISSUE THREAD

**Issue by jdinard** [atom/atom#9985] opened 2015-12-09 05:37 UTC
Hi guys,

Atom is repeatedly crashing on windows (it happens after about 5-10 minutes of usage). (version 1.2.4)

Nothing seems to fix the issue.

Unfortunately, when it crashes, it produces no reports that I can see.

The interesting part is that I can't re-open atom until I reboot windows. Even attempting to run it with the --safe tag makes no difference, it simply will not open. 3 processes start, and I can see them in task manager, but nothing I do causes any windows to open.

**Comment by lee-dohm** [comment] 2015-12-09 05:40
* What if you launch with `atom --safe` the first time you run Atom after a reboot?
* How did you install Atom?
* Where did you install Atom?

Also, can you try the following:

1. Reboot your machine
1. **Do not** launch Atom yet
1. Move the `$HOME\.atom` directory somewhere else
1. Launch Atom using `atom --safe`

And see if that reproduces the issue.

**Comment by jdinard** [comment] 2015-12-09 05:52
What if you launch with atom --safe the first time you run Atom after a reboot?
- Trying this now after deleting the .atom folder. So far no crashes. The only plugin I had installed though was the react.js one.

How did you install Atom?
- Windows installer on the website

Where did you install Atom?
- Default location from installer

I tried what you request

**Comment by lee-dohm** [comment] 2015-12-09 06:07
Let us know if moving the `.atom` folder fixes it. If so, it was either a wedged piece of serialized state or something in your configuration. If you wouldn't mind holding on to that moved folder, it might be helpful in debugging this later.

**Comment by jdinard** [comment] 2015-12-10 05:31
It sort of fixed it. It crashed again - running in safe mode. This time however I was able to start it back up in safe mode without rebooting windows.

**Comment by lee-dohm** [comment] 2015-12-10 06:18
Which version of Windows are you running?

/cc @raelyard @50Wliu for ideas on where crash logs might be stored.

**Comment by raelyard** [comment] 2015-12-10 12:31
I'm guessing Windows 7 - let's see if that's right.  Strange locks that don't resolve with a reboot is something I've seen there but nowhere else.  Perhaps duplicate of/related to #9644.

Crash dumps get written to: %LocalAppData%\Temp\Atom Crashes

Typically with a crash that writes a dump, you'll see a dialog saying "The Editor has crashed" or something like that.

**Comment by jdinard** [comment] 2015-12-21 20:58
I was running Windows 7.

After not being able to deal with the issue, I thought it mightve been some virus (had a few other issues and it had been years since I'd reformatted), I decided to reformat and install windows 10.

Unfortunately other weird file locking issues are persisting.

Up until a few minutes ago, I was having the same issue as this guy https://github.com/yeoman/generator-angular/issues/1208

For whatever reason, the grunt file watcher/cleaner doesn't seem to play well with atom at all.

I just randomly get locked out of files and have their permissions/ownership changed until I reboot.

**Comment by damieng** [comment] 2016-04-13 19:33
Given you no longer have problems since upgrading to Windows 10 and that we don't have a repro I'm going to close this bug for now. Please re-open if the problem comes back.

**Closed by damieng** 2016-04-13 19:33 UTC
Labels: more-information-needed, windows
