### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Applications/mamp/htdocs/Campaign Moni...

### ISSUE THREAD

**Issue by kendrajordan** [atom/atom#18904] opened 2019-02-25 00:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Applications/mamp/htdocs/Campaign Monitor/libraries'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/Applications/mamp/htdocs/Campaign Monitor/libraries'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (/Users/kendra/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:911648)
    at TreeView.t.exports.TreeView.onDrop (/Users/kendra/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:917567)
    at HTMLDivElement.<anonymous> (/Users/kendra/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:892277)
```

### Commands

```
     -8:51.3.0 core:backspace (input.hidden-input)
  2x -8:25.7.0 core:save (input.hidden-input)
     -5:44.2.0 core:backspace (input.hidden-input)
     -5:42.5.0 core:paste (input.hidden-input)
  2x -5:34.4.0 core:save (input.hidden-input)
     -4:16.8.0 tree-view:copy (span.name.icon.icon-file-directory)
     -4:05.8.0 core:paste (input.hidden-input)
     -3:59.1.0 core:undo (input.hidden-input)
     -3:49.2.0 tree-view:move (span.name.icon.icon-file-directory)
     -3:40.1.0 core:paste (input.hidden-input)
     -3:37.6.0 core:undo (input.hidden-input)
  6x -3:18.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
emmet 2.4.3 
language-vue 0.24.0 
platformio-ide-terminal 2.9.0 
```

**Comment by rsese** [comment] 2019-02-25 19:06
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-25 19:06 UTC
