### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 183Error: Cannot cal...

### ISSUE THREAD

**Issue by KBarnett8419** [atom/atom#17933] opened 2018-08-27 18:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 183
Error: Cannot call function 'getPosition' on missing remote object 183
    at throwRPCError (C:\Users\KatBarnett\AppData\Local\atom\app-1.29.0\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\KatBarnett\AppData\Local\atom\app-1.29.0\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\KatBarnett\AppData\Local\atom\app-1.29.0\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At C:\Users\KatBarnett\AppData\Local\atom\app-1.29.0\resources\electron.asar\renderer\api\remote.js:221

Error: Cannot call function 'getPosition' on missing remote object 183
Error: Cannot call function 'getPosition' on missing remote object 183
    at throwRPCError (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/renderer/api/remote.js:125:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.29.0/resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.29.0/resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.29.0/resources/app/src/window-event-handler.js:191:32)
```

### Commands

```
  2x -8:56.4.0 application:open-folder (input.hidden-input)
 13x -3:16.6.0 core:move-down (div.tool-panel.tree-view)
     -3:12.8.0 find-and-replace:show (div.tool-panel.tree-view)
  6x -3:06.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
styri-syntax 0.2.0 
```

**Comment by rsese** [comment] 2018-08-28 08:05
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-08-28 08:05 UTC
