### ISSUE TITLE
Weird behavior regarding backslashes and merging quotes and parentheses

### ISSUE THREAD

**Issue by zmbc** [atom/atom#11029] opened 2016-03-02 07:55 UTC
### Description

Not sure if I'm using the right term for this: when you type a `(` into Atom, it automatically fills in the other one, so that your file now looks like `()`. If you then type a `)`, this character is merged into the other one, so that you don't accidentally do this: `())`. This feature is available for `"` as well.

This merging does not occur if a `)` or `"` is typed directly after a backslash, which I assume is because a backslash is often used to escape these characters as literals. What doesn't make sense is that merging does not occur on the subsequent character, either: so typing `(\z)` on your keyboard renders `(\z))` in your file. This is especially annoying when it comes to strings, because something like `"\n"` will become `"\n""` unless the user is specifically wary of this bug.

### Steps to Reproduce

1. Open a new file
2. Type (as in, literally hit these keys) `(\z)`

**Expected behavior:** The file to contain `(\z)`

**Actual behavior:** File contains `(\z))`

### Versions

atom 1.5.3, apm 1.6.0

**Comment by 50Wliu** [comment] 2016-03-02 13:59
This is a duplicate of atom/bracket-matcher#80 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-02 13:59 UTC
