### ISSUE TITLE
Failed to load the line-ending-selector package

### ISSUE THREAD

**Issue by mgopi** [atom/atom#8830] opened 2015-09-17 23:21 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.12
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core
### Stack Trace

Failed to load the line-ending-selector package

```
At ENOENT: no such file or directory, lstat '/Users/gmunisifreddy/Downloads/Atom.app'

Error: ENOENT: no such file or directory, lstat '/Users/gmunisifreddy/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1449:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:108:13)
    at tryFile (module.js:104:22)
    at tryPackage (module.js:92:10)
    at Function.Module._findPath (module.js:155:20)
    at Module._resolveFilename (module.js:332:25)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.11
compare-files, v0.6.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-09-17 23:59
@mgopi did you move Atom while it was running?

**Comment by mgopi** [comment] 2015-09-18 05:55
I was trying to compare two large XML files ~ 1 mb each. I see the app crashing consistently when I try to compare large files.

**Comment by mnquintana** [comment] 2015-09-18 11:40
@mgopi In that case, it sounds like the problem lies with the package [compare-files](https://atom.io/packages/compare-files), but that honestly seems completely unrelated to this particular uncaught exception. Did you do anything else besides compare files before this specific exception occurred? Can you reproduce this consistently? If so, can you provide reproduction steps? Thanks!

**Comment by curtisforrester** [comment] 2015-09-19 22:07
I just saw this immediately after relaunching Atom. Closed and relaunched again and it did not happen again. Repeated the cycle a few more times but it didn't happen again.

**Comment by bkboggy** [comment] 2015-10-24 19:28
I got this when tried starting atom from command line in Windows 7.  It didn't start Atom.  I then typed atom filename and it started it up, opening both instances.  The original instance displayed the error.  Could not reproduce it again.

**Comment by 50Wliu** [comment] 2016-12-15 16:01
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8830#issuecomment-141425035. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2016-12-15 16:01 UTC
Labels: more-information-needed, uncaught-exception
