### ISSUE TITLE
Findable Settings

### ISSUE THREAD

**Issue by KiYugadgeter** [atom/atom#11896] opened 2016-06-04 01:10 UTC
### Settings is not Findable 

[Can not find string on Settings]

### Steps to Reproduce

1. [Open Settings]
2. [Open Find and Replace]
3. [Search a word]

**Expected behavior:** highlight a word if it exists

**Actual behavior:** Does not highlight in spite of the word exists

### Versions

Atom 1.7.4

**Comment by mnquintana** [comment] 2016-06-04 01:12
This looks like a duplicate of https://github.com/atom/settings-view/issues/284 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-06-04 01:12 UTC
