### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=read ECONNRESET

### ISSUE THREAD

**Issue by KZhou-ZJU** [atom/atom#14312] opened 2017-04-27 07:22 UTC
[Enter steps to reproduce:]

1. Install
2. Disable markdown-preview

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=read ECONNRESET

```
At stream.js:74

Error: tunneling socket could not be established, cause=read ECONNRESET
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-04-27 17:32
Thanks for the report!  Can you confirm if the error is reproducible and if so, do you see the error in safe mode (atom --safe) as well?

**Comment by CesarNog** [comment] 2017-05-02 16:41
I am having the same issue.

**Comment by annimesh2809** [comment] 2017-06-19 08:26
I am also having this issue

**Comment by rsese** [comment] 2017-06-22 22:47
@CesarNog @annimesh2809 - can you describe steps to reproduce the error and can you both confirm if you're behind a proxy?

**Comment by annimesh2809** [comment] 2017-06-23 14:55
I am not sure how to reproduce the error but I can confirm that I'm behind a proxy!

**Comment by rsese** [comment] 2017-06-23 18:33
So just to confirm, you see the error randomly and it's not reproducible with consistent steps?

**Comment by annimesh2809** [comment] 2017-06-25 14:03
I could not figure out any pattern or consistent steps that reproduce the error. However, Atom did not throw any error while I was with a non-proxy network.

**Comment by rsese** [comment] 2017-06-26 20:40
Thanks @annimesh2809 - since it's intermittent and not consistently reproducible and you don't see the error from a different network without a proxy, it's possible that it's a network specific issue.  I'll go ahead and close this for now but if anyone runs into an issue that seems Atom specific and is reproducible, please let us know and we can re-open.

**Closed by rsese** 2017-06-26 20:40 UTC
Labels: more-information-needed, uncaught-exception
