### ISSUE TITLE
editor is not reponding when i open a large json file  --  Windows 10

### ISSUE THREAD

**Issue by BruceZhang1993** [atom/atom#10267] opened 2016-01-04 05:49 UTC
xx.json     filesize:  2,359,640 bytes

Windows 10 Version 10.0.10586

**Comment by BruceZhang1993** [comment] 2016-01-09 04:07
addtion: It will happen only when lines are too long

**Comment by mnquintana** [comment] 2016-01-09 14:17
This looks like a duplicate of https://github.com/atom/atom/issues/979 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-09 14:17 UTC
