### ISSUE TITLE
[Feature request]: Auto 'find' highlighted/selected text

### ISSUE THREAD

**Issue by Shuudoushi** [atom/atom#8000] opened 2015-07-21 09:01 UTC
Just as the title suggest, using the 'find' feature to find and highlight/'box' other like mentions within the editor tab of selected text, but without opening the 'find' box/window. This type of functionality seems to be standard in most text editors these days, such as sublime text.

**Comment by mnquintana** [comment] 2015-07-21 11:59
This is a duplicate of https://github.com/atom/find-and-replace/issues/138 – please subscribe there for updates.

(Also, for future reference, Atom's find functionality is provided by [atom/find-and-replace](https://github.com/atom/find-and-replace), not atom/atom.)

**Closed by mnquintana** 2015-07-21 11:59 UTC

**Comment by mark-hahn** [comment] 2015-07-21 17:55
Check out the package `find-selection`.

**Comment by mark-hahn** [comment] 2015-07-21 17:56
The package `find-selection` offers a similar functionality.

**Comment by Shuudoushi** [comment] 2015-07-21 21:09
Thanks, @mark-hahn, I found highlight-selection and have been using that, it'll work fine till it's built into atom.
