### ISSUE TITLE
Uncaught Error: spawn /Users/bryant/Library/Application Support/com.github.atom.ShipIt/update.nTt...

### ISSUE THREAD

**Issue by blhagadorn** [atom/atom#9712] opened 2015-11-20 03:26 UTC
[Enter steps to reproduce below:]

1. Downloaded a new version of Atom 1.2.3
2. Already had an older version of Atom 1.2.0 with already open files (believe), kept on Dock
3. Opened a shell script in finder and chose open as Atom 1.2.3 instead of the usual.
4. Nothing but empty lines on the file, code appears for a second in all files in the directory (an Xcode project), got error

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/bryant/Library/Application Support/com.github.atom.ShipIt/update.nTt2juq/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/bryant/Library/Application Support/com.github.atom.ShipIt/update.nTt2juq/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/bryant/Library/Application Support/com.github.atom.ShipIt/update.nTt2juq/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/bryant/Library/Application Support/com.github.atom.ShipIt/update.nTt2juq/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/bryant/Library/Application Support/com.github.atom.ShipIt/update.nTt2juq/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/bryant/Library/Application Support/com.github.atom.ShipIt/update.nTt2juq/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-20 03:51
Duplicate of #9559 and #7399, please subscribe there for updates.

Also, could you please comment on #7399 with your reproduction steps?  Thanks!

**Closed by 50Wliu** 2015-11-20 03:51 UTC
