### ISSUE TITLE
General (UI) Instability in macOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by gskerry** [atom/atom#16178] opened 2017-11-13 20:05 UTC
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode
    * Followed all applicable steps in the debugging guide
    * Checked the FAQs on the message board for common solutions
    * Checked that your issue isn't already filed
    * Checked that there is not already an Atom package that provides the described functionality

### Description
Wondering if anyone else has reported. Very recent clean install of macOS (10.13), so a fairly clean system... Symptom(s) mostly around flickering and 'white-outs' in the UI (images attached). Also a couple instances where UI instability led to the app crashing. 

<img width="501" alt="1" src="https://user-images.githubusercontent.com/8867156/32712707-defb0146-c7fa-11e7-8205-7eac11c21540.png">

<img width="500" alt="2" src="https://user-images.githubusercontent.com/8867156/32712711-e332abc4-c7fa-11e7-860c-e111b694ad2c.png">

![3](https://user-images.githubusercontent.com/8867156/32712716-ea58a1a6-c7fa-11e7-8889-4282275d35b7.jpg)

<img width="500" alt="4" src="https://user-images.githubusercontent.com/8867156/32712717-ea72162c-c7fa-11e7-975e-cfb2555c1c5f.png">

![5](https://user-images.githubusercontent.com/8867156/32712718-ea882ca0-c7fa-11e7-93b5-363b597eaa04.jpg)

![6](https://user-images.githubusercontent.com/8867156/32712719-eaa0aef6-c7fa-11e7-96ce-7ec88d18a5cd.jpg)

### Steps to Reproduce
A bit difficult to pin down so far. Generally seems to be: 
*when resizing the window
*when app-switching back to Atom
*switching between files in a project

(Already performed a full uninstall (e.g. wiping ~/.atom and all macOS app directories) and clean reinstall of Atom. The last image above is immediately after reinstalling Atom.

**Reproduces how often:** 
Consistently (~occurence every 'session' on the app)

### Versions
1.22.0
macOS 10.13.1 (17B48)

**Comment by gskerry** [comment] 2017-11-13 20:06
Have moved to Atom/Atom
[#16178](https://github.com/atom/atom/issues/16178)
Sorry about that.

**Comment by acegfx** [comment] 2017-11-14 16:46
I'm currently having the same issue after upgrading to High Sierra (10.13.1).  Atom has not crashed, but currently experiencing the flickering "white-out" issues. 

Restarts seem to help, as well as limiting the amount of open projects, but the problem persists.

**Comment by acegfx** [comment] 2017-11-14 16:53
Follow up from my previous comments. Restarts only help sometimes, but switching files can enable the flickering.

![screen shot 2017-11-14 at 11 51 39 am](https://user-images.githubusercontent.com/20130278/32792806-59414da6-c932-11e7-9ed8-865cefa67b22.png)

This issue has made Atom unusable. Unable to work on my current projects at this current state. I need to find another editor.

**Comment by rsese** [comment] 2017-11-14 20:41
@gskerry @acegfx - did either of you run older versions of Atom on High Sierra that didn't have this issue?  Also, do you see the same issue with other Electron apps (e.g. Slack, VS Code).

**Comment by gskerry** [comment] 2017-11-14 21:02
@rsese I've only downloaded/installed the most current version of Atom (1.22.0) since updating to macOS 10.13. 

I do use Slack and have not experienced any similar issues.

**Comment by acegfx** [comment] 2017-11-14 21:20
@rsese I had the most recent version of Atom (1.22.0) installed before installing High Sierra.

Slack is experiencing some flickering issues, but never full white out issues.

VSCode, which I just started to use in the meantime, hasn't had any flickering issues.

**Comment by azachar** [comment] 2017-11-20 07:29
@rsese it seems to me that is related to Electron, I had the same issue with Slack, but it is working now, after upgrading it. So perhaps Atom needs to upgrade electron platform.

**Comment by dknell** [comment] 2017-11-22 03:23
I just did a fresh installation of OS X 10.13.1 and am having the same issue. I agree with the OP, this is completely unusable. Slack is noticeably more laggy than it was on 10.12.x, but it's not having the white-out issue. I have the latest version of Atom (1.22.1).

**Comment by dknell** [comment] 2017-11-22 14:50
This seems to happen only on external displays (when using the NVIDIA GeForce GT 750M card)

**Comment by capephotos** [comment] 2017-11-24 15:32
I am having the same issue. After restarting the computer I can use it for a while no problem but eventually it starts acting up and making the computer unusable.

Mid 2015 macbook pro 15"
NVIDIA GeForce GT 750M 2 GB
Intel Iris Pro 1536 MB
2.5 GHz Intel Core i7

HIgh sierra 10.13.1

**Comment by cleanenergyjoy** [comment] 2017-11-24 16:58
24 lis 2017 16:33 "Don Parkinson" <notifications@github.com> napisał(a):

**Comment by cleanenergyjoy** [comment] 2017-11-24 16:58
majorjammer830@gmail.com
24 lis 2017 16:33 "Don Parkinson" <notifications@github.com> napisał(a):

**Comment by jayhill90** [comment] 2017-11-24 22:24
I'm also having some big issues after updating to High Sierra today, frequently getting the "Application has not responded" error message previously reported in this thread.

**Comment by capephotos** [comment] 2017-11-25 19:00
I tried out vs code and was seeing the same issues.

**Comment by narko** [comment] 2017-11-27 21:21
Similar problem here. Atom is crashing high sierra and leaving the laptop completely frozen. Even restarting I had issues, i.e., the booting process had some issues (typical grey screen with the loading bar) and it took a loooong time to restart.

**Comment by viery365** [comment] 2017-12-09 19:19
Here too. Two days ago I've changed to High Sierra and suddenly: 

<img width="1438" alt="screen shot 2017-12-09 at 19 17 23" src="https://user-images.githubusercontent.com/20521892/33798726-d03b95a0-dd15-11e7-965f-83f0d7036b28.png">

**Comment by ioquatix** [comment] 2017-12-09 21:24
I feel like 12.13.2 is more stable, I've yet to reproduce the problem after updating, but I also have stopped using my Mac as much for development because it was getting so frustrating. I'll report back if I see further issues. I'm not convinced that it's fixed, but it's also not apparent that it's still broken.

**Comment by rsisto** [comment] 2017-12-15 14:27
Same problem here, thanks for the update @ioquatix , I'll try the update and see what happens...

**Comment by dknell** [comment] 2017-12-15 15:03
I opened a support case with Apple and their engineers are aware of the issue. They are supposedly working with NVIDIA to resolve the driver issue. They could not provide an estimate for when a solution would be available. In the meantime, I have downgraded back to Sierra, which works. My MBP is out of warranty, otherwise they would've replaced it.

Right now it's just a waiting game and the ball is in NVIDIA's court. 

If we all open support tickets with NVIDIA, maybe we could motivate them to prioritize the issue.

NVIDIA support:
800.797.6530
https://nvidia.custhelp.com/app/ask

**Comment by gregoryfoster** [comment] 2017-12-15 17:31
I've had no problems since I installed NVIDIA's High Sierra drivers for my GeForce GT 750M 2 GB card.  I found the drivers linked here:
http://hackintosher.com/guides/properly-install-nvidia-drivers-high-sierra-10-13/

This package also installs an "NVIDIA Driver Manager" preference pane and menu item enabling you to switch between the NVIDIA driver and the OS X default graphics driver.  You can configure an automatic check for updates to the NVIDIA driver, which triggered successfully when I upgraded to 10.13.2.

**Comment by kecinzer** [comment] 2017-12-21 08:10
dknell:
I have same issue with High Sierra and GeForce performace. But I still have my MacBook Pro in warranty. Do you think, that Apple service will replace it for me because of this bug?

**Comment by 50Wliu** [comment] 2017-12-21 15:30
It looks like Electron 1.7.10 "[f]ixed rendering issues with Nvidia GPU on High Sierra".  I don't know if this rendering issue and the one the release notes are referencing are the same one but we're investigating upgrading Electron in #16282.

**Comment by 50Wliu** [comment] 2018-01-03 23:21
We just merged the Electron upgrade.  Can anyone see if that helps by downloading this build? https://6395-3228505-gh.circle-artifacts.com/0/Users/distiller/atom/out/atom-mac.zip

**Comment by ioquatix** [comment] 2018-01-03 23:28
I've found the latest version of macOS a lot more stable.

**Comment by PierBover** [comment] 2018-01-29 17:47
I just moved High Sierra 10.3.3 on a brand new iMac and all the Electron apps I'm using (Atom, Slack, Postman) seem less performant than on my old MBP with El Capitan. Typing seems to lag a lot more which is specially bad on Atom. I've had to go back to Sublime Text for the time being...

**Comment by 50Wliu** [comment] 2018-01-29 21:37
@PierBover can you please follow the instructions in [my comment above](https://github.com/atom/atom/issues/16178#issuecomment-355155998) and see if that helps?

**Comment by PierBover** [comment] 2018-01-29 21:43
Yes @50Wliu there is an improvement. Typing is less laggy and scrolling is smoother.

**Comment by 50Wliu** [comment] 2018-01-29 21:49
Thank you for the quick response!  Would you say that the performance is acceptable, or is it still laggier than what you'd normally expect?

**Comment by PierBover** [comment] 2018-01-29 22:06
Yes I'd say it's acceptable.

**Comment by 50Wliu** [comment] 2018-01-29 22:28
🙇 In that case, I will be closing this issue.

**Closed by 50Wliu** 2018-01-29 22:28 UTC
Labels: electron, more-information-needed
