### ISSUE TITLE
Improve Atom Flight Manual: 3.3 Package: Word Count

### ISSUE THREAD

**Issue by dalinaum** [atom/atom#7716] opened 2015-07-05 04:23 UTC
Someone generate package as `wordcount`, his or her package will be shown as a deprecated package.

Because many names look like `lib/wordcount.coffee` and `keymaps/wordcount.cson`, many os use can name their packages `wordcount` and will get deprecated messages.

**Comment by lee-dohm** [comment] 2015-07-05 06:21
This is a duplicate of atom/docs#85. Please subscribe there for updates.

**Closed by lee-dohm** 2015-07-05 06:21 UTC
Labels: duplicate
