### ISSUE TITLE
Atom Crashes on Windows 10 Loading 1MB Log Files

### ISSUE THREAD

**Issue by WanderingKazuma** [atom/atom#14306] opened 2017-04-26 19:47 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    *[X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    *[X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    *[X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    *[X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    *[X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom slows down dramatically and eventually crashes. Tried safe-mode, and was able to reproduce this issue. Tried to clear saved state, and while that did solve the issue temporarily, it did come back. I only have two log files that I am working through, both are about 800kbs and 20k lines (not sure if loc is proper term here).

I have checked for updates after clearing saved state, and it states that 1.16.0 is the latest. Tried to install package-cop, but atom crashed before I even got to that.

### Steps to Reproduce

1. Load atom (various conditions: safe mode, clear saved state, etc)
2. Wait or load log files.
3. Wait for Microsoft to say that it is not responding

**Expected behavior:** Smooth operation and scrolling through the log files

**Actual behavior:** Scrolling stops at some point, and atom crashes

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

[operation_log.txt](https://github.com/atom/atom/files/959570/operation_log.txt)

**Comment by rsese** [comment] 2017-04-26 20:28
Does Atom crash only when you have those 2 log files open and works otherwise with other files or when no files are open?  Also, I'm guessing you can't but just to confirm, would you be able to share the log files so we can try them out?

Lastly, you mentioned how many lines are in each log file but can you also share how large the files are?

**Comment by rsese** [comment] 2017-04-26 20:29
Oh sorry, can you also start Atom like this and share any output you see when it crashes?

```
atom --safe -f
```

**Comment by Ben3eeE** [comment] 2017-04-27 10:14
@WanderingKazuma Can you also try to disable the `spell-check` package to see if that makes Atom faster? There is a performance issue with `spell-check` on Windows that can affect small files /cc: https://github.com/atom/spell-check/issues/190

**Comment by WanderingKazuma** [comment] 2017-04-27 15:01
Both log files are about 860 to 890 Kilobytes large, and no I can't share the log files. They are almost 85%-95% json structures that were printed into the log from an NLog enabled .NET application. 

Funny thing though. I disabled spell-check package, and noticed that Atom immediately went back to what I was expecting it to do, performing very well and fast/responsive. When I re-enabled the spell-check package, it seems like the act of disabling and re-enabling the package fixed whatever was causing the issue I was having. I'm now using atom without any crashes or slowdowns.

**Comment by rsese** [comment] 2017-04-27 18:06
I keep on forgetting about that spell-check issue, thanks @Ben3eeE :bow:

> When I re-enabled the spell-check package, it seems like the act of disabling and re-enabling the package fixed whatever was causing the issue I was having.

Hmmm, this seems odd, not sure how disabling and re-enabling spell-check would fix things?  I would think as described in that issue that you would have to spell-check disabled to avoid the problem.

In any case, since it sounds like things are working ok for you now and this seems to be a duplicate of https://github.com/atom/spell-check/issues/190, we'll go ahead and close this out @WanderingKazuma.

**Closed by rsese** 2017-04-27 18:06 UTC
Labels: crash, more-information-needed, windows
