### ISSUE TITLE
Command-E "Search Selection" is honored by Atom on OSX

### ISSUE THREAD

**Issue by groue** [atom/atom#8426] opened 2015-08-18 13:28 UTC
A very common scenario for text handling on OSX is the following:

- Select some text in App 1 using Command-E.
- Switch to App 2.
- Jump to next occurrence of the text using Command-G.

This scenario is *very* efficient, fast, and does not require any "panel" or "dialog" or any visible UI. It works with almost all apps on OSX, at least apps that are a good OSX citizen. Command-E, Command-Tab (switch), Command-G, and here is your string.

Atom is not a good citizen in this scenario.

It understands Command-E, but only within its own little environement: it does not inherit search strings from other apps, nor does it shares its own with other applications. It really should.

Atom 1.0.7, MacOS 10.10.5 (14F27).

**Comment by mnquintana** [comment] 2015-08-18 13:49
This looks like a duplicate of https://github.com/atom/atom/issues/4650 – please subscribe there for updates.

**Closed by mnquintana** 2015-08-18 13:49 UTC
