### ISSUE TITLE
Atom has trouble rendering files that are over 15k lines

### ISSUE THREAD

**Issue by belldandu** [atom/atom#8887] opened 2015-09-22 01:01 UTC
Atom will freeze in the editor area When loading files that have 15k lines or more. Rendering around that area will stop and will look like regular text.

**Comment by mnquintana** [comment] 2015-09-22 01:20
What version of Atom are you using? Can you reproduce this after quitting Atom completely and restarting it in safe mode? (`atom --safe`)

**Comment by kamijoutouma** [comment] 2015-09-22 11:55
atom 1.0.15

When i run it in safe mode it doesn't freeze but it is slow with rendering the huge amount of lines i have to wait about 10 seconds before the text becomes colored when i scroll straight to the bottom of the file.

**Comment by Ben3eeE** [comment] 2016-12-15 15:54
https://github.com/atom/atom/issues/8887

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/8864. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-15 15:54 UTC
Labels: more-information-needed
