### ISSUE TITLE
cmd+click multiple cursors not working

### ISSUE THREAD

**Issue by alvarosalgado** [atom/atom#20916] opened 2020-06-10 22:11 UTC
Hi,
My "cmd+click" multiple cursors functionality stopped working.
I tried disabling hyperclick inside atom-ide-ui, and also starting in safe mode. Nothing worked.
"cmd+d" and "ctrl+cmd+g" are still working.

Any clue?

**Comment by Atom-c** [comment] 2020-06-10 22:57
@alvarosalgado I was having the same issue and have a temporary workaround that brought functionality back in full for me 🙌 

In your Atom `config.cson` (Atom > Config...) (or search for Config in Command Palette):

Add this (if core > editor is already present, just add the last line under there):

```cson
  core:
    editor:
      multiCursorOnClick: true
```

I did some backwards digging from the file change (#20444) that added the setting for this
`atom.config.get('core.editor.multiCursorOnClick')`
seems to point to nesting in `core`, whereas nesting under just `editor` did not register. You can also test this in the dev tools console.

`atom.config.get('core.editor.multiCursorOnClick')`
vs
`atom.config.get('editor.multiCursorOnClick')`

I'm not sure if this is a local issue due to conflicts across specific packages or a more widespread issue due to improper `get()` path?

I am not incredibly familiar with Atom despite my name.

Please let me know if the above fix works for you @alvarosalgado @kitajchuk — I hope so! 

-----

Additionally the release [changelog](https://github.com/atom/atom/releases/tag/v1.48.0) for Atom 1.48.0 incorrectly links to a different change #20711; you should look at #20444:
> #20711 Update npm to 6.14.4 for Python 3 support
> #20711 Add setting to disable multi cursor on click

**Comment by Atom-c** [comment] 2020-06-10 23:00
@UziTech @lkashef  any thoughts on the above?

I believe this is a duplicate of issue #20911

**Comment by seanoquinn** [comment] 2020-06-11 02:06
This did not solve the issue for me.

**Comment by tommydunn** [comment] 2020-06-11 04:56
I ended up reverting back to [`1.47.0`](https://github.com/atom/atom/releases/tag/v1.47.0) while #20804 gets sorted. Thanks for figuring this out @UziTech

**Comment by softwarecreations** [comment] 2020-06-11 09:40
Confirming Ctrl Click for multi-cursor is broken in 1.48 on Linux.
Confirmed the issue in normal and safe mode 1.48 and 1.47.
Downgraded to 1.47 to be able to work.

**Comment by jinglesthula** [comment] 2020-06-11 15:51
Thanks @UziTech for the quick fix PR.  I use Atom, but am pretty unfamiliar w/ the development process.  Wondering out loud to any and all if there's a possibility for an automated test for this to prevent future regressions?

**Comment by UziTech** [comment] 2020-06-11 16:09
@jinglesthula There were tests written for this feature but in this case the feature and the tests used the wrong config setting to check if it was enabled. #20804 fixes the feature and the tests.

**Comment by alvarosalgado** [comment] 2020-06-11 17:18
> @alvarosalgado I was having the same issue and have a temporary workaround that brought functionality back in full for me 🙌
> 
> In your Atom `config.cson` (Atom > Config...) (or search for Config in Command Palette):
> 
> Add this (if core > editor is already present, just add the last line under there):
> 
> ```coffee
>   core:
>     editor:
>       multiCursorOnClick: true
> ```
> 
> I did some backwards digging from the file change (#20444) that added the setting for this
> `atom.config.get('core.editor.multiCursorOnClick')`
> seems to point to nesting in `core`, whereas nesting under just `editor` did not register. You can also test this in the dev tools console.
> 
> `atom.config.get('core.editor.multiCursorOnClick')`
> vs
> `atom.config.get('editor.multiCursorOnClick')`
> 
> I'm not sure if this is a local issue due to conflicts across specific packages or a more widespread issue due to improper `get()` path?
> 
> I am not incredibly familiar with Atom despite my name.
> 
> Please let me know if the above fix works for you @alvarosalgado @kitajchuk — I hope so!
> 
> Additionally the release [changelog](https://github.com/atom/atom/releases/tag/v1.48.0) for Atom 1.48.0 incorrectly links to a different change #20711; you should look at #20444:
> 
> > #20711 Update npm to 6.14.4 for Python 3 support
> > #20711 Add setting to disable multi cursor on click
@Atom-c it worked like a charm! Thank you!

**Comment by AlexNodex** [comment] 2020-06-12 13:49
Same issue...

Editing the config did not help... This is a massive regression for developers that use this functionality thousands of times a day :/

**Comment by UziTech** [comment] 2020-06-12 13:58
You can also open the console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>) and run `atom.config.set('core.editor.multiCursorOnClick', true);`

**Closed** 2020-06-12 15:49 UTC

**Comment by simonrepp** [comment] 2020-06-14 08:14
@AlexNodex It's easy to misplace the setting in `"*"` > `editor` instead of `"*"` > `core` > `editor`, and then it does not work - happened to me, happened to others  (see @seanoquinn's post above with screenshot explanation), I suspect that's what happened for you as well.

**Comment by isiahmeadows** [comment] 2020-06-17 05:47
On Windows 10, I'm impacted by this (Ctrl instead of Cmd) and setting `'*'.core.editor.multiCursorOnClick` to `true` did *not* work for me, but @Atom-c's [workaround](https://github.com/atom/atom/issues/20916#issuecomment-642309856) + reloading the tab worked. This was all reproduced in safe mode.

```
PS> atom --version

Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

**Comment by putude** [comment] 2020-06-21 07:57
> > @alvarosalgado I was having the same issue and have a temporary workaround that brought functionality back in full for me 🙌
> > In your Atom `config.cson` (Atom > Config...) (or search for Config in Command Palette):
> > Add this (if core > editor is already present, just add the last line under there):
> > ```coffee
> >   core:
> >     editor:
> >       multiCursorOnClick: true
> > ```
> > 
> > 
> > I did some backwards digging from the file change (#20444) that added the setting for this
> > `atom.config.get('core.editor.multiCursorOnClick')`
> > seems to point to nesting in `core`, whereas nesting under just `editor` did not register. You can also test this in the dev tools console.
> > `atom.config.get('core.editor.multiCursorOnClick')`
> > vs
> > `atom.config.get('editor.multiCursorOnClick')`
> > I'm not sure if this is a local issue due to conflicts across specific packages or a more widespread issue due to improper `get()` path?
> > I am not incredibly familiar with Atom despite my name.
> > Please let me know if the above fix works for you @alvarosalgado @kitajchuk — I hope so!
> > Additionally the release [changelog](https://github.com/atom/atom/releases/tag/v1.48.0) for Atom 1.48.0 incorrectly links to a different change #20711; you should look at #20444:
> > > #20711 Update npm to 6.14.4 for Python 3 support
> > > #20711 Add setting to disable multi cursor on click
> > > @Atom-c it worked like a charm! Thank you!

Thank you, its work for me. 
But I should use the combination CTRL+ALT + CLICK.

**Comment by isiahmeadows** [comment] 2020-06-22 20:47
@putude 

> But I should use the combination CTRL+ALT + CLICK.

It's possible you use an extension that rebinds it. I use Ctrl+Shift+click as I use Atom TypeScript.

**Comment by byronigoe** [comment] 2021-02-19 01:08
@isiahmeadows Thank you for this comment, as CTRL+Click does not work for me and neither the Keybinding Resolver nor the Atom TypeScript settings were any help in identifying why.
