### ISSUE TITLE
Character encoding detection fails for some text files

### ISSUE THREAD

**Issue by wbt** [atom/atom#18850] opened 2019-02-14 20:37 UTC
### Description
Atom fails to accurately detect character encoding in certain text files, and displays them with a space between each letter and a few unrecognized characters up front. 

### Steps to Reproduce
1. In Windows Powershell, execute a command with output redirected to a file.  Example: `man ls > lsExample.txt`
2. Open the file in Atom.

**Expected behavior:**
3. The text file displays the same readable way it shows in Notepad, but in Atom. 

![Notepad screenshot](https://user-images.githubusercontent.com/563406/52816044-4b566600-306e-11e9-8f3f-736840f842bc.png)

**Actual behavior:**
Atom shows a first line containing two characters each shown as question marks in diamonds, not visible in Notepad, and every character after that has an extra space preceding it.

![Atom Screenshot](https://user-images.githubusercontent.com/563406/52815995-282bb680-306e-11e9-91ac-ff48968bfa91.png)

**Reproduces how often:** 
100%, even in Safe mode.  
Does not reproduce if using Windows Command Prompt (e.g. `help help > help.txt`) instead of PowerShell.

### Versions
Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
NPM    : 6.5.0
OS   : Windows 10 Pro

### Additional Information
Channeling the output of a running script [to a file](https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file), and then opening that log to inspect what happened, seems like a reasonably common use case in programming activities Atom is intended to support.

**Comment by lee-dohm** [comment] 2019-02-14 21:08
Thanks for reaching out!

We noticed that this is a duplicate of https://github.com/atom/encoding-selector/issues/18. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2019-02-14 21:08 UTC

**Comment by wbt** [comment] 2019-02-14 21:44
Apologies for the dupe; I did search but apparently not the right project.
