### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 5961Error: Cannot ca...

### ISSUE THREAD

**Issue by shingoteshima** [atom/atom#17523] opened 2018-06-16 18:16 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 5961
Error: Cannot call function 'getPosition' on missing remote object 5961
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 5961
Error: Cannot call function 'getPosition' on missing remote object 5961
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:191:32)
```

### Commands

```
     -6:48.3.0 core:paste (input.hidden-input)
     -6:48 core:save (input.hidden-input)
     -6:43 emmet:insert-formatted-line-break-only (input.hidden-input)
     -6:43 editor:newline (input.hidden-input)
     -6:42.3.0 core:paste (input.hidden-input)
     -6:41.9.0 core:save (input.hidden-input)
     -5:56.6.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -5:45.6.0 core:confirm (input.hidden-input)
     -4:58.8.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -4:55.6.0 core:confirm (input.hidden-input)
     -3:34.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:33.2.0 emmet:toggle-comment (input.hidden-input)
     -3:33.2.0 editor:toggle-line-comments (input.hidden-input)
     -3:32.8.0 core:save (input.hidden-input)
     -3:18.9.0 core:undo (input.hidden-input)
     -3:18.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-clock 0.1.16 
atom-runner 2.7.1 
auto-update-packages 1.0.1 
autocomplete-paths 2.12.2 
autocomplete-sql 0.5.0 
busy-signal 1.4.3 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.21 
goto-definition 1.3.4 
highlight-selected 0.13.1 
intentions 1.1.5 
language-haml 0.31.1 
language-rspec 0.11.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
project-manager 3.3.6 
rails-i18n-autocomplete 0.4.0 
rails-snippets 2.19.0 
rails-transporter 1.7.1 
rspec 0.4.0 
ruby-block 0.3.6 
show-ideographic-space 1.0.2 
split-diff 1.5.2 
teletype 0.13.3 
```

**Comment by rsese** [comment] 2018-06-18 17:05
Thanks for the report!

This looks like a duplicate of #16630 so you can subscribe there for updates if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-06-18 17:05 UTC
