### ISSUE TITLE
Files uneditable on Atom 1.17 beta

### ISSUE THREAD

**Issue by ozo2003** [atom/atom#14216] opened 2017-04-15 12:47 UTC
### Description

Files are uneditable in 1.17.0-beta2 or 1.17.0-beta1 or 1.17.0-beta0. It looks like atom focuses tree-view instead of editor and makes editing impossible. pressing backspace or delete asks if i want to delete file i'm trying to edit and doesn't delete character in editor.

Same behaviour in safe mode.  
Doesn't happen in 1.16.0-beta0

### Steps to Reproduce

1. Open project in atom
2. Try to edit file

**Expected behavior:** Editing file

**Actual behavior:** Unable to edit file, delete button press asks if i want to delete file

**Reproduces how often:** Every time

### Versions

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.7.4

Atom    : 1.17.0-beta2
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

Linux puddle 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Installed from .deb package

**Comment by 50Wliu** [comment] 2017-04-17 20:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14176. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-04-17 20:29 UTC
