### ISSUE TITLE
Fresh install on arch, running atom makes it crash

### ISSUE THREAD

**Issue by tirrorex** [atom/atom#11322] opened 2016-03-31 01:30 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I installed atom on antergos (which is arch linux) following instruction on github.
After the installation i runned atom, it wasn't possible to run it using atom i had to use atom-beta.
The UI appers and the program instantly crash.
I would've try to downgrade freetype2 as some people suggested on issue #11198  but i don't have the apm command, have to use apm-beta.

Return is : 
apm-beta install freetype2@2.6.2-1
Installing freetype2@2.6.2-1 to /home/zipeldiablo/.atom/packages ✗
Request for package information failed: Not Found

### Steps to Reproduce

1. sudo pacman -S --needed gconf base-devel git nodejs npm libgnome-keyring python2
2. export PYTHON=/usr/bin/python2 (missed this step)
3. git clone https://github.com/atom/atom
4. cd atom
5. git fetch -p
6. git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
7. script/build
8 . sudo script/grunt install
9. atom-beta (to launch it, will crash)
9. apm-beta install freetype2@2.6.2-1 (to try to downgrade the package)
also tried : apm-beta downgrading package freetype2 (2.6.3-1 => 2.6.2-1)
zsh: parse error near `)'

**Expected behavior:** [What you expected to happen]

launching atom with the atom command, program will load successfully
**Actual behavior:** [What actually happened]

Have to launch program using atom-beta, crash on boot

### Versions

atom-beta -version
Atom    : 1.7.0-beta4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by 50Wliu** [comment] 2016-03-31 01:37
freetype is not an Atom package, so `apm` won't work on it - try following [this comment](https://github.com/atom/atom/issues/11198#issuecomment-201848696).  As this is a duplicate of #11198 I'm closing this issue.

**Closed by 50Wliu** 2016-03-31 01:37 UTC

**Comment by tirrorex** [comment] 2016-03-31 01:54
Fine by me.
Would just someone care to explain with apm and atom are installed in beta version while following the install instructions?

**Comment by noraj1337** [comment] 2017-10-16 21:49
@tirrorex Beta software are often unstable. If you run a fresh antergos (arch based) you should be able to run `pacman -S atom` ([atom](https://www.archlinux.org/packages/community/x86_64/atom/)) (apm is a dependency). You also tell you missed `export PYTHON=/usr/bin/python2`.

> After the installation i runned atom, it wasn't possible to run it using atom i had to use atom-beta.
The UI appers and the program instantly crash.

So which error message did you get? Why normal atom can't run? What happened?

I don't intend to be rude but you didn't use the official package from your disto or neither built atom by strictly respecting the build  process. The issue board is here in order to report bugs no to get help in a personnal use case.

Don't ask me question about atom I just came here randomly from google but it seemed to be that it was legit to close the issue.

**Comment by tirrorex** [comment] 2017-10-17 08:02
@noraj1337 dude it's been one year and a half, nobody cares.
