### ISSUE TITLE
SASS/SCSS autocomplete doesn't work properly

### ISSUE THREAD

**Issue by AmirFawzy** [atom/atom#16283] opened 2017-11-28 05:59 UTC
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
when i start to write variable or include mixin in atom suggestions list(autocomplete) doesn't work properly.
![2017-11-28_7-33-01](https://user-images.githubusercontent.com/19322308/33304055-386766c8-d40f-11e7-93c3-eeb0c8659612.png)
suggestion list(autocomplete) doesn't show any of variables should show in list to for autocomplete that happening with include too when i trying to use mixins.

### Steps to Reproduce

1. write $ or @include
2. autocomplete not work properly.

**Expected behavior:** when i write "$" or "@include" suggestion list show with my correct variables or mixins.

**Actual behavior:** suggestion list(autocomplete list) doesn't show project variables or mixins. 

**Reproduces how often:** all the time

### Versions

OS windows 10 pro v.16299 x64
Atom    : 1.22.1
Electron: 1.6.15
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
git 2.13.3.windows.1

### Additional Information

this problem start to happen after update atom to latest version.

**Comment by rsese** [comment] 2017-11-28 18:41
Hey @AmirFawzy - I'll close this as a duplicate of your original issue https://github.com/atom/atom/issues/16158.   The fix will be available in an upcoming release as mentioned in the comments https://github.com/atom/atom/issues/16158#issuecomment-347021959.

**Closed by rsese** 2017-11-28 18:41 UTC
