### ISSUE TITLE
[1.48.0] Don't work multi-cursor

### ISSUE THREAD

**Issue by duboloms** [atom/atom#20935] opened 2020-06-16 10:03 UTC
**Multi-cursor don't work in editor, although this param is on in settings:**

![image](https://user-images.githubusercontent.com/54753636/84760167-50b02180-afd0-11ea-917b-17569e830f3c.png)

I've turned it on and off a 100 times, but it didn't have any effect.

I looked at what is happening in atom keymap, and keybinding resolver.
In keymap i didn't find mention about **_ctrl-click_**. In keybinding resolver, also.

What i can do with this?

**Comment by zanna-37** [comment] 2020-06-16 10:12
duplicate of #20803 should be fixed in #20804

**Closed** 2020-06-16 10:18 UTC

**Comment by putude** [comment] 2020-06-17 08:13
Yes, doesn't work on version 1.48.0 (fresh installed, no package).
I back to 1.47.0
OS: Windows 10
