### ISSUE TITLE
Cmd + shift + z does not work on Dvorak keyboards (cmd + y does)

### ISSUE THREAD

**Issue by godspeedelbow** [atom/atom#10744] opened 2016-02-09 19:23 UTC
**Steps:**

Normal (US) keyboard:
- set keyboard layout to **US**
- start `atom --safe`
- new file
- type something
- `cmd + z` undoes
- `cmd + shift + z` redoes 

Dvorak keyboard:
- set keyboard layout to **Dvorak**
- start `atom --safe`
- new file
- type something
- `cmd + z` undoes
- `cmd + shift + z` **does not redo**
- `cmd + y` does redo

**Notes:**

- Running `1.4.3` on `El Capitan`
- I've had this problem since I started using Atom, two days ago
- This is first and only keybinding issue I've ever encountered in using Dvorak for the last 6 years on Mac.

Anything I can do to provide more info?

**Comment by Beatusvir** [comment] 2016-03-02 19:16
@godspeedelbow Have you tried using [Keyboard-Localization](https://atom.io/packages/keyboard-localization)?

**Comment by lee-dohm** [comment] 2016-03-03 04:51
This is a duplicate of https://github.com/atom/atom-keymap/issues/37. Please subscribe there for updates.

**Closed by lee-dohm** 2016-03-03 04:51 UTC

**Comment by pirelenito** [comment] 2017-05-03 14:08
Hi @lee-dohm, I saw that both this issue and atom/atom-keymap#37 were closed, but I also use the Dvorak keyboard and I'm having the same issue.

Should I open another issue? Should we re-open this?

@godspeedelbow, are you still having this issue as well?

Cheers,

**Comment by Ben3eeE** [comment] 2017-05-03 14:51
@pirelenito Please open a new issue over at the https://github.com/atom/atom-keymap repository. Make sure you fill out the entire issue template when you open the issue.  Feel free to @mention me when you have opened it and I can take a look.

**Comment by godspeedelbow** [comment] 2017-05-07 13:15
Nope @pirelenito, problem solved by switching back to Qwerty. I even wrote something about it :)

https://github.com/godspeedelbow/writing/blob/master/dvorak.md
