### ISSUE TITLE
Can't delet file & folder from project folder

### ISSUE THREAD

**Issue by xjjrain2012** [atom/atom#10668] opened 2016-02-03 07:33 UTC
when i delete file, editor show a dialog, when i click 'Move to trash', it do nothing.

**Comment by sudoankit** [comment] 2016-02-03 12:08
It works fine on OS X El Capitan, 10.11.2.
Which OS, are you using, and what do you mean by "it does nothing"?

When you click "Move to trash" on the dialog box, where does the file go?
Does it stay in the working directory/folder or get's deleted, but still shows up on Atom?

**Comment by 50Wliu** [comment] 2016-02-03 13:31
This is most likely a duplicate of atom/tree-view#666 - please subscribe there for updates.

**Closed by 50Wliu** 2016-02-03 13:31 UTC
