### ISSUE TITLE
Running Atom inside a browser

### ISSUE THREAD

**Issue by ph7vc** [atom/atom#7779] opened 2015-07-08 01:33 UTC
Since Atom is based on the web stack; is there a way it can be run inside a browser tab?

I am on a Chromebook and would love to be able to use Atom in a tab (or in a standalone window if possible)

Crouton is a solution to boot into a more traditional Linux environment; but it's really not an elegant solution. 

Thanks!

**Comment by thomasjo** [comment] 2015-07-08 05:23
Duplicate of https://github.com/atom/atom/issues/3088.

**Closed by thomasjo** 2015-07-08 05:23 UTC
