### ISSUE TITLE
Unexpected behavior of tab length

### ISSUE THREAD

**Issue by KenetJervet** [atom/atom#12019] opened 2016-06-21 18:04 UTC
Atom 1.8.

If leaving the global tab length (i.e. in Core Settings, defaults to 2) empty. I can override its value in specific language packages and it works well.

If set the global tab length to some other value (say 4), I can set the specific language tab length to anything but 2. (The text placeholder says 'Default: 2', while I type in '2' it wipes it out and fills in 4 automatically). If I leave it empty the actual tab length follows the global settings (i.e. 4). By all means I can't set it to 2.

**Comment by lee-dohm** [comment] 2016-06-29 23:43
This is a duplicate of https://github.com/atom/settings-view/issues/774. You may want to subscribe there for updates.

Thanks for reporting!

**Closed by lee-dohm** 2016-06-29 23:43 UTC
