### ISSUE TITLE
Atom freezes (windows10 - 64bit)

### ISSUE THREAD

**Issue by EducatedMF** [atom/atom#13413] opened 2016-12-09 09:38 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]
When I start Atom the editor freezes. I have tried re-installing but the bug persists.
### Steps to Reproduce

1. [First Step]
Just open Atom and it freezes and then a window pops up saying it is not responding.
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Not freeze.

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Ben3eeE** [comment] 2016-12-09 09:46
To fix this try to start atom using `atom --clear-window-state`.

**Comment by Ben3eeE** [comment] 2016-12-09 09:46
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12983. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-09 09:46 UTC
