### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, lstat 'M:/'

### ISSUE THREAD

**Issue by SapphireSunbeam** [atom/atom#17522] opened 2018-06-16 12:28 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, lstat 'M:\'

```
At fs.js:961

Error: UNKNOWN: unknown error, lstat 'M:\'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at start (fs.js:1614:10)
    at Proxy.realpathSync (fs.js:1602:3)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at atom.project.getPaths.map (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:73)
    at Array.map (native)
    at Object.startTask (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:56)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/fuzzy-finder/lib/main.js:129:43)
    at get_process.nextTick (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/fuzzy-finder/lib/main.js:31:45)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
city-lights-syntax 1.1.8 
color-picker 2.3.0 
css-color-name 0.4.0 
emmet 2.4.3 
file-icons 2.1.21 
indent-guide-improved 1.4.13 
pigments 0.40.2 
teletype 0.13.3 
```

**Comment by rsese** [comment] 2018-06-18 17:00
Thanks for the report!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/274. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-06-18 17:00 UTC
