### ISSUE TITLE
Uncaught Error: spawn /Users/emma/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents...

### ISSUE THREAD

**Issue by emmabeynon** [atom/atom#10822] opened 2016-02-15 08:58 UTC
[Enter steps to reproduce below:]

1. Open Atom
2. Command + Shift + O to open a project folder.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/emma/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/emma/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/emma/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/emma/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (/Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (/Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:15:15)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:170:22)
    at /Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at /Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:869:41
    at EventEmitter.<anonymous> (/Users/emma/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -3:36.7.0 core:close (atom-text-editor.editor.is-focused)
     -3:24.6.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -0:13.7.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "script",
      "git-plus",
      "about",
      "package-cop",
      "linter-jshint"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joshaber** [comment] 2016-02-15 15:46
This looks like a duplicate of #10774. Feel free to subscribe there for updates!

**Closed by joshaber** 2016-02-15 15:46 UTC
