### ISSUE TITLE
Uncaught Error: Tried to unload active package 'hyperclick'

### ISSUE THREAD

**Issue by pritishyuvraj** [atom/atom#18486] opened 2018-11-23 21:54 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Ubuntu 18.04.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'hyperclick'

```
At /snap/atom/206/usr/share/atom/resources/app/static/<embedded>:11

Error: Tried to unload active package 'hyperclick'
    at PackageManager.unloadPackage (/snap/atom/206/usr/share/atom/resources/app/static/<embedded>:11:378800)
    at PackageManager.t.exports.PackageManager.unload (/snap/atom/206/usr/share/atom/resources/app/static/<embedded>:11:912535)
    at PackageManager.t.exports.PackageManager.install (/snap/atom/206/usr/share/atom/resources/app/static/<embedded>:11:912768)
    at PackageCard.install (/snap/atom/206/usr/share/atom/resources/app/static/<embedded>:14:2941139)
    at HTMLButtonElement.installButtonClickHandler (/snap/atom/206/usr/share/atom/resources/app/static/<embedded>:14:2927461)
```

### Commands

```
     -1:07.6.0 github:toggle-git-tab (atom-pane.pane.active)
     -0:42.2.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
nuclide 0.366.0 
```

**Comment by rsese** [comment] 2018-11-27 03:51
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16873 so you can subscribe there for updates if you'd like.  If you have steps to reproduce or any other additional details, please let us know in https://github.com/atom/atom/issues/16873.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-27 03:51 UTC
