### ISSUE TITLE
Changed file indicator is not working properly with multiple project folders.

### ISSUE THREAD

**Issue by mattcollier** [atom/atom#12341] opened 2016-08-05 17:12 UTC
### Description

When working with one project folder (git repo) with changed files, the changed files are properly indicated in yellow and green in the project folders list.

When a second project folder(a separate git repo) is added, the colored file indicators stop working.

Video: https://drive.google.com/open?id=0B9zauMftfHD5cVNnSnliRWpNZW8

### Steps to Reproduce

1. Add a git repo as a project folder.
2. Change files in the project so that one or more files are indicated as changed (yellow) in the project list.
3. Add another project folder corresponding to a different git repo.

**Expected behavior:** The changed file indicators should continue to work properly.

**Actual behavior:** Changed files are no longer shown in yellow/green.

### Versions
I'm using 1.9.4 now, I believe I started seeing this with the 1.9.0 release.

**Comment by 50Wliu** [comment] 2016-08-05 19:17
This is a duplicate of atom/tree-view#906 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-05 19:17 UTC
