### ISSUE TITLE
 Can't switch to other tabs when diff of a file is open

### ISSUE THREAD

**Issue by krrishh-org** [atom/atom#17376] opened 2018-05-21 11:45 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Can't switch to other tabs when git diff tab is open. If I try to switch to another tab, it switches back automatically to the diff tab.

### Steps to Reproduce

1. Open a git version controlled project
1.2. Open a couple of editor tabs to test the functionality
2. Open and make changes to a file and save it
3. It should show up in the git pane as modified (unstaged section)
4. Click on the file to open diff
5. Try to switch to some other tab that's already open
6. It switches back to the diff tab
7. Try to open file using the `<>` button in the diff tab
8. It switches back to the diff tab

**Expected behavior:** [What you expect to happen]
It should allow the user to switch to any tab he wants.
**Actual behavior:** [What actually happens]
 It switches back to the diff tab
**Reproduces how often:** [What percentage of the time does it reproduce?]
Always (100%), Safe-mode (100%)
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.28.0-beta0
Electron: 2.0.0
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0-beta0
python 2.7.15rc1
git 2.17.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Ben3eeE** [comment] 2018-05-21 11:51
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/1444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-05-21 11:51 UTC
