### ISSUE TITLE
Unnecessary trailing separator in contextual menu

### ISSUE THREAD

**Issue by mquandalle** [atom/atom#10911] opened 2016-02-20 00:30 UTC
The contextual menu of the main editor view on Linux/Ubuntu contains an unnecessary separator at the end of the list items as outlined by the following red arrow:

![Unnecessary trailing separator](https://cloud.githubusercontent.com/assets/1730702/13192891/13120b90-d771-11e5-9c05-4134fabe57e3.png)

This bar is not present in others menu so it would be better to remove it here for consistency.

On the implementation side, I imagine the drawer could merge two consecutive separators and remove a separator on the first or the last position, ie removing separators that define empty sections.

**Comment by 50Wliu** [comment] 2016-02-20 00:44
This is a duplicate of #5390 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-20 00:44 UTC
