### ISSUE TITLE
UI Scaling for High DPI Displays?

### ISSUE THREAD

**Issue by Zane-** [atom/atom#7425] opened 2015-06-25 22:53 UTC
Here's what atom looks like on my Chromebook Pixel (2015) - running trusty Ubuntu / Gnome. 
It has a DPI of 239.
![screenshot from 2015-06-25 18 48 39](https://cloud.githubusercontent.com/assets/6345012/8367395/80fe2052-1b6b-11e5-8f7a-8263ee72b7d8.png)

Is there any way to fix this via internal settings?

**Comment by mnquintana** [comment] 2015-06-25 22:54
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/3826 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-25 22:55 UTC
