### ISSUE TITLE
Spell Checker

### ISSUE THREAD

**Issue by akshar-patel** [atom/atom#11440] opened 2016-04-13 05:16 UTC
Selecting Correct Spellings option for correcting spellings is time-consuming. Two or three corrected spelling suggestions should be available in context menu itself and give the option to see more suggestions if required.

![menu_003](https://cloud.githubusercontent.com/assets/18311126/14483443/b7b093ac-0164-11e6-9c7e-9746155c81e3.png)

**Comment by 50Wliu** [comment] 2016-04-13 14:35
This is a duplicate of atom/spell-check#54 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-13 14:35 UTC
