### ISSUE TITLE
Left side directory display wrong 

### ISSUE THREAD

**Issue by Robert-Rino** [atom/atom#5918] opened 2015-03-10 09:59 UTC
![image](https://cloud.githubusercontent.com/assets/10182040/6572606/64ff26ce-c74e-11e4-92bf-f18e4b74f0f8.png)

As the snapshot sometime my atom directory will display weird ,it seems that some text are show duplicately and overlapped.

Restart the program will fix the problem temporary  .

**Comment by 50Wliu** [comment] 2015-03-10 15:23
Duplicate of #4924, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-10 15:23 UTC
