### ISSUE TITLE
Uncaught Error: spawn gofmt ENOENT

### ISSUE THREAD

**Issue by laodao1990** [atom/atom#5080] opened 2015-01-15 16:00 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn gofmt ENOENT

```
At events.js:85

Error: spawn gofmt ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
  2x -4:34.2 core:save (input.hidden-input)
  3x -3:03.9 core:backspace (input.hidden-input)
  2x -3:02.5 core:save (input.hidden-input)
     -2:40.0 core:confirm (input.hidden-input)
  8x -2:21.9 core:backspace (input.hidden-input)
     -2:19.8 core:confirm (input.hidden-input)
  2x -1:19.6 core:backspace (input.hidden-input)
     -1:18.0 core:confirm (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
go-format, v1.0.7
go-plus, v3.0.13
gofmt, v0.2.0
linter-golint, v0.2.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-01-15 16:20
Looks like a duplicate of https://github.com/atom/atom/issues/4763.

**Closed by izuzak** 2015-01-15 16:20 UTC
