### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by Turecky** [atom/atom#12776] opened 2016-09-26 06:54 UTC
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:178:13)
    at undefined.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:112:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:636:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:670:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app.asar/src/window-event-handler.js:182:35)
    at /usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61

**Comment by thomasjo** [comment] 2016-09-26 08:19
Duplicate of #11692.

**Closed by thomasjo** 2016-09-26 08:19 UTC
