### ISSUE TITLE
If line number is a multiple of 6 or line number is 17, the tag will not show the match underline.

### ISSUE THREAD

**Issue by yubaoquan** [atom/atom#15355] opened 2017-08-17 06:26 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
[**In normal mode**] If line number mode 6 equals 0 or line number is 17, click on a tag, the highlighted underline indicating match tag will not show.

[**In safe mode**] If line number is 17, click on a tag, the highlighted underline indicating match tag will not show.

### Steps to Reproduce

1. Create an html file.
2. Input 25 lines of `<div></div>`
3. Click div tag on each line.

```
<div></div>
<div></div>
<div></div>
<div></div>
<div></div>
<div>not match</div>
<div></div>
<div></div>
<div></div>
<div></div>
<div></div>
<div>not match</div>
<div></div>
<div></div>
<div></div>
<div></div>
<div>not match<div>
<div>not match</div>
<div></div>
<div></div>
<div></div>
<div></div>
<div></div>
<div>not match</div>
<div></div>
<div></div>
<div></div>

```

![match](https://user-images.githubusercontent.com/2340296/29398399-11d9efac-8357-11e7-9cdc-afe566ebd51b.gif)

**Expected behavior:** Every line will show the underline of matched close tag.
**Actual behavior:** Line with number mode 6 equals 0 will not show the underline.
**Reproduces how often:** 100%

### Versions

Atom    : 1.20.0-beta3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0

OS: Mac Sierra 10.12.6

**Comment by Ben3eeE** [comment] 2017-08-17 08:02
Line 17 in your example does not have an ending div tag. It has two starting div tags.

Since the other issue does not reproduce in safe mode I will close this.

**Closed by Ben3eeE** 2017-08-17 08:02 UTC
Labels: invalid

**Comment by yubaoquan** [comment] 2017-08-17 09:50
https://github.com/jesseweed/seti-syntax/issues/157
