### ISSUE TITLE
Uncaught Error: Tried to unload active package 'language-swift'

### ISSUE THREAD

**Issue by JarekMaz** [atom/atom#16894] opened 2018-03-06 17:58 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'language-swift'

```
At /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:630

Error: Tried to unload active package 'language-swift'
    at PackageManager.unloadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.unload (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:502:36)
    at PackageManager.module.exports.PackageManager.install (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:512:18)
    at PackageCard.install (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:824:33)
    at HTMLButtonElement.installButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:302:22)
```

### Commands

```
 13x -4:24.6.0 core:move-left (input.hidden-input)
 29x -4:21.6.0 core:select-left (input.hidden-input)
     -4:18.1.0 core:backspace (input.hidden-input)
     -4:17.3.0 core:confirm (input.hidden-input)
     -2:25.8.0 core:paste (input.hidden-input)
     -2:24.3.0 core:confirm (input.hidden-input)
     -2:02.9.0 core:paste (input.hidden-input)
     -2:01.6.0 core:confirm (input.hidden-input)
     -1:31.7.0 core:paste (input.hidden-input)
     -1:30.1.0 core:backspace (input.hidden-input)
     -1:29.6.0 core:confirm (input.hidden-input)
     -0:57.3.0 core:paste (input.hidden-input)
     -0:55.9.0 core:backspace (input.hidden-input)
     -0:55.1.0 core:confirm (input.hidden-input)
     -0:26 core:paste (input.hidden-input)
     -0:24.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.32.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
language-swift 0.5.0 
linter 2.2.0 
linter-swiftlint 1.2.2 
linter-ui-default 1.7.1 
sort-lines 0.18.0 
```

**Comment by rsese** [comment] 2018-03-06 22:24
Thanks for contributing!

We noticed that this looks like a duplicate of #16873 so you can subscribe there for updates if you'd like.  If you have steps to reproduce or any more details that might be helpful, please let us know in #16873.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-06 22:24 UTC
