### ISSUE TITLE
Permissions/lock issue when changing git branch (Windows)

### ISSUE THREAD

**Issue by philomory** [atom/atom#18385] opened 2018-11-01 23:45 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When switching between git branches either via Atom or via `git checkout`, Atom appears to holds open file handles (or otherwise interact with the filesystem) in ways that cause further checkouts to fail. Whether the error occurs appears to be sensitive to the exact state of the UI when attempting to switch branches.

### Steps to Reproduce

1. `git clone https://github.com/philomory/atom-bug-reproduction`
2. `cd atom-bug-reproduction`
3. `git checkout reproduce-bug`
4. `atom .`
5. In the project sidebar, click to expand the 'bar' folder
6. Either:
    - `git checkout master` OR
    - Switch to 'master' branch from branch-switcher UI in Atom status bar
7. Observe that the 'bar' folder is still visible in the project pane, though it is not present in the 'master' branch. Do not click on it or otherwise interact with it at this stage.
8. Either:
    - `git checkout reproduce-bug` OR
    - Switch to the 'reproduce-bug' branch using the branch-switcher UI
9. Observe the message: `error: cannot stat 'bar': Permission denied`
10. In the project sidebar, collapse and re-expand project root folder
11. Observe that the 'bar' folder is no longer displayed.
12. Either:
      - `git checkout reproduce-bug` OR
      - Switch to the 'reproduce-bug' branch using the branch-switcher UI
13. Observe that you are able to successfully switch branches.

Small variations can additionally trigger the bug, for example, if you open `bar/baz.txt` instead of merely giving focus to `bar/`, the same general behavior is observed. Note that even in this case, `bar/baz.txt` disappears from the Project view immediately upon changing to the master branch; only `bar/` itself overstays its welcome.

**Expected behavior:** Atom should correctly refresh the project view when switching branches; or, at least, a stale project view should not hold open file handles that prevent further branch changes from succeeding.

**Actual behavior:** Atom appears to keep a handle to the `bar/` folder open even after that folder disappears.

**Reproduces how often:** With this sequence of steps, I've been able to reproduce it 100% of the time.

### Versions
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python
git 2.17.1.windows.2
visual studio

Windows 10 Pro, Version 1803, Build 17134.345

### Additional Information

This appears to be similar in some ways to #17013 and #17260, however, the presence or absence of `%userprofile%\.atom\recovery\` doesn't seem to have any impact on this issue, whereas it was very relevant in those issues. Thus, I suspect there is something different going on here.

**Comment by rsese** [comment] 2018-11-02 21:05
Thanks for contributing and for the detailed writeup!  Confirming I can reproduce with 1.32.1 on Windows 10.  However, because this only reproduces on Windows and involves expanding a directory in the tree view, I think this is a duplicate of https://github.com/atom/atom/issues/3365.

I'll tentatively close as in favor of that issue but let me know if you think I'm misunderstanding anything.

**Closed by rsese** 2018-11-02 21:05 UTC
