### ISSUE TITLE
Unfocused Password For Protected Files

### ISSUE THREAD

**Issue by bobrocke** [atom/atom#4822] opened 2015-01-01 16:59 UTC
When saving a protected file, such as http-vhosts.conf, Atom displays an authentication dialog. But the password field is unfocused requiring the user to click on the dialog and the field. It would be much more convenient of Atom would focus on that password field automatically.

**Comment by kevinsawicki** [comment] 2015-01-05 18:05
I believe this is a duplicate of https://github.com/atom/atom/issues/2862

**Closed by kevinsawicki** 2015-01-05 18:05 UTC
Labels: enhancement
