### ISSUE TITLE
Uncaught Error: /usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Re...

### ISSUE THREAD

**Issue by nagendras176** [atom/atom#22115] opened 2021-04-02 12:26 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: /usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node: cannot open shared object file: No such file or directory

```
At electron/js2c/asar.js:138

Error: /usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node: cannot open shared object file: No such file or directory
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695477)
    at get_KeyboardLayoutManager (/usr/share/atom/resources/app/static/<embedded>:14:2715396)
    at get_manager (/usr/share/atom/resources/app/static/<embedded>:14:2715498)
    at Object.getCurrentKeyboardLayout (/usr/share/atom/resources/app/static/<embedded>:14:2715624)
    at e.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:14:1047825)
    at KeymapManager.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1228394)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226379)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284820)
```

### Commands

```
     -1:42.8.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:37.9.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
     -1:13.2.0 pane:close (span.name.icon.icon-file-directory)
     -1:06.8.0 pane:reopen-closed-item (li.tab.sortable.active.right-clicked)
     -0:32.2.0 editor:select-line (atom-pane.pane)
  8x -0:23.5.0 tree-view:toggle-focus (atom-pane.pane)
```

### Non-Core Packages

```
busy-signal 2.0.1 
hyperclick 0.1.5 
ide-python 1.8.0 
intentions 1.1.5 
linter 3.1.1 
linter-ui-default 2.1.4 
project-manager 3.3.8 
you-complete-me 0.8.1 
```

**Comment by darangi** [comment] 2021-08-23 07:49
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2021-08-23 07:49 UTC
