### ISSUE TITLE
Why doesn't atom delete files?

### ISSUE THREAD

**Issue by xDinomode** [atom/atom#10402] opened 2016-01-13 19:07 UTC
Every time I need to delete a file I have to use a terminal. I right click on a file > delete > "Are you sure you want to delete the selected item" > move to trash... nothing.

**Comment by 50Wliu** [comment] 2016-01-13 20:34
@xDinomode what OS are you using, and what Atom version?

**Comment by xDinomode** [comment] 2016-01-14 00:03
@50Wliu Windows7 and 1.3.3

**Comment by 50Wliu** [comment] 2016-01-14 00:50
Ok.  In that case this is a duplicate of atom/tree-view#666.  I'm working on a fix for it.

**Closed by 50Wliu** 2016-01-14 00:50 UTC
Labels: more-information-needed

**Comment by xDinomode** [comment] 2016-01-14 00:57
Okay glad I'm not the only one with this problem. please fix soon
