### ISSUE TITLE
Atom crashed with SIGSEGV in v8::internal::GlobalHandles::Node::Release()

### ISSUE THREAD

**Issue by fcharlie** [atom/atom#12630] opened 2016-09-08 09:32 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When I close ATOM Editor, apport-gtk report ATOM exit with SIGSEGV.

**Package Info**
 
![2016-09-08 17-26-00](https://cloud.githubusercontent.com/assets/6904176/18344314/57d6e1f8-75e9-11e6-9169-d91011249c31.png)

**Disassembly**

![2016-09-08 17-27-03](https://cloud.githubusercontent.com/assets/6904176/18344356/7f41139e-75e9-11e6-8843-fc011592d10d.png)

**JournalErrors**

![2016-09-08 17-28-51](https://cloud.githubusercontent.com/assets/6904176/18344414/bba56916-75e9-11e6-9e01-0bae41f892f2.png)

**Stack and other**
![2016-09-08 17-29-42](https://cloud.githubusercontent.com/assets/6904176/18344444/e2325486-75e9-11e6-96ed-61bc67981e47.png)

![2016-09-08 17-31-21](https://cloud.githubusercontent.com/assets/6904176/18344488/19ef9e60-75ea-11e6-9407-0fac5e12082b.png)

### Versions

```shell
Atom    : 1.10.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

```shell
Linux someone 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

```shell
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by krasoffski** [comment] 2016-09-18 15:00
Have this problem on xubuntu 16.04 on differ workstations.

**Comment by clivend** [comment] 2016-09-20 13:40
+1 have it on Ubuntu 14.04 with n installed, from there I use node 6.6.0

**Comment by delacruzbordajn** [comment] 2016-09-22 03:09
Same problem....

Distributor ID: Ubuntu
Description: Ubuntu 16.04.1 LTS
Release:	16.04
Codename: Xenial

Atom    : 1.10.2

Kernel: 4.7.4-040704-generic

**Comment by 50Wliu** [comment] 2016-09-22 14:01
Anyone who is experiencing this: can you reliably reproduce this crash, or does it happen randomly?  If you can reproduce it, does it still happen in safe mode (`atom --safe`)?  And finally, can you paste the output of `atom --version` here?  Thanks.

**Comment by krasoffski** [comment] 2016-09-23 11:05
In my case crashes happen randomly. 
I just open atom with empty tab -> close with "ALT+F4", ubuntu notifies about crash report. Second and third, etc attempts are OK. 
After cleaning up /var/crash directory problem appears quite often:
 1. Open atom
 2. Close atom
 3. Crash detected
 4. Clean up `/var/crash`
 5. Open atom again
 6. Crash detected again.

Without clean up of `/var/crash` (x)ubuntu does not notify about crash.
```
atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

With `atom --safe` I have crash of atom too.
I can share ubuntu report if you with. It contains core dump.

**Comment by 50Wliu** [comment] 2016-09-23 20:08
Thanks @krasoffski!

**Comment by Aruee** [comment] 2016-09-26 10:05
I'm experiencing this, too... atom doesn't really crash though: Ubuntu reports a crash but the application itself seems to be unaffected.

    atom --version
    Atom    : 1.10.2
    Electron: 0.37.8
    Chrome  : 49.0.2623.75
    Node    : 5.10.0

**Comment by vicvega** [comment] 2016-09-26 10:09
Same problem here. On Ubuntu 16.04
```
atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by 50Wliu** [comment] 2016-09-26 15:22
Thanks for the replies everyone.

**Comment by maxbrunsfeld** [comment] 2016-09-26 16:50
Could everyone please try the beta release, [Atom 1.11-beta5](https://github.com/atom/atom/releases/tag/v1.11.0-beta5)? I believe this has been fixed.

**Comment by delacruzbordajn** [comment] 2016-09-27 03:57
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by krasoffski** [comment] 2016-09-27 11:00
It seems to me that problem has been fixed in the `atom 1.11`.
I was not able to reproduce crash with beta version of atom.
```
atom --version
Atom    : 1.11.0-beta5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```
But it would be great to keep this issue open till official release.

**Comment by vicvega** [comment] 2016-09-27 13:27
I confirm that it seems fixed with latest beta 
```
Atom    : 1.11.0-beta5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by 50Wliu** [comment] 2016-09-27 15:28
Thanks again everyone!

**Closed by 50Wliu** 2016-09-27 15:28 UTC
Labels: crash, linux, more-information-needed, needs-reproduction
