### ISSUE TITLE
ASCII code not recognizable   

### ISSUE THREAD

**Issue by DrMajkrosoft** [atom/atom#10948] opened 2016-02-24 13:19 UTC
While pressing " Ctrl + Alt + Q " with "Serbian" keyboard, the editor doesn't show the "backslash character", instead I have to switch keyboards in other to get the "backslash character".

**Comment by 50Wliu** [comment] 2016-02-24 13:28
This is a duplicate of atom/atom-keymap#35 - please subscribe there for updates.  You can also try the [keyboard-localization](https://atom.io/packages/keyboard-localization) package as a workaround.

**Closed by 50Wliu** 2016-02-24 13:28 UTC

**Comment by DrMajkrosoft** [comment] 2016-02-26 19:05
Ok, thank you.
