### ISSUE TITLE
Missing blank line in atom preview

### ISSUE THREAD

**Issue by DavidSagan** [atom/atom#17291] opened 2018-05-08 03:59 UTC
This is a minor inconsistency between how markdown is displayed in the atom previewer and how markdown is displayed on github. Simple markdown example:

```
- A
  - AA
  
- B
```

When displayed on github there is a blank line between the line `- AA` and the line `- B` but in the atom previewer there is no blank line between the two.

**Comment by rsese** [comment] 2018-05-08 22:06
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/markdown-preview/issues/150 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-08 22:06 UTC
