### ISSUE TITLE
Right click menu on two monitor setup is off position of actual mouse position

### ISSUE THREAD

**Issue by Dumr** [atom/atom#9087] opened 2015-10-08 16:54 UTC
Hi, when I right click anywhere in atom, menu shows on completely different position. It is quite far right and slightly below actual mouse cursor position. I am using Ubuntu 15.04 and have two monitors. One is laptop 1600x900 and other one is regular LCD 1280x1024

I can't capture screenshot because when i press it, menu disapers.

**Comment by mnquintana** [comment] 2015-10-08 17:45
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/8921 - please subscribe there for updates.

**Closed by mnquintana** 2015-10-08 17:45 UTC
