### ISSUE TITLE
Atom can not delete file or directory from left tree

### ISSUE THREAD

**Issue by linlingyu** [atom/atom#10492] opened 2016-01-19 07:46 UTC
System: windows 7
Atom version: 1.4.0

**Comment by mnquintana** [comment] 2016-01-19 13:14
Thanks for the report! :smile: This looks like a duplicate of https://github.com/atom/tree-view/issues/666 – feel free to subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) for a guide on where to post issues, including searching for duplicates.

**Closed by mnquintana** 2016-01-19 13:14 UTC
