### ISSUE TITLE
Fail to launch new window: SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by gabriel** [atom/atom#12018] opened 2016-06-21 17:16 UTC
Was unable to start a 2nd editor window. The console showed this:

```sh
6/21/16 10:13:19.975 AM Atom[30794]: App load time: 244ms
6/21/16 10:13:19.982 AM Atom[30658]: Unexpected end of input
6/21/16 10:13:19.983 AM Atom[30658]: SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:244:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
6/21/16 10:13:19.983 AM Atom[30658]: Unexpected token i
6/21/16 10:13:19.983 AM Atom[30658]: SyntaxError: Unexpected token i
    at Object.parse (native)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:244:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
6/21/16 10:13:19.984 AM Atom[30658]: Unexpected token L
6/21/16 10:13:19.984 AM Atom[30658]: SyntaxError: Unexpected token L
    at Object.parse (native)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:244:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

**Comment by 50Wliu** [comment] 2016-06-21 17:30
This is a duplicate of #11712 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-21 17:30 UTC
