### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by dflock** [atom/atom#12910] opened 2016-10-07 20:53 UTC
I wasn't doing anything in atom when this happened. I had it open with a load of windows & tabs, etc... but it wasn't the foreground window, I was doing something else. It had been running happily for a couple of weeks, used all day every day by this point. First time I've seen this error. Haven't installed any new packages lately.

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 14.04.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:178

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:178:13)
    at undefined.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:112:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:636:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:670:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app.asar/src/window-event-handler.js:182:35)
    at /usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
     -3:36.3.0 editor:delete-line (atom-text-editor.editor.is-focused)
  2x -3:35 core:move-up (atom-text-editor.editor.is-focused)
     -3:33.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -3:31.4.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -3:31.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -3:31.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:30.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -3:29.9.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:29.8.0 markdown-writer:indent-list-line (atom-text-editor.editor.is-focused)
     -3:29.8.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -3:29.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:29.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:29.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -3:29.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  4x -3:26.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:46.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ansible": [
        "yml"
      ]
    },
    "disabledPackages": [
      "robot-selenium-snippet",
      "atomatigit",
      "open-path",
      "linter-alex",
      "git-time-machine",
      "linter-jscs",
      "linter-jshint",
      "linter-jsonlint",
      "language-mongodb",
      "symbols-tree-view",
      "synced-sidebar"
    ],
    "ignoredNames": [
      ".git",
      ".pyc",
      ".iml",
      ".ipr",
      ".iws",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".codekit-cache",
      "bower_components",
      "node_modules"
    ],
    "projectHome": "/home/duncan/dev",
    "themes": [
      "one-dark-ui",
      "duotone-dark-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Operator Mono Book",
    "fontSize": 16,
    "invisibles": {},
    "lineHeight": 1.2,
    "preferredLineLength": 100,
    "scrollPastEnd": true,
    "showInvisibles": true,
    "softWrap": true,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
ansible-snippets, v0.2.0 (inactive)
asciidoc-assistant, v0.2.1 (active)
asciidoc-image-helper, v1.0.0 (active)
asciidoc-preview, v2.6.0 (active)
atom-beautify, v0.29.13 (active)
atom-dark-fusion-syntax, v1.2.4 (inactive)
atom-jinja2, v0.5.0 (active)
atom-special-char-highlighter, v0.1.0 (active)
atomatigit, v1.5.5 (inactive)
autocomplete-asciidoc, v0.1.1 (active)
autocomplete-modules, v1.6.3 (active)
autocomplete-project-paths, v2.2.0 (active)
autocomplete-python, v1.8.6 (active)
character-table, v0.4.3 (active)
color-picker, v2.2.2 (active)
docblockr, v0.8.5 (active)
duotone-dark-earth-syntax, v1.0.0 (inactive)
duotone-dark-forest-syntax, v1.0.0 (inactive)
duotone-dark-sea-syntax, v1.0.0 (inactive)
duotone-dark-space-syntax, v1.0.0 (inactive)
duotone-dark-syntax, v1.0.0 (active)
editorconfig, v1.4.1 (active)
emmet-simplified, v2.5.0 (active)
file-icons, v1.7.19 (active)
file-templates, v0.2.0 (active)
file-watcher, v0.4.0 (active)
genesis-syntax, v1.0.7 (inactive)
git-blame, v0.4.11 (active)
git-control, v0.8.2 (inactive)
git-hide, v0.1.2 (active)
git-history, v3.2.0 (active)
git-plus, v5.17.0 (active)
git-time-machine, v1.5.3 (inactive)
hard-wrap, v1.1.0 (inactive)
indent-guide-improved, v1.4.10 (active)
json-converter, v0.2.4 (inactive)
language-ansible, v0.1.11 (active)
language-asciidoc, v1.5.1 (active)
language-diff, v0.4.0 (active)
language-docker, v1.1.7 (active)
language-dotfiles, v0.4.1 (active)
language-dots, v0.0.4 (active)
language-generic-config, v1.1.0 (active)
language-gradle, v0.0.3 (active)
language-groovy, v0.6.0 (active)
language-hosts, v0.1.2 (active)
language-ini, v1.16.0 (active)
language-latex, v0.6.1 (active)
language-log, v1.5.0 (active)
language-mongodb, v0.3.1 (inactive)
language-nginx, v0.6.1 (active)
language-restructuredtext, v1.0.0 (active)
language-robot-framework, v2.2.0 (active)
language-svg, v0.9.0 (active)
language-vue, v0.16.1 (active)
last-cursor-position, v0.9.0 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.16 (active)
linter-alex, v3.2.0 (inactive)
linter-ansible-syntax, v1.1.0 (active)
linter-codeclimate, v0.1.2 (active)
linter-csslint, v1.3.2 (active)
linter-js-standard, v3.4.1 (active)
linter-js-yaml, v1.2.5 (active)
linter-jscs, v4.1.0 (inactive)
linter-jshint, v3.0.0 (inactive)
linter-jsonlint, v1.3.0 (inactive)
linter-less, v2.6.0 (active)
linter-markdown, v3.0.2 (active)
linter-pep8, v1.3.2 (active)
linter-pydocstyle, v0.4.2 (active)
linter-sass-lint, v1.7.1 (active)
linter-shellcheck, v1.4.1 (active)
linter-swagger, v0.3.6 (active)
linter-write-good, v0.7.0 (active)
linter-xmllint, v1.3.6 (active)
markdown-themeable-pdf, v1.2.0 (active)
markdown-writer, v2.5.1 (active)
minimap, v4.25.0 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-split-diff, v0.3.1 (active)
open-path, v0.3.6 (inactive)
open-terminal-here, v2.1.4 (inactive)
pigments, v0.35.1 (active)
pretty-json, v1.6.0 (active)
pubster-syntax, v1.4.1 (inactive)
robot-selenium-snippet, v1.0.1 (inactive)
rst-preview-pandoc, v0.1.12 (active)
set-syntax, v0.3.0 (active)
slime, v1.6.1 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v1.0.4 (active)
ssh-config, v0.10.1 (active)
standardjs-snippets, v2.4.0 (active)
susave, v0.4.0 (inactive)
symbols-tree-view, v0.13.2 (inactive)
synced-sidebar, v0.4.3 (inactive)
tabs-closer, v0.13.0 (inactive)
text-manipulation, v0.6.0 (active)
title-case, v0.4.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
tornado-templates, v0.2.0 (active)
tree-view-git-status, v1.1.0 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (active)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-10-07 21:04
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-07 21:04 UTC
