### ISSUE TITLE
Piping STDIN into Atom CLI

### ISSUE THREAD

**Issue by mrmark** [atom/atom#7556] opened 2015-06-29 16:07 UTC
When trying out Atom 1.0, I was totally digging it until I went to the command line and tried:

    ls | atom

And I got a blank document.  After some searching I found this [discussion thread](https://discuss.atom.io/t/it-would-be-nice-to-be-able-to-pipe-standard-out-to-atom-and-have-it-open-in-an-unsaved-document/4781).  Seems that a lot of folks would like this and for me, it is part of my daily workflow.

I searched the issues and pull requests here and couldn't find an issue for this, but please close if this topic has already come and gone.

Cheers and thanks!

**Comment by mnquintana** [comment] 2015-06-29 16:10
Thanks for the suggestion! Looks like this is a duplicate of https://github.com/atom/atom/issues/1729 – let's keep the discussion there.

**Closed by mnquintana** 2015-06-29 16:10 UTC

**Comment by smartnut007** [comment] 2015-07-09 19:50
:+1:
