### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Sabertooth/Downloads/Atom.app'

### ISSUE THREAD

**Issue by Sabertooth86** [atom/atom#12188] opened 2016-07-18 03:40 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Sabertooth/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/Sabertooth/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:314:24)
    at toRealPath (module.js:113:13)
    at Function.Module._findPath (module.js:153:20)
    at Module._resolveFilename (module.js:336:25)
    at Function.Module._resolveFilename (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Sabertooth/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
```

### Commands

```
     -0:52.6.0 vim-mode:repeat-find-reverse (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:50.7.0 vim-mode:outdent (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:10.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.operator-pending-mode.is-focused)
     -0:10.2.0 vim-mode:repeat-search (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:10 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  6x -0:07.7.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoclose-html",
      "autoclose",
      "vim-mode-zz"
    ]
  },
  "editor": {
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2016-07-18 08:00
https://github.com/atom/atom/issues/10774?

**Comment by 50Wliu** [comment] 2016-07-18 13:42
This is a duplicate of #10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-18 13:42 UTC
