### ISSUE TITLE
How can I open a file in the same tab using cmd+p?

### ISSUE THREAD

**Issue by jim-moody** [atom/atom#14395] opened 2017-05-11 15:00 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Currently, every time I use cmd+p to open a file in Atom, it creates a new tab which leads to tab overload.

I am looking for a way to open a file using cmd+p and have it replace the file I am currently viewing.

### Steps to Reproduce

1. Open directory in atom with at least 2 files
2. Hit Cmd+P, start typing a filename and click on a file
3. Hit Cmd+P again, start typing a new filename and click on that file

**Expected behavior:** 2nd file replaces the first file so I have only ONE tab open

**Actual behavior:** 2nd file opens in a new tab so now I have TWO tabs open

**Reproduces how often:** [100%

### Versions
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

The command is working as expected, but I would think there was some command to have it open in the same tab instead of opening a new tab.

**Comment by rsese** [comment] 2017-05-11 20:19
Hey @jim-moody :wave:  This isn't currently possible but there's an existing feature request for this behavior in https://github.com/atom/fuzzy-finder/issues/81.

Also, if you have a question rather than a specific bug report or feature request, the best place to start is the Atom message board:

https://discuss.atom.io/

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/81. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-11 20:19 UTC
