### ISSUE TITLE
After the last update I get some errors and development tools opened.

### ISSUE THREAD

**Issue by AnyoneCare** [atom/atom#11227] opened 2016-03-21 14:40 UTC
### Description

I'm runing Elementary OS Freya.
I updated atom today and...
When I open the atom editor I get development tools, windows is whole white and in the console from development tools I get:
`Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:17:12)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository-provider.js:8:19)
    at Object.<anonymous> (/opt/atom/resources/app.asar/src/git-repository-provider.js:83:4)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)`

### Steps to Reproduce

1. I just open the atom and get that error

**Expected behavior:** To enter like usually in the atom editor

**Actual behavior:** I get whole window in white and development tools opened.

### Versions
atom --version:
`1.6.0`
apm --version:
`apm  1.6.0`
`npm  2.13.3`
`node 0.10.40`
`python 2.7.6`
`git 1.9.1`

I've tried to reinstall atom, delete caches, configs.. etc. Didn't work..

P.S.: Sorry for my english!

P.S.2: I will leave here an image:
![screenshot from 2016-03-21 16 36 58](https://cloud.githubusercontent.com/assets/17096004/13921990/2a1935f0-ef83-11e5-8ff6-71cb59334ea9.png)

**Comment by YeFatBoy** [comment] 2016-03-21 14:50
Me Too! @AnyoneCare

**Comment by Ben3eeE** [comment] 2016-03-21 15:00
Duplicate of https://github.com/atom/atom/issues/10819 ?

**Comment by thomasjo** [comment] 2016-03-22 08:35
Definitely a duplicate of https://github.com/atom/atom/issues/10819. Thanks @Ben3eeE!

**Closed by thomasjo** 2016-03-22 08:35 UTC
