### ISSUE TITLE
Single line comments are not always displayed correctly (JS file)

### ISSUE THREAD

**Issue by ArmandGrillet** [atom/atom#4837] opened 2015-01-03 20:44 UTC
## Problem
When you have long lines in a JS file with single line comments at their end strange things happen. The issues happen to me twice today but only in specific cases (each time I was coding a concatenation of variables and strings) so I put examples that only need to be copy and paste.

## Configuration
Atom version 0.165.0
Mac OS X version 10.10.2.
File in JS language and encoded in UTF-8.

#### 1) Second line commented

```javascript
$("#answer-" + (maxAnswers + 1)).html("<h1 class=\"help-title\">" + term.substring(0, wordPos) + "<span class=\"match\">" + term.substr(wordPos, this.help.val().length) + "</span>" + "test".substring(this.help.val().length) + "</h1>"); // Put the answer in the appropriate div.
$("#answer-" + (maxAnswers + 1)).html("<h1 class=\"help-title\">" + term.substring(0, wordPos) + "<span class=\"match\">" + term.substr(wordPos, this.help.val().length) + "</span>" + "test".substring(this.help.val().length) + "</h1>" ); // Put the answer in the appropriate div.
```
This code in Atom will put the second line in comment:
![capture d ecran 2015-01-03 a 21 26 45](https://cloud.githubusercontent.com/assets/2117580/5603634/472a9428-938f-11e4-9ad8-119883c9760a.png)
The second line has only one comment at its end but the entire looks commented. If you run this code the second line will be executed as it should.

#### 2) No comment
```javascript
$("#answer-" + (maxAnswers + 1)).html("<h1 class=\"help-title\">" + term.substring(0, wordPos) + "<span class=\"match\">" + term.substr(wordPos, this.help.val().length) + "</span>" + term.substring(wordPos + this.help.val().length) + "</h1>" + result); // Put the answer in the appropriate div
```
The comment is not correctly displayed:
![capture d ecran 2015-01-03 a 21 37 18](https://cloud.githubusercontent.com/assets/2117580/5603657/ba8c720a-9390-11e4-9bc0-87f27c3b7ca3.png)

**Comment by izuzak** [comment] 2015-01-03 22:53
I believe this is a duplicate of atom/atom#1667 where the issue is that the line is too long and colorization stops/breaks at a certain token limit (currently, 100). Please subscribe to atom/atom#1667 for updates about this.

**Closed by izuzak** 2015-01-03 22:53 UTC
