### ISSUE TITLE
When searching acorss a project it should be possible to copy the text of the search result for reference

### ISSUE THREAD

**Issue by edwin-itrs** [atom/atom#12334] opened 2016-08-05 09:29 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce
When searching acorss a project it should be possible to copy the text of the search result for reference

1. Search for something across a project
2. Select the result
3. Try to copy the result so you can save it for future reference or share.

**Expected behavior:** [What you expected to happen]
Able to copy or save the results as text

**Actual behavior:** [What actually happened]
Copy does not work.

### Versions
1.9.2

**Comment by 50Wliu** [comment] 2016-08-05 19:10
This is a duplicate of atom/find-and-replace#416 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-05 19:10 UTC
