### ISSUE TITLE
Edit tab's drop list not rendered correctly

### ISSUE THREAD

**Issue by Code-Vortex** [atom/atom#5698] opened 2015-02-23 20:13 UTC
I have an issue with Edit tab when i select it the list is not rendered correctly the list should be under Edit word but its not , however the other tabs working perfect. my problem with Edit only

OS: Linux
Distro: Fedora 21

Screenshots:
![screenshot from 2015-02-23 22 06 04](https://cloud.githubusercontent.com/assets/4104127/6336094/e54db496-bba8-11e4-9727-970b584d5dad.png)
![screenshot from 2015-02-23 22 06 32](https://cloud.githubusercontent.com/assets/4104127/6336106/fa5bc526-bba8-11e4-80c6-ad9c3555442c.png)

**Comment by postcasio** [comment] 2015-02-24 11:23
Isn't this the intended behaviour by your window manager? Displaying the menu directly below the Edit label would cut it off at the bottom of the screen because it is too long, so it moves it up (and over, so it doesn't overlap the label) until it will fit.

**Comment by thomasjo** [comment] 2015-02-24 16:14
This is indeed related to a *Window Manager*. The only other way to fix this would be to "scroll" the menu, but I believe that is/should be handled by the *WM*. Regardless, this issue should be moved to [atom-shell](https://github.com/atom/atom-shell) since that's where the Menu Magic™ happens.

@Code-Vortex Please open a [new issue for atom-shell](https://github.com/atom/atom-shell/issues) and close this one, if you still consider this a bug.

**Closed** 2015-04-13 22:50 UTC
Labels: linux
