### ISSUE TITLE
TypeError: Cannot read property 'isEqual' of undefined

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18081] opened 2018-09-20 21:41 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

**EDIT: no problem in safe mode! So it must be some plugin.**

I click on the "soft wrap" option in "Editor" settings, and it does

```


**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core
```

### Stack Trace

```
Uncaught TypeError: Cannot read property 'isEqual' of undefined
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:261

TypeError: Cannot read property 'isEqual' of undefined
    at editorsWithMaintainedConfig.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:261:56)
    at Set.forEach (<anonymous>)
    at subscriptions.add.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:260:52)
    at emitter.on (/Applications/Atom.app/Contents/Resources/app/src/config.js:1290:15)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:1226:62)
    at Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:1052:23)
    at Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:715:18)
    at SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:238:34)
    at HTMLInputElement.changeHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:174:25)
```

### Commands

```
     -4:24.5.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -4:24.1.0 vim-mode-plus:put-after (input.hidden-input)
  2x -4:21 vim-mode-plus:move-to-next-word (input.hidden-input)
  3x -4:10 vim-mode-plus:move-down (input.hidden-input)
  4x -4:09.6.0 vim-mode-plus:move-up (input.hidden-input)
     -4:08.7.0 vim-mode-plus:move-to-first-line (input.hidden-input)
     -4:07.9.0 vim-mode-plus:repeat-search (input.hidden-input)
     -4:07.2.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -4:06.9.0 vim-mode-plus:move-down (input.hidden-input)
  2x -4:06.6.0 vim-mode-plus:move-up (input.hidden-input)
     -4:06.1.0 ex-mode:open (input.hidden-input)
  3x -4:06.1.0 blur (input.hidden-input)
     -4:05.7.0 core:confirm (input.hidden-input)
  3x -4:05.7.0 blur (input.hidden-input)
     -4:04.0 settings-view:open (input.hidden-input)
 36x -4:03.8.0 blur (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-browser 0.68.0 
atom-domterm 0.6.0 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-terminal-panel 4.4.4 
atom-vim-like-tab 1.5.1 
atom-webbrowser 2.1.4 
autocomplete 0.47.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
editorconfig 2.2.2 
ex-mode 0.18.0 
ex-mode-sort 1.0.0 
file-icons 2.1.21 
file-type-icons 1.3.4 
file-watcher 1.2.6 
hey-pane 1.1.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-typescript 0.7.6 
ide-vue 0.1.8 
imdone-atom 2.4.29 
indent-guide-improved 1.4.13 
intentions 1.1.5 
keymap-control 1.2.0 
keystroke 0.4.0 
language-babel 2.85.0 
language-javascript-semantic 0.2.1 
language-jenkinsfile 0.1.1 
language-pug 0.0.22 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-quick-highlight 1.0.1 
moonlight 0.7.0 
narrow 0.65.1 
narrow-git-ls 0.2.0 
open-this 0.5.0 
pane-browser 1.6.0 
paner 1.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
project-plus 1.0.0 
quick-highlight 0.13.0 
teletype 0.13.2 
terminal-plus 0.14.5 
terminal-tab 0.5.6 
todo-show 2.3.0 
toggle 0.6.2 
toggle-quotes 1.1.0 
tomorrow-night-eighties-syntax 1.0.2 
tree-view-git-status 1.5.0 
vim-mode-plus 1.34.0 
vim-mode-plus-ex-mode 0.11.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-macros 0.1.2 
vim-mode-plus-move-selected-text 0.12.0 
```

### Additional Information

@t9md is this a problem with vim-mode-plus?

**Comment by trusktr** [comment] 2018-09-20 21:46
@t9md nvm, I disabled vim-mode-plus, and I still get the error when I try to toggle soft-wrap.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'isEqual' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:261

TypeError: Cannot read property 'isEqual' of undefined
    at editorsWithMaintainedConfig.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:261:56)
    at Set.forEach (<anonymous>)
    at subscriptions.add.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:260:52)
    at emitter.on (/Applications/Atom.app/Contents/Resources/app/src/config.js:1290:15)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:1226:62)
    at Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:1052:23)
    at Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:715:18)
    at SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:238:34)
    at HTMLInputElement.changeHandler (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:174:25)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-browser 0.68.0 
atom-domterm 0.6.0 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-terminal-panel 4.4.4 
atom-vim-like-tab 1.5.1 
atom-webbrowser 2.1.4 
autocomplete 0.47.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
editorconfig 2.2.2 
ex-mode 0.18.0 
ex-mode-sort 1.0.0 
file-icons 2.1.21 
file-type-icons 1.3.4 
file-watcher 1.2.6 
hey-pane 1.1.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-typescript 0.7.6 
ide-vue 0.1.8 
imdone-atom 2.4.29 
indent-guide-improved 1.4.13 
intentions 1.1.5 
keymap-control 1.2.0 
keystroke 0.4.0 
language-babel 2.85.0 
language-javascript-semantic 0.2.1 
language-jenkinsfile 0.1.1 
language-pug 0.0.22 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-quick-highlight 1.0.1 
moonlight 0.7.0 
narrow 0.65.1 
narrow-git-ls 0.2.0 
open-this 0.5.0 
pane-browser 1.6.0 
paner 1.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
project-plus 1.0.0 
quick-highlight 0.13.0 
teletype 0.13.2 
terminal-plus 0.14.5 
terminal-tab 0.5.6 
todo-show 2.3.0 
toggle 0.6.2 
toggle-quotes 1.1.0 
tomorrow-night-eighties-syntax 1.0.2 
tree-view-git-status 1.5.0 
vim-mode-plus 1.34.0 
vim-mode-plus-ex-mode 0.11.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-macros 0.1.2 
vim-mode-plus-move-selected-text 0.12.0 
```

**Comment by trusktr** [comment] 2018-09-20 21:48
no problem in safe mode! So it must be some plugin.

**Comment by rsese** [comment] 2018-09-20 23:13
Thanks for the report!

> no problem in safe mode! So it must be some plugin.

:+1:  Based on the error, looks like a duplicate of https://github.com/atom/atom/issues/16394 where the issue seemed to be tracked down to `todo-show`.

Looks to be resolved in the latest release of that package /cc https://github.com/atom/atom/issues/16394#issuecomment-415984074.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-09-20 23:13 UTC
