### ISSUE TITLE
Uninstalling a package displays following message

### ISSUE THREAD

**Issue by amytruong** [atom/atom#11476] opened 2016-04-14 22:44 UTC
Both Mac and Windows.
Select a package to uninstall and following message displays. After restarting Atom, the message and the corresponding package is removed.

![screen shot 2016-04-14 at 12 32 20 pm](https://cloud.githubusercontent.com/assets/10725993/14546088/7e04f564-023e-11e6-8187-dc8cc1dd8719.png)

**Comment by Arcanemagus** [comment] 2016-04-14 23:44
Duplicate of #11464? Although that is labeled as Windows only the symptoms are the same.

**Closed** 2016-04-15 00:10 UTC
