### ISSUE TITLE
Files don't open in initial window on OS X

### ISSUE THREAD

**Issue by palant** [atom/atom#9526] opened 2015-11-11 11:29 UTC
I am using Atom 1.2.0-beta2 on OS X 10.10. I open files like that:

    open -a "Atom Beta" foo.js

If Atom isn't running yet then `foo.js` will be opened in the initial window. Opening another file after that will create a second application window, additional files will be added as tabs to that window. I would expect these files to be added to the initial window.

Originally I thought that the initial window is opened in dev mode because Cmd+Alt+I shortcut works there. However, `node-inspector` shows `window.devMode === false` for the initial window and `window.devMode === undefined` for the second one.

**Comment by palant** [comment] 2015-11-11 12:47
This seems to be caused by the strict comparison for the `window.devMode` flag. For externally opened files `openPath` function will be [called with `devMode === undefined`](https://github.com/atom/atom/blob/ff812749e67ed55518f91fa9d56286f8f3ce4ed6/src/browser/atom-application.coffee#L224). But this makes the comparison in [function `windowForPath`](https://github.com/atom/atom/blob/ff812749e67ed55518f91fa9d56286f8f3ce4ed6/src/browser/atom-application.coffee#L341) fail (`false !== undefined`) so that the existing window is considered unsuitable for the file. Adding something like this to `openPaths` function should do:    

    devMode = if devMode then true else false

**Comment by izuzak** [comment] 2015-11-11 16:43
Thanks for the report, @palant. I'm going to cc @maxbrunsfeld for more :eyes:.

**Comment by samrayner** [comment] 2015-11-13 20:31
I can reproduce this in 1.2.0. It seems to be a bug introduced since 1.1.0.

Navigate to a folder in Terminal > `atom .` to open the folder in Atom > `open .` to open the folder in Finder > double click a file within the folder in Finder > opens a new atom window instead of opening a tab in the existing window.

**Comment by ryanaltvater** [comment] 2015-11-16 19:12
I am also seeing this in the 1.2.0 release. When clicking on file outside of Atom and the current project/files open in Atom, the external file open a second window with the same files as the first window, only this time including the additional external file. This didn't occur in the previous 1.1.0 release.

**Comment by davydden** [comment] 2015-11-17 11:39
i noticed something interesting: Atom creates a new window when the current one does NOT have a project folder with a target file. When I drag-and-drop the second file from the same folder, the new window is not created.

**Comment by ryanaltvater** [comment] 2015-11-17 14:16
I use the Project Ring package, so I always have a project folder loaded in my main/current window. I just think it has more to do with the second part you mentioned, when the external file is not a part of the project loaded in the current window.

**Comment by benogle** [comment] 2015-11-17 19:58
@izuzak is this the same as https://github.com/atom/atom/issues/9574?

**Comment by palant** [comment] 2015-11-18 09:53
No, definitely not the same issue. #9574 talks about lots of windows being opened. https://github.com/atom/atom/issues/9526#issuecomment-155768149 has the analysis - the issue described here wouldn't result in more than two windows.

**Comment by izuzak** [comment] 2015-11-18 14:02
Yeah, not sure if it's the same problem, @benogle. The underlying cause might be the same (I'm not sure if it is, just saying it might), but it doesn't seem to be the same problem, as @palant mentioned.

**Comment by izuzak** [comment] 2015-11-19 17:07
This was fixed in https://github.com/atom/atom/pull/9672 (at least I can no longer reproduce the problem on master) so the changes will propagate to stable/beta releases at some point. Thanks again for the report and for investigating this.

**Closed by izuzak** 2015-11-19 17:07 UTC
Labels: mac, needs-reproduction

**Comment by palant** [comment] 2015-11-19 20:39
I can confirm that this issue is fixed in 1.3.0-beta5.
