### ISSUE TITLE
Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. ENOENT

### ISSUE THREAD

**Issue by jjohnson382** [atom/atom#11822] opened 2016-05-23 19:16 UTC
[Enter steps to reproduce below:]

1. Open a .hs file
2. Boom goes the dynamite: error message appears

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. ENOENT

```
At Error: spawn ghc-mod ENOENT
PATH: /Users/Jabulani/.local/bin:/Users/Jabulani/.cabal/bin:/Applications/ghc-7.10.3.app/Contents/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/git/bin:/sw/bin/:/usr/local/bin:/usr/local/:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/bin/
path: undefined
Path: undefined

Error: spawn ghc-mod ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

### Commands

```
     -0:14.9.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.5
haskell-ghc-mod, v1.14.3
ide-haskell, v1.6.5
language-haskell, v1.7.15

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-05-23 20:10
This is a duplicate of atom-haskell/haskell-ghc-mod#135 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-23 20:10 UTC
Labels: duplicate, wrong-repo
