### ISSUE TITLE
Failed to activate the Clean package

### ISSUE THREAD

**Issue by klingenm** [atom/atom#9928] opened 2015-12-03 10:40 UTC
[Enter steps to reproduce below:]

1. Opening new window (not tab)

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the Clean package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:3:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "preferredLineLength": 120,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "invisibles": {},
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
Clean, v0.10.0
language-puppet, v0.15.0
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-03 14:29
The Clean package appears to be unmaintained.  I would suggest uninstalling it and finding an alternative.  This is also a duplicate of andytlr/clean#7.

**Closed by 50Wliu** 2015-12-03 14:29 UTC
