### ISSUE TITLE
Uncaught Error: Cannot find module '../node_modules/keyboard-layout/build/Release/keyboard-layout...

### ISSUE THREAD

**Issue by SchadowofMorning** [atom/atom#15530] opened 2017-09-02 15:25 UTC
1. Open Atom
2. Klick a button
3. ???
4. Profit(or as here, this error)

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: EDO
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module '../node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'

```
At module.js:472

Error: Cannot find module '../node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.5/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.5/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.5/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.19.5/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:456:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:336:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.5/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.5/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
language-pug 0.0.21 
source-preview-pug 0.2.0 
```

**Comment by rsese** [comment] 2017-09-05 04:09
We've seen a handful of similar errors and I'll close as a duplicate of https://github.com/atom/atom/issues/14461.  Can you try reinstalling and let us know if you still get the error?

**Closed by rsese** 2017-09-05 04:09 UTC
