### ISSUE TITLE
Release Notes stuck at release 1.1.0

### ISSUE THREAD

**Issue by kdorsel** [atom/atom#10097] opened 2015-12-17 02:13 UTC
I've been upgrading Atom with every new release (Currently at 1.3.2), but the release notes have been stuck showing version 1.1.0 as the latest version and also showing the Restart and Update button when viewing the release notes

Clicking the Restart and Update button just closes Atom and it does not restart automatically.

I'm on Mac OS 11.2. This was also a problem on 11.1.

![screen shot 2015-12-16 at 21 13 14](https://cloud.githubusercontent.com/assets/2569415/11859536/d912bfda-a439-11e5-8220-b530a5453a88.png)

**Comment by 50Wliu** [comment] 2015-12-17 03:12
This is a duplicate of atom/release-notes#39 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-17 03:12 UTC
