### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by anokic** [atom/atom#22197] opened 2021-04-14 09:08 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At electron/js2c/asar.js:138

Error: Module did not self-register.
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:697035)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2798543)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2798645)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2798771)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1058046)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1228079)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1226064)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284879)
```

### Commands

```
     -0:18.4.0 editor:toggle-line-comments (input.hidden-input)
  6x -0:17.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
ace-material-syntax 1.5.0 
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-smart-path-autocomplete 0.1.0 
atom-vue 0.6.0 
autoclose-html-plus 0.27.2 
close-tags 0.6.0 
css-spy 0.6.0 
file-icons 2.1.40 
highlight-selected 0.17.0 
ide-vue 0.1.9 
language-vue 0.26.0 
material-syntax 0.6.1 
material-ui 1.0.10 
one-dark-material-syntax 1.0.3 
pigments 0.40.2 
```

**Comment by zanethomas** [comment] 2021-04-14 15:58
how can i disable this? cannot work

**Comment by zanethomas** [comment] 2021-04-14 15:59
updated and restarted atom, all better now

**Comment by sadick254** [comment] 2021-04-14 16:27
@anokic Have you tried updating atom to the latest version?

**Comment by zanethomas** [comment] 2021-04-14 20:31
@sadick254 what sadick? <g> j/k

**Comment by icecream17** [comment] 2021-04-14 20:54
same as https://github.com/atom/atom/issues/22186

**Comment by sadick254** [comment] 2021-04-27 19:14
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2021-04-27 19:14 UTC
