### ISSUE TITLE
"No, Never" on "Register as default atom:// URL Handler popup doesn't seem to work properly.

### ISSUE THREAD

**Issue by JMccormick264** [atom/atom#16440] opened 2017-12-24 19:28 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whenever I open a new Window, I always get "Register as default atom:// URL handler?" despite me pressing "No, Never" each time. 

### Steps to Reproduce

1 I am on https://github.com/atom/atom/releases/tag/v1.24.0-beta1 <-- Version
2. Install that
3. Open Atom
4. When you open the program, open a "New Window"
5. You should get [image here](https://i.imgur.com/XTRcRAs.png)

**Expected behavior:**
I expect the app to remember that I selected "No, Never" and not have that popup appear every time I open a new window

**Actual behavior:** [What actually happens]
When I open a new window, I get the popup "Register as default atom:// URL handler?" in blue at the top right of the window

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time

### Versions

Windows 10. Insider Build. Fast Ring. 17063

Atom    : 1.24.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.24.0-beta1
python 3.6.3
git 2.15.1.windows.2
visual studio 2015

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

[Image of what I see here](https://i.imgur.com/XTRcRAs.png)

**Comment by Ingramz** [comment] 2017-12-25 08:11
Should be fixed by #16397, but it hasn't made it to beta yet.

**Comment by JMccormick264** [comment] 2017-12-26 00:53
Alright. Will keep an eye out for it in the next beta builds.

**Comment by rsese** [comment] 2017-12-26 05:20
Thanks @Ingramz - I'll go ahead and close this as a duplicate of https://github.com/atom/atom/issues/16201.

**Closed by rsese** 2017-12-26 05:20 UTC
