### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by zojeda** [atom/atom#7011] opened 2015-05-29 14:44 UTC
[Enter steps to reproduce below:]

1. ...Add several Projects Folder
2. ...Right click on one of them

**Atom Version**: 0.204.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\zojeda\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -2:21.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:20 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
  3x -2:19.7.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:48.4.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -1:44.1.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:26.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
 13x -1:23.2.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -1:21.4.0 core:select-right (atom-text-editor.editor.is-focused)
     -1:20.3.0 core:delete (atom-text-editor.editor.is-focused)
 16x -1:19.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:18 core:move-left (atom-text-editor.editor.is-focused)
     -1:17.5.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -1:17.3.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:16.9.0 core:delete (atom-text-editor.editor.is-focused)
     -1:16.5.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
  3x -1:16.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "vim-mode",
      "atom-typescript",
      "linter-tslint",
      "terminal-panel"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs, v0.3.0
angularjs-styleguide-snippets, v0.7.0
atom-beautify, v0.27.9
atom-html-preview, v0.1.6
atom-terminal-panel, v4.4.4
atom-ternjs, v0.6.3
color-picker, v2.0.2
js-refactor, v0.3.0
linter, v0.12.6
minimap, v4.9.0
node-debugger, vundefined
refactor, v0.4.1
restore-windows, v0.4.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-29 14:48
Duplicate of #6548, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-29 14:48 UTC
