### ISSUE TITLE
Menu bar cannot be activated by keyboard

### ISSUE THREAD

**Issue by linquize** [atom/atom#6908] opened 2015-05-22 14:22 UTC
For example, pressing `Alt+F` should open `File` menu, then press `->` to move to `Edit` menu.
On Windows 7/8, this does not work after the main editor is focused, except for the welcome page.
On Ubuntu Linux (Unity), the menu bar can be activated normally by keyboard.

Atom version: 0.201

**Comment by mnquintana** [comment] 2015-05-22 14:30
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/4057 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-22 14:30 UTC
