### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by dal-green** [atom/atom#15668] opened 2017-09-16 18:51 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At C:\Users\Dallin.Green\AppData\Local\atom\app-1.20.0\resources\app\src\text-editor-component.js:2272

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:2261:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:2254:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:401:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:285:18)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.20.0/resources/app/src/text-editor-component.js:1561:59)
```

### Commands

```
     -9:56.4.0 core:move-up (input.hidden-input)
  2x -9:54.2.0 core:move-down (input.hidden-input)
     -9:48 core:move-up (input.hidden-input)
  4x -9:47.2.0 core:move-down (input.hidden-input)
     -9:44.4.0 autocomplete-plus:confirm (input.hidden-input)
     -9:43 core:save (input.hidden-input)
     -1:51 editor:newline (input.hidden-input)
     -1:47.7.0 core:paste (input.hidden-input)
     -1:34.8.0 core:save (input.hidden-input)
  2x -1:27.2.0 core:undo (input.hidden-input)
     -1:21.3.0 core:save (input.hidden-input)
     -0:46.1.0 core:paste (input.hidden-input)
     -0:23.8.0 core:undo (input.hidden-input)
     -0:23 core:paste (input.hidden-input)
     -0:20.2.0 core:undo (input.hidden-input)
     -0:18.4.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment] 2017-09-16 20:28
:wave: Thanks for opening an issue @dal-green!  Do you remember what you were doing when this error occurred?

**Comment by 50Wliu** [comment] 2017-09-16 20:30
Longer stacktrace from atom/tabs#521:
```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2272

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2261:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2254:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:401:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:285:18)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1468:18)
    at TextEditorComponent.didAttach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1435:20)
    at HTMLElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:41:25)
    at HTMLElement.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:138:24)
    at PaneContainer.replaceChild (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:146:16)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:232:25)
    at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:197:27)
    at /Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:240:30
    at wrapped (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:101:22)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app/src/pane.js:939:28)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:650:27)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:706:22)
    at TabBarView.module.exports.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:341:32)
    at HTMLDivElement.TabView.didClickCloseIcon (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:229:25)
```

**Comment by 50Wliu** [comment] 2017-09-16 20:51
Actually, this looks like a duplicate of #15263, but with the new error message.

**Closed by 50Wliu** 2017-09-16 20:51 UTC
Labels: editor-rendering, more-information-needed, uncaught-exception

**Comment by Ben3eeE** [comment] 2017-09-16 20:55
@dal-green It would be awesome if you could tell us anything about what you were doing when you ran into this exception 🙇

**Comment by dal-green** [comment] 2017-09-16 21:23
I believe I was pasting in some existing code. This erorr kept on showing
itself soI submitted a ticket cause it seemed like a good thing to do. But
I just closed out and logged back in to fix the issue.
