### ISSUE TITLE
File > New File fails if no window is focused

### ISSUE THREAD

**Issue by jsejcksn** [atom/atom#10298] opened 2016-01-06 03:54 UTC
*(Atom 1.3.2 on OS X 10.11.2)*

**Expected behavior**
Selecting `File > New File` in the menu bar (or pressing <kbd>⌘</kbd>+<kbd>n</kbd>) opens a new file (and a new window if necessary).

**Observed behavior**
Either method produces no result if there is not a window already open and focused (this includes having open but minimized windows).

**Comment by 50Wliu** [comment] 2016-01-06 14:41
@joshaber You just fixed this, right?

**Comment by joshaber** [comment] 2016-01-06 14:48
Yup! This is a dupe of https://github.com/atom/atom/issues/7171, which was fixed in https://github.com/atom/atom/pull/10233.

**Closed by joshaber** 2016-01-06 14:48 UTC
