### ISSUE TITLE
Uncaught Error: Cannot find module ./cONTEXT-menu Error: Cannot find module ./cONTEXT-menu at FUNCTION.Module._resolveFileNAME module.js:328:15 at FUNCTION.Module._load module.js:270:25 at Module.require module.js:357:17 at require module.js:376:17 at BrowserWindow. anonymous> C: Users Pat AppData Local atom app-0.209.0 resources app.asar src browser atom-window.js:152:27 at emitOne events.js:77:13 at BrowserWindow.emit events.js:166:7 at callFUNCTION C: Users Pat AppData Local atom app-0.209.0 resources atom.asar browser lib rpc-server.js:116:18 at EventEmitter. anonymous> C: Users Pat AppData Local atom app-0.209.0 resources atom.asar browser lib rpc-server.js:208:14 at emitMany events.js:108:13 

### ISSUE THREAD

**Issue by pkillean** [atom/atom#7263] opened 2015-06-13 06:34 UTC
Enter steps to reproduce below: 1. ... 2. ... **Atom Version**: 0.209.0 **System**: Microsoft Windows 8.1 **Thrown From**: Atom Core ### Stack Trace Uncaught Error: Cannot find module ./cONTEXT-menu Error: Cannot find module ./cONTEXT-menu at FUNCTION.Module._resolveFileNAME module.js:328:15 at FUNCTION.Module._load module.js:270:25 at Module.require module.js:357:17 at require module.js:376:17 at BrowserWindow. anonymous> C: Users Pat AppData Local atom app-0.209.0 resources app.asar src browser atom-window.js:152:27 at emitOne events.js:77:13 at BrowserWindow.emit events.js:166:7 at callFUNCTION C: Users Pat AppData Local atom app-0.209.0 resources atom.asar browser lib rpc-server.js:116:18 at EventEmitter. anonymous> C: Users Pat AppData Local atom app-0.209.0 resources atom.asar browser lib rpc-server.js:208:14 at emitMany events.js:108:13 At C: Users Pat AppData Local atom app-0.209.0 resources atom.asar renderer api lib remote.js:77 Error: Cannot find module ./cONTEXT-menu Error: Cannot find module ./cONTEXT-menu at FUNCTION.Module._resolveFileNAME module.js:328:15 at FUNCTION.Module._load module.js:270:25 at Module.require module.js:357:17 at require module.js:376:17 at BrowserWindow. anonymous> C: Users Pat AppData Local atom app-0.209.0 resources app.asar src browser atom-window.js:152:27 at emitOne events.js:77:13 at BrowserWindow.emit events.js:166:7 at callFUNCTION C: Users Pat AppData Local atom app-0.209.0 resources atom.asar browser lib rpc-server.js:116:18 at EventEmitter. anonymous> C: Users Pat AppData Local atom app-0.209.0 resources atom.asar browser lib rpc-server.js:208:14 at emitMany events.js:108:13 at metaToValue C: Users Pat AppData Local atom app-0.209.0 resources atom.asar renderer api lib remote.js:77:15 at BrowserWindow.RemoteMemberFUNCTION as emit C: Users Pat AppData Local atom app-0.209.0 resources atom.asar renderer api lib remote.js:111:26 at CONTEXTMenuManager.module.exports.CONTEXTMenuManager.showForEvent C: Users Pat AppData Local atom app-0.209.0 resources app.asar src cONTEXT-menu-manager.js:170:31 at HTMLDocument. anonymous> C: Users Pat AppData Local atom app-0.209.0 resources app.asar src window-event-handler.js:148:33 at HTMLDocument.handler C: Users Pat AppData Local atom app-0.209.0 resources app.asar src space-pen-extensions.js:112:34 at HTMLDocument.JQUERY.event.dispatch C: Users Pat AppData Local atom app-0.209.0 resources app.asar node_modules space-pen vendor jquery.js:4681:9 at HTMLDocument.elemData.handle C: Users Pat AppData Local atom app-0.209.0 resources app.asar node_modules space-pen vendor jquery.js:4359:46 ### Commands -2:28.6.0 paredit:OPENBracket atom-text-editor.editor.is-focused -2:28.4.0 paredit:closeBracket atom-text-editor.editor.is-focused -2:27.4.0 paredit:newLineAndIndent atom-text-editor.editor.is-focused -2:18.1.0 core:copy atom-text-editor.editor.is-focused -2:15.5.0 core:paste atom-text-editor.editor.is-focused -2:06.7.0 core:backspace atom-text-editor.editor.is-focused 7x -2:03.8.0 core:move-up atom-text-editor.editor.is-focused 3x -2:01.4.0 core:move-left atom-text-editor.editor.is-focused -2:00.4.0 core:move-right atom-text-editor.editor.is-focused 5x -2:00.3.0 core:move-down atom-text-editor.editor.is-focused -1:59.3.0 core:move-right atom-text-editor.editor.is-focused -1:59.2.0 core:move-down atom-text-editor.editor.is-focused 32x -1:58.4.0 core:move-right atom-text-editor.editor.is-focused -1:52.9.0 core:save atom-text-editor.editor.is-focused.autocomplete-active -0:10.2.0 core:move-up atom-text-editor.editor.is-focused -0:09.6.0 core:move-down atom-text-editor.editor.is-focused ### Config json { core : { disabledPackages : language-ruby-on-rails , language-ruby , language-c , language-coffee-script , language-csharp , language-go , language-less , language-make , language-objective-c , language-perl , language-php , language-sass , language-toml , language-mustache , paredit , themes : atom-dark-ui , atom-dark-syntax , autoHideMenuBar : true }, editor : { invisibles : {}, completions : console.log , showIndentGuide : true, scrollPastEnd : true, autoIndentOnPaste : false, fontSize : 13 } } ### Installed Packages coffee # User atom-paredit, v0.1.0 remember-session, v0.5.1 # Dev No dev packages

**Comment by izuzak** [comment] 2015-06-13 07:40
Thanks for the report -- this looks like a duplicate of https://github.com/atom/atom/issues/6548.

**Closed by izuzak** 2015-06-13 07:40 UTC
