### ISSUE TITLE
Add repo as a project folder, which was created in Ubuntu, in Windows crashes atom

### ISSUE THREAD

**Issue by kushalpandya** [atom/atom#9995] opened 2015-12-10 04:09 UTC
Steps to reproduce.

1) If you happen to use Dual-boot (Windows & Linux), create a Git repo under Linux with NPM packages included.
2) Come back to Windows and try to add it as project folder in Atom running on Windows.
3) Atom crashes.

*Affects current stable release 1.3* too.

I tried to run above steps while keeping DevTools open and setting _Break on uncaught exceptions_ ON, and debugger stopped in `fs` module within `fs.readSync()` (which may be the starting point of trouble) and finally, Atom crashed when call to `GitRepository.open` happened within `repositoryForDirectorySync()` of `git-repository-provider` module.

**Comment by kushalpandya** [comment] 2015-12-10 07:01
@lee-dohm I further debugged it and found that it is caused by call `repository.getSubmodulePaths()` , on path to `.git` folder of my repository,  in `git.js` within `openSubmodules()`, and since host environment is Windows, this is more of a compatibility issue. Let me know where can I find further information on implementation of `getSubmodulePaths` which happens to be a native method.

**Comment by lee-dohm** [comment] 2015-12-10 07:04
I suspect this may be a duplicate of https://github.com/atom/atom/issues/6674. It sounds like very similar if not the same symptoms.

**Comment by kushalpandya** [comment] 2015-12-10 07:19
I felt so but #6674 doesn't mention dual-boot scenario where `node_modules` of Linux may have some native Linux binaries which I'm trying to load on Windows, but then does it affect how `.git` is treated?

**Comment by kushalpandya** [comment] 2015-12-10 07:36
Looks like it is [libgit2](https://libgit2.github.com/) issue, @lee-dohm, you can mark it as duplicate of #8961. Let me know if I can help fixing it.

**Comment by lee-dohm** [comment] 2015-12-10 08:50
Feel free to help out on #8961. Thanks for the offer!

**Closed by lee-dohm** 2015-12-10 08:50 UTC
Labels: duplicate
