### ISSUE TITLE
"The editor has crashed" - atom consistently crashes within 30 seconds of opening

### ISSUE THREAD

**Issue by dfindley** [atom/atom#14101] opened 2017-03-30 15:48 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have been working on editing some SQL files and Atom keeps crashing whenever I open it up, even after following the steps from before. I have not installed any packages; it just breaks on me. I have reset my PC, reinstalled Atom, but still, constant crashing. I'm using 1.15 on Windows 7.

### Steps to Reproduce

1. Open up Atom
2. See it crash and have the window pop up within 30 seconds

**Expected behavior:** [What you expect to happen]

Less crashing

**Actual behavior:** [What actually happens]

Reliable crashing

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

1.15 on Windows 7

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by consciencia** [comment] 2017-03-30 17:57
I have same problem. Atom eats around 1.3 GB mem and then crash. This behaviour started after update in core linter package. If I remember it correctly ...

**Comment by rsese** [comment] 2017-03-31 00:14
@dfindley - would you be able to share the file that causes the crash?  Also, can you try running this command to [clear Atom's saved state](http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state) and see if it helps?

```
atom --clear-window-state
```

**Comment by 50Wliu** [comment] 2017-03-31 00:49
@consciencia That's interesting - does the crash still happen if you run Atom in safe mode (`atom --safe`)?  That way, Linter won't be loaded.

**Comment by consciencia** [comment] 2017-03-31 06:12
@50Wliu  Yes, it crash in safe mode.

**Comment by dfindley** [comment] 2017-03-31 16:40
@rsese I can't share my files as they're company files that access our database, but I'm even getting crashes with nothing opened. I followed all the debugging steps - safe mode, etc - and I'm still getting these crashes.

**Comment by rsese** [comment] 2017-03-31 23:22
@dfindley ahhh ok - so just to confirm so we're on the same page, things were working fine until you started working on those SQL files, and now Atom will crash when you open it even when starting it with `atom --safe` and after running `atom --clear-window-state`?

And for completeness, can you share the full version details for your system?

```
atom -v
apm -v
```

**Comment by rsese** [comment] 2017-03-31 23:27
Oh also, are there any crash files in `%LocalAppData%\Temp\Atom Crashes`?

**Comment by consciencia** [comment] 2017-04-02 08:35
My two cents.
Issue (at last, at my side) is either in atom-ctags or atom internal symbol handling facility.  
After I removed .tags files and masked node_modules directory (in ctags package), everything works fine.
I think, Atom have all symbols (of all added project) in memory, so when big index/es is/are loaded, it simply overflows heap and atom crash.

**Comment by dfindley** [comment] 2017-04-03 15:49
@rsese sorry, this is my work machine so I'm not on it on the weekends! Here are my version stats:

Atom: 1.15.0
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0

APM:
amp 1.15.3
npm: 3.10.5
node: 4.4.5 x64
python 2.7.11 (I'm pretty sure I also have 3.6 installed)
visual studio

I'm not sure I can get into my temp folder. I'm on a company PC, and am having trouble tracking it down.

**Comment by rsese** [comment] 2017-04-03 20:07
np @dfindley thanks for the details :v:

Just to step back a tiny bit, you mentioned:

> I have been working on editing some SQL files and Atom keeps crashing whenever I open it up

So to confirm, Atom worked fine until you started working on the SQL files and now it crashes every you open Atom since then?  Can you confirm how large the SQL files are or if there's anything else interesting about them (e.g. do they have a lot of lines, or super long lines, etc.)?

**Comment by rsese** [comment] 2017-04-03 20:10
@consciencia - could you open a new issue for the behavior you're seeing and fully fill out the issue template?   Though Atom is crashing for you as well, it sounds like some of the circumstances are a bit different so it would be great to track it separately :bow:

**Comment by josteinbf** [comment] 2017-04-05 08:19
Is this the same issue as #14049 ? If so, I'm having the same problem, and it is present also for 1.16.0-beta0.

**Comment by dfindley** [comment] 2017-04-06 16:31
@rsese for a long while, it was working fine with my SQL files. Then, within the last 2 weeks, it started crashing right after opening it. This still happened after following all the troubleshooting suggestions and clearing everything out. There wasn't anything terribly interesting about the SQL files - they're maybe 50-60 lines in length, no lines were terribly long, maybe 80 characters wide?

The SQL files could be misleading, maybe not.

**Comment by rsese** [comment] 2017-04-07 22:43
> Is this the same issue as #14049 ? If so, I'm having the same problem, and it is present also for 1.16.0-beta0.

Though the symptoms are similar It's hard to say if it's the same root cause @josteinbf, but thanks for cross-referencing them :+1:

> @rsese for a long while, it was working fine with my SQL files. Then, within the last 2 weeks, it started crashing right after opening it. This still happened after following all the troubleshooting suggestions and clearing everything out. There wasn't anything terribly interesting about the SQL files - they're maybe 50-60 lines in length, no lines were terribly long, maybe 80 characters wide?

Thanks for the details - just to get whatever more information we can, can you share the output of `atom -f`?

**Comment by dfindley** [comment] 2017-04-19 15:56
I get this error: FILE_ERROR_FAILED

**Comment by rsese** [comment] 2017-04-20 03:54
Thanks @dfindley, I see that error mentioned in https://github.com/atom/atom/issues/14049 as well.

Double checking some debugging steps, did you try resetting to factory defaults as well?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by rpuntaie** [comment] 2018-01-17 10:08
Version 1.23.3 of atom. 
The following ctags file makes atom still crash. Tried to debug, but debugger didn't stop in the async `get()` function somewhere down ` stream = ctags.createReadStream(p)`. Even if the ctags package has a problem, atom shouldn't crash.

.tags file:

```
ek4us	epic.rst	/^\.\. _`\?ek4us`\?:
x8xts	issues.rst	/^\.\. _`\?x8xts`\?:
x9zts	issues.rst	/^\.\. _`\?x9zts`\?:
```

**Comment by pabloab** [comment] 2018-02-25 18:46
This looks simmilar to issue #15688 (@50Wliu close it). I get this on `dmesg`:

    traps: atom[17403] trap invalid opcode ip:31adcf1 sp:7ffcb68616d0 error:0 in atom[400000+49c9000]
    traps: atom[16734] trap invalid opcode ip:28386d2 sp:7ffc5e5e3a40 error:0 in atom[400000+49c9000]
    traps: atom[29559] trap invalid opcode ip:31adcf1 sp:7ffc5e5e8050 error:0 in atom[400000+49c9000]

To maybe is related to nodejs issues [3898](https://github.com/nodejs/node/issues/3898) and [15798](https://github.com/nodejs/node/issues/15798). My case (since I'm working on something i don't [reset-to-factory-defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults), nor `--safe` nor `--clear-window-state`):

     $ (lsb_release -d && apm -v && apm -v) | tr '\n' ','
    Description:    Ubuntu 16.04.3 LTS,apm  1.18.12,npm  3.10.10,node 6.9.5 x64,atom 1.23.3,python 2.7.12,git 2.7.4,apm  1.18.12,npm  3.10.10,node 6.9.5 x64,atom 1.23.3,python 2.7.12,git 2.7.4

**Closed** 2018-10-02 15:16 UTC
Labels: crash, more-information-needed
