### ISSUE TITLE
Uncaught Error: spawn /bin/sh EAGAIN

### ISSUE THREAD

**Issue by Horta** [atom/atom#6340] opened 2015-04-11 17:56 UTC
[Enter steps to reproduce below:]

1. Opened atom from terminal while running fish shell.
2. Waited... Silent-sync package started its synchronisation.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /bin/sh EAGAIN

```
At events.js:141

Error: spawn /bin/sh EAGAIN
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
    at child_process.js:1127:20
    at process._tickCallback (node.js:357:13)
```

### Commands

```
  6x -7:30.3 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
script, v2.18.0
silent-sync, v1.1.5

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-04-13 12:10
This sounds like a duplicate of https://github.com/atom/atom/issues/4692. Can you check out that issue and leave a comment there if the suggestion doesn't help? Also, do you see the same problem in another shell?

**Closed by izuzak** 2015-04-13 12:10 UTC
