### ISSUE TITLE
[Further Request] Support Localization

### ISSUE THREAD

**Issue by Umoxfo** [atom/atom#16865] opened 2018-03-01 09:41 UTC
### Description

It will be easy to adapt the translation of menu items etc.
For example, add the "id" key to MenuManager so that we can overwrite the label by specifying the same id.

### Additional Information

I will introduce [japanese-menu](https://github.com/syon/atom-japanese-menu) as similar to my implementation proposal.

If my proposal is implemented, this package only needs to include language files, so the problem that occasionally translation is not solved is solved.

**Comment by Arcanemagus** [comment] 2018-03-01 17:32
It looks like there is already quite a bit more languages (and parts of the interface) supported in [atom-i18n](https://atom.io/packages/atom-i18n). There is a _lot_ more discussion on this in https://github.com/atom/atom/issues/3103.

**Comment by rsese** [comment] 2018-03-01 21:58
Thanks for the feedback @Umoxfo - :+1: on what @Arcanemagus said, I'm going to go ahead and close this as a duplicate of https://github.com/atom/atom/issues/3103.

**Closed by rsese** 2018-03-01 21:58 UTC
