### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by arcticicestudio** [atom/atom#7118] opened 2015-06-05 11:38 UTC
Atom: `0.206.0`
OS: Ubuntu 14.04 x64

Comes up everytime when opening the settings.

Stack Trace:
```
TypeError: Cannot read property 'find' of undefined
  at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.filterPackageListByText (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:377:15)
  at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.matchPackages (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:410:19)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:176:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1207:25
```

**Comment by mnquintana** [comment] 2015-06-05 12:03
This is a duplicate of https://github.com/atom/settings-view/issues/527 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-05 12:03 UTC
