### ISSUE TITLE
v1.25.1 Error: EACCES: using install script with custom location for user only install attempts to install to system directory

### ISSUE THREAD

**Issue by ypossem** [atom/atom#17090] opened 2018-04-06 01:01 UTC
### Description

The build and install script does not respect install location for icon installation. Unsure if this prevents a complete install, as opening the application still seems OK.

### Steps to Reproduce

1. git pull; git checkout v1.25.1
2. script/build --install=/home/user/.local

**Expected behavior:** Installation without errors

**Actual behavior:** Partial installation, ends with
Removing previously installed "atom-1.25.1-amd64" at "/home/user/.local/share/atom"
Installing "atom-1.25.1-amd64" at "/home/user/.local/share/atom"
Installing icons at "/usr/share/icons/hicolor"
Error: EACCES: permission denied, mkdir '/usr/share/icons/hicolor/1024x1024'
  at Object.fs.mkdirSync (fs.js:885:18)
  at mkdirsSync (/home/user/apps/atom/script/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
  at Object.mkdirsSync (/home/user/apps/atom/script/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:35:16)
  at Object.copySync (/home/user/apps/atom/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:36)
  at fs.readdirSync.forEach.imageName (/home/user/apps/atom/script/lib/install-application.js:103:14)
  at Array.forEach (<anonymous>:null:null)
  at module.exports (/home/user/apps/atom/script/lib/install-application.js:99:36)
  at binariesPromise.then.then.then.then.packagedAppPath (/home/user/apps/atom/script/build:132:7)
  at <anonymous>:null:null

**Reproduces how often:** 
Occurs both when building on top of previously built artifacts, and also after running git clean -fxd and building

### Versions

git tag/release v1.25.1

**Comment by rsese** [comment] 2018-04-06 01:50
Thanks for contributing!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16853 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-06 01:50 UTC
