### ISSUE TITLE
Uncaught Can't find                $insert_xml['delivery_type']   = trim($value->Cell[5]->Data);...

### ISSUE THREAD

**Issue by BlacklistMax** [atom/atom#17341] opened 2018-05-17 04:11 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 ia32
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find                $insert_xml['delivery_type']   = trim($value->Cell[5]->Data);
               $insert_xml['contact_name']    = trim($value->Cell[7]->Data);
               $insert_xml['address']         = trim($value->Cell[8]->Data);
               $insert_xml['postcode']        = trim($value->Cell[9]->Data); file

```
At C:\Users\max_b\AppData\Local\atom\app-1.27.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:980

undefined
```

### Commands

```
     -7:50.2.0 core:backspace (input.hidden-input)
     -7:49.5.0 intentions:highlight (input.hidden-input)
     -7:49.2.0 core:save (input.hidden-input)
  2x -6:36.5.0 core:backspace (input.hidden-input)
     -6:28.2.0 intentions:highlight (input.hidden-input)
     -6:28.1.0 core:paste (input.hidden-input)
     -6:27.3.0 core:save (input.hidden-input)
     -6:15.5.0 tree-view:remove (div.tool-panel.tree-view)
     -0:25 intentions:highlight (input.hidden-input)
  9x -0:24.9.0 core:undo (input.hidden-input)
  3x -0:19.8.0 core:save (input.hidden-input)
 42x -0:13.2.0 intentions:highlight (input.hidden-input)
     -0:11.3.0 emmet:encode-decode-data-url (input.hidden-input)
 12x -0:09.3.0 intentions:highlight (input.hidden-input)
     -0:08.4.0 editor:toggle-line-comments (input.hidden-input)
  2x -0:07.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.20 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
livereload 0.4.4 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
remote-ftp 2.1.4 
terminal-plus 0.14.5 
tortoise-svn 0.5.1 
```

**Comment by steveward** [comment] 2018-05-17 16:06
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/17271 so you can subscribe there for updates if you'd like.  If you remember what you were doing at the time of the error, please let us know in https://github.com/atom/atom/issues/17271.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by steveward** 2018-05-17 16:06 UTC
Labels: duplicate
