### ISSUE TITLE
MacOS new install Menu has no options

### ISSUE THREAD

**Issue by newscloud** [atom/atom#21820] opened 2020-12-23 02:50 UTC
### Description

Non-technical colleague downloaded Atom 1.53 from the website, atom-mac.zip for MacOS Mojave 14.6 and his Atom app appeared with a menu bar but almost no options... No way to create a new file or open a file. 

In finder, he was able to find the option to Open With Atom for a text file and this did nothing.

### Steps to Reproduce

1. Download Atom-mac.zip
2. Open Atom

**Expected behavior:**

menu has file options

**Actual behavior:**

menu does not have file options

one user on Mac Mojave 14.6 always

### Versions
1.53 atom

**Comment by ThatXliner** [comment] 2020-12-23 05:19
Did the window render?

**Comment by ThatXliner** [comment] 2020-12-23 20:27
I found similar behavior on #21751

**Comment by newscloud** [comment] 2020-12-30 03:03
There was a window for Atom, but no menu options.

**Comment by newscloud** [comment] 2020-12-30 21:35
> I found similar behavior on #21751

Thanks @ThatXliner  ... that turned out to be the problem. 

This doesn't explain the bug, but a workaround is to run Atom from Spotlight.

**Comment by ThatXliner** [comment] 2021-01-01 02:18
May you close this issue to reduce duplicate issues?

**Comment by DeeDeeG** [comment] 2021-01-07 17:24
Sometimes when I launch a build of Atom I've never run before, it starts with no window open and it doesn't respond to anything I try to do. Then quit Atom, and launch it again. It seems to work pretty often just quitting once and re-launching.

Sadly this is going to be a bit hard to debug, because you need to explicitly run with the `--inspect` or --inspect-brk` flags to capture what's going on, and without easy steps to reproduce you have to be a little bit psychic or lucky, or only even launch Atom in `--inspect-brk` mode...

Hmm.

**Closed** 2021-01-18 16:22 UTC
