### ISSUE TITLE
Uncaught Error: error: 126/\?\~\AppData\Local\atom\app-1.21.1\resources\app.asar.unpacked\node_mo...

### ISSUE THREAD

**Issue by FuriosoJack** [atom/atom#15877] opened 2017-10-12 17:18 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 126\\?\C:\Users\Juan\AppData\Local\atom\app-1.21.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: error: 126\\?\C:\Users\Juan\AppData\Local\atom\app-1.21.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:06.6.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -2:06.6.0 editor:newline (input.hidden-input)
     -2:06.5.0 intentions:highlight (input.hidden-input)
     -2:05.9.0 core:save (input.hidden-input)
     -1:51.3.0 core:backspace (input.hidden-input)
     -1:50.7.0 intentions:highlight (input.hidden-input)
     -1:50.4.0 core:save (input.hidden-input)
  2x -1:43.7.0 core:move-down (input.hidden-input)
     -1:43.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:43 editor:select-to-end-of-line (input.hidden-input)
     -1:42.7.0 core:delete (input.hidden-input)
     -1:42.3.0 core:move-up (input.hidden-input)
     -1:42.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:41.8.0 core:delete (input.hidden-input)
     -1:35.1.0 intentions:highlight (input.hidden-input)
     -1:34.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
acid-syntax 1.0.0 
activate-power-mode 2.6.0 
acute-syntax 1.0.0 
api-docs 0.0.6 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-material-ui 2.0.5 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
color-picker 2.2.5 
dun-syntax 0.4.0 
emmet 2.4.3 
file-icons 2.1.13 
git-plus 7.10.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
indent-guide-improved 1.4.13 
intentions 1.1.5 
koi-syntax 0.1.0 
language-blade 0.36.0 
laravel 0.7.1 
linter 2.2.0 
linter-htmlhint 1.3.4 
linter-php 1.5.1 
linter-ui-default 1.6.10 
Lux-Syntax 2.0.0 
merge-conflicts 1.4.5 
min-syntax 1.1.0 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
Neka-Syntax 1.0.1 
php-integrator-autocomplete-plus 1.6.0 
pigments 0.40.2 
pop-syntax 0.3.0 
rad-syntax 0.4.0 
Remote-FTP 1.0.0 
seti-syntax 1.1.3 
```

**Comment by rsese** [comment] 2017-10-12 20:42
Though the error message is different, I think this might be a duplicate of recent issues like https://github.com/atom/atom/issues/15722.  If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled.  If you don't have any anti-virus software, let me know.

**Closed by rsese** 2017-10-12 20:42 UTC

**Comment by FuriosoJack** [comment] 2017-10-13 12:42
This error appears after an hour install a plugin, I am trying to identify which was, and uninstall the atom and I have the folders of my profile analyzing in search of some amenzada

**Comment by FuriosoJack** [comment] 2017-10-13 12:49
the only strange thing is that I have a .link file and analyzing it with total virus I have the following result
![image](https://user-images.githubusercontent.com/26976637/31546899-e7bf59da-afea-11e7-8f79-ca477eab3dca.png)

also reviewing the history find configuration files pointing to a host

**dump.theadvancedcalendar.com**

**Comment by FuriosoJack** [comment] 2017-10-13 12:51
![image](https://user-images.githubusercontent.com/26976637/31547021-5d88121a-afeb-11e7-9a64-ba4f93792c26.png)

**Comment by FuriosoJack** [comment] 2017-10-13 12:54
opening the .link information with a notepad looks


` i d   " a t o m ( P r e v i e w F o r c e L o a d M e t a d a t a )     a c c e s s i b l e   " t r u e     a c c r o l e   " p u s h b u t t o n   / > 
 
 < / E l e m e n t > 
 
 < E l e m e n t   r e s i d   " P r e v i e w M e t a d a t a S p a c e r     i d   " a t o m ( P r e v i e w M e t a d a t a S p a c e r )   / > 
 
 < E l e m e n t   r e s i d   " P r e v i e w I t e m C o u n t T i t l e     l a y o u t   " b o r d e r l a y o u t ( )   > 
 
 < M e t a d a t a L a b e l   l a y o u t p o s   " L e f t     i d   " a t o m ( I t e m C o u n t L a b e l )     a c t i v e   " i n a c t i v e   / > 
 
 < / E l e m e n t > 
 
 < E l e m e n t   r e s i d   " P r e v i e w M e t a d a t a T i t l e     l a y o u t   " b o r d e r l a y o u t ( )   > 
 
 < M e t a d a t a E l e m e n t   l a y o u t p o s   " L e f t     i d   " a t o m ( P r e v i e w M e t a d a t a T i t l e C o n t r o l )     l a y o u t   " b o r d e r l a y o u t ( )   / > 
 
 < / E l e m e n t > 
 
 < E l e m e n t   r e s i d   " P r e v i e w M e t a d a t a S u b T i t l e     l a y o u t   " b o r d e r l a y o u t ( )   > 
 
 < M e t a d a t a E l e m e n t   l a y o u t p o s   " L e f 9   $    A u t o l i s t C a c h e T i m e   @    )Ž”‘CÓ§   "    A u t o l i s t C a c h e K e y      9   R e s u l t a d o s   d e   l a   b ú s q u e d a   e n   e l   m e n ú   I n i c i o   e n   A r c h i v o s 0               tY^–ßÓHg3¼î(ºgs3Ù
EæJÍ.”þ        d          f i l e s       J   1SPS¦jc(=•ÒµÖ ÀOÙÐ            0             S t a c k       ©  1SPS@è>+¼lG‚7*Íƒ›"Í      B      p r o p 4 2 9 4 9 6 7 2 9 5     •  ‘    1SPSÕÍÕœ.“— +,ù®!       K e y : P I D      d   ‘       C o n d i t i o n   B      p r o p 4 2 9 4 9 6 7 2 9 5     G   ‰\ñRZáH»ÍF£øœ|Â    =;ÑK‹æìD‰îvx@pd          f i l e s            u       K e y : F M T I D      N   { 4 B D 1 3 B 3 D - E 6 8 B - 4 4 E C - 8 9 E E - 7 6 1 1 7 8 9 D 4 0 7 0 }     /   
    N a m e         A r c h i v o s        
    T y p e                                      %          	   A r c h i v o s                  u          1   { 2 5 2 5 6 C 2 4 - 3 B 7 5 - 4 9 B 3 - A 4 3 3 - 4 B B 2 F 8 8 6 5 8 9 6 } . M e r g e   A n y         1   1SPSM‘ƒpÂ¿H°
NEP   d                          (   	      1SPSâŠXF¼L8C»ü“&˜mÎ            `

**Comment by brunotda** [comment] 2017-10-14 17:24
**Copy the file from the previous version:**
C:\Users\_Your_User_\AppData\Local\atom\app-**1.21.0**\resources\app.asar.unpacked\node_modules\keyboard-layout
**to**
C:\Users\_Your_User_\AppData\Local\atom\app-**1.21.1**\resources\app.asar.unpacked\node_modules\

**Comment by DavidWebcreate** [comment] 2017-10-14 23:12
Como resolver este problema, alguien que escriba en español.

**Comment by FuriosoJack** [comment] 2017-10-15 01:30
Amigo la causa probablemente sea un plugin que instalaste que puede que sea un virus mi solucion fue desintalar atom y volver a  instalarlo borrando la carpeta personal de atom. Pero puedes probar haciendo lo que comento brunotda

**Comment by DavidWebcreate** [comment] 2017-10-15 23:49
Vale, gracias.
