### ISSUE TITLE
HTML commenting for a `<script>` tag does `//` comment first

### ISSUE THREAD

**Issue by RanadeepPolavarapu** [atom/atom#8029] opened 2015-07-22 17:16 UTC
When trying to comment out a `<script>` tag it adds the `//` JavaScript style comments first and then if you hit `Ctrl + /` then it will do HTML style comments. All other standard HTML tags will be commented out right, it's just `script` tags that are not being commented on the first hit.

Why does this happen? Shouldn't it just do standard HTML style commenting on script tags?

**Comment by mnquintana** [comment] 2015-07-22 17:22
Thanks for the report! This is a duplicate of https://github.com/atom/language-html/issues/4 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-22 17:22 UTC
