### ISSUE TITLE
pane drag bars active in the wrong panes

### ISSUE THREAD

**Issue by sneiman** [atom/atom#10121] opened 2015-12-18 16:49 UTC
Atom 1.31, 1.32 on OSX 10.10.5:
If i split the screen vertically, and then split the upper pane horizontally, the upper panes 'drag' bars are active in the lower pane. They do not show visually, but the cursor changes and I can drag them.

To recreate:
open a new window.
split vertically
click on upper pane
split horizontally
You should have 3 panes now - something like this:
![3panes](https://cloud.githubusercontent.com/assets/4030906/11902009/d0e3e8cc-a563-11e5-9c0b-411387b14c7b.png)

NOW - hover the cursor in the LOWER pane in line horizontally with the split line between the panes in the upper half of the window. You will see the cursor change to the pane split double arrow, and if you click and drag you can change the pane size of the upper pane.

**Comment by mnquintana** [comment] 2015-12-18 18:08
Just out of curiosity, can you reproduce this if you quit Atom completely and start it in safe mode? (`atom --safe`)

**Comment by Ben3eeE** [comment] 2016-04-08 09:22
I can reproduce this in safe mode on windows 7 atom 1.6.2 by following the steps.
See gif of reproduction in action:
![kcfre94ycp](https://cloud.githubusercontent.com/assets/1058982/14379677/8289b89e-fd7b-11e5-842c-fcdb29ebb1dd.gif)

**Comment by 50Wliu** [comment] 2016-04-25 16:35
Closing as a duplicate of #7446.

**Closed by 50Wliu** 2016-04-25 16:35 UTC
Labels: more-information-needed, needs-reproduction
