### ISSUE TITLE
auto indent for C/C++ is frustrating

### ISSUE THREAD

**Issue by liangjs** [atom/atom#16346] opened 2017-12-08 05:51 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I find the behavior of atom's auto indent for C/C++ a little bit frustrating.
When I press enter to create a new line, atom always indents exactly as the previous line (except when the previous line ends with an opening bracket), that is, insert the same number of spaces or tabs as the previous line at the beginning of the new line, in front of the cursor.
But I'd like to say this is not a very satisfying indent policy.
See the following comparison between atom and vim.

**Expected behavior:** 

Vim indents for the line after 'if (xx)', waiting for a statement for the 'if'.
If you type in a '{' now, vim will indent backward.
![vimif](https://user-images.githubusercontent.com/10512425/33752780-bb68f480-dc1e-11e7-8ce7-21ec9bc52e83.png)
![vimif2](https://user-images.githubusercontent.com/10512425/33752785-bec45aac-dc1e-11e7-9a63-1e1e8a78eb85.png)

**Actual behavior:**

But atom just indents the same as the previous line.
![atomif](https://user-images.githubusercontent.com/10512425/33752789-c67e21a6-dc1e-11e7-99a1-6935f11ffc28.png)

**Expected behavior:** 

Vim behaves fairly well even in some cases like this.
![vimcout](https://user-images.githubusercontent.com/10512425/33752793-cc6b369e-dc1e-11e7-95f4-333edcfc1a6c.png)

**Actual behavior:**

But atom not.
![atomcout](https://user-images.githubusercontent.com/10512425/33752797-d18c3c5e-dc1e-11e7-835c-5d312b2ee887.png)

**Reproduces how often:** always.

### Versions

atom 1.22.1
apm  1.18.11
os: Archlinux

### Comments

Is there any way to improve atom's indent behavior?
Or will the atom team improve it someday?

**Comment by rsese** [comment] 2017-12-08 21:07
Thanks for taking the time to contribute!  The first issue you mentioned is a duplicate of https://github.com/atom/language-c/issues/96, you can subscribe there for updates if you'd like. 

Improving auto-indent is something the team would like to improve, but there's no specific timeframe for that to happen.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-08 21:07 UTC
