### ISSUE TITLE
Multiple useless "apm" processes is generated

### ISSUE THREAD

**Issue by Michal-Mikolas** [atom/atom#13482] opened 2016-12-21 10:43 UTC
### Description

Multiple "apm" processes is run, even if I don't install / uninstall any packages to Atom. Even if i close all Atom windows, "apm" processes is still running. 

Screenshot from today: 
![apm-memory-leak](https://cloud.githubusercontent.com/assets/900316/21385721/f4dfb128-c76f-11e6-9c03-f85efbd23f2f.png)

Yesterday, I had tens of "apm" processes running, which eated more than 1 GB of RAM. I had to do hard-reset of my computer. 

### Steps to Reproduce

1. Open Atom editor. 
2. Open few new instances of Atom editor again. 
3. Close all Atom's windows except the first one. 

**Expected behavior:** No "apm" process should run, if I don't play with instaling / uninstaling / searching packages. 

**Actual behavior:** Several "apm" processes is runing. 

### Versions

Atom 1.12.7; Linux Mint 17.2

**Comment by thomasjo** [comment] 2016-12-21 14:28
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by thomasjo** [comment] 2016-12-21 14:31
You omitted filling in the _prerequisites_ section, which specifically asks you whether you're able to reproduce your problem in safe mode...

Assuming you're running an official distribution of Atom (downloaded from atom.io), your problem is guaranteed to be caused by an installed community package. Therefore, the problem will not be reproducible in safe mode, and hence why we ask that you perform the safe mode check.

**Comment by Michal-Mikolas** [comment] 2016-12-21 18:45
I am sorry about missing informations. Now I tried it with safe mode on, so these are new informations. I also updated "Steps to reproduce", now more specific. 

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?


### Description

Multiple "apm" processes is run, even if I don't install / uninstall any packages to Atom. Even if i close all Atom windows, "apm" processes is still running. 

Screenshot from today: 
![apm-memory-leak](https://cloud.githubusercontent.com/assets/900316/21385721/f4dfb128-c76f-11e6-9c03-f85efbd23f2f.png)

Yesterday, I had tens of "apm" processes running, which eated more than 1 GB of RAM. I had to do hard-reset of my computer. 


### Steps to Reproduce

1. Open Atom editor in safe mode => No "apm" process is run. (OK)
2. Open new Atom editor window via CTRL+SHIFT+N => No "apm" process is run. (OK)
3. In that new window, via CTRL+SHIFT+O open folder with some project => Two "apm" processes is running. (BUG)
4. Open new Atom editor window via CTRL+SHIFT+N => Still 2 "apm" processes.  (BUG)
5. In that new window, via CTRL+SHIFT+O open folder with another project => Now 4 "apm" processes are running.  (BUG)
6. Close all Atom windows => Still 4 "apm" processes are running.  (VERY BUGGY :-) )

**Expected behavior:** No "apm" process should run, if I don't play with instaling / uninstaling / searching packages. 

**Actual behavior:** Several "apm" processes are running. 

### Versions

Atom 1.12.7; Linux Mint 17.2

**Comment by 50Wliu** [comment] 2016-12-21 18:53
What is the output of `atom --version`?

**Comment by Michal-Mikolas** [comment] 2016-12-21 18:58
```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by lee-dohm** [comment] 2016-12-23 19:39
@Michal-Mikolas Is the new window running in Safe Mode? Can you reproduce the bug in Safe Mode at all? It could be that a package you have installed is starting those rogue apm processes.

**Comment by lee-dohm** [comment] 2017-01-28 22:48
Thanks for taking the time to contribute!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13482#issuecomment-269036429. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by lee-dohm** 2017-01-28 22:48 UTC
Labels: more-information-needed, needs-reproduction
