### ISSUE TITLE
Cutting a few thousand selections: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Splitlocked** [atom/atom#11560] opened 2016-04-21 14:01 UTC
This also occurs in safe mode.
Every attempt to reproduce succeeds for me.
I've search for previously reported issues but found none that match my situation.
After the error report appears I can continue to use Atom as usual with no harm done apparently.

To reproduce:

1. Open a text file with 13000 lines, with lines alternating between 18 printables and one tab character
2. Ctrl+F
3. Do RegExp search for ^[^\s]+.*$
4. Press Alt+Enter to select every line that is not a line with just a tab character
5. Ctrl+X
6. Wait.
7. "Editor is not responding" => "Keep Waiting"
8. Wait.
9. The error occurrs

**Atom Version**: 1.7.2
**System**: Ubuntu 15.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/atom-patch/dist/patch.js:250

RangeError: Maximum call stack size exceeded
    at Patch.changesForSubtree (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/atom-patch/dist/patch.js:250:38)
    at Patch.changesForSubtree (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/atom-patch/dist/patch.js:256:12)
(the above line repeats 5920 times)
    at Patch.replaceChangedText (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/atom-patch/dist/patch.js:231:31)
    at Patch.splice (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/atom-patch/dist/patch.js:201:59)
    at Function.compose (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/atom-patch/dist/patch.js:52:27)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1370:64
```

### Commands

```
     -2:02.1.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -2:01.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:00.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:59.8.0 core:select-all (atom-text-editor.editor.is-focused)
  5x -1:54.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:52.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:52.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:50.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:33.3.0 find-and-replace:find-all (atom-text-editor.editor.mini.is-focused)
     -1:29.4.0 core:cut (atom-text-editor.editor.is-focused)
     -0:29.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:27.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:27 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:27 core:cancel (atom-text-editor.editor.is-focused)
     -0:27 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:27 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
package-sync-plus, v0.1.2

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2016-04-21 20:19
This is a duplicate of https://github.com/atom/atom/issues/5025. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-04-21 20:19 UTC

**Comment by jasongutt** [comment] 2016-05-10 13:09
My editor just crashed

**Comment by dreamstarter** [comment] 2016-06-01 13:59
Steps the caused the error:

1. Opened Atom

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:219

RangeError: Maximum call stack size exceeded
    at Array.indexOf (native)
    at Object._.contains._.include (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:219:68)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:275:14)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
    at GrammarRegistry.module.exports.GrammarRegistry.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar-registry.js:180:23)
    at Grammar.module.exports.Grammar.grammarUpdated (C:\Users\bryan.anderson\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\first-mate\lib\grammar.js:279:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-edit",
      "SFTP-deployment",
      "file-type-icons",
      "linter-cflint",
      "open-recent",
      "seti-icons",
      "linter"
    ],
    "projectHome": "C:\\ColdFusion11\\cfusion\\wwwroot",
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ]
  },
  "editor": {
    "fontFamily": "Consolas",
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode-delete, v0.6.1
autoclose-html, v0.23.0
highlight-selected, v0.11.2
language-cfml, v0.12.0
linter-csslint, v1.3.2
minimap, v4.23.5
monokai-seti, v0.7.0
Remote-FTP, v0.8.3

# Dev
No dev packages
```

**Comment by lorenzoambrosi** [comment] 2016-11-15 16:38
Same error here, here's my callstack:

[Enter steps to reproduce below:]

1. Open Atom
2. Write stuff

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:507

RangeError: Maximum call stack size exceeded
    at Array.filter (native)
    at KeymapManager.module.exports.KeymapManager.findPartialMatches (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:507:57)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:332:29)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:565:14)
[...] Bunch of identical type errors
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:423:21)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  8x -1:30.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:28.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:28.2.0 core:select-up (atom-text-editor.editor.is-focused)
  2x -1:27.9.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -1:26.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:26.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:25.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:20.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:20.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:20.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:19.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:19.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  4x -1:18 core:move-down (atom-text-editor.editor.is-focused)
     -1:16.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:12.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:select-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "editor": {
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
atom-ternjs, v0.16.1 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
platformio-ide-terminal, v2.2.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2016-11-15 16:42
@lorenzoambrosi Do you have anything in your `keymap.cson`?

**Comment by grahamb** [comment] 2016-11-16 00:49
I'm also getting this.

I do have entries in `keymap.cson`:

```
'atom-text-editor':
  'home': 'core:move-to-top'
  'end': 'core:move-to-bottom'


'.platform-darwin atom-workspace':
  'shift-cmd-T': 'platformio-ide-terminal:new'
  'ctrl-=': 'platformio-ide-terminal:toggle'
```
1. Open atom
2. Type things

**Atom Version**: 1.12.3
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: Atom Core

Stack trace et al at https://gist.github.com/grahamb/1030b950b9ecfcc023d606f12097c50e.

**Comment by grahamb** [comment] 2016-11-16 19:03
I commented out the contents of `keymap.cson` but I'm still getting frequent hangs.

**Comment by Ben3eeE** [comment] 2016-11-16 21:50
Hey, https://github.com/atom/atom/issues/13181 is the issue for this. If you can take a look at my [comment](https://github.com/atom/atom/issues/13181#issuecomment-261083392) there and investigate that would be appreciated, thanks.

**Comment by grahamb** [comment] 2016-11-16 23:58
Thanks, I'll move over there. I ended up on this issue because Atom told me the bug had already been reported and directed me here ;)

**Comment by Ben3eeE** [comment] 2016-11-17 07:10
Yeah, Atom likes to direct users to the wrong issues sometimes :slightly_smiling_face: Thank you very much for the provided information it is very appreciated :bowing_man:
