### ISSUE TITLE
Keyboard shortcut "ALT GR" + "G" (prints slash "/") doesn't work

### ISSUE THREAD

**Issue by rodrigocprates** [atom/atom#7972] opened 2015-07-19 22:09 UTC
Simply when I use keyboard shortcut ALT GR + G it doesn't print "/".

**Comment by mnquintana** [comment] 2015-07-19 22:10
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom-keymap/issues/35 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-19 22:10 UTC

**Comment by rodrigocprates** [comment] 2015-07-20 01:43
solved by installing keyboard-localzation atom package (https://github.com/andischerer/atom-keyboard-localization)
