### ISSUE TITLE
Stop  highlight text  after some characters 

### ISSUE THREAD

**Issue by burhandodhy** [atom/atom#10083] opened 2015-12-16 07:17 UTC
After some number of character atom stop highlight the text .. currently im using one dark theme  but this problem in other themes as well .. 

![screenshot_13](https://cloud.githubusercontent.com/assets/7139602/11834495/d2f00ebe-a3ee-11e5-8bf0-7d1242f7f83d.png)

**Comment by Zireael07** [comment] 2015-12-16 08:42
Duplicate of #1667

**Comment by 50Wliu** [comment] 2015-12-16 16:44
Thanks @Zireael07!

**Closed by 50Wliu** 2015-12-16 16:44 UTC
