### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 300Error: Cannot cal...

### ISSUE THREAD

**Issue by massic80** [atom/atom#17576] opened 2018-06-25 14:46 UTC
[Enter steps to reproduce:]
(I don't know whether it's reproducible)
1. I had Atom on fullscreen on the secondary display
2. I detached it and moved it to the primary display (don't remember whether directly follscreen or not)
3. the error popped up

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Windows 10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 300
Error: Cannot call function 'getPosition' on missing remote object 300
    at throwRPCError (C:\Users\m.caniparoli\AppData\Local\atom\app-1.28.0\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\m.caniparoli\AppData\Local\atom\app-1.28.0\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\m.caniparoli\AppData\Local\atom\app-1.28.0\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At C:\Users\m.caniparoli\AppData\Local\atom\app-1.28.0\resources\electron.asar\renderer\api\remote.js:209

Error: Cannot call function 'getPosition' on missing remote object 300
Error: Cannot call function 'getPosition' on missing remote object 300
    at throwRPCError (~/AppData/Local/atom/app-1.28.0/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.28.0/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.28.0/resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (~/AppData/Local/atom/app-1.28.0/resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (~/AppData/Local/atom/app-1.28.0/resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.28.0/resources/electron.asar/renderer/api/remote.js:113:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.28.0/resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.28.0/resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowResize (~/AppData/Local/atom/app-1.28.0/resources/app/src/window-event-handler.js:195:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-ide-ui 0.12.0 
atom-live-server 2.3.0 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.21 
git-time-machine 2.1.0 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-typescript 0.7.6 
intentions 1.1.5 
jshint 1.8.6 
language-ejs 0.4.0 
linter 2.2.0 
linter-package-json-validator 2.0.0 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-ui-default 1.7.1 
local-history 4.3.1 
prettier-atom 0.54.0 
react 0.18.0 
split-diff 1.5.2 
tasks 2.10.1 
teletype 0.13.3 
todo-show 2.3.0 
w3c-validation 0.4.0 
```

**Comment by rsese** [comment] 2018-06-25 19:17
Thanks for the report!

This looks like a duplicate of #16630 so you can subscribe there for updates if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-06-25 19:17 UTC
