### ISSUE TITLE
local atom Release Notes is outdated

### ISSUE THREAD

**Issue by Heather** [atom/atom#9713] opened 2015-11-20 08:12 UTC
Windows 10

Atom 1.2.3

In local Release Notes recent version is 1.1.0

**Comment by thorade** [comment] 2015-11-20 08:44
Same problem here, see screenshot below.
I can click the "Restart and update" button as often as I want, nothing changes.

![atom_releasenotesoutdated](https://cloud.githubusercontent.com/assets/314571/11295329/0c95fc3e-8f6b-11e5-8bb9-aeedbf4d75d6.png)

**Comment by davidspiess** [comment] 2015-11-20 08:50
Same here with 1.2.3 on Windows 8

**Comment by fmaida** [comment] 2015-11-20 09:35
I  can also confirm this problem on Mac OS X 10.11.1

**Comment by ashrayjain** [comment] 2015-11-20 10:21
Same issue on Mac OS X 10.10.5 with Atom 1.2.3

**Comment by Alhadis** [comment] 2015-11-20 11:07
Oh geez, I'm glad I'm not the only one having this issue. I actually just reinstalled Atom thinking it was only a problem on my end...

Whew, guess I'm not crazy, then.

**Comment by mnquintana** [comment] 2015-11-20 12:37
Thanks for the report! This is a duplicate of https://github.com/atom/release-notes/issues/39 - feel free to subscribe there for updates.

**Closed by mnquintana** 2015-11-20 12:37 UTC
