### ISSUE TITLE
Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog'    at Function.Module._resolveFilename (module.js:351:15)    at Function.Module._load (module.js:293:25)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

### ISSUE THREAD

**Issue by Tedko** [atom/atom#5947] opened 2015-03-12 01:38 UTC
[Enter steps to reproduce below:]

1. ...Install Shell Command

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77

Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
  at metaToValue (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77:15)
  at Object.exports.require (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:157:34)
  at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:698:23)
  at /Applications/Atom.app/Contents/Resources/app/src/command-installer.js:73:29
  at /Applications/Atom.app/Contents/Resources/app/src/command-installer.js:102:11
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
     -0:14.4 core:close (div.settings-view.pane-item)
     -0:01.4 window:install-shell-commands (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "color-gutter",
      "linter"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 20
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-color-highlight, v3.0.8
autocomplete-plus, v2.4.2
color-picker, v1.4.4
file-icons, v1.5.1
language-arm, v0.3.0
language-aspx, v0.2.0
language-x86, v0.1.0
minimap, v4.6.0
open-last-project, v0.3.4
vim-mode, v0.37.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-12 12:01
Duplicate of atom/tree-view#399, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-12 12:01 UTC
