### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/admin/Documents/workspace/coachcommune/components/web-site-app/WebSiteAppController.js'

### ISSUE THREAD

**Issue by kpgarrod** [atom/atom#6732] opened 2015-05-11 08:47 UTC
[Enter steps to reproduce below:]

1. Delete a file
2. Re-open atom project

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/admin/Documents/workspace/coachcommune/components/web-site-app/WebSiteAppController.js'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/Users/admin/Documents/workspace/coachcommune/components/web-site-app/WebSiteAppController.js'
    at Error (native)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "sublime-tabs",
      "atomatigit",
      "autocomplete-paths",
      "autocomplete-html",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-sql",
      "language-xml",
      "dev-live-reload",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-toml",
      "project-manager",
      "color-picker",
      "jumpy",
      "linter",
      "linter-tslint",
      "angularjs",
      "language-c",
      "language-clojure"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs-styleguide-snippets, v0.7.0
atom-typescript, v4.2.2
autocomplete-plus, v2.13.1
editorconfig, v1.0.0
emmet, v2.3.9
linter, v0.12.2
tag, v0.2.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-11 11:54
Duplicate of #6210, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-11 11:54 UTC
