### ISSUE TITLE
Pane resizer goes through other panes

### ISSUE THREAD

**Issue by JetLua** [atom/atom#11592] opened 2016-04-24 07:41 UTC
### screenshots
---
**os: windows 7**
**version: 1.7.2**

![screenshots](https://lufei.so/t.gif)

**Comment by 50Wliu** [comment] 2016-04-24 16:57
Reproduced on Atom 1.9.0-dev-9175194, Windows 10 x64.

**Comment by Ben3eeE** [comment] 2016-04-25 05:19
Duplicate of https://github.com/atom/atom/issues/10121?

**Comment by Ben3eeE** [comment] 2016-04-25 11:19
Also maybe https://github.com/atom/atom/issues/7446?

**Comment by 50Wliu** [comment] 2016-04-25 16:35
Closing as a duplicate of #7446 - thanks @Ben3eeE!

**Closed by 50Wliu** 2016-04-25 16:35 UTC
Labels: bug
