### ISSUE TITLE
Uncaught Error: spawn /Users/stuart/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Conten...

### ISSUE THREAD

**Issue by stuwilliams47** [atom/atom#10430] opened 2016-01-15 11:54 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/stuart/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/stuart/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
  at exports._errnoException (util.js:837:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at doNTCallback2 (node.js:441:9)
  at process._tickCallback (node.js:355:17)
  at EventEmitter.ipc.sendSync (/Users/stuart/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/stuart/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
  at Object.windowState (/Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
  at Object.plus.mapObject (/Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
  at Object.plus.deepClone (/Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
  at exports.getWindowLoadSettings (/Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:15:15)
  at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:170:22)
  at /Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
  at Function.module.exports.Emitter.simpleDispatch (/Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at Project.module.exports.Project.addPath (/Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
  at /Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:869:41
  at EventEmitter.<anonymous> (/Users/stuart/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -0:13.6.0 application:add-project-folder (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "csslint",
      "jshint"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 120,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-01-15 12:34
Hi @stuwilliams47, thanks for reporting!  This looks like a duplicate of #9559 though, so please subscribe there for updates!

**Closed by 50Wliu** 2016-01-15 12:34 UTC
