### ISSUE TITLE
Tabs open without showing the content of the file

### ISSUE THREAD

**Issue by gassius** [atom/atom#11632] opened 2016-04-27 22:18 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When clicking on a file in the project tree (single or double clicking) a tab is open with the name of the file (the name being in cursive if is one click, regular if is double-click) but the content of the file is not shown.

After a variable time, the content may be displayed. Sometimes is not displayed even after 2 min (the longest I have waited)

If the same file in the project tree is left-clicked and "Open in New Window" is selected, the content is displayed properly.

This has been tested with atom --safe option and after running atom --clear-window-state with similar results.

The problem don't seems to appear in the first file that is being opened. Only in files afterward.

### Steps to Reproduce

1. Open a file from the project's tree
2. Click on a second file of the project's tree (one or double-click)

**Expected behavior:** 
New tab should open and the file content should be displayed

**Actual behavior:** 
A tab is opened with the name of the file as title, but no content is displayed. Content may appear after a variable period of time or not appear at all.

### Versions

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

Ubuntu 14.04.4 LTS
4.2.0-35-generic GNU/Linux
6 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lee-dohm** [comment] 2016-04-27 22:26
I can't reproduce this using Atom v1.9.0-dev-c4d4e0f on Mac OS X 10.11.4 (or the latest Stable for that matter). I suspect that it has to do with either the content you're opening or from where you are opening it (presumably over a slow network connection). Can you give some more information along those lines?

**Comment by gassius** [comment] 2016-04-27 22:37
Simple .haml or .rb files (even under 1 Kb) in a local Vagrant instance, mounted as a simple gvfsd-fuse in the master OS.

Never had an issue before 1.7.2 with this setup.

However, based on your sugesstion I tried with some file in native fs of the master OS and the problem is still there, but only in about 25% of the cases

**Comment by gassius** [comment] 2016-04-27 22:40
I must add that after running atom --clear-window-state the problem don't seems to appear with the files in the local fs. 

It seems related then to the access via gvfsd-fuse.

**Comment by lee-dohm** [comment] 2016-04-27 22:43
Ok, that makes this a duplicate of https://github.com/atom/atom/issues/1766. You may want to take a look at this PR also that seems to have a workaround for these problems.

https://github.com/atom/atom/pull/11367

**Closed by lee-dohm** 2016-04-27 22:43 UTC
Labels: more-information-needed, needs-reproduction
