### ISSUE TITLE
atom hangs on opening js.map files

### ISSUE THREAD

**Issue by SampsonCrowley** [atom/atom#13337] opened 2016-11-27 00:41 UTC
### Prerequisites

* [y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Open any js.map file. atom hangs, then crashes.]

### Steps to Reproduce

1. [Open map file to make a quick edit instead of full rebuild]
2. [Atom hangs]
3. [Close Atom]
4. [Atom still hangs because of session]
5. [delete ~/.atom/storage and lose all open tabs you were working on]

**Expected behavior:** [Atom should be able to handle any development related file regardless of line length, if line length is a problem, force a soft wrap]

**Actual behavior:** [lost time and progress from force closing atom]

### Versions

v6.5.0

Arch Linux 

kernel 4.8.4-1

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by SampsonCrowley** [comment] 2016-11-27 00:43
the best solution here if you can't fix the long line issues is ad a disable storage flag to startup so I can clean start without having to manually wipe .atom/storage

**Comment by 50Wliu** [comment] 2016-11-27 01:15
There is a "delete window state" flag, which is clearly documented in the debugging guide (which you marked as having read): `atom --clear-window-state`.

As for the long lines issue, that is a duplicate of #979.  Feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-11-27 01:15 UTC
