### ISSUE TITLE
MacOS native character map doesn’t work with Atom

### ISSUE THREAD

**Issue by valtlai** [atom/atom#17180] opened 2018-04-19 19:19 UTC
### Description

When pressing Cmd Ctrl Space, the character map is usually displayed, but not in Atom.

![macos-character-map](https://user-images.githubusercontent.com/5496284/39013292-9824d4f8-441f-11e8-9af6-9e72f1aa4380.png)

### Steps to Reproduce

1. Open Atom.
2. Press Cmd Ctrl Space.

**Expected behavior:** The character map should appear and allow insert a character to the current caret position.

**Actual behavior:** Nothing happens.

**Reproduces how often:** Always.
### Versions

```sh
Valtteri-MBP:~ valtteri$ atom --version
Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
Valtteri-MBP:~ valtteri$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 2.7.10
git 2.15.1
Valtteri-MBP:~ valtteri$ 
```

**Comment by rsese** [comment] 2018-04-20 00:05
Thanks for contributing!

It looks like your system language is set to something other than English?  If so, I think this is a duplicate of https://github.com/atom/atom/issues/14963 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-20 00:05 UTC
