### ISSUE TITLE
Subpixel hinting problems on debian testing

### ISSUE THREAD

**Issue by rumpelsepp** [atom/atom#16109] opened 2017-11-06 07:06 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In the recent debian testing distribution there are problems with font rendering when subpixel hinting mode is enabled. `atom` seems to be the only application affected on my box; I use the official release .deb files from the atom website.

### Steps to Reproduce

1. start atom
2. open a text buffer

**Expected behavior:** Proper font rendering. :)

**Actual behavior:** Font Rendering is broken, see screenshots. It goes away when enabling grayscale hinting.

With subpixel hinting:
![screenshot from 2017-11-06 08-04-21](https://user-images.githubusercontent.com/1961699/32429030-1cfbdd44-c2c9-11e7-8ba6-98f96abc748f.png)

With grayscale hinting:
![screenshot from 2017-11-06 08-05-00](https://user-images.githubusercontent.com/1961699/32429054-3c0c2b6c-c2c9-11e7-886a-f816c680ec50.png)

**Reproduces how often:** Every time

### Versions

```
Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

and also:

```
Atom    : 1.22.0-beta2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

I use an up to date debian testing, with the standard gnome desktop installed. Here are the relevant font settings:
![screenshot from 2017-11-06 08-05-53](https://user-images.githubusercontent.com/1961699/32429089-58afeccc-c2c9-11e7-8fd3-d047572fbabf.png)
![screenshot from 2017-11-06 08-06-01](https://user-images.githubusercontent.com/1961699/32429090-58cda60e-c2c9-11e7-8dcd-20a2ce83750b.png)

**Comment by Ben3eeE** [comment] 2017-11-06 07:35
Thanks for reaching out!

Based on the screenshots you provided this looks like a duplicate of https://github.com/atom/atom/issues/15737. Please let me know if it isn't and I will be happy to reopen!

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15737. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-11-06 07:35 UTC
Labels: duplicate

**Comment by rumpelsepp** [comment] 2017-11-06 07:44
Thanks for the pointer! I did use the wrong search keywords. :-)
