### ISSUE TITLE
Unable to save any changes. 

### ISSUE THREAD

**Issue by harshattray** [atom/atom#15963] opened 2017-10-22 04:58 UTC
### Description

[Description of the issue]

Clicking on cmd+s on macOS doesn't save the changes. Instead throws an error when clicked on save as.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
atom version: 1.21.1
apm version: 1.18.5

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![screen shot 2017-10-22 at 10 21 47 am](https://user-images.githubusercontent.com/3311805/31858347-1d840816-b713-11e7-8fb9-3528b963630a.png)

**Comment by rsese** [comment] 2017-10-23 18:35
Thanks for the report - can you confirm which version of macOS you're running?  Also, it looks like the Prerequisites section of the issue template was removed, can you confirm if you can reproduce in safe mode (`atom --safe`)?  

Lastly, did this error just start after upgrading to Atom 1.21.1?

**Comment by sosnail** [comment] 2017-10-24 02:19
windows  cmd+s can't save
atom --safe is ok

**Comment by Zireael07** [comment] 2017-10-24 08:20
If it's fine with --safe, what packages do you have installed @sosnail ?

**Comment by harshattray** [comment] 2017-10-24 11:26
macOS version --10.12.6 and Yes the issue started post updating to 1.21.1. It works fine in safe mode

**Comment by Ben3eeE** [comment] 2017-10-24 11:30
@harshattray @sosnail Can you please provide the full output of `apm list`?

**Comment by harshattray** [comment] 2017-10-24 19:18
Attached the package list of apm

[package-list.txt](https://github.com/atom/atom/files/1412190/package-list.txt)

**Comment by harshattray** [comment] 2017-10-25 05:51
I can confirm that this seems to happen once we update npm from 5.4.1 to 5.5.1. 
![screen shot 2017-10-25 at 10 59 42 am](https://user-images.githubusercontent.com/3311805/31982001-03c7ef10-b974-11e7-8ef3-205165dbfb07.png)

I did an apm update 
![screen shot 2017-10-25 at 11 20 25 am](https://user-images.githubusercontent.com/3311805/31982454-9a0b5a28-b976-11e7-8c4d-b31e7e6a5484.png)

and restarted atom and everything seems to work fine now.

Still not sure which package broke it

**Comment by sosnail** [comment] 2017-10-25 11:10
thanks,the problem is in a package.

**Comment by rsese** [comment] 2017-10-25 21:14
Thanks @harshattray, glad things are working for you again.  One way to narrow things down is to disable all installed packages and then enable one-by-one.  Or if you a lot of installed packages, https://atom.io/packages/package-cop might be helpful too.  These approaches should be helpful for you too @sosnail.

I'll go ahead and close this issue for now though it would be interesting to hear what package caused the problem if you dig into that @sosnail.

**Closed by rsese** 2017-10-25 21:14 UTC
Labels: data-loss, more-information-needed, needs-reproduction
