### ISSUE TITLE
Issue when collapsing if blocks

### ISSUE THREAD

**Issue by Aermec** [atom/atom#15695] opened 2017-09-20 07:01 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When collapsing a if statement (javascript, C++ ...) Atom collapse also the end bracket even if it present a else statement. This creates problems reading the code.

### Steps to Reproduce

Write a code as: 
if (a == 2) {
  b = 1;
} else if (a == 1) {
  b = 2;
} else {
  b = 0;
}

**Expected behavior:** Collapse should include bracket (as now) if there isn't a else statement on the same line otherwise it should stop at the previous line

**Actual behavior:** Collapse hides the end bracket even if present a else statement creating a unreadable code

**Reproduces how often:** always

### Versions

1.20.1 x64 Windows

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![screenshot](https://user-images.githubusercontent.com/14887677/30630780-417a6458-9de2-11e7-886c-f266e023c32e.png)

**Comment by rsese** [comment] 2017-09-20 17:35
Thanks for the report - for C++, this is a duplicate of https://github.com/atom/language-c/issues/227 so you can subscribes for updates if you'd like.

I think folding issues like this might be language specific, in which case it would be helpful if you can open separate issues in https://github.com/atom/language-javascript too if there's no existing issue for it.

**Closed by rsese** 2017-09-20 17:35 UTC
