### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND gn-proxy0x...

### ISSUE THREAD

**Issue by neriai** [atom/atom#13964] opened 2017-03-09 00:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND gn-proxy0x.gndomain.gnavi.co.jp gn-proxy0x.gndomain.gnavi.co.jp:12080

```
At stream.js:74

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND gn-proxy0x.gndomain.gnavi.co.jp gn-proxy0x.gndomain.gnavi.co.jp:12080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1016:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -0:18.8.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.0 
atom-beautify 0.29.17 
atom-material-ui 1.3.9 
autocomplete-paths 1.0.5 
docblockr 0.9.1 
file-icons 2.0.17 
git-plus 7.3.3 
highlight-selected 0.12.0 
japanese-menu 1.9.0 
language-apache 1.7.0 
linter 1.11.23 
linter-csslint 1.3.4 
linter-jsonlint 1.3.0 
linter-php 1.3.1 
linter-tidy 2.3.0 
merge-conflicts 1.4.4 
minimap 4.26.8 
monokai 0.22.0 
php-cs-fixer 4.1.0 
project-manager 3.3.3 
regex-railroad-diagram 0.16.0 
show-ideographic-space 1.0.2 
Sublime-Style-Column-Selection 1.7.3 
tag 0.4.0 
```

**Comment by rsese** [comment] 2017-03-09 02:16
Can you confirm what you were doing when you saw the error?  Were you trying to install a package?

Also it looks like you'r using a proxy?

**Comment by steve2507** [comment] 2017-03-15 08:19
I'm on atom 1.15 on Windows 7 which to my knowledge supports using proxy settings on apm commands. The issue mentioned above happens for me when I update a (any) package through Settings->Update, when behind a proxy.
The same occurs when running `apm update <package>`.

`C:\Users\mv96ti>apm update file-icons
Request for package information failed: getaddrinfo ENOTFOUND atom.io atom.io:443`

Not sure if I should raise a seperate issue.

**Comment by rsese** [comment] 2017-03-15 18:28
@steve2507 - since your issue is reproducible and confirmed related to apm, can you open an issue in https://github.com/atom/apm?

**Comment by rsese** [comment] 2017-05-04 22:10
Thanks again for your issue @neriai!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/13964#issuecomment-285233984. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2017-05-04 22:10 UTC
Labels: more-information-needed
