### ISSUE TITLE
Atom command line always creates new files in a new window

### ISSUE THREAD

**Issue by ssbarnea** [atom/atom#14801] opened 2017-06-16 09:19 UTC
### Description

`atom new_file` will open the new file (that does not exist) in a new window instead of a new tab, creating a new Atom window. This does *not* happen if the file already exists.

### Steps to Reproduce

`atom some_new_file`

**Expected behavior:** [What you expect to happen]

Open the new file in a new *tab*

**Actual behavior:** [What actually happens]

Opens the new file in a new *window*.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.13.0

MacOS 10.12.5

Note: adding the `-n=false` didn't change the behaviour in any way.

**Comment by rsese** [comment] 2017-06-16 19:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/8030. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-16 19:15 UTC
