### ISSUE TITLE
Atom Helper using 100%+ of CPU

### ISSUE THREAD

**Issue by Dhrumin-Shah** [atom/atom#17587] opened 2018-06-26 15:54 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom Helper is using 100%+ of my CPU. It was doing this while Atom was idle, but I solved that by disabling Github integration. But now, even just scrolling down an HTML file brings Atom Helper's CPU usage back up to 100%+

### Steps to Reproduce

1. Run Atom with Github integration disabled
2. Open a file
3. CPU usage skyrockets

**Expected behavior:** Very low to 0% CPU usage from Atom Helper

**Actual behavior:** Extremely high usage

**Reproduces how often:** Always

### Versions

Atom: 1.28.0
APM: 1.19.0
OS: macOS High Sierra 10.13.5

### Additional Information

I only have the core packages because I also did a fresh install to try to solve this.

**Comment by steveward** [comment] 2018-06-26 19:31
Thanks for opening this @Dhrumin-Shah. Do you possibly have a `.git` folder in your home directory? You can check that by running this command from the Terminal:

`ls -ld ~/.git`

Let me know if that is the case.

**Comment by Dhrumin-Shah** [comment] 2018-06-26 20:09
Yes I do have a `.git` folder in my home directory

**Comment by Zireael07** [comment] 2018-06-27 05:52
In that case it's a duplicate of existing issue. Can't recall the # though

**Comment by steveward** [comment] 2018-06-27 17:19
@Dhrumin-Shah thanks for the update. Did you intentionally create the .git directory in this location? To resolve the high CPU usage issue, you will either need to rename that .git directory or move it to a new location outside of your home directory using the `mv` command:

`mv ~/.git > ~/.git_backup`
or
`mv ~/.git > ~/path/to/another/directory/.git`

Let me know if that does not resolve this issue for you.

**Comment by Dhrumin-Shah** [comment] 2018-06-27 20:11
@steveward renaming the .git folder did bring the CPU usage down, but it is still high, spiking to around 30% from just scrolling in an HTML file.

**Comment by steveward** [comment] 2018-07-05 19:08
Thanks for the update @Dhrumin-Shah. Could you check to see if you still encounter ~30% CPU usage when running Atom in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by the-j0k3r** [comment] 2018-07-06 15:51
I would like to join a me too bandwagon.

![scroll cpu](https://user-images.githubusercontent.com/31389848/42388101-5480db66-813c-11e8-84f4-90a2b769b278.gif)

Atom in safe mode

BUt I dont have to scroll for that, idling does same or worst

![idlecpu](https://user-images.githubusercontent.com/31389848/42388240-ccc6d832-813c-11e8-9f2e-a2c116fb9732.gif)


```
Windows 10 pro 1803

> atom -v

Atom    : 1.28.1
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3

> apm -v

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.1
python 3.5.2
git 2.17.1.windows.2
visual studio
```

**Comment by AaronDinesh** [comment] 2018-07-30 21:47
How does one fully delete their local git directory or repository? I've used git in the past but i dont need it now so i would like to get it off my computer

**Comment by AaronDinesh** [comment] 2018-07-31 11:31
Also even when I run it in safe mode I still get the same high cpu usage and in my project I only have an index.html file and a javascript file. Even just by scrolling in the settings menu the helper takes about 35% cpu usage and sometimes higher. And its not even that I have an enormous amount of code like altogether between the two files I only have 70 lines of code.

**Comment by mazzarolg** [comment] 2018-09-28 08:28
> @Dhrumin-Shah thanks for the update. Did you intentionally create the .git directory in this location? To resolve the high CPU usage issue, you will either need to rename that .git directory or move it to a new location outside of your home directory using the `mv` command:
> 
> `mv ~/.git > ~/.git_backup`
> or
> `mv ~/.git > ~/path/to/another/directory/.git`
> 
> Let me know if that does not resolve this issue for you.

This did work for me. Thank you!

**Closed** 2018-10-02 12:16 UTC
Labels: more-information-needed

**Comment by kuehlriegecom** [comment] 2018-10-29 13:19
Dear team, I have also github deactivated and from time to time i see the Atom Helper eating up all my cpu resources available. Killing Atom and loading it right again solves the issue for me. Removing the git folder from the project is not an option for me. Please review the problem, i would be very happy if i can help.

**Comment by salvoc81** [comment] 2018-10-30 07:39
I am also having a issue, and Atom is becoming almost unusable... :(
NOTE: No new packages installed [OSX 10.13.6, Atom 1.32.0]

**Comment by mazzarolg** [comment] 2018-10-30 10:31
Do you have .git folder in your home folder plus in your project? If so, can you give a go renaming the git folder in your home directory as per below:
mv ~/.git > ~/.git_backup

**Comment by kuehlriegecom** [comment] 2018-10-31 10:44
> Do you have .git folder in your home folder plus in your project?
No, i have only a single .git folder in the folder tree: 
/Users/john/Documents/git/folder_with_.git/templates/files

Atom version: 1.32.0 x64.
MacOs version: 10.13.6 (17G65)

**Comment by karl-gustav** [comment] 2019-01-29 10:24
I have a .git folder in my home folder, and I want to keep having it. I use it to commit my config/bin files. Any workaround?

**Comment by PentagramPro** [comment] 2019-02-11 16:00
Have the same issue, git module is disabled, .git folder exists in project directory. However, I don't have .git folder in my home dir.

**Comment by SumNeuron** [comment] 2019-03-08 10:52
same

**Comment by iriosu** [comment] 2019-03-26 16:55
Same here. No .git in my home directory.

**Comment by kingmodus** [comment] 2019-03-26 17:14
I want to make a atom for my Android is there anything for it already ?

**Comment by jeffnyman** [comment] 2019-08-06 12:42
I'll add to the list. Atom helper is often pegging my CPU terribly on a Mac. I have no `.git` in my home directory. I have also tried using `atom --safe`. This is a problem that has been getting worse and worse from what I can see and what I have experienced.

**Comment by mqln** [comment] 2019-09-07 19:09
Also experiencing heinous CPU usage from an artifact of a session (now closed) of Atom. I thought I needed a new battery, but it was just Atom Helper!

**Comment by pinplex** [comment] 2019-09-19 08:51
> I'll add to the list. Atom helper is often pegging my CPU terribly on a Mac. I have no `.git` in my home directory. I have also tried using `atom --safe`. This is a problem that has been getting worse and worse from what I can see and what I have experienced.

I have to add to the list, too. Exact same problem.

**Comment by rsese** [comment] 2019-09-20 19:24
If you're seeing similar behavior can you open a new issue with the issue template filled out so we can take a look?  Any additional information would be helpful - for example, does it matter what project you have open?  What kind of files do you have open (plain text, JavaScript, etc)?  How big are the files?  Can you share a minimal example file or project that reproduces the behavior?  Besides safe mode, what other debugging steps have you tried?

**Comment by celamb4** [comment] 2019-09-25 14:37
+1 Atom helper eats up my CPU.

**Comment by tonyisblind** [comment] 2019-10-28 18:20
same issue report, v1.41.0, burning the CPU (8-core i9 MBP....)

**Comment by alfredodelfabro** [comment] 2019-11-06 22:43
same issue report, v1.41.0, MBP 2017 i7

**Comment by Prashantmdgl9** [comment] 2019-12-01 14:02
Atom helper take 100% CPU even on Macbook pro 2019 16 inches.
I removed the git from Atom(from packages) but the issue persists.

**Comment by lacostenycoder** [comment] 2019-12-17 02:30
This issue appears to be a regression.  Since this version Atom is eating my CPU badly! 

Here's example of the process hogging the CPU

```
4637M 62744 ?  0.0  0.7  0:07.07 Atom Helper --type=gpu-process  \
--enable-features=SharedArrayBuffer --disable-features=MacV2Sandbox \
--no-sandbox --gpu-preferences=KAAAAAAAAACAAAAAAQAAKAAAA[truncated] \
--service-request-channel-token=123412341234 
```

 Please reopen and fix!  Here are my specs:

```
Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
OS: MacOS 10.14.3
```

**Comment by melaniewilson** [comment] 2020-01-25 04:49
Same issue. Any update?

**Comment by jwohlfeil** [comment] 2020-01-27 15:35
I used to get it under control with these settings:
![Atom Settings](https://user-images.githubusercontent.com/443761/73188376-10d0c680-4123-11ea-8d1a-d01f7bc7a085.jpg)

**Comment by lacostenycoder** [comment] 2020-01-27 20:44
@melaniewilson When I had this problem recently, trying this seemed to help.
Quit Atom and then try running this from the terminal
`atom --clear-window-state`

**Comment by Gwanghyeon** [comment] 2020-03-18 10:48
I disabled github package and Atom Helper cpu plummeted almost to zero.

**Comment by newscloud** [comment] 2020-06-24 17:27
I am seeing this too. It's not stopping and it's making Atom unusable.

Restarting doesn't matter - Atom Helper goes back to 100%

**Comment by lacostenycoder** [comment] 2020-06-25 14:53
> I am seeing this too. It's not stopping and it's making Atom unusable.
> 
> Restarting doesn't matter - Atom Helper goes back to 100%

did you try `atom --clear-window-state` also are you using github package?

**Comment by ptica** [comment] 2020-07-02 07:57
I needed to disable the github package as well,
this issue should not be closed, as it still affects fresh installs and places a google burden on them to find this thread, read it, and disable the plugin?!

**Comment by Prashantmdgl9** [comment] 2020-07-09 09:23
What I would recommend is remove .git and .atom from root folder of your machine. Install atom again and don't use GitHub on atom and it should work.
run ls -lah command on your terminal to reveal hidden files
and then run rm -rf .git to remove git

Once you have atom without git, you can add git on your machine again, just don't connect git and atom.

**Comment by lacostenycoder** [comment] 2020-07-09 15:10
@Prashantmdgl9 I'm using Github on Atom without any issues. So why shouldn't others be able to?

**Comment by SumNeuron** [comment] 2020-07-09 17:04
@lacostenycoder there are many similar issues for this. Your linked "suggestion" was someone having their whole system accidentally under git. The "works for me" is the issue as many people encounter this suggesting it is wide spread  and can be triggered in several different ways.

**Comment by newscloud** [comment] 2020-07-28 01:32
Since this issue is closed. I open a new issue which repros for me even on a completely clean install. https://github.com/atom/atom/issues/21116

**Comment by raf187** [comment] 2021-03-16 17:38
> @Dhrumin-Shah thanks for the update. Did you intentionally create the .git directory in this location? To resolve the high CPU usage issue, you will either need to rename that .git directory or move it to a new location outside of your home directory using the `mv` command:
> 
> `mv ~/.git > ~/.git_backup`
> or
> `mv ~/.git > ~/path/to/another/directory/.git`
> 
> Let me know if that does not resolve this issue for you.

Thx a lot mate 💪🏽
