### ISSUE TITLE
Uncaught TypeError: Invalid Point: (190, NaN)

### ISSUE THREAD

**Issue by kevinyangliu** [atom/atom#16216] opened 2017-11-17 00:31 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (190, NaN)

```
At C:\Users\Administrator\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: (190, NaN)
    at Function.module.exports.Point.assertValid (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/display-layer.js:335:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/display-marker.js:154:58)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/cursor.js:60:37
    at Cursor.module.exports.Cursor.changePosition (~/AppData/Local/atom/app-1.22.1/resources/app/src/cursor.js:644:13)
    at Cursor.module.exports.Cursor.setScreenPosition (~/AppData/Local/atom/app-1.22.1/resources/app/src/cursor.js:58:25)
    at Cursor.module.exports.Cursor.moveLeft (~/AppData/Local/atom/app-1.22.1/resources/app/src/cursor.js:248:27)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/selection.js:244:37
    at Selection.module.exports.Selection.modifySelection (~/AppData/Local/atom/app-1.22.1/resources/app/src/selection.js:971:13)
    at Selection.module.exports.Selection.selectLeft (~/AppData/Local/atom/app-1.22.1/resources/app/src/selection.js:242:25)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor.js:2386:32
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor.js:2573:19
    at TextEditor.module.exports.TextEditor.mergeSelections (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor.js:2635:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor.js:2597:41)
    at TextEditor.module.exports.TextEditor.expandSelectionsBackward (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor.js:2565:25)
    at TextEditor.module.exports.TextEditor.selectLeft (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor.js:2385:25)
    at TextEditor.core:select-left (~/AppData/Local/atom/app-1.22.1/resources/app/src/register-default-commands.js:330:27)
    at HTMLElement.newCommandListeners.(anonymous function) (~/AppData/Local/atom/app-1.22.1/resources/app/src/register-default-commands.js:658:38)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.22.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:46.2.0 core:move-left (input.hidden-input)
     -0:45.8.0 core:move-right (input.hidden-input)
 32x -0:45.3.0 core:select-right (input.hidden-input)
 31x -0:43 core:select-left (input.hidden-input)
```

### Non-Core Packages

```
markdown-themeable-pdf 1.2.0 
pdf-view 0.61.0 
```

**Comment by rsese** [comment] 2017-11-17 02:19
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14774. You may want to subscribe there for updates - if you can share steps to reproduce, please let us know in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-17 02:19 UTC
