### ISSUE TITLE
Deprecation Cop: Check for duplicate issue before creating new

### ISSUE THREAD

**Issue by brylie** [atom/atom#6120] opened 2015-03-27 10:03 UTC
The Deprecation Cop encourages users to create issues on repositories when deprecated features are being used. This may lead to a lot of [duplicate issues](https://github.com/awatson1978/meteor-api/issues).

**Comment by 50Wliu** [comment] 2015-03-27 12:16
Duplicate of atom/deprecation-cop#21, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-27 12:16 UTC
