### ISSUE TITLE
Building Atom against Node.js 10 fails with error building dependency

### ISSUE THREAD

**Issue by karthanistyr** [atom/atom#17370] opened 2018-05-20 10:27 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Building Atom against Node.js 10.x fails while building one of the deep-nested dependencies `nan`, at least on linux.

```
../../nan/nan_maybe_43_inl.h:112:15: error: « class v8::Object » n'a pas de membre nommé « ForceSet »
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
```
This has to do with a dependency tree that eventually pulls `nan@2.7.0`.

The culprit seems to be `electron-link@0.2.0` ([atom/atom/script/package.json](https://github.com/atom/atom/blob/master/script/package.json)), which depends on `leveldown@^1.6.0` ([atom/electron-link/package.json](https://github.com/atom/electron-link/blob/master/package.json#L27)).

`leveldown@^1.6.0` is resolved as `leveldown@1.9.0` which itself requires `nan@~2.7.0` ([Level/leveldown/package.json](https://github.com/Level/leveldown/blob/8ed6aed0912f94ea81a96d1a74a701d6d2cc12fb/package.json#L38)).

It very well looks like nan was only changed to not use the deprecated `v8::Object::ForceSet` call [somewhere between v2.7.0 and v.2.8.0](https://github.com/nodejs/nan/commit/95cbb976d6fbbba88ba0f86dd188223a8591b4e7) (and only made it into a release in v2.8.0).

I have isolated the Node.js code change that removed the deprecated function, which now breaks `nan` for versions below v2.8.0 against Node.js 10, [at this commit](https://github.com/nodejs/node/commit/88786fecff336342a56e6f2e7ff3b286be716e47#diff-42f385dff7890b3c213d9699bcc350cc), tagged for Node.js v10.0.0 and v10.1.0.

Ideally I think the dependencies should be bumped up to the extent of what's possible, failing that the build requirements should limit the latest usable Node.js version to v9.x.

### Steps to Reproduce
Following instructions found at https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#platform-linux

1. Ensure environment is set to run node v10.x
```
% node --version
v10.1.0
```
2. Clone repository and start building according to instructions (link above). Don't forget to run the recommended platform/distro-specific commands (e.g. Arch Linux-specific)
3. Watch build fail while building `nan` (actual error will be buried under lots of node error output)

**Expected behavior:**
Build should succeed.

**Actual behavior:** 
Build fails while building a dependency (`nan@2.7.0`) due to its using a now-removed (as of Node.js 10), long-deprecated call to `v8::Object::ForceSet`.

**Reproduces how often:**
Always reproduces.

### Versions
```
 % atom --version
Atom    : 1.26.1
Electron: 1.8.4
Chrome  : 59.0.3071.115
Node    : 8.2.1
```

```
 % apm --version
(node:12736) ExperimentalWarning: The fs.promises API is experimental
apm  1.19.0
npm  6.0.1
node 10.1.0 x64
atom 1.26.1
python 2.7.15
git 2.17.0
```
### Additional Information

There seems to be no workaround other than making it so that Atom is somehow built against Node.js 9.x or below (e.g. setting up a docker build environment, a VM, or plain downgrading...). While this issue is not resolved, [the flight manual will state wrong requirements](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#requirements-1) (as it does not limit the upper version of a compatible Node.js):

> Requirements
 ...
 Node.js 6.x **or later** (we recommend installing it via nvm)

On a side note, I am the author of [this thread at discuss.atom.io](https://discuss.atom.io/t/can-atom-be-built-on-node-superior-to-v8-x/55341), but did not wait for a response to post this issue.

**Comment by Arcanemagus** [comment] 2018-05-21 17:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/electron-link/issues/11. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-05-21 17:13 UTC
