### ISSUE TITLE
Copy paste is causing crash

### ISSUE THREAD

**Issue by kateklemp** [atom/atom#4923] opened 2015-01-08 16:32 UTC
Copying code from another source and pasting into an untitled doc causes Atom to crash with no error message.  Still happening after restart.

Running Xubuntu 14.04

**Comment by kateklemp** [comment] 2015-01-08 16:34
Does not happen every time, however - seems unpredictable

**Comment by Fank** [comment] 2015-01-08 16:57
Maybe related issues: #4388 #4892

**Comment by mnquintana** [comment] 2015-01-08 18:43
What version of Atom?

**Comment by kevinsawicki** [comment] 2015-01-08 19:07
@kateklemp can you try upgrading to Atom 0.169 or above?

**Comment by TMiguelT** [comment] 2015-04-04 09:52
I'm getting this exact issue (copying code from another application, only occurs intermittently) on Ubuntu 14.04 with Atom 0.189

**Comment by ellioseven** [comment] 2015-04-04 10:38
I am also getting this issue on Ubuntu 14.0.4.2 with Atom .189

**Comment by justinbroweUCI** [comment] 2015-04-04 22:09
I am running into this issue as well using Ubuntu 14.0.4.2 and Atom 0.189.

**Comment by martinexner** [comment] 2015-04-05 11:17
Same here, Ubuntu 14.04, Atom 0.189.

**Comment by booti386** [comment] 2015-04-06 12:19
Same Ubuntu 14.04 Atom 0.189

**Comment by younessm** [comment] 2015-04-06 14:26
Same here too, Ubuntu 14.04 Atom 0.189

**Comment by alferov** [comment] 2015-04-06 19:22
Randomly crashes after copying from Chrome.
Tried on Ubuntu 14.04.1 and 14.04.2  / Atom 0.189

**Comment by AusIV** [comment] 2015-04-06 19:31
I'm also seeing this issue on Ubuntu 14.04 with Atom 0.189. The terminal from which I ran Atom eventually pops up with the error:

    [3732:0406/142311:WARNING:accelerator_util.cc(181)] Invalid accelerator token: 
    The program 'atom' received an X Window System error.
    This probably reflects a bug in the program.
    The error was 'BadWindow (invalid Window parameter)'.
      (Details: serial 787 error_code 3 request_code 40 minor_code 0)
      (Note to programmers: normally, X errors are reported asynchronously;
       that is, you will receive the error a while after causing it.
       To debug your program, run it with the --sync command line
       option to change this behavior. You can then get a meaningful
       backtrace from your debugger if you break on the gdk_x_error() function.)

Also worth noting, I can't copy and paste from Atom into other applications.

**Comment by AusIV** [comment] 2015-04-06 21:28
As a final note, downgrading to 0.188 seems to resolve this issue, so it definitely looks like something 0.189 caused the issue.

**Comment by dishcandanty** [comment] 2015-04-07 06:21
I'm seeing the same issue. openSuse 13.1 0.189. Annoying... Going to try to downgrade tomorrow.

**Comment by Fank** [comment] 2015-04-07 08:34
Same issue here on Ubuntu 14.10, tried to copy text out of RDP session in atom -> atom crashed.
Happens since 0.189

**Comment by lancekuttner** [comment] 2015-04-07 08:46
It does not appear to be theme-related. I disabled all themes that I had installed, restarted Atom and same occurs. I think I noticed that if you select a block of text, the highlighting appears as a full block highlight and not as individual rows (sorry if this doesn't make sense - I can't even be sure if this is a difference or not).

**Comment by theblacklion** [comment] 2015-04-07 14:13
Today I updated to 0.189 and also getting the crashes - either by copying stuff from Atom window to window or by pasting something from Chrome into Atom. Also cannot copy from Atom to terminal or Chrome.

**Comment by izuzak** [comment] 2015-04-07 14:44
This looks very similar to #6221 which makes me think it's a duplicate of that issue. That issue should be fixed in the next release of Atom (probably out later today), but please let us know if you can still reproduce this in 0.190.0 once it's released! Thanks for all the reports.

**Closed by izuzak** 2015-04-07 14:44 UTC
Labels: bug, crash, linux

**Comment by theblacklion** [comment] 2015-04-08 07:27
No crashes here anymore - thanks!

**Comment by kateklemp** [comment] 2015-04-09 04:06
Mine's all fixed, too!

**Comment by poveda-ruiz** [comment] 2015-04-10 15:07
Im using atom 0.190 in debian jessie RC2 and still crashes randomly when I paste something from other window
