### ISSUE TITLE
Duplicate line should be more robust; duplicate line or selection

### ISSUE THREAD

**Issue by axefrog** [atom/atom#11283] opened 2016-03-26 03:39 UTC
When no selection exists, or an entire line is selected, the _duplicate line_ feature works as expected. If I select only a portion of a line though, _duplicate_ should duplicate only that section of text, placing the copy directly at the end of the selected text range. For reference, this is the default behaviour in Sublime Text.

Here is an Atom package that provides this behaviour:
https://atom.io/packages/duplicate-line-or-selection

You could argue that there's a package, and that I should just use that, but every package added to Atom slows down the load time, and I would argue that this particular behaviour is something that should be in core, as "duplicate" is the behaviour we want. The fact that it's easy to duplicate an entire line, either by selecting it, or by having no selection at all, means you're not really losing anything by implementing this.

In addition, I would argue that any user that has selected a specific range of characters within a line and then uses the duplicate shortcut probably intends for their selection to be duplicated, rather than the entire line.

**Atom Version:** 1.7.0-beta
**OS and Version:** Windows 10

**Comment by mnquintana** [comment] 2016-03-26 04:38
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/3002 though – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-03-26 04:38 UTC
