### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Konutis/Downloads/Atom.app'

### ISSUE THREAD

**Issue by konutis** [atom/atom#10012] opened 2015-12-11 07:56 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Konutis/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/Konutis/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/Users/Konutis/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -2:50.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:50.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:50.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:50.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:49.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:49.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:49.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:49.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:46.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:43.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:43 core:move-left (atom-text-editor.editor.is-focused)
  8x -2:42.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:40.9.0 core:paste (atom-text-editor.editor.is-focused)
     -1:56.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:56.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:36.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-11 12:35
This is a duplicate of #9813 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-11 12:35 UTC
