### ISSUE TITLE
command+p; command+shift+p; focus issue

### ISSUE THREAD

**Issue by safareli** [atom/atom#15789] opened 2017-10-02 11:50 UTC
### Description
command+p; command+shift+p; focus issue

### Steps to Reproduce

1. focus in contents of some file
2. command+p; 
3. command+shift+p;
4. not focus is in file instead of dialog; if you type something text is entered in the file where you had focus before.

**Expected behavior:** [What you expect to happen]
Focus should be (when you type something text should go) in input of "command palette"

**Actual behavior:** [What actually happens]
Focus should is (when you type something text should goes) in file you had focused before

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions

1.20.0 (and in old versions too)

**Comment by rsese** [comment] 2017-10-02 16:53
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14325. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-02 16:53 UTC
