### ISSUE TITLE
Shouldn't the package changelog be taken from GitHub?

### ISSUE THREAD

**Issue by leo** [atom/atom#10467] opened 2016-01-17 16:49 UTC
Currently, there's a big `CHANGELOG` which shows up if your package contains a file called `CHANGELOG.md`. But since GitHub already has the [Releases](https://github.com/atom/atom/releases) feature (which easily allows devs to add the changes to each version), I was wondering why we're not leveraging this instead?

If you ask me, the changelog should simply be generated from the existing changelog in the "Releases" section of each repo. :innocent:

<img width="880" alt="9e0f7a9e-bd30-11e5-8f8e-0476b13f48ab" src="https://cloud.githubusercontent.com/assets/6170607/12378580/b30f40ca-bd42-11e5-8e62-eafd521146b7.png">

**Comment by mnquintana** [comment] 2016-01-17 16:56
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/3705 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-17 16:56 UTC
