### ISSUE TITLE
Packages and Themes does not search automatically

### ISSUE THREAD

**Issue by sw3dish** [atom/atom#7590] opened 2015-06-30 13:56 UTC
To search for a package / theme in the settings tab, I have to type in the search query then click (if looking for a package) the themes button, then the package button to have Atom search for a package matching that string.

**Comment by mnquintana** [comment] 2015-06-30 14:04
This is a duplicate of https://github.com/atom/settings-view/issues/559 – please subscribe there for updats.

(Also for future reference, Atom's settings view is handled by atom/settings-view, not atom/atom.)

**Closed by mnquintana** 2015-06-30 14:04 UTC

**Comment by simurai** [comment] 2015-07-01 01:51
I made a new issue https://github.com/atom/settings-view/issues/562 since #559 got slightly changed (UX -> bug).
