### ISSUE TITLE
Uncaught Error: Cannot find pane for item in `DockItem#activate`

### ISSUE THREAD

**Issue by raghav18gupta** [atom/atom#15677] opened 2017-09-18 09:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find pane for item in `DockItem#activate`

```
At /usr/share/atom-beta/resources/app/node_modules/github/lib/views/dock-item.js:154

Error: Cannot find pane for item in `DockItem#activate`
    at setTimeout (/usr/share/atom-beta/resources/app/node_modules/github/lib/views/dock-item.js:154:21)
```

### Commands

```
     -0:07.1.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
script 3.15.0 
```

**Comment by rsese** [comment] 2017-09-18 17:47
Thanks for the report - I think this is a duplicate of https://github.com/atom/github/issues/1150 and should be fixed in a future release.

**Closed by rsese** 2017-09-18 17:47 UTC
