### ISSUE TITLE
Show Invisibles: series of spaces at the center of line not shown

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#9041] opened 2015-10-04 09:42 UTC
Is this a bug or a feature?

![image](https://cloud.githubusercontent.com/assets/504770/10267234/9e5944d6-6a8c-11e5-9421-7c5453408e8d.png)

 I can understand a single space is not displayed with a dot to improve readability, but series of spaces should in my opinion, at least starting from two or three. Especially when spaces are used to space tabular data.

**Comment by thomasjo** [comment] 2015-10-04 09:45
This behavior is by design.

**Comment by izuzak** [comment] 2015-10-04 18:54
Thanks for the feedback, @stijnsanders. The behavior you observed is expected for now, but there's already an issue which suggest improvements to the "Show invisibles" behavior: https://github.com/atom/atom/issues/4311. That issue is a bit more general, but I believe it covers your feedback as well, so I'm going to close this in favor of that issue. Please feel free to leave a comment on that issue -- having all the related feedback in one place is helpful.

**Closed by izuzak** 2015-10-04 18:54 UTC

**Comment by thomasjo** [comment] 2015-10-04 18:57
@izuzak Thanks for finding that issue! I was sure there was an issue or PR for improving this, but I missed it.
