### ISSUE TITLE
Uncaught TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by priyankvex** [atom/atom#5250] opened 2015-01-25 07:50 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.13.0-44-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'index' of undefined

```
At /usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:95

TypeError: Cannot read property 'index' of undefined
  at IntervalSkipList.module.exports.IntervalSkipList.findIntersecting (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:95:31)
  at MarkerManager.module.exports.MarkerManager.findMarkers (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-manager.js:156:46)
  at TextBuffer.module.exports.TextBuffer.findMarkers (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:661:27)
  at DisplayBuffer.module.exports.DisplayBuffer.findMarkers (/usr/share/atom/resources/app/src/display-buffer.js:1296:26)
  at DisplayBuffer.module.exports.DisplayBuffer.decorationsForScreenRowRange (/usr/share/atom/resources/app/src/display-buffer.js:1189:20)
  at TextEditor.module.exports.TextEditor.decorationsForScreenRowRange (/usr/share/atom/resources/app/src/text-editor.js:1252:33)
  at [object Object].module.exports.React.createClass.render (/usr/share/atom/resources/app/src/text-editor-component.js:77:30)
  at [object Object]._renderValidatedComponent (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1249:34)
  at [object Object].updateComponent (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1179:33)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1123:10)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1063:14)
  at runBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:152:17)
  at ReactReconcileTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /usr/share/atom/resources/app/src/text-editor-component.js:313:28

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
minimap, v3.5.6

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-01-25 15:22
Can you please share some steps to reproduce this error if possible?
Also, can you see if this still occurs in safe mode (`atom --safe`)?

**Comment by muchweb** [comment] 2015-01-26 16:16
This just happened to me, when I was closing a large tab. While editor was lagging, I've opened another large tab and started quickly scrolling using `minimap`. I suspect that this may happen when scroll is performed on half-loaded buffer.
---
Atom `0.175.0`, on GNU Operating system. I am also using `minimap` package.

**Comment by priyankvex** [comment] 2015-01-26 19:09
I agree with @muchweb. Happened to me for the same reason I guess.

**Comment by ReactiveRaven** [comment] 2015-01-27 12:46
Me too. Although it happened on a 138 line file on a machine with 16GB RAM, so I'd be surprised if it wasn't loaded quick enough. Although in total I do have 1361 lines open in total across all buffers.
---
Atom `0.176.0` on Ubuntu with `minimap` package.

**Comment by 1j01** [comment] 2015-01-28 19:40
I can consistently reproduce this by simply opening certain files.

![another atom crash](https://cloud.githubusercontent.com/assets/3630663/5944753/5e0e8c82-a6f7-11e4-80ab-7fa60c6d665b.png)

Okay, I jinxed it. It's now working just fine on those files.

This was on Windows 8.1, opening a file with `LF` line endings.
The rest of you are on linux... or "*unix-like* operating sysems", so probably have files with `LF`s as well, so I'm guessing this only happens with files with `LF`s as line endings (rather than just on unix-like systems as one might deduce prior to this windows-based report)

Wait, I just tried closing it and changing another file and then opening it (via drag and drop) and it crashed instantaneously!

I don't know. :pensive:

:page_facing_up: https://www.dropbox.com/s/zg70oga4gaytk9a/OverlapsAreGooooood.html?dl=0

**Comment by say2joe** [comment] 2015-01-29 19:33
Having same issue. My MiniMap is now a MiniBug.

**Comment by benogle** [comment] 2015-01-29 19:38
We need consistent repro steps. cc @abe33 may be minimap related?

**Comment by TadorHead** [comment] 2015-01-30 04:30
I'm having the same problem. It appeared twice.  :(

**Comment by abe33** [comment] 2015-01-30 08:58
@benogle Probably, but I'm not really sure what I did wrong in the minimap to trigger that. I had this error raised in tests with this one: 

https://github.com/fundon/atom-minimap/blob/master/spec/minimap-element-spec.coffee#L244-L263

The only thing I changed to remove the error in my test was to use `andCallFake` instead of `andCallThrough` for the `setScrollTop` spy:  

https://github.com/fundon/atom-minimap/blob/next/v4/spec/minimap-element-spec.coffee#L246-L265

So, as @muchweb mentioned, there's probably something related to scrolling a buffer. If it's a matter of preventing scroll until the editor reach a specific state, I don't mind adding a guard in the minimap. 
What's seems weird is that the stack doesn't mention the minimap at all, so if the minimap do something bad, the `TextEditor` fail to catch it when its done and doesn't prevent the crash later in the render process.

**Comment by 190n** [comment] 2015-02-01 20:13
I get this on linux as well. Atom 0.175.0, minimap 3.5.6.

**Comment by BrandonDusseau** [comment] 2015-02-02 04:25
This happens for me when I scroll on the minimap for the first time after splitting the view.

**Comment by abe33** [comment] 2015-02-02 09:45
Ok, I got it when the `V4 preview` setting is disabled, if @190n, @BrandonDusseau, @TadorHead, @1j01 and @say2joe can try confirming that the issue is no longer present when the setting is enabled it'll be great. 
Note that changing the setting need a restart of Atom to be effective.

**Comment by BrandonDusseau** [comment] 2015-02-02 13:34
@abe33 I do not get the error with `V4 preview` enabled.

**Comment by abe33** [comment] 2015-02-02 13:38
Ok great, I think I'll have to publish v4 sooner than I thought, v3 is too much of a mess now (hence the complete rewrite for v4) and I doubt that trying to fix v3 is a good option now that v4 has stabilized.

**Comment by benogle** [comment] 2015-02-02 18:53
:+1:

**Comment by abe33** [comment] 2015-02-03 09:25
V4 have been officially released, so I think this ticket can be closed.

**Closed** 2015-02-03 13:07 UTC
Labels: more-information-needed, needs-reproduction
