### ISSUE TITLE
Line width marker not moved on startup

### ISSUE THREAD

**Issue by YoYoYonnY** [atom/atom#13009] opened 2016-10-17 18:41 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
**Not applicable, but probably.**
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
**Yes.**
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
**Not applicable, but yes.**
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
**Not applicable, but yes.**
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
**Yes.**
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? **Yes, using the `line in:title` search selector**

### Description

When changing the font size on startup, the line width marker is in the incorrect (old) place.

### Steps to Reproduce

1. Edit your Init script (`Edit > Init script...`) to set font size on startup (e.g. by adding `atom.config.set('editor.fontSize', 1)`).
2. Zoom a little, so the line width marker is clearly visible near the middle.
3. Reopen atom.

**Expected behavior:** The line width marker is in the correct position, near the left when setting editor.fontSize to one.

**Actual behavior:** The line width marker is still in it's old positition. Zooming in or out will move the marker to the correct position.

### Versions

Atom 1.11.1
Ubuntu 16.04.1 LTS

**Comment by 50Wliu** [comment] 2016-10-17 19:04
This is a duplicate of atom/wrap-guide#25 - feel free to subscribe there for updates.

(Also, testing in safe mode and checking the debugging guide are both very applicable here.)

**Closed by 50Wliu** 2016-10-17 19:04 UTC

**Comment by YoYoYonnY** [comment] 2016-10-17 20:22
@50Wliu Thanks, I will.
