### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by zingerj** [atom/atom#15006] opened 2017-07-13 00:08 UTC
[Enter steps to reproduce:]

1. Click anywhere within a file

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At C:\Users\jzinger1\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\text-editor-component.js:2145

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/text-editor-component.js:2145:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/text-editor-component.js:2141:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/text-editor-component.js:382:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/text-editor-component.js:266:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -3:53.9.0 core:save (input.hidden-input)
  2x -3:48.3.0 intentions:highlight (input.hidden-input)
     -3:47.8.0 core:copy (input.hidden-input)
     -3:34.7.0 intentions:highlight (atom-text-editor.editor)
     -3:34.5.0 core:paste (atom-text-editor.editor)
     -3:32.7.0 intentions:highlight (atom-text-editor.editor)
     -3:32.6.0 core:undo (atom-text-editor.editor)
  3x -3:16.4.0 core:backspace (input.hidden-input)
undefined -3:14.1.0 core:delete (input.hidden-input)
     -3:06.8.0 intentions:highlight (input.hidden-input)
     -3:06.6.0 core:paste (input.hidden-input)
     -3:01.6.0 intentions:highlight (input.hidden-input)
  4x -3:01.4.0 core:save (input.hidden-input)
  7x -2:56.3.0 intentions:highlight (input.hidden-input)
  3x -2:55.6.0 core:save (input.hidden-input)
  2x -1:35 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-react-native-css 1.1.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-modules 1.6.10 
busy-signal 1.4.3 
color-picker 2.2.5 
css-comb 2.5.0 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.8 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-babel 2.66.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
minimap 4.28.3 
monokai-seti 0.9.0 
pigments 0.39.1 
seti-ui 1.9.0 
todo-show 1.11.0 
```

**Comment by rsese** [comment] 2017-07-14 20:13
Thanks for the report!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14794. You may want to subscribe there for updates and if you can let us know in that issue if you can reproduce the error in safe mode with your steps to reproduce, that would be helpful to know.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-14 20:13 UTC
