### ISSUE TITLE
"The editor has crashed" - windows 10

### ISSUE THREAD

**Issue by 3nk** [atom/atom#10717] opened 2016-02-06 09:57 UTC
Hi,

"The editor has crashed": This occurs quite often on windows 10 (no specific action or context)

![crash](https://cloud.githubusercontent.com/assets/5038522/12866051/2a265e6e-ccc0-11e5-9468-9b40f324a186.png)

**Comment by lee-dohm** [comment] 2016-02-08 19:39
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by kurosch** [comment] 2016-02-08 21:19
just checked `atom --safe` still crashes for me.
After a clean install (deleted `.atom`, `Roamin\atom`, and `local\atom` and version `1.4.3`), it only crashes when opening a folder.

-----
I will investigate this a bit more as it really frustrates me.

**Comment by bluekeys** [comment] 2016-02-18 10:40
I think I also have this issue. Atom crashed with a number of files open. When I tried to enter safe mode atom was still frozen so I was unable to debug. I found this thread and tried opening another file `atom --safe randomfile.txt` which appears to have resolved the issue so I can now continue using atom as I was. I am using windows 7 x64.

**Comment by jan-glx** [comment] 2016-04-08 09:04
I have the same symptoms as @3nk. It is happening 2 to 3 times a day while interacting but at no specific action. (And `-> Reload` does not work; pressing it turns the dark part of the editor black)
I am on Atom 1.6.2 on Windows 10.0.10586 Pro with the only non-core packages being `latextools` and `language-latex`. [crash log .txt files](https://gist.github.com/jan-glx/b42e7cfc2ce9025fd9e303d728443fef) 

How can I gather further information that may help to resolve this problem?

**Comment by lyquocnam** [comment] 2016-04-08 09:27
i have some on few hours ago !
windows 10 x64

**Comment by kevinhikaruevans** [comment] 2016-04-19 19:33
This is happening CONSTANTLY on my computer.

I haven't had any crashes while running it in safemode, which makes me think that's it's probably a package. The crash log doesn't seem to display anything meaningful. How can you tell which package is causing the issue?

I currently have:

- language-babel
- linter
- linter-eslint
- react
- atom-material-syntax
- atom-material-ui

...installed.

**Comment by 50Wliu** [comment] 2016-04-19 19:37
@kevinhikaruevans It most likely isn't language-babel or the two themes you have installed, so I'd try going in alphabetical order - first disable `linter` and `linter-eslint` for a while, and if that doesn't work, then try disabling `react`.

**Comment by lee-dohm** [comment] 2016-04-20 00:19
@3nk Are you still running into this problem?

For the others on this Issue, please file a new Issue with all the relevant information. If Atom is crashing, give us crash logs too. This Issue will be closed if @3nk is not experiencing it anymore.

**Comment by HaykoKoryun** [comment] 2016-04-27 01:43
I have a hunch that it might have something to do with packages using `git diff` on projects with a large/old `.git` directory. I just disabled `git-diff` and `minimap-git-diff` and stopped getting the crashes when typing; re-enabling brought the crashes back very soon.

I have two instances of `Atom` open, one with an old rep from ~2014, 75 megs and 3047 commits and the other one with a bunch of different git projects with < 100 commits combined and the former one keeps on crashing.

**Comment by lee-dohm** [comment] 2016-04-27 02:24
@HaykoKoryun The Atom repo dates back to 2011 and has over 28k commits. Since git-diff is a default-installed package, I would expect that our Windows maintainers would have reported something like this.

**Comment by lee-dohm** [comment] 2016-04-27 02:25
@3nk Do you have any updates? If we don't hear back from you, we'll have to close this.

**Comment by lee-dohm** [comment] 2016-04-28 19:01
Closing due to lack of response. If anyone else is having a similar problem, please file a new Issue.

**Closed by lee-dohm** 2016-04-28 19:01 UTC
Labels: more-information-needed, windows
