### ISSUE TITLE
Mac: Open dialog (CMD+O) will not appear if all windows are closed

### ISSUE THREAD

**Issue by ecbrodie** [atom/atom#13518] opened 2016-12-30 03:37 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Mac **Open Dialog** (CMD+O) will not appear if all windows are closed

### Steps to Reproduce

1. Open Atom in Mac
1. Close all app windows, but keep the app open
1. Trigger the Mac Open interface. You can do so by clicking on File --> Open or pressing CMD+O

**Expected behavior:** The Mac "Open Dialog" appears

**Actual behavior:** Nothing...The File menu will flash, but the Open Dialog will not appear

**Reproduces how often:** 100%

### Versions

```
➜ atom --version
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
➜ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.13
git 2.11.0
```

I am using `MacOS 10.12.2`. I can also comment that I have been witnessing this issue for at least a year. It was just never a blocking issue since there are workarounds (see below).

### Additional Information

The workaround is to have an app window open, in which case the Open Dialog will open without error. Or, I use the CLI to open a directory with the `atom` command.

**Comment by 50Wliu** [comment] 2016-12-31 01:40
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-31 01:40 UTC
