### ISSUE TITLE
File name dialog cuts off long paths but doesn't let you scroll to view it all

### ISSUE THREAD

**Issue by jglovier** [atom/atom#9267] opened 2015-10-23 19:15 UTC
I've run into an issue where working with long pathnames (whether creating a new file, or renaming an existing file) brings up the filename dialog but I cannot scroll past the current view. So if I'm creating a path or filename that exceeds the visible boundaries of the box, the text is not visible while typing, or even if I try to scroll horizontally.

![image](https://cloud.githubusercontent.com/assets/1319791/10702499/1cd34b1c-7998-11e5-90ca-24e10300ffe3.png)

I examined the element to see if there were any obvious style conflicts (like `overflow:hidden` or something) but didn't see anything noticeable.

![atom-screencap](https://cloud.githubusercontent.com/assets/1319791/10702614/d3ae7d20-7998-11e5-876e-9f3846d11a97.png)

**Comment by jglovier** [comment] 2015-10-23 19:15
Apologies if this is a dupe. i tried searching for something similar several different ways but didn't spot any existing issues.

**Comment by 50Wliu** [comment] 2015-10-23 20:11
I know it's a duplicate, I just forget what repo it's on :stuck_out_tongue: - /cc @atom/feedback.

**Comment by mnquintana** [comment] 2015-10-23 20:36
Thanks for the report! This looks like a duplicate of https://github.com/atom/tree-view/issues/592, but I know that one isn't the original either... ¯\\_(ツ)_/¯

In any case, I'll close this out in favor of that issue.

**Closed by mnquintana** 2015-10-23 20:36 UTC

**Comment by jglovier** [comment] 2015-10-23 21:04
:+1:

**Comment by simurai** [comment] 2015-10-24 01:51
Here a work-around for your `styles.less`: https://github.com/atom/tree-view/issues/473#issuecomment-131388489. Maybe doesn't work with every UI theme.

**Comment by jglovier** [comment] 2015-10-24 14:34
@simurai :bow: thanks! I saw that in the other thread and added it, and it works just fine. :pray:
