### ISSUE TITLE
Regular expression working with **`Find`** but not with **`Find All`**

### ISSUE THREAD

**Issue by sebabouche** [atom/atom#16224] opened 2017-11-17 16:05 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Regular expression working with **`Find`** inside a single file but not with **`Find All`** searching in the whole project.

#### 1. Open a projet with atom
`atom .` or `atom folder`
#### 2. Create a python file with:
```
def sample_method():
    print(
        "hello",
        "world",
    )
```
#### 3. In the top menu click `Find > Find in Buffer` or hit `CTRL+F` / `CMD+F`
+ Click the use Regex button `.*`
+ And search for `,*\n +\)` (_search for a comma or no comma, return, one or more spaces and a parenthesis_)
+ Click `Find`

#### 4. In the top menu click `Find > Find in Project` or hit `CTRL+SHIFT+F` / `CMD+SHIFT+F`
+ Click `Find All`

**Expected behavior:** steps (3) and (4) should both find one occurence in the file created

**Actual behavior:** step (3) only finds the regex ; step (4) outputs "No Results"

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by rsese** [comment] 2017-11-17 19:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/218. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-17 19:16 UTC
