### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ LLC'

### ISSUE THREAD

**Issue by troy-holleman** [atom/atom#18188] opened 2018-10-03 20:09 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ LLC'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/ LLC'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:343:29)
    at TreeView.module.exports.TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1544:34)
    at TreeView.module.exports.TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1844:37)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:389:30)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-package-sync 0.2.6 
autoclose-html 0.23.0 
autocorrect 0.1.0 
autocorrect-en 0.0.3 
block-comment 0.4.3 
busy-signal 1.4.3 
dnote-atom 0.2.2 
docblockr 0.13.7 
editorconfig 2.2.2 
expand-selection-to-quotes 0.11.0 
file-icons 2.1.25 
git-tabs 0.3.0 
git-time-machine 2.1.0 
hey-pane 1.1.2 
highlight-selected 0.14.0 
Hydrogen 2.6.0 
ide-vue 0.1.9 
intentions 1.1.5 
language-markdown 0.26.0 
language-vue 0.23.1 
lint-sass-vue 1.0.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
markdown-mindmap 0.5.0 
markdown-table-editor 1.1.1 
markdown-writer 2.9.0 
minimap 4.29.9 
php-cs-fixer 4.1.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
snippet-injector 1.5.3 
split-diff 1.5.2 
tab-length 0.1.0 
teletype 0.13.3 
terminal-tab 0.5.7 
tool-bar 1.1.10 
tool-bar-markdown-writer 0.5.0 
tree-view-git-status 1.5.2 
vue-autocomplete 0.1.1 
vue-fmt 0.1.1 
```

**Comment by rsese** [comment] 2018-10-03 21:13
Thanks for contributing!

Based on the stack trace, I'll close as a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.  If you can share exactly what you were doing at the time of the error, that would be helpful too.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-03 21:13 UTC
Labels: duplicate
