### ISSUE TITLE
Incorrect doc-block autocomplete

### ISSUE THREAD

**Issue by sinesc** [atom/atom#6835] opened 2015-05-18 06:22 UTC
Atom 0.199.0/win32 with all community packages disabled incorrectly autocompletes the following as soon as @ is typed:

```javascript
/**
 * @
```

This gets completed to...

```javascript
/**
 /**
  * @
```

* only happens on the first line after a `/*` or `/**`
* happens regardless of document type (tested js, plain text and markdown)
* if there is a line right below the @, cursor will be moved to the end of that line, otherwise will behind the @
* tried  `'ctrl-alt-q': 'unset!'` under `'.platform-win32 .editor'` in keymap.cson to no effect (suggested here: https://github.com/atom/atom-keymap/issues/35)

Sorry if this is a duplicate. Is there a way to search for single, non-alphanumeric characters on github (i.e. @) ?

**Comment by lee-dohm** [comment] 2015-05-18 06:44
I cannot reproduce this behavior on Atom v0.200.0-1a8ebd5 on Mac OS X 10.10.3. Here is what I attempted:

1. Open Atom
1. Open a new file using <kbd>Cmd+N</kbd> (plain text grammar automatically selected by Atom)
1. Type `/**` on the first line
1. Type ` * @` on the second line

**Expected and Actual:** Nothing happens beyond the entry of the characters

**Comment by lee-dohm** [comment] 2015-05-18 15:34
@Seadragon91 are you using a US English keyboard layout? Or something else?

**Comment by Seadragon91** [comment] 2015-05-18 15:35
I am using a German keyboard layout.

**Comment by lee-dohm** [comment] 2015-05-18 15:40
Ok, I believe this and atom/autoflow#27 are both duplicates of atom/atom-keymap#35. When you type `@`, I suspect Atom is thinking you're pressing <kbd>Ctrl+Alt+Q</kbd>, which activates the autoflow command. Please use the Keybinding Resolver (<kbd>Ctrl+.</kbd> on Windows/Linux, I believe) to confirm.

**Comment by sinesc** [comment] 2015-05-19 05:08
Looks like you're right...
```
unset! .platform-win32 .editor (keymap.cson)
autoflow:reflow-selection .platform-win32 atom-text-editor, .platform-linux atom-text-editor (...autoflow.json)
```

I have now tried appending this to keymap.cson without success (now shows up in resolver as well along with the reflow stuff):

```
'.platform-win32 atom-text-editor, .platform-linux atom-text-editor':
  'ctrl-alt-q': 'unset!'
```

**Comment by lee-dohm** [comment] 2015-05-19 05:22
So there are two issues here. One is atom/atom-keymap#35. The other is atom/autoflow#27. I'm going to close this as a duplicate of them since they are on the packages that the bugs are actually in. Please let me know if there is anything else I can do or answer :grinning:

**Closed by lee-dohm** 2015-05-19 05:22 UTC
Labels: more-information-needed, needs-reproduction

**Comment by sinesc** [comment] 2015-05-19 17:45
Ffr: https://github.com/atom/atom-keymap/issues/35#issuecomment-52508869 is a workaround. Just replace "ctrl-alt-[" with "ctrl-alt-q". Simply using !unset, !native, !abort, !whatever won't work, those are apparently broken as well.
