### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 12035

### ISSUE THREAD

**Issue by bra-fsn** [atom/atom#20133] opened 2019-11-08 13:36 UTC
[Enter steps to reproduce:]

1. I've edited a python file, nothing special. This is the first occasion I got this error

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 12035

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 12035
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:148:17)
    at /usr/share/atom/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -2:23 find-and-replace:show (input.hidden-input)
  3x -2:22.9.0 core:confirm (input.hidden-input)
     -2:21.4.0 editor:consolidate-selections (input.hidden-input)
     -2:21.4.0 core:cancel (input.hidden-input)
  3x -2:21 core:move-left (input.hidden-input)
     -2:20.3.0 editor:select-to-end-of-line (input.hidden-input)
     -2:20.1.0 core:select-left (input.hidden-input)
     -2:19.8.0 core:copy (input.hidden-input)
     -2:19.5.0 core:move-to-bottom (input.hidden-input)
  6x -2:19.1.0 core:move-up (input.hidden-input)
  4x -2:17.5.0 core:move-down (input.hidden-input)
     -2:16.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:16.8.0 editor:newline (input.hidden-input)
     -2:16.5.0 core:paste (input.hidden-input)
     -2:16.3.0 core:save (input.hidden-input)
     -2:10.9.0 core:close (div.github-StagingView.unstaged-changes-focused)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
docblock-python 0.15.1 
Hydrogen 2.13.0 
hydrogen-launcher 1.2.2 
ide-python 1.5.0 
language-groovy 0.7.0 
language-nginx 0.8.0 
last-cursor-position 0.9.3 
platformio-ide-terminal 2.9.4 
sort-lines 0.19.0 
```

**Comment by rsese** [comment] 2019-11-11 01:19
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

It sounds like the error isn't reproducible for you, but if it is, please let us know the steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-11 01:19 UTC
