### ISSUE TITLE
The editor is not responding.

### ISSUE THREAD

**Issue by satishverma143** [atom/atom#12983] opened 2016-10-14 12:51 UTC
Atom Version : 1.11.1
apm : 1.12.5

When i open atom then just after few seconds a window comes with this message 
![eee](https://cloud.githubusercontent.com/assets/11610172/19387995/1312b9f2-923b-11e6-8e8b-0704b42e3df5.png)

Please help me asap.

**Comment by Ingramz** [comment] 2016-10-14 13:50
@satishverma143 does that happen when you start Atom in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by mikecousins** [comment] 2016-10-14 17:14
It happens in safe mode as well. Tried a reinstall and that didn't fix it either.

**Comment by avdg** [comment] 2016-10-15 19:49
Got these window a lot in 1.11 and getting the feeling it's in 1.12 too. Doesn't happen when editor state gets reset which can be done using the command `atom --clear-window-state`.

**Comment by avdg** [comment] 2016-10-15 19:51
Actually, if one uses `atom --clear-window-state`, it might indicate an issue anyway (I wish I had stats of this for myself now actually)

**Comment by foresterre** [comment] 2016-10-16 14:25
The same happened to me today. upon installing the latest version, downloaded from the atom.io homepage.
I had an Atom version installed, and consequently removed a few months back, prior to installing it today again. I'm unsure what the previous version number was. I uninstalled atom last time by using "Programs and Features" > "Uninstall" (thus the default uninstaller I presume).
Community packages left over were: "autocomplete-plus", "language-dyon", "language-rust", "minimap".
 
**Versions**
My Atom version is 1.11.1.
My Windows version is 8.1.

**Steps taken:**
0. Installed Atom 1.11.1 from the installer on the Atom.io homepage.
1. Started Atom
2. Went to the settings panel (by Ctrl+Comma)

Result:
After a few seconds, Atom starts to hang. 
Then after some more time the pop-up window ("Atom: Editor is not responding, as shown above") pops up. 

3. Click on "Keep Waiting"

Result:
Atom crashes and asks by a pop-up: refresh editor, or close (there was a third option I can't remember)

4. Restarted a few times, with the same results
5. Restarted without going immediately to "Settings" > "Packages" (same results)
6. Removed Atom through "Program and Features" > "Uninstall"
7. Deleted %APPDATA%/Atom
8. Reinstalled Atom 1.11.1 from the installer on the Atom.io homepage.
9. Started Atom again. This time, the editor did not hang, neither after installing a package and working it ('using the editor') for about half an hour. 
10. After restarting the editor still works.

I am unsure what caused Atom to stop responding, but I hope this extra information might help to resolve the issue.
If more information, which I can provide is needed, I am happy to help.

**Comment by avdg** [comment] 2016-10-16 16:53
I guess atom got in a corrupt editor session state, not sure what caused the corruption though

**Comment by delk0** [comment] 2016-10-21 22:52
This happens to me as well but in my case it's every time I close atom.

**Comment by pgibelin** [comment] 2016-11-03 12:50
Hi

Hmmm.  I have the same problem. I can't do anything with atom until I clear its state with **atom --clear-window-state** and thus lose my previous configuration. It will work a few times (two or three...) and eventually go back to freezing when opening the program. Running it in safe mode does not help.

This does seem to be a common problem. I thought it was had to do with a Windows 10 update, but reading comentaries, it seems to fail on various OS'.

**Comment by avdg** [comment] 2016-11-03 13:20
I still wonder if I can get any useful debug information out of the crash when the editor got stuck. I didn't had as many issues on beta (probably since I avoided big files) but I won't directly say that the problem is resolved for now.

**Comment by riskers** [comment] 2016-11-10 05:23
i meet the same problem but i running it in safe mode is ok.
It seems one package is not suitable for version, but how find this package?

**Comment by 50Wliu** [comment] 2016-11-10 14:37
@riskers Try using the [package-cop](https://atom.io/packages/package-cop) package.

**Comment by AshleyFinney** [comment] 2016-11-15 11:41
I'm also getting this every few days in 1.13.0-beta2.  Calling `atom --clear-window-state` clears the problem.

**Comment by adambuczynski** [comment] 2016-11-22 22:34
I get these errors in particular when I am *closing* project windows. The windows disappear, then after 2-3 seconds reappear with that message. When I press "wait", they then disappear again by themselves.

**Comment by ADTC** [comment] 2016-12-05 07:36
On the latest version 1.12.6 on Windows 10, and I'm getting the same problem as adamreisnz when closing Atom window (to exit Atom):

![image](https://cloud.githubusercontent.com/assets/6047296/20876816/7e4a26dc-baff-11e6-8e4c-7c830eb7265a.png)

**Comment by adamreisnz** [comment] 2016-12-05 07:45
This also happens when I am trying to restart my Mac, and it tries to close all windows. It complains that the Editor has interrupted restart, and if I want to force quit it or keep waiting. 

Keep waiting is usually ok as it will close eventually, but it's a bit annoying, as Atom is open on my computers pretty much 100% of the time.

**Comment by Ben3eeE** [comment] 2016-12-06 10:06
@ungb There have been an increasing number of reports for this since 1.12 was released.

**Comment by ADTC** [comment] 2016-12-07 16:48
Regarding _needs-reproduction,_ would collecting info from my computer using a debug testing version help?

**Comment by i2000s** [comment] 2016-12-10 08:24
[operation_log.txt](https://github.com/atom/atom/files/643624/operation_log.txt)
Here is a log of crash, if anyone wants to look into this.

**Comment by zneyrl** [comment] 2016-12-31 01:57
Happens to me as well. I have the latest version of atom. I've tried every solution found here but, still can't make it work.

Atom: 1.12.7
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0

Windows: 1607

**Comment by i2000s** [comment] 2016-12-31 03:39
@zneyrl Per the request of @lee-dohm , could you try the following to see if you can reproduce the problem in the Safe Mode?

1. Completely exit all instances of Atom
2. Launch Atom with the command `atom --safe`

**Comment by RickvanMiltenburg** [comment] 2017-01-01 11:59
Having the same issue on startup for a while now. The editor loads whatever folder I was last in on startup, renders the windows and everything correctly, but just does not respond to user interaction. The "Editor is not responding" pop-up shows up a little later.

@i2000s Using --safe did not resolve the issue for me.

The following workaround works for me:

1. Start Atom (safe mode not required)
2. Go to Task Manager
3. Find an Atom instance with (on my system) roughly ~32 MB of RAM usage
4. Kill it

![image](https://cloud.githubusercontent.com/assets/6962414/21581077/effaf5a0-d020-11e6-96d6-76f88ce10e20.png)

This causes the editor to respond again, assuming you got the right instance. (In the case above: The one highlighted)

Atom runs without issues after the above process as far as I have noticed. It is always a particular instance you have to kill, but I cannot tell exactly what this instance is supposed to do. At the very least it appears to be doing some blocking operation which never completes, and the main editor instance appears to wait for this operation.

Another workaround with limited success is to just reset the startup folder. (In this case I just started a new window after doing the above, and closing the first window before the new window) Restarting Atom and going into the folder I was originally working from has reset the files I had open, and subsequently restarting Atom for a little while at least works again. After some time of use, it usually falls back into the same behaviour.

`Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0`

Only core packages installed.

**Comment by 50Wliu** [comment] 2017-01-01 16:09
@RickvanMiltenburg sounds like you need `atom --clear-window-state` (but before you do that, read up on the risks at http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state).  You may have some better luck figuring out which Atom process to kill if you turn on the Command Line option in the Task Manager (right-click on CPU).

**Comment by RickvanMiltenburg** [comment] 2017-01-03 18:39
@50Wliu This did fix it for a day, but today it is showing the same problems once again.

The command line tip is helpful though. This is the instance which I have to kill for it to work without `--clear-window-state`

![image](https://cloud.githubusercontent.com/assets/6962414/21618565/d00edfe6-d1eb-11e6-9767-887d633b3ec5.png)

**Comment by AshleyFinney** [comment] 2017-01-04 11:09
@RickvanMiltenburg I can confirm that this also works for me.  I have two identical instances with that same command line.  Killing either one of them brings Atom to life.

**Comment by theredpea** [comment] 2017-02-10 04:59
I get this error after Symantec Endpoint Protection quarantined "update.exe" as shown in attached log, thanks to this: https://www.symantec.com/security_response/writeup.jsp?docid=2016-111608-2910-99 . Looks like it quarantined .shasum's and .diff's having to do with squirrel. Maybe completely unrelated to the bug here, but...

**Comment by fchristant** [comment] 2017-02-11 11:39
Thanks to those with the useful tips for Windows specifically. Also, I believe Atom is the best editor out there, if only it would work.

I've had freezes and hangups plague my usage for two years now. The editor works 90% of the time, yet each time I encounter a hangup, it's almost impossible to restore it to a working state. Every time I have to reboot, reinstall, kill all packages, clear the window state, and lose my entire workflow. Safe mode makes no difference, nor does clearing the window state. And it's not consistent. Sometimes it crashes on a minified file, the next day it can open it just fine. 

I'm not asking for the world, I'm asking to open a bloody text file. It should not costs me dozens of hours of  productivity and troubleshooting to do so. To me, this instability seems to be at the core of the product, since it occurs without any packages as well. 

I'm sorry for the non-constructive rant, I really wish for Atom to succeed as it is my favorite editor, but it leaves me no choice but the switch back to Sublime. Atom has ruined so many days that I've lost patience and trust in it.

**Comment by jholewinski** [comment] 2017-02-13 13:53
Same problem here. Everytime I open Atom, I need to find the atom.exe process with the "--eval require" arguments and kill it. Sometimes I get 4-5 of them, and have to kill them all before I can use Atom.

Anything I can provide to help diagnose and fix this issue?

**Comment by 50Wliu** [comment] 2017-02-13 20:35
@jholewinski if you disable the fuzzy-finder package do the extra processes still show up? (And of course, do they show up in safe mode?)

**Comment by ungb** [comment] 2017-02-13 22:32
Hey All,  Thanks for providing all the feedback.  I'm the quality engineer on Atom and I am currently trying to get a repro of this issue. 

if anyone  that sees this issue can provide the following info below, would be helpful.  

1. Does Atom still freeze up if you open a different project?  For example, in cmd/powershell, go to a different directory and run `atom .`
2. Does this occur after opening a certain type of file?  Does the file that is in question, [have a single line that is very long?](https://github.com/atom/atom/issues/979)  

Any other detail can help.  When I try opening a file that has a very long line,  I can repro this issue on Mac and PC, but was wondering if that is the scenario ppl here are seeing.

**Comment by fchristant** [comment] 2017-02-13 23:43
@ungb Thanks for being open to feedback. I cannot structurally reproduce the freeze issue, it appears quite random in my case. I can tell some circumstances from many past freezes though. I don't know if they are the root cause, but they are suspicious:

1. Yes, my most recent freeze was when opening a minified file with a very long line in it. However, this certainly does not only occur for such files, it also happens for normal files. I do believe minified files are a factor, possibly one of multiple root causes leading to a freeze. 

2. When I have a freeze, the biggest frustration is recovering from it. I could live with killing the editor and restarting it. I'd lose only seconds of productivity. 

In reality, I have to reboot Windows, uninstall Atom, remove all packages, start in safe mode, delete appcache data, clear the window state, any combination of the above to hope and pray that it will work again. And often it makes no difference, and I just don't know what else to do. This is the true frustration for me, not the error, simply being unable to recover from it. I cannot afford to troubleshoot an editor for hours just to open a text file. It's a major productivity sink. 

Please don't see that as a complaint. My message is that perhaps there's a lot of root causes leading to a freeze, and it will be hard and take time to solve them all, but perhaps some focus can be applied to make errors recoverable. Maybe Atom can detect that the previous session was corrupted, and correct some things in the next session?

3. Atom does not seem to like networked drives in Windows. It's very sensitive to it. I sometimes develop using a network drive that is mapped to a Linux machine that is a VM on the same computer, mapped via SAMBA. When I start up that server, I can explore the network drive straight away in Windows, yet I learned that I should not start up Atom for about one minute, because starting it too soon means it will never find that drive. Likewise, I should not shut down that server (and thus drive) before first closing Atom, otherwise it will hang indefinitely. And it will remember that hung state next time, even when the drive is available again. 

4. No hard evidence, but I have reason to believe the outside editing of files can cause issues as well. For example, files touched by a build process or Git GUI, which I often use. 

All of the above scenarios I consider common use cases, where I have zero issues in Windows itself, Sublime, Notepad, Notepad++, basically any other editor. 

Sorry for the unstructured dump, I hope it is of some use.

**Comment by jholewinski** [comment] 2017-02-14 14:18
@50Wliu If I disable Fuzzy Finder, I only get one of the processes showing up when atom starts up, but I still have to kill that process before the editor responds.

Starting with --safe does *not* help. The --eval process still spawns, and needs to be killed before the editor responds.

Starting with --clear-window-state does seem to temporarily fix the issue. The --eval process still spawns, but does not appear to block the GUI.

I'm not aware of any source files that I work with having very long lines. 100-120 columns is usually the max. But I can't rule that out.

**Comment by adamreisnz** [comment] 2017-02-14 18:58
@ungb

> Does Atom still freeze up if you open a different project? For example, in cmd/powershell, go to a different directory and run atom .

For me, the freezing happens when I am trying to restart my Mac or shut it down, while Atom is still open. It doesn't seem to matter what project is open, or if there is just one open or more than one. If there's more than one, I'll usually get multiple dialog windows.

> Does this occur after opening a certain type of file? Does the file that is in question, have a single line that is very long?

While opening files with very long lines has a tendency to freeze the editor for me and is still a huge problem, this is *not* what's been happening in the above case. Just normal files with lines < 80 length are open in there.

I am suspecting that this is a problem with Electron rather than Atom itself, as I've had the same thing happening to me with Slack, which is also built on Electron. The same message about window not responding showed up when I tried to shut down the computer.

**Comment by ungb** [comment] 2017-02-15 19:51
Thanks everyone again for the feedback.  There's a [fix for when Atom becomes unresponsive with long single line](https://github.com/atom/atom/pull/13820) in the works, but I know this isn't the only that could cause Atom to not respond.  

I was wondering if those who see the issue where they need to kill a Atom process to respond, if they can try to disable spell-check by running `apm disable spell-check` from powershell/cmd line and then open Atom to see if the issue goes away. Also, those that see freezes on normal files(not long line), try the same thing and see if that fixes the issue.   /cc @jholewinski

**Comment by jonathanmoore** [comment] 2017-02-16 00:17
@ungb Disabling spell-check did not fix the issue for me. Opening a minified JavaScript file like jQuery still would cause Atom to become unresponsive.

**Comment by adamreisnz** [comment] 2017-02-16 00:21
@ungb Not fixing it for my case either. Restarting my mac would still cause Atom to report that it interrupted restart and whether I want to try again or cancel.

**Comment by ungb** [comment] 2017-02-16 00:40
@jonathanmoore The issue with the minified file should  be fixed with https://github.com/atom/atom/pull/13820 which was just merged into master today.  I specifically tested this change with this file: https://code.jquery.com/jquery-3.1.1.min.js and other large single line files.

@adamreisnz, the issue where atom stops mac from shutting down/restarting is probably due to https://github.com/electron/electron/issues/230 since you are seeing this using slack app as well.

**Comment by adamreisnz** [comment] 2017-02-16 00:43
@ungb looks like it, yes, I'll subscribe there. Quite demoralising that the issue has been open for 3 years though... ugh 😢

**Comment by elelowwaydi** [comment] 2017-02-18 08:15
I encountered this issue today and I found a solution that you can try.
before the issue occurred, I was installing a certain package and my internet connection suddenly disconnected and when the connection is back the package installation seemed not responding because it was taking too long to complete so I restarted atom and "the editor is not responding" issue occurred.
Then I went to this atom issue thread and tried @RickvanMiltenburg workaround.
- open task manager
- kill the atom process that has the most ram usage.
the atom starts to respond but after a half minute it won't respond again. 
so I repeated the steps and while the atom was still responding I went to settings -> installed packages and saw the package I was installing a while ago was installed. so I uninstalled it and the issue was gone.

**Comment by AshleyFinney** [comment] 2017-02-21 12:01
I can confirm that my freezes are fixed by disabling spell-check.  If I
enable spell-check while atom is running that process is created and atom
freezes.

**Comment by jholewinski** [comment] 2017-02-22 16:32
@ungb Yeah, it looks like disabling spell-check gets rid of the issue for me! Thanks!

**Comment by albrtogarcia** [comment] 2017-02-23 08:58
Hi, I have had this problem from few months ago, and I confirm that disabling spell-check package solve it.
Thank you all!

**Comment by ungb** [comment] 2017-02-23 20:50
Thanks everyone again for all the input and feedback. I am going to close out this issue, but I want to make sure we have all the capture issues in this issue into separate issues.

Here's a list of issues that are related:  

Spell check:  https://github.com/atom/spell-check/issues/190
Hanging on minified or file with a single long line: should be fixed in beta and next stable release. see pr https://github.com/atom/atom/pull/13820
Anti-virus warning on update.exe: https://github.com/atom/atom/issues/13234

> Atom does not seem to like networked drives in Windows. It's very sensitive to it. I sometimes develop using a network drive that is mapped to a Linux machine that is a VM on the same computer, mapped via SAMBA. When I start up that server, I can explore the network drive straight away in Windows, yet I learned that I should not start up Atom for about one minute, because starting it too soon means it will never find that drive. Likewise, I should not shut down that server (and thus drive) before first closing Atom, otherwise it will hang indefinitely. And it will remember that hung state next time, even when the drive is available again.

@fchristant  can you create a separate issue for this if you can provide detail repro steps for this?  I will try to get this prioritize and fixed in the near future. 


> No hard evidence, but I have reason to believe the outside editing of files can cause issues as well. For example, files touched by a build process or Git GUI, which I often use.

@fchristant  If you are able to get a repro, please file another issue on it with details from the issue template.  I haven't seen this issue before.  

If I'm missing anything, feel free to add a link to the issue.

Thanks everyone!

**Closed by ungb** 2017-02-23 20:50 UTC
Labels: more-information-needed, needs-reproduction

**Comment by adamreisnz** [comment] 2017-02-23 20:56
@ungb as for the issue with shutting down (electron/electron#230), is there any way to create some movement on that issue?

**Comment by 142ayushkumar** [comment] 2017-04-06 18:03
atom freezes when i opened  a file namely 1.txt and run my code on terminal which ave output in this file and then when i opened atom first time it took few seconds to respond and next time when i run the same code and came back to atom it was not responding ,i did force quit then

**Comment by nelson6e65** [comment] 2017-04-07 08:38
**There is a way to auto-close this dialog message when it becomes "responding"?**

Something like:
> _"Oh, never mind... Editor is responding again! :sweat_smile: I'm closing myself . . . * Puff * "_

I got that _"Editor is not responding"_ message **always** when starting Atom. So if I went away for 1 minute when I come back I must to click "Keep waiting" and then it loads and I am able to use it. I meant... A warning for a obsolete state in a modal dialog is kind of... irrelevant for a modal. 

> _"Hey! I'm waiting for you to notice me. Editor was not responding some minutes ago. Now it's fine, but... I'm providing you a **Close** button in case you regret your decision to open Atom."_

**Comment by 50Wliu** [comment] 2017-04-07 13:52
No.  What you are requesting is a feature that has not been implemented in Electron yet.

**Comment by nelson6e65** [comment] 2017-04-09 10:52
Sorry to hear that. 😞 
Thanks for your answer, @50Wliu

**Comment by kuz1toro** [comment] 2017-04-15 07:44
i had the same problem today, and its solve by deleting the history locate in .atom/storage/application.json

**Comment by traffic-camera** [comment] 2017-04-22 20:01
I'm still getting "Editor is not responding" after a clean installation on a new Windows 10 desktop. 

Atom version: 1.16.0 x64
OS: Windows 10 Home x64

How to reproduce: 
-install atom
-open editor
-close editor

About 10 seconds after the editor is closed, I get the "Editor is not responding" popup. **Disabling spellcheck does not fix the issue. Launching with --clear-screen-state does not fix the issue.**

I have not opened any projects or installed any extensions so I don't think a too-long file path is the problem.

**Comment by adamreisnz** [comment] 2017-04-23 01:12
I ran into it again yesterday as well while attempting to restart my Mac. It's really one of the most "pain in the ass" issues that are still out there at the moment.

**Comment by ADTC** [comment] 2017-05-03 11:15
@traffic-camera has just proven that this is a problem with Atom's latest core itself - not because of bloat/plugins/projects/old-version/whatever. Please fix this. Or workaround it at least: increase the time to wait before activating the dialog, **and** have the dialog dismiss itself if no longer necessary.

**Comment by 50Wliu** [comment] 2017-05-03 14:53
> increase the time to wait before activating the dialog, and have the dialog dismiss itself if no longer necessary.

Neither of those are possible yet.  The dialog is displayed when the browser window [detects](https://github.com/atom/atom/blob/03be10414189b195ce4cbb9f11936cf575b15042/src/main-process/atom-window.coffee#L158) that it is unresponsive and there is [no way](https://github.com/electron/electron/issues/5577) to programatically close the dialog.

@traffic-camera The correct command is `clear-window-state`, not `clear-screen-state`.

**Comment by mikecousins** [comment] 2017-05-03 19:44
This still happens all the time. I don't know how this got closed.

**Comment by 50Wliu** [comment] 2017-05-03 20:48
@mikecousins Please open a new issue.

**Comment by mikecousins** [comment] 2017-05-03 20:53
Sure: https://github.com/atom/atom/issues/14346

**Comment by kamilkhoury** [comment] 2017-06-18 01:26
I had the same issues within a nonresponsive Atom editor after numerous reinstallations I was able to somewhat narrowed the issue to GitHub/ssh integration. Once I removed all Github related files and deleted the ssh keys reinstalled Atom and it worked beautifully. Hope this might help some of you as it can be a very frustrating situation.

**Comment by 50Wliu** [comment] 2017-06-20 16:50
@kamilkhoury Yep, we're currently investigating issues related to the new GitHub integration.

**Comment by mikecousins** [comment] 2017-06-20 16:53
This definitely happened before the GitHub integration existed.

**Comment by 50Wliu** [comment] 2017-06-20 16:56
@mikecousins That's the main reason why we closed this issue in favor of opening separate ones: you and @kamilkhoury were experiencing different problems with Atom that both led to the not responding dialog.  Therefore, commenting on this issue doesn't help because instead of being focused on a particular problem, it became a "catch-all" for any and all performance problems.  By splitting it up into more focused issues, we can better identify the causes and fix the underlying problems.

**Comment by fchristant** [comment] 2017-06-20 20:37
I have a different perspective on this. 

It seems that Atom can crash for a whole series of reasons. That is very bad in itself. Text editors should not crash this easily. None of the competitors (Notepad++, Sublime, Visual Studio) crash with such frequency like Atom, if they crash at all. 

If addressing that problem means resolving multiple individual issues, that makes sense. It means general stability will take a very long time to achieve, but if that is the most practical path ahead, sure.

But there's another aspect to it. IMHO, poor recoverability is a far bigger problem. If Atom crashes and I relaunch it in 10 seconds and be back on the productive track, then the crash has little impact. Yet in my experience, I've lost DAYS troubleshooting and recovering just to get it to relaunch and be productive again, if I were to add up time lost across the many crashes. 

To me that was the showstopper, not that it crashed, but that I can't recover from it, without investing swaths of time. Therefore, would it not make sense to invest in crash detection and recoverability as a general issue?

**Comment by lee-dohm** [comment] 2017-06-20 20:54
> Yet in my experience, I've lost DAYS troubleshooting and recovering just to get it to relaunch and be productive again, if I were to add up time lost across the many crashes.

If you're running into this kind of problem and the steps in the [Debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/), most specifically the step of [Clearing Saved State](http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state), doesn't help, please do file an issue with as much information as you can supply for us. We will follow up and do what we can to help out.

> Therefore, would it not make sense to invest in crash detection and recoverability as a general issue?

It absolutely would make sense and if that is a problem, we would like to address it. I haven't heard of recovering from crashes being a problem, so a new issue would be appreciated so that we can investigate.

We want to keep our issues specific and focused so that:

1. We can know that they're fixed
1. We can close them when they're fixed
1. People can know that the problem affecting them is fixed because the issue they opened or are subscribed to has been closed

An issue such as "Atom crashes sometimes" essentially can never be closed because we can't prove that Atom will never ever crash under any circumstances. An issue such as "Atom crashes when I follow these exact steps" can, theoretically, be closed eventually. That's our goal.

**Comment by fchristant** [comment] 2017-06-20 21:56
I don't care that Atom crashes sometimes. Well, I do, but the reality is that there's so many reasons for it to crash, that I lost hope that all of them will be resolved anytime soon in order to reach an acceptable level of stability. 

That I can live with, if I can recover. I see recover-ability as a generic quality of the editor, not a specific one. I'm saying that if the editor crashes and is restarted, it should **always** be able to start, no matter the original crash reason. 

The debug guide is well intended, but please take this the right way, it is ridiculous that a text editor needs a debug guide to open a text file. There should be no debug guide, a text editor should be able to debug itself and just start, it's feature #1. 

I understand the open source mentality, but I think in this case too much burden is placed on a basic user to debug and troubleshoot the very core part of an editor: to not crash, to be able to restart. It seems a specific issue to Atom, as I have zero crashes in any competing editor.

**Comment by adamreisnz** [comment] 2017-06-20 22:22
I have similar (mixed) feelings. Yes I appreciate that Atom is an open source community effort, and debugging is often a part of that, but on the other hand it feels like there are often many hoops to jump through to be able to do successfully do that.

A lot of people will use Atom in a professional capacity, and in light of staying productive, they simply can't afford to close Atom, clear all settings, restart in safe mode, use package cop to narrow down, file a report, restore settings and then go back to normal working mode every time a bug occurs. 

I often face the same dilemma, and when I have the time I'm happy to jump through the hoops and provide meaningful debugging information, but just as often I can't be bothered and just want the editor to bloody work :)

I still love Atom, but I am seeing more and more people in my work environment moving away to for example VS Code, primarily on account of speed and stability. Addressing those issues is thus probably critical if Atom is to maintain a strong user base.

Not really making a point here, just wanted to share my thoughts. Carry on 👍

**Comment by fchristant** [comment] 2017-06-21 08:34
@adamreisnz I feel the same way. I want Atom to succeed, it really is my favorite editor if it wasn't for this instability. 

I've had dozens of small crashes from which I could recover relatively quickly. Whilst this undermines trust in the editor, I love Atom enough to wade through that. However, in at least 3 occasions Atom ruined my entire day. Deeply focused on a project, CRASH, and then spending hours Googling and debugging just to get it to start again. Those days really sting, it is those days you remember, where you switch and just give up. Adding to that productivity sink by reporting on highly specific circumstances feels like a drop in the ocean, even if it is the right thing to do. 

Open source or not, a text editor should open a text file. Always. A text editor should not crash, yet even if it does, it should reopen when you relaunch it. Always. I don't know of a single program in my 25 years of computing that cannot reopen after a crash. I'm repeating myself, but a crash should be recoverable, instantly. I don't know enough about the technical working of Atom to understand whether such a feature is possible at all, but I really hope so.

Please see my rant as tough love :)

**Comment by lee-dohm** [comment] 2017-06-22 17:14
> Open source or not, a text editor should open a text file.

I agree. Additionally:

1. All software has bugs. We're not perfect and we know it.
1. We can't fix bugs that we don't have any information on
1. If we don't encounter a bug ourselves and nobody tells us about a bug they're encountering, we won't have any way to fix it
1. Ranting, tough love or not, about the way things should be doesn't help fix bugs

I've asked in every way I can for help in getting information about these things so that I can help get them fixed. If you're not interested in helping fix things and only feel the need to rant, then please take the ranting someplace else. Our issues list is for tracking the things that we, the Atom maintainers and the people who want to collaborate with us, want to get done.

**Comment by fchristant** [comment] 2017-06-22 19:02
1. Yes, but one bug is not the other bug. Out of all major competing editors, only Atom crashes so often, and worse, can't recover from it. 

2. Which is why you should perhaps listen to my actual point: the editor should be able to recover from a crash on its own. It is not fruitful to chase the countless ways in which Atom crashes. It is much more productive to work on recover-ability at the core of the product.

3. Absurd mentality that makes everything the user's problem. Do you understand that most people will use Atom for what it is for: to code? And that instead of spending half a day debugging or reporting a problem of which the solution will not even address the true problem (recoverability) is a major productivity sink? We're not talking about a minor obscure bug here. We're talking about show-stopping flaws: opening a bloody text file or even opening the editor at all.

You cannot claim that you don't know about this "bug". If that was true, there would be no "debug guide" just to get an editor to start.

4. My "rant" was to point out that instead of solving dozens of crash bugs, perhaps the focus should be on the editor being able to recover on its own, no matter the root cause of the initial crash. It's strategic input. You're free to disagree or think it's a dumb idea.

I cannot give you bug "information" because of my point above: this is not a singular bug, it's a strategic feature request: general recoverability. You cannot address this by addressing one of many crash root causes.

Agreed though that this is not the place, I won't bother anymore.

**Comment by tamethecomplex** [comment] 2017-06-22 19:28
My two cents...  I love Atom and I use it every day.  I have noticed a significant decline in my crashes over the past couple of releases.  When all else fails, I use the above mentioned:

`atom --clear-window-state`

And the editor basically always recovers.

**Comment by lee-dohm** [comment] 2017-06-22 21:36
> Absurd mentality that makes everything the user's problem.

@fchristant this comment is a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. You may consider this an official warning.

I consider it insulting and derogatory because I have done nothing but try to help. I have offered help in multiple ways. At each attempt, you have told me that my help isn't good enough for you. This is not making it your problem, this is you refusing my attempts to help, which is absolutely your right. But I refuse to take the blame for not helping when you tell me not to.

**Comment by fchristant** [comment] 2017-06-23 00:26
You dismissed the entire content of my message (recoverability) and instead of actually responding to that, you take a fragment out of context as to prove I'm launching some personal attack against you.

I've never said you're not helpful, and nothing about it is personal. Disagreeing on something is not an attack. "Saying your help isn't good enough" is putting words in my mouth that I haven't even remotely said. I'm not refusing your help, the help you offered is to submit debug info, which misses the point of my input:

I explained twice already how I believe that instead of chasing 20 bug reports and wait forever for them to be solved, perhaps there should be focus on another feature: Atom being able to recover from a crash. If Atom can recover from a crash, users are back into productivity in 5 seconds. The impact of a crash, for whichever reason it happens, will then be near-zero. If Atom cannot recover from a crash (like currently), productivity lost can be hours or more, and a reason to abandon the product altogether, worst case.

Is this such a crazy reasoning to follow? I don't know of a single program that cannot be relaunched after a crash, except for Atom. There's tons of threads full of crash reports where users are trying many tricks in order to recover. Some recover instantly, others try everything in the debug guide and still fail. None of that would be needed if Atom can self-repair. 

So that's the input and the feature request: Atom being able to recover from a crash, any crash. There's nothing personal about it, it's just input to deal with the infamous "editor is not responding" message that so many people get. 

Maybe it's not possible. Or too much work. Or too generic input. In that case, at least I tried, even though you experience it as negative input.

**Comment by adamreisnz** [comment] 2017-06-23 00:42
It's probably a good idea to stop this discussion now as it's not very productive and derailing this thread. I wouldn't want the issue to get closed like many similar ones have, because that will be counter productive and prevent other users from being able to provide issue feedback.

As for on-topic -- I don't fully understand why you think that Atom can't recover from a crash. Atom rarely crashes outright for me, but if it does, there is no problem restarting it. 

Is this perhaps something related to your OS or version of Atom? Have you tried using another Atom version (e.g. beta, or dev), and are you experiencing this on other computers as well? What Atom version do you use?

**Comment by lee-dohm** [comment] 2017-06-23 00:47
> I wouldn't want the issue to get closed like many similar ones have,

This issue is already closed. Hence the reason why I've been suggesting people file a new issue.

**Comment by adamreisnz** [comment] 2017-06-23 00:56
Sorry, I meant closed for comments

**Comment by mikecousins** [comment] 2017-06-23 03:08
Yup, I opened a new one, but it seems stalled out.

https://github.com/atom/atom/issues/14346

**Comment by MattCz** [comment] 2017-07-16 16:11
I switched to Atom very recently from notepad++. F*ck it, I have to come back to np++ again as this shit cannot open files... terrible 👎

**Comment by ungb** [comment] 2017-07-16 20:50
To try to keep things constructive and productive I'm going to lock this thread.  For those that see similar issues to this, please file another issue and fill out the issue template and all the details you can for reproducing the issue.   You can even reference this issue if you see anything useful here.  

Also, Feel free to cc me and I can help take a look.
