### ISSUE TITLE
Redo not working bug?

### ISSUE THREAD

**Issue by tomcwatts** [atom/atom#7572] opened 2015-06-30 06:44 UTC
I cannot seem to replicate the bug I encountered, But I figure it's probably worth checking for an issue.
After writing some 50 lines of CSS, and then using CMD+Z to undo about 30 of those lines and saving, I was unable to CMD+Y to Redo that code I removed. I was luckily able to get it back through via the dev tools. Haven't been able to replicate the issue, but for now I'm going to switch back to my previous editor to be safe.

Using the new Version 1.0, with only 3 extra plugins: Autoprefixer, Atom-terminal and emmet.

**Comment by WolfieZero** [comment] 2015-07-03 15:31
I've also found a similar issue where I cannot redo/undo changes, or if I can I have to press keep pressing the keys (this has happened on different keyboards/systems); 2-3 times seems to be the magic number if this is the case.

[See my configs](https://gist.github.com/WolfieZero/a40c15e3492a70476eaa)

**Comment by francismozart** [comment] 2017-07-22 13:47
I've just had the same problem.

**Comment by andrew-davie** [comment] 2017-08-06 10:04
Same issue here.  I run "beautify" before a compile, which saves. Redo lost.

**Comment by Ben3eeE** [comment] 2017-08-08 10:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/9637. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-08 10:52 UTC
Labels: duplicate
