### ISSUE TITLE
Using underscore at the beginning of text affects syntax highlighting

### ISSUE THREAD

**Issue by oleersoy** [atom/atom#6518] opened 2015-04-25 18:20 UTC
For example the following works fine:

## Box Sizing:
`_base.css`

But if I remove the ticks like this:
## Box Sizing:
_base.css:

Syntax highlighting no longer works for the text that follows

**Comment by 50Wliu** [comment] 2015-04-25 19:25
@oleersoy what language is this?  Does this happen for all languages?  Can you reproduce this in safe mode (`atom --safe`)?  What Atom version is this?  Thanks.

**Comment by oleersoy** [comment] 2015-04-25 22:45
On 04/25/2015 02:25 PM, Wliu wrote:
>
> @oleersoy <https://github.com/oleersoy> what language is this?
>

Actually my original description is off.  It's for the highlighting that atom does in general for markdown documents.  If I start a word with the underscore character, it effects the application of colors to all subsequent text.  For example if I write a header like this:

`## _base`

The coloring of all text that follows will be one color.

The same thing happens if I start a word with a underscore in a paragraph.
>
> Does this happen for all languages?
>
Right now I'm only seeing this within markdown documents.
>
> Can you reproduce this in safe mode (|atom --safe|)?
>
Yes it also does it in safe mode.
>
> What Atom version is this? Thanks.
>

    v0.194.0 (2015-04-22)

Running on Ubuntu 14.04
Thanks for making Atom.  Love the editor!

**Comment by lee-dohm** [comment] 2015-04-25 23:21
This sounds like a duplicate of atom/language-gfm#84 (just using `_` instead of `*`).

**Comment by 50Wliu** [comment] 2015-04-25 23:34
Closing as a duplicate of atom/language-gfm#44 instead (since I just closed 84).
@oleersoy, you can subscribe there in order to get updates to the issue.

**Closed by 50Wliu** 2015-04-25 23:34 UTC
Labels: more-information-needed
