### ISSUE TITLE
racer.racerBinPath is not set in your config.

### ISSUE THREAD

**Issue by topksharma** [atom/atom#11569] opened 2016-04-22 07:57 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

racer.racerBinPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -0:24.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:24.1.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "editor": {
    "fontSize": 19
  }
}
```

### Installed Packages

```coffee
# User
d-struct, v1.0.4
language-d, v3.2.2
language-rust, v0.4.6
racer, v0.20.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-04-22 15:19
This is a duplicate of edubkendo/atom-racer#64 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-22 15:19 UTC
