### ISSUE TITLE
Space invisibles disappear when used for alignment(not indent)

### ISSUE THREAD

**Issue by polarathene** [atom/atom#11724] opened 2016-05-10 04:31 UTC
### Description

The invisible character for spaces disappears once I enter some text. I can understand this being desirable but only expected it to omit the space invisible char when a single space between text occurred. 

Tab invisibles still render as can be seen in [this bug report](https://github.com/atom/atom/issues/10733), I was confused with the actual code I was looking at wondering if the alignment was tabs/spaces/mixed or some other invisible since space invisibles were not rendering.

Code snippet:
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
	<style>
		h1 {
			font-size:     
			font-size      test
			font-size:     70px;
			font-size:     
		}
	</style>
<head>
</html>
```
Image:
![invisibles bug](http://i.imgur.com/HIhg9jw.png)

I can verify the same issue with a new JS file `var test =            'space aligned, invisibles don't show'` as well so it's not language specific.

### Steps to Reproduce

1. Create a new file.
2. Note how aligning text with spaces the space invisibles disappear once text occurs. Not the same if tabs are used where they still render.

**Expected behavior:** Invisibles for spaces should still render between text if the length is greater than 1, else an optional render option for this should exist.

**Actual behavior:** Unlike tab invisibles space invisibles disappear.

### Versions
Atom 1.7.3 OSX 10.11.3

**Comment by Ben3eeE** [comment] 2016-05-10 06:30
I reported the same effect in the third set of steps I described over in https://github.com/atom/atom/issues/11630. Difference is my steps breaks soft wrapping when the invisibles disappear while this is all on the same line.

// cc @lee-dohm master of referenced issue.

**Comment by lee-dohm** [comment] 2016-05-10 21:38
This is a duplicate of #2572. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-05-10 21:38 UTC
