### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by filipkofron** [atom/atom#7420] opened 2015-06-25 19:38 UTC
1. Open project
2. Right click for context menu on any project folder/file

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro N
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\filip_000\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -4:13.2.0 core:backspace (atom-text-editor#editor.fontSize.editor.mini.is-focused)
     -1:37.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "atom-terminal"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Ubuntu Mono",
    "confirmCheckoutHeadRevision": false,
    "lineHeight": 1.3
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
color-picker, v2.0.7
language-coffee-script-angular, v2.2.0
language-scala, v1.1.3
minimap, v4.10.0
pigments, v0.8.0
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-06-25 19:41
This is a duplicate of https://github.com/atom/atom/issues/7420 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-25 19:41 UTC
