### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by driuha** [atom/atom#6950] opened 2015-05-26 07:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\app.asar\src\window-event-handler.js:149:33)
    at HTMLDocument.handler (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\DaPimp\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -0:37.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -0:34.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:31.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:31.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:31.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:31.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:29.7.0 grammar-selector:show (atom-text-editor.editor)
 14x -0:27.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:23.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:22.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:22.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
  2x -0:22.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-05-26 07:46
Thanks for the report -- looks like a duplicate of https://github.com/atom/atom/issues/6548.

**Closed by izuzak** 2015-05-26 07:46 UTC
