### ISSUE TITLE
Windows defender quarantining Atom 1.0.4 as malware

### ISSUE THREAD

**Issue by simonbuerger** [atom/atom#8246] opened 2015-08-06 07:48 UTC
See discussion https://discuss.atom.io/t/windows-10-defender-atom-exe-malware/19645 - apparently it's not just me. Seems to mostly be people on Windows 10.

atom.exe is being quarantined as being infected with TrojanDownloader:Win32/Lerspeng.B ([Malware protection center page](http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=TrojanDownloader%3aWin32%2fLerspeng.B&threatid=2147686694&enterprise=0&wa=wsignin1.0#tab=1))

Hopefully it's just a false positive, but obviously it's a massive problem for Windows users.

**Comment by CmdrCupcake** [comment] 2015-08-06 07:54
My 1.0.4 atom.exe is being quarantined as being infected with Backdoor:Win32/Kelihos.F ([Maleware center page](http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Backdoor%3aWin32%2fKelihos.F&threatid=2147655469&enterprise=0))on Windows 10.

**Comment by Zireael07** [comment] 2015-08-06 07:59
Duplicate of #3927. (seriously, just search for "malware" before making an issue)

**Comment by tinymins** [comment] 2015-08-06 07:59
![image](https://cloud.githubusercontent.com/assets/1808990/9106601/14ce411e-3c54-11e5-9085-88d012d5367d.png)
![image](https://cloud.githubusercontent.com/assets/1808990/9106593/0e942a70-3c54-11e5-8c80-6e3cd2d188a7.png)

**Comment by paulcbetts** [comment] 2015-08-06 08:00
@Zireael07 I'm not so sure, the others were all reputation-based or generally bullshit, this seems far worse

**Comment by paulcbetts** [comment] 2015-08-06 08:01
@tinymins, @CmdrCupcake, @simonbuerger Can all of you get a SHA1 or MD5 hash and the file size of your Atom.exe?

**Comment by tinymins** [comment] 2015-08-06 08:02
文件: C:\Users\diyiming\AppData\Local\atom\app-1.0.4\atom.exe
大小: 7207936 字节
文件版本: 0.22.3
修改时间: 2015年8月6日, 16:01:42
MD5: 3621AF2D067448B969557DFDA7066DD7
SHA1: 5A2788BEE32D6A4E1A4B11E8CD987CC2FF074C1A
CRC32: 49674D34

**Comment by paulcbetts** [comment] 2015-08-06 08:05
Hm, that's what I have. @kevinsawicki, the binary inside the NuGet package isn't signed, I think that we need to fix the build to sign this. If you switch to using Squirrel's built-in signing, it should take care of this for you

**Comment by beckerc** [comment] 2015-08-06 09:49
Tried to reinstall it but it didn't work, it seems Kelihos.F is in the source code.

**Comment by Fat-Chocobo** [comment] 2015-08-06 11:08
I'm also getting the same.

**Comment by almostearthling** [comment] 2015-08-06 11:38
Does anyone know if the same problem arises using v1.0.3?

F.

**Comment by jaypanares** [comment] 2015-08-06 11:56
Also experiencing the issue on Windows 10.  I first noticed when Atom was not launching when I wanted to use it.  I uninstalled and tried to reinstall but then Windows Defender keeps popping up that malware was detected.  Had to uninstall Atom, turn off Defender, install Atom and then uninstall again to do a clean uninstall (the first uninstall didn't remove the context menu action).  So far still having Defender detect it as malware.

**Comment by almostearthling** [comment] 2015-08-06 12:04
> Does anyone know if the same problem arises using v1.0.3?

Just for the record, it looks like v1.0.3 doesn't make Windows Defender angry.

F.

**Comment by bagong** [comment] 2015-08-06 14:23
On Win 8.1 too!

**Comment by beckerc** [comment] 2015-08-06 14:37
What I did to make Atom work again:
1. Uninstall Atom
2. Go to %localappdata%/Atom and remove everything
3.  Put folder %localappdata%/Atom to ignore list in Windows Defender
4. Install Atom again.

**Comment by kevinsawicki** [comment] 2015-08-06 17:31
>  the binary inside the NuGet package isn't signed, I think that we need to fix the build to sign this. If you switch to using Squirrel's built-in signing, it should take care of this for you

You mean `atom.exe` isn't signed?

**Comment by kevinsawicki** [comment] 2015-08-06 18:00
Working on a fix for the codesigning issue over in https://github.com/atom/atom/pull/8254

**Comment by kevinsawicki** [comment] 2015-08-06 22:10
I've just released Atom 1.0.5 with some code-signing additions, can people try re-downloading it from https://atom.io and see if it addresses this problem? Thanks.

**Comment by almostearthling** [comment] 2015-08-06 23:18
It works for me, tested on Windows 10 32bit. Same setup as earlier, unless Windows Dwfwnder silently updated something.

F.

**Comment by CmdrCupcake** [comment] 2015-08-07 03:36
1.0.5 works for me on Windows 10 64bit.

**Comment by jaypanares** [comment] 2015-08-07 03:50
Installed and working so far without issues.  On Windows 10 64-bit.

**Comment by simonbuerger** [comment] 2015-08-07 08:06
@kevinsawicki Thank you :) Also all fine for me so far on 1.0.5, should I close?

**Closed** 2015-08-07 14:20 UTC
Labels: installer, windows

**Comment by kevinsawicki** [comment] 2015-08-07 15:13
@almostearthling @CmdrCupcake @jaypanares Thanks so much for confirming :+1: 

@simonbuerger Thanks so much for raising this issue :+1:

**Comment by CrafterSama** [comment] 2017-01-25 15:58
I am joining to this discussion to post this, 
Trojan in Version 1.13.0
![trojan_atom](https://cloud.githubusercontent.com/assets/1966205/22297985/55f85dac-e2f5-11e6-97f5-7202b84a19a9.png)

**Comment by Zireael07** [comment] 2017-01-25 16:04
HEUR means it's heuristics, and most AV software is prone to false positives when it comes to heuristics...

Also, 360 total security? seriously?
