### ISSUE TITLE
Atom 1.27.1: Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by erinachavez** [atom/atom#17391] opened 2018-05-22 21:39 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom seems to have auto-updated and I now cannot open it without this issue appearing.

![image](https://user-images.githubusercontent.com/25967093/40391379-03e22b02-5de6-11e8-9651-e8e02332db1e.png)

Nothing is clickable except for the debugging console on the right. When I try to close that window, it just turns white, and freezes the program.

![image](https://user-images.githubusercontent.com/25967093/40391391-0c95db54-5de6-11e8-80b9-31c0ee2cc8ae.png)

I've tried restarting my computer, reinstalling, installing 1.27.0, but every time I open atom, this keeps happening exactly. Advice?

### Versions
atom --version
Atom: 1.27.1
Electron: 1.7.15
Chrome: 58.0.3029.110
Node: 7.9.0

apm --version
apm 1.19.0
npm 3.10.10
node 6.9.5 x64
atom 1.27.1
python 3.6.3
git
visual studio

Windows 10 Pro

**Comment by rsese** [comment] 2018-05-22 23:16
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16892 so you can subscribe there for updates if you'd like.

To get around the error, people mentioned that clearing saved state helped (save any unsaved data first):

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-22 23:16 UTC
