### ISSUE TITLE
Dragging and dropping a file from the file system occasionally opens it as Chromium instead of Atom

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#4300] opened 2014-11-24 10:52 UTC
Atom's drag&drop feature seem quite buggy. Sometimes it just won't open a dragged file, but even worse bug is when decides to open the file as if it was a real browser, efectively replacing the entire editor with the content of the file.

Video: http://youtu.be/EPRRFs9SQbs

**Comment by alexandernst** [comment] 2015-06-17 13:05
This is still easiily reproducible with Atom .209

**Comment by mnquintana** [comment] 2015-06-17 13:15
@alexandernst Could you post a Gist of a file that consistently reproduces this for you?

**Comment by alexandernst** [comment] 2015-06-17 13:17
@mnquintana every file will do it. Just drag&drop fast a random text file to Atom and you'll get the bug.

**Comment by mnquintana** [comment] 2015-06-17 13:18
What OS are you on?

**Comment by alexandernst** [comment] 2015-06-17 13:20
Debian Lnux with KDE 4.11
Do you want me to make a new video?

**Comment by mnquintana** [comment] 2015-06-17 13:26
Hmmm, this looks like an instance of https://github.com/atom/electron/issues/908, which should have been fixed in atom-shell 0.20.1 (back when Electron was atom-shell) and [Atom's on atom-shell 0.22.3 now](https://github.com/atom/atom/blob/master/package.json#L20). 

/cc @zcbenz @paulcbetts @kevinsawicki

**Comment by ObviouslyGreen** [comment] 2015-07-21 19:24
I can reproduce this in Windows 8 using Atom Version 1.02
![image](https://cloud.githubusercontent.com/assets/4269549/8810126/bf28803a-2fa1-11e5-86db-db902b78af2d.png)

Very common when I want to open up another file really quick just to check something, have to close out of atom and reopen again. Sometimes it just closes Atom completely, end up having to end Atom in the task manager in order to restart it.

It seems like it only happens to me when I drag and drop quickly. For example, problem doesn't occur when I drag and drop over a two second time frame, but does over a 0.2 second time frame. Problem doesn't happen unless I have a project folder open in my experience.

**Comment by alexandernst** [comment] 2015-09-10 00:44
@mnquintana Were you able to repro thsi bug?

**Comment by 50Wliu** [comment] 2015-09-10 00:58
Confirmed on Windows 10 x64, Atom 1.0.11.

**Comment by zcbenz** [comment] 2015-09-10 03:09
Yeah preventing the `will-navigate` event will do the trick.

**Comment by alexandernst** [comment] 2015-09-10 18:57
@zcbenz Can we get a patch for this if the bug is trivial? (I'm saying this because you added the `beginner` tag).

**Comment by zcbenz** [comment] 2015-09-11 01:16
Yes the fix is trivial, I added `beginner` label so newbies can have a try. It is also on my TODO list, I'll fix it in future if no one takes care of it.

**Comment by thomasjo** [comment] 2015-10-09 23:30
Would be brilliant if someone here could test whether https://github.com/atom/atom/pull/9101 resolves this bug or not :bow:

**Comment by alexandernst** [comment] 2015-10-10 19:48
Can the patch be applied on top of latest stable?

**Comment by thomasjo** [comment] 2015-10-10 19:55
> Can the patch be applied on top of latest stable or is master required?

Should be trivial to rebase this on top of `stable`.

**Comment by alexandernst** [comment] 2015-10-12 11:53
I tried building `stable`, but I get an error while compiling (https://paste.kde.org/ptutyoj3u), then I tried latest beta and the build went fine, but I get errors as soon as I open Atom, so I wasn't able to test the patch.

**Comment by thomasjo** [comment] 2015-10-12 11:57
@alexandernst Try using a newer version of npm. Node v4.1.1 ships with npm v2.14.4 IIRC, so you should at least be using that (or newer).

**Comment by alexandernst** [comment] 2015-10-12 14:30
@thomasjo Can't get that newer on my Debian. Let's see if somebody else can test the patch, or I'll have to setup a VBox.

**Comment by mnquintana** [comment] 2015-10-12 14:36
@alexandernst Have you tried out [nvm](https://github.com/creationix/nvm) at all? That should let you easily install and manage multiple Node versions without having to rely on the Debian package being updated.

**Comment by alexandernst** [comment] 2015-10-12 14:40
@mnquintana I'd rather setup a VBox, really. Installing multiple *things* feels absolutely hacky and I can't let such a thing happen on my work machine.

**Closed** 2015-10-12 19:01 UTC
Labels: atom, beginner, bug, linux, windows
