### ISSUE TITLE
Clicking package title of uninstalled package in Install search list does nothing

### ISSUE THREAD

**Issue by AgentME** [atom/atom#5061] opened 2015-01-14 19:46 UTC
If you go to preferences, open the Install page, enter something into the search form, then a list of packages will show up. Their titles will be styled as links, but clicking on the titles of uninstalled packages does nothing. (I'd expect it to go to a page about that package, or at least open the package's page on atom.io in a browser window.) Clicking the title of an installed package brings you to an atom page for the package that gives you more info about the package.

Atom 0.170.0 on OS X

**Comment by kevinsawicki** [comment] 2015-01-14 19:52
I believe this is a duplicate of https://github.com/atom/settings-view/issues/328

**Closed by kevinsawicki** 2015-01-14 19:52 UTC
