### ISSUE TITLE
Feature: Profiles

### ISSUE THREAD

**Issue by vdun** [atom/atom#12411] opened 2016-08-13 01:22 UTC
Let's say I make 'profileCpp' which has C++ packages that I choose to install. Once enabled it will load these packages.
Thus no need to load all my C++ packages everytime atom is launched (speedup)

**Comment by mnquintana** [comment] 2016-08-13 02:07
This is a duplicate of https://github.com/atom/atom/issues/6619 – feel free to subscribe there for updates.

Also, please read the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#suggesting-enhancements) next time before opening a new issue – it includes a section on searching for an existing issue first.

**Closed by mnquintana** 2016-08-13 02:07 UTC
