### ISSUE TITLE
Crash after selection of 'Application Install Update'

### ISSUE THREAD

**Issue by pantuts** [atom/atom#9374] opened 2015-10-31 15:46 UTC
* Please delete this issue if it is a duplicate.

Atom: Installed from source and currently using 1.2.0-beta0-2ec1b18
OS: Manjaro Linux x86_64

Editor crashes always when I do CTRL+SHIFT+P then choose Application Install Update.
I do not know where is the log file. Please tell me what to do for how to get more information for this issue. Thanks.

**Comment by 50Wliu** [comment] 2015-11-01 16:47
Interesting.  This might be happening because Linux doesn't have an auto-updater.

**Comment by ghigt** [comment] 2015-12-07 13:54
I also have this issue on my ubuntu VM and on my Windows host machine. (not sure, but I think I also have the issue on my Mac)

**Comment by NiotoMOto** [comment] 2015-12-07 13:57
:+1

**Comment by pantuts** [comment] 2016-01-14 14:33
Current: 1.4.0-beta3-385721a

It is not crashing anymore but when Application Install Update is selected, it does nothing.

**Comment by lee-dohm** [comment] 2016-01-15 00:20
@pantuts Sounds like you built from source at the v1.4.0-beta3 tag?

**Comment by pantuts** [comment] 2016-01-15 02:07
@lee-dohm correct.

**Comment by lee-dohm** [comment] 2016-01-15 02:09
When you build from source, the only way to update is to build from source again or install a released version.

**Comment by lee-dohm** [comment] 2016-01-15 04:26
To be clear, perhaps this menu item should have a notification that comes up that informs people of this.

**Comment by pantuts** [comment] 2016-01-15 06:49
Is Application install update specific to atom update only? how about its installed packages?

**Comment by lee-dohm** [comment] 2016-01-15 17:48
Yes, it is only to update the application. Packages are updated in the Settings View.

**Comment by gnanadeeptu** [comment] 2016-09-14 20:28
@pantuts May I know why this bug was closed? Today I encountered this issue on my MAC machine. This was labeled as `**needs-reproduction**`, not sure if that is still the case.

**Comment by pantuts** [comment] 2016-09-15 04:59
@gnanadeeptu I did close this because when I updated and had latest builds, it disappeared. Let me reopen this one.

**Comment by 50Wliu** [comment] 2016-09-15 14:30
I'm going to keep this closed as this bug applied only to Linux and not Mac.

@gnanadeeptu Please open a new issue.

**Closed by 50Wliu** 2016-09-15 14:30 UTC
Labels: bug, linux, needs-reproduction
