### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by dcro** [atom/atom#14425] opened 2017-05-16 08:36 UTC
I got this error while typing in an editor but I wasn't able to reproduce it later.

**Atom**: 1.17.0-beta5 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /Applications/Atom Beta.app/Contents/Resources/electron.asar/renderer/api/remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Applications/Atom Beta.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (/Applications/Atom Beta.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:663:1)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:697:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:184:1)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:1
```

### Commands

```
  3x -0:36.5.0 core:select-left (input.hidden-input)
     -0:35.7.0 core:select-right (input.hidden-input)
     -0:35.3.0 core:backspace (input.hidden-input)
     -0:35.1.0 core:save (input.hidden-input)
  2x -0:28.6.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:27.9.0 core:select-down (input.hidden-input)
     -0:27.5.0 core:backspace (input.hidden-input)
     -0:25.7.0 core:paste (input.hidden-input)
     -0:25 core:undo (input.hidden-input)
     -0:21.7.0 core:copy (input.hidden-input)
     -0:20.7.0 core:paste (input.hidden-input)
     -0:16.8.0 core:backspace (input.hidden-input)
     -0:14.3.0 core:select-right (input.hidden-input)
     -0:14 core:backspace (input.hidden-input)
  2x -0:13.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:13.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
alignment 1.1.5 
api-docs 0.0.6 
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.24 
atom-typescript 11.0.3 
base64 0.3.0 
blade-snippets 0.2.0 
busy-signal 1.4.1 
editorconfig 2.2.2 
elasticsearch-client 0.9.5 
file-icons 2.1.5 
intentions 1.1.2 
language-blade 0.30.0 
language-docker 1.1.7 
language-dots 0.0.4 
language-nginx 0.7.3 
language-vue 0.21.2 
laravel 0.7.1 
linter 2.1.4 
linter-eslint 8.1.7 
linter-js-yaml 1.2.7 
linter-php 1.3.2 
linter-phpcs 1.6.4 
linter-stylelint 3.10.0 
linter-ui-default 1.3.0 
merge-conflicts 1.4.4 
pigments 0.39.1 
pretty-json 1.6.3 
project-manager 3.3.4 
```

**Comment by 50Wliu** [comment] 2017-05-16 13:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #11692. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-16 13:29 UTC
