### ISSUE TITLE
touch-screen rolling is not working for text-editing panel

### ISSUE THREAD

**Issue by QZSAMA** [atom/atom#17127] opened 2018-04-12 20:14 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Touch-screen scrolling feature for text-editing panel.
For welcome panel and project-files panel works fine, but for the text-editing panel, it doesn't work.

### Steps to Reproduce

1. open atom
2. open a file or input enough-length of text
3. try to use finger/pen to scroll the test 

**Expected behavior:** 
Expected finger/pen can scroll it up/down
**Actual behavior:** 
only allow click action
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0-beta1
python 2.7.14
git 2.10.2.windows.1
visual studio 2015

### Additional Information
the feature works in sublime-test3 so maybe we can also add this feature in atom.

**Comment by rsese** [comment] 2018-04-12 21:31
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/2209 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-12 21:31 UTC
