### ISSUE TITLE
Can't read "large" files

### ISSUE THREAD

**Issue by KrisZane** [atom/atom#12967] opened 2016-10-13 12:47 UTC
### Description

The editor consistently crashes while loading files larger than 3MB.

I am suspecting this has to do with the way the file is loaded or all of the different modules applied to it, resulting in rather large data sets and/or operations.

I would suggest that if a larger file is detected, it either switch to using a streaming file load and only loading what is currently seen or that automatic markup/module runs and what not are automatically disabled for large files.

3MB is a rough estimate of about 3-4000 lines of code, so this would also essentially cause trouble with writing larger blocks of code or larger libraries.

### Steps to Reproduce

Load a file larger than 3MB

**Expected behavior:** Open the file for viewing

**Actual behavior:** Editor hangs or crashs

### Versions
1.10.2

**Comment by 50Wliu** [comment] 2016-10-13 14:13
This is a duplicate of #8864 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-13 14:13 UTC
