### ISSUE TITLE
Mouse clicking doesn't work after trying to close a tab using wheel click

### ISSUE THREAD

**Issue by bger** [atom/atom#15261] opened 2017-08-11 17:14 UTC
Clicking mouse wheel on a not saved file blocks subsequent mouse clicks. You are shown a pop-up with warning that file was changed, but you can't click on the  buttons - Save, Cancel or Don't save. You also can not click on workspace, launcher buttons, etc. Only a keyboard is available, so you can close modal window via Esc press or Alt + F4.

### Steps to Reproduce

1. Change any file - new or existing, but don't save it
2. Click on the file tab using a mouse wheel to close it
3. Modal window with warning about unsaved files appears
4. Try to click any button or another program window

**Expected behavior:** Mouse clicking should work - you can close the modal window or switch to another program

**Actual behavior:** Mouse clicking doesn't work

**Reproduces how often:** Always

### Versions
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
Ubuntu 16.04 LTS 64-bit

**Additional information
If you close a tab by clicking on tab's cross, all is ok. The same is true for Ctrl + w combination.

**Comment by Ben3eeE** [comment] 2017-08-11 18:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15197. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-11 18:52 UTC
Labels: duplicate
