### ISSUE TITLE
Git Ignore **

### ISSUE THREAD

**Issue by xcrap** [atom/atom#16952] opened 2018-03-15 12:12 UTC
### Description

I have a problem when I have a special ignore in Git like /images/**/
This should ignore all subfolders in "images" but not the files within, in Git it works perfectly but in Atom it shows the images folder empty without the files in the tree view panel, when the files should appear except the sub-folders.

### Versions
Version 1.24.1

**Comment by lee-dohm** [comment] 2018-03-15 16:26
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/100. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2018-03-15 16:26 UTC
