### ISSUE TITLE
Atom unresponsive when switching between windows on desktop

### ISSUE THREAD

**Issue by crobinson42** [atom/atom#8851] opened 2015-09-18 20:04 UTC
The Atom window becomes unresponsive for 3-5 seconds when I take focus away from the window to another ie: Chrome, then back to Atom. this started happening after I added multiple project folders in the the file tree.

**Comment by avdg** [comment] 2015-09-21 13:57
Hmm.. if you are running a lot of programs at the same time, it could be that your computer was using a lot of memory. It's a long explanation, but if you want you can just provide operating system and memory usage / memory available if you can or want.


At least, the hypothesis goes as following:

If your computer uses more memory than it can hold in memory, it will try to swap memory, known as dumping memory on the (relative very slow) storage device so there is memory available to the system (which probably still is a hard disk these days, but ssd's are becoming more common).

Every time your computer swaps it can happen that the computer freezes, especially if it takes a lot of time to make it happen.

Though on the newer linux editions, os x 10.9 or later and the yet publicly unreleased (slow ring) windows 10 build 10525 (this build is a fast ring, known as a candidate for slow ring) all support memory compression to delay that.

How to detect: most systems have a control panel to check memory, if there is memory in swap, its likely to blame swap if the processes involved (in this case chrome and atom) are memory heavy.

How to solve: use less memory by using less apps, apps that consume less memory, or add more memory.

**Comment by crobinson42** [comment] 2015-09-21 19:20
I quickly learned the delay was because of the re indexing of each projects GIT. It does not do this with smaller project folders.

**Comment by phord** [comment] 2015-10-15 20:27
@crobinson42 is right.  It is because Atom reindexes all the git projects in onFocus for some reason.  It seems like Atom should monitor file activity even when it doesn't have the focus and this reindex should not be necessary.  But I haven't experimented with the effects of turning it off myself.

**Comment by MatthewHerbst** [comment] 2015-10-28 22:07
Experiencing this with Atom 1.0.19, OSX 10.10.5, with plenty of free memory (according to Activity Monitor reporting)

**Comment by neumond** [comment] 2016-04-03 05:46
Crosslinking my report here too: https://github.com/atom/atom/issues/10107#issuecomment-204879670

**Comment by Zireael07** [comment] 2016-04-03 07:12
Why re-index all git on focus? Also I think there was some work on reducing I/O recently, didn't it fix it?

**Comment by dthettich** [comment] 2016-04-06 07:58
@crobinson42 I can confirm it is the indexing of larger git repos.
When 'tree-view' package is disabled, Atom becomes responsive again. Obviously on the cost of navigating through the project.

**Comment by binhonglee** [comment] 2016-09-09 06:26
Seems like this is still unfixed. Any work around suggestion aside from as @dthettich mentioned, disabling the 'tree-view' package?

**Comment by d4rkd0s** [comment] 2016-12-12 18:34
@binhonglee doesn't seem like theres a fix...? I tried disabling tree-view with no luck still 500-800ms of delay before I can begin typing again once I focus Atom.

Does anyone know when this started? I don't remember this happening on older versions of Atom. I'm thinking about downgrading. I've tried fresh installs, different computers. Same issue. Slight delay when refocusing on Windows. Its NOT git related for me. Using blank/empty files. I have an i7 3700k and 16GB of RAM and an SSD + GTX1070 I shouldn't be having this near 1 second lag with Atom. Every other program I run doesn't have this issue.

Is there any more information on this? Anyone?

**Comment by paul-alkhimov** [comment] 2017-01-12 10:27
Just my two cents:

For me the problem was in "svn" plugin (I work on 16+GB svn project). I had a constant lag for 4-5 seconds.
After disabling only the "svn" plugin, the lag disappeared completely.

Unfortunately the "svn" plugin is unusable as-is in my case, unless developers decide to move in async/background direction.

**Comment by d4rkd0s** [comment] 2017-01-18 20:53
Anyone here just be SURE to stay tuned on #9544

Thats where the git related slowing is being looked at / fixed.

**Comment by iolsen** [comment] 2017-09-27 22:18
Fixed by https://github.com/atom/git-utils/pull/80. Shipping in 1.22.

**Closed by iolsen** 2017-09-27 22:18 UTC
Labels: git, performance
