### ISSUE TITLE
Restart and Update not working on OSX

### ISSUE THREAD

**Issue by ashrayjain** [atom/atom#7001] opened 2015-05-29 08:39 UTC
Clicking "Restart and Update" from the release notes page or the Atom menu causes Atom to close and fail to restart. Moreover, upon restarting manually, Atom is not updated.

I have tried clearing the ~/.atom/storage directory, as suggested [here](https://github.com/atom/atom/issues/5692#issuecomment-93859017) but it doesn't solve the problem here.

Platform: OSX 10.10.3, Atom 0.201.0

**Comment by izuzak** [comment] 2015-05-29 08:43
How long did you wait for Atom to restart after clicking "Restart and Update"? Does waiting longer help?

**Comment by ashrayjain** [comment] 2015-05-29 08:51
I waited for about 15 mins. Also, if it is any help, I waited for the "Downloading update..." in the Atom menu to show "Restart and Install Update" before clicking.

**Comment by izuzak** [comment] 2015-05-29 08:57
Are you able to reproduce that problem? I just downloaded Atom 0.201.0 on OSX 10.10.3, started it, waited for the "Downloading update..." in the menu to show "Restart and Install Update", then clicked that and Atom restarted just fine.

**Comment by ashrayjain** [comment] 2015-05-29 09:02
Yup, I have been trying to update it repeatedly for almost half a day now. It fails every time. I have been using Atom for quite a while and it used to update just fine before today. Also, I did not install any new packages or themes before this problem started.

**Comment by izuzak** [comment] 2015-05-29 09:06
Thanks for the extra information, @ashrayjain. I'd recommend downloading the latest release manually, then (https://github.com/atom/atom/releases). 

@paulcbetts @kevinsawicki Do you have any :thought_balloon:/:bulb: about what might be causing problems here?

**Comment by ashrayjain** [comment] 2015-05-29 09:23
Sure, glad to help! Some additional information, I manually downloaded 0.200 and 0.202 and tried to update them to the latest version. Both of them fail in the exact same way. Also tried updating after disabling all custom packages. Still no luck.

**Comment by kevinsawicki** [comment] 2015-07-29 17:14
> Do you have any :thought_balloon:/:bulb: about what might be causing problems here?

I don't, I've not seen issues before with restarting on Mac.

@ashrayjain are you still experiencing this when trying to restart after upgrades on Atom 1.0+ versions?

**Comment by braver** [comment] 2015-07-29 17:39
FWIW I'm experiencing exactly this trying to go from 1.0.2 to .3 (OS X 10.10.4):
> Clicking "Restart and Update" from the release notes page or the Atom menu causes Atom to close and fail to restart. Moreover, upon restarting manually, Atom is not updated.

I freshly installed Atom, wiped all config and other leftovers I could find, before install 1.0.2.

**Comment by mnquintana** [comment] 2015-08-05 15:17
This is a duplicate of https://github.com/atom/atom/issues/5692 – let's continue the discussion there.

**Closed by mnquintana** 2015-08-05 15:17 UTC
Labels: mac, more-information-needed
