### ISSUE TITLE
Atom 1.26 breaks PHP incorectly (unlike Atom 1.24)

### ISSUE THREAD

**Issue by angree** [atom/atom#17243] opened 2018-04-29 07:48 UTC
Not much to write, besides the fact that atom 1.26 is not useful with any php I made. 
1.24:
![image](https://user-images.githubusercontent.com/25037912/39404361-06cb328e-4b92-11e8-875e-4a27be2ebb8b.png)
1.26.1:
![image](https://user-images.githubusercontent.com/25037912/39404363-1499e27a-4b92-11e8-99ac-eee1d6d12951.png)

#MakeAtomGreatAgain

**Comment by Ingramz** [comment] 2018-04-29 12:02
Duplicate of https://github.com/atom/language-php/issues/321

**Closed** 2018-04-30 07:29 UTC
