### ISSUE TITLE
"New update" has wrong version shown if you let the update download first

### ISSUE THREAD

**Issue by AgentME** [atom/atom#12614] opened 2016-09-07 00:27 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When at Atom update is available, I usually don't notice the blue squirrel button immediately. By the time I do click it, if I wait long enough (to let it download?), then Atom always shows me that the update is to the current version number that I'm already at.

### Steps to Reproduce

1. Start up Atom when an update is available.
2. Don't click the blue squirrel icon immediately. Leave Atom running for a while (to give it time to finish downloading the update first maybe? If that's the case, then I assume "Automatically download updates" must be on.)
3. Click blue squirrel icon.

**Expected behavior:**

The current version and a link to the current version's release notes should be shown at the top, and then the "New update" section should show the version number of the new update

**Actual behavior:**

The current version and a link to the current version's release notes is shown at the top, and then the "New update" section shows my current version and a link to its release notes instead of the update's version.

If I restart Atom and then immediately click the blue squirrel button, the about page will say that it's downloading the new update and then always show the correct version number.

### Versions

Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.9.3

![screen shot 2016-08-02 at 2 51 02 pm](https://cloud.githubusercontent.com/assets/577345/18295526/faec4a84-7456-11e6-846c-d263cbb8a42e.png)
![screen shot 2016-09-06 at 5 22 14 pm](https://cloud.githubusercontent.com/assets/577345/18295527/faed4be6-7456-11e6-9d9e-ae1867938f5b.png)

**Comment by Ben3eeE** [comment] 2016-10-05 07:47
This is a duplicate of https://github.com/atom/atom/issues/12311. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-05 07:47 UTC
