### ISSUE TITLE
Atom 1.23.2 Crashing

### ISSUE THREAD

**Issue by Hugloss** [atom/atom#16496] opened 2018-01-05 18:10 UTC
See attched file.
It 's 'Atom file-watcher Package' who made the computer to crash. 

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
I run a .py script who changes 1000 .txt documents.

### Steps to Reproduce

1. [First Step]
Open terminal in Atom.io
2. [Second Step]
Run script who changes 1000 documents
3. [and so on...]
The computer crash before the script is done

**Expected behavior:** [What you expect to happen]
Run the script with no computer crash

**Actual behavior:** [What actually happens]

Computer crash hard.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%. Computer crash every time I run the script. 

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Windows 10 Pro, 64-bit
Version: 1703
OS Build: 15063.786

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

[operation_log.txt](https://github.com/atom/atom/files/1607479/operation_log.txt)

### Steps to fix the problem
Uninstall Atom file-watcher Package.
Then do the same steps agine.
No crash.

**Comment by rsese** [comment] 2018-01-05 23:29
Thanks for the report @Hugloss - the issue template information would be very helpful here, can you please fill in the details?  In particular, it would be good to know if you can reproduce the error or what you were doing at the time of the error.  Also, you don't mention what version of Atom you're running (`atom -v`) or what version of Windows.

**Comment by Hugloss** [comment] 2018-01-06 12:56
@rsese Update with more information.

**Comment by rsese** [comment] 2018-01-10 05:08
Thanks @Hugloss - were there any `.dmp` files in the crashes directory?

It looks like you didn't check off the `Prerequisites` section, can you confirm if you can reproduce in safe mode (`atom --safe`)?

Lastly, is the script you're using something you can share so we can try it out?

**Comment by rsese** [comment] 2018-04-07 00:30
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16496#issuecomment-356501196. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-04-07 00:30 UTC
Labels: more-information-needed
