### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of null

### ISSUE THREAD

**Issue by postoroniy** [atom/atom#11282] opened 2016-03-26 00:34 UTC
1. atom+ hydrogen and julia 0.4.2 preinstalled
2. running first time and observing that decorator on right side line is shown
3. re running exactly same lines of julia and getting this error

**Atom Version**: 1.8.0-dev-1548cef
**System**: Linux Mint
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of null

```
At /usr/local/share/atom/resources/app.asar/src/block-decorations-component.js:50

TypeError: Cannot read property 'remove' of null
    at BlockDecorationsComponent.module.exports.BlockDecorationsComponent.updateSync (/usr/local/share/atom/resources/app.asar/src/block-decorations-component.js:50:46)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/usr/local/share/atom/resources/app.asar/src/text-editor-component.js:246:15)
    at /usr/local/share/atom/resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/local/share/atom/resources/app.asar/src/view-registry.js:221:9)
    at /usr/local/share/atom/resources/app.asar/src/view-registry.js:3:61
```
### Commands

```
     -1:43.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:43.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:40.2.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:39.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:33.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:13.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.2.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:06.9.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:06.5.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  5x -0:05.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:save (atom-text-editor.editor.is-focused)
 23x -0:02.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.5.0 hydrogen:run-and-move-down (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "ink",
      "julia-client",
      "language-tcl"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {},
    "showIndentGuide": true,
    "tabLength": 4
  }
}
```
### Installed Packages

``` coffee
# User
Hydrogen, v0.8.0
autocomplete-julia, v0.1.0
hex, v0.6.2
highlight-selected, v0.11.2
language-diff, v0.4.0
language-julia, v0.6.0
language-rust, v0.4.6
language-swift, v0.4.0
language-tcltk, v0.1.0
language-verilog, v0.4.0
language-vhdl, v0.7.2
linter-clang, v3.4.4
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
scala-format, v0.1.8

# Dev
No dev packages
```

**Comment by postoroniy** [comment] 2016-03-26 01:42
on Atom branch c5ed25a1315c4b66593415077ef84248ecf8a2a4 no error, all looks good

**Comment by postoroniy** [comment] 2016-04-01 09:37
can't see issue on 9b4e45133379ea74e9330aa097c71dbdd402e26c commit

**Comment by postoroniy** [comment] 2016-04-05 08:05
again the same on master branch.. I had to roll back again into c5ed25a1315c4b66593415077ef84248ecf8a2a4 where all are good

**Comment by Aerlinger** [comment] 2016-05-02 02:12
Having this issue as well. Issue happens when plotting with Hydrogen. Any solution other than a rollback?

**Comment by postoroniy** [comment] 2016-05-02 02:24
Nope!
I am sitting on 1.7.3.  and so far so good
or 1.8 dev branch as I already mentioned is c5ed25a

**Comment by lee-dohm** [comment] 2016-05-02 05:05
Has this been reported to the maintainers of either the hydrogen or julia packages?

**Comment by postoroniy** [comment] 2016-05-02 07:19
just referenced to nitrogen repo

**Comment by n-riesco** [comment] 2016-07-23 17:22
@lee-dohm For the record, Hydrogen fixed this issue in https://github.com/nteract/hydrogen/commit/7fe7c3ad27e074e5bbe5c6e049cd38f65a4abf48 . The issue was caused by Hydrogen calling `.remove()` on the element used to create the decorator.

**Comment by mda6** [comment] 2017-01-10 02:37
@n-riesco @lee-dohm I just freshly installed hydrogen and got this issue, so it's seems is not fixed?

**Comment by n-riesco** [comment] 2017-01-10 08:33
@mda6 I can't reproduce the issue using the Julia kernel. Please, could you post the steps to reproduce your issue?

[Hydrogen issue #577](https://github.com/nteract/hydrogen/issues/577)

**Comment by Ben3eeE** [comment] 2017-08-24 11:46
It looks like this issue has already been solved and that there was a problem in a community package so I am going to close this.

**Closed by Ben3eeE** 2017-08-24 11:46 UTC
Labels: uncaught-exception
