### ISSUE TITLE
Startup window size saved incorrectly when maximzed

### ISSUE THREAD

**Issue by prasannavl** [atom/atom#6912] opened 2015-05-22 22:44 UTC
When maximized and then exited, it saves the sizes and not the maximization. And it ends up opening un-maximized, but with the maximized sizes. 

**Correct behaviour should be:** If maximized, use the value of last resize before maximization, but also flag the maximization. 

On Windows, resizing due to Aero-Snap behaviors should be not be saved, and ignored. Similar behavior to maximization has to be used for correctness.

**Comment by 50Wliu** [comment] 2016-04-29 23:46
@prasannavl Can you still reproduce this on Atom 1.7.3?

**Comment by prasannavl** [comment] 2016-04-29 23:59
Yes. This behavior doesn't seem to have changed.

**Comment by 50Wliu** [comment] 2016-04-30 00:02
Hmm, this works for me on Windows 10 - it was supposed to be fixed a long time ago.

**Comment by prasannavl** [comment] 2016-04-30 00:18
Oh oh, my bad. I ended having the process creation scripted to restore sizes. 

Back to the issue, the "maximization" bit is fixed. However not how it saves, or the expected correct behavior.

**Comment by 50Wliu** [comment] 2016-04-30 00:25
> However not how it saves, or the expected correct behavior.

Can you elaborate on this please?

**Comment by prasannavl** [comment] 2016-04-30 00:27
What should be saved:
'If maximized, use the value of **last resize before** maximization, but also flag the maximization.'

The maximized sizes are useless. Can be thrown away. Just the maximization bit is sufficient.

**Comment by 50Wliu** [comment] 2016-04-30 00:42
Yup, totally agree!  Now I think I see why you're saying this and the other issue are duplicates :).  As that has a bit more conversation going, I'm going to close this one in favor of #10720.  Can you please comment about the aero-snap feature over there?  Thanks!

**Closed by 50Wliu** 2016-04-30 00:42 UTC
Labels: more-information-needed, needs-reproduction, windows
