### ISSUE TITLE
Support more languages with new node-spellchecker

### ISSUE THREAD

**Issue by juh2** [atom/atom#10705] opened 2016-02-05 18:04 UTC
For years users who write non-english texts are desperatey waiting for spell checking in more languages than only English.

[From the bugtracker of node-spellchecker](https://github.com/atom/node-spellchecker/issues/4) I guess that everything is ready to get into Atom.

So please make non-english speakers happy.

**Comment by lee-dohm** [comment] 2016-02-05 23:12
This is a duplicate of https://github.com/atom/spell-check/issues/11. Please subscribe there for updates.

**Closed by lee-dohm** 2016-02-05 23:12 UTC
