### ISSUE TITLE
dependencies: atom still depends on python2

### ISSUE THREAD

**Issue by tiagogaspar8** [atom/atom#20171] opened 2019-11-22 14:40 UTC
Good afternoon,

I see that atom depends on python 2 and it won't be installed without it, but python 2 end of life is on January 1st. Shouldn't atom move to python 3?

Thanks!

**Comment by Arcanemagus** [comment] 2019-11-22 17:02
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/apm/pull/875. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-11-22 17:02 UTC

**Comment by tiagogaspar8** [comment] 2019-11-22 17:08
Yes I understand that and I'm sorry but I haven't found that thread, if I had I wouldn't have opened this issue.
I hope this gets merged soon and atom supports python 3 soon.

**Comment by Arcanemagus** [comment] 2019-11-22 17:10
Just in case it wasn't clear: Atom itself has nothing to do with Python 2 or 3 as far as dependencies, this is an ecosystem wide issue across most of JavaScript due to the widespread dependency on `node-gyp` which only just recently updated with support.

**Comment by tiagogaspar8** [comment] 2019-11-22 17:14
Ahhh I see, and now you guys are merging the new package into atom right?
