### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Dropbox/EECS 498 (Distributed Systems)/Project 3 (...

### ISSUE THREAD

**Issue by bradymathieson** [atom/atom#16094] opened 2017-11-03 19:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Adding a pane item with URI '/Users/bradymathieson/Dropbox/EECS 498 (Distributed Systems)/Project 3 (Paxos)/src/paxos/paxos_impl.go' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:514

Error: Adding a pane item with URI '/Users/bradymathieson/Dropbox/EECS 498 (Distributed Systems)/Project 3 (Paxos)/src/paxos/paxos_impl.go' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:514:21)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:489:20)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:715:25)
```

### Commands

```
  7x -3:09.7.0 editor:toggle-line-comments (input.hidden-input)
     -2:24 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
file-icons 2.1.13 
go-debug 1.5.2 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-markdown 0.25.1 
linter 2.2.0 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
platformio-ide-terminal 2.7.0 
Remote-FTP 1.2.6 
todo-show 2.1.0 
```

**Comment by rsese** [comment] 2017-11-05 04:03
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-05 04:03 UTC
