### ISSUE TITLE
Editor folding broken by indentation.

### ISSUE THREAD

**Issue by pushqrdx** [atom/atom#16029] opened 2017-10-30 16:39 UTC
So basically if you have an html element that contains another elements indented before the parent. when you try and fold it it just breaks. This behavior isn't normal for example using Webstorm or Visual Studio, the collapse should fold the whole element.

```
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <div>
    <div>
<div></div>
<div></div>
<div></div>
<div></div>
<div></div>
    </div>
  </div>
</body>
</html> 
```

Simply paste this code into a new html file then try and collaps the parent div element.

**Comment by rsese** [comment] 2017-10-30 18:07
Thanks for taking the time to contribute!

This looks like a duplicate of https://github.com/atom/atom/issues/11838 so you can subscribe there for updates if you'd like.

Additionally, for future issues it would be super helpful for us if you can fill out the issue template.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-30 18:07 UTC
