### ISSUE TITLE
Wierd artifacting on side of screen

### ISSUE THREAD

**Issue by LouieK22** [atom/atom#15178] opened 2017-08-06 16:26 UTC
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There are weird black artifacts on the left side of the screen. Not sure how else to describe them, or if they're even technically atifacts.

### Steps to Reproduce

1. Launch latest beta
2. Profit?

**Expected behavior:** 
Not this: http://i.imgur.com/AuxgNA1.png

**Actual behavior:** 
This: http://i.imgur.com/AuxgNA1.png
This in safe mode: http://i.imgur.com/yDrtgNq.png

**Reproduces how often:** 100%

### Versions

atom --version
Atom    : 1.19.0-beta7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 3.6.0
git 2.13.3.windows.1
visual studio 2015

### Additional Information

You can hide this issue by hiding the arrow button on the left side of the screen by setting "display: none;" in the Chrome Developer Tools or through styles.less

**Comment by rsese** [comment] 2017-08-07 17:30
Thanks for the report!  Just to confirm, this behavior started right after updating to 1.19.0-beta7?

Maybe similar to https://github.com/atom/atom/issues/14915?

**Comment by LouieK22** [comment] 2017-08-07 17:42
Behavior started at 1.19.0-beta7 yes. I also experience #14915 100% of the time, however the issue for that goes away when I toggle the bottom dock.

**Comment by rsese** [comment] 2017-08-07 21:46
Thanks for confirming - I think a pull request to fix https://github.com/atom/atom/issues/14915 will be reviewed soon but can you also check if you still see the same artifact you're reporting in this issue after adding the CSS referenced here to you styles.less?

https://github.com/atom/atom/issues/14915#issuecomment-313377782

**Comment by LouieK22** [comment] 2017-08-08 15:32
The CSS provided does fix my issue.

**Comment by rsese** [comment] 2017-08-08 17:48
Great thanks for trying that - I think we can mark this as a duplicate of https://github.com/atom/atom/issues/14915 for now and if you still see this problem after that issue is fixed we can re-open.

**Closed by rsese** 2017-08-08 17:48 UTC
Labels: more-information-needed
