### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1193Error: Cannot ca...

### ISSUE THREAD

**Issue by paulobarcelos** [atom/atom#19997] opened 2019-10-05 18:09 UTC
[Enter steps to reproduce:]

1. Happened suddenly. I just followed the recommendations of the error pop up to create the issue here.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1193
Error: Cannot call function 'getPosition' on missing remote object 1193
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 1193
Error: Cannot call function 'getPosition' on missing remote object 1193
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705396)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705811)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -3:24.7.0 core:cut (input.hidden-input)
     -3:22.4.0 core:paste (input.hidden-input)
     -3:21.6.0 core:save (input.hidden-input)
     -3:19 editor:newline (input.hidden-input)
     -3:18.1.0 core:undo (input.hidden-input)
     -3:13.5.0 core:confirm (div.github-StagingView.unstaged-changes-focused)
  3x -3:07.5.0 core:backspace (input.hidden-input)
     -3:06.4.0 github:commit (input.hidden-input)
     -3:05.6.0 intentions:highlight (input.hidden-input)
     -0:36.4.0 core:move-right (input.hidden-input)
     -0:36.1.0 core:backspace (input.hidden-input)
  2x -0:35.7.0 core:move-right (input.hidden-input)
     -0:35.2.0 core:backspace (input.hidden-input)
     -0:34.6.0 core:save (input.hidden-input)
     -0:19.2.0 core:copy (input.hidden-input)
     -0:19.1.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-typescript 13.3.0 
autocomplete-modules 2.2.6 
busy-signal 2.0.0 
console-panel 0.3.1 
duplicate-removal 0.1.3 
intentions 1.1.5 
language-babel 2.85.0 
language-gettext 0.6.1 
language-nsis 6.19.1 
linter 2.3.0 
linter-eslint 8.5.2 
linter-makensis 0.10.1 
linter-ui-default 1.7.1 
multi-cursor 2.1.5 
shebang-set-grammar 0.8.0 
sort-all-the-things 1.1.0 
tablr 1.8.3 
```

**Comment by rsese** [comment] 2019-10-07 20:08
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-10-07 20:08 UTC
