### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/****/Library/Application Sup...

### ISSUE THREAD

**Issue by urthilak** [atom/atom#9570] opened 2015-11-13 14:32 UTC
[Enter steps to reproduce below:]

1. Select a text file, right click
2. select Atom from the option "Open With"

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/*****/Library/Application Support/com.github.atom.ShipIt/update.J8yFTzx'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/******/Library/Application Support/com.github.atom.ShipIt/update.J8yFTzx'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/*****/Library/Application Support/com.github.atom.ShipIt/update.J8yFTzx/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (module.js:388:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by nathansobo** [comment] 2015-11-13 17:24
Is `******` really your home directory name or are you redacting here?

**Comment by 50Wliu** [comment] 2015-11-13 21:27
Closing as a duplicate of #7399, please subscribe there for updates.
However, please still answer @nathansobo's question.

**Closed by 50Wliu** 2015-11-13 21:27 UTC
Labels: uncaught-exception
