### ISSUE TITLE
Cannot install Atom 0.188 on Windows 7 (PathTooLongException)

### ISSUE THREAD

**Issue by weblogixx** [atom/atom#6180] opened 2015-03-31 06:11 UTC
Hi,

I seem to be unable to install Atom 0.188 on Windows 7. The installer just exits with an error message, which links to the following log:

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\christian.schilling\AppData\Local\atom\packages\RELEASES" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   bei Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\christian.schilling\AppData\Local\atom\app-0.169.0
ApplyReleasesImpl: runPostInstallAndCleanup: starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\christian.schilling\AppData\Local\atom\app-0.169.0\atom.exe]
ApplyReleasesImpl: cleanDeadVersions: for version 0.169.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.169.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian.schilling\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\christian.schilling\AppData\Local\atom\app-0.181.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian.schilling\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\christian.schilling\AppData\Local\atom\app-0.181.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\christian.schilling\AppData\Local\atom\packages\RELEASES" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   bei Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\christian.schilling\AppData\Local\atom\app-0.181.0
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\christian.schilling\AppData\Local\atom\app-0.181.0\atom.exe]
ApplyReleasesImpl: Starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: cleanDeadVersions: for version 0.181.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.181.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\christian.schilling\AppData\Local\atom\packages\RELEASES" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   bei Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\christian.schilling\AppData\Local\atom\app-0.187.0
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\christian.schilling\AppData\Local\atom\app-0.187.0\atom.exe]
ApplyReleasesImpl: Starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: cleanDeadVersions: for version 0.187.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.187.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
IEnableLogger: Failed to copy Update.exe to C:\Users\christian.schilling\AppData\Local\atom\Update.exe: System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Users\christian.schilling\AppData\Local\atom\Update.exe" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   bei Squirrel.Update.Program.<>c__DisplayClass2f.<Install>b__28()
   bei Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
IEnableLogger: Failed to copy Update.exe to C:\Users\christian.schilling\AppData\Local\atom\Update.exe: System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Users\christian.schilling\AppData\Local\atom\Update.exe" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   bei Squirrel.Update.Program.<>c__DisplayClass2f.<Install>b__28()
   bei Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian.schilling\AppData\Local\SquirrelTemp
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\christian.schilling\AppData\Local\atom\app-0.188.0
ApplyReleasesImpl: Writing files to app directory: C:\Users\christian.schilling\AppData\Local\atom\app-0.188.0
IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
   bei System.IO.PathHelper.GetFullPathName()
   bei System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   bei System.IO.Path.GetFullPathInternal(String path)
   bei System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   bei System.IO.FileInfo..ctor(String fileName)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8c.<installPackageToAppDir>b__89(IPackageFile x)
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8c.<installPackageToAppDir>b__88()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__8e.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian.schilling\AppData\Local\SquirrelTemp
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\christian.schilling\AppData\Local\atom\app-0.188.0
ApplyReleasesImpl: Writing files to app directory: C:\Users\christian.schilling\AppData\Local\atom\app-0.188.0
IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
   bei System.IO.PathHelper.GetFullPathName()
   bei System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   bei System.IO.Path.GetFullPathInternal(String path)
   bei System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   bei System.IO.FileInfo..ctor(String fileName)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8c.<installPackageToAppDir>b__89(IPackageFile x)
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8c.<installPackageToAppDir>b__88()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__8e.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian.schilling\AppData\Local\SquirrelTemp
ApplyReleasesImpl: Writing files to app directory: C:\Users\christian.schilling\AppData\Local\atom\app-0.188.0
IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
   bei System.IO.PathHelper.GetFullPathName()
   bei System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   bei System.IO.Path.GetFullPathInternal(String path)
   bei System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   bei System.IO.FileInfo..ctor(String fileName)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8c.<installPackageToAppDir>b__89(IPackageFile x)
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8c.<installPackageToAppDir>b__88()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__8e.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\christian.schilling\AppData\Local\atom\packages\RELEASES" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   bei Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian.schilling\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\christian.schilling\AppData\Local\atom\app-0.188.0
ApplyReleasesImpl: Writing files to app directory: C:\Users\christian.schilling\AppData\Local\atom\app-0.188.0
IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
   bei System.IO.PathHelper.GetFullPathName()
   bei System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   bei System.IO.Path.GetFullPathInternal(String path)
   bei System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   bei System.IO.FileInfo..ctor(String fileName)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8c.<installPackageToAppDir>b__89(IPackageFile x)
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8c.<installPackageToAppDir>b__88()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__8e.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<LogIfThrows>d__4f`1.MoveNext()
```

This error happens when I run atom as regular OR administrative user.
As I cannot install any packages and now I am also unable to install updates I seem to be a bit lost :(. I really want to use your editor, but you just dont let me :).

**Comment by izuzak** [comment] 2015-03-31 09:31
Looks like a duplicate of https://github.com/atom/atom/issues/5109.

**Closed by izuzak** 2015-03-31 09:31 UTC
