### ISSUE TITLE
No syntax highlighting for large SQL files

### ISSUE THREAD

**Issue by whizkydee** [atom/atom#12403] opened 2016-08-12 07:33 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

OS: Windows 10
Atom: v1.9.8

@mojombo @Caged @schacon @defunkt @benburkert 

### Description
No syntax highlighting for large SQL files

Hi guys,
Recently, I've been working quite more with databases and SQL. But I noticed in `v1.9.8` and some older versions that when I open an already existing large `*.sql` file, Atom doesn't highlight the code. I tried it in safe mode but still got the same issue even when I switched syntax themes.

Atom only highlights large SQL code when I create a new untitled file and set the type to SQL and paste or type SQL code into it.

**Expected Behavior:** Atom highlights all the code in my SQL file.

**Actual Behavior:** No highlights for the SQL code at all in a file except when in an untitled file.

Some help would be appreciated. Thanks 😄 ✔️

**Comment by 50Wliu** [comment] 2016-08-12 14:58
I'm going to assume that you're running into #1667 based on your description of "lengthy" files - if that's not the case, please clarify and I'll reopen this issue.

**Comment by whizkydee** [comment] 2016-08-20 08:55
@50Wliu This is more specific to `*.sql` files only and is not a duplicate of #1667 .

Also, when I create and empty sql file (not untitled) and paste the sql code, it gets highlighted. But when I re-open it i doesn't get highlighted even in `v1.9.9`. This has been tested on three Windows 10 PCs even in safe mode and on different themes.

_The image below is a GIF of an untitled file with language set to SQL and a named `stupiddb.sql` file._
![atom](https://cloud.githubusercontent.com/assets/8625066/17830170/fd2b4282-66c3-11e6-9394-cc4e54511bcc.gif)

Thanks. Please re-open.

**Comment by lee-dohm** [comment] 2016-08-23 03:30
I suspect that this is a duplicate of https://github.com/atom/atom/issues/11232 because the conditional behavior of it highlighting sometimes but not other times sounds identical to that Issue. Please add the information you have and any files that you can share that reproduce the problem to that Issue.

**Closed by lee-dohm** 2016-08-23 03:30 UTC

**Comment by whizkydee** [comment] 2016-08-23 06:57
Thanks @lee-dohm,
It's just as #11232. I couldn't have explored all the issues on the repo.
