### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.41.0\res...

### ISSUE THREAD

**Issue by annasrizal** [atom/atom#20065] opened 2019-10-25 10:37 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\FAKE\AppData\Local\atom\app-1.41.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: The specified module could not be found.
\\?\C:\Users\FAKE\AppData\Local\atom\app-1.41.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:1:727373)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:2746273)
    at get_manager (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:2746375)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:2746501)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1087039)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1249633)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1247618)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:284598)
```

### Commands

```
     -0:25 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
file-icons 2.1.35 
platformio-ide-terminal 2.9.4 
```

**Comment by rsese** [comment] 2019-10-26 22:03
Thanks for contributing!

We noticed that this looks like a duplicate of #14461 so you can subscribe there for updates if you'd like.

Can you try quitting Atom and reinstalling to see if that helps?  if you have an anti-virus program running, try temporarily disabling it before reinstalling.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-10-26 22:03 UTC
