### ISSUE TITLE
Auto identation issue caused by sql query in php script

### ISSUE THREAD

**Issue by Asdra** [atom/atom#13854] opened 2017-02-20 15:21 UTC
Hi,
I noticed a little bug with auto identation.

Here is two codes after auto identation :
![bug_atom_ident](https://cloud.githubusercontent.com/assets/7705276/23130632/7c7ffe8e-f787-11e6-8cb7-346144b94124.png)

As you can see, the closing ")' of the sql subquery seems to disturb the auto identation.

It only works if the closing ")" is on a new line, and if the string is not cutted, for exemple, this code doesn't work 

`public function withSql() {`
`    $query = "SELECT * FROm test WHERE test IN (`
`    test";`
`    $query .= ")";`
`}`

**Comment by rsese** [comment] 2017-03-07 03:49
I can reproduce the behavior you described if I paste in:

```
public function withSql() {
    $query = "SELECT * FROm test WHERE test IN (
    test";
    $query .= ")";
```

And then enter `}` after a newline.

I noticed that auto-indent issues have been reported in the language specific repositories in some cases e.g.:

https://github.com/atom/language-php/issues?q=is%3Aopen+is%3Aissue+label%3Aauto-indent

So I'm not positive if the language specific repos are the best place to report issues like this since I also came across issues like https://github.com/atom/atom/issues/6655.

/cc @50Wliu - do you think auto-indent issues should go in the language specific repos or just here in atom/atom?

**Comment by 50Wliu** [comment] 2017-03-07 04:24
I do like them to be reported to each language repo.  #6655 is more of a "auto-indentation is woefully inadequate" issue that hasn't been addressed yet.  This looks like one of those, since it would require the closing curly bracket to be twice-unindented, something the current system can't handle.  For those, I just add the blocked label.

@Asdra please reopen this on the [atom/language-php](https://github.com/atom/language-php) repo.  Thanks!

**Closed by 50Wliu** 2017-03-07 04:24 UTC
Labels: auto-indent

**Comment by rsese** [comment] 2017-03-07 07:29
Thanks for clarifying @50Wliu, super helpful :bow:
