### ISSUE TITLE
Python syntax highlighting parsing breaks for some comments

### ISSUE THREAD

**Issue by derekmaciel** [atom/atom#12318] opened 2016-08-03 23:47 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Python syntax highlighting fails to "close" a Python triple-quote `'''` comment, breaking the rest of the file's syntax highlighting. This occurs on all of the highlighting styles installed by default on Windows and occurs when atom is started in safe mode or when started with a cleared window state.

![capture](https://cloud.githubusercontent.com/assets/602444/17385803/14df4aae-59b3-11e6-84a8-3f62e29f2bf2.PNG)

### Steps to Reproduce

1. [Download file](https://github.com/saltstack/salt/blob/2016.3/salt/modules/file.py) and open in Atom
2. Go to line 1485

**Expected behavior:** Line 1485 should be highlighted as a line of code

**Actual behavior:** Line 1485 and onward are highlighted as a comment

### Versions

OS: Windows 10

```
Atom    : 1.9.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.11
git
visual studio
```

**Comment by 50Wliu** [comment] 2016-08-04 00:16
Closing as a duplicate of one or more of the following: atom/language-python#39, atom/language-python#45, atom/language-python#55.  If none of those describe the problem you have, please create a new issue on [atom/language-python](https://github.com/atom/language-python).  Thanks!

**Closed by 50Wliu** 2016-08-04 00:16 UTC
