### ISSUE TITLE
Atom Icon not showing up when selected as Default App

### ISSUE THREAD

**Issue by andigu** [atom/atom#12974] opened 2016-10-13 22:59 UTC
1. I selected Atom as the default app to open a specific file type (more specifically, a PY file)
2. The Atom logo doesn't show up next to the file as expected in file explorer. See image below:
![image](https://cloud.githubusercontent.com/assets/13321300/19370030/2007e08e-9177-11e6-89a4-5f8904b9eca0.png)
As you can see, the file icon isn't showing up next to test.py even though Atom is selected as the default app (like IntelliJ is doing)

**Comment by michaelmanoCOM** [comment] 2016-10-13 23:56
Can confirm. Ive even hacked the exe to reset the icon that didnt work so i went back to the original.

I then changed the shortcut to use the correct icon.
That didnt work.

I even made a batch file that launches atom compiled to exe with icon. No luck.

Starting to get over it. Might go back to previous versions

**Comment by AgamlaRage** [comment] 2016-10-18 16:28
I have the exactly same problem.
I also create a Virtual Machine to test this, **I can confirm that the last Atom version is showing the file icon correctly on a windows 10 version 10586.494**.

I also tried a lot of manipulation in windows to rebuild icon cache, or reset the default register for the file type that I wanted to associate with Atom ...etc
After 2 hours of trying every tutorial I found, icons came back... then just for the night, after restarting my computer, they were gone again... :(

I hope Atom or Windows community will take care of that, it is really annoying

**Comment by NoorKhan** [comment] 2016-10-18 19:07
I'm seeing this as well, on Windows 8.1.

**Comment by michaelmano** [comment] 2016-10-18 19:54
Yeah its fine from beta on so m guess is all done.

**Comment by jghaanstra** [comment] 2016-10-19 07:29
I can confirm the file association icon is back in the Atom beta channel. It's a different and less pretty icon but at least it's recognizable again.

**Comment by michaelmano** [comment] 2016-10-19 07:49
Lies. Its awesome. Once you get used to it. Its less obtrusive for a file
type but the atom exe icon is still the same.

**Comment by 50Wliu** [comment] 2016-10-19 14:00
Looks like this has been fixed in Atom 1.12-beta, so closing.

@damieng Is this something that should be backported to 1.11?

**Closed by 50Wliu** 2016-10-19 14:00 UTC
Labels: windows

**Comment by damieng** [comment] 2016-10-19 17:10
Yeah we added a new icon in 1.12 that is more of an 'Atom document' than reproducing the app icon everywhere.

Not sure if it's worth backporting will keep an eye on this thread.
