### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/rkmistry 1/Downloads/Atom.app'

### ISSUE THREAD

**Issue by avmist** [atom/atom#10919] opened 2016-02-21 20:09 UTC
[Enter steps to reproduce below:]

1. Click atom > Preferences
2. Error

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/rkmistry 1/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/rkmistry 1/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/rkmistry 1/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -0:49.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:49.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:42.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:42.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:42.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:41.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:40.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:40.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:40.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:40.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:37.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:37 editor:newline (atom-text-editor.editor.is-focused)
     -0:36.3.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:36.3.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:35.6.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:35.6.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2016-02-21 20:46
@joshaber It looks like this could be one of the `ENOENT` things I think you were looking at? Also, it could be because there is a space in the path to the app?

**Comment by avmist** [comment] 2016-02-21 21:24
I actually found out the issue; i moved the path from "Downloads" to "Applications"...once I moved it back to "Downloads," I stopped receiving the error.  Is there a way to change the file path in Atom?


________________________________

**Comment by joshaber** [comment] 2016-02-22 14:50
Yup, this is a duplicate of https://github.com/atom/atom/issues/10774.

@avmist Sure, just be sure to quit the app before you move it and then re-open it from the new location.

**Closed by joshaber** 2016-02-22 14:50 UTC
Labels: uncaught-exception
