### ISSUE TITLE
Context menu doesn't open at mouse cursor position

### ISSUE THREAD

**Issue by olmokramer** [atom/atom#8921] opened 2015-09-24 10:32 UTC
See this image:

![context-menu](https://cloud.githubusercontent.com/assets/3612514/10071091/4e0f6ca8-62b7-11e5-8b8f-7e3483e827b0.gif)

When I right click to open the context menu, there's a few pixels in between the mouse cursor and the top-left corner of the context menu. It seems to get worse on the right side of the screen. I would expect the context menu's top-left corner to coincide with the mouse position. I could replicate this in safe mode, but not in google chrome v45.0.2454.99.

System details:
Atom 1.2.0-dev-0145ae3
Debian 9 with Openbox window manager

**Comment by kevingimbel** [comment] 2015-09-25 13:44
Came here to open the same issue, I first noticed this after upgrading from Atom 1.0.0 to 1.0.15 (a few days ago).

##### Additional details
**OS**: Ubuntu 14.04 (64 Bit)
**Atom**: 1.0.15
**Theme (UI)**: Seti (but also happens with default themes)

![atom_context_menu_issue](https://cloud.githubusercontent.com/assets/2161714/10101882/ac2e9a54-639b-11e5-8197-764175ad916c.gif)

**Comment by Dumr** [comment] 2015-10-08 16:56
same problem here

**Comment by olmokramer** [comment] 2015-10-08 20:45
Yes, I'm using two monitors, one on the right of the monitor Atom is on. My monitors are aligned at the top, though. The issue is much worse with Atom on the right monitor.

**Comment by Dumr** [comment] 2015-10-08 20:49
okay :) I was close, then it has to do something with resolution of monitors. Maybe there is function in code which align context menu according to desktop size.

**Comment by olmokramer** [comment] 2015-10-08 21:01
The weird thing is, though, that I have the same problem in the vertical direction. The lower I click in the Atom window, the more the vertical offset to the menu is. This can even cause the menu to go completely off-screen. And I definitely don't have a monitor "below" my monitor with Atom.

**Comment by Dumr** [comment] 2015-10-08 21:09
yeah I know :) I have same exact problem. Ill remove atom and delete all folders and stuff and try to install it without dual monitors. I had no problem with old version.

**Comment by yochannah** [comment] 2015-10-16 14:40
I'm experiencing this too. Ubuntu Mate, dual monitors.

**Comment by olmokramer** [comment] 2015-10-16 17:06
@Dumr Well... [context-menu.coffee:8](https://github.com/atom/atom/tree/master/src/browser/context-menu.coffee#L8) is just passing an [electron `BrowserWindow`](https://github.com/atom/electron/blob/master/atom/browser/api/lib/browser-window.coffee) (I think it's that one, but please correct me if I'm wrong) instance to [electron's `Menu`](https://github.com/atom/electron/blob/master/atom/browser/api/lib/menu.coffee) class' [`popup`](https://github.com/atom/electron/blob/master/atom/browser/api/lib/menu.coffee#L81-L90) method, which should map to [Menu::Popup](https://github.com/atom/electron/blob/master/atom/browser/api/atom_api_menu.h#L54), but I don't know C++ and I don't really understand what's going on after that :fearful:...

**Comment by Dumr** [comment] 2015-10-21 16:35
okay with latest build from source from github it works for me now.

**Comment by olmokramer** [comment] 2015-10-21 16:48
Nope, still happening for me. Which branch did you build?

**Comment by Dumr** [comment] 2015-10-21 21:58
fdb1642 or in other words 'v1.1.0-beta1'

**Comment by olmokramer** [comment] 2015-10-21 23:52
It's still present on the master branch on my machine. I'll try 1.1.0-beta1

**Comment by lightradius** [comment] 2015-10-28 09:15
I have the exact same isse on Ubuntu 15.04, dual monitor setup.

**Comment by kevingimbel** [comment] 2015-10-28 16:08
Just upgraded to 1.0.19 and the offset is even worse than before.

**Comment by rnyberg** [comment] 2015-10-28 16:30
I reckon it's the same bug that exists in Chromium, and has now landed into Atom as well.  :P

**Comment by lightradius** [comment] 2015-10-28 16:42
So is this a problem with Atom or Ubuntu?

**Comment by rnyberg** [comment] 2015-10-28 17:04
Just saying they are related, maybe. No other software affected in my case.

**Comment by kevingimbel** [comment] 2015-10-29 12:56
@rnyberg adjusting the scaling does not fix it. 

@lightradius there's a similar bug in Chrome/Chromium. I'd say it is a Atom issue _on_ Ubuntu rather than a Ubuntu issue.

**Comment by rnyberg** [comment] 2015-10-29 13:12
@kevingimbel I'm running on Ubuntu 14.04 and setting scaling to 1 works for me. I reckon it's separate issue then.

**Comment by thedaniel** [comment] 2015-10-29 13:56
There have been a few reports in this thread that 1.1.0-beta1 has fixed the problem for some people. If you can, try out the beta, or wait until 1.1.0 stable is out before chiming in that you also have this problem. By all means please update this thread if you are seeing similar issues in 1.1.0 though.

**Comment by Kryten0807** [comment] 2015-11-03 16:11
I'm seeing this issue in 1.1.0.

OS: Ubuntu 14.04 (64 Bit)
Atom: 1.0.15

Monitor Configuration: two identical 24" monitors at 1920x1200 with scale for menu & title bars set to 0.875

On the left-hand monitor (where I do most of my editing), the context menu appears about 3" to the right and 1.5" below the mouse pointer.

If I move the editor to the right-hand monitor, I can't see the context menu at all.

Resetting the scaling to 1.0 does not fix the issue - now the menu appears about 2.5" to the right & either 1.5" above or below the pointer, depending on whether I'm near the bottom or top of the screen.

**Comment by kevingimbel** [comment] 2015-11-04 13:00
Quick Update: I've tried the 1.2.0-beta0 release and the issue is still present. 

**OS**: Ubutnu 14.04
**Atom**: 1.2.0-beta0

A possible workaround, for me, is setting the internal, smaller screen to display at 1,12x scale and the external to ~0.75x scale. Then the context menus appear in the correct position. However, this isn't a real fix or solution because the UI of everything becomes rather blurry/ugly when using this setup. 

I believe this issue is somewhat related to Chrome/Chromium since the I see a similar issue in those browsers.

**Comment by davidgross** [comment] 2015-11-04 19:34
+1 I have the same behavior

**OS**: Devuan Jessie
**Atom**: 1.0.15
I have the nvidia proprietary drivers, I don't know if that is related....

**Comment by HerrFolgreich** [comment] 2015-11-30 14:31
**OS**: Ubuntu 14.04 x64
**Atom**: 1.2.4
**Display**: two identic 24" 16:9 HD panels

I'm able to reproduce the issue on my system, but only if I set the menu scale of the **primary** monitor to something other than 1. Having atom on another monitor and this very monitor's scale on, say, 0.875,  the context menu is aligned correctly. On the other hand, if the primary monitor gets scaled, no matter where atom is open, the context menu pops up away from the cursor again.

**Comment by lightradius** [comment] 2015-12-18 11:29
Setting my second monitor's scale to 1.12 in Ubuntu's display settings solved the issue for me.
I have no idea why, but the context menu is now aligned with the mouse cursor.

**Comment by lee-dohm** [comment] 2015-12-28 17:47
Additional information here:

https://discuss.atom.io/t/right-click-menu-misaligned/22050

**Comment by bokiscout** [comment] 2016-01-04 03:29
I'm facing the same issue although I'm using only one monitor.

System:
GPU: nVidia GTX 560 (Assus)
Driver: 358.16
OS: Arch Linux
Kernel: 4.1.15.1 LTS
Atom: 1.3.2

**Comment by broedli** [comment] 2016-03-11 11:24
Having the same Issue. BUT when i do a rightclick in the first 1/5th of the window (about the default size of the tree-view) or up to the menu entrie "Find" (Menu Bar) it opens on the correct screen. Any clicks further to the right open up on the next monitor to the right.

System:
GPU: nvidia GTX970
Monitors: 3
Driver: 361.28
OS: Arch Linux
Kernel: 4.4.5-1
Atom 1.5.4

**Comment by olmokramer** [comment] 2016-04-15 15:13
I just upgraded to Atom v1.9.0-dev-c95412b and now the issue is gone!

**Comment by 50Wliu** [comment] 2016-04-15 15:19
:tada:
If anyone can still reproduce this on 1.9.0 please comment here!

**Closed by 50Wliu** 2016-04-15 15:19 UTC
Labels: bug, electron, linux
