### ISSUE TITLE
Cursor doesn't move to the correct position when creating comments using Cmd + /

### ISSUE THREAD

**Issue by pauljacobson** [atom/atom#17199] opened 2018-04-22 08:50 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I create a comment using `Cmd` + `/` in CSS, HTML, or Markdown docs (these are the formats I work with for the most part), the cursor isn't positioned _between_ the comment tags. For example:

![atom_comment_cursor_position](https://user-images.githubusercontent.com/2912202/39093086-39b7bbce-4622-11e8-9a46-82218bc25699.gif)

### Steps to Reproduce

1. Create a CSS document to test this out.
2. Positioned the cursor on a new line and hit `Cmd` + `/` to create the comment tags.
3. The cursor is always positioned _after_ the closing comment tag, regardless of whether I create comments in CSS, HTML, or Markdown files.

**Expected behavior:** [What you expect to happen]

When creating a comment using `Cmd` + `/`, the cursor should appear within the tags. Here is the previous example, but with additional demonstration in VS Code to illustrate expected behaviour:

![vscode_comment_cursor_position](https://user-images.githubusercontent.com/2912202/39093128-173c6b48-4623-11e8-8a2c-9d7ddb03cea8.gif)

**Actual behavior:** [What actually happens]

The cursor is always positioned _after_ the closing comment tag, regardless of whether I create comments in CSS, HTML, or Markdown files.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

I'm running macOS 10.13.4

### Additional Information

None

**Comment by rsese** [comment] 2018-04-23 17:12
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/4784 so you can subscribe there if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-23 17:12 UTC

**Comment by pauljacobson** [comment] 2018-06-08 17:08
Thanks for your feedback @rsese. The problem with this is that issue #4784 was closed because it was marked as stale in September 2017. Essentially, this issue doesn't appear to be on anyone's radar then, unless the lead times for dealing with issues is ±9 months?

**Comment by rsese** [comment] 2018-06-13 17:14
Sorry just saw your reply after the comment in https://github.com/atom/atom/issues/4784#issuecomment-396793011 - with the finite resources of the team and the work they have on their plate, you're right there are issues that just aren't on anyone's radar.  What the team is working on however we try to document in our [iteration plans](https://github.com/atom/atom/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aiteration-plan).

But for issues that aren't worked on, we do often get well-written community pull requests that the team is happy to review (though there's no guarantee they'll be accepted).

**Comment by pauljacobson** [comment] 2018-06-14 06:54
Hi @rsese 

Thanks for responding. I understand completely that there are limited resources for addressing all the issues that pop-up. I've had [a constructive discussion over in the Atom forum](https://discuss.atom.io/t/if-little-bugs-arent-fixed-in-atom-does-this-editor-have-a-future/55915/4) about this. If anything, my concerns come from a desire to see my preferred editor be even better.

Ultimately, I can live with needing to hit the back arrow key a couple times to add my comment text. I was frustrated at the time by the stale issue feedback loop.

**Comment by jrial** [comment] 2018-06-14 13:47
Stale simply means too much time has passed without any activity, and therefore the issue is deemed to be either solved or irrelevant, and consequently closed.

In this light, wouldn't it make sense to reopen the original issue now that it's been reported by a user again?
