### ISSUE TITLE
Mac OS X > Git not found

### ISSUE THREAD

**Issue by emveeoh** [atom/atom#11046] opened 2016-03-03 20:15 UTC
ERROR:
Multiple packages not finding git installation on Mac OS X. I have git installed. I updated it from git src and by using Homebrew. It works perfectly within Terminal. 

Atom seems to be looking for git and cannot find it. Is there some place within Atom that I can set the path to the git bin so that Atom and all of it's packages will find it?

My $PATH is already set to the correct path.
My simlinks are set to the correct path.
Besides Atom, all other applications are happy.

This is an ongoing issue with multiple users who do an update to git beyond the outdated version included in the Apple Dev Tools. 

I found this:
https://discuss.atom.io/t/unmet-git-dependency/14707/13

Suggestions:
- Better documentation and more detailed resolution instructions in error messages for this issue when it occurs in Atom. 

- Additionally, Atom could provide an input box in the global Settings to allow the user to provide a custom path to the git bin.

**Comment by lee-dohm** [comment] 2016-03-03 23:54
This is almost assuredly a duplicate of https://github.com/atom/atom/issues/11037. Please subscribe there for updates.

**Closed by lee-dohm** 2016-03-03 23:54 UTC
