### ISSUE TITLE
Bug on Git Tab

### ISSUE THREAD

**Issue by WLLR9505** [atom/atom#18152] opened 2018-09-28 20:28 UTC
Atom showing my e-mail in the last commit messages when I use on OFFLINE

Version: 1.31.1
OS: Windows 10

**Comment by rsese** [comment] 2018-09-28 20:43
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/github/issues/1528 so you can subscribe there for updates if you'd like.

Also, please use the issue template when creating issues - the information in the template is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-09-28 20:43 UTC
