### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by baiyinshi** [atom/atom#16388] opened 2017-12-15 07:01 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:173

Error: dlopen(/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/7p/qxqsxdq93kq0rwb_2gv7mdnr0000gn/T/AppTranslocation/C47D655F-E826-482B-AF80-BF0104004A91/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:47.6.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-12-15 18:48
Thanks for taking the time to contribute!

We noticed this looks like a duplicate of https://github.com/atom/atom/issues/15861, you can subscribe there for updates if you'd like.  If you can share any details in https://github.com/atom/atom/issues/15861 like what you were doing at the time of the error and whether you can reproduce, that would be super helpful.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-15 18:48 UTC
