### ISSUE TITLE
Editing is slow when parsing the wrong language

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#16590] opened 2018-01-18 18:16 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![cut crash](https://user-images.githubusercontent.com/1058982/35115023-0753ff38-fc87-11e7-910a-8cbc5d8c13b6.gif)

### Steps to Reproduce

1. Enable the `Use Tree Sitter Parsers` setting
1. Copy https://raw.githubusercontent.com/atom/language-php/3e45569d8fb3af6747f6e4208b16d17deb577b97/spec/php-spec.coffee to an untitled buffer
1. Change language mode to JavaScript
1. Select all text and `core:cut`
1. Atom crashes

**Expected behavior:** Atom to not crash when cutting text

**Actual behavior:** Atom crashes

**Reproduces how often:** 100%

### Versions

**Atom**: 1.25.0-dev-3d8902d x64
**Electron**: 1.7.10
**OS**: Microsoft Windows 7 Professional

### Additional Information

/cc: @maxbrunsfeld

**Comment by Ben3eeE** [comment] 2018-02-17 00:06
I can not reproduce the crash on latest master but I see a significant slowdown when editing this file.

The slowdown is not reproducible when disabling tree-sitter.

**Comment by Arcanemagus** [comment] 2018-07-30 16:34
I'm also unable to reproduce on v1.30.0-nightly15, marking as closed. We can always re-open if this is found to still be an issue.

**Closed by Arcanemagus** 2018-07-30 16:34 UTC
Labels: bug, crash, tree-sitter, triaged
