### ISSUE TITLE
Tab handling

### ISSUE THREAD

**Issue by SebastianGoendoer** [atom/atom#7979] opened 2015-07-20 08:12 UTC
There is an issue with the handling of Tabs in Atom, where tabs get replaced by (multiple) spaces, even with "softTabs: false". Here, tabs get replaced by (value of "tabLength") spaces. At some point, tabs are actually inserted as tabs. Google search found a comment claiming that this would depend on whether there is a "tab as spaces" already existing or not. Could not verify that on MacOS X, Atom 1.0.2.: pressing "tab" almost always adds (value of tabLength) spaces.
Next problem with this is that these spaces are sometimes interpreted as a tab, and at other times not. I.e. if you press "left", sometimes the cursor jumps back just one space (thus interpreting the inserted spaces as actual spaces) and at other times 4 spaces (where 4 is the setting of tabLength for me). Wasn't able to figure out a logic behind that...

Proposal: Change tab handling to that tabs are always treated as tabs and NEVER replaced when "softTabs" is off. Plus, add a short description to the config-pane for that value.

**Comment by benogle** [comment] 2015-07-20 17:45
Hey, sorry this isnt very clear. I'm going to close this as a duplicate of https://github.com/atom/atom/issues/3719.

**Closed by benogle** 2015-07-20 17:45 UTC
