### ISSUE TITLE
Changing encoding permanently destroys special characters

### ISSUE THREAD

**Issue by Dadibom** [atom/atom#13197] opened 2016-11-11 15:56 UTC
### Description

Atom completely destroys special characters in files when changing encoding. I mean, I get that stuff can go wrong since it's probably supposed to convert the file. But maybe it should check what the encoding is and not assume that it's utf-8 and destroy the file? (It saves the file and CTRL+Z cannot revert it)

### Steps to Reproduce

1. Put åäö in a file, save as iso8859-1 and close it
2. Set default encoding to utf-8
3. open the file and make some edit before changing encoding (sometimes I forget to check the file encoding before opening)
4. set encoding to iso8859-1

**Expected behavior:**
I expected to be able to edit files in the correct format without changing the default file encoding in the preferences each time i open a file

**Actual behavior:**
Special characters gone, I don't know why but CTRL+z stopped working, file is ruined (it's way too big to fix manually).

### Versions
atom 1.11.2
ubuntu 16.04

**Comment by Dadibom** [comment] 2016-11-11 16:20
The easiest fix would probably be to simply allow me to undo the encoding change.

**Comment by Ben3eeE** [comment] 2016-11-11 17:32
This is a duplicate of https://github.com/atom/encoding-selector/issues/33. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-11-11 17:32 UTC

**Comment by Dadibom** [comment] 2016-11-11 18:04
Oh, thanks!
