### ISSUE TITLE
Bottom pane obscures Find&Replace when hidden

### ISSUE THREAD

**Issue by wbkoetsier** [atom/atom#15432] opened 2017-08-24 10:40 UTC
I'd like to report the following issue for your information. Allthough it's a bit awkward for me, it doesn't break anything, a fix for me would be low priority.

Whenever I have linter-ui-default (1.6.7) package enabled, there is a panel in the bottom of the Atom window with a button to show or hide and a tab for linter:

![linter_obscures3](https://user-images.githubusercontent.com/1872066/29659299-1b3dadb0-88be-11e7-96a3-f0e752141e1e.JPG)

However, when it is hidden, this is what I see when I enable Find&Replace:

![linter_obscures1](https://user-images.githubusercontent.com/1872066/29659373-4ff82aa8-88be-11e7-97c0-1abfb56f7e5a.JPG)

The hidden panel obscures part of the 'replace' part of Find&Replace. When I hover my mouse in that area:

![linter_obscures2](https://user-images.githubusercontent.com/1872066/29659439-8f583544-88be-11e7-8db2-3833a626871c.JPG)

linter-ui-default got installed as dependency for api-workbench. Other community packages I have installed: linter, busy-signal and intentions (dependencies for linter-ui-default).

I reset to factory defaults and reproduced my packages and settings one-by-one, and restarted between every change, and repeated this multiple times in different order as well. I have found that this only occurs when linter-ui-default is installed (no dependencies or api-workbench installed yet), UI Theme is set to Atom Light and the Project pane at the left is hidden. (when Project is shown, the show-button of the bottom pane is enclosed by a black bar, like in the third picture above).

I couldn't find any related issues on the FAQ and the issues.

Expected behaviour: the pane and button stay below the Find&Replace when hidden, instead of partially obscuring it.

Atom: 1.19.3 x64, Windows 10

Please let me know if I should report this to linter-ui-default or perhaps to the creators of the Atom Light theme instead.

**Comment by 50Wliu** [comment] 2017-08-24 13:59
@wbkoetsier it looks like this is a duplicate of #14915.  Please tell me if you don't think that's the case!

**Closed by 50Wliu** 2017-08-24 13:59 UTC

**Comment by wbkoetsier** [comment] 2017-08-28 12:32
It seems to be the same problem, thank you for finding it for me. I was unaware the bottom panel was called 'dock'.
