### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1168

### ISSUE THREAD

**Issue by SimonBaars** [atom/atom#19067] opened 2019-03-28 13:31 UTC
[What I did:]

1. Working on my LateX file.
2. CTRL+S to Save.

[Is the error reproducible?]
Not that I know no

**Atom**: 1.35.1 x64
**Electron**: 3.1.6
**OS**: "Antergos Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1168
Error: Cannot call function 'getPosition' on missing remote object 1168
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 1168
Error: Cannot call function 'getPosition' on missing remote object 1168
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/usr/lib/atom/src/atom-environment.js:684:34)
    at AtomEnvironment.storeWindowDimensions (/usr/lib/atom/src/atom-environment.js:721:34)
    at WindowEventHandler.handleWindowBlur (/usr/lib/atom/src/window-event-handler.js:191:26)
```

### Commands

```
     -3:12.1.0 core:move-up (input.hidden-input)
     -2:47.3.0 autocomplete-plus:confirm (input.hidden-input)
     -2:46.5.0 core:backspace (input.hidden-input)
     -2:45.9.0 editor:newline (input.hidden-input)
 22x -2:43.7.0 core:backspace (input.hidden-input)
     -1:55.1.0 intentions:highlight (input.hidden-input)
     -1:55 core:paste (input.hidden-input)
     -1:53.7.0 core:backspace (input.hidden-input)
     -1:53.3.0 core:move-right (input.hidden-input)
     -1:53.2.0 core:move-down (input.hidden-input)
     -1:51.5.0 editor:newline (input.hidden-input)
     -1:51.1.0 core:backspace (input.hidden-input)
     -0:31.1.0 editor:newline (input.hidden-input)
     -0:27.3.0 intentions:highlight (input.hidden-input)
     -0:27.2.0 core:paste (input.hidden-input)
  6x -0:24.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-ansible 0.1.24 
busy-signal 2.0.1 
file-icons 2.1.31 
file-types 1.0.1 
ftp-remote-edit 0.13.6 
intentions 1.1.5 
language-ansible 0.2.2 
language-latex 1.2.0 
latex 0.50.2 
latex-completions 0.3.6 
linter 2.3.0 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.7.1 
move-panes 0.2.0 
pretty-json 2.0.3 
```

**Comment by rsese** [comment] 2019-03-28 20:25
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-03-28 20:25 UTC
