### ISSUE TITLE
Digit grouping symbol to match system setting

### ISSUE THREAD

**Issue by AlsoScratch** [atom/atom#20865] opened 2020-06-01 11:54 UTC
## Summary

I want it to be possible to change the digit grouping symbol from comma to space. (see screenshot)
## Motivation

I learned that comma is technically the wrong symbol to use for digit grouping. It should always be a space. Fortunately, Windows and macOS have the option to change it, but it can't do much outside the OS's built-in apps (like Calculator).

All we need is probably for Atom to change the digit grouping symbol according to the computer's language and region settings.
## Describe alternatives you've considered

It could also be possible to manually change the digit grouping symbol, decimal symbol, and digit grouping _manner_.

Digit grouping and decimal symbol could be a text field where the user enters a single character to use as the respective symbol. In my case, I would insert ` ` (whitespace) into the digit grouping symbol field and leave the decimal symbol field as default. (assuming it's `.`)

Digit grouping _manner_ would be a dropdown list of the following options:

- 123 456 789 (groups of 3)
- 12 34 56 789 (lowest group 3, from there onwards 2)
- 1 2345 6789 (groups of 4)

## Additional context

<img width="205" alt="Screenshot 2020-05-31 at 11 52 22 PM" src="https://user-images.githubusercontent.com/48752273/83404681-a8318780-a43d-11ea-9b50-79084d63a060.png">

**Comment by Arcanemagus** [comment] 2020-06-01 20:11
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/3103. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-06-01 20:11 UTC

**Comment by AlsoScratch** [comment] 2020-06-11 10:43
This has nothing to do with translations, I just wanted an option to change the digit grouping symbol to space independently of the language or region. Please reopen until this is implemented.

**Comment by Arcanemagus** [comment] 2020-06-11 18:50
Digit grouping is a localization issue, for example while you say this:
> I learned that comma is technically the wrong symbol to use for digit grouping.

That is entirely inaccurate for where I live. The "right" way to group numbers depends on your localization settings.

**Comment by AlsoScratch** [comment] 2020-06-12 14:16
> That is entirely inaccurate for where I live. The "right" way to group numbers depends on your localization settings.

Well too bad. The General Conference on Weights and Measures has clearly worded against commas or dots as decimal separators.

> "Numbers may be divided in groups of three in order to facilitate reading; **neither dots
> nor commas are ever inserted** in the spaces between groups"
_Source: [https://www.bipm.org/utils/en/pdf/Resol22CGPM-EN.pdf](https://www.bipm.org/utils/en/pdf/Resol22CGPM-EN.pdf)_

Regardless, my request at the top of the page still applies.

**Comment by AlsoScratch** [comment] 2020-07-06 04:18
Is there at least a package I can install to do this?
