### ISSUE TITLE
Atom loosing focus on OSX caused a bug

### ISSUE THREAD

**Issue by prettydiff** [atom/atom#12861] opened 2016-10-03 20:49 UTC
Here is a gist of the generated error message:

https://gist.github.com/prettydiff/13db6f442fe313cd53471f84a3958c7d

Sorry, but I do not have additional information to provide.

**Comment by Ben3eeE** [comment] 2016-10-03 20:56
Duplicate of https://github.com/atom/atom/issues/11692

**Closed** 2016-10-03 21:26 UTC
Labels: duplicate
