### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/myagoo/dev/workspace/project-eyelo/lib/prolo-eyelo/src/modules/wanDashboard/wanDashboard.controller.js'

### ISSUE THREAD

**Issue by myagoo** [atom/atom#6680] opened 2015-05-07 12:57 UTC
[Enter steps to reproduce below:]

1. open a file and modify it
2. revert modification with git (eg: git checkout {file})

**Atom Version**: 0.196.0
**System**: linux 3.13.0-52-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/myagoo/dev/workspace/project-eyelo/lib/prolo-eyelo/src/modules/wanDashboard/wanDashboard.controller.js'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/home/myagoo/dev/workspace/project-eyelo/lib/prolo-eyelo/src/modules/wanDashboard/wanDashboard.controller.js'
  at Error (native)

```

### Commands

```
     -3:02.5.0 editor:newline (atom-text-editor.editor)
     -3:02.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -3:02.3.0 editor:newline (atom-text-editor.editor)
     -3:00.3.0 core:backspace (atom-text-editor.editor)
  2x -3:00.1.0 core:delete (atom-text-editor.editor)
  3x -2:58.9.0 core:backspace (atom-text-editor.editor)
     -2:52.6.0 core:save (atom-text-editor.editor)
     -2:20.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -2:20.7.0 editor:newline (atom-text-editor.editor)
  2x -2:16.4.0 core:copy (atom-text-editor.editor)
     -2:14.5.0 core:paste (atom-text-editor.editor)
  2x -2:14 core:move-right (atom-text-editor.editor)
  3x -2:11 core:save (atom-text-editor.editor)
     -0:42.2.0 core:backspace (atom-text-editor.editor)
  2x -0:41.5.0 core:save (atom-text-editor.editor)
  4x -0:11.9.0 core:undo (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "linter-jshint",
      "merge-conflicts"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.27.0
color-picker, v1.7.0
editorconfig, v1.0.0
emmet, v2.3.8
file-icons, v1.5.5
local-history, v3.1.0
minimap, v4.8.0
project-manager, v1.15.5
react, v0.11.8

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-07 12:59
Duplicate of #6210, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-07 12:59 UTC
