### ISSUE TITLE
Failed to activate the atom-lint package

### ISSUE THREAD

**Issue by hi0711** [atom/atom#6262] opened 2015-04-06 04:33 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the atom-lint package

```
At Cannot read property 'previous' of undefined

TypeError: Cannot read property 'previous' of undefined
    at /Users/hi0711/.atom/packages/atom-lint/lib/atom-lint.coffee:60:59
    at Config.module.exports.Config.observeKeyPath (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/config.js:621:7)
    at Config.module.exports.Config.observe (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/config.js:133:21)
    at Function.module.exports.Config.observe (/Users/hi0711/.atom/packages/atom-lint/lib/config.coffee:38:26)
    at Object.module.exports.enable (/Users/hi0711/.atom/packages/atom-lint/lib/atom-lint.coffee:57:47)
    at Object.module.exports.activate (/Users/hi0711/.atom/packages/atom-lint/lib/atom-lint.coffee:29:19)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:240:19)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:214:14)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrap": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v2.0.14
atom-lint, v0.20.0
autocomplete-paths, v0.9.0
autocomplete-plus, v0.22.14
autocomplete-snippets, v0.3.1
emmet, v2.3.2
file-icons, v1.4.3
japanese-wrap, v0.2.3
tag, v0.2.3

# Dev
No dev packages
```

**Comment by v3ss0n** [comment] 2015-04-06 04:57
Can you open issue at atom-lint ?

**Comment by izuzak** [comment] 2015-04-06 12:40
Looks like a duplicate of https://github.com/yujinakayama/atom-lint/issues/144.

**Closed by izuzak** 2015-04-06 12:40 UTC
