### ISSUE TITLE
Request: Create ARM version

### ISSUE THREAD

**Issue by wozzes** [atom/atom#13499] opened 2016-12-24 14:38 UTC
Please make ARM port of Atom!

**Comment by m1guelpf** [comment] 2016-12-24 15:28
+1 for this!

**Comment by lee-dohm** [comment] 2016-12-24 19:22
Thanks for reaching out!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/7822. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2016-12-24 19:22 UTC
