### ISSUE TITLE
Undo / redo stack should be saved between reloads.

### ISSUE THREAD

**Issue by nicu** [atom/atom#8568] opened 2015-08-29 06:53 UTC
I'm trying to develop a plugin for Atom, but every time I reload the editor to see the new code changes, I lose the undo/redo stack.
Would be nice to be able to save it per 'session' and only clear it when the tab or editor is closed. 
I understand that reloading the editor using ctrl+alt+cmd+L is effectively closing the tabs and it could get tricky to detect if the user manually closed a tab, or chose to close all tabs, but I think it's doable.

Also, I had to disable the "Whitespace" package: https://discuss.atom.io/t/save-redo-save-redo-then-redo-did-not-work-bug/10501
In my opinion, the undo/redo stack should not be affected by packages.

**Comment by mnquintana** [comment] 2015-08-29 11:18
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/148 – please subscribe there for updates.

**Closed by mnquintana** 2015-08-29 11:18 UTC
