### ISSUE TITLE
Blurry Font and Ripple Effect Menu Bar!

### ISSUE THREAD

**Issue by jack-dev** [atom/atom#10380] opened 2016-01-11 22:32 UTC
This same thing happens on Atom, Visual Studio and Light Table, Brackets its fine.

Text is very distorted and blurry and it gets better if I hover with a mouse over part of a text (only that part gets better) if I don't move the mouse that area gets bad again, also the menu bar gets something like Ripple effect or like a page is opening and its moving, could someone explain why this happens?!

OS: Windows 10 Pro 1151

![screenshot 32](https://cloud.githubusercontent.com/assets/9529847/12248643/1299d6a4-b8bb-11e5-8ecd-45ec7793f5fc.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/9529847/12248644/12afc068-b8bb-11e5-8194-28d69ca0eb29.png)

**Comment by lee-dohm** [comment] 2016-01-12 00:13
It sounds like a bad video driver or card to me, especially since this is happening in multiple applications. Can you reproduce the problem in Chrome?

**Comment by jack-dev** [comment] 2016-01-12 11:17
@lee-dohm No I can't repro on Chrome, chrome is fine, I'm using Radeon Graphics Crimson Edition Drivers, if I can't repro on chrome hat means the problem is in Electron

**Comment by lee-dohm** [comment] 2016-01-12 16:44
We haven't seen anything like this. Can you reproduce this on another computer?

**Comment by musmo** [comment] 2016-03-08 04:08
Maybe related to #10185.

For me some parts of the text are blurry others aren't as bad. But on the whole font rendering is very, very bad.

**Comment by lee-dohm** [comment] 2016-03-08 05:37
@damieng can you work your font magic here?

**Comment by damieng** [comment] 2016-03-08 05:58
Electron uses DirectWrite hardware graphics acceleration and I suspect these new Radeon drivers are applying some additional processing effects without realizing what the result will be. Very few apps do this today although Chrome does I suspect they have opted Chrome out of things.

I'd try going into the Chrome folder on your machine and copying the chrome.exe and launching that to see if the new copy has distorted text (drivers tend to opt apps out based on the filename of the executable).

These new Radeon drivers do let you specify 3D options for specific apps according to http://www.anandtech.com/show/9811/amd-crimson-driver-overview/4 so I'd recommend adding atom.exe to that and turning off a bunch of options to see if it improves. (I don't have an AMD card to repro with as I use Nvidia)

I suspect this is going to be a Radeon driver bug they're going to want to address as it's going to affect more and more apps using DirectWrite.

**Comment by damieng** [comment] 2016-03-08 06:22
Based on some more research I think the specific setting you want to disable for atom.exe (and potentially other EXE's that use Electron) is to disable **Morphological Anti-Aliasing (MLAA)**

**Comment by musmo** [comment] 2016-03-09 00:46
I'm using an Nvidia and intel GPU.  @damieng  How can i disable  Morphological Anti-Aliasing (MLAA)?

**Comment by damieng** [comment] 2016-03-09 01:29
@musmo are you seeing exact same effect? Can you post a screen shot from yours too?

**Comment by musmo** [comment] 2016-03-09 01:31
![image](https://cloud.githubusercontent.com/assets/4319522/13622424/ad5e769e-e56c-11e5-9d9d-e1c518365d18.png)


bottom paragraph blurry top not blurry

**Comment by damieng** [comment] 2016-03-09 02:06
That's actually a different issue relating I think to sign pixel positioning. I'll see if I can find the issue number for the other one and link it here.

**Comment by damieng** [comment] 2016-03-09 21:06
Given other reports I've seen online referring to AMD drivers, this kind of text effect and the need to disable MLAA I'm going to close this bug. Please re-open if this does not solve your issue @jack-dev

**Closed by damieng** 2016-03-09 21:06 UTC
Labels: needs-reproduction, windows
