### ISSUE TITLE
Error when installing Linter in Atom (Windows 7)

### ISSUE THREAD

**Issue by elevenE** [atom/atom#4419] opened 2014-12-06 10:44 UTC
Hi, 

I get these errors when trying to install Linter package in Atom:

npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/jshint
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/chai
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/assertion-error/1.0.0
npm http GET https://registry.npmjs.org/deep-eql/0.1.3
npm ERR! Error: ENOENT, lstat 'C:\Users\I5TWO~1\AppData\Local\Temp\apm-install-dir-114116-25216-14g3dxl\node_modules\linter\node_modules\jshint\src\jshint.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\i 5 two\\.atom\\.apmrc" "install" "C:\\Users\\i 5 two\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.8.0\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2010"
npm ERR! cwd C:\Users\I5TWO~1\AppData\Local\Temp\apm-install-dir-114116-25216-14g3dxl
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\I5TWO~1\AppData\Local\Temp\apm-install-dir-114116-25216-14g3dxl\node_modules\linter\node_modules\jshint\src\jshint.js
npm ERR! fstream_path C:\Users\I5TWO~1\AppData\Local\Temp\apm-install-dir-114116-25216-14g3dxl\node_modules\linter\node_modules\jshint\src\jshint.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack d:\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\I5TWO~1\AppData\Local\Temp\apm-install-dir-114116-25216-14g3dxl\node_modules\linter\node_modules\sinon\pkg\sinon-1.12.0.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\i 5 two\\.atom\\.apmrc" "install" "C:\\Users\\i 5 two\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.8.0\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2010"
npm ERR! cwd C:\Users\I5TWO~1\AppData\Local\Temp\apm-install-dir-114116-25216-14g3dxl
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\I5TWO~1\AppData\Local\Temp\apm-install-dir-114116-25216-14g3dxl\node_modules\linter\node_modules\sinon\pkg\sinon-1.12.0.js
npm ERR! fstream_path C:\Users\I5TWO~1\AppData\Local\Temp\apm-install-dir-114116-25216-14g3dxl\node_modules\linter\node_modules\sinon\pkg\sinon-1.12.0.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack d:\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "d:\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\i 5 two\\.atom\\.apmrc" "install" "C:\\Users\\i 5 two\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.8.0\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2010"
npm ERR! cwd C:\Users\I5TWO~1\AppData\Local\Temp\apm-install-dir-114116-25216-14g3dxl
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 200 https://registry.npmjs.org/deep-eql/0.1.3
npm http GET https://registry.npmjs.org/deep-eql/-/deep-eql-0.1.3.tgz
npm http 200 https://registry.npmjs.org/assertion-error/1.0.0
npm http GET https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.0.tgz
npm http 200 https://registry.npmjs.org/deep-eql/-/deep-eql-0.1.3.tgz
npm http 200 https://registry.npmjs.org/assertion-error/-/assertion-error-1.0.0.tgz
npm http GET https://registry.npmjs.org/type-detect/0.1.1
npm http 200 https://registry.npmjs.org/type-detect/0.1.1
npm http GET https://registry.npmjs.org/type-detect/-/type-detect-0.1.1.tgz
npm http 200 https://registry.npmjs.org/type-detect/-/type-detect-0.1.1.tgz

**Comment by mnquintana** [comment] 2015-04-13 21:06
Closing as duplicate of #2263

**Closed by mnquintana** 2015-04-13 21:06 UTC
Labels: more-information-needed
