### ISSUE TITLE
Atom crashes frequently on win10

### ISSUE THREAD

**Issue by yorick-nogle** [atom/atom#16629] opened 2018-01-25 04:24 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashes frequently on win10, no special activities. 
plugins: go-plus, atom-html-preview, open-terminal-here

### Versions

1.23.3 x64

### Additional Information
[c5ce0435-68fe-4ab3-98bc-59e2584d3c19.txt](https://github.com/atom/atom/files/1662574/c5ce0435-68fe-4ab3-98bc-59e2584d3c19.txt)

**Comment by rsese** [comment] 2018-01-25 18:38
Thanks for the report - I see you checked off the Prerequisites section but just to double check, is there any difference in safe mode (`atom --safe`)?  I ask because I remember seeing reports of problems with atom-html-preview possibly causing crashes, I think that package hasn't had updates in a while.

**Comment by fuyutsuki** [comment] 2018-01-29 09:06
I am having the same problem.

### Environments
Win10 Home x64
### Versions
1.23.3 x64
### Method of reproducing problem
1. Either normal mode or safe mode is OK so start it.
2. The following error will be issued, and some of the packages used until now will not function.  
(if you re-enable it, you will return to the original).
![default](https://user-images.githubusercontent.com/16377174/35501897-a2f674b2-051e-11e8-84d5-2e45901d6a7f.JPG)
3. Closing the window of Atom will cause the PC to crash with the following error.
> Stop code: PAGE_FAULT_IN_NONPAGED_AREA
Failed content: K7Sentry.sys

**Comment by lee-dohm** [comment] 2018-01-31 19:21
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16629#issuecomment-360558976. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by lee-dohm** 2018-01-31 19:21 UTC
Labels: more-information-needed
