### ISSUE TITLE
Add Search and Replace button in the search

### ISSUE THREAD

**Issue by thisisnian** [atom/atom#8476] opened 2015-08-22 06:56 UTC
I was trying to do a search across all text files in a directory and what I noticed was there was no search button. I know the default search/replace button is the enter button on the keyboard, however there is no text advising that it is so.

What I propose is to add a 'Search' and also a 'Replace' button which would mimic the enter keypress of the respective textboxes in the red area highlighted below. If you look at other text editors, you will see that both methods are provided. Also the textboxes are pretty wide so the buttons can be accomodated without too much hassle UI wise.

![image](https://cloud.githubusercontent.com/assets/3102540/9422930/5253a5f0-48ee-11e5-9c04-0bcb91f4bc7b.png)

Just putting it out there to see if there is a consensus in doing this change.

**Comment by izuzak** [comment] 2015-08-22 07:15
I think this is a duplicate of https://github.com/atom/find-and-replace/issues/297 -- could you please add a comment there? That issue is closed, but we'd still appreciate if all the feedback regarding this is in one place -- that would help us follow the discussion and determine priority. Thanks!

**Closed by izuzak** 2015-08-22 07:15 UTC
