### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Moussab-Orabi** [atom/atom#17951] opened 2018-08-30 07:32 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:28

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:501:7)
    at onEvents.events.map.event (~/AppData/Local/atom/app-1.30.0/resources/app/src/path-watcher.js:283:46)
    at Array.map (<anonymous>)
    at handler (~/AppData/Local/atom/app-1.30.0/resources/app/src/path-watcher.js:276:34)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-09-03 18:49
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14227 so you can subscribe there for updates if you'd like.  Some people mentioned that changing the `Settings > File System Watcher` setting avoids the error /cc https://github.com/atom/atom/issues/14227#issuecomment-404041663

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-09-03 18:49 UTC
