### ISSUE TITLE
Atom crashes on opening a HTML file

### ISSUE THREAD

**Issue by dandaka** [atom/atom#11395] opened 2016-04-07 14:00 UTC
### Description

Atom crashes, when I open an HTML file (named msw.html)

### Steps to Reproduce

1. Download file https://gist.github.com/dandaka/35c535fde59a37f2ee1fab8109a2e05f
2. Name it msw.html
3. Open in Atom

**Expected behavior:**

Normal opening of a file

**Actual behavior:** 

Crash

Also pasting same content in Atom also crashes it.

### Versions

Atom 1.6.2
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.2
OSX 10.11.4

Crash log https://gist.github.com/dandaka/51d307c732651dfc06494f01f6cb5b5d

* Problem can be reproduced in safe mode: [Yes]
* Problem started happening recently, didn't happen in an older version of Atom: Don't know
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: Don't know

**Comment by Ben3eeE** [comment] 2016-04-07 14:26
Likely a duplicate of https://github.com/atom/atom/issues/979

**Comment by 50Wliu** [comment] 2016-04-07 19:57
Agreed.

**Closed by 50Wliu** 2016-04-07 19:57 UTC
