### ISSUE TITLE
Middle mouse click in tab paste text of clipboard

### ISSUE THREAD

**Issue by leotada** [atom/atom#15136] opened 2017-08-01 14:00 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Middle mouse click in tabs, paste text of clipboard in the text buffer.

### Steps to Reproduce

1. Install Atom 1.19.0-beta5
2. Store anything in you clipboard (CTRL+C)
3. Open more than one tab in Atom
4. Click with middle buton mouse in any tab to close

**Expected behavior:** Not paste anything while you are closing tabs.

**Actual behavior:** Appears in the text buffer you clipboard.

**Reproduces how often:** Always.

### Versions

Atom    : 1.19.0-beta5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Tested on Fedora 26 x64.

**Comment by theonedemon** [comment] 2017-08-01 17:53
+1

**Comment by 50Wliu** [comment] 2017-08-02 02:31
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/461. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-02 02:31 UTC
