### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by phant0mnyc** [atom/atom#16892] opened 2018-03-06 15:15 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:867:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:376:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1550:59)
```

### Commands

```
     -1:56.7.0 snippets:expand (input.hidden-input)
     -1:56.7.0 editor:indent (input.hidden-input)
  6x -1:56.2.0 core:backspace (input.hidden-input)
     -1:49.1.0 core:save (input.hidden-input)
     -1:45.7.0 editor:newline (input.hidden-input)
     -1:44.3.0 core:save (input.hidden-input)
     -1:16.3.0 emmet:toggle-comment (input.hidden-input)
     -1:16.3.0 editor:toggle-line-comments (input.hidden-input)
  3x -1:15.9.0 core:save (input.hidden-input)
     -0:33.8.0 core:backspace (input.hidden-input)
     -0:32.9.0 core:save (input.hidden-input)
     -0:28.5.0 find-and-replace:show (input.hidden-input)
  3x -0:26.8.0 core:backspace (input.hidden-input)
  4x -0:25.9.0 core:confirm (input.hidden-input)
     -0:19.5.0 editor:newline (input.hidden-input)
  4x -0:18.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
2-dark-syntax 1.1.0 
atom-html-preview 0.2.5 
atom-terminal 0.8.0 
blessed-dark-syntax 0.3.0 
city-lights-syntax 1.1.2 
city-lights-ui 1.1.7 
emmet 2.4.3 
snow-dark-syntax 0.1.1 
sort-lines 0.18.0 
terminal-plus 0.14.5 
```

**Comment by rsese** [comment] 2018-03-06 18:36
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by dixonwille** [comment] 2018-03-07 20:16
@rsese I am able to reproduce in safe mode. When not in safe mode it pops up really often. In safe mode not so much. There is one specific file that if I remember correctly I used the collapse lines.

**Comment by dixonwille** [comment] 2018-03-07 21:00
Just switched from `One Dark` to `Atom Dark` theme and unable to reproduce now?

**Comment by davisk4rpi** [comment] 2018-03-07 21:53
Could you try running `atom --clear-window-state`?  I suggest reading the link below first as "Clearing the saved state permanently destroys any state that Atom has saved across all projects"

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by dixonwille** [comment] 2018-03-07 21:58
@davisk4rpi as mentioned above I am unable to reproduce now (changed themes back and still unable to reproduce). Wish I could be of more help.

**Comment by alxtz** [comment] 2018-03-08 02:08
I've also faced the same issue, I think this is quite critical since the editor would freeze forever unless you clear the window state manually.

**Comment by rsese** [comment] 2018-03-08 05:38
Does anyone have specific steps to reproduce the error?  And if you can still reproduce, is it reproducible for you in safe mode?

Also curious if you can share your community package list, I wonder if there's anything in common (`apm list --installed`).

**Comment by probkiller** [comment] 2018-03-10 18:01
Atom had been crashing frequently for me for the past couple of days and this problem cropped up today. Don't remember what triggered this. But clearing window state helped. Will post an update if the problem reappears

**Comment by fergusmeiklejohn** [comment] 2018-03-23 03:24
To see this bug I:
Worked on a elm file in Atom.
Closed Atom
Worked on the same Elm file in JetBrains Rider
Save and close Rider
Open Atom
Bug appears:
Uncaught TypeError: Cannot read property 'length' of undefined
/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329

To fix
Quit Atom
atom --clear-window-state

**Comment by rsese** [comment] 2018-03-23 19:43
Thanks @fergusmeiklejohn - with those steps can you reproduce in safe mode?

**Comment by AldonIsenberg11** [comment] 2018-03-26 20:29
`apm list --installed`
├── atom-beautify@0.30.9
├── atom-jade@0.3.0
├── busy-signal@1.4.3
├── coffee-compile@0.29.0
├── editorconfig@2.2.2
├── emmet@2.4.3
├── file-icons@2.1.16
├── jade-autocompile@0.8.5
├── language-jade@0.7.2
├── language-vue@0.23.1
└── react@0.18.0

---
<img width="1317" alt="screen shot 2018-03-26 at 3 29 21 pm" src="https://user-images.githubusercontent.com/23458977/37931193-7c535650-310a-11e8-8fa4-999523d83407.png">

**Comment by FernandoGOT** [comment] 2018-04-05 19:30
Just got the same problem, for some reason wen I try to open one project (this happen only at this project) the developer tools window is opened and so the atom stop working for this project. All other projects can run normally at the same tume

**Comment by Qwlouse** [comment] 2018-04-17 09:10
Also got this problem, right after starting atom on a particular project. It also persisted through multiple restarts and in safe mode. It would keep popping up when clicking or scrolling, but only on the `main.tex` file. Interestingly deleting all the text in the file resolved the problem. I then restarted atom and pasted the text back, but the problem is gone now. 

<details>
<summary>atom --version</summary>

```
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
</details>

<details>
<summary>Stacktrace from the console</summary>

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/usr/share/atom/resources/app/src/text-editor-component.js:870:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/src/text-editor-component.js:377:16)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.flushPendingLogicalScrollPosition (/usr/share/atom/resources/app/src/text-editor-component.js:2033:18)
    at TextEditorComponent.didShow (/usr/share/atom/resources/app/src/text-editor-component.js:1461:18)
    at TextEditorComponent.didAttach (/usr/share/atom/resources/app/src/text-editor-component.js:1427:20)
    at TextEditorComponent.didFocus (/usr/share/atom/resources/app/src/text-editor-component.js:1478:36)
    at HTMLElement.addEventListener (/usr/share/atom/resources/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.<anonymous> (/usr/share/atom/resources/app.asar/src/pane-element.js:54:18)
    at HTMLElement.PaneElement.activated (/usr/share/atom/resources/app.asar/src/pane-element.js:117:14)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.activate (/usr/share/atom/resources/app/src/pane.js:1011:24)
    at HTMLElement.handleFocus (/usr/share/atom/resources/app.asar/src/workspace-element.js:223:32)
    at HTMLElement.attachedCallback (/usr/share/atom/resources/app.asar/src/workspace-element.js:12:10)
    at loadStatePromise.loadState.then (/usr/share/atom/resources/app/src/atom-environment.js:847:32)
    at <anonymous>
<embedded>:8335 Uncaught TypeError: Cannot read property 'delete' of undefined
    at TextEditorComponent.didDetach (/usr/share/atom/resources/app/src/text-editor-component.js:1450:48)
    at HTMLElement.detachedCallback (/usr/share/atom/resources/app.asar/src/text-editor-element.js:47:25)
    at HTMLElement.PaneAxisElement.childAdded (/usr/share/atom/resources/app.asar/src/pane-axis-element.js:92:12)
    at HTMLElement.PaneAxisElement.attachedCallback (/usr/share/atom/resources/app.asar/src/pane-axis-element.js:26:27)
    at loadStatePromise.loadState.then (/usr/share/atom/resources/app/src/atom-environment.js:847:32)
    at <anonymous>
<embedded>:135570 Uncaught TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/usr/share/atom/resources/app/src/text-editor-component.js:870:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/src/text-editor-component.js:377:16)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didShow (/usr/share/atom/resources/app/src/text-editor-component.js:1460:18)
    at TextEditorComponent.didAttach (/usr/share/atom/resources/app/src/text-editor-component.js:1427:20)
    at HTMLElement.attachedCallback (/usr/share/atom/resources/app.asar/src/text-editor-element.js:41:25)
    at HTMLElement.PaneAxisElement.childAdded (/usr/share/atom/resources/app.asar/src/pane-axis-element.js:92:12)
    at HTMLElement.PaneAxisElement.attachedCallback (/usr/share/atom/resources/app.asar/src/pane-axis-element.js:26:27)
    at loadStatePromise.loadState.then (/usr/share/atom/resources/app/src/atom-environment.js:847:32)
    at <anonymous>
<embedded>:135570 Uncaught TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/usr/share/atom/resources/app/src/text-editor-component.js:870:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/src/text-editor-component.js:377:16)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:275:16)
    at etch.getScheduler.updateDocument (/usr/share/atom/resources/app/src/text-editor-component.js:225:46)
    at ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:238:13)
```
</details>

<details>
<summary>apm list --installed</summary>

```
Community Packages (17) /home/greff/.atom/packages
├── Zen@0.18.0
├── atom-latex@0.8.4
├── busy-signal@1.4.3
├── custom-folds@1.9.5 (disabled)
├── file-icons@2.1.18
├── intentions@1.1.5
├── linter@2.2.0
├── linter-just-say-no@0.7.4 (disabled)
├── linter-spell@0.15.0 (disabled)
├── linter-spell-latex@0.11.0 (disabled)
├── linter-ui-default@1.7.1
├── linter-write-good@0.9.0 (disabled)
├── minimap@4.29.8 (disabled)
├── multi-cursor@2.1.5
├── thesaurus@0.3.0
└── wordcount@2.10.4
```
</details>

**Comment by uribes78** [comment] 2018-04-23 21:50
I tried working my project using GVim and modified some files, then I decided to open it at Atom, then the application crash, just when I try to open the file modified by GVim. I haven't clean the window state.

**Comment by uribes78** [comment] 2018-04-23 22:06
Well, I did a --clean-window-state, looks like work for me.

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

 ~/.atom/packages
├── atom-dark-monokai-syntax@0.18.0
├── file-icons@2.1.18
└── seti-syntax@1.1.3

Regards

**Comment by davincif** [comment] 2018-04-30 14:28
same issue. I'm unable to working in a projeto with ionic3, using angular4, typescript, scss... oddly I can work perfectly fine in a python + falcon + django project.

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

Community Packages (14) ~/.atom/packages
├── ScssBundle@0.5.0
├── atom-overtype-mode@0.4.0
├── atom-typescript@12.4.1
├── autoclose-html@0.23.0
├── autocomplete-python@1.10.5
├── busy-signal@1.4.3
├── color-picker@2.3.0
├── intentions@1.1.5
├── linter@2.2.0
├── linter-julia@0.7.3
├── linter-scss-lint@3.1.1
├── linter-ui-default@1.7.1
├── pigments@0.40.2
└── teletype@0.13.1

**Comment by Qwlouse** [comment] 2018-04-30 17:00
@davincif: ;-)
```
<details>
<summary>atom --version</summary>

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
</details>
```

**Comment by xanfus** [comment] 2018-05-11 13:36
```
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
Bug doesn't appear after sole usage of "--safe" option.

**Comment by jchook** [comment] 2018-06-13 23:51
Got this bug as well even after updating.

```
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by Zack-83** [comment] 2018-06-14 17:55
Hallo, I don't know if my problem is related:
Atom behaves strangely when dealing with a HTML file with Django syntax
which uses the `|length` filter within a `{% ... %}` tag.
Upon saving, the program creates two spaces around the pipe character, thus yielding
`variable | length.`
As a consequence, the Django interpreter does not parse the code correctly and yields an error message.
Does it depend on Atom itself or on the Django-Atom package?

**Comment by jstephani2** [comment] 2018-06-21 14:49
In my config file, I have the language of .twig extensions set to HTML. I then manually set the language of a .twig file to plain text. This bug popped up when I reopened the project in atom. It popped up multiple times, but stopped once I closed the file.

**Comment by josfaber** [comment] 2018-07-04 07:11
Reseting the window state atom --clear-window-state worked for me too. 

The problem showed up this morning, errors seemed to be triggered from the minimap package. On disabling minimap, the linter-ui-default began causing the error. Disabling that package, the error came from atom/atom.

Now on Atom Mac, before the error the file was edited on Atom Windows and then pushed into Bitbucket.

**Comment by beginrescueend** [comment] 2018-08-07 21:35
Today (2018-08-07), I also get "Uncaught TypeError: Cannot read property 'length' of undefined" on my Mac (High Sierra 10.13.6). It did this before I updated Atom and all packages and it also did it afterward.  I also got the `minimap` error, reported above on July 4. ^^

It did it repeatedly, but only if I opened files that Atom knew about in its history.  If I did `atom --help` or `atom -?` or if I did `atom <file that does not exist>`, it would work.

Just `atom` or `atom <file that generated the error>`, it would crash with the above error message.  It also did it in `atom --safe` mode.

After I closed all files in atom's history and closing `atom`, I can no longer reproduce the issue.  It now works, again.

**Comment by alisianoi** [comment] 2018-08-28 20:44
Subscribing. My two cents:

Similar to https://github.com/atom/atom/issues/16892#issuecomment-371270214, I was using collapse lines (collapsed many different blocks, collapsed/uncollapsed the same blocks several times). This is the first time I used collapsing feature, did not have this problem at all before (when not using collapsing feature).

Similar to https://github.com/atom/atom/issues/16892#issuecomment-371282926 my theme is One Dark.

**Comment by chokri** [comment] 2018-09-21 19:07
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04.1
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/usr/share/atom/resources/app/src/text-editor-component.js:870:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/src/text-editor-component.js:377:16)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:275:16)
    at etch.getScheduler.updateDocument (/usr/share/atom/resources/app/src/text-editor-component.js:225:46)
    at ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:238:13)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.1 
atom-eclipse-syntax 0.0.6 
atom-material-syntax 1.0.8 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
autumn-highlighter-syntax 1.13.0 
ayu 0.1.0 
ayu-mirage-atom-syntax 1.0.2 
ayu-mirage-ish-syntax 1.1.0 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
file-icons 2.1.24 
isotope-light-ui 2.3.0 
language-cmake 1.1.0 
language-ejs 0.4.0 
php-twig 4.0.0 
piatto-light-syntax 0.2.2 
platformio-ide-terminal 2.8.4 
spacegray-light-neue-ui 0.1.7 
two-light-ui 1.1.3 
```

**Comment by Ben3eeE** [comment] 2018-09-21 19:54
@chokri You Atom version is very old and there has been many fixes regarding the error you are seeing since then.

@alisianoi There are some bugs with folding that you may want to subscribe to I believe https://github.com/atom/atom/issues/16078 could cause this error.

@beginrescueend If you get this after updating a package with an error from that package I believe it's an error with this package and should be filed there. Before you file any issues there please ensure you are using the latest version of Atom since we have fixed some bugs for this in the 1.2X releases.

**Comment by Ben3eeE** [comment] 2018-09-21 19:55
To be able to move forward with this issue we are going to require some steps to reproduce the problem. Don't hesitate to reach out if you have steps to reproduce in a recent release of Atom.

**Comment by nickanna42** [comment] 2018-10-01 17:30
Same issue
[Enter steps to reproduce:]

1. Start atom

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:328

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:328:31)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:140:22)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:871:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:386:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:276:16)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1560:59)
```

### Commands

```
     -4:10.7.0 minimap:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-minify 0.8.0 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
hyperclick 0.1.5 
language-babel 2.85.0 
lint 0.0.1 
MavensMate-Atom 1.1.0 
minimap 4.29.9 
split-diff 1.5.2 
teletype 0.13.3 
```

**Comment by nickanna42** [comment] 2018-10-01 17:53
RTFM:
I closed all files in all open windows, closed all windows, ran `atom --clear-window-state`, and problem resolved itself

**Comment by Houley01** [comment] 2018-10-15 23:40
Was editing python file and came up with and error

C:\Users\username\AppData\Local\atom\app-1.31.2\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:328
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (C:\Users\username\AppData\Local\atom\app-1.31.2\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:328:31)
    at ScreenLineBuilder.buildScreenLines (C:\Users\username\AppData\Local\atom\app-1.31.2\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:140:22)
    at DisplayLayer.getScreenLines (C:\Users\username\AppData\Local\atom\app-1.31.2\resources\app\node_modules\text-buffer\lib\display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (C:\Users\username\AppData\Local\atom\app-1.31.2\resources\app\src\text-editor-component.js:871:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (C:\Users\username\AppData\Local\atom\app-1.31.2\resources\app\src\text-editor-component.js:386:16)
    at TextEditorComponent.updateSync (C:\Users\username\AppData\Local\atom\app-1.31.2\resources\app\src\text-editor-component.js:276:16)
    at etch.getScheduler.updateDocument (C:\Users\username\AppData\Local\atom\app-1.31.2\resources\app\src\text-editor-component.js:226:46)
    at ViewRegistry.performDocumentUpdate (C:\Users\username\AppData\Local\atom\app-1.31.2\resources\app\src\view-registry.js:238:13)

**Closed** 2018-10-19 21:16 UTC
Labels: more-information-needed, uncaught-exception
