### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 246Error: Cannot cal...

### ISSUE THREAD

**Issue by Ldthovn** [atom/atom#19943] opened 2019-09-23 04:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 246
Error: Cannot call function 'getPosition' on missing remote object 246
    at throwRPCError (/snap/atom/238/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/snap/atom/238/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/snap/atom/238/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /snap/atom/238/usr/share/atom/resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 246
Error: Cannot call function 'getPosition' on missing remote object 246
    at throwRPCError (/snap/atom/238/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/snap/atom/238/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/snap/atom/238/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/snap/atom/238/usr/share/atom/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/snap/atom/238/usr/share/atom/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/snap/atom/238/usr/share/atom/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/snap/atom/238/usr/share/atom/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:1:705395)
    at AtomEnvironment.storeWindowDimensions (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:1:705810)
    at WindowEventHandler.handleWindowBlur (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:285354)
```

### Commands

```
  2x -5:54.6.0 core:move-down (input.hidden-input)
  7x -5:54 core:move-left (input.hidden-input)
     -5:50.6.0 core:move-down (input.hidden-input)
  7x -5:50.4.0 core:move-left (input.hidden-input)
     -5:46.8.0 core:save (input.hidden-input)
 20x -5:14.6.0 core:backspace (input.hidden-input)
     -4:56.3.0 core:save (input.hidden-input)
  2x -4:06.0 core:move-left (input.hidden-input)
     -3:53.3.0 atom-beautify:beautify-editor (input.hidden-input)
  4x -3:52.7.0 core:save (input.hidden-input)
     -2:13.9.0 core:move-left (input.hidden-input)
     -2:12.7.0 core:backspace (input.hidden-input)
     -2:11 core:save (input.hidden-input)
     -1:50.5.0 core:undo (input.hidden-input)
  3x -1:49.1.0 core:copy (input.hidden-input)
     -0:29 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-jinja2 0.6.0 
autocomplete-python 1.16.0 
browser-plus 0.0.98 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.35 
git-plus 8.7.1 
kite 0.171.0 
minimap 4.29.9 
platformio-ide-terminal 2.9.4 
pp 0.0.1 
preview-plus 1.2.7 
script 3.18.1 
todo 0.6.0 
```

**Comment by rsese** [comment] 2019-09-30 20:11
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-09-30 20:11 UTC
