### ISSUE TITLE
Cursor position disappears when window loses focus

### ISSUE THREAD

**Issue by danielbarbarito** [atom/atom#3622] opened 2014-09-24 23:57 UTC
I'm on Ubuntu 14.04 and every time I alt+tab or make Atom lose focus in any way, the cursor position disappears.  I have to click on the window to make it reappear.

**Comment by puszczyk** [comment] 2015-01-04 00:11
@klaszlo @kevinsawicki  on xubuntu 12.04 I can reproduce it with alt + tab. To reproduce:
1. Use alt + tab to switch to next window
2. Use alt + tab to switch back to atom

Cursor is no longer there. If I start typing the letters appear, but the cursor is not there. The same with arrows. A "fix" is to click somewhere in the window or press ctrl + shift + p and then escape.

**Comment by LinuCC** [comment] 2015-01-10 03:27
same Problem.
Atom 0.169.0, Arch Linux + awesomewm
Any Function that changes the focused window will result in the Cursor disappearing.
Interesting to note: If atom regains focus, the cursor flashes for around 0.2s.
This is also the case when the cursor previously already disappeared. 
It always flashes up, then disappears.

**Comment by cmtonkinson** [comment] 2015-01-29 18:31
Reproduced with Atom 0.174.0 on Arch Linux.

**Comment by artiifix** [comment] 2015-02-08 17:39
I'm having the same issue (Atom `0.174.0` on Arch Linux with i3 WM `4.8`):
When Atom loses focus (I usually press a key combination to switch between windows) and I move the mouse afterwards, then when I switch back to Atom, the cursor disappears until I click the editor. But I can still move the cursor around using the keyboard.
The following workaround makes the cursor show even if Atom isn't focused (put it in your `styles.less`):
```less
atom-text-editor::shadow .cursor {
  opacity: 1;
}
```

**Comment by cmtonkinson** [comment] 2015-02-09 01:31
Nice workaround @artiifix. At least we've got a stop-gap until the underlying problem is addressed.

**Comment by muchweb** [comment] 2015-02-16 10:46
Related: https://github.com/atom/atom/issues/5318

**Comment by chrippa** [comment] 2015-02-21 12:14
@artiifix's workaround works great for the regular cursor, but this issue also causes vim-mode's command mode cursor to disappear. Here is a workaround for vim-mode aswell:

```less

atom-text-editor.vim-mode.command-mode,
atom-text-editor.vim-mode.operator-pending-mode,
atom-text-editor.vim-mode.visual-mode,
{
    &::shadow, &
    {
        .cursor, .cursor.blink-off {
            visibility: visible;
        }
    }
}
```

**Comment by deiwin** [comment] 2015-02-27 13:07
:+1: Have this on arch with i3wm as well.

Thanks @chrippa for the vim-mode workaround.

**Comment by benkaiser** [comment] 2015-03-24 04:17
Issue occurs for my on Arch with i3wm (using Alt as modkey).

The workaround from @artiifix works for the time being.

**Comment by yaph** [comment] 2015-03-26 09:37
Thanks @artiifix! This makes working with atom a lot better.

**Comment by arzeth** [comment] 2015-03-29 16:24
Thanks @artiifix !
I am on Arch Linux with i3 WM (version 4.8-168-gd5ec59e (2015-02-22)) too.

Also I use Atom Light theme. After window loses focusing, active line's background (yellow) is disappearing. So I fixed it with
```less
atom-text-editor::shadow {
    .line-number.cursor-line-no-selection,
    .line.cursor-line {
        background-color: rgba(255, 255, 134, 0.34);
    }
}
```
P.S. It is very stupid that the cursor is supposed to be seen only when window is focused, because developers often have more than one window at display and it is uncomfortable to switch between windows just to see which last line you have been editing.

**Comment by aksanoble** [comment] 2015-04-09 22:32
Facing the same issue. Cursor disappears when switching between work spaces.
 Atom 0.190.0 on Elementary Luna 
Version: 0.2.1 ( 32-bit ) based on Ubuntu 12.04

**Comment by wfayeBerman** [comment] 2015-05-12 12:36
This also happens on OS X Yosemite, but slightly different.

Steps to replicate:
- open 2 or more documents and you should now have multiple tabs
- click on a document and put your cursor on any random line (if you have a blank document that is fine)
- click on the tab that isn't currently active (at this point you'll notice there is no cursor)
- click back on the tab that is active (note that the cursor is now gone)

Ideal behavior:
- currently when the user uses the keyboard shortcut Command+1 (or +2, +3, etc) they go to that tab, and the cursor is there.  Ideally clicking on a tab would trigger the same behavior

**Comment by alpermat** [comment] 2015-05-20 08:47
Having the same issue here. Cursor disappears and atom seems to stay unfocussed after switching between applications / work spaces. However I can still type in the previously open document in Atom.

Atom 0.199.0
OSX Yosemite 10.10.3 (14D136)

Steps to replicate:
- Open atom and make it full screen
- Open another app (e.g., safari)
- While using atom for coding, use command+tab to switch from Atom to Safari
- Switch back to Atom by using command+tab.
- Cursor does not appear and most shortcuts (e.g., Command+P) does not work. Curiously, Command+O works.

**Comment by soulchainer** [comment] 2015-05-25 15:56
Same issue here. Cursor disappears when switching between tags (work spaces) or switching windows.
When this happen, you still can write in your current document, but (nobody has commented this before)  you can't write some special characters, like the chars `, ^ or ü (dieresis). If you try to write any of these (all of it characters normally combined with letters) all what you get is blank spaces. You still can write simple chars.

It happened to me where I was using Awesome WM and still happens to me now, using Qtile.
I'm using:
- Atom 0.201.0 in Antergos, (Arch Linux with nice gui installer) installed via AUR package [atom-editor](https://aur.archlinux.org/packages/atom-editor/).
- [Qtile](http://www.qtile.org/) , installed via AUR package [qtile-python3-git](https://aur.archlinux.org/packages/qtile-python3-git/).

@artiifix fix worked to me first time I switched between tags/windows and returned to Atom. And... no more. It's not working anymore. Don't ask me why.

**Comment by chrisfarms** [comment] 2015-06-26 23:42
This has been driving me nuts and I'd hoped would be sorted in Atom 1.0 ... here's a slight tweak of the previous rules combined that sweeps the issue under the rub for now (with static cursor).

```
/* fix for https://github.com/atom/atom/issues/3622 */
atom-text-editor:not(.mini)::shadow,
atom-text-editor:not(.mini)::shadow .blink-off,
atom-text-editor.vim-mode.command-mode,
atom-text-editor.vim-mode.operator-pending-mode,
atom-text-editor.vim-mode.visual-mode,
.editor.is-focused,
.editor:not(.is-focused),
{
  .cursor, .cursor.blink-off {
    visibility: visible !important;
    opacity: 1 !important;
  }
}
```

**Comment by MarkOSullivan94** [comment] 2015-07-08 18:31
Having this issue with Xubuntu 14.04

**Comment by Rush** [comment] 2015-08-08 21:13
Having this issue on openSUSE 13.2, KDE, Plasma 5

**Comment by ciroreed** [comment] 2015-08-18 16:53
Same issue on Debian Wheezy

Linux debian-ivan 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u2 x86_64 GNU/Linux

**Comment by diggit** [comment] 2015-08-18 17:47
It is pretty obvious guys. This bug is not platform, kernel nor distro dependent. There is no need to report such info.

**Comment by djbusby** [comment] 2015-08-31 22:25
Thank you @chrisfarms works perfect in Atom v1.0.7, multiple platforms (obviously)

**Comment by soulchainer** [comment] 2015-09-26 11:02
I just wanted to say that I don't know what you did guys, but I think you solved this bug. At least for me.
I mean, I didn't saw anything in your last updates (from 1.0.15 to 1.0.18) talking about you solving this problem, but, for me, you really do.
Now, **at least** it's solved. At least for me. The rest of the people, say something. I hope it's also gone for you.

I'm so happy, because this was a long, **long** running bug (from Atom 0.201.0 for me), I even believe it will never get fixed. 
But here we are, **finally**. Now using Atom is a more satisfactory experience.

I am still using it with:

- Antergos, (Arch Linux with nice gui installer).
- [Qtile](http://www.qtile.org/) , installed via AUR package [qtile-python3-git](https://aur.archlinux.org/packages/qtile-python3-git/).

**Comment by dustywilson** [comment] 2015-09-27 10:44
At the risk of piling on the me-toos, me too.  Some update in the recent past has fixed this issue for me, just as reported by @soulchainer above.  I had been using the stylesheet workaround for this issue, so I didn't notice.  I removed that workaround and it seems to be working fine.  I've been using it without the workaround for the last several hours with no issue, where before it was easy to reproduce.  I'm running Debian Linux (Jessie), not that the platform seems to matter on this issue.

**Comment by alexandernst** [comment] 2015-09-27 10:46
Not fixed for me, Debian Jessie and Gnome shell here.

**Comment by alexandernst** [comment] 2015-09-27 10:47
Oh, I'm sorry, I got confused by another bug that I'm also susbrited too. Indeed this is fixed on 1.0.19.

**Comment by izuzak** [comment] 2015-09-27 10:58
Thanks for letting us know, @soulchainer @dustywilson @alexandernst  -- happy to hear this was fixed for you (possibly by some recent Electron upgrades? Not really sure myself, I don't remember seeing discussions about this problem specifically). If someone can still reproduce the issue in Atom 1.0.19 -- let us know.

**Closed by izuzak** 2015-09-27 10:58 UTC
Labels: bug, linux

**Comment by rohan-deshpande** [comment] 2015-10-12 23:43
Never noticed this on Mac, but have recently had to use Windows 7 and am noticing this happening still on 1.0.19.

**Comment by izuzak** [comment] 2015-10-13 06:12
@rohan-deshpande Could I trouble you to record a GIF which clearly demonstrates the problem on Windows? Just to make sure this is the same issue. Thanks.

**Comment by rohan-deshpande** [comment] 2015-10-15 00:38
Heya will do, but just FYI alt tabbing back and forth seems to fix it so I'm guessing it's the same issue

**Comment by skamansam** [comment] 2015-10-16 02:51
I am having the same issue, for Atom 1.0.19. I am running GNOME Shell 3.16.3 on Fedora 22, with an Intel HD 3000 integrated GPU. Here is a gif screencapture. 
![atom_cursor](https://cloud.githubusercontent.com/assets/102971/10532688/3215bcda-738f-11e5-8cf1-14811583ebbf.gif)

**Comment by chok** [comment] 2015-10-20 15:09
Same problem with yakuake. I have to loose the focus on atom then the cursor come back.

**Comment by kubapok** [comment] 2015-10-29 21:11
The problem disappeared for me after upgrading to 1.0.19. I use mate.

**Comment by NKjoep** [comment] 2015-10-30 09:06
I had the same problem with Atom 1.1.0 under Windows, but I discovered that was the **synced-sidebar** 0.4.2 that was moving the focus to the tree view.

In fact after doing alt+tab or ctrl+pgup/down the focus was lost, trying to type something it asked to duplicate the file (wat?)... 
then I tried to disable **synced-sidebar** and the focus worked again.

**Comment by diggit** [comment] 2015-10-30 09:18
@NKjoep Issue resolved here was different. When atom lost focus by switching to another window, cursor disappeared, but typing was still possible. I have no **synced-sidebar** installed and this issue affected me. If your issue persists, you should report it to proper [bug tracker](https://github.com/peterdotjs/atom-synced-sidebar/issues).

**Comment by NKjoep** [comment] 2015-10-30 09:20
Yes @diggit, thank you :+1:
