### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/nelsonparreira/Downloads/Atom.app'

### ISSUE THREAD

**Issue by nelsonparreira** [atom/atom#10842] opened 2016-02-16 17:35 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/nelsonparreira/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/nelsonparreira/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/nelsonparreira/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -0:00.3.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joshaber** [comment] 2016-02-16 17:37
This is a duplicate of https://github.com/atom/atom/issues/10774. Feel free to subscribe over there for updates.

**Closed by joshaber** 2016-02-16 17:37 UTC
