### ISSUE TITLE
Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog'    at Function.Module._resolveFilename (module.js:351:15)    at Function.Module._load (module.js:293:25)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/Users/cesar/Downloads/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/Users/cesar/Downloads/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

### ISSUE THREAD

**Issue by nataren** [atom/atom#6044] opened 2015-03-19 22:31 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Users/cesar/Downloads/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Users/cesar/Downloads/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /Users/cesar/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77

Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Users/cesar/Downloads/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Users/cesar/Downloads/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
  at metaToValue (/Users/cesar/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77:15)
  at Object.exports.require (/Users/cesar/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:157:34)
  at Atom.module.exports.Atom.showSaveDialogSync (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/src/atom.js:843:23)
  at Pane.module.exports.Pane.saveItemAs (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/src/pane.js:560:26)
  at Pane.module.exports.Pane.saveItem (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/src/pane.js:550:21)
  at Pane.module.exports.Pane.saveActiveItem (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/src/pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/src/workspace.js:689:35)
  at atom-workspace.atom.commands.add.core:save (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Users/cesar/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/cesar/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:02.7 application:new-file (atom-text-editor.editor)
     -0:01.6 core:paste (atom-text-editor.editor.is-focused)
     -0:00.7 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "softWrapAtPreferredLineLength": true,
    "invisibles": {},
    "fontSize": 21
  }
}
```

### Installed Packages

```coffee
# User
ide-haskell, v0.1.1
language-haskell, v0.4.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-20 11:50
Duplicate of atom/tree-view#399, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-20 11:50 UTC
