### ISSUE TITLE
Uncaught Error: EACCES: permission denied, unlink '/home/mypc/.config/Atom/Cache/settings-view/atom-1475322816791'

### ISSUE THREAD

**Issue by marcelojr92** [atom/atom#12840] opened 2016-10-01 12:03 UTC
Why this appearing when I go into settings?

> Error: EACCES: permission denied, unlink '/home/mypc/.config/Atom/Cache/settings-view/atom-1475322816791'
>     at Error (native)
>     at Object.fs.unlinkSync (fs.js:990:18)
>     at WriteStream.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/atom-io-client.js:221:18)
>     at emitOne (events.js:95:20)
>     at WriteStream.emit (events.js:182:7)
>     at WriteStream.<anonymous> (fs.js:1933:12)
>     at FSReqWrap.oncomplete (fs.js:82:15)

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

**Comment by iDhruv22** [comment] 2016-10-17 06:35
same issue, while updating one of plugin.

**Comment by Ben3eeE** [comment] 2016-10-17 06:45
This is a duplicate of https://github.com/atom/settings-view/issues/850.

**Closed by Ben3eeE** 2016-10-17 06:45 UTC
