### ISSUE TITLE
Can't open Settings | Uncaught Error: ENOENT: no such file or directory, lstat [...]com.github.atom.ShipIt/update.p7CWNRM

### ISSUE THREAD

**Issue by luckydonald** [atom/atom#9745] opened 2015-11-22 13:36 UTC
[Enter steps to reproduce below:]

1. Going to the settings via ```cmd```+```,```, or use the menu ```Atom```>```Preferences...```
2. The error appears, no settings get opened.

Also, I feel unhappy about my user name in log files. Maybe you could just use ```~/``` in paths instead?

**Atom Version**: 1.2.3
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/{username}/Library/Application Support/com.github.atom.ShipIt/update.p7CWNRM'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/{username}/Library/Application Support/com.github.atom.ShipIt/update.p7CWNRM'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/{username}/Library/Application Support/com.github.atom.ShipIt/update.p7CWNRM/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
  2x -0:08.4.0 settings-view:open (atom-text-editor.editor.is-focused)
```
(Crashed the first time ```cmd```+```,``` too. This is the log for the second try. Thus ```2x```)

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "duplicate-line-or-selection"
    ],
    "disabledPackages": [
      "block-selection-mode"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by luckydonald** [comment] 2015-11-22 13:44
Edit: I somehow also have a Atom v1.2.2 here too, which is working fine.

**Comment by luckydonald** [comment] 2015-11-22 13:50
This is how I opened it:
![opening atom](https://cloud.githubusercontent.com/assets/2737108/11324105/9da9b09a-9127-11e5-9eca-a309953c8d36.png)

I noticed I have 2 Atoms in my dock now. The not working one isn't the one I am normally using.
 
Also, after selecting "keep it in Dock" the icon became blank:

![blank icon](https://cloud.githubusercontent.com/assets/2737108/11324112/03ce1ff0-9128-11e5-8fa0-874c09fbfc25.png)

**Comment by luckydonald** [comment] 2015-11-22 13:51
Further investigation shows, that the path of the broken Atom is ```/Users/{username}/Library/Application\ Support/com.github.atom.ShipIt/update.p7CWNRM/Atom.app```

**Comment by luckydonald** [comment] 2015-11-22 13:56
Now, if I try opening it via Finder again, Finder says 'Couldn't find Application' (in German)

**Comment by 50Wliu** [comment] 2015-11-22 16:08
@luckydonald This is a duplicate of #9559 and #7339 actually (the issue reporter didn't recognize that because of the different usernames and shipit folders).

Can you please report your findings over to #7339 please?  Thanks!

(I'll also create a new issue over at [atom/notifications] to track removing usernames from issues)

**Closed by 50Wliu** 2015-11-22 16:08 UTC
