### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.29.0\res...

### ISSUE THREAD

**Issue by a-hulman** [atom/atom#17809] opened 2018-08-09 08:59 UTC
Hello,
today I opened atom to edit a php file as usual, but the error appeared. Any keypress triggers another error window. ANY file produces the same error .

Thank you for any ideas before I reinstall :)

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Lenovo\AppData\Local\atom\app-1.29.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:172

Error: The specified module could not be found.
\\?\C:\Users\Lenovo\AppData\Local\atom\app-1.29.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.29.0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.29.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
```

### Non-Core Packages

```
Atom-Latte-lang-Highlighting 0.4.0 
color-picker 2.3.0 
convert-file-encoding 0.1.0 
ctrl-dir-scroll 0.2.5 
duplicate-removal 0.1.3 
highlight-selected 0.14.0 
language-latte 0.4.0 
sequential-number 0.5.0 
xml-tools 0.2.1 
```

**Comment by rsese** [comment] 2018-08-09 17:47
Thanks for contributing!

We noticed that this looks like a duplicate of #14461 so you can subscribe there for updates if you'd like.

> Thank you for any ideas before I reinstall :)

We don't have steps to reproduce yet so we would recommend reinstalling.  If you still have the same issue after reinstalling, if you have an anti-virus program running you can try temporarily disabling it and then try reinstalling again.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-08-09 17:47 UTC

**Comment by a-hulman** [comment] 2018-08-09 18:26
Hello rsese,
thank you for the reference to root issue. After reading through, I can tell that the problem must be from update as the node_modules folder differs from previous version 1.28.2 to 1.29.0:
https://i.imgur.com/JsXEH9h.png
Actually the resource folder lacks a lot of folders on all levels in the updated app.

The error was fixed by installing atom again(even without reinstall) as the missing folders were inserted/restored.

**Comment by asdf23** [comment] 2018-08-28 21:07
Duplicate of https://github.com/atom/atom/issues/14461 ?
Atom is completely broken ATM

**Comment by asdf23** [comment] 2018-08-28 21:09
I was able to resolve it by copying keyboard__layout from a different version (app-1.28)
