### ISSUE TITLE
Failed to load the settings-view package

### ISSUE THREAD

**Issue by cbwiedel** [atom/atom#9635] opened 2015-11-16 19:11 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the settings-view package

```
At ENOENT: no such file or directory, lstat '/Users/calebwiedel/Library/Application Support/com.github.atom.ShipIt/update.yYKoEIv'

Error: ENOENT: no such file or directory, lstat '/Users/calebwiedel/Library/Application Support/com.github.atom.ShipIt/update.yYKoEIv'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/calebwiedel/Library/Application Support/com.github.atom.ShipIt/update.yYKoEIv/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "softWrap": true,
    "tabLength": 3,
    "softWrapHangingIndent": 2,
    "fontFamily": "Hack"
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by cbwiedel** [comment] 2015-11-16 19:11
It might have to do with having Atom 1.1 open, then opening a new file in Atom 1.2

**Comment by 50Wliu** [comment] 2015-11-16 21:17
Duplicate of #9559 and #7399, please subscribe there for updates.

@cbwiedel can you please post your findings over to #7399?  Thanks.

**Closed by 50Wliu** 2015-11-16 21:17 UTC
