### ISSUE TITLE
Package update release notes information

### ISSUE THREAD

**Issue by montogeek** [atom/atom#10281] opened 2016-01-05 09:48 UTC
Hi!

I would like to propose a new _feature_ regarding a package update process:
Currently when an package update is available Atom does not show what exactly changed, I have plenty of packages installed and no one provides a clear changelog that you can see in the 'Available Updates' page.

It would be great to display the release notes of the packages when you click the package name in the 'Available Updates' page. I guess we need to introduce to the community an official way to do it.

Thanks!

**Comment by mnquintana** [comment] 2016-01-05 14:12
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/settings-view/issues/282 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-05 14:12 UTC

**Comment by montogeek** [comment] 2016-01-05 14:16
Thank you!
