### ISSUE TITLE
performing right-click rename from tab of non-focused file targets focused file instead

### ISSUE THREAD

**Issue by gudatcomputers** [atom/atom#16586] opened 2018-01-18 13:43 UTC
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

While 2 files are open in a split window configuration, with one file in focus, directly right click on the other tab and select Rename, Reveal in Tree View, or Show in Finder.  The selected action will target the file in focus rather than the one from which you activated the context menu. 

### Steps to Reproduce

1. open a file 
2. split (right || left || up || down)
3. open a second file in the split
4. with the second file in focus in the split, right click on the first file tab and select Rename, Reveal in Tree View, or Show in Finder

**Expected behavior:** The selected action targets the file on whose tab you clicked

**Actual behavior:** The selected action targets the file whose editor is in focus

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.8.2

macOS 10.12.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-01-18 21:09
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13617. You may want to subscribe there for updates - I'll go ahead and note in there that it's not just renames that are affected.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-01-18 21:09 UTC

**Comment by gudatcomputers** [comment] 2018-01-18 21:11
thanks @rsese.  Tried to search to find duplicates.  Wasn't sure how to search it properly.  Will subscribe on that issue.

**Comment by rsese** [comment] 2018-01-18 21:16
No problem @gudatcomputers, it took me a bit to find it, we have quite a few issues!  Thanks again for reporting :v:
