### ISSUE TITLE
Selections do not always disappear immediately, causing overwrites.

### ISSUE THREAD

**Issue by BrandonDusseau** [atom/atom#2454] opened 2014-05-30 15:06 UTC
Occasionally when selecting text and typing over it, the selection remains and selects the next text of the same length (or sometimes one character). Because of this, typing over a selection causes the original text AND the new selection to be overwritten. In the case that the selection is replaced by the one character selection, typing continually replaces the same character until a delay in typing occurs.

The expected behavior is that the selection and selected text both disappear immediately when beginning to type.

Using Atom 0.99 on OS X 10.9.3

**Comment by izuzak** [comment] 2015-02-13 16:56
This is still reproducible. Definitely not a priority, but just wondering if it might be a :bug: we could :hammer: more easily now? /cc @nathansobo @benogle

**Comment by nathansobo** [comment] 2015-02-13 17:53
Probably just as easy to fix. We just need to prioritize it.

**Comment by iclanzan** [comment] 2015-05-05 18:34
This is still happening in v0.196.0 and is quite annoying.

**Comment by gerwitz** [comment] 2015-05-11 08:37
+1

I'm also suffering from this and have been struggling mightily to narrow down the conditions under which it occurs. It still feels very random.

**Comment by izuzak** [comment] 2015-09-14 09:48
I believe this was fixed by https://github.com/atom/atom/pull/8446 and https://github.com/atom/atom/pull/8627. If anyone can still reproduce this in Atom 1.0.11 -- please let us know. :v:

**Closed by izuzak** 2015-09-14 09:48 UTC
Labels: atom, bug, editor-rendering

**Comment by nathansobo** [comment] 2015-09-14 15:28
There is one remaining corner related to commands that modify selections. Waiting for the removal of jQuery to be merged before fixing it.

**Comment by izuzak** [comment] 2015-09-14 15:36
> There is one remaining corner related to commands that modify selections. 

Thanks, @nathansobo :bow: Do we have a separate issue tracking that problem or was it described in this issue somewhere and I missed it? And just to make sure I understand -- which commands are you referring to (an example maybe)?

**Comment by nathansobo** [comment] 2015-09-14 18:08
> Thanks, @nathansobo :bow: Do we have a separate issue tracking that problem

I can't remember... I somehow crossed my stream of consciousness but I don't recall how.

> And just to make sure I understand -- which commands are you referring to (an example maybe)?

If you drag a selection and then quickly hit `cmd-g` to select the next find-and-replace result, the selection can contain both because we haven't seen the `mouseup` event yet due to Yosemite's weird delay. So we need to terminate the drag on any command being dispatched, but there were jQuery shims getting in the way of doing that a couple weeks ago so I opted to rip it out first.

**Comment by coreyk** [comment] 2017-08-30 18:41
I'm still definitely seeing this with three finger drag on Atom 1.19.3 on Mac OS X Sierra using either the built in trackpad or a Magic Trackpad.

**Comment by Ben3eeE** [comment] 2017-08-30 19:00
@coreyk This is a regression in Atom 1.19 that we fixed in Atom 1.19.4 /cc: https://github.com/atom/atom/pull/15407
