### ISSUE TITLE
After Save-As, hover over tab shows old filename

### ISSUE THREAD

**Issue by szabgab** [atom/atom#7719] opened 2015-07-05 10:24 UTC
I had a file open. Used Save-As to save with a different name.
Then put to mouse over the title of the buffer at the top of the window and the blue pop-out was still showing the name of the original file. (The filename written on the title is correct.)
Seen in Atom 1.0.0 using OSX.

**Comment by batjko** [comment] 2015-07-05 10:26
Looks like this behavior has already been reported on the tabs package's repo:
https://github.com/atom/tabs/issues/189

**Comment by mnquintana** [comment] 2015-07-05 11:58
@szabgab This looks like a duplicate of https://github.com/atom/tabs/issues/189 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-05 11:58 UTC

**Comment by szabgab** [comment] 2015-07-05 13:13
:+1:
