### ISSUE TITLE
'Check for Updates' button shows on 'Deprecation Cop' window

### ISSUE THREAD

**Issue by emcek** [atom/atom#7865] opened 2015-07-13 11:02 UTC
![image](https://cloud.githubusercontent.com/assets/475312/8648243/57095aee-295f-11e5-86dd-bbd8f3cd7324.png)

**Comment by kubetz** [comment] 2015-07-13 12:00
Can you create the issue in https://github.com/atom/deprecation-cop and close it here?

Also this seems to be a feature not a bug (see https://github.com/atom/deprecation-cop/commit/01459698b21f1c6da8536de74ebf3dc9c155e499) however the button looks bit off.

**Comment by mnquintana** [comment] 2015-07-13 12:03
Thanks @kubetz! Please reopen this on https://github.com/atom/deprecation-cop.

**Closed by mnquintana** 2015-07-13 12:03 UTC
