### ISSUE TITLE
Splitting Project pane removes it and all other panes

### ISSUE THREAD

**Issue by onelivesleft** [atom/atom#15436] opened 2017-08-24 15:37 UTC
### Description

I wanted to have two Project panels, and thought maybe that functionality was present simply by Splitting the one I had... not so much! My project panel disappeared entirely, and could not be opened again via the menu, nor could any other panel (command palette, git tab etc).  Atom did report an error about only one such object being allowed, but that didn't bring it back, neither did restarting.  Performing a ```atom --clear-window-state``` fixed it and got my atom back in a functional state.

### Steps to Reproduce

1. Right-click Project tab and pick a Split option

**Expected behavior:** 

Thought nothing would happen or I'd get two Project panes

**Actual behavior:** [What actually happens]

As described above: atom rendered unusable.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% I assume

### Versions

```
λ atom --version

Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

λ apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.6
git 2.13.3.windows.1
visual studio 2015

**Comment by rsese** [comment] 2017-08-28 21:28
Thanks for the report!  I was able to reproduce and the error pointed to https://github.com/atom/tabs/issues/234 - I assume that happened to you as well or at least the stack trace was similar?  Someone mentioned the same repro steps as well /cc https://github.com/atom/tabs/issues/234#issuecomment-306439035.

I'll go ahead and close as a duplicate for now and I'll bring that one up with the team.

---

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/234. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-28 21:28 UTC
