### ISSUE TITLE
Uncaught Error: spawn /Users/kraft/Library/Application Support/com.github.atom.ShipIt/update.x5tO...

### ISSUE THREAD

**Issue by kraftbj** [atom/atom#8346] opened 2015-08-12 16:49 UTC
1. Open app.

I had just opened it via the context menu in Finder, which opened fine with an existing workspace of files from another project. I closed all tabs, then exit (so I could reopen and have the project files available). The second open led to the error.

**Atom Version**: 1.0.6
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/kraft/Library/Application Support/com.github.atom.ShipIt/update.x5tOpGL/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/kraft/Library/Application Support/com.github.atom.ShipIt/update.x5tOpGL/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:734:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
    at child_process.js:1127:20
    at process._tickCallback (node.js:357:13)
    at EventEmitter.ipc.sendSync (/Users/kraft/Library/Application Support/com.github.atom.ShipIt/update.x5tOpGL/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getPosition] (/Users/kraft/Library/Application Support/com.github.atom.ShipIt/update.x5tOpGL/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
    at Atom.module.exports.Atom.getWindowDimensions (/Users/kraft/Library/Application Support/com.github.atom.ShipIt/update.x5tOpGL/Atom.app/Contents/Resources/app.asar/src/atom.js:558:29)
    at Atom.module.exports.Atom.storeDefaultWindowDimensions (/Users/kraft/Library/Application Support/com.github.atom.ShipIt/update.x5tOpGL/Atom.app/Contents/Resources/app.asar/src/atom.js:591:25)
    at /Users/kraft/Library/Application Support/com.github.atom.ShipIt/update.x5tOpGL/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:104:21
    at handler (/Users/kraft/Library/Application Support/com.github.atom.ShipIt/update.x5tOpGL/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:115:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  },
  "editor": {
    "fontSize": 16,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-13 21:26
Closing as a duplicate of #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-13 21:26 UTC
Labels: uncaught-exception
