### ISSUE TITLE
First context menu to be opened after Atom starts closes on its own

### ISSUE THREAD

**Issue by kaiyoma** [atom/atom#19308] opened 2019-05-12 01:02 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The first context menu to be opened after Atom starts closes on its own.

### Steps to Reproduce

1. Open Atom.
2. Right-click (either inside the editor or on an open file tab) to open the context menu.
3. Wait without clicking anything.

**Expected behavior:** [What you expect to happen]
Nothing.

**Actual behavior:** [What actually happens]
The context menu closes on its own after a few seconds.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Only the first context menu opened after a fresh start of Atom. Happens 100% of the time in that scenario.

### Versions

This is happening in Atom on Windows 10.

```
$ atom --version

Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by 50Wliu** [comment] 2019-05-12 01:36
Can confirm on Windows 10 x64. This is weird.

**Comment by rafeca** [comment] 2019-05-27 15:38
After reproducing this issue on OSX, I've done quite a long investigation but unfortunately I haven't been able to find the root cause of this issue.

I can say that this is not something that's been caused by some JavaScript logic in Atom, but looks like a deeper issue related to Electron (and possibly the Atom snapshots).

The reason why I think so it's because I've even been able to reproduce this issue without opening even an Atom window I can reproduce the issue.

What I've done is to replace the [`main.js`](https://github.com/atom/atom/blob/master/src/main-process/main.js) by [this minimal one](https://gist.github.com/rafeca/d7731f6315c3b1127c3749b0a1c5f89b), which basically only opens an electron window with an empty html page and a context menu.

When I use this file against a standard pre-built Atom version I can reproduce the issue (the context menu disappears after 7-8 seconds), but if I use a similar file on the [`electron-quick-start` project](https://github.com/electron/electron-quick-start) or on an Atom app prebuilt without snapshots, I cannot reproduce the issue.

It's very puzzling

**Comment by darangi** [comment] 2021-02-02 18:59
This issue no longer exist in the lastest version of atom, I will go ahead and close this

**Closed by darangi** 2021-02-02 18:59 UTC
Labels: d ⬆️, electron, i ⬇️, triaged, v ⬆️
