### ISSUE TITLE
Show closing brace/tag when folding code blocks for clarity

### ISSUE THREAD

**Issue by aaronbushnell** [atom/atom#11179] opened 2016-03-17 02:02 UTC
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

[Per some discussion on the Atom boards](https://discuss.atom.io/t/code-folding-close-bracket/9997) there's some concession that folded blocks of code can often be difficult to parse and work around.

Here are some examples of the current behavior and a suggested change to make the fold easier to parse.

``` js
// Example code
function () {
  console.log('Hello world.');
  console.log('How are you today?');
}

/*
 * How Atom currently handles folds within a given syntax
 */
// Folding the function - Atom (JavaScript syntax)
function () {...

/*
 * What I expect to happen to happen in a given syntax
 */
// Folding the function - Atom (Plain Text syntax)
function () {
}

// Folding the function - Sublime Text
function () {
}

// A one-line variation
function () {..}
```

And another example using HTML

``` html
<!-- Example code -->
<section>
  <p>Hello world.</p>
</section>

<!--
 How Atom currently handles folds within a given syntax
 -->
<!-- Folding the block - Atom (HTML syntax) -->
<section>...

<!--
 What I expect to happen to happen in a given syntax
 -->
<!-- Folding the block - Atom (Plain Text syntax) -->
<section>
</section>

<!-- Folding the block - Sublime Text -->
<section>
</section>

<!-- A one-line variation -->
<section>...</section>
```

The `Atom (Plain Text syntax)` and `Sublime Text` format is easier to parse because it's clear where the function/block starts and stops. It also makes wrapping a folded block with more code easier because you can see the beginning and end of the full statement.

The other problem with the current Atom folding method is indenting a folded function does not work properly.

**JavaScript Example**:
![Indenting folded JavaScript in Atom](https://zippy.gfycat.com/ExcellentMerryCoyote.gif)

**HTML Example**:
![Indenting folded HTML in Atom](https://zippy.gfycat.com/FarTenseAdeliepenguin.gif)

@lee-dohm suggested I provide some examples of other folds besides just the [1TBS](https://en.wikipedia.org/wiki/Indent_style#Variant:_1TBS) style. I've noted some proposals:

**Stroustrup**:

``` c++
// Example
class Vector { 
  public:
      Vector(int s) :elem(new double[s]), sz(s) { }
      double& operator[](int i) { return elem[i]; }
      int size() { return sz; } 
  private:
      double elem[lowast];
      int sz;
};

// Expected
class Vector {
  public:...
  private:...
}
```

**Allman**:

``` js
// Example
while (x == y)
{
  something();
  somethingelse();
}

// Expected
while (x == y)
{
}
```
### Steps to Reproduce
1. Launch Atom
2. In the correct syntax (not just "Plain Text"), write a multiline, indented function/block
3. Collapse block
4. (To replicate indentation issue) Indent the folded, one-line block
### Versions

**Atom**: 1.5.4
**apm**: 1.6.0

**Comment by curtisblackwell** [comment] 2016-03-17 05:27
I tried using code folding, but it was just confusing w/o seeing the closing brace, so I just don't use it in Atom.

**Comment by trangiiee** [comment] 2016-03-17 14:57
+1

**Comment by Nokel81** [comment] 2016-03-18 18:41
This is also a VERY BIG problem with if statements


`if (true) {`
`    var x = 0;`
`} else {`
`        `
`}`

Having the above as a statement and folding on the if (this is in javascript) code folds it to:

`if (true) {...`
``
`}`

The `else` has been completely removed

**Comment by aaronbushnell** [comment] 2016-03-18 19:02
Good catch, @Nokel81! 

Just to demonstrate, here's how Atom folds this in the JavaScript syntax:
![Folding a conditional under the JS syntax in Atom](https://zippy.gfycat.com/CompleteIdleCanary.gif)

And this is my expectation of how it should work instead (using the Plain Text syntax):
![Folding a conditional under the Plain Text syntax in Atom](https://zippy.gfycat.com/HarmoniousDelightfulHake.gif)

**Comment by infogulch** [comment] 2016-04-06 03:00
I like the idea of appending the rest of the line to the end of the folded replacement. As in, `if (true) { \n a=b; }` -> `if { .. }`. But this becomes messy in some cases with `else` etc. Proposal:

Append the block close line only if it's the last character on the line (with some exceptions), otherwise leave it on its' own line. Exceptions would include allowing some specific characters after the block close character, like `,` and `;` (language-dependent).

```javascript
if (true) {
  a=b;
}
// becomes
if (true) { .. }


if (true) {
  a=b;
} else {
  a=c;
}
// becomes
if (true) { ..
} else {
  a=c
}
// or...
if (true) { ..
} else { .. }


// example of an exception (note mismatched formatting):
[
  function() {
    return "a"
  },
  function() {
    return "b"
  }]
// becomes
[
  function() { .. },   // the ',' character is allowed to be appended with the '}'
  function() {
    return "b"
  }]
// but the last function() would not fold the ending ], because the matching } is not the last character on the line:
[
  function() { .. },
  function() { ..
  }]
```

This logic seems to solve many of the possible problems: unmatched brackets, unseen separators, disappearing else statements. And it's still sane with different bracket placement styles:

```javascript
// Stroustrup
if (x < 0) { .. }
else { .. }

// OTBS
if (x < 0) { ..
} else { .. }

// Allman
if (x < 0)
{ .. }
else
{ .. }
```

**Comment by Nokel81** [comment] 2016-04-06 12:07
@infogulch I think that (in Javascript or other C like languages), that semicolons should be ignored for the cold folding.
`var fn = function(x) {`
    `console.log(x);`
`};`
should fold to:
`var fn = function(x) { .. };`
not:
`var fn = function(x) { ..`
`};`

**Comment by aaronbushnell** [comment] 2016-04-06 12:42
Like the ideas @infogulch and @Nokel81! Though my concern with this type of folding is it seems like there are many rules and exceptions that drive the folding logic. It might take me a moment or two to process how and why the code folded in the way that it did versus it consistently folding due to indentation.

Many times when I fold my code it's to quickly wrap a large block with an HTML tag, CSS selector or a JS conditional. I'd prefer something solely indentation based so my expectations are always the same when I fold a block.

That said — what might be _ideal_ is if the folding functionality was a true plugin like the other components of Atom. Perhaps the folding style could be handled through a settings area or something?

**Comment by Nokel81** [comment] 2016-04-06 13:32
@aaronbushnell I however see a problem with just doing the tab level of code.
`/**`
` * This function is used to update an object in the database`
` */`
`_.update = function(req, res, next) {`
`    //the function`
`};`

Would this collapse (if you wanted to collapse the comment) to
`/**`
`...`
`_.update = function(req, res, next) {`
`    //the function`
`};`
or
`/**`
`...`
`};`

Since the function line is the last line before the next level of tabs (but those should really be also folded) to the last one which is even worse then what we have know.

**Comment by aaronbushnell** [comment] 2016-04-06 13:45
Hey @Nokel81, I'm having a hard time reading through that example because it appears as if you are using the inline code syntax instead of block style. Do you mind wrapping your example using the block style found in the [GitHub Flavored Markdown guide](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)?

I made a GIF of how Sublime handles this situation. I agree that the commenting folds a bit strangely, but the code itself folds as I expect it to:

![Folding a block of JavaScript in Sublime](https://zippy.gfycat.com/ImpracticalRaggedGourami.gif)

**Comment by Nokel81** [comment] 2016-04-06 13:52
Sorry about the styling.
    /**
     * This function is used to update an object in the database
     */
    _.update = function(req, res, next) {
        //the function
    };

    /**
    ...
     _.update = function(req, res, next) {
        //the function
    };

    /**
    ...
    };

What I was noticing that we would not be able to just do pure tab layering because the function is on the same vertical line as the comment. I think that the comment should fold similar to the function in that GIF of yours.I think that sort of folding is good

**Comment by curtisblackwell** [comment] 2016-04-06 20:14
Indentation-based collapsing sounds problematic for some coding styles. Especially since most languages don't care about whitespace.

Here's how I format ternary conditions when it doesn't fit on one line.

```js
var someVar = (whatever === insertSomeLongConditionalHereDidIMentionIWrapAtOneHundredChars)
  ? 'some value'
  : someVar;
```

I don't see how anything other than regexes would work properly. It could collapse based on the bracket at the end of the line you're starting on. Anything between it and the closing bracket would be collapsed with whatever exceptions you might want (like not hiding comments).

**Comment by aaronbushnell** [comment] 2016-04-06 20:24
@curtisblackwell I _think_ that's how Sublime handles the folding in that case, too. Is this what your expectation is if you were to fold that block?

```js
// Full block
var someVar = whatever === insertSomeLongConditionalHereDidIMentionIWrapAtOneHundredChars
  ? 'some value'
  : someVar;

// Folded block
var someVar = whatever === insertSomeLongConditionalHereDidIMentionIWrapAtOneHundredChars[...];
```

**Comment by curtisblackwell** [comment] 2016-04-06 20:40
I'm didn't have an expectation for it, and probably wouldn't even fold it; it's only three lines. It was just the first potentially-problematic-for-indentation-based code folding to come to mind. However, your suggestion looks good to me.

A switch statement in PHP might be a better example:

```php
switch ($i) {
    case 0:
        echo "i equals 0";
        break;
    case 1:
        echo "i equals 1";
        break;
    case 2:
        echo "i equals 2";
        break;
}
```

If I had a longer result for a case, I might fold it. I'd want to see something along the lines of:


```php
switch ($i) {
    case 0: …
    case 1:
        echo "i equals 1";
        break;
    case 2:
        echo "i equals 2";
        break;
}
```

Indentation-based might end up doing something weird like this, depending on settings.

```php
switch ($i) {
    case 0: … case 1:
        echo "i equals 1";
        break;
    case 2:
        echo "i equals 2";
        break;
}
```

**Comment by aaronbushnell** [comment] 2016-04-07 01:26
@curtisblackwell When I think "indentation-based", I think the fold would work exactly like this example you provided:

```js
switch ($i) {
    case 0: …
    case 1:
        echo "i equals 1";
        break;
    case 2:
        echo "i equals 2";
        break;
}
```

Not something like this:
```js
switch ($i) {
    case 0: … case 1:
        echo "i equals 1";
        break;
    case 2:
        echo "i equals 2";
        break;
}
```

Because the fold would collapse anything indented within. Here's a gif of how Sublime tackles this:
![Folding a switch statement in Sublime](https://zippy.gfycat.com/SeparateAgileKawala.gif)

Here's how Atom handles it. It's mostly the same, but I'd like to see the closing brace on the `switch` statement like Sublime shows.
![Folding a switch statement in Atom](https://zippy.gfycat.com/AnimatedSnoopyColt.gif)

**Comment by curtisblackwell** [comment] 2016-04-07 01:58
@aaronbushnell Well, there's also the possibility that the code is poorly formatted. I guess I agree on a surface level, but if the code was actually written to look at indentation, I imagine it'd cause more problems than it would if checking for things like opening/closing braces/parentheses/etc.

Here's an HTML example that would probably not work how I'd expect if folds were based on indentation:

```html
```

**Comment by aaronbushnell** [comment] 2016-04-07 02:43
@curtisblackwell Yeah, that's a good example of some of those edge-cases with indentation-based folds.

And, I'm sorry, I feel like I've pulled this conversation too far from my original request.  My main concern is I want to be able to see closing brackets, braces, tags, etc when a block is folded up.

```html
<!-- Expanded -->
<div>
  Hello world!
</div>

<!-- Folded -->
<div>
</div>
```

```js
// Expanded
var someFunction = function () {
    console.log('Hello world!');
};

// Folded
var someFunction = function () {
};
```

**Comment by francisrupert** [comment] 2016-04-16 03:58
The problem with...

```html
<div>
</div>
```

...and...

```js
var someFunction = function () {
};
```

...is they give a strong appearance of being empty, with potentially no clue something is obscured (gutter toggle notwithstanding).

The act of folding can be interpreted as *"show me the beginning and end, but make them discoverable."* The snippets I include above can be misinterpreted as *empty*. 

The best folding experience I've most appreciated is Textmate's. I highly recommend that as the model, **single-line**...

```html
<div> ... </div>
```

```js
var someFunction = function () { ... };

**Comment by curtisblackwell** [comment] 2016-04-16 04:17
@francisrupert I don't have any problem with your preference, but check out the gif in [Aaron's comment](https://github.com/atom/atom/issues/11179#issuecomment-206379769). The ellipses should prevent the confusion you mention.

**Comment by francisrupert** [comment] 2016-04-16 05:04
@curtisblackwell,

True and agree, especially in being able to style it. However, the orphan extra line has always been awkward. In my authoring workflow, I demand single-line. By folding I am stating I want this block to take up as little space as possible in the interest of getting a zoomed-out view to scan.

For example....

```html
<ul>
  <li> ... </li>
  <li> ... </li>
  <li> ... </li>
  <li> ... </li>
</ul>
```

... is smooth and scannable. While....

```html
<ul>
  <li> ... 
  </li>
  <li> ... 
  </li>
  <li> ... 
  </li>
  <li> ... 
  </li>
</ul>
```

...is clunky and slower to scan. I would almost rather Atom be left as is...

```html
<ul>
  <li> ...
  <li> ...
  <li> ...
  <li> ...
</ul>
```

...and rely on linting to catch those broken bits. HTML to demo my reasoning is a bit crude, though I've found it hold true for other languages.

One could make the argument for a Package (or perhaps core Settings item) allowing one to choose a folding pattern. As it is, every text editor makes that choice for every single one of us, and you deal with it. After all, if it's gonna be possible in any editor, it's the "hackable one."

**Comment by aaronbushnell** [comment] 2016-04-17 21:56
> One could make the argument for a Package (or perhaps core Settings item) allowing one to choose a folding pattern. As it is, every text editor makes that choice for every single one of us, and you deal with it. After all, if it's gonna be possible in any editor, it's the "hackable one."

I agree and like the idea that folding could be a package in the same way Tabs, Status Bar, and Snippets are. That'd allow users to uninstall the default package and load in their own if they prefer a different style.

**Comment by stugol** [comment] 2016-04-28 14:10
I too require single-line collapsed folds. Unless there's something important on the closing line, such as an `else`. Why not do this:
```
if (blah) { ... }

if (blah) { ... }
else { ... }
```
That way you can expand and collapse the `if`-part and the `else`-part as desired.

(Another potential solution to "you can't fold the `else` unless you fold it first" is to not allow collapsing one without the other. Either collapse the entire `if` or don't.)

**Comment by simoncpu** [comment] 2016-06-28 06:16
Let me add to the noise by typing "+1". Hehehe... I really hope that this gets fixed soon.

**Comment by songsanli** [comment] 2016-06-28 06:52
I've found a workaround to make Atom behave like Sublime. For example, you can change folding behavior of js file by adding below config to `config.cson`:

```cson
".js.source":
  editor:
    foldEndPattern: ""
```

My story: finally I wanted to take some effort on this pain point. After failure of studing source code, it occured to me that folding behavior of .txt file was what I want. So I diff [language-javascript](https://atom.io/packages/language-javascript) package with [language-text](https://github.com/atom/language-text) and guessed above config might reset foldEndPattern of js file. And it just worked. I had been in pain for a while T_T

Because I use [language-babel](https://atom.io/packages/language-babel) package, I add below lines to `config.cson` in fact:

```cson
".js.jsx.source":
  editor:
    foldEndPattern: ""
```

Work for me and the version of my Atom is 1.8.0.

**Comment by Nokel81** [comment] 2016-06-28 11:50
Brilliant, I think that this might actually "fix" our problems, now it would be nice if on the Atom site there was a page explaining how to make your own 'foldEndPattern'.

**Comment by aaronbushnell** [comment] 2016-06-28 23:59
@songsanli This is _brilliant_! Thanks for passing this along. I agree with @Nokel81. If this had a bit more documentation behind it I'd be absolutely satisfied with this as the solution.

**Comment by songsanli** [comment] 2016-07-01 02:17
During previous studying of source code, I guess that Atom use `foldEndPattern` to calculate range of row to be folded: if matched, current line will be folded. That is why `{}[]()` is been folded in js syntax setting. You can refer to source code [here](https://github.com/atom/atom/blob/ca041384fecf8a17bae078d2813fc94a90498bb8/src/language-mode.coffee#L166).

And the main fold function entry is [`foldBufferRow()`](https://github.com/atom/atom/blob/ca041384fecf8a17bae078d2813fc94a90498bb8/src/language-mode.coffee#L130).

Hope this info will help you if you want to dig deeper.

**Comment by joshbuchea** [comment] 2017-03-03 01:29
@songsanli thank you so much for your fix! This was driving me CRAZY!

**Comment by aeblin** [comment] 2017-05-22 23:38
Having trouble making @songsanli 's fix work. Anyone able to confirm that it works correctly in atom 1.17.0?

**Comment by joshbuchea** [comment] 2017-05-23 00:38
@aeblin it's working for me in Atom 1.17.0. Here is my config:

```cson
".basic.html.text":
  editor:
    foldEndPattern: ""
".css.source":
  editor:
    foldEndPattern: ""
".html.php.text":
  editor:
    foldEndPattern: ""
".js.jsx.source":
  editor:
    foldEndPattern: ""
".js.source":
  editor:
    foldEndPattern: ""
```

**Comment by aeblin** [comment] 2017-05-24 00:06
@joshbuchea Thanks! Looks like I'd managed to typo the html config. Working perfectly now.

**Comment by adriennn** [comment] 2017-07-01 17:30
Is it possible to achieve Brackets-style folding in Atom? i.e. folding on a single line with three dots and the closing bracket on the same line?

**Comment by LastGreenLeaf** [comment] 2017-07-15 05:10
The same question: Is there any way folding brackets on a single line with three dots and the closing bracket on the same line?

**Comment by ChristopherChudzicki** [comment] 2017-09-04 14:26
Ditto. It would be great to show `...` followed by the closing brace / tag. Unbalanced braces give me the shivers.

**Comment by Sosukodo** [comment] 2017-10-27 01:24
I agree.. { ... } is how it should be IMO. This is how TextWrangler looks:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/6215416/32083890-413691f2-ba83-11e7-8352-ce971b870e02.png">

**Comment by nestor-custodio** [comment] 2018-07-06 14:48
I really really hate to be the "not good enough" guy, but: satisfactory as @songsanli's may be for some, this really needs to be a toggle-able option in the settings screen. This issue is in need of a bump, so here you go.

**Comment by Aerijo** [comment] 2018-10-17 23:19
@spiffpitt This should already be the behaviour for Tree-sitter grammars (most common core packages like C, HTML, JS use this). Try `Settings -> Core -> Use Tree Sitter Parsers`.

**Comment by spiffpitt** [comment] 2018-10-18 00:57
@Aerijo Thank you, this worked great.

**Comment by andmej** [comment] 2019-02-28 00:29
> @spiffpitt This should already be the behaviour for Tree-sitter grammars (most common core packages like C, HTML, JS use this). Try `Settings -> Core -> Use Tree Sitter Parsers`.

This worked for me in C++. Thank you @Aerijo!

**Comment by rsese** [comment] 2019-02-28 05:21
Just to followup on @Aerijo's [comment above](https://github.com/atom/atom/issues/11179#issuecomment-430822249), Tree-sitter has been enabled by default since 1.32.0:

https://blog.atom.io/2018/10/23/atom-1-32.html#tree-sitter

With improved code folding, some things mentioned in this issue have been resolved, and additionally this particular issue has collected reports across different languages.  Right now, it would be most helpful if you have a reproducible folding problem with Tree-sitter enabled in the latest releases of Atom, please report it in the corresponding language repository (e.g. if you want to report an issue with JavaScript, you can open an issue in https://github.com/atom/language-javascript).  This makes things much easier to track for the team and anyone else that might want to contribute.  

But thanks again for all the reports and examples here :bow:  We'll go ahead and close this issue and if you open a new issue in one of the language repositories, please be sure to fill out the issue template and if you can also share a specific code snippet for copy/pasting, that would be extra helpful.

**Closed by rsese** 2019-02-28 05:21 UTC
Labels: enhancement
