### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/request/index.js'

### ISSUE THREAD

**Issue by pixelchutes** [atom/atom#5939] opened 2015-03-11 18:00 UTC
[Enter steps to reproduce below:]

1. Updated Atom via GUI (clicked "Restart and Update")
2. Clicked on Package Update notification icon
3. Updated 4 packages (clicked "Update" button individually per package)
4. Clicked the "Settings" button for the last package updated (remote-edit).
5. Error thrown

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

Looks like node module `request` is referenced, but not installed. Upgraded to `v0.187.0`, but no change... `node_modules/request` still does not exist.

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/request/index.js'

```
At fs.js:570

Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/request/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:503:18)
    at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
    at Object.fs.readFileSync (fs.js:355:15)
    at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:138:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
```

### Commands

```
     -0:43.4 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -0:06.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/git/",
    "disabledPackages": [
      "atom-beautify"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
git-log, v0.3.0
line-ending-converter, v1.0.0
monokai, v0.12.0
php-twig, v3.0.0
remote-edit, v1.7.2
script, v2.18.0

# Dev
No dev packages
```

**Comment by pixelchutes** [comment] 2015-03-13 01:01
Closing, since aforementioned steps do not reliably reproduce.

However, `/Applications/Atom.app/Contents/Resources/app/node_modules/request/` still does not exist, even though `request` package appears to be defined in `package.json` as a dependency.

**Comment by 50Wliu** [comment] 2015-03-13 01:07
@pixelchutes this (and related errors) seems to be happening randomly for a few people.  No one on the Atom team has been able to reproduce it yet.

**Comment by sambecker** [comment] 2015-03-15 20:07
Just got the same error after selecting 'Packages' from settings after attempting a failed auto-update from `0.186` to `0.187`.

`Error: ENOENT, no such file or directory '/Applications/Atom.app/Contents/Resources/app/node_modules/request/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:138:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at AtomIoClient.module.exports.AtomIoClient.fetchAndCacheAvatar (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:199:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:34:26
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:178:18
  at f (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/once/once.js:17:25)
  at Glob.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:129:7)
  at Glob.emit (events.js:116:17)
  at Glob._finish (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:166:8)
  at done (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:155:12)
  at Glob._processReaddir2 (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:346:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:283:17
  at RES (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/inflight/inflight.js:23:14)
  at f (/Applications/Atom.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator-babel/node_modules/commoner/node_modules/glob/node_modules/once/once.js:17:25)
  at Glob._readdirEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:475:10)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/glob/glob.js:452:12
  at FSReqWrap.oncomplete (fs.js:100:15)`

**Comment by pixelchutes** [comment] 2015-04-08 15:32
In my case, I was able to resolve by running `npm update` from: `/Applications/Atom.app/Contents/Resources/app/`, though that doesn't seem like it should be necessary? *(to do manually...)*

**Comment by kevinsawicki** [comment] 2015-04-30 17:58
This should be fixed now that [asar support in Atom](https://github.com/atom/atom/pull/6313) has shipped. Please comment if it happens again on Atom 0.194.0+.

**Closed by kevinsawicki** 2015-04-30 17:58 UTC
