### ISSUE TITLE
Almost frozen when editing huge javascript file

### ISSUE THREAD

**Issue by atrandafir** [atom/atom#7025] opened 2015-05-30 11:16 UTC
I've opened a plugins.js file from a theme from ThemeForrest, this file was containing a lot of packed js plugins of a total of 700kb of code.

The IDE simply got frozen for minutes until I could right click and close the tab.

Using 0.201 on Windows 7 64bits with 4gb of ram and i5 processor.

**Comment by izuzak** [comment] 2015-05-30 11:20
Thanks for the report -- sounds like a duplicate of https://github.com/atom/atom/issues/307 and https://github.com/atom/atom/issues/979, so I'm closing this in favor of those two. Improving Atom so that it can handle large files and files with very long lines is on the radar.

**Closed by izuzak** 2015-05-30 11:20 UTC
