### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by turigeza** [atom/atom#14481] opened 2017-05-18 12:28 UTC
[Enter steps to reproduce:]

I am really not sure how to reproduce I just switched from chrome to atom via the cmd+tab and I got this message ... sorry not being able to give you much more info

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:663:1)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:697:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:184:1)
    at /Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1
```

### Commands

```
     -3:15 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -3:13.1.0 core:confirm (input.hidden-input)
     -3:10.5.0 core:close (input.hidden-input)
     -3:09.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -3:08.3.0 core:move-down (input.hidden-input)
     -3:07.8.0 core:confirm (input.hidden-input)
     -2:56.3.0 core:copy (input.hidden-input)
     -2:55.5.0 core:paste (input.hidden-input)
  3x -2:53.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.17 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.3.0 
fold-functions 0.5.0 
fold-navigator 0.0.618 
git-control 0.9.0 
git-plus 7.3.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.57.2 
linter 2.1.2 
linter-csslint 1.3.4 
linter-htmlhint 1.3.3 
linter-js-standard 3.9.0 
linter-jshint 3.0.3 
linter-php 1.3.2 
linter-phpcs 1.6.0 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.2 
multi-cursor 2.1.5 
multi-cursor-plus 1.2.0 
php-class-tree 1.0.0 
php-integrator-symbol-viewer 0.6.4 
php-twig 4.0.0 
pigments 0.39.1 
project-plus 0.9.0 
split-diff 1.3.0 
symbols-tree-view 0.14.0 
tree-view-git-status 1.3.1 
```

**Comment by 50Wliu** [comment] 2017-05-18 15:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #11692. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-18 15:12 UTC
