### ISSUE TITLE
Reinstall and install not functional

### ISSUE THREAD

**Issue by ilg-ul** [atom/atom#12072] opened 2016-06-29 17:55 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Restart and install is not functional.

### Steps to Reproduce

1. click the **Restart and install** button in the About tab, or the **Restart and Install Update** menu

**Expected behavior:** to restart and update

**Actual behavior:** nothing

### Versions

1.7.4, on macOS 10.11.5

### Comments

I guess the problem is related to the fact that my account has no administrative rights, and the update procedure should ask the user for a password in order to be able to write into the `/Applications` folder.

**Comment by lee-dohm** [comment] 2016-06-29 19:59
Thanks for reporting this. This is a duplicate of https://github.com/atom/about/issues/21. The button doesn't function, but Atom should still update itself in the background. If you exit Atom normally and launch Atom again, it should launch with the new version.

**Closed by lee-dohm** 2016-06-29 19:59 UTC

**Comment by ilg-ul** [comment] 2016-06-29 20:08
unfortunately it does not work. Atom must ask the administrative password, and as long as it does not do it, it cannot succeed.

the workaround with the menu item does not work either.

**Comment by lee-dohm** [comment] 2016-06-29 20:11
In that case, this is a duplicate of https://github.com/atom/atom/issues/2860. You may want to subscribe there for updates.
