### ISSUE TITLE
Uncaught Can't find // if(divDestinosWidth > 400)            //     node.style.paddingTop = "0....

### ISSUE THREAD

**Issue by RiQuY** [atom/atom#18051] opened 2018-09-14 11:13 UTC
[ Steps to reproduce: ]

1. Select a block text (I was using JS), comment it with Ctrl+/
2. Press Ctrl+' (I have an spanish keyboard, I don't know if you can't access the ' key directly with an english keyboard)
3. Exception appears, the app don't crash, just warn me to report a Exception.

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version (I have Windows 10 Pro)
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find // if(divDestinosWidth > 400)
            //     node.style.paddingTop = "0.1em";
            // else
            //     node.style.paddingTop = "0.3em"; file

```
At C:\Users\Practicas02\AppData\Local\atom\app-1.30.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:982

undefined
```

### Commands

```
     -0:38.8.0 editor:toggle-line-comments (input.hidden-input)
     -0:30.7.0 emmet:encode-decode-data-url (input.hidden-input)
```

### Non-Core Packages

```
atom-i18n 0.16.0 
atom-ide-ui 0.13.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 - Disabled
emmet 2.4.3 
ide-php 0.7.15 
ide-typescript 0.7.6 
intentions 1.1.5 - Disabled
linter 2.2.0 - Disabled
linter-htmlhint 1.5.1 
linter-ui-default 1.7.1 - Disabled
```

**Comment by rsese** [comment] 2018-09-14 18:08
Thanks for contributing!

Based on the `undefined` and `text-buffer` reference in the error, I think this is a duplicate of https://github.com/atom/atom/issues/17830 so you can subscribe there for updates if you'd like.

Just to clarify, can you reproduce the error with your repro steps and if so, can you reproduce in safe mode?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-09-14 18:08 UTC
