### ISSUE TITLE
Opening file clears editor

### ISSUE THREAD

**Issue by tim740** [atom/atom#10183] opened 2015-12-26 00:52 UTC
When opening a file while editor is closed it clears the editor and opens the file, this can be annoying when you have project folders open and files open, i haven't found any online help or settings to prevent this, thanks for taking the time to look at this

**Comment by mnquintana** [comment] 2015-12-26 02:37
I'm not sure what you mean – what do you mean by "clears the editor"? What version of Atom are you using? What OS? Can you reproduce this in safe mode? (`atom --safe`)

Also please take a look at [the Reporting Bugs section of the Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) to help us help you debug further. Thanks!

**Comment by tim740** [comment] 2015-12-26 03:45
Im using Windows 10, what im saying is if I have 5 files and 2 project folders open in atom, close atom and reopen, and it will all reload like normal,  but if I close atom open a file with atom it clears the editor, so the only thing that is open is the file I've just opened, im using latest version of Atom.

**Comment by bkromhout** [comment] 2015-12-26 22:56
This also occurs on OS X.

**Comment by mindrones** [comment] 2015-12-29 10:33
Thanks for reporting this, it bugs me too.

@mnquintana on OSX:
- close Atom with 1+ open project(s) in it;
- in the Finder, right-click on a file, Open with: Atom;
- Atom opens the file but the previously open project(s) get lost.

I'd like to get the old projects in a window and the file opened from Finder in a separate Atom window, or get an alert with a question if I want to open the previous projects or not.

**Comment by tim740** [comment] 2016-01-01 21:40
I wish this was a togglable setting, Enabled by default.

**Comment by tyleracorn** [comment] 2016-03-25 21:00
Thanks for reporting this! This also is something that has been driving me crazy the past few days and I've so far been unable to find any solution. 
@mnquintana I'm on Windows 10 and I'm using Atom 1.6.0 

- close Atom with folders open in a current project
- in the windows explore, right-click on a file and select, open with Atom
- Atom opens the file, but previous project is now lost

Here are some screen shots of the behavor:
atom before closing atom the first time -
![image](https://cloud.githubusercontent.com/assets/10730870/14053866/0174c76c-f29a-11e5-93e7-f1a2c9b965f4.png)
atom after selecting "open with atom" in file explorer -
![image](https://cloud.githubusercontent.com/assets/10730870/14053893/315ed65c-f29a-11e5-8804-0b690d9cc58e.png)

@mnquintana is this enough information now or is there more information needed? If so, what sort of more information is needed? 

To me this seems like a bug. Or there should at least be an option to turn this on or off. Has anyone found a way around this feature of Atom? To be clear: when I click on a file in windows explorer and choose "open in Atom" I would like atom to start and keep the previous project loaded

Cheers,

**Comment by Zireael07** [comment] 2016-03-26 11:50
Related to #10517.

From what I understand, launching via Atom.exe opens to a different state than 'open in Atom'.

**Comment by tyleracorn** [comment] 2016-03-26 19:16
Thanks @Zireael07 ! That helps me at least start to understand what's going on. This will give me a new path to search down and maybe I can figure out how to modify what state "open in Atom" is used.

**Comment by alexchandel** [comment] 2016-04-18 18:22
This issue is a duplicate of #8427

**Comment by damieng** [comment] 2016-08-02 17:20
Will track under #8427

**Closed by damieng** 2016-08-02 17:20 UTC
Labels: feedback
