### ISSUE TITLE
Cmd+A doesn't select all when saving

### ISSUE THREAD

**Issue by thatlizarddude** [atom/atom#16155] opened 2017-11-10 20:15 UTC
### Description

Just a small issue, I decided I would report.
When you save a file on macOS, and the filename isn't selected, you can't do Cmd+A to select all the text.

### Steps to Reproduce

1. Save file as
2. Type something in
3. Try to Cmd+A

**Expected behavior:** [What you expect to happen]

Select the text

**Actual behavior:** [What actually happens]

It doesn't select the text

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

Atom: 1.22.0
Electron: 1.6.15
apm: 1.18.8
macOS: 10.13

### Additional Information

I tried to do the same in VS Code and it worked fine.

**Comment by 50Wliu** [comment] 2017-11-10 21:36
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14145. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-11-10 21:36 UTC
