### ISSUE TITLE
Atom Crashes After Opening Project Folder with 21k Line js File

### ISSUE THREAD

**Issue by ngmgithub** [atom/atom#12094] opened 2016-07-04 04:53 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom crashes with an "Editor not responding" message when loading a /dist/main.js file in a React.js project. If you're familiar with the React.js framework, main.js is a JavaScript file generated by tools like gulp, browserify and reactify to merge all libraries into one JavaScript file in order to be browser friendly. It is important to note that in this instance, the resulting file is approximately 21,000 lines of code.

Process information from top. Over 100% cpu being consumed by Atom Helper
```
53222  Atom Helper  101.0 01:31.25 21/1  0    124   250M   0B     0B     52624 52624 running  *0[2]            0.00000 0.00000    501  135808    1575
```

Problem is reproducible 100% of the time and occurs in safe mode.

### Steps to Reproduce

1. Launch Atom
2. File -> Add Project Folder -> Add folder with 21k line (1.8MB) main.js file

**Expected behavior:** [What you expected to happen]
CPU usage remains stable. Ability to edit and scroll through files as large or larger than 21k of code with given hardware (see versions).

**Actual behavior:** [What actually happened]
A few seconds to a minute after adding the project folder containing a 21k line main.js file CPU usage from an Atom helper process exceeds 100%. Error message "Editor not responding" occurs.

### Versions
```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4
Mac OS X: 10.11.4
MacBookPro Retina 15-Inch
2.5 GHz Intel Core i7 (4 Core)
16GB RAM
nVidia GPU
```

**Comment by yibuyisheng** [comment] 2016-07-04 06:06
Another similar case I have encountered is: When I open a file with some very long line,  Atom editor not responding.

I think the editor should not handle the text file's language syntax when it is too large, just treat it as a normal text file.

**Comment by Zireael07** [comment] 2016-07-04 06:29
@yibuyisheng: This is another issue, #979 to be precise.

@ngmgithub: Does the file have any long lines? 1.8 MB should be within Atom's abilities... so should 31k lines.

**Comment by lee-dohm** [comment] 2016-07-06 23:44
This is a duplicate of https://github.com/atom/atom/issues/8864. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-06 23:44 UTC
