### ISSUE TITLE
Highlight all ocurrences of the selected string in the current file

### ISSUE THREAD

**Issue by he7d3r** [atom/atom#5032] opened 2015-01-13 18:39 UTC
This is a very useful feature provided by Kate editor which I miss when I open I file on Atom.
Any chance it could be implemented?

Here is an example of how it works on Kate: suppose a file contains this
```
foo bar baz
baz foo bar
bar baz foo
```
If I double click on "foo", it gets selected and then all 3 occurrences of "foo" are highlighted. If I unselect "foo", the highlight disappears. If then I select "bar baz", its two occurrences (on lines 1 and 3) get selected.

**Comment by kevinsawicki** [comment] 2015-01-13 18:40
I believe this is a duplicate of https://github.com/atom/find-and-replace/issues/138

**Closed by kevinsawicki** 2015-01-13 18:40 UTC

**Comment by he7d3r** [comment] 2015-01-13 18:46
Indeed. Thanks!

**Comment by aeberlin** [comment] 2016-01-11 19:39
Although atom/find-and-replace#138 is still open, I think the hotkey is `ctrl-cmd-d`. It's not automatic.

https://github.com/atom/find-and-replace/commit/594fc16126ae1aeb8e2e159c192c041393e3a6d3
