### ISSUE TITLE
Tab type auto-detection fails when creating a new file

### ISSUE THREAD

**Issue by Lilalas** [atom/atom#17656] opened 2018-07-09 11:18 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tab type auto-detection fails when creating a new file; the editor always inserts tabs with respect to the `Soft Tabs` setting (specified in Settings → Editor). It only detects tabs correctly once I save and reopen the file.

### Steps to Reproduce

1. Make sure `Tab Type` is set to `auto` (Settings → Editor)

**First scenario:**

2. Set `Soft Tabs` to **`false`** (Settings → Editor)
3. Create a new file
4. Paste code that uses **soft tabs**
5. Press tab to indent a new line

**Second scenario:**

2. Set `Soft Tabs` to **`true`** (Settings → Editor)
3. Create a new file
4. Paste code that uses **hard tabs**
5. Press tab to indent a new line

**Expected behavior:** I expect the editor to automatically detect the tab type the code uses and therefore insert the corresponding tab characters when indenting a new line.

**Actual behavior:** In both scenarios, the editor inserts tab characters regarding the `Soft Tabs` setting—not the tab type used in the code.

**Reproduces how often:** Every time.

### Versions

```
$ atom --version
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.1
python 2.7.15rc1
git 2.17.1
$ lsb_release -idrc
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

### Additional Information

I found multiple packages that try to resolve this issue:

* [`auto-detect-indentation`](https://atom.io/packages/auto-detect-indentation): Detection works as soon as you save the file (you don't have to reopen it).
* [`indent-detective`](https://atom.io/packages/indent-detective): Detection works instantly—but not consistently for me.
* [`guess-indent`](https://atom.io/packages/guess-indent): Doesn’t do anything (or I don’t understand how to use it).

So they’re all not perfect. Also, I think you shouldn’t need to install a package for that.

**Comment by the-j0k3r** [comment] 2018-07-15 07:43
I use [editorconfig](https://atom.io/packages/editorconfig) its somewhat buggy for some operations but this seems to work OK.

**Comment by Lilalas** [comment] 2018-07-15 11:46
@the-j0k3r Thank you for sharing! `editorconfig` seems to be a very powerful package. However, I would rather prefer a solution that worked automagically.

**Comment by the-j0k3r** [comment] 2018-07-15 16:46
Automagically... Can of worms, may make for good fishing. I prefer 1 tab 4 spaces wide, then comes along another project which has 2 space no tabs then project C which has yet another indentation different from both. This would have to be some Merlin level magic to know what is what and where it belongs, working 100% of the time reliably.

**Comment by lee-dohm** [comment] 2018-07-17 20:32
@lee-dohm Reminder to take a look at this.

**Comment by Aerijo** [comment] 2018-07-25 10:46
The issue seems to be that spaces are being replaced to tabs _on paste_, so of course it detects hard tabs when you next press tab.

**Comment by lee-dohm** [comment] 2018-08-01 19:05
I've finally had a chance to take a look at this in more detail. According to the scenarios listed above, the actual behavior is as designed, even if it isn't what you expect. This is because when a new file is opened it has to decide on a tab type. Given that:

1. There is no text in the file
1. `Tab Type` is set to `auto`
1. `Soft Tabs` is set to `false` (in the first scenario)

The expected behavior for a new file is for it to have hard tabs behavior, regardless of what text is pasted in afterwards. The opposite is true for the second scenario, it is expected to have soft tabs behavior, regardless of what text is pasted in afterwards.

Could this be improved so that on creating new files the decision of tab type is deferred until the first time the actual tab key is pressed? I would have to give that a really strong _maybe._ There are a lot of different permutations of what indentation might be expected to be chosen for any particular sequence of events and I doubt that we'll be able to predict everyone's intent. The simple fact that none of the packages you tried worked the way you expected it to is a testament to that, in my opinion.

I'll bring this up to the team but given what else is on our plate, I don't think that creating more advanced indentation autodetection is going to bubble up very high at all on our priority list. For the most part, I feel the Tab Type setting works for most people and solutions like Editorconfig works for people that have more advanced needs.

**Comment by lee-dohm** [comment] 2018-08-01 19:16
@Aerijo I'm not sure that the change you're proposing would get @Lilalas where they want to go. The [`maintainConfig` function](https://github.com/atom/atom/blob/master/src/text-editor-registry.js#L145-L177) where the function you're redesigning resides is, to my knowledge, only [called when the Editor settings change](https://github.com/atom/atom/blob/master/src/text-editor-registry.js#L259-L265) not when text is pasted into the buffer.

Even still, if you've got some ideas about how to solve the originally specified behavior, I'd be very interested in hearing them :grinning:

**Comment by Aerijo** [comment] 2018-08-01 23:31
@lee-dohm That function is called whenever a new editor window is opened (and is not called when changing settings; it just fetches the latest value when it runs). By using events, I then cause it to run until it settles on a definite option.

So I still think it solves the original problem. But now I'm more inclined to agree that the current behaviour is to be expected; I don't want to accidentally set the project to tabs because I started by pasting some code I found online.

**Comment by lee-dohm** [comment] 2018-08-06 20:53
Thanks for the further clarification @Aerijo :bow:

Given that this is the expected behavior and we aren't planning on making additional changes to how the tab type is determined, I'm going to close this now. Thank you very much @Lilalas for the detailed bug report and your passion and interest in Atom!

**Closed by lee-dohm** 2018-08-06 20:53 UTC
Labels: triaged
