### ISSUE TITLE
Build script error for i386

### ISSUE THREAD

**Issue by ddm3rr1tt** [atom/atom#12116] opened 2016-07-07 18:45 UTC
platform: Debian i386.
error: while running script/build, the script bombs due to looking for x87 instead of x86 at nodejs.org

the build script is looking for:

http://nodejs.org/dist/v0.10.40/node-v0.10.40-linux-x87.tar.gz

when it should be looking for:

http://nodejs.org/dist/v0.10.40/node-v0.10.40-linux-x86.tar.gz

**Comment by lee-dohm** [comment] 2016-07-07 21:08
<details>
  <summary>Build log</summary>
```
root@kali2-i386:~/Desktop/PROJECTS/atom# script/build
Node: v4.3.1
npm: v1.4.21
Installing build modules...
=> Took 83365ms.

Installing apm...
download not found: http://nodejs.org/dist/v0.10.40/node-v0.10.40-linux-x87.tar.gz
npm ERR! Linux 4.6.0-kali1-686-pae
npm ERR! argv "/usr/bin/nodejs" "/root/Desktop/PROJECTS/atom/build/node_modules/.bin/npm" "--userconfig=/root/Desktop/PROJECTS/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v4.3.1
npm ERR! npm v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.9.2 install: `node ./script/download-node.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-package-manager@1.9.2 install script 'node ./script/download-node.js'.
npm ERR! This is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./script/download-node.js
npm ERR! You can get their info via:
npm ERR! npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /root/Desktop/PROJECTS/atom/apm/npm-debug.log
root@kali2-i386:~/Desktop/PROJECTS/atom#
```
</details>

**Comment by ruthgrace** [comment] 2016-07-08 22:44
Hi, I am unable to replicate the error.

I set up a VM with Debian jessie i386 (https://atlas.hashicorp.com/deb/boxes/jessie-i386), 2GB RAM, and installed git version 2.1.4 and node version 6.3.0, and ran the following, using the [build instructions here](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md)

```
sudo apt-get install build-essential git libgnome-keyring-dev fakeroot
git clone https://github.com/atom/atom.git
cd atom
git fetch -p
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
script/build
```

<detail>
```
vagrant@jessie-i386:~/atom$ script/build
Node: v6.3.0
npm: v3.10.3
Installing build modules...
=> Took 83458ms.

Installing apm...
=> Took 60232ms.

Deleting old packages...
=> Took 408ms.

Installing modules ✓
Installing atom-dark-syntax@0.27.0 ✓
Installing atom-dark-ui@0.51.0 ✓
Installing atom-light-syntax@0.28.0 ✓
Installing atom-light-ui@0.43.0 ✓
Installing base16-tomorrow-dark-theme@1.1.0 ✓
Installing base16-tomorrow-light-theme@1.1.1 ✓
Installing one-dark-ui@1.3.1 ✓
Installing one-light-ui@1.3.1 ✓
Installing one-dark-syntax@1.2.0 ✓
Installing one-light-syntax@1.2.0 ✓
Installing solarized-dark-syntax@1.0.2 ✓
Installing solarized-light-syntax@1.0.2 ✓
Installing about@1.5.0 ✓
Installing archive-view@0.61.1 ✓
Installing autocomplete-atom-api@0.10.0 ✓
Installing autocomplete-css@0.11.1 ✓
Installing autocomplete-html@0.7.2 ✓
Installing autocomplete-plus@2.29.2 ✓
Installing autocomplete-snippets@1.10.0 ✓
Installing autoflow@0.27.0 ✓
Installing autosave@0.23.1 ✓
Installing background-tips@0.26.0 ✓
Installing bookmarks@0.39.0 ✓
Installing bracket-matcher@0.82.0 ✓
Installing command-palette@0.38.0 ✓
Installing deprecation-cop@0.54.1 ✓
Installing dev-live-reload@0.47.0 ✓
Installing encoding-selector@0.21.0 ✓
Installing exception-reporting@0.38.0 ✓
Installing find-and-replace@0.199.0 ✓
Installing fuzzy-finder@1.0.5 ✓
Installing git-diff@1.0.1 ✓
Installing go-to-line@0.30.0 ✓
Installing grammar-selector@0.48.1 ✓
Installing image-view@0.57.0 ✓
Installing incompatible-packages@0.26.1 ✓
Installing keybinding-resolver@0.35.0 ✓
Installing line-ending-selector@0.4.1 ✓
Installing link@0.31.1 ✓
Installing markdown-preview@0.158.0 ✓
Installing metrics@0.53.1 ✓
Installing notifications@0.63.1 ✓
Installing open-on-github@1.0.1 ✓
Installing package-generator@1.0.0 ✓
Installing settings-view@0.235.1 ✓
Installing snippets@1.0.2 ✓
Installing spell-check@0.67.1 ✓
Installing status-bar@1.2.3 ✓
Installing styleguide@0.45.2 ✓
Installing symbols-view@0.112.0 ✓
Installing tabs@0.96.0 ✓
Installing timecop@0.33.1 ✓
Installing tree-view@0.205.0 ✓
Installing update-package-dependencies@0.10.0 ✓
Installing welcome@0.34.0 ✓
Installing whitespace@0.32.2 ✓
Installing wrap-guide@0.38.1 ✓
Installing language-c@0.51.3 ✓
Installing language-clojure@0.20.0 ✓
Installing language-coffee-script@0.46.1 ✓
Installing language-csharp@0.12.1 ✓
Installing language-css@0.36.1 ✓
Installing language-gfm@0.85.0 ✓
Installing language-git@0.12.1 ✓
Installing language-go@0.42.0 ✓
Installing language-html@0.44.1 ✓
Installing language-hyperlink@0.16.0 ✓
Installing language-java@0.17.0 ✓
Installing language-javascript@0.110.0 ✓
Installing language-json@0.18.0 ✓
Installing language-less@0.29.3 ✓
Installing language-make@0.21.1 ✓
Installing language-mustache@0.13.0 ✓
Installing language-objective-c@0.15.1 ✓
Installing language-perl@0.34.0 ✓
Installing language-php@0.37.0 ✓
Installing language-property-list@0.8.0 ✓
Installing language-python@0.43.1 ✓
Installing language-ruby@0.68.5 ✓
Installing language-ruby-on-rails@0.25.0 ✓
Installing language-sass@0.46.0 ✓
Installing language-shellscript@0.21.1 ✓
Installing language-source@0.9.0 ✓
Installing language-sql@0.20.0 ✓
Installing language-text@0.7.1 ✓
Installing language-todo@0.27.0 ✓
Installing language-toml@0.18.0 ✓
Installing language-xml@0.34.4 ✓
Installing language-yaml@0.25.2 ✓
=> Took 526039ms.

Deduping modules ✓
=> Took 39750ms.

Running "download-electron" task


Running "download-electron-chromedriver" task


Running "build" task

Running "babel:dist" (babel) task

Running "coffee:glob_to_multiple" (coffee) task
>> 336 files created.

Running "prebuild-less:src" (prebuild-less) task
>> 1891 files compiled, 0 files reused

Running "cson:glob_to_multiple" (cson) task
>> 172 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task
Generating parser from "node_modules/snippets/lib/snippet-body.pegjs"...
Parser "/home/vagrant/atom/out/Atom/resources/app/node_modules/snippets/lib/snippet-body.js" generated in 36ms.

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task

Running "set-version" task

Running "generate-asar" task

Done, without errors.


Execution Time (2016-07-08 22:05:22 UTC)
loading tasks                       2.4s  ▇ 1%
download-electron               1m 44.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 55%
download-electron-chromedriver      3.1s  ▇ 2%
build                               5.8s  ▇ 3%
coffee:glob_to_multiple            14.7s  ▇▇▇ 8%
prebuild-less:src                    38s  ▇▇▇▇▇▇▇ 20%
cson:glob_to_multiple               4.6s  ▇ 2%
generate-asar                      11.5s  ▇▇ 6%
Total 3m 8.8s

```
</detail>

I tried skipping the lines
```
git fetch -p
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
```
to run it on the latest developer version (currently https://github.com/atom/atom/tree/98fc8db3daa2021d391f03f93b1de8f40e424cb4), and that worked fine too. I'm not sure why, but in this case I had to run `script/build` twice.

<detail>
```
vagrant@jessie-i386:~/atom$ script/build
Node: v6.3.0
npm: v3.10.3
Installing build modules...
npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "--userconfig=/home/vagrant/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! path /home/vagrant/.atom/.npm/registry.npmjs.org/escope/.cache.json.880692309
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall lstat

npm ERR! enoent ENOENT: no such file or directory, lstat '/home/vagrant/.atom/.npm/registry.npmjs.org/escope/.cache.json.880692309'
npm ERR! enoent ENOENT: no such file or directory, lstat '/home/vagrant/.atom/.npm/registry.npmjs.org/escope/.cache.json.880692309'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/atom/build/npm-debug.log
vagrant@jessie-i386:~/atom$ 
vagrant@jessie-i386:~/atom$ script/build
Node: v6.3.0
npm: v3.10.3
Installing build modules...

=> Took 86018ms.

Installing apm...
=> Took 71408ms.

Deleting old packages...
=> Took 424ms.

Installing modules ✓
Installing atom-dark-syntax@0.27.0 ✓
Installing atom-dark-ui@0.52.0 ✓
Installing atom-light-syntax@0.28.0 ✓
Installing atom-light-ui@0.44.0 ✓
Installing base16-tomorrow-dark-theme@1.1.0 ✓
Installing base16-tomorrow-light-theme@1.1.1 ✓
Installing one-dark-ui@1.4.0 ✓
Installing one-light-ui@1.4.0 ✓
Installing one-dark-syntax@1.3.0 ✓
Installing one-light-syntax@1.3.0 ✓
Installing solarized-dark-syntax@1.0.2 ✓
Installing solarized-light-syntax@1.0.2 ✓
Installing about@1.5.3 ✓
Installing archive-view@0.61.1 ✓
Installing autocomplete-atom-api@0.10.0 ✓
Installing autocomplete-css@0.11.2 ✓
Installing autocomplete-html@0.7.2 ✓
Installing autocomplete-plus@2.31.1 ✓
Installing autocomplete-snippets@1.11.0 ✓
Installing autoflow@0.27.0 ✓
Installing autosave@0.23.1 ✓
Installing background-tips@0.26.1 ✓
Installing bookmarks@0.41.0 ✓
Installing bracket-matcher@0.82.1 ✓
Installing command-palette@0.38.0 ✓
Installing deprecation-cop@0.54.1 ✓
Installing dev-live-reload@0.47.0 ✓
Installing encoding-selector@0.22.0 ✓
Installing exception-reporting@0.38.1 ✓
Installing find-and-replace@0.201.0 ✓
Installing fuzzy-finder@1.2.0 ✓
Installing git-diff@1.0.1 ✓
Installing go-to-line@0.31.0 ✓
Installing grammar-selector@0.48.1 ✓
Installing image-view@0.58.2 ✓
Installing incompatible-packages@0.26.1 ✓
Installing keybinding-resolver@0.35.0 ✓
Installing line-ending-selector@0.5.0 ✓
Installing link@0.31.1 ✓
Installing markdown-preview@0.158.0 ✓
Installing metrics@0.53.1 ✓
Installing notifications@0.65.0 ✓
Installing open-on-github@1.1.0 ✓
Installing package-generator@1.0.0 ✓
Installing settings-view@0.240.0 ✓
Installing snippets@1.0.2 ✓
Installing spell-check@0.67.1 ✓
Installing status-bar@1.3.1 ✓
Installing styleguide@0.46.0 ✓
Installing symbols-view@0.113.0 ✓
Installing tabs@0.99.0 ✓
Installing timecop@0.33.1 ✓
Installing tree-view@0.208.0 ✓
Installing update-package-dependencies@0.10.0 ✓
Installing welcome@0.34.0 ✓
Installing whitespace@0.32.2 ✓
Installing wrap-guide@0.38.1 ✓
Installing language-c@0.52.1 ✓
Installing language-clojure@0.21.0 ✓
Installing language-coffee-script@0.47.1 ✓
Installing language-csharp@0.12.1 ✓
Installing language-css@0.37.0 ✓
Installing language-gfm@0.88.0 ✓
Installing language-git@0.14.0 ✓
Installing language-go@0.42.0 ✓
Installing language-html@0.44.1 ✓
Installing language-hyperlink@0.16.0 ✓
Installing language-java@0.23.0 ✓
Installing language-javascript@0.119.0 ✓
Installing language-json@0.18.1 ✓
Installing language-less@0.29.4 ✓
Installing language-make@0.22.2 ✓
Installing language-mustache@0.13.0 ✓
Installing language-objective-c@0.15.1 ✓
Installing language-perl@0.35.0 ✓
Installing language-php@0.37.1 ✓
Installing language-property-list@0.8.0 ✓
Installing language-python@0.45.0 ✓
Installing language-ruby@0.68.6 ✓
Installing language-ruby-on-rails@0.25.0 ✓
Installing language-sass@0.55.0 ✓
Installing language-shellscript@0.22.4 ✓
Installing language-source@0.9.0 ✓
Installing language-sql@0.22.0 ✓
Installing language-text@0.7.1 ✓
Installing language-todo@0.28.0 ✓
Installing language-toml@0.18.0 ✓
Installing language-xml@0.34.8 ✓
Installing language-yaml@0.26.0 ✓
=> Took 540214ms.

Deduping modules ✓
=> Took 47531ms.

Running "download-electron" task


Running "download-electron-chromedriver" task


Running "build" task

Running "babel:dist" (babel) task

Running "coffee:glob_to_multiple" (coffee) task
>> 343 files created.

Running "prebuild-less:src" (prebuild-less) task
>> 1610 files compiled, 0 files reused

Running "cson:glob_to_multiple" (cson) task
>> 172 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task
Generating parser from "node_modules/snippets/lib/snippet-body.pegjs"...
Parser "/home/vagrant/atom/out/Atom/resources/app/node_modules/snippets/lib/snippet-body.js" generated in 39ms.

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task

Running "set-version" task

Running "generate-asar" task

Done, without errors.


Execution Time (2016-07-08 22:37:26 UTC)
loading tasks                       3.5s  ▇ 2%
download-electron               1m 59.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 60%
download-electron-chromedriver      2.5s  ▇ 1%
build                                13s  ▇▇ 6%
coffee:glob_to_multiple            11.7s  ▇▇ 6%
prebuild-less:src                  33.1s  ▇▇▇▇▇ 16%
cson:glob_to_multiple               4.2s  ▇ 2%
generate-asar                       9.3s  ▇▇ 5%
Total 3m 20.6s

```
</detail>

**Comment by lee-dohm** [comment] 2016-07-12 07:08
@ddm3rr1tt Do you have any more information? We haven't been able to reproduce the problem you're describing.

**Comment by zapashcanon** [comment] 2016-07-12 23:49
I can confirm this. Debian Testing (Stretch), i386.

@lee-dohm, what kind of informations would you like to have ?

**Comment by lee-dohm** [comment] 2016-07-12 23:52
If you can help track down why it would be asking for `x87` instead of `x86` that would be a big help, because we haven't been able to figure it out so far.

**Comment by zapashcanon** [comment] 2016-07-13 00:21
[npm-debug.txt](https://github.com/atom/atom/files/360463/npm-debug.txt)

What else can I do ? I tried to look at the atom/apm repo, but didn't see anything. But I think it may be an error in some kind of library/function or idk what called (here)[https://github.com/atom/apm/blob/v1.9.2/script/download-node.js].

**Comment by ddm3rr1tt** [comment] 2016-07-16 01:25
i was using Kali i386...the script selected teh URL with x87 instead of
x86...i got around it by download teh package and installing it then
running the script again

**Comment by Ingramz** [comment] 2016-07-18 09:05
It looks like nodejs on Kali was built with target arch=x87 (`process.arch` evaluates to `"x87"`). Installing a build from [nodesource](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) should solve it as it is built for ia32. Seems like most recent debian release also uses ia32, but I don't know if it was different in the past (unlikely).

**Comment by damieng** [comment] 2016-11-29 03:06
Issue with Kali's node configuration. Closing.

**Closed by damieng** 2016-11-29 03:06 UTC
Labels: build-error, more-information-needed, needs-reproduction
