### ISSUE TITLE
Build-id link for libffmpeg.so should be removed from RPM

### ISSUE THREAD

**Issue by mrwulf** [atom/atom#19692] opened 2019-07-23 16:53 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When installing atom & bitwarden desktop, both include build-id info for `libffmpeg.so` so collide on fedora when trying to install:
`file /usr/lib/.build-id/bb/e5384c7ef7abee250ccc3090b0c7e99cf394a5 from install of atom-1.39.0-0.1.x86_64 conflicts with file from package bitwarden-1.14.0-1.x86_64`.

```
$ ll /usr/lib/.build-id/bb/e5384c7ef7abee250ccc3090b0c7e99cf394a5
lrwxrwxrwx. 1 root root 38 Mar 12 14:06 /usr/lib/.build-id/bb/e5384c7ef7abee250ccc3090b0c7e99cf394a5 -> ../../../../opt/Bitwarden/libffmpeg.so
```

Solve by defining `_build_id_links none` for the rpm build.

Here are some related links:
https://fedoraproject.org/wiki/Releases/FeatureBuildId
https://fedoraproject.org/wiki/Changes/ParallelInstallableDebuginfo
https://github.com/taw00/riot-rpm/issues/11
https://github.com/bitwarden/desktop/issues/277

### Versions

atom-1.39.0-0.1.x86_64

**Comment by rsese** [comment] 2019-07-23 17:09
Thanks for the heads up @mrwulf - just to clarify, does this issue just generate that warning message or does it also prevent whichever application you try to install second from working?

**Comment by mrwulf** [comment] 2019-07-23 17:28
@rsese - it prevents the second app from installing with a transaction check error. Here is the output from `dnf upgrade -y atom`:
```
Downloading Packages:
[SKIPPED] atom-1.39.0-0.1.x86_64.rpm: Already downloaded                                                                                                                                                          
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/lib/.build-id/bb/e5384c7ef7abee250ccc3090b0c7e99cf394a5 from install of atom-1.39.0-0.1.x86_64 conflicts with file from package bitwarden-1.14.0-1.x86_64

Error Summary
-------------

```
- I'm not sure why there is a `Transaction check succeeded.` line when there is clearly an error

**Comment by rsese** [comment] 2019-07-23 20:15
Thanks for confirming :bow:  Just noting that I reproduced by installing 1.39.0 on Fedora 29 and then installing BitWarden via the .rpm from https://bitwarden.com/#download.

**Comment by rsese** [comment] 2019-07-23 21:54
One more note - removed BitWarden, then installed 1.38.2.  Then installed BitWarden again and the installation completed successfully so tagging as a regression.

**Comment by jasonrudolph** [comment] 2019-07-23 21:58
@rsese: If you have a moment, could you try reproducing the issue with 1.39.0-beta2 and 1.39.0-beta3. I ask, because I suspect that this problem is due to the [build environment changes that happened between 1.39.0-beta2 and 1.39.0-beta3](https://github.com/atom/atom/issues/19690#issuecomment-514397823). If you _can_ reproduce this problem with 1.39.0-beta3 and *cannot* reproduce it with 1.39.0-beta2, that will likely confirm this hypothesis.

**Comment by rsese** [comment] 2019-07-23 22:11
Looks like you're right :zap:

Uninstalled Atom Beta and BitWarden first (`sudo yum remove bitwarden` and `sudo yum remove atom-beta`); then after installing 1.39.0-beta2, installing BitWarden completes.   Uninstalled both applications again and after installing 1.39.0-beta3, installing BitWarden fails as described in the OP.

**Comment by jasonrudolph** [comment] 2019-07-24 17:30
:wave: Hi @mrwulf: I think we've got a fix for this issue. You can find an rpm with the proposed fix at https://github.visualstudio.com/Atom/_build/results?buildId=46092&view=results:

<img width="1052" alt="screenshot" src="https://user-images.githubusercontent.com/2988/61814920-203f2200-ae17-11e9-9378-ef2c3826fcda.png">

Would you mind trying it out and letting us know if it resolves the issue for you? If it does, then we'll publish a new release with this fix.

**Comment by jasonrudolph** [comment] 2019-07-25 17:58
Atom 1.39.1 and 1.40.0.beta1 are out now with a fix for this problem, so I'm going to close out this issue.

**Closed by jasonrudolph** 2019-07-25 17:58 UTC
Labels: linux, regression, triaged

**Comment by mrwulf** [comment] 2019-07-25 18:05
@jasonrudolph build 46092 seems to work well- thanks!
