### ISSUE TITLE
action invoked with double click

### ISSUE THREAD

**Issue by calidion** [atom/atom#10399] opened 2016-01-13 14:13 UTC
currently single click will open a file. it is very strange for most of the time.

**Comment by ankit-m** [comment] 2016-01-13 19:08
Why double click? Single-click and double click do the same job.

**Comment by lee-dohm** [comment] 2016-01-13 23:20
@calidion This is a duplicate of https://github.com/atom/tree-view/issues/199. Please subscribe there for updates. If I'm misunderstanding, please let us know and if you can provide some more details it would be helpful!

**Closed by lee-dohm** 2016-01-13 23:20 UTC
