### ISSUE TITLE
Atom don't remove file in typescript project.

### ISSUE THREAD

**Issue by SalihKARAHAN** [atom/atom#11583] opened 2016-04-22 23:58 UTC
Hi,

I use atom for typescript development but atom can't deleting file or directory in project on windows and mac os. I observed this problem specific only typescript projects. Atom hasn't this bug for other projects.
<img width="464" alt="screen shot 2016-04-23 at 02 54 45" src="https://cloud.githubusercontent.com/assets/5853234/14757670/ce7e1a86-08fe-11e6-8a34-125edf5f9122.png">

**Comment by damieng** [comment] 2016-04-23 18:04
It is possible that the file is still in use? Are you using OmniSharp or another tool that might have it locked?

Also, which OS is this on?

**Comment by lee-dohm** [comment] 2016-05-01 06:27
@SalihKARAHAN Do you have any more information you can share with us? Right now, we don't have enough information to reproduce this issue and will have to close the Issue if there is nothing more you can tell us.

**Comment by SalihKARAHAN** [comment] 2016-05-03 18:48
@damieng @lee-dohm sorry for delay. Yes, i have extensions (i don't use OmniSharp). I think TypeScript addin installed on my editor and the addin watch all *.ts file in project according to defined itselft config but i don't understand why atom don't intercept the deleting process and stop watching on the file?

**Comment by lee-dohm** [comment] 2016-05-03 21:52
@SalihKARAHAN Atom stops watching things that Atom starts watching, but if a package does something to lock a file the rest of Atom doesn't necessarily know about it. Because Atom doesn't know everything that the packages are doing, it can't pre-emptively do things on the packages' behalf like you're suggesting.

It sounds like this is a bug in the typescript package you have installed. You should file an Issue on their repo to let them know. Let me know if I've misunderstood the situation :grinning:

**Closed by lee-dohm** 2016-05-03 21:52 UTC
Labels: more-information-needed
