### ISSUE TITLE
Release Notes is outdated

### ISSUE THREAD

**Issue by yamsellem** [atom/atom#10103] opened 2015-12-17 11:08 UTC
Displaying the releases notes (help > Release Note) displays releases until 1.1.0.
But the last Atom release is 1.3.2 (About Atom displays this proper release).

**Comment by 50Wliu** [comment] 2015-12-17 13:25
This is a duplicate of atom/release-notes#39 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-17 13:25 UTC

**Comment by yamsellem** [comment] 2015-12-17 14:55
@50Wliu Oups, sorry for the duplicate & thanks for the pointer ;-).
