### ISSUE TITLE
Cannot install atom-beautify package

### ISSUE THREAD

**Issue by smarts** [atom/atom#5090] opened 2015-01-16 01:41 UTC
after a clean install of atom (using the windows installer on my windows 8.1 machine) i cannot install the atom-beautify package. here's the output from the installation try:
```
npm http GET https://registry.npmjs.org/analytics-node
npm http GET https://registry.npmjs.org/atom-message-panel
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/editorconfig
npm http GET https://registry.npmjs.org/coffee-formatter
npm http GET https://registry.npmjs.org/loophole
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/js-beautify
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/node-dir
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/prettydiff
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/typescript-formatter
npm http GET https://registry.npmjs.org/yaml-front-matter
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/editorconfig
npm http 304 https://registry.npmjs.org/analytics-node
npm http 304 https://registry.npmjs.org/atom-message-panel
npm http 304 https://registry.npmjs.org/js-beautify
npm http 304 https://registry.npmjs.org/loophole
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http 304 https://registry.npmjs.org/coffee-formatter
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/node-dir
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/yaml-front-matter
npm http 304 https://registry.npmjs.org/prettydiff
npm http 304 https://registry.npmjs.org/typescript-formatter
npm http GET https://registry.npmjs.org/component-type
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/superagent-proxy
npm http GET https://registry.npmjs.org/uid/0.0.2
npm http GET https://registry.npmjs.org/join-component
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/commander/1.0.0
npm http GET https://reghttps://github.com/atom/atom/issues/newistry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/is-browser
npm http 304 https://registry.npmjs.org/component-type
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/rimraf
npm ERR! Error: ENOENT, chmod 'C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\lodash\LICENSE.txt'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\foo\\.atom\\.apmrc" "install" "c:\\Users\\foo\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.21.2\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\lodash\LICENSE.txt
npm ERR! fstream_path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\lodash\LICENSE.txt
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\foo\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/uid/0.0.2
npm http 304 https://registry.npmjs.org/superagent-proxy
npm http 304 https://registry.npmjs.org/join-component
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/js-yaml
npm ERR! Error: ENOENT, lstat 'C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\js-beautify\js\lib\unpackers\p_a_c_k_e_r_unpacker.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\foo\\.atom\\.apmrc" "install" "c:\\Users\\foo\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.21.2\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\js-beautify\js\lib\unpackers\p_a_c_k_e_r_unpacker.js
npm ERR! fstream_path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\js-beautify\js\lib\unpackers\p_a_c_k_e_r_unpacker.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\foo\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! error rolling back Error: EPERM, unlink 'C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\prettydiff\prettydiff.js'
npm ERR! error rolling back  atom-beautify@0.21.2 { [Error: EPERM, unlink 'C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\prettydiff\prettydiff.js']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Users\\foo\\AppData\\Local\\Temp\\apm-install-dir-115015-8932-9slqk5\\node_modules\\atom-beautify\\node_modules\\prettydiff\\prettydiff.js' }
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\foo\\.atom\\.apmrc" "install" "c:\\Users\\foo\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.21.2\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/commander/1.0.0
npm http 304 https://registry.npmjs.org/is-browser
npm ERR! Error: ENOENT, lstat 'C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\typescript-formatter\tests\expected\default\main.ts'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\foo\\.atom\\.apmrc" "install" "c:\\Users\\foo\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.21.2\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\typescript-formatter\tests\expected\default\main.ts
npm ERR! fstream_path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\typescript-formatter\tests\expected\default\main.ts
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\foo\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\space-pen\vendor\jquery.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\foo\\.atom\\.apmrc" "install" "c:\\Users\\foo\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.21.2\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\space-pen\vendor\jquery.js
npm ERR! fstream_path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\space-pen\vendor\jquery.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\foo\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\coffee-formatter\docs\public\fonts\aller-light.woff'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\foo\\.atom\\.apmrc" "install" "c:\\Users\\foo\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.21.2\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\coffee-formatter\docs\public\fonts\aller-light.woff
npm ERR! fstream_path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\coffee-formatter\docs\public\fonts\aller-light.woff
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\foo\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm http GET https://registry.npmjs.org/proxy-agent
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/ms/0.6.2
npm ERR! Error: ENOENT, lstat 'C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\prettydiff\prettydiff.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\foo\\.atom\\.apmrc" "install" "c:\\Users\\foo\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.21.2\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\prettydiff\prettydiff.js
npm ERR! fstream_path C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5\node_modules\atom-beautify\node_modules\prettydiff\prettydiff.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\foo\AppData\Local\atom\app-0.174.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm http 304 https://registry.npmjs.org/proxy-agent
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http GET https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/emitter-component/1.0.0
npm http 304 https://registry.npmjs.org/cookiejar/1.3.0
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/https-proxy-agent
npm http GET https://registry.npmjs.org/pac-proxy-agent
npm http GET https://registry.npmjs.org/http-proxy-agent
npm http GET https://registry.npmjs.org/socks-proxy-agent
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm http 304 https://registry.npmjs.org/pac-proxy-agent
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/http-proxy-agent
npm http 304 https://registry.npmjs.org/socks-proxy-agent
npm http 304 https://registry.npmjs.org/https-proxy-agent
npm http GET https://registry.npmjs.org/rainbowsocks
npm http GET https://registry.npmjs.org/agent-base
npm http GET https://registry.npmjs.org/get-uri
npm http GET https://registry.npmjs.org/pac-resolver
npm http GET https://registry.npmjs.org/stream-to-array
npm http 304 https://registry.npmjs.org/get-uri
npm http 304 https://registry.npmjs.org/stream-to-array
npm http 304 https://registry.npmjs.org/agent-base
npm http 304 https://registry.npmjs.org/pac-resolver
npm http 304 https://registry.npmjs.org/rainbowsocks
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/file-uri-to-path
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/data-uri-to-buffer
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/co
npm http GET https://registry.npmjs.org/regenerator
npm http GET https://registry.npmjs.org/degenerator
npm http GET https://registry.npmjs.org/netmask
npm http GET https://registry.npmjs.org/thunkify
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/file-uri-to-path
npm http 304 https://registry.npmjs.org/ftp
npm http 304 https://registry.npmjs.org/data-uri-to-buffer
npm http 304 https://registry.npmjs.org/co
npm http 304 https://registry.npmjs.org/degenerator
npm http 304 https://registry.npmjs.org/regenerator
npm http 304 https://registry.npmjs.org/netmask
npm http 304 https://registry.npmjs.org/thunkify
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http GET https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/ast-types
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/private
npm http GET https://registry.npmjs.org/defs
npm http GET https://registry.npmjs.org/recast
npm http 304 https://registry.npmjs.org/ast-types
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/defs
npm http 304 https://registry.npmjs.org/private
npm http 304 https://registry.npmjs.org/recast
npm http 304 https://registry.npmjs.org/escodegen
npm
```

**Comment by kevinsawicki** [comment] 2015-01-16 01:51
It looks like `git` isn't on your `Path`.

```
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\foo\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\foo\\.atom\\.apmrc" "install" "c:\\Users\\foo\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.21.2\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\foo\AppData\Local\Temp\apm-install-dir-115015-8932-9slqk5
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
```

**Comment by kevinsawicki** [comment] 2015-01-16 01:52
I believe this is a duplicate of #4902

**Closed by kevinsawicki** 2015-01-16 01:52 UTC
