### ISSUE TITLE
Uncaught Error: dlopen(~/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources...

### ISSUE THREAD

**Issue by Sharathrao98** [atom/atom#21455] opened 2020-10-08 21:09 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:160

Error: dlopen(/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/static/<embedded>:1:692867)
    at get_KeyboardLayoutManager (/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/static/<embedded>:14:2786167)
    at get_manager (/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/static/<embedded>:14:2786269)
    at Object.getCurrentKeyboardLayout (/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/static/<embedded>:14:2786395)
    at e.keystrokeForKeyboardEvent (/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/static/<embedded>:14:1083385)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/static/<embedded>:11:1250646)
    at KeymapManager.handleKeyboardEvent (/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/static/<embedded>:11:1248631)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/sharath/Library/Mobile Documents/com~apple~CloudDocs/Atom.app/Contents/Resources/app/static/<embedded>:11:284496)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
```

**Comment by darangi** [comment] 2020-10-15 09:06
I see you currently use an old version of atom, could you download the latest version (.52.0) and see if this issue persists?

**Comment by sadick254** [comment] 2020-10-19 07:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-10-19 07:13 UTC
