### ISSUE TITLE
Question :  portable version 

### ISSUE THREAD

**Issue by crper** [atom/atom#9271] opened 2015-10-24 02:17 UTC
- **Why does not the portable version, a summary of what the plug-in installation directory;**
- **atom does not seem to provide synchronization, with sync-settings often given, experience is very bad;**

Thankyou !!

**Comment by crperlin** [comment] 2015-10-24 02:19
- apm 管理 , 在其他地区使用非常糟糕(经常链接不上,插件主题什么也麻烦,,,为什么不用npm 管理)

**Comment by 50Wliu** [comment] 2015-10-24 02:54
> Why does not the portable version, a summary of what the plug-in installation directory;

This is being worked on in #8442!

> atom does not seem to provide synchronization

I think this one is a duplicate of #3572.

> plug Topics What is also troublesome

Can you elaborate on what you mean by this please?

**Comment by JohnMurga** [comment] 2015-11-02 07:10
For those looking for portability under Windows this may be useful :

https://github.com/JohnMurga/atom-portable/releases

Early days yet :+1:

**Comment by crperlin** [comment] 2015-11-02 11:51
@JohnMurga  Thank you! , How Stability?

**Comment by JohnMurga** [comment] 2015-11-02 14:34
@crperlin works for me :+1:

**Closed** 2016-12-02 07:10 UTC
