### ISSUE TITLE
Windows: make "Open with Atom" context menu a preference

### ISSUE THREAD

**Issue by leranus** [atom/atom#5002] opened 2015-01-12 12:52 UTC
As discussed in #4987, the Atom installer installs a "Open with Atom" entry in the Windows Explorer context menu for every file and folder. It would be preferable, as @paulcbetts suggests, to have a prefence where it can be turned off or on entirely, or just for specific files and folders. For example, not many people will open images from Explorer with Atom.

@lee-dohm pointed out that the specific code which adds and removes the item is in https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee.

**Comment by Moter8** [comment] 2015-01-12 15:01
Semi-Duplicate of #4695. :+1: though.

**Comment by maxbrunsfeld** [comment] 2015-01-12 16:37
Closing in favor of #4695. Thanks, @Moter8.

**Closed by maxbrunsfeld** 2015-01-12 16:37 UTC
Labels: windows

**Comment by leranus** [comment] 2015-01-12 16:42
Jep, hadn't noticed the earlier thread.
