### ISSUE TITLE
Atom Helper (Not Responding) 

### ISSUE THREAD

**Issue by sahilbabbar** [atom/atom#5917] opened 2015-03-10 09:05 UTC
Hi,

For the past few months, atom has become extremely slow and after searching for the causes, it was found that processes named *Atom Helper* goes into the state of *Not Responding* after few minutes of starting the editor. These processes consume more than 200 MB of memory and affects the overall Mac's performance. 

![screen shot 2015-03-10 at 2 36 13 pm](https://cloud.githubusercontent.com/assets/6317330/6571864/fae13d2e-c732-11e4-8b63-7981eca1bd8b.png)

How can this be eliminated?

If this continues that probably I would be forced to replace atom with some other editor.

**Comment by 50Wliu** [comment] 2015-03-10 15:19
Duplicate of #3928, please subscribe there for updates.
The helper actually is responding by the way (this bug is merely visual).

**Closed by 50Wliu** 2015-03-10 15:19 UTC
