### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by tylooor** [atom/atom#16800] opened 2018-02-20 22:26 UTC
Atom is flipping out every time I use it. I have uninstalled, reinstalled. I am using the stock version. This is very annoying as I am working on a project for my class and every minute I get 5 identical errors popping up. Literally the exact same error. covering the right side of my screen. Please help 
[Enter steps to reproduce:]

1. use atom ( pops up every now and then)
2. Click on the github desktop GUI guarantees the error pops up every time

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at ~/AppData/Local/atom/app-1.24.0/resources/app/src/path-watcher.js:184:48
    at Array.map (native)
    at handler (~/AppData/Local/atom/app-1.24.0/resources/app/src/path-watcher.js:177:36)
```

### Commands

```
     -1:57.7.0 core:move-left (input.hidden-input)
     -1:57.3.0 core:delete (input.hidden-input)
     -1:55 core:backspace (input.hidden-input)
     -1:48.9.0 core:cut (input.hidden-input)
     -1:17.5.0 editor:newline (input.hidden-input)
     -1:10.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-02-21 20:35
Thanks for the report - we'll go ahead and close the issue since it's a duplicate of https://github.com/atom/atom/issues/14227.

> 1. use atom ( pops up every now and then)

Do you have any more specific details you can share?  E.g. does it pop up at random?  What kind of files are you editing?  Do you see the errors only when working on a specific project?  And can you confirm if you can reproduce the error in safe mode(`atom --safe`)?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-02-21 20:35 UTC
