### ISSUE TITLE
Ubuntu keymap when non-EN keyboard layout active is wrong

### ISSUE THREAD

**Issue by Freezerburn** [atom/atom#9136] opened 2015-10-14 01:44 UTC
When running Atom under Ubuntu (14.04 LTS, I believe) with vim-mode and ex-mode installed and using a JP keyboard layout (see:https://www-01.ibm.com/software/globalization/topics/keyboards/images/fig3_new.GIF) the keys are not mapped correctly. Specifically, in the circumstance that was causing me issue, when I press the : key to bring up ex-mode (which is where ' is for QWERTY layout) nothing happened. When I opened the key binding resolver, I saw that it was being mapped to ;, and I had to press the normal SHIFT+; key combo in order to get Atom to recognize the : key and open ex-mode. Oddly, typing in the code window (and even the ex-mode area) showed the correct keys.

Using Atom on a Macbook with the same JP layout does not exhibit this issue. I have not tested on Windows.

**Comment by mnquintana** [comment] 2015-10-14 01:52
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom-keymap/issues/37 though - please subscribe there for updates.

**Closed by mnquintana** 2015-10-14 01:52 UTC
