### ISSUE TITLE
Pin Atom on taskbar of Windows

### ISSUE THREAD

**Issue by cristianvuolo** [atom/atom#8172] opened 2015-07-31 14:56 UTC
aftertaste when the Atom in the taskbar, a new icon appears and does not keep what already aberdo, when I click the locked icon, a new Atom window opens and the locked icon is sepadado.

I think it would be interesting to open the Atom in the same icon group.

**Comment by mnquintana** [comment] 2015-07-31 15:05
This looks like a duplicate of https://github.com/atom/atom/issues/7374 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-31 15:05 UTC
