### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.49.0\bootstr...

### ISSUE THREAD

**Issue by nazperi** [atom/atom#21106] opened 2020-07-24 19:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Admin\AppData\Local\atom\app-1.49.0\bootstrap-4.5.0-dist'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\Admin\AppData\Local\atom\app-1.49.0\bootstrap-4.5.0-dist'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:943665)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:950838)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:14:924225)
```

### Commands

```
     -9:54.2.0 tree-view:cut (span.name.icon.icon-file-text)
     -9:37.5.0 tree-view:add-folder (div.header.list-item.project-root-header)
     -9:34.4.0 core:confirm (input.hidden-input)
     -9:26.5.0 tree-view:add-folder (div.header.list-item.project-root-header)
     -9:25.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
```

**Comment by aminya** [comment] 2020-07-25 13:04
I cannot reproduce this.

**Comment by sadick254** [comment] 2020-09-15 12:37
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.

**Closed by sadick254** 2020-09-15 12:37 UTC
