### ISSUE TITLE
Ctrl-9 not recognized on macOS 10.12

### ISSUE THREAD

**Issue by kgrossjo** [atom/atom#15381] opened 2017-08-18 20:45 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The keyboard shortcuts ctrl-6, ctrl-7, ctrl-8 and ctrl-9 are not recognized.  By this I mean: I use `cmd-.` to invoke the keybinding resolver.  I hit some keyboard combination, say ctrl-1.  When I press ctrl, the keybindig resolver shows me "ctrl".  When I then hit the 1 key, the display changes from just "ctrl" to "ctrl-1", and underneath the key name, it shows me which command would be executed.

But when I hit ctrl-6, ctrl-7, ctrl-8 or ctrl-9, the keybinding resolver shows me just "ctrl" and never shows me the additional digit.

### Steps to Reproduce

1. Start Atom
2. Invoke keybinding resolver with `cmd-.`
3. Press and then release the `ctrl` key.  Remember what the keybinding resolver shows.
4. Press `ctrl-5`.  Remember what the keybinding resolver shows.
5. Press `ctrl-9`.  Remember what the keybinding resolver shows.

**Expected behavior:** What the keybinding resolver shows after steps 3, 4, 5 should be different.  What it shows after step 4 and after step 5 should be somehow similar.

**Actual behavior:** What the keybinding resolver shows after step 3 and after step 5 is _exactly_ the same.  By this I mean that if you were to take screenshots of the Atom window after these steps, they would be identical, pixel for pixel.

**Reproduces how often:** Always.

### Versions

Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.1

I'm running macOS Sierra 10.12.6..

### Additional Information

Actually, I wanted to complain that keybindings don't work in the github package, until I found out that it's actually the `ctrl-9` keybinding that doesn't give focus to the git tab.  If I invoke the command to focus the git tab from the palette, then I can use keybindings such as cursor up and cursor down.

It occurs to me that macOS might be stealing the keybinding, so I opened System Preferences and did some spelunking in the Keyboard / Shortcuts portion.  I went through all of "Launchpad & Dock", "Mission Control", "Keyboard", "Input Sources", "Screen Shots", "Services", "Spotlight", "Accessibility", "App Shortcuts".  The result is that `ctrl-6` through `ctrl-9` are not mentioned in any of these places.

It occurs to me that FastScripts might be stealing the keybinding, but I don't use these keys there, either.

It's not BetterTouchTool, either.

The activation key for ShortCat is `cmd-shift-space`, so that's not it, either.

I temporarily quit HammerSpoon to make sure that's not the culprit, either.

The only key configured in Bartender is `option-f12`, so that's not it, either.

I think you can tell I'm a keyboard fetishist...

**Comment by rsese** [comment] 2017-08-18 22:27
Thanks for the report - I can't reproduce with Atom 1.19.2 on macOS 10.12.6, `ctrl-9` toggles the Git tab's focus.

> What the keybinding resolver shows after step 3 and after step 5 is exactly the same. By this I mean that if you were to take screenshots of the Atom window after these steps, they would be identical, pixel for pixel.

So after typing `ctrl-5` and `ctrl-9`, the keybinding resolver looks like this in both cases where even when typing `ctrl-9`, the resolver says you typed `ctrl-5`?

![ctrl-5](https://github-slack.s3.amazonaws.com/monosnap/Git__sandboxrobo_2017-08-18_17-20-51.png)

It does sound like you have a handful of keyboard related apps - you mentioned quitting one of them, have you tried temporarily disabling all of them?

**Comment by kgrossjo** [comment] 2017-08-19 15:57
![untitled](https://user-images.githubusercontent.com/211020/29488272-b41241fa-8507-11e7-8b5f-88eb18c5f606.png)

The above is from `ctrl-9`.  As I said, it looks exactly as if I had just pressed and then released `ctrl`.  For reference, the below is from `ctrl-5`:

![untitled 3](https://user-images.githubusercontent.com/211020/29488282-e5954e20-8507-11e7-8c9a-3f48ffacef13.png)

**Comment by kgrossjo** [comment] 2017-08-19 19:02
By quitting lots of programs and by doing `ps uxww | egrep -v ' (/System/|/usr/libexec/|/usr/sbin/)'` and killing those processes, and restarting Atom, I was able to get the desired behavior a couple of times.  But it's not reproducible.  Just quitting Atom and starting it again (from the same command line, repeating the previous command) causes it to stop working.

Very difficult to track down.

**Comment by guylyons** [comment] 2017-08-21 13:41
I've tried reproducing this issue on **macOS 10.12.6** with **Atom 1.19.2** with no success. Keyboard resolver is able to detect `ctrl-1` thru `ctrl-9` without a problem. I don't think this is an issue out of the box.

**Comment by kgrossjo** [comment] 2017-08-21 20:27
I am afraid without a good way to reproduce this, I will have to close the issue.  For me, most of the time, `ctrl-6` through `ctrl-9` fail.  I have gotten `ctrl-9` to work once or twice, but even restarting Atom was sufficient to make it fail next time.  For me it's really frustrating, but I understand that you can't reproduce the problem, and therefore can't help.

**Comment by Ben3eeE** [comment] 2017-08-22 10:12
We have had quite a number of similar reports and every time it has been due to another application that was running in the background and responding to the keystroke. Since you do mention that quitting some applications helped resolve the issue it does seem like this is the case.

Some things to check before closing:

* Do you see any errors in the developer tools console? Warnings or errors when loading keymaps does not always surface to the UI.
* Do you have anything in your personal keymap file?
* What keyboard layout do you use?
* Can you try to change to another keyboard layout and restart Atom?

This would be far fetched but we had one issue with validating keymaps that caused users to be unable to write characters because it was interpreted as a command instead of a character. We have since then fixed the validation for the keymaps so invalid entires like that report are ignored. User keymaps are still loaded in safe mode so it was hard to track down that issue.

**Comment by rsese** [comment] 2018-03-16 22:33
Not sure if you had a chance to try some of the suggestions above ☝️ but we'll close for now since it's nothing something we can reproduce and since for the most part, this type of report is often due to another application responding to the key combination like @Ben3eeE mentions.   We can always re-open if you find the problem is with Atom.

**Closed by rsese** 2018-03-16 22:33 UTC
Labels: more-information-needed
