### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1564Error: Cannot ca...

### ISSUE THREAD

**Issue by claremag** [atom/atom#20143] opened 2019-11-12 20:50 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1564
Error: Cannot call function 'getPosition' on missing remote object 1564
    at throwRPCError (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 1564
Error: Cannot call function 'getPosition' on missing remote object 1564
    at throwRPCError (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/app/static/<embedded>:1:705396)
    at AtomEnvironment.storeWindowDimensions (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/app/static/<embedded>:1:705811)
    at WindowEventHandler.handleWindowBlur (/private/var/folders/qc/snbqzp9s5vz9j_qxrw8f_wbr0000gn/T/AppTranslocation/BECF8C63-CAF8-49DA-A8ED-FD49C6A821D6/d/Atom.app/Contents/Resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -0:35.1.0 editor:toggle-line-comments (input.hidden-input)
     -0:33.7.0 editor:newline (input.hidden-input)
     -0:18.3.0 core:copy (input.hidden-input)
     -0:16.3.0 core:paste (input.hidden-input)
     -0:15.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by darangi** [comment] 2019-11-14 15:43
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

It sounds like the error isn't reproducible for you, but if it is, please let us know the steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed** 2019-11-14 15:43 UTC
Labels: duplicate
