### ISSUE TITLE
Slow start up time launching from Dock or Mission Control 

### ISSUE THREAD

**Issue by jimtryon** [atom/atom#9406] opened 2015-11-03 04:22 UTC
I noticed that when I launch Atom from my applications that the loading time is significantly longer than if I use the command line.  I'm running a 2014 MacBook Pro.  

I've attached a screen shot of Time Cop showing several packages that have added milliseconds to the load time.  Is there any way to speed up Atom without having to disable packages as I use many of the packages on a regular basis?    

<img width="1280" alt="screenshot 2015-11-02 20 06 00" src="https://cloud.githubusercontent.com/assets/8931936/10901180/1ade1ed6-819f-11e5-8940-da45d0ce5bce.png">

**Comment by kepler0** [comment] 2015-11-03 04:26
I'd like to add that we discovered this when looking at Linter Provider Loading Times in #linter on the Atom Slack. It seems to me that this is another issue from launching Atom using the OS X application bundle directly, rather than from the command line.

**Comment by benogle** [comment] 2015-11-04 01:56
In my testing right now on master, there is no difference in speed between launching from the dock, `atom`, or `atom .`.

How many windows is it launching? What does timecop say when launching via `atom` and `atom .` on the command line. Try to have it open the same windows in all cases.

**Comment by jimtryon** [comment] 2015-11-04 04:19
<img width="1280" alt="atom screenshot" src="https://cloud.githubusercontent.com/assets/8931936/10929421/159a5f74-8268-11e5-80e5-5da41a1dacf5.png">
<img width="1280" alt="atom file screenshot 2015-11-03 20 14 52" src="https://cloud.githubusercontent.com/assets/8931936/10929423/15c4c390-8268-11e5-8968-a1c8b0eee75e.png">
<img width="1280" alt="dock screenshot" src="https://cloud.githubusercontent.com/assets/8931936/10929422/15c0c9ca-8268-11e5-921b-cc0196bd6859.png">

**Comment by jimtryon** [comment] 2015-11-04 04:20
The first screenshot is when I ran atom and passed it a file from the command line.  The second screenshot is when I did atom . and the last screenshot is the time it took launching it from dock.

**Comment by thomasjo** [comment] 2015-11-04 09:06
@jimtryon It would be great if you could also just type `atom` as @benogle requested, since that will launch Atom in the same manner as via Dock or Launchpad. Passing it a file or the current directory are essentially the same (perhaps even identical).

**Comment by jimtryon** [comment] 2015-11-04 15:23
<img width="1280" alt="atom screenshot" src="https://cloud.githubusercontent.com/assets/8931936/10942410/e49b4ee4-82c4-11e5-9020-3a22030d8123.png">

It did take longer when I just type atom to launch Atom.

**Comment by thomasjo** [comment] 2015-11-04 15:28
@jimtryon Thanks for that! Seems like there's some additional overhead taking place when deserializing the previous project state. Not really sure why it's this significant though. Hmm.

**Comment by benogle** [comment] 2015-11-04 23:06
There will be fluctuation, and it depends on how many windows + what is open in those windows. Try it a few times with exactly the same configuration. Like:

1. open one window with one file and the the tree view open
1. quit
1. type `atom`
1. note the startup time
1. quit
1. type `atom`
1. note the startup time
1. quit 
1. open from the dock
1. note the startup time
1. quit 
1. open from the dock
1. note the startup time
1. quit 
1. open from the dock
1. note the startup time
1. quit 
1. type `atom .` in the directory for the one window that was open
1. note the startup time
1. quit 
1. type `atom .` in the directory for the one window that was open
1. note the startup time
1. quit 
1. type `atom .` in the directory for the one window that was open
1. note the startup time
1. quit

**Comment by twz915** [comment] 2016-01-14 07:10
Sublime text 3 is much faster than atom. when I open a file, I want to modify it quickly, but Atom keeps me waiting too long. I like Atom and I think it may be much faster to load the text and show at first , and then highlight the code and load plugins.

**Comment by Mauin** [comment] 2016-09-06 13:33
Similarly to this: My Atom startup time (current 1.11.0-beta3) when launching from the Dock takes >60s. Opening Atom via command line both with `atom-beta` and `atom-beta --safe` takes <1s.

I've had this behavior for quite some time just recently started using Atom again to give it another go. Everything is up to date with only one community package installed (intellij-idea-keymap)

**Comment by jiayihu** [comment] 2016-11-06 12:29
I'm having the same issue with Atom v1.11.2 and macOS Sierra 10.12.1:
![schermata 2016-11-06 alle 13 27 01](https://cloud.githubusercontent.com/assets/10067273/20037673/cf746776-a424-11e6-803c-b258fa43bc18.png)
![schermata 2016-11-06 alle 13 27 20](https://cloud.githubusercontent.com/assets/10067273/20037672/cf725e68-a424-11e6-96d7-a554a8c34d68.png)

The first screenshot is with `atom .`, whereas the second is with Atom launched from Dock

**Comment by 50Wliu** [comment] 2016-11-06 15:43
@nathansobo I thought this was fixed in 1.11?

**Comment by thomasjo** [comment] 2016-11-06 15:56
@50Wliu Correct, #12540 shipped in 1.11.

**Comment by jiayihu** [comment] 2016-11-06 19:22
@50Wliu this issue seems a bit different though, because I'm having the opposite problem. Opening Atom from CLI is okay, whereas from Dock takes several seconds.

**Comment by nathansobo** [comment] 2016-11-09 17:05
@thomasjo @50Wliu Yeah I can confirm that the issue @jiayihu is describing differs from the App Nap problem that was delaying launches from the CLI. @jiayihu when launching in these two scenarios, is Atom running already in either case or are both cold-starts?

@bungdonuts when you get a chance, maybe you could see if you can reproduce this timing difference between launching from the Dock and other modes? It's very odd to me that launching via the Dock would take longer than any other approach.

**Comment by jiayihu** [comment] 2016-11-09 20:39
@nathansobo Both cold starts, if you mean that Atom is closed, but the screenshots are taken after several times I tried quitting and opening the editor with the same project.

**Comment by nathansobo** [comment] 2016-11-11 16:56
Figured this out. There was a change to shell out to retrieve environment variables... unfortunately the action is performed synchronously which is blocking startup. We'll fix this. Sorry.

/cc @joefitzgerald

**Closed** 2016-11-11 18:44 UTC
Labels: more-information-needed

**Comment by nathansobo** [comment] 2016-11-11 23:18
This should be fixed in 1.12.2 by making shelling out for the environment asynchronous and giving it a 5 second timeout.
