### ISSUE TITLE
| (pipe) is not possible on a danish keyboard on windows

### ISSUE THREAD

**Issue by dotnetCarpenter** [atom/atom#5253] opened 2015-01-25 19:38 UTC
If I want to write | (pipe), I press AltGr + ´ or in keycodes `17`+`18`+`192`. Possible you could omit `17`.
What happens is that the code block collapse. Since I'm writing javascript, I need to write | on a daily basis.
I couldn't find anything about AltGr on https://atom.io/docs/latest/customizing-atom#customizing-key-bindings

**Comment by 50Wliu** [comment] 2015-01-25 20:53
Duplicate of atom/atom-keymap#35, please subscribe there for updates.

**Closed by 50Wliu** 2015-01-25 20:53 UTC
