### ISSUE TITLE
Uncaught Error: spawn /Users/ilia/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents...

### ISSUE THREAD

**Issue by grayfall** [atom/atom#11135] opened 2016-03-11 13:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/ilia/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/ilia/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/ilia/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/ilia/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:15:15)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:170:22)
    at /Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.setPaths (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:217:27)
    at /Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:184:27
    at Function.module.exports.Emitter.simpleDispatch (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.setPath (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:342:27)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1048:12)
    at TextEditor.module.exports.TextEditor.saveAs (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:636:26)
    at Pane.module.exports.Pane.saveItemAs (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:569:16)
    at Pane.module.exports.Pane.saveItem (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:553:21)
    at Pane.module.exports.Pane.saveActiveItem (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Users/ilia/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:00.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -4:59 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:47.4.0 grammar-selector:show (atom-text-editor.editor)
  4x -3:42.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:39.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:04.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:50.5.0 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
     -0:46.4.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:41.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.2.0 core:close (atom-text-editor.editor.is-focused)
     -0:29 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:22.7.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrapAtPreferredLineLength": true,
    "tabLength": 4,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-03-11 13:55
This is a duplicate of #10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-11 13:55 UTC
