### ISSUE TITLE
Poor RTL support in the main editor.

### ISSUE THREAD

**Issue by abzarak** [atom/atom#15628] opened 2017-09-12 22:59 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Poor support for RTL language.
RTL text is not highlitable.

### Steps to Reproduce

1. type some RTL Language like Arabic or Persian inside a quotation. Like this : "سلام این یک جمله فارسی است".
2. Try to select a word or a phrase from within the quote.
3. Or try to add a new word in the sentence. It's typed somewhere else... [magical] 

### Versions

Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS : Windows 10

**Comment by rsese** [comment] 2017-09-13 18:05
Thanks for taking the time to contribute!  As mentioned below, there are existing issues with RTL text that you can subscribe to if you'd like.

About this part:

> Or try to add a new word in the sentence. It's typed somewhere else... [magical]

Curious if you can share a GIF or screencast of this behavior?  I just want to make sure this has already been captured in an existing issue.

---

We noticed that this is a duplicate of issues like https://github.com/atom/atom/issues/12282, https://github.com/atom/atom/issues/10132, and https://github.com/atom/atom/issues/13612. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by Ben3eeE** [comment] 2017-11-03 22:22
@rsese I am closing this as a duplicate. Let me know if you want to keep this open ✌️

**Closed by Ben3eeE** 2017-11-03 22:22 UTC
Labels: duplicate
