### ISSUE TITLE
ANSI encoding?

### ISSUE THREAD

**Issue by rugk** [atom/atom#8290] opened 2015-08-09 13:58 UTC
Test file: https://gist.github.com/rugk/63e276db7ddcef498008

Steps to reproduce:
1. Create a new TXT file with Notepad++
2. Make sure the encoding is set to ANSI.
3. Paste my test text in it.
4. Save the file.
5. Open it in Atom.

What happens: It will be detected as UTF-8 and displayed completely broken:
![ansiencodingissue](https://cloud.githubusercontent.com/assets/11966684/9155152/cc5f6d24-3eae-11e5-9ff8-c10ff4d7fd12.PNG)

What should happen: Detecting and encoding as ANSI.

Interestingly there is not even any possibility to select ANSI encoding if you click on UTF-8 in the status bar. There is just no entry.

Possibly related issues: https://github.com/atom/atom/issues/7553, https://github.com/atom/atom/issues/8219, https://github.com/atom/atom/issues/7899

**Comment by mnquintana** [comment] 2015-08-09 14:03
Thanks for the report! I think this is a duplicate of https://github.com/atom/atom/issues/4160 though, so I'm gonna close this out in favor of that issue. Let me know if I'm mistaken though.

**Closed by mnquintana** 2015-08-09 14:03 UTC

**Comment by rugk** [comment] 2015-08-09 14:10
No I think you're right.

**Comment by IVIJL** [comment] 2016-02-24 07:15
Still no fix ? As this is big issue that it cannot open ANSI encoded files correctly :(

**Comment by kevincaradant** [comment] 2016-10-06 14:24
Same problem today ? Any news ? I didn't find any plugin for this

**Comment by sangimed** [comment] 2017-03-09 14:46
The latest version still has this issue (version 1.14.4 x64 under windows 7 64bits).
