### ISSUE TITLE
Manipulating the clipboard doesn't work in Russian layout

### ISSUE THREAD

**Issue by qooob** [atom/atom#13626] opened 2017-01-15 10:35 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When keyboard layout switched to `RU` (Russian), _**copy/cut/paste**_ doesn't work as expected.

### Steps to Reproduce

1. Switch to Russian keyboard layout
2. Go to Atom and hit `Ctrl+C` to copy to clipboard

**Expected behavior:** [Text to be copied into clipboard]

**Actual behavior:** [Nothing happens]

**Reproduces how often:** [Always]

### Versions
Atom 1.13 x64
GNU Linux x64 with GNOME

### Additional Information

It works in all other apps with Russian layout.

**Comment by Ben3eeE** [comment] 2017-01-15 10:55
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom-keymap/issues/203. This issue has been fixed in Atom 1.14 currently in beta ✨ 

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-01-15 10:55 UTC
