### ISSUE TITLE
Uncaught Error: Tried to unload active package 'asciidoc-image-helper'

### ISSUE THREAD

**Issue by mikemorrell2** [atom/atom#19186] opened 2019-04-19 15:59 UTC
[Enter steps to reproduce:]

1. Start Gnome Software and Install Atom editor.
2. Launch Atom editor and start adding extensions for asciidoc.
3. Select the asciidoc-image-helper extension to install. Error happens.

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: linux 5.0.7-300.fc30.x86_64
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'asciidoc-image-helper'

```
At /app/share/atom/resources/app/static/<embedded>:11

Error: Tried to unload active package 'asciidoc-image-helper'
    at PackageManager.unloadPackage (/app/share/atom/resources/app/static/<embedded>:11:381635)
    at PackageManager.t.exports.PackageManager.unload (/app/share/atom/resources/app/static/<embedded>:11:916228)
    at PackageManager.t.exports.PackageManager.install (/app/share/atom/resources/app/static/<embedded>:11:916461)
    at PackageCard.install (/app/share/atom/resources/app/static/<embedded>:14:3042255)
    at HTMLButtonElement.installButtonClickHandler (/app/share/atom/resources/app/static/<embedded>:14:3028358)
```

### Commands

```
     -1:07.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.3 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.12.3 
asciidoc-reference-check 0.3.1 
autocomplete-asciidoc 0.1.2 
language-asciidoc 1.11.0 
```

**Comment by rsese** [comment] 2019-04-19 19:32
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16873 so you can subscribe there for updates if you'd like.

Just to clarify this part:

> Launch Atom editor and start adding extensions for asciidoc.
> Select the asciidoc-image-helper extension to install. Error happens.

So you saw the error after a fresh install and then trying to install `asciidoc-image-helper`, or you installed other packages first before installing  `asciidoc-image-helper`?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-19 19:32 UTC
