### ISSUE TITLE
Remove / Collapse Magento project

### ISSUE THREAD

**Issue by SmileyWar** [atom/atom#6999] opened 2015-05-29 03:46 UTC
Removing, collapsing a project in particular a magento installation, crashes Atom.

Very strange, now working with a one massive project folder opened, trying to scroll to my other projects heheh.

**Comment by SmileyWar** [comment] 2015-05-29 03:48
I just discovered the reason, if your folder tree is very deep and you try to collapse the top level tree, it crashes.

If you collapse all the folders one by one, Atom does not crash. So it seems it's handling large amounts of open folders in one parent.

**Comment by lee-dohm** [comment] 2015-05-29 05:48
How many items do you have visible in the top level tree?

**Comment by SmileyWar** [comment] 2015-05-29 05:55
Hi this is the open tree (9)
magento > app > design > frontend > rwd > default > template > catalog > product > view.phtml

I also noticed it's actually happens when I close atom, than reopen, this is when it crashes when I try to close the top level tree.

If I open up the tree and hide the top level tree within the same session (not closing down atom) it works fine.

When I leave the tree open close atom, reopen atom it than crashen when I try to close the top level tree.

**Comment by lee-dohm** [comment] 2015-05-29 05:57
* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by SmileyWar** [comment] 2015-05-29 06:00
Atom 0.204.0
Win 8.1
No I can't reproduce using atom --safe

**Comment by lee-dohm** [comment] 2015-05-29 06:22
Given that you can't reproduce this when using `atom --safe`, it looks like it is probably a third-party package issue. What packages do you have installed? You can get the list at the command line with `apm list`.

**Comment by SmileyWar** [comment] 2015-05-29 07:18
The command line thing is beyond my knowledge.

But here is the list of community packages

autocomplete-paths
remote-edit
todo-show

**Comment by lee-dohm** [comment] 2015-05-29 12:42
If you disable the remote-edit package, can you reproduce the issue?

**Comment by SmileyWar** [comment] 2015-05-30 05:45
Now it does not remember the open project folders, so I can't reproduce it. Is this a setting?

Every time I close Atom, than reopen I need to add the project folders again.

**Comment by SmileyWar** [comment] 2015-06-01 03:08
I think a restart resolved above message.

This has been resolved. It was indeed the remote-edit.

Thank you for your help.

**Comment by kevinsawicki** [comment] 2015-07-29 17:22
Looks like this was a third-party package issue since it wasn't reproducible using `atom --safe`, so I'm going to close this out.

Please comment if you still think this is a core Atom issue and if you are still experiencing it with Atom 1.0.3+.

**Closed by kevinsawicki** 2015-07-29 17:22 UTC
Labels: more-information-needed, needs-reproduction
