### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by rst0git** [atom/atom#12078] opened 2016-06-30 22:19 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
     -1:59.5.0 core:save (input.hidden-input)
     -1:43.9.0 core:undo (input.hidden-input)
     -1:42.7.0 core:save (input.hidden-input)
  2x -0:03.7.0 core:close (input.hidden-input)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "followSymlinks": false,
    "packagesWithKeymapsDisabled": [
      "grammar-selector"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 13,
    "invisibles": {},
    "useShadowDOM": false,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
language-scala, v1.1.6

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2016-07-01 04:46
Duplicate of https://github.com/atom/atom/issues/11692?

**Closed** 2016-07-01 20:41 UTC
