### ISSUE TITLE
Strange behaviour deleting over character

### ISSUE THREAD

**Issue by cobyism** [atom/atom#579] opened 2013-06-09 20:23 UTC
I was editing a file and noticed this wee oddity.

![atom-weird-delete-behaviour](https://f.cloud.github.com/assets/296432/629261/bd51c776-d139-11e2-9de1-ce1bce8addcc.gif)

Note that the caret position after backspacing is one column to the left of where it should be. The number of spaces is correct, and the positions correct themselves as soon as you type another character, and that it’s not any special characters either—it’s doing it with (at least) `=` and `#`.

**Comment by mnquintana** [comment] 2015-04-13 20:03
Still happens on 0.190.0

**Comment by mnquintana** [comment] 2015-06-20 11:08
I'm actually not sure this is a bug - this happens when the `editor.tabLength` is `2`. By default, Atom treats soft tabs as "one" character when moving the cursor with the keyboard - ie. you can't place the cursor in the middle of a soft tabs "character", even if it's made up of multiple individual space characters. So in this example, the code is indented by 1 space and there's a space after the `#`, but soft tabs is set to 2. When the `#` character is deleted, that leaves two spaces - a soft tab. Since Atom won't place the cursor in the middle of a soft tab unless you explicitly click there, it shifts it to the left. I actually think this is intended behavior given the way soft tabs are treated.

**Comment by revelt** [comment] 2016-11-20 14:26
Hi all, I can't recreate this issue and I have `tabLength=2` (which is default). Please confirm can you see this still happening.

**Comment by Ben3eeE** [comment] 2016-11-20 18:53
I can still reproduce this with the information from @mnquintana. But not sure if it actually is a bug, seems to be the intended behavior. If you disable `Atomic Soft Tabs` it stops happening.

**Comment by revelt** [comment] 2016-11-20 19:23
Aha! The GIF's above are scary, glad it's not happening on my Atom ;)

**Comment by Ben3eeE** [comment] 2016-11-20 19:37
The gif by @jlord is another issue.

**Comment by mnquintana** [comment] 2016-11-21 18:09
I'm going to close this out since this still seems like expected behavior, and can be disabled by disabling `Atomic Soft Tabs`.

**Closed by mnquintana** 2016-11-21 18:09 UTC
