### ISSUE TITLE
apm install partial code trace

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#10005] opened 2015-12-10 18:06 UTC
Atom: v1.4.0-beta0
OS: Windows 10 x64

I'm seeing the following when installing packages:
```
C:\path> apm install linter
Installing <package> to C:\Users\Landon Abney\.atom\packages
C:\Users\Landon Abney\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:163
let prepareStackTrace = prepareStackTraceWithSourceMapping
^^^
done
```

Unfortunately that is all the output, it looks like it is pointing to [this line](https://github.com/atom/atom/blob/v1.4.0-beta0/src/compile-cache.js#L163), but beyond that I'm not sure what is going on as it seems to install the package properly.

I did not see this in v1.3.0-beta6, and I'm pretty sure beta7 was fine as well.

**Comment by mnquintana** [comment] 2015-12-10 18:21
Thanks for the report! This looks like a duplicate of https://github.com/atom/apm/issues/476 – let's keep the discussion going there.

**Closed by mnquintana** 2015-12-10 18:21 UTC

**Comment by Arcanemagus** [comment] 2015-12-10 18:28
Whoops, really should have thought to search there. Thanks for pointing me over there!
