### ISSUE TITLE
Right clicking on text document content causes 'hang message

### ISSUE THREAD

**Issue by dodwmd** [atom/atom#12626] opened 2016-09-08 03:06 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

If you open a file, right click on the contents of the opened file. Wait less than a minute it will cause a 'Atom has crashed' message to pop up and a option to wait. Clicking wait unsticks the application.

### Steps to Reproduce

1. open txt file
2. right click on contents of file
3. stare at the dialog window (showing undo/redo etc) for a minute
4. see 'warning' able application being unresponsive

**Expected behavior:** Nothing

**Actual behavior:** See above

### Versions

Atom    : 1.10.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.12.5
npm  3.10.5
node 4.4.5
python
git 1.9.5.msysgit.0
visual studio

Windows 7 SP1

**Comment by Ben3eeE** [comment] 2016-09-08 05:23
Duplicate of https://github.com/atom/atom/issues/11901

**Comment by 50Wliu** [comment] 2016-09-08 14:00
Feel free to subscribe to #11901 for updates.

**Closed by 50Wliu** 2016-09-08 14:00 UTC
Labels: duplicate
