### ISSUE TITLE
Unable to rename files with long names

### ISSUE THREAD

**Issue by markoa** [atom/atom#10587] opened 2016-01-26 10:32 UTC
Given a filename of more than a handful of characters, I am not able to rename it, because I am not able to scroll horizontally to the end of the name.

Here's a screenshot. It shows the maximum length of highlighting or scroll movement that I can do.

![screen shot 2016-01-26 at 11 26 20](https://cloud.githubusercontent.com/assets/8651/12578309/547dbdea-c420-11e5-867b-81580f9cb341.png)

**Atom version:** 1.4.0
**OS and version:** OS X El Capitan

**Installed packages:**

- wordcount
- git-plus
- tag (all disabled)

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by kazdegroot** [comment] 2016-01-26 13:07
Have the same problem, with every function that uses that UI, including the New File and New Folder contextual menu items.

**Comment by 50Wliu** [comment] 2016-01-26 16:27
This is a duplicate of atom/tree-view#473 - please subscribe there for updates.

**Closed by 50Wliu** 2016-01-26 16:27 UTC
