### ISSUE TITLE
Snippet adds extra spaces if the snippet starts with spaces

### ISSUE THREAD

**Issue by VanVeenGames** [atom/atom#10696] opened 2016-02-05 02:23 UTC
The fix will probably have to be hard-coded, but here's the issue:

If you have a snippet with a body like this:
`$1.$2 = function ($3) {\n\t\n\t$4\n\t\n};`
It works fine. But, if your snippet has a space directly after a selector ($):
`$1 = function ($2) {\n\t\n\t$3\n\t\n};`
Then the whole block of lines of code all get a space inside the tabs.

Presumably also occurs if the snippet starts with a space.

**Comment by deadeyejoe** [comment] 2016-08-24 14:05
I'm encountering this issue, here are steps to reproduce:

Any multiline snippet that starts with a selector ($n) followed immediately by 'x' number of spaces will add  x spaces to the beginning of each line in the snippet.

More concretely, the snippet:
```
$1  = (arg1, arg2) ->
  return null
```
(note there are **two** spaces between '$1' and '=') will expand to:
```
  = (arg1, arg2) ->
    return null
```
there are now a total of 4 spaces before `return null` but I would expect it to expand to:
```
 = (arg1, arg2) ->
  return null
```
(i.e. 2 spaces before `return null`)

If the selector is followed by any other character, this doesn't happen.

I hope this is clear, let me know if I can provide any more information

**Comment by VanVeenGames** [comment] 2016-08-24 15:28
Yes that's the exact same issue. _I hereby welcome you to my newly discovered planet, being this issue, on which I lived alone for so long I almost forgot what a face was._ (Just to be clear, the Atom team is awesome, this is not a complaint for it taking too long _at all_; _no sarcasm_).

**Comment by 50Wliu** [comment] 2016-08-25 16:27
This is a duplicate of atom/snippets#195 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-25 16:27 UTC
Labels: needs-reproduction
