### ISSUE TITLE
`Uncaught TypeError: Cannot read property 'length' of undefined due to text-editor-component.js:2286:3

### ISSUE THREAD

**Issue by tywang2006** [atom/atom#15258] opened 2017-08-11 10:57 UTC
I just fresh hot issue again, as request, i open this new ticket for you

`Uncaught TypeError: Cannot read property 'length' of undefined
C:\Users\chao.wang\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2286
Hide Stack Trace
TypeError: Cannot read property 'length' of undefined
    at TextEditorComponent.screenPositionForPixelPosition (C:\Users\chao.wang\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2286:33)
    at HTMLElement.screenPositionForPixelPosition (C:\Users\chao.wang\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-element.js:247:32)
    at TextEditor.module.exports.TextEditor.screenPositionForPixelPosition (C:\Users\chao.wang\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor.js:3658:38)
    at showExpressionType (C:\Users\chao.wang\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:52:31)
    at C:\Users\chao.wang\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:41:59
The error was thrown from the atom-typescript package. This issue has already been reported.`

It is latest version Atom 1.19.0 ia32. that is not beta version. I got it from automatic update. in the previous version, the same project works well and not issue thrown, it happened very frequently in this version.

**Comment by whqkdhfh13** [comment] 2017-08-15 12:31
Same issue.

Uncaught TypeError: Cannot read property 'length' of undefined
```
C:\Users\owner\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2286
````
TypeError: Cannot read property 'length' of undefined

    at TextEditorComponent.screenPositionForPixelPosition (C:\Users\owner\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2286:33)

    at TextEditorComponent.screenPositionForMouseEvent (C:\Users\owner\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:1878:23)

    at TextEditorComponent.didMouseDownOnContent (C:\Users\owner\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:1694:39)`

**Comment by Ben3eeE** [comment] 2017-08-15 13:10
@tywang2006 @whqkdhfh13 Can you update to Atom 1.19.1 to see if that resolves the issue? We fixed some regressions in the editor in that hotfix release.

**Comment by tywang2006** [comment] 2017-08-15 16:03
I did get new updated from automatically update. Our company IT policy doesn't give me admin, so it is only way to update from automatically update:d

**Comment by tywang2006** [comment] 2017-08-16 11:00
I just found my version was updated to 1.19.1. so far it seems to have no error raised. I guess it has been fixed on this version. thanks mate

**Comment by Ben3eeE** [comment] 2017-08-16 11:02
@tywang2006 Thank you for the update :bowing_man:  I am going to close this since it looks like it has been fixed but if you run into this again then please comment with the full stack trace and I can reopen.

**Closed by Ben3eeE** 2017-08-16 11:02 UTC
Labels: more-information-needed, needs-reproduction, regression

**Comment by lwasser** [comment] 2017-08-30 01:13
hi there. i am getting this error with atom 1.19.4

**Comment by Ben3eeE** [comment] 2017-08-30 06:31
@lwasser Can you please open a new issue with the full stack trace and steps to reproduce, thank you :bowing_man:
