### ISSUE TITLE
"Use preview tabs" option not available in latest (0.104.2) version of tabs?

### ISSUE THREAD

**Issue by ddavison** [atom/atom#14291] opened 2017-04-24 22:01 UTC
_From @djoaquing on April 24, 2017 20:51_

Title. I'd like to only permanentely open a tab if i double click it, otherwise that it acts as a "preview".

Thanks.

_Copied from original issue: ddavison/sublime-tabs#135_

**Comment by rsese** [comment] 2017-04-25 00:29
Thanks @ddavison :bow:

@djoaquing - this option was renamed to "Pending Pane Items" and is in `Settings > Core` /cc https://github.com/atom/tabs/issues/288#issuecomment-199956018.

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of 
https://github.com/atom/tabs/issues/288.  Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-25 00:29 UTC
