### ISSUE TITLE
Menu bar shortcut keys and navigation issues

### ISSUE THREAD

**Issue by bminer** [atom/atom#6475] opened 2015-04-22 13:30 UTC
There a few issues with the menu bar in Atom.

Even though `Alt + E` opens the Edit drop down menu...
- `Alt + H` - does not open the Help drop down menu
- `Alt + F` - does not open the File drop down menu

Also...
- While a drop down menu is displayed (i.e. by pressing `Alt + E` or clicking to open the menu), the Left/Right arrow keys do not move to the previous/next menus.  Up/Down arrow keys move up/down within the menu, but Left/Right do not work as expected.  Generally, Left/Right can be used to expand/collapse a submenu, but when there is no submenu to the Left/Right to expand/collapse, the keys should navigate to the previous/next menu as you would find in many other applications that utilize a conventional menu bar.

**EDIT**: Bug is present in Atom 0.194, Linux Mint 17

**Comment by 50Wliu** [comment] 2015-04-22 16:39
Duplicate of #4057, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-22 16:39 UTC
