### ISSUE TITLE
Uncaught Can't find   background-repeat: no-repeat; file

### ISSUE THREAD

**Issue by javiquer** [atom/atom#18487] opened 2018-11-24 01:41 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find   background-repeat: no-repeat;
 file

```
At C:\ProgramData\Javique\atom\app-1.32.2\resources\app\static\<embedded>:11

undefined
```

### Commands

```
     -4:28.4.0 core:save (input.hidden-input)
  2x -4:23.5.0 core:move-left (input.hidden-input)
     -4:22.3.0 core:save (input.hidden-input)
  8x -4:19.4.0 core:undo (input.hidden-input)
     -4:15.5.0 core:redo (input.hidden-input)
     -4:14.4.0 core:undo (input.hidden-input)
  9x -4:12.4.0 core:redo (input.hidden-input)
  3x -4:06.7.0 core:backspace (input.hidden-input)
  2x -4:05.9.0 core:delete (input.hidden-input)
     -4:03.3.0 core:save (input.hidden-input)
  2x -1:57.5.0 core:backspace (input.hidden-input)
     -1:40.6.0 core:save (input.hidden-input)
  2x -0:21.3.0 emmet:encode-decode-data-url (input.hidden-input)
     -0:15.9.0 key-binding-resolver:toggle (input.hidden-input)
     -0:02.2.0 editor:toggle-line-comments (input.hidden-input)
     -0:00.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
emmet 2.4.3 
styri-syntax 1.0.0 
teletype 0.13.3 
```

**Comment by rsese** [comment] 2018-11-27 03:53
Thanks for contributing!

We noticed that this looks like a duplicate of issues like https://github.com/atom/atom/issues/18429 where it seems like the problem was narrowed down to https://atom.io/packages/emmet.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-27 03:53 UTC
