### ISSUE TITLE
Task switching on Windows is slow

### ISSUE THREAD

**Issue by ile** [atom/atom#9971] opened 2015-12-07 21:09 UTC
When switching the active window with Alt-Ctrl, it often happens that nothing happens. This is because I'm used to task switching happen fast (instantly), but with Atom, it happens is that there is often maybe a 0.3 - 0.5 second delay until the "tasks dialog" (the dialog that contains task icons) appears.

So, in normal use switching task feels very unrealible - the task isn't often switched at all, since the dialog didn't appear fast enough.

Not sure if there is a fix for this or if this is because of the runtime used. Using Win 7 64-bit.

**Comment by ile** [comment] 2015-12-25 02:17
Actually a lot of other things are slow too. Not sure if there is a work around for this.

Have to switch to another editor unfortunately.

**Comment by damieng** [comment] 2016-04-13 19:35
Suspect this is a dupe of https://github.com/atom/atom/issues/8451 will track it there.

**Closed by damieng** 2016-04-13 19:35 UTC
Labels: needs-reproduction, windows
