### ISSUE TITLE
Can't open files from application's menus

### ISSUE THREAD

**Issue by Karunamon** [atom/atom#8079] opened 2015-07-25 17:28 UTC
[Video Recording](http://gfycat.com/MixedFineFinwhale)

## Repro Steps

1. Start Atom in safe mode (cli: `atom --safe`)
2. Attempt opening a file or folder by file->open or by `application: open file` from the cmd-shift-P menu

**Expected:** File Opens.
**Actual:** Open dialog gets stuck on screen, file does not open.

## Versions

* **Atom:**       1.0.2
* **Atom-Shell:** 0.22.3
* **OS:**         Mac OS X 10.11 (Note: This is public beta 2)
* **Misc**
    * Could not determine apm version information

## Other info

This also happens when trying to do "add folder to project". It's as if all file handling functionality is almost completely broken. Only way to get files into the editor right now is to go to the CLI and do `atom filename` - which works, but is annoying :)

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by 50Wliu** [comment] 2015-07-25 18:45
Duplicate of #7811; please subscribe there for updates.

**Closed by 50Wliu** 2015-07-25 18:45 UTC
