### ISSUE TITLE
Compiling Atom to ARM

### ISSUE THREAD

**Issue by tomhala** [atom/atom#20288] opened 2020-01-01 14:53 UTC
Can you please compile Atom to ARM architecture, because I and others want run Atom on Raspberry Pi

**Comment by Arcanemagus** [comment] 2020-01-02 16:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15881. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-01-02 16:54 UTC

**Comment by brenovieira** [comment] 2020-06-11 18:59
arm version of Atom would be perfect.. commenting here as the original PR is already closed by the bot :)
