### ISSUE TITLE
Check for updates doesn't work (on Mac?)

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#13804] opened 2017-02-13 12:59 UTC
# **THIS ISSUE IS NOT ABOUT PACKAGE UPDATES**
Rather, it has to do with updating Atom itself.  Please create a new issue if you are having trouble updating packages.

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Clicking on the "Check for updates" option in Atom's "About" dialog says that there are no new updates, but at the moment of writing this, there are (I'm using 1.14 and 1.14.1 was released 4 days ago).

### Steps to Reproduce

1. Open "About" dialog
2. Click on "Check for updates"

**Expected behavior:** A message should tell me there is an update.

**Actual behavior:** A message tells me there are no updates.

**Reproduces how often:** 100%

### Versions

Atom 1.14 on Mac OS Sierra 10.12.3

### Additional Information

N/A

**Comment by chadwtkns** [comment] 2017-02-14 15:58
Not sure if the issue described above is the same but when I go to the updates tab I see the following error.

<img width="1168" alt="screen shot 2017-02-14 at 8 55 29 am" src="https://cloud.githubusercontent.com/assets/5611546/22936663/7326af7a-f293-11e6-8fba-a4bfda185fae.png">

### Versions
Atom 1.14.1 on Mac OS X El Capitan 10.11.6

**Comment by girlandhercode** [comment] 2017-02-14 16:00
Happening to me also but i'm on Windows 10 Home at the moment.

![image](https://cloud.githubusercontent.com/assets/2183606/22936847/b5a3304c-f2a4-11e6-827f-8682344cf119.png)

**Comment by alexandernst** [comment] 2017-02-14 16:05
No, those issues are not related. I'm talking about Atom updates, not about packages/themes updates.

**Comment by 50Wliu** [comment] 2017-02-14 16:20
@chadwtkns @girlandhercode Uninstall seti-syntax/seti-ui.  Those themes are causing issues at the moment and we're not yet sure if it's an issue with apm or with Seti.

@alexandernst Is your account an Administrator account?

**Comment by alexandernst** [comment] 2017-02-14 16:22
@50Wliu yes

**Comment by girlandhercode** [comment] 2017-02-14 16:25
@50Wliu This worked for me. This theme was uninstalled via the GUI previously and was not listed in the drop down for available themes when I checked before running the `apm uninstall` this morning.  I still had to manually run the `apm uninstall seti-syntax` command (which returned `done` - or something analogous) to fix the issue. Thanks!!!!

**Comment by angularcircle** [comment] 2017-02-23 13:21
The same issue happens on Linux (Atom v1.14.2) so it looks that all OS are affected (not Mac only). As advised - removing Seti-UI solves the problem.

**Comment by alexandernst** [comment] 2017-02-23 13:23
Please don't hijack my original issue with the Seti-UI issue. This is not what my issue is about.

**Comment by angularcircle** [comment] 2017-02-23 14:31
Sorry about that @alexandernst 

Maybe try to reinstall manually latest version and check whether problem is still valid for newer releases.

**Comment by Jnull** [comment] 2017-02-23 15:14
I'm on Atom Version 1.14.1 on Mac Version 10.12.3 and the latest version should update to 1.14.3. If automatic updates are disabled it shows no updates are available same as originally reported. 

If automatic updates are enabled, after Atom starts up about 30secs to 1min the status in the Top-left 'Atom' Drop-down goes from "Check for Updates" to "Downloading" to "Restart and Install Updates".   
Between the "Downloading" to "Restart and Install Updates" status a popup for credentials shows for running an install helper, after clicking that, Atom closes but never restarts, upon manually starting Atom again that scenario happens over and over.  

I've tried safe mode, disabling community packages, and running Atom with root with and w/o '--dev' flag. When i disabled almost all core packages i stopped receiving the install help dialog even after enabling all core packages again.  The last thing i did before i wrote this is restarted my mac and tried one last time, after this i'm probably going to switch to the beta version.

**Comment by pustovalov** [comment] 2017-03-06 23:59
the same problem:

![](https://monosnap.com/file/jwK37CNMdlfigS2WKCyBV1wuyIx3b7.png)

but now the latest version is v1.14.4

OS: Mac OS Sierra 10.12.3

**Comment by maurelian** [comment] 2017-03-07 02:48
I had this issue, I believe because I had originally not placed the atom.app file in the /applications.

Uninstalling and reinstalling fixed this. I used the [sync-settings](https://github.com/atom-community/sync-settings) package to ensure that my settings were maintained and it worked perfectly.

**Comment by pustovalov** [comment] 2017-03-07 11:45
My Atom right now in /applications, I have this problem for a long time, I just downloaded new version from site and replaced the current version

**Comment by Jnull** [comment] 2017-03-11 16:21
<img width="809" alt="screen shot 2017-03-11 at 8 18 29 am" src="https://cloud.githubusercontent.com/assets/3529087/23824859/9cc6d0b8-0633-11e7-8437-17009684cf1c.png">

beta also - "Restart and Install" closes Atom, but does not Restart or Install the new version.

**Comment by kidpollo** [comment] 2017-03-27 05:04
Still happening here btw and I dont have the Seti-ui packages 
![screenshot 2017-03-26 21 21 36](https://cloud.githubusercontent.com/assets/8182/24341672/2c4b70fc-1270-11e7-9be0-13b9bb5ab70e.png)

**Comment by saravntbe** [comment] 2017-03-27 05:27
i am also having the same issue in ubuntu.i uninstalled old one and freshly installed atom 1.15.0 with no third party packages
![screenshot from 2017-03-27 10-51-50](https://cloud.githubusercontent.com/assets/2472415/24342070/1ba0673c-12dc-11e7-92db-7db91f398f17.png)
![screenshot from 2017-03-27 10-51-32](https://cloud.githubusercontent.com/assets/2472415/24342075/22eb01f0-12dc-11e7-8fa4-fc0ee3adfeed.png)

.but same problem exist(i also run in safe mode but no use)

**Comment by sjclark** [comment] 2017-03-30 01:56
I had this problem until I uninstalled Seti-UI & Seti Syntax; following the suggestion above
`apm uninstall seti-syntax && apm uninstall seti-ui`

**Comment by alexandernst** [comment] 2017-03-30 01:58
Please stop hijacking this issue with the seti-stuff issue. PLEASE.

**Comment by sjclark** [comment] 2017-03-30 02:02
@alexandernst just because it didn't solve the problem for you does not mean it's not a valid solution. Clearly the references above ( @angularcircle @girlandhercode etc) to the problem indicate that this IS a fix to the problem for many people. At the very least it's an indication that it's problems with plugins - disable them all and re-enable until you can re-produce it. Regardless, this thread has 18 posts, not worth caps about pollution. Best of luck

**Comment by alexandernst** [comment] 2017-03-30 02:06
The issue (which I opened) is about Atom not finding updates of Atom, not
about the package manager in Atom not finding updates of packages. If
you're having a problem with the package manager in Atom not finding
updates for packages, open a new issue. So, once again, PLEASE stop
hijacking my issue about Atom not finding updates of Atom.

**Comment by Jnull** [comment] 2017-03-30 02:45
I've already removed all packages, reset defaults, and reinstalled manually to the latest build, this did not fix the problem. Lets not clip at each other, we all care about atom enough to report something, lets work together to diverge unrelated issues. Technically speaking this is a minor bug, we all can just manually upgrade, but i think the frustration is geared towards lack of official response for a problem that seems like it could get worse if nothing is done soon.

**Comment by 50Wliu** [comment] 2017-03-31 02:08
Created an h1 header at the top of the issue.  We'll see if that helps.

@joshaber how would you recommend diagnosing this issue?

**Comment by joshaber** [comment] 2017-03-31 15:54
I don't recall how Atom's logging is setup, but it's be interesting to know if `autoUpdater` is logging any errors anywhere.

**Comment by Jnull** [comment] 2017-03-31 20:44
I believe this is same as this #2860

**Comment by 50Wliu** [comment] 2017-03-31 20:55
@alexandernst has stated that he is using an Administrator account, so #2860 wouldn't apply here.

**Comment by Jnull** [comment] 2017-04-01 11:41
as far as i have read in 2860, it doesn't matter if you are admin or not, its due to Squirrel.Mac having a bug, and even if you are a non-admin, atom will prompt for an admin account authentication anyways and still fail after that. 

@50Wliu, is there any way, in any situation, that the update functionality will succeed on mac? if so, what do you do without manually downloading and installing directly from the site?

**Comment by pustovalov** [comment] 2017-04-01 12:52
Can I somehow turn the debug mode to update? In the developer tools there are no requests when I press the update button

**Comment by 50Wliu** [comment] 2017-04-02 01:46
I don't use a Mac, so I have no clue.  However, the general consensus appears to be that the auto-update functionality works fine if you are running Atom from an Administrator account.

**Comment by Jnull** [comment] 2017-04-02 02:03
@50Wliu that wasn't my question, but can you elaborate on general consensus?

**Comment by madrussa** [comment] 2017-04-25 07:43
Hello, I'm on _MacOS 10.12.4_ (admin user) and _Atom.io 1.15.0_ and unable to update. Each time it says 1.15.0 is the latest version... which is sad because all the blog posts about the latest version look just swell. Anyhoo, I've manually installed version 1.16.0 (which is as swell as the blog indicated) and I'm now up to date. However there does seem to be an issue with the updater... I'll keep an eye on the release versions and give feedback; if replacing the app fixed this issue for good or if it continues. Just thought I'd highlight that there is still an update issue present in version 1.15.0.

**Comment by 50Wliu** [comment] 2017-04-25 13:37
@Jnull whoops, missed your last comment.  By "general consensus" I mean that out of all the Mac users (http://blog.atom.io/2016/05/06/two-years-open-source.html) there have only been a [handful](https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aauto-updater%20label%3Amac) of auto-update related issues, most of which are related to permission issues.  Therefore, it would appear that for most Administrator users, auto-updating is working as expected.

@madrussa Did you ever check for updates in the About page?  If so, was there an error?

**Comment by madrussa** [comment] 2017-04-25 15:18
@50Wliu Yes, it didn't report any errors. I was also checking the console and I didn't see any issues.

**Comment by 50Wliu** [comment] 2017-04-25 15:27
So it just said "Atom is up to date!"?

**Comment by madrussa** [comment] 2017-04-25 15:28
@50Wliu Yes, it had the same result as checking from the toolbar.

**Comment by ungb** [comment] 2017-05-02 22:20
I was able to find this discuss post here: https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054 (thanks @lee-dohm for providing it). 

 @alexandernst, I know the message you are getting that you have latest when there is indeed a newer version of Atom available.  I'm wondering if the solution from the Discuss post might solve your issue if you can give it a try.

**Comment by gigmaps** [comment] 2017-05-16 21:56
I get the same issue - except slightly more frustratingly I have the little blue squirrel at the bottom right telling me that there's a Atom core update to apply - even when the `Atom / About` dialog tells me no update available (as well documented above). ...so Atom core knows there's an update to apply but something is blocking both the auto download (see below) and the manual checking via the `Atom / About` menu.

The only way to apply the update is to quit & restart - which starts the automatic download process - as set in my `Preferences / Core / Automatically Update` settings.  This then gives me the expected `Atom \ Restart and Install Update` menu option.

Interestingly auto core updates worked fine initially - but stopped working ~6-9 months ago.

**Comment by madrussa** [comment] 2017-05-17 12:23
As 1.17 has been released I thought I'd update you guys. I usually keep atom.io running on my Macbook for days, sometimes weeks, and only restart every now and then (might be relevant). 

Today I saw the release 1.17 and I ran the "Check for Update" from the toolbar and the about page, both stated that there were no new updates... curious, this is the same [issue as I had before](https://github.com/atom/atom/issues/13804#issuecomment-296945342). Then I noticed the little blue Squirrel in the corner and he told me in good faith that there were updates? I then restarted Atom and got the following prompt:
![image](https://cloud.githubusercontent.com/assets/1470257/26152902/ed50873e-3b00-11e7-968f-d8bbf2f601e6.png) 
I clicked on ok and then the about page was shown (as it was open before I restarted). At that point I saw it had found an update and was downloading it, this was confirmed by the same message as in the toolbar. It downloaded the update and asked me to restart. I restarted Atom as asked and I am now running 1.17, which is great. 

This is better than before when I tried updating from 1.15 to 1.16 where no amount of restarts resulted in it getting any updates. However it's not as seamless as it was before 1.15 where it worked first time without having to restart.

**Comment by rahlzel** [comment] 2017-05-21 23:55
This seems to be a duplicate of #8265, which was first opened in 2015, making this a very old problem.

**Comment by neilgee** [comment] 2017-05-26 20:31
Still an issue for me on macOS 10.12.13 on Atom 1.17.x - `There was an error checking for updates`

By recursively changing ```/Application/Atom``` ownership to either ```root:wheel``` or  ```user:staff``` or ```user:admin``` or ```root:admin``` still doesn't fix the issue for me

**Comment by michaelfich** [comment] 2017-05-30 20:27
This is occurring for me as well.  I'm on version `1.17.0` and cannot update to the latest; `1.17.2`

**Comment by UltCombo** [comment] 2017-06-11 01:52
> This is occurring for me as well. I'm on version 1.17.0 and cannot update to the latest; 1.17.2

Same is happening for me. The "Check for Update" menu as well as the About tab's "Check now" button say Atom is up to date, although I'm still on 1.17.0. As an added bonus, there's an error message in the screen saying my Atom is out of date and should be upgraded. 😅 

![screen shot 2017-06-10 at 22 35 21](https://user-images.githubusercontent.com/2090712/27007596-57d583d0-4e2e-11e7-957b-350fe3f4866f.png)

I had the `seti-icons` package installed, uninstalled it, quitted Atom (cmd+Q), restarted it and I'm still unable to update. Now I'm getting the same error message as @madrussa.

**Comment by neilgee** [comment] 2017-06-18 02:09
Got this working on macOS by disabling SIP and changing ownership of Atom in Applications directory
```
sudo chown -R $(whoami) /Applications/Atom.app/
sudo chown -R $(whoami) ~/Library/Caches/com.github.atom.ShipIt/
sudo chown -R $(whoami) ~/Library/Application\ Support/com.github.atom.ShipIt/
```

**Comment by nakulm95** [comment] 2017-08-09 22:25
Running into the same issue here. Currently on MacOS Sierra v10.12.6, atom v1.18.0 trying to update to v1.19.0. On the "About Atom" page, I see there is an update available so atom downloads the update, then a dialog pops up asking my account password so atom can download a helper. After inputting the password, I click on "restart and install" from the About page and when I open Atom again, I see this: 
![image](https://user-images.githubusercontent.com/7410988/29146611-e0cf218e-7d16-11e7-891a-e189ace718b8.png)

**Comment by jonnylink** [comment] 2017-08-13 13:02
I was having this issue as well. What was odd for me was that Atom just updated on my work computer which has the same settings, packages, atom version, MacOS version (etc). 

### What solved it for me:
- close each tab
- quit the app
- open the app
I suspect this has something to do with the mac resume function that autosaves app state when quitting, but that's just a guess.

**Comment by danqing** [comment] 2017-09-10 07:13
My behavior is the following:

* I see the squirrel icon that tells me that there's a new version
* I click on it, but the about page says I'm on the latest version (I'm not)
* I check for update, and it says I'm on the latest version
* I restart Atom, and I see the "there was an error checking for updates" popup
* I check for update, this time it checks update just fine

However, if I check for update immediately after a new version is released (i.e. before I see the squirrel), it will download the update just fine.

**Comment by drorata** [comment] 2017-09-10 16:09
The behavior I encounter is:

- squirrel is blue
- clicking on it and and `About` tab opens
- In this tab the newer version is downloaded. (1.19.7)
- When completed, I can click `Restart and install`
- Clicking closed Atom and nothing happens afterwards.
- When opening Atom manually, I see the lovely message: 
<img width="446" alt="screen shot 2017-09-10 at 18 07 27" src="https://user-images.githubusercontent.com/2905978/30250677-004335dc-9653-11e7-9cd6-5083fc62a389.png">

The only way I managed to update Atom so far is to download the newer version manually and replace the old one with it.

**Comment by lee-dohm** [comment] 2017-09-11 03:01
@danqing @drorata Try the instructions here in the [Atom FAQ](https://discuss.atom.io/c/faq): https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054

**Comment by lee-dohm** [comment] 2017-09-11 03:05
As far as I can tell, the only cause for this anymore is due to the permissions problem that is solved by [following the instructions](https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054) that have been posted now multiple times. Since this isn't a bug in Atom and is related to a permissions issue that is typically caused by installing as a different user, I'm going to close this issue.

If anyone continues to run into a problem like this, please follow the instructions. If that still doesn't fix it, please open a _new_ issue and fill in all of the information in the template.

**Closed by lee-dohm** 2017-09-11 03:05 UTC
Labels: auto-updater, mac, needs-reproduction, triaged

**Comment by zhouyu1993** [comment] 2017-09-21 01:45
To use [flag](https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054), I fix the problem.
