### ISSUE TITLE
Color scheme getting crazy when concatenating loads of var. + strings in Python3

### ISSUE THREAD

**Issue by gustavohmsilva** [atom/atom#14091] opened 2017-03-29 20:34 UTC
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When concatenating in Python 3 a high amount of content in my project, after a certain amount of quotations the color code stop working for some reason.

### Steps to Reproduce

1. [First Step] 
Create a .py file in atom
2. [Second Step] 
git clone my repo (where the problem appears) https://github.com/gustavohmsilva/Net-Claro-VOD-Manifest-Generator-Scripts.git
3. [Third Step]
Open the file CSVtoXML_Single.py in atom.
4. [Fourth Step]
Check how after some point on lines 127 and 152, this happens automatically, que color code just stop working and everything turns grey. On line 162, which is just a little bit smaller, the same doesn't happens.

**Expected behavior:** 
Color code should keep going like it would normally.

**Actual behavior:** 
Color code stop working and everything turns gray on that point forward (in that line, the next one is ok)

**Reproduces how often:** 
I'm concluding the third similar script and it always happens in long lines...

### Versions
1.15.0 x64 (running on mac os x sierra), but it also happened on the same version of atom in my Linux VM,  running Xubuntu 16.04 x64.

**Comment by rsese** [comment] 2017-03-30 17:32
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/1667. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-30 17:32 UTC
