### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by ByeDream** [atom/atom#18205] opened 2018-10-06 14:13 UTC
[Enter steps to reproduce:]

1. install linter-cppcheck
2. .edit then save a file

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'filter' of undefined

```
At C:\Users\EricR\AppData\Local\atom\app-1.31.1\resources\app\node_modules\settings-view\lib\atom-io-client.js:305

TypeError: Cannot read property 'filter' of undefined
    at Request._callback (~/AppData/Local/atom/app-1.31.1/resources/app/node_modules/settings-view/lib/atom-io-client.js:305:39)
    at Request.self.callback (/app.asar/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /app.asar/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -3:46.1.0 intentions:highlight (input.hidden-input)
     -3:46 core:save (input.hidden-input)
     -3:44.7.0 editor:newline (input.hidden-input)
     -3:42.7.0 intentions:highlight (input.hidden-input)
     -3:42.5.0 core:save (input.hidden-input)
  3x -3:08.3.0 core:backspace (input.hidden-input)
     -1:51 intentions:highlight (input.hidden-input)
     -1:50.8.0 core:save (input.hidden-input)
     -1:49.2.0 intentions:highlight (input.hidden-input)
     -1:49 core:save (input.hidden-input)
  2x -1:41.9.0 editor:newline (input.hidden-input)
     -1:40.9.0 intentions:highlight (input.hidden-input)
     -1:40.7.0 core:save (input.hidden-input)
     -1:39.1.0 intentions:highlight (input.hidden-input)
     -1:38.9.0 core:save (input.hidden-input)
  3x -1:34.6.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 1.4.3 
file-icons 2.1.25 
gpp-compiler 3.0.7 
intentions 1.1.5 
linter 2.2.0 
linter-cppcheck 0.2.3 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
```

**Comment by rsese** [comment] 2018-10-09 06:48
Thanks for contributing!

Based on the stack trace, I think this is a duplicate of https://github.com/atom/settings-view/issues/1052 so you can subscribe there for updates if you'd like.

Go ahead and try uninstalling/reinstalling the package and see if that helps for now.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-09 06:48 UTC
