### ISSUE TITLE
Wrong file title after save-as

### ISSUE THREAD

**Issue by bernardodesousa** [atom/atom#8942] opened 2015-09-25 11:23 UTC
After saving file with different name by save-as / ctr+shift+S, when hover over tab, old title is displayed.

**Comment by 50Wliu** [comment] 2015-09-25 12:26
What was the name of the old file, and of the new file?

**Comment by mnquintana** [comment] 2015-09-25 14:01
Thanks for the report! This looks like a duplicate of https://github.com/atom/tabs/issues/189 – please subscribe there for updates.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.,

**Closed by mnquintana** 2015-09-25 14:01 UTC
Labels: more-information-needed
