### ISSUE TITLE
Project Folder Sidebar text

### ISSUE THREAD

**Issue by WardsParadox** [atom/atom#7834] opened 2015-07-10 17:18 UTC
When opening a large project folder and scrolling down or up, the project folder sidebar text becomes unreadable in some parts.  Clicking near the text artifacts clears it up in that area, but opening the preferences pane clears it temporarily for that session. 
Atom version: 1.0.2
OS X 10.10.4
<img width="237" alt="screen shot 2015-07-10 at 11 13 36 am" src="https://cloud.githubusercontent.com/assets/8117192/8624403/d89e536a-26f4-11e5-929e-9916be2113a3.png">

**Comment by izuzak** [comment] 2015-07-10 17:26
Thanks for the report -- this looks like a duplicate of https://github.com/atom/atom/issues/4924.

**Closed by izuzak** 2015-07-10 17:26 UTC

**Comment by WardsParadox** [comment] 2015-07-10 17:27
Wow sorry. Didn't see that one, sorry about the duplicate.
