### ISSUE TITLE
Option to turn off "open last used tabs/folders"

### ISSUE THREAD

**Issue by gsklee** [atom/atom#6794] opened 2015-05-15 01:03 UTC
All of the projects I'm working on are mounted through SSHFS which will become inaccessible as I move around places, and now that Atom attempts to load previously opened tabs/folders on program startup, I almost always will see a huge list of red warnings on the right side twice a day as I move from home to office and office to home. It'd be great if we can add in an option to turn this behavior off because it's not beneficial to me in this case.

**Comment by mnquintana** [comment] 2015-05-15 01:21
This looks like a duplicate of https://github.com/atom/atom/issues/6605 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-15 01:21 UTC
