### ISSUE TITLE
Large Json on file.json

### ISSUE THREAD

**Issue by AnibalNicolas** [atom/atom#13396] opened 2016-12-06 13:42 UTC
### Description

I was working with large jsons (more than 50000 characteres), if you push a json into a single line file with .json extension, the pointer at the end of line is delayed.

Gif to show problem
http://gph.is/2h2fu7m

### Steps to Reproduce

1. Save file with json extension
2. Paste Large Json
3. Go to the end of line

**Expected behavior:** The current pointer position needs to be synchronized with the real position of it.

**Actual behavior:** When you try to delete some character, the action take place elsewhere.

### Versions
iOS 10.10.5 Yosemite
Atom version 1.12.6

**Comment by lee-dohm** [comment] 2016-12-23 20:48
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/10855. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2016-12-23 20:48 UTC
