### ISSUE TITLE
Feature Request: A Simple Drag-and-Drop for text, like every other editor.

### ISSUE THREAD

**Issue by GeorgeWL** [atom/atom#14059] opened 2017-03-24 14:17 UTC
I feel like this should be a feature that is in core and it really feels like an oversight that it's not, when even incredibly naive editors like notepad have this feature.

**Comment by 50Wliu** [comment] 2017-03-24 15:32
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1909. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-03-24 15:32 UTC

**Comment by GeorgeWL** [comment] 2017-03-24 17:35
oops, didn't see it. Thank you 👍
