### ISSUE TITLE
"Replace Next" never dismisses

### ISSUE THREAD

**Issue by jberk** [atom/atom#8796] opened 2015-09-15 13:11 UTC
![screen shot 2015-09-15 at 9 06 42 am](https://cloud.githubusercontent.com/assets/2653417/9877229/8f13f320-5b89-11e5-8aec-31471a4ceded.png)

version 1.0.11

**Comment by 50Wliu** [comment] 2015-09-15 13:31
Duplicate of atom/find-and-replace#501, please subscribe there for updates.

**Closed by 50Wliu** 2015-09-15 13:31 UTC
