### ISSUE TITLE
Blank dropdown for theme selection

### ISSUE THREAD

**Issue by vthuongt** [atom/atom#16436] opened 2017-12-24 13:37 UTC
### Description

I used the *.deb file provided from offical website to install atom. Afterwards I try to select a different theme (both UI and syntax) but only a blank dropdown menu appears:

<img src=https://i.imgur.com/llDREAy.png>

### Steps to Reproduce

1. download atom-amd64.deb from official website
2. install
3. try to select different color theme

**Expected behavior:** 
Some dropdown menu to select different theme

**Actual behavior:** 
On my main laptop screen only a blank dropdown appears
If I move the windows to my second screen with higher resolution, dropdown entries become visible

**Reproduces how often:** 100%

### Versions
atom --version:
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm --version:
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 3.6.3
git 2.14.1
lsb_release -a:
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

### Additional Information
Laptop screen resolution: 1366x768
2nd screen resolution: 1920x1080

**Comment by rsese** [comment] 2017-12-29 05:38
Thanks for the report!  It looks like you removed the `Prerequisites` section of the issue template - can you confirm if you can reproduce in safe mode (`atom --safe`)?  

Also, is there any difference if you start Atom with `atom --disable-gpu`?

**Comment by rsese** [comment] 2018-03-16 22:58
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16436#issuecomment-354400521. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-03-16 22:58 UTC
Labels: more-information-needed

**Comment by djh1997** [comment] 2018-06-08 10:30
atom - 1.27.2
os-Ubuntu 18.04 LTS
was having same issue safe mode didnt work but dissable-gpu did even fixing issue permantly  so far
