### ISSUE TITLE
parentheses rendering error in php file

### ISSUE THREAD

**Issue by netmou** [atom/atom#17128] opened 2018-04-13 00:40 UTC
parentheses rendering error in php file,atom v1.25.1
![image](https://user-images.githubusercontent.com/7068058/38711101-4006c390-3ef6-11e8-8188-0c20876704dd.png)

**Comment by Arcanemagus** [comment] 2018-04-13 20:14
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-php/issues/321. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-04-13 20:14 UTC
