### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `length` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by juanbanzer** [atom/atom#17922] opened 2018-08-24 15:31 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot destructure property `length` of 'undefined' or 'null'.

```
At /Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:493

TypeError: Cannot destructure property `length` of 'undefined' or 'null'.
    at TextMateLanguageMode.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:493:38)
    at TextMateLanguageMode.endRowForCodeFoldAtRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:677:41)
    at TextMateLanguageMode.endRowForFoldAtRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:656:25)
    at TextMateLanguageMode.isFoldableAtRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:380:23)
    at TextEditor.isFoldableAtBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:4129:63)
    at TextEditorComponent.queryLineNumbersToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:937:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:387:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1463:18)
    at IntersectionObserver.intersectionObserver.IntersectionObserver (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1412:22)
```

### Commands

```
     -0:42.9.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
emmet 2.4.3 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
open-in-browsers 0.0.30 
```

**Comment by rsese** [comment] 2018-08-24 18:11
Thanks for contributing!

Based on the stack trace I think this is a duplicate of https://github.com/atom/atom/issues/17482 so you can subscribe there for updates if you'd like.  If you have steps to reproduce, please let us know in https://github.com/atom/atom/issues/17482 (it seems related to code folding based on the comments).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-08-24 18:11 UTC
