### ISSUE TITLE
Windows 10 file dialogs don't scale with windows settings

### ISSUE THREAD

**Issue by eskemojoe007** [atom/atom#17425] opened 2018-05-29 21:30 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In windows 10 with very different resolution monitors and scaling, Atom scales properly, but the open and save as dialogs do not.  They match the resolution of the primary monitor, often making them super zoomed in or super zoomed out

### Steps to Reproduce
Windows 10 installed with two monitors: 4K primary set at 200% scale, 1680X1050 set at 100% scale.

**Expected behavior:** I expect the open and save as dialogs to scale with the rest of atom as does the windows file explorer and open and save as dialogs from other applications.  

**Actual behavior:** I attached an example of how it looks on screen 1
![image](https://user-images.githubusercontent.com/22135005/40686524-9935ed22-6365-11e8-804f-c02361c417f0.png)

and here an example of how it looks on screen 2

![image](https://user-images.githubusercontent.com/22135005/40686552-b858b1c6-6365-11e8-966d-7320200ea4bd.png)

**Reproduces how often:** This always happens with multiple computers with similar monitors that I've experienced.

### Versions

Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by rsese** [comment] 2018-05-29 23:17
Thanks for contributing!

This looks like a duplicate of https://github.com/atom/atom/issues/16717, see 50wliu's [comment](https://github.com/atom/atom/issues/16717#issuecomment-365058025) here for more details.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-29 23:17 UTC
