### ISSUE TITLE
Context menu throws error

### ISSUE THREAD

**Issue by pmwhite** [atom/atom#7370] opened 2015-06-22 16:30 UTC
I'm just reporting this error I got when using atom.
Error report:

[Enter steps to reproduce below:]

1. I opened a folder in atom with the windows context menu item
2. I right clicked on a a folder in the sidebar and up pops the error.

**Atom Version**: 0.210.0
**System**: Microsoft Windows 8.1 Pro with Media Center
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:150:33)
    at HTMLDocument.handler (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\Philip\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "atom-sharp",
      "autocomplete-paths",
      "linter"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.30
autoclose-html, v0.18.0
build, v0.38.0
javascript-snippets, v1.0.0
language-fsharp, v0.8.4
language-rust, v0.4.3
linter-rust, v0.1.0
racer, v0.14.1
scheme-syntax, v0.4.0
simple-drag-drop-text, v0.2.3
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by pmwhite** [comment] 2015-06-22 16:34
I know why now.  I had two instances of atom running.  I closed down the other one and right clicked again and I still got the error.  I closed down both, restarted atom, and it worked fine.

**Comment by mnquintana** [comment] 2015-06-22 17:17
This looks like a duplicate of https://github.com/atom/atom/issues/6548 - I'm gonna close this in favor of https://github.com/atom/atom/issues/6548 to keep the discussion in one place. Would you mind adding your comment about the two instances of Atom to the other issue? I'm wondering if that might be what's common across all instances of this error. Thanks!

**Closed by mnquintana** 2015-06-22 17:17 UTC
