### ISSUE TITLE
Failed to load the styleguide package

### ISSUE THREAD

**Issue by him0** [atom/atom#8679] opened 2015-09-05 00:00 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the styleguide package

```
At ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app.asar'

Error: ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app.asar'
  at Error (native)
  at fs.openSync (fs.js:544:18)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:402:12)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:307:21)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:286:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:499:45
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:498:59)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:187:19
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:667:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:82:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "fontSize": 15,
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "fontFamily": "SourceHanCodeJP-Medium"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
emmet, v2.3.12
japanese-dictionary, v0.2.0
japanese-menu, v1.3.0
japanese-wrap, v0.2.7
minimap, v4.12.3

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-09-08 16:25
Thanks for the report -- I believe this is a duplicate of https://github.com/atom/atom/issues/6604 so closing this in favor of that issue.

**Closed by izuzak** 2015-09-08 16:25 UTC
