### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of null

### ISSUE THREAD

**Issue by kaliara** [atom/atom#19700] opened 2019-07-24 20:24 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of null

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'getSelectedBufferRanges' of null
    at BufferSearch.search (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:747766)
    at FindView.liveSearch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:767805)
    at findEditor.onDidStopChanging (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:763524)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208969)
    at TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:504055)
    at later (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:103239)
```

### Commands

```
     -8:32.1.0 core:save (input.hidden-input)
  2x -7:08.7.0 core:close (input.hidden-input)
     -7:06.9.0 project-find:show (input.hidden-input)
     -7:06.5.0 core:paste (input.hidden-input)
     -7:05.6.0 core:confirm (input.hidden-input)
     -1:02.6.0 find-and-replace:show (input.hidden-input)
     -1:02.3.0 editor:consolidate-selections (input.hidden-input)
     -1:02.3.0 core:cancel (input.hidden-input)
  2x -0:48.9.0 core:close (input.hidden-input)
     -0:28.4.0 tree-view:collapse-directory (div.tool-panel.tree-view)
     -0:11.5.0 project-find:show (div.tool-panel.tree-view)
     -0:11.5.0 pane:show-previous-item (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-liquid-snippets 0.3.0 
language-liquid 0.7.0 
sass 0.5.0 
shopify-helper 0.6.0 
```

**Comment by rsese** [comment] 2019-07-24 23:42
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/find-and-replace/issues/998 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-07-24 23:42 UTC
