### ISSUE TITLE
Please add progress window when downloading update

### ISSUE THREAD

**Issue by przemolb** [atom/atom#18414] opened 2018-11-09 17:55 UTC
Please please:
- add popup window with a message if there is an update available (and what version) and a choice if an user want to download it
- add progress report window while downloading this update
It would be really, really useful to have that.

**Comment by thomasjo** [comment] 2018-11-09 18:06
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #9164. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by thomasjo** 2018-11-09 18:06 UTC
