### ISSUE TITLE
Uncaught Error: spawn /Users/name/Library/Application Support/com.github.atom.ShipIt/up...

### ISSUE THREAD

**Issue by donnyburnside** [atom/atom#9792] opened 2015-11-24 14:34 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/name/Library/Application Support/com.github.atom.ShipIt/update.jToqT6b/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/name/Library/Application Support/com.github.atom.ShipIt/update.jToqT6b/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/name/Library/Application Support/com.github.atom.ShipIt/update.jToqT6b/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/name/Library/Application Support/com.github.atom.ShipIt/update.jToqT6b/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/name/Library/Application Support/com.github.atom.ShipIt/update.jToqT6b/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (/Users/name/Library/Application Support/com.github.atom.ShipIt/update.jToqT6b/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/name/Library/Application Support/com.github.atom.ShipIt/update.jToqT6b/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
```

### Commands

```
  2x -2:00.0 core:copy (atom-text-editor.editor.is-focused)
     -0:39.8.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
  2x -0:38 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 13,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-24 15:59
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-24 15:59 UTC
