### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/zhangchao/Downloads/Atom.app'

### ISSUE THREAD

**Issue by Allkoman** [atom/atom#11365] opened 2016-04-04 12:36 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/zhangchao/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/zhangchao/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/zhangchao/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -6:43.6.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
     -6:32.7.0 package-generator:generate-package (atom-text-editor.editor.is-focused)
  2x -6:09.9.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -2:55.5.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
     -2:25.5.0 about:view-release-notes (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:52.3.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
     -1:06.1.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
  5x -1:02.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:39.4.0 package-generator:generate-package (atom-text-editor.editor.is-focused)
     -0:37.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.6.0 package-generator:generate-syntax-theme (atom-text-editor.editor.is-focused)
     -0:22.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-04-04 16:11
This is a duplicate of #10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-04 16:11 UTC
