### ISSUE TITLE
FYI: Atom quit unexpectedly

### ISSUE THREAD

**Issue by renegare** [atom/atom#9993] opened 2015-12-10 02:10 UTC
So to replicate on *osx*:

1. open a project
2. hit ```cmd``` + ```shift``` + ```w```

you should see a pop up stating "Atom quit unexpectedly"

I have not tested on other OSs, Hope this is a none issue!

**Comment by lee-dohm** [comment] 2015-12-10 02:48
It sounds like you are experiencing this issue:

https://github.com/atom/atom/issues/9584

Which version of Atom are you using?

**Comment by renegare** [comment] 2015-12-16 20:01
Apologies for the late response. 

I believe its the same issue, and to add it has to be in full screen mode.

I am using atom version 1.2.4.

Worth closing this ticket?

**Comment by 50Wliu** [comment] 2015-12-16 21:07
> and to add it has to be in full screen mode.

In that case this is a duplicate of #9584, and should be fixed in the 1.4.0 betas.

**Closed by 50Wliu** 2015-12-16 21:07 UTC
