### ISSUE TITLE
Atom covers most of window with white when moving between two screens while in full screen

### ISSUE THREAD

**Issue by will-in-wi** [atom/atom#9287] opened 2015-10-26 14:06 UTC
I have a retina MacBook Pro running El Capitan with two non-retina external monitors. I will frequently start Atom, make it full screen on the macbook, and then in Mission Control, drag the full-screen window to an external monitor. When I do, most of the window is white:

![screenshot 2015-10-26 09 02 27](https://cloud.githubusercontent.com/assets/1298231/10730830/5d632c36-7bc0-11e5-8121-a0393def628a.png)

If I remove it from full screen and then go right back to full screen on the external monitor, it resets.

If I move the window to the external monitor before making it full screen, it works correctly.

If I make the window full screen on a non-retina monitor and then move it to the other non-retina monitor, it works correctly.

I'm guessing that Atom doesn't handle the switch between retina states while full screen well.

**Comment by jeancroy** [comment] 2015-10-26 17:57
possible duplicate of https://github.com/atom/atom/issues/9226 ?

**Comment by will-in-wi** [comment] 2015-10-26 19:06
Possibly related, but a different issue.

**Comment by mnquintana** [comment] 2015-10-26 19:11
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/8847 – feel free to subscribe there for updates.

**Closed by mnquintana** 2015-10-26 19:11 UTC

**Comment by will-in-wi** [comment] 2015-10-26 19:24
Ah, yup. This is a dup.
