### ISSUE TITLE
Adding < as a wrappable token?

### ISSUE THREAD

**Issue by zyklus** [atom/atom#13039] opened 2016-10-21 00:18 UTC
Is there a way to add `<` as a wrappable token?  What I mean by this is if you select `text` and hit `(` you get `(text)`.  If you do the same with `<` it wipes out the text.

If not, can I suggest it?  :)

**Comment by 50Wliu** [comment] 2016-10-21 00:23
This is a duplicate of atom/bracket-matcher#121 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-21 00:23 UTC
