### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('highlight-selected light-theme background') contains HTML space characters, which are not valid in tokens.

### ISSUE THREAD

**Issue by plaxdan** [atom/atom#5751] opened 2015-02-25 22:24 UTC
Steps to reproduce:

1. highlight a word

**Atom Version**: 0.183.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('highlight-selected light-theme background') contains HTML space characters, which are not valid in tokens.

```
At /Applications/Atom.app/Contents/Resources/app/src/highlights-component.js:63

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('highlight-selected light-theme background') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at HighlightsComponent.module.exports.HighlightsComponent.updateHighlightNode (/Applications/Atom.app/Contents/Resources/app/src/highlights-component.js:63:33)
  at HighlightsComponent.module.exports.HighlightsComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/highlights-component.js:47:28)
  at LinesComponent.module.exports.LinesComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:118:32)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:213:27)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:283:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:159:9)
  at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:61

```

### Commands

```
  3x -1:54.3 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:53.3 core:move-right (atom-text-editor.editor.is-focused)
     -1:53.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -1:49.7 core:save (atom-text-editor.editor.is-focused)
     -1:29.5 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:24.0 core:save (atom-text-editor.editor.is-focused)
     -1:15.1 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -1:11.7 core:save (atom-text-editor.editor.is-focused)
     -0:56.6 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:56.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:32.8 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:27.8 core:move-left (atom-text-editor.editor.is-focused)
     -0:26.0 core:save (atom-text-editor.editor.is-focused)
     -0:25.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:21.2 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:20.2 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby-on-rails",
      "language-ruby",
      "todo-show",
      "glist",
      "omnisharp-atom",
      "minimap",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "minimap-selection",
      "live-archive",
      "styleguide",
      "autocomplete",
      "language-diff"
    ],
    "themes": [
      "one-light-ui",
      "monokai-light"
    ],
    "projectHome": "/Users/daniel/dev/ds"
  },
  "editor": {
    "fontFamily": "Source Code Pro for Powerline",
    "showIndentGuide": true,
    "scrollPastEnd": true,
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.11.0
atom-beautify, v0.21.3
atom-color-highlight, v3.0.8
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
change-case, v0.5.1
coffee-compile, v0.10.0
color-picker, v1.4.4
file-icons, v1.4.11
filesize, v0.1.1
git-tab-status, v1.5.3
highlight-selected, v0.9.0
language-batch, v0.3.2
language-csharp, v0.5.0
language-fsharp, v0.8.4
last-cursor-position, v0.7.0
linter-less, v0.3.1
monokai-light, v0.3.6
script-runner, v1.7.0
set-syntax, v0.2.1
trailing-spaces, v0.2.4

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-02-25 22:30
Looks like a duplicate of #5747

**Closed by kevinsawicki** 2015-02-25 22:30 UTC
