### ISSUE TITLE
Find in Project returns no results when path contains forward slashes (/)

### ISSUE THREAD

**Issue by beholdnec** [atom/atom#15219] opened 2017-08-09 18:36 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Find in Project returns no results when file/directory pattern contains forward slashes. Backslashes are required to separate directories.

### Steps to Reproduce

1. Open Find in Project panel.
2. In the File/directory pattern field, enter a path with forward slashes. For instance, `src/foo/bar`.
3. Search for text that is known to exist in the specified directory. No results are found.
4. Change the path to use backslashes. For instance, `src\foo\bar`. Now, results are found.

**Expected behavior:** File/directory pattern should return the same results, regardless of whether file/directory pattern contains forward slashes or backslashes. This matches the behavior of the vast majority of Windows apps.

**Actual behavior:** When file/directory pattern contains forward slashes, search returns no results.

**Reproduces how often:** Every time.

### Versions

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

OS: Windows 10 x64

### Additional Information

\-

**Comment by rsese** [comment] 2017-08-09 19:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/295 so you can subscribe there for updates if you'd like.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-09 19:20 UTC
