### ISSUE TITLE
Error when closing Atom after opening via GitBash

### ISSUE THREAD

**Issue by eicksl** [atom/atom#14888] opened 2017-06-25 07:13 UTC
If I open Atom with the GitBash shell, then close the Atom window, the shell displays the following error:

`Attempting to call a function in a renderer window that has been closed or released. Funct          ion provided here: Object.<anonymous> (C:\Users\SPENCER\AppData\Local\atom\app-1.18.0\resour          ces\app\node_modules\github\lib\worker.js:71:22.
Error: Attempting to call a function in a renderer window that has been closed or released.           Function provided here: Object.<anonymous> (C:\Users\SPENCER\AppData\Local\atom\app-1.18.0\r          esources\app\node_modules\github\lib\worker.js:71:22.
    at WebContents.callIntoRenderer (C:\Users\SPENCER\AppData\Local\atom\app-1.18.0\resource          s\electron.asar\browser\rpc-server.js:190:19)
    at emitOne (events.js:101:20)
    at WebContents.emit (events.js:188:7)`

Any idea how to fix this?

Atom version: 1.18
Git version: 2.13

**Comment by rsese** [comment] 2017-06-26 17:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/769. You may want to subscribe there for updates.  Also, for future issues it would be super helpful for us if you can completely fill out the issue template since it makes it easier to triage.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-26 17:47 UTC
Labels: duplicate
