### ISSUE TITLE
deactivating a deactivated package throws an exception

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#4193] opened 2014-11-14 22:55 UTC
Deactivating an already deactivated package throws an exception.  I can't show the error because I'm doing a `ctrl-alt-R` and the error just flashes.  I'm deactivating via `atom.packages.deactivatePackage('foo')` although I can imagine non-debug situations where this could happen.  In any case it's not good to throw in a harmless situation.

## Repro Steps

1. Deactive package with `atom.packages.deactivatePackage('foo')`
2. Do `ctrl-alt-R` and watch inspector to see red flash

## Versions

* **Atom:**       0.146.0
* **Atom-Shell:** 0.19.1
* **OS:**         Microsoft Windows 8.1 Pro with Media Center
* **Misc**
  * apm  0.111.0
  * npm  1.4.4
  * node 0.10.33
  * python 2.7.5
  * git 1.7.11.msysgit.1
  * visual studio 2013

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` version 0.4.1.</small>

**Comment by izuzak** [comment] 2015-09-17 15:30
I'm not seeing the read flash when I follow the reproduction steps. @mark-hahn do you still see that problem?

**Comment by izuzak** [comment] 2015-09-22 08:10
Closing since I can't reproduce the red flash, and doing this in console doesn't seem to trigger exceptions.

```
> atom.packages.isPackageActive('ctrl-last-tab')
true
> atom.packages.deactivatePackage('ctrl-last-tab')
undefined
> atom.packages.isPackageActive('ctrl-last-tab')
false
> atom.packages.deactivatePackage('ctrl-last-tab')
undefined
```

If you can still reproduce the problem -- let us know.

**Closed by izuzak** 2015-09-22 08:10 UTC
Labels: needs-reproduction
