### ISSUE TITLE
Make it easier to quickly close a large number of tabs

### ISSUE THREAD

**Issue by daveyjones** [atom/atom#10063] opened 2015-12-15 01:11 UTC
Have you ever noticed how you can close a large number of tabs very quickly in Chrome? This is because the width of the tab is held constant until the mouse leaves the tab area, so if I close a tab, the next tab moves to occupy the exact same space that the previous tab did, with the "x" in the same position, allowing me to quickly close a large number of tabs by simply clicking repeatedly in the same spot.

I've noticed while using Atom that I oftentimes want to quickly close a large number of tabs, which proves to be challenging given the current state of tab closing. Below are two options for how this could be improved.

**Option 1 (easier)**

Move the "x" to the same side tabs are floated. For me, tabs are floated left (this may be different for right-to-left languages, I don't know). For me, if the "x" was also on the left, then you could rapidly close tabs by clicking repeatedly in the same position, since the "x" of the next tab would occupy the same position as the "x" of the tab that was just closed. This seems like the obvious solution to me, but there may be other reasons that the "x" was placed on the right-hand side that I'm not aware of.

**Option 2 (more difficult)**

Leave the "x" where it is (on the right-hand side), but use Chrome's approach of keeping the tab size constant until the user moves the mouse out of the tab region. This would require a lot more code, but would allow you to keep the "x" on the right-hand side (if that is important for some reason).

**Comment by mnquintana** [comment] 2015-12-15 01:35
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/tabs/issues/129 – feel free to keep the discussion going there.

**Closed by mnquintana** 2015-12-15 01:35 UTC
