### ISSUE TITLE
Dragging in an XML file on Windows tries to render it in browser

### ISSUE THREAD

**Issue by rbrtmrtn** [atom/atom#7300] opened 2015-06-16 18:30 UTC
I dragged in an XML file (with the extension `.config`) into Atom and it tried to render it in the browser. Running v. 0.209.0 on Windows Server 2008 R2.

![atom](https://cloud.githubusercontent.com/assets/1463553/8191014/04fb8276-1434-11e5-8b72-87e17f80800a.png)

**Comment by mnquintana** [comment] 2015-06-16 20:30
Wellp, that's pretty strange. Just to make sure, can you reproduce this in safe mode? (`atom --safe`)

**Comment by mnquintana** [comment] 2015-06-16 20:40
I can't reproduce this with Atom 0.209.0 on Windows 8.1 in safe mode. [Here's the Gist I used based on the text in your screenshot.](https://gist.github.com/mnquintana/8d52b96834f0ce62268b)

**Comment by mnquintana** [comment] 2015-06-17 13:15
Actually looks like this is a duplicate of https://github.com/atom/atom/issues/4300 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-17 13:15 UTC
Labels: more-information-needed, needs-reproduction, windows
