### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by kc9zyz** [atom/atom#7392] opened 2015-06-23 21:02 UTC
Steps to reproduce:

1. right click on project folder in tree view, open or closed

**Atom Version**: 0.211.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\app.asar\src\window-event-handler.js:150:33)
    at HTMLDocument.handler (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\KC9ZYZ\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -8:47.3.0 core:save (atom-text-editor.editor.is-focused)
     -8:24.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -8:22.3.0 core:save (atom-text-editor.editor.is-focused)
  3x -7:51.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:50.6.0 core:save (atom-text-editor.editor.is-focused)
     -7:37.4.0 core:move-left (atom-text-editor.editor.is-focused)
  8x -7:37.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:35.4.0 core:save (atom-text-editor.editor.is-focused)
     -7:05.8.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -7:03.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:46.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:45.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:48.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:31.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:30.3.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -3:25.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-06-23 21:03
Duplicate of #6548, please subscribe there for updates.

**Closed by 50Wliu** 2015-06-23 21:03 UTC
