### ISSUE TITLE
Uncaught Error: variable @syntax-background-color is undefined

### ISSUE THREAD

**Issue by derkcris** [atom/atom#9545] opened 2015-11-12 16:07 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: variable @syntax-background-color is undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:291

Error
    at new Parser (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:275:20)
    at LessCache.module.exports.LessCache.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:263:19)
    at LessCompileCache.module.exports.LessCompileCache.read (/Applications/Atom.app/Contents/Resources/app.asar/src/less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:272:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:248:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:165:24)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:12:15)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:361:4)
```

### Commands

```
  5x -0:03.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-wombat-light-syntax.theme-native-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "wombat-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12,
    "showIndentGuide": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
jshint, v1.8.3
language-groovy, v0.4.0
linter, v1.10.0
linter-htmlhint, v0.2.1
linter-jscs, v3.2.0
linter-jshint, v1.2.1
native-ui, v0.7.3
php-cs-fixer, v2.5.1
wombat-light-syntax, v1.1.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-11-13 18:28
Closing as duplicate of #9541

**Closed by kevinsawicki** 2015-11-13 18:28 UTC
Labels: uncaught-exception
