### ISSUE TITLE
Clicking (not dragging) starts highlighting text

### ISSUE THREAD

**Issue by harai** [atom/atom#8609] opened 2015-09-01 02:01 UTC
On Ubuntu 15.04 (which is not on VM), clicking on Atom starts highlighting text.  This problem occurs on Atom 1.0.8 and 1.0.9 but doesn't occur on Atom 1.0.7.  No error messages are shown in DevTools' Console.

Adding `--safe` option and resetting Config, Init Script, Keymap, Snippets, and Stylesheet don't change anything.  The problem still occurs.

This is the screen capture.  I am not dragging.  I just click several times while moving the cursor on the editor.  Though there's no cursor in the movie, it is capture app's issue.

![output2](https://cloud.githubusercontent.com/assets/515636/9594352/fb08c5b0-5094-11e5-92c4-806b78904426.gif)

**Comment by izuzak** [comment] 2015-09-01 07:53
Thanks for the report, @harai -- that's very strange. I'm unable to reproduce this on OSX, so might be something OS-related. 

@atom/feedback Do any of you have Ubuntu 15.04 and can try and reproduce this?

Also cc-ing @nathansobo in case this is related to those fixes with selections on OSX somehow? :thought_balloon:

**Comment by harai** [comment] 2015-09-01 10:43
After reinstalling Atom 1.0.9 and rebooting the machine, the problem has disappeared.

The model on which the problem occured was Dell XPS 13.  Though I have another Ubuntu 15.04 machine, I couldn't reproduce it.

**Comment by izuzak** [comment] 2015-09-01 10:45
Thanks for letting us know, @harai -- I'm going to close this for now. And if you or anyone else notices this again -- please let us know.

**Closed by izuzak** 2015-09-01 10:45 UTC
Labels: bug, editor-rendering, linux, needs-reproduction

**Comment by danitt** [comment] 2016-10-25 16:47
fwiw, had the exact same issue on a Lenovo laptop running Ubuntu 16.04

- Atom restart did _not_ help
- OS restart _did_ help

I've used Atom extensively on OSX too and have never seen this before, so as suggested by @izuzak it certainly appears to be an OS-specific issue

in any case, laptop needed a restart, so no biggie :)

**Comment by Ben3eeE** [comment] 2016-10-25 17:47
@danitt Yeah this is still an issue. We are currently tracking it in https://github.com/atom/atom/issues/11691 if you want to subscribe there for updates.
