### ISSUE TITLE
Uncaught TypeError: Invalid Point: (163, NaN)

### ISSUE THREAD

**Issue by WebSaito** [atom/atom#17307] opened 2018-05-11 22:42 UTC
[Enter steps to reproduce:]

1. ... OPENED A FILE FROM MY NETWORK
2. ... JUST PRESSED [BACKSPACE ON A SPECIFIC LINE THAT I WANTED TO REMOVE FROM THE FILE]

Then this Red Modal appeard

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (163, NaN)

```
At C:\Users\space_000\AppData\Local\atom\app-1.26.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:959

TypeError: Invalid Point: (163, NaN)
    at Function.module.exports.Point.assertValid (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/display-layer.js:345:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/display-marker.js:154:58)
    at changePosition (~/AppData/Local/atom/app-1.26.1/resources/app/src/cursor.js:68:25)
    at Cursor.changePosition (~/AppData/Local/atom/app-1.26.1/resources/app/src/cursor.js:713:11)
    at Cursor.setScreenPosition (~/AppData/Local/atom/app-1.26.1/resources/app/src/cursor.js:67:16)
    at Cursor.moveLeft (~/AppData/Local/atom/app-1.26.1/resources/app/src/cursor.js:288:18)
    at modifySelection (~/AppData/Local/atom/app-1.26.1/resources/app/src/selection.js:252:50)
    at Selection.modifySelection (~/AppData/Local/atom/app-1.26.1/resources/app/src/selection.js:984:11)
    at Selection.selectLeft (~/AppData/Local/atom/app-1.26.1/resources/app/src/selection.js:252:16)
    at Selection.backspace (~/AppData/Local/atom/app-1.26.1/resources/app/src/selection.js:496:36)
    at mutateSelectedText.selection (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1373:65)
    at getSelectionsOrderedByBufferPosition.map (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1387:92)
    at Array.map (native)
    at transact (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1387:66)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.transact (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:3252:26)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1385:23)
    at TextEditor.backspace (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1373:23)
    at TextEditor.object.(anonymous function) [as backspace] (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.core:backspace (~/AppData/Local/atom/app-1.26.1/resources/app/src/register-default-commands.js:442:27)
    at ~/AppData/Local/atom/app-1.26.1/resources/app/src/register-default-commands.js:701:40
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.transact (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:1839:30)
    at HTMLElement.newCommandListeners.(anonymous function) (~/AppData/Local/atom/app-1.26.1/resources/app/src/register-default-commands.js:700:28)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.26.1/resources/app/src/command-registry.js:384:49)
```

### Commands

```
     -3:18.7.0 tabs:close-all-tabs (div.title)
     -0:30.5.0 core:backspace (input.hidden-input)
 21x -0:28.1.0 core:select-left (input.hidden-input)
     -0:26 core:backspace (input.hidden-input)
     -0:23.8.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -0:23.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-music 0.7.0 
atom-play-piano 3.2.1 
color-picker 2.3.0 
emmet 2.4.3 
highlight-selected 0.13.1 
html-entitize 1.1.0 
language-asp-html 0.3.0 
language-vb 0.1.0-pre1 
```

**Comment by rsese** [comment] 2018-05-14 16:38
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14774 so you can subscribe there for updates if you'd like.  If you can consistently reproduce the error, please let us know in https://github.com/atom/atom/issues/14774.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-14 16:38 UTC
