### ISSUE TITLE
automatic reloading does not work

### ISSUE THREAD

**Issue by Talent25** [atom/atom#16420] opened 2017-12-21 15:54 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am using atom as an editor for code development. I use clang as part of build process. So, if formatting is off, it changes the format of the content. Recently, I noticed the file is closed when reformatted/changed outside atom. When I disable "Close deleted file tabs", it close the original file and create a copy of it with different name. So I have to delete the newly created file manually. Please note that in this case no file is actually deleted outside atom. It is only modified outside atom.

atom keeps my changes and the only issue is:
When I enable "Close deleted file tabs": my changes are saved in the same file but it is closed instead of being reloaded

When I disable "Close deleted file tabs: my changes are saved in the original file but it is closed and one additional temporary file is also created that I have to delete manually

### Steps to Reproduce

1. Include a project folder (any coding project)
2.  compile ur code and as part of compiling have clang formatting
3. change a line of code to sth that does not comply with clang formmating
4. Save the file
5. Compile it again

**Expected behavior:** [What you expect to happen]
I expect to see my changes outside atom to be kept and the file to be automatically reloaded

**Actual behavior:** [What actually happens]
File is closed/ additional temp file is generatedd
**Reproduces how often:** [What percentage of the time does it reproduce?]
All the time
### Versions
I was not seeing this earlier but not sure which version or change caused the issue. 1.23 and 1.24 definitely have this issue

**Comment by rsese** [comment] 2017-12-21 19:37
Thanks for the report!  I noticed that you didn't check off the `Prerequisites` section - have you tried in safe mode?

> I noticed the file is closed when reformatted/changed outside atom

I'm unable to reproduce this generally (not specifically with clang and the auto formatting you mentioned) - e.g. if I open a file in Atom and then change it externally, the file in Atom shows the external changes but the file isn't closed.

> When I disable "Close deleted file tabs", it close the original file and create a copy of it with different name. 

Hmmm, I don't see this either - what's the format of the copy's filename?

Lastly what operating system are you running?

**Comment by rsese** [comment] 2018-03-16 22:55
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16420#issuecomment-353439045. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-03-16 22:55 UTC
Labels: more-information-needed

**Comment by sgtnoodle** [comment] 2018-04-13 19:38
@rsese Additionally, I've noticed that the .TMP file keeps being created on the file system after I delete it at the command line, even if I close the file's corresponding tab in atom. I need to close atom completely in order to rid myself of the file!

**Comment by rsese** [comment] 2018-04-17 21:07
Thanks @sgtnoodle - I think I mis-read your comment so just to clarify, is using IAR workbench to open and save the file part of your steps to reproduce?   At first I thought startup.c had to be open and saved in IAR workbench in addition to using Sublime, Notepad, and Vim, but now I think I read that wrong so wanted to clarify.

Also, if you change `Settings > Core > File System Watcher` to one of the other options (depends on what version of Atom you're running), does that make a difference?

**Comment by sgtnoodle** [comment] 2018-04-17 21:56
@rsese To clarify, I was just using IAR, notepad, sublime, and vim to demonstrate Atom's different behaviors when another editor saves a text file that's currently opened in Atom.

Day to day, what's really biting me is Atom's behavior when I edit a file inside IAR workbench. I generally work on embedded microcontroller code. I'll spend a couple hours writing new code in Atom, and then at some point I'll switch over to IAR workbench so that I can run and debug the code on a piece of hardware. While debugging, I'll use IAR workbench's text editor since it's integrated with the debugger. Right now, I basically need to close Atom completely to avoid getting a bunch of .TMP files.

I switched File System Watcher to "Emulated with Atom Events" and then restarted Atom, and I get the same behavior.

I'm pretty sure the .TMP filename is coming from IAR workbench. When it saves a file, it seems to be renaming the file to the .TMP version, saving to the original file name, and then deleting the .TMP file. Atom appears to be holding on to the original file through the rename.

I've attached a python script that is able to reproduce the issue. Make a file in Atom, save it, and then run this script on the file while it's still open in Atom. On my setup, the file's tab gets renamed to "test.txt~THISISABACKUP".

python file_toucher.py -t backup test.txt

`import argparse
import os
import time

parser = argparse.ArgumentParser(description='Atom file toucher demo')
parser.add_argument('--type', '-t', default="backup", type=str, help='The method to use: backup, or truncate')
parser.add_argument('target', type=str, nargs=1, help='The file to touch')
args = parser.parse_args()

filename = args.target[0]

if args.type == "truncate":
    with open(filename, "rb+") as f:
        data = f.read()
        f.seek(0)
        f.write(data)
        f.truncate()

elif args.type == "backup":
    with open(filename, "rb") as f:
        data = f.read()
    backup_filename = filename + "~THISISABACKUP"
    if os.path.exists(backup_filename):
        os.remove(backup_filename)
    os.rename(filename, backup_filename)
    with open(filename, "wb") as f:
        f.write(data)
    os.remove(backup_filename)`

**Comment by sgtnoodle** [comment] 2018-04-17 21:57
Bah, github dropped all the indentation.

[file_toucher.zip](https://github.com/atom/atom/files/1921720/file_toucher.zip)

**Comment by lee-dohm** [comment] 2018-04-18 03:51
@sgtnoodle If you want to understand how to make the formatting work, check the [Mastering Markdown help document](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) specifically about Syntax Highlighting and fenced code blocks.

**Comment by sgtnoodle** [comment] 2018-04-18 20:41
Also seemingly related, I've noticed that atom somehow affects files on the filesystem even after I close the file's tab.

This behavior seems to occur when I have a git-managed file open in atom, and then switch git branches to a branch that modifies that file. After the branch switch, git indicates that the file is not staged for commit but modified. When I try to access the file, I get a Permission denied error:

```
$ git status
On branch foo
Your branch is up to date with 'origin/foo'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   messed_up_file.py

no changes added to commit (use "git add" and/or "git commit -a")

~/Documents/Systems (foo)
$ git diff messed_up_file.py
fatal: failed to stat 'messed_up_file.py': Permission denied
```

If I close the "messed_up_file.py" tab in atom, I still can't access the file. If I close atom completely, the file actually disappears completely and so git says it's a not staged for commit delete.

I'm guessing that atom is maintaining an open file descriptor for that file, even after closing it in the UI. Presumably, when git switches branches, it's doing something to the file that results in Atom thinking it's been deleted, and somewhere in there, an open file descriptor is getting leaked.

**Comment by sgtnoodle** [comment] 2018-04-19 15:48
@Ben3eeE great, that issue definitely describes the same behavior I'm seeing with git. I don't think that issue necessarily captures the details of this issue, though, which more generally concerns files edited by other editors.

Both problems might be rooted in the same piece of code though. On #17013 it sounds like no one on the atom dev team has been able to reproduce the git issue. Has anyone tried the python script and procedure I attached above?

**Comment by lee-dohm** [comment] 2018-04-19 16:15
@sgtnoodle So that we can focus the conversation and share information with everyone concerned with the issue, can we move this conversation to #17013? Would you mind posting the Python script and the details you believe are relevant on that issue?
