### ISSUE TITLE
Error building on FreeBSD

### ISSUE THREAD

**Issue by vyal** [atom/atom#2599] opened 2014-06-13 10:00 UTC
I followed the build instructions given for the FreeBSD (10.0 x86_64) here- https://github.com/atom/atom/blob/master/docs/build-instructions/freebsd.md

I compiled node and npm from sources (FreeBSD ports) but still no luck. Here is the full error log:
http://pastebin.com/WQx8UXWs

**Comment by grobe0ba** [comment] 2015-01-02 19:44
So, have people actually succesfully built this on FreeBSD at this point?

**Comment by graemeg** [comment] 2015-05-11 13:21
So much for a cross-platform editor. :-1:  I just tried with the latest atom and node and npm from the port tree. Still no luck in compiling atom.

**Comment by pusateri** [comment] 2015-05-19 20:13
This ticket should be closed. It's a duplicate of #6035 and there's more information there.

**Closed** 2015-06-20 11:26 UTC
Labels: build-error
