### ISSUE TITLE
Huge disk space consumption

### ISSUE THREAD

**Issue by azev** [atom/atom#18131] opened 2018-09-27 17:08 UTC
This is what a just installed atom looks like:
![s20180927140541](https://user-images.githubusercontent.com/6639188/46162384-6f9bdc80-c25e-11e8-9c7b-3198103f7a37.png)

Unnaceptable for a text editor. Why not make a **light release branch** without all that c*** and node.exe in it?

**Comment by lee-dohm** [comment] 2018-09-27 17:10
Thank you for your submission!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/9755. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2018-09-27 17:10 UTC
