### ISSUE TITLE
Linux installation creates incorrect .desktop file with no icon

### ISSUE THREAD

**Issue by BeniaminK** [atom/atom#6766] opened 2015-05-13 15:43 UTC
.desktop file created after compiling from source has wrong binary location ( .../share/atom/atom) instead of the .../bin/atom file.
Besides there is no icon file in the installation share folder, so the .desktop file points at the wrong icon destination (because none is valid).

**Comment by 50Wliu** [comment] 2015-05-13 15:46
Duplicate of #6523, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-13 15:46 UTC
Labels: linux
