### ISSUE TITLE
Sometimes, clicking automatically starts a highlight

### ISSUE THREAD

**Issue by bluebear94** [atom/atom#12996] opened 2016-10-16 02:13 UTC
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Sometimes, especially after long periods of use, clicking in the text editor area automatically starts selecting text.

### Steps to Reproduce

1. Open a file
2. Left-click somewhere in text (don't drag)

**Expected behavior:** The text cursor moves to where you click.

**Actual behavior:** This happens, but sometimes, it starts a text selection. Moving the cursor will show that text is being selected

### Versions

```
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

I am running Atom on Ubuntu 15.10 (Linux kernel version 4.2.0).

**Comment by Ben3eeE** [comment] 2016-10-16 18:03
Closing as a duplicate of https://github.com/atom/atom/issues/11691. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-16 18:03 UTC
