### ISSUE TITLE
valid RegExp syntax highlighting bug. Highlights next line (a comment) incorrectly.

### ISSUE THREAD

**Issue by SeanJM** [atom/atom#9069] opened 2015-10-07 12:13 UTC
![Problem](http://i.imgur.com/aLaLNQV.png)

**Comment by izuzak** [comment] 2015-10-07 12:23
Thanks for the report -- looks like a duplicate of https://github.com/atom/atom/issues/1667. :v:

**Closed by izuzak** 2015-10-07 12:23 UTC
