### ISSUE TITLE
Uncaught Error: Tried to unload active package 'linter-ui-default'

### ISSUE THREAD

**Issue by miguel9703** [atom/atom#18462] opened 2018-11-19 20:26 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'linter-ui-default'

```
At C:\Users\leny-cn\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:11

Error: Tried to unload active package 'linter-ui-default'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:378800)
    at PackageManager.t.exports.PackageManager.unload (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:913346)
    at PackageManager.t.exports.PackageManager.install (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:913579)
    at PackageCard.install (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2945545)
    at HTMLButtonElement.installButtonClickHandler (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2931867)
```

### Commands

```
     -3:29.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angularjs 0.5.3 
atom-bootstrap3 1.2.12 
atom-typescript 11.0.10 
atom-wrap-in-tag 0.6.0 
autocomplete-jquery-mobile 0.2.2 
autocomplete-js-import 1.4.0 
busy-signal 1.4.3 
color-picker 2.3.0 
emmet 2.4.3 
esformatter 3.0.0 
file-icons 2.1.15 
icon-fonts 3.1.4 
intentions 1.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
linter 2.2.0 
linter-ui-default 1.7.1 
```

**Comment by rsese** [comment] 2018-11-20 00:43
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16873 so you can subscribe there for updates if you'd like.  If you have steps to reproduce or any other additional details, please let us know in https://github.com/atom/atom/issues/16873.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-20 00:43 UTC
