### ISSUE TITLE
Atom not responding

### ISSUE THREAD

**Issue by Orion314** [atom/atom#10787] opened 2016-02-12 08:24 UTC
When I pin the window to a side of a screen, it stops responding visually. I can still type and delete, but I won't see any changes unless I unpin the window, resize it, or minimize and get it back.

So, I start the program through the command prompt, drag the window to the side of the screen so it would pin there (Windows 10), and it stops responding. Pinning it to the corners (so it takes up a quarter of the screen) works fine.

**Comment by 50Wliu** [comment] 2016-02-12 13:58
This is a duplicate of #9901 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-12 13:58 UTC
