### ISSUE TITLE
Add theming of Atom app title bar and main menu bar

### ISSUE THREAD

**Issue by Zireael** [atom/atom#19262] opened 2019-05-04 11:19 UTC
## Summary

Please allow theming of Atom window title bar and menu bar.
If not possible directly, it should be possible to hide those two elements and re-render them through chromium engine. That's how probably VS Code, Discord etc do it.

## Motivation

To improve UI consistency when applying color themes (especially dark ones).
Please see screenshot below: I have Atom dark theme applied. However Atom window title and menu bar remain light/white themed.

## Describe alternatives you've considered

Changing window/menu colors globally through Windows settings. However this is not always suitable/desirable/possible for users. Would have to redo settings every time user changes theme. Also, there are packages that change your theme/syntax highlighting depending on time of day or language worked on. Windows would not follow those setting changes.

## Additional context
The only white elements on my screen are Atom top bars:
![image](https://user-images.githubusercontent.com/3856578/57178362-b857eb80-6e66-11e9-95cf-49c3e191fc95.png)

**Comment by rsese** [comment] 2019-05-06 19:49
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/13249 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-05-06 19:49 UTC
