### ISSUE TITLE
Atom segfault when closing in Linux

### ISSUE THREAD

**Issue by StyMaar** [atom/atom#10433] opened 2016-01-15 14:52 UTC
I got this when trying to close atom.
I'm running Atom on Linux Mint Mate qiana x64

```
/usr/bin/atom : ligne 113 : 22502 Erreur de segmentation  nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 211ms
Cannot read property 'send' of null
TypeError: Cannot read property 'send' of null
    at AtomWindow.module.exports.AtomWindow.sendMessage (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:276:44)
    at AtomWindow.module.exports.AtomWindow.openLocations (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:265:21)
    at AtomApplication.module.exports.AtomApplication.openPaths (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:648:22)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:131:21)
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:229:26)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
Cannot read property 'send' of null
TypeError: Cannot read property 'send' of null
    at AtomWindow.module.exports.AtomWindow.sendMessage (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:276:44)
    at AtomWindow.module.exports.AtomWindow.openLocations (/usr/share/atom/resources/app.asar/src/browser/atom-window.js:265:21)
    at AtomApplication.module.exports.AtomApplication.openPaths (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:648:22)
    at AtomApplication.module.exports.AtomApplication.openWithOptions (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:131:21)
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/browser/atom-application.js:229:26)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
[22502:0115/154813:FATAL:resource_dispatcher_host_impl.cc(1171)] Check failed: ContainsKey(active_resource_contexts_, resource_context). 
Failed to get crash dump id.
Report Id:
```

**Comment by mnquintana** [comment] 2016-01-16 22:43
- What version of Atom are you using?
- Can you reproduce this after quitting Atom completely and reopening it in safe mode? (`atom --safe`)
    - If you can, can you provide specific step-by-step instructions for reproducing this?

Please take a look at [this guide for submitting bug reports](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs).

**Comment by StyMaar** [comment] 2016-01-18 13:59
The problem is: I've only seen this bug once. It's not really a usability problem or anything. I just felt the need to report it since I usually consider memory-management errors to be critical.

**Comment by cjwelborn** [comment] 2016-07-10 03:07
@mnquintana, I don't really have any more info to add. I just wanted to say that this happened to me also. I'm on `Kubuntu 16.04`, and `Atom 1.7.4`. Atom froze on me when I used `ESC` to close the 'Find Box' (there were no open files at the time). I tried to shut Atom down gracefully, using the `X`. Eventually I got the 'Editor is not responding' dialog, and closed Atom with that. When I went back to my terminal I saw this message:
```
/usr/bin/atom: line 115:  7673 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 511ms
Failed to get crash dump id.
Report Id: 
Failed to get crash dump id.
```

Unfortunately I can't reproduce it. Sorry.

**Comment by lee-dohm** [comment] 2016-07-12 07:00
Since it only happened twice and we don't have any more information on this, I'm going to close it. Please let us know if you have any more information and I'll be happy to reopen the Issue.

**Closed by lee-dohm** 2016-07-12 07:00 UTC
Labels: more-information-needed

**Comment by cjwelborn** [comment] 2016-07-12 20:31
@lee-dohm, I hate to bug you or anyone else about this issue again, seeing how little info there is to go on. I managed to get Atom into a state where this was reproducible, but it was by accident, and now I can't make it happen again. I could make Atom freeze and then segfault on exit (and did, a dozen or so times) simply by typing a comma into the editor (comma was placed, but the editor was frozen after). My steps were:

* Open Atom with an unsaved, modified file already in the editor.
* Type a `,` into the editor.
* &lt;Atom is frozen&gt;
* Use the close button (`X`) to close Atom.
* Wait a few seconds for the 'Editor is not responding' dialog.
* Use the `Close` button to close Atom (the other option is `Wait`).
* Wait a few seconds for Atom to close, and see the segfault message (as above).

(I realize this alone tells you nothing)

I ran `strace /usr/share/atom/atom`, bypassing `nohup`, and collected the output ([atom-strace.txt](https://welbornprod.com/paste/raw?id=bffy), or this one [with syntax highlighting](https://welbornprod.com/paste?id=bffy)), but I'm not good with strace's so nothing jumps out at me. Maybe `strace` is not the right tool, but it was the only idea I had (dev-mode/logfile didn't say anything).
Is there something else, or another method I could use if I get into this state again? Something that would help diagnose this?

After I saved the file the bug disappeared.

There is definitely a problem here, it's just a hard one to pin down. If I see anything else I will let someone know.

**Comment by lee-dohm** [comment] 2016-07-12 20:49
The biggest benefit would be if you could reproduce the problem in Safe Mode, @cjwelborn. Also, I notice at the end of the strace file this line:

```
open("/tmp/Atom Crashes/43715e78-f167-83e8-73001779-3aed4963.dmp", O_RDONLY) = 22
```

If you can attach these crash dumps when you run into these problems, that would help too.

**Comment by joshhansen** [comment] 2017-01-01 01:39
This just happened to me. I believe it was as I was quitting the application. I'm running on Linux so I grabbed this out of the dmesg log:
[atom-dmesg.txt](https://github.com/atom/atom/files/679897/atom-dmesg.txt)

atom-1.12.7-amd64

If there are other logs I could grab for you, just let me know what you want.
