### ISSUE TITLE
Error Caught when Dragging Windows

### ISSUE THREAD

**Issue by c0fe** [atom/atom#14462] opened 2017-05-17 21:55 UTC
I got two files open into two separate windows, let's call them Window A and Window B. Window A has one file open in one tab and Window B has a different file open in one tab. I drag Window B's tab into Window A and I got this error.

What I was looking to accomplish was to close the other Window and have both tabs in one window.

Here is the error:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.104.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getItems' of undefined

```
At C:\Users\User\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:620

TypeError: Cannot read property 'getItems' of undefined
    at TabBarView.module.exports.TabBarView.onDrop (/app.asar/node_modules/tabs/lib/tab-bar-view.js:620:24)
```

### Commands

```
     -2:28.2.0 core:copy (input.hidden-input)
     -2:26.8.0 core:move-down (input.hidden-input)
     -2:26.6.0 core:move-left (input.hidden-input)
     -2:26.3.0 editor:newline (input.hidden-input)
     -2:26 core:move-up (input.hidden-input)
     -2:25.6.0 snippets:next-tab-stop (input.hidden-input)
     -2:25.6.0 snippets:expand (input.hidden-input)
     -2:25.6.0 editor:indent (input.hidden-input)
     -2:25.1.0 core:paste (input.hidden-input)
     -2:22.7.0 snippets:next-tab-stop (input.hidden-input)
     -2:22.7.0 snippets:expand (input.hidden-input)
     -2:22.7.0 editor:indent (input.hidden-input)
     -2:21.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-05-17 22:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/257. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-17 22:54 UTC
