### ISSUE TITLE
Uncaught Error: socket hang up

### ISSUE THREAD

**Issue by ThijsOostdam** [atom/atom#5925] opened 2015-03-10 20:08 UTC
[Enter steps to reproduce below:]

1. having unstable internet in the train :)
2. was checking my mail, when i got back it showed the error.

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: socket hang up

```
At events.js:94

Error: socket hang up
  at createHangUpError (_http_client.js:216:15)
  at TLSSocket.socketOnEnd (_http_client.js:294:23)
  at TLSSocket.emit (events.js:138:20)
  at _stream_readable.js:909:16
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -1:16.6 core:confirm (atom-text-editor.editor.mini)
     -1:02.7 core:backspace (atom-text-editor.editor.mini)
     -0:59.1 core:move-right (atom-text-editor.editor.mini)
     -0:58.4 core:backspace (atom-text-editor.editor.mini)
     -0:58.0 core:confirm (atom-text-editor.editor.mini)
     -0:49.5 core:copy (atom-text-editor.editor)
     -0:45.4 core:paste (atom-text-editor.editor)
     -0:36.9 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 13,
    "showIndentGuide": true,
    "autoIndent": false,
    "autoIndentOnPaste": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.21.2
atom-lint, v0.20.1
atom-spotify, v1.2.0
autocomplete-paths, v1.0.1
autocomplete-snippets, v1.0.0
circle-ci, v0.3.0
color-picker, v1.4.4
editorconfig, v0.3.0
emmet, v2.3.2
file-icons, v1.4.8
language-diff, v0.2.0
language-jade, v0.3.0
language-latex, v0.4.1
language-matlab, v0.1.0
language-nginx, v0.4.0
language-rspec, v0.3.0
language-rust, v0.3.5
language-stylus, v0.1.0
terminal-status, v1.3.5
test-status, v0.27.1
travis-ci-status, v0.11.2

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-10 11:38
@kevinsawicki Looking at https://github.com/atom/atom/issues/5035#issuecomment-69956737, it seems that this should have been fixed in a version older than reported in this issue. Any chance there's another place this needs to be addressed or that this is caused by a package somehow?

**Comment by kevinsawicki** [comment] 2015-07-21 00:23
I'm pretty sure was fixed by https://github.com/atom/notifications/pull/62 and released

**Closed by kevinsawicki** 2015-07-21 00:23 UTC
Labels: uncaught-exception
