### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollIntoViewIfNeeded' of undefined

### ISSUE THREAD

**Issue by ricardooow** [atom/atom#15869] opened 2017-10-11 19:34 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'scrollIntoViewIfNeeded' of undefined

```
At /private/var/folders/f9/_mpdvpsx30xfywgv_4ptdbzh0000gn/T/AppTranslocation/68F988E3-3927-4EEF-9B28-63546E4E7424/d/Atom.app/Contents/Resources/app/node_modules/github/lib/views/staging-view.js:482

TypeError: Cannot read property 'scrollIntoViewIfNeeded' of undefined
    at StagingView.writeAfterUpdate (/private/var/folders/f9/_mpdvpsx30xfywgv_4ptdbzh0000gn/T/AppTranslocation/68F988E3-3927-4EEF-9B28-63546E4E7424/d/Atom.app/Contents/Resources/app/node_modules/github/lib/views/staging-view.js:482:50)
    at updateSync (/private/var/folders/f9/_mpdvpsx30xfywgv_4ptdbzh0000gn/T/AppTranslocation/68F988E3-3927-4EEF-9B28-63546E4E7424/d/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:134:21)
    at /private/var/folders/f9/_mpdvpsx30xfywgv_4ptdbzh0000gn/T/AppTranslocation/68F988E3-3927-4EEF-9B28-63546E4E7424/d/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:72:13
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/private/var/folders/f9/_mpdvpsx30xfywgv_4ptdbzh0000gn/T/AppTranslocation/68F988E3-3927-4EEF-9B28-63546E4E7424/d/Atom.app/Contents/Resources/app/src/view-registry.js:187:15)
    at /private/var/folders/f9/_mpdvpsx30xfywgv_4ptdbzh0000gn/T/AppTranslocation/68F988E3-3927-4EEF-9B28-63546E4E7424/d/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:54.5.0 symbols-view:toggle-file-symbols (input.hidden-input)
  3x -1:51.3.0 core:backspace (input.hidden-input)
     -1:14.4.0 command-palette:toggle (input.hidden-input)
  8x -1:11.1.0 core:move-down (input.hidden-input)
     -1:06.5.0 core:move-up (input.hidden-input)
  5x -1:05.7.0 core:move-down (input.hidden-input)
     -0:59.9.0 core:confirm (input.hidden-input)
     -0:59.9.0 github:discard-all-changes (input.hidden-input)
     -0:53.4.0 core:move-up (input.hidden-input)
     -0:46.5.0 command-palette:toggle (div.github-StagingView.unstaged-changes-focused)
  4x -0:40.9.0 core:backspace (input.hidden-input)
     -0:39.5.0 core:move-up (input.hidden-input)
     -0:37.9.0 core:move-down (input.hidden-input)
 29x -0:35.9.0 core:move-up (input.hidden-input)
     -0:14.1.0 core:confirm (input.hidden-input)
     -0:14.1.0 github:view-unstaged-changes-for-current-file (div.github-StagingView.unstaged-changes-focused)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.5 
atom-typescript 11.0.9 
autocomplete-js-import 1.4.0 
autocomplete-paths 2.12.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
gpp-compiler 3.0.7 
highlight-selected 0.13.1 
intentions 1.1.5 
language-matlab 0.2.1 
linter 2.2.0 
linter-jshint 3.1.6 
linter-matlab 1.1.0 
linter-ui-default 1.6.10 
pigments 0.40.2 
seti-icons 1.5.4 
simple-drag-drop-text 0.3.6 
```

**Comment by rsese** [comment] 2017-10-11 20:16
Thanks for the report!

This looks like a duplicate of https://github.com/atom/github/issues/935 so you may want to subscribe there for updates.  If you have steps to reproduce, please let us know in the issue.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-11 20:16 UTC
