### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by JakeLambourn** [atom/atom#20523] opened 2020-03-17 15:15 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0-nightly2 x64
**Electron**: 4.2.7
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:160

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_KeyboardLayoutManager (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:14:2778016)
    at get_manager (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:14:2778118)
    at Object.getCurrentKeyboardLayout (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:14:2778244)
    at e.keystrokeForKeyboardEvent (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:14:1081110)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:1253631)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:1251616)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Nightly.app/Contents/Resources/app/static/<embedded>:11:284744)
```

### Commands

```
 25x -0:12.9.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.17 
laravel 0.7.1 
Quick-JavaScript 2.2.0 
teletype 0.13.4 
```

**Comment by perrosnk** [comment] 2020-03-19 01:13
+1 I am having the same issue

**Comment by ajithomasv** [comment] 2020-04-10 11:11
started getting the same issue after updating to 1.40.0

Issue: After upgrading to 1.40.0 while trying to install packages from Preferences-->Install. This issue is coming while typing something to the package search box in Install package section

OS: Mac OS Mojave (10.14.6)
Thrown From: Install Packages

**Comment by sadick254** [comment] 2020-09-01 16:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-01 16:20 UTC
