### ISSUE TITLE
no prompt for saving changes when close window in macOS Sierra

### ISSUE THREAD

**Issue by pkudemonhunter** [atom/atom#13895] opened 2017-02-28 14:08 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * [ X ] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [ X ] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [ X ] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [ X ] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [ X ] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

changes not saved when close window in macOS Sierra
Core Setting: By default, Restore Previous Windows on Start is checked.

### Steps to Reproduce

1. default installation of Atom 
2. create a project
3. create a new file
4. type in "asdf"
5. choose Menu->File->Close Window
6. reopen Atom

**Expected behavior:** [What you expect to happen]

 untitled document opens, with "asdf" content

**Actual behavior:** 

* untitled document opens, with no content

**Expected and Actual behaviour:**

* 'Close Pane', 'Close Tab', and 'Close all Tab' prompts to save changes
* 'Command-Q' to close Atom, then reopen Atom, "asdf" content appears

**Reproduces how often:** 

Always

### Versions

```
➜  ~ /Applications/Atom.app/Contents/MacOS/Atom --version
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

macOS Sierra 10.12.2
Windows client 1.14.3 does not have this issue
```

### Additional Information

No

**Comment by eduncan911** [comment] 2017-03-01 14:32
This works fine for me with EXISTING files that I open and edit.

The catch is the file has to EXIST on the system first, before you edit it.  Simply creating a new Tab and typing a few chars is not enough.  It to be an existing file first.

This is actually similar to VIM behavior as well: Vim can't shadow a buffer for a file that doesn't exist.  You have to save it at least once for any new changes in a buffer to save to a temp file.

--

Unless this is a bug (I can't reproduce it with Atom version 1.14.4 on macOS 10.12.3), I say this issue is invalid and to be closed as "Works as Designed."

**Comment by rsese** [comment] 2017-03-01 23:26
With `Restore Previous Windows on Start`, I'm unable to reproduce.  After running through the steps to reproduce, the untitled file has the content I typed into it when re-opening Atom.

I did however notice as well that if you close the window or quit Atom, you're not prompted with the unsaved changes dialog.  If you just try to close the tab, you are prompted.

**Comment by pkudemonhunter** [comment] 2017-03-02 02:25
Hi rsese,,are you using macOS or Windows? This issue does not appear on my Windows Box, but on my macOS box.

**Comment by pkudemonhunter** [comment] 2017-03-02 02:43
Hi eduncan911, I don't think it is related with EXISTING file. On my box, after re-opening an EXISTING file, previous saved content will show up, and new changes will gone. Could you help to confirm that you used "Menu->Close Window" to close Atom window? cause otherwise it won't have this issue.

**Comment by eduncan911** [comment] 2017-03-02 04:19
@pkudemonhunter I use CMD-Q to quit the entire application.

**Comment by rsese** [comment] 2017-03-02 06:53
> Hi rsese,,are you using macOS or Windows? This issue does not appear on my Windows Box, but on my macOS box.

Sorry I didn't mention, I tested on macOS 10.12.3.

But now that I poke at this again, I think I'm seeing the behavior you described with your steps to reproduce.  I must have not followed your step 5 correctly initially:

> 5. choose Menu->File->Close Window

If I Close Window, then I see the same behavior after I open a new window with `File > New Window`.

I had to play around a bit more but I found that in this case, when you just open a new window, there's no associated project at that point.  If you use `File > Reopen Project` and choose the project you added in your step (2), then the untitled document with the text you typed is restored.

The only catch I found is that after creating a new window, the Reopen Project list is empty.  So I had to open a different project directory first (not the project directory from your step (2)), and then use `File > Reopen Project` and choose the project from your step (2).

I think a similar issue I saw recently was https://github.com/atom/atom/issues/13861 and then maybe your report is related to this higher level issue https://github.com/atom/atom/issues/13873.   @ungb - do you think we should add this issue to https://github.com/atom/atom/issues/13873 or do you think it's a dupe of another issue that I haven't come across yet?  Or am I mis-understanding something?

**Comment by pkudemonhunter** [comment] 2017-03-02 07:28
@eduncan911 CMD-Q won't trigger this issue, could you try CMD-SHIFT-W?

**Comment by pkudemonhunter** [comment] 2017-03-02 07:38
@rsese thanks for the feedback! After following your step exactly, I can restore the previous project if I open a different project directory first. glad to know this.

Before opening this issue, I do read about #13861 and #13873 . I think a key difference is that in their cases: `Restore Previous Windows on Start` is NOT checked, while in my cases it is checked. So I raise this issue.

**Comment by 50Wliu** [comment] 2017-03-02 15:19
I believe Cmd-Shift-W is fundamentally different from Cmd-Q on macOS.  @maxbrunsfeld sorry to keep bothering you with these types of issues, but you always seem to explain it nicely.

**Comment by maxbrunsfeld** [comment] 2017-03-02 17:49
Yeah, when you close all of your Atom windows with `cmd-shift-w`, you've put Atom into a new state: the state with no windows. So then, when you quit Atom and reopen it, it restores *that* state  (well, it opens an empty window by default).

If you want to be able to restore atom with some windows open, you have to quit Atom with those windows open.

This is a general difference between Mac OS and other platforms; it trips a lot of people up.

**Closed by maxbrunsfeld** 2017-03-02 17:49 UTC

**Comment by rsese** [comment] 2017-03-02 18:56
Thanks for clearing things up @50Wliu @maxbrunsfeld :v:

Small note about this bit @pkudemonhunter:

> The only catch I found is that after creating a new window, the Reopen Project list is empty. So I had to open a different project directory first (not the project directory from your step (2)), and then use File > Reopen Project and choose the project from your step (2).

I found there's an existing issue for the empty Reopen Project list in case you want to subscribe:

https://github.com/atom/atom/issues/13758
