### ISSUE TITLE
Cannot use menus in atom on El Capitan

### ISSUE THREAD

**Issue by vernak2539** [atom/atom#7857] opened 2015-07-12 15:35 UTC
Having trouble using menus in atom on OS X El Capitan Beta (15A215h).

Atom version: 1.0.2

Here's the [youtube link](https://www.youtube.com/watch?v=NjCiqY-MwbU)

**Comment by sundarms** [comment] 2015-07-16 21:58
same here

**Comment by 50Wliu** [comment] 2015-07-16 22:24
Duplicate of #7811, please subscribe there for updates.

**Closed by 50Wliu** 2015-07-16 22:24 UTC
