### ISSUE TITLE
Editor text blinking when cursor's opacity is being animated

### ISSUE THREAD

**Issue by robertrossmann** [atom/atom#19630] opened 2019-07-03 16:22 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When I attempt to animate the cursor's `opacity` the text in the editor buffer starts to blink. It almost looks as if antialiasing is being turned off and on as the cursor transitions between the visible and transparent states. [Video (_.mov_)](https://github.com/atom/atom/files/3355863/atom-blinking.mov.zip).

This behaviour is most heavily observed on non-retina displays. My display is 27" 2560x1440. On retinas, I _think_ I am seeing an extremely subtle blinking as well, but I might be just imagining it... 🤷‍♂

This is the CSS override to make your cursor animated:

```less
atom-text-editor {
  .cursors .cursor {
    transition: opacity 0.2s;
  }
}
```

### Steps to Reproduce

1. Open your Atom's stylesheet
2. Add a custom CSS to animate your cursor's `opacity`
3. Observe current editor's text contents blinking

**Expected behavior:**

No blinking occurs, cursor is nice and animated

**Actual behavior:**

Cursor is nice and animated, but the whole text buffer is blinking

**Reproduces how often:**

100% of the time

### Versions

```sh
Atom    : 1.40.0-nightly22
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

### Additional Information

- Macbook Pro 15", macOS Mojave 10.14.5
- I **DO** have font smoothing enabled even though Mojave ships with this feature disabled:
  `defaults read -g CGFontRenderingFontSmoothingDisabled // -> 0`

[atom-blinking.mov.zip](https://github.com/atom/atom/files/3355863/atom-blinking.mov.zip)

**Comment by lee-dohm** [comment] 2019-07-03 16:44
I was unable to reproduce this using Atom Nightly v1.40.0-nightly22 on macOS 10.14.5, 2019 Retina iMac 27". I do not have font smoothing enabled.

**Comment by robertrossmann** [comment] 2019-07-03 17:37
I can confirm that disabling font smoothing (`CGFontRenderingFontSmoothingDisabled -> YES/1`) resolves the issue.

It is possible that this is a Mojave issue as I now remember seeing similar blinking issue in one or two other native apps on various occasions.

If you would like to investigate I will keep this open but feel free to close this issue if you feel that this is not Atom-specific.

Thanks a lot! ❤️

**Comment by lee-dohm** [comment] 2019-07-15 22:06
Thanks @robertrossmann. I'm going to go ahead and close this since disabled font smoothing is now a defaults-only option in more recent versions of macOS.

**Closed by lee-dohm** 2019-07-15 22:06 UTC
