### ISSUE TITLE
Windows installation failed 

### ISSUE THREAD

**Issue by Sasha1259** [atom/atom#18709] opened 2019-01-16 21:45 UTC
![untitled](https://user-images.githubusercontent.com/46729961/51280484-06dc9980-19e0-11e9-9537-f07ced92d40b.png)

I dont know what is the problem.I dont have antivirus and I tried to disable Windows Firewall but nothing happens.

Log:

2019-01-16 22:20:33> Program: Starting Squirrel Updater: --install .
2019-01-16 22:20:35> Program: Starting install, writing to C:\Users\Sasha\AppData\Local\SquirrelTemp
2019-01-16 22:20:36> Program: About to install to: C:\Users\Sasha\AppData\Local\atom
2019-01-16 22:20:36> Program: Install path C:\Users\Sasha\AppData\Local\atom already exists, burning it to the ground
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources\app.asar.unpacked\node_modules\cached-run-in-this-context\build: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources\app.asar.unpacked\node_modules\cached-run-in-this-context: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources\app.asar.unpacked\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources\app.asar.unpacked: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom: System.IO.IOExce

**Comment by rsese** [comment] 2019-01-16 22:01
Thanks for sending the log along this time @Sasha1259 - I don't see signs of the usual problems reported with Windows installs so can you give these steps a try?

1. Exit all Atom instances
2. Uninstall any Atom from `Control Panel > Add remove programs`
3. Manually delete %USERPROFILE%\AppData\Local\atom\
4. Reinstall Atom

**Comment by Sasha1259** [comment] 2019-01-16 22:18
Still Doesn't work,but it worked fine last week before I reinstalled Atom.Maybe I should download some other version of Atom.

**Comment by rsese** [comment] 2019-01-17 01:38
Hmm, can you share the new entries from SquirrelSetup.log?

**Comment by Sasha1259** [comment] 2019-01-17 18:40
I think that its same.







2019-01-16 22:20:33> Program: Starting Squirrel Updater: --install .
2019-01-16 22:20:35> Program: Starting install, writing to C:\Users\Sasha\AppData\Local\SquirrelTemp
2019-01-16 22:20:36> Program: About to install to: C:\Users\Sasha\AppData\Local\atom
2019-01-16 22:20:36> Program: Install path C:\Users\Sasha\AppData\Local\atom already exists, burning it to the ground
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources\app.asar.unpacked\node_modules\cached-run-in-this-context\build: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources\app.asar.unpacked\node_modules\cached-run-in-this-context: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources\app.asar.unpacked\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources\app.asar.unpacked: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0\resources: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom\app-1.34.0: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
2019-01-16 22:20:38> Utility: DeleteDirectory: could not delete - C:\Users\Sasha\AppData\Local\atom: System.IO.IOExce

**Comment by rsese** [comment] 2019-01-18 00:20
Hmm yeah it looks like there are no new entries.  Just to confirm, you deleted `C:\Users\Sasha\AppData\Local\atom` before trying to install again?  

If you run through https://github.com/atom/atom/issues/18709#issuecomment-454960735 again, can you double check that there are no Atom processes still running in Task Manager before trying to install?

**Comment by Sasha1259** [comment] 2019-01-18 20:57
@rsese There are no processes running and still doesn't work,but now new window pops out.


![untitled3](https://user-images.githubusercontent.com/46729961/51412486-0e30ae00-1b6c-11e9-9021-f5dcd374896d.png)

**Comment by rsese** [comment] 2019-01-18 23:36
No problem at all, thanks for bearing with me :v: 

If you give things a try again, the only other thing I might suggest is to restart your computer in case something/somewhere might be preventing the install?   

And yeah the .zip install works as a last resort, though note that it doesn't auto-update, you'll need to install manually with the latest .zip for each release.

Since you're up and running with the .zip install and there's no generally reproducible issue, we'll go ahead and close this out.

**Closed by rsese** 2019-01-18 23:36 UTC
Labels: installer, windows
