### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.46.0\res...

### ISSUE THREAD

**Issue by duboloms** [atom/atom#20700] opened 2020-05-06 12:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Кирилл\AppData\Local\atom\app-1.46.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: The specified module could not be found.
\\?\C:\Users\Кирилл\AppData\Local\atom\app-1.46.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:1:721712)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:2780724)
    at get_manager (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:2780826)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:2780952)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1081124)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1253631)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1251616)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:284744)
```

### Commands

```
  3x -0:09.1.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-run 0.9.7 
color-picker 2.3.0 
dark-one-dark-syntax 2.3.0 
emmet 2.4.3 
event-horizon-syntax 0.1.0 
file-icons 2.1.40 
highlight-selected 0.17.0 
ide-python 1.5.0 
inspired-github 0.10.0 
language-pug 0.0.22 
pacific-dark 0.5.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
seti-ui 1.11.0 
symbols-tree-view 0.14.0 
teletype 0.13.4 
```

**Comment by lkashef** [comment] 2020-05-08 18:08
Hey @duboloms, this seems like a duplicate of https://github.com/atom/atom/issues/20401, caused mainly by a faulty installation.

I will go ahead and close this one, feel free to comment or open a new issue if the problem still persists.

**Closed by lkashef** 2020-05-08 18:08 UTC
