### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.56.0\res...

### ISSUE THREAD

**Issue by AsmaahHAqq** [atom/atom#22276] opened 2021-04-25 03:00 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\asmaa\AppData\Local\atom\app-1.56.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\Users\asmaa\AppData\Local\atom\app-1.56.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:1:802769)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:2796891)
    at get_manager (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:2796993)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:2797119)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:1061934)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1220608)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:1218593)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:286076)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
color-picker 2.3.0 
csslint 1.2.0 
emmet 2.4.3 
hyperclick 0.1.5 
language-ejs 0.4.0 
minimap 4.38.3 
pigments 0.40.6 
```

**Comment by ThatXliner** [comment] 2021-04-28 15:05
Possible duplicate of #21285

**Closed** 2021-04-28 19:44 UTC
