### ISSUE TITLE
Atom crashes on copy/paste

### ISSUE THREAD

**Issue by lancekuttner** [atom/atom#6280] opened 2015-04-07 08:24 UTC
I am sure you have picked this up by now, but I am experiencing crashes when I copy/paste.

Initially I suspected that it was theme-related, but I have disabled all the themes I installed and still getting the same problem.

**Comment by Fank** [comment] 2015-04-07 08:33
Duplicate of #4923

**Closed** 2015-04-07 09:08 UTC
