### ISSUE TITLE
Syntax highlighting is wrong when putting SQL queries in PHP strings

### ISSUE THREAD

**Issue by matafokka** [atom/atom#19027] opened 2019-03-21 17:51 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Syntax highlighting is wrong when putting SQL queries in PHP strings.

### Steps to Reproduce

1. Write: $myvar = "AND (";
2. Write any code after that string
3. Enjoy wrong highlighting

**Expected behavior:** Right highlighting

**Actual behavior:** Everything is highlighted as a string

**Reproduces how often:** 100%

### Versions

Tried on latest version: 1.35.1 x64

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

![1](https://user-images.githubusercontent.com/34414488/54773503-c6d1a700-4c1a-11e9-9de2-b6f8786062e1.png)
![2](https://user-images.githubusercontent.com/34414488/54773504-c6d1a700-4c1a-11e9-849c-fd530f0a2177.png)

**Comment by rsese** [comment] 2019-03-21 19:41
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/language-php/issues/333 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-03-21 19:41 UTC
