### ISSUE TITLE
Multiple instances of Atom running on OSX

### ISSUE THREAD

**Issue by elliotcm** [atom/atom#13939] opened 2017-03-06 09:48 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom opens multiple instances of itself.  It seems to be related to different versions.

### Steps to Reproduce

1. Have atom open.
2. atom is upgraded without restarting, perhaps?
3. Use `atom` command to open a folder.

**Expected behavior:**

Atom opens a new window within the same instance.

**Actual behavior:**

Atom opens a new instance of the main application:
<img width="174" alt="screen shot 2017-03-06 at 09 42 20" src="https://cloud.githubusercontent.com/assets/109225/23604757/f62c04c4-0251-11e7-898c-15dc163adc23.png">

Both these versions were running at the same time:
<img width="240" alt="screen shot 2017-03-06 at 09 43 14" src="https://cloud.githubusercontent.com/assets/109225/23604756/f62bd3fa-0251-11e7-9b6a-c68d4c25499e.png">
<img width="240" alt="screen shot 2017-03-06 at 09 43 24" src="https://cloud.githubusercontent.com/assets/109225/23604758/f62d7084-0251-11e7-92a6-d8f954785561.png">

**Reproduces how often:**
100% under these circumstances.

### Versions

See screenshots.

**Comment by Dayjo** [comment] 2017-03-06 10:58
I have also had this problem previously (well, every time I've updated). Generally, after updating, I close everything and most of the time the old version disappears from the menu once I relaunch.

**Comment by rsese** [comment] 2017-03-06 17:39
Thanks for taking the time to contribute!

We noticed that this may be a duplicate of https://github.com/atom/atom/issues/9117. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-06 17:39 UTC

**Comment by elliotcm** [comment] 2017-03-06 17:47
@rsese Thanks for pointing me at that other issue.  This is indeed a duplicate.

That said, it is a little condescending even in a canned response to point me at github's search box when I already indicated that I checked for duplicates before posting.  The volume of issues open for atom often results in searches returning pages of unrelated issues.

**Comment by 50Wliu** [comment] 2017-03-06 18:09
It's mostly for consistency reasons.  More often than not people will check the checkbox without going through all the steps as a "hey look, I filled out the prereqs, now give me more attention" type of thing.  Don't take it negatively - we're aware that there's a ton of issues open, and sometimes the search box isn't that helpful :).
