### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by mMerlin** [atom/atom#5790] opened 2015-02-27 21:28 UTC
The sequence that lead to the crash, although simple testing could not reproduce:

Search and replace using regex (including using $1 for replace)
Go to do another search, but did not switch off regex mode
First character of the search was "."
The editor 'froze' doing the match for any character
Got a not responding message
Told it to keep waiting
After awhile longer, crash

The crash did not provide a stack trace or other information.  Below is an extract from a previous report that did have the details.  This should still be all current.

**Atom Version**: 0.182.0-d1e6dba
**System**: linux 3.18.7-200.fc21.i686

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "autoIndentOnPaste": false,
    "showInvisibles": true,
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by mark-hahn** [comment] 2015-02-27 23:58
I assume you ran out of memory.  You might be able to reproduce it by
limiting your memory somehow.  Maybe open 20 tabs in a chrome browser?

**Comment by 50Wliu** [comment] 2015-02-28 01:02
Chrome won't crash due to low memory.  Instead it'll shut down each tab with a "Page has crashed" error.

**Comment by bojidar-bg** [comment] 2015-03-26 08:18
Almost able to reproduce it. Take a large file (~97000 chars) and search by '.' as an regex. After it borders all selections, replace by ".." (or some other two characters). Press "Replace all" and keep waiting. On my computer it goes to 1.5 GiB, and uses one of the cores. (still working after 10 minutes, but if I had only 2GiB on my machine, I think I would have crashed).

**Comment by kevinsawicki** [comment] 2015-07-21 17:50
I believe this is essentially the same as https://github.com/atom/find-and-replace/issues/145 which is find and replace having poor performance for common patterns such as `.`, `\n`, etc.

There was a lot of work done pre-1.0 for this and the open issue should cover the remaining items so I'm going to close this out here.

**Closed by kevinsawicki** 2015-07-21 17:50 UTC
Labels: crash, needs-reproduction
