### ISSUE TITLE
Ambiguity between default and overridden values in the config

### ISSUE THREAD

**Issue by slavadir** [atom/atom#12103] opened 2016-07-05 15:51 UTC
### Description

There is an ambiguity in the config between default and overridden values. Sometimes you want to set a value which might be equal to the "original" default value. However, atom detects that and removes it automatically, causing the actual default value (in "*") to be used.

### Steps to Reproduce

1. Set default ("*") tab length to 4
2. Try to set other language's tab length to 2

Since 2 is the default value, it's automatically removed and causes the "*" default of 4 to be used.

Before save:
```coffee
"*":
  editor:
    tabLength: 4
".coffee.source":
  editor:
    tabLength: 2
".c.source":
  editor:
    tabLength: 2
".cpp.source":
  editor:
    tabLength: 2
".go.source":
  editor:
    tabLength: 2
".python.source":
  editor:
    tabLength: 2
```

After save:
```coffee
"*":
  editor:
    tabLength: 4
".c.source":
  editor:
    tabLength: 4
".coffee.source":
  editor:
    tabLength: 4
".cpp.source":
  editor:
    tabLength: 4
".go.source":
  editor:
    tabLength: 4
".python.source":
  editor:
    tabLength: 2

```

Note: this is not a mistake, Python actually does preserve the desired value of 2. Why? Because its default value is 4, not 2.

### Versions

Tested with Atom 1.8.0, using a completely clean, freshly created .atom directory in Windows 10 64bit.

**Comment by lee-dohm** [comment] 2016-07-06 23:11
This is a duplicate of https://github.com/atom/settings-view/issues/774. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-06 23:11 UTC
