### ISSUE TITLE
After 0.168 not able to press enter in any file

### ISSUE THREAD

**Issue by bobber205** [atom/atom#4925] opened 2015-01-08 19:13 UTC
Enter does nothing.
***Alt-enter*** is needed to make a new line.
Also just updated to 169 and it persists. 
So far happening in both .haml files, ruby and js files.

**Comment by bobber205** [comment] 2015-01-08 19:14
Looks like Command+/ doesn't do comment a line out anymore either? :(

**Comment by bobber205** [comment] 2015-01-08 19:14
Tabbing also broken.

**Comment by bobber205** [comment] 2015-01-08 19:17
Looks like this is issue with autocomplete-plus plugin. Reopening there.

**Comment by bobber205** [comment] 2015-01-08 19:27
Reopening because this keeps happening even with that plugin turned off.

**Comment by 50Wliu** [comment] 2015-01-08 20:11
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by bobber205** [comment] 2015-01-08 20:57
I've been in safe mode off and on all day and been seeing this all day. 
The best info I have is that it started with 168

**Comment by postcasio** [comment] 2015-01-08 22:42
Do you have emmet installed? I've had this happen a couple of times and checking keybindings showed emmet was taking over the keybind.

**Comment by bobber205** [comment] 2015-01-08 22:53
Emmet is indeed the cause. Uninstalled and cannot repo issue.

On Thu, Jan 8, 2015 at 2:42 PM, dominic <notifications@github.com> wrote:

> Do you have emmet installed? I've had this happen a couple of times and
> checking keybindings showed emmet was taking over the keybind.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/4925#issuecomment-69263734>.
>



-- 
Buoyancy and displacement float my boat.

**Comment by lee-dohm** [comment] 2015-01-09 01:52
Closing since this seems to be resolved. Thanks @postcasio, you beat me to the punch :laughing:

Let us know if the issue reoccurs!

**Closed by lee-dohm** 2015-01-09 01:52 UTC
