### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

### ISSUE THREAD

**Issue by mvaneijgen** [atom/atom#9109] opened 2015-10-11 11:41 UTC
1. Open two files an `.css` and any other file
2. View > Panes > Split left
3. trying to save the `.css` file and I get this error 

This doesn't happen with a `.php` file only with a `.css` file as far as I tested.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

TypeError: Cannot read property 'getTokenIterator' of undefined
    at LanguageMode.module.exports.LanguageMode.suggestedIndentForTokenizedLineAtBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:300:31)
    at LanguageMode.module.exports.LanguageMode.suggestedIndentForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:289:19)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:367:26)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRows (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:361:14)
    at TextEditor._results.push._this.(anonymous function) [as autoIndentBufferRows] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/delegato/lib/delegator.js:67:61)
    at /Users/mvaneijgen/.atom/init.coffee:18:12
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1012:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
```

### Commands

```
     -4:04.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:04.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -4:03.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -4:02.1.0 core:select-right (atom-text-editor.editor.is-focused)
     -4:00.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:59.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:59.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -3:55.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:53.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -3:49.3.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -3:48.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:44.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:01.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 13,
    "lineHeight": 1.4,
    "autoIndent": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
change-case, v0.6.0
emmet, v2.3.12
pigments, v0.12.0
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-10-11 12:06
@mvaneijgen Are you able to reliably reproduce this? Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by mvaneijgen** [comment] 2015-10-11 12:43
No. Could not reproduce in save mode. 

I uninstalled `change-case, v0.6.0` and `emmet, v2.3.12` this seems to have fixed the problem.

**Comment by izuzak** [comment] 2015-10-11 13:03
Thanks for confirming, @mvaneijgen. I also noticed that your init script is in the stack trace:

```
    at /Users/mvaneijgen/.atom/init.coffee:18:12
```

Can you share the contents of your init script here? Also, can you try re-enabling change-case and emmet, but removing everything from your init script, and see if that helps?

**Comment by mvaneijgen** [comment] 2015-10-11 13:05
```atom.workspace.observeTextEditors (editor) ->
  excludedGrammars = ['source.coffee', 'source.yaml']
  editor.buffer.onWillSave ->
    currentGrammar = editor.getGrammar()?.scopeName
    return if currentGrammar in excludedGrammars
    editor.autoIndentBufferRows 0, editor.getBuffer().getLineCount() - 1
``` is in my init script.

**Comment by izuzak** [comment] 2015-10-11 18:44
@mvaneijgen Can you also answer this question from my comment above?

> Also, can you try re-enabling change-case and emmet, but removing everything from your init script, and see if that helps?

Thanks! Also closing this since it doesn't seems to be a problem in Atom.

**Closed by izuzak** 2015-10-11 18:44 UTC
Labels: needs-reproduction, uncaught-exception

**Comment by mvaneijgen** [comment] 2015-10-13 08:41
Did a clean install of Atom, issue is still there.

**Comment by izuzak** [comment] 2015-10-13 08:44
@mvaneijgen That's because you still have content in your init.coffee file. 

Go to Atom > Open your init script, delete all content in your init script, then restart Atom, and see if you can reproduce the problem then.

<img width="261" alt="screen shot 2015-10-13 at 10 42 56" src="https://cloud.githubusercontent.com/assets/38924/10449963/3dbacbd8-7197-11e5-968a-4469abf666d1.png">

When you re-install Atom, your local configuration files (such as init.coffee and styles.less) are not deleted. You can delete them manually by deleting the .atom folder in your home directory.
