### ISSUE TITLE
[Feature request] Save position in Packages window when going into plugin settings

### ISSUE THREAD

**Issue by mrthebob** [atom/atom#14923] opened 2017-06-29 19:18 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I'm working with a list of plugins - whether installing a new plugin or going through settings or current plugins, or whatever, I'll be scrolling down a lengthy list, then I'll select one (or its settings), which will take me into the plugin's settings.  Now...  I want to go back to the list **to the place in the list where I just was - not at the beginning of the list!!!!**) It's kind of a pain to have to remember where I was and re-scroll back there every single time.

### Steps to Reproduce

1. Pull up any lengthy list of plugins - whether by search or by having a bunch of plugins listed
2. Scroll somewhere in the middle or toward the end of the list
3. Click on settings for a plugin
4. Try to go back to where you were before

**Expected behavior:** There should be some way to go back to the list and be where you just were in the list.  OR have the settings for the given plugin open in a new tab.  

**Actual behavior:** This doesn't happen

**Reproduces how often:** Every time

### Versions

All

### Additional Information

**Comment by Ben3eeE** [comment] 2017-08-18 09:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/settings-view/issues/361. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-18 09:24 UTC
Labels: enhancement
