### ISSUE TITLE
The folded code will be copied after the other folded code

### ISSUE THREAD

**Issue by 1030504258** [atom/atom#18599] opened 2018-12-19 08:52 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![default](https://user-images.githubusercontent.com/8848263/50208109-4dbc7c80-03ab-11e9-87da-4481d91cc162.gif)

[Multiple lines of copy appear in code folding]

### Steps to Reproduce

1. [First Step]
> Expand the code block
2. [Second Step]
> Hide code block
3. [and so on...]
> The folded code will be copied after the other folded code

**Expected behavior:** [What you expect to happen]
> Normal folding
**Actual behavior:** [What actually happens]
> It doesn't fold properly
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

```shell
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 3.7.1
git 2.19.2.windows.1
visual studio
```

### Additional Information

```shell
Community Packages (55) 
├── advanced-open-file@0.16.8
├── aligner@1.2.4
├── aligner-css@1.2.1
├── aligner-javascript@1.3.0
├── aligner-php@1.3.0
├── atom-autocomplete-caomei@0.0.5
├── atom-beautify@0.33.4
├── atom-clock@0.1.16
├── atom-eclipse-syntax@0.0.6
├── atom-html-preview@0.2.6
├── atom-ide-ui@0.13.0
├── atom-material-syntax@1.0.8
├── autocomplete-paths@2.12.2
├── autoprefixer@3.7.1
├── city-lights-syntax@1.1.8
├── color-picker@2.3.0
├── docblockr@0.13.7
├── double-tag@1.6.1
├── dracula-syntax@2.0.7
├── emmet@2.4.3
├── ex-mode@0.18.0
├── file-header@1.13.9
├── file-icons@2.1.27
├── git-plus@8.2.1
├── git-time-machine@2.1.0
├── highlight-selected@0.14.0
├── ide-php@0.7.17
├── ide-typescript@0.8.0
├── language-apache@1.8.0
├── language-ini@1.20.0
├── markdown-preview-enhanced@0.15.8
├── merge-conflicts@1.4.5
├── minimap@4.29.9
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-selection@4.5.0
├── minimap-split-diff@0.3.7
├── monokai@0.24.0
├── nord-atom-syntax@0.9.1
├── open-in-browser@0.5.2
├── pigments@0.40.2
├── platformio-ide-terminal@2.8.4
├── project-manager@3.3.6
├── regex-railroad-diagram@0.19.4
├── relative-numbers@0.9.0
├── remote-ftp@2.2.2
├── split-diff@1.5.3
├── Sublime-Style-Column-Selection@1.7.5
├── svg-preview@0.14.0
├── sync-settings@0.8.6
├── tree-view-git-status@1.5.2
└── vim-mode-plus@1.36.0
```

**Comment by 1030504258** [comment] 2018-12-19 09:01
> I'm a big fan of atom, which is now my main editor
---
@lee-dohm My friend, I am very sorry for the unpleasant before, please forgive me.
I have learned to submit questions with your template now.
Please remove the restrictions on my main account.
Now my main account cannot feed back atom problems

---
> My github master account：

|username|email|
|---|---|
`linjialiang`| `linjialiang@163.com`|

![github](https://user-images.githubusercontent.com/45992044/50209823-a130c980-03af-11e9-8f41-c509dd330668.png)

**Comment by lee-dohm** [comment] 2018-12-19 19:43
@linjialiang you have access again so long as you continue to follow the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md).

**Comment by rsese** [comment] 2018-12-19 21:49
Thanks for the report @1030504258!  It looks like your GIF isn't in safe mode, can you reproduce in safe mode?

Also, the behavior looks like a duplicate of https://github.com/atom/atom/issues/16078 but if you have steps to reproduce in safe mode, that would be super helpful.

**Comment by 1030504258** [comment] 2018-12-20 01:31
@lee-dohm Ok, my friend, I will submit the question according to the standard template

**Comment by linjialiang** [comment] 2018-12-20 01:43
@rsese This situation does not happen every time. I have not found the rule yet. I will give you feedback when I do find it

**Closed** 2019-01-17 17:58 UTC
Labels: more-information-needed
