### ISSUE TITLE
Open empty editor on startup not working

### ISSUE THREAD

**Issue by dkerzig** [atom/atom#12075] opened 2016-06-30 12:27 UTC
### Description

Atom does not open empty editor on startup even if I activate it in the settings.

### Steps to Reproduce

1. Activate "Open Empty Editor On Start" in Atoms core settings
2. Open any file or folder
3. Close Atom
4. Open Atom (even in --safe mode)

**Expected behavior:** Empty Editor

**Actual behavior:** Editor with all recently opened files/folders/tabs.

### Versions
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by Ben3eeE** [comment] 2016-06-30 12:35
https://github.com/atom/atom/issues/10623?

**Comment by dkerzig** [comment] 2016-06-30 12:39
You are completely right, I am so sorry. How could I've overseen that, actually I did a search...
Thanks

**Comment by Paviluf** [comment] 2016-07-03 09:36
Since it's a duplicate you can close it now. Thanks.

**Comment by thomasjo** [comment] 2016-07-03 13:00
Closing as duplicate of #10623.

**Closed by thomasjo** 2016-07-03 13:00 UTC
