### ISSUE TITLE
Uncaught TypeError: Invalid Point: (112, NaN)

### ISSUE THREAD

**Issue by odil-io** [atom/atom#16905] opened 2018-03-08 13:28 UTC
Steps to reproduce:

1. Open a .php document.
2. Try to type
3. ???
4. I don't really know why or how this happened, it just did.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (112, NaN)

```
At C:\Users\odil-io\AppData\Local\atom\app-1.24.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:950

TypeError: Invalid Point: (112, NaN)
    at Function.module.exports.Point.assertValid (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:345:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-marker.js:154:58)
    at changePosition (~/AppData/Local/atom/app-1.24.0/resources/app/src/cursor.js:68:25)
    at Cursor.changePosition (~/AppData/Local/atom/app-1.24.0/resources/app/src/cursor.js:713:11)
    at Cursor.setScreenPosition (~/AppData/Local/atom/app-1.24.0/resources/app/src/cursor.js:67:16)
    at Cursor.moveLeft (~/AppData/Local/atom/app-1.24.0/resources/app/src/cursor.js:288:18)
    at moveCursors.cursor (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:2553:52)
    at Array.forEach (native)
    at transact (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:2695:31)
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:943:24)
    at TextEditor.transact (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:1825:30)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:2694:23)
    at TextEditor.moveLeft (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:2553:23)
    at TextEditor.core:move-left (~/AppData/Local/atom/app-1.24.0/resources/app/src/register-default-commands.js:324:27)
    at HTMLElement.newCommandListeners.(anonymous function) (~/AppData/Local/atom/app-1.24.0/resources/app/src/register-default-commands.js:676:38)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:22.1.0 ftp-remote-edit:toggle (atom-pane.pane)
     -2:20 core:confirm (input.hidden-input)
  5x -0:18.7.0 core:move-right (input.hidden-input)
     -0:14.8.0 core:move-down (input.hidden-input)
     -0:14.7.0 core:move-left (input.hidden-input)
     -0:14.6.0 core:move-right (input.hidden-input)
     -0:14.5.0 core:move-down (input.hidden-input)
  3x -0:14.3.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
ftp-remote-edit 0.12.11 
sync-settings 0.8.5 
```

**Comment by odil-io** [comment] 2018-03-08 13:31
It seemed there was a hidden character after a closing tag (>).

Backspacing the line before resolved the issue some how. Possibly a false character created by changing the default mode to open files from UTF-8 to ISO-8859-1.

File was previously opened and saved in UTF-8.

**Comment by rsese** [comment] 2018-03-08 19:06
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14774 so you can subscribe there for updates if you'd like.

And thanks for sharing all the details you remembered about the error, I'll copy those over to https://github.com/atom/atom/issues/14774.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-08 19:06 UTC
