### ISSUE TITLE
Can't find package file in developer tools

### ISSUE THREAD

**Issue by bobrocke** [atom/atom#6935] opened 2015-05-24 16:19 UTC
Atom 0.201, Mac OS X 10.10.3

I've created a new package to work on, so the package folder has been symlinked into Atom, as expected.

But when I open Developer Tools -> Sources and try Cmd+P, I can't find my package files when searching in the resulting dialog.

What have I done wrong?

See also:

https://discuss.atom.io/t/cant-find-package-file-in-developer-tools/17118

**Comment by izuzak** [comment] 2015-05-24 16:58
Does this happen consistently or randomly? Do you not see any files for that package or only some files? Can you share a link to a package for which this happens so that we can try and reproduce? Has the package been activated and the file in question loaded/executed? (For example, if you start Atom and open devtools > sources and try to find the [deprecation-cop-view.js file](https://github.com/atom/deprecation-cop/blob/master/lib/deprecation-cop-view.coffee) -- you won't find it. However, if you _open_ the Deprecation Cop view from the command palette -- the file will show up in devtools because it's only then been loaded.)

**Comment by bobrocke** [comment] 2015-05-24 17:11
I think what was/is happening is that the package had not yet be executed, and so the files were not loaded yet.

Now to figure out why, with a break point set and the package's execution paused at that breakpoint, neither the call stack nor the scope variable panes show anything. They both say "Not Paused," although execution clearly is...

**Comment by izuzak** [comment] 2015-05-25 11:43
> Now to figure out why, with a break point set and the package's execution paused at that breakpoint, neither the call stack nor the scope variable panes show anything. They both say "Not Paused," although execution clearly is...

I'm not 100% sure I understand what that means. Does that mean that you're seeing the files from your package in the devtools now (sounds like you are), and there's some other problem now? If you'd like some help debugging this new problem -- screenshots and exact steps to reproduce the problem (+ link to the package you're playing with) would be helpful.

Gonna close this now but let me know if the issue you reported still isn't resolved. :v:

**Closed by izuzak** 2015-05-25 11:43 UTC
Labels: more-information-needed

**Comment by bobrocke** [comment] 2015-05-25 11:48
Sorry for the mixed messages.

Yes, I can open the package files now. Once I forced the package to be executed once, the files were available.

Although I can get the file to open now, and I can set what appears to be a breakpoint, execution won't pause at the breakpoint nor at `debugger;` statements. I'll open a new issue for that.

**Comment by izuzak** [comment] 2015-05-25 11:50
> I'll open a new issue for that.

:pray: Please provide _exact_ steps which reproduce the problem for you in that new issue. :pray:

**Comment by bobrocke** [comment] 2015-05-25 11:54
I hope I was clear in that issue:

https://github.com/atom/atom/issues/6938

**Comment by izuzak** [comment] 2015-05-25 11:55
> I hope I was clear in that issue:

Sorry, not clear for me and I'm not able to reproduce the issue. Exact steps to reproduce the issue would be really helpful. Thanks :bow:
