### ISSUE TITLE
The latest version cannot be opened

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#17552] opened 2018-06-22 01:52 UTC
![default](https://user-images.githubusercontent.com/8848263/41753765-fc522b6a-7601-11e8-8030-ebfcce19bc51.png)

![default](https://user-images.githubusercontent.com/8848263/41753754-dee309c8-7601-11e8-83ba-4d78a8b8385a.png)

**Comment by CJK-Regan** [comment] 2018-06-22 02:33
Same situation. It crashes on Windows 10

**Comment by Heier2013** [comment] 2018-06-22 02:45
same in mac

**Comment by ServiceYun** [comment] 2018-06-22 03:00
My mac is in the same situation. Version 10.13.5

**Comment by Varavarforvar** [comment] 2018-06-22 03:20
same with me

**Comment by coderbean** [comment] 2018-06-22 03:32
## if you are using shaodsocks,  try close shadowsocks or turn it to Global model or Manual model.
it works for me, but I do not know why

**Comment by linjialiang** [comment] 2018-06-22 03:44
@coderbean thank you!  Shaodsocks does not change when they become global

**Comment by Varavarforvar** [comment] 2018-06-22 03:48
@coderbean yet am i

**Comment by linjialiang** [comment] 2018-06-22 03:51
Shaodsocks system agent can be turned off

**Comment by fengerzh** [comment] 2018-06-22 05:50
Seems the way of Atom to fix a bug is to totally disable the feature related to bug.

**Comment by coderbean** [comment] 2018-06-22 08:14
Me: you crash from time to time.
Atom: what? Excuses me?
Me: you crash sometimes.
Atom: Alright，it will be fixed on next version.
......new version release......
Me: I can't ever open atom
Atom: No open, no bug, no fix. everybody happy.

**Comment by thomasjo** [comment] 2018-06-22 12:18
I'm closing this as a duplicate of #17557. Please subscribe there for updates.

**Closed by thomasjo** 2018-06-22 12:18 UTC

**Comment by laudukang** [comment] 2018-06-22 15:16
@coderbean  it works on windows 10 1709
