### ISSUE TITLE
Completion popups are offset in Atom 1.9.0beta0

### ISSUE THREAD

**Issue by albireox** [atom/atom#11963] opened 2016-06-11 17:49 UTC
The popup window for completion in Atom 1.9.0beta0 appear offset with respect to the cursor. This seems to happen for all themes.

![screen shot 2016-06-11 at 11 47 51](https://cloud.githubusercontent.com/assets/568775/15986674/86eeb3d6-2fca-11e6-8a6e-04f61ac5f03f.png)

## Versions
OSX 10.11.6

Atom    : 1.9.0-beta0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.4

**Comment by 50Wliu** [comment] 2016-06-11 17:58
I'm assuming you've tested this in safe mode as well?

**Comment by albireox** [comment] 2016-06-11 18:03
Sorry, forgot to do that. It seems to work fine there, although I'm not completely sure what's the expected behaviour in safe mode. Here's a screenshot

![screen shot 2016-06-11 at 12 01 20](https://cloud.githubusercontent.com/assets/568775/15986713/516449d6-2fcc-11e6-87ec-58e9f905a453.png)

**Comment by 50Wliu** [comment] 2016-06-11 18:05
Yeah, that looks like the expected behavior.  Since this seems to be a problem with one of your installed packages I'm going to close this.

**Closed by 50Wliu** 2016-06-11 18:05 UTC
Labels: bug, needs-reproduction
