### ISSUE TITLE
ctrl-delete does not remove CRLF

### ISSUE THREAD

**Issue by dwelle** [atom/atom#7662] opened 2015-07-02 21:03 UTC
By `ctrl-delete` I mean `editor:delete-to-next-word-boundary`, `editor:delete-to-end-of-word` or  `editor:select-to-beginning-of-word` (which is probably used by the first two commands).

I.e. when issuing the above commands in this position:

![image](https://cloud.githubusercontent.com/assets/5153846/8487587/5285ae6e-210d-11e5-868b-e41bb9378dd0.png)

__Nothing__ happens, the `CRLF` windows line-ending is not consumed.

Linux's `LF` works fine, though (`editor:delete-to-next-word-boundary`):

![image](https://cloud.githubusercontent.com/assets/5153846/8487775/7565e1b4-210e-11e5-9206-085256a411e9.png)

Also, the other way round (`editor:delete-to-previous-word-boundary` etc.) works fine.

Windows 7, Atom 1.0

**Comment by nycdotnet** [comment] 2015-08-13 16:09
This is also a problem with keyboard navigation.  When holding down CTRL and using the left arrow key, Atom will successfully navigate backward through a document one "word" at a time.  CTRL and right arrow also works *until* the end of the line is reached.  Then atom will stay there stuck at the end of the line when CTRL+Right arrow is pressed.  Right-arrow alone works fine to navigate to the first position of the next line, and then CTRL+Right will work again until the end of that line is reached.

**Comment by billybonks** [comment] 2015-10-02 07:06
@nycdotnet is this on windows ? seems to be working on mac but i use alt instead of control

**Comment by davidspiess** [comment] 2015-11-05 23:16
This problem is a nasty one.
It's caused by a regex in `wordRegExp` function in [cursor.coffee](https://github.com/atom/atom/blob/v1.1.0/src/cursor.coffee#L609)

`["^[\t ]*$"]` causes 0-length matches with CRLF line ending.

JavaScript treats CRLF pairs as two line breaks. ^ matches in the middle of and after CRLF, while $ matches before and in the middle of CRLF.

You can read more about this here https://github.com/atom/find-and-replace/issues/454

I tried to fix it with `["^[\t ]+$"]` as suggested in the issue above, but by running the testsuite empty lines do not count as words anymore. Maybe someone knows a solution for it.

**Comment by sanuj** [comment] 2016-01-07 13:50
Please close this issue as it was fixed in #9937.

**Comment by 50Wliu** [comment] 2016-01-07 14:06
Thanks @sanuj.

**Closed by 50Wliu** 2016-01-07 14:06 UTC
Labels: beginner, bug, help-wanted

**Comment by nycdotnet** [comment] 2016-01-14 13:49
Confirmed fixed - CTRL+right arrow on Windows still navigates word by word but DOES NOT get stuck at the end of a line anymore in a CRLF formatted document.  Thank you!
