### ISSUE TITLE
Is version 0.198.0 for OS X with wrong node version?

### ISSUE THREAD

**Issue by fishg** [atom/atom#6697] opened 2015-05-08 03:23 UTC
when I install  omnisharp-atom,I get this error:
npm WARN engine omnisharp-node-client@1.1.4: wanted: {"node":">=0.12.0","iojs":">=1.0.0","atom":">=0.194.0"} (current: {"node":"0.10.35","npm":"2.5.1"})

Then I test atom node version:
/Applications/Atom.app/Contents/Resources/app/apm/bin/node --version
v0.10.35

**Comment by thomasjo** [comment] 2015-05-08 06:39
This has been the case for a long time. `apm` still relies on Node.js v0.10.x. For reference, the bundled version was changed from [v0.10.33 to v0.10.35 on January 9](https://github.com/atom/apm/commit/56181c8f0a9aac062f5c5fb7b0797711aa84d5bc).

Closing since this is not a bug.

**Closed by thomasjo** 2015-05-08 06:39 UTC
Labels: question
