### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.31.2\ Inc'

### ISSUE THREAD

**Issue by a-thay** [atom/atom#18219] opened 2018-10-10 15:23 UTC
[Enter steps to reproduce:]

1. Create a new .html file in a project folder.
2. Drag and attempt to drop the file to another project folder within Atom.
3. Update Atom to latest version (1.31.1 to 1.31.2).
4. Retry; encountered the same error.

Note: Project folders are on an enterprise SharePoint directory. Prior to today, I've been able to move files around this way without encountering this error.

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\aaron.thayer\AppData\Local\atom\app-1.31.2\ Inc'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\aaron.thayer\AppData\Local\atom\app-1.31.2\ Inc'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:343:29)
    at TreeView.module.exports.TreeView.moveEntry (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/tree-view/lib/tree-view.js:1544:34)
    at TreeView.module.exports.TreeView.onDrop (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/tree-view/lib/tree-view.js:1844:37)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.31.2/resources/app/node_modules/tree-view/lib/tree-view.js:389:30)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.5 
atom-live-server 2.3.0 
atom-wrap-in-tag 0.6.0 
atomic-chrome 0.3.3 
color-picker 2.3.0 
language-vba 0.2.5 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.15.7 
markdown-writer 2.9.0 
multi-wrap-guide 1.1.6 
pandoc-convert 1.1.1 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 0.8.6 
teletype 0.13.3 
```

**Comment by rsese** [comment] 2018-10-14 02:46
Thanks for contributing!

Based on the stack trace, I'll close as a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

Also just to clarify, is `C:\Users\aaron.thayer\AppData\Local\atom\app-1.31.2\ Inc` the name of the directory you were trying to drag to?  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-14 02:46 UTC
