### ISSUE TITLE
directory lock problem

### ISSUE THREAD

**Issue by SemteulGaram** [atom/atom#13510] opened 2016-12-28 15:05 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I build, I want to delete the folder that contains the output that was created earlier and create a new folder
It's okay to erase the folder, but when I try to recreate the folder with the same name, it creates an error when file-tree of that folder is open in Atom.

### Steps to Reproduce

1. open some folder file tree on atom 
2. rmdir that folder
3. mkdir folder with the same name
4. Error occur

**Expected behavior:** directory cleared

**Actual behavior:** emit error: `Error: EPERM: operation not permitted, mkdir`

**Reproduces how often:** 100%

### Versions

Window 10 64bit

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

![img](http://i.imgur.com/CevMvek.png)

**Comment by 50Wliu** [comment] 2016-12-31 01:49
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3365. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-31 01:49 UTC
