### ISSUE TITLE
Settings menu not loading appropriately when right-clicking a file

### ISSUE THREAD

**Issue by daniboyg** [atom/atom#12683] opened 2016-09-13 15:03 UTC
I'm getting a misbehavior of the 'Settings' menu (via 'File' > 'Settings'). If I open atom via the command line (either 'atom' or 'atom --safe'), and open a file from the 'Open' option, everything works fine.

However, if I open the same file in Windows by right-clicking the file and selecting 'Open with atom' (launching a new instance of atom), when I go to the 'settings' menu and select 'Packages', 'Themes', or 'Updates', the system is unable to load any information about installed packages, etc.

![atom](https://cloud.githubusercontent.com/assets/21962654/18478619/d02c8980-79c9-11e6-9311-2f79c141c04c.png)

However, inside the 'Settings' menu, the information still appears for the submenus 'Settings' and 'Keybindings'.

I deactivated all non-core packages to see if this solved the problem - it didn't.

Some info about my system:

*OS: Windows 10, home edition, build 10.0.10586

*atom --version output:
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

* apm --version output:
apm  1.12.5
npm  3.10.5
node 4.4.5
python 3.5.1
git 2.9.3.windows.3
visual studio

**Comment by Ben3eeE** [comment] 2016-09-13 16:45
Try this:

1. Completely exit all instances of Atom.
2. Launch Atom in safe mode.
3. In the settings-view open the Systems tab and check all three options.
4. Close Atom and try to reproduce this issue.
5. In the settings-view systems tab check all options as you want.

From the picture the settings-view that opens is from an older version of Atom(No Systems tab is visible) so it is possible your shell integrations are not correctly updated.

**Comment by daniboyg** [comment] 2016-09-13 18:00
That worked!

Would it be advisable to update my atom installation? From the 'Settings' > 'Updates', my systems tells that all packages are up to date. At the 'Help' > 'Update' menu I also get the information that my system is up to date.

**Comment by Ben3eeE** [comment] 2016-09-14 05:02
As long as all launch options report Atom version 1.10.2 or newer in the about dialog you should be fine.

/cc @damieng another problem caused by shell integrations not updating.

**Comment by damieng** [comment] 2016-09-14 06:16
Yeah this has been fixed in master, 1.10 and 1.11 branches but won't take affect until the next releases, sorry for the inconvenience.

**Closed by damieng** 2016-09-14 06:16 UTC
