### ISSUE TITLE
Uncaught TypeError: packages[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by framehost** [atom/atom#15804] opened 2017-10-03 22:55 UTC
[Enter steps to reproduce:]

1. Open Atom. ( Doesn't matter if first launch or not.. )
2. Edit > Preferences > ( Attempt to ) Open Install Menu

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: packages[Symbol.iterator] is not a function

```
At /usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:390

TypeError: packages[Symbol.iterator] is not a function
    at InstallPanel.addPackageViews (/usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:390:30)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:461:26
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:68:26
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:160:22)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (/usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:65:25)
    at InstallPanel.loadFeaturedPackages (/usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:455:27)
    at new InstallPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:128:16)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:237:22
    at SettingsView.getOrCreatePanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:361:25)
    at SettingsView.showPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:419:30)
    at SettingsView.showDeferredPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:406:20)
    at SettingsView.addPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:335:20)
    at SettingsView.addCorePanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:325:18)
    at SettingsView.initializePanels (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:236:18)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:118:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Packages

I have not installed any packages aside from any that are installed by default. Nor have I been able to..

**Comment by rsese** [comment] 2017-10-04 04:54
Thanks for the report - I think this looks like a duplicate of https://github.com/atom/settings-view/issues/962, so we'll close in favor of that issue.  Looks like we haven't been able to repro it - if you can let us know in that issue if the error is reproducible in safe mode (`atom --safe`) and any other details that you think might be relevant, please do.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-04 04:54 UTC

**Comment by rsese** [comment] 2018-02-19 23:34
:+1:  it looks like you commented in #962 where this is being tracked and there's a potential fix in https://github.com/atom/settings-view/pull/1034 if you want to subscribe for updates.
