### ISSUE TITLE
feature request: Tree View: 'search' a file by typing

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#7408] opened 2015-06-25 07:35 UTC
When a folder has a lot of files, more than fits on the screen vertically, I would like to 'focus' a specific file by typing the first letters of the file.
I notice 'A' and 'D' are already mapped by default to _add_ and _duplicate_, so I propse to add 'F' (or 'S') for _find_ (or _search_) to use following keyboard input for finding a matching file and focusing it, bringing it into view if it's off screen.
A comparative user experience is in Windows Explorer, also when done there on the folder tree-view, if I remember correctly, the search is done over all currently visible nodes of the tree.

**Comment by mehcode** [comment] 2015-06-25 07:38
Is hitting <kbd>Ctrl-P</kbd> not sufficient? Or are you thinking of something completely different?

**Comment by mnquintana** [comment] 2015-06-25 12:16
Thanks for the suggestion! This is a duplicate of https://github.com/atom/tree-view/issues/200 and https://github.com/atom/tree-view/issues/159 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-25 12:16 UTC

**Comment by giorgiobeggiora** [comment] 2018-01-19 14:50
CTRL+P is not sufficient, because it does not show folders
