### ISSUE TITLE
Uncaught Error: spawn /Users/admin/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Content...

### ISSUE THREAD

**Issue by kwokandy** [atom/atom#10629] opened 2016-01-31 07:56 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/admin/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/admin/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/admin/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/admin/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.setPaths (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:217:27)
    at /Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:184:27
    at Function.module.exports.Emitter.simpleDispatch (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.setPath (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:342:27)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1048:12)
    at TextEditor.module.exports.TextEditor.saveAs (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:608:26)
    at Pane.module.exports.Pane.saveItemAs (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:558:16)
    at Pane.module.exports.Pane.saveActiveItemAs (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:521:19)
    at Workspace.module.exports.Workspace.saveActivePaneItemAs (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:647:35)
    at atom-workspace.commandRegistry.add.core:save-as (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:176:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Users/admin/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -4:31.3.0 editor:split-selections-into-lines (atom-text-editor.editor.is-focused)
     -4:28.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  7x -4:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:02.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:55.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:51.8.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -3:42 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:41.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:41 core:move-down (atom-text-editor.editor.is-focused)
     -3:40.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:36.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:32.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:26.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:24.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:01.7.0 core:copy (atom-text-editor.editor.is-focused)
     -0:42.9.0 core:save-as (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by kwokandy** [comment] 2016-01-31 07:58
I wrote 4 lines , save it. Things were ok until this error popped out... The file has been saved

**Comment by demhydraz** [comment] 2016-01-31 12:19
Looks like a duplicate of #9559, no?

**Comment by 50Wliu** [comment] 2016-01-31 16:15
Yep, thanks @demhydraz!

**Closed by 50Wliu** 2016-01-31 16:15 UTC

**Comment by benogle** [comment] 2016-02-01 21:27
@kwokandy what were you doing when this happened? Was it around the same time as an atom update? Did you move the app on disk by chance when it was running?
