### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked, open 'D:\dev\cpp\pagmo-1.1.7\src\problems.h'

### ISSUE THREAD

**Issue by elypma** [atom/atom#9296] opened 2015-10-26 21:22 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, open 'D:\dev\cpp\pagmo-1.1.7\src\problems.h'

```
At C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:128

Error: EBUSY: resource busy or locked, open 'D:\dev\cpp\pagmo-1.1.7\src\problems.h'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
  at File.module.exports.File.readSync (C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:261:36)
  at TextBuffer.module.exports.TextBuffer.updateCachedDiskContentsSync (C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1072:85)
  at C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1213:17
  at Emitter.module.exports.Emitter.emit (C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:447:40
  at _fulfilled (C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:756:13)
  at C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:564:44
  at flush (C:\Users\eypma\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\q\q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
     -9:27.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:12.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-sql",
      "language-toml",
      "markdown-preview",
      "atom-terminal-panel"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-material-ui, v0.6.2
autocomplete-python, v0.6.1
build-tools, v3.7.3
file-icons, v1.6.9
file-types, v0.5.1
highlight-selected, v0.10.1
language-batch, v0.3.3
language-cmake, v0.1.4
language-fortran, v2.0.0
language-ini, v1.12.0
language-lua, v0.9.4
language-nsis, v3.1.1
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-highlight-selected, v4.3.1
nsis-plugins, v1.0.2
open-recent, v2.3.0
pretty-json, v0.4.1
project-manager, v2.6.1
project-ring, v0.35.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-10-26 22:27
Closing as a duplicate of #9031 and/or #8976.

**Closed by 50Wliu** 2015-10-26 22:27 UTC
