### ISSUE TITLE
Atom opens up every clicked folder automatically. 

### ISSUE THREAD

**Issue by harikrishkk** [atom/atom#10501] opened 2016-01-19 21:03 UTC
Whenever i double click any folder, that keeps opening in the Atom editor, even if that folder contains a pdf or a word doc. Is there any ways to disable this annoying behavior? 

![image](https://cloud.githubusercontent.com/assets/5024456/12431901/1bbe611e-bf1e-11e5-98b4-3a7824b0e3be.png)

**Comment by mnquintana** [comment] 2016-01-19 21:06
This looks like a duplicate of https://github.com/atom/tree-view/issues/411 – feel free to subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) for a guide on where to post issues, including searching for duplicates.

**Closed by mnquintana** 2016-01-19 21:06 UTC
