### ISSUE TITLE
open an image many times

### ISSUE THREAD

**Issue by QiiSyhx** [atom/atom#12100] opened 2016-07-05 09:23 UTC
double click an image,open 1 times.
single click an image,preview 
then double click the image, will open the image in a new window.

**Comment by Ben3eeE** [comment] 2016-07-05 09:27
This is a duplicate of https://github.com/atom/image-view/issues/48

**Comment by thomasjo** [comment] 2016-07-05 09:29
Closing as a duplicate of atom/image-view#48.

---
Thanks @Ben3eeE 🙇

**Closed by thomasjo** 2016-07-05 09:29 UTC
