### ISSUE TITLE
"Open in new window" doesn't work on buffers that don't belong to a file

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#16608] opened 2018-01-21 00:00 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Right-clicking on a tab and then selecting "Open in new window" doesn't work for buffers that don't belong to a file

### Steps to Reproduce

1. Create a new tab
2. Write something in the buffer
3. Right-click on the tab and then click con "Open in new Window"

**Expected behavior:** 

A new window with the newly created buffer should appear.

**Actual behavior:**

Nothing

**Reproduces how often:**

Always

### Versions

1.23.3

**Comment by Ben3eeE** [comment] 2018-01-22 09:09
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/400. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-01-22 09:09 UTC
Labels: duplicate
