### ISSUE TITLE
Invalid syntax coloring for Python code containing SQL-like string literals

### ISSUE THREAD

**Issue by krzysztof-sikorski** [atom/atom#13387] opened 2016-12-05 16:40 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Syntax coloring do not work correctly for Python code that follows a string literal with a certain content.

After the literal the code is colored as string, as if the literal did not end.

I tried a few variants to pin down the bug, and the conditions seem to be at least:
1) The literal is a triple-quoted string, using double quotes. It does not matter if it spans a single line or multiple lines.
2) The literal contains an SQL keyword in single quotes.
3) The keyword is uppercase.
4) Not all SQL keywords trigger the bug. SELECT and UPDATE do, INSERT do not.

### Steps to Reproduce

1. Open a new tab, switch language to Python
2. Enter following code:
```python
"""'SELECT'"""
pass
```

**Expected behavior:**

Second line should be colored as code.

**Actual behavior:**

Second line is colored as part of string literal.

### Versions

OS: Linux Mint 18

Atom:
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

APM:
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.11.0

**Comment by 50Wliu** [comment] 2016-12-05 17:55
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-python/issues/110. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-05 17:55 UTC

**Comment by krzysztof-sikorski** [comment] 2016-12-06 09:18
I am sorry, I forgot that language syntaxes are split into separate packages.
