### ISSUE TITLE
Certain string break code highlighting for PHP + SQL

### ISSUE THREAD

**Issue by AndrejIT** [atom/atom#18065] opened 2018-09-17 13:43 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Code highlighting in .php file are broken after certain line]

### Steps to Reproduce

1. [Put this text in middle of existing php code: $q = " SELECT GROUP_CONCAT(SomeColumn SEPARATOR ',\\\\n') FROM SomeTable";]
2. [Observe highlighting of php code under this line]

**Expected behavior:** [Code highlighting as usual]

**Actual behavior:** [It acts like i have not closed string correctly]

**Reproduces how often:** [100%]

### Versions
Atom 1.3.0 on Windows 7

### Additional Information
$q = " SELECT GROUP_CONCAT(SomeColumn SEPARATOR ',\\\\n') FROM SomeTable";

**Comment by AndrejIT** [comment] 2018-09-17 14:42
Easy workaround is to format string like this:
$q = " SELECT GROUP_CONCAT(SomeColumn SEPARATOR '".",\\\\n') FROM SomeTable";

**Comment by Arcanemagus** [comment] 2018-09-17 15:55
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-php/issues/333. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-09-17 15:55 UTC
