### ISSUE TITLE
Atom not responding when viewing large minified js file (maybe other file too)

### ISSUE THREAD

**Issue by ariona** [atom/atom#6440] opened 2015-04-20 09:18 UTC
Atom will not responding when viewing a large chunk of minified script, maybe it has to do with the syntax highlighting.

**Comment by izuzak** [comment] 2015-04-20 10:09
I believe this is a duplicate of https://github.com/atom/atom/issues/979. Please subscribe there for updates and thanks for the feedback! :+1:

**Closed by izuzak** 2015-04-20 10:09 UTC
