### ISSUE TITLE
装个atom真费劲儿....

### ISSUE THREAD

**Issue by zhangtianxiao** [atom/atom#15620] opened 2017-09-12 11:33 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At C:\Users\92095\AppData\Local\atom\app-1.19.5\resources\app\src\pane-container.js:257

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.19.5/resources/app/src/pane-container.js:257:21)
    at Pane.module.exports.Pane.activate (~/AppData/Local/atom/app-1.19.5/resources/app/src/pane.js:911:20)
    at Pane.module.exports.Pane.focus (~/AppData/Local/atom/app-1.19.5/resources/app/src/pane.js:290:25)
    at HTMLElement.<anonymous> (~/AppData/Local/atom/app-1.19.5/resources/app/src/pane-element.js:51:25)
```

### Commands

```
  3x -1:31 tree-view:toggle (atom-pane.pane.active)
     -1:29 application:open-folder (div.tool-panel.tree-view)
     -1:19.5.0 application:open-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
  2x -1:16.8.0 tree-view:toggle (atom-pane.pane.active)
     -1:12.1.0 application:open-folder (atom-pane.pane)
```

### Non-Core Packages

```
activate-power-mode 2.5.0 
atom-ternjs 0.18.3 
autocomplete-java 1.2.7 
```

**Comment by 50Wliu** [comment] 2017-09-12 13:55
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14716. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-09-12 13:55 UTC
