### ISSUE TITLE
Closing Atom does not reopen projects

### ISSUE THREAD

**Issue by larsvanhilten** [atom/atom#15336] opened 2017-08-16 15:53 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When closing Atom with the close button from the title bar it won't reopen previously open projects. 

### Steps to Reproduce

1. Open a project in Atom
2. Close Atom with close button from title bar
3. Open Atom

**Expected behavior:**  Projects should have reopened

**Actual behavior:** Projects don't reopen

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.19.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.9.2
```

### Additional Information

Reopening projects works fine when selecting `Atom > Quit` from the Application bar. Or when using ` CMD + Q `.

**Comment by rsese** [comment] 2017-08-16 21:48
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14315, see this comment for more details /cc https://github.com/atom/atom/issues/14315#issuecomment-298447286.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-16 21:48 UTC

**Comment by larsvanhilten** [comment] 2017-08-17 07:37
Is there a fix available for this issue on MacOS?

**Comment by rsese** [comment] 2017-08-17 20:09
> @rsese Is there a fix available for this issue on MacOS?

No this is expected behavior if you close the last window as you described ("When closing Atom with the close button from the title bar ") - if you want the project you had open to re-open, you should close Atom as you described here:

> Reopening projects works fine when selecting Atom > Quit from the Application bar. Or when using CMD + Q.
