### ISSUE TITLE
[1.19.0] [macOS] Atom CLI doesn't open native tabs

### ISSUE THREAD

**Issue by giannisp** [atom/atom#15202] opened 2017-08-09 07:15 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom CLI doesn't open native tabs.
It used to be working on 1.18.x just fine.

### Steps to Reproduce

1. Navigate to a project, and do `atom .`
2. Navigate to a second project and do `atom .`

**Expected behavior:** Single Atom window with two native tabs.

**Actual behavior:** Two Atom windows.

**Reproduces how often:** 100%

### Versions

macOS: 10.12.6
Atom: 1.19.0
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
apm: 1.18.2

### Additional Information

macOS Dock settings:  
Prefer tabs when opening documents: `Always`

Atom Core / Title Bar option: `native`

**Comment by maplemap** [comment] 2017-08-09 09:20
True. I observe the same behavior  when I try to open some projects through Finder.

**Comment by yubaoquan** [comment] 2017-08-09 10:18
Same bug. When I open recent projects with atom 1.18.x, it will open the project in another native tab of the current opened window. But now, it just opens another window.

**Comment by rsese** [comment] 2017-08-09 17:05
I can reproduce this with `System Preferences > Dock > Prefer tabs when opening documents` in 1.19.0 - I *think* this is related to Electron changes but there's also an open pull request to enable this functionality here https://github.com/atom/atom/pull/14711.

**Comment by dannyradden** [comment] 2017-08-09 17:22
Same problem here. I cant figure out how to combine projects into a single window at all anymore. 😢

**Comment by tsdorsey** [comment] 2017-08-09 22:42
Same thing here. Perhaps related to https://github.com/electron/electron/pull/9052 where they defaulted to no tabs by default for compatibility reasons.

**Comment by kudorori** [comment] 2017-08-11 01:34
@dannyradden 

1. open file "/Applications/Atom.app/Contents/Resources/app/src/main-process/atom-window.js"

2. to line 58, option variables, add `tabbingIdentifier: 'atom',`

**Comment by cleverbeagle** [comment] 2017-08-12 02:33
@kudorori thank you. Sigh of relief seeing that work.

**Comment by jhoium2004** [comment] 2017-08-15 16:41
@magicdawn Same here.

**Comment by fmunteanu** [comment] 2017-08-15 18:53
I was sure the fix will be present into 1.19.1 ☹️

**Comment by rsese** [comment] 2017-08-15 22:41
The PR I mentioned above (https://github.com/atom/atom/pull/14711) isn't merged yet but I'm bringing it up with the team tomorrow.

**Comment by the4yeast** [comment] 2017-08-15 23:10
I seem to be missing something - how can I update to 1.19.1 (in Sierra)? Do I need to download the correct binary? Atom doesn't see any updates in "Check for Update".

**Comment by the4yeast** [comment] 2017-08-16 23:05
^^ nvm, now I updated to 1.19.2. I guess the version wasn't published in the right place, or some caching was involved in the check.

**Comment by fmunteanu** [comment] 2017-08-16 23:31
@rsese, 1.19.2 is out, let's make #14711 happen on 1.19.3! 😄

**Comment by rsese** [comment] 2017-08-17 17:00
I have it on our list to discuss soon @fmunteanu :v:

**Comment by giannisp** [comment] 2017-08-23 07:36
Good news 1.19.3 is out, bad news the fix (that works just fine!) isn't merged yet.

**Comment by mrleblanc101** [comment] 2017-08-25 22:40
How much longer ? This is a real pain.

**Comment by tsdorsey** [comment] 2017-08-28 04:44
The fix was merged into the master branch 3 days ago with commit 80ce23734.
Not sure how long it takes to get things into the beta and then release branches but it's going to happen now.

**Comment by tsdorsey** [comment] 2017-08-30 07:47
For anyone that doesn't want to dig through the commit logs... the 1.21-releases branch has been made and it includes the tag fix. Should mean that when 1.21 is released you'll get native tabs again. 1.20 making it's way through beta testing and does not have the fix now (and I doubt it will be pulled in at this point).

**Comment by fmunteanu** [comment] 2017-09-05 14:43
Thank you @tsdorsey. @rsese, is there a way to push the fix into a new production release? Is difficult to work without this feature.

**Comment by Ben3eeE** [comment] 2017-09-05 15:04
@fmunteanu There are no plans to include this in a hotfix release. It will be available in Atom 1.21 /cc: https://github.com/atom/atom/pull/14711#issuecomment-324790511.

I'm going to close this since it looks like it was fixed when https://github.com/atom/atom/pull/14711 was merged.

**Closed by Ben3eeE** 2017-09-05 15:04 UTC
Labels: electron, mac

**Comment by mrleblanc101** [comment] 2017-09-11 01:03
So we had the issue for a month now and it's not coming in the next release ? This is a regression, why do we have to wait so long for a fix ? At the pace of Atom release, we'll probably have to wait another month or two before seeing 1.21

**Comment by 50Wliu** [comment] 2017-09-11 08:20
@mrleblanc101 native tabs were intentionally disabled _because_ they were causing other bugs (see #14197).  Now that Electron has better native tab support, we are adding it back, but would like to make sure there are no further regressions before releasing it to the stable channel.  I understand that you really like this feature, but please understand that we still have to balance shipping features and making sure those features are as bug-free as possible.

Again, sorry for the delay.

**Comment by tsdorsey** [comment] 2017-09-15 21:58
Atom 1.21.0-beta0 is [here](https://atom.io/beta)! Native tabs are back! Thanks guys. 🥇

**Comment by the4yeast** [comment] 2017-10-04 04:10
any ideas how to set up a key shortcut to cycle thru native tabs?

**Comment by markstickley** [comment] 2017-11-16 17:35
I'd love to see full support for this, including menu options to open, close and cycle through.

**Comment by OmgImAlexis** [comment] 2018-03-31 06:49
Since https://github.com/atom/atom/issues/12690 was forcefully closed this should probably be closed too.
