### ISSUE TITLE
File location is wrong on title 

### ISSUE THREAD

**Issue by tommytroylin** [atom/atom#5058] opened 2015-01-14 17:57 UTC
![qq20150115-6](https://cloud.githubusercontent.com/assets/3364271/5744008/1e9efe78-9c58-11e4-92fb-8309de0cff27.png)

![qq20150115-7](https://cloud.githubusercontent.com/assets/3364271/5743951/a89aac22-9c57-11e4-8c58-daaed03efa0d.png)

You can find the correct location on the tree view, but on title the location don't change.

If this location is represent for the current folder on the view, it will confuse the user. It will be a disaster for a user editing 2 files with the same name in different folders.

I think this title is to indicate the current file location, so this must be a bug..

**Comment by tommytroylin** [comment] 2015-01-14 17:58
My System & Version 
Mac OS X Yosemite
Atom 172

**Comment by kevinsawicki** [comment] 2015-01-14 18:00
Yeah, the window title always show the format "filename - projectPath - Atom", it isn't currently meant to convey the full path to the folder containing the file, just the project path root.

**Comment by abejfehr** [comment] 2015-03-04 15:08
Does this overlap with #5585?

**Comment by Li-ReDBox** [comment] 2015-05-15 03:19
I have an issue I am not sure if related to this: when two files have the same name but different locations, title is not updated with correct location (which is the second part of title as mentioned by @kevinsawicki above). Does Atom use some kind of dictionary which has too short keys?

**Comment by captain-digitalsailors** [comment] 2015-12-01 10:42
@abejfehr I think this is a duplicate of #5585 .

I understand that showing "filename - projectPath - Atom" as the window title is working a specified, but this highly unexpected behavior, especially on Mac OS:

1) The title bar icon can be used as a drag'n'drop item for the file, so actually showing a different file path here is highly misleading (especially in a situation with two files with the same name).

2) If two files are open, the top part of the window does not indicate which file is actually shown, unless you mouseover the tab. Again, very high potential to actually edit the wrong file (which will be very hard to detect, once it has happened). (See screenshot).

![atom_pathproblem](https://cloud.githubusercontent.com/assets/13032249/11498537/4dd14b6e-9820-11e5-891d-65f11106cef2.png)

**Closed** 2016-12-20 04:30 UTC
Labels: enhancement
