### ISSUE TITLE
receltly ATOM editor is crashing when i run my python or c++ program. 

### ISSUE THREAD

**Issue by vamshireddy08** [atom/atom#16688] opened 2018-02-06 02:34 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

I HAVE ATTACHED ALL THE CRASH REPORTS.

[1adf02dd-b5c4-4082-a38c-b5541135ecc6.txt](https://github.com/atom/atom/files/1697522/1adf02dd-b5c4-4082-a38c-b5541135ecc6.txt)
[4bce30e9-2e41-4d66-ab20-23066f807b9d.txt](https://github.com/atom/atom/files/1697523/4bce30e9-2e41-4d66-ab20-23066f807b9d.txt)
[17be4861-55ba-49ed-975d-c528d82d4f0c.txt](https://github.com/atom/atom/files/1697524/17be4861-55ba-49ed-975d-c528d82d4f0c.txt)
[33adf8d3-8f59-4d97-927d-57e4401a5aea.txt](https://github.com/atom/atom/files/1697525/33adf8d3-8f59-4d97-927d-57e4401a5aea.txt)
[42ba9ff7-eea6-4929-9209-28c53b312795.txt](https://github.com/atom/atom/files/1697526/42ba9ff7-eea6-4929-9209-28c53b312795.txt)
[56deb2c0-54ce-4725-adf5-0b58a1757b36.txt](https://github.com/atom/atom/files/1697527/56deb2c0-54ce-4725-adf5-0b58a1757b36.txt)
[072af990-3dd5-48f7-816a-e23fb8ca639d.txt](https://github.com/atom/atom/files/1697528/072af990-3dd5-48f7-816a-e23fb8ca639d.txt)
[417d5e57-8090-4824-af8f-d9029c512db2.txt](https://github.com/atom/atom/files/1697529/417d5e57-8090-4824-af8f-d9029c512db2.txt)
[691f3e30-f86a-4f95-b224-c0ef4e27036e.txt](https://github.com/atom/atom/files/1697530/691f3e30-f86a-4f95-b224-c0ef4e27036e.txt)
[6589ddb2-a4b6-4935-8088-e20327534c26.txt](https://github.com/atom/atom/files/1697531/6589ddb2-a4b6-4935-8088-e20327534c26.txt)
[ac0c8102-641d-4a01-873e-f14c26351850.txt](https://github.com/atom/atom/files/1697532/ac0c8102-641d-4a01-873e-f14c26351850.txt)
[af2bb8b2-94d8-4eb8-b474-9ebaa7830494.txt](https://github.com/atom/atom/files/1697533/af2bb8b2-94d8-4eb8-b474-9ebaa7830494.txt)
[bbb489c4-67be-41bc-a3ea-0ca70dbf26a4.txt](https://github.com/atom/atom/files/1697534/bbb489c4-67be-41bc-a3ea-0ca70dbf26a4.txt)
[c7bd3543-d53d-4e47-a25e-7789fe93ad1d.txt](https://github.com/atom/atom/files/1697535/c7bd3543-d53d-4e47-a25e-7789fe93ad1d.txt)
[c1357bf5-da47-4667-8cb4-db0da37a1f0b.txt](https://github.com/atom/atom/files/1697536/c1357bf5-da47-4667-8cb4-db0da37a1f0b.txt)
[operation_log.txt](https://github.com/atom/atom/files/1697537/operation_log.txt)

**Comment by rsese** [comment] 2018-02-06 05:16
Thanks for the report - can you share more information about the issue?  In particular, the issue template information is really helpful and if you can add more details we can go from there:

* Can you reproduce the crash in safe mode (`atom --safe`)?
* Based on one of the operation_log.txt files, it looks like you're running Atom 1.23.3 - what version of Windows are you running?
* Do you have specific steps to reproduce?  It sounds like it crashes when you're trying to run a Python or C++ program (which makes me think the crash isn't reproducible in safe mode?) but if you can describe exactly what steps you take before the crash, that would be helpful.
* Besides the operation_log.txt files, are there any .dmp files in the crashes directory?

As mentioned in https://github.com/atom/atom/issues/16682#issuecomment-363111857, please fill out the issue template as much as possible since the information is super helpful for us when we investigate issues.

**Comment by rsese** [comment] 2018-02-06 06:22
> Besides the operation_log.txt files, are there any .dmp files in the crashes directory?

Just to clarify this point, if there are .dmp files, you can send them to atom@github.com since they can potentially contain sensitive information.

**Comment by rsese** [comment] 2018-04-27 21:44
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16688#issuecomment-363313594. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-04-27 21:44 UTC
Labels: crash, more-information-needed
