### ISSUE TITLE
Cannot install Atom on CentOS 6

### ISSUE THREAD

**Issue by a1exanderjung** [atom/atom#15411] opened 2017-08-22 21:19 UTC
### Prerequisites

* CentOS 6.9
* Kernel `2.6.32-696.6.3.el6.x86_64`

### Description

There is an inability to install atom text editor as it has a dependency on `libsecret-1` which is not made available to CentOS6.

### Versions

This occurs in all version of atom which a dependency on `libsecret-1`.  From version below, including, 1.17.2, the installation passes but the editor fails to start.  From versions onwards, such as 1.19 and 1.18, the package dependency is made apparent before installation.

**Comment by rsese** [comment] 2017-08-28 19:23
We'll go ahead and close as a duplicate of https://github.com/atom/atom/issues/2177 but see this comment about a potential workaround https://github.com/atom/atom/issues/2177#issuecomment-320073787.

**Closed by rsese** 2017-08-28 19:23 UTC
