### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by harlibott** [atom/atom#17500] opened 2018-06-11 14:22 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:881:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at didDrag (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1827:20)
    at get_window.requestAnimationFrame (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1902:17)
```

### Commands

```
     -4:29.1.0 core:move-right (input.hidden-input)
     -4:28.7.0 core:backspace (input.hidden-input)
  2x -4:28.1.0 core:save (input.hidden-input)
     -4:00.6.0 core:backspace (input.hidden-input)
     -3:58.4.0 core:save (input.hidden-input)
     -2:32.7.0 core:backspace (input.hidden-input)
     -2:31.2.0 core:save (input.hidden-input)
  3x -2:15 core:backspace (input.hidden-input)
     -2:13.6.0 core:move-down (input.hidden-input)
  4x -2:12.1.0 core:backspace (input.hidden-input)
     -2:06.3.0 core:save (input.hidden-input)
  2x -1:56.4.0 core:backspace (input.hidden-input)
     -1:55.4.0 core:save (input.hidden-input)
  4x -1:03.4.0 core:backspace (input.hidden-input)
     -0:54.2.0 core:save (input.hidden-input)
  7x -0:09.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by harlibott** [comment] 2018-06-11 14:29
This keeps popping up everytime I scroll in atom to edit anything

**Comment by rsese** [comment] 2018-06-11 17:13
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16892 so you can subscribe there for updates if you'd like.

To get around the error, people mentioned that clearing saved state helped (save any unsaved data first):

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

If you still have trouble after trying this though, let me know.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-06-11 17:13 UTC
