### ISSUE TITLE
Network Mounted Files crashes atom, when network is gone

### ISSUE THREAD

**Issue by bjmtrk** [atom/atom#11040] opened 2016-03-03 03:19 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
yes
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
Yes
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
yes
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
Yes
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
I don't know
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
No

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]
Network Mounted Files crashes atom, when network is gone

### Steps to Reproduce

1. Mount fs via network
2. Open project on the network fs
3. Close the network

**Expected behavior:** [What you expected to happen]
Atom crashes and gives 3 options: Reload, Close, Exit

**Comment by Zireael07** [comment] 2016-03-03 07:59
You should have searched - there's multiple issues related to network fs and crashes.

**Comment by 50Wliu** [comment] 2016-03-03 12:49
Closing as a duplicate of #10271, feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-03 12:49 UTC
