### ISSUE TITLE
Huge memory leak on Mac OS X and Linux, even on safe mode (10MB per sec) - narrowing the problem

### ISSUE THREAD

**Issue by remisharrock** [atom/atom#9006] opened 2015-09-30 12:21 UTC
Hello, I have a huge memory leak (10MB per sec !), even when starting with atom --safe
- atom versions :  atom-1.0.19-1.fc22.x86_64.rpm   (same issue with 1.0.18 )
- OS: Fedora 22   kernel 4.1.6-201.fc22.x86_64
- OS: Mac OS X Yosemite

To reproduce the issue, you simply have to have this .atom folder containing uniquely:

```
~/.atom $ tree -a
.
├── .apm
│   └── .apmrc
├── config.cson
└── storage
    ├── application.json
    └── editor-79f814a9e20f61c1885b00e04712625e8942ce1e

2 directories, 4 files
```

however, when I delete the file storage/editor-79f814a9e20f61c1885b00e04712625e8942ce1e  ; the memory leak is no more active. It may be somehow related to this file ?
Here is the content of the files:
- .apm/.apmrc : 

```
 ~/.atom $ cat .apm/.apmrc 
; This file is auto-generated and should not be edited since any
; modifications will be lost the next time any apm command is run.
;
; You should instead edit your .apmrc config located in ~/.atom/.apmrc
cache = /infres/s3/sharrock/.atom/.apm
```
- config.cson

```
 ~/.atom $ cat config.cson : 

"*":
  "exception-reporting":
    userId: "edcc3125-7d52-52c1-7768-d57490b1ccc7"
  welcome:
    showOnStartup: false
  core: {}
  editor:
    invisibles: {}
  "one-dark-ui": {}
```
- storage/application.json

```
 ~/.atom $ cat storage/application.json 
[{"initialPaths":["/infres/s3/sharrock"]}]
```
- storage/editor-79f814a9e20f61c1885b00e04712625e8942ce1e: 

```
 ~/.atom $ cat storage/editor-79f814a9e20f61c1885b00e04712625e8942ce1e 
{"mode":"editor","version":1,"windowDimensions":{"x":871,"y":34,"width":1048,"height":1020,"maximized":false},"grammars":{"deserializer":"GrammarRegistry","grammarOverridesByPath":{}},"project":{"paths":["/infres/s3/sharrock"],"buffers":[],"deserializer":"Project"},"workspace":{"paneContainer":{"root":{"id":3,"items":[{"deserializer":"AboutView","uri":"atom://about"}],"activeItemURI":"atom://about","focused":true,"flexScale":1,"deserializer":"Pane"},"activePaneId":3,"deserializer":"PaneContainer","version":1},"fullScreen":false,"packagesWithActiveGrammars":[],"deserializer":"Workspace"},"packageStates":{"find-and-replace":{"findOptions":{"findPattern":"onlyoffice","replacePattern":"","pathsPattern":"","useRegex":false,"wholeWord":false,"caseSensitive":false,"inCurrentSelection":false},"findHistory":["auth","onlyoffice"],"replaceHistory":[],"pathsHistory":[]},"fuzzy-finder":{},"metrics":{"sessionLength":90558},"tabs":[{}],"tree-view":{"directoryExpansionStates":{"/infres/s3/sharrock":{"isExpanded":true,"entries":{".adobe":{"isExpanded":false,"entries":{}},".android":{"isExpanded":false,"entries":{}},".atom":{"isExpanded":false,"entries":{}},".cache":{"isExpanded":false,"entries":{}},".ccache":{"isExpanded":false,"entries":{}},".cinnamon":{"isExpanded":false,"entries":{}},".config":{"isExpanded":false,"entries":{}},".dbus":{"isExpanded":false,"entries":{}},".eclipse":{"isExpanded":false,"entries":{}},".eclipse.old":{"isExpanded":false,"entries":{}},".emacs.d":{"isExpanded":false,"entries":{}},".fontconfig":{"isExpanded":false,"entries":{}},".fvwm":{"isExpanded":false,"entries":{}},".gconf":{"isExpanded":false,"entries":{}},".gconfd":{"isExpanded":false,"entries":{}},".gconfdOLD":{"isExpanded":false,"entries":{}},".gconfOLD":{"isExpanded":false,"entries":{}},".gem":{"isExpanded":false,"entries":{}},".gimp-2.8":{"isExpanded":false,"entries":{}},".giteye":{"isExpanded":false,"entries":{}},".gnome":{"isExpanded":false,"entries":{}},".gnome2":{"isExpanded":false,"entries":{}},".gnome2_private":{"isExpanded":false,"entries":{}},".gnome2_privateOLD":{"isExpanded":false,"entries":{}},".gnome2OLD":{"isExpanded":false,"entries":{}},".gnomeOLD":{"isExpanded":false,"entries":{}},".gnupg":{"isExpanded":false,"entries":{}},".gstreamer-0.10":{"isExpanded":false,"entries":{}},".gvfs":{"isExpanded":false,"entries":{}},".icedove":{"isExpanded":false,"entries":{}},".icons":{"isExpanded":false,"entries":{}},".IntelliJIdea14":{"isExpanded":false,"entries":{}},".java":{"isExpanded":false,"entries":{}},".kde":{"isExpanded":false,"entries":{}},".links2":{"isExpanded":false,"entries":{}},".local":{"isExpanded":false,"entries":{}},".macromedia":{"isExpanded":false,"entries":{}},".mission-control":{"isExpanded":false,"entries":{}},".mozilla":{"isExpanded":false,"entries":{}},".mplayer":{"isExpanded":false,"entries":{}},".npm":{"isExpanded":false,"entries":{}},".nv":{"isExpanded":false,"entries":{}},".pip":{"isExpanded":false,"entries":{}},".pki":{"isExpanded":false,"entries":{}},".pulse":{"isExpanded":false,"entries":{}},".qws":{"isExpanded":false,"entries":{}},".rvm":{"isExpanded":false,"entries":{}},".smartgit":{"isExpanded":false,"entries":{}},".smartgit.old":{"isExpanded":false,"entries":{}},".spice-vdagent":{"isExpanded":false,"entries":{}},".ssh":{"isExpanded":false,"entries":{}},".subversion":{"isExpanded":false,"entries":{}},".swt":{"isExpanded":false,"entries":{}},".themes":{"isExpanded":false,"entries":{}},".thumbnails":{"isExpanded":false,"entries":{}},".uml":{"isExpanded":false,"entries":{}},".virtualenvs":{"isExpanded":false,"entries":{}},".x2go":{"isExpanded":false,"entries":{}},"bin":{"isExpanded":false,"entries":{}},"Desktop":{"isExpanded":false,"entries":{}},"Downloads":{"isExpanded":false,"entries":{}},"IdeaProjects":{"isExpanded":false,"entries":{}},"INF346":{"isExpanded":false,"entries":{}},"MesDocuments":{"isExpanded":false,"entries":{}},"NTProfile":{"isExpanded":false,"entries":{}},"public_html":{"isExpanded":false,"entries":{}},"workspace":{"isExpanded":false,"entries":{}},"workspace.old":{"isExpanded":false,"entries":{}},"workspaceNEW":{"isExpanded":false,"entries":{}}}}},"selectedPath":"/infres/s3/sharrock","hasFocus":false,"attached":false,"scrollLeft":0,"scrollTop":0,"width":200}}}
```

unfortunately, when I import the .atom directory with the files above on another account there is no memory leak. Therefore it is hard to reproduce the memory leak only with these files... But I'm sure it's related to the file storage/editor-79f814a9e20f61c1885b00e04712625e8942ce1e

**Comment by remisharrock** [comment] 2015-10-01 21:11
seems to be reproductible on Mac OS X also !

**Comment by emanuelet** [comment] 2015-12-07 02:15
for me the issue was generated by the "pigments" plugin. Disabling it it solved the issue, and also I've been able to observe that the it happens only on load, because if I disable it and re-enable it, the process doesn't hog cpu and memory anymore.

**Comment by geeeeeeeeek** [comment] 2015-12-12 07:01
I was having a weird situation last night. The *kernal_task* kept using a lot of disk space(in GBs), and deleting files didn't help at all, cause the space was being filled up so fast. 

All I was doing was working on a clang project in atom, and having it closed and Mac restarted seemed to solve the problem. I'm wondering if this was caused by some kind of memory leak of atom?

**Comment by remisharrock** [comment] 2016-01-07 17:31
@emanuelet I thought starting with atom --safe ,as I did,  disables the packages (ie. plugins) : 
https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode

**Comment by lee-dohm** [comment] 2016-01-07 17:58
It disables community packages, yes, among other things.

**Comment by kingjr** [comment] 2016-03-07 16:24
For me, this issue only appears when I open atom in a 'root' directory. I suppose it's because atom or one of the plugins is trying to index everything in the directory.

**Comment by 50Wliu** [comment] 2016-03-07 21:22
@kingjr what Atom version are you using?

**Comment by kingjr** [comment] 2016-03-07 22:45
1.0.5 with ubuntu 14.04

**Comment by 50Wliu** [comment] 2016-03-07 23:18
@kingjr The latest version is currently Atom 1.5.4, which should have fixed the issue you are experiencing.

@remisharrock Can you please test Atom 1.5.4 and see if you still have performance issues?  Thanks.

**Comment by artemisclyde** [comment] 2017-05-11 13:45
The same thing happened to me on linux because I **added my home folder as a project folder**. The result was a spike in memory usage at first and then what seemed to me like a memory leak. I don't know if it would eventually stop, but it slowly filled up several GBs of memory.

**Comment by 50Wliu** [comment] 2017-05-11 15:50
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/9006#issuecomment-193500310. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
***
@artemisclyde Would you mind opening a new issue?  Lots of things have changed since this one was filed.  Thanks!

**Closed by 50Wliu** 2017-05-11 15:50 UTC
Labels: performance
