### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by Halamix2** [atom/atom#7494] opened 2015-06-27 18:15 UTC
1.Go to settings
2. Keybindings and find alt-s
3. Select text and righ-click

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Halamix2\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  3x -3:57.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:40.9.0 keyboard-localization:keymap-generator (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:34.6.0 core:move-right (atom-pane.pane.active)
  6x -2:29.2.0 application:run-all-specs (input.key-input)
  3x -2:24.1.0 core:backspace (input.key-input)
  9x -2:22.9.0 application:run-all-specs (input.key-input)
  3x -2:11 core:backspace (atom-text-editor.editor.is-focused)
  5x -1:59 core:save (input.key-input)
  2x -1:44.7.0 application:run-all-specs (atom-text-editor.editor.is-focused)
  2x -1:42.1.0 editor:checkout-head-revision (atom-text-editor.editor.is-focused)
  5x -1:38.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:27.6.0 application:run-all-specs (atom-text-editor.editor.mini.is-focused)
     -1:24.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:23 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:21.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:20.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7
keyboard-localization, v1.4.3
language-batch, v0.3.3
language-rust, v0.4.3
linter-javac, v0.1.4
linter-rust, v0.1.0
minimap, v4.10.0
pigments, v0.8.1
racer, v0.15.2
rust-api-docs-helper, v0.5.1
text-manipulation, v0.6.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment] 2015-06-27 19:13
Duplicate of https://github.com/atom/atom/issues/6548. Please subscribe to that issue if you want updates.

**Closed by thomasjo** 2015-06-27 19:13 UTC
