### ISSUE TITLE
Mouse back button support in install package/themes

### ISSUE THREAD

**Issue by XDelta** [atom/atom#15500] opened 2017-08-30 06:04 UTC
Using the mouse back button in the install package/themes page should be included as a feature. Makes browsing packages or themes much nicer. If there is a package that does this that would be nice but I couldn't find one.

**Comment by Ben3eeE** [comment] 2017-08-30 06:27
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/settings-view/issues/912. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-30 06:27 UTC
Labels: duplicate, wrong-repo

**Comment by XDelta** [comment] 2017-08-30 06:29
ah thanks
