### ISSUE TITLE
Corrupted text rendering

### ISSUE THREAD

**Issue by RyanTheNerd** [atom/atom#16165] opened 2017-11-13 00:07 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
All text is corrupted, characters overlap, speckles all over the screen, occurs in all text rendered.

### Steps to Reproduce

1. Start atom

**Expected behavior:** [What you expect to happen]
Properly rendered text
**Actual behavior:** [What actually happens]
Corrupted text
**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time
### Versions
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
I've tried using a different font and deleting my .atom folder to no prevail.
Here's an image of the corruption: 
![Here's an image of the corruption](https://user-images.githubusercontent.com/15710586/32704991-6ae240ee-c7c3-11e7-9a4f-1f86939443bf.png)

**Comment by 50Wliu** [comment] 2017-11-13 00:09
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15737. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-11-13 00:09 UTC
