### ISSUE TITLE
SCSS Syntax Highlighting error, nth-child(-n) inside media query.

### ISSUE THREAD

**Issue by dustindowell22** [atom/atom#7706] opened 2015-07-04 07:58 UTC
The red background should not be red. This only happens when inside a media query.

![image](http://cl.ly/image/3w2d3x3b2w3m/Screen%20Shot%202015-07-04%20at%202.50.47%20AM.png)

**Comment by izuzak** [comment] 2015-07-04 10:41
Seems like a duplicate of https://github.com/atom/language-sass/issues/70, so closing in favor of that one.

**Closed by izuzak** 2015-07-04 10:41 UTC
