### ISSUE TITLE
ctrl-q quits atom without prompting to save modified files

### ISSUE THREAD

**Issue by tomak-git** [atom/atom#5257] opened 2015-01-26 11:06 UTC
With such a keybinding, it is far too easy to lose work, i.e. when hitting it accidentally, or when slipping from a similar keybinding. This happenned to me few times now when I wanted to reflow selection (default keybinding ctrl-alt-q) but instead, I ended up with atom closed and work lost.

**Comment by benogle** [comment] 2015-01-26 21:46
This definitely works for me. What system are you on?

**Comment by tomak-git** [comment] 2015-01-27 07:48
I'm on fully updated ubuntu 14.04, atom version 0.174.

**Comment by tomak-git** [comment] 2015-01-27 10:35
That's weird, I can't reproduce the behavior today. I'll keep this issue updated if I manage to reproduce it again.

**Comment by tomak-git** [comment] 2015-01-28 06:00
Ok, I figured it out and I can now reproduce it consistently. It happens only when you have the same file opened in two panes. Steps to reproduce:

1. Start Atom
2. Open a file
3. Open the same file in another pane (hit ctrl-k right arrow)
4. Edit the file
5. Hit ctrl-q

Can anyone else reproduce this?

**Comment by lee-dohm** [comment] 2015-01-28 12:16
I just reproduced it in Atom v0.177.0-87c2f44 on Mac OS X 10.10.1 using your repro steps.

**Comment by kevinsawicki** [comment] 2015-02-05 01:18
This will be fixed in the next Atom release, 0.178, thanks for the reproduction steps!

**Closed** 2015-02-05 01:18 UTC
Labels: atom, bug

**Comment by tomak-git** [comment] 2015-02-05 09:29
Great! My pleasure.
