### ISSUE TITLE
atom installation 

### ISSUE THREAD

**Issue by Nageshwari-p** [atom/atom#10537] opened 2016-01-21 11:56 UTC
Hi , 
I'm using this editor.due to insufficient system battery window had been shutdown automatically , when i reopened and start   editor its showing below error.

SyntaxError: Unexpected token 
    at Object.parse (native)
    at FileSystemBlobStore.load (C:\Users\Admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\file-system-blob-store.js:36:31)
    at Function.load (C:\Users\Admin\AppData\Local\atom\app-1.3.2\resources\app.asar\src\file-system-blob-store.js:10:14)
    at window.onload (file:///C:/Users/Admin/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:18:39)

please help me in this

**Comment by Zireael07** [comment] 2016-01-21 13:04
Duplicate of #10015.

**Comment by mnquintana** [comment] 2016-01-21 13:36
Thanks @Zireael07! Closing in favor of https://github.com/atom/atom/issues/10015.

**Closed by mnquintana** 2016-01-21 13:36 UTC
