### ISSUE TITLE
Add a toggle to disable re-opening previous files at startup

### ISSUE THREAD

**Issue by ian-rose** [atom/atom#8111] opened 2015-07-28 14:00 UTC
While I appreciate many people enjoy the ability to quickly resume work by having Atom re-open the files that were open when Atom last exited, this functionality can also hamper work. With my day-to-day usage of Atom I find the delay in re-opening files to be frustrating, and when attempting to create a new file I find myself often accidentally editing an existing file.

I would like to see a setting added to Atom to toggle between re-opening previous files and opening with only a new file.

**Comment by mnquintana** [comment] 2015-07-28 14:37
This is a duplicate of https://github.com/atom/atom/issues/6605 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-28 14:37 UTC
