### ISSUE TITLE
"Create issue on the xyz package" and "Copy to clipboard" not working

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#7113] opened 2015-06-05 07:29 UTC
When I get an error (that red warning that shows on the upper right side of Atom) and I try to interact with it by either clicking on the "Copy to clipboard" or the "Create issue on the xyz package" buttons, nothing happens.

**Comment by mnquintana** [comment] 2015-06-05 10:21
Thanks for the report! This is a duplicate of https://github.com/atom/notifications/issues/70 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-05 10:21 UTC
