### ISSUE TITLE
CTRL+Backspace behavior 

### ISSUE THREAD

**Issue by xx999** [atom/atom#15817] opened 2017-10-04 20:55 UTC
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Uncomfortable deleting of code. This is very small feature but so uncomfortable behavior.
For example you have block code where you have a lot of whitespaces after closing bracket }
```javascript
name() {

}    
```
or you you stay on next empty line after }
and you press **ctrl+backspace** this closing bracket REMOVED! Why?
### Steps to Reproduce
```
1. write
name() {

}// <- this bracket
```
2. Add new line
3. Press ctrl + backspace

**Expected behavior:** [What you expect to happen]

**Actual behavior:** Removed closing bracket **}**

**Reproduces how often:** **}** shouldn't removed

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Last time WS start lagging a lot and prefer Atom between all editors. Similar behavior in WS. Thanks

**Comment by rsese** [comment] 2017-10-04 21:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/3362. You may want to subscribe there for updates - I haven't tried it, but a potential workaround is mentioned in https://github.com/atom/atom/issues/3362#issuecomment-248875263.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-04 21:38 UTC
