### ISSUE TITLE
Uncaught TypeError: Invalid Point: (257, NaN)

### ISSUE THREAD

**Issue by begatsby** [atom/atom#18223] opened 2018-10-11 03:59 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (257, NaN)

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:982

TypeError: Invalid Point: (257, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:345:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-marker.js:154:58)
    at changePosition (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:68:25)
    at Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:715:11)
    at Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:67:16)
    at Cursor.moveLeft (/Applications/Atom.app/Contents/Resources/app/src/cursor.js:288:18)
    at moveCursors.cursor (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2739:52)
    at Array.forEach (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2881:31)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:24)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2007:30)
    at TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2880:23)
    at TextEditor.moveLeft (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2739:23)
    at TextEditor.core:move-left (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:318:27)
    at HTMLElement.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:686:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:20.5.0 find-and-replace:show (input.hidden-input)
  2x -0:18.4.0 core:confirm (input.hidden-input)
     -0:17.1.0 editor:consolidate-selections (input.hidden-input)
     -0:17.1.0 atom-minify:close-panel (input.hidden-input)
     -0:17.1.0 core:cancel (input.hidden-input)
     -0:16.8.0 core:move-up (input.hidden-input)
     -0:16.5.0 core:move-down (input.hidden-input)
     -0:16 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -0:15.7.0 core:move-right (input.hidden-input)
     -0:14.4.0 core:move-down (input.hidden-input)
  2x -0:13.5.0 core:move-left (input.hidden-input)
  3x -0:10.6.0 core:move-right (input.hidden-input)
     -0:02.3.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.2 
atom-minify 0.8.0 
atom-typescript 12.4.0 
autocomplete-python 1.10.12 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.19 
ftp-remote-edit 0.12.12 
git-diff-details 1.4.0 
git-plus 8.0.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-pycodestyle 2.1.3 
linter-pylint 2.1.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
multiple-remote-ftp 0.3.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
project-manager 3.3.6 
python-autopep8 0.1.3 
remote-ftp 2.2.0 
script 3.17.3 
selection-highlight 0.1.6 
seti-ui 1.10.0 
split-diff 1.5.2 
sync-settings 0.8.6 
tree-view-sort 0.11.0 
```

**Comment by rsese** [comment] 2018-10-14 02:49
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14774 so you can subscribe there for updates if you'd like.  If you can consistently reproduce the error, please let us know in https://github.com/atom/atom/issues/14774.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-14 02:49 UTC
