### ISSUE TITLE
Uncaught TypeError: Invalid Point: (133, NaN)

### ISSUE THREAD

**Issue by Nickel2Plus** [atom/atom#19745] opened 2019-08-03 18:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (133, NaN)

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Invalid Point: (133, NaN)
    at Function.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:48794)
    at DisplayLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:89900)
    at DisplayMarkerLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1187509)
    at DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2807483)
    at changePosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:521252)
    at Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:529796)
    at Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:521218)
    at Cursor.moveLeft (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:524040)
    at modifySelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:533852)
    at Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:546998)
    at Selection.selectLeft (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:533820)
    at Selection.backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:538344)
    at mutateSelectedText.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16061)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:491299)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16037)
    at TextEditor.e.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:257668)
    at TextEditor.core:backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:300877)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:306618
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:491299)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at HTMLElement.s.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:306561)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348736)
```

### Commands

```
     -1:01.1.0 editor:newline (input.hidden-input)
     -1:00.8.0 core:move-up (input.hidden-input)
     -1:00.6.0 core:paste (input.hidden-input)
     -0:59.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:59.7.0 snippets:expand (input.hidden-input)
     -0:59.7.0 editor:indent (input.hidden-input)
     -0:59.2.0 core:undo (input.hidden-input)
     -0:58.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:58.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:58.1.0 snippets:expand (input.hidden-input)
     -0:58.1.0 editor:indent (input.hidden-input)
     -0:57.7.0 core:save (input.hidden-input)
  3x -0:16.7.0 core:backspace (input.hidden-input)
     -0:09.0 core:save (input.hidden-input)
     -0:04.4.0 core:move-down (input.hidden-input)
  5x -0:03.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
auto-encoding 0.7.1 
japanese-menu 1.14.0 
textile-preview 0.1.2 
```

**Comment by rsese** [comment] 2019-08-05 18:05
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/19114 so you can subscribe there for updates if you'd like.   If you have repro steps or other information to share, please let us know in https://github.com/atom/atom/issues/19114.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-05 18:05 UTC
