### ISSUE TITLE
atom - massive size, App load time 7359ms, then core dump (Archlinux)

### ISSUE THREAD

**Issue by drankinatty** [atom/atom#12069] opened 2016-06-29 05:28 UTC
### Prerequisites

* [x ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Fresh build and install on Archlinux. (AMD FX-8350, 32G DDR3 3200)

```
~/arch/git/atom> script/build --build-dir ../atom_build
Node: v6.2.2
npm: v3.10.2
Installing build modules...
=> Took 104107ms.

Installing apm...
(node:20959) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
<snip>
=> Took 68576ms.

Deleting old packages...
=> Took 384ms.

Installing modules ✓
Installing atom-dark-syntax@0.27.0 ✓
Installing atom-dark-ui@0.51.0 ✓
<snip>
=> Took 420689ms.

Deduping modules ✓
=> Took 35764ms.
<snip>
Running "generate-asar" task

Done, without errors.

Execution Time (2016-06-29 04:41:13 UTC)
loading tasks                         2s  ▇ 1%
download-electron               1m 50.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 61%
download-electron-chromedriver      2.2s  ▇ 1%
build                                 5s  ▇ 3%
coffee:glob_to_multiple            11.7s  ▇▇ 6%
prebuild-less:src                  32.9s  ▇▇▇▇▇▇ 18%
cson:glob_to_multiple               4.7s  ▇ 3%
generate-asar                       9.3s  ▇▇ 5%
Total 3m 2.1s

$ sudo script/grunt install --build-dir ../atom_build
(node:3376) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Running "install" task

Done, without errors.


Execution Time (2016-06-29 04:49:54 UTC)
loading tasks   1.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 69%
install        850ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 31%
Total 2.8s

```
[Description of the bug or feature]

Launching atom via ssh (local 1G network), the window loads then atom crashes:

```
$ atom
$ /usr/local/bin/atom: line 115:  3464 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 7359ms
Failed to get crash dump id.
Report Id:
Failed to get crash dump id.
Report Id:
Failed to get crash dump id.
Report Id:

```
I'm not sure why atom crashed, but I am proving the report so it can be addressed. The atom concept is good, but it has far to big a footprint to be usable to me.  1.1G for the atom source dir and 237M for the build - the entire KDE3 install is less:

```
$ du -hcs ../atom
1.1G    ../atom
1.1G    total
$ du -hcs ../atom_build/
237M    ../atom_build/
237M    total

```
The last note I would add is you should provide an uninstall script that will clean the various pieces of atom that get scattered through the users $HOME directory in .cache, .config, .node-gyp, .pki, etc..

Keep up the good work and see if this issue can be fixed and perhaps atom can be paired down a bit to be more usable.

**Comment by lee-dohm** [comment] 2016-06-29 20:10
Thanks very much for the report. This is a duplicate of a couple different Issues:

* https://github.com/atom/atom/issues/2654
* https://github.com/atom/atom/issues/9755

If you have any more information to provide on the crashing problem, please open a new Issue. Thanks again for the feedback.

**Closed by lee-dohm** 2016-06-29 20:10 UTC
