### ISSUE TITLE
[ Keyboard usability enhancement ] Search box for Tree View

### ISSUE THREAD

**Issue by i90rr** [atom/atom#10202] opened 2015-12-28 15:49 UTC
Hi,

Often a project is made up of tens if not hundreds or even thousands of files and directories, it would be quite handy to have a box to search (as-you-type) for them.

Cheers

**Comment by mnquintana** [comment] 2015-12-28 16:02
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/tree-view/issues/159 – feel free to subscribe there for updates.

You can already live search for files in your project in Atom already though, via the fuzzy-finder: https://atom.io/docs/latest/getting-started-atom-basics#opening-a-file-in-a-project

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) for a guide on submitting bug reports (including searching for duplicates first).

**Closed by mnquintana** 2015-12-28 16:02 UTC
