### ISSUE TITLE
Canceling "unsaved changes" warning closes window anyway

### ISSUE THREAD

**Issue by devios1337** [atom/atom#6770] opened 2015-05-13 16:53 UTC
I've encountered a very severe bug (Atom 0.198.0) where if you attempt to close a window with tabs with unsaved changes, and you hit cancel in the warning dialog that appears, it closes the window anyway (presumably *without* saving).

**Comment by mnquintana** [comment] 2015-05-13 19:54
Thanks for the report! What OS are you running? Can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) (`atom --safe`)?

**Comment by 50Wliu** [comment] 2015-05-13 20:33
This is a duplicate of #4092, please subscribe there for updates (and also comment there with your OS and `atom --safe` results).

**Closed by 50Wliu** 2015-05-13 20:33 UTC
Labels: more-information-needed
