### ISSUE TITLE
Decorations on soft-wrap borders should not stretch across the border

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#4842] opened 2015-01-04 18:19 UTC
I don't think that the spell-check package is doing anything wrong here, so I assume that this visual bug is due to decorations stretching across soft-wrap boundaries when maybe they shouldn't:

![screen shot 2015-01-04 at 10 17 03 am](https://cloud.githubusercontent.com/assets/1038121/5606912/de32d7fc-93fa-11e4-985e-02304d21b02b.png)

*(As a side note, I'm impressed that supercalifragilisticexpialidocious is in the OS X dictionary. I had to come up with another long nonsense word :laughing:)*

I would expect that "absafragginglutely" would be decorated, but *not* the space between "absafragginglutely" and the previous instance of the word "testing".

Atom v0.166.0-25b44ce on Mac OS X 10.10.1

/cc @benogle

**Comment by izuzak** [comment] 2015-01-04 19:44
Looks like a duplicate of https://github.com/atom/spell-check/issues/43. If you agree, what do you think about closing one of these two issues?

**Comment by lee-dohm** [comment] 2015-01-04 19:46
Yeah, I do agree that it is a duplicate. Let me see if I can duplicate outside of spell-check to verify that it is an issue with the Decorations API itself. If so, I'll close the other one. If not, I'll close this one. Sound good?

**Comment by izuzak** [comment] 2015-01-04 19:50
:+1: You're a :star2:, @lee-dohm!

**Comment by lee-dohm** [comment] 2015-01-04 23:18
Yep, looks like the Decorations API, specifically the `highlight` type, I believe.

## Repro Steps

1. Create a Markdown file containing exactly `testing testing testing testing testing testing testing testing testing testing testing supercalifragilisticexpialidocious\n`
1. Enable Soft Wrap if it isn't already
1. Resize the window so that the first `s` in `supercalifragilisticexpialidocious` is the first character on the second screen line, but there is a visual gap between the right edge of the editor view (before any panels) and the `g` in `testing`
1. Execute the following commands in the Console:

    ```javascript
    editor = atom.workspace.getActiveEditor()
    marker = editor.markBufferRange([[0, 88], [0, 123]]) // The exact buffer range of "supercalifragilisticexpialidocious"
    decoration = editor.decorateMarker(marker, {type: 'highlight', class: 'test-decoration'})
    ```

1. Open the Elements pane in the Developer Tools:

![screen shot 2015-01-04 at 3 14 40 pm](https://cloud.githubusercontent.com/assets/1038121/5607950/8288d936-9424-11e4-8afb-72eb897f6d8e.png)

**Expected:** There should only be one highlighted region, the word on the second screen line
**Actual:** There are two highlighted regions, the visual gap and the word that is the content of the Range specified in step 4

**Comment by lee-dohm** [comment] 2015-01-04 23:22
I've closed the spell-check bug since I'm pretty certain this is in the Decorations API.

**Comment by as-cii** [comment] 2016-03-31 09:21
This seems to be working correctly, both with the spell-checker *and* with a custom decoration (following @lee-dohm's reproduction steps). I am not exactly sure about when/how it was fixed, but I cannot reproduce it on **master**.

A different issue is when a decoration spans multiple screen lines (independently of whether is soft-wrapped or not): 

![screen shot 2016-03-31 at 11 17 08](https://cloud.githubusercontent.com/assets/482957/14171237/295c526c-f732-11e5-8564-4ea6a8d10587.png)

This is a completely different scenario, though, and there's [even a PR already](atom/atom#11072) that tries to change it (I don't feel like that's a bug though, because we explicitly implemented it this way).

I am going to close this for now: please, feel free to reopen it if I am missing something. Thanks! :bow:

**Closed by as-cii** 2016-03-31 09:21 UTC
Labels: atom, bug, post-1.0-roadmap, quality-bogle
