### ISSUE TITLE
The program 'atom' received an X Window System error

### ISSUE THREAD

**Issue by D-side** [atom/atom#7364] opened 2015-06-22 09:58 UTC
For the one who will tag this issue: Affects **Linux** version. Likely is a bug. Causes a crash.

I'm not sure where the issue is, but since it's Atom that crashes as a result, I assume I should report it here. If it turns out to be issue somewhere else, I'll take my time to report it in the appropriate place.

### Software involved

1. Firefox Developer Edition 40.0a2 (installed from [Firefox Aurora PPA](https://launchpad.net/~ubuntu-mozilla-daily/+archive/ubuntu/firefox-aurora) as `firefox`)
2. Atom 0.210.0 (installed from [Webupd8 PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/atom))
3. Linux Mint 17.1 Rebecca, XFCE edition, fully updated and with XFCE 4.12

Not sure if the last one is important, I'll add others to the list or remove the point altogether if the specific Linux distro turns out to be irrelevant.

### Steps to reproduce:

1. Run Firefox and open some tabs
2. Run Atom in safe mode to isolate the issue (I used `atom --safe .` from terminal)
3. Grab one of the Firefox' tabs and drag it over the Atom's window, not releasing the mouse button

**Result**: Atom crashes, outputting the following into the terminal:
```
[10718:0622/124154:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
App load time: 288ms
[10755:0622/124154:INFO:renderer_main.cc(212)] Renderer process started
[10718:0622/124154:INFO:CONSOLE(175)] "Enabled theme 'tomorrow-night-eighties-syntax' is not installed.", source: /opt/atom/resources/app.asar/src/theme-manager.js (175)
[10718:0622/124155:INFO:CONSOLE(175)] "Enabled theme 'tomorrow-night-eighties-syntax' is not installed.", source: /opt/atom/resources/app.asar/src/theme-manager.js (175)
[10718:0622/124155:INFO:CONSOLE(175)] "Enabled theme 'tomorrow-night-eighties-syntax' is not installed.", source: /opt/atom/resources/app.asar/src/theme-manager.js (175)
[10718:0622/124156:INFO:CONSOLE(56)] "Window load time: 1439ms", source: file:///opt/atom/resources/app.asar/static/index.js (56)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 1312 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by 50Wliu** [comment] 2015-06-22 12:48
Duplicate of #3593, please subscribe there for updates.

**Closed by 50Wliu** 2015-06-22 12:48 UTC
