### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by YUTATanamoto** [atom/atom#19651] opened 2019-07-10 01:51 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\human\AppData\Local\atom\app-1.38.2\resources\app\static\<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1190092)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1185798)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:89970)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:79712)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:70365)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:67993)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:92801)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by StuartHadfield** [comment] 2019-07-10 08:43
Hey, got the same thing on MacOS. Attaching the stack trace for extra info.

[Enter steps to reproduce:]

1. Open Atom?

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at DisplayLayer.updateSpatialIndex (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:94452)
    at DisplayLayer.populateSpatialIndexIfNeeded (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:95597)
    at DisplayLayer.doBackgroundWork (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:81871)
    at TextEditor.doBackgroundWork (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:641)
```

**Comment by BrendanPotts** [comment] 2019-07-10 14:55
I am only getting the issue when I try and scroll past 552 lines

**Comment by md37** [comment] 2019-07-11 09:47
Working on my Windows 10

**Comment by rsese** [comment] 2019-07-11 20:00
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/19108 so you can subscribe there for updates if you'd like.

Based on previous reports, it seems like the error isn't reproducible if you close and reopen the file or project that's giving you trouble.  But if anyone has specific repro steps with a minimal example, please let us know in https://github.com/atom/atom/issues/19108.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-07-11 20:00 UTC
