### ISSUE TITLE
"Atom" crashs on open minify css file.

### ISSUE THREAD

**Issue by dslpp056193** [atom/atom#10042] opened 2015-12-13 18:11 UTC
Then i opened minify css file (where all code in one line), "atom" crashs.

## Versions

* **Atom:**       1.3.1
* **Atom-Shell:** 
* **OS:** Windows 7
* **Misc**
    * apm  1.4.1
    * npm  2.13.3
    * node 0.10.40
    * python 
    * git 
    * visual studio 

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by mnquintana** [comment] 2015-12-13 18:26
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/979 – feel free to subscribe there for updates.

**Closed by mnquintana** 2015-12-13 18:26 UTC
