### ISSUE TITLE
Issue Ubuntu 14.04.2 I was following the method on the linux install page used ubuntu method

### ISSUE THREAD

**Issue by cre84j** [atom/atom#6315] opened 2015-04-09 03:48 UTC
gregory@gregory-UX303LA:~$ atom -v
No command 'atom' found, did you mean:
 Command 'atom4' from package 'atom4' (universe)
 Command 'atobm' from package 'x11-apps' (main)
 Command 'atop' from package 'atop' (universe)
 Command 'atoms' from package 'horae' (multiverse)
 Command 'atrm' from package 'at' (main)
atom: command not found
gregory@gregory-UX303LA:~$ cd atom
gregory@gregory-UX303LA:~/atom$ cd ../
gregory@gregory-UX303LA:~$ npm -v
1.3.10
gregory@gregory-UX303LA:~$ node -v
v0.10.25
gregory@gregory-UX303LA:~$ sudo npm run-script atom script/build
[sudo] password for gregory: 
npm ERR! Error: ENOENT, open '/home/gregory/node_modules/atom/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-33-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "atom" "script/build"
npm ERR! cwd /home/gregory
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/gregory/node_modules/atom/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gregory/npm-debug.log
npm ERR! not ok code 0
gregory@gregory-UX303LA:~$ 

Everything seemed right untill I tried: script/build
Nothing doing so tested for atom as you can see above, nodes there, npm is there. I don't think I should be using npm for this but just don't know enough yet. Can anyone tell me what's happening and what I got wrong please.

**Comment by thomasjo** [comment] 2015-04-09 05:27
You need to follow the instructions properly: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#instructions.
I don't get why are you're doing `sudo npm run-script atom script/build`. You're supposed to merely execute `script/build` from the root of wherever you cloned the git repo.

---
Closing this as a user error.

**Comment by cre84j** [comment] 2015-04-09 05:30
I did follow those instructions it didn't work so tried something else

**Comment by cre84j** [comment] 2015-04-09 05:31
what are you doing closing this its not resolved

**Comment by thomasjo** [comment] 2015-04-09 05:38
Your issue text did not show any attempt at following the build instructions, only an incorrect approach, so I assumed you didn't try do the *right thing*. You really need to provide more details about what steps you followed prior to what you have shown us above. For instance, what was the result of doing `script/build`?

**Comment by cre84j** [comment] 2015-04-09 05:43
well I closed that terminal down it was earlier in the day and there was a lot of things I tried
Nothing at all as I remember
gregory@gregory-UX303LA:~$ cd atom
gregory@gregory-UX303LA:~/atom$ script/build
npm v1.4+ is required to build Atom. Version 1.3.10 was detected.
gregory@gregory-UX303LA:~/atom$ 

thats what happens just tried it again

**Comment by cre84j** [comment] 2015-04-09 05:45
I don't know what to do from here

**Comment by thomasjo** [comment] 2015-04-09 05:48
The error message tells you what the problem is
```
npm v1.4+ is required to build Atom. Version 1.3.10 was detected
```

The instructions [clearly state](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#requirements) that you need version 1.4+.
You need to update `npm` — http://stackoverflow.com/a/6237400/57858. Now I'm closing this issue, as it's clearly a user error and not a problem with Atom. If you need further assistance regarding building from source, go to https://discuss.atom.io/.

**Closed by thomasjo** 2015-04-09 05:48 UTC
