### ISSUE TITLE
Make word regex language specific

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#1685] opened 2014-03-04 17:59 UTC
As is discussed in atom/autocomplete#13, for a language like CSS, a `-` character needs to be considered part of a word. Allowing the word regex to be overridden with a syntactic scope would allow the autocompleter to work more intuitively in CSS.

**Comment by fbender** [comment] 2015-02-16 16:00
Will this also solve the issue of autocomplete creating `linear-linear-gradient` after you typed `linear-g`, selected the appropriate entry and hit `Tab`?

**Comment by izuzak** [comment] 2015-09-11 21:11
I think we can close this since the `nonWordCharacters` config setting has been a scoped setting for a while and can be defined for each grammar:

https://github.com/atom/settings-view/blob/5a115f9e051da32e7af676daf6076d890d8d5e75/lib/settings-panel.coffee#L20

> Will this also solve the issue of autocomplete creating linear-linear-gradient after you typed linear-g, selected the appropriate entry and hit Tab?

I'm unable to reproduce this behavior with autocomplete on Atom 1.0.11, so I'll say "yes" :8ball: :smile:

**Closed by izuzak** 2015-09-11 21:11 UTC
Labels: enhancement
