### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createObjectStore' of undefined

### ISSUE THREAD

**Issue by aquddos** [atom/atom#16781] opened 2018-02-19 11:49 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'createObjectStore' of undefined

```
At C:\Users\AQ\AppData\Local\atom\app-1.24.0\resources\app\src\state-store.js:17

TypeError: Cannot read property 'createObjectStore' of undefined
    at IDBOpenDBRequest.dbOpenRequest.onupgradeneeded (~/AppData/Local/atom/app-1.24.0/resources/app/src/state-store.js:17:19)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-02-20 00:03
Thanks for the report - looks like this was reported a while back /cc https://github.com/atom/atom/issues/11577.  

Do you remember what you were doing at the time of the error and if the error is reproducible?

**Comment by lee-dohm** [comment] 2018-02-28 21:05
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16781#issuecomment-366830809. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by lee-dohm** 2018-02-28 21:05 UTC
Labels: more-information-needed, uncaught-exception
