### ISSUE TITLE
Code Color lost in an Array with many Elements

### ISSUE THREAD

**Issue by treedbox** [atom/atom#15758] opened 2017-09-27 21:29 UTC
versions: **1.21.0-beta2** (Windows) and **1.17.2x64** (Linux)
language: **JavaScript**
When i type:
`let foo=[ "top","window","location","external","chrome","document","inlineCSS","target","width","height","canvas","data","DOMURL","img","svg","ctx","url","w","a","speechSynthesis","webkitNotifications","localStorage","sessionStorage","applicationCache","webkitStorageInfo","indexedDB","webkitIndexedDB","crypto","CSS","performance","console","devicePixelRatio","styleMedia","parent","opener","frames","self","defaultstatus","defaultStatus","status","name","length","closed","pageYOffset","pageXOffset","scrollY","scrollX"];`

If i type: **let foo=[** (without space) or **let foo =[** (whitout space between assigment and square brackets), after the 24 element, atom lost the visual color code:
![array-visual](https://user-images.githubusercontent.com/4041664/30938400-44d5a288-a3b0-11e7-8cc9-87a34edfc532.png)

if i type: **let foo = [** appears normal:
![atom-normal](https://user-images.githubusercontent.com/4041664/30938621-0fa43286-a3b1-11e7-88d7-4ac0ee1eb3ea.png)

**Comment by 50Wliu** [comment] 2017-09-27 21:43
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1667. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-09-27 21:43 UTC
