### ISSUE TITLE
Editor Scrolls Down When Clicking Directly Above Horizontal Scrollbar

### ISSUE THREAD

**Issue by nathansomething** [atom/atom#15489] opened 2017-08-29 15:18 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The editor view scrolls down/up if you click near the bottom/top of the page. This is particularly annoying because whenever I try to scroll horizontally, the editor scrolls down. Is there anyway to fix this?

### Steps to Reproduce

1. Open Atom
2. Click right above the horizontal scrollbar
3. The editor window scrolls down

**Expected behavior:** The editor does not scroll

**Actual behavior:** The editor scrolls down

Gif from @rsese https://github.com/atom/atom/issues/15489#issuecomment-325751074

![click-scroll](https://user-images.githubusercontent.com/734194/29837029-a65cbfec-8cbc-11e7-9ce4-085329e95390.gif)

**Reproduces how often:** 100% of the time

### Versions 1.19.4

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

I'm running macOS Sierra version 10.12.6

From @rsese:

Should set `System Preferences > General > Show scroll bars` to `Always`.

Doesn't reproduce in 1.18.0.

**Comment by rsese** [comment] 2017-08-29 18:21
Thanks for the report - I can reproduce this as of 1.19.0 and on 1.19.4 on macOS 10.12.6 but not if I click directly on the horizontal scrollbar, only if I click directly above the horizontal scrollbar.

![click-scroll](https://user-images.githubusercontent.com/734194/29837029-a65cbfec-8cbc-11e7-9ce4-085329e95390.gif)

I couldn't reproduce on 1.18.0 though so tagging as a regression.

**Comment by Ben3eeE** [comment] 2017-08-29 18:39
This is really annoying on Windows because you can't even click on the scrollbar without hitting this bug /cc: https://github.com/atom/atom/issues/15488

**Comment by sanada01** [comment] 2017-08-30 08:37
If I click on the horizontal scroll, it causes the same issue, i hope there is a solution because it's very annoying. Please fix this bug. :)

![atombug](https://user-images.githubusercontent.com/28780118/29862981-8c6b0046-8d6e-11e7-8686-bbac9977fcb2.gif)

**Comment by rsese** [comment] 2017-08-30 20:34
Added to the project board but /cc @as-cii @nathansobo on this regression (also I think you were looking at other scrolling issues Antonio?) :v:

**Comment by rsese** [comment] 2017-08-30 20:42
I also tried again in 1.19.4 and now see this behavior when clicking on the scroll bar, not sure why I didn't see it before.

**Comment by Ben3eeE** [comment] 2017-08-31 13:19
@rsese I'm not sure if this was fixed by #15515. #15515 only fixed the mouse moving when clicking on the scrollbar. But it seems that there was another issue here as well?

**Comment by rsese** [comment] 2017-08-31 20:35
Yeah I think so :+1:

The case where clicking on the horizontal scrollbar scrolls down is fixed like you said @Ben3eeE  but in the case where you click right above the scroll bar, it still scrolls down.   I'll go ahead and re-open this one @as-cii :v:

**Comment by Ben3eeE** [comment] 2017-09-01 06:58
@rsese I edited the title and body of the issue to make it more clear what the problem is. It would be great if you could check that my description is accurate :zap:

**Closed** 2017-09-06 09:12 UTC
Labels: bug, regression, triaged
