### ISSUE TITLE
Atom is really slow when opening jquery.min.js

### ISSUE THREAD

**Issue by zg** [atom/atom#8462] opened 2015-08-21 03:10 UTC
I tried to open jquery.min.js and Atom was really slow. I'm running the latest version on Windows 8.1.

**Comment by mnquintana** [comment] 2015-08-21 03:27
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/979 - please subscribe there for updates.

**Closed by mnquintana** 2015-08-21 03:27 UTC
