### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by KevinAMurray** [atom/atom#17615] opened 2018-07-03 10:08 UTC
[Enter steps to reproduce:]

1. Have gitbook serve running in background whilst editing gitbook
2. edit page and save
3. wait for gitbook serve to reindex pages (and possibly load page in browser)
4. Atom raises above exception

I can also replicate by:

1. Run atom
2. open suitable (gitbook) project
3. "touch" any file in project, e.g. run "touch SUMMARY.md"
4. Atom raises above exception

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:28

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at onEvents.events.map.event (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:283:46)
    at Array.map (<anonymous>)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:276:34)
```

### Commands

```
  3x -1:50.9.0 core:move-right (input.hidden-input)
     -1:50.1.0 core:backspace (input.hidden-input)
     -1:49.3.0 core:move-down (input.hidden-input)
     -1:48.9.0 core:backspace (input.hidden-input)
 13x -1:48.6.0 core:move-left (input.hidden-input)
     -1:46.5.0 core:backspace (input.hidden-input)
     -1:46.1.0 core:move-up (input.hidden-input)
  2x -1:45.7.0 core:move-right (input.hidden-input)
     -1:45.2.0 core:backspace (input.hidden-input)
     -1:44.9.0 core:move-up (input.hidden-input)
     -1:44.6.0 core:move-left (input.hidden-input)
     -1:44.2.0 core:backspace (input.hidden-input)
     -1:43.9.0 core:move-up (input.hidden-input)
     -1:43.6.0 core:move-right (input.hidden-input)
     -1:43.2.0 core:backspace (input.hidden-input)
     -1:39.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-07-03 17:09
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14227 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-07-03 17:09 UTC

**Comment by KevinAMurray** [comment] 2018-07-09 16:32
(Sorry for delay!)

1) mkdir Test
2) Atom Test/Test2
3) Enter some data, and save (cmd-S)
4) touch Test/Test2
6) Enter some more text, and save (cmd-S)

and I get the path.js exception mentioned.

Anything else I can do to help track/fix this?

**Comment by KevinAMurray** [comment] 2018-07-09 16:32
Opps. Wrong thread
