### ISSUE TITLE
100% CPU on Fedora25 launched form GUI

### ISSUE THREAD

**Issue by ezickler** [atom/atom#13324] opened 2016-11-24 15:41 UTC
Hi,

when i start Atom from gnome 3 on a fresh installed Fedora 25. Atom spawns an process 
"/bin/zsh -ilc command env" which used up 100% of cpu and dosn't get killed if i close atom.

When is start atom from a terminal this dosn't happen.  Noticed after i tried --safe and then without it. 
Also moved my ./atom folder and deactivated all packages. Both have no effect. 

I'm not sure if this is a gnome/fedora problem or a problem in your rpm package.

**Comment by Ben3eeE** [comment] 2016-11-24 15:49
Closing as a duplicate of https://github.com/atom/atom/issues/13317.

**Closed by Ben3eeE** 2016-11-24 15:49 UTC
