### ISSUE TITLE
C syntax highlighter underscore problem in markdown files

### ISSUE THREAD

**Issue by kkeri** [atom/atom#10398] opened 2016-01-13 12:50 UTC
In a markdown file, when I'm using C or C++ syntax highlight, names **starting with a single
 underscore** will break the syntax highlighter for the remaining part of the whole markdown file.

This happens with names in special contexts. For example this block will break highlighting:

    ~~~C
    f(_);
    ~~~

But not these one:

    ~~~C
    struct _;
    ~~~

**Atom version:** 1.3.3

**OS and version:** Windows 7 SP1

**Installed packages:** this is a fresh installation with all the standard packages

**Screenshot:**

![](https://cloud.githubusercontent.com/assets/1475458/12294557/bac52fb8-b9fb-11e5-92c5-ed78f20cba6f.png)

**Comment by kepta** [comment] 2016-01-13 14:57
What does ~ do in markdown?

**Comment by 50Wliu** [comment] 2016-01-13 15:18
It's the same as \`\`\` I believe.

**Comment by 50Wliu** [comment] 2016-01-13 15:19
Actually, this is a duplicate of atom/language-gfm#44 - @kkeri please subscribe there for updates.

**Closed by 50Wliu** 2016-01-13 15:19 UTC

**Comment by kkeri** [comment] 2016-01-13 15:20
@50Wliu: I see. Thanks.

@kepta: It is a variation of writing fenced code blocks in markdown. It's not part of the original markdown but supported by [pandoc](pandoc.org) and also included in the [commonmark](http://commonmark.org) specification.

Three or more ~ at the beginning of a row starts / ends a code block.
It also works with \` characters (it is understood by [github flavored markdown](https://help.github.com/articles/github-flavored-markdown/)).

I want to remark that the bug can also be reproduced using the \`\`\`c syntax.

**Comment by kepta** [comment] 2016-01-13 18:24
@kkeri that I didn't know. Yes, I can confirm ``` shows up with this bug.
