### ISSUE TITLE
Matching bracket is not found after first click after Select Next

### ISSUE THREAD

**Issue by AgentME** [atom/atom#10118] opened 2015-12-17 21:52 UTC
Have the following text open:

```
{
  foo
  foo {
  }
}
```
1. Place the cursor somewhere on the first "foo".
2. Activate "Find And Replace: Select Next" (bound to cmd-D on OS X by default) twice so that both "foo"  occurrences are selected.
3. Click to the right of the the closing brace on line 4 to place the cursor immediately to the right of it.
4. Notice that the brace and its partner are not underlined as they usually should be when you place the cursor touching a brace.
5. Activate "Bracket Matcher: Go To Matching Bracket" (ctrl-M on OS X by default).
6. See that the cursor jumps to before the opening brace on line 1 instead of the opening brace on line 3.

**Comment by lee-dohm** [comment] 2015-12-17 23:17
I cannot reproduce this issue using Atom v1.5.0-dev-329d7f4 on Mac OS X 10.11.2.

Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by AgentME** [comment] 2015-12-17 23:21
I'm on Atom 1.3.2 on OS X 10.11.1. I don't have Emmet installed. I can reproduce in safe mode.

**Comment by rsese** [comment] 2017-03-09 05:48
Trying to go through and cleanup some older issues - it's been a while since this report and Atom is currently at release version 1.14.4.  I also tried to reproduce the behavior with the steps to reproduce but couldn't.

I'll go ahead and close the issue for now but if you're still seeing this behavior with the latest release version of Atom and in safe mode, please let us know @AgentME :v:

**Closed by rsese** 2017-03-09 05:48 UTC
Labels: more-information-needed, needs-reproduction
