### ISSUE TITLE
Git panel not show when open it at first time

### ISSUE THREAD

**Issue by juliaovod** [atom/atom#18529] opened 2018-12-02 11:34 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I am opening project at first time and then opening Git panel, it is not shown. But when i clicking on the right side of mouse on Git panel area and choosing «Close Pane ⌘W» and then reopen this with button from bottom panel – it is showing!

### Steps to Reproduce

[See screen record](https://drive.google.com/file/d/1h3idQxIukyNRtvPGT99U3VZsojmmNl-a/view?usp=sharing)

1. Open project at first time in Atom
2. Click the button which locate in bottom panel for open git panel
3. Move mouse to git panel area, click one the right side of mouse and choosing «Close Pane ⌘W»
4. Repeat second step

**Expected behavior:** Git panel must open at first time

**Actual behavior:** Git panel open after some magic actions

**Reproduces how often:** Every time when i try open project and try open git panel at first time

### Versions
**atom --version**
```
Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
**apm --version**
```
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.10
git 2.15.1
```
**OS Information**
```
macOS High Sierra
Version 10.13.6
```

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-12-03 19:15
Thanks for the report and for taking the time to create a video, that's super helpful :bow:

Based on your description and video, we noticed that this looks like a duplicate of https://github.com/atom/github/issues/1718 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-12-03 19:15 UTC
