### ISSUE TITLE
Does Atom Support Array's For Package Settings Yet?

### ISSUE THREAD

**Issue by JosephTLyons** [atom/atom#17827] opened 2018-08-12 08:46 UTC
## Summary

It seems that Atom supports manually using an array to hold user settings in the config.cson file.  For example:

```
"your-package":
    arrayName: [
      value1
      value2
      ...
    ]
```

However, I don't think there is an interface for a user in the package settings like we would normally see for say an integer (I could be wrong, but I'm not seeing anything when defining such a setting in the package.json file:

```
"arrayName": {
      "title": "Array Name",
      "type": "array",
      "default": [value1, value2, ...]
```

So if a package needs to use an array and the user is supposed to be able to set the values of that array, they must do it in the config.cson file.  It would be nice if in the package settings there was a line where the user could insert values, separated by commas, so they wouldn't have to manually insert them in the config.cson file.

## Motivation

It would be way more convenient to have a visual UI to insert the values over using the config.cson file.   I know that VS Code does this with certain settings (for example, the wrap guide in VS Code is an array that the user can set multiple values in for multiple wrap guides).

## Describe alternatives you've considered

None.

## Additional context

None.

**Comment by lee-dohm** [comment] 2018-08-12 16:28
Thank you for your submission!

We noticed that this is a duplicate of https://github.com/atom/settings-view/issues/279. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2018-08-12 16:28 UTC
