### ISSUE TITLE
Square bracket not working on Windows 7

### ISSUE THREAD

**Issue by jdepypere** [atom/atom#7842] opened 2015-07-11 13:07 UTC
I've had this issue with pre-1.0 builds as well, but it doesn't seem to be fixed. Whenever I try to type in an opening square bracket, `[`, it doesn't show. The key does work, as `^` and `¨` do work. The closing bracket `]` does show up. Also in other programs this key works.

My keyboard layout is dutch azerty (not sure what the official name is), looking like this:

![2000px-belgian_pc_keyboard svg](https://cloud.githubusercontent.com/assets/3522063/8633812/beb94984-27dd-11e5-9122-d692157ee207.png)

The blue letters have to be typed together with `Alt Gr`. I have already checked the keybindings that there is nothing overriding the combination, but can't really find an issue:

![altg](https://cloud.githubusercontent.com/assets/3522063/8633821/009d5836-27de-11e5-96c2-9cd2fe5406d5.PNG)

Again, closing the square bracket works. Also other `Alt Gr` combinations work, such as `@`, `|`, `#`, `{`, `}`, `]`, ...

**Comment by mnquintana** [comment] 2015-07-11 13:12
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-11 13:12 UTC
