### ISSUE TITLE
File save issues in 1.15

### ISSUE THREAD

**Issue by umpirsky** [atom/atom#13995] opened 2017-03-13 15:28 UTC
### Description

This started to happen after upgrade  from `1.14.0` to `1.15.0`.

After file save file chooser is not focused and current folder is not selected.

![screencast from 13-03-17 16_21_47](https://cloud.githubusercontent.com/assets/208957/23861282/db353588-0809-11e7-9799-7779276a0565.gif)

### Steps to Reproduce

1. Create new file
2. Try to save it

### Versions

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.7.4
```

**Comment by rsese** [comment] 2017-03-13 16:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13978. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-13 16:56 UTC

**Comment by umpirsky** [comment] 2017-03-13 16:58
Sure, will subscribe, thanks.
