### ISSUE TITLE
Strange syntax hiliting in md documents

### ISSUE THREAD

**Issue by mrstux** [atom/atom#16380] opened 2017-12-14 03:42 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using a javascript code block in a mark-down document, which contains a non-fully formed function (ie with {}), the syntax hiliter does not correctly hilite syntax after the code block closes.

### Steps to Reproduce

Place the following in a markdown editor window

>>>
```javascript
function somePrototype( someArgument); // returns somethingElse
```
*this* **should** `be` hilited
<<<

**Expected behavior:**

I expect the contents of the javascript code block to not affect the syntax hiliting of the rest of the document.

**Actual behavior:**

The the syntax colorer seems to stop functioning until another javascript code block is included with curly braces, for example

>>>
```javascript
function somePrototype( someArgument); // returns somethingElse
```
*this* **should** `be` hilited

```javascript
{}
```
*now* **this** is `hilited` correctly
<<<

A picture of the strange behaviour:
![strange syntax coloring on md docs](https://user-images.githubusercontent.com/2467970/33974514-f1a718ac-e0dc-11e7-89ef-9068bda9f53c.png)

**Reproduces how often:** 

100%

### Versions

atom --version
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Mac OS X 10.12.6

### Additional Information

Seems to work fine in the HTML MarkDown preview though.

**Comment by rsese** [comment] 2017-12-14 19:20
Thanks for taking the time to contribute!  I think this might be a duplicate of or at least similar to issues like https://github.com/atom/language-gfm/issues/171 so you can subscribe there for updates if you'd like.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-14 19:20 UTC
