### ISSUE TITLE
Window position gets restored even if out of visible area

### ISSUE THREAD

**Issue by Neosublimation** [atom/atom#9223] opened 2015-10-20 07:34 UTC
**Version:** Atom 1.0.19 on Windows 7 (64 Bit)

**Observed Behavior:**
I'm using Atom on my Laptop at different locations, some of which I have a second screen at. After using Atom on such a second screen lately I found the editor to restore its window position without a second screen available today, i.e. it moved itself out of the visible area on start.

**Expected Behavior:**
Before restoring its old position, Atom checks whether that position would place it outside the current visible area (defined by all installed screend and their resolution). If so, it just moves to some default position (e.g. `(0; 0)`).

**Workaround:**
There might be some easy tricks, but I was just lucky to have a program I regularly use to easily order my windows and that tool is able to move the window back into the visible area. Those who are not having such a tool may find [this solution from superuser.com](http://superuser.com/a/53590) useful (but as this issue hasn't been posted yet I assume as a regular screen-configuration-changer I'm part of a minority).

I don't see this as a major/important issue, but I wanted to report it for the sake of integrity. **If you're able to, please try to reproduce this. It may also just be an issue on my side.**

**Comment by lee-dohm** [comment] 2016-05-03 16:11
This is a duplicate of #6939. You may want to subscribe there for updates.

**Closed** 2016-05-03 16:12 UTC
Labels: duplicate
