### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by gianlucainnocente** [atom/atom#15232] opened 2017-08-10 12:16 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2168

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2168:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:385:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -2:40.5.0 core:paste (input.hidden-input)
     -2:40.4.0 core:confirm (input.hidden-input)
  2x -2:36.6.0 core:copy (input.hidden-input)
     -2:33.4.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -2:31.6.0 core:confirm (input.hidden-input)
  2x -2:30.1.0 editor:newline (input.hidden-input)
     -2:29.6.0 core:paste (input.hidden-input)
     -2:27.8.0 editor:newline (input.hidden-input)
     -2:26.2.0 autocomplete-plus:confirm (input.hidden-input)
     -2:26.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -2:23.5.0 core:save (input.hidden-input)
     -0:28.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:23 core:select-all (input.hidden-input)
     -0:21.6.0 core:confirm (input.hidden-input)
     -0:20.5.0 find-and-replace:show (input.hidden-input)
  4x -0:19.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-minify 0.8.0 
busy-signal 1.4.3 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.3 
pigments 0.39.1 
```

**Comment by 50Wliu** [comment] 2017-08-10 12:53
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15168. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-10 12:53 UTC
