### ISSUE TITLE
Switching desktops in OS X makes text cursor change to normal cursor (fullscreen mode).

### ISSUE THREAD

**Issue by cubuspl42** [atom/atom#9489] opened 2015-11-08 12:46 UTC
![atombug1](https://cloud.githubusercontent.com/assets/2590174/11020375/80a5e8f6-861e-11e5-8ed8-64a86dc23b7a.gif)

When Atom is in fullscreen mode and you click on some text in Atom, you can see a text cursor. That's correct. But when you switch to other desktop, and then switch to Atom again, the cursor is not a text cursor. Even clicking on the text again doesn't change that. The only workaround is to move the cursor to some other widget, and then move it over text area again.

Atom 1.1.0, OS X 10.11

**Comment by mcpDESIGNS** [comment] 2015-11-08 18:18
+1

**Comment by chbk** [comment] 2015-12-10 17:42
Having a very similar issue here: #8566

**Comment by cubuspl42** [comment] 2015-12-10 22:49
Although it might seem irrelevant, I'll note that JetBrains products also have similar issue. It might be OS X non obvious behavior / bug.

**Comment by rsese** [comment] 2017-08-08 23:36
Coming here from https://github.com/atom/atom/issues/8566 - I can't reproduce as described on macOS 10.12.6 and Atom 1.18.0.  Going to go ahead and close this but let us know if you still see the issue @cubuspl42 and if so, what version of macOS you're on.

**Closed by rsese** 2017-08-08 23:36 UTC
Labels: bug, mac
