### ISSUE TITLE
Not displaying hidden character: 200b (ZERO WIDTH SPACE)

### ISSUE THREAD

**Issue by scedge** [atom/atom#7631] opened 2015-07-01 17:01 UTC
Not sure how the character got into my code but it does not show up in Atom even with Show Invisibles set to true.

Info on the character can be found here http://www.fileformat.info/info/unicode/char/200b/index.htm

My specific issue: If this character comes after a CSS closing curly bracket, all following styles are inaccessible and do not parse. 

Example: https://jsfiddle.net/9tuy9w8o/2/
Setting the image class to cat works but setting it to dog causes it to break.

**Comment by chuntr** [comment] 2016-07-07 01:15
I just discovered this same issue, coding with PHP. Also in my case, the "zero-width space" after a closing curly bracket results in a ```PHP Parse error:  syntax error, unexpected '' (T_STRING), expecting function (T_FUNCTION)```

**Comment by lee-dohm** [comment] 2016-07-12 21:57
This is a duplicate of #1839. You may want to subscribe there for updates.

**Closed** 2016-07-12 22:03 UTC
Labels: duplicate
