### ISSUE TITLE
Wrong version number on OS X

### ISSUE THREAD

**Issue by hugokrantz** [atom/atom#9836] opened 2015-11-26 12:50 UTC
The Mac binary has the version number stuck at 1.1.0, even after updating to newer versions.

This causes the release notes tab to not show newer notes than 1.1.0 and show the ”Restart and update” button. If you are already running the latest version (as I am), all the button does is quit the app.

The ”About” tab shows the correct version.

**Comment by mnquintana** [comment] 2015-11-26 14:51
Thanks for the report! This looks like a duplicate of https://github.com/atom/release-notes/issues/39 - please subscribe there for updates.

**Closed by mnquintana** 2015-11-26 14:51 UTC

**Comment by hugokrantz** [comment] 2015-11-26 14:55
Oh bummer! I actually _did_ search for duplicates before posting, but obviously I failed. :-(
