### ISSUE TITLE
Allow customization of install path for Atom

### ISSUE THREAD

**Issue by AluminiumTech** [atom/atom#14212] opened 2017-04-15 03:36 UTC
### Description
Atom defaults to installing on the drive containing Windows. This is not particularly helpful and is a real pain point of atom. It's almost a dealbreaker. 

I would like for Atom to allow users to choose where to install it. This one of the only things that stops me from recommending atom to others and using atom whenever I need a code editor.

There is no excuse for why I can't currently configure where to install Atom. I can configure where to install almost all other Windows programs including those from the Windows Store.

Please fix this. 

### Versions

All versions affected

**Comment by MaximSokolov** [comment] 2017-04-15 16:10
This is duplicate of #7504

**Comment by rsese** [comment] 2017-04-17 07:07
Thanks @MaximSokolov :v:

**Closed by rsese** 2017-04-17 07:07 UTC
