### ISSUE TITLE
Create issue from notification does not work

### ISSUE THREAD

**Issue by poci-hu** [atom/atom#12431] opened 2016-08-15 12:42 UTC
version 1.9.8.
Windows 10 pro

Tried to click the button in the notification, but nothing happens.
I tried to create:  #12430

**Comment by 50Wliu** [comment] 2016-08-15 14:42
This is a duplicate of atom/notifications#129 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-15 14:42 UTC
