### ISSUE TITLE
Chrome 41 - Text selection not working in Virtual Box

### ISSUE THREAD

**Issue by jpmn** [atom/atom#6360] opened 2015-04-13 19:14 UTC
When trying to drag the mouse in order to select text, nothing happen and the cursor stays where the mouse was first clicked. It also prevent from drag and dropping tabs in the same way.

I had the same bug as soon as I updated my Google Chrome to version 41. I had to add this flag '--touch-devices=123' when opening it as mentionned in this issue tracker:

https://code.google.com/p/chromium/issues/detail?id=456222#c102

I do not know how I can add this flag for Atom?

Windows 8.1 Host, Ubuntu 14.04 Guest, VirtualBox 4.3.26

**Comment by mnquintana** [comment] 2015-04-13 19:17
Duplicate of #6306 - please track that issue for updates. Thanks for the submission though!

**Closed by mnquintana** 2015-04-13 19:17 UTC
