### ISSUE TITLE
Multiple `:` colons in commands

### ISSUE THREAD

**Issue by jerone** [atom/atom#6893] opened 2015-05-21 18:54 UTC
I can't find any docs that says that using more then one `:` in a command isn't allowed. 
Executing a command with multiple colons works as expected, however the [Command Palette](https://github.com/atom/command-palette) doesn't show the text after the second colon.

**Example commands:**
[`tool-bar:position:top`](https://github.com/suda/tool-bar/blob/master/lib/tool-bar-view.coffee#L34)
[`tool-bar:position:right`](https://github.com/suda/tool-bar/blob/master/lib/tool-bar-view.coffee#L37)
[`tool-bar:position:bottom`](https://github.com/suda/tool-bar/blob/master/lib/tool-bar-view.coffee#L40)
[`tool-bar:position:left`](https://github.com/suda/tool-bar/blob/master/lib/tool-bar-view.coffee#L43)

**Screenshot Command Palette:**
[![tool-bar command palette](https://cloud.githubusercontent.com/assets/941075/7754772/8dd535ac-ffc5-11e4-9018-929ac8b5e5b3.png)](https://github.com/suda/tool-bar/issues/40)

**Trace:**
After some research I traced it down to Underscore Plus [`humanizeEventName`](https://github.com/atom/underscore-plus/blob/master/src/underscore-plus.coffee#L142), which then only takes the first and second parts.

**Specs:**
Windows 7 64-bits
Atom 0.200.0
tool-bar 0.1.1

**Comment by thomasjo** [comment] 2015-05-21 19:48
It's not supported because the definition is `namespace-name:event-name`. Each part is separated into words by using dashes. You should change those position events to `tool-bar:position-top`, `tool-bar:position-bottom`, etc.

I'm closing this it's working as designed. While it's not explicitly documented that the used pattern is **not** documented, it's also never implied to work. The only examples documented are of the support format (see e.g. https://atom.io/docs/api/v0.200.0/CommandRegistry).

If you believe this should be better documented on our end, let us know here, or better yet open a PR with added documentation in https://github.com/atom/atom/blob/master/src/command-registry.coffee, and/or [atom/docs](https://github.com/atom/docs).

**Comment by jerone** [comment] 2015-05-21 19:59
Understood. Then I'm requesting to update the documentation with the part you mentioned; "`namespace-name:event-name`". I'm not confident with my English to send a PR for a doc change.

**Comment by thomasjo** [comment] 2015-05-21 20:08
Either me, or one of the other maintainers will change the documentation :+1:—I'm reopening the issue until the documentation gets tweaked.

**Closed** 2015-05-29 20:45 UTC
Labels: documentation
