### ISSUE TITLE
Open Window doesn't appear unless you a window in atom already open

### ISSUE THREAD

**Issue by koldrid** [atom/atom#13540] opened 2017-01-04 17:58 UTC
### Description

Open Window doesn't appear unless you a window in atom already open

### Steps to Reproduce

1. Open Atom
2. Close all windows, do not quit the application
3. Go to the File Menu and click on Open

**Expected behavior:** A window to open up allowing me to select a file/folder to open in Atom

**Actual behavior:** Nothing

**Reproduces how often:** Always

### Versions

Atom    : 1.12.8
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

macOS: 10.12.2 Build 16C67

### Additional Information

This is on a fresh install of macOS. Also the Open Window does appear but only when you have a window in Atom already open.

**Comment by Ben3eeE** [comment] 2017-01-04 18:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-01-04 18:54 UTC
