### ISSUE TITLE
Atom doesn't ignore commented out braces!

### ISSUE THREAD

**Issue by Wafflespeanut** [atom/atom#9279] opened 2015-10-25 04:51 UTC
![shot](https://cloud.githubusercontent.com/assets/6691262/10714088/42c22ed2-7b01-11e5-95ea-321fd6590dbd.png)

Well, this is just a minor enhancement. While fiddling around some code, I can always comment out a particular condition block and insert another one, but if the commented out brace points to something that's alive, then it's definitely gonna confuse the situation.

So, shall we make atom ignore the braces in comments?

**Comment by mnquintana** [comment] 2015-10-25 19:23
Thanks for the report! This looks like a duplicate of https://github.com/atom/bracket-matcher/issues/78 - feel free to subscribe there for updates.

Also, take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Closed by mnquintana** 2015-10-25 19:23 UTC

**Comment by Wafflespeanut** [comment] 2015-10-26 06:10
@mnquintana Oops, sorry about that. Thanks :)
