### ISSUE TITLE
Cannot install packages on Windows 7, Atom 0.175.0

### ISSUE THREAD

**Issue by RichardJECooke** [atom/atom#5249] opened 2015-01-25 05:56 UTC
I installed Atom for the first time today and receive the following error on installing any package. Google cannot help.  Please can anyone provide some suggestions:

---

Installing “ide-haskell@0.3.0” failed.Hide output…

npm ERR! Failed to clone git+https://github.com/saschagehlich/autocomplete-plus.git#83cfccee996ba10b69a48550717a97fcc9a01c19 from https://github.com/saschagehlich/autocomplete-plus.git fatal: could not create work tree dir 'C:\Users\ruser\AppData\Local\Temp\npm-9952-39b32829\1422165134706-0.7615572370123118\83cfccee996ba10b69a48550717a97fcc9a01c19'.: No such file or directory
npm ERR! Failed to clone git+https://github.com/saschagehlich/autocomplete-plus.git#83cfccee996ba10b69a48550717a97fcc9a01c19 from https://github.com/saschagehlich/autocomplete-plus.git 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Users\\ruser\\AppData\\Local\\atom\\app-0.175.0\\resources\\app\\apm\\bin\\\\node.exe" "c:\\Users\\ruser\\AppData\\Local\\atom\\app-0.175.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\ruser\\AppData\\Local\\atom\\app-0.175.0\\resources\\app\\apm\\.apmrc" "--userconfig" "c:\\Users\\ruser\\.atom\\.apmrc" "install" "C:\\Users\\ruser\\AppData\\Local\\Temp\\d-115025-9680-14nzkej\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code 128

npm ERR! Command failed: fatal: could not create work tree dir 'C:\Users\ruser\AppData\Local\Temp\npm-9952-39b32829\1422165134706-0.7615572370123118\83cfccee996ba10b69a48550717a97fcc9a01c19'.: No such file or directory
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by mark-hahn** [comment] 2015-01-25 06:24
I am getting this also on several packages. It seems to happen on packages
that load a repo directly from github instead of npm.

**Comment by mark-hahn** [comment] 2015-01-25 06:25
I am on windows 8.1, atom 175 and ...

apm  0.123.0
npm  2.1.18
node 0.10.35
python 2.7.8
git 1.7.11.msysgit.1
visual studio 2013

**Comment by 50Wliu** [comment] 2015-01-25 15:20
Duplicate of #5202.

**Closed by 50Wliu** 2015-01-25 15:20 UTC
