### ISSUE TITLE
Uncaught Error: dlopen(~/Downloads/atom-mac/Atom.app/Contents/Resources/app.asar.unpacked/node_mo...

### ISSUE THREAD

**Issue by Soomin97** [atom/atom#22996] opened 2021-09-17 20:31 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.5.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At electron/js2c/asar.js:140

Error: dlopen(/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_KeyboardLayoutManager (/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app/static/<embedded>:14:2894476)
    at get_manager (/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app/static/<embedded>:14:2894578)
    at Object.getCurrentKeyboardLayout (/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app/static/<embedded>:14:2894704)
    at e.keystrokeForKeyboardEvent (/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app/static/<embedded>:14:1119649)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app/static/<embedded>:11:1224825)
    at KeymapManager.handleKeyboardEvent (/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app/static/<embedded>:11:1222810)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/soomin/Downloads/atom-mac/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
```

### Commands

```
```

### Non-Core Packages

```
teletype 0.13.4 
termination 0.7.6 
```

**Comment by the-j0k3r** [comment] 2021-09-18 05:43
Seems like a bad install, have you tried re-installing?

**Comment by darangi** [comment] 2021-09-20 15:23
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2021-09-20 15:23 UTC
