### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by DanielaSofia** [atom/atom#16893] opened 2018-03-06 17:04 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /usr/share/atom/resources/app/src/text-editor-component.js:2409

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (/usr/share/atom/resources/app/src/text-editor-component.js:2409:65)
    at TextEditorComponent.screenPositionForMouseEvent (/usr/share/atom/resources/app/src/text-editor-component.js:1974:23)
    at TextEditorComponent.didMouseDownOnContent (/usr/share/atom/resources/app/src/text-editor-component.js:1773:39)
```

### Commands

```
     -1:07.6.0 core:move-up (input.hidden-input)
     -1:07.0 core:move-right (input.hidden-input)
     -1:06.0 core:move-up (input.hidden-input)
     -1:05.8.0 core:move-right (input.hidden-input)
     -1:00.6.0 core:backspace (input.hidden-input)
     -0:58.9.0 core:move-down (input.hidden-input)
     -0:58.9.0 core:move-left (input.hidden-input)
     -0:58.5.0 core:move-down (input.hidden-input)
     -0:57.9.0 core:move-up (input.hidden-input)
 11x -0:54.3.0 core:delete (input.hidden-input)
  5x -0:50.6.0 core:undo (input.hidden-input)
     -0:42 core:copy (input.hidden-input)
     -0:40 editor:newline (input.hidden-input)
  3x -0:34.8.0 core:backspace (input.hidden-input)
     -0:32.5.0 core:move-down (input.hidden-input)
  2x -0:13.5.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-03-06 18:48
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15682. You may want to subscribe there for updates - if you have any more details about reproducing the error, feel free to let us know in https://github.com/atom/atom/issues/15682.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-06 18:48 UTC
