### ISSUE TITLE
Atom will not update from 1.0.0 to 1.0.2 on Mac OS X 10.10.4

### ISSUE THREAD

**Issue by faddah** [atom/atom#7940] opened 2015-07-16 21:37 UTC
i have tried, several times, to get the new Atom 1.0.0 to update to 1.0.2, on a 27" iMac with a intel i7 2.8 GHz, 16 GB RAM, and Mac OS X 10.10.4 with all the latest updates. first, Atom _never_, repeat, _NEVER_ restarts — you click "update & restart app" and it quits the app but _never_ restarts it. never restarts. never. never, never, never. period. then, when i re-launch the app, it is _still_ at 1.0.0, even though it had said it downloaded the new 1.0.2 version and was ready to re-launch as the new, updated app. how do i fix this? please advise.

—  faddah
     portland, oregon, u.s.a.

**Comment by jonathanbull** [comment] 2015-07-16 21:47
I'm also having this issue (noted in the thread you referenced). Does anyone know if there's an error log or any kind of diagnostics we can do to try and narrow down the issue?

**Comment by mnquintana** [comment] 2015-07-16 21:47
Since this does indeed seem like a duplicate of the issue you linked from (https://github.com/atom/atom/issues/7833), let's keep the discussion there.

**Closed by mnquintana** 2015-07-16 21:47 UTC
