### ISSUE TITLE
Wrong cursor behavior when moving from tree view to editor

### ISSUE THREAD

**Issue by chbk** [atom/atom#15076] opened 2017-07-22 15:58 UTC
Running Atom 1.18.0 on OS X 10.10.5

**Expected behavior:** the cursor should always be a text cursor when hovering over code in the editor.
**Actual behavior:** clicking on the tree view then clicking on code switches the cursor to default pointer.

A gif to illustrate:

![cursor](https://user-images.githubusercontent.com/7478535/28492601-d5ea37cc-6f06-11e7-889b-9fa88c9e5fa3.gif)

Related issues: #8566 #9489 #12314

**Comment by 50Wliu** [comment] 2017-07-26 18:49
Cannot reproduce on Windows, Atom 1.20.0-dev-c84d705e5.

**Comment by rsese** [comment] 2017-08-02 01:05
Hmmm, can't reproduce either with 1.18.0 on macOS 10.12.6 - do you see any difference in safe mode @chbk?

**Comment by chbk** [comment] 2017-08-02 01:51
No difference, same bug in safe mode. It only happens when Atom is in fullscreen (just noticed this).

**Comment by 50Wliu** [comment] 2017-08-02 15:52
Still can't reproduce in fullscreen.

**Comment by rsese** [comment] 2017-08-02 21:09
I tried again in fullscreen and can't reproduce either.

**Comment by chbk** [comment] 2017-08-05 17:49
I upgraded my OS to macOS 10.12.6 and can't reproduce anymore.

**Comment by rsese** [comment] 2017-08-08 23:26
Thanks @chbk - since it's not reproducible after an OS update, we'll go ahead and close this.

**Closed by rsese** 2017-08-08 23:26 UTC
Labels: needs-reproduction
