### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 20Error: Cannot call...

### ISSUE THREAD

**Issue by auliawiguna** [atom/atom#19725] opened 2019-07-30 01:24 UTC
Steps to reproduce:

1. Open atom.app
2. And then got this one
3. It was fine 2 hrs before, shutdown my mac, turn it on, re-open atom and got this error

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 20
Error: Cannot call function 'getPosition' on missing remote object 20
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 20
Error: Cannot call function 'getPosition' on missing remote object 20
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:703888)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:704303)
    at WindowEventHandler.handleWindowResize (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285033)
    at l (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1195719)
```

### Commands

```
  2x -0:03.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.33.4 
atom-visual-studio-code-ui 2.1.0 
bootstrap-3-snippets-for-atom 2.19.0 
busy-signal 2.0.1 
docblockr 0.13.7 
file-icons 2.1.33 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-blade 0.43.1 
laravel 0.7.1 
laravelcollective-html-form-snippets 1.0.0 
linter 2.3.0 
linter-php 1.6.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-git-diff 4.3.1 
php-cs-fixer 4.1.1 
sublime-ui-dark 0.0.7 
sublimify 0.10.0 
v-bootstrap4 0.2.2 
viscode-ui 0.3.1 
```

**Comment by rsese** [comment] 2019-07-30 23:06
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

About your steps to reproduce, can you reproduce consistently or did it happen just one time?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-07-30 23:06 UTC
