### ISSUE TITLE
Uncaught TypeError: packages is not iterable

### ISSUE THREAD

**Issue by bry02g** [atom/atom#17665] opened 2018-07-11 06:15 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Ubuntu 18.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: packages is not iterable

```
At /usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:385

TypeError: packages is not iterable
    at InstallPanel.addPackageViews (/usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:385:30)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:456:26
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:68:26
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:159:22)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (/usr/share/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:65:25)
    at InstallPanel.loadFeaturedPackages (/usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:450:27)
    at new InstallPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/install-panel.js:124:16)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:247:22
    at SettingsView.getOrCreatePanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at SettingsView.showDeferredPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:416:20)
    at SettingsView.addPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:345:20)
    at SettingsView.addCorePanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:335:18)
    at SettingsView.initializePanels (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:246:18)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:122:26
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by thomasjo** [comment] 2018-07-11 09:41
Duplicate of #17658

**Closed by thomasjo** 2018-07-11 09:41 UTC
