### ISSUE TITLE
Atom Fails to Load Installed Packages in Settings

### ISSUE THREAD

**Issue by CodingAnarchy** [atom/atom#10770] opened 2016-02-11 07:29 UTC
I'm getting an issue where only three or four of my installed packages show up in the Settings/Packages pane, making it impossible to find out what is presently installed, what versions they are at and modify the settings thereof.  In the developer tools I'm seeing this output:

```
Cannot read property 'getTitle' of undefined TypeError: Cannot read property 'getTitle' of undefined
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/grammar-utils/coffee-script.coffee:14:56)
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/grammar-utils/coffee-script.coffee:3:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/grammar-utils.coffee:74:17)
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/grammar-utils.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/grammars.coffee:5:16)
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/grammars.coffee:4:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/code-context-builder.coffee:2:14)
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/code-context-builder.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/script.coffee:1:22)
    at Object.<anonymous> (/Users/vision/.atom/packages/script/lib/script.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:12)
    at PackageManager.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:55:14)
    at PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:658:63)
    at PackageCard.module.exports.PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:611:34)
    at PackageCard.module.exports.PackageCard.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:205:17)
    at PackageCard.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new PackageCard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:22:48)
    at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.createPackageCard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:337:18)
    at ListView.createView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:3:61)
    at ListView.module.exports.ListView.addView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list-view.js:50:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list-view.js:13:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at List.module.exports.List.setItems (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list.js:42:22)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:284:28
```

Atom version is 1.5.1.  Hopefully this can be resolved fairly quickly.  Thanks.

**Comment by richdean** [comment] 2016-02-11 11:52
Looks like it's a problem with the script package. Try removing it and see if that fixes the issue.

If you can't remove the package directly in Atom you can use apm to do so:

`apm remove script`

If this fixes your problem you might want to raise an issue on the script package repo:

https://github.com/rgbkrk/atom-script

**Comment by 50Wliu** [comment] 2016-02-11 14:49
HI @CodingAnarchy, this looks like a duplicate of atom/settings-view#591, so feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-11 14:49 UTC
