### ISSUE TITLE
Ubuntu SAMBA: Cannot delete files with Atom editor

### ISSUE THREAD

**Issue by blockba5her** [atom/atom#17033] opened 2018-03-27 02:40 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I store almost all of my files on an in-home VPS that I run so that I can have them up 24/7. To access these I have a samba server on my VPS setup so that I can easily access the files via Windows. Whenever I'm using the Atom editor on the samba file system it seems to not work because it cannot detect a Recycle Bin. I have to manually delete the file in File Explorer for it to work. I tried changing the `File System Watcher` settings under `Core Settings` to see if it would have an effect but it didn't solve the issue.

### Steps to Reproduce

Just try to delete a file on a Ubuntu samba server

**Expected behavior:** The file to delete like normal

**Actual behavior:** Popup message:
```
The following file couldn't be moved to the trash.
\\NETWORK\share\node\web\extensions\test.js
Is there a Recycle Bin on the drive where the files are stored?
```

**Reproduces how often:** 100% of the time, I have to delete in the Windows File Tree

### Versions

```
Windows 10 Pro

Atom    : 1.26.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0-beta0
python 3.6.4
git 2.16.0.windows.2
visual studio
```

**Comment by Arcanemagus** [comment] 2018-03-27 15:51
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/3306. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-27 15:51 UTC
