### ISSUE TITLE
[Bug] () problems in .php file

### ISSUE THREAD

**Issue by bmiwdmb** [atom/atom#7035] opened 2015-05-31 11:03 UTC
## Infomation ##
+ System: Windows 7
+ FileName: index.php

-----

### in Notepad++ ###
![Notepad++](https://i.imgur.com/Nl7pOX2.png)

### in Visual Studio Code ###
![vsc](http://i.imgur.com/e3tcCs9.png)

### in Atom Version 0.204.0 ###
: )
![Atom](https://i.imgur.com/BWM0ek9.png)
: \\)
![Atom](http://i.imgur.com/mYSQUnC.png)

**Comment by bmiwdmb** [comment] 2015-05-31 11:09
in Visual Studio Code
![vsc](http://i.imgur.com/e3tcCs9.png)

P.s. FileName: index.php

**Comment by mnquintana** [comment] 2015-05-31 14:17
Can you elaborate on what the problem is?

**Comment by alexwhitman** [comment] 2015-05-31 14:36
The bracket matching is matching the `)` in the string rather than the one closing the array.

**Comment by izuzak** [comment] 2015-05-31 15:29
Thanks for clarifying, @alexwhitman -- this looks like a duplicate of https://github.com/atom/bracket-matcher/issues/23. Let us know if we misunderstood your report, @bmiwdmb

**Closed by izuzak** 2015-05-31 15:29 UTC
Labels: more-information-needed
