### ISSUE TITLE
Atom crashes in Full screen mode( Cannot exit)

### ISSUE THREAD

**Issue by karneaud** [atom/atom#13400] opened 2016-12-06 18:08 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom would out of full screen mode and "Keep Waiting" dialog appears

### Steps to Reproduce

1. start atom from command line or .exe
2. enter full screen mode
3. close/ reopen and try exiting fullscreen mode via shortcut or menu context

**Expected behavior:**

Atom UI should exit full screen mode

**Actual behavior:** 

Atom UI refuses to exit full screen mode

### Versions

Windows:  8
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by 50Wliu** [comment] 2016-12-06 19:00
Cannot confirm on Windows 10 x64, 1.14.0-dev-d3d06fb.

**Comment by DylanJCain** [comment] 2016-12-07 00:09
Cannot confirm on Windows 7 32-bit. Atom v.1.11.1

**Comment by i2000s** [comment] 2016-12-10 08:05
Well, I have encountered this issue for a few days. I cannot see the version number, but it should be the latest one. The menu can expand and dropdown, but no response whatsoever. None of the tabs can be closed, no items on the left panel can be closed... I cannot even exit. It happened in a normal mode on my second monitor (not necessarily max-window mode). Not sure what's happening inside.

**Comment by ungb** [comment] 2016-12-13 00:00
I am unable to repro with atom 1.12.6 on Windows 10 x64.  Even with a lot of tabs open.  Does this happen when you have a certain project open or it always happens when you just open Atom and go to full screen mode and try to get out?

**Comment by i2000s** [comment] 2016-12-13 00:40
For me, I think there is a slow built-up process. I have been adding new project folders to one project, and then suddenly it crashes with a lot of tabs open. Please refer to the crash log reported on [this issue](https://github.com/atom/atom/issues/12983). I cannot catch out the root cause. Thanks.

**Comment by lee-dohm** [comment] 2016-12-23 20:44
@i2000s Can you reproduce this problem in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by i2000s** [comment] 2016-12-31 03:37
@lee-dohm Sorry, it's a bit late that I have reset atom already. In the issue I referred to earlier, there is another guy encountered this issue recently as well. I will ask him to try the safe mode. Please follow up there. Thanks!

**Comment by lee-dohm** [comment] 2017-01-05 19:18
Since we can't reproduce the problem as described here and we've got the other issue already, I'm going to close this. Thanks for all your help @i2000s :grinning:

**Closed by lee-dohm** 2017-01-05 19:18 UTC
Labels: crash, more-information-needed, needs-reproduction
