### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 266Error: Cannot cal...

### ISSUE THREAD

**Issue by leviaton** [atom/atom#20108] opened 2019-11-03 13:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 266
Error: Cannot call function 'getPosition' on missing remote object 266
    at throwRPCError (C:\JuliaPro-1.2.0-1\app-1.40.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\JuliaPro-1.2.0-1\app-1.40.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\JuliaPro-1.2.0-1\app-1.40.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At C:\JuliaPro-1.2.0-1\app-1.40.1\resources\electron.asar\renderer\api\remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 266
Error: Cannot call function 'getPosition' on missing remote object 266
    at throwRPCError (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/app/static/<embedded>:1:731570)
    at AtomEnvironment.storeWindowDimensions (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/app/static/<embedded>:1:731985)
    at WindowEventHandler.handleWindowResize (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/app/static/<embedded>:11:285420)
    at l (C:/JuliaPro-1.2.0-1/app-1.40.1/resources/app/static/<embedded>:11:1197399)
```

### Commands

```
     -0:32.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
default-language 0.3.1 
ink 0.10.12 
julia-client 0.9.4 
language-julia 0.19.1 
latex-completions 0.3.6 
project-manager 3.3.7 
tool-bar 1.1.12 
```

**Comment by rsese** [comment] 2019-11-04 04:53
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

If the error is reproducible for you, please us know the steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).  It would also be helpful to know if you can reproduce with the current stable [Atom 1.41.0 release](https://github.com/atom/atom/releases/tag/v1.41.0) which is running Electron 4.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-04 04:53 UTC
