### ISSUE TITLE
"Restart and Install Update" doesn't work as a non-administrative user under OSX

### ISSUE THREAD

**Issue by gitsnaf** [atom/atom#8671] opened 2015-09-04 13:29 UTC
I have an iMac with OSX 10.10.4 and this behaviour is reproducible. I would expect the app to ask for administrative credentials like all other apps are doing.

My MacBook where I work as an administrative user, the update procedure is working.

**Comment by adas172002** [comment] 2015-09-13 14:33
+1, I am on Atom 1.0.9

**Comment by dstack4273** [comment] 2016-04-16 16:31
The updater is still broken for me too, also use a non-admin account if that makes any difference.

**Comment by 50Wliu** [comment] 2016-06-08 19:13
This is a duplicate of #2860 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-08 19:13 UTC
Labels: auto-updater, bug, mac
