### ISSUE TITLE
atom launches with no workspace or menus after build/install

### ISSUE THREAD

**Issue by Scherer81** [atom/atom#11088] opened 2016-03-07 15:50 UTC
### Prerequisites

* [N] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [Y] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [N] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [Y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

After install a new version following guide available at https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md when trying to launch atom interface window doesn't show any workspace or menus, just a blank browser screen, even removing .atom on home directory doesn't solve (as an attempt to fix this behavior).

### Steps to Reproduce

- Follow steps to install a new version of atom referenced above

```
$ script/build
Node: v5.6.0
npm: v3.8.0
Installing build modules...
=> Took 638630ms.

Installing apm...
=> Took 134574ms.

Deleting old packages...
=> Took 388ms.

Installing modules ✓
Installing atom-dark-syntax@0.27.0 ✓
Installing atom-dark-ui@0.51.0 ✓
Installing atom-light-syntax@0.28.0 ✓
Installing atom-light-ui@0.43.0 ✓
Installing base16-tomorrow-dark-theme@1.1.0 ✓
Installing base16-tomorrow-light-theme@1.1.1 ✓
Installing one-dark-ui@1.1.9 ✓
Installing one-light-ui@1.1.9 ✓
Installing one-dark-syntax@1.2.0 ✓
Installing one-light-syntax@1.2.0 ✓
Installing solarized-dark-syntax@1.0.0 ✓
Installing solarized-light-syntax@1.0.0 ✓
Installing about@1.3.0 ✓
Installing archive-view@0.61.0 ✓
Installing autocomplete-atom-api@0.10.0 ✓
Installing autocomplete-css@0.11.0 ✓
Installing autocomplete-html@0.7.2 ✓
Installing autocomplete-plus@2.25.0 ✓
Installing autocomplete-snippets@1.10.0 ✓
Installing autoflow@0.27.0 ✓
Installing autosave@0.23.0 ✓
Installing background-tips@0.26.0 ✓
Installing bookmarks@0.38.2 ✓
Installing bracket-matcher@0.79.0 ✓
Installing command-palette@0.38.0 ✓
Installing deprecation-cop@0.54.0 ✓
Installing dev-live-reload@0.47.0 ✓
Installing encoding-selector@0.21.0 ✓
Installing exception-reporting@0.37.0 ✓
Installing find-and-replace@0.197.3 ✓
Installing fuzzy-finder@0.94.0 ✓
Installing git-diff@0.57.0 ✓
Installing go-to-line@0.30.0 ✓
Installing grammar-selector@0.48.0 ✓
Installing image-view@0.56.0 ✓
Installing incompatible-packages@0.25.0 ✓
Installing keybinding-resolver@0.33.0 ✓
Installing line-ending-selector@0.3.0 ✓
Installing link@0.31.0 ✓
Installing markdown-preview@0.157.2 ✓
Installing metrics@0.53.1 ✓
Installing notifications@0.62.1 ✓
Installing open-on-github@0.41.0 ✓
Installing package-generator@0.41.0 ✓
Installing settings-view@0.232.3 ✓
Installing snippets@1.0.1 ✓
Installing spell-check@0.65.0 ✓
Installing status-bar@0.83.0 ✓
Installing styleguide@0.45.1 ✓
Installing symbols-view@0.110.1 ✓
Installing tabs@0.91.1 ✓
Installing timecop@0.33.0 ✓
Installing tree-view@0.201.5 ✓
Installing update-package-dependencies@0.10.0 ✓
Installing welcome@0.33.0 ✓
Installing whitespace@0.32.1 ✓
Installing wrap-guide@0.38.1 ✓
Installing language-c@0.51.1 ✓
Installing language-clojure@0.19.1 ✓
Installing language-coffee-script@0.46.0 ✓
Installing language-csharp@0.11.0 ✓
Installing language-css@0.36.0 ✓
Installing language-gfm@0.84.0 ✓
Installing language-git@0.12.1 ✓
Installing language-go@0.42.0 ✓
Installing language-html@0.44.0 ✓
Installing language-hyperlink@0.16.0 ✓
Installing language-java@0.17.0 ✓
Installing language-javascript@0.110.0 ✓
Installing language-json@0.17.4 ✓
Installing language-less@0.29.0 ✓
Installing language-make@0.21.0 ✓
Installing language-mustache@0.13.0 ✓
Installing language-objective-c@0.15.1 ✓
Installing language-perl@0.32.0 ✓
Installing language-php@0.37.0 ✓
Installing language-property-list@0.8.0 ✓
Installing language-python@0.43.0 ✓
Installing language-ruby@0.68.0 ✓
Installing language-ruby-on-rails@0.25.0 ✓
Installing language-sass@0.45.0 ✓
Installing language-shellscript@0.21.0 ✓
Installing language-source@0.9.0 ✓
Installing language-sql@0.20.0 ✓
Installing language-text@0.7.0 ✓
Installing language-todo@0.27.0 ✓
Installing language-toml@0.18.0 ✓
Installing language-xml@0.34.2 ✓
Installing language-yaml@0.25.1 ✓
=> Took 1085802ms.

Deduping modules ✓
=> Took 42654ms.

Running "download-electron" task

Running "download-electron-chromedriver" task

Running "build" task

Running "babel:dist" (babel) task

Running "coffee:glob_to_multiple" (coffee) task
>> 333 files created.

Running "prebuild-less:src" (prebuild-less) task
>> 1891 files compiled, 0 files reused

Running "cson:glob_to_multiple" (cson) task
>> 172 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task
Generating parser from "node_modules/snippets/lib/snippet-body.pegjs"...
Parser "/usr/local/src/atom/out/Atom Beta/resources/app/node_modules/snippets/lib/snippet-body.js" generated in 27ms.

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task

Running "set-version" task

Running "generate-asar" task

Done, without errors.

Execution Time (2016-03-07 13:56:19 UTC)
loading tasks                      23.9s  ▇▇ 5%
download-electron               5m 16.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 66%
download-electron-chromedriver     15.6s  ▇ 3%
build                            1m 3.6s  ▇▇▇▇ 13%
coffee:glob_to_multiple             9.6s  ▇ 2%
prebuild-less:src                  33.2s  ▇▇▇ 7%
cson:glob_to_multiple                 5s  ▇ 1%
generate-asar                         7s  ▇ 1%
Total 7m 59.7s
```

- Start atom

- A new blank window (without workspace or menus) shows

**** There's no guarantee that these steps will reproduce the bug once it appears to be something about environment.

**Expected behavior:**
Open editor window with workspace and menus.

**Actual behavior:**
Open editor window with no workspace or menus just like a blank window browser.

### Versions
$ atom --version
1.6.0-beta6-532c45b

$ apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.3
git 1.9.1

**Comment by mnquintana** [comment] 2016-03-07 15:55
Sorry to hear you're running into trouble! Does Atom also have Chrome Dev Tools open when this happens? Have you tried quitting Atom completely and restarting it in safe mode? (`atom --safe`) Did you have a stable version of Atom installed before building Atom from source?

**Comment by Scherer81** [comment] 2016-03-07 16:00
@mnquintana 
Yes, Chrome Dev Tools open when start atom.
Yes, I've tried safe mode but no positive effect, same behavior repeats.
Yes, I'd a previous stable version installed before, made building from source too. 

Important to mention that it's a similar behavior as reported in #4351 but now on linux environment.

Case it helps, more information about my host is pasted below.

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.8/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)

**Comment by 50Wliu** [comment] 2016-03-07 21:22
When the dev tools open please click the red "x" with a number next to it, then paste the error here.  Thanks!

**Comment by Scherer81** [comment] 2016-03-08 10:36
Hi, @50Wliu 
As requested, messages from console pasted below.

Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/local/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:15:12)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-provider.js:8:19)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-provider.js:83:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    handleSetupError @ index.js:62

Line referenced above has this code.

...
56  function handleSetupError (error) {
57    var currentWindow = require('remote').getCurrentWindow()
58    currentWindow.setSize(800, 600)
59    currentWindow.center()
60    currentWindow.show()
61    currentWindow.openDevTools()
62    console.error(error.stack || error)
63  }
...

**Comment by 50Wliu** [comment] 2016-03-08 15:12
Thanks for the update @Scherer81!  This looks like a duplicate of #10819 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-08 15:12 UTC
Labels: more-information-needed
