### ISSUE TITLE
Updates failing in Atom 1.0

### ISSUE THREAD

**Issue by frankhale** [atom/atom#7415] opened 2015-06-25 17:14 UTC
Just updated to Atom 1.0 and it tells me there are updates but it errors out when checking for updates. Here is a screenshot:

![atom-1 0-updates-failing](https://cloud.githubusercontent.com/assets/190154/8360648/0d126b00-1b3c-11e5-973f-22dd459a4470.png)

**Comment by sbromberger** [comment] 2015-06-25 17:14
Same issue here.

**Comment by DavidAwad** [comment] 2015-06-25 17:30
+1 also got it. 

```HTML
Fetching outdated packages and themes failed.Hide output…
Request for package information failed: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

**Comment by inlikealion** [comment] 2015-06-25 17:38
Same here on OS X 10.10.3.
```html
Fetching outdated packages and themes failed.Hide output…
Request for package information failed: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

**Comment by sjaakvandenberg** [comment] 2015-06-25 18:11
Same here on `Linux 4.0.5-1-ARCH x86_64`

**Comment by PGPereira** [comment] 2015-06-25 18:17
Same here on 'Linux 4.0.6-1-ck x86-64'

**Comment by karai17** [comment] 2015-06-25 18:29
When I try to use the Windows installer, it errors out without a message. When I try to upgrade within Atom, it doesn't seem to work, it just lets me press the "Restart and update" button over and over again.

**Comment by robobenklein** [comment] 2015-06-25 18:36
Confirmed Ubuntu 15.04, I'm thinking this may not be a bug with Atom, but maybe a problem with the package servers.

**Comment by thomasjo** [comment] 2015-06-25 18:48
This is indeed **not** a bug in Atom. This is a backend problem. The package API seems to be struggling with the load right now.

I'm thinking we really should show a better error message for this scenario.

/cc @thedaniel

**Comment by thomasjo** [comment] 2015-06-25 18:48
Since this is not a bug in Atom and the team is aware of the problems, I'm closing this.

**Closed by thomasjo** 2015-06-25 18:48 UTC

**Comment by thedaniel** [comment] 2015-06-25 20:12
> I'm thinking we really should show a better error message for this scenario.

This is very true - there are a few related issues on settings-view that we could knock out by making this message better there.
