### ISSUE TITLE
CTRL+R is not accurate in PHP

### ISSUE THREAD

**Issue by ChristianGrech** [atom/atom#10476] opened 2016-01-18 11:04 UTC
When using CTRL+R in PHP it loads both methods and attributes (both attributes in method and global). Using atom 1.4 on windows.

**Comment by mnquintana** [comment] 2016-01-18 19:33
Thanks for the report! :smile: This looks like a duplicate of https://github.com/atom/language-php/issues/118 – feel free to subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) for a guide on where to post issues, including searching for duplicates.

**Closed by mnquintana** 2016-01-18 19:33 UTC
