### ISSUE TITLE
Renaming a file no longer renames but copies the file to a new file with a new name.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#7299] opened 2015-06-16 15:06 UTC
Renaming a file inside of Atom (using the sidebar -- tree view -- and if this is a direct problem there I will move this ticket there) no longer renames the actual file but copies it to a new file with a new name, leaving the file file to be manually deleted. Is this expected behavior?

**Comment by envygeeks** [comment] 2015-06-16 15:07
jordon@envygeeks:beta (master * u=) ~> atom --version
0.209.0-d965eb7

**Comment by mnquintana** [comment] 2015-06-16 15:19
Can you reproduce this in safe mode? (`atom --safe`)

**Comment by envygeeks** [comment] 2015-06-16 20:23
Yes, and it seems to only happen if he file starts with a number oddly...

**Comment by maxbrunsfeld** [comment] 2015-06-16 21:35
I can't reproduce this yet, even w/ a file that starts with a number.

@envygeeks An issue was recently fixed in the autosave package that seems like it might relate to this: https://github.com/atom/autosave/pull/35. It is on master of atom. Could you rebuild Atom from master and see if this still happens to you?

**Comment by yohanesu** [comment] 2015-06-18 02:45
Same for me. Rename has some function as Duplicate.
Atom version 0.205.0.
Filename does not matter, still duplicates instead of rename.

**Comment by mark-hahn** [comment] 2015-06-18 04:09
I may be speaking out of my hat, but it seems to be a symptom of a more general problem of recreating things it finds missing.  Today I renamed a folder from outside Atom, which worked, but Atom recreated the folder.  So it ended up being just like the symptom of renaming a file.

**Comment by envygeeks** [comment] 2015-06-18 04:12
That seems to line up with what @maxbrunsfeld implied this could be, have you tried it with that update @mark-hahn I haven't bothered to update yet because I've been super busy with other stuff but that seems like exactly it.

**Comment by yohanesu** [comment] 2015-06-18 04:14
@mark-hahn  Exactly! Today I removed two files from shell that belonged to an open atom project. Atom recreated them later...

**Comment by maxbrunsfeld** [comment] 2015-06-18 04:52
The bug I was talking about is fixed in Atom 0.210. Could you folks upgrade and report whether the problem is still happening?

**Comment by yohanesu** [comment] 2015-06-18 05:27
Upgraded to 0.211.0-309410f. Rename and duplicate works fine now. However delete does not (maybe other issue - file not being deleted (arch linux)).

**Comment by envygeeks** [comment] 2015-06-18 14:22
Works for me on 0.210.0

**Comment by mnquintana** [comment] 2015-06-18 14:23
Thanks for the update! This is a duplicate of https://github.com/atom/autosave/issues/9 and resolved in https://github.com/atom/autosave/pull/35

**Closed by mnquintana** 2015-06-18 14:23 UTC
Labels: more-information-needed, needs-reproduction
