### ISSUE TITLE
Dock toggle rendering issue

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#14915] opened 2017-06-28 16:51 UTC
### Prerequisites

_Note: Unable to reproduce in safe mode._

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Dock toggles will sometimes develop a rendering glitch, causing a bar to appear around the button.

### Steps to Reproduce (_Updated_)

1. Install the `docks-test` package found here: [docks-test.zip](https://github.com/atom/atom/files/1109683/docks-test.zip)
2. Install `atom-material-ui`. Tested with v2.0.4.
3. Open a file.

**Expected behavior:**

No graphical bugs with the Dock item.

**Actual behavior:**

When the "flow in" animation for the Dock toggle finishes a rectangular shaped region of the screen as high as the button but much wider will appear colored in the `@app-background-color` (I think), sometimes it will have content from the status bar showing in the bar. This status bar content is _not_ from the area "under" the bar, so it's not something that is getting translated up with the button.

"Normal" blank bar:
![image](https://user-images.githubusercontent.com/427137/27649520-e67c8668-5be6-11e7-896d-38285a96c1b9.png)

Status bar content:
![image](https://user-images.githubusercontent.com/427137/27649153-d0a616a2-5be5-11e7-9b60-f0499731681a.png)

GIF:
![2017-06-28_09-48-51](https://user-images.githubusercontent.com/427137/27649602-1607e576-5be7-11e7-9487-c512ba257bf7.gif)

Note that with the updated steps to reproduce the behavior is actually worse than shown in the screenshots as the window starts out with a glitched rendering bar:
![image](https://user-images.githubusercontent.com/427137/27652328-239b7a78-5bf0-11e7-83ac-a714a4f3488f.png)

There is actually a line number hidden behind the bar as well, as can be seen (briefly) in this GIF:
![2017-06-28_10-55-14](https://user-images.githubusercontent.com/427137/27652371-4b9adafa-5bf0-11e7-9978-912ad8265ab2.gif)

**Reproduces how often:**

Almost all windows seem to eventually show this behavior, but I can't determine a reliable way to reproduce this.

- I can't seem to replicate in safe mode, or with a stock theme (One Dark).
- I use `atom-material-ui` with One Dark Syntax.
- ~~This _might_ be dependent on `linter-ui-default`,~~ but it may just be that that is the only bottom Dock item that I usually have running.
- I only ever see a brief flash of the right side Dock toggle showing this when Atom is loading, once loaded I don't see it from that toggle.

### Versions

 I've seen this since at least v1.18.0 betas, possibly since v1.17.0 betas.

Currently seeing this in:
```
Atom    : 1.19.0-beta2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

Related issues:
https://github.com/steelbrain/linter-ui-default/issues/344
https://github.com/steelbrain/linter/issues/1501

<details>
<summary>Here is a list of installed packages</summary>

```
atom-autocomplete-php@0.25.6
atom-beautify@0.30.3
atom-jade@0.3.0
atom-material-syntax@1.0.6
atom-material-syntax-dark@1.0.0
atom-material-syntax-light@0.4.6
atom-material-ui@2.0.4
atom-typescript@11.0.4
autocomplete-lua@0.8.2
autocomplete-python@1.9.1
busy-signal@1.4.3
docblockr@0.10.5
editorconfig@2.2.2
file-watcher@1.1.0
fizzy@0.21.0
flow-ide@1.5.0
highlight-selected@0.13.1
intentions@1.1.2
language-ansible@0.2.1
language-babel@2.66.0
language-chef@0.10.0
language-cjson@0.0.1
language-docker@1.1.8
language-elixir@0.19.0
language-erlang@3.2.0
language-fortran@2.1.0
language-gettext@0.6.1
language-glsl@2.0.1
language-haml@0.24.6
language-haskell@1.12.1
language-icinga2@0.3.0
language-ini@1.19.0
language-jade@0.7.2
language-jolie@0.5.0
language-kotlin@0.5.0
language-lua@0.9.11
language-moonscript@1.7.1
language-postcss@1.3.1
language-powershell@4.0.0
language-puppet@0.22.0
language-r@0.4.1
language-reg@0.0.0
language-rust@0.4.10
language-swift@0.5.0
language-terraform@0.8.1
language-vue@0.23.0
linter@2.2.0
linter-alex@4.0.0
linter-clang@4.1.1
linter-coffeelint@1.2.1
linter-csslint@1.3.4
linter-eslint@8.2.1
linter-flake8@2.2.1
linter-htmlhint@1.3.3
linter-js-standard@3.9.1
linter-js-yaml@1.2.7
linter-jshint@3.1.4
linter-jsonlint@1.3.0
linter-markdown@4.0.1
linter-perl@0.8.0
linter-perlcritic@1.4.2
linter-php@1.3.2
linter-phpcs@1.6.7
linter-phpmd@1.5.3
linter-proselint@3.2.1
linter-pylama@0.9.3
linter-pylint@2.1.0
linter-rails-best-practices@0.2.2
linter-reek@2.2.1
linter-rubocop@2.1.1
linter-ruby@1.2.5
linter-stylelint@3.10.0
linter-tidy@2.3.1
linter-ui-default@1.6.2
mapfile-grammar@0.1.0
merge-conflicts@1.4.5
minimap@4.28.2
minimap-git-diff@4.3.1
minimap-highlight-selected@4.6.1
minimap-linter@2.0.0
minimap-selection@4.4.0
monokai@0.24.0
nord-atom-syntax@0.9.1
nord-atom-ui@0.11.0
pigments@0.39.1
sequential-number@0.5.0
seti-syntax@1.1.3
seti-ui@1.9.0
sort-lines@0.14.0
Stylus@3.1.1
svn@0.0.13
tab-control@0.6.10
toggle-quotes@1.0.1
trailing-spaces@0.4.0
```
</details>

**Comment by Arcanemagus** [comment] 2017-06-28 16:52
Actually, re-reading some of those issues it seems others are seeing this without `atom-material-ui`.

**Comment by Arcanemagus** [comment] 2017-06-28 17:56
Created a minimal reproduction case, updated the above with it.

**Comment by Arcanemagus** [comment] 2017-06-28 18:01
After a bit of further testing, this is dependent on the `activatePane: false` option being passed to `atom.workspace.open`. If the Dock item is visible by default this bug doesn't reproduce, but if it's hidden this shows up.

**Comment by Arcanemagus** [comment] 2017-06-29 20:35
@rsese Does the minimal package I posted in the issue reproduce this for you?

**Comment by rsese** [comment] 2017-06-29 21:30
Haven't had a chance yet but I'll try in the next day or so - thanks so much for creating a test package :bow:

**Comment by Arcanemagus** [comment] 2017-06-29 21:44
If it makes a difference, but myself and the user who also reported their OS are on Windows.

**Comment by rsese** [comment] 2017-06-30 22:44
I was able to try things out just now and found that I can't reproduce in macOS 10.12.5 with Atom 1.19.0-beta1 and I couldn't reproduce at first on Windows 10 with 1.19.0-beta2 and 1.18.0.

Then I realized I hadn't updated `atom-material-ui` in a long while (it was at 1.3.9) so after updating to 2.0.4, I saw the behavior you described in your GIF but not the screenshots.

Playing around a bit more, I could also reproduce with Atom Light and Dark as well (though not the One themes like you noted @Arcanemagus) - do you see the same behavior with Atom Light and Dark @Arcanemagus?

**Comment by Arcanemagus** [comment] 2017-07-03 16:59
@rsese Here's what I see:

Broken:

UI | Syntax
-- | ------
Atom Dark | Atom Dark
Atom Dark | Atom Light
Atom Dark | Base16 Tomorrow Dark
Atom Dark | Base16 Tomorrow Light
Atom Dark | One Dark
Atom Dark | One Light
Atom Dark | Solarized Dark
Atom Dark | Solarized Light
Atom Light | _Same as Atom Dark_
Atom Material | _Same as Atom Dark_

Working:

UI | Syntax
-- | ------
One Dark | Atom Dark
One Dark | Atom Light
One Dark | Base16 Tomorrow Dark
One Dark | Base16 Tomorrow Light
One Dark | One Dark
One Dark | One Light
One Dark | Solarized Dark
One Dark | Solarized Light
One Light | _Same as One Dark_

**Comment by Arcanemagus** [comment] 2017-07-03 19:09
Just to document it, managed to catch it happening on the sidebar:
![image](https://user-images.githubusercontent.com/427137/27805236-7444bed4-5fe8-11e7-84bf-bbf7c85ab355.png)

The GitHub package is loaded there, and would have initialized collapsed here.

**Comment by rsese** [comment] 2017-07-06 06:32
Thanks for confirming and for that table @Arcanemagus :v:

**Comment by simurai** [comment] 2017-07-06 12:08
I can't reproduce it, but looks like some GPU texture rendering issue. Does it still happen if you add the following to your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file:

```less
.atom-dock-toggle-button {
  backface-visibility: hidden;
}
```

**Comment by Arcanemagus** [comment] 2017-07-06 15:54
@simurai Confirmed that that seems to cause this issue to stop reproducing!

The computer I normally see this on has the following in it:
* NVS 310, driver 21.21.13.6959
* NVS 315, driver 21.21.13.6959

_Newer drivers cause major instability, haven't bothered to track down why as this is a workstation not a gaming machine._ 😛

**Comment by Arcanemagus** [comment] 2017-07-10 16:15
Is this something that needs to be fixed in Atom Core? Or worked around in all themes?

Is there any further testing I can do to help narrow this down further?

**Comment by simurai** [comment] 2017-07-11 03:23
> Is this something that needs to be fixed in Atom Core?

Yeah, I think we should fix it in Core since it might affects other community themes too. Hard to say how many, though.

@Arcanemagus Do you mind trying a few more options? It's less hacky to use the more official `will-change` or the new `contain` property.

```less
// option 1
.atom-dock-toggle-button {
  will-change: contents;
}

// option 2
.atom-dock-toggle-button {
  will-change: transform;
}

// option 3
.atom-dock-toggle-button {
  contain: size layout;
}

// option 4
.atom-dock-toggle-button-inner {
  will-change: transform;
}

// option 5
.atom-dock-toggle-button-inner {
  contain: size layout;
}
```

Probably only `option 2` will work.

**Comment by Arcanemagus** [comment] 2017-07-11 16:18
* Option 1: Changes the behavior... but almost makes it worse as the button now "ghosts"
  ![image](https://user-images.githubusercontent.com/427137/28078296-3896fcbc-6619-11e7-917f-f1d4c8f179ba.png)
  ![image](https://user-images.githubusercontent.com/427137/28078306-4426e3da-6619-11e7-8e83-360db4b50d2a.png)
  In addition, the "hidden line" effect that is normally temporary when the transition is happening is permanent with this option.

* Option 2: Appears to work!
* Option 3: No change from broken as far as I can tell?
* Option 4: Appears to work!
* Option 5: No change from broken as far as I can tell?

Looks like your guesses were spot on @simurai 😉.

**Comment by HotelCalifornia** [comment] 2017-07-24 16:27
I've just started having this issue on macOS now, I don't think it was happening last week or before.

![there it is](https://user-images.githubusercontent.com/6646541/28533121-9a99f124-7061-11e7-8703-1b3d61dccb10.png)

On further inspection, the reason it's only happening now is probably because this is the first time in  a while that I've manually opened Atom (as opposed to having the OS resume it on startup). Once I opened the dock and closed both of the git tabs in it, I am no longer seeing the black bars (though I'm also not seeing the dock tab at all).

Running the `GitHub: Toggle Git Tab` command puts the dock back without showing the black bars.

Also might be worth noting that when I was seeing the black bars, nothing showed up in the git tabs.

Current UI theme+syntax is `Atom Material` + `Base16 Tomorrow Dark` (both noted in the table above)
<details>
<summary>Here's a list of installed packages, if that helps</summary>
<pre>
angularjs@0.4.0
atom-material-syntax@1.0.6
atom-material-ui@2.0.4
atom-terminal-tab@0.2.2
atom-ternjs@0.18.3
atom-wrap-in-tag@0.6.0
autoclose-html@0.23.0
busy-signal@1.4.3
dracula-ui@0.6.0
emmet@2.4.3
file-icons@2.1.9
highlight-selected@0.13.1
indent-guide-improved@1.4.12
intentions@1.1.2
less-than-slash@0.17.0
linter@2.2.0
linter-jshint@3.1.5
linter-ui-default@1.6.3
linter-ui-plus@0.3.2
minimap-find-and-replace@4.5.2
minimap-git-diff@4.3.1
minimap-highlight-selected@4.6.1
minimap-linter@2.0.2
minimap-pigments@0.2.2
minimap-plus@4.29.2
pigments@0.39.1
pure-syntax@0.3.0
rainbow-delimiters@1.3.0
</pre>
</details>

**Comment by huxingyi** [comment] 2017-08-06 10:52
### Description
If the width of .atom-dock-mask never near to or greater than the .atom-dock-content-wrapper, there would be a black bar under the button .atom-dock-toggle-button.
Once you toggle the button, the symptom just disappear, or you can manually change the width of .atom-dock-mask euqal to the width of .atom-dock-content-wrapper from the `Viewer > Developer > Toggle Developer Tools`, the symptom also not show again.

### Steps to Reproduce
1. Run atom normally.
2. Boot another atom window from menu: `File > New Window` (This step make sure you open a window with only one tab opened)
3. On the newly opened window, move your cursor to the right edge of the window frame to make the dock toggle button show, then there will be a black bar under the button.

**Expected behavior:**  
Toggle button without weird black background.

**Actual behavior:**  
Toggle button with a weird black bar undernearth.

**Reproduces how often:**    
100%

### Versions
1.18.0 ia32 Windows 7 SP 1
(64bit windows also has the same issue)

### Additional Information
I fixed it by force the wrapper element follow the size of mask:  
https://github.com/huxingyi/atom/commit/4e76eb682eaa41feaaac4125e8ea401842a41fe2

**Comment by superjoefly** [comment] 2017-08-20 06:50
Just wanted to mention that this worked for me using atom-material-ui 2.0.4

.atom-dock-toggle-button {
  backface-visibility: hidden;
}

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0


Thanks for the fix :-)

**Comment by garretwilson** [comment] 2017-08-27 16:05
This is getting in the way with my work, as every time I open Atom and try to do a search, I have to go through a ritual of opening the bottom dock and closing it again just so I can see my replacement text. (See #14594.)

Is there a way I can just disable this new docking mechanism until this is fixed?

**Comment by Ben3eeE** [comment] 2017-08-27 20:23
@garretwilson You can try the CSS solution in https://github.com/atom/atom/pull/14998.

**Comment by wbkoetsier** [comment] 2017-08-28 12:37
I have this problem as well, see this closed issue #15432 (as referenced above by 50Wliu) for my details.

Adding

```
.atom-dock-toggle-button {
  backface-visibility: hidden;
}
```

To my `styles.less` seems to have fixed it.

**Comment by Arcanemagus** [comment] 2017-08-28 15:46
@wbkoetsier and @superjoefly can you please try the method in https://github.com/atom/atom/pull/14998#issuecomment-317490455 and see if that works? That is the currently proposed solution but it needs testing by people affected by this issue.

**Comment by HotelCalifornia** [comment] 2017-08-28 18:25
I confirmed in #14998 that it worked on my macbook, so here I am confirming that it works on my windows machine as well

**Comment by Arcanemagus** [comment] 2017-08-28 19:17
@HotelCalifornia the `backface-visibility` trick **isn't** the proposed fix, which is why I said they should try the one in the PR:

```css
.atom-dock-toggle-button-inner {
  will-change: transform;
}
```

**Comment by HotelCalifornia** [comment] 2017-08-28 21:27
@Arcanemagus would you believe that that was what I put in my stylesheet? I must have gotten confused when editing my comment above

**Comment by simurai** [comment] 2017-08-29 00:36
👍  Thanks, if `will-change: transform;` works too, we should use that. Slightly less of a hack. Will change it in #14998.

**Closed** 2017-08-29 01:01 UTC
Labels: bug, triaged

**Comment by wbkoetsier** [comment] 2017-08-29 14:40
For me, the proposed fix works.
Windows 10 x64, atom 1.19.3

I removed

```
.atom-dock-toggle-button {
  backface-visibility: hidden;
}
```

from my `styles.less` and added

```
.atom-dock-toggle-button-inner {
  will-change: transform;
}
```

and the problem is gone.

**Comment by superjoefly** [comment] 2017-09-06 08:06
Proposed change is working for me as well.
Strangely, in near empty files, I can still see a black bar running across the bottom of the gutter.
I'm not sure this is related to the dock toggle though.
Of course most of my files are not 'near empty' so it's not really a big deal...:-)
