### ISSUE TITLE
Curly brace marked even inside comment

### ISSUE THREAD

**Issue by tonmoy18** [atom/atom#9311] opened 2015-10-27 21:12 UTC
In C/C++ or java like languages, even if the starting curly brace is commented, it is selected when the cursor is taken to the ending curly brace.
![image](https://cloud.githubusercontent.com/assets/11350803/10772753/ed1529c0-7ccd-11e5-9679-f7fbdbdfa453.png)

**Comment by 50Wliu** [comment] 2015-10-27 23:20
Duplicate of atom/bracket-matcher#78, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-27 23:20 UTC
