### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by styx** [atom/atom#12108] opened 2016-07-06 09:02 UTC
[Enter steps to reproduce below:]

1. Unknown
2. Happens from time to time, not often.
3. Feel free to close this issue if not enough info

### Stack

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:178

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
  at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)
  at undefined.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:112:18)
  at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:631:29)
  at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:665:36)
  at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:182:35)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61

```

### Commands

```
  2x -0:23 vim-mode-plus:move-to-next-word (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:22.4.0 vim-mode-plus:move-left (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:21.9.0 vim-mode-plus:insert-after (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:21.8.0 core:backspace (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:19.7.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:19.5.0 core:save (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  9x -0:11.2.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  4x -0:10.4.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:09.6.0 vim-mode-plus:insert-after (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:09.4.0 core:backspace (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:09.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
  7x -0:08.8.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:08.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -0:06.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:05.2.0 core:save (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  4x -0:04.8.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "atom-neovim",
      "atom-neovim",
      "vim-mode",
      "ex-mode",
      "script",
      "welcome",
      "tree-view",
      "minimap",
      "tool-bar"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "atom-elixir"
    ],
    "projectHome": "/Users/styx/ProjectX",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 110,
    "scrollPastEnd": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.9 (active)
atom-elixir, v0.2.1 (active)
atom-keyboard-macros-vim, v0.1.4 (inactive)
atom-typescript, v9.0.0 (active)
autoclose-html, v0.23.0 (active)
clipboard-plus, v0.5.1 (active)
egghead-react-snippets, v1.2.1 (active)
es6-javascript, v1.0.0 (inactive)
file-icons, v1.7.16 (active)
git-plus, v5.16.2 (inactive)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
jumpy, v3.0.3 (inactive)
keyboard-localization, v1.4.18 (active)
language-babel, v2.30.1 (active)
language-elixir, v0.14.0 (active)
language-ini, v1.16.0 (active)
language-ocaml, v1.1.2 (active)
language-thrift, v1.0.2 (active)
last-cursor-position, v0.9.0 (active)
linter, v1.11.14 (active)
merge-conflicts, v1.4.4 (active)
nuclide, v0.148.0 (active)
open-git-modified-files, v0.2.3 (inactive)
pigments, v0.31.0 (active)
react-native-snippets, v0.3.0 (active)
sort-lines, v0.14.0 (inactive)
terminal-plus, v0.14.5 (active)
tool-bar, v1.0.0 (inactive)
vim-mode-clipboard-plus, v0.2.0 (active)
vim-mode-plus, v0.46.0 (active)
vim-mode-plus-ex-mode, v0.4.0 (inactive)
vim-mode-plus-move-selected-text, v0.6.0 (active)
vim-mode-plus-subword-movement, v0.2.2 (active)
you-complete-me, v0.7.8 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (active)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2016-07-06 09:14
Duplicate of #11692?

**Closed** 2016-07-06 09:27 UTC
