### ISSUE TITLE
UI bug in open file

### ISSUE THREAD

**Issue by havthgem** [atom/atom#9949] opened 2015-12-05 03:33 UTC
When i open file, at window left-bottom, should not appear "Hide extension".
Platform is Mac OS X.
Atom version is 1.2.4.

<img width="134" alt="screen shot 2015-12-03 at 21 45 24" src="https://cloud.githubusercontent.com/assets/11625453/11605784/29855720-9b43-11e5-942f-f87821966eb3.png">

**Comment by mnquintana** [comment] 2016-12-30 16:50
Can't reproduce this with Atom 1.14.0-dev-5669246 and macOS 10.12.2, so I'm going to close this out. If you're still running into this with the latest version of Atom off `master` then feel free to comment and I'll reopen! 😄

**Closed by mnquintana** 2016-12-30 16:50 UTC
Labels: bug, electron, mac
