### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by annalaura** [atom/atom#5123] opened 2015-01-17 16:33 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.168.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:355

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:355:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:332:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:286:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:485:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:412:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
 62x -5:43.1 core:backspace (atom-text-editor.editor)
     -3:18.6 core:save (atom-text-editor.editor)
     -3:02.7 find-and-replace:select-next (atom-text-editor.editor)
     -3:01.1 core:move-to-bottom (atom-text-editor.editor)
     -2:59.3 core:move-to-top (atom-text-editor.editor)
  2x -2:49.2 core:move-down (atom-text-editor.editor)
 11x -2:47.5 core:move-right (atom-text-editor.editor)
     -2:39.9 find-and-replace:select-next (atom-text-editor.editor)
     -2:37.9 core:move-to-bottom (atom-text-editor.editor)
  7x -2:19.2 core:backspace (atom-text-editor.editor)
  9x -0:36.7 find-and-replace:select-next (atom-text-editor.editor)
     -0:29.1 core:backspace (atom-text-editor.editor)
     -0:12.7 core:copy (atom-text-editor.editor)
     -0:07.8 editor:newline (atom-text-editor.editor)
     -0:06.4 core:paste (atom-text-editor.editor)
     -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "editor": {
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
pdf-view, v0.14.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-01-17 16:42
Duplicate of #307-please subscribe there for updates.
Also please update your Atom version to experience better error handling for this.

**Closed by 50Wliu** 2015-01-17 16:42 UTC
