### ISSUE TITLE
First dead key not working in editor

### ISSUE THREAD

**Issue by villermen** [atom/atom#13263] opened 2016-11-18 13:35 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The first dead key used in the editor will ignore its first keystroke.

### Steps to Reproduce

1. Use a fresh install of Atom
2. Set Windows' keyboard mode to United States-International (preferably while using a keyboard with the same layout)
3. <kbd>Ctrl</kbd> + <kbd>N</kbd> to get a new file.
4. <kbd>Shift</kbd> + <kbd>"</kbd> then <kbd>Space</kbd>

**Expected behavior:**

A double quotation mark character `"` should be inserted.

**Actual behavior:**

A space character ` ` was inserted. When repeating step 4 after this a double quotation mark character is inserted as expected. This issue will not occur again in the same window unless it is reloaded or Atom is restarted.

### Versions

- Atom 1.12.4
- Electron 1.3.9
- Chrome 52.0.2743.82
- Node 6.5.0
- Windows 7 Enterprise SP1 x64
- Windows 10 (1611?) x64

**Comment by Ben3eeE** [comment] 2016-11-18 13:49
Can reproduce using `Atom 1.14.0-dev-96a4e44 (Electron 1.4 branch)`. Windows 7 x64.

1. Reload Atom
1. Open an new TextEditor unless one was opened already
1. Press a dead key on my Swedish keyboard layout and then space
1. Expected: dead key to be typed. Actual: Space is typed

For all subsequent tries the dead key works as expected. For me this only reproduces if the first key typed is a dead key. If I enter text before trying to reproduce this it works as expected.

**Comment by villermen** [comment] 2016-11-18 14:05
> @Ben3eeE: For all subsequent tries the dead key works as expected. For me this only reproduces if the first key typed is a dead key. If I enter text before trying to reproduce this it works as expected.

I have checked again if this also happened in my setup. This is *not* the case. I can type anything as long as it does not contain dead keys, and the first dead key will faulter. This might be a slight difference between branches then.

**Comment by 50Wliu** [comment] 2016-11-18 22:46
I can confirm @villermen's observation that the first dead will falter even if other text is entered beforehand.

**Comment by nathansobo** [comment] 2016-11-20 23:06
It looks like this is caused by yet another annoying shortcoming of Windows APIs. Calling `ToUnicodeEx` to build up a keymap is clobbering the state of the Windows keyboard buffer. It may be impossible to determine the key cap for dead keys on Windows without causing this problem.

**Comment by nathansobo** [comment] 2016-11-20 23:20
So, the trade off we're faced with is as follows:

I can eagerly construct the keymap on Windows when Atom is first loaded, thus avoiding interference with dead keys. However, if you switch keyboard layouts during an Atom session and the *first* key you type after doing so is dead, it won't work properly.

I can disable bindings for dead keys entirely.

I'm leaning toward disabling bindings for dead keys entirely because it's the only way we can have 100% consistent behavior on these layouts. Users that didn't like this could implement custom keystroke resolvers that resolved keys based on the `KeyboardEvent.code` property of the event. It's just hard to bake-in something that will work with every layout without consulting the OS, and in this case consulting the OS for these keys creates this bug.

**Comment by nathansobo** [comment] 2016-11-21 00:45
Closed via aa2c0d52e2c552698e8573fd5e07d9dd9a639e1e.

**Closed by nathansobo** 2016-11-21 00:45 UTC
Labels: bug
