### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by chiraggada2911** [atom/atom#18783] opened 2019-02-04 02:24 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Hp Folio\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1103242)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1098948)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:89306)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:69977)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:92354)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-formatter-jsbeautify 1.1.2 
git-plus 8.4.2 
terminal-tab 0.5.7 
```

**Comment by artuc** [comment] 2019-02-04 19:12
Same is happening for a couple days:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at DisplayLayer.updateSpatialIndex (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:93788)
    at DisplayLayer.populateSpatialIndexIfNeeded (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:94933)
    at DisplayLayer.doBackgroundWork (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:81207)
    at TextEditor.doBackgroundWork (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:641)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
language-blade 0.41.4 
language-vue 0.23.1 
laravel-docs 1.0.3 
linter-python-pep8 0.2.0 
nuclide 0.288.0 
python-autopep8 0.1.3 
python-debugger 0.2.0 
```

**Comment by rsese** [comment] 2019-02-05 02:52
Thanks for the report @chiraggada2911!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/18739 so you can subscribe there for updates if you'd like.  If you have steps to reproduce, please let us know in https://github.com/atom/atom/issues/18739.

@nateGeorge I'm unable to reproduce with steps you mentioned, I'm assuming that you can no longer reproduce after you've closed all files for that particular project you were working on?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-05 02:52 UTC

**Comment by nateGeorge** [comment] 2019-02-06 21:22
@rsese 
Yes, it seemed to be something weird with that one project or my computer state at the time.  Doesn't seem to be happening any more.
