### ISSUE TITLE
Can Atom do automatic closing of tags?

### ISSUE THREAD

**Issue by jianlin** [atom/atom#10487] opened 2016-01-19 00:57 UTC
Either when you type 

    <script>

and then it will immediately become 

    <script></script>

or the other way is, if you have a `<script>`  that is not yet closed yet, and you type

    </

and it will automatically make it `</script>` for you, because it will help you find the closing tag and enter for you.  Adobe Brackets can do this quite well.

**Comment by captainmoha** [comment] 2016-01-19 01:02
I think you will find [Emmet](http://emmet.io/) very useful. It makes writing HTML/CSS a lot faster. You can add it as a plugin for Atom.

**Comment by mnquintana** [comment] 2016-01-19 01:41
This looks like a duplicate of https://github.com/atom/atom/issues/7108 – take a look at https://github.com/atom/atom/issues/7108#issuecomment-109299586 for our recommendation on that issue.

**Closed by mnquintana** 2016-01-19 01:41 UTC
