### ISSUE TITLE
Render artifact in the tree view. 

### ISSUE THREAD

**Issue by javajosh** [atom/atom#5248] opened 2015-01-25 01:10 UTC
![graphical issue](https://cloud.githubusercontent.com/assets/18854/5889758/9862095e-a3eb-11e4-8ce3-9dae4e61bc69.gif)
So as you can see, there are some double printing artifacts here. I didn't see them happen, but noticed them after switching to another application. I'm running a recent OSX (10.10.1) and just installed Atom today from binary (Version 0.175.0 (0.175.0)). 

Pretty cool editor; I look forward to using it.

**Comment by 50Wliu** [comment] 2015-01-25 02:06
Duplicate of #4924.

**Closed by 50Wliu** 2015-01-25 02:06 UTC
