### ISSUE TITLE
Uncaught Error: Setting active pane that is not present in pane container

### ISSUE THREAD

**Issue by HIceFire** [atom/atom#15896] opened 2017-10-15 10:15 UTC
[Enter steps to reproduce:]

1. install package "file-icons"
2. click "Disable" repeatedly

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Setting active pane that is not present in pane container

```
At /private/var/folders/pz/thsj7p6s5tv6qf0drclp6t440000gn/T/AppTranslocation/275A3E24-7D43-4D2A-BD29-0E4994720364/d/Atom.app/Contents/Resources/app/src/pane-container.js:257

Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (/private/var/folders/pz/thsj7p6s5tv6qf0drclp6t440000gn/T/AppTranslocation/275A3E24-7D43-4D2A-BD29-0E4994720364/d/Atom.app/Contents/Resources/app/src/pane-container.js:257:21)
    at Pane.module.exports.Pane.activate (/private/var/folders/pz/thsj7p6s5tv6qf0drclp6t440000gn/T/AppTranslocation/275A3E24-7D43-4D2A-BD29-0E4994720364/d/Atom.app/Contents/Resources/app/src/pane.js:925:20)
    at Pane.module.exports.Pane.focus (/private/var/folders/pz/thsj7p6s5tv6qf0drclp6t440000gn/T/AppTranslocation/275A3E24-7D43-4D2A-BD29-0E4994720364/d/Atom.app/Contents/Resources/app/src/pane.js:290:25)
    at /app.asar/src/pane-element.js:51:25)
```

### Commands

```
     -1:54.4.0 tree-view:toggle (input.hidden-input)
     -1:54.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:52.3.0 command-palette:toggle (div.tool-panel.tree-view)
     -1:47.2.0 application:add-project-folder (div.tool-panel.tree-view)
     -1:43.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:08.1.0 application:add-project-folder (atom-pane.pane)
     -0:49 settings-view:open (atom-pane.pane)
  2x -0:20.7.0 tree-view:toggle (button.btn.icon.enablement.icon-playback-pause)
```

### Non-Core Packages

```
file-icons 2.1.13 
language-babel 2.75.1 
```

**Comment by rsese** [comment] 2017-10-16 19:34
Thanks for the report!

Based on the stack trace, it looks like this is a duplicate of https://github.com/atom/atom/issues/14716 and you've found another way to reproduce the error.  You can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-16 19:34 UTC

**Comment by jhessin** [comment] 2018-01-28 22:29
I am getting the same issue but I'm just trying to load the tree-view. It shows up as blank and I get a reference to this issue every time I click in the empty field.

**Comment by Recmo** [comment] 2018-02-01 23:57
Same here. I can't get the tree-view to work again. It goes 'empty' the moment I open a particular project.

**Comment by rsese** [comment] 2018-02-05 21:48
Looks like this is fixed by https://github.com/atom/atom/pull/16610 and the fix should be available in an upcoming release.

**Comment by gadlopes** [comment] 2018-03-14 09:28
I'm still getting this issue in 1.24.1 on macOS.

**Comment by martinzh** [comment] 2018-03-14 17:49
Same here... I need to restart Atom when it occurs to be able to use and see the files in the project tree view

**Comment by rsese** [comment] 2018-03-14 22:40
@gadlopes @martinzh can you try 1.25.0-beta3?  I think the fix wasn't in 1.24.

**Comment by gadlopes** [comment] 2018-03-15 09:00
Dear @rsese and @martinzh,
I've been using 1.25.0-beta3 all morning and I didn't see the tree view problem. I think it might be solved. Thank you so much for the tip!!!

Also, just a thank you for all developers working on Atom. Its a brilliant piece of software!

Best regards

**Comment by msabramo** [comment] 2018-04-05 21:25
I am getting this after upgrading to Atom 1.25.1 and I get it simply by clicking in the editor pane.

```
Error: Setting active pane that is not present in pane container
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:258:21)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1010:46)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:393:23)
    at HTMLElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:51:25)
```

**Comment by rsese** [comment] 2018-04-11 23:01
@msabramo - if you clear saved state, can you still reproduce (make sure to first save any unsaved work before clearing saved state)?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by Xmetalfanx** [comment] 2018-06-06 20:52
I just ran across this after having power issues and the power went out while atom was open.

I can COMFIRM that "atom --clear-window-state" (and even closing that atom instance and then reopening via menu (just "atom" i am getting at) FIXES this....

just want to post this for anyone who may have gotten to this thread the same way I have.
