### ISSUE TITLE
Can't update because of libcurl conflicts. Ubuntu 18.04

### ISSUE THREAD

**Issue by ecotechie** [atom/atom#18758] opened 2019-01-28 19:16 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:

### Description

Uubuntu 18.04 can't update from Atom 1.33 because of the libcurl3 vs libcurl4 dependencies. Not sure this issue was fixed by: atom/atom#18201

### Steps to Reproduce

1. Have Atom 1.33 installed
2. Try to update to newer version

**Expected behavior:** Update succeeds 

**Actual behavior:** Installer asks to install libcurl3 and remove libcurl4 (which also removes any other program using libcurl4)

**Reproduces how often:**100%

### Versions

Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.15rc1
git 2.17.1

Kubuntu 18.04

### Additional Information

Looks like there was a merged fix for this but it does not seem to be working for me. atom/atom#18201

**Comment by rsese** [comment] 2019-01-28 21:11
Thanks for reaching out - did you install using one of the supported installation methods?

https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt

I remember a few people mentioned they were still getting an error but they were using the unofficial Snap installation.

**Comment by ecotechie** [comment] 2019-01-28 21:52
I guess not...

I've been downloading the file directly from the release.
https://github.com/atom/atom/releases/latest

This is the one I'm trying to install now:
https://github.com/atom/atom/releases/download/v1.34.0/atom-amd64.deb

**Comment by ecotechie** [comment] 2019-01-28 23:05
So adding the Atom repo from the manual page worked! I guess it's just the .deb file from the GitHub releases that don't work?

Thanks, not sure if it's still a problem then?

**Comment by ecotechie** [comment] 2019-01-29 00:06
Ahh, now I see. I was installing through QApt from the dolphin file browser...
If I use the command line, up/down grading works as it did with your example.

This is when attempting to install the atom-amd64-1.34.0.deb
![image](https://user-images.githubusercontent.com/11607383/51874623-91919280-2316-11e9-99a4-cd222a5938bb.png)


Strange that it would have that effect....

**Comment by TriMoon** [comment] 2019-01-29 07:59
@ecotechie must be some other package(s) that insist on libcurl3?

Because im using the latest from the repo on Debian buster/sid at moment:
```console
~/ dpkg-query -l atom\* libcurl\*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version      Architecture Description
+++-=====================-============-============-==============================================================
ii  atom-beta             1.35.0-beta0 amd64        A hackable text editor for the 21st Century.
un  libcurl3              <none>       <none>       (no description available)
ii  libcurl3-gnutls:amd64 7.63.0-1     amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4:amd64        7.63.0-1     amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
un  libcurl4-gnutls-dev   <none>       <none>       (no description available)
```

**Comment by rsese** [comment] 2019-01-30 00:14
> Ahh, now I see. I was installing through QApt from the dolphin file browser...
If I use the command line, up/down grading works as it did with your example.
...
> If it's nothing to do with the packaging of the deb, then it may be the gui program's issue? Just thought I'd share my experiences updating.

Yep thanks for the heads up @ecotechie :+1:

Since this doesn't seem to reproduce directly with a supported installation method, we'll go ahead and close this out.  But if you find an issue specific to installing directly with the .deb or the official package repository, please let us know.

**Closed by rsese** 2019-01-30 00:14 UTC
Labels: linux

**Comment by TriMoon** [comment] 2019-01-30 09:46
You might want to try reporting this bug to the QApt devs.
Because if it were something related to the deb itself it would also happen on console line...
