### ISSUE TITLE
Wrong cursor placement on Gnome HiDPI

### ISSUE THREAD

**Issue by razvanz** [atom/atom#9047] opened 2015-10-05 09:49 UTC
I'm struggling since I upgraded to Atom `1.0.19` (on Arch Linux) with wrong cursor placement. I have a 4k 60Hz monitor therefore I increased the Gnome `scaling-factor 2` (HiDPI). 

Here is a image of the visual cursor being placed wrongly after (on top) of the semicolon, while the real one is before the semicolon:

![wrong_cursor](https://cloud.githubusercontent.com/assets/3844203/10277477/68b3dc18-6b56-11e5-8ece-3fb2ec336969.png)

It made a GIF for better feedback. Just focus on the cursor (Sorry for the other things going on. Didn't had time to find a better capture tool):

![atom](https://cloud.githubusercontent.com/assets/3844203/10277545/df23568a-6b56-11e5-847d-4d8229f7c5bf.gif)

**Comment by 50Wliu** [comment] 2015-10-05 11:57
This is a duplicate of #8964 and it looks like it'll be fixed by #8811, so follow those issues for updates :smile:.

**Closed by 50Wliu** 2015-10-05 11:57 UTC
