### ISSUE TITLE
Segmentation fault leading to system crash

### ISSUE THREAD

**Issue by askamist** [atom/atom#13610] opened 2017-01-13 14:48 UTC
### Description

I don't know the cause of the issue, but it is repeatedly happening, and when it happens my system stops responding completely. 

this is the syslog

```
Jan 13 19:11:47 MIST kernel: [  531.318445] show_signal_msg: 27 callbacks suppressed
Jan 13 19:11:47 MIST kernel: [  531.318453] atom[1935]: segfault at 1b11 ip 00007f06bdb8e4af sp 00007ffd817eb9c0 error 4 in libnode.so[7f06bd517000+136d000]
```

### Versions

```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12+
git 2.9.3
```

uname -a
```
Linux MIST 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

lsa_release -a

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety
```

**Comment by lee-dohm** [comment] 2017-01-28 01:33
Thanks for the report.

There isn't enough information in this issue for us to meaningfully attempt to reproduce it. If we can't reproduce the problem, we're not going to be able to debug it and then fix it. If there is any more information you can give us, we'll be happy to investigate further.

Let us know :grinning:

**Comment by AndreaGriffiths11** [comment] 2017-02-08 00:52
Thanks for taking the time to contribute!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13610#issuecomment-275817037. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by AndreaGriffiths11** 2017-02-08 00:52 UTC
Labels: linux, more-information-needed
