### ISSUE TITLE
Ignored file patterns vs. searching, fuzzy finder, opening from tree view

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#7513] opened 2015-06-28 19:17 UTC
Currently, opening files through the fuzzy finder or searching in project files can take a long time and make Atom slowish when you have folders like `node_modules` and `bower_components` in your project which can get quite large.

A solution is to add these folders to Atom's list of Ignored names. However, this causes them to disappear from the tree view as well, making it impossible to look in them if needed, unless you remove them from the ignored names again.

Needless to say going back and forth like this is a bit of a hassle, especially when working on different projects where you need frequent access to `node_modules` and others where you don't. I find myself adding and removing `node_modules` from the ignore list at least two or three times a day.

Is there a way to support this use case? Some idea's that come to mind:

* Exclude files and folders listed in .gitignore from the fuzzy finder / search in files? That way I don't have to add `node_modules` to Atom's ignore list, it will still be accessible in tree view (greyed out), yet it won't slow Atom by searching in those folders.
* Have a separate ignore list for the search / fuzzy file opener? That way `node_modules` can be visible in Atom, but search and fuzzy file opener will be able to ignore it.
* A toggle option to "view ignored files/folders"? They will be displayed in the tree view (greyed out) when toggled, but all other functionality remains the same (e.g. they are not included in the search).

**Comment by Soleone** [comment] 2015-07-02 20:43
for what it's worth i personally like to have the ignored files removed from both `tree-view` and the fuzzy finder (and anything else that might slow down atom or me), but i can see the use case of @adambuczynski

**Comment by adambuczynski** [comment] 2015-07-02 21:18
I've noticed that as long as files are ignored by the VCS (e.g. .gitignore) are actually not included in the fuzzy file finder if you have the setting "Exclude VCS Ignored Paths" on. However, Atom still causes a significant delay in indexing the project if I have a large `node_modules` folder, even with that setting on. This is odd, since you'd think the folder should not be indexed in the first place at all if you have that setting on.

I'd expect the flow to be:
1) Read .gitignore if "Exclude VCS Ignored Paths" is enabled
2) Index project, while ignoring the paths in .gitignore and "Ignored names"
3) Re-index if .gitignore changes?

**Comment by adambuczynski** [comment] 2015-07-05 23:43
Just an additional observation, the fuzzy finder starts to lag tremendously after every character typed, if folders with a lot of files are not ignored explicitly. I've had two folders which are ignored in VCS but were not ignored in Atom settings.

Opening the project and indexing all the files the first time took a while, but even after that was done, every time you open another file the fuzzy finder is extremely laggy and slow, as if it's still going through all of those files even though they will never show up in the results.

Adding those two folders to Atom's ignored names works and speeds up the fuzzy finder again, however, as I explained above, I don't want to keep adding/removing them depending on which project I work.

Could this be flagged as a bug please? It seems that if the options "Exclude VCS ignored paths" is enabled, those paths should not be indexed by the fuzzy finder, but that doesn't seem to be the case now.

**Comment by carlo** [comment] 2016-04-19 07:09
+1

**Comment by lee-dohm** [comment] 2016-04-21 22:52
I'm not sure I understand exactly what is being described here.

* Atom provides the means to ignore files either using your `.gitignore` in projects that are under Git control or the "Ignored Names" setting in the Settings View
* Either of the above will prevent files from showing up in the Tree View or Fuzzy Finder
* You can toggle whether either VCS ignored files or ignored names are displayed in the Tree View using the `tree-view:toggle-vcs-ignored-files` and `tree-view:toggle-ignored-names` commands, respectively
* The `tree-view:toggle-vcs-ignored-files` command is mapped to <kbd>I</kbd> by default when the Tree View is focused

Is there anything I missed?

**Comment by adambuczynski** [comment] 2016-04-22 01:29
So here's the thing. Not all packages respect or use the setting `Exclude VCS ignored paths` properly. For example find & replace seems to ignore it.

For example, I have a project with a `bower_components` folder. This folder is in my `.gitignore` and I have the option `Exclude VCS ignored paths` enabled in my settings. However, when I do a find & replace for `bower`, I get a lot of results from files within the `bower_components` folder. That's not the behaviour I want, and it makes finding and replacing very slow, since Atom is looking in all the subfolders in `bower_components`. 

So the current solution is to add `bower_components` to the list of `Ignored names`. Now, find & replace will no longer search in that folder. However, a side effect is that now the folder `bower_components` also no longer appears in tree view. This is undesirable, because sometimes I want to browse through the various packages to view some code.

I think the problem lies in the fact that there is a global setting for `Ignored names`, and that all packages use it indiscriminately. More flexibility could be achieved by letting each of the relevant packages that deal with ignored files (fuzzy finder, tree view, find & replace, etc) have their own `Ignored names` setting, which may or may not get merged with the "main" setting.

I actually created a PR for the tree view package that does exactly that, but it never got merged/reviewed: https://github.com/atom/tree-view/pull/698

This is all still current with Atom 1.9.0-dev-77dea79.

Let me know if you have further questions @lee-dohm , I hope I made the use case clear.

**Comment by lee-dohm** [comment] 2016-04-22 18:07
> I have a project with a bower_components folder. This folder is in my .gitignore and I have the option Exclude VCS ignored paths enabled in my settings. However, when I do a find & replace for bower, I get a lot of results from files within the bower_components folder. 

I can't replicate this behavior using Atom v1.7.2 on Mac OS X 10.11.4. Additionally, if there is something I'm missing in how I'm attempting to repro this, I would consider this a bug in find-and-replace.

The main problem with having each package have their own settings for these things is that people have a hard enough time understanding the system we have now. Making it more complex will turn something that is challenging to support into a support nightmare.

**Comment by adambuczynski** [comment] 2016-04-22 22:14
> I can't replicate this behavior using Atom v1.7.2 on Mac OS X 10.11.4. Additionally, if there is something I'm missing in how I'm attempting to repro this, I would consider this a bug in find-and-replace.

That's very strange. I've been having this issue for as long as I can remember (on OS X). I will try to create an isolated test case.

> The main problem with having each package have their own settings for these things is that people have a hard enough time understanding the system we have now. Making it more complex will turn something that is challenging to support into a support nightmare.

While I appreciate that, I think you are alienating more serious users who need this kind of flexibility. Maybe there are different ways of tackling the problem though. I would also be happy if there's anything I could do in my own init script that would fix this issue for me.

**Comment by lee-dohm** [comment] 2016-04-22 22:20
Here's what I did to attempt to reproduce the issue you described:

1. Launch Atom in my Atom project repository
1. Create a new file using <kbd>Cmd+N</kbd>
1. Save the file as `debug.log` using <kbd>Cmd+S</kbd> (since Atom has `debug.log` ignored in `.gitignore`) 
1. Type the text `supercalifragilisticexpialidocious` into the file
1. Save again using <kbd>Cmd+S</kbd>
1. Open the Find in Project panel with <kbd>Shift+Cmd+F</kbd>
1. Paste in `supercalifragilisticexpialidocious` to the field and press <kbd>Enter</kbd>

Expected and Actual: No results found

**Comment by lee-dohm** [comment] 2016-04-22 22:24
> I think you are alienating more serious users who need this kind of flexibility.

I would definitely be open to creating a [Behavior Service](https://github.com/atom/atom/issues/9820) that all packages could use to determine whether files are ignored. If someone wanted a more complex ignore system, they could then create a package that offered it and install that.

**Comment by adambuczynski** [comment] 2016-04-24 10:38
> I would definitely be open to creating a Behavior Service that all packages could use to determine whether files are ignored. If someone wanted a more complex ignore system, they could then create a package that offered it and install that.

That sounds like a great idea! It would make modifying behaviour of the service easier, when it's addressed in one place and you don't have to go around all the different packages to adjust settings/code.

I'll get back to you regarding the reproduction steps next week when I'm back at work.

**Comment by lee-dohm** [comment] 2016-04-25 17:56
Thanks @adambuczynski! I'm looking forward to it :grinning:

**Comment by adambuczynski** [comment] 2016-04-26 23:58
@lee-dohm ok, it's getting interesting. I've created some test files with `supercalifragilisticexpialidocious` in it, put one of them in my project app folder, one in `node_modules`, and one in `bower_components`.

My `.gitignore:` contains:

```
node_modules
bower_components
```

And both those folders are greyed out in the tree view.

When doing a search for `supercalifragilisticexpialidocious` it doesn't find the file that I created in `node_modules`. However, it finds both the one in my app folder, and the one in `bower_components`:

![image](https://cloud.githubusercontent.com/assets/490562/14837760/4dce2858-0c6f-11e6-8746-2ab4f48f717e.png)

I have to add `bower_components` to Ignored Names setting manually for this to stop happening...

Seems like an actual bug, since `node_modules` are being ignored properly.

**Comment by lee-dohm** [comment] 2016-04-27 00:04
What version of Atom did you experience this on?

**Comment by adambuczynski** [comment] 2016-04-27 00:44
This is on 1.9.0-dev-77dea79

**Comment by adambuczynski** [comment] 2016-05-03 20:37
@lee-dohm have you had a chance to look into this further?

**Comment by lee-dohm** [comment] 2016-05-03 21:59
**Ugh**, it seems I lost a big reply with all the investigation I did on this ... it'll take me a while to redo it. Look for it later today.

**Comment by adambuczynski** [comment] 2016-05-03 22:15
Oh, bummer.. :(

**Comment by lee-dohm** [comment] 2016-05-04 00:11
I can't reproduce this using Atom v1.9.0-dev-c56cbe3 on Mac OS X 10.11.4. (And to my recollection, I couldn't reproduce it on v1.9.0-dev-77dea79 either.) Here's what I did:

```bash
[~/Source] mkdir test
[~/Source] cd test
[~/Source/test] git init
Initialized empty Git repository in /Users/Lee/Source/test/.git/
[master][~/Source/test] echo "node_modules" >> .gitignore
[master][~/Source/test] echo "bower_components" >> .gitignore
[master][~/Source/test] echo "supercalifragilisticexpialidocious" > test.js
[master][~/Source/test] mkdir node_modules
[master][~/Source/test] mkdir bower_components
[master][~/Source/test] echo "supercalifragilisticexpialidocious" > node_modules/test.js
[master][~/Source/test] echo "supercalifragilisticexpialidocious" > bower_components/test.js
[master][~/Source/test] atom .
```

![screen shot 2016-05-03 at 5 10 11 pm](https://cloud.githubusercontent.com/assets/1038121/15002054/eefe0c52-1151-11e6-8f82-1681412d741b.png)

**Comment by lee-dohm** [comment] 2016-05-04 00:13
I also tried it with the `node_modules` and `bower_components` entries reversed in the `.gitignore` in case it was some sort of nodegit problem with ordering in the ignore file.

**Comment by lee-dohm** [comment] 2016-05-04 00:15
I also redid the test after closing Atom and moving my `~/.atom` directory somewhere else to ensure it isn't anything with one of my packages or configuration:

![screen shot 2016-05-03 at 5 14 43 pm](https://cloud.githubusercontent.com/assets/1038121/15002110/ad68b016-1152-11e6-8343-ed70139a890a.png)

**Comment by adambuczynski** [comment] 2016-05-04 01:27
@lee-dohm You are right good sir. Reproducing it with your steps was not possible. So I went to see what was different between the setup you tested with, and the project where I'm having this issue, and I think I've figured it out.

It seems to have to do with the folder structure. Try nesting all your files (except `.git`) in a sub folder (e.g. `test/some-folder`). Then, open this sub folder in Atom, instead of the base folder, and do a search. Now, the files do show up even though the folders are still greyed out in the tree view:

![image](https://cloud.githubusercontent.com/assets/490562/15003054/c62ec19a-11fb-11e6-800b-38357f27290c.png)

When I open the parent folder and search, I can't reproduce it:

![image](https://cloud.githubusercontent.com/assets/490562/15003066/e492a9bc-11fb-11e6-98a1-2dccd4a11e76.png)

So it seems to me that while tree view is properly ignoring the folders, and using the rules in the `.gitignore` file contained in the sub folder, find & replace is not.

Hope this helps!

**Comment by adambuczynski** [comment] 2016-05-04 01:30
PS in case you're wondering why I am opening my project with a sub folder, it's because this is a very large project in one git repo, and we have a team doing server side development separate from client side development, and the client side code which I'm working on is nested several folders deep.

But regardless, it seems to me like a bug in Atom or in find & replace package.

**Comment by lee-dohm** [comment] 2016-05-04 01:52
Yes, this is the expected behavior. We used to go hunting up the directory structure for a Git repository if Atom couldn't find one in the root of the project. This led to serious [performance concerns](https://github.com/atom/atom/issues/6437) when people had initialized their home directory as a Git repository and then opened up directories that weren't repositories at all underneath their home directory. Because of this, we disabled support for this setup. (We also don't detect if the [Git repository is in a folder that is below the project root](https://github.com/atom/atom/issues/2203).)

**Closed by lee-dohm** 2016-05-04 01:52 UTC
Labels: more-information-needed

**Comment by adambuczynski** [comment] 2016-05-04 02:19
@lee-dohm but current behaviour is inconsistent, because the folders are still marked as ignored in tree view. That means tree view is aware of the `.gitignore` file and it's rules, but find & replace is not. Why this discrepancy?

While I appreciate the performance issues, I wonder if we can handle this in a more pragmatic way. Instead of going through all sub folders, it would be enough to solve this issue to simply look in the opened root folder.

That's what tree view seems to be doing, so why can't find & replace do the same? It would solve this issue and doesn't seem like it would impact performance, as we only need to look in the root folder that's currently opened in Atom.

**Comment by adambuczynski** [comment] 2016-05-06 03:05
@lee-dohm any thoughts on the above?

**Comment by adambuczynski** [comment] 2016-05-14 04:37
@lee-dohm I really don't think this issue should be closed yet. In another project, where I have the following in my `.gitignore` in the root of the project, it's also not working as expected.

See this related issue: https://github.com/atom/find-and-replace/issues/636

Could you please reopen this, as I really don't think it's been resolved to satisfaction.

**Comment by lee-dohm** [comment] 2016-05-16 16:37
> but current behaviour is inconsistent, because the folders are still marked as ignored in tree view. That means tree view is aware of the .gitignore file and it's rules, but find & replace is not. Why this discrepancy?

Do you have repro steps for this behavior? Or is that what you included in the linked issue?

**Comment by adambuczynski** [comment] 2016-05-16 19:15
> Do you have repro steps for this behavior? Or is that what you included in the linked issue?

Same as the test setup we used above, see my comment https://github.com/atom/atom/issues/7513#issuecomment-216716533

You can see in the screenshots that tree view marks the folders as ignored both times (properly), whereas find & replace works in the one scenario and doesn't in the other.

**Comment by lee-dohm** [comment] 2016-05-18 19:47
I feel like this Issue has ranged around too much to be well-defined at this point. @adambuczynski would you mind opening a new Issue specifically for the inconsistency problem? Please @mention me on it when you do.

**Comment by adambuczynski** [comment] 2016-05-18 20:06
Ok will do

**Comment by dj-hedgehog** [comment] 2016-07-26 09:40
This issue and https://github.com/atom/find-and-replace/issues/636 should be closed in favor of https://github.com/atom/find-and-replace/issues/621. They all describe the same problem and the wrong behaviour can be reproduced 100% of the time.
