### ISSUE TITLE
Search in directory results are in unexpected order

### ISSUE THREAD

**Issue by ajones513** [atom/atom#6494] opened 2015-04-23 12:34 UTC
See screenshot: seems like `a/b/file5` should appear just below `a/file2`, not after `z/file4`.

![screen shot 2015-04-23 at 13 28 15](https://cloud.githubusercontent.com/assets/3205856/7297018/c295f750-e9bc-11e4-8f48-03fdd4e6717c.png)

I'm using OS X 10.9.5, Atom version 0.194.0.

**Comment by mnquintana** [comment] 2015-04-23 12:41
Duplicate of atom/find-and-replace#64

**Closed by mnquintana** 2015-04-23 12:41 UTC
