### ISSUE TITLE
Minor blur applied to editor after scrolling down.

### ISSUE THREAD

**Issue by RealBlazeIt** [atom/atom#15221] opened 2017-08-09 21:27 UTC
### Description

Whenever I scroll down to the bottom of a file, a minor blur is added to the editor, slightly blurring all text, and only returns to normal once I scroll back up. Here is a screenshot before scrolling down entirely: https://prnt.sc/g6ixmp and here is a screenshot after: https://prnt.sc/g6ixyr. If you switch back and forth between tabs, you can clearly notice a difference, which has been bothering me since I noticed it. 

This does not happen to files that fit entirely on my screen, as there is nothing to scroll to. It only occurs when I scroll down while viewing a file, and reach the complete bottom, then this minor blur will affect that file only, until I scroll up entirely to the top. 

I have tried switching UI/syntax, disabling all the packages I use, restarting Atom, and it keeps happening.

### Versions
Atom: 1.19.0

OS: Windows 8

**Comment by rsese** [comment] 2017-08-09 22:22
Are you using DPI scaling?  /cc https://github.com/atom/atom/issues/14237.

Also, it's not mentioned in your issue but did you remember if you saw this behavior in 1.18.0?

**Comment by ArekX** [comment] 2017-08-10 08:38
I have the same issue.

I ran Atom 1.18.0 whole day yesterday since I didn't want to update yet because I was using it for work. I ran the updated version today and I have the same issue. I am using Windows 10 with latest Creators Update on 2 monitors, one is 1920x1080 21'', second is 1920x1080 15.6''. 

Atom 1.18 had no issues whatsoever and I did not need to turn off high dpi settings.

Here it is how it looks like without any High DPI settings turned off:
![image](https://user-images.githubusercontent.com/4344776/29161515-d1f1cedc-7db6-11e7-8c8c-00b8d300dbe3.png)
You can clearly see the difference on the title and on the editor.

When I turn off High DPI settings this is how it looks like (Override high DPI scaling behavior performed by: Application):
![image](https://user-images.githubusercontent.com/4344776/29161566-05ce41e0-7db7-11e7-8201-d344addb5205.png)
You can see now it is crisp and looks ok.

But when you have large amount of code and have to scroll down, you experience this after few scrolls up and down:
![image](https://user-images.githubusercontent.com/4344776/29161783-d356a47c-7db7-11e7-915c-10f0f63f8900.png)
When you scroll to top up it becomes crisp again.

Again, I used Atom 1.18.0 whole day yesterday and this was never the issue nor did I have to tweak any High DPI settings in windows. This started happening when I upgraded to Atom 1.19.0 today.

**Comment by 50Wliu** [comment] 2017-08-10 12:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14237. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-10 12:52 UTC
Labels: more-information-needed
