### ISSUE TITLE
Select to beginning or end of word in macOS Sierra save dialog not working

### ISSUE THREAD

**Issue by thebigreason** [atom/atom#13542] opened 2017-01-04 18:38 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom is not respecting the system keybinding for select to the beginning or end of word (shift+option+left arrow/right arrow) in macOS Sierra save dialog boxes.

### Steps to Reproduce

1. Create a new blank document or open an existing one.
2. Choose File > Save As… 
3. Enter a multi-word file name in the Save As: field and use shift+option+left arrow or shift+option+right arrow to attempt to select individual words in the file name.

**Expected behavior:** The preceding or proceeding word should be selected.

**Actual behavior:** Atom invokes the Selection > Select to Beginning of Word/Select to End of Word menu item.

**Reproduces how often:** 100%

### Versions

Atom    : 1.12.8
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.7.2

OS: macOS Sierra 10.12.2 (16C67)

### Additional Information

This issue happens in both states of the expanded or non-expanded state of the macOS Sierra save dialog.

**Comment by lee-dohm** [comment] 2017-01-28 22:30
I was able to reproduce this using Atom v1.13.1 on Mac OS X 10.12.3.

**Comment by jasonrudolph** [comment] 2017-05-10 13:13
This appears to be resolved as of Atom 1.15.0

On macOS 10.12.4, I can reproduce the issue in Atom 1.14.4, but I cannot reproduce it in 1.15.0 or 1.16.0. With that in mind, I'm going to close this issue. If anyone is still able to reproduce this issue in the current release, please let us know.

**Closed by jasonrudolph** 2017-05-10 13:13 UTC
Labels: bug, regression, triaged

**Comment by thebigreason** [comment] 2017-05-10 18:32
I can no longer reproduce this on 1.15.0, macOS 10.12.4. Excellent work. Thank you!
