### ISSUE TITLE
Uncaught Error: EEXIST, file already exists '/Users/BernzAir/.atom/storage'

### ISSUE THREAD

**Issue by mrbernz** [atom/atom#4844] opened 2015-01-04 21:35 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EEXIST, file already exists '/Users/BernzAir/.atom/storage'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:74

undefined
```

### Commands

```
```

### Config

```
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "auto-indent": true,
    "softWrap": true,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.2.0
auto-update-packages, v0.2.1
autocomplete-paths, v0.7.0
autocomplete-plus, v0.22.3
autocomplete-snippets, v0.2.0
color-picker, v1.2.6
linter, v0.9.0
seti-syntax, v0.2.1
seti-ui, v0.5.1
trailing-spaces, v0.2.3

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-01-06 18:01
Did this happen when you launched Atom?

**Comment by kevinsawicki** [comment] 2015-01-06 18:02
I believe this is a duplicate of https://github.com/atom/atom/issues/4806

**Closed by kevinsawicki** 2015-01-06 18:02 UTC
Labels: more-information-needed
