### ISSUE TITLE
Incorrect selection highlight after pane resize

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#12891] opened 2016-10-06 14:33 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

After selecting a region of code and resizing the pane, the highlight will _visually_ be in the incorrect position, but it still is actually where the original highlight was.

### Steps to Reproduce

1. The easiest way to reproduce this is by creating a new pane, such as through Markdown Preview, though simply splitting the current pane works as well.
2. Open a `.md` file.
3. Highlight some text
4. `markdown-preview:toggle`
5. The text should still be highlighted at this point
6. `markdown-preview:toggle`
7. ?!
8. You can verify that the highlight is still in the correct place through a variety of ways: using the arrow keys to move the cursor, cutting the highlighted text, etc.

![incorrect-selection-on-pane-resize](https://cloud.githubusercontent.com/assets/2766036/19156576/5ffa4bb8-8bb0-11e6-9dbc-1b7ab4ea60c6.gif)

**Expected behavior:** The highlight to visually stay in the correct place.

**Actual behavior:** The highlight moves! :ghost:

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.
```
Atom    : 1.12.0-dev-fcddf83
Electron: 1.4.1
Chrome  : 53.0.2785.113
Node    : 6.5.0
```
```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.0.windows.1
visual studio 2015
```

**Comment by Ben3eeE** [comment] 2016-10-06 14:38
Might be a duplicate of https://github.com/atom/atom/issues/12622. I can reproduce this with the steps in https://github.com/atom/atom/issues/12622.

**Closed** 2016-10-06 14:45 UTC
Labels: bug, editor-rendering
