### ISSUE TITLE
Old folder is also appeared when  save all files in mac

### ISSUE THREAD

**Issue by zhjhxxxjh** [atom/atom#11759] opened 2016-05-16 01:56 UTC
the error appear :
1. new folder and create a file, open the file and write some content
2. rename the folder 
3. save all files Ctrl+Option+S

the old folder is appeared, and this operation is in mac
atom 1.7.3

**Comment by lee-dohm** [comment] 2016-05-16 02:13
This is a duplicate of https://github.com/atom/atom/issues/10751. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-05-16 02:13 UTC
