### ISSUE TITLE
atom not detecting sass/scss mixins or variables

### ISSUE THREAD

**Issue by AmirFawzy** [atom/atom#16158] opened 2017-11-11 12:22 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

when i working on sass/scss files and use mixin, custom function or variables atom doesn't detecting those mixin, variables...atc
for example: when i use a variable when i write *"$"* which is declaration with first letter of the variable name atom doesn't show suggestions with list for all variables that start with that first letter i written it like autocomplete the variable ... and instead of that it show just suggestions for the most use words in project.
image for more clarification.
![screenshot 1](https://user-images.githubusercontent.com/19322308/32689340-632a7a0c-c6eb-11e7-8597-d61c4c82585b.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** when i start type value in sass/scss starting with *"$"* and first letter atom show list of all variables which start with that letter ... when i write *"@include"* and first letter or more of mixin name it should show list with all mixins start or match that letter or word i written.

**Actual behavior:** when i write *$, @include and @extend* it show suggestions with the most used words in project not with actual variables or mixin it doesn't auto detecting variables or mixins like it's not exist or bind with project.
like image in description above.  

**Reproduces how often:** all the time.

### Versions
**OS:** windows 10 Pro v1709 x64
**atom**
Atom    : 1.22.0
Electron: 1.6.15
**apm**
apm  1.18.8
npm  3.10.10
node 6.9.5 x64

**Comment by alex-schmidt** [comment] 2017-11-13 16:13
The same problem for LESS from recent times, maybe a week...

**Comment by rsese** [comment] 2017-11-13 18:16
Thanks for the report - can either of you share a project or small reproduction that shows this behavior?  

@alex-schmidt - do you remember what version of Atom where this used to work for you?  And you're also on 1.22.0?

**Comment by AmirFawzy** [comment] 2017-11-16 03:37
it's tons of codes sorry but not able to share the project even small part of it will not make the problem clear anyway i think the bug is very clear **atom doesn't hint** any of variables or mixins that bind with main SCSS file that's it.
and obvious that happening with all **preprocessor languages** cuz that happening with @alex-schmidt as well with LESS.
need to mention again that bug/problem **start to happening after latest update** for atom before that atom was working good with preprocessor langs.

**Comment by AmirFawzy** [comment] 2017-11-16 05:54
it's tons of codes sorry but not able to share the project even small part of it will not make the problem clear anyway i think the bug is very clear **atom doesn't hint** any of variables or mixins that bind with main SCSS file that's it.
and obvious that **happening with all preprocessor languages** cuz that happening with @alex-schmidt as well with LESS.
need to mention again that **bug/problem start to happening after latest update for atom** before that atom was working good with preprocessor lang (SCSS).

**Comment by AmirFawzy** [comment] 2017-11-17 09:05
problem still exist after upgrade to atom 1.22.1

**Comment by SolderHQ** [comment] 2017-11-17 11:18
I have the very same problem. It started happening some time ago, and is totally driving me nuts. Autocomplete used to work as expected a while ago. Unfortunately I don't remember exact date when this broke. Here's a screenshot:

![screen shot 2017-11-17 at 13 16 46](https://user-images.githubusercontent.com/17155971/32944851-ac003da4-cb99-11e7-80ed-7a3526666cb4.png)

I'm running Atom 1.22.1 on macOS 10.13.1.

**Comment by AmirFawzy** [comment] 2017-11-18 18:35
[Uploading charts-master.zip…]()

**Comment by DamirPecnik** [comment] 2017-11-21 18:04
I have the same problem running 1.22.1 version!

**Comment by SolderHQ** [comment] 2017-11-23 06:56
Is there anything we could do to help you with this @rsese ? The label says this needs more information, could we provide that for you somehow? :)

**Comment by rsese** [comment] 2017-11-24 18:42
Sorry just getting back around to this @SolderHQ - can you provide a simple reproduction?  I can ask the team to take a look soon.

**Comment by rsese** [comment] 2017-11-26 08:12
Hmmm, fixed by https://github.com/atom/autocomplete-plus/pull/928 @leroix?  Based on the images, looks like variables with hyphens in the name like https://github.com/atom/autocomplete-plus/issues/931?

**Comment by leroix** [comment] 2017-11-26 16:45
@rsese yup, that's correct. It'll be applied to 1.23, but maybe this warrants a hotfix to stable?

**Comment by rsese** [comment] 2017-11-27 18:49
Ahhh great, thanks @leroix :v:, we'll go ahead and close this issue then since the fix is merged.

> maybe this warrants a hotfix to stable?

Hmm good question, let's confirm with other folks when we talk later this week.

**Closed by rsese** 2017-11-27 18:49 UTC
Labels: needs-reproduction

**Comment by Mushr0000m** [comment] 2017-12-22 11:01
Sorry to reopen this issue but I'm using the 1.23.1 and still having this issue, the fix is not merged ?

**Comment by leroix** [comment] 2017-12-22 16:39
Hi @Mushr0000m, I believe the fix is in 1.24 beta.

**Comment by RAFA3L** [comment] 2017-12-22 16:46
![screen shot 2017-12-22 at 12 44 37 pm](https://user-images.githubusercontent.com/3952265/34305749-ff46e976-e715-11e7-8256-22286e561a61.png)
It work for me in 1.23.1

**Comment by Mushr0000m** [comment] 2017-12-22 16:50
@RAFA3L : It looks your are using Pigment package, if yes that's why it's working.

**Comment by RAFA3L** [comment] 2017-12-22 16:53
You are right, only work with Pigment
