### ISSUE TITLE
Incorrect Tag Matching with self-closing tags

### ISSUE THREAD

**Issue by unional** [atom/atom#9976] opened 2015-12-08 01:38 UTC
![image](https://cloud.githubusercontent.com/assets/3254987/11645423/4405bfdc-9d09-11e5-8495-c721b265b122.png)
See the end tag `A` is matched with the self-closing `A` inside.

https://github.com/TypeStrong/atom-typescript/issues/771

**Comment by 50Wliu** [comment] 2015-12-08 02:56
This seems like a duplicate of atom/bracket-matcher#115 - please subscribe there for updates.

Though if the issue turns out to be because of the extra `begin`/`open` tags, please comment over at atom/bracket-matcher#115 so that I can take a look at the other grammars that are having this issue!

**Closed by 50Wliu** 2015-12-08 02:56 UTC
