### ISSUE TITLE
Cannot open files or folders on Mac OS X El Capitan beta

### ISSUE THREAD

**Issue by sourcebits-robertbiggs** [atom/atom#7811] opened 2015-07-09 03:50 UTC
You cannot open a file or folder on Mac OS X El Capitan. This has been the case with the first, second and current third developer release.

Also, after opening the file dialog, cancel does not close it. Command Q does, then Command Q to close Atom. 

Interestingly, Visual Studio Code, built on the same Electron code base, runs perfectly fine on these builds of Mac OS X El Capitan.

**Comment by paulcbetts** [comment] 2015-07-09 05:56
This is your computer, I've been using El Capitan for all three releases, all of which have successfully opened files and folders.

**Comment by batjko** [comment] 2015-07-09 06:00
Presumably you have tried opening files and folders via the various different means, i.e. the menu, right-click into the tree-view, and key binding, and they all don't work?

When using the key bindings, what does the Keybinding Resolver (`Cmd-.`) tell you?

**Comment by sourcebits-robertbiggs** [comment] 2015-07-09 06:06
I'm on a new Macbook 12". Nothing really unusal about my setup. Command O failes. But if I drag a folder/file to the dock icon, it opens. As soon as I try to access the menu or command key to open a file/folder, it freeze and I have to right click on the dock icon to quite.

The (```Cmd-.```) returns: No issues.

**Comment by sourcebits-robertbiggs** [comment] 2015-07-09 06:09
OK, so I delete the app and delete its folder from ~/Library/Application Support, then download Atom again and the same problems persist.

**Comment by thomasjo** [comment] 2015-07-09 06:47
I assumed you've tried running Atom in safe mode? `atom --safe`

**Comment by mrz1277** [comment] 2015-07-09 08:34
+1 Same here. 
Drag works but open from menu not.

**Comment by moxorama** [comment] 2015-07-09 10:30
+1 10.11 Beta 3, Beta 2 was ok.

**Comment by mnquintana** [comment] 2015-07-09 11:56
This might be blocked on https://github.com/atom/atom/pull/6877

**Comment by sourcebits-robertbiggs** [comment] 2015-07-09 16:59
@thomasjo I tried opening Atom with ```atom --save```, but the same problems persist for me.

**Comment by framerate** [comment] 2015-07-09 22:43
I know using beta OS is my problem, but I wanted to chime in:

On mine cmd-o opens the El Capitan open dialog but I cannot close it. Open + Cancel both have no effect


<img width="898" alt="screen shot 2015-07-09 at 3 42 29 pm" src="https://cloud.githubusercontent.com/assets/74291/8608598/27082390-2651-11e5-9e6e-17e964bb6f2b.png">

**Comment by sourcebits-robertbiggs** [comment] 2015-07-09 22:45
That's exactly my problem as well.

**Comment by azdavis** [comment] 2015-07-09 23:00
Yep, this happens with me as well. Also, "New Folder" covers the "Hide extension" checkbox for me, as in the screenshot attached above.

**Comment by ylong** [comment] 2015-07-10 01:10
My problem as well, atom 1.0.2 + EI Captian beta 3

**Comment by sollicity** [comment] 2015-07-10 12:44
My problem as well, atom 1.0.2 + EI Captian beta 3

**Comment by Cu3PO42** [comment] 2015-07-10 14:12
+1 get this as well, Atom 1.0.2, 10.11 Beta (15A215h). Once the "open file" dialog is opened, I can close it by "quitting" Atom, which only closes the dialog. Dragging files in also works for me. Safe mode does not solve the problem. Reinstalling didn't either.

**Comment by thomasjo** [comment] 2015-07-10 15:07
I can reproduce the problems on 15A215h.
Here's a snippet of the relevant parts of the system log:
https://gist.github.com/thomasjo/7d5755428327361b8798

The part that stands out is
```
BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d
```

I believe that is triggered when you launch the *Open* dialog. Hard to time exactly, but I get the same stuff dumped every time I provoke the problem.

**Comment by shawnyeager** [comment] 2015-07-10 15:48
I'm seeing the same behavior with build 15A215h and Atom 1.0.2. The file open dialog will display, but neither Cancel nor Open are responsive. I have to force-quit.

Also, the initial rendering of window, toolbar menu and side panel are very slow.

**Comment by mcculley1108** [comment] 2015-07-10 17:32
Also having the same issue.

**Comment by ciokan** [comment] 2015-07-10 18:59
+1 drag works but not using the finder

**Comment by arynhard** [comment] 2015-07-10 19:53
+1

**Comment by nicoNaN** [comment] 2015-07-10 21:57
Same issue here - can `cd` into a directory and do `atom .` without a problem, but the dialogue window is totally busted.

**Comment by ljsebald** [comment] 2015-07-11 01:25
+1 here on Public Beta 1 (15A215h).

**Comment by crazytyper** [comment] 2015-07-11 04:28
+1 here on Public Beta 1 (15A215h).
open file dialog cannot be closed.

it appears to work with other electron shell based applications (e.g. visual studio code 0.5.0).

**Comment by vypr** [comment] 2015-07-11 09:12
+1

**Comment by fterrier** [comment] 2015-07-11 10:46
+1

**Comment by alvesdan** [comment] 2015-07-11 11:40
+1 Public Beta (15A215h).
"Add project folder" also doesn't work.

**Comment by ElDood** [comment] 2015-07-11 16:23
Same problem here on Beta 15A216g. Open menu get "stuck" and you can neither open a file/folder or close the window.

Drag & drop and "Open with" seems to do the trick in the meantime.

**Comment by shanev** [comment] 2015-07-11 20:05
+1

**Comment by 50Wliu** [comment] 2015-07-12 00:21
Hey everyone, we're currently aware of this issue and its magnitude.  However, all the "+1s" are just adding noise at this point, so I'm going to lock this issue.  Once someone starts to work on this issue or fixes it (which could be one of you - feel free to contribute!) we may unlock it to keep everyone updated.

**Comment by benogle** [comment] 2015-07-31 19:45
This should have been fixed by el capitan beta 3. Please upgrade and let us know if it is fixed for you.

**Comment by nicoNaN** [comment] 2015-07-31 19:57
Fixed on beta 3 here.

**Comment by nebm51** [comment] 2015-07-31 19:58
Works on beta 3

**Comment by thomasjo** [comment] 2015-07-31 20:01
Verified. Fixed in public beta 3 (and developer preview 5).

**Closed by thomasjo** 2015-07-31 20:01 UTC
Labels: bug, mac

**Comment by emlai** [comment] 2015-08-01 07:22
Not working for me on beta 3.

**Comment by marvu** [comment] 2016-08-10 10:05
Can someone explain how this issue did happen? I have the same problem with AU Lab with a Audio Plugin I'm developing and it would be great if someone can give me a hint how to solve this problem...

I also get this log message:
`10/08/16 11:49:11,112 AU Lab[50509]: BUG in libdispatch client: kevent[EVFILT_MEMORYSTATUS] add: "Operation not supported" - 0x2d`
