### ISSUE TITLE
Missed Project Folder

### ISSUE THREAD

**Issue by amirarsalan** [atom/atom#12488] opened 2016-08-21 08:24 UTC
Hello guys, 

I have a problem in atom. when add same project folder to that if atom was closed and I open a **file** ( txt, json, ... ) atom open and missed my Project Folder and add **file** path instead to Project Folder!

**Comment by damieng** [comment] 2016-08-25 20:35
Hi, this is a duplicate of #9643 and we'll track progress there. Thanks.

**Closed by damieng** 2016-08-25 20:35 UTC
