### ISSUE TITLE
Fetching outdated packages and themes failed. (MacOSX)

### ISSUE THREAD

**Issue by macpham** [atom/atom#13840] opened 2017-02-17 14:42 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![image](https://cloud.githubusercontent.com/assets/1777724/23069071/05d24610-f4f4-11e6-884f-700ade1a4faf.png)

It occurs in safe mode too.

### Steps to Reproduce
Try to check for updates to packages and themes.

**Expected behavior:**
It successfully checks for updates.

**Actual behavior:**
Error message and output shows `undefined`.

**Reproduces how often:**
100% of the time. 

### Versions

Mac OSX 10.11.6 El Capitan

![image](https://cloud.githubusercontent.com/assets/1777724/23069014/c9c0f554-f4f3-11e6-9add-1018f07cb881.png)

```
apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.1.3
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by prajjwaldimri** [comment] 2017-02-17 14:55
I am getting the same "undefined" error on Windows too.

**Comment by 50Wliu** [comment] 2017-02-17 18:06
Uninstall seti-syntax and seti-ui.  This is a duplicate of #13790.

**Closed by 50Wliu** 2017-02-17 18:06 UTC

**Comment by Krysisx** [comment] 2017-03-16 15:42
Hi, it does not work for me. I removed only `seti-ui` because it's the only packaged I had. My system is Linux Mint x64. Any help please?

**Comment by TristanBrotherton** [comment] 2017-05-19 18:28
I am having this issue and I do not have seti-syntax or seti-ui  and never have.

**Comment by dr-nafanya** [comment] 2017-06-08 17:20
Observing the same in the latest Atom. Have neither `seti-ui` nor `seti-syntax` themes.
<img width="1032" alt="screen shot 2017-06-08 at 10 17 03 am" src="https://user-images.githubusercontent.com/1902404/26941664-1d747d00-4c34-11e7-8337-7fd285616c82.png">

**Comment by averydev** [comment] 2017-08-14 17:19
I had this issue, and removing `seti-syntax` and `seti-ui` didn't help. The issue was that i didn't have my ssh key auto loading into my ssh-agent. 
This fixed it: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

**Comment by kdodia** [comment] 2017-08-19 02:59
For some reason the `seti-syntax` and `seti-ui` packages were not showing up within the settings pane of Atom itself, but I was able to find and remove them manually. Steps to reproduce:

1. Atom > Settings > Open Config Folder
1. Right click on "Packages" in the sidebar and select "Open in Finder"
1. Delete the `set-syntax` and `seti-ui` directories
1. Restart Atom

**Comment by Leland-Kwong** [comment] 2017-08-25 20:44
@kdodia That saved the day ,thanks for that!

**Comment by RexJaguarius** [comment] 2017-08-26 17:36
@kdodia Nice work. I was having this problem for weeks and I couldn't understand why, and I "didn't have seti installed" same as you. I never thought to check the directory, a simple thing to do but you thought of it not I. Thanks so much! 

This is the cause of this problem 100% - seti causes it, and in some cases does NOT show in the packages list.

**Comment by npawar868** [comment] 2018-03-27 12:04
I m using Fedora 25 and once I also had same error on my system. 
So I tried to update the Atom by using following command.

Fedora- **yum update atom**
Ubuntu- **sudo apt-get update atom**
And now error has gone.
