### ISSUE TITLE
onDidReload getting fired before onDidChange

### ISSUE THREAD

**Issue by ungb** [atom/atom#14189] opened 2017-04-12 21:22 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
onDidReload getting fired before onDidChange

### Steps to Reproduce
Was able to get a isolated repro with @Arcanemagus help.

1. `git clone https://github.com/AtomLinter/linter-eslint.git`
2. `git checkout arcanemagus/atom-repro-case`
3. run `atom .` from the repo cloned in step 1.
4. run package specs(test will always pass)
5.  open devtools in the spec window

**Expected behavior:** [What you expect to happen]
onDidReload gets fired after onDidChange.

**Actual behavior:** [What actually happens]
`onDidReload` sometimes gets fired before `onDidChange`,  This causes issues as `onDidReload` is being fired when the editor is blank.  

**Reproduces how often:** [What percentage of the time does it reproduce?]
~75%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
Atom    : 1.18.0-dev-9202160ca
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information
Here's a screenshot of the issue you'll see after you open dev tools

![image](https://cloud.githubusercontent.com/assets/5624870/24980007/3b5fae46-1f8b-11e7-9911-7f4beceeeea2.png)

Any additional information, configuration or data that might be necessary to reproduce the issue.

This is probably the underlying cause for issues #12243 and #5730

**Comment by Arcanemagus** [comment] 2017-04-13 01:37
To provide a little bit more context, normally when a file is changed externally the `TextBuffer` will update current contents line by line, firing an `onDidChange` for each removal of the old content line and adding of the new content line, when it has finished updating the editor for the new contents `onDidReload` is triggered:
![image](https://cloud.githubusercontent.com/assets/427137/24986343/8a34a814-1fae-11e7-89d8-5afa2f74af30.png)

When the bug triggers however, for some reason there is an `onDidChange` event fired when the `TextBuffer` has been emptied, then `onDidReload` fires in the same state. After a very short delay (not timed, but < 100 ms) an `onDidChange` event is fired with the full current contents of the file:
![image](https://cloud.githubusercontent.com/assets/427137/24986414/ec375124-1fae-11e7-8119-eff214a354f1.png)

The specs as they are in that branch will _usually_ pass due to the `await wait(100)` line in the relevant spec, removing that will cause it to fail whenever the bug reproduces.

**Comment by Arcanemagus** [comment] 2017-05-15 16:40
Is there anything I can do to help trace this down further?

**Comment by Arcanemagus** [comment] 2017-06-25 20:11
Further update, in the Atom v1.19.0 betas `onDidReload` appears to never fire, maybe this is related?

**Comment by Arcanemagus** [comment] 2017-08-09 19:10
Looks like this was fixed in the TextBuffer rewrite that happened for v1.19.0 🎉.

The reason the specs were failing was due to `TextBuffer::onDidReload` being broken _only_ in the specs.

**Closed** 2017-08-09 19:11 UTC
Labels: bug

**Comment by Arcanemagus** [comment] 2017-08-09 19:15
For posterities sake, the `atom-repro-case` branch was at https://github.com/AtomLinter/linter-eslint/commit/ac64f067a42bfbc5ea439153900d3278e8a0e072.
