### ISSUE TITLE
slow opening JSON document

### ISSUE THREAD

**Issue by sjamesmccarthy** [atom/atom#6607] opened 2015-05-01 20:46 UTC
opening and editing a JSON file is slow. seems more slow than it should be considering it's only bout 60k in size. I would attach the file but can't. It's nothing fancy, but here it is. In fact this textarea form reads the data in faster :-(

See https://gist.github.com/thomasjo/9b88cb2ee1e94f9f002f

---
**NOTE:** inline file removed by @thomasjo, and moved to a Gist.

**Comment by thomasjo** [comment] 2015-05-01 20:58
Please remove the massive JSON blob—create a Gist instead and link to that.

**Comment by sjamesmccarthy** [comment] 2015-05-01 21:16
so at last we agree it's massive but thank you for being fairly unhelpful otherwise. just close the issue it's obvious you're more concerned with less important things like putting a stupid 60k file in a post than trying to provide any kind of useful help.

**Comment by thomasjo** [comment] 2015-05-01 21:31
OK. I moved the inline file to a Gist for you. Removing noise from the issue body makes it easier for the rest of us to help you out.

I saved a copy locally, and opened it in Atom; it opens up really quick here. Are you able to reproduce the poor performance characteristics in safe mode? Just to make sure the issue is not caused by a community package.

In addition, it'd be nice if you could let us know which version of Atom you're running, OS, and if the relevant storage unit(s) is spinning rust or SSD.

**Comment by thomasjo** [comment] 2015-05-01 21:36
In addition, while this might not technically be a *large file*, #307 might be worth subscribing to. Specifically that issue is being addressed in https://github.com/atom/text-document, so you might want to follow that as well if you're interested.

**Comment by mnquintana** [comment] 2015-05-01 21:45
Also maybe related to #979?

**Comment by 50Wliu** [comment] 2015-05-01 22:29
I can't reproduce the slowness either on `0.197.0-570c424`.  Ubuntu 15.04, 4-year-old laptop with a HDD.

**Comment by mnquintana** [comment] 2015-05-01 22:31
@thomasjo @50Wliu Did you test with the formatted JSON file or the original one-line JSON file?

**Comment by thomasjo** [comment] 2015-05-01 22:33
> Did you test with the formatted JSON file or the original one-line JSON file?

Both. The one-liner does not cause any performance issues, but syntax highlighting breaks (as expected) due to the token limitation being hit.

**Comment by izuzak** [comment] 2015-09-11 15:38
I wasn't able to reproduce the slowness when opening either version. I did, however, observe a slight delay when editing the one-line version. I believe https://github.com/atom/atom/issues/979 already covers that since it contains comments which mention editing delays.

I'm going to close this since a few people haven't been able to reproduce and no more information was provided (see https://github.com/atom/atom/issues/6607#issuecomment-98242818). @sjamesmccarthy If you can reproduce this in Atom 1.0.11 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) and the problem isn't already covered by https://github.com/atom/atom/issues/979 -- let us know and try to provide [this information](https://atom.io/docs/latest/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler). :v:

**Closed by izuzak** 2015-09-11 15:38 UTC
Labels: more-information-needed, needs-reproduction
