### ISSUE TITLE
PCRE does triggers exception on UTF8 codes

### ISSUE THREAD

**Issue by ggl** [atom/atom#17005] opened 2018-03-21 14:36 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When one moves the cursor over code with UTF8 codes like \u00b7 atom triggers an exception.
![screen shot 2018-03-21 at 16 28 26](https://user-images.githubusercontent.com/3610557/37715686-52b904c2-2d25-11e8-98b6-fc81e1f4a6b9.png)

### Steps to Reproduce

1. Start Atom
2. Open a JavaScript file with unicode codes
3. Move the cursor over the code

**Expected behavior:** [What you expect to happen]

Should not trigger an exception.

**Actual behavior:** [What actually happens]

Triggers an exception.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time. 100%.

### Versions

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
OS X 10.10.5 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment] 2018-03-21 21:13
Thanks for contributing!

I was unable to reproduce using the steps that you outlined above. Can you verify that you are still seeing this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? If so, are you able to share a file that shows this behavior?

**Comment by rsese** [comment] 2018-03-21 21:18
Thanks for the report!  Looks like this is coming from `highlight-selected` - I see you opened https://github.com/richrace/highlight-selected/issues/167, thanks for doing that :+1:

Going to go ahead and close this issue since you opened https://github.com/richrace/highlight-selected/issues/167 but I'll also reference it in https://github.com/atom/superstring/issues/52 since I'm guessing they're at least related.

**Closed by rsese** 2018-03-21 21:18 UTC
Labels: more-information-needed

**Comment by rsese** [comment] 2018-03-21 21:26
Sorry I missed the live update @Arcanemagus - I can reproduce with `highlight-selected` as described in https://github.com/richrace/highlight-selected/issues/167:

1. In a JavaScript file paste `frag.appendChild(document.createTextNode('\u00A0'));`
2. Uncheck `Settings > Packages > highlight-selected > Only Highlight Whole Words`
3. Select the `\u`

The stack trace below isn't exactly the same as https://github.com/atom/superstring/issues/52 but they look related?

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.13.1


### Stack Trace

Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/superstring/index.js:246

Error: PCRE does not support \L, \l, \N{name}, \U, or \u
    at TextBuffer.findAllInRangeSync (/app.asar/node_modules/superstring/index.js:246:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1167:32)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1080:32)
    at TextEditor.scanInBufferRange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3378:73)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:151:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:136:10
    at Array.forEach (native)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:135:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:62:8
```
