### ISSUE TITLE
Uncaught Can't find text file

### ISSUE THREAD

**Issue by AntonKuts** [atom/atom#18977] opened 2019-03-12 17:34 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.0 x64
**Electron**: 2.0.18
**OS**: �������� Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find text file

```
At C:\Users\Super\AppData\Local\atom\app-1.35.0\resources\app\static\<embedded>:11

undefined
```

### Commands

```
  2x -2:55.2.0 core:paste (input.hidden-input)
     -2:48.6.0 core:save (input.hidden-input)
     -1:14.5.0 core:copy (input.hidden-input)
  2x -1:13.1.0 editor:newline (input.hidden-input)
     -1:12.3.0 core:paste (input.hidden-input)
     -1:09.0 core:copy (input.hidden-input)
     -1:04.9.0 core:paste (input.hidden-input)
  2x -1:03.1.0 core:backspace (input.hidden-input)
     -1:01.5.0 core:copy (input.hidden-input)
  2x -1:00.0 emmet:encode-decode-data-url (input.hidden-input)
  4x -0:40.9.0 core:move-right (input.hidden-input)
     -0:38.2.0 core:move-left (input.hidden-input)
  2x -0:36.4.0 core:move-right (input.hidden-input)
     -0:35.3.0 core:move-left (input.hidden-input)
     -0:33.6.0 core:paste (input.hidden-input)
     -0:32.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-paths 2.12.2 
color-picker 2.3.0 
emmet 2.4.3 
highlight-selected 0.14.0 
language-babel 2.85.0 
seti-ui 1.11.0 
```

**Comment by rsese** [comment] 2019-03-13 02:29
Thanks for contributing!

We noticed that this looks like a duplicate of issues like https://github.com/atom/atom/issues/18429 where it seems like the problem was narrowed down to https://atom.io/packages/emmet (/cc https://github.com/atom/atom/issues/18429#issuecomment-439216378).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-03-13 02:29 UTC

**Comment by AntonKuts** [comment] 2019-03-13 09:29
Ok
