### ISSUE TITLE
Can't launch atom on Mac after update 1.19.3 (LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.)

### ISSUE THREAD

**Issue by pjliddy** [atom/atom#15453] opened 2017-08-26 13:13 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After the latest update to atom (1.19.3), Atom will not launch. It returns an error: 

```
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.
```

The error appeared when I restarted my Mac and relaunched Atom.

Atom will not launch in safe mode, either.

I tried downloading the 1.19.2 and 1.19.3 .zip files to re-install but neither of them is un-zipping successfully. They have been trying for over an hour and appear frozen at about 40%.

### Steps to Reproduce

1. In terminal, enter `atom` or `atom --safe`

**Expected behavior:** [What you expect to happen]
Atom would launch

**Actual behavior:** [What actually happens]
Error: LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Atom 1.19.3
Mac OS X 10.12.6

### Additional Information
```
Process:               Atom [3811]
Path:                  /Applications/Atom.app/Contents/MacOS/Atom
Identifier:            com.github.atom
Version:               1.19.3 (1.19.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Atom [3811]
User ID:               501

Date/Time:             2017-08-26 08:59:49.095 -0400
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        C95297BC-6C47-9EFC-5303-9DB6A431AC2D


Time Awake Since Boot: 2500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

**Termination Reason:    DYLD, [0x1] Library missing**

Application Specific Information:
**dyld: launch, loading dependent libraries**

**Dyld Error Message:
  Library not loaded: @rpath/libnode.dylib
  Referenced from: /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found**

Binary Images:
       0x103525000 -        0x103525ff7 +com.github.atom (1.19.3 - 1.19.3) <CB63147A-C9DC-308B-8CA1-EE92A5042E8E> /Applications/Atom.app/Contents/MacOS/Atom
       0x10352e000 -        0x1071b3f73 +com.github.electron.framework (0) <02EEB879-495F-3A71-9D22-B9C1710D7DC4> /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x1077f9000 -        0x107813fff +com.github.Squirrel (1.0 - 1) <4C459C36-AFB6-3B8A-8FEC-76C192C17E30> /Applications/Atom.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x10783c000 -        0x10789fff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Applications/Atom.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x107919000 -        0x10792dfff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Applications/Atom.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x10d709000 -        0x10d746dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff7ac6a000 -     0x7fff7ac6afff  com.apple.Carbon (154 - 157) <69F403C7-F0CB-34E6-89B0-235CF4978C17> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff8125c000 -     0x7fff8125cfff  com.apple.quartzframework (1.5 - 21) <09455972-8A33-3D61-B193-BA7E7CF984CA> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff8125d000 -     0x7fff8145dfff  com.apple.QuartzCore (1.11 - 453.39.4) <A45AFBC4-87D4-3533-A0AC-1D6629C77984> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff819c4000 -     0x7fff81cc6ff7  com.apple.security (7.0 - 57740.60.18) <005E8C96-40B6-35E3-B58B-888A5F5957C2> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff81d3d000 -     0x7fff81d66fff  com.apple.securityinterface (10.0 - 55079.50.4) <C9B0E11A-362B-3C0D-8B2E-B06510BCE20A> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff8f915000 -     0x7fff8f916ffb  libSystem.B.dylib (1238.60.2) <F18AC1E7-C6F1-34B1-8069-BE571B3231D4> /usr/lib/libSystem.B.dylib
    0x7fff8fa4f000 -     0x7fff8faa5ff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib

Model: MacBookAir6,2, BootROM MBA61.0099.B53, 2 processors, Intel Core i7, 1.7 GHz, 8 GB, SMC 2.13f15
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.171.130.1a1)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Card Reader
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

```
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment] 2017-08-28 18:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3093. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-28 18:47 UTC
