### ISSUE TITLE
Cursor breaks when switching tabs

### ISSUE THREAD

**Issue by chbk** [atom/atom#8566] opened 2015-08-29 06:32 UTC
I'm using Atom 1.0.9 on OS X 10.10.5

I've noticed the cursor gets stuck as "default" when switching tabs with keyboard shortcuts.
This is how I get the bug:
- Open 2 tabs in a full screen window
- In the first tab, hover over your code: you get the text cursor
- Switch to the second tab with <kbd>cmd</kbd> <kbd>alt</kbd> <kbd>←</kbd> or <kbd>cmd</kbd> <kbd>alt</kbd> <kbd>→</kbd>
- In the second tab, hover over your code: you get the default cursor

The cursor doesn't change when clicking the text. It stays default until the tab title is clicked.

**Comment by chbk** [comment] 2015-10-23 15:22
This is still a problem on Atom 1.0.19

![1](https://cloud.githubusercontent.com/assets/7478535/10697085/7a4883f4-79aa-11e5-8502-7b0d19f9fbc0.gif)

**Comment by chbk** [comment] 2017-08-05 17:50
The bug doesn't appear on newer versions of macOS.

**Comment by rsese** [comment] 2017-08-08 23:26
Since it's not reproducible after an OS update, we'll go ahead and close this.

**Closed by rsese** 2017-08-08 23:26 UTC
Labels: needs-reproduction
