### ISSUE TITLE
Editor not responding when working with large files.

### ISSUE THREAD

**Issue by machinavn** [atom/atom#11894] opened 2016-06-03 18:17 UTC
I've been using atom for 5 months. And now when I try to do some task like beautify code, (~ 700 lines ), The editor seems very lagging It's not responding and I have to wait ~ 20s and click wait pop-up. It's also eat my CPU to 100%. Any ideas?

I'm running win7-64, lastest version Atom.

**Comment by Zireael07** [comment] 2016-06-03 18:22
I assume you meant atom-beautify, which is a plugin, report it on the plugin's repo.

**Comment by machinavn** [comment] 2016-06-03 18:30
I just tested again, I create an empty html file and copy ~ 1000 lines of code. And Editor's not responding again, I choose wait and after 5 sec, it crashed. 

Here's my task manager. Notice I only open 2 tabs Chrome.
![100 cpu](https://cloud.githubusercontent.com/assets/16027895/15788837/9beb4196-29f3-11e6-9104-8433ed1f9fc6.png)

And some information about my computer: 

![100 cpu](https://cloud.githubusercontent.com/assets/16027895/15788919/efa83faa-29f3-11e6-8c14-6fb9e80fdeba.png)

**Comment by machinavn** [comment] 2016-06-03 18:43
atom --version

Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

Here's a crash dump file.
Oh man I Zipped dump file but Github 's not accept zz -_-

**Comment by Zireael07** [comment] 2016-06-04 12:33
Convert zz to zip. Or save it as dmp.txt.

**Comment by danielle-mustillo** [comment] 2016-06-09 20:59
Same issue on Ubuntu 14.04. All plugins disabled and default theme (Atom Dark) used. Copy pasted 162K json into new file (so no syntax highlighting), got many prompts from Ubuntu that the window is unresponsive. Waiting about 1 minute (telling Ubuntu to keep waiting) seems to allow Atom to "catch up". CPU at 100% until the Atom window becomes responsive. Larger files seem to require more "Catch up" time. 

atom --version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by machinavn** [comment] 2016-06-18 10:22
Man this prob's been stalking me for weeks -_-

**Comment by trusktr** [comment] 2016-06-28 17:52
Tracking all these large-file issues in #12065.

**Comment by mnquintana** [comment] 2016-06-29 00:46
This seems like a duplicate of https://github.com/atom/atom/issues/8864 – let's keep the discussion going there.

**Closed by mnquintana** 2016-06-29 00:46 UTC

**Comment by krabbypattified** [comment] 2017-03-05 18:14
Hello from issue #12065. Atom Beta should fix this for many people.
