### ISSUE TITLE
Cannot type more than a single character

### ISSUE THREAD

**Issue by august** [atom/atom#7882] opened 2015-07-13 22:02 UTC
Mac OS
Version 1.0.2

Sometimes (not all the time), I double-click some text to select it, start typing or then hit DELETE and start typing. For some reason, it drops into a single-character edit mode, that lets me type only  single character. Subsequent characters replace the first one. I have to click out somewhere else on the page, then click back to do any real typing.

Again, this doesn't happen 100% of the time. It seems to be about 50%. It comes and goes, and I haven't been able to detect a pattern.

**Comment by helenemccarron** [comment] 2015-08-04 15:25
+1 
Experiencing this as well, especially when using the trackpad on Macbook pro. 
Clicking a specific location then deleting will result in all my characters being typed within the space of one character, each character replacing the next one. I have to click somewhere else, back again and I can start typing as normal. Escape doesn't work.

**Comment by batjko** [comment] 2015-08-04 19:53
Can you guys try atom in safe mode (`atom --safe`) and confirm whether the issue is gone then?

If so, I'm going to assume you have a community package installed that messes with keyboard input, such as Emmet for example. Try and disable that.

**Comment by Ben3eeE** [comment] 2016-12-15 15:41
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7882#issuecomment-127735119. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2016-12-15 15:41 UTC
Labels: more-information-needed, needs-reproduction
