### ISSUE TITLE
Still no ARM64 binaries?

### ISSUE THREAD

**Issue by pseudofunizer** [atom/atom#21142] opened 2020-08-02 14:35 UTC
If you're going to maintain that you're for "the 21st Century", you might want to put your money where your mouth is and start offering pre-compiled arm64/aarch64 binaries for Linux.

Otherwise, don't try.

**Comment by pseudofunizer** [comment] 2020-08-02 14:54
P.S. You've left out `npm` from your installation guide's build dependencies for Ubuntu. You might want to update that list. In Ubuntu (20.04LTS) It can be installed with:

`sudo apt install npm`

Otherwise, you'll get errors such as `Error: spawnSync npm ENOENT` upon running `./build` .

**Comment by pseudofunizer** [comment] 2020-08-02 15:05
... And, even with `npm` installed, the build fails on a Raspberry Pi 4B on a 64-bit Ubuntu 20.04LTS.

`code ELIFECYCLE` , `errno 1` - just like people have been complaining on your own user forums. 

https://discuss.atom.io/t/atom-arm64/76088/2

So, yeah, you might want to start offering that arm64 pre-built binary at some point. Will be glad to send you all the log files regarding the build attempt that are needed.

**Comment by pseudofunizer** [comment] 2020-08-02 15:21
I tried running what was suggested in those ELIFECYCLE errors, a.k.a. 

`npm cache clean --force`  and then `npm install` exposes at least one of the culprits; 

`WARNING: mksnapshot does not run on arm64.`

More detailed info:

```
$ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

$ npm install

> electron-mksnapshot@9.0.2 install /home/((user))/atom/script/node_modules/electron-mksnapshot
> node ./download-mksnapshot.js

WARNING: mksnapshot does not run on arm64. Download
  https://github.com/electron/electron/releases/download/v9.0.2/mksnapshot-v9.0.2-linux-arm64-x64.zip
  on a x64 linux OS to generate undefined snapshots.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN atom-build-scripts@ No repository field.
npm WARN atom-build-scripts@ No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-mksnapshot@9.0.2 install: `node ./download-mksnapshot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-mksnapshot@9.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/((user))/.npm/_logs/2020-08-02T15_07_24_086Z-debug.log

```

So, how's that 21st century rollin' on? Just askin'.

**Comment by jeff-hykin** [comment] 2020-08-02 21:20
I know it might be frustrating that it doesn't work, but why would you insult people who work for free, and then ask them for help? You are welcome to get it working for ARM, here are the relevant old comments you could find. Which can be summed up as Electron getting support (great), but it taking some extra effort to build Atom for ARM.
https://github.com/atom/atom/issues/14279#issuecomment-296839127
https://github.com/atom/atom/issues/7822


@pseudofunizer Have you tried following what the error messages told you to do?
> WARNING: mksnapshot does not run on arm64. 
**Download
  https://github.com/electron/electron/releases/download/v9.0.2/mksnapshot-v9.0.2-linux-arm64-x64.zip
  on a x64 linux OS to generate undefined snapshots.**

and 

> npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

I imagine ARM binaries will be better supported once Apple Silicon is in use

**Comment by Arcanemagus** [comment] 2020-08-05 06:36
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/7822. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-08-05 06:36 UTC

**Comment by jeff-hykin** [comment] 2020-08-05 12:55
Hey @Arcanemagus that issue you linked is locked so (unless I'm mistaken?) subscribing to it isn't going to do anything. Is there a duplicate issue that isn't locked/closed?

**Comment by lee-dohm** [comment] 2020-08-05 16:03
@pseudofunizer I can understand you're frustrated that we don't support your chosen platform. There are lots of potential platforms that we don't support with precompiled binaries. But that's the wonderful thing about open source, one person or even one team does what they can and then others can contribute, add on to that work, or even transform it completely.

However, your initial post is in violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. You may consider this an official warning.

**Comment by lee-dohm** [comment] 2020-08-05 16:04
@jeff-hykin Subscribing there is still the right thing because if we do decide to start work on supporting ARM that's where we'll announce the effort.

**Comment by jeff-hykin** [comment] 2020-08-05 18:09
@lee-dohm thanks for the clarification 👍

**Comment by pseudofunizer** [comment] 2020-09-16 18:23
> 
> 
> @pseudofunizer I can understand you're frustrated that we don't support your chosen platform. There are lots of potential platforms that we don't support with precompiled binaries. But that's the wonderful thing about open source, one person or even one team does what they can and then others can contribute, add on to that work, or even transform it completely.
> 
> However, your initial post is in violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. You may consider this an official warning.

Why was it considered an insult if I called out the fact that your **official** claim is that the editor is for "the 21st century" (this is your official tagline, btw, not mine) -- Apple just moved to solely ARM-based chips and ARM got sold for billions to Nvidia. 

I admit the part that I was blunt in my approach, but it was due to the fact that year after year and decade after decade, there's no cohesion in the dev world. Me getting an "official warning" for pointing out a fault in your rationale is highly illogical -- and funny, for that matter. Yeah, it's not like anybody uses ARM64 as a dev platform or anything... :D lol.

Thank you for your time, though. And, for the warning, it's always heartwarming to open up my mailbox and see who has remembered me with tender warmth! :o)
