### ISSUE TITLE
CPU pegged by atom/helper - all actions running slowly

### ISSUE THREAD

**Issue by slconley** [atom/atom#14877] opened 2017-06-22 22:59 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

Problem seems to occur during any activity at all.  Steps below give a quick example.

[atom-issue.zip](https://github.com/atom/atom/files/1096367/atom-issue.zip)

1. Start atom
2. Open any two files in single pane
3. Switch tabs between these two files

**Expected behavior:**  Switching should be very quick

**Actual behavior:** Switching is very slow

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2017-06-23 03:50
Thanks for the report!  Can you share what operating system you're running?

I can't reproduce with your steps but if you can clarify that would be great.  Using these 2 tests file, random Atom JavaScript files /cc https://github.com/atom/atom/blob/c1c0e7e921b7125aa8afbb652b238694d3b3cd31/src/atom-paths.js and https://github.com/atom/atom/blob/c1c0e7e921b7125aa8afbb652b238694d3b3cd31/src/auto-update-manager.js I tried:

1. Start Atom with `atom --safe`
2. Open the first file I mentioned above with <kbd>cmd-o</kbd>
3. Open the second file I mentioned above with <kbd>cmd-o</kbd>
4. Click on the 2 file tabs back and forth for a minute or so.

Can you confirm if you can reproduce with these steps or if I have your steps wrong?

Also, the CPU profile you shared is empty, I think that's a bug that should be fixed as of the 1.19 beta.  Would you be able to share a screenshot of the CPU profile or do you happen to have the beta installed as well?

Lastly, is the behavior exactly the same when you ran in safe mode or the same?

**Comment by kieckhafer** [comment] 2017-06-23 18:24
I'm also experience this, in both safe and regular modes.

In addition to tab switching, it's literally everything I do. When I click, there is a .5s+ delay. When I type, there is a .5+s delay before it registers. Anything I do has a very noticeable delay on it.

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by danfuzz** [comment] 2017-06-23 19:21
I am seeing something like this as well, and I believe I can narrow my problem specifically to sluggishness when files are being modified/written (e.g. in my case a build is being performed) under a project directory being managed in an Atom window: If I have two different projects open in different windows and only one of them is having its files written, just the one "active" project window becomes sluggish.

Quitting and restarting Atom seems to mitigate the problem, but it ultimately slows down again. I'm not quite sure what the triggering condition is.

I normally have "Hide VCS Ignored Files" turned _off_ in the "Tree View" settings. That is, I like having the greyed out `.git` and `out` (my project's built-output directory) available for occasional browsing. Maybe this is related?

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

MacBook Pro (2015)
macOS Sierra 10.12.5
```

**Comment by amckay1** [comment] 2017-06-23 20:41
Same issue here, typing is either super delayed or freezes for ~5 to 10 seconds before catching up.  Occurs immediately after opening the application.

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.11.0

MacBook Air (13-inch, Mid 2011)
1.8 GHz Intel Core i7
4 GB 1333 MHz DDR3
macOS Sierra 10.12.5

**Comment by rsese** [comment] 2017-06-23 22:30
Just to rule out the GitHub package which is new to stable as of 1.18.0, can people seeing this behavior confirm if they still see the sluggishness after temporarily disabling the GitHub package?

**Comment by amckay1** [comment] 2017-06-23 22:32
Sorry, just deleted 1.18 and reinstalled 1.17.2: not having any issues, also refused to install "Atom Helper" when prompted.

**Comment by danfuzz** [comment] 2017-06-27 00:28
>Just to rule out the GitHub package which is new to stable as of 1.18.0, can people seeing this behavior confirm if they still see the sluggishness after temporarily disabling the GitHub package?

@rsese: I disabled the GitHub package this morning and restarted Atom. By the end of the day, I still hadn't seen the sluggishness come back. No firm conclusion yet, but my experience is certainly consistent with the hypothesis that that package bears some responsibility for the observed behavior.

**Comment by kieckhafer** [comment] 2017-06-27 00:38
Disabled the GitHub package a few hours ago and haven't had any slowdown yet.

Prior to disabling, the app would start to slow down within 10-15 minutes of booting up. Seems like that package might be the culprit.

**Comment by kieckhafer** [comment] 2017-06-27 19:48
^^^ a day later and still running smoothly, must be that package

**Comment by danfuzz** [comment] 2017-06-27 22:17
>a day later and still running smoothly

Likewise.

**Comment by RCD-Y** [comment] 2017-06-28 14:06
Same issue here. Typing is almost unbearable before disabling the GitHub package.

**Comment by brittany-johnson** [comment] 2017-06-28 19:41
I was also having the same issue. Disabling the GitHub packages worked perfectly!

**Comment by kraegpoeth** [comment] 2017-07-31 11:04
I just discovered that Atom Helper is choking the CPU with 100% usage (about every 5. second) even when scrolling, editing text, etc, making it more or less so slow that it was unusable.
I had set `git config --global core.editor atom` and once i changed this to vim the issue disappeared completely with normal cpu load and atom running smooth again.

Hope this helps someone!

**Comment by rsese** [comment] 2017-08-09 01:57
Thanks again for your issue @slconley - we haven't received a response to our question in this comment https://github.com/atom/atom/issues/14877#issuecomment-310564151 so with only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

---

If anyone else is still having a problem that's separate from the GitHub package, feel free to open a new issue and completely fill out the issue template so we can take a look.

**Closed by rsese** 2017-08-09 01:57 UTC
Labels: more-information-needed

**Comment by haykam821** [comment] 2017-09-10 00:03
I also disabled GitHub and Open on GitHub and the problem instantly went away.

**Comment by chronosis** [comment] 2017-11-30 18:58
After some debugging based on the feedback above, it appears that the issue is being caused on older/slower machines in the atom/github plugin.  The problematic code is the 'onSick' function of the `lib/worker-manager.js` -- https://github.com/atom/github/blob/06577d0d3caf101c69c488252f77c0501541bfbb/lib/worker-manager.js#L83

The problem occurs because when one of the worker threads is slow and then is reported as sick. This can be observed occurring because when in debug mode you can observe the 'Sick Worker Detected...' messages in the console.   The plugin code then increases the worker count limit and spawns a new worker thread.  The problem occurs because garbage collection has not had a chance to clean up the existing slow(sick) thread. It then increase in the worker count occurs and then spawns a new worker. Because the computer is becoming slower due to existing workers, the new worker then gets sick as well hangs in memory and causes the whole process to balloon memory and CPU usage.

Disabling the atom/github plugin prevents the issue from occurring and prevents atom from becoming sluggish as time progresses.

**Comment by kieckhafer** [comment] 2017-11-30 19:12
@chronosis Disabling the plugin is the solution I've found to work, I don't agree it's older / slower machines only though.

I'm on a 2016 MacBook Pro, 16GB of Ram, 2.7Ghz processor and I'm seeing the issue.

**Comment by anton-mladenov** [comment] 2018-05-07 16:53
Hi, 
just disabled both Github plugins and still experience the issue. My CPU constantly is running between 89 and 99% (sometimes even 115% for half a second). 
I also use in on a new 2016 Macbook Pro machine.

**Comment by rsese** [comment] 2018-05-08 23:31
@anton-mladenov if you can reproduce in safe mode, please open a new issue and fill out the issue template and we'll take a look.
