### ISSUE TITLE
Focus of atom after opening file (Windows 7) 

### ISSUE THREAD

**Issue by christophfroehlich** [atom/atom#6649] opened 2015-05-05 07:56 UTC
Windows 7, atom already opened with the window in the background. 
When I open a file via the explorer, the symbol in the task bar is blinking but atom doesn't come to the front.
Is this a wanted behavior? 

(I couldn't find any existing issue. If this is the case, please let me know)

**Comment by mnquintana** [comment] 2015-05-05 10:26
Duplicate of #6614 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-05 10:26 UTC
Labels: duplicate

**Comment by christophfroehlich** [comment] 2015-05-05 11:52
Thanks!
