### ISSUE TITLE
Update broke JavaScript syntax Highlighting

### ISSUE THREAD

**Issue by bexo94** [atom/atom#18481] opened 2018-11-22 17:28 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I just updated my Atom editor to version 1.32.2 on osx 10.13.6 and the highlighting of my javascript code broke.
The Todo's are not highlighted like before. All JsDoc comments are just gray. And my variables have no color highlighting.
When I checked the developer tools the classes for variables are missing:
<img width="879" alt="bildschirmfoto 2018-11-22 um 18 26 29" src="https://user-images.githubusercontent.com/11523616/48916834-2a71e080-ee84-11e8-9a89-7b0d38dc185f.png">

This is just a line a code like this:
`const componentName = componentSplit[3]`

I tried running the newest beta version of Atom, the bug still is there.
I also tried downgrading to an old version, but then I can't open the Projects because of an Error

**Comment by rsese** [comment] 2018-11-27 03:50
Thanks for the report - this is related to Tree-sitter getting enabled by default in 1.32.0:

http://blog.atom.io/2018/10/23/atom-1-32.html#tree-sitter

And I believe the 3 issues you mentioned have been reported:

> The Todo's are not highlighted like before.

https://github.com/atom/language-todo/issues/82 if you want to subscribe.

> All JsDoc comments are just gray.

https://github.com/atom/language-javascript/issues/600 - the fix will be in 1.33.0 /cc https://github.com/atom/language-javascript/issues/600#issuecomment-439229717.

> And my variables have no color highlighting.
...
> This is just a line a code like this:
> `const componentName = componentSplit[3]`

I believe this is a duplicate of https://github.com/atom/language-javascript/issues/597, see Max's comment /cc https://github.com/atom/language-javascript/issues/597#issuecomment-423629661 in particular.  If I'm mis-understanding and you're talking about a different issue, feel free to open a new issue in https://github.com/atom/language-javascript with the template filled out and we'll take another look.

**Closed by rsese** 2018-11-27 03:50 UTC
