### ISSUE TITLE
Softwrap works improperly when we use multi-byte language.

### ISSUE THREAD

**Issue by xelion8** [atom/atom#8550] opened 2015-08-28 07:38 UTC
![atom_error_softwrap](https://cloud.githubusercontent.com/assets/5965265/9541440/116e1e94-4da3-11e5-8102-22e134f1c1a3.png)

Softwrapping works not properly when we use multi-byte language. There are 5~6 more characters in right side. (It works fine with English.)

**Comment by izuzak** [comment] 2015-08-28 07:42
Thanks for the report -- I think this is a duplicate of https://github.com/atom/atom/issues/1783, so closing in favor of that. Let me know if I misunderstood.

**Closed by izuzak** 2015-08-28 07:42 UTC
