### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Carthorn** [atom/atom#5273] opened 2015-01-27 15:40 UTC
A lot of files are really just .xml files, but end in different extensions. This is just one example

It would be nice if
A) If on AutoDetect, check the the first line if it contains <?xml ....> then parse as xml language
B) Associate an extension with a particular language

Someone might have already created a package for it, but haven't found one yet.

Thanks!

**Comment by mnquintana** [comment] 2015-01-27 15:45
@lee-dohm Were you working on something like this with [atom-linguist](https://github.com/lee-dohm/atom-linguist)?

**Comment by 50Wliu** [comment] 2015-01-27 15:53
Duplicate of atom/first-mate#17.

**Closed by 50Wliu** 2015-01-27 15:53 UTC

**Comment by lee-dohm** [comment] 2015-01-28 00:14
@mnquintana Yes, and I'm still working on it on the weekends. I haven't been able to find time during the week though.
