### ISSUE TITLE
Slow project-wide searches should be cancelable

### ISSUE THREAD

**Issue by eppsilon** [atom/atom#11651] opened 2016-04-29 16:15 UTC
### Description

Searches using Find in Project can be very slow if there are many files and the search term is too vague. Unfortunately, an in-progress search can't be stopped without closing the editor. There should be a button next to the progress spinner that cancels the search.

### Versions

Atom 1.7.3 on OS X 10.11.4.

**Comment by 50Wliu** [comment] 2016-04-29 17:54
This is a duplicate of atom/find-and-replace#310 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-29 17:54 UTC
