### ISSUE TITLE
Can't change language specific tab length (Beta 1.25.0)

### ISSUE THREAD

**Issue by Skeeve** [atom/atom#16879] opened 2018-03-04 14:53 UTC
### Description
Trying out the beta release I noticed I cannot change the tab length of any language.

### Steps to Reproduce

1. Search a language package (tried perl and java)
2. Click on tab-length
3. Just for a second "2" is shown, then it's removed and replaced by the default text.
4. Also when you change it in config.cson, it's always removed.

**Expected behavior:** tab ength should be changable

**Actual behavior:** tab legth is always removed

**Reproduces how often:** 100%

### Versions

$ atom-beta -v
Atom    : 1.25.0-beta2
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by Arcanemagus** [comment] 2018-03-04 23:58
Duplicate of https://github.com/atom/atom/issues/16817, with a fix already in place in https://github.com/atom/settings-view/pull/1047 😉.

**Comment by lee-dohm** [comment] 2018-03-05 04:06
Thanks @Arcanemagus :bow: Closing as duplicate :+1:

**Closed by lee-dohm** 2018-03-05 04:06 UTC
