### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by snerdish** [atom/atom#7522] opened 2015-06-29 00:12 UTC
[Enter steps to reproduce below:]

1.Right click on svn working directory
2.Blam

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\rob.kearey\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  2x -1:43.9.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:18.3.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
color-picker, v2.0.7
go-runtime, v0.2.0
language-ansible, v0.1.3
language-rust, v0.4.3
linter, v1.1.0
linter-ansible-lint, v0.0.7
linter-golinter, v0.1.0
linter-rust, v0.1.0
svn, v0.0.6

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-06-29 01:29
Duplicate of #6548, please subscribe there for updates.

**Closed by 50Wliu** 2015-06-29 01:29 UTC
