### ISSUE TITLE
Eclipse like perspective

### ISSUE THREAD

**Issue by tejainece** [atom/atom#11570] opened 2016-04-22 08:56 UTC
i am missing an important feature that i used to enjoy in Eclipse: the perspectives.

Right now, a lot of plugins are being activated for no reason. It is not easy to disable some plugins in certain projects.

This would be solved by having perspective feature. Plugins can be activated and deactivated when perspectives are changed.

**Comment by arcticicestudio** [comment] 2016-04-22 09:02
I think this can be clustered with #11424 to allow a customized "package profile" to configure enable/disable specific packages.

**Comment by tejainece** [comment] 2016-04-22 09:40
Grouping a bunch of packages is not a good solution. I think it should be based on a "Perspective" framework. And a way to activate and dis-activate packages based on current perspective will be very good.

One can have different perspectives for same language: Code, Debug, Coverage, etc.

**Comment by bric3** [comment] 2016-04-25 15:24
IntelliJ is more interesting on this part, it has a _scoped_ views

<img width="535" alt="screen shot 2016-04-25 at 17 24 06" src="https://cloud.githubusercontent.com/assets/803621/14788946/86dfbaf0-0b0a-11e6-97d6-bdbdd7b15f34.png">

**Comment by lee-dohm** [comment] 2016-04-29 01:57
This is a duplicate of https://github.com/atom/atom/issues/11424. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-04-29 01:57 UTC

**Comment by tejainece** [comment] 2016-04-29 11:18
It is not duplicate. The other one wants to group packages and enable/disable them based on the programming language.

Perspectives are more powerful!

1. It remembers the layout of the panels
2. Same programming language have more than 1 perspective: Debug, Code, Lint, etc
3. When a programming language is selected, list of supported perspectives are shown in a dropdown box
4. The process has to tap into Activation/Deactivation process of a package

**Comment by lee-dohm** [comment] 2016-04-29 20:33
They're the same basic concept and we would only implement one or the other, so there's no point in keeping two separate issues open. Please add your ideas to the other Issue.
