### ISSUE TITLE
PHP Syntax Coloring Issue

### ISSUE THREAD

**Issue by syamsoul** [atom/atom#16241] opened 2017-11-20 09:08 UTC
After amperson (&), if I write php code, the color change to brown all the way down to the end of file...

`<a href="login.php?status=logout&cloud_id=<?=$variable?>">Logout</a>`

It will be no problem if I remove the php tag ($variable)

Please refer picture below..

![image](https://user-images.githubusercontent.com/30229150/33010426-66eccc9a-ce15-11e7-9cbe-cc7d2049cb7b.png)

**Comment by rsese** [comment] 2017-11-20 19:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-html/issues/141 which was closed a while ago but a couple of people have mentioned that it seems to be an issue in Atom 1.22.  You can subscribe there for updates if you'd like, it's possible we'll re-open that one or a new issue will be created.

As a side note, it's super helpful for us if you can fill out the issue template when creating issues (e.g. we don't know what operating system or version of Atom you're running) so if you can use the template for future issues, we would appreciate it :v:

--- 

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-20 19:38 UTC
