### ISSUE TITLE
French Keyboard Layout can't wrote } or ].

### ISSUE THREAD

**Issue by moanatari** [atom/atom#11891] opened 2016-06-03 13:31 UTC
### Description

It is impossible to write the symbols "}" and "]" with a French keyboard.
Im sad. :cry: 

French Keyboard Layout : http://f.tqn.com/y/french/1/S/m/H/2/frenchkeyboard.jpg

### Steps to Reproduce

1. Switch to french layout
2. Ctrl + Alt + =
3. Wrap your code instead of writing a "}".

**Expected behavior:** [What you expected to happen]
}
**Actual behavior:** [What actually happened]
Code wrap
### Versions
1.7.4
Windows 7

Tanks ! :smile: 

Alex in :heart: with Atom.

**Comment by 50Wliu** [comment] 2016-06-03 16:11
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.  You may also want to try installing the [keyboard-localization](https://atom.io/packages/keyboard-localization) package.

**Closed by 50Wliu** 2016-06-03 16:11 UTC
