### ISSUE TITLE
Adding vim-like tabs to Atom

### ISSUE THREAD

**Issue by c10b10** [atom/atom#11349] opened 2016-04-02 08:09 UTC
I realize that this would take a major effort to implement, but I'd like to ask you to [give it five minutes](https://signalvnoise.com/posts/3124-give-it-five-minutes) instead of rejecting it out of the get go. Please thoughtfully consider this:

I propose implementing Vim-style pane splitting / tab management in Atom.

In Vim, all pane splits are contained to a single tab. Changing the tab results in a having a different split configuration on screen which allows one to organize more efficient.

Imagine I have the following arrangement where I work on the redux data flow of a react app:

<img width="1370" alt="screen shot 2016-04-02 at 10 50 45" src="https://cloud.githubusercontent.com/assets/306633/14225138/e0be934a-f8c0-11e5-9857-1a5be0040e1f.png">

Imagine now, that I want to start tweaking css in two different files, without disturbing the current pane split setup.

<img width="1427" alt="screen shot 2016-04-02 at 11 03 53" src="https://cloud.githubusercontent.com/assets/306633/14225195/a20647a4-f8c2-11e5-92e9-e6164cd2c022.png">

There's no easy way to do this in the same Atom window. The reason for this fact is that in Atom, tabs are created for each pane, instead of for each pane container. 

In Vim, creating a new tab would generate a fresh workspace with a fresh pane splitting context.

**When we code, we conceptually split work into logically separate sections of the project, each of which involves working with multiple files at once: Data flow, Styling, UI components, etc.**

Atom's current tab model sadly makes it difficult to map this way of working to the workspace. I think we would all benefit immensely from changing it.

**Comment by paradox460** [comment] 2016-04-02 10:21
Could borrow Opera/Vivaldi's concept of "tab stacks". That way each stack could have its own layout, and still hold multiple buffers within a single pane

**Comment by vassyz** [comment] 2016-04-07 16:13
I know this is not a solution, but what I do is open several full screen windows and switch between desktop spaces (on Mac). On the second Atom window you have to use "Add Project Folder", otherwise you'll just switch focus to the initial window.

**Comment by c10b10** [comment] 2016-04-07 16:40
@vassyz I sometimes do that too, but it quickly becomes inconvenient when you have to do that each time I need to switch work to a separate part of the project.

Also, that renders autocomplete less potent (since autocomplete only takes into account open files in the current window), and there's not way make atom remember all windows with all their tabs for a single project. 

I think the key argument for this change I'm proposing is that we need to be able to separate work on different parts of the same project using a single instance of our text editor.

**Comment by rugginoso** [comment] 2016-04-23 17:43
Completely agree with @c10b10 analysis. I'll love to see this in atom (and it actually is the only reason for which atom isn't my primary editor)

**Comment by mnquintana** [comment] 2016-04-24 21:56
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/672 though – let's move the conversation there.

**Closed by mnquintana** 2016-04-24 21:56 UTC
Labels: enhancement
