### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.34.0\ 개인취미'

### ISSUE THREAD

**Issue by MilkBomb11** [atom/atom#18686] opened 2019-01-13 02:37 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\chan1\AppData\Local\atom\app-1.34.0\ 개인취미'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\chan1\AppData\Local\atom\app-1.34.0\ 개인취미'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:911621)
    at TreeView.t.exports.TreeView.onDrop (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:917375)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:892215)
```

### Commands

```
     -2:01.6.0 intentions:highlight (input.hidden-input)
     -2:01.5.0 editor:select-to-beginning-of-word (input.hidden-input)
     -2:00.2.0 core:backspace (input.hidden-input)
     -1:59.2.0 intentions:highlight (input.hidden-input)
     -1:59.1.0 core:save (input.hidden-input)
     -1:52.8.0 intentions:highlight (input.hidden-input)
     -1:52.6.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:51.5.0 intentions:highlight (input.hidden-input)
     -1:51.2.0 core:save (input.hidden-input)
     -1:33.5.0 tree-view:remove (span.name.icon.icon-file-text)
     -0:26.7.0 tree-view:add-file (div.header.list-item.project-root-header)
     -0:22.9.0 core:confirm (input.hidden-input)
     -0:21.8.0 intentions:highlight (input.hidden-input)
     -0:21.7.0 core:paste (input.hidden-input)
     -0:17.7.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:12.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-glsl 0.2.3 
autocomplete-love 0.4.0 
busy-signal 2.0.0 
hyperclick 0.1.5 
hyperclick-love 0.6.0 
intentions 1.1.5 
language-glsl 2.0.4 
language-lua 0.9.11 
linter 2.2.0 
linter-luaparse 0.2.0 
linter-ui-default 1.7.1 
love-ide 0.17.0 
script 3.18.1 
tool-bar 1.1.11 
```
I can't move files into folders

**Comment by rsese** [comment] 2019-01-14 20:54
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-01-14 20:54 UTC
