### ISSUE TITLE
Uncaught Error: toString failed

### ISSUE THREAD

**Issue by kasikasi2014** [atom/atom#11554] opened 2016-04-21 02:44 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: toString failed

```
At buffer.js:378

Error: toString failed
    at Buffer.toString (buffer.js:378:11)
    at Object.fs.readFileSync (fs.js:496:33)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at File.module.exports.File.readSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:266:36)
    at File.module.exports.File.getDigestSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:167:14)
    at TextBuffer.module.exports.TextBuffer.serialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:231:68)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/project.js:137:27
    at Array.map (native)
    at Project.module.exports.Project.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:135:41)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:769:31)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:984:27
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2016-04-21 20:47
What were you doing at the time of the exception?

**Comment by tntim96** [comment] 2016-04-26 11:19
I got directed to here when opening a log file of size 288339043 bytes.

**Comment by d-Pixie** [comment] 2016-05-31 14:41
I got the same error trying to load a log file of 755,3 MB.

**Comment by lukec11** [comment] 2016-06-04 23:25
I got this error trying to load a .sh file of 289669397 bytes

**Comment by kurtismullins** [comment] 2016-07-19 20:49
+1 -- The file I am reading is huge (570M JSON File). Even Chrome has trouble opening it, although it doesn't crash and burn.

**Comment by kaftw** [comment] 2016-09-10 22:47
+1 840MB CSV

**Comment by manthis** [comment] 2016-09-18 17:56
Crashes when trying to read a > 2GB file or > 10GB file. That would be nice to have a fix. If I can help, let me kow.

**Comment by QuentinDela** [comment] 2016-11-03 10:53
+1

**Comment by fracalo** [comment] 2016-12-02 10:47
Same issue for a 124k js build , even in safe mode.

**Comment by a-abella** [comment] 2016-12-22 16:09
I've experienced hangs on a text file only 4.7MB in size, with 39,000 lines (unix find output). It loaded with time, but any form of manipulation (particularly, a find and replace) caused the window to become completely unresponsive. Version 1.13.0-beta8.

**Comment by 50Wliu** [comment] 2016-12-22 17:46
@a-abella Large file performance should be greatly increased in Atom 1.14, as long as the file does not also contain very long lines.  Though your issue is unrelated to this one.

**Comment by joedaniels29** [comment] 2017-05-02 18:48
Still seeing this in 1.16.

**Comment by pietrovismara** [comment] 2017-05-19 09:01
Is anyone even working on this issue?  
This should be a primary matter.
I got to the point where, having atom open on a project folder, if a script creates a big file in the folder or changes it atom will freeze and hang until i'm forced to close it. 

All this without even opening the file. This problem seriously compromise the usability of this editor.

**Comment by suryaavala** [comment] 2017-05-22 00:13
I think the problem is not only with opening large files (in size), but also with files (of any size) containing long single lines. Atom either crashes or gets hung when I try to open files like the ones described above.

Example: I have a file of ~800KB and one of its lines is of 279768 characters length. Trying to edit/save the file is extremely slow (in the order of 30-45sec per operation). Other text editors (text wrangler) seem to deal with files like this without any problem. 

Atom Version: 1.18.0-beta0

**Comment by 50Wliu** [comment] 2017-05-23 05:15
I _think_ #14435 will fix at the very least this uncaught exception. @maxbrunsfeld?

**Comment by maxbrunsfeld** [comment] 2017-05-23 13:58
Yes, there are several separate issues that can cause poor behavior with large files, some in Atom core, and some in packages. #14435 will fix a very fundamental issue relating to large files and will ship in either Atom 1.19 or 1.20.

**Comment by 0cd** [comment] 2017-06-05 21:19
Suggestion: There could be a setting called "Editor for large files" in Atom, that'd make atom automatically open files larger than it can handle (or larger than a value defined by the user) in a different text editor. That'll save users the hassle of checking file size before they can decide whether to use Atom or another editor for that file, or trying to open it in Atom, failing and then switching to a different editor

**Closed** 2017-06-08 23:50 UTC
Labels: bug, uncaught-exception
