### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by saroar** [atom/atom#14531] opened 2017-05-20 17:23 UTC
MacBook Pro (Retina, 15-inch, Late 2013)
http://prntscr.com/fa3frk

macOS Seiria 10.12.4

**Comment by saroar** [comment] 2017-05-20 17:24
I try this its not working 
Apple > System Preferences... > Displays > Color tab and selecting AppleRGB as my color profile (from Adobe RGB (1998)).

**Comment by saroar** [comment] 2017-05-20 17:27
I also try this vim ~/.bash_profile
(or nano ~/.bash_profile if you're not a fan of vim)

Append the alias:

# added to fix Electron gpu tiles with macOS 10.12
alias atom="atom --enable-gpu-rasterization"
Save and close the file, then reload your profile:

source ~/.bash_profile

**Comment by saroar** [comment] 2017-05-20 17:29
Atom version 1.17.0

**Comment by 50Wliu** [comment] 2017-05-20 19:03
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12634. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-20 19:03 UTC
