### ISSUE TITLE
Unable to create windows installer when building; path and file name are too long.

### ISSUE THREAD

**Issue by jenroper** [atom/atom#15629] opened 2017-09-12 23:53 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Running the script with the --create-windows-installer flag fails after throwing a PathTooLongException.

Output of script
```
Node:   v6.10.3
Npm:    v5.4.1
Python: v2.7.13
Installing script dependencies
prebuild-install info begin Prebuild-install version 2.2.2
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v1.7.2-node-v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\Jen\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v48-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\Jen\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v48-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\atom\script\node_modules\leveldown\build\Release\leveldown.node
prebuild-install info unpack required C:\atom\script\node_modules\leveldown\build\Release\leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!
Installing apm
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1.windows.1
visual studio 2015
Installing modules done
Installing atom-dark-syntax@0.28.0 done
Installing atom-dark-ui@0.53.0 done
Installing atom-light-syntax@0.29.0 done
Installing atom-light-ui@0.46.0 done
Installing base16-tomorrow-dark-theme@1.5.0 done
Installing base16-tomorrow-light-theme@1.5.0 done
Installing one-dark-ui@1.10.8 done
Installing one-light-ui@1.10.8 done
Installing one-dark-syntax@1.8.0 done
Installing one-light-syntax@1.8.0 done
Installing solarized-dark-syntax@1.1.2 done
Installing solarized-light-syntax@1.1.2 done
Installing about@1.7.8 done
Installing archive-view@0.63.3 done
Installing autocomplete-atom-api@0.10.3 done
Installing autocomplete-css@0.17.3 done
Installing autocomplete-html@0.8.1 done
Installing autocomplete-plus@2.35.9 done
Installing autocomplete-snippets@1.11.1 done
Installing autoflow@0.29.0 done
Installing autosave@0.24.3 done
Installing background-tips@0.27.1 done
Installing bookmarks@0.44.4 done
Installing bracket-matcher@0.87.3 done
Installing command-palette@0.41.1 done
Installing dalek@0.2.1 done
Installing deprecation-cop@0.56.9 done
Installing dev-live-reload@0.47.1 done
Installing encoding-selector@0.23.5 done
Installing exception-reporting@0.41.4 done
Installing find-and-replace@0.212.2 done
Installing fuzzy-finder@1.5.8 done
Installing github@0.5.1 done
Installing git-diff@1.3.6 done
Installing go-to-line@0.32.1 done
Installing grammar-selector@0.49.5 done
Installing image-view@0.62.3 done
Installing incompatible-packages@0.27.3 done
Installing keybinding-resolver@0.38.0 done
Installing line-ending-selector@0.7.3 done
Installing link@0.31.3 done
Installing markdown-preview@0.159.13 done
Installing metrics@1.2.6 done
Installing notifications@0.69.2 done
Installing open-on-github@1.2.1 done
Installing package-generator@1.1.1 done
Installing settings-view@0.251.8 done
Installing snippets@1.1.4 done
Installing spell-check@0.72.2 done
Installing status-bar@1.8.13 done
Installing styleguide@0.49.6 done
Installing symbols-view@0.118.0 done
Installing tabs@0.107.2 done
Installing timecop@0.36.0 done
Installing tree-view@0.217.9 done
Installing update-package-dependencies@0.12.0 done
Installing welcome@0.36.5 done
Installing whitespace@0.37.2 done
Installing wrap-guide@0.40.2 done
Installing language-c@0.58.1 done
Installing language-clojure@0.22.4 done
Installing language-coffee-script@0.49.0 done
Installing language-csharp@0.14.2 done
Installing language-css@0.42.5 done
Installing language-gfm@0.90.1 done
Installing language-git@0.19.1 done
Installing language-go@0.44.2 done
Installing language-html@0.47.7 done
Installing language-hyperlink@0.16.2 done
Installing language-java@0.27.4 done
Installing language-javascript@0.127.3 done
Installing language-json@0.19.1 done
Installing language-less@0.33.0 done
Installing language-make@0.22.3 done
Installing language-mustache@0.14.1 done
Installing language-objective-c@0.15.1 done
Installing language-perl@0.37.0 done
Installing language-php@0.41.0 done
Installing language-property-list@0.9.1 done
Installing language-python@0.45.4 done
Installing language-ruby@0.71.3 done
Installing language-ruby-on-rails@0.25.2 done
Installing language-sass@0.61.1 done
Installing language-shellscript@0.25.3 done
Installing language-source@0.9.0 done
Installing language-sql@0.25.8 done
Installing language-text@0.7.3 done
Installing language-todo@0.29.2 done
Installing language-toml@0.18.1 done
Installing language-typescript@0.1.0 done
Installing language-xml@0.35.2 done
Installing language-yaml@0.30.2 done
Wrote Dependencies Fingerprint: C:\atom\node_modules\.dependencies-fingerprint e862d356110563b40130b6f7f40569a7b4f5e7aa
Copying assets to C:\atom\out\app
Transpiling packages with custom transpiler configurations in C:\atom\out\app
 transpiling for package github
Installing modules done
Transpiling Babel paths in C:\atom\out\app
Transpiling CoffeeScript paths in C:\atom\out\app
Transpiling CSON paths in C:\atom\out\app
Transpiling PEG.js paths in C:\atom\out\app
Generating module cache for C:\atom\out\app
Generating pre-built less cache in C:\atom\out\app\less-compile-cache
Generating metadata for C:\atom\out\app\package.json
Generating API docs at C:\atom\docs\output\atom-api.json
Skipping symbol dumping because minidump is not supported on Windows
Running electron-packager on C:\atom\out\app with app name "atom"
Downloading electron-v1.6.9-win32-x64.zip
[============================================>] 100.0% of 52.4 MB (6.55 MB/s)
Packaging app for platform win32 x64 using electron v1.6.9
Copying non-ASAR resources to C:\atom\out\Atom x64\resources
Writing LICENSE.md to C:\atom\out\Atom x64\resources
Application bundle created at C:\atom\out\Atom x64
Generating snapshot script at "C:\atom\out\startup.js" (54)
Verifying if snapshot can be executed via `mksnapshot`
Generating startup blob at "C:\atom\out\snapshot_blob.bin"
Moving generated startup blob into "C:\atom\out\Atom x64\snapshot_blob.bin"
Skipping code-signing. Specify the --code-sign option to perform code-signing
Creating Windows Installer for C:\atom\out\Atom x64
Deleting downloaded nupkg for previous version at C:/atom/out/atom-1.20.0-full.nupkg to prevent it from being stored as an artifact
Error: Failed with exit code: 4294967295
Output:
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Squirrel.DeltaPackageBuilder.createDeltaForSingleFile(FileInfo targetFile, DirectoryInfo workingDirectory, Dictionary`2 baseFileListing)
   at Squirrel.DeltaPackageBuilder.CreateDeltaPackage(ReleasePackage basePackage, ReleasePackage newPackage, String outputFile)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

  at ChildProcess.proc.on.code (C:\atom\script\node_modules\electron-winstaller\lib\spawn-promise.js:62:16)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:886:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```

### Steps to Reproduce

These steps assume all prerequisite software is installed (git, node.js, python, etc.) 

1. Open PowerShell
2. cd C:\
3. git clone https://github.com/atom/atom.git
4. cd atom
5. script\build --create-windows-installer

**Expected behavior:** A window installer gets created

**Actual behavior:** An exception is thrown and a windows installer is not created.

**Reproduces how often:**  100% of the time.  

### Versions

Windows 10 64-bit.  All versions are listed in script output above.

### Additional Information

This was a fresh build.  All of my pertinent software versions are listed.  Prior to trying to build atom from the source, I downloaded and installed atom.  I'm not sure if having an existing installation would cause issues with building a windows installer for atom, but that seems unlikely.  This looks like a bug in one of the build scripts.

**Comment by rsese** [comment] 2017-09-13 18:12
Thanks for taking the time to contribute!

Based on the error and error code, looks like a duplicate of https://github.com/atom/atom/issues/14264 I think?  Can you give the mentioned workaround a try /cc https://github.com/atom/atom/issues/14264#issuecomment-303870182?
 
---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14264. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-13 18:12 UTC

**Comment by jenroper** [comment] 2017-09-13 19:00
Thank you for your help.  What search terms did you use?  I tried to see if this was a duplicate issue but had no luck finding it.

**Comment by jenroper** [comment] 2017-09-13 19:35
Actually, I tried the workaround listed in [#14264.](https://github.com/atom/atom/issues/14264), and it did not work. 
 ```
PS C:\atom> set SQUIRREL_TEMP=c:\squirreltemp
PS C:\atom> script\build --create-windows-installer
Node:   v6.10.3
Npm:    v5.3.0
Python: v2.7.13
Installing script dependencies
Installing apm
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1.windows.1
visual studio 2015
Installing modules done
Wrote Dependencies Fingerprint: C:\atom\node_modules\.dependencies-fingerprint e862d356110563b40130b6f7f40569a7b4f5e7aa
Cleaning C:\atom\out
Copying assets to C:\atom\out\app
Transpiling packages with custom transpiler configurations in C:\atom\out\app
 transpiling for package github
Installing modules done
Transpiling Babel paths in C:\atom\out\app
Transpiling CoffeeScript paths in C:\atom\out\app
Transpiling CSON paths in C:\atom\out\app
Transpiling PEG.js paths in C:\atom\out\app
Generating module cache for C:\atom\out\app
Generating pre-built less cache in C:\atom\out\app\less-compile-cache
Generating metadata for C:\atom\out\app\package.json
Generating API docs at C:\atom\docs\output\atom-api.json
Skipping symbol dumping because minidump is not supported on Windows
Running electron-packager on C:\atom\out\app with app name "atom"
Packaging app for platform win32 x64 using electron v1.6.9
Copying non-ASAR resources to C:\atom\out\Atom x64\resources
Writing LICENSE.md to C:\atom\out\Atom x64\resources
Application bundle created at C:\atom\out\Atom x64

Verifying if snapshot can be executed via `mksnapshot`
Generating startup blob at "C:\atom\out\snapshot_blob.bin"
Moving generated startup blob into "C:\atom\out\Atom x64\snapshot_blob.bin"
Skipping code-signing. Specify the --code-sign option to perform code-signing
Creating Windows Installer for C:\atom\out\Atom x64
Deleting downloaded nupkg for previous version at C:/atom/out/atom-1.20.0-full.nupkg to prevent it from being stored as an artifact
Error: Failed with exit code: 4294967295
Output:
System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Squirrel.ReleasePackage.<>c__DisplayClass14_0.<extractZipWithEscaping>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Squirrel.ReleasePackage.<>c__DisplayClass14_0.<extractZipWithEscaping>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---


  at ChildProcess.proc.on.code (C:\atom\script\node_modules\electron-winstaller\lib\spawn-promise.js:62:16)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:886:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by rsese** [comment] 2017-09-14 07:12
> What search terms did you use?

I don't quite remember but I either searched for "Failed with exit code: 4294967295":

https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=is%3Aissue%20Failed%20with%20exit%20code%3A%204294967295%20

Or I just remembered that issue.  In my searches I also get rid of the default `is:open` so I can see both open and closed issues.

> Actually, I tried the workaround listed in #14264, and it did not work.

Hmmm, did you also try what was mentioned in https://github.com/atom/atom/issues/14264#issuecomment-314793503?  Looks like they said setting the variable from the command line didn't work and they had to define a global environment variable.

**Comment by jenroper** [comment] 2017-09-14 15:57
Setting SQUIRREL_TEMP as a system environment variable seems to have work.  Thank you for your help.

**Comment by Hillery21** [comment] 2017-09-24 12:57
I used long path tool for this problem . Some says it doesn't work but it works fine for me. Try using it . I hope to hear your experience about it. :) I hope it helps :D
