### ISSUE TITLE
Uncaught Error: Patch does not apply

### ISSUE THREAD

**Issue by cznq** [atom/atom#16284] opened 2017-11-28 06:38 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Patch does not apply

```
At C:\Users\Administrator\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\helpers.js:68

Error: Patch does not apply
    at exports.patchFromChanges (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/helpers.js:68:17)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1692:68)
    at later (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -2:49.1.0 core:move-up (input.hidden-input)
  2x -2:48.1.0 core:move-down (input.hidden-input)
     -2:46.7.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -2:46.7.0 editor:newline (input.hidden-input)
     -2:42.4.0 core:move-down (input.hidden-input)
     -2:42.1.0 autocomplete-plus:confirm (input.hidden-input)
     -2:42.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:37.3.0 autocomplete-plus:confirm (input.hidden-input)
  3x -2:28.8.0 core:move-right (input.hidden-input)
     -2:27.5.0 core:move-down (input.hidden-input)
  3x -2:10.7.0 core:backspace (input.hidden-input)
     -0:17.6.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-bootstrap3 1.2.12 
atom-chs-menu 1.0.0 
atom-css-comb 3.3.1 
atom-less 0.1.10 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autoprefixer 3.7.1 
cson 2.0.1 
css-snippets 1.1.0 
emmet 2.4.3 
file-type-icons 1.3.4 
file-types 0.5.5 
jquery-snippets 11.0.0 
language-vue 0.23.1 
less-autocompile 1.0.0 
linter 1.11.23 
linter-js-standard 3.9.1 
linter-jshint 3.1.5 
linter-less 2.6.0 
linter-sass-lint 1.7.4 
minimap 4.29.3 
simplified-chinese-menu 5.3.4 
```

**Comment by 50Wliu** [comment] 2017-11-28 17:30
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15827. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-11-28 17:30 UTC
