### ISSUE TITLE
[⌘] Command key broken sometimes [macOS]

### ISSUE THREAD

**Issue by damianobarbati** [atom/atom#15533] opened 2017-09-03 11:54 UTC
I have no idea how to reproduce or which are the steps to reproduce this: from time to time the command key (⌘) simply stops working.
Nearly impossible to work like this: I cleaned up the plugins, the atom preferences, freshly reinstalled everything and updated everything.

```
$ atom --version
Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
$ apm list --installed --bare
busy-signal@1.4.3
docblockr@0.11.0
intentions@1.1.5
linter@2.2.0
linter-eslint@8.2.1
linter-ui-default@1.6.8
markdown-pdf@2.0.3
markdown-preview-plus@2.4.10
pdf-view@0.59.0
project-manager@3.3.5

imac:repmemo damz$ 
```

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode <== *I can't use Atom without plugins!*
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

**Comment by rsese** [comment] 2017-09-05 20:26
Can you share a screenshot of what the [keybinding resolver](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings) shows when <kbd>⌘</kbd> stops working and you're pressing <kbd>⌘</kbd>?  Also, I'm assuming the <kbd>⌘</kbd> otherwise works on your computer in general and with other apps when it stops working in Atom?

**Comment by damianobarbati** [comment] 2017-09-05 21:14
>I'm assuming the ⌘ otherwise works on your computer in general and with other apps when it stops working in Atom
Correct assumption: I didn't know about the keybind resolver, I'll be posting the output as soon as the behaviour happens again! 
Thanks @rsese for helping me.

**Comment by damianobarbati** [comment] 2017-09-07 21:06
@rsese I managed to screenshot the keybinding resolver! 
It just says: `shift - cmd` or `cmd`.

Notice:
1- when I try to save with `cmd+s` it doesn't report `cms-s`.
In another parallel window/instance of Atom where cmd is working I get `cms-s` and `core:save`
2- arrows are working if pressed with `cmd`: I get `editor:move-to-the-end-of-screen-line`

So for sure `cmd+s` and `cmd+shift+left/right` combinations gets broken somehow.

<img width="2048" alt="screen shot 2017-09-07 at 22 56 53" src="https://user-images.githubusercontent.com/2225869/30185151-9e68b47e-9420-11e7-828e-767479c706b7.png">

EDIT: even if I go to File and click Save nothing happens! Not just related to `cmd` key.

**Comment by pjrebsch** [comment] 2017-09-08 18:33
I stumbled upon this issue on accident, but I, too, have experienced this using a MacBook Pro and Atom version `1.19.4 x64`.

I have not been able to identify a pattern for what triggers it. I use `cmd` + `left/right arrow` a lot to highlight words. What usually happens is that will stop working suddenly, so I go to try to save the file with `cmd` + `s` (because I'm afraid that Atom might be in the process of crashing and I don't want to lose any of my work) and that doesn't work either, so I'll go up to `File > Save` and that doesn't do anything either. Other text editing functions seem to work properly, such as typing characters normally or highlighting by character with `shift` + `arrow`.

This occurs to me maybe 1-3 times a week when I'm doing a lot of development work. When it does occur it doesn't last long for me (maybe 10-15 seconds), so it isn't long enough for me to really intentionally investigate what else may not be working or what the state of Atom is at the time.

**Comment by rsese** [comment] 2017-09-08 19:28
Hmmm, this seems like a tough one to test in safe mode since it happens intermittently - @pjrebsch can you shared your installed packages?  Wondering if you have anything in common with @damianobarbati:

```
apm list --installed
```

**Comment by pjrebsch** [comment] 2017-09-08 20:54
@rsese Here are my installed packages:

```
$ apm list --installed
Community Packages (3) /Users/patrickrebsch/.atom/packages
├── file-icons@2.1.11
├── language-haml@0.25.1
└── language-nginx@0.8.0
```

Since my last comment I have updated Atom to `1.19.7 x64` to see if the problem will occur again with the newest version.

**Comment by damianobarbati** [comment] 2017-09-08 21:50
@pjrebsch yes that's exactly what I'm experiencing now.
But it lasts for 10-15s then back to normal, then back again: very hard to work with it :\

@rsese thanks for helping!

**Comment by damianobarbati** [comment] 2017-10-03 08:41
@rsese I just found out it is a "focus" problem! Somehow the tab loose focus just for the "cmd", how can this be? 
When the bug happens, everything but cmd works fine: I need to click the tab I'm working on and "cmd" starts working, like if it lost focus... but just for cmd :|

**Comment by rsese** [comment] 2017-10-03 20:23
Do you remember what you were doing around the time things stopped working?  E.g. were you using the command palette or fuzzy finder?  Or find and replace?  If we can get to reproducible steps, that would be super helpful.

**Comment by rsese** [comment] 2018-03-16 22:39
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15533#issuecomment-333966881. With only the information that is currently in the issue, we don't have enough information to take action.  I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-03-16 22:39 UTC
Labels: more-information-needed

**Comment by pjrebsch** [comment] 2018-03-19 15:09
By the way, I haven't re-experienced this issue for months, so it may have been resolved indirectly by an update.
