### ISSUE TITLE
Overlapping text when cutting folds

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#16289] opened 2017-11-29 00:02 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Occasionally when there are a lot of folds, cutting folds results in overlapping text such as the following.
![folds-overlapping-text](https://user-images.githubusercontent.com/2766036/33350721-9598be46-d4a0-11e7-943a-d19387b62286.png)

I've managed to reproduce it twice now on https://github.com/atom/language-php/blob/3e45569d8fb3af6747f6e4208b16d17deb577b97/spec/php-spec.coffee while moving heredoc and nowdoc specs into their own `describe`s.

### Steps to Reproduce

1. Open https://github.com/atom/language-php/blob/3e45569d8fb3af6747f6e4208b16d17deb577b97/spec/php-spec.coffee
2. Fold everything and then unfold the top-level describe
3. Try cutting and pasting some folds until it reproduces?

**Expected behavior:** Text to appear in order

**Actual behavior:** Text occasionally overlaps

**Reproduces how often:** Unknown, I'm guessing ~10-20%.

### Versions

```
Atom    : 1.24.0-dev-f76a7a6ed
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by sybrew** [comment] 2018-01-09 03:34
I'm also experiencing this in any language. 
Re-opening the file doesn't work so I'd assume this can be easily reproduced.

![image](https://user-images.githubusercontent.com/7662236/34703799-4c1285d4-f4f5-11e7-9954-9eb2b90215fe.png)

It seems that the CSS transform property is overstating its welcome:

![image](https://user-images.githubusercontent.com/7662236/34703986-4bda3c46-f4f6-11e7-87f0-c727f07102cb.png)

**Comment by Ben3eeE** [comment] 2018-01-10 11:55
This seems to happen for edits that cause the horizontal scrollbar to appear.

/cc: https://github.com/atom/atom/pull/15831 because it might fix this issue. We should test to see if it is fixed by that PR and add test coverage for this bug as well.

@sybrew Do you make edits that cause the horizontal scrollbar to appear when reproducing this? If not can you please open a new issue and fill out the issue template?

---

Recorded this in 1.23-beta. Forgot if I was in safe mode or not but I reproduced 100% with these steps:

![that double line thing again](https://user-images.githubusercontent.com/1058982/34771320-6d68ee3e-f604-11e7-98eb-cb3d9e8520a1.gif)

**Closed** 2018-02-15 22:32 UTC
Labels: bug, editor-rendering, triaged
