### ISSUE TITLE
Auto-update for plugins 

### ISSUE THREAD

**Issue by jarrodek** [atom/atom#13128] opened 2016-11-02 12:06 UTC
Allow auto updates for plugins by either selecting plugins that will be allowed to update automatically in the background or allowing all installed plugins to auto-update.

The auto-update should be performed (as is right now) in the background but some indication that plugins are now updating should be visible in the main UI (like a progress bar with name of the plugin that is being updated.

**Steps which explain the enhancement**

1. Application has auto-update plugin option set to true
2. Plugins are installed automatically as soon as new versions are discovered
3. A notification (like a status message) is displayed in the main UI to indicate upgrade process
4. User can stop auto-update that is performed at the moment if s/he don't like the update

**Current and suggested behavior**

Consider Android use case. In first few version users had to agree and take an action on every update. It was the worst update UX I've ever seen. With platform development they decided to add auto-update option for selected applications with option to enable auto-update for all apps. For years now, in Android, applications that don't need new permissions are auto-updated by default.

The same problem now has Atom. I have many plugins installed to enhance the editor and increase productivity. However, right now I'm starting my every day at work from updating plugins and then in the evening second time at home. Every day. It would be very beneficial to the users if there were an option to enable auto-update for plugins so they don't need to care about it anymore (as probably most of them don't care right now but they forced to do so).

**Why would the enhancement be useful to most users**

You may perform a user research and ask them if they care about what version of the plugin is currently installed and if they would like to have automatic update. I feel that the most may answer no for the first one and yes to second one. 
It should increase productivity by not being distracted by plugins updates. It also increase confidence that the software installed in plugins directory is always up to date.

[List some other text editors or applications where this enhancement exists]
Not sure about that. 

**Atom Version:** It's not version related
**OS and Version:** It's not OS related

**Comment by thomasjo** [comment] 2016-11-02 12:42
This is a duplicate of #6897, so I'm closing this, but please post this as a comment in that issue since you've provided lots of good input here 🙇

**Closed by thomasjo** 2016-11-02 12:42 UTC

**Comment by Equinox** [comment] 2016-11-02 13:19
There's also [this gem](https://atom.io/packages/auto-update-plus) (the most updated out of the forks from what I can see) that works perfectly, albeit Atom handling this by itself would be a great improvement also.
