### ISSUE TITLE
Function parameter is not syntax highlighted in python

### ISSUE THREAD

**Issue by Interdictor** [atom/atom#18360] opened 2018-10-30 10:39 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom no longer show a special highlight syntax for the parameters of the methods. Their css scope has changed to be considered generic text.

In previous versions

### Steps to Reproduce

1. [First Step]
  Create a new python file
2. [Second Step]
  Define a function with an argument

**Expected behavior:** [What you expect to happen]
  The argument shows is colored in a different way than regular code

**Actual behavior:** [What actually happens]

  It has the same color than regular code

### Versions

Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

---

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 2.7.10
git 2.17.1

--

MacOs 10.14 (18A391)

### Additional Information

With the browser inspector I can see that the argument doesn't have any special css rules to highlight it:

![screenshot 2018-10-30 at 11 35 30](https://user-images.githubusercontent.com/15923542/47712433-fb2ad380-dc37-11e8-9b2c-92bec6f6899d.png)

**Comment by Ben3eeE** [comment] 2018-10-30 10:59
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-python/issues/281. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-10-30 10:59 UTC
