### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by Superpencil** [atom/atom#7897] opened 2015-07-15 00:36 UTC
I love atom, but the RTL support is lacking, not sure if this is just me, could be a problem with webkit instead.

To replicate, throw the following into a YML file in Atom, put the cursor halfway in either of the Arabic sentences, and hit backspace.

Expected: The character RIGHT of the cursor be deleted as we are going RTL
Seen: Cursor picks the identical opposite end of the line and deletes there instead

Example with numerals instead:
Line:                            `123456789`
Place cursor:               `1234567|89`
Hit backspace result:   `134567|89`
Expected:                    `1234567|9`
The corrosponding opposite end of the line is edited.

```YML
ar:
  shared_metatag:
    description: "Import from US online stores"
  guide:
    title: دليل فيشيزفاست
    h1: دليلك للتعرف على عالم التسوق عبر الإنترنت
```

**Comment by 50Wliu** [comment] 2015-07-15 01:39
Hey there @Superpencil, this seems to be a duplicate of #1849 - can you please subscribe there instead?  Thanks.

**Closed by 50Wliu** 2015-07-15 01:39 UTC

**Comment by Superpencil** [comment] 2015-07-15 09:20
Thanks!
