### ISSUE TITLE
Redesign top bar

### ISSUE THREAD

**Issue by Risengan** [atom/atom#12758] opened 2016-09-22 17:42 UTC
Before :
![before](https://cloud.githubusercontent.com/assets/11879201/18759403/a1f63a04-80fc-11e6-9f9c-4ff3754e895c.png)
![before 2](https://cloud.githubusercontent.com/assets/11879201/18759405/a5de2e60-80fc-11e6-88f3-78c8ed826ab0.png)

After :
![after](https://cloud.githubusercontent.com/assets/11879201/18759411/ae8be20a-80fc-11e6-84d3-833ca37aad93.png)
![after 2](https://cloud.githubusercontent.com/assets/11879201/18759418/b0b56c40-80fc-11e6-95ea-4bc1ac29e793.png)

**Comment by 50Wliu** [comment] 2016-09-22 18:38
This is a duplicate of #4599 - feel free to subscribe there for updates.

In the future, please **completely** fill out the provided issue template.

**Closed by 50Wliu** 2016-09-22 18:38 UTC
