### ISSUE TITLE
Go to beginning of line doesn't work with soft wrapped lines

### ISSUE THREAD

**Issue by Nokel81** [atom/atom#14345] opened 2017-05-03 19:22 UTC
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When on a soft wrapped line pressing "Home" on windows brings the cursor to the start of the text but pressing it again does not move the cursor (and especially the view) to the beginning of the line

### Steps to Reproduce

1. Have a line that atom will soft wrap
2. Have the cursor on the soft wrapped line with the view scrolled somewhat away from the left side
3. Press the Home key twice, the cursor will move to the start of the wrapped code and the view will go to only just beyond that

**Expected behavior:** 
The view to move all the way to the left side and or the cursor to move the left as well

**Actual behavior:** 
Nothing, the cursor and view stay at the end of the displayed text

**Reproduces how often:** 
100%

### Versions
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by rsese** [comment] 2017-05-03 19:39
> When on a soft wrapped line pressing "Home" on windows brings the cursor to the start of the text but pressing it again does not move the cursor (and especially the view) to the beginning of the line

Thanks for the report @Nokel81 :v:  So it looks like you're reporting 2 things:

1. Pressing <kbd>Home</kbd> twice doesn't take you to the beginning of a soft wrapped line.
2. The view doesn't move like you expect either, you mention you expect "The view to move all the way to the left side".

For (1), that's expected behavior and is basically a duplicate of https://github.com/atom/atom/issues/14294.   If you'd like <kbd>Home</kbd> to move to the beginning of the entire physical/buffer line rather than the soft wrapped line, you can map <kbd>Home</kbd> to `editor: move-to-beginning-of-line`.

For (2), I'm not quite sure what you mean with your second step for steps to reproduce:

> 2. Have the cursor on the soft wrapped line with the view scrolled somewhat away from the left side

Can you share a screenshot that shows what you mean when you say:

> with the view scrolled somewhat away from the left side

**Comment by Nokel81** [comment] 2017-05-03 20:07
![atom_fgif](https://cloud.githubusercontent.com/assets/8225332/25679194/6755426e-301a-11e7-821d-c1914324d61b.gif)

Here is a visual example, every time the cursor moves not by the mouse I am pressing the "Home" key

**Comment by rsese** [comment] 2017-05-03 23:14
Ohh ok gotcha, thanks for the GIF - that looks related to the behavior of what the <kbd>Home</kbd> key is mapped to and the fact that you're on a soft-wrapped line.  If you map <kbd>Home</kbd> to `editor: move-to-beginning-of-line` like I mentioned above, I think you'll have the behavior you want in general (you also won't have to press <kbd>Home</kbd> twice).  So just add this to your keymaps file:

```
`atom-text-editor`:
  'home': 'editor:move-to-beginning-of-line'
```

I'm going to go ahead and close as a dupe of #14294 but let me know if I'm mis-understanding anything.

**Closed by rsese** 2017-05-03 23:14 UTC
Labels: more-information-needed
