### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by agstew** [atom/atom#16179] opened 2017-11-13 23:36 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\Allan\AppData\Local\atom\app-1.22.0\resources\app\src\text-editor-component.js:646

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:646:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:643:43)
    at TextEditorComponent.renderContent (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:586:18)
    at TextEditorComponent.renderScrollContainer (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:561:18)
    at TextEditorComponent.render (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:506:20)
    at Object.updateSync (~/AppData/Local/atom/app-1.22.0/resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.22.0/resources/app/src/text-editor-component.js:1538:59)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
docblockr 0.13.2 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
expand-region 0.4.0 
file-icons 2.1.13 
git-control 0.9.0 
git-plus 7.10.0 
git-time-machine 1.5.9 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-shorcuts-react 2.1.0 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-babel 2.78.0 
language-patch 1.2.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
local-history 4.3.1 
markdown-preview-plus 2.4.16 
merge-conflicts 1.4.5 
open-html-in-browser 0.2.1 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
project-plus 1.0.0 
re-re-re-react 3.0.0 
split-diff 1.5.1 
todo-show 2.1.0 
xatom-debug 1.6.11 
xatom-debug-chrome 0.7.4 
xatom-debug-nodejs 0.9.3 
```

**Comment by rsese** [comment] 2017-11-14 21:14
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by ethamitc** [comment] 2017-12-07 01:44
Steps to reproduce:
1. Create a .log file
2. have that .log file open in Atom
3. switch to a different file in Atom (so the .log file isnt visible)
4. have a script write to that file
5. go back into that .log file
thats how it happened to meh, i dont know about the otha guy tho!

**Comment by Arcanemagus** [comment] 2018-02-02 06:08
@rsese Here are a few more issues with this same error. The error reporter is blaming `linter-ui-default` because it's the last file in the stack trace but these are the same bugs:
https://github.com/steelbrain/linter-ui-default/issues/468
https://github.com/steelbrain/linter-ui-default/issues/469
https://github.com/steelbrain/linter-ui-default/issues/470

Similar issues to this were fixed by @maxbrunsfeld in https://github.com/atom/atom/pull/15051, released in Atom v1.20.0 but this set seems to be a slightly different trigger.

Unfortunately as with the issues referenced from #15051 the issue is notoriously hard to replicate, but doesn't seem to be tied to a specific OS as this issue is from Windows while the others I just linked are macOS and "Arch Linux".

**Comment by rsese** [comment] 2018-02-08 20:26
Thanks @Arcanemagus :bow:

Hopefully we'll get a report with consistent repro steps 🤞 

@ethamitc do those steps you shared happen to be reproducible on your end or was it just a one time thing?

**Comment by CodyORourke** [comment] 2018-02-21 21:38
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:650

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:650:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:647:43)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:590:18)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:565:18)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:510:20)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1550:59)
```

### Commands

```
     -9:58.6.0 core:confirm (input.hidden-input)
     -9:12.6.0 find-and-replace:show (input.hidden-input)
     -9:11.1.0 core:confirm (input.hidden-input)
     -3:45 find-and-replace:show (input.hidden-input)
     -3:41.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-html-preview 0.2.5 
atom-wrap-in-tag 0.6.0 
color-picker 2.2.5 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
highlight-selected 0.13.1 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
mjml-preview 1.4.0 
pigments 0.40.2 
sync-settings 0.8.4 
tag 0.5.0 
```

**Comment by revelt** [comment] 2018-02-22 21:52
I can't replicate @ethamitc instructions :(

- I created an empty `.log`, in one different tests, in one test - using Atom, in another test - using `touch`. Then in both tests, same steps:
- Then opened it on active tab.
- Then switched to different tab showing the file of the same-level. 
- Then wrote to the `.log` using `echo "zzz"  >> .log`
- Then switched back to Atom
- Then activated the tab with `.log`

All fine.

Not that it denies existence of this bug, but it only proves it's a sneaky-one. Let's gather more info about the nature of the script that's writing to the file and also exact timing, if possible. Also, I see @agstew is on Windoze (I'm on Mac), maybe it's a platform specific bug? Did anybody succeed in recreating @ethamitc steps on Windows?

**Comment by rsese** [comment] 2018-02-23 21:58
Thanks for giving it a try @revelt :+1:

> Did anybody succeed in recreating @ethamitc steps on Windows?

I was unable to reproduce on Windows 10 with 1.24.0 using your steps.

**Comment by jimmyadaro** [comment] 2018-03-01 17:29
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:650

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:650:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:647:43)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:590:18)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:565:18)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:510:20)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1550:59)
```

### Commands

```
     -0:38.9.0 editor:consolidate-selections (input.hidden-input)
     -0:38.9.0 core:cancel (input.hidden-input)
     -0:37.9.0 editor:consolidate-selections (input.hidden-input)
     -0:37.9.0 core:cancel (input.hidden-input)
     -0:37.7.0 editor:consolidate-selections (input.hidden-input)
     -0:37.7.0 core:cancel (input.hidden-input)
     -0:37.5.0 editor:consolidate-selections (input.hidden-input)
     -0:37.5.0 core:cancel (input.hidden-input)
     -0:35.6.0 editor:consolidate-selections (input.hidden-input)
     -0:35.6.0 core:cancel (input.hidden-input)
     -0:35.3.0 editor:consolidate-selections (input.hidden-input)
     -0:35.3.0 core:cancel (input.hidden-input)
     -0:34 editor:consolidate-selections (input.hidden-input)
     -0:34 core:cancel (input.hidden-input)
     -0:32 editor:consolidate-selections (input.hidden-input)
     -0:32 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-bracket-highlight 0.3.2 
auto-update-packages 1.0.1 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.17 
file-templates 0.2.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-htaccess 0.2.0 
less-than-slash 0.18.0 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-jscs 4.1.3 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
package-sync 1.1.0 
pigments 0.40.2 
sass-autocompile 0.13.5 
teletype 0.9.0 
uglify 1.3.1 
```

**Comment by lifelogic** [comment] 2018-03-07 09:23
I can't tell how to reproduce it, but I can tell you one thing that appeared to resolve the issue: I zoomed out. Usually, I keep my window zoomed (cmd plus) to about 16 to 18pt font, due to vision problems.

On a hunch based on some of the stuff I saw in the stack trace, I just zoomed out to a more normal size (8pt or so), and it was fine.

I had been totally locked out of editing a particular file, since editing it seemed to trigger the error every time, which ruined that tab, making it uneditable (insertion point caret doesn't move, errors keep popping up in rapid succession).  Zooming out seemed to completely resolve it.

**Comment by Ben3eeE** [comment] 2018-03-20 08:54
I'm interested to see if anyone is running into this issue when using Atom 1.26, currently in beta. We fixed a rendering issue for edits that changed the horizontal scrollbar visibility. Changing font size like @lifelogic mentioned in their comment could also have changed the horizontal scrollbar visibility.

**Comment by darkn3rd** [comment] 2018-05-17 17:50
I got this issue with 1.27.0. x64, all I did with click on "Show Invisibles".

**Comment by rsese** [comment] 2018-05-17 20:33
Thanks @darkn3rd - based on the stacktrace I think that error is more related to the other issue you commented on https://github.com/atom/atom/issues/16394.

**Comment by blurHY** [comment] 2018-06-21 07:07
[Enter steps to reproduce:]

1. Open markdown-preview-plus preview pane
2. Copy some text from preview pane.
3. Search it.

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: win10
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At D:\Atom x64\resources\app\src\text-editor-component.js:663

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (D:/Atom x64/resources/app/src/text-editor-component.js:663:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (D:/Atom x64/resources/app/src/text-editor-component.js:660:43)
    at TextEditorComponent.renderContent (D:/Atom x64/resources/app/src/text-editor-component.js:601:18)
    at TextEditorComponent.renderScrollContainer (D:/Atom x64/resources/app/src/text-editor-component.js:577:18)
    at TextEditorComponent.render (D:/Atom x64/resources/app/src/text-editor-component.js:522:20)
    at Object.updateSync (D:/Atom x64/resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (D:/Atom x64/resources/app/src/text-editor-component.js:392:16)
    at TextEditorComponent.updateSync (D:/Atom x64/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didShow (D:/Atom x64/resources/app/src/text-editor-component.js:1471:18)
    at TextEditorComponent.didFocus (D:/Atom x64/resources/app/src/text-editor-component.js:1495:35)
    at HTMLElement.addEventListener (/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:164:16)
    at Function.module.exports.Emitter.simpleDispatch (D:/Atom x64/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (D:/Atom x64/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Pane.setActiveItem (D:/Atom x64/resources/app/src/pane.js:443:26)
    at Pane.activateItem (D:/Atom x64/resources/app/src/pane.js:583:18)
    at TabBarView.module.exports.TabBarView.onClick (D:/Atom x64/resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
     -4:54.1.0 intentions:highlight (input.hidden-input)
     -4:54 core:undo (input.hidden-input)
     -4:52.2.0 core:backspace (input.hidden-input)
     -4:51.6.0 markdown-img-paste:paste (input.hidden-input)
     -4:51 core:undo (input.hidden-input)
     -4:50.3.0 intentions:highlight (input.hidden-input)
     -4:50.1.0 core:undo (input.hidden-input)
     -4:47.3.0 core:backspace (input.hidden-input)
     -4:31.3.0 markdown-img-paste:paste (input.hidden-input)
  2x -4:27.1.0 core:backspace (input.hidden-input)
     -4:19.3.0 core:confirm (input.hidden-input)
     -4:12.9.0 core:copy (input.hidden-input)
     -4:07.1.0 intentions:highlight (input.hidden-input)
     -4:07.0 find-and-replace:show (input.hidden-input)
     -2:43.5.0 core:confirm (input.hidden-input)
  3x -2:38.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.12.1 
atom-html-preview 0.2.5 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-asciidoc 0.1.2 
autocomplete-html-entities 0.2.0 
autocomplete-javascript 0.0.2 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.3.0 
convert-file-encoding 0.1.0 
css-color-name 0.4.0 
css-snippets 1.1.0 
emmet 2.4.3 
gl-light-syntax 3.0.0 
google-translate-modal 1.2.2 
intentions 1.1.5 
language-asciidoc 1.11.0 
language-assembly 0.7.2 
language-batch 0.4.0 
language-markdown 0.26.0 
language-svg 0.9.2 
latex 0.50.0 
linter 2.2.0 
linter-ui-default 1.7.1 
lorem 1.5.0 
markdown-assistant 0.2.0 
markdown-image-paste 2.5.2 
markdown-pdf 2.2.0 
markdown-preview-enhanced 0.15.6 
markdown-preview-plus 3.3.1 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
pdf-view 0.70.0 
pigments 0.40.2 
react 0.18.0 
react-snippets 1.1.1 
simplified-chinese-menu 5.3.5 
solarized-one-light-ui 1.12.0 
svg-preview 0.12.1 
tidy-markdown 3.0.1 
tool-bar 1.1.7 
tool-bar-markdown-writer 0.3.1 
```

**Comment by ethamitc** [comment] 2018-06-29 03:30
@revelt sorry for the late response, you daid you did mt steps, but I wrote to it using a nodejs scripy, not echo.

**Closed** 2018-10-02 14:16 UTC
Labels: more-information-needed, uncaught-exception
