### ISSUE TITLE
Atom Beta - Install Shell Commands doesn't work (or does it...)

### ISSUE THREAD

**Issue by monkpit** [atom/atom#11573] opened 2016-04-22 13:40 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Using the menu option "Install Shell Commands" in the Atom Beta reports `The shell commands 'atom' and 'apm' are installed.` But they are sneaky commands - `atom` and `apm` will not do anything from a terminal... Because they are called `atom-beta` and `apm-beta`. Secrets and lies!

### Steps to Reproduce

1. Install Atom Beta (I'm on OSX, with no Atom non-Beta installed).
2. Open Atom Beta, click the menu option `Atom > Install Shell Commands`.
3. Atom displays an alert stating "Commands installed. The shell commands 'atom' and 'apm' are installed."
4. Open a fresh terminal and type `atom` or `apm`. The command is not found.

**Expected behavior:** I expect the commands displayed in the alert to work verbatim. My preference would be for the alert window text to read `atom-beta` and `apm-beta`.

**Actual behavior:** The commands need to be suffixed with `-beta`, or they will not work and you probably won't know why...

### Versions

OSX 10.11.4
```
$ atom-beta --version
Atom    : 1.8.0-beta2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm-beta --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.2
```

**Comment by lee-dohm** [comment] 2016-04-22 16:17
This is a duplicate of https://github.com/atom/atom/issues/9361. You may want to subscribe there for updates. Thanks for reporting!

**Closed by lee-dohm** 2016-04-22 16:17 UTC
