### ISSUE TITLE
can i set auto-detect encoding as default 

### ISSUE THREAD

**Issue by friskfly** [atom/atom#7547] opened 2015-06-29 13:24 UTC
it always opens as utf8 ,  can i set auto-detect as default ？

**Comment by friskfly** [comment] 2015-06-29 13:28
My project may have different encodings , so i can't just set the only file encoding.

**Comment by friskfly** [comment] 2015-06-29 13:36
> If you pull up the file encoding dialog, you can choose an alternate file encoding to save your file in. Normally it will auto-detect the encoding if it can, otherwise it will default to UTF-8. New files will also be UTF-8 files by default.
The Docs shows that it will auto-detect the encoding if it can , but it didn't . When i manually select __auto-detect__ , it shows correctly, so i guess it may be a bug.

**Comment by stebiger** [comment] 2015-06-29 15:12
Just checked it:
Same behaviour here - always enforcing default encoding upon opening and writing files.

Easy reproducable..
https://discuss.atom.io/t/not-recognizing-file-encoding-always-enforcing-default-encoding/18219

**Comment by hebbet** [comment] 2015-06-30 11:59
see #4160

**Comment by mnquintana** [comment] 2015-06-30 12:10
Thanks @hebbet! This is indeed a duplicate of https://github.com/atom/atom/issues/4160 – let's move the discussion there.

**Closed by mnquintana** 2015-06-30 12:10 UTC
