### ISSUE TITLE
Uncaught Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by lorenabrams** [atom/atom#7998] opened 2015-07-21 04:40 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.13055644
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

```
At _tls_common.js:87

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
  at Error (native)
  at Object.createSecureContext (_tls_common.js:87:19)
  at Object.exports.connect (_tls_wrap.js:873:21)
  at Agent.createConnection (https.js:61:14)
  at Agent.createSocket (_http_agent.js:175:16)
  at Agent.addRequest (_http_agent.js:147:23)
  at new ClientRequest (_http_client.js:130:16)
  at Object.exports.request (http.js:30:10)
  at Object.exports.request (https.js:115:15)
  at Request.start (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/node_modules/request/request.js:904:30)
  at Request.end (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/node_modules/request/request.js:1635:10)
  at end (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/node_modules/request/request.js:676:14)
  at Immediate._onImmediate (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/node_modules/request/request.js:690:7)
  at processImmediate [as _immediateCallback] (timers.js:369:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-07-21 12:00
How did you install Atom? That's a really weird version number.

**Comment by bolinfest** [comment] 2015-07-22 17:28
@mnquintana It's a build of Atom with Nuclide packages pre-bundled.

**Comment by kevinsawicki** [comment] 2015-07-27 22:39
This stack trace looks like an HTTP request created with no error handler and since it is async the location where it happened isn't possible to know.

I'm going to close this out, please comment if you can provide reproduction steps so we can try and address the root cause of this error.

**Closed by kevinsawicki** 2015-07-27 22:39 UTC
Labels: more-information-needed, uncaught-exception
