### ISSUE TITLE
Atom does not autocomplete non-ASCII characters

### ISSUE THREAD

**Issue by Yajo** [atom/atom#9540] opened 2015-11-12 11:52 UTC
1. Edit a markdown file.
2. Write "versión" in a line.
3. Write "ver" in the next line.
4. Atom will show completion for "versi", not "versión".

**Comment by izuzak** [comment] 2015-11-12 11:54
Thanks for the report. I think this is a duplicate of https://github.com/atom/autocomplete-plus/issues/76, so I'm going to close this in favor of that issue. If I misunderstood your report -- please let me know. I also recommend checking out the guidelines for submitting [bug reports](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs).

**Closed by izuzak** 2015-11-12 11:54 UTC
