### ISSUE TITLE
Make chocolatey an official release channel

### ISSUE THREAD

**Issue by adamralph** [atom/atom#6931] opened 2015-05-24 12:56 UTC
Although it is mentioned in README.md, it appears that chocolatey is a third party release channel only. The current version on chocolatey is 0.174.1 and plenty of GitHub releases have been published since then. How about making chocolatey an official release channel so that it gets updated in lock-step with the GitHub releases?

**Comment by thomasjo** [comment] 2015-05-24 16:29
I'm hoping we're gonna nuke the Chocolatey stuff soon. I think the only valid reason for having it around still is that is simplifies the process of setting up CI environments a little bit.

@atom/feedback: are there any **really** good reasons for keeping the Chocolatey stuff alive?

**Comment by adamralph** [comment] 2015-05-24 16:34
Perhaps I'm missing something, but what does the Chocolatey package have to do with CI environments? I'm not setting up a CI environment, I'm building development machines for myself. IMHO Chocolatey is a great way to bootstrap and maintain a development machine.

**Comment by thomasjo** [comment] 2015-05-24 16:40
It's used to bootstrap CI environments, just like you use it to bootstrap a dev environment; https://github.com/atom/ci/blob/master/appveyor.yml

Initially Chocolatey was used as because we didn't have the auto-update story on Windows, but now that we do, Chocolatey is not, and will not be, the recommended way to install Atom on Windows. That doesn't mean it won't be kept alive, but I *personally* hope we just get rid of it to avoid confusion. The decision ultimately comes down to the core team, I'm just a highly opinionated maintainer :smirk:

**Comment by adamralph** [comment] 2015-05-24 16:49
I think that would be a real shame. Chocolatey is Window's best answer to apt-get and homebrew and for myself and many others is the favoured method of installing software on Windows. I don't want to go hunting around on websites for installers. I want to be able to type `choco install atom`. I also want to be able to write simple scripts for bootstrapping all my required dev software onto a machine.

Where do you see the risk of confusion?

**Comment by 50Wliu** [comment] 2015-05-24 16:59
> Where do you see the risk of confusion?

There's been more than a couple of issues that have been resolved due to a Chocolatey/Squirrel misunderstanding.

**Comment by thomasjo** [comment] 2015-05-24 16:59
Well, I haven't checked recently, but in the past Atom installed via Chocolatey did not use the built-in auto-updater, and thus essentially means users are left with outdated versions of Atom. We basically want to force updates (in the future, aka post v1.0.0, there will be a stable release channel, as well as beta channel etc) just like Chrome does. I don't think the Chocolatey model can be made compatible with Squirrel, but I'll let @paulcbetts comment on that since I really have no clue.

So if this is still a problem, this causes confusion because we have to tell some users that they have to be super-diligent about updating Atom via `cup` (or whatever is recommended in Chocolatey these days) frequently, while the rest of the users will suffer no such pain and will enjoy the Happy Place™ of wonderful automatic updates.

**Comment by nosami** [comment] 2015-05-24 17:01
According to [this](https://chocolatey.org/packages/Atom), the package always installs the latest version. I haven't tried it although it clearly states that it uses Atom's own automatic updater too.

**Comment by thomasjo** [comment] 2015-05-24 17:06
> According to this, the package always installs the latest version. I haven't tried it although it clearly states that it uses Atom's own automatic updater too.

Cool, then whatever issues were present in the past, have been resolved. Thanks for the info!

**Comment by adamralph** [comment] 2015-05-24 17:21
In that case, the only problem is that the current chocolatey package does not work - https://gist.github.com/adamralph/efd15b74c8b3b67fc277

**Comment by adamralph** [comment] 2015-05-24 17:29
A re-install of chocolatey itself got rid of that error :smile: 

So it seems that all is good. Whilst the installer stays the same and at the same URL, the current chocolatey package will work. It would still be nice if the project owners embraced the chocolatey package as an official release channel though.

**Comment by luisrudge** [comment] 2015-05-24 17:46
:+1: Chocolatey is awesome. It should not be a second class installer.

**Comment by paulcbetts** [comment] 2015-05-24 18:53
In new versions of Atom, the `--silent` switch should make implementing a Chocolatey-based installer super easy

**Comment by ferventcoder** [comment] 2015-05-24 19:03
>Well, I haven't checked recently, but in the past Atom installed via Chocolatey did not use the built-in auto-updater, and thus essentially means users are left with outdated versions of Atom.

@thomasjo @50Wliu I'm hoping that the above was mentioned with the understanding that Chocolatey does not block an auto-updater and that the only reason the above would be true is due to not continuing to release updated versions of Atom that **do** use an auto-updater. Or at least one that would allow auto updates. ;)

I recently heard a source of confusion from @shanselman that troubled me, which may have come from this group. I just want to clear it up though, so that there is no misinformation. Chocolatey does not have any built-in facilities to disable any automatic update of underlying software and the moderators on Chocolatey.org discourage package maintainers from adding anything that would - to do so would be a disservice to the community. Yes, I understand that means that choco believes software is on one version and it's actually on a much newer version, but that's okay. The system stays up to date and that is more important. We'll figure out how to better work with applications that autoupdate. :)

**Comment by ferventcoder** [comment] 2015-05-24 19:08
> In that case, the only problem is that the current chocolatey package does not work - https://gist.github.com/adamralph/efd15b74c8b3b67fc277

@atom/feedback - I do want to mention that I've been trying to get folks to fix the current Atom package as it used some things that were not part of the public API, but to date have not heard back:
https://github.com/atom/chocolatey/issues/40#issuecomment-95616294

I finally gave up and added those non-public variables to choco, specifically calling out the Atom package install being fixed in the release notes - https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#0996-may-16-2015

**Comment by ferventcoder** [comment] 2015-05-24 19:13
> In new versions of Atom, the `--silent` switch should make implementing a Chocolatey-based installer super easy

:+1: 

It's how we provided the Visual Studio Code package so quickly. :)

**Comment by thomasjo** [comment] 2015-05-24 19:14
@ferventcoder it was not my intention to blame Chocolatey; the problem was on our side. 

Thanks for info on even better support for autoupdating apps!

**Comment by ferventcoder** [comment] 2015-05-24 19:22
@thomasjo No worries. Chocolatey is in a state of transition, with the move to moderation and the compiled version of choco. The road has been bumpy and I'm sure that you Atom folks have felt that bumpiness from October up until now. :/

We know on our end we have quite a way to go to be as fully featured as other package managers. Over the next year folks will see that transition and future bumps along the way. Squirrel is awesome and I'm pretty confident that there is a symbiotic relationship with choco moving forward. :)

**Comment by cpdeethree** [comment] 2015-06-26 16:15
I had the same issue as @adamralph regarding Chocolatey installation of Atom. It was also resolved by reinstalling Chocolatey.

I understand that Chocolately's update methodology differs from Atom's auto updater, and using them in tandem is like trying to fit a square peg into a round hole.

Atom shouldn't be removed off of Chocolatey, but something should be done to correct the confusion caused by the version differences. A symbolic version bump on Chocolatey along with a some more detailed notes and possibly a link to the article explaining the switch (http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html) would probably do the trick.

**Comment by mark-hahn** [comment] 2015-06-26 17:21
> Atom shouldn't be removed off of Chocolatey

Do you use the GUI version of Chocolatey?  Last year when I had to use it
for Atom I found it unusable on my Windows 8.  It was crash city.  The
command-line worked ok.

I also disliked the delay it caused in the release cycle.

**Comment by cpdeethree** [comment] 2015-06-26 20:17
Hi Mark,

No, I experienced this issue on the command line version of Chocolatey.

Conor

**Comment by gep13** [comment] 2015-07-08 20:26
As one of the moderators/contributors to Chocolatey, I am seeing a growing number of questions like this one:

https://chocolatey.org/packages/Atom#comment-2123303651

Regarding the outdated version of Atom hosted on Chocolatey.org.  Now, I understand, based on this blog post:

http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html

That you have moved to a new Squirrel based, auto updating package installation, and that is great, but I think we (Chocolatey) can still help out.  And I mentioned this in a couple tweets to @AtomEditor, that didn't seem to gain any traction:

https://twitter.com/gep13/status/614858654462836740
https://twitter.com/gep13/status/614858762860556288

I would like to suggest that you push one more version of the Atom Editor Chocolatey installation package.  This would contain the most recent version of Atom (at the time the package was pushed) which would then mean that people can do a simple:

```choco install atom```

and then immediately get the automatic updates from Squirrel, i.e. best of both worlds.

If you go ahead with this, I would suggest that you update the description of the package to indicate that there will unlikley be any new packages pushed to Chocolatey, but that the automatic updates will take care of it.

What are your thoughts on this?  Thanks!

**Comment by kevinsawicki** [comment] 2015-07-08 20:30
> What are your thoughts on this?

The current chocolatey Atom release already uses the latest Windows installer available, meaning `choco install atom` will install `1.0.1`, the latest release at the time of writing this.

**Comment by gep13** [comment] 2015-07-08 20:34
> The current chocolatey Atom release already uses the latest Windows installer available, meaning choco install atom will install 1.0.1, the latest release at the time of writing this.

Perfect, that I did not know, and in all honesty, I hadn't checked.  Based on the wording of the blog post, I took it to mean that the Chocolatey package wasn't going to work any more, since the suggestion was to uninstall from Chocolatey, and then download from Atom.io.

**Comment by kevinsawicki** [comment] 2015-07-08 21:03
> Based on the wording of the blog post, I took it to mean that the Chocolatey package wasn't going to work any more, since the suggestion was to uninstall from Chocolatey, and then download from Atom.io.

Yeah, probably should have updated the blog post but after it was posted there was some discussion about migrating it to the new installer and doing a final chocolatey release that was done in the following pull request:

https://github.com/atom/chocolatey/pull/35

**Comment by gep13** [comment] 2015-07-08 21:08
@kevinsawicki sounds like we are all on the same page, so that is the main thing :+1: 

Thanks for getting back to me!

**Comment by alexchandel** [comment] 2015-07-30 05:32
Atom's Chocolatey package shouldn't use an installer at all, including Squirrel, InstallShield, MSI, or anything else that touches the registry. Instead, it should unarchive the [Windows zip release](https://github.com/atom/atom/releases/download/v1.0.3/atom-windows.zip) to the folder Chocolatey gives it.

This is because Chocolatey is useful for installing packages globally, not just per-user. It's orthogonal to the Squirrel installer. By forcibly installing its package to the `~/AppData/Local/atom` of the current user, Atom blocks other users from accessing it, defeating the purpose of Chocolatey and preventing people from deploying Atom on servers or across multiple machines (I wanted to do exactly this recently).

**Comment by lee-dohm** [comment] 2016-05-02 17:29
Since the original question of official support for Chocolatey has been addressed, I'm going to close this Issue.

Regarding changing the Chocolatey package to install via the Windows zip release, we don't have any plans to do that at this time.

**Closed by lee-dohm** 2016-05-02 17:29 UTC
Labels: question, windows
