### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/denis/Library/Application Suppor...

### ISSUE THREAD

**Issue by denisko** [atom/atom#9810] opened 2015-11-25 10:01 UTC
[Enter steps to reproduce below:]

1. In file browser select (xml) file to open
2. Select "open with..." -->  "Atom" from file browser
3. Wait for file to open
4. Squirel lights up to indicate update information
5. Press Squirrel to see update notes
6. Boom....

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/denis/Library/Application Support/com.github.atom.ShipIt/update.ffkdG5y'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/denis/Library/Application Support/com.github.atom.ShipIt/update.ffkdG5y'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/denis/Library/Application Support/com.github.atom.ShipIt/update.ffkdG5y/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "formatter",
      "atom-beautify"
    ]
  },
  "editor": {
    "fontSize": 10,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-25 13:10
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-25 13:10 UTC
