### ISSUE TITLE
Loading a big project with SPELL-CHECK" on freezes Atom.

### ISSUE THREAD

**Issue by drhugobr** [atom/atom#14359] opened 2017-05-05 00:16 UTC
I have a big project folder with a few hundreds of files, after looking at TIMECOP, it says that on a BLANK start it takes 406ms just to load, after spell-ckeck 0.71.3 is disabled, blank startup falls to 38ms.

With Spell-Check on, it simply freezes, i've left it loading for about 5 minutes and no response.

**Comment by Ben3eeE** [comment] 2017-05-05 05:42
Duplicate of https://github.com/atom/spell-check/issues/190?

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Closed by Ben3eeE** 2017-05-05 05:42 UTC
