### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/[project dir]/project.json'

### ISSUE THREAD

**Issue by wn9FHW2nhO** [atom/atom#4862] opened 2015-01-06 10:30 UTC
[Enter steps to reproduce below:]

1. ... Open any file.

or

1. ... Open any file.
2. ... Type any charactor

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/[project dir]/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/[project dir]/project.json'
  at Error (native)

```

### Commands

```
     -1:05.2 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:05.1 refactor:done (atom-text-editor.editor.is-focused)
     -1:05.1 editor:newline (atom-text-editor.editor.is-focused)
  3x -1:02.8 core:backspace (atom-text-editor.editor.is-focused)
     -1:01.7 autocomplete-plus:cancel (input)
  3x -0:59.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:39.0 pane:show-previous-item (button.btn.btn-default.icon.icon-playback-play)
     -0:38.4 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:37.9 core:close (div.settings-view.pane-item)
     -0:05.1 core:save (atom-text-editor.editor.is-focused)
     -0:00.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "atom-ternjs",
      "autocomplete-paths"
    ],
    "themes": [
      "atom-light-ui",
      "monokai-light"
    ]
  },
  "editor": {
    "fontFamily": "SourceCodePro-Light",
    "fontSize": 12,
    "showInvisibles": true,
    "showIndentGuide": true,
    "autoIndentOnPaste": false,
    "tabLength": 4,
    "useShadowDOM": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.4.0
atom-beautify, v0.21.1
autocomplete-plus, v1.1.0
coffee-refactor, v0.6.2
color-picker, v1.2.6
docs-snippets, v0.8.0
emmet, v2.3.0
file-icons, v1.4.4
js-refactor, v0.3.0
language-jade, v0.3.0
linter, v0.9.1
linter-javac, v0.1.3
linter-php, v0.0.11
monokai-light, v0.1.0
refactor, v0.4.1
save-session, v0.11.2

# Dev
No dev packages
```

**Comment by wn9FHW2nhO** [comment] 2015-01-06 13:50
Stacktrace on "window.fs" methods.
![2015-01-06 22 49 23](https://cloud.githubusercontent.com/assets/4343487/5629396/587c2a20-95f6-11e4-8cec-26eba21b85fd.png)

**Comment by wn9FHW2nhO** [comment] 2015-01-06 14:56
I sent a pull-request to the repository of the "save-session".
see https://github.com/wn9FHW2nhO/save-session/commit/866d3879f65c2e66a7e793fcc384ee451acb8c79

**Comment by kevinsawicki** [comment] 2015-01-06 17:56
This is a duplicate of https://github.com/atom/atom/issues/4854

**Closed by kevinsawicki** 2015-01-06 17:56 UTC

**Comment by benogle** [comment] 2015-01-06 18:39
https://github.com/mpeterson2/save-session/issues/43
