### ISSUE TITLE
Unable to use <enter> to go to new line after file dragged to different panel.

### ISSUE THREAD

**Issue by mltroutt** [atom/atom#5407] opened 2015-02-04 21:32 UTC
Atom Version: 0.174.0
OS: OSX Mavericks

When I create a new panel and then drag an already open file from the existing panel to the new panel, I can no longer create a new line by pressing `<enter>`, but I can create a new line by using `<command>` + `<enter>`.

This only seems to happen when the file is dragged over. The initial file which started the panel, as well as any files that are opened in the panel work fine.

There are no console errors when pressing `<enter>`.

**Comment by lee-dohm** [comment] 2015-02-05 01:46
Do you happen to have the [emmet package](https://atom.io/packages/emmet) installed? Virtually every time someone has said that their <kbd>ENTER</kbd> key stopped working, emmet has been the cause.

See: emmetio/emmet-atom#186

**Comment by mltroutt** [comment] 2015-02-05 14:37
Can confirm that emmet seems to be the issue. After disabling or disabling and reenabling emmet the problem is resolved.

**Comment by lee-dohm** [comment] 2015-02-05 15:40
Great! I'm going to close this then. Thanks for the update!

**Closed by lee-dohm** 2015-02-05 15:40 UTC
Labels: bug
