### ISSUE TITLE
Atom As Daemon

### ISSUE THREAD

**Issue by X4** [atom/atom#6352] opened 2015-04-12 22:54 UTC
Hi!

**Postive:**
I've been so happy with Atom, it replaced my IntelliJ/PHPStorm and other IDE's incl. Vim and Sublime Text as a general purpose editor and sometimes IDE for a wide array of languages. 

**Negative:**
Now here is my problem: The startup-time is frustrating.

Can't I run atom as a daemon during startup and attach it to the [daemon like emacs-client](http://www.emacswiki.org/emacs/EmacsAsDaemon)?

Hey, that's also a good business model for you @github :+1:

**Comment by paulcbetts** [comment] 2015-04-13 00:20
Let's just fix the load time :)

**Comment by mark-hahn** [comment] 2015-04-13 00:51
duplicate of #3673

**Comment by 50Wliu** [comment] 2015-04-13 00:57
Startup time is being improved.  @kevinsawicki just introduced a few more PRs to shave off a couple of milliseconds on load.  But yeah, please see #3673 for the main discussion :).

**Closed by 50Wliu** 2015-04-13 00:57 UTC
