### ISSUE TITLE
Remove Atom from Windows context menu 

### ISSUE THREAD

**Issue by BramVanroy** [atom/atom#8264] opened 2015-08-07 09:19 UTC
Atom is integrated into Windows' context menu. For some this might be useful, however I find it annoying. It would be useful if the "Open with Atom" only appeared on eligible files, but the message even appears when right-clicking on an executable.

![schermopname 2](https://cloud.githubusercontent.com/assets/2779410/9132723/e05e152e-3cf5-11e5-87f8-00bbb8fee0b4.png)

I tried disabling Atom in the context menu with CCleaner, but even though I disabled it, it's still there:

![schermopname 3](https://cloud.githubusercontent.com/assets/2779410/9132748/1d400f10-3cf6-11e5-9f04-43f93d92bd2c.png)

I also looked in Atom's settings, but I can't find anything. Is there a way to remove Atom from the context menu?

**Comment by mnquintana** [comment] 2015-08-07 10:47
I think this is a duplicate of https://github.com/atom/atom/issues/5901 – let's keep the discussion going there.

**Closed by mnquintana** 2015-08-07 10:47 UTC
Labels: enhancement, question, windows
