### ISSUE TITLE
Incorrect default directory when initializing a new Git repository

### ISSUE THREAD

**Issue by vrrajkum** [atom/atom#17762] opened 2018-07-30 23:57 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When trying to initialize a new Git repository in a directory that does not already contain one, the path in the modal dialog that pops up defaults to `C:\Users\<user>\github` rather than the current working directory.

### Steps to Reproduce

1. Add a new project folder that does not already contain a Git repository
2. Open the Git tab (`Ctrl+Shift+9` or click the bottom right corner)
3. Click 'Create repository' button

**Expected behavior:** The dialog window pops up with the working directory as the default path

**Actual behavior:** The dialog window pops up with a generic directory as the default path https://imgur.com/iTKr8H9

**Reproduces how often:** 100%

### Versions

Atom 1.28.2 x64
Windows 7 Pro SP1 x64

### Additional Information

Not sure if this is related: if I add a project folder that does not already contain a Git repository to Atom, and then initialize a repository in that directory by running `git init` in the command line, the repository initializes successfully but Atom does not detect it unless I exit and reload Atom.

**Comment by Wittiest** [comment] 2018-08-03 05:50
This issue is already open on the correct repo with sufficient documentation:
https://github.com/atom/github/issues/1237

**Comment by rsese** [comment] 2018-08-03 18:05
Thanks for the report @vrrajkum and thanks for the pointer (and pull request) @Wittiest :+1:

Closing as a duplicate of atom/github#1237.

**Closed by rsese** 2018-08-03 18:05 UTC
