### ISSUE TITLE
Unexpected character '' in grunt build. Atom adding wierd characters on Windows and showing up strange in linux console.

### ISSUE THREAD

**Issue by danrossi** [atom/atom#13903] opened 2017-03-01 10:27 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am trying to edit in Atom on windows and build on Linux. Everytime I save , the editor is adding strange characters everywhere and is hard to cleanup because they are only visible on the Linux console.

I get errors like 

```
Unexpected character '�'
```

when running grunt builds.

I haven't even edited these parts it shows up like

```
^?myMethod(e) {
```

or

```
 {^? type:
```

It seems to be inserting within curly braces in parts I have not edited when saving. 

It is not happening with SublimeText.

Encoding is set to utf8

### Steps to Reproduce

Windows 10 Atom Editor. Edit any code and save. 
View in Linux or Linux Subsystem. 

**Expected behavior:** 

No funny characters inserted. 

**Actual behavior:** 

These characters inserted. 

**Reproduces how often:** 

Happens on every save. 

### Versions

1.14.4

**Comment by 50Wliu** [comment] 2017-03-01 15:40
Have you completed the prerequisites?  I noticed that you didn't check the box.

**Comment by danrossi** [comment] 2017-03-01 17:18
I'll run it in safe mode and see what happens. I have no custom packages installed yet.

**Comment by danrossi** [comment] 2017-03-01 17:56
this is unrelated but was also happening on OSX. The app crashes because its loading compressed minified files when selected when trying to copy and paste. Entire app timesout and locks up. Have to do that outside the editor. It just did it in safe mode.

**Comment by danrossi** [comment] 2017-03-04 04:58
I believe in safe mode the character issue is not happening. I had to keep trying. 

There is too many other issues so I need to put them here too. 

That issue viewing minified javascript causing it to hang is still a problem. This was a problem on OSX too. I have to copy and paste min files outside the editor to stop it crashing. 

It is now crashing on startup even in safe mode. It is hanging. I eventually get a notice "editor is not responding"

**Comment by 50Wliu** [comment] 2017-03-04 05:25
Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
***
1.15.0-beta4 fixes the minified JavaScript issues.  To get out of the hanging state, start Atom using `atom --clear-window-state`.  Be aware that this will remove all serialized state, including unsaved changes.

**Comment by danrossi** [comment] 2017-03-04 05:48
@50Wliu  I mentioned in a previous ticket that I was forced to close and start again. It is a fresh install with no packages installed. 

I managed to find the location of the beta4 download. The msi for some reason does not start the installation process in Windows 10 it just closes. I found the installer location in C:\Program Files (x86)\Atom Installer\atom. 

It is also crashing on startup for some reason so can't confirm anything else yet. I might keep trying the beta downloads so we're on the same page for now no worries. 

I will try and find a way to clear a cache or something to stop the crashing uninstalling didn't help.

**Comment by danrossi** [comment] 2017-03-04 05:50
OK confirming 

```
atom --clear-window-state
```

Fixes the crashing problem. I'll keep it out of safe mode and see if the character issue shows up again. It happens on any file including html if I edit html and therefore breaks in the browser. 

**Comment by danrossi** [comment] 2017-03-04 05:52
Actually this might be a non issue and sorry about the noise. Get a load of that weird character just in the form in the browser. It could be windows or my system ? 

**Comment by 50Wliu** [comment] 2017-03-04 06:02
The `.msi` is primarily for enterprise installs and shouldn't be used for regular installs.  Use `AtomSetup.exe` for that (it's not your fault for choosing the wrong one - we really need to document this).

I'm going to tentatively close this for now, but if later on you feel that the bug is reproducible in safe mode, and isn't a more general problem with your system, feel free to comment here and I'll reopen it.

**Closed by 50Wliu** 2017-03-04 06:02 UTC
Labels: more-information-needed

**Comment by danrossi** [comment] 2017-03-04 06:12
That is ok. I'll stick with the beta downloads. Then see if the character issue comes up again. 

**Comment by danrossi** [comment] 2017-03-04 15:08
just in case somebody says anything about this. For some reason the unicode characters are being inserted where the cursor is and control-s is keyed in to save. It's Window.

**Comment by danrossi** [comment] 2017-03-05 08:15
It has crashed on startup again requiring a reset. Very unstable.

**Comment by danrossi** [comment] 2017-03-10 04:18
It has crashed again and will need to reset. I have to keep coming back in it to remember the command.
