### ISSUE TITLE
powershell: atom can't use relative paths in the command line

### ISSUE THREAD

**Issue by aae42** [atom/atom#17030] opened 2018-03-26 18:45 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

No matter what directory i'm in in my powershell console, if i run `atom .` it opens the `C:\Users\myusername\AppData\Local\atom\app-1.25.0` directory.... 

so if i try to open a .\README.md in the directory i'm in using `atom .\README.md` it creates a new blank README.md file in that AppData directory...

if i run `atom $(resolve-path .)`  or... `atom $(resolve-path ./README.md)` it works as you'd expect without the `resolve-path` bits

### Steps to Reproduce

1. Run `atom .` from any directory

**Expected behavior:** i expect atom to open up a project with the directory of the present working directory

**Actual behavior:** it opens up `C:\Users\myusername\AppData\Local\atom\app-1.25.0`

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

atom --version doesn't output anything
apm --version outputs "atom 1.25.0"

this is on windows 10 pro, 64-bit... version 1703

### Additional Information

seems like it's a problem with my profile but i don't know where to look

**Comment by Arcanemagus** [comment] 2018-03-26 18:50
> if i run atom . it opens the C:\Users\myusername\AppData\Local\atom\app-1.25.0 directory....

> if i run atom $(resolve-path .) or... atom $(resolve-path ./README.md) it works as you'd expect without the resolve-path bits

> atom --version doesn't output anything

Something seems to not be working correctly in your PowerShell environment, are you using the Windows shell with no modifications? Are you using a third-party wrapper?

Does `cd .` work or does it show the similar issues?

**Comment by Arcanemagus** [comment] 2018-03-26 19:36
Thanks for taking the time to contribute!

I did some searching and noticed that this is a duplicate of https://github.com/atom/atom/issues/15853. Could you try the steps you've done above in Command Prompt as well and report back in that issue? Thanks!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-26 19:36 UTC
Labels: more-information-needed, windows
