### ISSUE TITLE
Atom fails to render this emoji --> ▶️ (U+25B6)

### ISSUE THREAD

**Issue by tennysonholloway** [atom/atom#10403] opened 2016-01-13 19:25 UTC
It displays as a blank box, and also counts as two characters. Other emojis seem to render fine and only count as one character.

on osx 10.11.3
atom version 1.3.3 (and version 1.4)

the two character problem is perhaps related to https://github.com/atom/atom/issues/8974

Can anyone else reproduce this?

**Comment by lee-dohm** [comment] 2016-01-13 19:41
I cannot reproduce this using Atom v1.3.3 on Mac OS X 10.11.2. Since OS X 10.11.3 at this point is still in Beta, I'm reluctant for us to spend time investigating this yet. I'm going to leave this open for now though.

**Comment by Wasserschlange** [comment] 2016-01-13 20:18
I am not able to reproduce it on Atom v1.3.3 on XUbuntu 14.04 LTS.

Here is a screen shot on my system:
![screenshot - 16-01-13 - 12 11 50 pm rendered](https://cloud.githubusercontent.com/assets/5054653/12306607/7c38750e-b9ef-11e5-87f1-3fe3e606013a.png)

**Comment by demhydraz** [comment] 2016-01-14 18:05
I am unable to reproduce using Arch Linux x86_64 and Atom 1.5.0-beta0.

![](http://i.imgur.com/k1Qdihl.png)

**Comment by lee-dohm** [comment] 2016-01-14 19:02
Yep, looks like it is a problem specifically with the OS X beta. @tennysonholloway you may want to report this to Apple. Going to close this for now until it shows up on a released version.

**Comment by lee-dohm** [comment] 2016-01-14 19:09
Yep, looks like it is a problem specifically with the OS X beta. @tennysonholloway you may want to report this to Apple. Going to close this for now until it shows up on a released version.

**Comment by matteocrippa** [comment] 2016-03-29 19:09
I'm experiencing the same issue w/ stable version of OSX 10.11.4 and Atom 1.6.0

eg. ❤️ renders as the image attached

![screen shot 2016-03-29 at 21 09 22](https://cloud.githubusercontent.com/assets/475463/14120326/8fca8fb4-f5f2-11e5-95c8-2096a09868d8.png)

**Comment by amytruong** [comment] 2016-03-29 22:36
@lee-dohm: Reproduced this on 10.10 and atom 1.6.0 
Re-opening... 😬

**Comment by lee-dohm** [comment] 2016-03-30 19:37
Hmmmm ... exploring further, it seems some emoji render properly and some don't. Copying and pasting the play button or heart emoji from this Issue renders the box. If I directly enter the Unicode character codes using the Unicode Hex Input on OS X, I get the black-and-white versions:

<img width="326" alt="screen shot 2016-03-30 at 12 33 49 pm" src="https://cloud.githubusercontent.com/assets/1038121/14154858/b1aa0f5c-f673-11e5-806b-4b34ebbbf062.png">

But if I use the Emoji Input in OS X, I get the box for both of them. Also, I can't enter the emoji for the grinning face (:grinning:) using the Unicode Hex Input mode, but when I use the Emoji Input it works and renders fine.

Unicode for the play button is `U+25B6` as mentioned above and for the heart is `U+2764`. See the [Full Emoji Data chart](http://www.unicode.org/emoji/charts/full-emoji-list.html).

**Closed** 2016-03-31 15:45 UTC
Labels: atom, bug
