### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by TonyToth** [atom/atom#6780] opened 2015-05-14 07:54 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Tony's\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:17.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:13.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:13.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:12.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:12.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:12 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:11.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:11.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:11 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:10.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:09.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:09.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:09.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.16.0
autocomplete-css, v0.7.2
autocomplete-html, v0.7.2
autocomplete-plus, v2.15.2
remote-sync, v2.4.1

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-05-14 10:23
Duplicate of https://github.com/atom/atom/issues/6548 - please subscribe there for updates.

**Closed by mnquintana** 2015-05-14 10:23 UTC
