### ISSUE TITLE
A JavaScript error occured in the browser process

### ISSUE THREAD

**Issue by Nordic89** [atom/atom#4814] opened 2014-12-31 11:36 UTC
Uncaught Exception:
Error: EPERM, operation not permitted '/tmp/atom.sock'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:807:18)
    at AtomApplication.module.exports.AtomApplication.deleteSocketFile (/usr/share/atom/resources/app/src/browser/atom-application.js:193:21)
    at AtomApplication.module.exports.AtomApplication.listenForArgumentsFromNewProcess (/usr/share/atom/resources/app/src/browser/atom-application.js:172:12)
    at new AtomApplication (/usr/share/atom/resources/app/src/browser/atom-application.js:88:12)
    at Socket.createAtomApplication (/usr/share/atom/resources/app/src/browser/atom-application.js:43:16)
    at Socket.emit (events.js:107:17)
    at net.js:436:14
    at process._tickCallback (node.js:378:11)

Whenever I try to start atom, I get this error.

Running on: Archlinux 64 bit.
Atom version is 0.165.0-1

**Comment by izuzak** [comment] 2015-01-02 20:16
Looks like a duplicate of https://github.com/atom/atom/issues/4346, so closing this in favor of that issue.

**Closed by izuzak** 2015-01-02 20:16 UTC
