### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by alexis900** [atom/atom#7677] opened 2015-07-03 10:25 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Alejandro\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:48.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:48.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:48.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:45 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:45 snippets:expand (atom-text-editor.editor.is-focused)
     -0:45 editor:indent (atom-text-editor.editor.is-focused)
     -0:42.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:42.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:42.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:40.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:40.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:40.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:38.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:38.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:38.7.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:27.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.1.2
atom-material-ui, v0.4.15
color-picker, v2.0.7
file-icons, v1.5.8
minimap, v4.10.2

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-07-03 10:27
This is a duplicate of https://github.com/atom/atom/issues/6548 -- it will be fixed in the next release of Atom. Thanks for the report!

**Closed by izuzak** 2015-07-03 10:27 UTC
