### ISSUE TITLE
Uncaught TypeError: Cannot set property 'localAddress' of undefined

### ISSUE THREAD

**Issue by Akshay-Thakare** [atom/atom#6611] opened 2015-05-02 08:52 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot set property 'localAddress' of undefined

```
At net.js:840

TypeError: Cannot set property 'localAddress' of undefined
  at connect (net.js:840:23)
  at net.js:943:9
  at dns.js:87:18
  at process._tickCallback (node.js:366:11)

```

### Commands

```
     -30:38.0 remote-edit:new-host-sftp (atom-text-editor.editor)
  2x -30:35.3 core:backspace (atom-text-editor.editor.mini)
     -30:07.7 remote-edit:show-open-files (atom-text-editor.editor)
     -30:02.3 remote-edit:browse (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-light-theme"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.4.0
autocomplete-html, v0.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.0
autocomplete-ruby, v0.0.1
remote-edit, v1.7.2
remote-sync, v2.4.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-02 15:28
Duplicate of #5468, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-02 15:28 UTC
