### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by vbellotto** [atom/atom#16798] opened 2018-02-20 20:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At C:\Users\vitorDesk\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor-component.js:2290

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2279:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2272:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:400:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:278:20)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.24.0/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -2:07.1.0 core:backspace (input.hidden-input)
     -2:05.4.0 core:save (input.hidden-input)
     -1:42.4.0 core:backspace (input.hidden-input)
     -1:41.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-02-20 21:47
Thanks for the report!  Looks like this is a duplicate of https://github.com/atom/atom/issues/15263 and the [fix](https://github.com/atom/atom/pull/15831) will be available in an upcoming release.

**Closed by rsese** 2018-02-20 21:47 UTC
