### ISSUE TITLE
Atom doesn't work when launch without arguments

### ISSUE THREAD

**Issue by ragekit** [atom/atom#4674] opened 2014-12-17 23:02 UTC
Hi all !

I'm on windows : installed with the new installer on the website after doing a clean remove from chocolatey.

I have a weird problem : if i open atom from the commandline, with atom . or atom ./myfile , then everything work fine. If i open it from the desktop shortcut (or even right click open with atom) then, i can't write anything or create new files, and i've got a bunch of "module did not register" in the console from a load of module (all of them i guess ?)

It's a pretty weird bug, everything worked fine with my old chocolatey version.

**Comment by kevinsawicki** [comment] 2015-07-21 21:16
Closing as duplicate of #4662

**Closed by kevinsawicki** 2015-07-21 21:16 UTC
Labels: more-information-needed, windows
