### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by michelecos** [atom/atom#9674] opened 2015-11-18 12:16 UTC
[Enter steps to reproduce below:]

1. Launch atom
2. Launch atom from the command line, like "open -a atom ." on Mac
3. It is not deterministic, the problem happens sometimes.

**Atom Version**: 1.2.1
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the linter package

```
At ENOENT: no such file or directory, lstat '/Users/michele/Library/Application Support/com.github.atom.ShipIt/update.hIJBcio'

Error: ENOENT: no such file or directory, lstat '/Users/michele/Library/Application Support/com.github.atom.ShipIt/update.hIJBcio'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at tryFile (module.js:105:22)
    at tryExtensions (module.js:115:20)
    at Function.Module._findPath (module.js:156:20)
    at Module._resolveFilename (module.js:334:25)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-18 14:32
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-18 14:32 UTC

**Comment by michelecos** [comment] 2015-11-18 14:41
Right.
