### ISSUE TITLE
Syntax highlighting stops working on long strings w/out a newline

### ISSUE THREAD

**Issue by bkushigian** [atom/atom#9521] opened 2015-11-11 05:56 UTC
This seems to be dependent on how many different things there are to highlight in a line. Another user (askielboe) found a relatively brief example, written in LaTeX:
`$\a \a \a 0 \a^\a{a} \a^\a{a} \a^\a{a} \a^\a{a} $ $\a \a \a \a \a 0 \a $ $\a\a $ $^{a} \a 0$ $^{a}$ this text should not be colored`

I've also noted the bug in other languages.

**Comment by izuzak** [comment] 2015-11-11 16:48
Thanks for the report, @bkushigian -- this seems like a duplicate of https://github.com/atom/atom/issues/1667 so I'm going to close this in favor of that issue.

**Closed by izuzak** 2015-11-11 16:48 UTC
