### ISSUE TITLE
Downloading the Windows installer with IE 11 loses the .exe extension 

### ISSUE THREAD

**Issue by shepmaster** [atom/atom#10088] opened 2015-12-16 18:10 UTC
Clicking on the big "Download Windows Installer" link on the homepage downloads from the link `https://atom.io/download/windows`. When this is finished, however, the file name is `AtomSetup` with no extension. Renaming the file to add an `.exe` allows it to be run.

This is on a fresh [modern.ie](https://dev.windows.com/en-us/microsoft-edge/tools/vms/) VM with Windows 7 and IE 11.

(Let me know if this isn't the right place to report website bugs — I didn't find a repository for the website with a tiny amount of searching)

**Comment by 50Wliu** [comment] 2015-12-16 21:11
I can't reproduce this on Windows 10 x64, Internet Explorer 11

I'll move this over to the [atom/atom.io](https://

**Comment by lee-dohm** [comment] 2015-12-17 19:47
Isn't this a bug for IE11 even if we can reproduce it? If every other browser can download the same file without losing the extension, then this is a bug in Internet Explorer. Am I misunderstanding @shepmaster?

**Comment by shepmaster** [comment] 2015-12-17 21:19
> This is on a fresh modern.ie VM with Windows 7 and IE 11.

I updated the VM with all available updates in Windows Update, but the problem persists.

> then this is a bug in Internet Explorer

I suppose that's possible. You'd have to look into how the file name is being suggested to the browser, check the relevant specs, etc. It's always possible that IE follows the actual spec and other browsers happen to follow a different *ad-hoc* spec.

I know there are thousands (or more?) people that wish they could simply claim "that's a bug in IE" (or Firefox or Chrome or Safari) and move on with their lives :smiley_cat: However, that can leave users out in the cold and lead to bad experiences. Usually that determination has to be made factoring in market share, intended audience, amount of time / money available to spend, etc. I am not qualified to speak towards any of that for the Atom project. The only thing I *can* say is that [IE11 is the second-largest desktop browser / version by usage](http://caniuse.com/usage-table) (if I'm reading that table correctly), so **I** would not be quick to discount it.

**Comment by lee-dohm** [comment] 2015-12-17 21:31
Let me be more specific in my wording then. If every other browser, including older versions of IE, can download the file with no issue, isn't this a bug in IE11?

I wasn't dismissing IE because it is IE. I wasn't dismissing IE at all. I was dismissing a bug in IE as something that perhaps we shouldn't spend time working around if they're just going to fix it.

**Comment by paulcbetts** [comment] 2015-12-17 23:23
@lee-dohm You're not wrong, but they're almost certainly not going to change IE's behavior, and there might be a way to work around it so that it works for erry'one

**Comment by lee-dohm** [comment] 2016-01-27 00:25
Marking this as duplicate of the newer issue https://github.com/atom/atom.io/issues/51 because this really should be on the other repository. Sorry for getting caught up in the debate and losing sight of proper triage process :grinning:

**Closed by lee-dohm** 2016-01-27 00:25 UTC
Labels: needs-reproduction
