### ISSUE TITLE
filename-tabs are flickering

### ISSUE THREAD

**Issue by Blaubeersirup** [atom/atom#7006] opened 2015-05-29 10:43 UTC
I am using atom as my standard editor on my MacBook Pro 13, but after some time i noticed that the tabs are flickering! It makes me sometimes a bit nervous.... Maybe you can fix that. Sorry for my bad english, i'm from Germany.

**Comment by izuzak** [comment] 2015-05-29 10:45
Can you please provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging) (e.g. if the problem is visible in safe mode)?

**Comment by Blaubeersirup** [comment] 2015-05-29 10:47
Open atom, open some tabs and try to set brightness on 100% on a Mac. Now watch the tabs. They should flicker a bit now....

**Comment by Blaubeersirup** [comment] 2015-05-29 10:48
I use version 0.202.0

**Comment by izuzak** [comment] 2015-05-29 10:51
Thanks for the details, but they're not flickering for me. Can you reproduce this behavior in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Which themes are you using? Can you reproduce this in Atom 0.204.0? Can you record a short GIF which demonstrates the flickering? (e.g. using [this tool](http://www.cockos.com/licecap/))

**Comment by Blaubeersirup** [comment] 2015-05-29 10:54
safe mode + atom 0.204.0: still flickering, flickering must come from atom because my screen is not damaged. i will try to record.

**Comment by Blaubeersirup** [comment] 2015-05-29 11:02
unfortunately you can't see the flickering on the gif. I am now trying to make a short screen record

**Comment by Blaubeersirup** [comment] 2015-05-29 11:06
same problem when making a screen record with quicktime....

**Comment by Blaubeersirup** [comment] 2015-05-29 11:10
I use One Dark for syntax and for ui theme
When i use other themes, then there's no flickering! 
Maybe the problem is the One Dark Theme???

**Comment by izuzak** [comment] 2015-05-29 11:41
> When i use other themes, then there's no flickering! 
> Maybe the problem is the One Dark Theme???

I'm using a Mac and the One Dark Theme as well, and I don't see any flickering in the tabs. 

@simurai @atom/issue-triage do you see any flickering in the tabs, as @Blaubeersirup described, or maybe have an idea about what might be causing this?

**Comment by simurai** [comment] 2015-05-30 01:25
This sounds like https://github.com/atom/one-dark-ui/issues/27.

I can't reproduce it on OS X with a 13" MBP, Late 2012, with a "Intel HD Graphics 4000 1024 MB". So maybe it depends on the exact configuration.

@Blaubeersirup Could you try to add the following to: `Menu > Atom > Open Your Stylesheet`.

```less
.theme-one-dark-ui .tab-bar .tab {
  backface-visibility: hidden;
}
```

And see if that helps. It did in some cases.

**Comment by simurai** [comment] 2015-07-29 06:19
There was a recent change that might have fixed this issue.

@Blaubeersirup Can you still reproduce it in Atom `1.0.3`?

**Comment by kevinsawicki** [comment] 2015-07-29 17:15
I'm going to close this out for now, please comment if you still see this on Atom 1.0.3+ and if the suggestions by @simurai help at all.

**Closed by kevinsawicki** 2015-07-29 17:15 UTC
Labels: more-information-needed, needs-reproduction

**Comment by guilala** [comment] 2015-11-25 16:34
I'm using Atom 1.3.0-beta6, on Ubuntu 15.10 Gnome 3, and try all kind of css like in Simurai's example to force hardware acceleration. But the flickering stays, and almost renders the select-list useless. But in order to properly use Atom on a Linux desktop, stop this flickering, and improve graphical performance, we really need access to startup flags! They should be in the settings, just like they are in a Chrome browsers like "chrome://flags"...

**Comment by DarioBoh** [comment] 2016-08-18 15:16
I have Atom 1.9.8 on MacBookProf12, ElCapitan v. 10.11.6 and the flickering is there

**Comment by adisahay** [comment] 2017-03-01 07:09
I started experiencing the flickering issue when I upgraded to Ubuntu 16.04 LTS. Happens around 50% of the time whenever I switch between tabs.

I have been noticing a very similar flickering issue in Chrome after my Ubuntu upgrade, which can be stopped using "--disable-gpu-driver-bug-workarounds" flag or by disabling "hardware acceleration".

I am wondering if that is the cause behind Atom's issue as well, since Atom depends on chromium engine for rendering its UI.
