### ISSUE TITLE
slow typing,  lag after enter, high CPU usage

### ISSUE THREAD

**Issue by svrkispm** [atom/atom#7481] opened 2015-06-27 10:17 UTC
I have just installed Atom 1.0.0 and it runs very slow. When I type it seems to lag every 5-10 characters for up to 2-3 seconds. The file I opened has around 3500 lines and 180 kB. I have tried using safe mode and disabling spellcheck, but it is still too slow. CPU usage peaks to 80-100% on one core as soon as I start typing.
When I press enter, editor lags for 3 seconds and CPU usage spikes to maybe 80% on one core.

When I open new file with only several lines, it works without the lag.

System info: Linux 3.13.0-40-generic #69-Ubuntu x86_64, Intel(R) Core(TM) i5 CPU M 520  @ 2.40GHz, 6 GB RAM, SSD.

I like this editor and I would like to help to diagnose this problem if someone tells me what to do.

Thank You.

**Comment by batjko** [comment] 2015-06-27 17:10
General lag issues have been opened a few times, e.g. see this one:
https://github.com/atom/atom/issues/6303

The core team is working on it.

**Comment by MisterCruz** [comment] 2015-06-29 02:08
I am also experiencing severe lag.

I even opened a 20 line plain html file and it lags like crazy. It's unbearable to type.

It also eats up my CPU.

System: Macbook Pro Retina 13 in.

**Comment by batjko** [comment] 2015-06-29 10:20
In addition to the issue I mentioned above, this other issue is also worthwhile following for lagging problems:
https://github.com/atom/atom/issues/6437

I think this one can be closed as a duplicate of any of these two (and I know there are probably others as well).

**Closed** 2015-06-29 13:28 UTC

**Comment by benogle** [comment] 2015-06-29 22:09
Please try: 'atom --safe .' Is the issue issue still there?

**Comment by svrkispm** [comment] 2015-07-01 14:26
Yes it is.

**Comment by Shwrndasink** [comment] 2015-12-17 05:35
I had the same issue. I had a package that was installed, then disabled it and everything seemed to go back to normal. I would try all packages you have installed and disable one-by-one and see if your lag goes away. Good luck!

**Comment by getaaron** [comment] 2015-12-29 22:29
@Shwrndasink's suggestion will do in a pinch but that's really a horrible user experience. Atom should be able to tell me which package is making everything slow.

**Comment by 50Wliu** [comment] 2015-12-29 22:31
@getaaron You might want to check out @mark-hahn's [package-cop](https://atom.io/packages/package-cop) package which bisects all the packages to find which one is causing the issue.

**Comment by omarcuba** [comment] 2016-09-26 03:22
Even I am using a ssd and it crashes
![image](https://cloud.githubusercontent.com/assets/5275497/18821730/82c68c14-836e-11e6-91b8-d73748cad3fb.png)

**Comment by PIXPOINT** [comment] 2016-11-16 12:19
I had similar problems. High CPU utilization, slow UI. I could solve the problem by running Atom via "run as admin" on Windows.

![help](https://cloud.githubusercontent.com/assets/19437713/20346978/38e6a4b2-abff-11e6-9816-3a400d2182b1.PNG)

**Comment by KingGeneral** [comment] 2017-02-10 00:41
the same happen when user use too much UI plugin that modified the UI, idk why but i need to manually disable some plugin when i not use it.
