### ISSUE TITLE
1.12.7 (64 bit) dep on libXss.so.1 tries to dep install 686 packages

### ISSUE THREAD

**Issue by philwyett-hemi** [atom/atom#13417] opened 2016-12-09 19:58 UTC
Terminal below from CentOS 7.3 (7.3 packages as of Continuous Release CR repo)

```
[philwyett@hemi-yoda Downloads]$ sudo yum localinstall atom.x86_64.rpm 
[sudo] password for philwyett: 
Loaded plugins: changelog, fastestmirror, langpacks
Examining atom.x86_64.rpm: atom-1.12.7-0.1.x86_64
Marking atom.x86_64.rpm as an update to atom-1.12.6-0.1.x86_64
Resolving Dependencies
--> Running transaction check
---> Package atom.x86_64 0:1.12.6-0.1 will be updated
---> Package atom.x86_64 0:1.12.7-0.1 will be an update
--> Processing Dependency: libXss.so.1 for package: atom-1.12.7-0.1.x86_64
adobe-linux-x86_64                                       |  951 B     00:00     
base                                                     | 3.6 kB     00:00     
cr                                                       | 3.4 kB     00:00     
epel/x86_64/metalink                                     |  18 kB     00:00     
epel                                                     | 4.3 kB     00:00     
extras                                                   | 3.4 kB     00:00     
hemi                                                     | 3.0 kB     00:00     
hemi-epel                                                | 3.0 kB     00:00     
updates                                                  | 3.4 kB     00:00     
(1/10): base/7/x86_64/group_gz                             | 155 kB   00:00     
(2/10): epel/x86_64/group_gz                               | 170 kB   00:01     
(3/10): extras/7/x86_64/primary_db                         | 166 kB   00:01     
(4/10): hemi/primary_db                                    |  11 kB   00:00     
(5/10): hemi-epel/primary_db                               | 3.7 kB   00:00     
(6/10): epel/x86_64/updateinfo                             | 679 kB   00:04     
(7/10): epel/x86_64/primary_db                             | 4.4 MB   00:10     
(8/10): cr/7/x86_64/primary_db                             | 3.7 MB   00:15     
(9/10): base/7/x86_64/primary_db                           | 5.3 MB   00:15     
(10/10): updates/7/x86_64/primary_db                       | 9.1 MB   00:16     
adobe-linux-x86_64/primary                                 | 1.2 kB   00:00     
Determining fastest mirrors
Including mirror: mirror.bytemark.co.uk
Including mirror: anorien.csc.warwick.ac.uk
Including mirror: mirrors.ukfast.co.uk
Including mirror: epel.check-update.co.uk
 * epel: mirror.bytemark.co.uk
Including mirror: mirrors.melbourne.co.uk
Including mirror: centos.mirroring.pulsant.co.uk
Including mirror: mirror.sov.uk.goscomb.net
Including mirror: repo.uk.bigstepcloud.com
Including mirror: centos.mirrors.nublue.co.uk
Including mirror: mirror.mhd.uk.as44574.net
Including mirror: mirror.sax.uk.as61049.net
Including mirror: mirror.ox.ac.uk
 * extras: mirrors.melbourne.co.uk
adobe-linux-x86_64                                                          2/2
--> Running transaction check
---> Package libXScrnSaver.i686 0:1.2.2-6.1.el7 will be installed
--> Processing Dependency: libc.so.6(GLIBC_2.4) for package: libXScrnSaver-1.2.2-6.1.el7.i686
--> Processing Dependency: libXext.so.6 for package: libXScrnSaver-1.2.2-6.1.el7.i686
--> Processing Dependency: libX11.so.6 for package: libXScrnSaver-1.2.2-6.1.el7.i686
--> Running transaction check
---> Package glibc.i686 0:2.17-157.el7_3.1 will be installed
--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.17-157.el7_3.1.i686
--> Processing Dependency: libfreebl3.so for package: glibc-2.17-157.el7_3.1.i686
---> Package libX11.i686 0:1.6.3-3.el7 will be installed
--> Processing Dependency: libxcb.so.1 for package: libX11-1.6.3-3.el7.i686
---> Package libXext.i686 0:1.3.3-3.el7 will be installed
--> Running transaction check
---> Package libxcb.i686 0:1.11-4.el7 will be installed
--> Processing Dependency: libXau.so.6 for package: libxcb-1.11-4.el7.i686
---> Package nss-softokn-freebl.i686 0:3.16.2.3-14.4.el7 will be installed
--> Running transaction check
---> Package libXau.i686 0:1.0.8-2.1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                Arch       Version               Repository        Size
================================================================================
Updating:
 atom                   x86_64     1.12.7-0.1            /atom.x86_64     241 M
Installing for dependencies:
 glibc                  i686       2.17-157.el7_3.1      cr               4.2 M
 libX11                 i686       1.6.3-3.el7           cr               610 k
 libXScrnSaver          i686       1.2.2-6.1.el7         base              24 k
 libXau                 i686       1.0.8-2.1.el7         base              29 k
 libXext                i686       1.3.3-3.el7           base              39 k
 libxcb                 i686       1.11-4.el7            base             202 k
 nss-softokn-freebl     i686       3.16.2.3-14.4.el7     cr               188 k

Transaction Summary
================================================================================
Install             ( 7 Dependent packages)
Upgrade  1 Package

Total size: 247 M
Total download size: 5.3 M
Is this ok [y/d/N]

```

**Comment by philwyett-hemi** [comment] 2016-12-09 20:23
In the spec file to make it cleaner for fedora and RHEL (+ derivatives i.e. CentOS/Scientific Linux) that have 'libXScrnSaver' and for alternate RPM distros i.e. SUSE that have libXss.
```

%if 0%{?fedora} || 0%{?rhel}
Requires: libXScrnSaver
%else
Requires: libXss1
%endif
```

**Comment by philwyett-hemi** [comment] 2016-12-10 15:51
See pull request: https://github.com/atom/atom/pull/13421

These commits fix the issue and also adds a few doc cleanups related to fedora and RHEL / CentOS.

**Comment by cobexer** [comment] 2016-12-11 15:13
The **libXss.so.1** requirement is the 32bit library, the 64 bit dependency has to be called **libXss.so.1()(64bit)** and that also works on Fedora
Fedora 25 container output 64bit dependency:
```
[root@6f34ccb1f615 /]# dnf whatprovides "libXss.so.1()(64bit)"
libXScrnSaver-1.2.2-10.fc24.x86_64 : X.Org X11 libXss runtime library
Repo        : fedora
```
Fedora 25 container output 32bit dependency:
```
[root@6f34ccb1f615 /]# dnf whatprovides libXss.so.1
libXScrnSaver-1.2.2-10.fc24.i686 : X.Org X11 libXss runtime library
Repo        : fedora
```

Why is automatic dependency generation even disabled in the spec file?

**Comment by philwyett-hemi** [comment] 2016-12-11 15:45
@cobexer Atom is designed for 64-bit systems. Efforts are being made on the 32-bit side, but I have limited knowledge of these.

A previous build of atom failed to install due to lack of libXScrnSaver (or libXss1 on SUSE) on many systems and an explicit requires was added. The current incarnation that features in trunk and 1.12.7 is on a shared object, which is a big no no and breaks install trying to install 686 packages. The code I have supplied fixes the issue for Fedora, RHEL (plus derivatives i.e CentOS) and SUSE. Other avenues/methods can be pursued once clean releases resume.

**Comment by cobexer** [comment] 2016-12-11 16:43
@philwyett-hemi I don't care about 32bit :) I just pointed out that the added requirement was a 32bit one which is not going to help a 64bit package.

I'm not sure I understand what you are trying to say with the second paragraph... why is a dependency on a shared object a "big no no" - I mean it is exactly what the requirement is! atom is not going to search for some shared object installed by a package named "libXScrnSaver" it is only going to load a library called **libXss.so.1** from the same architecture. Depending on the shared object is a hard requirement.

From what I can tell atom also has at least the dependencies listed below:
```
/usr/share/atom-beta # readelf -d atom|grep NEED
 0x0000000000000001 (NEEDED)             Shared library: [libnode.so]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgtk-x11-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgdk-x11-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libatk-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgio-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpangocairo-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgdk_pixbuf-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libcairo.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpango-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libfontconfig.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgobject-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdbus-1.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXi.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXcursor.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXdamage.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXrandr.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libXcomposite.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXext.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXfixes.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libXrender.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXtst.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXss.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgconf-2.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libgmodule-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libnss3.so]
 0x0000000000000001 (NEEDED)             Shared library: [libnssutil3.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsmime3.so]
 0x0000000000000001 (NEEDED)             Shared library: [libnspr4.so]
 0x0000000000000001 (NEEDED)             Shared library: [libffmpeg.so]
 0x0000000000000001 (NEEDED)             Shared library: [libasound.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcups.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libexpat.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```
Not listing them in the RPM requires will only cause problems sooner or later.
I'm really interested in the reasoning behind calling shared object dependencies a "big no no" because while the RPM may not have them, the ELF binary does.

**Comment by philwyett-hemi** [comment] 2016-12-11 18:57
Here is what building atom trunk with no dep on libXScrnSaver or libXss.so.1 gives us on fedora 25.

```
[philwyett@hemi-r2d2 x86_64]$ sudo dnf install atom-1.14.0.dev.9efae86-0.1.fc25.x86_64.rpm 
[sudo] password for philwyett: 
Last metadata expiration check: 0:42:44 ago on Sun Dec 11 17:29:41 2016.
Dependencies resolved.
================================================================================
 Package                  Arch   Version                     Repository    Size
================================================================================
Installing:
 atom                     x86_64 1.14.0.dev.9efae86-0.1.fc25 @commandline  67 M
 ed                       x86_64 1.13-1.fc25                 fedora        77 k
 esmtp                    x86_64 1.2-4.fc25                  fedora        54 k
 libesmtp                 x86_64 1.0.6-10.fc24               fedora        65 k
 liblockfile              x86_64 1.09-4.fc24                 fedora        28 k
 m4                       x86_64 1.4.17-9.fc24               fedora       266 k
 mailx                    x86_64 12.5-19.fc24                fedora       258 k
 ncurses-compat-libs      x86_64 6.0-6.20160709.fc25         fedora       302 k
 redhat-lsb-core          x86_64 4.1-33.fc25                 updates       42 k
 redhat-lsb-submod-security
                          x86_64 4.1-33.fc25                 updates       19 k
 spax                     x86_64 1.5.3-6.fc24                fedora       213 k
 util-linux-user          x86_64 2.28.2-1.fc25               fedora        90 k

Transaction Summary
================================================================================
Install  12 Packages

Total size: 68 M
Total download size: 1.4 M
Installed size: 252 M
Is this ok [y/N]: y
Downloading Packages:
(1/11): redhat-lsb-core-4.1-33.fc25.x86_64.rpm  194 kB/s |  42 kB     00:00    
(2/11): redhat-lsb-submod-security-4.1-33.fc25.  70 kB/s |  19 kB     00:00    
(3/11): ed-1.13-1.fc25.x86_64.rpm               234 kB/s |  77 kB     00:00    
(4/11): m4-1.4.17-9.fc24.x86_64.rpm             504 kB/s | 266 kB     00:00    
(5/11): ncurses-compat-libs-6.0-6.20160709.fc25 563 kB/s | 302 kB     00:00    
(6/11): util-linux-user-2.28.2-1.fc25.x86_64.rp 103 kB/s |  90 kB     00:00    
(7/11): esmtp-1.2-4.fc25.x86_64.rpm             289 kB/s |  54 kB     00:00    
(8/11): mailx-12.5-19.fc24.x86_64.rpm           138 kB/s | 258 kB     00:01    
(9/11): libesmtp-1.0.6-10.fc24.x86_64.rpm       323 kB/s |  65 kB     00:00    
(10/11): spax-1.5.3-6.fc24.x86_64.rpm           144 kB/s | 213 kB     00:01    
(11/11): liblockfile-1.09-4.fc24.x86_64.rpm     228 kB/s |  28 kB     00:00    
--------------------------------------------------------------------------------
Total                                           248 kB/s | 1.4 MB     00:05     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : liblockfile-1.09-4.fc24.x86_64                             1/12 
  Installing  : libesmtp-1.0.6-10.fc24.x86_64                              2/12 
  Installing  : esmtp-1.2-4.fc25.x86_64                                    3/12 
  Installing  : util-linux-user-2.28.2-1.fc25.x86_64                       4/12 
  Installing  : spax-1.5.3-6.fc24.x86_64                                   5/12 
  Installing  : ncurses-compat-libs-6.0-6.20160709.fc25.x86_64             6/12 
  Installing  : mailx-12.5-19.fc24.x86_64                                  7/12 
  Installing  : m4-1.4.17-9.fc24.x86_64                                    8/12 
  Installing  : ed-1.13-1.fc25.x86_64                                      9/12 
  Installing  : redhat-lsb-submod-security-4.1-33.fc25.x86_64             10/12 
  Installing  : redhat-lsb-core-4.1-33.fc25.x86_64                        11/12 
  Installing  : atom-1.14.0.dev.9efae86-0.1.fc25.x86_64                   12/12 
  Verifying   : atom-1.14.0.dev.9efae86-0.1.fc25.x86_64                    1/12 
  Verifying   : redhat-lsb-core-4.1-33.fc25.x86_64                         2/12 
  Verifying   : redhat-lsb-submod-security-4.1-33.fc25.x86_64              3/12 
  Verifying   : ed-1.13-1.fc25.x86_64                                      4/12 
  Verifying   : m4-1.4.17-9.fc24.x86_64                                    5/12 
  Verifying   : mailx-12.5-19.fc24.x86_64                                  6/12 
  Verifying   : ncurses-compat-libs-6.0-6.20160709.fc25.x86_64             7/12 
  Verifying   : spax-1.5.3-6.fc24.x86_64                                   8/12 
  Verifying   : util-linux-user-2.28.2-1.fc25.x86_64                       9/12 
  Verifying   : esmtp-1.2-4.fc25.x86_64                                   10/12 
  Verifying   : libesmtp-1.0.6-10.fc24.x86_64                             11/12 
  Verifying   : liblockfile-1.09-4.fc24.x86_64                            12/12 

Installed:
  atom.x86_64 1.14.0.dev.9efae86-0.1.fc25                                       
  ed.x86_64 1.13-1.fc25                                                         
  esmtp.x86_64 1.2-4.fc25                                                       
  libesmtp.x86_64 1.0.6-10.fc24                                                 
  liblockfile.x86_64 1.09-4.fc24                                                
  m4.x86_64 1.4.17-9.fc24                                                       
  mailx.x86_64 12.5-19.fc24                                                     
  ncurses-compat-libs.x86_64 6.0-6.20160709.fc25                                
  redhat-lsb-core.x86_64 4.1-33.fc25                                            
  redhat-lsb-submod-security.x86_64 4.1-33.fc25                                 
  spax.x86_64 1.5.3-6.fc24                                                      
  util-linux-user.x86_64 2.28.2-1.fc25                                          

Complete!
[philwyett@hemi-r2d2 x86_64]$ atom 
[philwyett@hemi-r2d2 x86_64]$ /usr/share/atom/atom: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```

As you can see auto dependencies did not work in this case. I have yet to find time to dig deeper.

If we started listing requires per arch in the spec file, what a nightmare that would create and quickly lead to breakage.

There are many conventions when building RPMS:

https://fedoraproject.org/wiki/Category:Package_Maintainers
https://fedoraproject.org/wiki/Packaging:Guidelines#File_Dependencies

Using conditionals as I have done in the fix, is the standard way of correcting this error.

This requires will be revisited and investigated to hopefully drop it. Until then, this is the best solution.

Note: I am not a member of the atom dev team and am doing this on my own time as a developer and user of atom very happily on CentOS 7.x.

**Comment by vishytk** [comment] 2016-12-12 05:34
For now, On Fedora 25, following command will do the trick.

# rpm -ivh --nodeps atom-1.12.7.x86_64.rpm OR

# rpm -Uvh --nodeps atom-1.12.7.x86_64.rpm (for upgrade)

**Comment by philwyett-hemi** [comment] 2016-12-12 07:13
@vishytk We should fix issues and not work round them. Anyone who admins production systems does not do things like this.

**Comment by vishytk** [comment] 2016-12-12 07:17
Yes. I totally agree.

This is just for users to get going till the issue is resolved.

**Comment by as-cii** [comment] 2016-12-12 15:02
Thanks to @philwyett-hemi this will be fixed in the next release. Thanks everyone for the feedback!

**Comment by vishytk** [comment] 2017-01-06 04:49
Looks like this issue has popped up again with 1.12.9

sudo dnf install atom-1.12.9.x86_64.rpm
Last metadata expiration check: 0:17:22 ago on Fri Jan  6 09:58:18 2017.
Dependencies resolved.
==========================================================================================
 Package                   Arch          Version                Repository           Size
==========================================================================================
Installing:
 glibc                     i686          2.24-4.fc25            updates             4.0 M
 libX11                    i686          1.6.4-1.fc25           fedora              614 k
 libXScrnSaver             i686          1.2.2-10.fc24          fedora               28 k
 libXau                    i686          1.0.8-6.fc24           fedora               34 k
 libXext                   i686          1.3.3-4.fc24           fedora               43 k
 libcrypt-nss              i686          2.24-4.fc25            updates              43 k
 libxcb                    i686          1.12-1.fc25            fedora              227 k
 nss-softokn-freebl        i686          3.27.0-1.0.fc25        fedora              209 k
Upgrading:
 atom                      x86_64        1.12.9-0.1             @commandline         81 M

Transaction Summary
==========================================================================================
Install  8 Packages
Upgrade  1 Package

**Comment by vishytk** [comment] 2017-01-14 07:54
And this continues in 1.13.0 as well...

sudo dnf install atom-1.13.0.x86_64.rpm
Last metadata expiration check: 2:28:31 ago on Sat Jan 14 10:52:24 2017.
Dependencies resolved.
==========================================================================================
 Package                   Arch          Version                Repository           Size
==========================================================================================
Installing:
 atom                      x86_64        1.13.0-0.1             @commandline         82 M
 glibc                     i686          2.24-4.fc25            updates             4.0 M
 libX11                    i686          1.6.4-3.fc25           updates             623 k
 libXScrnSaver             i686          1.2.2-10.fc24          fedora               28 k
 libXau                    i686          1.0.8-6.fc24           fedora               34 k
 libXext                   i686          1.3.3-4.fc24           fedora               43 k
 libcrypt-nss              i686          2.24-4.fc25            updates              43 k
 libxcb                    i686          1.12-1.fc25            fedora              227 k
 nss-softokn-freebl        i686          3.27.0-1.0.fc25        fedora              209 k

Transaction Summary
==========================================================================================
Install  9 Packages

Total size: 87 M
Total download size: 5.2 M
Installed size: 265 M
Is this ok [y/N]: n
Operation aborted.

**Closed** 2017-01-19 12:49 UTC
Labels: bug, linux
