### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.57.0\res...

### ISSUE THREAD

**Issue by kajal-kumari-ml** [atom/atom#22538] opened 2021-06-03 21:33 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\hp\AppData\Local\atom\app-1.57.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:140

Error: The specified module could not be found.
\\?\C:\Users\hp\AppData\Local\atom\app-1.57.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2893541)
    at get_manager (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2893643)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2893769)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1118316)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1224088)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1222073)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:286551)
```

### Commands

```
     -2:02.1.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
autocomplete-clang 0.13.0 
build 0.70.0 
build-platformio 1.2.4 
busy-signal 2.0.1 
file-icons 2.1.39 
intentions 1.1.5 
language-babel 2.85.0 
language-ini 1.23.0 
language-javascript-jsx 0.3.7 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
meteor-api 2.20.0 
meteor-snippets 0.5.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
platomformio 0.7.1 
script 3.32.2 
tool-bar 1.2.0 
```

**Comment by darangi** [comment] 2021-08-23 07:44
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2021-08-23 07:44 UTC
