### ISSUE TITLE
Uncaught Error: spawn /Users/moonnshinwoo/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/...

### ISSUE THREAD

**Issue by chocoma87** [atom/atom#10625] opened 2016-01-30 17:22 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/moonnshinwoo/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/moonnshinwoo/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Users/moonnshinwoo/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -8:26.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -8:26.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -8:25.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:25.2.0 about:view-release-notes (atom-pane.pane.active)
     -7:58.6.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -7:46.8.0 application:add-project-folder (button.btn.btn-primary)
  8x -5:18.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:14.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
  5x -1:08.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:07.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-01-30 21:02
Thanks for reporting!  This looks like a duplicate of #9559 though, so please subscribe there for updates.

**Closed by 50Wliu** 2016-01-30 21:02 UTC
