### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 39Error: Cannot call...

### ISSUE THREAD

**Issue by BuZZ-dEE** [atom/atom#17360] opened 2018-05-18 19:49 UTC
**Atom**: 1.27.0 x64
**Electron**: 1.8.4
**OS**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 39
Error: Cannot call function 'getPosition' on missing remote object 39
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)

```
At /usr/lib/electron/resources/electron.asar/renderer/api/remote.js:209

Error: Cannot call function 'getPosition' on missing remote object 39
Error: Cannot call function 'getPosition' on missing remote object 39
    at throwRPCError (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
    at Object.exception (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.remoteMemberFunction (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:113:16)
    at AtomEnvironment.getWindowDimensions (/usr/lib/atom/src/atom-environment.js:680:34)
    at AtomEnvironment.storeWindowDimensions (/usr/lib/atom/src/atom-environment.js:717:34)
    at WindowEventHandler.handleWindowResize (/usr/lib/atom/src/window-event-handler.js:195:26)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.4 
atom-ide-debugger-node 0.7.1 
atom-ide-debugger-python 0.7.1 
atom-ide-ui 0.11.2 
atom-java-snippets 0.5.1 
atom-ternjs 0.18.3 
autocomplete-bash-builtins 0.3.5 
autocomplete-jsp 1.2.1 
build 0.70.0 
build-cmd 0.5.2 
build-gradle 0.6.0 
build-python 0.9.3 
build-sass 0.11.0 
build-tsc 0.7.2 
busy-signal 1.4.3 
css-hyperclick 0.1.5 
cursor-history 0.13.1 
docblockr 0.13.7 
editorconfig 2.2.2 
emmet 2.4.3 
flow-ide 1.11.0 
git-blame 1.6.0 
git-plus 7.10.2 
git-projects 1.17.0 
git-time-machine 2.0.1 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-css 0.3.0 
ide-flowtype 0.23.0 
ide-html 0.4.2 
ide-java 0.8.3 
ide-json 0.2.1 
ide-python 0.9.2 
ide-typescript 0.7.6 
intentions 1.1.5 
Java-Bytecode-Disassembler 0.7.2 
java-generator 2.2.3 
js-hyperclick 1.13.0 
js-refactor 0.8.1 
language-freemarker 0.2.0 
language-gradle 0.0.5 
language-ini 1.20.0 
language-svg 0.9.4 
language-typescript-grammars-only 1.6.0 
linter 2.2.0 
linter-csslint 2.0.1 
linter-scss-lint 3.1.1 
linter-shellcheck 1.4.7 
linter-tslint 1.9.1 
linter-ui-default 1.7.1 
linter-xmllint 1.4.4 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
open-file-in 1.2.3 
pigments 0.40.2 
prettier-atom 0.53.0 
project-manager 3.3.5 
refactor 0.11.5 
remote-edit 1.9.0 
split-diff 1.5.2 
svg-preview 0.12.1 
teletype 0.13.2 
terminal-plus 0.14.5 
tool-bar 1.1.7 
```

**Comment by rsese** [comment] 2018-05-18 20:39
Thanks for the report!

> Sorry, but no idea about what happened.

No problem, this looks like a duplicate of #16630 so you can subscribe there if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-18 20:39 UTC
