### ISSUE TITLE
Uncaught Error: Tried to unload active package 'Sublime-Style-Column-Selection'

### ISSUE THREAD

**Issue by Dalinar42** [atom/atom#17324] opened 2018-05-14 22:17 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'Sublime-Style-Column-Selection'

```
At C:\Users\Austin Dean Nelson\AppData\Local\atom\app-1.26.1\resources\app\src\package-manager.js:630

Error: Tried to unload active package 'Sublime-Style-Column-Selection'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.26.1/resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.unload (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-manager.js:458:36)
    at PackageManager.module.exports.PackageManager.install (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-manager.js:468:18)
    at PackageCard.install (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-card.js:825:33)
    at HTMLButtonElement.installButtonClickHandler (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/settings-view/lib/package-card.js:302:22)
```

### Commands

```
```

### Non-Core Packages

```
atom-monokai 0.10.9 
atom-wrap-in-tag 0.6.0 
atomic-game-engine 0.4.5 
auto-update-plus 0.5.6 
browse 1.10.6 
build 0.70.0 
busy-signal 1.4.3 
ctrl-dir-scroll 0.2.5 
minimap 4.29.8 
monokai-dark 1.5.0 
multi-cursor 2.1.5 
satisfy-dependencies 0.4.2 
set-syntax 0.4.0 
sublime 0.5.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
sublime-word-navigation 0.2.0 
sublimify 0.10.0 
tag 0.5.0 
text-manipulation 0.6.0 
```

**Comment by rsese** [comment] 2018-05-15 17:35
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #16873 so you can subscribe there for updates if you'd like.  If you remember what you were doing at the time of the error, please let us know in #16873.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-15 17:35 UTC
