### ISSUE TITLE
Scrollbar is ugly when first start/open

### ISSUE THREAD

**Issue by miftahafina** [atom/atom#9669] opened 2015-11-18 03:14 UTC
When I open atom, and yes, it automatically open the last file I edited. But the problem is scroll bar is ugly (like standard scrollbar in google chrome). I must change to another tab and back to change the scrollbar.
I'm using ubuntu 14.04 (64bit) using atom 1.3.0-beta0 when i saw this error.

**Comment by mnquintana** [comment] 2015-11-18 03:16
This looks like a duplicate of https://github.com/atom/atom/issues/9189

**Closed by mnquintana** 2015-11-18 03:16 UTC
