### ISSUE TITLE
Grapheme clusters are not properly supported

### ISSUE THREAD

**Issue by craigotis** [atom/atom#13360] opened 2016-11-30 13:09 UTC
**EDIT: The emoji is now rendered properly but does not behave properly.  See https://github.com/atom/atom/issues/13360#issuecomment-272671671.**

I'm running Atom 1.12.6 on macOS Sierra 10.12.1. While many single-codepoint emoji like 👻 are properly supported, emojis consisting of multiple codepoints (connected via [zero-width joiners](http://emojipedia.org/zero-width-joiner/)) like 👩‍👩‍👦‍👦 are not.

Pasting the first into Atom:

![screen shot 2016-11-30 at 8 08 31 am](https://cloud.githubusercontent.com/assets/1620098/20753399/3f48f3fc-b6d4-11e6-82c2-af4b637237c3.png)

Pasting the second:

![screen shot 2016-11-30 at 8 08 43 am](https://cloud.githubusercontent.com/assets/1620098/20753407/451c35dc-b6d4-11e6-9503-e29e7f79bd68.png)

It seems the joiners are removed, and the individual codepoints are inserted as separate characters. You can reproduce this by simply copy-pasting the emojis from this issue, or using the emoji selector (Ctrl + Command + Space) on a Mac.

**Comment by 50Wliu** [comment] 2016-11-30 20:52
Confirmed on Atom 1.14.0-dev-d3d06fb, Windows 10 64.

**Comment by 50Wliu** [comment] 2017-01-14 01:03
@Ben3eeE or @ungb I can no longer reproduce this on Atom 1.15.0-dev-d5785a1.  Can one of you test beta just to confirm?

**Comment by Ben3eeE** [comment] 2017-01-14 09:08
@50Wliu I copied and pasted the emoji in the body of the issue to an empty TextEditor. In Atom 1.13.0 it is rendered as 4 emojis. In Atom 1.14.0-beta1 it is rendered as one emoji. Using Windows 10 x64.

In Atom 1.14.0-beta1 the emoji 👩‍👩‍👦‍👦counts as 12 columns so moving the cursor past it is not working correctly.

**Comment by 50Wliu** [comment] 2017-01-15 03:49
Yeah ok this is weird.  Here's a gif.
![emoji-please](https://cloud.githubusercontent.com/assets/2766036/21960083/22ca6f62-daab-11e6-969f-622ca7fe8542.gif)
Apologies for the snow...forgot to turn off that package when recording.
Here's what I did:
1. Paste the emoji, go to column 1 by pressing the left arrow key (note how the column count goes 12 -> 10 -> 9 -> 7 -> 6 -> 4 -> 3 -> 1).  Works the other way as well.
2. At column 1, press the right arrow key and type a letter.  Repeat until you are out of the emoji.
3. Paste the emoji on a new line.  Keep backspacing.
4. Paste the emoji.  Press the left arrow key and backspace.  Repeat until the line joins with the previous line.

**Comment by ungb** [comment] 2017-02-02 16:30
I can repro the issue with steps @50Wliu you provided.  Should we create a new issue for this since the title `Grapheme clusters are not properly supported` seems to be working, but getting strange behavior.  

I used this emoji 👩‍👩‍👦‍👦
```
atom --version
Atom    : 1.15.0-dev-81e8ccc
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by 50Wliu** [comment] 2017-02-02 18:21
@ungb I'll leave the decision for you whether to create a new issue.

**Comment by milesj** [comment] 2017-04-12 01:28
Going to jump into this issue. Seems like gender specific emoji are having problems with rendering. Not sure if it's Atom or Chrome. For example, the female doctor (👩‍⚕️) renders as a female and symbol (image attached). 

<img width="137" alt="screen shot 2017-04-11 at 18 28 21" src="https://cloud.githubusercontent.com/assets/143744/24937312/b32ee2c2-1ee4-11e7-849d-6aff21c8a920.png">

**Comment by 50Wliu** [comment] 2017-04-12 02:06
That's a Chrome issue.

**Comment by samkelleher** [comment] 2017-07-26 19:10
I also have the same issue as @milesj , but the affected emoji render perfectly in chrome, but break in anything within electron. I'm investigating the issue.

**Comment by HeinrichTremblay** [comment] 2018-01-20 12:47
Any update on this issue?

**Comment by HeinrichTremblay** [comment] 2018-01-20 12:51
I'm having the same issue as @milesj 

<img width="346" alt="screen shot 2018-01-20 at 8 48 30 pm" src="https://user-images.githubusercontent.com/5926155/35183571-60722dd6-fe23-11e7-9efb-5d3b81e56d6e.png">

**Comment by Arcanemagus** [comment] 2019-12-30 06:39
I'm no longer able to reproduce this in Atom 1.44.0-nightly2, this was likely fixed in one of the Electron upgrades since this issue was filed.

I can still see the column count described, however that seems to be common to all editors that I have to open the file. If somebody feels that should be changed please open a new issue with your reasoning 😉.

**Closed by Arcanemagus** 2019-12-30 06:39 UTC
Labels: bug, editor-rendering, triaged
