### ISSUE TITLE
Segfault after Ubuntu 17.10 upgrade

### ISSUE THREAD

**Issue by khaeru** [atom/atom#15944] opened 2017-10-19 20:39 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following: [snip]

### Description

After an upgrade to Ubuntu 17.10 "artful aardvark", and installing 1.21.1 from the official amd64 .deb, Atom will not start.

### Steps to Reproduce

`$ atom`

**Expected behavior:** Atom starts.

**Actual behavior:** `/usr/bin/atom: line 129:  9862 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1`

**Reproduces how often:** 100%

### Versions

Ubuntu 17.10
https://github.com/atom/atom/releases/tag/v1.21.1

`atom --version` gives no output.

```
$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.1
```

**Comment by laurentpayot** [comment] 2017-10-20 14:12
Same here after I upgraded from Ubuntu 17.04 to 17.10.

With atom installed via atom.io debian package:
```shell
laurent@pinkmoon:~$ atom
laurent@pinkmoon:~$ /usr/bin/atom : ligne 129 : 24411 Erreur de segmentation  (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

laurent@pinkmoon:~$ atom --version
laurent@pinkmoon:~$ 
```

With atom installed via snap:
```shell
laurent@pinkmoon:~$ atom
Erreur de segmentation (core dumped)
laurent@pinkmoon:~$ atom --version
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "overlay-scrollbar"
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
laurent@pinkmoon:~$
```

**Comment by rsese** [comment] 2017-10-20 19:15
Thanks for the reports - when you started in safe mode, was there any difference at all or did Atom crash right after starting?

I'll try to install 17.10 and test today.

**Comment by laurentpayot** [comment] 2017-10-20 19:41
I didn't even know that there was a `--safe` option. It's quite ugly but it is working in safe mode.

**Comment by khaeru** [comment] 2017-10-20 19:45
Thanks, @rsese! I did follow the instruction in the bug template to run `atom --safe`. Unfortunately (unlike @laurentpayot) I get the same segfault with that option.

**Comment by rsese** [comment] 2017-10-21 05:55
Finally had a chance to install 17.10 and then installed Atom 1.21.1.  I ran into the error described in https://github.com/atom/atom/issues/14358, but after running `sudo apt --fix-broken install`, that fixed things up and Atom started ok. 

@khaeru did you also try temporarily resetting to factory defaults?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by khaeru** [comment] 2017-10-22 03:52
@rsese yes—that was part of the "Prerequisites" in the bug template (along with `--safe`, as we discussed previously) so did I try that. I had been using a custom location by setting the `ATOM_HOME` environment variable, so I *also* unset that. Same symptoms.

**Comment by Puller** [comment] 2017-10-22 13:15
Same here...
Really annoying. Reset to Factory settings and Safe mode do not help either!

**Comment by laurentpayot** [comment] 2017-10-23 08:24
Are you guys using gnome system-monitor? It displays system informations in gnome shell status bar, such as memory usage, cpu usage, network rate etc. It may interfere with atom title display, because that's the only thing I can remember playing with between my non-working and my working atom.

**Comment by Puller** [comment] 2017-10-23 09:13
Hi,

I don't use gnome-system-monitor.
However, I reinstalled Ubuntu 17.10 from scratch and now it's working with
the official Debian package from the Atom website. The snappy package from
Ubuntu failed however during installation. Seems to be an Ubuntu problem...

Regards,

Ben


2017-10-23 10:27 GMT+02:00 Laurent Payot <notifications@github.com>:

**Comment by khaeru** [comment] 2017-10-23 17:06
FYI, I have two computers: a laptop and a desktop; the former displays the bug, the latter does not (ie. Atom 1.21.1 works, no segfault, after Ubuntu 17.10 upgrade). I will try to diff a list of installed packages between the two systems, and inspect Atom-related files, sometime today or tomorrow to determine what might be causing this issue.

In any case, it would be lovely if there were also an `atom-dbg` package that could be installed to produce a human-readable stack trace when things like this happen…

PS. @laurentpayot `gnome-system-monitor` appears to be installed on both systems, but like @Puller I never use it.

**Comment by pcnate** [comment] 2017-10-23 17:10
this appears to affect back to 1.10 on ubuntu 17.10 so it isn't a recent change

**Comment by pcnate** [comment] 2017-10-23 19:16
I skipped the state of: _My code works, I don't know why_.

While rebooting to switch to the previous kernel for testing which failed to load the GUI, I discovered 4 packages from the PPA that could be updated. After updating them, and rebooting back to the GUI and Atom works!
    2017-10-23 14:08:25 upgrade libicu-dev:amd64 57.1-6 57.1-6ubuntu0.2
    2017-10-23 14:08:27 upgrade icu-devtools:amd64 57.1-6 57.1-6ubuntu0.2
    2017-10-23 14:08:27 upgrade libicu57:i386 57.1-6 57.1-6ubuntu0.2
    2017-10-23 14:08:28 upgrade libicu57:amd64 57.1-6 57.1-6ubuntu0.2

**Comment by khaeru** [comment] 2017-10-23 21:00
Hi all—this has now mysteriously fixed itself on my system, too.
1. Noticed that I received the same upgrades to `libicu57` as @pcnate (however I don't think these are from the `webupd8team/atom` PPA, but from Ubuntu's official repositories), as well as others to `libcurl3{,-gnutls}` and `libmysqlclient20`.
2. Tried `atom`, `atom --safe`, `atom --version` etc.—same segfault.
3. Rebooted.
4. `atom`, `atom --safe` and `atom --version` now work. ¯\\\_(ツ)\_/¯

So, @rsese, I suppose it can be closed unless it is still affecting someone else. Sorry for the spam.

P.S. for any dev who may care at a later date, the last crash of Atom at 2—unlike all others before—was caught by Ubuntu apport's tool, which displayed the message "atom crashed with SIGSEGV in __start_google_malloc()". No idea where that method appears in Atom or its dependencies.

**Comment by rsese** [comment] 2017-10-24 04:29
Thanks for the update @khaeru - since we were unable to get a reproduction with the .deb from atom.io (the PPA and the snap are unofficial) on a fresh install of Ubuntu 17.10, we'll go ahead and close for now (but definitely not spam @khaeru, we appreciate the bug report).  But at least we have more information in case other folks run into problems with Ubuntu 17.10, thanks to everyone who chimed in.

**Comment by snaumov** [comment] 2017-11-05 09:55
hi all. Just to add my 5 cents - the same problem is happening to me after an upgrade from 17.04 to 17.10 and that's what ubuntu apport stacktrace contains

![screenshot from 2017-11-05 11-50-49](https://user-images.githubusercontent.com/5119578/32413298-cba9f790-c21f-11e7-8ca6-42f3fcf6fd11.png)
![screenshot from 2017-11-05 11-51-40](https://user-images.githubusercontent.com/5119578/32413299-cbc5ab66-c21f-11e7-9a97-6f39c5d14808.png)

neither of electron based apps work now... Will try to see if I can find something else or if the issue magically disappears.

**Comment by adamdrake** [comment] 2017-11-10 01:35
I have this issue randomly as well, and with all Electron apps (though not atom).  I can confirm it occurs with 17.10 and the latest version of Slack and VS Code.  Any developments on this issue?

**Comment by laurentpayot** [comment] 2017-11-10 10:53
Just like atom, Visual Studio Code is based on Electron. So it might be an Electron issue. This link may help: https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20crash%20ubuntu

**Comment by settel-np** [comment] 2017-11-21 17:57
Issue is not solved for me, atom still crashes.
All Ubuntu updates have been applied successfully, there are no broken packages left. And I rebooted several times after upgrading, too.

Using atom 1.22.1 from atom.io under Ubuntu 17.10 (upgraded from Ubuntu 17.04).

```
 $ dpkg -l atom libicu-dev icu-devtools libicu57
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  atom           1.22.1       amd64        A hackable text editor for the 21
ii  icu-devtools   57.1-6ubuntu amd64        Development utilities for Interna
ii  libicu-dev     57.1-6ubuntu amd64        Development files for Internation
ii  libicu57:amd64 57.1-6ubuntu amd64        International Components for Unic
ii  libicu57:i386  57.1-6ubuntu i386         International Components for Unic

 $ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.1


 $ atom
/usr/bin/atom: line 129: 23536 Segmentation fault      nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

 $ ls -l nohup.out 
-rw-rw-r-- 1 settel settel    0  Nov 21 18:55 nohup.out
```

BTW: Running atom as root (strongly discouraged! Don't try this at home!) works, the editor shows up.

**Comment by pcnate** [comment] 2017-11-22 00:54
I would expect that when you run it as root, then ~/.atom becomes /root/.atom instead of /home/you/.atom

**Comment by settel-np** [comment] 2017-11-22 14:25
> I would expect when you run it as root, then ~/.atom becomes /root/.atom instead of /home/you/.atom

I use sudo -i to run it as root, so ~/.atom is still /home/USER/.atom. But it doesn't matter, Atom crashes way before it even gets to read the .atom/ folder. 


> Have you tried backing up then removing ~/.atom?

sure. doesn't change the outcome.

**Comment by twogood** [comment] 2017-11-23 11:41
As a workaround Try to set GTK2_RC_FILES environment variable to empty when you start the application.

See my blog post https://divideandconquer.se/2017/11/23/workaround-for-crashing-electronatom-applications/

**Comment by settel-np** [comment] 2017-11-23 11:49
That run-as-root-solves-the-problem stuff got me searching for the differences. Some trials later, I figured out that unsetting XDG_CONFIG_DIRS makes atom run:
`XDG_CONFIG_DIRS="" /usr/share/atom/atom`

**Comment by settel-np** [comment] 2017-11-23 11:50
@twogood hehe, you've found a similar workaround at about the same time :-)
`GTK2_RC_FILES="" /usr/share/atom/atom` 
works for me, too

**Comment by twogood** [comment] 2017-11-23 11:57
@settel-np Cool, I'll add that to my blog post! Not less strange though! Maybe it will be solved if I restart with the latest package updates... My update manager is nagging me to reboot :)

**Comment by settel-np** [comment] 2017-11-23 20:52
This issue is not atom-specific, I managed to reproduce the crash with electron quick start application, too. I filed a bugreport with electron, see https://github.com/electron/electron/issues/11234

**Comment by lil5** [comment] 2018-03-07 21:54
I found that if you add 10 or more sources in `GTK_RC_FILES` this issue happens

```
~ $ GTK2_RC_FILES="a:b:c:d:e:f:g:h:i" /usr/share/atom-beta/atom
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
~ $ GTK2_RC_FILES="a:b:c:d:e:f:g:h:i:f" /usr/share/atom-beta/atom
Segmentation fault
```

**Comment by lil5** [comment] 2018-03-07 22:56
In the end I installed https://github.com/atom/atom/releases/tag/v1.21.2 after an uninstall and reboot

**Comment by shemgp** [comment] 2018-09-11 02:35
Upgraded to Ubuntu Cosmic and atom won't start, but atom snap does:
```
 shemgp  shemgp-x230t  ~  $  atom-beta 
 shemgp  shemgp-x230t  ~  $  /usr/bin/atom-beta: line 157: 30355 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
 shemgp  shemgp-x230t  ~  $  atom-beta --safe
 shemgp  shemgp-x230t  ~  $  /usr/bin/atom-beta: line 157: 32460 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

 shemgp  shemgp-x230t  ~  $  XDG_CONFIG_DIRS="" atom-beta
 shemgp  shemgp-x230t  ~  $  /usr/bin/atom-beta: line 157:   547 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

 shemgp  shemgp-x230t  ~  $  atom-beta
 shemgp  shemgp-x230t  ~  $  /usr/bin/atom-beta: line 157:  1983 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
^C
 shemgp  shemgp-x230t  ~  SIGINT  $  GTK2_RC_FILES="" atom-beta
 shemgp  shemgp-x230t  ~  $  /usr/bin/atom-beta: line 157:  3307 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
```

**Comment by rsese** [comment] 2018-09-12 04:45
@shemgp - I think you're running into a different issue since you're on Cosmic, see https://github.com/atom/atom/pull/17904#issuecomment-419395900.

**Comment by madeindjs** [comment] 2018-10-04 06:37
Same issue for me:

~~~bash
$ atom
/usr/bin/atom : ligne 157 : 26264 Erreur de segmentation  (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
$ atom -v
$ XDG_CONFIG_DIRS="" atom
/usr/bin/atom : ligne 157 : 26590 Erreur de segmentation  (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
~~~

This happens just after upgraded to Xubuntu Cosmic Cuttlefish

~~~bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Cosmic Cuttlefish (development branch)
Release:	18.10
Codename:	cosmic
~~~

**Comment by larp-welt** [comment] 2018-10-18 19:59
And same for me:

`/usr/bin/atom: Zeile 157: 19514 Speicherzugriffsfehler  (Speicherabzug geschrieben) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1`

Just after the upgrade to Ubuntu 18.10. 

`No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic`

I've allready redownloaded Atom, reinstalled it, and removed '.atom' too.

**Comment by katian** [comment] 2018-10-19 03:52
And same for me:
```
/usr/bin/atom : ligne 157 :  6040 Erreur de segmentation  (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1> ```
 
Just after the upgrade to Ubuntu 18.10.

 ```
I've allready redownloaded Atom, reinstalled it, and removed `.atom` too.

```
Linux 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rsese** [comment] 2018-10-19 21:21
@madeindjs @larp-welt @katian - please see https://github.com/atom/atom/issues/18268#issuecomment-431438571.  As mentioned by @katian above, 1.32 which is currently in beta should work.

**Comment by thalessa** [comment] 2018-10-22 23:17
Have same problem. Confirming that 1.32 beta works.

**Comment by daviwil** [comment] 2019-01-29 18:52
Since it seems Atom 1.32.0 has resolved this issue, I'll go ahead and close it.  Please feel free to comment here if you are still experiencing the issue and we'll be happy to reopen!

**Closed by daviwil** 2019-01-29 18:52 UTC
Labels: electron, linux, needs-reproduction
