### ISSUE TITLE
close all tabs closes everything regardless of changed state

### ISSUE THREAD

**Issue by schmurfy** [atom/atom#9121] opened 2015-10-12 15:21 UTC
I am using 1.0.19.

The behavior I would expect is to have a popup window to confirm if I am really sure and warn about lost changes.
The behavior I currently see is that it closes everything regardless of whether there are changes or not...

PS: in fact even when closing one pane the behavior is the same, it does not ask anything

**Comment by mnquintana** [comment] 2015-10-12 16:53
Hmmm that's weird - I can't seem to reproduce this with 1.0.19 on OS X 10.10.5. What OS are you using? Can you reproduce this if you quit Atom completely and try reopening it in safe mode? (`atom --safe`) Just to clarify, when you say "changed state" do you mean that this happens if you have unsaved changes? Or that you have uncommitted changes (in a Git repo)?

**Comment by schmurfy** [comment] 2015-10-13 07:52
unsaved changes, I have the confirmation in safe mode so I suppose that's one of my plugins that messed up.... :(

**Comment by schmurfy** [comment] 2015-10-13 08:07
I am starting to have a fair number of packages, what is the best way to find my culprit ?

**Comment by jlarcombe** [comment] 2016-02-11 13:29
This happens for me too with Atom 1.50 on Mac OS X 10.9.5.

Create a new window, create a new file in that window, type something, close the window: the window and tab closes silently with no "<file> has changes, do you want to save them?" warning.

Closing the tab on its own does give the warning.

This also happened when I ran atom with "atom --safe".

**Comment by schmurfy** [comment] 2016-02-11 14:41
for me it was the extension "save-session" which is now unmaintained and partly integrated into atom as I understand. When you ran "atom --safe" was it really running in safe mode ? It should start atom without any addon.

If you have "save-session" you can try disabling it.

**Comment by jlarcombe** [comment] 2016-02-11 14:56
Ah, I don't have that one installed. Yes, when I ran "atom --safe" none of my add-ons appeared and I see the green square on the left of the status bar. The packages that come with Atom still run, though, so perhaps one of them is the culprit.

**Comment by Ben3eeE** [comment] 2016-04-08 08:06
@jlarcombe I think you are describing a different intended behavior that was implemented in 1.4.0, see https://github.com/atom/atom/issues/942. This feature has an open issue over here https://github.com/atom/atom/issues/10474.

**Comment by jlarcombe** [comment] 2016-04-11 13:55
Really? It seems pretty unambiguous to me and I can't see why it would be intended behaviour: open a new window, type into the tab, close the window (not the tab) and you don't get prompted to save. Doing the same thing but closing the tab instead correctly prompts you to save.

**Comment by 50Wliu** [comment] 2016-04-11 19:28
@jlarcombe There's an important distinction between closing the _window_ and closing an individual _tab_.

When you close a window, the window's state is serialized, which includes open folders, tabs open, their contents, etc.  That is restored when you start Atom again, and so Atom doesn't need to prompt about unsaved files, as that same unsaved content is still there when you next start Atom.

When you close a tab, it's assumed that you're done with the tab, so Atom needs to know whether you want to save your changes or not.

This behavior is consistent with other major text editors such as Notepad++ and Sublime Text.

**Comment by jlarcombe** [comment] 2016-04-11 20:07
Eh? That's completely different. I'm not talking about quitting Atom, I'm talking about closing a window. Closing the last window doesn't quit Atom on the Mac, and besides, this happens if you close any window, not just the last one. You can't get those unsaved tabs back whatever you do.

I'm surprised this seems to be controversial. I'm beginning to wish I had the time to dig in to it and patch it myself.

**Comment by 50Wliu** [comment] 2016-04-11 20:54
Sorry, I'm unfamiliar with Mac.  Should have remembered it handles window-closing differently.

**Comment by iolsen** [comment] 2016-10-10 16:52
I believe this is the same issue as https://github.com/atom/atom/issues/10474, which we do plan to address. Feel free to subscribe there for updates.

**Closed by iolsen** 2016-10-10 16:52 UTC
Labels: more-information-needed, needs-reproduction
