### ISSUE TITLE
Search in project hangs and memory consumption increases infinitely

### ISSUE THREAD

**Issue by rpbaltazar** [atom/atom#16692] opened 2018-02-07 03:56 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is a particular weird issue in the sense that I can't reproduce it across machines. I'm inclined to say that it has to do with machine hardware as it is the main difference between the two testing machines. 

As you can see on the attached gif, whenever I search within a project, the process of searching simply hangs and increases the memory consumption up to the roof.
I've tried everything I can remember of:
  - Starting in Safe Mode
  - Removing my atom configuration and use the defaults
  - Completely uninstalling the application and start from fresh

This seems to be project dependent, thus my idea that it might be due to poor performance being beaten by a better machine specs. Are there any issues when the number of files in a project is large?

### Steps to Reproduce

![atom-memory-bug](https://user-images.githubusercontent.com/5548466/35897792-e849b462-0bfd-11e8-88fa-d1d146d737cd.gif)

1. Open Atom with a project
2. Search in project

**Expected behavior:** Results to start appearing on the output window

**Actual behavior:** The process hangs and the memory bloats

**Reproduces how often:** Every time in this machine

### Versions

```
$ atom --version
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.14.3
```
macOS High Sierra - v. 10.13.3
iMac Late 2013
3.5GHz Intel Core i7
16 GB 1600 MHz DD3

### Additional Information

-

**Comment by rsese** [comment] 2018-02-07 19:26
Do you happen to have a third machine you can test with?  I wonder if there's also maybe an issue with the one machine?

> Are there any issues when the number of files in a project is large?

There's one that i know of:

https://github.com/atom/find-and-replace/issues/653

Are you able to share the project you're working on by any chance so we can give it a try?

In any case, if you don't think this is basically a duplicate of https://github.com/atom/find-and-replace/issues/653 (at a high level seems similar at least?), the issue should go in https://github.com/atom/find-and-replace.

**Closed by rsese** 2018-02-07 19:26 UTC

**Comment by rpbaltazar** [comment] 2018-02-09 02:38
I'll test in some other machines here in office, but I'm unaware of why would this particular machine would have such behaviour.
It might have something to do with the https://github.com/atom/find-and-replace/issues/653.
Thanks for pointing out to it.

I'll move my comment there and see if anyone has any more hints.

**Comment by rsese** [comment] 2018-02-09 06:01
> I'll test in some other machines here in office, but I'm unaware of why would this particular machine would have such behaviour.

Yeah it does seem odd that one machine would show this behavior and another not (unless there was a huge difference between the machines?).

Also I re-read your issue and I think I mis-read it, sorry about that - the issue I pointed you to is specifically about searching in large files whereas yours seems to be about a large project with lots of files. How large is the project?  I do remember this other issue searching in a large project, though people were hitting a specific error in that case (https://github.com/atom/find-and-replace/issues/869).

**Comment by rpbaltazar** [comment] 2018-02-20 13:33
It is definitely something to do with the size of the repo.
I've tried the same thing in a smaller project, same machine, and it works perfectly fine.
