### ISSUE TITLE
Linux, Atom >0.188.0, Chrome 21, wrongly detected touchscreen interface

### ISSUE THREAD

**Issue by gas333** [atom/atom#6725] opened 2015-05-10 22:06 UTC
Chrome wrongly detects input devices, so it enables touchscreen interface. This means that:

- menu is harder to use, as it doesn't detect mousemove
- mouse input is broken, it detects all mouse buttons as button 1
- selection is broken, a touchscreen selection tool appears
- the same problems happen when I use Chrome internal controls, like dev tools

Bug still happens when I:

- rm -rf ~/.atom ~/.config/Atom ~/.cache/Atom
- run atom under a new user account
- replace virtual machine graphic cards, change input devices
- rebuild from scratch (scripts/clean)
- try various chrome flags (--touch-events=disabled, --disable-touch-input, ...)

Bug doesn't happen when I:

- run atom under a Xephyr X server.

Bug happens on:

- master
- v0.193.0
- v0.194.0
- v0.195.0
- v0.196.0
- v0.197.0
- v0.198.0

Bug doesn't happen on:

- v0.188.0
- previous versions

I assume that the problem is due to upgrading to Chrome 21.

**Comment by 50Wliu** [comment] 2015-05-11 01:12
Do you mean Chrome 41?
Also, can this be considered a duplicate of #6306?

**Comment by paulcbetts** [comment] 2015-05-11 01:33
Is this on a Virtualbox VM?

**Comment by 50Wliu** [comment] 2015-07-10 19:23
I'm going to mark this as a duplicate of #6306.

**Closed by 50Wliu** 2015-07-10 19:23 UTC
Labels: more-information-needed
