### ISSUE TITLE
Uncaught Error: spawn /Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOt...

### ISSUE THREAD

**Issue by gregmacfarlane** [atom/atom#10760] opened 2016-02-10 18:45 UTC
1. In GitHub desktop, select repository
2. Right click, "open in Atom"

**Atom Version**: 1.5.0
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Users/Greg/Library/Application Support/com.github.atom.ShipIt/update.FzyOtqY/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-lintr",
      "linter-chktex",
      "markdown-preview",
      "vim-mode",
      "Hydrogen"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ]
  },
  "editor": {
    "fontFamily": "inconsolata",
    "fontSize": 13,
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "softWrap": true,
    "useShadowDOM": false
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joshaber** [comment] 2016-02-10 19:31
When this happened, did Atom seem to behave normally otherwise? Did you have to restart Atom?

**Comment by gregmacfarlane** [comment] 2016-02-10 20:40
Atom seemed to behave normally, but I only used it for a couple of minutes before shutting down.

**Comment by 50Wliu** [comment] 2016-02-10 20:47
Going to mark this as a duplicate of #9559 and close this, but feel free to continue the conversation here!

**Closed by 50Wliu** 2016-02-10 20:47 UTC
