### ISSUE TITLE
Keyboard layout: open bracket is not displayed

### ISSUE THREAD

**Issue by kowdermeister** [atom/atom#7618] opened 2015-07-01 09:02 UTC
I'm using Win 7, 64bit.
Atom version: 1.0.0

I'm using a Hungarian keyboard layout and I have trouble entering the open bracket [ symbol.

Pressing AltGr F produces this:
![image](https://cloud.githubusercontent.com/assets/342688/8451032/3e1608f8-1fe0-11e5-82e0-ba3b639c066f.png)

This is how special characters are laid out for us:
![image](https://cloud.githubusercontent.com/assets/342688/8451064/76d7ff5c-1fe0-11e5-94ba-99ff95cebf06.png)

I'd expect this to be handled by default, without any extra configuration.

**Comment by thomasjo** [comment] 2015-07-01 09:25
This is a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37. Please subscribe to those issues for updates.

**Closed by thomasjo** 2015-07-01 09:25 UTC
