### ISSUE TITLE
Uncaught Error: Can't undo with an open transaction

### ISSUE THREAD

**Issue by mMerlin** [atom/atom#5723] opened 2015-02-25 00:01 UTC
Looks like https://github.com/atom/atom/issues/4817 has resurfaced.

Additional environment details: This is a guest VM running in VirtualBox for host OS Windows 7 64-bit.  At the time the error occurred, I had a momentary slow down, where atom / the VM was not responding quickly.  I **think** what happened, is I did &lt;ctrl>x a second time on a highlighted word before the first had been processed, and my finger slipped over and also did a &lt;ctrl>z.  Don't really know which got there first.  I saw the same thing with an older version of atom (about 0.173), but ignored it when I saw the 'already reported' message.  This time I had a look at the report, and saw that it had been closed.

Just incase it overlaps.  I saw some reports about problems using split tabs.  When the error occurred, there were no splits, but earlier in the session I had 3 splits open (Split Down) for a single file, editing in all 3.

As you can see from the config report, this is a pretty bare environment.  Quite new to using atom, and have not done any real customizing, other than tabs-to-spaces.

After collecting the details for reporting, the session continued.  A couple of undo operations got things back where the should be.  Save, Exit, restarted, just to be safe :)

**Atom Version**: 0.182.0-d1e6dba
**System**: linux 3.18.7-200.fc21.i686
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Can't undo with an open transaction

```
At /opt/atom/share/atom/resources/app/node_modules/text-buffer/lib/history.js:76

Error: Can't undo with an open transaction
    at History.module.exports.History.undo (/opt/atom/share/atom/resources/app/node_modules/text-buffer/lib/history.js:76:15)
    at TextBuffer.module.exports.TextBuffer.undo (/opt/atom/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:679:27)
    at TextEditor.module.exports.TextEditor.undo (/opt/atom/share/atom/resources/app/src/text-editor.js:1186:26)
    at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/opt/atom/share/atom/resources/app/src/text-editor-element.js:318:19)
    at atom-text-editor.newCommandListeners.(anonymous function) (/opt/atom/share/atom/resources/app/src/text-editor-element.js:286:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/share/atom/resources/app/src/command-registry.js:243:29)
    at /opt/atom/share/atom/resources/app/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/share/atom/resources/app/src/window-event-handler.js:176:20)
```

### Commands

```
     -0:22.6 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:21.9 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:20.6 core:move-left (atom-text-editor.editor.is-focused)
     -0:20.4 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:19.7 core:cut (atom-text-editor.editor.is-focused)
  2x -0:19.4 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:17.9 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:17.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:16.4 core:paste (atom-text-editor.editor.is-focused)
     -0:11.1 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:10.4 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:09.8 core:select-left (atom-text-editor.editor.is-focused)
     -0:09.1 core:cut (atom-text-editor.editor.is-focused)
     -0:09.1 core:undo (atom-text-editor.editor.is-focused)
     -0:02.6 core:cut (atom-text-editor.editor.is-focused)
     -0:02.4 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "autoIndentOnPaste": false,
    "showInvisibles": true,
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-02-25 17:21
Thanks for the report, @mMerlin. 

I tried really hard, but couldn't reproduce this. @maxbrunsfeld @nathansobo I'm guessing you might have :thought_balloon:/:bulb: about this since you've been working on [this part of text-buffer](https://github.com/atom/text-buffer/blob/72bd8f55a708c76d02c149445614b0e90ce42430/src/history.coffee#L43). 

What would need to happen for this to be triggered during normal Atom operation? Does the description above explain how this might happen:

> I had a momentary slow down, where atom / the VM was not responding quickly. I think what happened, is I did <ctrl>x a second time on a highlighted word before the first had been processed, and my finger slipped over and also did a <ctrl>z. 

If this _does_ happen, could we instead drop the undo/redo operation (and return `false` or something) instead of throwing an exception?

**Comment by bojidar-bg** [comment] 2015-03-10 20:23
Just happened to me... I pressed ctrl-x and slipped to ctrl-z. No damaged ocurred, though. (e.g. I was able to make undo/redo after that).

**Comment by yoavst** [comment] 2015-04-15 16:50
I've just did ctrl x and it happens. sorry that I cannot give more details (Ubuntu 14.04)

**Comment by izuzak** [comment] 2015-06-10 12:13
This was closed in https://github.com/atom/text-buffer/pull/58, I believe. /cc @maxbrunsfeld

**Closed by izuzak** 2015-06-10 12:13 UTC
Labels: more-information-needed
