### ISSUE TITLE
'find work not: in folder, in project or file /multifiles on macOS

### ISSUE THREAD

**Issue by abonino** [atom/atom#21321] opened 2020-09-16 06:40 UTC
'find work not: in folder, in project or in file /multifiles on macOS
– macOS 10.15.4
– atom 1.51 (latest & stable)
;-(

– activate folder or file or multifiles
– activate find (cmd-f or cmd-shift-f)
– search-text (existing .... )
=> 'noting found'

**Comment by sadick254** [comment] 2020-09-16 08:01
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see in Atom. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see the [How Can I Contribute? section of the Atom CONTRTIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by sadick254** [comment] 2020-10-05 08:49
Closing this issue for now since there has not been any activity in the past 19 days. Am happy to reopen when we have reproduction steps.

**Closed by sadick254** 2020-10-05 08:49 UTC
Labels: needs-reproduction

**Comment by abonino** [comment] 2020-10-07 06:17
Hääääääää!
step-by-step you have the instuction !!!!!!!!!!!!!!!!!!!
;(
