### ISSUE TITLE
Add native feature to Sign-in and Sync Settings to GitHub account

### ISSUE THREAD

**Issue by mrmckeb** [atom/atom#8149] opened 2015-07-30 01:31 UTC
I've tried a few plugins, like the sync-settings one - and they're good. But native support would be ideal. Atom is a great GitHub product, and I'd like to see more GitHub integration.

**Comment by mnquintana** [comment] 2015-07-30 01:32
Thanks for the suggestion! This is a duplicate of https://github.com/atom/atom/issues/3572 though – let's keep the discussion there.

**Closed by mnquintana** 2015-07-30 01:32 UTC

**Comment by mrmckeb** [comment] 2015-07-30 06:26
Thanks, sorry I must have missed that when I searched...
