### ISSUE TITLE
Disabled package updates enable package

### ISSUE THREAD

**Issue by polarathene** [atom/atom#8988] opened 2015-09-29 10:58 UTC
If I have disabled packages installed, and an update is available, triggering the update manually/individually or via update all packages enables any updated disabled package afterwards. I do not believe this is an intended behaviour? I cannot use Update All button unless I take note of my disabled packages to disable again after updating or uninstall them prior.

Win 8.1x64

**Comment by izuzak** [comment] 2015-09-29 10:59
Thanks for the report -- I think this is a duplicate of https://github.com/atom/settings-view/issues/603.

**Closed by izuzak** 2015-09-29 10:59 UTC
