### ISSUE TITLE
Unexpected/wrong indentation when not using brackets

### ISSUE THREAD

**Issue by patrickjane** [atom/atom#15987] opened 2017-10-25 08:57 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom seems not to be capable of indenting lines after `if` statements and the like *without using brackets* in java script code (have not tried other languages).
For our style of code this is extremely annoying, since it has to be manually fixed in every line, and the auto-indentation will unfix it everytime as well, so it needs manual adjustment again.

### Steps to Reproduce

1. type `if (xxx)`
2. press [Enter]
3. type 'something'

**Expected behavior:** 
You should see

    if (xxx)
       something

**Actual behavior:**
You actually see

    if (xxx)
    something

**Reproduces how often:** 
100%

### Versions

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5

### Additional Information

I know not every style of indentation can be supported, and not every editor covers every style of indentation. However I would argue that this example is really one of the most basic situations, which *should* be supported somehow.

I don't mind installing a package for this, or hacking the config to make it work. I just haven't found a way yet to have atom indent in the way I need it.

**Comment by rsese** [comment] 2017-10-25 18:35
Thanks for taking the time to contribute!

I thought this sounded familiar - looks like a duplicate of https://github.com/atom/language-javascript/issues/476 so you can subscribe there for updates if you'd like.

---

We noticed that this is a duplicate of https://github.com/atom/language-javascript/issues/476. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-25 18:35 UTC

**Comment by patrickjane** [comment] 2017-10-26 05:59
Okay sorry for the duplicate. I was searching issues before opening a new one, but didn't find the one you linked. Seeing its from dec. 2016, it seems like we wont get a fix for this.
