### ISSUE TITLE
Atom no longer remembers previous session

### ISSUE THREAD

**Issue by wrummler** [atom/atom#7255] opened 2015-06-12 20:46 UTC
Using 0.209.0 on Windows 7 Pro 64-bit, Atom (even in safe mode) will no longer open a new first-and-only window with the session state (open folder and open files) from the previous last-to-be-closed Atom window.

#6917 seems similar, but that was fixed. I guess this might be a regression, unless it was a deliberate choice. I found no issue or changelog or release notes that mentioned it.

I believe 0.208.0 restored the previous session, and the last version in which the previous session wasn't restored was some time ago, maybe around 0.197.0 or so but not sure. Even then, File / Exit seemed to allow session restoring, while the window's close button did not. Now, neither seem to allow the previous session to be restored. (File / Close Window doesn't currently work either, but I hadn't checked it closely in previous versions.)

**Comment by mnquintana** [comment] 2015-06-12 20:47
Duplicate of https://github.com/atom/atom/issues/7231 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-12 20:47 UTC

**Comment by wrummler** [comment] 2015-06-12 22:56
Thanks @mnquintana --- sorry for missing the ref.
