### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getEntries' of undefined

### ISSUE THREAD

**Issue by dressedfez** [atom/atom#5907] opened 2015-03-09 10:25 UTC
[Enter steps to reproduce below:]

1. Install on windows 7 box
2. start the editor

**Atom Version**: 0.186.0
**System**: NTPC66
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getEntries' of undefined

```
At /c:/Users/zimmer/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:236

TypeError: Cannot read property 'getEntries' of undefined
    at module.exports.TualoGitContextView.refreshTree (/c:/Users/zimmer/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:236:18)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
git-merge-conflicts, v0.0.2
git-tab-status, v1.3.0
tualo-git-context, v0.3.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-09 13:06
Looks like a duplicate of both tualo/tualo-git-context#7 and tualo/tualo-git-context#8, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-09 13:06 UTC
