### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('a...

### ISSUE THREAD

**Issue by eltoncyc** [atom/atom#16899] opened 2018-03-07 20:26 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('as
(
select') contains HTML space characters, which are not valid in tokens.

```
At C:\Users\eltonc\AppData\Local\atom\app-1.24.0\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:419

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('as
(
select') contains HTML space characters, which are not valid in tokens.
    at SuggestionListElement.addClassToElement (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:419:50)
    at SuggestionListElement.renderItem (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:471:30)
    at SuggestionListElement.renderItems (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:293:18)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.24.0/resources/app/src/view-registry.js:238:13)
```

### Commands

```
  2x -0:58.9.0 editor:newline (input.hidden-input)
     -0:58.5.0 core:move-up (input.hidden-input)
  5x -0:53.4.0 core:backspace (input.hidden-input)
     -0:52 autocomplete-plus:cancel (input.hidden-input)
  2x -0:47.5.0 hydrogen:run (input.hidden-input)
     -0:43.5.0 core:move-down (input.hidden-input)
     -0:43.1.0 hydrogen:run (input.hidden-input)
     -0:38 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.10.5 
git-plus 7.10.0 
Hydrogen 2.2.2 
kite 0.71.0 
```

**Comment by rsese** [comment] 2018-03-07 21:17
Thanks for the report!  I'm guessing this isn't reproducible in safe mode (`atom --safe`)?

I think this is likely a duplicate of https://github.com/atom/atom/issues/16164 -  based on that issue and https://github.com/atom/atom/issues/16305, my guess would be that autocomplete-python might be causing the error?  

If you can reproduce in safe mode however, please let us know.

**Closed by rsese** 2018-03-07 21:17 UTC
