### ISSUE TITLE
Atom crashes on startup

### ISSUE THREAD

**Issue by bjornwsv** [atom/atom#11559] opened 2016-04-21 12:17 UTC
### Description
Atom crashes on startup. 

### Steps to Reproduce

1. Open Atom
2. Wait a few seconds

**Expected behavior:** 
Atom opens without error

**Actual behavior:**
Atom crashes and tels me so:

![screenshot from 2016-04-21 13-30-41](https://cloud.githubusercontent.com/assets/3709210/14708025/559c1f00-07c8-11e6-968d-ef80fa213189.png)

### Versions

apm:                1.9.2
npm:                2.13.3
node:               0.10.40
python:            3.5.1
git:                  2.8.0

Atom    : 1.9.0-dev-f00ac5c
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

OS: Arch Linux
DE: Gnome 3.20
Kernel: 4.5.1-1-ARCH

I first noticed this running Atom 1.6.2-1. I upgraded to see if that worked, it didn't.

### What I have tried
* Running Atom in safe mode
* Disabling all community extensions
* Removing all community extensions 
* Disabling all extensions
* Removing atom and its configuration files and building atom from git.

### Crashlog

App load time: 602ms
Failed to get crash dump id.
Report Id:

**Comment by beliarsclaw** [comment] 2016-04-21 14:52
Getting the same error. 

Running on Manjaro (Arch Linux - Kernel 4.4.6)

**Comment by CraZySacX** [comment] 2016-04-21 14:58
This is caused by the latest freetype2 release on Arch (2.6.3).   One option is to downgrade the freetype2 package back to 2.6.2.   Look at https://aur.archlinux.org/packages/downgrader/.

If you downgrade, and use atom heavily, you'll also want to add freetype2 to your ignore list in pacman.conf.

**Comment by beliarsclaw** [comment] 2016-04-21 21:27
@CraZySacX  - Atom is working fine (no more crash @ start) after downgrading freetype package from 2.6.3 to 2.6.2 using  downgrade  (https://aur.archlinux.org/packages/downgrade/). Many thanks for the tip. :+1:

**Comment by 50Wliu** [comment] 2016-04-21 22:59
Closing in favor of #11198 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-21 22:59 UTC
Labels: blocked, bug, linux
