### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/pinky/Library/Application Suppor...

### ISSUE THREAD

**Issue by p1nx** [atom/atom#9764] opened 2015-11-23 16:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/pinky/Library/Application Support/com.github.atom.ShipIt/update.YlYDLmU'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/pinky/Library/Application Support/com.github.atom.ShipIt/update.YlYDLmU'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/pinky/Library/Application Support/com.github.atom.ShipIt/update.YlYDLmU/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (module.js:388:19)
```

### Commands

```
     -0:00.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-23 20:42
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-23 20:42 UTC
