### ISSUE TITLE
HTML syntax highlighting breaks with <script> tags in new html files

### ISSUE THREAD

**Issue by ggstuart** [atom/atom#21959] opened 2021-02-13 09:53 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When I insert a `<script>` tag into an HTML page, it consistently messes up the syntax highlighting.

### Steps to Reproduce

1. Create new file - index.html
2. Use built-in HTML template (type html and press enter)
3. Insert a `script` or `scriptsrc` from  template (type script or scriptsrc and press enter) 

**Expected behavior:**

The script tag should be highlighted as valid HTML.

**Actual behavior:**

The script tag appears grey and any further editing of the HTML produces highlighting that indicates an error in the syntax.

**Reproduces how often:**

It seems to only happen with newly created files.

### Versions

Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 2.7.17
git 2.17.1

Ubuntu 18.0.4

### Additional Information

Closing the file tab and opening the file again will solve the issue.

**Comment by ThatXliner** [comment] 2021-02-15 00:26
Possible duplicate of #21804

**Comment by darangi** [comment] 2021-02-17 15:30
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21959 You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2021-02-17 15:30 UTC
