### ISSUE TITLE
Uncaught Invariant Violation: RelayModernGraphQLTag: 

### ISSUE THREAD

**Issue by NeelPi** [atom/atom#16920] opened 2018-03-09 17:10 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Invariant Violation: RelayModernGraphQLTag: Expected an request, got `{"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByBranchQuery","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"FragmentSpread","name":"PrSelectionByBranchContainer_repository","args":null}],"storageKey":null}],"type":"Query"},"id":null,"kind":"Batch","metadata":{},"name":"PrInfoControllerByBranchQuery","query":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Root","name":"PrInfoControllerByBranchQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":30,"type":"Int"},{"kind":"Variable","name":"headRefName","variableName":"branchName","type":"String"}],"concreteType":"PullRequestConnection","name":"pullRequests","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequest","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"createdAt","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"title","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"last","value":1,"type":"Int"}],"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommitEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommit","name":"node","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Commit","name":"commit","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Status","name":"status","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"StatusContext","name":"contexts","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"InlineFragment","type":"StatusContext","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"context","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"description","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"targetUrl","storageKey":null}]}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"commits{\"last\":1}"},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"number","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"author","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"avatarUrl","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"InlineFragment","type":"Bot","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]},{"kind":"InlineFragment","type":"User","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"owner","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactionGroup","name":"reactionGroups","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"content","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactingUserConnection","name":"users","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":"commitsCount","args":null,"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":100,"type":"Int"}],"concreteType":"LabelConnection","name":"labels","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"LabelEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Label","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"color","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"labels{\"first\":100}"}],"storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}]},"text":"query PrInfoControllerByBranchQuery(\n  $repoOwner: String!\n  $repoName: String!\n  $branchName: String!\n) {\n  repository(owner: $repoOwner, name: $repoName) {\n    ...PrSelectionByBranchContainer_repository\n    id\n  }\n}\n\nfragment PrSelectionByBranchContainer_repository on Repository {\n  pullRequests(first: 30, headRefName: $branchName) {\n    totalCount\n    edges {\n      node {\n        id\n        number\n        title\n        url\n        ...PrInfoContainer_pullRequest\n      }\n    }\n  }\n}\n\nfragment PrInfoContainer_pullRequest on PullRequest {\n  ...PrStatusesContainer_pullRequest\n  id\n  url\n  number\n  title\n  state\n  createdAt\n  author {\n    __typename\n    login\n    avatarUrl\n    ... on User {\n      url\n    }\n    ... on Bot {\n      url\n    }\n    ... on Node {\n      id\n    }\n  }\n  repository {\n    name\n    owner {\n      __typename\n      login\n      id\n    }\n    id\n  }\n  reactionGroups {\n    content\n    users {\n      totalCount\n    }\n  }\n  commitsCount: commits {\n    totalCount\n  }\n  labels(first: 100) {\n    edges {\n      node {\n        name\n        color\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusesContainer_pullRequest on PullRequest {\n  id\n  commits(last: 1) {\n    edges {\n      node {\n        commit {\n          status {\n            state\n            contexts {\n              id\n              state\n              ...PrStatusContextContainer_context\n            }\n            id\n          }\n          id\n        }\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusContextContainer_context on StatusContext {\n  context\n  description\n  state\n  targetUrl\n}\n"}`.

```
At C:\Users\neelp\AppData\Local\atom\app-1.24.1\resources\app\node_modules\fbjs\lib\invariant.js:49

Invariant Violation: RelayModernGraphQLTag: Expected an request, got `{"fragment":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"PrInfoControllerByBranchQuery","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"FragmentSpread","name":"PrSelectionByBranchContainer_repository","args":null}],"storageKey":null}],"type":"Query"},"id":null,"kind":"Batch","metadata":{},"name":"PrInfoControllerByBranchQuery","query":{"argumentDefinitions":[{"kind":"LocalArgument","name":"repoOwner","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"repoName","type":"String!","defaultValue":null},{"kind":"LocalArgument","name":"branchName","type":"String!","defaultValue":null}],"kind":"Root","name":"PrInfoControllerByBranchQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Variable","name":"name","variableName":"repoName","type":"String!"},{"kind":"Variable","name":"owner","variableName":"repoOwner","type":"String!"}],"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":30,"type":"Int"},{"kind":"Variable","name":"headRefName","variableName":"branchName","type":"String"}],"concreteType":"PullRequestConnection","name":"pullRequests","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequest","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"createdAt","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"title","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"last","value":1,"type":"Int"}],"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommitEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"PullRequestCommit","name":"node","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Commit","name":"commit","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Status","name":"status","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"StatusContext","name":"contexts","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"InlineFragment","type":"StatusContext","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"context","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"description","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"targetUrl","storageKey":null}]}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"commits{\"last\":1}"},{"kind":"ScalarField","alias":null,"args":null,"name":"state","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"number","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"author","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"avatarUrl","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null},{"kind":"InlineFragment","type":"Bot","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]},{"kind":"InlineFragment","type":"User","selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"url","storageKey":null}]}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Repository","name":"repository","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":null,"name":"owner","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"__typename","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"login","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactionGroup","name":"reactionGroups","plural":true,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"content","storageKey":null},{"kind":"LinkedField","alias":null,"args":null,"concreteType":"ReactingUserConnection","name":"users","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":"commitsCount","args":null,"concreteType":"PullRequestCommitConnection","name":"commits","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"totalCount","storageKey":null}],"storageKey":null},{"kind":"LinkedField","alias":null,"args":[{"kind":"Literal","name":"first","value":100,"type":"Int"}],"concreteType":"LabelConnection","name":"labels","plural":false,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"LabelEdge","name":"edges","plural":true,"selections":[{"kind":"LinkedField","alias":null,"args":null,"concreteType":"Label","name":"node","plural":false,"selections":[{"kind":"ScalarField","alias":null,"args":null,"name":"name","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"color","storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}],"storageKey":null}],"storageKey":"labels{\"first\":100}"}],"storageKey":null}],"storageKey":null}],"storageKey":null},{"kind":"ScalarField","alias":null,"args":null,"name":"id","storageKey":null}],"storageKey":null}]},"text":"query PrInfoControllerByBranchQuery(\n  $repoOwner: String!\n  $repoName: String!\n  $branchName: String!\n) {\n  repository(owner: $repoOwner, name: $repoName) {\n    ...PrSelectionByBranchContainer_repository\n    id\n  }\n}\n\nfragment PrSelectionByBranchContainer_repository on Repository {\n  pullRequests(first: 30, headRefName: $branchName) {\n    totalCount\n    edges {\n      node {\n        id\n        number\n        title\n        url\n        ...PrInfoContainer_pullRequest\n      }\n    }\n  }\n}\n\nfragment PrInfoContainer_pullRequest on PullRequest {\n  ...PrStatusesContainer_pullRequest\n  id\n  url\n  number\n  title\n  state\n  createdAt\n  author {\n    __typename\n    login\n    avatarUrl\n    ... on User {\n      url\n    }\n    ... on Bot {\n      url\n    }\n    ... on Node {\n      id\n    }\n  }\n  repository {\n    name\n    owner {\n      __typename\n      login\n      id\n    }\n    id\n  }\n  reactionGroups {\n    content\n    users {\n      totalCount\n    }\n  }\n  commitsCount: commits {\n    totalCount\n  }\n  labels(first: 100) {\n    edges {\n      node {\n        name\n        color\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusesContainer_pullRequest on PullRequest {\n  id\n  commits(last: 1) {\n    edges {\n      node {\n        commit {\n          status {\n            state\n            contexts {\n              id\n              state\n              ...PrStatusContextContainer_context\n            }\n            id\n          }\n          id\n        }\n        id\n      }\n    }\n  }\n}\n\nfragment PrStatusContextContainer_context on StatusContext {\n  context\n  description\n  state\n  targetUrl\n}\n"}`.
    at invariant (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/fbjs/lib/invariant.js:42:21)
    at getRequest (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/relay-runtime/lib/RelayModernGraphQLTag.js:42:57)
    at ReactRelayQueryRenderer._fetchForProps (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:119:27)
    at new ReactRelayQueryRenderer (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:64:46)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:295:22)
    at ReactCompositeComponentWrapper._constructComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:282:25)
    at ReactCompositeComponentWrapper.mountComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:185:27)
    at Object.mountComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at ReactCompositeComponentWrapper.performInitialMount (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:368:40)
    at ReactCompositeComponentWrapper.mountComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:255:27)
    at Object.mountComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:43:41)
    at Object.updateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:119:57)
    at ReactDOMComponent._reconcilerUpdateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:209:34)
    at ReactDOMComponent._updateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:308:37)
    at ReactDOMComponent.updateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactMultiChild.js:295:18)
    at ReactDOMComponent._updateDOMChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:944:18)
    at ReactDOMComponent.updateComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:758:16)
    at ReactDOMComponent.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactDOMComponent.js:720:16)
    at Object.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:544:16)
    at Object.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at ReactCompositeComponentWrapper._updateRenderedComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:751:29)
    at ReactCompositeComponentWrapper._performComponentUpdate (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:721:16)
    at ReactCompositeComponentWrapper.updateComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:642:18)
    at ReactCompositeComponentWrapper.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactCompositeComponent.js:544:16)
    at Object.receiveComponent (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactReconciler.js:122:28)
    at Object.updateChildren (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/react-dom/lib/ReactChildReconciler.js:107:31)
```

### Commands

```
     -5:40.1.0 core:paste (input.btn.btn-primary.icon.icon-check.inline-block-tight)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-03-09 21:38
Thanks for contributing!

Based on the error I think this is a duplicate of https://github.com/atom/github/issues/1340 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-09 21:38 UTC
