### ISSUE TITLE
Setting associations with arbitrary files on Windows is problematic due to Squirrel

### ISSUE THREAD

**Issue by Splike** [atom/atom#8490] opened 2015-08-23 18:03 UTC
Currently it installs in the "user\appdata\Local\" folder. Atom needs to change its installation directory to either "C:\program files" or "C:\program files (x86)".

Whenever I encounter a text file with a new extension, I (of course) want to make it open by default with Atom. To chose Atom as a default program, I manually have to dig down to the .exe file, which is located here:  "user\AppData\Local\atom\app-1.0.7\atom.exe" The problem here lies with the .exe file sitting inside a folder with a version number. Whenever Atom updates, the whole default program shortcut breaks.

Solution:
1) Make Atom install into Program Files
2) Delete old versions when updating Atom
3) Don't place the version number in the folder name
4) If people want to roll back, they can download previous versions from github.

**Comment by paulcbetts** [comment] 2015-08-23 18:29
The reason that we do these things is in order to do transparent background updates. This has the unfortunate side-effect of making it annoying to associate files with extensions. While we're not going to ever install to Program Files, it would be awesome if Atom made this easier, perhaps via a new settings page.

**Comment by mnquintana** [comment] 2015-08-23 18:32
This looks like a duplicate of https://github.com/atom/atom/issues/4893 – let's continue the discussion there.

**Closed by mnquintana** 2015-08-23 18:32 UTC
