### ISSUE TITLE
Multiple Crashes / Freezes on Mac After 1.1 update 

### ISSUE THREAD

**Issue by jaysig** [atom/atom#9536] opened 2015-11-12 02:58 UTC
Since upgrading last week, my Atom has become increasingly unstable. I have tried to disable most of my packages, but the problems are continuing. The most common issue is it says the Editor has stopped responding, would you like to close. It also seems to use a lot of Memory.

<img width="735" alt="screenshot 2015-11-11 21 39 20" src="https://cloud.githubusercontent.com/assets/4924440/11109500/1eeb7772-88bf-11e5-9779-9c9cca2d890b.png">

<img width="712" alt="screenshot 2015-11-11 21 39 06" src="https://cloud.githubusercontent.com/assets/4924440/11109501/1eec29ce-88bf-11e5-9311-ff4b81bd6bce.png">

Any suggestions for how to identify the problem would be appreciated.

**Comment by perpetualmultimedia** [comment] 2016-01-31 03:05
Same here. Did you ever figure this out?

**Comment by lee-dohm** [comment] 2016-02-01 23:31
Sorry I missed this in the past. Can either of you reproduce this on the latest stable version of Atom? Also, could you give the following information?

* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by jaysig** [comment] 2016-02-02 21:29
Mac 10.11.13
Atom --safe works for me, I think my issue is one of the packages which causes a huge memory leak.

**Comment by mnquintana** [comment] 2016-02-02 21:45
Thanks for the update @jaysig! Since this sounds like an issue with one of the packages you have installed, I'm going to close this out.

**Closed by mnquintana** 2016-02-02 21:45 UTC
Labels: more-information-needed
