### ISSUE TITLE
OS X - Open File dialog does not show after closing editor window.

### ISSUE THREAD

**Issue by alexmoore** [atom/atom#12721] opened 2016-09-19 13:54 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? 
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

The Open File dialog doesn't show if you close the editor window upon starting the application, and then try to open a file. 

![atom-no-openy-file](https://cloud.githubusercontent.com/assets/1438/18634500/160f02fa-7e4f-11e6-843e-6e32861d5786.gif)

### Steps to Reproduce

1. Open atom with no folder/file arguments.
2. Close the default window with it's blank editor tab ( or `Cmd+W`, `Cmd+W` to close the empty editor tab, and then the window)
3. Try to open a new file via the `File->Open...` menu, or `Cmd+O`

**Expected behavior:** An open file dialog to pop up.

**Actual behavior:** Nothing happens.

### Versions

OS X 10.11.6

```
 $ atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.8.3
```

**Comment by Ben3eeE** [comment] 2016-09-19 14:39
This sounds like a duplicate of https://github.com/atom/atom/issues/12508

**Comment by 50Wliu** [comment] 2016-09-19 18:03
Thanks @Ben3eeE.

**Closed by 50Wliu** 2016-09-19 18:03 UTC
