### ISSUE TITLE
Atom does not start. Ubuntu 14.04, Atom 0.166

### ISSUE THREAD

**Issue by fbrundu** [atom/atom#4871] opened 2015-01-06 16:09 UTC
I am unable to start Atom after update to release 0.166.
I receive this error:

    /opt/atom/atom: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

The library libgconf-2.so.4 is installed and it is under:

    /usr/lib/x86_64-linux-gnu/libgconf-2.so.4
    /usr/lib/x86_64-linux-gnu/libgconf-2.so.4.1.5

Thanks

**Comment by kedashoe** [comment] 2015-01-06 16:32
I am also unable to start atom on Ubuntu 14.04 after installing. I am getting

`nohup: failed to run command ‘/opt/atom/atom’: No such file or directory`

**Comment by cmillion** [comment] 2015-01-06 16:52
After most recent update on Ubuntu 14.04 via apt-get, cannot open atom with error `/opt/atom/atom: 1: /opt/atom/atom: Syntax error: "(" unexpected`. Tried remove and reinstall with apt-get; issue remains.

**Comment by ihashacks** [comment] 2015-01-06 16:58
I'm using the WebUpd8 packages from @hotice. I'm receiving a similar issue after going from 0.165 --> 0.166. Ubuntu 14.10 x86_64.

```
$ atom
/opt/atom/atom: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```

```
$ LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu atom
/opt/atom/atom: error while loading shared libraries: libX11.so.6: wrong ELF class: ELFCLASS64
```

```
apt-cache show atom | grep ^Architecture
Architecture: amd64
```

```
apt-cache policy atom
atom:
  Installed: 0.166.0-1~webupd8~0
  Candidate: 0.166.0-1~webupd8~0
  Version table:
 *** 0.166.0-1~webupd8~0 0
        500 http://ppa.launchpad.net/webupd8team/atom/ubuntu/ utopic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by opennomad** [comment] 2015-01-06 16:59
ditto. I noticed that the package claims to be for `amd64`, but ldd of /opt/atom/atom shows it as 32 bit:

    file  /opt/atom/atom 
/opt/atom/atom: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=d465e34b657858331450db73ea2ee3e848eca381, stripped

ldd also shows it referencing 32 bit libraries.

**Comment by hotice** [comment] 2015-01-06 17:25
Sorry about the issue guys, it's working fine in Ubuntu 14.10 and that's why I didn't notice it. I'm not sure what's going on and I'll upload Atom 0.165.0 in the PPA until I figure this out.

**Comment by ihashacks** [comment] 2015-01-06 17:49
@hotice I'm on Ubuntu 14.10 x86_64 if you need someone to test a possible fix you come up with. That way you'll have someone to test the fix who was previously affected by the issue.

**Comment by hotice** [comment] 2015-01-07 08:43
@ihashacks Thanks but there's no need. I can reproduce it in a fresh Ubuntu virtual machine. I haven't been able to figure out what's wrong yet though :/

**Comment by hotice** [comment] 2015-01-07 08:58
@ihashacks thanks but there's no need. I'll upload a fixed 0.166.0 build soon.

**Comment by kedashoe** [comment] 2015-01-07 16:18
Update installed and seems to be working, thank you @hotice for the ppa :fireworks:

**Comment by cmillion** [comment] 2015-01-07 16:24
Confirmed. This morning's update fixed the issue for me. Thank you.

**Comment by kevinsawicki** [comment] 2015-01-07 16:55
Closing this out.

**Closed by kevinsawicki** 2015-01-07 16:55 UTC
