### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by andreistroescu** [atom/atom#7632] opened 2015-07-01 17:41 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Radu\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -1:34.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:34.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:34.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:34.3.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:14.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:10.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:10.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:09.5.0 core:paste (atom-text-editor.editor.is-focused)
 11x -1:02.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:31.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:27.1.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:26.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:26 core:save (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:19 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "softWrap": true,
    "tabLength": 4,
    "showIndentGuide": true,
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.6
emmet, v2.3.10
minimap, v4.10.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-07-01 17:44
Duplicate of #6548 - this has been fixed for the next version of Atom.

**Closed by mnquintana** 2015-07-01 17:44 UTC
