### ISSUE TITLE
wrong behavior for .gitignore entry with trailing /

### ISSUE THREAD

**Issue by schmurfy** [atom/atom#8634] opened 2015-09-02 09:56 UTC
In my .gitignore I have something like this:

```
lib/something/*/
```

What this does is ignore all folders in lib/something but keep files, when I open this project in atom it gets confused: lib/something and everything below is ignored which is not the correct behavior applied by git.

**Comment by seamlik** [comment] 2015-11-27 06:29
I have this issue too. If in my .gitignore has:

```gitignore
android-*/
```

This is supposed to ignore some directories but not any files. But if the directory has a `android-liblog.install` file, Git doesn't ignore it but Atom does.

**Comment by schmurfy** [comment] 2017-03-29 15:43
@izuzak I never saw tat the need reproduction label, this is pretty easy to reproduce, just do this:

```bash
$ mkdir -p project/deps/one
$ mkdir -p project/deps/two
$ cd project
$ git init
$ echo "deps/*/" > .gitignore
```

The correct behavior when opening this in atom is that deps and any files in it should not be greyed out since they are NOT ignored by git, one and two will be ignored and these should appear greayed out.

This is the documented behavior in the git manpage and this is how it actually works.

**Comment by seamlik** [comment] 2018-03-30 04:31
I can confirm this issue is now fixed in at least 1.25.0.

**Comment by Arcanemagus** [comment] 2018-03-30 06:10
Since the original reproduction steps posted are incorrect (`git` _does_ correctly ignore any file under `deps`), and one of the users reporting this says that they no longer see this I am closing this.

Thanks for reaching out!

**Closed by Arcanemagus** 2018-03-30 06:10 UTC
Labels: git, needs-reproduction

**Comment by schmurfy** [comment] 2018-04-03 10:38
I am not sure what you meant by saying that the reproduction steps were incorrect, I did exactly what I wrote and the atom behavior was incorrect compared to the git commad line executable but if this is fixed it is good :)

**Comment by Arcanemagus** [comment] 2018-04-03 16:36
@schmurfy `git` doesn't work like your reproduction steps claim it does 😉

```
PS C:\temp\8634\project> git status --ignored
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitignore

Ignored files:
  (use "git add -f <file>..." to include in what will be committed)

        deps/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by Arcanemagus** [comment] 2018-04-04 16:09
Thanks for the updated reproduction steps, I can confirm that `git add .` _does_ add `deps/test.txt`, and actually this issue is **not** solved by the current version of Atom.

Although the `github` package's integration calls out to `git`, and thus handles it correctly (probably leading to the reports that it is working above), the `git` integration built into Atom itself that uses `libgit2` _doesn't_ handle it correctly, and still shows the file as ignored.

With `project` open in Atom, and `deps/test.txt` open as the active editor:
![image](https://user-images.githubusercontent.com/427137/38319833-b332990e-37e7-11e8-8504-fcddb9d15269.png)

All that being said, this issue should have been filed over on `atom/git-utils`, and there is actually a PR up that will likely solve this in https://github.com/atom/git-utils/pull/88. I'd recommend following that issue and checking again on a release of Atom that includes that change.

Thanks for taking the time to give more details!
