### ISSUE TITLE
Copypaste fail

### ISSUE THREAD

**Issue by SeibelStan** [atom/atom#6251] opened 2015-04-05 01:34 UTC
Copy and paste inside the Atom works. When you insert one Atom to another application it hangs up for a second and nothing sticks. Then, the clipboard is cleared. When you paste from another application in the Atom, the Atom sometimes falling, sometimes inserts. Change the frequency, once every hour or two, once every few inserts.

**Comment by m1ga** [comment] 2015-04-05 09:13
duplicate of https://github.com/atom/atom/issues/6221

**Comment by izuzak** [comment] 2015-04-05 10:36
Yeah, I'm guessing this is the same problem as in #6221. Closing this in favor of that issue, but let us know if you can reproduce this after that issue is fixed.

**Closed by izuzak** 2015-04-05 10:36 UTC
