### ISSUE TITLE
Regex replace, re-escaping the backslash multiple times in consecutive replacements

### ISSUE THREAD

**Issue by andresperezl** [atom/atom#10865] opened 2016-02-17 16:21 UTC
When escaping the backslash `\` to be inserted/replaced in a file, it will escape it multiple times until the the backslash is not shown anymore

For example when using the regex: `(\(\d\)(\s|\w)+)` and the replace text `\\textbf{$1}` on the text:

> (3) Normal—Is able to ambulate for 10 steps heel to toe with no
> staggering.
> (2) Mild impairment—Ambulates 7–9 steps.
> (1) Moderate impairment—Ambulates 4 –7 steps.
> (0) Severe impairment—Ambulates less than 4 steps heel to toe or
> cannot perform without assistance.

It will end up with:

> \\textbf{(3) Normal}—Is able to ambulate for 10 steps heel to toe with no
> staggering.
> `     `extbf{(2) Mild impairment}—Ambulates 7–9 steps.
> `	`extbf{(1) Moderate impairment}—Ambulates 4 –7 steps.
> `	`extbf{(0) Severe impairment}—Ambulates less than 4 steps heel to toe or
> cannot perform without assistance.

If we keep adding backslash, we can see that the error comes from reinterpreting the regex again and again, after it has been already interpreted. For example, if we change the replace text with `\\\\textbf{$1}`, then we end up with this:

> \\\textbf{(3) Normal}—Is able to ambulate for 10 steps heel to toe with no
> staggering.
> \textbf{(2) Mild impairment}—Ambulates 7–9 steps.
>` 	`extbf{(1) Moderate impairment}—Ambulates 4 –7 steps.
>` 	`extbf{(0) Severe impairment}—Ambulates less than 4 steps heel to toe or
> cannot perform without assistance.

**Comment by 50Wliu** [comment] 2016-02-17 20:37
This is a duplicate of atom/find-and-replace#615 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-17 20:37 UTC
