### ISSUE TITLE
Uncaught Error: Cannot find module '../node_modules/keyboard-layout/build/Release/keyboard-layout...

### ISSUE THREAD

**Issue by zloveldm** [atom/atom#15576] opened 2017-09-07 09:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.6 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module '../node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'

```
At module.js:472

Error: Cannot find module '../node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.6/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.6/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.6/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.19.6/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/atom-keymap/lib/helpers.js:244:117)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:456:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.6/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:336:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.6/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.6/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```
atom-terminal 0.8.0 
atom-ternjs 0.18.3 
autocomplete-html-entities 0.1.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.64 
color-picker 2.2.5 
emmet 2.4.3 
es6-javascript 1.0.0 
ex-mode 0.15.0 
file-icons 2.1.7 
git-plus 7.9.3 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
nodejs-snippets 2.0.2 
open-in-browsers 0.0.30 
pxtorem 0.1.3 
react 0.16.2 
```

**Comment by rsese** [comment] 2017-09-07 21:41
We've seen a handful of similar errors and I'll close as a duplicate of https://github.com/atom/atom/issues/14461.  Can you try reinstalling and let us know if you still get the error?

**Closed by rsese** 2017-09-07 21:41 UTC
Labels: duplicate
