### ISSUE TITLE
Color coding engine fails when using HTML inside Markdown document

### ISSUE THREAD

**Issue by toSvenson** [atom/atom#10214] opened 2015-12-29 11:55 UTC
When adding:
<a href="http://google.com" target="_blank">google.com</a>

the underscore is parsed as the start of italic text.
The rest of the document becomes italic and hard to read.

Since Markdown is allowed to have HTML included, the actual rendered MD is correctly visualized.

**Comment by mnquintana** [comment] 2015-12-29 15:37
Thanks for the report! This looks like a duplicate of https://github.com/atom/language-gfm/issues/44 – feel free to subscribe there for updates.

**Closed by mnquintana** 2015-12-29 15:37 UTC
