### ISSUE TITLE
Unresponsive editor after window reload

### ISSUE THREAD

**Issue by idleberg** [atom/atom#12345] opened 2016-08-06 11:40 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

After reloading the editor window (e.g. View > Developer > Reload Window) the editor is unresponsive and the following error shows up in the console:

```text
Uncaught (in promise) TypeError: Cannot read property 'bufferId' of null(…)
/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:51 
module.exports.TokenizedBuffer.deserialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:51
module.exports.TextEditor.deserialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:98
module.exports.DeserializerManager.deserialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/deserializer-manager.js:45(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:37
module.exports.Pane.deserialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:36
module.exports.DeserializerManager.deserialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/deserializer-manager.js:45
module.exports.PaneContainer.deserialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:64
module.exports.Workspace.deserialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:174
module.exports.AtomEnvironment.deserialize @ /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1031(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:752
```

This behaviour only started since my upgrade v1.9.2 to v1.9.5!

### Steps to Reproduce

1. Open editor
2. Reload window

**Expected behavior:** Responsive editor

**Actual behavior:** Editor window freezes, while the Atom menu still works. I can open a new editor window using the menu (not the shortcut) and the new editor works fine, while the old window remains unresponsive

### Versions

Mac OS X 10.11.6

Atom    : 1.9.5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4

**Comment by idleberg** [comment] 2016-08-06 14:01
I also noticed, that this does not happen when there's at least one non-editor pane (e.g. Settings) open

**Comment by 50Wliu** [comment] 2016-08-07 13:56
This is a duplicate of #12280 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-07 13:56 UTC
