### ISSUE TITLE
With no consent for data sharing and exception-reporting & metrics packages disabled, Atom still appears to contact some internet service in case of an error

### ISSUE THREAD

**Issue by JonasT** [atom/atom#13669] opened 2017-01-20 16:50 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With no consent for data sharing and exception-reporting & metrics packages disabled, Atom still appears to contact some internet service in case of an error.

Because this is a one time error incident, I haven't tested this in safe mode.

### What did I do to prevent data collection:
I disabled the exception-reporting and metrics package (before this incident occurred, and they are still disabled).
Additionally, in the initial new launch dialog which asks for data sharing consent, I haven't clicked yes on all of my machines, although I'm not sure if on this machine where I just ran into this I had Atom already installed before that dialog was introduced. (so I might not have said no on that dialog)

### How was the internet service connected

I got an exception, and it clearly refers to an issue on github which was already reported. I didn't click anything to make this happen, and still it clearly connected to some service to get this sort of information:
![atom-online-github](https://cloud.githubusercontent.com/assets/1573352/22157573/804b1a10-df38-11e6-9386-268f258b4c84.png)

### Steps to Reproduce
Since this is a one time incident for me, I'm not perfectly sure. It might be enough to just observe some exception.

**Expected behavior:** With exception-reporting and metrics disabled and no consent given for data collection, no internet service should be consulted ever without user interaction (package install, explicit query for error details, ..)
**Actual behavior:** Some online service appears to be consulted

**Reproduces how often:** unknown

### Versions

```
jonas@cyberman:~$ atom --version
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
jonas@cyberman:~$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.3
jonas@cyberman:~$
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment] 2017-01-20 18:07
How this works is it connects directly to GitHub and looks to see if there's already an issue open with the exception message.  If there isn't, it then offers you the option to create an issue on GitHub by going through is.gd (a URL-shortening service due to numerous problems with opening long URLs).

I believe that this was not covered by the metrics consent screen because you are explicitly in control of whether you want to file an issue or not.  That being said, this is otherwise a duplicate of https://github.com/atom/notifications/issues/144, so feel free to subscribe there for updates.

**Closed by 50Wliu** 2017-01-20 18:07 UTC

**Comment by JonasT** [comment] 2017-01-21 01:02
> I believe that this was not covered by the metrics consent screen because you are explicitly in control of whether you want to file an issue or not. 

I believe this is a mistake because GitHub appears to be immediately contacted to check if there is already an issue reported on the error. Therefore, clearly this should be covered by the initial metrics consent screen. If no metrics and exceptions reporting consent was given, the notifications dialog should ask first whether it should contact GitHub, instead of doing it automatically as of now.
