### ISSUE TITLE
cmd-l in multi-line selection doesn't select beginning of first line

### ISSUE THREAD

**Issue by colllin** [atom/atom#3624] opened 2014-09-25 01:52 UTC
When you you have no selection, with a cursor in the middle of a line, `cmd-l` selects the entire line, from the left side of the editor to the right side, including the ending newline.

When you have a selection that spans a few lines, `cmd-l` selects the end of the last line, but doesn't select the beginning of the first line.  I expected it to select the beginning of the first line too.
![Screen capture]
(http://cl.ly/image/042j0S2T1t04/Screen%20Recording%202014-09-24%20at%2007.47%20PM.gif)

**Comment by 50Wliu** [comment] 2015-04-13 23:01
Still reproducible in latest master.

**Comment by colllin** [comment] 2015-04-14 02:43
I'd be willing to look into it if someone could point me in the right direction.

**Comment by billyjanitsch** [comment] 2015-06-22 22:57
Some more inconsistent behavior here: if you click mid-way through a line, then shift+down and cmd+l, you get the behavior @colllin describes. If you do shift+up then cmd+l, the beginning of the first line is selected, but not the end of the last line. So, what seems to be going on is that cmd+l is adding the line containing the cursor to the selection, instead of adding all lines containing selected text to the selection.

Weirdly, if you click and drag from midway through a line to midway through the line above then cmd+l, it selects all of the upper line but deselects the lower line entirely.

Also happy to look into this and come up with a PR if someone can suggest where to look.

**Comment by jeancroy** [comment] 2015-09-02 18:36
OK the problem is here.
https://github.com/atom/atom/blob/v1.0.10/src/selection.coffee#L329-338

1) It'll only expand the line that contain the cursor.
2) The cursor is on the last selected line.

IE 
- select from top to bottom: only last line expand 
- select from bottom to top: only first line expand

**Comment by maxbrunsfeld** [comment] 2015-09-03 16:54
Fixed via #8646.

**Closed by maxbrunsfeld** 2015-09-03 16:54 UTC
Labels: bug

**Comment by colllin** [comment] 2015-09-03 17:20
YES!  :clap: @jeancroy

**Comment by billyjanitsch** [comment] 2015-09-03 18:13
Thank you so much @jeancroy!

**Comment by bronson** [comment] 2015-09-03 21:18
Very nice!  :rainbow: @jeancroy
