### ISSUE TITLE
Atom asks for permission for Contacts, Calendar, and Photos. 

### ISSUE THREAD

**Issue by theodormarcu** [atom/atom#18403] opened 2018-11-07 19:11 UTC
Atom asks for permission for Contacts, Calendar, and Photos. Is this normal? I did nothing special. Is this a rogue spyware plugin?

Edit: Added screenshots.
<img width="780" alt="screen shot 2018-11-07 at 14 12 23" src="https://user-images.githubusercontent.com/8714338/48154675-3613b380-e297-11e8-9a3c-ad25d3264f1f.png">
<img width="780" alt="screen shot 2018-11-07 at 14 12 17" src="https://user-images.githubusercontent.com/8714338/48154676-36ac4a00-e297-11e8-8d38-cf368cd95707.png">
<img width="780" alt="screen shot 2018-11-07 at 14 12 20" src="https://user-images.githubusercontent.com/8714338/48154677-36ac4a00-e297-11e8-8cf3-54bfc91c9d86.png">

**Comment by rsese** [comment] 2018-11-07 19:19
Thanks for contributing!

Closing as a duplicate of https://github.com/atom/atom/issues/17687, see this FAQ item for more details:

https://discuss.atom.io/t/why-does-macos-say-that-atom-wants-to-access-my-calendar-contacts-photos-etc/59291

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-07 19:19 UTC
