### ISSUE TITLE
Warp function works wrong with full-width letters(Chinese)

### ISSUE THREAD

**Issue by DeckerCHAN** [atom/atom#5146] opened 2015-01-19 18:33 UTC
![default](https://cloud.githubusercontent.com/assets/1845937/5805673/f8f86dec-a04b-11e4-8cc4-20661e3b1dc6.PNG)

You could see that warp works fine with half-width letters(English) at first line.   
But something wrong with warp in second line which filled with Chinese characters.
Actually, the correct character after the warp should be "一" , however, it showed "九".
Currently using the latest version(0.174.0 2015/1/16)

**Comment by benogle** [comment] 2015-01-19 19:06
Dupe of #1783

**Closed by benogle** 2015-01-19 19:06 UTC
