### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 6209Error: Cannot ca...

### ISSUE THREAD

**Issue by nevillenzf** [atom/atom#20125] opened 2019-11-07 03:27 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 6209
Error: Cannot call function 'getPosition' on missing remote object 6209
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 6209
Error: Cannot call function 'getPosition' on missing remote object 6209
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705396)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705811)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -4:47.5.0 editor:newline (input.hidden-input)
  3x -4:46.2.0 core:backspace (input.hidden-input)
     -3:42.5.0 core:save (input.hidden-input)
     -3:31.5.0 core:cut (input.hidden-input)
     -3:30.8.0 core:save (input.hidden-input)
     -3:29.1.0 editor:newline (input.hidden-input)
     -3:27.9.0 core:paste (input.hidden-input)
     -3:24.9.0 core:backspace (input.hidden-input)
     -3:23.4.0 core:move-right (input.hidden-input)
  4x -3:23.2.0 core:backspace (input.hidden-input)
  4x -3:19.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
fast-eslint 4.11.0 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.0 
```

**Comment by rsese** [comment] 2019-11-11 01:10
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

If the error is reproducible for you, please let us know the steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).  It would also be helpful to know if you can reproduce with the current [stable release (1.41.0)](https://github.com/atom/atom/releases/tag/v1.41.0) which is running Electron 4.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-11 01:10 UTC
