### ISSUE TITLE
Display Progress of Download of a package 

### ISSUE THREAD

**Issue by bauripalash** [atom/atom#17383] opened 2018-05-22 04:27 UTC
## Summary

It would a good idea to show a progress bar of how much is downloaded when installing a package via `apm` or `atom ui`

## Motivation

When installing a package via `apm` or `atom ui` it sometimes took a long time, so sometimes it let me think, is it really downloading something or it crashed?

## Additional context

It would be helpful for many people. i hope this feature will be added in next releases.

**Comment by rsese** [comment] 2018-05-22 17:12
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/apm/issues/148 so you can subscribe there if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-22 17:12 UTC
