### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by bnb** [atom/atom#7355] opened 2015-06-21 13:02 UTC
1. Right click on a file in tree view.

**Atom Version**: 0.210.0
**System**: Microsoft Windows 10 Home Insider Preview
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:150:33)
    at HTMLDocument.handler (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\Tierney\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -1:05.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:03.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:00.0 core:undo (atom-text-editor.editor.is-focused)
  4x -0:57.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:48.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "C:\\Users\\Tierney\\code\\personal"
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true,
    "scrollSensitivity": 60,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "tabLength": 4,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
file-type-icons, v0.7.0
flex-tool-bar, v0.4.2
minimap, v4.10.0
new-tab, v0.3.0
pain-split, v1.4.0
project-manager, v1.15.10
symbols-tree-view, v0.9.3
tool-bar, v0.1.7
tool-bar-main, v0.0.8
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-06-21 13:09
This is a duplicate of https://github.com/atom/atom/issues/6548 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-21 13:09 UTC
