### ISSUE TITLE
UX: Inconsistent position of "Search in Directory" menu item

### ISSUE THREAD

**Issue by lbebber** [atom/atom#8991] opened 2015-09-29 14:52 UTC
If I right click on the project folder, the search button is down there:
![atom1](https://cloud.githubusercontent.com/assets/5691711/10167669/e5ac76f0-669f-11e5-8d93-dc464e8cddc9.jpg)

However, it's on the top of the menu if I right click on any sub folder:
![atom2](https://cloud.githubusercontent.com/assets/5691711/10167670/e5adb0ce-669f-11e5-95d6-32a4ebaee422.jpg)

**Comment by mnquintana** [comment] 2015-09-29 21:42
Thanks for the report! This looks like a duplicate of https://github.com/atom/tree-view/issues/535 – closing this out in favor of that issue.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Closed by mnquintana** 2015-09-29 21:42 UTC
