### ISSUE TITLE
Linux closing tab with middle mouse pastes text in next tab

### ISSUE THREAD

**Issue by nebularazer** [atom/atom#15039] opened 2017-07-17 07:54 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Text from your clipboard will be pasted into the next tab when closing another tab with middle mouse button.

### Steps to Reproduce

1. Open two tabs and safe the content
2. ctrl-c some text to clipboard
3. close one of the two tabs with middle mouse button
4. text from clipboard gets pasted into the remaining open tab

**Expected behavior:** Just close the tab.

### Versions

```
atom-beta --version
Atom    : 1.19.0-beta4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

OS: Linux Fedora 25
Kernel: 4.11.9-200.fc25.x86_64

### Additional Information

Works fine on Atom 1.18.
Broken since: 1.19.0-beta1

Maybe related to: #8648

**Comment by 50Wliu** [comment] 2017-07-17 14:41
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/tabs#461. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-07-17 14:41 UTC
