### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '~/Documents\Ejercicios Pagina Web\HTML.html'

### ISSUE THREAD

**Issue by victoriaramire** [atom/atom#21894] opened 2021-01-25 22:14 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat 'C:\Users\Victoria Rmz\Documents\Ejercicios Pagina Web\HTML.html'

```
At fs.js:126

Error: EPERM: operation not permitted, lstat 'C:\Users\Victoria Rmz\Documents\Ejercicios Pagina Web\HTML.html'
    at Proxy.realpathSync (fs.js:1470:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:996503)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1003449)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:976665)
```

### Commands

```
  2x -7:52.6.0 tree-view:rename (div.title)
     -7:24.5.0 tree-view:show-current-file-in-file-manager (div.title)
     -6:49.9.0 tree-view:rename (div.title)
 70x -6:45.2.0 core:backspace (input.hidden-input)
     -6:31.1.0 core:confirm (input.hidden-input)
     -6:15.8.0 tree-view:show-current-file-in-file-manager (div.title)
```

### Non-Core Packages

```

```

**Comment by darangi** [comment] 2021-01-27 17:43
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/19433 so you can subscribe there for updates if you'd like.   If you have specific steps to reproduce, please let us know in https://github.com/atom/atom/issues/19433.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2021-01-27 17:43 UTC
