### ISSUE TITLE
Patch not replacing file associations (Windows 8.1 x64)

### ISSUE THREAD

**Issue by deathernater** [atom/atom#5234] opened 2015-01-23 15:21 UTC
Whenever Atom updates, opening a file associated with Atom will open only the old version. The updated Atom is in a different folder, and I have to delete the old folder and re-associate. Is there a way to fix this, and delete the previous installation of Atom after an update?

**Comment by kevinsawicki** [comment] 2015-01-23 17:27
Are you referring to the `Open With Atom` context menu in the explorer not working correctly?

**Comment by deathernater** [comment] 2015-01-23 17:33
I am not referring to that, I am referring to associating a .txt or .java
file to open with atom under properties. The old version will load (if I
don't manually delete it) if I double click the file to open it. I am using
the official installtion shortcut to make the association, not the absolute
path of the old version in its folder. It seems like a waste of space also
to keep old versions of Atom also.

**Comment by 50Wliu** [comment] 2015-01-23 17:48
It is not a waste of space.  The installer only keeps one backup version which is to ensure that you are still able to use Atom if the new version is horribly broken.  Chrome does this too.
All that Atom really needs to do now is to provide a stable path to the Atom executable.

**Comment by deathernater** [comment] 2015-01-23 17:56
Well I agree, but atom keeps every version and it has been quite a few
releases. I am not saying it shouldn't do that at all. But back to the
problem it shouldn't open up the old version like that from double clicking
on an associated file, just to update again and overwrite the files in the
update folder. It has been quite a few releases and it wasn't fixed so I
wanted to bring this issue into light (if it wasn't reported before).

**Comment by 50Wliu** [comment] 2015-01-23 18:18
Hmm.  Are you using Chocolatey or the new Atom installer?

**Comment by deathernater** [comment] 2015-01-23 18:30
The new installer

**Comment by madhead** [comment] 2015-03-26 09:28
@kevinsawicki I have problems with "Open with Atom" too. When use context menu for folders, old version is opened.

Also, I have problems opening file with new version of editor. I've configured editor in Total Commander as `C:\Users\Siarhei_Krukau\AppData\Local\atom\Update.exe --processStart atom.exe %1`, but this does not open files since last update (0.188)

**Comment by batjko** [comment] 2015-03-26 13:28
I can confirm that (at least on Windows) it doesn't seem to remove previous versions.

Although it tries. 

For example, in this case it was unable to get rid of some versions, with Windows complaining it can't remove non-empty folders:

     ApplyReleasesImpl: cleanDeadVersions: for version 0.187.0
     ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.186.0
     ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.187.0
     Utility: DeleteDirectory: could not delete -      c:\Users\[username]\AppData\Local\atom\app-   0.184.0\resources\app\node_modules\open-on-github\spec\fixtures\github-   enterprise-remote.git\objects: System.IO.IOException: The directory is not empty.
 
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean  recursive, Boolean throwOnTopLevelDirectoryNotFound)
     at System.IO.Directory.Delete(String fullPath, String userPath, Boolean  recursive, Boolean checkHost)
     at Squirrel.Utility.<DeleteDirectory>d__36.MoveNext()
     Utility: DeleteDirectory: could not delete -    c:\Users\[username]\AppData\Local\atom\app-  0.184.0\resources\app\node_modules\open-on-github\spec\fixtures\github- enterprise-remote.git: System.IO.IOException: The directory is not empty.

However, when I just kicked off an update again, it did remove the v186 folder (and left the one for v184 behind for some reason):
![image](https://cloud.githubusercontent.com/assets/7287076/6847105/e5901f7c-d3bb-11e4-971f-54f0c5dc5eb5.png)

    ApplyReleasesImpl: cleanDeadVersions: for version 0.188.0
    ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.187.0
    ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.188.0

**Comment by panfeng** [comment] 2015-06-13 20:02
https://discuss.atom.io/t/uninstall-on-windows-leaves-context-menu-items/12818

I fixed by removing the "Atom" folder from registry.

**Comment by codekraft-studio** [comment] 2015-08-08 16:35
Is this bug fixed?

**Comment by mloskot** [comment] 2015-09-28 12:11
@madhead I can confirm your problem using 1.0.19.
It is an annoyance I can't set up an application to load a file into Atom using stable Atom.exe location.

**Comment by dmase44** [comment] 2015-11-16 02:18
With atom 1.0.11.0 on win7 I was able to associate file types by going to control panel/default programs/ associate a file type with a specific program, select the file type then hit the change program button then other programs drop down and atom was there to select. Having upgraded to 1.2.0 this option has evaporated then hit the browse button and have tried ever path I can to no avail. Where is the path for the real atom.exe? Atom does not even show in the list of default programs. I go to programs GitHub, Inc and there's the atom.ico. Right click, open file location and it takes me to path... appdata/local/atom/update.exe which does not work. Next folder up app-1.2.0 /atom.exe which does not work either. Target> Update.exe --processStart atom.exe? This sucks as all the file associations are linked to Brackets that I was previously using. If I can't get the file types associated w/ 1.2 I guess  I'll go back to 1.0.11 or Brackets. I have way to much time with this and searched this forum for an answer and none of posted suggestions I have tried work. I can say this is the first editor I have had, out of several, since the late 90's that does not have that option built in. I do hope I find a solution here. 
Thanks for your time

**Comment by dmase44** [comment] 2015-11-17 15:23
Previous to the 1.2.0 update my file association were working fine and the atom.ico was present in default programs. Now every workaround I have tried does not work. Most end up pointing to Update.exe witch does nothing. The atom/app-1.2.0/atom.exe does open atom but doesn't show in the default programs to select for file associations even after setting it in the variable path. This is a shame having to right click on a Brackets icon to open with Atom. I have tried every suggestion posted in these pages to no avail.

**Comment by damieng** [comment] 2016-02-23 04:43
Atom.exe is now registered in the correct place in the registry as of f8ae09b1122ded5de3d4958630b485a2e1fd82a0 to be a file handler. (This will ship in a future release)

When you choose "Open with > Choose another app" now Atom will appear in the subsequent list (you may have to click more apps) so you do not need to choose a path or executable by hand.

Any associations made this way will be linked to the atom.exe registry entry which is kept up to date as part of the installer.

**Closed by damieng** 2016-02-23 04:43 UTC
Labels: auto-updater, bug, windows
