### ISSUE TITLE
Dev-linked default-installed package's stylesheets not loaded

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#4870] opened 2015-01-06 16:07 UTC
I'm taking a look at bracket-matcher due to #4868 and I'm trying to test changes I'm making to the stylesheet, but when I:

1. `apm link` (whether `--dev` or not) the bracket-matcher package
1. Start Atom in the appropriate mode

The stylesheet for the bracket-matcher package isn't loaded:

![screen shot 2015-01-06 at 8 03 07 am](https://cloud.githubusercontent.com/assets/1038121/5631319/7e0d47fa-957a-11e4-907d-06fbef25a80e.png)

Isn't here either:

![screen shot 2015-01-06 at 8 03 45 am](https://cloud.githubusercontent.com/assets/1038121/5631329/93320724-957a-11e4-9f0e-33750c193552.png)

This is with the Shadow DOM enabled.

If I unlink the bracket-matcher package and restart Atom, everything works as expected:

![screen shot 2015-01-06 at 8 05 13 am](https://cloud.githubusercontent.com/assets/1038121/5631357/c6106b5e-957a-11e4-8a04-b8dcf6c42f9f.png)

Atom v0.167.0-a9c0553 on Mac OS X 10.10.1

/cc @nathansobo

**Comment by nathansobo** [comment] 2015-01-06 17:29
Taking a look.

**Comment by nathansobo** [comment] 2015-01-06 17:34
I'm having trouble reproducing this. I set the status-bar element's background to red and it worked in dev mode. The bracket-matcher package definitely has issues with the default styles though.

**Comment by nathansobo** [comment] 2015-01-06 17:38
Now I've been able to reproduce it, but not quite sure how. Stay tuned.

**Comment by nathansobo** [comment] 2015-01-06 17:47
I noticed that my bracket-matcher package wasn't loading due to an incompatible compiled module. I ran `apm rebuild` and it then loaded correctly. Could this be the problem? I was able to fix the default styling in [this commit](https://github.com/atom/bracket-matcher/commit/069a47c49123bdf68c278667803555146a10ca7c) and observe it working with `apm link --dev`.

**Comment by nathansobo** [comment] 2015-01-06 18:05
Closing this for now. Reopen if I'm missing something.

**Closed by nathansobo** 2015-01-06 18:05 UTC
Labels: bug

**Comment by lee-dohm** [comment] 2015-01-07 01:14
It must have been something like that, I was pretty rushed this morning and wanted to get this recorded before I forgot half of it. I'll reopen if I run into anything, but I doubt it. Thanks @nathansobo!
