### ISSUE TITLE
Syntax Error Issue -_- 2 month of trying fix this issue .

### ISSUE THREAD

**Issue by VolcanoMc** [atom/atom#12199] opened 2016-07-20 11:57 UTC
I am not so happy to type too much my problem mentioned before in this website but it wasn't full and it was only for Linux Users what about those people whom using windows how to fix that Syntax error of theme crashing .... 

  at new Parser (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\less-cache\node_modules\less\lib\less\parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:255:16)
    at LessCache.module.exports.LessCache.cssForFile (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:286:20)
    at LessCache.module.exports.LessCache.readFileSync (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\less-cache\lib\less-cache.js:274:19)
    at LessCompileCache.module.exports.LessCompileCache.read (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\src\less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\src\theme-manager.js:281:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\src\theme-manager.js:257:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\src\theme-manager.js:174:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\src\theme-manager.js:237:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\src\theme-manager.js:232:19)
    at new AtomEnvironment (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:269:19)
    at module.exports (C:\Users\aei94\AppData\Local\atom\app-1.8.0\resources\app.asar\src\initialize-application-window.js:25:19)
    at setupWindow (file:///C:/Users/aei94/AppData/Local/atom/app-1.8.0/resources/app.asar/static/index.js:87:12)
    at window.onload (file:///C:/Users/aei94/AppData/Local/atom/app-1.8.0/resources/app.asar/static/index.js:41:9)

it's totally pieced me of ....

**Comment by 50Wliu** [comment] 2016-07-20 13:58
This is a duplicate of your comment in #7282.

**Closed by 50Wliu** 2016-07-20 13:58 UTC
