### ISSUE TITLE
autosave should not have two ways to enable/disable

### ISSUE THREAD

**Issue by TheLastProject** [atom/atom#6170] opened 2015-03-30 17:57 UTC
As each package has an enable/disable option through the settings view, a package should not have its own enable/disable setting, as a package should never have to check for itself if it is enabled or not.

If autosave is not something that should be enabled by default (which I feel it isn't), it probably shouldn't even be installed by default in the first place.

Small cleanups like these could probably help make Atom faster. Even though it's only 2ms in this case, all bits help (especially because the Atom startup time, on my desktop, is currently around 7 seconds).

![autosave](https://cloud.githubusercontent.com/assets/1885159/6902810/73342578-d716-11e4-815e-7e316b4d49f6.png)

**Comment by izuzak** [comment] 2015-03-30 18:01
I think this is a duplicate of https://github.com/atom/autosave/issues/14.

**Closed by izuzak** 2015-03-30 18:01 UTC
