### ISSUE TITLE
Syntax highlighting conditionally works on super-long HTML file

### ISSUE THREAD

**Issue by suvjunmd** [atom/atom#11232] opened 2016-03-21 19:17 UTC
Atom 1.6.0 on Windows 10.

Syntax highlighting doesn't work for the file https://raw.githubusercontent.com/kangax/compat-table/gh-pages/es6/index.html. Although it works fine for other html files from the same repository.

![c757788e-eec2-11e5-8273-0f0235a7b306](https://cloud.githubusercontent.com/assets/11020536/13931051/3cceca08-efaa-11e5-96ff-6a680103ef2c.png)

**Comment by Zireael07** [comment] 2016-03-21 20:26
How long is the file? Are there any long lines in it? Any non-ASCII characters?

**Comment by abejfehr** [comment] 2016-04-21 12:14
That's hardly an HTML file, it's basically a small database. I don't think it's practical to keep HTML files this large (3.8MB) and I don't know if it's possible to do syntax highlighting without my computer catching fire

**Comment by lee-dohm** [comment] 2016-04-21 20:21
I can't reproduce this using Atom v1.7.2 on Mac OS X 10.11.4. @suvjunmd Does this reproduce for you on the latest Atom version?

**Comment by suvjunmd** [comment] 2016-04-23 17:06
@lee-dohm, yes, it does repoduce in Atom 1.7.2

**Comment by lee-dohm** [comment] 2016-04-23 20:17
Can you reproduce the issue in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by suvjunmd** [comment] 2016-04-23 20:43
@lee-dohm, same in safe mode:
![safe](https://cloud.githubusercontent.com/assets/11020536/14763900/1d2a130c-09ad-11e6-95c5-0838eedb7463.png)

**Comment by 50Wliu** [comment] 2016-04-23 21:21
This works for me as well on Ubuntu 16.04, though it takes quite a while to highlight the whole file.

**Comment by 50Wliu** [comment] 2016-04-25 20:53
Unable to reproduce on Windows 10 x64, Atom 1.9.0-dev-9175194.  I did not test in safe mode for either Ubuntu or Windows.

**Comment by lee-dohm** [comment] 2016-04-27 17:27
@suvjunmd Are you running Windows 10 x64? Or the 32-bit version? (Do they have a 32-bit version anymore?)

**Comment by damieng** [comment] 2016-04-27 18:02
I am also seeing this with that file on Windows 10 x64. If I cut the file down to about 32,000 lines/1.93MB then it starts highlighting (you have to re-open atom and give the file a new name - I suspect it caches that syntax highlighting is disabled).

I'm guessing this is part of our performance code to not highlight things too large. It would be great if there was a tooltip over the syntax highlighting button in the status bar that indicated why...

**Comment by lee-dohm** [comment] 2016-04-27 18:24
I was able to reproduce this by:

1. Copying the text from the Gist above
1. Pasting it into a new file
1. Saving the file as `test.html`
1. Closing the file
1. Renaming `test.html` to `test1.html`
1. Opening `test1.html`

Whereas if I paste the text into a new file and then set the syntax to HTML, it eventually works.

**Comment by suvjunmd** [comment] 2016-04-30 15:58
@lee-dohm, I'm running Windows 10 x64. Also, I was able to reproduce this on Windows 7 x64.

**Comment by whizkydee** [comment] 2016-08-23 07:18
Same in SQL files as #12403.

**Comment by simurai** [comment] 2016-11-23 13:50
Syntax highlighting gets now (June 2015) disabled for files larger than 2MB, see https://github.com/atom/atom/pull/7130 for more details.

I like @damieng's suggestion:

> It would be great if there was a tooltip over the syntax highlighting button in the status bar that indicated why...

**Comment by mossarelli** [comment] 2016-12-30 10:35
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I use Atom to write HTML files that uses CSS, Bootstrap and JS for work but there's a repeating issue that I keep seeing when I work.
Any line longer than 280-320 characters stops highlighting and keeps the highlight from the last lint state.

This happens with and without softwrap, also in safemode and normal mode:
![wrap](https://cloud.githubusercontent.com/assets/2856049/21563362/e78f5cbc-ce81-11e6-90f9-7c42db989dd4.jpg)

### Steps to Reproduce

1. Paste the following HTML into your Atom editor:
`<p>Resultatet blir att siffrorna: <code class="lua hljs"><span class="hljs-number">0</span></code>, <code class="lua hljs"><span class="hljs-number">1</span></code>, <code class="lua hljs"><span class="hljs-number">2</span></code>, <code class="lua hljs"><span class="hljs-number">3</span></code> skrivs ut i konsolen. Anledningen till att <code class="lua hljs"><span class="hljs-number">4</span></code> inte skrivs ut är för att <code class="lua hljs"><span class="hljs-keyword">while-do</span></code> inte körs när <code class="lua hljs">i</code> blivit <code class="lua hljs"><span class="hljs-number">4</span></code>.</p>`
2. Check if highlighting works from beginning to end

**Expected behavior:**
Syntax highlighting should not be limited by line character length and the HTML highlight should work regardless of length.

**Actual behavior:**
Syntax highlightning fails.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the times the line length exceeds 280 characters.

### Versions

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 3.5.1
git
visual studio

Microsoft Windows 10 Home x64

### Additional Information

The HTML files are under 2MB in size.

Additional packages:
atom-beautify
atom-format-lua
atom-touch-events
auto-detect-indentation
duplicate-removal
file-icons
fonts
highlight-selected
html-entities
language-lua
livereload
minimap
minimap-highlight-selected
minimap-pigments
open-recent
pigments
project-manager
script
todo-show

inb4:
you are writing HTML wrong

**Comment by 50Wliu** [comment] 2016-12-31 01:38
@mossarelli Your issue is a different issue that is being tracked at #1667.

**Comment by stavnstrup** [comment] 2017-02-10 06:10
Will another panel syntax color the large file in a fraction as a second, although the mail window won't, as reported in #13588.

**Comment by chrisvio** [comment] 2017-10-15 15:58
I'm running into this with "large" files as well. Any file larger than 2048K will not highlight.

**Comment by lee-dohm** [comment] 2017-10-15 18:36
The following behavior is expected:

* Files larger than 2MB will not be syntax highlighted - #7130
* Lines longer than ~100 tokens will not be syntax highlighted - #1667

And since I just tested this issue based on the repro steps I [mentioned above](https://github.com/atom/atom/issues/11232#issuecomment-215182011) and was not able to reproduce this issue, it would appear that this is fixed. The syntax highlighting breaks at approximately line 380 at this construct:

```html
<tr class="subtest" data-parent="proper_tail_calls_(tail_call_optimisation)" id="test-proper_tail_calls_(tail_call_optimisation)_mutual_recursion"><td><span><a class="anchor" href="#test-proper_tail_calls_(tail_call_optimisation)_mutual_recursion">&#xA7;</a>mutual recursion</span><script data-source="
&quot;use strict&quot;;
function f(n){
  if (n &lt;= 0) {
    return  &quot;foo&quot;;
  }
  return g(n - 1);
}
function g(n){
  if (n &lt;= 0) {
    return  &quot;bar&quot;;
  }
  return f(n - 1);
}
return f(1e6) === &quot;foo&quot; &amp;&amp; f(1e6+1) === &quot;bar&quot;;
      ">test(function(){try{var asyncTestPassed=global.__asyncPassedFn && __asyncPassedFn("2");try{return Function("asyncTestPassed","\n\"use strict\";\nfunction f(n){\n  if (n <= 0) {\n    return  \"foo\";\n  }\n  return g(n - 1);\n}\nfunction g(n){\n  if (n <= 0) {\n    return  \"bar\";\n  }\n  return f(n - 1);\n}\nreturn f(1e6) === \"foo\" && f(1e6+1) === \"bar\";\n      ")(asyncTestPassed)}catch(e){asyncTestPassed=global.__strictAsyncPassedFn && __strictAsyncPassedFn("2");return Function("asyncTestPassed","'use strict';"+"\n\"use strict\";\nfunction f(n){\n  if (n <= 0) {\n    return  \"foo\";\n  }\n  return g(n - 1);\n}\nfunction g(n){\n  if (n <= 0) {\n    return  \"bar\";\n  }\n  return f(n - 1);\n}\nreturn f(1e6) === \"foo\" && f(1e6+1) === \"bar\";\n      ")(asyncTestPassed)&&"Strict"}}catch(e){return false;}}());
```

which appears to be from the 100 token rule.

If people have something that is not due to the long file or long line rule that is exhibiting strange behavior, please open a new issue.

**Closed by lee-dohm** 2017-10-15 18:36 UTC
Labels: bug
