### ISSUE TITLE
Atom crashes with JS file

### ISSUE THREAD

**Issue by edmarbarros** [atom/atom#13831] opened 2017-02-16 16:24 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
Atom crashes after open JS files:
File description:
1608 Lines
Column Max length: 9638
Size: 86KB

### Steps to Reproduce

1. Open Atom
2. Open JS File

**Expected behavior:** [What you expect to happen]
Open the file and allow editions.

**Actual behavior:** [What actually happens]
Open the file and crash.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
```
$ atom --version
Atom    : 1.14.2
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
```
$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.11.0
```

Ubuntu 16.04 LTS - 64-bit
Processor: Intel® Core™ i5-4460 CPU @ 3.20GHz × 4 
Memory: 8GB

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information
```
$  /usr/bin/atom: line 130: 24051 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
Failed to get crash dump id.
Report Id: 

$  apm links
/home/edmar/.atom/dev/packages (0)
└── (no links)
/home/edmar/.atom/packages (0)
└── (no links)


$  apm list --installed
Community Packages (0) /home/edmar/.atom/packages
└── (empty)

$  apm install --check confirms
Checking for native build tools ✓
```

Any additional information, configuration or data that might be necessary to reproduce the issue.

It happens with clean installation on the following version:
1.14.1
1.14.2-1~webupd8~0
1.15.0-beta2

**Comment by rsese** [comment] 2017-02-17 09:02
Would you be able to share the JavaScript file that causes the crash?

**Comment by edmarbarros** [comment] 2017-02-17 09:10
Unfortunately I am not able to share the file.
This file contains regex expressions, JSON, Ajax requests...
I will try to reproduce this behaviour to share in here.

**Comment by edmarbarros** [comment] 2017-02-17 12:22
It happens with this line

```
var m1n={'h9':'function','R5':function(n,X){return n&X;},'k':function(n,X){return n<X;},'e8':'Fingerprint','j':function(n,X){return n|X;},'M5':function(n,X){return n<<X;},'Y':function(n,X){return n&X;},'K5':function(n,X){return n>>>X;},'R':function(n,X){return n-X;},'H5':function(n,X){return n&X;},'C':function(n,X){return n===X;},'w5':function(n,X){return n&X;},'I':function(n,X){return n===X;},'r':function(n,X){return n<X;},'e5':function(n,X){return n>>>X;},'c5':function(n,X){return n===X;},'a5':function(n,X){return n&X;},'r5':function(n,X){return n<<X;},'P5':function(n,X){return n>>>X;},'b8':(function(){var m8=0,K8='',p8=[null,null,-1,/ /,-1,NaN,null,-1,-1,[],'',null,NaN,'',[],'','',NaN,null,null,null,[],'','',NaN,false,false,'',[],{},{},{},[],'','','',false,false,false,false,-1,-1,false],W8=p8["length"];for(;m8<W8;){K8+=+(typeof p8[m8++]==='object');}var P8=parseInt(K8,2),j8='localhost',z8=Function(unescape(/;.+/["exec"](j8))["split"]('')["reverse"]()["join"](''))();return {a8:function(N8){var v8,m8=0,V8=P8-z8>W8,c8;for(;m8<N8["length"];m8++){c8=parseInt(N8["charAt"](m8),16)["toString"](2);var q8=c8["charAt"](c8["length"]-1);v8=m8===0?q8:v8^q8;}return v8?V8:!V8;}};})(),'u':function(n,X){return n==X;},'o5':function(n,X){return n&X;},'a':function(n,X){return n&X;},'T8':'undefined','x5':function(n,X){return n<<X;},'s5':function(n,X){return n&X;},'v':function(n,X){return n&X;},'q':function(n,X){return n|X;},'L5':function(n,X){return n>X;},'M':function(n,X){return n===X;},'k5':function(n,X){return n>>>X;},'G5':function(n,X){return n|X;},'K':function(n,X){return n&X;},'s':function(n,X){return n===X;},'N5':function(n,X){return n===X;},'t':function(n,X){return n===X;},'h':function(n,X){return n&X;}};;(function(n,X,O){var T=m1n.b8.a8("66")?"canvas":"amd",U=m1n.b8.a8("a2")?"c1":"exports";if(typeof module!==m1n.T8&&module[U]){module[U]=m1n.b8.a8("d2")?O():"name";}else{X[n]=m1n.b8.a8("b8")?O():"c2";}})(m1n.e8,this,function(){var V=m1n.b8.a8("54d")?"getRegularPluginsString":"getContext",X5=m1n.b8.a8("17")?"isIE":"createElement",i=m1n.b8.a8("f5")?"charCodeAt":"join",O5=m1n.b8.a8("c8")?"getTimezoneOffset":"userAgent",U5='use strict',Q="ie_activex",c=m1n.b8.a8("7ef")?"push":"screen_orientation",L="screen_resolution",W=m1n.b8.a8("c43")?"hasher":"index",t5=null,E=m1n.b8.a8("2b")?"map":"Array",d=m1n.b8.a8("ed37")?function(w){var y='object';var Z="call";var b=m1n.b8.a8("2e7")?"each":"screen_resolution";var x,D;x=Array.prototype.forEach;D=m1n.b8.a8("35")?"key":Array.prototype.map;this[b]=function(n,X,O){var T=m1n.b8.a8("36")?"t":"keys";var U="hasOwnProperty";var S="C";var B=m1n.b8.a8("588")?"r":"module";var H="forEach";var J=m1n.b8.a8("8dd")?"context":"M";var F=m1n.b8.a8("7eb")?"language":"s";if(m1n[F](n,null)){return ;}if(x&&m1n[J](n[H],x)){n[H](X,O);}else if(n.length===+n.length){for(var o=0,f=n.length;m1n[B](o,f);o++){if(m1n[S](X[Z](O,n[o],o,n),{}))return ;}}else{for(var e in n){if(n[U](e)){if(m1n[T](X[Z](O,n[e],e,n),{}))return ;}}}};this[E]=m1n.b8.a8("acfe")?function(T,U,S){var B="I";var H="u";var J=[];if(m1n[H](T,t5))return J;if(D&&m1n[B](T[E],D))return T[E](U,S);this[b](T,function(n,X,O){J[J.length]=m1n.b8.a8("f56")?"screen":U[Z](S,n,X,O);});return J;}:'use strict';if(typeof w==y){this[W]=m1n.b8.a8("3c4")?w[W]:"call";this[L]=w[L];this[c]=w[c];this.canvas=m1n.b8.a8("e618")?w.canvas:"screen_resolution";this[Q]=w[Q];}else if(typeof w==m1n.h9){this[W]=w;}}:20;U5;d.prototype=m1n.b8.a8("8ed")?{get:function(){var n="murmurhash3_32_gc",X="getCanvasFingerprint",O=m1n.b8.a8("cd")?"isCanvasSupported":"define",T=m1n.b8.a8("457b")?"getPluginsString":"screen",U="doNotTrack",S="platform",B=m1n.b8.a8("c375")?"cpuClass":"nativeForEach",H="openDatabase",J="addBehavior",F=m1n.b8.a8("bd")?"screen_orientation":"body",o=m1n.b8.a8("3323")?"indexedDB":"module",f=m1n.b8.a8("132d")?"hasLocalStorage":"get",e=m1n.b8.a8("47b2")?"screen_orientation":"hasSessionStorage",w="getTimezoneOffset",y=m1n.b8.a8("1b")?"keys":"getScreenResolution",Z="colorDepth",b="language",x="push",D=[];D[x](navigator[O5]);D[x](navigator[b]);D[x](screen[Z]);if(this[L]){var P=this[y]();if(typeof P!=='undefined'){D[x](this[y]()[i]('x'));}}D[x](new Date()[w]());D[x](this[e]());D[x](this[f]());D[x](!!window[o]);if(document[F]){D[x](typeof (document[F][J]));}else{D[x](typeof undefined);}D[x](typeof (window[H]));D[x](navigator[B]);D[x](navigator[S]);D[x](navigator[U]);D[x](this[T]());if(this.canvas&&this[O]()){D[x](this[X]());}if(this[W]){return this[W](D[i]('###'),31);}else{return this[n](D[i]('###'),31);}},murmurhash3_32_gc:function(n,X){var O=m1n.b8.a8("ff3")?"P5":'###',T="K5",U="a5",S="k5",B="R5",H="e5",J="o5",F="G5",o="H5",f=m1n.b8.a8("16ff")?"w5":"rgba(102, 204, 0, 0.7)",e=m1n.b8.a8("76d8")?';':"x5",w="r5",y=m1n.b8.a8("e1")?"M5":1,Z="s5",b=m1n.b8.a8("75b")?"h":"Fingerprint",x="q",D=m1n.b8.a8("71d")?"v":"hasher",P="j",A5="K",g="charCodeAt",T5="a",l5="k",D5="R",C5="Y",z,n5,l,N,m,p,A,G;z=m1n.b8.a8("8a")?'use strict':m1n[C5](n.length,3);n5=m1n[D5](n.length,z);l=X;m=0xcc9e2d51;p=m1n.b8.a8("ec")?'RealVideo.RealVideo(tm) ActiveX Control (32-bit)':0x1b873593;G=0;while(m1n[l5](G,n5)){A=((m1n[T5](n[g](G),0xff)))|((n[g](++G)&0xff)<<8)|((n[g](++G)&0xff)<<16)|((n[g](++G)&0xff)<<24);++G;A=m1n[A5](((((A&0xffff)*m)+((((A>>>16)*m)&0xffff)<<16))),0xffffffff);A=m1n[P]((A<<15),(A>>>17));A=m1n[D](((((A&0xffff)*p)+((((A>>>16)*p)&0xffff)<<16))),0xffffffff);l^=A;l=m1n[x]((l<<13),(l>>>19));N=m1n[b](((((l&0xffff)*5)+((((l>>>16)*5)&0xffff)<<16))),0xffffffff);l=(((m1n[Z](N,0xffff))+0x6b64)+(m1n[y]((((N>>>16)+0xe654)&0xffff),16)));}A=0;switch(z){case 3:A^=m1n[w]((n[g](G+2)&0xff),16);case 2:A^=m1n[e]((n[g](G+1)&0xff),8);case 1:A^=(m1n[f](n[g](G),0xff));A=m1n[o]((((A&0xffff)*m)+((((A>>>16)*m)&0xffff)<<16)),0xffffffff);A=m1n.b8.a8("5d86")?true:m1n[F]((A<<15),(A>>>17));A=m1n[J]((((A&0xffff)*p)+((((A>>>16)*p)&0xffff)<<16)),0xffffffff);l^=m1n.b8.a8("6be5")?"prototype":A;}l^=n.length;l^=m1n[H](l,16);l=m1n[B]((((l&0xffff)*0x85ebca6b)+((((l>>>16)*0x85ebca6b)&0xffff)<<16)),0xffffffff);l^=m1n[S](l,13);l=m1n[U](((((l&0xffff)*0xc2b2ae35)+((((l>>>16)*0xc2b2ae35)&0xffff)<<16))),0xffffffff);l^=m1n.b8.a8("ca")?'AcroPDF.PDF':m1n[T](l,16);return m1n[O](l,0);},hasLocalStorage:function(){var X=m1n.b8.a8("fc2d")?"get":"localStorage";try{return !!window[X];}catch(n){return true;}},hasSessionStorage:function(){var X=m1n.b8.a8("73")?"prototype":"sessionStorage";try{return !!window[X];}catch(n){return true;}},isCanvasSupported:function(){var n=m1n.b8.a8("5d")?0x85ebca6b:document[X5]('canvas');return !!(n[V]&&n[V]('2d'));},isIE:function(){var n="test",X="c5",O="appName",T=m1n.b8.a8("4d57")?"N5":"top";if(m1n[T](navigator[O],'Microsoft Internet Explorer')){return true;}else if(m1n[X](navigator[O],'Netscape')&&/Trident/[n](navigator[O5])){return true;}return false;},getPluginsString:function(){var n="getRegularPluginsString",X="getIEPluginsString",O=m1n.b8.a8("5f")?"hasher":"isIE";if(this[O]()&&this[Q]){return this[X]();}else{return this[n]();}},getRegularPluginsString:function(){var H="plugins";return this[E](navigator[H],function(T){var U="description",S="name",B=this[E](T,function(n){var X="suffixes";var O=m1n.b8.a8("ac8")?"screen":"type";return [n[O],n[X]][i]('~');})[i](',');return [T[S],T[U],B][i]('::');},this)[i](';');},getIEPluginsString:function(){var O="ActiveXObject";if(window[O]){var T=['ShockwaveFlash.ShockwaveFlash','AcroPDF.PDF','PDF.PdfCtrl','QuickTime.QuickTime','rmocx.RealPlayer G2 Control','rmocx.RealPlayer G2 Control.1','RealPlayer.RealPlayer(tm) ActiveX Control (32-bit)','RealVideo.RealVideo(tm) ActiveX Control (32-bit)','RealPlayer','SWCtl.SWCtl','WMPlayer.OCX','AgControl.AgControl','Skype.Detection'];return this[E](T,function(X){try{new ActiveXObject(X);return X;}catch(n){return null;}})[i](';');}else{return "";}},getScreenResolution:function(){var n="L5",X;if(this[c]){X=(m1n[n](screen.height,screen.width))?[screen.height,screen.width]:[screen.width,screen.height];}else{X=[screen.height,screen.width];}return X;},getCanvasFingerprint:function(){var n="toDataURL",X=document[X5]('canvas'),O=X[V]('2d'),T='http://valve.github.io';O.textBaseline="top";O.font="14px 'Arial'";O.textBaseline="alphabetic";O.fillStyle="#f60";O.fillRect(125,1,62,20);O.fillStyle="#069";O.fillText(T,2,15);O.fillStyle="rgba(102, 204, 0, 0.7)";O.fillText(T,4,17);return X[n]();}}:"";return d;});```

when the file syntax highlight is set to Javascript

**Comment by Zireael07** [comment] 2017-02-17 12:49
That line looks very long, in that case it's a duplicate of #979. 

Good news is, there's a fix merged that fixes it.

Bad news, the new version with it isn't out yet.

**Comment by 50Wliu** [comment] 2017-02-17 18:04
Closing as a duplicate of #979; will be fixed in Atom 1.16.0.

**Closed by 50Wliu** 2017-02-17 18:04 UTC
Labels: more-information-needed

**Comment by edmarbarros** [comment] 2017-02-17 18:50
@50Wliu 
The line size is less than less than 9000 characters and it only occurs when the syntax highlight is javascript.

I am able to open the file and manipulate it if the syntax is not javascript.

It doesn't seems to be related to #979

**Comment by 50Wliu** [comment] 2017-02-17 21:16
Yes, syntax highlighting is part of the problem.  It's very related to #979 because the line in question is extremely long; it doesn't necessarily have to be 9000 characters.

Please try Atom 1.15.0-beta3 to see if your issue has been resolved.
