### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by ekifakhrureza** [atom/atom#17022] opened 2018-03-24 09:01 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At /snap/atom/136/usr/share/atom/resources/app/src/text-editor-component.js:2280

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/snap/atom/136/usr/share/atom/resources/app/src/text-editor-component.js:2269:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/snap/atom/136/usr/share/atom/resources/app/src/text-editor-component.js:2262:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/snap/atom/136/usr/share/atom/resources/app/src/text-editor-component.js:401:16)
    at scheduler.readDocument (/snap/atom/136/usr/share/atom/resources/app/src/text-editor-component.js:279:20)
    at ViewRegistry.performDocumentUpdate (/snap/atom/136/usr/share/atom/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -2:18.8.0 core:paste (input.hidden-input)
     -2:18.4.0 core:save (input.hidden-input)
     -2:16.6.0 core:backspace (input.hidden-input)
  2x -2:16.3.0 core:save (input.hidden-input)
  6x -2:11 core:move-left (input.hidden-input)
     -2:09.1.0 core:save (input.hidden-input)
 13x -1:46.7.0 core:move-down (input.hidden-input)
  7x -1:35.9.0 core:backspace (input.hidden-input)
     -1:22.8.0 core:save (input.hidden-input)
  6x -1:15.7.0 core:backspace (input.hidden-input)
     -1:13.5.0 core:save (input.hidden-input)
  5x -0:57.3.0 core:backspace (input.hidden-input)
     -0:55.8.0 core:undo (input.hidden-input)
     -0:51.8.0 editor:newline (input.hidden-input)
     -0:50.2.0 core:move-left (input.hidden-input)
  7x -0:48.9.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-runner 2.7.1 
```

**Comment by rsese** [comment] 2018-03-26 17:23
Thanks for the report! Looks like this is a duplicate of #15263 and the fix I believe is in 1.26, currently in beta. If you still see this error when you're on 1.26 please let us know.

**Closed by rsese** 2018-03-26 17:23 UTC
