### ISSUE TITLE
Multiple selections loosing context

### ISSUE THREAD

**Issue by muchweb** [atom/atom#3107] opened 2014-07-28 17:59 UTC
Example:

1. Select text `aa`
![1](https://cloud.githubusercontent.com/assets/7157049/3724616/fefd8dcc-167f-11e4-82fc-b8e3aeff987a.png)

2. Press `ctrl+d` for next selection
![2](https://cloud.githubusercontent.com/assets/7157049/3724614/fefcd8fa-167f-11e4-9e0a-6d44a51450c5.png)

3. Press `ctrl+d` for next selection
![3](https://cloud.githubusercontent.com/assets/7157049/3724615/fefcfc5e-167f-11e4-954a-5b232ca901f9.png)

4. I expect editor to select next occurrence of text on `ctrl+d`, but initial search string is now lost.

**Comment by izuzak** [comment] 2015-09-14 20:32
I can no longer reproduce this. Here's what I'm seeing on the latest master version (keybinding resolver is visible so that it's clear which keys I'm pressing):

![select](https://cloud.githubusercontent.com/assets/38924/9861052/4eccf81a-5b30-11e5-93df-cb704c4c9eb7.gif)

Since that matches the expected behavior described in https://github.com/atom/atom/issues/3107#issuecomment-50500663 -- I'm closing this issue. 

@muchweb If you can still reproduce this in Atom 1.0.11 -- would be great to have a new example and a GIF which demonstrates the problem.

**Closed by izuzak** 2015-09-14 20:32 UTC
Labels: bug
