### ISSUE TITLE
Arabic mis-selection text

### ISSUE THREAD

**Issue by elshahat** [atom/atom#10729] opened 2016-02-08 11:37 UTC
I'll try to explain the issue exactly step by step:

First I wrote this text:
بسم الله الرحمن الرحيم
![atom1](https://cloud.githubusercontent.com/assets/12900700/12884689/9e01ae7a-ce68-11e5-81a6-8c5c62a625c2.jpg)

The full text characters including spaces are: 22 characters

Then I selected the first three words and their characters count including spaces are: 15
![atom2](https://cloud.githubusercontent.com/assets/12900700/12884696/aac9093c-ce68-11e5-8d54-d1fd0790203c.jpg)

Then I cut this selected text (ctrl+x) so the latest word that should still appear is ( الرحيم) including it's space and the characters count  should be: 7
The issue is that the cut text is not what I selected and my selection is reversed, the first 7 characters are the characters that appear not the last 7 characters.
![atom3](https://cloud.githubusercontent.com/assets/12900700/12884703/b552fbce-ce68-11e5-8625-dbbfb70944e9.jpg)

That's the issue with Arabic language which I face now. My current version is: 1.4.2

When I use Arabic text in my code I use Brackets as it handle Arabic language accurately.

I hope to solve this issue soon.

**Comment by lee-dohm** [comment] 2016-02-09 06:46
I'm pretty certain this is a duplicate of https://github.com/atom/atom/issues/10132. You may want to subscribe there for updates.

Please let me know if I'm mistaken and feel free to add your repro information to that Issue.

**Closed by lee-dohm** 2016-02-09 06:46 UTC
