### ISSUE TITLE
Blurry text on Windows 10

### ISSUE THREAD

**Issue by in-dex** [atom/atom#13341] opened 2016-11-27 23:20 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Hello, I'm having issues with font rendering on Windows 10 since a while now. I've already tried to fix it with CSS and adjust the ClearType text, but nothing happened. My screen resolution is `1366x768`. 

When I click somewhere on the screen, the font goes back to normal for a few seconds, then slowly blurs back again (as you can see below). It would be nice to fix this, I'm sticking to Sublime Text until I find a solution. Thanks in advance.

![blurry](https://cloud.githubusercontent.com/assets/17071218/20652572/de127754-b4e2-11e6-8e28-a0179501d272.png)
![blurry](https://cloud.githubusercontent.com/assets/17071218/20652768/27dc0aa4-b4e7-11e6-90b5-5f42c3059e15.gif)

### Steps to Reproduce

1. When opening Atom
2. When typing something

**Expected behavior:** The font should be sharp as below (print from Sublime Text):
![image](https://cloud.githubusercontent.com/assets/17071218/20652681/e2492550-b4e4-11e6-8626-fd56ef45db89.png)
**Actual behavior:** Everything looks blurry.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
`apm  1.12.9`

**Comment by shiftkey** [comment] 2016-11-28 02:06
@in-dex could you also launch Command Prompt and see what build of Windows 10 you're running?

<img width="422" src="https://cloud.githubusercontent.com/assets/359239/20654239/6eadb142-b56b-11e6-9c01-52743240d6ec.png">

**Comment by damieng** [comment] 2016-11-28 03:00
Also what graphics chip and driver you are using and whether you get any odd font issues in Chrome.

**Comment by in-dex** [comment] 2016-11-28 08:27
@shiftkey 
![image](https://cloud.githubusercontent.com/assets/17071218/20661018/91b1ca26-b533-11e6-8311-629fc124eed8.png)

**Comment by 50Wliu** [comment] 2016-11-28 20:22
I believe this is a duplicate of #12652, no?

**Comment by damieng** [comment] 2016-11-28 21:03
I don't think it is - the other one is losing subpixel AA. This one appears to be more of a bad transform happening and somehow 'eroding' the text.

**Comment by damieng** [comment] 2016-11-28 21:05
I personally suspect it's a bad video driver or a graphics profile setting intended for games getting applied to Atom by mistake.

**Comment by damieng** [comment] 2016-11-28 21:45
Not able to repro with stock Atom 1.12.6 on the closest machine I have - Intel HD Graphics 520 with drivers 20.19.15.4463

**Comment by damieng** [comment] 2016-11-28 21:49
Can you include a screenshot of the blurry text while running `atom --safe` ?

**Comment by in-dex** [comment] 2016-11-28 22:35
@damieng I finally fixed it! You were right, the problem was the sharpness settings on the Intel Graphics Panel (even though I never opened it), it also fixed the same problem on Visual Studio Code and Visual Studio 2016. 
![image](https://cloud.githubusercontent.com/assets/17071218/20688944/2c5c7f96-b5aa-11e6-8d11-f1f0fa3004cd.png)

**Comment by damieng** [comment] 2016-11-28 22:39
Thanks for figuring that out - I'm sure this thread will be useful to other people too running into this. Not many apps take advantage of HW accelerated rendering yet so I'm sure Intel have some work to do in figuring out when to turn this on (although in my mind that would be never ;-) )

**Closed by damieng** 2016-11-28 22:39 UTC
Labels: editor-rendering, typography, windows

**Comment by amitkvmz** [comment] 2017-12-06 09:24
@c0imbra  I can't find any sharpness settings in Intel HD graphics panel.  can you please tell me where can I find this option.

**Comment by JW0914** [comment] 2018-06-02 14:19
The issue for most, if not all, is with the graphics card options software, which also explains why this only occurs on Windows and not Linux.  

I was able to fix this by setting the following:
- **_Intel HD Graphics Control Panel_**
   - **3D:**
      - **Application Optimal Mode:** _Disable_
      - **Multi-Sample Anti-Aliasing:** _Disable_
