### ISSUE TITLE
Trying to click a file seemingly clicks the one below it

### ISSUE THREAD

**Issue by atomiks** [atom/atom#17545] opened 2018-06-20 23:31 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I first noticed this in either 1.27.0 or the version right before it.

Trying to click the previous file in the list seemingly clicks the one below it despite the cursor being right on it.

Link: https://gfycat.com/ClutteredInfatuatedGossamerwingedbutterfly

(happens at 0:05 -- trying to click `tippy.js` from `tippy.min.js`

### Steps to Reproduce

1. Open a project
2. Click/open a file
3. Try to click/open a file directly above it

**Expected behavior:** The correct file should be clicked

**Actual behavior:** The file directly below is clicked

**Reproduces how often:** Seems kind of random

### Versions

Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python 2.7.10
git 2.10.1

macOS 10.13.4

**Comment by rsese** [comment] 2018-06-21 00:14
Thanks for contributing!

I believe this is a duplicate of https://github.com/atom/one-dark-ui/issues/257 which is [fixed](https://github.com/atom/one-light-ui/pull/133) as of 1.28 (currently in beta).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

https://github.com/atom/one-light-ui/pull/133

**Closed by rsese** 2018-06-21 00:14 UTC
