### ISSUE TITLE
Atom crashes after loading 30 MB text file

### ISSUE THREAD

**Issue by luki96** [atom/atom#10969] opened 2016-02-25 12:33 UTC
[Short description of problem here]

**Reproduction Steps:**

1. I have started atom from start menu
2. It were few files opened
3. I have drag text file (size a bit over 30 MB) and drop it to atom
4. Atom had loaded this file and then after few minutes it has crashed. I didn't do anything with the file which had been loaded

**Expected behavior:**

Atom should not crash and should allow to work on this file

**Observed behavior:**

Simply it crashed

**Screenshots and GIFs**

Screenshot
![atom-crash](https://cloud.githubusercontent.com/assets/4086823/13319317/2dd10414-dbc1-11e5-9aad-88c83651e3ee.png)

**Atom version:** 1.5.3
**OS and version:**
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

**Installed packages:**

I didn't have install any new package. I have only default 77 core packages.

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Atom: I don't know that other versions have this issue because version 1.5.3 is my first version of Atom
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

Config file

> "*":
  core:
    themes: [
      "atom-dark-ui"
      "atom-dark-syntax"
    ]
  editor:
    invisibles: {}
  "exception-reporting":
    userId: "7017a4d7-bd38-cb69-512c-20dee9b90c88"
  welcome:
    showOnStartup: false

**Comment by Zireael07** [comment] 2016-02-25 12:46
Duplicate of existing issues. Atom doesn't work well with files over 2 MB.

**Comment by 50Wliu** [comment] 2016-02-25 17:52
Closing as a duplicate of #9825.

**Closed by 50Wliu** 2016-02-25 17:52 UTC
