### ISSUE TITLE
Bug Alt+] AZERTY(FR) keyboard 

### ISSUE THREAD

**Issue by xonlly** [atom/atom#6034] opened 2015-03-19 15:34 UTC
Hello,

Alt + ] or AltGr + ] not working in AZERTY(FR) keyboard please fix or help :'(.

Thanks ! ;)

**Comment by 50Wliu** [comment] 2015-03-19 15:36
Duplicate of atom/atom-keymap#35, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-19 15:36 UTC
