### ISSUE TITLE
Static Launcher (File Association)

### ISSUE THREAD

**Issue by karai17** [atom/atom#5205] opened 2015-01-22 06:45 UTC
I have a strong habit of opening files from Windows Explorer. My prefered method is to double-click the file. Herein lies the issue: Atom is not only hidden in %appdata% where it can be difficult to find, but there is no static file to associate to since atom.exe is in a versioned directory.

My suggestion is to create a very basic launcher that opens the latest version of Atom installed so that users can associate files to Atom without needing to update associations every update.

**Comment by LPGhatguy** [comment] 2015-01-22 07:27
This is a feature I would also like as a Windows user. Sublime Text, like Atom, adds a context menu association, but it can also be associated with a filetype.

**Comment by mnquintana** [comment] 2015-08-23 12:05
This looks like a duplicate of https://github.com/atom/atom/issues/4893 – closing in favor of that issue.

**Closed by mnquintana** 2015-08-23 12:05 UTC
