### ISSUE TITLE
Node 7 support

### ISSUE THREAD

**Issue by mpkh** [atom/atom#13173] opened 2016-11-10 07:07 UTC
I package gentoo ebuild (build script) for myself

currently I set < node7 as rule due build errors: is there some information whether it's unsupported officially and is there plan for node7 support

thank you

**Comment by Ben3eeE** [comment] 2016-11-10 07:32
This sounds like a duplicate of https://github.com/atom/apm/issues/636. If you want to test out the PR that is open for fixing this that would be appreciated.

**Closed by Ben3eeE** 2016-11-10 07:32 UTC
