### ISSUE TITLE
Cannot display Chinese in ubuntu

### ISSUE THREAD

**Issue by arthurtalkgoal** [atom/atom#6544] opened 2015-04-28 02:02 UTC
Hi,

My Ubuntu 14.04 Atom cannot display Chinese (utf-8 files), but a series of strange square boxes. I tried to update the font to 細明體 but in ruin. 

Here is the output－
![screenshot from 2015-04-28 10 01 27](https://cloud.githubusercontent.com/assets/7088330/7361591/cc5969fa-ed8d-11e4-8116-72aa107c29ca.png)

**Comment by 50Wliu** [comment] 2015-04-28 02:15
Duplicate of #6214, please subscribe there for updates and possible workarounds.

**Closed by 50Wliu** 2015-04-28 02:15 UTC
