### ISSUE TITLE
After removing second monitor Atom can become unusable

### ISSUE THREAD

**Issue by sergey-shambir** [atom/atom#9478] opened 2015-11-07 07:20 UTC
Bug appears on Windows
1. Move Atom window to second monitor and maximize it
2. Close Atom
3. Remove second monitor
4. Open Atom
Result: Atom spawns outside of 1st monitor and cannot be moved inside. In other words, Atom becomes unusable; deleting data in %APPDATA% doesn't help.

**Comment by Zireael07** [comment] 2015-11-07 07:40
Solution:



I just found a solution to my problem. The atom window was rendered outside any screen coordinates. I did the following steps to solve it:

    Alt + Tab to choose the atom window
    Alt + Space to open the context menu
    Press 'm' to select move
    Press any arrow key once
    Move your mouse (The misplaced window will follow your cursor.)
    Open a new file or project and close it again to save the new window state.


Also I'm 100% certain there's already an issue for that, but can't find it atm.

**Comment by 50Wliu** [comment] 2016-05-25 16:10
This is a duplicate of #6939 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-25 16:10 UTC
