### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by NathanRSmith** [atom/atom#17047] opened 2018-03-29 14:42 UTC
Encountered error while editing a ReStructuredText file (rst). Doesn't seem to matter what I type.

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527

TypeError: Cannot read property 'replace' of undefined
    at AutocompleteManager.getWordCharacterRegex (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527:72)
    at AutocompleteManager.getPrefix (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:507:43)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:260:31)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1748:32)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:975:18)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1386:25)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3249:53)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3223:42)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1385:23)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1349:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1654:30)
```

### Commands

```
     -0:29.8.0 intentions:highlight (input.hidden-input)
     -0:29.7.0 pane:show-next-item (input.hidden-input)
     -0:27.9.0 core:close (div.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
change-case 0.6.5 
cucumber 0.6.0 
git-plus 7.10.2 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-diff 0.7.0 
language-docker 1.1.8 
language-FBP 0.1.0 
language-graphql 0.9.0 
language-hql 4.1.0 
language-json5 1.1.1 
language-restructuredtext 1.1.0 
language-scala 1.1.9 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
pig 1.0.0 
pretty-json 2.0.0 
snippet-generator 0.3.2 
sort-lines 0.18.0 
split-diff 1.5.2 
```

**Comment by rsese** [comment] 2018-03-29 17:51
Thanks for the report - can you reproduce in safe mode (`atom --safe`)?

**Comment by NathanRSmith** [comment] 2018-03-29 18:01
Yes, it does occur in safe mode as well.

**Comment by rsese** [comment] 2018-03-29 23:17
Hmm, I'm unable to reproduce on macOS 10.12.6 with Atom 1.25.0.  

Can you try a couple of the other recommended debugging steps like clearing saved state (save any unsaved work first):

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

And if that doesn't help, temporarily resetting to factory defaults?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by NathanRSmith** [comment] 2018-03-30 20:15
Clearing save state did not fix it, but resetting did. Of relevance is that I recently upgraded from El Capitan to High Sierra.

This issue is resolved for me personally. Unsure of what the root cause was.

**Comment by Arcanemagus** [comment] 2018-03-30 20:18
Thanks for taking the time to contribute!

I'm guessing that in your old configuration you had added `_` to your list of Non-word characters. From the stack trace this is a duplicate of https://github.com/atom/autocomplete-plus/issues/956. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-30 20:18 UTC
Labels: more-information-needed, uncaught-exception

**Comment by NathanRSmith** [comment] 2018-03-30 20:25
I did indeed have `_` in my non-word characters. Adding it back causes the error to occur and removing again "fixes" it.
