### ISSUE TITLE
Unable to watch path

### ISSUE THREAD

**Issue by Enkouyami** [atom/atom#5758] opened 2015-02-26 06:43 UTC
When I opened atom, I got these errors:

> Unable to watch path: config.cson. Make sure you have permissions to /home/ely/.atom/config.cson.

> Unable to watch path: keymap.cson. Make sure you have permission to read /home/ely/.atom/keymap.cson.

> Unable to watch path: styles.less. Make sure you have permissions to /home/ely/.atom/styles.less.

> Unable to watch path: snippets.cson. Make sure you have permissions to the ~/.atom directory and /home/ely/.atom/snippets.cson.

**Atom Version**: 0.184.0
**System**: linux 3.13.0-37-generic
**OS**: Linux Mint 17.1 Cinnamon 64-bit

I installed atom via the deb from [the main site](https://atom.io/). I previously had v0.182.0 installed, then tried to purged it and the configuration files from my system using `sudo apt-get purge atom` before getting the newer version, but the "/home/ely/.atom" folder was still there, so I don't know if there's also problem with my package manager.

**Comment by Enkouyami** [comment] 2015-02-26 07:08
Is there a problem with my package manager or atom?

**Comment by steelbrain** [comment] 2015-02-26 07:12
@Enkouyami Can you please post the output of `ls -lah /home/ely/.atom`

**Comment by Enkouyami** [comment] 2015-02-26 07:18
Here's the output:
> ls -lah /home/ely/.atom
> total 44K
> drwxr-xr-x  5 ely ely 4.0K Feb 26 02:13 .
> drwxr-xr-x 30 ely ely 4.0K Feb 26 02:12 ..
> drwxr-xr-x  2 ely ely 4.0K Feb 26 02:13 .apm
> drwxr-xr-x  4 ely ely 4.0K Feb 26 02:12 compile-cache
> -rw-r--r--  1 ely ely   95 Feb 26 02:13 config.cson
> -rw-r--r--  1 ely ely   41 Feb 26 02:13 .gitignore
> -rw-r--r--  1 ely ely  386 Feb 26 02:13 init.coffee
> -rw-r--r--  1 ely ely  861 Feb 26 02:13 keymap.cson
> drwxr-xr-x  2 ely ely 4.0K Feb 26 02:13 packages
> -rw-r--r--  1 ely ely  582 Feb 26 02:13 snippets.cson
> -rw-r--r--  1 ely ely  486 Feb 26 02:13 styles.less

**Comment by Enkouyami** [comment] 2015-02-26 19:30
What other information can I add?

**Comment by Enkouyami** [comment] 2015-02-26 19:55
The @curtiszimmerman 6th comment on issue #5121 fixed the problem.

**Comment by Moter8** [comment] 2015-02-27 22:03
@Enkouyami The one about running atom as superuser? That is not a fix, obviously.

**Comment by curtiszimmerman** [comment] 2015-02-27 23:04
@Moter8 Uhh, I'm not sure where you get "run as superuser" idea. The one he references -- and the one I mentioned -- is about increasing fs.inotify.max_user_watches from 8k to 32k.

**Comment by Moter8** [comment] 2015-02-27 23:08
That's not really the 6th comment :P

Nevermind this.

**Comment by Enkouyami** [comment] 2015-03-02 06:32
@Moter8 I said the sixth occurrence of when curtiszimmerman commented on that issue.

**Comment by albertJ32** [comment] 2015-07-08 16:10
i've just started having the same problem, did you ever find a solution to this?

**Comment by Enkouyami** [comment] 2015-07-14 00:37
@albertJ32 *read* the the sixth occurrence of when curtiszimmerman commented on issue #5121.

**Comment by kevinsawicki** [comment] 2015-07-21 18:00
Closing as duplicate of https://github.com/atom/atom/issues/5121

**Closed by kevinsawicki** 2015-07-21 18:00 UTC
Labels: more-information-needed

**Comment by Meeyan** [comment] 2016-12-09 07:27
os:linux mint 18
I got this problem also.I solved this by follow steps:
first ,  close atom and then make sure that the logging user own the  directory   `.atom` , if not ,try `chown` or `rm`,i used rm;
sec , delete file `config.json` then reopen atom. and everything goes well.
but, the operation `rm` will empty all your settings for atom , just be careful...

**Comment by fredericgermain** [comment] 2017-03-18 15:14
os: fedora 25
I had the same problem, fixed with the fs.inotify.max_user_watches sysctl hack...

When I run strace without the hack, I have an error from the first call to inotify_* functions.
It doesn't look to me like an error on the number of watches, more like an error on how linux treat all the flags in inotify_add_watch...

[pid 14157] inotify_init1(IN_CLOEXEC)   = 27
[pid 14157] inotify_add_watch(27, "/home/fred/.config/ibus/bus", IN_MODIFY|IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF|IN_UNMOUNT|IN_ONLYDIR <unfinished ...>
[pid 14157] <... inotify_add_watch resumed> ) = -1 ENOSPC (No space left on device)

**Comment by mverissimo** [comment] 2018-03-19 16:27
This worked for me on fedora 27:

echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system

https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
