### ISSUE TITLE
Character positioning/cursor movement breaks with certain emoji characters

### ISSUE THREAD

**Issue by postcasio** [atom/atom#6307] opened 2015-04-08 16:17 UTC
Atom 0.190.0, OS X 10.10
Enter some random emoji, such as :ocean::eyes::relieved:, then add :m: to the end, the preceding characters move and overlap and the cursor position gets weird.

![emoji](https://cloud.githubusercontent.com/assets/1759837/7049599/9f3f513a-de12-11e4-842e-76ea1a04206e.gif)

Seems to only happen with :m:, but I haven't tried everything.

I think it's something to do with variation selectors. When you enter :m: using the OS X emoji palette, it encodes as `e2 93 82 ef b8 8f`, or `CIRCLED LATIN CAPITAL LETTER M` followed by `VARIATION SELECTOR 16`. If you copy and paste just `CIRCLED LATIN CAPITAL LETTER M` it works fine.

**Comment by as-cii** [comment] 2015-04-09 13:46
@postcasio: I have tried to reproduce it outside Atom through this HTML file.

```html
<html><body>Ⓜ️👊🌊🇮🇹</body></html>
```

It turns out that emojis are displayed nicely on Safari, whereas they get messed up on Chrome 41.

| Safari          | Chrome          |
| :-------------: | :-------------: |
| ![screen shot 2015-04-09 at 15 35 48](https://cloud.githubusercontent.com/assets/482957/7067797/4724d38c-dece-11e4-85b0-249d591f6182.png)      | ![screen shot 2015-04-09 at 15 34 25](https://cloud.githubusercontent.com/assets/482957/7067755/126f0c2a-dece-11e4-9bf8-32fabe392629.png)

Our character measurement/positioning system contributes to make things worse, but that's not the cause and, although we need to address it soon anyway, I think this is something that must be fixed at a lower layer (https://code.google.com/p/chromium/issues/detail?id=473703).

Maybe we should move this issue elsewhere? :thought_balloon: 

/cc: @kevinsawicki @nathansobo

**Comment by benogle** [comment] 2015-10-26 23:11
This is fixed on master via #8811

**Closed by benogle** 2015-10-26 23:11 UTC
Labels: bug, editor-rendering
