### ISSUE TITLE
Configuration option for text-rendering: optimizeLegibility

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#9082] opened 2015-10-08 09:45 UTC
Implement a configuration option for `text-rendering: optimizeLegibility` as that is required for ligatures to work. See https://github.com/atom/atom/issues/3821#issuecomment-146474764

**Comment by kennethormandy** [comment] 2015-10-12 08:57
If this is added as an option, it should be done  with `font-feature-settings`, rather than `text-rendering: optimizeLegibility`. Some of the coding fonts with OpenType features are using contextual alternates, [per this article](https://medium.com/@larsenwork/ligatures-coding-fonts-5375ab47ef8e), which means the setting should at least enable:

```css
.feature-enabled {
  font-feature-settings: "liga" 1, "calt" 1;
}
```

Contextual alternates and ligatures are both supposed to be on by default anyway, per the OpenType spec, but isn’t being consistently followed. A more thorough, forward-looking version would be:

```
.feature-enabled {
  @supports not (font-variant-ligatures: common-ligatures) {
    font-feature-settings: "liga" 1;
  }
  @supports not (font-variant-ligatures: contextual) {
    font-feature-settings: "calt" 1;
  }
  font-variant-ligatures: common-ligatures;
  font-variant-ligatures: contextual;
}
```

Another approach would be to include this by default, as the majority of monospaced fonts will not include OpenType features, and the ones that do should be making the less widely applicable ligatures `dlig` discretionary ligatures.

**Comment by ebraminio** [comment] 2015-11-25 07:02
Just want to let you know optimizeLegibility will be default behaviour on Chrome 49 so some font-feature-settings setting will probably what you want if the feature is not enabled by default (which most features fonts need, like `liga`, are)

**Comment by alexandernst** [comment] 2015-11-25 18:31
@ebraminio Does that mean that ligatures will work by default in Atom when Atom is upgraded to Chrome 49? I feel like there is something missing in your statement and I can't fully understand what you wanted to say.

**Comment by ebraminio** [comment] 2015-11-25 18:54
Yes. In fact there was two code path for handling text shaping, the one that was called simple and wasn't able to make ligatures happen and the other one which was called complex (webdevs know that as being triggered by optimizeLegibility) which uses a third party library for shaping and is able to do all needed font features request if they are enabled by default. These code paths now are merged and actually it is just got became to be like Firefox.

**Comment by alexandernst** [comment] 2015-11-25 18:57
Cool :D 
Do you happen to know when will be electron upgraded to Chrome 49?

**Comment by ebraminio** [comment] 2015-11-25 19:00
Yes. Of course if nothing unpredicted happens in between.

**Comment by alexandernst** [comment] 2015-11-25 19:01
I was asking for *when*, not *if* it's going to be upgraded.

**Comment by ebraminio** [comment] 2015-11-25 19:04
Oh sorry, well that also depends, I am not an electron team member :) But I guess electron will be updated to Chrome 49 sometime after it become stable which would be couple of weeks I'd guess.

**Comment by 50Wliu** [comment] 2015-11-25 19:25
> Do you happen to know when will be electron upgraded to Chrome 49?

It all depends on how much needs to be changed, especially within Atom.  I'd guess that switching the default text rendering path will break a lot of tests.

**Comment by alexandernst** [comment] 2015-11-25 19:28
@50Wliu I'm confused. Wasn't Atom 1.1 supposed to `fix` ligatures? (which btw aren't enabled by default even that we're almost at Atom 1.3 now). Why would enabling ligatures by default break unit tests if the entire point of Atom 1.1 was to fix ligatures in the first place?

**Comment by 50Wliu** [comment] 2015-11-25 19:33
> Why would enabling ligatures by default break unit tests if the entire point of Atom 1.1 was to fix ligatures in the first place?

Subtle differences in character widths and spacing, etc.  It's happened before with subpixel font scaling.  I'm not familiar with this part of Atom though so I could be totally wrong.  We'll see when the initial PR is created :).

**Comment by alexandernst** [comment] 2015-11-25 19:36
Maybe @as-cii can enlighten us?

**Comment by ebraminio** [comment] 2015-11-25 19:36
> I'd guess that switching the default text rendering path will break a lot of tests.
It did on Chrome so probably would do here also but if you have updated enough version of Chrome, you can do apply optimizeLegibility before hand and remove it after the migration so that would make the change smoother.

**Comment by as-cii** [comment] 2015-11-25 20:13
Personally, I don't think unit tests are much of a deal-breaker here. However, I'd prefer the `optimizeLegibility` setting to be opt-in (at least for the time being) because that styling is known to affect **Layout** times and it becomes increasingly noticeable when there are lots of text runs (such as within a text editor).

An opt-in configuration setting would make most sense to me, although hacking the personal stylesheet seems almost as straightforward (I guess this is the reason why it wasn't implemented yet).

**Comment by ebraminio** [comment] 2015-11-25 20:34
Known layout time defects are mostly gone on the recent versions with CachingWordShaper, the technique which is also incorporated on Firefox. I suggest if you have Chrome 46 in, give it a try. And if you have runed into performance regress that also is available on 49, report that to Chrome project.

**Comment by as-cii** [comment] 2015-11-25 20:40
That's great to hear, @ebraminio. Electron currently runs on top of Chrome 45 and I think my benchmarks were based on that version or the immediately previous one. I am :ok: to enable this by default as soon as we upgrade to a more recent major version of Chrome and test performance out once again. :chart_with_upwards_trend:

**Comment by ebraminio** [comment] 2015-11-25 20:49
Oh that would great. Actually 45 is also good but its complex tab is unable to handle tabs. If you are handling tabs by your own that would be no issue, but I am not sure how Atom works.

**Comment by ebraminio** [comment] 2015-11-25 20:54
And oh 45 performance is bad when white-space: pre is enabled but it is fixed on 46. Still not sure if you using it but 46 probably would be safer for test.

**Comment by as-cii** [comment] 2015-11-26 10:11
Yeah, I just tried to perform some benchmarks on this version and indeed we have a performance regression if we turn on `optimizeLegibility` (I guess because we use `white-space: pre`). I'll be more than happy to come back to this once Chrome solves these slowdowns in the next versions. :tada: :racehorse:

**Comment by ebraminio** [comment] 2016-03-06 21:16
Time has passed and Chrome 49 which is always "optimizeLegibility" has become stable Chrome release now, I guess all bugs with mention of "optimizeLegibility" could be closed after the migration on Atom also.

**Comment by ebraminio** [comment] 2016-03-17 10:03
Well, it seems still some differences is available, asked on https://bugs.chromium.org/p/chromium/issues/detail?id=404597#c70

**Comment by 50Wliu** [comment] 2016-03-17 12:52
Labeling as blocked until Atom upgrades to Electron 0.37.

**Comment by ebraminio** [comment] 2016-05-31 13:10
This should be closed as the upgrade to Chrome 49 on Electron 0.37 which atom uses now.

**Comment by 50Wliu** [comment] 2016-05-31 13:21
Thanks for the update @ebraminio!

**Closed by 50Wliu** 2016-05-31 13:21 UTC
Labels: enhancement
