### ISSUE TITLE
Altgr (ctrl-alt) doesn’t work correctly on Linux

### ISSUE THREAD

**Issue by phaazon** [atom/atom#7535] opened 2015-06-29 08:52 UTC
I’m using a [bépo](http://bepo.fr/wiki/Accueil) keyboard layout. On Windows, when hitting *AltGr*, I get it translated to `ctrl-alt`. On Linux, I get it translated to… `á`, which is very weird and wrong.

**Comment by mnquintana** [comment] 2015-06-29 10:47
This is a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-29 10:47 UTC

**Comment by phaazon** [comment] 2015-06-29 11:06
Thanks.
