### ISSUE TITLE
Uncaught Error: Cannot find module '../node_modules/atom-keymap/lib/command-event.js'

### ISSUE THREAD

**Issue by Guilhermelvs** [atom/atom#15593] opened 2017-09-08 15:13 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 ia32
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module '../node_modules/atom-keymap/lib/command-event.js'

```
At module.js:472

Error: Cannot find module '../node_modules/atom-keymap/lib/command-event.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.7/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.7/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.19.7/resources/app/static/<embedded>:96:26)
    at get_CommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:22:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:607:38)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.7/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.7/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.7/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:30.9.0 core:save (input.hidden-input)
     -0:16.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-material-ui 2.0.4 
emmet 2.4.3 
language-blade 0.30.0 
laravel 0.7.1 
```

**Comment by rsese** [comment] 2017-09-08 17:34
We've seen a handful of similar errors and I'll close as a duplicate of https://github.com/atom/atom/issues/14461.  Can you try reinstalling and let us know if you still get the error?

**Closed by rsese** 2017-09-08 17:34 UTC
Labels: duplicate

**Comment by joaonetto** [comment] 2017-10-07 20:18
Interesting. This erros happen after i include .gitignore in my project. After this file with exclude <APP>/node_modules the Atom start this errors.

I re-install my Atom and they working fine right now.
