### ISSUE TITLE
Periodically have to reset Exclude VCS Ignored Paths

### ISSUE THREAD

**Issue by ericyoung** [atom/atom#6104] opened 2015-03-25 23:27 UTC
Pretty regularly, when I create a file in a project, ctrl-p won't reveal the new file in results unless I drill into Preferences, check, and then uncheck, Exclude VCS Ignored Paths. After that, the new file shows up as expected.

**Comment by lee-dohm** [comment] 2015-03-26 17:57
Seems like this is a duplicate of atom/fuzzy-finder#30. Do you agree?

**Comment by ericyoung** [comment] 2015-03-26 20:59
Probably so. In my case, I'm adding the file, not via touch (which might understandably fall outside the immediate knowledge of atom), but from the file menu within atom. I haven't tried moving away and then back to force a refresh. I hesitate to call this a bug, since it may be something that falls outside atom's capacity to refresh folders (chromeos editors like zed and caret seem to require a manual refresh in order to pick up new files).

**Comment by lee-dohm** [comment] 2015-03-26 21:16
Ok, if you can add your details and repro steps to that bug, I think it would be a great help. Also, could you give the following information on that bug?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

I'm going to close this as a duplicate but let us know if there's anything else we can answer! Also, don't forget to subscribe to that issue to be notified of any changes.

**Closed by lee-dohm** 2015-03-26 21:16 UTC

**Comment by ericyoung** [comment] 2015-03-26 22:39
1. open a project folder
2. File > New File (provide name + save)
3. ctrl+p + start typing file name (never found)
4. Edit > Preferences
5. Since I already have Exclude VCS Ignored Path unchecked, I check it, then uncheck it
6. ctrl+p + start typing file name (found)

Atom version: 0.187.0
OS: Ubuntu 14.10 chroot (ChromeOS)
Device: Chromebook Pixel 2015

--safe doesn't resolve the issue for me

If others aren't experiencing the same issue, then perhaps it's just a limitation of developing in a crouton + ChromeOS environment.
