### ISSUE TITLE
Atom on Mac crashes when opening a 20MB plain text file

### ISSUE THREAD

**Issue by nmaxcom** [atom/atom#13105] opened 2016-10-30 13:36 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
Yes

* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
Yes (1.11.2)

* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
Yup

* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
No, I'm investing enough.

* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
Yes

* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
Yes

### Steps to Reproduce

I open the folder that contains several files in binary. A few of them is plain text, all small files except a 20MB one, which is also plain text (I can see it with Mac's default file previewer).
I click on it and Atom freezes. A few seconds later I get the "crashed" Mac window and I close it.

[This is the compressed file (a HOI4 saved game): USA_1942_06_29_18YEA.hoi4.zip](https://github.com/atom/atom/files/560480/USA_1942_06_29_18YEA.hoi4.zip)

[And here you can find the crash report](http://pastebin.com/q1pTyV8M)

**Comment by 50Wliu** [comment] 2016-10-30 15:56
This is a duplicate of #8864 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-30 15:56 UTC
