### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by camelop** [atom/atom#15070] opened 2017-07-21 08:17 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At C:\Users\lxy98\AppData\Local\atom\app-1.18.0\resources\app\node_modules\react-dom\lib\EventPluginUtils.js:97

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/EventPluginUtils.js:97:11)
    at executeDispatchesAndRelease (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/EventPluginHub.js:43:28)
    at executeDispatchesAndReleaseTopLevel (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/EventPluginHub.js:54:16)
    at Array.forEach (native)
    at forEachAccumulated (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/forEachAccumulated.js:24:15)
    at Object.processEventQueue (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/EventPluginHub.js:254:13)
    at runEventQueueInBatch (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:24)
    at Object.handleTopLevel [as _handleTopLevel] (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:27:11)
    at handleTopLevelImpl (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactEventListener.js:72:30)
    at ReactDefaultBatchingStrategyTransaction.perform (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/Transaction.js:143:26)
    at Object.batchedUpdates (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactUpdates.js:97:33)
    at dispatchEvent (C:/Users/lxy98/AppData/Local/atom/app-1.18.0/resources/app/node_modules/react-dom/lib/ReactEventListener.js:147:26)
```

### Commands

```
     -1:10.7.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:10.3.0 command-palette:toggle (input.hidden-input)
     -1:07.7.0 core:confirm (input.hidden-input)
     -1:07.7.0 settings-view:open (input.hidden-input)
     -0:49.3.0 core:backspace (div.package-detail.panels-item)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-beautify 0.30.4 
atom-python-run 0.7.3 
atom-runner 2.7.1 
atom-terminal-panel 4.4.4 
autocomplete-python 1.9.1 
gpp-compiler 3.0.7 
Hydrogen 1.19.0 
markdown-pdf 1.5.4 
markdown-preview-plus 2.4.10 
markdown-writer 2.6.5 
minimap 4.29.0 
power-mode 0.1.3 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-tools 0.6.9 
```

**Comment by rsese** [comment] 2017-07-21 17:46
Thanks for the report!  As mentioned below, this looks like a duplicate of https://github.com/atom/atom/issues/14900 and where we found that the error was likely caused by a community package since it wasn't reproducible in safe mode (`atom --safe`).

I'll go ahead and close for now but if you can reproduce the error in safe mode, please share the steps to reproduce and we can re-open.

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14900. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-21 17:46 UTC
