### ISSUE TITLE
[Workaround] Fix for newly added project folder having git related view issues

### ISSUE THREAD

**Issue by ramity** [atom/atom#15600] opened 2017-09-09 23:33 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I've noted a high number of git related issues marked as bug with the following files/folders.
- `.gitignore`
- `.git` folder

This workaround is for newly created project folders not adding in git visuals in the treeview interface.

### Steps to Reproduce

1. Create a directory
2. Add the newly created directory as a new project folder
 - `File > Add Project Folder`
3. Navigate to the directory via CLI and execute `git init`
![image](https://user-images.githubusercontent.com/8001375/30244712-743c0196-9589-11e7-9538-867b6e0571ef.png)
 - First, note that the directory has not been recognized as a git repo in the tree view.
 - Second, the `.git` directory has not been recognized as a hidden folder
 - Third, **if you proceed as if nothing is wrong, `.gitignore` will not "darken/hide" files properly**.
![image](https://user-images.githubusercontent.com/8001375/30244736-c1814a10-9589-11e7-8211-90caa430d367.png)
4. To fix this, remove the **project folder** (not the actual directory) in the tree view and add it back.
 - 😄 All fixed
![image](https://user-images.githubusercontent.com/8001375/30244750-f6a97866-9589-11e7-8afa-dc79150baf90.png)

**Expected behavior:** [What you expect to happen]
Tree view recognizes the project folder being initialized to a git repo and updates

**Actual behavior:** [What actually happens]
Tree view does not recognize the project folder being initialized as a git repo and does not implement additional git functionality as a result.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time

### Versions

Windows 10 Pro 10.0.15063 Build 15063

```
Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Notes

While this functionality is a bit of a feature and the implementation required to detect a change as to whether or not the folder has been initialized git repo after addition may prove impractical, I believe this process may prove invaluable to further debug actual issues.

**Comment by rsese** [comment] 2017-09-11 19:38
Thanks for reaching out and for sharing this workaround!  We'll go ahead and close this as a duplicate of https://github.com/atom/tree-view/issues/1040 since the described problem is the same (and that issue was in turn closed as a duplicate of https://github.com/atom/tree-view/issues/1036 so you can subscribe there for updates if you'd like).  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that [don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

**Closed by rsese** 2017-09-11 19:38 UTC
