### ISSUE TITLE
atom segmentation fault with clean build on Linux

### ISSUE THREAD

**Issue by jdknox** [atom/atom#14960] opened 2017-07-05 19:03 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashes immediately upon running from the command line.  As far as I remember it was working one day, then after a system restart it would segfault no matter what, even after deleting my `~/.atom` folder and trying safe mode.

I also tried downloading the latest source and building from scratch, but I still get a segfault.  Even attempting to get the version results in a segfault.

### Steps to Reproduce

1. delete `~/.atom` config folder
2. run `atom --safe` from command line

**Actual behavior:** [What actually happens]
`$ atom --safe`
```
/usr/local/bin/atom: line 130: 12082 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
`$ atom --version`
blank line

`$ /usr/local/share/atom/atom --version`
```
Segmentation fault (core dumped)
```

`$ apm --version`
```
 apm  1.18.2
 npm  3.10.10
 node 6.9.5 x64
 python 2.7.13
 git 2.13.0
```
(note: when I run `$ node --version` I get "v8.1.3")

I am running Ubuntu Gnome 17.04
`$ uname -a`
```
Linux knox-pc-linux 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Additional Information

I can't figure out what I changed when this started happening, but I can try to get more info if anyone has ideas what to look for (gdb, etc.).  My main problem is that I don't know where to start looking since I don't get any error messages from `atom`.

**Comment by jdknox** [comment] 2017-07-05 20:58
I just tried to download and run [VS Code](https://code.visualstudio.com/) and got a segfault error.  So I'm thinking this might have something to do with `electron`.

**Comment by jdknox** [comment] 2017-07-05 22:15
I was also checking my package change history and found some changes that occurred around the time `atom` started segfaulting:

```
Package changes:
    -bsdutils 1:2.29-1ubuntu2 amd64
    +bsdutils 1:2.29-1ubuntu2.1 amd64
    -google-chrome-stable 59.0.3071.109-1 amd64
    +google-chrome-stable 59.0.3071.115-1 amd64
    -libblkid1 2.29-1ubuntu2 amd64
    +libblkid1 2.29-1ubuntu2.1 amd64
    -libfdisk1 2.29-1ubuntu2 amd64
    +libfdisk1 2.29-1ubuntu2.1 amd64
    -libmount1 2.29-1ubuntu2 amd64
    +libmount1 2.29-1ubuntu2.1 amd64
    -libsmartcols1 2.29-1ubuntu2 amd64
    +libsmartcols1 2.29-1ubuntu2.1 amd64
    -libuuid1 2.29-1ubuntu2 amd64
    +libuuid1 2.29-1ubuntu2.1 amd64
    -linux-generic 4.10.0.24.26 amd64
    +linux-generic 4.10.0.26.28 amd64
    -linux-headers-generic 4.10.0.24.26 amd64
    +linux-headers-4.10.0-26 4.10.0-26.30 all
    +linux-headers-4.10.0-26-generic 4.10.0-26.30 amd64
    +linux-headers-generic 4.10.0.26.28 amd64
    +linux-image-4.10.0-26-generic 4.10.0-26.30 amd64
    -linux-image-generic 4.10.0.24.26 amd64
    -linux-libc-dev 4.10.0-24.28 amd64
    -linux-signed-generic 4.10.0.24.26 amd64
    +linux-image-extra-4.10.0-26-generic 4.10.0-26.30 amd64
    +linux-image-generic 4.10.0.26.28 amd64
    +linux-libc-dev 4.10.0-26.30 amd64
    +linux-signed-generic 4.10.0.26.28 amd64
    -linux-signed-image-generic 4.10.0.24.26 amd64
    +linux-signed-image-4.10.0-26-generic 4.10.0-26.30 amd64
    +linux-signed-image-generic 4.10.0.26.28 amd64
    -mount 2.29-1ubuntu2 amd64
    +mount 2.29-1ubuntu2.1 amd64
    -nplan 0.20 amd64
    +nplan 0.23~17.04.1 amd64
    -util-linux 2.29-1ubuntu2 amd64
    -uuid-runtime 2.29-1ubuntu2 amd64
    +util-linux 2.29-1ubuntu2.1 amd64
    +uuid-runtime 2.29-1ubuntu2.1 amd64
```

And although I installed kernel 4.10.0.26, but I'm actually running 4.10.0.24 right now (which was the last kernel I was using when atom was working).

**Comment by jdknox** [comment] 2017-07-06 00:32
Another bit of info:

I can get both `electron` and `atom` to run over an `ssh -Y` connection from my Mac.  Maybe this is a deeper problem with `gtk` on my Linux box?  At this point I highly doubt the problem lies within `atom`...

**Comment by maxbrunsfeld** [comment] 2017-07-07 18:54
@jdknox Thanks for following up with this information, and sorry we weren't able to help you. I don't have any experience running electron with gtk. I'm going to close this out, since I don't think this is something the Atom team is going to take action on.

If you open an issue on https://github.com/electron/electron, that team might be better able to help you.

**Closed by maxbrunsfeld** 2017-07-07 18:54 UTC

**Comment by balthazarbux** [comment] 2018-01-16 21:06
@jdnox did you ever figure out the cause of this issue? for myself I am working with a clean ubuntu 17.10 install but an old home directory. I'm getting the same error unless I run atom in tmux or with sudo.
