### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Houman/Library/Application Suppo...

### ISSUE THREAD

**Issue by intensivist** [atom/atom#10731] opened 2016-02-08 15:22 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Houman/Library/Application Support/com.github.atom.ShipIt/update.XVOrorJ/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -0:08.8.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false
  },
  "editor": {
    "backUpBeforeSaving": true,
    "invisibles": {},
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-02-08 17:51
Thanks for reporting!  This looks like a duplicate of #7399 though, so feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-08 17:51 UTC

**Comment by joshaber** [comment] 2016-02-08 20:06
@intensivist When you got this error, did Atom seem to be functioning fine? Did you have to restart for it to work?

**Comment by intensivist** [comment] 2016-02-08 21:58
It was working fine. I tried to go to preferences and change some settings and I received this message. I did not restart it. 
BTW, I love writing codes with Atom.
