### ISSUE TITLE
Allow copy file via drag and drop

### ISSUE THREAD

**Issue by rillig** [atom/atom#16103] opened 2017-11-04 20:58 UTC
### Description

At the left of the screen, there is the Project view, listing all project files in a directory tree.
There, I can move files using drag and drop.
But I cannot copy files using drag and drop.
The latter should be possible, too.

### Steps to Reproduce

1. Open a project
2. Drag some file to another folder and, during dragging, press <kbd>Ctrl</kbd>.

**Expected behavior:**

* The mouse cursor gets a little [+] decoration instead of the [ ].
* The file is copied instead of moved.

**Actual behavior:**
* The mouse cursor stays at [ ].
* The file is moved.

### Versions

Atom: 1.21.2 x64
Windows: 10

### Additional Information

Other applications that allow copy using drag and drop:
* Windows Explorer
* IntelliJ IDEA
* Pretty much any file manager

**Comment by lee-dohm** [comment] 2017-11-04 23:42
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/703. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2017-11-04 23:42 UTC
