### ISSUE TITLE
Atom uses unexpectedly large quantities of storage space in a hidden folder

### ISSUE THREAD

**Issue by jh3141** [atom/atom#15694] opened 2017-09-20 03:52 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom uses an extraordinarily large amount of disk space in a hidden folder (%LOCALAPPDATA%\Atom under Windows, presumably the same thing happens in ~/.atom under Linux although I haven't tested this).  Usage is apparently increasing without limits over time.

Having had Atom installed for several months, I have the following contents in the given folder (along with sizes and timestamps of most-recently-modified file in each subdirectory):

> 595M    2017-06-16 04:04        ./app-1.18.0
> 582M    2017-08-08 18:13        ./app-1.19.0
> 581M    2017-08-14 22:47        ./app-1.19.1
> 581M    2017-08-17 02:33        ./app-1.19.2
> 583M    2017-08-22 23:14        ./app-1.19.3
> 583M    2017-08-28 19:34        ./app-1.19.4
> 4.0K    2017-08-28 19:33        ./bin
> 1.1G    2017-08-28 19:33        ./packages
> 4.5G    2017-08-30 16:41        .
> 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

Usage is limited and reasonably small, and does not grow boundlessly over time.  Presumably, this means that older versions should be deleted (perhaps retain the current version and the previous version, and deleted anything older than that?  also the downloaded packages could presumably be deleted as soon as they've been installed?)

**Actual behavior:** [What actually happens]

Disk usage grows boundlessly.  For users trying to run an OS off a modest-sized SSD (e.g. 80GB) the level of usage growth is so large that it will become problematic in reasonably short timespans.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time, AFAICT.

### Versions

Versions are as shown in the file dump above.  I'm running on Windows 7 Professional, but doubt it would be any different in other versions.

**Comment by jh3141** [comment] 2017-09-20 04:05
Hmm.  Looking at the update log in the directory, it seems that it has been *attempting* to remove the out of date versions, but something's going wrong.  Most recent complete update operation in the log looks like this:

```
2017-08-28 19:29:37> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.4-delta.nupkg
2017-08-28 19:30:33> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()
2017-08-28 19:30:33> CheckForUpdateImpl: Using existing staging user ID: 1f29626f-208f-5acf-bf32-f448206c0d7f
2017-08-28 19:30:33> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.19.1
2017-08-28 19:30:33> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.19.1&id=atom&localVersion=1.19.3&arch=amd64
2017-08-28 19:30:33> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.4-full.nupkg
2017-08-28 19:31:46> ApplyReleasesImpl: Writing files to app directory: C:\Users\admin\AppData\Local\atom\app-1.19.4
2017-08-28 19:31:49> LogHost: Rigging execution stub for atom_ExecutionStub.exe to C:\Users\admin\AppData\Local\atom\atom.exe
2017-08-28 19:33:48> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\admin\AppData\Local\atom\app-1.19.4\atom.exe]
2017-08-28 19:34:04> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\admin\AppData\Local\atom\app-1.19.4\atom.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2017-08-28 19:34:04> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-08-28 19:34:04> ApplyReleasesImpl: Examining Pin: Atom.lnk
2017-08-28 19:34:04> ApplyReleasesImpl: Examining Pin: Calculator.lnk
2017-08-28 19:34:05> ApplyReleasesImpl: Examining Pin: eclipse.exe - Shortcut.lnk
2017-08-28 19:34:05> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-08-28 19:34:05> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2017-08-28 19:34:05> ApplyReleasesImpl: Processing shortcut 'C:\Users\admin\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Atom.lnk'
2017-08-28 19:34:05> ApplyReleasesImpl: Old shortcut target: 'C:\Users\admin\AppData\Local\atom\atom.exe'
2017-08-28 19:34:05> ApplyReleasesImpl: New shortcut target: 'C:\Users\admin\AppData\Local\atom\atom.exe'
2017-08-28 19:34:05> ApplyReleasesImpl: Old iconPath is: 'C:\Users\admin\AppData\Local\atom\atom.exe'
2017-08-28 19:34:05> ApplyReleasesImpl: Finished shortcut successfully
2017-08-28 19:34:05> ApplyReleasesImpl: Fixing up tray icons
2017-08-28 19:34:05> ApplyReleasesImpl: cleanDeadVersions: for version 1.19.4
2017-08-28 19:34:05> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.19.3
2017-08-28 19:34:05> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.19.4
2017-08-28 19:34:14> ApplyReleasesImpl: Failed to clean dead versions, continuing anyways: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass14_2.<cleanDeadVersions>b__8(Tuple`2 p)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass14_0.<<cleanDeadVersions>b__7>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<cleanDeadVersions>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
```

**Comment by rsese** [comment] 2017-09-20 17:11
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15320. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-20 17:11 UTC
