### ISSUE TITLE
Uncaught Error: Requested measurement of a line that is not currently rendered

### ISSUE THREAD

**Issue by garethallenstringer** [atom/atom#15318] opened 2017-08-15 17:03 UTC
[Enter steps to reproduce:]

1. Deleted a line of code in JS
2. Got caught in an infinite error loop

**Atom**: 1.19.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At C:\Users\GarethAllen-Stringer\AppData\Local\atom\app-1.19.1\resources\app\src\text-editor-component.js:2206

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:2204:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:2197:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:384:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.19.1/resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.1/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.1/resources/app/src/view-registry.js:3:65
```

### Commands

```
  2x -6:03.8.0 intentions:highlight (input.hidden-input)
     -6:03.3.0 core:save (input.hidden-input)
  2x -5:34.1.0 core:backspace (input.hidden-input)
     -5:29.6.0 intentions:highlight (input.hidden-input)
     -5:29.3.0 core:save (input.hidden-input)
  8x -3:36.3.0 core:backspace (input.hidden-input)
  8x -2:27.1.0 core:move-right (input.hidden-input)
  4x -2:24.7.0 core:backspace (input.hidden-input)
     -2:14.2.0 editor:newline (input.hidden-input)
  6x -1:43.5.0 intentions:highlight (input.hidden-input)
     -1:42.9.0 core:save (input.hidden-input)
     -1:34.9.0 intentions:highlight (input.hidden-input)
     -1:34.4.0 core:select-all (input.hidden-input)
 31x -1:32.7.0 intentions:highlight (input.hidden-input)
     -1:25.3.0 settings-view:open (input.hidden-input)
     -1:10.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autoclose-html 0.23.0 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
file-icons 2.1.10 
intentions 1.1.5 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-ui-default 1.6.5 
lucid-tabs 1.1.1 
minimap 4.29.6 
minimap-selection 4.5.0 
open-recent 5.0.0 
pigments 0.40.2 
sass-autocompile 0.13.3 
scroll-through-time 0.2.0 
sync-settings 0.8.2 
todo-show 1.11.0 
```

**Comment by Ben3eeE** [comment] 2017-08-15 17:55
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15263. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-15 17:55 UTC
Labels: duplicate
