### ISSUE TITLE
Install packages: When space is hit on search, view goes to bottom

### ISSUE THREAD

**Issue by pantuts** [atom/atom#11956] opened 2016-06-10 09:54 UTC
I dont know how to call this.
The problem(?): Go to Install package, type any word. When you hit space, the view goes to bottom as shown in below gif.

```
Atom    : 1.8.0
Electron: 0.36.9
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

![preview](https://cloud.githubusercontent.com/assets/894185/15960821/2df91dd4-2f34-11e6-8e95-4d861f10a85c.gif)

**Comment by Ben3eeE** [comment] 2016-06-10 10:11
This is a duplicate of https://github.com/atom/settings-view/issues/767

**Closed** 2016-06-10 11:05 UTC
