### ISSUE TITLE
atom not launching/application.json

### ISSUE THREAD

**Issue by ahelhot** [atom/atom#9644] opened 2015-11-17 08:56 UTC
After few hourse of work today, atom just close and not open again. I try run with --safe mode, but nothing happen. Atom wont delete from machine, i try reinstall this, but windows detect very long folders name, like this packages/atombeauti/some_module/somefile/some_module/somefile/some_module/somefile/some_module/somefile/some_module/somefile/some_module/somefile/some_module/somefile/ ...

and in folder .atom/storage placed file called application.json, this file just broke ntfs file system from normal work, windows can't do anything from this file. In my machine (work), i don't have linux with another file system, so i can't reinstall atom or unistall them completly.

//sorry for english.

**Comment by benogle** [comment] 2015-11-17 20:13
Can you move the `.atom` folder to another name? Does it start then?

**Comment by fluteamahoot** [comment] 2015-11-17 23:41
I'm having the same issue, but what I've found is that it's the .atom\storage\application.json file that is breaking windows. It prevents deleting, moving, renaming, hell even right clicking. I've tried both windows and cygwin utilities to delete it, but I can delete it after a reboot. This is making Atom unusable.

**Comment by ChadLefort** [comment] 2015-11-18 04:19
I've been having this same problem for the last couple of days. Atom will just crash on me and I can't open it back up until I restart my computer. I am running Windows 7 Professional x64. I've tried running with the --safe command and made sure no processes or running. I also can't rename or move my .atom folder as my explorer locks up because of the .atom\storage\application.json file. Once I restart my computer atom works again and I am able to delete/move the .atom folder.

**Comment by benogle** [comment] 2015-11-18 17:24
@ChadLefort to be clear, after a reboot, does moving the `.atom` folder fix the issue? Fix it just once? Or for all subsequent atom starts?

cc @raelyard @kevinsawicki why is the storage/application.json locked?

**Comment by raelyard** [comment] 2015-11-18 20:29
@ChadLefort noted being on Windows 7 - didn't see specified which OS for @ahelhot or @fluteamahoot.  Which version of Windows are you on?  I have seen disturbing locking behavior (not often) on Win 7 like described where I can't unlock and can't access and can't take ownership.  Haven't seen that on 10 (yet) and don't recall whether on 8/8.1, but don't think so.  Suspecting this might be specific to 7.

@fluteamahoot, @ChadLefort - you both said you saw crashes.  Could you grab a crash dump from "C:\Users\David\AppData\Local\Temp\Atom Crashes" and share it?  @ahelhot, when Atom stopped working, did you see a crash message?  Do you see a .dmp file in that location?

**Comment by 50Wliu** [comment] 2015-11-18 20:54
I've had Atom lock files that were open, but I haven't experienced this bug yet.

Windows 10 x64.

**Comment by ChadLefort** [comment] 2015-11-18 22:47
@raelyard I should have also been more specific, but pretty much what @fluteamahoot has said. It's more of a hang and then I get 3 processes, and Atom just won't start back up.

Here is everything on my crash folder. 
[operation_log.txt](https://github.com/atom/atom/files/38421/operation_log.txt)

**Comment by ahelhot** [comment] 2015-11-19 09:10
> Can you move the .atom folder to another name? Does it start then?
i set atom in autostart with windows, after remove from this list, i again can do this. Now i can delete file  /application.json and reinstall atom.

**Comment by raelyard** [comment] 2015-11-19 19:27
Pretty safe to assume this is Win 7 only.  I can try to reproduce, but not a lot to go on here for steps to make it happen.  Looks like it appears pretty sporadically.  I'll work in a Windows 7 machine over the next few days and see if it happens to me.  If anybody can isolate any conditions that lead to this, it would be helpful.

**Comment by fluteamahoot** [comment] 2015-11-20 00:23
Well, if it's any help, I've been noticing it happening after I open another project in another window without closing the first. Usually it's after I switch back to the original window that Atom hangs, and this issue starts.

**Comment by raelyard** [comment] 2015-11-25 16:11
Thanks for the additional information, @fluteamahoot.  I am still unable to reproduce, though.

**Comment by loque** [comment] 2015-11-25 22:42
In response to what @fluteamahoot added, working with one projects produces the same error. Also using Windows 7 Pro x64. The symptoms are exactly as described above. I'm unable to delete the file .atom/storage/application.json from Explorer and from command prompt.

These are the packages I'm using:
* ctrl-last-tab
* highlight-selected
* minimap
* minimap-highlight-selected
* php-twig
* react
* Stylus

**Comment by mjobdt** [comment] 2015-12-22 08:19
I have same issue.

symptomatic treatment. Maybe, not suitable for multi projects.
Chang application.json attribute to 'Read Only'.
application.json is here : C:\Users\USERNAME\.atom\storage

I'm not good at English.
Please ask again if you cannot the written.

**Comment by fluteamahoot** [comment] 2015-12-24 05:47
Quick update, I upgraded to Windows 10 on that machine to see what would happen. Been using Atom for a while after and I haven't had a single problem since.

**Comment by damieng** [comment] 2016-09-29 16:03
No activity on this issue for a while and there's a good chance it's been fixed as part of the other work in this area. Please feel free to comment if you run into this exact issue and we'll re-open.

**Closed by damieng** 2016-09-29 16:03 UTC
Labels: bug, windows
