### ISSUE TITLE
core deprecation  : Assigning editor 170's height explicitly via position: 'absolute' and an assigned top and bottom implicitly assigns the autoHeight property to false on the editor.

### ISSUE THREAD

**Issue by anielka** [atom/atom#13682] opened 2017-01-23 12:45 UTC
### Description

in Ubuntu 16.04 Mate after updating from 1.8.0 to 1.13.0 x64 ( from website .deb download and from unofficial repo ppa:webupd8team/atom ) there exists 1 atom core deprecation

### Steps to Reproduce

1. upgrade atom 
2. run atom

**Reproduces how often:** every run

### Versions

**atom --version**
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**apm --version**
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12

**lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

### Additional Information

Deprecated calls
  atom core (1 deprecation)
    Assigning editor 170's height explicitly via position: 'absolute' and an assigned top and bottom implicitly assigns the autoHeight property to false on the editor. This behavior is deprecated and will not be supported in the future. Please explicitly assign autoHeight on this editor.

    TextEditorComponent.measureDimensions - /opt/atom/resources/app.asar/src/text-editor-component.js:1011:20
    TextEditorComponent.becameVisible - /opt/atom/resources/app.asar/src/text-editor-component.js:295:12
    TextEditorComponent.checkForVisibilityChange - /opt/atom/resources/app.asar/src/text-editor-component.js:993:16
    atom-text-editor.attachedCallback - /opt/atom/resources/app.asar/src/text-editor-element.js:87:22
    atom-pane.activeItemChanged - /opt/atom/resources/app.asar/src/pane-element.js:138:24
    Function.module.exports.Emitter.simpleDispatch - /opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14

**Comment by Ben3eeE** [comment] 2017-01-23 18:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13653. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-01-23 18:22 UTC
