### ISSUE TITLE
Release note doesn't update

### ISSUE THREAD

**Issue by pistou** [atom/atom#10013] opened 2015-12-11 09:26 UTC
Hey,

I'm currently using **Atom v1.3.1** on **Windows 10**.
Yet, the release note is stuck on v1.1.0 - I have to check on [atom.io](https://atom.io/releases) to see what are the updates.

Is it normal the green button "Restart and update" remains here even if I'm on the latest version?

![issue](https://cloud.githubusercontent.com/assets/6703711/11740223/5fba8204-9ff1-11e5-9cf3-af5bf9fdfbb5.jpg)

**Comment by 50Wliu** [comment] 2015-12-11 13:00
This is a duplicate of atom/release-notes#39 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-11 13:00 UTC
