### ISSUE TITLE
window state is only saved if atom was closed correctly

### ISSUE THREAD

**Issue by SlimeQ** [atom/atom#9898] opened 2015-12-01 23:38 UTC
this is a pretty low impact issue

i use ubuntu with i3wm, so i typically shut down my laptop at the end of a work day from the command line. this means that atom gets force closed every day. when starting it up the next day, it opens all saved windows from the last session... that i closed correctly. this means that it will usually open a ton of files that i was editing weeks ago. this can take several minutes in particularly bad instances with multiple windows.

obviously this is partially user error, but i figure i'd throw an issue up anyways. sublime doesn't behave like this so i know it can be better.

additionally it seems as though the "Open an empty editor on start" option in the preferences is ignored. my assumption is that such an option would disable persistence... am i wrong?

**Comment by thedaniel** [comment] 2015-12-02 14:59
Thanks for writing in - this is a dupe of #1516, also I believe that preference is for fresh (non-restored) instances of Atom.

**Closed by thedaniel** 2015-12-02 14:59 UTC
