### ISSUE TITLE
Atom loses unsaved changes and doesn't remember my open tabs

### ISSUE THREAD

**Issue by bitbonk** [atom/atom#8327] opened 2015-08-11 17:10 UTC
I have just downloaded **atom-windows.zip** (version 1.0.5) unzipped it and started atom.exe on my Windows 7 machine. 

When I close the editor I get a messagebox saying

> 'test.txt' has changes, do you want to save them?
> Your changes will be lost if you close this item without saving.

For new tabs that have not beens saved to a file yet I get *'untitled'* instead of the filename in that messagebox.

Atom should close without this messagebox and when I reopen atom, it should be right where I left of. The same tabs should be open and **all unsaved changes should still be there**.

**Comment by mnquintana** [comment] 2015-08-11 17:11
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/942 though – please subscribe there for updates.

**Closed by mnquintana** 2015-08-11 17:11 UTC

**Comment by thenoelforte** [comment] 2015-08-14 05:22
Along the lines of this particular issue and many like it, it's confusing to have the editor warn you about not saving, nonetheless it restores your session for you when you reopen it. Should I open a new issue about this behavior, or should I subscribe to #942? I feel like that part of the UI is not directly related.
