### ISSUE TITLE
Line Position resets on file change

### ISSUE THREAD

**Issue by vinnytroia** [atom/atom#6723] opened 2015-05-10 21:36 UTC
When working in a CSS file (or presumably any type of file), if the file is updated from an outside source, the position of the page will reset causing you to have to scroll back down to where you were. 

Case: When working in CSS, I often work both directly in the CSS and via Chrome Dev Tools (changes are autosaved to the local CSS). Every time the file changes via Chrome Dev Tools, Atom resets the scroll position. 

Sublime Text handles this perfectly. Any changes are just updated but your position is never lost. This can probably be solved by just capturing the current line number before the file resets, then going back to that number.

**Comment by lee-dohm** [comment] 2015-05-10 22:28
Duplicate of #5730. Please subscribe there for updates.

**Closed by lee-dohm** 2015-05-10 22:28 UTC

**Comment by RobertSasak** [comment] 2017-01-13 12:01
This plugins prevent scrolling https://atom.io/packages/remember-file-positions
