### ISSUE TITLE
[BUG] Long single-line file crashes Atom every time.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#12065] opened 2016-06-28 17:48 UTC
Some care needs to be taken by Atom when loading longs files or binary files, because crashing is not a good experience.

What's worse is that if the file is open in a project, if we restart Atom then load the project, Atom crashes again. So there's no way to open a project that crashed with that file open and the project is now useless. To solve the problem, the project has to be deleted and a new one created.

(Interesting to note that Vim and NeoVim don't crash when opening the same files, even with all my plugins installed, and remain responsive).

Related issues:
- https://github.com/atom/atom/issues/12049
- https://github.com/atom/atom/issues/11992
- https://github.com/atom/atom/issues/11894
- https://github.com/atom/atom/issues/11831
- https://github.com/atom/atom/issues/11110 (the number 11110 suits this issue well)
- https://github.com/atom/atom/issues/10917
- https://github.com/atom/atom/issues/9825
- https://github.com/atom/atom/issues/8154
- https://github.com/atom/atom/issues/7583
- https://github.com/atom/atom/issues/7396

Guys, I think this is a serious issue and it should possibly have the highest priority over all other issues (seriously!). People don't like clicking on project-find search results only to have a crash (because it's not possible to tell how long a file is in those search results, for example, but it shouldn't even matter).

**Comment by Zireael07** [comment] 2016-06-28 18:42
Duplicate of #979.

**Comment by mnquintana** [comment] 2016-06-29 00:34
Thanks @Zireael07! This is indeed a duplicate of https://github.com/atom/atom/issues/979 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-06-29 00:34 UTC

**Comment by mnquintana** [comment] 2016-06-29 00:39
For the large file (but not long line) issues, let's continue to keep the discussion in https://github.com/atom/atom/issues/8864. Thanks!

**Comment by JonET** [comment] 2016-09-13 14:57
@mnquintana I'd love to follow #979 but it just seems that the Atom developers have locked discussion and buried their heads in the sand on the issue.  This is a serious usability problem I run into when pasting in normal JSON responses from Chrome, which come in one long unformatted line.  Wastes a lot of time when I forget that this modern whiz-bang text editor can't handle text.

**Comment by mnquintana** [comment] 2016-09-13 15:07
@JonET Just to be clear, if we lock an issue that does *not* mean the team is "burying their heads in the sand" regarding it – it just means that the conversation on the issue wasn't adding any valuable information for the team or the 50+ subscribers on the issue. (Take a look for yourself – all the comments at the end are about switching to other editors.) You can still subscribe to an issue for updates even if it's locked.

I agree that this particular performance issue definitely needs to get addressed, but it's part of an ongoing effort – it's not as simple as copying this One Weird Trick from another editor.

I don't work for GitHub, but as far as I know performance is always one of the top priorities for the core team.

**Comment by JonET** [comment] 2016-09-13 15:14
Somebody could have asked people to keep the thread on-topic.  Since it's closed right now I just see an open issue with no movement for almost a year.

**Comment by thomasjo** [comment] 2016-09-13 15:19
> Somebody could have asked people to keep the thread on-topic.

Yeah, that doesn't work.

> Since it's closed right now I just see an open issue with no movement for almost a year.

How would it be any different if it wasn't locked? I fail to see the point you're trying to make here.
If someone on the core team or one of the collaborators where specifically working on that issue they would most likely post an comment. If we needed more feedback, we'd unlock the issue.

In summary, we are painfully aware of this issue, but it's a very complex problem that is being addressed incrementally in various ways. I fail to see how the aforementioned issue being locked has any impact on this at all. Locked does not mean the same as closed.

**Comment by iolsen** [comment] 2016-09-13 17:10
> I don't work for GitHub, but as far as I know performance is always one of the top priorities for the core team.

I'm the engineering manager for Atom at GitHub and I just want to echo this, and essentially everything @mnquintana  said above. Performance is positively a top priority and we are deeply appreciative of discussions that help us identify or fix performance issues. In order to focus on those, we sometimes have to lock threads that have become unproductive. In no way should this be interpreted as a sign that we don't care about making Atom faster!

**Comment by AzRu** [comment] 2016-09-22 18:43
I'm seeing a hang with a ~1000 line .js file after adding about ~600 lines of mock data as an array of 3 key, value pair objects. @iolsen

**Comment by jamalsoueidan** [comment] 2017-01-03 10:04
Still hanging here also 2017! if the lines is long!

**Comment by iolsen** [comment] 2017-01-03 17:05
@maxbrunsfeld @ungb Can we test some of this with the new native changes?

**Comment by ungb** [comment] 2017-01-03 18:55
I'll take a look today!

**Comment by ungb** [comment] 2017-01-03 22:01
@iolsen I was able to test this out with the new native changes off master that @maxbrunsfeld made.  I tested with binary file provided in https://github.com/atom/atom/issues/11110, It was able to open the file.  I do not see crashes any more.

@trusktr @jamalsoueidan We've made some improvements with regards to large files that will be out in stable in our next release, which should happen sometime next week, currently these changes are only in master. 

**Note**: these changes will address large files, but still see some issues with extremely large files (over 10 million lines),  Also, these changes don't address a file with a long single line.  

I believe with long single-line and extremely large file, you'll run into https://github.com/atom/atom/issues/11690

**Comment by iCaio** [comment] 2017-02-22 17:27
https://github.com/moip/moip-sdk-js/blob/master/dist/moip-2.7.0.min.js

This file is crashing my Atom, and this is not so large :(

Version: 1.14.2 x64 On MacOS Sierra.

**Comment by iCaio** [comment] 2017-02-22 17:33
Fixed on Beta 👍 , thanks!

**Comment by kendrick** [comment] 2017-03-03 19:28
So happy to find this fixed in the 1.15 beta—thank you!

**Comment by golovan** [comment] 2017-03-04 11:35
Good job!

**Comment by davidgreens** [comment] 2017-03-05 18:44
⚡🔐👏

**Comment by objectivehtml** [comment] 2017-03-06 17:45
Thanks a lot for the work. This issue has been causing me headache for a while and just stumbled upon this thread in attempt to see what was causing it.

**Comment by sijpkes** [comment] 2018-02-06 03:33
This is still happening in 1.23.3

**Comment by 50Wliu** [comment] 2018-02-06 03:53
@sijpkes your comment is not actionable.  Please open a new issue and completely fill out the issue template and we'll take a look :).
