### ISSUE TITLE
Syntax highlighting for Brackets

### ISSUE THREAD

**Issue by JayRJoshi** [atom/atom#10356] opened 2016-01-10 09:31 UTC
Atom treats brackets inside the string equally as brackets outside of string as far as highlighting/underlining brackets is concerned.

For example, When placing cursor after lone bracket inside string, bracket is highlighted as if it were in pair with one of the bracket outside the scope of the string ( a part of screenshot is attached ).

![atom](https://cloud.githubusercontent.com/assets/10296262/12220662/085c1240-b7a0-11e5-863a-eb79c7ed1306.PNG)

Notepad++ does not pair brackets inside string with outside one.

![np](https://cloud.githubusercontent.com/assets/10296262/12220891/9a453dd0-b7aa-11e5-80e6-eb60b63d5e00.PNG)

Likewise, this will apply to brackets inside comments as well.

**Comment by mnquintana** [comment] 2016-01-10 13:58
Thanks for the report! :smile: This looks like a duplicate of https://github.com/atom/bracket-matcher/issues/23 – feel free to subscribe there for updates.

Also, please take a look at [this guideline for reporting bugs](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs).

**Closed by mnquintana** 2016-01-10 13:58 UTC
