### ISSUE TITLE
Reopen files and project folders does not work

### ISSUE THREAD

**Issue by lczech** [atom/atom#7323] opened 2015-06-17 18:50 UTC
Just recently updated to 0.209 on Ubuntu 14.04. Since then atom starts empty every time. It opened all my files, panes, project tree and so on before the update (I think, I was using 0.201 then).

I also tried re-installing the old version, but neither this nor a complete un-install works in Ubuntu...

Then I tried installing a fresh atom on a different machine (also Ubuntu 14.04), it shows the same behaviour (not saving the session) - so it is definitely due to the core as I do not yet have any other packages installed on this machine.

What happened there?

**Comment by mnquintana** [comment] 2015-06-17 18:51
This is a duplicate of #7231– this has been fixed already for the next release of Atom, 0.210.0.

**Closed by mnquintana** 2015-06-17 18:51 UTC

**Comment by lczech** [comment] 2015-06-17 19:01
sorry, seems I searched for the wrong keywords and did not find this thread.
