### ISSUE TITLE
Reopen window invisible (on disconnected monitor) on Windows 7 virtual machine with VMWare Fusion

### ISSUE THREAD

**Issue by gonglei** [atom/atom#13376] opened 2016-12-02 21:56 UTC
### Description
Atom editor window is invisible if it closed on 2nd monitor previously and 2nd monitor is disconnected. I'm running on Windows 7 VM on MAC with Fusion 7 unity mode.

### Steps to Reproduce
I run a Windows 7 VM on MAC with VMWare Fusion 7. The VM is in unity mode. 

1. Open Atom editor on 2nd monitor and close it.
2. Suspend VM
3. Disconnect 2nd monitor
4. Resume VM
5. Open Atom editor

**Expected behavior:** [What you expected to happen]
The Atom window should show on my primary monitor since 2nd monitor is disconnected

**Actual behavior:** [What actually happened]
The Atom window is not visible. It is actually opened on the disconnected monitor. I have to change VM view from unity to single window, right click the small atom window on bottom and choose move, then use keyboard and mouse to bring the window to my primary monitor.

### Versions
<= 1.12.6

**Comment by Ben3eeE** [comment] 2016-12-04 16:07
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/6939. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-04 16:07 UTC
