### ISSUE TITLE
Cancel is ignored when closing window with unsaved changes

### ISSUE THREAD

**Issue by ameuret** [atom/atom#4092] opened 2014-11-07 14:32 UTC
It looks like the same issue as #1989.

I'm runing 0.142.0 on Windows 7.

I've tracked it down to three 'beforeunload' handlers being called, one of them honoring the Cancel request but only to have its result flag trampled by the third handler. Could not go further for now.

It behaves as if "Don't Save" was chosen. :scream: 

(Dismissing the dialog using the close icon does the same, as you would expect.)

**Comment by devios1337** [comment] 2015-05-14 00:02
I'm experiencing this on OS X 10.10.3 and Atom 0.198.0.

**Comment by thomasjo** [comment] 2015-05-14 06:59
@devios1337 Are you able to reproduce the problem in [safe mode](https://atom.io/docs/v0.198.0/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by devios1337** [comment] 2015-05-14 23:04
@thomasjo No it appears to work fine in safe mode.

**Comment by thomasjo** [comment] 2015-05-15 04:55
@devios1337 Would you mind providing us with a list of installed packages so we can track down the culprit? Simply share the output of `apm list --installed`.

**Comment by devios1337** [comment] 2015-05-18 17:34
Sorry for the delay. Here you are:

├── atom-beautify@0.27.1
├── auto-update-packages@0.2.2
├── file-icons@1.5.5
├── fuzzy-finder-plus@1.4.0
├── highlight-selected@0.9.3
├── incremental-search@4.3.0
├── line-count@0.2.0
├── minimap
├── monokai@0.14.0
├── one-dark-syntax@0.5.0
├── one-dark-ui@0.8.1
├── remember-session@0.5.1
├── unity-ui@2.0.8
└── up2date@0.0.7

**Comment by thomasjo** [comment] 2015-05-18 17:38
OK, as a start, you should remove `remember-session`. It's been deprecated by similar functionality provided by Atom Core. See https://github.com/hampustagerud/atom-remember-session/pull/29.

Let us know if that resolves the issue. If not, I'll look more closely at some other candidates from your list.

**Comment by devios1337** [comment] 2015-05-18 17:44
Thanks! That does indeed seem to have eliminated the issue. However if I may be so bold without knowing anything about it, the fact that a package can cause this to happen at all seems like something of a design issue to me. Unless `remember-session` itself is really fully to blame.

**Comment by thomasjo** [comment] 2015-05-18 17:48
Well, packages are allowed to do almost anything really. Most of the time, that freedom is awesome! However, it does have a cost, as you've just discovered. But I'm willing to accept that, since the benefits greatly outweigh the downsides (in my opinion).

**Comment by thomasjo** [comment] 2015-05-18 17:49
I'm going to close this issue since the underlying problem has been resolved. Sorry about the problems @devios1337, but thankfully we managed to resolve it.

**Closed by thomasjo** 2015-05-18 17:49 UTC
Labels: more-information-needed, windows

**Comment by devios1337** [comment] 2015-05-18 17:54
Of course, I'm not suggesting changing that, but as I see it there are two possibilities of what's going on here:

1. `remember-session` is doing something it shouldn't and is responsible for the closing of the window and the loss of data, in which case there's nothing to be done as it's already deprecated.
2. There is a bug in Atom core that is causing the window to be closed because of some unexpected behavior by `remember-session`, in which case that should be fixed as it could happen again with other packages.
