### ISSUE TITLE
Atom 1.0 vs Windows VM

### ISSUE THREAD

**Issue by absalomedia** [atom/atom#7673] opened 2015-07-03 05:21 UTC
Editor keeps freezing when running inside a Windows VM ( Server 2008r2 to be specific -10Gb total VM memory).

Usually it freezes under the Package view when trying to browse / update the list.

**Comment by batjko** [comment] 2015-07-03 05:40
VMs are known to not work very well with Atom, have a look at this one: https://github.com/atom/atom/issues/6306.

However, your issue appears to be more related to this one: https://github.com/atom/settings-view/issues/555, which is all about the lag and sometimes crashing of the package listings in Settings View.

**Comment by paulcbetts** [comment] 2015-07-03 06:25
@batjko This isn't a general truism, it's only VirtualBox that decided to declare its mouse as a touch device - I have had zero problems with Atom and Parallels

**Comment by thomasjo** [comment] 2015-07-03 06:31
> This isn't a general truism, it's only VirtualBox that decided to declare its mouse as a touch device - I have had zero problems with Atom and Parallels

Same here, zero problems with VMware.

**Comment by batjko** [comment] 2015-07-03 07:45
Ok, that's good to know. I have edited my comment above.

**Comment by visualcookie** [comment] 2015-07-03 09:07
Duplicate of this issue:
https://github.com/atom/atom/issues/7191

**Comment by batjko** [comment] 2015-07-03 09:26
@visualcookie It isn't. This issue is specifically about problems using Atom on a Vbox, 
The one you linked is observable on physical machines as well.

**Comment by absalomedia** [comment] 2015-07-06 01:38
I RDP into a Windows VM. Unsure what architecture the actual VM is, all I've got is Windows 2008 R2 inside it.

**Comment by damieng** [comment] 2016-05-05 23:43
The two bugs referenced originally by this one are fixed - please re-open if they have not resolved your issue.  I'd also recommend updating to the latest version of VirtualBox including the client VM tools.

**Closed by damieng** 2016-05-05 23:43 UTC
