### ISSUE TITLE
Auto-indent on paste misbehaviour (javascript): next line after "if" statement w/o braces

### ISSUE THREAD

**Issue by afanasy** [atom/atom#5106] opened 2015-01-16 13:16 UTC
```javascript
if (true)
  a = b
  return
```
"Return" should have the same indent as "if"

**Comment by kevinsawicki** [comment] 2015-01-16 17:36
I believe this is a duplicate of https://github.com/atom/language-javascript/issues/51

**Closed by kevinsawicki** 2015-01-16 17:36 UTC

**Comment by afanasy** [comment] 2015-01-17 05:56
Thanks!
