### ISSUE TITLE
Allow Command+W to close windows, not just tabs

### ISSUE THREAD

**Issue by mcandre** [atom/atom#6092] opened 2015-03-25 14:30 UTC
On Mac OS X, many applications allow users to close tabs and windows with the same hotkey, `Command + w`. Could Atom respect this convention as well?

**Comment by mnquintana** [comment] 2015-03-25 14:34
Do you mean that <kbd>Cmd+W</kbd> should also close the window if there are no tabs open?

**Comment by mcandre** [comment] 2015-03-25 14:40
Aye.

**Comment by izuzak** [comment] 2015-03-25 17:40
I believe this is a duplicate of https://github.com/atom/atom/issues/863.

**Closed by izuzak** 2015-03-25 17:40 UTC
