### ISSUE TITLE
Regression: Select Next (CMD + D) Case Insensitivity Option

### ISSUE THREAD

**Issue by elado** [atom/atom#13961] opened 2017-03-08 19:55 UTC
According to https://github.com/atom/atom/issues/9003 this issue was resolved, but on 1.14.3 it is not working.

Expected behavior:

```
FooBar
FooBar

fooBar
fooBar
```

Selecting first `Foo` and hitting CMD+D 3 times should also select the two `foo` in `fooBar`.

Currently it stops at the second `Foo`.

**Comment by rsese** [comment] 2017-03-08 20:27
It looks like this was already reported again in atom/find-and-replace /cc https://github.com/atom/find-and-replace/issues/825. 

Going to go ahead and close this as a dupe of that one and label it as a bug.

**Closed by rsese** 2017-03-08 20:27 UTC
