### ISSUE TITLE
Feature Request for package/theme website

### ISSUE THREAD

**Issue by MandarSant** [atom/atom#13442] opened 2016-12-14 06:07 UTC
I am requesting a feature request for package/theme website ie install option on website 

- install option on website for every package/theme when ever install is clicked the package/theme will be auto downloaded and installed in atom.

- Installed package/theme should be shown in separate My package/theme page or column or etc

- And also  Uninstall option, when uninstall button is clicked(on website) the package/theme should be auto remove from editor

reference is from google play store website

**Comment by Ben3eeE** [comment] 2016-12-14 07:11
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/5262. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-14 07:11 UTC

**Comment by MandarSant** [comment] 2016-12-14 11:54
@Ben3eeE  i think u didnt got what i describe #5262 is different

**Comment by Ben3eeE** [comment] 2016-12-14 12:36
It would be helpful if you can describe why you think it is different. As I am reading it both issues are about initiating a package installation from the atom.io website.
