### ISSUE TITLE
Wrong character being inserted when period key is pressed

### ISSUE THREAD

**Issue by mauricioklein** [atom/atom#11071] opened 2016-03-05 07:26 UTC
### Description

I'm facing an strange behavior, where, for no reason and happening at random moments, my period key begins to insert the '>' character instead the period one.

I couldn't figure out yet a pattern or even steps to reproduce it, since this bug happens randomly.

The only way I found to fix it is rebooting.

Facing this problem on Ubuntu Linux, Atom v.1.5.3 and French (Azerty) keyboard.

### Steps to Reproduce
Couldn't find a pattern or steps to reproduce yet.

**Expected behavior:** When the period key is pressed, a period mark should be inserted on text.

**Actual behavior:** When the period key is pressed, the symbol '>' is placed instead.

### Versions
Atom: **v1.5.3**
APM: **v1.0.1**
NPM: **v2.5.1**
Node: **v0.10.35**
Python: **v2.7.6**
Git: **v1.9.1**

**Comment by 50Wliu** [comment] 2016-03-05 16:41
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.  As a workaround you can try installing the [keyboard-localization](https://atom.io/packages/keyboard-localization) package.

**Closed by 50Wliu** 2016-03-05 16:41 UTC

**Comment by mauricioklein** [comment] 2016-03-05 18:22
Thanks for the quick responde @50Wliu !
