### ISSUE TITLE
Very slow start up on windows

### ISSUE THREAD

**Issue by laolusrael** [atom/atom#9393] opened 2015-11-02 14:13 UTC
Atom very slow to start up on windows 10. 
That is a put off, as wonderful and editor as it is.
Speed is most important.

OS: Windows 10 Pro
RAM: 4Gb
Processor: Intel Core i3

**Comment by benogle** [comment] 2015-11-03 00:12
Closing as a dupe of https://github.com/atom/atom/issues/2654

**Closed by benogle** 2015-11-03 00:12 UTC
