### ISSUE TITLE
Matching Brackets 

### ISSUE THREAD

**Issue by jhudzik** [atom/atom#9089] opened 2015-10-08 18:18 UTC
Issue arises where brackets which are part of a string or regex match up with brackets that define blocks when the language type is set to JavaScript.

```function() {
    var regex = /\sibTplLoop='(.*?})'(.*?>)/;
};```

Opening bracket of function block will match closing bracket in regex. 

1.0.0 Ubuntu 14.04 and 1.0.19 Yosemite 10.10.5

**Comment by philipgiuliani** [comment] 2015-10-08 18:24
Hi, there are already a lot of issues open for this. Some of them are linked in the following issue: https://github.com/atom/atom/issues/3181
Please subscribe/comment to https://github.com/atom/bracket-matcher/issues/23 and close here!

**Comment by mnquintana** [comment] 2015-10-08 18:25
Thanks for the report! This looks like a duplicate of https://github.com/atom/bracket-matcher/issues/23 - please subscribe there for updates.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Comment by philipgiuliani** [comment] 2015-10-08 18:26
@mnquintana i was faster :smiley:

**Closed by mnquintana** 2015-10-08 18:25 UTC

**Comment by jhudzik** [comment] 2015-10-08 18:56
Thanks, guys ... I did try searching this issue before submitting. Must have missed it!
