### ISSUE TITLE
performance issue when replace 40,000 lines file

### ISSUE THREAD

**Issue by kevinzhow** [atom/atom#12427] opened 2016-08-15 07:30 UTC
### Description

performance issue when replace 40,000 lines file

### Steps to Reproduce

1.` wget https://haoel.github.io/downloads/dnsmasq.conf.add`
2. replace 114.114.114.114 to 8.8.8.8
3. click replace all

**Expected behavior:** 
replace within 2 second

**Actual behavior:** 

The atom will freeze

### Versions
1.9.8

**Comment by 50Wliu** [comment] 2016-08-15 14:37
This is a duplicate of atom/find-and-replace#653 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-15 14:37 UTC
