### ISSUE TITLE
Scroll bar change by scroll on other applications

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [atom/atom#19731] opened 2019-07-30 16:59 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When I move from Atom to any other application (E.x: Firefox) and scroll to up or down and come back to Atom and when hit first scroll (Mouse wheels change) it seems my scroll in Firefox was applied to Atom too.
This mean if I scroll down 5 times in Firefox and come back to Atom and trigger a mouse wheel event my 5 times scroll in Firefox was apply to Atom scroll bar.

### Steps to Reproduce

1. Open a scroll able file in Atom
2. Make some scroll in file
3. Go to another scroll able app, like Firefox or any other
4. Make some scroll in that application
5. Come back to Atom (Now everything is OK)
6. Just change scroll 1 time.

**Expected behavior:**

Of-course it should not be happen. The scroll should not be changed.

**Actual behavior:**

Other applications scroll changes was applied to Atom after one scroll change.

**Reproduces how often:**

Every time....
It happen every time for me. Even in safe-mode or in clean install...

### Versions

Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
OS : Linux Debian 4.9.0-9-amd64

**Comment by Aerijo** [comment] 2019-07-30 23:05
Sounds like https://github.com/atom/atom/issues/15482

**Comment by AmirHosseinKarimi** [comment] 2019-07-31 06:37
Thanks @Aerijo , Then I'll waiting for Electron 4.

**Comment by Aerijo** [comment] 2019-07-31 07:07
@AmirHosseinKarimi If possible, could you confirm in the other issue if https://atom.io/nightly does solve it?
_____
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15482. You may want to subscribe there for updates.

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by Aerijo** 2019-07-31 07:07 UTC
