### ISSUE TITLE
File Rename input box doesn't scroll if the filename is very long

### ISSUE THREAD

**Issue by elyseholladay** [atom/atom#10892] opened 2016-02-18 20:42 UTC
When renaming a file, if the filename is very long (too long to fit in the width of the Rename input box), the entire path will not show up and you can't horizontally scroll to see the end of the path.

For example:

1. Right click on a file in the sidebar and go to Rename
2. If the file is short, for example, `index.hbs` it will show in its entirety in the input box

<img width="882" alt="rename-short" src="https://cloud.githubusercontent.com/assets/685195/13156096/731a8e6c-d646-11e5-895d-49f0d193131d.png">

versus

1. Right click and go to Rename
2. If the filename is long, it will not show. You cannot right-arrow or select/move to get to the end of it.

![rename-long](https://cloud.githubusercontent.com/assets/685195/13156274/4e840c30-d647-11e5-85e5-c3b80320d4b6.gif)

You can delete part of the filename/path to shorten it enough to get the whole thing in the input box. You can still successfully rename the file.

Correct behavior should be that the input box will scroll horizontally as you arrow/select over the entire filename so you can see the whole path and edit it.

Version 1.5.3, OSX 10.11.3

**Comment by lee-dohm** [comment] 2016-02-18 20:53
This is a duplicate of https://github.com/atom/tree-view/issues/473. Please subscribe there for updates.

**Closed by lee-dohm** 2016-02-18 20:53 UTC
Labels: duplicate

**Comment by elyseholladay** [comment] 2016-02-18 20:54
apologies @lee-dohm, I searched over there too but just for "rename" "input length" and similar, and managed to miss that one. thanks!

**Comment by lee-dohm** [comment] 2016-02-18 20:58
You're welcome! I know that searching for these things is somewhat finicky :grinning:
