### ISSUE TITLE
C syntax highlight bugs in MD default syntax

### ISSUE THREAD

**Issue by Schweigert** [atom/atom#16288] opened 2017-11-28 16:37 UTC
Hi guys,

I found a little bug.
The for statement don't draw a blue 'f' character.

### SS

![image](https://user-images.githubusercontent.com/13274722/33331731-88e1ab06-d449-11e7-85dc-3cbff1c1b5a6.png)

### Versions

Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
ElementaryOS Loki 0.4.2

**Comment by rsese** [comment] 2017-11-28 19:00
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-gfm/issues/40. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-28 19:00 UTC
