### ISSUE TITLE
Cannot install atom package on Debian GNU/Linux where apmd is installed

### ISSUE THREAD

**Issue by eppesuig** [atom/atom#20434] opened 2020-02-19 20:31 UTC
Hello,
I just downloaded atom-amd64.deb from atom.io web site and tried to install it on a Debian "stretch" machine with command "sudo dpkg -i atom-amd64.deb". The installation failed because the package tried to install executable /usr/bin/apm while a different package already installed a different file with the same name; in fact, the file has been installed by "apmd" package.
The list of files in apmd package is here: https://packages.debian.org/stretch/amd64/apmd/filelist

So, I had to remove package apmd before installing atom package.

I understand that apmd was a quite old package and that it was installed on this machine a few Debian versions ago, but I still think you should list it in the "conflicts" list of the package "control" file.

Bye,
Giuseppe

**Comment by lee-dohm** [comment] 2020-02-20 17:10
Thanks for reaching out!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/3926. I'll bring up your suggestion to the developers.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2020-02-20 17:10 UTC
