### ISSUE TITLE
Setting cursor in redactor after choose file from tree.

### ISSUE THREAD

**Issue by pyvim** [atom/atom#9103] opened 2015-10-10 10:09 UTC
It would be convenient. For example, after choose file from tree I push `Ctrl+R` for searching function, but nothing happens because need click in redactor area.

**Comment by izuzak** [comment] 2015-10-12 11:07
Thanks for the feedback -- I think this is a duplicate of https://github.com/atom/atom/issues/3542, so I'm going to close this in favor of that issue. Please feel free to leave a comment there.

**Closed by izuzak** 2015-10-12 11:07 UTC
