### ISSUE TITLE
can't comment out <script> tags properly in html

### ISSUE THREAD

**Issue by hawsome** [atom/atom#7132] opened 2015-06-05 21:51 UTC
Whenever I try to `cmd + /` to comment `<script>` tags, it does the following:
```html
// <script ...
```
Instead of:
```html
<!-- <script ... -->
```

**Comment by 50Wliu** [comment] 2015-06-05 22:25
Duplicate of atom/language-html#4, please subscribe there for updates.

**Closed by 50Wliu** 2015-06-05 22:25 UTC
