### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by hieupm37** [atom/atom#7610] opened 2015-07-01 03:29 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\hieupm\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  4x -1:53.4.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -1:45.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:20.9.0 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
     -1:16.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:28.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:27.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:10 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "zenburn"
    ],
    "disabledPackages": [
      "atom-ctags"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "softTabs": false,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.1.0
linter-cpplint, v0.1.4
zenburn, v3.0.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment] 2015-07-01 04:35
Duplicate of https://github.com/atom/atom/issues/6548. Resolved in the next release of Atom.

**Closed by thomasjo** 2015-07-01 04:35 UTC
