### ISSUE TITLE
Copying Text from Preview Copies Full HTML Instead

### ISSUE THREAD

**Issue by mikehaytm** [atom/atom#8470] opened 2015-08-21 14:59 UTC
**Summary**
When working with markdown as a source type, and attempting to copy text from a preview of that markdown content, when I attempt to copy text from within a code block shown in the preview, I get the full html of the preview, instead of the plain text that appeared on screen.

**Configuration**
Mac OS 10.10.4 , Atom 1.0.7 , markdown-preview 0.150.0

**Steps**
1. Open a markdown file in Atom which contains code blocks delimited by three backticks (`)
2. Show the preview of the markdown using the standard markdown-preview (0.150.0) package
3. Select text shown within a code block in the preview pane, and copy
4. Paste into another editor (e.g. TextEdit, BBEdit)

**Expected Behavior**
I expected that when I copy/pasted the text from within the code block, I would get the plain text that I was seeing on screen.

**Problem Behavior**
Instead of being able to copy and paste text from within code blocks shown in markdown-preview, I get the entire html of the rendered markdown file.

**Comment by izuzak** [comment] 2015-08-21 15:01
Thanks for the report -- looks like a duplicate of https://github.com/atom/markdown-preview/issues/251, but let me know if I misunderstood.

**Closed by izuzak** 2015-08-21 15:01 UTC

**Comment by mikehaytm** [comment] 2015-08-21 15:02
Agreed. Same issue as 251.
