### ISSUE TITLE
Loss of subpixel AA on soft-wrapped line

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#16889] opened 2018-03-06 02:30 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is a followup to #16595.  I tried replacing `Math.ceil` with both `ceilToPhysicalPixelBoundary` and `roundToPhysicalPixelBoundary` but neither fixed the issue I'm seeing.

### Steps to Reproduce

1. Open a file that is soft-wrapped at the edge of the screen
2. On a new line, type characters until you are at the edge of the screen (i.e. right before soft-wrapping kicks in)

**Expected behavior:** Subpixel AA

**Actual behavior:** Subpixel AA is lost on the entire file

**Reproduces how often:** 100%

![soft-wrap-subpixel-aa-loss](https://user-images.githubusercontent.com/2766036/37011006-26558d76-20bc-11e8-8c5e-eebc1289d478.gif)
Sorry for the GIF quality.  Had some troubles with Licecap + Magnifier interaction.

### Versions

```
Atom    : 1.26.0-dev-e3a464ead
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### Additional Information

Refs #16595

/cc @as-cii

**Comment by 50Wliu** [comment] 2018-03-06 15:05
Can't believe I forgot to add that.  It's 1.5.

**Comment by lee-dohm** [comment] 2018-03-07 17:21
@Ben3eeE Can you repro this?

/cc @as-cii

**Comment by Ben3eeE** [comment] 2018-03-08 19:14
1. Open [text-editor.js](https://github.com/atom/atom/blob/2e19cf4a7c0a4d624b1f9c1072cd292de112cdb0/src/text-editor.js) in Atom
1. Copy the first 21 lines to a new untitled window
1. Turn on soft wrapping and change language mode to javascript
1. Resize the Window so it's soft wrapped
1. On line 15 type `a` until the you reach the end of the window

Master build on: https://github.com/atom/atom/commit/429f2bdd09bbdb226d5ff8648d7c069075f5961b

![subpixel aa loss softwrap](https://user-images.githubusercontent.com/1058982/37170628-a3901da0-230b-11e8-991e-c302db473eb3.gif)

**Comment by lee-dohm** [comment] 2018-03-08 19:48
Thanks very much @Ben3eeE :bow:

**Comment by revelt** [comment] 2018-03-09 07:57
White mice! It's Windows! I tried recreating this on Mac, no luck. It must be Windows-only issue. 

Did you notice, M$ have never really, completely, nailed the antialiasing; they were meant to with original Longhorn plan but didn't make it. Gates had just took the foot off the pedal back then. And since then the issue became fossilised.

**Comment by Ben3eeE** [comment] 2018-03-20 09:07
We merged https://github.com/atom/atom/pull/16943 which improves this but it's still possible to reproduce when the edit is very near the edge of the window.

/cc: https://github.com/atom/atom/pull/16943#issuecomment-372793413

**Closed** 2018-10-02 15:16 UTC
Labels: editor-rendering, more-information-needed
