### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/services/2checkoutService.ts'

### ISSUE THREAD

**Issue by kpgarrod** [atom/atom#6468] opened 2015-04-22 07:30 UTC
[Enter steps to reproduce below:]

1. Create a file named 2Checkout.ts
2. Rename file to checkOut.ts

I'm not sure if these are the steps (or which step) resulted in the error, but this is what I was doing at the time.

When the problem occurred, the ide opened hundreds of tabs. I was not able to work again until I had manually closed all the tabs.

I have noticed a couple of related(?) issues:
 
1. when I rename a file in the tree, a file with the new name is created but a file with the old name remains. This only happens if the file is open in the editor (e.g. if I left-click on the tree item, then right-click and rename). If I right-click on the tree-item and rename, the file is renamed correctly.  
2. When I delete the old file from the tree, the file remains open in the editor, but with the 'trashed' name.

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/admin/Documents/workspace/coachcommune/services/2checkoutService.ts'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/Users/admin/Documents/workspace/coachcommune/services/2checkoutService.ts'
  at Error (native)

```

### Commands

```
     -7:18 linter:lint (atom-text-editor.editor)
     -7:06.1.0 core:backspace (atom-text-editor.editor.mini)
     -7:05.8.0 core:confirm (atom-text-editor.editor.mini)
     -7:05.8.0 linter:lint (atom-text-editor.editor)
     -6:55.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-theme.theme-unity-ui)
  4x -4:20.8.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-theme.theme-unity-ui)
     -2:56.9.0 core:confirm (atom-text-editor.editor.mini)
     -2:24.1.0 core:backspace (atom-text-editor.editor.mini)
     -2:18.8.0 core:cancel (atom-text-editor.editor.mini)
  2x -1:52.5.0 core:confirm (atom-text-editor.editor.mini)
     -1:28.3.0 core:cut (atom-text-editor.editor)
     -1:21.9.0 core:paste (atom-text-editor.editor)
     -1:14.7.0 core:save (atom-text-editor.editor)
  2x -1:11.9.0 linter:lint (atom-text-editor.editor)
     -0:07.8.0 core:save (atom-text-editor.editor)
     -0:07.2.0 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "dracula-theme"
    ],
    "disabledPackages": [
      "sublime-tabs",
      "atomatigit",
      "autocomplete-paths",
      "autocomplete-html",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-sql",
      "language-xml",
      "dev-live-reload",
      "language-coffee-script",
      "language-csharp",
      "language-go",
      "language-toml",
      "project-manager",
      "merge-conflicts",
      "color-picker",
      "jumpy",
      "linter",
      "linter-tslint",
      "angularjs"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs-styleguide-snippets, v0.7.0
atom-beautify, v0.24.1
atom-typescript, v3.0.4
autocomplete-plus, v2.12.0
dracula-theme, v0.7.6
editorconfig, v0.3.3
emmet, v2.3.8
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-04-22 16:31
Did you rename the file from the tree view or outside of Atom?
This might be a duplicate of #6210.

**Comment by kpgarrod** [comment] 2015-04-23 05:28
From the tree-view.i was using the unity theme at the time. Have switched
back to a default theme and deleting and renaming seems to work correctly.
I  haven't experienced the issue again since switching.

**Closed** 2015-05-18 16:29 UTC
Labels: error-from-open, needs-reproduction, uncaught-exception
