### ISSUE TITLE
racer.racerBinPath is not set in your config.

### ISSUE THREAD

**Issue by battegoal** [atom/atom#11907] opened 2016-06-06 02:16 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

racer.racerBinPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -0:48.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:29 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-language-rust, v0.8.0
autocomplete-go, v1.1.0
builder-go, v1.0.0
go-config, v1.1.4
go-debug, v0.1.12
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
language-rust, v0.4.6
linter, v1.11.4
linter-rust, v0.4.6
navigator-godef, v1.0.3
racer, v0.20.0
rust-api-docs-helper, v0.5.1
tester-go, v1.0.4
tokamak-terminal, v0.1.1
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-06-06 11:51
This is a duplicate of edubkendo/atom-racer#61 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-06 11:51 UTC
