### ISSUE TITLE
Inside of an html tag opening and closing a script tag produces unwantde

### ISSUE THREAD

**Issue by JFusco** [atom/atom#2490] opened 2014-06-03 15:09 UTC
When closing a script tag </script> the editor automatically adds another "script" to the end - before the closing caret.  Screenshot attached.

![screen shot 2014-06-03 at 11 06 35 am](https://cloud.githubusercontent.com/assets/486049/3161971/fc6033be-eb30-11e3-8b8c-56a4785169af.png)

**Comment by benogle** [comment] 2015-01-19 22:43
@JFusco are you still having this issue? Do you have emmet installed? Please quit atom completely and run `atom --safe`. Is the issue still there?

**Comment by kevinsawicki** [comment] 2015-07-27 23:29
Closing this out, I'm unable to reproduce on Atom 1.0 and this hasn't been reported bumped in a long time.

**Closed by kevinsawicki** 2015-07-27 23:29 UTC
Labels: bug, more-information-needed
