### ISSUE TITLE
why tree view doesn't marked this as a git repo?

### ISSUE THREAD

**Issue by KSXGitHub** [atom/atom#10119] opened 2015-12-18 02:59 UTC
![image](https://cloud.githubusercontent.com/assets/11488886/11888233/f947d3b4-a56d-11e5-9275-b3f798a4a009.png)

**Comment by Zireael07** [comment] 2015-12-18 08:58
Because it isn't the project root? as far as I can see from the screenshot?

**Comment by KSXGitHub** [comment] 2015-12-18 10:33
@Zireael07 what's a "project root"? and why this isn't?

Full screenshot
![image](https://cloud.githubusercontent.com/assets/11488886/11894983/6d073468-a5ad-11e5-8bc7-d68cb8fdb29c.png)

**Comment by lee-dohm** [comment] 2015-12-18 16:49
This is a duplicate of https://github.com/atom/atom/issues/2203. Please subscribe there for updates. And thanks for reporting!

**Closed by lee-dohm** 2015-12-18 16:49 UTC
