### ISSUE TITLE
jquery.min.js cause hangs

### ISSUE THREAD

**Issue by fiftin** [atom/atom#6304] opened 2015-04-08 12:22 UTC
I have selected jquery.min.js (84Kb) in Tree View and Atom is hangs. But jquery.mobile.min.css (1 line 200Kb) does not cause hangs.
Version: 0.188.0

**Comment by mnquintana** [comment] 2015-04-08 12:44
Duplicate of #979

**Comment by izuzak** [comment] 2015-04-08 12:58
Thanks, @mnquintana. :bow: 

@fiftin Please subscribe to https://github.com/atom/atom/issues/979 for updates on this issue.

**Closed by izuzak** 2015-04-08 12:58 UTC
Labels: duplicate

**Comment by fiftin** [comment] 2015-04-09 07:41
Ok, thanks
