### ISSUE TITLE
Atom warns "Editor is not responding" when leaving right-click menu open

### ISSUE THREAD

**Issue by Ayase-252** [atom/atom#12981] opened 2016-10-14 09:48 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom warns "Editor is not responding" dialog when you leaving a right-click menu open for about 30 seconds.

![bug](https://cloud.githubusercontent.com/assets/6264033/19383305/319540c0-9236-11e6-8209-05e7d9c99ba5.gif)
(GIF is about 30 secs long.)

### Steps to Reproduce
1.  Open atom.
2.  Right click any position in Atom to pop up the menu.
3.  Leave menu open for about 30 second.

**Expected behavior:** It shouldn't warn "Editor is not responding." since it's responding to actions.

**Actual behavior:** It warns when editor is running normally.

### Versions
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

OS: Windows 10 Professional
Version: 1607
OS Version: 14393.222

**Comment by Ben3eeE** [comment] 2016-10-14 10:03
This is a duplicate of https://github.com/atom/atom/issues/11901 - feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-14 10:03 UTC
