### ISSUE TITLE
Atom forgets last window when reopened from commandline or file association

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8427] opened 2015-08-18 13:36 UTC
This is painful, and it happens to me on both OS X and Windows, on 1.0.7.

Atom is ~okay~ at remembering the window state when closed and reopened from the dock/shortcut. But using the `atom` command on a file or double-clicking a file and launching Atom via LaunchServices/Explorer makes it forget the previous window state, and worse yet Atom replaces the project folders with the folder of the selected file.

**Comment by izuzak** [comment] 2015-08-22 13:50
Hey, @alexchandel -- could you please provide the _exact_ steps which reproduce this problem, being as specific as possible about how you're starting and closing Atom? Providing steps on a specific example (e.g. two project you clone from GitHub) would be really helpful. An additional GIF which follows those steps and clearly demonstrates the problem would be :sparkles:. Just want to make sure what you're doing and what seems to be the problem and what you expected instead. Thanks!

**Comment by alexchandel** [comment] 2015-10-14 20:15
Assuming a fresh Atom installation, OS X, a `.txt` file association to Atom, and a file hierarchy in `~/project/`:

0. Open fresh Atom.
1. Add project folder `~/project` to the blank window.
2. Open tabs for `~/project/foo.txt` and `~/project/bar.txt`
3. *Let this window be called "Houdini"*
4. Quit Atom with "Houdini" open.
5. Double-click `~/project/baz/biz.txt` in Finder (the system's file explorer)
6. *Atom opens*
7. "Houdini" has vanished, and Atom now creates a window whose project folder is `~/project/baz/`

Let's make it even better. Assuming a Wine installation in `~/.wine/`, and a `.reg` file association to Atom:

0. Do the first 5 steps from above.
1. Double-click `~/.wine/system.reg` in Finder
2. *Atom opens*
3. Not only has "Houdini" vanished, but Atom has decided to create a project folder for `~/.wine/`, immediately going to 100% CPU usage and melting my computer as it tries to index all 6,000,000 files in my Windows install.

Internet-Explorer-tier infuriating.

**Comment by maxbrunsfeld** [comment] 2015-10-14 20:23
> going to 100% CPU usage and melting my computer as it tries to index all 6,000,000 files in my Windows install

I think this is a separate issue; subscribe to https://github.com/atom/atom/issues/6437 for updates on this problem.

**Comment by alexchandel** [comment] 2015-10-14 20:39
@maxbrunsfeld seems like that is the direct cause of the 100% CPU usage. But in this case, this issue is indirectly triggering it. If Atom hadn't forgotten "Houdini", nor replaced it with a blank new window and a new Project Folder, we wouldn't be indexing a massive folder.

**Comment by izuzak** [comment] 2015-11-09 12:22
@maxbrunsfeld I was able to reproduce the behavior described in the steps 1-8 in https://github.com/atom/atom/issues/8427#issuecomment-148182581. I'm still not sure I understand what the expected behavior is for all of these cases. Could I trouble you for help one more time? Also, do you think it would be helpful if we had documentation on this, so that users know which behavior is expected and which isn't? (I sure would find it helpful. :sweat_smile:) Thanks!

**Comment by franciscop** [comment] 2015-11-29 15:18
Another point of view is mine. I have known of this bug for ages. What I try to do is never to open a file by double clicking. But the really unexpected behaviour for me is when opening a file by double clicking:

- If Atom is already opened, it opens the file with no problem nor issue
- If Atom is closed, this issue occurs

So you need to know whether you left Atom open or not when opening a file because then there'll be two really different behaviors. I think the expected behavior should be that if Atom is closed, it opens the previous state AND opens the file (similar to the first case). This gives Atom more predictability, which is really important for production.

**Comment by nem75** [comment] 2015-12-15 16:27
@izuzak The expected behavior (in my case at least) would be for Atom to open the file clicked in Finder (or passed on the command line) **in addition** to everything it had open before, no matter if Atom is already running or not.

At the very least it should not discard all projects in the tree view. Which it does, if opening a file by clicking and Atom not currently running.

**Comment by hellerbarde** [comment] 2016-09-21 10:59
Can we finally fix this? I have recently lost some work (I'm not blaming anyone) to this. This is unfortunate. 

My argument: If atom provides the Sublime-like functionality of remembering unsaved files/tabs, it should NEVER lose data just due to this confusing behaviour. (Or provide a way to restore the lost content from a backup folder somewhere)

So either we remove the "magically save dirty tabs" feature or we fix this bug. Please? 
I am willing to help, if I someone can point me in the vaguelly right direction. (is this an electron bug? is this an atom core bug? a plugin? if so, which one?)

**Comment by maxbrunsfeld** [comment] 2016-09-21 18:16
I believe this is the same issue described in https://github.com/atom/atom/issues/9643. I'm going to close this one because there is more discussion on that issue. Please subscribe to #9643 for updates.

Also, see [my comment](https://github.com/atom/atom/issues/9643#issuecomment-234676046) for some context regarding this issue. TLDR - This is currently the expected behavior, and I believe the right solution is to add some notion of 'recent projects' to Atom.

**Closed by maxbrunsfeld** 2016-09-21 18:16 UTC
Labels: atom, documentation, feedback
