### ISSUE TITLE
crash when duplicate a file

### ISSUE THREAD

**Issue by hbkfabio** [atom/atom#4920] opened 2015-01-08 14:43 UTC
Steps for reproduce:

> Open atom
> Open folder with source code
> Select any source file from trreview
> rigth click and duplicate file
> crash

I am using Fedora 21 and atom version is 0.168.0

Here the output:

[fabio@ironhide ~]$ /usr/bin/atom: line 92: 10917 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$DOT_ATOM_DIR/nohup.out" 2>&1
[10917:0108/113744:ERROR:browser_main_loop.cc(163)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
libGL error: MESA-LOADER: could not create udev device for fd 12
libGL error: MESA-LOADER: could not create udev device for fd 12
ATTENTION: default value of option force_s3tc_enable overridden by environment.
App load time: 278ms
[10970:0108/113745:INFO:renderer_main.cc(207)] Renderer process started
[10917:0108/113746:INFO:CONSOLE(92)] "Download the React DevTools for a better development experience: http://fb.me/react-devtools", source: /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/React.js (92)
[10917:0108/113747:INFO:CONSOLE(64)] "Window load time: 1968ms", source: file:///usr/share/atom/resources/app/static/index.js (64)
Crash dump id: 9cee5385-744a-4d2f-b907-388b21ff66d5

**Comment by lee-dohm** [comment] 2015-01-08 15:50
Related issues: #4388 #4892

**Comment by kevinsawicki** [comment] 2015-01-08 18:31
Can you try upgrading to 0.169?

**Comment by mnquintana** [comment] 2015-06-17 00:37
Since this is an old version of Atom (built on the old React editor), I'm going to close this out. Feel free to comment / reopen if you can reproduce this with the latest version of Atom (0.209.0).

**Closed by mnquintana** 2015-06-17 00:37 UTC
Labels: bug, crash, linux
