### ISSUE TITLE
Uncaught Can't find body file

### ISSUE THREAD

**Issue by MarToxAk** [atom/atom#18911] opened 2019-02-26 06:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find body file

```
At C:\Users\MarTox Gamer Work\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

undefined
```

### Commands

```
     -0:07.9.0 emmet:encode-decode-data-url (input.hidden-input)
```

### Non-Core Packages

```
emmet 2.4.3 
```

**Comment by rsese** [comment] 2019-02-26 06:38
Thanks for contributing!

We noticed that this looks like a duplicate of issues like https://github.com/atom/atom/issues/18429 where it seems like the problem was narrowed down to https://atom.io/packages/emmet (/cc https://github.com/atom/atom/issues/18429#issuecomment-439216378).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-26 06:38 UTC
