### ISSUE TITLE
Windows 10 home version crash on start 

### ISSUE THREAD

**Issue by readpan** [atom/atom#17553] opened 2018-06-22 02:36 UTC
### Description
Windows 10 home version crash on start 
[Description of the issue]
Install the newest version 1.28.0 For Windows-64bit
### Steps to Reproduce

1. Double click icon.
2. IDE appear.
3. It disappeared after 5 seconds.
4. There is not anything crash report dialog or something.

### Versions
1.28.0

**Comment by thomasjo** [comment] 2018-06-22 12:18
I'm closing this as a duplicate of #17557. Please subscribe there for updates.

**Closed by thomasjo** 2018-06-22 12:18 UTC
