### ISSUE TITLE
Find returning old results

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#8509] opened 2015-08-25 21:10 UTC
I had a problem with find in project.  It was stuck returning results for an old word, "currentPage".  You can see at the top of the screen cap that it was supposed to show "watch".  It kept showing "currentPage"  no matter what I tried.  Reloading atom fixed it.  I have only had this happen once and I'll try to give a better report if it happens again.

![screenshot 2015-08-25 at 2 04 28 pm](https://cloud.githubusercontent.com/assets/811455/9479460/6348a3ba-4b32-11e5-9c65-21725132d4c6.png)

Atom 1.0.7.
Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

**Comment by mnquintana** [comment] 2015-08-25 21:12
Thanks for the report! This looks like a duplicate of https://github.com/atom/find-and-replace/issues/492 though, which has been fixed for the next release of Atom (1.0.8).

**Closed by mnquintana** 2015-08-25 21:12 UTC
