### ISSUE TITLE
Settings button after package update not working

### ISSUE THREAD

**Issue by arcticicestudio** [atom/atom#6994] opened 2015-05-28 18:52 UTC
When updating one or more packages the "Settings" button won't work anymore.
I came across this issue some time ago when i wanted to read the changelog of the updated package, so i can't really say in which version i first experienced this.
Actually using `0.200.0`, also tried in `--safe` mode, same result.

It's a bit difficult to reproduce the issue as you need updateable package, so here's a anim do demonstrate:
![screencast](http://i.imgur.com/C3gnmLe.gif)

**Comment by mnquintana** [comment] 2015-05-28 18:56
Thanks for the report! This is a duplicate of https://github.com/atom/settings-view/issues/499 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-28 18:56 UTC
