### ISSUE TITLE
Focusing Atom will show a progress cursor

### ISSUE THREAD

**Issue by julmot** [atom/atom#11132] opened 2016-03-11 11:47 UTC
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [ ] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)? 1.5.3
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

When focusing the Atom window a progress cursor appears (even if there is no visible action running).
![screen](https://cloud.githubusercontent.com/assets/8310677/13701283/3913594a-e787-11e5-8fea-5c3fe4067f27.gif)
### Steps to Reproduce
1. Focus Atom
2. Focus another window
3. Focus Atom again

**Expected behavior:** No progress icon

**Actual behavior:** Progress icon
### Versions

Atom: 1.5.3
Windows: 7

**Comment by julmot** [comment] 2017-09-12 20:19
LOL. Why is this issue closed without any comment?

**Comment by 50Wliu** [comment] 2017-09-12 20:33
Sorry about that @julmot!  The bot's been having some rate limiting issues that occasionally prevented it from issuing a warning comment.

**Comment by 50Wliu** [comment] 2017-09-12 20:33
That said, is this still reproducible on the latest release, Atom 1.20.0?

**Comment by julmot** [comment] 2017-09-12 20:46
I'm sorry but I've switched to PHPStorm some time ago. But, as far as I can remember, the issue only came up on a USB 3.0 stick. So, it was probably caused by Atom that tried to load something everytime the editor was focused.

**Comment by 50Wliu** [comment] 2017-09-12 20:56
Ok.  Since there haven't been any more reports of this issue I'm going to close it, since there's been a lot of changes since Atom 1.5.3.  That said, if anyone can reproduce this, I'd be more than happy to reopen it.

**Closed by 50Wliu** 2017-09-12 20:56 UTC
Labels: feedback
