### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/my-dev/js/megusta/megusta-frontend/mc-web-client/mc-web-client/vendor/modules/chat-api-core/config/stages.coffee'

### ISSUE THREAD

**Issue by Matrosskin** [atom/atom#6530] opened 2015-04-27 08:40 UTC
1. Open directory in Atom. Directory is under git.
2. Open file1.coffee in editor tab.
3. In Linux console checkout another git branch where file1.coffee is absent.
4. Now in atom you should see error message

**Atom Version**: 0.194.0
**System**: linux 3.19.0-12-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/my/file/path/file1.coffee'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/my/file/path/file1.coffee'
  at Error (native)

```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "select-scope",
      "language-ruby-on-rails",
      "git-diff-details"
    ]
  },
  "editor": {
    "fontSize": 21,
    "showInvisibles": true,
    "showIndentGuide": true,
    "preferredLineLength": 120,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-grails, v0.1.0
autocomplete-plus, v2.12.0
editorconfig, v1.0.0
highlight-selected, v0.9.2
language-hjson, v0.2.0
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-htmlhint, v0.0.13
linter-jshint, v0.1.2
word-jumper, v0.2.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-04-27 11:05
Duplicate of #6210 - please subscribe there for updates.

**Closed by mnquintana** 2015-04-27 11:05 UTC
