### ISSUE TITLE
AltGr is not Alt

### ISSUE THREAD

**Issue by ortreum** [atom/atom#12374] opened 2016-08-09 16:50 UTC
Hello,

it might only be a problem of a de-de keyboard but if I can not press AltGr+ß then I can not get a \. You need \ for namespaces in PHP. There is no easy way to deactivate alt-\-keybinding. I've read the CSON manual but couldn't find a clue how to do "nothing" on a keybinding.
For me Atom is useless unless this is not solved.

**Comment by lee-dohm** [comment] 2016-08-09 16:56
This is a duplicate of https://github.com/atom/atom-keymap/issues/35. You may want to subscribe there for updates. Additionally, some people have reported good results from using the [keyboard-localization package](https://atom.io/packages/keyboard-localization).

**Closed by lee-dohm** 2016-08-09 16:56 UTC
