### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 307Error: Cannot cal...

### ISSUE THREAD

**Issue by misode** [atom/atom#19105] opened 2019-04-04 18:08 UTC
**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 307
Error: Cannot call function 'getPosition' on missing remote object 307
    at throwRPCError (C:\Users\misoloo\AppData\Local\atom\app-1.35.1\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\misoloo\AppData\Local\atom\app-1.35.1\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\misoloo\AppData\Local\atom\app-1.35.1\resources\electron.asar\browser\api\web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At C:\Users\misoloo\AppData\Local\atom\app-1.35.1\resources\electron.asar\renderer\api\remote.js:221

Error: Cannot call function 'getPosition' on missing remote object 307
Error: Cannot call function 'getPosition' on missing remote object 307
    at throwRPCError (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at Object.exception (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:125:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:1:683538)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:1:683953)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:286221)
```

### Commands

```
```

### Non-Core Packages

```
auto-indent 0.5.0 
charcode-display 0.2.1 
ftp-remote-edit 0.12.19 
Hydrogen 2.8.0 
mcfunction 0.6.4 
mcfunction-plus 0.1.0 
open-on-bitbucket 0.5.0 
remote-ftp 2.2.2 
remote-sync 4.1.8 
Sublime-Style-Column-Selection 1.7.5 
teletype 0.13.3 
terminal-plus 0.14.5 
```

**Comment by rsese** [comment] 2019-04-04 18:26
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-04 18:26 UTC
