### ISSUE TITLE
Crashes bug on MAC OS with Proxy

### ISSUE THREAD

**Issue by arthurkiller** [atom/atom#17567] opened 2018-06-23 07:57 UTC
macos 10.13.5
atom 1.28.0
proxy: shadowsock-NG 1.7.1 with auto PAC mode

-------

Can you guys fix crash bugs on atom? 
Those problem really got me tired since 1.25 version.

**Comment by Bignan** [comment] 2018-06-23 08:37
atom sucks

**Comment by Bignan** [comment] 2018-06-23 08:38
already uninstall

**Comment by thomasjo** [comment] 2018-06-23 12:00
Duplicate of #17557.

**Closed by thomasjo** 2018-06-23 12:00 UTC
