### ISSUE TITLE
RPI

### ISSUE THREAD

**Issue by ender-music** [atom/atom#20244] opened 2019-12-16 01:05 UTC
## Summary

Why can't we use this on a raspberry pi?

## Motivation

I only own a raspberry pi, and atom is what I see all the pros using, so I want to use it.

## Describe alternatives you've considered

Not a single one.

## Additional context

No additional context. Please get working on ARM.

**Comment by Arcanemagus** [comment] 2019-12-16 18:05
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15881. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-12-16 18:05 UTC

**Comment by ender-music** [comment] 2019-12-16 18:12
If you guys respond, I'm new to GitHub, so I didn't know how to do nothing.
If possible, I would like you to make it possible to run Atom on raspberry
pi's.

**Comment by RaspberryPiFan** [comment] 2019-12-22 16:36
@ender-music I'm creating a fork for the Raspberry Pi. I can tell you when it's finished.

**Comment by foxybislut69** [comment] 2019-12-26 22:04
Unsubscribe me please

To You From Mee With Love & Kisses

& Please be patient with me I will be betterSoon 4 My Babies xxxx


On 16 Dec 2019, at 18:07, Landon Abney <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15881<https://github.com/atom/atom/issues/15881>. You may want to subscribe there for updates.

Because we treat our issues list as the Atom team's backlog<https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog>, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide<https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute>.
