### ISSUE TITLE
Improve Command-W behavior on OS X

### ISSUE THREAD

**Issue by cesarandreu** [atom/atom#7726] opened 2015-07-06 05:32 UTC
OS X 10.10.4
Atom 1.0

When you no longer have open tabs, pressing Command-W should close the front window and focus the next unminimized window, if there are any.

This is how Sublime Text 3 behaves. Google Chrome also behaves similarly, except that they do it when you have a single open tab. Pressing Command-W when you have a single open tab will close the window and shift focus to the next open window unless it's minimized.

Originally posted in #7428.

**Comment by mnquintana** [comment] 2015-07-06 10:56
Thanks for the suggestion! This is a duplicate of https://github.com/atom/atom/issues/863 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-06 10:56 UTC
