### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by juhee3403** [atom/atom#16318] opened 2017-12-04 16:39 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2269

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2258:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2251:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:400:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:278:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:09.0 core:cancel (input.hidden-input)
     -0:08.8.0 editor:consolidate-selections (input.hidden-input)
     -0:08.8.0 core:cancel (input.hidden-input)
     -0:08.3.0 editor:consolidate-selections (input.hidden-input)
     -0:08.3.0 core:cancel (input.hidden-input)
     -0:08.1.0 editor:consolidate-selections (input.hidden-input)
     -0:08.1.0 core:cancel (input.hidden-input)
     -0:07.9.0 editor:consolidate-selections (input.hidden-input)
     -0:07.9.0 core:cancel (input.hidden-input)
     -0:07.7.0 editor:consolidate-selections (input.hidden-input)
     -0:07.7.0 core:cancel (input.hidden-input)
     -0:07.0 editor:consolidate-selections (input.hidden-input)
     -0:07.0 core:cancel (input.hidden-input)
     -0:06.8.0 editor:consolidate-selections (input.hidden-input)
     -0:06.8.0 core:cancel (input.hidden-input)
     -0:05.9.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-html-preview 0.2.5 
emmet 2.4.3 
highlight-column 0.5.4 
script 3.17.3 
```

**Comment by rsese** [comment] 2017-12-04 19:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15263. You may want to subscribe there for updates - if you can share any details about what you were doing when you saw the error, please let us know in https://github.com/atom/atom/issues/15263!

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-04 19:20 UTC
