### ISSUE TITLE
Keymap win32.json collision

### ISSUE THREAD

**Issue by csholmq** [atom/atom#10087] opened 2015-12-16 14:27 UTC
With ccccc9657c7f9f6ecfb161da6a850b770348391d my keymap (Swedish) now have a collision which means I can't type backslash (\\).

    "atom-workspace atom-pane": {
      "ctrl-alt-=": "pane:increase-size",
      "ctrl-alt--": "pane:decrease-size"
    },

The culsprit (ctrl-alt-= in the keymap) is unfortunately mapped/triggered by me pressing ctrl-alt-+ which *should* produce backslash.

![image](https://cloud.githubusercontent.com/assets/1297882/11843343/6b3db878-a409-11e5-8c21-a24f7e1790de.png)

This should be true for german keyboards as well from what I can see.

I temporarily fixed this with

    "atom-workspace atom-pane":
      "ctrl-alt-=": "unset!"

I believe the keymaps could benefit from some localization. E.g that the *tree-view:toggle* is actually triggered by ctrl-§ on my keyboard and not what's written in the keymap (ctrl+\).

**Comment by mnquintana** [comment] 2015-12-16 15:04
Thanks for the report! I think this is a duplicate of https://github.com/atom/atom-keymap/issues/37 – let me know if I'm misunderstanding though!

**Closed by mnquintana** 2015-12-16 15:04 UTC

**Comment by csholmq** [comment] 2015-12-16 15:24
Perfect, thanks!
