### ISSUE TITLE
Sometimes tree view looks broken.

### ISSUE THREAD

**Issue by mirek** [atom/atom#7737] opened 2015-07-06 19:44 UTC
![image](https://cloud.githubusercontent.com/assets/8561/8531480/1376fda6-23fe-11e5-9f72-8d1c4f6a446e.png)

Clicking on the tree view refreshes directory which becomes readable again.

**Comment by mnquintana** [comment] 2015-07-06 19:47
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/4924 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-06 19:47 UTC
