### ISSUE TITLE
Uncaught Error: The element has already been freed!

### ISSUE THREAD

**Issue by hyonzin** [atom/atom#13869] opened 2017-02-23 13:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The element has already been freed!

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/dom-element-pool.js:83

Error: The element has already been freed!
    at DOMElementPool.module.exports.DOMElementPool.free (/app.asar/src/dom-element-pool.js:83:15)
    at DOMElementPool.module.exports.DOMElementPool.freeElementAndDescendants (/app.asar/src/dom-element-pool.js:63:12)
    at LinesTileComponent.removeLineNode (/app.asar/src/lines-tile-component.js:84:25)
    at LinesTileComponent.updateLineNodes (/app.asar/src/lines-tile-component.js:111:14)
    at LinesTileComponent.updateSync (/app.asar/src/lines-tile-component.js:73:10)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/app.asar/src/tiled-component.js:55:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/app.asar/src/tiled-component.js:18:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/app.asar/src/text-editor-component.js:264:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/app.asar/src/text-editor-component.js:196:12)
    at /app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/app.asar/src/view-registry.js:219:9)
    at /app.asar/src/view-registry.js:3:59
```

### Commands

```
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.4.6 
atom-typescript 10.1.6 
cursor-blink-interval 0.3.1 
es6-javascript 1.0.0 
javascript-snippets 1.2.1 
language-scala 1.1.6 
linter 1.11.16 
linter-gcc 0.6.15 
linter-pylama 0.5.7 
linter-python 3.0.5 
python-tools 0.6.8 
```

**Comment by 50Wliu** [comment] 2017-02-23 14:32
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #13377. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-23 14:32 UTC
