### ISSUE TITLE
Uncaught Error: spawn /Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5...

### ISSUE THREAD

**Issue by dgilliam** [atom/atom#10482] opened 2016-01-18 22:24 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getPosition] (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:574:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeDefaultWindowDimensions (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:607:25)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:181:35)
    at /Users/dgilliam/Library/Application Support/com.github.atom.ShipIt/update.5Md5MuQ/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2016-01-18 22:32
Thanks for the report! This looks like a duplicate of #9559 though – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-18 22:32 UTC
