### ISSUE TITLE
Tooltips are displaced from where they should be

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18395] opened 2018-11-04 20:02 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I haven't used Atom for a while, but I started again 8 months ago, and since then atom-ide-ui and linter-ui-default tooltips have always been positioned erroneously.

I haven't tried safe mode, as then the packages are disabled and so I don't have the tooltips.

F.e., here's a screenshot showing a tooltip from the `linter-ui-default` package far away from the mouse cursor (I am hovering over the red-underlined `function log()`:

<img width="1225" alt="screen shot 2018-11-04 at 11 58 34 am" src="https://user-images.githubusercontent.com/297678/47969218-fba4df00-e028-11e8-878b-1c455df7db7c.png">

The offset appears to be the same for tooltips generated by the `atom-ide-ui` package, so it lead me to believe they are using the same API, which I'm guessing is part of Atom's built-in overlay API.

### Steps to Reproduce

Here's the version of everything I have installed, then it happens with the tooltips 100% of the time:

<details>
  <summary>debug info with package info</summary>

```json
{
  "atom": "1.32.0",
  "platform": "darwin",
  "release": "18.0.0",
  "vmpVersion": "1.35.0",
  "vmpConfig": {},
  "activeCommunityPackages": [
    "language-javascript-jsx: 0.3.7",
    "atom-material-syntax: 1.0.8",
    "aligner-javascript: 1.3.0",
    "atom-domterm: 0.6.0",
    "atom-vim-like-tab: 1.5.2",
    "autocomplete-modules: 2.2.2",
    "autocomplete-paths: 2.12.2",
    "better-git-blame: 0.4.7",
    "busy-signal: 1.4.3",
    "docblockr: 0.13.7",
    "emmet: 2.4.3",
    "ex-mode-sort: 1.0.0",
    "file-icons: 2.1.21",
    "file-watcher: 1.2.6",
    "git-plus: 8.1.0",
    "hey-pane: 1.1.0",
    "highlight-line: 0.12.0",
    "highlight-selected: 0.13.1",
    "hyperclick: 0.1.5",
    "imdone-atom: 2.4.29",
    "indent-guide-improved: 1.4.13",
    "intentions: 1.1.5",
    "keystroke: 0.4.0",
    "linter: 2.2.0",
    "linter-eslint: 8.4.1",
    "linter-ui-default: 1.7.1",
    "linter-ui-plus: 0.3.2",
    "minimap: 4.29.8",
    "minimap-bookmarks: 0.4.2",
    "minimap-git-diff: 4.3.1",
    "minimap-highlight-selected: 4.6.1",
    "minimap-linter: 2.2.1",
    "minimap-pigments: 0.2.2",
    "minimap-quick-highlight: 1.0.1",
    "pigments: 0.40.2",
    "prettier-atom: 0.55.2",
    "project-plus: 1.0.0",
    "quick-highlight: 0.13.0",
    "split-diff: 1.4.0",
    "teletype: 0.13.2",
    "todo-show: 2.3.0",
    "trailing-spaces: 0.4.0",
    "tree-view-git-status: 1.5.0",
    "vim-mode-plus: 1.35.0",
    "vim-mode-plus-keymaps-for-surround: 0.2.1",
    "editorconfig: 2.2.2",
    "language-jenkinsfile: 0.1.1",
    "language-pug: 0.0.22",
    "language-vue: 0.23.1",
    "atom-typescript: 12.6.3",
    "ex-mode: 0.18.0"
  ]
}
```

</details>

**Expected behavior:**

Tooltips should be next to the cursor, Or next to the part of the line (below) where the note is regarding.

**Actual behavior:**

The tooltips are displaced.

It gets worse depending on pane split configuration (the offset varies depending on orientation and size of pane splits.

**Reproduces how often:** 

100% of the time.

### Versions

See above

### Additional Information

What else can I do to help find the problem?

**Comment by trusktr** [comment] 2018-11-04 20:35
For fun!

![spin](https://user-images.githubusercontent.com/297678/47969560-20e81c00-e02e-11e8-905a-b9968f42b30d.gif)

**Comment by rsese** [comment] 2018-11-05 20:48
Thanks for the report!

> Aha! It appears that my custom stylesheet is the culprit, and the styling is causing the overlay system to calculate incorrect positions.

Ahhh ok, thanks for tracking this down :+1:

> From this, it seems that the overlay needs to calculate the position of the overlays taking into consideration CSS transforms. Granted, not many people have this type of stuff in their style sheet! 😄

😄 - since the issue is related to custom styles you had set we'll go ahead and close this but we'll share your note with the team as feedback to consider.

> For fun!

That's pretty neat 😄

**Closed by rsese** 2018-11-05 20:48 UTC
