### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat 'I:/'

### ISSUE THREAD

**Issue by zoubert** [atom/atom#18690] opened 2019-01-14 13:16 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat 'I:\'

```
At fs.js:1621

Error: EPERM: operation not permitted, lstat 'I:\'
    at Proxy.realpathSync (fs.js:1621:13)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at atom.project.getPaths.map.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:788946)
    at Array.map (<anonymous>)
    at Object.startTask (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:788937)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:186974)
    at get_process.nextTick (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:185036)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2019-01-14 23:05
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/fuzzy-finder/issues/289 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-01-14 23:05 UTC
