### ISSUE TITLE
key-mappings with `alt` don't suppress Mac OS composition characters anymore (atom-1.19)

### ISSUE THREAD

**Issue by despairblue** [atom/atom#15189] opened 2017-08-08 16:20 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Shortcuts with alt don't suppress Mac OS composition characters.

### Steps to Reproduce

With `ABC - Extended` keyboard layout:

1. `Open Your Keymap`
2. Add the following keymaps:
```
# general
'atom-text-editor':
  # use jkl; vim-like when pressing alt (word by word, paragraph by paragraph)
  # or alt (letter by letter)
  'alt-h': 'core:move-left'
  'alt-j': 'core:move-down'
  'alt-k': 'core:move-up'
  'alt-l': 'core:move-right'
```
3. save
4. try to use them

With `US` keyboard layout /cc https://github.com/atom/atom/issues/15189#issuecomment-321503095.

**Expected behavior:** [What you expect to happen]

A GIF from atom-1.18

![atom-1 18](https://user-images.githubusercontent.com/927609/29082497-f96e7ebc-7c65-11e7-913e-9f6d394c2d36.gif)

**Actual behavior:** [What actually happens]

A GIF from atom-1.19

![atom-1 19](https://user-images.githubusercontent.com/927609/29082512-04686558-7c66-11e7-8016-8fbe979c1da3.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always.

### Versions

* **Atom:**       1.19.0-beta7
* **Atom-Shell:** 
* **OS:**         Mac OS X 10.12.5
* **Misc**
    * apm  1.18.2
    * npm  3.10.10
    * node 6.9.5 x64
    * python 2.7.10
    * git 2.11.0

### Additional Information

Probably only happens on Mac OS.

**Comment by rsese** [comment] 2017-08-08 22:38
Hmmm, I gave this a try on 1.19.0-beta7 but can't reproduce - tagging as needs repro for now.

Also about your steps to reproduce, based on your GIFs, seems like this:

> 'alt-shift-J': 'block-travel:move-down'
> 'alt-shift-K': 'block-travel:move-up'

should be this?

> 'alt-shift-J': 'core:move-down'
> 'alt-shift-K': 'core:move-up'

**Comment by despairblue** [comment] 2017-08-09 08:15
@rsese sorry I copied the wrong keymaps (the shortcuts as well as the commands), I updated the original post. :smile: 

Thanks for pointing that out. Could you try again with that setup?

**Comment by rsese** [comment] 2017-08-09 20:04
Np thanks :+1:  I tried with the updated keybindings and it still works ok for me with the latest releases (1.19.0 and 1.20.0-beta0).  Have you tried with the latest versions that went out yesterday?

**Comment by despairblue** [comment] 2017-08-10 09:27
@rsese Thanks for your time. I just tested both and the characters are still not suppressed when a key mapping is triggered.

Are you testing this on a Mac? What keyboard layout are you using? I'm using `ABC - Extended` and pressing `alt-{h,j,k,l}` leads to `ˍ˝˚-` being printed in input fields like this textedit on github.

Problem is that they used to be suppressed if a key mapping is triggered, probably by something like `event.preventDefault()` which would lead to the key event not propagating to the system, but since the C++ editor buffer implementation this does not happen anymore and the event is propagated to the system no matter what.

**Comment by despairblue** [comment] 2017-08-10 09:39
I changed my layout to `US - International` and now it works. I think the difference is that now `alt-{h,j,k,l}` are not mapped to composition characters anymore: `∆˚¬…`

I can reproduce this with this mapping using a US layout:

```
  'alt-u': 'core:move-down'
```

`alt-u` is used for creating umlaute like ü, ä, ö.

**Comment by Ben3eeE** [comment] 2017-08-10 09:51
Related: https://github.com/atom/atom-keymap/issues/190

**Comment by rsese** [comment] 2017-08-10 21:36
Ahhh yes, I'm using `US` layout and I can reproduce with `alt-u` like you described.

Just to confirm, do you think this is its own issue @Ben3eeE vs. a dupe of https://github.com/atom/atom-keymap/issues/190?

**Comment by Ben3eeE** [comment] 2017-08-11 06:12
I think this is it's own issue. Just referencing it because both issues are about `alt-` variants on macOS inserting the character when it should not.

I can not reproduce this on Windows using `AltGraph` modified bindings.

**Comment by despairblue** [comment] 2017-08-11 07:51
Thanks for helping to reproduce this 🙂 

Then I think the `needs-reproduction` label can be removed.

**Comment by despairblue** [comment] 2017-08-15 10:33
@nathansobo Thanks for the work around, sadly this only prevents the composition character from being rendered, it will still compose:

![alt composition](https://user-images.githubusercontent.com/927609/29312458-aef82e96-81b5-11e7-9f32-13106eeb8abc.gif)


## Versions

* **Atom:**       1.19.1
* **Atom-Shell:** 
* **OS:**         Mac OS X 10.12.5
* **Misc**
    * apm  1.18.4
    * npm  3.10.10
    * node 6.9.5 x64
    * python 2.7.10
    * git 2.11.0

**Closed** 2017-08-15 16:13 UTC
Labels: mac, regression, triaged
