### ISSUE TITLE
Automatically rename untitled tabs

### ISSUE THREAD

**Issue by huyndnse63331** [atom/atom#19942] opened 2019-09-22 04:57 UTC
## Summary

Hi, i was Sublime's user, and now i'm using Atom as my main editor. I would like to suggest a feature like Sublime's, the editor will automatically rename untitled (unsaved) tabs.

## Motivation

This feature actually helps people who like writing down notes a lot, easier to organize and find their notes in their editor based on beginning words to be set as tab title like below.

![095](https://user-images.githubusercontent.com/25204246/65382456-f7141280-dd2f-11e9-9e74-9d31ff98caf7.png)

**Comment by rsese** [comment] 2019-09-30 20:40
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/18978 - as mentioned in https://github.com/atom/atom/issues/18978#issuecomment-472523478, it looks like there's a package that provides the functionality you're looking for.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-09-30 20:40 UTC
