### ISSUE TITLE
Uncaught Error: Tried to unload active package 'hyperclick-love'

### ISSUE THREAD

**Issue by mdbuff** [atom/atom#18939] opened 2019-03-03 23:15 UTC
[Enter steps to reproduce:]

1. ...Clicked on install for Hyperclick-love
2. ...

**Atom**: 1.34.0 ia32
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Education
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'hyperclick-love'

```
At C:\Users\Michael\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

Error: Tried to unload active package 'hyperclick-love'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:381493)
    at PackageManager.t.exports.PackageManager.unload (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:898586)
    at PackageManager.t.exports.PackageManager.install (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:898819)
    at PackageCard.install (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2932926)
    at HTMLButtonElement.installButtonClickHandler (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2919248)
```

### Commands

```
     -5:56.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-runner 2.7.1 
autocomplete-glsl 0.2.3 
autocomplete-love 0.4.0 
autocomplete-lua 0.9.1 
busy-signal 2.0.0 
Hydrogen 2.8.0 
hyperclick 0.0.0 
hyperclick-love 0.6.0 
ide-cpp 0.0.3 
ide-powershell 0.1.0 
ide-rust 0.20.0 
intentions 1.1.5 
language-glsl 2.0.4 
language-gmod-lua 0.4.0 
language-lua 0.9.11 
language-powershell 5.0.0 
language-rust 0.4.12 
linter 2.3.0 
linter-lua 2.0.0 
linter-luaparse 0.2.0 
linter-rust 1.0.1 
linter-ui-default 1.7.1 
love-ide 0.17.0 
platformio-ide-terminal 2.9.1 
rust-api-docs-helper 0.5.1 
tabletopsimulator-lua 11.0.2 
terminal-tab-service 0.1.4 
tool-bar 1.1.11 
```

**Comment by rsese** [comment] 2019-03-05 00:30
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16873 so you can subscribe there for updates if you'd like.  If you can reproduce after uninstalling/reinstalling or have any other details to share, please let us know in https://github.com/atom/atom/issues/16873.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-03-05 00:30 UTC
