### ISSUE TITLE
Keyboard shortcuts in command palette unreadable after update on Ubuntu 14.04

### ISSUE THREAD

**Issue by BelfryGhost** [atom/atom#6953] opened 2015-05-26 14:04 UTC
After updating to version 0.201.0, keyboard shortcuts, which are displayed next to the commands when going through the command palette (Ctrl+Shift+P), have a white font on a bright background. 

![command_palette2](https://cloud.githubusercontent.com/assets/4437458/7814052/db0f7a1e-03bf-11e5-947c-57376b8c9001.png)

I think the font colour should be black instead.
I use the webupd8 PPA ppa:webupd8team/atom on Ubuntu 14.04

This issue can be worked around by using a dark UI theme. But with UI themes "One Light" and "Atom Light" the text is pretty much unreadable.

**Comment by mnquintana** [comment] 2015-05-26 14:15
Duplicate of https://github.com/atom/atom/issues/6923 – this will be fixed in the next Atom release, 0.202.0.

**Closed by mnquintana** 2015-05-26 14:15 UTC
