### ISSUE TITLE
cmd+d is working in a wrong way...

### ISSUE THREAD

**Issue by llqgit** [atom/atom#12096] opened 2016-07-04 09:12 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

cmd+d to select the next word is working in a wrong way, I think...

### Steps to Reproduce

1. if we have a method like this: 
```
abc_aaa.abc_aaa.aaa();
```
2. select the first **aaa**  it looks like this:

  abc_[aaa]().abc_aaa.aaa();
 
3. then **cmd + d** it looks like this:

  abc_[aaa.abc_]()aaa.aaa();

**Expected behavior:** [What you expected to happen]

 but I want this way: 

 abc_[aaa]().abc_[aaa]().aaa();

**Actual behavior:** [What actually happened]

### Versions

>Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by lee-dohm** [comment] 2016-07-06 23:39
I could not replicate the behavior you're describing using Atom v1.8.0 on Mac OS X 10.11.5. Here's what I did:

1. Launch Atom
1. Open a new file using <kbd>Cmd+N</kbd>
1. Paste in the text `abc_aaa.abc_aaa.aaa();` from your example
1. Highlight the first `aaa` using the key commands
1. Press <kbd>Cmd+D</kbd>

Expected and actual: The first two `aaa` instances were selected.

Have you tried reproducing the problem in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by llqgit** [comment] 2016-07-07 02:43
Yes , I have run in safe mode, and I run again just now. In the first time ,I think you are right, safe mode is  looks normal. But when I try several times, I find out that it's not happened in every single time. So, maybe it is a real problem I think.

And my OS is Mac OS X 10.11.5 also Atom 1.8.0

**Comment by llqgit** [comment] 2016-07-07 03:06
I found a little tail about that problem. Maybe it is happened about the mouse event.
I use my Mac's pad not a real mouse to drag and select a word. 
when I finish my select, if I don't move out my mouse from the word. It will happen more often.

**Comment by emilchristensen** [comment] 2016-07-11 14:07
The described behavior is what happens when <kbd>Cmd</kbd>+<kbd>D</kbd> is pressed before the mouse/trackpad button has been released after selection.

Steps to reproduce:

1. Launch Atom
2. Open a new file using <kbd>Cmd</kbd>+<kbd>N</kbd>
3. Paste in the text abc_aaa.abc_aaa.aaa(); from your example
4. Highlight the first aaa using the mouse or trackpad, and do *not* release the mouse buttom
5. Press <kbd>Cmd</kbd>+<kbd>D</kbd>

I don't see this as a bug. It is more likely a bad trackpad that doesn't release properly everytime.

It behaves like this on both Windows 10 and Mac OS X 10.11 with Atom 1.9.0beta

**Comment by llqgit** [comment] 2016-07-12 03:16
You are right about that the mouse(actually the trackpad) do not release in some situation, actually not 'some' but 'one' situation when I drag to select a word with three fingers gesture and don't move out from the word, just keep it in the end of the word.

Now, I can reproduce when I want. It will happened more often when I do the **rules** as I said above.

----------------

By the way, my trackpad would not be bad I think. Cause my Mac book pro is a new one.
And what I want is the Atom will be better and better.
**Thank you for your test and answers.**

**Comment by lee-dohm** [comment] 2016-07-12 06:28
Thanks @emilchristensen for the extra information. I'm going to close this for a few reasons:

1. Atom can't help it if the OS is telling it that the mouse button hasn't been released
1. If I'm understanding you correctly, [the three fingers gesture](http://www.macobserver.com/tmo/article/os-x-the-three-finger-tap-opening-the-dictionary) is for getting the definition of a word from the OS X dictionary. It isn't designed to select a word within a program, even if that is a side-effect.
1. If you want an easy way to select a word with the trackpad, I recommend the [highlight-selected package](https://atom.io/packages/highlight-selected). It will allow you to double-click a word to select it. This way you don't need to use a problematic gesture for selections.

**Closed by lee-dohm** 2016-07-12 06:28 UTC
Labels: more-information-needed, needs-reproduction

**Comment by llqgit** [comment] 2016-07-12 08:29
@lee-dohm 
Sorry, you got some mis-understanding with the question.
 At the last with the helps, I figure out that the point is when your mouse(not trackpad) is not released after you select a word. The <kbd>cmd + d</kbd> will be wrong. And why I said it's a mistake, cause the **Sublime Text** do not have that problem in the same situation. And it appears more often if you use a trackpad rather than a mouse.
I try it on my friends computers, it is a problem indeed.

Please forget the ** the three fingers gesture **. It's a mis-understanding of mine.

And one more thing is mostly we need to select a part of word, a part of code, so I have to use the mouse to drag and select, not a double-click.

**Comment by lee-dohm** [comment] 2016-07-12 19:40
@llqgit Without the three fingers gesture, this is a duplicate of https://github.com/atom/atom/issues/10312 and will still remain closed. You should subscribe to that Issue for updates.
