### ISSUE TITLE
Uncaught AssertionError: 2103 == 0

### ISSUE THREAD

**Issue by MrBoffin** [atom/atom#16790] opened 2018-02-20 02:53 UTC
[Enter steps to reproduce:]

1. Open Install packages
2. Searched for "base64"

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError: 2103 == 0

```
At assert.js:85

AssertionError: 2103 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:290:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:394:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -1:25.2.0 core:paste (input.hidden-input)
     -1:23.5.0 editor:move-to-first-character-of-line (input.hidden-input)
  5x -1:22.4.0 core:move-up (input.hidden-input)
     -1:21.3.0 core:delete (input.hidden-input)
     -1:19.9.0 core:select-to-bottom (input.hidden-input)
     -1:08.2.0 encoding-selector:show (span.syntax--text.syntax--plain.syntax--null-grammar)
     -1:06.7.0 editor:consolidate-selections (input.hidden-input)
     -1:06.7.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-02-20 20:56
Thanks for contributing!

This looks like a duplicate of https://github.com/atom/atom/issues/14074 so you can subscribe there for updates if you'd like.  I'll copy over your steps but feel free to let us know in https://github.com/atom/atom/issues/14074 if the error is reproducible.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-02-20 20:56 UTC
