### ISSUE TITLE
File->Open... and Atom->About Atom broken in macOS

### ISSUE THREAD

**Issue by mcandre** [atom/atom#16236] opened 2017-11-19 13:44 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Multiple menu items in Atom are now broken.

### Steps to Reproduce

1. Launch Atom in macOS.
2. Select Atom->About Atom.
3. Close all Atom windows.
4. Select Open... in an attempt to browse for files and directories to open in Atom.

**Expected behavior:**

The About page is raised, with no errors.

A Finder pane is displayed for navigating the file system.

**Actual behavior:**

Atom raises an error "Project directory atom://about is no longer on disk."

No Finder pane is displayed.

**Reproduces how often:**

Always

### Versions

```console
$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.8.4
```

Using macOS High Sierra.

**Comment by rsese** [comment] 2017-11-20 18:55
Thanks for the report!  The issue where `File > Open` doesn't work when no windows are open in macOS is reported here if you want to subscribe:

https://github.com/atom/atom/issues/12508

About this part:

> Atom raises an error "Project directory atom://about is no longer on disk."

I'm unable to reproduce this, can you share a GIF or screencast that demonstrates the behavior?

**Comment by kavon** [comment] 2017-12-18 23:12
@rsese Here's a video demonstrating the bug: https://youtu.be/8mm7JIe2cPs

I recall first seeing the error message a few releases ago, but it hasn't been fixed by now, so I figured I should chime in. 

System details: 
- macOS 10.13.2
- Atom 1.23.1 x64

Please let me know if you have additional questions.

**Comment by rsese** [comment] 2017-12-20 23:23
Thanks @kavon - it seems like some bad state was saved maybe?  It looks like you can reproduce consistently @kavon can you try clearing saved state and let us know if that fixes things for you?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

Make sure to save any unsaved work first as mentioned in the warning.

**Comment by mbokil** [comment] 2017-12-21 00:02
@rsese I cleared the state and moved the .atom folder. I reinstalled my packages. The error message is gone.

**Comment by kavon** [comment] 2017-12-21 17:04
@rsese I simply cleared the window state and the message is gone now. Thanks!

**Comment by rsese** [comment] 2017-12-21 17:51
Thanks @mbokil @kavon :bow:

Pretty sure that clearing saved state will fix things for you too @mcandre but if not let me know and we can re-open.

**Closed by rsese** 2017-12-21 17:51 UTC
Labels: more-information-needed
