### ISSUE TITLE
"Create issue on the <package> package" button can create very large URIs.  

### ISSUE THREAD

**Issue by derekdreery** [atom/atom#13127] opened 2016-11-02 10:40 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

"Create issue on the <package> package" button can create very large URIs.  

### Steps to Reproduce

1. Generate an error in a package that generates a long issue length (converted into URI) (I got one in `vim-mode`) 
2. Click the "Create issue on the <package> package" button

**Expected behavior:** Created ticket

**Actual behavior:** 414 Request-URI Too Large

### Suggested fix

The bug reporter could check the length of the issue, and if it's too large for a URI instead present instructions for copy-pasting the ticket. Alternatively you could bump up the uri limit of github.com.

http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

### Versions

Atom    : 1.11.2
Electron: 1.4.4
Chrome  : 53.0.2785.113
Node    : 6.5.0

apm  1.13.0
npm  3.10.9
node 6.9.1
python 3.5.2
git 2.10.1

Linux 4.8.4-1-ARCH #1 SMP PREEMPT Sat Oct 22 18:26:57 CEST 2016 x86_64 GNU/Linux

**Comment by Ben3eeE** [comment] 2016-11-02 10:43
This is a duplicate of https://github.com/atom/notifications/issues/129. Feel free to subscribe there for updates.

You are also using an [unofficial Atom distribution](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Closed by Ben3eeE** 2016-11-02 10:43 UTC

**Comment by derekdreery** [comment] 2016-11-02 10:45
Thanks for the quick response!
