### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isValid' of undefined

### ISSUE THREAD

**Issue by Willibaur** [atom/atom#10156] opened 2015-12-22 13:10 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'isValid' of undefined

```
At /Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:665

TypeError: Cannot read property 'isValid' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateOverlaysState (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:665:36)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPostMeasurementState (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:166:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:183:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:195:38)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:278:21)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:933:16)
    at TextEditorComponent.module.exports.TextEditorComponent.pollDOM (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:920:17)
    at /Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/view-registry.js:234:9)
    at ViewRegistry.<anonymous> (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:701:23)
    at ViewRegistry.module.exports.ViewRegistry.requestDocumentPoll (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/view-registry.js:225:21)
    at MutationObserver.<anonymous> (/Users/willibaur/Desktop/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61)
```

### Commands

```
     -0:39.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:39.2.0 core:move-up (atom-text-editor.editor.is-focused)
  9x -0:38.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:37.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:36.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:36.2.0 core:move-right (atom-text-editor.editor.is-focused)
 14x -0:35.8.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:33.2.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:29.8.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:28.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:22.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -0:20.8.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -0:19.2.0 core:move-left (atom-text-editor.editor.is-focused)
  8x -0:17.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "linter-htmlhint",
      "minimap"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 10,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "zoomFontWhenCtrlScrolling": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
atom-pair, v2.0.10
autoclose-html, v0.19.0
capybara-snippets, v0.2.0
color-picker, v2.0.14
emmet, v2.3.17
file-icons, v1.6.13
hashrocket, v0.4.8
highlight-line, v0.11.0
highlight-selected, v0.11.1
indent-guide-improved, v1.4.5
linter, v1.11.3
linter-rubocop, v0.4.5
linter-ruby, v1.2.0
seti-syntax, v0.4.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Willibaur** [comment] 2015-12-22 13:11
Issue generated after updating atom

**Comment by niahmiah** [comment] 2015-12-22 17:17
I get this when opening a new pane. Currently only single-pane view works.

**Comment by kevinsawicki** [comment] 2016-01-04 21:10
This looks like a duplicate of #10014, closing it out here, please subscribe there for updates.

**Closed by kevinsawicki** 2016-01-04 21:10 UTC
Labels: uncaught-exception

**Comment by shivrajvc** [comment] 2018-02-06 05:36
sga
