### ISSUE TITLE
Autocomplete snippets seem to be displayed in arbitrary order

### ISSUE THREAD

**Issue by gregplaysguitar** [atom/atom#6503] opened 2015-04-23 23:38 UTC
In language-javascript/snippets, there's an "f" snippet for an anonymous function, and language-todo/snippets has "fix" for a "fix me" comment. To see this:

1. Open a javascript file
2. Type "f"

The former should be offered as the first suggestion, as it's the best match, but instead it appears 6th on the list, behind fix, for, forin, forof and fun.

**Comment by mnquintana** [comment] 2015-04-23 23:42
Are you using autocomplete or autocomplete-plus?

**Comment by gregplaysguitar** [comment] 2015-04-23 23:53
autocomplete-plus and autocomplete-snippets

**Comment by mnquintana** [comment] 2015-04-24 00:27
Duplicate of atom-community/autocomplete-snippets#43 - please subscribe there for updates.

**Closed by mnquintana** 2015-04-24 00:27 UTC
