### ISSUE TITLE
Windows Explorer <-> Atom Copy/Paste is not working.

### ISSUE THREAD

**Issue by moonjoungyoung** [atom/atom#16715] opened 2018-02-12 10:00 UTC
### Description
Windows Explorer -> Atom and Atom -> Windows Explorer
Copy/Paste is not working.

It seems at https://github.com/atom/atom/issues/12867 too.
#12867 has closed, but this issue is still working.

### Steps to Reproduce
At https://github.com/atom/atom/issues/12867.
1. Copy file at Windows Explorer / Atom
2. Paste file at Atom / Windows Explorer

**Expected behavior:** [What you expect to happen]
Working Copy/Paste.

**Actual behavior:** [What actually happens]
Copy/Paste is not working.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Atom verson: 1.23.3
OS: windows10 1709

**Comment by 50Wliu** [comment] 2018-02-12 15:21
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/tree-view#569. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-02-12 15:21 UTC
