### ISSUE TITLE
On need (dynamic) plugin loading

### ISSUE THREAD

**Issue by lefta** [atom/atom#13380] opened 2016-12-04 11:07 UTC
## Rationale

Atom is a great multipurpose text editor, and the one that best suit my need. But depending on the usage, it may become too much multipurpose as adding more and more plugins to support many usages quickly makes it a bloatware.

For a concrete example, I'm using Atom as a text editor, a markdown editor, a C/C++ IDE, and sometimes as a C# IDE or a Python IDE. I end up with lots of specific usage plugins which increase startup time and resource usage for nothing: clang-autocomplete and clang-linter are useless in C#, and OmniSharp is useless in C/C++, even worst, both are not needed when I want to quickly edit a text file, and waiting several seconds to edit a text file is quite boring.

There are some workarounds, like enabling plugins per project, but loading plugins only when needed would be easier, more flexible and sometimes the only alternative (when using Atom as a simple text editor with language plugins for example).

## Typical usages

* IDE / advanced text editor: This is mostly the typical usage. It uses plugins providing autocompletion, linting and some other language-specific features (markdown-preview for example). It also uses CVS, but not always.
* Simple text editor: I know that there are editors more suited for this, but why having multiple text editors for multiple usages when we have a modular one? And, why not, maybe a fool in the future will even make an office suite plugin to replace LibreOffice...

## Some brainstorming

Plugins would be separated in two types :
* always-enabled plugins, which are (almost?) always usefull / wanted like the project-manager plugin. These would be always loaded on start.
* usage-specific plugins, which are usefull only on some condition, like language linters. These would be loaded only when the conditions are met.
* dependency-only plugin, which are useless on themselves, like the linter plugin. These would be loaded only when another plugin need them.

To let plugin writers handle this change slightly, plugins not reporting their type would be considered as always-enabled plugins.

Conditions would include, but not be extaustive to :
* the open file(s) / project(s) language(s) : Some plugins would be explicitely related to some language(s). For quick opening of Atom, language plugins would be loaded on file open. To avoid often loads and unloads, a plugin would be unloaded only when there is no file of this language in the project anymore.
* the presence of a file / directory in the project : Obviously, I don't need git-status if I have no `.git` folder in my project. The same goes for the build plugin with the .atom-build file.

As some plugins need some dependencies but may not always report them correctly (especially for those which depend on default plugins), I suggest a "force always-loaded" setting to let time to reflect the change to plugin writers.

## The word of the end

I'm not an Atom developper, and I know that this is a very big work and that it likely needs code refactoring. The behavior like the implementation details need to be carefully thought to avoid making plugin management a big mess. I don't expect to see it anytime soon, but it would make Atom the perfect text editor / IDE (at least for me).

**Comment by lee-dohm** [comment] 2016-12-23 20:56
Thank you for reaching out! This is a great description of the desired feature :metal:

We noticed that this is a duplicate of https://github.com/atom/atom/issues/6619. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2016-12-23 20:56 UTC
