### ISSUE TITLE
"Editor: Toggle Comments" converts leading tabs to spaces

### ISSUE THREAD

**Issue by caleb531** [atom/atom#16462] opened 2017-12-29 03:59 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When toggling on comments for blank lines, the leading tabs are converted to spaces if the line consists of entirely whitespace. This has been especially irritating for projects where tabs are the preferred indent style because I end up committing files with mixed indentation. The [editorconfig package](https://github.com/sindresorhus/atom-editorconfig) does not seen to influence the occurrence of this issue, either.

Please see the following GIF:  
![toggle-comments-bug](https://user-images.githubusercontent.com/872474/34429140-f131767e-ec08-11e7-80bb-e1fe610909fa.gif)

### Steps to Reproduce

1. Make sure your default Atom indent style is set to tabs (Settings > Editor > Uncheck "Soft Tabs")
2. Open any file (new or existing) with a grammar that has toggle-able line comments
3.Make sure whitespace is visible (via the `window:toggle-invisibles` command)
4. Indent a blank line by any amount (so there are a couple tabs)
5. At this point, toggling on comments (via `editor:toggle-line-comments`, or via key binding) will add the comment, but convert the leading tabs to spaces.
  - If I type any non-whitespace characters before toggling on comments, the tabs are preserved
  - Note that the leading spaces are *not* converted back to tabs when toggling off comments

**Expected behavior:** The leading tabs on the line to be preserved

**Actual behavior:** The leading tabs are converted to spaces

**Reproduces how often:** Every time.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2017-12-29 05:35
Thanks for taking the time to contribute!  This looks like a duplicate of https://github.com/atom/atom/issues/16193, I believe it's fixed in 1.24 (currently in beta).  If I mis-understood anything, please let me know.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-29 05:35 UTC
