### ISSUE TITLE
Drag & Drop Files to Project Produces Errors

### ISSUE THREAD

**Issue by garrett85** [atom/atom#17234] opened 2018-04-28 01:48 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

From Linux Mint
When I try to drag and drop html/css files from my file explorer (Nemo) to the project directory on the left hand of my Atom window I get an error.

Failed to move entry /home/user/Downloads/Django-Python-Full-Stack-Web-Devloper-master/CSS_Level_One/CSS_Level_One_Assessment.html to /var/www/html/udemy/css1
EXDEV: cross-device link not permitted, rename '/home/user/Downloads/Django-Python-Full-Stack-Web-Devloper-master/CSS_Level_One/CSS_Level_One_Assessment.html' -> '/var/www/html/udemy/css1/CSS_Level_One_Assessment.html'

### Steps to Reproduce
1. Open Nemo to directory of needed files
2. Drag file to Atom application on my Linux Mint menu bar
3. Release over the project directory from within Atam
4. Get error

**Expected behavior:** [What you expect to happen]
I expected the files to be added to my project directory.

**Actual behavior:** [What actually happens]
Failed to move entry /home/garrett/Downloads/Django-Python-Full-Stack-Web-Devloper-master/CSS_Level_One/CSS_Level_One_Assessment.html to /var/www/html/udemy/css1
EXDEV: cross-device link not permitted, rename '/home/garrett/Downloads/Django-Python-Full-Stack-Web-Devloper-master/CSS_Level_One/CSS_Level_One_Assessment.html' -> '/var/www/html/udemy/css1/CSS_Level_One_Assessment.html'

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
1.26
![atom1](https://user-images.githubusercontent.com/3172701/39390578-2b173f66-4a5c-11e8-87d3-5d8e7ad2dd7f.png)
![atom2_error](https://user-images.githubusercontent.com/3172701/39390579-2b2c5ec8-4a5c-11e8-9b86-90c0e1222a97.png)

**Comment by rsese** [comment] 2018-04-30 17:38
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/11456 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-30 17:38 UTC
