### ISSUE TITLE
Can't type Chinese using Sogou Wubi on Mac

### ISSUE THREAD

**Issue by linuxsong** [atom/atom#11988] opened 2016-06-16 11:04 UTC
When I upgrade Atom from 1.7.4 to 1.8.0,then I can type only one Chines word use Sogou input method(a Chinese keyboard layout).When I continue type Chinese word  then can't type anything.If change to English keyboard layout and type English text is ok.
I try Atom 1.9.0-beta0 version and have the same problem.But 1.7.4 version is work good.
My OS version is  OS X 10.11.5.

**Comment by 50Wliu** [comment] 2016-06-16 17:00
Microsoft Pinyin works fine for me on Atom 1.9.0-dev-3b9b28d:
![chinese](https://cloud.githubusercontent.com/assets/2766036/16125554/300dc6d2-33c2-11e6-92a1-ce0cd3f46865.gif)

**Comment by 50Wliu** [comment] 2016-06-19 14:37
@cooppor What OS and what IME are you using?

**Comment by linuxsong** [comment] 2016-06-21 14:30
I change another Chinese IME(OS X built-in Chinese IME)  work good.But the Sogou IME work good on Atom 1.7.4 and can't work on Atom 1.8.0.
I use  OS X 10.11.5.

**Comment by cooppor** [comment] 2016-06-24 17:17
@50Wliu  
OS: Mac OSX 10.11.5,
IME: Sogou Wubi v1.0.0.78455,  official website http://pinyin.sogou.com/mac/wubi.php .

ps.
I tried mac Wubi and other Wubi IME, they all work good, but the Sogou Wubi.

**Comment by 50Wliu** [comment] 2016-06-24 19:17
Still cannot reproduce using Sogou Wubi 2.1.0 for Windows on Atom 1.10.0-dev-a5fdf3e, so tagging as mac-only.

**Comment by zjunothing** [comment] 2016-06-30 03:41
got the same issue
mac：  10.10.5
atom：  1.8
input：  QQpinyin for mac 2.9

**Comment by zjunothing** [comment] 2016-06-30 03:47
@cooppor  just use baidu pinyin instead， baidu pinyin is ok for me.
Sougou and QQpinyin  NOT work

**Comment by wildplant** [comment] 2016-07-11 19:12
I use wubi input. Sogou wubi cant work in atom editor, but qingge(清歌五笔) is ok.

**Comment by 50Wliu** [comment] 2016-07-12 09:48
@zcbenz could this be an Electron/Chromium issue, and if so do you think it's been fixed in 1.0 or later?

**Comment by ChangeZhang** [comment] 2016-07-22 03:06
this bug is fixed?

**Comment by Robin-front** [comment] 2016-08-10 06:58
+1

**Comment by huarse** [comment] 2016-08-25 06:03
+1

**Comment by luzuojin** [comment] 2016-08-30 15:57
reinstall Sogou Wubi

**Comment by lee-zhi** [comment] 2016-09-02 07:24
reinstall Sogou Wubi is ok in my computer.

**Comment by DaWiii** [comment] 2016-09-05 09:05
1. download http://pinyin.sogou.com/mac/wubi.php
2. uninstall
3. install

**Comment by 50Wliu** [comment] 2016-09-05 19:13
Assuming fixed.

**Closed by 50Wliu** 2016-09-05 19:13 UTC
Labels: bug, electron, mac

**Comment by sosobad** [comment] 2016-09-21 05:14
reinstall Sogou Pinyin is work!!
