### ISSUE TITLE
Contents in untitled files will be lost on close

### ISSUE THREAD

**Issue by sgoendoer** [atom/atom#11510] opened 2016-04-18 13:41 UTC
### Description

When starting Atom (v 1.7.1) and creating some text in the new, unnamed, and empty file ("untitled") - and THEN close atom, everything will be lost. Atom does not ask to save, nor does it autosave. Using "reopen last object" does not work. The text is just lost. Reproducible - also in safe mode.

### Steps to Reproduce

1. open atom
2. create some text in "untilted"
3. close atom

**Expected behavior:** being prompted to save - or at least creating an autosave

**Actual behavior:** file contents are lost

### Versions

OS: Mac OS X 10.11.4

    $ atom --version
    Atom    : 1.7.1
    Electron: 0.36.8
    Chrome  : 47.0.2526.110
    Node    : 5.1.1
    
    $ apm --version
    apm  1.9.2
    npm  2.13.3
    node 0.10.40
    python 2.7.10
    git 2.8.1

**Comment by Zireael07** [comment] 2016-04-18 17:25
I believe this is a duplicate?

**Comment by sgoendoer** [comment] 2016-04-19 12:24
Still exists in Atom 1.7.2

**Comment by lee-dohm** [comment] 2016-04-21 22:32
This is a duplicate of https://github.com/atom/atom/issues/10474. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-04-21 22:32 UTC
