### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -1, expected to pop -227.

### ISSUE THREAD

**Issue by sihrc** [atom/atom#7209] opened 2015-06-10 15:43 UTC
Steps to reproduce below:

1. Have a really long line of text more than 350 characters and the text formatting stops after about that many characters.
2. Using multiple select, select characters that appear in beginning of line to the end of the line (or at least past the 350 char mark)
3. Try to delete or edit

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -1, expected to pop -227.

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:741

Error: Encountered an invalid scope end id. Popped -1, expected to pop -227.
    at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:607:21)
    at TokenizedBuffer.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:483:31)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLinesForRows (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:490:10)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:383:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:622:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:530:12)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:452:43)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:742:31
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:787:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:736:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1148:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:781:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1974:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1948:35)
```

### Commands

```
 33x -0:50.6.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:44.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:40.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:39.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:39.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:39.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:38.1.0 core:undo (atom-text-editor.editor.is-focused)
  9x -0:25.3.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:23.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:22.7.0 core:save (atom-text-editor.editor.is-focused)
 17x -0:18.7.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:15.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:backspace (atom-text-editor.editor.is-focused)
 10x -0:06.6.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "csscomb"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.10
atom-javascript-snippets, v1.0.0
color-picker, v2.0.4
csslint, v1.1.3
emmet-atom, v2.3.10
highlight-line, v0.10.2
javascript-snippets, v1.0.0
language-r, v0.2.0
seti-syntax, v0.4.0
seti-ui, v0.7.1
tabs-to-spaces, v0.11.0
terminal-status, v1.6.7
trailing-spaces, v0.3.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-10 15:47
Thanks for the report, @sihrc -- do you remember which type of file you were editing (JavaScript, Ruby, ...)? I'm guessing this doesn't happen with every type of file?

cc @nathansobo another one of these

**Comment by sihrc** [comment] 2015-06-10 16:26
@izuzak At the time, it was ruby. I recall it might have happened in another language before. What's worth noting is the beautifier I'm using also doesn't work for Ruby. I'm not sure if the problem is in the package or not.

**Comment by izuzak** [comment] 2015-06-10 16:32
Thanks, @sihrc -- it's probably a problem in Atom, but hard to find the corner case that causes it. If it happens again, it would be really helpful to know the file contents that trigger it -- see https://github.com/atom/atom/issues/7177#issuecomment-110814111 for details.

**Comment by sihrc** [comment] 2015-06-10 16:54
Sure.  Actually sorry, it's a public README file that triggered it. I was writing ruby code in markdown. You can find it [here](https://github.com/IndicoDataSolutions/IndicoIo-ruby/tree/development). 

It was the code in the last code chunk in the readme. I was changing double quotes to single quotes using multi select in the hash outputs.

**Comment by nathansobo** [comment] 2015-06-10 21:18
This error looks so similar to #7177 that I have a strong suspicion it's the same issue, which is now fixed. I tested the latest state of the README file and was unable to reproduce it. Please reopen if this occurs again after 0.209.0. Sorry for the trouble and thanks for your time.

**Closed by nathansobo** 2015-06-10 21:18 UTC
Labels: bug, uncaught-exception
