### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\D:\atom\app-1.21.1\resources\app.as...

### ISSUE THREAD

**Issue by demetrisKPI** [atom/atom#16009] opened 2017-10-26 21:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\D:\atom\app-1.21.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\D:\atom\app-1.21.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (D:/atom/app-1.21.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (D:/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (D:/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (D:/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (D:/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (D:/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (D:/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (D:/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (D:/atom/app-1.21.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (D:/atom/app-1.21.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
 83x -2:59.2.0 core:move-down (input.hidden-input)
 13x -2:50.8.0 core:backspace (input.hidden-input)
  2x -0:24.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-js-import 1.4.0 
color-picker 2.2.5 
emmet 2.4.3 
git-plus 7.9.3 
platformio-ide-terminal 2.7.0 
Remote-FTP 1.2.4 
```

**Comment by rsese** [comment] 2017-10-26 22:16
I think this might be a duplicate of recent issues like https://github.com/atom/atom/issues/15722.  If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled.  If you don't have any anti-virus software, let me know.

**Closed by rsese** 2017-10-26 22:16 UTC
