### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new...

### ISSUE THREAD

**Issue by plReynaerde** [atom/atom#13312] opened 2016-11-23 14:51 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/line-numbers-tile-component.js:120

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Error (native)
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.updateLineNumbers (/Applications/Atom.app/Contents/Resources/app.asar/src/line-numbers-tile-component.js:120:37)
    at LineNumbersTileComponent.module.exports.LineNumbersTileComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/line-numbers-tile-component.js:78:19)
    at LineNumberGutterComponent.module.exports.TiledComponent.updateTileNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:67:19)
    at LineNumberGutterComponent.module.exports.TiledComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:30:12)
    at GutterContainerComponent.module.exports.GutterContainerComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container-component.js:79:25)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:232:39)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:323:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:219:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:59
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "git-plus",
      "go-plus",
      "language-sql",
      "qolor"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1 (active)
atom-terminal-panel, v4.4.4 (active)
autocomplete-go, v1.3.0 (active)
builder-go, v1.0.1 (active)
change-case, v0.6.3 (active)
git-plus, v5.25.5 (inactive)
git-time-machine, v1.5.4 (inactive)
git-time-metric, v1.1.7 (active)
git-tools, v0.4.1 (inactive)
go-config, v1.2.4 (active)
go-debug, v0.1.22 (active)
go-get, v2.1.1 (active)
go-plus, v4.3.2 (inactive)
godoc, v1.1.1 (active)
gofmt, v1.2.0 (active)
gometalinter-linter, v1.2.2 (active)
gorename, v1.1.0 (active)
jshint, v1.8.6 (active)
language-arm, v1.2.2 (active)
linter, v1.11.18 (active)
minimap, v4.25.6 (active)
minimap-git-diff, v4.3.1 (active)
multi-cursor-plus, v1.0.3 (inactive)
navigator-go, v1.1.3 (active)
qolor, v0.4.1 (inactive)
tester-go, v2.0.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-11-25 17:02
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see in Atom. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see the [How Can I Contribute? section of the Atom CONTRTIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by 50Wliu** [comment] 2016-12-15 15:48
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13312#issuecomment-262998348. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2016-12-15 15:48 UTC
Labels: more-information-needed, needs-reproduction

**Comment by aschwtzr** [comment] 2016-12-25 15:55
@50Wliu I'm being redirected here by Atom. I don't think I'm having any errors (my code is compiling and running otherwise) but wanted to give you a heads up about it.

**Comment by 50Wliu** [comment] 2016-12-31 01:54
@aschwtzr Can you please create a new issue and fill out the issue template?  Thanks :).

**Comment by vingorius** [comment] 2017-02-06 02:40
+1

**Comment by dmo-odoo** [comment] 2017-02-28 14:58
Is there somewhere where this issue is being treated ? I will have to downgrade Atom as it is happening all the time and is preventing me from working properly...

**Comment by 50Wliu** [comment] 2017-02-28 17:07
@dmo-odoo Can you please open a new issue?

**Comment by dmo-odoo** [comment] 2017-03-01 08:14
@50Wliu I'm completely unable to reproduce it right now, like the bug is completely gone, I don't understand what is going on, I did not update or downgrade Atom since my last message. I'll see if I still encounter it and if I can reproduce it.

**Comment by bardes** [comment] 2017-09-21 05:00
I can reproduce it through the following steps:

1. Install and enable the [relative-numbers](https://github.com/justmoon/relative-numbers) package.
2. Make sure you have "Show Line Numbers" enabled at the editor's settings
3. Split the window into two panes: one with the editor's settings and the other with any file.
4. Toggle the "Show Line Numbers" settings twice (off and on again)

This should trigger the exception. Clicking around the file and scrolling through also causes more exceptions...

**Comment by 50Wliu** [comment] 2017-09-26 20:54
@bardes you might want to report this to the relative-numbers maintainers.  Then they can decide if it's a bug in their implementation or whether there's a bug in Atom that needs fixing as well.

**Comment by keremer35** [comment] 2017-11-21 13:16
Same on Windows 10 too.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core


### Stack Trace

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
At C:\Users\Kerem\AppData\Local\atom\app-1.22.1\resources\app\src\text-editor-component.js:3722

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at LinesTileComponent.updateLines (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor-component.js:3722:32)
    at LinesTileComponent.update (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor-component.js:3604:20)
    at updateComponent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:52:19)
    at patch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:16:25)
    at updateChildren (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/etch/lib/component-helpers.js:116:26)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor-component.js:383:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor-component.js:274:16)
    at etch.getScheduler.updateDocument (~/AppData/Local/atom/app-1.22.1/resources/app/src/text-editor-component.js:224:46)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.22.1/resources/app/src/view-registry.js:187:15)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:45.7.0 core:save (input.hidden-input)
     -0:41.6.0 intentions:highlight (input.hidden-input)
     -0:41.6.0 core:cut (input.hidden-input)
     -0:40.2.0 editor:newline (input.hidden-input)
     -0:39.9.0 intentions:highlight (input.hidden-input)
     -0:39.8.0 core:paste (input.hidden-input)
     -0:39.8.0 core:save (input.hidden-input)
     -0:34.8.0 intentions:highlight (input.hidden-input)
  2x -0:34.7.0 core:undo (input.hidden-input)
     -0:33.4.0 intentions:highlight (input.hidden-input)
     -0:33.3.0 core:undo (input.hidden-input)
     -0:28.5.0 intentions:highlight (input.hidden-input)
  2x -0:28.1.0 core:undo (input.hidden-input)
  2x -0:26.8.0 intentions:highlight (input.hidden-input)
  4x -0:25.7.0 core:undo (input.hidden-input)
 28x -0:23.7.0 core:redo (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.2 
autoclose-html 0.23.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.12 
ftp-remote-edit 0.12.3 
intentions 1.1.5 
language-sourcepawn 0.7.2 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-plus 4.29.2 
split-diff 1.5.1 
```

**Comment by haluvibe** [comment] 2018-02-22 18:13
Ive been redirected here by Atom. Can you reopen this issue please.

**Comment by Ben3eeE** [comment] 2018-02-23 12:51
@haluvibe Please open a new issue and completely fill out the issue template, thank you :bowing_man:
