### ISSUE TITLE
Parentheses matching is incomplete

### ISSUE THREAD

**Issue by falcondai** [atom/atom#17181] opened 2018-04-19 19:51 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Some matched parentheses are not correctly displayed. (I believe that they are correctly matched but it is an essentially UI issue due to triggering the matches on both left and right of any parenthesis.)

### Steps to Reproduce

1. Input `(())()` on a new line
2. Move your cursor to *the second right parenthesis* (the closing parenthesis of the doubly nested parentheses)
```
(())()
   ^
```

**Expected behavior:** [What you expect to happen]
The second right parenthesis should be highlighted along with the first left parenthesis as they are matched.

**Actual behavior:** [What actually happens]
This parenthesis cannot be highlighted by the parenthesis matching.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment] 2018-04-19 20:04
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/bracket-matcher/issues/350. You may want to subscribe there for updates. If you think that issue doesn't cover what you are describing here, please file a new issue on that repository.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-04-19 20:04 UTC

**Comment by falcondai** [comment] 2018-04-19 20:30
@Arcanemagus Ahh you are right! I am happy to know that it is only an issue in a package: I am planning to hack on it
