### ISSUE TITLE
getBoundingClientRect called on undefined in TextEditorComponent sometimes

### ISSUE THREAD

**Issue by steelbrain** [atom/atom#15341] opened 2017-08-16 18:42 UTC
Continuing from https://github.com/steelbrain/linter-ui-default/issues/355

What we know so far

- The error comes from [`pixelPositionForMouseEvent `](https://github.com/atom/atom/blob/15e3fbaa07f90174ab84d35a4281956b54128d12/src/text-editor-component.js#L1930)
- The error is often from commands like `core:confirm`, `core:copy` etc
- Either `scrollContainer` or `lineTiles` is undefined in Text Editor when those are invoked and it's not handled in Atom internally

First seen on 1.19.0-beta0, still hitting on 1.19.0

My rough guess about what it could be (not dug deep into sources so might be very wrong):

- A race condition after switching pane, those refs aren't yet resolved when the user moves mouse
- Either of these is two occurrences has the object undefined when the text editor is out of focus before moving mouse because in reports, one user had just closed dev tools, other kept switching, closing/reopening pane items
- Maybe the pane component doesn't check if it's been disposed and the items no longer exist and the bug is actually in linter-ui-default requesting mouse positions for closed tabs? (https://github.com/steelbrain/linter-ui-default/pull/420 fixes linter-ui-default side)

**Comment by robjtede** [comment] 2017-08-16 21:01
Definitely reproducible by myself and others on steelbrain/linter-ui-default#355

Sometimes, not always, when closing tabs, that error is raised through the linter-ui-default package.

**Comment by nathansobo** [comment] 2017-08-16 22:50
This is a private API but I'd still like to help out. I'm pretty confused because both of those refs should be defined after the editor is initially constructed and should never be invalidated.

**Comment by nathansobo** [comment] 2017-08-16 23:01
@as-cii Do you have any ideas on this one. As far as I can tell both the `scrollContainer` and `lineTiles` refs are created on construction of the component and never go away.

**Comment by as-cii** [comment] 2017-08-17 06:31
Prior to Atom 1.19.2 (specifically, before #15317), the `lineTiles` ref may have not been there if we hadn't performed the initial measurements, so I wonder if this problem got fixed as part of that pull-request. @robjtede @steelbrain: can you still reproduce this on the latest version?

**Comment by robjtede** [comment] 2017-08-17 09:17
I haven't had any issues since updating `linter-ui-default` to v1.6.7 (which was before updating Atom to 1.19.2).

**Comment by steelbrain** [comment] 2017-08-17 16:28
@as-cii My best guess at this point is that linter-ui-default was requesting measurements when the text editor had been unmounted (we have some internal debounce logic) so in the latest update I've made sure not to ask for measurements if the editor is unmounted

That seems to have fixed it for people so far, as for the Atom side, I think the text editor refs are removed when the editor is closed? A safeguard that throws an error with a proper message would be nice and helpful in debugging further cases like this

**Comment by nathansobo** [comment] 2017-08-17 18:22
From what I know about the `TextEditorComponent` and @as-cii's reminder about the change that landed in 1.19.2, I think what was happening is that the `mousemove` handler was calling that method on the editor before it had detected that it had become visible. Previously, we waited to render the `lineTiles` div until after performing an initial measurement of line height etc that requires the editor to be visible. Now we render the `lineTiles` div on construction, so the exception shouldn't occur. Thanks for the report.

**Closed by nathansobo** 2017-08-17 18:22 UTC
Labels: needs-reproduction, regression, uncaught-exception
