### ISSUE TITLE
[1.19.0] "View > Show Tab Bar" option gone

### ISSUE THREAD

**Issue by fmunteanu** [atom/atom#15222] opened 2017-08-09 21:59 UTC
Prior 1.19.0, I used Atom with multiple project tabs (not regular tabs), so I can switch easy in between project while using the same window. After upgrade, the `View > Show Tab Bar` option is gone on my Sierra Mac. Was this option relocated or replaced with a new feature? Reverting back to 1.18.x solves the issue.

**Comment by rsese** [comment] 2017-08-09 22:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15202. You may want to subscribe there for updates - also check out my comment in that issue /cc https://github.com/atom/atom/issues/15202#issuecomment-321318542.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-09 22:22 UTC
