### ISSUE TITLE
Folding Keybindings change to impossible values

### ISSUE THREAD

**Issue by Urm3l** [atom/atom#12480] opened 2016-08-19 18:17 UTC
Atom 1.9.9
Windows 10

While using the German keyboard layout the keybinding of Edit->Folding->Fold changes to
Alt+Ctrl+ß

This combination can not be overwritten within keymap and is not within the default keymap since there is no ß.

This means I can't type a \ because it always folds the line which is quite annoying.

**Comment by 50Wliu** [comment] 2016-08-19 19:58
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.  You may also want to try installing the [keyboard-localization](https://atom.io/packages/keyboard-localization) package.

**Closed by 50Wliu** 2016-08-19 19:58 UTC

**Comment by Urm3l** [comment] 2016-08-19 20:06
I have the keyboard-localization installed. It enables the ß key in the keybinding resolver. However there is no ß within the actual keybindings or the keybinding files. I don't know why the fold shortcut changes from ctrl-alt-] to ctrl-alt-ß. Not sure if it really is a duplicate since altgr works fine.

**Comment by Ben3eeE** [comment] 2016-08-19 20:10
If the keyboard localization package changes the keybindings you should probably open an issue on that repo and not here.

**Comment by Urm3l** [comment] 2016-08-19 20:16
The keybindings also change with keyboard localization package disabled. But using the package the keybinding resolver actually recognizes ctrl-alt-ß as ß and not as ctrl-alt-]. Its still the wrong repo though.
