### ISSUE TITLE
Cursor offset by 1-2 spaces

### ISSUE THREAD

**Issue by sogajeffrey** [atom/atom#9464] opened 2015-11-06 05:24 UTC
after using atom for some time, it started offseting the cursor by 1 to 2 spaces so when i clicked somewhere it would be offset. I would also have to move the cursor out of the {} for example to type in it. The only fix was to completely uninstall atom and reinstall it.

**Comment by izuzak** [comment] 2015-11-06 07:31
Thanks for opening an issue, @sogajeffrey. This seems like a duplicate of #9343 -- please see that for more information and let us know if you can reproduce this problem without the seti syntax theme. I'm going to close this in favor of that. :v:

**Closed by izuzak** 2015-11-06 07:31 UTC
