### ISSUE TITLE
Uncaught Error: ESPIPE: invalid seek, write

### ISSUE THREAD

**Issue by IngvarLosev** [atom/atom#6763] opened 2015-05-13 11:37 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: linux 3.16.0-37-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ESPIPE: invalid seek, write

```
At /usr/share/atom/resources/app.asar/src/pane.js:759

Error: ESPIPE: invalid seek, write
  at Error (native)
  at Object.fs.writeSync (fs.js:657:20)
  at Object.fs.writeFileSync (fs.js:1164:21)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
  at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:264:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:362:21)
  at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:336:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:913:17)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:592:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:310:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
  2x -1:34.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-13 11:56
I'm assuming that this is a duplicate of #2539, so please subscribe there for updates.
If you weren't in fact saving to FTP mounted with gvfs please comment here so this can be re-opened!

**Closed by 50Wliu** 2015-05-13 11:56 UTC

**Comment by IngvarLosev** [comment] 2015-05-13 12:24
yes i trying aving to FTP mounted with gvfs  - as result this error

**Comment by apikey** [comment] 2015-06-27 20:06
I'm using Ubuntu Meerkat and have connected to files on my webserver using FTP.  I go to save a file through Atom and get this error.  It also deletes the contents of my PHP file when I go to save it.

**Comment by amansoni** [comment] 2015-07-30 15:10
I'm the same as apikey!
