### ISSUE TITLE
option+left/right arrow does nothing; control+left/right arrow does nothing

### ISSUE THREAD

**Issue by sandover** [atom/atom#5867] opened 2015-03-05 20:08 UTC
Mac OS X version 10.10.2 (14C109)
Atom Version 0.186.0 (0.186.0)

Standard OS X behavior (e.g. Mail.app) is:

  - option+left/right arrow moves by one word
  - control+left/right arrow moves to beginning/end of line

(For reference, in Sublime Text, both those options move by one word, which I happen to prefer.)

In current versions of Atom, the cursor does not move at all with these key combinations.

(I don't have any custom bindings for these keys in my keymap.cson)

**Comment by maxbrunsfeld** [comment] 2015-03-05 20:25
> option+left/right arrow moves by one word

This works for me. See [our mac keymap](https://github.com/atom/atom/blob/master/keymaps/darwin.cson#L107). If it's not working for you, could you try it with `atom --safe`, and report what the `Keybinding Resolver` shows when you press those combinations? 

> control+left/right arrow moves to beginning/end of line

Interesting; I didn't know those were bound by default. We *do* have *command*-left and *command*-right mapped to those motions, which also match Mac OS's defaults.

/cc @atom/core - is there any reason we shouldn't add those key-bindings for `ctrl-left` and `ctrl-right` on mac?

**Comment by mnquintana** [comment] 2015-03-06 13:34
> control+left/right arrow moves to beginning/end of line
Do you mean <kbd>Cmd+→/←</kbd>? <kbd>Ctrl++→/←</kbd> is generally mapped to switching between spaces. <kbd>Cmd+→/←</kbd> is mapped to moving to the beginning / end of the line and has always worked for me (and is the standard for OS X apps).

I also can't reproduce this with the same versions of Yosemite and Atom.

**Comment by sandover** [comment] 2015-04-08 03:58
Check with Atom 0.190 and 

- option+left/right arrow moves by one word -- works for me now
- command+left/right arrow moves to beginning/end of line -- works as always
- control+left/right arrow -- for me, doesn't do anything, but i'm not familiar with the spaces feature.  

Feel free to close.

**Comment by gvieira** [comment] 2015-04-08 14:20
I believe @sandover mean something like the attached gif.
![arrow](https://cloud.githubusercontent.com/assets/856480/7046990/e9516eb2-dddf-11e4-92b2-cbf2b3dcf2f1.gif)

It is exactly what I search for too. As @mnquintana said, [Ctrl]+[→]/[←] is really mapped to switch between spaces, but it was not in old OSX versions. Here in my company, everybody disable this default behavior to be able to use this in both Xcode and SublimeText.

Also, I search in Atom docs and couldn't find any editor command to perform this kind of operation.
Don't know if it is a OSX standard, althought.

**Comment by sandover** [comment] 2015-04-08 21:21
Yes, on all counts.

**Comment by mnquintana** [comment] 2015-04-08 21:31
Oh I see what you meant now – this isn't supported yet. You can track #1982 and #5806 for updates though. /cc @dsandstrom

(Actually I think this might be a duplicate of #1982.)

**Comment by gvieira** [comment] 2015-04-09 11:16
@mnquintana For sure it is a duplicate of #1982. And thanks for the references!

**Comment by mnquintana** [comment] 2015-04-09 11:21
No problem! (Closing as duplicate)

**Closed by mnquintana** 2015-04-09 11:21 UTC
Labels: more-information-needed

**Comment by gvieira** [comment] 2015-04-09 11:22
Also, [Subword Navigation](https://atom.io/packages/subword-navigation) solved to me.
