### ISSUE TITLE
Error: Could not create an input method

### ISSUE THREAD

**Issue by STommydx** [atom/atom#13785] opened 2017-02-10 11:04 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After upgrading to atom 1.14.1, atom crashes.
I have tried removing the config completely and reinstalling the whole package but it wont work.

### Steps to Reproduce

1. Open atom editor

**Expected behavior:** [What you expect to happen]
Editor shows up.

**Actual behavior:** [What actually happens]
Chrome-like console shows up with error. Also, a message popped up which says the editor crashed and please report the issue here.
Behavior is the same in safe mode.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.14.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12+
git 2.9.3

Running on Ubuntu 16.10.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

1.10.2 version was the old version i used. It runs perfectly fine on my computer.

The error log: 
> Error: Could not create an input method.
    at Error (native)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/keyboard-layout/lib/keyboard-layout.js:9:17)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/helpers.js:6:20)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/helpers.js:372:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/key-binding.js:4:10)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/key-binding.js:129:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:17:11)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:639:4)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)

This is my first time reporting an issue, i am fine to provide extra information if needed. Thanks!

UPDATE: 1.13.0 works fine.

**Comment by avnes** [comment] 2017-02-10 13:00
I am hitting the same issue on Fedora 25 with Atom 1.14.1, which was upgraded from 1.13.1

**Comment by 50Wliu** [comment] 2017-02-10 18:04
@STommydx, @avnes what keyboard layout(s) are you using?

@nathansobo

**Comment by avnes** [comment] 2017-02-10 18:09
@50Wliu I am not at that desktop PC until later this month due to vacation, but I use a Danish keyboard layout. As I am running Openbox on Fedora 25 on that box, I have set the keyboard layout with setxkbmap

**Comment by nathansobo** [comment] 2017-02-10 19:14
@Ben3eeE Can you link those PRs of changes to keyboard-layout in 1.14 that you posted to me in Slack?

**Comment by Ben3eeE** [comment] 2017-02-10 19:17
@nathansobo 

* https://github.com/atom/keyboard-layout/pull/25 to fix keyboard layout switching on Linux for non latin languages. Fixed issues like https://github.com/atom/atom-keymap/issues/203
* https://github.com/atom/keyboard-layout/pull/24 to fix https://github.com/atom/atom/issues/13296 which originally was only fixed and reported as a problem on Windows.

Also https://github.com/atom/keyboard-layout/pull/26 was merged to fix CI problems from https://github.com/atom/keyboard-layout/pull/25.

**Comment by jakubhruby** [comment] 2017-02-13 08:15
Same for me since 1.14.0 on ArchLinux:
```
System Locale: LANG=cs_CZ.UTF-8
VC Keymap: cz-us-qwertz
X11 Layout: cz,us
X11 Variant: ,
```

**Closed** 2017-02-13 16:32 UTC
Labels: more-information-needed, uncaught-exception

**Comment by binaryDiv** [comment] 2017-02-14 19:05
I just spent almost 2 hours to find a way to circumvent this problem (as the atom-editor-bin package on ArchLinux hasn't been fixed yet), and only found out because I had a similar problem with dmenu. May be helpful to @jakubhruby and anyone stumbling over this post via Google:

The problem results from using a locale different from "en_US". It should suffice to set the environment variable `LC_CTYPE` to `en_US.utf8`, for example by starting atom from shell via `LC_CTYPE=en_US.utf8 atom` or by changing your locale.conf.

**Comment by nathansobo** [comment] 2017-02-14 22:17
Please give just-published [1.15.0-beta2](https://github.com/atom/atom/releases/tag/v1.15.0-beta2) a try. We think we have fixed this issue.

**Comment by avnes** [comment] 2017-02-17 17:09
I tried the 1.14.2 on Fedora 25 with LANG=en_DK.UTF-8 and Danish keyboard, and I could not reproduce this issue any longer.

**Comment by nathansobo** [comment] 2017-02-17 17:36
Thanks for the report. Glad it's working for you.
