### ISSUE TITLE
How do we translate the UI language into other languages?

### ISSUE THREAD

**Issue by laichiaheng** [atom/atom#8772] opened 2015-09-13 08:15 UTC
The interface language is only in English, it should be translated into other languages.

**Comment by mnquintana** [comment] 2015-09-13 13:08
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/3103 though - closing this out in favor of that issue.

**Closed by mnquintana** 2015-09-13 13:08 UTC
