### ISSUE TITLE
release update shows wrong version on about page

### ISSUE THREAD

**Issue by crostine** [atom/atom#13537] opened 2017-01-04 08:34 UTC
Hello,

Today Atom got an update and I noticed the version wasn't showing correct.
It shows the current version on top right under ATOM and in the little box with the 'restart and install' button it says 'new update [current version]' instead of 'new update [new version]' .
![atomversion](https://cloud.githubusercontent.com/assets/5873080/21635781/cd6f6476-d25f-11e6-8c39-3105a1815545.png)
In safemode the update is already installed which is odd because I hadnt accepted it yet.
I can not reproduce this at this time becouse atom is already updated, but I can imagine this happens every patch like it has before.

**Comment by mnquintana** [comment] 2017-01-04 08:54
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

This also looks to be a duplicate of https://github.com/atom/about/issues/44

**Closed by mnquintana** 2017-01-04 08:54 UTC
