### ISSUE TITLE
Certain characters not recognized

### ISSUE THREAD

**Issue by MyNameIsJulien** [atom/atom#8975] opened 2015-09-28 13:58 UTC
I have witnessed a bug in the newest version of Atom.
Certain characters are simply not being recognized.

For instance, I am unable to type '~','@', and 'E'. 
This occurred sudenly to me right now and persists even when I am restarting
the application (also in "atom --safe"). Switching to other files does NOT
fix this behaviour.

I am using the newest version 1.0.19 on Windows 10 for a C++ Project.

**Comment by mnquintana** [comment] 2015-09-28 14:13
What keyboard layout are you using?

**Comment by MyNameIsJulien** [comment] 2015-09-28 16:30
I am using the german one. It behaves like it should, except for the three
characters as described above.

It worked like charm 'till today.

**Comment by ComSecNinja** [comment] 2015-09-29 14:40
Finnish keyboard works otherwise fine but  `\` is not working. It is typed with `AltGr + +`, in which `+` means the key right of zero in the number row.

**Comment by MyNameIsJulien** [comment] 2015-09-29 15:22
Just checked for curiosity. "\" is not recognized either.
I usually type these characters this way:
AltGr + Q = @
AltGr + E = €
AltGr + '+' = ~
AltGr + ß  = \

'\' seems to be a binded key. It collapses the code, whenever it can.

**Comment by 50Wliu** [comment] 2015-09-29 15:47
Ok, then this is a duplicate of atom/atom-keymap#35 and atom/atom-keymap#37.  Installing the [keyboard-localization](https://atom.io/packages/keyboard-localization) package might help.

**Closed by 50Wliu** 2015-09-29 15:47 UTC
Labels: more-information-needed

**Comment by MyNameIsJulien** [comment] 2015-10-02 10:20
Thanks, fixed it, but let me quote:
" Why the fuck is this not considered a standard plug in?"

**Comment by benogle** [comment] 2015-10-02 17:51
Fixing these issues is on our list. Sorry for the inconvenience.
