### ISSUE TITLE
Can not do backslash with BÉPO keyboard layout on Windows in

### ISSUE THREAD

**Issue by Dragnalith** [atom/atom#5906] opened 2015-03-09 10:04 UTC
I am using [BÉPO keyboard layout](http://bepo.fr/wiki/Accueil) and I am not able to produce a *"\"* in the _atom-text-editor_. However it works fine in _setting menu_ and in the _command prompt_ (ctrl+shift+p menu), and everything word fine if I switch to a QWERTY or AZERTY layout.

_Repro case:_ With standard windows BÉPO driver, inside a text editor tab, press AltGr+à (which is AtlGr+w in QWERTY, or to be precise 0xE011+0x1A from a scan code point of view) and observe it does not produce a backslash.

It may be similar to #1625

**Comment by 50Wliu** [comment] 2015-03-09 13:01
Duplicate of atom/atom-keymap#35, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-09 13:01 UTC

**Comment by Dragnalith** [comment] 2015-10-04 11:44
Hi @50Wliu, I am asking you to re-open this issue please.

I have followed https://github.com/atom/atom-keymap/issues/35 for months now, and this issue is not related to https://github.com/atom/atom-keymap/issues/35.

Indeed, backslash character works fine everywhere inside Atom **except in the text-editor**. Whereas the https://github.com/atom/atom-keymap/issues/35 is a lower level issue related to key events.

**Comment by 50Wliu** [comment] 2015-10-04 15:50
So to confirm: Does installing the keyboard-localization package not help?  In addition, can you see if atom/atom-keymap#37 is related to your issue?

**Comment by Dragnalith** [comment] 2015-10-04 18:27
So my bad, I can fix the issue with keyboard-localization. But the fact that it works everywhere except in the text editor view still make it different from the issue of other people.
Anyway it can remain closed. Sorry about the false alarm.
