### ISSUE TITLE
Uncaught Error: EACCES - Atom should handle the failure more gracefully

### ISSUE THREAD

**Issue by yvan-sraka** [atom/atom#4797] opened 2014-12-29 19:26 UTC
Steps to reproduce:

1. Open a file in atom with the package `vim-mode` enabled.
2. Change the file permissions.
3. <kbd>Esc</kbd> <kbd>i</kbd> (switch to insert mode).

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES, open '/Users/Yvan/Downloads/test.css'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

Error: EACCES, open '/Users/Yvan/Downloads/test.css'
  at Error (native)

```

### Commands

```
     -0:00.0 vim-mode:activate-insert-mode (input.hidden-input)
```

### Config

```
{
  "editor": {
    "fontSize": 12,
    "tabLength": 4,
    "showInvisibles": true,
    "softWrap": true,
    "autoIndentOnPaste": false
  }
}
```

### Installed Packages

```coffee
# User
ascii-codes, v0.3.3
autocomplete-plus, v1.0.0
color-picker, v1.2.6
editor-stats, v0.16.0
file-icons, v1.4.3
html-entities, v0.2.0
language-haskell, v1.0.0
language-latex, v0.4.1
language-rust, v0.3.2
language-viml, v0.2.0
linter, v0.9.0
linter-coffeelint, v0.1.7
linter-javac, v0.1.3
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-pylint, v0.2.0
linter-rubocop, v0.2.1
linter-scalac, v0.3.3
linter-scss-lint, v0.0.11
linter-shellcheck, v0.0.6
linter-xmllint, v0.0.5
minimap, v3.4.9
project-manager, v1.14.1
tabs-to-spaces, v0.8.0
travis-ci-status, v0.11.1
vim-mode, v0.22.0
visual-bell, v0.9.0

# Dev
No dev packages
```

**Comment by yvan-sraka** [comment] 2015-01-02 19:04
`$ chmod 000 test.css`, then atom asks for my password and I have the bug.

The stack trace may change, for example, this time I got this:

### Stack Trace

Uncaught Error: EACCES, open '/Users/Yvan/Desktop/test.css'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

Error: EACCES, open '/Users/Yvan/Desktop/test.css'
  at Error (native)
  at Ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:47:28)
  at BrowserWindow.RemoteMemberFunction [as getSize] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at Atom.module.exports.Atom.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom.js:501:29)
  at Atom.module.exports.Atom.storeDefaultWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom.js:533:25)
  at /Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:95:21
  at handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -1:09.7 vim-mode:move-right (input.hidden-input)
     -0:30.3 vim-mode:activate-insert-mode (input.hidden-input)
     -0:21.4 vim-mode:activate-command-mode (input.hidden-input)
     -0:20.4 vim-mode:activate-insert-mode (input.hidden-input)
     -0:15.6 core:save (input)
     -0:14.4 core:backspace (input.hidden-input)
     -0:12.2 core:save (input.hidden-input)
     -0:03.1 vim-mode:activate-command-mode (input.hidden-input)
     -0:02.7 vim-mode:activate-insert-mode (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

**Comment by maxbrunsfeld** [comment] 2015-01-02 19:40
Ok, so you're denying yourself read or write access to the file? So Atom *should* be unable to open the file. Do you just mean that Atom should handle the failure more gracefully?

**Comment by yvan-sraka** [comment] 2015-01-02 19:53
Yes, that's what I meant. Of course, I understand that atom could not open my file, but not why he told me that with an `Uncaught Error`.

**Comment by maxbrunsfeld** [comment] 2015-01-02 19:56
I agree; we should be handling this error better. Thanks!

**Comment by izuzak** [comment] 2015-01-02 19:59
If I understood the request correctly, this might be a duplicate of https://github.com/atom/atom/issues/1405

**Comment by maxbrunsfeld** [comment] 2015-01-02 20:05
Yeah, you're right. Closing in favor of that issue. Thanks, @izuzak!

**Closed by maxbrunsfeld** 2015-01-02 20:05 UTC
Labels: enhancement
