### ISSUE TITLE
version 1.19, input Chinese is very strange

### ISSUE THREAD

**Issue by buuug7** [atom/atom#15281] opened 2017-08-13 08:09 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
when input Chinese the editor is very strange.the cursor jump up left top corner and down current line , makes me very uncomfortable. but use version 1.18, everything is good.  
i sure my Chinese input is no problem, i test with several text editor and several Chinese input tools, only atom(v1.19) is very strange.  
like below gif image show , whether input how many letters, only one letter is shown.  
so i could not input Chinese correctly.

### Steps to Reproduce
![201708130435001502613300943_small](https://user-images.githubusercontent.com/12119289/29248255-3c14b40a-8046-11e7-8dfa-03200f4ae5c3.gif)

### Versions
```
// atom --version
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

// apm --version
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.3

// system info
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

### Additional Information

no additional information.

**Comment by Ben3eeE** [comment] 2017-08-13 08:57
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14911.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-13 08:57 UTC
Labels: duplicate
