### ISSUE TITLE
Ability to configure find/search to be like gedit

### ISSUE THREAD

**Issue by pknowles** [atom/atom#9962] opened 2015-12-07 00:33 UTC
Gedit 3 has the most convenient find feature I've ever used.

- Ctrl-f brings up a very tiny input box in the top right which doesn't obscure any code.
- Results are shown to you as you start typing, without having to hit enter.
- Down/up arrows select the next/previous results.
- Enter exits the search, leaving the current result selected.
- Esc exits the search but puts you back where you started before searching.

I've managed to get down/up arrows working, but there doesn't seem to be a way to exit find and replace with anything other than hitting esc. Furthermore, recording the state before the search begins is beyond simple keymapping.
```cson
'.find-and-replace, .project-find, .project-find .results-view':
  'up': 'find-and-replace:show-previous'
  'down': 'find-and-replace:confirm'
```
Are these enter/esc actions something that could make it into the core find-and-replace?

**Comment by lee-dohm** [comment] 2015-12-09 06:04
This seems to be a duplicate of https://github.com/atom/find-and-replace/issues/367 and at least the "jump to first match on type" was implemented as an option in https://github.com/atom/find-and-replace/pull/427. If there is more that you are looking for, can you open a new issue on the find-and-replace package?

**Closed by lee-dohm** 2015-12-09 06:04 UTC
