### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Becca/Downloads/Atom.app'

### ISSUE THREAD

**Issue by beccasjames** [atom/atom#10825] opened 2016-02-15 19:17 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Becca/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/Becca/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Becca/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -7:27.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -7:26.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -7:25.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:50.2.0 core:save (atom-text-editor.editor.is-focused)
     -4:06.1.0 core:save-as (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:39.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:39.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:39.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:37.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:35.2.0 core:save (atom-text-editor.editor.is-focused)
  4x -2:14.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:02.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:19.4.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -1:08.9.0 tree-view:remove (span.name.icon.icon-file-directory)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joshaber** [comment] 2016-02-15 19:24
This looks like a duplicate of #10774. Feel free to subscribe there for updates!

**Closed by joshaber** 2016-02-15 19:24 UTC
