### ISSUE TITLE
Uncaught Error: No line exists for row 11. Last screen row: 10

### ISSUE THREAD

**Issue by mvpgomes** [atom/atom#5899] opened 2015-03-08 12:40 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: No line exists for row 11. Last screen row: 10

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:385

Error: No line exists for row 11. Last screen row: 10
  at TextEditorPresenter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:385:19)
  at TextEditorPresenter.module.exports.TextEditorPresenter.batch (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:91:12)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:375:19)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:123:14)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:172:38)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:280:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:159:9)
  at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:61

```

### Commands

```
     -0:05.3 editor:indent (atom-text-editor.editor.is-focused)
     -0:05.1 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.1 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.1 editor:indent (atom-text-editor.editor.is-focused)
     -0:04.9 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:04.9 snippets:expand (atom-text-editor.editor.is-focused)
     -0:04.9 editor:indent (atom-text-editor.editor.is-focused)
     -0:03.2 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:03.2 snippets:expand (atom-text-editor.editor.is-focused)
     -0:03.2 editor:indent (atom-text-editor.editor.is-focused)
     -0:02.9 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.9 snippets:expand (atom-text-editor.editor.is-focused)
     -0:02.9 editor:indent (atom-text-editor.editor.is-focused)
     -0:02.7 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.7 snippets:expand (atom-text-editor.editor.is-focused)
     -0:02.7 editor:indent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "invisibles": {},
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
autocomplete-plus, v2.4.1
autocomplete-snippets, v1.0.1
color-picker, v1.4.4
emmet, v2.3.4
highlight-line, v0.10.1
javascript-snippets, v1.0.0
jshint, v1.3.0
language-latex, v0.4.1
language-puppet, v0.10.0
latex, v0.19.1
linter, v0.12.0
minimap, v4.5.0
pdf-view, v0.17.0

# Dev
No dev packages
```

**Comment by Moter8** [comment] 2015-03-08 13:29
@mvpgomes Please, reporting issues without typing in what you did is not useful. You are supposed to enter steps so people can try to reproduce the bug.
```
[Enter steps to reproduce below:]

...
...
```

Anyway, it's a duplicate of #5667.

**Closed** 2015-03-08 16:19 UTC
