### ISSUE TITLE
Failed to activate the ionide-installer package

### ISSUE THREAD

**Issue by sunitjoshi** [atom/atom#9091] opened 2015-10-08 21:18 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro N
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the ionide-installer package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\sjoshi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.activate (C:/Users/sjoshi/Downloads/AtomPackages/ionide-installer-1.3.0/lib/installer.js:4:21)
    at Package.module.exports.Package.activateNow (C:\Users\sjoshi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:245:19)
    at C:\Users\sjoshi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:226:30
    at Package.module.exports.Package.measure (C:\Users\sjoshi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
    at Package.module.exports.Package.activate (C:\Users\sjoshi\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:218:14)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
ionide-installer, v1.3.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-10-09 01:30
This seems to be a duplicate of ionide/ionide-installer#5, so please subscribe there for updates.

**Closed by 50Wliu** 2015-10-09 01:30 UTC
