### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by yuteshvishnu** [atom/atom#20010] opened 2019-10-12 13:54 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:166

Error: dlopen(/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/pm/q7rw1nq57bv7_rmwsdly6rlm0000gn/T/AppTranslocation/14A5A89B-F3C2-4A5E-80C6-129FC4EBFA02/d/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -8:57.4.0 tree-view:copy-full-path (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose-html-plus 0.27.1 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-jshint 3.1.17 
linter-ui-default 1.8.0 
pigments 0.40.2 
```

**Comment by rsese** [comment] 2019-10-14 22:21
Thanks for the report! If you quit and reinstall Atom, does that clear things up for you?  Going to go ahead and close since I think this is a duplicate of https://github.com/atom/atom/issues/14461 (the error messages are a bit different) but let me know if you still have trouble after reinstalling.

**Closed by rsese** 2019-10-14 22:21 UTC
