### ISSUE TITLE
After replacing all items found during search and replace, Find button remains covered by "Replace Next" balloon

### ISSUE THREAD

**Issue by psnider** [atom/atom#8586] opened 2015-08-31 01:37 UTC
This ballon remains for a long period of time, and I haven't figured out yet when it disappears.

This  prevents me from clicking on the buttons underneath the balloon,
such as the "Whole Word" button.

I'll add a screenshot the next time I see it.

**Comment by 50Wliu** [comment] 2015-08-31 01:40
Duplicate of atom/find-and-replace#501, please subscribe there for updates.

**Closed by 50Wliu** 2015-08-31 01:40 UTC

**Comment by SlimeQ** [comment] 2015-09-02 22:52
[find and replace bug](http://i.imgur.com/rCpiaTy.png)

this is so bad, i don't understand why this was closed
