### ISSUE TITLE
json highlighting is broken in atom 1.38.0

### ISSUE THREAD

**Issue by zorn-v** [atom/atom#19498] opened 2019-06-12 03:31 UTC
As you can see almost is underscored and "marked" as "links"
Also invalid sintax is not recognized (marked by red rectangle by me)
![bug screen](https://i.imgur.com/BvZwwBe.png)

**Comment by Arcanemagus** [comment] 2019-06-12 03:35
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-json/issues/75. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-06-12 03:35 UTC
