### ISSUE TITLE
Async save

### ISSUE THREAD

**Issue by dtruel** [atom/atom#6761] opened 2015-05-13 00:10 UTC
Hello,

Atom is great.  I am working with a cloud server and don't have the fastest internet connection.  I have the server mounted via win-sshfs.  When I save, it sometimes takes 5-10 seconds for the file to get transferred and saved, and Atom is completely frozen during that time.  It would be great if Atom had the option to do asynchronous saves so that I could keep editing while the file is being uploaded to the server.

**Comment by thomasjo** [comment] 2015-05-13 07:29
Closing this as a duplicate of https://github.com/atom/atom/issues/477.

Also note that @maxbrunsfeld and @nathansobo are actively working on improving file handling performance (in particular large files), so it's likely that this is something they will touch on in relation to that work.

**Closed by thomasjo** 2015-05-13 07:29 UTC
Labels: duplicate

**Comment by dtruel** [comment] 2015-08-10 23:00
Found a solution for my specific problem, in case anyone has the same.  The remote-ftp package allows connecting to sshfs/sftp/ftp and saves nearly instantly without a problem

https://atom.io/packages/remote-ftp
