### ISSUE TITLE
new release version have many error

### ISSUE THREAD

**Issue by crperlin** [atom/atom#9210] opened 2015-10-19 07:20 UTC
new release version have many error;

minimap and color-picker , atom-beautify can't start; Enable plugins  show many error ;

Sometimes they are given information directly to the collapse of the card

my plugins list :
 
```json
[
	{
		"name": "advanced-open-file",
		"version": "0.11.0"
	},
	{
		"name": "atom-alignment",
		"version": "0.12.1"
	},
	{
		"name": "atom-beautify",
		"version": "0.28.14"
	},
	{
		"name": "atom-bootstrap3",
		"version": "1.2.12"
	},
	{
		"name": "atom-ctags",
		"version": "4.3.0"
	},
	{
		"name": "atom-html-preview",
		"version": "0.1.11"
	},
	{
		"name": "atom-material-ui",
		"version": "0.6.2",
		"theme": "ui"
	},
	{
		"name": "atom-minify",
		"version": "0.4.2"
	},
	{
		"name": "atom-shortcuts",
		"version": "0.0.2"
	},
	{
		"name": "atom-ternjs",
		"version": "0.8.4"
	},
	{
		"name": "autoclose-html",
		"version": "0.19.0"
	},
	{
		"name": "autocomplete-html-entities"
	},
	{
		"name": "autocomplete-paths",
		"version": "1.0.2"
	},
	{
		"name": "autoprefixer",
		"version": "3.1.0"
	},
	{
		"name": "bottom-dock",
		"version": "0.3.5"
	},
	{
		"name": "chester-atom-syntax",
		"version": "0.1.1",
		"theme": "syntax"
	},
	{
		"name": "css-snippets",
		"version": "0.9.0"
	},
	{
		"name": "csscomb",
		"version": "0.3.1"
	},
	{
		"name": "docblockr",
		"version": "0.7.3"
	},
	{
		"name": "editorconfig",
		"version": "1.2.0"
	},
	{
		"name": "emmet",
		"version": "2.3.13"
	},
	{
		"name": "eval-javascript",
		"version": "1.2.0"
	},
	{
		"name": "ex-mode",
		"version": "0.7.0"
	},
	{
		"name": "file-icons",
		"version": "1.6.11"
	},
	{
		"name": "foldername-tabs",
		"version": "0.1.5"
	},
	{
		"name": "fonts",
		"version": "0.6.1"
	},
	{
		"name": "git-control",
		"version": "0.4.0"
	},
	{
		"name": "git-log",
		"version": "0.4.1"
	},
	{
		"name": "gulp-manager",
		"version": "0.2.11"
	},
	{
		"name": "highlight-selected",
		"version": "0.10.1"
	},
	{
		"name": "javascript-snippets",
		"version": "1.0.0"
	},
	{
		"name": "jsformat",
		"version": "0.9.0"
	},
	{
		"name": "linter",
		"version": "1.8.1"
	},
	{
		"name": "linter-js-standard",
		"version": "3.2.1"
	},
	{
		"name": "linter-jshint"
	},
	{
		"name": "linter-less",
		"version": "2.2.0"
	},
	{
		"name": "linter-manager",
		"version": "0.2.3"
	},
	{
		"name": "merge-conflicts",
		"version": "1.3.6"
	},
	{
		"name": "minimap",
		"version": "4.14.0"
	},
	{
		"name": "minimap-find-and-replace",
		"version": "4.3.1"
	},
	{
		"name": "nucleus-dark-ui",
		"version": "0.6.3",
		"theme": "ui"
	},
	{
		"name": "open-recent",
		"version": "2.3.0"
	},
	{
		"name": "pigments",
		"version": "0.18.0"
	},
	{
		"name": "polymer-snippets",
		"version": "2.0.2"
	},
	{
		"name": "react",
		"version": "0.12.10"
	},
	{
		"name": "Sublime-Style-Column-Selection",
		"version": "1.3.0"
	},
	{
		"name": "sync-settings",
		"version": "0.6.0"
	},
	{
		"name": "todo-manager",
		"version": "0.2.5"
	},
	{
		"name": "tree-view-git-status",
		"version": "0.2.2"
	},
	{
		"name": "vim-mode",
		"version": "0.61.0"
	},
	{
		"name": "vim-mode-visual-block",
		"version": "0.2.13"
	},
	{
		"name": "atom-dark-syntax",
		"version": "0.27.0",
		"theme": "syntax"
	},
	{
		"name": "atom-dark-ui",
		"version": "0.51.0",
		"theme": "ui"
	},
	{
		"name": "atom-light-syntax",
		"version": "0.28.0",
		"theme": "syntax"
	},
	{
		"name": "atom-light-ui",
		"version": "0.43.0",
		"theme": "ui"
	},
	{
		"name": "base16-tomorrow-dark-theme",
		"version": "1.0.0",
		"theme": "syntax"
	},
	{
		"name": "base16-tomorrow-light-theme",
		"version": "1.0.0",
		"theme": "syntax"
	},
	{
		"name": "one-dark-ui",
		"version": "1.1.5",
		"theme": "ui"
	},
	{
		"name": "one-dark-syntax",
		"version": "1.1.1",
		"theme": "syntax"
	},
	{
		"name": "one-light-syntax",
		"version": "1.1.1",
		"theme": "syntax"
	},
	{
		"name": "one-light-ui",
		"version": "1.1.5",
		"theme": "ui"
	},
	{
		"name": "solarized-dark-syntax",
		"version": "0.38.1",
		"theme": "syntax"
	},
	{
		"name": "solarized-light-syntax",
		"version": "0.22.1",
		"theme": "syntax"
	},
	{
		"name": "about",
		"version": "1.1.0"
	},
	{
		"name": "archive-view",
		"version": "0.61.0"
	},
	{
		"name": "autocomplete-atom-api",
		"version": "0.9.2"
	},
	{
		"name": "autocomplete-css",
		"version": "0.11.0"
	},
	{
		"name": "autocomplete-html",
		"version": "0.7.2"
	},
	{
		"name": "autocomplete-plus",
		"version": "2.22.0"
	},
	{
		"name": "autocomplete-snippets",
		"version": "1.7.1"
	},
	{
		"name": "autoflow",
		"version": "0.26.0"
	},
	{
		"name": "autosave",
		"version": "0.22.0"
	},
	{
		"name": "background-tips",
		"version": "0.26.0"
	},
	{
		"name": "bookmarks",
		"version": "0.38.0"
	},
	{
		"name": "bracket-matcher",
		"version": "0.78.0"
	},
	{
		"name": "command-palette",
		"version": "0.36.0"
	},
	{
		"name": "deprecation-cop",
		"version": "0.54.0"
	},
	{
		"name": "dev-live-reload",
		"version": "0.47.0"
	},
	{
		"name": "encoding-selector",
		"version": "0.21.0"
	},
	{
		"name": "exception-reporting",
		"version": "0.37.0"
	},
	{
		"name": "find-and-replace",
		"version": "0.185.0"
	},
	{
		"name": "fuzzy-finder",
		"version": "0.90.0"
	},
	{
		"name": "git-diff",
		"version": "0.56.0"
	},
	{
		"name": "go-to-line",
		"version": "0.30.0"
	},
	{
		"name": "grammar-selector",
		"version": "0.47.0"
	},
	{
		"name": "image-view",
		"version": "0.55.0"
	},
	{
		"name": "incompatible-packages",
		"version": "0.25.0"
	},
	{
		"name": "keybinding-resolver",
		"version": "0.33.0"
	},
	{
		"name": "line-ending-selector",
		"version": "0.2.0"
	},
	{
		"name": "link",
		"version": "0.31.0"
	},
	{
		"name": "markdown-preview",
		"version": "0.154.0"
	},
	{
		"name": "metrics",
		"version": "0.52.0"
	},
	{
		"name": "notifications",
		"version": "0.59.0"
	},
	{
		"name": "open-on-github",
		"version": "0.38.0"
	},
	{
		"name": "package-generator",
		"version": "0.40.0"
	},
	{
		"name": "release-notes",
		"version": "0.53.0"
	},
	{
		"name": "settings-view",
		"version": "0.230.0"
	},
	{
		"name": "snippets",
		"version": "0.100.0"
	},
	{
		"name": "spell-check",
		"version": "0.61.0"
	},
	{
		"name": "status-bar",
		"version": "0.79.0"
	},
	{
		"name": "styleguide",
		"version": "0.44.0"
	},
	{
		"name": "tabs",
		"version": "0.84.0"
	},
	{
		"name": "timecop",
		"version": "0.33.0"
	},
	{
		"name": "tree-view",
		"version": "0.190.0"
	},
	{
		"name": "update-package-dependencies",
		"version": "0.10.0"
	},
	{
		"name": "welcome",
		"version": "0.30.0"
	},
	{
		"name": "whitespace",
		"version": "0.31.0"
	},
	{
		"name": "wrap-guide",
		"version": "0.38.0"
	},
	{
		"name": "language-c",
		"version": "0.48.0"
	},
	{
		"name": "language-clojure",
		"version": "0.18.0"
	},
	{
		"name": "language-coffee-script",
		"version": "0.42.0"
	},
	{
		"name": "language-csharp",
		"version": "0.11.0"
	},
	{
		"name": "language-css",
		"version": "0.34.0"
	},
	{
		"name": "language-gfm",
		"version": "0.81.0"
	},
	{
		"name": "language-git",
		"version": "0.10.0"
	},
	{
		"name": "language-go",
		"version": "0.39.0"
	},
	{
		"name": "language-html",
		"version": "0.42.0"
	},
	{
		"name": "language-hyperlink",
		"version": "0.14.0"
	},
	{
		"name": "language-java",
		"version": "0.16.0"
	},
	{
		"name": "language-javascript",
		"version": "0.96.0"
	},
	{
		"name": "language-json",
		"version": "0.17.0"
	},
	{
		"name": "language-less",
		"version": "0.28.2"
	},
	{
		"name": "language-make",
		"version": "0.19.0"
	},
	{
		"name": "language-mustache",
		"version": "0.13.0"
	},
	{
		"name": "language-objective-c",
		"version": "0.15.0"
	},
	{
		"name": "language-perl",
		"version": "0.30.0"
	},
	{
		"name": "language-php",
		"version": "0.30.0"
	},
	{
		"name": "language-property-list",
		"version": "0.8.0"
	},
	{
		"name": "language-python",
		"version": "0.40.0"
	},
	{
		"name": "language-ruby",
		"version": "0.60.0"
	},
	{
		"name": "language-ruby-on-rails",
		"version": "0.23.0"
	},
	{
		"name": "language-sass",
		"version": "0.42.0"
	},
	{
		"name": "language-shellscript",
		"version": "0.19.0"
	},
	{
		"name": "language-source",
		"version": "0.9.0"
	},
	{
		"name": "language-sql",
		"version": "0.17.0"
	},
	{
		"name": "language-text",
		"version": "0.7.0"
	},
	{
		"name": "language-todo",
		"version": "0.27.0"
	},
	{
		"name": "language-toml",
		"version": "0.16.0"
	},
	{
		"name": "language-xml",
		"version": "0.33.0"
	},
	{
		"name": "language-yaml",
		"version": "0.24.0"
	}
]
Raw  settings.json
{
	"exception-reporting": {
		"userId": "60996b13-4ebd-a0ab-e123-7b3de026d63b"
	},
	"welcome": {
		"showOnStartup": false
	},
	"core": {
		"packagesWithKeymapsDisabled": [
			"vim-mode"
		],
		"themes": [
			"atom-dark-ui",
			"chester-atom-syntax"
		],
		"disabledPackages": [
			"symbols-view",
			"minimap-pigments",
			"jquery-snippets",
			"color-picker"
		]
	},
	"editor": {
		"invisibles": {},
		"fontSize": 22,
		"backUpBeforeSaving": true,
		"tabLength": 4
	},
	"minimap": {
		"plugins": {
			"find-and-replace": true,
			"pigments": true
		},
		"absoluteMode": true,
		"createPluginInDevMode": true,
		"scrollAnimation": true
	},
	"tool-bar": {},
	"advanced-open-file": {
		"caseSensitiveAutoCompletion": true,
		"createFileInstantly": true,
		"helmDirSwitch": true
	},
	"atom-alignment": {
		"addSpacePostfix": true
	},
	"atom-html-preview": {
		"triggerOnSave": true
	},
	"autoclose-html": {
		"additionalGrammars": [
			"*"
		]
	},
	"docblockr": {
		"auto_add_method_tag": true,
		"deep_indent": true,
		"development_mode": true
	},
	"file-icons": {
		"forceShow": true,
		"onChanges": true
	},
	"jsformat": {
		"break_chained_methods": true,
		"eval_code": true,
		"indent_with_tabs": true,
		"jslint_happy": true,
		"space_after_anon_function": true,
		"format_on_save": false
	},
	"vim-mode": {
		"startInInsertMode": true,
		"useClipboardAsDefaultRegister": true,
		"useSmartcaseForSearch": true
	},
	"linter": {
		"showErrorTabLine": true
	},
	"fonts": {
		"fontFamily": "Roboto Mono"
	},
	"atom-ctags": {
		"autoBuildTagsWhenActive": true
	},
	"open-recent": {
		"listDirectoriesAddedToProject": true
	},
	"pigments": {
		"extendAutocompleteToVariables": true
	},
	"linter-jshint": {
		"lintInlineJavaScript": true
	},
	"color-picker": {
		"abbreviateValues": true,
		"automaticReplace": true,
		"preferredFormat": "HEX",
		"triggerKey": "E"
	},
	"react": {
		"enabledForAllJavascriptFiles": true
	},
	"atom-ternjs": {},
	"flex-tool-bar": {},
	"linter-scss-lint": {},
	"atom-beautify": {
		"_analyticsUserId": "d4b978e2-d1f6-4f5c-8c34-e0b6a7d8b2ed"
	},
	"atom-minify": {
		"jsMinifier": "Google Closure Compiler",
		"notifications": "Panel, Notifications",
		"showStartMinificationNotification": true
	},
	"simplified-chinese-menu": {
		"useSetting": false,
		"useMenu": false,
		"useContext": false
	},
	"bottom-dock": {
		"startOpen": true
	},
	"linter-js-standard": {
		"showEslintRules": true
	},
	"todo-manager": {}
}
```

**Comment by 50Wliu** [comment] 2015-10-19 11:47
Hey @crperlin, I think this is a duplicate of #8891.  Can you try updating to Atom [1.1.0-beta1](https://github.com/atom/atom/releases/tag/v1.1.0-beta1) and see if that fixes your issue?  Thanks!

**Closed by 50Wliu** 2015-10-19 11:47 UTC
