### ISSUE TITLE
GIRL Emoji with the FITZ-3 modifier rendering as two separate characters

### ISSUE THREAD

**Issue by TELunus** [atom/atom#13615] opened 2017-01-13 23:28 UTC
[Description of the issue]

The GIRL Emoji with the FITZ-3 modifier, which renders correctly according to the Unicode specification in Chromium as a FITZ-3 GIRL , renders as default GIRL emoji followed separately by a square showing the FITZ-3 skin tone.

### Steps to Reproduce

0. Have an Emoji font that supports the Fitzpatrick modifiers installed.  I'm using Google's Noto Color Emoji from https://noto-website-2.storage.googleapis.com/pkgs/Noto-hinted.zip
1. Open a shell in a terminal emulator.  I'm using ZSH in Guake
2. Run Atom from your shell.  I'm doing this as `atom --clear-window-state --safe`
3. Open Chromium
4. In Chromium go to https://en.wikipedia.org/wiki/Emoji#Skin_color
5. Select the FITZ-3 GIRL as shown here: ![screenshot4](https://cloud.githubusercontent.com/assets/2502960/21948798/3c01154e-d9a2-11e6-88da-eed671baf07f.png)

6. Copy with Ctrl+C
7. Switch to Atom
8. Create a new document in Atom with Ctrl+N
9. Paste with Ctrl+V

**Expected behavior:** FITZ-3 GIRL is rendered according to the Unicode specification, as Chromium does as shown here: ![screenshot2](https://cloud.githubusercontent.com/assets/2502960/21948334/5d7f5cf6-d99f-11e6-919f-ba40670da3eb.png) 

**Actual behavior:** The default GIRL emoji followed by seperate FITZ-3 modifier is shown as shown here: ![screenshot5](https://cloud.githubusercontent.com/assets/2502960/21948848/93aa9720-d9a2-11e6-9c87-f95e1bccf823.png)

**Reproduces how often:** Every time

### Versions
Atom version info:
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12+
git 2.9.3

OS info:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety

### Additional Information

I doubt these matter, but the issue posting guide says I should include them:

I have not installed any packages after installing Atom
I just installed Atom for the first time, and as such have not tested this on other versions.
I have not changed any Atom configuration files.
I only have one monitor.
I use the us-dvorak keyboard layout.

Please let me know if there is something else I should include.

**Comment by 50Wliu** [comment] 2017-01-14 01:02
I cannot reproduce this on Atom 1.15.0-dev-d5785a1 (Electron 1.4 + latest master).  It looks like this is the same as #13360 though, so I'm going to close this issue in favor of that one.

**Closed by 50Wliu** 2017-01-14 01:02 UTC
