### ISSUE TITLE
Using escape character in string messes with character pair overwriting.

### ISSUE THREAD

**Issue by nerssi** [atom/atom#8959] opened 2015-09-26 21:03 UTC
Sorry if the title is vague, the problem is a bit hard to put in to words. The following gif illustrates the problem:

![atom-string-escape-bug](https://cloud.githubusercontent.com/assets/5460027/10119816/ff03333c-6456-11e5-96b8-53083abdb540.gif)

**Comment by izuzak** [comment] 2015-09-26 21:08
Thanks for the report -- I think this is a duplicate of https://github.com/atom/bracket-matcher/issues/80.

**Closed by izuzak** 2015-09-26 21:08 UTC
