### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by wdanilo** [atom/atom#11757] opened 2016-05-15 20:20 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When I switch desktops on my Linux box (Gentoo, Awesome WM without other graphic environments) After one or two switches Atom crashesh displaying error "The Editor has crashed ...". After reloading the window it works unless I switch the desktops again.

### Steps to Reproduce

1. launch atom
2. Switch to other desktop and switch back
3. Repeat the step 2. several times fast enough (I noticed that when I'm switching desktop every 15-20 seconds, the issue appears but not so often. If I switch it in 1-5 seconds it appears almost always).
3. The error appears. Restart Atom -> point 1

**Expected behavior:** [What you expected to happen]

The app should not crash.

**Actual behavior:** [What actually happened]

The app Crashes.

### Versions

Atom    : 1.7.3
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 5.10.1
python 3.4.3
git 2.7.3

Os: Gentoo linux (rolling release, no version)

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Nikki1993** [comment] 2016-05-16 10:23
I believe this is a duplicate of [#11198](https://github.com/atom/atom/issues/11198)

Same issue, electron needs a version bump (fix has been merged into master) to resolve issue with fontconfig.

**Comment by wdanilo** [comment] 2016-05-16 13:12
It seems relevant. Unfortunetally Gentoo maintainers removed older version of electron fro mthe repo (which is strange), so I cannot downgrade it :/

**Comment by Nikki1993** [comment] 2016-05-16 15:04
@wdanilo you could always just build from source on master branch, that has electron version bump.

**Comment by wdanilo** [comment] 2016-05-16 15:51
Of course, but this is just some kind of work-around that makes my system inconsistent in some way. Anyway I'll do this way :)

**Comment by 50Wliu** [comment] 2016-05-16 20:25
Ok, closing as a duplicate of #11198.

**Closed by 50Wliu** 2016-05-16 20:25 UTC
Labels: crash, linux
