### ISSUE TITLE
Uncaught The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Jihoon** [atom/atom#20021] opened 2019-10-16 11:53 UTC
I'm re-opening this because #19081 is closed.

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

[Enter steps to reproduce:]

1. Open a file
2. Press ctrl-s

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)
    at onEvents.e.map.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:24548)
    at Array.map (<anonymous>)
    at watcher.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:24400)
```

### Commands

```
     -1:31.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Reproduces how often:**

100%

**Comment by Jihoon** [comment] 2019-10-16 11:58
I can now see it is only for the files on network drives. Probably this is an issue linked to the GitKraken failure with repositories on network drives.

**Comment by rsese** [comment] 2019-10-16 17:46
Thanks for opening a new issue for this - based on the error and the fact that you're using a network drive, I think this is a duplicate of https://github.com/atom/atom/issues/14227 so you can subscribe there for updates if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-10-16 17:46 UTC
