### ISSUE TITLE
no mnemonics in menus (File, Edit, ...)

### ISSUE THREAD

**Issue by kolAflash** [atom/atom#6666] opened 2015-05-06 07:22 UTC
My system:
Linux
Desktop: KDE 4.14.6

In the menus there are any mnemonics shown at all!
(the menu buttons themselves show mnemonics when pressing ALT)
E.g. in File menu:

```
New Window
New File
Open File
...
```

don't show any mnemonics. Also when pressing "ALT" while menu is opened.
Nevertheless, mnemonics seem to be there (but not shown). If I press "n" while in File menu (found out by guessing) Atom opens a new file.

**Comment by kolAflash** [comment] 2015-05-06 08:05
In Gnome 3.14 applications like file-roller, the mnemonics in the menu are always shown once the menu is opened.

E.g.:
File -> Open (the O is underlined)

**Comment by kolAflash** [comment] 2015-05-07 13:17
Guess this is not just an enhancement but a bug.

At least the lack of mnemonics in the menus. Because on Windows there are mnemonics in the menus.

**Comment by NullVoxPopuli** [comment] 2015-09-03 17:17
I would actually like a way to disable this. 
I'm having difficult splitting panes right now, because of some state I get in where alt only effects the menu (I use alt-arrow keys for pane splitting)

**Comment by kolAflash** [comment] 2015-09-27 21:23
Anyone else having this issue?

I don't think it's hard to find the reason for this if you have some knowledge of the source (which I unfortunately don't have).

**Comment by impinball** [comment] 2015-11-08 11:29
I don't have the issue. I'm running Ubuntu GNOME 14.04, 64-bit.

**Comment by kolAflash** [comment] 2016-02-23 07:09
This is what it looks like for me on Ubuntu GNOME 15.10.

Pressing ALT to show mnemonics. Now Atom shows a mnemonic for each menu.
![alt-pressed](https://cloud.githubusercontent.com/assets/3355089/13243948/e5222078-da02-11e5-9e57-40d9629a59ff.png)

Pressing ALT-F to open the File menu. But there are no more mnemonics. Either for the different menus (File, Edit, View, ...) nor for the entries in the menus ("New Window", "New File", "Open File", ...).
![menu-opened](https://cloud.githubusercontent.com/assets/3355089/13243950/e897cca8-da02-11e5-9243-c4ccca90bd25.png)

Pressing just ALT on Windows (8.1) looks the same.
![alt-pressed_win](https://cloud.githubusercontent.com/assets/3355089/13244206/a5f8f1c2-da04-11e5-8f5f-cb5aa51c8cae.png)

But pressing ALT-F on Windows also gives mnemonics in the menus.
![menu-opened_win](https://cloud.githubusercontent.com/assets/3355089/13244217/b56d7ad8-da04-11e5-9ac9-f9649c0c2fa1.png)

**Comment by isiahmeadows** [comment] 2016-02-25 04:01
I can confirm on Ubuntu 15.10 as well. It's inconvenient on rare occasion,
but in practice I hardly notice. Low priority for me to want fixed.

**Comment by rivis** [comment] 2017-01-08 07:14
I have the same issue.

Atom: 1.12.9
OS: Debian GNU/Linux 8.6 (jessie)
Desktop: Xfce4 4.10

This issue was the largest blocker for me to move to Atom from other editors because I usually use the menu by mnemonic key strokes to run commands which don't have key-bindings or I can't remember key-bindings of.

Until the issue is fixed, I wrote a script in `$HOME/.atom/init.js` to show mnemonics in menu labels.

```javascript
(() => {
    let appendMnemonic = (menuList) => {
        menuList.forEach((menu) => {
            if (menu.label) {
                let amp = menu.label.indexOf('&');
                if (amp >= 0) {
                    let mnemonic = menu.label.charAt(amp + 1).toUpperCase();
                    menu.label = `${menu.label}  (${mnemonic})`;
                }
            }
            if (menu.submenu) {
                appendMnemonic(menu.submenu);
            }
        })
    }
    appendMnemonic(atom.menu.template);
    atom.menu.update();
})();
```

![atom-mnemonics](https://cloud.githubusercontent.com/assets/9392077/21748008/6de5fa96-d5bc-11e6-988e-1f15eba0b598.png)

**Comment by jsolisu** [comment] 2017-01-08 16:14
I don´t have the issue on Windows 10.

**Comment by 50Wliu** [comment] 2017-01-08 17:14
> I don´t have the issue on Windows 10.

Yep, because this is a Linux-only bug.

**Comment by kolAflash** [comment] 2018-01-10 16:45
Bug is still existing in 1.23.3 without any changes to what I previously reported.

**Comment by daviwil** [comment] 2019-01-24 01:01
Looks like this has been fixed by Electron 3 based on a quick check using my Manjaro Linux machine!  Keep an eye on this PR for when the Electron 3 upgrade is complete: https://github.com/atom/atom/pull/18603

**Comment by 50Wliu** [comment] 2019-03-15 03:28
New Electron 3 PR is #18916.

**Closed** 2019-05-20 13:20 UTC
Labels: bug, electron, linux
