### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replaceChild' of null

### ISSUE THREAD

**Issue by ungb** [atom/atom#16622] opened 2018-01-23 21:17 UTC
[Enter steps to reproduce:]
Repro and initially found by @Ben3eeE 

Initial setup: Make sure you have `Preserve Last Search` enabled in command palette package
![image](https://user-images.githubusercontent.com/5624870/35301218-cc957540-003f-11e8-9009-7091b12dadd4.png)

1. Open `text-editor-component.js`
2. Open `command-palette`
3. Type `ap` in the `command-palette` and close it
4. Switch to settings-view tab
5. Open `command-palette` and type something

**Atom**: 1.25.0-dev-c100ad010 x64
**Electron**: 1.7.10
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

see gif:
![replace child of null 2](https://user-images.githubusercontent.com/5624870/35301149-ab4b733a-003f-11e8-9071-e75c7c0c259d.gif)

### Stack Trace

Uncaught TypeError: Cannot read property 'replaceChild' of null

```
At /Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:462

TypeError: Cannot read property 'replaceChild' of null
    at ListItemView.update (/Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:462:34)
    at updateComponent (/Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:52:19)
    at patch (/Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:16:25)
    at updateChildren (/Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateSync (/Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:116:26)
    at /Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:72:13
    at ViewRegistry.performDocumentUpdate (/Users/ungb/github/atom/out/Atom.app/Contents/Resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -3:30.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -3:28.2.0 core:confirm (input.hidden-input)
     -3:15 command-palette:toggle (input.hidden-input)
     -3:13.2.0 editor:consolidate-selections (input.hidden-input)
     -3:13.2.0 core:cancel (input.hidden-input)
     -3:12.5.0 settings-view:open (input.hidden-input)
     -3:11.9.0 command-palette:toggle (div.panels-item)
     -3:10.4.0 core:backspace (input.hidden-input)
     -2:45 command-palette:toggle (input.hidden-input)
     -2:42.5.0 core:confirm (input.hidden-input)
     -2:42.5.0 application:zoom (input.hidden-input)
     -2:38.3.0 command-palette:toggle (div.panels-item)
  2x -2:37.3.0 core:backspace (input.hidden-input)
     -0:25.5.0 settings-view:open (div.panels-item)
     -0:23 core:confirm (input.hidden-input)
  2x -0:16 command-palette:toggle (input.hidden-input)
```

### Non-Core Packages

```
teletype 0.6.0 
```
see the following exceptions:

![image](https://user-images.githubusercontent.com/5624870/35301206-c3ae75a8-003f-11e8-88e6-32be1469cc15.png)

/cc @Ben3eeE @rsese

**Comment by ungb** [comment] 2018-01-23 21:38
This doesn't repro in 1.23.3, but repros in `1.24.0-beta3` and master

**Comment by Ben3eeE** [comment] 2018-01-29 11:46
If you scroll down to the bottom of the list before the last step there are a number of items without a name:

![image](https://user-images.githubusercontent.com/1058982/35508848-2c7aab9a-04f2-11e8-93b8-2059da31506f.png)

**Comment by daviwil** [comment] 2018-02-06 21:58
It looks like PR atom/atom-select-list#22 might have caused a regression here since it attempts to virtualize the list view for better rendering performance.  Still investigating.

**Comment by daviwil** [comment] 2018-02-07 17:45
@as-cii @t9md This problem occurs at this line in atom-select-list:

https://github.com/atom/atom-select-list/blob/b989655f536418ac6d59506e03e03dd5a04ce811/src/select-list-view.js#L449

It seems that `update()` is being called on nodes that haven't yet been added to the DOM, hence having no `parentNode` yet.  Since `ListItemView.update()` expects there to be a `parentNode` on the current `element`, this error is thrown.

The simplest solution is checking for `parentNode` to contain a node before calling `replaceChild`, but I think this may be avoiding a larger issue.  When I made this simple change, I saw missing items in the command palette similar to the screenshot @Ben3eeE [pasted in this comment](https://github.com/atom/atom/issues/16622#issuecomment-361221447).

Any thoughts on the correct solution for this?

**Comment by daviwil** [comment] 2018-02-07 20:18
I've created a PR for a temporary workaround here: https://github.com/atom/command-palette/pull/105

**Comment by t9md** [comment] 2018-02-08 02:09
@daviwil Thank you for investigating and workaround patch.
I'm investigating now, for clarity, what caused this issue is not my PR atom/atom-select-list#22.
It's element cache behavior introduced in  https://github.com/atom/command-palette/pull/94.
I could reproduce issue with just command-palette@0.42.1 with atom1.23.3 and also with 1.24.0-beta3.

Basically select-list's client(command-palette in this case) side cache is confusing and need to be very careful.
There are several cases where it should not return cached element.
I'll open issue on command palette.

Quick reaction for this issue is just remove element cache which was originally intended to improve responsiveness, but it have no noticeable perf gain in UX especially after render-on-display feat introduced.

**Comment by daviwil** [comment] 2018-02-08 02:15
@t9md I agree, after further investigation it seemed that the element cache was the problem.  Please feel free to file an issue on command-palette with the information you found, thank you!

**Comment by Ben3eeE** [comment] 2018-02-27 08:38
Closed via https://github.com/atom/command-palette/pull/109

**Closed by Ben3eeE** 2018-02-27 08:38 UTC
Labels: regression, triaged, uncaught-exception
