### ISSUE TITLE
Uncaught Error: EIO: i/o error, open '/Volumes/bifrost.melted.pw/var/www/steelbea.ms/index.html'

### ISSUE THREAD

**Issue by adendrag** [atom/atom#7289] opened 2015-06-15 19:53 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EIO: i/o error, open '/Volumes/bifrost.melted.pw/var/www/steelbea.ms/index.html'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:759

Error: EIO: i/o error, open '/Volumes/bifrost.melted.pw/var/www/steelbea.ms/index.html'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:264:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:362:21)
    at File.module.exports.File.writeSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:336:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:17)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
```

### Commands

```
     -0:06.9.0 core:paste (atom-text-editor.editor.is-focused)
 10x -0:02.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-17 12:17
Thanks for the report -- this looks like a duplicate of https://github.com/atom/atom/issues/6348.

**Closed by izuzak** 2015-06-17 12:17 UTC
Labels: error-from-open
