### ISSUE TITLE
Problems when activate Use Tree-sitter Parsers option

### ISSUE THREAD

**Issue by edarblanco** [atom/atom#17534] opened 2018-06-18 14:48 UTC
### Description
When the option is activated, Use Tree Setter Parsers in the core section, the autocompletion does not show results for the required files, it only shows the results of the snippets. I ask if it is a preconsecitated feature that must be handled in another way or it is an error, I did tests using atom-ternjs and atom-ide-ui and the result is the same

### Steps to Reproduce

1. activated option Use Tree Setter Parsers, (don't show, only snippets)
![screenshot_20180618_103129](https://user-images.githubusercontent.com/3819778/41542416-e5b5c58c-72e2-11e8-9ff2-62b1d97c10c8.png)
2. deactivated option Use Tree Setter Parsers, (show)
![screenshot_20180618_103316](https://user-images.githubusercontent.com/3819778/41542469-08263c28-72e3-11e8-8bc7-a81b0249ca4e.png)

**Expected behavior:** [What you expect to happen]
Show results and parse
**Actual behavior:** [What actually happens]
It does not show results, but if it parsers
**Reproduces how often:** [What percentage of the time does it reproduce?]
All time
### Versions
Atom    : 1.27.2
Electron: 2.0.2
Chrome  : 61.0.3163.100
Node     : 8.9.3
apm  1.19.0
npm  6.1.0
node 10.4.1 x64
atom 1.27.2
python 2.7.15
git 2.17.1
System: ArchLinux 64

**Comment by rsese** [comment] 2018-06-18 20:01
Thanks for reaching out!

I *think* this is a duplicate of https://github.com/atom/autocomplete-plus/issues/962?  I think the fix isn't released in ide-typescript yet though (I'm guessing that's the ide package you're using based on your screenshot).   Let me double check on that though.

Also, it looks like you're using an unofficial build of Atom (but I was able to reproduce the behavior on macOS 10.12.6 with Atom 1.29.0-dev-3717b48ba) :

> Atom : 1.27.2
> Electron: 2.0.2

Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/).

**Comment by edarblanco** [comment] 2018-06-18 20:40
Thanks for everything, I will follow your advice, and I will verify, since after a little Atom 1.27.2 works with Electron 1.7.15, so I will upload the Atom version and comment, as it was all

**Comment by lee-dohm** [comment] 2018-07-23 18:56
To our understanding, this is fixed now. Please let us know if this is not the case.

Thanks for reporting!

**Closed by lee-dohm** 2018-07-23 18:56 UTC
