### ISSUE TITLE
Invisibles hard tab after indent is misleading

### ISSUE THREAD

**Issue by polarathene** [atom/atom#10733] opened 2016-02-09 00:41 UTC
I've just noticed that hard tab after indents shows a tab invisible followed by however many space invisibles which is normally blank. I assumed it was being smart with space insertion, but upon opening the file in another text editor, they are in fact tabs with no spaces.

Example:

``` JS
->  ->  test->..->..
```

The space invisibles should not be rendered. That said I'd really like it if there was a way to insert soft tabs after indents and use hard tabs for indents, at first I thought this rendering issue was a feature improvement :P

Atom 1.4.3
Antergos(Arch Linux)

**Comment by Alhadis** [comment] 2016-02-26 01:19
+1, fully agreed we need a "smart tab" feature.

**Comment by lee-dohm** [comment] 2016-02-26 20:25
This is a duplicate of https://github.com/atom/atom/issues/3051. Please subscribe there for updates.

**Comment by polarathene** [comment] 2016-02-27 23:54
@lee-dohm Not a duplicate far as I can tell. I don't have an issue with how the tab is usually displayed(single char + blank spaces). This is fine, and works great for indents, after indentation, any tabs when I reported this were displaying the tab invisible followed by space invisibles, despite that no actual spaces existed. 

Pressing backspace would remove the tab, pressing tab again or consecutive times would insert the tab invisible + space invisibles each time like described above. Save the file and open it in another text editor like GEdit instead of Atom, you can verify it's just tabs inserted like you'd expect, no spaces.

The problem described here is inconsistency with the rendering of invisibles, the space invisibles should not be showing up, I was initially assuming Atom was communicating that my tabs had been converted into spaces, the tab invisible just as an indication that the 4(or whatever tab width set) spaces would be treated like a tab, but saved as spaces.

As that is no the case the tab insertions should render just like those for doing indentation. **This is a bug not a feature request like #3051 .**

**Comment by polarathene** [comment] 2016-02-28 00:01
Turns out, this is a trailing white-space bug, so it's rarely ever going to be a problem. Still a bug though?

Here's a picture:
![Invisibles rendering bug](http://i.imgur.com/h9weL17.png)

**Comment by lee-dohm** [comment] 2016-02-29 18:42
Thanks for clarifying @polarathene. I've updated the Issue to better reflect the problem you're reporting.

I was able to reproduce the issue using Atom v1.7.0-dev-92dea03 on Mac OS X 10.11.3. Here's what I did:

1. Launch Atom
1. Open the Settings View and set "Tab Type" to "hard" and "Tab Length" to 4
1. Open a new file using <kbd>Cmd+N</kbd>
1. Type the text `test`
1. Press <kbd>Tab</kbd> twice

**Expected:** To only see the tab character invisible for each <kbd>Tab</kbd>
**Actual:** The tab character invisible followed by three space character invisibles for each <kbd>Tab</kbd>

**Comment by lee-dohm** [comment] 2017-02-05 17:45
Not sure when this was fixed, but it is fixed in the latest `master`.

**Closed by lee-dohm** 2017-02-05 17:45 UTC
Labels: bug

**Comment by polarathene** [comment] 2017-02-06 00:32
@lee-dohm I just tested it with `Atom 1.14-beta2 x64`. The given example in my first post is now rendering correctly. Thanks to whomever fixed this!

Noticed a rendering issue but that's already listed in the invisibles tracking issue you created a while ago, hopefully it'll be fixable soon :)
