### ISSUE TITLE
Writting a XML DTD (Fail)

### ISSUE THREAD

**Issue by cristobal85** [atom/atom#6330] opened 2015-04-10 13:59 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: linux 3.13.0-48-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'addMarkerAtLevel' of undefined

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:128

TypeError: Cannot read property 'addMarkerAtLevel' of undefined
  at IntervalSkipList.module.exports.IntervalSkipList.placeMarker (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:379:13)
  at IntervalSkipList.module.exports.IntervalSkipList.insert (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:183:12)
  at IntervalSkipList.module.exports.IntervalSkipList.update (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:207:19)
  at Marker.module.exports.Marker.updateIntervals (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:523:37)
  at Marker.module.exports.Marker.update (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:459:14)
  at Marker.module.exports.Marker.handleBufferChange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:436:19)
  at MarkerManager.module.exports.MarkerManager.handleBufferChange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-manager.js:202:16)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:538:15)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:461:12)
  at Selection.module.exports.Selection.insertText (/usr/share/atom/resources/app/src/selection.js:452:43)
  at /usr/share/atom/resources/app/src/text-editor.js:718:31
  at /usr/share/atom/resources/app/src/text-editor.js:760:29
  at History.module.exports.History.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:119:18)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:647:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1109:26)
  at /usr/share/atom/resources/app/src/text-editor.js:754:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:1931:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:1901:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:752:19)
  at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:715:21)
  at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at /usr/share/atom/resources/app/src/text-editor-component.js:438:31
  at History.module.exports.History.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/history.js:119:18)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:647:27)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1109:26)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:436:35)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/src/text-editor-component.js:3:61)

```

### Commands

```
     -0:15.9 core:copy (atom-text-editor.editor.is-focused)
     -0:15.6 core:move-down (atom-text-editor.editor.is-focused)
     -0:14.6 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.4 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:13.9 editor:newline (atom-text-editor.editor.is-focused)
     -0:13.3 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.9 core:paste (atom-text-editor.editor.is-focused)
  2x -0:10.3 core:select-up (atom-text-editor.editor.is-focused)
 28x -0:09.7 core:select-left (atom-text-editor.editor.is-focused)
     -0:07.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:07.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:05.9 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:05.4 core:move-up (atom-text-editor.editor.is-focused)
  8x -0:04.4 core:move-left (atom-text-editor.editor.is-focused)
     -0:03.3 core:move-right (atom-text-editor.editor.is-focused)
  5x -0:03.0 core:select-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.0
linter-xmllint, v0.0.5

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-04-13 15:27
@cristobal85 Can you reliably reproduce this problem? If so, can you share the steps (and perhaps the file which you were using)?

@nathansobo Should this ever happen?

**Comment by thomasjo** [comment] 2015-04-13 15:39
I'm willing to bet this is caused by `linter-xmllint`.

**Comment by izuzak** [comment] 2015-04-13 15:45
@thomasjo Yep, definitely seems like it. Still, I'm wondering if it should be possible to cause problems like these or if we should prevent them from happening somehow.

**Comment by thomasjo** [comment] 2015-04-13 15:47
@izuzak Good point. We could simply do an existence check as early in the chain as possible I guess.

**Comment by cristobal85** [comment] 2015-04-13 16:03
I have removed linter-xmllint and I don't had any problem. I'm sorry for my English, I'm Spanish.

**Comment by 50Wliu** [comment] 2015-04-13 16:24
I'm going to close this for now.  If it occurs again without linter-xmllint please comment here!

**Closed by 50Wliu** 2015-04-13 16:24 UTC
Labels: bug, editor-rendering, more-information-needed
