### ISSUE TITLE
Can't access global commands from Atom

### ISSUE THREAD

**Issue by iraasta** [atom/atom#8059] opened 2015-07-24 11:43 UTC
Mac OS X 10.10.3
Atom 1.0

Hello, I'm the creator of [autocomplete-elixir]](https://github.com/iraasta/autocomplete-elixir) and I've got a problem with BufferedProcess spawning in atom on OS X systems.

Whenever I try to spawn global 'elixir' command from atom's BufferedProcess (childprocess.spawn doesn't work either) when it's open on OS X using Finder it cannot find it. Using the absolute path launches `elixir` successfully, but then `elixir` fails on it's dependencies in PATH variable.
There is no problem when launching atom from commandline what so ever.
It works fine on any other OS too.

iraasta/autocomplete-elixir#14

**Comment by mnquintana** [comment] 2015-07-24 12:13
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/6956 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-24 12:13 UTC
