### ISSUE TITLE
Soft wrap flickering when very close to needing a vertical scrollbar

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#15685] opened 2017-09-18 21:00 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It seems that when the editor height is very close to needing a vertical scrollbar, soft-wrapped lines will rapidly flicker.  Possibly the vertical scrollbar is showing up for a fraction of a second before realizing it's not needed and hiding again.  On occasion, the cursor is also rendered incorrectly.  In the GIF, it is incorrectly appearing as a blue block below the line where the cursor actually is.

### Steps to Reproduce

This might be difficult to repro because on my screen there's only two pixels before the scrollbar is required.

1. Have a file with soft-wrapped lines that _almost_ reaches the threshold necessary for vertical scrollbars to appear
2. Move your cursor around the file, make some random selections, etc.

**Expected behavior:** Editor contents to stay static

**Actual behavior:** Soft-wrapped lines jump around as the scrollbar appearance is constantly recalculated

**Reproduces how often:** 100%

![uh](https://user-images.githubusercontent.com/2766036/30564290-d83a26cc-9cc4-11e7-8f96-ac8db91fe700.gif)

### Versions

```
Atom    : 1.22.0-dev-b269b2086
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

If it's helpful, here's the contents of the file I was working on: https://gist.github.com/50Wliu/6d516fd9b32c1191303a5ac64ff39fe7

/cc: @nathansobo @ungb

**Comment by Arcanemagus** [comment] 2018-05-04 16:06
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17268. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-05-04 16:06 UTC
Labels: bug, editor-rendering, triaged
