### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 355Error: Cannot cal...

### ISSUE THREAD

**Issue by degosoft** [atom/atom#19527] opened 2019-06-13 19:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 355
Error: Cannot call function 'getPosition' on missing remote object 355
    at throwRPCError (C:\Users\degosoft\AppData\Local\atom\app-1.38.1\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\degosoft\AppData\Local\atom\app-1.38.1\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\degosoft\AppData\Local\atom\app-1.38.1\resources\electron.asar\browser\api\web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At C:\Users\degosoft\AppData\Local\atom\app-1.38.1\resources\electron.asar\renderer\api\remote.js:221

Error: Cannot call function 'getPosition' on missing remote object 355
Error: Cannot call function 'getPosition' on missing remote object 355
    at throwRPCError (~/AppData/Local/atom/app-1.38.1/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.38.1/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.38.1/resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at Object.exception (~/AppData/Local/atom/app-1.38.1/resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (~/AppData/Local/atom/app-1.38.1/resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.38.1/resources/electron.asar/renderer/api/remote.js:125:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:1:705873)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:1:706288)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.38.1/resources/app/static/<embedded>:11:284649)
```

### Commands

```
     -1:27.2.0 core:move-left (input.hidden-input)
  2x -1:26.5.0 core:move-right (input.hidden-input)
  2x -1:23.3.0 core:move-left (input.hidden-input)
     -1:21.6.0 core:delete (input.hidden-input)
     -1:21.6.0 core:move-right (input.hidden-input)
  3x -1:19.2.0 core:move-left (input.hidden-input)
     -1:16.6.0 core:backspace (input.hidden-input)
     -1:16.3.0 core:paste (input.hidden-input)
     -1:15.8.0 core:save (input.hidden-input)
     -1:06.1.0 core:select-left (input.hidden-input)
     -1:03.5.0 core:move-up (input.hidden-input)
     -1:01.8.0 core:move-right (input.hidden-input)
     -1:00.2.0 core:delete (input.hidden-input)
     -0:59.5.0 core:save (input.hidden-input)
     -0:46.8.0 core:select-right (input.hidden-input)
     -0:45.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-minify 0.8.0 
autoclose-html 0.23.0 
color-picker 2.3.0 
file-icons 2.1.26 
highlight-selected 0.14.0 
imagemin 1.6.1 
remember-folds 0.3.0 
sass-autocompile 0.13.5 
sort-lines 0.18.0 
split-diff 1.5.3 
sync-settings 0.8.6 
tortoise-svn 0.5.1 
```

**Comment by Arcanemagus** [comment] 2019-06-13 19:44
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16630. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-06-13 19:44 UTC
