### ISSUE TITLE
Atom auto update doesn't work for unprivileged users on OSX

### ISSUE THREAD

**Issue by ricardograca** [atom/atom#9496] opened 2015-11-09 14:43 UTC
When using Atom from an unprivileged user account and there is an update available I can see that Atom downloads it and then asks to install an update. The popup that shows up asks for my password, but since this is an unprivileged account that doesn't work. What happens in this case is that I enter the password, click on the button to install and nothing happens. I go to the Atom menu where there's now the "Restart and update" option which I choose.

After clicking on the mentioned menu option Atom closes and doesn't reopen again. Ever. I waited. After restarting it manually I'm still on the old version and Atom is again trying to download the update.

If I try to enter the computer's admin username and password in the popup mentioned above, the behavior is exactly the same as described.

If I try to update when logged in with the admin account, it works perfectly fine.

This is with OSX 10.9.5 and Atom 1.0.19.

**Comment by mnquintana** [comment] 2015-11-09 16:43
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/8671 - feel free to subscribe there for updates.

**Closed by mnquintana** 2015-11-09 16:43 UTC

**Comment by ricardograca** [comment] 2015-11-09 16:57
Sorry for the dupe. I searched but that one didn't show up.
Em 09/11/2015 4:44 da tarde, "Machisté N. Quintana" <
notifications@github.com> escreveu:
