### ISSUE TITLE
Feature request: "Really close?" popup keyboard shortcuts

### ISSUE THREAD

**Issue by kgrossjo** [atom/atom#5458] opened 2015-02-09 08:23 UTC
When I close an unsaved file, I get a popup saying "foo has changes, do you want to save them?".  The popup has three buttons "Save", "Cancel" and "Don't Save".

The standard Windows dialog for this allows me to hit n to select Don't Save.

WIBNI Atom would allow me to do the same, at least on Windows?

**Comment by batjko** [comment] 2015-02-09 15:08
Yes, Windows users are used to Yes/No/Cancel decisions (with the appropriate Y/N/C key bindings), whenever being asked anything like `"Closing this thing, do you want to save your shit?"`

**Comment by zcbenz** [comment] 2015-02-10 03:53
This is not possible for now because of a limitation in Chromium, see also https://github.com/atom/atom/issues/2928#issuecomment-52272834.

I'm closing this since it is a duplicate of #2928.

**Closed by zcbenz** 2015-02-10 03:53 UTC
Labels: enhancement
