### ISSUE TITLE
Cannot pipe to `atom` command

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8115] opened 2015-07-28 15:14 UTC
Piping directly to a text editor is incredibly useful. It lets you view massive amounts of somewhat structured temporary data, like disassembly, from a convenient syntactically highlighted GUI. But it doesn't work with atom:
```bash
echo "foo" | atom
otool -vVjhlt /usr/lib/libSystem.B.dylib | atom
dd bs=$[128*3] count=1 if=/dev/urandom | perl -MMIME::Base64 -E 'while(read STDIN, $x, 3){print encode_base64 $x,""}' | atom
```

(here atom -> `/Applications/Atom.app/Contents/Resources/app/atom.sh`)

**Comment by izuzak** [comment] 2015-07-28 15:16
Thanks for the feedback -- I think this is a duplicate of https://github.com/atom/atom/issues/1729, so closing in favor of that.

**Closed by izuzak** 2015-07-28 15:16 UTC
