### ISSUE TITLE
Scroll issue 1.17.2 OSX

### ISSUE THREAD

**Issue by phstoned** [atom/atom#14733] opened 2017-06-07 16:25 UTC
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I can't scroll left pane with trackpad on mac osx v. 10.12.14. I just don't see the scrollbar, but if jump between files with arrows everything is ok. 
In previous version 1.16.0 x64 scroll on trackpad works as expected.

### Steps to Reproduce

1. Open atom in full window
2. Open much projects and open many folder trees
3. Try to scroll with trackpad (two fingers), and nothing happens

**Expected behavior:** Scroll left pane content

**Actual behavior:** No scroll at all

**Reproduces how often:** on new version 1.17.2 every time

### Versions
`$ atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0`

### Additional Information
Same issue happens on 1.18-beta.

But works as expected on previous stable release 1.16
`$ atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0`

osx version

`Darwin MacBook-zh.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64`

**Comment by 50Wliu** [comment] 2017-06-07 17:43
Unable to reproduce on Windows.

**Comment by rsese** [comment] 2017-06-07 18:34
I can't reproduce either on macOS 10.12.15 with Atom 1.17.2.

> Open atom in full window

Just to confirm, do you mean fullscreen here?  If so, does that mean scrolling works ok if you're not fullscreen?

Also, are you using the Atom Material theme by any chance @phstoned?

**Comment by SimonFricker** [comment] 2017-06-08 19:55
I have the same issue. 

Atom 1.17.2 x64
macOS 10.12.4 (16E195)
Theme: Atom Material

**Comment by rsese** [comment] 2017-06-08 20:21
> Change the theme and it works again

Thanks @SimonFricker, it looks like that issue is fixed in Material 2.0 /cc https://github.com/atom-material/atom-material-ui/issues/420.

**Comment by phstoned** [comment] 2017-06-09 08:27
@rsese It works neither fullscreen nor in window. I just thought it only fullscreen problem but then I did testing and the issue happens no matter how window is opened.
yes, I'm using Atom material. 
so is it theme issue, not atom?

**Comment by phstoned** [comment] 2017-06-09 08:31
yes, this is definitely theme problem. Atom Dark is somehow broken.

**Changed theme from Atom Dark to Atom Light and scrolling works well.**

**Comment by rsese** [comment] 2017-06-09 17:30
Can you clarify @phstoned, you mentioned both:

> yes, I'm using Atom material.

But also:

> Atom Dark is somehow broken.

Do you mean Material in this sentence ☝️ or did you have a scrolling problem with Atom Dark as well?

**Comment by phstoned** [comment] 2017-06-09 19:45
@rsese I used these
![Alt text](https://monosnap.com/file/OVBL0r8ODxFySKj6j23pDkD8GbjPb4.png)
I think the problem is in UI theme.

**Comment by rsese** [comment] 2017-06-09 20:49
Gotcha, thanks :+1:  So it does look like you're hitting https://github.com/atom-material/atom-material-ui/issues/420, and they say it's fixed as of Material 2.0 so we'll go ahead and close this out.

**Closed by rsese** 2017-06-09 20:49 UTC
Labels: needs-reproduction
