### ISSUE TITLE
Azerty keyboard support broken

### ISSUE THREAD

**Issue by Mikarnage** [atom/atom#11344] opened 2016-04-01 13:56 UTC
### Description

Some very common (for a developper) characters of the azerty keyboard ("]", "}") don't work with default bindings.
Typing "}" doesn't do anything, and typing "]" collapses the current block and doesn't write "]".

Is it possible to disable the binding associated with it?
Anyway, it shouldn't be the default setting..

### Steps to Reproduce

1. Install French keyboard support (or any other azerty keyboard)
2. Try typing a "]" or a "}"
3. GL, HF ;)

**Comment by Mikarnage** [comment] 2016-04-01 14:10
Note : I'm pretty sure I didn't have this bug in previous version of atom (or else I would have chosen another editor), my current version is 1.5.4

**Comment by 50Wliu** [comment] 2016-04-01 15:47
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-01 15:47 UTC
