### ISSUE TITLE
c syntax highlighting breaks on long chains of case statements

### ISSUE THREAD

**Issue by andrewpcone** [atom/atom#5267] opened 2015-01-27 00:28 UTC
Running 0.176.0 on Mac OS X 10.10.1

The following is highlighted incorrectly:

```c
const char* f(const char *s)
{
    switch((s[0] << 8) + s[1]) {
    case 'B': case 'C': case 'D': case 'E': case 'F': case 'G':
        return "XX";
    case 'H': case 'I': case 'J': case 'K': case 'L': case 'M': case 'N': case 'O': case 'P': case 'Q': case 'R':
        return "XX";
    case 'S': case 'T': case 'U': case 'V': case 'W': case 'X': case 'Y': case 'Z': case '[':case '\\': case ']': case '^': case '_': case '`': case 'a': case 'b': case 'c': case 'd': case 'e': case 'f':
        return "XX";
    case 'g': case 'h': case 'i': case 'j': case 'k': case 'l': case 'm': case 'n': case 'o': case 'p': case 'q': case 'r': case 's': case 't': case 'u':
        return "XX";
    case 'v':
        return "XX";
    case 'w': case 'x':
        return "XX";
    case 'y':
        return "XX";
    default:
    case 0:
        return s;
    }
}
```

![screen shot 2015-01-26 at 4 28 27 pm](https://cloud.githubusercontent.com/assets/1505330/5911279/636b3a8e-a578-11e4-8e64-da81a6dee843.png)

**Comment by kevinsawicki** [comment] 2015-01-27 00:30
I believe this is a duplicate of https://github.com/atom/atom/issues/1667

**Closed by kevinsawicki** 2015-01-27 00:30 UTC
