### ISSUE TITLE
Installation failed on Windows 7

### ISSUE THREAD

**Issue by AlexandreKieling** [atom/atom#5295] opened 2015-01-28 19:58 UTC
Stacktrace:

Program: Starting install, writing to C:\Users\alexandre.briani.NT\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\alexandre.briani.NT\AppData\Local\atom\packages\RELEASES'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\alexandre.briani.NT\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\alexandre.briani.NT\AppData\Local\atom\app-0.176.0
IEnableLogger: Failed to write file: C:\Users\alexandre.briani.NT\AppData\Local\atom\app-0.176.0: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
at System.IO.PathHelper.GetFullPathName()
at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at NuGet.PhysicalPackageFile.GetStream()
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8b.<copyFileToLocation>b__8a()
at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
at System.IO.PathHelper.GetFullPathName()
at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at NuGet.PhysicalPackageFile.GetStream()
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8b.<copyFileToLocation>b__8a()
at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
at Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass84.<installPackageToAppDir>b__80(IPackageFile x)
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass84.<installPackageToAppDir>b__7f()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()

**Comment by kevinsawicki** [comment] 2015-01-28 20:05
@paulcbetts would it be possible to get the path into the log file?

**Comment by paulcbetts** [comment] 2015-01-28 20:10
@AlexandreKieling Can you upload the entire log as a Gist?

**Comment by robingram** [comment] 2015-01-29 01:47
Same issue on Windows 7: https://gist.github.com/robingram/40ff2d05753fc11658e5

**Comment by AlexandreKieling** [comment] 2015-01-29 10:50
Entire log here: https://gist.github.com/AlexandreKieling/f5e9ab0ac70c3e3557e9

**Comment by paulcbetts** [comment] 2015-01-29 16:23
I think this change was caused by our fix for memory usage; NuGet extracts the file out to a temp dir and probably uses some brain dead base path. I'll see what I can do about this.

**Comment by zornosaur** [comment] 2015-01-30 15:18
I had the same error, a fix would be greatly appreciated.

**Comment by sevin7676** [comment] 2015-02-16 12:25
I have the same error on Windows 8.1 x64

**Comment by 50Wliu** [comment] 2015-02-16 15:32
@paulcbetts this can be closed now right?
@sevin7676 What Atom version are you using?

**Comment by sevin7676** [comment] 2015-02-16 16:08
I just downloaded the latest installer from https://atom.io/ today

**Comment by paul-sh** [comment] 2015-02-16 16:32
0.179.0 still fails on Windows 7 x64. Here is a log file: https://gist.github.com/paul-sh/012b3960ffc34829a6fd

**Comment by Zireael07** [comment] 2015-02-23 13:32
0.182.0 on Windows 7 x64 installed with no issues today.

**Comment by sevin7676** [comment] 2015-02-23 14:35
0.182.0 also worked for me on Windows 8.1 x64

**Comment by 50Wliu** [comment] 2015-02-23 14:55
All right, closing as fixed.
If anyone is still experiencing this please comment below!

**Closed by 50Wliu** 2015-02-23 14:55 UTC
Labels: bug, installer, windows
