### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by krishna201** [atom/atom#16486] opened 2018-01-04 10:56 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At C:\Users\krishna\AppData\Local\atom\app-1.23.2\resources\app\src\text-editor-component.js:2289

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:2278:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:2271:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:400:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.23.2/resources/app/src/text-editor-component.js:278:20)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.23.2/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -2:48.8.0 core:undo (input.hidden-input)
     -2:45.9.0 editor:newline (input.hidden-input)
  2x -2:39.5.0 core:undo (input.hidden-input)
     -2:33.3.0 editor:newline (input.hidden-input)
     -2:24.4.0 core:undo (input.hidden-input)
     -2:18.2.0 editor:newline (input.hidden-input)
  2x -2:14.3.0 core:undo (input.hidden-input)
     -2:03.8.0 core:move-right (input.hidden-input)
     -1:58.5.0 core:copy (input.hidden-input)
     -1:54.6.0 core:backspace (input.hidden-input)
     -1:49.9.0 core:paste (input.hidden-input)
     -1:45.2.0 editor:newline (input.hidden-input)
     -1:34 core:move-right (input.hidden-input)
  2x -1:30.1.0 core:backspace (input.hidden-input)
     -1:21.6.0 editor:newline (input.hidden-input)
     -1:18.6.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-formatter-jsbeautify 1.1.2 
atom-react 0.4.0 
atom-react-instyle 0.2.8 
atom-react-native-style 0.2.0 
atom-react-snippets 0.2.2 
atom-ternjs 0.18.3 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
badass-react-snippets 1.1.0 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
expand-region 0.4.0 
file-header 1.13.8 
file-icons 2.1.14 
git-control 0.9.0 
git-plus 7.10.0 
git-time-machine 1.5.9 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-shorcuts-react 2.1.0 
hyperclick 0.1.5 
javascript-snippets 1.2.1 
js-hyperclick 1.12.2 
language-babel 2.79.0 
language-patch 1.2.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
native-color-picker 0.2.5 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
react-developer-snippets 0.2.0 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
react-native-components 0.1.1 
react-native-redux-snippets-es6-es7-atom 0.6.0 
react-native-snippets 0.3.0 
react-native-snippets-horse 2.0.0 
react-redux-atom-snippets 0.7.2 
react-redux-es6-snippets 0.1.3 
react-redux-react-native-snippets 0.2.4 
react-snippets 1.0.1 
react-snippets-for-atom 0.2.0 
react-storybook-snippets 0.3.0 
tree-view-open-files 0.3.0 
```

**Comment by rsese** [comment] 2018-01-04 19:37
Thanks for the report!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15263. You may want to subscribe there for updates - if you can share any details about what you were doing at the time of the error and if it's reproducible, please let us know!

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-01-04 19:37 UTC
