### ISSUE TITLE
MarkDown not rendering syntax correctly

### ISSUE THREAD

**Issue by rceee** [atom/atom#8995] opened 2015-09-29 16:33 UTC
When using backticks to denote code in MarkDown, it seems there is some issue between the editor preview (the text color) and the MarkDown Preview pane.  The Preview displays as expected, but unless you insert line breaks and sometimes an extra backtick in the editor, the editor text stops highlighting properly after certain code blocks.

E.g., if you do inline code, ```like this```, then put a header a couple of lines down, the header will not highlight (the syntax is not picked up) in the editor–Atom seems to still think the code block is open.

Please see screenshot for example.

Is this a bug or is there an error in syntax?

![atom-markdown](https://cloud.githubusercontent.com/assets/1851567/10171146/3020b0e0-669e-11e5-8f17-007ae2f026cc.png)

**Comment by mnquintana** [comment] 2015-09-29 21:47
I think this is a duplicate of https://github.com/atom/language-gfm/issues/21 – let me know if I'm misunderstanding though!

**Closed by mnquintana** 2015-09-29 21:47 UTC
Labels: question
