### ISSUE TITLE
Editor crashes when I copy into Atom 0.189 on Linux

### ISSUE THREAD

**Issue by cokelly** [atom/atom#6237] opened 2015-04-03 14:52 UTC
This may well be related to #6234 but I am experiencing a crash in the other direction. 

I am on Arch Linux. When I seek to copy into a markdown file (a pandoc reference of format [xyz2000]) I get a white screen and a notification that the window has crashed.

**Comment by victorhqc** [comment] 2015-04-05 18:38
This happens to me when I copy from the postman app, which is another webkit based app. Not sure if copying from another source could make it crash. The difference with you is that crashes with a php file.
I am using Ubuntu 14.10

**Comment by kedashoe** [comment] 2015-04-05 19:29
Crashed copying from firefox into a javascript file. Ubuntu 14.10

**Comment by zba** [comment] 2015-04-06 05:03
It seems it start to enter bad phase after sometime running, when this "phase" active there two simptoms:

1. paste to editor makes it crash
2. copy from editor is impossible. i.e. when you paste from buffer to any window, target window stall for several seconds then looks like it pasted nothing (I suspect it is tonns of nulls)

Ubuntu 14.04.

**Comment by mark-hahn** [comment] 2015-04-06 06:15
> This happens to me when I copy from the postman app, which is another webkit based app

It happens to me whenever I try to copy from one Atom window to another.  I think this qualifies as copying from one web-kit app to another (although the name "web-kit" is wrong).

P.S. This thread should be renamed to "cut/paste crashes in linux"

Ubuntu 14.04
atom 189
apm  0.157.0
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.1

**Comment by booti386** [comment] 2015-04-06 12:29
I'm able to reproduce...

**Comment by geir54** [comment] 2015-04-06 13:03
I'm also able to reproduce on Ubuntu, but nothing comes up in the console. Any tips for future debugging?

**Comment by kedashoe** [comment] 2015-04-06 15:49
> also it beginning between 0.175 and 0.189

I hadn't noticed anything until upgrading to 0.189. I use the ppa http://ppa.launchpad.net/webupd8team/atom/ubuntu. After running into this, I installed https://github.com/atom/atom/releases/download/v0.189.0/atom-amd64.deb but still had the issue. I'm running 0.188 from the releases page today and haven't hit any problems yet.

**Comment by jieter** [comment] 2015-04-06 18:39
I'm experiencing this mostly with middle click paste, very annoying.

**Comment by izuzak** [comment] 2015-04-06 18:42
This seems to be a duplicate of https://github.com/atom/atom/issues/6221 so I'm merging this issue into that one. Please subscribe to that other issue for updates.

**Closed by izuzak** 2015-04-06 18:42 UTC
Labels: atom, crash, linux
