### ISSUE TITLE
cannot write vertical line (|) in editor 

### ISSUE THREAD

**Issue by pSkpt** [atom/atom#9742] opened 2015-11-22 04:16 UTC
I can't write | (vertical line) (Alt Gr + 9) sign in editor. 
I can write in Sublime Text or Notepad...
I try js, php, html files.

OS : Windows 7 x64
Atom 1.2.3

**Comment by lee-dohm** [comment] 2015-11-22 05:38
This is a duplicate of atom/atom-keymap#35. Please subscribe there for updates.

**Closed by lee-dohm** 2015-11-22 05:38 UTC
Labels: duplicate
