### ISSUE TITLE
Failure to launch from Windows git-bash shell via atom command

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8605] opened 2015-08-31 19:21 UTC
The system is x86_64 Windows 10, typical Atom install, typical portable git install. I can't provide a normal error message because Atom crashes immediately after the first window paint, and I'm shown the inspector:

```
c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:127 Error reading compiled file TypeError: Arguments to path.join must be strings
    at f (path.js:178:13)
    at Object.filter (native)
    at Object.win32.join (path.js:183:38)
    at readCachedJavascript (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:81:24)
    at require.install.retrieveSourceMap (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:125:22)
    at mapSourcePosition (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\source-map-support\source-map-support.js:132:21)
    at wrapCallSite (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\source-map-support\source-map-support.js:295:20)
    at c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\source-map-support\source-map-support.js:330:26
    at Array.map (native)
    at Function.prepareStackTrace (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\source-map-support\source-map-support.js:329:24)
    at handleSetupError (file:///C:/Users/alex/AppData/Local/atom/app-1.0.9/resources/app.asar/static/index.js:56:24)
    at window.onload (file:///C:/Users/alex/AppData/Local/atom/app-1.0.9/resources/app.asar/static/index.js:39:7)
index.js:56 TypeError: Cannot redefine property: .ts
    at Function.defineProperty (native)
    at c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:164:10
    at Array.forEach (native)
    at Object.<anonymous> (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:161:24)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value (C:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at new Task (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\task.js:32:26)
    at Function.module.exports.Task.once (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\task.js:19:14)
    at GitRepository.module.exports.GitRepository.refreshStatus (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\git-repository.js:398:37)
    at GitRepositoryProvider.module.exports.GitRepositoryProvider.repositoryForDirectorySync (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\git-repository-provider.js:56:14)
    at Project.module.exports.Project.addPath (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\project.js:270:89)
    at Project.module.exports.Project.setPaths (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\project.js:231:14)
    at new Project (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\project.js:87:12)
    at Function.module.exports.Serializable.deserialize (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\serializable\lib\serializable.js:72:22)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\deserializer-manager.js:42:29)
    at Atom.module.exports.Atom.deserializeProject (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\atom.js:812:52)
    at Atom.module.exports.Atom.deserializeEditorWindow (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\atom.js:842:12)
    at Atom.module.exports.Atom.startEditorWindow (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\atom.js:668:12)
    at Object.<anonymous> (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\window-bootstrap.js:12:8)
    at Object.<anonymous> (c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value (C:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at setupWindow (file:///C:/Users/alex/AppData/Local/atom/app-1.0.9/resources/app.asar/static/index.js:82:25)
    at window.onload (file:///C:/Users/alex/AppData/Local/atom/app-1.0.9/resources/app.asar/static/index.js:35:9)index.js:56 handleSetupError
c:\Users\alex\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:164 Uncaught TypeError: Cannot redefine property: .ts
```

`which atom` resolves to `/c/Users/alex/AppData/Local/atom/bin/atom` as expected. This error occurs regardless of whether `atom` is passed a file, although the *very* first time I called it with file, Atom didn't crash to the inspector but rather displayed a normal error message. Atom shouldn't fail to open when run from Git bash.

**Comment by peduxe** [comment] 2015-08-31 19:44
https://github.com/atom/atom/issues/8580#issuecomment-136479188

**Comment by maxbrunsfeld** [comment] 2015-08-31 23:16
This is a duplicate of https://github.com/atom/atom/issues/8551. Please subscribe there for updates.

**Closed by maxbrunsfeld** 2015-08-31 23:16 UTC
