### ISSUE TITLE
Please help. Thai language problem when i updated atom 0.189.0 in my ubuntu

### ISSUE THREAD

**Issue by l54n71** [atom/atom#6232] opened 2015-04-03 04:36 UTC
Hello, 
    When I updated atom to version 0.189.0 in my ubuntu desktop. It has problem with thai language.

Now i down grade to 0.188.0. It work. Please fix it in next version. atom is good IDE for me.

Thank you.

**Comment by maxbrunsfeld** [comment] 2015-04-03 16:59
@l54n71 can you describe the problem? Maybe include a screenshot or GIF if that helps to explain the issue?

**Comment by l54n71** [comment] 2015-04-03 19:57
![screenshot from 2015-04-04 02 55 35](https://cloud.githubusercontent.com/assets/11692854/6987881/3e9ce8d2-da76-11e4-9b21-622f55e18f13.png)

This is screenshot when i upgraded to 0.189.0 

Please help.

Thank you.

**Comment by l54n71** [comment] 2015-04-04 14:28
I fixed it. I Setting Font Family with "Loma". It's work.
Thank you.

**Comment by paulcbetts** [comment] 2015-04-05 01:13
The default Editor font should probably always come with a set of editor fonts that can render different languages like CJK or Thai

**Comment by v3ss0n** [comment] 2015-04-06 04:59
It usually fallbacks to whatever it can display. 189 have broke that.
I tested unicode characters in atom and they all broken with my univspace font too.

**Comment by izuzak** [comment] 2015-04-06 06:25
This looks like a duplicate of https://github.com/atom/atom/issues/6214, so I'm closing this in favor of that issue.

**Comment by izuzak** [comment] 2015-04-06 06:27
Reported in https://github.com/atom/atom/issues/6263 as well.

**Comment by izuzak** [comment] 2015-04-06 06:27
Reported in https://github.com/atom/atom/issues/6264 as well.

**Closed** 2015-04-06 06:28 UTC
Labels: more-information-needed

**Comment by khemmac** [comment] 2015-07-03 10:12
For thai language try this
![Thai language setting for atom](https://cloud.githubusercontent.com/assets/869855/8497330/76eea294-21a6-11e5-93bd-dd5162e4d1c9.png)
It works.

**Comment by M4R14** [comment] 2015-07-07 07:12
thank, @khemmac   it work for me!!

**Comment by pureexe** [comment] 2015-09-21 08:08
Thank @khemmac  work fine on my PC.
