### ISSUE TITLE
Uncaught TypeError: this.registry.startIdForScope is not a function

### ISSUE THREAD

**Issue by gretschdrummer** [atom/atom#16741] opened 2018-02-14 18:14 UTC
I saw that this issue was opened, but then closed by the person who opened it without any comments.  I'm now experiencing the issue.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.registry.startIdForScope is not a function

```
At C:\Users\apeterson\AppData\Local\atom\app-1.24.0\resources\app\node_modules\first-mate\lib\grammar.js:324

TypeError: this.registry.startIdForScope is not a function
    at Grammar.module.exports.Grammar.startIdForScope (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/first-mate/lib/grammar.js:324:34)
    at TextMateLanguageMode.tokenizedLineForRow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:428:30)
    at TextMateHighlightIterator.seek (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-mate-language-mode.js:746:49)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:83:58)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at DisplayLayer.getScreenLine (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/text-buffer/lib/display-layer.js:639:60)
    at TextEditor.screenLineForScreenRow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor.js:1243:36)
    at TextEditorComponent.requestHorizontalMeasurement (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2258:47)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:372:18)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:274:16)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:1457:18)
    at TextEditorComponent.didFocus (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:1481:35)
    at HTMLElement.addEventListener (/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.PaneElement.activeItemChanged (/app.asar/src/pane-element.js:170:25)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:435:26)
    at Pane.activateItem (~/AppData/Local/atom/app-1.24.0/resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
     -8:54.8.0 console:clear (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.8.1 
ide-css 0.2.0 
ide-json 0.2.0 
ide-php 0.7.5 
ide-yaml 0.4.2 
language-apache 1.8.0 
language-docker 1.1.8 
language-groovy 0.7.0 
tasks 2.9.1 
tortoise-svn 0.5.1 
```

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-02-14 22:35
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by Diskutant** [comment] 2018-02-14 22:57
I have the same error. It started with Atom 1.24
always happens when opening a .todo file (using the tasks plugin)
Doesn't happen with safe mode.

**Comment by bbezanson** [comment] 2018-02-14 22:59
I'm having the same error that seemed to have just started today as well.

- For me the error was related to trying to view a ".taskpaper" file.
- Yes reproducable
- The error does not show in safe mode.
- I thought I fixed the error by restarting with "atom --clear-window-state"
  - But I had manually turned off all installed plug-ins. After turning things back on and restarting Atom the issue reappeared.

I am doing other debugging now.

**Comment by kevinmanify** [comment] 2018-02-15 08:58
I have the same issue and this occurred after I had restarted Atom with "atom --clear-window-state". And I get this error only(as far as I know) when I try to open .todo files.

**Comment by vicked** [comment] 2018-02-15 09:29
Same for me, tasks plugin, since yersterday (1.24).

**Comment by SpeedySparrow** [comment] 2018-02-15 10:11
You might might want to take a look at https://discuss.atom.io/t/function-this-registry-startidforscope-is-not-a-function/52441/4 
A user has proposed a solution that might also serve as a workaround for you.

**Comment by maxbrunsfeld** [comment] 2018-02-15 23:46
I think this error is because the `tasks` package relied on the fact that Atom's `GrammarRegistry` class was a subclass of the `first-mate` module's `GrammarRegistry` class, but this is no longer the case.

Specifically, [this code](https://github.com/irrationalistic/atom-tasks/blob/fc22bb326d77ca493e520c1411b5c8d02e0e4b48/lib/tasks.coffee#L124) probably no longer works.

/cc @irrationalistic Could you take a look at this when you get a chance? There have been some changes to our `GrammarRegistry` class (of which `atom.grammars` is an instance). Is there a way to make your package work with the current public APIs? If not, let me know; maybe there are public APIs we can add.

**Comment by irrationalistic** [comment] 2018-02-16 06:54
Just published a fix for this, not sure if it's ideal.

Essentially I am generating an actual grammar file and saving/loading that whenever the grammar needs to update. It works fine and unbreaks the issue!

Any thoughts, @maxbrunsfeld?

**Comment by irrationalistic** [comment] 2018-02-16 06:56
(also, this should be fixed)

**Comment by gretschdrummer** [comment] 2018-02-16 14:11
Working great for me now.  Thanks!

**Comment by Arcanemagus** [comment] 2018-02-16 17:45
There's a similar stack trace reported in https://github.com/steelbrain/linter-ui-default/issues/481, however nothing is being done directly with `Grammar`s in there.

The full stack trace reported by @adamzerner:
```
At /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324

TypeError: this.registry.startIdForScope is not a function
    at Grammar.module.exports.Grammar.startIdForScope (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324:34)
    at TextMateLanguageMode.tokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:428:30)
    at TextMateHighlightIterator.seek (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:746:49)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:83:58)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at DisplayLayer.getScreenLine (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:639:60)
    at TextEditor.screenLineForScreenRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1243:36)
    at TextEditorComponent.requestHorizontalMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2258:47)
    at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:205:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

This part is identical between them:
```
At /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324

TypeError: this.registry.startIdForScope is not a function
    at Grammar.module.exports.Grammar.startIdForScope (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324:34)
    at TextMateLanguageMode.tokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:428:30)
    at TextMateHighlightIterator.seek (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:746:49)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:83:58)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at DisplayLayer.getScreenLine (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:639:60)
    at TextEditor.screenLineForScreenRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1243:36)
    at TextEditorComponent.requestHorizontalMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2258:47)
```

However they differ in the "triggering section":
```
   at TextEditorComponent.pixelPositionForScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:205:18)
    at HTMLElement.pixelPositionForScreenPosition (/app.asar/src/text-editor-element.js:246:32)
    at getBufferPositionFromMouseEvent (/packages/linter-ui-default/lib/editor/helpers.js:12:47)
    at /packages/linter-ui-default/lib/editor/index.js:178:29)
    at later (/packages/linter/node_modules/sb-debounce/index.js:9:14)
```

If you want me to file this as a separate issue since the triggering code is different let me know! The reported steps to reproduce though are the same (Open a `.todo` file with `tasks`).

**Comment by irrationalistic** [comment] 2018-02-16 19:36
@Arcanemagus: did the changes I pushed yesterday fix the issue reported on linter?

**Comment by Arcanemagus** [comment] 2018-02-16 19:44
@adamzerner Could you answer that? ☝️

**Comment by Arcanemagus** [comment] 2018-02-16 20:43
All I can confirm is that the issue reported here is fixed as I can't reproduce the issue reported on `linter-ui-default`.

**Comment by maxbrunsfeld** [comment] 2018-02-16 20:45
Great. Thanks so much for the quick action @irrationalistic! And thanks everyone for the reports.

**Closed by maxbrunsfeld** 2018-02-16 20:45 UTC
Labels: more-information-needed, uncaught-exception

**Comment by adamzerner** [comment] 2018-02-17 18:54
> @Arcanemagus: did the changes I pushed yesterday fix the issue reported on linter?

Yes, they did. Thanks for the quick fix!
