### ISSUE TITLE
entering \ not possible

### ISSUE THREAD

**Issue by sango0711** [atom/atom#7447] opened 2015-06-26 09:37 UTC
I installed the windows Version (Win7, 64bit), Atom 1.0 and i cant input \ (Alt-gr + ß) on a german keyboard.

Doesnt work in Latex or textfile.

**Comment by izuzak** [comment] 2015-06-26 10:37
Thanks for the report -- I believe this is a duplicate of https://github.com/atom/atom-keymap/issues/35, so I'm closing this in favor of that issue.

**Closed by izuzak** 2015-06-26 10:37 UTC
