### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by 286810** [atom/atom#17065] opened 2018-04-01 07:20 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:870:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:377:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1553:59)
```

### Commands

```
     -4:45.4.0 core:close (atom-pane.pane.active)
     -3:32.4.0 settings-view:open (a.)
     -2:45.5.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -1:27.7.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-easy-jsdoc 4.12.5 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 1.4.3 
docblockr 0.13.6 
emmet 2.4.3 
file-icons 2.1.18 
goto-definition 1.3.4 
intentions 1.1.5 
js-hyperclick 1.13.0 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint undefined 
pigments 0.40.2 
react-snippets 1.1.0 
vim-mode-plus 1.32.0 
```

**Comment by Arcanemagus** [comment] 2018-04-01 20:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16892. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-04-01 20:13 UTC
