### ISSUE TITLE
Atom shows there are available updates but then Settings/Updates start fetching updates again

### ISSUE THREAD

**Issue by mindrones** [atom/atom#10637] opened 2016-02-01 15:54 UTC
Atom says there are available updates, 

![screen shot 2016-02-01 at 16 51 56](https://cloud.githubusercontent.com/assets/1309648/12722218/24cf9ecc-c904-11e5-90db-0234de80408f.png)

but clicking on the blu link it opens the `Settings/Updates` tab and start fetching updates again.
Shouldn't it already know and show the available updates instead?

**Comment by 50Wliu** [comment] 2016-02-01 16:48
Hi @mindrones, this is a duplicate of atom/settings-view#409 - please subscribe there for updates.

**Closed by 50Wliu** 2016-02-01 16:48 UTC

**Comment by mindrones** [comment] 2016-02-01 16:55
ok thanks!
