### ISSUE TITLE
Search performance

### ISSUE THREAD

**Issue by nikmartin** [atom/atom#8055] opened 2015-07-24 02:54 UTC
I have a 636k XML/XSD file that I have to use for reference frequently in a project. If I open this file to search for a tag, like "E04", atom locks up and blocks for about 6 seconds looking for "E", which there are 30,000 of. If I type quickly enough, and get "E0" typed quickly, then atom doesn't find many, and doesn't lock up. It seems that the block is while atom tries to decorate all the E's it found with a little box. The search itself doesn't seem to be the issue, as evidenced by the lack of freezing when I quickly type an uncommon search string. atom is version 1.0.2-9432598, built from source, on 64 bit Arch linux

**Comment by mnquintana** [comment] 2015-07-24 03:17
This looks like a duplicate of https://github.com/atom/find-and-replace/issues/145 – let's keep the discussion there.

**Closed by mnquintana** 2015-07-24 03:17 UTC
