### ISSUE TITLE
Uncaught Error: spawn /Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/upd...

### ISSUE THREAD

**Issue by Linuxhombre** [atom/atom#10804] opened 2016-02-13 05:42 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Users/joshuafeldman/Library/Application Support/com.github.atom.ShipIt/update.4t7vJhd/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "softWrap": true,
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2016-02-13 17:25
Thanks for the report! This looks like a duplicate of #9559 though – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-02-13 17:25 UTC

**Comment by joshaber** [comment] 2016-02-14 19:16
@Linuxhombre Thanks! Do you recall how you launched Atom when you got this?

**Comment by Linuxhombre** [comment] 2016-02-14 22:57
Absolutely. I used Mac OS X el captain and also had Xamarin open with my
iOS simulator also open. I have quad core / 16 gigabyte of RAM so I don't
think any of that is an issue. Cheers! Glad I could be of help.

**Comment by demhydraz** [comment] 2016-02-14 23:01
I think he meant more along the lines of if you used the Finder context menus, or Spotlight, or a dock icon, or Launchpad, or from the CLI...

**Comment by Linuxhombre** [comment] 2016-02-14 23:04
Oh sorry about that, I actually launched it directly from the Xamarin IDE
using the open with Atom feature in one of the drop down menus for a CS
file I was building.

**Comment by joshaber** [comment] 2016-02-15 01:44
Great, thanks @Linuxhombre!

**Comment by Linuxhombre** [comment] 2016-02-15 01:59
my pleasure!
