### ISSUE TITLE
Pasting multiple lines into the "find in current buffer" field

### ISSUE THREAD

**Issue by joesustaric** [atom/atom#5021] opened 2015-01-13 02:37 UTC
Hi there, when I command + f and paste multiple lines into the "find in current buffer" field the lines seem to be pasted into the field but behind all the other ui elements. 

![example](http://i.imgur.com/mP4nZT7.png)
bug?

**Comment by lee-dohm** [comment] 2015-01-13 03:15
Duplicate of #4400. Please subscribe to that issue for updates.

**Closed by lee-dohm** 2015-01-13 03:15 UTC
