### ISSUE TITLE
atom is not possible to install in openSUSE Tumbleweeds

### ISSUE THREAD

**Issue by dominuskernel** [atom/atom#13378] opened 2016-12-03 10:19 UTC
When I try to install the rpm there is one dependency that it isn't possible to resolve: 
libXScrnSaver
I tried to install and added the repository 
http://download.opensuse.org/repositories/X11:/XOrg/openSUSE_Tumbleweed/
but that library with that name doesn't exit. In addition, I have installed theses libraries
libXss1 and libXss-devel but it continues ask me for the libXScrnSaver library
Anyway I tried to install from sources with 
sudo script/build --install
everything seems that works fine but when I try to execute it, the process is executing but the editor doesn't show.

**Comment by johnmuhl** [comment] 2016-12-03 15:49
The same happens when using the pre-built `1.13.0-beta6` rpm. `1.13.0-beta5` works as expected.

**Comment by johnmuhl** [comment] 2016-12-03 15:51
Related: https://github.com/atom/atom/pull/13289, https://github.com/atom/atom/issues/13354

**Comment by dominuskernel** [comment] 2016-12-03 16:22
yes I tried with the version `1.13.0-beta6` but I have the same problem

**Comment by 50Wliu** [comment] 2016-12-03 17:21
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #13354. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-03 17:21 UTC
