### ISSUE TITLE
Uncaught AssertionError [ERR_ASSERTION]: 14153 == 0

### ISSUE THREAD

**Issue by NhatNam98** [atom/atom#18831] opened 2019-02-11 15:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError [ERR_ASSERTION]: 14153 == 0

```
At assert.js:42

AssertionError [ERR_ASSERTION]: 14153 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
  9x -8:48.5.0 core:backspace (input.hidden-input)
     -6:27.6.0 application:open-folder (input.hidden-input)
     -0:32.7.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
framer-syntax 1.1.0 
framer-ui 2.0.0 
```

**Comment by rsese** [comment] 2019-02-11 22:54
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14074 so you can subscribe there for updates if you'd like.  If you have specific steps to reproduce, please let us know in https://github.com/atom/atom/issues/14074.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-11 22:54 UTC
