### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by Eslem** [atom/atom#7684] opened 2015-07-03 15:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Slem-Destop\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -1:32.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:28.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:27.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:27.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:23.8.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -1:20.2.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:19.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:19.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:17.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:05.9.0 core:copy (atom-text-editor.editor.is-focused)
     -1:02.1.0 core:paste (atom-text-editor.editor.is-focused)
     -1:01.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:49.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:48.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:32.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:28.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
color-picker, v2.0.7
emmet, v2.3.12
file-icons, v1.5.8
jshint, v1.3.8
minimap, v4.10.1
nuclide-click-to-symbol, v0.0.22
nuclide-code-format, v0.0.22
nuclide-diff-view, v0.0.22
nuclide-file-tree, v0.0.22
nuclide-file-watcher, v0.0.22
nuclide-flow, v0.0.22
nuclide-hack, v0.0.22
nuclide-hg-repository, v0.0.22
nuclide-installer, v0.0.22
nuclide-language-hack, v0.0.22
nuclide-remote-projects, v0.0.22
nuclide-type-hint, v0.0.22

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-07-03 15:25
Duplicate of #6548 - this has been fixed for the next version of Atom.

**Closed by mnquintana** 2015-07-03 15:25 UTC
