### ISSUE TITLE
Provide a official PPA or Snap package for ubuntu.

### ISSUE THREAD

**Issue by nextgenthemes** [atom/atom#15888] opened 2017-10-13 19:43 UTC
You build .deb packages but one has to manually download them and install them when a new version comes out. I think Atom not even tells you when that is. That makes no sense. You should provide a official Ubuntu package.

**Comment by damieng** [comment] 2017-10-13 21:35
Duplicate of https://github.com/atom/atom/issues/2956

**Closed by damieng** 2017-10-13 21:35 UTC
