### ISSUE TITLE
bracket pairing - putting cursor at an open bracket highlights its closing bracket within a comment

### ISSUE THREAD

**Issue by deveedutta** [atom/atom#9951] opened 2015-12-05 08:50 UTC
If the code looks like:
```js
function () { //put the cursor next to the bracket here
 //some comment with a bracket } anywhere (people even put smileys in comments :) like this)
 // the underline appears below the bracket in the comment
} //instead of this one
```
The bracket pairing highlighting( with an underline below the bracket) fails.

**Comment by izuzak** [comment] 2015-12-05 10:50
Thanks for the report, @deveedutta. I think this is a duplicate of https://github.com/atom/bracket-matcher/issues/78 so I'm going to close this in favor of that issue. Let me know if I misunderstood, though.  :v: 

You might also want to check out [this section](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) of the contributing guide.

**Closed by izuzak** 2015-12-05 10:50 UTC
