### ISSUE TITLE
Editor hangs forever when navigating to the end of a long line

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#11645] opened 2016-04-29 00:27 UTC
### Description

When the cursor is at column 0 of the line after an extremely long line, and the left arrow key is pressed to move the cursor to the end of that line, Atom freezes forever.

Moreover upon relaunch, it reopens the SAME FILE to the SAME CURSOR POSITION and hangs again, meaning the user is stuck in a permanent hang-restart loop. Atom is reduced to an annoying emulator of DLL Hell.

### Steps to Reproduce

0. Set Atom to open
1. Open a 200kB XML file, encoded in UTF-16 LE, that has all its text distributed on two lines.
2. Atom opens this file with your cursor at the top left.
3. Move the cursor to column 0 of the second line.
4. Press the left arrow key.
5. Atom wraps around and then hangs forever.

### Versions

1.7.3, tested on OSX 10.11.4 and Windows 10 x64.

**Comment by lee-dohm** [comment] 2016-04-29 00:29
Do you have a sample file that we can reproduce this on?

> user is stuck in a permanent hang-restart loop

They can get out of it by clearing the editor state using `atom --clear-window-state`.

**Comment by alexchandel** [comment] 2016-04-29 00:59
> They can get out of it by clearing the editor state using atom --clear-window-state

I managed to get out of it by deleting some stuff in `~/.atom`, but I don't think a user should be required to know to do these things.

> Do you have a sample file that we can reproduce this on?

I'm not sure I have one to distribute, but try a randomly generated one. Average xml tag name's length is ~10 chars, only leaves have any body content, which averages ~10 chars too.

#### Further developments:

It turns out this only happens on incorrectly encoded files (produced by a slew of Honeywell programs) that incorrectly encode the CR in CRLFs as a single byte. So it could be an encoding problem, but the editor still shouldn't hang. Ever.

**Comment by bj7** [comment] 2016-05-01 15:19
How long is this line? Is there any way you could calculate the total number of chars so I could reproduce?

 If someone could point me in the general direction of what Atom uses to process and read files, I would love to start investigating this!

**Comment by lee-dohm** [comment] 2016-05-01 18:59
> How long is this line? Is there any way you could calculate the total number of chars so I could reproduce?

From the problem description, I would guess somewhere in the neighborhood of tens of thousands of characters long.

**Comment by bj7** [comment] 2016-05-01 19:17
Only reason I was asking is if Atom uses native modules for line reads, the issue could be from the size limit found in standard C data types, 65535 bytes. I've run into this issue in other text editing applications before. An improperly encoded line break doesn't trigger a new line read operation, and thus continues to append to the end of the current input, eventually causing a crash (seg fault if I remember correctly since you overwrite the maximum allocated space).

**Comment by lee-dohm** [comment] 2016-05-02 01:30
Theoretically though the file has already been loaded if it is being displayed on screen for the cursor to be in play.

**Comment by bj7** [comment] 2016-05-02 11:35
Ahh this is true. When I get some free time I'll poke around in the buffer files to see if I can't find out more, but my day job is calling now.

@alexchandel , does the hang only happen on really big lines with the incorrect encoding, or does it happen on shorter lines with incorrect encoding?

**Comment by lammel** [comment] 2016-05-05 19:50
I created a sample text file that already shows the performance issue when dealing with long lines.
As this is a plain text file there is no incorrect syntax, but still working with this file gives a pretty bad user experience. Saving the file caused 100% CPU for some seconds for example. Even switching to the tab takes a few seconds (on modern hardware).

The file has a few lines where the length of line is reduced with every line, which may help to check buffer handling by removing a line until it works fine. As the longest line is only ~15000 chars we are not even near an 65535 char limit.

[lorum_ipsum_long_line.zip](https://github.com/atom/atom/files/251088/lorum_ipsum_long_line.zip)

Hope that helps.

**Comment by bj7** [comment] 2016-05-05 20:00
Ok, thanks for clarifying and giving a test file. I'll look into this, but I think that these sort of performance hits are an on going issue, and actively worked on

**Comment by 50Wliu** [comment] 2016-05-05 20:05
Looks like this got fixed in #11617 and is now on master as part of #11414?

**Comment by lammel** [comment] 2016-05-05 20:09
This is probably a duplicate of issue #979 (which is locked).

**Comment by bj7** [comment] 2016-05-05 20:11
@50Wliu I don't think that merge fixed it. Two days ago I pulled from Master, and built Atom fresh. My editor still lags badly. The merge was 6 days ago.

**Comment by 50Wliu** [comment] 2016-05-05 20:17
@bj7 Except #11414, which #11617 got merged into, was not merged into master until yesterday...

**Comment by bj7** [comment] 2016-05-05 20:18
@50Wliu My apologies! I did not see that. I'll give another pull and rebuild and test it out.

**Comment by bj7** [comment] 2016-05-05 20:39
I can verify that the original issue of the cursor being at column 0 under a very long line, followed by a left arrow to append to the end of said long line, has been fixed on Master. T here is no noticeable lag in that respect. The other issues in regards to general performance on large files still stand, but that is not the point of focus for this issue, and probably still applies to #979.

**Comment by 50Wliu** [comment] 2016-05-05 22:06
Awesome, thanks for the update @bj7!  In that case I'm going to close this issue because it appears that it has been resolved.

**Closed by 50Wliu** 2016-05-05 22:06 UTC
Labels: bug, performance
