### ISSUE TITLE
Open window reopens even with "Restore Previous Windows On Start" set to `no` on Windows

### ISSUE THREAD

**Issue by antikmozib** [atom/atom#19716] opened 2019-07-28 08:52 UTC
### Description

Setting _Restore Previous Windows On Start_ to **no** does nothing. Atom always opens with the last project and files loaded.

### Steps to Reproduce

1. Open some project
2. Set `Settings > Core > Restore Previous Windows on Start` to `no`
3. Quit Atom
4. Start Atom from the command line with `atom` or with the Atom icon on your OS

**Expected behavior:**

Fresh, clean window.

**Actual behavior:**

Atom loads the last project and any files that were open the previous session.

**Reproduces how often:**

100%

### Versions

Atom 1.39.0 x64
Windows 10 Pro x64

### Additional Information

Related bug: https://github.com/atom/settings-view/issues/1129

**Comment by rsese** [comment] 2019-07-29 22:26
Thanks for the report!  I can reproduce with 1.39.1 and 1.41.0-nightly1 on Window 10 though it doesn't reproduce on macOS.  Looks like this did work in 1.37.0 however so tagging as a regression.

As a side note, please keep the `Prerequisites` section of the issue template, it's helpful for us for us when triaging issues (I was able to reproduce in safe mode).

**Comment by tmatijevich** [comment] 2019-10-08 13:27
Any update on this?
[Atom Discussion](https://discuss.atom.io/t/setting-restore-previous-windows-on-start-set-no-has-no-effect-issue-19716/68700)

**Comment by rsese** [comment] 2019-10-11 02:25
Sorry no update, the team hasn't been able to prioritize this - if someone in the community opened a well-written pull request, we wouldn't be able to provide a specific timeframe for when it would be reviewed, but things would be farther along than just having the open issue.

**Comment by tmatijevich** [comment] 2020-08-08 17:55
I upgraded `1.48.0` > `1.49.0` on Windows 10 a few weeks ago and now this is no longer an issue for me.
Possibly fixed by @sht - thank you.
I have not seen this work since `1.37.0`.

**Comment by sadick254** [comment] 2020-09-22 10:12
Thanks for reporting this!

This has already been fixed in https://github.com/atom/atom/pull/20547. The fix is currently available in the latest version of atom `v1.51.0`.

**Closed by sadick254** 2020-09-22 10:12 UTC
Labels: d ⬇️, i ⬇️, regression, triaged, v ⬇️
