### ISSUE TITLE
File -> Open and File -> Add Project Folder do not work is there are no open windows

### ISSUE THREAD

**Issue by VivaLosDoyers** [atom/atom#13692] opened 2017-01-25 02:19 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If there are no open windows, File -> Open and File -> Add Project Folder do not spawn the expected file dialog.

This is on OS X 10.12.3 by the way.

### Steps to Reproduce

1. Start Atom
2. Close the whole window (not just the file, the whole window)
3. File -> Open

For any non-believers out there, here's a video of this happening: https://youtu.be/XwbVUFenDus

**Expected behavior:** [What you expect to happen]
A file open dialog

**Actual behavior:** [What actually happens]
 NOTHING! ABSOLUTELY NOTHING!

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
✘-255  [derp@derp] ~ 
15:34 $ atom --version
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Workaround: Quit and relaunch. Oy.

**Comment by 50Wliu** [comment] 2017-01-25 02:45
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-01-25 02:45 UTC
