### ISSUE TITLE
Beginning of line and end of line modifiers not working as expected when soft wrap is enabled

### ISSUE THREAD

**Issue by joncalhoun** [atom/atom#14294] opened 2017-04-25 02:16 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

*note* - I am using Mac OSX but I believe these shortcuts are applicable on most OSes.

When soft wrap is enabled and a line wraps to the next line pressing `ctrl+shift+e` doesn't work as expected.

`ctrl+e` goes to the end of the line as expected. That is, it goes to the end of the ACTUAL line, not the end of the soft-wrapped line. This means the cursor may move a few rows downward.

`ctrl+shift+e` on the other hand stops at the end of the current row even if the line is soft wrapped to multiple lines. It also occasionally does not highlight the last character in that line.

Screenshot: ![](https://www.dropbox.com/s/kt675lvkrvlysjg/Screenshot%202017-04-24%2022.06.06.png?dl=0&raw=1)

On a similar note, if you go to any line beyond the first of a soft-wrapped line and press `ctrl+a` it only goes to the beginning of the soft wrapped line, not the actual line.

This behavior is unexpected because soft wrapping shouldn't affect what is or isn't a line. It is just tool to help visualize long lines easier. Unfortunately this isn't how it is behaving in Atom.

### Steps to Reproduce

1. Open up atom and turn on soft wrap (View -> Toggle Soft Wrap).
2. Write a line of text that soft wraps to the next line
3. Go to any position of the line in the first row and press `ctrl+shift+e`

or

1. Open up atom and turn on soft wrap (View -> Toggle Soft Wrap).
2. Write a line of text that soft wraps to the next line
3. Go to any position of the line in the second row and press `ctrl+a`

**Expected behavior:** I expect to go to the end of the actual line, not the soft-wrapped line when pressing `ctrl+shift+e`. I expect to go to the start of the actual line, not the soft-wrapped line, when pressing `ctrl+a`. These would both be inline with what happens when you press `ctrl+e` currently.

**Actual behavior:** My cursor moves near the end of the soft-wrapped line (and sometimes misses the last character on it oddly) when pressing `ctrl+shift+e` and there is a soft-wrap. Similarly if I am on any line but the first soft-wrapped line and press `ctrl+a` my cursor moves to the start of the current soft-wrapped line, not the start of the actual line.

**Reproduces how often:** 100%

### Versions

Atom:

```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

OS: Mac OS X El Capitan - 10.11.6

APM:

```
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.10.1
```

### Additional Information

None

**Comment by rsese** [comment] 2017-04-25 17:23
> ctrl+shift+e on the other hand stops at the end of the current row even if the line is soft wrapped to multiple lines. It also occasionally does not highlight the last character in that line.

Hmmm, I think I agree this is a bug just because <kbd>ctrl-shift-e</kbd>  is mapped to `editor: select-to-end-of-line` and `editor: select-to-beginning-of-line` selects to the beginning of the physical line:

![select-to-beginning](https://cloud.githubusercontent.com/assets/734194/25398353/4eb5de04-29b1-11e7-99a4-e6558313619d.gif)

I would think the 2 functions would act similarly?  👍 / 👎  @lee-dohm?

> On a similar note, if you go to any line beyond the first of a soft-wrapped line and press ctrl+a it only goes to the beginning of the soft wrapped line, not the actual line.

This has come up somewhere before, there's a `editor: move-to-beginning-of-line` command that you can map <kbd>ctrl+a</kbd> to if you'd like and it will behave like you want.

**Comment by lee-dohm** [comment] 2017-04-25 20:14
@rsese Yes, there are separate commands for `editor:move-to-end-of-line` meaning the end of the buffer line (what you refer to as the "physical" line) and `editor:move-to-end-of-screen-line` meaning the end of the current soft-wrapped line. Since this is `editor:select-to-end-of-line`, I would expect it to select to the end of the buffer line. Unless this is a recent regression though, I would suspect that there is already an open issue on this.

**Comment by rsese** [comment] 2017-04-25 20:53
> Unless this is a recent regression though, I would suspect that there is already an open issue on this.

Lol I'm pretty sure I had seen this issue before too, you're right:

https://github.com/atom/atom/issues/7159

I'll go ahead and close this one as a dupe @joncalhoun, you can subscribe to that issue ☝️ for updates.

**Closed by rsese** 2017-04-25 20:54 UTC

**Comment by joncalhoun** [comment] 2017-04-25 23:57
Thanks @rsese.

For anyone who stumbles across this in the future - the `ctrl-shift-e` (select to end of line) is the duplicate bug. 

The `ctrl-a` and `ctrl-shift-a` behavior can be changed to select to the beginning of the line by adding the following to your `keymap.cson` file:

```
'ctrl-a': 'editor:move-to-beginning-of-line'
'ctrl-shift-a': 'editor:select-to-beginning-of-line'
```
