### ISSUE TITLE
Small  Open File Bug

### ISSUE THREAD

**Issue by 5t33** [atom/atom#14141] opened 2017-04-05 13:59 UTC
Hi, 

Not sure if this a bug or just a feature, but file->'open' does not work unless a window is already open. Thought it might be something to make more standard with most editors.

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Open Atom
2. Close Window
3. select file->open...

**Expected behavior:** [What you expect to happen]
File browser opens
**Actual behavior:** [What actually happens]
Nothing
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
I've only tried on the latest: 1.15
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Ben3eeE** [comment] 2017-04-05 14:42
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-04-05 14:42 UTC
Labels: duplicate
