### ISSUE TITLE
Mac Services

### ISSUE THREAD

**Issue by stevencombs** [atom/atom#3723] opened 2014-10-05 17:17 UTC
Seems like later version of Atom (.130+) have enabled the Services menu on OS X; however, I only see two service (see image) and have many installed (see second image). Use many of Terpstra's markdown services, including SearchLink, within other editors, but have not been able to get several to work in Atom. Anyone else experiencing this issue? Current version is .135.

![screen shot 2014-10-05 at 1 12 00 pm](https://cloud.githubusercontent.com/assets/665292/4519202/0215b502-4cb3-11e4-9ea0-cdac9469d081.png)

![screen shot 2014-10-05 at 1 15 03 pm](https://cloud.githubusercontent.com/assets/665292/4519208/367132d6-4cb3-11e4-9f03-ea66dde1701e.png)

**Comment by 50Wliu** [comment] 2015-04-13 23:03
Duplicate of #3204, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-13 23:03 UTC
