### ISSUE TITLE
Scroll to top when I save

### ISSUE THREAD

**Issue by Soularix** [atom/atom#8231] opened 2015-08-05 12:45 UTC
I have a problem with ATom , when I save , CTRL + S the editor scroll to the top automatically

**Comment by mnquintana** [comment] 2015-08-05 15:23
We're going to need [a lot more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) to help you debug this. What version of Atom are you using? What OS and version? Can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? (`atom --safe`)

**Comment by Soularix** [comment] 2015-08-05 17:09
ATom 1.0.4, windows 10

**Comment by mnquintana** [comment] 2015-08-05 17:10
Can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? (`atom --safe`)

**Comment by Soularix** [comment] 2015-08-05 17:16
in safe mode it's working fine, the only pakage I installed was Emmet now I tried disabling him & retarting Atom , same problem still happens

**Comment by Soularix** [comment] 2015-08-06 00:05
and I have this problem only on HTML files

**Comment by mnquintana** [comment] 2015-08-06 00:10
Thanks for the update! Since you can't reproduce this in safe mode, and the only package you have installed is Emmet, that seems to indicate that this is an issue with Emmet and not Atom core. Since it doesn't seem like an issue with Atom core, I'm going to close this out - I'd recommend opening an issue on [Emmet's repo](https://github.com/emmetio/emmet-atom), if one doesn't exist already.

**Closed by mnquintana** 2015-08-06 00:10 UTC
Labels: more-information-needed

**Comment by Soularix** [comment] 2015-08-06 00:56
I unistalled Emmet still have same problem !

**Comment by mnquintana** [comment] 2015-08-06 01:15
Have you restarted Atom since uninstalling Emmet? Also, can you post a list of your installed packages now? (`apm list --installed`)
