### ISSUE TITLE
Issues with cursor focus after changing syntax or encoding from the status bar

### ISSUE THREAD

**Issue by bzx** [atom/atom#7615] opened 2015-07-01 07:00 UTC
1. After setting syntax or file encoding from the menus in the status bar, the cursor focus stays in the status bar, and to move focus back to the file with keyboard only, you need to press Tab key twice (after setting syntax) or thrice (after setting encoding). Imho it would be better to move the cursor focus to its last position in the file window.

2. Even though the focus is retained (coloured outline) after completing syntax/encoding change, there is no way to bring up these menus with Enter key (or other key combinations that I've tried).

If you decide to move cursor focus to file, the status bar menu outline should be removed.

If you decide to keep the focus in the status bar, the focus appearance could be improved in appearance. Currently it doesn't look bad, but it could at least use some padding on the sides of the focused item.
![screen shot 2015-07-01 at 08 57 29](https://cloud.githubusercontent.com/assets/654500/8449160/3cdf8d94-1fcf-11e5-8d70-5850454550d6.png)

Lastly, setting syntax/encoding should be available from the Command Palette. Perhaps the same way as in Sublime Text (showing all entries prefixed appropriately) or just a way to trigger the selection menus as they exist now.

(Atom 1.0 on OSX 10.10)

**Comment by mnquintana** [comment] 2015-07-01 12:05
Thanks for the report! This is a duplicate of https://github.com/atom/status-bar/issues/82 – please subscribe there for updates.

(Also for future reference, Atom's status bar is handled by [atom/status-bar](https://github.com/atom/status-bar), not [atom/atom](https://github.com/atom/status-bar).)

> Lastly, setting syntax/encoding should be available from the Command Palette.

They are:

![screenshot 2015-06-27 22 17 15](https://cloud.githubusercontent.com/assets/823545/8454008/ec6e0d24-1fc7-11e5-8742-c8b5cbdc396b.png)
![screenshot 2015-06-27 21 54 15](https://cloud.githubusercontent.com/assets/823545/8454006/e71386d8-1fc7-11e5-841d-02a7b21a282a.png)

**Closed by mnquintana** 2015-07-01 12:05 UTC

**Comment by bzx** [comment] 2015-07-01 12:19
Thanks @mnquintana ! Wasn't aware of the separate repo. Now I am.
