### ISSUE TITLE
Failed to activate the timekeeper package

### ISSUE THREAD

**Issue by akours** [atom/atom#6004] opened 2015-03-17 18:32 UTC
[Enter steps to reproduce below:]

1. Tried to install timekeeper package
2. Got bug report.

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the timekeeper package

```
At undefined

- Timekeeper is active

**Comment by izuzak** [comment] 2015-03-18 18:05
@akours I'm having trouble reproducing this. Can you reproduce this reliably?

**Comment by akours** [comment] 2015-03-18 18:07
Will try again in a couple of minutes and let you know.

**Comment by izuzak** [comment] 2015-03-21 08:56
@akours Wondering if you've managed to reproduce this? :panda_face:

**Comment by stevenazari** [comment] 2015-03-25 13:24
I have ;)

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.13.0-46-generic
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the timekeeper package

```
At undefined

- Timekeeper is active & functional only with a valid project open
```

### Commands

```
     -1:04.6 settings-view:open (a.btn-copy-report.icon.icon-clippy)
     -0:32.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "followSymlinks": true
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.5.0
linter, v0.12.0
linter-php, v0.0.11
minimap, v4.6.0
timekeeper, v0.4.0
wakatime, v4.0.1

# Dev
No dev packages
```

**Comment by thomasjo** [comment] 2015-03-25 16:03
Duplicate of https://github.com/queenp/punchclock/issues/1 and https://github.com/atom/atom/issues/6090.

Problem is caused by an uncaught exception in the package's initialization. Easily reproduced if Atom is opened from e.g. the dock or in any other form that does not load a project.

**Closed by thomasjo** 2015-03-25 16:03 UTC
Labels: more-information-needed

**Comment by akours** [comment] 2015-03-26 16:41
Sorry for not responding guys. Had some issues with my pc. Glad it was sorted.
