### ISSUE TITLE
The tree-view package does not match files against the most specific rule in .gitignore

### ISSUE THREAD

**Issue by AlexHowansky** [atom/atom#7403] opened 2015-06-24 18:54 UTC
Consider this .gitignore:

    /lib/*
    !/lib/foo/

Here, we are instructing git to ignore everything under /lib, except for things under /lib/foo. However, tree-view does not parse this correctly, and instead matches everything under /lib, regardless of whether it's under /lib/foo or not. Thus, if I have "Hide VCS Ignored Files" unchecked, everything under /lib and lib/foo will be ghosted out. If I have "Hide CVS Ignored Files" check, everything under /lib and /lib/foo will be hidden. It appears that it's using the first rule that matches, and not the most-specific rule that matches.

**Comment by pablasso** [comment] 2015-06-26 02:58
+1

Also if `Exclude VCS Ignored Paths` is on, the files won't be indexed at all.

**Comment by izuzak** [comment] 2015-06-26 12:06
Thanks for the report, @AlexHowansky -- I think this is a duplicate of https://github.com/atom/tree-view/issues/196, so I'll close this one in favor of that. Let me know if I've misunderstood. :bow:

**Closed by izuzak** 2015-06-26 12:06 UTC

**Comment by AlexHowansky** [comment] 2015-06-26 14:08
Yep that looks like the same bug. I'm guessing I didn't find it in my searches because "gitignore" is spelled wrong in its title. :)

**Comment by izuzak** [comment] 2015-06-26 14:12
> I'm guessing I didn't find it in my searches because "gitignore" is spelled wrong in its title. :)

Hah, never noticed that -- just updated the title, thanks! :zap: :eyes:

**Comment by pablasso** [comment] 2015-06-26 16:05
@izuzak as stated above, this is still a bug for the core setting 'Exclude VCS Ignored Paths' which prevent them from being indexed for the search. That's outside the tree-view package, where should we track that?

**Comment by izuzak** [comment] 2015-06-26 16:15
@pablasso That's a good question. I'm pretty sure that fixing the problem for Tree View will fix the problem for other packages. So, my suggestion is that we keep that issue, and if resolving that issue doesn't fix the problem with search -- we can create a new one. 

That said, I'd also be okay if you wanted to create a new issue in atom/atom to track the general problem. Since this one was focused on the tree view package, it made sense to close it.

Sound good?

**Comment by pablasso** [comment] 2015-06-26 16:17
Sounds great, thanks!
