### ISSUE TITLE
Why Linux‘s Atom can't automatically update 

### ISSUE THREAD

**Issue by avalond** [atom/atom#15469] opened 2017-08-28 03:46 UTC
Why Linux‘s Atom can't automatically update , i am use ubuntu, if atom have new version, i must download in github new version,then use apt -dpkg -i xxx.deb install new atom, but vscode have repo, i can use apt-get update and  upgrade install new version, please support this future, thanks

**Comment by Ben3eeE** [comment] 2017-08-28 05:41
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/2956. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-28 05:41 UTC
Labels: duplicate
