### ISSUE TITLE
Dailog "Save / Cancel / Don't Save" should respond to keypresses

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#7296] opened 2015-06-16 12:02 UTC
Reproduce:

* open a file
* edit a file
* close tab (<kbd>Ctrl-F4</kbd> on Windows)
* press <kbd>N</kbd>

The "Save / Cancel / Don't save" dialog should respond to key-presses of <kbd>Y</kbd> and <kbd>N</kbd> since it's conceptially posing for a Yes/No/Cancel dialog. Perhaps <kbd>S</kbd> and <kbd>D</kbd> if you disagree, but if there's no way to control this dialog with the keyboard, that's bad.

(To be pedantic: Windows introduced a few version ago that by pressing <kbd>Alt</kbd> the letters that respond to <kbd>Alt</kbd>-combinations show underlined. It may be a flavour, but one one grows accustomed to.)

**Comment by mnquintana** [comment] 2015-06-16 12:06
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/2928 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-16 12:06 UTC
