### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, lstat '/\webdav.dcourseweb.com@SSL\DavWWWRoot\'

### ISSUE THREAD

**Issue by aaronstokes** [atom/atom#16580] opened 2018-01-17 15:26 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, lstat '\\webdav.dcourseweb.com@SSL\DavWWWRoot\'

```
At fs.js:902

Error: UNKNOWN: unknown error, lstat '\\webdav.dcourseweb.com@SSL\DavWWWRoot\'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at start (fs.js:1515:10)
    at Proxy.realpathSync (fs.js:1503:3)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at atom.project.getPaths.map (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:73)
    at Array.map (native)
    at Object.startTask (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:56)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/fuzzy-finder/lib/main.js:109:43)
    at get_process.nextTick (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/fuzzy-finder/lib/main.js:25:45)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.0.3 
atom-beautify 0.30.9 
atom-material-ui 2.1.1 
atom-python-run 0.9.5 
autoclose-html 0.23.0 
autocomplete-python 1.10.5 
city-lights-syntax 1.1.6 
city-lights-ui 1.3.1 
fonts 3.0.3 
pigments 0.40.2 
seti-syntax 1.0.1 
seti-ui 1.9.0 
todo-show 2.1.0 
```

**Comment by rsese** [comment] 2018-01-17 19:23
Thanks for taking the time to contribute!

Though the stack trace isn't exactly the same, I think this might be a duplicate of https://github.com/atom/fuzzy-finder/issues/274 - if you have any more details about the error (e.g. steps to reproduce), please let us know in https://github.com/atom/fuzzy-finder/issues/274.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-01-17 19:23 UTC
