### ISSUE TITLE
Make setting Atom as Default Editor for filetypes easier

### ISSUE THREAD

**Issue by hebbet** [atom/atom#4893] opened 2015-01-07 16:09 UTC
Currently it is not so easy to assign atom as default editor on windows eg for all .css files

the path to atom.exe is changed with every update.

no exe in C:\Users\hebbet\AppData\Local\atom
![image](https://cloud.githubusercontent.com/assets/1423115/5648585/df87f05a-968f-11e4-87bc-ae2b5b6f9280.png)

Chrome has eg an chrome.exe in:
C:\Users\username\AppData\Local\Google\Chrome SxS\Application which starts chrome with the currect folder.

![image](https://cloud.githubusercontent.com/assets/1423115/5648575/c9bdcde4-968f-11e4-9f63-42fc08e3f0b5.png)

**Comment by kevinsawicki** [comment] 2015-01-07 21:35
Have you tried using `C:\Users\hebbet\AppData\Local\atom\bin\atom`?

That should be a consistent location that always points to the latest installed release

**Comment by hebbet** [comment] 2015-01-07 22:11
With atom it doesn't work. Tested with Windows 7 and 8.

With atom.cmd it works but with an pretty annoying cmd Window for a very
short time.

**Comment by sick51** [comment] 2015-02-11 14:39
I tried to use .lnk file in the start menu instead of the .cmd file and it seems to work. The annoying cmd window is no longer appearing.

**Comment by ArtskydJ** [comment] 2015-02-26 14:47
Thanks @sick51, it works for me!

**Comment by samirotiv** [comment] 2015-03-24 13:06
Doesn't work for me - I tried opening a C file in Windows 8 using the Start Menu shortcut, and it showed a Command Prompt window (which itself is alright), but then didn't proceed after that.

**Comment by ArtskydJ** [comment] 2015-03-24 16:38
@samirotiv The shortcut target should be `C:\Users\[you]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc\atom.exe`

**Comment by samirotiv** [comment] 2015-03-24 16:51
I think there's something wrong with that since the executable surely
wouldn't be in the Start Menu (and it indeed isn't), and the shortcut in
the Start Menu won't point to an executable in the same folder.

The location I wrote above is the target of the shortcut in the Start Menu.

Regards,
Samir.

**Comment by dogancelik** [comment] 2015-04-28 10:43
It's easy to set Atom as default editor.

1. Go to Windows Explorer
2. Select a `.txt` file, right click, go to *Open with*, then *Choose default program*
3. In dialog, copy and paste this: `%LOCALAPPDATA%\atom\bin\atom.cmd` and click *OK*

[Here's a GIF](http://cl.ly/image/0H1T1W3a013G)

`atom.cmd` is a shortcut to the **latest version** of Atom.

**Comment by Amleto** [comment] 2015-05-02 23:22
I used the atom installer for win 7.  There is no bin directory in ```%LOCALAPPDATA%\atom```

**Comment by dogancelik** [comment] 2015-05-02 23:48
@Amleto

Create a new batch file and save it as `atom.cmd` and put it in `%LOCALAPPDATA%\atom\bin\` then make sure that directory is in PATH.
```
@echo off
FOR /F "delims=" %%i IN ('dir %LOCALAPPDATA%\atom\app-* /b /ad-h /t:c /o:d') DO SET foldername=%%i
%LOCALAPPDATA%\atom\%foldername%\resources\cli\atom.cmd
```

This batch file I created will get the latest version of Atom and start it.

**Comment by bilderbuchi** [comment] 2015-05-11 12:54
:+1: on this issue. While targeting atom.cmd works, it's not really a great workaround, since
* you have to know and manually paste the path to that cmd file
* you get a blank rectangle as the file icon, not the Atom logo, so the file association is not clear.
* you get an annoying short flicker of a terminal when opening files, which you don't get when opening Atom itself via the start menu.

**Comment by samirotiv** [comment] 2015-05-11 21:08
Touché.

On Mon, May 11, 2015 at 6:24 PM, Christoph Buchner <notifications@github.com

**Comment by rjv** [comment] 2015-05-18 14:07
:+1:

**Comment by atom-project** [comment] 2015-05-25 01:12
:+1:

**Comment by ceddc** [comment] 2015-05-27 07:43
:+1:

**Comment by dogancelik** [comment] 2015-06-04 08:46
As @bilderbuchi said, that terminal dialog before Atom is really annoying and takes a lot of time.

**Comment by refactorsaurusrex** [comment] 2015-06-04 22:10
:+1:

**Comment by designisokay** [comment] 2015-06-05 05:47
:+1:

**Comment by kamijoutouma** [comment] 2015-06-07 10:31
:+1:

**Comment by rjfmachado** [comment] 2015-06-24 09:41
:+1:

**Comment by nhogle** [comment] 2015-06-26 17:35
:+1::+1:

**Comment by MatthewSteen** [comment] 2015-06-26 22:22
:+1:

**Comment by tylerapplebaum** [comment] 2015-07-02 20:07
:+1:

**Comment by JamesMilnerUK** [comment] 2015-07-03 15:56
:+1:

**Comment by dogancelik** [comment] 2015-07-06 09:49
A solution could be: A C program (compiled with MinGW) that finds latest folder, starts Atom
This program would find the latest Atom folder (`AppData\Local\atom\app-1.0.0\`), and behave like the batch file `resources\cli\atom.cmd`

**Comment by swharrell** [comment] 2015-07-09 14:08
:+1: Love the editor but this is an annoying issue.

**Comment by crabilld** [comment] 2015-07-09 22:14
Hello Windows 95: ![win-95-ftw](https://cloud.githubusercontent.com/assets/2469658/8608115/bba7433c-264c-11e5-9bb0-7a12db4798fc.jpg)

**Comment by PerfectSlayer** [comment] 2015-07-10 07:39
Please add this! :+1:

**Comment by w1res** [comment] 2015-07-13 14:01
The solutions here work, but the Icon wrong (it is the ugly system default) and it isn't clear what program you are opening the file with.

**Comment by shiftkey** [comment] 2015-07-16 23:52
There's a lot going on in here, so I'll just summarize the feedback as I see it:

 - it'd be nice to have Atom appear in the "Default Programs" list - how this will work with the potentially unknown number of file extensions available, I'm not sure.
 - when manually setting Atom to be associated with a specific extension using `atom.cmd`, the icon is not used. That should be addressed with the previous step.
 - the current workaround for pointing to the `atom.cmd` script means a command prompt is launched - perhaps an alternative approach is necessary here.

Did I miss anything?

**Comment by miroslawlis** [comment] 2015-07-17 21:32
:+1:

**Comment by batjko** [comment] 2015-07-17 21:37
Please, the added +1s are just adding noise at this point. People are aware of the gravity of the request, as Windows is a big user base for Atom (and Electron incidentally), and the issue is being worked on.

**Comment by samirotiv** [comment] 2015-07-19 16:58
+1 to your comment. ;)

**Comment by bilderbuchi** [comment] 2015-07-20 06:19
>  and the issue is being worked on.

@batjko is that so? There is no label on this issue that would indicate that (like in-progress, work-in-progress, under-review)

**Comment by shiftkey** [comment] 2015-07-20 07:08
@bilderbuchi 

> is that so? There is no label on this issue that would indicate that 

You're right, the issue is still unassigned. Sorry for not making it clearer what I've been up to.

**Comment by batjko** [comment] 2015-07-20 07:19
> @batjko is that so? There is no label on this issue that would indicate that (like in-progress, work-in-progress, under-review)

Well, it's just something one adds to a comment like that ;)
Nonetheless, awareness has been raised to the point where any further +1's don't add any value.

**Comment by kamijoutouma** [comment] 2015-07-20 07:27
Mfw my email has been spammed with these DaMN +1's chill please. BTW you can easily just make a simple wrapper exe that calls the function  for opening files in atom and have that automatically set to be default on install.

**Comment by spenat28** [comment] 2015-07-21 13:39
+1

**Comment by mnquintana** [comment] 2015-07-21 13:42
All these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – we may unlock it once someone starts working on this enhancement to get further feedback.

**Comment by wmhilton** [comment] 2015-08-01 17:38
I made a workaround using AutoHotKey.

atom.ahk:
```
Run, %LocalAppData%\atom\bin\atom.cmd %1% %2% %3% %4% %5% %6% %7% %8% %9% %10%,,Hide
```

Then using Ahk2Exe for AutoHotkey:
![screenshot_11](https://cloud.githubusercontent.com/assets/587740/9019989/5b830114-37c5-11e5-8178-1baa4930278b.png)

Now when I set filetypes to "Open With..."
![screenshot_14](https://cloud.githubusercontent.com/assets/587740/9020007/efe9015a-37c5-11e5-99ba-314a2c8d6cbb.png)

They have this nice icon:
![image](https://cloud.githubusercontent.com/assets/587740/9020021/76752ea6-37c6-11e5-9fa9-2d7b2289fc6f.png)

**Comment by regendo** [comment] 2015-08-05 20:55
That autohotkey script doesn't work for files with spaces in their file name. With quotes, it does.

    Run, %LocalAppData%\atom\bin\atom.cmd "%1%",,Hide

**Comment by chrwi** [comment] 2015-08-11 08:01
I tried your solution @wmhilton but the Open With... dialog wont "find" the generated exe (tested to be working) even though I'm pointing right at it...

**Comment by johnrezzo** [comment] 2015-08-11 14:23
Definitely need a fix for this. It would be good to have an Atom setting with all the main file extensions to choose from.

**Comment by RogerSik** [comment] 2015-08-19 07:36
:+1:

**Comment by jaybkun** [comment] 2015-08-19 14:34
:+1:

**Comment by onetrev** [comment] 2015-08-19 15:06
Stop the thumbs up madness. If you are here to add one, please stop and think. GitHub is not a feature voting system. All these thumbs up are giving Windows users a bad name and not helping Atom folks or the community get this issue fixed.

**Comment by bilderbuchi** [comment] 2015-08-19 18:47
They do help to make the Atom team be aware of the scope of this issue / the big number of affected users, so they may prioritize issues accordingly. 
This is not giving Windows users a bad name, this is giving the Github issue tracking system a bad name for not having something like google code "stars" or Launchpad "affects me too!" -equivalent systems implemented. ;-)

**Comment by mnquintana** [comment] 2015-08-19 18:50
> They do help to make the Atom team be aware of the scope of this issue / the big number of affected users, so they may prioritize issues accordingly.

Unfortunately, not really. :+1:s are only helpful up to a certain threshold - beyond that they're just noise.

I unlocked this issue to let someone post a useful workaround for subscribers to this issue, but now that it's devolved into +1s again I'm going to re-lock it to keep the noise levels down.

**Comment by damieng** [comment] 2016-02-16 18:46
Fix checked in to master. Will now appear in the list of apps from "Open With..." and the update will take care of updating/correcting the exe path.

**Closed by damieng** 2016-02-16 18:46 UTC
Labels: enhancement, windows

**Comment by 50Wliu** [comment] 2016-02-20 03:46
To clarify, Atom will only appear in the "Open With" list starting in Atom 1.7.0.  After upgrading to 1.7.0 (when it's released), if Atom is still missing in the Open With menu, please file a new issue.  Thanks!

**Comment by damieng** [comment] 2016-02-25 20:56
Screenshots showing this fix in action are at https://github.com/atom/atom/pull/10818
