### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/StruckRug67/Library/Mobile Documents/com~apple~CloudDocs/Projects/project.json'

### ISSUE THREAD

**Issue by Sebastian01** [atom/atom#4861] opened 2015-01-06 09:42 UTC
[Enter steps to reproduce below:]

1. Open atom
2. Go to File > Open... > Select "projects" folder > Open random file from tree
The file opens, but several red error balloons show up as well.

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/StruckRug67/Library/Mobile Documents/com~apple~CloudDocs/Projects/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/StruckRug67/Library/Mobile Documents/com~apple~CloudDocs/Projects/project.json'
  at Error (native)

```

### Commands

```
 11x -0:00.0 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter",
      "linter-puppet"
    ],
    "projectHome": "/Users/StruckRug67/Projects"
  },
  "editor": {
    "fontFamily": "source code pro",
    "fontSize": 12,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
language-docker, v1.1.2
language-dockerfile, v0.1.0
language-puppet, v0.10.0
linter-puppet-lint, v0.2.3
save-session, v0.11.2

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-01-06 17:56
This is a duplicate of https://github.com/atom/atom/issues/4854

**Closed by kevinsawicki** 2015-01-06 17:56 UTC

**Comment by benogle** [comment] 2015-01-06 18:31
mpeterson2/save-session#43
