### ISSUE TITLE
Auto raise

### ISSUE THREAD

**Issue by mderdem** [atom/atom#6244] opened 2015-04-03 19:57 UTC
When started from another application, e.g. windows explorer with "Open with Atom", the existing Atom process opens the file, but Atom window doesn't raise (or restore). This is however actually almost always the case when a file is double clicked in Explorer.

**Comment by 50Wliu** [comment] 2015-05-11 14:07
Duplicate of #6614, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-11 14:07 UTC
Labels: windows
