### ISSUE TITLE
File system error for Atom on Mac Sierra OS

### ISSUE THREAD

**Issue by jzelony** [atom/atom#13404] opened 2016-12-07 22:46 UTC
### Prerequisites

* [ I don't think this is applicable] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ Yes] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ Yes] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ Yes ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ I think so] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Yes ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Description:
It appears that Atom can't find a file and continues searching for it. I noticed this in var/log/system.log of Mac running Sierra v10.12.1

### Steps to Reproduce
Not sure

Dec  7 13:59:11 Jamess-MBP com.apple.xpc.launchd[1] (com.github.atom.ShipIt[49509]): Service exited with abnormal code: 1
Dec  7 13:59:11 Jamess-MBP com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Dec  7 13:59:13 Jamess-MBP ShipIt[49510]: Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7f9eb4d013c0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Application Support/com.github.atom.ShipIt/ShipItState.plist, NSUnderlyingError=0x7f9eb4d00f30 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}

**Expected behavior:**Would not expect to see file system error.

**Actual behavior:** file system error continually appearing

### Versions
Latest Atom - I think I have updated several times over about ten days.
OS version Sierra 10.12.1

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by jonc125** [comment] 2016-12-08 11:49
I can confirm I'm seeing this too on Sierra.

```
$ atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.9.0
```

And also with the latest, installed manually just now because the auto-update didn't work:
```
 atom --version
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.9.0
```

**Comment by 50Wliu** [comment] 2016-12-08 16:34
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2860 and #6397. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-08 16:34 UTC

**Comment by jzelony** [comment] 2016-12-08 22:25
Hi Wliu,
Glad to help, I really enjoy using Atom.
I wonder what the ETA is for fixing the issue I mentioned?

It looks like the bugs I was duped to have been open for a while?

Cheers,
Jim

**Comment by 50Wliu** [comment] 2016-12-08 22:30
Yeah.  This is an issue with the macOS updater framework that Atom is using, [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac).  They have an open issue about it at https://github.com/Squirrel/Squirrel.Mac/issues/131.
