### ISSUE TITLE
White borders on resize

### ISSUE THREAD

**Issue by faustinoaq** [atom/atom#15331] opened 2017-08-16 06:57 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom shows white borders when window is resized

### Steps to Reproduce

1. Open Atom
2. Resize the window using corner helper.
3. See the white borders

**Expected behavior:** No white borders

**Actual behavior:** White borders are shown.

**Reproduces how often:** Always

### Versions

```
$ atom -v
Atom    : 1.19.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

OS: Manjaro Linux KDE Gellivara Kernel 4.9

![ezgif-4-2d758ccf5c](https://user-images.githubusercontent.com/3067335/29350883-f0771e34-8225-11e7-892a-d28f3c4d7c8e.gif)

**Comment by rsese** [comment] 2017-08-16 17:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/929. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-16 17:54 UTC

**Comment by faustinoaq** [comment] 2017-08-16 18:58
Ok, Thanks you!
