### ISSUE TITLE
Wrong bracket highlighting with comments

### ISSUE THREAD

**Issue by robinki** [atom/atom#10857] opened 2016-02-17 07:55 UTC
When clicking on an opening bracket "{" in the code, atom highlights where the section starts and ends, like underlining the opening bracket { and the closing bracket }.

The problem is with comments. When writing a comment that contains brackets after an opening bracket, the highlighting is wrong, because Atom takes the comment into account. 
Example to try it out yourself:

```
    def classABC() {   // click on the bracket
      if () {
        
      }
      // }  Atom highlights this bracket, which is wrong
    }
```

**Comment by 50Wliu** [comment] 2016-02-17 19:23
This is a duplicate of atom/bracket-matcher#78 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-17 19:23 UTC
