### ISSUE TITLE
atom becomes unresponsive after opening a file with many lines

### ISSUE THREAD

**Issue by Yomi0** [atom/atom#9553] opened 2015-11-13 03:28 UTC
To reproduce
1. Download and open [words.txt](https://github.com/atom/atom/files/33582/words.txt)
2. Attempt to scroll down. 

After several, 'Editor not responding...' messages, a 'Editor has crashed.' message will appear. 

1.3.0-dev-7bcdc9a

**Comment by mnquintana** [comment] 2015-11-13 04:55
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/8864 - feel free to subscribe there for updates.

**Closed by mnquintana** 2015-11-13 04:55 UTC
