### ISSUE TITLE
Atom fails to build on FreeBSD 11.0 x86_32

### ISSUE THREAD

**Issue by cpu82** [atom/atom#6035] opened 2015-03-19 15:47 UTC
I tried to build it following this instructions: 
https://github.com/atom/atom/blob/8db47bd7b2226b858a255867aaa16419c652f64d/docs/build-instructions/freebsd.md

Here is the full build log:
http://pastebin.com/VEtB9WuY

TIA,

**Comment by cpu82** [comment] 2015-03-19 22:28
Some outputs:
```
% uname -a
FreeBSD box.underbuild.com 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r279847M: Wed Mar 11 01:46:19 CET 2015     charly@box.underbuild.com:/usr/obj/usr/src/sys/PROD  i386
```
```
% pkg info node
node-0.12.0_1
Name           : node
Version        : 0.12.0_1
Installed on   : Thu Mar 19 15:16:37 CET 2015
Origin         : www/node
Architecture   : freebsd:11:x86:32
Prefix         : /usr/local
Categories     : www
Licenses       : MIT
Maintainer     : linpct@gmail.com
WWW            : http://nodejs.org/
Comment        : V8 JavaScript for client and server
Annotations    :
Flat size      : 12.7MiB
Description    :
node - evented I/O for V8 javascript

WWW: http://nodejs.org/
```
```
% pkg info npm
npm-2.7.1
Name           : npm
Version        : 2.7.1
Installed on   : Thu Mar 19 20:23:14 CET 2015
Origin         : www/npm
Architecture   : freebsd:11:x86:32
Prefix         : /usr/local
Categories     : www
Licenses       : MIT
Maintainer     : sunpoet@FreeBSD.org
WWW            : http://npmjs.org/
Comment        : Node package manager
Options        :
	IOJS           : off
	NODE           : on
	NODE010        : off
	NODE_DEVEL     : off
Annotations    :
	cpe            : cpe:2.3:a:npmjs:node_packaged_modules:2.7.1:::::freebsd11:x86
Flat size      : 7.44MiB
Description    :
npm is a package manager for node. You can use it to install and publish your
node programs. It manages dependencies and does other cool stuff.

WWW: http://npmjs.org/
WWW: https://github.com/npm/npmff
```

**Comment by cpu82** [comment] 2015-03-20 10:35
I'm willing to help with this issue.

**Comment by pusateri** [comment] 2015-04-23 17:42
The problem with csslint is fixed in later versions. Applying this patch gets past this problem but on to the next:

--- build/package.json.orig	2015-04-23 13:32:14.919342000 -0400
+++ build/package.json	2015-04-23 13:32:58.564682041 -0400
@@ -17,11 +17,11 @@
     "grunt-cli": "~0.1.9",
     "grunt-coffeelint": "git+https://github.com/atom/grunt-coffeelint.git#cfb99aa99811d52687969532bd5a98011ed95bfe",
     "grunt-contrib-coffee": "~0.12.0",
-    "grunt-contrib-csslint": "~0.1.2",
+    "grunt-contrib-csslint": "~0.2.0",
     "grunt-contrib-less": "~0.8.0",
     "grunt-cson": "0.14.0",
     "grunt-download-atom-shell": "~0.14.0",
-    "grunt-lesslint": "0.13.0",
+    "grunt-lesslint": "0.17.0",
     "grunt-peg": "~1.1.0",
     "grunt-shell": "~0.3.1",
     "harmony-collections": "~0.3.8",

**Comment by pusateri** [comment] 2015-04-23 21:45
More forward progress:
# pkg install gcc

export CC=/usr/local/bin/gcc48
export CXX=/usr/local/bin/g++48
export GYP_DEFINES="linux_breakpad=0"

Without the breakpad crash reporter, I don't think we need minidump. So I removed minidump from build/package.json.

The new error is now:
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:366:17)

which may be angular or font-awesome but still looking into it.

**Comment by pusateri** [comment] 2015-04-25 13:33
This throw er; turns out to be the fact that apm is trying to download a binary package of node to run and freebsd isn't in the list of built packages.

http://nodejs.org/dist/v0.10.35/

dark% node ./script/download-node.js
http://nodejs.org/dist/v0.10.35/node-v0.10.35-freebsd-x64.tar.gz
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: incorrect header check
  at Zlib._handle.onerror (zlib.js:366:17)

Can anyone explain why apm tries to download another node runtime?

**Comment by pusateri** [comment] 2015-04-25 13:52
Looks like I'm chasing jbt who's already identified this:

https://github.com/atom/apm/issues/312

**Comment by shkhln** [comment] 2015-04-27 01:39
> Can anyone explain why apm tries to download another node runtime?

You should probably know that the last step in 'source install' is downloading binary electron (gnome-shell) package from https://github.com/atom/electron/releases. That doesn't sound so bad until you actually try to build electron *from sources* and see it trying to download binary version of itself.

**Comment by pusateri** [comment] 2015-04-27 01:50
Nice. Haven't got there yet. I'm thinking of working from the FreeBSD port infrastructure and just patching files to get rid of these circular dependencies. I was able to just remove the install target in apm ./script/download-node.js and skip the download of another binary of node. Then apm build and tested ok standalone.

**Comment by pusateri** [comment] 2015-05-19 20:10
I've gotten apm (atom-package-manager) to compile on FreeBSD but 'apm install' isn't working. Not sure why yet (see https://github.com/atom/apm/issues/282). Lately, I've been working on libchromiumcontent. It requires a lot of the same patches as the FreeBSD port does for Chromium. I'm not done yet though and I'm not sure how to get those changes into the tree. There are still 3 or 4 places that download binaries of node or iojs I've come across in Atom overall that have to be worked around for a non-supported OS. If anyone wants to help, please let me know. It's a big job.

**Comment by shkhln** [comment] 2015-05-19 21:21
> It requires a lot of the same patches as the FreeBSD port does for Chromium.
Take a look at my building notes: https://gist.github.com/shkhln/208a1e6b945e5f07046b. I was hoping to produce a proper makefile, but that will do for now.

**Comment by pusateri** [comment] 2015-05-22 22:41
Thanks for the build instructions. So we need a plan of attack. Should we just build FreeBSD ports for all of the components first and that way we can apply patches and include external dependencies without having to get everything merged? Then we can work to get the changes merged into the distribution and slowly remove the patches from the ports?

**Comment by shkhln** [comment] 2015-05-26 02:48
> Thanks for the build instructions.

Were they at least somewhat helpful? I mean, were you able to build libchromiumcontent?

> Should we just build FreeBSD ports

That would be lovely.

**Comment by pusateri** [comment] 2015-06-02 18:50
Working on a port of libchromiumcontent using your gist: https://gist.github.com/shkhln/208a1e6b945e5f07046b

The ports infrastructure doesn't want to clone repos. They want to download a binary release that can be verified. But the repo at https://github.com/gliaskos/freebsd-chromium hasn't produced a release tag since last November. I'm not sure how to download a .tgz file based on hash, only a tag.

If you know the repo owner (gliaskos), maybe you could ask them if they plan to create any more release tags.

This is necessary for submodules too. So the port Makefile is getting pretty complicated downloading all of the components. It's not finished but if you want to take a look, you can monitor progress here:
https://github.com/pusateri/ports/tree/master/www/libchromiumcontent

**Comment by pusateri** [comment] 2015-06-02 18:54
Also, I would't have to use the https://github.com/gliaskos/freebsd-chromium repo, I might could use the existing chromium port but I'm not sure how to have access to the work directory of another port. So I think I need to download all of the source in a self contained port.

**Comment by pusateri** [comment] 2015-06-03 04:46
Ok, I was mistaken about needing a release tag. FreeBSD ports seem to work fine with a commit hash. So now I just need to fix an error in my Makefile that is preventing the download from completing.

**Comment by shkhln** [comment] 2015-06-03 07:15
> Also, I would't have to use the https://github.com/gliaskos/freebsd-chromium repo

That's the semi-official chroimum port repo according to the https://wiki.freebsd.org/Chromium. There is no particular reason I'm refering to that repo in the gist, except it is slightly easier to tinker with than the whole ports tree.

> I might could use the existing chromium port but I'm not sure how to have access to the work directory of another port. So I think I need to download all of the source in a self contained port.

Is it ok to nest ports like that? It might be easier to copy the chromium port's patchset and compile flags, as I don't see any clean way to reuse them at all. I'm not really that familiar with the ports infrastructure, though.

> Ok, I was mistaken about needing a release tag. FreeBSD ports seem to work fine with a commit hash.

Don't forget to pick chromium port and libchromiumcontent versions based on the same major chromium release. Right now you are mixing 43.0.2357.65 with 42.0.2311.135.

**Comment by pusateri** [comment] 2015-06-03 19:01
Yeah, I've got the version mismatch fixed and the downloading works thanks to some ports help on the mailing list. They suggest make a chromium slave port. I will get it working standalone first as an exercise and then see about converting it to a slave port.

**Comment by cpu82** [comment] 2015-08-07 21:42
@pusateri, is any update trying to create a port for atom?

**Comment by yonas** [comment] 2015-10-18 06:18
Any news on bringing atom to FreeBSD 10/11?

**Comment by yonas** [comment] 2015-10-18 06:31
I'm seeing the same issues as #8885:

```
# env CC=clang CXX=clang++ LINKXX=clang++ LINK=clang ./script/build 
Node: v4.1.1
npm: v2.13.3
Installing build modules...
Traceback (most recent call last):
  File "/root/atom/build/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/root/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/root/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/root/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/root/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/root/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2756, in Load
    RemoveLinkDependenciesFromNoneTargets(targets)
  File "/root/atom/build/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 1501, in RemoveLinkDependenciesFromNoneTargets
    if targets[t].get('variables', {}).get('link_dependency', 0):
KeyError: 'deps/breakpad/breakpad.gyp:dump_syms#target'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/root/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System FreeBSD 10.2-RELEASE
gyp ERR! command "/usr/local/bin/node" "/root/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/atom/build/node_modules/minidump
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! FreeBSD 10.2-RELEASE
npm ERR! argv "/usr/local/bin/node" "/root/atom/build/node_modules/.bin/npm" "--userconfig=/root/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v4.1.1
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/atom/build/npm-debug.log
```

**Comment by pusateri** [comment] 2015-10-18 17:21
I haven't worked on this in a while. You don't need minidump:

--- a/build/package.json
+++ b/build/package.json
@@ -26,7 +26,6 @@
     "grunt-shell": "~0.3.1",
     "harmony-collections": "~0.3.8",
     "legal-eagle": "~0.9.0",
-    "minidump": "~0.8",
     "npm": "2.5.1",
     "rcedit": "~0.3.0",
     "request": "~2.27.0",

**Comment by pr1ntf** [comment] 2015-10-23 15:30
I'm currently trying to build Atom on `FreeBSD  11.0-CURRENT FreeBSD 11.0-CURRENT #0: Sun Oct 18 15:17:12 UTC 2015`

I have installed `node`, `npm`, and `libgnome-keyring` along with running `npm config set python /usr/local/bin/python2 -g` as stated I should do so in [this readme](https://github.com/atom/atom/blob/master/docs/build-instructions/freebsd.md)

For the record, @pusateri's diff fixed the minidump error on FreeBSD 11-CURRENT, but now I'm onto some more errors: 
````
download not found: http://nodejs.org/dist/v0.10.40/node-v0.10.40-freebsd-x64.tar.gz
npm ERR! FreeBSD 11.0-CURRENT
npm ERR! argv "/usr/local/bin/node" "/usr/home/pr1ntf/atom/build/node_modules/.bin/npm" "--userconfig=/usr/home/pr1ntf/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v4.2.1
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.4.0 install: `node ./script/download-node.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.4.0 install script 'node ./script/download-node.js'.
npm ERR! This is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-node.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/pr1ntf/atom/apm/npm-debug.log
````

>download not found: http://nodejs.org/dist/v0.10.40/node-v0.10.40-freebsd-x64.tar.gz


Makes sense because `http://nodejs.org/dist/v0.10.40/node-v0.10.40-freebsd-x64.tar.gz` does not exist. 
I'm assuming there's some sort of `uname` stuff going on, is there anyway to force the script to grab the `https://nodejs.org/dist/v0.10.40/node-v0.10.40.tar.gz` tarball?

I'm happy to help, I want to see Atom in the ports tree. :grinning:

**Comment by pr1ntf** [comment] 2015-10-23 20:43
I guess I should actually learn to read the _whole_ ticket before asking next time. libchromium, got it. 
I'll report back with any issues.

**Comment by dfr** [comment] 2015-12-21 14:09
Any progress on this? I would also like to be able to use Atom on FreeBSD.

**Comment by tony** [comment] 2016-01-14 20:17
Link to the minidump ticket: https://github.com/atom/node-minidump/issues/4

**Comment by Makdiuk** [comment] 2016-02-07 23:58
I am update pathwatcher - v 6.3.1
And try Again install Atom Package Manager.
Get The Same Problem:
``` sh
download not found: http://nodejs.org/dist/v0.10.40/node-v0.10.40-freebsd-x64.tar.gz
/usr/local/lib
└── (empty)

npm ERR! FreeBSD 11.0-CURRENT
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "atom-package-manager"
npm ERR! node v0.10.40
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.6.0 install: `node ./script/download-node.js`
npm ERR! Exit status 1
```

**Comment by mike-pt** [comment] 2016-02-12 02:08
I was looking into the ports version of node and it fetches node from "http://nodejs.org/dist/vX.X.X/node-vX.X.X.tar.gz so this could be fixed in the download-node.js script.

At I've tried is point it to the local installed node version and I get other errors (will post soon)

**Comment by yohanesu75** [comment] 2016-02-13 03:29
node-v0.10.40-freebsd-x64.tar.gz seem to be a dependency for building Atom. Even if I build and install this version as the system default, Atom's dependencies depend on other version of node I think, and it also wants to download from nodejs.org/dist/ even though I have the same version as system default.
 
I have built v0.10.40 from tarball successfully on my freebsd-x64 machine using the patch from /usr/ports/www/node010/files/. The problem is, how can I tell node/npm to look for the binary tarball on my harddisk and not on nodejs.org/dist/?.. 

Is the solution to build binaries for freebsd and send to nodejs so they can make them available?

**Comment by lebel** [comment] 2016-03-18 00:51
Still no solutions?  I still fail to build at the point where the build process tries to fetch the pre-built version of node 0.10.40 from nodejs website.

**Comment by pusateri** [comment] 2016-03-18 04:15
atom/apm is trying to download node.js. You can use node010 installed from the ports collection by just commenting out the install line in the scripts section of apm/package.json. But even after getting apm to work, you then have to get libchromiumcontent, electron, and several other packages. I tackled libchromiumcontent for a while but it was very time consuming. My approach was to build ports for these components in order to apply patches since getting changes upstream is difficult. This is no small project and you will have to contribute significant resources to get atom working on FreeBSD.

**Comment by zacts** [comment] 2016-08-27 20:18
Is there still interest in getting atom to build on FreeBSD, namely FreeBSD-11?

**Comment by scottgeigel** [comment] 2016-08-28 00:32
I'm still interested. I kind of like FreeBSD, but support for atom is kind of a deal breaker for me on Operating Systems.

**Comment by yonas** [comment] 2016-08-28 00:39
I think I can safely say that a lot of FreeBSD users would appreciate having Atom and Electron-based applications running on their desktop, just like any Linux user.

With the upcoming release of FreeBSD 11, it would be great to have Atom support as another great reason to get excited for FreeBSD on the desktop.

**Comment by yohanesu75** [comment] 2016-08-28 00:50
I came as far as discovering that electron was very difficult to get running on FreeBSD... Any progress here? I for one would love to see Atom on FreeBSD.

**Comment by yohanesu75** [comment] 2016-08-28 00:52
Soon we'll have updated graphics support in line with Linux so FreeBSD will be even nicer to run as desktop OS.

**Comment by yonas** [comment] 2016-08-28 00:52
@yohanesu75 Some work was being done in https://github.com/electron/electron/issues/3797

**Comment by bclark-systech** [comment] 2016-08-30 16:22
I switched from FreeBSD to Linux just to get Atom to work, so yes, I would greatly appreciate it if we can have a working version for FreeBSD. Thank you to those working on a solution.

**Comment by prash-wghats** [comment] 2016-10-12 07:46
Was able to build electron and VSCode in freebsd11RC1. the build instruction is posted in
https://gist.github.com/prash-wghats/89be1ee069d2acf23c289e9c606616e1

**Comment by yohanesu75** [comment] 2016-11-22 02:58
Seems like someone was successful at https://github.com/electron/electron/issues/3797. Can we use that to get Atom running?

**Comment by MAHDTech** [comment] 2017-03-26 03:06
Any updates from this side?

**Comment by trollboy** [comment] 2017-04-30 04:46
Updates would be appreciated.  
https://gist.github.com/trollboy/c3aae8e9a1decbaded10e30eaaa3c77a

**Comment by tony** [comment] 2017-04-30 04:50
Something like electron / atom really needs official support. It's just being ignored now. What's the point of anything if there's no official backing?

It's just like developing Android apps on FreeBSD. Sure, You can do it, but the time invested in retooling yourself 1. Takes much much longer than if Android's actual developers took a small time help, 2. You wouldn't really get any Android apps shipped.

If FreeBSD/OpenBSD is going to get atom, it should work like a charm.

**Comment by trollboy** [comment] 2017-05-01 01:56
So change OS's until such time as the FreeBSD maintainers retool Electron themselves?  I don't understand the comment.

**Comment by grahamperrin** [comment] 2017-05-01 13:17
From the Bountysource page that's linked from the head of https://github.com/electron/electron/issues/3797: 

> pjincz started working on this issue …

**Comment by yonas** [comment] 2017-12-07 13:19
Because of @prash-wghats 's hard work, Electron runs on FreeBSD 11.1:

![electron-on-freebsd-11](https://user-images.githubusercontent.com/110130/33717224-1d65963c-db27-11e7-9cd8-027a001da1a5.png)

I've asked for his help in porting Atom to FreeBSD.

**Comment by yzgyyang** [comment] 2018-03-02 06:27
With the help of @prash-wghats, I am making Electron port (1.8.2) for FreeBSD (https://github.com/yzgyyang/freebsd-ports-electron). The port is now able to install Electron to /usr/local/share/electron/* and create symlink to /usr/local/bin/electron (executable) on FreeBSD. I get the idea that most of the Electron Apps come with its own copy of Electron, but starting from here, can applications based on Electron (like Atom) directly or indirectly use this?

I am not an expert of Electron/Atom, thus it would be great that I can get some help to further get atom into the ports tree.

**Comment by yzgyyang** [comment] 2018-03-02 18:34
For the information, my Electron port will install the following files:
(pkg-plist)
```
bin/electron
%%DATADIR%%/LICENSE
%%DATADIR%%/LICENSES.chromium.html
%%DATADIR%%/blink_image_resources_200_percent.pak
%%DATADIR%%/chromedriver
%%DATADIR%%/chromedriver-v1.8.2-beta.2-freebsd-x64.zip
%%DATADIR%%/content_resources_200_percent.pak
%%DATADIR%%/content_shell.pak
%%DATADIR%%/electron
%%DATADIR%%/electron-api.json
%%DATADIR%%/electron-v1.8.2-beta.2-freebsd-x64.zip
%%DATADIR%%/electron.d.ts
%%DATADIR%%/ffmpeg-v1.8.2-beta.2-freebsd-x64.zip
%%DATADIR%%/icudtl.dat
%%DATADIR%%/libffmpeg.so
%%DATADIR%%/libnode.so
%%DATADIR%%/locales/am.pak
%%DATADIR%%/locales/ar.pak
%%DATADIR%%/locales/bg.pak
%%DATADIR%%/locales/bn.pak
%%DATADIR%%/locales/ca.pak
%%DATADIR%%/locales/cs.pak
%%DATADIR%%/locales/da.pak
%%DATADIR%%/locales/de.pak
%%DATADIR%%/locales/el.pak
%%DATADIR%%/locales/en-GB.pak
%%DATADIR%%/locales/en-US.pak
%%DATADIR%%/locales/es-419.pak
%%DATADIR%%/locales/es.pak
%%DATADIR%%/locales/et.pak
%%DATADIR%%/locales/fa.pak
%%DATADIR%%/locales/fake-bidi.pak
%%DATADIR%%/locales/fi.pak
%%DATADIR%%/locales/fil.pak
%%DATADIR%%/locales/fr.pak
%%DATADIR%%/locales/gu.pak
%%DATADIR%%/locales/he.pak
%%DATADIR%%/locales/hi.pak
%%DATADIR%%/locales/hr.pak
%%DATADIR%%/locales/hu.pak
%%DATADIR%%/locales/id.pak
%%DATADIR%%/locales/it.pak
%%DATADIR%%/locales/ja.pak
%%DATADIR%%/locales/kn.pak
%%DATADIR%%/locales/ko.pak
%%DATADIR%%/locales/lt.pak
%%DATADIR%%/locales/lv.pak
%%DATADIR%%/locales/ml.pak
%%DATADIR%%/locales/mr.pak
%%DATADIR%%/locales/ms.pak
%%DATADIR%%/locales/nb.pak
%%DATADIR%%/locales/nl.pak
%%DATADIR%%/locales/pl.pak
%%DATADIR%%/locales/pt-BR.pak
%%DATADIR%%/locales/pt-PT.pak
%%DATADIR%%/locales/ro.pak
%%DATADIR%%/locales/ru.pak
%%DATADIR%%/locales/sk.pak
%%DATADIR%%/locales/sl.pak
%%DATADIR%%/locales/sr.pak
%%DATADIR%%/locales/sv.pak
%%DATADIR%%/locales/sw.pak
%%DATADIR%%/locales/ta.pak
%%DATADIR%%/locales/te.pak
%%DATADIR%%/locales/th.pak
%%DATADIR%%/locales/tr.pak
%%DATADIR%%/locales/uk.pak
%%DATADIR%%/locales/vi.pak
%%DATADIR%%/locales/zh-CN.pak
%%DATADIR%%/locales/zh-TW.pak
%%DATADIR%%/mksnapshot
%%DATADIR%%/mksnapshot-v1.8.2-beta.2-freebsd-x64.zip
%%DATADIR%%/natives_blob.bin
%%DATADIR%%/pdf_viewer_resources.pak
%%DATADIR%%/resources/default_app.asar
%%DATADIR%%/resources/electron.asar
%%DATADIR%%/snapshot_blob.bin
%%DATADIR%%/ui_resources_200_percent.pak
%%DATADIR%%/version
%%DATADIR%%/views_resources_200_percent.pak
```

So the question is, is there a way that we could utilize this for the possible atom port?

**Comment by amiramix** [comment] 2018-04-05 21:48
Is it now possible to create an atom port for FreeBSD?

**Comment by prash-wghats** [comment] 2018-04-06 05:01
https://github.com/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/releases/tag/atom_v1.23.0
https://github.com/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/tree/master/atom

**Comment by amiramix** [comment] 2018-04-06 22:08
Thanks for sharing. I will find some time to try to compile this too.

**Comment by catastrop** [comment] 2019-06-09 08:42
any update?

**Comment by shkhln** [comment] 2019-06-09 09:05
@catastrop
> any update?

https://github.com/electron/electron/issues/3797#issuecomment-487287467

**Comment by lapo-luchini** [comment] 2019-06-17 16:03
Also: https://github.com/tagattie/FreeBSD-Atom

**Comment by amiramix** [comment] 2020-06-17 07:43
Atom can now be compiled on FreeBSD, see https://www.freshports.org/editors/atom
However, it's marked as deprecated because it's using Python 2.7

**Comment by lkashef** [comment] 2020-07-16 07:07
Thanks @amiramix for the update. I will close this issue but if anyone interested to learn about Python changes in Atom you can check [this PR](https://github.com/atom/atom/pull/20716)

**Closed by lkashef** 2020-07-16 07:07 UTC
Labels: blocked, build-error, electron, linux
