### ISSUE TITLE
Duplicate files in sidebar removes extension in special filenames

### ISSUE THREAD

**Issue by iamzozo** [atom/atom#9286] opened 2015-10-26 11:08 UTC
When I'm duplicating a file in the sidebar with CTRL+C, CTRL+V it removes the extension if the filename has double dots, like: **index.blade.php** become: **index0.blade**

**Comment by 50Wliu** [comment] 2015-10-26 11:54
This is a duplicate of atom/tree-view#581 - please subscribe there for updates.

**Closed by 50Wliu** 2015-10-26 11:54 UTC
