### ISSUE TITLE
Auto-update should not be compulsory

### ISSUE THREAD

**Issue by artcommacode** [atom/atom#8838] opened 2015-09-18 09:39 UTC
##### Expected:
I open Atom, ready for another productive day of work.

##### Reality:
Atom uses all 60KB/s of my bandwidth to download an unneeded update and I can't get anything done for the next hour.

##### Possible Fixes:
Add a checkbox to Settings that allows those of us in low-bandwith situations to turn off auto-updating.

Thanks!

**Comment by 50Wliu** [comment] 2015-09-18 15:53
Duplicate of #1882, please subscribe there for updates.

**Closed by 50Wliu** 2015-09-18 15:53 UTC

**Comment by artcommacode** [comment] 2015-09-18 16:24
Obviously I didn't search well enough. Thanks
