### ISSUE TITLE
Move to new pane [enhancement] [ux]

### ISSUE THREAD

**Issue by OJFord** [atom/atom#11025] opened 2016-03-02 02:25 UTC
### Description

Maybe my work pattern is strange, but almost 100% of the time when I want a new pane (i.e. to split) I want to _move_ an _existing_ buffer to that new pane. Not duplicate it, and not create an empty pane.

### Steps to Reproduce

1. Split pane right
2. Oh. Not what I wanted.
3. Move buffer to new pane

**Expected behavior:** I don't expect, but I desire the buffer to move to the newly created pane.

**Actual behavior:** The newly created pane is either empty, or the focussed buffer is opened there as well as remaining in existing pane.

Suggestion is to add 'split and move pane right/left/up/down'.

### Versions
```sh
atom 1.5.3
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.2
```

**Comment by mnquintana** [comment] 2016-03-02 02:27
Thanks for the suggestion! :smile: This looks like a duplicate of https://github.com/atom/atom/issues/2670 though, so I'm going to close this out in favor of that issue. Feel free to subscribe there for updates!

**Closed by mnquintana** 2016-03-02 02:27 UTC

**Comment by OJFord** [comment] 2016-03-02 02:31
Oops! I confess I did see that when I searched, but from the title assumed it was purely about navigation.

Cheers.
