### ISSUE TITLE
The editor crashed when attempting to Install Packages

### ISSUE THREAD

**Issue by galpin** [atom/atom#9158] opened 2015-10-15 15:14 UTC
I get the following error whenever I cilck on "Install" in the Settings pane.

I am on Windows 7 with v1.0.19.

Any ideas?

![image](https://cloud.githubusercontent.com/assets/485240/10518059/981cb8d6-7357-11e5-8610-2d0bf7577a42.png)

**Comment by Zireael07** [comment] 2015-10-15 16:57
Are you behind a proxy?

**Comment by galpin** [comment] 2015-10-15 18:59
Yes, I am on a corporate network.

**Comment by Zireael07** [comment] 2015-10-16 09:16
Duplicate of #8465, then.

**Comment by 50Wliu** [comment] 2015-10-16 12:19
Thanks, @Zireael07!

**Closed by 50Wliu** 2015-10-16 12:19 UTC
