### ISSUE TITLE
Atom keeps adding desktop shortcut

### ISSUE THREAD

**Issue by BrandonDusseau** [atom/atom#5323] opened 2015-01-30 21:58 UTC
Atom keeps recreating its desktop shortcut unexpectedly. I'm guessing it's something involved in the automatic update process, since it doesn't happen all the time. Creating a desktop shortcut on initial installation makes sense, but doing it every time a background update occurs does not.

I'm using Atom 0.176.0 on Windows 8.1 x64.

**Comment by 50Wliu** [comment] 2015-01-30 22:52
This is something that @paulcbetts said would be addressed eventually.  Basically if you delete the shortcut it won't come back again.

**Comment by paulcbetts** [comment] 2015-01-30 23:02
I'll have a look at this soon

**Comment by BrandonDusseau** [comment] 2015-01-31 01:14
Thanks, both of you.
@50Wliu I've deleted the shortcut a few times, but it keeps getting replaced. That's why I filed the issue.

**Comment by 50Wliu** [comment] 2015-01-31 01:37
Sorry, should have mentioned that that was the *plan* and that it's not implemented yet.

**Comment by BrandonDusseau** [comment] 2015-01-31 02:26
Gotcha!

**Comment by paulcbetts** [comment] 2015-01-31 02:40
This could also be addressed directly in Atom today now that we've landed Squirrel/Squirrel.Windows#201

**Comment by kevinsawicki** [comment] 2015-02-03 02:27
This should have been addressed by https://github.com/atom/atom/commit/3d149eb9d151d72a51bda9721ddfc4d5d341c425

@BrandonDusseau What is the absolute path to the desktop shortcut it is creating?

**Comment by BrandonDusseau** [comment] 2015-02-03 03:11
@kevinsawicki F:/Brandon/Desktop/
It hasn't done it again since I filed the bug, but I don't know if an update has occurred since then.

**Comment by BrandonDusseau** [comment] 2015-02-03 18:00
@kevinsawicki No, it's set to C:\Users\Brandon.

**Comment by kevinsawicki** [comment] 2015-02-03 18:08
> No, it's set to C:\Users\Brandon.

Yeah, so thats the issue.

**Comment by BrandonDusseau** [comment] 2015-02-03 18:11
Is there a way to force the update process so that I can see if this is still an issue?

**Comment by kevinsawicki** [comment] 2015-02-03 18:12
An update was just released so you should see a 0.177 update soon

**Comment by kevinsawicki** [comment] 2015-02-03 18:16
If you open Atom, open the dev tools (`ctrl-alt-I`) and type `process.env` in the Console tab, do you have any variables listed that refer to `F:\Brandon\Desktop` or anything desktop related?

**Comment by BrandonDusseau** [comment] 2015-02-03 20:32
None of the variables refer to that location. The icon just came back after applying the update.

**Comment by paulcbetts** [comment] 2015-02-03 21:56
@BrandonDusseau How did your user folder end up on the F: drive? Knowing that should help us fix this

**Comment by BrandonDusseau** [comment] 2015-02-03 22:21
I keep my personal files separate from my OS drive, so when I install Windows I go to the properties of each default folder in my user profile and select "Change location." The user profile itself remained with the OS drive, but each of the default folders maintains a separate location variable in the registry (it may be accessibly elsewhere as well).

**Comment by 50Wliu** [comment] 2015-02-21 22:29
@BrandonDusseau can you still reproduce this?  I just updated to 0.182.0 and no new shortcut appeared (I didn't have a shortcut before updating, either).

**Comment by BrandonDusseau** [comment] 2015-02-22 05:08
Just updated from 0.179.0 to 0.182.0. Can confirm that the icon does not come back.

**Comment by pbraga** [comment] 2015-09-24 11:15
i have version 1.0.15 and still have this same issue.
I believe it is tied to every update to atom, i delete the shortcut but after update a new one is created.
It should either be an option or only create on first installation.

**Comment by BrandonDusseau** [comment] 2015-09-24 13:29
I noticed that it popped up again too, but never got around to reopening this.

**Comment by pbraga** [comment] 2015-09-24 13:33
I only started using from 1.0.2, but with recent series of updates in not
so many days this became more evident.

When i searched atom.io for it only found this so decided to alert it was
not solved.

**Comment by 50Wliu** [comment] 2015-09-24 13:40
Refs #8789.

**Comment by mastazi** [comment] 2015-09-24 23:52
I just updated from 1.0.17 to 1.0.18 on Win 8.1 X64 and the desktop icon was not added (In the previous update, from 1.0.16 to 1.0.17, it was added), so it's now working for me.

**Comment by 50Wliu** [comment] 2015-09-25 01:32
Can also confirm that it didn't reappear for me.

@paulcbetts do you think that this can be closed?

**Comment by BrandonDusseau** [comment] 2015-09-25 03:56
I just had it reappear when auto-updating from 1.0.16 to 1.0.18.

**Comment by mastazi** [comment] 2015-09-25 05:32
@BrandonDusseau can you let us know after your next update? When I was updating from 1.0.16 I was in your same situation.

**Comment by GizMecano** [comment] 2015-09-25 06:25
I'm sorry to say that this issue is still persistent when updating from 1.0.16 to 1.0.18 with Windows 7 64bts SP1 this morning.

By the way, the auto-updater system continues also to (re)create a folder `GitHub, Inc` and a shortcut in `AppData\Roaming\Microsoft\Windows\Start Menu\Programs` (what is annoying when you have set up a customized workspace): I don't know if the opening of a new issue is needed or if this behaviour is related to the present one.

**Comment by mastazi** [comment] 2015-09-25 09:10
It would be great to hear from anyone who updated from 1.0.17 (or newer). Please note that the important bit is the version you update from, not the version you update to.

**Comment by pbraga** [comment] 2015-09-25 09:28
yes you could be right, unfortunately i also went from 1.0.16 to 1.0.18 so the fact it reappeared could be due to version 1.0.16. I will post how the next update goes.

**Comment by 50Wliu** [comment] 2015-09-25 12:20
Next time someone experiences this bug, it would be great if they could post the contents of their `%localappdata%/atom/SquirrelSetup.log` file.

**Comment by GizMecano** [comment] 2015-09-25 12:45
The full content, really? This file is actually huge: more than 17'000 lines for the last iteration that I've found...

**Comment by 50Wliu** [comment] 2015-09-25 14:11
Just the last time Squirrel updated Atom to a new version.  Also, so that this issue doesn't become massive, uploading the file as a Gist and then pasting the link here would probably be better.

**Comment by GizMecano** [comment] 2015-09-25 14:30
@50Wliu : Good idea :+1: 

I have uploaded the `log` [file from my last update](https://gist.github.com/GizMecano/a4b06e1b576a20671443) (I have only translated directory names for better readability).

Hoping you will find something interesting...

**Comment by 50Wliu** [comment] 2015-09-28 01:43
I don't actually see Squirrel logging info about adding shortcuts (other than during the initial installation), which is a bit weird.

**Comment by BrandonDusseau** [comment] 2015-09-28 02:44
Just completed upgrade from 1.0.18 to 1.0.19. The shortcut reappeared before restarting Atom.
[Log file is here](https://gist.github.com/BrandonDusseau/b03d4ccfdb6f7554fa71).

**Comment by pbraga** [comment] 2015-09-28 09:13
Hi i tried to check for updates, trough help menu, today (with version 1.0.18) and while atom told me i was up to date the icon reappeared ! 
So it seems the update check triggers the recreation of the shortcut. Either directly or by updating/changing some varible.

**Comment by 50Wliu** [comment] 2015-09-28 12:18
```
2015-09-27 22:39:33> ApplyReleasesImpl: Processing shortcut 'C:\Users\Brandon\AppData\Local\atom\app-1.0.18\atom.exe'
2015-09-27 22:39:33> ApplyReleasesImpl: Does not match 'C:\Users\Brandon\AppData\Local\atom\app-1.0.16', continuing to next directory
```
is the only thing that seems interesting from @BrandonDusseau's log.

**Comment by GizMecano** [comment] 2015-09-28 15:15
I had the same issue as @pbraga, but I've noticed some changes in the `log`.

There is more than 2'000 additions and, even if Atom wasn't updated, the version string "1.0.19" appears 50 times [in the file](https://gist.github.com/GizMecano/a4b06e1b576a20671443/revisions).
By the way, the application continues to add a shortcut on the desktop and in a folder named ``GitHub, Inc.` in `AppData\Roaming\Microsoft\Windows\Start Menu\Programs\`

:disappointed:

**Comment by rugk** [comment] 2015-09-28 15:18
> Hi i tried to check for updates, trough help menu, today (with version 1.0.18) and while atom told me i was up to date the icon reappeared !
So it seems the update check triggers the recreation of the shortcut. Either directly or by updating/changing some varible.

I cannot confirm this. Just tried it and no shortcut was created.

**Comment by GizMecano** [comment] 2015-09-28 15:40
@rugk : Could you tell if the update to the version 1.0.19 was successful?

(And, by the way, I wonder if we should specify the OS configuration in order to better define the issue)

**Comment by rugk** [comment] 2015-09-28 16:06
> @rugk : Could you tell if the update to the version 1.0.19 was successful?

Yes, but I've skipped so,me versions there.

Windows 7 x64

**Comment by pbraga** [comment] 2015-09-28 16:40
In the meantime i was able to update to 1.0.19  after restarting atom and
no shortcut appeared, i am on Windows 7 64bit. It seem s atom may have
indeed download the update as described previously and was simply did not
update the help menu.
In short the behaviour of recreating the shortcut seems tied to the update
downlad and that has not changed in the update from 1.0.18 to 19.

**Comment by GizMecano** [comment] 2015-09-28 17:15
According to the last comment of @pbraga, I've restarted Atom for a third time, and the update has been applied indeed. FYI, I uploaded the `log` file as [a gist](https://gist.github.com/GizMecano/a4b06e1b576a20671443/revisions).

I must admit I'm a bit surprised by the lines 3-7 (which seem to still allude to creation of shortcuts):

```
ApplyReleasesImpl: About to create shortcuts for atom.exe, rootAppDir C:\Users\gizmecano\AppData\Local\atom\..\atom
ApplyReleasesImpl: Creating shortcut for atom.exe => C:\Users\gizmecano\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\Atom.lnk
ApplyReleasesImpl: About to save shortcut: C:\Users\gizmecano\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\Atom.lnk (target C:\Users\gizmecano\AppData\Local\atom\update.exe, workingDir C:\Users\gizmecano\AppData\Local\atom\..\atom\app-1.0.0, args --processStart atom.exe)
ApplyReleasesImpl: Creating shortcut for atom.exe => C:\Users\gizmecano\desktop\Atom.lnk
ApplyReleasesImpl: About to save shortcut: C:\Users\gizmecano\desktop\Atom.lnk (target C:\Users\gizmecano\AppData\Local\atom\update.exe, workingDir C:\Users\gizmecano\AppData\Local\atom\..\atom\app-1.0.0, args --processStart atom.exe)
```

**Comment by BrainCrumbz** [comment] 2015-10-20 22:44
To project collaborators: some time ago we created PR #8793 just to better express intent in desktop shortcut tests. At that time they still passed, both before (of course) and after refactoring, even if there were already issues by users on this *strange* behaviour.

**Comment by rugk** [comment] 2015-11-02 22:39
Reappeared again while updating to v1.1.0.

**Comment by GizMecano** [comment] 2015-11-03 07:45
Indeed, the shortcut is created again. On the other hand, the reference to this creation is still present in the `log`, cf. [line 4](https://gist.github.com/GizMecano/a4b06e1b576a20671443/dcee78e25aaa1bde157106ac5f21be25b11b00fb#file-squirrelsetup-log-L4) or [line 6](https://gist.github.com/GizMecano/a4b06e1b576a20671443/dcee78e25aaa1bde157106ac5f21be25b11b00fb#file-squirrelsetup-log-L6). So no real surprise.

**Comment by mjohnsonengr** [comment] 2015-11-18 02:38
Shortcut has re-appeared the past few updates for me.
On another note, as @GizMecano mentioned, the shortcut in AppData\Roaming\Microsoft\Windows\Start Menu\Programs\ gets replaced, breaking my taskbar pinned icon and start menu pinned icon.
Further, I have selected that certain files be opened with Atom by default by selecting AppData\Local\atom\bin\atom.cmd.  This linkage breaks on each update.

**Comment by pbraga** [comment] 2015-11-25 10:56
As Marcus predicted new (1.2.4) update also breaks taskbar shortcut and
recreates desktop shortcut.

**Comment by paulcbetts** [comment] 2015-11-25 16:38
The pinning icon is a known issue that we're going to fix soon

**Comment by BrainCrumbz** [comment] 2015-12-01 18:18
Maybe it can help:

some time ago we suggested a refactoring (PR #8793) just to better express the test intent when testing desktop shortcut. At that time tests passed (before and after refactoring as well), even if users were already notifying issues on this strange behaviour.
Having clearer tests might help to understand what is really going wrong.

**Comment by giacomocerquone** [comment] 2016-03-07 08:22
Here! Updated today to 1.5.4 and desktop shortcut was recreated after the update.
I also experienced another problem in the past (I see here actually that they're common problems) with the icon on the taskbar.

**Comment by Schweinepriester** [comment] 2016-04-06 12:04
Pretty annoying, please fix.

I'd be willing to provide logs or help debug this.

**Comment by jaoord** [comment] 2016-04-06 12:29
Why doesn't the installer ask us if we would like a shortcut on the desktop, instead of assuming that Atom is so important that the whole world wants to have a shortcut on the desktop?

**Comment by BrandonDusseau** [comment] 2016-04-06 13:41
@jaoord That isn't really relevant to this issue, as updates do not occur via the installer.

**Comment by rugk** [comment] 2016-04-06 17:29
> That isn't really relevant to this issue, as updates do not occur via the installer.

Then why does the updater even have to add a shortcut at all? Just disable it...
When I install Atom I may add a shortcut to my desktop, but if I want it it obviously stays there until I uninstall Atom, so there is no need to add the shortcut every time (again) when updating.

**Comment by 50Wliu** [comment] 2016-04-07 19:35
@rugk The installer will never have a UI, so it defaults to creating shortcuts.  As previously stated, however, the intention is for the auto-updater (which does use the same framework as the installer) not to recreate the shortcut if it was deleted.

**Comment by Schweinepriester** [comment] 2016-04-07 19:46
> The installer will never have a UI, so it defaults to creating shortcuts.

lol, quite invasive.

_yes i saw the disclaimer_

**Comment by damieng** [comment] 2016-04-13 17:41
Believed to be fixed in 1.7 with the latest Squirrel. Please re-open if you see this when the auto-updater brings you to 1.7 release.

**Comment by BrandonDusseau** [comment] 2016-04-15 04:45
Upgrading from 1.7.0 to 1.7.1 made the icon reappear. This is my first upgrade since a new installation of Atom (and Windows), however, so I'm unsure if that's expected behavior. I will comment again if the icon reappears with 1.7.2.

**Comment by pbraga** [comment] 2016-04-15 09:15
I also have the icon reappear every update, now 1.7.1, even thought i have
been just upgrading atom since 1.5.

**Comment by damieng** [comment] 2016-04-15 16:37
Looks like this is still a problem so more work needs to be done figuring out why Squirrel is getting confused. Should we raise a bug on Squirrel @paulcbetts ?

**Comment by BrandonDusseau** [comment] 2016-04-20 03:58
I was able to reproduce the issue on 1.7.2 as well. I'm sure given the prior comment that's fairly clear already but I'd rather be slightly too verbose than too silent.

**Comment by giacomocerquone** [comment] 2016-04-21 09:08
Updating to 1.7.2 didn't cause any issue to me.

**Comment by oportsac** [comment] 2016-12-08 17:18
We're using the windows machine-wide installer in an environment where we delete user profiles every night. The shortcut reappears for users shortly after logging in. Is there any way to disable that in the msi installer?

**Comment by damieng** [comment] 2016-12-08 17:29
@oportsac Are you referring to the msi?  If so that just puts the regular installer on the machine and sets it up to autorun for all users that sign in.

A true shared install of Atom is not available as it would interfere with the update process.

**Comment by oportsac** [comment] 2016-12-08 17:35
I see. In that case could I copy the atom beta files over manually and create a shortcut for all users? We'd like to disable auto-updating if possible unless the program can do it silently without user interaction.

**Comment by damieng** [comment] 2016-12-08 17:38
It sounds like you would be better off extracting atom-windows.zip where
you want it to be - it won't appear in programs/auto update/add shortcuts
etc.

**Comment by oportsac** [comment] 2016-12-08 17:39
Exactly what I mean. Thanks!

**Comment by 50Wliu** [comment] 2017-01-30 16:47
The last occurrence of this issue was in April.  Since then, we've updated Squirrel, so it seems safe to close this issue.

**Comment by BrandonDusseau** [comment] 2017-01-31 02:44
The shortcut was last created for me just five days ago, upon updating to 1.13.1.

**Comment by BrandonDusseau** [comment] 2017-02-11 20:09
Tested on my other computer, and upgrading to 1.13.1 did not recreate the icon. The only potentially related difference between the two machines (that I can think of) is the Desktop is in the default location on the unaffected machine, and is located at F:\Brandon\Desktop on the affected machine. %appdata% is in the same location on both machines.

**Comment by BrandonDusseau** [comment] 2017-02-15 02:53
Affects 1.14.1 -> 1.14.2

**Comment by conoro** [comment] 2017-02-28 08:25
1. Launch Atom
2. Desktop icon created
3. Delete icon
4. Icon re-created some time later
5. Shutdown Atom
6. Delete icon
7. Go to 1

Every version, beta or non-beta, for many months. Currently 1.15.0-beta0. Windows 10.

**Closed** 2017-06-15 15:45 UTC
Labels: auto-updater, bug, installer, windows

**Comment by BrandonDusseau** [comment] 2017-08-08 22:58
Upgrade from 1.18.0 -> 1.19.0 recreated the icon.

**Comment by rugk** [comment] 2017-08-09 13:19
Never ending story… 🙄

**Comment by BrandonDusseau** [comment] 2017-10-03 22:39
1.20.0 -> 1.21.0 did NOT create the icon, so confirmed fixed on my end. Thanks!

**Comment by furicle** [comment] 2018-01-12 14:14
I'm still getting this behaviour
