### ISSUE TITLE
ATOM erases PATH Variable when installing on Win7

### ISSUE THREAD

**Issue by SpectreJan** [atom/atom#7757] opened 2015-07-07 13:53 UTC
When I installed ATOM 1.0.0 and one of the previous versions on Windows7 using the Windows installer it erased the user PATH Variable instead of appending it to the existing PATH variable, which is kind of annoying. Sorry I forgot which was the version I installed before, but that behaviour is still present in 1.0.0.
Not sure if this behaviour is intended, I sincerely hope not!

Cheers,
Jan

**Comment by SpectreJan** [comment] 2015-07-07 13:55
With appending it to the PATH variable I meant appending it's own bin directory to PATH. Sorry for the bad phrasing.

Cheers,
Jan

**Comment by 50Wliu** [comment] 2015-07-07 17:00
Refs #5092
/cc @kevinsawicki

**Comment by batjko** [comment] 2015-07-07 18:39
It sure isn't intended behavior, but it didn't happen for me on Win7 or Win8.
Have you tried completely uninstalling Atom and re-installing it from scratch, see if it does it again?

**Comment by SpectreJan** [comment] 2015-07-08 06:28
I did that,
It still shows the same behaviour. I also had a look at the Issue 50Wliu linked (thanks), and it seems that it is the same problem.

**Comment by thomasjo** [comment] 2015-07-08 06:59
@SpectreJan So running `reg query HKCU\Environment /v Path` fails just like it does for others in the referenced issue (#5092)?

**Comment by SpectreJan** [comment] 2015-07-08 07:53
@thomasjo Yes it fails.

**Comment by thomasjo** [comment] 2015-07-08 07:57
@SpectreJan Can you show us the error message? I'm guessing it's in German? If so, then that's the problem since @kevinsawicki's quick fix only works if the error message is in English unfortunately.

**Comment by SpectreJan** [comment] 2015-07-08 08:10
@thomasjo  No problem
 `C:\Users\krae_jn>reg query HKCU\Environment /v Path`
`FEHLER: Die Registrierungsbearbeitung wurde vom Administrator deaktiviert.`

**Comment by thomasjo** [comment] 2015-07-08 08:23
As I expected then. @kevinsawicki looks like the old fix needs to be revisited (somehow). Perhaps we can always fiddle with `Path` on Windows in a safe way?

**Comment by batjko** [comment] 2015-07-08 08:44
What both the German and English error messages have in common is the words 'error' and 'administrator'.
That may be true for a bunch of other languages, though surely not for all.
But it could be a quick adjustment to the existing fix.

**Comment by Stanzilla** [comment] 2015-08-09 06:48
Sounds like Atom tried to edit the system PATH variable instead of the user PATH variable?

**Comment by benogle** [comment] 2016-03-03 23:28
@damieng is this fixed?

**Comment by damieng** [comment] 2016-03-04 00:17
This is indeed fixed, it looks like I missed closing down this bug with the other ones.

**Closed by damieng** 2016-03-04 00:17 UTC
Labels: bug, installer, windows
