### ISSUE TITLE
Find-file (cmd-p) in gargantuan repo experiences significant slowness

### ISSUE THREAD

**Issue by alex** [atom/atom#14275] opened 2017-04-21 12:47 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using atom with a gargantuan repo (in my case, all of Firefox: https://hg.mozilla.org/mozilla-central), the fine-file dialog (cmd-p) experiences significant performance problems. It is generally not able to keep up with the speed at which I type, leading to confusion.

When I say doesn't keep up with the speed at which I type, I don't mean it can't search that fast, I mean that rendering the keys I'm typing is delayed, often for many seconds.

### Steps to Reproduce

1. Be in a _massive_ repo
2. cmd-p
3. Start typing (for example in mozilla-central: SandboxPolicies)

**Expected behavior:** The letters I type are rendered instantly, even if the search can't be completed instantly

**Actual behavior:** The UI jerks around, the letters I type take multiple seconds to appear on the screen

**Reproduces how often:** Nearly always

### Versions

```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

macOS 10.12.4

**Comment by alex** [comment] 2017-04-21 13:22
[atom-vid.zip](https://github.com/atom/atom/files/947145/atom-vid.zip)

This is a video demonstrating this problem (sorry it's in a `.zip`, github doesn't allow uploading `.mov` files).

Here's a description of what you see:

* `cmd-p`
* Immediately type "sandboxpolicies"
* It basically hangs for a while, you can see that the cursor is not flashing during this time
* After many seconds, it completes the search and returns to responsiveness (a flashing cursor)
* I wait until it finishes reindexing the project
* `cmd-p`
* Immediate type "sandboxpolicies"
* Same behavior

**Comment by rsese** [comment] 2017-04-21 17:53
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/88. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-21 17:53 UTC
