### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by mary-celine** [atom/atom#22663] opened 2021-06-27 05:34 UTC
Issue - Getting an error while downloading the Atom 1.57.0
Error Message displayed - This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:23853ea7-e01e-003c-450b-6b0ba2000000 Time:2021-06-27T04:19:25.8717535Z</Message>
</Error>
Steps to Reproduce
1) Google Search - Download Atom
2) Click on Download button
3) error message is displayed

**Comment by UziTech** [comment] 2021-06-27 05:54
duplicate of #22650

**Comment by abioz-aiz** [comment] 2021-06-27 07:38
I am currently facing the same issue
![Screenshot 2021-06-27 130705](https://user-images.githubusercontent.com/73377489/123536579-be953a00-d748-11eb-8cf9-e62b550bad13.png)

**Comment by aayushchugh** [comment] 2021-06-27 07:52
@abioz-aiz Download from here https://github.com/atom/atom/releases/tag/v1.57.0

**Comment by darangi** [comment] 2021-06-28 08:07
Thanks for reporting 🙇🏾‍♂️ 

it has been resolved, you can now download from https://atom.io

**Closed by darangi** 2021-06-28 08:07 UTC
