### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'G:/'

### ISSUE THREAD

**Issue by EmiLithium** [atom/atom#17796] opened 2018-08-07 14:10 UTC
### Steps to reproduce

1. Open Atom, either directly or from GitHub Desktop through "Open in Atom".
2. See red error popup as soon as Atom loads! This error pops up immediately upon starting Atom, with no other steps.
![enoent](https://user-images.githubusercontent.com/41804177/43781246-7e5a05be-9a2a-11e8-992e-15241fa6e741.PNG)

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'G:\'

```
At fs.js:1700

Error: ENOENT: no such file or directory, lstat 'G:\'
    at Proxy.realpathSync (fs.js:1700:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:320:29)
    at atom.project.getPaths.map (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:73)
    at Array.map (<anonymous>)
    at Object.startTask (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:56)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/fuzzy-finder/lib/main.js:129:43)
    at get_process.nextTick (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/fuzzy-finder/lib/main.js:31:45)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by steveward** [comment] 2018-08-07 15:14
Thanks for contributing!

We noticed that this looks like a duplicate of #10774 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by steveward** 2018-08-07 15:14 UTC

**Comment by EmiLithium** [comment] 2018-08-07 15:22
Are you sure? I didn't move the app while it was open. The error gets thrown as soon as I open Atom, and Atom hasn't been moved.

**Comment by rsese** [comment] 2018-08-09 22:07
Ahhh yeah :+1:  Based on the stack trace, I think it might be https://github.com/atom/fuzzy-finder/issues/255.

**Comment by steveward** [comment] 2018-08-10 01:49
Sorry about that @EmiLithium!
