### ISSUE TITLE
"editor has crashed"

### ISSUE THREAD

**Issue by karneaud** [atom/atom#13228] opened 2016-11-15 11:05 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom keeps crashing on start whether from the laugh app or from command line. Runs in --safe mode but without packages.

### Steps to Reproduce

1. Download latest atom
2. open

**Expected behavior:** 

To be able to use the editor

**Actual behavior:** 

"Editor has crashed" with dialog to keep it open reload or close window

### Versions

Atom    : 1.12.2
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.8.2

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by davidak** [comment] 2016-11-15 12:03
I have the same problem since updated from `1.11.2.64bit+1.11.2.32bit-1~webupd8~0` to `1.12.1-1~webupd8~0` (using [WEBUPD8 PPA](http://ppa.webupd8.org/post/152996598191/atom-1120-available-in-ppa)).

### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Logs

```
davidak@unibook:~$ atom -f
[26131:1115/124354:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Gtk-Message: Failed to load module "pantheon-filechooser-module"
[26131:1115/124354:ERROR:browser_main_loop.cc(283)] Gtk: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,
[26131:1115/124354:ERROR:browser_main_loop.cc(283)] Gtk: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,
[26131:1115/124354:ERROR:browser_main_loop.cc(283)] Gtk: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,
[26131:1115/124354:ERROR:browser_main_loop.cc(283)] Gtk: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,
```

strace -f atom

https://gist.github.com/davidak/8ca5720035fac032cc69829d0252da72

### Versions

Atom    : 1.12.1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

---

[elementary OS](https://elementary.io/) 0.4 Loki (based on Ubuntu 16.04)
running on a MacBook Pro Retina from 2009

**Comment by Ben3eeE** [comment] 2016-11-15 12:45
Can you try to start Atom using `atom --clear-window-state` to see if that solves the problem?

**Comment by davidak** [comment] 2016-11-15 13:47
@Ben3eeE I already installed the old version to continue working.

i had 7 tabs in 1 window open, so nothing special.

To test it, i updated again. I started like this but got the crash message again.

```
davidak@unibook:~$ atom --clear-window-state -f
[7089:1115/144053:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Gtk-Message: Failed to load module "pantheon-filechooser-module"
[7089:1115/144053:ERROR:browser_main_loop.cc(283)] Gtk: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,
[7089:1115/144053:ERROR:browser_main_loop.cc(283)] Gtk: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,
[7089:1115/144053:ERROR:browser_main_loop.cc(283)] Gtk: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,
[7089:1115/144053:ERROR:browser_main_loop.cc(283)] Gtk: Im Modulpfad »pixmap« konnte keine Themen-Engine gefunden werden,
```

**Comment by 50Wliu** [comment] 2016-11-15 16:00
As @karneaud's issue cannot be reproduced in safe mode, that means one of your installed packages is causing the issue.

@davidak 1.12.3 will be released soon - once that is available, can you please try to see if it still crashes in safe mode?  If so, please open a new issue.  Thanks!

**Closed by 50Wliu** 2016-11-15 16:00 UTC

**Comment by karneaud** [comment] 2016-11-16 00:39
Well i had to trash my .atom folder. What hurts the most is it was working fine until i updated it and this started happening on the day I'm suppose to present trying to fix a last minute change and it really delayed it....smh but atlas its working again
