### ISSUE TITLE
Search in directory: search in file with Windows-1251 (cyrillic) encoding

### ISSUE THREAD

**Issue by st1gus** [atom/atom#13838] opened 2017-02-17 09:01 UTC
### Description

When you try to search for a latin substring in the list of **files containing latin and cyrillic characters and saved in windows-1251 encoding**, the search engine does not return any result.

### Steps to Reproduce

1. Create file with containing text:
`some text with кирилическими символами`
2. Save file with windows-1251 encoding in some directory
3. Try to search in this directory substring `some text with` no opening file on new page.

**Expected behavior:** returns a list of files containing the searched substring

**Actual behavior:** the search engine does not return any result

**Reproduces how often:** always

### Versions

OS: Windows 10
Atom: 1.14.2

**Comment by rsese** [comment] 2017-02-26 02:48
I think I was able to reproduce but to clarify:

> 2. Save file with windows-1251 encoding in some directory

Can you confirm how you perform this step?

**Comment by ousennin** [comment] 2017-02-28 14:16
Yes, the bug is present. It is caused by [bug in node module 'scandal'](https://github.com/atom/scandal/issues/26). It simply opens files for search in wrong codepage or even worse - as a binary...

**Comment by st1gus** [comment] 2017-03-03 06:16
to @rsese 
> Can you confirm how you perform this step?

Sure, you can do this in Atom, just open new file, select encoding `windows-1251` (on the bottom of Atom panel), insert into file content `some text with кирилическими символами`, save them in some folder. Now you can try `Search in direcory` phrase 'some text'.

**Comment by Ben3eeE** [comment] 2017-03-03 08:25
@rsese I found three issues related to `find-and-replace` not working with various encodings. https://github.com/atom/find-and-replace/issues/741 and https://github.com/atom/find-and-replace/issues/751 that can be duplicates for this and https://github.com/atom/find-and-replace/issues/819 that is possibly related.

**Comment by rsese** [comment] 2017-03-03 21:17
Thanks for the pointers @Ben3eeE :zap:   Not sure why I didn't search the find-and-replace package....those do seem like basically the same issue.

We'll go ahead and close this as a duplicate @st1gus but you can subscribe to any of those issues above if you want to follow along.

**Closed by rsese** 2017-03-03 21:17 UTC
