### ISSUE TITLE
Hangs UI when opening large file

### ISSUE THREAD

**Issue by Jishaxe** [atom/atom#10800] opened 2016-02-12 23:12 UTC
When opening a large (say, a binary) file, the UI hangs while it is being read.

**Comment by miftahafina** [comment] 2016-02-13 07:41
me too

**Comment by mnquintana** [comment] 2016-02-13 07:44
This sounds like a duplicate of either https://github.com/atom/atom/issues/8864 or #979 – feel free to subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) for a guide on reporting bugs, including searching for duplicates first.

**Closed by mnquintana** 2016-02-13 07:44 UTC
