### ISSUE TITLE
Repeating File->Open can open many Finder windows

### ISSUE THREAD

**Issue by sfrankian** [atom/atom#19616] opened 2019-06-30 15:40 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Repeating File->Open followed by a click back to the editor allows you to open multiple Finder windows.

### Steps to Reproduce

1. Click File->Open to open a Finder window.
2. Click on the editor window to focus back on it.
3. Repeat steps 1 and 2 again. There will now be 2 Finder windows open in the background.

**Expected behavior:**
I should only be able to open one Finder window at a time. Also, clicking away from the open Finder window should not cause it to disappear into the background.

**Actual behavior:**
I am able to have more than one Finder window open at a time. Clicking away from an open Finder window causes it to disappear into the background.

**Reproduces how often:**
Always.

### Versions
MacOS 10.14.5

`atom --version`
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

`apm --version`
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 2.7.13
git 2.13.0

### Additional Information
![atom_issue](https://user-images.githubusercontent.com/8781591/60398846-f0a83d00-9b2a-11e9-91ea-b8f3bb46a543.png)

**Comment by rsese** [comment] 2019-07-01 16:52
Thanks for the report - reproduced on macOS 10.12.6 with 1.40.0-nightly19.

**Comment by lee-dohm** [comment] 2019-07-03 15:30
Thanks for the report!

Upon investigation of this issue, we found that other macOS applications (including official apps, such as Pages) do not allow multiple Finder windows to be opened. On the other hand, we found that they _do_ allow the Finder windows to go to the background, in other words, they are not modal windows.

While the maintainer team isn't going to work on fixing this issue, we would be open to a well-written pull request to fix the problem of the multiple Finder windows being opened. Any pull request should still allow the Finder windows to go to the background, however. Because of this, I'm going to mark this issue as `help-wanted` and close the issue.

Thanks again for the detailed and well-written report!

**Closed by lee-dohm** 2019-07-03 15:30 UTC
Labels: help-wanted, mac, triaged
