### ISSUE TITLE
Fail to uninstall packages

### ISSUE THREAD

**Issue by moongod101** [atom/atom#12122] opened 2016-07-08 14:14 UTC
First try the GIU system to uninstall the package,it fail,then second using the CLI,enter `apm uninstall PACKAGE`,the come with a error message said `Failed to delete PACKAGE: Does not exist`

Atom infos:
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by lee-dohm** [comment] 2016-07-12 20:53
Duplicate of https://github.com/atom/atom/issues/11464. This is fixed in v1.9.0-beta.

**Closed by lee-dohm** 2016-07-12 20:53 UTC
