### ISSUE TITLE
Atom will be closed ?

### ISSUE THREAD

**Issue by gavnoe** [atom/atom#17465] opened 2018-06-04 18:29 UTC
Atom will be closed after Microsoft buy Github ? Anyone have information about that ?

**Comment by lee-dohm** [comment] 2018-06-04 18:30
Thanks for your concern.

Atom remains key to GitHub. Our product roadmap is set, and the team will continue all of their work.

-----

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17460. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2018-06-04 18:30 UTC
