### ISSUE TITLE
Backslash (\) and At (@) characters do not work in editor

### ISSUE THREAD

**Issue by stefan-baumann** [atom/atom#5688] opened 2015-02-23 10:23 UTC
When using the Editor on Windows 8.1, I'm not able to write backslashes and at-signs. Every other application works just fine.
I'm using a german (QUERTZ) keyboard, so the key combinations are `Alt Gr + Q` for `@` and `Alt Gr + ß` for `\`. Interestingly I am still able to write them with the Alt + Numpad combinations (`Alt + 6 + 4` for `@` and `Alt + 9 + 2` for `\`).

**Comment by batjko** [comment] 2015-02-23 11:44
Yea this is a known issue with some international keyboard layouts, related to the `Alt-Gr` key.

'Fraid this is a dupe of [this issue](https://github.com/atom/atom-keymap/issues/35). Follow that one for updates...

**Closed** 2015-02-23 12:48 UTC

**Comment by GiovanniAdvent** [comment] 2016-05-24 21:25
Yea dude but i wrote Alt Gr + Q , Alt Gr + ß for \ like you said  and it doesn´t work !! what other idea could work ? D:
