### ISSUE TITLE
Open Folder instead opens Chrome Inspector

### ISSUE THREAD

**Issue by theflyingnerd** [atom/atom#12331] opened 2016-08-05 02:28 UTC
### Description

When using the Open Folder feature, upon selecting a folder, the Chrome Inspector is opened instead. This is also affecting the Project Manager plugin, which ultimately uses folders.

### Steps to Reproduce

1. File -> Open Folder
2. Select a folder and choose "Select Folder"
3. Inspector is opened.

Expected at step 3: Atom is opened in the selected folder context.

### Versions
Atom    : 1.9.3
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by mnquintana** [comment] 2016-08-05 02:30
Sorry to hear you're running into this! This is a duplicate of https://github.com/atom/atom/issues/12328 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-08-05 02:30 UTC
