### ISSUE TITLE
copy/paste not working and atom crash sometimes on paste

### ISSUE THREAD

**Issue by lazychino** [atom/atom#6283] opened 2015-04-07 15:11 UTC
Not sure if the problems go together, but I cant copy from atom and paste somewhere else (ex: firefox). Also atom crashed sometime when pasting from other place to atom and this is the screen that appears 
![screenshot from 2015-04-06 16 19 38](https://cloud.githubusercontent.com/assets/976310/7026246/9d4036b2-dd16-11e4-8363-1d9b8dae1f6d.png)

I'm on ubuntu 14.04, Atom 0.189.0

**Comment by izuzak** [comment] 2015-04-07 15:12
This looks very similar to #6221 which makes me think it's a duplicate of that issue. That issue should be fixed in the next release of Atom (probably out later today), but please let us know if you can still reproduce this in 0.190.0 once it's released! Thanks for all the reports.

**Closed by izuzak** 2015-04-07 15:12 UTC

**Comment by lazychino** [comment] 2015-04-07 16:18
:+1:
