### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by GOGO98901** [atom/atom#6616] opened 2015-05-02 20:51 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\gogo9_000\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:42.4.0 editor:newline (atom-text-editor.editor)
     -0:38.3.0 core:paste (atom-text-editor.editor)
  5x -0:35.5.0 core:backspace (atom-text-editor.editor)
     -0:29.6.0 core:save (atom-text-editor.editor)
     -0:27.8.0 core:backspace (atom-text-editor.editor)
     -0:27.2.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "web-view"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {},
    "softWrapAtPreferredLineLength": true,
    "softTabs": false,
    "scrollPastEnd": true,
    "tabLength": 3,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.7.0
file-icons, v1.5.4
linter-javac, v0.1.3
minimap, v4.8.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
project-manager, v1.15.5
seti-ui, v0.6.3
web-browser, v1.4.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-02 21:14
Duplicate of atom/tree-view#399, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-02 21:14 UTC
