### ISSUE TITLE
Can no display Chinese in Tree View and Editor

### ISSUE THREAD

**Issue by gotnix** [atom/atom#6384] opened 2015-04-15 07:04 UTC
atom-0.191.0-0.1.fc21 on openSUSE 20150227 "Tumbleweed", no apm. 
atom display Chinese character as box like ☐, both the tree view and editor.

**Comment by mnquintana** [comment] 2015-04-15 10:24
Duplicate of #6214

**Closed by mnquintana** 2015-04-15 10:24 UTC
