### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 66Error: Cannot call...

### ISSUE THREAD

**Issue by ejaramillom** [atom/atom#19719] opened 2019-07-29 15:11 UTC
[Enter steps to reproduce:]

1. copy - paste a division of cards to change image source. a total of 5 cards. two additional documents were open at the time,to help copy paste process; one with the original content and one with the content replaced
2. pasted the last card in the index.html, then included a col-md-6 class in the first division. pressed ctrl+s and the error poped up

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 66
Error: Cannot call function 'getPosition' on missing remote object 66
    at throwRPCError (C:\Users\ejara\AppData\Local\atom\app-1.39.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\ejara\AppData\Local\atom\app-1.39.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\ejara\AppData\Local\atom\app-1.39.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At C:\Users\ejara\AppData\Local\atom\app-1.39.1\resources\electron.asar\renderer\api\remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 66
Error: Cannot call function 'getPosition' on missing remote object 66
    at throwRPCError (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:1:730051)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:1:730466)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:284967)
```

### Commands

```
     -2:44.2.0 core:copy (input.hidden-input)
     -2:40.8.0 core:paste (input.hidden-input)
     -2:36.4.0 core:copy (input.hidden-input)
     -2:33.3.0 core:paste (input.hidden-input)
     -2:26.3.0 core:save (input.hidden-input)
     -2:24.1.0 core:copy (input.hidden-input)
     -2:22.1.0 core:paste (input.hidden-input)
     -2:20.9.0 core:save (input.hidden-input)
     -0:53.7.0 core:backspace (input.hidden-input)
  8x -0:49.4.0 core:select-left (input.hidden-input)
     -0:47.5.0 core:copy (input.hidden-input)
     -0:47.2.0 core:move-right (input.hidden-input)
     -0:46.4.0 core:paste (input.hidden-input)
  2x -0:45.9.0 core:move-left (input.hidden-input)
  2x -0:45.2.0 core:backspace (input.hidden-input)
     -0:42.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2019-07-30 00:32
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

About your steps to reproduce, can you reproduce consistently or did it happen just one time?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-07-30 00:32 UTC

**Comment by ejaramillom** [comment] 2019-07-30 00:37
Hello robert!

It only happened once; although it really didn't compromise any file or code line.

Cheers.
________________________________
