### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by miggiegarciadev** [atom/atom#22186] opened 2021-04-13 21:15 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At electron/js2c/asar.js:138

Error: Module did not self-register.
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Users/miggiegarcia/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:1:697035)
    at get_KeyboardLayoutManager (/Users/miggiegarcia/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2798543)
    at get_manager (/Users/miggiegarcia/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2798645)
    at Object.getCurrentKeyboardLayout (/Users/miggiegarcia/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2798771)
    at e.keystrokeForKeyboardEvent (/Users/miggiegarcia/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:1058046)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/miggiegarcia/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1228079)
    at KeymapManager.handleKeyboardEvent (/Users/miggiegarcia/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1226064)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/miggiegarcia/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:284879)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-live-server 2.3.0 
atom-live-server-plus 3.0.1 
atom-runner 2.7.1 
autosave-onchange 1.5.1 
define-jump 1.0.1 
emmet 2.4.3 
goto-definition 1.3.4 
goto-mathematica 0.3.1 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
```

**Comment by sadick254** [comment] 2021-04-14 16:28
@miggiegarciadev Have you tried updating atom to the latest version?

**Comment by ThatXliner** [comment] 2021-04-23 20:11
Can we get this pinned? There's a lot of duplicates and I think pinning this may help...

**Comment by icecream17** [comment] 2021-04-24 15:15
This is probably what happened with https://github.com/atom/atom/pull/22159

**Comment by sadick254** [comment] 2021-04-27 19:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2021-04-27 19:13 UTC
