### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1252Error: Cannot ca...

### ISSUE THREAD

**Issue by AbdelhakAj** [atom/atom#16657] opened 2018-01-31 14:39 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1252
Error: Cannot call function 'getPosition' on missing remote object 1252
    at throwRPCError (C:\Users\abdelhak.ajbouni\AppData\Local\atom\app-1.23.3\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\abdelhak.ajbouni\AppData\Local\atom\app-1.23.3\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\abdelhak.ajbouni\AppData\Local\atom\app-1.23.3\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At C:\Users\abdelhak.ajbouni\AppData\Local\atom\app-1.23.3\resources\electron.asar\renderer\api\remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 1252
Error: Cannot call function 'getPosition' on missing remote object 1252
    at throwRPCError (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:691:34)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:725:42)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.23.3/resources/app/src/window-event-handler.js:189:32)
```

### Commands

```
     -6:04.6.0 find-and-replace:show (input.hidden-input)
     -6:04.2.0 core:paste (input.hidden-input)
  2x -5:59.5.0 editor:newline (input.hidden-input)
     -5:47.2.0 core:move-down (input.hidden-input)
     -5:46.9.0 autocomplete-plus:confirm (input.hidden-input)
     -5:46.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -5:40.3.0 core:copy (input.hidden-input)
     -5:34.9.0 editor:newline (input.hidden-input)
     -5:34.6.0 core:paste (input.hidden-input)
     -5:31.6.0 core:backspace (input.hidden-input)
     -5:20.1.0 editor:newline (input.hidden-input)
     -5:19.8.0 core:paste (input.hidden-input)
     -5:17.3.0 core:backspace (input.hidden-input)
     -5:03.9.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
autosave-onchange 1.5.1 
css-spy 0.6.0 
double-tag 1.1.0 
emmet 2.4.3 
file-icons 2.1.16 
highlight-selected 0.13.1 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
screen-recorder 1.5.0 
```

**Comment by rsese** [comment] 2018-02-01 18:14
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.  If you remember what you were doing at the time of the error or if you have steps to reproduce the error, feel free to let us know in https://github.com/atom/atom/issues/16630.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-02-01 18:14 UTC
