### ISSUE TITLE
Uncaught Error: spawn /Users/Brett/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Content...

### ISSUE THREAD

**Issue by BlackRoseAngel** [atom/atom#11038] opened 2016-03-03 00:52 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/Brett/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/Brett/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/Brett/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/Brett/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/Brett/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/Brett/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/Brett/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/Brett/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/Brett/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/Brett/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/Brett/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at /Users/Brett/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:869:41
    at EventEmitter.<anonymous> (/Users/Brett/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
  8x -3:08.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:02.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:01.8.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:55 editor:newline (atom-text-editor.editor.is-focused)
     -2:27.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:27.4.0 core:select-up (atom-text-editor.editor.is-focused)
  2x -2:26.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:24.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -2:24.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:19.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:03.3.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -2:01.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:00.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:59.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:41.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.5.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-03-03 01:15
This is a duplicate of #10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-03 01:15 UTC
