### ISSUE TITLE
Cannot click and drag anything

### ISSUE THREAD

**Issue by jdfreder** [atom/atom#6991] opened 2015-05-28 18:01 UTC
Hi,  I recently opened an issue here atom/tabs#148 , claiming I couldn't drag tabs around to rearrange them, but realized it's a more general problem.  I can't left-click and drag ANYTHING in Atom.  I can't even left mouse down and drag to highlight text.  It's as if the mouse up event is firing when it shouldn't.

I'm using a fresh install of 
Atom 0.204.0
on Linux Mint 17 Qiana (based on Ubuntu 14.04, Trusty Tahr)

Thanks!

**Comment by jdfreder** [comment] 2015-05-28 18:04
I can't even highlight text in the dev console, so I had to take a screenshot of the error:

![capture](https://cloud.githubusercontent.com/assets/3292874/7867176/424eff78-0529-11e5-99fb-59aa567e747c.PNG)

**Comment by mnquintana** [comment] 2015-05-28 18:15
I can't reproduce this with Atom 0.204.0 on OS X 10.10.3 – can you reproduce this in safe mode? (`atom --safe`)

**Comment by jdfreder** [comment] 2015-05-28 19:10
A quick test in safe mode, I don't see the memory leak, yet.  But I still can't highlight text or drag tabs.  Could it be related to other things installed on my machine, i.e. my version of Chrome?

**Comment by jdfreder** [comment] 2015-05-28 19:12
What other information can I gather for you?  Is there a test suite I can run?

**Comment by mnquintana** [comment] 2015-05-28 19:15
Are you running your OS in a VM by any chance?

**Comment by jdfreder** [comment] 2015-05-28 19:19
Yes, I am - VBox

**Comment by mnquintana** [comment] 2015-05-28 19:24
Thanks! I think this is a duplicate of https://github.com/atom/atom/issues/6243, so I'm going to close this in favor of that issue. This should be fixed when Atom upgrades to a version of Electron built on Chromium 43.

**Closed by mnquintana** 2015-05-28 19:24 UTC
Labels: more-information-needed

**Comment by jdfreder** [comment] 2015-05-28 19:28
Thanks!  Sorry for the noise!  I looked and couldn't find that issue, otherwise I wouldn't have opened this one.

**Comment by Godje** [comment] 2016-04-26 23:45
I cannot move my tabs around, but i am working with updated Atom and with default theme, on my Windows without any Virtual Machines. Everything was working until recently (like 2 weeks ago, i tried to solve it by myself)
