### ISSUE TITLE
Atom close/crash if i drag/move a firefox tab over it

### ISSUE THREAD

**Issue by Fank** [atom/atom#5547] opened 2015-02-13 16:06 UTC
Tested with Firefox last stable & developer edition (Aurora).
If i open a new tab or one with content, and i drag it away (to open a new window), and move the cursor over Atom it closes.

Here the shell output:
```bash
mfkinder@wk-boe001:~$ atom
mfkinder@wk-boe001:~$ [14953:0213/170206:ERROR:browser_main_loop.cc(164)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[14983:0213/170206:INFO:renderer_main.cc(211)] Renderer process started
App load time: 314ms
[14953:0213/170208:INFO:CONSOLE(11)] "activate linter-jshint", source: /home/mfkinder/.atom/packages/linter-jshint/lib/init.coffee (11)
[14953:0213/170208:INFO:CONSOLE(79)] "Window load time: 1688ms", source: file:///usr/share/atom/resources/app/static/index.js (79)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 495 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Here tested with "--safe"
```bash
mfkinder@wk-boe001:~$ atom --safe
mfkinder@wk-boe001:~$ [14753:0213/170133:ERROR:browser_main_loop.cc(164)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[14783:0213/170133:INFO:renderer_main.cc(211)] Renderer process started
App load time: 303ms
[14753:0213/170135:INFO:CONSOLE(79)] "Window load time: 1552ms", source: file:///usr/share/atom/resources/app/static/index.js (79)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 448 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

OS: Ubuntu 14.10 x64
Plugins installed:
mfkinder@wk-boe001:~$ apm list
Built-in Atom packages (84)
├── archive-view@0.47.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.47.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.41.0
├── autocomplete@0.44.0
├── autoflow@0.22.0
├── autosave@0.20.0
├── background-tips@0.22.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.71.0
├── command-palette@0.34.0
├── deprecation-cop@0.36.0
├── dev-live-reload@0.41.0
├── encoding-selector@0.18.0
├── exception-reporting@0.21.0
├── find-and-replace@0.156.0
├── fuzzy-finder@0.65.0
├── git-diff@0.51.0
├── go-to-line@0.30.0
├── grammar-selector@0.45.0
├── image-view@0.49.0
├── incompatible-packages@0.22.0
├── keybinding-resolver@0.27.0
├── language-c@0.38.0
├── language-clojure@0.12.0
├── language-coffee-script@0.39.0
├── language-csharp@0.5.0
├── language-css@0.28.0
├── language-gfm@0.63.0
├── language-git@0.10.0
├── language-go@0.21.0
├── language-html@0.29.0
├── language-hyperlink@0.12.2
├── language-java@0.14.0
├── language-javascript@0.56.0
├── language-json@0.12.0
├── language-less@0.24.0
├── language-make@0.13.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.10.0
├── language-php@0.20.0
├── language-property-list@0.8.0
├── language-python@0.32.0
├── language-ruby@0.48.0
├── language-ruby-on-rails@0.18.0
├── language-sass@0.34.0
├── language-shellscript@0.12.0
├── language-source@0.9.0
├── language-sql@0.14.0
├── language-text@0.6.0
├── language-todo@0.16.0
├── language-toml@0.15.0
├── language-xml@0.28.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.134.0
├── metrics@0.42.0
├── notifications@0.27.0
├── one-dark-syntax@0.3.0
├── one-dark-ui@0.4.0
├── one-light-syntax@0.3.0
├── one-light-ui@0.3.0
├── open-on-github@0.32.0
├── package-generator@0.37.0
├── release-notes@0.48.0
├── settings-view@0.178.0
├── snippets@0.72.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.54.0
├── status-bar@0.59.0
├── styleguide@0.44.0
├── symbols-view@0.82.0
├── tabs@0.65.0
├── timecop@0.29.0
├── tree-view@0.154.0
├── update-package-dependencies@0.8.0
├── welcome@0.21.0
├── whitespace@0.28.0
└── wrap-guide@0.31.0

/home/mfkinder/.atom/packages (11)
├── atom-auto-uglify@0.4.0
├── autocomplete-paths@1.0.2
├── autocomplete-plus@2.1.6
├── git-blame@0.4.0
├── git-log@0.2.0
├── git-tab-status@1.5.3
├── language-mason@2.0.0
├── linter@0.11.1
├── linter-jshint@0.1.0
├── seti-ui@0.6.3
└── tabs-to-spaces@0.8.1

**Comment by Fank** [comment] 2015-02-13 16:08
Im using Atom 0.179.0

**Comment by 50Wliu** [comment] 2015-02-13 16:10
Duplicate of #3593.

**Comment by Fank** [comment] 2015-02-13 16:11
Sry didn't searched it before

**Closed by 50Wliu** 2015-02-13 16:10 UTC
