### ISSUE TITLE
How to open miltiple github projects as tabs?

### ISSUE THREAD

**Issue by hugeme** [atom/atom#15333] opened 2017-08-16 08:31 UTC
Atom: 1.19.1 x64
Electron: 1.6.9
OS: Mac OS X 10.12.6
Thrown From: Atom Core

After the update to Atom: 1.19.1 one of the coolest features disappeared, opening multiple github projects in different tabs with toggled full screen (using ctrl alt o.) 
Now, each project gets its own window. I know, I can open projects with (ctrl shift alt o) in order to keep projects in the same windows keeping them within the same tree view. However, working on multiple projects simultaneously was a very convenient way. 
May I ask for some clarification on that. Is that going to be added in near future again?

**Comment by rsese** [comment] 2017-08-16 17:59
Thanks for taking the time to contribute!

You're talking about macOS native tabs yes?  If so,  this is a duplicate of https://github.com/atom/atom/issues/15202 and you can subscribe there for updates if you'd like (see my comment here /cc https://github.com/atom/atom/issues/15202#issuecomment-321318542).

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-16 17:59 UTC
