### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by guyskk** [atom/atom#13156] opened 2016-11-07 03:52 UTC
This occurs after I reload window(`ctrl+alt+r`), when I press `ctrl+c` or `ctrl+v` atom will popup this error messgae. I had disabled all community packages. 

`Create issue on atom/atom` failed because:
```
414 Request-URI Too Large

nginx
```

`Copy error report to clicpboard` also not work, I can't copy anything in atom to my clicpboard.

![selection_007](https://cloud.githubusercontent.com/assets/6367792/20045981/69c56578-a49d-11e6-889e-9376dbc184e0.png)
![selection_008](https://cloud.githubusercontent.com/assets/6367792/20045984/73d95d62-a49d-11e6-9c2b-2c73baeb1391.png)

-----------

TypeError: Cannot read property 'objec...&body=[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 1.4.5
**System**: linux 4.8.6-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/lib/electron/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:315:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:871

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/lib/electron/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:315:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217:13)
    at Clipboard.write (/usr/lib/atom/src/clipboard.js:70:34)
    at Selection.module.exports.Selection.copy (/usr/lib/atom/src/selection.js:748:31)
    at Selection.module.exports.Selection.cut (/usr/lib/atom/src/selection.js:708:12)
    at /usr/lib/atom/src/text-editor.js:2904:21
    at /usr/lib/atom/src/text-editor.js:1102:29
    at TextBuffer.module.exports.TextBuffer.transact (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/lib/atom/src/text-editor.js:1519:26)
    at /usr/lib/atom/src/text-editor.js:1096:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/lib/atom/src/text-editor.js:2493:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/lib/atom/src/text-editor.js:2459:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/lib/atom/src/text-editor.js:1094:19)
    at TextEditor.module.exports.TextEditor.cutSelectedText (/usr/lib/atom/src/text-editor.js:2901:19)
    at TextEditor.core:cut (/usr/lib/atom/src/register-default-commands.js:426:21)
    at /usr/lib/atom/src/register-default-commands.js:661:34
    at TextBuffer.module.exports.TextBuffer.transact (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/lib/atom/src/text-editor.js:1519:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/usr/lib/atom/src/register-default-commands.js:660:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:260:29)
    at /usr/lib/atom/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/usr/lib/atom/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:37 core:cut (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.dockerfile": [
        "dockerfile"
      ]
    },
    "disabledPackages": [
      "spell-check",
      "symbols-tree-view",
      "vim-mode",
      "linter-eslint",
      "advanced-open-file",
      "atom-jinja2",
      "emmet",
      "highlight-selected",
      "language-docker",
      "language-restructuredtext",
      "language-typescript-grammars-only",
      "language-vue",
      "linter",
      "linter-flake8",
      "linter-jshint",
      "linter-less",
      "minimap",
      "pigments",
      "project-plus",
      "react",
      "toggle-quotes",
      "atom-beautify"
    ],
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited"
  },
  "editor": {
    "autoIndentOnPaste": false,
    "showIndentGuide": true,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-jinja2, v0.5.0 (inactive)
emmet, v2.4.3 (inactive)
highlight-selected, v0.11.2 (inactive)
language-docker, v1.1.7 (inactive)
language-restructuredtext, v1.0.1 (inactive)
language-typescript-grammars-only, v1.5.0 (inactive)
language-vue, v0.20.0 (inactive)
linter, v1.11.18 (inactive)
linter-eslint, v8.0.0 (inactive)
linter-flake8, v2.0.2 (inactive)
linter-jshint, v3.0.1 (inactive)
linter-less, v2.6.0 (inactive)
minimap, v4.25.6 (inactive)
pigments, v0.37.0 (inactive)
project-plus, v0.9.0 (inactive)
react, v0.16.1 (inactive)
symbols-tree-view, v0.13.2 (inactive)
toggle-quotes, v1.0.0 (inactive)
vim-mode, v0.65.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2016-11-07 06:23
You are running an [unofficial build of Atom](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md). Open this issue in the arch linux bugtracker for packages.

414 is a duplicate of https://github.com/atom/notifications/issues/129.

**Closed by Ben3eeE** 2016-11-07 06:23 UTC
