### ISSUE TITLE
Release Notes not showing anything past 1.1.0

### ISSUE THREAD

**Issue by ericcirone** [atom/atom#10023] opened 2015-12-11 18:07 UTC
It looks like the release call is getting back the right JSON, but the page won't show anything past 1.1.0 and the button restart and install is active.

This has happened for a while. running Atom 1.3.1

**Comment by mnquintana** [comment] 2015-12-11 19:05
This is a duplicate of https://github.com/atom/release-notes/issues/39 – feel free to subscribe there for updates.

**Closed by mnquintana** 2015-12-11 19:05 UTC
