### ISSUE TITLE
Requesting Official PPA

### ISSUE THREAD

**Issue by steelbrain** [atom/atom#5052] opened 2015-01-14 12:55 UTC
I have [Webupd8][1] has a PPA [here][2]. But it doesn't get very frequently updated. It'd be great to have a PPA by the atom folks themselves, so when the publish a new release on GitHub, they can push it to the PPA as well.

[1]:http://www.webupd8.org/
[2]:https://launchpad.net/~webupd8team/+archive/ubuntu/atom

**Comment by 50Wliu** [comment] 2015-01-14 13:47
Duplicate of #3717 and #2956.

**Closed by 50Wliu** 2015-01-14 13:47 UTC
