### ISSUE TITLE
Unable to delete files / folders in atom tree view in Windows 7

### ISSUE THREAD

**Issue by h2oboi89** [atom/atom#11163] opened 2016-03-14 18:27 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)? (1.5.4)
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Unable to delete files / folders in atom tree view in Windows 7

### Steps to Reproduce

1. Right click file / folder
2. Select `Delete` option
3. Select `Move to Trash`

**Expected behavior:** File / folder to be deleted

**Actual behavior:** Nothing

### Versions
1.5.4

**Comment by h2oboi89** [comment] 2016-03-14 18:28
My company has some rather annoying security software installed, so if no one else can reproduce this, I am ready to declare that at fault instead of Atom.

**Comment by 50Wliu** [comment] 2016-03-14 19:27
This is a duplicate of atom/tree-view#666 and will be fixed in Atom 1.7.0.  Sorry for how long this bug has been present in Atom :(.

**Closed by 50Wliu** 2016-03-14 19:27 UTC

**Comment by h2oboi89** [comment] 2016-03-16 22:09
Works @ home, so most likely an issue with the "security" software we have at work.
