### ISSUE TITLE
Atom crashes when trying to open an extremely large file (>2GB in this case)

### ISSUE THREAD

**Issue by crener** [atom/atom#11600] opened 2016-04-25 16:50 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom crashes after opening extremely large files (>2GB in my case).

### Steps to Reproduce

1. Open extremely large file with atom
2. press proceed on warning
3. watch as atom crashes

**Expected behavior:** 

Atom opens file and shows text

**Actual behavior:** 

Atom attempts to open file and crashes almost immediately 

### Versions
1.7.2

**Comment by Zireael07** [comment] 2016-04-26 08:40
Atom can't handle files bigger than a couple of MBs, and you're trying to open a file several GBs large? Shoo!

**Comment by tylercrompton** [comment] 2016-04-26 12:35
I don't see how that makes this any less of an issue. Some text editors are capable of this.

**Comment by djaiss** [comment] 2016-04-26 13:38
I would argue that Atom is primarily used by developers to write code. A very large file of code is at best several MBs. A file larger that this is probably a log. Any text editor will have difficulty to open very large, multiple GBs logs - unless you use Vim or Emacs. A good rule of thumb would be to use tools that are better suited for specific tasks.

**Comment by tylercrompton** [comment] 2016-04-26 13:45
I have a client who occasionally sends me database dumps, the last of which was roughly roughly seven or eight Gigabytes, if I remember correctly. I needed to open the dump, and Atom proved useless in that regard. But honestly, opening up a file that even of a couple of Megabytes isn't as uncommon as you'd think. Most people who I know use Atom are aware that it can't handle large files. Personally, I feel that that alone is an indicator that some improvements in this regard would be beneficial and much appreciated by the community. I'm not suggesting that it should open up any file of any size. But there is definitely room for some optimizations.

**Comment by jimmycallin** [comment] 2016-04-27 07:28
I keep sublime text around mainly for two reasons: its startup window time (which makes it useful for editing where you want to quickly open and close windows, e.g. writing commit messages), and editing large files (~50MB files are rarely a problem for sublime). While the short term goal definitely should be to be able to open ~5MB files without problems, being able to open multi-gigabyte files is definitely a viable long-term goal.

**Comment by lee-dohm** [comment] 2016-04-27 22:29
This is a duplicate of https://github.com/atom/atom/issues/11554. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-04-27 22:29 UTC

**Comment by msj121** [comment] 2017-01-19 03:04
I routinely have to sometimes work on a large file if for example I am editing library files quickly to test before suggesting updates on github etc...

@jimmycallin Wow, sublime text works like a champ.
