### ISSUE TITLE
Menus not working in plasma 5.9 with global menu enabled

### ISSUE THREAD

**Issue by rgawenda** [atom/atom#13885] opened 2017-02-27 09:11 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using global menu from JDE Plasma 5.9, atom menu shows, but doesn't work. Clicking any submenu doesn't show any submenu

### Steps to Reproduce

1. Enable kde plasma global menu in symtensettings5 -> Application Style -> Widget Style -> Fine Tuning tab -> Menubar style -> Application Menu widget -> Add a menubar Panel to desktop
2. Start atom
3. Try to use the desktop menu

**Expected behavior:** [What you expect to happen]

Clicking on a menu entry should show it's submenu dropdown.

**Actual behavior:** [What actually happens]

Nothing happens

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.15.0-beta3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.13
git 2.10.2

Kubuntu (Ubuntu 17.04) Ubuntu Zesty Zapus (development branch)

### Additional Information

Setting the Global Menu (settings) style to: "Use single button for application menu", second level submenus are shown, but they're not functional. Third level submenu (as Packages) are not shown.

**Comment by rsese** [comment] 2017-02-27 18:43
Hmmm, not sure but does this sound related to https://github.com/electron/electron/issues/8455?  And possibly a dupe of https://github.com/atom/atom/issues/6255?

**Comment by 50Wliu** [comment] 2017-02-27 21:42
Definitely caused by electron/electron#8455, not sure about being a duplicate of #6255 though.

**Comment by rgawenda** [comment] 2017-03-01 08:34
I don't see any CPU overuse here, but after reading the comments from that electron's issue it seems you're right.
I'm sorry for failing in my search-fu here. Thanks.

**Comment by michaldybczak** [comment] 2017-03-22 00:28
I checked it and I have the same issue with Atom. There are also other apps that have this problem too (like: messenger for desktop).

**Comment by acerspyro** [comment] 2017-05-05 17:36
I have experienced this bug with both Atom and Discord, and have noticed that if you spam the menu buttons, eventually the menu will appear, but quickly close.
If you time it right, you can keep the menu open and browse through it, but subsections don't open.

**Comment by ChALkeR** [comment] 2017-07-12 10:04
@acerspyro The actual issue is that electron is constantly spamming over dbus and sending lots of `layout-updated` events, repopulating the menu each time even when there were no changes.

**Comment by gasinvein** [comment] 2017-08-10 13:24
This is fixed in electron/electron#10070. Can you backport this fix or update bundled electron?

**Comment by 50Wliu** [comment] 2017-08-10 14:15
@gasinvein we're going to wait until a stable version of Electron is released that contains the fix before updating.  Both 1.6.10+ and 1.7.x are in beta right now.

**Comment by gasinvein** [comment] 2017-08-10 15:21
@50Wliu so maybe this issue should stay opened until the update is released?

**Closed** 2017-10-03 17:44 UTC
Labels: electron, linux

**Comment by ungb** [comment] 2017-10-11 17:13
I'm attempting to test this out but I don't see the issue as describe above on atom 1.21.0 and 1.15.0

see gif on 1.21.0(same as behavior as 1.15.0):
![before](https://user-images.githubusercontent.com/5624870/31454880-cd99739a-ae6b-11e7-8d4f-cedc16f3e421.gif)

After Electron upgrade 1.6.14 I see the same thing but some things on the menu kind of work, but not most things.
![after](https://user-images.githubusercontent.com/5624870/31455477-7df6c512-ae6c-11e7-80c4-adfc216c051d.gif)


I'm running kubuntu 17.04:

![image](https://user-images.githubusercontent.com/5624870/31455530-b454d9a0-ae6c-11e7-8567-aff3d3a1e161.png)

@rgawenda unsure if I'm missing a step?

**Comment by gasinvein** [comment] 2017-10-11 17:38
@ungb You are using menu widget in single-button mode. For me this bug appears if a panel with menu*bar* is present.

**Comment by ungb** [comment] 2017-10-11 17:40
@gasinvein like this? 
![image](https://user-images.githubusercontent.com/5624870/31457108-a18fd6b8-ae70-11e7-9ba7-a9f75990160f.png)

**Comment by gasinvein** [comment] 2017-10-11 17:44
@ungb Nope. Place application menu widget on a pannel, like this:
![screenshot_20171011_204351](https://user-images.githubusercontent.com/4569691/31457259-ece67b72-aec4-11e7-8246-49b730ddcf94.png)

**Comment by ungb** [comment] 2017-10-11 17:52
@gasinvein I think I can confirm this is fixed in master which we plan to hotfix soon.

Before 1.15.0:
![before](https://user-images.githubusercontent.com/5624870/31457507-d672d0b4-ae71-11e7-9f53-08ba182b395c.gif)

After (off master):
![after](https://user-images.githubusercontent.com/5624870/31457629-2e347df2-ae72-11e7-99ae-80c2a7a1d873.gif)

**Comment by rgawenda** [comment] 2017-10-13 07:34
Working nicely for me with release 1.22.0-beta1 :+1:
