### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/xxx/Library/Application Support...

### ISSUE THREAD

**Issue by nsatija** [atom/atom#9695] opened 2015-11-19 11:34 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.2
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/xxx/Library/Application Support/com.github.atom.ShipIt/update.NqIyN1I'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/xxx/Library/Application Support/com.github.atom.ShipIt/update.NqIyN1I'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/Nick/Library/Application Support/com.github.atom.ShipIt/update.NqIyN1I/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
     -0:25.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:02.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-19 17:41
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-19 17:41 UTC

**Comment by nsatija** [comment] 2015-11-19 18:16
ok thanks
—
Schedule a quick chat
https://calendly.com/fed/30min <https://calendly.com/fed/30min> 

Thanks 
Nick S
856-425-0007
