### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ LPC.docx'

### ISSUE THREAD

**Issue by bill-brown** [atom/atom#19787] opened 2019-08-14 19:40 UTC
[Enter steps to reproduce:]

1. put a comma in the file name. for example the file name is 'abc Mui, LPC.docx'
2. attempt to move it in the UI from one folder in a project to a sub folder or another folder.

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ LPC.docx'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat '/ LPC.docx'
    at Proxy.realpathSync (fs.js:1744:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:335:40)
    at TreeView.moveEntry (/Users/billbrown/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:14:1009292)
    at TreeView.onDrop (/Users/billbrown/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:14:1016221)
    at HTMLDivElement.<anonymous> (/Users/billbrown/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:14:989852)
```

### Commands

```
  8x -2:39.7.0 core:save (input.hidden-input)
  7x -2:07.1.0 core:backspace (input.hidden-input)
  2x -1:59.7.0 core:paste (input.hidden-input)
  2x -1:30.2.0 core:backspace (input.hidden-input)
  2x -1:28.8.0 core:move-right (input.hidden-input)
  8x -1:27 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-cform-yaml 0.5.1-0 
compare-files 0.8.1 
git-plus 8.7.1 
php-twig 4.0.0 
platformio-ide-terminal 2.9.4 
pretty-json 2.1.2 
save-session 0.15.7 
structure-view 0.2.1 
xml-formatter 0.13.0 
```

**Comment by rsese** [comment] 2019-08-14 20:09
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-14 20:09 UTC
