### ISSUE TITLE
Something wrong in atom 0.194.0.

### ISSUE THREAD

**Issue by CCCzKen** [atom/atom#6531] opened 2015-04-27 09:48 UTC
When I run 0.194.0 have a period time , I found that the computer will turn very slow . One time my mechina almost can't move, after a few minutes raise the error like this.

**Comment by CCCzKen** [comment] 2015-04-27 09:50
[5539:0427/171705:ERROR:browser_main_loop.cc(216)] Gdk: gdk_window_set_user_time called on non-toplevel

[5539:0427/171705:ERROR:browser_main_loop.cc(216)] Gdk: gdk_window_set_user_time called on non-toplevel

[5539:0427/171807:ERROR:browser_main_loop.cc(216)] Gdk: gdk_window_set_user_time called on non-toplevel

[5539:0427/171909:ERROR:browser_main_loop.cc(216)] Gdk: gdk_window_set_user_time called on non-toplevel

The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 62207 error_code 3 request_code 25 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by KeitIG** [comment] 2015-04-27 09:57
I get sometimes some huge memory leaks and total laptop freeze for a few minutes, but I didn't know if it was due to Chrome, Atom, or when they were both opened at the same time.

**Comment by lee-dohm** [comment] 2015-04-27 14:51
Is this potentially related to #6496?

**Comment by lee-dohm** [comment] 2015-04-27 14:52
Also, @CCCzKen can you let us know what OS this is on?

**Comment by KeitIG** [comment] 2015-04-27 14:52
I can confirm this just now. I'm using an Ubuntu 14.04 derivative. Closing Electron/Atom/Chrome "fixes" this

**Comment by CCCzKen** [comment] 2015-04-28 01:39
@lee-dohm I work on Ubuntu 14.10 .

**Comment by 50Wliu** [comment] 2016-07-24 20:32
@CCCzKen @KeitIG can you still reproduce this on Atom 1.8.0?

**Comment by KeitIG** [comment] 2016-07-24 22:55
@50Wliu Nope.

**Comment by mnquintana** [comment] 2016-07-24 23:12
Gonna close this out – @CCCzKen @KeitIG feel free to comment if you run into this again on the latest version of Atom!

**Closed by mnquintana** 2016-07-24 23:12 UTC
Labels: linux, more-information-needed
