### ISSUE TITLE
When open the editor for large files its keeps hanging! But in sublime it works!

### ISSUE THREAD

**Issue by raghunath1616** [atom/atom#10045] opened 2015-12-14 05:08 UTC
When I try to open large files it is hanging and I can't able to type a single in the editor. But the same when I open in sublime its working. Please fix it!

**Comment by mnquintana** [comment] 2015-12-14 06:26
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/8864 and/or #979 – feel free to subscribe there for updates.

**Closed by mnquintana** 2015-12-14 06:26 UTC
