### ISSUE TITLE
Fold doesn't work with soft wrap

### ISSUE THREAD

**Issue by freemanoid** [atom/atom#7288] opened 2015-06-15 18:50 UTC
I have soft wrap enabled and there's a block which is wrapped to the next line. When I fold it soft wrap stops working.
![fold_wrap_bug](https://cloud.githubusercontent.com/assets/180154/8167645/4aaa7750-13a8-11e5-9776-0539649309fd.gif)

**Comment by mnquintana** [comment] 2015-06-15 18:53
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/5740 – please subscribe there for updates.

**Comment by izuzak** [comment] 2015-06-15 18:53
I think this is a duplicate of #5740

**Closed by mnquintana** 2015-06-15 18:53 UTC
