### ISSUE TITLE
@toggleLineCommentsInSelection: Place the cursor within an empty comment

### ISSUE THREAD

**Issue by adunning** [atom/atom#7983] opened 2015-07-20 11:18 UTC
When invoking editor:toggle-line-comments on an empty line, Atom correctly inserts an empty comment, but places the cursor at the end of the inserted string. For HTML-style comments, could this be adjusted to place the cursor in the centre of the inserted `<!--  -->`? (This is the behaviour of Sublime Text, TextMate, and every XML editor I have used.)

**Comment by mnquintana** [comment] 2015-07-20 11:52
Thanks for the report! This is a duplicate of https://github.com/atom/language-html/issues/65 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-20 11:52 UTC
