### ISSUE TITLE
'atom' CLI command produces second temporary Atom icon in dock if Atom is already open

### ISSUE THREAD

**Issue by cthielen** [atom/atom#6039] opened 2015-03-19 18:07 UTC
Very minor issue but if Atom is already open and one uses the 'atom' command in the Terminal to open a new file the Dock temporarily experiences two Atom icons before returning to the proper one.

In an ideal world, we'd never see this second icon.

**Comment by 50Wliu** [comment] 2015-03-19 19:24
Duplicate of #2964, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-19 19:24 UTC
