### ISSUE TITLE
After closing atom , project window  is emptied

### ISSUE THREAD

**Issue by galiedon** [atom/atom#17480] opened 2018-06-06 18:32 UTC
### Description

project window has many folders.
After I close the all documents, I close the atom **by cmd+w not cmd+q**.
I reopen atom , but the project window *is emptied*.
But it is OK when I reopen atom After I close atom **by cmd+q not cmd+w**.

I don't know its a bug or feature, I just feel uncomfortable because I usually quit atom **by cmd+w**.

### Steps to Reproduce

1.  open atom
2. add project folder
3. close all documents and close atom **by cmd+w**
4. reopen atom

### Versions
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

System :macOS

**Comment by rsese** [comment] 2018-06-06 19:00
Thanks for contributing!

We noticed that this is a duplicate of issues like https://github.com/atom/atom/issues/15336 - this is [expected behavior](https://github.com/atom/atom/issues/13895#issuecomment-283726843) if you close all windows with `cmd-w` on macOS.  If you want the project windows you had opened to re-open, you need to quit Atom completely with `cmd-q` like you found.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-06-06 19:00 UTC

**Comment by galiedon** [comment] 2018-06-07 04:20
Thank you , and I'm sorry that I don't noticed the issues like #15336 - this is expected behavior
