### ISSUE TITLE
Conflicting with Chrome 

### ISSUE THREAD

**Issue by smiffy6969** [atom/atom#6279] opened 2015-04-07 07:33 UTC
Hiya,

Since I updated to 189, I have this really strange bug with chrome. Whenever I run chrome and atom together, I loose the ability to cut and paste in chrome, in fact right click menu doesn't always work in chrome either.

This has only happened since I upgraded atom to 189 and only when I run the two together (I notice chrome version in atom was updated in 189).

I have had to go back to using ST2 since this shows it's face at the worst moments, timing is random but it always happens at least once a day requiring a re start, or complete kill of chrome and all processes.

I am running Ubuntu Gnome 64bit, chrome Version 41.0.2272.118 (64-bit) and atom 189. Problem happens at least once a day and completely screws chrome browser. I have ran ST2 for a few days now and am no longer getting the issue so atom is definitely causing this since i updated to 189.

ta

Paul

**Comment by YuriSolovyov** [comment] 2015-04-07 07:53
fixed in https://github.com/atom/atom/commit/a6d47d403fc68ef9e0c29635a5427dff4d5ecfe9

**Comment by smiffy6969** [comment] 2015-04-07 07:56
awesome... glad I was not imagining it!

**Comment by izuzak** [comment] 2015-04-07 08:03
Duplicate of https://github.com/atom/atom/issues/6221

**Closed by izuzak** 2015-04-07 08:03 UTC
