### ISSUE TITLE
context menu stops editor responding

### ISSUE THREAD

**Issue by UziTech** [atom/atom#11926] opened 2016-06-07 19:47 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Leaving a context menu open for 30 seconds triggers an "Editor is not responding" dialog

### Steps to Reproduce

1. Right click anywhere to bring up the context menu
2. Wait for about 30 seconds

**Expected behavior:** Nothing

**Actual behavior:** An "Editor is not responding" dialog box pops up

### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.8.3.windows.1
visual studio 2013

Windows 10 Pro Insider Preview 
build 14352.rs1-release.160522-1930

**Comment by Ben3eeE** [comment] 2016-06-07 20:01
Duplicate of https://github.com/atom/atom/issues/11901

**Closed** 2016-06-07 20:36 UTC
