### ISSUE TITLE
Bring to Front

### ISSUE THREAD

**Issue by Sharpiro** [atom/atom#6614] opened 2015-05-02 17:38 UTC
When Atom is restored but hidden behind several windows.  "Open with Atom" right click function should send it to the front.

**Comment by lee-dohm** [comment] 2015-05-02 17:40
Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?

**Comment by lee-dohm** [comment] 2015-05-02 17:41
I could not reproduce this using Atom v0.197.0-f8047ba on Mac OS X 10.10.3.

**Comment by Sharpiro** [comment] 2015-05-02 17:47
Atom Version: 0.196.0
System: Windows 8.1 Enterprise
Notes:  Had this issue about 15 days ago on a different version.  Updated today, still having the same issue.  Same issue in VS Code.  The icons in the taskbar blink and light up showing that they have new information to display, but remain in the background.

**Comment by 50Wliu** [comment] 2015-05-02 18:18
Refs #6201 (Linux version of this bug).

**Comment by izuzak** [comment] 2015-05-04 13:27
Happens for me as well on Windows 8.1

**Comment by christophfroehlich** [comment] 2015-05-05 11:53
the same on Windows 7 with atom during the last month, at the moment with version 0.196.0

**Comment by varunagrawal** [comment] 2015-05-19 18:01
I can pick this up. Need some help though identifying where the issue might be.

**Comment by christophfroehlich** [comment] 2015-05-20 09:06
how can we help?

**Comment by quarion** [comment] 2015-06-26 11:56
Happens to me on Windows 7 x64 with Atom v1.0.0

**Comment by Nom4d3** [comment] 2015-07-07 19:14
It's also happening on Windows 10 x64 with Atom v1.0.0.
I even tried to disabled the tree-view package to see if it was something to do with it but I have no success.

**Comment by iongion** [comment] 2015-08-06 07:26
Same thing happening on Windows 8.1 x64 - Atom v1.0.3

**Comment by zessin** [comment] 2015-08-10 19:45
Same problem here.
Atom v1.0.5
Windows 7 Pro x64

**Comment by ixiom** [comment] 2015-08-12 12:57
Same problem for me as well.
Atom v1.0.4
Windows 7 Pro x64

**Comment by vorou** [comment] 2015-09-05 10:04
Still happens.

Atom 1.0.11
Windows 10 Pro N

**Comment by 50Wliu** [comment] 2015-10-17 23:49
Closing in favor of #6201 which I've just updated to also include Windows.

**Closed by 50Wliu** 2015-10-17 23:49 UTC
Labels: bug, windows
