### ISSUE TITLE
Uncaught Error: spawn /Users/erdem/Desktop/downloads/Atom.app/Contents/Frameworks/Atom Helper.app...

### ISSUE THREAD

**Issue by laphilosophia** [atom/atom#11005] opened 2016-02-29 14:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/erdem/Desktop/downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/erdem/Desktop/downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:15:15)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:170:22)
    at /Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.setPaths (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/project.js:217:27)
    at /Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:184:27
    at Function.module.exports.Emitter.simpleDispatch (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.setPath (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:342:27)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1048:12)
    at TextEditor.module.exports.TextEditor.saveAs (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:636:26)
    at Pane.module.exports.Pane.saveItemAs (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:569:16)
    at Pane.module.exports.Pane.saveItem (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:553:21)
    at Pane.module.exports.Pane.saveActiveItem (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Users/erdem/Desktop/downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:25.9.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21.4.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:21.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:20.8.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:19.6.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:18.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "dev-live-reload"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "scrollPastEnd": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-02-29 20:27
This is a duplicate of #10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-29 20:27 UTC
