### ISSUE TITLE
Can't write @ character

### ISSUE THREAD

**Issue by MrLinDowsMac** [atom/atom#8031] opened 2015-07-22 18:45 UTC
I have Windows 8. I was trying to write a single @ character using the ALT GR - Q keys. At beginning I though was a problem of my keyboard configuration, so I tried by using the onscreen keyboard tactile, and typing the @ character directly, but it doesn't render it anyway.

**Comment by mnquintana** [comment] 2015-07-22 18:50
I think this is a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-22 18:50 UTC
