### ISSUE TITLE
Git Tab - Open preview of diff in same tab

### ISSUE THREAD

**Issue by royteusink** [atom/atom#15658] opened 2017-09-15 12:14 UTC
**The problem:**
At this time, if you have a lot of changes across many files and you want to preview the changes, every diff opens in a separate tab which leads to a lot of open tabs.

**My feature request:**
Option to open all git diffs in one and the same tab.

[ ] Put configuration option in module.
[ ] Open diff view in same tab by default.
[ ] Ctrl + Click opens diff in separate tab.

**Comment by royteusink** [comment] 2017-09-15 14:16
https://github.com/atom/github/issues/1175

**Comment by thomasjo** [comment] 2017-09-15 14:44
Closing as duplicate of https://github.com/atom/github/issues/1175.

**Closed by thomasjo** 2017-09-15 14:44 UTC
