### ISSUE TITLE
Can't click or drag to select text when theme is using atom-text-editor

### ISSUE THREAD

**Issue by jcgallaher** [atom/atom#5132] opened 2015-01-18 00:45 UTC
When theme is using atom-text-editor instead of the .editor class I can't click or drag to select any text. When I change back to the "soon to be depreciated" .editor class and reload Atom, I can select text again like normal.

**Comment by lee-dohm** [comment] 2015-01-18 02:07
I can't reproduce this issue on Atom v0.175.0-60970d6 on Mac OS X 10.10.1

I'm currently using the latest version of the [atom-dark-ui theme](https://github.com/atom/atom-dark-ui). It uses the `atom-text-editor` selector and I have no problem selecting text. If you're talking about a syntax theme, I'm also using the updated selectors in my own [advanced-railscasts-syntax theme](https://atom.io/packages/advanced-railscasts-syntax) (though you don't use `atom-text-editor` in a syntax theme) and everything is working fine.

Can you be more specific about exactly how you are using the `atom-text-editor` selector?

**Comment by jcgallaher** [comment] 2015-01-18 02:22
Hi lee-dohm,

If I change a theme from the old code, for example:

```
.editor {
  background-color: @syntax-background-color;
  color: @syntax-text-color;
}
```
to the new code version
```
atom-text-editor {
  background-color: @syntax-background-color;
  color: @syntax-text-color;
}
```
I can no longer highlight the text. I'm using Windows 8.1, so maybe it's an issue in windows or I'm getting the code wrong.

**Comment by lee-dohm** [comment] 2015-01-18 02:25
According to your comment here:

https://discuss.atom.io/t/use-the-atom-text-editor-tag-instead-of-the-editor-class/14286/7?u=leedohm

You are working on a *syntax* theme. The `atom-text-editor` selector is not appropriate for that use. See my post there for more information.

**Comment by jcgallaher** [comment] 2015-01-18 02:38
Hi lee-dohm, I replied back there, but I'll briefly explain here. I added :host to the following code example ```.editor, :host {...``` and that fixes one of the error messages, but I still get the "Use the `atom-text-editor` tag instead of the `editor` class." for the theme in Deprecation Cop.

**Comment by lee-dohm** [comment] 2015-01-18 02:41
Ok, since this issue is fixed, I'll close this here and we can continue working on the issue on Discuss.

**Closed by lee-dohm** 2015-01-18 02:41 UTC
Labels: more-information-needed

**Comment by jcgallaher** [comment] 2015-01-18 02:55
Thanks! :-)
