### ISSUE TITLE
Uncaught SyntaxError: Expected "-" or end of input but "/" found.

### ISSUE THREAD

**Issue by sedrickcz** [atom/atom#4485] opened 2014-12-09 22:02 UTC
Uncaught SyntaxError: Expected "-" or end of input but "/" found.

**Atom Version**: 0.153.0
**System**: linux 3.13.0-40-generic
**Thrown From**: Atom Core

**Comment by kevinsawicki** [comment] 2015-07-06 20:54
Closing this out, this is going to be incredibly hard to reproduce since it is a really old version, no longer being experienced, and missing a stack trace.

**Closed by kevinsawicki** 2015-07-06 20:54 UTC
Labels: more-information-needed, uncaught-exception
