### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by lcir** [atom/atom#5140] opened 2015-01-18 21:54 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:355

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:355:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:332:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:286:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:485:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:412:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
     -0:00.0 application:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete"
    ]
  },
  "editor": {
    "fontSize": 12,
    "softWrap": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
autoclose-html, v0.13.0
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
dart-tools, v0.8.5
editorconfig, v0.3.0
html-id-class-snippets, v1.4.1
jsformat, v0.7.18
language-clojure, v0.10.0
language-dart, v0.1.1
linter-clojure, v0.0.4
minimap, v3.5.6
react, v0.8.8
recent-files, v0.3.0
remote-edit, v1.6.3
terminal-status, v1.3.5

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2015-01-18 23:28
Duplicate of atom/atom#4421 and atom/atom#307.

**Closed by lee-dohm** 2015-01-18 23:28 UTC
