### ISSUE TITLE
Text file associated with Atom, it's file icon is an empty white rectangle, which causes by Windows register error

### ISSUE THREAD

**Issue by laudukang** [atom/atom#13077] opened 2016-10-26 17:12 UTC
Atom Version : Windows 10, 1.11.2

Problem:
Associated all text file(like .java/.txt) with atom, but on Windows, these file icons are  an empty white rectangle, seems like unknown file type.

Reason:
I have found the reason caused the problem in Windows register,
`HKEY_CLASSES_ROOT\Applications\atom.exe\DefaultIcon `
After install , the term value refers to 
`"C:\Users\Admin\AppData\Local\atom\app-1.11.2\resources\cli\file.ico"`
but actually, file.ico file is not exited in this path, 

Solution:
as I modified as 
`C:\Users\Admin\AppData\Local\atom\app.ico`,  it works.

**Comment by Ben3eeE** [comment] 2016-10-26 17:53
This is a duplicate of https://github.com/atom/atom/issues/12974 and will be fixed in Atom 1.12

**Closed by Ben3eeE** 2016-10-26 17:53 UTC
