### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by madhead** [atom/atom#12045] opened 2016-06-25 13:57 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Manjaro Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as getPosition] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:626:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:660:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app.asar/src/window-event-handler.js:182:35)
    at /usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
  2x -2:18 editor:delete-line (atom-text-editor.editor.is-focused)
     -2:17.6.0 core:save (atom-text-editor.editor.is-focused)
  3x -2:17.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:16.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:16.1.0 core:close (atom-text-editor.editor.is-focused)
  7x -2:08.7.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -2:06.8.0 editor:delete-line (atom-text-editor.editor.is-focused)
  3x -2:06.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:26.2.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:37.2.0 tree-view:duplicate (span.name.icon.icon-file-directory)
     -0:33.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:32.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.8.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:11.7.0 tree-view:remove (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.multi-select)
     -0:07.3.0 core:move-down (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
  3x -0:05.6.0 tree-view:remove (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
```

### Config

```json
{
  "core": {
    "themes": [
      "lavender-ui",
      "lavender-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.8
autocomplete-go, v1.1.0
builder-go, v1.0.0
environment, v1.2.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
language-ini, v1.16.0
language-nginx, v0.6.1
lavender-syntax, v0.0.2
lavender-ui, v0.0.2
linter, v1.11.14
navigator-godef, v1.0.3
symbol-gen, v1.3.1
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-06-25 15:58
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-25 15:58 UTC
