### ISSUE TITLE
Error: kill EPERM

### ISSUE THREAD

**Issue by 921034403** [atom/atom#15619] opened 2017-09-12 07:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:160

Error: kill EPERM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.kill (internal/child_process.js:392:26)
    at Task.module.exports.Task.terminate (~/AppData/Local/atom/app-1.19.7/resources/app/src/task.js:148:31)
    at GitRepository.module.exports.GitRepository.refreshStatus (~/AppData/Local/atom/app-1.19.7/resources/app/src/git-repository.js:391:20)
    at ~/AppData/Local/atom/app-1.19.7/resources/app/src/git-repository.js:83:32
```

### Commands

```
     -9:59 core:copy (input.hidden-input)
     -9:56.6.0 core:paste (input.hidden-input)
     -9:49.1.0 core:copy (input.hidden-input)
     -9:47.7.0 core:paste (input.hidden-input)
     -9:34.2.0 core:copy (input.hidden-input)
     -9:32.4.0 core:paste (input.hidden-input)
  2x -9:30.5.0 core:save (input.hidden-input)
     -7:06.6.0 core:paste (input.hidden-input)
  4x -7:05.6.0 core:confirm (input.hidden-input)
  3x -6:18.7.0 core:paste (input.hidden-input)
  2x -1:47.5.0 Python run: run-f5 (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.8.1 
atom-runner 2.7.1 
autoclose-html 0.23.0 
autocomplete-python 1.10.2 
Hydrogen 1.21.1 
language-markdown 0.25.1 
markdown-preview-plus 2.4.10 
markdown-writer 2.7.2 
```

**Comment by rsese** [comment] 2017-09-12 20:21
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/7885. You may want to subscribe there for updates - if you have any consistent steps to reproduce in safe mode, please let us know in the issue!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-12 20:21 UTC
