### ISSUE TITLE
Enclosing Braket didn't work.

### ISSUE THREAD

**Issue by AFerreli** [atom/atom#12063] opened 2016-06-28 15:12 UTC
Hi,

### Description

I can't use the enclosing braket. I tried in varius type of file (i switch the language too, but it still didn't work). I also tried the safe mode: didn't work.

### Steps to Reproduce

1. Try to click Ctrl + Alt + Enclosing braket (italian keyboard).
I also tried Alt Gr + Enclosing braket but still didn't work.

### Versions

Atom 1.8.0, Windows 8.1 64bit.

Thanks in advance for the response.

**Comment by mnquintana** [comment] 2016-06-29 00:48
Sorry to hear you're running into this! This looks like a duplicate of https://github.com/atom/atom-keymap/issues/37 and/or https://github.com/atom/atom-keymap/issues/35 – feel free to subscribe to those issues for updates.

**Closed by mnquintana** 2016-06-29 00:48 UTC

**Comment by AFerreli** [comment] 2016-06-29 07:26
Thanks for the quick reply! I searched for "braket" in the issue list (open and closed) but didn't find nothing. Sorry for the duplciate.
