### ISSUE TITLE
I can not copy the string with spaces

### ISSUE THREAD

**Issue by Mencey0** [atom/atom#10706] opened 2016-02-05 19:14 UTC
I copy the two lines. Each row of 80 whitespaces. After inserting these lines get two lines. Each contains 0 whitespaces. Where are my whitespaces ???

P.S. Sorry for my English.

**Comment by trainto** [comment] 2016-02-06 06:11
Well, I was confused what your were talking about.. but I figured out what your are referring to :)
However I was wondering that do you really need copy white spaces?
I've checked other text editors(e.g. Sublime, notepad++) they can copy and paste white spaces.....
but considering you code programming language, ignoring white spaces(only tailing,
ATOM does not ignore white spaces for indentation) will be actually helpful for you.

**Comment by lee-dohm** [comment] 2016-02-08 19:03
I am able to reproduce this using Atom v1.4.3 on Mac OS X 10.11.3. Here's what I did:

1. Launch Atom
1. Go into the [whitespace package](https://atom.io/packages/whitespace) settings and disable "Remove Trailing Whitespace"
1. Open a new file using <kbd>Cmd+N</kbd>
1. Press <kbd>Space</kbd> ten times
1. Highlight the ten spaces using <kbd>Shift+Cmd+Left</kbd>
1. Copy the ten spaces to the clipboard using <kbd>Cmd+C</kbd>
1. Paste the ten spaces eight times using <kbd>Cmd+V</kbd> eight times
1. Press <kbd>Enter</kbd> (since "Remove Trailing Whitespace" is off, you should now have two lines with 80 space characters)
1. Press <kbd>Enter</kbd> again
1. Highlight to the beginning of the third line using <kbd>Shift+Cmd+Left</kbd>
1. Delete the third line of spaces using <kbd>Backspace</kbd>
1. Highlight to the beginning of the file using <kbd>Shift+Cmd+Up</kbd>
1. Copy the two lines of 80 space characters to the clipboard using <kbd>Cmd+C</kbd>
1. Delete the two lines of 80 space characters by pressing <kbd>Backspace</kbd>
1. Paste the two lines of 80 space characters by pressing <kbd>Cmd+V</kbd>

**Expected:** Two lines of 80 space characters to be inserted
**Actual:** Two lines with no contents at all are inserted

**Comment by lee-dohm** [comment] 2016-02-08 19:08
I did a little searching and this is a duplicate of #5891. Disabling the "Auto Indent On Paste" setting allows for the whitespace to be inserted properly. Please subscribe there for updates.

**Closed by lee-dohm** 2016-02-08 19:08 UTC
Labels: bug
