### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '/\corp.qf.qantas.com.au\Profiles\'

### ISSUE THREAD

**Issue by hossainmoazzem** [atom/atom#19604] opened 2019-06-27 00:36 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat '\\corp.qf.qantas.com.au\Profiles\'

```
At fs.js:1621

Error: EPERM: operation not permitted, lstat '\\corp.qf.qantas.com.au\Profiles\'
    at Proxy.realpathSync (fs.js:1621:13)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at atom.project.getPaths.map.e (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:814633)
    at Array.map (<anonymous>)
    at Object.startTask (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:814624)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:188846)
    at get_process.nextTick (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:186810)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
```

**Comment by rsese** [comment] 2019-06-27 05:31
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/19433 so you can subscribe there for updates if you'd like.   If you have specific steps to reproduce, please let us know in https://github.com/atom/atom/issues/19433.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-27 05:31 UTC
