### ISSUE TITLE
In mac,with no opening window or window without project, the reopen project menu has no items.

### ISSUE THREAD

**Issue by xjkdev** [atom/atom#14130] opened 2017-04-04 13:34 UTC
Prerequisites
[X] Reproduced the problem in Safe Mode
[X] Followed all applicable steps in the debugging guide
[X] Checked the FAQs on the message board for common solutions
[X] Checked that your issue isn't already filed
[X] Checked that there is not already an Atom package that provides the described functionality

Description

The reopen project menu only works if a project opened, and it's confusing to me. I think when i start atom i should be able to reopen history opened projects but i can't.

Steps to Reproduce

1. Close all windows and then quit atom.
2. reopen atom.
or
1. Close all windows.
or
1. Close all windows.
2. New window(empty window) or new file etc. without projects.

Expected behavior: reopen project menu has history projects, and when click reopen it.

Actual behavior: reopen project is empty or nothing happens when click.

Reproduces how often: everytimes

Versions
Atom        : 1.15.0
Electron   : 1.3.13
Chrome   : 52.0.2743.82
Node       : 6.5.0
Mac         : 10.12.4 (16E195)

**Comment by Ben3eeE** [comment] 2017-04-04 14:09
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13758.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-04-04 14:09 UTC
Labels: duplicate

**Comment by xjkdev** [comment] 2017-04-05 06:23
I'm sorry that i didn't found that issue when asking, for it's closed before mine.

**Comment by Ben3eeE** [comment] 2017-04-05 08:32
@xjkdev No problem :grinning: The issue is closed because it has been fixed. The fix should be in Atom 1.16 currently in beta or in Atom 1.17 which is the next beta version. I don't remember exactly which version it was fixed in.
