### ISSUE TITLE
Atom is really slow when typing 

### ISSUE THREAD

**Issue by alejomendoza** [atom/atom#10619] opened 2016-01-29 15:28 UTC
So it would take like a lot of time for the letters to show up when I type. I'm using OS X Yosemite with a MCP 16GB of Ram, 2.6 GHz Intel core i7. I tried using Atom like 3 times now and I always go back to webstorm because of the UI slowness and slow rendering. Performance needs a lot of improvement here. 

https://vid.me/5Ppi
https://vid.me/sCqu

**Comment by alejomendoza** [comment] 2016-01-29 15:35
![screen shot 2016-01-29 at 10 34 45 am](https://cloud.githubusercontent.com/assets/5351127/12679773/0009c622-c674-11e5-8629-cbde9867d66d.png)

**Comment by mnquintana** [comment] 2016-01-29 16:18
Sorry you're running into trouble! 

- Can you reproduce this particular slowness after quitting Atom completely and reopening it in safe mode? (`atom --safe`)
- What version of Atom are you using?

**Comment by brennhill** [comment] 2016-02-26 12:46
Let me add some data.
We have this issue with unacceptable slowness when editing RAML files.  In particular if a RAML file has lots of include directives everything slows to a halt.  We've taken to editing in webstorm and then checking errors in Atom because of the RAML support.

**Comment by 50Wliu** [comment] 2016-12-15 16:05
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/10619#issuecomment-176842466. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2016-12-15 16:05 UTC
Labels: more-information-needed, performance

**Comment by Breno999** [comment] 2017-01-05 16:20
Hi! 
I apologize for reopening this thread.

I'm running into apparently the same issue.
When I type, the editor keeps stuttering like some sort of short freeze in whatever speed I type.

I tried atom --safe and the lag went away, but I tried cleaning all of my plugins and the issue still goes on...

**Comment by 50Wliu** [comment] 2017-01-05 16:29
@Breno999 Rename `~/.atom` to `~/.atom-backup` (or if on Windows, the directory is `%USERPROFILE%\.atom`, and you'll have to rename it to `%USERPROFILE%\.atom-backup.`).  Then slowly start moving things back to `~/.atom` until the slowdown occurs, and you've narrowed down the issue.

**Comment by Breno999** [comment] 2017-01-05 16:31
OK! Gonna try it know!
I'll keep this updated...

Thank you!
