### ISSUE TITLE
Uncaught TypeError: Array.prototype.slice called on null or undefined

### ISSUE THREAD

**Issue by petergi** [atom/atom#9007] opened 2015-09-30 12:38 UTC
[Enter steps to reproduce below:]
1. Launch Atom...
2. See error...
3. Be amazed...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Array.prototype.slice called on null or undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:79

TypeError: Array.prototype.slice called on null or undefined
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:79:67)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at handleMessage (internal/child_process.js:632:10)
  at Pipe.channel.onread (internal/child_process.js:421:11)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
Remote-FTP, v0.7.4
antialiased, v0.1.0
atom-typescript, v7.0.1
atom-wallaby, v1.0.4
atom-yamljson, v0.2.3
autocomplete-modules, v1.2.0
circle-ci, v0.10.1
coffee-navigator, v0.0.16
drag-drop-text, v0.1.4
figlet, v0.4.0
file-icon-supplement, v0.8.3
file-icons, v1.6.9
file-type-icons, v0.7.3
file-types, v0.5.1
font-awesome-snippetset, v0.0.6
font-viewer, v0.3.0
fonts, v0.6.0
git-log, v0.4.1
github-utils, v0.6.2
grunt-runner, v0.11.0
icon-fonts, v1.6.2
js-autoimport, v0.5.1
js-patterns-atom-snippets, v0.2.1
jsformat, v0.9.0
json-colorer, v0.3.0
jsonpp, v0.1.1
language-gherkin-i18n, v1.2.0
language-js-specs, v0.1.0
language-json5, v1.1.0
language-mongodb, v0.2.0
linter, v1.6.0
linter-coffeescript, v1.0.0
linter-eslint, v3.0.2
linter-js-yaml, v1.1.2
make-coffee, v0.1.1
markdown-deluxe, v1.0.0
markdown-format, v2.5.1
method-separator, v0.1.3
mocha, v0.0.7
node-debugger, v1.1.8
node-on-fire, v0.1.0
nodejs-snippets, v1.0.3
opentype-feature-bundle, v0.2.2
pretty-json, v0.4.1
remote-edit, v1.8.21
smart-daemon-control, v0.7.2
ssh-config, v0.10.1
tab-control, v0.6.8
tree-view-git-modified, v0.5.10
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by benogle** [comment] 2015-09-30 16:04
Try starting atom with `atom --safe .`. Does that help?

**Comment by petergi** [comment] 2015-10-05 21:01
Hey there, Thanks for the reply. I did something far more drastic. I removed all traces of Atom and it’s plugins. Then reinstalled it with a strict minimum. All is well now. 
In hindsight though… I wish I had taken the time to figure out WHICH plugin was having the bad interaction.

**Comment by Ben3eeE** [comment] 2016-12-15 15:57
Looks like this was caused by a community package. Closing.

**Closed by Ben3eeE** 2016-12-15 15:57 UTC
Labels: more-information-needed, needs-reproduction, uncaught-exception
