### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Mforever** [atom/atom#17728] opened 2018-07-23 07:12 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\RusBear55\AppData\Local\atom\app-1.28.2\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:328

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:328:31)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:140:22)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor-component.js:881:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor-component.js:1560:59)
```

### Commands

```
     -6:28.1.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -0:33.1.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-clock 0.1.16 
atom-live-server 2.3.0 
autocomplete-modules 2.1.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.3.0 
comment 0.6.1 
double-tag 1.5.0 
emmet 2.4.3 
file-icons 2.1.22 
git-plus 8.0.0 
highlight-selected 0.14.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.2.0 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-autohide 0.10.1 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
open-in-browser 0.5.2 
pigments 0.40.2 
project-manager 3.3.6 
remote-ftp 2.2.0 
```

**Comment by CraigCottingham** [comment] 2018-07-23 15:39
Also happening on macOS 10.13.6.

**Comment by rsese** [comment] 2018-07-23 19:44
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16892 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-07-23 19:44 UTC
