### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '/\oevs8r2file.1ed.local\fr$\'

### ISSUE THREAD

**Issue by dapilk** [atom/atom#20870] opened 2020-06-02 09:25 UTC
[Enter steps to reproduce:]
The bug appears after selecting and opening a project folder from menu.

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat '\\oevs8r2file.1ed.local\fr$\'

```
At fs.js:122

Error: EPERM: operation not permitted, lstat '\\oevs8r2file.1ed.local\fr$\'
    at Proxy.realpathSync (fs.js:1470:5)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at C:/ProgramData/mark.pilkington/atom/app-1.47.0/resources/app/static/<embedded>:11:813938
    at Array.map (<anonymous>)
    at Object.startTask (C:/ProgramData/mark.pilkington/atom/app-1.47.0/resources/app/static/<embedded>:11:813929)
    at Object.startLoadPathsTask (C:/ProgramData/mark.pilkington/atom/app-1.47.0/resources/app/static/<embedded>:11:189147)
    at C:/ProgramData/mark.pilkington/atom/app-1.47.0/resources/app/static/<embedded>:11:187111
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-live-server 2.3.0 
```

**Comment by darangi** [comment] 2021-01-27 17:43
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/19433 so you can subscribe there for updates if you'd like.   If you have specific steps to reproduce, please let us know in https://github.com/atom/atom/issues/19433.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2021-01-27 17:43 UTC
