### ISSUE TITLE
Unsaved buffer lost during version upgrade

### ISSUE THREAD

**Issue by henyojess** [atom/atom#12080] opened 2016-07-01 10:01 UTC
### Description
Unsaved changes were lost during atom restart during an update.
No warning was displayed prompting the user to save the files.

### Steps to Reproduce

1. Install atom 1.7.4
2. open a new tab and type some text in without saving to a file
3. open About Atom screen and trigger download updates
4. allow atom to restart

**Expected behavior:** 
when atom restarts, it should have the tab with the unsaved text or it should have warned  the user that there are unsaved changes and they will be lost so that the user can cancel the restart

**Actual behavior:** 
the tab containing the unsaved text was LOST

### Versions
Before update: Atom 1.7.4
After update: Atom 1.8.0 running on OSX El Capitan 10.11.5

**Comment by lee-dohm** [comment] 2016-07-12 23:49
I was unable to reproduce this using Atom v1.7.4 on Mac OS X 10.11.5. I tried several different ways to lose unsaved changes between v1.7.4 and v1.8.0 and the only way that I was able to was via https://github.com/atom/atom/issues/10474. So I'm going to close this as a duplicate of that Issue. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-12 23:49 UTC
