### ISSUE TITLE
atom terminal command only works when app is not running

### ISSUE THREAD

**Issue by s2t2** [atom/atom#11737] opened 2016-05-11 20:24 UTC
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

The `atom` terminal command works only when atom is not currently running. When the app is running, subsequent attempts to use the `atom` command do not work.

### Steps to Reproduce

1. Ensure installation of shell commands from the atom menu.
2. Quit Atom. 
3. Open Terminal
4. execute `atom my_file.txt` (works!)
5. execute `atom my_other_file.txt` (doesn't work :-/)

**Expected behavior:** The `atom` command should open files/folders upon subsequent attempts.

**Actual behavior:** Subsequent attempts do quickly flash the Mac menu bar's active application from **Terminal** to **Atom**, but the file never opens.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4

Mac OS El Capitan - version 10.11.4

I recently installed xcode, which could perhaps be the cause of the error.

**Comment by s2t2** [comment] 2016-05-11 20:41
FYI - I completely uninstalled atom using [these instructions](https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/14?u=s2t2), then installed it again using `brew cask install atom` and the problem persists.

**Comment by s2t2** [comment] 2016-05-11 20:57
I thought this might be a path issue. FYI here are the values of `PATH`...


From Terminal:

```` sh
echo $PATH
/usr/local/var/rbenv/shims:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
````

From Atom Dev Console:

````js
process.env["PATH"]
"/usr/local/var/rbenv/shims:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
````

**Comment by damieng** [comment] 2016-05-12 01:48
Duplicate of https://github.com/atom/atom/issues/11712

**Closed by damieng** 2016-05-12 01:48 UTC
Labels: duplicate, mac

**Comment by s2t2** [comment] 2016-05-12 05:27
Thanks, I searched but didn't see that one.
