### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by lro3818** [atom/atom#11741] opened 2016-05-12 14:08 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: linux 4.5.2-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as getPosition] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:626:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:660:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app.asar/src/window-event-handler.js:182:35)
    at /usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
     -0:26.4.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:25.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:21.7.0 editor:newline-above (atom-text-editor.editor.is-focused)
     -0:20 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:19.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.1.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:17.8.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:17.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:15.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.3.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:06.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.8.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-sass-lint"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "tabType": "hard"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-wordpress-hooks, v0.2.0
css-snippets, v0.9.0
emmet, v2.4.3
linter, v1.11.4
linter-htmlhint, v1.1.4
linter-jshint, v2.1.0
minimap, v4.23.5
minimap-pigments, v0.2.0
pigments, v0.26.2
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-05-12 14:17
Closing as a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-12 14:17 UTC
