### ISSUE TITLE
Data loss when exiting Atom with unsaved files

### ISSUE THREAD

**Issue by JDougherty** [atom/atom#13568] opened 2017-01-08 03:21 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When exiting Atom with one or more unsaved files, there is no confirmation to exit without saving, and the content of any unsaved files is completely lost. 

### Steps to Reproduce

1. Open Atom
2. Start a new file
3. Add some content to the file
4. Exit Atom (e.g, by clicking the "X" icon in the window, or by using File --> Quit)
5. Re-open Atom
6. File content is gone! 

**Expected behavior:** 

Atom should either automatically save files that have not been saved when closed (e.g, like Sublime Text does by default), or confirm with the user that they would like to exit without saving changes. 

**Actual behavior:** 

There is no confirmation to exit, nor is there any automatic saving. This means the content of any unsaved files is lost! 

**Reproduces how often:**
100% 

### Versions

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS: Linux Mint 18 "Sarah", Linux 4.7.5-040705-generic #201609240533 SMP Sat Sep 24 09:35:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lee-dohm** [comment] 2017-01-08 17:16
Thanks for reaching out! This is a duplicate of https://github.com/atom/atom/issues/10474, when an Atom window is opened that has no project folders, the current stable version of Atom (v1.12.9) can close without a confirmation when there are unsaved changes. This has been fixed to present a confirmation dialog in v1.13-beta, see https://github.com/atom/atom/pull/12922 for details. In the situation where there is at least one project folder, the unsaved information is stored as part of the project state.

Thanks again for reporting the problem.

**Closed by lee-dohm** 2017-01-08 17:16 UTC
