### ISSUE TITLE
Ubuntu: Project root directory selecting issues.

### ISSUE THREAD

**Issue by tchalvak** [atom/atom#3887] opened 2014-10-18 20:18 UTC
Did a fresh install on ubuntu.  However, when I try to open a directory to get a tree listing on the left, or set the default project directory in the preferences, both are ignored.  Instead, it only shows a project using my /home/userName/ folder as it's root.  This is somewhat problematic because there's a lot of unnecessary cruft in my home directory that get picked up (for instance, running a search makes it try to index).  And, of course, it's also a problem because I can't get a useful listing of files that -aren't- located in my home directory, and have an unusably long project file tree instead.

version: .deb version 0.138.0
Ubuntu version: Ubuntu 12.04.5 LTS (64 bit)
How to reproduce: Install the .deb from a directory under your /home/ folder.
developer console: No logged errors in the developer console.

**Comment by vumaasha** [comment] 2015-02-24 10:29
+1 I have the same issue.  It is taking more than a quarter to get this fixed on a next gen Editor? Come on guys

**Comment by 50Wliu** [comment] 2015-02-24 12:57
@vumaasha what Atom version are you using?  Are you on Ubuntu as well?  Can you reproduce this in safe mode (`atom --safe`)?

**Comment by vumaasha** [comment] 2015-02-24 18:34
atom version 0.182.0
*No. it does not happen in safe mode.*
Ubuntu version: ( with all latest updates)
============
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

**Comment by 50Wliu** [comment] 2015-02-24 20:07
All right, since it doesn't happen in safe mode, that means that one of your installed community packages is causing the issue.  You could try out the [package-cop](https://atom.io/packages/package-cop) package by @mark-hahn to try to resolve your issue or just manually disable packages to find the culprit.

**Comment by vumaasha** [comment] 2015-02-26 08:35
@50Wliu  I do not have any community packages installed. I am testing this in a fresh atom installation. It has only core packages in settings page

**Comment by 50Wliu** [comment] 2015-02-26 17:47
If you can't reproduce it in safe mode, that means you have a package somewhere interfering with Atom.  Safe mode and non-safe mode should perform identically with no community packages.

**Comment by kevinsawicki** [comment] 2015-07-27 22:56
Closing this out since it seems to be a 3rd party package issue and hasn't been reported when running in safe mode.

**Closed by kevinsawicki** 2015-07-27 22:56 UTC
Labels: linux, more-information-needed
