### ISSUE TITLE
Opening a file in a folder with lots of files (50.000 or more) takes very long time.

### ISSUE THREAD

**Issue by me-kell** [atom/atom#18646] opened 2019-01-04 11:34 UTC
### Description

Opening a file in a folder with lots of files (50.000 or more) takes very long time. And causes Atom to crash.
This is probably because the Project Tree has to be build.
Toggling off the Tree Pane doesn't change anything.
Closing atom with an open file in such a full folder takes also some time. And reopening atom it tries to reload the whole Project Tree.
Is there any way to disable loading the whole folder contents?

### Versions

Windows 7 64bit
Atom 1,33,1 x64

**Comment by rsese** [comment] 2019-01-04 22:19
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/1847 so you can subscribe there for updates if you'd like (you may want to subscribe to https://github.com/atom/atom/pull/18608 as well, the behavior change there would help this particular case you describe).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-01-04 22:19 UTC
