### ISSUE TITLE
Remove squirrel after open change log.

### ISSUE THREAD

**Issue by pyvim** [atom/atom#8392] opened 2015-08-15 08:49 UTC
Distracting me. We need to re-open the Atom that it has disappeared.

**Comment by mnquintana** [comment] 2015-08-15 10:55
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/release-notes/issues/36 though - please subscribe there for updates.

**Closed by mnquintana** 2015-08-15 10:55 UTC
