### ISSUE TITLE
Old versions not removed on upgrade (Windows)

### ISSUE THREAD

**Issue by siucdude** [atom/atom#15655] opened 2017-09-14 23:03 UTC
So I'm probably not following the bug report concept (sorry not a developer or much of it person)... but i need to send this to developers..

The issue is how ATOM is filling up my windows 10 hard drive..

I was wondering recently why my HD was beginning to fill up. after looking at all the issues i found one strange folder
~/AppData/Local/atom/ 
was at almost 5.5GB of space.. after exploring it a bit i found out that old version of ATOM are not being cleared out properly, this included old bugs... and packages. about 450MB per each version you upgrade.

Thank You and please correct this issue.

Thank You
Tom

**Comment by MatthijsBlom** [comment] 2017-09-15 05:56
I have experienced this problem as well, every time I updated Atom.

I do not have a third party anti-virus running, nor am I on a corporate network.

**Comment by Ben3eeE** [comment] 2017-09-15 06:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15320. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-09-15 06:38 UTC
Labels: duplicate
