### ISSUE TITLE
Editor Parse Syntax Errror not successfull

### ISSUE THREAD

**Issue by unname123** [atom/atom#17083] opened 2018-04-05 09:06 UTC
Hi ,
i am installed new atom and added package atom-ide-ui , this is very good but has some problem, that is unsuccess to editor color parse , please check my photo 
![screenshot from 2018-04-05 11-55-20](https://user-images.githubusercontent.com/16854006/38356759-49c7ce5c-38c9-11e8-9b5b-f42424f37e68.png)

that problem start point is in the string '(' , if i remove this then will success 

i will wait  for patch , thanks everyone 

Code Type : PHP

**Comment by Ben3eeE** [comment] 2018-04-05 13:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-php/issues/321. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-04-05 13:29 UTC
