### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetHeight' of undefined

### ISSUE THREAD

**Issue by oscaroceguera** [atom/atom#8762] opened 2015-09-12 05:57 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'offsetHeight' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:829

TypeError: Cannot read property 'offsetHeight' of undefined
  at TextEditorComponent.module.exports.TextEditorComponent.isVisible (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:829:26)
  at TextEditorComponent.module.exports.TextEditorComponent.measureLineHeightAndDefaultCharWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:915:16)
  at TextEditorComponent.module.exports.TextEditorComponent.sampleFontStyling (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:896:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:587:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:772:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:564:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Workspace.module.exports.Workspace.increaseFontSize (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:663:26)
  at atom-workspace.atom.commands.add.window:increase-font-size (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:164:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
  2x -0:14.9.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:14 window:increase-font-size (atom-text-editor.editor.is-focused)
  6x -0:06.3.0 core:backspace (atom-text-editor.editor.is-focused)
 13x -0:03.9.0 window:increase-font-size (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-eslint"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "tabLength": 4,
    "fontSize": 24
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
atom-alignment, v0.12.1
drunken-php, v0.1.2
emmet, v2.3.12
language-babel, v0.13.2
linter, v1.5.1
linter-php, v1.0.3
minimap, v4.13.2
php-cs-fixer, v2.4.0
php-debug, v0.1.3
react-snippets, v0.2.0
seti-icons, v0.4.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-09-12 20:58
Hi @oscaroceguera, what were you doing when this happened?  In addition, can you reproduce this exception in safe mode (`atom --safe`)?  Thanks.

**Comment by izuzak** [comment] 2015-09-22 07:41
Wondering if @nathansobo or @as-cii have any :thought_balloon: on this one. Any chance this is a problem in Atom and not some package causing problems?

**Comment by as-cii** [comment] 2015-09-22 08:17
It seems as if the `@domNode` variable in `TextEditorComponent` cannot be accessed. We never reassign it in our core code so I can this of two possible scenarios:

1. A package is setting the variable to `null`. This seems a bit unlikely, though.
2. A change in configuration happens **before** assigning `@domNode`. This is quite strange as well, 'cause I'd expect `TextEditorComponent`'s constructor to complete before relinquishing control to config events.

I'll try to reproduce it: if I can't, we may put an `atom.assert` call to gather some more information.

**Comment by samschmidt** [comment] 2016-11-05 15:23
Looks like this was fixed! Consider closing.

**Closed** 2016-11-05 15:40 UTC
Labels: editor-rendering, more-information-needed, uncaught-exception

**Comment by PointedEars** [comment] 2017-10-06 01:13
Apparently this issue re-emerged in Atom 1.21.0.

Steps to reproduce:

1. Write something.

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Debian GNU/Linux
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'offsetHeight' of undefined

```
At /usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337

TypeError: Cannot read property 'offsetHeight' of undefined
    at SuggestionListElement.readUIPropsFromDOM (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337:54)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:191:15)
    at /usr/share/atom/resources/app/src/view-registry.js:3:65
```

### Commands

```
  4x -1:23.8.0 vim-mode-plus:move-left (input.hidden-input)
     -1:22.2.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -1:21.7.0 editor:select-to-end-of-line (input.hidden-input)
     -1:21.3.0 intentions:highlight (input.hidden-input)
     -1:21.2.0 core:cut (input.hidden-input)
     -1:20.6.0 core:backspace (input.hidden-input)
     -1:20.2.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -1:19.6.0 core:move-down (input.hidden-input)
     -1:19.3.0 core:move-left (input.hidden-input)
     -1:12.7.0 intentions:highlight (input.hidden-input)
     -1:12.7.0 core:paste (input.hidden-input)
     -1:08.2.0 click (span.syntax--comment.syntax--line.syntax--percentage.syntax--tex)
  2x -1:08.0 core:backspace (input.hidden-input)
     -1:06.2.0 intentions:highlight (input.hidden-input)
     -1:05.9.0 core:save (input.hidden-input)
  2x -0:42.6.0 click (a.btn-issue.btn.btn-error)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-css-unit-converter 1.1.1 
atom-mysql-snippets 0.3.1 
atom-php-navigation 0.6.0 
atom-ternjs 0.18.3 
atom-x 0.4.0 
atomatigit 1.5.5 
autoclose-html 0.23.0 
autocomplete-awk 0.1.2 
autocomplete-bibtex 0.7.0 
autocomplete-clang 0.11.3 
autocomplete-html-entities 0.1.0 
autocomplete-paths 2.11.0 
autocomplete-php 0.3.7 
autocomplete-python 1.10.3 
autocomplete-xml 0.9.4 
autoupdate-packages 1.3.1 
block-comment 0.4.3 
busy-signal 1.4.3 
character-table 0.4.3 
clipboard-plus 0.5.1 
color-picker 2.2.5 
column-select 0.2.0 
compare-files 0.8.1 
css-snippets 1.1.0 
ctrl-last-tab 0.3.0 
data-atom 0.26.0 
docblockr 0.11.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
es6-javascript 1.0.0 
ex-mode 0.18.0 
filesize 3.0.0 
fixmyjs 1.4.1 
fold-comments 0.6.0 
git-blame 1.3.1 
git-clone 0.2.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-difftool 0.2.7 
git-go 1.0.5 
git-hide 1.0.0 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.9.3 
git-rebase 0.1.1 
git-status 0.3.4 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
goto 1.8.3 
goto-definition 1.3.4 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
hyperclick-php 0.2.1 
indent-toggle-on-paste 0.1.3 
intentions 1.1.5 
iso8601-timestamp 0.1.1 
javascript-snippets 1.2.1 
js-hyperclick 1.11.1 
js-refactor 0.7.5 
language-apache 1.7.0 
language-awk 0.1.12 
language-babel 2.75.0 
language-diff 0.7.0 
language-gettext 0.6.1 
language-ini 1.19.0 
language-latex 1.1.1 
language-lua 0.9.11 
language-sql-mysql 0.3.1 
language-swift 0.5.0 
latex-autocomplete 1.0.0 
latex-completions 0.3.3 
latex-friend 0.0.11 
latex-hyperclick 0.2.0 
latexer 0.3.0 
latextools 0.8.5 
lcars-syntax 0.0.1 
less-autocompile 1.0.0 
less-than-slash 0.17.0 
line-count-status 0.0.3 
line-jumper 0.14.1 
linter 2.2.0 
linter-checkbashisms 0.1.5 
linter-chktex 1.3.1 
linter-csslint 2.0.0 
linter-htmlhint 1.3.4 
linter-jshint 3.1.6 
linter-less 2.6.0 
linter-mixed-indent 1.1.1 
linter-mypy 2.3.0 
linter-php 1.5.1 
linter-pylint 2.1.0 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
local-history 4.3.0 
MagicPython 1.0.12 
man 0.8.2 
merge-conflicts 1.4.5 
method-separator 0.2.0 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.1 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
multi-cursor-plus 1.2.0 
multi-file-open 0.1.1 
multirow-tabs 0.3.3 
navigate 0.1.17 
navigate-indent 0.1.0 
next-occurrence 0.5.0 
nuclide 0.258.0 
nuclide-format-js 0.0.41 
open-git-modified-files 0.2.4 
open-recent 5.0.0 
open-this 0.4.0 
pdf-view 0.59.0 
php-debug 0.2.5 
php-extract-method 0.2.1 
php-getters-setters 0.5.5 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
preview 0.17.0 
preview-inline 1.4.7 
project-folder 1.5.0 
project-view 0.6.2 
promote-folder-to-project 2.0.2 
punchclock 0.6.5 
python-isort 0.0.7 
python-tools 0.6.9 
qolor 0.4.2 
quantum-shell 0.7.1 
quick-query 0.12.1 
recent-projects 0.13.1 
refactor 0.11.5 
regex-tester 0.2.0 
remember-file-positions 0.2.3 
remote-edit 1.9.0 
revert-buffer 0.5.0 
script 3.16.0 
set-syntax 0.4.0 
seti-ui 1.9.0 
show-origin 0.2.0 
sloc 1.1.0 
sort-lines 0.15.0 
split-diff 1.5.1 
switch-header-source 0.22.1 
symbols-tree-nav 0.15.5 
symbols-tree-view 0.14.0 
term 0.2.4 
text-manipulation 0.6.0 
todo-show 2.1.0 
tool-bar 1.1.0 
tree-view-git-status 1.4.0 
up2date 0.1.2 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 1.8.1 
w3c-validation 0.4.0 
wordcount 2.10.4 
xkcd-comics 0.3.0 
xml-tools 0.2.1 
Zen 0.18.0 
```

**Comment by ExillustX** [comment] 2017-10-12 13:39
[Enter steps to reproduce:]

1. editing a `.todo` file.

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'offsetHeight' of undefined

```
At C:\Users\ExillustX\AppData\Local\atom\app-1.21.0\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:337

TypeError: Cannot read property 'offsetHeight' of undefined
    at SuggestionListElement.readUIPropsFromDOM (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337:54)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.21.0/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:18 tasks:add (input.hidden-input)
  2x -0:15.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
autoprefixer 3.7.1 
comment-headers 2.15.0 
dash-syntax 0.4.1 
dash-ui 0.4.3 
docblockr 0.11.0 
emmet 2.4.3 
monokai-seti 0.9.0 
pigments 0.40.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
tasks 2.6.7 
wakatime 7.0.3 
```

**Comment by mdotwills** [comment] 2017-10-16 01:07
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'offsetHeight' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337

TypeError: Cannot read property 'offsetHeight' of undefined
    at SuggestionListElement.readUIPropsFromDOM (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:337:54)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:58.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:58.1.0 snippets:expand (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-jade 0.3.0 
atom-panda-syntax 0.18.0 
highlight-selected 0.13.1 
language-javascript-jsx 0.3.7 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
path-copy 0.14.0 
pigments 0.40.2 
project-manager 3.3.5 
save-workspace 0.4.0 
tree-view-copy-relative-path 1.2.0 
```

**Comment by nathansobo** [comment] 2017-10-16 14:22
@leroix Can you take a look at these exceptions and see if you can make sense of the stack trace?

**Comment by Ben3eeE** [comment] 2017-10-16 14:30
@nathansobo Looks like the issue that @leroix already fixed in https://github.com/atom/autocomplete-plus/pull/895#issuecomment-333679203?

**Comment by nathansobo** [comment] 2017-10-16 14:58
@Ben3eeE Maybe we should cherry-pick his fix to the current version of autocomplete to prevent people from hitting this until the next release?

**Comment by Ben3eeE** [comment] 2017-10-16 15:17
@nathansobo Yeah I think we should queue this up for hotfix. There are many users hitting this issue.

**Comment by leroix** [comment] 2017-10-16 19:36
We have a hotfix for 1.21 queued up for this 👍 .

**Comment by 0PEIN0** [comment] 2017-11-20 05:12
Is the hotfix deployed? Faced the error just now again.
