### ISSUE TITLE
Icons display incorrectly on macOS High Sierra

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom#15410] opened 2017-08-22 19:19 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On macOS High Sierra (10.13 Beta), icons look "whitewashed".

### Steps to Reproduce

1. Install Atom + Atom Beta
2. Upgrade to Mac High Sierra
3. Observe whitewashed icons

**Expected behavior:** Icons should look as they did in macOS Sierra (10.12.x)

**Actual behavior:** Icons look whitewashed

<img width="337" alt="screen shot 2017-08-22 at 11 44 55 am" src="https://user-images.githubusercontent.com/744740/29583119-471a6302-873c-11e7-97b1-263698b3a8fc.png">

![screen shot 2017-08-22 at 12 27 48 pm](https://user-images.githubusercontent.com/744740/29583235-a83844c4-873c-11e7-8f00-9dc9deda9140.png)

<img width="352" alt="screen shot 2017-08-22 at 12 34 48 pm" src="https://user-images.githubusercontent.com/744740/29583137-512ad0f2-873c-11e7-831a-97d111f3efa1.png">

**Reproduces how often:** 100%

### Versions

OS: macOS 10.13 Beta 7
Atom    : 1.21.0-dev-411d878b3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by simurai** [comment] 2017-08-22 22:58
@joefitzgerald Thanks for the issue. I'm not on High Sierra yet, but based on the above screenshot and this one..

<img width="430" alt="screen_shot_2017-08-22_at_12 35 42_pm_1024" src="https://user-images.githubusercontent.com/378023/29591141-27a50620-87d8-11e7-97e9-45d5330890dc.png">

.. it's not an issue with macOS's dock or some sort of setting. But more a problem of the `.ico` file itself and the washed out look is shown in all programs (like Preview). Maybe a color profile issue?

Anyone else already on High Sierra that can reproduce it?

**Comment by bladey** [comment] 2017-08-23 00:27
This is currently a problem for most of my Electron apps on High Sierra, aside from Atom, it also affects GitHub Desktop and Abstract.

![image](https://user-images.githubusercontent.com/737821/29593432-9d370446-87ed-11e7-8172-25d419203014.png)

**Comment by maxvoltar** [comment] 2017-09-11 20:42
Did some research, and apparently `.icns` files generated with Icon Slate.app are the culprit here. Really funny that this impacted mostly Electron apps, as their designers don't use Xcode to generate their app icons.

Started using Icon Creator, and the icon looks great now.

**Comment by donokuda** [comment] 2017-09-21 23:31
> Started using Icon Creator, and the icon looks great now.

@maxvoltar Any chance you can point to me to Icon Creator? My googling isn't getting me anywhere. 🙈

**Comment by maxvoltar** [comment] 2017-09-21 23:33
@donokuda https://itunes.apple.com/us/app/icon-creator-icns-and-icon-set-composer/id562977787?mt=12 :)

**Comment by donokuda** [comment] 2017-09-21 23:36
You're my hero. Thank you! ❤️

**Comment by eonist** [comment] 2017-09-26 13:45
The icon is all washed out. It's like its all Sun bleached. Love the retro look and all but 😁

**Comment by chris-c-thomas** [comment] 2017-09-26 14:15
Having this issue with GitHub Desktop but not Atom. What's the best way to revert the icon or will it be fixed in future app updates?

**Comment by fernandopasik** [comment] 2017-09-26 14:20
@chris-c-thomas check the latest version of Github Desktop, they fixed the icon and now it's being shown with the right colors.
With Atom Beta I can't still see it right.

**Comment by chris-c-thomas** [comment] 2017-09-26 14:25
@fernandopasik hmm I'm using version 1.0.1 and it's still washed out in my dock. It shows fine in the launchpad though. 

Atom version 1.20.1 is showing up fine in my launchpad and dock.

**Comment by fernandopasik** [comment] 2017-09-26 14:45
Weird, I'm with v1.0.1 and I'm seeing it with the right colors.

**Comment by chris-c-thomas** [comment] 2017-09-26 14:47
@fernandopasik I'm thinking is has more to do with local cache on the Mac vs the actual version of the app. Updating the app may have refreshed the icon for you? Just guessing here.

**Comment by donokuda** [comment] 2017-09-26 14:52
Hi @chris-c-thomas and @fernandopasik, I'm currently looking into this for both Atom and Desktop and should get a fix out by reexporting the icons with Icon Creator.

**Comment by danielbayley** [comment] 2017-09-26 17:14
It will be another colour profile issue… a similar thing happened after the last macOS release.

@donokuda You could use a combination of `sips` and `iconutil` as part of the Atom build process to generate the icns.

**Comment by pilarArr** [comment] 2017-09-27 10:42
Just installed Atom 1.21.0 Beta 2 x64 on macOC High Sierra 10.13 and still looks like this.

**Comment by chris-c-thomas** [comment] 2017-09-27 16:43
@pilarArr Can confirm, mine does as well, though my stable looks fine.

**Comment by thomasjo** [comment] 2017-09-27 22:05
PR #15760 resolves the issue, although it might break stuff on macOS 10.12 (and older).

**Closed** 2017-09-30 05:58 UTC
Labels: electron, mac

**Comment by pilarArr** [comment] 2017-09-30 10:51
@chris-c-thomas Can confirm too that the stable Atom icon looks fine as well, only the beta icon looks washed out.

**Comment by thomasjo** [comment] 2017-09-30 10:55
This has been fixed by #15760, but needs to be released. Might end up being hotfixed to stable and beta.

**Comment by hopkinschris** [comment] 2017-10-03 19:08
Was this not included in the `1.22.0-beta0` release?

**Comment by thomasjo** [comment] 2017-10-03 19:11
@hopkinschris Sadly, seems like this wasn't hotfixed to beta. I'll see what we can do about getting it into a patch release or some such.

**Comment by thomasjo** [comment] 2017-10-03 19:42
@hopkinschris Just a quick follow-up; I just cherry-picked the fix to both stable and beta — will get released with the next round of hotfix releases.
