### ISSUE TITLE
@lee-dohm - Atom as windows app is an opportunity for your software.

### ISSUE THREAD

**Issue by duble0** [atom/atom#14290] opened 2017-04-24 21:33 UTC
@lee-dohm 
Hi! I'm Francesco Venuti and I founded UWP Open Source Community, dgsimone15 already contacted you about UWP, but you didn't seem to understand our intentions, so let me explain better ...
We are a team of Windows lovers and developers without any scope of make money. We would only improve our OS ... in the last year Windows 10 has improved a lot, for example today also incorporates a Linux Subsystem (WSL)... Now Microsoft also engaged the mobile challenge, it seems that they would change the concept of mobile computing ... so not just a smartphone, but real desktop experience that could run on ARM devices like tablets and smartphones (connected with a monitor).
We saw the preview of "Windows Colud Edition", this could be the next edition of Windows for education PC (like Chromebooks). Unfortunately for running win32 software on this edition, the software must be converted into UniversalWindowsPlatform app; after conversion, the software could run even on regular Windows 10 editions. If this could be a problem, you should consider the opportunities like: all UWP could use a telemetry to send information about problems to developer, guarantee automatic update every time you emprove your software, could impact on a larger and younger user base that can give You feedback and also start developing your software. 
Furthermore distributing your software as UWP mean that your software run in a sandbox that don't compromise the OS if there are problems.
We don't want make a copy of your work, rather we prefer YOU start publish also on Windows Store as alternative distribution to traditional installer.
We tried the online tool made by Microsoft for convert win32 software to UWP app, if you would use our work to start your experience on Microsoft Store we are pleased to give you all materials and information. Don't be scared about shadow costs, for publish on Microsoft Store you pay only the first time as developer registration, because your app will FLOSS, so there are not fee!
For us is important start Windows Cloud with a large amount of open source apps available for every one.
Scuse me for poor English...😉

**Comment by lee-dohm** [comment] 2017-04-24 21:47
Closing this as a duplicate of [the original](https://github.com/atom/atom/issues/14279). I'll address your points there :grinning:

**Closed by lee-dohm** 2017-04-24 21:47 UTC
