### ISSUE TITLE
The cursor position doesn't follow the writing

### ISSUE THREAD

**Issue by yriveiro** [atom/atom#9335] opened 2015-10-29 23:46 UTC
After upgrade to 1.1.0 I can write right because the cursor is misplaced from the real position.

![atom](https://cloud.githubusercontent.com/assets/934763/10835009/33387730-7e96-11e5-8e3d-ac9401935cb2.gif)

In this screenshot the cursor also is in the wrong place.

![screenshot 2015-10-29 23 49 10](https://cloud.githubusercontent.com/assets/934763/10835166/b2a7a9ae-7e97-11e5-9a69-56963e96ec36.png)

Platform: OS X 10.10.5
Atom: 1.1.0

My config:

```cson
"*":
  "exception-reporting":
    userId: "bc2d58dc-8a4d-9388-ba7c-31de54b21e34"
  welcome:
    showOnStartup: false
  linter:
    lintOnChange: false
    clearOnChange: true
    lintDebug: true
    statusBar: "Show error if the cursor is in range"
    ignoredLinterErrors: [
      "php"
    ]
    subtleLinterErrors: [
      "shellcheck"
    ]
    lintOnFly: false
    showErrorPanel: false
  core:
    disabledPackages: [
      "autocomplete"
      "meteor-api"
      "meteor-helper"
      "meteor-snippets"
      "git-tab-status"
      "color-tabs"
      "hyperclick"
      "sourcegraph-atom"
      "racer"
      "wrap-guide"
    ]
    themes: [
      "atom-dark-ui"
      "seti-syntax"
    ]
    projectHome: "/Users/yriveiro/Development/github/"
  minimap:
    plugins:
      "git-diff": true
      bookmarks: true
    scrollAnimation: true
  editor:
    invisibles: {}
    fontSize: 12
    showIndentGuide: true
    showInvisibles: true
    tabLength: 4
    softTabs: false
    scrollPastEnd: true
    backUpBeforeSaving: true
    fontFamily: "monaco"
  "atom-beautify":
    _analyticsUserId: "ce228ba4-4864-4fdf-aab5-7624cb263e2c"
    language_go_beautify_on_save: true
  "vim-mode":
    useClipboardAsDefaultRegister: true
  "tree-view":
    hideVcsIgnoredFiles: true
  "autocomplete-plus":
    confirmCompletion: "enter"
    includeCompletionsFromAllBuffers: true
  "local-history": {}
  wakatime:
    ignore: [
      "^/var/"
      "^/tmp/"
      "^/private/"
      "COMMIT_EDITMSG$"
      "PULLREQ_EDITMSG$"
      "MERGE_MSG$"
    ]
    apikey: "39bf47b3-1c86-4634-8e52-48a7cb479cd1"
  term2:
    colors: {}
    openPanesInSameSplit: true
  "tool-bar":
    position: "Right"
    visible: false
  "unity-ui": {}
  "one-dark-ui":
    fontSize: 11
    layoutMode: "Spacious"
  tabs:
    tabScrolling: true
    usePreviewTabs: true
    enableVcsColoring: true
  "block-cursor":
    primaryColor:
      red: 239
      green: 153
      blue: 26
      alpha: 1
    cursorLineFix: true
    secondaryColor:
      red: 227
      green: 79
      blue: 170
      alpha: 1
    pulseDuration: 1
    cursorType: "bordered-box"
    preview: "dsfadsf"
  "file-icons":
    forceShow: true
  "git-diff":
    showIconsInEditorGutter: true
  "highlight-line":
    enableUnderline: true
  "color-tabs": {}
  docblockr:
    auto_add_method_tag: true
    deep_indent: true
    development_mode: true
    extra_tags_go_after: true
    lower_case_primitives: true
    per_section_indent: true
    min_spaces_between_columns: 2
  "file-watcher":
    promptWhenFileHasChangedOnDisk: false
  nuclide:
    remoteProjectsConfig: []
  "go-plus":
    runCoverageOnSave: true
    goPath: "/Users/yriveiro/Development/gocode"
    goInstallation: "/usr/local/bin/go"
  "sourcegraph-atom": {}
  "linter-php": {}
  pigments:
    extendAutocompleteToVariables: true
  "find-and-replace":
    openProjectFindResultsInRightPane: true
    scrollToResultOnLiveSearch: true
  "autocomplete-php": {}
  racer: {}
  "linter-rust":
    buildTest: true
    cargoPath: "/usr/local/bin/cargo"
    rustcPath: "/usr/local/bin/rustc"
  whitespace:
    ensureSingleTrailingNewline: false
  "linter-shellcheck":
    shellcheckExecutablePath: "/usr/local/bin/shellcheck"
  "multi-wrap-guide":
    columns: [
      80
      90
    ]
    locked: true
  "php-cs-fixer":
    showInfoNotifications: true
    executeOnSave: true
    executablePath: "/usr/local/bin/php-cs-fixer"
  phpunit:
    execPath: "./vendor/bin/phpunit"
".html.php.text":
  "multi-wrap-guide":
    columns: [
      80
      90
    ]
    rows: [
      13
      32
    ]
  editor:
    preferredLineLength: 90
```

**Comment by kogai** [comment] 2015-10-30 00:16
Same problem has also occured in my enviroment.
Possibly the cause of this problem may be `seti-syntax`, because problem fixed when I switched syntax-them `seti-syntax` to other syntax-theme.

**Comment by yozlet** [comment] 2015-10-30 00:29
Yep, I'm seeing it in `seti-syntax` too. This may still be a core Atom bug, though; I don't see what in `seti-syntax` could be triggering this problem.

**Comment by ncallaway** [comment] 2015-10-30 04:02
I'm seeing the same issue with the Seti theme. I switched to Monokai and everything is working properly now. I tested with each of the themes and only had an issue with Seti. Every time I switched to Seti I saw this issue.

* Atom Dark (Good)
* Atom Light (Good)
* Base16 Tomorrow Dark (Good)
* Base16 Tomorrow Light (Good)
* Monokai (Good)
* One Dark (Good)
* One Light (Good)
* Seti Monokai (Good)
* Solarized Dark (Good)
* Solarized Light (Good)

* Seti (Bad)

I guess this is a good way of getting all of us Seti users together :)

**Comment by pustovalov** [comment] 2015-10-30 04:47
Try this:
https://github.com/jesseweed/seti-syntax/issues/106

**Comment by izuzak** [comment] 2015-10-30 10:18
Thanks for the reports, everyone. I'm going to close this in favor of https://github.com/jesseweed/seti-syntax/issues/106, and cc @as-cii and @nathansobo in case they feel there's something we should do in Atom core about this. :v: 

https://github.com/atom/atom/issues/9336 seems to be the same problem.

**Closed by izuzak** 2015-10-30 10:18 UTC
