### ISSUE TITLE
reg fileswrongly detected as UTF8?

### ISSUE THREAD

**Issue by RezzZ** [atom/atom#20361] opened 2020-01-27 08:02 UTC
when opening a registry file in atom 1.43x64 on windows (10) the file is a plain text UTF8 but it should be UTF-16LE. After a click on autodetect encoding atom correctly changes to UTF16LE display. Why is Atom not autodetecting encoding by default?

**Comment by Arcanemagus** [comment] 2020-01-27 18:14
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/encoding-selector/issues/62. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-01-27 18:14 UTC
