### ISSUE TITLE
Remembering Removed Project Folder(s)

### ISSUE THREAD

**Issue by Utilityman** [atom/atom#13390] opened 2016-12-05 21:55 UTC
### Description
Discovered on a Mac!

User view: If you remove a project folder from atom, the next time you close and reopen Atom the project returns.  

Under the hood: You can see what's going on in the ~/.atom/storage/application.json file. When you remove a project, the initial path is not removed from the file. So on reboot it comes back as if it were never removed at all. 

### Steps to Reproduce (for mac)

1. Right Click Project -> Remove Project Folder
2. Command-Q to quit atom
3. Reboot to find the return of the project.

**Expected behavior:** 
I would expect that when you remove a project folder that it stays removed and does not come back on a separate session. Projects that are added should be added and those that are removed should be removed. 

**Actual behavior:** 
The removed projects persist between sessions. It seems that 'Remove Project Folder' just graphically removes it. 

### Versions

Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

Running On Mac 
OS X El Capitan Version 10.11.6

**Comment by Ben3eeE** [comment] 2016-12-05 22:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12495. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-05 22:16 UTC

**Comment by Utilityman** [comment] 2016-12-06 01:07
Not trying to sound rude but, is this not different? That issue is about remembering projects and this issue is about forgetting projects. 

I suppose that it's in the same umbrella issue with the application.json file but this issue is just about the opposite of that linked.

**Comment by Ben3eeE** [comment] 2016-12-06 06:35
The window state system only saves when changing focus, adding and removing windows. This means that both the add and remove project folder commands have the same issue of not remembering state of the folders, it was just never described in that issue that it also occurs when removing project folders. We like to unify issues that are this closely related in the same place since we are likely to fix all of them at the same time. Which is also what seems to be the case here, the [PR for fixing this](https://github.com/atom/atom/pull/12545) makes changes to the `application:remove-project-folder` command in addition to the `applcation:add-project-folder` command.

Please correct me if there is something that I am misunderstanding about your report that would invalidate what I said above!
