### ISSUE TITLE
Uncaught Error: spawn /usr/share/atom/atom (deleted) ENOENT

### ISSUE THREAD

**Issue by mfisher31** [atom/atom#5871] opened 2015-03-05 20:50 UTC
This is happening after a fresh install:
I am running Debian 8

[Enter steps to reproduce below:]

1. Installed deb file atom-amd64.deb  v0.186.0
2. Run the Program

**Atom Version**: 0.184.0
**System**: linux 3.12-1-amd64
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /usr/share/atom/atom (deleted) ENOENT

```
At events.js:94

Error: spawn /usr/share/atom/atom (deleted) ENOENT
    at exports._errnoException (util.js:753:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
    at child_process.js:1142:20
    at process._tickCallback (node.js:364:11)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-clang",
      "web-browser",
      "deprecation-cop"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
html2haml, v0.6.0
language-haml, v0.15.0
linter, v0.12.0
linter-clang, v2.25.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-05 21:55
Duplicate of #4505, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-05 21:55 UTC
