### ISSUE TITLE
deleting file from tree doesn't actually delete file. no notification either

### ISSUE THREAD

**Issue by ahnbizcad** [atom/atom#10693] opened 2016-02-04 23:32 UTC
deleting file from tree doesn't actually delete file. no notification of failure either.

**Comment by 50Wliu** [comment] 2016-02-04 23:44
Hi @ahnbizcad, what operating system are you on?

**Comment by gansai** [comment] 2016-02-05 07:10
Using Windows 7. I am also able to reproduce this. 
For example, if a folder is listed in tree-view. 
And I select it -> context menu opens.
I select delete. It shows a confirmation dialog for moving to trash. 
I select Move to Trash.

But, the folder is not deleted.

**Comment by JigneshRaval** [comment] 2016-02-05 10:21
Hi, I am facing the same issue in Windows 7 with Atom v1.4.3.

Click on file from left panel and hit Del key, but it can not delete the file or using right click > delete

Thank you,

**Comment by 50Wliu** [comment] 2016-02-05 15:29
This is a duplicate of atom/tree-view#666 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-05 15:29 UTC
Labels: more-information-needed

**Comment by demhydraz** [comment] 2016-02-05 16:41
That's one hell of an issue. *ba dum tss*
