### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.23.1\res...

### ISSUE THREAD

**Issue by R3C0Nx00** [atom/atom#16377] opened 2017-12-14 00:46 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\faggy\AppData\Local\atom\app-1.23.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\faggy\AppData\Local\atom\app-1.23.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.23.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -1:21.3.0 core:close (input.hidden-input)
     -1:11.4.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:42.9.0 core:close (input.hidden-input)
     -0:09.6.0 core:undo (input.hidden-input)
     -0:08.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-html-preview 0.2.2 
atom-jade 0.3.0 
dash-syntax 0.4.1 
dash-ui 0.4.3 
jade-beautify 0.1.5 
language-pug 0.0.21 
teletype 0.1.2 
```

**Comment by Mrzzchao** [comment] 2017-12-14 02:23
i have the same problem after updating to version 1.23.1

**Comment by Shaya-pnc** [comment] 2017-12-14 07:25
Getting this error on every key type on Atom, which makes it unusable. 
V-1.23.1, Win10

**Comment by Awesomelotad** [comment] 2017-12-14 08:00
Yep, after latest windows update (perhaps? That's the only thing that's changed on my end) every key-press fires that error.

**Comment by copelandhouse2** [comment] 2017-12-14 17:50
I have this error as well.

**Comment by rsese** [comment] 2017-12-14 18:55
I think this is a duplicate of issues like #15722. If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled. If you don't have any anti-virus software running, let me know and we'll re-open.

**Closed by rsese** 2017-12-14 18:55 UTC
