### ISSUE TITLE
Right click menu not showing on taller 2nd monitor

### ISSUE THREAD

**Issue by itsmoirob** [atom/atom#7385] opened 2015-06-23 13:46 UTC
Using Windows and 0.211.0

I have a second monitor, if I position my "Atom" monitor to the right and higher than other monitor and use FILE or right click options, the right click menu doesnt appear.

If I position my monitors at the same height, when I right click, hit FILE, the right click menu appears on the second monitor.

While the "Atom" monitor is to the right and higher than the other monitor, Atom attempts to display the right click menu in a space that doesnt exist, meaning I cannot see it. 

How to fix this, make it so that any right clicking or pressing of the FILE button doesnt extend outside of the Atom window.
What is weird si that if you put Atom in window mode and right click/hit FILE, the menu appears inside the Atom window. Just when in maximise window mode, right click/FILE will go off screen

**Comment by izuzak** [comment] 2015-06-23 14:38
I believe this is a duplicate of https://github.com/atom/atom/issues/3415. Please let me know if I misunderstood your report.

**Closed by izuzak** 2015-06-23 14:38 UTC
