### ISSUE TITLE
.php Files recognized as HTML

### ISSUE THREAD

**Issue by Dogacel** [atom/atom#8485] opened 2015-08-23 10:21 UTC
When i have a php file that only has 
```php
<?php ?>
```
code in it, it's syntax is recognized as php.
But when i have a php file with html tags in it, Atom recognizes it as a html file, but it's extension is php. And that causes Gray syntax on php code.
like this
```html
<p> Your name is : <?php echo $_SESSION['name']; ?> <p>
```
But it should show up like this:
```php
<p> Your name is : <?php echo $_SESSION['name']; ?> <p>
```
( Thanks to github's syntax coloring , start p and end p's color doesn't match too :/ , sorry for my english)

**Comment by mnquintana** [comment] 2015-08-23 11:56
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/2734 though - closing this out in favor of that issue.

**Closed by mnquintana** 2015-08-23 11:56 UTC
