### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Apple/Downloads/Atom.app'

### ISSUE THREAD

**Issue by petroslee** [atom/atom#9885] opened 2015-12-01 03:11 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Apple/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/Apple/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/Apple/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Apple/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Users/Apple/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```

### Commands

```
  2x -4:58.4.0 tree-view:remove-project-folder (div.header.list-item)
     -3:01.3.0 window:install-shell-commands (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 22x -2:26.8.0 core:move-up (ul.list-inline.tab-bar.inset-panel)
     -0:35.4.0 tree-view:remove-project-folder (div.header.list-item)
     -0:00.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-01 03:13
This is a duplicate of #9559 and #7399 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-01 03:13 UTC
