### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -3, expected to pop -95.

### ISSUE THREAD

**Issue by ue5963** [atom/atom#7028] opened 2015-05-30 14:30 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -3, expected to pop -95.

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:755

Error: Encountered an invalid scope end id. Popped -3, expected to pop -95.
    at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:573:21)
    at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:555:21)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:369:113)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:624:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:789:16)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:753:14)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1136:26)
    at TextEditor.module.exports.TextEditor.moveLineUp (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:793:19)
```

### Commands

```
     -1:26.3.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:24.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -1:22.4.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:20.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:20 core:move-right (atom-text-editor.editor.is-focused)
     -1:19.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:19.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:18.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:11.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:07.3.0 editor:newline (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:53.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:46.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.1.0 core:paste (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:10.4.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:02.7.0 editor:move-line-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "atom-color-highlight"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 11,
    "showIndentGuide": true,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-yamljson, v0.2.3
autocomplete-paths, v1.0.2
color-picker, v1.6.0
local-server-express, v0.3.1
show-ideographic-space, v0.1.7

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-01 18:47
Thanks for the report, @ue5963 -- I think this is a duplicate of https://github.com/atom/atom/issues/7012. /cc @nathansobo to double-check

**Closed by izuzak** 2015-06-01 18:47 UTC

**Comment by nathansobo** [comment] 2015-06-01 19:39
@izuzak This is an assertion that can fail in a variety of cases. I *hope* I got the last one in #7012 but I might not have. Even so, might make sense to keep this closed and see if any more crop up after the release.

@ue5963 What language were you editing at the time?
