### ISSUE TITLE
Atom 1.4.0 is installed in the future on Windows 8.1

### ISSUE THREAD

**Issue by Fumble** [atom/atom#10539] opened 2016-01-21 13:27 UTC
I installed Atom 1.4.0 some days ago and today, when I opened the "Uninstall programs" window, I noticed that Atom is has been installed on June 15th 2016.

This is quite akward to have a software installed in the future.
The installation dates of the other softwares are OK.

Screenshot:
![atom_future](https://cloud.githubusercontent.com/assets/634461/12481660/ed6ed586-c04a-11e5-9f39-3d6622a9cd71.png)

Configuration: French version of Windows 8.1 Enterprise 64 bits

**Comment by mnquintana** [comment] 2016-01-21 13:32
Thanks for the report! :smile: This looks like a duplicate of https://github.com/atom/atom/issues/6606 – feel free to subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) for a guide on reporting bugs, including searching for duplicates.

**Closed by mnquintana** 2016-01-21 13:32 UTC
