### ISSUE TITLE
Req. for enhancement: Project manager which is NOT a directory listing.

### ISSUE THREAD

**Issue by BugZappr** [atom/atom#13040] opened 2016-10-21 00:48 UTC
I am using Notepad++ currently, and I prefer the Workspace/Project management it uses (View|Workspace|Workspace Panel1). In it you add files individually to a project. More than occasionally, I have files in a project which are no longer in use, are alternate versions which I did not bother to make a branch for, might be notes I took or are example code. Directory listing-based project managers generally have no easy way to exclude these files. I'd rather use the model that I ADD the files which ARE in a project, instead of SUBTRACTING files which are not. (It also has a new feature, "Folder as Workspace", thereby giving users the choice). It is easy enough, after all, to multi-select files which are. Ideally, one might be able to right-click on a file's tab, and choose "Add to project". I imagine it might be a plug-in for those who prefer not to work that way (well, nearly all of Atom is plugins), but if there is a plug-in that comes close to this for me to post an issue on, I do not know what it is.

Of the usual features I first look for in evaluating a new text editor, this is the principle one which Atom does not seem to have. (Spell-checking might ignore keywords; but this is not a stopper for me. This is impressive for such a new editor, BTW.)

Note: This is not a question, but an enhancement request.  Also note that in Notepad++, this is part of the core, so this is not necessarily about a "package"; or to state it more accurately, this is not necessarily about a non-core package - although I don't propose by any means for it to be the only official form of project management either.

One great feature this project manager might have, is to create a project from a git or hg repository.  After all, one is not forced to add directories in Git or Hg; and when one does, and then add new files, they are not automatically part of the repository.  Why shouldn't a text editor have a project manager work that way?  I am keen to get Atom started on this early on.  Netbeans is a mature text editor, and does not have this; but it is not uncommon either.

**Comment by lee-dohm** [comment] 2016-10-21 02:02
As I mentioned on your original Issue, this is a duplicate of https://github.com/atom/tree-view/issues/854. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-10-21 02:02 UTC

**Comment by BugZappr** [comment] 2016-10-21 03:12
My bad.  I seem to have missed that.
