### ISSUE TITLE
Issue adding second root folder that is inside a VCS ignored path

### ISSUE THREAD

**Issue by brianwestphal** [atom/atom#5965] opened 2015-03-14 00:39 UTC
Given directories like:
* my-project
  * node-modules
    * my-library
where node-modules is a VCS ignored path

I cannot easily create a workspace with my-project and my-library as root folders.

Here's what works:
I can open my-library in a window and then add another root folder: my-project

Here's what doesn't work:
I can't open my-project in a window and then add another root folder: my-library (because this just does nothing)

Atom: 0.187.0

**Comment by 50Wliu** [comment] 2015-03-14 00:55
Duplicate of atom/tree-view#404.

**Closed by 50Wliu** 2015-03-14 00:55 UTC
