### ISSUE TITLE
Setting don't save

### ISSUE THREAD

**Issue by jdantzler** [atom/atom#19094] opened 2019-04-02 18:55 UTC
### Description

Every time I open atom my settings do not save.  For example when atom launches I am presented with a Welcome Guide. I unchecked the"Show Welcome Guide when opening Atom".   When I close atom and relaunch it the welcome guide is still there and the box is checked again.  Also, If I go into settings and change the default font size from 14 to 12 and close and reopen atom the font size has change back to 12.  No matter what settings I change it always reverts back to the defaults.  I can't figure out how to actually get these settings to stay so I believe this is a bug.

### Steps to Reproduce

1. Launch Atom
2. Uncheck the "Show Welcome Guide when opening Atom"
3.  Close and Relaunch Atom
4. Welcome guide appears with the check box even though it shouldn't
5. You can also repeat this process and change the default font size form 14 to 12 as well and it will revert back.

**Expected behavior:** I expect when Atom is relaunched after unchecking the box the welcome guide is no longer displayed and all my other settings have remained too such as my font size.

**Actual behavior:** The Welcome guide appears again with the box checked and the font size has revert back from 12 to 14.

**Reproduces how often:** 100% of the time.

### Versions

Atom Version: 1.35.1
Windows 10 Build 1703 x64

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2019-04-02 23:21
Thanks for the report!  It looks like the `Prerequisites` section was removed - can you confirm if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

I was unable to reproduce with 1.35.1 on Windows 10.

**Comment by jdantzler** [comment] 2019-04-03 14:04
> Thanks for the report! It looks like the `Prerequisites` section was removed - can you confirm if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
> 
> I was unable to reproduce with 1.35.1 on Windows 10.

Yes it still happens in safe mode too unfortunately.  Any ideas?  Thanks.

**Comment by rsese** [comment] 2019-04-03 22:49
Hmm, is this just your local computer at home or a computer in a university or similar setting where your computer is managed by your IT department?

Do you see any console errors when you adjust any settings?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools

**Comment by jdantzler** [comment] 2019-04-08 17:15
It is managed by IT so it is probably something they are blocking or preventing I guess.  I went ahead and checked the console and there is no errors or anything showing up in it.  Thanks for your help.

**Comment by rsese** [comment] 2019-04-09 05:03
Ahhh ok, it seems like that could be at least related - Atom's settings are stored in a file ([`config.cson`](https://flight-manual.atom.io/using-atom/sections/basic-customization/#global-configuration-settings)) in your Atom home directory which is by default located in the home directory for your OS.  I wonder if there's some policy interfering with saving files there?

One thing you can try is to set `ATOM_HOME` to a directory where you know there's no issues saving:

https://flight-manual.atom.io/using-atom/sections/basic-customization/#controlling-where-customization-is-stored-to-simplify-your-workflow

Since this seems like an issue not specific to Atom we'll go ahead and close this out but feel free to reach out on our message board if you'd like: https://discuss.atom.io/.  Also feel free to @ mention me there.

**Closed by rsese** 2019-04-09 05:03 UTC

**Comment by rsese** [comment] 2019-04-10 00:19
Hmm, is your config file set to read-only?  Can you edit it in some other application like Notepad or Wordpad?  Not sure if Notepad++ has some specific functionality that lets you edit read-only files.
