### ISSUE TITLE
racer.racerBinPath is not set in your config.

### ISSUE THREAD

**Issue by JakeEhrlich** [atom/atom#11091] opened 2016-03-07 20:22 UTC
1. Install rust language "racer" package for code completion
2. open a .rs file and start editing

**Atom Version**: 1.5.4
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

racer.racerBinPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -3:11.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:24.6.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:11 tree-view:remove (span.name.icon.icon-file-directory)
     -2:05.3.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -1:50.8.0 editor:newline (atom-text-editor.editor.is-focused)
 15x -1:39.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:27.6.0 core:backspace (atom-text-editor.editor.is-focused)
 13x -0:16.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:03.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-hdevtools",
      "helium",
      "haskell-hoogle",
      "haskell-pointfree",
      "linter",
      "linter-hlint",
      "autocomplete-haskell",
      "linter-lua-findglobals",
      "haskell-ghc-mod",
      "linter-rust",
      "language-rust",
      "build-cargo"
    ]
  },
  "editor": {
    "fontSize": 16,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-language-rust, v0.5.0
hover-tooltips-liquid, v0.8.0
language-haskell, v1.3.1
language-idris, v0.4.1
language-lua, v0.9.4
linter-liquid, v0.1.0
linter-lua, v1.0.1
minimap, v4.19.0
racer, v0.18.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2016-03-07 21:04
This looks like a duplicate of https://github.com/edubkendo/atom-racer/issues/64 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-03-07 21:04 UTC
