### ISSUE TITLE
Pressing the spacebar in 'install packages' tab scrolls the panel down

### ISSUE THREAD

**Issue by jadekler** [atom/atom#12143] opened 2016-07-11 19:57 UTC
### Prerequisites

* [y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Open atom
1. Go to preferences > install
1. Type 'foo bar'
1. See screen scroll on the space, instead of staying at the top

**Expected behavior:** [What you expected to happen]

Stay at the top

**Actual behavior:** [What actually happened]

Scroll

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Mac

```
 2016-07-11 13:10:58 ☆  |2.3.0| declerk in ~/workspace/http_sim
±  |master ✓| → atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

 2016-07-11 13:57:32 ☆  |2.3.0| declerk in ~/workspace/http_sim
±  |master U:2 ✗| → apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4
```

**Comment by aseom** [comment] 2016-07-11 20:33
Same for me... (OS X 10.10)
```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by edwinksl** [comment] 2016-07-11 23:52
Same bug on Atom Beta 1.9.0 on Ubuntu 16.04:

```
$ atom-beta -v
Atom    : 1.9.0-beta0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by lee-dohm** [comment] 2016-07-12 06:41
This is a duplicate of https://github.com/atom/settings-view/issues/767. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-12 06:41 UTC

**Comment by lee-dohm** [comment] 2016-07-12 06:42
Also, please do follow the template and check to ensure that you're posting an Issue to the correct repository.
