### ISSUE TITLE
Uncaught Can't find DashboardController file

### ISSUE THREAD

**Issue by Specialist001** [atom/atom#18912] opened 2019-02-26 10:40 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find DashboardController file

```
At C:\Users\ES1-512-C2DP\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

undefined
```

### Commands

```
     -0:48.9.0 core:backspace (input.hidden-input)
     -0:48.6.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:48.6.0 editor:newline (input.hidden-input)
     -0:47.5.0 core:move-up (input.hidden-input)
  2x -0:46.6.0 core:undo (input.hidden-input)
  2x -0:44.1.0 core:backspace (input.hidden-input)
     -0:42.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:42.1.0 core:move-left (input.hidden-input)
  2x -0:41.3.0 core:move-right (input.hidden-input)
     -0:39.9.0 core:move-left (input.hidden-input)
  2x -0:39.5.0 core:select-left (input.hidden-input)
  2x -0:36.8.0 core:move-right (input.hidden-input)
     -0:36 core:move-left (input.hidden-input)
     -0:34.9.0 editor:select-to-beginning-of-word (input.hidden-input)
  2x -0:33.8.0 emmet:encode-decode-data-url (input.hidden-input)
  2x -0:04.7.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
autosave-onchange 1.5.1 
emmet 2.4.3 
goto-definition 1.3.4 
language-blade 0.41.4 
laravel 0.7.1 
platformio-ide-terminal 2.9.1 
```

**Comment by rsese** [comment] 2019-02-26 18:51
Thanks for contributing!

We noticed that this looks like a duplicate of issues like https://github.com/atom/atom/issues/18429 where it seems like the problem was narrowed down to https://atom.io/packages/emmet (/cc https://github.com/atom/atom/issues/18429#issuecomment-439216378).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-26 18:51 UTC
