### ISSUE TITLE
Can't install/update Atom on Windows

### ISSUE THREAD

**Issue by inosik** [atom/atom#8930] opened 2015-09-24 19:17 UTC
I had a working v1.0.7 of Atom, which couldn't update to later versions due to `PathTooLongException`s. So I uninstalled it completely and tried to re-install v1.0.15, which failed.

I tried again today with v1.0.9, but had no luck. This is the log of the installer:
```
2015-09-24 16:16:50> Program: Starting Squirrel Updater: --install .
2015-09-24 16:16:50> Program: Starting install, writing to d:\profiles\my_name\Lokale Einstellungen\Anwendungsdaten\SquirrelTemp
2015-09-24 16:16:50> Program: About to install to: d:\profiles\my_name\Lokale Einstellungen\Anwendungsdaten\atom
2015-09-24 16:16:50> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Ein Teil des Pfades "d:\profiles\my_name\Lokale Einstellungen\Anwendungsdaten\atom\packages\RELEASES" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   bei Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3a.MoveNext()
2015-09-24 16:16:50> CheckForUpdateImpl: Reading RELEASES file from d:\profiles\my_name\Lokale Einstellungen\Anwendungsdaten\SquirrelTemp
2015-09-24 16:16:50> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-09-24 16:16:50> ApplyReleasesImpl: Writing files to app directory: d:\profiles\my_name\Lokale Einstellungen\Anwendungsdaten\atom\app-1.0.9
2015-09-24 16:17:02> IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
   bei System.IO.PathHelper.GetFullPathName()
   bei System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   bei System.IO.Path.GetFullPathInternal(String path)
   bei System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   bei System.IO.FileInfo..ctor(String fileName)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass9f.<installPackageToAppDir>b__9b(IPackageFile x)
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass9f.<installPackageToAppDir>b__9a()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__a1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
2015-09-24 16:17:02> Unhandled exception: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
   bei System.IO.PathHelper.GetFullPathName()
   bei System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   bei System.IO.Path.GetFullPathInternal(String path)
   bei System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   bei System.IO.FileInfo..ctor(String fileName)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass9f.<installPackageToAppDir>b__9b(IPackageFile x)
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass9f.<installPackageToAppDir>b__9a()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__a1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__70.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Update.Program.<Install>d__31.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei System.Threading.Tasks.Task.Wait()
   bei Squirrel.Update.Program.executeCommandLine(String[] args)
   bei Squirrel.Update.Program.main(String[] args)
---> (Interne Ausnahme #0) System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.
   bei System.IO.PathHelper.GetFullPathName()
   bei System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   bei System.IO.Path.GetFullPathInternal(String path)
   bei System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   bei System.IO.FileInfo..ctor(String fileName)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass9f.<installPackageToAppDir>b__9b(IPackageFile x)
   bei System.Collections.Generic.List`1.ForEach(Action`1 action)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass9f.<installPackageToAppDir>b__9a()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__a1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__70.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Squirrel.Update.Program.<Install>d__31.MoveNext()<---
 ```

So I end up with an half-installed Atom and a non-working "Open with Atom".
This happens at my machine at work with Windows 7 64 Bit.

**Comment by 50Wliu** [comment] 2015-09-25 01:05
Duplicate of #5109, please subscribe there for updates.

**Closed by 50Wliu** 2015-09-25 01:05 UTC
