### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by bitverdreher** [atom/atom#7533] opened 2015-06-29 08:23 UTC
1. right click on folder or file

**Atom Version**: 1.0.0
**System**: Win 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\User\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -4:24.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:20.1.0 autoflow:reflow-selection (atom-text-editor.editor.is-focused)
     -4:13.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:12.1.0 core:save (atom-text-editor.editor.is-focused)
     -4:10.3.0 core:close (atom-text-editor.editor.is-focused)
     -4:06.7.0 core:copy (atom-text-editor.editor.is-focused)
     -4:04.4.0 core:paste (atom-text-editor.editor.is-focused)
     -4:03.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:02.5.0 core:save (atom-text-editor.editor.is-focused)
     -3:57 core:paste (atom-text-editor.editor.is-focused)
  2x -3:56.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:55.5.0 core:save (atom-text-editor.editor.is-focused)
     -3:49.6.0 core:paste (atom-text-editor.editor.is-focused)
  2x -3:49.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:48 core:save (atom-text-editor.editor.is-focused)
  4x -3:45.3.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
less-autocompile, v1.0.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-29 09:01
This is a duplicate of #6548, so closing this in favor of that issue.

**Closed by izuzak** 2015-06-29 09:01 UTC
