### ISSUE TITLE
Atom crash when update to 1.28 and 1.28.1

### ISSUE THREAD

**Issue by cage1618** [atom/atom#17638] opened 2018-07-06 03:56 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Atom crash when update to 1.28 and 1.28.1. My os is macos 10.13.5.

I tried use atom --safe and atom --clear-window-state but still not work.
[Description of the issue]

### Steps to Reproduce
1.update atom to 1.28 or 1.28.1 on macos 10.13.5
2.open atom

**Expected behavior:** [What you expect to happen]
no crash

**Actual behavior:** [What actually happens]
![image](https://user-images.githubusercontent.com/2541448/42359296-939495e6-8113-11e8-98ee-c8d5b544ee67.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
everytime

### Versions
1.28 & 1.28.1

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by pkgodara** [comment] 2018-07-06 11:19
Same problem for me. Crashing and Actually it didn't even auto restart after I clicked for **restart and install** for both 1.28 and 1.28.1 updates.

Error: https://ideone.com/qA5cb6

**Comment by mrbjjackson** [comment] 2018-07-06 11:40
Yes I'm getting the same crashing behaviour.

Here is my error message:

![screen shot 2018-07-06 at 12 39 44](https://user-images.githubusercontent.com/1610988/42377091-b5a1d27e-8119-11e8-9fb1-2e0a61e2bc27.png)

I thought this may be an OSX version issue (I'm still on 10.9.5) but the documentation says that Atom is supported from OSX 10.9 and above so perhaps not.

Apologies if this is a different issue but it sounds similar.

**Comment by pkgodara** [comment] 2018-07-06 13:19
Now, if I restart, it froze my Mac. You can see memory stats: 
There are numerous **Atom Helper** processes each consuming approx 500mb.

<img width="737" alt="screen shot 2018-07-06 at 6 39 07 pm" src="https://user-images.githubusercontent.com/16938349/42380924-1f0d52f0-814d-11e8-960a-972cc1ee74b3.png">

**Comment by gcoderre** [comment] 2018-07-06 17:33
Same here with all community packages disabled

**Comment by rsese** [comment] 2018-07-06 17:33
@cage1618 @pkgodara - are either of you using a network proxy?

@mrbjjackson - are you on Atom 1.28.0?  If so I think you're hitting https://github.com/atom/atom/issues/17565 which has been fixed in 1.28.1.

**Comment by pkgodara** [comment] 2018-07-06 17:38
@rsese No network proxy.

**Comment by cage1618** [comment] 2018-07-07 03:14
It is ok when I turn off network proxy

**Comment by pkgodara** [comment] 2018-07-07 03:19
@rsese running fine in safe mode.

**Comment by 50Wliu** [comment] 2018-07-07 22:10
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.

**Closed by 50Wliu** 2018-07-07 22:10 UTC
Labels: crash, more-information-needed
