### ISSUE TITLE
'ebase-merge' is not recognized...' when doing interactive rebase with atom

### ISSUE THREAD

**Issue by alicanb** [atom/atom#12032] opened 2016-06-22 22:57 UTC
### Description

When I try to do an interactive rebase with atom, atom screen doesn't show up and error message is shown (see actual behavior). [This](http://stackoverflow.com/questions/37573298/git-rebase-fails-with-ebase-merge-is-not-recognized) is the only link I could find relevant to the issue. If I unset atom as core editor, I can successfully rebase with vim. @lee-dohm 

### Steps to Reproduce (approximately)
1. [Install git & atom, clone a repo, make atom core editor]
2. exact command I used was ```git rebase -i origin/master~3 master```

**Expected behavior:** atom to open

**Actual behavior:** error message is shown:
```
'ebase-merge' is not recognized as an internal or external command,
operable program or batch file.
```
### Versions
atom 1.8.0
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.9.0.windows.1
visual studio 2013

**Comment by thomasjo** [comment] 2016-06-23 07:37
Judging from the error message, this is not a bug in Atom. The error you are seeing is coming directly from the Windows shell.

Since we are trying to minimize [the deluge of open issues](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), I'm going to close this issue. However, I will try to assist you in getting the problem resolved via this issue if you want. But I would highly recommend that you [join us on Slack](https://discuss.atom.io/t/join-us-on-slack/16638) instead.

If you prefer to keep going here, please share your Git config, or at least the output of
`git config --global core.editor`. Thanks! 🙇

**Closed by thomasjo** 2016-06-23 07:37 UTC

**Comment by lee-dohm** [comment] 2016-06-23 15:12
Git config (pasted from Slack):

```
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
credential.helper=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
user.name=Alican Bozkurt
user.email=alican@ece.neu.edu
merge.tool=kdiff3
diff.guitool=kdiff3
core.autocrlf=true
core.excludesfile=C:/Users/Alican/.gitignore_global
core.editor=atom --wait
push.default=simple
alias.lol=log --oneline --graph --decorate --all
alias.co=commit -m
alias.pu=push -u origin
gui.recentrepo=D:/Documents/MATLAB/JSTSP
gui.recentrepo=D:/Documents/MATLAB/SC Paper
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/Microsoft/monaco-editor.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

**Comment by lee-dohm** [comment] 2016-06-24 00:12
Sorry I wasn't able to follow up on this today ... some family stuff went down. I'll be on it tomorrow.

**Comment by alicanb** [comment] 2016-06-24 15:06
Solved it using the solution provided in #12027

**Comment by kevinkuszyk** [comment] 2016-07-07 08:04
For future Googlers, on Atom 1.8.0 my `atom.cmd` in `%localappdata%\atom\app-1.8.0\resources\cli` was already the same as the one at https://github.com/atom/atom/blob/master/resources/win.

The fix for me was changing my git config to this:

```
git config --global core.editor "'%localappdata%\atom\bin\atom.cmd' --wait"
```

**Comment by jareiko** [comment] 2016-07-07 18:37
The above command didn't work for me on Windows 8.1, but this one did:

    git config --global core.editor "atom.cmd --wait"
