### ISSUE TITLE
Uncaught Error: spawn /usr/share/atom/atom (deleted) ENOENT

### ISSUE THREAD

**Issue by gopiariv** [atom/atom#4824] opened 2015-01-01 23:41 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.13.0-40-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /usr/share/atom/atom (deleted) ENOENT

```
At events.js:85

Error: spawn /usr/share/atom/atom (deleted) ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
```

### Config

```
{
  "core": {},
  "editor": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-01-02 19:56
This looks like a duplicate of https://github.com/atom/atom/issues/4505 (so I'm closing this in favor of that issue). Can you try the suggestion from https://github.com/atom/atom/issues/4505#issuecomment-66795073?

**Closed by izuzak** 2015-01-02 19:56 UTC
