### ISSUE TITLE
deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by Spy-Seth** [atom/atom#9629] opened 2015-11-16 14:50 UTC
Since the last Atom update when I run beautify I get a deprecation error and the beautify do not happen:

![screenshot 2015-11-16 11 19 23](https://cloud.githubusercontent.com/assets/95120/11179551/77be80e0-8c54-11e5-9901-cfa57b746a04.png)

Sorry for the screenshot: I cannot copy/past the text.

**Comment by 50Wliu** [comment] 2015-11-16 14:53
I *think* this is a duplicate of #9350, since it's the same error.

**Closed by 50Wliu** 2015-11-16 14:53 UTC
