### ISSUE TITLE
Don't check for updates after having checked for updates

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#7952] opened 2015-07-18 01:19 UTC
When I'm notified of package updates in the bottom right corner, it's always an anti-climax to click it and see a "Checking for updates..." hourglass appear.

If Atom has already checked for updates and it *knows* there are and X number of package updates, just show those package updates straight away without checking again and making the user wait needlessly.

**Comment by mnquintana** [comment] 2015-07-18 01:22
Thanks for the suggestion! This is a duplicate of https://github.com/atom/settings-view/issues/409 – please subscribe there for updates.

**Comment by adambuczynski** [comment] 2015-07-18 01:23
Thanks, you're right, I missed that one when searching for existing issues.

**Closed by mnquintana** 2015-07-18 01:22 UTC
