### ISSUE TITLE
Unable to Command A (Select All) In Save New File Dialog [OS X]

### ISSUE THREAD

**Issue by bobber205** [atom/atom#15922] opened 2017-10-17 20:02 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Not able to select all to rename a file. -- I have to move cursor to end of "Untitled" then delete manually.

### Steps to Reproduce
Open new file
Type Something
Press Command S 
Untitled Appears
Press Command A -- get an error beep 

I've never experienced not being able to do Command-A/C/V in a file saving dialog before.

**Comment by rsese** [comment] 2017-10-17 22:30
Thanks for taking the time to contribute!

This looks like a duplicate of https://github.com/atom/atom/issues/14145 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-17 22:30 UTC
