### ISSUE TITLE
Use shared system buffer on CMD+E

### ISSUE THREAD

**Issue by elado** [atom/atom#13897] opened 2017-02-28 17:34 UTC
In most native apps on mac, CMD+E puts the selected text in a special buffer which is shared between all apps. While in Atom CMD+E puts the selected text in the find input, it is not shared with other apps or between multiple Atom windows.

This behavior works in Sublime, Chrome, iTerm etc.

Steps to reach the behavior on Sublime:

1. Select some text
2. Hit CMD+E
3. Switch to Chrome/iTerm/Other Sublime window
4. Hit CMD+F
5. The text from Sublime will appear in the input

**Comment by rsese** [comment] 2017-02-28 18:48
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/4650. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-02-28 18:48 UTC
