### ISSUE TITLE
Remove Spyware features please

### ISSUE THREAD

**Issue by cyphunk** [atom/atom#5669] opened 2015-02-21 22:54 UTC
You can only avoid having your constant call backs to google analytics or atom.io servers described as something other than spyware when you ask the user first if they would like you to turn on these features.

Your access to google analytics should only be enabled with the "send anonymous statistics to improve product" button, as most half decent non-spyware applications do.

Your access to atom.io to check for updates should only be enabled with the "automatically check for updates on startup" button, as is done by most reasonably sane applications.

Asking users to edit your *coffee script* in order to disable is not a valid response.

**Comment by 50Wliu** [comment] 2015-02-21 23:00
For the first part of your question (about Metrics), please see [this comment](https://github.com/atom/metrics/issues/16#issuecomment-36307675) for why it is currently enabled by default.

In addition, the installer that Atom is currently using is also in beta, and I don't believe it has a UI that allows you to check/uncheck certain features yet (@paulcbetts, can you confirm?).

**Comment by cyphunk** [comment] 2015-02-21 23:23
Beta, aha. Well if beta is the excuse make sure the installer has a glaring warning explaining that "metrics will be collected" and asking the user to give their "ok" before continuing installation. Or add an option in the preferences to turn this option off

**Comment by 50Wliu** [comment] 2015-02-21 23:27
There is at least an option in Settings (albeit a bit hard to find, but that's another issue that's being tracked).  Settings (<kbd>Ctrl</kbd>+<kbd>,</kbd>)-->Packages-->Metrics-->Disable.

In addition, the first file that gets shown when Atom is first installed (`Welcome.md`) contains a notice warning you about Metrics, but not about auto-updates (at least I don't think so).

**Comment by mark-hahn** [comment] 2015-02-21 23:34
BTW, Atom metrics do not fit the definition of spyware.  From wikipedia ...

"*Spyware* is software <http://en.wikipedia.org/wiki/Software> that aids in
gathering information about a person or organization without their
knowledge and that may send such information to another entity without the
consumer's consent, or that asserts control over a computer without the
consumer's knowledge".

It does not fit "without their knowledge" or "without the consumer's consent
".

**Comment by cyphunk** [comment] 2015-02-21 23:53
It absolutely fits the definition of without their knowledge and without their consent. There is no request that the user allow this and no clear information given to the user that this is happening.

**Comment by mark-hahn** [comment] 2015-02-21 23:56
> no clear information given to the user that this is happening.

For some reason I was well aware of it when I first found Atom but I don't
remember why.  I thought I learned it from the docs.

**Comment by cyphunk** [comment] 2015-02-21 23:58
@50Wliu indeed welcome.md has as its verify first item a description of metrics gathering. So at least the user might be informed. But it seems to me that there is no future in sight of when this will not be the default and placing this information amongst a slew of other details makes it easy to ignore. It should simply be off by default. Or very easy to turn off during install. It's just horrible manners, no matter if it is "beta", be that an infinite beta or one that only lasts a few months.

**Comment by mark-hahn** [comment] 2015-02-22 00:01
>  It's just horrible manners

According to whom?  Manners are defined by social convention and almost
every website collects metrics.  You are projecting your own convention
(and hacker news') on everyone else.

**Comment by cyphunk** [comment] 2015-02-22 00:08
Yes, I'm projecting my convention. That's how feedback and criticism often works. I hope the developers of this product at Github make note of it and choose to improve the privacy awareness of their product.

**Comment by mark-hahn** [comment] 2015-02-22 00:13
> That's how feedback and criticism often works.

Definitely.  I was just objecting to the use of the word "manners".  It is
a bit of a slur.  But I understand you care a lot about this and
exaggerate. I have flamed much worse on this very board.

**Comment by paulcbetts** [comment] 2015-02-22 01:20
@50Wliu Squirrel does no automated checking of its own in Atom, the code in atom/atom explicitly invokes it on a timer (i.e. it controls update policy). Squirrel will indeed not (nor will it ever) add options in the installer.

**Comment by mnquintana** [comment] 2015-06-28 12:19
Closing as duplicate of https://github.com/atom/atom/issues/4966

**Closed by mnquintana** 2015-06-28 12:19 UTC
Labels: question
