### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `textNodes` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by amarinelli** [atom/atom#17643] opened 2018-07-06 20:04 UTC
### Reproduction steps:

1. Collapsing function definitions in .js file.

- This error happened at the same time as I experienced #17482 
- Restarted Atom and was able to reproduce after collapsing a few more function definitions.  Always hit #17482 first, and then this new TypeError.
- I **was** able to reproduce in safe mode

**Atom**: 1.28.1 ia32
**Electron**: 2.0.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot destructure property `textNodes` of 'undefined' or 'null'.

```
At C:\Users\Adam Marinelli\AppData\Local\atom\app-1.28.1\resources\app\src\text-editor-component.js:2406

TypeError: Cannot destructure property `textNodes` of 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.28.1/resources/app/src/text-editor-component.js:2406:65)
    at TextEditorComponent.screenPositionForMouseEvent (~/AppData/Local/atom/app-1.28.1/resources/app/src/text-editor-component.js:1971:23)
    at TextEditorComponent.didMouseDownOnLineNumberGutter (~/AppData/Local/atom/app-1.28.1/resources/app/src/text-editor-component.js:1844:41)
    at LineNumberGutterComponent.didMouseDown (~/AppData/Local/atom/app-1.28.1/resources/app/src/text-editor-component.js:3364:36)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
highlight-selected 0.13.1 
linter-solidity 0.5.0 
minimap 4.29.8 
```

**Comment by Ben3eeE** [comment] 2018-07-06 20:38
@amarinelli I would say this is a duplicate of the issue you referenced. Since you saw that first. And that this happens because #17482 puts you in an invalid state.

If you could post a gif or screencap of hitting the first issue or sharing the code your were trying to collapse in #17482 that would be very helpful to us to narrow this down 🙇

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17482. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-07-06 20:38 UTC
Labels: duplicate
