### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/home/jeff/repos/crud/package.json'

### ISSUE THREAD

**Issue by jeffdavidthompson** [atom/atom#6046] opened 2015-03-20 07:06 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.16.0-31-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES, permission denied '/home/jeff/repos/crud/package.json'

```
At /opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:329

Error: EACCES, permission denied '/home/jeff/repos/crud/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:503:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1116:15)
    at Object.fsPlus.writeFileSync (/opt/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:243:17)
    at File.module.exports.File.writeFileSync (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:245:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:315:21)
    at File.module.exports.File.write (/opt/atom/resources/app/node_modules/pathwatcher/lib/file.js:304:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
    at TextBuffer.module.exports.TextBuffer.save (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
seti-syntax, v0.3.3
seti-ui, v0.6.3
web-browser, v1.4.2

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-03-20 12:01
Similar to https://github.com/atom/atom/issues/5999

**Comment by kevinsawicki** [comment] 2015-03-26 21:09
@jeffdavidthompson did this occur while you were saving the editor, closing the editor, quitting Atom, something else? Thanks

**Comment by kevinsawicki** [comment] 2015-07-08 20:20
I believe this is a duplicate of #5999

**Closed by kevinsawicki** 2015-07-08 20:20 UTC
Labels: bug, error-from-save, uncaught-exception
