### ISSUE TITLE
`--wait` is not respected if atom is already open

### ISSUE THREAD

**Issue by MaxNoe** [atom/atom#9097] opened 2015-10-09 13:31 UTC
We use this command:
`git config --global core.editor "atom --wait"`
to use atom as the default git editor. 

But if another atom window is open, the `--wait` option is not respected and git just
closes with an empty commit message.

Even if we use `git config --global core.editor "atom --wait --new-window"`, it does not work.

This behaviour is on windows, on linux everything works just fine.

**Comment by mnquintana** [comment] 2015-10-09 14:31
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/3074 though - please subscribe there for updates.

**Closed by mnquintana** 2015-10-09 14:31 UTC
