### ISSUE TITLE
Windows installer won't start

### ISSUE THREAD

**Issue by sryze** [atom/atom#6343] opened 2015-04-12 10:10 UTC
I have a problem installing Atom 0.190.0 using AtomSetup.exe - it runs for a fraction of a second and exits immediately without any error message.

I managed to determine that Atom is using something called Squirrel to build the installer (is it mentioned somewhere?), so here is its SquirrelSetup.log:

```
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\szx\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\szx\AppData\Local\atom\app-0.187.0
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.187.0\atom.exe]
ApplyReleasesImpl: Starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: cleanDeadVersions: for version 0.187.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.187.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: hwhat, local version is greater than remote version
ApplyReleasesImpl: Found partially applied release folder, killing it: C:\Users\szx\AppData\Local\atom\app-0.189.0
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\apm\node_modules\npm\node_modules\fstream-npm\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\apm\node_modules\npm\node_modules\fstream-npm: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\node_modules\babel-core\node_modules\output-file-sync\node_modules\mkdirp\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\node_modules\babel-core\node_modules\output-file-sync\node_modules\mkdirp: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\node_modules\babel-core\node_modules\output-file-sync\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\node_modules\babel-core\node_modules\output-file-sync: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\node_modules\babel-core\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\node_modules\babel-core: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\apm\node_modules\npm\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\apm\node_modules\npm: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\apm\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\apm: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources\app: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0\resources: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\szx\AppData\Local\atom\app-0.189.0: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
ApplyReleasesImpl: Writing files to app directory: C:\Users\szx\AppData\Local\atom\app-0.189.0
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
ApplyReleasesImpl: Starting fixPinnedExecutables
ApplyReleasesImpl: Processing shortcut 'C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe'
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.187.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Program Files (x86)\CMake\bin\cmake-gui.exe'
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.187.0', continuing to next directory
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.190.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut ''
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.187.0', continuing to next directory
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.190.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Program Files (x86)\foobar2000\foobar2000.exe'
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.187.0', continuing to next directory
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.190.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Program Files (x86)\Mozilla Firefox\firefox.exe'
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.187.0', continuing to next directory
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.190.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Program Files (x86)\Skype\Phone\Skype.exe'
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.187.0', continuing to next directory
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.190.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe'
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.187.0', continuing to next directory
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.190.0', continuing to next directory
ApplyReleasesImpl: Processing shortcut 'C:\Users\szx\AppData\Roaming\uTorrent\uTorrent.exe'
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.187.0', continuing to next directory
ApplyReleasesImpl: Does not match 'C:\Users\szx\AppData\Local\atom\app-0.190.0', continuing to next directory
ApplyReleasesImpl: cleanDeadVersions: for version 0.190.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.190.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.190.0
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\szx\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Reading RELEASES file from C:\Users\szx\AppData\Local\SquirrelTemp
ApplyReleasesImpl: No release to install, running the app
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\szx\AppData\Local\atom\app-0.190.0\atom.exe]
```

**Comment by sryze** [comment] 2015-04-12 10:16
FYI deleting the `AppData\Local\atom` directory manually fixed this.

**Comment by izuzak** [comment] 2015-04-13 12:19
Sounds like a duplicate of https://github.com/atom/atom/issues/5767 -- just left a comment there to point to this issue. Thanks for the report.

**Closed by izuzak** 2015-04-13 12:19 UTC
