### ISSUE TITLE
Open file in current directory?

### ISSUE THREAD

**Issue by kyleabeauchamp** [atom/atom#6871] opened 2015-05-20 18:53 UTC
I'm on Ubuntu 15.04 and Atom 0.200.0.  Whenever I try to open a file via File -> Open File, I am given a file chooser in my "recent files" directory.  What I really want is to open another file from the current directory.  

Has anyone else seen this?

**Comment by 50Wliu** [comment] 2015-05-20 20:29
Duplicate of #6762, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-20 20:29 UTC
