### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1362Error: Cannot ca...

### ISSUE THREAD

**Issue by Letni1** [atom/atom#17359] opened 2018-05-18 15:40 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1362
Error: Cannot call function 'getPosition' on missing remote object 1362
    at throwRPCError (C:\Users\Max Proskurin\AppData\Local\atom\app-1.27.0\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\Max Proskurin\AppData\Local\atom\app-1.27.0\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\Users\Max Proskurin\AppData\Local\atom\app-1.27.0\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At C:\Users\Max Proskurin\AppData\Local\atom\app-1.27.0\resources\electron.asar\renderer\api\remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 1362
Error: Cannot call function 'getPosition' on missing remote object 1362
    at throwRPCError (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.27.0/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.27.0/resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.27.0/resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.27.0/resources/app/src/window-event-handler.js:191:32)
```

### Commands

```
  2x -8:39.2.0 editor:newline (input.hidden-input)
 20x -7:37.8.0 core:backspace (input.hidden-input)
     -7:35.6.0 core:undo (input.hidden-input)
 26x -7:35 core:backspace (input.hidden-input)
     -4:52.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-django 0.3.2 
atom-python-run 0.9.6 
atom-python-test 0.9.0 
atom-runner 2.7.1 
autocomplete-python 1.10.5 
base16-ocean-dark-spacegray 0.13.0 
base16-ocean-dark-syntax-theme 0.1.10 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
color-tabs 0.1.8 
django-atom 0.2.4 
django-templates 0.5.0 
docker 0.8.0 
dracula-syntax 2.0.7 
dracula-ui 0.6.0 
emmet 2.4.3 
file-icons 2.1.20 
hex-view 0.2.1 
high-street-ui 1.3.0 
Hydrogen 2.5.0 
language-django 0.1.1 
language-docker 1.1.8 
minimap 4.29.8 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nordkind-dark-syntax 0.6.0 
phantom-ui 1.0.0 
python-debugger 0.2.0 
python-indent 1.1.5 
python-tools 0.6.9 
seti-classic 0.10.3 
seti-ui 1.10.0 
spacegray-dark-ui 0.13.0 
unicorn-syntax 2.2.0 
unicorn-ui 1.2.0 
```

**Comment by rsese** [comment] 2018-05-18 18:05
Thanks for the report!

> Sorry, but no idea about what happened.

No problem, this looks like a duplicate of #16630 so you can subscribe there if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-18 18:06 UTC
