### ISSUE TITLE
Options --disable-gpu and --ignore-gpu-blacklist don't work 🤔

### ISSUE THREAD

**Issue by artkirienko** [atom/atom#18514] opened 2018-11-29 19:21 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

1. MacBook Pro (15-inch, Early 2011)
2. I'm trying to disable using High Perf. GPU.
```bash
open /Applications/Visual\ Studio\ Code.app/ --args --disable-gpu --ignore-gpu-blacklist
```
It doesn't work.

But for Google Chrome it works fine
```bash
open /Applications/Google\ Chrome.app/ --args --disable-gpu --ignore-gpu-blacklist
```

**Expected behavior:**

Use Intel HD Graphics 3000 to have low energy impact. 

**Actual behavior:**

Atom uses High Perf. AMD Radeon HD 6490M having high energy impact.

**Reproduces how often:**

100%

### Versions

atom --version
Atom    : 1.31.1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm --version
apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.1
python 2.7.15
git 2.19.2

OS: 64bit Mac OS X 10.13.6 17G3025

### Additional Information

Usual Google Chrome:
![screen shot 2018-11-29 at 21 50 53](https://user-images.githubusercontent.com/2473081/49245923-bce62700-f424-11e8-840d-235a0c11e35c.png)

Google Chrome disabled GPU:
![screen shot 2018-11-29 at 21 53 10](https://user-images.githubusercontent.com/2473081/49245964-d2f3e780-f424-11e8-85ce-a0eb5cd5eb76.png)

Trying to disable GPU in Atom:
![screen shot 2018-11-29 at 22 08 12](https://user-images.githubusercontent.com/2473081/49245997-e69f4e00-f424-11e8-90eb-cdd0cca4d83c.png)

**Comment by lee-dohm** [comment] 2018-11-29 19:33
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17694. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2018-11-29 19:33 UTC
