### ISSUE TITLE
Would it be possible to install under %UserProfile%\AppData instead of directly under %UserProfile% on Windows?

### ISSUE THREAD

**Issue by ovatsus** [atom/atom#6821] opened 2015-05-16 10:35 UTC
The current installation location makes all the files visible to tools that use the Windows Indexer, spamming it a bit

**Comment by 50Wliu** [comment] 2015-05-16 14:55
What Atom version are you using?  Did you install using Chocolate or the new Squirrel installer?  Squirrel installs Atom to `%LOCALAPPDATA%` by default.

**Comment by ovatsus** [comment] 2015-05-16 15:01
I used the installer from the Download button on http://atom.io
After installation I get a C:\User\<username>\.atom folder with a bunch of stuff inside

**Comment by 50Wliu** [comment] 2015-05-16 15:41
Ah, in that case this is a duplicate of #6345 which has a PR at #6346.

**Closed by 50Wliu** 2015-05-16 15:41 UTC
Labels: more-information-needed
