### ISSUE TITLE
Editor layout destroyed when hitting end of auto-complete popup with arrow keys

### ISSUE THREAD

**Issue by pkaske** [atom/atom#7886] opened 2015-07-14 08:15 UTC
I'm on elementary os freya (based on Ubuntu 14.04).
After I hit to the end of the snippets popup by using the arrow keys, the list jumps up to the first entry - as expected - but atoms bottom bar suddenly get huge. Only way to correct the layout I found is to close and reopen atom.

I attached a gif to show the issue.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11567985/8668966/c1ff6076-2a10-11e5-9326-1c38f242d389.gif)

**Comment by mnquintana** [comment] 2015-07-14 10:47
This is a duplicate of https://github.com/atom/autocomplete-plus/issues/511 and https://github.com/atom/autocomplete-plus/issues/505 and has been fixed for the next release of Atom.

**Closed by mnquintana** 2015-07-14 10:47 UTC
