### ISSUE TITLE
onDidChangeActivePaneItem triggered without the activePane item in the callback

### ISSUE THREAD

**Issue by skandasoft** [atom/atom#4946] opened 2015-01-09 11:56 UTC
with the latest update 0.169.0 onDidChangeActivePaneItem is triggered without the activePane item in the callback when atom.workspace.open  is called

**Comment by maxbrunsfeld** [comment] 2015-01-09 18:38
I can't reproduce this. From the dev tools:

```javascript
atom.workspace.onDidChangeActivePaneItem(function(item) { console.log("item:", item); });
atom.workspace.open("/Users/maxbrunsfeld/github/atom/.gitignore");

// output:
// item: TextEditor {softTabs: true…}
```

**Comment by maxbrunsfeld** [comment] 2015-01-09 18:38
Can you report your list of installed packages (`apm list`) and your OS?

**Comment by benogle** [comment] 2015-01-09 18:40
What happens when the only pane is removed/closed? It is null then?

**Comment by benogle** [comment] 2015-01-09 18:41
After testing, it is correctly undefined when a pane's last item is removed. I'm going to close this out.

**Closed by benogle** 2015-01-09 18:41 UTC
Labels: more-information-needed

**Comment by postcasio** [comment] 2015-01-12 11:48
@benogle the docs for this method say it returns an event object with an `activeItem` property https://atom.io/docs/api/v0.169.0/Workspace#instance-onDidChangeActivePaneItem but it returns just the item itself. Which behaviour is intended?

**Comment by maxbrunsfeld** [comment] 2015-01-12 16:08
Thanks for catching that @postcasio. I think we should change the docs. The status-bar currently [relies on the current behavior](https://github.com/atom/status-bar/blob/master/lib/cursor-position-view.coffee#L5), as do two or three community packages.
