### ISSUE TITLE
Text in file renaming dialog won't fit

### ISSUE THREAD

**Issue by nkkollaw** [atom/atom#14041] opened 2017-03-21 21:41 UTC
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I right-click on the file tree and rename a file that has a long path, the path won't fit in the dialog. Instead of growing horizontally (I have about 2000px that it could use), it shows a hard-to-see vertical scrollbar.

### Steps to Reproduce

1. right click on a file in the tree view that has a long name or path
2. in the context menu, pick "Rename"

**Expected behavior:**
I would like the dialog to grow horizontally so that it could show the whole path

**Actual behavior:**
The dialog width stays the same, dialog grows vertically and a scrollbar appears

**Reproduces how often:**
100%

### Versions
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by 50Wliu** [comment] 2017-03-21 22:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/473. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-03-21 22:24 UTC

**Comment by nkkollaw** [comment] 2017-03-21 23:48
Ok, thanks.
