### ISSUE TITLE
move between panes

### ISSUE THREAD

**Issue by schmurfy** [atom/atom#2670] opened 2014-06-19 15:15 UTC
Hi, I am currently using sublime text with the Origami plugin which allows easily to split/unsplit and move between panes with keyboard shortcuts, some of the features are already available in the last Atom with I am missing some:

Already possible:
- split left/right/top/bottom

Not possible as far as I can tell:
- move to left/right/top/bottom
- unsplit left/right/top/bottom (the associated pane tabs will get merged into the current pane)
- move active tab to pane left/right/top/bottom

**Comment by damonallison** [comment] 2015-04-08 11:59
+1 for a keyboard shortcut to move a file to another pane (or a new pane). 

Splitting the current pane, (say, pane:split-right) puts the current file is in both panes. The first think I personally want to do is remove it from one of the two. Sort of a pane ;)

**Comment by andersennl** [comment] 2015-04-08 12:17
Exactly, the same file in two panes isn’t really useful, right?

**Comment by damonallison** [comment] 2015-04-08 12:40
@andersennl not useful at all.

I like how sublime text manages panes (aka "groups"). They have a pre-set list of pane configurations, which allows them to have predictable keyboard shortcuts to select a pane (ctrl-1, ctrl-2, etc) and move files between panes (ctrl-shift-1, ctrl-shift-2). This is vastly more efficient than moving to the right / left multiple times when you have > 2 panes open.

**Comment by schmurfy** [comment] 2015-04-08 14:06
sublime text can also works like this with the Origami plugin which allows you to split any panel vertically or horizontally as you want/need and that's great :)
There is no "right way" especially when it comes to our text editors, having options is what set an editor aside or the pack for me and that's why Sublime and Textmate before it are awesome tools ^^

Atom is taking the right path, if enough power is given to the plugins then everyone can have the editor work as wanted.

**Comment by damonallison** [comment] 2015-04-08 14:22
@schmurfy absolutely - the plugin approach is ideal. I am on the lookout for something that helps me manage files / panes better. I'm guessing all the primitives are there, we simply need to string a few commands together as you discussed last year.

**Comment by andersennl** [comment] 2015-04-09 12:18
I guess it would be great if when you have a file open and then open up a split pane, the new pane should either be blank - or - grab the open file from the first pane. Maybe there could be two different commands for either one.

**Comment by jrissler** [comment] 2015-07-10 15:35
+1 @andersennl - I agree

**Comment by joshbadger** [comment] 2015-08-31 16:38
-1 @andersennl I disagree. I often view the same file in two panes simultaneously for reference purposes (i.e. there's a method at the top of a file that I need to see while writing new code further down in the file).

**Comment by schmurfy** [comment] 2015-09-01 10:15
I am pretty we all have our preferred ways, all these "details" should be options since for me the power of Atom is its flexibility.

I also wish it would either open a blank panel or move my file over, that said currently in sublime I often open a file twice side by side when working on different sections, the two are not mutually exclusive :)

**Comment by andersennl** [comment] 2015-09-02 07:50
@joshbadger you're right, I actually found it handy to have the same file open twice and the last days. I guess being able to do both is the key.

**Comment by jackocnr** [comment] 2016-03-05 02:25
FYI there is the (confusingly named) [move-panes](https://atom.io/packages/move-panes) plugin which allows you to move tabs between panes with keyboard shortcuts. Would love to see this in core tho!

**Comment by Cosmosz** [comment] 2016-03-29 07:01
If you have vim-mode enabled, you can use `Ctrl+ww` to switch between panes.

**Comment by femans** [comment] 2016-09-15 20:27
@Zhong-z: that just closed my entire editor. Im having trouble to find a shortcut to jump from the file navigation to the code. I hope I am not off topic here, but I see the filenavigator as a pane. All the tips and cheatsheets online though, just mention jumping between code panes, I believe. If anyone has an insight on this, I would appreciate it.

**Comment by harole** [comment] 2016-10-12 09:16
> move to left/right/top/bottom
> move active tab to pane left/right/top/bottom

+1

**Comment by mdrozdziel** [comment] 2016-10-19 08:55
> FYI there is the (confusingly named) move-panes plugin which allows you to move tabs between panes with keyboard shortcuts. Would love to see this in core tho!

Unfortunately this plugin is no longer maintained and as of recent Atom release (1.11.x) does not work any more (https://github.com/santip/move-panes/issues/17).

**Comment by mdrozdziel** [comment] 2016-10-19 09:07
... aaaand it works again in 1.11.2.

**Comment by Ben3eeE** [comment] 2016-11-03 09:44
https://github.com/atom/atom/pull/7953 addressed this and added even more commands. I believe unsplit is the only one not yet implemented which is a duplicate of https://github.com/atom/atom/issues/380. So I am closing this in favor of that one.

**Closed by Ben3eeE** 2016-11-03 09:44 UTC
Labels: enhancement, help-wanted

**Comment by fwuensche** [comment] 2016-11-06 04:47
You can use `cmd-k cmd-arrow` 

![screen shot 2016-11-06 at 12 46 14 am](https://cloud.githubusercontent.com/assets/1740848/20035434/9797e82e-a3ba-11e6-90c0-ba12e40cd164.png)

**Comment by mdrozdziel** [comment] 2016-11-06 07:32
@fwuensche This moves the focus, the issue is about moving the pane.

**Comment by neu-rah** [comment] 2017-04-28 19:14
ctrl-k ctrl-n seems to work fine with me, linux (or cmd-k cmd-n)
i found it more quick than the arrows thing
