### ISSUE TITLE
Atomic Tumbleweed woes

### ISSUE THREAD

**Issue by Adobe-Android** [atom/atom#13357] opened 2016-11-29 11:46 UTC
I can't install the .rpm file (which I should be able to do) because I don't satisfy the dependency libXScrnSaver. Problem is, in openSUSE that package is called libXss1 and so I can't use Atom even though I technically do satisfy the requirements. Mainly, I'd like support added or even efforts made to remove the dependency altogether would be great.

**Comment by Ben3eeE** [comment] 2016-11-29 11:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13354. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-11-29 11:47 UTC
