### ISSUE TITLE
[macOS] File->Open does nothing when there are no open Atom windows

### ISSUE THREAD

**Issue by karevn** [atom/atom#17528] opened 2018-06-17 15:41 UTC
Steps to reproduce:
1. Have macOS version.
2. Open Atom.
3. Close all its windows, but don't exit.
4. Click in menu File -> Open.
Expected behaviour: open file dialog should open.
What happens: nothing.

I'm preparing a pull request for this.

**Comment by karevn** [comment] 2018-06-17 16:11
Should fix it: https://github.com/atom/atom/pull/17529

**Comment by 50Wliu** [comment] 2018-06-17 21:30
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-06-17 21:30 UTC
