### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rnandodias** [atom/atom#18085] opened 2018-09-21 15:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\rnand\AppData\Local\atom\app-1.30.0\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:328

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:328:31)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:140:22)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:870:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.30.0/resources/app/src/text-editor-component.js:1549:59)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-typescript 12.6.3 
autoclose-html 0.23.0 
gitlab 0.1.3-7 
gitlab-integration 0.4.7 
platformio-ide-terminal 2.8.4 
```

**Comment by rsese** [comment] 2018-09-21 16:44
Thanks for the report!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16892 so you can subscribe there for updates if you'd like.  If you have steps to reproduce, please let us know in https://github.com/atom/atom/issues/16892.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-09-21 16:44 UTC
