### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ Design and Technology'

### ISSUE THREAD

**Issue by N00161198** [atom/atom#18289] opened 2018-10-20 07:58 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ Design and Technology'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/ Design and Technology'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:343:29)
    at TreeView.module.exports.TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1544:34)
    at TreeView.module.exports.TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1844:37)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:389:30)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-10-22 17:41
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-22 17:41 UTC
