### ISSUE TITLE
Selection stuck on mouse movement

### ISSUE THREAD

**Issue by nhnb** [atom/atom#11691] opened 2016-05-04 09:50 UTC
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

After I click in an editor window, moving the mouse will select the text. Atom behaves as if I did not release the mouse button.
### Steps to Reproduce
1. Start atom (in normal or safe mode) and open an editor
2. Press and release the left mouse button
3. Move the mouse cursor

**Expected behavior:** [What you expected to happen]

Text should not be selected because I clicked and  released the mouse button

**Actual behavior:** [What actually happened]

Text is selected as if I had not release the mouse button
### Versions

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
on
Ubuntu 15.10 (Wily Werewolf)

**Comment by nlaplante** [comment] 2016-05-10 15:26
I have the same problem. Same steps as above

### Versions
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
on
Fedora 23

**Comment by manuelmazzuola** [comment] 2016-05-19 07:53
Same problem with version 1.5.4

**Comment by lee-dohm** [comment] 2016-05-24 03:35
Can any of you reproduce this on the latest `master`? We recently updated the version of Electron to v0.37.8 on `master` (which brings Chrome 49 with it) and I wonder if that fixes things.

**Comment by eeejay** [comment] 2016-06-06 00:25
I see this in 1.8 beta. building master now..

**Comment by lee-dohm** [comment] 2016-06-07 16:03
The version of Electron I mentioned above should now be in the Beta channel. Let us know if anyone is still running into this!

**Comment by XYunknown** [comment] 2016-06-13 13:09
I had this issue on Arch Linux for ages, too (ever since the first Atom release) . It seemed to be triggered randomly and can not be fixed for me by reopening the file. It also affects all files I open in Atom.. Not even a restart of Atom helps. I'd be happy to provide more details if you tell me what exactly you need (it is reproducable in safe mode, but I don't know what triggers it)

**Comment by XYunknown** [comment] 2016-06-13 13:20
Update: Issue is present in 1.8.0. B3, too. I have as of now found no way of fixing this problem once it occurs with my Atom installation.

**Comment by 50Wliu** [comment] 2016-06-13 20:25
@XYunknown As @lee-dohm mentioned above, please try the 1.9.0 betas.

**Comment by XYunknown** [comment] 2016-06-18 08:37
Tried 1.9, still the same issue.

**Comment by nlaplante** [comment] 2016-06-18 21:50
What I do on Linux to fix this is to restart into a Wayland session, then
log back in an X11 session. Works every time.

**Comment by XYunknown** [comment] 2016-06-18 21:54
I suspect this to be a problem with X and electron, too. But your proposed solution doesn't solve the issue in the long run.. It works for me again after restarting X. This might be a bug in electron?

**Comment by cydrobolt** [comment] 2016-07-26 22:40
Same problem on Fedora 23 GNOME

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by emptyemail** [comment] 2016-08-14 17:53
I was able to reproduce this on Fedora 24 GNOME

```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

1. Start Atom
2. Suspend
3. Resume
4. Click anywhere in an open file and try to move the mouse. 

if I ignore it sometimes goes away but always comes back after resume, I am pretty sure the problem is limited to the touchpad and not a usb mouse.

I switched my session to wayland and so far problem seems to be fixed for me.

**Comment by 50Wliu** [comment] 2016-08-14 20:05
@emptyemail Try Atom 1.9.8 and see if that works.

**Comment by emptyemail** [comment] 2016-08-21 18:58
@50Wliu works much better, no issues yet. Thanks!

**Comment by emptyemail** [comment] 2016-08-31 00:38
@50Wliu I spoke too soon, looks like its happening again.

**Comment by CarlosRoque** [comment] 2016-09-08 16:33
I have the same problem
atom 1.10.2

**Comment by AdrianVovk** [comment] 2016-09-13 02:13
Have it too

**Comment by krassowski** [comment] 2016-09-14 22:37
The same here:

Fedora 24 with Gnome 3.20.2
Atom 1.10.0

A lot of comments suggests a relation to Gnome shell.

**Comment by pmted** [comment] 2016-09-15 08:03
I have the same problem.

Ubuntu Gnome 16.10
Atom 1.10.2

**Comment by ssendev** [comment] 2016-09-16 09:31
I can reproduce it on Fedora 24 with Gnome 3.20.4 and Atom 1.10.0

I can reliably trigger the select behavior by opening the screen keyboard with https://extensions.gnome.org/extension/993/slide-for-keyboard/ while the screen keyboard is disabled in accessibility settings.

A tap on the touchscreen fixes it.

Atom doesn't need to be running while doing these things.

**Comment by ro31337** [comment] 2016-09-21 21:30
Same on Ubuntu 16.04 LTS with Gnome 3.18.5, Atom 1.9.9. Atom restart doesn't help. Tired rebooting computer two times a day (-:

**Comment by joaokamun** [comment] 2016-10-01 02:47
Archlinux here, and its happening very frequently.

**Comment by vadixidav** [comment] 2016-10-05 13:51
I have the same issue. Archlinux with i3 as WM here. I used to be able to fix this issue by using xinput to disable and enable my touch screen, which would periodically fix it, but now this no longer fixes it (after a recent system upgrade).

**Comment by dschissler** [comment] 2016-10-11 08:09
I'm on Atom `1.10.2`, Gnome 3.22 and even closing the application didn't help until I tapped Atom with the touchscreen.  Wow, super annoying but I'm happy that it can be fixed.

**Comment by bstrdsmkr** [comment] 2016-10-13 14:59
I use a Mac Book Pro running Ubuntu 16.04 in a VM and see the same problem. I also use an external mouse and just discovered that once this occurs with my external mouse, tapping the touch pad fixes it. Maybe for those without a touch screen/pad, moving your mouse to a different USB port and clicking could help? Still sucks, but maybe better than rebooting until this is fixed.

**Comment by umpirsky** [comment] 2016-10-18 15:56
@dschissler Same here, thanks, tap with a touchscreen helps!

**Comment by SovcikJoe** [comment] 2016-10-24 06:11
Same issue

Arch (Manjaro) with Gnome, 'fixed' by tapping the touchscreen.

I just wanted to comment so I get updates for this thread.

**Comment by nathanchere** [comment] 2016-10-29 09:55
1.10.2 on Fedora 25
*STILL* same issue, and touching or disable/renabling the touchscreen via xinput no longer solves it.

**Comment by Orangestar12** [comment] 2016-11-03 06:14
Thanks for the thread, thought I'd shed some light on the situation.

This doesn't seem to be a problem with Electron or Atom specifically. I'm running GNOME 3.20 with a touchscreen, and occasionally my system will enter a state where tapping anywhere onscreen will raise the onscreen keyboard (known as Caribou) in a smaller state (presumably to quickly enter keypresses when not typing large text.)

![Attached is a screenshot showing the Caribou onscreen keyboard slightly minimized in the bottom left corner.](https://cloud.githubusercontent.com/assets/785315/19957124/e349af1a-a161-11e6-8df5-533cca2d48c6.png)

For reference, this is what Caribou normally looks like.
![Attached is a screenshot showing the Caribou onscreen keyboard taking up the entire bottom of the screen.](https://cloud.githubusercontent.com/assets/785315/19957174/546fdcf0-a162-11e6-86ae-dc2d470ab223.png)

I have a hunch that the state of "Annoying Caribou" and Atom always highlighting selections are related somehow. "Annoying Caribou" seems to happen more often when I am using the "Slide For Keyboard" GNOME extension, and especially when I am using the "Caribou-Resize-Workspace" GNOME extension.

If this helps narrow down why any of this is happening, I will be happy knowing I helped.

**Comment by yeltsin** [comment] 2016-11-04 03:29
Like @Orangestar12 I have a notebook with touchscreen (but I don't use it).

The same problem on Ubuntu GNOME 16.10, Atom v.1.11.2.

**Comment by fbourigault** [comment] 2016-11-04 12:28
I also confirm that a tap on the touch screen fixes the annoying behavior.

**Comment by jayarc** [comment] 2016-12-06 13:42
I can confirm was well running Debian testing that a tap on the touchscreen fixed this for me as well.

**Comment by stephanedaviet** [comment] 2016-12-06 13:50
I sometimes get the same behaviour in IntelliJ if it can help.

**Comment by ruda-almeida** [comment] 2017-01-22 20:00
I had the same issue. 

I own a touchscreen laptop (looks like it's a quite common factor among those affected) and the issue happened only after it going to sleep and then a subsequent restore. 

I was running atom-1.7.3-0.1.fc21.x86_64, on both on Fedora 23 and Fedora 24.  Restarting gnome wouldn't fix it.

I'm updating Atom to the latest version (`atom-1.7.3-0.1.fc21.x86_64`) and will see if the issue is fixed.

**Comment by ruda-almeida** [comment] 2017-01-22 20:11
Well, looks like it's been fixed! 👍

**Comment by ayoisaiah** [comment] 2017-01-28 01:05
I also have this issue on Fedora 25 GNOME 3.22. Tapping my touchscreen seemed to fix it too

**Comment by Madko** [comment] 2017-02-04 15:06
same issue here on 1.13.1. Tapping the touchscreen is a good to know workaround. Thanks.

**Comment by nicszerman** [comment] 2017-05-05 02:21
Same issue here on 1.13.0. I have the touchscreen disabled, so tapping it is not an option. What did the trick for me was enabling and disabling it again (using xinput).

**Comment by StephanMeijer** [comment] 2017-05-19 11:10
Same issue here, Fedora 25 with Gnome, XPS 13 with touchscreen.

**Comment by lgilz** [comment] 2017-05-19 13:01
Same Issue here. Ubuntu 17.04 and touching the touchscreen solves it.... However, this is really annoying. Atom used to be my favorite Editor and I was close to abandoning it before I found this thread! Please fix this!

**Comment by aaronddickson** [comment] 2017-06-13 03:32
Same issue here on 1.17.2, Arch Linux and a touch screen, and like others, touching the touchscreen solves it.

**Comment by aimalz** [comment] 2017-06-20 19:19
I think the problem is more about the system/X than Atom because it happens with TeXstudio and Okular  as well, and they are all affected at the same time, i.e. if one if affected they all are.  Closing and restarting the programs has no effect, but simply giving some mouse input via the touchscreen fixes it, until the next time it happens of course.

**Comment by Orangestar12** [comment] 2017-07-12 06:39
A similar error seems to happen when using the touch screen with Eye of Gnome. Occasionally when doing swipes or taps, the tap will "catch" and any other taps are treated like a multi-touch tap around the first one, leading to many rotations and scalings.

**Comment by ro31337** [comment] 2017-07-12 17:25
Observation: using Visual Studio Code for ~6 months. There is no such bug in VS Code.

**Comment by JamesTiberiusKirk** [comment] 2017-07-27 08:36
This is definitely a touchscreen related issue.
I have a Dell XPS 13 w/touch and I get the same behaviour in telegram, atom and sometimes some weirdness with items on the gnome dock when using mouse/touch pad.
When this happens, I found that if I start scrolling with the touchscreen the issue resolves itself.

**Comment by internalfx** [comment] 2017-07-30 00:01
@JamesTiberiusKirk Thank you

**Comment by CarlosRoque** [comment] 2017-07-30 15:05
On Ubuntu Gnome 17.04 and atom 1.18.0. on a surface pro 3. 

I can confirm that touching the screen fixes the problem

**Comment by Kamforka** [comment] 2017-08-09 07:42
Same issue on Windows 7 SP1 64-bit and Atom 1.19.0 x64. I have no touchscreen to touch unfortunately, so the problem cannot be solved for me at the moment, rebooting doesn't help either.

**Comment by Youfka** [comment] 2017-08-09 08:52
have this issue right now on windows 10, this happening with my mouse (no touchscreen), please help :(

**Comment by razilevin** [comment] 2017-08-09 14:13
I had the same issue but restarting atom in safe mode fixed my issue, The only thing that worked without safe mode was renaming the .atom folder. Just started this morning do not know why/how it happened

**Comment by Endlessline** [comment] 2017-08-09 15:10
Can confirm disabling atom-terminal-panel and restarting Atom stops this behavior

**Comment by razilevin** [comment] 2017-08-09 16:15
Nice work @Vitzkrieg. I also have atom-terminal and saw the deprecated function alert. But why today when I have had that plugin installed before the issue appeared.

**Comment by Orangestar12** [comment] 2017-08-09 20:00
Sounds like that's specifically causing the problem on Windows. I personally use the platformio-ide-terminal package and even then the issue appeared long before I installed that and long after I disabled it.

**Comment by razilevin** [comment] 2017-08-09 20:34
@Orangestar12 Difficult to pin-point your issue since you have the variable of "touchscreen" while in my case I use a vanilla setup. Removing my .atom directory fixed my issue, I did have a KB security update yesterday. I also checked my old .atom/packages folder for any files modified on yesterday. Nothing... So maybe the KB was the culprit in my case

**Comment by VadimDor** [comment] 2017-08-15 12:02
The same for me normal mouse ( no-touchscreen)  on Win8.1 x64:

Atom: 1.19.1 x64
Electron: 1.6.9
atom-terminal-panel enabled - disabling stops this behavior!

**Comment by PSpurlingTPF** [comment] 2017-08-17 21:26
Thank you @Vitzkrieg . Disabling atom-terminal-panel resolved this for me also. 
Mac 10.12.6 
Atom  1.19.2
normal mouse, no touchscreen

**Comment by dnalbach** [comment] 2017-09-13 15:04
I was having this problem too after installing atom-terminal-panel. Uninstalled it and restarted Atom. Fixed.

Mac 10.11.3
Atom 1.19.1
Touchpad, Macbook Pro, no touchscreen.

**Comment by anselmobd** [comment] 2018-07-31 14:27
I'm using Atom 1.15.0 x64 on Ubuntu 16.04, and a note with touchscreen.
From time to time this problem appears.
To solve it, I just touch anywhere in the text in the file edited.
I hope this information save someone or help to fix the bug.

**Closed** 2018-09-20 20:29 UTC
Labels: bug, linux, more-information-needed
