### ISSUE TITLE
Atom profiles

### ISSUE THREAD

**Issue by mindrones** [atom/atom#10682] opened 2016-02-04 12:11 UTC
I'm stuck with an Atom that [constantly hangs](https://github.com/atom/atom/issues/10159) (CPU at 100%) and I'd like to try to disable packages iteratively to track this problem down.

This makes me think that when you have a similar problem in Firefox the suggested approach is to disable all addons manually or just use a clean profile.

Disabling all packages is problematic as I keep some package installed but disabled for future testing, hence disabling a package I use just to inspect an Atom problem would send it to the list of Disabled packages, which makes it difficult to find it again in a long list of greyed out packages.

Instead, running Atom with a "clean" profile would let me quickly check if the problem persists, it would be much more powerful.

**Comment by 50Wliu** [comment] 2016-02-04 14:02
`atom --safe` seems to be exactly what you're asking for :wink:.

**Comment by lee-dohm** [comment] 2016-02-04 23:57
I agree. Safe Mode is designed for exactly this kind of use.

**Comment by mindrones** [comment] 2016-02-08 08:51
What about having different profiles with different installed packages like we do in Firefox?
One might have a "python dev" profile and a "javascript dev" profile with different linters and syntax highlighters etc, so to keep running packages at minimum in each Atom session.

**Comment by lee-dohm** [comment] 2016-02-08 16:16
If this is about profiles for different types of work (and not just Safe Mode), then this is a duplicate of https://github.com/atom/atom/issues/6619.

**Closed by lee-dohm** 2016-02-08 16:16 UTC
Labels: more-information-needed
