### ISSUE TITLE
Bad else indention

### ISSUE THREAD

**Issue by Jglez2330** [atom/atom#15781] opened 2017-09-30 16:52 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
### Description
When I write an else: , atom place the else in the funtion indent level
### Steps to Reproduce

1. Select python language
2. Write a funtion with else:

**Expected behavior: keep the else in the same place I wrote it 

**Actual behavior: Atom moves the else to the left 

**Reproduces how often: Every time i write an else in an Funtion

### Versions
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by dfbenjamin** [comment] 2017-10-01 19:43
I get the same unexpected behaviour when I try to write something like this:

```python
def f(x):
    else:
```

which becomes:

```python
def f(x):
else:
```

However, I get the expected behaviour when I type this:

```python
def f(x):
    if True:
        pass
    else:
```

Versions:

Atom    : 1.19.6
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by Ben3eeE** [comment] 2017-10-01 19:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-python/issues/209. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-10-01 19:47 UTC
