### ISSUE TITLE
Option to NOT remember previously opened files

### ISSUE THREAD

**Issue by code-tree** [atom/atom#6839] opened 2015-05-18 11:00 UTC
**Feature request** for the opposite of #1603 (not to reverse it, but to add an option to disable it).

**Currently:** Atom will reopen files that were not closed from last time (within the same project)
**Desired:** An option to disable this, so that no additional files are opened when Atom starts

There is currently [a hack for this](https://discuss.atom.io/t/dont-open-previously-opened-files-on-new-start/5959), however, a configurable setting would be much more appropriate.

**Using:** Atom 0.198.0 on Linux

Thanks

**Comment by mnquintana** [comment] 2015-05-18 11:32
Thanks for the suggestion! This is a duplicate of https://github.com/atom/atom/issues/6605 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-18 11:32 UTC
