### ISSUE TITLE
Feature: Titlebar like Github Desktop (Windows)

### ISSUE THREAD

**Issue by flofriday** [atom/atom#14969] opened 2017-07-06 22:00 UTC
## Atom
![image](https://user-images.githubusercontent.com/21206831/27933793-251d231a-62a3-11e7-9d2d-3a8542da53fa.png)

## Github Desktop (Beta)
![image](https://user-images.githubusercontent.com/21206831/27934049-3bec3044-62a4-11e7-9a4b-27a3ae9a9902.png)

## Description
The new Desktop Client for Github has a really sexy Titlebar. 
Not only because it matches the color of the application but also because it doesn't use the OS default application menu but a custom one inside the Titlebar. 
Unfortunately, the windows default Titlebar and the application menu are very ugly. Especially the application menu looks like Windows 95 when Microsoft introduced this grayish style which they didn't changed since for it. Sure, it's sad that developers have to come up with custom solutions but the windows version would look soo much better with a custom title bar like the Github Client.

A custom Titlebar would also be nice on other platforms but on macOS, the application menu isn't in the window but in the menubar wich looks great and it should be there. On most Linux distros the Titlebar and the application menu have at least the same style so it doesn't look so bad there. Therefore the windows version of Atom is worst one and needs this feature the most.

Other Issues:
#13249 
#4599

**Comment by brograhamer** [comment] 2017-07-12 18:51
+1

**Comment by rsese** [comment] 2017-07-20 23:37
Thanks for the request @flofriday :v:  I skimmed some of the linked issues and but just to confirm, is what you're asking for basically covered in https://github.com/atom/atom/issues/13249/#4599?

**Comment by flofriday** [comment] 2017-07-20 23:53
@rsese 
Yeah basically.
However, I would like to see a complete remake of the title-bar with the application menu which included in the title-bar itself. 

A helpful package might be:
https://www.npmjs.com/package/electron-titlebar 
(But I haven't used it yet so I can't confirm how well it perform or if it is even stable)

**Comment by skylize** [comment] 2017-09-10 20:58
@rsese 

#4599 looks pretty focused on mac, and they seem to have found themselves an acceptable solution in an OSx-only addon package.

I _do_ think it's safe to mark this as duplicate of #13249. 

@flofriday 

You should go to that thread and point out that you think that copying stylistic choices of GitHub is a good idea.

**Comment by rsese** [comment] 2017-09-13 20:39
I think agree with you @skylize :+1:, I think it's close enough to close as a duplicate of https://github.com/atom/atom/issues/13249.   If you disagree let me know @flofriday, otherwise feel free to chime in there.

**Closed by rsese** 2017-09-13 20:39 UTC
Labels: enhancement, more-information-needed
