### ISSUE TITLE
Why is Atom going online during indexing?

### ISSUE THREAD

**Issue by greencopper** [atom/atom#12429] opened 2016-08-15 12:28 UTC
Why is Atom accessing the net every time it is indexing? What's going on?

**Comment by greencopper** [comment] 2016-08-15 12:43
Followup: Doing some package capturing, Atom goes to Amazon, but the transmission is encrypted.

```
92	0.484375144	23.23.162.51	10.102.1.6	TLSv1.2	83	Encrypted Alert
93	0.484378962	23.23.162.51	10.102.1.6	TCP	52	443 → 47006 [FIN, ACK] Seq=6196 Ack=631 Win=16640 Len=0 TSval=2292837117 TSecr=1390491
...
156	0.623338798	23.23.162.51	10.102.1.6	TLSv1.2	879	Application Data
```

And TONS of data goes to Amazon following! And yes, I have metrics disabled!

I am no longer going to use Atom until EVERYTHING is open and EVERYTHING can be disabled!

**Comment by thomasjo** [comment] 2016-08-15 13:06
Please fill out [the issue template](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md). There are very good reasons why this is presented to you **by default** when you open a new issue. First and foremost, it allows us to verify whether a certain behavior or bug is caused by Atom or an installed community package.

What you are describing is not caused by any code present in a default Atom installation, hence caused by either an installed package or some other form of environment issue.

> I am no longer going to use Atom until EVERYTHING is out in the open and EVERYTHING can be disabled!

Everything **is** _"out in the open"_... everything tracked by the metrics and the exception-reporting packages is publicly available.

**Comment by 50Wliu** [comment] 2016-08-15 14:43
> Actually, this is one of the packages.

Assuming issue reported on wrong repo, so closing.

**Closed by 50Wliu** 2016-08-15 14:43 UTC
Labels: invalid, more-information-needed

**Comment by greencopper** [comment] 2016-08-15 15:59
Yes, sorry, this was a mistake on my part.
