### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.36.1\uhost-i...

### ISSUE THREAD

**Issue by vladislavicus** [atom/atom#19314] opened 2019-05-12 13:03 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\User\AppData\Local\atom\app-1.36.1\uhost-icon.png'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\User\AppData\Local\atom\app-1.36.1\uhost-icon.png'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:914554)
    at TreeView.t.exports.TreeView.onDrop (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:920438)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:895148)
```

### Commands

```
  2x -3:21.9.0 core:move-right (input.hidden-input)
  2x -3:21.4.0 core:backspace (input.hidden-input)
  2x -3:04.6.0 editor:newline (input.hidden-input)
  3x -2:49.8.0 core:backspace (input.hidden-input)
     -2:44.7.0 core:move-down (input.hidden-input)
     -2:44.5.0 autocomplete-plus:confirm (input.hidden-input)
     -2:36.3.0 core:move-right (input.hidden-input)
     -2:33.4.0 autocomplete-plus:confirm (input.hidden-input)
     -2:33.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  4x -2:28 core:backspace (input.hidden-input)
     -2:16.9.0 core:move-left (input.hidden-input)
  2x -2:14.9.0 core:save (input.hidden-input)
     -1:36.2.0 core:backspace (input.hidden-input)
     -1:33.8.0 core:save (input.hidden-input)
     -1:18.1.0 core:backspace (input.hidden-input)
  2x -1:17 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
Hydrogen 2.9.0 
```

**Comment by rsese** [comment] 2019-05-13 21:48
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-05-13 21:48 UTC
