### ISSUE TITLE
Object.extname is deprecated.

### ISSUE THREAD

**Issue by AnetteMM** [atom/atom#18606] opened 2018-12-20 14:55 UTC
Argument to `path.extname` must be a string
```
Object.extname (D:\abc_my folders\cherrytrees\Atom\Atom\resources\app.asar\src\electron-shims.js:20:10)
Object.getGrammar (C:\Users\PC\.atom\packages\preview-plus\lib\preview-plus.coffee:439:20)
StatusView.setCompilesTo (C:\Users\PC\.atom\packages\preview-plus\lib\status-view.coffee:315:26)
<unknown> (C:\Users\PC\.atom\packages\preview-plus\lib\preview-plus.coffee:86:17)
Function.simpleDispatch (<embedded>:11:1190583)
Emitter.emit (<embedded>:11:1192024)
```

**Comment by Ingramz** [comment] 2018-12-20 15:57
Duplicate of https://github.com/skandasoft/preview-plus/issues/53

**Closed** 2018-12-20 16:16 UTC
