### ISSUE TITLE
Atom hangs when clicking a package link from "Install Packages"

### ISSUE THREAD

**Issue by jmacmahon** [atom/atom#7929] opened 2015-07-16 09:39 UTC
## Version information
Using Arch GNU/Linux with latest packages as of 2015-07-16.
```
$ atom --version
1.0.2
$ chromium --version
Chromium 43.0.2357.134
$ uname -a
Linux edsger 4.0.7-2-ARCH #1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64 GNU/Linux
```

## Bug
From the Settings > + Install view, clicking on any package (from Featured Packages or from search results) results in an unrecoverable hang, followed by the "Editor is not responding" modal dialog.

`-f` and `--safe` parameters were used to start atom.

### Expected behaviour
The package page is opened in my default browser (Chromium).

### Actual behaviour
Editor hangs until it is terminated.  Once terminated, a single chromium process is left behind on the system.  Killing this process causes the relevant package page to be opened in Firefox.

### Screenshots and GIFs
The initial click which produces the hang.
![step1](https://cloud.githubusercontent.com/assets/1281068/8719777/0184fd26-2bb7-11e5-9651-63c8bf9e539c.gif)

"Editor is not responding" modal
![step2](https://cloud.githubusercontent.com/assets/1281068/8719783/07499b5e-2bb7-11e5-8baa-be2440d7affe.png)

Killing the straggler chromium process causes the package page to be opened in Firefox
![step3](https://cloud.githubusercontent.com/assets/1281068/8719785/09d0bf56-2bb7-11e5-8f30-0e78c35a7609.gif)

### Debugging
No relevant output on the terminal when `-f` was specified; no stacktrace in the Dev Tools.  Unable to use the profiler tool as the editor is unresponsive when the "Stop" button is clicked.

**Comment by mnquintana** [comment] 2015-07-16 10:42
I think this is a duplicate of https://github.com/atom/atom/issues/6335 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-16 10:42 UTC
