### ISSUE TITLE
[1.19.0] Reveal in tree view not selecting file when all parent directories are closed

### ISSUE THREAD

**Issue by webb04** [atom/atom#15210] opened 2017-08-09 14:44 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Reveal in tree view doesn't select current file if all parent directories are closed.

### Steps to Reproduce

1. Open atom window in root directory of project
2. Open a file nested somewhere deep in the folder structure
3. Close all parent directories in tree view
4. right click on open file and select `reveal in tree view`

**Expected behavior:** [What you expect to happen]
The current file to be selected in the tree view.

**Actual behavior:** [What actually happens]
Root directory is still selected.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.8
git 2.10.1

### Additional Information

**Comment by Ben3eeE** [comment] 2017-08-09 15:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/188. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-09 15:47 UTC
Labels: duplicate, wrong-repo
