### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.26.0\res...

### ISSUE THREAD

**Issue by splendidaakif** [atom/atom#17201] opened 2018-04-23 05:01 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Enterprise N
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Duha-Group_Aakif_Lap\AppData\Local\atom\app-1.26.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\Duha-Group_Aakif_Lap\AppData\Local\atom\app-1.26.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.26.0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.26.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.5.3 
atom-live-server 2.2.0 
atom-ternjs 0.18.3 
autocomplete-html-entities 0.2.0 
css-spy 0.6.0 
html-to-css 0.2.2 
linter 2.2.0 
linter-jscs 4.1.3 
linter-json-lint 0.1.3 
pretty-json 2.0.0 
```

**Comment by DiThi** [comment] 2018-04-23 14:47
This happens to me when trying to search a package.

**Comment by rsese** [comment] 2018-04-23 17:13
I think this is a duplicate of issues like #15722. If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled. If you don't have any anti-virus software running or re-installing doesn't help, let me know.

**Closed by rsese** 2018-04-23 17:13 UTC

**Comment by DiThi** [comment] 2018-04-24 01:03
I don't think it's a duplicate. I don't use any antivirus (other than windows' built in that says there were no threats found) and the previous version of Atom works just fine.

**Comment by rsese** [comment] 2018-04-24 16:49
Did you try reinstalling @DiThi?

**Comment by DiThi** [comment] 2018-05-14 17:35
Yes, still happening. Copied an older version from another machine and disabled updates for now.
