### ISSUE TITLE
Alt + menu hotkey doesn't work, closes menu on Windows

### ISSUE THREAD

**Issue by KeithTurkowski** [atom/atom#10732] opened 2016-02-08 18:20 UTC
When trying to save a file by hitting the key sequence: alt+f alt+s the menu closes and the file does not save.

In every other Windows application I tested, this works. This is done to compensate when typing alt+f s quickly, the release of the alt key does not register before the s key is pressed, or the user does not release it in time.

It is expected that opening the menu, then pressing the hotkey OR alt+hotkey should trigger the action, as this behavior is present in virtually every other Windows application.

**Comment by 50Wliu** [comment] 2016-02-08 21:08
Thanks for reporting, @KeithTurkowski!  This looks like a duplicate of #4057 though, so please subscribe there for updates.

**Comment by KeithTurkowski** [comment] 2016-02-08 22:01
This is NOT a duplicate. This is a different issue. I read through all the open bugs before submitting this issue, including #4057. While this bug is similar, it's actually a different issue altogether.

In fact, the first thing I did was remove the 'alt-f': 'editor:move-to-end-of-word' binding as mentioned in that other thread.

Please reopen.

**Comment by 50Wliu** [comment] 2016-02-08 22:26
Ok, I can reproduce this after unbinding <kbd>Alt+F</kbd>.  In the future, please clearly indicate the steps to reproduce (see https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report), as in your initial issue it wasn't clear that you had already unset <kbd>Alt+F</kbd>.

**Comment by damieng** [comment] 2016-02-19 04:33
So it seems there are a two keyboard shortcut issues here:

<kbd>Alt-F</kbd> (File) is bound to ``editor:move-to-end-of-word	``
<kbd>Alt-H</kbd> (Help) is bound to ``editor:delete-to-beginning-of-word``

Both shortcuts **only** work when no file is open and unbinding doesn't fix that.

Also noticed that the right/left arrow keys do not cycle between menus like they should in Windows.

**Comment by KeithTurkowski** [comment] 2016-02-19 05:48
Just to clarify, this bug is not for the Alt-F / Alt-H bindings, that is a separate issue #4057.

If you go into keymap.cson and add:
`  'atom-text-editor':
    'alt-h': 'unset!'
    'alt-f': 'unset!'`
It will unset those bindings, and you can access the menu using the Alt-F and Alt-H hotkey.

This bug occurs once the menu is open, if you press the hotkey for any menu item while holding down the ALT key, the menu will close and not execute the menu item. This is not consistent with other windows applications, that allow you to execute menu items by pressing either hotkey or ALT+hotkey.

This is a problem for people who hit hotkeys combinations very quickly and do not release the ALT key in time for the next key stroke. e.g. Alt+S F (saves file), Alt+F Alt+S (fails to save file)

**Comment by Treit** [comment] 2016-09-23 01:34
This issue is my top complaint when trying to use Visual Studio Code as an editor. I have trained myself over many years to use Alt+F+S to save open files (rather than, say, Ctrl+S) and it is deeply ingrained in my muscle memory. 80% of the time I execute this key combination in VS Code it fails to save the file. It appears this Atom issue is the root cause.

**Comment by 50Wliu** [comment] 2016-09-23 02:18
> Visual Studio Code [...] It appears this Atom issue is the root cause.

@Treit Atom and VS Code both use the same underlying framework (Electron), but VS Code does **not** run on Atom, and as such Atom is not causing the Visual Studio Code bug that you may be experiencing.  Please open a separate bug report on the VS Code repo.

**Comment by Treit** [comment] 2016-09-23 02:36
@50Wliu There is already an active bug (not opened by me) in vscode (#5556, see the reference above) that points to this Atom issue. Sounds like maybe that was opened erroneously.

**Comment by 50Wliu** [comment] 2016-09-23 03:00
Yeah it looks like @Tyriar got confused because he talked about Electron while referencing an Atom issue.  He may have been referencing the fact that because the core issue stems from Electron, Atom is also experiencing the same bug.

**Comment by Tyriar** [comment] 2016-09-23 03:07
The latter 😃

**Comment by damieng** [comment] 2017-05-05 21:41
Alt-F S works but Alt-F Alt-S does not - this is a limitation of the way Electron is handling menus and is not Atom specific - as has been pointed out it affects other Electron based apps such as VSCode.  No action here although you might want to open an issue for Electron if there isn't already one.

**Closed by damieng** 2017-05-05 21:41 UTC
Labels: bug, windows

**Comment by SteveALee** [comment] 2017-05-08 08:04
A concur with @damieng 

At one point I found ALT+F, S did NOT work the first time in @code and I had to do it twice! Then it seemed to take a second and now it fine works. I suspect there is another saving speed issue overlaying the basic menu mnemonic handling problem.
