### ISSUE TITLE
Add "collapse all" option to tree view context menu

### ISSUE THREAD

**Issue by petebachant** [atom/atom#10129] opened 2015-12-19 16:49 UTC

**Comment by jerone** [comment] 2015-12-20 13:54
There's no collapse/expand (all) option in the context menu, but you could use option-click (<kbd>Alt</kbd> on Windows) a folder to collapse/expand all.

**Comment by leebenson** [comment] 2016-11-29 16:24
Just an FYI that some Mac keyboards show "Option" as <kbd>Alt ⌥</kbd> <-- that's the key you press.

**Comment by Akronix** [comment] 2016-11-30 12:46
> There's no collapse/expand (all) option in the context menu, but you could use option-click (Alt on Windows) a folder to collapse/expand all.

@jerone  that doesn't work on Ubuntu :confused:

**Comment by 50Wliu** [comment] 2016-11-30 20:50
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/960. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-11-30 20:50 UTC

**Comment by majebry** [comment] 2017-02-06 09:01
@Akronix try "ctrl-alt-["

**Comment by Akronix** [comment] 2017-02-06 22:36
@majebry that works for the code blocks only, not for the tree view.

**Comment by winterblack** [comment] 2017-02-09 22:10
@Akronix works for me on the tree. Using ubuntu 16.04 LTS

**Comment by Akronix** [comment] 2017-02-09 23:55
Ok guys, you're right! It doesn't collapse all at once but it's useful anyway.
I was using version 1.13.1 of Atom thanks to #2956. I updated to 1.14.1 and now it works.
Thanks.

**Comment by Jesus-Gonzalez** [comment] 2017-06-21 18:42
Since I'm using a non-english keyboard layout (es-ES, indeed) I select the top or root directory I want to collapse, and press `ALT + left arrow` in order to collapse all. You can also press `ALT + right arrow` to expand all.

**Comment by eugenet8k** [comment] 2017-08-30 23:09
My Tree View doesn't have one root folder, but rather 10 different folders, this is why "Collapse All" is especially desirable. If I try to do "ctrl-alt-[" or "ALT + left arrow" on one of the top level folders the Atom editor just hangs forever.
