### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by 00King00** [atom/atom#19393] opened 2019-05-23 17:21 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: �������� Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\BIP\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:1114514)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:1110220)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:14:89928)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:69977)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:92413)
```

### Commands

```
     -4:08.8.0 core:paste (input.hidden-input)
     -3:15 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
custom-folds 1.9.5 
file-icons 2.1.27 
indent-guide-ext 0.2.3 
intentions 1.1.5 
language-ini 1.20.0 
language-pug 0.0.22 
language-vue 0.24.0 
lint-sass-vue 1.0.5 
linter 2.2.0 
linter-gcc 0.7.1 
markdown-folding 0.3.1 
minimap 4.29.9 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.4 
sass 0.5.0 
tabs-to-spaces 1.0.5 
tool-bar 1.1.11 
trailing-spaces 0.4.0 
vue-autocomplete 0.1.1 
white-cursor 0.7.0 
```

**Comment by rsese** [comment] 2019-05-23 20:41
Thanks for contributing!

We noticed that this looks like a potential duplicate of https://github.com/atom/atom/issues/19108 so we'll close in favor of that issue and you can subscribe there for updates if you'd like.  If you have specific steps to reproduce, please let us know in https://github.com/atom/atom/issues/19108.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-05-23 20:41 UTC
