### ISSUE TITLE
Copy/paste lag causes previous clipboard to be pasted when using "find" field

### ISSUE THREAD

**Issue by atombender** [atom/atom#11579] opened 2016-04-22 18:42 UTC
### Description

If do the steps below fast enough, it pastes the _previous_ clipboard contents instead of the new one.

In other words, there's a lag before anything copied ends up on the clipboard. If I wait slightly after `cmd-F`, it pastes the correct thing. The same lag does not occur within a single editor; only when copying from the editor and into another buffer, in this case the "find" field.

Here's a video ([mp4](https://www.dropbox.com/s/9iut1241xq5gl8f/atom.mp4?dl=0)). It's slowed down to 1/10 of the real speed and shows me copying the word "key" and pasting it, which ends up being "position", which wasn't what I copied. (Please ignore the fact when the "find" panel is shown intially, it contains the word "key". That's from a previous attempt. Had to do this a bunch of times to reproduce in a way that was understandable in a video.)

![atom](https://cloud.githubusercontent.com/assets/50314/14751466/ffb107ba-0897-11e6-9025-a093af078c79.gif)

It's super annoying because I work very fast, and this has started hitting me constantly. I believe the lag only showed up in 1.7.x, which I recently upgraded to.

I don't have any keymap stuff that should interfere here.

### Steps to Reproduce

1. Select text.
2. Hit `cmd-C` to copy.
3. Hit `cmd-F` to find.
4. Hit `cmd-V` to paste.

**Expected behavior:** Selected text to be pasted.

**Actual behavior:** Previous contents of the clipboard is pasted. If I wait a little bit, pasting pastes the correct content.

### Versions

```
# atom --version
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

OS X 10.11.4.

**Comment by atombender** [comment] 2016-04-24 01:41
@50Wliu: There's an easy way to reproduce. Select a word with `cmd-D`. Hold down cmd. Then rapidly press C, F and V while still holding the cmd key.

When I tested this, I often found that pasting appends to, rather than replaces, whatever is already in the find field. So the find field has "foo" in there and I copy "bar", do `cmd-F` and `cmd-V`, I often end up with "foobar" in the find field, even though it's supposed to initially select the entire contents of the field so that a paste will overwrite it.

I went back to 1.6.2 and tried to replicate it, and I can't. So I'd say this is definitely a 1.7.x regression. Any idea what change could cause this?

**Comment by Ben3eeE** [comment] 2016-04-27 12:18
This might be a duplicate of https://github.com/atom/find-and-replace/issues/684 which was discovered and introduced in 1.7.0 beta. This issue that @atombender reported has an additional step of pasting the clipboard contents which seems to happen before the find field gets replaced by https://github.com/atom/find-and-replace/issues/684. At least this is what my investigation shows when backtracking in the find field with `ctrl-z` after doing the steps described in these issues.

@atombender I guess as a workaround you could skip the copy and paste steps? For me at least selecting some text and opening the search-and-replace with `ctrl-f` also searches for the selected text.

I am using atom 1.7.2 on windows 7.

cc @50Wliu duplicate?

**Comment by atombender** [comment] 2016-04-27 19:36
@Ben3eeE: That does sound likely. I can of course work around the problem by not copy/pasting, or simply waiting a fraction of a second before pasting, but I'm so used to working like this — I don't want to be slowed down.

**Comment by 50Wliu** [comment] 2016-04-27 20:44
Closing in favor of atom/find-and-replace#684, then.

**Closed by 50Wliu** 2016-04-27 20:44 UTC
Labels: needs-reproduction
