### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by meafmira** [atom/atom#14228] opened 2017-04-16 20:15 UTC
[Enter steps to reproduce:]

1. Install Atom
2. Open project folder

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Object.tildify (/app.asar/node_modules/fs-plus/lib/fs-plus.js:64:39)
    at Workspace.updateWindowTitle (/app.asar/src/workspace.js:259:24)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/app.asar/src/project.js:288:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/app.asar/src/atom-environment.js:1195:26)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:229:18)
    at emitThree (events.js:121:20)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:09.6.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-04-17 20:42
I was going to close as a dupe of https://github.com/atom/atom/issues/14228 but the stack traces are slightly different.  Just to confirm though, were the steps to reproduce the same in both issues?

**Comment by meafmira** [comment] 2017-04-17 21:33
@rsese yes

**Comment by rsese** [comment] 2017-04-18 17:23
Closing per https://github.com/atom/atom/issues/14227#issuecomment-294917485.

**Closed by rsese** 2017-04-18 17:23 UTC
Labels: more-information-needed
