### ISSUE TITLE
Syntax highlighting issue in TypeScript files

### ISSUE THREAD

**Issue by ElecTreeFrying** [atom/atom#20332] opened 2020-01-20 09:21 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. download atom in https://atom.io/
2. download atom-typescript package in https://atom.io/packages/atom-typescript
3. check if language-typescript in Core Packages is installed/enabled

**Expected behavior:**

TypeScript files should have syntax highlighting.

**Actual behavior:**

No syntax highlighting in *.ts files.

### Versions

v1.43.0

### Additional Information

Syntax highlighting works perfectly fine on other file types. I already checked .html, .json, .scss, .json and even in other file types. Only typescript files have no syntax highlighting. 

I already tried downloading and checking if maybe the syntax highlighting works in Beta and Nightly version but still no syntax highlighting at all.

**Comment by sirpask** [comment] 2020-01-20 13:42
Maybe this interests you, and it's related.
https://github.com/atom/atom/issues/20330#issuecomment-575848797

**Comment by darangi** [comment] 2020-01-20 15:06
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-typescript/issues/47. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2020-01-20 15:06 UTC
Labels: duplicate, wrong-repo
