### ISSUE TITLE
"Updating" status hangs while updating packages

### ISSUE THREAD

**Issue by pronkman** [atom/atom#7682] opened 2015-07-03 12:31 UTC
During package updates the "Updating" status of many (not all) packages doesn't seem to change to "Updated" even after the updates have been successfully installed. I can see the updates were successfully installed by clicking "Check for Updates" again after which the "Updating" message disappears and I get the message "All of your installed packages are up to date!".

The issue only appeared after the 1.0.0 release and mostly with some of the larger packages. I realise that larger packages take longer to install but I've tested by waiting more than 10 min and then checking for updates again.

This is not a major issue – in the past I usually waited for conformation that all packages were installed before I continued working where now I have to allow enough time to ensure the process has successfully run.

System specs:
MacBook Pro 17" 2011
Mac OS X Yosemite (10.10.4)
Atom Version 1.0.0

Thx!
(PS. I've tried pretty much all available editors and Atom is by far the best.)

**Comment by mnquintana** [comment] 2015-07-03 12:39
Thanks for the report! This is a duplicate of https://github.com/atom/settings-view/issues/532 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-03 12:39 UTC
