### ISSUE TITLE
AltGr-o (right alt) resolves in Windows version of Atom as Ctrl-Alt-o

### ISSUE THREAD

**Issue by jnareb** [atom/atom#7075] opened 2015-06-03 11:38 UTC
I am trying to use Atom to edit contents in Polish language. The default and preferred keyboard bindings, so called "programmers keyboard", uses AltGr (right Alt) to enter Polish letters: ą, ć, ę, ł, ń, ó, ś, ż, ź.

The problem is that the Atom editor (or perhaps MS Windows 7 Home Pro) represents AltGr-o, which is used to enter 'ó' character, as Ctrl-Alt-o... which keybinding is taken by Atom as application:add-project-folder. This makes it hard to use Atom for content in Polish language...

**Comment by batjko** [comment] 2015-06-03 11:48
Sounds like another duplicate of [this issue](https://github.com/atom/atom-keymap/issues/35) on the keymap repo.

Alt-Gr is simply not supported yet so will produce bad behavior. Check that issue for updates when there are any.

**Comment by mnquintana** [comment] 2015-06-03 11:59
Thanks @batjko! This does indeed seem like a duplicate of https://github.com/atom/atom-keymap/issues/35 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-03 11:59 UTC

**Comment by erroid** [comment] 2017-01-20 17:16
any fast solution for now?

**Comment by Ben3eeE** [comment] 2017-01-20 17:20
@erroid This should be fixed in Atom 1.13, 1.14-beta if you are on Linux. If you still are having problems after updating please open a new issue in the [atom-keymap](https://github.com/atom/atom-keymap/issues) repository and fill out the issue template completely.
