### ISSUE TITLE
Weird font rendering on Linux

### ISSUE THREAD

**Issue by edomato** [atom/atom#15962] opened 2017-10-22 02:28 UTC
I'm experiencing a weird font rendering in Linux and an image and animation can explain it better than my English since it's not my native language :smile:

![screenshot](https://user-images.githubusercontent.com/1550373/31857567-014ecde4-b6b8-11e7-966f-9515a67f0d87.png)

As you can see in the image, the word that is highlighted is "repository" but the first appearance in the image seems to be "reppsitory" instead. In the Developer Tools you can clearly see that the word is "repository".

![capture](https://user-images.githubusercontent.com/1550373/31857570-0d0c4d46-b6b8-11e7-9135-92039de24af1.gif)

In the animation, you can see that the "o" in "repository" word changes when I start adding spaces.

I tested in last stable and beta version. In safe mode and also moving the .atom directory.

One thing that seems to fix the problem is changing the font size, but with the default size (that's 14) this is how is rendering.

Let me know if you need any other information.
Thanks.
Ernesto

**Comment by 50Wliu** [comment] 2017-10-22 09:53
What version of freetype are you using?

**Comment by edomato** [comment] 2017-10-22 13:39
It's 2.8.1 so, do you think that could be related with #15737?

On other editors that use the same freetype library version doesn't happens.

**Comment by 50Wliu** [comment] 2017-10-22 13:45
Yes, in that case I'm closing this as a duplicate of #15737.  Other editors use different font rendering technologies.

**Closed by 50Wliu** 2017-10-22 13:45 UTC
Labels: more-information-needed

**Comment by edomato** [comment] 2017-10-22 16:07
Oh, ok, so it's a problem of the rendering engine with the freetype library. Thanks.

**Comment by sandorex** [comment] 2018-04-01 00:14
ok i have same issue using debian testing, is it fixable or we need to wait for next version of freetype ?
