### ISSUE TITLE
Toggle Soft Tabs fails from Atom Preferences

### ISSUE THREAD

**Issue by jkarimi91** [atom/atom#7605] opened 2015-06-30 22:23 UTC
Toggling Atom's Soft Tabs setting from Preferences\Settings\Editor Settings has no effect.
The only way to toggle the setting is using Editor: Toggle Soft Tabs from the Command Palette

**Comment by mnquintana** [comment] 2015-10-09 15:59
I think this is a duplicate of https://github.com/atom/atom/issues/6203 - let me know if I'm misunderstanding though!

**Closed by mnquintana** 2015-10-09 15:59 UTC
