### ISSUE TITLE
Atom fails to open project root from cmd

### ISSUE THREAD

**Issue by ndland** [atom/atom#12141] opened 2016-07-11 17:49 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

If there is an existing instance of Atom running, I am unable to open any other files/directories from the command line. If there isn't an existing instance of Atom running, I'm able to open files/directories as normal with `atom -a dir/` or `atom filename`.
### Steps to Reproduce

1. Open Atom
2. Attempt to open a file/directory using `atom -a dir/` or `atom filename`

**Expected behavior:** 

Expect that when Atom is open, I can open a new file or directory using `atom filename` or `atom -a dir/`.

**Actual behavior:**

When I try to open up a file or directory, Atom doesn't do anything at all. It looks like Atom is opening on my system, but then the app quickly closes. Note, this is independent of the existing running instance of Atom.

Here is the stack trace from `/var/log/system.log`

```
Jul 11 13:46:52 SIA-MC-W01PG3QC loginwindow[91]: -[SFLListManager(ServiceReplyProtocol) notifyChanges:toListWithIdentifier:] Notified of item changes to list with identifier com.apple.LSSharedFileList.RecentApplications
Jul 11 13:46:52 SIA-MC-W01PG3QC iTerm2[42729]: Time to encode state for window <PseudoTerminal: 0x7fe60062d500 tabs=1 window=<PTYWindow: 0x7fe60072a0c0 frame=NSRect: {{-1080, 60}, {1074, 1881}} title=1. tmux alpha=1.000000 isMain=0 isKey=0 isVisible=1 delegate=0x7fe60062d500>>: 0.00199204683303833
Jul 11 13:46:52 SIA-MC-W01PG3QC Atom[6463]: App load time: 320ms
Jul 11 13:46:52 SIA-MC-W01PG3QC Atom[90817]: Unexpected end of input
Jul 11 13:46:52 SIA-MC-W01PG3QC Atom[90817]: SyntaxError: Unexpected end of input
            at Object.parse (native)
            at Socket.<anonymous> (/Users/nland/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:244:28)
            at emitOne (events.js:77:13)
            at Socket.emit (events.js:169:7)
            at readableAddChunk (_stream_readable.js:146:16)
            at Socket.Readable.push (_stream_readable.js:110:10)
            at Pipe.onread (net.js:523:20)
Jul 11 13:46:52 SIA-MC-W01PG3QC Atom[90817]: Unexpected token r
Jul 11 13:46:52 SIA-MC-W01PG3QC Atom[90817]: SyntaxError: Unexpected token r
            at Object.parse (native)
            at Socket.<anonymous> (/Users/nland/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:244:28)
            at emitOne (events.js:77:13)
            at Socket.emit (events.js:169:7)
            at readableAddChunk (_stream_readable.js:146:16)
            at Socket.Readable.push (_stream_readable.js:110:10)
            at Pipe.onread (net.js:523:20)
```

### Versions

apm version `1.9.2`
atom version `1.8.0`

Running on osx `10.11.5`

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by lee-dohm** [comment] 2016-07-12 06:45
As I stated on the message board, I couldn't reproduce this despite running the same general configuration. I'm going to leave this open for a while to see if we can get more information.

**Comment by 50Wliu** [comment] 2016-07-12 09:29
Looks similar enough to #11712, so closing in favor of that issue.

**Closed by 50Wliu** 2016-07-12 09:29 UTC
Labels: more-information-needed
