### ISSUE TITLE
High latency loading network mapped files

### ISSUE THREAD

**Issue by kevin-y** [atom/atom#9506] opened 2015-11-10 07:22 UTC
I have a remote server with samba server installed. I shared one directory on the server and mapped the dir to my local windows machine.
When I tried to add the directory as project folder into Atom, it took a very long time to load the first level dirs and files.
I also tried to load the remote dir into sublime, the loading is pretty fast. 
Do you guys have any idea about this? I prefer Atom better, but the latency is not bearable for me.

Environments:
OS: Windows 7 64bit ultimate
lastest Atom Text Editor

Thanks.

**Comment by thomasjo** [comment] 2015-11-10 07:27
Duplicate of https://github.com/atom/atom/issues/1766. Please subscribe there for updates.

**Closed by thomasjo** 2015-11-10 07:27 UTC
