### ISSUE TITLE
Open recent?

### ISSUE THREAD

**Issue by masedesign** [atom/atom#7565] opened 2015-06-29 23:04 UTC
Would be nice to be able to open recent projects or window configurations instead of having to digging and adding a dir to a window every time I decide to close it and re open it later.

**Comment by mnquintana** [comment] 2015-06-29 23:23
This is a duplicate of https://github.com/atom/atom/issues/4241 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-29 23:23 UTC

**Comment by kevinmickey** [comment] 2015-07-28 03:42
Fixed link to issue: #4241
