### ISSUE TITLE
An error occurred, view the console for more information.

### ISSUE THREAD

**Issue by rayk** [atom/atom#17220] opened 2018-04-26 04:36 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

An error occurred, view the console for more information.

```
At undefined

undefined
```

### Commands

```
     -0:51.9.0 application:open (input.hidden-input)
     -0:12.8.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -0:10 application:add-project-folder (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
atom-yarn 0.7.0 
autocomplete-json 5.5.2 
busy-signal 1.4.3 
file-icons 2.1.19 
flow-ide 1.11.0 
git-plus 7.10.2 
hyperclick 0.1.5 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
prettier-atom 0.53.0 
pretty-json 2.0.0 
teletype 0.13.1 
```

**Comment by rsese** [comment] 2018-04-26 17:38
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

Also, can you share a screenshot of what you see in [devtools console](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools)?

**Comment by rsese** [comment] 2018-05-11 18:14
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17220#issuecomment-384726357. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-05-11 18:14 UTC
Labels: more-information-needed, uncaught-exception

**Comment by paulcalabro** [comment] 2018-05-11 20:04
Hi, I'm experiencing the same error. 
Answers to your questions:

- Opening Atom
- Every time I open Atom
- I do not.

**Comment by paulcalabro** [comment] 2018-05-11 20:10
For me, it looks like it was an issue with the **atom-yarn** package. I removed that an the issue went away.

**Comment by rsese** [comment] 2018-05-15 23:03
> For me, it looks like it was an issue with the atom-yarn package. I removed that an the issue went away.

Thanks for tracking that down, looks like the OP has atom-yarn installed as well.

Since it appears that this is being caused by [atom-yarn](https://atom.io/packages/atom-yarn), we'll need the maintainer of the package to help track that down. You can file this issue on their repository so they can either fix the problem or tell us where the problem is coming from since the bug could still be in Atom. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
