### ISSUE TITLE
Updating Atom on Windows creates a new shortcut on the desktop

### ISSUE THREAD

**Issue by mshindal** [atom/atom#10008] opened 2015-12-10 23:14 UTC
Seems that every time Atom updates, it creates a new shortcut on the desktop for Atom.

**Comment by mjohnsonengr** [comment] 2015-12-11 00:59
I don't like this either.

**Comment by 50Wliu** [comment] 2015-12-11 02:25
This is a duplicate of #5323, please subscribe there for updates.

**Closed by 50Wliu** 2015-12-11 02:25 UTC
