### ISSUE TITLE
Cant open folder mounted locally with sshfs

### ISSUE THREAD

**Issue by bitswarming** [atom/atom#8592] opened 2015-08-31 08:29 UTC
Cant open remote folder mounted with "sudo sshfs -o allow_other ....." .
Sublime and others -  can.
Just receive Editor is not responding message.
Linux.

**Comment by mnquintana** [comment] 2015-08-31 11:57
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/2456 / https://github.com/atom/atom/issues/1766 – please subscribe there for updates.

**Closed by mnquintana** 2015-08-31 11:57 UTC
