### ISSUE TITLE
Pasting or typing instead of selected text results in random selection

### ISSUE THREAD

**Issue by stervo4ka** [atom/atom#5200] opened 2015-01-21 23:01 UTC
When I select some text and then paste something instead of it, sometimes I get random piece of the pasted text being selected. Look at the screencast:
![atom_paste_instead_selection](https://cloud.githubusercontent.com/assets/7574192/5847084/71d1d11a-a1da-11e4-93f3-d76f59c67e5c.gif)
Here I'm selecting pieces of text and pasting some other text. In one of three times it results in a part of the pasted text being selected.

It leads to some inconvenience in my work. After I replace selected text with text from the clipboard, I should check whether something is selected before I type anything (because the text I'm typing will replace the selection).

The same when I start typing while some text is selected. The typed symbol replaces the selection, but sometimes it becomes selected itself. So when I type the second symbol, it replaces the first one.

The behaviour which I observe in other text editors is: replace selected text with pasted/typed one, deselect anything, place the cursor after the pasted text. This is the most convenient option, I guess.

My Atom version is 0.175.0 (and I've observed it in all previous versions), my system - OS X 10.9.5.

**Comment by 50Wliu** [comment] 2015-01-21 23:07
Can you replicate this in safe mode (`atom --safe`)?

**Comment by stervo4ka** [comment] 2015-01-21 23:11
@50Wliu Yep. It happens in safe mode too.

**Comment by mnquintana** [comment] 2015-01-21 23:37
I was able to reproduce this in OS X 10.10.1 and Atom 0.175.0 but it took like, 30 tries going rapidfire. For me, I sometimes end up with both a random selection and a blinking cursor.

**Comment by mnquintana** [comment] 2015-01-24 20:10
This might be related to (or a duplicate of, not sure) #5243

**Closed** 2015-08-19 20:13 UTC
Labels: bug
