### ISSUE TITLE
Recursive copy crushed

### ISSUE THREAD

**Issue by alt-123** [atom/atom#12611] opened 2016-09-06 21:10 UTC
I copied folder in tree view into itseft accidentally. Atom starts recursive copy and crushed. Now I cant delete this folder any way (Long Path).

Atom 1.10.0, Windows 7 Professional 64 bit.

**Comment by Ben3eeE** [comment] 2016-10-05 07:39
This is a duplicate of https://github.com/atom/tree-view/issues/656. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-05 07:39 UTC
