### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by ayyrickay** [atom/atom#15028] opened 2017-07-15 00:05 UTC
[Enter steps to reproduce:]

1. Use Github tab in Atom Beta
2. Click on a file name from the tab while resolving merge conflicts

NOTE: This is not happening for all files. I'm not sure what the difference was with this particular file.

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2145

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2145:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2141:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:382:16)
    at scheduler.readDocument (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:266:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -2:40.2.0 core:save (input.hidden-input)
     -2:31.9.0 core:backspace (input.hidden-input)
     -2:30.2.0 core:save (input.hidden-input)
     -1:50.5.0 core:cut (input.hidden-input)
     -1:48.9.0 editor:newline (input.hidden-input)
     -1:48.6.0 core:paste (input.hidden-input)
     -1:47.9.0 core:backspace (input.hidden-input)
     -1:46.9.0 core:move-down (input.hidden-input)
     -1:46.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:46.3.0 core:backspace (input.hidden-input)
  2x -1:45.2.0 core:save (input.hidden-input)
  2x -1:06.5.0 core:undo (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -0:58 core:copy (input.hidden-input)
  3x -0:54.1.0 core:backspace (input.hidden-input)
     -0:48 core:paste (input.hidden-input)
  2x -0:46.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
autocomplete-robot-framework 3.3.0 
busy-signal 1.4.3 
file-icons 2.1.8 
highlight-selected 0.13.1 
intentions 1.1.2 
language-javascript-jsx 0.3.7 
language-robot-framework 2.2.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.2 
minimap 4.28.3 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
prettier-atom 0.36.1 
```

**Comment by rsese** [comment] 2017-07-18 01:15
Thanks for the report!  Stacktrace looks pretty close to https://github.com/atom/atom/issues/14794 so closing as a duplicate - it sounds like you can reproduce with a specific file but if you can confirm if the error is reproducible in safe mode (`atom --safe`), please let us know in the issue!

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14794. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-18 01:15 UTC
