### ISSUE TITLE
Available Updates: icon for git repo is broken

### ISSUE THREAD

**Issue by brendanfalkowski** [atom/atom#8163] opened 2015-07-31 03:14 UTC
Atom 1.0.3 / Mac

When updating packages, the repo icon is always broken. Have observed for a few weeks assuming it would clear up, but it's still happening with every package. Looks like this:

![screen shot 2015-07-30 at 11 12 55 pm](https://cloud.githubusercontent.com/assets/214924/9000104/c49af374-3710-11e5-9027-1708ffba2aae.png)

**Comment by mnquintana** [comment] 2015-07-31 04:58
This is a duplicate of https://github.com/atom/settings-view/issues/595 – please subscribe there for updates.

(Also see https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290?u=mnquintana for a guide to where to post issues)

**Closed by mnquintana** 2015-07-31 04:58 UTC

**Comment by brendanfalkowski** [comment] 2015-07-31 05:03
Sorry, didn't know where to post exactly. I went to "Help > Report Issue" which takes you here:
https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues

It might be good to provide a link from there to here because it's more informative:
https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290
