### ISSUE TITLE
Keyboard layout problem (AZERTY)

### ISSUE THREAD

**Issue by cyChop** [atom/atom#7980] opened 2015-07-20 08:24 UTC
We have detected a problem with a specific AZERTY.

### The problem

The whole keyboard seems to be correctly interpreted, except for `[`. When trying to type this character, only `Alt Gr + 5` seems to work, as if this was the traditional French layout. The normal key combination does not produce any character.

No error is printed to the console.

### The layout we use

[![Belgian AZERTY layout](https://upload.wikimedia.org/wikipedia/commons/4/41/Belgian_pc_keyboard.svg)](https://commons.wikimedia.org/wiki/File:Belgian_pc_keyboard.svg)

### Traditional French layout

[![French AZERTY layout](https://upload.wikimedia.org/wikipedia/commons/b/b9/KB_France.svg)](https://commons.wikimedia.org/wiki/File:KB_France.svg)

### System info

Atom 1.0.2 (out of the box, no additional package)
Windows 7

---
<small>Keyboard layout images: Wikimedia (click each picture for the source page)</small>

**Comment by mnquintana** [comment] 2015-07-20 10:43
I think this is a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37 – let's keep the discussion there.

**Closed by mnquintana** 2015-07-20 10:43 UTC

**Comment by cyChop** [comment] 2015-07-20 10:49
Did not see. Thanks for the link.

**Comment by rams3s** [comment] 2015-08-26 17:33
Using the Key Binding Resolver and trying to type '[' on a Belgian French keyboard turned out to be interpreted as  'ctrl-alt-]'.

The following entry in my keymap configuration fixed the issue:
```javascript
'.platform-win32 atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-]': 'unset!'
```

**Comment by cyChop** [comment] 2015-08-26 19:11
Yup, thanks @rams3s . I found it with the keybinding resolver. Still, I lose the ability to fold lines from the keyboard.
