### ISSUE TITLE
Graphical glitches on file selector when opening folders

### ISSUE THREAD

**Issue by nicolasblanco** [atom/atom#5508] opened 2015-02-12 02:37 UTC
Hi,
this kind of graphical glitches open very often when opening folders in the file selector, is there already an issue for these?

Thanks!

OS X 10.10.2, Atom 0.179, MacBookPro Retina display.

![screen shot 2015-02-12 at 13 33 14](https://cloud.githubusercontent.com/assets/12682/6160832/1d74c184-b2bc-11e4-946c-5a56e4aa8342.png)

**Comment by kevinsawicki** [comment] 2015-02-12 02:47
I believe this is a duplicate of #4924

**Closed by kevinsawicki** 2015-02-12 02:47 UTC
