### ISSUE TITLE
Quick file/folder add disappears when Atom loses focus

### ISSUE THREAD

**Issue by jasoncavett** [atom/atom#5754] opened 2015-02-26 01:15 UTC
**Version**: 1.184.0
**OS**: OSX
**Problem Description**: I am using the quick file/folder add feature when I use the file explorer right-click functionality to add a new file. When the dialog appears, if, for any reason, I move away from the app, it disappears. On OSX, this can be if I switch applications, three-finger swipe away, etc. Minor, but annoying from a UX perspective.
**Expected**: With most other dialogs, the dialog stays around despite loss of focus of the application.

**Steps to Reproduce**
1. Right click on a folder that is showing in the file navigator.
2. Chose *New File*
3. Swipe away/switch away from the app.
4. Dialog is gone.

**Comment by izuzak** [comment] 2015-02-26 11:52
Thanks for the feedback! I think this is a duplicate of https://github.com/atom/atom/issues/1918. Can you add a comment to that issue please?

**Closed by izuzak** 2015-02-26 11:52 UTC
Labels: bug

**Comment by izuzak** [comment] 2015-02-26 11:54
And let me know if I misunderstood your report -- I think this is a specific instance of that more general issue.

**Comment by jasoncavett** [comment] 2015-02-26 15:05
Thanks @izuzak. Apologies for missing that bug when I did my search. I'll update with a comment on #1918.
