### ISSUE TITLE
git-diff package support sub-folders which are different git repositories.

### ISSUE THREAD

**Issue by scriptnull** [atom/atom#19966] opened 2019-09-26 11:23 UTC
## Summary

Currently git-diff works by analysing the `.git` folder specified in root folder in which atom is open.

```
root-folder
|__ .git
|__ src/
|__ tests/
```

This feature is about making it work even if the git repository is a sub-folder of the root folder.
```
root-folder
|__ project-a
    |__ .git
    |__ src/
    |__ tests/
|__ project-b
    |__ .git
    |__ src/
    |__ tests/
```

Right now, project-a and project-b are not getting git-diff support. `git-diff` package should use their repective `.git` files to show the diff.

It would be good to have `Pattern` field in settings of this package to match against the patterns of where .git folder could be found. Example, for my above case, I would mention the pattern to be `*/.git`. If this pattern is not found. git-diff only matches against the root (i.e. default pattern is `.git`)

## Motivation

Sometimes, we tend to open up the root folder that contains multiple projects that has dependency on each other, but maintained in a separate git repo. 

## Describe alternatives you've considered

I considered searching for a Pattern setting in the git-diff package. But it doesn't exist. Hence the request.

## Additional context

None.

**Comment by lee-dohm** [comment] 2019-09-26 15:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/1835. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2019-09-26 15:56 UTC
