### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by clayzermk1** [atom/atom#5912] opened 2015-03-09 23:38 UTC
1. Make lots of changes to a file.
2. Undo a lot of times.

**Atom Version**: 0.186.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'slice' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:559

TypeError: Cannot read property 'slice' of undefined
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:559:41)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:74:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:60:29)
  at History.module.exports.History.undo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:87:24)
  at TextBuffer.module.exports.TextBuffer.undo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:679:27)
  at TextEditor.module.exports.TextEditor.undo (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1206:26)
  at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:312:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:280:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -8:31.5 core:backspace (atom-text-editor.editor.is-focused)
  2x -8:30.3 core:save (atom-text-editor.editor.is-focused)
  4x -1:15.7 core:move-right (atom-text-editor.editor.mini)
     -1:13.9 core:confirm (atom-text-editor.editor.mini)
undefined -1:10.7 core:undo (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  9x -0:23.1 core:redo (atom-text-editor.editor.is-focused)
  8x -0:07.7 core:undo (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "showInvisibles": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
compare-files, v0.4.1
emmet, v2.3.4
language-ejs, v0.1.0
monokai, v0.12.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-09 23:51
Duplicate of #4619, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-09 23:51 UTC

**Comment by campside** [comment] 2017-01-18 08:00
I still get this issue 

/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:872
Hide Stack Trace
TypeError: Cannot read property 'slice' of undefined
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:687:39)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:916:16)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:870:14)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1566:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1143:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2540:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2506:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1141:19)
    at TextEditor.module.exports.TextEditor.pasteText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2971:19)
    at TextEditor.core:paste (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:437:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:666:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:867:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1566:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:665:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)

**Comment by Ben3eeE** [comment] 2017-01-18 08:05
@campside What were you doing when you got this exception?

**Comment by campside** [comment] 2017-01-18 10:46
I copy/paste a big piece of text from browser window into the editor

**Comment by campside** [comment] 2017-01-18 10:48
+ it is encoded and really huge, looks like this - http://prntscr.com/dx51t0

**Comment by nathansobo** [comment] 2017-01-18 16:11
This issue is closed because of changes on the master branch. It won't be fixed on the beta channel until the hotfix goes out later today.

**Comment by jrial** [comment] 2017-05-05 08:42
Still getting it though, Atom version 1.16.0 x64

Was this issue erroneously closed?

My report looks like this:

[Enter steps to reproduce:]

1. Make a bunch of changes
2. Quickly undo or redo these changes by holding down ctrl-z or ctrl-y

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'slice' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:631

TypeError: Cannot read property 'slice' of undefined
    at TextBuffer.module.exports.TextBuffer.applyChange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:631:41)
    at TextBuffer.module.exports.TextBuffer.redo (/app.asar/node_modules/text-buffer/lib/text-buffer.js:808:16)
    at /app.asar/src/text-editor.js:1587:31
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2568:43)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (/app.asar/src/text-editor.js:2554:35)
    at TextEditor.module.exports.TextEditor.redo (/app.asar/src/text-editor.js:1585:12)
    at /app.asar/src/register-default-commands.js:310:21)
    at /app.asar/src/register-default-commands.js:647:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -4:04.2.0 intentions:highlight (input.hidden-input)
     -4:04.1.0 editor:move-line-down (input.hidden-input)
     -4:01.1.0 intentions:highlight (input.hidden-input)
     -4:00.9.0 core:save (input.hidden-input)
  2x -3:56.2.0 intentions:highlight (input.hidden-input)
  8x -3:49 editor:move-line-down (input.hidden-input)
     -3:46.7.0 core:move-up (input.hidden-input)
     -3:46.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:46.2.0 editor:newline (input.hidden-input)
     -3:45.4.0 intentions:highlight (input.hidden-input)
     -3:45.2.0 core:save (input.hidden-input)
     -3:39.6.0 intentions:highlight (input.hidden-input)
 22x -3:39.3.0 core:undo (input.hidden-input)
     -3:37.2.0 core:save (input.hidden-input)
     -0:07.4.0 intentions:highlight (input.hidden-input)
     -0:07.0 core:redo (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-cli-diff 1.9.0 
atom-django 0.3.2 
atom-meld 0.3.3 
atom-python-virtualenv 0.9.0 
atom-transpose 0.3.4 
autocomplete-python 1.8.63 
blame 0.10.3 
busy-signal 1.4.1 
custom-title 1.0.1 
data-atom 0.25.1 
DjangoRAD 0.0.1 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-watcher 1.1.0 
git-plus 7.8.0 
git-time-machine 1.5.9 
hyperclick 0.0.40 
indent-guide-improved 1.4.12 
intentions 1.1.2 
language-django 0.1.1 
language-nginx 0.7.3 
linter 2.1.4 
linter-pycodestyle 2.0.2 
linter-pylint 2.0.1 
linter-ui-default 1.2.3 
local-history 4.0.1 
merge-conflicts 1.4.4 
minimap 4.28.2 
minimap-linter 2.0.0 
monokai 0.22.0 
open-terminal-here 2.3.0 
persistent-undo 1.2.0 
project-manager 3.3.4 
python-tools 0.6.9 
selection-highlight 0.1.6 
sort-lines 0.14.0 
symbols-tree-view 0.14.0 
tag 0.5.0 
termination 0.5.1 
up2date 0.1.2 
Zen 0.16.4 
```

**Comment by nathansobo** [comment] 2017-05-05 15:34
@ungb can you try to reproduce this and reopen if you can?

**Comment by samaphp** [comment] 2017-05-14 11:56
Faced the same issue, can't reproduce it but it has the same error line:
Atom: 1.16.0 x64
OS: Mac OS X El Capitan 10.11.6

**Non-Core Packages:**
```
atom-autocomplete-php
atom-drupal-api
block-comment-plus
docblockr
docs-snippets
gitignore-snippets
gloom
hey-pane
linter
linter-drupalcs
snippet-generator
tabs-closer
zentabs
```

Many Thanks

**Comment by ungb** [comment] 2017-05-16 21:12
I am unable to repro this issue on mac using repro steps from https://github.com/atom/atom/issues/5912#issuecomment-299412564,  I can try mint linux and see.  

@samaphp, do you have any more info on what you were doing when you saw the issue?
