### ISSUE TITLE
Uncaught Error: spawn /Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.Hy...

### ISSUE THREAD

**Issue by mbaudis** [atom/atom#10805] opened 2016-02-13 09:42 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Users/mbaudis/Library/Application Support/com.github.atom.ShipIt/update.HyaxfFM/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false
  },
  "editor": {
    "fontSize": 16,
    "invisibles": {},
    "lineHeight": 1.3,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2016-02-13 17:25
Thanks for the report! This looks like a duplicate of #9559 though – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-02-13 17:25 UTC

**Comment by joshaber** [comment] 2016-02-14 19:16
@mbaudis Thanks! Do you recall how you launched Atom when you got this?

**Comment by mbaudis** [comment] 2016-02-14 19:53
Sorry for lazyness. Could have been OS X Finder's "open with". There seems to be a background installation of upgrade versions, so that then 2 versions show up (and I obviously select the newest one - not knowing which is running already).

Not sure if it's this, or if this is just another problem.

Also, not stable for large (some hundred MB ...) text files. This is the main reason I still keep BBedit around ...
