### ISSUE TITLE
Atom packages broken avatar images

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#8058] opened 2015-07-24 08:58 UTC
Recently, I'm seeing a lot of these broken avatar images for packages:

![ss](https://www.dropbox.com/s/m35tfpv7cyv9o6g/Screenshot%202015-07-24%2020.55.39.png?dl=1)

They are supposedly coming from the cache, but for some reason don't show up:

![ss](https://www.dropbox.com/s/is2peuxofj20wh8/Screenshot%202015-07-24%2020.58.05.png?dl=1)

**Comment by batjko** [comment] 2015-07-24 11:24
Duplicate of either https://github.com/atom/settings-view/issues/327 or https://github.com/atom/settings-view/issues/327, or both.

**Comment by mnquintana** [comment] 2015-07-24 12:10
Thanks @batjko! This is indeed a duplicate of https://github.com/atom/settings-view/issues/327 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-24 12:10 UTC

**Comment by adambuczynski** [comment] 2015-07-24 19:22
Excellent, thank you.
