### ISSUE TITLE
minify js files cause lag and results in crash of atom

### ISSUE THREAD

**Issue by Modularfield** [atom/atom#7789] opened 2015-07-08 13:46 UTC
Operating System: OS X 10.10.02 
Atom Version: 1.0.0

Steps to reproduce: Open a minified js file of your choice (If your cool choose a large one)

Atom Responds after a while:  Editor is not responding Dialog

**Comment by mnquintana** [comment] 2015-07-08 13:58
This is a duplicate of github.com/atom/atom/issues/979 - please subscribe there for updates.

**Closed by mnquintana** 2015-07-08 13:58 UTC
