### ISSUE TITLE
Auto indent on paste not working as expected

### ISSUE THREAD

**Issue by joelanman** [atom/atom#12131] opened 2016-07-09 18:57 UTC
### Description

When I copy and paste a block of code in Atom, it always adds more indentation, regardless of "Auto indent on paste" setting.

### Steps to Reproduce

1. Copy block of code
2. Paste block of code
3. Change the  'Auto indent on paste'  setting and repeat

**Expected behavior:**

I'd expect one of the 'Auto indent on paste' settings to mean that the pasted block has the same indentation as the copied block - this is what I need, and what happens in Sublime.

**Actual behavior:**

The pasted block is always indented further to the right.

### Versions

Atom 1.8.0
OSX 10.10.5

**Comment by joelanman** [comment] 2016-07-09 18:58
This capture went a bit wonky, but you can see the issue

![atom-paste-indent](https://cloud.githubusercontent.com/assets/1132904/16709688/6c127a7e-460f-11e6-9705-ebd878ba8a65.gif)

**Comment by sevenupcan** [comment] 2016-07-10 09:38
👍  same issue for me

**Comment by lee-dohm** [comment] 2016-07-12 06:59
This is a duplicate of https://github.com/atom/atom/issues/10407. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-12 06:59 UTC
