### ISSUE TITLE
Ugly font and overlapping close tab on text

### ISSUE THREAD

**Issue by dkorzhevin** [atom/atom#12137] opened 2016-07-11 05:38 UTC
Hello,

Please, take a look on screenshot, you will see problem:

http://i.piccy.info/i9/ad696a508bff2bdb5bdfceeb944b25f2/1468215440/5940/1050747/atom_180_ugly_icons.png

I'm using Atom 1.8.0 under windows 8.1

**Comment by thomasjo** [comment] 2016-07-11 05:56
Closing as duplicate of https://github.com/atom/one-light-ui/issues/59, and will be fixed in an upcoming relase of Atom.

**Closed by thomasjo** 2016-07-11 05:56 UTC
