### ISSUE TITLE
Packages not "Clickable" to find out more

### ISSUE THREAD

**Issue by Phorce** [atom/atom#5741] opened 2015-02-25 16:06 UTC
So when you want to find more about a particular package, it is not possible.

For example:

![annoying3](https://cloud.githubusercontent.com/assets/878780/6374348/2e1a24a6-bd08-11e4-95a6-bcbca37e15fd.png)

If I want to know what "color-picker" is, I can't since it won't allow me to go into the pane to find out more. This also does not work for many other packages and means I have to sometimes install them, to find out more. 

This is on Windows.

**Comment by izuzak** [comment] 2015-02-25 16:19
Closing as a duplicate of https://github.com/atom/settings-view/issues/328. 

Also, please :eyes: the notes on submitting issues, they offer some useful advice on creating bug reports and feature requests (in this case, advice on opening the issue in the issue tracker for the package you have feedback on):

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues

**Closed by izuzak** 2015-02-25 16:19 UTC
