### ISSUE TITLE
Uncaught TypeError: Patch does not apply

### ISSUE THREAD

**Issue by MadMax888** [atom/atom#15516] opened 2017-08-31 11:18 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Patch does not apply

```
At C:\...\AppData\Local\atom\app-1.19.4\resources\app\node_modules\text-buffer\lib\history.js:144

TypeError: Patch does not apply
    at History.module.exports.History.getChangesSinceCheckpoint (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/history.js:144:34)
    at TextBuffer.module.exports.TextBuffer.getChangesSinceCheckpoint (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/text-buffer.js:964:38)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/text-buffer.js:1579:36)
    at later (~/AppData/Local/atom/app-1.19.4/resources/app/node_modules/text-buffer/lib/helpers.js:21:13)
```

### Commands

```
  2x -4:11.9.0 core:move-left (input.hidden-input)
  5x -4:05.0 core:backspace (input.hidden-input)
     -4:03.8.0 intentions:highlight (input.hidden-input)
 14x -3:50.2.0 core:backspace (input.hidden-input)
  2x -3:25.8.0 core:move-left (input.hidden-input)
     -3:24.5.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.30.5 
atom-jade 0.3.0 
atom-ternjs 0.18.3 
autocomplete-modules 1.7.0 
busy-signal 1.4.3 
css-from-html 0.1.5 
emmet 2.4.3 
file-icons 2.1.11 
git-blame 1.2.2 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
jshint 1.8.6 
language-pug 0.0.21 
linter 2.2.0 
linter-eslint 8.2.1 
linter-jshint 3.1.5 
linter-sass-lint 1.7.6 
linter-scss-lint 3.1.1 
linter-ui-default 1.6.8 
merge-conflicts 1.4.5 
minimap 4.29.6 
minimap-pigments 0.2.2 
monokai 0.24.0 
multi-cursor 2.1.5 
node-debugger undefined 
pigments 0.40.2 
react 0.16.2 
Stylus 3.1.1 
tabs-to-spaces 1.0.3 
tag 0.5.0 
terminal-plus 0.14.5 
```

**Comment by Rustynote** [comment] 2017-08-31 12:27
No idea how to reproduce it but it only triggered on untitled tab. Closing the tab fixes the error.

**Comment by Ben3eeE** [comment] 2017-08-31 12:50
@Rustynote Any information you can share about what you were doing before you saw the error in the untitled tab that can help us to reproduce? Thank you :bowing_man:

**Comment by jesseteal** [comment] 2017-08-31 14:51
Doesn't just happen in untitled tabs. I have none but I'm getting spammed by these errors.  I'm editing the same set of files I had open yesterday. No error yesterday. Too many today.
I generally start each day by closing and re-opening Atom to bypass other bugs that pop up when its been open too long.

I have 2 instances open (2 different projects, backend/frontend) and the error only occurs in one, the frontend (react.js app).

**Comment by StlthyLee** [comment] 2017-08-31 15:06
I've just started seeing this error too, not in an untitled tab but in a file that I've already been working in. Seems to be happening every time I type something.

For reference, this is on Mac OS Sierra.

**Comment by jesseteal** [comment] 2017-08-31 15:07
Closing all tabs seems to work. my errors are gone (for now...)

**Comment by StlthyLee** [comment] 2017-08-31 15:08
@jesseteal that is probably because have no tabs open anymore for the error to occur in ...

**Comment by Ben3eeE** [comment] 2017-08-31 15:30
@jesseteal @StlthyLee It would be great if you could say something about what you were doing just before you got into this state 🙇

**Comment by jesseteal** [comment] 2017-08-31 15:34
I did say:  I closed Atom down. Re-opened it and continued editing open files from the day before, but the errors only occurred in one of two open Atom instances.

Closing all tabs and reopening them makes the errors go away.

**Comment by Ben3eeE** [comment] 2017-08-31 15:40
@jesseteal Did the error appear right away in the Atom instance that was in this state? Or did you make any edits before seeing this exception?

**Comment by JoshuaASmith** [comment] 2017-08-31 15:43
I just opened atom for the day and immediately got these errors popping up @Ben3eeE . .js files in a react app

**Comment by Rustynote** [comment] 2017-08-31 15:45
@Ben3eeE Did same as @jesseteal. I closed atom yesterday, re-opened it today to continue with stuff. Despite multiple tabs, only untitled one triggered the error. Tab was ~600 lines long, language was HTML. Error continued even after restarting the atom. Only closing said tab fixed it.

**Comment by jesseteal** [comment] 2017-08-31 15:46
I managed to edit the files for a while before the error appeared (not sure how long).  The instance where errors never appeared was used a lot less than the one that started throwing errors.

Also 
PHP Project: used less, no errors
React.js Project: used most, errors after some editing.

**Comment by Ben3eeE** [comment] 2017-08-31 15:51
@JoshuaASmith @Rustynote @jesseteal Thank you, that is very helpful 🙇

**Comment by maxbrunsfeld** [comment] 2017-08-31 20:57
This may be addressed by https://github.com/atom/text-buffer/pull/252, which will be released in 1.19.5.

**Comment by maxbrunsfeld** [comment] 2017-08-31 23:09
I'm going to close this out because I think it's likely that it's fixed. Please let me know if you're still experiencing this on Atom 1.19.5, and we can reopen if so.

**Closed by maxbrunsfeld** 2017-08-31 23:09 UTC

**Comment by matt3224** [comment] 2017-09-04 08:20
I'm now getting this in 1.20.0-beta5

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Patch does not apply

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:144

TypeError: Patch does not apply
    at History.module.exports.History.getChangesSinceCheckpoint (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:144:34)
    at TextBuffer.module.exports.TextBuffer.getChangesSinceCheckpoint (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:964:38)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1579:36)
    at later (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:21:13)
```

### Commands

```
     -2:07.0 core:backspace (input.hidden-input)
     -2:06.8.0 core:move-right (input.hidden-input)
     -2:06.1.0 core:save (input.hidden-input)
     -1:40.1.0 core:backspace (input.hidden-input)
     -1:39.5.0 core:move-right (input.hidden-input)
     -1:38.2.0 core:backspace (input.hidden-input)
     -1:38 core:move-left (input.hidden-input)
     -1:37.1.0 core:save (input.hidden-input)
  2x -1:32.2.0 core:backspace (input.hidden-input)
     -1:30.7.0 core:save (input.hidden-input)
     -1:02.8.0 core:backspace (input.hidden-input)
     -0:56.1.0 core:move-right (input.hidden-input)
     -0:54.6.0 autocomplete-plus:confirm (input.hidden-input)
     -0:54.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:18.1.0 core:save (input.hidden-input)
     -0:04.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
autocomplete-paths 2.11.0 
file-icons 2.1.11 
filesize 3.0.0 
php-twig 4.0.0 
platformio-ide-terminal 2.6.0 
```

**Comment by Ben3eeE** [comment] 2017-09-04 08:41
@matt3224 The fix that @maxbrunsfeld mentioned is only on stable right now. We have not published a new beta version with the fix yet.

**Comment by matt3224** [comment] 2017-09-04 09:00
It happens every time i hit a keyboard key :( whens beta 6?

**Comment by Ben3eeE** [comment] 2017-09-04 09:15
@matt3224 Other users that got in to this state reported that they had to close all tabs and restart Atom to get rid of the errors. Can you try doing that?

**Comment by matt3224** [comment] 2017-09-04 09:31
Ah yeah cool, that fixed it!

**Comment by sompylasar** [comment] 2017-11-25 01:26
@maxbrunsfeld @Ben3eeE

I'm sorry to say that, but this keeps happening:
```
/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: Patch does not apply
    at DefaultHistoryProvider.module.exports.DefaultHistoryProvider.groupChangesSinceCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/default-history-provider.js:106:45)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:969:34)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1687:32)
    at BracketMatcher.module.exports.BracketMatcher.insertNewline (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:106:27)
    at TextEditor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:3:65)
    at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:76:26)
    at TextEditor.editor:newline (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:617:27)
    at /Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:677:40
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1687:32)
    at HTMLElement.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:676:28)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

```
atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.9.3

uname -a
Darwin ivanbabaks-MacBook-Pro.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
```

**Comment by 50Wliu** [comment] 2017-11-27 18:00
@sompylasar we're aware and the new tracking issue is #15827.

**Comment by sompylasar** [comment] 2017-11-27 18:10
@50Wliu :+1: Thanks.
