### ISSUE TITLE
I can't run Atom

### ISSUE THREAD

**Issue by barhouum7** [atom/atom#19540] opened 2019-06-15 00:03 UTC
I meet this problem when run Atom..
On Windows 10
Please I need help
![wdxw](https://user-images.githubusercontent.com/28789723/59544414-29300000-8f09-11e9-9e9c-9545b13c3147.PNG)

**Comment by Arcanemagus** [comment] 2019-06-16 01:21
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14461. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-06-16 01:21 UTC
