### ISSUE TITLE
Unable to move file located on SMB network drive on Linux

### ISSUE THREAD

**Issue by ipimpat** [atom/atom#19463] opened 2019-06-06 18:04 UTC
Seems like Atom fails to resolve the correct path, when moving files (dragging), located on a remote "Windows share" on Linux.

The folder is located on a remote server and shared using Samba and mounted using GUI tool (gvfs / Gigolo)

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/kimse/user=kimse'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/home/kimse/user=kimse'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (/usr/share/atom/resources/app/static/<embedded>:14:930839)
    at TreeView.t.exports.TreeView.onDrop (/usr/share/atom/resources/app/static/<embedded>:14:936593)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:911450)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
blade-spacer 0.4.2 
docblockr 0.13.7 
ide-php 0.7.18 
intentions 1.1.5 
language-blade 0.42.0 
language-pascal 1.0.0 
php-cs-fixer 4.1.1 
php-ide-serenata 4.5.3 
project-manager 3.3.7 
remote-ftp 2.2.2 
```

**Comment by rsese** [comment] 2019-06-06 23:32
Thanks for contributing!

Based on the stack trace, we'll go ahead and close as a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-06 23:32 UTC
