### ISSUE TITLE
Release notes broken in 1.2

### ISSUE THREAD

**Issue by schlamar** [atom/atom#9556] opened 2015-11-13 07:09 UTC
After upgrade to 1.2.0, the release notes page is still showing the "Restart and update" button and is missing the release notes for the current version:

![1](https://cloud.githubusercontent.com/assets/238652/11140704/cb8ad9fe-89dd-11e5-8c3d-3207468db229.png)

![2](https://cloud.githubusercontent.com/assets/238652/11140706/cd83381e-89dd-11e5-87cd-d1b9c02539bc.png)

**Comment by rm-code** [comment] 2015-11-13 13:08
I have the same issue on OSX 10.10.5 :+1:

**Comment by Zireael07** [comment] 2015-11-13 13:46
Win 7 here, same thing.

**Comment by havthgem** [comment] 2015-11-13 14:04
Same to.

**Comment by mnquintana** [comment] 2015-11-13 16:43
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/8315 - let's keep the discussion going there.

**Closed by mnquintana** 2015-11-13 16:43 UTC
