### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'

### ISSUE THREAD

**Issue by richardchey** [atom/atom#7262] opened 2015-06-13 02:39 UTC
**Atom Version**: 0.209.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\app.asar\src\window-event-handler.js:148:33)
    at HTMLDocument.handler (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\Richard\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -9:52.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:52.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -9:00.1.0 remote-ftp:toggle (atom-text-editor.editor.is-focused)
     -8:57.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -8:54.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:50.5.0 core:copy (atom-text-editor.editor.is-focused)
     -8:47.3.0 core:paste (atom-text-editor.editor.is-focused)
     -8:15.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:12.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -7:30.4.0 core:paste (atom-text-editor.editor.is-focused)
     -7:23.1.0 core:copy (atom-text-editor.editor.is-focused)
     -7:19.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -7:17.2.0 core:paste (atom-text-editor.editor.is-focused)
     -7:05.6.0 remote-ftp:upload-selected (atom-text-editor.editor.is-focused)
     -6:59.4.0 core:save (atom-text-editor.editor.is-focused)
  3x -6:49.1.0 remote-ftp:toggle (atom-text-editor.editor.is-focused)
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.6
autocomplete-python, v0.4.2
docblockr, v0.7.2
language-blade, v0.14.0
language-fish-shell, v1.0.2
laravel, v0.7.0
Remote-FTP, v0.7.1

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-13 07:41
Thanks for the report -- this looks like a duplicate of https://github.com/atom/atom/issues/6548.

**Closed by izuzak** 2015-06-13 07:41 UTC
