### ISSUE TITLE
Keyboard layout error in Linux x64

### ISSUE THREAD

**Issue by erwinkendo** [atom/atom#4158] opened 2014-11-12 16:05 UTC
Greetings

I am using atom v0.145.0 in Linux x64 and when trying to use keyboard shortcuts, I discovered that atom itself recognizes shift + 7 as & character, not / as it is recognized inside the editor itself. This seems like an issue with the module recognizing key inside atom.

If maybe it is only some configuration error, any feedback is well received

Kind regards

**Comment by bgse** [comment] 2015-06-30 13:33
Same issue with Atom 1.0 on Fedora21, using the german keyboard layout, doesn't matter if 'nodeadkeys' or otherwise.

The editor inserts the proper keys, but the keybinding resolver appears to resolve the keys that would be there on a en-US keyboard layout.

**Comment by mnquintana** [comment] 2015-06-30 13:39
This seems like a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-30 13:39 UTC
