### ISSUE TITLE
Atom will not open a large JS file after update to 1.14.1 or 1.14.2

### ISSUE THREAD

**Issue by bferdinand** [atom/atom#13832] opened 2017-02-16 16:35 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When opening a large file, in this case it is any file that has multiple js minified plugins in it. Atom will just freeze and eventually comes up to ask if I want to keep waiting or close, if I choose keep waiting it will continue in that loop until I click close.

### Steps to Reproduce

1. Open a large file with quite a few minified jquery plugins in it
2. Wait

**Expected behavior:** [What you expect to happen]
With the 1.13.1 release I was on, it would take about 5 - 10 seconds and then open with proper syntax highlighting and I could work with the file.

**Actual behavior:** [What actually happens]
Atom will freeze and eventually comes up to ask if I want to keep waiting or close, if I choose keep waiting it will continue in that loop until I click close.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time I try to open this type of file.

### Versions

Atom    : 1.14.2
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.7.4

### Additional Information

We use atom in production at our agency, and this is currently affecting all that have updated to the 1.14.1 and 1.14.2 versions.

**Comment by rsese** [comment] 2017-02-16 19:05
@bferdinand - looks like this is a duplicate of the issue you opened here?

https://github.com/atom/text-buffer/issues/209

Going to go ahead and close but if I'm mis-understanding and this is a separate issue, let me know :v:

**Closed by rsese** 2017-02-16 19:05 UTC
Labels: duplicate
