### ISSUE TITLE
Atom does not work with Magnet on Mac

### ISSUE THREAD

**Issue by johnmccutchan** [atom/atom#8389] opened 2015-08-14 23:35 UTC
Magnet (http://magnet.crowdcafe.com/) resizes and tiles windows you drag to screen edges. Atom does not work with Magnet. This is likely an issue with Atom. If relevant- Chrome works fine with Magnet.

**Comment by benogle** [comment] 2015-08-14 23:37
cc @zcbenz

**Comment by mnquintana** [comment] 2015-08-15 00:05
This is interesting because Atom *does* work with [BetterSnapTool])https://itunes.apple.com/us/app/bettersnaptool/id417375580?mt=12_

**Comment by benogle** [comment] 2015-08-15 00:29
It also has no issues with http://www.irradiatedsoftware.com/sizeup/ which I use like 1000 times a day

**Comment by maxbrunsfeld** [comment] 2015-08-15 03:01
Yeah, it also works with [ShiftIt](https://github.com/fikovnik/ShiftIt), which is free and similar to SizeUp. I use that.

**Comment by thomasjo** [comment] 2015-08-15 15:27
Aaaand it works with [Spectacle](http://spectacleapp.com).

**Comment by mnquintana** [comment] 2015-08-15 15:29
Soooo now that we've listed just about every Mac window manager, I wonder why Magnet doesn't work? :stuck_out_tongue_closed_eyes:

**Comment by johnmccutchan** [comment] 2015-08-17 13:27
I've done some more testing with Atom + Magnet and it works, but, it depends on where you start the drag from.

works: start drag on blank area of window bar.
does not work: start drag on title area of window bar.

**Comment by Johannes-Esseling** [comment] 2016-03-25 17:04
@johnmccutchan 
I can recreate the Problem you mentioned in Atom as well. 
This doesn't seem to be exclusive to Atom though, I can recreate the behavior in Intellij as well. 
It seems to be related to the right-click functionality these apps offer.

The right-click on the title area of Atom and Intellij opens a Menu where you can select a different folder. 
My attempt at a solution would be allowing the user to disable this functionality.

**Comment by mnquintana** [comment] 2016-12-30 16:11
Is this still an issue with the latest versions of Atom (1.12.7) and Magnet (1.10)?

**Comment by Johannes-Esseling** [comment] 2017-02-13 08:36
The behaviour I described in my comment above can be reproduced in the current version.
However, if you select the "Use Custom Title Bar"-Option from the settings this error can't be reproduced. 
Since the behaviour can be used exactly as intended with the selected option, we could probably close this issue.

**Comment by lee-dohm** [comment] 2017-11-13 05:56
Given there are plenty of Mac window managers that Atom works fine with, I suspect that this is a problem with Magnet and may be resolved by now (or at least has a workaround as @Johannes-Esseling mentions). I'm going to go ahead and close this. If anyone is continuing to run into this, please let us know :+1:

**Closed by lee-dohm** 2017-11-13 05:56 UTC
Labels: electron, mac, more-information-needed
