### ISSUE TITLE
Failed to load the vagrant package

### ISSUE THREAD

**Issue by fpgeek** [atom/atom#8128] opened 2015-07-29 04:46 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Failed to load the vagrant package

```
At ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app.asar'

Error: ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app.asar'
    at Error (native)
    at fs.openSync (fs.js:544:18)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:402:12)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:138:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/helpers/parse.js:8:16)
    at Module._compile (module.js:452:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "github-2014"
    ],
    "disabledPackages": [
      "linter-ansible-lint",
      "go-playground",
      "linter-ansible-lint",
      "go-playground",
      "go-playground",
      "go-rename",
      "go-runtime",
      "go-oracle",
      "go-imports",
      "go-find-references",
      "linter-golinter",
      "linter-gotype",
      "linter-govet",
      "git-go"
    ]
  },
  "editor": {
    "invisibles": {},
    "autoIndent": false
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autoclose-html, v0.18.0
autocomplete-elixir, v1.3.12
bootstrap-3-snippetset, v0.0.6
colorful-json, v1.0.0
github-2014, v3.9.0
go-plus, v3.4.3
language-ansible, v0.1.3
language-docker, v1.1.3
language-elixir, v0.5.1
language-jade, v0.6.1
language-scala, v1.1.3
language-scala-plus, v1.2.2
language-vue, v0.1.0
language-vue-component, v0.2.0
pretty-json, v0.4.1
racer, v0.15.2
rust-api-docs-helper, v0.5.1
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by batjko** [comment] 2015-07-29 05:31
Sounds like this should be opened on the `vagrant` package's repo.
Nothing Atom core can do anything about.

**Comment by kevinsawicki** [comment] 2015-07-31 16:35
I believe this is a duplicate of https://github.com/atom/atom/issues/6604

**Closed by kevinsawicki** 2015-07-31 16:35 UTC
Labels: uncaught-exception
