### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Satish-A-Wadekar** [atom/atom#18756] opened 2019-01-28 02:24 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Developer Tool/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Developer Tool/Atom.app/Contents/Resources/app/static/<embedded>:14:1103304)
    at ScreenLineBuilder.buildScreenLines (/Applications/Developer Tool/Atom.app/Contents/Resources/app/static/<embedded>:14:1099010)
    at DisplayLayer.getScreenLines (/Applications/Developer Tool/Atom.app/Contents/Resources/app/static/<embedded>:14:89306)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Developer Tool/Atom.app/Contents/Resources/app/static/<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Developer Tool/Atom.app/Contents/Resources/app/static/<embedded>:11:69977)
    at TextEditorComponent.updateSync (/Applications/Developer Tool/Atom.app/Contents/Resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.didMouseWheel (/Applications/Developer Tool/Atom.app/Contents/Resources/app/static/<embedded>:11:92354)
```

### Commands

```
     -2:18.3.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-light-ui)
  6x -1:54.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-typescript 13.1.0 
busy-signal 2.0.0 
ide-json 0.2.1 
intentions 1.1.5 
language-babel 2.85.0 
language-ocaml 1.9.5 
linter 2.3.0 
linter-csslint 2.0.2 
linter-eslint 8.5.0 
linter-ui-default 1.7.1 
nuclide 0.366.0 
nuclide-format-js 0.0.47 
prettier-atom 0.56.2 
sort-lines 0.18.0 
tool-bar 1.1.11 
```

**Comment by rsese** [comment] 2019-01-28 21:09
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/18692 so you can subscribe there for updates if you'd like.  If you have any more information like steps to reproduce, please let us know in https://github.com/atom/atom/issues/18692.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-01-28 21:09 UTC
