### ISSUE TITLE
Can't see whole new name of a duplicate or new file

### ISSUE THREAD

**Issue by arielnoname** [atom/atom#9988] opened 2015-12-09 15:46 UTC
Just see the gif please. Happens to me since always.

![naming](https://cloud.githubusercontent.com/assets/11996305/11689932/dc70db34-9e72-11e5-94da-2e9acd4c269e.gif)

**Comment by lee-dohm** [comment] 2015-12-09 17:55
This is a duplicate of https://github.com/atom/tree-view/issues/473. Please subscribe there for updates. Apologies that this has been frustrating.

**Closed by lee-dohm** 2015-12-09 17:55 UTC
