### ISSUE TITLE
"Move line down" keyboard shortcut triggers alert sound on OSX

### ISSUE THREAD

**Issue by bzx** [atom/atom#8116] opened 2015-07-28 16:08 UTC
Every time I want to move a line down with a key shortcut, the system alert sound is played.
OSX 10.10, and latest Atom.

Key binding resolver shows me that the shortcut is there, also present in the config file:
```
"ctrl-cmd-down": "editor:move-line-down"
```

**Comment by mnquintana** [comment] 2015-07-28 16:09
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/1669 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-28 16:09 UTC
