### ISSUE TITLE
Drag tab out of window to open in new window

### ISSUE THREAD

**Issue by halleycarleton** [atom/atom#4830] opened 2015-01-02 19:28 UTC
It would be nice to be able to drag a tab out of the window and have it open in a new window rather then having to open a new window then drag the tab into the new window.

I'm on Windows 8.1, not sure if this behavior is different on other OS.

**Comment by izuzak** [comment] 2015-01-02 19:46
Yeah, that would be useful -- thanks for the feedback! I think this is a duplicate of https://github.com/atom/tabs/issues/39, so I'm closing this in favor of that issue.

**Closed by izuzak** 2015-01-02 19:46 UTC
