### ISSUE TITLE
Running "resources\cli\apm.cmd" doesn't respect portable mode

### ISSUE THREAD

**Issue by segevfiner** [atom/atom#14804] opened 2017-06-16 10:59 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When Atom is in portable mode (Having an adjacent ".atom" folder) and you try to run "resources\cli\apm.cmd" to install packages or anything else it will use the standard Atom home (`%USERPROFILE%\.atom`). You can set `ATOM_HOME` to your portable ".atom" folder to work around this.

### Steps to Reproduce

1. Setup Atom in [Portable Mode](http://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode).
2. Try and use "resources\cli\apm.cmd" to install packages.
3. They will end up in `%USERPROFILE%\.atom`.

**Expected behavior:** apm respects portable mode automatically.

**Actual behavior:** It doesn't.

**Reproduces how often:** Always

### Versions

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.1.windows.2
visual studio 2015
```

Windows 10.0.15063 x64

**Comment by rsese** [comment] 2017-06-16 17:34
Thanks for contributing!

We noticed that this is a duplicate of https://github.com/atom/apm/issues/678.   In particular, see the comments starting here for more context and a suggested workaround for the path issue you described:

https://github.com/atom/apm/issues/678#issuecomment-275770107

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-16 17:34 UTC
