### ISSUE TITLE
When create a new folder, segmentation fault on latest version

### ISSUE THREAD

**Issue by joowh85** [atom/atom#4929] opened 2015-01-08 22:28 UTC
OS: Ubuntu 14.10 x86-64
Atom: 0.168.0

line 92:  5289 세그멘테이션 오류 (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$DOT_ATOM_DIR/nohup.out" 2>&1
[5289:0109/072204:ERROR:browser_main_loop.cc(163)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 111ms
[5319:0109/072204:INFO:renderer_main.cc(207)] Renderer process started
[5289:0109/072205:INFO:CONSOLE(58)] "No deserializer found for", source: /opt/atom/resources/app/src/deserializer-manager.js (58)
[5289:0109/072205:INFO:CONSOLE(64)] "Window load time: 1102ms", source: file:///opt/atom/resources/app/static/index.js (64)
Crash dump id: 0cd1948e-e980-4867-a381-c03d6d2ef221

**Comment by kevinsawicki** [comment] 2015-01-08 22:29
Can you try 0.169? I believe the crash has been fixed in that version

**Comment by kevinsawicki** [comment] 2015-01-08 22:30
I believe this is a duplicate of https://github.com/atom/atom/issues/4892

**Closed by kevinsawicki** 2015-01-08 22:30 UTC
Labels: crash, linux
