### ISSUE TITLE
Allow for nested snippet folder lookups

### ISSUE THREAD

**Issue by lmajano** [atom/atom#14974] opened 2017-07-07 16:00 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is not a bug report but a feature request.  When creating packages, you can put cson files under the `snippets` folder but only the top-level folder is scanned.  I would like to propose a recursive lookup under the `snippets` folders in order to better organize snippets in a tree like hierarchy.

I know you allow fo rmultiple snippets per file, but when you have a large collection of snippets, it is easier to organize via folders first.

### Steps to Reproduce

1. Create a hierarchy under `snippets` folder in a package.

```
+ snippets
  + wirebox
      + snippets.cson
  + testbox 
     + skeletons
        + files.cson
```
2. Reload the workbench to activate snippets

**Expected behavior:** [What you expect to happen]

For the snippets to register

**Actual behavior:** [What actually happens]

None of the nested snippets are registered

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Mac OS Latest
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0

**Comment by rsese** [comment] 2017-07-11 20:44
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/snippets/issues/28. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-11 20:44 UTC
