### ISSUE TITLE
Debian package is missing dependency to libasound2 and libxkbfile1

### ISSUE THREAD

**Issue by oberlies** [atom/atom#13591] opened 2017-01-11 18:30 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom

### Description

After having installed the debian package of Atom 1.13.0 on Ubuntu 16.04, atom fails to start up due to missing library files. Manually installing the packages libasound2 and libxkbfile1 fixes the problem. So these dependencies seem to be missing in the debian package.

### Steps to Reproduce

1. Get a minimal installation of Ubuntu 16.04
2. `sudo apt-get update`
4. `wget https://github.com/atom/atom/releases/download/v1.13.0/atom-amd64.deb`
5. `sudo apt-get install ./atom-amd64.deb`
6. `atom`

**Expected behavior:**

Atom should start up.

**Actual behavior:**

The following error message is printed in the console
```
/usr/share/atom/atom: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory
```
After having executed `sudo apt-get install libasound2`, running `atom` results in an almost empty window with the Chrome debugging tools being shown. On the Console tab, a stack trace is shown starting with the following line:
```
Error: libxkbfile.so.1: cannot open shared object file: No such file or directory
```
After having executed `sudo apt-get install libxkbfile1`, atom starts up normally.

**Reproduces how often:**
1/1

### Versions
```
atom --version
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
```
apm --version
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4
```
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

**Comment by oberlies** [comment] 2017-01-11 18:32
Screen shot of the console log error when libxkbfile1 is not yet installed:
![libxkbfile error message](https://cloud.githubusercontent.com/assets/353942/21861309/943934ae-d834-11e6-89aa-5ac4d2ccae4e.png)

**Comment by EagleOne42** [comment] 2017-02-17 16:21
I ran into the same issue.  Same OS and fix worked.

**Comment by Arcanemagus** [comment] 2018-02-17 19:42
I'd say this should be closed as a duplicate of #16659, as that has a more complete list of the missing dependencies. For example this is missing `libxss1`, without which Atom completely fails to start.

**Comment by DanielTate** [comment] 2018-02-20 06:16
Has this been resolved I am still getting this exact issue.

**Comment by Arcanemagus** [comment] 2018-03-05 19:03
Should be fixed on `master` now by https://github.com/atom/atom/pull/16812. 😉

@DanielTate Note that on your own system you can simply install the missing packages manually with `sudo apt-get update && sudo apt-get install libx11-xcb1, libxss1, libasound2 (>= 1.0.16), libxkbfile1`.

**Closed** 2018-03-05 19:11 UTC
Labels: linux, needs-reproduction
