### ISSUE TITLE
holding press middle mouse button is not work scrolling

### ISSUE THREAD

**Issue by Eskander88** [atom/atom#17237] opened 2018-04-28 08:36 UTC
There is in others softs (eg: web browsers) scrolling function. When user click middle mouse button is showed icon:
![91](https://user-images.githubusercontent.com/24587938/39394213-ef8cfd4c-4ad7-11e8-99d5-483f96900f22.png)

If cursor move down or up, then scrolling is moving

Tried with Atom x64-1.25.1, x64-1.27.0-beta1 – Windows 10 x64

**Comment by rsese** [comment] 2018-04-30 18:35
Thanks again @Eskander88 - this looks like a duplicate of https://github.com/atom/atom/issues/6884 so you can subscribe there for updates if you'd like.  Also, see the last comment in that issue for a community package that might help https://github.com/atom/atom/issues/6884#issuecomment-341710422.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-30 18:35 UTC
