### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ZohrehGorji** [atom/atom#18942] opened 2019-03-04 13:47 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:14:1103304)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:14:1099010)
    at DisplayLayer.getScreenLines (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:14:89306)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:69977)
    at TextEditorComponent.updateSync (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:67605)
    at TextEditorComponent.didMouseWheel (/Applications/Atom for cpp.app/Contents/Resources/app/static/<embedded>:11:92354)
```

### Commands

```
     -1:02.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-material-ui 2.1.3 
atom-prettify 0.1.3 
atomic-chrome 0.3.3 
auto-update-packages 1.0.1 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
busy-signal 2.0.0 
color-picker 2.3.0 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.30 
git-plus 8.6.1 
git-time-machine 2.1.0 
gpp-compiler 3.0.7 
highlight-selected 0.14.0 
intentions 1.1.5 
language-liquid 0.7.0 
linter 2.3.0 
linter-eslint 8.5.2 
linter-rubocop 2.2.4 
linter-scss-lint 3.2.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
open-in-browsers 0.0.30 
open-recent 5.0.0 
pane-layout-plus 0.7.4 
pdf-view 0.71.0 
pigments 0.40.2 
project-manager 3.3.6 
remote-edit 1.9.0 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
terminal-plus 0.14.5 
vim-mode 0.66.0 
web-view 3.0.0 
```

**Comment by rsese** [comment] 2019-03-05 01:45
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

x-ref: https://github.com/atom/atom/issues/16892

**Comment by kagai** [comment] 2019-03-05 05:01
Got the same issue with atom on ubuntu 18.04

**Comment by kagai** [comment] 2019-03-05 05:14
This issue might be occurring due to the length of the file, smaller files have no issues.My file is around 500 lines. I stand to be corrected on this though.

**Comment by ZohrehGorji** [comment] 2019-03-05 10:01
i think so too, i was working on a file with 400 line but the moment i went over 500 i had this problem, which is very confusing because 500 is not that many line.

**Comment by ameenmattar** [comment] 2019-03-05 15:00
I am facing the same issue in one file, but i guess its nothing because of the number of lines, all my files exceed 500 lines and even 600 , and the issue happens only in one file. Not sure whats the problem.

**Comment by rsese** [comment] 2019-03-05 22:11
Thanks for the extra details - does anyone have specific steps to reproduce along with a sample file?  And can you reproduce in safe mode?

**Comment by foxinatardis** [comment] 2019-03-15 16:13
I don't believe number of lines is the issue. I have a file with less than 200 lines triggering the error. The error pops up when I try to scroll:

```
TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (C:\Users\abell\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1104122)
    at ScreenLineBuilder.buildScreenLines (C:\Users\abell\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:1099828)
    at DisplayLayer.getScreenLines (C:\Users\abell\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14:89305)
    at TextEditorComponent.queryScreenLinesToRender (C:\Users\abell\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (C:\Users\abell\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:69977)
    at TextEditorComponent.updateSync (C:\Users\abell\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:67605)
    at TextEditorComponent.didMouseWheel (C:\Users\abell\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11:92354)
```

Makes editing the file impossible. I guess maybe I'll finally switch to Emacs.

**Comment by bhtru** [comment] 2019-03-15 17:51
It appeared for me when did a search in a directory and opened a file from the "Project Find Results" pane.  However, when I open the same file from project directory pane no errors occur.

**Comment by tyhaguh** [comment] 2019-03-17 17:54
I've been having this problem too, however, I've managed to overtake it by closing the file and reopening it. After 24 hours I continue without problems.

**Comment by SpringShadow** [comment] 2019-03-29 07:00
11

**Comment by Ma3k4H3d** [comment] 2019-03-31 02:02
[Enter steps to reproduce:]

1. after install minimap 4.29.9
2. open this files:
    1)  https://github.com/shellphish/rex/blob/master/rex/crash.py
    2) https://github.com/shellphish/rex/blob/master/tests/test_rex.py

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1108203)
    at ScreenLineBuilder.buildScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1103913)
    at DisplayLayer.getScreenLines (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:89276)
    at TextEditorComponent.queryScreenLinesToRender (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:79025)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:69678)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:67306)
    at TextEditorComponent.didShow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:90936)
    at TextEditorComponent.didFocus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:91127)
    at HTMLElement.addEventListener (/app.asar/src/text-editor-element.js:36:67)
    at HTMLElement.activeItemChanged (/app.asar/src/pane-element.js:164:16)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186984)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188425)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:452700)
    at Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:454751)
    at Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:454248)
    at Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:456970)
    at Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:458255)
    at <anonymous>
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-python 1.14.0 
minimap 4.29.9 
vim-mode-plus 1.36.0 
```

**Comment by MrDoomah** [comment] 2019-04-01 14:11
Hi, I have the same issue. It seems to have to do something with the network drive. 

The share I was working on is mapped to U:. When I browse to `U:\Operations\Position` and open position.py it gives this error. When I got to `\\<domain>\shares\<project>\Operations\Position` and open position.py it doesn't give the error. This behavior is repeatable.

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\timmer\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:1104122)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:1099828)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:89305)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:79324)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:69977)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:67605)
    at visible.suppressUpdates.updatedSynchronously.updateScheduled.i.getScheduler.updateDocument (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:66633)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:326599)
```

### Non-Core Packages

```
atom-runner 2.7.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
```

**Comment by ayanezeclac** [comment] 2019-04-02 14:00
hi, Since yesterday I have the same problem with a file. Is there any news about it? Anyway, I love this tool, but that problem generates a serious problem in my workflow.

**Closed** 2019-04-02 22:49 UTC
Labels: more-information-needed, uncaught-exception
