### ISSUE TITLE
Crash on quit on OS X 10.11.6

### ISSUE THREAD

**Issue by taoeffect** [atom/atom#12368] opened 2016-08-09 03:01 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Crash. See attached log: **[atom.crash.zip](https://github.com/atom/atom/files/408119/atom.crash.zip)**

### Steps to Reproduce

1. Check for updates
2. Choose to install and restart

**Expected behavior:** Just restart, no funny business

**Actual behavior:** Crash.

Also, for some reason `/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/crashpad_handler` wants to connect to `54.249.141.255` on port `1127`. I'm guessing this is an automatic crash reporter. However, the odd port number (not being 443 as it should be), made me prevent this outgoing connection.

### Versions

I believe all starting with 1.9 have done this.

**Comment by lee-dohm** [comment] 2016-08-09 04:17
I could not replicate this using Atom v1.9.3 on Mac OS X 10.11.6. Here's what I did:

1. Download the 1.9.3 version from https://github.com/atom/atom/releases
1. Install it
1. Launch Atom from the terminal
1. Select Open on the security dialog
1. Wait for the update to download
1. Restart and install update using the menu item *Atom > Restart and Install Update*

After a few seconds, everything restarted just fine.

**Comment by oltmannsdaniel** [comment] 2016-08-10 16:02
Had the same Problem on Windows 10. The Update Process took so much RAM and CPU that the App crash.

**Comment by jasonsperske** [comment] 2016-08-10 16:30
I have experienced this issue on every update since at least 1.9.1 on my Windows 10 workstation, is there any information I can provide, since I'm sure I can reproduce this bug once I update to 1.9.7.  A simple manual start of the updated Atom works without a hitch, it just doesn't auto launch on update.

**Comment by taoeffect** [comment] 2016-08-11 05:56
So, a few things:

1. This has nothing to do with autoupdate, it crashes every time I quit Atom, so I've renamed the issue appropriately.
2. I've tried disabling all of my plugins (44 in total), and it doesn't help. "Atom Helper" still crashes every time.
3. I tried `atom --clear-window-state`, didn't help.
4. I tried `atom --safe`, didn't help.

**Comment by taoeffect** [comment] 2016-08-11 06:05
Wow. OK, this is curious. Now I've just noticed that the crash happens ***anytime a window is closed!*** This means that Atom itself isn't crashing, but its helper per-window process.

And yes, this happens in safe mode as well.

**Comment by taoeffect** [comment] 2016-08-11 07:01
If it helps, I just noticed that I have 4 zombie processes stuck in the background that looks like this:

```
/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper --eval require('/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js').setCacheDirectory('/Users/taoeffect/.atom/compile-cache');^Jrequire('/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js');
```

**Comment by debugDS** [comment] 2016-08-16 16:47
I have the same problem (closed window = helper crashing)
OSX 10.11.6, Atom 1.9.8

**Comment by adolby** [comment] 2016-08-29 22:56
I'm having the same problem. OS X 10.11.6, Atom 1.9.9

**Comment by isinkler** [comment] 2016-08-30 18:22
Having the same problem. (OS X 10.11.6, Atom 1.9.9)

**Comment by cyberchucktx** [comment] 2016-09-06 23:07
Same problem. (OS X 10.11.5, Atom 1.10.1)

**Comment by isinkler** [comment] 2016-09-07 10:28
Got it fixed by upgrading to 1.10.1.

**Comment by debugDS** [comment] 2016-09-07 15:41
Same problem (macOS 10.11.6, Atom 1.10.1)
Launch Atom in safe mode
If I close the window ➜ Atom Helper crash
But if I force quit the Atom Helper with the highest PID before closing the window ➜ no crash
This works the same even if I rename the ~/.atom folder

**Comment by maverickwoo** [comment] 2016-09-23 22:33
I am on OS X 10.9.5, running Atom 1.10.2 (latest as of this writing). I think I have a reasonable repro study. Please be sure to use `--clear-window-state` or else there can be lingering tabs from the previous session and it will affect the result. I hope this effort helps tracking down this annoying bug.

### Setup:

This is the content of the current directory. There are four one-line files.

```
$ grep ^ *
a.md:# abc
b.txt:b.txt
c.c:#include <stdio.h>
d.go:package main
```

### Single-file tests:

`atom --safe --clear-window-state a.md`: quit -> crash

`atom --safe --clear-window-state a.md`: close a.md -> quit -> ok

`atom --safe --clear-window-state b.txt`: quit -> crash

`atom --safe --clear-window-state b.txt`: close b.txt -> quit -> ok

`atom --safe --clear-window-state c.c`: quit -> ok

`atom --safe --clear-window-state d.go`: quit -> ok

### Multi-file tests:

`atom --safe --clear-window-state a.md c.c`: close a.md -> quit -> crash

`atom --safe --clear-window-state a.md c.c`: close c.c -> quit -> crash

`atom --safe --clear-window-state a.md c.c`: close both -> quit -> ok

`atom --safe --clear-window-state c.c d.go`: quit -> ok

### Current hypothesis:

It is file-type specific. If you have an offending file-type opened in one of the tabs, then you need to close all tabs before quit or else Atom Helper will crash. But if you do not have one of the offending file-types opened, then Atom Helper will not crash even with multiple tabs opened. In the tests, `md` and `txt` are offending, whereas `c` and `go` are not.

**Comment by maxbrunsfeld** [comment] 2016-09-23 23:30
I believe this has been fixed. Can you see if the problem exists on [the latest Beta release](https://github.com/atom/atom/releases/tag/v1.11.0-beta5)? If it does, could you try the latest master builds ([download link](https://1235-3228505-gh.circle-artifacts.com/0//Users/distiller/atom/out/atom-mac.zip))?

**Comment by debugDS** [comment] 2016-09-24 17:19
Yep. Problem solved in 1.11.0 beta 5 (and 1.12). Tx!

**Comment by taoeffect** [comment] 2016-09-24 22:29
I can confirm the problem seems to be solved in the beta.

**Comment by maxbrunsfeld** [comment] 2016-09-24 22:30
Thanks for the update!

**Closed by maxbrunsfeld** 2016-09-24 22:30 UTC
Labels: crash, needs-reproduction
