### ISSUE TITLE
Multiple Atom release channels can't be installed side-by-side on Windows

### ISSUE THREAD

**Issue by MethodGrab** [atom/atom#9247] opened 2015-10-21 20:49 UTC
**Expected**
According to the [beta info page](https://atom.io/beta) Atom Beta should "run side-by-side with Atom stable". To me that reads like I should be able to have both the beta and stable installed (and even running) simultaneously on the same system (like with Chrome's stable & beta releases) and there should be separate links to run each build.

**Actual**
On Windows (7 x64), when I install the beta (`1.1.0-beta1`), it replaces the context menu "Open with Atom" shortcut and the start menu shortcuts with the beta so there is no apparent way to run stable without reinstalling.
Reinstalling stable works but it replaces all the shortcuts with links to the stable version so there is no way to run the beta without re-installing.

![image](https://cloud.githubusercontent.com/assets/2421069/10649437/18a1a58c-783c-11e5-8c7c-fe4be8b6a49d.png)

**Comment by benogle** [comment] 2015-10-21 21:36
cc @raelyard

**Comment by maxbrunsfeld** [comment] 2015-10-23 21:45
Ok, I had to stop work on this for the time being because of some PathLength issues on windows. We need to upgrade our build infrastructure to use npm 3, which does a better job of reducing path nesting. Until that time, I'm reopening this.

**Comment by damieng** [comment] 2016-02-26 17:14
With the file associations and shell integration having the beta executable named something different - atombeta.exe for example - would also make this work better. Thoughts?

**Comment by maxbrunsfeld** [comment] 2016-02-26 17:39
> having the beta executable named something different - atombeta.exe for example - would also make this work better.

:+1: Ah, I didn't realize that. We already rename a bunch of stuff based on the `channel` (`stable` vs `beta`) in the build scripts, so this would just be one more.

**Comment by damieng** [comment] 2016-05-05 18:20
Now the shell integration is coming out of the installer and into Atom settings we should make sure we use productName instead of atom.exe everywhere when we do that work in #5901

**Comment by damieng** [comment] 2016-07-20 00:24
Included in the forthcoming shell integration options.

**Comment by calebmeyer** [comment] 2016-07-22 00:17
@damieng what's the process/timeline for getting both installed side by side on windows?

**Comment by damieng** [comment] 2016-07-23 00:34
It's checked into master now on both atom/atom and atom/settings-view and should ship in Atom 1.10.

**Comment by Ben3eeE** [comment] 2016-10-26 09:03
Reopening because I am not able to install Atom beta side by side with Atom stable on Windows 7. Installing beta removes the stable install. See below for a full list of what I did to try and install `Atom 1.12.0-beta4` side by side with `Atom 1.11.2`.

I can test it out on Windows 10 later if required to see if stable and beta side by side works there.

Originally reported in: https://github.com/atom/atom/issues/13016 so not alone seeing this.

## Windows 7 - Trying to install stable and beta side by side. 

1. Uninstalled `Atom 1.12-beta4` using `Programs and Features` found in the Control panel.
1. Removed the `.atom` folder from `%USERPROFILE%`.
1. Removed the `atom` folder from `%localappdata%`. It contained `update.exe` and `.dead`.
1. Expected: Atom to be uninstalled. Actual: Atom pin is still on the taskbar, clicking it gives an error that it might have been moved, renamed or deleted asking me to remove the pin.
1. Unpinned Atom from the taskbar by clicking Yes on the dialog.
1. Installed `Atom 1.11.2` using `AtomSetup.exe` downloaded from `atom.io`.
1. Expected and Actual: `Atom 1.11.2` starts after install, all settings lost.
1. Answered yes on the telemetry consent and unchecked the `Show On Start` option for the welcome guide.
1. Opened the settings-view using <kbd>Ctrl+,</kbd>
1. Navigated to the System tab and checked all three options.
1. Pinned Atom to the taskbar.
1. Closed `Atom 1.11.2`.
1. Checked `%localappdata\atom` it contains the `app-1.11.2` folder.
1. Installed `Atom 1.12.0-beta4` using `AtomSetup.exe` downloaded from `atom.io`.
  1. `Atom 1.12.0-beta4` starts.
  1. Atom does not ask for telemetry consent or show the welcome guide.
  1. `Atom 1.11.2` is not in `%localappdata%\atom`. Only `app-1.12.0-beta4`.
  1. Atom is still pinned to the taskbar and can open from there but it has the icon from stable.
  1. Open with Atom context menu works, icon from beta and opens `Atom 1.12.0-beta4`.
1. Checked the Systems tab all three options are checked.

**Comment by damieng** [comment] 2016-10-26 16:15
Atom Beta is expected to use the same config and settings as regular Atom right now so I wouldn't expect it to show the welcome guide or telemetry consent.

The real problem right now is that beta and non-beta on Windows share the same setup-id in Squirrel so one is considered an upgrade to the other.

One option for now would be to use the beta zip and unpack that somewhere.  That should allow you to run side-by-side.  If you want the beta to also use a separate config then you should be able to create an empty .atom folder in the folder about where you unpacked the beta, e.g.

```c:\apps\atombeta
c:\apps\.atom```

**Comment by jerone** [comment] 2016-11-19 14:11
I see exactly the same happening as @Ben3eeE is describing. While installing any version of Atom (release, beta or dev) the previous Atom installation is being removed from `%LOCALAPPDATA%\atom\`.

_Windows 7 EN 64-bits_

**Comment by vvs** [comment] 2017-05-31 09:14
Just installed Atom 1.18 beta (Windows 10, x64) and it has deleted the stable Atom version (1.17). If the issue is not going to be fixed, it would be good to remove the wrong message on the Atom beta page that the beta can be used side-by-side.

**Comment by sonokamome** [comment] 2017-05-31 15:32
Heya Vlad, no it works in other platforms as far as the side-by-side install. It's just in Windows where this is currently an issue. side-by-side installs work fine in UNIX and UNIX-like environments. They're still working on it. In the meantime, refer to @damieng 's suggestion:

> Atom Beta is expected to use the same config and settings as regular Atom right now so I wouldn't expect it to show the welcome guide or telemetry consent.
>
>The real problem right now is that beta and non-beta on Windows share the same setup-id in Squirrel so one is considered an upgrade to the other.
>
>One option for now would be to use the beta zip and unpack that somewhere. That should allow you to run side-by-side. If you want the beta to also use a separate config then you should be able to create an empty .atom folder in the folder about where you unpacked the beta, e.g.
>
>```
>c:\apps\atombeta
>c:\apps\.atom
>
>```

**Comment by paulcbetts** [comment] 2017-06-14 17:03
Hi all, I've written the first version of a tool designed to solve this problem: https://github.com/atom/avm

Here's how to get started:

```
npm install -g atom-version-manager

## Install the stable version:
avm switch stable

## Switch to the beta
avm switch beta
```

The initial run of these commands will take awhile as it downloads Atom and installs it, but from then on switching between the two will be very fast (i.e. 2-3 sec or so). Let me know if this helps!

**Comment by MartyGentillon** [comment] 2017-06-18 22:58
At a minimum, it would be nice to mention something about this on the atom beta website.  It's really annoying to discover after the fact that it blew away my stable atom install.

**Comment by MorganMarshall** [comment] 2017-08-15 10:02
Guys, tons of people are wasting a lot of time on this. Like everyone is suggesting please remove the side by side sales pitch from the site, at least on windows side. From the looks of this thread it hasn't worked in years. Its causing a lot of confusion and cursing.

**Closed** 2019-07-16 14:51 UTC
Labels: :night_with_stars: nightly-releases, installer, triaged, windows
