### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by pdulong** [atom/atom#15280] opened 2017-08-13 07:40 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2168

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2168:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:385:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:52 core:copy (input.hidden-input)
     -1:49.7.0 core:close (div.results-view.focusable-panel)
     -1:49 find-and-replace:show (input.hidden-input)
     -1:48.8.0 core:paste (input.hidden-input)
     -1:48.7.0 core:confirm (input.hidden-input)
     -1:46.8.0 find-and-replace:find-next (input.hidden-input)
     -1:19.9.0 core:copy (input.hidden-input)
     -1:18.2.0 core:select-all (input.hidden-input)
     -1:17.6.0 core:paste (input.hidden-input)
     -1:16.6.0 core:select-all (input.hidden-input)
     -1:16.4.0 core:paste (input.hidden-input)
     -0:53.4.0 find-and-replace:show (input.hidden-input)
 11x -0:49.5.0 find-and-replace:find-next (input.hidden-input)
     -0:39.7.0 core:save (input.hidden-input)
  8x -0:38.7.0 find-and-replace:find-next (input.hidden-input)
  2x -0:09.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
etheratom 3.1.0 
intentions 1.1.5 
language-ethereum 0.3.9 
linter 2.2.0 
linter-eslint 8.2.1 
linter-solidity 0.5.0 
linter-ui-default 1.6.4 
merge-conflicts 1.4.5 
react 0.16.2 
```

**Comment by Ben3eeE** [comment] 2017-08-13 08:33
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15168.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-13 08:33 UTC
Labels: duplicate
