### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\C:\ProgramData\battupa\atom\app-1.2...

### ISSUE THREAD

**Issue by alokreddy** [atom/atom#17476] opened 2018-06-06 06:29 UTC
[Enter steps to reproduce:]

1. On startup 
2. Atom throws this error

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\ProgramData\battupa\atom\app-1.27.2\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\ProgramData\battupa\atom\app-1.27.2\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (C:/ProgramData/battupa/atom/app-1.27.2/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (C:/ProgramData/battupa/atom/app-1.27.2/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (C:/ProgramData/battupa/atom/app-1.27.2/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (C:/ProgramData/battupa/atom/app-1.27.2/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (C:/ProgramData/battupa/atom/app-1.27.2/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (C:/ProgramData/battupa/atom/app-1.27.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:/ProgramData/battupa/atom/app-1.27.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (C:/ProgramData/battupa/atom/app-1.27.2/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
busy-signal 1.4.3 
genesis-ui 0.5.0 
Hydrogen undefined 
intentions 1.1.5 
linter 2.2.0 
linter-python 3.1.2 
linter-ui-default 1.7.1 
python-indent 1.1.5 
python-tools 0.6.9 
react-snippets 1.1.1 
```

**Comment by rsese** [comment] 2018-06-06 19:06
I think this could be a duplicate of issues like #15722. If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled. If you don't have any anti-virus software running or re-installing doesn't help, then this could be a duplicate of #14461 and you can subscribe there if you'd like.

**Closed by rsese** 2018-06-06 19:06 UTC
