### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by fejfar** [atom/atom#5544] opened 2015-02-13 15:13 UTC
Uncaught Error: Atom can only handle files < 2MB for now.

**Atom Version**: 0.158.0
**System**: linux 3.13.0-37-generic
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /usr/share/atom/resources/app/src/project.js:461

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:461:15)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:438:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:392:19)
  at Workspace.module.exports.Workspace.openUriInPane (/usr/share/atom/resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:409:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

**Comment by postcasio** [comment] 2015-02-13 15:23
Duplicate of #4421 and #307. Please subscribe there for updates.

**Closed by postcasio** 2015-02-13 15:23 UTC
