### ISSUE TITLE
Inconsistent Background Colour on Second Display

### ISSUE THREAD

**Issue by jasonroyle** [atom/atom#14627] opened 2017-05-24 16:00 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Different shades of colours rendering in blocks in the background of the editor window on a second display.

Primary display:
<img width="1052" alt="screen shot 2017-05-24 at 16 01 13" src="https://cloud.githubusercontent.com/assets/439662/26412724/988a2c2c-40a1-11e7-9e7e-f2bad5b2bc60.png">

Secondary display:
![screen shot 2017-05-24 at 16 00 44](https://cloud.githubusercontent.com/assets/439662/26412756/b23ed5c8-40a1-11e7-85c7-0c282290ea8e.png)

### Steps to Reproduce

1. Open a document in Atom.
2. Drag the Atom window to a second display.
3. Expand the window until the the blocks of colours are visible.

**Expected behavior:** Background colour should be consistent (as it is on the primary display).

**Actual behavior:** Background colour renders in blocks of different shades.

**Reproduces how often:** 100%

### Versions

OS: macOS Sierra 10.12.6 Beta (16G8c)

Atom: 1.17.0
Electron: 1.3.15
Chrome: 52.0.2743.82
Node: 6.5.0
apm: 1.17.0
npm: 3.10.5
node: 6.9.5 x64
python: 2.7.10
git: 2.11.0

Atom: 1.18.0-beta0
Electron: 1.3.15
Chrome: 52.0.2743.82
Node: 6.5.0
apm: 1.18.1
npm: 3.10.10
node: 6.9.5 x64
python: 2.7.10
git: 2.11.0

### Additional Information

Hardware:

- MacBook Pro (Retina, 15-inch, Early 2013)
- NVIDIA GeForce GT 650M 1024 MB
- Intel HD Graphics 4000 1536 MB

The behaviour is much easier to see when using dark themes but is visible on all themes I have tested.

I was seeing the exact same behaviour when using the `Caret` markdown editor which also runs on `Electron`. I reported the issue and they fixed it in [version 1.14.0](https://github.com/careteditor/caret/releases/tag/1.14.0). See the [conversion](https://storify.com/jasonroyle/conversation-with-jasonroyle-and-careteditor) that I had with them (with examples).

**Comment by 50Wliu** [comment] 2017-05-24 17:03
Duplicate of #12634; will be fixed in Atom 1.19.0.

**Closed by 50Wliu** 2017-05-24 17:03 UTC
