### ISSUE TITLE
Bug moving lines of text

### ISSUE THREAD

**Issue by rpavez** [atom/atom#10340] opened 2016-01-08 14:07 UTC
Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

[Enter steps to reproduce below:]

1. Select multiple lines
2. Drag those lines below
3. Press undo and try again

**Atom Version**: 1.3.2
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'restoreFromSnapshot' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280

TypeError: Cannot read property 'restoreFromSnapshot' of undefined
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1280:55)
    at TextBuffer.module.exports.TextBuffer.undo (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1186:31
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2082:18)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2064:35)
    at TextEditor.module.exports.TextEditor.undo (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1184:12)
    at TextEditor.commandRegistry.add.stopEventPropagation.core:undo (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:223:21)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:554:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:23.2.0 core:redo (atom-text-editor.editor.is-focused)
     -0:07.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:05.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.9.0 pane:split-down (atom-text-editor.editor.is-focused)
     -0:02.0 pane:close (atom-text-editor.editor)
  2x -0:01.1.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2016-01-08 14:18
This looks like a duplicate of https://github.com/atom/atom/issues/9918 and has been fixed for the next patch release of Atom.

**Closed by mnquintana** 2016-01-08 14:18 UTC
