### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/v3ss/rethink_latest/tags'

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#6474] opened 2015-04-22 10:56 UTC
I believe opening of non-existance file shoould prompt to create a new file instead of  Uncaught Error. 
1. Open a missing file
2. PROFIT!

**Atom Version**: 0.195.0-ecd0444
**System**: linux 3.17.0-sabayon
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/v3ss/rethink_latest/tags'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/home/v3ss/rethink_latest/tags'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-ruby-on-rails",
      "mobile-preview",
      "atom-html-preview",
      "color-picker",
      "run-command",
      "runcoderun",
      "script",
      "whitespace",
      "svg-preview",
      "autosave",
      "autocomplete-jedi",
      "autocomplete-plus-async",
      "cute-cursor",
      "pulsing-cursor",
      "neon-selection",
      "pdf-view",
      "atom-lint",
      "animation-showcase",
      "vim-mode",
      "tree-view-open-files",
      "autocomplete",
      "auto-reveal-in-sidebar",
      "ease-blink",
      "highlight-line",
      "minimap-highlight-selected",
      "tree-view",
      "tabs"
    ],
    "ignoredNames": [
      "*.pyc",
      "/home/v3ss/workspace/phwa.be/condaenv",
      "/home/v3ss/workspace/phwa.be/pypyenv",
      "*.zip",
      "*.tar",
      ".hg"
    ],
    "autoHideMenuBar": true,
    "audioBeep": false,
    "themes": [
      "one-dark-pirate-ui",
      "neon-pirate"
    ]
  },
  "editor": {
    "preferredLineLength": 120,
    "tabLength": 4,
    "confirmCheckoutHeadRevision": false,
    "scrollPastEnd": true,
    "autoIndentOnPaste": false,
    "scrollSensitivity": 80,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": false,
    "fontFamily": "NK57 Monospace",
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-atom-api, v0.8.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.12.0
autocomplete-plus-python-jedi, v0.2.6
block-cursor, v0.12.4
block-travel, v1.0.2
build, v0.29.0
editorconfig, v0.3.3
file-type-icons, v0.5.4
highlight-column, v0.4.0
highlight-selected, v0.9.2
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-flake8, v1.4.0
linter-jshint, v0.1.2
linter-tidy, v1.0.0
linter-xmllint, v0.0.5
local-history, v3.1.0
minimap, v4.7.6
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-selection, v4.2.0
neon-pirate, v0.3.5
one-dark-pirate-ui, v0.6.3
project-palette-finder, v2.4.16
script-runner, v1.7.3
sublime-tabs, v0.5.4
symbols-tree-view, v0.9.2
web-browser, v1.4.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-04-22 16:38
Duplicate of #6372 and possibly #6210.

**Closed by 50Wliu** 2015-04-22 16:38 UTC
