### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 9Error: Cannot call ...

### ISSUE THREAD

**Issue by Runawary** [atom/atom#17058] opened 2018-03-31 00:43 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 9
Error: Cannot call function 'getPosition' on missing remote object 9
    at throwRPCError (C:\Users\kexin\AppData\Local\atom\app-1.25.0\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\kexin\AppData\Local\atom\app-1.25.0\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\Users\kexin\AppData\Local\atom\app-1.25.0\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At C:\Users\kexin\AppData\Local\atom\app-1.25.0\resources\electron.asar\renderer\api\remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 9
Error: Cannot call function 'getPosition' on missing remote object 9
    at throwRPCError (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.25.0/resources/app/src/atom-environment.js:691:40)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.25.0/resources/app/src/atom-environment.js:728:40)
    at WindowEventHandler.handleWindowResize (~/AppData/Local/atom/app-1.25.0/resources/app/src/window-event-handler.js:195:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-python-run 0.9.6 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.18 
highlight-selected 0.13.1 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
simplified-chinese-menu 5.3.5 
```

**Comment by Arcanemagus** [comment] 2018-03-31 03:40
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16630. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-31 03:40 UTC
