### ISSUE TITLE
Caret positioning is incorrect in Atom 1.1 - does not land correctly on first character

### ISSUE THREAD

**Issue by mrapczynski** [atom/atom#9356] opened 2015-10-30 17:04 UTC
I excitedly installed Atom 1.1 - which seems a lot faster - but now I paid the price for early adopting because the caret seems messed up and is confusing when editing a file. I have included a little screen grab and associated shot showing the cursor position read out in the footer.

GitHub rejected my .mov attachment so here is posted on S3: http://fhda.s3.amazonaws.com/atom-1.1-cursor-bug.mov

And the screenshot showing the cursor position to be "5:1" but graphically the caret is 1 or 1.5 steps forward.

<img width="316" alt="screen shot 2015-10-30 at 9 59 14 am" src="https://cloud.githubusercontent.com/assets/258614/10852339/7b6907de-7eed-11e5-97f5-fe03e0735f31.png">

Thanks!

**Comment by izuzak** [comment] 2015-10-30 17:08
Thanks for the report, @mrapczynski -- I think this is a duplicate of #9343. Can you take a look in there and let us know if your problem is not covered by that? Seems like a problem with the seti syntax theme after upgrading to Atom 1.1

**Closed by izuzak** 2015-10-30 17:08 UTC

**Comment by mrapczynski** [comment] 2015-10-30 17:10
@izuzak Ah, yeah that did it! I have had the theme enabled for so long I totally forgot about it. Thanks for the fast support.
