### ISSUE TITLE
Not open any files from command prompt after upgrade to 1.0.9

### ISSUE THREAD

**Issue by qiluo** [atom/atom#8585] opened 2015-08-31 01:11 UTC
When I typed in `atom .` or `atom somefile`, I kept got below error
```
index.js:56 TypeError: Cannot redefine property: .ts
    at Function.defineProperty (native)
    at c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:164:10
    at Array.forEach (native)
    at Object.<anonymous> (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:161:24)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value (C:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at new Task (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\task.js:32:26)
    at Function.module.exports.Task.once (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\task.js:19:14)
    at GitRepository.module.exports.GitRepository.refreshStatus (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\git-repository.js:398:37)
    at GitRepositoryProvider.module.exports.GitRepositoryProvider.repositoryForDirectorySync (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\git-repository-provider.js:56:14)
    at Project.module.exports.Project.addPath (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\project.js:270:89)
    at Project.module.exports.Project.setPaths (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\project.js:231:14)
    at new Project (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\project.js:87:12)
    at Function.module.exports.Serializable.deserialize (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\node_modules\serializable\lib\serializable.js:72:22)
    at DeserializerManager.module.exports.DeserializerManager.deserialize (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\deserializer-manager.js:42:29)
    at Atom.module.exports.Atom.deserializeProject (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\atom.js:812:52)
    at Atom.module.exports.Atom.deserializeEditorWindow (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\atom.js:842:12)
    at Atom.module.exports.Atom.startEditorWindow (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\atom.js:668:12)
    at Object.<anonymous> (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\window-bootstrap.js:12:8)
    at Object.<anonymous> (c:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value (C:\Users\xyz\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at setupWindow (file:///C:/Users/xyz/AppData/Local/atom/app-1.0.9/resources/app.asar/static/index.js:82:25)
    at window.on
```

but I can properly use Atom if I open Atom from start menu.

I'm on Win7, 64bits

**Comment by 50Wliu** [comment] 2015-08-31 01:39
Duplicate of #8551, please subscribe there for updates.

**Closed by 50Wliu** 2015-08-31 01:39 UTC
