### ISSUE TITLE
Duplicate file -- persist rename dialog

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#10871] opened 2016-02-17 21:31 UTC
TEST CASE:

1. Open a directory of files
2. Right click one of the files and click DUPLICATE
3. (The rename box appears)
4. Alt-tab to another application and copy the name of the file you want
5. Alt-tab back to Atom

EXPECTED

The rename box is still there so you can paste into it

ACTUAL

It disappears

**Comment by mnquintana** [comment] 2016-02-17 23:15
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/1918 though – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-02-17 23:15 UTC
