### ISSUE TITLE
Atom prompts for update to 1.10 although I'm running 1.2.3

### ISSUE THREAD

**Issue by prabinv** [atom/atom#9725] opened 2015-11-20 21:19 UTC
I'm running version 1.2.3 on a Mac OS X 10.11.1 (El Capitan). I've been getting an update alert showing "Update and Restart" to 1.10. I've attached the screenshot.
<img width="954" alt="screen shot 2015-11-20 at 3 01 05 pm" src="https://cloud.githubusercontent.com/assets/306468/11312068/50dd59cc-8f99-11e5-8a93-1af9072d3e82.png">

**Comment by mnquintana** [comment] 2015-11-20 21:29
Thanks for the report! This looks like a duplicate of https://github.com/atom/release-notes/issues/39 - feel free to subscribe there for updates.

**Closed by mnquintana** 2015-11-20 21:29 UTC
