### ISSUE TITLE
Very slow on find and replace compared with VS Code

### ISSUE THREAD

**Issue by tigrankhachikyan** [atom/atom#16213] opened 2017-11-16 18:52 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It is ver-very slow on find and replace on a file where the items to replace are pretty much. 
For example, I need to replace ~343200 `#012` string into `\n` (with regex) or even without regex, replace `#012` => `.`.

It never finished (at least I didn't waited and killed the process ).
You can use the attached file. [012-1.7MB.txt.zip](https://github.com/atom/atom/files/1479767/012-1.7MB.txt.zip)

I'm filing this issue as when I do the same in VS Code it takes just a couple of seconds.

### Steps to Reproduce
In find and Replace window do the following:
Find => `#012`,
Replace with `\n` (with `.*`)
or
Replace with `.` (raw text)

**Expected behavior:** Complete in a couple of seconds 

**Actual behavior:** very long time / killed the process 

**Reproduces how often:** always on the attached file

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
```
atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.15.0
```
### Additional Information
foe comparison VS Code version:
```
/code --version
1.18.0
dcee2202709a4f223185514b9275aa4229841aa7
```
Hardware: MacBook Pro (13-inch, 2017)

Any additional information, configuration or data that might be necessary to reproduce the issue.
See the attached file to reproduce.

**Comment by rsese** [comment] 2017-11-16 22:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/653. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-16 22:56 UTC
