### ISSUE TITLE
“Restart and install updates” silently fails and does nothing

### ISSUE THREAD

**Issue by MidnightLightning** [atom/atom#5880] opened 2015-03-06 04:13 UTC
On my Mac (10.9.5), my Atom app notices when there's an update, and indicates it by adding a "Restart and install updates" option in the "Atom" menu. If I choose that menu option, Atom quits, and relaunches, but it's the same version it was; no update seems to have happened.

Looking in the Console log, it seems "ShipIt" is running into issues trying to install Atom, since it can't copy the application to the proper folder:

    3/5/15 9:25:53.041 AM ShipIt[54372]: Couldn't abort install and restore owned bundle to previous location file:///Applications/Atom.app, error NSError { domain: NSPOSIXErrorDomain, code: 2, description: "No such file or directory" }
    
    3/5/15 9:26:19.075 AM ShipIt[54372]: Installation error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo=0x7ff3e3bde200 {NSLocalizedDescription=Permission denied}
Atom.app is in the Applications folder, but my user is not an Admin of the computer, so doesn't have permission to copy a file into the Applications folder. Atom should probably pop up an authentication prompt to accomplish that task? Or more gracefully fail out with a dialog to the user indicating there was an error?

**Comment by thomasjo** [comment] 2015-03-06 06:36
Thanks for your report. This seems like a duplicate of #2860, so I'm closing this one. Subscribe to the other issue for updates, etc.

**Closed by thomasjo** 2015-03-06 06:36 UTC
