### ISSUE TITLE
Garbage characters at number gutter

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#6249] opened 2015-04-04 19:11 UTC
Updated to 0.189 and  i see this :
![garbage](https://cloud.githubusercontent.com/assets/419606/6994170/e01d57aa-db34-11e4-905e-de5abc8ed118.png)

there is one garbage char on the left side of each line number.

**Comment by izuzak** [comment] 2015-04-04 19:16
Which OS are you on? Do you see that problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) as well? Which font are you using? Do you see that problem with every font?

**Comment by v3ss0n** [comment] 2015-04-04 19:21
I've tested on Linux Sabayon 3.17 kernel , yes safe mode. 
My own modification of Unispace font. It dosen't happen before.
Tested with other fonts , they are fine.

**Comment by izuzak** [comment] 2015-04-04 19:25
Sounds like a duplicate of https://github.com/atom/atom/issues/5488. Can you check that and close this if they are the same thing or provide more details to explain in what way they're not?

**Comment by v3ss0n** [comment] 2015-04-04 19:34
so this will be fix only when chromuim fixed , right ?

**Comment by v3ss0n** [comment] 2015-04-04 20:24
not sure if i did is right , but i copy the normal space on top of nbsp. and its looking ok. (it do not have NBSP before).

**Comment by izuzak** [comment] 2015-04-05 10:19
> so this will be fix only when chromuim fixed , right ?

I don't know the answer to that. Suggestion: subscribe to https://github.com/atom/atom/issues/5488 for updates. I'm closing this since it looks like a duplicate of that issue.

**Closed by izuzak** 2015-04-05 10:19 UTC
Labels: more-information-needed
