### ISSUE TITLE
Uncaught Endless loop detected

### ISSUE THREAD

**Issue by mikpatte** [atom/atom#4481] opened 2014-12-09 21:04 UTC
Uncaught Endless loop detected

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:121

undefined
```

**Comment by kevinsawicki** [comment] 2015-07-27 23:35
Closing this out since the stack trace contained no frames and it doesn't seem like it is still reproducible, please comment if you are still seeing this issue though.

**Closed by kevinsawicki** 2015-07-27 23:35 UTC
Labels: more-information-needed, uncaught-exception

**Comment by manasc** [comment] 2018-02-16 17:32
Hey, for me I had this issue when I put this snippet into my keymap.cson:

**Comment by manasc** [comment] 2018-02-16 17:34
Hey, I got this error when I put this snipped into my keymap.cson:
```
'atom-text-editor':
    'cmd-shift-up': 'editor:add-selection-above'
    'cmd-shift-down': 'editor:add-selection-below'
    'cmd-w': 'editor:toggle-soft-wrap'

'atom-text-editor[data-grammar="text html php"]:not([mini])':
    'tab': 'emmet:expand-abbreviation'

'atom-text-editor[data-grammar~="jsx"]:not([mini])':
    'tab': 'emmet:expand-abbreviation'
```

Just had to change `emmet:expand-abbreviation` to `emmet:expand-abbreviation-with-tab`
