### ISSUE TITLE
html preview corrupt since 1.47

### ISSUE THREAD

**Issue by hhaensel** [atom/atom#20763] opened 2020-05-20 15:07 UTC
since the latest update to version 1.47 any html preview panes don't work. I experience this in `atom-html-preview` as well as in the plot pane of `julia-client.`

(Windows 10)

**Comment by ashthespy** [comment] 2020-05-20 16:19
cc #20604  #20754

**Comment by lkashef** [comment] 2020-05-22 15:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #20604  #20754. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lkashef** 2020-05-22 15:28 UTC
Labels: duplicate
