### ISSUE TITLE
Can't Cmd-V paste into file open dialog in OSX

### ISSUE THREAD

**Issue by bedge** [atom/atom#11050] opened 2016-03-04 01:30 UTC
### Prerequisites

yes to all - pre-req's

### Description

Cannot paste a string into the file open dialog prompt

### Steps to Reproduce

- Open file dialog - Cmd o
- "Go to folder" - Cmd-shift g - opens a text input box
- backspace to clear default text, OK so far
- Paste (or try to) in path - Cmd v  - does nothing.

![screen shot 2016-03-03 at 5 29 42 pm](https://cloud.githubusercontent.com/assets/499317/13515363/915f22a0-e165-11e5-8d98-f2c68980e66c.png)
At this point I wold expect my clipboard contents to appear in the file dialog prompt box. Instead, nothing happens.

However, I can paste in there using Rt-click - paste with the mouse.

### Versions

%> atom --version
1.5.3

**Comment by alexchandel** [comment] 2016-03-04 08:07
Confirmed. That is weird. And confirmed that it works normally in Finder, Safari, and Chrome. Atom must be doing something weird with keyboard shortcuts...

**Comment by 50Wliu** [comment] 2016-03-04 15:27
This is actually a duplicate of #10446, so feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-04 15:27 UTC
Labels: mac, needs-reproduction
