### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by FrankDraws** [atom/atom#14861] opened 2017-06-21 12:46 UTC
[Enter steps to reproduce:]

1. Opened Atom Beta.
2. Errors began displaying and won't stop even after restart.

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2132

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2132:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2128:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:373:16)
    at scheduler.readDocument (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:263:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
  3x -0:15.2.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
atom-panels 0.4.1 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
emmet 2.4.3 
markdown-writer 2.6.5 
mobile-preview 0.4.0 
monokai 0.24.0 
platformio-ide-terminal 2.5.1 
Sass-Syntax-Highlight 0.1.1 
```

**Comment by rsese** [comment] 2017-06-21 17:27
Thanks for the report!  Do you see the error in safe mode as well (`atom --safe`)?

**Comment by rsese** [comment] 2017-06-21 17:30
Oh I also just realized this is a dupe of https://github.com/atom/atom/issues/14794, same stack trace - I'll close this and we can move the conversation there @FrankDraws :v:

**Closed by rsese** 2017-06-21 17:30 UTC
Labels: more-information-needed, uncaught-exception
