### ISSUE TITLE
Crash when I create a file named "todo"

### ISSUE THREAD

**Issue by emmanueltriballier** [atom/atom#8318] opened 2015-08-11 08:21 UTC
Atom 1.0.5 crashes when I want to create a file from the tree on the left, if I give the name "todo".

**Comment by izuzak** [comment] 2015-08-11 08:33
@emmanueltriballier Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Also, which OS+version are you on?

**Comment by emmanueltriballier** [comment] 2015-08-11 18:17
The crash happens on Windows 10 and Windows 8.1 when I create the file from the tree on the left.
In safe mode, I can see "Maximum call stack size excedeed".

**Comment by izuzak** [comment] 2015-08-12 11:11
> In safe mode, I can see "Maximum call stack size excedeed".

@emmanueltriballier Where do you see that exactly? Can you share a screenshot? Sharing as many details as possible would be helpful.

**Comment by emmanueltriballier** [comment] 2015-08-12 18:44
Here is a screenshot :
![crash](https://cloud.githubusercontent.com/assets/41192/9233082/6e19fcae-4131-11e5-97c7-1b1eab686dba.png)

Important : you have to create the file from the tree on the left, not from the top menu of the app.

One detail : the "Test" folder is stored on my Google Drive

**Comment by emmanueltriballier** [comment] 2015-09-05 18:46
The crash no longer occurs under Atom 1.0.11. @izuzak You've fixed something ?

**Comment by izuzak** [comment] 2015-09-07 06:34
@emmanueltriballier Thanks for letting us know. I'm not aware of any changes which were made to intentionally address this, but it's possible that some changes unintentionally fixed this.

Since you can no longer reproduce this (and I wasn't able to reproduce before), I'm going to close this. If this starts happening again -- let me know.

**Closed by izuzak** 2015-09-07 06:34 UTC
Labels: more-information-needed
