### ISSUE TITLE
Password dialog to edit root files does not appear

### ISSUE THREAD

**Issue by ivan-kleshnin** [atom/atom#15396] opened 2017-08-21 09:42 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

OSX. I didn't have this problem before. But the editor now refuses to edit `/etc/hosts` showing an alert "Unable to save file... Blah-blah... permissions". Running as `sudo atom /etc/hosts` does not help. Previously, when I edited this file with Atom, it showed a dialog box where I could enter a root password. Now it's just a non-interactive alert.

### Steps to Reproduce

1. `$ atom /etc/hosts`
2. Edit file
3. Save file
4. Watch worthless alert instead of a dialog box

**Expected behavior:** [What you expect to happen]

4\. Provide a dialog box to enter root password.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always. 

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Info

I didn't change permissions for `/etc/hosts`, all my setup is the same as it was before, except for possibly some language-specific Atom plugins.

**Comment by Ben3eeE** [comment] 2017-08-21 09:46
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15267.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-21 09:46 UTC
Labels: duplicate
