### ISSUE TITLE
Atom hangs on changing tab of deleted file

### ISSUE THREAD

**Issue by gokulkulkarni1987** [atom/atom#15705] opened 2017-09-21 06:41 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom hangs on changing tab of deleted file

### Steps to Reproduce

1. Create a file (say foo).
2. Open foo
3. Delete foo.
4. Open another file (say foo1).
5. Try to change the tab using ctrl+tab

**Expected behavior:** 
Atom must not consider the deleted file while changing the tab

**Actual behavior:** [What actually happens]
Atom tries to open the deleted file and atom freezes.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

atom --version => 
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version =>
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by kevinvdburgt** [comment] 2017-09-21 14:45
What OS are you using?

Tried to reproduce this problem but it works fine for me (MacOS)

**Comment by rsese** [comment] 2017-09-21 18:36
I'm also unable to reproduce on macOS 10.12.6 and Atom `1.22.0-dev-615b67b46` - can you also share a GIF that demonstrates this behavior @gokulkulkarni1987?

**Comment by gokulkulkarni1987** [comment] 2017-09-22 00:22
@kevinvdburgt I am using Mac10.12.6

**Comment by gokulkulkarni1987** [comment] 2017-09-22 00:22
@rsese I will get GIF

**Comment by rsese** [comment] 2018-01-19 22:17
Closing for now but if you have that GIF/can still reproduce @gokulkulkarni1987 we can definitely re-open.

**Closed by rsese** 2018-01-19 22:17 UTC
Labels: more-information-needed
