### ISSUE TITLE
Assertion Failed Error on Git repos with missing path

### ISSUE THREAD

**Issue by tigerhawkvok** [atom/atom#11196] opened 2016-03-18 08:33 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

If a git repo has a missing submodule path (compared to what's set up in git), Atom throws assertion errors.

### Steps to Reproduce

1. Create a git repo
2. Include a submodule
3. Delete the submodule path from your working tree, but don't really "remove" the submodule
4. Open the project directory in Atom

**Expected behavior:** [What you expected to happen]

A usable Atom

**Actual behavior:** [What actually happened]

Atom throws C++ "Assertion Failed" errors repeatedly, and throws uncaught errors in console:

```
Uncaught (in promise) Error: Failed to resolve path 'C:\path\to\submodule\dir': The system cannot find the file specified.



    at Error (native)
```

![screenshot 2016-03-17 19 53 53](https://cloud.githubusercontent.com/assets/165937/13872651/51ab7132-eca9-11e5-8703-d82f45fc3a7a.png)

### Versions

apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.3
git 2.7.1.windows.1
visual studio 2013

**Comment by joshaber** [comment] 2016-03-18 15:24
@tigerhawkvok Thanks for letting us know! I'm looking into it.

**Comment by joshaber** [comment] 2016-03-18 16:52
@tigerhawkvok I haven't been able to reproduce this given those steps. I see an error in the console, but no assertion failure popups.

**Comment by tigerhawkvok** [comment] 2016-03-18 20:25
Interesting. Unmounting the project directory definitely made the error go away, I'll dig some more and try to narrow it down

**Comment by aerth** [comment] 2016-03-30 10:49
I just happened to run into this bug with a bad .gitmodule file, removed it and it went away.

contents of .gitmodules:
```
[submodule "dbtool"]
        path = ./cmd/dbtool
        url = https://github.com/some/repo

```

Steps to reproduce the error:

1. `cd` into a basic git repo directory
2. create .gitmodules and add the above to it.
3. run: `atom .`
4. Fix: rm .gitmodules

In linux there was no popup error like yours, it just  says "The editor has crashed - Please report this issue to https://github.com/atom/atom" but I ended up seeing the error message in the terminal window (pasted below)

```awk
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.9
git 2.1.4
```

Here is the error message in console, which is the same as the Windows popup one @tigerhawkvok posted.
```
App load time: 1656ms
[18007:0330/033105:INFO:CONSOLE(52)] "Window load time: 3147ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (52)
[18007:0330/033105:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
atom --type=renderer --js-flags=--harmony --no-sandbox --lang=en-US --node-integration=true --enable-delegated-renderer --num-raster-threads=1 --gpu-rasterization-msaa-sample-count=8 --content-image-texture-target=3553 --video-image-texture-target=3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --channel=18007.1.1934519337 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd: ../vendor/libgit2/src/submodule.c:1673: int submodule_load_from_config(const git_config_entry *, void *): Assertion `error != 0' failed.
Failed to get crash dump id.
Report Id: 

```

Literally had no idea what was going on until i seen `../vendor/libgit2/src/submodule.c:1673: int `

**Comment by joshaber** [comment] 2016-05-04 15:26
It looks like this is https://github.com/libgit2/libgit2/issues/3414, which has happily been fixed in libgit2. Nodegit [just recently upgraded](https://github.com/nodegit/nodegit/pull/1010) to the latest release of libgit2 which includes the fix.

So once a new release of Nodegit is available, we _should_ be able to update and fix this.

Thanks for all the reports!

**Comment by 50Wliu** [comment] 2016-06-10 12:48
Atom is using Nodegit 0.13.0 on master, so I think this can be closed now.

**Closed by 50Wliu** 2016-06-10 12:48 UTC
Labels: atom, blocked, bug, git
