### ISSUE TITLE
Decompose ligatures when the cursor is in/beside them

### ISSUE THREAD

**Issue by JoeyEremondi** [atom/atom#11567] opened 2016-04-22 00:54 UTC
### Description

I use FiraCode2 with ligature support in Atom, and for the most part it's very nice.

However, I find it very difficult to edit ligatures. For example, I often need to change <$> to <*> in Haskell, but Atom does not show where in the ligature the cursor is, and I often lose time erasing the wrong part of the ligature.
Similarly, I will often try to delete the space before an arrow -> , but I end up deleting the first dash - because the cursor is shown beside the ligature, even when its actual position is in the middle.

Ideally, when the cursor was at the edge of, or inside a ligature, it would be rendered not as the single character, but as the actual simple characters which make it up.

Is this possible? If it is not, consider this a request that it be added, or at least supported in a package.

Thanks!

### Steps to Reproduce

1. Set the font to FiraCode, HaskLig, or another ligature-supporting font
2. Enter a ligature, such as `->`
3. Move the cursor from one side to the ligature of the other

**Expected behavior:** The ligature is decomposed into its constituent characters, or the cursor is shown inside the ligature.

**Actual behavior:** The cursor remains to the right of the ligature.

### Versions

I've tested in 1.7.1, but it showed up in all previous versions I'd used.

**Comment by bj7** [comment] 2016-04-22 02:15
What OS are you on?

**Comment by JoeyEremondi** [comment] 2016-04-22 02:27
@bj7 I'm on Linux. 

I just tried it with Atom 1.7.2 on Windows, and the cursors show up in the middle of the ligature, which solves the problem. 

I'd initially thought this was a feature request, but maybe this is a bug on Linux?

If it helps, the linux stylesheet is as follows:

```css
// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
  text-rendering: optimizeLegibility;
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}
```

**Comment by JoeyEremondi** [comment] 2016-04-22 02:33
I just updated to 1.7.2 on Linux, and the problem still persists, so it does not appear to be a version issue.

**Comment by JoeyEremondi** [comment] 2016-04-26 00:09
Having done some more experimenting, it seems the problem is not with Windows vs. Linux, but latter with FiraCode vs Hasklig. Both Windows and Linux show the error with Hasklig, and neither with FiraCode.

This could be an Atom bug, or just a bug wth Hasklig.

In any case, my apologies for the misdirection with this.

**Comment by bj7** [comment] 2016-04-26 01:18
@JoeyEremondi, perhaps try using the Hasklig in another editor on both systems to determine if it is a rendering issue in Atom only, or if it's a larger system issue. I thought your issue was primarily with Fira Code? I haven't tried Hasklig on OS X, but I will and see if I can replicate the bug.

**Comment by bj7** [comment] 2016-04-26 12:39
I can reproduce the issues in Hasklig v0.9 on OS X and Atom v1.7.2. I used Hasklig in another non-Electron-based editor to test ligature support, and it worked fine. I tested Hasklig in Visual Studio Code (Electron based) and the problem persists. Fira Code works perfectly for both Atom and VS Code. This is not Atom specific.

This may be an issue with how Electron handles Hasklig, or it could be an issue with Hasklig itself (it is only v0.9), or it could be much deeper. Electron is based on Chromium, so if Chromium does not properly handle Hasklig ligatures, then Electron would most likely not, either. This is speculation on my part since I have not investigated Electron's source enough to say what it relies on to render fonts. 

I recommend this issue is either closed, or opened under Electron/Hasklig repos.

**Comment by lee-dohm** [comment] 2016-04-27 23:18
Since this is only a problem with the Hasklig font and not the Fira Code one, I'm going to close this. It does seem like it could be a problem with Electron or Chromium rather than Hasklig, but it appears that Hasklig is probably the most likely suspect right now. Please feel free to reopen this if I have misunderstood the problem.

**Closed by lee-dohm** 2016-04-27 23:18 UTC
Labels: bug, editor-rendering, more-information-needed

**Comment by phyllisstein** [comment] 2017-01-09 18:59
I was able to reproduce this on macOS Sierra and the PragmataPro font with Atom stable and Atom beta. Here's a GIF of what happens when I navigate over a ligature in a completely clean Atom Beta instance:

![screenflow](https://cloud.githubusercontent.com/assets/2207980/21778940/6ad4dc3e-d673-11e6-9b9a-aa3c105a04da.gif)

For comparison, here's what happens in the latest nightly of iTerm2:

![screenflow](https://cloud.githubusercontent.com/assets/2207980/21779009/bd40aeb2-d673-11e6-88df-243d256eea9a.gif)

It seems reasonable to conclude that something is up with Atom's (or Electron's) text rendering here, but unfortunately I don't have much more insight than that. I'd be grateful for any suggestions or thoughts from @lee-dohm and the other maintainers.

**Comment by phyllisstein** [comment] 2017-01-09 19:09
...conversely, and puzzlingly, Hasklig's ligatures do not exhibit this behavior in Atom beta:

![screenflow](https://cloud.githubusercontent.com/assets/2207980/21779343/3f7b8d38-d675-11e6-8758-1f748284c37c.gif)

**Comment by phyllisstein** [comment] 2017-01-12 08:15
Looks like this was cleared up in i-tu/Hasklig#40. It's because Pragmata Pro uses the `liga` OpenType feature and Hasklig uses `calt`.
