### ISSUE TITLE
The atom terminal command does not open a new window

### ISSUE THREAD

**Issue by albireox** [atom/atom#11738] opened 2016-05-12 02:18 UTC
The terminal commands `atom` or `atom --wait` do not open a new Atom window as expected when there is at least one already opened Atom window. When no windows exists, the command works and opens a new window. This makes Atom almost useless as git editor.

I see this behaviour both in atom-1.8.0-beta3 and 1.7.3. I'm running OSX 10.11.5. My shell is fish.

**Comment by 50Wliu** [comment] 2016-05-12 02:27
This is a duplicate of #11712 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-12 02:27 UTC
