### ISSUE TITLE
If all windows are closed preferences does not open

### ISSUE THREAD

**Issue by jekriske** [atom/atom#6816] opened 2015-05-15 20:45 UTC
under OSX 10.10.3 atom build 0.199.0 if you close all windows then hit atom->preferences the preferences windows does not come up. You have to do it twice.

If using keyboard shortcuts you must hit command+, two times in order to actually get the presences window.

Expected behavior: hit it once and the preferences window comes up. If no windows are currently open then it should not only open a window, but then automatically open preferences.

**Comment by mnquintana** [comment] 2015-05-15 20:47
Thanks for the report! This is a duplicate of https://github.com/atom/settings-view/issues/503 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-15 20:47 UTC
