### ISSUE TITLE
Font-family name field in the settings (unnecessary quote mark)

### ISSUE THREAD

**Issue by danilopeixoto5** [atom/atom#11213] opened 2016-03-20 00:35 UTC
### Description

Problem to set the font-family in the settings.

### Steps to Reproduce

1. Open settings.
2. Scroll down until font-family setting.
3. Try entering the name. (e.g. Meslo, "Meslo")
4. Meslo" and "Meslo work.

**Expected behavior:** Enter only the font-family name.

**Actual behavior:** It is necessary to add one quote mark (") after font-family name to work.

### Versions
Atom 1.6.0
Windows 10

**Comment by PombaM** [comment] 2016-03-21 03:24
+1

**Comment by lee-dohm** [comment] 2016-03-21 05:36
It's not necessary to place any quote marks for the "Font Family" setting to work, even for a font with spaces in the name. If the name of the font is `Meslo` ... then simply `Meslo` should be sufficient in the field.

**Comment by danilopeixoto5** [comment] 2016-03-30 04:09
`Meslo` don't work. Maybe it's a specific problem of Meslo font-family.

**Comment by lee-dohm** [comment] 2016-03-30 06:55
Do you have a link to where I can find Meslo to reproduce this?

**Comment by damieng** [comment] 2016-04-02 07:57
I downloaded Meslo from https://github.com/andreberg/Meslo-Font/releases/tag/v1.2.1 and installed the Meslo LG M Regular font.  Required I set the font as 'Meslo LG M' (without quotes) as that is the font-name - worked fine.

**Comment by Ben3eeE** [comment] 2016-04-08 07:20
I downloaded the same font as @damieng linked and tested with Meslo LG L Regular. I can't get it to work with Meslo" as the bug report suggests. Took some screenshots of my testing and findings.

Default no font set:
![no font family name fresh install before restart](https://cloud.githubusercontent.com/assets/1058982/14376369/495709ee-fd69-11e5-9856-18e424e8a9e2.PNG)

After installing font - before restarting atom:
Setting Meslo LG L:
![meslo lg l fresh install before restart](https://cloud.githubusercontent.com/assets/1058982/14376376/59d464e2-fd69-11e5-8439-f7f6b68d5226.PNG)
Setting random text:
![random text fresh install before restart](https://cloud.githubusercontent.com/assets/1058982/14376378/5fe1e652-fd69-11e5-8e7e-011b8c7f5d25.PNG)

After installing font - after restarting atom:
Meslo LG L now works:
![meslo lg l after restart](https://cloud.githubusercontent.com/assets/1058982/14376393/74dea70c-fd69-11e5-9f26-71c66acc1eb7.PNG)
Random text is same weird font:
![random text after restart](https://cloud.githubusercontent.com/assets/1058982/14376400/827c6890-fd69-11e5-87d0-df27fc3f1adb.PNG)

Why is fail font different from default font?

Setting single quote after font-family name as this bug report suggests has another issue though, it affects line height and sets the font back to default with no font family set. Which seems like a different issue but maybe this has people confused?
Only Meslo big line height shows fail font:
![just meslo font family before restart](https://cloud.githubusercontent.com/assets/1058982/14376480/140ba85c-fd6a-11e5-9469-0d2fd2e73b84.PNG)
Setting it to Meslo" changes font to default font with empty font family name and clears line height to default value:
![meslo with quote font family before restart](https://cloud.githubusercontent.com/assets/1058982/14376489/27b06dd4-fd6a-11e5-8d8a-ec670d8612fe.PNG)

**Comment by damieng** [comment] 2016-04-11 17:48
Closing bug as 23 days since opened and nobody can repro. Please re-open if you have repro steps.

**Closed by damieng** 2016-04-11 17:48 UTC
Labels: more-information-needed, needs-reproduction
