### ISSUE TITLE
Opening a directory on startup doesn't restore the project state

### ISSUE THREAD

**Issue by oclbdk** [atom/atom#4913] opened 2015-01-08 10:20 UTC
I'm running on OS X.

Steps to reproduce:
1. Start Atom
2. Open a directory
3. Open a file so there's a tab open
4. Restart Atom
5. Reopen the same directory

I expect the workspace to be restored (i.e. the file should be opened) when I reopen the directory in Atom. If I open the directory a second time after startup, it does the proper thing (but then I have two workspaces open that are backed by the same directory/project).

**Comment by 50Wliu** [comment] 2015-01-08 18:21
Duplicate of #3406.

**Comment by kevinsawicki** [comment] 2015-01-08 18:22
Thanks @50Wliu

**Closed by kevinsawicki** 2015-01-08 18:22 UTC
