### ISSUE TITLE
Failed to load the autocomplete-haxe package

### ISSUE THREAD

**Issue by workroomprds** [atom/atom#9014] opened 2015-10-01 09:37 UTC
Error thrown on starting Atom
Installed packages are up to date

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the autocomplete-haxe package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:10:3
    at Object.<anonymous> (<anonymous>:10:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12,
    "fontFamily": "Monaco"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autocomplete-haxe, v0.2.0
flow, v0.4.3
haxe, v0.8.7
language-actionscript, v0.2.0
language-actionscript3, v0.3.0
language-haxe, v0.3.0
linter, v1.7.2
linter-flexpmd, v0.1.9

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-10-01 12:13
Duplicate of HaxeIDE/atom-autocomplete-haxe#10, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-01 12:13 UTC
