### ISSUE TITLE
When closing tab -- Cmd-D for Don't Save does not work (not keyboardable)

### ISSUE THREAD

**Issue by shacker** [atom/atom#13028] opened 2016-10-19 18:26 UTC
On Mac OS, when closing a window or tab and seeing the attached dialog, standard behavior is that Cmd-D can be used as an equivalent of clicking Don't Save. Alternatively, one should be able to use the Tab key to tab to a selection such as Don't Save. However, this dialog in recent Atom builds doesn't respond to Cmd-D or Tab, and forces mouse use.

<img width="472" alt="screenshot 2016-10-19 11 22 31" src="https://cloud.githubusercontent.com/assets/102694/19531926/5d30d904-95ee-11e6-9365-8a09950107eb.png">

**Comment by Ben3eeE** [comment] 2016-10-19 19:13
This is a duplicate of https://github.com/atom/atom/issues/12277. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-19 19:13 UTC
