### ISSUE TITLE
config file gets sorted/reversed.

### ISSUE THREAD

**Issue by kirjatoukka** [atom/atom#8798] opened 2015-09-15 17:20 UTC
At launch, it appears that the `config.cson` is sorted in reverse-alphabetical order, by section. Launching the settings view then causes `config.cson` to be re-sorted in alphabetical order. (However, in some cases I think these have happened the other way around.)

This does not occur on a clean installation, nor with my everyday config with a variety of plugins; however it does occur when `linter` (and only `linter`) is installed and enabled. The linter developers have said this must be an atom issue, see atom-community/linter#883.

This is on Mac OS X 10.10.5 with Atom 1.0.11.

Example config:

```
"*":
  "exception-reporting":
    userId: "d73cea11-7484-691d-3884-7da39d96dd04"
  welcome:
    showOnStartup: false
  editor:
    fontFamily: "Source Code Pro"
    fontSize: 12
    invisibles: {}
  core: {}
".python.source":
  editor:
    tabType: "soft"
    tabLength: 4
".ruby.source":
  editor:
    tabType: "soft"
    tabLength: 2
```

Symptom is that the ".python.source" and ".ruby.source" sections will swap around.

**Comment by zargony** [comment] 2016-01-30 01:06
Same issue here. It's a bit annoying since I keep config.cson in a git repo which sometimes gets dirty because of this.

**Comment by lee-dohm** [comment] 2016-02-01 23:25
This was definitely the case with earlier versions of Atom. Recent versions (like v1.4.x and up) have been pretty good about maintaining a consistent sort order. Can either of you reproduce this issue on the latest stable release?

**Comment by Ben3eeE** [comment] 2016-12-12 15:00
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8798#issuecomment-178252380. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2016-12-12 15:00 UTC
Labels: more-information-needed, needs-reproduction
