### ISSUE TITLE
Atom not saving files (sometimes after an initial save works)

### ISSUE THREAD

**Issue by guillaume-chevalier** [atom/atom#18620] opened 2018-12-26 09:14 UTC
Bump. This issue should NOT be closed: https://github.com/atom/atom/issues/18114

It's been months. I tried to reinstall Atom and it still happens. I tried to delete Atom's `~` home cache folder too, and more.

**Comment by wohlben** [comment] 2018-12-26 14:34
I said it in the linked issue as well, but i guess i can confirm it here as well.
My current host os is fedora 28, but i also encountered the bug at work -- which is a windows installation.

removing ~/.atom entirely doesnt help
starting with --save doesnt help

as github is a core package, downgrading it alone is simply impossible.
downgrading the whole atom installation is, however, possible ... but doesn't seem to help either.
for reference: I went back to 1.29.0 which had github  0.17.3 embedded

sadly, using the original git package isn't possible anymore, now that the silly and entirely useless github integration has been added to it...

anyway. checking if the bug got triggered is easy as well: just open the github panel ctrl-shift-8 or crl-shift-P and search for "Toggle Github Tab". If its a Spinner, you'll have to restart and might lose everything that hasn't been saved yet.

**Comment by rsese** [comment] 2018-12-27 18:58
@guillaume-chevalier - that was issue was closed because the issue author didn't reply back to questions.  From the comments, it also looks like though people may see the same result where there's a problem saving, there were different causes so should be separate issues (at least for now, if they happen to have the same root cause we can always close in favor of another issue).

Please edit the issue body to use the issue template and we can go from there.

@wohlben @inmysocks - if you both have narrowed things down to the GitHub package, please open an issue in https://github.com/atom/github.  From @guillaume-chevalier's comments, it doesn't seem like there's mention of the GitHub package so let's keep things separate for now.

**Comment by guillaume-chevalier** [comment] 2018-12-27 21:10
@rsese I have not installed more packages, I should only have the default packages that comes with a new Atom installation - unless all my previous packages were kept between uninstalling and reinstalling, which I doubt.

**Comment by guillaume-chevalier** [comment] 2018-12-27 21:15
> "as github is a core package, downgrading it alone is simply impossible."

Interesting. I'll try to do your "unshare" fix at some point. 

Also note: when I start Atom, it asks me for my sudo password a few times in a row (sometimes 2 or 3 times), so I close those pop-ups windows. Weird.

**Comment by inmysocks** [comment] 2018-12-27 21:39
I am a bit confused by all of these fixes. You can disable the package like any other package in the packages part of the settings, search for GitHub and click on disable. That was enough to fix it for me.

**Comment by rsese** [comment] 2018-12-28 17:57
> I have not installed more packages, I should only have the default packages that comes with a new Atom installation - unless all my previous packages were kept between uninstalling and reinstalling, which I doubt.

Your packages are installed to your Atom home directory so if you didn't remove that directory, your community packages will still be there.  But as long as you tested in safe mode that's ok since safe mode runs Atom with all community packages disabled.

> Also note: when I start Atom, it asks me for my sudo password a few times in a row (sometimes 2 or 3 times), so I close those pop-ups windows. Weird.

Hmm, did you ever start Atom with `sudo`?  That can mess up permissions (e.g. see https://github.com/atom/tree-view/issues/1256#issuecomment-395273510).  Not sure if that's related to the file saving problem you're having.

> I am a bit confused by all of these fixes. You can disable the package like any other package in the packages part of the settings, search for GitHub and click on disable. That was enough to fix it for me.

Yes, if the problem is related to the GitHub package, this is something you can try @guillaume-chevalier if you haven't already.  Like I mentioned above, people mentioned different things in the other issue, there wasn't one thing that got people past the problem.

And since for some folks this looks related to the GitHub package, reporting this in https://github.com/atom/github would be helpful.

Also @guillaume-chevalier, please edit the issue body to fill out the issue template, it's helpful to know all those details.

**Comment by wohlben** [comment] 2018-12-29 11:47
> I am a bit confused by all of these fixes. You can disable the package like any other package in the packages part of the settings, search for GitHub and click on disable. That was enough to fix it for me.

That is a valid option if you don't need the git integration.
I personally adore that panel on the right which highlights every modified file and opens a diff between the current and the committed version on click.

that panel and the vim package are the primary reason why i keep going back to atom, despite owning a JetBrains All Products Licence.

**Closed** 2019-01-25 18:32 UTC
Labels: more-information-needed
