### ISSUE TITLE
Each atom update adds a new item to "Open with"

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#1720] opened 2014-03-07 00:22 UTC
support/6be6d1eaa44911e38bd5c0467822a465?page=1

![screen shot 2014-03-06 at 4 21 49 pm](https://f.cloud.github.com/assets/1476/2352623/94a2aa1e-a58e-11e3-8932-f285beded6b5.png)

**Comment by Moter8** [comment] 2015-01-12 15:03
Is this issue actually still relevant? Should probably be closed...

**Comment by benogle** [comment] 2015-01-19 19:34
Closing. If anyone still has this issue, please comment!

**Closed by benogle** 2015-01-19 19:34 UTC
Labels: bug

**Comment by MarkMurphy** [comment] 2015-06-08 12:43
I'm still having this issue 0.205.0 and 0.207.0 both appear in my "open with.." context menu.

**Comment by MarkMurphy** [comment] 2015-06-08 12:57
Rebuilding LanuchServices as documented in the link @jspahrsummers posted, fixed this issue for me.

**Comment by ukolov-k** [comment] 2015-06-23 06:20
Had this trouble 2 months ago. "rebuilding launch services" helped, but recently it started again - new entry in "open with" menu with each update. 0.204 - 0.208

**Comment by julesbravo** [comment] 2015-07-29 15:24
I just rebuilt with the following command and I'm still seeing multiple versions in "Open With".

```
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.fram ework/Support/lsregister -kill -r -domain local -domain system -domain user ; killall Dock
```

I'm seeing 1.0.3 and 1.0.2

**Comment by alceufc** [comment] 2015-08-20 14:04
I am also having this issue.

**Comment by jspizziri** [comment] 2015-09-02 17:02
+1, both my colleague and I are having this issue. @jspahrsummers posted fix did not work for me either.

**Comment by mischkl** [comment] 2015-12-02 12:07
Rebuilding launch services is a hacky workaround. Considering that I have this problem with exactly zero other applications that update themselves (Chrome, Firefox, WebStorm, ...) and considering 99% of Mac users will never figure out how to fix it, this is a pretty big deal that can't be just dismissed. I'm actually kind of shocked that this has been closed.

For reference I am using the very newest Atom and Mac OS 10.11.1

**Comment by apetrushin** [comment] 2016-01-15 01:03
Same issue.

**Comment by SugarOverflow** [comment] 2016-02-04 15:36
Same issue. I rebuilt launch services a few months ago, but it's happened again. I don't have this problem with any other applications. Running OS X El Capitan 10.11.2

<img width="344" alt="screen shot 2016-02-04 at 10 34 51 am" src="https://cloud.githubusercontent.com/assets/6685950/12819948/1638f7b8-cb2b-11e5-8313-ee2901a22ce1.png">

**Comment by alceufc** [comment] 2016-02-05 15:41
Is it possible to re-open this issue?

**Comment by DaveEveritt** [comment] 2016-02-10 20:54
This [does happen with other applications](http://apple.stackexchange.com/a/82747/169745), and there's uncertainty about whether it's an OS X or Atom bug, consensus seems to be OS X. I worked around it by adding the recommended commands to an alias to my .bash_profile so I can just do `killdups` when it happens:

`alias killdups='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"'
`

**Comment by SugarOverflow** [comment] 2016-02-11 19:54
@DaveEveritt thank you! that's useful :)

**Comment by mamezito** [comment] 2016-05-05 08:56
why its closed if the problem still extists?

**Comment by Apolotary** [comment] 2016-06-02 09:01
Can confirm, currently having 1.7.4 and 1.6.0 in the right-click menu, and one of them keeps crashing

**Comment by humanfactors** [comment] 2016-08-03 05:23
Issue still exists for me at 1.9.x as well

**Comment by zaridan** [comment] 2016-08-18 23:32
Found this issue while looking for a solution to this annoyance.  Confirmed still an issue.

**Comment by humanfactors** [comment] 2016-08-21 06:03
Still affecting Atom 1.99. Please can someone work out what is causing this?

**Comment by jakey-wan-kenobi** [comment] 2016-09-21 01:59
Yup, same issue here. Super annoying.

**Comment by vacantgeologist** [comment] 2016-10-21 04:45
Same here...

**Comment by rfreitas** [comment] 2016-11-02 22:31
Still a problem

**Comment by caioiglesias** [comment] 2016-11-08 15:32
`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user ; killall Dock`

[source](https://www.tekrevue.com/tip/rebuild-launchservices-fix-duplicate-entries-os-xs-open-menu/)

**Comment by yobyot** [comment] 2016-11-10 15:51
Yup, same problem here. Annoying enough to have made me try (for just about 30 seconds) Visual Studio Code.
![2016-11-10_10-50-10](https://cloud.githubusercontent.com/assets/14332263/20183536/a9df4f96-a733-11e6-9f88-d26d84e56b66.png)

**Comment by jwfehr** [comment] 2016-11-17 20:28
I am having this issue with atom 1.12.1 1.12.2 and 1.12.3 however I have the ability to open the different versions. ex. I currently have 1.12.1 and 1.12.3 running at the same time. Yet when I search for atom in finder I only get one executable. Any Ideas?

**Comment by chengguangnan** [comment] 2016-11-22 04:16
I have 1.12.4 installed, but the menu is suggesting:

- 1.12.5
- 1.12.4

**Comment by sergiouceda** [comment] 2016-11-28 22:24
I had the same issue. I uninstalled/reinstalled and it got fixed. I think it could also be related with having the old version icon pinned on the dock. I hope it helps.

**Comment by galvax** [comment] 2016-12-02 02:10
@sergiouceda that solved it for me after reading your comment. Removed, the icon from the dock and everything fixed itself 🎉

**Comment by MarkMurphy** [comment] 2016-12-05 14:26
Confirmed. Removing the icon from the dock also solved it for me. Obviously I don't want to have to do this every time so hopefully this discovery helps someone address this problem.

**Comment by wbednarski** [comment] 2016-12-18 17:29
This issue just showed up for me. I have version `1.12.7`. However, when I use the context menu in GitHub for Mac it opens separate Atom version `1.12.5`. I uninstalled Atom (removing all library files), and the issue persists. I've also tried to upgrade that strange phantom Atom that is seen only by GitHub Desktop but it fails to update, after the restart, it is still old version `1.12.5`.

**Comment by theflofly** [comment] 2016-12-20 11:29
Same problem whereas as don't have the icon pinned in the dock.

**Comment by oxbits** [comment] 2017-01-15 07:20
If you are having this issue, temporary work around...

In terminal:

/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user

Then Relaunch Finder - hold down alt/option key and right click the Finder icon in the Dock > Relaunch

It worked for me.

:-D

From:
http://www.hongkiat.com/blog/mac-remove-duplicate-right-click-menus/

**Comment by mPanasiewicz** [comment] 2017-01-23 21:15
THX @oxbits It worked for me.

**Comment by rameshvr** [comment] 2017-02-06 15:19
emptied the trash, it solved for me. the older version stays in your mac trash. try deleting that.

**Comment by stephendavidsmith** [comment] 2017-02-23 01:58
Use @oxbits solution with a bit of caution - it didn't work for me, but in my case it did mess up some of my file associations

**Comment by oxbits** [comment] 2017-02-23 03:08
@stephendavidsmith yeah, seemed good at first, but now it does some sort of "search" to determine file associations, and that takes a little longer than it seems it should

**Comment by blakeperdue** [comment] 2017-04-24 05:59
Consistently happens to me over time. I also have zero other apps that have this issue. I realize it may be a Mac issue but would love if Atom could figure out a workaround to this issue :)

**Comment by ToddMurphy92** [comment] 2017-05-08 23:25
In the same boat as @blakeperdue

**Comment by blakeperdue** [comment] 2017-05-09 02:39
I actually noticed this happening with one other app: Skitch. That would imply it is a MacOS issue. However, there's clearly something different in how apps like Skitch and Atom are doing versioning with the OS. Other apps do not show a version number in that Finder context menu, such as Google Chrome, Safari, Adobe CS, VLC.

But, then there are many apps that do list the version number: Affinity Designer, Sketch, Skitch, iBooks, and even xCode! So, I'm at a loss. 

I'd love for an easier solution than wiping all the Finder data around apps. It's taking a sledgehammer to the problem. Is there not a more simple way of taking a scalpel and cutting out the old Atom versions from the OS?

**Comment by david-ciamberlano** [comment] 2017-05-21 23:31
I found that after an update, older versions of the App remain in the "~/Library/Caches/com.github.atom.ShipIt/" folder.
Deleting them seems to solve the problem...

**Comment by blakeperdue** [comment] 2017-05-22 02:37
@david-ciamberlano Wow, awesome find. That worked for me!!

**Comment by blakeperdue** [comment] 2017-07-26 21:16
So, deleting the contents of `~/Library/Caches/com.github.atom.ShipIt` does fix the Atom issue. But, I tried that with other apps (like Skitch) and it did not work. The ShipIt suffix I'm guessing is an Electron distribution thing as other apps have a similar folder. 

So, I'm guessing this fix will work for Electron-based apps, but not for other apps like Skitch 😢

**Comment by matthewpoer** [comment] 2017-09-11 13:08
> rameshvr commented on Feb 6
> emptied the trash, it solved for me. the older version stays in your mac trash. try deleting that

That's dumb. Totally worked.
