### ISSUE TITLE
Opened projects won't be back at launch

### ISSUE THREAD

**Issue by pierretusseau** [atom/atom#6549] opened 2015-04-28 10:08 UTC
Hello,

I'm sorry I don't have much idea how to report the problem, and I never done that before, so I'll try my best.

I learned from this issue tracker that "Opened projects" was recently added to Atom. While it requires obviously some technical precisions (no command line option must be used), the exemple is given of a shortcut in a OSX Dock, but I'm on windows... So I tried to delete anything unnecessary in the windows atom short cut (there were like ../update.exe -open atom.exe) so I just let ../atom.exe

It doesn't seem to work.... at all.

I don't have many pluggins only essentials (I guess), here is the list : atom-alignment, atom-color-highlight, autocomplete-plus, emmet, file-icons, linter, minimap, Sublime-style-columns-selection.

Should I disable any pluggin to test ? And reactivate one by one. Or is this a common known problem ?
I've seen the update is fairly recent, so I may be the first to get the problem.

I hope this'll help you, I'm open to any question if you need anything more

Windows 8.1(Pro)
Atom 0.194

**Comment by 50Wliu** [comment] 2015-04-28 12:03
Duplicate of #6466, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-28 12:03 UTC
