### ISSUE TITLE
Error when I put my cursor to the text

### ISSUE THREAD

**Issue by thanhmssl10** [atom/atom#6413] opened 2015-04-17 05:16 UTC
I use Atom 0.192 and i write vietnamese text (markdown) with UTF-8, when i put my cursor to the text line, It not true,It deviated from a word which i want

**Comment by izuzak** [comment] 2015-04-17 12:20
@thanhmssl10 I'm not sure I understand what you mean by "when i put my cursor to the text line, It not true,It deviated from a word which i want". Could you perhaps record a short GIF which demonstrates the problem and post it here in a comment? Thanks

**Comment by izuzak** [comment] 2015-04-17 12:21
Also, can you let us know which OS you're using and if you can reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by thanhmssl10** [comment] 2015-04-17 14:22
I use Windows 7, 64bit, laptop asusp450l, i use a supporter to type Vietnamese is Unikey 
This error I get when i write a doccument of my project on github by markdown
http://unikey.vn
http://sourceforge.net/projects/unikey/
If you can't know my error, i can make a gif, but I think you can know what I mean with this picture.
![error_atom_markdown](https://cloud.githubusercontent.com/assets/10551242/7203772/54200e42-e547-11e4-85b7-a91b1ecdc8ec.png)

**Comment by mark-hahn** [comment] 2015-04-17 21:48
Is this utf-16?  You might try utf-8.  (Wild guess).

**Comment by thanhmssl10** [comment] 2015-04-18 04:41
![utf8](https://cloud.githubusercontent.com/assets/10551242/7214032/bee475a6-e5bf-11e4-8685-d89405a0f79a.png)
I don't think so because, i choose UTF - 8 like this picture

**Comment by izuzak** [comment] 2015-04-19 15:54
Thanks for clarifying, @thanhmssl10. I think this is a duplicate of https://github.com/atom/atom/issues/1849, so please subscribe to that issue for update. If you think this isn't a duplicate of that issue -- please provide more details.

**Closed by izuzak** 2015-04-19 15:54 UTC
Labels: more-information-needed
