### ISSUE TITLE
Uncaught BufferedProcessError: Failed to spawn command apm.cmd

### ISSUE THREAD

**Issue by stebiger** [atom/atom#8199] opened 2015-08-03 06:02 UTC
Hi,

I tried to execute the cmd "Update Package Dependencies: Update" from cmd-shell (ctrl+shift+P)

and got following error:

```
C:\Users\sb\.atom\packages\keyboard-localization\lib\keymap-loader.coffee:41 keyboard-localization Keymap loaded "C:\Users\sb\.atom\packages\keyboard-localization\lib\keymaps\de_DE.json"
index.js:56 Window load time: 1134ms
C:\Users\sb\AppData\Local\atom\app-1.0.3\resources\app.asar\src\buffered-process.js:260 Uncaught BufferedProcessError: Failed to spawn command `C:\Users\sb\AppData\Local\atom\app-1.0.3\resources\app\apm\bin\apm.cmd`. Make sure `C:\Users\sb\AppData\Local\atom\app-1.0.3\resources\app\apm\bin\apm.cmd` is installed and on your PATH
```

**Comment by izuzak** [comment] 2015-08-11 15:12
This seems to be a duplicate of https://github.com/atom/atom/issues/5464 -- closing in favor of that.

**Closed by izuzak** 2015-08-11 15:12 UTC
Labels: uncaught-exception
