### ISSUE TITLE
Atom Editor is shaking when writing

### ISSUE THREAD

**Issue by giannissc** [atom/atom#15786] opened 2017-10-01 18:30 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Fill editor with text so that the cursor is at the bottom of the screen when writing
2. Press enter for a new line and start writing
3. The whole editor window will start shaking up and down
4. Does not do it consistently (sometimes it will shake some other times it wont just press enter again and keep writing until it occurs)

**Expected behavior:** [What you expect to happen]
No shaking whatsoever as it is annoying

**Actual behavior:** [What actually happens]
Shaking (Can sent a video if you want)

**Reproduces how often:** [What percentage of the time does it reproduce?]
When in safe mode at random.
When not all the time the cursor reaches the bottom of the screen. Even if there is text beneath the cursor in the document it still happens

### Versions
atom-beta 1.21

**Comment by Ben3eeE** [comment] 2017-10-02 06:07
> Can sent a video if you want

It would be great to have a video of reproducing this behavior in safe mode, thank you :bowing_man:

**Comment by giannissc** [comment] 2017-10-02 09:18
Could not upload video directly so i will zip it and attach it. 
[atom-shaking-editor.zip](https://github.com/atom/atom/files/1348402/atom-shaking-editor.zip)

**Comment by gaibo** [comment] 2017-10-03 02:06
Hey I actually have the same problem! Really glad I saw this on front page.

Some more details from me:
- **It only happens on every 5th line of code.** So if the final line of code is line 25 or 30 or 35 etc., screen will shake no matter what line you're typing on. It's very subtle, and I thought I was going crazy at first, because this is happening on my new laptop. Sager Windows 10 64-bit Nvidia GTX 1050 Ti if that's useful at all (it looks like graphics driver flickering).

**Comment by Gregwar** [comment] 2017-10-10 21:40
I can confirm this happened to me too, not sure what cause this though

**Comment by EricThomson** [comment] 2017-10-11 02:17
Is happening to me in Ubuntu 16, so safe mode not required. Is when I am in bottom 1/4 of window.

**Comment by EricThomson** [comment] 2017-10-17 05:04
Here is video of shaking...Ubuntu. This is pretty much my standard use case. The desktop capture software I used doesn't do it 100% justice the jiggling is much higher frequency.
https://imgur.com/a/4P4XX

**Comment by kshitijgorde** [comment] 2018-01-18 15:33
This is happening to me as well. Is there a fix for this yet?

**Comment by 50Wliu** [comment] 2018-01-19 16:21
@giannissc I'm having trouble opening your video on Windows - it doesn't play for me.

For everyone else experiencing this issue, have you been able to reproduce it when starting Atom with `atom --safe` as well?

**Comment by H8to** [comment] 2018-02-02 12:16
@50Wliu 
Also occurring in safe mode:

(had to type a bit until it appears in the gif)
![The issue after typing some a's](https://media.giphy.com/media/26DNeM4kdNy25Ezrq/giphy.gif)

**Comment by svetoslav80** [comment] 2018-02-02 13:40
I also confirm this. It's reproducible in safe mode too. Your whole window should be full of text, and you should write on the last bottom line. Note that it doesn't happen every time, so try to write at least a few lines on the bottom. I'm running Atom on Ubuntu 17.10.

**Comment by Ben3eeE** [comment] 2018-02-02 14:27
I am unable to reproduce this when testing. Can you reproduce with a public document and record the entire Atom window? For example does it happen in https://github.com/atom/atom/blob/master/CONTRIBUTING.md?

**Comment by Ben3eeE** [comment] 2018-02-02 14:28
Additionally do you have anything added to your personal stylesheet?

**Comment by svetoslav80** [comment] 2018-02-03 17:10
I've attached a zip file (mp4 inside). The shaking is most noticeable at the end of the video, on line 506. I have this code in styles.less :
`.scrollbars-visible-always {
    /deep/ ::-webkit-scrollbar {
        width: 20px;
        height: 20px;
    }
}`
but atom was shaky even when I commented and saved it.
[atom.zip](https://github.com/atom/atom/files/1691969/atom.zip)

**Comment by akutz** [comment] 2018-02-08 18:08
It is happening on my system as well, I'm using Elementary OS Loki on a Dell Precision 5520 with Intel and nVidia graphics. I'm using Atom Dark as my UI theme and Monokai Dark as my syntax theme.

**Comment by akutz** [comment] 2018-02-08 18:16
FWIW, the behavior appears to have stopped after I changed my syntax theme to `Atom Dark`.

**Comment by kshitijgorde** [comment] 2018-02-14 01:30
Changing syntax theme to ```Atom Dark``` didn't fix the issue for me!.

**Comment by peterzhu2118** [comment] 2018-02-26 23:27
![ezgif-5-97a9bcbab5](https://user-images.githubusercontent.com/15860699/36631497-098c97d8-1947-11e8-96f5-ebbe6c9a5311.gif)

This occurs all time for me on my laptop. Would be nice if it is fixed ASAP because it drives me crazy to code on that machine.

OS: Windows 10 Home
CPU: Intel Core i7-4500U
GPU: Intel Graphics 4400

Versions:
```
C:\Users\Peter>atom --version

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

C:\Users\Peter>apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.11
git 2.9.0.windows.1
visual studio 2015
```

**Comment by jrial** [comment] 2018-02-27 10:24
As a temporary workaround for those experiencing this issue: does it go away when you enable Scroll Past End in Settings => Editor? At the very least, it should allow you to scroll down until the last line of the file is above the lower quarter of the screen, where the shaking is triggered.

**Comment by H8to** [comment] 2018-02-27 13:18
@jrial The workaround works as described. As soon as you scroll a bit further the shaking disappears. I hope the issues gets identified somehow :|

**Comment by Ben3eeE** [comment] 2018-02-28 08:38
I investigated this issue some. I think what happens is that we get into a state where the content height is rounded up to a physical pixel boundary but the height of the dummy scrollbar is not.

This means that we can't scroll the full content of the file so `maxScrollTop` is slightly larger than the current `scrollTop` even when the file has been scrolled to the bottom. When making edits Atom automatically scrolls so the edit you made is visible and this is based on `maxScrollTop` which is larger than the vertical scrollbar allows causing it to scroll back.

I pushed a branch with a potential fix https://github.com/atom/atom/commit/e6bfa082dcf56c7217af34af35789dbba3ee0587 and will open a PR later today after I can test it out, verify my thoughts and record some gifs.

refs: https://github.com/atom/atom/pull/15372

**Comment by TheSimple** [comment] 2018-03-04 15:40
Running the latest version of Atom on Windows as of 4th March, 18. I am also affected by this issue. The way the screen wiggles is very annoying. Any fix would be greatly appreciated.
Some points to notice:
1. It occurs when screen is filled with text irrespective of where the cursor is.
2. Sometimes it occurs other times not.
3. Hitting enter fixes it some of the times.
PLEASE PLEASE RELEASE A BUG FIX.
THE WORKAROUND WORKS BUT IT'S JUST A WORKAROUND.

**Closed** 2018-03-06 10:28 UTC
Labels: bug, editor-rendering, triaged
