### ISSUE TITLE
Incorrect matching element underlining

### ISSUE THREAD

**Issue by theblindprophet** [atom/atom#16427] opened 2017-12-21 23:40 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Matching element tags underlined incorrectly.

### Steps to Reproduce

Write such HTML code:

```
<div class="my-scans__filters">
    <div class="my-scans__filters-quick-dates">
        <div class="my-scans__filters-quick-date my-scans__filters-quick-date--first"
            ng-click="vm.setFilterDatesQuick('today')">
            <span>Today</span>
        </div>
        <div class="my-scans__filters-quick-date"
            ng-click="vm.setFilterDatesQuick('week')">
            <span>This week</span>
        </div>
        <div class="my-scans__filters-quick-date my-scans__filters-quick-date--last"
            ng-click="vm.setFilterDatesQuick('month')">
            <span>This month</span>
        </div>
    </div>
    <div class="my-scans__filters-apply-dates">
        <div class="my-scans__filters-apply">
            <span>Apply</span>
        </div>
    </div>
</div>
```

In this example if I place the cursor on the first `div` then the closing `div` on line 10 is highlighted instead of line 21. This markup displays correctly and is valid.

### Versions

**1.23.1**

Here is a picture of the incorrect underlining:

<img width="693" alt="screen shot 2017-12-21 at 6 29 46 pm" src="https://user-images.githubusercontent.com/7903413/34279252-ca1bbc6a-e67d-11e7-96da-1b92aabeca07.png">

**Comment by 50Wliu** [comment] 2017-12-21 23:41
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/bracket-matcher#333. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-12-21 23:41 UTC
