### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'

### ISSUE THREAD

**Issue by crazyR14** [atom/atom#6623] opened 2015-05-03 15:37 UTC
[Enter steps to reproduce below:]

1. ... right click the project folders list

**Atom Version**: 0.196.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\user\AppData\Local\atom\app-0.196.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\user\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:30.4.0 pane:reopen-closed-item (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "feedback",
      "welcome"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
language-lua, v0.9.2
linter, v0.12.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-03 18:12
Duplicate of #6548, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-03 18:12 UTC
