### ISSUE TITLE
Search input box should trim carriage return

### ISSUE THREAD

**Issue by bombless** [atom/atom#5644] opened 2015-02-19 22:09 UTC
I'm new for Atom so I don't have a clue how to fix this.

On Windows, I copy some text that have a trailing carriage return from other application, such as excel, notepad, then try to search the opening doc in Atom. Then I was surprising that there's no match. Because you cannot see the trailing carriage return in any form on the editor, you may not aware the fact that you are actually searching a 2-lines text.

The search input box seems to be a single-line one, so I guess we may need to trim CRs and LFs there.

Atom Version `0.181.0 2015/2/19 上午5:56:33`

**Comment by kevinsawicki** [comment] 2015-02-19 22:10
I believe this is a duplicate of https://github.com/atom/atom/issues/4400

**Closed by kevinsawicki** 2015-02-19 22:10 UTC

**Comment by bombless** [comment] 2015-02-19 22:19
God, there _is_ a scroll bar there. Very funny.
