### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/rishisanganee/Downloads/Atom.app'

### ISSUE THREAD

**Issue by MrRishi** [atom/atom#12138] opened 2016-07-11 09:15 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/rishisanganee/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/rishisanganee/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:314:24)
    at toRealPath (module.js:113:13)
    at Function.Module._findPath (module.js:153:20)
    at Module._resolveFilename (module.js:336:25)
    at Function.Module._resolveFilename (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/rishisanganee/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
```

### Commands

```
     -8:56.6.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  6x -5:21.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:35.1.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -4:34.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:43.5.0 core:paste (atom-text-editor.editor.is-focused)
 24x -3:41.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:33.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:30.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2016-07-12 06:50
This is generally caused by launching Atom from the Downloads folder and then moving it to the Applications folder when it is still running. Close Atom completely, move the application, and launch Atom from the new location. Things should work fine.

**Closed by lee-dohm** 2016-07-12 06:50 UTC
