### ISSUE TITLE
Crash when quitting from two full-screen windows on Mac

### ISSUE THREAD

**Issue by giacecco** [atom/atom#10000] opened 2015-12-10 12:01 UTC
This is with Atom 1.3.0 on MacOS 10.11.2.

To reproduce:
- open a few files from a folder; it will create one Atom window
- open a few other files from another folder; it will create another Atom window
- make both windows full screen
- close all files in one of the windows; here you will note an issue already, that is that that window remains open; I would expect it to close itself, leaving the other window open only
- quit by doing CMD-Q, and Atom will crash

**Comment by lee-dohm** [comment] 2015-12-11 02:45
This is almost assuredly a duplicate of https://github.com/atom/atom/issues/9584. Please install the latest Beta version and see if you can reproduce the issue.

**Comment by Moeriki** [comment] 2015-12-11 09:47
Issue #10000 🎉

**Comment by giacecco** [comment] 2015-12-11 09:56
@lee-dohm #9584 is likely linked but different, my crash happens when trying to quit (CMD-Q), not  when closing the window (CMD-SHIFT-W), I would not get for granted that solving one solves the other. @amytruong why do you say it needs reproduction? The instructions are insufficient?

**Comment by lee-dohm** [comment] 2015-12-11 17:29
For guidance on labels, please see the [CONTRIBUTING document](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#type-of-issue-and-issue-state). I've never been able to reliably reproduce any of these crashes.

Did you try reproducing the issue on the latest beta?

**Comment by DarthSim** [comment] 2015-12-16 11:34
Have the same issue. Can't reproduce it on 1.4.0-beta1.

**Comment by 50Wliu** [comment] 2015-12-16 17:01
I'm closing this as a duplicate of #9584 since @DarthSim reported that 1.4.0-beta1 fixed his crashes.

@giacecco if 1.4.0 doesn't fix it for you please comment here and we'll re-open this.

**Closed by 50Wliu** 2015-12-16 17:01 UTC
Labels: needs-reproduction
