### ISSUE TITLE
Changing tabs using mouse steals focus from text editor

### ISSUE THREAD

**Issue by nurtext** [atom/atom#6901] opened 2015-05-22 08:20 UTC
Platform: OS X 10.10
Atom Version: 0.201.0

Description:
Changing tabs using the mouse button (clicking on them) steals the focus from the editor window and requires another click into the text to continue writing. 

Expected behavior:
Text editor regains focus after tabs are switched.

Note:
Changing tabs using keyboard shortcuts works and won't steal the focus

**Comment by izuzak** [comment] 2015-05-22 08:22
Thanks for the report -- looks like a duplicate of https://github.com/atom/atom/issues/6662. :point_left:

**Closed by izuzak** 2015-05-22 08:22 UTC
