### ISSUE TITLE
Splitting tree-view in dock creates empty pane in docks

### ISSUE THREAD

**Issue by ungb** [atom/atom#14201] opened 2017-04-13 21:05 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Splitting tree-view in dock splits empty pane

### Steps to Reproduce

1.  Open a project in atom-beta
2. on the tree-view, split the item, left, right, top, and bottom

**Expected behavior:** [What you expect to happen]
It should probably no-op as it is splitting empty items  

**Actual behavior:** [What actually happens]
it creates a bunch of empty panes in the dock.
![image](https://cloud.githubusercontent.com/assets/5624870/25024292/2f2646f4-2052-11e7-8a66-954c969534bb.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 
### Versions
Atom    : 1.17.0-beta1
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment] 2017-04-14 03:34
I actually get `Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]` when attempting to split, which then totally explodes my Atom instance.  Had to clear window state to get it to start again.

**Comment by ungb** [comment] 2017-04-14 03:38
@50Wliu, glad it's not just me.  I was going to comment on the same thing.  I saw this too, but I couldn't consistently repro it.  

There's a few bugs related to that issue. like this one: https://github.com/atom/tabs/issues/234 the one error message linked to

**Comment by Ben3eeE** [comment] 2017-09-07 19:34
> I actually get Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object] when attempting to split, which then totally explodes my Atom instance. Had to clear window state to get it to start again.

This happens if you right click on the `tab` of the `tree-view` and split.

**Comment by as-cii** [comment] 2018-01-15 09:21
Thanks for the report, @ungb. I wanted to start looking into this but unfortunately I am unable to reproduce the issue:

* Right-clicking on a tab and splitting has no effect.
* Invoking `pane:split-right-and-copy-active-item` creates a new pane, but does not duplicate the tree-view item. This is consistent with what happens when you attempt to split a non-copyable item in the center dock. Maybe it could be slightly confusing but it does not seem to be a bug.
* Invoking `pane:split-right` correctly creates a new pane.

None of the cases above triggered an exception and I could close the mistakenly opened panes quite easily. Also, I think splitting panes in docks is a quite useful behavior, as it allows to move other dock items (like the Git pane) into the same dock:

![screen shot 2018-01-15 at 10 19 53](https://user-images.githubusercontent.com/482957/34935303-b2e4efee-f9dd-11e7-86f1-20ad62249d86.png)

Given that I can't reproduce the exception and the behavior isn't necessarily confusing, I would propose to go ahead and close this. What do you think @ungb @50Wliu @Ben3eeE?

**Comment by Ben3eeE** [comment] 2018-01-15 09:40
@as-cii I can no longer reproduce the exception by following the same steps as I did before. Maybe fixed by https://github.com/atom/tabs/pull/522?

I think that we should close this.

**Comment by as-cii** [comment] 2018-01-15 12:37
Thanks for confirming, @Ben3eeE!

**Closed by as-cii** 2018-01-15 12:37 UTC
Labels: bug
