### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by AzadSadigli** [atom/atom#16811] opened 2018-02-21 20:08 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At C:\Users\Azad\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor-component.js:2290

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2279:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2272:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:400:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:278:20)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.24.0/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -8:45 core:save (input.hidden-input)
     -8:05.5.0 editor:toggle-line-comments (input.hidden-input)
     -8:04.6.0 core:save (input.hidden-input)
     -7:20.4.0 editor:newline (input.hidden-input)
     -7:20 core:paste (input.hidden-input)
     -7:19.4.0 core:save (input.hidden-input)
     -7:19.1.0 core:backspace (input.hidden-input)
     -7:18.8.0 core:save (input.hidden-input)
  3x -6:26.9.0 core:undo (input.hidden-input)
     -6:14.3.0 core:select-all (input.hidden-input)
     -6:14 core:paste (input.hidden-input)
  2x -6:01.7.0 editor:toggle-line-comments (input.hidden-input)
     -5:44.9.0 core:backspace (input.hidden-input)
     -5:44 core:save (input.hidden-input)
 41x -5:22.9.0 core:undo (input.hidden-input)
     -5:11.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-02-21 21:31
Thanks for the report!  Looks like this is a duplicate of https://github.com/atom/atom/issues/15263 and the [fix](https://github.com/atom/atom/pull/15831) will be available in an upcoming release.

**Closed by rsese** 2018-02-21 21:31 UTC
