### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.40.1\res...

### ISSUE THREAD

**Issue by Redstoneguy129** [atom/atom#20203] opened 2019-12-03 19:22 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Cameron\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:166

Error: The specified module could not be found.
\\?\C:\Users\Cameron\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:714332)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2747069)
    at get_manager (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2747171)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2747297)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:1087835)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -1:12.9.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:59.4.0 tree-view:show-current-file-in-file-manager (div.line)
```

### Non-Core Packages

```
atom-discord 2.0.2 
autocomplete-javascript 0.0.2 
autocomplete-python 1.14.1 
autocomplete-unity 0.1.3 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.35 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.0 
pigments 0.40.2 
script 3.18.1 
teletype 0.13.4 
```

**Comment by WilSnoop** [comment] 2019-12-04 14:28
@Redstoneguy129 :
Hi Cameron.

1. Please confirm if you have the file stored at the location:
`C:\Users\Cameron\AppData\Local\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node`

2.  Does this happen often or once?

3. Which layout keyboard do you use?

4. Does your situation change when you update to the current (1.41.0) version of Atom?

**Comment by sadick254** [comment] 2020-09-16 15:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-16 15:16 UTC
