### ISSUE TITLE
Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by mssever** [atom/atom#10819] opened 2016-02-15 03:37 UTC
When launching Atom, I get nothing but what appears to be a Chrome JavaScript error page.
![atom_057](https://cloud.githubusercontent.com/assets/17238705/13039235/2aa28ec8-d362-11e5-8f61-920eb6bbf178.png)
The error in question is:` Cannot find module '../build/Debug/nodegit.node'`.

I'm unfamiliar with NodeJS, but it appears to me that perhaps there may be an omission in the [build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md). It looks like I'm missing something that I need, but what is it?

v.1.6.0beta3 built from source on Ubuntu 14.04 32-bit and installed from a self-built .deb, all done according to the instructions.

**Comment by Arakaki** [comment] 2016-02-18 02:30
I got same error.
*  OS: Ubuntu 14.04 32-bit
*  Atom version: v.1.6.0beta3

**Comment by Arakaki** [comment] 2016-02-18 03:12
This is the error detail.
```
Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/local/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:15:12)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/local/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-provider.js:8:19)
    at Object.<anonymous> (/usr/local/share/atom/resources/app.asar/src/git-repository-provider.js:83:4)
    at Module._compile (/usr/local/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
```

**Comment by joshaber** [comment] 2016-02-18 21:05
Hmm very odd! What happens if you try `npm install nodegit`?

**Comment by mssever** [comment] 2016-02-19 01:01
Running `npm install nodegit` changes nothing. However, I haven't rebuilt Atom. I don't know if it's necessary to do so, but rebuilding on my machine will require about 2 hours, so I'm not anxious to do any extra work. And anyway, since nodejs is Javascript, I'm assuming it's interpreted at runtime, anyway. (I may be showing my ignorance here.)

**Comment by mssever** [comment] 2016-02-19 03:23
I rebuilt atom, but the issue persists.

**Comment by avastor** [comment] 2016-02-20 13:20
I've same problem.

**Comment by korova08** [comment] 2016-02-26 18:11
same problem with Debian testing (32 bits)

**Comment by mingjunyang** [comment] 2016-03-10 01:50
Atom    : 1.7.0-dev-ac35fec
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1


```
index.js:62 Error: Cannot find module '../build/Debug/nodegit.node'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/mingjunyang/bin/atom/Atom/resources/app.asar/node_modules/nodegit/lib/nodegit.js:17:12)
    at Module._compile (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/git-repository-async.js:25:16)
    at Module._compile (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/git-repository.js:12:24)
    at Object.<anonymous> (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/git-repository.js:428:4)
    at Module._compile (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/git-repository-provider.js:8:19)
    at Object.<anonymous> (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/git-repository-provider.js:83:4)
    at Module._compile (/home/mingjunyang/bin/atom/Atom/resources/app.asar/src/native-compile-cache.js:103:30)
```

**Comment by Arakaki** [comment] 2016-03-18 08:35
v1.5.3 works well.
But v1.6.0 and v1.7.0-beta0 still have the probrem. :crying_cat_face:

**Comment by roshimon** [comment] 2016-03-19 04:04
I have the same issue too. So what's the solution for this ?

**Comment by dvdfu** [comment] 2016-03-19 04:17
Seeing this problem as well, nothing changes when running atom using `--safe`.

* Ubuntu 15.10
* Atom 1.6.0

**Comment by roshimon** [comment] 2016-03-19 04:33
What's C++ toolchain ? Where to get that ?

**Comment by srujalsk** [comment] 2016-03-19 12:38
Me too facing this Issue post update of Atom in Ubuntu 15.10 x86

**Comment by wadsworj** [comment] 2016-03-19 16:50
I've got this issue on Ubuntu 15.10

**Comment by srujalsk** [comment] 2016-03-19 18:36
I have also tried rebuilding it from source, but still same issue i guess it is something related to packaging, but not able to understand which directory it is trying to access, if I can get hold of it then can add that module & resolve this issue.

**Comment by robertgeb** [comment] 2016-03-19 19:32
I have this problem too
Arch Linux
Rebuild don't solve.

**Comment by robertgeb** [comment] 2016-03-19 20:19
When i try run `npm install nodegit` show this error:
`node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.11.9-node-v47-linux-ia32.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/nodegit/node_modules/node-pre-gyp/lib/install.js:101:37)
node-pre-gyp ERR! stack     at emitOne (events.js:95:20)
`

**Comment by joshaber** [comment] 2016-03-20 01:50
Thanks for all the reports. Is everyone using some 32-bit Linux distro?

**Comment by mssever** [comment] 2016-03-20 02:07
I am.

**Comment by alba2020** [comment] 2016-03-20 03:49
The same problem. Mint 17.3 x32.

**Comment by jag3rm3ist3r** [comment] 2016-03-20 04:46
I have the same problem.

Ubuntu 15.10 32bit using the WebUpd8 package.

**Comment by XDTZ** [comment] 2016-03-20 04:52
Same problem as everyone above, running 32bit Ubuntu 15.10.

**Comment by srujalsk** [comment] 2016-03-20 08:44
# Revert to Version 1.5.3 for Ubuntu 15.10 x86 

I have build v1.5.3 for Atom on Ubuntu 15.10 x86 can be downloaded below

[https://onedrive.live.com/redir?resid=E6C14FDDB7D6AE69!3766&authkey=!AL8jSJiCFgbnfnA&ithint=file%2cdeb]

**Comment by loopdigga98** [comment] 2016-03-20 12:18
@srujalsk thank you so much!

**Comment by korova08** [comment] 2016-03-20 15:31
Version 1.5.3 works on Debian (32bit) too, but it would be nice to be able to successfully build the latest version and/or to understand what's wrong with it.

**Comment by srujalsk** [comment] 2016-03-20 15:54
@korova08 Agree, but there seems to be some issue with packaging so, I just provided an option to revert back to previous version instead of getting involved in all the process of Building from Source

**Comment by robertgeb** [comment] 2016-03-20 21:52
Arch linux 32-bit, too

**Comment by dweldon** [comment] 2016-03-20 22:03
For anyone using the WebUpd8 PPA: if you just hosed atom by updating to 1.6, you can remove it and then manually install this deb:

http://ppa.launchpad.net/webupd8team/atom/ubuntu/pool/main/a/atom/atom_1.5.4-1~webupd8~0_i386.deb

**Comment by Narrat** [comment] 2016-03-21 02:06
Same symptoms and error and also on 32bit

**Comment by jvandenbroek** [comment] 2016-03-21 11:08
Link dweldon above provided no longer exists, found a working one here: https://bugs.launchpad.net/~nilarimogard/+archive/ubuntu/test3/+files/atom_1.5.4-1~webupd8~0_i386.deb

**Comment by jag3rm3ist3r** [comment] 2016-03-22 04:28
Why is this still marked as needs reproduction, we have clearly reproduced it many times.

**Comment by Sfinx** [comment] 2016-03-23 08:28
The same thing with v1.6.0 x32 build at slackware

**Comment by joshaber** [comment] 2016-03-23 12:13
@jag3rm3ist3r Very true!

To provide some context, on most platforms we download pre-built binaries of NodeGit. 32-bit Linux is the one exception. But it _should_ fall back to building from source. Clearly that's not happening.

**Comment by Sfinx** [comment] 2016-03-23 12:47
I've builded by hand the nodegit and clearly seeing it (nodegit.node ELF binary) in my local node_modules directory (~/node_modules/nodegit/build/Release/). So I'm seeing that atom installs the similar binary ELF file in /usr/local/share/atom/resources/app.asar.unpacked/node_modules/git-utils/build/Release but it is named git.node.

**Comment by joshaber** [comment] 2016-03-23 12:53
@Sfinx Ah, note that `git-utils` is different from `nodegit`.

**Comment by Arakaki** [comment] 2016-03-23 13:08
I built on another machine(32bit Lubuntu).
But not works.

**Comment by Sfinx** [comment] 2016-03-23 13:12
git-utils contains the same libgit2 functions linked inside (checked with nm) as the nodegit.node.

**Comment by joshaber** [comment] 2016-03-23 17:04
Yes, both `git-utils` and `nodegit` include libgit2. However, this issue is about `nodegit`.

**Comment by ioganegambaputifonguser** [comment] 2016-03-24 09:59
I have the same issue
Build atom from the sources v1.7.0-beta0
```
uname -a
Linux iogane-pc 3.19.0-56-generic #62~14.04.1-Ubuntu SMP Fri Mar 11 11:03:33 UTC 2016 i686 i686 i686 GNU/Linux
```

**Comment by Sfinx** [comment] 2016-03-25 04:34
May be related ?

http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/

**Comment by SEAPUNK** [comment] 2016-03-25 04:37
@Sfinx No, left-pad was un-unpublished. "Cannot read property 'target' of null" is a known npm issue that isn't related to unpublished packages, that looks like it's still being worked on.

**Comment by Sfinx** [comment] 2016-03-25 04:43
@SEAPUNK I see. I mean that the original author have been unpublished all his modules 

https://gist.githubusercontent.com/azer/db27417ee84b5f34a6ea/raw/50ab7ef26dbde2d4ea52318a3590af78b2a21162/gistfile1.txt

left-pad was published back without his permission and will

**Comment by yixiaoyang** [comment] 2016-03-27 09:16
same problem on  Gentoo x86 i686(32bit)

**Comment by cancerberoSgx** [comment] 2016-03-28 08:43
Same problem here in Arch linux 32 bits. Steps to reproduce: 
1) Follow https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md
2) execute atom-beta
P/D: no relevant errors / information in the terminal

**Comment by rafaelsoaresbr** [comment] 2016-03-28 15:57
Same problem with Arch Linux i686, Atom v1.6 built from AUR, v1.5.4 is fine.
Please fix this problem.
$ atom -f
[23329:0328/115549:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[23329:0328/115550:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
App load time: 563ms

**Comment by tbranyen** [comment] 2016-03-28 17:01
@rafaelsoaresbr I'm also on Arch Linux, very surprised that AUR doesn't install the prebuilt when one exists and instead opts to recompile and install.

Unless you're missing the Arch base-devel package, I can't imagine why it wouldn't compile from source for you. Did you see any GCC output?

**Comment by SEAPUNK** [comment] 2016-03-28 17:05
@tbranyen I'm on Arch/AUR as well, and it builds the atom package fine for me -- I think nodegit silently fails to install. When I manually attempted to install nodegit (`npm install nodegit` in a clean directory), it gave me the error in my previous comment (https://github.com/atom/atom/issues/10819#issuecomment-200963545).

**Comment by rafaelsoaresbr** [comment] 2016-03-28 17:49
@tbranyen I got a lot of erros when I run npm install nodegit (http://pastebin.com/WtvmN2JP)
I have tried to build form source with no success (http://www.nodegit.org/guides/install/from-source/)

**Comment by artynet** [comment] 2016-03-30 09:02
Same issue with the very latest trunk source. OS : xubuntu 14.04.1 LTS

**Comment by nikmartin** [comment] 2016-03-30 22:24
@joshaber I'm getting the error on 
`Linux nik-desk 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux`

**Comment by SEAPUNK** [comment] 2016-04-01 21:08
I created a PR over at nodegit that should start publishing 32-bit binaries for nodegit. If this works, then after a new release of nodegit is out, and after atom bumps its version, it should hopefully start working again.

**Comment by joshaber** [comment] 2016-04-01 21:21
That's fantastic! Thanks @SEAPUNK!

**Comment by eqielb** [comment] 2016-04-04 02:35
same error on 
OSX EI Capitan 10.11.4
node v5.7.0

**Comment by rafaelsoaresbr** [comment] 2016-04-04 05:54
https://github.com/nodegit/nodegit/commit/25afe8a80fae9c0a82b6861768ccb0e22b852616
The fix was merged upstream, let's see how it does.

**Comment by johnhaley81** [comment] 2016-04-07 23:48
Just published v0.12.2 of nodegit which contains the 32-build prebuilt binaries https://github.com/nodegit/nodegit/releases/tag/v0.12.2

**Comment by rafaelsoaresbr** [comment] 2016-04-08 05:12
For those running Arch Linux i686 it's now possible to build/run Atom 1.6.2 (from AUR) editing packages.json file:
https://github.com/sjug/atom-editor/issues/4#issuecomment-207211093
I hope that @sjug create a patch inside AUR package.

**Comment by artynet** [comment] 2016-04-08 09:22
so i think it's just a matter of updating the nodegit version in the package.json file to 0.12.2

**Comment by rafaelsoaresbr** [comment] 2016-04-09 03:17
Yes @artynet 
Since https://github.com/nodegit/nodegit/pull/980 has been merged.
I've just opened a pull request to fix AUR package:
https://github.com/sjug/atom-editor/pull/5

**Comment by mahdavipanah** [comment] 2016-04-10 08:08
I have the same issue with **v1.6.1** and **v1.6.2** but v1.6.0 works fine.
My system: elementry OS Freya (Ubuntu 14.04) 64-bit

P.S. I updated atom to v1.6.2 on my _Linux Mint 17.3 Rosa (Ubuntu 14.04) 64-bit_ and it worked with no problem.

**Comment by rafaelsoaresbr** [comment] 2016-04-10 20:30
This problem is related to 32bits machines. There wasn't 32-bit prebuilt binaries of nodegit.
If you have this problem on 64-bit machine, then something went wrong with you build. Or not, can someone confirm this? For me this problem doesn't happen on 64-bit Linux machine.

Running:
```
npm install nodegit
```
Didn't solve this problem on 32bit machines (See https://github.com/atom/atom/issues/10819#issuecomment-198778893)

**Comment by joshaber** [comment] 2016-04-11 18:16
As of #11426 we should be able to nodegit's 32-bit binaries too.

**Closed by joshaber** 2016-04-11 18:16 UTC
Labels: bug, build-error, linux

**Comment by roshimon** [comment] 2016-04-16 06:42
Upgrading to atom 1.8.0-beta1 has fixed the issue for me. Working flawlessly now :)

**Comment by AnwarShah** [comment] 2016-04-17 16:09
I'm on Ubuntu trusty 32bit. I built version 1.7.1 today and same errors happen. I upgraded nodegit by `npm install nodegit`, but nothing changed!

**Comment by rafaelsoaresbr** [comment] 2016-04-17 16:30
@AnwarShah 
ask the package maintainer to apply a [small patch] (https://github.com/sjug/atom-editor/blob/master/package.patch) like the one applied to the AUR package (for Arch Linux) or use v1.8beta instead.

**Comment by Sfinx** [comment] 2016-04-17 17:04
v1.8.0beta (commit 9e39445f802a63....) still not working when building from source code at Slackware 32bit.

**Comment by Sfinx** [comment] 2016-04-17 17:06
Sorry, my fault - missed "atom-beta" binary name, 1.8.0beta works ! ;)

**Comment by AnwarShah** [comment] 2016-04-18 04:03
@Sfinx I built the package myself. Trying to apply the patch. Thanks

**Comment by gzaffin** [comment] 2016-04-28 16:09
Sorry to clutter this thread.
I managed to have atom working on Ubuntu 32-bit, but it is not perfect.
After script/build of brench version atom-beta-1.8.0beta2, I git cloned nodegit, installed nodegit (here I think I missed something) and manually copied nodegid installation form my default installed modules folder into atom-beta-1.8.0beta2 modules sub-folder. In this way atom can start from out folder, but installed atom in /usr/local/bin shows once more
Error: Cannot find module '../build/Debug/nodegit.node'
etc. etc.

**Comment by nikolowry** [comment] 2016-05-24 05:56
This is still a problem in master (1.90-dev). I had to cd into `node_modules/ohnogit/node_modules/nodegit/` and run `npm run install`. I tried `npm run installDebug` but it had an error. I then duplicated the `node_modules/ohnogit/node_modules/nodegit/build/Release` to `node_modules/ohnogit/node_modules/nodegit/build/Debug` and everything worked.

Atom maintainers need to trigger a post install hook for that module
