### ISSUE TITLE
Deactivate multiple cursors feature (on Ctrl+mouse click)

### ISSUE THREAD

**Issue by mjrk** [atom/atom#7595] opened 2015-06-30 14:26 UTC
I searched already several times but I cannot find out how to deactivate multiple cursors or how to change/deactivate the key binding. Finally, I open the issue here.

If there is an option for this, how could I possibly find it; or rather, how can I find and search available configuration options in my version of the editor?
The compiled coffeescript may make it hard to find options by using `grep`.

**Comment by mnquintana** [comment] 2015-06-30 14:28
It's not currently possible to disable the multiple cursors feature. Why do you want to disable it?

All configurable options are available in Settings (search the Command Palette for Settings); core settings are in the Settings panel, and individual packages' settings are available for each package in the Packages panel.

**Comment by mjrk** [comment] 2015-06-30 15:40
@mnquintana thanks for your answer.

IMHO I have seen and searched most options accessible by the Settings, however, I was talking about further configurations in the Config folder. Some plugins and core packages allow further configuration in the `config.cson`. 
Thus, I had in mind e.g. a command (to be used in atom-terminal) to list all options. I hoped there was a way to change this keybinding or to deactivate the feature but did not know how to search for it.

I want to disable it because sometimes when coding fast with some `Ctrl`-keybinding I accidentally get two cursors with unpleasant side effects. I do not use this feature, especially I would not use it by mouse.

As there is no option - if you can point me to the code where to hack to disable it, it would be great. I already read some pull requests about multiple cursors etc., however, I could not find this place yet.

**Comment by batjko** [comment] 2015-06-30 18:24
Each individual package may have its own settings, which you can find by opening it in the packages section and clicking the "Settings" buttonp on the package itself.

**Comment by sys13** [comment] 2015-07-01 07:35
I am also trying to disable it - accidentally click it often.

**Comment by robhagemans** [comment] 2015-07-26 17:01
Would also like to be able to disable this feature, as I often activate it without intending to (perhaps due to how my touchpad works?) and I don't really have a frequent use for it. Since the effects can be quite confusing and intrusive if you don't notice  double cursor is on, it can take quite some time to fix the damage.

**Comment by gerkirill** [comment] 2015-08-27 11:53
+1 for robhagemans comment.

**Comment by maxbrunsfeld** [comment] 2015-08-27 16:22
Related: https://github.com/atom/atom/issues/2256. If mouse events were handled via the key-map system, we could unset or override them the same way we do for key-bindings.

**Comment by hedefalk** [comment] 2015-10-15 11:23
+1 I do not use this feature, but have a binding of cmd-click for "jump to definition" of my Scala IDE https://atom.io/packages/ensime (most IDE:s use cmd-click for this). Collision.

**Comment by bibendi** [comment] 2015-10-28 09:44
+1 it's an annoying feature

**Comment by nmote** [comment] 2015-11-02 21:34
Nuclide uses cmd+click on OS X for click-to-symbol (via the hyperclick package). This is a common binding for click-to-symbol in other IDEs. It would be valuable for us to have multiple cursors use a different binding so that these no longer conflict. If that is not possible, it would at least be nice to have the ability to disable it.

**Comment by SergKam** [comment] 2015-12-18 17:30
+1 for the "Go To Declaration" action

**Comment by proAlexandr** [comment] 2016-02-16 17:00
+1 for the "Go To Declaration" action

**Comment by magnusart** [comment] 2016-03-10 15:15
+1 I ran into this issue with Scala ID for Ensime as well.

**Comment by DGolubets** [comment] 2016-03-12 20:25
Yeah, I often use it accidentally.. very annoying.

**Comment by dorian-marchal** [comment] 2016-03-21 15:51
+1 for the "Go To Declaration" action

**Comment by top1select** [comment] 2016-04-07 23:21
+1, this is causing a lot of trouble to me, once i accidentally triggered it without me knowing, so all of a sudden the javascript is not working any more, and firebug is throwing irrelavent error messages.  it took me a while, but still not able to figure out what went wrong, at last i had to restore the last working code, there is no way to debug this kind of issues.

**Comment by lxg** [comment] 2016-04-21 15:01
definitely +1 for the "Go To Declaration" action

**Comment by anwerjunaid** [comment] 2016-05-02 06:35
+1 for Go To Declaration, may be only for JS.

**Comment by fariza** [comment] 2016-05-13 02:29
+1 for Go to Declaration

**Comment by theonedemon** [comment] 2016-05-13 08:45
+1 for Go to Declaration

**Comment by manustays** [comment] 2016-05-16 12:10
+1, Ctrl+Click has caused a lot of bugs for me. Really need a way to disable it.

**Comment by shigekazu-inohara** [comment] 2016-05-28 21:19
Here is a quick workaround for deactivating multiple cursors invoked by Ctrl-click on Windows.  This workaround depends on autohotkey (https://autohotkey.com/).  Ctrl-click is converted to a simple “click” if the active window is atom, while other applications continue to receive Ctrl-click.  
``` 
;;; autohotkey config for deactivating Atom multiple cursors through mouse click ;;;
^LButton::
if WinActive("ahk_exe atom.exe") {
    Send {LButton}
    Return
} else {
    send ^{LButton}
    Return
}
```
You can substitute “Send {LButton}” with a keyboard shortcut for “Go-to-declaration”, if you like.

**Comment by philmaker1** [comment] 2016-06-05 00:54
Yes, please allow multi-cursor mode to be disabled or assigned to another key command. This is going to cause more grief and defects than it's worth.

**Comment by Laberbear** [comment] 2016-06-05 22:05
+ 1 on the disabling part.
It's a huge issue for since I often randomly hit the touchpad on my laptop while typing.

**Comment by wli0503** [comment] 2016-07-06 15:29
+1 on having the option of disabling it. Not a huge fan of the feature.

**Comment by theonedemon** [comment] 2016-07-30 21:08
bump

**Comment by sgsvenkatesh** [comment] 2016-08-13 06:58
+1 for Go to Declaration

**Comment by orenmizr** [comment] 2016-11-05 20:38
any news about disabling multi cursor ?

**Comment by Laberbear** [comment] 2016-11-06 22:40
@orenmizr Yes it is pretty easy actually
https://code.visualstudio.com/

This will solve this and the non-english keyboard layout issues.

**Comment by bretsko** [comment] 2016-12-05 20:49
+1 for having the ability to disable multiple cursors on ctrl+click

**Comment by GroovyCarrot** [comment] 2016-12-22 19:32
Trying to get into using atom, however this functionality keeps tripping me up. This is also probably better replaced with some refactoring tools, ie. symbol renaming.

**Comment by chrisjensen** [comment] 2017-03-19 10:29
I've been using atom for 2 weeks. I've yet to deliberately use this feature, but it trips me up practically every hour.
Can we have an off switch please?

**Comment by SergKam** [comment] 2017-03-22 00:40
Let's do something about it.
The code is here https://github.com/atom/atom/blob/master/src/text-editor-component.coffee#L559
As a workaround, you can just replace method call `addCursorAtScreenPosition` with `setCursorScreenPosition`.

 In long term, I would add another keyboard like keystroke,(similar to `ctrl+MouseLeft`) and fire it after setting cursor (like here https://github.com/atom/atom-keymap/blob/master/src/keymap-manager.coffee#L589)
```js  
this.emitter.emit('did-match-binding', {
          keystrokes: keystrokes,
          eventType: event.type,
          binding: dispatchedExactMatch,
          keyboardEventTarget: target
        });
```
So users can configure any handler for it.

**Comment by SergKam** [comment] 2017-03-22 01:39
Looks like related issues to me. "Mouse configuration".  https://github.com/atom/atom/issues/4402

**Comment by SergKam** [comment] 2017-03-22 01:43
And this https://github.com/atom/atom/issues/2256

**Comment by seinecle** [comment] 2017-03-24 12:35
Please, no time to fiddle with Atom internals to disable it - I keep editing stuff in the wrong place because of this feature. Can the atom team move on it? Thanks!

**Comment by twothe** [comment] 2017-03-24 21:14
Select text, ctrl-c, click somewhere else (with ctrl accidentally still down), ctrl-v, start writing, erase previously selected text thanks to this "feature".

SO. SUPER. ANNOYING!

**Comment by alupkasix** [comment] 2017-04-14 07:20
Atom is amazing, so thanks for that. But . . .

+1 to disable this feature!

My code project just went atomic because of this feature. While writing one function, it was simultaneously rewriting other functions without my knowledge (yes more than one because they were smaller). Took me ages to repair and figure out what happened. Atom is supposed to help me code faster, but due to this feature it just completely destroyed my project and wasted a lot of my time. As a result of this feature, I'm so paranoid about it wrecking my code again that I'm actually developing much slower than with alternative editors.

I usually have six different panels open across 4 monitors so it's not always obvious where the multiple cursors are. I also have a very sensitive ctrl key. 

So please, just let me disable it in settings. Can this be included the next update?

**Comment by 50Wliu** [comment] 2017-04-15 02:29
> So please, just let me disable it in settings. Can this be included the next update?

Perhaps if you submit a PR implementing the setting, then yes.

**Comment by chrisjensen** [comment] 2017-04-15 12:01
To add some additional context for developers that wonder why this is an issue for people, and strictly speak this is a bug on Macbooks:

On Macbook's, there is a delay of around 500ms between a tap on the trackpad, and that tap being sent to the application.

The delay is while the system determines if it's a tap or a tap-drag as discussed [here](https://apple.stackexchange.com/questions/14242/is-there-a-way-to-speed-up-the-way-mac-responds-to-my-trackpad-clicks)

The user experience is that Atom detects the Cmd key down at the time the click is received, and then behaves as if this is a Cmd + Click, rather than what it actually was: Cmd, Click.
So the user is getting an experience other than what they expected.

In OSX 10.11, the Tap-Drag feature cannot be disabled in the system preferences, so it's an issue for everyone using trackpad on macbooks with the latest OS.

If you have a Macbook, you can reproduce this:
1) Open Atom, open an editor and have it focused
2) Use the trackpad to tap somewhere to move the cursor to a different position in the editor, and immediately press Cmd after you remove your finger from the tap.
4) You will see a second cursor appear

So this is a bug.

Presumably it could be fixed by checking for the Cmd key down at the time of the tap rather than time of receiving the tap, but surely it'd just be easier to create an off switch ;-)

**Comment by 50Wliu** [comment] 2017-04-16 00:16
@chrisjensen You should create a separate issue for that.

**Comment by T1MOXA** [comment] 2017-04-25 07:32
+1 to disable this feature!

**Comment by hg42** [comment] 2017-04-25 10:01
> Presumably it could be fixed by checking for the Cmd key down at the time of the tap rather than time of receiving the tap

If that's possible (and it really should or OSX would be terribly broken) that's definitely the way to go.

There can be several seconds between creating an event and receiving it. Situations like heavy swapping and blocking hardware interrupts can delay events for several seconds. There could even be a suspend and wakeup in between.

Thererfore, in an event based user input system and especially with cooperative multitasking it's mandatory to use the key state at the time of event generation and never use the state after you finally received the event.

Another aspect is key binding compatibility between several platforms.
If you have to use atom on more than one platforms, you want to have the same bindings on all of them. Given different standards on different platforms you usually have to configure it yourself.
So +1 for configurable key binding for mouse events.

**Comment by satbirjhuti** [comment] 2017-06-08 18:43
I seem to have lost this feature recently. How can enable this feature?

**Comment by henhal** [comment] 2017-06-24 14:36
This is driving me crazy. At least 20 times a day I accidentally enter code in two places, It's extremely frustrating. This is one of the main reasons I prefer other IDE's over Atom.

**Comment by jellyfeelings** [comment] 2017-07-02 15:33
Hah - Would've junked Sublime for Atom if it just fixed this - same bug-creating frustrating behavior exists in Sublime with no way to disable.   Nope, guess not.

**Comment by jellyfeelings** [comment] 2017-07-02 15:33
satbirjhuti congratulations

**Comment by mayankyadav** [comment] 2017-07-07 15:26
+1 conflicts with go to definition in hyper click

**Comment by Kennna** [comment] 2017-09-28 05:54
+1 
Most annoying "feature" (i would call it a bug) of the world

**Comment by JonathanJumper** [comment] 2017-10-24 00:37
I want to go to definition, not that, why would anyone use that instead of regex

**Comment by muzixinly** [comment] 2017-11-02 08:22
+1

**Comment by olegantonyan** [comment] 2017-11-06 08:12
+1 very annoying

**Comment by eexit** [comment] 2018-01-08 12:00
+1

**Comment by VincentMarmiesse** [comment] 2018-03-02 15:06
Hi,

It's almost 3 years and it's still not possible to disable it or at least change the key binding?

**Comment by gerkirill** [comment] 2018-03-15 13:47
> It's almost 3 years and it's still not possible to disable it or at least change the key binding?

c'mon, let's just celebrate this issue anniversary and then switch to VisualStudioCode or whatever which treats user feedback seriously.

**Comment by Kennna** [comment] 2018-03-15 14:07
@gerkirill 
My initial plan was to drop Notepad++ for Atom back in September 2017. But thanks to the multi-cursor nonsense, i'm still using Notepad++ and will continue to do so.

As someone furiously saving the file i'm working on with CTRL+S, selecting content with CTRL+A, revert changes with CTRL+Z and copying/pasting stuff with CTRL+C and CTRL+P its nearly inevitable to accidentally write on multiple lines without even noticing it.

Its so stupid and unbelievable that none of the developers of Atom had this problem in mind.

**Comment by grade-xavier** [comment] 2018-04-06 06:44
+1 ctrl+click should select the whole word. But hey. Let the user decide!

**Comment by gstokkink** [comment] 2018-09-12 09:38
+1

**Comment by paiv** [comment] 2018-12-12 08:56
In four years of using Atom, I don't recall I ever using the multiple cursors feature. But myriad times it turned on, with me not expecting it.

I need an option to disable it, or rebind to another short-key.

Atom 1.33.0, macOS, touchpad

**Comment by henhal** [comment] 2018-12-12 09:09
@paiv Same here, and about a year ago this issue single-handedly made me leave Atom. Unbelievable that this issue is still open 3½ years later.

**Comment by grade-xavier** [comment] 2018-12-12 10:13
@paiv and @henhal Same here! I still use Atom but will eventually leave because of this and the poor drag and drop editing support.

**Comment by olegantonyan** [comment] 2018-12-12 10:17
wow! more than 1 year I'm using a modified version https://github.com/atom/atom/issues/7595#issuecomment-342074841

**Comment by lkview** [comment] 2019-01-17 14:52
Has caused me a lot of grief. Please allow disabling this feature.

**Comment by chrisjensen** [comment] 2019-01-24 02:34
I just want to say, I love how Atom asks you if it can collect telemetary to improve the product, but when over 60 people take time to come and create an issue for something that's causing a lot of grief, the developers are like "Nope!"

**Comment by grade-xavier** [comment] 2019-01-24 08:40
> I just want to say, I love how Atom asks you if it can collect telemetary to improve the product, but when over 60 people take time to come and create an issue for something that's causing a lot of grief, the developers are like "Nope!"

Bad, bad, bad to be so stubborn. It seems almost religiously locked. Mac user taking decision on that?

**Comment by 50Wliu** [comment] 2019-01-24 14:47
@chrisjensen thanks for your input. This issue is still open because we are willing to entertain and review a well-crafted PR that adds the ability to deactivate this feature, but it is unlikely that the Atom maintainers will have time to implement this in the near future.

**Comment by lukecleland-myfiziq** [comment] 2019-08-08 07:22
I am considering switching IDEs because of this.  Why is it not fixed yet?  It's a bug masquerading as a feature.

**Comment by octomagon** [comment] 2019-08-17 13:44
I am also actively looking for other IDEs because of this. Atom is SO good otherwise, but it is not worth the fury I feel every time I accidentally do this.  This feature should exist, but be inactive by default.  Bad user experience, IMHO.

**Comment by alupkasix** [comment] 2019-08-18 06:40
why are so many directly relevant comments marked as spam?

**Comment by chrisjensen** [comment] 2019-11-08 07:36
Yeah, I'm done. I've switched

**Comment by grade-xavier** [comment] 2019-11-08 08:19
It is not so much for the multiple cursor function but more for the **deaf ears** and **lack of respect** for the users' requests that I have left this editor for more flexible ones.

Good by and thanks for all the fish.

**Comment by finnbear** [comment] 2020-02-22 01:52
While using Atom, I regularly find seemingly random snippets of strings, numbers, and code blocks throughout my files. Sometimes they cause compile errors. Sometimes they case bugs. Sometimes they go unnoticed for a while. **Now I know why.** The lack of a way to turn this off ruins Atom's usability, in my view, unless of course you rely on random mutations to improve your code via a process of natural selection.

**Comment by UziTech** [comment] 2020-02-22 02:48
Pressing <kbd>Esc</kbd> cancels the multiple cursors

**Comment by finnbear** [comment] 2020-02-22 03:58
> Pressing Esc cancels the multiple cursors

That works, so long as you know multiple cursor mode is on. A big problem is that saving the file with `CTRL+S` and clicking the mouse to edit a new part of the file (without releasing the control key in time) often activates a second cursor without the user even knowing. The end result is that whatever you were typing gets duplicated to wherever your cursor was before.

**Comment by lkview** [comment] 2020-02-22 12:58
This is an extremely annoying, frustrating, and time-wasting issue. We know that pressing esc cancels the multiple cursors — the problem is that you don't know that the mode is on.

Please provide a way to turn off the feature. Better yet, the default should be off.

**Comment by UziTech** [comment] 2020-02-24 20:33
I created PR  #20444 which adds a setting to disable adding multiple cursors on <kbd>Ctrl</kbd> + Click

**Closed** 2020-05-13 11:29 UTC
Labels: enhancement

**Comment by leviwheatcroft** [comment] 2020-06-12 09:48
I can't get ctrl-click to create multiple cursors at all.

Checking / unchecking doesn't change the setting in config.cson

if I manually set config.cson to be multiCursorOnClick: true, ctrl-click still doesn't work.

I'm using 1.48.0 x64 on windows. Is there any additional information I can provide?

**Comment by kevteljeur** [comment] 2020-06-12 13:23
I've just spent far too long going through all my packages and trying to research it, and it seems like it is a core breakage. Is this a reported issue?

**Comment by kevteljeur** [comment] 2020-06-12 13:27
> I can't get ctrl-click to create multiple cursors at all.
> 
> Checking / unchecking doesn't change the setting in config.cson
> 
> if I manually set config.cson to be multiCursorOnClick: true, ctrl-click still doesn't work.
> 
> I'm using 1.48.0 x64 on windows. Is there any additional information I can provide?

Here, I should have checked it myself instead of agreeing (it's a problem for me too): https://github.com/atom/atom/issues/20911

**Comment by UziTech** [comment] 2020-06-12 14:00
Temporary fix:
Open the console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>) and run
`atom.config.set('core.editor.multiCursorOnClick', true);`

**Comment by chimeraha** [comment] 2021-08-24 00:24
For those still looking to for the setting, it's at:

Settings -> Editor -> Multi Cursor on Click
