### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/vijay/dev/ruby/oss/XXX/project.json'

### ISSUE THREAD

**Issue by vraravam** [atom/atom#4872] opened 2015-01-06 16:16 UTC
[Enter steps to reproduce below:]

1. Quit and reopen atom when a project was previously open.
2. My settings will try to reopen files that were previously open while quitting.
3. But, there is no file called 'project.json' in that folder.

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/vijay/dev/ruby/oss/XXX/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/vijay/dev/ruby/oss/XXX/project.json'
  at Error (native)

```

### Commands

```
  2x -30:00.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true,
    "disabledPackages": [
      "language-c",
      "archive-view",
      "welcome",
      "jshint",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-toml",
      "package-generator"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "showIndentGuide": true,
    "preferredLineLength": 120,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.2
autocomplete-plus-async, v0.22.0
change-case, v0.4.0
coffee-compile, v0.8.4
file-type-icons, v0.5.3
git-tab-status, v1.3.0
highlight-line, v0.9.2
highlight-selected, v0.7.0
language-rspec, v0.2.1
linter, v0.9.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-less, v0.3.1
linter-rubocop, v0.2.1
linter-scss-lint, v0.0.11
minimap, v3.5.0
minimap-git-diff, v3.1.0
omnisharp-atom, v0.1.6
recent-files, v0.3.0
recent-projects, v0.2.6
ruby-block-converter, v2.5.0
save-session, v0.11.2
syntax-settings, v0.7.1
tab-history, v0.4.0
tree-ignore, v0.1.1

# Dev
No dev packages
```

**Comment by vraravam** [comment] 2015-01-06 16:33
This could be an issue with the save-session plugin and not necessarily from atom (the core) - but, this started happening only once i upgraded to atom v 0.166 (in 0.165, i didnt face this issue)

**Comment by benogle** [comment] 2015-01-06 18:31
Dupe of mpeterson2/save-session#43

**Closed by benogle** 2015-01-06 18:31 UTC
