### ISSUE TITLE
Syntax Highlighting breaks after certain length of line

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#13270] opened 2016-11-19 05:40 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

If a line exceeds a certain length, syntax highlighting stops working.
I'm not sure where to report this bug, is this something the language (in this case Lua) module has to fix or the editor itself? 

### Steps to Reproduce

1. [First Step]
Create a new file
2. [Second Step]
Example code
```
zoneIDs.SpeciesToZoneId = {
[1755]={[1014]=1014}, -- Plump Jelly
	[1233]={[782]=782}, -- Pocket Reaver
	[1200]={[930]=930}, -- Pygmy Direhorn
	[1907]={[1018]=1018}, -- Pygmy Owl
	[378]={[181]=181,[475]=475,[510]=510,[42]=42,[27]=27,[34]=34,[30]=30,[462]=462,[121]=121,[1024]=1024,[24]=24,[491]=491,[241]=241,[606]=606,[9]=9,[950]=950,[36]=36,[480]=480,[21]=21,[81]=81,[301]=301,[20]=20,[22]=22,[39]=39,[40]=40}, -- Rabbit
	[237]={[201]=201}, -- Ravasaur Hatchling
	[238]={[40]=40}, -- Razormaw Hatchling
}
```
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Syntax highlighting works as expected
**Actual behavior:** [What actually happened]
Syntax highlighting breaks
http://i.imgur.com/wGRnPTf.png

### Versions

Atom    : 1.14.0-dev-87e6776
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

Windows 8.1 x64

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Alhadis** [comment] 2016-11-19 07:40
This is natural. Each line is capped to match a certain number of tokens, and no more.

It does this for performance reasons.

**Comment by Ben3eeE** [comment] 2016-11-19 08:50
Thanks @Alhadis. This is a duplicate of https://github.com/atom/atom/issues/1667. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-11-19 08:50 UTC
