### ISSUE TITLE
Runs only when connected with Internet

### ISSUE THREAD

**Issue by sparkprince** [atom/atom#17513] opened 2018-06-14 17:57 UTC
My Atom was previously working fine but today when I opened it, it worked because it was connected with internet but after getting offline, when I tried to restart, it does not worked. I did a experiment. First I connected my PC with Internet, and it worked. Then I tried it after getting disconnected which resulted in Atom no respond. Nothing happens , I checked in task manager there was no single sigh of it. I tried this so many time and same result I got. Making me frustrated. Same result every time... 
Internet=Atom runs
No Internet=Atom's do not run

**Comment by sparkprince** [comment] 2018-06-14 17:59
same thing was happening with VS Code

**Comment by rsese** [comment] 2018-06-14 19:09
Thanks for the report!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16373 so you can subscribe there if you'd like.  Also, please fill out the issue template for future issues, the information in the template is helpful for us when triaging issues.

> same thing was happening with VS Code

Maybe an Electron issue then?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by rsese** [comment] 2018-06-14 19:10
> Maybe an Electron issue then?

This looks related?

https://github.com/electron/electron/issues/6437

**Closed by rsese** 2018-06-14 19:09 UTC
