### ISSUE TITLE
[MAC] Text is bolder since 1.39

### ISSUE THREAD

**Issue by mrleblanc101** [atom/atom#19715] opened 2019-07-28 04:11 UTC
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:
* [x] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
* [x] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
* [x] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
* [x] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
* [x] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The text got bolder and it's very ugly.
I'm on a 15" Macbook Pro with retina display (2017)
My display scaling is a «More space» in macOS settings

### Steps to Reproduce

1. Update atom to 1.39 from 1.38

**Expected behavior:**

The font-weight shouldn't have changed between the two version

**Actual behavior:**

All the text is slightly bolder.

**Reproduces how often:**

Always

### Versions
atom -v
```
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
apm -v 
```
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 2.7.15
git 2.18.0
```

### Additional Information
Before:
<img width="2032" alt="Capture d’écran, le 2019-07-28 à 00 01 23" src="https://user-images.githubusercontent.com/17392251/62002134-30cbf280-b0cc-11e9-9772-821e0cd946fc.png">
After:
<img width="2032" alt="Capture d’écran, le 2019-07-28 à 00 02 52" src="https://user-images.githubusercontent.com/17392251/62002135-31648900-b0cc-11e9-9ea3-422f1fd6ab8f.png">

**Comment by gussyboy** [comment] 2019-07-28 22:41
I have this same issue too and i find it much hard to read the text, now. So im downgrading back to 1.38.0

**Comment by Arcanemagus** [comment] 2019-07-29 15:32
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/19356. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-07-29 15:32 UTC
