### ISSUE TITLE
Settings referred to as Preferences

### ISSUE THREAD

**Issue by meiamsome** [atom/atom#13935] opened 2017-03-05 18:14 UTC
The settings pane is referred to as preferences in the menus, which makes it hard to find when using the menus.

**Comment by rsese** [comment] 2017-03-05 21:41
Thanks for the report!  You don't mention but I'm assuming you're on macOS?  If so, then this is a duplicate of https://github.com/atom/atom/issues/1640 and there's more discussion about the naming in that issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-05 21:41 UTC

**Comment by meiamsome** [comment] 2017-03-05 23:03
Hey @rsese,

Sorry for not specifying, I didn't realize it differed across distributions, and I didn't find #1640 when searching before. My actual issues is on the linux distribution where it is under edit -> preferences.

**Comment by rsese** [comment] 2017-03-06 20:04
> Sorry for not specifying, I didn't realize it differed across distributions, and I didn't find #1640 when searching before.

np :v:

>  My actual issues is on the linux distribution where it is under edit -> preferences.

Ahh gotcha - based on the discussion in https://github.com/atom/atom/issues/1640, I think it's similar to the macOS issue?  With Chrome on macOS and the Linux distribution I'm using (Ubuntu), they both have a Preferences menu item that goes to chrome://settings and Atom mirrors that in both cases.
