### ISSUE TITLE
Package author images are broken on Windows installs

### ISSUE THREAD

**Issue by tvanantwerp** [atom/atom#10607] opened 2016-01-27 19:51 UTC
The author images for packages are often broken. I usually notice it in the update section, as shown below. This has been happening on both my work and home Windows machines (10 and 8.1, respectively). Sometimes they do display correctly, but it's very hit-or-miss. Not a terribly critical issue, but wanted to report it. The below image is from Atom 1.4.0 on Windows 10.

![image](https://cloud.githubusercontent.com/assets/2487968/12626109/f09b34de-c504-11e5-9323-9abe78c44316.png)

**Comment by lee-dohm** [comment] 2016-01-27 20:29
This is a duplicate of https://github.com/atom/settings-view/issues/327 and https://github.com/atom/settings-view/issues/595. Please subscribe there for updates :grinning:

**Closed by lee-dohm** 2016-01-27 20:29 UTC
Labels: duplicate
