### ISSUE TITLE
Atom Detected as virus

### ISSUE THREAD

**Issue by di48l069** [atom/atom#7138] opened 2015-06-06 11:46 UTC
Hi there after the new update my avast detected atom as a virus and as blocked it. I tried uninstalling and reinstalling it but continues to block it. What must I do?

See image
![virus](https://cloud.githubusercontent.com/assets/7794777/8019536/07673f9c-0c54-11e5-8d49-2f8a354f1060.PNG)

**Comment by mnquintana** [comment] 2015-06-06 12:45
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/3927 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-06 12:45 UTC
