### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 61

### ISSUE THREAD

**Issue by antheali89** [atom/atom#20123] opened 2019-11-06 19:37 UTC
[Enter steps to reproduce:]

1. typed a SQL comment

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 61

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 61
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
  3x -1:31 editor:newline (input.hidden-input)
  2x -1:26.9.0 core:backspace (input.hidden-input)
  2x -1:21.6.0 editor:newline (input.hidden-input)
  2x -0:51.5.0 core:select-up (input.hidden-input)
     -0:50.5.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:48.7.0 core:copy (input.hidden-input)
     -0:37.5.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:36.8.0 editor:move-to-end-of-word (input.hidden-input)
     -0:36.4.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:36.1.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:35.8.0 core:backspace (input.hidden-input)
     -0:35 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -0:28.5.0 editor:newline (input.hidden-input)
     -0:23.9.0 core:backspace (input.hidden-input)
  2x -0:18.5.0 core:move-up (input.hidden-input)
     -0:17.3.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by kiralikbeyin** [comment] 2019-11-10 12:30
@antheali89 
Same here.
I removed unused atom packs and click atom>about atom and restart solved my problem.

**Comment by rsese** [comment] 2019-11-11 01:09
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

If you can, please let us know in that issue if you consistently see the error with your steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-11 01:09 UTC
