### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by mikecg** [atom/atom#6971] opened 2015-05-27 13:07 UTC
1. I opened a markdown file
2. I typed ctrl-shift-m to get the markdown preview
3. I highlighted some text in the markdown preview, and right clicked.

**Atom Version**: 0.201.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\mgreenspan\AppData\Local\atom\app-0.201.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:07.6.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "c:\\Repository\\Cougar Cloud",
    "disabledPackages": [
      "language-syntax-settings",
      "omnisharp-atom"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.6
atom-yeoman, v0.2.0
autocomplete-plus-async, v0.22.0
language-csharp, v0.5.0
language-powershell, v2.0.1
last-cursor-position, v0.9.0
linter, v0.12.6
pretty-json, v0.3.3
script, v2.23.0
sync-settings, v0.2.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-05-27 13:08
This is a duplicate of https://github.com/atom/atom/issues/6548 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-27 13:08 UTC
Labels: duplicate
