### ISSUE TITLE
False git error when trying to install packages

### ISSUE THREAD

**Issue by TrangPham** [atom/atom#5471] opened 2015-02-09 23:10 UTC
This is a minor issue. When trying to install some packages through Atom's packages > setting view >  install packages/themes , a false error is given (screenshot below), and the package is not installed. But apm can find git and the packages install using the command line.

Atom version: 0.177.0
Mac OSX: 10.9.5

![screen shot 2015-02-09 at 6 01 50 pm](https://cloud.githubusercontent.com/assets/2117313/6117883/0aa88bea-b086-11e4-8e92-9e585a4dd591.png)

Here's my `apm -v` output:
```
> apm -v
apm  0.134.0
npm  2.3.0
node 0.10.35
python 2.7.5
git 2.3.0
```

Installing via `apm install` works perfectly fine:
```
> apm install linter
Installing linter to /Users/trangpham/.atom/packages ✓
> apm install merge-conflicts
Installing merge-conflicts to /Users/trangpham/.atom/packages ✓
```

And then restarting atom shows the installed packages.

**Comment by kevinsawicki** [comment] 2015-02-09 23:21
Where do you have Git installed to?

**Comment by TrangPham** [comment] 2015-02-09 23:22
I have installed git through home brew

```
> which git
/usr/local/bin/git
```

**Comment by kevinsawicki** [comment] 2015-02-09 23:22
Can you open the dev tools in Atom (`cmd-alt-I`) and run `process.env.PATH` from the Console tab and include the the value that gets printed?

**Comment by TrangPham** [comment] 2015-02-09 23:24
Yes

```
process.env.PATH
"/usr/bin:/bin:/usr/sbin:/sbin"
```

**Comment by kevinsawicki** [comment] 2015-02-09 23:26
> Is it the difference between this PATH and my bash PATH which is causing the issue?

I believe so

**Comment by kevinsawicki** [comment] 2015-02-09 23:32
I think this is a duplicate of https://github.com/atom/atom/issues/1874 and https://github.com/atom/atom/issues/4126

I would recommend subscribing to those issues to know when this is resolved.

**Closed by kevinsawicki** 2015-02-09 23:32 UTC

**Comment by TrangPham** [comment] 2015-02-09 23:37
@kevinsawicki Actually I think it's related to https://github.com/atom/atom-shell/issues/550 more.
I found this after a bit of digging: https://github.com/atom/atom/blob/ef9ae8e7d75bbba0e8990c6c854236f40ec9b4f7/src/browser/main.coffee#L162

``` Javascipt
  # On Yosemite the $PATH is not inherited by the "open" command, so we have to
  # explicitly pass it by command line, see http://git.io/YC8_Ew.
  process.env.PATH = args['path-environment'] if args['path-environment']
```

Thanks for your help! :)
