### ISSUE TITLE
Problem with Arabic

### ISSUE THREAD

**Issue by modev32** [atom/atom#13010] opened 2016-10-17 18:55 UTC
### Description

It seems to be difficult to write Arabic within codes as it becomes impossible to select the text or to move the courser around the Arabic words. Plus I can't highlight words written in Arabic.

### Versions
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Running on:
      System Version: macOS 10.12 (16A323)
      Kernel Version: Darwin 16.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

**Comment by Ben3eeE** [comment] 2016-10-21 15:29
This is a duplicate of https://github.com/atom/atom/issues/12282. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-21 15:29 UTC
