### ISSUE TITLE
ctrl-0 conflicts on Windows and cannot reset font size

### ISSUE THREAD

**Issue by awayken** [atom/atom#7185] opened 2015-06-09 14:42 UTC
When I hit `ctrl-0` in an editor pane, I expect the font-size to reset. Instead, the tree view focus is toggled. The `ctrl-=` and `ctrl--` keystrokes both work to increase and decrease the font size, and `ctrl-0` is listed under the "View" toolbar menu as being the appropriate keyboard shortcut for resetting font size.

There are no errors in the Developer Tools. The issue appears simply to be a keystroke conflict. For `.platform-win32, .platform-linux`, `ctrl-0` toggles tree view as well as resets font size, and tree view toggle apparently wins.

I'm using Windows 8.1 and Atom 0.207.0.

**Comment by mnquintana** [comment] 2015-06-09 14:51
There are two keybindings for Reset Font Size – the second is <kbd>Ctrl-Shift-0</kbd> which shouldn't have any out of the box conflicts.

**Comment by awayken** [comment] 2015-06-09 15:31
@mnquintana I tried `Ctrl-Shift-0` but nothing happened. When I search for all "font" keybindings, I find shift aliases for increase and decrease but not reset.

![font-keybindings](https://cloud.githubusercontent.com/assets/156215/8061870/852a3598-0e92-11e5-8aa2-0e03cec4723c.png)

**Comment by mnquintana** [comment] 2015-06-09 15:32
@awayken Ah my mistake! I was thinking of the increase / decrease font size commands. This is indeed a keybinding conflict - we should figure out what to do about this for Windows and Linux.

/cc @atom/feedback

**Comment by 50Wliu** [comment] 2015-06-09 15:40
This is actually a duplicate of atom/tree-view#251, so I'm going to close this in favor of that issue.

**Closed by 50Wliu** 2015-06-09 15:40 UTC
Labels: bug, linux, windows
