### ISSUE TITLE
Uncaught Error: dlopen(~/Desktop/Web Development/Atom.app/Contents/Resources/app.asar.unpacked/no...

### ISSUE THREAD

**Issue by Whitey26** [atom/atom#24485] opened 2022-03-28 03:58 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.0.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)

```
At electron/js2c/asar.js:140

Error: dlopen(/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 0x0001): tried: '/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node' (no such file), '/usr/lib/keyboard-layout-manager.node' (no such file)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app/static/<embedded>:1:756278)
    at get_KeyboardLayoutManager (/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app/static/<embedded>:14:2890405)
    at get_manager (/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app/static/<embedded>:14:2890507)
    at Object.getCurrentKeyboardLayout (/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app/static/<embedded>:14:2890633)
    at e.keystrokeForKeyboardEvent (/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app/static/<embedded>:14:1118314)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app/static/<embedded>:11:1224088)
    at KeymapManager.handleKeyboardEvent (/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app/static/<embedded>:11:1222073)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/seanwhite/Desktop/Web Development/Atom.app/Contents/Resources/app/static/<embedded>:11:286551)
```

### Commands

```
     -4:00.9.0 application:add-project-folder (input.hidden-input)
     -0:21.7.0 tree-view:add-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autoclose-html-plus 0.27.2 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-eslint-node 1.0.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by darangi** [comment] 2022-03-30 08:30
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2022-03-30 08:30 UTC
