### ISSUE TITLE
search bar is too eager

### ISSUE THREAD

**Issue by sublines** [atom/atom#8181] opened 2015-07-31 23:06 UTC
When I start searching inside a large file (or in a small file with long lines that atom hates so much), 
atom starts to lag because it immediately scans the whole file even for the first character. 

let's say I want to search in a 2k line javascript file for something like **if (a) {**.
atom will start searching the whole file for all **if**, then for all **if (**, all **if (a** and so on. 
that can get really laggy.  If I want to search for something that starts with a whitespace I can even crash atom when there are thousands of whitespaces in one file. 

I know if you type very fast you don't get that problem. but unless you search for words like **function** etc. you won't be fast enough to keep atom from auto searching..

my suggestion: don't automatically search inputs below 2 characters. if search for just one single character is ever necessary, hitting the return key or clicking the find button should not be too much to ask. or include a settings option to disable auto search below a certain number of characters.

**Comment by mnquintana** [comment] 2015-07-31 23:15
Thanks for the report! This looks like a duplicate of https://github.com/atom/find-and-replace/issues/145 – let's keep the discussion there.

(Also see https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues)

**Closed by mnquintana** 2015-07-31 23:15 UTC
