### ISSUE TITLE
Rename/New file with long path, cursor goes past input field viewable area

### ISSUE THREAD

**Issue by hilyin** [atom/atom#8174] opened 2015-07-31 18:44 UTC
Noted on version 1.0.2

Steps to reproduce:

1. In directory tree, find a file deeply nested in folders. 
2. Rename a file in deeply nested folder.
3. Try to see filename when editing.

You should see something like this:
![image](https://cloud.githubusercontent.com/assets/6288867/9014773/619df762-3779-11e5-9951-0d7d990d77cd.png)

Thanks.

**Comment by rm-code** [comment] 2015-08-06 08:43
I can confirm this. It still happens in version 1.0.4.

**Comment by izuzak** [comment] 2015-08-07 10:20
I think this is a duplicate of https://github.com/atom/tree-view/issues/473. I'm closing this in favor of that issue so that we have all reports in one place. Thanks for the feedback! 

Also /cc @simurai as a friendly ping on that issue in case you have any ideas on patching that up :smile:

**Closed by izuzak** 2015-08-07 10:20 UTC
