### ISSUE TITLE
Open file from command line with line-column didn't work in Windows

### ISSUE THREAD

**Issue by m0nhawk** [atom/atom#7709] opened 2015-07-04 21:41 UTC
Opening file from command line with line-column didn't work in Windows (particularly on Windows 8.1 and Atom 1.0.0).

Both

    > atom.cmd article.tex:22:10

and

    > atom.cmd "article.tex:22:10"

Didn't work as expected, it open the file `article.tex:22:10` and not the `article.tex` on line 22 and column 10.

**Comment by batjko** [comment] 2015-07-04 23:30
Reproducable every time on Win8.1:
Always opens a new file pane taking the the whole thing as a filename.

![image](https://cloud.githubusercontent.com/assets/7287076/8509728/0226bcfa-22ad-11e5-99cf-7085163e59ce.png)

**Comment by kubetz** [comment] 2015-07-04 23:40
Yup, 100% reproducible. GIF version :bow: :
![atom_line_col](https://cloud.githubusercontent.com/assets/1128248/8509746/c0959856-22b6-11e5-8fd7-174d63200ab9.gif)

**Comment by izuzak** [comment] 2015-07-05 06:09
Thanks for the report -- I think this is a duplicate of https://github.com/atom/atom/issues/7342.

**Closed by izuzak** 2015-07-05 06:09 UTC
Labels: bug, windows
