### ISSUE TITLE
Font become bolder when switching from atom 1.38 to atom 1.39

### ISSUE THREAD

**Issue by gffuma** [atom/atom#19699] opened 2019-07-24 16:19 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
Font become bolder when switching from atom 1.38 to atom 1.39

Atom 1.38:
![Atom1 38](https://user-images.githubusercontent.com/5680676/61810350-5f816900-ae3f-11e9-9277-80abeece8744.png)

Atom 1.39:
![Atom1 39](https://user-images.githubusercontent.com/5680676/61810367-66a87700-ae3f-11e9-9b74-b9651ce7ed7f.png)

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**
Always

### Versions

OSX: 10.14.5

Atom    : 1.39.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.0
python 2.7.15
git 2.17.2

**Comment by Arcanemagus** [comment] 2019-07-24 16:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/19356. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-07-24 16:20 UTC
