### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by MichaelSchumacher** [atom/atom#16985] opened 2018-03-19 12:11 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At C:\Users\boton\AppData\Local\atom\app-1.25.0\resources\app\src\text-editor-component.js:2280

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:2269:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:2262:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:401:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:279:20)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.25.0/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -1:22.1.0 window:decrease-font-size (input.hidden-input)
  3x -1:18.9.0 core:move-down (input.hidden-input)
     -0:10 editor:newline (input.hidden-input)
     -0:09.0 core:backspace (input.hidden-input)
     -0:07.8.0 editor:newline (input.hidden-input)
     -0:06.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
language-sml 0.7.0 
```

**Comment by rsese** [comment] 2018-03-19 21:15
Thanks for the report! Looks like this is a duplicate of #15263 and the fix I believe is in 1.26, currently in beta.  If you still see this error when you're on 1.26 please let us know.

**Closed by rsese** 2018-03-19 21:15 UTC
