### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by Lundblom** [atom/atom#7648] opened 2015-07-02 08:57 UTC
[Enter steps to reproduce below:]

1. Selected text
2. Right clicked it

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
    at HTMLDocument.handler (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\Programmerare\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -1:58 core:save (atom-text-editor.editor.is-focused)
     -1:12.2.0 core:copy (atom-text-editor.editor.is-focused)
  2x -1:08.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:07.9.0 core:paste (atom-text-editor.editor.is-focused)
     -1:07.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:36.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:36.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:36.4.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:31.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26 core:cut (atom-text-editor.editor.is-focused)
     -0:24.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:22.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:16.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:00.8.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "fileEncoding": "iso88591",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by kubetz** [comment] 2015-07-02 09:07
Duplicate of https://github.com/atom/atom/issues/6548. Will be fixed in next release.

**Comment by mnquintana** [comment] 2015-07-02 11:06
Thanks @kubetz!

**Closed by mnquintana** 2015-07-02 11:06 UTC
