### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by jorge8168711** [atom/atom#7781] opened 2015-07-08 06:14 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\JorgeEduardo\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -4:19.4.0 core:select-left (atom-text-editor.editor.is-focused)
     -4:16 core:move-down (atom-text-editor.editor.is-focused)
     -4:15.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:15.3.0 editor:move-line-down (atom-text-editor.editor.is-focused)
     -4:14.6.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -4:14.2.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -4:13.3.0 core:select-up (atom-text-editor.editor.is-focused)
     -4:09.1.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
  8x -4:06.5.0 core:undo (atom-text-editor.editor.is-focused)
     -4:01.9.0 editor:upper-case (atom-text-editor.editor.is-focused)
     -4:01.5.0 core:undo (atom-text-editor.editor.is-focused)
     -4:00.5.0 core:save (atom-text-editor.editor.is-focused)
     -3:59.7.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -2:26.3.0 settings-view:open (atom-text-editor.editor)
  9x -2:14.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -1:55 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".cfg"
    ],
    "projectHome": "C:\\Users\\JorgeEduardo\\Dropbox\\Apps\\GitHub"
  },
  "editor": {
    "invisibles": {
      "tab": false,
      "cr": false,
      "eol": false,
      "space": false
    },
    "fontFamily": "Roboto Mono",
    "scrollPastEnd": true,
    "scrollSensitivity": 60,
    "showInvisibles": true,
    "fontSize": 15,
    "tabLength": 4,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-jshint, v2.0.0
autocomplete-paths, v1.0.2
color-picker, v2.0.9
emmet, v2.3.12
git-log, v0.4.1
highlight-selected, v0.10.1
linter, v1.1.0
linter-stylint, v2.0.0
live-archive, v0.1.15
pigments, v0.8.3
project-manager, v1.15.11
selection-counter, v0.1.1
Stylus, v1.0.0
Sublime-Style-Column-Selection, v1.3.0
sublime-word-navigation, v0.1.2
tool-bar, v0.1.8
tool-bar-main, v0.0.8
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by thomasjo** [comment] 2015-07-08 07:11
Duplicate of https://github.com/atom/atom/issues/6548. Has been fixed in the upcoming release of Atom.

**Closed by thomasjo** 2015-07-08 07:11 UTC
