### ISSUE TITLE
Pressing alt destroys unsaved changes and entire tabs and undo buffer

### ISSUE THREAD

**Issue by niedzielski** [atom/atom#7238] opened 2015-06-11 21:17 UTC
Atom 0.208.0 on Linux Mint 17.1 Cinnamon

1. Go to a directory in the shell.
1. Launch atom from the shell.
1. Open a file.
1. Go down a couple screens in the file and type some rubbish without saving.
1. Press alt.
1. Observe that the menu is now visible, the unsaved changes in the file are destroyed, the undo buffer is cleared, and the cursor position resets to the first line in the file.

The above steps on an unsaved tab will actually destroy its contents and close it.

Screenshots (sorry, upload doesn't seem to be working for me today):
- Enter some rubbish in the buffer: https://img.bi/#/QvT4bXP!exmmkclbatacdtDfbcfaECGqJaWnnajdWyrzicur
- Tap alt and see the menu: https://img.bi/#/nbZT9ww!cyeabHOkhxqCozesEnozCaQdgpkwBsziDejKbbBw

I did not observe any errors in the dev console.

**Comment by thomasjo** [comment] 2015-06-11 21:24
Are you able to reproduce in safe mode? `atom --safe`

**Comment by niedzielski** [comment] 2015-06-11 21:38
@thomasjo, no, the issue does not repro in safemode.

**Comment by thomasjo** [comment] 2015-06-11 21:40
OK, that means it's almost surely caused by a community package. Can you please provide a list of installed packages; `apm list --installed` (or `apm list -i`)

**Comment by niedzielski** [comment] 2015-06-13 21:34
I'm a little perplexed as I tested disabling each package (except for the theme, which I switched) but the issue still occurred on each. Here's what I have installed:

├── hidpi@0.5.0
├── jshint@1.3.7
├── language-dart@0.2.0
├── language-fish-shell@1.0.2
├── language-gradle@0.0.3
├── language-mediawiki@2.0.0
├── linter-jshint@0.1.6
├── save-session@0.15.5
├── script@2.25.1
└── soda-light-ui@0.2.0

**Comment by kevinsawicki** [comment] 2015-07-31 16:20
Closing this out as it appears to be a third party package problem.

If you open the keybinding resolver using `ctrl-.` you should be able to see what commands are running when you press `alt` and that may show which package could be causing this behavior.

Please comment after trying this if this still appears to be a core Atom issue and we can reopen this.

**Closed by kevinsawicki** 2015-07-31 16:20 UTC
Labels: more-information-needed

**Comment by niedzielski** [comment] 2015-08-01 02:38
@kevinsawicki I tried again today and I'm sorry for posting earlier (but happy it's resolved), it was the hidpi plugin. As soon as I disabled that, things started working fine. Thanks for the help!
