### ISSUE TITLE
Uncaught Error: ENOTEMPTY: directory not empty, rmdir '/tmp/AtomLinter11565-7287-ykeinr'

### ISSUE THREAD

**Issue by cabellicar123** [atom/atom#7721] opened 2015-07-05 19:58 UTC
[Enter steps to reproduce below:]

1. Delete HTML file from file browser

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOTEMPTY: directory not empty, rmdir '/tmp/AtomLinter11565-7287-ykeinr'

```
At fs.js:55

Error: ENOTEMPTY: directory not empty, rmdir '/tmp/AtomLinter11565-7287-ykeinr'
  at Error (native)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  2x -1:09.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:09.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:57.7.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -0:56.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:53.7.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:53.3.0 core:move-left (atom-text-editor.editor.is-focused)
  9x -0:48.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:46.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:46.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:46.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:40.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:32.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:24.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:20.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:15.5.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Inconsolata-g for Powerline"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
autocomplete-clang, v0.7.0
autocomplete-php, v0.3.6
autocomplete-python, v0.5.1
autocomplete-ruby, v0.1.0
color-picker, v2.0.7
emmet, v2.3.12
file-icons, v1.5.8
hex, v0.6.2
jshint, v1.3.8
language-latex, v0.6.1
language-x86, v0.1.0
latex, v0.24.2
latexer, v0.2.3
linter, v1.1.0
linter-chktex, v0.3.2
linter-clang, v2.26.0
linter-csslint, v0.0.14
linter-htmlhint, v0.0.16
linter-javac, v0.1.4
linter-php, v0.0.15
linter-ruby, v0.1.6
linter-shellcheck, v0.0.8
linter-tidy, v1.0.1
minimap, v4.10.1
minimap-git-diff, v4.1.3
minimap-linter, v1.0.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by batjko** [comment] 2015-07-05 20:50
Since the error complains about a temporary Linter folder, it sounds like you're trying to delete a file that the Linter is still working on (I don't know how Linter works exactly, but I'm guessing the temp folder is holding information about that file and won't be released (emptied) until some operation is done.

Can you reproduce this more than once?

**Comment by kevinsawicki** [comment] 2015-07-08 16:37
This definitely looks like an linter bug that is being incorrectly marked as a core bug.

Going to close it out here since the stack trace does not contain enough information to reproduce to trace though why it occurred.

**Closed by kevinsawicki** 2015-07-08 16:37 UTC
Labels: more-information-needed, uncaught-exception
