### ISSUE TITLE
Valid code highlight breaks on long conditional (ternary) operator and in many familiar

### ISSUE THREAD

**Issue by qooob** [atom/atom#13709] opened 2017-01-28 18:55 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Highlighting of the valid code breaks
### Steps to Reproduce

1. Insert this code to your _.php_ files
```PHP
<?
/**
 *
 * Extract unique values ( from multidimensional array ) by using specific keys
 * @return array
 *
 */
function array_multi_unique_values($input_array, $v1, $v2 = false, $v3 = false, $v4 = false, $v5 = false, $v6 = false, $v7 = false, $v8 = false)
{
    if (is_array($input_array)) {
        $output_array = [];
        foreach ($input_array as $array) {
            $output_array[] = $array[$v1] . (!empty($array[$v2]) ? ', ' . $array[$v2] : false) . (!empty($array[$v3]) ? ', ' . $array[$v3] : false) . (!empty($array[$v4]) ? ', ' . $array[$v4] : false) . (!empty($array[$v5]) ? ', ' . $array[$v5] : false) . (!empty($array[$v6]) ? ', ' . $array[$v6] : false) . (!empty($array[$v7]) ? ', ' . $array[$v7] : false) . (!empty($array[$v8]) ? ', ' . $array[$v8] : false);
        }
        return array_unique($output_array);
    } else {
        return false;
    }
}
```
2. Set file type to PHP if necessary

**Expected behavior:** [What you expect to happen]
Code being highlighted the same way us on GitHub for example.

**Actual behavior:** [What actually happens]
It doesn't, here is the example in the screenshot:
![screenshot from 2017-01-28 21-48-22](https://cloud.githubusercontent.com/assets/4426533/22399025/75032a5e-e5a4-11e6-8c70-9a3bde34e60c.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
All the time

### Versions
Atom Editor v1.13.1

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information
Linux Fedora 25

**Comment by qooob** [comment] 2017-01-28 18:57
Another example:

![screenshot from 2017-01-28 21-56-19](https://cloud.githubusercontent.com/assets/4426533/22399030/ae67af9a-e5a4-11e6-80ef-93ec62438687.png)

**Comment by lee-dohm** [comment] 2017-01-28 21:40
Thank you for reaching out!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/1667. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2017-01-28 21:40 UTC
