### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ content already created'

### ISSUE THREAD

**Issue by zazazack** [atom/atom#18240] opened 2018-10-16 18:19 UTC
[Enter steps to reproduce:]

1. Drag and drop file to a folder in tree view

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ content already created'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/ content already created'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:343:29)
    at TreeView.module.exports.TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1544:34)
    at TreeView.module.exports.TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1844:37)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:389:30)
```

### Commands

```
     -0:32.7.0 core:move-down (input.hidden-input)
     -0:32.4.0 core:confirm (input.hidden-input)
     -0:32.4.0 tree-view:rename (input.hidden-input)
     -0:30.6.0 core:paste (input.hidden-input)
     -0:29.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:29.2.0 core:confirm (input.hidden-input)
     -0:27.9.0 command-palette:toggle (input.hidden-input)
     -0:27.2.0 editor:consolidate-selections (input.hidden-input)
     -0:27.2.0 core:cancel (input.hidden-input)
     -0:26.6.0 tree-view:toggle (input.hidden-input)
     -0:22.2.0 command-palette:toggle (div.tool-panel.tree-view)
     -0:19.5.0 editor:delete-to-beginning-of-line (input.hidden-input)
  2x -0:18.6.0 core:backspace (input.hidden-input)
     -0:16 core:confirm (input.hidden-input)
     -0:16 tree-view:add-folder (div.tool-panel.tree-view)
     -0:12.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
file-icons 2.1.25 
git-plus 8.1.0 
Hydrogen 2.6.0 
ide-docker 0.1.0 
ide-json 0.2.1 
ide-python 1.0.0 
language-caddyfile 0.1.7 
language-docker 1.1.8 
language-dot 1.7.0 
language-dotfiles 1.1.0 
language-fish-shell 1.1.0 
language-generic-config 1.4.0 
language-http 0.3.1 
language-log 1.10.1 
language-nginx 0.8.0 
language-openscad 0.4.3 
language-plantuml 0.2.0 
plantuml-viewer 0.7.2 
python-tools 0.6.9 
refactor 0.11.5 
rest-client 1.3.1 
script 3.18.1 
sort-lines 0.18.0 
```

**Comment by rsese** [comment] 2018-10-16 22:11
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-16 22:11 UTC
