### ISSUE TITLE
Pasting single line long string

### ISSUE THREAD

**Issue by boralp** [atom/atom#7629] opened 2015-07-01 15:36 UTC
In Mac OS X when you paste a minified file like jquery.min.js or bootstrap.min.css Atom crashes or stays unresponsive for a minute or two.

**Comment by mnquintana** [comment] 2015-07-01 15:38
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/979 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-01 15:38 UTC
