### ISSUE TITLE
BufferedProcess doesn't capture stdout past a certain threshold

### ISSUE THREAD

**Issue by lloeki** [atom/atom#8382] opened 2015-08-14 10:21 UTC
Currently developing the linter-markdownlint package, when running the mdl command and capturing its output, nothing is captured when, apparently, the output is too long.

Test case:

- clone linter-markdownlint package
- install prerequisites as indicated in the readme
- notice test.md gets proper linting on save
- notice README.md doesn't, while running the command mdl README.md manuall does produce output
- notice that copy-pasting content into test.md makes its behavior identical to README.md
- add `console.log(data)` in stdout handler and `console.log(code)` in exit handler
- notice that no output is captured when in the failing test case while the exit code being correctly reported as 1

Conclusion: varying amount of content produces increasing amount of linting errors, up to a certain threshold (under 18 lines or 889 characters) where nothing is being captured by BufferedProcess.

**Comment by maxbrunsfeld** [comment] 2015-08-14 16:40
I can't reproduce this yet. Test code:

From the Atom console:
```js
new (require("atom").BufferedProcess)({
  command: "tail",
  args: ["-f", "/tmp/some-file.txt"],
  stdout: function(out) { console.log("OUT", out); },
  stderr: function(out) { console.log("ERR", out); },
});
```

From the shell (as many times as desired):
```sh
$ for i in $(seq 1 1000); do echo line-$i >> /tmp/some-file.txt; done
```

As expected, I continue to see output in Atom no matter how much I write to the file from the terminal. @lloeki can you try reproducing the problem w/ a simpler setup, independent of the `linter-markdownlint` package?

**Comment by lloeki** [comment] 2015-08-17 15:00
Honestly, I thought so (following the adage about one's own code being at fault in face of supposed compiler bugs).

Ok, I have something now, While `mdl README.txt` works fine in the terminal, the following crashes:

```javascript
new (require("atom").BufferedProcess)({
  command: "mdl",
  args: ["/Users/lloeki/Workspace/projects/linter-markdownlint/README.md"],
  stdout: function(out) { console.log("OUT", out); },
  stderr: function(out) { console.log("ERR", out); },
});

// /Users/lloeki/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mdl-0.2.1/lib/mdl/doc.rb:31:in `split': invalid byte sequence in US-ASCII (ArgumentError)
// ---8<---
```

I added stderr logging to `linter-markdownlint` and sure enough, the same error. What misled me was that it was expected to return with exit code 1, so error'ing out was supposed to be normal... Such a gaping oversight on my part not to catch stderr :-/.

This points us here in mdl source code:

```
    ##
    # Create a new document given a string containing the markdown source
    def initialize(text)
      @lines = text.split("\n")
```

Seems like for some reason this `text` is containing invalid UTF-8.

I'll investigate my issue further but unless `BufferedProcess` is doing something whacky and transcodes stuff, it should not be at fault.

**Comment by lloeki** [comment] 2015-08-17 15:09
> Seems like for some reason this text is containing invalid UTF-8 although hacking my way into it and dumping the var doesn't produce useful results.

For the record, this is what I mean:

```ruby
# added this right at the start of `initialize`
File.open('/tmp/mdl.txt', 'wb') { |f| f.write(text) }
# in a terminal, after having saved `README.md` to trigger linter (with `mdl` crashing on the `split` line in `initialize`)
ruby -e "p File.read('/tmp/mdl.txt').split('\n')"
# and it works. just. fine. *stumped*.
```

Meanwhile,

```javascript
new (require("atom").BufferedProcess)({
  command: "ruby",
  args: ["-e", "p File.read('/tmp/mdl.txt').split('\n')"],
  stdout: function(out) { console.log("OUT", out); },
  stderr: function(out) { console.log("ERR", out); },
});
// ERR -e:1:in `split': invalid byte sequence in US-ASCII (ArgumentError)
//	from -e:1:in `<main>'
```

Something's amiss, but I can't put my finger on it yet.

**Comment by lloeki** [comment] 2015-08-17 15:22
@maxbrunsfeld I found the minimal test case:

```
$ ruby -e "p '“'.split('\n')"
["“"]
# works
```

```javascript
new (require("atom").BufferedProcess)({
  command: "ruby",
  args: ["-e", "p '“'.split('\n')"],
  stdout: function(out) { console.log("OUT", out); },
  stderr: function(out) { console.log("ERR", out); },
});
// fails
```

**Comment by maxbrunsfeld** [comment] 2015-08-17 16:22
@lloeki What output do you see when you say it fails? I see this:

```js
OUT ["“"]
```

This is what I would expect.

**Comment by lloeki** [comment] 2015-08-17 16:27
This:

```
ERR -e:1:in `split': invalid byte sequence in US-ASCII (ArgumentError)
  from -e:1:in `<main>'
```

Your output is what's expected.

**Comment by maxbrunsfeld** [comment] 2015-08-17 16:46
It seems like your `ruby` is using `US-ASCII` as its default encoding, instead of `UTF-8`. It's interesting that it works when you run it from the command line. It could be due to a difference in environment variables. Can you try this?

```js
var _ = require("underscore-plus");

new (require("atom").BufferedProcess)({
  command: "ruby",
  args: ["-e", "p '“'.split('\n')"],
  options: {
    env: _.defaults({
      LANGUAGE: "en_US.UTF-8",
      LANG: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    }, process.env)
  },
  stdout: function(out) { console.log("OUT", out); },
  stderr: function(out) { console.log("ERR", out); },
});
```

**Comment by maxbrunsfeld** [comment] 2015-08-17 16:49
On my system, setting the `LC_ALL` environment variable to `en_US.ASCII` causes the same error that you're reporting.

**Comment by lloeki** [comment] 2015-08-17 17:45
Had that hunch too, ran that previously:

```javascript
new (require("atom").BufferedProcess)({
  command: "ruby",
  args: ["-e", "p ENV"],
  stdout: function(out) { console.log("OUT", out); },
  stderr: function(out) { console.log("ERR", out); },
});
```

which outputs:

```
OUT {"TMPDIR"=>"/var/folders/4h/gxzl7q_s3xbbrpzmtx47qlz40000gn/T/", "__CF_USER_TEXT_ENCODING"=>"0x1F5:0x0:0x0", "SHELL"=>"/bin/zsh", "HOME"=>"/Users/lloeki", "Apple_PubSub_Socket_Render"=>"/private/tmp/com.apple.launchd.dwaMRchGAj/Render", "SSH_AUTH_SOCK"=>"/private/tmp/com.apple.launchd.DVGnG2HIvX/Listeners", "PATH"=>"/usr/bin:/bin:/usr/sbin:/sbin", "LOGNAME"=>"lloeki", "XPC_SERVICE_NAME"=>"0", "USER"=>"lloeki", "XPC_FLAGS"=>"0x0", "GOOGLE_API_KEY"=>"//**redacted**//", "ATOM_HOME"=>"/Users/lloeki/.atom", "NODE_PATH"=>"/Applications/Atom.app/Contents/Resources/app.asar/exports", "NODE_ENV"=>"production"}
```

Setting LC_ALL works, but doing it manually feels like a crutch. It should be something Atom does.

I nailed the difference in behaviour. Case 1:
- quit Atom entirely
- start Atom with the app icon
- run ruby -e 'p ENV' from a BufferedProcess
- notice the env is pristine

vs Case 2:
- quit Atom entirely
- start Atom with `atom` from terminal.
- run ruby -e 'p ENV' from a BufferedProcess
- notice the env is littered with vars from the terminal

Damn. I [warned about that](https://github.com/atom/atom/issues/4126) myself a few times already and just got bitten my it. Atom should *really* always behave the same WRT env vars, that is behave as being launched from `launchd`, i.e, with a pristine env. This is critical as what matters is the first instance of Atom being opened, and whatever subsequent instance is opened will get the behaviour of the first one ever opened since the last quit.

**Comment by maxbrunsfeld** [comment] 2015-08-17 17:54
OK, I'm going to close this out, since this problem is a special case of your earlier issue about inheriting environment variables. I agree it would be great to fix that. If you're interested in helping to solve that issue, I'd love to merge a PR that fixes it, even if just fixes it for OSX.

**Closed by maxbrunsfeld** 2015-08-17 17:54 UTC
Labels: more-information-needed, needs-reproduction

**Comment by lloeki** [comment] 2015-08-17 17:58
Thanks for your assistance @maxbrunsfeld. I'll look into the parent issue.

**Comment by lloeki** [comment] 2015-08-18 09:48
Workaround:

```coffee
new (require("atom").BufferedProcess)
  command: "osascript"
  args: ["-e", "user locale of (get system info)"]
  stdout: (out) ->
    m = /^([a-z]{2}_[A-Z]{2})/.exec(out)
    process.env.LANG = "#{m[1]}.UTF-8" if m?
```
