### ISSUE TITLE
Can't Paste Large Amount of Text - "Uncaught RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by kamyarinfinity** [atom/atom#14468] opened 2017-05-18 01:55 UTC
### Prerequisites

* [X] I have checked the following:
    * [X] The problem didn't happen in Safe Mode, but disabling packages didn't change anything.
    * [X] Followed all applicable steps in the debugging guide.
    * [X] Checked the FAQs on the message board for common solutions.
    * [X] I couldn't find my issue. Though, atom reported this issue is already reported, that problem was about saving to network, and I couldn't see any similarity.

### Description

Pasting a large amount of text leads to `Maximum call stack size exceeded`.
Full Stack Trace:

```
Uncaught RangeError: Maximum call stack size exceeded
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833

RangeError: Maximum call stack size exceeded
    at Object.spliceWithArray (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:362:46)
    at TokenizedBuffer.module.exports.TokenizedBuffer.bufferDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:278:18)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:671:36
    at Set.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:670:33)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:664:12)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:557:19)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:480:43)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3023:31
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1161:28
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1594:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1155:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2572:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2534:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1153:19)
    at TextEditor.module.exports.TextEditor.pasteText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2996:19)
    at TextEditor.core:paste (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:437:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:666:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1594:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:665:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Steps to Reproduce

1. Copy a large amount of text (around 4MB)
2. Paste inside a new tab (with Plain Text syntax)

**Expected behavior:** You should see the text.

**Actual behavior:** An exception is thrown and the text is not pasted.

**Reproduces how often:** Always

### Versions

This my Atom version. I see there's also a new 1.17, which the autoupdate doesn't detect yet. I couldn't see any resolved issues that was about this error, so I assume nothing has changed.

> Atom    : 1.16.0
> Electron: 1.3.13
> Chrome  : 52.0.2743.82
> Node    : 6.5.0

### Additional Information

I don't have any content inside `init.coffee`, and most of the packages I have are supposed to be used when a specific syntax is present (not for plain text). I tried disabling some of the 3rd party ones, and even some of the core ones, but none of them changed anything. Anyway, the stack trace didn't show any 3rd-party package involved in the exception, so I think there's something extra happening when Atom is not run in Safe Mode.

**Comment by 50Wliu** [comment] 2017-05-18 02:18
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #4767. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-18 02:18 UTC
