### ISSUE TITLE
Cannot save a file in a remote folder through FTP

### ISSUE THREAD

**Issue by cisoun** [atom/atom#6555] opened 2015-04-28 13:50 UTC
This happens when I'm trying to write a file directly in a remote FTP directory.

1. Try to open a remote FTP folder through Nautilus (Linux/Gnome).
2. Open a file from this folder with Atom.
3. Write something and save.

**Atom Version**: 0.194.0
**System**: linux 3.19.3-3-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ESPIPE: invalid seek, write

```
At /usr/share/atom/resources/app.asar/src/pane.js:759

Error: ESPIPE: invalid seek, write
  at Error (native)
  at Object.fs.writeSync (fs.js:657:20)
  at Object.fs.writeFileSync (fs.js:1164:21)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:240:17)
  at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:264:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:362:21)
  at File.module.exports.File.writeSync (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:336:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:913:17)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:554:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:574:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:310:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:01.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "autoHideMenuBar": true,
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Monaco",
    "showIndentGuide": true,
    "tabLength": 4,
    "useShadowDOM": true,
    "invisibles": {},
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-beautify, v0.24.1
atom-html-preview, v0.1.6
atomui, vundefined
autoclose-html, v0.15.0
color-picker, v1.7.0
docblockr, v0.6.3
html-helper, v0.2.3
laravel, v0.4.2
script, v2.19.0
terminal-panel, v1.10.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-04-28 14:09
This looks like a duplicate of #2539 - please subscribe there for updates.

**Closed by mnquintana** 2015-04-28 14:09 UTC
