### ISSUE TITLE
The status bar (window name) is light when the application uses a dark theme

### ISSUE THREAD

**Issue by Rakleed** [atom/atom#19450] opened 2019-06-05 14:00 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The status bar (window name) is light when the application uses a dark theme.

### Steps to Reproduce

1. Open Atom

**Expected behavior:** The status bar (window name) is dark.

**Actual behavior:** The status bar (window name) is light.

**Reproduces how often:** 100 %

### Versions
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
Windows : 10 v. 1903

### Additional Information
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19418601/58962174-4e0ecf80-87b3-11e9-9e6c-ab074097a74a.png)

</details>

**Comment by rsese** [comment] 2019-06-05 21:28
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/13249 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-05 21:28 UTC
