### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by lacsus** [atom/atom#20083] opened 2019-10-29 14:41 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:160

Error: dlopen(/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app/static/<embedded>:1:688212)
    at get_KeyboardLayoutManager (/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2743819)
    at get_manager (/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2743921)
    at Object.getCurrentKeyboardLayout (/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2744047)
    at e.keystrokeForKeyboardEvent (/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1087018)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1249633)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1247618)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/bw/56_pv5vn1rdchd9585kr4dmc0000gn/T/AppTranslocation/B49221B5-FA64-4AA0-B3CF-B695F1A3BE5F/d/Atom.app/Contents/Resources/app/static/<embedded>:11:284598)
```

### Commands

```
     -7:29.9.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -7:27.4.0 encoding-selector:show (atom-text-editor.editor.is-focused)
     -7:25.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -6:36.1.0 application:add-project-folder (div.tool-panel.tree-view)
  2x -5:12.2.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:34.4.0 grammar-selector:show (atom-text-editor.editor)
```

### Non-Core Packages

```

```

**Comment by sadick254** [comment] 2020-09-16 19:01
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-16 19:01 UTC
