### ISSUE TITLE
Text in Text Field Not Visible when used with VMware Fusion

### ISSUE THREAD

**Issue by vgrsec** [atom/atom#17135] opened 2018-04-13 21:46 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When attempting to type text into text fields when Atom is installed on MacOS running on VMware Fusion, text doesn't appear. 

### Steps to Reproduce

1. Install MacOS on VMware Fusion 10.1.1 (7520154) - Latest
2. Install Atom 1.25.1 or Atom Beta
3. Find -> Find in Buffer
4. Type

**Expected behavior:** [What you expect to happen]

The typed characters to appear

**Actual behavior:** [What actually happens]

Nothing appears, but the text does get recorded in the text field

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

MacOS 10.12.6 through 10.13.4
Atom 1.25.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Reproduction videos

Atom on 10.13.0 with latest VMWare Fusion & without Tools installed
https://www.youtube.com/watch?v=Wmrs8T64Uro

Atom on 10.13.4 with latest VMWare Fusion & Tools installed
https://www.youtube.com/watch?v=QXXZLDVx5zo

Atom on 10.12.6 with latest VMWare Fusion & without Tools installed
https://www.youtube.com/watch?v=gD5XIqcnPgE

Atom on 10.12.6 with latest VMWare Fusion & Tools installed
https://www.youtube.com/watch?v=tSkXST7pKBU

**Comment by lee-dohm** [comment] 2018-04-13 21:56
Thank you for your submission!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17094. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2018-04-13 21:56 UTC
