### ISSUE TITLE
Uncaught Error: Cannot read property 'isFullScreen' of undefinedTypeError: Cannot read property ...

### ISSUE THREAD

**Issue by mgild** [atom/atom#11982] opened 2016-06-15 00:15 UTC
[Enter steps to reproduce below:]

1. Opened atom
2. Attempted to add a remote project (Nuclide is installed)

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'isFullScreen' of undefined
TypeError: Cannot read property 'isFullScreen' of undefined
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:295:35)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:113

Error: Cannot read property 'isFullScreen' of undefined
TypeError: Cannot read property 'isFullScreen' of undefined
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:295:35)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
  at metaToValue (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:113:13)
  at BrowserWindow.RemoteMemberFunction [as isFullScreen] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:204:16)
  at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:103:40)
  at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:588:39)
  at AtomEnvironment.module.exports.AtomEnvironment.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:775:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:984:27

```

### Commands

```
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "TARGETS",
        "cconf",
        "cinc",
        "mcconf",
        "tw",
        "BUCK"
      ]
    },
    "disabledPackages": [
      "metrics",
      "fuzzy-finder",
      "tree-view"
    ]
  },
  "editor": {
    "fontSize": 11,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.28.0
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.142.31531189
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-06-15 12:41
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-15 12:41 UTC
