### ISSUE TITLE
Scrolling Markdown source code should also scroll preview

### ISSUE THREAD

**Issue by scls19fr** [atom/atom#7891] opened 2015-07-14 13:41 UTC
Hello,

I'm new to Atom. It's a great app.
But I'm looking for a feature to edit Markdown.

Scrolling Markdown source code should also scroll preview
(and also inverse)

At least 2 modes should exists:

 - follow top
 - follow bottom

Kind regards

**Comment by mnquintana** [comment] 2015-07-14 13:54
Thanks for the suggestion! This is a duplicate of https://github.com/atom/markdown-preview/issues/24 – please subscribe there for updates.

(Also, for future reference, the Markdown previewing functionality is provided by a separate repo, [atom/markdown-preview](https://github.com/atom/markdown-preview), rather than atom/atom.)

**Closed by mnquintana** 2015-07-14 13:54 UTC

**Comment by scls19fr** [comment] 2015-07-14 13:57
Sorry thanks

**Comment by mark-hahn** [comment] 2015-07-14 15:12
I have a package called `markdown-scroll-sync`.

**Comment by scls19fr** [comment] 2015-07-14 15:34
Thanks.
