### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/developer3/Desktop/Atom.app'

### ISSUE THREAD

**Issue by avdienko** [atom/atom#10100] opened 2015-12-17 07:57 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/developer3/Desktop/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/developer3/Desktop/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/developer3/Desktop/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -4:50.2.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
  2x -4:46.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:45 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -4:44.5.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -4:43.3.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -4:21.2.0 open-on-github:repository (atom-text-editor.editor.is-focused)
     -1:43.4.0 grammar-selector:show (atom-text-editor.editor)
     -1:38.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:35.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:32.9.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:31.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:31.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 13x -1:26.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:14.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:13.6.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -1:09.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-17 12:51
Closing as a duplicate of #9813 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-17 12:51 UTC
