### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by jellenelis** [atom/atom#15256] opened 2017-08-11 10:01 UTC
[Enter steps to reproduce:]

1. Click anywhere on the Atom window
2. 2 notifications pop up
3. Closing the notifications with Close All shows 2 new notifications, one saying it is a bug in Atom, one saying it is coming from linter-ui-default

Possible duplicate of #15093

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /usr/share/atom/resources/app/node_modules/react-dom/lib/EventPluginUtils.js:97

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/usr/share/atom/resources/app/node_modules/react-dom/lib/EventPluginUtils.js:97:11)
    at executeDispatchesAndRelease (/usr/share/atom/resources/app/node_modules/react-dom/lib/EventPluginHub.js:43:28)
    at executeDispatchesAndReleaseTopLevel (/usr/share/atom/resources/app/node_modules/react-dom/lib/EventPluginHub.js:54:16)
    at Array.forEach (native)
    at forEachAccumulated (/usr/share/atom/resources/app/node_modules/react-dom/lib/forEachAccumulated.js:24:15)
    at Object.processEventQueue (/usr/share/atom/resources/app/node_modules/react-dom/lib/EventPluginHub.js:254:13)
    at runEventQueueInBatch (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:24)
    at Object.handleTopLevel [as _handleTopLevel] (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:27:11)
    at handleTopLevelImpl (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactEventListener.js:72:30)
    at ReactDefaultBatchingStrategyTransaction.perform (/usr/share/atom/resources/app/node_modules/react-dom/lib/Transaction.js:143:26)
    at Object.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactUpdates.js:97:33)
    at dispatchEvent (/usr/share/atom/resources/app/node_modules/react-dom/lib/ReactEventListener.js:147:26)
```

### Commands

```
     -2:03.3.0 intentions:highlight (input.hidden-input)
     -2:03.2.0 core:paste (input.hidden-input)
  2x -2:01.2.0 core:backspace (input.hidden-input)
     -1:59.9.0 core:delete (input.hidden-input)
     -1:59.5.0 intentions:highlight (input.hidden-input)
     -1:59 core:save (input.hidden-input)
  2x -1:32.3.0 intentions:highlight (input.hidden-input)
     -1:29.9.0 core:backspace (input.hidden-input)
     -1:29.7.0 intentions:highlight (input.hidden-input)
     -1:29.5.0 core:save (input.hidden-input)
  2x -1:17.2.0 meteor-helper:toggle (p.)
     -0:17.7.0 editor:newline (input.hidden-input)
     -0:15.5.0 core:move-right (input.hidden-input)
  2x -0:14.9.0 core:move-left (input.hidden-input)
     -0:06.3.0 intentions:highlight (input.hidden-input)
     -0:06.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-typescript 11.0.6 
busy-signal 1.4.3 
formatter 2.12.4 
intentions 1.1.5 
linter 2.2.0 
linter-tslint 1.7.0 
linter-ui-default 1.6.4 
meteor-helper 0.29.0 
```

**Comment by rsese** [comment] 2017-08-11 17:54
Yeah based on the stack trace I think it's a duplicate of https://github.com/atom/atom/issues/15093 :+1:

Based on your steps to repro, I'm guessing it's not reproducible in safe mode but feel free to drop more details in https://github.com/atom/atom/issues/15093.

**Closed by rsese** 2017-08-11 17:54 UTC
