### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Nickismyname/Downloads/Atom.app'

### ISSUE THREAD

**Issue by Nickismyname** [atom/atom#11974] opened 2016-06-13 23:09 UTC
[Enter steps to reproduce below:]

1. ...downloaded Atom, moved to Applications folder
2. ...wrote some text
3....went to packages-->markdown preview-->toggle preview

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Nickismyname/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/Nickismyname/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:314:24)
    at toRealPath (module.js:113:13)
    at Function.Module._findPath (module.js:153:20)
    at Module._resolveFilename (module.js:336:25)
    at Function.Module._resolveFilename (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/Nickismyname/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
```

### Commands

```
     -2:36.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:20.3.0 pane:split-up (atom-text-editor.editor.is-focused)
     -2:18.6.0 core:undo (atom-pane.pane.active)
     -2:09.0 pane:close (atom-pane.pane.active)
     -1:02.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:12.8.0 open-on-github:branch-compare (atom-text-editor.editor.is-focused)
     -0:00.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-06-14 00:04
This is a duplicate of #10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-14 00:04 UTC
