### ISSUE TITLE
Hungarian keyboard layout problems

### ISSUE THREAD

**Issue by ownsideup** [atom/atom#12598] opened 2016-09-03 17:25 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? Yes.
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository]  (https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

On the Hungarian keyboard, we use Alt+F for the character [, and it is registered as a hotkey, and I can't remove it.

### Steps to Reproduce

1. Press Alt+F

**Expected behavior:** It would type a [ character

**Actual behavior:** It did nothing

### Versions

Atom: 1.10.0
Windows 10 Pro 64bit

**Comment by 50Wliu** [comment] 2016-09-03 20:13
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-03 20:13 UTC
