### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by ajay5121992** [atom/atom#16881] opened 2018-03-05 04:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At C:\Users\ajay.sharma2\AppData\Local\atom\app-1.24.0\resources\app\src\text-editor-component.js:2290

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2279:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:2272:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:400:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.24.0/resources/app/src/text-editor-component.js:278:20)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.24.0/resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -3:07.5.0 core:paste (input.hidden-input)
  2x -3:04.9.0 editor:newline (input.hidden-input)
     -2:57.9.0 core:paste (input.hidden-input)
  2x -2:49.7.0 editor:newline (input.hidden-input)
     -2:48.7.0 core:paste (input.hidden-input)
  3x -2:15.9.0 editor:newline (input.hidden-input)
     -2:14.1.0 core:paste (input.hidden-input)
  4x -2:09.3.0 editor:newline (input.hidden-input)
  7x -1:53.9.0 core:undo (input.hidden-input)
     -1:32.5.0 core:paste (input.hidden-input)
  2x -1:23.9.0 core:backspace (input.hidden-input)
  6x -1:19.1.0 core:move-down (input.hidden-input)
  2x -1:09.7.0 core:select-down (input.hidden-input)
 13x -1:08.3.0 core:select-right (input.hidden-input)
     -0:58.6.0 core:backspace (input.hidden-input)
     -0:43.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by ajay5121992** [comment] 2018-03-05 04:24
Issue occured while copying

**Comment by rsese** [comment] 2018-03-05 20:11
Thanks for the report!  Looks like this is a duplicate of https://github.com/atom/atom/issues/15263 and the [fix](https://github.com/atom/atom/pull/15831) will be available in an upcoming release.

**Closed by rsese** 2018-03-05 20:11 UTC
