### ISSUE TITLE
Cant update Atom due to permission denied

### ISSUE THREAD

**Issue by masiama** [atom/atom#13984] opened 2017-03-11 12:11 UTC
### Prerequisites

* Was unable to find an existing issue with solution that works for me

### Description

Trying to update atom with GUI

<img width="553" alt="2017-03-11 14 08 14" src="https://cloud.githubusercontent.com/assets/14037820/23823118/34fd23a2-0664-11e7-8f4b-f6608a55dfa4.png">

### Steps to Reproduce

1. Click on squirrel
2. Click on Check now

**Expected behavior:** Atom updated

**Actual behavior:** Error while updating

**Reproduces how often:** 100%

### Versions

Atom: 1.14.4

Electron: 1.3.13

Chrome: 52.0.2743.82

Node: 6.5.0

macOS: 10.12.3

### Additional Information

tried to execute `sudo chown -R $USER ~/Library/Application\ Support/com.github.atom.ShipIt`

`chown: /Users/masiama/Library/Application Support/com.github.atom.ShipIt: No such file or directory`

**Comment by rsese** [comment] 2017-03-12 06:26
Thanks for the report!  It looks like you found https://github.com/atom/atom/issues/5160?  Going to go ahead and close this as a dupe of that issue.  Even though it seems like some users had some success running that `sudo chown`, the issue is still open so that's the best place to subscribe for updates.

**Closed by rsese** 2017-03-12 06:26 UTC

**Comment by masiama** [comment] 2017-03-12 10:12
This didn't help cause there is no such folder `~/Library/Application\ Support/com.github.atom.ShipIt`

**Comment by masiama** [comment] 2017-03-12 10:14
In `~/Library/Application\ Support` is only Atom folder but using `sudo chown` to that folder also didn't help

**Comment by rsese** [comment] 2017-03-12 20:13
Yeah it looks like some people ran into the same thing as you when trying to run that command but that issue will be the place to subscribe since the issue is the same and it's still open.

**Comment by rsese** [comment] 2017-03-14 18:06
@masiama - from https://github.com/atom/atom/issues/13984 I saw a link to this FAQ item from the Atom Discuss forum:

https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054

Can you run through that as well?  In particular, it mentions a second directory to check, `~/Library/Caches/com.github.atom.ShipIt`.

If that still doesn't fix the problem for you, then I'd suggest subscribing to https://github.com/atom/atom/issues/13984 for updates.

**Comment by masiama** [comment] 2017-03-14 18:15
Using `~/Library/Caches/com.github.atom.ShipIt` updating succeeded. Thanks for help

**Comment by rsese** [comment] 2017-03-14 18:25
Awesome, glad that worked for you  🙌
