### ISSUE TITLE
Invalid keybindings on non-US keyboard layouts

### ISSUE THREAD

**Issue by UmkaDK** [atom/atom#19426] opened 2019-05-31 16:26 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Typing inside the editor on a UK-layout keyboard works as expected. However, keybindings assigned to `` ` `` and ` ~ ` keys do not work, because the keys are resolved to the wrong characters:

<img width="723" alt="Screenshot 2019-05-31 at 18 04 18" src="https://user-images.githubusercontent.com/2833247/58718856-ad916780-83ce-11e9-8183-04ff1a8645ed.png">

### Steps to Reproduce

Do the following on a mac with a UK keyboard:

1. `mv ~/.atom ~/.atom~`
2. `atom --safe --clear-window-state`
3. Cmd-.
4. Ensure that the focus is in the editor window
5. Press `` ` `` and observe the key reported by the Key Binding Resolver being different to the one that gets typed in the editor.

**Expected behaviour:** The key reported by Key Binding Resolver should match the key that gets typed in the editor.

**Actual behavior:** The key reported by the Key Binding Resolver differs from the one that gets typed in the editor.

**Reproduces how often:** 100%

### Versions

macOS 10.14.5

Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.37.0
python 2.7.16
git 2.20.1

### Additional Information

Old, but somewhat relevant issues:
- https://github.com/atom/atom/issues/6091
- https://github.com/atom/atom-keymap/issues/35
- https://github.com/atom/atom-keymap/issues/37

Old, but somewhat relevant PR:
- https://github.com/atom/atom/pull/12697

**Comment by rsese** [comment] 2019-05-31 19:39
Thanks for contributing!

I believe this is a duplicate of https://github.com/atom/atom/issues/19168?  You can subscribe there for updates if you'd like though let me know if you think the issue is different.  From the comments, looks like this is an Electron issue, see https://github.com/atom/atom/issues/19168#issuecomment-490064826 for more details.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-05-31 19:39 UTC
