### ISSUE TITLE
.html files without <body> element explode

### ISSUE THREAD

**Issue by njakobsen** [atom/atom#16820] opened 2018-02-22 17:55 UTC
1. create a file with a `.html` extension using the project tree view

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.registry.startIdForScope is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324

TypeError: this.registry.startIdForScope is not a function
    at Grammar.module.exports.Grammar.startIdForScope (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:324:34)
    at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:150:32)
    at TextMateLanguageMode.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:407:50)
    at TextMateLanguageMode.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:402:23)
    at TextMateLanguageMode.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:290:47)
    at _.defer (/Applications/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:274:63)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -3:44.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -3:43.5.0 editor:consolidate-selections (input.hidden-input)
     -3:43.5.0 core:cancel (input.hidden-input)
     -3:04.2.0 core:paste (input.hidden-input)
     -2:26.7.0 core:close (input.hidden-input)
     -2:25.4.0 pane:show-item-1 (input.hidden-input)
     -2:24.6.0 pane:show-item-3 (input.hidden-input)
     -0:09.9.0 pane:show-item-1 (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-dark-ui)
     -0:09.5.0 pane:show-item-2 (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-dark-ui)
     -0:08.8.0 pane:show-item-3 (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-dark-ui)
     -0:08.1.0 pane:show-item-4 (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-dark-ui)
     -0:07.7.0 pane:show-item-5 (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-underscore 0.1.3 
busy-signal 1.4.3 
change-case 0.6.5 
intentions 1.1.5 
pigments 0.40.2 
recent-files-fuzzy-finder 0.4.0 
rspec 0.4.0 
```

**Comment by Ben3eeE** [comment] 2018-02-22 20:01
@njakobsen Thanks for reporting this 🙇 

Can you reproduce the issue in safe mode `atom --safe`? If you can't this is most likely caused by a community package. Looking at the list of packages you have installed `atom-underscore` seems likely since it's for HTML files.

**Comment by revelt** [comment] 2018-02-22 21:23
I tried to recreate this issue on my latest beta Atom, no luck. I can create whatever HTML I want.

Then I tried installing `atom-underscore`. After first reboot I get error message, never-seen before:

<img width="469" alt="screen shot 2018-02-22 at 21 20 23" src="https://user-images.githubusercontent.com/8344688/36564793-6c8f6acc-1816-11e8-8b58-25015f1f46b3.png">

It must be an issue with `atom-underscore`. Especially since the last entry in stack trace point to `underscore.js`!

Should we move this issue to `atom-underscore`?

**Comment by njakobsen** [comment] 2018-02-23 02:58
Yeah, I disabled that package and restarted Atom. Problem solved. It's too bad, because the files I was having problems with were the underscore template files ><

**Comment by 50Wliu** [comment] 2018-02-23 02:58
Closing as this bug should be filed on the underscore package repo.

**Closed by 50Wliu** 2018-02-23 02:58 UTC

**Comment by njakobsen** [comment] 2018-02-23 03:00
For reference, here is the ticket in atom-underscore https://github.com/dborstelmann/atom-underscore/issues/4.

**Comment by njakobsen** [comment] 2018-02-23 03:01
What's strange though is that this only recently started happening. I was able to create those underscore template files without any issues until sometime in the last week.

**Comment by Ben3eeE** [comment] 2018-02-23 07:57
> What's strange though is that this only recently started happening. I was able to create those underscore template files without any issues until sometime in the last week.

Most likely is that this package is using a private `atom.grammars` API function. These changed in Atom 1.25 because of the tree-sitter integration,

**Comment by dborstelmann** [comment] 2018-03-02 13:20
@Ben3eeE you have any advice on where in this code the error may be?  I'm sure it's between 153-169 but I haven't been working on this package for 2 years and have not kept up with the latest Atom updates.

https://github.com/dborstelmann/atom-underscore/blob/master/lib/atom-underscore.js

**Comment by Arcanemagus** [comment] 2018-03-02 17:17
It looks like that code must have been written before the Grammar stuff was added to the public API? I don't have any experience with it myself, but it looks like you need to move your [`grammarJSON`](https://github.com/dborstelmann/atom-underscore/blob/53af6d2422604e76b6d3fd74894e74110c3fbc49/lib/atom-underscore.js#L83-L151) object out into a separate file and then use [`atom.grammars.loadGrammar`](https://atom.io/docs/api/v1.24.0/GrammarRegistry#instance-readGrammar) to have Atom itself parse and load the file into the registry for you. Note that this means you can also drop the [`Grammar` require](https://github.com/dborstelmann/atom-underscore/blob/53af6d2422604e76b6d3fd74894e74110c3fbc49/lib/atom-underscore.js#L1) which is causing [this error](https://github.com/atom/atom/issues/16820#issuecomment-367826643).

That will just get your `Grammar` added through the Public API though, I'm not seeing where in the code that stack trace is actually being triggered myself, but it could be something that loading the `Grammar` normally will fix for you?

**Comment by Ben3eeE** [comment] 2018-03-02 19:33
@dborstelmann @Arcanemagus Has some good comments on how you can improve the overall design. Thank you @Arcanemagus 🙇 

For the exception you see: You make a call to `atom.textEditor.maintainGrammars`. This function is now deprecated and the shim appears to not be working correctly in recent releases of Atom, which is something that should be fixed. You can try changing that to `atom.grammars.maintainLanguageMode` which may fix this exception. I can't test myself because I also have the problem mentioned in https://github.com/atom/atom/issues/16820#issuecomment-367826643

/cc: @maxbrunsfeld
