### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by nacr-dev** [atom/atom#7543] opened 2015-06-29 10:43 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
    at HTMLDocument.handler (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\nuno.rodrigues\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -2:52.7.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:52.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:41.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:41 core:save (atom-text-editor.editor.is-focused)
  2x -2:04.8.0 core:copy (atom-text-editor.editor.is-focused)
  4x -1:18.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:05.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:04.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:02.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:59.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:59 core:move-up (atom-text-editor.editor.is-focused)
     -0:53.8.0 core:copy (atom-text-editor.editor.is-focused)
     -0:49.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:40.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:37.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "terminal-panel",
      "atom-terminal-panel"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
laravel, v0.7.0
minimap, v4.10.1
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by batjko** [comment] 2015-06-29 11:57
Dupe of the also just opened #7542.

**Comment by izuzak** [comment] 2015-06-29 11:59
This is a duplicate of #6548, so closing this in favor of that issue.

**Closed by izuzak** 2015-06-29 11:59 UTC
