### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by david115599** [atom/atom#21159] opened 2020-08-08 02:34 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:160

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778162)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778264)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778390)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1081110)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1253631)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1251616)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284744)
```

### Commands

```
     -9:09.3.0 tree-view:show-in-file-manager (span.name.icon.icon-file-pdf)
     -0:40.5.0 core:paste (input.hidden-input)
     -0:28.3.0 core:undo (input.hidden-input)
     -0:22 core:close (input.hidden-input)
     -0:13.9.0 core:paste (input.hidden-input)
     -0:12.1.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ide-debugger-node 0.7.3 
atom-ide-ui 0.13.0 
atom-live-server-plus 3.0.1 
atom-nodejs-snippets 2.1.1 
atom-python-run 0.9.7 
auto-indent 0.5.0 
autocomplete-clang 0.13.1 
beautify 0.33.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.41 
ide-c-cpp 0.1.0 
ide-html 0.6.0 
ide-java 0.9.0 
ide-python 1.5.0 
intentions 1.1.5 
language-ini 1.23.0 
language-tex 0.4.0 
latex 0.50.2 
linter 2.3.1 
linter-gcc 0.9.0 
linter-ui-default 1.8.1 
node-debugger 1.10.1 
node-on-fire 0.1.0 
platformio-ide-terminal 2.10.0 
processing 0.13.0 
spell-check-project 0.7.0 
teletype 0.13.4 
tex-color 0.7.2 
tool-bar 1.3.0 
Youtube-and-chill 0.1.2 
```

**Comment by sadick254** [comment] 2020-09-01 16:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-01 16:22 UTC
