### ISSUE TITLE
Used inside WSL - `Settings` -> `Packages` page is displaying `Loading packages...` forever

### ISSUE THREAD

**Issue by razvan-panda** [atom/atom#19823] opened 2019-08-21 14:19 UTC
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When launching Atom inside WSL + VcXsrv the `Settings` -> `Packages` page is displaying `Loading packages...` forever.

### Steps to Reproduce

1. Install WSL
2. Install VcXsrv
3. Install Atom
4. Launch Atom

**Expected behavior:**

I would expect to be able to see installed packages and the ones that can be installed.

**Actual behavior:**

`Settings` -> `Packages` page is displaying `Loading packages...` forever.

**Reproduces how often:**

Always.

### Versions

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

```shell
neo@DESKTOP-R88JKVQ:/mnt/c/WINDOWS/system32$ apm --version
/usr/bin/apm: line 54: /usr/share/atom/resources/app/apm/bin/node.exe: No such file or directory
```

**Comment by rsese** [comment] 2019-08-21 20:17
Thanks for contributing!

Though we don't officially support Atom installed through WSL, we noticed that this looks like a duplicate of https://github.com/atom/atom/issues/19610 so you can subscribe there for updates if you'd like.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-21 20:17 UTC
