### ISSUE TITLE
Missing Japanese characters completely

### ISSUE THREAD

**Issue by freed00m** [atom/atom#7322] opened 2015-06-17 15:41 UTC
I have no jap charakters also in UTF-8. (Linux Mint 17.1)

I didn't choose any font family in settings.

![screenshot](https://cloud.githubusercontent.com/assets/9461698/8187455/11ce610a-1450-11e5-8b05-4bbc9e8ded53.png)

for example this 
"TITLE_LOST_NEW": "新遺失",
"TITLE_LOST_EDIT": "遺失修正",
"TITLE_LOST_DETAIL": "遺失詳細",
"TITLE_LOSTS_PAIRS": "対で遺失",
"TITLE_LOSTS_MY": "個人の遺失",
"TITLE_LOSTS": "遺失",

*** Here is my additional information ***

$ atom --version
0.209.0

---

$ apm links
/home/frdm/.atom/dev/packages (0)
└── (no links)
/home/frdm/.atom/packages (0)
└── (no links)

---

YES the problem remains if Atom runs in *safe mode*
YES it doesn't matter if I chose a font that supports these characters, DejavuSans Mono, Monospace, Noto Sans etc...

---

here is my FULL /.atom

.atom.zip 13.3 MB
https://mega.co.nz/#!CZw1ETab!MG8JHXZ_3kIYuYoSMhwp-oaV2jATdMqk3Pk7MXavSbk

---

Processor : 4x AMD A8-4500M APU integrated GPU
Operating System : Linux Mint 17.1 Rebecca (MATE)
OpenGL : AMD Radeon HD 7640G
X11 Vendor : The X.Org Foundation v1.15.1
Kernel : Linux 3.13.0-55-generic (x86_64)

**Comment by izuzak** [comment] 2015-06-19 12:34
@freed00m Can you post a screenshot which demosntrates the problem in safe mode?

I'm unable to reproduce this on Ubuntu, and the only other time I've heard about such problems is this: https://github.com/atom/atom-keymap/issues/37#issuecomment-110912999. In that case, the problem turned out to be a package the user installed.

Also, did this start happening recently or was it always like this for you? If you use an older version, (e.g. 0.180.0 and 0.190.0), do you see the same problem?

**Comment by freed00m** [comment] 2015-06-19 19:54
@izuzak 
Here is a 1:40 long DEMO: https://youtu.be/FDqzpwIKCeI

I have been able to reproduce the bug with a clean install of Atom 0.210 on Linux Mint Debian Edition "Betsy" 2

Could you provide a Ubuntu or Debian package for the older version of Atom? I might not want to build it from a git tree, sorry I usually fail to follow build instruction.

**Comment by paulcbetts** [comment] 2015-06-19 20:09
I believe this is https://github.com/atom/electron/pull/2014

**Comment by izuzak** [comment] 2015-06-22 06:45
> Could you provide a Ubuntu or Debian package for the older version of Atom? I might not want to build it from a git tree, sorry I usually fail to follow build instruction.

@freed00m You can find those downloads on the releases page: https://github.com/atom/atom/releases. Try using version 0.185.0 and 0.190.0

> I believe this is atom/electron#2014

@paulcbetts That's what I thought so too, but that problem normally manifests in a different way (see https://github.com/atom/atom/issues/6214) and users are normally able to fix that problem by changing the font, while @freed00m isn't able to do that it seems. Definitely not saying it isn't related, just that it doesn't fit the existing pattern exactly.

**Comment by freed00m** [comment] 2015-06-22 07:03
@izuzak I have tested an older version 0.185 and I must say the japanese characters are working properly.

Shall I test another version, which one would help pin point the issue?

**Comment by izuzak** [comment] 2015-06-22 07:07
@freed00m Thanks for testing. I believe this is a duplicate of https://github.com/atom/atom/issues/6214. To confirm, you could test also versions 0.188 and 0.189. Version 0.188 should not have the problem and version 0.189 should have the problem, if the theory is correct. As I mentioned above, the problem normally manifests in a different way (with different characters, not empty one).

**Comment by freed00m** [comment] 2015-06-22 20:54
@izuzak  *CONFIRMED* 

So I have tested version     0.188 and there were no problem.
Then I have tested version 0.189 and the problem appeared as initially described.

Tested on Debian Linux mint MATE

**Comment by freed00m** [comment] 2015-06-22 20:58
The dirty HACK is to use fontfamilia mentioned in #6214 issue

"Droid Sans Mono, Droid Sans Fallback"

If you don't have noto fonts install them via apt.

Should be satisfactory when noto sans mono looks the same as default

**Comment by izuzak** [comment] 2015-06-22 21:01
Thanks for helping investigate this, @freed00m :bow: -- I think we can close this in favor of #6214 then. Please subscribe there for updates about this problem.

**Closed by izuzak** 2015-06-22 21:01 UTC
Labels: editor-rendering, more-information-needed
