### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\k.karashima\Desktop\Pastis\PDF_DecisionTable.page'

### ISSUE THREAD

**Issue by kimino-n** [atom/atom#6409] opened 2015-04-17 01:51 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\k.karashima\Desktop\Pastis\PDF_DecisionTable.page'

```
At events.js:141

Error: ENOENT: no such file or directory, open 'C:\Users\k.karashima\Desktop\Pastis\PDF_DecisionTable.page'
  at Error (native)

```

### Commands

```
  3x -8:19.8 encoding-selector:show (atom-text-editor.editor)
     -7:31.5 core:save (atom-text-editor.editor)
     -6:52.8 core:backspace (atom-text-editor.editor)
  2x -6:51.5 core:save (atom-text-editor.editor)
     -3:39.4 core:backspace (atom-text-editor.editor)
     -3:37.5 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
MavensMate-Atom, v0.0.20

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-04-17 02:22
Hi, could you please share some reproduction steps (for instance, what were you doing when this happened)?  If it happens reliably, could you please try to reproduce this in safe mode (`atom --safe`)?  Thanks!

**Comment by halhenke** [comment] 2015-04-17 07:24
If its the same as this: #6372 I've put steps to reproduce that error there.

**Comment by kimino-n** [comment] 2015-04-17 07:30
Yes! Its the same as #6372 <https://github.com/atom/atom/issues/6372>.
Thank you!

********************************************************
株式会社ウフル
辛嶋 公諸 Kimio Karashima
〒105-0001 東京都港区虎ノ門4-1-8 虎ノ門四丁目MTビル6F
TEL 03-6895-1520
FAX 03-6895-1524
E-mail k.karashima@uhuru.jp
企業情報 http://uhuru.co.jp

■Facebookページ
⇒Uhuru Facebook ページ
【ウフルからのご案内や、Salesforceの活用ノウハウなどをご案内！】
http://www.facebook.com/uhuru.co.jp
<http://www.google.com/url?q=http%3A%2F%2Fwww.facebook.com%2Fuhuru.co.jp&sa=D&sntz=1&usg=AFrqEzdsMPwCTKw8rjDY0d3QgS9a3PGdNA>

⇒Uhuru Social Business Lab
【SNSを企業活動に活用するサービスを企画！関連情報を発信中！】
http://www.facebook.com/UhuruSocialBusinessLab
<http://www.google.com/url?q=http%3A%2F%2Fwww.facebook.com%2FUhuruSocialBusinessLab&sa=D&sntz=1&usg=AFrqEzeWOtt3zBhUC60fK432j_vXwUWN-A>
********************************************************

2015-04-17 16:24 GMT+09:00 Hal Henke <notifications@github.com>:

**Comment by 50Wliu** [comment] 2015-04-17 14:04
Closing as a duplicate of #6372/#6210, thanks @halhenke!

**Closed by 50Wliu** 2015-04-17 14:04 UTC
Labels: error-from-open, more-information-needed
