### ISSUE TITLE
A mechanism to visit the parent folder in tree view

### ISSUE THREAD

**Issue by tommytroylin** [atom/atom#5056] opened 2015-01-14 17:15 UTC
Why not add a mechanism in tree view that can visit it's parent folder?
like add a line .. on the top of tree view

Now I must do "Show in Finder" —> find the file in parent folder -> drag it into Atom ->"Reveal in tree view" to show the parent folder content in the tree view.

By the way, if you really do so, you will find you can not get the tree view of the parent folder. It only highlights the current folder. See more detail in #4524 

Thank you

**Comment by maxbrunsfeld** [comment] 2015-01-14 21:07
I think this is a duplicate of https://github.com/atom/tree-view/issues/286.

**Closed by maxbrunsfeld** 2015-01-14 21:07 UTC
Labels: enhancement
