### ISSUE TITLE
'Soft Wrap' and 'Preferred line length' don’t support multibyte characters

### ISSUE THREAD

**Issue by ls84** [atom/atom#6376] opened 2015-04-14 14:18 UTC
This issue has been discussed at [here](https://discuss.atom.io/t/preferred-line-length-dont-support-chinese/4666)

[Blaisorblade](https://discuss.atom.io/users/blaisorblade/activity) also presented a solution, however fixing this is kind of out my technical reach, I must first understand coffee script. However I am willing to contribute in anyway I can.

**Comment by SaschaNaz** [comment] 2015-04-16 12:02
Possible duplicate of #1783. Try [AtomicChar package](https://atom.io/packages/atomicchar) I made to temporarily fix this.

**Comment by 50Wliu** [comment] 2015-04-16 12:44
Yeah, I'm going to close this as a duplicate of #1783-thanks @SaschaNaz!

**Closed by 50Wliu** 2015-04-16 12:44 UTC
Labels: bug
