### ISSUE TITLE
Latest Version 1.17.0 on Windows does not change the encoding in the editor when done so

### ISSUE THREAD

**Issue by gabyx** [atom/atom#14499] opened 2017-05-19 07:38 UTC
I double checked for latest encoding issues, but they seem to be all closed:
When I open a file (which is encoded in `ISO 8859-1`) atom opens it in UTF-8.

With the [auto-encoding](https://atom.io/packages/auto-encoding) package, the file is opened in `Windows 1252` encoding.

Even if the encoding detection has not worked, changing the encoding in the `encoding-selector` to the **correct** encoding `ISO 8859-1` does not work. Meaning the editor does not change anything at all, all 
unrecognized character stay the same , for example: `f�hrt`.

What can we do about that?

**Comment by ungb** [comment] 2017-05-19 07:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/encoding-selector/issues/48. You may want to subscribe there for updates.

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by ungb** 2017-05-19 07:47 UTC
