### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 17 is larger than or equal to the node's length (16).

### ISSUE THREAD

**Issue by hadrienbaradel** [atom/atom#5571] opened 2015-02-16 09:47 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 17 is larger than or equal to the node's length (16).

```
At /Applications/Atom.app/Contents/Resources/app/src/lines-component.js:396

Error: Failed to execute 'setEnd' on 'Range': The offset 17 is larger than or equal to the node's length (16).
  at Error (native)
  at [object Object].module.exports.React.createClass.measureCharactersInLine (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:396:33)
  at [object Object].boundMethod [as measureCharactersInLine] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at /Applications/Atom.app/Contents/Resources/app/src/lines-component.js:349:21
  at DisplayBuffer.module.exports.DisplayBuffer.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:560:7)
  at TextEditor.module.exports.TextEditor.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2897:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.batchCharacterMeasurement (/Applications/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:782:18)
  at [object Object].module.exports.React.createClass.measureCharactersInNewLines (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:341:24)
  at [object Object].boundMethod [as measureCharactersInNewLines] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/Applications/Atom.app/Contents/Resources/app/src/lines-component.js:108:14)
  at CallbackQueue.mixInto.notifyAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.forceUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232:18)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:243:28

```

### Commands

```
     -6:41.1 core:confirm (atom-text-editor.editor.mini)
  4x -6:28.9 core:backspace (atom-text-editor.editor)
     -6:16.1 core:save (atom-text-editor.editor)
  3x -2:40.9 core:move-left (atom-text-editor.editor)
  2x -2:33.7 core:move-right (atom-text-editor.editor)
     -2:27.9 core:copy (atom-text-editor.editor)
     -2:25.7 core:paste (atom-text-editor.editor)
     -2:17.0 core:save (atom-text-editor.editor)
     -1:09.1 core:copy (atom-text-editor.editor)
     -0:53.9 core:move-to-bottom (atom-text-editor.editor)
     -0:51.0 core:paste (atom-text-editor.editor)
     -0:49.0 editor:newline (atom-text-editor.editor)
     -0:48.5 snippets:next-tab-stop (atom-text-editor.editor)
     -0:48.5 snippets:expand (atom-text-editor.editor)
     -0:48.5 editor:indent (atom-text-editor.editor)
     -0:38.2 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 13,
    "autoIndent": false,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-02-16 13:56
@hadrienbaradel Thanks for the report -- can you reproduce this reliably or share more details about what you were doing when this error happened? I'm having trouble reproducing this. Also /cc @nathansobo for :eyes:.

**Comment by izuzak** [comment] 2015-02-16 14:43
Ah, this looks like a duplicate of https://github.com/atom/atom/issues/5349.

**Closed by izuzak** 2015-02-16 14:43 UTC
Labels: bug
