### ISSUE TITLE
Autocomplete bug

### ISSUE THREAD

**Issue by sanada01** [atom/atom#16348] opened 2017-12-08 10:56 UTC
Hello everybody!

I'm trying to tag autocomplete, but it doesn't always work. Only if there is space next to it.
Atom version: 1.22.1 x64

![atombug](https://user-images.githubusercontent.com/28780118/33762836-6d991844-dc0e-11e7-927f-6c6c93067786.gif)

**Comment by willihangga** [comment] 2017-12-08 11:04
yep, I can reproduce this error too

**Comment by rsese** [comment] 2017-12-08 21:36
Thanks for taking the time to contribute!  I think this is a duplicate of https://github.com/atom/autocomplete-plus/issues/932 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-08 21:36 UTC
