### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

### ISSUE THREAD

**Issue by KoheiSumioka** [atom/atom#15867] opened 2017-10-11 15:02 UTC
[Enter steps to reproduce:]

1. ...[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:66

TypeError: Cannot read property 'onDidStopChanging' of undefined
    at BufferSearch.setEditor (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:66:54)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find.js:61:42
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:262:18)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:925:20)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:290:25)
    at HTMLElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:51:25)
```

### Commands

```
  9x -9:25.1.0 core:backspace (input.hidden-input)
     -9:20.1.0 core:confirm (input.hidden-input)
  3x -8:21 core:backspace (input.hidden-input)
     -8:12.3.0 core:confirm (input.hidden-input)
     -7:15.9.0 application:open (div.panels-item)
  2x -6:39.7.0 find-and-replace:select-next (input.hidden-input)
     -5:37.8.0 plantuml-viewer:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.5 
autocomplete-fortran 0.9.5 
autocomplete-paths 2.12.0 
file-icons 2.1.13 
highlight-selected 0.13.1 
language-fortran 2.1.6 
language-plantuml 0.2.0 
markdown-preview-enhanced 0.14.11 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.2 
mathjax-wrapper 0.1.0 
plantuml-viewer 0.7.2 
script 3.17.1 
tag 0.5.0 
term3 0.22.1 
web-search 0.3.3 
```

2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:66

TypeError: Cannot read property 'onDidStopChanging' of undefined
    at BufferSearch.setEditor (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:66:54)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find.js:61:42
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:262:18)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:925:20)
    at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app/src/pane.js:290:25)
    at HTMLElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:51:25)
```

### Commands

```
  9x -9:25.1.0 core:backspace (input.hidden-input)
     -9:20.1.0 core:confirm (input.hidden-input)
  3x -8:21 core:backspace (input.hidden-input)
     -8:12.3.0 core:confirm (input.hidden-input)
     -7:15.9.0 application:open (div.panels-item)
  2x -6:39.7.0 find-and-replace:select-next (input.hidden-input)
     -5:37.8.0 plantuml-viewer:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.5 
autocomplete-fortran 0.9.5 
autocomplete-paths 2.12.0 
file-icons 2.1.13 
highlight-selected 0.13.1 
language-fortran 2.1.6 
language-plantuml 0.2.0 
markdown-preview-enhanced 0.14.11 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.2 
mathjax-wrapper 0.1.0 
plantuml-viewer 0.7.2 
script 3.17.1 
tag 0.5.0 
term3 0.22.1 
web-search 0.3.3 
```

**Comment by rsese** [comment] 2017-10-11 17:02
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/898. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-11 17:02 UTC
