### ISSUE TITLE
Force focus on command palette

### ISSUE THREAD

**Issue by idleberg** [atom/atom#13143] opened 2016-11-04 08:12 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When in the Developer Tools console and the cursor is focused in the console prompt, launching the Command Palette does not change the focus. 

### Steps to Reproduce

1. Open Developer Tools
2. Put focus on console prompt
3. Use keyboard shortcut to show the Command Palette
4. Type anything

**Expected behavior:**
Focus changes to Command Palette, so commands can be typed in

**Actual behavior:**
Focus remains in console

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.5
git 1.8.5.2
```

**Comment by 50Wliu** [comment] 2016-11-04 17:28
By developer mode command prompt, I assume you mean the developer tools.  If so, I cannot reproduce this issue as the keyboard shortcut for the command palette opens the dev tools command palette instead.

If I'm misunderstanding something please say so.

**Comment by idleberg** [comment] 2016-11-04 17:38
Yes, I meant the Developer Tools and edited my issue accordingly.

> I cannot reproduce this issue as the keyboard shortcut for the command palette opens the dev tools command palette instead.

I'm not sure what this means. I can fire up the Command Palette from the dev tools console, but I cannot type in the Command Palette as you would usually be able to.

Tested on macOS 10.9, macOS 10.12 and Windows 10.0.14393, each running Atom 1.11.2. The problem has been around in older versions as well.

**Comment by Ben3eeE** [comment] 2016-11-04 17:41
Pressing <kbd>Ctrl+Shift+P</kbd> in the developer tools console opens the developer tools command palette.

![dev tols palette](https://cloud.githubusercontent.com/assets/1058982/20016073/405a07a6-a2be-11e6-9e95-502a886b18aa.gif)

**Comment by idleberg** [comment] 2016-11-04 17:48
> Pressing Ctrl+Shift+P in the developer tools console opens the developer tools command palette.

That is true in Atom Beta, but not for the stable version

![vjpu6o9rtz](https://cloud.githubusercontent.com/assets/1504938/20016335/4c7b9314-a2bf-11e6-9d06-a28e189074f9.gif)

**Comment by 50Wliu** [comment] 2016-11-04 19:07
Since the Chrome dev tools includes its own "command palette" in Atom 1.12 and up, I'm closing this as `wontfix`.

**Closed by 50Wliu** 2016-11-04 19:07 UTC
Labels: more-information-needed, needs-reproduction
