### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/nuclide:'

### ISSUE THREAD

**Issue by siliconblade** [atom/atom#17349] opened 2018-05-17 18:23 UTC
[Enter steps to reproduce:]

1. Launch atom after 7 plugin updates
2. get error: Uncaught Error: ENOENT: no such file or directory, lstat '/nuclide:'

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/nuclide:'

```
At fs.js:961

Error: ENOENT: no such file or directory, lstat '/nuclide:'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1641:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at atom.project.getPaths.map (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:73)
    at Array.map (native)
    at Object.startTask (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:56)
    at Object.startLoadPathsTask (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/main.js:129:43)
    at get_process.nextTick (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/main.js:31:45)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.20 
highlight-selected 0.13.1 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.7 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.303.108323685 
nuclide-format-js 0.0.45 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by rsese** [comment] 2018-05-17 19:56
Thanks for contributing!

This looks like a duplicate of https://github.com/atom/fuzzy-finder/issues/233 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-17 19:56 UTC
