### ISSUE TITLE
Failed to build/install atom on FreeBSD

### ISSUE THREAD

**Issue by Heather** [atom/atom#9809] opened 2015-11-25 09:56 UTC
callstack:

``` shell
84077 verbose unlock done using /home/heather/.atom/.npm/_locks/grunt-standard-6bc8c822d8ec00d1.lock for /usr/home/heather/H/atom/build/node_modules/grunt-standard
84078 verbose stack Error: minidump@0.9.0 install: `node-gyp rebuild`
84078 verbose stack Exit status 1
84078 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
84078 verbose stack     at emitTwo (events.js:87:13)
84078 verbose stack     at EventEmitter.emit (events.js:172:7)
84078 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
84078 verbose stack     at emitTwo (events.js:87:13)
84078 verbose stack     at ChildProcess.emit (events.js:172:7)
84078 verbose stack     at maybeClose (internal/child_process.js:818:16)
84078 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
84079 verbose pkgid minidump@0.9.0
84080 verbose cwd /usr/home/heather/H/atom/build
84081 error FreeBSD 10.1-RELEASE-p24
84082 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig=/usr/home/heather/H/atom/build/.npmrc" "install" "--loglevel" "error"
84083 error node v4.2.1
84084 error npm  v2.14.7
84085 error code ELIFECYCLE
84086 error minidump@0.9.0 install: `node-gyp rebuild`
84086 error Exit status 1
84087 error Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
84087 error This is most likely a problem with the minidump package,
84087 error not with npm itself.
84087 error Tell the author that this fails on your system:
84087 error     node-gyp rebuild
84087 error You can get their info via:
84087 error     npm owner ls minidump
84087 error There is likely additional logging output above.
84088 verbose exit [ 1, true ]
84089 verbose unbuild node_modules/minidump
84090 info preuninstall minidump@0.9.0
84091 info uninstall minidump@0.9.0
```

**Comment by lee-dohm** [comment] 2015-11-26 01:42
Were you building or installing Atom when this happened? What version of Atom were you attempting to build and/or install?

**Comment by 50Wliu** [comment] 2015-11-26 02:36
Looks like a duplicate of #6035, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-26 02:36 UTC
Labels: more-information-needed
