### ISSUE TITLE
Atom v1.28.0 not compatible with OS X 10.10.5

### ISSUE THREAD

**Issue by bretmette** [atom/atom#17614] opened 2018-07-03 04:21 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It looks like the minimum version for OS X has been bumped up for v1.28.0, The website home page for atom.io states 10.9 and above, but 10.10.5 is throwing an error when booting Atom.

I cannot remember the exact error, but it is along the lines of the operating system not meeting the minimum required version for the software. This error appears to be a standard operating system error that is being thrown before Atom loads. My guess is there is a version requirement setting being set for the build target that is higher than 10.10.5 and the operating system is seeing that and not allowing the program to open.

### Steps to Reproduce

1. Be running OS X 10.10.5
2. Download Atom 1.28.0 and place into Applications folder
3. Attempt to open Atom.

**Expected behavior:** Software runs

**Actual behavior:** Operating system error regarding version number of OS too low.

**Reproduces how often:** 100%

### Versions

OS X 10.10.5
Atom 1.28.0

### Additional Information

I installed 1.27.2 x64 and it works just fine. So my guess is this is a change in 1.28.0, I don't see it documented anywhere but if it is than at the very least the home page stating "For macOS 10.9 or later" is probably inaccurate.

I wish I had the exact error but I already have 1.27.2 open and I am working on a project and don't have time to reinstall 1.28.0 but wanted to report this error before I forgot. If I have time I will pull down 1.28.0 and get the exact error.

**Comment by lee-dohm** [comment] 2018-07-03 04:37
Looks like https://github.com/electron/electron/issues/13459 is the cause. v1.28.0 is the first version to be released on Electron v2.x.

**Comment by 50Wliu** [comment] 2018-07-03 04:41
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #17565 and #17586. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-07-03 04:41 UTC
Labels: blocked, electron, mac, triaged
