### ISSUE TITLE
Selecting the root directory in the tree should initialize the git sidebar

### ISSUE THREAD

**Issue by cryobry** [atom/atom#19548] opened 2019-06-16 15:48 UTC
## Summary

The git sidebar currently only initializes when a document residing in the root git directory is open and focused. I would like for it to also initialize when the root git directory is selected in the sidebar tree.

## Motivation

I use nested git repos, therefore my root git directory just contains a bunch of other directories, each with their own version control. I use the nested git repos to merge changes from upstream and the parent git repo to push to my production site. This requires me to open an unrelated document that resides in the root git repo in order to be able to push changes to production. Oftentimes my root git repo does not contain any files, which requires me to make a dummy file in order to initialize the git sidebar. Even when there are documents in the parent git repo directory, it is annoying to have to open and focus a random document that does not correspond to my current project just so I can push changes.

## Describe alternatives you've considered

Abandoning nested repos. Maybe a smart choice but everything works fine in the terminal, therefore I think that everything should work fine in Atom also.

## Additional context

I think that only initiating the git sidebar when the root git directory is selected should not cause issues in existing workflows, since selecting that directory would not change the scope of the git sidebar when people are just working on a single repo in the root. Others that are using nested repos would probably welcome the same functionality I am proposing here since https://github.com/atom/github/issues/1835 is still unresolved.

**Comment by Arcanemagus** [comment] 2019-06-16 18:07
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/1835. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-06-16 18:07 UTC

**Comment by cryobry** [comment] 2019-06-16 23:09
Not sure that this is duplicate since this functionality is completely independent of supporting subdirectory repos.
