### ISSUE TITLE
Full screen focus error

### ISSUE THREAD

**Issue by cyberwombat** [atom/atom#4489] opened 2014-12-10 00:41 UTC
When Atom is in full screen and I switch to another app (in this case iTerm in full screen - I have hotkeys assigned to each) Atom doesn't quite regain a full focus. The menu bar says "Atom" and if I type it will type within the open tab but it doesn't always respond to commands such as Cmd-P for a file dialog. So I hit Cmd-P and start typing a file name but instead it just writes it in the open tab fie,  Seems to be mosly related to full screen I believe.

**Comment by gonegreen** [comment] 2015-01-04 20:30
I can confirm this. Incredibly annoying.

**Comment by nunofgs** [comment] 2015-01-23 10:06
I've stopped using full-screen for exactly this reason.

**Comment by mnquintana** [comment] 2015-06-17 13:21
I can't reproduce this with Atom 0.210.0-83d143c and OS X 10.10.3? Is anyone still experiencing this with the latest version of Atom (0.209.0) (or master)?

**Comment by kevinsawicki** [comment] 2015-07-29 17:19
Closing this out for now since this may have been fixed by subsequent Chromium upgrades and no confirmation of it still happening has been reported in the last month.

Please comment if anyone still sees this happening with Atom 1.0.3+ and if it is exclusive to the Atom app or is happening with other full screen apps.

**Closed by kevinsawicki** 2015-07-29 17:19 UTC
Labels: mac, more-information-needed, needs-reproduction
