### ISSUE TITLE
Enable Dictionary lookup in OS X

### ISSUE THREAD

**Issue by adunning** [atom/atom#8052] opened 2015-07-23 21:44 UTC
On OS X, the standard Dictionary service does not work (usually set to ctrl + option + D or three-finger-tap). While there is a package that provides a workaround (https://atom.io/packages/dictionary), this should not be necessary, and the system-provided version of this is much less intrusive.

**Comment by mnquintana** [comment] 2015-07-24 00:15
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/5967 – let's keep the discussion there.

**Closed by mnquintana** 2015-07-24 00:15 UTC
Labels: enhancement

**Comment by a7744hsc** [comment] 2015-07-24 07:27
If it is because of -webkit-user-select: none; property in the editor-contents and editor-contents--private selector(As mathiasvr has metioned)? If so, where can I change it by myself?  Or I just need edit the source code and compile it ?
