### ISSUE TITLE
Uncaught TypeError: Cannot read property 'closest' of null

### ISSUE THREAD

**Issue by tphecca** [atom/atom#16272] opened 2017-11-24 22:07 UTC
[Enter steps to reproduce:]

1. Try to use `Tree View: Remove` command on a single-line Javascript file
File was not removed (my other file was), this error was thrown. Was able to remove it after trying a second time, no error was thrown.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'closest' of null

```
At /opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:1087

TypeError: Cannot read property 'closest' of null
    at atom.confirm.buttons.Move to Trash (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:1087:57)
    at ApplicationDelegate.module.exports.ApplicationDelegate.confirm (/opt/atom/resources/app/src/application-delegate.js:229:55)
    at AtomEnvironment.module.exports.AtomEnvironment.confirm (/opt/atom/resources/app/src/atom-environment.js:1020:45)
    at TreeView.module.exports.TreeView.removeSelectedEntries (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:1056:25)
    at HTMLElement.tree-view:remove (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view-package.js:23:66)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/opt/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/opt/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:324:26)
    at HTMLDivElement.core:confirm (/opt/atom/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -1:04.4.0 vim-mode-plus:move-right (input.hidden-input)
  5x -0:59 blur (input.hidden-input)
     -0:37.4.0 command-palette:toggle (input.hidden-input)
  3x -0:37.2.0 blur (input.hidden-input)
  2x -0:33.7.0 core:move-down (input.hidden-input)
  2x -0:32.1.0 core:move-up (input.hidden-input)
     -0:31.5.0 core:confirm (input.hidden-input)
  2x -0:31.5.0 blur (input.hidden-input)
     -0:31.5.0 tree-view:remove (input.hidden-input)
  6x -0:27.4.0 blur (input.hidden-input)
     -0:22.4.0 command-palette:toggle (input.hidden-input)
  3x -0:22.3.0 blur (input.hidden-input)
     -0:18.7.0 core:confirm (input.hidden-input)
  2x -0:18.7.0 blur (input.hidden-input)
     -0:18.7.0 tree-view:remove (input.hidden-input)
  8x -0:17.4.0 blur (input.hidden-input)
```

### Non-Core Packages

```
city-lights-syntax 1.1.3 
city-lights-ui 1.2.0 
ex-mode 0.18.0 
file-icons 2.1.14 
Hydrogen 2.1.0 
open-this 0.5.0 
teletype 0.2.3 
vim-mode-plus 1.20.0 
vim-mode-plus-exchange 0.4.0 
vim-mode-plus-move-selected-text 0.11.1 
```

**Comment by rsese** [comment] 2017-11-26 01:21
Thanks for the report!  Looks like a duplicate of https://github.com/atom/tree-view/issues/1194 and I believe should be fixed in 1.23, currently in beta.

**Closed by rsese** 2017-11-26 01:21 UTC
