### ISSUE TITLE
the following file couldn't moved to trash

### ISSUE THREAD

**Issue by xianghongai** [atom/atom#11338] opened 2016-04-01 05:00 UTC
windows 7 x64 , atom v1.6.1 .

![0](https://cloud.githubusercontent.com/assets/2075006/14198129/32f03de8-f809-11e5-9298-ededf8093671.png)

![1](https://cloud.githubusercontent.com/assets/2075006/14198132/3965006e-f809-11e5-8d1b-7306cd871e2a.png)

1、move to trash
2、the following file couldn't moved to trash
3、run as administrator , also can't .

**Comment by Ben3eeE** [comment] 2016-04-01 05:41
This looks like a duplicate of https://github.com/atom/tree-view/issues/666 which should be fixed in atom 1.7.0 according to the last comment in the issue. If you want this feature right away you can try the atom beta release.

**Closed** 2016-04-01 13:27 UTC
