### ISSUE TITLE
Uncaught BufferedProcessError: Failed to Spawn Command

### ISSUE THREAD

**Issue by patmcd** [atom/atom#8257] opened 2015-08-07 00:02 UTC
This only happens when I open up the preferences window. (Or open Atom with the tab from last session actie). 

This did not happen until I installed 1.0.5.

Window load time: 1753ms
/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260 Uncaught BufferedProcessError: Failed to spawn command `/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper`. Make sure `/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper` is installed and on your PATH

![image](https://cloud.githubusercontent.com/assets/538543/9126049/071981b0-3c76-11e5-9c8a-1275f166dc2e.png)

**Comment by 50Wliu** [comment] 2015-08-07 00:22
Duplicate of #7594, please subscribe there for updates.

**Closed by 50Wliu** 2015-08-07 00:22 UTC
