### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by karelsteinmetz** [atom/atom#7412] opened 2015-06-25 12:16 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\k.steinmetz\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:57.1.0 core:delete (atom-text-editor.editor.is-focused)
     -0:56.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:56 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:56 snippets:expand (atom-text-editor.editor.is-focused)
     -0:56 editor:indent (atom-text-editor.editor.is-focused)
     -0:54.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:47.3.0 pane:show-next-item (atom-text-editor.editor.is-focused)
  2x -0:45.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:41.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:37.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:35.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:34 core:backspace (atom-text-editor.editor.is-focused)
     -0:33 core:move-left (atom-text-editor.editor.is-focused)
     -0:29 core:undo (atom-text-editor.editor.is-focused)
     -0:27.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:27.6.0 linter:lint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 17
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.6.4
linter, v1.0.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-06-25 12:18
This is a duplicate of https://github.com/atom/atom/issues/6548 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-25 12:18 UTC
