### ISSUE TITLE
Atom internet connexion

### ISSUE THREAD

**Issue by orochies** [atom/atom#12586] opened 2016-09-01 22:17 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom does not start when internet offline.

### Steps to Reproduce

1. With internet conection launch atom.
2. Atom  is launched successfully
3. Close atom
4. Turn off internet connection
5. Launch atom
6. Nothing happens and no atom launched. 

**Expected behavior:** 

Atom  is launched successfully.

**Actual behavior:**

Nothing happens and no atom launched.  

Just type in the log "%LOCALAPPDATA%\atom\SquirrelSetup.log": 

"Program: Want to launch '%LOCALAPPDATA%\atom\app-1.10.0\atom.exe'
"Program: About to launch: '%LOCALAPPDATA%\atom\app-1.10.0\atom.exe'"

### Versions

Atom 1.10.0
System: Windows 8.1 x64
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.5.3.windows.1
visual studio 2015

**Comment by andyrichardson** [comment] 2016-09-03 17:56
I could not replicate this issue in Windows 10 or Fedora 24.

**Comment by thomasjo** [comment] 2016-09-05 06:01
Unable to reproduce.

**Comment by 50Wliu** [comment] 2016-09-05 19:11
Also cannot reproduce on Windows 10 x64, Atom 1.12.0-dev-4a73709.  As that's three people who are unable to reproduce, I'm closing this issue.

If someone else is experiencing this please comment here.

**Closed by 50Wliu** 2016-09-05 19:11 UTC
Labels: needs-reproduction, network

**Comment by orochies** [comment] 2016-09-07 07:17
Atom is now working with mobile hotspot connection without internet access. 

Windows Loopback is related. 
I happened width nodejs proxy  "An Error occured: getaddrinfo ENOENT localhost"

But: Atom 1.8.0 always work, width and widthout internet connection.

Thanks.
