### ISSUE TITLE
Project Tree Erased

### ISSUE THREAD

**Issue by cakenggt** [atom/atom#7168] opened 2015-06-08 14:15 UTC
The project tree gets erased and replaced with the containing folder when you select "Open in Atom" from the right click menu when right clicking on a file. This is happening on Windows 7 with 0.207.0 .

Steps for reproduction:
1. Add several project folders to the tree view.
2. Close down Atom.
3. In a file explorer, right click a file and select "Open in Atom".
4. All of the projects you added before to the tree are removed, leaving only the containing folder of the file you just opened.
5. Close down Atom.
6. On reopening atom, the project tree still only contains the folder present in step 4.

**Comment by maxbrunsfeld** [comment] 2015-06-08 17:01
@cakenggt I believe this is the expected behavior. When you open a directory in Atom, a new window is created. We don't automatically add it to a window containing all the folders you had open previously, because we think this would often be surprising to people.

We know your use case is important though: a lot of people generally have a lot of projects open at a time and need an easy way to get back to that state. Correct me if I'm wrong, but it sounds like the feature that may be missing for you is some kind of 'project file' that you can use to save and repoen the state of a window, which may contain many project folders. We plan to add something like that at some point.

**Comment by cakenggt** [comment] 2015-06-08 17:22
You are correct, that feature is exactly what I need. Thanks for the reply, I'll be looking forward to it in the future!

**Comment by maxbrunsfeld** [comment] 2015-06-08 17:25
Ok, I'm going to close this issue for now. You might want to subscribe to issue #5728. The feature that we're talking about shouldn't be too hard to implement, but we haven't decided exactly how we want it to work yet. Thanks for the feedback!

**Closed by maxbrunsfeld** 2015-06-08 17:25 UTC
Labels: enhancement, question
