### ISSUE TITLE
Atom Editor code flickers when focused

### ISSUE THREAD

**Issue by Bazooo** [atom/atom#15892] opened 2017-10-14 17:00 UTC
### Description

The code seems to flicker when a pane of the Atom Editor is focused

![2017-10-14_12-51-45](https://user-images.githubusercontent.com/8026631/31577557-a9e21e50-b0de-11e7-93a5-85df2081eb4a.gif)
*GIF of the issue in safe mode*

### Steps to Reproduce

Focus a pane with code

**Expected behavior:** A static code that does not flicker, similar to when it is not focused.

**Actual behavior:** Code flickers/moves a little bit

**Reproduces how often:** Every time

### Versions
*atom version*
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

*apm version*
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python
git 2.12.0.windows
visual studio 2015

*OS*
Windows 10 Home 1607 build 14393.170

**Comment by Bazooo** [comment] 2017-10-14 19:35
Fixed the issue.
Having a transition on the opacity of the cursor created this problem.
![2017-10-14_15-33-57](https://user-images.githubusercontent.com/8026631/31578723-3406da6a-b0f5-11e7-8137-3a24c26cf01d.gif)
*style.less*

**Comment by Bazooo** [comment] 2017-10-15 17:55
Seems like this issue is from the atom version 1.21.1, since the 1.20 version did not have this kind of issue.

**Comment by Ben3eeE** [comment] 2017-10-15 18:16
@Bazooo This is a duplicate of https://github.com/atom/atom/issues/15626

**Closed by Ben3eeE** 2017-10-15 18:16 UTC
