### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by dhbmedanis** [atom/atom#17259] opened 2018-05-02 09:29 UTC
I had a problem after installing these packages in atom
gitlab 0.1.3-7 
meteor-api 2.20.0 
meteor-helper 0.29.0 
meteor-snippets 0.5.0 

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:95

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:95:11)
    at executeDispatchesAndRelease (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:41:28)
    at executeDispatchesAndReleaseTopLevel (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:52:16)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/forEachAccumulated.js:22:15)
    at Object.processEventQueue (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:252:13)
    at runEventQueueInBatch (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:15:24)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:25:11)
    at handleTopLevelImpl (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:70:30)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:32)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:95:33)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:145:26)
```

### Commands

```
     -0:22.2.0 tabs:close-other-tabs (div.title)
```

### Non-Core Packages

```
gitlab 0.1.3-7 
meteor-api 2.20.0 
meteor-helper 0.29.0 
meteor-snippets 0.5.0 
```

**Comment by rsese** [comment] 2018-05-02 16:28
Thanks for contributing!

This looks like a duplicate of https://github.com/atom/atom/issues/15093 so you can subscribe there for updates if you'd like.  It looks like this issue could be related to having `NODE_ENV=development` set on your system?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-02 16:28 UTC
