### ISSUE TITLE
File Search Result Order Is Unintuitive

### ISSUE THREAD

**Issue by hharnisc** [atom/atom#6148] opened 2015-03-28 17:41 UTC
When searching for a file with `CMD + P` I would expect results with exact filenames to be more relevant.

![screen shot 2015-03-28 at 10 39 12 am](https://cloud.githubusercontent.com/assets/1388079/6882075/bbb89860-d536-11e4-83b6-57ee45aa76f0.png)

**Comment by thomasjo** [comment] 2015-03-28 17:53
Duplicate of https://github.com/atom/fuzzy-finder/issues/21.

**Closed by thomasjo** 2015-03-28 17:53 UTC
