### ISSUE TITLE
package dependency npm install failure

### ISSUE THREAD

**Issue by StevenACoffman** [atom/atom#5375] opened 2015-02-03 13:59 UTC
Running Atom Version 0.176.0 (0.176.0) and atom-fixmyjs 1.3.0
Originally from sindresorhus/atom-fixmyjs/issues/7

Reproduceable. This appears to be an atom bug, rather than in the atom-fixmyjs package. It looks like there is an npm install error where the fixmyjs dependency doesn't get installed. Previous versions of Atom worked fine, and there were no relevant changes in atom-fixmyjs.

If I go to ~/.atom/packages/fixmyjs and run npm install it works, but with a clean install without manually installing the dependency, if I go to the command palette I can execute FixMyJS the web developer view will show this:
```
Failed to activate package named 'fixmyjs' Error: Cannot find module 'fixmyjs'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Object.<anonymous> (/Users/gears/.atom/packages/fixmyjs/index.js:2:15)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:623:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:250:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:232:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:682:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:224:20)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:336:21)
  at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/go-to-line/node_modules/atom-space-pen-views/lib/select-list-view.js:140:19)
  at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)
```

**Comment by 50Wliu** [comment] 2016-04-29 22:50
Still appears to be an issue - at least up to Atom 1.6.0 - based on sindresorhus/atom-fixmyjs#12.

**Comment by 50Wliu** [comment] 2016-04-29 23:42
Closing as a duplicate of atom/apm#323.

**Closed by 50Wliu** 2016-04-29 23:42 UTC
Labels: bug, more-information-needed
