### ISSUE TITLE
Document tree in navigator panel cut off while a lot of files shown

### ISSUE THREAD

**Issue by tomexx** [atom/atom#10703] opened 2016-02-05 17:08 UTC
Atom 1.4.3 for Mac
<img width="618" alt="screen shot 2016-02-05 at 15 58 26" src="https://cloud.githubusercontent.com/assets/2822756/12853106/97a45e66-cc32-11e5-8156-3ab832e9c8cd.png">

**Comment by mnquintana** [comment] 2016-02-05 17:31
Thanks for the report! This looks like a duplicate of https://github.com/atom/tree-view/issues/709 / https://github.com/atom/one-dark-ui/issues/109 which has been fixed in the 1.5 betas.

You can take a look at https://github.com/atom/tree-view/issues/709#issuecomment-173432622 for a workaround until 1.5.0 is released.

**Closed by mnquintana** 2016-02-05 17:31 UTC
