### ISSUE TITLE
After closing all windows, File > Open doesn't show Finder

### ISSUE THREAD

**Issue by helbnt** [atom/atom#14809] opened 2017-06-16 12:55 UTC
Mac OS X 10.12.5
atom --version:
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Steps to Reproduce

1. Launch Atom as normal. Last project or new window will be in view.
2. Close window (don't exit out of Atom)
3. Go to File, select Open

**Expected behavior:** Finder window opens, allowing for new file selection

**Actual behavior:** No Finder window appears

**Reproduces how often:** 100%

**Comment by helbnt** [comment] 2017-06-16 12:57
Workaround right now is File > New Window, then File > Open

**Comment by 50Wliu** [comment] 2017-06-16 15:17
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-06-16 15:17 UTC
