### ISSUE TITLE
Add a config setting for quitting the app when the last window is closed on Mac OS clicking the x icon directly

### ISSUE THREAD

**Issue by wanghaisheng** [atom/atom#7835] opened 2015-07-10 18:27 UTC
mac 10.10.4
atom 1.0.2 download from release atom-mac.zip and install.
1.from Dock I click the icon
when I first open atom it comes to a untitled txt file,then choose a local folder and open it ,then close editor and reopen,it come to a untitled again.

add project folder does not work either
2. from the terminal, try to use atom . from a local folder, and close the editor manually by clicking the "x" icon ，also i try to open two local folders and shutdown one of them and reopen editor again, it won`t work either

**Comment by kubetz** [comment] 2015-07-10 20:19
@wanghaisheng Is the behavior of atom described [here](https://github.com/atom/atom/issues/1603#issuecomment-116083477) same as the one you are experiencing? If yes then use <kbd>Cmd-Q</kbd> to make Atom remember your session.

**Comment by maxbrunsfeld** [comment] 2015-07-10 21:10
Does this happen even if you open atom with the folder using `atom the-folder` from the terminal? What about if you open a new window after opening the first window.

**Comment by wanghaisheng** [comment] 2015-07-11 04:27
@maxbrunsfeld   @mnquintana  update the info

**Comment by maxbrunsfeld** [comment] 2015-07-11 04:48
So you said that when you close Atom, you close the window by clicking the `x` button. What if instead, you quit the app with `command-q`?

**Comment by wanghaisheng** [comment] 2015-07-11 04:54
@maxbrunsfeld let me try .instead of using 1.0.x atom , I am always doing things like that and it is ok

**Comment by maxbrunsfeld** [comment] 2015-07-11 04:58
Ok, I think that what you are seeing is the expected behavior. On Mac OS, the standard behavior is that the `x` button does not quit the app; it just closes the window. Atom remembers the windows you have open when you quit and reopen it, so if you close a window, it will remember that you had no windows  open.

**Comment by wanghaisheng** [comment] 2015-07-11 05:06
thx. it seems so, when i right click the atom icon on Dock and quit the editor ,it works .but click the "x"，the atom   icon still stays on the Dock.
is there any config i can set to let atom do the same as command-q when i click the "x" close the window.

**Comment by maxbrunsfeld** [comment] 2015-07-15 07:48
No, there's no such config setting right now. I know that MacVim has a config setting like that, so it would be a reasonable thing to add. Now that we understand the problem that you're experiencing, would you like to rename this issue, turning it into a feature request for that config setting?

**Comment by wanghaisheng** [comment] 2015-07-15 13:31
how to describe would be proper ,a little advice？

**Comment by lee-dohm** [comment] 2015-07-16 03:07
There is a whole, huge sordid history to this. Most of it can be found in #2986. This also looks like a duplicate of #863, would you agree?

Also, there is [the-closer](https://atom.io/packages/the-closer) that, last I checked, offered this already.

**Comment by wanghaisheng** [comment] 2015-07-16 04:47
@lee-dohm  i tried the solutions in the links you provided,
neither of these three tabs-closer,close-after-last-tab,the-closer works,when I click the red "x" button as the below image shows
<img width="688" alt="qq20150716-2 2x" src="https://cloud.githubusercontent.com/assets/2363295/8715709/cbbadae2-2bb8-11e5-8590-d679644babba.png">

**Comment by lee-dohm** [comment] 2015-07-16 05:13
You're right, the-closer doesn't cover clicking the red button. I misunderstood.

**Comment by janwo** [comment] 2017-04-27 13:40
Any updates?

**Comment by lee-dohm** [comment] 2017-04-27 16:09
Thanks for the ping @janwo. While we understand that this would be useful for some people's workflows, this isn't something that we're going to be adding to Atom.

**Closed by lee-dohm** 2017-04-27 16:09 UTC
Labels: enhancement
