### ISSUE TITLE
Modify mouse behaviour

### ISSUE THREAD

**Issue by karai17** [atom/atom#10574] opened 2016-01-25 12:44 UTC
I think it would be nice if users could modify mouse behaviour similar to how we can modify key bindings. My main reasoning for this is that I have recently switched from Windows to Linux and have learned that middle mouse pasting is not only a thing, but deeply ingrained into X itself. This is frustrating for me because an Atom add-on I can't live without, **Sublime-Style-Column-Selection** simply does not work on Linux. If I set it to use the left mouse button, that disables my ability to click and drag to select text. If I set it to middle mouse, I end up pasting junk everywhere, and if I set it to right mouse, well, it just pops up menus instead.

I use this feature about 9000 times a day, and not being able to use it is killing me. I know that Atom was recently "fixed" to comply with X's nonsense, but there seems to be no simple way to revert to using sane controls.

**Comment by mnquintana** [comment] 2016-01-25 14:40
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/2256 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-25 14:40 UTC
