### ISSUE TITLE
High CPU usage when fed a long string of digits

### ISSUE THREAD

**Issue by MatthijsBlom** [atom/atom#17725] opened 2018-07-21 17:01 UTC
### Prerequisites

*   [x] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
*   [ ] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
*   [x] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
*   [x] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>

I could not figure out how to obtain a CPU profile.  
(The debugging section of the Flight Manual appears to be out of date.)

### Description

When an editor contains or receives a long string of digits, this will result in high CPU usage. As far as I can tell, this happens only with strings of digits; not with long letter sequences.

On my machine, the CPU spikes become noticeable at ~20 digits. The size of the spikes increases superlinearly with the length of the digit sequence. After ~27 digits, CPU usage caps at ~20% but takes increasingly long times to go down.

### Steps to Reproduce

1.  Open an empty editor;
2.  Slowly enter a long string of digits and keep an eye on Atom's CPU usage;
3.  Notice the spikes following each addition of a digit, and that these spikes get larger as the string gets longer.

**Expected behavior:** no CPU spikes

**Actual behavior:** CPU spikes

**Reproduces how often:** 100%

### Versions

Windows 10 Home, version 1803

```
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python 3.7.0
git 2.18.0.windows.1
visual studio
```

### Additional Information

&mdash;

**Comment by rsese** [comment] 2018-07-23 21:35
Thanks for the report - I'm unable to reproduce on Windows 10 and Atom 1.28.2 (I went past a random string of 40 digits) and task manager showed about 7% CPU at most.

Is this in any particular type of file or can you reproduce in a plain text file (that's what I tested in, starting with a blank file with no project open)?  Was the CPU usage exactly the same in safe mode?

**Comment by rsese** [comment] 2018-09-14 20:06
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17725#issuecomment-407208870. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-09-14 20:06 UTC
Labels: more-information-needed

**Comment by rsese** [comment] 2018-09-14 20:17
Not positive if it's the issue you were hitting but it's possible that you were hitting an issue that's since been resolved in https://github.com/atom/superstring/pull/44.
