### ISSUE TITLE
Add vibrancy support for macOS

### ISSUE THREAD

**Issue by chrisdrackett** [atom/atom#14162] opened 2017-04-10 21:26 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I wonder if it might be possible to add support for vibrancy (https://github.com/electron/electron/pull/7898) to atom. I think a good first step would be to enable vibrancy for the tree-view. Maybe giving an option in settings to choose between dark and light.

### Steps to Reproduce

None. Feature request

**Expected behavior:** [What you expect to happen]

Ability to set the background of tree view to use vibrancy

**Actual behavior:** [What actually happens]

Not currently possible

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

1.15.0
10.12.4

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by thomasjo** [comment] 2017-04-11 04:56
This will most likely be possible to some extent, once #12696 ships.

Please update your issue body with the issue template (or at very least more details) — we require all issues to be clearly actionable. Non-actionable issues with insufficient details on expected behavior and so on, will be closed.

Thanks!

**Comment by austin-guevara** [comment] 2017-06-16 15:27
@thomasjo – it seems that this was successfully merged to master. Does that mean that this is now possible in the regular release of Atom? Or am I misreading? Thanks!

**Comment by 50Wliu** [comment] 2017-06-17 03:56
I don't believe it's possible to set vibrancy on _portions_ of a window.  It looks like Atom needs to expose an API or a config to support setting vibrancy, since the Electron APIs for vibrancy are directly tied to BrowserWindows.

**Comment by chrisdrackett** [comment] 2017-06-17 04:12
still you could set it to the whole window and set things you want to be vibrant as transparent while giving everything else a background color

**Comment by austin-guevara** [comment] 2017-06-19 18:49
My dream is to have the side panels with vibrancy (tree view, Github panel) and everything else as the standard theme background color. But it sounds like that's not fully possible yet. 

Unless your workaround works, @chrisdrackett. Any idea of how to get started with that?

**Comment by chrisdrackett** [comment] 2017-06-19 18:58
@aureliojargas I want to do the same thing :)

I do something pretty similar with hyper where the whole window is vibrant and I just overlay it with flat colors to "remove" vibrancy. I'm guessing it should be easily doable.

**Comment by austin-guevara** [comment] 2017-06-19 20:53
@chrisdrackett – I use vibrancy in Hyper as well! 

I believe that @50Wliu is correct, however – this is possible in Hyper because they have an API exposed for just that.

**Comment by the0neyouseek** [comment] 2017-07-22 19:10
I don't know if I did my pull request correctly but I managed to get a pretty decent result with some tweaks to the stylesheet.

![atom-vibrancy](https://user-images.githubusercontent.com/4009175/28494018-28c1ff46-6f22-11e7-8193-56f0c7d37e0b.png)

**Comment by austin-guevara** [comment] 2017-07-22 19:16
This. Looks. _Incredible_. This is exactly what I imagined. It brings a whole new level of maturity to the Atom UI. Great work!

**Comment by the0neyouseek** [comment] 2017-07-22 19:27
@austin-guevara If you want to test it yourself you can download my branch, compile it (`script/build` from the root folder if you're on a mac), then you only need to add
```js
atom.getCurrentWindow().setVibrancy('medium-light');
```
to your `Init Script`, and 
```css
// style the background color of the tree view
html,
atom-workspace,
.atom-dock-mask,
atom-pane-container atom-pane,
.tree-view {
  background: transparent !important;
}
```
to your stylesheet.

**Comment by austin-guevara** [comment] 2017-07-23 19:51
Was able to successfully do the same using your method – it should be fairly easy to get this enabled as a toggle/dropdown in the settings UI and added into the next official release 🤗!

Here’s my implementation – using Atom Material, One Dark, and `ultra-dark` as the vibrancy setting.

<img width="1440" alt="screen shot 2017-07-23 at 3 49 48 pm" src="https://user-images.githubusercontent.com/14018074/28502372-c3817d6c-6fbe-11e7-9335-6f165b22cf3c.png">

**Comment by lee-dohm** [comment] 2017-07-31 18:51
Thanks everyone for your interest in this. At this time, we've decided that we aren't going to add an official API for the vibrancy feature. Since theme authors can use the techniques described here and in @austin-guevara's great PR, we don't feel that an official API is necessary.

Thanks for the suggestion and all the amazing work!

**Closed by lee-dohm** 2017-07-31 18:51 UTC

**Comment by chrisdrackett** [comment] 2017-08-06 05:32
@lee-dohm so wait, is this doable without forking atom?

**Comment by the0neyouseek** [comment] 2017-08-06 05:54
@chrisdrackett Yes it is, only on `1.19` beta and the api is :

ˋˋˋjs
require('electron').remote.getCurrentWindow().setVibrancy('medium-light');
ˋˋˋ
