### ISSUE TITLE
The exchange of branches causes the file to be lost(Operating the git)

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#17235] opened 2018-04-28 07:14 UTC
### Description
> When git exchanges branches, there is a caching problem, which causes the file to be lost.
> -  `issue` : Every time I want to change my branch, I have to close `atom` 

```shell
$ git checkout master
error: unable to create file program-basic/git/03-Git-Branching/3.02-*.md: Permission denied
Switched to branch 'master'
D       program-basic/git/03-Git-Branching/3.02-*.md
Your branch is up to date with 'github-programmer/master'.
```

### Steps to Reproduce

**Expected behavior:** [Switch Git branches normally.]

**Actual behavior:** [The exchange of branches causes the file to be lost.]

**Reproduces how often:** [It's always been a problem.]

### Versions
> windows 10 

```shell
C:\Users\username>atom --version

Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

```shell
C:\Users\username>apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.14
git 2.17.0.windows.1
visual studio
```

### Additional Information

```shell
Community Packages (51) C:\Users\username\.atom\packages
├── activate-power-mode@2.7.0
├── advanced-open-file@0.16.8
├── aligner@1.2.4
├── aligner-css@1.2.1
├── aligner-javascript@1.3.0
├── aligner-php@1.2.0
├── atom-beautify@0.32.2
├── atom-clock@0.1.16
├── atom-html-preview@0.2.5
├── atom-ide-ui@0.11.1
├── atom-material-syntax@1.0.8
├── atom-minify@0.8.0
├── autocomplete-paths@2.12.2
├── autoprefixer@3.7.1
├── city-lights-syntax@1.1.8
├── color-picker@2.3.0
├── docblockr@0.13.7
├── emmet@2.4.3
├── ex-mode@0.18.0
├── file-icons@2.1.19
├── git-blame@1.6.0
├── git-history@3.3.0
├── git-plus@7.10.2
├── git-time-machine@1.5.9
├── highlight-column@0.5.4
├── highlight-line@0.12.0
├── highlight-selected@0.13.1
├── ide-php@0.7.14
├── ide-typescript@0.7.6
├── markdown-scroll-sync@2.1.2
├── merge-conflicts@1.4.5
├── minimap@4.29.8
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2
├── minimap-split-diff@0.3.7
├── monokai@0.24.0
├── open-in-browser@0.5.2
├── pigments@0.40.2
├── project-viewer@1.3.1
├── relative-numbers@0.9.0
├── remote-ftp@2.1.4
├── seti-syntax@1.1.3
├── split-diff@1.5.2
├── Sublime-Style-Column-Selection@1.7.4
├── sync-settings@0.8.6
├── tree-view-git-status@1.5.0
└── vim-mode-plus@1.32.0
```

**Comment by rsese** [comment] 2018-04-30 17:46
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/17013 so you can subscribe there for updates if you'd like.  Some people have mentioned that they haven't seen this issue on Atom 1.24.1 so you can try that version to confirm/as a workaround.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-30 17:46 UTC
