### ISSUE TITLE
Pressing left or right when a menu is open does nothing

### ISSUE THREAD

**Issue by stuaxo** [atom/atom#12054] opened 2016-06-27 17:20 UTC
Open the edit menu

Press left and observe that you are not on the file menu

Press right and observe that you are not on the view menu.

OS:  Ubuntu 64 bit 16.04

**Comment by mnquintana** [comment] 2016-06-27 17:21
This looks like a duplicate of https://github.com/atom/atom/issues/5998 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-06-27 17:21 UTC
