### ISSUE TITLE
Tree panel automatically expands when changing tabs if Reveal is enabled

### ISSUE THREAD

**Issue by Eugeny** [atom/atom#16690] opened 2018-02-06 16:18 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The collapsed tree panel will automatically re-expand if I switch tabs while "Reveal in the tree view" setting is enabled, making it impossible to keep the tree pane collapsed.

### Steps to Reproduce

1. Set `tree-view.autoReveal = true` 
2. Have two tabs open
3. Collapse the tree pane
4. Switch to a different tab

**Expected behavior:** tree view stays collapsed

**Actual behavior:** tree view expands

**Reproduces how often:** 100%

### Versions

```
Ubuntu 18.04
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by rsese** [comment] 2018-02-07 04:51
Thanks for the report!  This is a duplicate of https://github.com/atom/tree-view/issues/796 which has been fixed but it looks like some version bumping needs to happen for it to make it in an upcoming release.  I'll ask the team to take a look.

**Closed by rsese** 2018-02-07 04:51 UTC
