### ISSUE TITLE
File tab hover tooltip get's stuck and won't disappear

### ISSUE THREAD

**Issue by mrseanbaines** [atom/atom#15849] opened 2017-10-09 18:32 UTC
### Description

Occasionally (seemingly randomly), the tooltip that shows the file path on the file tab when you hover on it gets stuck and won't go away until I restart Atom. Sometimes when this happens and I have multiple tabs open, all of the tab's tooltips will remain.

### Steps to Reproduce

Not sure what is causing this - seems to be random, and with general use.

**Reproduces how often:** Once or twice a day.

### Versions

Atom: 1.20.1
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0

### Additional Information

![image](https://user-images.githubusercontent.com/24367010/31352893-5b648a6a-ad28-11e7-8208-629070e0c323.png)

**Comment by rsese** [comment] 2017-10-10 04:37
Thanks for the report!  I've vaguely noticed this as well in the settings view lately but could never reproduce it on purpose.  I'm guessing it doesn't happen enough for you to try and reproduce in safe mode since it happens sporadically.

We'll go ahead and leave this open for a bit and see if anyone else runs into it and if anyone comes up with steps to reproduce.

Can you share what operating system you're running?

**Comment by rsese** [comment] 2017-10-10 04:40
oh I just came across https://github.com/atom/tabs/issues/362 which reminds me that this should probably be moved to https://github.com/atom/tabs (that issue was closed as fix so we should open a new issue).

I can re-open this in https://github.com/atom/tabs/issues/362 tomorrow unless you get to it first @mrseanbaines.

**Closed by rsese** 2017-10-10 04:40 UTC
Labels: more-information-needed
