### ISSUE TITLE
File dialogues broken

### ISSUE THREAD

**Issue by discentem** [atom/atom#14191] opened 2017-04-12 23:41 UTC
### Prerequisites
    * [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Neither `File/Reopen Project` nor `File/Add Project Folder` work if the main Atom window has been closed. 

<img width="1280" alt="screen shot 2017-04-12 at 7 29 49 pm" src="https://cloud.githubusercontent.com/assets/2560432/24983767/59d5557a-1fb7-11e7-9286-f0355da6de58.png">

### Steps to Reproduce

1. Launch Atom
2. Select `File/Reopen Project` or `File/Add Project Folder`
3. <Nothing happens>

**Expected behavior:** In `step 3` above I expect either Atom to open with my project or to be presented with a file dialogue. 

**Actual behavior:** Nothing happens when selecting `File/Reopen Project` or `File/Add Project Folder` if the empty Atom window is closed. 

**Reproduces how often:** 100%

### Versions

> brandons-mbp:~ Brandon$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Occurs in both Atom and Atom Beta on macOS 10.12.x.

**Comment by 50Wliu** [comment] 2017-04-12 23:43
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-04-12 23:43 UTC
