### ISSUE TITLE
Flaky test: FuzzyFinder git-status-finder behavior displays all new and modified paths

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#19095] opened 2019-04-02 23:25 UTC
We sometimes see [this test](https://github.com/atom/fuzzy-finder/blob/d53f278abff1887e80ab33fabe7e806579150cc1/spec/fuzzy-finder-spec.js#L1286-L1294) fail due to a timeout...

```
FuzzyFinder
  file-finder behavior (ripgrep=false, scoringSystem=alternate)
    Git integration
      git-status-finder behavior
        it FuzzyFinder file-finder behavior (ripgrep=false, scoringSystem=alternate) Git integration git-status-finder behavior displays all new and modified paths
          timeout: timed out after 60000 msec waiting for condition     at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:1471:11)
```

Rebuilding usually resolves the failure.

---

**Affected CI provider(s)**: Azure DevOps

**Affected platform(s)**: macOS

**Example commit experiencing flakiness**: https://github.com/atom/atom/commit/44271255fc5e0ff6ab73c49a669f0c068837947a

**Example failing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=37033&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=8b9bff53-2841-58c7-68fc-e30c30330fc3&lineStart=2762&lineEnd=2767&colStart=1&colEnd=18

**Example passing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=37090

**Example log from failing build**: https://github.com/atom/atom/files/3036232/build.log

**Comment by jasonrudolph** [comment] 2019-04-02 23:25
Note: The build described in the issue body above also included another failing test. I don't know if one failure is likely to cause the other, but I figured I'd mention in here just in case it offers any clues:

```
FuzzyFinder
  file-finder behavior (ripgrep=false, scoringSystem=alternate)
    Git integration
      git-status-finder behavior
        it FuzzyFinder file-finder behavior (ripgrep=false, scoringSystem=alternate) Git integration git-status-finder behavior displays all new and modified paths
          timeout: timed out after 60000 msec waiting for condition     at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:1471:11)
      status decorations
        when a modified file is shown in the list
          it FuzzyFinder file-finder behavior (ripgrep=false, scoringSystem=alternate) Git integration status decorations when a modified file is shown in the list displays the modified icon
            TypeError: Attempted to wrap cpus which is already wrapped
              at checkWrappedMethod (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/util/core.js:81:29)
              at Object.wrapMethod (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/util/core.js:121:21)
              at Object.stub (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/stub.js:67:26)
              at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:110:15)
              at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/async-spec-helpers.js:3:20)
              at jasmine.Spec.args.(anonymous function) (/Users/vsts/agent/2.149.2/work/1/s/out/app/spec/jasmine-test-runner.coffee:90:27)
              at <anonymous>
              --------------
              Error: Stack Trace for original
              at Object.wrapMethod (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/util/core.js:140:34)
              at Object.stub (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/stub.js:67:26)
              at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:110:15)
              at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/async-spec-helpers.js:3:20)
              at jasmine.Spec.args.(anonymous function) (/Users/vsts/agent/2.149.2/work/1/s/out/app/spec/jasmine-test-runner.coffee:90:27)
              at <anonymous>
```

**Comment by jasonrudolph** [comment] 2019-04-02 23:29
Hmm. I ran into another similar (but not exactly the same) failure [here](https://github.visualstudio.com/Atom/_build/results?buildId=37034&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=8b9bff53-2841-58c7-68fc-e30c30330fc3&lineStart=2761&lineEnd=2816&colStart=1&colEnd=1):

```
FuzzyFinder
  file-finder behavior (ripgrep=true, scoringSystem=standard)
    toggling
      when the project has multiple paths
        it FuzzyFinder file-finder behavior (ripgrep=true, scoringSystem=standard) toggling when the project has multiple paths shows each file's path, including which root directory it's in
          Error: Timed out waiting on anonymous condition
            at exports.conditionPromise (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/async-spec-helpers.js:46:13)
            at <anonymous>
    Git integration
      git-status-finder behavior
        it FuzzyFinder file-finder behavior (ripgrep=true, scoringSystem=standard) Git integration git-status-finder behavior displays all new and modified paths
          timeout: timed out after 60000 msec waiting for condition     at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:1471:11)
      status decorations
        when a modified file is shown in the list
          it FuzzyFinder file-finder behavior (ripgrep=true, scoringSystem=standard) Git integration status decorations when a modified file is shown in the list displays the modified icon
            TypeError: Attempted to wrap cpus which is already wrapped
              at checkWrappedMethod (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/util/core.js:81:29)
              at Object.wrapMethod (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/util/core.js:121:21)
              at Object.stub (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/stub.js:67:26)
              at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:110:15)
              at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/async-spec-helpers.js:3:20)
              at jasmine.Spec.args.(anonymous function) (/Users/vsts/agent/2.149.2/work/1/s/out/app/spec/jasmine-test-runner.coffee:90:27)
              at <anonymous>
              --------------
              Error: Stack Trace for original
              at Object.wrapMethod (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/util/core.js:140:34)
              at Object.stub (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/stub.js:67:26)
              at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:110:15)
              at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/async-spec-helpers.js:3:20)
              at jasmine.Spec.args.(anonymous function) (/Users/vsts/agent/2.149.2/work/1/s/out/app/spec/jasmine-test-runner.coffee:90:27)
              at <anonymous>
  file-finder behavior (ripgrep=false, scoringSystem=fast)
```

@rafeca: The reference to `cpus` above reminds me of the work in https://github.com/atom/fuzzy-finder/pull/373, but I don't know enough to say whether that's just a coincidence or not. Can you think of any recent fuzzy-finder changes that might be increasing the likelihood of these failures?

**Comment by jasonrudolph** [comment] 2019-04-02 23:32
Another similar (but not _exactly_ the same) failure: 

https://github.visualstudio.com/Atom/_build/results?buildId=37112&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=8b9bff53-2841-58c7-68fc-e30c30330fc3&lineStart=2285&lineEnd=2310&colStart=1&colEnd=1

```
FuzzyFinder
  file-finder behavior (ripgrep=false, scoringSystem=fast)
    Git integration
      status decorations
        when a modified file is shown in the list
          it FuzzyFinder file-finder behavior (ripgrep=false, scoringSystem=fast) Git integration status decorations when a modified file is shown in the list displays the modified icon
            timeout: timed out after 60000 msec waiting for condition     at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:1471:11)
        when a new file is shown in the list
          it FuzzyFinder file-finder behavior (ripgrep=false, scoringSystem=fast) Git integration status decorations when a new file is shown in the list displays the new icon
            TypeError: Attempted to wrap cpus which is already wrapped
              at checkWrappedMethod (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/util/core.js:81:29)
              at Object.wrapMethod (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/util/core.js:121:21)
              at Object.stub (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/stub.js:67:26)
              at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:110:15)
              at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/async-spec-helpers.js:3:20)
              at jasmine.Spec.args.(anonymous function) (/Users/vsts/agent/2.149.2/work/1/s/out/app/spec/jasmine-test-runner.coffee:90:27)
              at <anonymous>
              --------------
              Error: Stack Trace for original
              at Object.wrapMethod (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/util/core.js:140:34)
              at Object.stub (/Users/vsts/agent/2.149.2/work/1/s/node_modules/sinon/lib/sinon/stub.js:67:26)
              at beforeEach (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/fuzzy-finder-spec.js:110:15)
              at jasmine.Spec.<anonymous> (/Users/vsts/agent/2.149.2/work/1/s/node_modules/fuzzy-finder/spec/async-spec-helpers.js:3:20)
              at jasmine.Spec.args.(anonymous function) (/Users/vsts/agent/2.149.2/work/1/s/out/app/spec/jasmine-test-runner.coffee:90:27)
              at <anonymous>
```

**Comment by 50Wliu** [comment] 2019-04-03 04:05
I ran into these failures around 5 times while rebuilding #19085 until I got a green build. The most I saw at once were four failures on the macOS run.

**Comment by rafeca** [comment] 2019-04-03 08:32
> @rafeca: The reference to cpus above reminds me of the work in atom/fuzzy-finder#373, but I don't know enough to say whether that's just a coincidence or not. Can you think of any recent fuzzy-finder changes that might be increasing the likelihood of these failures?

The `os.cpus` error seems to be caused by a previous test failure: if a test fails without cleaning up the `os.cpus` stub correctly the next test will fail when trying to create the stub ([code](https://github.com/atom/fuzzy-finder/blob/master/spec/fuzzy-finder-spec.js#L110)) since Sinon cannot handle this situation.

We're restoring the `os.cpus` stub after each test invocation ([code](https://github.com/atom/fuzzy-finder/blob/master/spec/fuzzy-finder-spec.js#L116)) so this should never happen... but I would not be suprised if there's a bug in the `afterEach` logic in the ancient version of `jasmine` that we're using... I'm gonna investigate it.

The original test failure (at least the most common one from the traces you posted) seems to be coming from https://github.com/atom/fuzzy-finder/blob/master/spec/fuzzy-finder-spec.js#L1471, I'm gonna investigate it... this may (or may not 😅) be related to the upgrade of `git-utils`(maybe the `gitRepository.onDidChangeStatuses` method now gets triggered even before we start listening to it?).

**Comment by rafeca** [comment] 2019-04-03 08:56
> We're restoring the os.cpus stub after each test invocation (code) so this should never happen... but I would not be surprised if there's a bug in the afterEach logic in the ancient version of jasmine that we're using... I'm gonna investigate it.

Ok, I've been able to reproduce the problem: whenever there's a timeout handled by `jasmine` (not by our async-helpers logic that adds promise support to our test suite) on a `beforeEach` method, the `afterEach` method for that test is not executed. This is a repro example of the issue in jasmine:

```js
describe('describe', () => {
  beforeEach(() => {
    console.log('beforeEach')

    // this causes a timeout
    waitsFor((done) => {})
  })

  afterEach(() => {
    // this is never called
    console.log('afterEach')
  })

  it('it code', () => {
    console.log('it code')
  })
})
```

I can workaround this problem by using `conditionPromise()` (not worth to do some archeology in our ancient version of `jasmine` to know when this got fixed there)

**Comment by rafeca** [comment] 2019-04-08 13:52
This has been fixed, closing ☺️

**Closed by rafeca** 2019-04-08 13:52 UTC
Labels: FY2019Q5 deterministic builds, flaky-test
