### ISSUE TITLE
Newly added project folder in tree-view disappears after window:reload

### ISSUE THREAD

**Issue by liuderchi** [atom/atom#13933] opened 2017-03-05 16:10 UTC
From @ungb:

I was able to repro by doing the following:
1. Open a empty Atom window with no project
2. Open context menu and click `Add Project Folder`
3. Add a folder
4. Open command palette and run window:reload

Actual: Atom will reload with empty atom with no project
NOTE: if you open Atom with a project or `atom .` and reload the project will persist.

Expected: project will persist

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Added project folder in tree view would _disappear_ after dispatching command `window:reload` in current beta `1.15-beta-4`;
however, in current stable version `1.14.4` it _shows_ in tree view.

__NOTE__: 
  - this issue happens in both `tree-view`: `0.213.1` and `0.214.1` which are versions along with Atom `1.14.4` and `1.15-beta-4` respectively.
  - if doing `atom.restartApplication()` rather than `window:reload` then added project folder would show.

### Steps to Reproduce

1. `$ atom-beta` in terminal to launch Atom beta
2. atom shows some project folders in tree view from last session
3. add a new project folder to tree view
4. `ctrl-shift-f5` to reload atom

**Expected behavior:**

added new project folder would appear in tree view

**Actual behavior:**

added new project folder disappears in tree view, tree view remains same as in step no.2.

**Reproduces how often:**

always

### Versions

```
$ atom-beta --version
Atom    : 1.15.0-beta4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0~
```

**Comment by damieng** [comment] 2017-03-06 01:00
Confirmed repro on master.

**Comment by WalterGR** [comment] 2017-06-02 17:39
Still repros in the (current) Atom 1.17.0.  Should "in 1.15 beta 4" be removed from this issue's title?

**Comment by WalterGR** [comment] 2017-06-02 17:41
This also repros when exiting Atom and starting it again using `atom .` in a console.

It does not repro when starting Atom again using `atom` nor when starting Atom via Spotlight in OS X / macOS.

**Comment by liuderchi** [comment] 2017-06-05 06:52
> Still repros in the (current) Atom 1.17.0. Should "in 1.15 beta 4" be removed from this issue's title?

I'll update the title to make it noticed.

**Comment by shd101wyy** [comment] 2017-06-05 19:58
yes I meet the same issue.

**Comment by damieng** [comment] 2017-07-10 23:21
@WalterGR Typing `atom .` should only ever start atom with the current folder opened and no other added folders. That's by design.

**Comment by ungb** [comment] 2017-08-22 23:01
@damieng I'm able to repro this on master.  Not sure if this regressed again recently.  Adding to prioritize list for person on reactive duty to look at.

**Comment by kuychaco** [comment] 2017-08-23 23:34
@ungb just to confirm, are you repro-ing using `window:reload`? I thought this was a regression but then came to realize that I was doing a hard refresh of the entire chromium window using `cmd-r` while the dev tools are focused, bypassing Atom's keybinding system.

**Comment by as-cii** [comment] 2017-08-31 15:59
Yeah, I am also unable to reproduce this on master. @ungb: can you post the steps you used to reproduce this?

**Comment by liuderchi** [comment] 2017-08-31 16:41
@as-cii I guess [first paragraph of first comment](https://github.com/atom/atom/issues/13933#issue-211963182) is editted by @ungb, which has some info about reproduction.

**Comment by daviwil** [comment] 2018-01-05 00:23
Magical code elves seem to have fixed this issue for us, @ungb and I cannot reproduce this issue in Atom 1.23.2.  Closing this issue for now, please let us know if you can still repro @liuderchi and we will reopen.  Thanks a lot!

**Closed by daviwil** 2018-01-05 00:23 UTC
Labels: bug, regression

**Comment by ungb** [comment] 2018-01-05 00:24
I was able to repro on 1.17.0 but unable to on latest! if you still see this issue, we'll be having to investigate further!
