### ISSUE TITLE
«File | Open File ...» does not work when there is no window opened

### ISSUE THREAD

**Issue by floverdevel** [atom/atom#15764] opened 2017-09-28 12:30 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Cannot open a file when there is no window opened.

### Steps to Reproduce

1. Open Atom
2. Close All Windows
3. Click on «File | Open File...» (or use the keyboard shortcut, "CMD+O" for me)

**Expected behavior:** The Open dialog appears

**Actual behavior:** Nothing actually happens

**Reproduces how often:** 100% when there is no window opened, 0% when at least one window is already opened

### Versions
macOS Sierra Version 10.12.6 (16G29)

atom --version
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.8.1

**Comment by 50Wliu** [comment] 2017-09-28 13:03
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-09-28 13:03 UTC

**Comment by floverdevel** [comment] 2017-09-28 13:11
It's weird i didn't find this issue using this search :
https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20file%20open%20window%20dialog

Anyway, thank you for your response :)
I subscribed to issue #12508.
