### ISSUE TITLE
Highlight same string as currently selected

### ISSUE THREAD

**Issue by theblacklion** [atom/atom#5433] opened 2015-02-06 10:59 UTC
In my previous text editor I could just select some text/code and would then see all other occurrences highlighted in the view. From there on I could jump to each one by a simple shortcut (it put the selection into the finder and then normal jumping between results could occur).

Would be great to have it also in Atom!

**Comment by 50Wliu** [comment] 2015-02-06 15:02
I know this is a duplicate, but I can't find the issue right now.

**Comment by mark-hahn** [comment] 2015-02-06 22:17
>  I could jump to each one by a simple shortcut

The second part of what you are asking for is in my package
`find-selection`.  I'm pretty sure the first part is available because I
used to use it in Atom.

**Comment by kevinsawicki** [comment] 2015-02-06 22:18
Yeah, I believe this is a duplicate of https://github.com/atom/find-and-replace/issues/138

**Closed by kevinsawicki** 2015-02-06 22:18 UTC

**Comment by theblacklion** [comment] 2015-02-07 13:23
"find-selection" and "highlight-selected" were really the missing parts here. Hope they find their way into the core some time. Thanks for the hints, guys!
