### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 2059Error: Cannot ca...

### ISSUE THREAD

**Issue by dcro** [atom/atom#19123] opened 2019-04-09 07:54 UTC
The issue appeared once Atom lost and regained focus (switched to another app and then switched back to Atom).

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 2059
Error: Cannot call function 'getPosition' on missing remote object 2059
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:221

Error: Cannot call function 'getPosition' on missing remote object 2059
Error: Cannot call function 'getPosition' on missing remote object 2059
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:125:16)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:681550)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:681965)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:286221)
```

### Commands

```
     -3:31.2.0 core:confirm (input.hidden-input)
  2x -3:25.2.0 core:copy (input.hidden-input)
  3x -3:19.2.0 core:undo (input.hidden-input)
     -3:15.5.0 core:paste (input.hidden-input)
     -3:15 core:move-right (input.hidden-input)
     -3:14 core:save (input.hidden-input)
  2x -2:21.7.0 core:undo (input.hidden-input)
     -2:21.3.0 core:save (input.hidden-input)
     -1:22.7.0 core:select-down (input.hidden-input)
     -1:19.5.0 core:cut (input.hidden-input)
     -1:18.2.0 core:undo (input.hidden-input)
     -1:14.1.0 core:save (input.hidden-input)
     -0:22.9.0 find-and-replace:show (input.hidden-input)
  7x -0:21.8.0 core:confirm (input.hidden-input)
     -0:17.8.0 editor:consolidate-selections (input.hidden-input)
     -0:17.8.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
alignment 1.1.5 
api-docs 0.0.6 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-typescript 13.2.1 
base64 0.3.0 
blade-snippets 0.2.0 
busy-signal 2.0.1 
editorconfig 2.3.0 
elasticsearch-client 0.9.5 
file-icons 2.1.31 
ide-php 0.7.18 
intentions 1.1.5 
language-blade 0.41.4 
language-docker 1.1.8 
language-dots 0.0.4 
language-nginx 0.8.0 
language-vue 0.24.0 
laravel 0.7.1 
linter 2.3.0 
linter-eslint 8.5.2 
linter-js-yaml 1.4.4 
linter-php 1.6.0 
linter-phpcs 1.6.13 
linter-stylelint 4.4.3 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
pigments 0.40.2 
pretty-json 2.0.3 
project-manager 3.3.6 
```

**Comment by rsese** [comment] 2019-04-09 22:46
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-09 22:46 UTC
