### ISSUE TITLE
GitHub integration does not work if remote does not contain 'github.com'

### ISSUE THREAD

**Issue by haider-plero** [atom/atom#18442] opened 2018-11-15 12:13 UTC
### Description

GitHub integration does not work if remote does not contain 'github.com'

### Steps to Reproduce

1. Set up a git remote like `git@github-xyz:user/repo.git` which is common if you have multiple GitHub accounts specified in `~/.ssh/config` like:
```
Host github-abc
 HostName github.com
 PreferredAuthentications publickey
 IdentityFile ~/.ssh/gh_rsa_abc

Host github-xyz
 HostName github.com
 PreferredAuthentications publickey
 IdentityFile ~/.ssh/gh_rsa_xyz
```
2. Open GitHub panel in Atom (Ctrl+Shift+8)

**Expected behavior:**
The GitHub panel should show information from GitHub for current repository.

**Actual behavior:**
This message is shown: "This repository does not have any remotes hosted at GitHub.com"

**Reproduces how often:**
100%

### Versions

atom --version
```
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

apm --version
```
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 2.7.15
git 2.17.2
```

**Comment by rsese** [comment] 2018-11-15 22:56
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/github/issues/1010 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-15 22:56 UTC
