### ISSUE TITLE
Atom crashes with saving HTML files on Mac

### ISSUE THREAD

**Issue by paconity** [atom/atom#19511] opened 2019-06-12 17:01 UTC
Hi! I'm starting with coding JS using Atom, but when I try to save the files with ".html" Atom just crashes, I already try to do the same with the safe mode and the problem still in there.
Posdata, I use atom v1.38.0 with a MackBook Pro 2012 (10.10.5).

**Comment by rsese** [comment] 2019-06-12 17:05
Thanks for contributing!

Based on your version of macOS, I think this is a duplicate of https://github.com/atom/atom/issues/19497 so you can subscribe there for updates if you'd like.  You can temporarily disable Tree-sitter as detailed in https://github.com/atom/atom/issues/19497#issuecomment-501311338 as a workaround.

Additionally, for future issues please use the template when opening issues or your issues may be closed.  The information in the issue template is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-12 17:05 UTC
