### ISSUE TITLE
Support touch interfaces

### ISSUE THREAD

**Issue by jrajav** [atom/atom#12772] opened 2016-09-26 03:25 UTC
### Description

Atom currently doesn't support touch interfaces to scroll the editor (though the sidebar scrolls with touch just fine). This probably extends to "precision touchpad" or "natural" scrolling methods as well, which work similarly.

### Steps to Reproduce

1. Touch the screen and wiggle your finger a bit.
2. Observe the dead, unfeeling stillness of the code on your screen.
3. Weep.

### Versions

Atom 1.10.2, Windows Version 10.0.14393 Build 14393

**Comment by thomasjo** [comment] 2016-09-26 08:23
Duplicate of #2209.

**Closed by thomasjo** 2016-09-26 08:23 UTC
