### ISSUE TITLE
Long line results in half-line syntax-highlighting

### ISSUE THREAD

**Issue by TurnOffNOD** [atom/atom#12160] opened 2016-07-13 06:43 UTC
I opened a .sql file generated by mysqldump, in which there is very long lines.

In a very long line, the syntax highlighting will be broken as the screenshot:

<img width="944" alt="screen shot 2016-07-13 at 14 37 47" src="https://cloud.githubusercontent.com/assets/2140029/16794021/d49aaa12-4907-11e6-8d1a-1a50fcaf09b8.png">

Attention the line numbers. It's one line.

A part of the line is rightly syntax-highlighted, but the other part is losing syntax-highlighting.

**Comment by TurnOffNOD** [comment] 2016-07-13 07:03
Sorry, I forgot to say my atom version.
I am using atom 1.8.0 stable, all packages are latest.
(The same with  issue #12161)

**Comment by Zireael07** [comment] 2016-07-13 07:15
It's a limitation of Atom's syntax highlighting for performance reasons - only the first 200 characters or so will be highlighted. I don't remember the issue number, though.

**Comment by thomasjo** [comment] 2016-07-14 07:38
Duplicate of #979 and #1667.

**Closed by thomasjo** 2016-07-14 07:38 UTC
