### ISSUE TITLE
Uncaught Error: spawn /Users/richhagu/Library/Application Support/com.github.atom.ShipIt/update.n...

### ISSUE THREAD

**Issue by richhagu** [atom/atom#9565] opened 2015-11-13 10:19 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/*/Library/Application Support/com.github.atom.ShipIt/update.n14kPkN/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/*/Library/Application Support/com.github.atom.ShipIt/update.n14kPkN/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/*/Library/Application Support/com.github.atom.ShipIt/update.n14kPkN/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/*/Library/Application Support/com.github.atom.ShipIt/update.n14kPkN/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/richhagu/Library/Application Support/com.github.atom.ShipIt/update.n14kPkN/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/richhagu/Library/Application Support/com.github.atom.ShipIt/update.n14kPkN/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/*/dev-code",
    "openEmptyEditorOnStart": false
  },
  "editor": {
    "invisibles": {},
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment] 2015-11-13 17:21
Is your home directory really `/Users/*` or did you replace your username with `*` to obfuscate it in the issue report?

**Comment by 50Wliu** [comment] 2015-11-13 21:26
Closing as a duplicate of #7399, please subscribe there for updates.
However, please still answer @joefitzgerald's question.

**Closed by 50Wliu** 2015-11-13 21:26 UTC
Labels: uncaught-exception
