### ISSUE TITLE
Clipboard issues in 0.189 on Ubuntu 12.04

### ISSUE THREAD

**Issue by xak2000** [atom/atom#6282] opened 2015-04-07 13:38 UTC
After update atom to 0.189 I have several issues with clipboard.

1. If I copy something into clipboard from `atom` editor then I can't paste it in any program except atom. For example into `gedit`.

2. Even worse. If I try to paste it into some text field of any webpage opened in `Google Chrome 41` then Chrome's tab freezes for a long time (several minutes) and then crashes. If I even try to copy some text from webpage opened in `Chrome` while clipboard already contains text copied from `atom` then `Chrome` still freezes (if clipboard contains any value not copied from `atom` then all is ok).

**Comment by Platzer** [comment] 2015-04-07 14:02
do you have sort of vm running? i got the same problem on 14.10 but i had the feeling it's just while my docker container were running...

**Comment by xak2000** [comment] 2015-04-07 14:22
No I haven't any VM's running. I have VirtualBox installed but not running.

**Comment by gau1991** [comment] 2015-04-07 14:27
I am also facing same issue on Fedora 21,
Atom version 0.189

**Comment by pierriko** [comment] 2015-04-07 14:33
Same issue on Ubuntu 14.04.2, atom 0.189.0

**Comment by izuzak** [comment] 2015-04-07 14:36
I believe this is a duplicate of https://github.com/atom/atom/issues/6221 which will be fixed in the next release of Atom (probably out later today).  Let us know if you can reproduce this in 0.190.0 once it's released.

**Closed by izuzak** 2015-04-07 14:36 UTC
