### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.23.3\res...

### ISSUE THREAD

**Issue by Davito3** [atom/atom#16579] opened 2018-01-17 04:18 UTC
[Enter steps to reproduce:]

1. ... Open atom
2. ... Press any key

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Davit\AppData\Local\atom\app-1.23.3\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\Davit\AppData\Local\atom\app-1.23.3\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.23.3/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
  2x -0:19.4.0 core:delete (div.line)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
busy-signal 1.4.3 
emmet 2.4.3 
git-control 0.9.0 
git-plus 7.10.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.5 
language-cpu12 1.4.1 
language-markdown 0.25.1 
linter 2.2.0 
linter-javac 1.9.4 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
markdown-preview-plus 2.4.10 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.3 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
project-manager 3.3.5 
symbol-gen 1.3.1 
sync-settings 0.8.3 
tree-view-git-status 1.4.0 
```

**Comment by rsese** [comment] 2018-01-17 19:01
I think this is a duplicate of issues like #15722. If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled. If you don't have any anti-virus software running, let me know.

**Closed by rsese** 2018-01-17 19:01 UTC
