### ISSUE TITLE
Question: Sort by Stars/Downloads

### ISSUE THREAD

**Issue by boustanihani** [atom/atom#6721] opened 2015-05-10 16:53 UTC
Is it possible to **sort by stars or the number of downloads** when searching packages & themes ?

It would be nice to have this feature for atom and also on the webpage...

**Comment by mark-hahn** [comment] 2015-05-10 18:26
Yes, on atom.io.

**Comment by boustanihani** [comment] 2015-05-10 18:33
How? **I can't find any options for this neither on the packages page nor on the themes page** :(

https://atom.io/packages/search?q=meteor
![search packages](https://cloud.githubusercontent.com/assets/4227548/7555688/9b1bbb48-f753-11e4-852c-7f957daa443c.png)

https://atom.io/themes/search?utf8=%E2%9C%93&q=cobalt
![search themes](https://cloud.githubusercontent.com/assets/4227548/7555690/aa7b55b2-f753-11e4-83bf-5e40959b3c32.png)

**Comment by mark-hahn** [comment] 2015-05-10 19:55
Weird.  I've never seen that page.

This one has what you want.  https://atom.io/packages/list

**Comment by boustanihani** [comment] 2015-05-10 19:58
https://atom.io/packages/list lists all, but **when you search for something you won't be able to sort**, try it.

**Comment by lee-dohm** [comment] 2015-05-10 20:02
Duplicate of your own atom/apm#303.

**Closed by lee-dohm** 2015-05-10 20:02 UTC

**Comment by boustanihani** [comment] 2015-05-10 20:04
sorry I forgot I opened this :)

**Comment by lee-dohm** [comment] 2015-05-10 20:05
:grinning: It's quite alright

**Comment by faddat** [comment] 2015-12-31 06:39
I'd like to second this with a +1,000,000.  This would enable me to choose better packages and whatnot.

**Comment by lee-dohm** [comment] 2015-12-31 06:41
@faddat, this issue is a duplicate of atom/apm#303. Please subscribe there for updates.

**Comment by DomingoMontoya** [comment] 2018-09-20 18:03
Just like to say that I'm shocked this still isn't implemented.
