### ISSUE TITLE
Windows 10: Random Font Blurring

### ISSUE THREAD

**Issue by rolyataylor2** [atom/atom#9161] opened 2015-10-15 17:45 UTC
When working with the editor sometimes the fonts will become blurry randomly for one of the editor items (tabs). When this happens the only way to fix it is to close the item and reopen it, Editing it or changing focus does not help.

    Blurry version:
![2015-10-15_10-34-57](https://cloud.githubusercontent.com/assets/6402800/10522288/3abf0afa-7329-11e5-84e1-2592ed6af77c.png)

    Normal Text:
![2015-10-15_10-35-22](https://cloud.githubusercontent.com/assets/6402800/10522292/4293e84a-7329-11e5-860d-e8c075ddf2eb.png)

**Comment by DuckThom** [comment] 2015-10-15 18:54
This also happens to me when I scroll through the file by selecting text and dragging the cursor slightly outside the editor.
Scrolling with the mouse wheel or dragging the scrollbar fixes the issue for me though.

**Comment by 50Wliu** [comment] 2015-10-16 00:11
This seems to be a duplicate of #8979, so closing in favor of that issue.

**Closed** 2015-10-16 01:47 UTC
Labels: duplicate
