### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 3Error: Cannot call ...

### ISSUE THREAD

**Issue by eliecerthoms** [atom/atom#17003] opened 2018-03-21 00:48 UTC
[Enter steps to reproduce:]

1. Open Atom in a folder

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 3
Error: Cannot call function 'getPosition' on missing remote object 3
    at throwRPCError (C:\Users\edtho\AppData\Local\atom\app-1.25.0\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\edtho\AppData\Local\atom\app-1.25.0\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\Users\edtho\AppData\Local\atom\app-1.25.0\resources\electron.asar\browser\api\web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At C:\Users\edtho\AppData\Local\atom\app-1.25.0\resources\electron.asar\renderer\api\remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 3
Error: Cannot call function 'getPosition' on missing remote object 3
    at throwRPCError (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.25.0/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.25.0/resources/app/src/atom-environment.js:691:40)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.25.0/resources/app/src/atom-environment.js:728:40)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.25.0/resources/app/src/window-event-handler.js:191:32)
```

### Commands

```
```

### Non-Core Packages

```
altgr 0.1.0 
ariake-dark-syntax 0.1.3 
atom-eclipse-syntax 0.0.5 
atom-ternjs 0.18.3 
autumn-highlighter-syntax 1.13.0 
bleen-syntax 0.3.1 
busy-signal 1.4.3 
city-lights-syntax 1.1.3 
city-lights-ui 1.2.0 
emmet 2.4.3 
firewatch-syntax 1.1.1 
ice-cold-syntax 0.1.0 
intentions 1.1.5 
language-babel 2.80.1 
language-graphql 0.9.0 
language-mjml 1.10.0 
language-pgsql 0.2.3 
linter 2.2.0 
linter-mjml 1.2.0 
linter-ui-default 1.6.10 
lorem 1.3.0 
mac-os-ui 0.3.0 
minimap-plus 4.29.2 
mjml-preview 1.4.0 
neon-syntax 0.3.7 
prettier-atom 0.41.0 
seti-ui 1.8.0 
seti-ui-red 0.13.0 
slim-dark-ui 0.12.0 
styri-syntax 0.1.1 
```

**Comment by rsese** [comment] 2018-03-21 19:33
Thanks for the report - this looks like a duplicate of #16630 so you can subscribe there for updates if you'd like.  Also, is the error reproducible for you by just opening a folder in Atom or it just happened to you once?

---

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by rsese** 2018-03-21 19:33 UTC
