### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by ceyhunkerti** [atom/atom#4948] opened 2015-01-09 12:33 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: linux 3.13.0-43-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /usr/share/atom/resources/app/src/project.js:355

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:355:15)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:332:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:286:19)
  at Workspace.module.exports.Workspace.openUriInPane (/usr/share/atom/resources/app/src/workspace.js:485:29)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:412:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
  2x -1:44.1 application:new-file (ul.list-inline.tab-bar.inset-panel)
  2x -1:21.8 tree-view:toggle (atom-text-editor.editor)
     -0:49.6 command-palette:toggle (atom-text-editor.editor)
     -0:45.3 core:confirm (atom-text-editor.editor.mini)
     -0:45.3 settings-view:open (atom-text-editor.editor)
  4x -0:22.9 core:backspace (atom-text-editor.editor)
     -0:21.7 editor:newline (atom-text-editor.editor)
  4x -0:18.8 core:backspace (atom-text-editor.editor)
  2x -0:17.9 core:select-up (atom-text-editor.editor)
     -0:17.3 core:backspace (atom-text-editor.editor)
     -0:00.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-01-09 12:43
Duplicate of https://github.com/atom/atom/issues/4421

**Closed by izuzak** 2015-01-09 12:43 UTC
