### ISSUE TITLE
MarkDown preview skips last empty cell

### ISSUE THREAD

**Issue by yhoogstrate** [atom/atom#8808] opened 2015-09-16 10:25 UTC
When the very last cell of a MarkDown table in the MarkDown preview is empty, the entire cell doesn't show up.

![empty_cell](https://cloud.githubusercontent.com/assets/2264697/9902146/6a5d1424-5c6c-11e5-8e32-8e54345fd188.png)

![4columns](https://cloud.githubusercontent.com/assets/2264697/9902231/158a1ffe-5c6d-11e5-89a0-bbd4a47f2fed.png)

Behavior as expected (without the dot in the last cell):

![non-empty-last-cell](https://cloud.githubusercontent.com/assets/2264697/9902158/7b5c8a52-5c6c-11e5-9c45-f2e3f686b3b0.png)

Atom: 1.0.11
MarkDown preview: 0.150.0
OS: GNU/Linux 3.19.0-28-generic (x86_64)

**Comment by izuzak** [comment] 2015-09-16 10:27
Thanks for the report -- looks like a duplicate of https://github.com/atom/markdown-preview/issues/206 so closing in favor of that.

**Closed by izuzak** 2015-09-16 10:27 UTC
