### ISSUE TITLE
Auto-update doesn't work (OS X)

### ISSUE THREAD

**Issue by winterflags** [atom/atom#9578] opened 2015-11-13 19:22 UTC
When opening Atom, it automatically starts a download of the new version Atom 1.2.0.

After a while, I get the option in the menu to "Restart and Install Update". Atom closes, but when it opens again it's back at "Downloading Update" and the version is still 1.1.0.

No matter how many times I try, I'm stuck in this cycle.

I thought that the package [sync-settings](https://atom.io/packages/sync-settings) might be the offender, but I still have this problem after disabling it. Besides that, I don't have any particular packages of interest to note.

**Comment by mnquintana** [comment] 2015-11-13 19:56
Did you install Atom as an admin, or as a non-admin user?

**Comment by xeron** [comment] 2015-11-13 20:53
I have the same issue.

After manual update to 1.2.0 if I open release notes it still shows "Restart and update" button.

I've installed atom as non-admin user.

**Comment by xeron** [comment] 2015-11-13 20:58
Just removed `~/Library/Application\ Support/com.github.atom.ShipIt` and `~/Library/Application\ Support/Atom` and it fixed this issue.

**Comment by andradei** [comment] 2015-11-13 22:55
Same problem, also installed as local user. Unfortunately OS X doesn't play nicely with the tools Atom is using, like Squirrel.

**Comment by winterflags** [comment] 2015-11-14 16:51
Same here, I haven't installed Atom on an admin account.

Removing `~/Library/Application\ Support/com.github.atom.ShipIt` and `~/Library/Application\ Support/Atom` did work for me last time I had this problem (before updating to 1.1.0), but didn't help this time. I downloaded the new zip from [atom.io](http//www.atom.io) instead.

It's a shame that the update for non-admin users doesn't work smoothly, because it's usually not a problem for other applications. They usually just ask for temporary admin rights when running the update installer.

**Comment by lee-dohm** [comment] 2015-11-15 06:36
I agree that this is a duplicate of the older Issue. Please subscribe to #2860 for updates.

**Closed by lee-dohm** 2015-11-15 06:36 UTC
Labels: more-information-needed
