### ISSUE TITLE
Feature: Progress-bar to display the progress of package update process

### ISSUE THREAD

**Issue by bhaskarmac** [atom/atom#15998] opened 2017-10-26 06:01 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Feature: Progress-bar to display the progress of package update process

### Steps to Reproduce

1. While updating any installed package

**Expected behavior:** [What you expect to happen]
There should be a progress-bar which displayings package update status while updating the isntalled packages

**Actual behavior:** [What actually happens]
No progress-bar is displayed while updating installed packages. I am always waiting for an update to complete or what will be the approx update time for the package.

**Reproduces how often:** [What percentage of the time does it reproduce?]
N.A.
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

atom --verison
Atom : 1.21.1
Electron: 1.6.15
Chrome :  62.0.3202.62
Node : 7.4.0

OS
Windows 10 Pro 32 bit

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment] 2017-10-26 07:59
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/apm#148. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-10-26 07:59 UTC
