### ISSUE TITLE
menu bar can not be see with theme one dark, ubuntu 18.10

### ISSUE THREAD

**Issue by 0x2d3c** [atom/atom#19083] opened 2019-04-01 11:38 UTC

**Comment by rsese** [comment] 2019-04-01 20:34
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/18535 so you can subscribe there for updates if you'd like.  Also see a workaround mentioned in https://github.com/atom/atom/issues/18535#issuecomment-443937472.

Lastly, for future issues please fill out the issue template - the information in the template is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-01 20:34 UTC
