### ISSUE TITLE
naming the packages

### ISSUE THREAD

**Issue by a-atalla** [atom/atom#7646] opened 2015-07-02 07:10 UTC
All the downloadable packages are named   "atom.x86_64.rpm" , could you please specify the  version in the package names , it will be so helpful

Thank you

**Comment by batjko** [comment] 2015-07-02 18:47
I'd agree with that. It's worthwhile for people who want to keep installers for several versions around.

**Comment by mnquintana** [comment] 2015-07-02 19:05
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/4044 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-02 19:05 UTC
