### ISSUE TITLE
peerinvalid error when building in Ubuntu 14.04

### ISSUE THREAD

**Issue by mpancorbo** [atom/atom#9143] opened 2015-10-14 15:04 UTC
I've been compiling and using Atom in my Ubuntu 14.04 box without problems until now. After

```
$ git fetch -p
$ git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
$ script/build
```

I get following error:

```
Node: v0.10.30
npm: v2.13.3
Installing build modules...
npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "node" "/home/manuel/src/atom/build/node_modules/.bin/npm" "--userconfig=/home/manuel/src/atom/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v0.10.30
npm ERR! npm  v2.13.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package grunt@0.4.4 does not satisfy its siblings' peerDependencies requirements!
```

A [full log is provided](https://gist.github.com/mpancorbo/c8920d6dab95e443af68#file-npm-debug-log)

TIA!

**Comment by mpancorbo** [comment] 2015-10-16 16:45
A temporary workaround (it blows up your start up config):
    
    $ git fetch -p
    $ git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
    $ script/clean
    $ script/build

**Comment by lee-dohm** [comment] 2015-10-17 03:22
If a clean build fixes it, I'm not sure that it is a build error? Can you reproduce the issue now?

**Comment by mpancorbo** [comment] 2015-10-17 07:52
The first build after the clean was successful.

But I'll wait some days to update and rebuild (without previous clean) for definitive diagnostic.

**Comment by mpancorbo** [comment] 2015-10-20 10:52
Ok. My "fix" survived an update few days after.

But I don't think it is a serious fix, to force a clean. It destroys local start up config.

**Comment by Ben3eeE** [comment] 2016-12-15 15:45
Looks like this was solved by running script/clean. Closing.

**Closed by Ben3eeE** 2016-12-15 15:45 UTC
Labels: build-error, more-information-needed
