### ISSUE TITLE
Atom does not restore opened files on start when no project folder was opened.

### ISSUE THREAD

**Issue by schtandard** [atom/atom#20500] opened 2020-03-12 20:18 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
After closing Atom with no open project folder, but with open files, the opened files are not restored upon starting Atom. Opening any folder (using Ctrl+Shift+O) resolves the issue, even if the folder is unrelated to the opened files and is empty.

### Steps to Reproduce
1. Install and run Atom.
2. Optional: In the settings, set "Restore Previous Windows On Start" to "always"
3. Open two text files.
4. Close Atom.
5. Open Atom (either from the start menu or from the command line).

**Expected behavior:**
Atom should appear with both previously opened text files opened.

**Actual behavior:**
Only an empty editor is present.

**Reproduces how often:**
Always.

### Versions
- Operating system: Windows 10 Enterprise, 64 bit
- Output from `atom --version`:
  ```text
  Atom    : 1.45.0
  Electron: 4.2.7
  Chrome  : 69.0.3497.128
  Node    : 10.11.0
  ```

**Comment by lee-dohm** [comment] 2020-03-12 20:32
Thank you for reaching out!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13318. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2020-03-12 20:32 UTC
