### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by AgentME** [atom/atom#12408] opened 2016-08-12 19:01 UTC
I was editing a file and hit save. Nothing seemed to go wrong, but Atom opened a large red notification about an error and prompted me to create an issue. I would have done that, but that [triggered an error](https://github.com/atom/notifications/issues/129), so I'm manually making this issue report.

Here's the stack trace it gave me:

```
Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)
    at undefined.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:112:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:631:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:665:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:182:35)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61
```

### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Steps to Reproduce

1. Save a file? I can't reproduce this issue. It just happened once so far.

**Expected behavior:** [What you expected to happen]

No giant red error message.

**Actual behavior:** [What actually happened]

There was a giant red error message.

### Versions

Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by 50Wliu** [comment] 2016-08-12 19:46
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-12 19:46 UTC
