### ISSUE TITLE
Opening Uglify/YUI compressed files with long lines can take seconds

### ISSUE THREAD

**Issue by staaky** [atom/atom#5862] opened 2015-03-05 16:47 UTC
Opening files compressed with UglifyJS or YUI compressor, which put everything on 1 line, can take seconds, even for small files (<100kb). Pasting a line like that into an already open file can also freeze things up. I guess syntax highlighting might have a problem dealing with the long lines.

If it's the syntax highlighting, perhaps that can kick in later so the file can at least be displayed within a reasonable time? Maybe it's a more fundamental problem. It just doesn't feel right to wait around 4 seconds for a 100kb file to load.

**Comment by 50Wliu** [comment] 2015-03-05 17:40
Duplicate of #979, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-05 17:40 UTC
