### ISSUE TITLE
Wrong Ctrl + Delete behavior

### ISSUE THREAD

**Issue by bjdash** [atom/atom#15928] opened 2017-10-18 11:43 UTC
### Description

If in a line I have a couple of tabs followed by some lines of code and I move to the beginning of the line and press Ctrl + Del to remove all the tabs, it also deletes the first word in the line along with the tabs. In most of the editors the behavior is to just remove the tabs at the beginning.

### Steps to Reproduce

1. Write one line with few tabs at the beginning followed by some text. Eg: 
````
            Hi There (few tabs at the beginning)
````
2. Press **Home** button to move to the beginning of the line
3. Press **Ctrl + Del** (windows)

**Expected behavior:** It Should only delete all the tabs at the beginning and the remaining text should be `Hi There`

**Actual behavior:** It deleted all tabs along with the word `Hi`

**Reproduces how often:** Always

### Versions
Version: 1.21.1

**Comment by Tynael** [comment] 2017-10-18 13:13
I also reproduced this issue on Atom 1.2.20-beta1 x64.

**Comment by 50Wliu** [comment] 2017-10-18 15:40
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #4026. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-10-18 15:40 UTC
