### ISSUE TITLE
open a file at a specific line

### ISSUE THREAD

**Issue by X-G** [atom/atom#7342] opened 2015-06-19 09:56 UTC
Running `atom file.tex:100`,  Atom will  open a file called `atom file.tex:100` rather than open `file.tex` at line 100
![qq 20150619115603](https://cloud.githubusercontent.com/assets/6829403/8251122/2392524e-167a-11e5-9b70-d94fb4da6d83.png)
.

**Comment by maxbrunsfeld** [comment] 2015-06-19 17:11
I can't reproduce this; for me, it goes to line 100 of the file. What OS and Atom version are you using? Does this happen if you run Atom with `atom --safe`?

**Comment by X-G** [comment] 2015-06-20 21:15
I'm using Windows10 and Atom 0.210. 
And yes, this will happen even if I run `atom --safe file.tex:100`.

**Comment by lee-dohm** [comment] 2015-06-20 22:11
Reproduced using Atom v0.211.0-fc4f2a1 on Mac OS X 10.10.3.

## Steps to Reproduce

1. Change directory to `$HOME`
1. Execute `mkdir temp`
1. Execute `touch temp/file.tex`
1. **Works as expected:** Start Atom with `atom temp/file.tex:100`
1. Close Atom with <kbd>Cmd+Q</kbd>
1. Change directory to `$HOME/temp`
1. Start Atom with `atom file.tex:100`

**Expected:** Atom opens with the `file.tex` file already open
**Actual:** Atom opens with a new file called `file.tex:100` already open

**Comment by izuzak** [comment] 2015-06-22 08:47
Thanks for the reproduction steps, @lee-dohm. :heart: 

@maxbrunsfeld @mostafaeweda As far as I can tell, the reason why this is happening is [here](https://github.com/atom/atom/blob/e817de4f3f06d16dd6d11bbdcef35c32ab6d9a5b/src/browser/atom-application.coffee#L535):

```coffee
    return {pathToOpen} if url.parse(pathToOpen).protocol?
```

For a path like `foo.txt:100`, `url.parse(pathToOpen).protocol` returns `foo.txt:`, so the check succeeds and the full path is returned (including `:100`), and the logic for splitting the path by `:` isn't even reached.

Wondering if we can work around this case somehow? /cc https://github.com/atom/atom/pull/6978 where this was added.

**Comment by maiklos** [comment] 2015-06-25 19:03
same for me on ubuntu linux.
echo "a\nb\nc\n" > somefile.txt
atom somefile.txt:3

resutlt: opens "somefile.txt:3"
note: "somefile.txt:3" is valid filename under linux
I tried some other linux editors (emacs, vim) and they behave exactly same.

How about to use vim syntax ? instead of :x +x ?
see here: http://www.cyberciti.biz/faq/linux-unix-command-open-file-linenumber-function/

**Comment by Flonker** [comment] 2015-07-01 10:41
Hi!

Atom 1.0.0 on Windows 7 pro here.
No matter how I open the file it allways opens a new file with the ":linenumber".

![image](https://cloud.githubusercontent.com/assets/13133504/8452783/35327696-1fee-11e5-90bf-364ba8371af8.png)

Both tries open a new file called "test.txt:5" according to this screenshot.

![image](https://cloud.githubusercontent.com/assets/13133504/8452685/74e8651c-1fed-11e5-8310-d5c46f019bc8.png)

This is the file:
![image](https://cloud.githubusercontent.com/assets/13133504/8452823/85dbafd6-1fee-11e5-83d0-2ade5b65fdc2.png)

**Comment by samachr** [comment] 2015-07-02 19:23
Same problem here. Really would like to use this feature. Also happens when opening with absolute paths instead of relative.

**Comment by X-G** [comment] 2015-07-02 21:09
+1

**Comment by m0nhawk** [comment] 2015-07-06 12:31
Same problem for me. Hope this will be fixed soon.

**Comment by doggan** [comment] 2015-08-17 23:54
Same issue here. It works properly with some files, and not for other files. I can't figure out what is different in the cases where it works vs when it doesn't work. :cry:

**Comment by doggan** [comment] 2015-08-18 00:10
It seems to work for files with an underscore in their name.

This doesn't work (opens up a file called `dummy1.txt:2` or `dummy-1.txt:2`):
```
shyam@shyam-mac:~$ printf "a\nb\nc\n" > dummy1.txt
shyam@shyam-mac:~$ atom dummy1.txt:2

shyam@shyam-mac:~$ printf "a\nb\nc\n" > dummy-1.txt
shyam@shyam-mac:~$ atom dummy-1.txt:2
```

This works (opens up `dummy_1.txt` to line 2):
```
shyam@shyam-mac:~$ printf "a\nb\nc\n" > dummy_1.txt
shyam@shyam-mac:~$ atom dummy_1.txt:2
```

Hopefully that is helpful info :eyes:

**Comment by jgable** [comment] 2015-08-19 22:00
@doggan :+1: The prepend an underscore to the file workaround also worked for me.

**Comment by m0nhawk** [comment] 2015-08-30 19:47
@doggan It doesn't work for me under Windows with latest (1.0.9) Atom. Thus, it's not a fixed issue and hardly be called a workaround.

**Comment by doggan** [comment] 2015-08-30 20:27
@m0nhawk I don't see anyone claiming it is fixed, hence the reason this issue is still open. My comment was to provide repro information.

**Comment by Xcodo** [comment] 2015-08-31 15:15
+1

Same for me on Windows with Atom 1.0.9.

This is my only issue with moving to Atom at the moment from a combination of Notepad++ and BowPad. Being able to just to specific error lines from an IDE is a massive time saver.

**Closed** 2015-09-03 19:19 UTC
Labels: atom, bug, quality-bogle

**Comment by maxbrunsfeld** [comment] 2015-09-03 19:21
:zap: @izuzak Thanks so much for tracking this down.
