### ISSUE TITLE
Can't use enter key in Atom on xfce/xRDP, Ubuntu 16.04.

### ISSUE THREAD

**Issue by smeans** [atom/atom#16350] opened 2017-12-09 01:38 UTC
This is a weird one. At first I couldn't get Atom to display (fixed using the workaround from issue #4360). Once it ran, I couldn't use the enter key in the editor window. I traced through window-event-handler.js to KeymapManager handleKeyboardEvent(). For some reason, the KeyboardEvent has the key as "Enter" but the code as "Space". I was able to hack it by adding this to my keymap file:
`'space': 'editor:newline'`

**Comment by rsese** [comment] 2017-12-11 22:51
Thanks for the report @smeans, glad you have a workaround!  The information in the issue template is super helpful for us when looking at issues - can you update the issue body with the issue template filled out? For example, it would be really helpful to know what version of Atom you're running and if you tried any of the other debugging suggestions in http://flight-manual.atom.io/hacking-atom/sections/debugging/, especially if you tried starting Atom in safe mode (`atom --safe`). 

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by ssplavec** [comment] 2017-12-30 06:29
I ran into the same problem as @smeans. Used the Keybinding Resolver and received 'Key Binding Resolver: space' when I pressed the Enter key. Copied the entry for 'enter' from Preferences->Keybindings, pasted it into my keymap.cson file and changed 'enter' to 'space'. 

The contents of my keymap.cson file are:
`'atom-text-editor:not([mini])':
  'space': 'editor:newline'`
Now the Enter key works as expected.

I am running Atom version 1.23.1 on Linux Mint 18.2 (MATE). I'm using RDP from a Macbook Pro to remote into the Linux box. I did not try starting Atom in safe mode.

**Comment by Ben3eeE** [comment] 2017-12-30 11:53
Thanks for reaching out!

This is a bug in Chromium where it reports incorrect fields for `KeyboardEvent.key` or `KeyboardEvent.code` when using remote connections. I don't know if anyone created an issue for it on chromium side but we have one here https://github.com/atom/atom-keymap/issues/222 to resolve differently to work around these bugs. For a long term workaround you can create a custom keystroke resolver. See https://discuss.atom.io/t/e-key-acting-as-backspace/37075/16.

---

We noticed that this is a duplicate of https://github.com/atom/atom-keymap/issues/222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-12-30 11:53 UTC
Labels: duplicate
