### ISSUE TITLE
App for Own/NextCloud

### ISSUE THREAD

**Issue by blackcrack** [atom/atom#17950] opened 2018-08-30 05:21 UTC
Hi,

why do you not make a editor/pad-app for Own/NextCloud to have 
a html/php editor in xXx-Cloud :) and maybe for other sourcecodes ..
Atompad maybe ..

best regards
Blacky

**Comment by Arcanemagus** [comment] 2018-09-10 17:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/3088. This is also answered in the FAQ: [Atom in the cloud?](https://discuss.atom.io/t/atom-in-the-cloud/30975).

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-09-10 17:16 UTC
