### ISSUE TITLE
Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

### ISSUE THREAD

**Issue by WangTao0127** [atom/atom#15835] opened 2017-10-07 09:35 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

```
At C:\Users\Administrator\AppData\Local\atom\app-1.21.0\resources\app\src\command-registry.js:361

TypeError: Cannot read property 'webkitMatchesSelector' of undefined
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.0/resources/app/src/command-registry.js:361:30)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.21.0/resources/app/src/command-registry.js:266:23)
    at HTMLAnchorElement.<anonymous> (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/line-ending-selector/lib/main.js:181:25)
```

### Commands

```
  2x -7:55.4.0 application:add-project-folder (atom-pane.pane.active)
     -5:35.7.0 github:toggle-git-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -4:32.7.0 open-on-github:repository (ul.list-inline.tab-bar.inset-panel)
     -3:32.3.0 core:paste (input.hidden-input)
     -3:29.6.0 core:move-left (input.hidden-input)
     -2:53.8.0 tree-view:add-folder (span.name.icon.icon-repo)
     -2:51 core:backspace (input.hidden-input)
     -2:49.9.0 core:confirm (input.hidden-input)
     -2:43.6.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -2:35.8.0 core:confirm (input.hidden-input)
     -0:49.2.0 command-palette:toggle (atom-pane.pane)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-10-09 17:29
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/line-ending-selector/issues/49 so you can subscribe there for updates if you'd like - if you can share what you were doing at the time of the error and if the error is reproducible in the issue, that would be super helpful :v:

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-09 17:29 UTC
Labels: duplicate
