### ISSUE TITLE
Uncaught Error: spawn /Users/kpatel/Library/Application Support/com.github.atom.ShipIt/update.upS...

### ISSUE THREAD

**Issue by kalps1982** [atom/atom#10167] opened 2015-12-23 09:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/kpatel/Library/Application Support/com.github.atom.ShipIt/update.upSog1U/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/kpatel/Library/Application Support/com.github.atom.ShipIt/update.upSog1U/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/kpatel/Library/Application Support/com.github.atom.ShipIt/update.upSog1U/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getSize] (/Users/kpatel/Library/Application Support/com.github.atom.ShipIt/update.upSog1U/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Users/kpatel/Library/Application Support/com.github.atom.ShipIt/update.upSog1U/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:573:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeDefaultWindowDimensions (/Users/kpatel/Library/Application Support/com.github.atom.ShipIt/update.upSog1U/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:605:25)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Users/kpatel/Library/Application Support/com.github.atom.ShipIt/update.upSog1U/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:181:35)
    at /Users/kpatel/Library/Application Support/com.github.atom.ShipIt/update.upSog1U/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-23 13:13
This is a duplicate of #9559, please subscribe there for updates.

**Closed by 50Wliu** 2015-12-23 13:13 UTC
