### ISSUE TITLE
Atom 1.11.2 Background color issue

### ISSUE THREAD

**Issue by NerdPad** [atom/atom#13147] opened 2016-11-04 17:05 UTC
### Prerequisites

* [✔] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [✔] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [✔] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [✔] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [✔] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

The background color seems to have issues while code is open. The background color is blocky when the window is resized. The issue get's worse with other themes.

###Screenshot:
<img width="1045" alt="screen shot 2016-11-04 at 12 27 51 pm" src="https://cloud.githubusercontent.com/assets/87896/20014377/297e1134-a28d-11e6-896a-15ab447c44d0.png">

###Videos
**Test with all my customization**
All my settings can be found here: https://gist.github.com/NerdPad/d3e0c62c4d7af2f4f5bd8d84f0404ef3

https://youtu.be/k3uWnoZtG7E

**Test in safe mode after resetting atom**

https://youtu.be/ei0ofGHqPVI

### Steps to Reproduce

1. Open code and resize window (Check video)

**Expected behavior:** [What you expected to happen]
The background color should be consistent.

**Actual behavior:** [What actually happened]
The background color is inconsistent, and patchy.

### Versions
```
⇨ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by Ben3eeE** [comment] 2016-11-04 17:37
This looks like a duplicate of https://github.com/atom/atom/issues/12634. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-11-04 17:37 UTC
