### ISSUE TITLE
Uncaught Error: EIO: i/o error, open '/Users/sean/remote/workspace-crystal/...

### ISSUE THREAD

**Issue by SeanTater** [atom/atom#7654] opened 2015-07-02 13:45 UTC
1. Open a workspace on a removable or network-attached medium
2. Close Atom
3. Disconnect the medium
4. Open Atom
5. Experience an error while trying to open the workspace. Of course, it shouldn't open. But it shouldn't throw an error either; just ask me to make/open a new workspace.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EIO: i/o error, open '/Users/sean/remote/workspace-crystal/---hidden-package-name---/WebContent/WEB-INF'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:466

Error: EIO: i/o error, open '/Users/sean/remote/workspace-crystal/---hidden-package-name---/WebContent/WEB-INF'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:371:27)
    at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:449:31)
    at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:375:19)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:46:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by batjko** [comment] 2015-07-02 18:43
Potential duplicate of https://github.com/atom/atom/issues/7203.

Also relevant: https://github.com/atom/atom/issues/6974

**Closed** 2015-07-08 22:57 UTC
Labels: uncaught-exception
