### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.25.1\res...

### ISSUE THREAD

**Issue by allancth** [atom/atom#17099] opened 2018-04-08 03:15 UTC
[Enter steps to reproduce:]

Not sure what happened. Last thing changed was styling for the scrollbar in styles.less. All keyboard input will result in this error.

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\[username]\AppData\Local\atom\app-1.25.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\[username]\AppData\Local\atom\app-1.25.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.25.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.25.1/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
```

### Non-Core Packages

```

```

__EDIT:__ The node_module __keyboard-layout__ does not exist 1.25.1. It is available in 1.25.0. Copying the module from 1.25.0 to 1.25.1 makes the error goes away. Not sure if it is a legit fix.

**Comment by rsese** [comment] 2018-04-09 18:03
I think this is a duplicate of issues like #15722. If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled. If you don't have any anti-virus software running, let me know.

**Closed by rsese** 2018-04-09 18:03 UTC

**Comment by allancth** [comment] 2018-04-09 23:51
@rsese Thanks for the response. I do not have any 3rd party anti virus installed. But I did run a file scan for threats with the OS threat scanner several days ago.

**Comment by rsese** [comment] 2018-04-10 17:54
:+1:  

It sounds like you have a workaround, but if you have any trouble, folks have also mentioned that reinstalling should fix things up as well.
