### ISSUE TITLE
unresponsive on loading big files

### ISSUE THREAD

**Issue by tomquas** [atom/atom#7729] opened 2015-07-06 09:15 UTC
copy-pasting the content of the minified css below files make atom unresponsive for ~20secs. atom helper load goes up to 100%

reporter-ohne-grenzen.de/fileadmin/templates/assets/dist/style.min.css

**Comment by izuzak** [comment] 2015-07-06 09:21
Thanks for the report -- I believe this is a duplicate of https://github.com/atom/atom/issues/979.

**Closed by izuzak** 2015-07-06 09:21 UTC
