### ISSUE TITLE
Gherkin fail to toggle comment 

### ISSUE THREAD

**Issue by wellsonjain** [atom/atom#11453] opened 2016-04-14 00:38 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When I tried to toggle comment (`cmd+/`) in cucumber gherkin, it doesn't work even I use it from menu bar. I have to put # to each line. I switched to safe mode and it's the same problem.

### Steps to Reproduce

1. Create a new file, and set grammar to "Gherkin" 
2. Type in "Scenario: title"
3. Press `cmd+/`

**Expected behavior:** [What you expected to happen]
That line should be commented 
**Actual behavior:** [What actually happened]
no effect 
### Versions
Atom    : 1.7.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by wingyplus** [comment] 2016-07-13 13:16
@wellsonjain What do you use language plugin for gherkins?

**Comment by thomasjo** [comment] 2016-07-14 07:28
As @wingyplus asked, we need to know what package you are using for Gherkin files, since there's no bundled language (AFAIK) that provides such support. Once we know what package you're using, we can check if the bug is in that package or not.

**Comment by wellsonjain** [comment] 2016-07-14 07:52
I'm using [cucumber](https://github.com/edda/cucumber-atom) package. And just checked the repository and found there is a same [issue](https://github.com/edda/cucumber-atom/issues/15).  This package seems not to be maintained anymore...

**Comment by thomasjo** [comment] 2016-07-14 08:13
Then I'm closing this issue since the problem isn't on our end.

As for the package not being maintained, maybe you or someone else in the community should fork it, fix the problem, and publish an updated package (you'll need to use another name).

**Closed by thomasjo** 2016-07-14 08:13 UTC
Labels: more-information-needed

**Comment by edda** [comment] 2016-12-30 16:46
Hi,

I've updated the package. Toggling a comment now works as expected. (From v0.6.0)

**Comment by rocel** [comment] 2017-01-24 16:17
@edda thank you very much ! it works like a charm.
