### ISSUE TITLE
Using Atom as git editor on Windows 10 is broken

### ISSUE THREAD

**Issue by kevinkuszyk** [atom/atom#12109] opened 2016-07-06 09:18 UTC
### Description

I've set Atom to be my git editor using the following command from the [GitHub docs](https://help.github.com/articles/associating-text-editors-with-git/):

```
git config --global core.editor "atom --wait"
```

When I run an interactive git command, Atom doesn't open the text file and and error is displayed on the console.

### Steps to Reproduce

1. Set Atom as your git editor: `git config --global core.editor "atom --wait"`
2. Run a git command which needs input: `git rebase branch -i`

**Expected behavior:** Atom opens with the git rebase text file.

**Actual behavior:** It fails with this error message:

```
'ebase-merge' is not recognized as an internal or external command,
operable program or batch file.
```

### Versions

Atom versions:

```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
````

- Windows 10 Enterprise 64bit, build 10240.
- git version 2.9.0.windows.1.

**Comment by lee-dohm** [comment] 2016-07-06 22:27
This is a duplicate of https://github.com/atom/atom/issues/12032. See the solution mentioned here https://github.com/atom/atom/issues/12032#issuecomment-228371403.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

**Closed by lee-dohm** 2016-07-06 22:27 UTC

**Comment by kevinkuszyk** [comment] 2016-07-07 08:01
Thanks @lee-dohm - I didn't see that other issue when I searched.

FWIW - changing my git config to this fixed it for me:

```
git config --global core.editor "'%localappdata%\atom\bin\atom.cmd' --wait"
```
