### ISSUE TITLE
File > Open... only works with a window open on Mac

### ISSUE THREAD

**Issue by ericchernuka** [atom/atom#14623] opened 2017-05-24 14:15 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If Atom has no open windows and just the menu bar interface.  Clicking File > Open... or File > Reopen Project does nothing.

### Steps to Reproduce

1. Close all windows, but still leave Atom in an open state.
2. Click File > Open
3. That's it.

**Expected behavior:** The file dialogue opens.

**Actual behavior:** Nothing. The command silently fails.

**Reproduces how often:** 100%

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0

### Additional Information
I've tried seeing the log out of the Console app, but it receives nothing.  Tested the same scenario on 1.18 and it produces the same issue.

**Comment by 50Wliu** [comment] 2017-05-24 14:21
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-24 14:21 UTC

**Comment by ericchernuka** [comment] 2017-05-24 14:24
@50Wliu Sorry about that. I did search before-hand, but must have missed this one.
