### ISSUE TITLE
Serious energy consumption problem when animating.

### ISSUE THREAD

**Issue by Micooz** [atom/atom#7705] opened 2015-07-04 07:49 UTC
Atom version: 1.0.0
OS: OS X 10.10.3

I found an energy consumption problem when I install or upgrade packages.
Atom shows animation when I click the Install or Update buttom, and it will cause a high CPU consumption:

<img width="471" alt="qq20150704-2 2x" src="https://cloud.githubusercontent.com/assets/8897063/8507071/ae488c22-2265-11e5-9576-3e70a3698fe8.png">

The impact on energy consumption has risen to 234.6 in total.Under normal circumstances, it won't be so dramatic.

Have any idea about these issue or how can I find the solution to this problem?

**Comment by 50Wliu** [comment] 2015-07-04 16:12
This is a duplicate of atom/settings-view#555 and atom/settings-view#546.  Please subscribe there for updates.

**Closed by 50Wliu** 2015-07-04 16:12 UTC
