### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 172.31.1.246:8080

### ISSUE THREAD

**Issue by zhengyanhu** [atom/atom#14086] opened 2017-03-29 06:50 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 172.31.1.246:8080

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 172.31.1.246:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -4:49.8.0 core:copy (input.hidden-input)
  3x -4:16.2.0 core:backspace (input.hidden-input)
     -4:13.9.0 core:confirm (input.hidden-input)
     -2:26.4.0 core:backspace (input.hidden-input)
     -2:24.1.0 core:confirm (input.hidden-input)
  9x -2:16.9.0 core:backspace (input.hidden-input)
  2x -2:14.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.2.5 
emmet 2.4.3 
minimap 4.26.8 
```

**Comment by zhengyanhu** [comment] 2017-03-29 06:50
error

**Comment by rsese** [comment] 2017-03-29 17:51
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14056. You may want to subscribe there for updates.  If you can share some information in that issue, that would be great:

* what were you doing at the time of the error
* is the error reproducible
* if reproducible, is the error reproducible in safe mode (`atom --safe`)

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-29 17:51 UTC
