### ISSUE TITLE
Editor Freeze constantly 

### ISSUE THREAD

**Issue by edwinwong90** [atom/atom#13394] opened 2016-12-06 08:30 UTC
This is really frustrating when i open Editor and freeze it there until the system prompt me to say keep waiting or close it down. 

I google it out, there is only one way that work for me which is delete the folder c://users/users/.atom/storage then open the editor.

although, it works but it still not a long term solution, whenever my editor is freezing and i delete that folder. Also, my recently files open and project is gonna so i need to re-add my project folder.

Please Advice if have any better solution. I hope this issue will rectify soon!

I using Window 10, 32-bit, my editor version 1.12.6

**Comment by Ben3eeE** [comment] 2016-12-06 10:06
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12983. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-06 10:06 UTC
