### ISSUE TITLE
Code blinks when moving cursor

### ISSUE THREAD

**Issue by borishere** [atom/atom#17197] opened 2018-04-21 19:29 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Do a mouse click on code or move cursor with a keyboard - code will blink
![7](https://user-images.githubusercontent.com/4622497/39087983-c3f8012e-45b2-11e8-9db0-111ee79f5db1.gif)

### Steps to Reproduce

1. Do a mouse click on code or move cursor with a keyboard

**Expected behavior:** No blinking

**Actual behavior:** Code will blink

**Reproduces how often:** 100%

### Versions

c:>atom --version

Atom : 1.26.0
Electron: 1.7.11
Chrome : 58.0.3029.110
Node : 7.9.0

c:>apm --version
apm 1.19.0
npm 3.10.10
node 6.9.5 x64
atom 1.26.0
python 2.7.14
git 2.13.0.windows.1
visual studio

Windows 10 Pro 64-bit [Version 10.0.16299.371]

**Comment by rsese** [comment] 2018-04-23 16:51
Thanks again for reporting!

This looks like a duplicate of https://github.com/atom/atom/issues/15626, see Nathan's comment for a summary https://github.com/atom/atom/issues/15626#issuecomment-338801822.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-23 16:51 UTC
