### ISSUE TITLE
Can't switch tabs with keyboard when tree view is focused

### ISSUE THREAD

**Issue by chbk** [atom/atom#15075] opened 2017-07-22 13:33 UTC
Running Atom 1.18.0 on OS X 10.10.5

Using keyboard shortcuts <kbd>⌘</kbd>+<kbd>⌥</kbd>+<kbd>←</kbd> and <kbd>⌘</kbd>+<kbd>⌥</kbd>+<kbd>→</kbd> doesn't switch tabs when the tree view is focused.

I have keyboard shortcuts assigned to specific gestures on the mac trackpad and they should work everywhere in the app, regardless of where the cursor is. This is also inconsistent behavior as closing and reopening tabs with <kbd>⌘</kbd>+<kbd>W</kbd> and <kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>T</kbd> works as intended.

### Steps to Reproduce

With 2 file tabs open and the tree view visible:

1. Click to focus the tree view.
2. Use <kbd>⌘</kbd>+<kbd>⌥</kbd>+<kbd>←</kbd> to switch to previous tab.

**Expected behavior:** To switch to previous tab.

**Actual behavior:** Tab switching doesn't work with that key combo.

**Comment by rsese** [comment] 2017-08-02 00:51
Thanks @chbk :+1:

I can reproduce with 1.18.0 on macOS 10.12.6, going to tag as a bug for now since it seems inconsistent like you mentioned based on how other functions work with tree view focused.  I went ahead and added steps to reproduce in the issue body as well.

**Comment by rsese** [comment] 2017-08-08 23:53
I went ahead andI brought this up with the team and it looks like though some folks agree that it could be useful to be able to switch file tabs with the tree view focused, things are working as expected for a dock like the tree view.  Though it could be a possible enhancement in the future (providing an option that enables this behavior), it's not something that would happen soon so we're going to close it for now.

**Closed by rsese** 2017-08-08 23:53 UTC
Labels: bug, triaged
