### ISSUE TITLE
Cursor bug after upgrading to OSX el capitan

### ISSUE THREAD

**Issue by stresslimit** [atom/atom#9363] opened 2015-10-30 21:30 UTC
My cursor is now 1 character off to the right of where it's supposed to be, immediately after upgrading to OSX 10.11.1 "El Capitan"; I've disabled all community plugins and still see the bug, but opening in `atom --safe` shows the cursor working as normal. I have no linked packages, no dev packages, no errors in developer tools, nothing of note in `config.cson`. 

Any ideas?

![atom-cursor-bug](https://cloud.githubusercontent.com/assets/199718/10858482/c5ef0950-7f2b-11e5-80c9-bae68f00e491.gif)

**Comment by izuzak** [comment] 2015-10-30 21:40
Hey @stresslimit -- I think this is a duplicate of #9343. Can you take a look in there and let us know if your problem is not covered by that? Seems like a problem with the seti syntax theme after upgrading to Atom 1.1

**Closed by izuzak** 2015-10-30 21:40 UTC

**Comment by stresslimit** [comment] 2015-10-31 01:23
Indeed, thanks so much! Solved by https://github.com/jesseweed/seti-syntax/issues/106
