### ISSUE TITLE
Nested projects result in Atom opening files in wrong project window

### ISSUE THREAD

**Issue by johnbillion** [atom/atom#15293] opened 2017-08-14 07:40 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

A project which contains another project within a subdirectory can result in files being opened in the incorrect project window.

Given a main project at `/project`, and another project at `/project/subproject`. Upon opening a file from Finder, Atom doesn't open the file in the correct project window if one of the other project windows is already open.

This can result in a file at `/project/subproject/file.txt` being opened in the `/project` project window.

### Steps to Reproduce

1. Open a new window in Atom, and add a directory as a project folder.
2. Repeat this step, adding a directory which is a subdirectory of the first.
3. Close the second project window.
3. In macOS Finder, open a file which lives in the subdirectory.

**Expected behavior:**

Atom opens the project window for the subdirectory project and opens the file.

**Actual behavior:**

Atom opens the file in the existing project window for the root directory project.

**Reproduces how often:**

Every time.

### Versions

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS      : macOS 10.12.3 

### Additional Information

Note that if you already have both project windows open, the problem does not appear to occur.

**Comment by rsese** [comment] 2017-08-14 17:56
Thanks for the report!  So though I can reproduce with your steps, I'm not sure it's related to the nested projects?  E.g. if I have I have some project open (and the project root isn't the parent of the project in your step 2) and then continue on with your steps to reproduce, Atom will open the file in the currently open project whatever it is.

If I have no windows open or I have a window open with no project, then if open the file in the subdirectory from Finder (your step 4), it will open the project at the subdirectory.

**Comment by johnbillion** [comment] 2017-08-14 18:30
Ah you're correct, this bug doesn't rely on nested projects. Any file that you open will open in the currently open project window if its own project isn't open.

Is this expected behaviour?

**Comment by rsese** [comment] 2017-08-15 04:01
> Is this expected behaviour?

I feel like it is (or at least the behavior hasn't changed as of 1.19.0) but I'll double check with the other maintainers.

**Comment by rsese** [comment] 2017-08-15 19:57
@johnbillion - so it looks like it's expected behavior but understandably can be unexpected for some folks.  For now we'll close this in favor of https://github.com/atom/atom/issues/10517 which is a high level issue about Atom's startup story.

**Closed by rsese** 2017-08-15 19:57 UTC
