### ISSUE TITLE
Bad 'Save As' dialog behaviour in atom version 1.15.0

### ISSUE THREAD

**Issue by Josca** [atom/atom#14055] opened 2017-03-24 09:21 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Wrong direction in Save As dialog.

### Steps to Reproduce

1. Run in command line 'atom hello.txt'.
2. Try to 'Save As' (from menu or Ctrl + Shift + S).

**Expected behavior:** In dialog should be path to hello.txt.

**Actual behavior:** I am requested to specify file path manually.

**Reproduces how often:** Always.

### Versions
Atom    : 1.15.0
OS: Ubuntu 16.04

### Additional Information
I solved it downgrading to atom version 1.14.4.

**Comment by Ben3eeE** [comment] 2017-03-24 09:43
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13978. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-03-24 09:43 UTC
Labels: duplicate
