### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by pierretusseau** [atom/atom#6783] opened 2015-05-14 15:53 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Pierre\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -1:42.1.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:54.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -0:52.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  9x -0:46.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:44.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.7.0 find-and-replace:show-previous (atom-text-editor.editor.mini.is-focused)
     -0:42.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:34.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:30.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:28.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.7.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:22.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:12 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:12 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "twilight-syntax"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "fontSize": 13,
    "showIndentGuide": true,
    "softWrap": true,
    "tabLength": 3,
    "scrollPastEnd": true
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-color-highlight, v3.0.9
autocomplete-plus, v2.15.2
emmet, v2.3.9
file-icons, v1.5.5
linter, v0.12.2
minimap, v4.8.0
seti-ui, v0.7.1
Sublime-Style-Column-Selection, v1.2.3
twilight-syntax, v0.7.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-14 16:44
Duplicate of #6548, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-14 16:44 UTC
