### ISSUE TITLE
Segmentation fault and block with last update

### ISSUE THREAD

**Issue by analca3** [atom/atom#11501] opened 2016-04-17 08:46 UTC
* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When launching atom in whatever folder, it gets stuck and it doesn't respond. Even with safe mode.

![image](https://cloud.githubusercontent.com/assets/3939991/14585989/4748dbec-0489-11e6-8655-16ad15fe5220.png)

The terminal output:

```
[antonio@Antonio-ArchG MH2015-16]$ atom --safe .
[antonio@Antonio-ArchG MH2015-16]$ /usr/bin/atom: línea 123:  2289 Violación de segmento  (`core' generado) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ $ATOM_USER_FLAGS "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 281ms
Failed to get crash dump id.
Report Id: 
ALSA lib pcm_dmix.c:1029:(snd_pcm_dmix_open) unable to open slave
Failed to get crash dump id.
Report Id: 

```

### Steps to Reproduce

1. Launch Atom

**Expected behavior:** Atom launchs correctly.

**Actual behavior:** I can't code :(.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.
```
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
-------
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.0
---------
ArchLinux x64_86
```

It's related to https://github.com/atom/atom/issues/11444 and https://github.com/atom/atom/issues/11198 ? I can't downgrade easily freetype2 because I'm using Infinality.

**Comment by ijanos** [comment] 2016-04-17 11:50
Same here, also on Arch Linux 64 bit. Here is the segfault in engish:


`/usr/bin/atom: line 123:  6425 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ $ATOM_USER_FLAGS "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 1199ms
Failed to get crash dump id.
Report Id: 
Failed to get crash dump id.
Report Id: `

And a not too helpful stacktrace: 

    Process 6425 (atom) of user 1000 dumped core.
    Stack trace of thread 6425:
    #0  0x00007f2d619c4548 _ZN2v86String11NewFromUtf8EPNS_7IsolateEPKcNS0_13NewStringTypeEi (libnode.so)
    #1  0x0000000002eddb67 _ZN4mate12EventEmitter13EmitWithEventIJEEEbRKN4base16BasicStringPieceISsEEN2v85LocalINS7_6ObjectEEEDpRKT_
    #2  0x0000000002eddaa2 _ZN4mate12EventEmitter14EmitWithSenderIJEEEbRKN4base16BasicStringPieceISsEEPN7content11WebContentsEPN3IPC
    #3  0x0000000002f22e98 _ZThn72_N4atom3api6Window22OnRendererUnresponsiveEv (atom)
    #4  0x0000000002f360a7 _ZN4atom12NativeWindow24NotifyWindowUnresponsiveEv (atom)
    #5  0x0000000001ae1683 n/a (atom)
    #6  0x0000000001afcceb n/a (atom)
    #7  0x0000000001afcff9 n/a (atom)
    #8  0x0000000001afd4b3 n/a (atom)
    #9  0x0000000001ad65c0 n/a (atom)
    #10 0x00007f2d5cf54f07 g_main_context_dispatch (libglib-2.0.so.0)
    #11 0x00007f2d5cf55160 n/a (libglib-2.0.so.0)
    #12 0x00007f2d5cf5520c g_main_context_iteration (libglib-2.0.so.0)
    #13 0x0000000001ad6476 n/a (atom)
    #14 0x0000000001b103e0 n/a (atom)
    #15 0x000000000225b4fb n/a (atom)
    #16 0x000000000225b440 n/a (atom)
    #17 0x000000000225e55d n/a (atom)
    #18 0x00000000022567f3 n/a (atom)
    #19 0x00000000010a9fa1 n/a (atom)
    #20 0x00000000010a8e80 n/a (atom)
    #21 0x0000000002ea74bc main (atom)
    #22 0x00007f2d5abb5710 __libc_start_main (libc.so.6)
    #23 0x0000000000539c59 _start (atom)

**Comment by Chronoes** [comment] 2016-04-17 12:26
Also on Arch Linux 64bit. Downgrading to freetype2-2.6.2-1 fixed it for me.

**Comment by danReynolds** [comment] 2016-04-18 03:26
Also on Ubuntu 14.04 for me. Haven't resolved yet.

**Comment by 50Wliu** [comment] 2016-04-18 12:43
Closing as a duplicate of #11198 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-18 12:43 UTC
