### ISSUE TITLE
Impossible to type a curly bracket / brace closing, on Windows with French keyboard

### ISSUE THREAD

**Issue by ghusse** [atom/atom#8747] opened 2015-09-10 19:23 UTC
Hi

I'm using atom editor on Windows, with a french keyboard.

When I'm using atom, it's impossible for me to type closing curly braces `}` in the editor. As you can see, they are working otherwise.

Curly brackets are typed with `alt-g =` on the french keyboard

![azerty](https://cloud.githubusercontent.com/assets/527245/9798563/0a9c8196-5802-11e5-86da-2380cdb3663e.png)

As you can imagine, this is quite annoying!

I don't see in my key bindings anything that could cause this issue:

![keybindings](https://cloud.githubusercontent.com/assets/527245/9798585/34f1d98c-5802-11e5-90fd-69c9bf58c690.png)

Do you have any idea?

**Comment by mnquintana** [comment] 2015-09-10 19:24
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom-keymap/issues/35 – please subscribe there for updates.

**Closed by mnquintana** 2015-09-10 19:24 UTC

**Comment by JosipHaboic** [comment] 2016-08-19 20:22
Meh... lame...
Back to notepad++
