### ISSUE TITLE
[build script] lack of 'break' on switch statement on codeSign phase

### ISSUE THREAD

**Issue by t9md** [atom/atom#16663] opened 2018-02-01 05:04 UTC
Noticed while reading build script.

https://github.com/atom/atom/blob/287b554d637dec1ff1d53ef25e33fa113e5fc913/script/build#L82-L121

Lack of **break** in `switch` statement.
Cause unwanted fallthrough.
Platform `darwin` matches, `win32` and `linux` too.

### Steps to Reproduce

Just evaluated following code snippet

```javascript
function test() {
  switch ('hello') {
    case 'hello': {
      console.log('hello')
    }
    case 'world': {
      console.log('world')
    }
    default: {
      console.log('bye')
    }
  }
}
test()

//--- output is bellow ---------
// hello
// world
// bye
```

**Comment by victor-cordova** [comment] 2018-02-16 14:48
@t9md  that is actually the intended behavior of the switch block. There are times where such as fallthrough is useful. Best explained [here](https://youtu.be/ftQjEw2RjC4?t=2m30s)

**Comment by t9md** [comment] 2018-02-16 15:16
I'm saying lack of `break` in each clause is BUG(although it harmless in current build script).
Maybe author just forget to `break`.

**Comment by lee-dohm** [comment] 2018-10-23 20:38
This was fixed in the intervening time span. Thanks for bringing it to our attention @t9md :bow:

**Closed by lee-dohm** 2018-10-23 20:38 UTC
