### ISSUE TITLE
Cursor focusses background when switching from ⌘+P to ⌘+⇧+P

### ISSUE THREAD

**Issue by rmehner** [atom/atom#15635] opened 2017-09-13 10:03 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Cursor jump

### Steps to Reproduce

1. Use ⌘+P (or ⌘+T, doesn't matter) to bring up the file navigation
2. Use ⌘+⇧+P to bring up the commands menu
3. Start typing

**Expected behavior:**

I type in the command and the list is fuzzy searched by what I've typed.

**Actual behavior:**

The list is not searched, because it has lost focus. Instead the editor in the background is focussed and receives my input.

Maybe this GIF helps to illustrate the problem a bit: 
![atom-focus-bug](https://user-images.githubusercontent.com/82050/30371495-0e0f941a-987b-11e7-9725-1d3ee3477962.gif)

**Reproduces how often:** 100%

### Versions

`atom --version`:

Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

`apm --version`:

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.

OSX 10.12.6

### Additional Information

Thanks all involved for your hard work, I use Atom daily and can't wait for the IDE to land with the next release :)

**Comment by rsese** [comment] 2017-09-13 18:31
Thanks for taking the time to contribute!  Thanks for the kind words, we do appreciate it :bow: 

About this issue, we noticed it's a duplicate of https://github.com/atom/atom/issues/15616 (which was in turn closed as a duplicate of https://github.com/atom/atom/issues/14325). You can subscribe there for updates if you'd like.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-13 18:31 UTC
