### ISSUE TITLE
ARM port?

### ISSUE THREAD

**Issue by SConaway** [atom/atom#17876] opened 2018-08-17 00:23 UTC
An ARM port for `Atom` would be nice and it would allow people to use the wonderful editor on low cost platforms as the Raspberry Pi. `Electron` already supports ARM. I'd be willing to help port this if any work is needed, although some pointers on the code would be helpful.

**Comment by 50Wliu** [comment] 2018-08-17 01:10
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15881. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-08-17 01:10 UTC

**Comment by SConaway** [comment] 2018-08-17 01:36
Odd. I searched for `arm`-related issues and didn't find that. Is there any hope/want to do this?

**Comment by 50Wliu** [comment] 2018-08-17 02:43
This isn't something that the Atom team is working on at the moment, though that doesn't mean that it won't happen.
