### ISSUE TITLE
Scrolling does not work in tree-view/settings after some time

### ISSUE THREAD

**Issue by malnvenshorn** [atom/atom#19756] opened 2019-08-06 20:05 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After some time working with atom it is not possible to scroll with the mouse wheel anymore within the tree-view and settings pane. Scrolling in files is still working.

### Steps to Reproduce

1. Start Atom
2. Load project
3. Start working
4. Wait...

**Expected behavior:** [What you expect to happen]

That the scrolling works

**Actual behavior:** [What actually happens]

Scrolling stops working

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%, but the time till this happens varies

### Versions

```
atom --version
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm --version
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 2.7.16
git 2.22.0
```

### Additional Information

Unfortunately I haven't found out what triggers this behavior.

**Comment by rsese** [comment] 2019-08-07 17:18
Aside from the version details, I went ahead and copied over the issue template from https://github.com/atom/atom/issues/18780, it easier for us that way.

Looking at that issue again, it looks like from your last [comment](https://github.com/atom/atom/issues/18780#issuecomment-460667062), after installing the official 1.34.0 .deb, you stopped seeing this behavior.  Did you start seeing it again after installing 1.39.1 or did you see it before then?

And it's still the case that you can reproduce in safe mode?

**Comment by malnvenshorn** [comment] 2019-08-07 20:13
Yes it was gone after I installed the official 1.34.0, but now I'm seeing it again with 1.39.1. It also happens in safe mode, so it is not caused by a third party package.

**Comment by rsese** [comment] 2019-08-07 21:31
> Yes it was gone after I installed the official 1.34.0, but now I'm seeing it again with 1.39.1.

Sorry just to clarify - from 1.34 to 1.39.0 you didn't see any issues but the problem started again specifically with 1.39.1?  If you install 1.39.0 again, the problem goes away?

**Comment by malnvenshorn** [comment] 2019-08-07 21:46
Never had 1.39.0 installed, I updated from 1.38.2 to 1.39.1

**Comment by rsese** [comment] 2019-08-07 23:58
> Never had 1.39.0 installed, I updated from 1.38.2 to 1.39.1

Ok I would guess you would have the same issue on 1.39.0 since there was an Electron upgrade (from Electron 2 to Electron 3) in 1.39.0 - so it sounds like 1.38.2 was the last version where you didn't see this issue.

Can you try the latest [nightly version](https://atom.io/nightly) (after installing you start it with `atom-nightly` instead of `atom`)?

The current nightly is on Electron 4 so I wonder if the issue is resolved for you there.

**Comment by malnvenshorn** [comment] 2019-08-08 11:01
Testing the nightly build and haven't noticed the issue so far.

```
Atom    : 1.41.0-nightly8
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

Does that mean it is an Electron bug? If so it might be the wrong choice to use the Electron framework. The Electron version(s) used before Atom 1.39 have the annoying bug that the menu text is unreadable, now the scrolling issue. Don't know what surprises will come with the Electron version shipped with the final release of Atom 1.41 :disappointed:  

Is there a plan when Atom 1.41 will be released? Going back to 1.38.2 is not very appealing.

**Comment by ONDABOX** [comment] 2019-08-09 18:40
I have been having the same issue. The temporary fix is to close and reopen the program, or use another application.

**Comment by zacwitte** [comment] 2019-08-21 19:45
I can confirm the same issue. It's fixed by restarting atom, but this is quite annoying.

```
atom --version
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

**Comment by igloro** [comment] 2019-08-22 06:56
Same problem here:

> Atom :1.40.1
>Electron: 3.1.10
>Chrome: 66.0.3359.181
>Node: v10.2.0

People write that possible solution is to change theme "atom-material-ui" if you are using one... ( https://github.com/atom/atom/issues/14230 or https://discuss.atom.io/t/tree-view-does-not-scroll-in-1-17-0-beta0-and-1-17-0-beta1/41733/4 )

Will try this one.

**Comment by bugstamp** [comment] 2019-08-22 07:26
> Same problem here:
> 
> > Atom :1.40.1
> > Electron: 3.1.10
> > Chrome: 66.0.3359.181
> > Node: v10.2.0
> 
> People write that possible solution is to change theme "atom-material-ui" if you are using one... ( #14230 or https://discuss.atom.io/t/tree-view-does-not-scroll-in-1-17-0-beta0-and-1-17-0-beta1/41733/4 )
> 
> Will try this one.

I'm facing this bug also when don't use "atom-material-ui" theme

**Comment by igloro** [comment] 2019-08-22 07:34
> > Same problem here:
> > > Atom :1.40.1
> > > Electron: 3.1.10
> > > Chrome: 66.0.3359.181
> > > Node: v10.2.0
> > 
> > 
> > People write that possible solution is to change theme "atom-material-ui" if you are using one... ( #14230 or https://discuss.atom.io/t/tree-view-does-not-scroll-in-1-17-0-beta0-and-1-17-0-beta1/41733/4 )
> > Will try this one.
> 
> I'm facing this bug also when don't use "atom-material-ui" theme

Yep. didn't helped. So uninstalling atom-material-ui didn't helped.

**Comment by choma1** [comment] 2019-08-22 15:33
I had this issue and reverted to version v1.39.0-beta3 (2019-07-02) and the issue hasn't resurfaced so far. v1.39.0 (2019-07-23) modified tree-view so that may be related.

**Comment by muka** [comment] 2019-08-27 06:33
I am on xubuntu 19.04 atom 1.41 and can confirm the issue

Regards

**Comment by malnvenshorn** [comment] 2019-08-28 12:59
> Personally I'd recommend running the beta since I've seen these unofficial releases have other problems.

As long as I don't have issues I'll stick with the unofficial release because the Electron version is more up to date. I'm only switching between between my distribution package and the official release to bypass Electron bugs (quite annoying though).

@muka have you tried the 1.41 beta? I'm not seeing the issue with Electron4. 1.40.1 still uses Electron3. FWIW I'm also using multiple screens.

**Comment by muka** [comment] 2019-08-28 13:09
@malnvenshorn you are right, I have been trying on atom not atom-beta.. my fault. Beta works well

**Comment by lharper** [comment] 2019-09-10 15:58
I was having the exact same issue as well but I'm using Windows 10. It doesn't happen in the beta.

> 
> 
> > Does that mean it is an Electron bug?
> 
> It does seem Electron related since you don't see the issue when
> 
> > Is there a plan when Atom 1.41 will be released? Going back to 1.38.2 is not very appealing.
> 
> We don't have a specific release schedule but 1.41 is currently in beta, no need to run the nightly release.
> 
> > Update: Switched to the unofficial Atom package provided by my Linux distribution. Seems to work fine too.
> 
> Personally I'd recommend running the beta since I've seen these unofficial releases have other problems.
> 
> Can other folks that see this issue confirm that things work ok in the 1.41 beta? Also is everyone on Linux? I haven't been able to reproduce with a 19.04 Ubuntu VM.

I'm using Windows 10 and was having the issue as well. I've been using the beta and that fixes it for me. Thanks.

**Comment by GyozaGuy** [comment] 2019-09-10 16:05
I actually saw the issue yesterday on the beta as well (1.41.0-beta1 x64) on Ubuntu 19.04, but it took days to happen compared to just hours or minutes when using the release version.

**Comment by akecoinomyltd** [comment] 2019-09-18 13:46
Same issue on 1.40.1 x64. Maybe it happens then window focus changes (to browser e.g.)

**Comment by lexxcbrm** [comment] 2019-09-18 13:48
Same issue on 1.40.1 x64. Maybe it happens then window focus changes (to browser e.g.)

**Comment by lexxcbrm** [comment] 2019-09-24 07:37
Interesting fact. If I launch and minimize JetBrains WebStorm window then scrolling in Atom's project tree doesn't stop working. It's a trick )))

**Comment by sydro** [comment] 2019-10-04 11:23
In atom beta (v1.41.0-beta1) the issue isn't showing up.

**Closed** 2020-02-27 17:27 UTC
Labels: electron
