### ISSUE TITLE
HDPI on Gnome 3

### ISSUE THREAD

**Issue by jmml97** [atom/atom#8664] opened 2015-09-03 21:19 UTC
Hi! I've used Atom on Unity before on the MacBook's Retina Display and Atom has scaled properly. However now that I'm using Ubuntu Gnome with Gnome 3, Atom doesn't scale properly and elements are too small. What can be done?

**Comment by mnquintana** [comment] 2015-09-03 21:25
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/3636 – it should be fixed when https://github.com/atom/atom/pull/7877 is merged.

**Closed by mnquintana** 2015-09-03 21:25 UTC
Labels: duplicate
