### ISSUE TITLE
Atom built from source (v1.34) crashes when opening a folder with git repository 

### ISSUE THREAD

**Issue by bogdandobanda** [atom/atom#18926] opened 2019-02-28 15:48 UTC
*Edit by @rsese to add extra notes*

Reproduced on Ubuntu 16.04 but couldn't reproduce on 18.04. 

On 16.04, used node 8.9.3 and npm 6.2.0:

```
$ apm -v
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.12
```
Used the same node and npm versions on 18.04.

---

### Description

Atom crashes when opening a folder containing a git repository

### Steps to Reproduce

1. Build Atom from source (v1.34) "./script/build --create-debian-package"
2. Install your build
3. Start Atom
4. Open a folder containing git repository

**Expected behavior:** 

**Actual behavior:** 
Crashes

**Reproduces how often:**
Always 

### Versions
OS: Ubuntu 16.04 LTS

building with:
Node:	v8.9.3
Npm:	v5.5.1

checks during build:
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
python 2.7.12
git 2.7.4

after installing built package: 
_atom --version_
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

_apm --version_
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.12
git 2.7.4

### Additional Information
Seems related to nsfw package.
Noticed that my build produces different(bigger) nsfw.node file than the one from official release (118K vs 102K)
./resources/app.asar.unpacked/node_modules/@atom/nsfw/build/Release
Instructions from manual were followed.

Crash log:
[_usr_share_atom_atom.1000.zip](https://github.com/atom/atom/files/2915706/_usr_share_atom_atom.1000.zip)

**Comment by rsese** [comment] 2019-03-01 20:57
Thanks for the report!  Hmmm, yeah I was able to reproduce after building from `v.134.0`, `v.1.35.0-beta0`, and from a recent checkout (https://github.com/atom/atom/commit/aad8bd68).

But if I install the [1.34.0 .deb](https://github.com/atom/atom/releases/download/v1.34.0/atom-amd64.deb) release, it doesn't crash.

Also confirmed that it seems to crash when opening a git repository (I opened the atom/atom I just cloned and created a new repository with a single test file).

**Comment by jasonrudolph** [comment] 2019-03-12 17:56
I love the smell of `git bisect` in the morning. 🌇😀

Thanks to `git bisect`, I've identified b34cefa75bad9dfbbde00436fccf2f1a44f36ef4 as the commit that introduces this regression. That commit was introduced in https://github.com/atom/atom/pull/18012.

That change upgrades Atom from Electron 2.0.7 to 2.0.9, which means that this regression is the result of upgrading Atom to either Electron 2.0.8 or 2.0.9. When I build atom/atom from source using Electron 2.0.7, I don't see these crashes. However, when I build atom/atom from source using Electron 2.0.8, I _do_ see these crashes. This leads me to believe that **one of the [few changes in Electron 2.0.8](https://github.com/electron/electron/releases/tag/v2.0.8) triggers these crashes**.

My _guess_ is that https://github.com/electron/electron/pull/13988 is the change that triggers these crashes, but that's just a guess. That pull request was intended to fix https://github.com/electron/electron/issues/13972, and the Electron 2.0.8 release notes claim to fix that issue, but the issue is still open, and I see recent discussion of people still encountering the issue. I'll ping some folks on the Electron team to see if I can gather more insight on the status of that issue.

**Comment by bogdandobanda** [comment] 2019-03-13 14:01
It runs smoothly on Ubuntu 16.04 after downgrading to Electron 2.0.7
Thumbs up for the work!
Problem is now that issues fixed in [#18012](https://github.com/atom/atom/pull/18012) resurfaced... a critical one being Segmentation fault that still happens on Fedora 29 upon atom startup.

**Comment by jasonrudolph** [comment] 2019-03-14 20:22
> It runs smoothly on Ubuntu 16.04 after downgrading to Electron 2.0.7
> Thumbs up for the work!

Thanks, @bogdandobanda.

Because this crash is a result of upgrading from Electron 2.0.7 to 2.0.8, and because the latest Electron 2.x version still exhibits this crash, and because [active development of Electron is focused on the 5.x series](https://electronjs.org/blog/electron-5-0-timeline), I don't think we can expect an Electron 2.x fix for this issue. Instead, I think our best chance of overcoming this issue is to get Atom using a more modern version of Electron.

The good news is that we have a pull request open for getting Atom running on Electron 3 (https://github.com/atom/atom/pull/18916), and when I build that branch from source on Ubuntu 16.04, I can no longer reproduce this crash. 😅 The less good news is that we still have quite a bit of work to do before that pull request can be merged. (See the "issues to resolve" section of the [pull request body](https://github.com/atom/atom/pull/18916#issue-256469481).)

With that in mind, I think we can offer a few workarounds for now:

- Use a pre-built version of Atom (e.g., `atom-amd64.deb` for [Atom 1.35.1](https://github.com/atom/atom/releases/tag/v1.35.1)) instead of building from source, or ...
- Build [Atom's Electron 3 branch](https://github.com/atom/atom/pull/18916) from source, and if you encounter any of the known issues, try to help us resolve them :pray:

I understand that neither of these workarounds are ideal (sorry about that), but they're probably the best we can do with our limited resources in the near term. I hope that makes sense.

**Comment by darangi** [comment] 2021-02-02 19:07
This issue no longer exists, I will go ahead and close this

**Closed by darangi** 2021-02-02 19:07 UTC
Labels: crash, d ⬆️, i ⬆️, linux, triaged, v ⬇️
