### ISSUE TITLE
Find and replace not working for a lookahead pattern

### ISSUE THREAD

**Issue by jrajav** [atom/atom#13068] opened 2016-10-25 20:13 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? **Yes**
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? **Yes**
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? **Yes**
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? **Yes**
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? **Yes**
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? **Yes**

### Description

Regular expression find and replace does not work given a lookahead pattern.

### Steps to Reproduce

1. Open a buffer containing some text to search over. For instance, `const object = { 'key': 'value' }`
2. Open find-and-replace (Ctrl-F or Cmd-F) and turn Regex on.
3. Enter a search string containing a lookahead in the Find field (for instance, `'(?=.*:)`), and click Find. Notice that the matched strings are properly highlighted.
4. Click "Replace" or "Replace All".

**Expected behavior:** One or all of the strings are replaced with the given replacement string (or deleted if the replace field is blank).

**Actual behavior:** Nothing happens.

### Versions

1.11.2, Windows 10.0.14393 Build 14393

**Comment by 50Wliu** [comment] 2016-10-25 20:44
This is a duplicate of atom/find-and-replace#299 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-25 20:44 UTC
