### ISSUE TITLE
Atom crashes consistently.

### ISSUE THREAD

**Issue by GlennBurkins** [atom/atom#13561] opened 2017-01-07 00:09 UTC
I have installed atom without any apparent problems.
I open atom and attempt to perform some task (it does not seem tied to which task, any causes the problem) and the following dialog pops up:

![image](https://cloud.githubusercontent.com/assets/20824672/21737024/39987a68-d42a-11e6-9f29-c80f37b399db.png)

I am running Windows 10 Pro x64. It is up to date.
Any ideas?
Thank you.

**Comment by 50Wliu** [comment] 2017-01-07 01:05
Can you please fill out the issue template, available [here](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md)?  Copy it into your comment and then fill it out.

**Comment by t9md** [comment] 2017-01-08 17:31
Not sure it's same issue, I recently started to hit atom freeze issue maybe from when Atom-1.13.0-beta10(IFAIR when beta9 I haven't experience same issue).
When Atom freeze, sometime I can see console.log if lucky case, or simply have to force close Atom.
When I see console.log it said `maximum call stack size exceeded` but reporting source part is vary by timing.
After I quickly glanced call stack and found recursive loop happened at that time involved decorationManager and `bracket-matcher` package, I disabled bracket-matcher package then freezing stopped.
I don't have time to narrow down the root cause further at this point.

**Comment by bdubaut** [comment] 2017-01-20 08:41
I have the same problem on OSX Sierra, with Atom 1.13.0 x64. I can use atom for about 2 minutes and then it crashes, sometimes with a crash report to Apple, sometimes not. I removed everything and did a clean install. The problem persists.
```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

Could it be related to the Electron version? Or related to #13619 ?

**Comment by 50Wliu** [comment] 2017-01-20 18:14
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13561#issuecomment-271050039. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
---
To everyone else: please open new issues.

**Closed by 50Wliu** 2017-01-20 18:14 UTC
Labels: more-information-needed
