### ISSUE TITLE
Crash on trying to add a file

### ISSUE THREAD

**Issue by sergeyfilimonov** [atom/atom#20046] opened 2019-10-22 14:47 UTC
### Description

Often when I try to create a file in Atom it just crashes.

### Steps to Reproduce

1. Click the mouse right button.
2. Choose add a file.

**Reproduces how often:**

Every now and then.

### Versions

Atom 1.40.1
macOS 10.15

**Comment by rsese** [comment] 2019-10-22 16:24
Thanks for the report!  Please keep all the template sections when opening an issue, all the information is helpful for us when triaging.

For example, from the `Prerequisites` section, did you reproduce in safe mode and have you tried any of the other debugging suggestions?  

Also, can you share more specific steps to reproduce?  For example, where are you clicking in step 1?

Lastly, did you just start seeing this behavior just after updating to Catalina?

**Comment by rsese** [comment] 2019-10-22 16:24
Oh also, can you share any crash logs that you see?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

**Comment by sergeyfilimonov** [comment] 2019-10-22 18:16
@rsese 

> Please keep all the template sections when opening an issue, all the information is helpful for us when triaging.

Ok, sorry..

> For example, from the Prerequisites section, did you reproduce in safe mode and have you tried any of the other debugging suggestions?

Yes, but I have to use Atom in the safe mode for quite a long time to catch the bug as well as with the normal mode.

> Also, can you share more specific steps to reproduce? For example, where are you clicking in step 1?

I am clicking a folder. And actually not only `New file` causes the error but also `Collapse all folder` and `New folder`. 

> Lastly, did you just start seeing this behavior just after updating to Catalina?

Can't answer it for sure.

> Oh also, can you share any crash logs that you see?

Console.app shows no reports which can be related to Atom...

**Comment by NatachaH** [comment] 2019-10-23 09:01
I have the same problem, but it's also happen when I try to duplicate or delete a file (always with right click)

The bug doesn't happen every time, but it's happen more that once a day (this morning it's happen already 5 times...)

The is no alerte message when Atom crash. 

The bug started after I update my Mac to Catalina.
And I tried to re-install Atom but nothing changed.

Atom: 1.40.1
Mac: 10.15

I tried to look on the Console.app, but i don't know what to look at ...
the last entry in devices/macbook: Removing assertions for terminated process: [executable<Atom Helper(501)>:3730]
in system.log: com.apple.xpc.launchd[1] (com.github.atom.6288[3726]): Service exited due to SIGSEGV | sent by exc handler[3726]

**Comment by rsese** [comment] 2019-10-23 20:30
> Yes, but I have to use Atom in the safe mode for quite a long time to catch the bug as well as with the normal mode.

Interesting, so it does crash in safe mode eventually :+1:

Based on the writeup in https://github.com/atom/atom/issues/20034 and the fact that you're running Catalina, I'm going to tentatively close as a duplicate of that issue but we can reopen if your issue ends up being different.

**Closed by rsese** 2019-10-23 20:30 UTC
