### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by i32ropie** [atom/atom#5507] opened 2015-02-11 23:44 UTC
Error: write EPIPE
  at Object.exports._errnoException (util.js:753:11)
  at exports._exceptionWithHostPort (util.js:776:20)
  at WriteWrap.afterWrite (net.js:766:14)

Almost everytime I save a file, i have this error.

**Comment by izuzak** [comment] 2015-02-12 13:57
@i32ropie Can you share more [debugging information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)? Also, where are the files you are saving located (local drive, network drive, ...)?

**Comment by izuzak** [comment] 2015-02-12 14:00
Possibly related: https://github.com/atom/atom/issues/4708

**Comment by djpowers** [comment] 2015-02-27 17:15
I've also experienced the linked issue (and commented there with my experience). Currently using Atom 0.181.0 on OS X 10.9.5.

Working with files saved on a local drive. It seems that this is again triggered for me when writing within an ERB tag in an .html.erb file.

**Comment by ChrisKdon** [comment] 2015-02-28 15:12
Atom Version: 0.184.0
OSX Version: 10.9.5

For me I received the error because a linter plugin I had installed could not find the "clang-format" on my computer. Once I installed it correctly the error went away. So I would say this is not an issue with Atom.

**Comment by ChaoMai** [comment] 2015-03-05 07:43
Got same problem when saving.

Uncaught Error: write EPIPE
events.js:94

Error: write EPIPE
  at Object.exports._errnoException (util.js:753:11)
  at exports._exceptionWithHostPort (util.js:776:20)
  at WriteWrap.afterWrite (net.js:766:14)

**Comment by ChaoMai** [comment] 2015-03-05 09:26
I guess this is caused by [atom-clang-format](https://github.com/LiquidHelium/atom-clang-format/blob/master/lib/main.coffee).

@ChrisKdon 
In the file `atom-clang-format/lib/main.coffee` at line 6, you can find `executable` is `clang-format`. But you may have to use `clang-format + edition number` to call the clang-format in the terminal, like `clang-format-3.5`. So [atom-clang-format](https://github.com/LiquidHelium/atom-clang-format/blob/master/lib/main.coffee) cannot find the clang-format.

What's more. `formatOnSave` is set to `true` in the file `atom-clang-format/lib/main.coffee` at line 5. So  [atom-clang-format](https://github.com/LiquidHelium/atom-clang-format/blob/master/lib/main.coffee) will format file every time when you save it. But [atom-clang-format](https://github.com/LiquidHelium/atom-clang-format/blob/master/lib/main.coffee) won't success since `executable` is `clang-format`.

**Comment by ChaoMai** [comment] 2015-03-05 15:00
@ChrisKdon 
Finally I got it. In the settings for the clang-format you should be able to change the executable name.

**Comment by ahmetabdi** [comment] 2015-03-10 10:54
Got this today too

**Comment by izuzak** [comment] 2015-03-10 13:13
@ahmetabdi Which packages do you have installed and which version of Atom are you using? Can you provide the output of `apm list`?

**Comment by ahmetabdi** [comment] 2015-03-10 13:49
@izuzak https://gist.github.com/ahmetabdi/715920ca2b6aa94a6909

I'm on the latest 0.186.0

**Comment by kolis** [comment] 2015-03-20 11:55
same problem, same fix, disabling clang-format

**Comment by vlux** [comment] 2015-05-05 01:41
I remove the package "clang format" and it's alright.
You guys can try it.

**Comment by ondine** [comment] 2015-05-13 23:04
Error when using Markdown to PDF package:

Uncaught Error: write EPIPE
events.js:141
Hide Stack Trace
````
Error: write EPIPE
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at WriteWrap.afterWrite (net.js:753:14)
````

**Comment by izuzak** [comment] 2015-06-10 12:27
This should have been fixed by atom/notifications#62. Let us know if you can still reproduce this. /cc @kevinsawicki

**Closed by izuzak** 2015-06-10 12:27 UTC
Labels: more-information-needed

**Comment by djpowers** [comment] 2015-06-10 13:22
I can confirm that atom/notifications#62 resolved the issue for me. Thanks!

**Comment by djpowers** [comment] 2015-07-23 20:08
Sorry to renege on my previous comment, but I just ran into this issue again on Atom OS X 1.0.2.

[Enter steps to reproduce below:]

1.Edit conditional statement within ERB tag `<% %>`

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at WriteWrap.afterWrite (net.js:753:14)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getPosition] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
    at Atom.module.exports.Atom.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:530:29)
    at Atom.module.exports.Atom.storeDefaultWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:563:25)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:104:21
    at handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:115:32)
    at jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
```

### Commands

```
     -4:09.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:09.2.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -4:09.1.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:08.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:07.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:06.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:06.1.0 open-on-github:blame (atom-text-editor.editor.vim-mode.normal-mode)
  2x -1:33 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:09.3.0 pane:show-next-item (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:06.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:05.8.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.9.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.3.0 editor:select-to-end-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.2.0 core:select-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.7.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 17
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.11
linter, v1.2.4
linter-coffeelint, v1.0.0
linter-erb, v0.1.1
linter-jshint, v1.1.4
linter-ruby, v0.1.6
linter-scss-lint, v1.0.5
minimap, v4.12.0
symbol-gen, v1.0.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment] 2015-07-23 20:13
It looks to me like a process spawned by the linter (maybe `ruby` or `erb`) is crashing. Is there any warning output in your console?

**Comment by djpowers** [comment] 2015-07-23 20:41
@maxbrunsfeld, do you mean the linter Error Panel at the bottom? Or the web inspector console (invoked with cmd + option + I)?

If the former, there are a couple errors on the file, and some warnings along with errors in the project.

If the latter, I see "activate linter-erb", "activate linter-ruby", and "activate linter-scss-lint". Then I see multiple instances of this error ("Uncaught Error: write EPIPE").

**Comment by misterdai** [comment] 2015-08-17 08:53
I'm getting this issue with Atom 1.0.6 on Windows 7.  I was connecting to a local VM via a Windows share, when I powered down the VM and the share was no longer accesssible, Atom starting throwing these errors.  Probably to be expected as the files were no longer available, but would be nice if the error message could reflect this and be handled more gracefully.
