### ISSUE TITLE
Guess tabLength from file

### ISSUE THREAD

**Issue by montogeek** [atom/atom#10143] opened 2015-12-21 20:00 UTC
Hi!

It would be great if Atom can guest the tab length of the opened file to set the tabLength option.

Thanks!

**Comment by Ben3eeE** [comment] 2016-08-17 07:22
https://github.com/atom/atom/issues/3043?

**Comment by 50Wliu** [comment] 2016-08-17 13:29
Thanks - closing as a duplicate of #3043.  Feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-17 13:29 UTC
Labels: enhancement
