### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAllowedLocations' of undefined

### ISSUE THREAD

**Issue by codetony25** [atom/atom#15813] opened 2017-10-04 13:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getAllowedLocations' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/layout.js:159

TypeError: Cannot read property 'getAllowedLocations' of undefined
    at itemIsAllowedInPane (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/layout.js:159:41)
    at Object.end (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/layout.js:42:18)
    at HTMLLIElement.TabView.element.ondragend (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-view.js:62:29)
```

### Commands

```
     -0:22.7.0 tree-view:toggle (atom-pane.pane.active)
     -0:09.3.0 diagnostics:toggle-table (div.tool-panel.tree-view)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.0.1 
atom-clock 0.1.15 
atom-ide-ui 0.4.0 
atom-symfony2-ui 1.7.2 
autoclose-html 0.23.0 
base16-ocean-dark-spacegray 0.13.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.12 
flat-simple-dark-ui 0.1.1 
flat-ui-syntax 0.5.1 
fontawesome5-ui 0.9.4 
git-blame 1.3.1 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
ide-css 0.2.0 
ide-flowtype 0.17.4 
intellij-idea-keymap 0.2.3 
intentions 1.1.5 
isotope-ui 2.8.5 
language-babel 2.75.1 
linter 2.2.0 
local-history 4.3.0 
lodash-snippets 2.0.0 
operator-mono 0.11.0 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
pragmatic-syntax 1.1.0 
prettier-atom 0.40.0 
pristine-ui 1.1.10 
project-manager 3.3.5 
smart-backspace 0.2.3 
```

**Comment by rsese** [comment] 2017-10-04 19:27
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/tabs/issues/433. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-04 19:27 UTC
