### ISSUE TITLE
Failed to load the .git package

### ISSUE THREAD

**Issue by Sheridan-Tech** [atom/atom#9805] opened 2015-11-25 07:11 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the .git package

```
At Unexpected token ILLEGAL

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.defineProperty.value [as .js] (C:\Users\James\AppData\Local\atom\app-1.2.4\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\James\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:661:34)
    at C:\Users\James\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:115:28
    at Package.module.exports.Package.measure (C:\Users\James\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:92:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "welcome",
      "background-tips",
      "language-yaml",
      "language-sass",
      "language-mustache",
      "language-go",
      "jsonlint",
      "linter-pylama",
      "language-scilab",
      "language-arduino",
      "linter-csslint",
      "linter-pylint",
      "linter-shellcheck",
      "tree-view",
      "apm-publish",
      "linter",
      "linter-clang",
      "color-picker",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher",
      "bracket-matcher"
    ],
    "projectHome": "C:\\Users\\jsheridan\\Desktop\\repositories\\witpgn",
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "J-Sheridans_dark_syntax_theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 18,
    "showIndentGuide": true,
    "autoIndent": false,
    "autoIndentOnPaste": false,
    "showInvisibles": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
.git, vundefined
auto-indent, v0.5.0
feedback, v0.38.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
J-Sheridans_dark_syntax_theme, v0.1.0
keymaps, vundefined
lib, vundefined
menus, vundefined
minimap, v4.16.2
spec, vundefined
styles, vundefined
Sublime-Style-Column-Selection, v1.3.0
sync-settings, v0.6.0
whitespace, v0.32.1
wrap-guide, v0.38.1

# Dev
No dev packages
```

**Comment by thedaniel** [comment] 2015-11-25 13:46
This is fixed in apm 1.5.0 and on atom master by ignoring packages that start with a dot.

**Closed by thedaniel** 2015-11-25 13:46 UTC
Labels: uncaught-exception

**Comment by ProgramFan** [comment] 2016-04-03 03:32
The same error shows up again with Atom 1.6.2 on Max OSX El Captain.

```bash
$ apm -v
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.0
```

**Comment by thedaniel** [comment] 2016-04-03 09:01
@BinaryMuse @kuychaco is it possible that package installation from git caused the issue fixed in this PR to regress? -> https://github.com/atom/apm/pull/458

**Comment by BinaryMuse** [comment] 2016-04-04 00:10
@thedaniel One of the recent PRs took care of the `.bin` folder but not other `.*` folders. I will comment on that PR inline and we'll take care of it soon.

**Comment by BinaryMuse** [comment] 2016-04-04 00:13
@thedaniel Actually @kuychaco points out that the git installation via apm stuff isn't on 1.6, it's only on 1.7-beta and dev.

**Comment by kuychaco** [comment] 2016-04-04 00:22
yeah, the package installation changes were introduced in Atom v1.7.0-beta0 and apm v1.8.0 and this error came up on 1.6.2. 

Not sure what could be causing this error. fwiw I tried to repro this by adding a .git folder in my `~/.atom/packages` folder and didn't seem to have a problem loading Atom, though since there are no repro steps listed maybe I'm missing something. I tried this for 1.6.2 and 1.8.0-dev-307944c.

**Comment by ProgramFan** [comment] 2016-04-04 01:47
Reproduce Steps: On Mac OSX El Captain:
1. Install Atom 1.6.2
2. Clean $HOME/.atom
3. Start Atom and install activate-power-mode and atomic-chrome
4. Shutdown Atom
5. `cd $HOME/.atom/packages && git init && git add . && git commit -m "Init repo"`
6. Start Atom and the error shows up.
