### ISSUE TITLE
Crash Opening 1.5 MB HTML File

### ISSUE THREAD

**Issue by MatthewSteen** [atom/atom#8471] opened 2015-08-21 18:17 UTC
Created by [Bokeh](http://bokeh.pydata.org/) when opening in 1.0.7 on a Windows 7 x64 machine. Also occurred in Safe Mode. I was able to open a small ~25 KB webpage without issues.

![image](https://cloud.githubusercontent.com/assets/8397034/9416931/a75ae0ca-4805-11e5-9462-94680b44b512.png)

[FILE](https://onedrive.live.com/redir?resid=FB448AABCC04755!118&authkey=!AMPAyIRXOY4Nbns&ithint=file%2chtml)

**Comment by izuzak** [comment] 2015-08-21 18:54
Thanks for the report, @MatthewSteen, but it would be much more helpful if you provided [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues). 

Also, can you share the file in question? Can you reproduce the crash in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Did Atom actually crash or did you observe an exception?

**Comment by MatthewSteen** [comment] 2015-08-21 19:56
@izuzak see above for additional info.

**Comment by mnquintana** [comment] 2015-08-21 20:20
@MatthewSteen Thanks for the update! Looking at that file it seems like this is happening because of a very long line, which is the same issue as https://github.com/atom/atom/issues/979 - I'm gonna close this out in favor of that issue.

**Closed by mnquintana** 2015-08-21 20:20 UTC
Labels: more-information-needed

**Comment by MatthewSteen** [comment] 2015-08-21 20:22
sounds good @mnquintana, I did a search for my specific case but didn't see that one.
