### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat '/\INSIM.BIZ\IM\SNL-IIM-Users-B'

### ISSUE THREAD

**Issue by DerekGeng** [atom/atom#16545] opened 2018-01-12 14:04 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat '\\INSIM.BIZ\IM\SNL-IIM-Users-B'

```
At fs.js:902

Error: EPERM: operation not permitted, lstat '\\INSIM.BIZ\IM\SNL-IIM-Users-B'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1542:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at atom.project.getPaths.map (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:73)
    at Array.map (native)
    at Object.startTask (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:56)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/fuzzy-finder/lib/main.js:109:43)
    at get_process.nextTick (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/fuzzy-finder/lib/main.js:25:45)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.10.5 
file-icons 2.1.15 
minimap 4.29.7 
predawn-ui 1.0.7 
python-autopep8 0.1.3 
```

**Comment by rsese** [comment] 2018-01-12 18:45
Thanks for taking the time to contribute!

This looks like a duplicate of https://github.com/atom/fuzzy-finder/issues/289 - if you have any more details you can share (e.g. what were you doing at the time of the error, is the error reproducible, etc.), feel free to mention it in the issue.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-01-12 18:45 UTC
