### ISSUE TITLE
request for ppa on ubuntu

### ISSUE THREAD

**Issue by horvan** [atom/atom#5162] opened 2015-01-20 19:14 UTC
Building atom from scratch takes very long on ubuntu 
even your .deb package is currently not working.
A launchpad ppa in addition to the fit hub source may love this for ubuntu as well as for debian

**Comment by thedaniel** [comment] 2015-01-20 19:15
This is a dupe of #2956 and depends on #3717 which depends on a fully offline build. We want to have it for 1.0 though!

**Closed by thedaniel** 2015-01-20 19:15 UTC
