### ISSUE TITLE
Atom handles macOS aliases incorrectly

### ISSUE THREAD

**Issue by modest** [atom/atom#18629] opened 2018-12-29 00:15 UTC
### Description

macOS supports 3 types of links to files or directories:

- symlinks
- hard links
- aliases

Aliases are the default type of link created by macOS.  In the Finder, users create them by selecting File -> Make Alias.

Aliases are important because:
- Aliases are the default type of link.
- Aliases are supported **literally everywhere else in the system** including by all POSIX utilities.
- Aliases are superior to symlinks in every way. They contain multiple reference types are resilient to path changes such as file renames.

Atom does not handle alias files correctly.  Instead of following the link (or displaying an error), Atom shows the binary contents of the file.

### Steps to Reproduce

1. Create a folder containing at least 1 alias.
2. In Atom, open a new window (File->New Window)
3. Add the folder as a project folder (File->Add Project Folder…)
4. In the tree view, select the alias.

**Expected behavior:**
The alias's target file or folder is opened.

**Actual behavior:**
Atom displays the binary contents of the alias data.  This is unacceptable for any app on macOS.

**Reproduces how often:**
100%

### Versions

Atom    : 1.33.1
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment] 2019-01-02 18:41
Thanks for the report - this looks like a duplicate of https://github.com/atom/tree-view/issues/529 so you can subscribe there for updates if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-01-02 18:41 UTC
