### ISSUE TITLE
Win10 - No shortcut & start menu

### ISSUE THREAD

**Issue by daniel-hyuuga** [atom/atom#15427] opened 2017-08-24 01:16 UTC
Just installed Atom on my Windows 10 x64, the installer goes fine but there is no entry on Start Menu or Desktop Shortcut created. Downloaded & using Atom 1.19.3.

**Comment by ichthub** [comment] 2017-08-24 10:45
The same issue with me.

**Comment by 50Wliu** [comment] 2017-08-24 14:00
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12124. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-24 14:00 UTC
