### ISSUE TITLE
Editor freezes when saving a file for the first time on launch

### ISSUE THREAD

**Issue by DrMajkrosoft** [atom/atom#13373] opened 2016-12-02 12:52 UTC
When I open up Atom, and then when I make changes to a file, the first time I save the changes using `Ctrl + S`, the editor freezes for approx. 8 seconds. If I make another change and then save it again, it doesn't freeze. This happened on version 1.11 too and it still present today. I firstly thought that it  was a problem with my system, but even with the fresh installment of the OS, the issue is still present. It happened on "Windows 10" and it is present on "Windows 7" also. So here is the reproduction of the issue.

Atom version: **1.12.6**
- Open up Atom.
- Make changes to a file for the first time, press `Ctrl + S`, editor freezes for approx. 8 seconds.
- Make another change to the exact same file, press `Ctrl + S` again, editor doesn't freeze.

Now, it might also be a problem with one of the packages, but I'm not sure though. Here is the list of packages that I use.

- Atom Beautify ( https://atom.io/packages/atom-beautify )
- Monokai Theme ( https://atom.io/themes/monokai )
- File Icons ( https://atom.io/packages/file-icons )

**Comment by Ben3eeE** [comment] 2016-12-02 12:58
Can you try to start Atom using `atom --safe` and see if you still experience this behavior?

**Comment by DrMajkrosoft** [comment] 2016-12-02 20:36
Tried it, now it's about 4 secs. It's not that big of a problem, it's just weird. I don't really mind if this doesn't get fixed, I mean, it's 8 seconds.  Maybe other people do not have this issue.

**Comment by arcticicestudio** [comment] 2016-12-03 08:22
This behavior can be easily reproduced.
It is caused by the type of your disk the `.atom` dir is stored on.
If it is stored on a normal **HDD** it'll freeze from some seconds only on the first save action. I don't know exactly what Atom is doing or if it is related to Electron/NodeJS, but it heavily starts to read operations on the disk.
If you move your `.atom` dir onto a **SSD** there will be almost no freeze.

**Comment by lee-dohm** [comment] 2016-12-23 21:01
@ungb Do we have any old systems with HDDs lying around that this can be tested on?

**Comment by 50Wliu** [comment] 2016-12-31 01:57
I can attempt to reproduce this tomorrow on my old laptop.

**Comment by ungb** [comment] 2017-01-05 20:46
@lee-dohm I can take a look at home, I have a laptop that doesn't have ssd.

**Comment by lee-dohm** [comment] 2017-01-28 22:51
@50Wliu @ungb Were either of you able to reproduce this?

**Comment by 50Wliu** [comment] 2017-01-29 00:03
No...I forgot the password :/.  Sorry.

**Comment by ungb** [comment] 2017-01-31 00:02
I wasn't able to get a repro,  I have a hd without ssd but I haven't setup windows on it.  I'll try to get to it this week.

**Comment by ungb** [comment] 2017-02-03 21:59
I installed windows on my 5400 rpm hd and things were running slow (everything not just Atom).   Saving for me was instant though.  I was testing on 1.13.1.  

We've made some improvements to large files and saving.  @arcticicestudio, any chance you can try with latest version?

**Comment by arcticicestudio** [comment] 2017-02-11 07:56
Sorry for the delay, had to setup my old computer to test it it.
It is reproducible with version `1.13.1` and `1.14.1`.
Would a profile record /heap dump help to analyze this problem?

**Comment by lee-dohm** [comment] 2017-02-11 20:20
> Would a profile record or heap dump help to analyze this problem?

Yes, a CPU profile would be necessary at this point to make any forward progress here.

**Comment by arcticicestudio** [comment] 2017-02-13 20:24
This is a CPU profile record after saving a 124 line-long `README.md` file for the first time while running  Atom for the first time in a OS session. The UI was frozen for ~6 seconds

📦  [CPU-20170213T211326.zip](https://github.com/atom/atom/files/772312/CPU-20170213T211326.zip)

**Comment by lee-dohm** [comment] 2017-02-13 20:33
It looks like three seconds are taken up by two child processes: one run by the [pigments package](https://atom.io/packages/pigments) and the other by the built-in Git support checking the status of the files and folders in the repo. Nearly two seconds of that is consumed by pigments. Are you working in a particularly large repo @arcticicestudio? How many files are tracked?

**Comment by arcticicestudio** [comment] 2017-02-15 20:12
The `README.md` file is located in a small repository with only 12 files at all where 8 of them are `.png` files. Currently none are tracked since it is a new project.
I can create a seond CPU profile in `--safe` mode to compare it to the first profile this weekend, but I can't remember that I had the pigments package installed when this problem occurred the first time.

**Comment by arcticicestudio** [comment] 2017-02-23 15:03
There's only a really small delay in `--safe` mode, so it seems like the pigments package is the source of trouble :anguished:
I've installed the pigments package on my main system (SSD) and it works fine without any freeze, so I think the package only performs badly on a HDD based system.
[CPU-20170223T155608.zip](https://github.com/atom/atom/files/796793/CPU-20170223T155608.zip)

**Comment by lee-dohm** [comment] 2017-02-23 18:14
Thanks for the follow up @arcticicestudio :+1: Since it looks like this doesn't reproduce in Safe Mode, I'm going to close it. You may want to report this on the [pigments package repo](https://github.com/abe33/atom-pigments) to see if it is something that can be corrected.

**Closed by lee-dohm** 2017-02-23 18:14 UTC
Labels: more-information-needed, needs-reproduction

**Comment by VladimirDev93** [comment] 2017-06-08 18:29
Hey, I know that this issue is closed and it should stay closed. Turns out that, save that takes 8 secs on first save was indeed related to the package **Atom Beautify**, here's the conformation: 

https://github.com/Glavin001/atom-beautify/issues/876

Thank you all for your effort, the issue is now resolved. Tested myself, and indeed those 8 secs are gone, now it saves instantly. Once again, thank you all for your effort! 🥂  😄

**Comment by lee-dohm** [comment] 2017-06-08 19:05
Thanks for the followup, @VladimirDev93 :bow: I'm glad to hear that things are working for you again :+1:
