### ISSUE TITLE
automatic indentation for C++ file

### ISSUE THREAD

**Issue by llodds** [atom/atom#19899] opened 2019-09-11 22:07 UTC
For a C++ function with its input arguments written in two separate lines, now Atom automatically indents it as the following:

```c++
int function(int a,
  int b){
    return 0;
  }
```

Is it possible to make Atom indent the code in the following way?

```c++
int function(int a,
             int b){
  return 0;
}
```

**Comment by llodds** [comment] 2019-09-11 22:09
Also, is it possible to ensure the "#pragma"s are aligned at column 0? For example, below is what Atom is doing right now:
```c++
  int ix, iy;
  #pragma omp parallel for collapse(2) schedule(static,1) private(ix, iy)
  for(iy = 0; iy < ny; ++iy)
```

Is it possible to make Atom indent the pragmas like
```c++
  int ix, iy;
#pragma omp parallel for collapse(2) schedule(static,1) private(ix, iy)
  for(iy = 0; iy < ny; ++iy)
```

**Comment by rsese** [comment] 2019-09-11 23:40
Thanks for contributing!

We noticed the first issue mentioned looks like a duplicate of https://github.com/atom/language-c/issues/136 so you can subscribe there for updates if you'd like.

About the second issue, please open a new issue in https://github.com/atom/language-c with the issue template completely filled out so we can take a look.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-09-11 23:40 UTC
