### ISSUE TITLE
Auto-Completion Can't Handle Umlauts

### ISSUE THREAD

**Issue by the-max0r** [atom/atom#7413] opened 2015-06-25 13:42 UTC
The auto-completion popup fails on words containing umlauts (äöü). The umlaut and all characters after that are missing. I'm using Atom `0.211.0` from the .deb file and Ubuntu 14.04.

![opt](https://cloud.githubusercontent.com/assets/8014859/8355663/b95183ce-1b50-11e5-99f4-f2b4feb4a28b.gif)

**Comment by mnquintana** [comment] 2015-06-25 15:45
Would you mind moving this to https://github.com/atom/autocomplete-plus?

**Comment by kubetz** [comment] 2015-06-25 16:00
FYI autocomplete-plus has this issues already reported: https://github.com/atom/autocomplete-plus/issues/76 . So I think opening another issue there is not necessary.

**Comment by mnquintana** [comment] 2015-06-25 16:01
Ah good catch @kubetz, thanks!

@the-max0r This is a duplicate of https://github.com/atom/autocomplete-plus/issues/76 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-25 16:01 UTC
Labels: wrong-repo

**Comment by the-max0r** [comment] 2015-06-25 17:40
Thanks, I didn't know that. I'll subscribe to https://github.com/atom/autocomplete-plus/issues/76
