### ISSUE TITLE
Indent-guide not aligned for some fonts

### ISSUE THREAD

**Issue by vdclouis** [atom/atom#11016] opened 2016-03-01 16:21 UTC
### Description

For some fonts, the `indent-guide` is not aligned properly.

### Steps to Reproduce

1. Change font to, say Operator Mono
2. check code snippet

See:
![](https://cldup.com/u07R3KFIbh.png)

**Expected behavior:** correct alignment
**Actual behavior:** not aligned correctly

### Versions

Atom 1.5.3

**Comment by 50Wliu** [comment] 2016-03-01 16:39
This is a duplicate of #9369 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-01 16:39 UTC
