### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by Eldair** [atom/atom#13751] opened 2017-02-06 14:39 UTC
[Enter steps to reproduce:]

1. Undo changes (not every time when doing `undo` but only when doing `undo`)

**Atom**: 1.14.0-beta4 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At C:\Users\krist\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:189

TypeError: Cannot read property 'destroy' of undefined
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.destroyMarker (/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:189:34)
    at /app.asar/node_modules/text-buffer/lib/marker-layer.js:366:37
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.destroyMarker (/app.asar/node_modules/text-buffer/lib/marker-layer.js:365:34)
    at Marker.module.exports.Marker.destroy (/app.asar/node_modules/text-buffer/lib/marker.js:269:18)
    at MarkerLayer.module.exports.MarkerLayer.restoreFromSnapshot (/app.asar/node_modules/text-buffer/lib/marker-layer.js:285:18)
    at TextBuffer.module.exports.TextBuffer.restoreFromMarkerSnapshot (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1323:79)
    at TextBuffer.module.exports.TextBuffer.undo (/app.asar/node_modules/text-buffer/lib/text-buffer.js:784:14)
    at /app.asar/src/text-editor.js:1532:31
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2525:18)
    at TextEditor.module.exports.TextEditor.avoidMergingSelections (/app.asar/src/text-editor.js:2507:35)
    at TextEditor.module.exports.TextEditor.undo (/app.asar/src/text-editor.js:1530:12)
    at /app.asar/src/register-default-commands.js:307:21)
    at /app.asar/src/register-default-commands.js:647:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -9:06.3.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -9:06.3.0 docblockr:parse-enter (input.hidden-input)
     -9:06.3.0 editor:newline (input.hidden-input)
     -9:06.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -9:06.2.0 docblockr:parse-enter (input.hidden-input)
     -9:06.2.0 editor:newline (input.hidden-input)
     -9:02.6.0 core:backspace (input.hidden-input)
     -9:00.6.0 core:move-right (input.hidden-input)
     -8:59.7.0 core:save (input.hidden-input)
     -2:34 core:paste (input.hidden-input)
     -0:13.2.0 core:undo (input.hidden-input)
     -0:12.2.0 core:save (input.hidden-input)
 20x -0:10.4.0 core:undo (input.hidden-input)
     -0:08.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
aesthetic-ui 2.0.0 
an-old-hope-syntax 1.0.1 
atom-autocomplete-php 0.21.0 
atom-beautify 0.29.17 
atom-dark-fusion-syntax 2.0.3 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-minify 0.8.0 
atom-wrap-in-tag 0.6.0 
auto-indent 0.5.0 
change-case 0.6.3 
color-picker 2.2.5 
docblockr 0.9.1 
emmet 2.4.3 
file-icons 2.0.14 
firewatch-syntax 1.1.1 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
highlight-selected 0.12.0 
hyperclick 0.0.40 
icon-fonts 2.12.0 
isotope-ui 2.7.1 
jquery-snippets 11.0.0 
js-hyperclick 1.10.1 
language-babel 2.54.0 
language-blade 0.27.1 
language-vue 0.21.2 
laravel 0.7.1 
laravel-forms-bootstrap-snippets 1.2.0 
linter 1.11.21 
linter-csslint 1.3.3 
linter-eslint 8.1.0 
linter-jshint 3.0.2 
linter-php 1.3.1 
linter-phpcs 1.5.8 
linter-phpmd 1.5.2 
linter-stylelint 3.7.0 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
nova-atom-syntax 1.4.0 
nova-atom-ui 1.3.0 
open-recent 5.0.0 
php-fmt 0.1.2 
prettier-atom 0.15.0 
prettier-eslint 1.2.5 
sass-autocompile 0.13.2 
sync-settings 0.8.1 
text-manipulation 0.6.0 
todo-show 1.9.0 
vue-hyperclick 0.2.0 
webbox-color 0.5.9 
```

**Comment by 50Wliu** [comment] 2017-02-06 16:15
@Eldair Can you try reproducing this in safe mode (`atom --safe`)?  Thanks!

**Comment by Eldair** [comment] 2017-02-08 16:32
Hi, I tried but in vain. I couldn't determine exact circumstances when it happens.
It is probably related to php linter/package since I think it never happened in any other file type.

**Comment by 50Wliu** [comment] 2017-02-08 17:58
Ok, thanks.  Since it seems like this is an issue with a community package I'm going to close this issue.  However, if you ever manage to reproduce it in safe mode, I'll be happy to reopen this!

**Closed by 50Wliu** 2017-02-08 17:58 UTC
Labels: more-information-needed, needs-reproduction, uncaught-exception

**Comment by joseluisq** [comment] 2017-02-16 09:50
The same error occurs when I press <kbd>ctrl + z</kbd> or <kbd>ctrl + y</kbd>

```
$ atom -v
Atom    : 1.14.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

```
