### ISSUE TITLE
Atom freezes when any external link is clicked

### ISSUE THREAD

**Issue by cyrozap** [atom/atom#8203] opened 2015-08-03 20:56 UTC
Any time I accidentally click on a link to a website, the whole editor freezes and the link won't open in my browser (Chromium). I can avoid the issue by not clicking any links, but sometimes I'll accidentally click a package name or something and I'll have to kill the `atom` process. I assume this is happening because Atom is trying and failing to open the link externally, but I don't know how that works so I don't know if I need to set a default browser or if I'm missing a helper program or something else. This issue is strange since it hasn't been working for some time now, but there was a time when it did work but links were opened in Atom's own browser.

Atom version: 1.0.3, installed via the `atom-editor` package from the AUR
OS: Arch Linux
Window Manager: i3
Browser: Chromium normally, Firefox also installed

**Comment by mnquintana** [comment] 2015-08-03 21:13
I think this is a duplicate of https://github.com/atom/atom/issues/6335, which should be fixed by https://github.com/atom/atom/issues/7877

**Closed by mnquintana** 2015-08-03 21:13 UTC
