### ISSUE TITLE
Atom won't open without internet connection (Multiple versions)

### ISSUE THREAD

**Issue by Validbit** [atom/atom#18577] opened 2018-12-13 15:25 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I've been using Atom more than a year and multiple time I ran onto an issue where it did't start at random (probably no previous update/package installation has happened). Only recently I found out it's probably because of the internet connection, that Atom seems to require (even when Automatic updates are disabled.). I've carefuly took the steps listed in *Prerequisities* but no-one seems to have this issue there. You can find more information about my PC below. If it is normal, is there a way to launch it offline? Thank you in advance :)

### Steps to Reproduce

1. Turn off Wi-Fi/Disconnect from internet (you can have Wi-Fi enabled)
2. Open Atom (--safe doesn't seem to help here)

**Expected behavior:** Launch Atom

**Actual behavior:** Nothing (loading cursor blinks once instead of thrice)

**Reproduces how often:** Every time

### Versions

I've tried to launch atom executables from
./app-1.32.2/atom.exe
./app-1.33.0/atom.exe
./atom.exe
./Update.exe
### Additional Information

Tried on Lenovo Yoga 720, Windows 10 Home (v1809) (2 weeks from clean installation), 8G RAM
Might have happen on my older computer as well.
It was once posted as an issue by someone else, but wasn't answered since he did not provide any details.

**Comment by rsese** [comment] 2018-12-13 21:31
Thanks for the report - I've seen this mentioned by a handful of folks and I think the issue you're referring to is https://github.com/atom/atom/issues/16373?

From https://github.com/atom/atom/issues/16373#issuecomment-443537309, it seems like enabling the loopback adapter helped?  There was another report on the message board where someone confirmed that fixed things for them too.

Does that help on your computer?

**Comment by Validbit** [comment] 2018-12-13 22:33
Yes, thank you. Without any configuration, installing "legacy" **Microsoft KM-TEST Loopback Adapter** driver works really well so far (even after restart) It seems that it's a Electron problem though ([Direct link to solution comment](https://github.com/electron/electron/issues/6437#issuecomment-265828944)) Thank you for your quick reply :)

**Comment by rsese** [comment] 2018-12-17 21:57
Glad that helped, we'll go ahead and close this out as a duplicate of https://github.com/atom/atom/issues/16373.

**Closed by rsese** 2018-12-17 21:57 UTC
Labels: duplicate
