### ISSUE TITLE
Atom Pasting 100K characters long word takes about 2 minutes to make Atom responsive and app is slow

### ISSUE THREAD

**Issue by tomkowz** [atom/atom#11500] opened 2016-04-16 19:51 UTC
### Description

Pasting long text like 100K characters long word makes Atom inresponsive for about two minutes.

### Steps to Reproduce

1. Create new document
2. Paste 100K long word (attached)

**Expected behavior:** Word should be pasted faster

**Actual behavior:** It takes 2 minutes to make app responsive. Sometimes I see popup whether I want to wait or just close the app. Also everything is laggy then, switching between tabs for example.

### Versions
OS X 10.11.4
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

[long-word.txt](https://github.com/atom/atom/files/222375/long-word.txt)

**Comment by dhulwells** [comment] 2016-04-19 10:24
Is this real?

**Comment by tomkowz** [comment] 2016-04-19 11:01
It happens sometimes. Not sure what causes it but I saw this "Do you want to wait" message like 20 times.

**Comment by wiggzz** [comment] 2016-04-19 11:45
This seems to be fixed by my pull request, https://github.com/atom/atom/pull/10881.

**Comment by tomkowz** [comment] 2016-06-25 20:39
Still happening with 1.8.0 version. It happens especially if I tapped below the text in empty place where arrow points to.

![screen shot 2016-06-25 at 22 37 49](https://cloud.githubusercontent.com/assets/2303177/16359005/8c26c634-3b25-11e6-9940-d61d8b3cd5a6.png)

Attached the file.

OS X El Capitan, 10.11.5, MBPr 13 Late 2013, i5 2.6, 8GB RAM.

[example.json.zip](https://github.com/atom/atom/files/333271/example.json.zip)

Hope it helps. I try to combine ten such files like this one.

**Comment by lee-dohm** [comment] 2016-06-29 20:50
This is a duplicate of https://github.com/atom/atom/issues/979. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-06-29 20:50 UTC
