### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#19204] opened 2019-04-24 00:55 UTC
## Summary

`atom --safe` console is still an error

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered. Be sure to explain why Atom's existing customizability isn't suitable for this feature.

## Additional context

![图片](https://user-images.githubusercontent.com/8848263/56625181-b2942600-666e-11e9-85df-4f8e7f11c8d6.png)

**Comment by rsese** [comment] 2019-04-24 03:59
Duplicate of https://github.com/atom/atom/issues/19097

**Closed by rsese** 2019-04-24 03:59 UTC
