### ISSUE TITLE
SMB error 

### ISSUE THREAD

**Issue by cam1170** [atom/atom#19036] opened 2019-03-22 19:35 UTC
Note that the automatic create issue with this information didn't work properly for some reason. I tried to open a file in an smb share and while it was not responding I shut my laptop. I think.
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EINVAL: invalid argument, lstat '/run/user/1000/gvfs/smb-share:server=myhome.itap.purdue.edu,share=myhome'

```
At fs.js:1661

Error: EINVAL: invalid argument, lstat '/run/user/1000/gvfs/smb-share:server=myhome.itap.purdue.edu,share=myhome'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at atom.project.getPaths.map.e (/usr/share/atom/resources/app/static/<embedded>:11:806765)
    at Array.map (<anonymous>)
    at Object.startTask (/usr/share/atom/resources/app/static/<embedded>:11:806756)
    at Object.startLoadPathsTask (/usr/share/atom/resources/app/static/<embedded>:11:187012)
    at get_process.nextTick (/usr/share/atom/resources/app/static/<embedded>:11:185074)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2019-04-24 04:35
Thanks for contributing and sorry for the delay!

Not 100% sure but I think this may be a duplicate of https://github.com/atom/fuzzy-finder/issues/274 so you can subscribe there for updates if you'd like.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-24 04:35 UTC
