### ISSUE TITLE
Atom should use standard directories correctly on Linux and Windows

### ISSUE THREAD

**Issue by sergey-shambir** [atom/atom#8281] opened 2015-08-08 08:49 UTC
(updated 14 aug 2015)
## On Linux

XDG Base Directory Specification defines standard paths inside $HOME folders that should be used by applications. Unfortunately, Atom creates directory "~/.atom" and puts part of data into it. Another part correctly placed at "~/.config/atom". Directory "~/.cache/atom" created, but seems to stay unused.
- Atom should not either create "~/.atom" or use it
- Atom should use "~/.config/atom" for all configuration files
- Atom should use "~/.local/share/atom" for all intermediate data and downloaded packages
- Atom should use "~/.cache/atom" for all cache and intermediate data that can be deleted without breaking user's work
- Lowercase version of application name used in paths - "atom" instead of "Atom"
## On Windows

Atom creates .atom directory in user's home folder - it's absolutely wrong behaviour since most Windows apps don't and shouldn't create anything in user folder.
- Atom should not either create "C:\Users\%USERNAME%.atom" or use it
- Atom should use "C:\Users\%USERNAME%\AppData\Roaming\Atom" for all configuration files; Roaming used to allow standard way of synchronization between user's devices
- Atom should use "C:\Users\%USERNAME%\AppData\Local\Atom" for all intermediate data and downloaded packages
- Atom should use "C:\Users\%USERNAME%\AppData\Local\Atom\cache" for all cache and intermediate data that can be deleted without breaking user's work
  Note that Windows can be installed on drive "D:\", so "C:\Users" used as example.
## More information on standard paths

For more information see tables for Windows and Linux at http://doc.qt.io/qt-5/qstandardpaths.html
You can search at this page by words:
- DataLocation
- CacheLocation
- ConfigLocation

**Comment by andya9** [comment] 2015-08-08 15:00
This is a duplicate of #7701, but much more informed, and extended to windows.

(On linux I’d suggest using lowercase.)

**Comment by 50Wliu** [comment] 2015-08-08 22:44
See also #2199 (Linux) and #6346 (Windows).

**Comment by envygeeks** [comment] 2015-08-09 14:03
Please no uppercase names on Linux, even Google adheres to that want.  `~/.config/atom`  maybe I'm the only one who gets annoyed (especially at GNOME who uses /etc/NetworkManager) but yeah :cry:

**Comment by mkwmms** [comment] 2015-08-09 23:19
:+1: 

But just to be clear, per the [XDG base directory spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), it should not be ~/.config/atom but $XDG_CONFIG_HOME/atom and not ~/.cache/atom but $XDG_CACHE_HOME/atom etc. allowing the user to specify those directories themselves (the whole point of the XDG system). ~/.config, ~/.local/share and ~/.cache are simply the defaults... so atom should only use ~/.config as a default if $XDG_CONFIG_HOME is not set. Also atom should respect those paths on OS X too instead of creating ~/.atom...

**Comment by JamenMarz** [comment] 2015-08-13 00:42
I agree, but like the others have said:  use lowercase on Linux `~/.config/atom`.  That's pretty much what all the others folders in there follow.  I'm not sure about Windows, but I imagine it's the same scenario.  So in general, I think the folder should be lowercase.

**Comment by kovbal** [comment] 2015-08-13 17:28
On Windows Atom should use `C:\Users\%USERNAME%\AppData\Roaming` instead of  `C:\Users\%USERNAME%\AppData\Local` for configuration files, since the [those should be synced][1] across workstations in case of a [roaming user profile][2].

 [1]: http://windows.microsoft.com/en-us/windows-8/what-appdata-folder
 [2]: https://en.wikipedia.org/wiki/Roaming_user_profile

**Comment by pedromaltez** [comment] 2015-10-06 21:37
I had already prepared the issue report below for [atom/apm] when I thought to look in [atom/atom] for issues mentioning `XDG_CONFIG_HOME`.

It looks like a solution not adhering to the XDG specs was preferred in #5385, even though this problem had been mentioned quite a while before in #2199 and #2261. There seemed to be some reluctance to change it to the XDG form in those issues because of widespread adoption and not wanting to break users' configurations. Atom has now reached 'stability' at 1.0.0 so I can only imagine that that would exacerbate the issue but I'm hopeful this will get resolved.

I think this issue should concern itself with the locations of the files on all the supported platforms (linux/freebsd/os x/windows from what I can tell). I assume FreeBSD would follow the same standard as linux and just use XDG specs, although perhaps there's some specific standard for FreeBSD. There is a proper place that Apple defines as the place where applications should place their configuration files, and perhaps that should be the default on os x if neither `$ATOM_HOME` nor `$XDG_CONFIG_HOME` is specified. I don't know what the solution should be but we ought to keep on mind that Atom is an application that's used by hackery types/people that use the command line and they will probably expect to find the config files for this type of application somewhere in their `$HOME` directory or if they have set it, in the `$XDG_CONFIG_HOME`. My personal preference is certainly to follow the XDG spec if the variables are set.

I know I'm referring to [atom/apm], but it's still relevant, as that would have to change if [atom/atom] changes. I'm specifically concerned with linux and os x systems below, as those are the systems I use and understand.

===============================================================================

Respect XDG Base Directory Specification
---------------------------------------------------------

It would be nice if atom followed the [XDG Base Directory Specification][XDG]. This, among other things, allows a user to specify a directory in which they want all applications to look for their user configurable setting files. Instead of having to set it individually for each application (like setting `$ATOM_HOME`) where it's even possible to do so (since plenty of applications have the locations hard coded), or having the config files live directly under `$HOME`, you can set the `$XDG_CONFIG_HOME` environment variable and let all applications look for their files in there, preferably in their own directory. A change like this shouldn't impact any user that doesn't have `$XDG_CONFIG_HOME` currently set, and it would, I assume, be a welcome change to any that does.

This is a small example of what not following the XDG Base Directory Specification and using your own application specific variables instead can end up causing, for some people:

```
# Vim
export VIMRC=$XDG_CONFIG_HOME/vim/vimrc
export VIM_CONFIG_DIR=$XDG_CONFIG_HOME/vim/config.d
export VIMINIT="source $VIMRC"
export VIM_CACHE=$XDG_CACHE_HOME/vim/vim

# Ruby tools
export IRBRC=$XDG_CONFIG_HOME/irb/irbrc
export PRYRC=$XDG_CONFIG_HOME/pry/pryrc

# Ruby versions below 2.1.0 are not aware of the GEM_SPEC_CACHE variable and
# will always place their gem cache in $HOME/.gem instead
export GEM_SPEC_CACHE=$XDG_CACHE_HOME/ruby/gem/spec

# Bundle config locations
export BUNDLE_CONFIG=$XDG_CONFIG_HOME/bundler/config
```

I've looked around and think that [src/apm.coffee][source] is the only file in the source (excluding tests) where anything would have to change.

I'm not particularly well versed in CoffeeScript and certainly don't really know its idioms, but this is fairly simple so I think instead of

```
getAtomDirectory: ->
  process.env.ATOM_HOME ? path.join(@getHomeDirectory(), '.atom')
```

it could be something along the lines of (this particular implementation feels kind of gross though... and I'm not even sure it works. Perhaps it's best to use `if ... else` instead of `?` here?)

```
getAtomDirectory: ->
  process.env.ATOM_HOME ?
  ( process.env.XDG_CONFIG_HOME ? path.join(process.env.XDG_CONFIG_HOME, 'atom') path.join(@getHomeDirectory(), '.atom') )
```

or whatever this is in idiomatic CoffeeScript

```
getAtomDirectory: function() {
  if process.env.ATOM_HOME {
    return process.env.ATOM_HOME
  } else if process.env.XDG_CONFIG_HOME {
    return path.join(process.env.XDG_CONFIG_HOME, 'atom')
  } else {
    return path.join(@getHomeDirectory(), '.atom')
  }
}
```

such that the order in which atom and friends would look for the config files is:  `$ATOM_HOME` -> `$XDG_CONFIG_HOME/atom` -> `.config/atom` (didn't implement this in the examples above though) -> `$HOME/.atom` This would cause the least amount of disruption, yet still kind of follows the XDG standard by falling back to a default of `.config/atom`. In an ideal world the original location and environment variable would be dropped, but keeping those would prevent people's configs from breaking. Only those that have already set `$XDG_CONFIG_HOME` are affected, as well as those that place their config file in the XDG default location. Similar things could be done for the cache/runtime directories. I'm just primarily concerned with the configuration files here for simplicity.

I understand this would likely also require changes in some tests and it would probably be a good idea to ensure consistency across [atom/apm] and [atom/atom], as well as any other projects that make use of `$ATOM_HOME`.

I also understand that this can only really be seen as pretty low priority and I don't know if this is something that the maintainers would like to include or not. Still, from my perspective it would be nice to have. I'll look into it some more if I get a go ahead. Otherwise the alternative is just to set one more environment variable with `export ATOM_HOME = $XDG_CONFIG_HOME/atom`, which at the end of the day isn't that big of a deal.

Please let me know whether this might be a welcome change and I'll look into it further if so.

===============================================================================

As mentioned by someone else on this thread, it's not a good idea to hard code the locations to `~/.config/atom`, `~/.cache/atom`, etc.

[XDG]: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
[source]: https://github.com/atom/apm/blob/c6e5123b17c99233b661a616ce4e09c38c2c9a07/src/apm.coffee#L11-L12
[atom/apm]: https://github.com/atom/apm
[atom/atom]: https://github.com/atom/atom

**Comment by apjanke** [comment] 2015-10-16 14:50
+1 to this, especially on the Windows side. I think that would make it friendlier for advanced Windows users and administrators, who would know their platform's conventions, and use tools that make use of them.

> Atom should use "C:\Users\%USERNAME%\AppData\Roaming\Atom"
> ...
> Note that Windows can be installed on drive "D:\", so "C:\Users" used as example.

It's not just the drive letter that could be different; all these special "shell folders" are subject to renaming or relocation, due to localization, name conflicts, configuration by sysadmins, or changes between Windows versions. (For example, if multiple users with the same unqualified name log in to a machine (because they're from different domains, or the user names have changed), the profile folder basename will not match `%USERNAME%`.) They should be located using environment variables or corresponding Windows API calls, to respect this relocation.

The `C:\Users\%USERNAME%` folder is `%USERPROFILE%`.
The `C:\Users\%USERNAME%\AppData\Roaming` folder is `%APPDATA%`.
The `C:\Users\%USERNAME%\AppData\Local` folder is `%LOCALAPPDATA%`.

It's also a convention on Windows to add a "vendor" layer to the folder structure (for example, `%APPDATA%\GitHub\Atom` instead of `%APPDATA%\Atom`) to reduce the chance of product name collisions (and maybe to help in identifying what program created it). You might want to, or even need to, do that here: My `%APPDATA%` folder already has an `%APPDATA%\Atom` subdirectory that was there a few months prior to installing this Atom, and doesn't appear related. I don't know what it's from.

**Comment by impinball** [comment] 2015-11-08 11:24
For actual config being relocated on Linux, that could be a little inconvenient. +1 for the rest. Following file conventions is almost always a good thing.

Although I normally use Linux, I do feel that in Windows, not including the drive letter is better. It's better to use `%AppData%` than `C:\Users\%Username%\AppData\Roaming`, for example. Also, typically, `%AppData%` is used for config and saved settings, while `%LocalAppData%` is usually used for caching. I used to be a Windows power user, and that's what I have seen, but feel free to correct me if I'm wrong on any of this.

**Comment by coderstephen** [comment] 2015-11-30 01:38
:+1: Yes please. The non-standard locations used by Atom make setting up my configuration files more work for me, since I have to selectively choose which individual files that are actually configuration I want to back up, instead of just using the whole `~/.config/atom` directory like every other program I use on Linux.

**Comment by paulcbetts** [comment] 2015-11-30 01:46
_Copy-pasted from the other bug:_

I'm pretty :-1: on this change:

* All of the documentation / 3rd party blogs point to `C:\Users\NAME\.atom`, this will lead to a ton of "I don't have a `C:\Users\NAME\.atom` folder!" questions because they followed some guide

* `%AppData%\Atom` already has lots of stuff in it because it's the folder where Electron puts its data, whereas we expect users to directly edit files in this folder like `styles.less`

In exchange for these pretty significant drawbacks (especially that first one), we don't really get anything in return, other than some "cleanliness". If Atom weren't already released software it'd be a different story, but this really will cause problems for users if we try to move the folder.

**Comment by jamen** [comment] 2015-11-30 01:58
@paulcbetts 

The XDG standard defaults to some of the things Atom is currently use.  Someone probably isn't using the XDG environment vars if they don't know what they are.  And on the topic of support, the person needing help can simply state their operating system, and if they haven't used the XDG vars, it's in the location expected.  On the topic of old references like blog posts and documentation, we should always be making Atom better, we shouldn't let 3rd parties hold us back.  Posts can be edited. 

As far as Electron using `~/.config/Atom`, I would say that's a issue with Electron - so that would be another thing we should fix.

**Comment by apjanke** [comment] 2015-11-30 02:03
The "third-party documentation" problem will solve itself. If this change is made, "where's my .atom folder?" will bubble up to the top of the Google & SO results pretty quickly, and new pages will replace the old. Users will get the info they need, and if they want to dig deeper, learn more about platform conventions for storing user data. And there will be an opportunity for new people to earn rep and googlejuice by writing about this change.

"We can't change our mind about this design choice because some other people wrote about it" is ridiculous.

**Comment by paulcbetts** [comment] 2015-11-30 06:58
> The XDG standard defaults to some of the things Atom is currently using anyways. Someone probably isn't using the XDG environment vars if they don't know what they are

Not correctly looking up XDG folder names is different, I'm :+1: on fixing any of those kinds of bugs

> "We can't change our mind about this design choice because some other people wrote about it" is ridiculous.

Not only is it not ridiculous, it's the major reason that Linux as a platform is continuing to fail - this blind desire to break software and ecosystems around it, in order to promote something that's "technically correct". In this case, there's not even a user benefit! There is solely cost. Not a **single** user's life will be better as a result of this change. Not one. However, *many* users will be confounded and frustrated by it. Developers making choices like this have consistently hamstrung OSS platforms, over and over again.

I appreciate @pedromaltez's approach in that he's _thinking_ about the end user and the disruption this could cause, but even his approach has problems, in that it is now difficult to tell an arbitrary user where their Atom directory is ("Well, it's here, unless it's here, it might also be there uhhhhh, it depends!")

**Comment by envygeeks** [comment] 2015-11-30 07:07
> Not only is it not ridiculous, it's the major reason that Linux as a platform is continuing to fail - this blind desire to break software and the ecosystems around it in order to promote something that's more "technically correct". 

That's how you do it, blame Linux because you're bad at computers. Linux has been the same, you chose not to follow those principles (and you even demonstrated the lack of care for any principles on Windows too, are you going to say that's the reason that Windows the biggest operating system on the plant doesn't gain traction?)

Tell your bullshit to the fucking servers that run the site you are using to talk shit on Linux, or this user who knows thousands of people who use Linux.  Or the hundreds of thousands of people (actually more like millions) who use Ubuntu.

**Comment by paulcbetts** [comment] 2015-11-30 07:34
> Tell that to servers that run the site you are using to talk bad about Linux

I feel as if you think I want Linux or OSS to fail, which can't be further from the truth. On the contrary, I thoroughly want open-source software to *succeed*, which is **why** we cannot break user software unless we absolutely must. 

Do you know why Windows is the most popular operating system on the planet? It's not because its architecture is particularly good or elegant or beautiful (I've seen the source, I assure you, it's not). Because when you get an app, and it says on the box "Runs on Windows", you don't even have to *think* about what version it was written for. It Just Works. Entire buildings full of people put in thousands of man-hours into making sure when you download that EXE file, even if it's from 1998 and was never "written correctly" and didn't follow the "principles", it **just works**.

So, Atom should Just Work, and when we kick out the user's config dir out from under them, or make breaking changes to make an API "better", or or or, Atom no longer Just Works.

**Comment by envygeeks** [comment] 2015-11-30 08:00
> which is why we cannot break user software unless we absolutely must.

You don't need to break users software, you need to add utilities like Postfix where you can get information about the system and where everything is and ask users to post that, Docker does that too, even our software does that regardless of platform, because things are configurable and they can type "atom [--]info" and suddenly you have all the information *you* need.

> Here's one big reason: because when you get an app, and it says on the box "Runs on Windows", you don't even have to think about what version it was written for. It Just Works. Entire buildings full of people put in thousands of man-hours into making sure when you download that EXE file, even if it's from 1998 and was never "written correctly" and didn't follow the "principles", it just works.

Except they don't put that much effort in, and no, you cannot run a lot of binaries from 1998 on Windows, trust me, I've tried before just for fun and also, a lot of XP apps required a dedicated virtual machine, remember that Windows XP mode? That was because those thousand of hours of man-time were wasted and compatibility mode really turned out to not be all that good (and still isn't all that good, though it's improved.) So they needed a virtual machine to power those apps.

**Comment by jschneider** [comment] 2015-11-30 08:35
Guys, please try to calm down a bit.

I think there are a few things, that seem to be clear:

- the current location of config files is not the best choice
- following XDG specs on Linux is preferable
- using AppData\Roaming directories on Windows is preferable
- just changing the config directories and leaving the user without his configuration is a very, very bad idea

Therefore it seems to be pretty obvious that we need:
- a nice migration path for all users
- a (long) time where the old directories can still be used


Maybe this could be solved like this:
1. Step - Preparation / early adopters:
- The new directories are used if they exist. If they do not exist, atom uses the old directories. 
- Atom uses still the old directories per default (for easy use for new users)
- There is a menu entry (help menu?) that opens the config directory
- the new directories are documented
2. Step - Manual migration possible
- Atom adds a "migration wizard" to the menu. This wizard 
   - moves the content of the old directories to the new locations. 
   - adds a readme file with the location of the new folder into the old folder 
   - and/or creates a symlink to the new location
- Default is still using the old directory
3. Step - Changing default
- Atom uses the new directories by default
- Users are notified (maybe once a month) that the configuration files should be migrated (see above)
4. Step - enforcing the new directories
- If everything above works fine, the user could be notified maybe once a month that the configuration files should be migrated (see "migration wizard").
- The frequency of notifications is increased
5. Step - final migration (several months later)
- The user will be notified every day that the migration should be done now.

**Comment by jamen** [comment] 2015-11-30 15:58
+1 for @jschneider's steps.

We're not "breaking the software" if we choose to do this correctly, and migrate appropriately.

**Comment by SShrike** [comment] 2015-12-01 12:46
> Not a single user's life will be better as a result of this change. Not one.

I disagree, separating configuration, cache and data out into separate directories is makes backups of user configuration a whole lot easier (just a `tar -zcf config.tar.gz .config` away ) plus allowing all cached data to be blown away with a simple `rm -r ~/.cache`.

Also, +1 to @jschneider's steps seem like a pretty solid solution.

**Comment by skmlcd** [comment] 2016-02-29 07:59
:+1: on this issue, especially on Linux. Any progress?

**Comment by Siilwyn** [comment] 2016-02-29 10:55
As @Dremora [commented at a related issue](https://github.com/atom/atom/issues/2199#issuecomment-74733198) in Februari 2015! The changes can be made backward-compatible and it doesn't even have to be complicated. I mean even a bunch of symlinks could solve a lot. Another choice/option could be to slowly migrate as @jschneider proposed which may even be a better option.

Either way, just ditching this of as "we already released Atom so we can't change it" seems stupid and holds back improvement.

**Comment by isiahmeadows** [comment] 2016-02-29 18:06
@Siilwyn

Yes, symlinks are backwards compatible enough to be semver minor (unless people are using lstat), but removing it is a semver major break.

**Comment by Siilwyn** [comment] 2016-02-29 18:16
@isiahmeadows I only listed symlinks as a possible solution that could be combined with @jschneider's proposal. Though I think falling back to the old configuration location like @Dremora suggested is a bit cleaner. That said, plenty of options to do this in a graceful way.

**Comment by lee-dohm** [comment] 2016-03-01 19:15
Thanks everyone for your feedback on this. While this is something that we may do for future major versions, we won't be considering this for v1.x.

**Comment by jamen** [comment] 2016-03-01 20:44
@lee-dohm What about the symlink discussion?  That's backwards compatible, as stated.

**Comment by envygeeks** [comment] 2016-03-01 20:47
@jamen not without the users consent and very explicit at  that.  One does not just move around files and symlink without the users permission.  Home is home.  You don't go into somebodies home and start moving stuff around without asking them.

**Comment by jamen** [comment] 2016-03-01 20:54
@envygeeks I thought that was the point of the symlinks, to work as a polyfill until they are actually moved.

**Comment by envygeeks** [comment] 2016-03-01 20:56
@jamen I mean removing the symlink after it's added, I'm fine up until the symlink is removed without asking me and making sure I know.  If you move it to another folder and then symlink I can still work as I work now (my scripts can too) but once all that is being removed the proper course is to ask.

**Comment by jamen** [comment] 2016-03-01 20:59
@envygeeks Ah, I see now.  You do make a good point, that even if it were a major release, it would break a lot of things in userland.

**Comment by jamen** [comment] 2016-03-01 21:04
@envygeeks: @jschneider's steps take that into account though.

**Comment by CyberSkull** [comment] 2016-03-01 23:28
This is also an issue on OS X. Quoting #11014:

> Atom is not making full use of the standard file storage locations/conventions on OS X. OS X provides standard locations for storing configuration, data and cache files. Those location should be used instead of the  `~/.atom/` folder. Most of the items found in `~/.atom/` should be moved to `~/Library/Application Support/Atom/`.

> 
> The following files should be moved to `~/Library/Application Support/Atom/`:
> * `blob-store`
> * `config.cson`
> * `dev`
> * `init.coffee`
> * `keymap.cson`
> * `packages`
> * `snippets.cson`
> * `storage`
> * `styles.less`
> 
> The following files should be moved to `~/Library/Caches/Atom/`:
> * `compile-cache`
> * `Cache` (move from `~/Library/Application Support/Atom/`)
> * `GPUCache` (move from `~/Library/Application Support/Atom/`)

One particular side effect of the current setup is that cache files not in the Caches folder will be backed up by Time Machine.

**Comment by Zoltu** [comment] 2016-03-12 02:15
I would like to emphasize comment from @apjanke https://github.com/atom/atom/issues/8281#issuecomment-148737450.  The original description here (and many comments) reference `*:\Users\%USERNAME%\AppData`.  For all of the reasons mentioned in his post, an application should not reference those paths directly!  This will break on some international installs, it will break on some domain installs, it will break on users simply redirecting various folders to other drives.

Because there are so many comments here, **it would be nice if the original description could be updated to reflect this**.  I don't believe anyone participating in this discussion has a problem with this particular change.  It sounds like most of the debate is about whether to make a change at all.

**Comment by silasdavis** [comment] 2016-04-19 14:36
> Why is my `~/.atom` directory 500 MB?
-- Disgusted, of Tunbridge Wells

As others have said, it would be nice to have an clear single point of backup to preserve any declarative atom config from which we can rebuild a working installation. Would make sense to follow existing standards all things being equal, and it looks like people have solved the migration/backwards compatibility problem on paper at least.

**Comment by caesar** [comment] 2016-05-29 16:33
Is this going to be fixed? I'm getting really frustrated with all this junk in my home directory. Modern apps should be storing their data in the standard locations. Its not difficult.

**Comment by Siilwyn** [comment] 2016-09-02 14:11
Greenkeepe moved forward by moving the old config to the new location if it exists: https://github.com/greenkeeperio/rc/pull/3#issuecomment-244353503

**Comment by envygeeks** [comment] 2016-09-02 14:14
I'm sorry, but... what's that to do with Atom again?

**Comment by Siilwyn** [comment] 2016-09-02 14:40
It shows a possible solution the this issue which is in turn related to Atom.

**Comment by smyrman** [comment] 2016-12-01 22:50
> Thanks everyone for your feedback on this. While this is something that we may do for future major versions, we won't be considering this for v1.x.

Just in case anyone of the Atom developers wonders _why_ it's a good idea to follow the XDG Base Directory standard, it's not all about being as correct as possible, but also about adding real value to the end-users.

The best use-case I got myself, would be to sync the atom config files between my macbook and my Linux desktop alongside other developer tool configs, e.g. git config and neovim config. While I do so, I really, really do not want to sync compiled cache or other downloaded content at the sane tune.

Following the XDG Base Directory spec as well as the correct conventions for MacOS and Windows, makes this sync significantly easier, as you could just do a git init in ~/.config and manually add the files/folders you want to sync. Today I need to have bash scripts that creates ugly symlinks, wich works, but it"s tedious to maintain :-(

Hopefully the initial backwards-compatibility will be straight forward. Even if I had to add an `export ATOM_XDG_BASE_DIRECTORY_EXPERIMENT=1` to my shell's initfile, I would be quite happy with that as the initial support. Note that `export ATOM_HOME="$XDG_CONFIG_HOME/atom"` does not appear to be sufficient, as this adds non-config files and cache to the config directory.

**Comment by swirly** [comment] 2017-02-17 13:51
+1 on a resolution of this bug.

As I explained in a discussion thread, I'm trying to deploy atom in a high school on a standard industrialized base. I think atom has a great potential and we begin to teach code massively here in France

we have 1300+ users, using 300+ computers

of course, we use roaming profiles, so the users usually get their apps configured the same way on ALL computers. Everybody just use two or three differents computers in a day, and may be 10 in a week !

The correct way to implement this is to use the 

%APPDATA% environnement variable on windows, wich defaults to C:\Users\%username%\Appdata\Roaming 

This is the synchronised folder where the app should set their configuration (for those not using registry)

Each time one of our user change computers (all day long) he loose all the packages he downloaded and any config he made. 

Even if he come backs three days laters on the same computer, the profile was erased (any profile older than 24hour is automatically erased, for saving disk space : 1300+ users...)

Actually, atom can not have any customisation other than the "out of the box" one.  It's a real problem. for a highly customisable editor.

The usual environment variables for microsoft OS can be found here (for windows 7 and Vista)
https://technet.microsoft.com/en-us/library/dd560744(v=ws.10).aspx

It's very important to use %APPDATA% and not a hardcoded C:...  as on some networks, %APPDATA% is modified by system administrator (for many many reasons) by GPO

hope it helps.

**Comment by Siilwyn** [comment] 2018-02-17 16:59
Issue is still relevant.

**Comment by Siilwyn** [comment] 2018-02-22 12:02
Hi @lee-dohm since Electron 2 beta is out could this issue be reconsidered?

**Comment by the-j0k3r** [comment] 2018-06-27 07:38
>This issue has been automatically marked as stale because it has not had recent activity.

mmm this bot is not happy unless there's blood? JK ;) lets bump this for the sake of sakes.

**Comment by Seb-dev** [comment] 2018-08-09 16:01
Same problem with each release of `atom-bin` (1.29) for Gentoo
resolved with 
`chmod +x /usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/bin/git`

**Comment by sander1095** [comment] 2019-02-03 20:58
BUMP because of recent discussion on Reddit

https://www.reddit.com/r/programming/comments/amp06h/dotfile_madness/
https://www.reddit.com/r/linux/comments/971m0z/im_tired_of_folders_littering_my_home_directory/

**Comment by lee-dohm** [comment] 2019-02-04 21:09
Thanks for the feedback.

I understand that people have strong opinions on this. Realistically, this isn't something that the Atom team is going to take the time to work on anytime soon. We also won't be accepting a pull request for this functionality without an accepted [RFC](https://github.com/atom/atom/blob/master/docs/rfcs/000-template.md) that seriously considers and addresses all of the ramifications of making such a change to existing users and users of all skill levels.

Thanks again for all the interest.

**Closed by lee-dohm** 2019-02-04 21:09 UTC
Labels: feedback
