### ISSUE TITLE
Failed to deploy to 172.16.234.246 see console output for details.

### ISSUE THREAD

**Issue by tayarubam** [atom/atom#17115] opened 2018-04-11 14:30 UTC
[Enter steps to reproduce:]

1. Try to deploy a Roku channel using 
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Failed to deploy to 172.16.234.246 see console output for details.

```
At undefined

undefined
```

### Commands

```
     -4:27.3.0 application:reopen-project (atom-pane.pane.active)
  3x -1:38.6.0 roku-deploy:deployRoku (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-language-brightscript 0.3.0 
busy-signal 1.4.3 
go-plus 5.7.2 
gpp-compiler 3.0.7 
intentions 1.1.5 
language-brightscript 0.6.3 
linter 2.2.0 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
roku-deploy 0.5.1 
roku-develop 0.1.8 
terminal-plus 0.14.5 
```

**Comment by Arcanemagus** [comment] 2018-04-11 16:00
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17116. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-04-11 16:00 UTC
