### ISSUE TITLE
When searching show file beneath quick file pick

### ISSUE THREAD

**Issue by kevinsimper** [atom/atom#6375] opened 2015-04-14 14:08 UTC
Often you have files with the same names when searching, and you can easily see if you have the correct one based on the content, quicker than looking at the file path.

I suggest that the file is shown beneath the file quick picker.

**Comment by mnquintana** [comment] 2015-04-14 14:11
Duplicate of #3683 – please subscribe to that issue for updates. Thanks!

**Closed by mnquintana** 2015-04-14 14:11 UTC
