### ISSUE TITLE
Implement accessibility info at Mac OS X 

### ISSUE THREAD

**Issue by mkk** [atom/atom#11033] opened 2016-03-02 20:50 UTC
In OS X native text editing apps provide information about the edited text using the accessibility methods. It allows other application to communicate with the application.

Currently Atom does not support anything like that. Including the beta version.

Here is an example. On the screenshot, there is _TextMate_ (popular programmer editor) window and _Accessibility Inspector_ (displays information provided by other applications using accessibility).

The most interesting values are AXValue (editing content) and AXSelectedTextRange (range of the selected text.)

![accessibility](https://cloud.githubusercontent.com/assets/868275/13474673/683b6baa-e0bf-11e5-8a92-044750990f51.png)

**Comment by lee-dohm** [comment] 2016-03-03 08:12
This is a duplicate of https://github.com/atom/atom/issues/1691. You may want to subscribe there for updates.

Thanks for reporting!

**Closed by lee-dohm** 2016-03-03 08:12 UTC
