### ISSUE TITLE
International keyboard support

### ISSUE THREAD

**Issue by DJviolin** [atom/atom#7344] opened 2015-06-19 16:14 UTC
The following characters not working with the Hungarian keyboard:

\ => Alt Gr + q
[ => Alt Gr + f
€ => Alt Gr + u => This key also uploading the sync settings with the "sync-settings" plugin.

2 of these 3 keys ar urgent for code editing.

**Comment by 50Wliu** [comment] 2015-06-19 17:36
Duplicate of atom/atom-keymap#35, please subscribe there for updates.

**Closed by 50Wliu** 2015-06-19 17:36 UTC
