### ISSUE TITLE
[Feature Request] 64bit Windows build

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#9028] opened 2015-10-02 17:07 UTC
Would love to get a 64bit version of Atom for Windows, too since Linux and OS X already have it :)

**Comment by Zireael07** [comment] 2015-10-02 18:17
Agreed.

**Comment by 50Wliu** [comment] 2015-10-02 19:46
Duplicate of #4881, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-02 19:46 UTC

**Comment by Stanzilla** [comment] 2015-10-02 19:48
Oh oops, sorry.
