### ISSUE TITLE
atom.io API docs missing for a workspace item's optional methods

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#17746] opened 2018-07-25 18:50 UTC
`src/workspace.js` defines the [required and optional methods for a workspace item](https://github.com/atom/atom/blob/v1.28.2/src/workspace.js#L29-L174). The [API docs on atom.io](https://atom.io/docs/api/v1.28.2/Workspace) show the [required methods](https://github.com/atom/atom/blob/v1.28.2/src/workspace.js#L36-L41), but the [optional methods](https://github.com/atom/atom/blob/v1.28.2/src/workspace.js#L36-L41) are missing from the docs for some reason:

![screen shot 2018-07-25 at 14 39 45 pm](https://user-images.githubusercontent.com/2988/43221066-b5df8af6-9019-11e8-99c7-b2ab0e19082a.png)

**Comment by kodemonster** [comment] 2018-11-18 22:57
How can we find out what methods should be listed there?

**Comment by 50Wliu** [comment] 2018-11-19 03:14
Click on the first link in the issue.

**Comment by Aerijo** [comment] 2019-01-25 12:11
@jasonrudolph Duplicate of #16106 (@WolfieMario posted first -_-)

On a related note, it's also stuffing up the [options parameter](https://atom.io/docs/api/v1.17.0/Workspace#instance-open) properties of [`workspace.open`](https://github.com/atom/atom/blob/2791572cd20b1d8c84a100e8308dcce57d1853d7/src/workspace.js#L821-L853). It's interpreted as an optional argument, and it's properties as arguments themselves. There may be more, but that's all I looked at.

**Comment by Aerijo** [comment] 2019-03-04 09:42
It looks like the biggest difference between this and the `config.js` docs are that the headers have code in them. In particular, the description stops as soon as `` // #### `getTitle()` `` is reached, and `workspace.js` is the only file to match this regex pattern ``//\s*#{1,4} ` ``

The docs are all there in `jsMetadata`, but they break after the call to `tello.digest([metadata])`.

**Comment by Aerijo** [comment] 2019-06-14 15:11
I was wrong; the cause is the `Returns` at the start of a paragraph. The parser has [special handling](https://github.com/atom/atomdoc/blob/632b25d0a35078a95915defead04868ea29eda25/src/parser.js#L381-L382) for when the paragraph looks like a "return value", and will stop all further description making.

**Comment by Aerijo** [comment] 2019-06-15 10:23
> On a related note, it's also stuffing up the options parameter properties of workspace.open. It's interpreted as an optional argument, and it's properties as arguments themselves

The generated api JSON looks fine, with and without the fix for this issue. The format of `Workspace.open` matches that of `TextEditor.setTextInBufferRange`, which also has an options object. I don't know if I can debug that any further.

**Comment by kam773** [comment] 2019-06-26 23:22
Can I work on this one?

**Comment by as-cii** [comment] 2019-07-23 14:13
This seems to be related to https://github.com/atom/atom/issues/16106 and, as mentioned by @Aerijo, both issue can be tracked down to the same underlying cause. I am assigning myself to it because I already opened a few pull requests to fix #16106.

**Closed** 2019-07-26 09:23 UTC
Labels: d ⬆️, documentation, i ⬇️, v ⬇️
