### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/5.py'

### ISSUE THREAD

**Issue by slopey112** [atom/atom#19080] opened 2019-04-01 06:08 UTC
1. Open two project folders.
2. Move a python file from one project folder to the other.

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/5.py'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/5.py'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:912566)
    at TreeView.t.exports.TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:918320)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:893160)
```

### Commands

```
     -0:17.8.0 core:close (atom-pane.pane.active)
```

### Non-Core Packages

```
language-lisp 0.2.0 
```

**Comment by Theriot7797** [comment] 2019-04-01 06:56
Fuck off

**Comment by Theriot7797** [comment] 2019-04-01 07:04
> 1. Open two project folders.
> 2. Move a python file from one project folder to the other.
> 
> **Atom**: 1.35.1 x64
> **Electron**: 2.0.18
> **OS**: Mac OS X 10.14
> **Thrown From**: Atom Core
> 
> ### Stack Trace
> Uncaught Error: ENOENT: no such file or directory, lstat '/5.py'
> 
> ```
> At fs.js:1661
> 
> Error: ENOENT: no such file or directory, lstat '/5.py'
>     at Proxy.realpathSync (fs.js:1661:15)
>     at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
>     at TreeView.t.exports.TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:912566)
>     at TreeView.t.exports.TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:918320)
>     at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:893160)
> ```
> ### Commands
> ```
>      -0:17.8.0 core:close (atom-pane.pane.active)
> ```
> ### Non-Core Packages
> ```
> language-lisp 0.2.0 
> ```

😶

**Comment by lee-dohm** [comment] 2019-04-01 15:34
@Theriot7797 your comment was hidden as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by rsese** [comment] 2019-04-01 21:23
Thanks for the report @slopey112 :+1:

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-04-01 21:23 UTC
