### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by cars000000** [atom/atom#8021] opened 2015-07-22 05:54 UTC
[Enter steps to reproduce below:]

1.just open any file
2.CTRL + R

**Atom Version**: 1.0.2
**System**:  Windows 8.1 
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.100.0

### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:260

Error: spawn UNKNOWN
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:188:44)
  at new BufferedProcess (C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:50:14)
  at TagGenerator.module.exports.TagGenerator.generate (C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\tag-generator.js:149:15)
  at FileView.module.exports.FileView.generateTags (C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\file-view.js:144:62)
  at FileView.module.exports.FileView.populate (C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\file-view.js:139:21)
  at FileView.module.exports.FileView.toggle (C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\file-view.js:98:14)
  at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:toggle-file-symbols (C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\symbols-view\lib\main.js:21:43)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\l\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\圣庭\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
  2x -7:05.3.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -6:22.6.0 symbols-view:toggle-file-symbols (atom-pane.pane.active)
 23x -6:13.8.0 window:increase-font-size (atom-pane.pane.active)
     -6:12.6.0 settings-view:open (atom-pane.pane.active)
     -6:05.4.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -5:51.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -5:49.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 37x -5:46.6.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.mini.is-focused)
     -3:38.8.0 release-notes:show (atom-text-editor.editor.is-focused)
     -0:13.4.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by batjko** [comment] 2015-07-22 13:47
What's your COMSPEC environment variable set to?

**Comment by cars000000** [comment] 2015-07-23 01:26
comspec is "%SystemRoot%\system32\cmd.exe", which refers to "C://windows/system32/cmd.exe"

**Comment by kevinsawicki** [comment] 2015-07-27 22:02
This is a duplicate of https://github.com/atom/symbols-view/issues/117

**Closed by kevinsawicki** 2015-07-27 22:02 UTC
Labels: uncaught-exception
