### ISSUE TITLE
Installation does not work on Windows 10 x64

### ISSUE THREAD

**Issue by zhangnian** [atom/atom#11247] opened 2016-03-23 02:42 UTC
The lastest install packages(version 1.6.0) from website atom.io can't install on Windows 10 x64, from its error message i guess if it is the 32-bit version?

I also download the package verson 1.5.4, It works well.

**Comment by mnquintana** [comment] 2016-03-23 03:37
This looks like a duplicate of https://github.com/atom/atom/issues/11235 – let's keep the discussion there.

**Comment by thomasjo** [comment] 2016-03-29 06:26
Actually this looks like a different problem (just a minor language/terminology confusion); this is actually related to the installation of Atom itself.

/cc @damieng

**Comment by damieng** [comment] 2016-04-02 07:45
Can you post a screenshot of the error? 32-bit binaries work fine on 64-bit systems so would be good to get an indication as to what exactly is unhappy.

**Comment by Valenchak** [comment] 2016-04-02 17:35
даже не устанавливал

**Comment by damieng** [comment] 2016-04-12 21:44
No response for more information. Please re-open if you can provide a screenshot or the exact error message.

**Closed by damieng** 2016-04-12 21:44 UTC
Labels: installer, more-information-needed, windows
