### ISSUE TITLE
Once a file in a project is opened in a different text editor it disappears from atom

### ISSUE THREAD

**Issue by ericbrooke** [atom/atom#3736] opened 2014-10-06 23:49 UTC
On Mac, lost a couple files this way.  All of which are ymls they are also all in my gitignore.  I opened with open with choice and they came back, one by one manually.

Atom version 0.135.0
Mac OS X 10.9.5

**Comment by izuzak** [comment] 2015-09-15 15:10
I wasn't able to reproduce this either on OSX 10.10.5 and Atom 1.0.12-dev-c7d4871.

Since we haven't seen other reports, haven't been able to reproduce this, and @ericbrooke didn't get back to us on the question posted in https://github.com/atom/atom/issues/3736#issuecomment-58131142 -- I'm going to close this. @ericbrooke if you can still reproduce this in Atom 1.0.11 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) -- please let us know and provide more details.

**Closed by izuzak** 2015-09-15 15:10 UTC
