### ISSUE TITLE
hi to everyone im not a programmer but i can support with the Greek (el) language translation 

### ISSUE THREAD

**Issue by tsiras** [atom/atom#18007] opened 2018-09-08 05:51 UTC
hi to everyone
i'm not a programmer but i can support this project with the Greek (el) language translation i know is not an easy job but is helpful .i can make a try .... atom means άτομο (the one )
if you in the atom community are interested please send me the pages that contains the (eng to el) texts for translation. or in the documentation 
best regards
tsiras p. michael

## Summary

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered. Be sure to explain why Atom's existing customizability isn't suitable for this feature.

**Comment by Arcanemagus** [comment] 2018-09-08 07:36
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/3103. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-09-08 07:36 UTC
