### ISSUE TITLE
Undo/redo doesn't change cursor position after multiple block edit

### ISSUE THREAD

**Issue by xeron** [atom/atom#8178] opened 2015-07-31 21:36 UTC
May be related to: #6915 and #2158.

Atom: 1.0.3
OS X: 10.10.4

Steps to reproduce:
1. Open some long file (2+ pages)
2. Edit something on the top of file
3. Scroll down and edit something using multiple selection
4. Cancel multiple selection with ESC
5. Try to undo/redo changes

Cursor will be always in the same position (in the latest multiple selection place).

**Comment by maxbrunsfeld** [comment] 2015-08-25 19:10
Thanks for this report @xeron, and I'm really sorry that this bug existed for so long. I believe it'll be fixed in the next release, Atom 1.0.8.

**Comment by xeron** [comment] 2015-08-25 20:02
:+1:

**Comment by maxbrunsfeld** [comment] 2015-09-02 17:17
It turns out that the fix for this bug introduced another regression, so we need to roll it back. Working on a new fix now.

**Comment by maxbrunsfeld** [comment] 2015-09-02 18:23
Ok, we've found a fix that doesn't require rolling this back :+1:. False alarm.

**Closed by maxbrunsfeld** 2015-09-02 18:23 UTC
Labels: atom, bug
