### ISSUE TITLE
Atom stops opening files

### ISSUE THREAD

**Issue by kans** [atom/atom#5777] opened 2015-02-27 02:08 UTC
Under some (potentially all) conditions, atom squelches errors in the callback to atom.workspace.eachEditor (something something domains).  The result is that atom stops opening files with no user feedback as to why.  I'm not sure if the same problem exists with observe, but I'm guessing the answer is yes.  Plugins should not be able to interfere with the editor.

**Comment by lee-dohm** [comment] 2015-02-27 06:09
Do you have a consistent repro or a package that is causing this behavior? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have the [Emmet package](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by kevinsawicki** [comment] 2015-07-21 17:55
Closing this out since more details were never provided and the API referred to is no longer available in Atom 1.0+

**Closed by kevinsawicki** 2015-07-21 17:55 UTC
Labels: more-information-needed
