### ISSUE TITLE
Launch time slow on Ubuntu 14.04

### ISSUE THREAD

**Issue by Faiz7412** [atom/atom#7347] opened 2015-06-20 08:01 UTC
I have 8 GB ram and all my apps run blazing fast, including chrome which is known these days to be laggy.
Unfortunately, launch time for Atom is really slow on Ubuntu 14.04 64 bit

**Comment by mnquintana** [comment] 2015-06-20 10:46
Duplicate of https://github.com/atom/atom/issues/3673 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-20 10:46 UTC
Labels: duplicate
