### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isValid' of undefined

### ISSUE THREAD

**Issue by Rubemlrm** [atom/atom#10014] opened 2015-12-11 10:49 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0-beta0
**System**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'isValid' of undefined

```
At C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\text-editor-presenter.js:665

TypeError: Cannot read property 'isValid' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateOverlaysState (C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\text-editor-presenter.js:665:36)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPostMeasurementState (C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\text-editor-presenter.js:166:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getState (C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\text-editor-presenter.js:183:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\text-editor-component.js:195:38)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\text-editor-component.js:278:21)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\text-editor-component.js:933:16)
    at TextEditorComponent.module.exports.TextEditorComponent.pollDOM (C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\text-editor-component.js:920:17)
    at C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\view-registry.js:259:9)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\view-registry.js:222:14)
    at C:\Users\rubemlrm\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\view-registry.js:3:61
```

### Commands

```
     -1:45.7.0 core:copy (atom-text-editor.editor.is-focused)
  3x -1:42.5.0 core:paste (atom-text-editor.editor.is-focused)
     -1:23.8.0 core:undo (atom-text-editor.editor.is-focused)
     -1:17.2.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:16.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:06.6.0 core:copy (atom-text-editor.editor.is-focused)
 46x -0:55.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:46.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:39.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:37.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:37.6.0 core:move-right (atom-text-editor.editor.is-focused)
 14x -0:37 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.2.0 core:copy (atom-text-editor.editor.is-focused)
  3x -0:14.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:11.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:10.2.0 pane:split-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "php-class-tree",
      "minimap",
      "sass-autocompile",
      "linter-sass-lint"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "tabLength": 4,
    "fontFamily": "Source Code Pro",
    "scrollPastEnd": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-material-ui, v0.8.0
auto-detect-indentation, v0.4.2
build, v0.50.0
docblockr, v0.7.3
dockerletion, v0.1.0
file-type-icons, v0.7.4
language-blade, v0.16.0
language-diff, v0.4.0
language-docker, v1.1.6
language-mongodb, v0.3.1
language-tmux, v0.4.0
laravel, v0.7.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.1.0
linter-js-standard, v3.2.1
linter-jsonlint, v1.1.0
linter-perl, v0.7.1
linter-php, v1.1.6
linter-phpcs, v1.3.0
linter-phpmd, v1.3.2
linter-pylint, v1.2.0
linter-ruby, v1.2.0
livereload, v0.4.4
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.1
php-debug, v0.1.4
php-getters-setters, v0.5.5
php-introspector, v1.0.0
phpunit-snippets, v0.1.0
project-manager, v2.6.5
remote-edit, v1.8.23
rest-client, v0.5.0
seti-syntax, v0.4.1
SFTP-deployment, v1.0.2
terminal-panel, v1.14.1
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by coreyk** [comment] 2015-12-11 17:46
Happening on 1.3.1 too:
[Enter steps to reproduce below:]

1. ... Open Atom
2. ... Edit file

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'isValid' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:665

TypeError: Cannot read property 'isValid' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateOverlaysState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:665:36)
    at TextEditorPresenter.module.exports.TextEditorPresenter.setGutterWidth (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1400:21)
    at TextEditorComponent.module.exports.TextEditorComponent.measureDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:964:22)
    at TextEditorComponent.module.exports.TextEditorComponent.pollDOM (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:922:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61
    at ViewRegistry.module.exports.ViewRegistry.performDocumentPoll (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:234:9)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:197:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
     -1:24.9.0 pane:split-right (atom-text-editor.editor.is-focused)
 16x -0:31.6.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "ember-snippets",
      "jshint",
      "atom-beautify"
    ],
    "openEmptyEditorOnStart": false
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "softWrap": true,
    "preferredLineLength": 5000,
    "fontFamily": "source code pro",
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v1.1.0
atom-html-preview, v0.1.13
atom-wordpress, v0.3.0
autoclose-html, v0.19.0
autocomplete-php, v0.3.7
autocomplete-ruby, v0.1.0
clipboard-plus, v0.5.1
color-picker, v2.0.14
css-comb, v2.4.0
css-snippets, v0.9.0
docs-snippets, v0.8.0
editor-stats, v0.17.0
emmet, v2.3.17
file-icons, v1.6.13
filesize, v0.4.2
fonts, v1.0.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
html-entities, v0.4.0
jquery-snippets, v11.0.0
jsformat, v0.9.0
language-pgsql, v0.2.0
linter, v1.11.3
linter-csslint, v1.1.0
linter-jshint, v1.2.1
linter-rubocop, v0.4.4
node_modules, vundefined
pretty-json, v0.4.1
symbol-gen, v1.0.0
symbols-tree-view, v0.10.1
sync-settings, v0.6.0
w3c-validation, v0.2.0
webbox-color, v0.5.9
wordcount, v2.4.1

# Dev
No dev packages
```

**Comment by jtheoof** [comment] 2015-12-13 03:23
I confirm this is also happening on `1.3.1`.

**Comment by 50Wliu** [comment] 2015-12-13 03:32
@jtheoof what packages are you using?

@Rubemlrm, @coreyk, @jtheoof: does this happen all the time?  Are there specific reproduction steps or does it happen randomly?  And finally, does this error still occur if you run Atom in safe mode (`atom --safe`)?  Thanks!

**Comment by jtheoof** [comment] 2015-12-13 03:36
@50Wliu I was using `TypeStrong/atom-typescript @7.14.2` when it happened. I had two vertical split windows. I was not able to reproduce since restart of `atom`.

Here is a dump of all my packages.

```
activate-power-mode@0.4.1
atom-beautify@0.28.19
atom-fuzzy-grep@0.8.0
atom-typescript@7.14.2
color-picker@2.0.14
compare-files@0.6.2
dash@1.5.0
docblockr@0.7.3
emmet@2.3.17
file-explorer@0.3.0
file-icons@1.6.13
git-blame@0.4.7
git-history@3.2.0
git-plus@5.6.10
git-status@0.3.3
jumpy@2.0.10
language-diff@0.4.0
language-docker@1.1.6
linter@1.11.3
linter-eslint@5.2.6
linter-jscs@3.2.0
linter-jshint@1.2.1
linter-tslint@0.6.0
minimap@4.18.0
open-this@0.1.8
open-vim@0.2.2
project-manager@2.6.5
sort-lines@0.12.0
symbols-tree-view@0.10.1
vim-mode@0.63.0
vim-surround@0.8.1
```

**Comment by 50Wliu** [comment] 2015-12-13 16:29
Two things I noticed:
* All the errors happened after a pane split.
* The error is coming from updateOverlayState, which could? suggest that the error is coming from Linter, which is the only package that all three reports have in common.

**Comment by IvoKoller** [comment] 2015-12-20 11:57
I can confirm what 50Wliu said: 
- The error occurs after a pane split and it is probably coming from Linter.
It seems that (at least when I get the error) that I'm currently working on a 
.css file - which leads me to the conclusion that it has something to do with the "csslint"-package.
But since jtheoof has also experienced the error I'm not 100% sure about that.

**Comment by 50Wliu** [comment] 2015-12-20 17:14
@steelbrain would you like to take a look and see if the error might be coming from your side?

**Comment by steelbrain** [comment] 2015-12-20 17:16
@50Wliu the bug @IvoKoller  is expericing was fixed months ago in both Atom and Linter, it shouldn't be reproducible in the latest versions of either

**Comment by jtheoof** [comment] 2015-12-20 18:50
@IvoKoller I was definitely working on a `ts` file when the error occured.
@steelbrain We were using `linter@1.11.3`. So it's pretty recent.

**Comment by steelbrain** [comment] 2015-12-20 18:53
We have only had one error relating panes from the beginning in linter, and that was fixed. I am not aware of any other errors. The traces that I see here are from the TextEditor from atom core and not from linter, not sure what's wrong

**Comment by IvoKoller** [comment] 2015-12-20 18:54
@steelbrain I was and am using the version 1.3.2 which is latest version.

**Comment by 50Wliu** [comment] 2015-12-20 19:12
@steelbrain Yeah, I wasn't sure if it was from Linter or Atom core, just wanted to ask to make sure.

**Comment by jtheoof** [comment] 2015-12-21 00:06
OK so today I was able to reproduce the issue.  Here a more feedbacks.

While working on `typescript` code (vertical split windows). One of my file had errors. This file was opened in both split panes. By closing the file on the right pane, and saving the file on the left pane, the error showed up again.

<img width="460" alt="screen shot 2015-12-20 at 7 00 43 pm" src="https://cloud.githubusercontent.com/assets/90020/11921025/6b488cbc-a74c-11e5-8a29-4191189097e2.png">

There are two error toasters that show up, one for the linter and one for atom core.

Hope this helps.

**Comment by steelbrain** [comment] 2015-12-21 04:43
@jtheoof If you could provide me the trace from the linter one, that would be **very** helpful

**Comment by jtheoof** [comment] 2015-12-21 05:10
@steelbrain I will try next time, this bug is playing hide and seek.

**Closed** 2016-01-11 22:41 UTC
Labels: atom, bug, uncaught-exception

**Comment by bgrieder** [comment] 2016-01-18 11:39
@steelbrain @jtheoof Stacktraces I get for the same error


    TypeError: Cannot read property 'onDidDestroy' of undefined
    at new Decoration (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration.js:58:49)
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1052:20)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1288:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/bgrieder/.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/bgrieder/.atom/packages/linter/lib/helpers.coffee:23:18



    TypeError: Cannot read property 'isValid' of undefined
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateOverlaysState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:665:36)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPostMeasurementState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:166:14)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:183:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:195:38)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:298:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:227:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61

**Comment by steelbrain** [comment] 2016-01-18 11:49
@bgrieder Now that stack trace was really helpful! Thank you for that. I just want all of you to know that the bug pointed out in your stack trace has already been fixed in the UI rewrite, you can expect it soon.

The bug is that the linter bubble was re-using the markers from underline highlights. If you are receiving this error a lot of times and want a workaround, the workaround is to disable inline bubble/tooltip
