### ISSUE TITLE
Uncaught Error: ENXIO, no such device or address '/Users/weldemariam/Projects/experiments/dockerbox/code/airwatch-redesign/app/templates'

### ISSUE THREAD

**Issue by samtes** [atom/atom#5863] opened 2015-03-05 17:40 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENXIO, no such device or address '/Users/weldemariam/Projects/experiments/dockerbox/code/airwatch-redesign/app/templates'

```
At /Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/src/pane.js:782

Error: ENXIO, no such device or address '/Users/weldemariam/Projects/experiments/dockerbox/code/airwatch-redesign/app/templates'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:752:18)
  at Function.sync (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/node_modules/fs-plus/node_modules/mkdirp/index.js:55:12)
  at Object.fsPlus.writeFileSync (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:242:14)
  at File.module.exports.File.writeFileSync (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:239:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:309:21)
  at File.module.exports.File.write (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:298:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/src/pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/src/pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/src/workspace.js:677:35)
  at atom-workspace.atom.commands.add.core:save (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/weldemariam/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -1:29.7 find-and-replace:show (atom-text-editor.editor.is-focused)
  4x -1:23.3 core:confirm (atom-text-editor.editor.mini)
     -0:58.8 core:move-right (atom-text-editor.editor.mini)
     -0:58.4 core:move-left (atom-text-editor.editor.mini)
  3x -0:54.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:46.2 core:confirm (atom-text-editor.editor.mini)
  3x -0:42.3 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:23.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "grunt-runner",
      "merge-conflicts",
      "minimap",
      "preview",
      "travis-ci-status",
      "vim-mode"
    ],
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "zoomFontWhenCtrlScrolling": true,
    "autoIndentOnPaste": false,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.2.0
autocomplete-plus, v1.1.0
color, v0.5.0
color-picker, v1.4.4
language-jade, v0.3.0
linter, v0.10.1
project-manager, v1.15.0
seti-ui, v0.6.3
webbox-color, v0.5.4

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-04-28 21:25
I believe this is a duplicate of https://github.com/atom/atom/issues/5576 which was fixed in https://github.com/atom/atom/commit/55b6499b7d932f4baa845c786d16e8da4d484547 and released in 0.192

**Closed by kevinsawicki** 2015-04-28 21:25 UTC
