### ISSUE TITLE
Garbled tree view on OSX

### ISSUE THREAD

**Issue by chmac** [atom/atom#7888] opened 2015-07-14 08:31 UTC
I'm not sure how to reproduce this, but I see it somewhat regularly. I'm not even sure how to describe it, so perhaps there's already an open issue for the same problem that I couldn't find.

I'm using Atom 1.0.2 on OSX 10.10.3, installed packages:

```
├── Sublime-Style-Column-Selection@1.3.0
├── brogrammer-syntax@1.0.0
├── brogrammer-ui@1.0.0
├── color-picker@2.0.10
├── ctrl-last-tab@0.2.0
├── editorconfig@1.0.1
├── rulerz@0.3.3
└── webbox-color@0.5.7
```

Just let me know if I can post any other useful info. I read the debugging guide but I didn't think most of it was relevant.

* To clear the issue, I just close and open a directory in the tree view. I'm not 100% sure, but I think that forcing it to redraw fixes the issue.
* Switching from the Atom application to another OSX application has no effect.
* Moving the Atom window, while it is the active window, or not, has no effect.

<img width="202" alt="screen shot 2015-07-14 at 10 23 10" src="https://cloud.githubusercontent.com/assets/690997/8669210/f0856376-2a12-11e5-9eec-da299ad3cb9f.png">

**Comment by chmac** [comment] 2015-07-14 08:31
Oh, and in case it's related, the red line you see across the bottom of the screenshot is from an awesome little application called Honer.

**Comment by mnquintana** [comment] 2015-07-14 10:41
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/4924 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-14 10:41 UTC
