### ISSUE TITLE
Atom Git Project Freeze/Hanging Frame after Refocusing

### ISSUE THREAD

**Issue by michaelgira23** [atom/atom#14792] opened 2017-06-15 21:39 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whenever I'm inside a Git repository and I refocus the editor (by clicking outside the window then back in), Atom will freeze up for a few seconds before functioning as expected. I've noticed that the delay is generally longer the bigger the selected file is.

[Here's quick gif about what I'm talking about.](https://i.imgur.com/w3qXcu2.gifv) Notice how the cursor in the first clip (opened in a plain folder) immediately pops up upon focusing the window, while the cursor in the second clip (opened in the Git repo) has a slight delay before the cursor pops up.

Furthermore, when doing this same thing in the Chrome tools timeline, you see the big red section in which the frame freezes:

![atom-timeline](https://user-images.githubusercontent.com/6778537/27199642-6123b7ac-51dc-11e7-8a98-9eedeb9c2f47.png)

### Steps to Reproduce

1. Start up Atom
2. Open up a folder that is a Git repo
3. Open any file in the repo
4. Click somewhere outside the Atom window (therefore deselecting it)
5. Click back onto the editor (will freeze for a few seconds)

**Expected behavior:** Editor doesn't freeze

**Actual behavior:** Editor freezes for a few seconds

**Reproduces how often:** Every single time I deselect the Window and reselect. **This also sometimes occurs when opening up a new file within the Git repo.**

### Versions
```
> atom --version

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

>apm --version

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.12.0.windows.1
visual studio 2015
```
I'm on Windows 10 Version 1703 (OS Build 15063.413)

### Additional Information

When I first installed Atom, I didn't have this issue. This issue started happening after updating Atom some time ago (don't know which version sorry!)

Any help is much appreciated! Thanks!

**Comment by 50Wliu** [comment] 2017-06-15 21:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #9544. You may want to subscribe there for updates.  https://github.com/atom/atom/issues/9544#issuecomment-254378382 lists a potential workaround.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-06-15 21:54 UTC
