### ISSUE TITLE
Search All Open Files

### ISSUE THREAD

**Issue by c0fe** [atom/atom#11116] opened 2016-03-09 18:01 UTC
Add a feature to search all open files like it can be done in Dreamweaver. # # #

**Comment by 50Wliu** [comment] 2016-03-09 20:18
This is a duplicate of atom/find-and-replace#241 - feel free to subscribe there for updates.

In the future, please follow the issue template, as that would have told you to report the issue over there instead.

**Closed by 50Wliu** 2016-03-09 20:18 UTC
