### ISSUE TITLE
Markdown syntax highlight is broken after * in a code block

### ISSUE THREAD

**Issue by apuchkov** [atom/atom#10576] opened 2016-01-25 16:22 UTC
**Atom Version:** 1.4.0
**OS:** Windows 10

![image](https://cloud.githubusercontent.com/assets/150003/12556796/ad3210a6-c355-11e5-8c18-bbc48579f5a9.png)

**Sample Code:**
```md
Lorem ipsum

    <S127.0.0.1:11111:132333898:*grn/D9BB797F/00000000:@c24c4187>.
    [2014-03-12 15:25:37.398 GMT    27      WARNING 100157  CallbackData    127.0.0.1:11111] 

Text, which should not be purple.
```

**Comment by amytruong** [comment] 2016-01-25 17:47
@apuchkov That is a bug :grimacing: Thanks!

Fortunately, there's also a workaround for that by using fenced code blocks. 
<img width="838" alt="screen shot 2016-01-25 at 9 43 11 am" src="https://cloud.githubusercontent.com/assets/10725993/12559196/743e0b7c-c348-11e5-8a38-1d9e2bed3747.png">

This also might be helpful. :point_right: https://help.github.com/articles/github-flavored-markdown/

**Comment by 50Wliu** [comment] 2016-01-25 18:07
This is actually a duplicate of atom/language-gfm#44 - please subscribe there for updates!

**Closed by 50Wliu** 2016-01-25 18:07 UTC
Labels: bug
