### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/carmenminikus/Library/Applicatio...

### ISSUE THREAD

**Issue by minikus** [atom/atom#10941] opened 2016-02-23 22:11 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/carmenminikus/Library/Application Support/com.github.atom.ShipIt/update.ywHuEMe/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -6:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:01.9.0 core:save (atom-text-editor.editor.is-focused)
  3x -5:56.6.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -2:48.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:45.6.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -2:45.2.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:42.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:39.2.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -2:37.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:35.7.0 core:backspace (atom-text-editor.editor.is-focused)
  8x -2:35.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:59.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:56.3.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:56 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:53.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:08.2.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 14,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-02-23 22:52
Thanks for the report!  This is a duplicate of #9559, so feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-23 22:52 UTC
Labels: uncaught-exception
