### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by gabodo** [atom/atom#4645] opened 2014-12-16 16:43 UTC
Uncaught TypeError: Arguments to path.join must be strings

**Atom Version**: 0.158.0
**System**: linux 3.13.0-40-generic
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At path.js:384

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:384:15)
  at atom-workspace.atom.commands.add.window:run-package-specs (/opt/atom/resources/app/src/workspace-element.js:248:49)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:167:20)

```

**Comment by sdornan** [comment] 2015-06-25 21:10
I just got this error with Atom 1.0.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:449

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:449:13)
  at tryPathIndex (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/index.js:230:37)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/index.js:233:29
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -2:04.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:02.9.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:00.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:57.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:57.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:57.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:55.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  5x -0:07.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:05.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -0:03.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jscs",
      "linter-pylint"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.6
color-picker, v2.0.7
editorconfig, v1.0.0
file-icons, v1.5.8
language-jade, v0.4.0
linter, v1.0.4
linter-jshint, v0.1.6
linter-less, v2.0.0
linter-pep8, v0.2.0
minimap, v4.10.0
monokai, v0.14.0
pigments, v0.8.0
tabs-to-spaces, v0.11.0
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-26 11:20
That sounds like a different problem than the one described in the initial report, but still reopening this since less-cache is in the path in the stack trace. /cc @kevinsawicki for :eyes: and :thought_balloon:

**Comment by kevinsawicki** [comment] 2015-07-21 22:58
I don't think this was caused by any core code since it looks like the async less loading path which isn't used internally anywhere.

So I'm going to close this out, I believe it was package doing some async less parsing and having bad inputs to the Less API.

**Closed by kevinsawicki** 2015-07-21 22:58 UTC
Labels: needs-reproduction

**Comment by benjamine** [comment] 2015-09-24 15:15
atom took me here, here's my stack trace
```
TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:467:13)
  at tryPathIndex (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/index.js:230:37)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/index.js:233:29
  at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by 50Wliu** [comment] 2015-09-25 00:59
@benjamine What Atom version are you on?

**Comment by benjamine** [comment] 2015-09-25 01:01
1.0.16 (on OSX 10.10.5)
