### ISSUE TITLE
Choosing "Help" -> "Documentation" from menu freezes Atom

### ISSUE THREAD

**Issue by reinvantveer** [atom/atom#9927] opened 2015-12-03 08:45 UTC
This one is reproducible for me: running Atom 1.2.1 as root (don't ask me why, I know it's wrong) on Ubuntu with LXDE desktop environment. Needs restarting when this happens.

**Comment by SuperuserMax** [comment] 2015-12-03 09:59
Just tried it out myself, as root, on LXDE (Linux Mint with meta lxde), is working actually.
First thing: Are you sure it's supposed to be working? (root or su / gksu / sudo ?, how do you execute?)

**Comment by reinvantveer** [comment] 2015-12-03 13:01
$ sudo su
$ atom
Sorry I can't be of more help, is there a dump I can upload when I encounter this again?

**Comment by PombaM** [comment] 2015-12-08 04:22
I am on v1.2.4, can't reproduce. Update to the latest version.

**Comment by drewmnoel** [comment] 2016-05-21 00:55
I could recreate this using the latest source. No crash, it just sits there. Nothing in the log file, the following was from safe mode:

```
$ atom -f --safe
[3670:0520/205304:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[3670:0520/205304:INFO:audio_manager_pulse.cc(257)] Failed to connect to the context.  Error: Connection refused
App load time: 1016ms
[3670:0520/205306:INFO:CONSOLE(52)] "Window load time: 1188ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (52)
[3670:0520/205307:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[3670:0520/205308:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
```

Relevant version numbers:

```
$ atom --version
Atom    : 1.9.0-dev-7253514
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.2
```

**Comment by 50Wliu** [comment] 2016-05-23 16:44
I have a suspicion that this has been fixed in Electron 0.38.  Can someone please try building the latest master and see if this issue has been resolved?

**Comment by drewmnoel** [comment] 2016-05-23 21:14
Latest master does fix the freezing. It doesn't open anything, but that's *probably* related to latest Chromium not running as root anyways.

```$ atom -v
Atom    : 1.9.0-dev-720ad9c
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0```

**Comment by 50Wliu** [comment] 2016-05-23 23:08
Ok, thanks @drewmnoel.  If you think that Atom is still at fault by not opening anything, please create a new issue!

**Closed by 50Wliu** 2016-05-23 23:08 UTC
Labels: linux, needs-reproduction
