### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.35.1\ sun ri...

### ISSUE THREAD

**Issue by HaydenPaulWoodger** [atom/atom#19043] opened 2019-03-25 03:29 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Hayden\AppData\Local\atom\app-1.35.1\ sun rising.jpg'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\Hayden\AppData\Local\atom\app-1.35.1\ sun rising.jpg'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:912504)
    at TreeView.t.exports.TreeView.onDrop (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:918258)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:14:893098)
```

### Commands

```
     -1:56.2.0 core:paste (input.hidden-input)
  2x -1:42.7.0 tree-view:remove (span.name.icon.icon-file-directory)
     -1:18.8.0 core:save (div.tool-panel.tree-view)
     -0:41.4.0 tree-view:cut (span.name.icon.icon-file-text)
     -0:37.2.0 tree-view:paste (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
platformio-ide-terminal 2.9.1 
script 3.18.1 
```

**Comment by rsese** [comment] 2019-03-25 20:34
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-03-25 20:34 UTC
