### ISSUE TITLE
Build Error - Loading index.js tasks / Module did not self register

### ISSUE THREAD

**Issue by alefragnani** [atom/atom#7745] opened 2015-07-06 23:53 UTC
Hi,

I'm trying to build Atom, following the [instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md), but while running `script/build` it fail with the following error:

    Node: v1.3.0
    npm: v2.5.1
    Python: v2.7.9
    Installing build modules...
    Installing apm...
    Installing modules done
    Deduping modules done
    Loading "index.js" tasks...ERROR
    >> Error: Module did not self-register.
    Running "download-atom-shell" task
    Running "download-atom-shell-chromedriver" task
    Running "build" task
    Running "coffee:glob_to_multiple" (coffee) task
    >> 336 files created.
    Running "prebuild-less:src" (prebuild-less) task
    Running "cson:glob_to_multiple" (cson) task
    >> 170 files compiled to JSON.
    Running "peg:glob_to_multiple" (peg) task
    Running "generate-license:save" (generate-license) task
    Running "generate-module-cache" task
    Running "compile-packages-slug" task
    Running "set-exe-icon" task
    Running "set-version" task
    Running "generate-asar" task
    Running "install" task
    Aborted due to warnings.

The `verbose` says:

    [1mRegistering "grunt-atom-shell-installer" local Npm module tasks.[22m
    Reading C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell-installer\package.json...[32mOK[39m
    Parsing C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell-installer\package.json...[32mOK[39m
    Loading "index.js" tasks...[31mERROR[39m
    [31m>> [39mError: Module did not self-register.[31m
    >> [39m  at Error (native)[31m
    >> [39m  at Module.load (module.js:339:32)[31m
    >> [39m  at Function.Module._load (module.js:294:12)[31m
    >> [39m  at Module.require (module.js:349:17)[31m
    >> [39m  at require (module.js:368:17)[31m
    >> [39m  at bindings (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell-installer\node_modules\asar\node_modules\chromium-pickle\node_modules\bindings\bindings.js:76:44)[31m
    >> [39m  at Object.<anonymous> (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell-installer\node_modules\asar\node_modules\chromium-pickle\lib\main.js:1:99)[31m
    >> [39m  at Module._compile (module.js:444:26)[31m
    >> [39m  at Object.Module._extensions..js (module.js:462:10)[31m
    >> [39m  at Module.load (module.js:339:32)[31m
    >> [39m  at Function.Module._load (module.js:294:12)[31m
    >> [39m  at Module.require (module.js:349:17)[31m
    >> [39m  at require (module.js:368:17)[31m
    >> [39m  at Object.<anonymous> (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell-installer\node_modules\asar\lib\disk.js:3:14)[31m
    >> [39m  at Module._compile (module.js:444:26)[31m
    >> [39m  at Object.Module._extensions..js (module.js:462:10)[31m
    >> [39m  at Module.load (module.js:339:32)[31m
    >> [39m  at Function.Module._load (module.js:294:12)[31m
    >> [39m  at Module.require (module.js:349:17)[31m
    >> [39m  at require (module.js:368:17)[31m
    >> [39m  at Object.<anonymous> (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell-installer\node_modules\asar\lib\asar.js:9:12)[31m
    >> [39m  at Module._compile (module.js:444:26)[31m
    >> [39m  at Object.Module._extensions..js (module.js:462:10)[31m
    >> [39m  at Module.load (module.js:339:32)[31m
    >> [39m  at Function.Module._load (module.js:294:12)[31m
    >> [39m  at Module.require (module.js:349:17)[31m
    >> [39m  at require (module.js:368:17)[31m
    >> [39m  at Object.<anonymous> (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell-installer\tasks\index.js:8:10)[31m
    >> [39m  at Object.<anonymous> (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell-installer\tasks\index.js:135:4)[31m
    >> [39m  at Module._compile (module.js:444:26)[31m
    >> [39m  at Object.Module._extensions..js (module.js:462:10)[31m
    >> [39m  at Module.load (module.js:339:32)[31m
    >> [39m  at Function.Module._load (module.js:294:12)[31m
    >> [39m  at Module.require (module.js:349:17)[31m
    >> [39m  at require (module.js:368:17)[31m
    >> [39m  at loadTask (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt\lib\grunt\task.js:323:10)[31m
    >> [39m  at C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt\lib\grunt\task.js:361:7[31m
    >> [39m  at Array.forEach (native)[31m
    >> [39m  at loadTasks (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt\lib\grunt\task.js:360:11)[31m
    >> [39m  at Task.task.loadNpmTasks (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt\lib\grunt\task.js:408:5)[31m
    >> [39m  at Object.module.exports (C:\AtomBuilded\1.0.0\atom\build\Gruntfile.coffee:26:9)[31m
    >> [39m  at loadTask (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt\lib\grunt\task.js:325:10)[31m
    >> [39m  at Task.task.init (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt\lib\grunt\task.js:437:5)[31m
    >> [39m  at Object.grunt.tasks (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt\lib\grunt.js:120:8)[31m
    >> [39m  at Object.module.exports [as cli] (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt\lib\grunt\cli.js:38:9)[31m
    >> [39m  at Object.<anonymous> (C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-cli\bin\grunt:45:20)[31m
    >> [39m  at Module._compile (module.js:444:26)[31m
    >> [39m  at Object.Module._extensions..js (module.js:462:10)[31m
    >> [39m  at Module.load (module.js:339:32)[31m
    >> [39m  at Function.Module._load (module.js:294:12)[31m
    >> [39m  at Function.Module.runMain (module.js:485:10)[31m
    >> [39m  at startup (node.js:111:16)[31m
    >> [39m  at node.js:799:3

Settings:
* Windows 10 Insider
* io.js version 1.3.0
* Python 2.7.0

Thanks in advance

**Comment by ankitaggarwal011** [comment] 2015-07-07 10:56
Have you tried to remove the node_modules folder, reinstall the node packages and try again?
Also, take a look at this http://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register.

**Comment by alefragnani** [comment] 2015-07-09 03:36
Hi @ankitaggarwal011,

I tried, with no success. Even running cmd as administrator do run `npm update`. 
I also tried with io.js 2.3.3 (previously uninstalling and removing the older folder), but the problem remains exactly the same. Even running the `build` command as administrator.

**Comment by ankitaggarwal011** [comment] 2015-07-09 13:12
Hi @alefragnani , I have been looking into the issue, all the people who had previously ran into it in other projects suggests that It could possibly be because of the conflicting node.js or io.js versions. 

> The version of node.js used at compile time, that is when npm install is run, needs to be the same as the version of node.js used at runtime. Perhaps you've recently upgraded Node.js version? If so, try running npm rebuild to recompile against that new version.

I was a bit busy and I haven't built atom on my system yet, I will try that soon as well.
In the meantime, maybe you could uninstall remove all this and do a fresh install of node.js supported version and build atom again.

**Comment by alefragnani** [comment] 2015-07-10 03:08
Hi @ankitaggarwal011,

I replaced **io.js** for **node.js** (full installation) and another problem occured. Even running `npm rebuild`, the problem remained.

The error is still in `index.js`, but message and the stack, differs:

    Loading "index.js" tasks...ERROR
    >> Error: The specified module could not be found. 
    >> C:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell- installer\node_modules\asar\node_modules\chromium-pickle\build\Release\pickle.node

The `verbose` is:

	Loading "index.js" tasks...[31mERROR[39m
	[31m>> [39mError: The specified module could not be found.
	[31m
	>> [39mC:\AtomBuilded\1.0.0\atom\build\node_modules\grunt-atom-shell-installer\node_modules\asar\node_modules\chromium-pickle\build\Release\pickle.node[31m
	>> [39m  at Error (native)[31m
	>> [39m  at Module.load (module.js:355:32)[31m

Thanks in advance

**Comment by ankitaggarwal011** [comment] 2015-07-10 06:12
This is better than before. Now, this just seems to be appearing because of a few missing node packages. Install all the packages and dependencies. Run ```npm install```. Is this command producing any errors?

**Comment by alefragnani** [comment] 2015-07-11 18:09
I decided to clone latest Atom (1.0.2) and run `npm instal`, `npm rebuild` a couple of times, restarted windows :smile: and tried to build again. It was appearing that this time it would work, because it installed a bunch of atom packages, but then it raised this error:

    Deduping modules done  
    module.js:338
    throw err;
          ^
    Error: Cannot find module 'grunt-legacy-util'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\AtomBuilded\1.0.2\atom\build\node_modules\grunt\lib\grunt.js:26:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\AtomBuilded\1.0.2\atom\build\node_modules\grunt-cli\bin\grunt:45:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

In fact, at the start of the building process, instead of errors, some *deprecation messages* appeared. I don't know if this has some influence on the error itself.

    Installing apm...
    child_process: customFds option is deprecated, use stdio instead.
    child_process: customFds option is deprecated, use stdio instead.
    child_process: customFds option is deprecated, use stdio instead.
    Installing modules done
    Installing atom-dark-syntax@0.27.0 done

I tried to install `grunt-legacy-util` by myself (`npm install grunt-legacy-util`). It installed, but when I tried to build, it uninstalled and then after that, it says *cannot find module*?!?! :confused: 
  
    Installing apm...
    Removing grunt-legacy-util done
    Installing modules done
    Deduping modules done 
    module.js:338
        throw err;
              ^   
    Error: Cannot find module 'grunt-legacy-util'
      at Function.Module._resolveFilename (module.js:336:15)

Thanks for your help.

**Comment by KINFOO** [comment] 2015-07-30 10:25
Hi,

I have same error:

    Deduping modules ✓
    Loading "index.js" tasks...ERROR
    >> Error: Module did not self-register.

Did you manage to fix it?

**Comment by KINFOO** [comment] 2015-07-30 10:30
Long version:

```sh
git co v1.0.2  
La position précédente de HEAD était 17d6d97... Merge pull request #8119 from atom/ns-ctrl-up-down
HEAD est maintenant sur 9432598... :arrow_up: tree-view@0.177
$ script/build 
Node: v0.12.7
npm: v2.5.1
Installing build modules...
Installing apm...
Removing about ✓
Installing modules ✓
Installing one-dark-ui@1.0.0 ✓
Installing one-dark-syntax@1.0.0 ✓
Installing one-light-syntax@1.0.0 ✓
Installing one-light-ui@1.0.0 ✓
Installing autocomplete-atom-api@0.9.0 ✓
Installing autocomplete-css@0.8.0 ✓
Installing autocomplete-plus@2.17.4 ✓
Installing autocomplete-snippets@1.7.0 ✓
Installing deprecation-cop@0.53.0 ✓
Installing exception-reporting@0.35.0 ✓
Installing find-and-replace@0.174.2 ✓
Installing incompatible-packages@0.24.0 ✓
Installing settings-view@0.211.0 ✓
Installing tree-view@0.177.0 ✓
Installing language-css@0.32.0 ✓
Installing language-gfm@0.78.0 ✓
Installing language-go@0.30.0 ✓
Installing language-javascript@0.80.0 ✓
Installing language-less@0.28.0 ✓
Installing language-python@0.37.0 ✓
Installing language-ruby@0.56.0 ✓
Installing language-sass@0.39.0 ✓
Deduping modules ✓
Loading "index.js" tasks...ERROR
>> Error: Module did not self-register.

Running "download-atom-shell" task

Running "download-atom-shell-chromedriver" task

Running "build" task

Running "coffee:glob_to_multiple" (coffee) task
>> 342 files created.

Running "prebuild-less:src" (prebuild-less) task

Running "cson:glob_to_multiple" (cson) task
>> 170 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task

Running "set-version" task

Running "generate-asar" task
Done, without errors.
```

More

```sh
$ python -V
Python 2.7.9
$ uname -a
Linux hendrix 3.19.0-25-generic #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by KINFOO** [comment] 2015-07-30 12:25
Well, `--verbose` stack says the same:

```sh
$ script/build --verbose
Node: v0.12.7
npm: v2.5.1
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓                                                                                                                                                                                                
Initializing                                                                                                                                               ...
Registering "grunt-atom-shell-installer" local Npm module tasks.
Reading /home/kevin/Development/atom/build/node_modules/grunt-atom-shell-installer/package.json...OK
Parsing /home/kevin/Development/atom/build/node_modules/grunt-atom-shell-installer/package.json...OK
Loading "index.js" tasks...ERROR
>> Error: Module did not self-register.
>>   at Error (native)
>>   at Module.load (module.js:355:32)
>>   at Function.Module._load (module.js:310:12)
>>   at Module.require (module.js:365:17)
>>   at require (module.js:384:17)
>>   at bindings (/home/kevin/Development/atom/build/node_modules/grunt-atom-shell-installer/node_modules/asar/node_modules/chromium-pickle/node_modules/bindings/bindings.js:76:44)
>>   at Object.<anonymous> (/home/kevin/Development/atom/build/node_modules/grunt-atom-shell-installer/node_modules/asar/node_modules/chromium-pickle/lib/main.js:1:99)
>>   at Module._compile (module.js:460:26)
>>   at Object.Module._extensions..js (module.js:478:10)
>>   at Module.load (module.js:355:32)
>>   at Function.Module._load (module.js:310:12)
>>   at Module.require (module.js:365:17)
>>   at require (module.js:384:17)
>>   at Object.<anonymous> (/home/kevin/Development/atom/build/node_modules/grunt-atom-shell-installer/node_modules/asar/lib/disk.js:3:14)
>>   at Module._compile (module.js:460:26)
>>   at Object.Module._extensions..js (module.js:478:10)
>>   at Module.load (module.js:355:32)
>>   at Function.Module._load (module.js:310:12)
>>   at Module.require (module.js:365:17)
>>   at require (module.js:384:17)
>>   at Object.<anonymous> (/home/kevin/Development/atom/build/node_modules/grunt-atom-shell-installer/node_modules/asar/lib/asar.js:9:12)
>>   at Module._compile (module.js:460:26)
>>   at Object.Module._extensions..js (module.js:478:10)
>>   at Module.load (module.js:355:32)
>>   at Function.Module._load (module.js:310:12)
>>   at Module.require (module.js:365:17)
>>   at require (module.js:384:17)
>>   at Object.<anonymous> (/home/kevin/Development/atom/build/node_modules/grunt-atom-shell-installer/tasks/index.js:8:10)
>>   at Object.<anonymous> (/home/kevin/Development/atom/build/node_modules/grunt-atom-shell-installer/tasks/index.js:135:4)
>>   at Module._compile (module.js:460:26)
>>   at Object.Module._extensions..js (module.js:478:10)
>>   at Module.load (module.js:355:32)
>>   at Function.Module._load (module.js:310:12)
>>   at Module.require (module.js:365:17)
>>   at require (module.js:384:17)
>>   at loadTask (/home/kevin/Development/atom/build/node_modules/grunt/lib/grunt/task.js:323:10)
>>   at /home/kevin/Development/atom/build/node_modules/grunt/lib/grunt/task.js:361:7
>>   at Array.forEach (native)
>>   at loadTasks (/home/kevin/Development/atom/build/node_modules/grunt/lib/grunt/task.js:360:11)
>>   at Task.task.loadNpmTasks (/home/kevin/Development/atom/build/node_modules/grunt/lib/grunt/task.js:408:5)
>>   at Object.module.exports (/home/kevin/Development/atom/build/Gruntfile.coffee:26:9)
>>   at loadTask (/home/kevin/Development/atom/build/node_modules/grunt/lib/grunt/task.js:325:10)
>>   at Task.task.init (/home/kevin/Development/atom/build/node_modules/grunt/lib/grunt/task.js:437:5)
>>   at Object.grunt.tasks (/home/kevin/Development/atom/build/node_modules/grunt/lib/grunt.js:120:8)
>>   at Object.module.exports [as cli] (/home/kevin/Development/atom/build/node_modules/grunt/lib/grunt/cli.js:38:9)
>>   at Object.<anonymous> (/home/kevin/Development/atom/build/node_modules/grunt-cli/bin/grunt:45:20)
>>   at Module._compile (module.js:460:26)
>>   at Object.Module._extensions..js (module.js:478:10)
>>   at Module.load (module.js:355:32)
>>   at Function.Module._load (module.js:310:12)
>>   at Function.Module.runMain (module.js:501:10)
>>   at startup (node.js:129:16)
>>   at node.js:814:3
```

**Comment by KINFOO** [comment] 2015-07-30 13:51
@alefragnani Did you try the following?

```sh
$ git co v1.0.3
HEAD est maintenant sur 17d6d97... Merge pull request #8119 from atom/ns-ctrl-up-down
$ script/clean 
$ script/build
```

Kevin

**Comment by kevinsawicki** [comment] 2015-07-31 17:03
I believe this is a duplicate of #5661 and fixed by https://github.com/atom/atom/commit/bd5403fe074ebd3f98bbf697edf3c1160e8a329e

**Closed by kevinsawicki** 2015-07-31 17:03 UTC
Labels: build-error, windows
