### ISSUE TITLE
Atom 1.17.0 with tree control hidden has bar cover covering search.

### ISSUE THREAD

**Issue by garretwilson** [atom/atom#14594] opened 2017-05-23 18:07 UTC
I'm on Windows 10 Pro 64-bit running Atom 1.17.0 ia32. When I hit `Ctrl+F` to bring up search, everything looks normal. But when I it `Ctrl+\` to hide the left pane with the tree control, a thick bar appears on the bottom, covering part of the search fields.

The bar has a gray portion on the left and a black portion on the right, divided at exactly where the right side of the horizontal scrollbar would appear for the left tree pane, were it visible. (My file tree is wider than the pane, so when it is visible there is a horizontal scrollbar.)

Sorry, I don't have time to go through and do in-depth debugging, screen shots, logs, etc. But I thought I would at least inform you---that's better than not knowing. Good luck.

**Comment by 50Wliu** [comment] 2017-05-23 18:10
Unable to reproduce on Windows 10, Atom 1.19.0-dev-17dace898 x64.
@garretwilson is this reproducible in safe mode?

**Comment by garretwilson** [comment] 2017-05-23 18:22
Sorry, I haven't tried. I'm in the middle of catching up with a lot of work from last week.

As a developer I realize your need for more information. As developer I'm overloaded. hehe I'll do my best to circle back in a week or two and provide more info if you can't reproduce it.

Oh, interesting... so this occurred editing an HTML file. I switched to a JavaScript file, brought up the linter, and made an error to see if that had anything to do with it. Then I closed the linter window at the bottom, tried the find dialog again, and noticed that this didn't happen anymore.

So I went back to the HTML tab and now I can't reproduce it anymore. Weird. I know I saw it --- even after an Atom restart. But either opening the JavaScript file and/or bringing up the linter did something.

It looks like even I can't provide further information, now. You might be on the lookout for it, now that someone has seen it.

**Comment by garretwilson** [comment] 2017-05-23 18:39
Thanks for replying so quickly. Sorry I can't provide more information --- or even reproduce it now.

**Comment by garretwilson** [comment] 2017-05-24 18:09
Uh, oh. It's happening again. This time the gray/black bar is only on the right editor pane; it doesn't cover the "project" panel with the file tree.

When I bring up search (e.g. `Ctrl+F`), it appears, covering some of the fields.

I had errors in the JavaScript document (I'm using `linter`, `linter-ui-default`, and `linter-eslint`), but I removed the errors and this bar still appears.

With this new "docking" mechanism in Atom, I can click the half-circle at the bottom and bring up the "Linter" tab. Now the bars do not appear when I bring up search. And when I click the half-circle again to hide the "Linter" tab, the bars still do not appear when I show and hide the search panel. Now I can no longer reproduce the error.

With this limited information, I would guess that it is a bug in the new docking system, and how it interacts with the linter (or a bug in the linter and how it interacts with the new docking system).

**Comment by garretwilson** [comment] 2017-08-18 15:49
I'm sorry to say that this is really getting in the way of functionality. I can't do a search/replace, because this gray and white bar covers part of the search/replace box. (It used to be black and white. Now it seems to be gray and white.) I have to type the replacement text "blind" because I can't see what I'm typing.

I'm attaching a screen snippet.

![atom-gray-block](https://user-images.githubusercontent.com/627125/29466548-1a5b90cc-83f2-11e7-959f-d130d3273126.png)

**Comment by garretwilson** [comment] 2017-08-18 15:53
It probably has to do with the bottom pull-up tab for the bottom (currently containing the linter tool). When I put my mouse over the up-arrow for the bottom tab, the tab covers exactly the space covered by the gray/white bar in the photo above.

When I show and then hide again the bottom linter tab, the problem no longer occurs during the session --- somehow that resets it.

So it's something to do with this new tab/docking mechanism in Atom.

**Comment by 50Wliu** [comment] 2017-08-18 19:49
Hmm, maybe it's related to #14915?  #14998 contains a CSS solution if you want to try it out.

**Comment by Arcanemagus** [comment] 2017-08-21 21:31
@50Wliu Yep, that looks exactly like #14915, just with different colors (as those are based on the theme).

**Comment by Ben3eeE** [comment] 2017-08-29 14:45
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14915.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-29 14:45 UTC
Labels: more-information-needed, needs-reproduction
