### ISSUE TITLE
Fails in Syntax Highlight - PHP / MySQL

### ISSUE THREAD

**Issue by dertin** [atom/atom#17305] opened 2018-05-11 18:22 UTC
### Description

Atom does not understand that within $foo there is a string and that it ends with "("
is validating as if it were a MySQL query?
Until you find a ")", it will not stop marking the middle code in green.

### Steps to Reproduce

```
<?php

$foo = ' AND (';
echo $foo;
echo '1234';
echo 'abcd';
echo ')';
echo 'Hello Word';
```

### Versions

Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by rsese** [comment] 2018-05-11 20:17
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/language-php/issues/321 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-11 20:17 UTC
