### ISSUE TITLE
"sudo atom" does not work, shuts down system Ubuntu 16

### ISSUE THREAD

**Issue by nizz0k** [atom/atom#13222] opened 2016-11-14 14:37 UTC
I can run atom from the application launcher, but when I need to modify a file with root privileges then it does not respond, and the my system shuts itself down from overheating. I am running Atom version 1.12.1 on Ubuntu 16.04. Installed via apt

**Comment by Ben3eeE** [comment] 2016-11-14 14:40
This sounds like a duplicate of https://github.com/atom/atom/issues/13084. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-11-14 14:40 UTC
