### ISSUE TITLE
Release notes are stuck in atom since the release of the beta channel

### ISSUE THREAD

**Issue by fibric** [atom/atom#10123] opened 2015-12-19 10:59 UTC
Hi,

I am wondering if it's just me or if nobody cares.

Since I've downloaded Atom beta additionally to Atom stable, the release notes in Atom (stable and beta) are stuck at v1.1.0.

Upgrading to newer version still works, but when I click to squirrel icon in the bottom right corner, I always see the same old release notes.

![image](https://cloud.githubusercontent.com/assets/623932/11912635/ed29d6ca-a646-11e5-8eb4-edef13fd8ed4.png)
On the picture, you'll see the release notes in the browser, the releases in Atom stable and the release notes in Atom beta.

**Comment by mnquintana** [comment] 2015-12-19 13:39
Thanks for the report! This is a duplicate of https://github.com/atom/release-notes/39 - please subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) for a guide on submitting bug reports (including searching for duplicates first).

**Closed by mnquintana** 2015-12-19 13:39 UTC

**Comment by snocorp** [comment] 2015-12-21 15:47
Better link in case someone else stumbles upon this: https://github.com/atom/release-notes/issues/39
