### ISSUE TITLE
Thanks for the update I didn't want

### ISSUE THREAD

**Issue by skychef** [atom/atom#20349] opened 2020-01-23 18:43 UTC
I turned off "**Automatically Update**" in 2018 but you thought no one would notice if you force updated the application anyway this week. In the year 2020.

Since I disabled the automatic update setting, **no updates have occurred automatically**. Today, I find that the application has been updated. _Without consent_.

Because of some terrible changes since the Microsoft acquisition, Atom is utterly useless and a non-trivial amount of addon packages have been recklessly broken.

Many addon maintainers don't care, won't fix the issues and have moved on away from Atom because they cannot deal with the constant recklessness of the breaking changes. And that's before we even get to things like disrespecting user's settings by doing things like forced updating.

Thanks for the update.. I actually turned updates off, so that I wouldn't end up with a broken copy of Atom which I would need to revert then containerise or uninstall.

I wish the project all the luck in the world in it's fight for relevancy. It clearly needs all it can get if stooping as low as forced updates has become the way in which the project attempts to earn user's trust.

When you **force** things made with :heart: onto people, especially when they do not want them, it is called **abuse**.

![1](https://user-images.githubusercontent.com/186629/73010947-4ae05680-3e0b-11ea-90ee-9f3106fa828b.png)

![2](https://user-images.githubusercontent.com/186629/73010950-4caa1a00-3e0b-11ea-894d-09c279155374.png)

![3](https://user-images.githubusercontent.com/186629/73010955-4e73dd80-3e0b-11ea-9c08-cf0d3b6a989b.png)

There is no way this was a bug. It's forced, intended and abusive behaviour, plain and simple. I highly recommend that you stop doing this immediately. Your motives are likely telemetry and that therefore makes Atom: malware.

**Comment by lee-dohm** [comment] 2020-01-23 18:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20321. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2020-01-23 18:56 UTC
