### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of null

### ISSUE THREAD

**Issue by Mamoru1234** [atom/atom#16003] opened 2017-10-26 16:08 UTC
[Enter steps to reproduce:]

1. Open JS file.
2. Cursor at beginning of empty line outside of any block.
3. Try to fold/unfold block

Expected behavior:
It should not have error. Because there is no block to change

**Atom**: 1.22.0-beta1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.10
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of null

```
At /usr/share/atom-beta/resources/app/node_modules/text-buffer/lib/range.js:33

TypeError: Cannot read property 'start' of null
    at Function.module.exports.Range.fromObject (/usr/share/atom-beta/resources/app/node_modules/text-buffer/lib/range.js:33:37)
    at DisplayLayer.foldBufferRange (/usr/share/atom-beta/resources/app/node_modules/text-buffer/lib/display-layer.js:206:31)
    at TextEditor.module.exports.TextEditor.foldCurrentRow (/usr/share/atom-beta/resources/app/src/text-editor.js:3135:38)
    at TextEditor.editor:fold-current-row (/usr/share/atom-beta/resources/app/src/register-default-commands.js:549:27)
    at HTMLElement.newCommandListeners.(anonymous function) (/usr/share/atom-beta/resources/app/src/register-default-commands.js:658:38)
    at CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom-beta/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:17.1.0 editor:fold-current-row (input.hidden-input)
     -0:16.3.0 intentions:highlight (input.hidden-input)
     -0:16 editor:fold-current-row (input.hidden-input)
  2x -0:15.2.0 core:move-up (input.hidden-input)
     -0:07.2.0 intentions:highlight (input.hidden-input)
     -0:06.6.0 editor:fold-current-row (input.hidden-input)
     -0:05.6.0 intentions:highlight (input.hidden-input)
     -0:05.2.0 editor:unfold-current-row (input.hidden-input)
     -0:04.6.0 intentions:highlight (input.hidden-input)
     -0:04.4.0 editor:fold-current-row (input.hidden-input)
     -0:03.8.0 intentions:highlight (input.hidden-input)
     -0:03.6.0 editor:unfold-current-row (input.hidden-input)
     -0:03.0 intentions:highlight (input.hidden-input)
  3x -0:02.6.0 core:move-down (input.hidden-input)
     -0:02.1.0 intentions:highlight (input.hidden-input)
     -0:01.5.0 editor:fold-current-row (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.7.3 
block-comment-plus 0.5.1 
busy-signal 1.4.3 
file-icons 2.1.13 
git-blame 1.3.1 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.11.1 
language-babel 2.76.1 
language-freemarker 0.2.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
local-history 4.3.1 
split-diff 1.5.1 
sync-settings 0.8.3 
zentabs 0.8.8 
```

**Comment by Ben3eeE** [comment] 2017-10-26 16:14
@maxbrunsfeld This looks like a duplicate of https://github.com/atom/atom/issues/15923. Should this be hotfixed to beta?

**Comment by maxbrunsfeld** [comment] 2017-10-26 16:29
Yes! Thanks @Ben3eeE; this will go into the next beta hotfix.

**Comment by maxbrunsfeld** [comment] 2017-10-26 16:29
Fixed via https://github.com/atom/atom/pull/15974

**Closed by maxbrunsfeld** 2017-10-26 16:29 UTC
