### ISSUE TITLE
Key bindings use default keyboard layout rather than the current one

### ISSUE THREAD

**Issue by cifkao** [atom/atom#13340] opened 2016-11-27 19:08 UTC
### Description

After upgrading from 1.8.0 to 1.12.5, Atom uses the default keyboard layout rather than the current one when resolving key bindings. If this non-standard behaviour is intended, there should be a switch in the settings that disables it.

### Steps to Reproduce

1. Change your default keyboard layout to a QWERTZ layout (e.g. Czech).
2. Change your active keyboard layout to English (QWERTY).
2. Open the Key Binding Resolver.
3. Press <kbd>Ctrl</kbd>-<kbd>Z</kbd>.

**Expected behavior:** _core:undo_ is executed.

**Actual behavior:** _core:redo_ is executed.

**Comment by Ben3eeE** [comment] 2016-11-27 19:30
In Atom 1.12.5 there is an issue where the keyboard layout does not update correctly if you change layouts while Atom is running. This has been fixed on master and will go out in the next hotfix release.

**Closed by Ben3eeE** 2016-11-27 19:30 UTC

**Comment by cifkao** [comment] 2016-11-27 19:37
@Ben3eeE I can reproduce the same behaviour by changing the keyboard layout settings when Atom is _not_ running. Are you sure this is the same issue?

**Comment by Ben3eeE** [comment] 2016-11-27 20:10
Actually just realized that I can't be sure since your issue is missing information. What operating system are you using?

**Comment by cifkao** [comment] 2016-11-27 20:12
Linux Mint 17.1 Cinnamon

**Comment by Ben3eeE** [comment] 2016-11-27 20:13
Do you see the same behavior in the keybinding resolver when using another modifier than <kbd>Ctrl</kbd>?

**Comment by cifkao** [comment] 2016-11-27 20:24
No. If I add a binding for <kbd>Alt</kbd>-<kbd>Z</kbd> or just <kbd>Z</kbd>, it works fine.

**Comment by Ben3eeE** [comment] 2016-11-27 20:35
@cifkao Your issue is a duplicate of https://github.com/atom/atom/issues/13170. This was previously only known to happen on colemak but given your added information of the same behavior with qwerty and qwertz I am assuming it happens with any layout. Thank you for your report 🙇
