### ISSUE TITLE
How can i not copy the simbol "$" with double click?

### ISSUE THREAD

**Issue by Encr1pt3d** [atom/atom#14314] opened 2017-04-27 17:31 UTC
Hi,

when I used sublime and I doubled clic in a register in PHP the simbol "$" wasn't copied, how can I do that?

Thank you so much

**Comment by rsese** [comment] 2017-04-27 17:43
Hi @Encr1pt3d - the duplicate issue is mentioned below with a potential workaround described in https://github.com/atom/language-php/issues/92#issuecomment-263557774.

For future issues, please completely fill out the issue template and if you have general questions about Atom, our message board is a great place to have those conversations:

https://discuss.atom.io/

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-php/issues/92. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-27 17:43 UTC
