### ISSUE TITLE
Make holding option while dragging create multiple cursors when

### ISSUE THREAD

**Issue by Keno** [atom/atom#7852] opened 2015-07-12 00:51 UTC
In Sublime, holding Option (on Mac) while dragging the cursor, creates multiple cursors in a line. I did a quick screen capture of this behavior here: https://youtu.be/71EveOv6tf4. It would be great if the same worked in atom.

**Comment by mnquintana** [comment] 2015-07-12 04:50
Thanks for the suggestion! This is a duplicate of https://github.com/atom/atom/issues/2306 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-12 04:50 UTC
Labels: enhancement

**Comment by Keno** [comment] 2015-07-12 04:52
Ah, sorry, I looked around, but couldn't find it.
