### ISSUE TITLE
Cursor got stuck when select->paste

### ISSUE THREAD

**Issue by ethancfchen** [atom/atom#15404] opened 2017-08-22 05:44 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I selected some characters and try to replace by typing or paste new text, the cursor is not showing as expected and sometimes it replace the text after the cursor.

### Steps to Reproduce

1. Type some random words.
2. Type some random words on next line.
3. Copy the word from first line.
4. Select some words on second line.
5. Paste words from clipbook.

**Expected behavior:** [What you expect to happen]

![8 -22-2017 13-41-48](https://user-images.githubusercontent.com/5051791/29550308-b038e86a-873f-11e7-9b8c-c6e44cd50ae6.gif)

**Actual behavior:** [What actually happens]

![8 -22-2017 13-26-27](https://user-images.githubusercontent.com/5051791/29550130-b43ec7c8-873e-11e7-95ba-b0ddb474aa33.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?]

Sometimes.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

OS: macOS Sierra 10.12.6

```bash
atom --version

Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```bash
apm --version

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.6.4
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ethancfchen** [comment] 2017-08-22 05:48
I'm not sure it's same problem or should I create another issue, but it has similar situation when I selected and typed.

Here it is:

![8 -22-2017 13-27-56](https://user-images.githubusercontent.com/5051791/29550407-26b8ec92-8740-11e7-8ecc-a47b1800a758.gif)
I just `[select]` and typed `123456789` but it only shows `456789`.

**Comment by Ben3eeE** [comment] 2017-08-22 06:14
Thank you for the report :bowing_man: 

I believe both of these are because you are selecting with the mouse and still holding down the mouse button while typing or copying the new text. Can you please verify if this is the case?

We have a duplicate issue if you are holding down the mouse button. /cc: https://github.com/atom/atom/issues/15217

**Comment by ethancfchen** [comment] 2017-08-22 06:18
No, I'm not holding my mouse button, because I'm using trackpad actually.
Maybe the events are different between mouse and trackpad?

**Comment by Ben3eeE** [comment] 2017-08-22 06:36
Sorry my repro is to hold the mouse button because I don't use a trackpad. I should have been more clear. The user in that issue is also on macOS with a trackpad. He had some setting that caused this for him because of event delay /cc: https://github.com/atom/atom/issues/15217#issuecomment-321528582

Seems there is some difference with a trackpad because of event delays.

**Comment by ethancfchen** [comment] 2017-08-22 06:47
After reading the comment on #15217, I'm pretty sure it's the same issue on me, thanks.
I think it's a bug obviously because it's not happening when I use previous versions such as 1.18.x.

**Comment by Ben3eeE** [comment] 2017-08-22 07:08
@ethancfchen Thank you for verifying this :bowing_man: I will bring it up with the team. Can you please comment in the issue with the gifs you posted in this issue?

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15217. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-22 07:08 UTC
Labels: duplicate
