### ISSUE TITLE
Uncaught Error: EACCES, open '/home/shehryar/.atom/compile-cache/cson/5af7724b023a6274b520f79f04fb798a67319ca7.json'

### ISSUE THREAD

**Issue by sshehryar** [atom/atom#4949] opened 2015-01-09 13:11 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: linux 3.13.0-30-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES, open '/home/shehryar/.atom/compile-cache/cson/5af7724b023a6274b520f79f04fb798a67319ca7.json'

```
At fs.js:75

Error: EACCES, open '/home/shehryar/.atom/compile-cache/cson/5af7724b023a6274b520f79f04fb798a67319ca7.json'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by benogle** [comment] 2015-01-09 18:43
Did you install with sudo?

cc @kevinsawicki

**Comment by kevinsawicki** [comment] 2015-01-13 17:42
I believe this is a duplicate of https://github.com/atom/atom/issues/4676

**Closed by kevinsawicki** 2015-01-13 17:42 UTC
