### ISSUE TITLE
CTRL + Click to Open File

### ISSUE THREAD

**Issue by tuhinkarmakar** [atom/atom#8136] opened 2015-07-29 09:56 UTC
This was the second part of the issue #7938. I split it into 2 issues, as suggested by @mnquintana and @izuzak.

#### CTRL + Click to open file in editor

Holding down CTRL and left clicking a file in the current editor tab, opens the file in a new tab (or, switches to the tab).

![ctrl-click](https://cloud.githubusercontent.com/assets/11135104/8740156/050d81b4-2c63-11e5-9a5d-78ff63c4c772.gif)

**Comment by izuzak** [comment] 2015-08-18 20:12
@tuhinkarmakar Thanks for opening this. I think this is actually a duplicate of https://github.com/atom/atom/issues/1647 -- can you add your comment there?

**Closed by izuzak** 2015-08-18 20:12 UTC
Labels: package-idea
