### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('T...

### ISSUE THREAD

**Issue by gsportelli** [atom/atom#19040] opened 2019-03-24 14:23 UTC
[Enter steps to reproduce:]

1. Open Atom
2. Create new tempfile

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('Th
1') contains HTML space characters, which are not valid in tokens.

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('Th
1') contains HTML space characters, which are not valid in tokens.
    at SuggestionListElement.addClassToElement (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1970197)
    at SuggestionListElement.renderItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1971489)
    at SuggestionListElement.renderItems (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1967854)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:326599)
```

### Commands

```
     -0:13.1.0 tempfile:create (input.hidden-input)
     -0:10.8.0 core:confirm (input.hidden-input)
     -0:09.9.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:09.8.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:09.6.0 core:close (input.hidden-input)
     -0:08.9.0 core:paste (input.hidden-input)
  2x -0:05.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:04.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
aligner-javascript 1.3.0 
aligner-vhdl 0.1.0 
atom-clock 0.1.16 
autoclose-html 0.23.0 
autocomplete-clang 0.11.5 
autocomplete-python 1.14.0 
build 0.70.0 
busy-signal 2.0.1 
color-picker 2.3.0 
duplicate-line-or-selection 0.9.0 
file-icons 2.1.31 
git-control 0.9.0 
git-diff-details 1.4.0 
git-history 3.3.0 
git-plus 8.6.2 
git-time-machine 2.1.0 
highlight-line 0.12.0 
highlight-selected 0.15.0 
Hydrogen 2.8.0 
intentions 1.1.5 
kite 0.153.0 
language-ini 1.20.0 
language-markdown 0.29.0 
language-pug 0.0.22 
language-vhdl 0.7.2 
linter 2.3.0 
linter-gcc 0.7.1 
linter-markdown 5.2.6 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
markdown-preview-plus 3.7.1 
markdown-writer 2.11.5 
open-recent 5.0.0 
pdf-view 0.71.0 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
script 3.18.1 
sequential-number 0.5.0 
simple-align 0.2.0 
sort-lines 0.19.0 
source-preview-pug 0.2.0 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 0.8.6 
teletype 0.13.3 
tempfile 0.3.2 
tool-bar 1.1.11 
vhdl-entity-converter 0.9.0 
wordcount 3.0.0 
```

**Comment by rsese** [comment] 2019-03-25 18:46
Thanks for the report! I'm guessing this isn't reproducible in safe mode (atom --safe)?

I think this is likely a duplicate of #16164 - based on that issue and #16305, my guess would be that autocomplete-python might be causing the error?

If you can reproduce in safe mode however, please let us know.

**Closed by rsese** 2019-03-25 18:46 UTC
