### ISSUE TITLE
Installing packages takes too long without any visible feedback

### ISSUE THREAD

**Issue by vfonic** [atom/atom#19445] opened 2019-06-04 11:43 UTC
## Summary

Sometimes it takes a minute to install a package, the only indicator of something maybe happening are the stripes over "Install" button. I think at least a bit more info would be welcome:

Here are some suggestions:
1) ETA
2) What's happening (logs)
3) Make the packages install faster

## Motivation

I switched from VS Code to Atom and the difference in time it takes to install a single package is really noticeable.

**Comment by rsese** [comment] 2019-06-05 01:57
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/apm/issues/148 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-05 01:57 UTC
