### ISSUE TITLE
update reminder doesn't dismiss after update

### ISSUE THREAD

**Issue by reidzen** [atom/atom#7064] opened 2015-06-02 18:21 UTC
![screen shot 2015-06-02 at 11 19 55 am](https://cloud.githubusercontent.com/assets/12400509/7943401/4004fa62-0919-11e5-9441-3d9fdef7c0f0.png)
the update reminder is still there after updating. does go away after click, but not immediately after updating.

**Comment by mnquintana** [comment] 2015-06-02 18:22
This is a duplicate of https://github.com/atom/settings-view/issues/511 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-02 18:22 UTC
