### ISSUE TITLE
Regex backreference being inserted instead of match group for project wide searches

### ISSUE THREAD

**Issue by m4rk3r** [atom/atom#20608] opened 2020-04-09 19:46 UTC
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

It appears the the regex `find all` and `replace all` within a project has a bug. When a *file is open* the backreference is inserted instead of the captured text. If the file isn't open, the replace works as it should. This bug doesn't seem to appear when `find all` and `replace all` within a single file.

### Steps to Reproduce

1. create two identical test text files within a folder, with text to search and replace
<img width="1105" alt="Screen Shot 2020-04-09 at 3 35 31 PM" src="https://user-images.githubusercontent.com/216952/78933889-f9de1700-7a77-11ea-804f-d289a4da8458.png">
<img width="1105" alt="Screen Shot 2020-04-09 at 3 30 35 PM" src="https://user-images.githubusercontent.com/216952/78933903-fea2cb00-7a77-11ea-8843-2c6923995d66.png">
 
2. Crate a regex search w/ replacement using backreference, leaving one file open..
![image](https://user-images.githubusercontent.com/216952/78934042-3f9adf80-7a78-11ea-9db7-b6c66b82c037.png)

3. Select `Replace All`
<img width="1105" alt="Screen Shot 2020-04-09 at 3 41 12 PM" src="https://user-images.githubusercontent.com/216952/78934230-92749700-7a78-11ea-9fc3-f4be168b0b8f.png">

**Expected behavior:**

It would be expected that the search & replace would work in both files

**Actual behavior:**
In the file that was open, the `backreference` is inserted, instead of match:
<img width="1105" alt="Screen Shot 2020-04-09 at 3 42 05 PM" src="https://user-images.githubusercontent.com/216952/78934319-bafc9100-7a78-11ea-9307-c1e34b6dfbed.png">

And the file that was closed performed as expected:
<img width="1105" alt="Screen Shot 2020-04-09 at 3 42 10 PM" src="https://user-images.githubusercontent.com/216952/78934349-c6e85300-7a78-11ea-8f85-4e202f04e198.png">

**Reproduces how often:**
Consistently reproduces, in both Linux and MacOS

### Versions
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

### Additional Information
Thank you, love atom : )

**Comment by lkashef** [comment] 2020-04-10 18:33
Hey @m4rk3r, thanks for the report.

Reproduced in Atom 1.44.0 stable and 1.47.0-5 Nightly

**Comment by maxm123** [comment] 2020-04-13 23:50
This seems to have been fixed with [this commit to the text-buffer repo](https://github.com/atom/text-buffer/commit/fefbab23412de3907172377b0da76ed34a914ce2). Before that, occurrences plain-text replaced. This didn't happen to files which are closed because of the different handling of open editors (for which unsaved buffers may exist) and 'untouched' files for which the search-and-replace is done by another library. That difference is found [here](https://github.com/atom/atom/blob/master/src/workspace.js#L2211).

**Closed** 2020-07-17 13:50 UTC
Labels: triaged
