### ISSUE TITLE
Atom hangs if right click menu is open for 30 seconds

### ISSUE THREAD

**Issue by raaaste** [atom/atom#11901] opened 2016-06-04 19:44 UTC
Steps to reproduce:
1. Open Atom
2. Right click on the editor or tree view
3. Wait for about 30 seconds
4. Ubuntu / Atom gives the following error dialog:

![screenshot from 2016-06-04 22-37-14](https://cloud.githubusercontent.com/assets/19609673/15801662/ec3be2a2-2aa4-11e6-947d-f0eabc956453.png)

It's possible to continue normally by clicking "keep waiting". I don't think Atom really crashes, so this dialog probably shouldn't appear. I think there's some sort of timeout _somewhere_ for something to happen after opening the right click menu. I haven't tested this on Windows / OS X.

Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial

EDIT: added version info.

**Comment by sbrl** [comment] 2016-10-10 09:58
Yep, I see this on Windows 10 (with the anniversary update).

**Comment by damieng** [comment] 2017-03-15 00:15
Not able to repro this on Windows 10 - it is likely however caused by the issue fixed in https://github.com/electron/electron/pull/8702 on Electron.

Will be a while before we can use it tho - it ships in Electron 1.6.2

**Comment by 50Wliu** [comment] 2018-01-10 02:26
Fixed by #16192 if I'm not mistaken.

**Closed by 50Wliu** 2018-01-10 02:26 UTC
Labels: bug, electron
