### ISSUE TITLE
Uncaught Error: spawn /usr/local/bin/pep8 ENOENT

### ISSUE THREAD

**Issue by lluc** [atom/atom#8131] opened 2015-07-29 07:48 UTC
Uncaught Error: spawn /usr/local/bin/pep8 ENOENT

**Atom Version**: 0.161.0
**System**: linux 3.13.0-58-generic
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At events.js:85

Error: spawn /usr/local/bin/pep8 ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by batjko** [comment] 2015-07-29 07:50
Can you try and update Atom to the latest version, then also update any packages you have installed, then see if the issue still occurs?

This appears to be a problem of a package, presumably one regarding Python?
Therefore running `atom --safe` should not show this issue, can you confirm?

**Comment by lluc** [comment] 2015-07-29 07:54
I confirm : with running atom --safe it's OK. :-)

2015-07-29 9:51 GMT+02:00 Patrick Metzdorf <notifications@github.com>:

**Comment by batjko** [comment] 2015-07-29 07:56
Still upgrade Atom, though. Your version is rather far behind. We're on 1.0.3 as of this morning.

**Comment by lluc** [comment] 2015-07-29 08:55
OK.

2015-07-29 9:57 GMT+02:00 Patrick Metzdorf <notifications@github.com>:

**Comment by kevinsawicki** [comment] 2015-07-29 17:27
Closing this out as a duplicate of #4561 and also if it is linter related then there is a custom notification for this message now instead of an uncaught exception message.

**Closed by kevinsawicki** 2015-07-29 17:27 UTC
