### ISSUE TITLE
Crashes when file in project is edited outside of Atom (Windows)

### ISSUE THREAD

**Issue by paul-goggin** [atom/atom#8521] opened 2015-08-26 14:58 UTC
Crashes in Windows 7 when a file is changed outside of Atom. if you move or add or delete a file in Windows Explorer it will cause Atom to Crash,
This also happens if the file is on a windows server share (\\server\share\projectDir\) and another user changes a file in the project dir

**Comment by damieng** [comment] 2016-05-06 02:46
Unable to reproduce this - it's possible it's been fixed in the meantime. If you still experience this in Atom 1.7 please re-open.

**Closed by damieng** 2016-05-06 02:46 UTC
Labels: windows
