### ISSUE TITLE
Update Atom package for Windows/Chocolatey

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8153] opened 2015-07-30 04:26 UTC
The [package for Atom](https://chocolatey.org/packages/Atom) on Chocolatey is woefully outdated and poorly behaved, and it needn't be.

Atom shouldn't use an installer for its Windows package. This excludes Squirrel, InstallShield, MSI, and anything else that touches the registry or creates shortcuts. Instead, its package should unarchive its [Windows zip release](https://github.com/atom/atom/releases/download/v1.0.3/atom-windows.zip) into the folder Chocolatey gives it, like [most other packages](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/automatic/autohotkey.portable/tools/chocolateyInstall.ps1).

Moreover, Chocolatey is for installing packages globally via script, not on a per-user basis. It's orthogonal to [the Squirrel installer](https://atom.io/download/windows). By randomly installing to the `~/AppData/Local/atom` of the current user, Atom blocks other users from accessing it, defeating the purpose of package management, and preventing users and organizations from deploying Atom on servers or across multiple machines via Chocolatey (I wanted to do exactly this recently).

Changing Atom's Chocolatey package to install a zipfile fixes all of this.

**Comment by mnquintana** [comment] 2015-07-30 04:29
This looks like a duplicate of https://github.com/atom/atom/issues/6931 – let's keep the discussion there.

**Closed by mnquintana** 2015-07-30 04:29 UTC
