### ISSUE TITLE
Available package updates count does not sync when updating packages from menu

### ISSUE THREAD

**Issue by bhalperin** [atom/atom#8881] opened 2015-09-21 17:24 UTC
###### Using version 1.0.15 on Windows 7.
1. Status bar shows e.g. __1 update__ (1 available package update)
2. Choose package updates from the menu
3. Update the package

Status still shows available updates. Restarting Atom refreshes this count.

**Comment by mnquintana** [comment] 2015-09-21 17:29
Thanks for the report! This looks like a duplicate of https://github.com/atom/settings-view/issues/511 – please subscribe there for updates.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Closed by mnquintana** 2015-09-21 17:29 UTC

**Comment by bhalperin** [comment] 2015-09-21 17:35
Indeed duplicate. I searched for similar report before creating this one, but did not find. Thanks.
