### ISSUE TITLE
Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog'    at Function.Module._resolveFilename (module.js:351:15)    at Function.Module._load (module.js:293:25)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

### ISSUE THREAD

**Issue by s-wirth** [atom/atom#5979] opened 2015-03-16 10:15 UTC
[Enter steps to reproduce below:]

1. Create new File
2. Try to safe empty file with cmd+shift+s

**Atom Version**: 0.184.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77

Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
    at metaToValue (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77:15)
    at Object.exports.require (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:157:34)
    at Atom.module.exports.Atom.showSaveDialogSync (/Applications/Atom.app/Contents/Resources/app/src/atom.js:836:23)
    at Pane.module.exports.Pane.saveItemAs (/Applications/Atom.app/Contents/Resources/app/src/pane.js:560:26)
    at Pane.module.exports.Pane.saveActiveItemAs (/Applications/Atom.app/Contents/Resources/app/src/pane.js:529:19)
    at Workspace.module.exports.Workspace.saveActivePaneItemAs (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:693:35)
    at atom-workspace.atom.commands.add.core:save-as (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:298:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
```

### Commands

```
     -0:42.1 core:save (atom-text-editor.editor)
     -0:16.6 application:new-file (atom-text-editor.editor)
  3x -0:15.0 core:save-as (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by thomasjo** [comment] 2015-03-16 10:33
Try updating to the latest version (v0.187.0) and see if the problem goes away.

**Comment by s-wirth** [comment] 2015-03-16 11:43
That is the version I am already using. I just restarted the app and now it
works swimmingly again.
But thank you very much for the help :)

2015-03-16 11:33 GMT+01:00 Thomas Johansen <notifications@github.com>:

**Comment by 50Wliu** [comment] 2015-03-16 12:38
This is actually a duplicate of atom/tree-view#399.

**Closed by 50Wliu** 2015-03-16 12:38 UTC
Labels: more-information-needed
