### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by Pileggi** [atom/atom#11773] opened 2016-05-17 12:27 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/lib64/electron/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/rpc-server.js:304:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)

```
At /usr/lib64/electron/resources/electron.asar/renderer/api/remote.js:178

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/lib64/electron/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/rpc-server.js:304:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/usr/lib64/electron/resources/electron.asar/renderer/api/remote.js:178:13)
    at undefined.remoteMemberFunction (/usr/lib64/electron/resources/electron.asar/renderer/api/remote.js:112:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/lib64/atom/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/lib64/atom/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/lib64/atom/src/atom-environment.js:775:26)
    at /usr/lib64/atom/src/atom-environment.js:984:27
```

### Commands

```
  5x -2:53.2.0 core:close (atom-text-editor.editor.is-focused.mini)
     -1:05.7.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  7x -1:02.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:02.4.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.9.1
auto-indent, v0.5.0
color-picker, v2.1.1
colorful-json, v1.0.0
highlight-selected, v0.11.2
jshint, v1.8.5
language-docker, v1.1.6
linter, v1.11.4
linter-checkbashisms, v0.1.5
linter-docker, v0.1.2
pigments, v0.26.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-05-17 13:49
Closing as a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-17 13:49 UTC
