### ISSUE TITLE
Release Notes tab stuck at 0.157.0

### ISSUE THREAD

**Issue by simonjosefsson** [atom/atom#5101] opened 2015-01-16 09:08 UTC
Atom is updating fine but 'Help' > 'Release Notes' gives me an old stale version with an active restart and update button.

![atom](https://cloud.githubusercontent.com/assets/3242316/5773581/64818ffc-9d64-11e4-9e25-6227464c88ae.jpg)

First time I installed Atom was 2-3 months ago before auto-updating was added (direct, not through chocolatey) so that could potentially be a clue. Haven't tried a complete nuke and re-install yet.

Atom 0.174.0 at Win 8.1 64bit

**Comment by 50Wliu** [comment] 2015-01-16 14:56
Duplicate of #3757, please subscribe there for updates.

**Closed by 50Wliu** 2015-01-16 14:56 UTC

**Comment by simonjosefsson** [comment] 2015-01-16 15:21
Sorry for the duplicate, weird that I missed it
