### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/fbricon/Library/Application Supp...

### ISSUE THREAD

**Issue by fbricon** [atom/atom#9935] opened 2015-12-03 17:42 UTC
[Enter steps to reproduce below:]

1. opened ~/.zshrc with Atom 1.2.4
2. see error message

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/fbricon/Library/Application Support/com.github.atom.ShipIt/update.yambcqO'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/fbricon/Library/Application Support/com.github.atom.ShipIt/update.yambcqO'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/fbricon/Library/Application Support/com.github.atom.ShipIt/update.yambcqO/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "showInvisibles": true,
    "preferredLineLength": 120,
    "invisibles": {},
    "showIndentGuide": true,
    "fontSize": 20
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-03 22:13
This is a duplicate of #7399 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-03 22:13 UTC
