### ISSUE TITLE
no UI after 1.20.0-beta0 update

### ISSUE THREAD

**Issue by Nowass** [atom/atom#15207] opened 2017-08-09 13:14 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After the update to 1.20.0-beta0 version, no UI is loaded. When Atom is lunched (opening some *.adoc/*.c file), only black window is appear. When the file is open from menu View->Developer->Open In Dev Mode then the UI is loaded and content of file is displayed.

### Steps to Reproduce

1. update to 1.20.0-beta0
2. open any *.adoc / *.c file

**Expected behavior:** The UI is loaded and content of file is displayed

**Actual behavior:** Only black window with menu bar is displayed

**Reproduces how often:** 100% of time

### Versions

Atom    : 1.20.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.3                                                                                                                                                                                             npm  3.10.10                                                                                                                                                                                            node 6.9.5 x64                                                                                                                                                                                          python 3.6.0                                                                                                                                                                                            git 2.11.0.windows.1                                                                                                                                                                                    visual studio

Windows 10 version 1703 build 15063.540

### Additional Information

N/A

**Comment by 50Wliu** [comment] 2017-08-09 13:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15194. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-09 13:15 UTC
