### ISSUE TITLE
Uncaught Error: Tried to unload active package 'platformio-ide-terminal'

### ISSUE THREAD

**Issue by thescolima** [atom/atom#19765] opened 2019-08-08 18:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'platformio-ide-terminal'

```
At C:\Users\thesc\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:11

Error: Tried to unload active package 'platformio-ide-terminal'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:380394)
    at PackageManager.unload (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:935024)
    at PackageManager.install (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:935257)
    at PackageCard.install (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:2570353)
    at HTMLButtonElement.installButtonClickHandler (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:2556456)
```

### Commands

```
     -2:19.3.0 platformio-ide-terminal:toggle (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.9.3 
ult-terminal 0.2.2 
```

**Comment by rsese** [comment] 2019-08-08 21:04
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16873 so you can subscribe there for updates if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-08 21:04 UTC
