### ISSUE TITLE
Using CTRL+CMD+Down Arrow to move code down results in an error sound

### ISSUE THREAD

**Issue by simonbingham** [atom/atom#12370] opened 2016-08-09 07:53 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Using CTRL+CMD+Down Arrow to move selected code down results in an error sound. These's no sound when moving code up. I don't think there should be a sound.

### Steps to Reproduce

1. Select a line of code.
2. Press CTRL+CMD+Down Arrow to move the selected code down.

**Expected behavior:**

There is no error sound.

**Actual behavior:**

There is an error sound.

### Versions

1.9.4

**Comment by 50Wliu** [comment] 2016-08-09 13:35
This is a duplicate of #1669 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-09 13:35 UTC
