### ISSUE TITLE
binding "alt-'" does not work

### ISSUE THREAD

**Issue by liefswanson** [atom/atom#7993] opened 2015-07-20 19:19 UTC
OS: Arch-Linux x64 (kde)
version: 1.0.2 https://aur.archlinux.org/packages/atom-editor-bin/

When i try to bind to "alt-'" it shows up in the keybindings menu but does not function.
however "ctrl-'" does work (both in the menu and the binding actually works.

For clarification, I am using a fairly obscure keyboard layout (programmer-dvorak) 
In my layout, the ' is where z is in qwerty. So I would like to bind
"alt-'": 'core:undo' **or** 'alt-\'': 'core:undo

but that does not work. As in pressing the keys does not actually undo

"ctrl-'": 'core:undo' **and** 'ctrl-\'': 'core:undo'
both work. As in pressing the keys does actually undo

I also tried binding it to other commands
'ctrl-\'': 'command-palette:toggle' 
does not work

I also tried changing keyboard layouts, and in qwerty I could not seem to make the binding work either.

My unsubstantiated theory is something is not properly reading the ' character even when escaped.

**Comment by mnquintana** [comment] 2015-07-20 19:20
I think this is a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37 – let's keep the discussion there.

**Closed by mnquintana** 2015-07-20 19:20 UTC
