### ISSUE TITLE
Can't install any package, neither from GUI nor from the command line

### ISSUE THREAD

**Issue by zank-it** [atom/atom#16646] opened 2018-01-29 16:45 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Can't install any package, neither from GUI nor from the command line

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

That it works?!

**Actual behavior:** [What actually happens]

[http://oi66.tinypic.com/28jxnjm.jpg ](url)
Error code:
"write EPROTO 101057795:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:openssl\ssl\s3_pkt.c:1493:SSL alert number 10
101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:"

CPU: n3450

**Reproduces how often:** [What percentage of the time does it reproduce?]

every time

### Versions

(29/01/18 all last version)
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by rsese** [comment] 2018-01-31 00:07
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16640 (and https://github.com/atom/settings-view/issues/924). You may want to subscribe there for updates.

The workaround for now is to use the 32-bit version of Atom as mentioned in https://github.com/atom/settings-view/issues/924#issuecomment-334625768.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-01-31 00:07 UTC
