### ISSUE TITLE
multi-line editing broken with new soft wrapping

### ISSUE THREAD

**Issue by jt-money** [atom/atom#14012] opened 2017-03-15 23:02 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
![mar-15-2017 11-59-14](https://cloud.githubusercontent.com/assets/18338995/23974366/24796158-0998-11e7-96d3-ac5b4309abff.gif)

After the most recent update to 1.15.0, I noticed multi-line editing is broken when Adding selections (above or below) or Splitting into Lines when the line is longer than 500 characters and continues onto the next line ("soft-wrapped" line?). Forgive me if I am missing something simple here; I would love to hear suggestions if this is a configuration problem on my part.

### Steps to Reproduce

1. Have a line of text that surpasses 500 characters, and is thus wrapped on the following line (with a dot as the line number)
2. Use Add Selection (above or below) to add a soft-wrapped line
3. Use Split into Lines to add a soft-wrapped line

**Expected behavior:** 

"Split into lines" will split into the logical "start" of each line, regardless of soft-wrapping.

"Add selection (above or below)" will use the logical "start" of each line, regardless of woft-wrapping.

**Actual behavior:** 

"Split into lines" seems to ignore the logical "start" of soft-wrapped lines and treats the continued line as the actual line of text to which the cursor is distributed (see animated gif). 

"Add selection (above or below)" uses the correct logical "start" of the next soft-wrapped line IN ADDITION TO the "start" (NOT A REAL LINE START!!!) of the continued line, which is incorrect because, after all, this is just one big "logical line", except it has been "virtually" split at the 500 char mark (see animated gif)

**Reproduces how often:** All 500+ character soft-wrapped lines are affected, I beleive

### Versions

OSX 10.10.5
$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.5.4
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

I use Atom only for Python, so not sure if this applies to other languages, etc.

**Comment by rsese** [comment] 2017-03-16 02:45
Thanks for the report!  I think I see what you're describing but I have some questions to clarify.

> After the most recent update to 1.15.0

Just to confirm, the behavior was different in 1.14?

The soft-wrap at 500 lines was introduced in 1.15.0 /cc https://github.com/atom/atom/pull/13820.

To clarify your steps to reproduce, you're describing 2 separate behaviors yes?

* `Add Selection` places a cursor to the start of both the soft-wrapped line and the actual line.

![add-select](https://cloud.githubusercontent.com/assets/734194/23979296/ad27c34a-09c6-11e7-889c-d813609650f1.gif)

* `Split selection into lines` and then <kbd>Cmd</kbd><kbd>←</kbd> and you'll see a cursor only at the start of the soft-wrapped line.

![split-select](https://cloud.githubusercontent.com/assets/734194/23979305/b013f88a-09c6-11e7-9b3d-9b92ba2e1781.gif)

And in both cases, you expect a cursor to be placed at line 5 only and not the soft-wrapped line?

**Comment by jt-money** [comment] 2017-03-16 20:01
> Just to confirm, the behavior was different in 1.14?

Yes, indeed, in 1.14.x I do remember that lines longer than 500 characters were not force soft-wrapped as they are in 1.15.0 (which meant syntax highlighting stopped after 100 tokens(?) I did not care about highlighting because in almost all cases they were SQL strings that I did not want to bother formatting just for the sake of Atom multi-line edit compatibility). I stumbled across this when trying to comment out many lines in my python script (without using """; that is silly, and makes psycopg2 scripts a royal pain) and I saw that Split into Lines did not actually allow me to accomplish this as it had done countless times prior to 1.15.0.

> To clarify your steps to reproduce, you're describing 2 separate behaviors yes?

I should have split the gif in two parts for each demonstration, but that is correct and your gifs demonstrate this a little better.

> And in both cases, you expect a cursor to be placed at line 5 only and not the soft-wrapped line?

Yes, that is correct (in my opinion/interpretation) because line 5.5 (*hello world hello world"*) is _not_ actually a "line" in the true sense; rather it is a "logical extension" of the _preceding_ line (line 5) and thus "line" rules do not apply here (as far as multi-line cursors are concerned) and apply only to the actual line itself (line 5). In my world, there is no "line 5.5", there is only line 5, followed by line 6, so "line" 5.5 needs to exist in a sort of "pseudo-line" state where the _"beginning"_ of line 5.5 is actually the beginning of line 5, and the _"end"_ of line 5 is actually the end of line 5.5.

Personally, that is my interpretation of how multi-line editing should work. For that matter, I believe Home and End should work the same way: going to the "actual" beginning or end of line 5 (if it was force soft-wrapped by the editor), but currently in version 1.15.0 line 5.5 _really is_ treated like a true line - even though it's "existence" depends ONLY on the fact that you opened it up in Atom editor. In other words, your hello function script is considered to have 10 lines in Atom editor, but only 9 lines in Sublime Text 3...obviously there is only one right answer here, but I would absolutely love to hear anyone else rationalize the current behavior, or some alternate behavior, as I may be excluding someone else's multi-line edit use case(s). After all, I don't really see anyone else complaining about this, haha, though it could also mean that everyone else in the world wraps their text religiously - making this whole thing a non issue for them ;)

**Comment by rsese** [comment] 2017-03-16 22:33
> Yes, indeed, in 1.14.x I do remember that lines longer than 500 characters were not force soft-wrapped as they are in 1.15.0

Oh sorry, I meant the behavior with soft-wrapping and selections described in your report - the wrapping for lines longer than 500 characters was intentional for 1.15.0 and was for sure different than the 1.14.x releases.

> > And in both cases, you expect a cursor to be placed at line 5 only and not the soft-wrapped line?

> Yes, that is correct

Great thanks for confirming - about the second case:

> * Split selection into lines and then <kbd>Cmd</kbd><kbd>←</kbd> and you'll see a cursor only at the start of the soft-wrapped line.

I found another report of this particular behavior and it looks like expected behavior based on the discussion there:

https://github.com/atom/atom/issues/6059#issuecomment-84604301

I also tested things out in Sublime and the behavior seems the same to me?

> * `Add Selection` places a cursor to the start of both the soft-wrapped line and the actual line.

![add-select-sublime](https://cloud.githubusercontent.com/assets/734194/24021144/678b6056-0a6d-11e7-9501-e125edc7c5f0.gif)

> * Split selection into lines and then <kbd>Cmd</kbd><kbd>←</kbd> and you'll see a cursor only at the start of the soft-wrapped line.

![split-select-sublime](https://cloud.githubusercontent.com/assets/734194/24021198/b12718e0-0a6d-11e7-9050-d63e0ad62ac4.gif)

So it looks like our behavior matches how Sublime works.  Are you seeing differently?

**Comment by jt-money** [comment] 2017-03-17 18:03
> I also tested things out in Sublime and the behavior seems the same to me?

I was moreso looking for a rationalization of the current behavior with unwrapped lines, not changing the subject to "but what if you _also_ wrap in Sublime?". What about my question pertaining to line count/numbering? Your script either has a total of 9 lines or 10 lines - it can't have _both_; Sublime handles this by saying: "**let's let the user decide if they want soft-wrapping, and if they just want to keep the lines long, hey, we can let the user do that too, but some features could break down - like syntax highlighting**", which is also how Atom was handling it, but now in Atom this has been changed to: "**the user will no longer be able to disable soft-wrap at 500 characters, so the user's scripts now behave as if they have extra lines, which also, by the way, means in a Split into Lines scenario, 'line 5 and 1/2' is a valid line number, but 'line 5' is not**".

In my opinion, this is just as silly as saying "your script has a syntax error on line 5.5 - not line 5, this is _not_ line 5 we are talking about with the syntax problem; it's on a new line that exists after 5, but before 6, and that new line I just created for you as an editor program is called "line 5 and 1/2", or, simply "line 5.5" if you're not into the whole 'brevity' thing."

> So it looks like our behavior matches how Sublime works. Are you seeing differently?

Yes I am seeing differently because I don't use soft wrapping AT ALL in Sublime either, as I hate it just as much there, or on any other editor for that matter. I switched to using Atom because it has superior interface design (over Sublime) and I was just dealing with the broken syntax highlighting in these cases of 500+ char lines, but I can't really use multi-line editing in Atom anymore at this point (and thus Atom editor) without formatting these long SQL strings down to something that is compatible with Atom. Honestly, I'd rather have my super long, broken highlighted, 500+ character lines back (from 1.14.x) which would also give me the benefit of being able to open that same script in any other editor and it would _not_ show the extra lines as if they were actual, additional lines in the file.

If Python 2.7 rejected lines longer than 80 characters, then I would gladly stamp this into my mind forever as an immutable fact and abide by it in every script I write, but I think even the most hardcore Python-formatting-nazis out there would not seriously push for such a 'feature' to be added to Python - the same goes for a 100 char limit, same goes for a 275 char limit, and same goes for a 500 char limit. Those limits are all just as arbitrary, unless you want to argue for returning back to our console editor roots - and hey, while we're at it, let's just all go back to using 8 letters max per file name and using exclusively vim/emacs and also hating on people who use nano because they haven't memorized vim yet like a _real_ man, or they didn't grow up in an era where the _only good choice_ was vi/vim/emacs.

Without reliable multi-line edit functionality, I'll have to go back to Sublime 3 for now...makes me sad since I like Electron and I really prefer your cleaner, nicer UI vs. Sublime - but if:

1. I highlight a block of text
2. I split that text into lines using "Split into Lines"
3. I go to beginning of line, which means the beginning of all selected lines
4. I type the character '#'

The above steps should comment out a block of text, as it did before, but now there will always be a line that didn't get a comment (line 5 in your example), because line 5.5 steals all the cursor glory from line 5 - this is both illogical and unacceptable in my opinion.

**Comment by rsese** [comment] 2017-03-17 21:20
Thanks for the extra detail, I think I see what you're getting at now.  The behavior you noticed and that we both showed in our GIFs was somewhat secondary to the idea of lines longer than 500 characters auto soft-wrapping as of 1.15.0 when soft-wrapping was completely user-controlled before. The reasoning is explained in the PR I referenced (https://github.com/atom/atom/pull/13820) but is also touched on in this discussion from the forum:

https://discuss.atom.io/t/atom-editor-line-length-wraps-at-500-chars-on-1-15/40589/7

The soft-wrapping for lines longer than 500 characters was introduced because of a performance problem.  Like Lee mentions and based on a number of reports we received, if we didn't wrap those long lines, then for some people the editor would just hang and be unusable.   But as also mentioned in the PR, this is something that the team is looking to improve so the auto soft-wrap of long lines isn't necessary in the future /cc https://github.com/atom/atom/pull/13820#issuecomment-280778310.

Though not ideal, the workarounds described in the [issue I mentioned earlier](https://github.com/atom/atom/issues/6059#) might be helpful - after making the selections, a couple of things you could do are:

* https://github.com/atom/atom/issues/6059#issuecomment-84617109 - use just <kbd>←</kbd> instead of <kbd>cmd</kbd><kbd>←</kbd>
* https://github.com/atom/atom/issues/6059#issuecomment-84617542 - use "Editor: move to beginning of line" from the command palette (or bind that command to a keystroke and hit that).

Since the cursor behavior after selections we both saw and reported in this issue is already reported in https://github.com/atom/atom/issues/6059, I'm going to go ahead and close this issue as a duplicate of that one.

**Closed by rsese** 2017-03-17 21:20 UTC
Labels: more-information-needed

**Comment by jt-money** [comment] 2017-03-17 21:51
> The behavior you noticed and that we both showed in our GIFs was somewhat secondary to the idea of lines longer than 500 characters auto soft-wrapping as of 1.15.0 when soft-wrapping was completely user-controlled before.

You are correct, though as an avid soft-wrap hater, I was basically unaware of this and was only referencing the new behavior in 1.15.0 that broke my use case for multi-line editing.

> The soft-wrapping for lines longer than 500 characters was introduced because of a performance problem

I had a feeling this was changed due to that "syntax highlights break after 100 tokens" or some other limitation, and I suppose this is a perfectly sane response from an Electron-based project, so I will continue opening up Atom every few months to see if the next update brings back a kind of "soft-wrap disable", or perhaps if I'm super lucky, soft-wrapped lines will be treated as virtual lines instead, making Atom's implementation of soft-wrap much more logical than Sublime's (I fail to see anything wrong about improving a feature vs. merely copying it).

The workaround of typing half of sentence instead of a quick keyboard command is...awkward, to say the least, so yea, thanks for all the good times, and I'll see you guys again (hopefully) in a few months/years/whatever.
