### ISSUE TITLE
Tab length spaces are treated as tabs

### ISSUE THREAD

**Issue by trent-** [atom/atom#6048] opened 2015-03-20 10:58 UTC
My settings have `tab spaces` set to 4. I also have `soft tabs` enabled - as well as `Show invisibles` so I can see that spaces are being inserted instead of tabs.

If I hit space bar 4 times (or hit tab once).

![space-4](https://cloud.githubusercontent.com/assets/1747643/6747444/7ed62c82-cf2d-11e4-96d4-ad0e763e28ba.png)
That's good, it appears 4 spaces have been inserted. Now if I hit the left key, I'm taken to the start of the line (and not back one space).
![left-arrow](https://cloud.githubusercontent.com/assets/1747643/6747454/b5721a80-cf2d-11e4-8e1f-2bc29afbd729.png)
Or, if I hit backspace, all four spaces are removed.
![backspace](https://cloud.githubusercontent.com/assets/1747643/6747466/e1d0af06-cf2d-11e4-8139-ca42b9f3e42d.png)

Similarly if I try and highlight one of those spaces with my mouse, I can only highlight all or nothing of the 4 spaces.
![hightlight](https://cloud.githubusercontent.com/assets/1747643/6747648/6cd283e8-cf30-11e4-907a-58db5a7add3d.png)
In other editors I use (gedit, brackets), the behaviour I've found is that backspace, or left, will only go back one character, not the whole 4 (or what's configured) spaces.

I'm running on Ubuntu 14.04 (x86_64) and with version 0.187 of Atom.

**Comment by pathawks** [comment] 2015-03-22 22:15
This sounds like the intended behavior of soft tabs.

**Comment by jhasse** [comment] 2015-04-15 11:36
Also think this is intended, I like it (don't want to press 4 times when changing indention)

**Comment by marcoms** [comment] 2015-04-15 15:40
Seems like intentional behaviour from now on (see https://github.com/atom/atom/issues/3174), but +1 for changing it!

**Comment by mnquintana** [comment] 2015-04-15 15:41
Duplicate of #3174

**Closed by mnquintana** 2015-04-15 15:41 UTC
Labels: enhancement

**Comment by marcoms** [comment] 2015-04-15 15:54
@mnquintana I don't think these issues are duplicates. This one seems to be suggesting the removal of this behaviour, while #3174 complains of it not being configurable.

**Comment by mnquintana** [comment] 2015-04-15 15:57
@marcoms You're right in that it's not quite a duplicate, but it is referring to the same underlying "issue" – how Atom treats soft tabs. Since this is intended behavior, and not a bug, it's not likely to be removed, but there could certainly be a config option to change it (as in #3174).

**Comment by dmitrymakhnin** [comment] 2016-06-25 17:35
Please fix this.

It takes control of the text away from the developer.

I, the programmer should choose whether it should treat tab length spaces as tabs or not.

This is incredibly frustrating.

Take for instance a "pre" tag in HTML. My tabs are length 2, but I want to remove 3 spaces before this word. I want to press backspace 3 times, but this causes an additional character to be removed because it
1. removes the 1 whitespace
2. removes the 2 whitespaces
3. removes additional character.

I now have to ctrl-z.

I HATE tabs with a passion and if you like using tabs, you are wrong but that's okay, I respect you as a person as long as you let me have a choice to press my backspace for each white space.

Please fix this!

**Comment by 50Wliu** [comment] 2016-06-25 18:38
@dmitrymakhnin If you read the duplicate issue, you will have found out that it has been fixed already and is already available as a config option in Atom 1.9.0-beta0.

**Comment by dmitrymakhnin** [comment] 2016-07-18 20:34
I'll check out 1.9.0 :)
