### ISSUE TITLE
Non UTF-8 encoding files needs better performance while loading

### ISSUE THREAD

**Issue by alefragnani** [atom/atom#7657] opened 2015-07-02 17:10 UTC
I use my **File Encoding** setting as *Windows 1252*, because I mostly use this kind of file with Atom. And every time I open a large file (let's say 500Kb size, 10k lines), Atom freezes. After a while Atom displays that *keep waiting / close* window, and sometimes it will load, sometimes not.

Atom always open the file as *UTF-8*. I noted it because I can see the erroneous characters instead of  accented words, and then it *changes* the encoding to *Windows 1252*. If I use **File Encoding** as *UTF-8*, the file is opened almost instantaneously (but with that erroneous characters).

It should avoid the *UTF-8* loading step, and directly open it as the defined encoding.

**Comment by batjko** [comment] 2015-07-02 18:27
Have a look at #7493. What you're seeing is at least very closely related, probably a duplicate of it.

**Comment by alefragnani** [comment] 2015-07-02 21:46
I agree. I remember taking a look at the profile and it was showing the same point (`JsDiff.diffLines`, `Diff.diff` and so on).

**Comment by damieng** [comment] 2016-04-23 18:08
Closing as dupe of https://github.com/atom/atom/issues/7493 so will track there.

**Closed by damieng** 2016-04-23 18:08 UTC
