### ISSUE TITLE
Uncaught Error: Tried to unload active package 'Pymakr'

### ISSUE THREAD

**Issue by GHardman** [atom/atom#16931] opened 2018-03-11 15:45 UTC
[Enter steps to reproduce:]
1. Got an error when opening Atom that it could not load PyMakr package. 
2. It suggested I re-install. 
3. When I tried to do that, this is the error I got.

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'Pymakr'

```
At C:\Users\w0run\AppData\Local\atom\app-1.24.1\resources\app\src\package-manager.js:630

Error: Tried to unload active package 'Pymakr'
    at PackageManager.unloadPackage (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.unload (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-manager.js:502:36)
    at PackageManager.module.exports.PackageManager.install (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-manager.js:512:18)
    at PackageCard.install (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-card.js:824:33)
    at HTMLButtonElement.installButtonClickHandler (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-card.js:302:22)
```

### Commands

```
     -0:26.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
Pymakr 1.0.3 
```

**Comment by Arcanemagus** [comment] 2018-03-11 20:51
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16873. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-11 20:51 UTC
