### ISSUE TITLE
[UI] Problem with user choice of window size

### ISSUE THREAD

**Issue by maxborowsky** [atom/atom#12356] opened 2016-08-07 15:23 UTC
OS: Win8.1
Atom Versions: 1.9.6 and early

1. I set size of application window ~1030x700:

![image-001](https://cloud.githubusercontent.com/assets/20723033/17463163/79903cc6-5cd1-11e6-99be-ca9c3a966e36.png)

2. I expand the window to full screen (with border):

![image-002](https://cloud.githubusercontent.com/assets/20723033/17463187/ec5371b0-5cd1-11e6-9a35-a7841b50001e.png)

3. I restart Atom, but when I minimize window, its size is default and my choice, as it turns out, is not saved:

![image-003](https://cloud.githubusercontent.com/assets/20723033/17463319/1d6929fa-5cd4-11e6-812c-5066f3de462b.png)

**Comment by arcticicestudio** [comment] 2016-08-07 15:54
I think this is related to [Electron](http://electron.atom.io).  
There is a enhancement issue [electron/electron #5993](https://github.com/electron/electron/issues/5993) for a *API to restore window state*.

**Comment by Ben3eeE** [comment] 2016-08-07 20:32
https://github.com/atom/atom/issues/10720

**Comment by Ben3eeE** [comment] 2016-10-04 19:17
Closing a duplicate of #10720. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-04 19:17 UTC
