### ISSUE TITLE
Some packages in settings tab are missing settings button

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#6592] opened 2015-05-01 04:11 UTC
Some packages in the settings tab don't have a button to see the settings for that package.  I assume these are packages without configuration options.  But there are many other useful features in the settings for a package that are missing for these packages ....

- Load time
- Github link
- Report issue
- Changelog
- License
- View code
- Keybindings

## Versions

* **Atom:**       0.194.0
* **Atom-Shell:** 0.22.3
* **OS:**         linux 3.14.0
* **Misc**
    * apm  0.161.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.3
    * git 1.7.9.5

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.6.3.</small>

**Comment by mnquintana** [comment] 2015-05-01 04:15
Duplicate of atom/settings-view#471

You can get to the package detail view by clicking on the package card body - there's no need to click on the settings button. You can see the design discussion in atom/settings-view#443 and atom/settings-view#355

**Closed by mnquintana** 2015-05-01 04:15 UTC

**Comment by mark-hahn** [comment] 2015-05-01 06:05
> You can get to the package detail view by clicking on the package card
body

No one would think to click on the background.  I've added my comment to
that issue.
