### ISSUE TITLE
Uncaught Error: error: 126/\?\~\AppData\Local\atom\app-1.26.0\resources\app.asar.unpacked\node_mo...

### ISSUE THREAD

**Issue by rafalszo** [atom/atom#17192] opened 2018-04-21 09:41 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 126\\?\C:\Users\rafal\AppData\Local\atom\app-1.26.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: error: 126\\?\C:\Users\rafal\AppData\Local\atom\app-1.26.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.26.0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.26.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:55.1.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-monokai 0.10.9 
autoclose-html 0.23.0 
busy-signal 1.4.3 
git-plus 7.10.2 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-autohide 0.10.1 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
monokai-seti 0.9.0 
open-in-browsers 0.0.30 
print-atom 0.1.1 
python-autopep8 0.1.3 
refactor 0.11.5 
script 3.17.3 
seti-syntax 1.1.3 
seti-ui 1.10.0 
sync-settings 0.8.6 
wombat-light-syntax 1.2.0 
```

**Comment by lee-dohm** [comment] 2018-04-21 15:55
Thanks for reaching out!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14461. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2018-04-21 15:55 UTC
