### ISSUE TITLE
Uncaught Error: Impossibile trovare il modulo specificato./\?\~\AppData\Local\atom\app-1.46.0\r...

### ISSUE THREAD

**Issue by Chiaras91** [atom/atom#20706] opened 2020-05-07 09:24 UTC
[Enter steps to reproduce:]

1. ...

2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Impossibile trovare il modulo specificato.
\\?\C:\Users\kiara\AppData\Local\atom\app-1.46.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: Impossibile trovare il modulo specificato.
\\?\C:\Users\kiara\AppData\Local\atom\app-1.46.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:1:721712)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:2780724)
    at get_manager (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:2780826)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:2780952)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1081124)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1253631)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1251616)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:284744)
```

### Commands

```
     -0:17.3.0 core:delete (span.syntax--meta.syntax--delimiter.syntax--comma)
```

### Non-Core Packages

```

```

**Comment by lkashef** [comment] 2020-05-08 18:13
Hey @Chiaras91, thanks for reaching out

This seems like a duplicate of https://github.com/atom/atom/issues/20401, caused mainly by a faulty installation.

I will go ahead and close this one, feel free to comment or open a new issue if the problem still persists.

**Closed by lkashef** 2020-05-08 18:13 UTC
