### ISSUE TITLE
Critical: Opening a file with command line arguments ends up in wrong encodings

### ISSUE THREAD

**Issue by prasannavl** [atom/atom#6914] opened 2015-05-22 23:06 UTC
Calling `atom.cmd filename` on windows, or opening with `node atom.js filename` , always ends up with UTF-8 encoding, even if its not. Auto-detect doesn't seem to be triggered when opened from arguments.

However, manually triggering auto-detect seems to do the trick.

But this is serious, as there is no warning of any kind, and the file will end up being filled up with garbage due to wrong encoding, with no way to reverse it.

**Comment by izuzak** [comment] 2015-05-23 20:39
Thanks for the feedback -- this is a duplicate of https://github.com/atom/atom/issues/4160, I believe. You might also be interested in reading https://github.com/atom/encoding-selector/issues/3 for more context.

**Closed by izuzak** 2015-05-23 20:39 UTC
