### ISSUE TITLE
Atom Beta - v1.3.0-beta0 - Unable to update SSL error

### ISSUE THREAD

**Issue by tgandrews** [atom/atom#9658] opened 2015-11-17 20:30 UTC
When attempting to update the Beta I am seeing the following message 

    An SSL error has occurred and a secure connection to the server cannot be made.: (null)

The release version updated successfully, so I doubt this is a local environment issue.

What additional information can I provide?

**Comment by benogle** [comment] 2015-11-17 21:13
cc @maxbrunsfeld

**Comment by jasonrudolph** [comment] 2015-11-17 23:26
I'm seeing this error as well.

![atom-beta-update-error](https://cloud.githubusercontent.com/assets/2988/11228150/ba09619a-8d58-11e5-8a93-81e835376ee4.png)

**Comment by enilsen16** [comment] 2015-11-18 00:10
![test_rb_-__users_erik_dev_st_overseer_-_atom](https://cloud.githubusercontent.com/assets/5035876/11228974/ad32c2d0-8d45-11e5-87e8-402b968b0cbb.png)

Same here

**Comment by Coyoter** [comment] 2015-11-18 03:42
The same. Maybe the issue is made by the newest OSX release? (10.11.2  15C47A)

**Comment by dbpolito** [comment] 2015-11-18 12:27
Same here

**Comment by peterpoe** [comment] 2015-11-18 12:36
Got this in the console:
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

Found a workaround here:
https://forums.developer.apple.com/message/5857

Add this to Info.plist:

	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key><true/>
	</dict>

Don't know if it's a fix or a hack though...

**Comment by joshaber** [comment] 2015-11-18 16:59
This is caused by https://github.com/atom/electron/issues/3442.

**Comment by joshaber** [comment] 2015-11-18 17:13
Hmm this is weird. It looks like atom.io passes the ATS check:

```
$ nscurl --ats-diagnostics https://atom.io
...
Default ATS Secure Connection
---
ATS Default Connection
Result : PASS
```

Could someone who's having this issue run `nscurl --ats-diagnostics https://atom.io` and let me know what they get?

**Comment by dbpolito** [comment] 2015-11-18 17:31
My Output:

```$ nscurl --ats-diagnostics https://atom.io
Starting ATS Diagnostics

Configuring ATS Info.plist keys and displaying the result of HTTPS loads to https://atom.io.
A test will "PASS" if URLSession:task:didCompleteWithError: returns a nil error.
Use '--verbose' to view the ATS dictionaries used and to display the error received in URLSession:task:didCompleteWithError:.
================================================================================

Default ATS Secure Connection
---
ATS Default Connection
Result : PASS
---

================================================================================

Allowing Arbitrary Loads

---
Allow All Loads
Result : PASS
---

================================================================================

Configuring TLS exceptions for atom.io

---
TLSv1.2
Result : PASS
---

---
TLSv1.1
Result : PASS
---

---
TLSv1.0
Result : PASS
---

================================================================================

Configuring PFS exceptions for atom.io

---
Disabling Perfect Forward Secrecy
Result : PASS
---

================================================================================

Configuring PFS exceptions and allowing insecure HTTP for atom.io

---
Disabling Perfect Forward Secrecy and Allowing Insecure HTTP
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled for atom.io

---
TLSv1.2 with PFS disabled
Result : PASS
---

---
TLSv1.1 with PFS disabled
Result : PASS
---

---
TLSv1.0 with PFS disabled
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled and insecure HTTP allowed for atom.io

---
TLSv1.2 with PFS disabled and insecure HTTP allowed
Result : PASS
---

---
TLSv1.1 with PFS disabled and insecure HTTP allowed
Result : PASS
---

---
TLSv1.0 with PFS disabled and insecure HTTP allowed
Result : PASS
---

================================================================================
```

**Comment by joshaber** [comment] 2015-11-18 17:32
@dbpolito Thanks! And are you still getting that error checking for updates?

**Comment by dbpolito** [comment] 2015-11-18 18:24
Yes, i'm still able to see, OS Version: `10.11.2 15C47A`

**Comment by joshaber** [comment] 2015-11-18 19:14
That's interesting. I wonder if it's a bug in the OS X beta then.

What OS is everyone else on who's seen this?

**Comment by tgandrews** [comment] 2015-11-18 19:22
I'm on `10.11.1 (15B42)`

**Comment by joshaber** [comment] 2015-11-18 19:23
@tgandrews Thanks! Could you run `nscurl --ats-diagnostics https://atom.io` and paste in the output?

**Comment by tgandrews** [comment] 2015-11-18 19:27
@joshaber 
````
➜  api git:(master) nscurl --ats-diagnostics https://atom.io
Starting ATS Diagnostics

Configuring ATS Info.plist keys and displaying the result of HTTPS loads to https://atom.io.
A test will "PASS" if URLSession:task:didCompleteWithError: returns a nil error.
Use '--verbose' to view the ATS dictionaries used and to display the error received in URLSession:task:didCompleteWithError:.
================================================================================

Default ATS Secure Connection
---
ATS Default Connection
Result : PASS
---

================================================================================

Allowing Arbitrary Loads

---
Allow All Loads
Result : PASS
---

================================================================================

Configuring TLS exceptions for atom.io

---
TLSv1.2
Result : PASS
---

---
TLSv1.1
Result : PASS
---

---
TLSv1.0
Result : PASS
---

================================================================================

Configuring PFS exceptions for atom.io

---
Disabling Perfect Forward Secrecy
Result : PASS
---

================================================================================

Configuring PFS exceptions and allowing insecure HTTP for atom.io

---
Disabling Perfect Forward Secrecy and Allowing Insecure HTTP
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled for atom.io

---
TLSv1.2 with PFS disabled
Result : PASS
---

---
TLSv1.1 with PFS disabled
Result : PASS
---

---
TLSv1.0 with PFS disabled
Result : PASS
---

================================================================================

Configuring TLS exceptions with PFS disabled and insecure HTTP allowed for atom.io

---
TLSv1.2 with PFS disabled and insecure HTTP allowed
Result : PASS
---

---
TLSv1.1 with PFS disabled and insecure HTTP allowed
Result : PASS
---

---
TLSv1.0 with PFS disabled and insecure HTTP allowed
Result : PASS
---

================================================================================
````

**Comment by joshaber** [comment] 2015-11-18 23:46
I've opened #9688 to address this, but it comes with a big caveat: those already on the beta with this problem won't see the new update. They'll need to manually download a new version, or wait until we get the new cert deployed.

**Comment by nathansobo** [comment] 2015-11-19 05:07
@joshaber Are there any advantages to waiting for the cert to be deployed? Once that cert is deployed will any beta users that didn't re-download leapfrog to it?

**Comment by fmaida** [comment] 2015-11-20 09:29
I can confirm that I'm getting the same error on Atom Beta v1.3.0-beta1, -beta2 and -beta3.
I'm using Atom on a Mac with Mac OS X 10.11.1

**Comment by joshaber** [comment] 2015-11-20 10:32
@nathansobo I decided to close that PR. It was a bandaid and a not particularly great one. We have to do the infrastructure changes to support a new cert.

**Comment by nathansobo** [comment] 2015-11-20 16:38
Cool. :heart: for taking care of this.

**Comment by joshaber** [comment] 2015-12-01 15:59
The fix has been deployed :boom:

**Closed by joshaber** 2015-12-01 15:59 UTC
Labels: atom, bug, network

**Comment by tgandrews** [comment] 2015-12-01 16:43
:+1: Thanks @joshaber
