### ISSUE TITLE
Add portable version for Linux

### ISSUE THREAD

**Issue by Ricain** [atom/atom#4980] opened 2015-01-10 14:40 UTC
Hi,

I am a student and I can not install and use Atom since I do not have root access on any school computer.
Is there a way to download directly a binary like Sublime Text?

This could be also useful for anyone that would like Atom on a thumb drive.

May be this join atom/atom#2939

**Comment by lee-dohm** [comment] 2015-01-10 23:05
I agree that the concept of the feature is the same between this and #2939, but I think there needs to be enough different in the implementation that it merits a separate Issue. @izuzak, what do you think? Should we combine these issues? Or leave them separate?

**Comment by izuzak** [comment] 2015-01-11 10:16
@lee-dohm good question and I'm not really sure, to be honest. I'd probably close this one in favor of atom/atom#2939 -- it already has some non-windows specific comments.

**Comment by lee-dohm** [comment] 2015-01-11 18:31
Sounds good. Thanks for the advice, @izuzak. @Ricain, I'm going to close this as a duplicate of #2939, please subscribe to that issue. I'll add a comment there and mark it as Linux too.

**Closed by lee-dohm** 2015-01-11 18:31 UTC
Labels: enhancement, linux

**Comment by Ricain** [comment] 2015-01-12 17:17
Thank :)

**Comment by JonasT** [comment] 2016-10-01 23:48
@lee-dohm 
Has this actually been implemented for Linux?

https://github.com/atom/atom/pull/8442 explicitly mentions "We're on Windows", so it doesn't really look like Linux was taken into account.

It would also be nice if such a version was actually provided for download, e.g. as AppImage build ( http://appimage.org/ ) which can be simply launched - or at least instructions on how to assemble one.

**Comment by probonopd** [comment] 2016-10-02 11:07
@JonasT I also think it would be nice if the Atom team would provide an official [AppImage](http://appimage.org). In the meantime, you can have a look at my AppImage builds at
https://bintray.com/probono/AppImages/Atom#files

These are generated using the binaries from the officially-provided deb and are just repackaged in the AppImage format. The script that does this is at
https://github.com/probonopd/AppImages/blob/master/recipes/atom/Recipe

**Comment by JonasT** [comment] 2016-10-02 11:47
@probonopd yes but I would assume they are not portable, are they? They would still use the `~/.atom` folder which goes completely against the point of a truly portable build. So that only makes the install & running slightly easier, but it doesn't actually provide something you can slap on an usb stick.

**Comment by probonopd** [comment] 2016-10-02 12:15
@JonasT 

```
export HOME=/your/usb/stick
./Atom.AppImage
```

done :-)

**Comment by JonasT** [comment] 2016-10-02 12:27
@probonopd and then you forget it once, and everything is messed up. Also, I imagine this can have weird side effects if any external tools are used by any of the Atom plugins.

I'm not saying it doesn't work perfectly as you intended, but maybe this should be officially tested & provided preferably by making the AppImage internally do this, so people can actually rely on it to work properly.

**Comment by probonopd** [comment] 2016-10-02 12:32
@JonasT that would be trivially easy to do; e.g., the AppImage could export $HOME to a directory that is next to the AppImage and has the .home extension or something like that.

**Comment by JonasT** [comment] 2016-10-02 12:36
That is good to know. However, now it's still your personal homebrew package and not an official one...

We're kinda derailing here a bit with this discussion of implementation details. The important thing at this point would be some official word on whether we can get an official portable version.

It's neat that you made one that works, but there is some value in having this officially packaged and provided directly and officially on the Atom site.

**Comment by probonopd** [comment] 2016-10-02 12:39
Couldn't agree more @JonasT

**Comment by probonopd** [comment] 2017-08-08 20:26
See https://github.com/atom/atom/pull/15193.

@JonasT AppImage now [supports](https://github.com/AppImage/AppImageSpec/issues/4#issuecomment-309285394) portable home and data directories.

**Comment by JonasT** [comment] 2017-08-08 21:35
@probonopd that is amazing <3

@lee-dohm suggestion: since #2939 was closed despite no official portable Linux build being available yet and the pull request for generating the app image still being unmerged / work in progress, maybe this issue here should be reopened again until Linux portable mode has actually been added to Travis-CI and official releases?

**Comment by infinito84** [comment] 2017-09-29 13:30
I downloaded the rpm version, extracted the files, and ran the executable file at Downloads/usr/share/atom/atom, 
Works on Ubuntu 14.04 64bits

**Comment by probonopd** [comment] 2017-09-29 16:20
@infinito84 may I ask why you did not use the AppImage?

**Comment by Serkan-devel** [comment] 2017-09-30 16:28
@probonopd is the Appimage version actually ready?
And @infinito84 how did you run rpm on ubuntu?

**Comment by infinito84** [comment] 2017-09-30 18:01
@probonopd I was on a guest session, and I couldn't install anything, and I didn't see the [link](https://bintray.com/probono/AppImages/Atom#files) for downloads.

@Serkan-devel I don't really run a rpm on Ubuntu, but a rpm file is just a compressed file, I uncompressed it, and found the executable file, and just double clicked on it.

**Comment by probonopd** [comment] 2017-10-01 11:44
There is a PR for it, https://github.com/atom/atom/pull/15193. It has not been merged yet.

**Comment by Ben3eeE** [comment] 2017-10-01 11:49
@probonopd The PR is labeled as work in progress and the first words in the body of the PR are `Don't merge this`

**Comment by probonopd** [comment] 2017-10-01 12:20
You are right, I will update the wording to reflect the current status. Thank you.
