### ISSUE TITLE
Tooltip for tab lingers after closing pane

### ISSUE THREAD

**Issue by makyo** [atom/atom#13056] opened 2016-10-24 04:28 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Tooltip displaying full path of file when hovering over tab remains if you right click and close pane.

### Steps to Reproduce

1. Open a file
2. Open a second file in a split pane (e.g: right click file in tree, click "Split right")
3. Hover over one of the tabs until the blue tooltip pops up showing the file's full path
4. Without moving off the tab, right click and select "Close pane"

**Expected behavior:** The tooltip disappears when the tab is closed with the pane

**Actual behavior:** The tooltip remains, even if you interact with, hover over, and close other tabs.

<img width="1280" alt="fullscreen_10_23_16__10_27_pm" src="https://cloud.githubusercontent.com/assets/303761/19633515/f0bd777a-996f-11e6-9cf6-71ec3f7948ea.png">

### Versions

```
$ atom -v
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm -v
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.8.4
```

**Comment by Ben3eeE** [comment] 2016-10-24 06:34
Duplicate of https://github.com/atom/tabs/issues/362. Closed via https://github.com/atom/tabs/pull/379.

**Closed by Ben3eeE** 2016-10-24 06:34 UTC
