### ISSUE TITLE
Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog'    at Function.Module._resolveFilename (module.js:351:15)    at Function.Module._load (module.js:293:25)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

### ISSUE THREAD

**Issue by ajndroortiz** [atom/atom#6012] opened 2015-03-18 00:15 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77

Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
  at metaToValue (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77:15)
  at Object.exports.require (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:157:34)
  at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:705:23)
  at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:507:21)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:456:18)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:697:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:741:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
  2x -0:33.6 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
     -0:28.7 snippets:expand (atom-text-editor.editor.is-focused)
  4x -0:28.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.4 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
     -0:17.9 core:undo (atom-text-editor.editor.is-focused)
     -0:14.6 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.4 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
     -0:09.5 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:09.1 core:move-to-bottom (atom-text-editor.editor.is-focused)
  8x -0:07.7 core:move-up (atom-text-editor.editor.is-focused)
     -0:06.1 core:move-down (atom-text-editor.editor.is-focused)
     -0:05.8 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.3 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -0:04.6 core:select-up (atom-text-editor.editor.is-focused)
  3x -0:03.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".codekit"
    ],
    "disabledPackages": [
      "sassbeautify",
      "emmet"
    ],
    "themes": [
      "itg-dark-ui",
      "dracula-theme"
    ]
  },
  "editor": {
    "fontFamily": "menlo",
    "fontSize": 14,
    "lineHeight": 1.5,
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "softWrap": true,
    "useShadowDOM": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
ScssBundle, v0.4.0
Stylus, v0.6.0
atom-alignment, v0.11.0
atom-jade, v0.1.0
auto-detect-indentation, v0.3.0
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.5.0
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v1.2.0
change-case, v0.5.1
color-picker, v1.4.4
compass, v0.7.5
css-color-highlighting, v0.2.4
css-snippets, v0.5.0
dash, v1.1.0
dracula-theme, v0.7.6
foundation5-snippets, v0.2.0
highlight-line, v0.10.1
itg-dark-ui, v0.2.0
jslint, v1.2.1
language-liquid, v0.2.0
webbox-color, v0.5.6
wordpress, v0.2.0
wordpress-api, v1.1.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-03-18 00:16
Woot! That is one un-clean title.

**Comment by 50Wliu** [comment] 2015-03-18 00:26
Duplicate of atom/tree-view#399, please subscribe there for updates.
@steelbrain the long-title thing is being worked on by @benogle.

**Closed by 50Wliu** 2015-03-18 00:26 UTC
