### ISSUE TITLE
apm doesn't work with `chokidar` package

### ISSUE THREAD

**Issue by paulmillr** [atom/atom#5050] opened 2015-01-14 10:21 UTC
so if you install it w apm install it simply doesn't work, throws errors. just add it to package.json and lauhch `node` CLI, then load chokidar

everything is cool w NPM.

node v0.10.35
npm 2.1.18
atom-shell v0.20.5

log:

```
[2048:0114/122537:INFO:renderer_main.cc(207)] Renderer process started
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file /Users/user/.atom/.node-gyp/.node-gyp/0.20.0/src/node_object_wrap.h, line 77.
[1]    2046 abort      ../atom-shell-v0.20.5-darwin-x64/Atom.app/Contents/MacOS/Atom .
```

**Comment by kevinsawicki** [comment] 2015-01-14 17:27
Can you paste the code you are using that is failing?

Here is what I'm seeing:

![screen shot 2015-01-14 at 9 26 52 am](https://cloud.githubusercontent.com/assets/671378/5743644/82c31170-9bcf-11e4-88b6-821b67204808.png)

**Comment by kevinsawicki** [comment] 2015-01-14 22:39
I believe this is a duplicate of https://github.com/atom/apm/issues/220

**Closed by kevinsawicki** 2015-01-14 22:39 UTC
Labels: more-information-needed
