### ISSUE TITLE
Changelog doesn't update?

### ISSUE THREAD

**Issue by vinkla** [atom/atom#9715] opened 2015-11-20 12:42 UTC
It seems the changelog isn't updated? Maybe it doesn't download or it isn't published?

<img width="487" alt="screen shot 2015-11-20 at 1 40 58 pm" src="https://cloud.githubusercontent.com/assets/499192/11300104/835fed68-8f8c-11e5-8323-69a2c162d50b.png">

**Comment by mnquintana** [comment] 2015-11-20 13:35
Thanks for the report! This is a duplicate of https://github.com/atom/release-notes/issues/39 - feel free to subscribe there for updates.

**Closed by mnquintana** 2015-11-20 13:35 UTC

**Comment by vinkla** [comment] 2015-11-20 13:43
Thanks!
