### ISSUE TITLE
Atom does not create shortcuts at install time 

### ISSUE THREAD

**Issue by inemesitaffia** [atom/atom#20107] opened 2019-11-03 11:21 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
   * [X]  Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * [X]  Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * [X]  Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
     * [X] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * [X]  Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. download atom 64 bit on windows 10 1903 
2. Install -
3. close atom… 
4.  look for shortcut on start menu and desktop 
**Expected behavior:**
A shortcut should be on the start menu and desktop

**Actual behavior:**
no shortcut start menu and desktop

**Reproduces how often:**

100%
### Versions

atom 1.41.0 x64 on Windows 10 1903 64 bit
### Additional Information

This is my first time ever installing atom. I worked around it by reinstalling and then pinning atom to my taskbar

**Comment by rsese** [comment] 2019-11-11 00:56
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14020 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-11 00:56 UTC
