### ISSUE TITLE
I want to change the installation and location directory of the program

### ISSUE THREAD

**Issue by cybermerlin** [atom/atom#16266] opened 2017-11-24 13:33 UTC

**Comment by rsese** [comment] 2017-11-26 00:51
Thanks for taking the time to contribute!

I'm assuming you're on Windows since the issue template isn't filled out with those details?  Will go ahead and close as a duplicate of https://github.com/atom/atom/issues/7504, see that issue for the discussion that took place.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-26 00:51 UTC
