### ISSUE TITLE
Backup improvement : prefer ~/.config/atom/ and ~/.local/shared/atom/ instead of ~/.atom/

### ISSUE THREAD

**Issue by jpolo** [atom/atom#6020] opened 2015-03-18 13:27 UTC
It would be nice to split .atom into .config/atom and .local/shared/atom (respectively AppData/Roaming and AppData/Local for Windows). There are more details on freedesktop.org spec for corresponding environment variable and use cases.

For example "compile-cache" would rather go to .local/shared and "snippets.cson, keymap.cson" to .config.

This clean separation would really help for backups (.local can usually be ignored, .config is important)

**Comment by rumpelsepp** [comment] 2015-03-23 09:39
related docs for this: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by lee-dohm** [comment] 2017-05-10 03:48
Duplicate of the more detailed #8281.

**Closed by lee-dohm** 2017-05-10 03:48 UTC
Labels: duplicate
