### ISSUE TITLE
Can't open on the new  macOS

### ISSUE THREAD

**Issue by sex-squirrel** [atom/atom#17589] opened 2018-06-27 06:19 UTC
macOS 10.13.5 (17F77)
Darwin 17.6.0
Automatic flashback

**Comment by darkforest666** [comment] 2018-06-27 07:05
all the same , try to reinstall as usual

**Comment by thomasjo** [comment] 2018-06-27 07:56
Despite the lack of information, I'm going to assume this is a duplicate of #17557. If you are confident it is not, open a new issue and completely fill in the issue template.

**Closed by thomasjo** 2018-06-27 07:56 UTC
