### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('/...

### ISSUE THREAD

**Issue by luckywwx** [atom/atom#17334] opened 2018-05-16 12:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('\
"') contains HTML space characters, which are not valid in tokens.

```
At C:\Users\lucky\AppData\Local\atom\app-1.27.0\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:445

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('\
"') contains HTML space characters, which are not valid in tokens.
    at SuggestionListElement.addClassToElement (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:445:50)
    at SuggestionListElement.renderItem (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:497:30)
    at SuggestionListElement.renderItems (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:319:18)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.27.0/resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -4:58 editor:newline (input.hidden-input)
     -4:57.6.0 core:paste (input.hidden-input)
  2x -4:47.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:21.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:16.3.0 core:move-left (input.hidden-input)
     -1:15.6.0 core:move-right (input.hidden-input)
  2x -1:11.1.0 core:move-down (input.hidden-input)
     -1:10.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:07.5.0 core:move-down (input.hidden-input)
     -1:07.1.0 autocomplete-plus:confirm (input.hidden-input)
  2x -1:06.5.0 core:move-right (input.hidden-input)
     -0:51 editor:newline (input.hidden-input)
  2x -0:49.6.0 core:backspace (input.hidden-input)
     -0:48.5.0 editor:newline (input.hidden-input)
     -0:42.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Non-Core Packages

```
atom-python-run 0.9.6 
autocomplete-python 1.10.5 
file-icons 2.1.20 
kite 0.91.0 
linter-flake8 2.3.0 
minimap 4.29.8 
predawn-ui 1.0.7 
python-autopep8 0.1.3 
python-debugger 0.2.0 
script 3.17.3 
```

**Comment by rsese** [comment] 2018-05-16 19:49
Thanks for the report! I'm guessing this isn't reproducible in safe mode (atom --safe)?

I think this is likely a duplicate of #16164 - based on that issue and #16305, my guess would be that autocomplete-python might be causing the error?

If you can reproduce in safe mode however, please let us know.

**Closed by rsese** 2018-05-16 19:49 UTC
