### ISSUE TITLE
Feature Request: Add Find Previous Button on Ctrl-F

### ISSUE THREAD

**Issue by kp25** [atom/atom#7840] opened 2015-07-11 06:57 UTC
In Atom v1.0, 
On Ctrl-F & selecting a term, one can find all the terms with "Find Next" option. 
Let's say i'm searching for the term "callback", there are over 200 results found in the code. Now i click "Find Next" for 5 times (5th term is the target, i need to modify it), If Accidentally, i click "Find Next" again for the 6th time (past the target), To go back to 5th Term, i need to either restart the search or click "Find Next" until i get back to target. Sublime provides a great option of doing that. Please add that feature to the atom.

**Comment by mnquintana** [comment] 2015-07-11 11:17
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/find-and-replace/issues/322 – closing in favor of that issue.

Also for future reference, Atom's find behavior is provided by [atom/find-and-replace](https://github.com/atom/find-and-replace), not atom/atom.

**Closed by mnquintana** 2015-07-11 11:17 UTC
