### ISSUE TITLE
Open file dialog only opens Window if at least one Window is open on macOS

### ISSUE THREAD

**Issue by patricks** [atom/atom#13966] opened 2017-03-09 13:44 UTC
I found a strange bug on Atom (1.14.4) with the latest macOS version.

Steps to reproduce:

- Open Atom.app
- Close all Windows
- Try to open a file via File -> Open...
- Nothing happens

**Comment by 50Wliu** [comment] 2017-03-09 15:19
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-03-09 15:19 UTC
