### ISSUE TITLE
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.

### ISSUE THREAD

**Issue by Dentosal** [atom/atom#6135] opened 2015-03-27 22:04 UTC
Atom crashes every time when I try to open it, from command line and from dock. It crashes immediately after opening, I can't even see the window. I have used atom in my computer few months with out any problem.

When opening atom from terminal it prints following message every time:

    LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.

And OS X opens "Problem Report for Atom" window.

It contains following information

    Process:         Atom [27076]
    Path:            /Applications/Atom.app/Contents/MacOS/Atom
    Identifier:      com.github.atom
    Version:         ???
    Code Type:       X86-64 (Native)
    Parent Process:  launchd [353]
    Responsible:     Atom [27076]
    User ID:         501

    Date/Time:       2015-03-27 23:58:27.061 +0200
    OS Version:      Mac OS X 10.9.5 (13F1066)
    Report Version:  11

    ...

    Crashed Thread:  0

    Exception Type:  EXC_BREAKPOINT (SIGTRAP)
    Exception Codes: 0x0000000000000002, 0x0000000000000000

    Application Specific Information:
    dyld: launch, loading dependent libraries

    Dyld Error Message:
      Library not loaded: @rpath/libchromiumcontent.dylib
      Referenced from: /Applications/Atom.app/Contents/Frameworks/Atom Framework.framework/Versions/A/Atom Framework
      Reason: image not found

    Binary Images:
        0x7fff6e412000 -     0x7fff6e445817  dyld (239.4) <7AD43B9B-5CEA-3C7E-9836-A06909F9CA56> /usr/lib/dyld
        0x7fff855f1000 -     0x7fff855f1fff  com.apple.Carbon (154 - 157) <45A9A40A-78FF-3EA0-8FAB-A4F81052FA55> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
        0x7fff8727d000 -     0x7fff87419ff3  com.apple.QuartzCore (1.8 - 332.3) <72003E51-1287-395B-BCBC-331597D45C5E> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
        0x7fff8ee6d000 -     0x7fff8eebffff  libc++.1.dylib (120) <4F68DFC5-2077-39A8-A449-CAC5FDEE7BDE> /usr/lib/libc++.1.dylib
        0x7fff90102000 -     0x7fff90103ff7  libSystem.B.dylib (1197.1.1) <E303F2F8-A8CF-3DF3-84B3-F2D0EE41CCF6> /usr/lib/libSystem.B.dylib

**Comment by 50Wliu** [comment] 2015-03-27 22:28
Duplicate of #3093, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-27 22:28 UTC
