### ISSUE TITLE
Crash on start with Atom 1.28.0 or Atom 1.28 beta

### ISSUE THREAD

**Issue by yodatak** [atom/atom#17574] opened 2018-06-25 09:54 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
* [X] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [X] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
* [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When i run atom 1.28 it crash in running when i do rename %USERPROFILE%\.atom .atom-backup2 it launch but crash if i accept or refuse the telemetry windows .

The crash log dump:

[Atom Crashes.zip](https://github.com/atom/atom/files/2132618/Atom.Crashes.zip)

### Steps to Reproduce

1. Launch Atom ( it can crash just by launch)
2. Accept telemerty or refuse it 
3.  Crash

**Expected behavior:** To not crash

**Actual behavior:** It crash and i can't use atom

**Reproduces how often:** 1min/ 2 min 

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python 3.6.4
git 2.17.1.windows.2
visual studio

Xeon E3-1240
32GO
Windows 10 64 bit 

1607 14393.2189

**Comment by yodatak** [comment] 2018-06-25 10:04
I got this when i open the dmp
FAULTING_IP: 
node+2879f1
00007fff`984679f1 8b410c          mov     eax,dword ptr [rcx+0Ch]

EXCEPTION_RECORD:  ffffffffffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 00007fff984679f1 (node+0x00000000002879f1)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 000000000000000c
Attempt to read from address 000000000000000c

DEFAULT_BUCKET_ID:  NULL_CLASS_PTR_READ

PROCESS_NAME:  atom.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at "0x%08lx" referenced memory at "0x%08lx". The memory could not be "%s".

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at "0x%08lx" referenced memory at "0x%08lx". The memory could not be "%s".

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  000000000000000c

READ_ADDRESS:  000000000000000c 

FOLLOWUP_IP: 
node+2879f1
00007fff`984679f1 8b410c          mov     eax,dword ptr [rcx+0Ch]

NTGLOBALFLAG:  0

FAULTING_THREAD:  0000000000002024

PRIMARY_PROBLEM_CLASS:  NULL_CLASS_PTR_READ

BUGCHECK_STR:  APPLICATION_FAULT_NULL_CLASS_PTR_READ

IP_ON_HEAP:  00000257846daff0
The fault address in not in any loaded module, please check your build's rebase
log at \bin\build_logs\timebuild\ntrebase.log for module which may
contain the address if it were loaded.

FRAME_ONE_INVALID: 1

LAST_CONTROL_TRANSFER:  from 00000257846daff0 to 00007fff984679f1

**Comment by 50Wliu** [comment] 2018-06-25 14:18
@yodatak are you using a proxy?

**Comment by hui** [comment] 2018-06-25 15:18
+1 

```
atom -v
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python 2.7.10
git 2.16.1
```

Fresh install, crash with Shadowsocks proxy, won't crash when Shadowsocks is off.

**Comment by 50Wliu** [comment] 2018-06-25 15:44
@hui please subscribe to #17557.

**Comment by 50Wliu** [comment] 2018-06-25 22:16
@yodatak is it possible to temporarily disable the proxy and try starting Atom without it?

**Comment by wulidongdong** [comment] 2018-06-26 04:32
same issue here, and i am using a proxy(shadowsocks), when i close shadowsocks, atom can start without crash, but when i open shadowsocks, atom always crash whether i change the proxy setting in .apmrc or not.

**Comment by yodatak** [comment] 2018-06-26 07:22
I can't disable the proxy because of GPIO but when i disconnect the network i got no problem

**Comment by thomasjo** [comment] 2018-06-26 07:57
Assuming this is a duplicate of #17557.

**Closed by thomasjo** 2018-06-26 07:57 UTC
Labels: crash, windows
