### ISSUE TITLE
Nearly permanently brick the current session

### ISSUE THREAD

**Issue by Xembie** [atom/atom#13884] opened 2017-02-27 01:43 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This utilizes ctrl+scroll (font scaling) to make a session permanently(nearly) frozen or corrupt.  Steps to reproduce work most of the time.

### Steps to Reproduce

1. Open about 5-10 files with at least 3000 lines.  The content of the files must have incorrect spelling variations with spell checking enabled. (For some reason, spell checking on some txt files enable upon font scaling and some txt files don't have spell checking at all.)
2. Select any tab and ctrl+scroll (font scaling) in any direction for like a second to create a lot of scroll events.
3. ~~Do a save all.~~
4. Close and reopen Atom.

**Expected behavior:** Scale the font size.

**Actual behavior:** Session immediately freezes upon opening, which may be due to it still trying to resize the tabs.

**Reproduces how often:** 75%

### Versions

atom --version --safe

Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

OS: Windows 10
RAM: 8GB
CPU: i3-6100
GPU: GTX-970

**Comment by lee-dohm** [comment] 2017-02-27 02:12
I can't reproduce this using Atom v1.16.0-dev-2e72f39a2 on Mac OS X 10.12.3. I used [this script](https://github.com/lee-dohm/dotfiles/blob/master/bin/big-file) to create ten files of 3,000 lines each and followed your repro steps. There was no freezing. 

I'm also not sure what you mean by "resize the tabs". The font size is set when you do the `Ctrl+Scroll` action. This setting is saved immediately and when Atom next starts, whatever font size you ended on is the font size that everything is drawn with from the beginning ... there's no "resizing" that happens.

**Comment by Xembie** [comment] 2017-02-27 03:18
@lee-dohm I've updated the steps to produce.

**Comment by lee-dohm** [comment] 2017-02-27 03:44
I was also unable to reproduce using the new steps using both Atom v1.16.0-dev-2e72f39a2 and Atom v1.14.3. I updated my script to generate Lorem Ipsum text and customize the file extension to activate the spell-check package. It is definitely sluggish, but at no point does it "brick" the session. Scaling the font also is unnecessary and seems to not contribute to or ameliorate the sluggishness.

**Comment by Xembie** [comment] 2017-02-27 04:18
@lee-dohm Just tested your script with 1 file of 1000 length, and it has permanently froze my session.  Even reloading Atom leaves it in an unresponsive state.

**Comment by lee-dohm** [comment] 2017-02-27 04:36
@ungb Can you reproduce this?

**Comment by ungb** [comment] 2017-02-27 04:45
Hi @Xembie, can you try disabling spell-check?

We currently have a issue https://github.com/atom/spell-check/issues/190.  @lee-dohm This only occurs on Windows if the issue is related to the spell-check package. 

To disable the package, you can run `apm disable spell-check` from cmd/powershell.

**Comment by Xembie** [comment] 2017-02-27 05:01
@ungb Ahh yeah that fixed it.

**Comment by lee-dohm** [comment] 2017-02-27 05:03
Thanks @ungb 👍 Closing this as a duplicate of atom/spell-check#190.

**Closed by lee-dohm** 2017-02-27 05:03 UTC
Labels: more-information-needed, needs-reproduction
