### ISSUE TITLE
Atom Helper uses 70% CPU after a opening large plain text file is opened

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8908] opened 2015-09-23 15:44 UTC
After opening an 8.4 MB, 521914 line plain-text UTF-8 file in Atom 1.0.15 on OSX, Atom Helper immediately begins to use 70% CPU and continues for ~15 minutes (sometimes much longer). When I'm not plugged in on my older laptop, this causes me to shed 5% battery. What on earth is the purpose of this?!? There is no grammar to parse, and nothing appears to change when it finally stops (if it ever does).

**Comment by mnquintana** [comment] 2015-09-23 15:47
Can you reproduce this after quitting Atom completely and restarting it in safe mode? (`atom --safe`)

Would you be able to share this file so we can try to debug further?

**Comment by vinniejames** [comment] 2015-09-23 21:58
Atom Helper is going crazy for me as well, over 100% on the cpu then Atom hangs and crashes. Completely uninstalled Atom and tried with a clean install, same issue. 

Particularly bad if the Settings > Packages window is open, only default packages and Nuclide are currently installed

Problem is making Atom entirely unusable

<img width="565" alt="screen shot 2015-09-23 at 2 57 51 pm" src="https://cloud.githubusercontent.com/assets/2112033/10060083/80b24630-6203-11e5-8cd6-40ce18266e00.png">

**Comment by alexchandel** [comment] 2015-09-24 21:12
> Can you reproduce this after quitting Atom completely and restarting it in safe mode? (atom --safe)

@mnquintana Yes, Atom Helper even briefly spiked to 99% CPU with `atom --safe`. I really wish I could share it, but unfortunately it's confidential material from a client.

You could probably simulate it though. It's a 521914 line file, LF endings, ascii text, very short lines (median 12 characters, low variance, max is probably 45), 98% of all lines begin with 2 spaces and have an ` = `as the 9th-11th characters and match `^\w+\s*` for the 3rd-8th characters, 95% of all lines end in a digit.

**Comment by dcpomfret** [comment] 2015-09-27 20:40
I can confirm the same issue 
![image](https://cloud.githubusercontent.com/assets/1091024/10125095/a0c5fbde-6568-11e5-89b1-47a56053037d.png)

**Comment by vinniejames** [comment] 2015-09-28 17:19
Possibly some kind of memory leak in the main app? Does anyone know if there is a log file Atom uses that may help narrow down the issue?

**Comment by alexchandel** [comment] 2015-10-14 19:59
Is it possible Atom is trying to match some default regex patterns on the file?

**Comment by vinniejames** [comment] 2015-10-16 00:20
Not likely. It happens for me no matter what file is opened. It has always
been an issue with no files open, as soon as the Settings > Packages tab is
opened

**Comment by 50Wliu** [comment] 2015-10-16 00:24
@vinniejames can you try updating to 1.1.0-beta1 (if you feel safe trying out a beta) and see if that fixes your freezes?

**Comment by vinniejames** [comment] 2015-10-17 20:41
Giving the beta build a try now. I may have narrowed down the issue, I'm
currently running Node v0.10.40 (which apparently is missing packages for
Nuclide
https://discuss.atom.io/t/why-does-atom-1-0-11-on-darwin-ship-with-nodejs-v0-10-40/20615)
Going to check the beta build first on v0.10.40, then try updating to v0.12

**Comment by vinniejames** [comment] 2015-10-17 20:59
The root of the issue appears to be running v0.10.40, at least in my case. Updating Node to v0.12 resolved the issue.

I noticed the beta ships with 0.12 as default. How is the compatibility of newer versions of Node (4.2.1)?

**Comment by 50Wliu** [comment] 2015-10-17 23:51
> How is the compatibility of newer versions of Node (4.2.1)?

Atom and apm were both recently updated to support Node 4, so I think using v4 shouldn't be a problem.

**Comment by vinniejames** [comment] 2015-10-19 20:13
@50Wliu the Atom Helper CPU issue seems to be back after upgrading to Node 4. I tested using both the Beta branch, as well as v1.0.19

**Comment by SebastianZaha** [comment] 2015-11-11 16:49
Can confirm Atom Helper takes 70% CPU constantly with no files open, both on stable branch and on beta channel for me on mac.

I realized this was new and I checked and found out I was running version 1.0.2 for a long time, then jumped to 1.1.0. 

I just tried going back to 1.0.2 and that solves the CPU issues.

**Comment by enricoschroeder** [comment] 2015-11-18 11:59
Same problem here, constant ~70% CPU load with no files open (100% load with a long markdown document open). Very much unusable for me... OSX 10.11.1. 
Contrary to my predecessors, the problem does not go away with version 1.0.2 (also not for 1.1.0 and the current 1.3. betas)

**Comment by alexchandel** [comment] 2015-12-17 14:03
@enricoschroeder Indeed, this is still present (when opening a large file) on 1.3.2. Sadly, Atom fixes <0.1 important bugs per month :\

**Comment by maxbrunsfeld** [comment] 2016-01-04 21:51
@alexchandel, @vinniejames My apologies for the poor experience.

I believe that the `autocomplete-plus` package is the culprit. When opening a new buffer, it attempts to build an index of all 'words' in the file, in order to provide autocomplete suggestions. We need to make this task much faster, and make it utilize the UI thread less.

**Comment by maxbrunsfeld** [comment] 2016-01-04 22:15
Related: https://github.com/atom/autocomplete-plus/issues/452

**Comment by maxbrunsfeld** [comment] 2016-01-04 23:02
Another issue that affects plain text files specifically is the performance of our spell checker. Subscribe to this issue for updates: https://github.com/atom/spell-check/issues/53

**Comment by alexchandel** [comment] 2016-02-02 18:17
@maxbrunsfeld disabling spell-check eliminates the 70% CPU usage when opening the original file.

**Comment by 50Wliu** [comment] 2016-02-02 20:35
Going to assume that the original performance issue reported by @alexchandel has been fixed by atom/node-spellchecker#27, so closing.

@vinniejames, @enricoschroeder, @SebastianZaha: If disabling spell-check (or updating to the 1.5.0 betas) doesn't help, please create a new issue.  Thanks!

**Closed by 50Wliu** 2016-02-02 20:35 UTC
Labels: atom, more-information-needed
