### ISSUE TITLE
Removing many files - modal overlaping ui

### ISSUE THREAD

**Issue by lukasjuhas** [atom/atom#10325] opened 2016-01-07 17:01 UTC
Hi there,

When you are deleting lot of files at once, the modal that comes up when you have to confirm that you are sure you want to deleted selected files overlaps UI.

I was wondering if this would be considered as a bug.

![screen shot 2016-01-07 at 16 53 53](https://cloud.githubusercontent.com/assets/5247674/12176635/4326b52a-b560-11e5-9764-e9981aff7cd3.png)

**Comment by mnquintana** [comment] 2016-01-07 17:04
Thanks for the report! This looks like a duplicate of https://github.com/atom/tree-view/issues/96 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-07 17:04 UTC
