### ISSUE TITLE
Restart and Install Update button on about screen does not work

### ISSUE THREAD

**Issue by eppsilon** [atom/atom#11643] opened 2016-04-28 19:45 UTC
### Description

The button to restart and install an update on the about screen does nothing. The option in the Atom menu did work. I was trying to update from 1.7.2 to 1.7.3. I don't know if the problem persists in 1.7.3.

### Steps to Reproduce

1. Click squirrel icon indicating new update available.
2. On about screen, click "Restart and Install Update".

**Expected behavior:** Atom quits and the new version starts.

**Actual behavior:** Nothing happens.

### Versions

After upgrade:

```
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.8.1
```

**Comment by lee-dohm** [comment] 2016-04-28 22:59
This is a duplicate of https://github.com/atom/about/issues/21. A fix has already been made and we're just waiting for it to percolate down to Stable. For now, the "Restart and Install Update" menu item still works.

**Closed by lee-dohm** 2016-04-28 22:59 UTC
