### ISSUE TITLE
Can not dismiss "No update available" window if opening menu again before the update check finishes

### ISSUE THREAD

**Issue by kosmiq** [atom/atom#12935] opened 2016-10-11 10:23 UTC
### Description

So I just discovered a weird little issue. If I use "check for updates" from the menu, and before the window pops up I open the Atom-menu again I can not dismiss the "No updates available" window neither press something in the menu. The only way to exit Atom is to kill the process using Activity Monitor.
- It happens in safe mode as well.
- I am running version 1.10.2
- No error pops up
- Trying to close in any other way that using Activity Monitor fails.

I am using a Macbook Pro Retina 13" (late 2013) with MacOS 10.12 (sierra) installed.
### Steps to Reproduce
1. Open Atom.
2. Go to Atom menu and select "Check for Update"
3. Before the window appears (telling you there are no updates) open the Atom menu again.
4. Wait a bit.
5. When the update-check window appears try to click whatever. It is no longer possible to close the menu, ok the update-check window.
### Versions

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by Ben3eeE** [comment] 2016-10-11 11:01
I can not reproduce this on Atom 1.10.2 Windows 7. I am able to dismiss the `No Updates Available` dialog.

**Comment by kosmiq** [comment] 2016-10-11 11:56
Here's a video with the issue reproduced on my Mac. I did however also find out that if you click "Ok" enough times (20-30 times or more, seems to vary) it will eventually close.

[atom-bug-update-check.zip](https://github.com/atom/atom/files/521721/atom-bug-update-check.zip)
(I could not upload the .mov, so I zipped it, contains only a small screen recording of the issue in action).

**Comment by sethlopezme** [comment] 2016-10-11 22:18
I was able to reproduce this issue. I was not able to close the dialog, no matter how many times I clicked "OK".

MacOS Sierra 10.12
Atom: 1.11.0
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0

**Comment by kosmiq** [comment] 2016-10-12 07:00
Still happens on 1.11.1, just got the updated and tested it (did not expect it to be fixed, just wanted to update on that).

**Comment by thomasjo** [comment] 2016-10-12 07:46
I have successfully reproduced this in Atom 1.11.1 on macOS 10.12. Looks like a bug in Electron. I'll investigate further, and follow up here once I know more.

**Comment by lkashef** [comment] 2020-07-16 07:18
This seems to have been already fixed, closing the issue

**Closed by lkashef** 2020-07-16 07:18 UTC
Labels: bug, electron, mac, triaged
