### ISSUE TITLE
Atom Helper 104% CPU Usage

### ISSUE THREAD

**Issue by charleshkang** [atom/atom#9053] opened 2015-10-05 18:42 UTC
Atom Version: 1.0.19
OSX: 10.11 El Capitan

First time using Atom to create a simple website. I did not notice any lag on my other 2012MBP with 4GB and the default HDD, but on my 8GB and 250GB SSD I have noticed extreme amounts of CPU consumption.

The only packages I have installed is beautify, so I'm not sure what the issue is. I did read that some people were experiencing this when they created files directly on the desktop but I am not sure why this is happening.

Please tell me if I'm missing anything since this is my first issue submission!

![activitymonitor](https://cloud.githubusercontent.com/assets/12476080/10289903/01b68aba-6b6f-11e5-9b4d-1bf729ce51a0.png)

**Comment by mnquintana** [comment] 2015-10-05 18:45
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/3426 though - closing this out in favor of that issue.

**Closed by mnquintana** 2015-10-05 18:45 UTC

**Comment by charleshkang** [comment] 2015-10-05 18:47
@mnquintana will going through that hopefully fix my problems?

**Comment by mnquintana** [comment] 2015-10-05 18:51
@charleshkang It's still an open issue, unfortunately :confused: - it's something that should get better though as the core team continues focusing on performance.

**Comment by charleshkang** [comment] 2015-10-05 18:56
@mnquintana it's just so weird that atom runs perfectly fine on my other mac, but the one with double the ram and a SSD is somehow being super slowed down...

**Comment by mnquintana** [comment] 2015-10-05 18:57
Can you try quitting Atom completely and reopening it in safe mode (`atom --safe`) and see if you can reproduce this?

**Comment by charleshkang** [comment] 2015-10-05 19:00
where do i input that command? sorry, pretty new to atom!

**Comment by mnquintana** [comment] 2015-10-05 19:02
No worries! Just run that in Terminal. (Make sure you run Atom > Install Shell Commands first from the main app menu - you'll only have to do that once though.)

**Comment by charleshkang** [comment] 2015-10-05 19:04
At 104.8% when ran in safe mode

**Comment by nicbet** [comment] 2015-10-05 23:40
On my 2014 rMBP high CPU occurs when a file is changed and a file changed indicator is visible (tabs / tree view packages - if disable these Atom behaves fine and sits at 1% CPU).

**Comment by usmantahirr** [comment] 2015-10-09 20:27
I am facing same issue as well. I tried 1.0, quit because of this issue, again updated again quit. I downloaded latest build today, still same issue. Atom Helper eats alot of memory.

I even tried opening it in Safe mode, tried deleting and completely installing a fresh copy but nothing solved my problem. I am using El Capitan on MBP 15 i7 16 gb ram and ssd. Atom is very good editor and this issue is blocking me to shift from Webstorm. I am constantly looking for a light weight editor with less impact on memory.

<img width="703" alt="screenshot 2015-10-10 01 24 50" src="https://cloud.githubusercontent.com/assets/4997359/10404694/bc640e1a-6eed-11e5-8ba0-8353088ef6bf.png">

**Comment by CrockCity** [comment] 2015-10-22 21:02
I'm still getting this issue on safe mode as well. 2015 MBP 
![image](https://cloud.githubusercontent.com/assets/4262788/10678174/a9881c28-78de-11e5-9d3e-8b6fcae57691.png)

**Comment by nicolazj** [comment] 2015-12-17 23:40
replace /Applications/Atom.app/Contents/Resources/app/apm/bin/node with newer version, like 0.12.*

It works perfectly now

**Comment by lee-dohm** [comment] 2015-12-18 00:07
As I mentioned in [my post on Discuss](https://discuss.atom.io/t/atomhelper-high-cpu-usage/2553/111?u=leedohm), replacing that copy of node doesn't change the version of node that Atom is running on.

**Comment by sharpmachine** [comment] 2016-06-14 15:54
I having the same issue. CPU at 104%.

<img width="491" alt="screen shot 2016-06-14 at 8 53 49 am" src="https://cloud.githubusercontent.com/assets/600836/16049714/a0f50902-320d-11e6-8c72-316487ce3b59.png">

**Comment by ahanriat** [comment] 2016-08-24 09:11
I've identified a potential bottleneck, it seems like atom spend a lot of time in `child_process.js` file managing `pipes` on stdio
![screen shot 2016-08-24 at 11 10 57](https://cloud.githubusercontent.com/assets/1374161/17925019/7a774158-69eb-11e6-8ba7-3fb8b440fb69.png)

**Comment by jtabone16** [comment] 2016-09-29 14:29
Just had this issue. CPU usage for Atom Helper hit 140% immediately after opening the app. My solution was closing the project that opens on load of Atom (my work repo) so that next time Atom opens, it will be in a clean state. Re-opened my project and now CPU usage for Atom Helper is at 0% when I'm not using the app, hits 34% when doing a global search for a string.

**Comment by soulcreate** [comment] 2016-12-03 16:57
some issue. Why closing?

**Comment by johansen** [comment] 2016-12-14 22:07
This is happening to me as well. Atom 1.12.7 on OSX 10.11.6. It's really killing my battery life.

**Comment by GordeevD** [comment] 2017-08-24 12:40
Probably github plugin. It helped me turn my mac back to cool, when I turned it off.

**Comment by snow** [comment] 2017-09-21 11:00
> Probably github plugin. It helped me turn my mac back to cool, when I turned it off.

same here, in safe mode, atom helper dropped under 5% after disabled github plugin (and leave git-diff enabled).

atom 1.20.1
![image](https://user-images.githubusercontent.com/72957/30692564-a4a2e344-9efe-11e7-8841-84d2572708d1.png)

**Comment by diego-** [comment] 2018-01-22 15:31
ditto, github plugin was the source of high CPU for me. atom 1.23.3

**Comment by Natesurf8** [comment] 2018-07-18 16:35
yep it was github

**Comment by wihodges** [comment] 2018-12-02 03:18
Removal of github helped at first. But still experiencing slow typing. Atom may have to go if it can't even edit text quickly... 

Mojave 10.14.1 - no other app behaves like this so I don't think it's the machine or os.

**Comment by rsese** [comment] 2018-12-03 18:05
@wihodges - if you can reproduce that behavior in safe mode, please open a new issue and fill out the issue template and we'll take a look.
