### ISSUE TITLE
Preview tabs don't stay open when double clicked

### ISSUE THREAD

**Issue by ismay** [atom/atom#7180] opened 2015-06-09 09:46 UTC
With the new preview tabs, there's currently not a way to keep a tab opened without making changes to the file's contents. In sublime, double clicking a file prevents the preview from being closed when switching to another file. This would be useful behaviour in atom's preview tabs as well.

**Comment by mnquintana** [comment] 2015-06-09 11:03
This is a duplicate of https://github.com/atom/tabs/issues/156 – please subscribe there for updates. You can turn a preview tab into a permanent tab either by double-clicking the tab or by right clicking and selecting Keep Preview Tab.

**Closed by mnquintana** 2015-06-09 11:03 UTC
