### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by nford** [atom/atom#21601] opened 2020-10-28 15:16 UTC
[Enter steps to reproduce:]

1. Start Atom
2. Open Project
3. Attempt to type in window

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: 10.15.7
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At electron/js2c/asar.js:138

Error: Module did not self-register.
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2715520)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2715622)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2715748)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1047867)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1228180)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1226165)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284829)
```

### Commands

```
  2x -0:45.4.0 find-and-replace:show (input.hidden-input)
     -0:44.4.0 core:undo (input.hidden-input)
     -0:43.1.0 find-and-replace:show (input.hidden-input)
  5x -0:38.6.0 find-and-replace:find-next (input.hidden-input)
     -0:17 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-jinja2 0.6.0 
auto-close-html2 0.7.0 
busy-signal 2.0.1 
color-picker 2.3.0 
ide-html 0.6.2 
ide-python 1.5.0 
intentions 1.1.5 
language-nunjucks 4.2.1 
language-terraform 0.9.3 
linter 3.1.1 
linter-json-lint 0.1.3 
linter-ui-default 2.1.2 
open-in-browser 0.5.2 
python-autopep8 0.1.3 
split-diff 1.6.1 
terraform-fmt 0.3.0 
url-encode 0.5.0 
```

**Comment by darangi** [comment] 2020-10-29 10:26
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2020-10-29 10:26 UTC
