### ISSUE TITLE
Uncaught Error: spawn /Users/shawn/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Content...

### ISSUE THREAD

**Issue by shawnxusy** [atom/atom#10942] opened 2016-02-23 22:56 UTC
The following occurred when adding a new Go project to Atom. (No additional project open, no changes made to the project yet).

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/shawn/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/shawn/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/shawn/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/shawn/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (/Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (/Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:15:15)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:170:22)
    at /Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at /Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:869:41
    at EventEmitter.<anonymous> (/Users/shawn/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:33.3.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:30 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-02-23 23:38
This is a duplicate of #10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-23 23:38 UTC
