### ISSUE TITLE
Pasting should be its own undo/redo action

### ISSUE THREAD

**Issue by narrowtux** [atom/atom#14785] opened 2017-06-15 08:26 UTC
### Description

When typing a bunch of text and then immediately pasting something, atom will consider the whole text as an "action" in the undo system. If you decide that you pasted the clipboard in the wrong location and undo it, it will not only delete the pasted text, but a few words you've typed before.

### Steps to Reproduce

1. have some text in your clipboard
2. type `abc abc abc = `
3. immediately hit cmd-v / ctrl-v
4. hit cmd-z / ctrl-z

**Expected behavior:**

Editor should contain `abc abc abc = `

**Actual behavior:**

In this example, my editor contained `abc abc ab ` (notice the space behind `ab` which wasn't there before either). This mainly varies by how fast you type and maybe also by the length of the clipboard string. Sometimes it deletes a whole word.

**Reproduces how often:** 

90%

### Versions

Atom: tested with 1.16.0 and 1.18.0-beta0
Electron: 1.3.15
Chrome: 52.0.2743.82
Node: 6.5.0
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0

**Comment by rsese** [comment] 2017-06-15 17:29
Thanks for taking the time to contribute!

I think this a duplicate of https://github.com/atom/atom/issues/4372? You may want to subscribe there for updates but if I mis-understood, please let me know.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-15 17:29 UTC

**Comment by narrowtux** [comment] 2017-06-15 19:38
Thanks :)
