### ISSUE TITLE
Atom fails to launch from older versions of Bash

### ISSUE THREAD

**Issue by h2oboi89** [atom/atom#11164] opened 2016-03-14 19:26 UTC
Running `atom .` opens Atom in local directory just fine (verifies that Git Bash can find and run executable)

Running `atom --version` in Command Prompt spits out version (1.5.4) as expected.

Running `atom --version` in Git Bash does nothing

Running `atom --version > ~/Desktop/atom_version.txt` generates an empty text file.

**Comment by damieng** [comment] 2016-03-14 23:21
Can you try this with the atom.sh and atom.cmd from master?  Just overwrite the contents of your existing 1.5.4 files.

**Comment by h2oboi89** [comment] 2016-03-16 23:57
Couldn't find atom.cmd, but ran atom.sh:
>  AppData/Local/atom/bin/atom.sh -v
>Your platform (MINGW64_NT-10.0 Waters-PC 2.4.0(0.292/5/3) 2016-01-07 19:39 x86_64 Msys) is not supported.

**Comment by damieng** [comment] 2016-03-18 05:58
you'll need to copy them from https://github.com/atom/atom/tree/master/resources/win over the resources folder in your Atom program folder.

**Comment by h2oboi89** [comment] 2016-03-18 23:25
Updated to 1.6.0

Git Bash:
```
>atom -v

>
```

Command Prompt:
```
>atom -v
'ELSE' is not recognized  as an internal or external command,
operable program or batch file.

1.6.0

>
```

**Comment by h2oboi89** [comment] 2016-03-18 23:27
Copied files from master and same behavior, minus the `ELSE` clause.

**Comment by damieng** [comment] 2016-03-19 00:38
Can you type

```bash
which atom
```

And paste here what it outputs? Thanks.

**Comment by h2oboi89** [comment] 2016-03-20 19:41
>15:41:11-Waters~$ which atom
>/c/Users/Waters/AppData/Local/atom/bin/atom

**Comment by TimMensch** [comment] 2016-03-21 18:14
As of 1.7.0-beta0, I get a broken atom command line when using MSYS Bash:

```
tim@copper12 ~/projects/games
$ atom .
/c/Devel/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 1: @echo: command not found
/c/Devel/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 3: SET: command not found
/c/Devel/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 4: SET: command not found
/c/Devel/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 6: syntax error near unexpected token `('
/c/Devel/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 6: `FOR %%a IN (%*) DO ('


tim@copper12 ~/projects/games
$ which atom
/c/Devel/atom/bin/atom

tim@copper12 ~/projects/games
$
```

The new bash.sh that /c/Devel/atom/bin/atom calls consists of 

```
#!/bin/sh
$(dirname "$0")/atom.cmd "$@"
```

It then attempts to run this as a Bash shell script, with the above errors as a result. Until I got the 1.7.0 beta update, everything had been working.

**Comment by damieng** [comment] 2016-03-21 18:40
On both Cygwin and MSYS2 that second line causes it to be run by the standard Windows command processor.  This change was made because the --wait logic in the native bash script was broken on Windows.

I'm not sure why your version of bash wants to try and run the cmd file as if it was a bash script - where did you get your msys?

**Comment by TimMensch** [comment] 2016-03-22 01:49
I got my MSYS from the mingw-get installer. I use the full distribution because the MSYS-Git distribution doesn't have enough of the support tools (GCC etc.).

Bash Version: bash-3.1.17-4-msys-1.0.16-bin.tar.lzma

I just re-ran mingw-get and upgrade Bash, just in case it was relevant. New version::

```
tim@copper12 ~
$ bash --version
GNU bash, version 3.1.23(1)-release (i686-pc-msys)
Copyright (C) 2005 Free Software Foundation, Inc.

tim@copper12 ~
$ atom.cmd .
/c/Devel/atom/bin/atom.cmd: line 1: @echo: command not found
/c/Devel/atom/bin/atom.cmd: line 2: fg: no job control

tim@copper12 ~
$
```

I've never seen bash run a .cmd or .bat file correctly. A quick Google finds:

https://sourceforge.net/p/mingw/bugs/1902/

... plus similar questions about "Why doesn't running a .bat or .cmd file work?" with the answer being "It just doesn't; run it via cmd //c batch.cmd".

A better question might be why your MSYS command line DOES work with .cmd and .bat. I've rolled back to 1.6.0 stable, because I had to get work done, and the only way I could seem to make that happen was to DELETE 1.7.0 beta. (This is why I demonstrated running a .cmd file directly above) If you need me to test anything else, please let me know how to switch back and forth between stable and beta channels without having to do a full reinstall. My Googling for an answer to that question has come up empty on the three separate times I've searched; docs could be improved if there *is* an answer.

**Comment by TimMensch** [comment] 2016-03-22 02:00
Out of curiosity I ran the MSYS that comes with Git as well:

```
Welcome to Git (version 1.9.5-preview20150319)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

tim@COPPER12 /usr
$ atom.cmd
/c/Devel/atom/bin/atom.cmd: line 1: @echo: command not found
/c/Devel/atom/bin/atom.cmd: line 2: fg: no job control

tim@COPPER12 /usr
$
```

**Comment by damieng** [comment] 2016-03-22 03:18
I just tested this again with my default installations of Cygwin on Windows 7:

```bash
damieng@dpg-win7 ~
$ atom.cmd --version

Atom    : 1.8.0-dev-3959259
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

damieng@dpg-win7 ~
```

and with MSYS2 on Windows 10:

```bash
damie@dpg-desk MSYS ~
$ atom --version

Atom    : 1.7.0-beta0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

damie@dpg-desk MSYS ~
```

The 1.6 native bash script failed when using the --wait parameter hence why we were doing this.  (The --wait parameter requires passing a process id to atom.exe that it should kill when the file is closed. We can't just block on atom.exe because if a copy of atom is already open it tells the original copy to open the file and quits)

Open to suggestions!

**Comment by TimMensch** [comment] 2016-03-22 17:07
The [Git For Windows](https://git-for-windows.github.io/) and [official MinGW install](http://mingw.org/) both use MSYS 1. You're using MSYS2, which until your post I'd never even heard of. It appears to be a fork of MinGW partly based on Cygwin, which is interesting, but a lot of people don't use it. 

I can tell you for certain that a *lot* of people do use MSYS1. I was just working for Amazon and MSYS1 is approved while MSYS2 wasn't on the approved list (or I would have heard of it!), and I expect that *far* more people use MSYS1 than MSYS2 because of the fact that it comes with Git for Windows. I might switch to MSYS2 at some point, now that I know about it, but I'm not going to want to switch in the middle of a project (like right now), and neither are a lot of other people, so this is a pretty critical/showstopper bug.

Suggestion: Revert the change so that the command line _works_ with all platforms and find another way to make --wait work. Making --wait work for some people but breaking the entire command line for everyone else is not reasonable, and will result in hundreds of reports if you push it to stable. Install MSYS1 from Git for Windows or from the MinGW installer and add that to your testing cycle so you can know what does and doesn't work in it. You just can't run .cmd files directly from Bash on Windows.

Sorry, but I don't have time to produce an alternate solution to the problem right now. I've already uninstalled 1.7.0, so I don't even have the code to look at, and I need to get back to work on my project.

**Comment by damieng** [comment] 2016-03-22 18:08
I've investigated some more. It would appear that the problem is Bash 3 as all the tools that use Bash 4 are working fine, specifically:

**Works**
* GitHub Shell - Bash 4.3.42(5)-release
* Cygwin - Bash 4.3.42(4)-release
* MSYS2 - Bash 4.3.42(5)-release
* Git Bash (2.7.4) - Bash 4.3.42(5)-release

**Fails**
* MSYS - Bash 3.1.0(1)-release

Reverting back the change so an unsupported platform half-works at the expense of breaking supported platforms again isn't really an option. I suspect it isn't even possible to implement --wait properly on Bash 3 given the effort spent so far.

About the only option left would be to detect Bash 3 and provide the old functionality except for --wait which would provide an error saying Bash 4 is required.

**Comment by TimMensch** [comment] 2016-03-24 17:08
I think your solution is fine: Detect Bash 3 and if they use --wait, present a warning that --wait won't work. Otherwise forward to the new .cmd.

I was unaware of the existence of MSYS2. Others might be as well; the GitForWindows that I downloaded less than a year ago came with MSYS1 (downloading the new version as I write this). 

It might be good, therefore, if someone uses --wait, to say more than "it won't work", but to also let them know that a new version of MSYS2 or GitForWindows would be a valuable upgrade.

**Comment by damieng** [comment] 2016-03-24 17:11
Yeah that sounds like a good idea. I'll try and get that done in the next few days although things are a bit busy.

**Comment by damieng** [comment] 2016-04-11 17:42
It looks like the new Linux subsystem for Windows available on the Insider Fast Ring also tries to execute the cmd as Bash not Powershell.  We're going to need an alternative solution here.

**Comment by damieng** [comment] 2016-04-15 16:44
The Linux subsystem for Windows is currently (build 14316) incapable of running Windows executables so the bash it provides can not be used to launch atom in any way.

**Comment by redxeagle** [comment] 2016-04-18 13:52
i have same error with my git bash on windows 7.

dirty workaround: 
instead of `atom .` use  `powershell atom .`
could be shorten via alias in .bashrc

**Comment by damieng** [comment] 2016-04-22 21:51
Fixed in https://github.com/atom/atom/pull/11544/commits/196bc53e6bef729c4925e0ae3789c3360def8dfd

**Closed by damieng** 2016-04-22 21:51 UTC
Labels: windows
