### ISSUE TITLE
Opening any file with atom leads to opening atom with empty state

### ISSUE THREAD

**Issue by nexisn4** [atom/atom#14357] opened 2017-05-04 20:10 UTC
If i just open atom by clicking on the desktop exe short, it opens blank state, which is fine. I can open any file I want by ctrl+O or drag&drop from a file explorer program.

However, if I open a file with atom, for example "test.cpp" file, atom will proceed to open the blank state.
This happens with any file I open with atom. 

Is this a bug?

**Comment by ungb** [comment] 2017-05-04 20:24
@nexisn4, in the future, please fill out the issue template.  Here's the reason why:

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.


By blank state, do you mean that when open the file `atom test.cpp`, it opens atom, but there's no project in the tree view and the file doesn't show up?  A screenshot or gif would be helpful in this case.  

Also, Can you provide the following info?


### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ahogen** [comment] 2017-05-30 19:38
I noticed this issue as well. However, running on Atom 1.17.2 x64, I don't have this issue anymore, so I think it's been fixed.

(running on Windows 7 Professional 64-bit (sp1))

**Comment by ahogen** [comment] 2017-05-30 19:41
Possibly related:

* Issue #10283
* Issue #9643
* Issue #7186

**Comment by cetkovic** [comment] 2017-08-10 00:00
I'm having the same issue as described in this bug. Here are more details:

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If I open a file using 'atom myfile.txt', a blank atom window opens with a blank new file. When I open by providing either the --safe or -d, it opens up the file normally. I have also tried disabling all community packages, but it still doesn't work.

### Steps to Reproduce

1. open a terminal window and type 'atom myFile.txt'

**Expected behavior:** [What you expect to happen]
Atom opens up with the provided file being open.

**Actual behavior:** [What actually happens]
Atom opens up empty (with an 'untitled' new file ready for writing).

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.1

### Additional Information
*starting with the -d or --safe flags seems to work. 
*Removing the ~/.atom directory and re-installing atom from scratch doesn't help. 
*Disabling all community packages doesn't help, here is the list of packages I have installed:

highlight-selected@0.13.1
language-log@1.8.0
minimap@4.29.6
minimap-find-and-replace@4.5.2
minimap-highlight-selected@4.6.1
react-snippets@0.9.0

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lee-dohm** [comment] 2017-08-25 13:57
@cetkovic I can't reproduce the behavior you're describing using Atom v1.19.2 on Mac OS X 10.12.6.

Since this was opened without a template and @cetkovic's issue description seems to say that Safe Mode works, I'm going to close this as not being able to be reproduced. If any of you continue to have this problem, please open a new issue by filling out the template and including as much information as you can, probably including the contents of your `config.cson`.

**Closed by lee-dohm** 2017-08-25 13:57 UTC
Labels: more-information-needed
