### ISSUE TITLE
Shortcut is created on desktop

### ISSUE THREAD

**Issue by jaoord** [atom/atom#10371] opened 2016-01-11 12:28 UTC
I opened a folder in Atom, which caused Atom to start a new instance of atom. At the same time, a new icon appeared on my Windows desktop pointint to atom

**Steps which explain the enhancement**

1. Open Atom
2. Go to File > Open Folder ... and choose a folder
3. Atom opens again, and an icon appears on the desktop

**Current and suggested behavior**

I don't want programs to automatically add icons to my desktop. If i want a desktop icon for Atom, it can ask me during setup, but after that it should not automatically add icons to my desktop.

**Why would the enhancement be useful to most users**

The current behavior is erratic and annoying.

**Atom Version:** 1.2.2
**OS and Version:** Windows 10

**Comment by 50Wliu** [comment] 2016-01-11 15:02
Hi @jaoord, thanks for reporting!  This seems to be a duplicate of #5323 - please subscribe there for updates.

**Closed by 50Wliu** 2016-01-11 15:02 UTC
