### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by d-Pixie** [atom/atom#14580] opened 2017-05-23 07:00 UTC
[Enter steps to reproduce:]

I don't know. I had saved a file, tabbed over to the second workspace on that monitor and tabbed back. When I came back the error was there. Hasn't happened before. Haven't installed anything new recently and the project I'm working on has been open in the editor for a few days ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:663:1)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:697:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:184:1)
    at /Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1
```

### Commands

```
  2x -2:06.7.0 core:backspace (input.hidden-input)
     -2:06.4.0 core:move-down (input.hidden-input)
  3x -2:06.2.0 core:move-right (input.hidden-input)
     -2:05.7.0 core:move-down (input.hidden-input)
  2x -2:05.4.0 core:backspace (input.hidden-input)
     -2:05.1.0 core:move-down (input.hidden-input)
  2x -2:05.0 core:move-right (input.hidden-input)
  2x -2:04.7.0 core:backspace (input.hidden-input)
 12x -2:03.9.0 core:move-right (input.hidden-input)
     -2:02.5.0 core:move-up (input.hidden-input)
     -2:01.8.0 core:move-left (input.hidden-input)
     -2:01.7.0 core:move-up (input.hidden-input)
  5x -2:01.2.0 core:select-right (input.hidden-input)
 22x -1:58.8.0 core:move-left (input.hidden-input)
  5x -1:56.2.0 core:backspace (input.hidden-input)
     -1:54.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-elixir 1.5.14 
busy-signal 1.4.1 
copy-as-rtf 0.9.3 
copy-with-style 1.1.0 
file-types 0.5.5 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.61.0 
language-docker 1.1.7 
language-elixir 0.17.0 
language-javascript-jsx 0.3.7 
language-pug 0.0.21 
language-slim 0.5.0 
language-vue 0.21.2 
linter 2.1.4 
linter-docker 0.2.0 
linter-elixirc 1.6.0 
linter-jsonlint 1.3.0 
linter-pycodestyle 2.0.2 
linter-rubocop 2.1.1 
linter-ui-default 1.5.4 
railscast-theme 0.3.0 
red-wavy-underline 0.3.3 
Stylus 3.1.0 
```

**Comment by Ben3eeE** [comment] 2017-05-23 08:40
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #11692. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-05-23 08:40 UTC
