### ISSUE TITLE
TextEditor.getPath only providing realpath

### ISSUE THREAD

**Issue by dirk-thomas** [atom/atom#9879] opened 2015-11-30 21:29 UTC
Currently `TextEditor.getPath` returns the realpath of the file. When a project directory contains symlinks somewhere under it it becomes impossible to decide which project root a specific file belongs to. Please see noseglid/atom-build#245 for a longer explanation of the use case as well as an example folder hierarchy.

The only way to make a correlation between a TextEditor and a project root requires the TextEditor to provide the non-real path of the file.

Getting the realpath from the non-real path is trivial (`fs.realpath())`) but the other way around is simply not possible.

**Comment by thedaniel** [comment] 2015-12-03 13:52
@atom/feedback thoughts on this? I'm not familiar with a foolproof way to associate a TextEditor to a project path - I can see the benefit of adding a getter for something like `nonRealPath` / `literalPath` (naming is hard), or perhaps even better, a method that returns the project root, if any, that the file in the editor belongs to. My gut tells me that a lot of people are inferring project root from the file path.. i certainly have in packages before.

**Comment by lee-dohm** [comment] 2015-12-03 15:00
If we could get the project root and project-relative path (both I think would be useful in other contexts too) from a `TextEditor`, that should fix this issue I think?

But this is going to be a really, really deep rabbit hole, I feel. The problem is that there can be an infinite number of paths that can reach a file. Should the `TextEditor` instance have to know about all of them? What if one of the `n` paths changes after the `TextEditor` is created? Say one of the non-real (imaginary?) paths to the file in question is `a/foo/c.txt` and gets renamed to `a/bar/c.txt`. Do we have to have file watchers on everything to manage this?

**Comment by maxbrunsfeld** [comment] 2015-12-03 22:50
I agree with @dirk-thomas that we should simply *not* compute the real path, and leave that to the caller. Does anyone know of circumstances where that would break things in a way that wasn't trivially fixable?

**Comment by lee-dohm** [comment] 2015-12-04 01:17
> Does anyone know of circumstances where that would break things in a way that wasn't trivially fixable?

I'm pretty sure it was this way to begin with (because it was easier), but it changed for some reason ¯\_(ツ)_/¯ I'll see if I can backtrace it.

**Comment by lee-dohm** [comment] 2015-12-04 02:42
So I devised a test just to see how consistent this is:

1. Created a new repository `lee-dohm/test-atom-9879`
1. Created a directory `real-dir` inside it
1. Created a symlink to `real-dir` named `fake-dir`
1. Created a file inside `real-dir` named `test.md`

Then I attempted to open `test.md` in multiple ways from both `real-dir` and `fake-dir` and recorded their `getPath()` result with the command: `atom.workspace.getActiveTextEditor().getPath()`. Here are the results:

* `real-dir/test.md`
    * Open from tree-view: `/Users/Lee/Source/test-atom-9879/real-dir/test.md`
    * Open from fuzzy-finder: `/Users/Lee/Source/test-atom-9879/real-dir/test.md`
    * Open from <kbd>Cmd+O</kbd>: `/Users/Lee/Source/test-atom-9879/real-dir/test.md`
    * Open via drag-and-drop: `/Users/Lee/Source/test-atom-9879/real-dir/test.md` (New window appears)
* `fake-dir/test.md`
    * Open from tree-view: `/Users/Lee/Source/test-atom-9879/real-dir/test.md`
    * Open from fuzzy-finder: **Does not show up in list**
    * Open from <kbd>Cmd+O</kbd>: `/Users/Lee/Source/test-atom-9879/real-dir/test.md`
    * Open from drag-and-drop: `/Users/Lee/Source/test-atom-9879/real-dir/test.md` (New window appears)

Ok, 100% consistent. Which tells me that the code for all of this is almost assuredly in one place ... most likely the opener mechanism.

So then I delved into the Wayback Machine and followed the opener code all the way back to November 2013. As far as I can see, the opener code (which migrated between `Project` and `Workspace` over the span) has always* called `Project::resolvePath` or `Project::resolve` on the path passed to it. And the `resolve` twins have always* called `fs.absolute()` on the path passed to them. Which you can still see here:

https://github.com/atom/atom/blob/2696f493852a265e21c6e326ca963bf947625314/src/project.coffee#L212-L219

So I was wrong and completely fabricated my previously mentioned memory.

Now, where does that leave us? Well, it appears that `Project::resolvePath` has never been part of the public API and [`Project::resolve` was deprecated back on January 9th, 2015.](https://github.com/atom/atom/commit/d26c19a0ec9a4c807b37995970c6ba83782189c1) So at least we don't have to worry about third-party packages depending on this as an API. *But* since TextEditors have always* returned absolute paths ... we may want to be careful about breaking that implicit contract.

* For values of "always" back to November 2013

**Comment by dirk-thomas** [comment] 2015-12-05 20:03
I do understand that changing the existent behavior is risky. But do we agree that we should somehow expose the non-realpath with a different method (however clumsy the name might be)?

Regarding the `absolute()` function in `fs-plus`: I find it rather unintuitive that it resolves symlinks. Based on how similar functions in other languages work (e.g. in Python: https://docs.python.org/3/library/os.path.html#os.path.abspath) I expect the function to:

* prefix a relative path with a "cwd"
* collapse `..` within the path (normalize `X/path/../Y` to `X/Y`)
* replace stuff like `~`

But I would not expect the function to perform a `realpath()`.

**Comment by lee-dohm** [comment] 2015-12-05 20:33
> But do we agree that we should somehow expose the non-realpath with a different method (however clumsy the name might be)?

Sure, we should. The question is *when*? Is this no big deal and we can take it now? Or is it something that should wait until v2.0?

**Comment by dirk-thomas** [comment] 2015-12-05 22:18
Obviously I would like to have the feature rather sooner then later :wink: in order to actually make the build commands (referenced in the description) work. Without this feature there is simply no way to make it work for projects with symlinks. Out of curiosity: what is the rough time frame for Atom 2.0? 

Let me try to describe what changes would be required (also for me to understand the Atom internals a bit better) and what that might affect:

* Modify [Project.resolvePath()](https://github.com/atom/atom/blob/0896142ea2adf85d90fa1c97e6b19e90b304f0c2/src/project.coffee#L206) to return non-realpath but normalized absolute path instead.
* Consider the current usage of the function:
  * [Project.isPathModified()](https://github.com/atom/atom/blob/0896142ea2adf85d90fa1c97e6b19e90b304f0c2/src/project.coffee#L305-L306) depends on what `Buffer.getPath()` returns. If it will return a non-realpath nothing needs to be done. Otherwise `Project.isPathModified()` needs to invoke realpath on the argument before passing it to `findBufferForPath()`.
  * [Project.bufferForPathSync()](https://github.com/atom/atom/blob/0896142ea2adf85d90fa1c97e6b19e90b304f0c2/src/project.coffee#L312-L315) same as for the previous bullet.
  * [Workspace.open()](https://github.com/atom/atom/blob/master/src/workspace.coffee#L407-L425) this is where we actually want the non-realpath since from here the uri / path gets passed throughout the pipeline until it ends up in the `TextEditor`.
    * The function also determines if the file is already open in a pane (`itemForURI()`). This is based on `TextBuffer.getUri()` which uses `getPath()`. If `getPath()` continues to return a realpath the argument to `itemForURI()` needs to be a realpath.
  * [Workspace.openSync()](https://github.com/atom/atom/blob/master/src/workspace.coffee#L445-L459) same as for the previous bullet.
  * [Workspace.openTextFile()](https://github.com/atom/atom/blob/master/src/workspace.coffee#L502-L523) calls `fs.getSizeSync()` which might need a realpath (?).
  * Is there a way to find out if other code invokes this non-public API?
* Modify `TextEditor.getPath()` to call `realpath()` before returning the value and introduce a new method `TextEditor.getNonRealPath()`.

If we ensure that existing API like `TextEditor.getPath()` or `TextBuffer.getPath()` still return the same realpath as before this might be a backward compatible change? I am happy to hear your thoughts...

**Comment by dirk-thomas** [comment] 2015-12-20 22:34
It would be great if someone could provide guidance regarding my proposed changes. I am happy to work on a patch if the direction is clear.

**Comment by 50Wliu** [comment] 2015-12-22 01:51
Was going through a few old issues and noticed this one that seemed really similar: #3110.

**Comment by dirk-thomas** [comment] 2016-01-13 00:10
ping :wink:

**Comment by joefitzgerald** [comment] 2016-01-29 04:53
@50Wliu yep, this is exactly what #3110 is about. I'm going to close it in deference to this.

**Comment by dirk-thomas** [comment] 2016-09-07 23:53
I have updated #10856 to provide additional API exposing the non-realpath. The existing API should not change behavior (except that a TextBuffer now internally stores the non-realpath). Any feedback is welcome.

**Comment by maxbrunsfeld** [comment] 2017-01-05 00:49
This will be fixed in Atom 1.14. We'll preserve whatever path the project was initialized with. Sorry for the very very long turnaround time.

**Closed by maxbrunsfeld** 2017-01-05 00:49 UTC
Labels: api, atom

**Comment by dirk-thomas** [comment] 2017-01-05 00:55
:+1: for supporting this with the current API without the need for additional API.
