### ISSUE TITLE
Overlapping button and checkbox. OS X 10.11.3

### ISSUE THREAD

**Issue by dustindowell22** [atom/atom#11117] opened 2016-03-09 19:01 UTC
![error](http://cl.ly/2a003f1Z1T3j/error.png)

A "Hide Extension" check box is hidden underneath the new folder button.

I'm not sure if this is an Atom bug or an OS X bug. But I've only ever seen it in Atom. I'm not sure when it first appeared but I just noticed it today.

To reproduce, just right click the left sidebar and click "Add Project Folder".

OS X 10.11.3
Atom 1.5.4

**Comment by dustindowell22** [comment] 2016-04-06 15:26
Just a note, this is still present with

OS X 10.11.3
Atom 1.6.1

**Comment by 50Wliu** [comment] 2016-04-15 00:25
Closing as a duplicate of #9949.

**Closed by 50Wliu** 2016-04-15 00:25 UTC
Labels: blocked, electron, mac, needs-reproduction
