### ISSUE TITLE
Remapping 'pane:show-next-recently-used-item' to cmd+<another key> behaves differently then the default

### ISSUE THREAD

**Issue by scottdarch** [atom/atom#16849] opened 2018-02-27 16:47 UTC
### Description

To prevent the ligament damage that ctrl+tab on a macbook pro causes I always remap my editor switching commands in IDEs to CMD+2. When I did this in atom the "show next recently used item" pane doesn't dismiss after releasing the cmd key as it does when you release the ctrl key.

### Steps to Reproduce

1. create the following key remap on OSX sierra or high sierra.

```
'body':
  'cmd-2': 'pane:show-next-recently-used-item'
```
2. In an editor press "cmd+2"

**Expected behavior:** The same behavior as the default `ctrl+tab` action which is the "show-next-recently-used-item" pane appears and remains open while the ctrl key is held. Then the pane automatically goes away when the ctrl key is released.

**Actual behavior:** The "show-next-recently-used-item" pane remains visible (with lightbox) until escape is pressed (Keyboard focus is in the editor behind the panel making for some neat side-effects as one tries to hit "enter" to dismiss the dialog).

**Reproduces how often:** always

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.11
git 2.7.4

**Comment by rsese** [comment] 2018-02-28 00:32
Thanks for the report!

This seems like a duplicate of https://github.com/atom/atom/issues/16259 I think so you can subscribe there for updates if you'd like (let me know if I'm wrong @Ben3eeE :v:).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-02-28 00:32 UTC

**Comment by thirtytwobits** [comment] 2018-03-14 17:02
I looked through #16259 but I don't think this is the same thing. This is about the dialog not getting dismissed not anything about the effectiveness of the keybinding. The keybinding works fine it's that the dialog doesn't go away when cmd is released.

**Comment by Ben3eeE** [comment] 2018-03-14 17:26
@thirtytwobits Does the workaround mentioned in https://github.com/atom/atom/issues/16259#issuecomment-356637631 resolve the issue for you?

**Comment by Ben3eeE** [comment] 2018-03-14 17:29
Can you share your keymap? This could be because there is no `cmd-2 ^cmd` keybinding for `'pane:move-active-item-to-top-of-stack'` and not a duplicate of #16259

**Comment by scottdarch** [comment] 2018-03-14 20:03
Holy crud! That works! Thank-you so much!

```
'body':
  'cmd-2': 'pane:show-next-recently-used-item'
  'cmd-2 ^cmd': 'pane:move-active-item-to-top-of-stack'
```
