### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by darkrsw** [atom/atom#20779] opened 2020-05-22 06:44 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:160

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778162)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778264)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778390)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1081110)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1253631)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1251616)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284744)
```

### Commands

```
     -0:23.4.0 tree-view:add-file (span.name.icon.icon-file-directory)
  4x -0:18.8.0 editor:consolidate-selections (input.hidden-input)
     -0:10.4.0 tree-view:add-file (span.name.icon.icon-file-directory)
  3x -0:05.1.0 editor:consolidate-selections (input.hidden-input)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
auto-detect-indentation 1.3.0 
convert-to-utf8 0.2.4 
hard-wrap 1.7.1 
highlight-line 0.12.0 
highlight-selected 0.17.0 
ide-rust 0.22.0-beta.3 
jekyll 2.1.0 
jekyll-snippets 0.3.2 
jekyll-syntax-highlighting 0.1.0 
language-latex 1.2.0 
language-rust 0.4.12 
language-scala 1.1.10 
latex 0.50.2 
latex-completions 0.3.6 
markdown-pdf 2.3.3 
markdown-writer 2.11.10 
minimap-pigments 0.2.2 
pigments 0.40.2 
pp-markdown 0.0.2 
runtime-info-atom 1.0.0 
save-workspace 0.5.0 
sbt 0.13.0 
```

**Comment by brunosmm** [comment] 2020-05-22 11:10
I am experiencing the same error after I set an npm ca globally to fix an npm error when installing plugins:

```
verbose node v10.2.1
verbose npm  v6.2.0
error code SELF_SIGNED_CERT_IN_CHAIN
error errno SELF_SIGNED_CERT_IN_CHAIN
error request to https://codeload.github.com/wooorm/linter-remark/legacy.tar.gz/v8.0.0 failed, reason: self signed certificate in certificate chain
verbose exit [ 1, true ]
```
Comand to set cafile:
`npm config -g  set cafile "/path_to.pem"`

**Comment by sadick254** [comment] 2020-09-01 16:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-01 16:16 UTC
