### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 21Error: Cannot call...

### ISSUE THREAD

**Issue by ethomps2** [atom/atom#17503] opened 2018-06-12 17:12 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 21
Error: Cannot call function 'getPosition' on missing remote object 21
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 21
Error: Cannot call function 'getPosition' on missing remote object 21
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowResize (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:195:32)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:175:22)
    at WebViewImpl.onElementResize (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:159:10)
```

### Commands

```
     -2:34.1.0 core:backspace (input.hidden-input)
     -2:33.8.0 core:move-left (input.hidden-input)
     -2:33.2.0 core:backspace (input.hidden-input)
     -2:19.2.0 core:save (input.hidden-input)
     -2:02.7.0 core:backspace (input.hidden-input)
     -1:57.8.0 core:save (input.hidden-input)
  4x -1:42.8.0 core:backspace (input.hidden-input)
     -1:39.8.0 editor:newline (input.hidden-input)
     -1:38.1.0 snippets:next-tab-stop (input.hidden-input)
     -1:38.1.0 snippets:expand (input.hidden-input)
     -1:38.1.0 editor:indent (input.hidden-input)
     -1:36 core:move-down (input.hidden-input)
     -1:33.3.0 core:move-up (input.hidden-input)
     -1:32.8.0 snippets:next-tab-stop (input.hidden-input)
     -1:32.8.0 snippets:expand (input.hidden-input)
     -1:32.8.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-ternjs 0.18.3 
auto-update-packages 1.0.1 
autocomplete-modules 2.0.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
git-plus 7.10.2 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
react 0.18.0 
react-snippets 1.1.1 
```

**Comment by steveward** [comment] 2018-06-12 17:49
:wave: Thanks for opening this @ethomps2.

This looks like a duplicate of #16630 so you can subscribe there for updates if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by steveward** 2018-06-12 17:49 UTC
