### ISSUE TITLE
Make control + arrow keys (move to beginning/end of word shortcut) not move to end of periods or commas

### ISSUE THREAD

**Issue by sn0wyfall** [atom/atom#13953] opened 2017-03-07 19:03 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

So, I couldn't find a package which did this.

Essentially, the `control + right/left arrow` (or `alt + right/left arrow` if you're on a Mac) allows you to go to the end or beginning of the word. I think that's well-known. However, for some reason, Atom works a bit differently.

This is what happens in Atom as you press the `alt + right arrow` shortcut in a line (the `|` is the cursor)

    |if 20,000

    if| 20,000

    if 20|,000

    if 20,|000

    if 20,000|

So, as you can see, the cursor stops at the comma. However, this is much different to how it works in other apps. I tested it in Pages, TextEdit, Safari, as well as a bunch of other third-party apps, and they all work like this:

    |if 20,000

    if| 20,000

    if 20,000|

Simple and easy to use.

So, why do I want Atom to change its behavior to the second way instead of using its current method? Because it makes text editing and going to other places within a line *extremely annoying.* You *always* have to keep pressing `alt + right` to go somewhere, and sometimes this problem makes navigating as slow as having to press the right arrow key on its own, which is a real bummer.

Is the comma the only character that causes this to happen? No, there is also `.` and `'`. One this about the single quote `'`. Additionally, there's another problem: `alt + backspace` (or `control + backspace`) also stops at these characters. That means that if you want to backspace the word `don't` in Atom, you need to press `alt + backspace` three times, whereas virtually in app other than Atom this shortcut only needs to be pressed once. You have the same problem with text selection via `alt + shift + arrow key` as well, making text editing in Atom a burden in general.

This is why I honestly think that this behavior should be changed.

### Versions

macOS 10.12.3

Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.1

### Additional Information

None

**Comment by rsese** [comment] 2017-03-07 19:14
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/13651?  If I'm mis-understanding, let me know.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-07 19:14 UTC

**Comment by sn0wyfall** [comment] 2017-03-08 09:18
@rsese Thank you. Yes, it seems like it's related to that issue in a way, and the way you handle duplicates I think this issue could be considered a duplicate of that one. I didn't find that other issue probably because I searched up `control + arrow` instead of `alt + arrows`.

**Comment by rsese** [comment] 2017-03-08 17:57
No problem at all, we have a large number of open issues so it's definitely not always straightforward to find the things you're looking for :v:
