### ISSUE TITLE
Using pipes with the atom command in a shell should open a new atom window or tab with the piped output.

### ISSUE THREAD

**Issue by SarenCurrie** [atom/atom#11703] opened 2016-05-05 22:16 UTC
This would be useful for browsing the output of a long running command in atom.

**Steps which explain the enhancement**

1. Run some command in a terminal which produces a lot of output.
eg: `ps aux`
2. Pipe the output into atom.
`ps aux | atom`
3. The output should now appear in atom

**Current and suggested behavior**

Currently doing this opens a new empty window.

I've confirmed that this feature works in Textmate but surprisingly, not in any tty editors.

**Atom Version:** 1.7.3
**OS and Version:** Mac OSX 10.10.5

**Comment by 50Wliu** [comment] 2016-05-05 22:35
This is a duplicate of #1729 - feel free to subscribe there for updates.
In addition you might want to subscribe to #11184 which aims to implement the behavior you're asking for.

**Closed by 50Wliu** 2016-05-05 22:35 UTC

**Comment by SarenCurrie** [comment] 2016-05-05 22:37
Cheers, sorry.
