### ISSUE TITLE
File --> Open... not functional after closing editor Window (OS X)

### ISSUE THREAD

**Issue by sijpkes** [atom/atom#12508] opened 2016-08-25 01:02 UTC
In Atom version 1.9.9 on OS X, when you try to open a Project from the File menu after closing the editor window, the FInder file selection pane does not pop-up as expected.  

To reproduce this:
1. Open Atom
2. Close the main 'untitled' window
3. Try to Open a project or Add a project folder

The Atom menu bar remains open after closing the main window after launch, so you would assume that you could Open... a new project from the menu and I'm sure this used to work in version 1.8.x. 

Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by mydesignwrexham** [comment] 2016-08-26 09:39
The way I am getting round this is to click **new file** > **Open**

**Comment by archcorsair** [comment] 2016-09-15 06:27
Another simple workaround for the time being:
Clicking on the atom icon in your dock brings up a **new window**
From here you should be able to **open** a file/folder.

**Comment by clajiness** [comment] 2016-09-15 13:42
Do we have any confirmation that this is being treated as a bug, and not some new default behavior?

**Comment by Ben3eeE** [comment] 2016-09-15 13:45
@clajiness Since this issue is labeled bug I would assume that it is indeed a bug and not a new default behavior.

**Comment by stottsan** [comment] 2016-10-08 15:34
Experiencing this in 1.10.2, also, with behavior identical to #12721.

**Comment by Zmaon** [comment] 2016-10-12 08:19
Still the case in 1.11.1

**Comment by mrpunkin** [comment] 2016-11-10 22:44
Still the case in 1.12.0

**Comment by pcate-fls** [comment] 2017-01-23 15:43
Still happening in 1.13.0

**Comment by gopsmith** [comment] 2017-02-03 15:35
Still happening in 1.13.1 on MnacOS 10.12.3

**Comment by archcorsair** [comment] 2017-02-10 19:53
Still happens in 1.14.1 on MacOS 10.12.13

**Comment by deitch** [comment] 2017-02-23 09:43
Confirm still happening in 1.14.3 on macOS 10.12.13

**Comment by jheasly** [comment] 2017-03-13 19:31
Still happening in 1.15.0 on Mac OS X 10.9.5.

**Comment by discentem** [comment] 2017-04-12 23:45
Still an issue :(

**Comment by robzenn92** [comment] 2017-05-24 23:52
Still happening in 1.17.1 on MacOS Sierra 10.12.5.

**Comment by sijpkes** [comment] 2017-05-25 01:04
Yes me too, just unintuitive. Atom is an awesome editor, so it's a minor
irritation!

**Comment by brunnopleffken** [comment] 2017-05-26 20:01
As mentioned by @rsese, I think my issue is related to this one.

1. Close the current window (on Mac we can close all windows without quitting the app).
2. Go to File > Reopen Project > Select any directory...

**Expected behavior:** Selecting a project with all windows closed in Mac should automatically open a new window and load the selected project in it.

**Actual behavior:** Nothing happens. I need to open a new window and then go to File > Reopen Project.

### Versions

macOS Sierra 10.12.5 on MacBook Pro Retina 13" Late-2013
Atom : 1.17.2
Electron: 1.3.15
Chrome : 52.0.2743.82
Node : 6.5.0

---
A possible solution: "Reopen Project" and related tasks - such as "File > Open" and "Add Project" - may check if platform is 'darwin' and if a window exists. If not, then automatically open a new window BEFORE executing the actual task.

**Comment by tyleranton** [comment] 2017-06-27 16:03
I'd like to take this bug on. I'm assuming the appropriate area to work on this is [here](https://github.com/atom/atom/blob/master/src/reopen-project-menu-manager.js)?

> A possible solution: "Reopen Project" and related tasks - such as "File > Open" and "Add Project" - may check if platform is 'darwin' and if a window exists. If not, then automatically open a new window BEFORE executing the actual task.

Is this an acceptable solution?

**Comment by lee-dohm** [comment] 2017-06-28 17:30
@tyleranton The described solution is valid yes. The "area to work on" is not. That's code having to do with the reopen project menu item and wouldn't be appropriate for placing code in to solve this problem.

**Comment by discentem** [comment] 2017-06-29 01:07
Where would the correct section of code be, if you could give any hints?

**Comment by lee-dohm** [comment] 2017-07-05 16:04
@discentem Wherever the rest of the "File > Open" code is?

**Comment by discentem** [comment] 2017-07-05 16:09
@lee-dohm I assumed you might have familiarity with the location of the code :P

**Comment by russell07** [comment] 2017-10-15 15:26
Issue still exists in 1.21.0

**Comment by duncanmalashock** [comment] 2017-10-15 23:18
Issue still exists in 1.21.1. Atom is an awesome editor – it's sad that this bug has been open for more than a year!

**Comment by lee-dohm** [comment] 2017-10-16 14:44
@duncanmalashock comments such as yours are insulting to the maintainers and contributors to Atom, in essence you're saying that all their hard work for the past year is worthless because they didn't fix this one bug that annoys you. And since being insulting or derogatory are explicitly against the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md), you may consider this an official warning.

One thing to consider is that Atom is open source and that everyone has the ability to submit fixes for issues such as this.

**Comment by duncanmalashock** [comment] 2017-10-16 14:57
@lee-dohm I think you're reading too much into my comment, because that's not at all what I'm saying. I appreciate everyone's work on Atom.

I work on software too, and believe me, there are some bugs in my team's codebase that are sad also, that we should fix! But to say so isn't an insult to us, or to say our work is worthless. Far from it.

In any case, I hope this clarifies my sentiment, and I certainly didn't mean for anyone to take my comment personally.

**Comment by thebigreason** [comment] 2017-11-22 17:30
Still having this problem in 1.22.1

Atom : 1.22.1
Electron : 1.6.15
Chrome : 56.0.2924.87
Node : 7.4.0
OS : macOS High Sierra 10.13 (17A365)

**Comment by jeffdaley** [comment] 2017-12-14 14:21
Still broken in 1.23.1.

**Comment by TonyLianLong** [comment] 2017-12-23 08:53
I guess it's because commands such as application:reopen-project here could not be executed when no window is open.

**Comment by louisgjohnson** [comment] 2018-03-27 22:47
Still having the issue in 1.25.0

**Comment by yasirmturk** [comment] 2018-03-29 04:02
still an issue on 1.25.0 x64 high sierra 10.13.3

**Comment by breadadams** [comment] 2018-06-09 13:06
Still occurring on 1.27.2, macOS 10.13.4

_(subscribing for updates)_

**Comment by karevn** [comment] 2018-06-18 17:59
Guys.... Please test my fix for it. https://github.com/atom/atom/pull/17529

**Comment by mattdiamond** [comment] 2018-11-01 17:47
How has this bug not been fixed yet? Yes, there's a simple workaround, but it's ridiculous that something as basic as "opening a project when no windows are open" is currently impossible. This is core functionality that doesn't work!

Seriously, this belongs in the Software Hall of Are You Fucking Kidding Me alongside "GitHub code search doesn't support special characters" and "Reddit's mobile app silently hides comments". Could someone who works on Atom take 30 minutes out of their day and fix this? You don't even have to code a fix from scratch... @karevn already did most of the work for you!

**Comment by mattdiamond** [comment] 2018-11-01 19:34
Sorry, I'll try to express this in a more productive way:

I am disappointed that a bug this fundamental has yet to be fixed after more than 2 years. I understand that projects like Atom have an enormously complex codebase, but @karevn's PR suggests that fixing this bug does not require a significant amount of work. I have difficulty understanding why this has not been addressed, especially since Atom is an active project and significant resources have been directed toward building new features and improving existing ones. As a software developer, I know all too well the issue of technical debt and the difficulty of prioritizing bug-fixes, but this bug is so fundamental to the operation of Atom -- it involves the ability to open files -- that it could plausibly be considered a Blocker on a new release. I simply don't understand why this bug was not prioritized at any point in the past 2 years.

**Comment by lee-dohm** [comment] 2018-11-01 19:42
Thanks @mattdiamond. I've brought your feedback directly to the development team.

**Comment by nicbarker** [comment] 2018-11-01 22:38
Update for everyone subscribed:
@karevn has created a PR to fix this one, it's currently in review, status according to this comment:
https://github.com/atom/atom/pull/17529#issuecomment-435178178

> lee-dohm commented 2 hours ago
> @makingoff @daviwil is on parental leave for the time being. We've got this in the queue for prioritization.

Looks like a fix is incoming relatively soon, pending @daviwil coming back from parental leave.

**Comment by movingobjects** [comment] 2018-11-30 00:33
Still present in 1.33.0 (macOS 10.14.1), and tripping me up several times every day.

**Comment by mattaningram** [comment] 2019-01-04 17:47
Uhhhh, what is going on with this issue? I am using Atom for a project (I switched to VSCode a while back because of issues like this) and I can't believe this is still not fixed over a year later.

**Comment by mrpunkin** [comment] 2019-01-04 17:58
Yeah this is crazy. How is this a non-priority issue? You all have had a PR ready for like 6 months now it seems and in the meantime the guy who submitted the PR has moved on to other software. 

Is there really only one person on the Atom team that can handle reviewing this @lee-dohm?

**Comment by kevineleven** [comment] 2019-01-17 21:48
Just going to be the latest to chime in about this. Fix greatly appreciated soon.

MacOS 10.13.4
Atom 1.34.0

**Comment by daviwil** [comment] 2019-02-07 23:48
This issue has been resolved by @karevn's PR https://github.com/atom/atom/pull/17529 and will be included in Atom 1.36.0-beta0 to be released sometime next week.

**Closed by daviwil** 2019-02-07 23:48 UTC
Labels: bug, help-wanted, mac, triaged

**Comment by movingobjects** [comment] 2019-03-13 21:38
(Atom `1.35.1`) So glad **File -> Open...** was fixed, but **File -> Reopen Project** still doesn't do anything if there isn't a window already open. 😕

**Comment by brunnopleffken** [comment] 2019-03-13 22:25
Confirmed. Although "Open" is fixed and working, "Reopen Project" and select a folder from the list don't do anything.

**Comment by 50Wliu** [comment] 2019-03-15 20:37
@movingobjects @brunnopleffken can one of you two please open a new issue so that we can track this? Thanks!

**Comment by movingobjects** [comment] 2019-03-15 20:45
@50Wliu This item has an issue (https://github.com/atom/atom/issues/17530), but looks like you had marked it as a duplicate of this ticket. 😬 Can we just reopen that one?

**Comment by 50Wliu** [comment] 2019-03-17 18:15
Yeah, that works :).

**Comment by mitchiru** [comment] 2019-04-25 11:05
+1

**Comment by birdguts** [comment] 2020-04-29 11:37
still present lol
