### ISSUE TITLE
Indent error on non-bracketed single statements code with C-look-alike languages.

### ISSUE THREAD

**Issue by lhartmann** [atom/atom#18117] opened 2018-09-26 17:19 UTC
Write the code below, copy and paste thrice.

```
if (false)
  continue;
```

What happens: Atom will indent badly, the following statements look nested.

```
if (false)
  continue;
  if (false)
    continue;
    if (false)
      continue;
      if (false)
        continue;
```

What should happen: Indent as properly, following statements are NOT nested.

```
if (false)
  continue;
if (false)
  continue;
if (false)
  continue;
if (false)
  continue;
```

**Comment by rsese** [comment] 2018-09-26 22:34
Thanks for the report!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/5473 so you can subscribe there for updates if you'd like.  For future issues, it would be super helpful if you fill out the issue template, the information in the template is very helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-09-26 22:34 UTC
