### ISSUE TITLE
Uncaught Error: spawn /Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7X...

### ISSUE THREAD

**Issue by danmork** [atom/atom#9630] opened 2015-11-16 16:05 UTC
1. Selected "Add Project Folder..." from the menu.

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:132:14)
    at /Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:822:44
    at Emitter.module.exports.Emitter.emit (/Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Project.module.exports.Project.addPath (/Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at /Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:847:41
    at EventEmitter.<anonymous> (/Users/danmork/Library/Application Support/com.github.atom.ShipIt/update.7XMoQIi/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
```

### Commands

```
  6x -5:49.1.0 core:select-right (atom-text-editor.editor.mini.is-focused)
     -5:40.5.0 core:save (atom-text-editor.editor.is-focused)
     -5:35.7.0 tree-view:move (li.file.entry.list-item.status-added.selected)
     -5:33.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -5:32.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:28.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:49.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:45.9.0 core:save (atom-text-editor.editor.is-focused)
     -4:19.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:19.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:09.7.0 core:save (atom-text-editor.editor.is-focused)
     -3:15 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:09.3.0 core:undo (atom-text-editor.editor.is-focused)
  2x -3:02.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:34.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:18.2.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 18
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-16 17:12
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-16 17:12 UTC
