### ISSUE TITLE
Autoupdate doesn't work well if Atom is owned by root on Mac.

### ISSUE THREAD

**Issue by scv119** [atom/atom#8720] opened 2015-09-08 23:24 UTC
I have Atom.app installed in /Application/Atom.app and it's owned by root but readable and executable by all users.

When I first launched, I got a request to install a helper application to keep it up to date. 
I did so, and it told me to quit and relaunch.  
The next relaunch asked me the same question, and caused Atom to crash and close.  I reopened it again and it had finally updated, but now I see two entries in the "Open with..." menu:

![screen shot 2015-09-02 at 11 27 57 am](https://cloud.githubusercontent.com/assets/837180/9749879/fdad3b50-5645-11e5-99f9-3095f618465a.png)

**Comment by scv119** [comment] 2015-09-24 00:02
Some error logs after click the `Restart and install` in /var/log/system.log 
```
Sep 23 16:57:06 chenshen-mbp2.dhcp.thefacebook.com ShipIt[92506]: ShipIt quitting
Sep 23 16:57:06 chenshen-mbp2 com.apple.xpc.launchd[1] (com.github.atom.ShipIt[92506]): Service exited with abnormal code: 1
Sep 23 16:57:06 chenshen-mbp2 com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Sep 23 16:57:08 chenshen-mbp2.dhcp.thefacebook.com ShipIt[92510]: Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo=0x7fa1a50351a0 {NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fa1a50330c0 "The file “ShipItState.plist” couldn’t be opened because there is no such file."}
```

**Comment by 50Wliu** [comment] 2015-09-24 00:30
That error looks similar to #6397 - is that the same issue?
As far as your Open With bug goes, that's a duplicate of #1720.

**Comment by WardsParadox** [comment] 2015-09-25 03:36
@50Wliu I can confirm that the same issue mentioned in #6397 still occurs in 1.0.16, at least in terms of the Console bombardment of ShipIt failures.

**Comment by 50Wliu** [comment] 2015-09-26 16:44
Closing in favor of #6397.

**Closed by 50Wliu** 2015-09-26 16:44 UTC
Labels: more-information-needed
