### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '$ATOM_HOME/packages/atom-beautify/README...

### ISSUE THREAD

**Issue by rifkytech** [atom/atom#18785] opened 2019-02-04 12:44 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 16.04.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/rifky/.atom/packages/atom-beautify/README.md'

```
At fs.js:646

Error: ENOENT: no such file or directory, open '/home/rifky/.atom/packages/atom-beautify/README.md'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Proxy.fs.readFileSync (fs.js:551:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at PackageDetailView.renderReadme (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:736817)
    at PackageDetailView.updateInstalledState (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:736577)
    at /snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:737448
    at Function.simpleDispatch (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:919667)
    at /snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:917076
    at r (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:11:911606)
    at o (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:1037724)
    at t.bufferStream (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:1037878)
    at Socket.e.on (/snap/atom/211/usr/share/atom/resources/app/static/<embedded>:14:1036480)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -5:00.4.0 core:confirm (input.hidden-input)
     -4:54 core:backspace (input.hidden-input)
     -4:53.2.0 core:confirm (input.hidden-input)
     -4:39.3.0 core:select-all (input.hidden-input)
  3x -4:38.6.0 core:backspace (input.hidden-input)
     -3:55.4.0 core:select-all (input.hidden-input)
     -3:54.7.0 core:paste (input.hidden-input)
     -3:34.9.0 command-palette:toggle (div.panels-item)
     -3:31 application:show-preferences (div.panels-item)
     -3:21.3.0 command-palette:toggle (input.hidden-input)
     -3:17.7.0 application:show-preferences (input.hidden-input)
     -3:13.8.0 core:paste (input.hidden-input)
     -2:07.5.0 core:select-all (input.hidden-input)
     -1:55.3.0 spell-check:correct-misspelling (div.line)
     -0:52.7.0 core:select-all (input.hidden-input)
     -0:20.6.0 styleguide:show (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
remote-ftp 2.2.2 
```

**Comment by rsese** [comment] 2019-02-04 23:21
Thanks for contributing!

We noticed that this looks like a duplicate of issues like https://github.com/atom/atom/issues/18656, so you can subscribe there for updates if you'd like.

If reinstalling the package doesn't help, please let us know in https://github.com/atom/atom/issues/18656.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-04 23:21 UTC
