### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by foxlg** [atom/atom#15984] opened 2017-10-24 20:48 UTC
Only open file and after try to save or using VIM keys for navigation. 
**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/partial-keyup-matcher.js:57

TypeError: Cannot read property '0' of undefined
    at PartialKeyupMatcher.getMatches (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/partial-keyup-matcher.js:42:105)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:375:91)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:01.8.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -1:00.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:59.8.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  2x -0:59.5.0 vim-mode-plus:undo (input.hidden-input)
     -0:57.1.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
  4x -0:56.6.0 vim-mode-plus:move-right (input.hidden-input)
     -0:55.7.0 vim-mode-plus:delete (input.hidden-input)
     -0:54.7.0 vim-mode-plus:set-register-name (input.hidden-input)
     -0:54.5.0 vim-mode-plus:set-input-char-w (input.hidden-input)
     -0:54 vim-mode-plus:move-to-first-character-of-line-down (input.hidden-input)
     -0:51.6.0 vim-mode-plus-ex-mode:open (input.hidden-input)
     -0:50.5.0 core:confirm (input.hidden-input)
  2x -0:38.8.0 core:close (input.hidden-input)
     -0:35.1.0 vim-mode-plus-ex-mode:open (input.hidden-input)
     -0:34.2.0 core:confirm (input.hidden-input)
     -0:16.6.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-django 0.3.2 
atom-runner 2.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
django-templates 0.5.0 
emmet 2.4.3 
file-icons 2.1.13 
git-plus 7.10.0 
intentions 1.1.5 
linter 2.2.0 
linter-flake8 2.2.1 
linter-python-pep8 0.2.0 
linter-ui-default 1.6.10 
Remote-FTP 1.2.6 
symbols-tree-view 0.14.0 
sync-settings 0.8.3 
terminal-fusion 2.4.4 
todo-show 2.1.0 
vim-mode-plus 1.11.6 
vim-mode-plus-ex-mode 0.10.1 
wakatime 7.0.3 
```

**Comment by rsese** [comment] 2017-10-25 00:07
Thanks for taking the time to contribute!

Though you don't have proton-mode installed, based on the stack trace I think this is a duplicate of https://github.com/atom/atom/issues/15851 (which was tagged as a dupe of https://github.com/dvcrn/proton/issues/286) and is fixed in Atom 1.22, currently in beta.  If you can reproduce in 1.22, please let us know.

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15851. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-25 00:07 UTC
