### ISSUE TITLE
renaming file doesn't always update tab title

### ISSUE THREAD

**Issue by bwiklund** [atom/atom#5833] opened 2015-03-04 05:11 UTC
The file's tab doesn't update if the change to the file name was only letter case, ie foo.coffee -> Foo.coffee.

I can't imagine this actually hurting anything but it's something I noticed.

**Comment by lee-dohm** [comment] 2015-03-04 05:22
It's possible that you're on a case-insensitive file system so the tab isn't notified of the change (if the file name changes at all).

**Comment by bwiklund** [comment] 2015-03-04 05:38
Yeah, that's possible. I tried digging into atom/atom, atom/tabs, and atom/tree-view, but couldn't track down the source of the relevant 'title-changed' event. This is on OSX 10.9.5 fyi.

**Comment by bwiklund** [comment] 2015-03-04 05:49
Also, for clarity, this is when renaming something from the tree-view, not simply renaming it from outside Atom.

**Comment by irodrigo17** [comment] 2015-05-04 17:41
Same here, running Atom 0.196.0 on OS X 10.10.3, the file was renamed from chapter14.hs to Chapter14.hs and the tab was not updated.

After seeing @lee-dohm's answer I remembered my file system is case insensitive :smile:

Just double checked and renaming the file from chapter14.hs to chapter15.hs does update the tab.

**Comment by lee-dohm** [comment] 2017-05-09 20:58
Whoops ... forgot to close this when we figured out what the root cause was 😊

**Closed by lee-dohm** 2017-05-09 20:58 UTC
Labels: invalid
