### ISSUE TITLE
[Enhancement idea] Support git-diff for files outside of current projects

### ISSUE THREAD

**Issue by aviatesk** [atom/atom#19584] opened 2019-06-21 12:27 UTC
## Summary

Support git-diff features for files under a directory that is not added for the current projects list.

## Motivation

`git-diff` packages currently shows diffs only for files in current projects.
I want to enhance this features so that it shows diffs for files outside of projects as well.

## Approach

This can be done by searching for git-repository recursively up from an opened file.
I found the existing [`GitRepository.open` API](https://atom.io/docs/api/v0.188.0/GitRepository#open) can do this job with a bit modification.

## Describe alternatives you've considered

As an API doc above says, using `GitRepository` directly is not considered as a proper way to access to git repository.
Even though I've done a small tweak to safely use `GitRepository.open` for this purpose on my local machine, we may want to switch to use `atom.project` global for searching a git repository for an opened file. (But sure this will make code more complex).

## Note

The basic change would be able to be done with this small modifications:
https://github.com/aviatesk/atom/commit/948dd1c064637e2a2997a60c26c62ef50d100dec

**Comment by rsese** [comment] 2019-06-21 18:22
Thanks for the suggestion @aviatesk!

This sounds like a duplicate of issues like https://github.com/atom/git-diff/issues/41 and https://github.com/atom/git-diff/issues/55; we're currently tracking this in a higher level issue at https://github.com/atom/github/issues/1835 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-21 18:22 UTC
