### ISSUE TITLE
Atom crashes on startup with certain git repository

### ISSUE THREAD

**Issue by steve9164** [atom/atom#10469] opened 2016-01-17 23:18 UTC
Atom crashes on startup with the message "The editor has crashed" when opening a certain repository. 

Some information:
- The OS is Windows 7
- This crash occurs with the latest Atom version as well as 1.5.0-beta0
- The crash occurs in normal and safe mode
- I was able to reproduce the issue by creating a new folder, cloning the repo
(https://github.com/TerriaJS/terriajs) and launching atom with `atom --safe terriajs/`

**Comment by davidvgalbraith** [comment] 2016-01-18 10:14
Works fine on Mac.

**Comment by steve9164** [comment] 2016-01-19 00:53
Here's a zip of the repo with files removed (only the .git folder remaining). Crashes on the command `atom --safe terriajs/`
[terriajs.zip](https://github.com/atom/atom/files/95175/terriajs.zip)

**Comment by 50Wliu** [comment] 2016-01-19 01:00
Confirmed on Windows 10 using Atom 1.6.0-dev-032a734.  This looks like an issue with Git (the `.git/objects` folder is 20.7 MB): /cc @joshaber.

Dump file:
[crashdump.zip](https://github.com/atom/atom/files/95183/crashdump.zip)

**Comment by steve9164** [comment] 2016-02-22 03:55
Just realised the cause of the crash. At that specific time, [there were some files with colons in the repo](https://github.com/TerriaJS/terriajs/tree/1f8db85/wwwroot/data/regionids). Windows doesn't allow colons in file names, so when git clones a repo and it has a whole bunch of files of the form `region_map:SOMETHING.json`, it just puts one empty file `region_map` instead. (On a side note: deleting this file and committing will cause git to delete all of the original colon-named files, so they stay "linked" to and representative of the original files.) This mismatch of git files and file system files seems to crash Atom on startup. By January the 22nd, [these files were renamed](https://github.com/TerriaJS/terriajs/tree/b5d6312/wwwroot/data/regionids), replacing the colon with a dash `-` (because of the Windows file name restrictions) so Atom worked with the repo again.

Below is an experiment I did which confirms this. On a freshly cloned [TerriaJS/terriajs](https://github.com/TerriaJS/terriajs) in Git Bash:

``` sh
MINGW64 ~/Documents/test/terriajs ((b5d6312...))
$ git checkout `git rev-list -n 1 --before="2016-01-22 10:00" master`
HEAD is now at b5d6312... add clock to ABS

MINGW64 ~/Documents/test/terriajs ((b5d6312...))
$ ls wwwroot/data/regionids | HEAD -3
region_map-FID_AUS_2011_AUST_AUS_CODE.json <---------------- Renamed files
region_map-FID_CED_2011_AUST_CED_CODE.json
region_map-FID_CED_2011_AUST_CED_NAME.json

MINGW64 ~/Documents/test/terriajs ((b5d6312...))
$ atom . <---------------- Atom launches correctly here


MINGW64 ~/Documents/test/terriajs ((b5d6312...))
$ git checkout `git rev-list -n 1 --before="2016-01-21 10:00" master`
Previous HEAD position was b5d6312... add clock to ABS
HEAD is now at 1f8db85... detect dates specified simply as years

MINGW64 ~/Documents/test/terriajs ((1f8db85...))
$ ls wwwroot/data/regionids | HEAD -3
region_map <---------------- File that represents the files with a colon in the name

MINGW64 ~/Documents/test/terriajs ((1f8db85...))
$ atom . <---------------- Atom crashes here (probably because all the region_map:STUFF files are not there)


```

**Comment by Zireael07** [comment] 2016-02-22 08:37
@steve9164: Then it is a duplicate of another issue, about crashing with names not allowed by Windows.

**Comment by 50Wliu** [comment] 2016-02-22 13:42
Thanks for the update @steve9164!  As @Zireael07 said, this issue is a duplicate of #10490, so feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-22 13:42 UTC
Labels: crash, git, windows
