### ISSUE TITLE
At least on mac, Command-W should close a window when it has no tab left open.

### ISSUE THREAD

**Issue by groue** [atom/atom#8423] opened 2015-08-18 12:25 UTC
Today Shift-Command-W is required. Command-W should close the window when it has no tab left, because the intent of the user is obvious. Forcing her to look for the damned command or click the close button is a bad experience.

Thanks for listening!

**Comment by groue** [comment] 2015-08-18 13:08
Atom 1.0.7, MacOS 10.10.5 (14F27).

Requested behavior can be found in TextMate. TextWrangler, BBEdit, and most tabbed applications (Safari, Chrome, Firefox) have a slightly different behavior: they close the window when its last tab gets closed.

**Comment by mnquintana** [comment] 2015-08-18 13:37
Thanks for the suggestion! This is a duplicate of https://github.com/atom/atom/issues/863 though – please subscribe there for updates.

**Closed by mnquintana** 2015-08-18 13:37 UTC
