### ISSUE TITLE
Resizing Text w/ Cmd-+ or Cmd-- quickly results in failure to change.

### ISSUE THREAD

**Issue by mcowger** [atom/atom#6394] opened 2015-04-15 18:45 UTC
Version: 0.190.0
Setup:  Enter text into an editor window.
Action: Use Cmd-+ or Cmd-- to change the size of the text.  If you press the keys slowly, it works as expected.  If you press them quickly (faster than about 5Hz), the text does not properly change size and 'bounces' between sizes.
Expected:Text size changes rapidly.

Example in video: https://www.youtube.com/watch?v=yKx4I5uiyF0&feature=youtu.be

**Comment by mnquintana** [comment] 2015-04-15 18:53
Duplicate of #5771

**Closed by mnquintana** 2015-04-15 18:53 UTC

**Comment by mcowger** [comment] 2015-04-15 20:01
Sorry about that - I looked for an existing issue but missed it.
