### ISSUE TITLE
Windows File Association and Icon not updated via auto update

### ISSUE THREAD

**Issue by linquize** [atom/atom#12920] opened 2016-10-09 03:39 UTC
### Description

Windows File Association and Icon not updated via auto update.

I searched the following registry keys and they all point to `C:\Users\User\AppData\Local\atom\app-1.9.8\atom.exe` which is out-dated.

```
HKEY_CLASSES_ROOT\*\shell\Atom:Icon
HKEY_CLASSES_ROOT\*\shell\Atom\Command:
HKEY_CLASSES_ROOT\Applications\atom.exe\shell\open\command:
HKEY_CLASSES_ROOT\directory\background\shell\Atom:Icon
HKEY_CLASSES_ROOT\directory\background\shell\Atom\command:
HKEY_CLASSES_ROOT\directory\shell\Atom:Icon
HKEY_CLASSES_ROOT\directory\shell\Atom\command:
```

### Steps to Reproduce

Right click Windows Explorer "Open with Atom"

**Expected behavior:** [What you expected to happen]
Menu Icon present, and correct version of atom is launched

**Actual behavior:** [What actually happened]
Menu Icon missing, and atom did not launch

### Versions

I installed Atom 1.8.0 via `AtomSetup.exe` at very beginning.
Then it automatically upgraded to 1.9.8, 1.10.0, 1.10.2 versions

Currently using Atom 1.10.2
Win 7 x64

**Comment by Ben3eeE** [comment] 2016-10-09 06:49
This is a duplicate of https://github.com/atom/atom/issues/12642 and will be fixed in the next upgrade of Atom.

**Closed by Ben3eeE** 2016-10-09 06:49 UTC
