### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by bil-elmoussaoui** [atom/atom#11863] opened 2016-05-29 18:54 UTC
[Enter steps to reproduce below:]

1. ... I have no idea, i was working and this message showed up
2. ...

**Atom Version**: 1.7.4
**System**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
  9x -0:41.9.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:39.9.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:33.5.0 markdown-writer:insert-new-line (atom-text-editor.editor.power-mode.is-focused)
     -0:33.5.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:31.7.0 core:backspace (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:30.4.0 core:save (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:25.4.0 core:cut (atom-text-editor.editor.power-mode.is-focused)
     -0:23.3.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -0:23 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:20.2.0 markdown-writer:insert-new-line (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:20.2.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:19.7.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:19.5.0 core:move-down (atom-text-editor.editor.power-mode.is-focused)
     -0:16.7.0 core:cut (atom-text-editor.editor.power-mode.is-focused)
  2x -0:16.5.0 core:save (atom-text-editor.editor.power-mode.is-focused)
 14x -0:09.8.0 core:backspace (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "terminal-plus"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "fontFamily": "consolas",
    "invisibles": {
      "space": "\t"
    },
    "showIndentGuide": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
atom-beautify, v0.29.7
atom-material-ui, v1.2.12
auto-detect-indentation, v1.0.0
autocomplete-python, v1.7.3
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.13
flex-tool-bar, v0.10.0
highlight-line, v0.11.1
language-arduino, v0.4.1
linter, v1.11.4
markdown-writer, v2.3.3
minimap, v4.24.3
pigments, v0.28.4
python-autopep8, v0.1.3
python-isort, v0.0.7
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-05-30 01:24
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-30 01:24 UTC
