### ISSUE TITLE
Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by idleberg** [atom/atom#13665] opened 2017-01-20 11:33 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When working with multiple panes, Atom throws
 this error when trying to open non-editor tabs that are already open:

```
item-registry.coffee:8 Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object](…)
module.exports.ItemRegistry.addItem @ item-registry.coffee:8
module.exports.PaneContainer.addedPaneItem @ pane-container.coffee:241
(anonymous function) @ pane-container.coffee:235
module.exports.Emitter.simpleDispatch @ emitter.js:25
module.exports.Emitter.emit @ emitter.js:129
module.exports.Pane.addItem @ pane.coffee:455
module.exports.Pane.activateItem @ pane.coffee:410
(anonymous function) @ workspace.coffee:525
```

Also, the result looks glitchy:

![screen shot 2017-01-20 at 12 30 39](https://cloud.githubusercontent.com/assets/1504938/22148056/4721f7f8-df0c-11e6-8f2e-421cec4b3f01.png)

Take note, that both Settings panes have focus. The left pane has the correct title (“Settings”), but the view remains empty. The right pane is *untitled* and shows the Settings view.

### Steps to Reproduce

1. Launch new Atom window
2. Split Pane (for this example I used *Split Right*)
3. Select the left pane, then open Preferences
4. Select the right pane, then open Preferences again

**Expected behavior:** Either show the settings pane in both tabs or focus to the first opened pane.

**Actual behavior:** Throws error and produces visual glitch

**Reproduces how often:** 100%

### Versions

```bash
$ atom --version
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --version 
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.5
git 1.9.5
```

### Additional Information

Tested in both, normal and safe mode, on Mac OS X 10.9.5

**Comment by Ben3eeE** [comment] 2017-01-20 11:49
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/settings-view/issues/723. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-01-20 11:49 UTC
