### ISSUE TITLE
HTML syntax highlight breaks with multi-line attributes

### ISSUE THREAD

**Issue by trusktr** [atom/atom#17493] opened 2018-06-09 08:23 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:

### Description

HTML syntax highlighting breaks when using multi-line attributes. See screenshot with and without multi-line attribute:

<img width="746" alt="screen shot 2018-06-09 at 1 17 56 am" src="https://user-images.githubusercontent.com/297678/41189458-22e4f278-6b83-11e8-9215-88513e03bf27.png">

<img width="967" alt="screen shot 2018-06-09 at 1 20 29 am" src="https://user-images.githubusercontent.com/297678/41189467-55dbba9a-6b83-11e8-9195-8f87cfb98fcf.png">

### Steps to Reproduce

Open Atom in safe mode and paste this HTML:

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>infamous timestamp</title>
        <script src="./global.js"></script>
        <script>
            infamous.html.useDefaultNames()
        </script>
        <style>
            body, html {
                width: 100%;
                height: 100%;
                padding: 0;
            }
        </style>
    </head>
    <body>
        <i-scene>
            <i-node id="node" align="0.5 0.5 0.5" mountPoint="0.5 0.5 0.5" style="
                background: deeppink
            ">
                Hello
            </i-node>
        </i-scene>
        <script>
            infamous.core.Motor.addRenderTask(() => {
                window.node.rotation.y ++
            })
        </script>
    </body>
</html>
```

**Expected behavior:**

HTML should not be green at the end

**Actual behavior:**

HTML starting after the `background: deeppink` is all green like an unclosed string.

**Reproduces how often:** 

100%

### Versions

<details>
  <summary>debug info with package info</summary>

```json
{
  "atom": "1.27.2",
  "platform": "darwin",
  "release": "17.5.0",
  "vmpVersion": "1.32.0",
  "vmpConfig": {
    "automaticallyEscapeInsertModeOnActivePaneItemChange": true,
    "keymapYToYankToLastCharacterOfLine": true,
    "wrapLeftRightMotion": true,
    "blackholeRegisteredOperators": [],
    "startInInsertModeScopes": [],
    "charactersToAddSpaceOnSurround": [],
    "highlightSearchExcludeScopes": [],
    "flashOnOperateBlacklist": []
  },
  "activeCommunityPackages": [
    "atom-material-syntax: 1.0.8",
    "atom-ide-ui: 0.12.0",
    "atom-ide-busy-signal: 0.0.0",
    "atom-ide-code-actions: 0.0.0",
    "atom-ide-code-format: 0.0.0",
    "atom-ide-code-highlight: 0.0.0",
    "atom-ide-console: 0.0.0",
    "atom-ide-datatip: 0.0.0",
    "atom-ide-debugger: 0.0.0",
    "atom-ide-definitions: 0.0.0",
    "atom-ide-diagnostics: 0.0.0",
    "atom-ide-diagnostics-ui: 0.0.0",
    "atom-ide-find-references: 0.0.0",
    "atom-ide-global: 0.0.0",
    "atom-ide-outline-view: 0.0.0",
    "atom-ide-signature-help: 0.0.0",
    "atom-ide-terminal: 0.0.0",
    "hyperclick: 0.0.0",
    "atom-vim-like-tab: 1.5.1",
    "ex-mode-sort: 1.0.0",
    "file-icons: 2.1.21",
    "file-watcher: 1.2.6",
    "hey-pane: 1.1.0",
    "highlight-line: 0.12.0",
    "highlight-selected: 0.13.1",
    "ide-css: 0.3.0",
    "ide-html: 0.4.2",
    "ide-json: 0.2.1",
    "ide-typescript: 0.7.6",
    "ide-vue: 0.1.8",
    "indent-guide-improved: 1.4.13",
    "keystroke: 0.4.0",
    "language-javascript-semantic: 0.2.1",
    "minimap: 4.29.8",
    "minimap-highlight-selected: 4.6.1",
    "minimap-pigments: 0.2.2",
    "minimap-quick-highlight: 1.0.1",
    "one-tab: 0.10.0",
    "pigments: 0.40.2",
    "project-plus: 1.0.0",
    "quick-highlight: 0.13.0",
    "teletype: 0.13.2",
    "terminal-tab: 0.5.6",
    "tree-view-git-status: 1.5.0",
    "vim-mode-plus: 1.32.0",
    "vim-mode-plus-keymaps-for-surround: 0.2.1",
    "editorconfig: 2.2.2",
    "language-pug: 0.0.22",
    "language-vue: 0.23.1"
  ]
}
```

</details>

**Comment by Ingramz** [comment] 2018-06-09 21:01
Duplicate of atom/language-html#194

**Closed** 2018-06-09 21:17 UTC
