### ISSUE TITLE
Uncaught Error: EINVAL: invalid argument, lstat '~/OneDrive - x'

### ISSUE THREAD

**Issue by genxlee** [atom/atom#15927] opened 2017-10-18 09:21 UTC
[Enter steps to reproduce:]

1. Opened .html file

**Atom**: 1.21.1 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EINVAL: invalid argument, lstat 'C:\Users\Gen Lee\OneDrive - x'

```
At fs.js:902

Error: EINVAL: invalid argument, lstat 'C:\Users\Gen Lee\OneDrive - x'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1542:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:21:27
    at Array.map (native)
    at Object.startTask (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:19:52)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/fuzzy-finder/lib/main.js:119:45)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/fuzzy-finder/lib/main.js:33:30
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
gruvbox 1.0.5 
```

**Comment by rsese** [comment] 2017-10-18 18:06
Thanks for taking the time to contribute!

Based on the stack trace, I think this looks like a duplicate of https://github.com/atom/fuzzy-finder/issues/324 so you can subscribe there for updates if you'd like.  If you can share more details in the issue (e.g. is it reproducible, is it reproducible in safe mode), that would be helpful too.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-18 18:06 UTC
