### ISSUE TITLE
Brace matching does not ignore comments

### ISSUE THREAD

**Issue by kgrossjo** [atom/atom#9005] opened 2015-09-30 11:51 UTC
Running Atom 1.0.19 on Windows, I do `atom --safe C:\Temp\foo.js` to open this non-existing file.  I then enter the following content:

```js
function foo() {
    // }
}
```

Positioning the cursor on the only opening brace tells me that it incorrectly matches the closing brace in the comment.  And indeed, hitting <kbd>Ctrl-M</kbd> to jump to the matching brace confirms this.

Shouldn't braces in comments be skipped for the purposes of brace matching?

**Comment by mnquintana** [comment] 2015-09-30 12:00
This looks like a duplicate of https://github.com/atom/bracket-matcher/issues/78 - please subscribe there for updates.

**Closed by mnquintana** 2015-09-30 12:00 UTC
