### ISSUE TITLE
git support broken for one of my projects

### ISSUE THREAD

**Issue by hannes-landeholm** [atom/atom#8323] opened 2015-08-11 12:37 UTC
- It has a `.git` folder in the root.
- The project has several submodules.
- The `.git` folder is not grayed out as usual.
- No visual indication from atom at all that atom understands the git status.
- Using `git status` in the project via terminal works fine.
- I am using atom 1.0.5.

**Comment by izuzak** [comment] 2015-08-11 14:08
@hannes-landeholm thanks for taking the time to submit an issue, but you'll need to be a bit more precise about what exactly is the problem and even better -- provide steps which reproduce the problem.

From your report it's not clear which folder you've opened in Atom (the root of the project or a sub-directory?), which indication _exactly_ you expected to see in Atom related to Git status (a screenshot might be helpful), what's returned by `git status`, which OS you're using, if you're seeing this problem only for that project or for other projects, if you can reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode), and any other [details](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) which would help us narrow things down and provide advice. Could you share that information? Also, if that project is public, can you share a link to it?

**Comment by hannes-landeholm** [comment] 2015-08-11 14:40
Opened folder: Root of project with the .git folder.

Indication: Any. E.g. coloured folders when they are updated/new, color indication in gutter for changed/deleted/added lines.

Git status: Normal output. When I change a file I can see the change in git status, I see nothing in atom. I see that I changed a file `modified:   setup/schema/x.sql`, however in atom there is no indication that `x.sql` file is changed.

OS: Mac OS X 10.10.4

Git works fine in other opened atom projects.

The project is unfortunately not public.

Problem persists in safe mode although I'm not sure that safe mode works. I launched atom with `/Applications/Atom.app/Contents/MacOS/Atom --safe`.

**Comment by izuzak** [comment] 2015-08-12 17:56
@hannes-landeholm Thanks for the details. It's interesting that this single project is problematic. Is there anything special about the project (e.g. does it have special characters in the name, does it use symlinks, stuff like that)?

@kevinsawicki @maxbrunsfeld what's the best way to investigate issues like these? :school:

**Comment by maxbrunsfeld** [comment] 2015-08-12 18:03
@hannes-landeholm Yeah, sorry for the broken feature. Since your project is not public, it's going to be a little more difficult for us to get to the bottom of this. If you're interested in helping figure this out, could you try to create another git repository that exhibits the same problem, and which you could share with us?

Some features that come to mind that might be worth replicating if applicable:
* As @izuzak said, symlinks
* Any non-standard file-system on which the repo exists
* Any interesting git features like submodules, filters.

**Comment by hannes-landeholm** [comment] 2015-08-18 09:25
I tried to isolate the problem and realized a completely new clone of the entire repo worked fine so I cloned everything again into a new folder and now atom works fine. It must have been some "bad" .git state that only atom was bothered by. Since my problem is resolved I unfortunately don't have time to investigate further.

**Comment by maxbrunsfeld** [comment] 2015-08-18 16:42
Thanks for the update @hannes-landeholm. I'm going to close this out for now. Let me know if you find out any more details of the problem; I'll reopen it.

**Closed by maxbrunsfeld** 2015-08-18 16:42 UTC
Labels: git, more-information-needed
