### ISSUE TITLE
Uncaught TypeError: e.target.closest is not a function

### ISSUE THREAD

**Issue by hdavidzhu** [atom/atom#15978] opened 2017-10-24 03:23 UTC
[Enter steps to reproduce:]

1. Drag file from one folder to another
2. See error output

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: e.target.closest is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1508

TypeError: e.target.closest is not a function
    at TreeView.module.exports.TreeView.onDragStart (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1508:34)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:239:30)
```

### Commands

```
```

### Non-Core Packages

```
atom-ctags 5.1.2 
busy-signal 1.4.3 
goto-definition 1.3.4 
hard-wrap 1.1.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-stylus 0.2.0 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-jsonlint 1.3.0 
linter-stylint 2.2.8 
linter-ui-default 1.6.10 
pretty-json 1.6.4 
sort-lines 0.18.0 
```

**Comment by rsese** [comment] 2017-10-24 21:58
Thanks for taking the time to contribute!

Based on the stack trace, I think this is a duplicate of https://github.com/atom/tree-view/issues/1088?  @hdavidzhu can you let us know in that issue if you can reproduce in safe mode?  If so, can you share more detailed steps to reproduce or share a GIF or screencast of the behavior?

---

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/1088. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-24 21:58 UTC
