### ISSUE TITLE
Failed to load the theme-roulette package

### ISSUE THREAD

**Issue by drodrigo** [atom/atom#9033] opened 2015-10-03 03:57 UTC
[Enter steps to reproduce below:]

1. ... It happens right away (I just have to open the editor), it started happening when I upgraded to the version below.

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.2
**Thrown From**: Atom Core

### Stack Trace

Failed to load the theme-roulette package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:8:5
    at Object.<anonymous> (<anonymous>:8:5)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "fontFamily": "Inconsolata-dz",
    "fontSize": 19,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.13.4
seti-syntax, v0.4.0
seti-ui, v0.8.0
theme-roulette, v1.1.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment] 2015-10-03 14:04
Duplicate of https://github.com/DavidLGoldberg/theme-roulette/issues/10.

---
@atom/feedback Anyone got a clue as to why this ended up here? This should have been attributed to the package. I guess this is some type of edge case not handled? Shouldn't be, but then again I haven't looked at the relevant code in notifications in a while.

**Closed by thomasjo** 2015-10-03 14:04 UTC
