### ISSUE TITLE
Unable to start Atom: "dyld: Symbol not found: _CIDetectorTypeText"

### ISSUE THREAD

**Issue by textchimp** [atom/atom#17565] opened 2018-06-23 03:59 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom 1.28.0 fails to start on OSX 10.10.1

### Steps to Reproduce

1. Start Atom as usual from the Applications folder, Spotlight, or the command line

**Expected behavior:** [What you expect to happen]

App to launch as usual

**Actual behavior:** [What actually happens]

- When started from Finder/Spotlight, a popup window appears which states `Atom cannot be opened because of a problem`.

- When started from the command line with `/Applications/Atom.app/Contents/MacOS/Atom`, the error text is:
```
dyld: Symbol not found: _CIDetectorTypeText
  Referenced from: /Applications/Atom.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework
  Expected in: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
 in /Applications/Atom.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework
Trace/BPT trap: 5
```

- When started with `atom --safe`, the error text is 
```
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time; unable to start Atom normally

### Versions

The Atom version commands are not working. They cause the "Atom cannot be opened because of a problem" popup to appear.

I downloaded the latest version of Atom (1.28.0) and replaced my previous installation with it, but the result was the same.

OSX Yosemite 10.10.1

### Additional Information

- I have tried re-downloading Atom and reinstalling it, which made no difference to the error
- I have tried removing `~/.atom`, which made no difference
- I have tried restarting my system several times

- The issue seems to have started after two instances of the program opened following a system restart, but both hung and had to be force quit. Googling the specific `dyld` error message I receive in the console yields no relevant results.

**Comment by golilang** [comment] 2018-06-23 04:41
P

**Comment by sir-ion** [comment] 2018-06-23 15:09
Same here on MacOSX 10.9.5 and atom 1.28.0 (obtained via `apm --version`, since `atom --version` does not work). The error occurred from evening to morning: yesterday everything was fine, today atom does not start. Possibly a regression due to an automatic update to version 1.28.0?

Moreover, before getting this error I had the following error

    user$ /Applications/Atom.app/Contents/MacOS/Atom 
      dyld: Library not loaded: 
        /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
      Referenced from: /Applications/Atom.app/Contents/Frameworks/Electron 
      Framework.framework/Versions/A/Electron Framework
      Reason: image not found
      Trace/BPT trap: 5

but I solved it using

    user$ sudo ln -s /System/Library/Frameworks/IOBluetooth.framework/Frameworks/CoreBluetooth.framework /System/Library/Frameworks/CoreBluetooth.framework

**Comment by lebenspuls** [comment] 2018-06-23 17:10
I also can't start Atom 1.2.8 suddenly not anymore on OSX 10.10.5. It still worked yesterday.

Process:               Atom [708]
Path:                  /Applications/Atom.app/Contents/MacOS/Atom
Identifier:            com.github.atom
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Atom [708]
User ID:               501

Date/Time:             2018-06-23 18:09:50.574 +0100
OS Version:            Mac OS X 10.10.5 (14F2511)
Report Version:        11
Anonymous UUID:        F597F35C-D5C4-9689-B920-882F606AE052


Time Awake Since Boot: 2900 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: _CIDetectorTypeText
  Referenced from: /Applications/Atom.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework
  Expected in: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
 in /Applications/Atom.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework

**Comment by jamols** [comment] 2018-06-23 18:54
Same here on OSX 10.10.5, except I don't see a popup - Atom 1.28.0 just silently fails to open.

Downgrading to Atom 1.27.2 solved it for me.

**Comment by sir-ion** [comment] 2018-06-23 18:57
How did you downgrade? Could you describe the process?

**Comment by lebenspuls** [comment] 2018-06-23 19:03
https://github.com/atom/atom/releases

**Comment by sir-ion** [comment] 2018-06-23 19:10
Ok, I was expecting that answer... I mean, if I delete my current version of Atom 1.28.0 and reinstall Atom 1.27.2, then do I loose all the package I installed and all the configurations I set?

**Comment by adrianshep** [comment] 2018-06-23 19:23
Reverting to 1.27.2 working for me so far (the sudo ln -s move came up empty for me). Thanks, jamols and lebenspuls!

**Comment by jamols** [comment] 2018-06-23 19:30
@sir-ion: no config / package issues here, just drop 'Atom.app' from the 1.27.2 .dmg into /Applications (and disable auto-updates if necessary)

**Comment by textchimp** [comment] 2018-06-24 03:36
I can also confirm that reverting to 1.27.2 is working for me (with my original `.atom` folder). Thanks for this suggestion.

**Comment by oditorium** [comment] 2018-06-24 08:49
Worked for me as well, but there is a gotcha: if you have autoupdates enabled it'll only start once. So essentially what you have to do is to

1/ download Atom 1.27.2
2/ unzip it
3/ launch it
4/ disable auto updating
5/ delete the previously extracted Atom executable
6/ unzip it again and move it to /Applications

**Comment by ryemccoy** [comment] 2018-06-24 18:57
same problem, had to fully remove, and then download 1.27.2, and followed oditorium's to do list.  and it works.  note: to disable auto updating, once atom is open, go to the menu option "ATOM", then "About Atom", and you'll see the checkbox there to install updates.  uncheck that.  notes: number 5 and 6 seem strange, on oditorium's suggestion, but it is how it will work.

**Comment by rsese** [comment] 2018-06-24 20:00
I'm unable to reproduce with macOS 10.12.6 but  it looks like everyone hitting this that mentioned their macOS version was on macOS 10.10.x or earlier.

About this error:

> dyld: Symbol not found: _CIDetectorTypeText

I found this Electron issue that looks related?  x-ref: https://github.com/electron/electron/issues/13404.

**Comment by jorgebg** [comment] 2018-06-25 08:19
Same for me, macOS 10.10.5

**Comment by Mister-Ax** [comment] 2018-06-25 10:28
i’ve the same problem!
https://discuss.atom.io/t/atom-crashes/56261 

1.28 worked, now it doesn't.
and
1.29 doesn't work

Downgrading worked, thanks for help
1.27 WORKS

what happened with other versions?

**Comment by vdcrea** [comment] 2018-06-25 12:51
Same for me, now I downgraded I got this annoying popin, telling me the linter package is not compiled with the same node version. Too bad.

NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing

**Comment by daviwil** [comment] 2018-06-25 14:19
Hey folks, thanks a lot for all the issue reports!  We need a bit of help determining which version of Atom/Electron this issue started happening in.  Could someone who sees this crash try both of these releases and let me know if the problem still exists on either one:

- Atom 1.28.0-beta0 / Electron 2.0.0: https://github.com/atom/atom/releases/tag/v1.28.0-beta0
- Atom 1.28.0-beta1 / Electron 2.0.1: https://github.com/atom/atom/releases/tag/v1.28.0-beta1

This will help us determine the version of Electron where this issue started to occur.

Thanks a lot for your help!

**Comment by sir-ion** [comment] 2018-06-25 19:16
Both version runs smoothly on my MacOSX 10.9.5 (but I still get the error using atom 1.28.0).
I run beta versions both with "double-click" from the finder and using terminal (no output at all, all clean).

**Comment by daviwil** [comment] 2018-06-25 19:23
Thanks @sir-ion, that was helpful!

**Comment by philof** [comment] 2018-06-25 19:28
Running on MacOSX 10.10.5:

Atom 1.28.0-beta0 works 
Atom 1.28.0-beta1 works
Atom 1.28.0-beta2 works 
Atom 1.28.0-beta3 works
Atom 1.28.0 crashes

**Comment by mmplisskin** [comment] 2018-06-26 04:21
1.28.0 same issue OS X Yosemite

**Comment by chuan-wang** [comment] 2018-06-26 06:46
Same issue: `Atom cannot be opened because of a problem.`
ATOM v1.28.0
OS X Yosemite v10.10.5

**Comment by techmag** [comment] 2018-06-26 13:34
Here with same problem and return/revert to v1.27.2 worked (albeit I had to reinstall twice to thwart auto-updates). 

Commenting merely to get thread notifications. Thanks!

**Comment by hypnoboutique** [comment] 2018-06-26 18:35
Phew! Excuse me while I change my underpants...

**Comment by RJVB** [comment] 2018-06-26 20:29
> We need a bit of help determining which version of Atom/Electron this issue started happening in

I think this is not a problem with Electron itself, but with how it was built, or rather on what version of the OS it was built.

There is a simple general rule of thumb for complex software where you cannot easily control the SDK against which the build has to be made (= the oldest supported OS version): build on a system running the oldest OS version.

**Comment by cowu** [comment] 2018-06-27 07:35
Same exact issue as OP down to the error messages, downloading v1.27.2 worked. Mac OS X 10.9.

**Comment by lee2sman** [comment] 2018-06-29 19:14
Same issue. I have a Macbook Air 2014. Had to download Atom 1.27.2 remove auto-update and deleted my prefs. argh.

**Comment by lee-dohm** [comment] 2018-07-03 05:13
According to https://github.com/electron/electron/issues/13459#issuecomment-400878134, Electron v2.0.3, which Atom v1.28.0 is built on, uses a version of Chromium that will not run on versions of macOS prior to version 10.10. I realize that some of you are running versions of macOS 10.10.x, but at least it is a partial explanation.

**Comment by jasonrudolph** [comment] 2018-07-03 21:32
This issue is resolved in https://github.com/atom/atom/pull/17620, and we're actively working on publishing this fix as part of Atom 1.28.1 and Atom 1.29.0-beta1.

Once those releases are published, Atom should once again run on OS X 10.10.x. 💦

**Comment by jasonrudolph** [comment] 2018-07-05 13:59
Atom 1.28.1 and Atom 1.29.0-beta1 are now available and should resolve this issue for anyone using Atom on OS X 10.10 Yosemite. Additionally, if you're seeing this issue on OS X 10.11 El Capitan or macOS 10.12 Sierra, please give this update a try and let us know if you continue to experience the problem.

**Closed by jasonrudolph** 2018-07-05 13:59 UTC
Labels: crash, electron, mac, regression, triaged

**Comment by delucis** [comment] 2018-07-05 15:33
I can confirm this is working for me on OS X 10.9.5 👏

**Comment by metaljoe** [comment] 2018-07-18 10:31
Thanks for getting this fixed 👍
