### ISSUE TITLE
[v1.21.0-beta0] Error: Cannot find module '../node_modules/nsfw/node_modules/fs-extra/lib/index.js'

### ISSUE THREAD

**Issue by hultberg** [atom/atom#15642] opened 2017-09-13 19:36 UTC
Just installed v1.21.0-beta0 and I'm getting these errors in the console:
```
Uncaught (in promise) Error: Cannot find module '../node_modules/nsfw/node_modules/fs-extra/lib/index.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom-beta/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom-beta/resources/app.asar/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom-beta/resources/app/static/<embedded>:96:26)
    at get_fse (/usr/share/atom-beta/resources/app/node_modules/nsfw/lib/src/index.js:17:80)
    at Object.buildNSFW (/usr/share/atom-beta/resources/app/node_modules/nsfw/lib/src/index.js:88:16)
    at nsfw (/usr/share/atom-beta/resources/app/node_modules/nsfw/lib/src/index.js:33:37)
    at NSFWBackend.<anonymous> (/usr/share/atom-beta/resources/app/src/path-watcher.js:192:34)
    at Generator.next (<anonymous>)
    at step (/usr/share/atom-beta/resources/app/src/path-watcher.js:5:279)
    at /usr/share/atom-beta/resources/app/src/path-watcher.js:5:449
    at NSFWBackend.<anonymous> (/usr/share/atom-beta/resources/app/src/path-watcher.js:5:105)
    at NativeWatcher.<anonymous> (/usr/share/atom-beta/resources/app/src/path-watcher.js:326:32)
    at Generator.next (<anonymous>)
    at step (/usr/share/atom-beta/resources/app/src/path-watcher.js:5:279)
    at /usr/share/atom-beta/resources/app/src/path-watcher.js:5:449
    at NativeWatcher.<anonymous> (/usr/share/atom-beta/resources/app/src/path-watcher.js:5:105)
    at NativeWatcher.onDidChange (/usr/share/atom-beta/resources/app/src/path-watcher.js:358:18)
    at PathWatcher.onDidChange (/usr/share/atom-beta/resources/app/src/path-watcher.js:566:37)
    at /usr/share/atom-beta/resources/app/src/path-watcher.js:575:24
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Also, from the github package:
```
Uncaught (in promise) Error: Cannot find module '../node_modules/nsfw/node_modules/fs-extra/lib/index.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom-beta/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom-beta/resources/app.asar/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom-beta/resources/app/static/<embedded>:96:26)
    at get_fse (/usr/share/atom-beta/resources/app/node_modules/nsfw/lib/src/index.js:17:80)
    at Object.buildNSFW (/usr/share/atom-beta/resources/app/node_modules/nsfw/lib/src/index.js:88:16)
    at nsfw (/usr/share/atom-beta/resources/app/node_modules/nsfw/lib/src/index.js:33:37)
    at /usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:146:68
    at Generator.next (<anonymous>)
    at step (/usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:36:197)
    at /usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:36:443
    at /usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:36:105
    at WorkspaceChangeObserver.watchActiveRepositoryGitDirectory (/usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:185:13)
    at /usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:97:25
    at Generator.next (<anonymous>)
    at step (/usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:36:197)
    at /usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:36:443
    at /usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:36:105
    at WorkspaceChangeObserver.start (/usr/share/atom-beta/resources/app/node_modules/github/lib/models/workspace-change-observer.js:100:13)
    at WorkdirContext.repositoryChangedState (/usr/share/atom-beta/resources/app/node_modules/github/lib/models/workdir-context.js:163:27)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Repository.transition (/usr/share/atom-beta/resources/app/node_modules/github/lib/models/repository.js:111:24)
    at Loading.transitionTo (/usr/share/atom-beta/resources/app/node_modules/github/lib/models/repository-states/state.js:470:34)
    at /usr/share/atom-beta/resources/app/node_modules/github/lib/models/repository-states/loading.js:29:28
    at Generator.next (<anonymous>)
    at step (/usr/share/atom-beta/resources/app/node_modules/github/lib/models/repository-states/loading.js:14:197)
    at /usr/share/atom-beta/resources/app/node_modules/github/lib/models/repository-states/loading.js:14:367
```

```
$ apm-beta --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 3.6.2
git 2.14.1
```

```
$ atom-beta --version
Atom    : 1.21.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by rsese** [comment] 2017-09-13 20:23
Thanks for the report!  So just to confirm, did you update to `1.21.0-beta0` from a previous beta version or did you install it directly?

If you re-install `1.21.0-beta0` do you still get the same error?

**Comment by rsese** [comment] 2017-09-13 20:24
Oh also, what operating system are you running?

**Comment by hultberg** [comment] 2017-09-13 20:39
@rsese I upgraded directly from v1.20.0-beta7. I'm using arch linux 64-bit, installed the official .deb package.

**Comment by alflanagan** [comment] 2017-09-13 22:02
See the same thing on Fedora 26, installed the official RPM. Error appears when running with --safe, but NOT after I renamed my .atom directory.

**Comment by rgawenda** [comment] 2017-09-14 09:35
It's due to a wrong dependency, as it lloks for fsevents:

    npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.1.2
    npm ERR! notsup Valid OS:    darwin
    npm ERR! notsup Valid Arch:  any
    npm ERR! notsup Actual OS:   linux

**Comment by alflanagan** [comment] 2017-09-14 15:24
Good catch! Usually when I install a package on Linux that depends on fsevents, it's an optional dependency, so I just get a warning message. Maybe it just wasn't marked as optional for this release??

**Comment by qmmp123** [comment] 2017-09-14 15:40
Did not get error when launch atom with --dev flag

**Comment by hultberg** [comment] 2017-09-18 07:43
@rgawenda Do you suspect this bug is related to when atom is built for linux?

**Comment by rgawenda** [comment] 2017-09-18 08:54
@hultberg It seems highly plausible

**Comment by hultberg** [comment] 2017-09-18 09:26
@rsese See https://github.com/atom/atom/issues/15642#issuecomment-329428713

**Comment by rsese** [comment] 2017-09-18 21:39
Thanks @hultberg - curious, if you temporarily reset to factory defaults like @alflanagan mentioned above, do you still see the error?  E.g.:

mv ~/.atom ~/.atom-backup

I'll also try to build on my Ubuntu VM and I'll bring this one up with the team.

**Comment by hultberg** [comment] 2017-09-20 07:41
@rsese Thanks, I tried that without luck. I upgraded to 1.21.0-beta1 and getting this error with a new .atom directory:
```
Uncaught (in promise) Error: Cannot find module '../node_modules/nsfw/node_modules/fs-extra/lib/index.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom-beta/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom-beta/resources/app.asar/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom-beta/resources/app/static/<embedded>:96:26)
    at get_fse (/usr/share/atom-beta/resources/app/node_modules/nsfw/lib/src/index.js:17:80)
    at Object.buildNSFW (/usr/share/atom-beta/resources/app/node_modules/nsfw/lib/src/index.js:88:16)
    at nsfw (/usr/share/atom-beta/resources/app/node_modules/nsfw/lib/src/index.js:33:37)
    at NSFWBackend.<anonymous> (/usr/share/atom-beta/resources/app/src/path-watcher.js:192:34)
    at Generator.next (<anonymous>)
    at step (/usr/share/atom-beta/resources/app/src/path-watcher.js:5:279)
    at /usr/share/atom-beta/resources/app/src/path-watcher.js:5:449
    at NSFWBackend.<anonymous> (/usr/share/atom-beta/resources/app/src/path-watcher.js:5:105)
    at NativeWatcher.<anonymous> (/usr/share/atom-beta/resources/app/src/path-watcher.js:326:32)
    at Generator.next (<anonymous>)
    at step (/usr/share/atom-beta/resources/app/src/path-watcher.js:5:279)
    at /usr/share/atom-beta/resources/app/src/path-watcher.js:5:449
    at NativeWatcher.<anonymous> (/usr/share/atom-beta/resources/app/src/path-watcher.js:5:105)
    at NativeWatcher.onDidChange (/usr/share/atom-beta/resources/app/src/path-watcher.js:358:18)
    at PathWatcher.onDidChange (/usr/share/atom-beta/resources/app/src/path-watcher.js:566:37)
    at /usr/share/atom-beta/resources/app/src/path-watcher.js:575:24
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by n06rin** [comment] 2017-09-25 03:52
@hultberg I have that error too. Try to delete .atom folder and reinstall atom 1.21.0-beta1.

**Comment by blamoo** [comment] 2017-09-25 19:32
Maybe deleting the `.atom` folder because that file should be located in `/usr/share/atom-beta`.

I have compared the .deb release files and, for some reason, that file exists in 
`/usr/share/atom/resources/app/node_modules/nsfw/node_modules/fs-extra/lib/index.js`
and doesn't in
`/usr/share/atom-beta/resources/app/node_modules/nsfw/node_modules/fs-extra/lib/index.js`

**Comment by hultberg** [comment] 2017-10-03 17:23
I'm not getting this error with 1.22.0-beta0.

**Comment by blamoo** [comment] 2017-10-03 18:55
@hultberg same here, it is working now.

**Comment by rsese** [comment] 2017-10-16 06:08
We talked about this one last week and were wondering if you could take a look because of all your recent fs work @smashwilson?  Confirmed that the error appears in 1.21.0 but not in 1.22.0-beta0 on Linux.

**Comment by icetee** [comment] 2017-11-08 22:37
Did the v1.22.0 resolve the issue?

**Comment by blamoo** [comment] 2017-11-09 00:06
yes

**Comment by rsese** [comment] 2017-11-10 01:36
I tested again and saw that the error isn't present in 1.21.1 or 1.22.0 on Ubuntu 16.04 - going to go ahead and close, thanks again for reporting this @hultberg.

**Closed by rsese** 2017-11-10 01:36 UTC
Labels: more-information-needed, uncaught-exception
