### ISSUE TITLE
Jump to the beginning or end of the real line

### ISSUE THREAD

**Issue by rbu** [atom/atom#17419] opened 2018-05-29 14:39 UTC
When editing a file with very long lines, there is no way to navigate to the real beginning or end of the line.
This is most obvious in soft-wrap mode, but it also happens when a line has over 500 characters and is wrapped due to that.

Jump to the beginning/end of the screen line (Ctrl+E on Mac, End key on Linux) will not jump to the real end. This makes it impossible to, for example, use Multi-Cursor editing to insert a character at the end or beginning of all lines.

![image](https://user-images.githubusercontent.com/65913/40664420-344d927a-635b-11e8-931c-cd959b7b1fef.png)

**Comment by rsese** [comment] 2018-05-29 21:02
Thanks for contributing!

We noticed that this is a duplicate of issues like https://github.com/atom/atom/issues/14345 - there's a `editor:move-to-end-of-line` command and you can set a custom keybinding for that to get the behavior you want with soft-wrapped lines e.g. on Linux:

```cson
'atom-text-editor':
  'end': 'editor:move-to-end-of-line'
```
Also, please fill out the issue template when opening issues, the information in the template is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-29 21:02 UTC
