### ISSUE TITLE
Wrong bracket highlighting with Regular Expressions

### ISSUE THREAD

**Issue by vorillaz** [atom/atom#10916] opened 2016-02-20 18:16 UTC
### Description

Atom is messing closing brackets when regular expressions are parsed
 
### Steps to Reproduce

1. Create a new JavaScript file.
2. Paste the code above
```javascript
function foo(toTest){
  return new RegExp(/^[^{]+\{\s*\[bar \w/).test(toTest);
}
```

### Versions
atom 1.5.3
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.4

**Comment by 50Wliu** [comment] 2016-02-20 18:46
This is a duplicate of atom/bracket-matcher#78 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-20 18:46 UTC
