### ISSUE TITLE
git ignore rules in .gitignore files that are in a parent directory of an Atom project are not used in search results

### ISSUE THREAD

**Issue by vladvelici** [atom/atom#14679] opened 2017-05-30 14:49 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For a project with the following directory structure:

    ./.git
    ./.gitignore
    ./hello.tmp
    ./hello.txt
    ./subproject
    ./subproject/index.html
    ./subproject/index.tmp

With the following .gitignore:

    *.tmp

If you open the root project, the search (cmd+shift+p) does not show the .tmp files and the file tree view on the side shows them greyed out, which is exactly what should happen.

If you however want to only work on `subproject/`, the .tmp files are greyed out in the side pane but they do show up in the search results. I think they shouldn't show up in the search results.

A workaround is to simply copy the `.gitignore` contents of the parent directory into the `subproject` directory, but I think this is an Atom bug that should be addressed.

Screenshots to make everything clearer:

Root project, everything is good:

![parent-project-search](https://cloud.githubusercontent.com/assets/787566/26588842/5f61bb0c-454e-11e7-8ead-da00e2f4e836.png)
![parent-project](https://cloud.githubusercontent.com/assets/787566/26588844/5f656bee-454e-11e7-9c78-098e62cf4795.png)

Subproject, the search shows results that should be omitted:

![subproject](https://cloud.githubusercontent.com/assets/787566/26588841/5f423156-454e-11e7-88eb-c5520165624c.png)
![subproject-search](https://cloud.githubusercontent.com/assets/787566/26588843/5f659164-454e-11e7-8f4a-a4f68b2eb1eb.png)

### Steps to Reproduce

1. Setup a git repository with a `.gitignore` like described above. [I made one here](https://github.com/vladvelici/atom-gitignore-bug-report-sample-repo)
2. Open the project, observe the tree file navigation sidebar and the search for the git ignored files.
3. Open a subfolder, observe the tree file navigation correctly greying out git ignored files but the search is not omitting those files.

**Expected behavior:** The search should omit the git ignored files even if the .gitignore file is in a parent directory outside the Atom project.

**Actual behavior:** The search does not omit those files, but the file navigator does grey them out.

**Reproduces how often:** It always behaves the same.

### Versions

Vlads-MacBook-Air:test vlad$ atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
Vlads-MacBook-Air:test vlad$ apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0

Running macOS 10.12.5.

**Comment by rsese** [comment] 2017-05-30 18:14
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/fuzzy-finder/issues/120. You may want to subscribe there for updates but if I misunderstood and you think the issue is different, please let me know.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-30 18:14 UTC
