### ISSUE TITLE
[UI, very low priority] Integrated toolbar

### ISSUE THREAD

**Issue by Tajnymag** [atom/atom#9384] opened 2015-11-01 19:03 UTC
Is it possible to integrate the toolbar to some sort of global theme? For me it seems weird to see more than 3 colour bars when looking at the top part of the editor :-/

**Comment by mnquintana** [comment] 2015-11-02 02:58
Thanks for the suggestion! I think this is a duplicate of https://github.com/atom/atom/issues/4599 - feel free to subscribe there for updates.

**Closed by mnquintana** 2015-11-02 02:58 UTC
