### ISSUE TITLE
Atom crash after close folder in Windows 10

### ISSUE THREAD

**Issue by Dovchiproeng** [atom/atom#9145] opened 2015-10-14 17:00 UTC
i open folder in atom after close it, it appear crash dialog.
![untitled](https://cloud.githubusercontent.com/assets/5102972/10491236/c0bd068e-72cf-11e5-958f-0440515b59fa.png)

**Comment by 50Wliu** [comment] 2015-10-14 21:53
This has happened to me as well, maybe twice.

@Dovchiproeng can you please paste the output of `apm list --installed` here?

Mine:
```
├── file-icons@1.6.10
├── find-and-replace@0.185.0
├── fizzy@0.16.0
├── git-control@0.4.0
├── language-csharp@0.10.0
├── language-java@0.16.0
├── language-javascript@0.96.0
├── language-make@0.18.0
├── language-php@0.30.0
├── language-python@0.40.0
├── language-shellscript@0.19.0
├── language-sourcepawn@0.5.0
├── language-sql@0.17.0
├── language-xml@0.32.0
├── linter@1.8.1
├── merge-conflicts@1.3.6
├── notifications@0.59.0
├── pdf-view@0.32.0
└── travis-ci-status@0.18.0
```

**Comment by rosafaria** [comment] 2015-10-20 08:54
Same thing happened to me I think 4 times already, on Windows 8.
I ran `apm list --installed` and got `<empty>`.

**Comment by damieng** [comment] 2016-04-13 19:40
Does this happen with every folder or only ones with specific file types? Does it happen with ones that contain a .git folder?

**Comment by lee-dohm** [comment] 2016-05-04 23:36
Has anyone run into this recently?

**Comment by 50Wliu** [comment] 2016-05-05 00:22
I don't recall the specifics of this, and can't say that I've had any crashes recently that are related to closing a folder.

**Comment by lee-dohm** [comment] 2016-05-13 21:41
Since nobody has run into this recently, I'm going to close it. Please let us know if anyone can reproduce it!

**Closed by lee-dohm** 2016-05-13 21:41 UTC
Labels: bug, crash, more-information-needed, windows
