### ISSUE TITLE
Atom for the web

### ISSUE THREAD

**Issue by chaudhs769** [atom/atom#21055] opened 2020-07-08 12:42 UTC
## Summary

Could you please create an atom for the web, like vscode.

## Motivation

This could enable people to code on their tablet or laptop

**Comment by Arcanemagus** [comment] 2020-07-08 16:37
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/3088. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-07-08 16:37 UTC
