### ISSUE TITLE
racer.rustSrcPath is not set in your config.

### ISSUE THREAD

**Issue by maxtnuk** [atom/atom#13742] opened 2017-02-04 15:38 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: Atom Core

### Stack Trace

racer.rustSrcPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
  4x -6:53 core:backspace (input.hidden-input)
     -6:36.4.0 settings-view:open (input.hidden-input)
  4x -6:28.2.0 core:backspace (input.hidden-input)
     -0:37.7.0 settings-view:open (input.hidden-input)
     -0:31.3.0 core:copy (input.hidden-input)
     -0:24.2.0 core:confirm (input.hidden-input)
     -0:06.8.0 core:save (input.hidden-input)
  2x -0:02.5.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "packagesWithKeymapsDisabled": [
      "atom-beautify"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  },
  "editor": {
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.2.0 (active)
atom-beautify, v0.29.17 (active)
atom-material-syntax-dark, v0.2.7 (active)
atom-material-ui, v1.3.9 (active)
autocomplete-plus, v2.34.2 (active)
docblockr, v0.9.1 (active)
git-time-machine, v1.5.4 (inactive)
highlight-selected, v0.12.0 (active)
language-crystal-actual, v0.33.0 (active)
language-gradle, v0.0.3 (active)
language-kotlin, v0.5.0 (active)
language-rust, v0.4.9 (active)
linter, v1.11.21 (active)
linter-crystal, v3.5.2 (active)
linter-kotlin, v0.2.0 (active)
linter-rust, v0.7.2 (active)
linter-write-good, v0.8.0 (active)
minimap, v4.26.8 (active)
minimap-autohide, v0.10.1 (active)
minimap-codeglance, v0.4.5 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.5.0 (active)
racer, v0.20.0 (active)
rustfmt, v0.1.3 (active)
seti-icons, v1.3.4 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.34.2 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2017-02-04 16:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/9204 and is an issue with [racer](https://github.com/edubkendo/atom-racer), rather than Atom core – feel free to open an issue there.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by mnquintana** 2017-02-04 16:24 UTC

**Comment by maxtnuk** [comment] 2017-02-08 10:28
Sorry for report the error.
This problum is caused by rust source code.
Because rust version in use and source version are not equal, it causes the
problum


2017. 2. 5. 오전 1:25에 "Machisté N. Quintana" <notifications@github.com>님이 작성:
