### ISSUE TITLE
"atom core" deprecation message

### ISSUE THREAD

**Issue by gottlike** [atom/atom#13653] opened 2017-01-18 17:18 UTC
After updating to 1.3.0 I am getting the following deprecation error:

```
atom core (1 deprecation)
Assigning editor 274's height explicitly via position: 'absolute' and an assigned top and bottom implicitly assigns the autoHeight property to false on the editor. This behavior is deprecated and will not be supported in the future. Please explicitly assign autoHeight on this editor.
TextEditorComponent.measureDimensions - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:1011:20
TextEditorComponent.becameVisible - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:295:12
TextEditorComponent.checkForVisibilityChange - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:993:16
atom-text-editor.attachedCallback - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:87:22
<unknown> - /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:826:33
```

macOS 10.11.6

**Comment by damieng** [comment] 2017-01-18 23:12
Can you please fill in the template that includes what steps you were performing.

Can you also clarify what version of Atom you are using?  We are on 1.13.0 right now - 1.3.0 is very old -typo?

**Comment by 50Wliu** [comment] 2017-01-19 00:18
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/metrics/issues/76. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by gottlike** [comment] 2017-01-20 09:25
Yes, I was talking about 1.13, sorry.

@50Wliu , I don't think this is a duplicate of the issue you linked to, as there is not mention of `path.dirName` or `Object.dirName` anywhere in the error message.

However, I just found out that the deprecation error was only showing when Atom opened an old "session", e.g.: I have two .txt files open pretty much all of the time. I used to close Atom with them still opened, so on the next start of Atom they will open right away. Now, after the update I got this error when reopening the session/files. I fixed the issue by closing the files, exiting Atom, starting Atom again and reopening the files again. Now there's now error message, even when reopening the session.

**Comment by srMarquinho** [comment] 2017-01-20 11:49
Just to state the above @gottlike comment solved the issue for me.

**Comment by 50Wliu** [comment] 2017-01-20 17:57
Ha, you're totally right.  My mistake 🙈.

**Comment by lee-dohm** [comment] 2017-01-28 22:00
It sounds like this can be fixed by either doing as @gottlike did or by running `atom --clear-window-state` as described in the [Atom Flight Manual](http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state). Since this can be resolved completely without a code change, I'm going to close this. If someone wants to run down where in the session restore code this could be fixed preemptively, we would accept a well-written PR for it.

**Closed by lee-dohm** 2017-01-28 22:00 UTC
Labels: needs-reproduction

**Comment by Luchanso** [comment] 2017-03-22 15:02
Atom 1.15.0 x64, Ubuntu 16.04 LTS

```
atom core (1 deprecation)
Assigning editor 2845's height explicitly via position: 'absolute' and an assigned top and bottom implicitly assigns the autoHeight property to false on the editor. This behavior is deprecated and will not be supported in the future. Please explicitly assign autoHeight on this editor.
TextEditorComponent.measureDimensions - /usr/share/atom/resources/app.asar/src/text-editor-component.js:1012:20
TextEditorComponent.becameVisible - /usr/share/atom/resources/app.asar/src/text-editor-component.js:295:12
TextEditorComponent.checkForVisibilityChange - /usr/share/atom/resources/app.asar/src/text-editor-component.js:994:16
atom-text-editor.attachedCallback - /usr/share/atom/resources/app.asar/src/text-editor-element.js:87:22
atom-pane-axis.childAdded - /usr/share/atom/resources/app.asar/src/pane-axis-element.js:95:12
Function.module.exports.Emitter.simpleDispatch - /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14
```

**Comment by shcherbak** [comment] 2017-03-22 21:48
1.15.0

Assigning editor 9553's height explicitly via position: 'absolute' and an assigned top and bottom implicitly assigns the autoHeight property to false on the editor. This behavior is deprecated and will not be supported in the future. Please explicitly assign autoHeight on this editor.
TextEditorComponent.measureDimensions - /usr/share/atom/resources/app.asar/src/text-editor-component.js:1012:20
TextEditorComponent.becameVisible - /usr/share/atom/resources/app.asar/src/text-editor-component.js:295:12
TextEditorComponent.checkForVisibilityChange - /usr/share/atom/resources/app.asar/src/text-editor-component.js:994:16
atom-text-editor.attachedCallback - /usr/share/atom/resources/app.asar/src/text-editor-element.js:87:22
atom-pane.activeItemChanged - /usr/share/atom/resources/app.asar/src/pane-element.js:138:24
Function.module.exports.Emitter.simpleDispatch - /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14

**Comment by suryaavala** [comment] 2017-03-23 00:42
1.15.0

atom core (1 deprecation)

Assigning editor 16's height explicitly via position: 'absolute' and an assigned top and bottom implicitly assigns the autoHeight property to false on the editor. This behavior is deprecated and will not be supported in the future. Please explicitly assign autoHeight on this editor.
TextEditorComponent.measureDimensions - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:1012:20
TextEditorComponent.becameVisible - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:295:12
TextEditorComponent.checkForVisibilityChange - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:994:16
atom-text-editor.attachedCallback - /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:87:22
atom-pane.activeItemChanged - /Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24
Function.module.exports.Emitter.simpleDispatch - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14
