### ISSUE TITLE
Uncaught TypeError: Invalid Point: (81, NaN)

### ISSUE THREAD

**Issue by zocoi** [atom/atom#19631] opened 2019-07-03 18:40 UTC
I'm not sure how it happened, I was opening an existing JS file and it starts showing

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (81, NaN)

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Invalid Point: (81, NaN)
    at Function.t.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:44572)
    at DisplayLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:85678)
    at DisplayMarkerLayer.t.exports.DisplayMarkerLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1179778)
    at DisplayMarker.t.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2799313)
    at changePosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:520594)
    at Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:529138)
    at Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:520560)
    at Cursor.moveLeft (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:523382)
    at modifySelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:533194)
    at Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:546340)
    at Selection.selectLeft (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:533162)
    at Selection.backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:537686)
    at mutateSelectedText.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16061)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:490618)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16037)
    at TextEditor.e.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:257430)
    at TextEditor.core:backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:300559)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:306300
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:490618)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at HTMLElement.s.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:306243)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348418)
```

### Commands

```
  6x -0:26.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-handlebars 1.3.0 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
firepad 0.8.0 
intentions 1.1.5 
language-haml 0.32.1 
language-jade 0.7.3 
language-matlab 0.2.1 
language-scala 1.1.10 
language-slim 1.0.0 
linter 2.3.0 
linter-erb 1.1.4 
linter-eslint 8.5.5 
linter-ruby 1.3.1 
linter-sass-lint 1.9.0 
linter-slim 2.0.0 
linter-tidy 2.4.0 
linter-ui-default 1.7.1 
multi-cursor 2.1.5 
multifile-rename 0.1.6 
prettier-atom 0.56.6 
react 0.18.0 
seti-syntax 1.2.0 
seti-ui 1.11.0 
Stylus 3.2.0 
TabNine 0.1.5 
```

**Comment by rsese** [comment] 2019-07-03 23:43
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/19114 so you can subscribe there for updates if you'd like.   It sounds like it just happened once and isn't reproducible, but if you have repro steps, please let us know in https://github.com/atom/atom/issues/19114.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-07-03 23:43 UTC
