### ISSUE TITLE
Travis builds for ATOM_CHANNEL=beta failing

### ISSUE THREAD

**Issue by Xapphire13** [atom/atom#14464] opened 2017-05-17 22:57 UTC
Failure error looks like

```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/travis/atom/usr/share/atom-beta/resources/app/apm/node_modules/git-utils/build/Release/git.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/home/travis/atom/usr/share/atom-beta/resources/app/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:570:32)
Downloading package dependencies...
module.js:597
  return process.dlopen(module, path._makeLong(filename));
```

Example Travis CI build [here](https://travis-ci.org/AtomLinter/linter-tslint/jobs/233339550)

Got info to tag @BinaryMuse and @smashwilson as they may have info on this

**Comment by 50Wliu** [comment] 2017-05-17 23:08
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14440. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-17 23:08 UTC

**Comment by BinaryMuse** [comment] 2017-05-17 23:09
Apologies, @50Wliu , I asked someone to open this. I'll ping the appropriate folks in the other issue.
