### ISSUE TITLE
Close tab when splitting it into a new pane

### ISSUE THREAD

**Issue by htor** [atom/atom#9322] opened 2015-10-28 15:02 UTC
Is it possible when I right-click a tab and select split-{up,down,right,left} to have that tab close, since I now have two tabs open with the same file (the original and the new split pane)?

Don't know if this is possible today - haven't found any package for it.

**Comment by mlms13** [comment] 2015-10-28 16:25
I'd also love to see this behavior. Perhaps this issue is duplicate of #4738, which might be getting fixed in #7953?

**Comment by htor** [comment] 2015-10-28 17:20
@mlms13 Looks like you're right. I hope #7953 will fix this soon, because I'm running out of tab space!

**Comment by 50Wliu** [comment] 2015-10-28 18:02
Ok, closing this in favor of #4738 then!  Thanks @mlms13.

**Closed by 50Wliu** 2015-10-28 18:02 UTC
