### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\Owusu Tsalah 

### ISSUE THREAD

**Issue by etsalah** [atom/atom#6952] opened 2015-05-26 11:02 UTC
[Enter steps to reproduce below:]

1. ...ignored *.pyc files in setting view
2. ...and right clicked on found name in tree-view

**Atom Version**: 0.201.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Owusu Tsalah

**Comment by mnquintana** [comment] 2015-05-26 11:05
This is a duplicate of https://github.com/atom/atom/issues/6548 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-26 11:05 UTC

**Comment by etsalah** [comment] 2015-05-26 11:08
ok thanks
