### ISSUE TITLE
Issue with python language format

### ISSUE THREAD

**Issue by TheElementalOfCreation** [atom/atom#15597] opened 2017-09-09 07:09 UTC
Issue: Eventually on a line, and bits of code (i.e. numbers, "int", strings, etc.) stops being colored.

Steps to reproduce:
1. Open a .py file
2. type the number 1
3. type the subtract symbol ("-")
4. repeat steps 2 and three around 50 or so times (may be more or less in certain situations) and it will happen.

**Comment by 50Wliu** [comment] 2017-09-09 18:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1677. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-09-09 18:22 UTC

**Comment by TheElementalOfCreation** [comment] 2017-09-09 18:44
Are you high? This is not a duplicate of 1667. This is not even CLOSE to 1667.

**Comment by TheElementalOfCreation** [comment] 2017-09-09 18:46
Never mind, my browser was being weird. Opened a different issue.

**Comment by TheElementalOfCreation** [comment] 2017-09-09 18:56
To be more specific, the email I received had 1677 as the post, even though your comment said 1667. What the heck even happened there?

**Comment by 50Wliu** [comment] 2017-09-09 20:44
Yeah, I'm sorry - I typed out the wrong issue number originally.  Right after commenting I noticed my mistake and edited my comment, but I guess github had already sent the email by then.  Sorry again for the confusion :sweat:.

**Comment by TheElementalOfCreation** [comment] 2017-09-12 04:47
Lol, no problem. Was a pretty funny story.
