### ISSUE TITLE
Cursor jumps by "tabs" not spaces

### ISSUE THREAD

**Issue by jameshfisher** [atom/atom#13517] opened 2016-12-29 21:11 UTC
### Description

I can't get the cursor to move in the expected way when hitting the arrow keys, i.e. moving one character left and right. Instead it moves according to some idea of "tabs", which seems to be set to 2 spaces.

### Steps to Reproduce

1. Type `______test` on a line,  where `_` is a space.
2. Go to start of line (cursor is at index 0, i.e. `|______test`).
3. Press right.

**Expected behavior:** cursor is at index 1, i.e. `_|_____test`.

**Actual behavior:** cursor is at index 2, i.e. `__|____test`.

**Reproduces how often:** always.

### Versions

```
% atom --version
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by mnquintana** [comment] 2016-12-29 23:05
This looks like a duplicate of https://github.com/atom/atom/issues/3174 – just enable the `Atomic Soft Tabs` setting to get the behavior you're looking for. 😄

**Closed by mnquintana** 2016-12-29 23:05 UTC

**Comment by jameshfisher** [comment] 2016-12-30 13:14
Aha! Fixed! Thanks!
