### ISSUE TITLE
Broken scrolling on (un)staged changes when dragging scrollbar

### ISSUE THREAD

**Issue by eltian** [atom/atom#15942] opened 2017-10-19 18:37 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The scrolling on the (un)staged changes window seems to be broken when dragging the corresponding scrollbar using the mouse. Using keyboard navigation or the wheel-mouse works as expected.

### Steps to Reproduce

1. Open a git project with changes on it (staged or not).
2. Open the git tab and select a file with enough changes for the scrollbar to show up.
3. On the "changes" window, drag the scrollbar to an arbitrary point.

**Expected behavior:** The scrollbar should stay where the dragging stops, leaving the window  proportionately scrolled down/up (i.e.: the usual scrollbar functionality when dragging)

**Actual behavior:** When dropping the scrollbar, it jumps up to the beginning of the file, undoing the scrolling and rendering the scrollbar-dragging useless.

**Reproduces how often:** Always

### Versions
**Atom --version:**
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**apm --version**
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.5
git 1.8.3.1

Using CentOS 7

**Comment by 50Wliu** [comment] 2017-10-19 21:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/github#1226 You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-10-19 21:24 UTC
