### ISSUE TITLE
Uncaught Error: Cannot find module 'dialog'Error'

### ISSUE THREAD

**Issue by artempartos** [atom/atom#5974] opened 2015-03-15 16:46 UTC
Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog'    at Function.Module._resolveFilename (module.js:351:15)    at Function.Module._load (module.js:293:25)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77

Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
  at metaToValue (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77:15)
  at Object.exports.require (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:157:34)
  at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:698:23)
  at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:507:21)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:456:18)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:697:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:741:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -1:05.9 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:05.7 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -1:04.2 cut-line:cut-line (atom-text-editor.editor.is-focused)
     -0:58.1 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:57.9 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:54.1 core:move-down (atom-text-editor.editor.is-focused)
     -0:54.0 core:move-up (atom-text-editor.editor.is-focused)
  7x -0:53.3 cut-line:cut-line (atom-text-editor.editor.is-focused)
     -0:51.1 editor:newline (atom-text-editor.editor.is-focused)
     -0:50.6 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:50.0 core:save (atom-text-editor.editor.is-focused)
     -0:43.1 core:close (atom-text-editor.editor.is-focused)
     -0:32.9 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -0:01.3 core:close (atom-text-editor.editor.is-focused)
     -0:00.1 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:00.1 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "exception-reporting",
      "feedback",
      "go-plus",
      "bookmarks",
      "eslint",
      "linter-jshint",
      "linter",
      "atom-ctags",
      "symbol-gen",
      "term2"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "fontSize": 14,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
autocomplete-plus, v2.3.0
block-travel, v1.0.2
cut-line, v0.10.0
git-log, v0.3.0
jshint, v1.2.0
language-erlang, v2.0.0
language-haml, v0.15.0
line-jumper, v0.13.0
linter-eslint, v0.4.1
linter-ruby, v0.1.4
monokai, v0.12.0
subword-navigation, v2.5.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-15 16:52
Duplicate of atom/tree-view#399, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-15 16:52 UTC
