### ISSUE TITLE
Dragging file into window makes it unusable

### ISSUE THREAD

**Issue by achlubek** [atom/atom#8302] opened 2015-08-10 13:24 UTC
If you drag a file on Windows 7 into atom window, internal browser opens it instead and none atom controls work since then.

**Comment by alexandernst** [comment] 2015-08-10 13:36
Duplicate of https://github.com/atom/atom/issues/4300

**Comment by 50Wliu** [comment] 2015-08-10 13:37
Thanks!

**Closed by 50Wliu** 2015-08-10 13:37 UTC
