### ISSUE TITLE
Atom freezes when trying to write on non writable file

### ISSUE THREAD

**Issue by Pytness** [atom/atom#17418] opened 2018-05-29 14:27 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom freezes when trying to save a file that is not writable

### Steps to Reproduce

1. Create non writable file
2. Open that file with atom and write something
3. Try to save it

**Expected behavior:** Display an error message or do nothing

**Actual behavior:** Atom freezes

**Reproduces how often:** When i try to modify a non writable file

### Versions
Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

Windows 32 bits

**Comment by rsese** [comment] 2018-05-29 20:33
Thanks for the report!  I'm unable to reproduce with Windows 10 and Atom 1.27.1 - when I set a simple test file (just has "hello world!" in it) as read-only in its Properties, I get a permission denied error when trying to save it.

What version of Windows are you running?

And have you been able to reproduce with a test file or just with a particular file that you've already been working with?

**Comment by Pytness** [comment] 2018-05-30 09:41
@rsese I was working with a file in which was added a large number of bytes (it was not me, so I did not realize) and it become non writable.
So when i tried to write, it did not freeze because it was not writable, but for being a really large file.
I checked if I could save in another copy of that file (an old lighter one) and i could, so i though it was an issue.

Sorry about the false alarm 😓  .

**Comment by rsese** [comment] 2018-05-30 17:12
Ahhh ok no problem and thanks for confirming - since trying to write read-only files is throwing a permission denied error as expected, we'll go ahead and close this.

**Closed by rsese** 2018-05-30 17:12 UTC
Labels: more-information-needed
