### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blockHeight' of undefined

### ISSUE THREAD

**Issue by jeromelachaud** [atom/atom#15756] opened 2017-09-27 15:32 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'blockHeight' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/line-top-index/dist/line-top-index.js:313

TypeError: Cannot read property 'blockHeight' of undefined
    at LineTopIndex.adjustNodeBlockHeight (/Applications/Atom.app/Contents/Resources/app/node_modules/line-top-index/dist/line-top-index.js:313:17)
    at LineTopIndex.removeBlock (/Applications/Atom.app/Contents/Resources/app/node_modules/line-top-index/dist/line-top-index.js:78:18)
    at marker.bufferMarker.onDidChange (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2524:35)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:424:26)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:324:31
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker-layer.js:321:52)
    at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1561:40)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:924:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2174:25)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1969:25)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1805:25)
```

### Commands

```
  2x -2:04.0 core:backspace (input.hidden-input)
     -2:00.9.0 editor:newline (input.hidden-input)
     -1:58.8.0 core:backspace (input.hidden-input)
     -1:57.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.30.5 
atom-bracket-highlight 0.3.2 
atom-jump-block 0.5.4 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
autocomplete-module-import 0.1.2 
autocomplete-modules 1.7.0 
base16-ocean-dark-spacegray 0.13.0 
better-window-title 1.0.3 
busy-signal 1.4.3 
css-in-js 1.4.0 
cssbeautify 1.3.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.12 
highlight-selected 0.13.1 
import-cost-atom 1.0.4 
intentions 1.1.5 
js-func-viewer 1.1.4 
language-babel 2.74.3 
letter-spacing 0.3.1 
linter 2.2.0 
linter-eslint 8.3.2 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-quick-highlight 1.0.1 
oceanic-next 1.0.0 
open-project-file 1.1.1 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
react 0.16.2 
react-snippets 0.9.0 
single-click-open 0.2.2 
speed-bot 0.1.0 
sync-settings 0.8.3 
tree-view-open-files 0.3.0 
whitespacer 1.1.1 
```

**Comment by rsese** [comment] 2017-09-27 18:13
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by jeromelachaud** [comment] 2017-09-29 12:34
I was doing select all and paste all

**Comment by rsese** [comment] 2017-09-29 20:37
Thanks for the details - so the error is reproducible for you with those steps?  If so, can you clarify your steps?  

> I am selecting text in a file > then select all in another file.

When you say select, do you mean select and copy?

> I got the error when I want to paste

Where are you pasting?  In file 1 or 2 or it doesn't matter?

> I have to delete before pasting in order not to have the error

What do you delete before pasting?

A GIF or screencast could be helpful too.

**Comment by jeromelachaud** [comment] 2017-10-06 14:24
I am selecting text in a file and copy > then select all in another file.
All the text is selected on the new file, I paste the I got the error message

**Comment by IanMitchell** [comment] 2017-10-08 17:11
I think it might be caused by my package, `import-cost-atom` - been struggling to figure out what's going on. Also reported here: https://github.com/IanMitchell/import-cost-atom/issues/5

For repro steps, install my package, create a new Node project with something like 

```javascript
import debug from 'debug';

const log = debug('test');
log('Hello World');
```

With the corresponding package.json with `debug` dependency. The import line should be marked up - selecting the line and deleting it should trigger this error.

As far as I can tell, my package gets through everything without problem but something that's leftover is mucking with the line and preventing it from being removed. Been tearing my hair out trying to figure out what I'm doing wrong haha

**Comment by IanMitchell** [comment] 2017-10-09 20:40
Should be fixed now - @jeromelachaud do you still get the exception after updating to the latest version of `import-cost-atom`?

**Comment by rsese** [comment] 2017-10-10 04:56
Oh awesome @IanMitchell - just to clarify, do you think there's an issue on our end that we should ask the team to look at?

**Comment by jeromelachaud** [comment] 2017-10-10 08:45
@IanMitchell , I have just updated the package and so far, so good 👍 
Keeping this issue opened for a few hours to confirm the problem is gone and I'll dully close it.
Thanks @rsese as well

**Comment by Ben3eeE** [comment] 2017-10-10 08:50
@rsese @jeromelachaud We should keep this open and ask the team about it.

**Comment by IanMitchell** [comment] 2017-10-10 15:47
@rsese I don't believe so - the only thing I'd mention is that the exception never mentioned my package, and the stack trace didn't have any hints either. I know the language-babel folk also got a bug report that came through Atom, even though the root cause was my fault (see: https://github.com/gandm/language-babel/issues/415)

I don't know if it's worth the effort to investigate / try to fix though since it seems this issue is a pretty rare one.

**Comment by Ben3eeE** [comment] 2017-10-11 08:17
@IanMitchell There is now a PR open to fix this. Thank you for the clear steps to reproduce :bowing_man:

**Closed** 2017-10-11 14:16 UTC
Labels: triaged, uncaught-exception
