### ISSUE TITLE
Uncaught Error: spawn /opt/atom/atom (deleted) ENOENT

### ISSUE THREAD

**Issue by linuxxxxx** [atom/atom#5079] opened 2015-01-15 15:14 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: linux 3.13.0-44-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /opt/atom/atom (deleted) ENOENT

```
At events.js:85

Error: spawn /opt/atom/atom (deleted) ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1047:32)
  at child_process.js:1138:20
  at process._tickCallback (node.js:386:11)

```

### Commands

```
     -0:12.6 core:move-left (atom-text-editor.editor)
  2x -0:12.1 editor:select-to-end-of-word (atom-text-editor.editor)
     -0:10.7 core:move-up (atom-text-editor.editor)
     -0:10.4 core:move-left (atom-text-editor.editor)
  2x -0:10.0 editor:select-to-end-of-word (atom-text-editor.editor)
     -0:08.8 core:move-up (atom-text-editor.editor)
     -0:08.5 core:move-left (atom-text-editor.editor)
  2x -0:08.1 editor:select-to-end-of-word (atom-text-editor.editor)
     -0:06.7 core:move-up (atom-text-editor.editor)
     -0:06.4 core:move-left (atom-text-editor.editor)
  2x -0:05.5 editor:select-to-end-of-word (atom-text-editor.editor)
     -0:04.2 core:move-up (atom-text-editor.editor)
     -0:03.9 core:move-left (atom-text-editor.editor)
  2x -0:03.5 editor:select-to-end-of-word (atom-text-editor.editor)
     -0:01.6 core:backspace (atom-text-editor.editor)
     -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git .bak .hv *~"
    ],
    "projectHome": "/git/"
  },
  "editor": {
    "fontFamily": "ubuntu",
    "fontSize": 13,
    "showInvisibles": true,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
language-batch, v0.3.2

# Dev
No dev packages
```

**Comment by batjko** [comment] 2015-01-15 15:18
Could you give some information as to what you were doing when this happened, i.e. reproducible steps if possible?

Does this happen every time you do the same thing?

Does the issue still occur when you open Atom in safe mode (`atom --safe`)?

**Comment by linuxxxxx** [comment] 2015-01-15 15:22
I click inside the window (it doesn't matter if i click on the document, a menu or file from tree). And yes, it happens even with atom --safe

**Comment by linuxxxxx** [comment] 2015-01-15 15:24
I forgot to tell you that this issue happened as soon as i updated atom a few hrs ago via apt

**Comment by izuzak** [comment] 2015-01-15 16:20
This looks like a duplicate of https://github.com/atom/atom/issues/4505 (so I'm closing this in favor of that issue). Can you try the suggestion from https://github.com/atom/atom/issues/4505#issuecomment-66795073?

**Closed by izuzak** 2015-01-15 16:20 UTC
