### ISSUE TITLE
small bug for editing .cpp files

### ISSUE THREAD

**Issue by jazzcurio** [atom/atom#9076] opened 2015-10-08 04:46 UTC
When editing .cpp files
there is a small bug.

Atom editor doesn't act like.. it's supposed to

Try to type the following then you will recognize the problem right away.

std::cout << "hello world\n";

After \n
when you try to put the closing quotation
it doesn't close it.
It puts another opening quotation mark.
So.. it will be like the following:

std::cout << "hello world\n"";

I had to manually delete one of the quotation marks.

**Comment by izuzak** [comment] 2015-10-08 06:33
Thanks for the report -- looks like a duplicate of https://github.com/atom/bracket-matcher/issues/80. :v:

**Closed by izuzak** 2015-10-08 06:33 UTC
