### ISSUE TITLE
Failed to activate the language-jsx package

### ISSUE THREAD

**Issue by mik01aj** [atom/atom#9394] opened 2015-11-02 15:07 UTC
The error appears on startup.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the language-jsx package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:7:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:300:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-pylint",
      "linter-jsxhint",
      "linter-jscs",
      "language-javascript-semantic",
      "linter-jshint",
      "autocomplete-flow"
    ],
    "themes": [
      "isotope-light-ui",
      "seti-syntax"
    ],
    "projectHome": "~/code/"
  },
  "editor": {
    "showInvisibles": true,
    "showIndentGuide": true,
    "preferredLineLength": 100,
    "tabLength": 4,
    "invisibles": {},
    "lineHeight": 1.4,
    "fontFamily": "Source Code Pro",
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
color-picker, v2.0.13
file-type-icons, v0.7.3
file-types, v0.5.1
isotope-light-ui, v2.1.0
language-diff, v0.3.1
language-groovy, v0.4.0
language-jsx, v0.1.4
linter, v1.8.1
linter-eslint, v3.1.1
linter-flow, v3.1.3
linter-sass-lint, v0.4.1
minimap, v4.16.0
minimap-git-diff, v4.1.8
pretty-json, v0.4.1
raml, v0.2.0
react, v0.12.10
refactor, v0.6.0
seti-syntax, v0.4.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-02 18:54
Closing as a duplicate of Icehunter/language-jsx#5, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-02 18:54 UTC
