### ISSUE TITLE
racer.racerBinPath is not set in your config.

### ISSUE THREAD

**Issue by nipengmath** [atom/atom#10224] opened 2015-12-30 12:19 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

racer.racerBinPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -3:11.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:06.8.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -3:05.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:30.4.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:27.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:25.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:25.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:25.9.0 editor:indent (atom-text-editor.editor.is-focused)
  5x -1:25 core:backspace (atom-text-editor.editor.is-focused)
     -1:06.0 grammar-selector:show (atom-text-editor.editor)
  4x -0:14.6.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
language-rust, v0.4.5
racer, v0.17.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-12-30 14:32
This looks like a duplicate of https://github.com/edubkendo/atom-racer/issues/64 – feel free to subscribe there for updates.

**Closed by mnquintana** 2015-12-30 14:32 UTC
