### ISSUE TITLE
Open file tabs should not shrink so small

### ISSUE THREAD

**Issue by maxkfranz** [atom/atom#6388] opened 2015-04-15 14:51 UTC
They shrink so much that with many open files the titles become unreadable, e.g.:

![screen shot 2015-04-15 at 10 51 33 am](https://cloud.githubusercontent.com/assets/989043/7161499/67e4d598-e35d-11e4-8b1e-287259ce63f7.png)

**Comment by mnquintana** [comment] 2015-04-15 14:55
Duplicate of atom/one-dark-ui#49

**Closed by mnquintana** 2015-04-15 14:55 UTC
