### ISSUE TITLE
support

### ISSUE THREAD

**Issue by mostafamemariani** [atom/atom#15128] opened 2017-07-30 08:53 UTC
hi,
please support persian language in editor!

**Comment by 50Wliu** [comment] 2017-07-30 17:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3103. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-07-30 17:24 UTC

**Comment by mostafamemariani** [comment] 2017-07-31 10:21
hi, i don't mean translation
i mean editing persian string in eg my html file is impossible,
when i change press the arrow keys, the cursor does not move and is fixed in a certain position.
![image](https://user-images.githubusercontent.com/6501140/28773634-a6cbecba-75ff-11e7-9f81-05d9a0f8e133.png)

**Comment by 50Wliu** [comment] 2017-07-31 14:45
Then this is a duplicate of #10294 and #13348.
