### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/v3ss/workspace/phwa.re/gui/phwabe/...

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#7539] opened 2015-06-29 10:29 UTC
[Enter steps to reproduce below:]

1. Delete a file that is already in project
2. Open that session.

**Atom Version**: 1.0.1-375cf27
**System**: "Sabayon Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/v3ss/workspace/phwa.re/gui/phwabe/source/class/phwabe/utils/list/InfiniListDebounce.js'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/home/v3ss/workspace/phwa.re/gui/phwabe/source/class/phwabe/utils/list/InfiniListDebounce.js'
  at Error (native)
  at EventEmitter.ipc.sendSync (/opt/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at Object.exports.require (/opt/atom/resources/atom.asar/renderer/api/lib/remote.js:160:16)
  at Object.<anonymous> (/home/v3ss/.atom/init.coffee:1:19)
  at Object.<anonymous> (/home/v3ss/.atom/init.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Atom.module.exports.Atom.requireUserInitScript (/opt/atom/resources/app.asar/src/atom.js:924:20)
  at Atom.module.exports.Atom.startEditorWindow (/opt/atom/resources/app.asar/src/atom.js:644:14)
  at Object.<anonymous> (/opt/atom/resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/opt/atom/resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///opt/atom/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///opt/atom/resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-ruby-on-rails",
      "mobile-preview",
      "atom-html-preview",
      "color-picker",
      "run-command",
      "runcoderun",
      "whitespace",
      "svg-preview",
      "autosave",
      "autocomplete-jedi",
      "autocomplete-plus-async",
      "cute-cursor",
      "pulsing-cursor",
      "neon-selection",
      "atom-lint",
      "animation-showcase",
      "tree-view-open-files",
      "autocomplete",
      "ease-blink",
      "highlight-line",
      "minimap-highlight-selected",
      "minimap",
      "markdown-writer",
      "atom-alignment",
      "autocomplete-atom-api",
      "fancy-input",
      "sublime-tabs",
      "spell-check",
      "tool-bar-main",
      "tool-bar",
      "flex-tool-bar",
      "atom-ternjs",
      "gutter-shadow",
      "local-history",
      "tab-rename",
      "open-in",
      "pigments",
      "linter",
      "goto",
      "cursor-blink-interval"
    ],
    "ignoredNames": [
      "*.pyc",
      "/home/v3ss/workspace/phwa.be/condaenv",
      "/home/v3ss/workspace/phwa.be/pypyenv",
      "*.zip",
      "*.tar",
      ".hg"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "steam-pirate-ui",
      "steam-pirate-syntax"
    ]
  },
  "editor": {
    "preferredLineLength": 120,
    "tabLength": 4,
    "confirmCheckoutHeadRevision": false,
    "autoIndentOnPaste": false,
    "scrollSensitivity": 120,
    "invisibles": {},
    "showIndentGuide": true,
    "lineHeight": 1.35,
    "scrollPastEnd": true,
    "zoomFontWhenCtrlScrolling": false,
    "fontSize": 12,
    "fontFamily": "NK57 Monospace"
  }
}
```

### Installed Packages

```coffee
# User
auto-reveal-in-sidebar, v0.5.0
autocomplete-plus-python-jedi, v0.3.6
autohide-tree-view, v0.20.2
block-cursor, v0.13.1
block-travel, v1.0.2
build, v0.38.0
editorconfig, v1.0.0
file-icons, v1.5.8
file-type-icons, v0.7.0
hashrocket, v0.4.8
highlight-column, v0.5.0
highlight-selected, v0.10.1
language-javascript-better, v1.5.0
language-nim, v0.2.2
linter-coffeelint, v0.3.2
linter-csslint, v0.0.14
linter-flake8, v1.4.2
linter-jshint, v0.1.7
linter-tidy, v1.0.1
linter-xmllint, v0.0.6
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-selection, v4.2.0
pdf-view, v0.22.0
script-runner, v1.8.3
steam-pirate-syntax, v0.3.0
steam-pirate-ui, v0.6.1
symbols-tree-view, v0.9.3
tabs-to-spaces, v0.11.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by batjko** [comment] 2015-06-29 10:33
I think this is the same as https://github.com/atom/atom/issues/7488.
Can you confirm that?

**Comment by v3ss0n** [comment] 2015-06-29 10:40
Not sure , seems not related .
i think this one is very simple issue.
When a file is already open with atom , then that file is deleted from outside process, atom causes error popup on startup (with that file opened as blank file) .

A simple exception check for file existance can fix that.

**Comment by batjko** [comment] 2015-06-29 11:52
In the issue I linked Atom seems to crash when a folder gets deleted from outside Atom.
In your case, I gather, you're just getting this error?

**Comment by izuzak** [comment] 2015-07-06 18:10
Closing as a duplicate of https://github.com/atom/atom/issues/6210.

**Closed by izuzak** 2015-07-06 18:10 UTC
Labels: uncaught-exception
