### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by Finrod927** [atom/atom#14448] opened 2017-05-17 12:37 UTC
Hello
I just get this "Uncaught Error" error when saving a NodeJS file (changed a `Buffer.alloc` to `Buffer.from`).
I tried to reproduce the error by doing the same steps but I didn't succeed.

I will update the issue if I can find more details.

EDIT: it seems we found the issue of the day: #14441 #14443 #14447, Atom did not found the issue was already created.

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\Users\sfa\AppData\Local\atom\app-1.17.0\resources\electron.asar\browser\objects-registry.js:41:28)
    at EventEmitter.<anonymous> (C:\Users\sfa\AppData\Local\atom\app-1.17.0\resources\electron.asar\browser\rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\sfa\AppData\Local\atom\app-1.17.0\resources\electron.asar\browser\api\web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At C:\Users\sfa\AppData\Local\atom\app-1.17.0\resources\electron.asar\renderer\api\remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.17.0/resources/app/src/atom-environment.js:663:1)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.17.0/resources/app/src/atom-environment.js:697:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:184:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1
```

### Commands

```
     -9:48.2.0 intentions:highlight (input.hidden-input)
     -9:48.1.0 core:save (input.hidden-input)
     -4:46.4.0 intentions:highlight (input.hidden-input)
  2x -4:46.2.0 core:undo (input.hidden-input)
     -4:44.6.0 core:save (input.hidden-input)
     -4:43.9.0 core:close (input.hidden-input)
     -3:58.2.0 intentions:highlight (input.hidden-input)
     -3:58.1.0 core:close (input.hidden-input)
     -3:40.3.0 core:select-right (input.hidden-input)
  6x -3:39.8.0 intentions:highlight (input.hidden-input)
     -3:39.2.0 project-find:show (input.hidden-input)
     -3:38.7.0 core:confirm (input.hidden-input)
     -0:35.9.0 core:backspace (input.hidden-input)
     -0:26.4.0 core:close (div.results-view.focusable-panel)
     -0:23.9.0 intentions:highlight (input.hidden-input)
     -0:23.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-handlebars 1.3.0 
busy-signal 1.4.1 
cson 2.0.1 
editorconfig 2.2.2 
file-icons 2.1.5 
intentions 1.1.2 
language-vue 0.21.2 
linter 2.1.4 
linter-eslint 8.1.7 
linter-htmlhint 1.3.3 
linter-ui-default 1.5.0 
pigments 0.39.1 
restart-atom 0.2.0 
standard-formatter 2.8.0 
sync-settings 0.8.1 
todo-show 1.11.0 
tree-view-autoresize 2.0.0 
```

**Comment by 50Wliu** [comment] 2017-05-17 15:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #11692. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-17 15:20 UTC
