### ISSUE TITLE
1.4.0beta3 Release Notes is outdated

### ISSUE THREAD

**Issue by tomByrer** [atom/atom#10165] opened 2015-12-23 01:31 UTC
1.4.0beta3 has release notes from last November.
Win7

![atom1 4 0-beta3-release-notes](https://cloud.githubusercontent.com/assets/1308419/11969645/d3b6f9b2-a8d9-11e5-9407-1d151da8d3d7.gif)

**Comment by mnquintana** [comment] 2015-12-23 17:19
Thanks for the report! This is a duplicate of https://github.com/atom/release-notes/issues/39 - please subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) for a guide on submitting bug reports (including searching for duplicates first).

**Closed by mnquintana** 2015-12-23 17:19 UTC

**Comment by tomByrer** [comment] 2015-12-23 17:53
Cheers!
