### ISSUE TITLE
Rogue 'config' node in tree view

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#8227] opened 2015-08-05 07:16 UTC
Couldn't find this reported, but due to sheer amount of issues filed, I might have missed it. Sorry if it's a duplicate.

### Issue

When opening Atom settings/preferences with no project directories and tree view visible, an extra `config` node is added to tree view and atom project directories with path `atom://config` and class `Directory`.

This is a strange occurrence, and it breaks some code (see, e.g. https://github.com/atom-haskell/haskell-ghc-mod/issues/31).

What makes matters somewhat worse is this node is saved in application.json and apparently haunts atom project directories even after Atom is restarted.

### How to reproduce

1. Atom Main Menu -> View -> Toggle TreeView. make sure left treeview is visible
2. remove any project folder in the left treeview. 
3. Atom Main Menu -> Atom -> Preferences
then in the left treeview there is only an empty root node named 'config'.  
4. Run `atom.project.getDirectories()` in dev. console

**Comment by izuzak** [comment] 2015-08-06 16:46
Thanks for the report, @lierdakil -- I was able to reproduce this. Sorry that this is causing problems in packages.

/cc @benogle @kevinsawicki not really sure what's causing this, so not sure in which section of the quality initiative issue to put this. Might be worth taking a quick look and see if it's a regression from some recent changes?

**Comment by lierdakil** [comment] 2015-08-06 16:58
If it helps, first time I've got a report about this problem was in late June with Atom 1.0.0, but it "went away" by itself in that particular case. Didn't report then since had no idea on how to reproduce it.

**Comment by maxbrunsfeld** [comment] 2015-08-12 16:52
/cc @mostafaeweda  - I think this was caused by your changes in #6978. Now we unconditionally call `atom.project.addPath` with an opened path, even if it's a URI like `atom://config`.

Maybe `Project::addPath` should check with all of the existing directory providers to see if the given path is a directory, and if not, it should do nothing?

**Comment by vaindil** [comment] 2015-09-04 15:56
Copy/pasting part of my comment on #7576 as this issue happens under the exact same circumstances.

>Same issue here, Windows 10 x64, Atom 1.0.11. Once Atom is initialized the title bar _always_ says `<filename> - atom://config - Atom`. Output from `atom.project.getPaths()` is `["atom://config"]`. `atom --safe` had no effect. Deleting `storage` fixes the problem (the title bar is correct and Settings doesn't open), but once Settings is opened again the problem begins again and persists through program restarts, regardless of whether the Settings tab was closed before restarting the program.

>Not sure if it's related to #8227, but I do have that problem as well--any time I open the Settings menu that `config` folder is added to the tree view indefinitely (it appears under the same circumstances that cause the Settings menu to open).

>In case it matters, I open Atom by clicking on its icon, which is pinned to my taskbar. I pinned it by opening from the Start menu, then right-clicking on the icon and hitting "Pin to Taskbar". The shortcut there has no command-line flags, just the location of `atom.exe`.

**Comment by lierdakil** [comment] 2016-08-22 01:31
So... any progress on this issue at all?

Here's a little nugget of information I completely forgot to mention: running `settings-view:open` command does ***not*** add `atom://config`, while using the menu item (Edit → Preferences) ***does***. This seems somewhat strange at least....

**Comment by lierdakil** [comment] 2016-08-22 01:34
Also something I noticed, `application:open-your-stylesheet` etc create `atom://.atom/...` nodes as well. Doesn't matter if opened from menu or from command pallette.

**Comment by 50Wliu** [comment] 2016-08-28 00:05
@lierdakil Would you be ok with me closing this in favor of #10297, which is more general?

**Comment by lierdakil** [comment] 2016-08-28 00:13
@50Wliu, I don't really care as long as this gets fixed....

**Closed** 2016-08-28 00:15 UTC
Labels: bug
