### ISSUE TITLE
"Open Recent" fails to open projects after closing all previously open Atom windows

### ISSUE THREAD

**Issue by mattsparks** [atom/atom#15085] opened 2017-07-24 23:15 UTC
### Prerequisites

* [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [n/a] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After closing a number of Atom windows (I tested between 1 and 4, all different projects), selecting a project from `File -> Open Recent` results in the project not being opened.

### Steps to Reproduce

1. Open any number of Atom windows
2. Close all opened windows.
3. Select a project from `File -> Open Recent`

**Expected behavior:** 
The selected project would open.

**Actual behavior:** 
The project doesn't open.

**Reproduces how often:**
Since I noticed the behavior this morning, I'm able to reproduce it 100% of the time.

### Versions

```
MacOS Sierra (10.12.6)

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0
```
### Additional Information
I'm not seeing this behavior when I have at least one project window open.

**Comment by rsese** [comment] 2017-07-25 09:13
Thanks for taking the time to contribute!

We noticed that this looks like basically a duplicate of https://github.com/atom/atom/issues/12508 so you can subscribe there for updates if you'd like.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-25 09:13 UTC
