### ISSUE TITLE
Atom Is Really Slow At Refocusing.

### ISSUE THREAD

**Issue by RekkyRek** [atom/atom#13888] opened 2017-02-27 17:16 UTC
When refocusing atom it takes about 1 - 2 seconds to capture the cursor.
[Video Examle](https://www.youtube.com/watch?v=RY0iI3we7a4)

I have a really high spec system so that is not the problem (i7 4790k, 16gb RAM, GTX 1080, Generic Sandisk SSD)

**Comment by 50Wliu** [comment] 2017-02-27 18:08
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #9544. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-27 18:08 UTC
