### ISSUE TITLE
Release Notes can't update

### ISSUE THREAD

**Issue by angelia-yuqi** [atom/atom#7810] opened 2015-07-09 00:43 UTC
When I install Atom 1.0.0
 Help->Release Notes is not update, I click "Restart and update" button, nothing happens.
How Can I update Atom Release Notes.
thank you very much

**Comment by batjko** [comment] 2015-07-09 07:50
I noticed this as well. Win8.1. Updating from v1.0.0 to v1.0.2.

Clicking "Check for new version" also results in the false "Already on latest version" message.

However, I can confirm that everything is downloaded (the v1.0.2 folder gets created and the `atom.cmd` file links to that latest version.

And when I close and restart Atom manually, it does use the latest version as expected.

So the download appears to work, just the usual notification that a newer version is ready and Atom needs to be restarted, does not make an appearance.

**Comment by andya9** [comment] 2015-07-09 18:16
I can confirm this too on linux

**Comment by 50Wliu** [comment] 2015-07-09 21:27
> I can confirm this too on linux

The Linux version doesn't have an auto updater built in.

**Comment by andya9** [comment] 2015-07-10 06:36
@50Wliu I didn’t mean the autoupdater, but the Release Notes blue icon that appears first time after an update (the one from release-notes package). Sorry, I thought angelia was referring to that

**Comment by batjko** [comment] 2015-07-10 08:07
@andya9 Because on Linux there isn't an auto-updater, I suspect there won't be a release notes icon. 
I might be wrong here ( @50Wliu? ), but isn't that squirrel icon triggered by the auto-updater on Windows and Mac?

**Comment by andya9** [comment] 2015-07-10 08:31
@bat No, no, we have the squirrel too, I’m using atom since 0.170 or so on linux and always had it.
Simply, when clicking it we get to a page in atom whith the changelog of last versions

**Comment by batjko** [comment] 2015-07-10 09:43
Ah ok. thanks for clarifying.

**Comment by mnquintana** [comment] 2015-08-05 15:16
This is a duplicate of https://github.com/atom/atom/issues/5692 – please subscribe there for updates.

**Closed by mnquintana** 2015-08-05 15:16 UTC
