### ISSUE TITLE
"Search in Directory" no longer appears in the context menu when right-clicking on project tree entries

### ISSUE THREAD

**Issue by hughlomas** [atom/atom#14364] opened 2017-05-05 18:09 UTC
![image](https://cloud.githubusercontent.com/assets/187210/25758275/e7a10e6c-319b-11e7-900f-1ce71eb31308.png)

Somewhere in the last 2-4 weeks, my "Search in directory" option has disappeared from the context menu on the project tree.

This featured heavily in my workflow, I use it constantly throughout the day. Opening the global search with ctrl+shift+f is tedious because it forces users to manually type their search scope.

Was it intentionally removed or did it disappear as a regression?

Is there a way to re-enable it?

Versions:

Atom    : 1.17.0-beta4
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by rsese** [comment] 2017-05-05 18:16
Thanks for the report!  This was a regression and is fixed in 1.17.0-beta5 which is released today.  As mentioned below, the dupe issue is https://github.com/atom/find-and-replace/issues/887.

As a side note, it would be great if you could fill out the issue template completely when opening issues, it's super helpful to know if you done things like tried in safe mode, etc.

---

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/887. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-05 18:16 UTC
