### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/AppData\Local\atom\node_modules\highli...

### ISSUE THREAD

**Issue by TheGlamGeek** [atom/atom#16504] opened 2018-01-07 01:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\ShaTo\AppData\Local\atom\node_modules\highlights\gen\grammars.json'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'C:\Users\ShaTo\AppData\Local\atom\node_modules\highlights\gen\grammars.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:468:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Highlights.module.exports.Highlights.loadGrammarsSync (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/highlights/lib/highlights.js:238:34)
    at Highlights.module.exports.Highlights.highlightSync (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/highlights/lib/highlights.js:40:18)
    at CodeBlock.update (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/lib/code-block.js:33:62)
    at new CodeBlock (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/lib/code-block.js:23:16)
    at render (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:17:31)
    at addChildren (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at addChildren (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at updateChildren (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:109:40)
    at patch (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:15:15)
    at updateSync (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:108:26)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:72:13
    at DefaultScheduler.performUpdates (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/styleguide/node_modules/etch/lib/default-scheduler.js:48:40)
```

### Commands

```
```

### Non-Core Packages

```
atom-monokai 0.10.9 
```

**Comment by rsese** [comment] 2018-01-08 18:54
Thanks for the report!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15852 so you may want to subscribe there for updates.  If you have steps to reproduce the error, please let us know in https://github.com/atom/atom/issues/15852.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-01-08 18:54 UTC
