### ISSUE TITLE
after updating a package, it is enabled automatically

### ISSUE THREAD

**Issue by stevemao** [atom/atom#8405] opened 2015-08-17 06:58 UTC
Should it still be disabled if it was? Or update all shouldn't update disabled packages?

**Comment by mnquintana** [comment] 2015-08-17 11:17
Thanks for the report! This looks like a duplicate of https://github.com/atom/settings-view/issues/603 though - closing this out in favor of that issue.

**Closed by mnquintana** 2015-08-17 11:17 UTC
