### ISSUE TITLE
Atom exit when drag-drop a firefox tag across double screens.

### ISSUE THREAD

**Issue by li-thy-um** [atom/atom#6370] opened 2015-04-14 05:01 UTC
When drag-drop a firefox tag across screens, the atom(0.190.0) will exit. On Ubuntu 14.04, Firefox 37.01. Here's the console log . 

 [23715:0414/125813:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 195ms
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[23751:0414/125814:INFO:renderer_main.cc(212)] Renderer process started
[23715:0414/125816:INFO:CONSOLE(8)] "activate linter-erb", source: /home/lithium/.atom/packages/linter-erb/lib/init.coffee (8)
[23715:0414/125816:INFO:CONSOLE(7)] "activate linter-xmllint", source: /home/lithium/.atom/packages/linter-xmllint/lib/init.coffee (7)
[23715:0414/125816:INFO:CONSOLE(59)] "Window load time: 2382ms", source: file:///usr/share/atom/resources/app/static/index.js (59)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 353 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by 50Wliu** [comment] 2015-04-14 11:46
Duplicate of #3593, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-14 11:46 UTC
