### ISSUE TITLE
Unicode not displaying in most fonts

### ISSUE THREAD

**Issue by lmagno** [atom/atom#6366] opened 2015-04-14 00:30 UTC
Suddenly today Atom doesn't seem capable of displaying unicode in most fonts. I've tried a bunch of font families (droid, consolata, inconsolata, monospace, courier, sans-serif, arial, impact, ubuntu, ubuntu mono, etc) and the apparently only one who works is sans:
![sans](https://cloud.githubusercontent.com/assets/4805640/7128040/2224beaa-e223-11e4-83da-1606213d9126.png)

But in monospace:
![monospace](https://cloud.githubusercontent.com/assets/4805640/7128041/2bfc89e4-e223-11e4-878f-9c19b718c347.png)

And I don't have any problem of seeing unicode in other applications, just Atom.

Might help:
> lucas ~> apm -v
> apm  0.157.0
> npm  2.5.1
> node 0.10.35
> python 2.7.6
> git 1.9.1
> lucas ~> uname -a
> Linux magno-Z97-D3H 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 50Wliu** [comment] 2015-04-14 00:51
Closing as a duplicate of #6214, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-14 00:51 UTC
