### ISSUE TITLE
Foreground dialog box does not acquire focus

### ISSUE THREAD

**Issue by falcondai** [atom/atom#17224] opened 2018-04-26 16:08 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The newly opened dialog box in the foreground does not acquire focus if it is opened after another dialog box.

![atom-pane-focus-bug](https://user-images.githubusercontent.com/997426/39316409-b35262c6-493e-11e8-84f9-dd5971521d3b.gif)

### Steps to Reproduce

I have seen this happened with many dialog boxes. For example, with file switcher and command selector.
1. `Cmd + t` to bring up the file switcher dialog box.
2. `Shift + Cmd + p` to bring up the command selector dialog box.

**Expected behavior:** [What you expect to happen]
The command selector acquires focus.

**Actual behavior:** [What actually happens]
The command selector does not acquire focus and the text editor does instead.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime 

### Versions
OS: macOS 10.13.4
Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-04-26 18:31
Thanks for contributing!

This looks like a duplicate of https://github.com/atom/atom/issues/14325 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-26 18:31 UTC

**Comment by falcondai** [comment] 2018-04-26 18:41
Thanks. I would love to hunt this down and patch it. Any pointer?

**Comment by rsese** [comment] 2018-04-27 20:42
I don't know myself but I'll ask around for you and let you know :bow:
