### ISSUE TITLE
Can't uninstall packages

### ISSUE THREAD

**Issue by LNWPOR** [atom/atom#7371] opened 2015-06-22 17:50 UTC
I just have a problem that when i click disable button and then click the uninstall button on the package and then I think that this package is remove because I can't see it in the package list in the setting.but it not because when i try to reinstall it by searching the package name again ,the uninstall and enable button still show on the package and i can't install it because no install button.Nothing happen when I click that uninstall or enable button.
Thx for help and sorry for my English. :(
I use Windows 8.1

**Comment by izuzak** [comment] 2015-06-23 15:07
Thanks for the report, @LNWPOR -- this looks like a duplicate of https://github.com/atom/settings-view/issues/507.

For now, to work around the issue, you can either remove the disabled package from the `disabledPackages` array in your config.cson file (Atom -> Open your config), or you can use `apm` to install the package, as suggested in that other issue.

**Closed by izuzak** 2015-06-23 15:07 UTC
