### ISSUE TITLE
Edition unresponsive/slow with a 300k json file

### ISSUE THREAD

**Issue by Loda** [atom/atom#10577] opened 2016-01-25 16:53 UTC
Hi,

overall, Atom is the best editor out there. None Obstante, I got an issue when editing a 300k json file.

Especially, when using "search/replace" dialog (bottom bar visible + search result highlight)
(if you just open it, and do no search nor edition : no problem)

The editor get slow or freez ("not responsive" system dialog). The key press stop being process until atom "wake up" and process them all at once.

my json:
- file extension : ".jsonExtra"
- 330k (please, don't call that "big")
- max line length : 400char
- num of line: 7300
- a valid json with some unicode char
- no syntaxe higlight / nor folding activated

The json is generated using python code:

              jsonFile = codecs.open(jsonFileName, 'w', encoding='utf-8')
              out = json.dumps(self.jsondata, sort_keys=True, indent=4, ensure_ascii=False)
              jsonFile.write(out)

my system:
- Ubunutu 14.04 LTS / 64 bit / locale:EN
- Atom version 1.3.0 (from help menu) / locale: EN
- clean install : No special extension / plugin. I did disable the "whitespace" extension.
- dual monitor (atom on secondary monitor)
- proc : Intel® Core™ i5-4590 CPU @ 3.30GHz × 4
- with "atom --safe" the problem does not reproduce
- with "atom" and some extension disable(find-and-replace, language-json, spell-check, whitespace, Autocomplete Atom Api), the system dialog does not pop up, but atom is slower that you could expect for a 300k file. (on my system, gedit can edit this file without problem. very fluid)

I did report the issue in atom's project (and not to the extensions' project) because it seem to be a "cumulative" issue. Like if the extension were using all the CPU time of the process.

related ?
- https://github.com/atom/atom/issues/6607
- https://github.com/atom/atom/issues/2902

regards,

**Comment by maxbrunsfeld** [comment] 2016-01-25 19:56
Can you try disabling the `spell-check` and `autocomplete-plus` packages, and report whether that improves the editing experience?

**Comment by Loda** [comment] 2016-02-03 11:16
Hi max,

I try without theses extension. I did not get the "not responsive" system dialog, but the editor is still way too slow for a nice UX.

eg: if I do a CAP-cursorDown to select a line or a few CTRL-cursorRight to go at the end of the line, the UI can take 0.5-1s to react.

I don't know if this is important, but I also (often) got the "project view" visible (left side panel with the file tree)

regards,

**Comment by jsieler** [comment] 2016-02-24 16:52
Same issue. My 900kb large JSON produces Atom just in hang. Was trying just to disable all packages, even core packages. Same, hanging...

**Comment by mnquintana** [comment] 2016-06-29 00:42
This seems like a duplicate of https://github.com/atom/atom/issues/8864 – let's keep the discussion going there.

**Closed by mnquintana** 2016-06-29 00:42 UTC
Labels: more-information-needed, performance
