### ISSUE TITLE
Don't open the directory when I just want to open a single file.

### ISSUE THREAD

**Issue by lichenhao** [atom/atom#10223] opened 2015-12-30 11:32 UTC
RT,when I open a single file, don't open the directory of that file. It's more slowly than just open the file only.

**Comment by mnquintana** [comment] 2015-12-30 14:51
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/8030 – feel free to subscribe there for updates.

**Comment by midwire** [comment] 2016-01-27 18:24
After reading #8030, I don't believe this is a duplicate issue.  Let me describe it this way. When I run the following command from a terminal:

```
/usr/local/bin/atom /Users/cblackburn/.env /Users/cblackburn/.bashrc
```

Atom will open with the `~/.env` directory in the sidebar, as expected. But it also opens with my home directory `cblackburn` in the sidebar as well because I loaded `.bashrc` which resides in my home directory.

![_bashrc_ __users_cblackburn](https://cloud.githubusercontent.com/assets/178386/12623654/c3a64afe-c4f0-11e5-904b-bc098176cb1e.png)

It loads the containing directory of the file, but I don't think it should. I didn't ask it to load the directory `cblackburn`, but only a file which happens to exist inside that directory `.bashrc`.

**Comment by mnquintana** [comment] 2016-01-28 05:28
@midwire Thanks for elaborating! I think you're right that this isn't a duplicate of #8030 after all, though I think this is a duplicate of another issue. If I find it, I'll add a comment here.

**Comment by Ben3eeE** [comment] 2016-10-10 20:45
This is a duplicate of https://github.com/atom/atom/issues/8934 - Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-10 20:45 UTC
Labels: duplicate
