### ISSUE TITLE
[Feature Request] "Find in opened tabs" functionality

### ISSUE THREAD

**Issue by cybernetlab** [atom/atom#15946] opened 2017-10-20 07:16 UTC
### Description

Now we have a `Find in project` item in a `Find` menu and in a project context menu. It would be nice to have a `Find in opened tabs` functionality

### Steps to Reproduce

1. open atom

**Expected behavior:**

I want to be able to search a text in opened tabs only.

**Actual behavior:**

There are no such functionality

**Reproduces how often:**

Always

### Versions

```
$ atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by 50Wliu** [comment] 2017-10-20 08:50
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/find-and-replace#241. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-10-20 08:50 UTC
