### ISSUE TITLE
Soft Wrap in Japanese

### ISSUE THREAD

**Issue by m3at** [atom/atom#8611] opened 2015-09-01 04:44 UTC
On Mac OS X 10.10.3

With the `Soft Wrap` option turned on, lines containing **Japanese character** are **not wrapped correctly**, leaving approximately 14 characters out of view. Seems to occur regardless of the window size.

![screen shot 2015-09-01 at 13 37 36](https://cloud.githubusercontent.com/assets/3440771/9596362/b9f13192-50ae-11e5-830f-98c59d9696d0.png)

**Comment by izuzak** [comment] 2015-09-01 11:43
Thanks for the report -- this looks like a duplicate of https://github.com/atom/atom/issues/1783, so I'm closing this in favor of that issue.

**Closed by izuzak** 2015-09-01 11:43 UTC

**Comment by m3at** [comment] 2015-09-02 03:27
Indeed, I checked similar problems poorly, sorry. Thanks for the correction
