### ISSUE TITLE
Ignore dot files/folders for packages

### ISSUE THREAD

**Issue by zimme** [atom/atom#7718] opened 2015-07-05 10:17 UTC
See this issue for more details, https://github.com/TypeStrong/atom-typescript/issues/365

**Comment by mnquintana** [comment] 2015-07-05 12:00
Thanks for the report! This is a duplicate of https://github.com/atom/settings-view/issues/348 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-05 12:00 UTC

**Comment by zimme** [comment] 2015-07-05 12:02
:+1:
