### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by netmou** [atom/atom#14471] opened 2017-05-18 02:38 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (D:\Program Files\Atom x64\resources\electron.asar\browser\objects-registry.js:41:28)
    at EventEmitter.<anonymous> (D:\Program Files\Atom x64\resources\electron.asar\browser\rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (D:\Program Files\Atom x64\resources\electron.asar\browser\api\web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At D:\Program Files\Atom x64\resources\electron.asar\renderer\api\remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (D:/Program Files/Atom x64/resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (D:/Program Files/Atom x64/resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (D:/Program Files/Atom x64/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (D:/Program Files/Atom x64/resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (D:/Program Files/Atom x64/resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (D:/Program Files/Atom x64/resources/app/src/atom-environment.js:663:1)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (D:/Program Files/Atom x64/resources/app/src/atom-environment.js:697:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (D:/Program Files/Atom x64/resources/app/src/window-event-handler.js:184:1)
    at D:/Program Files/Atom x64/resources/app/src/window-event-handler.js:3:1
```

### Commands

```
     -7:08.2.0 intentions:highlight (input.hidden-input)
     -7:07.9.0 core:save (input.hidden-input)
  4x -3:11.8.0 intentions:highlight (input.hidden-input)
     -3:11.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -3:10.9.0 core:paste (input.hidden-input)
  7x -3:06.6.0 core:backspace (input.hidden-input)
     -3:04.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-paths 1.0.5 
change-case 0.6.5 
color-picker 2.2.5 
docblockr 0.9.4 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.6 
git-plus 7.8.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.61.0 
language-batch 0.4.0 
linter 2.1.4 
linter-htmlhint 1.3.3 
linter-jshint 3.1.2 
linter-php 1.3.2 
linter-ui-default 1.5.4 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-git-diff 4.3.1 
minimap-selection 4.4.0 
monokai 0.24.0 
php-twig 4.0.0 
```

**Comment by 50Wliu** [comment] 2017-05-18 02:41
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #11692. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-18 02:41 UTC
