### ISSUE TITLE
Individual grammar editor tab lengths revert to incorrect settings on global tab length change.

### ISSUE THREAD

**Issue by gandm** [atom/atom#11840] opened 2016-05-25 16:59 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)? Can't run in safe mode atom --safe doesn't seem to do it
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Any grammar e.g. language-javascript will have it's local tab lengths settings changed dynamically to non defined values.

### Steps to Reproduce

1. Change language-javascript's grammar tab length to 6
2. config.cson will show 

![image](https://cloud.githubusercontent.com/assets/2313237/15548477/7952c064-22a0-11e6-8f12-f2fe52c5a533.png)
3. Change the global tab length to 4
4. config.cson will show

![image](https://cloud.githubusercontent.com/assets/2313237/15548558/ece79220-22a0-11e6-8df6-af4ac2e7c07e.png)
![image](https://cloud.githubusercontent.com/assets/2313237/15548477/7952c064-22a0-11e6-8f12-f2fe52c5a533.png)
5. Change the global tab length back to default: 2
6 config.cson now shows

![image](https://cloud.githubusercontent.com/assets/2313237/15548647/40bbaa62-22a1-11e6-9570-a5450e906ec6.png)
![image](https://cloud.githubusercontent.com/assets/2313237/15548477/7952c064-22a0-11e6-8f12-f2fe52c5a533.png)
7 Now change language-javascript's grammar tab length to default: 2
8 config.cson now shows

![image](https://cloud.githubusercontent.com/assets/2313237/15548647/40bbaa62-22a1-11e6-9570-a5450e906ec6.png)
9 Now change the Global tab length to 4
10 config.cson now shows
![image](https://cloud.githubusercontent.com/assets/2313237/15548738/a7820296-22a1-11e6-8457-9b2897b1ffcf.png)
![image](https://cloud.githubusercontent.com/assets/2313237/15548745/b02d3ea6-22a1-11e6-9b49-50344009563f.png)
11 The grammar's trab length has been set back to it's last known non-default value!
EDIT: sorry I left out a step. If the default global value is not set back to default:2 then the language-JavaScript value remains at 4.

**Expected behavior:** 
The grammar should revert back to it's last value - in the above case default: 2

**Actual behavior:*
The grammar had it's tab length changed back to it's last known non-default value.

### Versions
![image](https://cloud.githubusercontent.com/assets/2313237/15548911/1d297ba0-22a2-11e6-9f2e-9806e73b1bd1.png)
![image](https://cloud.githubusercontent.com/assets/2313237/15548926/2f6c40b8-22a2-11e6-893f-0641c219c22a.png)

**Comment by gandm** [comment] 2016-06-03 15:52
Closed due to lack of interest :disappointed:

**Comment by Zireael07** [comment] 2016-06-03 18:09
Why close? It may take some time for maintainers to notice it.

Pinging @50Wliu @izuzak

**Comment by gandm** [comment] 2016-06-03 19:01
@Zireael07 it's not critical and can be worked around.

**Comment by 50Wliu** [comment] 2016-06-03 20:38
I don't see the problem here: since you changed language-javascript's setting back to the default value, then it should be controlled by the overarching default.  Or am I missing something?

Also @Zireael07 I don't believe @izuzak works on Atom anymore.

**Comment by gandm** [comment] 2016-06-03 20:59
@50Wliu in step 9 I change the global to 4 but it also changes the JavaScript grammar to 4. It should have left it as it was set in step 7 i.e. default which is 2.

**Comment by gandm** [comment] 2016-06-03 21:07
In other words it is impossible to set a global of 4 spaces but a specific grammar spacing to 2 because it becomes 'default' which the global can override.

**Comment by 50Wliu** [comment] 2016-06-03 21:35
Ok, thanks for the clarification.

**Comment by pepjo** [comment] 2016-06-18 15:37
Yep! It's also impossible to set a "soft wraping" on a specific language and not set it on the general settings or otherwise. When you change it either on an specific language or on the global settings it changes everywhere, really anoying.

**Comment by lee-dohm** [comment] 2016-06-30 01:28
This is a duplicate of https://github.com/atom/settings-view/issues/774. Please subscribe there for updates.

**Closed by lee-dohm** 2016-06-30 01:28 UTC
Labels: bug
