### ISSUE TITLE
Uncaught Error when drag-n-dropping file with comma in the name

### ISSUE THREAD

**Issue by treszkai** [atom/atom#19368] opened 2019-05-20 13:22 UTC
Steps to reproduce reliably:

0. Start Atom with `atom --safe`
1. Add a project folder
2. Create file `foo,bar` and directory `tmp` in the project. (Can also be created before Atom is started.)
3. In the tree view, try to move `foo,bar` to `tmp` with drag-and-drop.

Important: the file name must contain a comma.

![image](https://user-images.githubusercontent.com/30578582/58024698-177a5900-7b13-11e9-9852-c6058a62b587.png)

[Link to screen recording](https://postimg.cc/t1g2KWZQ)

---------------------

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/bar'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/bar'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:925724)
    at TreeView.t.exports.TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:931478)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:906335)
```

### Commands

```
     -0:27 application:add-project-folder (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by 50Wliu** [comment] 2019-05-20 14:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/tree-view#1282. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2019-05-20 14:29 UTC
