### ISSUE TITLE
Windows: beta breaks right-click "Open in Atom"ep

### ISSUE THREAD

**Issue by tomByrer** [atom/atom#10164] opened 2015-12-23 01:23 UTC
1.  Install main channel
2.  Right-click "Open in Atom" works
3.  Install beta
4.  Right-click will not open either version

**Comment by jgaines** [comment] 2016-01-26 22:17
A similar thing happened to me under windows 7.  What appears to happen is that when you install beta, it removes the stable version (contrary to the claim that the two can be run side-by-side).  The failure of the right-click to "Open in Atom" seems to also affect installing a new version over an old version.  The sequence of events which reproduced it for me was:

1. Install stable 1.4.0
2. "Open in Atom" works
3. install stable 1.4.1 (without first uninstalling 1.4.0)
4. "Open in Atom" is now broken
5. Install beta 1.5.0-beta1
6. "Open in Atom" still broken and 1.4.1 is uninstalled.

The issue with "Open in Atom" appears to be that the installer won't overwrite the existing registry settings so the "Open in Atom" command is still pointing to the now missing 1.4.0 install.  (Which is the same as what appears to be happening in the beta install over stable scenario Tom described.)

## Workaround for "Open in Atom" being broken

1. Completely uninstall all atom installs.
2. Reinstall just one atom (stable or beta).

**Comment by damieng** [comment] 2016-05-05 21:00
Duplicate of #9247

**Closed by damieng** 2016-05-05 21:00 UTC
Labels: needs-reproduction
