### ISSUE TITLE
PHP syntax mixup

### ISSUE THREAD

**Issue by Bendraneu** [atom/atom#5976] opened 2015-03-16 05:27 UTC
Latest Atom version 0.187.0 (on OS X) does not highlight the following PHP code correctly:

`$cvsData = date("Y-m-d H:i:s") . ";" . $_POST["venue"] . ";" . $_POST["salutation"] . ";" . $_POST["surname"] . ";" . $_POST["name"] . ";" . $_POST["company"] . ";" . $_POST["phone"] . ";" . $_POST["email"] . ";" . $_POST["address"] . ";" . $_POST["plz"] . ";" . $_POST["place"] . "\n";`

It stops inking the variables starting with $_POST["phone"].

![bildschirmfoto 2015-03-16 um 06 28 13](https://cloud.githubusercontent.com/assets/4235935/6661029/a9d153a2-cba5-11e4-9547-83c739f68597.png)

**Comment by postcasio** [comment] 2015-03-16 09:05
Looks like a duplicate of https://github.com/atom/atom/issues/1667. Please subscribe there for updates.

**Closed by postcasio** 2015-03-16 09:05 UTC
