### ISSUE TITLE
Atom randomly disables my Wacom tablet

### ISSUE THREAD

**Issue by folosophy** [atom/atom#13485] opened 2016-12-21 23:15 UTC
### Prerequisites

* [YES] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? 
* [YES] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [YES] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [YES] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [YES] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [YES] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Recently, Atom started randomly preventing my Wacom tablet from being able to click or select anything. It works fine if I just stay in Atom, but if I switch to another program, then back to Atom, the tablet stops functioning normally. 

This only happens when I have Atom open, but it effects all applications. For example, if I start Atom, switch to Chrome, then back to Atom, then back to Chrome, I now can't click/select anything with the tablet in any app (not just Atom).

When I don't have Atom open, the issue does not occur.

### Steps to Reproduce

1. Open Atom
2. Switch to another application
3. Switch back to Atom (Wacom tablet will now not click or select anything)

### Versions

Atom: 1.12.7
Mac: Sierra, 10.12

**Comment by lee-dohm** [comment] 2016-12-23 19:37
Can anyone who has a Wacom tablet reproduce this problem?

**Comment by simurai** [comment] 2017-01-13 07:39
Tried to reproduce this with my old Wacom Bamboo tablet (MTE-450), but everything works fine. Also when switching between other applications. But only tried it like 5mins.

> @folosophy Atom started randomly preventing my Wacom tablet from being able to click or select anything.

Does hovering still work? Like when moving over a button/link or so, does the cursor change, or is it completely unresponsive?

Might also be worth trying with the [latest drivers](http://www.wacom.com/en-us/support/product-support/drivers)?

```
Atom    : 1.14.0-dev-ef99fbc
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
OS: macOS 10.12.2
```

**Comment by lee-dohm** [comment] 2017-01-28 22:47
Thanks for contributing!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13485#issuecomment-272380321. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by lee-dohm** 2017-01-28 22:47 UTC
Labels: help-wanted, mac, needs-reproduction

**Comment by jefersontonin** [comment] 2017-02-21 20:59
I can reproduce this problem in my setup.
I can't click or select anything when I'm back to Atom from another application.
But hovering on screen elements still working.
After few attempts my tablet woke up and the click function start to work again.

Atom 1.14.3 x64
Mac Pro: OSX El Capitan 10.11.5

**Comment by willfrombrazil** [comment] 2017-03-13 15:47
I'm having the exact same issue. Sometimes ATOM won't recognise wacom's pen click on a open document. The project folders view is always clickable.

Mac OS 10.10.5
Wacom CTL 480 Driver 5.3.7-6 (10.9x - 10.12x)
Atom 1.12.6

**Comment by hexrcs** [comment] 2017-04-08 11:55
Exactly the same problem here :( 

Pen click works on project folder view and PlatformIO terminal, and all other UI elements, but doesn't work with opened document tabs or the content inside the tab. However it also works in Settings tab. Had vim-mode-plus, autocomplete-python and kite installed, now all disabled, still won't work. The touch function on the Wacom tablet works though. Weird.

Mac OS 10.12.4
Atom 1.15.0 x64

**Comment by folosophy** [comment] 2017-04-08 14:02
In my case, I don't think this is a problem with Atom. After much testing, it seems to be caused by Adobe products (Illustrator, in specific, though I'm not 100% sure). 

Strangely enough, problems start occurring when I use the pen with Illustrator, then switch to Chrome, then back to Atom. No idea why, but this causes pen "clicks" to stop registering.

Bizarrely, if you hit one of the shortcut buttons on the tablet, this seems to clear the problem temporarily, but it soon becomes completely unresponsive when you switch to another app.

SO... I don't think this is a problem with Atom. I think Wacom is just buggy as hell, and if anything, it's Adobe that's causing issues (at least for me).

**Comment by hexrcs** [comment] 2017-04-08 17:04
In my case I don't have any Adobe apps running. :( Just Chrome, PyCharm (launched via JetBrains toolbox app), Sublime Text 3 and Terminal.

I just tested. With the above mentioned apps running, I opened Atom, closed the welcome tab, typed a few letters then opened a new tab, typed another few letters - the pen clicks stops working from then on. Switched back and forth apps, hit the shortcut buttons, didn't resolve temporarily.

All the other UI elements seem to react just fine, it's only the editor section, as well as the tab title bar (sorry I don't know the term for it) that's not reacting, so I can't switch editor tabs with pen click - settings tab work though. I can also click on and change the encoding and language highlight.

The touch pad function of my tablet always worked.

I tried the buttons on my pen, which I have assigned to right click and middle click, they both worked, with right click bringing out the context menu at correct positions. I re-assigned one of the button to left-click, the normal pen tip click into right-click, the button didn't work, whereas the normal pen tip brings out the context menu normally. 

My guess is that some of my behaviour combinations have triggered either Atom or the driver or both into thinking I might have wanted to do some controls other than just left-clicking. I've set up an application profile with different double click distance/ tip firmness settings for Atom in Wacom's driver/control center, problem remained. 

Haven't encountered any similar issues with any other apps yet. Never got problems with text selection in Chrome so far as well.

**Comment by hexrcs** [comment] 2017-04-08 17:21
Should I open a new issue? As what I'm experiencing now is not exactly the same as OP - the pen click works in other applications.

**Comment by Johnfredadams** [comment] 2017-06-06 15:24
I have the same issue - pen click not working when in Atom, but works as soon as I switch out to other apps.

**Comment by jj-carlson** [comment] 2017-09-06 19:25
I too experience the same issue, but it has even occurred just within Atom without my switching to another program. I'll have just finished editing selected text—text that I selected using my Wacom Intuos Pro—when I try to select another line of characters within the application, only to have it fail to do so.

My feeling is that it's more to do with the tablet than Atom, though, because I've seen random buggy behavior in other programs. For example, hovering over menus with drop-downs will not result in the menu expanding (Chrome, Firefox, etc.) at times while using the tablet, and other times the menu does expand.

**Comment by aaronpctv** [comment] 2017-12-11 21:05
Same problem, but it only started happening when I made custom settings for Atom in the Wacom Tablet settings panel. Deleted custom settings, now works fine with Global Settings.

**Comment by sogen** [comment] 2018-04-22 04:37
Similar to @aaronpctv , what solved it on my side was Selecting **Default** for ExpressKeys in All Other:
![screen shot 2018-04-21 at 9 29 51 pm](https://user-images.githubusercontent.com/34488214/39091604-0609946c-45ac-11e8-979b-8cfb717a6843.png)
