### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\F:\PROGRAMMING SOFTWARE\atom\app-1....

### ISSUE THREAD

**Issue by shikharrocks** [atom/atom#21531] opened 2020-10-18 14:27 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\F:\PROGRAMMING SOFTWARE\atom\app-1.52.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:138

Error: The specified module could not be found.
\\?\F:\PROGRAMMING SOFTWARE\atom\app-1.52.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (F:/PROGRAMMING SOFTWARE/atom/app-1.52.0/resources/app/static/<embedded>:1:735077)
    at get_KeyboardLayoutManager (F:/PROGRAMMING SOFTWARE/atom/app-1.52.0/resources/app/static/<embedded>:14:2716464)
    at get_manager (F:/PROGRAMMING SOFTWARE/atom/app-1.52.0/resources/app/static/<embedded>:14:2716566)
    at Object.getCurrentKeyboardLayout (F:/PROGRAMMING SOFTWARE/atom/app-1.52.0/resources/app/static/<embedded>:14:2716692)
    at e.keystrokeForKeyboardEvent (F:/PROGRAMMING SOFTWARE/atom/app-1.52.0/resources/app/static/<embedded>:14:1047827)
    at KeymapManager.keystrokeForKeyboardEvent (F:/PROGRAMMING SOFTWARE/atom/app-1.52.0/resources/app/static/<embedded>:11:1228394)
    at KeymapManager.handleKeyboardEvent (F:/PROGRAMMING SOFTWARE/atom/app-1.52.0/resources/app/static/<embedded>:11:1226379)
    at WindowEventHandler.handleDocumentKeyEvent (F:/PROGRAMMING SOFTWARE/atom/app-1.52.0/resources/app/static/<embedded>:11:284820)
```

### Commands

```
     -0:06.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 3.1.1 
linter-eslint 8.5.5 
linter-ui-default 2.1.2 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by sadick254** [comment] 2020-10-19 07:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-10-19 07:13 UTC
