### ISSUE TITLE
Uncaught Error: ENOENT, open '/home/stramel/Projects/Test/src/common/services/userService.js'

### ISSUE THREAD

**Issue by stramel** [atom/atom#6025] opened 2015-03-18 20:11 UTC
[Enter steps to reproduce below:]

1. Open a git project in Atom
2. Open a file that will be modified when switching branches
3. Open a terminal and checkout the branch with the modified file

**Atom Version**: 0.188.0-f57abc9
**System**: linux 3.13.0-46-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open '/home/stramel/Projects/Test/src/common/services/userService.js'

```
At events.js:94

Error: ENOENT, open '/home/stramel/Projects/Test/src/common/services/userService.js'
  at Error (native)

```

### Commands

```
     -7:09.7 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -7:03.9 core:confirm (atom-text-editor.editor.mini)
     -7:03.2 find-and-replace:show (atom-text-editor.editor)
  2x -6:59.9 core:backspace (atom-text-editor.editor)
     -6:58.0 core:save (atom-text-editor.editor)
     -6:00.3 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -5:57.5 core:confirm (atom-text-editor.editor.mini)
     -5:52.8 go-to-line:toggle (atom-text-editor.editor)
     -5:51.4 core:confirm (atom-text-editor.editor.mini)
  2x -4:14.1 core:backspace (atom-text-editor.editor)
     -2:27.9 core:undo (atom-text-editor.editor)
     -0:33.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/stramel/Projects",
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-gjslint",
      "autocomplete-paths"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 120,
    "showIndentGuide": true,
    "showInvisibles": true,
    "scrollPastEnd": true,
    "fontSize": 13,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.22.3
atom-color-highlight, v3.0.8
atom-jasmine, v0.5.0
autoclose-html, v0.15.0
autocomplete-plus, v2.5.0
autocomplete-snippets, v1.2.0
editorconfig, v0.3.3
file-icons, v1.5.1
highlight-line, v0.10.1
highlight-selected, v0.9.1
linter, v0.12.0
linter-jscs, v1.9.0
linter-jshint, v0.1.0
linter-less, v0.3.1
monokai, v0.12.0
pain-split, v1.3.1
project-manager, v1.15.5
project-palette-finder, v2.4.16

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-03-18 21:28
Thanks for the report, @stramel. I wasn't able to reproduce this, though -- the file updates just fine for me in the editor after I switch branches. Have you been able to reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) (noticed you have quite a few packages installed)? And just to make sure -- this happens every time for any file?

Atom Version: 0.188.0-609a661
System: OSX 10.10.2

**Comment by stramel** [comment] 2015-03-20 16:28
@izuzak Sorry, I'm really not sure how to reproduce this every time. I just ran into the issue again, this time I did a `$ git checkout -- .`  I will have to try safe mode sometime when I have time.

**Comment by stramel** [comment] 2015-03-23 20:30
@izuzak It is now happening every time for the open and selected file that changes when doing a git command that changes the contents of the file.

Atom Version: 0.188.0-6c38562
System: Ubuntu 14.04

**Comment by izuzak** [comment] 2015-03-24 11:09
@stramel Strange, I still can't reproduce. Here's what might help: a GIF which clearly demonstrates what exactly you're doing (with Atom running in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)). Could you record such a GIF and post it here together with a set of instructions which explain what's going on in the GIF?

**Comment by 50Wliu** [comment] 2015-04-01 22:34
Closing in favor of #6210.

**Closed by 50Wliu** 2015-04-01 22:34 UTC
Labels: bug, error-from-open, needs-reproduction
