### ISSUE TITLE
Atom crashes when trying to load a file

### ISSUE THREAD

**Issue by larfoley** [atom/atom#12040] opened 2016-06-24 13:18 UTC
When I try open my webpack generated bundle.js file using Atom, it crashes every time.

I'm using the latest version of Atom with Ubuntu 16.04 and have tried running in safe mode, re-installing atom and tried opening the file with using another PC and it still crashed. The only time it doesn't crash is when I minify the file which is only 411.7 kB when un-minified.

#### Output from the terminal when the crash happens
/usr/bin/atom: line 98: 10962 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 580ms
Failed to get crash dump id.
Report Id:

#### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
Operating System: Ubuntu 16.04

**Comment by Zireael07** [comment] 2016-06-24 16:40
How many lines does it have? Have you tried changing the extension to .txt (plain text) to see if it's the java grammar highlight at fault? Does it have any long lines?

**Comment by larfoley** [comment] 2016-06-24 17:40
There was just over 1500 lines in the file. I just tried changing the file extension from .js to .txt and that allowed the file to load. There was also some long lines in the file which when stopped atom from crashing. So when its trying to load a javaScript file with a long line, it will crash. But when I minify the entire .js file it will not crash.

**Comment by Zireael07** [comment] 2016-06-24 17:47
Duplicate of #979, then. Long lines crashing Atom.

**Closed** 2016-06-24 17:53 UTC
