### ISSUE TITLE
Atom 1.0.5 craches on startup (only console and devtools visible) OS X

### ISSUE THREAD

**Issue by Nosenation** [atom/atom#8277] opened 2015-08-07 20:10 UTC
I have problem on OS X with starting an Atom. Just upgraded to 1.0.5 and I see this error (no other pane is visible except devtools and console, so can't work with it).

```
Error
    at new Parser (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:275:20)
    at LessCache.module.exports.LessCache.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:263:19)
    at LessCompileCache.module.exports.LessCompileCache.read (/Applications/Atom.app/Contents/Resources/app.asar/src/less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:310:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:286:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:203:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:266:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:261:19)
```
at:
```
file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js line: 66
```

**Comment by 50Wliu** [comment] 2015-08-07 20:26
Duplicate of #7282, please subscribe there for updates.
This error usually comes up when you have a syntax error in your `styles.less` file, so try opening it in another editor and seeing if you can identify the mistake.  If you can't, or suspect one of your installed packages is causing the problem, deleting `~/.atom/packages/` and `~/.atom/styles.less` should do the trick.

**Closed by 50Wliu** 2015-08-07 20:26 UTC

**Comment by Nosenation** [comment] 2015-08-07 20:34
Deleted https://atom.io/themes/nucleus-dark-ui and it works right now.
