### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/akihiroyajima/Dropbox/Settings/.atom/packages/save-session/projects//Users/ietty/Works/totalsupport/project.json'

### ISSUE THREAD

**Issue by yaji-ietty** [atom/atom#6215] opened 2015-04-02 07:20 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/akihiroyajima/Dropbox/Settings/.atom/packages/save-session/projects//Users/ietty/Works/totalsupport/project.json'

```
At fs.js:55

Error: ENOENT: no such file or directory, open '/Users/akihiroyajima/Dropbox/Settings/.atom/packages/save-session/projects//Users/ietty/Works/totalsupport/project.json'
  at Error (native)

```

### Commands

```
     -2:07.2 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -1:43.9 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -1:25.2 core:copy (atom-text-editor.editor.vim-mode.visual-mode)
     -1:17.7 pane:show-previous-item (atom-text-editor.editor.vim-mode.visual-mode)
     -1:16.9 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -1:03.5 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:45.6 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:39.7 pane:show-previous-item (div.deprecation-cop.pane-item.native-key-bindings)
     -0:36.6 vim-mode:insert-after (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:35.9 emmet:insert-formatted-line-break-only (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:35.9 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:32.7 emmet:insert-formatted-line-break-only (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:32.7 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:22.8 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:18.6 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:06.7 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "sublime-tabs",
      "atom-lint",
      "web-view",
      "npm-install",
      "term2",
      "jquery-snippets",
      "script",
      "atom-html-preview",
      "linter-htmlhint",
      "jsformat",
      "auto-indent",
      "save-session"
    ],
    "followSymlinks": true,
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Source Code Pro",
    "tabLength": 4,
    "lineHeight": 1.5,
    "scrollPastEnd": true,
    "softWrap": true,
    "preferredLineLength": 500,
    "fontSize": 12,
    "showIndentGuide": true,
    "zoomFontWhenCtrlScrolling": true,
    "autoIndentOnPaste": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.23.1
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.2.0
color-picker, v1.5.0
css-snippets, v0.5.0
emmet, v2.3.6
file-icons, v1.5.2
git-log, v0.3.0
highlight-line, v0.10.1
japanese-wrap, v0.2.4
javascript-snippets, v1.0.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-scss-lint, v0.0.14
minimap, v4.7.2
project-manager, v1.15.5
tabs-to-spaces, v0.9.2
travis-ci-status, v0.13.0
vim-mode, v0.42.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-04-02 11:48
Duplicate of your other issue.

**Closed by 50Wliu** 2015-04-02 11:48 UTC
