### ISSUE TITLE
Bracket matching bugs??

### ISSUE THREAD

**Issue by touiminao** [atom/atom#17252] opened 2018-05-01 03:57 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Versions
1.26.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

below is the bug i'm dealing with

![image](https://user-images.githubusercontent.com/24784216/39460507-f3add5d6-4d3e-11e8-90cb-c6bfac094860.png)

and this is the same codes opened in sublime

![image](https://user-images.githubusercontent.com/24784216/39460528-1d130022-4d3f-11e8-8adf-f8f62c817d6a.png)

how can i fix this?

**Comment by rsese** [comment] 2018-05-01 19:33
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/language-php/issues/321 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-01 19:33 UTC
