### ISSUE TITLE
Uncaught Error: Cannot find module '../node_modules/keyboard-layout/build/Release/keyboard-layout...

### ISSUE THREAD

**Issue by Xsinh** [atom/atom#14583] opened 2017-05-23 08:43 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module '../node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'

```
At module.js:457

Error: Cannot find module '../node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.0/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.17.0/resources/app/static/<embedded>:73:1)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:1)
    at get_manager (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:1)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:1)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:1)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/helpers.js:244:1)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:456:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:336:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:52.2.0 application:open-folder (input.hidden-input)
  2x -0:24.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
minimap 4.27.1 
seti-syntax 1.1.3 
seti-ui 1.7.0 
```

**Comment by rsese** [comment] 2017-05-23 17:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14461. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-23 17:28 UTC
