### ISSUE TITLE
Git Tab stops working in Atom

### ISSUE THREAD

**Issue by dmitriivikorchuk** [atom/atom#16157] opened 2017-11-11 10:00 UTC
### Description

Unable to use Git Tab or Github Tab in Atom 1.21-1.22 (maybe issue happens in early versions, but I didnot check this) - branch and number of changes not clickable in status bar.
![image](https://user-images.githubusercontent.com/31388230/32688232-cf907892-c6d5-11e7-8584-38b27e529c8e.png)

Git tab did not showing in any way (with Atom menu, or with hotkeys).
At the same time I can see branch and number of changes, but its not clickable. And of course a have git in folder, where I try to use Git Tab.

Visual Studio at the same time see and operate with same git correctly.

### Steps to Reproduce

1. Run Atom (latest version).
2. Open *.ts file, see branch and difference.
3. Can't click on branch or numbers or toggle Git/Github Tabs.

**Expected behavior:** Show Git Tab and Github Tab (CTRL-SHIFT-9, 8)

**Actual behavior:** Unable to show Git Tab and Github Tab.

**Reproduces how often:** Always

### Versions
atom --version
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
Windows 10

### Additional Information

This morning I try to use atom --clear-window-state. This helps only for one time. After restart Atom issue is return again. Further use of this command dont works any more.

**Comment by dmitriivikorchuk** [comment] 2017-11-11 11:37
Issue only fixed after removing NODE_ENV from System Environment Variables (https://github.com/atom/github/issues/833).
![image](https://user-images.githubusercontent.com/31388230/32689048-1072b79e-c6e5-11e7-8c97-44fb6b62f217.png).
So why this setting affect Atom Git Tab?

**Comment by rsese** [comment] 2017-11-13 17:59
Thanks for the report, glad you found https://github.com/atom/github/issues/833 - we'll go ahead and close as a duplicate of that issue.

> So why this setting affect Atom Git Tab?

Since https://github.com/atom/github/issues/833 is still open, this is part of what the team is trying to figure out - you can subscribe to that issue for updates if you'd like.

**Closed by rsese** 2017-11-13 17:59 UTC
