### ISSUE TITLE
[OSX] Unexpected behavior hitting spacebar in Settings pane 

### ISSUE THREAD

**Issue by claudiofantacci** [atom/atom#11957] opened 2016-06-10 12:45 UTC
### Description

In Atom Settings pane, whenever you press the spacebar (space action) in a textbox the UI scrolls down of one page (approx). The problem is also experienced in safe mode. 

### Steps to Reproduce

1. Open Settings (cmd+,)
2. Select one of the sub-panes (e.g. Keybindings, Packages, etc.)
3. Have the text cursor in one textbox
4. Hit the spacebar

**Expected behavior:** I expect to just have a space in the textbox.

**Actual behavior:** You get a space in the textbox while the UI, if possible, scrolls down of one page (approx).

### Versions

Atom: 1.8.0
Electron: 0.36.8
Chrome: 47.0.2526.110
Node: 5.1.1

System version: OS X 10.11.5 (15F34) - OSX El Capitan
Kernel version: Darwin 15.5.0

**Comment by 50Wliu** [comment] 2016-06-10 12:49
This is a duplicate of atom/settings-view#767 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-10 12:49 UTC
