### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 311

### ISSUE THREAD

**Issue by Hypercube80** [atom/atom#20159] opened 2019-11-19 08:38 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 311

```
At C:\Users\Daniel\AppData\Local\atom\app-1.41.0\resources\electron.asar\renderer\api\remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 311
    at throwRPCError (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:148:17)
    at ~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -3:53.8.0 editor:newline (input.hidden-input)
     -3:52.7.0 core:paste (input.hidden-input)
     -3:48.5.0 editor:newline (input.hidden-input)
     -3:45.7.0 core:backspace (input.hidden-input)
     -2:06.9.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -2:04.0 core:backspace (input.hidden-input)
     -2:00.0 core:paste (input.hidden-input)
     -1:57.4.0 snippets:next-tab-stop (input.hidden-input)
     -1:57.4.0 snippets:expand (input.hidden-input)
     -1:57.4.0 editor:indent (input.hidden-input)
  7x -1:30.4.0 core:backspace (input.hidden-input)
     -1:00.4.0 core:copy (input.hidden-input)
     -0:59 core:cut (input.hidden-input)
     -0:55.1.0 editor:newline (input.hidden-input)
     -0:53.9.0 core:paste (input.hidden-input)
     -0:47.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by darangi** [comment] 2019-11-19 16:55
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

It sounds like the error isn't reproducible for you, but if it is, please let us know the steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2019-11-19 16:55 UTC
