### ISSUE TITLE
Filter themes by name doesn't work

### ISSUE THREAD

**Issue by cperryk** [atom/atom#7325] opened 2015-06-17 19:17 UTC
In settings, on the "Themes" tab, when I type anything into the box labelled "Filter themes by name," all themes are filtered _out_, even if I type in strings that appear within the names of themes I've installed, and even if I type in the exact name of the theme.

For example, suppose I was trying to quickly get to "seti-ui." If I type in `seti`, nothing appears. If I type in `seti-ui`, nothing appears. As far as I can tell, the filter box filters out every theme, no matter what you type into it.

 Running at Atom 0.209.0 on OS X 10.10.4.

**Comment by mnquintana** [comment] 2015-06-17 19:26
Thanks for the report! This looks like a duplicate of https://github.com/atom/settings-view/issues/530 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-17 19:26 UTC
