### ISSUE TITLE
Blurry Text when scrolling

### ISSUE THREAD

**Issue by GabrSaac** [atom/atom#15257] opened 2017-08-11 10:41 UTC
Since yesterday (automatic updates) the text gets blurry when I scroll in certain positions.

Example:
![blurry text atom](https://user-images.githubusercontent.com/14870322/29210219-5dc24c7e-7e8a-11e7-9e93-f268517ab049.png)

Adding a few new lines at the bottom of the page (temporarily and partially) solves the issue.

**Comment by rsese** [comment] 2017-08-11 17:57
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14824. You may want to subscribe there for updates.  As a side note, for future issues it would be super helpful if you can fill out the issue template.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-11 17:57 UTC
