### ISSUE TITLE
Setting Default Syntax for New Documents 

### ISSUE THREAD

**Issue by ChrisChiera** [atom/atom#12732] opened 2016-09-20 16:02 UTC
### Prerequisites
- [Y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [Y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [Y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [Y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Opening a new document defaults to "Plain Text" syntax. You can save the file with a select file extension or manually select a syntax but cannot set the default syntax for new documents. An official init.coffee solution exists on the [Atom FAQ](https://discuss.atom.io/t/how-can-i-make-all-new-files-open-with-a-specific-grammar-or-syntax/20754) however new documents still default to "Plain Text" and rather only opening a new tab defaults to the desired syntax:

```
atom.workspace.observeTextEditors (editor) ->
  if editor.getTitle() is "untitled"
    editor.setGrammar(atom.grammars.grammarForScopeName('text.html.php'))
```

Other developers have noted the bug appears to be, "Open Empty Editor On Start option enabled is required as this issue only occurs on the first editor created by that option."
### Steps to Reproduce
1. Edit init.coffee with above code
2. Restart Atom
3. Open Atom and notice default syntax is still Plain Text

**Expected behavior:** [What you expected to happen]
Default syntax (based on above code) should be PHP
**Actual behavior:** [What actually happened]
It is still Plain Text (unless you open another tab via shortcut or Menu). Opening New Window view menu or shortcut also results in same issue.
### Versions

1.10.2, Mac 10.12 (16A313a)

**Comment by lee-dohm** [comment] 2016-09-28 16:35
My hypothesis is that the `init.coffee` is getting run *after* the `untitled` document is created when a new window is opened.

**Comment by thomasjo** [comment] 2018-10-26 08:17
@rsese That only happens if you have an "untitled" editor open when closing and re-launching Atom. The problem occurs because the init script is invoked before all grammars/packages have finished loading.

Resolving the problem in @ChrisChiera's example above can be achieved by altering the init script to
``` coffee
atom.grammars.onDidAddGrammar (grammar) ->
  if grammar.scopeName is 'text.html.php'
    atom.workspace.observeTextEditors (editor) ->
      if editor.getTitle() is "untitled"
        editor.setGrammar(grammar)
```
The fix works by only wiring up the event handler _after_ the desired grammar has been added.

Since this is not a bug in Atom, I'm going to close this issue.

**Closed by thomasjo** 2018-10-26 08:17 UTC
Labels: api, bug, triaged

**Comment by rsese** [comment] 2018-10-26 15:48
Great, thanks for the explanation @thomasjo :bow:
