### ISSUE TITLE
nodegit error when adding git repo with submodules as project.

### ISSUE THREAD

**Issue by LogoiLab** [atom/atom#11675] opened 2016-05-03 02:08 UTC
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)? **YES**
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? **YES**
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? **YES**
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? **YES**
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?  **YES**
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? **YES**

### Description

**EDIT:** THIS IS A REPO BASED ERROR
The `Microsoft Visual C++ Runtime Library` kicks out an error upon adding a git repository with submodules as a project folder.
<pre><code>Assertion failed!

Program: ...ed\node_modules\nodegit\build\Release\nodegit.node
File: ..\..\vendor\libgit2\src\submodule.c
Line: 1673

Expression: error != 0</code></pre>
![2016-05-02](https://cloud.githubusercontent.com/assets/5545218/14972969/5a90ee28-10b0-11e6-9389-1707d36ea175.png)

This looks like [nodegit](https://github.com/nodegit/nodegit) is trying to process the submodules in some way but then fails.

### Steps to Reproduce

1. Install Atom using the windows installer from <a href="atom.io">atom.io</a>
2. Try to add a local git repo with submodules as a project folder.
3. Read `Microsoft Visual C++ Runtime Library` errors.

**Expected behavior:** Just add the repo and get on with it like it does with a normal repos.
**Actual behavior:** nodegit errors out and causes atom to crash.
### Versions
Atom 1.7.3
Microsoft Windows 10 x86_64 (Upgraded from preinstalled Windows 7)
Acer Aspire 5334 Laptop [*hardware list here*](http://www.lapspecs.com/detail/acer+aspire+5334)

**Comment by lee-dohm** [comment] 2016-05-03 03:30
Is there anything else you can tell us? Where on your hard drive is the repository? Do you have more than one and all of them reproduce this error? Is this a public repository that we can try to reproduce the error with?

**Comment by LogoiLab** [comment] 2016-05-03 11:42
It is on the local hard drive in the documents folder of a standard user account. The repository I am using is:
 
GitHub.com/LogoiLab/Zika

I have the latest version of git installed via chocolatey.

The issue seems to be at least a little bit similar to issue [10490](https://github.com/atom/atom/issues/10490)

**Comment by LogoiLab** [comment] 2016-05-03 11:45
The only thing I can think that is different about the repository that would cause the error is that it has submodules added in a custom subdirectory.

**Comment by LogoiLab** [comment] 2016-05-03 16:39
as I added, this is in no way a hardware error. It is strictly an error based on submodules within a git repository.

**Comment by lee-dohm** [comment] 2016-05-03 21:37
So you don't get this behavior with any other Git repository?

**Comment by LogoiLab** [comment] 2016-05-03 21:48
That is true

**Comment by joshaber** [comment] 2016-05-04 14:09
This looks like a duplicate of #11196, so I'm gonna close it. @LogoiLab feel free to subscribe to that issue for updates!

**Closed by joshaber** 2016-05-04 14:09 UTC
Labels: more-information-needed, needs-reproduction, windows
