### ISSUE TITLE
Files keeps marked as modified

### ISSUE THREAD

**Issue by n9iels** [atom/atom#9134] opened 2015-10-13 21:07 UTC
I have the following problem wit the Git integration:
1) I open a folder with a .git folder in it, right click->open with atom
2) I modified just one line
3) Atom thinks the whole file is modified. So the file is orange, and the status bar says for example:
![knipsel](https://cloud.githubusercontent.com/assets/2659866/10468247/4fa6286c-71fe-11e5-8d00-6e2feb626398.PNG)
But at the begin of the lines, just after the line numbers, there is no sign of any modified lines.

I also happens sometimes that the whole file list is marked as modified (al files are orange).
When I run `git status` it says the repository is clean, and there are no new commits, new files of modified files.

### System information
OS: Windows 7
Atom version: 1.0.19

**Comment by 50Wliu** [comment] 2015-10-13 23:54
This is probably a duplicate of #3768 - make sure your `core.autocrlf` option is set correctly.

**Closed by 50Wliu** 2015-10-13 23:54 UTC
