### ISSUE TITLE
Text at start of line breaks code folding

### ISSUE THREAD

**Issue by postcasio** [atom/atom#3442] opened 2014-09-03 14:37 UTC
Using the following PHP file:

``` php
<?php

class Test {
    public function test() {
//      breaks folding
    }
}
```

Attempting to fold the class results in a fold up to the comment.
![screen shot 2014-09-03 at 15 34 54](https://cloud.githubusercontent.com/assets/1759837/4135590/8018824a-3377-11e4-85a9-59d2a9b5e22d.png)

![screen shot 2014-09-03 at 15 37 58](https://cloud.githubusercontent.com/assets/1759837/4135634/f2612a96-3377-11e4-935e-6ee3f8b486c5.png)

It seems like using any character other than whitespace at the start of the line will cause the fold to break.

Atom 0.124.0 in safe mode, btw.

**Comment by nathansizemore** [comment] 2015-09-29 12:54
Would be nice if folding was not based of indentation, but key items based on current language spec of the file. The folding is really a pain when working with C/C++ and there are a ton of macro based conditionals. Basically makes it impossible to fold a function that has a `#ifdef` in it. 
For better or worse, these are most often at the beginning of the line.

**Comment by Rimhollow** [comment] 2016-05-04 02:54
Still happening in 1.7.3. Has anyone found a workaround? It's causing me a lot of headaches.

**Comment by networkinterfacecontroller** [comment] 2016-11-07 19:23
Has there been any progress on resolving this issue?

**Comment by brigand** [comment] 2017-03-12 09:50
This also comes up with ES6 template literals, and the [language-babel author](https://github.com/gandm/language-babel/issues/156) says it's out of his hands.

**Comment by a7madgamal** [comment] 2017-03-23 12:40
:shipit: :D

**Comment by alexchandel** [comment] 2017-05-19 21:25
Note that this doesn't just occur when there's whitespace, but whenever the indentation of some inner block isn't hierarchical. For example, this folds wrong:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Outer>
    <Inner>
        <![CDATA[LINE 1
    LINE 2]]>
    </Inner>
</Outer>
```

But this folds right:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Outer>
    <Inner>
        <![CDATA[LINE 1
        LINE 2]]>
    </Inner>
</Outer>
```

The former case also leaves lines 5&6 dangling, even though they match the indentation of line 3, while the latter case successfully folds line 6 into line 3.

**Comment by LastBrat** [comment] 2017-12-04 12:08
I'm a total newbie, but the replies suggest this issue has been solved, right? 
However, I still have this issue in my xml file, in Atom version 1.22.1 (x64, windows). Anything that does not follow correct indentation, is not folded, just like the comments above illustrate.

Any help with this is greatly appreciated!

**Comment by 50Wliu** [comment] 2017-12-04 19:20
@LastBrat we're working on improved folding support, starting with #16299.

**Comment by Ben3eeE** [comment] 2018-11-16 21:47
The root cause of the problem has been fixed by the integration of the [tree-sitter grammar system as the default in Atom](http://blog.atom.io/2018/10/23/atom-1-32.html). While it is true that not every bundled language has a tree-sitter grammar, that will be achieved over time. We're in the process of marking all of our bundled grammar repos with the [`tree-sitter` topic](https://github.com/search?q=org%3Aatom+topic%3Atree-sitter&unscoped_q=topic%3Atree-sitter) and [atom.io keyword](https://atom.io/packages/search?utf8=%E2%9C%93&q=tree-sitter+language&commit=Search) so that people can easily see which languages have been updated.

I hope that helps!

**Closed by Ben3eeE** 2018-11-16 21:47 UTC
Labels: bug
