### ISSUE TITLE
Typing a space into a text field is interpreted as PgDn

### ISSUE THREAD

**Issue by DamnedScholar** [atom/atom#11943] opened 2016-06-09 01:56 UTC
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Whenever I type a space into a text field in the Settings pane, regardless of which tab I'm on, it does add a space to the field, but it also gets caught by the editor as a PgDn instruction.

### Steps to Reproduce

1. Open the settings pane.
2. Click on a text field.
3. Hit the spacebar.

**Expected behavior:** A space is inserted into the text field.

**Actual behavior:** A space is inserted, and the pane scrolls down as if the PgDn button had been pressed.

### Versions

This happens across both of my personal machines. My Windows 10 computer is running 1.8.0. My Manjaro (Arch fork) machine is running 1.9.0-dev-b9dbb81.

**Comment by 50Wliu** [comment] 2016-06-09 02:01
This is a duplicate of atom/settings-view#767 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-09 02:01 UTC
