### ISSUE TITLE
Atom fails to build on Arch Linux when not using official npm & nodejs packages

### ISSUE THREAD

**Issue by maxcr** [atom/atom#13960] opened 2017-03-08 16:16 UTC
When using nodejs, and npm installed from source the neither the official Atom, nor the aur Atom packages work. Solution, install from source.

Second, when building from source the error
```
You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```
When building APM persists even after adding the `export PYTHON` switch. Appending the ` --python switch ` to the `./script/build` does not work either.

The only solution I have found to work is to modify the system symlink of /sbin/python3.6 -> /sbin/python to /usr/sbin/python2.7 -> /usr/sbin/python

Surely there is a cleaner solution. I'm trying to find one atm.

**Comment by MoritzKn** [comment] 2017-04-01 14:36
I think your second problem is a duplicate of atom/apm/#698.

**Comment by 50Wliu** [comment] 2017-04-02 15:32
Thanks @MoritzKn.

**Closed by 50Wliu** 2017-04-02 15:32 UTC
Labels: build-error, linux
