### ISSUE TITLE
Support OS X’s Create Window/Document from the Dock

### ISSUE THREAD

**Issue by davidbarsky** [atom/atom#6498] opened 2015-04-23 19:43 UTC
Small, nickpicky-issue: a lot of applications, especially document-based apps offer a quick way to create a new document/window directly from the dock. Terminal.app is a great example of this:
![](https://cloud.githubusercontent.com/assets/2067774/7305813/cf4c82cc-e9ce-11e4-9499-2c8825376f73.png)

It’d be useful if Atom could do the same thing, but the current options are:
![screen shot 2015-04-23 at 3 41 19 pm](https://cloud.githubusercontent.com/assets/2067774/7305861/31aef76a-e9cf-11e4-9839-4557ae3f00b8.png)

**Comment by mnquintana** [comment] 2015-04-23 20:22
Duplicate of #5921 - please subscribe there for updates.

**Closed by mnquintana** 2015-04-23 20:22 UTC
