### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by igorgottschalg** [atom/atom#6703] opened 2015-05-08 14:22 UTC
[Enter steps to reproduce below:]

1. Right click in folder project or file

**Atom Version**: 0.198.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Igor\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  6x -5:47.6.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -5:46.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:45.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:45.1.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -5:44.9.0 core:cut (atom-text-editor.editor.is-focused)
     -5:44.7.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -5:44.2.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -5:44 core:move-up (atom-text-editor.editor.is-focused)
     -5:43.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:43.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -5:43.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:43 core:move-down (atom-text-editor.editor.is-focused)
     -5:42.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:42.2.0 core:paste (atom-text-editor.editor.is-focused)
     -5:42.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.3.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 11
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-05-08 15:14
This is a duplicate of #6548, I believe.

**Closed by izuzak** 2015-05-08 15:14 UTC
