### ISSUE TITLE
macOS Sierra Fullscreen menubar not pushing tabs down

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [atom/atom#13981] opened 2017-03-11 05:03 UTC
Currently when I have atom in fullscreen mode and I move the mouse to the top of the screen to show the menu bar, when the menu bar appears, it slides down _over the top_ of atoms tab bar. This is really annoying if I _accidentally_ move the mouse to far to the top of the screen when Im trying to change tabs within atom, then the menu bar appears and obscures the tab bar, then I have to move the mouse back down to the middle of the screen, wait for the menu bar to go away, then try again.

Correct behaviour should be like Chrome on Sierra - when you go fullscreen then move the mouse up to show menu bar, it pushes the top of the Chrome window down when it appears, allowing me to still access my tabs.

**Comment by rsese** [comment] 2017-03-13 18:28
Just noting that I can reproduce this behavior - going to label it as a bug as a first pass, though I'm not sure if this is more of an Electron issue?

**Comment by matthewjumpsoffbuildings** [comment] 2017-03-13 18:33
Ah it might be electron, it happens in Slack too now that you mention it

**Comment by rsese** [comment] 2017-03-13 19:01
Oh yep you're right, I see it with Slack too and another Electron app I have - I'll go ahead and close this out.  If you don't mind, could you re-open in the Electron repository if there isn't already an existing issue for this?

**Closed by rsese** 2017-03-13 19:01 UTC
Labels: bug, mac, triaged

**Comment by lee-dohm** [comment] 2017-03-13 19:07
The behavior described here is a standard behavior. If you use iTunes in Full Screen mode, the top of the window is obscured while the menu bar is available and the window never resizes. While I agree that the Chrome behavior is perhaps more desirable, since the menu bar goes away when you move the pointer off of the menu bar, I don't think this is a requirement.
