### ISSUE TITLE
horrendous json syntax highlighting after update to 1.38

### ISSUE THREAD

**Issue by mbotmcc** [atom/atom#19501] opened 2019-06-12 08:37 UTC
Updated atom to v 1.38 and the json syntax highlighting is fugly.

now:
![image](https://user-images.githubusercontent.com/35934878/59336000-41c3ce80-8ced-11e9-9205-45ec4ff9b50b.png)

before (randon example from google)
![image](https://user-images.githubusercontent.com/35934878/59336018-4a1c0980-8ced-11e9-92ce-6159464882e2.png)

**Comment by gbvanrenswoude** [comment] 2019-06-12 08:42
Have the same issue, upvoted. Terrible json syntax highlighting

**Comment by kevteljeur** [comment] 2019-06-12 09:58
I came here Google the same thing. First thing I noticed. It doesn't seem consistent, either. It's all over the place. Some keys and values are underlined or highlighted, others not, and there's no consistency there. Horrendous to look at. Somebody on the team a YAML fan perhaps?

**Comment by Aerijo** [comment] 2019-06-12 10:04
This is tracked at https://github.com/atom/language-json/issues/75

**Comment by Arcanemagus** [comment] 2019-06-12 16:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-json/issues/75. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-06-12 16:29 UTC
