### ISSUE TITLE
Settings -> packages only shows a subset of installed packages

### ISSUE THREAD

**Issue by halhenke** [atom/atom#9221] opened 2015-10-20 05:10 UTC
e.g. If I do `apm list` in the console I can see that the `atom-ctags` package is installed. 

However, inside Atom - in the Settings view, it isnt shown in any of the various Package sections nor on the Update page. 

Interestingly the Settings page says I have 138 packages installed (60 Community Packages & 78 Core Packages) while apm reports 153 packages (63 Community Packages & 90 Built-In Packages).

**Comment by thomasjo** [comment] 2015-10-20 05:26
Very odd. Any chance you can share the output of `apm list` with us? In addition, assuming you're on a *NIX box, what does `apm list --no-dev --bare | sed "/^$/d" | wc -l` produce?

**Comment by 50Wliu** [comment] 2015-10-20 13:00
This sounds like a duplicate of atom/settings-view#591.

**Comment by halhenke** [comment] 2015-10-20 13:56
`apm list --no-dev --bare | sed "/^$/d" | wc -l` gives me 153

here the full output of `apm list`

```shell
Built-in Atom packages (90)
├── about@1.1.0
├── archive-view@0.60.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.19.1
├── autocomplete-snippets@1.7.1
├── autoflow@0.25.0
├── autosave@0.22.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@0.27.0
├── base16-tomorrow-light-theme@0.9.0
├── bookmarks@0.37.0
├── bracket-matcher@0.76.0
├── command-palette@0.36.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.181.0
├── fuzzy-finder@0.88.0
├── git-diff@0.56.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.54.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.48.0
├── language-clojure@0.16.0
├── language-coffee-script@0.41.0
├── language-csharp@0.10.0
├── language-css@0.34.0
├── language-gfm@0.81.0
├── language-git@0.10.0
├── language-go@0.37.0
├── language-html@0.41.2
├── language-hyperlink@0.14.0
├── language-java@0.16.0
├── language-javascript@0.94.0
├── language-json@0.16.0
├── language-less@0.28.2
├── language-make@0.17.0
├── language-mustache@0.12.0
├── language-objective-c@0.15.0
├── language-perl@0.29.0
├── language-php@0.30.0
├── language-property-list@0.8.0
├── language-python@0.40.0
├── language-ruby@0.58.0
├── language-ruby-on-rails@0.22.0
├── language-sass@0.41.0
├── language-shellscript@0.17.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.16.0
├── language-xml@0.32.0
├── language-yaml@0.24.0
├── line-ending-selector@0.0.5
├── link@0.30.0
├── markdown-preview@0.150.0
├── metrics@0.51.0
├── notifications@0.59.0
├── one-dark-syntax@1.1.0
├── one-dark-ui@1.0.4
├── one-light-syntax@1.1.0
├── one-light-ui@1.0.4
├── open-on-github@0.38.0
├── package-generator@0.40.0
├── release-notes@0.53.0
├── settings-view@0.216.0
├── snippets@0.99.0
├── solarized-dark-syntax@0.38.1
├── solarized-light-syntax@0.22.1
├── spell-check@0.59.0
├── status-bar@0.79.0
├── styleguide@0.44.0
├── symbols-view@0.104.0
├── tabs@0.84.0
├── timecop@0.31.0
├── tree-view@0.187.0
├── update-package-dependencies@0.10.0
├── welcome@0.30.0
├── whitespace@0.31.0
└── wrap-guide@0.36.0

/Users/hal/.atom/packages (63)
├── .bin
├── angularjs@0.3.3
├── atom-beautify@0.28.14
├── atom-bootstrap3@1.2.12
├── atom-ctags@4.3.0
├── atom-speech-to-code@0.4.3
├── atom-typescript@7.4.2
├── atom-yeoman@0.3.15
├── atomatigit@1.5.4
├── bower-install@0.2.4
├── coffee-compile@0.19.2
├── color-picker@2.0.13
├── command-logger@0.23.0
├── dash@1.3.2
├── ember-cli-helper@0.9.0
├── ember-snippets@1.4.0
├── expand-selection-to-quotes@0.7.0
├── file-types@0.5.1
├── git-blame@0.4.5
├── git-plus@5.4.7
├── gulp-snippets@0.6.2
├── isotope-ui@2.6.0
├── javascript-snippets@1.0.0
├── jslint@1.4.0
├── jumpy@2.0.10
├── language-ansible@0.1.3
├── language-applescript@0.2.0
├── language-babel@0.15.7
├── language-diff@0.3.1
├── language-docker@1.1.3
├── language-fish-shell@1.0.2
├── language-haml@0.23.1
├── language-haskell@1.4.11
├── language-jade@0.6.2
├── language-nginx@0.6.1
├── language-yaml@0.24.0
├── line-jumper@0.14.1
├── linter@1.8.1
├── linter-eslint@3.1.1
├── linter-jshint@1.2.1
├── linter-rubocop@0.4.4
├── monokai@0.18.0
├── move-panes@0.2.0
├── npm-docs@0.2.0
├── npm-install@4.0.3
├── pain-split@1.4.0
├── preview@0.16.5
├── project-manager@2.6.4
├── quippet@2.0.0
├── react@0.12.10
├── regex-railroad-diagram@0.10.4
├── release-notes@0.53.0
├── ruby-block@0.3.5
├── ruby-block-converter@3.5.0
├── script@3.0.1
├── set-syntax@0.3.0
├── spacegray-dark-ui@0.12.0
├── starred-package-installer@0.1.0
├── tabs-to-spaces@0.11.1
├── term2@0.9.21
├── url-encode@0.5.0
├── word-jumper@0.3.0
└── zentabs@0.8.6
```

Heres something else - `Deprecated Packages` section always says "Loading Packages"


....and heres what looks like a very relevant error message from the Dev Tools Console:

```
Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/hal/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:1:1)
  at /Users/hal/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:6:3
  at Object.<anonymous> (/Users/hal/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:84:5)
  at Object.<anonymous> (/Users/hal/.atom/packages/starred-package-installer/lib/starred-package-installer-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/hal/.atom/packages/starred-package-installer/lib/starred-package-installer.coffee:1:31)
  at Object.<anonymous> (/Users/hal/.atom/packages/starred-package-installer/lib/starred-package-installer.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:263:14)
  at PackageManager.module.exports.PackageManager.packageHasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:42:14)
  at PackageCard.module.exports.PackageCard.hasSettings (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:611:34)
  at PackageCard.module.exports.PackageCard.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:205:17)
  at PackageCard.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageCard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:22:48)
  at InstalledPackagesPanel.module.exports.InstalledPackagesPanel.createPackageCard (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:327:18)
  at ListView.createView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:3:61)
  at ListView.module.exports.ListView.addView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list-view.js:50:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list-view.js:13:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at List.module.exports.List.setItems (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/list.js:42:22)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:275:28
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)
(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/installed-packages-panel.js:288
```

**Comment by halhenke** [comment] 2015-10-20 13:59
So yeah, looks like a duplicate of atom/settings-view#591

**Closed** 2015-10-20 14:24 UTC
Labels: more-information-needed, needs-reproduction
