### ISSUE TITLE
Installation splash screen extremely small and unreadable

### ISSUE THREAD

**Issue by mattb5906** [atom/atom#16568] opened 2018-01-15 21:29 UTC
### Prerequisites

* [N/A / X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The installation splash screen is extremely small (200 x 200 px) at 100% scaling

### Steps to Reproduce
1. Launch AtomSetup-x64.exe
2. Wait for the installation splash screen.

**Expected behaviour:** [What you expect to happen]
A readable splash screen.

**Actual behaviour:** [What actually happens]
Extremely small unreadable splash screen. 200 x 200 px
https://i.imgur.com/Sef43M3.png
See screen capture at 100% scaling:
https://i.imgur.com/RCu5ujB.gifv

Reproduces 100% of the time on multiple Windows 10 devices.

### Versions
Atom    : 1.24.0-beta3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information
Windows 10 Insider Preview 1709 build 17063.1000

**Comment by rsese** [comment] 2018-01-15 23:49
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15873, you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-01-15 23:49 UTC
