### ISSUE TITLE
Tree View makes an unchanged file green as a new file

### ISSUE THREAD

**Issue by sh01ch1** [atom/atom#11430] opened 2016-04-12 06:28 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Tree View makes a file green, but the file is committed and unchanged. The filename includes some non-ascii (Japanese) characters.

### Steps to Reproduce

1. In terminal, execute the following commands:

    ```bash
    $ mkdir ~/atomtest
    $ cd ~/atomtest
    $ git init
    Initialized empty Git repository in /Users/xxx/atomtest/.git/
    $ touch Webデザイン.md
    $ git add .
    $ git commit -m "test"
    [master (root-commit) 66a26c0] test
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 Webデザイン.md
    $ git status
    On branch master
    nothing to commit, working directory clean
    $ atom --safe .
    ```

**Expected behavior:**

The committed file is shown as an unchanged file in Tree View.

**Actual behavior:**

The committed file is shown as a new file in Tree View:

<img width="165" alt="2016-04-12 15 06 57" src="https://cloud.githubusercontent.com/assets/9210715/14451225/4375d2da-00c0-11e6-98cc-63efba79e9c0.png">

### Versions

* ATOM: 1.6.2
* apm: 1.6.0
* npm  2.13.3
* node 0.10.40
* python 2.7.10
* git 2.6.0
* OS: Mac OS X 10.10.5

**Comment by 50Wliu** [comment] 2016-04-12 16:19
This is a duplicate of #1890 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-12 16:19 UTC

**Comment by sh01ch1** [comment] 2016-04-13 00:58
thank you
