### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 414

### ISSUE THREAD

**Issue by dievasetyatama** [atom/atom#20130] opened 2019-11-08 08:26 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 414

```
At C:\Users\Dieva\AppData\Local\atom\app-1.41.0\resources\electron.asar\renderer\api\remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 414
    at throwRPCError (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:148:17)
    at ~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
     -1:21.9.0 intentions:highlight (input.hidden-input)
  3x -1:21.4.0 core:copy (input.hidden-input)
     -1:20.5.0 intentions:highlight (input.hidden-input)
     -1:20.4.0 core:paste (input.hidden-input)
     -1:19.1.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:18.8.0 intentions:highlight (input.hidden-input)
     -1:18.7.0 core:paste (input.hidden-input)
     -1:18.3.0 intentions:highlight (input.hidden-input)
  4x -1:18.2.0 core:save (input.hidden-input)
     -0:25.1.0 core:move-right (input.hidden-input)
 11x -0:24.8.0 core:select-down (input.hidden-input)
     -0:21.9.0 intentions:highlight (input.hidden-input)
  2x -0:21.5.0 core:select-down (input.hidden-input)
     -0:21 intentions:highlight (input.hidden-input)
  2x -0:20.7.0 core:copy (input.hidden-input)
     -0:13.1.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-formatter-jsbeautify 1.1.2 
atom-material-ui 2.1.3 
atom-vue 0.6.0 
busy-signal 2.0.1 
cssbeautify 1.3.0 
highlight-colors 0.8.0 
highlight-selected 0.16.0 
Hydrogen 2.12.1 
intentions 1.1.5 
linter 2.3.1 
linter-eslint 8.5.5 
linter-php 1.6.1 
linter-tslint 1.10.31 
linter-ui-default 1.8.0 
minimap 4.29.9 
php-cs-fixer 4.1.1 
vue-fmt 0.1.1 
```

**Comment by rsese** [comment] 2019-11-11 01:13
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

If the error is reproducible for you, please let us know the steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-11 01:13 UTC
