### ISSUE TITLE
Uncaught Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Nathan-Smith** [atom/atom#4985] opened 2015-01-11 11:15 UTC
[Enter steps to reproduce below:]

1. Checking for package updates.

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: connect ETIMEDOUT

```
At stream.js:94

Error: connect ETIMEDOUT
  at exports._errnoException (util.js:746:11)
  at Object.afterConnect [as oncomplete] (net.js:990:19)

```

### Commands

```
     -1:46.5 settings-view:open (atom-text-editor.editor)
     -0:12.0 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
  2x -0:03.9 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-scss-lint",
      "linter-jshint",
      "minimap"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "audioBeep": false
  },
  "editor": {
    "fontSize": 10,
    "showInvisibles": true,
    "showIndentGuide": true,
    "autoIndentOnPaste": false,
    "scrollPastEnd": true,
    "useShadowDOM": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.2.2
color-picker, v1.2.6
command-logger, v0.20.0
editor-stats, v0.16.0
editorconfig, v0.2.2
git-log, v0.2.0
git-tab-status, v1.3.0
hex, v0.3.10
language-groovy, v0.3.0
language-jade, v0.3.0
linter, v0.9.0
linter-cpplint, v0.1.3
live-archive, v0.1.7
seti-syntax, v0.2.1
seti-ui, v0.5.1

# Dev
linter-cpplint, v0.1.2
```

**Comment by Moter8** [comment] 2015-01-11 17:24
Well, the connection to the remote server timed out. This could be caused by temporary outages of the server or your internet. Try it again some hours later perhaps?

**Comment by lee-dohm** [comment] 2015-01-11 18:49
@Moter8 A timeout should display a simple message in the UI (if anything at all), not an Uncaught Exception dialog. This is a valid bug.

**Comment by Moter8** [comment] 2015-01-11 18:58
@lee-dohm I was aware of that, didn't word myself properly :/

**Comment by kevinsawicki** [comment] 2015-01-13 17:00
Fixed by https://github.com/atom/settings-view/commit/3fe0db5dc1c7db9f936b506a126d689057a24e0d

**Closed by kevinsawicki** 2015-01-13 17:00 UTC
Labels: bug
