### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by szabba** [atom/atom#11690] opened 2016-05-04 05:48 UTC
1. Open Atom.

**Atom Version**: 1.7.3
**System**: "Arch Linux"
**Thrown From**: Atom Core
### Stack Trace

Uncaught RangeError: Invalid string length

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:83

RangeError: Invalid string length
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:83:23)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```
### Commands

```
  5x -2:00.3.0 core:move-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
  7x -1:58.2.0 core:move-up (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -1:53.1.0 editor:newline (atom-text-editor.editor.hidden-line-numbers.is-focused)
  2x -1:52.3.0 core:backspace (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -1:51.2.0 core:save (atom-text-editor.editor.hidden-line-numbers.is-focused)
 10x -1:49.8.0 core:move-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
  3x -1:48.2.0 core:move-up (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -1:47.1.0 core:move-down (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -1:46.7.0 core:move-up (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:08.1.0 editor:consolidate-selections (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:08.1.0 core:cancel (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:08.0 editor:consolidate-selections (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:08.0 core:cancel (atom-text-editor.editor.hidden-line-numbers.is-focused)
     -0:07.4.0 editor:consolidate-selections (atom-text-editor.editor.hidden-line-numbers.is-focused)
  6x -0:07.4.0 core:cancel (atom-text-editor.editor.hidden-line-numbers.is-focused)
  2x -0:01.5.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-no-syntax-highlighting-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "destroyEmptyPanes": true,
    "disabledPackages": [
      "vim-mode",
      "keybinding-resolver",
      "ionide-fsi",
      "wrap-guide",
      "local-settings",
      "linter-jslint",
      "spell-check",
      "TODOs",
      "todo-list",
      "markdown-preview-plus",
      "markdown-folder",
      "markdown-toc",
      "builder-go"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".cvn",
      ".DS_Store",
      "._*",
      "Thumbds.db",
      "*.pyc",
      "*.pyo"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/home/karol/src/",
    "themes": [
      "one-dark-ui",
      "no-syntax-highlighting-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontFamily": "Hack",
    "fontSize": 13,
    "invisibles": {},
    "lineHeight": 1.7,
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "showInvisibles": true,
    "zoomFontWhenCtrlScrolling": false
  }
}
```
### Installed Packages

``` coffee
# User
Parinfer, v1.14.0
atom-slime, v2.3.3
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
autocomplete-glsl, v0.2.3
autocomplete-go, v1.0.8
autocomplete-love, v0.3.0
autocomplete-python, v1.7.2
bottom-dock, v0.4.4
bug-report, v0.7.1
django-templates, v0.5.0
environment, v1.2.0
file-icons, v1.7.8
file-watcher, v0.4.0
fold-functions, v0.4.3
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
godoc, v0.2.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
hyperclick, v0.0.36
hyperclick-love, v0.3.0
language-docker, v1.1.6
language-elm, v1.3.3
language-glsl, v2.0.1
language-haskell, v1.7.13
language-idris, v0.4.4
language-latex, v0.6.1
language-lisp, v0.2.0
language-lua, v0.9.4
language-python-django-templates, v0.1.0
language-restructuredtext, v0.13.0
language-rust, v0.4.6
language-scala, v1.1.6
language-scheme, v1.4.0
linter, v1.11.4
linter-clojure, v1.1.2
linter-elm-make, v0.4.0
linter-flake8, v1.13.0
linter-luaparse, v0.2.0
linter-scalac, v1.4.0
markdown-scroll-sync, v2.1.2
merge-conflicts, v1.4.2
navigator-godef, v1.0.3
no-syntax-highlighting-syntax, v0.2.11
project-manager, v2.9.7
python-isort, v0.0.7
python-tools, v0.6.7
scala-format, v0.1.8
select-rectangle, v1.0.2
term3, v0.22.0
tester-go, v1.0.4
todo-manager, v0.2.8
toggle-gutter, v0.2.2
wordcount, v2.6.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-05-04 19:33
@szabba Can you try reproducing this in safe mode (`atom --safe`)?  Thanks!

**Comment by lee-dohm** [comment] 2016-05-04 19:51
Could you also include more accurate steps to reproduce the problem? That command list is quite long for "Open Atom" to be the only step :grinning:

**Comment by szabba** [comment] 2016-05-05 19:36
@50Wliu I can't say I can reproduce it without it. It wasn't there when I opened Atom the next time. In the future I'll try not to report an error unless it happens repeatably.

@lee-dohm I might've left the error notification hanging for a moment before clicking the report button. :wink: 

Basically, it's ok to close it (not sure if it's ok for me to do it, so I'll leave it to you).

**Comment by lee-dohm** [comment] 2016-05-05 22:02
Thanks for reporting the problem and thank you for pointing out that the command list is generated when the Issue is submitted, not when the dialog is displayed. That's a bug we should fix ... it could be sending us down some blind alleys :grinning:

I'll close this for now. Please feel free to reopen it if you run into it again 👍

**Comment by jordanshipt** [comment] 2016-05-09 14:59
I'm still experiencing the error.


RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/Users/JordanHome/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:307:38)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)

**Comment by samboustani** [comment] 2016-05-09 18:43
This happens to me when I try to open a large JSON file (350 MB)

**Comment by jordanshipt** [comment] 2016-05-09 19:08
Have you found a work-around @samboustani

**Comment by samboustani** [comment] 2016-05-10 12:40
@jordanshipt I'm new to Atom and this was the first file I tried opening in it. I haven't looked for a solution yet.

**Comment by BlueTac92** [comment] 2016-05-23 20:39
I have just had the same error (at least, atom directed me to this bug).

I can reproduce by opening a file containing a single IP address on each line with approximately 34,000,000 lines .

**Comment by jcwatson11** [comment] 2016-05-24 18:01
I am having the same issue with a 300MB SQL file opened in Atom. Please fix.

**Comment by jordanshipt** [comment] 2016-05-24 20:30
I can take a look later tonight.


Thanks,

[image: Shipt-Logo-Screen-Color-RGB-Small.jpg]

Jordan Kerr | Lead Product Database Specialist
17 North 20th St Suite 100
Birmingham, AL 35203
*www.shipt.com* <http://www.shipt.com/>

**Comment by bosnj** [comment] 2016-05-30 12:22
Same issue here, 400MB text file, can't open.

**Comment by jfleisher** [comment] 2016-05-31 18:30
I am having this same issue. Always on folders with log files of 55-300Mb. Is there a resolution?

**Comment by vivekhaldar** [comment] 2016-06-07 04:07
See this issue while opening a large (300 MB) text file. Atom 1.9.0 beta on Mac.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310:38)
    at emitNone (events.js:85:20)
    at ReadStream.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:06.3.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "editor": {
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jfleisher** [comment] 2016-06-07 10:42
On Jun 7, 2016, at 12:08 AM, Vivek Haldar <notifications@github.com> wrote:

See this issue while opening a large (300 MB) text file. Atom 1.9.0 beta on Mac.
[Enter steps to reproduce below:]
Open Folder (my folder contains 50 or so log files from a windows service ranging in size from a few kb to to 34Mb.
Select small file from folder list and it will edit and display fine.
Select a large file from the list and Atom crashes (Happens on any file larger than 24Mb in my cases)
I have had even large files, but the smallest it has crashed on so far is 24Mb.

**Comment by 50Wliu** [comment] 2016-06-07 20:23
Re-opening as this appears to be reproducible using large files.

**Comment by rakmial** [comment] 2016-06-17 19:13
Same issue, error thrown attempting to open 500MB OpenStreetMap XML file.

`C:\Users\*\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:310

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (C:\Users\Bash\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:310:38)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)`

**Comment by davisonio** [comment] 2016-07-02 13:00
Having the same issue here, I opened a `mbox` file (exported from Apple Mail).

```
**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length


At /opt/homebrew-cask/Caskroom/atom/1.4.3/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.4.3/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310:38)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/craig/Documents/",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "invisibles": {},
    "showLineNumbers": false,
    "softTabs": false,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
devdocs, v0.2.1
file-icons, v1.7.4
highlight-selected, v0.11.2
less-than-slash, v0.13.0
minimap, v4.22.1
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.0
minimap-codeglance, v0.4.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.0
pigments, v0.26.0
travis-ci-status, v1.0.0
wordpress-api, v1.2.2

# Dev
No dev packages
```

```

**Comment by jordanshipt** [comment] 2016-07-04 03:14
I'm on a flight back from Thailand. I will take a look at the code when I
get time tomorrow afternoon. Can you send me all the details of the file
and what exactly happened when you were attempting to upload? Just from a
quick look, how are you using the events json call? Hope you have a good
4th of July!

Thanks,

Jordan Kerr

On Saturday, July 2, 2016, Craig Davison <notifications@github.com> wrote:

> Having the same issue here, I opened a mbox file (exported from Apple
> Mail).
>
> **Atom Version**: 1.8.0
> **System**: Mac OS X 10.11.6
> **Thrown From**: Atom Core
>
>
> ### Stack Trace
>
> Uncaught RangeError: Invalid string length
>
>
> At /opt/homebrew-cask/Caskroom/atom/1.4.3/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310
>
> RangeError: Invalid string length
>     at Array.join (native)
>     at ReadStream.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.4.3/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310:38)
>     at emitNone (events.js:72:20)
>     at ReadStream.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:905:12)
>     at doNTCallback2 (node.js:465:9)
>     at process._tickCallback (node.js:379:17)
>
> Config
>
> {
>   "core": {
>     "disabledPackages": [
>       "wrap-guide"
>     ],
>     "openEmptyEditorOnStart": false,
>     "projectHome": "/Users/craig/Documents/",
>     "themes": [
>       "one-dark-ui",
>       "solarized-dark-syntax"
>     ]
>   },
>   "editor": {
>     "backUpBeforeSaving": true,
>     "invisibles": {},
>     "showLineNumbers": false,
>     "softTabs": false,
>     "tabLength": 4
>   }
> }
>
> Installed Packages
>
> # User
> color-picker, v2.1.1
> devdocs, v0.2.1
> file-icons, v1.7.4
> highlight-selected, v0.11.2
> less-than-slash, v0.13.0
> minimap, v4.22.1
> minimap-autohide, v0.10.1
> minimap-bookmarks, v0.3.0
> minimap-codeglance, v0.4.5
> minimap-cursorline, v0.1.0
> minimap-find-and-replace, v4.5.1
> minimap-git-diff, v4.3.0
> minimap-highlight-selected, v4.4.0
> minimap-pigments, v0.2.0
> pigments, v0.26.0
> travis-ci-status, v1.0.0
> wordpress-api, v1.2.2
> # DevNo dev packages
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/atom/atom/issues/11690#issuecomment-230100649>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQWYQ9jNPYhlaCKj6-1LS2-kAROHB0_rks5qRmFAgaJpZM4IW2dW>
> .
>


-- 

[image: Shipt-Logo-Screen-Color-RGB-Small.jpg]

Jordan Kerr | Senior Product Data Analyst

p. 256-289-1901

Shipt
17 North 20th St Suite 100
Birmingham, AL 35203
*www.shipt.com* <http://www.shipt.com/>

**Comment by odupuy** [comment] 2016-07-06 18:19
Same issue with Atom 1.8.0 on Mac opening the 250 MB commit log file of Cassandra! Thanks

**Comment by h3adache** [comment] 2016-08-03 19:07
Same issue also from loading a large file (326M log file)

**Comment by PivotSportCTO** [comment] 2016-08-04 12:00
Same issue loading some Google Analytics raw data (exported from BigQuery as json)

**Comment by valugi** [comment] 2016-11-21 11:41
got the same opening 321 MB sql dump.

**Comment by msemple1111** [comment] 2016-11-21 17:40
same issue when opening 300+mb .txt file. 
Mac OS X 10.10 
atom 1.11.2.

Steps to reproduce:
1. get 300mb+ txt file
  Or generate one with this command `base64 /dev/urandom | head -c 300000000 > file.txt`

2. open file.txt
3. crash

**Comment by muhrifqii** [comment] 2017-01-27 07:06
Same issue openning 1.2 GB txt file on Ubuntu 16.0.4

[Enter steps to reproduce below:]

1. ope the .txt file
2. crash

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310:38)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "minimap-autohide",
      "minimap"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-clock, v0.1.3 (active)
autocomplete-python, v1.8.28 (active)
file-icons, v2.0.12 (active)
git-plus, v7.2.0 (active)
highlight-selected, v0.12.0 (active)
language-gradle, v0.0.3 (active)
language-kotlin, v0.5.0 (active)
language-latex, v1.0.0 (active)
latex-autocomplete, v1.0.0 (active)
latex-completions, v0.3.2 (active)
linter-write-good, v0.8.0 (active)
markdown-writer, v2.6.3 (active)
minimap, v4.26.7 (inactive)
minimap-autohide, v0.10.1 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (active)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by erikhuizinga** [comment] 2017-02-07 13:16
I have the same problem with a 300+MB JSON file on macOS 10.12.3 with Atom 1.13.1 x64. Happens with my default configuration (some packages) and with the `--safe` switch enabled.

**Comment by lzj1989712** [comment] 2017-02-24 07:25
same issue When I open a 320+MB binary file, with atom 1.14.3 x64  win10  。

**Comment by jacopofar** [comment] 2017-03-15 16:51
It happens on Atom 1.15 on macOS, trying to open a 348MB text files with a few KBs for each row

```
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310
Hide Stack Trace
RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310:38)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jrmyr** [comment] 2017-03-16 13:28
Same for me, here's the exact error report from Atom:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310

RangeError: Invalid string length
    at Array.join (native)
    at /app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310:38)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
minimap-split-diff 0.3.6 
split-diff 1.2.0 
Sublime-Style-Column-Selection 1.7.4 
xml-tools 0.2.1 
```

**Comment by lcjdot** [comment] 2017-04-04 20:01
I am trying to open a sql file (528mb) to conduct a find/replace and get the error:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310

RangeError: Invalid string length
    at Array.join (native)
    at /app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:310:38)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by said026** [comment] 2017-05-02 13:02
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length

```
At /opt/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:310

RangeError: Invalid string length
    at Array.join (native)
    at /app.asar/node_modules/pathwatcher/lib/file.js:310:38)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
language-scala 1.1.8 
react 0.16.2 
```

**Comment by Maki711** [comment] 2017-05-31 12:07
[Enter steps to reproduce:]

1. Select a db.sql that is 416MB big
2. Crash with the error...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: WARTOP
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid string length

```
At C:\Users\Maki\AppData\Local\atom\app-1.17.2\resources\app\node_modules\pathwatcher\lib\file.js:314

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/pathwatcher/lib/file.js:314:1)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
### Non-Core Packages

```
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.6.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
```

**Comment by mitchellcash** [comment] 2017-06-09 14:24
**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Description

Cannot open a large CSV file within Atom.

### Steps to Reproduce

1. Download Australian Company Dataset http://data.gov.au/dataset/7b8656f9-606d-4337-af29-66b89b2eeefb/resource/a1df019f-cb11-43e8-8d5d-0f830115c8a6/download/company201706.zip
2. Unzip the file, which will show a CSV which is 286 MB on disk
3. Open CSV in Atom

### Stack Trace

Uncaught RangeError: Invalid string length

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:314

RangeError: Invalid string length
    at Array.join (native)
    at ReadStream.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/file.js:314:1)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by lee-dohm** [comment] 2017-06-09 15:16
This crash appears to be fixed in the latest `master` with the merge of https://github.com/atom/atom/pull/14435, which is currently scheduled for release in Atom v1.19.

**Closed by lee-dohm** 2017-06-09 15:16 UTC
Labels: bug, uncaught-exception
