### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/pw/39drj2gd3kvgyqt...

### ISSUE THREAD

**Issue by svoun** [atom/atom#15956] opened 2017-10-21 04:33 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents'

```
At fs.js:902

Error: ENOENT: no such file or directory, lstat '/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at realpathSync (fs.js:1542:21)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:331:24)
    at toRealPath (module.js:130:13)
    at Function.Module._findPath (module.js:178:22)
    at Module._resolveFilename (module.js:468:25)
    at Module._resolveFilename (/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_CommandEvent (/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:22:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:618:38)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/private/var/folders/pw/39drj2gd3kvgyqtx7lmj52yc0000gn/T/AppTranslocation/2E8136EF-CDBB-4BB8-8E58-C9A69BFA3D48/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-10-21 05:50
Guessing the error isn't reproducible?  Also, did you come across this error after updating Atom?

Based on the stack trace, going to go ahead and close as a duplicate of https://github.com/atom/atom/issues/15878.

**Closed by rsese** 2017-10-21 05:50 UTC
