### ISSUE TITLE
Feature: Add Repo During Install of Deb Package for Automatic Updates

### ISSUE THREAD

**Issue by akorcharlie** [atom/atom#14981] opened 2017-07-10 13:20 UTC
There's either an obvious reason for this not being the case or it was an oversight but it would be handy if on Debian based Linux OSes we'd get updates and upgrades every time we ran apt-get update && apt-get upgrade.

**Comment by rsese** [comment] 2017-07-11 20:32
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/2956. You may want to subscribe there for updates but also see this comment for the most general comment about the issue status: https://github.com/atom/atom/issues/2956#issuecomment-264260509.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-11 20:32 UTC
