### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/inigohernandez/.atom/packages/sav...

### ISSUE THREAD

**Issue by damarte** [atom/atom#9523] opened 2015-11-11 08:35 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/inigohernandez/.atom/packages/save-session/projects//Applications/MAMP/htdocs/iWineBackend/project.json'

```
At fs.js:60

Error: ENOENT: no such file or directory, open '/Users/inigohernandez/.atom/packages/save-session/projects//Applications/MAMP/htdocs/iWineBackend/project.json'
    at Error (native)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as getSize] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
    at Atom.module.exports.Atom.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:510:29)
    at Atom.module.exports.Atom.storeDefaultWindowDimensions (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:542:25)
    at module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:228:19)
```

### Commands

```
  4x -1:47.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:47.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:47 project-manager:list-projects (atom-text-editor.editor)
  2x -1:45.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:44.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -1:42 click (div.header.list-item)
     -0:50.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:49.4.0 click (atom-text-editor.editor.is-focused)
     -0:48.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:48.6.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:45.8.0 click (atom-text-editor.editor.is-focused)
     -0:42.6.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:41.3.0 click (atom-text-editor.editor.is-focused)
     -0:14 core:paste (atom-text-editor.editor.is-focused)
  3x -0:11 click (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "monokai"
    ],
    "projectHome": "/Applications/MAMP/htdocs/",
    "disabledPackages": [
      "local-history",
      "cakephp-snippets",
      "live-archive",
      "goto"
    ],
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {},
    "showIndentGuide": true,
    "softTabs": false,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.17
atom-minify, v0.5.0
atom-pair, v2.0.10
autocomplete-php, v0.3.7
color-picker, v2.0.13
editor-stats, v0.17.0
file-icons, v1.6.11
laravel, v0.7.0
linter, v1.10.0
linter-csslint, v1.1.0
linter-php, v1.1.1
monokai, v0.18.0
native-ui, v0.7.1
php-debug, v0.1.3
php-extract-method, v0.2.0
pretty-json, v0.4.1
project-manager, v2.6.5
save-session, v0.15.7
symbols-tree-view, v0.10.1

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment] 2015-11-11 23:21
I think this exception has to do with the `save-session` package. Does it happen if you disable or uninstall that package?

**Comment by lee-dohm** [comment] 2015-12-17 07:16
Since there hasn't been a response to the request for more information, I'm going to close this. Please let us know if the issue reproduces for you.

**Closed by lee-dohm** 2015-12-17 07:16 UTC
Labels: more-information-needed, uncaught-exception
