### ISSUE TITLE
invisible ETX character

### ISSUE THREAD

**Issue by kukac7** [atom/atom#13822] opened 2017-02-15 11:07 UTC
### Description

I do not see the editing interface of the [ETX](https://en.wikipedia.org/wiki/End-of-Text_character) character.
(For example, if you enter a photoshop text and copy it, the characters are not visible.)
Later this website bad characters that appear as a result.
The editor just an invisible character is displayed and can not be filtered.

### Versions

* Atom: latest (1.14.2)

**Comment by rsese** [comment] 2017-02-16 05:55
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12157 which is tracking enhancements and fixes around invisible characters. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-02-16 05:55 UTC
Labels: duplicate
