### ISSUE TITLE
Uncaught TypeError: Cannot read property 'editors' of undefined

### ISSUE THREAD

**Issue by micahblu** [atom/atom#8065] opened 2015-07-24 18:34 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'editors' of undefined

```
At /Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:745

TypeError: Cannot read property 'editors' of undefined
    at /Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/symbol-provider.js:115:54
    at Emitter.module.exports.Emitter.emit (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:594:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:12)
    at Selection.module.exports.Selection.insertText (/Applications/Atom 2.app/Contents/Resources/app.asar/src/selection.js:468:43)
    at /Applications/Atom 2.app/Contents/Resources/app.asar/src/text-editor.js:2415:30
    at /Applications/Atom 2.app/Contents/Resources/app.asar/src/text-editor.js:778:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom 2.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom 2.app/Contents/Resources/app.asar/src/text-editor.js:1151:26)
    at /Applications/Atom 2.app/Contents/Resources/app.asar/src/text-editor.js:772:24
```

### Commands

```
  3x -0:27.1.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:25.9.0 core:redo (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:14 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:12.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:11.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:10 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:07.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:04.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:01.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
remote-sync, v3.1.2

# Dev
No dev packages
```

**Comment by benogle** [comment] 2015-07-24 18:41
Closing as dupe of https://github.com/atom/autocomplete-plus/issues/480 Not sure why this wasnt attributed to ac+

**Closed by benogle** 2015-07-24 18:41 UTC
Labels: uncaught-exception
