### ISSUE TITLE
Downloaded Atom 1.40.1 - hoping I can get it working with new PyMakr

### ISSUE THREAD

**Issue by jdcrunchman** [atom/atom#19936] opened 2019-09-20 17:14 UTC
After downloading the new Atom,   it was able to load in my project,   but I cannot access any of the plugins.    Somehow I cannot access the plugins.   In one of the earlier recommendations,  they said to load Atom in safe mode .  $atom --safe

But then I do that,   I get...  $ atom --safe
-bash: atom: command not found
 NONE of the plugins appear right now.   I go to "About Atom" and nothing but a blank screen comes up.   I'm in the middle of a serious project,  all of my development efforts came to a screeching halt.

I go to the packages menu,  and see PyMakr,  but then it gives me 3 choices...   
toggle pycom control
run current file
Synchronize project

NONE of these items do anything.

Why is my brand new copy of Atom not able to bring up the plugins?   Something is corrupted, and I'm not an Atom programmer,  nor do I have any clue how to fix it.

Can someone please help me?    I know the Atom developers are busy fixing bugs,  but is there anyway the developers can contact me directly at jdcrunchman at gmail dot com?

**Comment by Arcanemagus** [comment] 2019-09-20 18:07
Thanks for taking the time to contribute!

We noticed that this is a duplicate of [https://github.com/atom/atom/issues/19913]. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-09-20 18:07 UTC
