### ISSUE TITLE
Linux moving to trash

### ISSUE THREAD

**Issue by Akumetsu-Dev** [atom/atom#14940] opened 2017-07-03 01:48 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The following file couldn't be moved to the trash.
/srv/www/htdocs/index.php
Is gvfs-trash installed?

the system i use (openSUSE Tumbleweed: KDE) recommend use gio trash (gio help trash for more infor)

### Steps to Reproduce

1. Open Atom.
2. Select file and press delete.
3. Alert appear click move to trash.
4. Error Appear.

**Expected behavior:** File Deleted

**Actual behavior:** Error by package gvfs-trash

**Reproduces how often:** Everytime

### Versions
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git

OS info
 OS: Opensuse 20170529
 Kernel: x86_64 Linux 4.11.7-1-default
 
KDE 5.34.0 / Plasma 5.10.2
WM: KWin
CPU: Intel Core i5-2430M @ 4x 3GHz [69.0°C]
GPU: intel
RAM:5744MiB

### Additional Information

what the OS said:
gvfs-trash
This tool has been deprecated, use 'gio trash' instead.
See 'gio help trash' for more info.

**Comment by rsese** [comment] 2017-07-03 20:58
Thanks for the report!  I think this is basically a duplicate of https://github.com/atom/tree-view/issues/345 where I think this is blocked as described here?

https://github.com/atom/tree-view/issues/345#issuecomment-248072158

So Electron needs to be updated to support different trash clients and it looks like it was in:

https://github.com/electron/electron/pull/7178

But I don't believe the version of Electron containing that work is included in Atom 1.18.0.

Going to go ahead and close as a dupe for now but let me know if I mis-understood anything.

**Closed by rsese** 2017-07-03 20:58 UTC
