### ISSUE TITLE
Selecting text doesn't work like it should (macOS)

### ISSUE THREAD

**Issue by v57** [atom/atom#18842] opened 2019-02-14 01:19 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When you select text using double mouse click it doesn't works like in macOS standard text selection. I'm selecting text like this a lot in Xcode and this is really annoying when you sometimes can't do the same in atom.

Here how it works in Atom:
![atom](https://user-images.githubusercontent.com/2669441/52755203-321dcd00-300e-11e9-8650-9c91ffead5e8.gif)

And TextEdit:
![textedit](https://user-images.githubusercontent.com/2669441/52755199-2df1af80-300e-11e9-84fb-22b7024d245a.gif)

### Steps to Reproduce

```
// When you select "array[0]" it selects "array[0]," instead
some(array[0], b)
// When you select "func2()" it selects "func2());" instead
func1(func2());
```

### Versions

Atom    : 1.33.1
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
macOS 10.14.1

**Comment by rsese** [comment] 2019-02-14 06:37
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/10374 so you can subscribe there if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-14 06:37 UTC
