### ISSUE TITLE
[BUG] Previous version of Atom stays in RAM after an update

### ISSUE THREAD

**Issue by AlexSHoffman** [atom/atom#16979] opened 2018-03-18 18:10 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After Atom is updated and closed, it stays in memory:

![image](https://user-images.githubusercontent.com/13764106/37569197-d3806830-2aef-11e8-9a89-c39793c71d51.png)

### Steps to Reproduce

1. Update Atom
2. See the open processes, the previous version is probably going to be in there

**Expected behavior:** all Atom's processes are closed after the update

**Actual behavior:** stays in memory

**Reproduces how often:** do not know.

### Versions

Updated `1.23.2` to `1.25.0`

**Comment by Ben3eeE** [comment] 2018-04-05 06:20
@lee-dohm Yes I can reproduce this issue when updating from 1.24.1 to 1.25.0.

In my case pressing `Restart and Install Update` closed Atom but didn't close every process from 1.24.1. Atom never started automatically after a couple of minutes waiting so I manually started Atom 1.25.0 from the command line again.

**Comment by Ben3eeE** [comment] 2018-04-19 06:06
I had the same issue when updating from 1.26.0-beta2 to 1.27.0-beta0. Atom does not restart when I click `Restart and Install Update` it only closes and leaves several processes in the task manager.

**Comment by rsese** [comment] 2019-06-13 01:21
Can you still reproduce this part @Ben3eeE?

> and leaves several processes in the task manager.

I don't see this when I update from 1.37.0 to 1.38.0.

If you don't, I was going to close this and use https://github.com/atom/atom/issues/19493 for the other issue where Atom only closes but doesn't restart on update on Windows.

**Comment by Ben3eeE** [comment] 2019-06-20 07:32
@rsese I am unable to reproduce it on nightly

**Comment by rsese** [comment] 2019-06-22 00:00
Thanks for confirming :bow:  If you see differently @AlexSHoffman please let us know.

Going to go ahead and close this out and use https://github.com/atom/atom/issues/19493 to track the fact that you have to manually restart Atom after update on Windows.

**Closed by rsese** 2019-06-22 00:00 UTC
Labels: d ⬆️, i ⬇️, triaged, v ⬆️
