### ISSUE TITLE
After setting custom scrollbar style, my scrollbar disappears

### ISSUE THREAD

**Issue by cortical-iv** [atom/atom#17146] opened 2018-04-16 03:10 UTC
Followed the guidelines described elsewhere and inserted the following in `styles.less` to ensure my scrollbar is always visible and larger than the default skinny little gray thing. The following is as described at https://discuss.atom.io/t/change-the-color-and-width-of-editors-sidebar/18545 : 
```
// style scrollbar
.scrollbars-visible-always {
/deep/ ::-webkit-scrollbar {
width: 20px;
height: 20px;

&-track {
  border: 0px;
  border-radius: 0px;
  background-color: rgb(100, 100, 100) !important;
}

&-thumb {
  background-color: rgb(205, 100, 31) !important;
  border: 1px;
  border-radius: 1px;
}}}
```
When I put the above in `styles.less` and save it, the scrollbar temporarily shows up, but then disappears when I leave Atom, or switch to a new tab within Atom.  Switching to safe mode doesn't change anything. Strangely, hitting `ctrl-\` a few times sometimes helps for a little while (this toggles tree view).

When I delete the above style for my scrollbar, the little skinny gray default scrollbar shows just fine. I'd love to have my big thick scrollbar work all the time!

My version information:
```
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
Related issue:   
https://github.com/atom/atom/issues/15107

**Comment by Ben3eeE** [comment] 2018-04-16 05:45
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17002. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-04-16 05:45 UTC
Labels: duplicate

**Comment by cortical-iv** [comment] 2018-04-16 14:06
Thanks sorry I missed that one.
