### ISSUE TITLE
[bug?] [github] new TextEditor-based diff viewer froze on huge diff

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18685] opened 2019-01-13 00:33 UTC
Although things are now better, very huge diffs can still 'freeze' Atom. For example, the bundle generated by a library of mine include the entire library, and so any time I update the bundle the diff is huge (it is checked in). So I accidentally froze Atom by clicking on it.

It'd be great to have an option to restore the old feature where large diffs are hidden by default, and require an additional click to show them.

**Comment by rsese** [comment] 2019-01-14 20:41
Thanks for the report!

We noticed that this looks like a duplicate of https://github.com/atom/github/issues/1759 so you can subscribe there for updates if you'd like.  Please note that GitHub package specific issues can be opened in https://github.com/atom/github :v:

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-01-14 20:41 UTC
