### ISSUE TITLE
Uncaught Error: Module did not self-register: '/usr/share/atom/resources/app.asar.unpacked/node_m...

### ISSUE THREAD

**Issue by MichaelDouglas94** [atom/atom#22799] opened 2021-08-01 04:15 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Pop!_OS 21.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register: '/usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'.

```
At electron/js2c/asar.js:140

Error: Module did not self-register: '/usr/share/atom/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'.
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at get_KeyboardLayoutManager (/usr/share/atom/resources/app/static/<embedded>:14:2894476)
    at get_manager (/usr/share/atom/resources/app/static/<embedded>:14:2894578)
    at Object.getCurrentKeyboardLayout (/usr/share/atom/resources/app/static/<embedded>:14:2894704)
    at e.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:14:1119649)
    at KeymapManager.keystrokeForKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1224825)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1222810)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:286651)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by MichaelDouglas94** [comment] 2021-08-01 04:16
I using Linux (Pop_Os )

**Comment by mykeysway** [comment] 2021-08-01 21:42
So I believe, you have to identify the 
Stage Hunk.

@@ -284,6 +284,10 @@ export default  class StagingView {
284  284   @autobind
285  285  
286  286   asyncdiveIntoSelection() {
         287  
         289   +const selectedItems = this.
         290   selection.getSelectedItem();
                   +if (selectedItems.size ! = =     
                   1) {
                   + return;
 287 291    + }
 288 292        
 289 293

**Comment by darangi** [comment] 2021-08-23 07:41
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2021-08-23 07:41 UTC
