### ISSUE TITLE
Windows install date in the future

### ISSUE THREAD

**Issue by ismyrnow** [atom/atom#9178] opened 2015-10-16 19:09 UTC
In Windows 8.1, the install date shows a future date.

![atom_install_date](https://cloud.githubusercontent.com/assets/1127410/10550943/df299e40-7417-11e5-8a70-79177e3411da.png)

I'm not sure if this is a Windows issue or an Atom one, but I've never seen this before for another program. If it's not an Atom issue, I'm happy to close this as resolved.

**Comment by mnquintana** [comment] 2015-10-16 19:13
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/6606 - please subscribe there for updates.

**Closed by mnquintana** 2015-10-16 19:13 UTC
Labels: installer, windows
