### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of ~

### ISSUE THREAD

**Issue by rick-kilgore** [atom/atom#15931] opened 2017-10-18 18:37 UTC
[Enter steps to reproduce:]

1. Clicked on an updates button in the bottom right
2. Updated one plugin - vim-mode-plus
3. Clicked on Update All
4. got the error popup

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/updates-panel.js:312

TypeError: Cannot read property 'then' of undefined
    at UpdatesPanel.updateAll (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/updates-panel.js:312:37)
    at HTMLButtonElement.onclick (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/updates-panel.js:152:36)
```

### Commands

```
     -0:34.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  4x -0:24.1.0 click (button.btn.btn-info.icon.icon-cloud-download.install-button)
```

### Non-Core Packages

```
clang-format 1.29.0 
file-icons 2.1.10 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.69.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.11 
nuclide 0.260.75053414 
nuclide-format-js 0.0.41 
php-extract-method 0.2.1 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
vim-mode-plus 1.9.1 
```

**Comment by 50Wliu** [comment] 2017-10-18 18:39
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/settings-view#879. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-10-18 18:39 UTC
