### ISSUE TITLE
更新到1.9后，编辑需要授权的文件异常

### ISSUE THREAD

**Issue by gooking** [atom/atom#15428] opened 2017-08-24 01:18 UTC
我用的 MAC 系统，以前的版本，用 atom 编辑 /etc/hosts 文件的时候，会提示让我授权的界面

但是现在升级到 1.9 以后，编辑这个文件直接就提示错误了，说没权限

能否改回之前的那种模式，之前体验很好，编辑这种文件的时候，新款 MAC 会提示授权窗口，我一按指纹就修改成功了

**Comment by Ben3eeE** [comment] 2017-08-24 06:14
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15267. This has been fixed in Atom 1.9.3.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-24 06:14 UTC
