### ISSUE TITLE
Broken indentation indicators

### ISSUE THREAD

**Issue by skeyl** [atom/atom#9737] opened 2015-11-21 16:38 UTC
OS: Mint 17.2
Atom: 1.2.0

The indicators are broken (not a perfect line). I can fix this by deleting a line and pushing enter to get them flush again. It appears to do this upon loading of the file; new files do not do this (unless I reload it).

![selection_002](https://cloud.githubusercontent.com/assets/7646510/11319422/47e535f0-9044-11e5-9360-88d769170bd2.png)

**Comment by 50Wliu** [comment] 2015-11-21 20:57
Duplicate of #9369, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-21 20:57 UTC

**Comment by skeyl** [comment] 2015-11-21 21:28
Ah sorry, I searched for broken and didn't find.
