### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by frenchbread** [atom/atom#12372] opened 2016-08-09 12:48 UTC
**Atom Version**: 1.10.0-beta1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)

```
At /Applications/Atom Beta.app/Contents/Resources/electron.asar/renderer/api/remote.js:178

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/Applications/Atom Beta.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)
    at undefined.remoteMemberFunction (/Applications/Atom Beta.app/Contents/Resources/electron.asar/renderer/api/remote.js:112:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/atom-environment.js:636:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/atom-environment.js:670:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:182:35)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
     -1:10.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:09.2.0 core:move-up (atom-text-editor.editor.is-focused)
  7x -1:08.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:07.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:06.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:00.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:58.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:32.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:31.1.0 core:close (atom-text-editor.editor.is-focused)
     -0:28.3.0 git-plus:add-all-commit-and-push (atom-workspace.workspace.seti-ui-no-icons.theme-firewatch-syntax.theme-one-dark-ui.scrollbars-visible-when-scrolling)
     -0:25 core:backspace (atom-text-editor.editor.is-focused)
     -0:22.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:22.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:21.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "firewatch-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
aesthetic-ui, v2.0.0 (inactive)
atom-jade, v0.3.0 (active)
color-picker, v2.2.2 (active)
es6-javascript, v1.0.0 (inactive)
file-icons, v1.7.18 (active)
firewatch-syntax, v1.0.1 (active)
git-plus, v5.16.2 (active)
github-atom-light-syntax, v0.2.0 (inactive)
highlight-selected, v0.11.2 (active)
language-erlang, v3.0.0 (active)
linter, v1.11.16 (active)
linter-xo, v0.16.0 (active)
minimap, v4.24.7 (active)
minimap-highlight-selected, v4.4.0 (active)
my-github-profile, v0.2.1 (active)
pigments, v0.31.2 (active)
pretty-json, v1.5.1 (active)
project-manager, v2.9.7 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-08-09 13:31
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-09 13:31 UTC
