### ISSUE TITLE
Spaces are rendering after soft line breaks rather than before

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#18195] opened 2018-10-05 00:19 UTC
### Description

👋 

![screen shot 2018-10-04 at 6 09 42 pm](https://user-images.githubusercontent.com/1789/46509661-4e5c6280-c801-11e8-87d3-62836d013255.png)

In the image above, notice how the last segment of the soft-wrapped line begins with a space. This is distracting and we took care in the original implementation to ensure that spaces like this always go to the previous line. I'm wondering if #18087 or #17949 may have introduced this regression recently.

### Steps to Reproduce

1. Enter soft wrap mode
2. Arrange things such that a space lands right after the soft-wrap boundary

**Expected behavior:** The space should stay on the previous line or not be rendered at all

**Actual behavior:** The space renders at the start of the soft wrap line

**Reproduces how often:** 100%

### Versions

Atom    : 1.33.0-dev-1e5575e91
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

This correctness of this behavior is of course subjective, but we followed TextMate and Sublime when originally keeping spaces at the end of the preceding line before soft wraps. I find the current behavior pretty distracting. Thanks for your time ❤️.

/cc @smashwilson @daviwil @ariasuni

**Comment by maxbrunsfeld** [comment] 2018-10-07 03:37
I noticed this too. @ariasuni @daviwil Do you think it could have been caused by #17949?

**Comment by thomasjo** [comment] 2018-10-08 10:48
Definitely caused by #17949; that's one of the features introduced in the PR, breaking lines _before_ a space. The end result is therefore that the wrapped lines might begin with a space. Why this change to space handling was introduced is not immediately obvious. I agree with @nathansobo that this change is pretty distracting, and in my opinion, a regression that should be fixed. Seems like something that can be fixed quite easily :sparkles: 

Whether we should simply remove the `' '` equality or switch from `character` to `previousCharacter` needs to be tested. We should also introduce another test case or two to guard against future regressions.

For the reference, the line of code that introduced this change in wrapping behavior:
https://github.com/ariasuni/atom/blob/81364b6a1c6c93248fbc43159e7dd5355cb60e6c/src/text-utils.js#L107

**Comment by ariasuni** [comment] 2018-10-08 21:12
If I remove `|| character === ' '`, then it breaks lines this way (`|` is the character limit, `␣` is space):

```
this␣is␣  |
a␣␣test   |
```

Is it the behavior you want?

**Comment by daviwil** [comment] 2018-10-16 20:56
@ariasuni yep, that sounds right.  The main issue here is the line wrapping before a space.  If you can submit a PR with the change that @thomasjo refers to in his comment, that'd be super helpful!

**Closed** 2018-10-20 17:11 UTC
Labels: editor-rendering, regression

**Comment by ariasuni** [comment] 2018-10-22 12:49
Sorry, didn’t have the time ^^
