### ISSUE TITLE
Autodetect does not recognize the ISO-8859-1 encoding correctly

### ISSUE THREAD

**Issue by Webysther** [atom/atom#10939] opened 2016-02-23 20:54 UTC
### Description

Autodetect does not recognize the ISO-8859-1 encoding correctly, is showing how ibm855 or windows 1251.

I know that there is a detection problem of how the encoding table is checked and it is not 100% safe.

I suggest changing the way the auto-detection work, allowing to put a list of preferred character sets during automatic detection. Many projects differ only between UTF-8 and ISO-5598-1, allowing just put the two for automatic detection helps quite a lot.

That way you can put lipstick on the direction to detect all projects that use the programmer without having to change or set up every time.

Allowing put comma separated encoding which must support is a good start, as is the ignored names.

![](https://raw.githubusercontent.com/Webysther/sample.atom.encoding/master/printscreen.png)

### Steps to Reproduce

1. Copy sample file on [zip of repo](https://github.com/Webysther/sample.atom.encoding)
2. Open on Atom and force autodetect

**Expected behavior:** Detect ISO-8859-1

**Actual behavior:** Detect Windows 1251

### Versions

1.5.3

**Comment by rthiago** [comment] 2016-02-26 21:45
You can try using the [default-encoding](https://atom.io/packages/default-encoding) package so you can set the encoding for different file types.

I'm using uft-8 as default and iso-8859-1 for php files and it works with your sample.

My config is something like this:

```CoffeeScript
"*":
  # ...
  defaultEncoding: "utf8"
".php":
  defaultEncoding: "iso88591"
```

**Comment by lee-dohm** [comment] 2016-02-29 23:39
This appears to be a duplicate of https://github.com/atom/atom/issues/10252. Please let us know if that is not the case!

Thanks for your detailed description too!

**Closed by lee-dohm** 2016-02-29 23:39 UTC

**Comment by yesroh** [comment] 2017-03-17 18:26
@rthiago where I can find this file?

**Comment by rthiago** [comment] 2017-03-17 18:48
The sample? I think it's gone :(

**Comment by yesroh** [comment] 2017-03-18 15:14
No, in my atom. Where I can find this file on my editor

**Comment by rthiago** [comment] 2017-03-18 16:07
I don't remember, but it' probably on atom's configuration
