### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.28.1\res...

### ISSUE THREAD

**Issue by Daiva-Pamaiva** [atom/atom#17666] opened 2018-07-11 11:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\dbale\AppData\Local\atom\app-1.28.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:172

Error: The specified module could not be found.
\\?\C:\Users\dbale\AppData\Local\atom\app-1.28.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.28.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.28.1/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by steveward** [comment] 2018-07-11 18:00
Thanks for reaching out!  It would be great if you can fill out the issue template, the information is really helpful for us when triaging issues.  In particular, please share exact numbered step-by-step instructions to reproduce, what you expect to happen, and what actually happens - if you can share an example file to try, that would be great too.

And please share what you have set for `Settings > Editor > Tab Type`.

Once you have done that, can you confirm a few things for us?

- what were you doing at the time of the error?
- is the error reproducible?
- if reproducible, do you see the error in safe mode (atom --safe)?

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by steveward** [comment] 2018-07-11 18:07
This also looks like a duplicate of https://github.com/atom/atom/issues/15722 -- are you running anti-virus software on your machine that could be causing this issue? If you are not running any anti-virus software I would recommend trying to reinstall Atom to see if that gets things working.

**Closed by steveward** 2018-07-11 18:07 UTC
Labels: duplicate

**Comment by Daiva-Pamaiva** [comment] 2018-07-15 05:50
Thanks!
It was helpfull.

2018 m. liep. 11 d., tr 21:08, Steve Ward <notifications@github.com> rašė:
