### ISSUE TITLE
Editor freezes when I try to open html files.

### ISSUE THREAD

**Issue by ankibahuguna** [atom/atom#5495] opened 2015-02-11 07:21 UTC
I am using windows 32 bit OS.When I try to  open html files ,the editor stops responding ,the file editing area becomes unclickable.
Here is the screenshot of the issue:  http://prntscr.com/63oo3q

**Comment by izuzak** [comment] 2015-02-11 10:52
@ankibahuguna Does that file perhaps a very long line? I have a feeling that it does by looking at the horizontal scrollbar, and if that's true -- you're probably experiencing this issue: https://github.com/atom/atom/issues/979. 

Can you confirm that this doesn't happen for an html file which doesn't have long lines like that?

**Comment by izuzak** [comment] 2015-02-11 10:53
Also, which version of Atom are you using?

**Comment by ankibahuguna** [comment] 2015-02-12 10:42
Hi,
Yes.I tried to open a simpler html file with shorter lines ,it works fine.But the moment I try to open a larger file ,editor just freezes and stops responding.The same file opens smoothly on notepad++.
I am using  version 0.177.0.

**Comment by izuzak** [comment] 2015-02-12 10:45
Thanks for confirming. I'm closing this as a duplicate of #979 and #307 then. Subscribe to those issues for updates.

**Closed by izuzak** 2015-02-12 10:45 UTC
Labels: more-information-needed
