### ISSUE TITLE
Atom should respect OS X standard file locations

### ISSUE THREAD

**Issue by CyberSkull** [atom/atom#11014] opened 2016-03-01 12:33 UTC
Atom is not making full use of the standard file storage locations/conventions on OS X. OS X provides standard locations for storing configuration, data and cache files. Those location should be used instead of the  `~/.atom/` folder. Most of the items found in `~/.atom/` should be moved to `~/Library/Application Support/Atom/`.

The following files should be moved to `~/Library/Application Support/Atom/`:
* `blob-store`
* `config.cson`
* `dev`
* `init.coffee`
* `keymap.cson`
* `packages`
* `snippets.cson`
* `storage`
* `styles.less`

The following files should be moved to `~/Library/Caches/Atom/`:
* `compile-cache`
* `Cache` (move from `~/Library/Application Support/Atom/`)
* `GPUCache` (move from `~/Library/Application Support/Atom/`)

**Comment by hultberg** [comment] 2016-03-01 12:44
Related to #8281

**Comment by lee-dohm** [comment] 2016-03-01 19:09
Thank you for the feedback. While this is something that we may do for future major versions, we won't be considering this for v1.0.

**Comment by CyberSkull** [comment] 2016-03-01 23:17
It is especially important that the cache files be moved, as currently they are caught up in Time Machine backups.

**Comment by lee-dohm** [comment] 2016-03-01 23:24
With the exception of the locations being different and being a different platform, this is a duplicate of #8281. @CyberSkull, would you mind posting the specifics of what needs to be done for OS X on that Issue so that we can keep track of this all in one place?

**Comment by lee-dohm** [comment] 2016-03-01 23:59
Thanks very much @CyberSkull. I'm going to close this in favor of the original so that we can keep track of it all in one spot.

Thank you for reporting and documenting this.

**Closed by lee-dohm** 2016-03-01 23:59 UTC
Labels: feedback, mac
