### ISSUE TITLE
Samba shares and Atom

### ISSUE THREAD

**Issue by KvanSteijn** [atom/atom#10598] opened 2016-01-26 22:11 UTC
Hello,

I have some problems with Atom and Samba shares. All samba shares that i used have their own Git repo. The first problem is that the package Git diff believes that all files are modified, but after changing the Git config (core.fileMode) works the package perfectly. But that's an option for me. The second problem is that Atom sometimes crashed with samba shares. It seems that Atom has difficulty waiting for a response from Samba. The last problem is that changing words in a samba share can damage files. The word had to be changed is replaced with nothing.

**Comment by lee-dohm** [comment] 2016-01-27 00:48
It sounds like this is a duplicate of https://github.com/atom/atom/issues/10596. Let us know if you believe this to not be the case.

**Closed by lee-dohm** 2016-01-27 00:48 UTC
Labels: duplicate

**Comment by KvanSteijn** [comment] 2016-01-28 19:23
No, because my issue is different. Atom showed the wrong color by Git repo's in a Samba share. The files are not modified. The last problem is that the replace method in Atom, the method doen't work every time. The application crasht after pressing the replace button and the word is replaced with nothing. 

Before:
`function test() {
}`

After:
`function () {
}`
