### ISSUE TITLE
atom -w requires the entire window be closed, not just the tab

### ISSUE THREAD

**Issue by alex** [atom/atom#5127] opened 2015-01-17 22:17 UTC
This is slightly inconvenient when one uses `atom -w` for things like git commit messages, it'd be great if just closing the tab that was opened was enough to cause the process to exit.

**Comment by izuzak** [comment] 2015-01-30 13:18
@alex This sounds very similar to https://github.com/atom/atom/issues/863 -- would you consider your suggestion a duplicate of that? If not -- can you clarify the difference?

**Comment by alex** [comment] 2015-01-30 13:21
@izuzak I don't think I can answer that without knowing more about the internals of atom: if closing the window on closing the last tab would produce the effect of the "atom -w" process exiting, then absolutely feel free to close this as a dupe.

**Comment by izuzak** [comment] 2015-01-30 13:25
@alex :cool:

> if closing the window on closing the last tab would produce the effect of the "atom -w" process exiting, then absolutely feel free to close this as a dupe.

You can double-check that using [a package](https://atom.io/packages/the-closer).

**Closed by izuzak** 2015-01-30 13:25 UTC

**Comment by alex** [comment] 2015-01-30 13:26
@izuzak thanks!
