### ISSUE TITLE
Syntax highlighting bug found with HTML Comments.

### ISSUE THREAD

**Issue by philipgiuliani** [atom/atom#3639] opened 2014-09-26 10:50 UTC
I found a reproduceable bug with the Syntax Highlighting. The language i used was HTML+ERB. Haven't tested it yet in other languages.

![bug](https://cloud.githubusercontent.com/assets/5446019/4419401/5e9d43e4-456a-11e4-90d3-dcae6e13d910.gif)

How you can see the commented part losses the "comment style" when i write the first `</div>` in the wrong indent after a copy & paste.

If  i delete the comment beginning `<!--` and write it again, it colors the comment again as expected.

**Information**
Atom Version: 0.131.0
Reproduceable with `--safe`: Yes
OS: OS X 10.9

**Comment by mnquintana** [comment] 2016-03-30 00:22
I can't reproduce this in Atom 1.6.0 – closing this out. Feel free to comment if you run into this again with the latest version of Atom. :smile:

**Closed by mnquintana** 2016-03-30 00:22 UTC
Labels: bug
