### ISSUE TITLE
Do not open an "untitled" editor at startup

### ISSUE THREAD

**Issue by jorangreef** [atom/atom#5835] opened 2015-03-04 11:32 UTC
Atom should not open an "untitled" editor at startup.

It should either start with no open editors, or else start with the last open editor (especially where the last open editor was a folder).

Otherwise, if it starts with an "untitled" editor, one needs to first press CMD+Shift+W and then CMD+O to get where one wants.

**Comment by jorangreef** [comment] 2015-03-04 11:33
Or perhaps, it could open an "untitled" editor the very first time the program is run, but not thereafter.

**Comment by andreasbroch** [comment] 2015-03-04 12:59
Yes I agree. When opening a folder there is no need for an untitled document, only when selecting new document or the first time Atom is run without specifying a file to open i.e. from Finder (mac)

**Comment by 50Wliu** [comment] 2015-03-04 13:00
Duplicate of #5820 and #4573.

**Closed by 50Wliu** 2015-03-04 13:00 UTC
