### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by tqsoft** [atom/atom#20772] opened 2020-05-21 08:25 UTC
[Enter steps to reproduce:]

1. while downloading files from ftp using remote-ftp plugin
2.  every type on the keyboard rasise error

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:160

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778162)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778264)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2778390)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1081110)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1253631)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1251616)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284744)
```

### Commands

```
     -3:25.3.0 remote-ftp:download-selected (li.directory.entry.list-nested-item.collapsed.selected)
     -0:46 find-and-replace:show (input.hidden-input)
     -0:45.2.0 editor:consolidate-selections (input.hidden-input)
     -0:42.7.0 core:copy (input.hidden-input)
     -0:39.7.0 find-and-replace:show (input.hidden-input)
     -0:29.4.0 editor:consolidate-selections (input.hidden-input)
     -0:11.5.0 core:paste (button.btn)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
autoclose-html 0.23.0 
autoclose-html-plus 0.27.2 
autocomplete-html-entities 0.2.0 
busy-signal 2.0.1 
docksend 1.3.0 
git-plus 8.7.1 
html-tag-auto-complete 0.1.1 
hyperclick-php 0.3.0 
ide-html 0.6.0 
ide-php 0.7.18 
intentions 1.1.5 
linter 2.3.1 
linter-php 1.6.1 
linter-ui-default 1.8.1 
php-cs-fixer 4.1.1 
php-debug 0.3.5 
remote-ftp 2.2.4 
transmit 1.5.0 
```

**Comment by nelsonic** [comment] 2020-05-21 09:09
Seeing the same error while attempting to edit a Markdown doc.

Using Latest Atom:
![image](https://user-images.githubusercontent.com/194400/82543042-e4fea400-9b4a-11ea-9c16-38dc55f214bf.png)

This was working fine yesterday. Today it's unusable. 😞

**Comment by sadick254** [comment] 2020-09-01 16:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-01 16:16 UTC
