### ISSUE TITLE
Atom freezes & crashes when opening minified files. [macOS Sierra]

### ISSUE THREAD

**Issue by ryanlloydfrench** [atom/atom#13900] opened 2017-02-28 22:48 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[When opening a minified css or js file in the Atom editor, Atom freezes then crashes.]

### Steps to Reproduce

1. [Open Atom]
2. [Open large example.min.js or example.min.css]
3. [App freezes]

**Expected behavior:** [Expect the app not to choke]

**Actual behavior:** [App freezes and hangs]

**Reproduces how often:** [Every time I open a minified file. (100%)]

### Versions

Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

OS: MacOs 10.12.3

Installed Atom Packages:
atom-beautify
color-picker
editorconfig
file-icons
file-types
git-blame
git-time-machine
language-freemarker
linter-eslint
linter-scss-lint
merge-conflicts
pigments
project-manager
sync-settings
linter

**Comment by rsese** [comment] 2017-02-28 22:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/979. You may want to subscribe there for updates but it looks like it should be resolved in 1.16.0 or as of the 1.15.0-beta3.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-02-28 22:54 UTC
