### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received ~

### ISSUE THREAD

**Issue by saifazmi** [atom/atom#14288] opened 2017-04-24 20:04 UTC
[Enter steps to reproduce:]

1. Go to: File > Add Project Folder
2. Select a project folder
3. Click on Open

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Object.tildify (/app.asar/node_modules/fs-plus/lib/fs-plus.js:64:39)
    at Workspace.updateWindowTitle (/app.asar/src/workspace.js:259:24)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/app.asar/src/project.js:288:29)
    at /app.asar/src/atom-environment.js:1028:40
    at /app.asar/src/application-delegate.js:31:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -1:02.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.seti-roboto.seti-animate.theme-seti-syntax.theme-seti-ui)
     -0:07.0 application:add-project-folder (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autoprefixer 3.6.1 
busy-signal 1.4.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.3 
git-plus 7.6.0 
git-time-machine 1.5.9 
goto-definition 1.3.3 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.4 
linter-alex 4.0.0 
linter-csslint 1.3.4 
linter-eslint 8.1.6 
linter-htmlhint 1.3.3 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-sass-lint 1.7.4 
linter-shellcheck 1.4.4 
linter-ui-default 1.2.3 
linter-write-good 0.9.0 
linter-xmllint 1.4.1 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
open-recent 5.0.0 
pigments 0.39.1 
project-manager 3.3.4 
remote-edit 1.9.0 
rest-client 1.3.1 
restart-atom 0.2.0 
seti-syntax 1.1.3 
seti-ui 1.7.0 
todo-show 1.11.0 
```

**Comment by rsese** [comment] 2017-04-24 21:05
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14228 based on the stack trace.  I'm going to go ahead and close this but can you confirm in https://github.com/atom/atom/issues/14228  if the error is reproducible for you and if so, is it reproducible in safe mode (` atom --safe`)?

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-24 21:05 UTC
