### ISSUE TITLE
the editor crashes shortly after startup

### ISSUE THREAD

**Issue by coderobe** [atom/atom#11549] opened 2016-04-20 21:38 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When opening atom, the editor freezes and then crashes within the first minute.  
This issue was not occurring on atom v. `1.6.2`. I confirmed this on my machine by downgrading the package to said version, the issue didn't reoccur.

### Steps to Reproduce

1. Start atom. Whether you're using `--safe` or not does not matter.
2. The editor will now crash. See the screenshot below for more details.

**Expected behavior:**

The editor should function normally

**Actual behavior:**

The editor crashes
![screenshot from 2016-04-20 23-25-42](https://cloud.githubusercontent.com/assets/8442384/14691040/653caa7a-074f-11e6-9a9a-2d1b622d1bb4.png)

### Versions

I have tested the following versions of atom on `Arch Linux x86_64`, all of which seem to have the same issue: 

* atom 1.7.1  
* atom 1.9.0-dev-9ff5fb2 (built from source)  

### Additional information

`~/.atom/nohup.out` contains `Failed to get crash dump id.`

### Related Issues

https://github.com/atom/atom/issues/11519#issuecomment-212033766  
https://github.com/atom/atom/issues/11519#issuecomment-212456837

**Comment by 50Wliu** [comment] 2016-04-20 21:56
This is a duplicate of #11198 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-20 21:56 UTC

**Comment by coderobe** [comment] 2016-04-20 22:05
This is not the same issue. I'm not getting a segmentation fault in my case.

**Comment by 50Wliu** [comment] 2016-04-20 22:20
Not all reports included a segmentation fault.  To verify that this crash is not in fact #11198, would you mind building #11348 and see if you still experience crashes?

**Comment by coderobe** [comment] 2016-04-21 13:23
building https://github.com/atom/atom/pull/11348 fixes this issue
