### ISSUE TITLE
[Debian] Atom is not minimizing.

### ISSUE THREAD

**Issue by johnnyjohnjoe** [atom/atom#11766] opened 2016-05-16 09:25 UTC
### Description

I installed Atom (newest version) on Debian 8. My Problem is that whenever i wanna minimize the window only the top bar goes away but the rest of the editor stays in foreground.
Tried it also on another computer with Debian 8...no problem. Maybe it's because of the low resolution, 1376 x 700 something like that.
What can I do?

**Comment by marc-bertola** [comment] 2016-05-17 15:03
I saw the same behavior yesterday. Happens systematically for me. It was working last week.

I can resize the image, but once atom is started, the window content stays on top - no way to remove it. 

System: CentOS 7 on a VirtualBox VM

Community packages installed:
Sublime-Style-Column-Selection, build-cargo, hex, language-rust, linter, linter-rust, script, xml-formatter.

77 core packages installed as well -- is there any way to get a text list?
Please let me know if you need any additional info. 

![atomafterminimize](https://cloud.githubusercontent.com/assets/5149167/15327282/e83ee56c-1c1e-11e6-82f3-1b2bcce15497.png)
![atombeforeminimize](https://cloud.githubusercontent.com/assets/5149167/15327283/e84190f0-1c1e-11e6-9ae2-b5d841ee7581.png)

**Comment by 50Wliu** [comment] 2016-05-17 20:04
@johnnyjohnjoe Are you using a VM as well?

**Comment by johnnyjohnjoe** [comment] 2016-05-17 21:59
@50Wliu Yes, I'm using a VM. But on another PC with the same Linux Distribution and VM it works without problems.

**Comment by 50Wliu** [comment] 2016-05-17 22:20
This seems like a duplicate of #11574, so closing in favor of that issue.

**Closed by 50Wliu** 2016-05-17 22:20 UTC
Labels: linux, more-information-needed, needs-reproduction
