### ISSUE TITLE
Uncaught Error: Não foi possível encontrar o módulo especificado./\?\~\AppData\Local\atom\app-1...

### ISSUE THREAD

**Issue by tobiascavich** [atom/atom#15905] opened 2017-10-16 18:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Não foi possível encontrar o módulo especificado.
\\?\C:\Users\gelad\AppData\Local\atom\app-1.21.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: Não foi possível encontrar o módulo especificado.
\\?\C:\Users\gelad\AppData\Local\atom\app-1.21.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:32.4.0 snippets:next-tab-stop (input.hidden-input)
     -0:32.4.0 snippets:expand (input.hidden-input)
     -0:32.4.0 editor:indent (input.hidden-input)
     -0:31 editor:newline (input.hidden-input)
  2x -0:02.4.0 core:move-left (input.hidden-input)
  2x -0:00.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.7.3 
autocomplete-python 1.8.63 
```

**Comment by rsese** [comment] 2017-10-16 20:09
I think this might be a duplicate of recent issues like https://github.com/atom/atom/issues/15722.  If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled.  If you don't have any anti-virus software, let me know.

**Closed by rsese** 2017-10-16 20:09 UTC
