### ISSUE TITLE
Atom TreeView ignores files with a negated rule for them in .gitignore

### ISSUE THREAD

**Issue by sleepingevil** [atom/atom#16269] opened 2017-11-24 15:49 UTC
### Prerequisites

* [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

We started introducing TypeScript to our project and added `*.js` to .gitignore to ignore generated js files. Some of our tests are still written in JavaScript, so we added `![test_folder_name]/*.js` also. This works as expected in git, but Atom still ignores the js files in our test folders.

### Steps to Reproduce

```
$ mkdir gittest
$ cd gittest
$ git init
Initialized empty Git repository in /Users/algabor/Documents/0code/0playground/gittest/.git/
$ touch untracked.js
$ mkdir trackme
$ touch trackme/tracked.js
$ echo '*.js' >> .gitignore
$ git status --ignored
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.gitignore

Ignored files:
  (use "git add -f <file>..." to include in what will be committed)

	trackme/
	untracked.js

nothing added to commit but untracked files present (use "git add" to track)

$ echo '!trackme/*.js' >> .gitignore
$ git status --ignored
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.gitignore
	trackme/

Ignored files:
  (use "git add -f <file>..." to include in what will be committed)

	untracked.js

nothing added to commit but untracked files present (use "git add" to track)

$ atom .
```

**Expected behavior:** 

Atom should ignore `untracked.js` and should not ignore `trackme/tracked.js`.

**Actual behavior:** 

Atom ignores both `untracked.js` and `trackme/tracked.js`.

**Reproduces how often:** 

100%

### Versions

Atom: 1.22.1
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0
OS: macOS Sierra 10.12.6

<img width="300" alt="screen shot 2017-11-24 at 15 49 20" src="https://user-images.githubusercontent.com/9592130/33217243-fa8e63d4-d12e-11e7-8118-49ac16eb49bd.png">

**Comment by rsese** [comment] 2017-11-26 00:58
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/196. You may want to subscribe there for updates.  Also, for future issues it would be super helpful if you can fill out the issue template since it helps us triage issues.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-26 00:58 UTC
