### ISSUE TITLE
[OS X] File -> Open... menu command does nothing if there are no windows open

### ISSUE THREAD

**Issue by nicbarker** [atom/atom#13782] opened 2017-02-09 23:23 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Open Atom on Mac OS X
2. Close the blank window that atom creates on startup
3. Try using the File -> Open... command, nothing happens
4. Open a new blank window using File -> New Window
5. File -> Open... now correctly opens a file selection dialog.

**Expected behavior:** [What you expect to happen]
That File -> Open... would produce a file selection dialog when atom has no windows currently open but is still running.

**Actual behavior:** [What actually happens]
No dialog appears.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

```
atom --version
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```
```
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.10.1
```

### Additional Information
N/A

**Comment by 50Wliu** [comment] 2017-02-10 01:01
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-10 01:01 UTC

**Comment by nicbarker** [comment] 2017-02-10 01:02
Ah, my apologies - don't know how I didn't manage to find that open issue. Thanks!

**Comment by 50Wliu** [comment] 2017-02-10 01:05
No worries - it's sometimes hard to find issues given the 1,661 currently open ones 😀.
