### ISSUE TITLE
Atom Inputes on macOS are invisible

### ISSUE THREAD

**Issue by emps** [atom/atom#17246] opened 2018-04-30 11:04 UTC
Atom Inputes on macOS are invisible

on search input , create folder input etc...

cant see what im typing, you can see blank box , there is a typed value at least but hidden

latest macOS High Siera 10.13.4
latest atom 1.26.1

**Comment by rsese** [comment] 2018-04-30 21:05
Thanks for reaching out!  This sounds like it could be a duplicate of https://github.com/atom/atom/issues/17094?  Go ahead and try the suggestion in https://github.com/atom/atom/issues/17094#issuecomment-379344427 and if you still have trouble, please fill out the issue template and we can re-open and go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Closed by rsese** 2018-04-30 21:05 UTC
