### ISSUE TITLE
Saving files in a safer way

### ISSUE THREAD

**Issue by jiangyy** [atom/atom#10609] opened 2016-01-28 08:28 UTC
We have found that Atom is overwriting file using `fs.writeFileSync()` in both `TextBuffer::saveAs` and writing a configuration file. Note that `fs.writeFileSync()` opens a file with `O_TRUNC` flag. Imagine that there is a system crash in between, all data may be gone, leaving a blank file in the file-system. Our automated tool found this potential crash unsafety. This is particularly important when there is no backup file -- even if no backup file means less guarantee (the backup file treatment is correct).

The correct way to save a file: (1) write contents to a backup file; (2) rename the backup to the original file. The key is that (2) is ensured to be atomic by modern file-system implementations (like ext4). It is optional to add a fdatasync() between (1) and (2) in Linux, though I am not quite sure of behaviors under Windows.

Here are some discussions FYI: http://stackoverflow.com/questions/1812115/how-to-safely-write-to-a-file.

**Comment by lee-dohm** [comment] 2016-01-28 19:39
This is a duplicate of https://github.com/atom/atom/issues/3158. See the thread there for our investigations into and the inherent problems with atomic writes.

**Closed by lee-dohm** 2016-01-28 19:39 UTC
Labels: duplicate
