### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 249Error: Cannot cal...

### ISSUE THREAD

**Issue by HamoodFaridi** [atom/atom#19815] opened 2019-08-20 05:14 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 249
Error: Cannot call function 'getPosition' on missing remote object 249
    at throwRPCError (C:\Users\labuser\AppData\Local\atom\app-1.40.0\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\labuser\AppData\Local\atom\app-1.40.0\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\labuser\AppData\Local\atom\app-1.40.0\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At C:\Users\labuser\AppData\Local\atom\app-1.40.0\resources\electron.asar\renderer\api\remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 249
Error: Cannot call function 'getPosition' on missing remote object 249
    at throwRPCError (~/AppData/Local/atom/app-1.40.0/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.40.0/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.40.0/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (~/AppData/Local/atom/app-1.40.0/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (~/AppData/Local/atom/app-1.40.0/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (~/AppData/Local/atom/app-1.40.0/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.40.0/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:1:744557)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:1:744972)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.40.0/resources/app/static/<embedded>:11:285354)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-mysql-snippets 0.3.1 
autocomplete-python 1.14.1 
data-atom 0.29.1 
python-debugger 0.2.0 
script 3.18.1 
```

**Comment by HamoodFaridi** [comment] 2019-08-20 05:18
I am not sure why this error popped up. The code ran to completion as expected without any issue.
After 2-3 seconds, this error came up on the screen. 
Anyone who has an understanding of this kind of issue, please help.

**Comment by rsese** [comment] 2019-08-20 19:25
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

Can you reproduce the error or did you see it just one time?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-20 19:25 UTC

**Comment by HamoodFaridi** [comment] 2019-08-22 18:58
Thanks a lot for the response.

I checked this kind of error exists but the Error Code is different the one that I got.
So, I preferred to bring this to your attention.
As I faced this issue for the first time, I will update you in case I see the same error again.
