### ISSUE TITLE
Uncaught AssertionError: 9015 == 0

### ISSUE THREAD

**Issue by knockerclot0715** [atom/atom#17318] opened 2018-05-14 00:25 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError: 9015 == 0

```
At assert.js:81

AssertionError: 9015 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:160:14)
    at Object.onceWrapper (events.js:293:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:197:7)
    at Socket.socketOnData (_http_client.js:443:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-clock 0.1.16 
dash 1.7.1 
emmet 2.4.3 
file-icons 2.1.20 
ftp-remote-edit 0.12.12 
ide-php 0.7.14 
jshint 1.8.6 
minimap 4.29.8 
platformio-ide-terminal 2.8.1 
wakatime 7.0.4 
```

**Comment by rsese** [comment] 2018-05-14 17:14
Thanks for contributing!

This looks like a duplicate of https://github.com/atom/atom/issues/14074 so you can subscribe there for updates if you'd like.   If you have more information about what you were doing at the time of the error, please let us know in #14074.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-14 17:14 UTC
