### ISSUE TITLE
editor:delete-line is really slow

### ISSUE THREAD

**Issue by neilstuartcraig** [atom/atom#8706] opened 2015-09-07 21:14 UTC
Hi all

Firstly, thanks for everyone's on atom, it's awesome!

I have a minor bugbear with atom though, editor:delete-line is pretty slow (on both my MBP and MBA). I have tried it via `atom --safe` but it's barely any faster so I guess it's likely an issue with atom core rather than a plugin. It's so slow that I often hit another hotkey before the `editor:delete-line` is finished and end up with unintended consequences.

Is there any info I can provide to help in debugging? Anyone else finding the same issue?

Cheers
Neil

**Comment by izuzak** [comment] 2015-09-08 15:53
Hey @neilstuartcraig.

> Is there any info I can provide to help in debugging? Anyone else finding the same issue?

I haven't observed this myself. Does this happen regardless of file size? Can you share one file for which it happens, and point out the line which you deleted?

Also, can you try following [these instructions](https://atom.io/docs/latest/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler) and record a profile and post a screenshot + profile data as explained there? Thanks!

**Comment by neilstuartcraig** [comment] 2015-09-10 21:12
Hi and apologies for the slow reply.

Yes, it happens on any size files - I typically work on files from tens to a few hundred lines, so nothing huge, I can reproduce this on literally any file - e.g. my key bindings file (i added 4 bindings).

I get nothing from the CPU profiling (see attached).

Just wondering whether it's because I attached a keybinding (in fact 2) to "delete line":
```
...
'atom-text-editor:not([mini])':
  'ctrl-k': 'editor:delete-line'
  'cmd-k': 'editor:delete-line'
...
```
If i remove the keybindings for "delete-line" then it's fast! Adding just cmd-k keybinding back in and it's slow again. Now i tried amending my single keybinding from cmd-k to cmd-alt-k and it's fast...So it seems to be the cmd-k keybinding that's slow.

Having checked, cmd-k doesn't directly clash with any other key binding but there are some cmd-k "x" key bindings so i wonder if it's just atom waiting to see if i press another key after releasing cmd-k?

As a workaround, i guess i can change my keybinding but it's a shame to have to as i wanted to set them up as i've got used to with sublime (and i way prefer atom so i will keep using atom).

Cheers
Neil
<img width="1247" alt="screen shot 2015-09-10 at 22 03 43" src="https://cloud.githubusercontent.com/assets/320215/9801102/fd5d21dc-5808-11e5-8888-069368e1d2ee.png">
<img width="390" alt="screen shot 2015-09-10 at 22 03 55" src="https://cloud.githubusercontent.com/assets/320215/9801103/fd60c238-5808-11e5-9904-66afcea8ffda.png">

**Comment by izuzak** [comment] 2015-09-11 06:21
Thanks for investigating -- really appreciate it!

> Having checked, cmd-k doesn't directly clash with any other key binding but there are some cmd-k "x" key bindings so i wonder if it's just atom waiting to see if i press another key after releasing cmd-k?

That's exactly the problem -- see my comment [here](https://github.com/atom/atom/issues/6233#issuecomment-89779581). 

> As a workaround, i guess i can change my keybinding but it's a shame to have to as i wanted to set them up as i've got used to with sublime (and i way prefer atom so i will keep using atom).

Changing them so that there's no keybinding which is a prefix of another keybinding should fix this problem. 

I'm going to close this since this is working as intended, but let me know if this doesn't explain things.

**Closed by izuzak** 2015-09-11 06:21 UTC
Labels: needs-reproduction, performance

**Comment by neilstuartcraig** [comment] 2015-09-11 19:37
Yeah, that's fair :-). Thanks very much for your help.

Would be nice if there were some way around it other than having to use a different binding or maybe even a warning when you add the binding...at least people would know then.

Ta

**Comment by izuzak** [comment] 2015-09-15 11:27
> Would be nice if there were some way around it other than having to use a different binding or maybe even a warning when you add the binding...at least people would know then.

I agree -- I opened a new issue to track that idea: https://github.com/atom/atom/issues/8795. Thanks for mentioning it. :+1:

**Comment by neilstuartcraig** [comment] 2015-09-15 11:57
Cool, thanks Ivan
