### ISSUE TITLE
pathwatcher: duplicate handles

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#6943] opened 2015-05-25 17:42 UTC
This happened when I renamed `stylesheets` folder to `styles` and reloaded.

```
The handle(3) returned by watching /root/.atom/packages/git-diff-popup/styles is the same with an already watched path(/root/Dropbox/.atom/packages/git-diff-popup/styles)/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:70
 HandleWatcher.start/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:30
 HandleWatcher/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:120
 PathWatcher/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:179
 exports.watch/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:334
 module.exports.Directory.subscribeToNativeChangeEvents/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:95
 module.exports.Directory.willAddSubscription/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:3
 __bind/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/directory.js:89
 module.exports.Directory.onDidChange/usr/share/atom/resources/app.asar/node_modules/dev-live-reload/lib/watcher.js:50
 module.exports.Watcher.watchDirectory/usr/share/atom/resources/app.asar/node_modules/dev-live-reload/lib/package-watcher.js:46
 module.exports.PackageWatcher.watch/usr/share/atom/resources/app.asar/node_modules/dev-live-reload/lib/package-watcher.js:30
 PackageWatcher/usr/share/atom/resources/app.asar/node_modules/dev-live-reload/lib/ui-watcher.js:71
 module.exports.UIWatcher.createWatcher/usr/share/atom/resources/app.asar/node_modules/dev-live-reload/lib/ui-watcher.js:65
 module.exports.UIWatcher.watchPackage/usr/share/atom/resources/app.asar/node_modules/dev-live-reload/lib/ui-watcher.js:31
 module.exports.UIWatcher.watchPackages/usr/share/atom/resources/app.asar/node_modules/dev-live-reload/lib/ui-watcher.js:16
 UIWatcher/usr/share/atom/resources/app.asar/node_modules/dev-live-reload/lib/main.js:16
 (anonymous function)/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82
 module.exports.Emitter.emit/usr/share/atom/resources/app.asar/src/package-manager.js:402
 (anonymous function)/usr/share/atom/resources/app.asar/node_modules/q/q.js:794
 _fulfilled/usr/share/atom/resources/app.asar/node_modules/q/q.js:823
 Promise.then.Q.nextTick.self.promiseDispatch.done/usr/share/atom/resources/app.asar/node_modules/q/q.js:756
 promise.promiseDispatch/usr/share/atom/resources/app.asar/node_modules/q/q.js:564
 (anonymous function)/usr/share/atom/resources/app.asar/node_modules/q/q.js:110
 flushnode.js:357
 _tickCallback
```

atom 201
ubuntu 14.0.4
apm  0.168.0
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.1

**Comment by 50Wliu** [comment] 2015-05-25 19:14
@mark-hahn were you by any chance in dev mode?  If so this looks like a duplicate of atom/dev-live-reload#17.

**Closed** 2015-05-25 19:36 UTC
Labels: more-information-needed
