### ISSUE TITLE
option to always retain unsaved buffers no matter what

### ISSUE THREAD

**Issue by dwelle** [atom/atom#14389] opened 2017-05-11 08:56 UTC
__Problem:__

Currently, unsaved buffers (by that I mean new, unsaved, unnamed buffers with notes etc.) are somewhat loosely associated with atom project.

When you open a new project in a new window, the unsaved buffers are not opened/transferred to that window (whether it's a good thing is subjective). When you close that project (window), those unsaved buffers are (AFAIK) irreversibly lost.

I'm not sure how the unsaved buffers are retained between atom sessions, but if you happen to close the project as stated above, and then do `File → Reopen project`, the unsaved buffers created within that project __are not restored__.

I can't express how many times I've lost work due to atom not re-opening active project (even though it's been mostly fixed [there's so many related issues that I don't keep track] it happens to me every other week or so), thus losing unsaved buffers. I've since learned to keep my most important code-snippets-to-be-processed-later in a saved buffer, but I'm pretty lazy so I forget to do that all the time. And you know, it always happens that the atom loses state right when I put some important stuff in there :).

__Proposal:__

Either one would be fine:

- Add an option to always retain unsaved buffers no matter what, and don't associate them with a project
- Keep them associated with a project, but restore them when doing `File → Reopen project` (or when reopening project via other means)
- Keep easily accessible backup (plaintext) of the unsaved buffers that's not removed under any circumstances (unless either user manually closes that buffer, or saves it) -- or at least have some way to restore unsaved buffers that's not been reopened for some reason.

**Comment by lee-dohm** [comment] 2017-05-17 21:25
Thank you for your submission!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13318. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2017-05-17 21:25 UTC
Labels: duplicate
