### ISSUE TITLE
Atom shows the text (in menus and editor) with glitches

### ISSUE THREAD

**Issue by mdtrooper** [atom/atom#16398] opened 2017-12-17 03:13 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom shows the text (in menus and editor) with glitches. It remembers me when years ago in a old computers the graphics card broke.

### Steps to Reproduce

1. Open Atom.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
```
$ atom --version
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (buster)
Release:	testing
Codename:	buster

$ uname -a
Linux speccy-laptop 4.13.0-1-amd64 #1 SMP Debian 4.13.4-2 (2017-10-15) x86_64 GNU/Linux
```

### Additional Information

![pantallazo-2017-12-17 04-07-54](https://user-images.githubusercontent.com/1285451/34076236-858a5908-e2e0-11e7-9a00-9269cea49836.png)
![pantallazo-2017-12-17 04-08-06](https://user-images.githubusercontent.com/1285451/34076238-85b56fa8-e2e0-11e7-9275-4579a274d6c5.png)

**Comment by Ingramz** [comment] 2017-12-17 19:26
Does it happen every time you open Atom?

Does it happen when you run Atom using a different locale, eg by invoking `LC_ALL=C atom` or `LC_ALL=en_US.UTF-8 atom` from Terminal (make sure other Atom windows are closed before)?

**Comment by 50Wliu** [comment] 2017-12-17 21:31
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15737. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-12-17 21:31 UTC

**Comment by mdtrooper** [comment] 2017-12-18 00:19
Thanks @50Wliu . It is duplicate the bug.

```
$ dpkg -l | grep freetype
ii  libfreetype6:amd64                    2.8.1-0.1                         amd64        FreeType 2 font engine, shared library files
ii  libfreetype6:i386                     2.8.1-0.1                         i386         FreeType 2 font engine, shared library files
ii  libfreetype6-dev                      2.8.1-0.1                         amd64        FreeType 2 font engine, development files
```
Sorry, I should have searched better.

**Comment by 50Wliu** [comment] 2017-12-18 00:23
@mdtrooper No problem!  There are a lot of bugs and sometimes it's hard to use the correct search words :).
