### ISSUE TITLE
[Atom beta] — infinity restart nodemon when only set focus on watched tab on MacOS High Sierra

### ISSUE THREAD

**Issue by ruslankonev** [atom/atom#17037] opened 2018-03-27 08:33 UTC
I don't know why, but in last times I not can work in atom, because started nodemon always restart when cursor only set on some watched file. In other code editors this problem will not be reproduced.

![image](https://user-images.githubusercontent.com/2588730/37955666-e5badd32-31b1-11e8-99a3-2f809f65339e.png)

**Comment by Arcanemagus** [comment] 2018-03-27 16:19
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/10702. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-27 16:19 UTC
