### ISSUE TITLE
Uncaught Error: EACCES, open '/home/lloir/.atom/compile-cache/cson/5af7724b023a6274b520f79f04fb798a67319ca7.json'

### ISSUE THREAD

**Issue by Lloir** [atom/atom#5026] opened 2015-01-13 14:20 UTC
[Enter steps to reproduce below:]

1. Open atom
2. Grab popcorn

**Atom Version**: 0.169.0
**System**: linux 3.13.0-44-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES, open '/home/lloir/.atom/compile-cache/cson/5af7724b023a6274b520f79f04fb798a67319ca7.json'

```
At fs.js:75

Error: EACCES, open '/home/lloir/.atom/compile-cache/cson/5af7724b023a6274b520f79f04fb798a67319ca7.json'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  },
  "editor": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-01-13 17:34
I believe this is a duplicate of https://github.com/atom/atom/issues/4676

**Closed by kevinsawicki** 2015-01-13 17:34 UTC
