### ISSUE TITLE
when i change  the file name.all the opened file still use old name and auto create Dir. without any notice

### ISSUE THREAD

**Issue by hzmnet** [atom/atom#11121] opened 2016-03-10 07:15 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [ ] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

**Comment by lee-dohm** [comment] 2016-03-10 07:18
Can you give us a little more information? Maybe some steps to reproduce the problem? This sounds like something that is probably a duplicate of another Issue. I'd like to be sure though.

**Comment by damieng** [comment] 2016-04-22 21:54
No new information so closing. Please re-open if you have more information to share.

**Closed by damieng** 2016-04-22 21:54 UTC
Labels: more-information-needed
