### ISSUE TITLE
Opening XML Plists as "Old Style"

### ISSUE THREAD

**Issue by Redoubts** [atom/atom#11334] opened 2016-03-31 18:51 UTC
Using Atom 1.6 on OS X 10.11.

When I open my XML plist files, Atom correctly detects it's a plist, but it chooses "Old Style" instead of "XML" , so the syntax highlighting is wrong. I think it should probably default to XML if there is no detection beyond the file extension.

My plists start with 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
```
Like normal.

**Comment by Redoubts** [comment] 2016-03-31 18:56
Here's what it looks like: http://i.imgur.com/rsP2dr0.png

**Comment by 50Wliu** [comment] 2016-03-31 19:31
Hi @Redoubts, it looks like this is a duplicate of atom/language-property-list#5, so feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-31 19:31 UTC
