### ISSUE TITLE
Windows Alt Key Code Combinations for Special Characters Not Possible

### ISSUE THREAD

**Issue by thomashigginbotham** [atom/atom#7019] opened 2015-05-29 19:14 UTC
On Windows systems, you can hold the Alt key and type a number combination on the number pad to insert special characters. For example, I can insert an m-dash (—) by holding Alt and typing 0151.

This works fine in most text editors, including Sublime Text; however, in Atom, the Alt key + a number results in switching to a different tab.

**Comment by mnquintana** [comment] 2015-05-29 19:16
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/6788 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-29 19:16 UTC
