### ISSUE TITLE
Filename tooltip doesn't update after renaming file

### ISSUE THREAD

**Issue by samuela** [atom/atom#7663] opened 2015-07-02 21:09 UTC
I'm on Atom 1.0. To reproduce:

* Open a file in Atom. Scrolling over its tab will show a tooltip with its full path.
* Rename the file in tree view.
* Now, scrolling over the tab will still show the previous file path.

**Comment by mnquintana** [comment] 2015-07-02 21:16
Thanks for the report! This looks like a duplicate of https://github.com/atom/tabs/issues/189 – let's continue the discussion there.

(Also for future reference, Atom's tabs are provided by [atom/tabs](https://github.com/atom/tabs) rather than [atom/atom](https://github.com/atom/atom).)

**Closed by mnquintana** 2015-07-02 21:16 UTC
