### ISSUE TITLE
Pane split also splits file

### ISSUE THREAD

**Issue by halleycarleton** [atom/atom#4738] opened 2014-12-22 15:08 UTC
When splitting a pane you end up with the same file open in two panes. While splitting a file is a useful feature it should be separate from splitting panes. It is frustrating having to close the extra file view every time I split a pane.

I should be able to split panes without ending up with duplicate views of the same file, but I should also be able to split a file into multiple views if I want.

**Comment by tylerFowler** [comment] 2015-03-15 01:21
+1 

I find this pretty annoying. I always end up with a floating tab that I don't need (and usually forget about it until it creates too much clutter).

**Comment by acontreras89** [comment] 2015-06-19 10:54
:+1:

**Comment by austincrft** [comment] 2015-07-09 16:12
:+1:

**Comment by phaazon** [comment] 2015-07-14 11:05
:+1:

**Comment by elliotlarson** [comment] 2015-07-18 00:57
:+1: this would be a nice addition, I agree with @tylerFowler

**Comment by acontreras89** [comment] 2015-07-18 01:07
I'm working on this right now :)

**Comment by arxpoetica** [comment] 2015-10-30 18:51
Progress?

**Comment by T-Grave** [comment] 2015-12-20 00:37
:+1: 

I always close the tab after splitting it, so this would be an awesome feature!

**Comment by ramirezd42** [comment] 2016-01-07 18:17
Any progress on this? It's very annoying to have to close a file every time i open a pane

**Comment by justinko** [comment] 2016-02-04 12:02
:pray:

**Comment by acontreras89** [comment] 2016-02-04 12:14
This will be coming shortly. Sorry for the delay.
You can keep an eye on PR atom/pull/7953 for updates.

**Comment by 50Wliu** [comment] 2016-02-09 02:00
#7953 has been merged and the improvements should be available in Atom 1.6.0.  Thanks @acontreras89!

**Closed by 50Wliu** 2016-02-09 02:00 UTC
Labels: enhancement

**Comment by acontreras89** [comment] 2016-02-09 09:52
My pleasure, @50Wliu! Glad to see my PR finally merged :blush:

**Comment by Trudko** [comment] 2016-02-11 08:36
@acontreras89 thank you , you wonderful human being :D. It has bothered me for some time and I decide today , that I will look  for solution, so I am happy to see that 1.6 will include this.

**Comment by whomwah** [comment] 2016-03-03 11:35
@acontreras89 Great stuff on this one. Thank you!

**Comment by kehd07** [comment] 2017-11-17 11:58
Hello! This is already close, but I am also getting this issue on 1.22.1
What am I missing? Thanks!

**Comment by acontreras89** [comment] 2017-11-17 15:01
@kehd07 this is not a bug but a design decision. Others commands are available which implement different behaviors.

[This comment on the discuss forum](https://discuss.atom.io/t/how-to-replace-a-keymap-binding/16834/3) explains how to override a default keybinding.

I guess what you want is to add something like this to your `keymap.cson`:

```
'body':
  'ctrl-k down': 'pane:split-down-and-move-active-item'
  'ctrl-k left': 'pane:split-left-and-move-active-item'
  'ctrl-k right': 'pane:split-right-and-move-active-item'
  'ctrl-k up': 'pane:split-up-and-move-active-item'
```

**Comment by kehd07** [comment] 2017-11-21 12:07
Thanks for the reply @acontreras89 but this thread is not about keybinding, is about closing not ending up with the same file opened twice after spliting

**Comment by acontreras89** [comment] 2017-11-22 11:41
@kehd07 again, duplicating files on split was a design decision. This issue led to PR #7953, which extended the API to better fit all users' needs. However, default behavior was never changed.

**Comment by kehd07** [comment] 2017-11-23 10:05
Ok now I got you @acontreras89! Thank a lot, and also for the patience ;)
