### ISSUE TITLE
how to config when I open a reopen project in the current window as a different tab?

### ISSUE THREAD

**Issue by huberyh** [atom/atom#15543] opened 2017-09-05 09:39 UTC
I mean click 'File' -> 'reopen projects' -> [my project],
expected : [my project] be opened in current window as a different tab
actual: [my project] be opened in a new window.

Is there anything I need to set?

**Comment by 50Wliu** [comment] 2017-09-05 09:44
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #15542. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by 50Wliu** [comment] 2017-09-05 09:45
Please don't create duplicate issues.  Thanks! :smile:

**Closed by 50Wliu** 2017-09-05 09:44 UTC
