### ISSUE TITLE
Uncaught Error: ENOENT, open '/Users/Steve/sb/www/spec/workers/amazebot/inventory_report/update_total_listed_products_spec.rb'

### ISSUE THREAD

**Issue by SFEley** [atom/atom#5030] opened 2015-01-13 16:43 UTC
1. Was working in a Git branch where the file named above existed.
2. Did a `git checkout` to a branch where that file did not exist. 
3. The red error box popped up with a "Create issue" button, so here I am.

This may or may not be related to the quirk I've noticed where Atom will not only keep files open that were removed by a Git checkout, but will autosave them and create them again, making Git think it's a new untracked file.  Other editors I've used seem to do better at closing a file window if the file was removed by outside means.

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open '/Users/Steve/sb/www/spec/workers/amazebot/inventory_report/update_total_listed_products_spec.rb'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

Error: ENOENT, open '/Users/Steve/sb/www/spec/workers/amazebot/inventory_report/update_total_listed_products_spec.rb'
  at Error (native)

```

### Commands

```
     -4:41.6 fuzzy-finder:toggle-file-finder (input.hidden-input)
  9x -4:37.7 core:backspace (input.hidden-input)
     -4:34.5 core:confirm (input.hidden-input)
     -4:32.6 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -4:31.2 editor:consolidate-selections (input.hidden-input)
     -4:31.2 core:cancel (input.hidden-input)
     -2:55.2 command-palette:toggle (input.hidden-input)
     -2:53.5 core:confirm (input.hidden-input)
     -2:53.5 git-blame:toggle (input.hidden-input)
     -0:01.7 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:00.0 core:confirm (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-soda-dark-ui",
      "blackboard"
    ],
    "disabledPackages": [
      "wrap-guide"
    ],
    "destroyEmptyPanes": false
  },
  "editor": {
    "fontSize": 15,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
api-blueprint-preview, v0.2.2
atom-color-highlight, v2.0.14
atom-soda-dark-ui, v0.8.0
blackboard, v0.1.0
color-picker, v1.2.6
command-logger, v0.20.0
css-color-highlighting, v0.2.4
editor-stats, v0.16.0
enhanced-package-list, v0.6.3
file-icons, v1.4.3
git-blame, v0.3.2
git-tab-status, v1.3.0
highlight-selected, v0.7.0
jsonpp, v0.0.4
language-haml, v0.14.0
language-slim, v0.3.0
linter, v0.9.0
linter-js-yaml, v0.1.3
linter-jscs, v1.4.9
linter-jshint, v0.1.0
linter-rubocop, v0.2.1
linter-tidy, v0.0.1
minimap, v3.4.9
minimap-color-highlight, v3.0.3
minimap-find-and-replace, v3.0.4
minimap-highlight-selected, v3.0.0
project-ring, v0.18.2
rspec-snippets, v0.4.0
ruby-slim, v0.2.0
ruby-strftime-reference, v0.2.0
sassbeautify, v0.2.0
ssh-config, v0.10.0

# Dev
No dev packages
```

**Comment by benogle** [comment] 2015-01-13 17:08
Does this happen every time you switch branches in this situation? If so, can you try it in safe mode? Quit atom completely and run `atom --safe` from the command line. 

I am unable to reproduce this, so wondering if it's a package reading the file when it isnt there.

**Comment by benogle** [comment] 2015-01-14 20:25
Closing as a dupe of https://github.com/atom/atom/issues/4850

**Closed by benogle** 2015-01-14 20:25 UTC
Labels: more-information-needed
