### ISSUE TITLE
Uncaught Error: dlopen(/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/...

### ISSUE THREAD

**Issue by henryreeb** [atom/atom#19741] opened 2019-08-02 20:53 UTC
[Enter steps to reproduce:]

1. ...Opened Preferences, clicked on Packages in the sidebar.
2. ...Typed "GitHub" in search bar.

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:166

Error: dlopen(/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app/static/<embedded>:1:686763)
    at get_KeyboardLayoutManager (/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2698718)
    at get_manager (/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2698820)
    at Object.getCurrentKeyboardLayout (/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app/static/<embedded>:14:2698946)
    at e.keystrokeForKeyboardEvent (/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app/static/<embedded>:14:1086055)
    at KeymapManager.keystrokeForKeyboardEvent (/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1245252)
    at KeymapManager.handleKeyboardEvent (/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1243237)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/wt/pkcdlzmj1bd1d1ffxqfhfv180000gn/T/AppTranslocation/5DF855E0-C352-4880-A70A-E0F05585CC7C/d/Atom.app/Contents/Resources/app/static/<embedded>:11:283942)
```

### Commands

```
```

### Non-Core Packages

```
import 1.7.0 
```

**Comment by rsese** [comment] 2019-08-02 21:29
Thanks for the report!

We noticed that this looks like a duplicate of #14461 so you can subscribe there for updates if you'd like.   To get past the error, I'd recommend running through the [installation](https://flight-manual.atom.io/getting-started/sections/installing-atom/) again but if you still have trouble let me know.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-02 21:29 UTC
