### ISSUE TITLE
Atom Beta 1.10.beta1 : Indexing Project never completes.

### ISSUE THREAD

**Issue by rwatts3** [atom/atom#12313] opened 2016-08-03 18:21 UTC
Since the release this morning 08/03/2016 when trying to search files with `ctrl + p` Atom indexing never finishes and files are not found. Always says 0 and indexing project.
I believe this is related to the `fuzzy-finder` package.

**Comment by Ben3eeE** [comment] 2016-08-03 20:03
https://github.com/atom/fuzzy-finder/issues/205?

**Comment by 50Wliu** [comment] 2016-08-03 20:11
@rwatts3 If this is not a duplicate of atom/fuzzy-finder#205, please reopen this issue on the fuzzy-finder repo.  Thanks.

**Closed by 50Wliu** 2016-08-03 20:11 UTC

**Comment by rwatts3** [comment] 2016-08-03 20:30
I'm not sure that it is the same because I didn't notice this issue until I updated. 
I downgraded to beta0 and it wen't away. 

Very similar symptoms but something in beta1 is causing it to happen.

**Comment by Ben3eeE** [comment] 2016-08-03 21:05
Can confirm that this is happening to me in beta1 on windows 10. @rwatts3 please open a new issue in the [fuzzy finder repo](https://github.com/atom/fuzzy-finder/issues/new)

**Comment by rwatts3** [comment] 2016-08-03 21:14
will do
