### ISSUE TITLE
Atom every time opens new untitled-Atom window on startup.

### ISSUE THREAD

**Issue by gautamkvashisht** [atom/atom#17372] opened 2018-05-20 13:32 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom opening new untitled-Atom window on startup.

### Steps to Reproduce

1. Whenever I open Atom editor, I get new untitled-Atom window. 

2. Even if I Add a new Project, the next time I open Atom, instead of getting that project on which I was working, I again get this untitled-Atom window.

**Expected behavior:** I expect atom to open the project I am working on.

**Actual behavior:** I get new untitled-Atom window.

**Reproduces how often:** Every time I open Atom editor 

### Versions

Atom    : 1.27.0
Electron: 1.7.11
apm  1.19.0
OS : Kali Linux 2016.2

### Additional Information

I wasn't getting this issue earlier. But now suddenly it has appeared. I unchecked `Open Empty Editor on Start` but when I reopen Atom, it remains checked. I have tried deleting `~/.atom/storage` and `~/.atom/compile-cache` directories. Also I had reinstalled Atom. But this issue has not been resolved.

**Comment by gautamkvashisht** [comment] 2018-05-21 10:51
Yes. I also think that it is a *feature* of Atom 1.27. But it is outrightly annoying.

**Comment by rsese** [comment] 2018-05-21 17:55
I'm unable to reproduce this after installing 1.27.1 using the official .deb from http://atom.io on Ubuntu 16.04.

Do you have `Restore Previous Windows on Start` set to `yes` or `always`?  

> Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/

Have you tried clearing saved state or temporarily resetting to factory defaults from the debugging guide?

**Comment by gautamkvashisht** [comment] 2018-05-21 19:37
`Restore previous Windows on Start` is set to `yes`. But even if I set it to `always`, I get the same untitled - Atom window.

**Comment by rsese** [comment] 2018-05-21 21:38
Can you reply to my other question?

> Have you tried clearing saved state or temporarily resetting to factory defaults from the debugging guide?

Also, based on this:

>  I unchecked Open Empty Editor on Start but when I reopen Atom, it remains checked. 

It seems like something else is going on that might be causing the behavior you're seeing.

Do you see any error in devtools console when you start Atom?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools

**Comment by gautamkvashisht** [comment] 2018-05-22 08:02
In devtools console, earlier I used to get **locale related error** : something like `en_IN locale not found`. But now after reinstalling Atom and starting Atom in Safe Mode, I am not getting untitled - Atom window. I think the issue has been resolved for now.

**Comment by gautamkvashisht** [comment] 2018-05-22 08:03
Thanks for your help :-)

**Comment by rapus95** [comment] 2018-05-22 09:56
For me this doesn't occur anymore aswell; version states 1.27.1 for me too. Thus i guess that 1.27.1 fixed the issue!

**Comment by rsese** [comment] 2018-05-22 19:47
Glad things are working for you both 🙌   I'll go ahead and close this out.

**Closed by rsese** 2018-05-22 19:47 UTC
Labels: more-information-needed
