### ISSUE TITLE
[Windows] Running atom from cmd.exe doesn't load passed file

### ISSUE THREAD

**Issue by themaninthesuitcase** [atom/atom#2879] opened 2014-07-09 14:30 UTC
Using version 0.113.0.

Using cmd.exe ran the following:
   
    C:\Users\cpearson\.atom>atom .gitignore

Expected:
atom to open with  C:\Users\cpearson\.atom\.gitignore opened and the file tree to show contents of C:\Users\cpearson\.atom.

Actual:
Atom opens with a new blank file .gitignore and file tree show contents of atom application directory.

![capture](https://cloud.githubusercontent.com/assets/196630/3525666/2cb5e922-0775-11e4-96b0-6e47b3919864.PNG)

**Comment by benogle** [comment] 2015-01-19 20:23
Is this still an issue for anyone?

**Comment by batjko** [comment] 2015-01-22 19:44
Can't reproduce this on v174, Win8.
Then again, I never could before.

**Comment by kevinsawicki** [comment] 2015-08-07 00:14
I believe this has been fixed now by the command line tools installed as part of the Windows installer, closing this out, please comment if you still see it happening on Atom 1.0.5+

**Closed by kevinsawicki** 2015-08-07 00:14 UTC
Labels: bug, windows
