### ISSUE TITLE
Hover text in tab bar is incorrect after "Save As"

### ISSUE THREAD

**Issue by roche-xx** [atom/atom#8563] opened 2015-08-28 23:22 UTC
After saving a file to a different name/location, the text that renders when users hover over the file tab references the legacy file.

Repro:
1) Create a file called "file1.txt"
2) Save the file
3) Save the file as "file2.txt", at this point, the tab and file path at the foot of the window show that you're looking at "file2.txt"
4) Hover over the tab at the top of the screen. The text that appears will reference the path to "file1.txt"

Note:
I found that this only happens when the file is in the directory structure reflected in the window. If you open a file outside of the designated directory and follow the steps above, the bug does not appear.

![2015-08-28 16_20_41-file2 txt - c__tmp - atom](https://cloud.githubusercontent.com/assets/306110/9558947/cf5f92e6-4da0-11e5-9c6a-42eb261dc6a1.png)

**Comment by thomasjo** [comment] 2015-08-29 07:34
This issue is a duplicate of https://github.com/atom/tabs/issues/189. Please subscribe there if you want updates on resolution, etc.

**Closed by thomasjo** 2015-08-29 07:34 UTC
Labels: needs-reproduction
