### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectWord' of undefined

### ISSUE THREAD

**Issue by aloncarmel** [atom/atom#6753] opened 2015-05-12 14:14 UTC
Atom Version: 0.198.0
System: Mac OS X 10.10.3
Thrown From: Atom Core

Stack Trace

```
Uncaught TypeError: Cannot read property 'selectWord' of undefined

At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:554

TypeError: Cannot read property 'selectWord' of undefined
  at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:554:41)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

Commands

Config
```
{
  "core": {
    "disabledPackages": [
      "devunityatom",
      "devunityx",
      "firepad"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {}
  }
}
```
Installed Packages
```
# User
devunity, v2.1.0

# Dev
No dev packages
```
![screen shot 2015-05-12 at 5 12 53 pm](https://cloud.githubusercontent.com/assets/912405/7589274/5922e7fc-f8ca-11e4-86c6-e5552fe5d7e6.png)

**Comment by 50Wliu** [comment] 2015-05-12 15:14
Hi @aloncarmel, what were you doing when this happened?  If you can reproduce this reliably, could you please try in safe mode (`atom --safe`)?  Thanks.

**Comment by aloncarmel** [comment] 2015-05-31 11:32
i focused in and out of the editor to chrome and back. back and forth until the cursor suddenly disappeared and this error appeared.

**Comment by izuzak** [comment] 2015-09-10 18:25
I believe this is a variant of https://github.com/atom/atom/issues/5311, so closing this for the reasons listed in https://github.com/atom/atom/issues/5311#issuecomment-139003051. Also checked bugsnag and didn't notice any exceptions from recent versions.

If anyone runs into this again -- please let us know.

**Closed by izuzak** 2015-09-10 18:25 UTC
Labels: more-information-needed, uncaught-exception
