### ISSUE TITLE
Atom began copying empty lines

### ISSUE THREAD

**Issue by vlad1777d** [atom/atom#16344] opened 2017-12-08 00:41 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom began copying empty lines. 
It's especially annoying when you cut something (ctrl + x), than instead of ctrl + v pressed ctrl + c.
Earlier all was normal.

### Steps to Reproduce

1. Place caret on empty line and press ctrl + c
2. Select some other line and press ctrl + v.

**Expected behavior:** 
As it was earlier. It would do nothing if you press ctrl + c on empty line (when nothing is selected) and keep in buffer previous value (if it was present).

**Actual behavior:**
When you press ctrl + c on empty line (nothing is selected), it copies that empty line and replaces current text in buffer.

**Reproduces how often:** always

### Versions

OS: Linux Mint 18.3 x64 Cinnamon

atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

### Additional Information

absent

**Comment by rsese** [comment] 2017-12-08 04:27
Thanks for taking the time to contribute!  This was discussed in https://github.com/atom/atom/issues/7103, see the comment here for how to workaround this issue:

https://github.com/atom/atom/issues/7103#issuecomment-345662385

---

We noticed that this is a duplicate of https://github.com/atom/atom/issues/7103. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-08 04:27 UTC

**Comment by vlad1777d** [comment] 2017-12-08 21:44
@rsese , thank you.
