### ISSUE TITLE
White flashes on editor after upgrade

### ISSUE THREAD

**Issue by burabure** [atom/atom#15648] opened 2017-09-14 03:56 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Experiencing frequent white flashes after upgrading atom from 1.18.0 -> 1.19.0+; see gif

![untitled 1](https://user-images.githubusercontent.com/3132298/30411480-82e18d0e-98e7-11e7-9a6e-51d4815faa51.gif)

Reading the changelog on 1.19.0 it seems like the rendering rewrite/electron update might have caused this

### Steps to Reproduce

it doesn't happen all the time, but scrolling, changing tabs, moving mouse out of the window and back in, hovering on tabs and such trigger this issue

**Expected behavior:** it shouldn't flash

**Actual behavior:**  it flashes

**Reproduces how often:** about 40% of the time i'm using the editor

### Versions

```
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by rsese** [comment] 2017-09-14 18:03
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15323. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-14 18:03 UTC

**Comment by DamienGong** [comment] 2017-11-14 02:07
I got this issue as well just after an upgrade to latest stable. 
I noticed only if I created dual atom windows, then the 2nd window blinks. The original window is free from it.
Maybe a clue for fixing.
