### ISSUE TITLE
Atom fails to build on ARM Linux 32bit

### ISSUE THREAD

**Issue by cnshenyi** [atom/atom#10742] opened 2016-02-09 11:32 UTC
I tried to build it on a arm chromebook asus c201, it's a armv7 platform. I run crouton ,it's runing the ubuntu 14.04 . but i got a error for building apm:
`download not found: http://nodejs.org/dist/v0.10.40/node-v0.10.40-linux-arm.tar.gz
npm ERR! Linux 3.14.0
npm ERR! argv "/usr/bin/nodejs" "/home/matrix/Downloads/atom/build/node_modules/.bin/npm" "--userconfig=/home/matrix/Downloads/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v5.5.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.6.0 install: `node ./script/download-node.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.6.0 install script 'node ./script/download-node.js'.
npm ERR! This is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-node.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matrix/Downloads/atom/apm/npm-debug.log`

My node is v5.5.0, npm is v3.7.1 .

**Comment by cnshenyi** [comment] 2016-02-09 11:44
the npm-debug.log:
`24046 verbose stack Error: atom-package-manager@1.6.0 install: `node ./script/download-node.js`
24046 verbose stack Exit status 1
24046 verbose stack     at EventEmitter.<anonymous> (/home/matrix/Downloads/atom/build/node_modules/npm/lib/utils/lifecycle.js:214:16)
24046 verbose stack     at emitTwo (events.js:100:13)
24046 verbose stack     at EventEmitter.emit (events.js:185:7)
24046 verbose stack     at ChildProcess.<anonymous> (/home/matrix/Downloads/atom/build/node_modules/npm/lib/utils/spawn.js:24:14)
24046 verbose stack     at emitTwo (events.js:100:13)
24046 verbose stack     at ChildProcess.emit (events.js:185:7)
24046 verbose stack     at maybeClose (internal/child_process.js:821:16)
24046 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
24047 verbose pkgid atom-package-manager@1.6.0
24048 verbose cwd /home/matrix/Downloads/atom/apm
24049 error Linux 3.14.0
24050 error argv "/usr/bin/nodejs" "/home/matrix/Downloads/atom/build/node_modules/.bin/npm" "--userconfig=/home/matrix/Downloads/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
24051 error node v5.5.0
24052 error npm  v2.13.3
24053 error code ELIFECYCLE
24054 error atom-package-manager@1.6.0 install: `node ./script/download-node.js`
24054 error Exit status 1
24055 error Failed at the atom-package-manager@1.6.0 install script 'node ./script/download-node.js'.
24055 error This is most likely a problem with the atom-package-manager package,
24055 error not with npm itself.
24055 error Tell the author that this fails on your system:
24055 error     node ./script/download-node.js
24055 error You can get their info via:
24055 error     npm owner ls atom-package-manager
24055 error There is likely additional logging output above.
24056 verbose exit [ 1, true ]
24057 verbose unbuild node_modules/atom-package-manager
24058 info preuninstall atom-package-manager@1.6.0
24059 info uninstall atom-package-manager@1.6.0
24060 verbose unbuild rmStuff atom-package-manager@1.6.0 from /home/matrix/Downloads/atom/apm/node_modules
24061 silly gentlyRm /home/matrix/Downloads/atom/apm/node_modules/.bin/apm is being gently removed
24062 silly gentlyRm verifying /home/matrix/Downloads/atom/apm is an npm working directory
24063 silly gentlyRm containing path /home/matrix/Downloads/atom/apm is under npm's control, in /home/matrix/Downloads/atom/apm
24064 silly gentlyRm deletion target /home/matrix/Downloads/atom/apm/node_modules/.bin/apm is under /home/matrix/Downloads/atom/apm
24065 verbose gentlyRm vacuuming from /home/matrix/Downloads/atom/apm/node_modules/.bin/apm up to /home/matrix/Downloads/atom/apm
24066 silly vacuum-fs removing /home/matrix/Downloads/atom/apm/node_modules/.bin/apm
24067 silly vacuum-fs removing /home/matrix/Downloads/atom/apm/node_modules/.bin
24068 silly vacuum-fs quitting because other entries in /home/matrix/Downloads/atom/apm/node_modules
24069 info postuninstall atom-package-manager@1.6.0
24070 silly gentlyRm /home/matrix/Downloads/atom/apm/node_modules/atom-package-manager is being purged from base /home/matrix/Downloads/atom/apm
24071 verbose gentlyRm don't care about contents; nuking /home/matrix/Downloads/atom/apm/node_modules/atom-package-manager
24072 silly vacuum-fs purging /home/matrix/Downloads/atom/apm/node_modules/atom-package-manager
24073 silly vacuum-fs removing /home/matrix/Downloads/atom/apm/node_modules
24074 silly vacuum-fs finished vacuuming up to /home/matrix/Downloads/atom/apm
`

**Comment by cnshenyi** [comment] 2016-02-09 11:45
24046 verbose stack Error: atom-package-manager@1.6.0 install: `node ./script/download-node.js`
24046 verbose stack Exit status 1
24046 verbose stack     at EventEmitter.<anonymous> (/home/matrix/Downloads/atom/build/node_modules/npm/lib/utils/lifecycle.js:214:16)
24046 verbose stack     at emitTwo (events.js:100:13)
24046 verbose stack     at EventEmitter.emit (events.js:185:7)
24046 verbose stack     at ChildProcess.<anonymous> (/home/matrix/Downloads/atom/build/node_modules/npm/lib/utils/spawn.js:24:14)
24046 verbose stack     at emitTwo (events.js:100:13)
24046 verbose stack     at ChildProcess.emit (events.js:185:7)
24046 verbose stack     at maybeClose (internal/child_process.js:821:16)
24046 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
24047 verbose pkgid atom-package-manager@1.6.0
24048 verbose cwd /home/matrix/Downloads/atom/apm
24049 error Linux 3.14.0
24050 error argv "/usr/bin/nodejs" "/home/matrix/Downloads/atom/build/node_modules/.bin/npm" "--userconfig=/home/matrix/Downloads/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
24051 error node v5.5.0
24052 error npm  v2.13.3
24053 error code ELIFECYCLE
24054 error atom-package-manager@1.6.0 install: `node ./script/download-node.js`
24054 error Exit status 1
24055 error Failed at the atom-package-manager@1.6.0 install script 'node ./script/download-node.js'.
24055 error This is most likely a problem with the atom-package-manager package,
24055 error not with npm itself.
24055 error Tell the author that this fails on your system:
24055 error     node ./script/download-node.js
24055 error You can get their info via:
24055 error     npm owner ls atom-package-manager
24055 error There is likely additional logging output above.
24056 verbose exit [ 1, true ]
24057 verbose unbuild node_modules/atom-package-manager
24058 info preuninstall atom-package-manager@1.6.0
24059 info uninstall atom-package-manager@1.6.0
24060 verbose unbuild rmStuff atom-package-manager@1.6.0 from /home/matrix/Downloads/atom/apm/node_modules
24061 silly gentlyRm /home/matrix/Downloads/atom/apm/node_modules/.bin/apm is being gently removed
24062 silly gentlyRm verifying /home/matrix/Downloads/atom/apm is an npm working directory
24063 silly gentlyRm containing path /home/matrix/Downloads/atom/apm is under npm's control, in /home/matrix/Downloads/atom/apm
24064 silly gentlyRm deletion target /home/matrix/Downloads/atom/apm/node_modules/.bin/apm is under /home/matrix/Downloads/atom/apm
24065 verbose gentlyRm vacuuming from /home/matrix/Downloads/atom/apm/node_modules/.bin/apm up to /home/matrix/Downloads/atom/apm
24066 silly vacuum-fs removing /home/matrix/Downloads/atom/apm/node_modules/.bin/apm
24067 silly vacuum-fs removing /home/matrix/Downloads/atom/apm/node_modules/.bin
24068 silly vacuum-fs quitting because other entries in /home/matrix/Downloads/atom/apm/node_modules
24069 info postuninstall atom-package-manager@1.6.0
24070 silly gentlyRm /home/matrix/Downloads/atom/apm/node_modules/atom-package-manager is being purged from base /home/matrix/Downloads/atom/apm
24071 verbose gentlyRm don't care about contents; nuking /home/matrix/Downloads/atom/apm/node_modules/atom-package-manager
24072 silly vacuum-fs purging /home/matrix/Downloads/atom/apm/node_modules/atom-package-manager
24073 silly vacuum-fs removing /home/matrix/Downloads/atom/apm/node_modules
24074 silly vacuum-fs finished vacuuming up to /home/matrix/Downloads/atom/apm

**Comment by craigotis** [comment] 2016-03-09 13:48
+1 I'm seeing the exact same thing. I already have Node installed, I wonder if there's a way to tell it *not* to go grab a different version?

**Comment by lee-dohm** [comment] 2016-03-14 21:26
We discussed this and we do want to fully support ARM builds in the future, so we're going to leave this open. We don't know when that would be though, so we encourage members of the community to give feedback and collaborate on solving this problem.

**Comment by nonnymoose** [comment] 2016-06-11 14:59
I have the exact same problem. I'm glad there is an already mature bug report.
I think that this happens because, as you can see [here](http://nodejs.org/dist/v0.10.40/), node 0.10.40 simply isn't available for ARM.
All we have to do is compile node 0.10.40 for ARM and then change that download location to wherever the tarball is.
However, this is easier said than done. script/download-node.js does not exist. I think it is auto-generated during the build process, but I cannot find where. 
@lee-dohm Do you know what script generates download-node.js? If I can change that download url I should be able to fix this.

**Comment by 50Wliu** [comment] 2016-06-11 15:23
@nonnymoose I would suggest trying to build this PR instead: #11897.

**Comment by nonnymoose** [comment] 2016-06-13 16:37
@50Wliu Thank you. Your changes to bootstrap should now use the current version of node.

**Comment by nonnymoose** [comment] 2016-06-14 13:31
@50Wliu I tried that, and I had absolutely no problem with `download-node`! Then my Raspberry Pi ran out of memory. :(

**Comment by nonnymoose** [comment] 2016-06-15 13:46
Okay, so @50Wliu I got past "Installing apm"!
Now I have this error, which seems related, since it still failed to download node:
```
Node: v4.2.6
npm: v3.9.5
Installing build modules...
=> Took 44107ms.

Installing apm...
=> Took 23678ms.

/usr/local/src/atom/apm/node_modules/atom-package-manager/bin/apm: line 35: /usr/local/src/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory
```
My question is:
Why is it downloading (and failing at it) node? I already have node.

**Comment by NicoHood** [comment] 2016-06-21 14:18
I also would want to see ARM builds, but isnt this a duplicate of this:
https://github.com/atom/atom/issues/7822

We have a lot more information there.
It would be nice if @gjtorikian could give us an update about the arm builds and noone of us was able to reproduce a working build. Now that a few more patches were merged it might not be much to get atom finally running on arm.

**Comment by 50Wliu** [comment] 2016-06-21 15:27
Ok, closing in favor of #7822.

**Closed by 50Wliu** 2016-06-21 15:27 UTC
Labels: build-error, help-wanted, linux
