### ISSUE TITLE
Atom crashes when loading large binary file

### ISSUE THREAD

**Issue by axelw** [atom/atom#11110] opened 2016-03-09 09:12 UTC
### Description

Atom crashes when loading large binary file

### Steps to Reproduce

1. Install Oracle Database 12c Enterprise Edition for Windows 64
2. After installation, open [OraHome]\cfgtoollogs\dbca\\[dbname]\tempControl.ctl

**Expected behavior:**

Atom displays the content of the file.

**Actual behavior:** 

Atom crashes.

### Versions

Atom Version 1.5.4

[tempControl.zip](https://github.com/atom/atom/files/164777/tempControl.zip)

**Comment by echavezNS** [comment] 2016-03-10 00:44
I did open the file and Atom didn't crashed, I think is something wrong with your installation.

**Comment by Rantahu** [comment] 2016-03-10 00:48
I getting the same error when opening your file.

**Comment by ardhipoetra** [comment] 2016-03-10 14:13
I also can open that file. Sluggish, but it did open. Same version 1.5.4

**Comment by kuzyn** [comment] 2016-06-23 18:29
I'm either getting a complete slowdown or a crash (if there is a few tabs open) with binaries of a couple of MB. My question is why does Atom default to preview those files? It serves no purpose and gets it the way when you simply need to delete said files

**Comment by trusktr** [comment] 2016-06-28 17:50
It might depend on specs, or possibly on packages installed too. Tracking all these issues at #12065.

**Comment by mnquintana** [comment] 2016-06-29 00:41
This seems like a duplicate of https://github.com/atom/atom/issues/8864 – let's consolidate the discussion there.

**Closed by mnquintana** 2016-06-29 00:41 UTC

**Comment by krabbypattified** [comment] 2017-03-05 18:14
Hello from issue #12065. Atom Beta should fix this for many people.
