### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/j0/c_fq5brn6gqb_vr...

### ISSUE THREAD

**Issue by SmallPierce** [atom/atom#16913] opened 2018-03-09 10:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/private/var/folders/j0/c_fq5brn6gqb_vr92xgd8lx40000gn/T/AppTranslocation/04C331A2-EC06-45F1-8AD7-F3A9CD111CD8/d/Atom.app'

```
At fs.js:902

Error: ENOENT: no such file or directory, lstat '/private/var/folders/j0/c_fq5brn6gqb_vr92xgd8lx40000gn/T/AppTranslocation/04C331A2-EC06-45F1-8AD7-F3A9CD111CD8/d/Atom.app'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at realpathSync (fs.js:1542:21)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:331:24)
    at toRealPath (module.js:130:13)
    at Function.Module._findPath (module.js:178:22)
    at Module._resolveFilename (module.js:468:25)
    at Module._resolveFilename (/private/var/folders/j0/c_fq5brn6gqb_vr92xgd8lx40000gn/T/AppTranslocation/04C331A2-EC06-45F1-8AD7-F3A9CD111CD8/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/j0/c_fq5brn6gqb_vr92xgd8lx40000gn/T/AppTranslocation/04C331A2-EC06-45F1-8AD7-F3A9CD111CD8/d/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/private/var/folders/j0/c_fq5brn6gqb_vr92xgd8lx40000gn/T/AppTranslocation/04C331A2-EC06-45F1-8AD7-F3A9CD111CD8/d/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at get_CommandEvent (/private/var/folders/j0/c_fq5brn6gqb_vr92xgd8lx40000gn/T/AppTranslocation/04C331A2-EC06-45F1-8AD7-F3A9CD111CD8/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:22:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/j0/c_fq5brn6gqb_vr92xgd8lx40000gn/T/AppTranslocation/04C331A2-EC06-45F1-8AD7-F3A9CD111CD8/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:618:38)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/j0/c_fq5brn6gqb_vr92xgd8lx40000gn/T/AppTranslocation/04C331A2-EC06-45F1-8AD7-F3A9CD111CD8/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/j0/c_fq5brn6gqb_vr92xgd8lx40000gn/T/AppTranslocation/04C331A2-EC06-45F1-8AD7-F3A9CD111CD8/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
  7x -0:10.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-03-09 21:19
Thanks for contributing!

We noticed that this looks like a duplicate of #10774 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by rsese** 2018-03-09 21:19 UTC
