### ISSUE TITLE
Unicode not showing properly

### ISSUE THREAD

**Issue by ljbade** [atom/atom#4403] opened 2014-12-05 12:07 UTC
Just found this text rendering error in part of https://github.com/mapbox/mapbox-gl-native/blob/master/src/clipper/clipper.cpp#L4336-L4340

This is what it looks like, see all the ?
![screenshot from 2014-12-05 22 47 35](https://cloud.githubusercontent.com/assets/1215089/5315572/556d5d0e-7cd3-11e4-84b8-d1e53637237b.png)

It renders fine on github.com

I am on Ubuntu 14.04 x64 with Atom 0.152.0

**Comment by jasperblues** [comment] 2015-01-17 01:52
Not sure if this is a new issue or related: On OSX I'm seeing a square where I'm expecting Unicode. I've selected the Menlo font (same as Terminal is using). Terminal shows the expected Unicode character, Atom does not.

**Comment by marcopiraccini** [comment] 2015-04-17 07:03
I see squares in Ubuntu 14.10 also for: ✓
The very same (system) fonts shows correctly in console, gedit, etc. 
I tried that changing fonts between the ones availabe in the system...same behaviour.

**Comment by 50Wliu** [comment] 2015-04-17 14:00
Can this now be considered a duplicate of #6214?

**Comment by marcopiraccini** [comment] 2015-04-17 14:48
It seems so.

**Closed** 2015-04-17 14:53 UTC
