### ISSUE TITLE
No error message in logs or console when there's a dead socket in /tmp

### ISSUE THREAD

**Issue by sumdog** [atom/atom#12156] opened 2016-07-12 19:13 UTC
### Prerequisites

I'm currently running Atom 1.8.0 on Gentoo using the package that's on the default Gentoo portage tree. 

### Description

I had a situation where I'd run `atom` and I wouldn't get my editor. There was nothing in the `~/.atom/nohup.log`.  I repeatedly killed all my electron and atom processes. They'd show up in the `ps` list, just no editor window. 

I also attempted moving by `~/.atom` and `~/.config/Atom` out of the way. When I restarted atom, I'd only get the `nohup.log` indicating that atom has successfully started (App load time: xxxms). Per discussion on the #atom chatroom on Freenode, I tried starting it with `-l /tmp/mylog.log` (Atom didn't even create the log file) and then `atom -f` which generated no errors.

Finally, I noticed in `/tmp` I had an `atom-1.8.0-[my username].sock` after I had killed the processes. It was a dead socket. I removed it an atom started up fine. I killed it, replaced my old atom config and storage directories and it started right up.  

### Workaround

Delete the old, dead socket in `/tmp`. 

### Issue/Solution

I'm not an atom dev, so I'm not sure how the socket communication works, but I feel like there should be a means to check if the socket isn't connected to a running process and report an error if that's the case; or at least indicate something in the foreground logs. 

### Related

The only bug I could found that's related was the following:

https://github.com/atom/atom/issues/4346

I wasn't sure if I should just append to that one or open a new issue. Feel free to merge/duplicate mark this if maintainers feel it's appropriate. 

### Versions

```
$atom --version
Atom    : 1.8.0
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1

$apm --version
apm  1.9.2
npm  2.13.3
node 5.1.1
python 3.4.3
git 2.7.3
```

**Comment by lee-dohm** [comment] 2016-07-12 19:42
Yes, I would say that this is a duplicate of #4346. Thanks for the extra information. You may want to subscribe to that Issue for updates.

**Closed by lee-dohm** 2016-07-12 19:42 UTC
