### ISSUE TITLE
Keymap error for commands on spanish command layout

### ISSUE THREAD

**Issue by voylinux** [atom/atom#5154] opened 2015-01-20 09:05 UTC
Hi! I am using Atom on a Linux (Ubuntu) machine and I  have spanish (es-ES) layout on my keyboard.
When writting code everything is ok, but with commands, the Key Binding Resolver console is showing bas results.

I suspect it is showing what the key combination would be for an (EN) keyboard layout. For example if I press (SHIFT) - ,   it show < symbol. But this is not correct in a spanish keyboard, we have ; there. So looks that it is taking waht is is suposed to be in that key, not what the system is actually passing.

**Comment by 50Wliu** [comment] 2015-01-20 17:51
Duplicate of atom/atom-keymap#37.

**Closed by 50Wliu** 2015-01-20 17:51 UTC
