### ISSUE TITLE
Uncaught TypeError: Invalid Point: (115, NaN)

### ISSUE THREAD

**Issue by dacharyc** [atom/atom#19470] opened 2019-06-08 01:34 UTC
When working in a GitHub Markdown file in Atom:

1. Selected lines 100 through 102 of a 228 line file;
2. Copied the lines;
3. Hit Backspace to delete lines.

Boom, error. (Although the lines did successfully delete, and I was able to Undo the delete.)

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (115, NaN)

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Invalid Point: (115, NaN)
    at Function.t.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:44530)
    at DisplayLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:85636)
    at DisplayMarkerLayer.t.exports.DisplayMarkerLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1104283)
    at DisplayMarker.t.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3309224)
    at changePosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:522041)
    at Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:530585)
    at Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:522007)
    at Cursor.moveLeft (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:524829)
    at modifySelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:534641)
    at Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:547723)
    at Selection.selectLeft (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:534609)
    at Selection.backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:539133)
    at mutateSelectedText.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16061)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492065)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39529)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16037)
    at TextEditor.e.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:259297)
    at TextEditor.core:backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:302063)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:307804
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492065)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at HTMLElement.s.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:307747)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349922)
```

### Commands

```
     -4:03.4.0 core:paste (input.hidden-input)
     -4:00.8.0 editor:newline (input.hidden-input)
     -4:00.5.0 core:move-up (input.hidden-input)
  2x -3:21.3.0 core:backspace (input.hidden-input)
     -3:15 core:move-right (input.hidden-input)
  4x -3:13.1.0 core:backspace (input.hidden-input)
     -2:56.1.0 editor:newline (input.hidden-input)
  2x -2:45.3.0 core:move-down (input.hidden-input)
  5x -2:38 editor:newline (input.hidden-input)
     -2:14.1.0 core:move-right (input.hidden-input)
     -2:05.6.0 editor:newline (input.hidden-input)
     -2:00.4.0 core:move-right (input.hidden-input)
     -0:57 core:backspace (input.hidden-input)
     -0:41.4.0 core:copy (input.hidden-input)
  2x -0:37.4.0 core:backspace (input.hidden-input)
     -0:27.9.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
rest-client 1.3.1 
```

**Comment by rsese** [comment] 2019-06-10 21:27
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/19114 so you can subscribe there for updates if you'd like.  

With the same file you mentioned, can you reproduce the error?  If so, are you able to share the file with us?  Or can you reproduce with any other files?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-10 21:27 UTC
