### ISSUE TITLE
[PHP] Code coloration for multiline queries

### ISSUE THREAD

**Issue by Galaxias** [atom/atom#4425] opened 2014-12-06 17:27 UTC
Hi, 
When try to make a multiline database query, the syntax colouration is bad...
```php
            $newUser = $db->prepare("INSERT INTO users".
                "(id, realname, pseudo, email, pwd, isfirstvisit)".
                "VALUES (:id,:realname,:pseudo,:email,:pwd,1)");

```
(just like markdown :) )

**Comment by mnquintana** [comment] 2015-04-26 13:22
Duplicate of atom/language-php#52

**Closed by mnquintana** 2015-04-26 13:22 UTC
