### ISSUE TITLE
Braces in strings are not ignored when highlighting the corresponding open/close brace

### ISSUE THREAD

**Issue by maxgrass** [atom/atom#9912] opened 2015-12-02 16:09 UTC
Repro:
1. use code
```
function x(){
 console.log('        {(         ');
}
```

2. set cursor at "{" or "(" inside the string.

Expected:
no counterpart ("}" resp. ")") is highlighted.

Happens:
Next following "}" resp. ")" outside of the string is shown.

![2015-12-02 17_03_12-untitled - atom](https://cloud.githubusercontent.com/assets/169885/11536139/719aaff2-9917-11e5-919e-386b906096fa.png)

**Comment by 50Wliu** [comment] 2015-12-02 17:05
This is a duplicate of atom/bracket-matcher#78 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-02 17:05 UTC
