### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by CharlesPs** [atom/atom#6856] opened 2015-05-19 15:35 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\app.asar\src\window-event-handler.js:149:33)
    at HTMLDocument.handler (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\CarlosAndres\AppData\Local\Atom\app-0.199.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -5:26.4.0 core:paste (atom-text-editor.editor.is-focused)
     -5:26.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:45.8.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -1:45.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:17.5.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -1:17.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:15.3.0 core:undo (atom-text-editor.editor.is-focused)
     -1:14.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:12.3.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -1:12.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:06.4.0 core:undo (atom-text-editor.editor.is-focused)
     -1:06.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:36.5.0 core:undo (ul.list-inline.tab-bar.inset-panel)
     -0:34.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:34.2.0 core:undo (atom-text-editor.editor.is-focused)
     -0:33.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-diff",
      "atom-color-highlight",
      "emmet",
      "terminal-panel",
      "notebook",
      "project-manager"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontFamily": "ubuntu mono",
    "fontSize": 12,
    "showIndentGuide": true,
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.1
atom-color-highlight, vundefined
atom-jade, v0.1.0
color-picker, v1.7.0
file-icons, v1.5.5
git-history, vundefined
git-log, v0.3.0
git-tab-status, v1.9.2
highlight-selected, v0.9.3
jshint, vundefined
language-jade, v0.4.0
linter, vundefined
linter-php, v0.0.12
minimap, v4.9.0
minimap-color-highlight, v4.1.3
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.2.3
minimap-selection, v4.2.0
monokai, v0.14.0
Stylus, v1.0.0
trailing-spaces, v0.2.5

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-05-19 15:41
This is a duplicate of https://github.com/atom/atom/issues/6548 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-19 15:41 UTC
