### ISSUE TITLE
Formatting of lines behind if-statements without brackets

### ISSUE THREAD

**Issue by daffunn** [atom/atom#5049] opened 2015-01-14 08:27 UTC
Hi,

I investigated an enjoying bug in terms of the auto formatting in atom. This happens if you call "Auto Ident" or if code becomes pasted into the editor.

In many languages, e.g. Java, Javascript, PHP, ... the following should be formatted as this:
```javascript
if(somevariable === 3)
   alert(somevariable);
somevariable++;
```
This is the similar behavior as:
```javascript
if(somevariable === 3) {
   alert(somevariable);
}
somevariable++;
```
Atom unfortunately format all lines behind the statements the following way:
```javascript
if(somevariable === 3) 
   alert(somevariable);
   somevariable++;
```

Hope this can be fixed soon :+1:

**Comment by kevinsawicki** [comment] 2015-01-14 17:22
I believe this is a duplicate of https://github.com/atom/language-javascript/issues/51

**Closed by kevinsawicki** 2015-01-14 17:22 UTC

**Comment by daffunn** [comment] 2015-01-14 19:57
It might be important that this is not only an issue for javascript. PHP, Java and many other languages are using this formatting style as well.
