### ISSUE TITLE
close tab 'x' button missing after upgrade to 0.175.0

### ISSUE THREAD

**Issue by sirianni** [atom/atom#5215] opened 2015-01-22 16:14 UTC
After upgrading to atom 0.175.0 this morning, the `x` button is no longer present in the tab header (on hover or otherwise). 

Looking in the inspector, the `close-icon` div is present, but nothing is inside it, nor is any CSS rule causing an 'x' to be rendered.

```
<li is="tabs-tab" class="tab sortable" data-original-title="" title="">
  <div class="title" data-name="app-main.js" data-path="/src/app-main.js">app-main.js</div>
  <div class="close-icon"></div>
</li>
```

I am running Ubuntu 14.04.

**Comment by sirianni** [comment] 2015-01-22 16:29
I'm also noticing that file names that exceed the max tab width are incorrectly overflowing the tab container.  I'm not sure what caused this regression, but adding a CSS rule `.tab-bar .tab .title { overflow: hidden; }` seems to fix it.

**Comment by 50Wliu** [comment] 2015-01-22 17:02
This is a duplicate of #5198.

**Closed by 50Wliu** 2015-01-22 17:02 UTC

**Comment by benogle** [comment] 2015-01-22 17:07
@sirianni what theme do you have? Does it happen in safe mode? Please quit atom completely and run `atom --safe`. Is the issue still there?

**Comment by sirianni** [comment] 2015-01-22 17:14
Thanks.  I was also using the webupd8 PPA.  Strangely though, I was seeing the issues with 0.175.0.  I removed 0.175.0 and installed the `atom-amd64.deb` manually.  This fixed it.
