### ISSUE TITLE
Uncaught TypeError: Cannot set property 'localAddress' of undefined

### ISSUE THREAD

**Issue by wilrnh** [atom/atom#6049] opened 2015-03-20 16:20 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot set property 'localAddress' of undefined

```
At net.js:840

TypeError: Cannot set property 'localAddress' of undefined
  at connect (net.js:840:23)
  at net.js:943:9
  at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:83:16)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:101:10)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/will/Dropbox/PROJ",
    "disabledPackages": [
      "symbols-view"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.6.1
git-control, v0.1.8
git-projects, v1.10.1
jenkins, v0.3.1
language-puppet, v0.10.0
linter-puppet, v0.1.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-03-20 16:24
Thanks for the report, @wilrnh. 

Can you share some steps which reproduce the problem for you? Can you reproduce this reliably? Can you reproduce in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by wilrnh** [comment] 2015-03-20 16:32
I think this was caused entirely by me passing out last night and the laptop going to sleep. Just popped Atom open and a bunch of those exceptions littered the screen.

They should probably be caught and either ignored (if they're part of some auto-update pingback mechanism) or converted to a more useful message for the user.

**Comment by 50Wliu** [comment] 2015-03-20 16:43
Duplicate of #5468.

**Closed by 50Wliu** 2015-03-20 16:43 UTC
Labels: more-information-needed

**Comment by izuzak** [comment] 2015-03-20 16:47
Thanks for clarifying, @wilrnh! And thanks @50Wliu -- I thought it sounded familiar :grin:

**Comment by daithi-coombes** [comment] 2015-04-06 02:21
I also got this issue, but solved it by removing the `jenkins` package:
