### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/isa/Library/Application Support/...

### ISSUE THREAD

**Issue by ibnIrshad** [atom/atom#10128] opened 2015-12-19 16:44 UTC
[Steps to reproduce below:]

1. Open Atom v1.3.2 from file context menu in OSX on a `.c` file
2. Attempt to open Atom->Preferences from the menu bar. This error happens every time, and doesn't let me open up preferences. I have both Atom v1.3.2 and v1.2.2 installed on my system (no error for me on 1.2.2).
 
**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/isa/Library/Application Support/com.github.atom.ShipIt/update.ozswjie/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "ir-black-k-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "Courier",
    "fontSize": 13,
    "showIndentGuide": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-19 16:55
This is a duplicate of #7399 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-19 16:55 UTC
