### ISSUE TITLE
Uncaught Error: Adding a pane item with URI '~/Google Drive\Live\Work\Documentation\ASCIIDOC\Stor...

### ISSUE THREAD

**Issue by roganjoshua** [atom/atom#15940] opened 2017-10-19 15:32 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Adding a pane item with URI 'C:\Users\Martin_Sarosi\Google Drive\Live\Work\Documentation\ASCIIDOC\Stories\PandID\PandID.adoc' that has already been destroyed

```
At C:\Users\Martin_Sarosi\AppData\Local\atom\app-1.21.1\resources\app\src\pane.js:514

Error: Adding a pane item with URI 'C:\Users\Martin_Sarosi\Google Drive\Live\Work\Documentation\ASCIIDOC\Stories\PandID\PandID.adoc' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.21.1/resources/app/src/pane.js:514:21)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.21.1/resources/app/src/pane.js:489:20)
    at TabBarView.module.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/tabs/lib/tab-bar-view.js:715:25)
```

### Commands

```
     -0:14.2.0 pane:split-right-and-copy-active-item (div.plantuml-viewer.native-key-bindings)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.10.3 
atom-beautify 0.30.5 
atom-mermaid 3.2.1 
autocomplete-asciidoc 0.1.2 
diagrams 0.28.3 
language-asciidoc 1.11.0 
language-mermaid 0.6.0 
node-debugger 1.10.1 
org-mode 0.1.0 
plantuml-viewer 0.7.2 
pretty-json 1.6.4 
refactor 0.11.5 
seti-syntax 1.1.3 
seti-ui 1.9.0 
tree-view-filter 0.5.3 
```

**Comment by rsese** [comment] 2017-10-19 19:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/444. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-19 19:28 UTC
