### ISSUE TITLE
Atom freezes when interacting with packages in Settings

### ISSUE THREAD

**Issue by coreyog** [atom/atom#8160] opened 2015-07-30 19:43 UTC
Almost every time I open Settings and go to packages to do something, it'll freeze. If I search for a package that isn't there, sometimes when I open a package to see it's settings, sometimes just opening the package view before I even do anything it'll freeze.

Win7 x64 Atom 1.0.3 all packages fully updated.

**Comment by karai17** [comment] 2015-07-31 09:59
This has been a consistent frustration for me and others I know who use Atom for the past month or two. This is definitely a regression and I believe I have posted an issue about this in the past. I am using a freshly minted clean install of Windows 10 Pro x86_64 with a fresh install of Atom 1.0.3. Reinstalling my packages was a bit of a nightmare and even now when I want to go in and tweak a setting I ask myself if it's just something I can live with because tweaking that setting could take up to five minutes of waiting for Atom to do... Whatever it is Atom is doing.

**Comment by mnquintana** [comment] 2015-07-31 11:07
I think this is a duplicate of https://github.com/atom/atom/issues/7191 – let's keep the discussion there. Let me know if I'm mistaken though.

**Closed by mnquintana** 2015-07-31 11:07 UTC
