### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 15Error: Cannot call...

### ISSUE THREAD

**Issue by plusallofyou** [atom/atom#19771] opened 2019-08-09 18:10 UTC
[Enter steps to reproduce:]

1. Quit Atom
2. Restarted Computer
3. Started Atom

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 15
Error: Cannot call function 'getPosition' on missing remote object 15
    at throwRPCError (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 15
Error: Cannot call function 'getPosition' on missing remote object 15
    at throwRPCError (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:1:703888)
    at AtomEnvironment.storeWindowDimensions (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:1:704303)
    at WindowEventHandler.handleWindowResize (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:285033)
    at l (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1195719)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-cobol 0.3.0 
atom-isort 2.6.3 
atom-material-ui 2.1.3 
atom-react-native-style 0.2.0 
atom-typescript 13.3.0 
autoclose-html 0.23.0 
autocomplete-python 1.14.1 
autocomplete-python-jedi 1.10.3-0 
better-git-blame 0.4.7 
bottom-dock 0.4.4 
browser-plus 0.0.98 
busy-signal 2.0.1 
Chromo-Color-Previews 1.6.6 
color-picker 2.3.0 
color-tabs 0.1.8 
css-color-name 0.4.0 
file-icons 2.1.33 
goto-definition 1.3.4 
Hydrogen 2.10.3 
hyperclick 0.1.5 
ide-json 0.2.1 
ide-python 1.4.2 
ide-typescript 0.9.1 
image-preview 0.4.0 
intentions 1.1.5 
kite 0.168.0 
language-graphql 1.0.0 
language-markdown 0.37.0 
language-nginx 0.8.0 
language-r 0.4.2 
language-sas 0.2.4 
linter 2.3.0 
linter-pycodestyle 2.1.3 
linter-ui-default 1.7.1 
MagicPython 1.1.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-linter 2.2.1 
nbviewer 1.0.2 
platformio-ide-terminal 2.9.3 
prettier-atom 0.57.2 
python-indent 1.2.3 
python-tools 0.6.9 
python-yapf 0.14.0 
pythonic-atom 0.2.9 
react 0.18.0 
script 3.18.1 
sort-lines 0.19.0 
svg-preview 0.14.0 
teletype 0.13.4 
todo-manager 0.2.10 
```

**Comment by rsese** [comment] 2019-08-09 21:28
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

About your steps to reproduce, can you reproduce consistently or did it happen just one time?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-09 21:28 UTC
