### ISSUE TITLE
Popup not under the writing text

### ISSUE THREAD

**Issue by ScriptorNY** [atom/atom#10634] opened 2016-02-01 09:19 UTC
Hello,

I have a problem concerning the atom popup menu (I also have autocomplete-plus installed).
Here is a recording of the problem:

![output](https://cloud.githubusercontent.com/assets/1183923/12712998/73372338-c8cc-11e5-9656-35f57d743108.gif)

Here is my [atom config](https://gist.github.com/ScriptorNY/bcd65349f2caf408799a)

atom: 1.5.0-beta1
OS: archlinux

Thank you very much in advance :)

**Comment by lee-dohm** [comment] 2016-02-01 23:46
This appears to be a duplicate of https://github.com/atom/autocomplete-plus/issues/640. If that is not the case, please open a new issue on the https://github.com/atom/autocomplete-plus repository. That is where we track issues with the autocomplete-plus package.

**Closed by lee-dohm** 2016-02-01 23:46 UTC
Labels: linux
