### ISSUE TITLE
Uncaught TypeError: Cannot read property 'index' of undefined 

### ISSUE THREAD

**Issue by despairblue** [atom/atom#4891] opened 2015-01-07 14:17 UTC
Don't know how I did that but this happened when I opened a specific file and clicked into it. It kept happening until I closed that file. After that never happened again. Can't reproduce it yet. 

![screenshot from 2015-01-07 14 52 49](https://cloud.githubusercontent.com/assets/927609/5646739/aa389c3e-967f-11e4-9630-c81e7bd5e07d.png)

Can't format the stack trace as a block (maybe to big).
```
Uncaught TypeError: Cannot read property 'index' of undefined /usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:95module.exports.IntervalSkipList.findIntersecting /usr/share/atom/resources/app/node_modules/text-buffer/node_modules/interval-skip-list/lib/interval-skip-list.js:95module.exports.MarkerManager.findMarkers /usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-manager.js:156module.exports.TextBuffer.findMarkers /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:657module.exports.DisplayBuffer.findMarkers /usr/share/atom/resources/app/src/display-buffer.js:1296module.exports.DisplayBuffer.decorationsForScreenRowRange /usr/share/atom/resources/app/src/display-buffer.js:1189module.exports.TextEditor.decorationsForScreenRowRange /usr/share/atom/resources/app/src/text-editor.js:1220module.exports.React.createClass.render /usr/share/atom/resources/app/src/text-editor-component.js:77(anonymous function) /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1249(anonymous function) /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1179ReactCompositeComponentMixin._performComponentUpdate /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1123ReactCompositeComponentMixin.performUpdateIfNecessary /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1063runBatchedUpdates /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:152Mixin.perform /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141Mixin.perform /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:141mixInto.perform /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98(anonymous function) /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176Mixin.closeAll /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214Mixin.perform /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155ReactDefaultBatchingStrategy.batchedUpdates /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70enqueueUpdate /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209ReactCompositeComponentMixin.forceUpdate /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232(anonymous function) /usr/share/atom/resources/app/src/text-editor-component.js:320requestAnimationFrame (async)module.exports.React.createClass.requestUpdate /usr/share/atom/resources/app/src/text-editor-component.js:323boundMethod /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295module.exports.React.createClass.onScrollTopChanged /usr/share/atom/resources/app/src/text-editor-component.js:929boundMethod /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295(anonymous function) /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:155module.exports.Emitter.emitSlow /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:154module.exports.Emitter.emit /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:107module.exports.Signal.emitValue /usr/share/atom/resources/app/node_modules/emissary/lib/signal.js:82(anonymous function) /usr/share/atom/resources/app/node_modules/emissary/lib/behavior.js:81(anonymous function) /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:155module.exports.Emitter.emitSlow /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:154module.exports.Emitter.emit /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:107module.exports.Behavior.emit /usr/share/atom/resources/app/node_modules/emissary/lib/behavior.js:44module.exports.Signal.emitValue /usr/share/atom/resources/app/node_modules/emissary/lib/signal.js:82module.exports.Model.set /usr/share/atom/resources/app/node_modules/theorist/lib/model.js:166accessor.set /usr/share/atom/resources/app/node_modules/theorist/lib/model.js:57module.exports.DisplayBuffer.setScrollTop /usr/share/atom/resources/app/src/display-buffer.js:466module.exports.DisplayBuffer.setWidth /usr/share/atom/resources/app/src/display-buffer.js:456module.exports.TextEditor.setWidth /usr/share/atom/resources/app/src/text-editor.js:2863module.exports.React.createClass.measureHeightAndWidth /usr/share/atom/resources/app/src/text-editor-component.js:1098boundMethod /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295(anonymous function) /usr/share/atom/resources/app/src/text-editor-component.js:1066requestAnimationFrame (async)module.exports.React.createClass.requestHeightAndWidthMeasurement /usr/share/atom/resources/app/src/text-editor-component.js:1068boundMethod /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295resize (async)makeDateFromInput /home/despairblue/.atom/packages/bug-report/node_modules/moment/moment.js:1469makeMoment /home/despairblue/.atom/packages/bug-report/node_modules/moment/moment.js:1801moment /home/despairblue/.atom/packages/bug-report/node_modules/moment/moment.js:1832module.exports.CommandLogger.formatTime /usr/share/atom/resources/app/node_modules/notifications/lib/command-logger.js:143module.exports.CommandLogger.formatEvent /usr/share/atom/resources/app/node_modules/notifications/lib/command-logger.js:124(anonymous function) /usr/share/atom/resources/app/node_modules/notifications/lib/command-logger.js:54module.exports.CommandLogger.eachEvent /usr/share/atom/resources/app/node_modules/notifications/lib/command-logger.js:106module.exports.CommandLogger.getText /usr/share/atom/resources/app/node_modules/notifications/lib/command-logger.js:46NotificationElement.getIssueBody /usr/share/atom/resources/app/node_modules/notifications/lib/notification-element.js:326NotificationElement.getIssueUrl /usr/share/atom/resources/app/node_modules/notifications/lib/notification-element.js:297NotificationElement.generateMarkup /usr/share/atom/resources/app/node_modules/notifications/lib/notification-element.js:118NotificationElement.initialize /usr/share/atom/resources/app/node_modules/notifications/lib/notification-element.js:33(anonymous function) /usr/share/atom/resources/app/node_modules/notifications/lib/main.js:73module.exports.ViewRegistry.createView /usr/share/atom/resources/app/src/view-registry.js:56module.exports.ViewRegistry.getView /usr/share/atom/resources/app/src/view-registry.js:43(anonymous function) /usr/share/atom/resources/app/node_modules/notifications/lib/main.js:24module.exports.Emitter.emit /usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82module.exports.NotificationManager.addNotification /usr/share/atom/resources/app/src/notification-manager.js:54module.exports.NotificationManager.addFatalError /usr/share/atom/resources/app/src/notification-manager.js:45(anonymous function) /usr/share/atom/resources/app/node_modules/notifications/lib/main.js:47module.exports.Emitter.emit /usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82(anonymous function) /usr/share/atom/resources/app/src/atom.js:233Mixin.closeAll /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:214Mixin.perform /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/Transaction.js:155ReactDefaultBatchingStrategy.batchedUpdates /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70enqueueUpdate /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209ReactCompositeComponentMixin.forceUpdate /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1232(anonymous function) /usr/share/atom/resources/app/src/text-editor-component.js:320requestAnimationFrame (async)module.exports.React.createClass.requestUpdate /usr/share/atom/resources/app/src/text-editor-component.js:323boundMethod /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295module.exports.React.createClass.onScrollTopChanged /usr/share/atom/resources/app/src/text-editor-component.js:929boundMethod /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295(anonymous function) /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:155module.exports.Emitter.emitSlow /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:154module.exports.Emitter.emit /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:107module.exports.Signal.emitValue /usr/share/atom/resources/app/node_modules/emissary/lib/signal.js:82(anonymous function) /usr/share/atom/resources/app/node_modules/emissary/lib/behavior.js:81(anonymous function) /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:155module.exports.Emitter.emitSlow /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:154module.exports.Emitter.emit /usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:107module.exports.Behavior.emit /usr/share/atom/resources/app/node_modules/emissary/lib/behavior.js:44module.exports.Signal.emitValue /usr/share/atom/resources/app/node_modules/emissary/lib/signal.js:82module.exports.Model.set /usr/share/atom/resources/app/node_modules/theorist/lib/model.js:166accessor.set /usr/share/atom/resources/app/node_modules/theorist/lib/model.js:57module.exports.DisplayBuffer.setScrollTop /usr/share/atom/resources/app/src/display-buffer.js:466module.exports.DisplayBuffer.setWidth /usr/share/atom/resources/app/src/display-buffer.js:456module.exports.TextEditor.setWidth /usr/share/atom/resources/app/src/text-editor.js:2863module.exports.React.createClass.measureHeightAndWidth /usr/share/atom/resources/app/src/text-editor-component.js:1098boundMethod /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295module.exports.React.createClass.pollDOM /usr/share/atom/resources/app/src/text-editor-component.js:1042boundMethod /usr/share/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295
```

## Versions

* **Atom:**       0.166.0
* **Atom-Shell:** 0.19.4
* **OS:**         linux 3.14.26-1-lts
* **Misc**
    * apm  0.116.0
    * npm  1.4.4
    * node 0.10.33
    * python 3.4.2
    * git 2.2.1

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.5.3.</small>

**Comment by izuzak** [comment] 2015-01-07 16:39
Thanks for the report!

@nathansobo might have :thought_balloon: about this (looking at the stack trace and seeing interval-skip-list at the top). I can't reproduce this either, though.

**Comment by nathansobo** [comment] 2015-01-07 17:02
These kinds of bugs are brutal. The interval skip list that indexes marker locations is getting into a corrupted state. Somehow a forward pointer in the list is pointing to undefined. Going to need some reproduction steps. :disappointed:

**Comment by Fiend3d** [comment] 2015-01-09 18:41
I think I managed to reproduce it three times. 
1. Reboot Windows 
2. Open any file with atom using the right button 
Atom stops responding and I can only close it. It doesn't show up again, only after rebooting. 

![atom1](https://cloud.githubusercontent.com/assets/10120007/5685090/0736a452-9848-11e4-8da0-2bb1e4efc2df.png)

**Comment by Fiend3d** [comment] 2015-01-09 19:09
If I disable minimap everything seems to be fine.

**Comment by abe33** [comment] 2015-01-09 23:55
@nathansobo You can use the minimap test suite if you need reproducible steps, I had one that appears systematically on Travis since I started working on v4 ([3.5.4 build](https://travis-ci.org/fundon/atom-minimap/builds/46231717) which ran 2 days ago had it), with my [latest commit](https://travis-ci.org/fundon/atom-minimap/builds/46258692) there's even more errors raised with `interval-skip-list` if you want to dig in it.

**Comment by Alchiadus** [comment] 2015-01-15 09:48
I've been getting the same error for a while and finally managed to reproduce it consistently.

##### Reproduction Steps:
1. Open Atom (via command line or GUI, both is fine).
2. Close the new 'untitled' tab.
3. Open any file that is scrollable (e.g. `config.cson` if the file is long enough to be scrollable, via `File` -> `Open Your Config`).
4. Do not scroll the file (with the mousewheel / keyboard).
5. Drag the mouse over the minimap to scroll the file.
6. Observe Atom completely locks up with the above mentioned error being thrown and needs to be restarted.

Step 4 is important. Replacing only step 4 in the original reproduction steps by:
4. Scroll the file.
results in normal behaviour in step 6, no error is thrown and the file is scrolled appropriately.

Step 2 is peculiar. Replacing only step 2 in the original reproduction steps by:
2. Keep the new 'untitled' tab open.
results in normal behaviour in step 6, no error is thrown and the file is scrolled appropriately.

Replacing only step 2 in the original reproduction steps by:
2a. Close the new 'untitled' tab.
2b. Open a file (e.g. `init.coffee`, via `File` -> `Open Your Init Script`).
2c. Immediately click on `File` and move your mouse to `Open Your Config` (assuming it is long enough to be scrollable).
2d. Wait until the loading wheel disappears next to the cursor.
2e. Click to open `config.cson`.
results in normal behaviour in step 6, no error is thrown and the file is scrolled appropriately.

However, merging 2c/2d into:
2cd: Immediately click on `File` and move your mouse to `Open Your Config` (assuming it is long enough to be scrollable) and click to open it as quickly[*] as you can.
results in the above mentioned error being thrown.

[*] quickly means at least fast enough so that the loading wheel is still next to the cursor, but probably fast enough so that it is not almost done loading.

'Human readable' summary:
If you have another file open long enough so that it has been scanned the error does not occur when you open a scrollable file and drag the minimap without scrolling in this file first. Somewhat surprisingly, the error does occur if you do not have any files open, open a scrollable file, make a cup of coffee to make sure it has enough time to be scanned and drag the minimap without scrolling the file first.

##### OS:
Windows 8.1
##### Versions:
* Atom 0.172.0
* Minimap 3.5.5 (without v4 enabled)
* apm  0.119.0
* npm  1.4.4
* node 0.10.35
* python 2.7.8
* git 1.9.5.msysgit.0

**Comment by maxbrunsfeld** [comment] 2015-01-16 19:42
I can't reproduce this currently. I'm just going to leave minimap enabled for a while during work and see if it ever happens for me.

**Comment by btleffler** [comment] 2015-01-20 14:49
I can confirm what @Alchiadus said about setting Minimap to v4 preview. After a restart, I can't reproduce this error anymore.

Windows 8.1

Atom 0.174.0
Minimap 3.5.6
apm  0.120.0
npm  1.4.4
node 0.10.35
python 2.7.6
git 1.8.5.2.msysgit.0
visual studio 2013

**Comment by benogle** [comment] 2015-06-30 18:24
Several marker related bits have changed, and this has not been reported in a while. If anyone still gets this, please comment!

**Closed by benogle** 2015-06-30 18:24 UTC
Labels: atom, bug, post-1.0-roadmap, uncaught-exception
