### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/colleensmith/Downloads/Atom.app'

### ISSUE THREAD

**Issue by colleenalicia** [atom/atom#10351] opened 2016-01-09 18:33 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/colleensmith/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/colleensmith/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/colleensmith/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
     -1:13.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:05.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:00.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:58.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:56.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:56.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:56.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:54.5.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:52.6.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:51.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:49.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:49.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:49.7.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:45.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:17.9.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:07.3.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-01-09 19:25
Hi @colleenalicia, thanks for reporting!  This looks like a duplicate of #7399 though, so please subscribe there for updates.

**Closed by 50Wliu** 2016-01-09 19:25 UTC
