### ISSUE TITLE
PHP is not coloring

### ISSUE THREAD

**Issue by leotecco** [atom/atom#6936] opened 2015-05-25 01:14 UTC
Hello ,

I've got a problem ... my files in PHP are not coloring ... it always happens that involves files in PHP ... any solution? My Atom is in Patch 0.201.0

Thank you !!

Waiting for answers !

**Comment by m1ga** [comment] 2015-05-25 10:38
without seeing a screenshot its hard to say but add a blank line on top, save the file and reopen it. There was a bug with files that had HTML in the beginning

**Comment by izuzak** [comment] 2015-05-25 14:04
@leotecco Yeah, can you please share a screenshot of what you see (Atom's window fully visible), and a link to the file in question?

**Comment by leotecco** [comment] 2015-05-26 03:30
Screenshot...
Very strange ... Because Atom is in version 0.201.0 and in version 0.198.0 fixed the bug...

"v0.198.0 (2015-05-07)
Notable Changes
Fixed an issue where certain PHP files would not be colorized"
https://atom.io/releases


I am Brazilian... do not be surprised with the words in the file hahahaha...
Thank you for help...

![screenshot](https://cloud.githubusercontent.com/assets/12589548/7804701/7032cdfa-033c-11e5-82ba-09b614f75380.png)

**Comment by m1ga** [comment] 2015-05-26 05:18
As you can see in the bottom right corner it says its an html file. Try my tip from before or manually set it to php

**Comment by izuzak** [comment] 2015-05-26 08:29
I believe this is a duplicate of https://github.com/atom/atom/issues/2734 -- please follow that for updates.

**Closed by izuzak** 2015-05-26 08:29 UTC
Labels: more-information-needed
