### ISSUE TITLE
Atom crashes when large files are opened

### ISSUE THREAD

**Issue by akshaybabloo** [atom/atom#12049] opened 2016-06-27 00:04 UTC
### Description

Atom crashes when large files are opened. I have a JSON file of 10 MB (which is not that large), it opens for the first time, but when I scroll down I get a popup window saying - "The editor has crashed"

### Versions

**Atom**
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**amp**
apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.1.windows.1
visual studio 2013

**Comment by brianbancroft** [comment] 2016-06-28 16:22
I also have the same problem when I open a 626KB JSON file using the same version of ATOM with my Macbook Pro running the latest version of OS X.

**Comment by trusktr** [comment] 2016-06-28 17:52
Tracking all these large-file issues in #12065.

**Comment by mnquintana** [comment] 2016-06-29 00:43
This seems like a duplicate of https://github.com/atom/atom/issues/8864 – let's keep the discussion going there.

**Closed by mnquintana** 2016-06-29 00:43 UTC

**Comment by krabbypattified** [comment] 2017-03-05 18:13
Hello from issue #12065. Atom Beta should fix this for many people.
