### ISSUE TITLE
Unable to auto update on OS X 10.10.3

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [atom/atom#7833] opened 2015-07-10 14:46 UTC
Trying to upgrade from 1.0.0 to 1.0.2.

10/07/15 16:27:14,748 Atom[23703]: App load time: 675ms
10/07/15 16:27:51,981 Atom[23703]: Download completed to: file:///Users/jeffwilliams/Library/Application%20Support/com.github.atom.ShipIt/update.BVNKFkF/download

I choose "Restart and Install Update".

Atom closes and never restarts. When I restart manually it is still version 1.0.0.

I ended up manually copying Library/Application\ Support/com.github.atom.ShipIt/update.BVNKFkF/Atom.app to /Applications, which seemed to work fine.

I had a similar issue with upgrading to 1.0.0 and downloaded from the website and installed.

**Comment by michaelaye** [comment] 2015-07-13 18:05
Similar issue on OSX 10.10.4:
1. Trying to upgrade from 1.0.0 to 1.0.2
2. Click "Restart and update"
3. Atom closes AND restarts (contrary to OP)
4. Update was NOT performed (still 1.0.0)

**Comment by michaelaye** [comment] 2015-07-13 18:07
Tried it on my 10.10.4 machine, it behaves exactly the same as I described in comment above.

**Comment by jonathanbull** [comment] 2015-07-14 13:07
I'm also having this issue.

**Comment by faddah** [comment] 2015-07-16 21:39
ditto, also seeing this in attempting to update from 1.0.0 to 1.0.2. will not update, will not re-launch itself as promised. see my submitted issue here:  #7940 .

—  faddah
     portland, oregon, u.s.a.

**Comment by jonathanbull** [comment] 2015-07-16 21:55
Does anyone know if there's an error log or any kind of diagnostics we can do to try and narrow down the issue?

**Comment by faddah** [comment] 2015-07-17 01:04
since my other issue, #7940, was closed citing this as a duplicate, i thought i'd put my info on what i found from there to here —

i have tried, several times, to get the new Atom 1.0.0 to update to 1.0.2, on a 27" iMac with a intel i7 2.8 GHz, 16 GB RAM, and Mac OS X 10.10.4 with all the latest updates. first, Atom never, repeat, NEVER restarts — you click "update & restart app" and it quits the app but never restarts it. never restarts. never. _*never, never, never.*_ period. then, when i re-launch the app, it is still at 1.0.0, even though it had said it downloaded the new 1.0.2 version and was ready to re-launch as the new, updated app. how do i fix this? please advise.

keep in mind, this is with the newer Mac OS X 10.10.4, not the earlier 10.10.3, so it's still happening after the Mac OS X update.

— faddah
portland, oregon, u.s.a.

**Comment by faddah** [comment] 2015-07-30 17:31
just wanted to give an update, still happening on a 2009 iMac 27", intel core i7 2.8 GHz processor, 16 GB RAM, Mac OS X 10.10.4 Yosemite, and Atom Editor update going from v.1.0.2 to v.1.0.3.  still happending, says it's downloaded the update and needs to restart, hit "restart," nothing happens. launch Atom Editor again, starts same process all over again, never updates. thought you'd want to know.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by braver** [comment] 2015-07-30 18:30
This is probably a duplicate: https://github.com/atom/atom/issues/7001

**Comment by mnquintana** [comment] 2015-08-05 15:19
This is a duplicate of https://github.com/atom/atom/issues/7833 – please subscribe there for updates.

**Closed by mnquintana** 2015-08-05 15:19 UTC
Labels: installer, mac, more-information-needed, needs-reproduction, quality-bogle
