### ISSUE TITLE
application:open-file should default to the directory where the currently viewed file resides

### ISSUE THREAD

**Issue by mercmobily** [atom/atom#7110] opened 2015-06-05 04:10 UTC
The title says everything. If you have several files open, and press CTRL-O, at the moment the open dialog will default to "Recently Used". However, it makes a _lot_ of sense to default, as a starting point, to the directory where the file currently viewed is.

For example if you are working on the file `youtRepo/auth/button/facebook.js`, and you want to open `youtRepo/auth/button/local.js`, you should be able to press CTRL-O and find yourself in `youtRepo/auth/button/`. Again, this is what happens in Sublime and I find it immensely helpful.

I tried to do it myself, but I am not familiar with Atom's code. However, the relevant lines seem to be https://github.com/atom/atom/blob/master/src/browser/atom-application.coffee#L225-L227 and https://github.com/atom/atom/blob/master/src/browser/atom-application.coffee#L171.

**Comment by mnquintana** [comment] 2015-06-05 10:18
Thanks for the suggestion! This seems like a duplicate of https://github.com/atom/atom/issues/6088 – does that about cover what you're looking for?

**Comment by mercmobily** [comment] 2015-06-05 10:38
Actually... it's to solve the same problem, but in a totally different way. I think presenting the last folder is not the right way to go about it: the dialog should be where the *currently viewed* file is, so that you can open files around it. The same should apply to Save. That's what Sublime does, and it's crucial.

**Comment by mercmobily** [comment] 2015-06-05 13:25
I tried once again to do it on my own and failed. I am not familiar with Coffeescript at all, which isn't helping. (I am not familiar with the code base either, and that's another issue).

If somebody has any pointers to hemp me give it a crack, I will me most grateful!

**Comment by rbu** [comment] 2015-06-20 11:38
@mercmobily wrote:
> it's to solve the same problem, but in a totally different way. I think presenting the last folder is not the right way to go about it: the dialog should be where the currently viewed file is, so that you can open files around it. The same should apply to Save.

I would argue that when saving a file, your description is inaccurate. Since the currently viewed bufer is no file yet, it has no directory and the editor should default to the directory of the last viewed buffer that is a file. Maybe I was not as clear in issue #6088 either ("opened" vs. "viewed"), but I think we are describing the same algorithm.

**Comment by mercmobily** [comment] 2015-06-20 12:09
Sorry, writing this from my phone while looking after kids.
The idea is that when saving, it should use the directory of last viewed
file.

Use case: I am in a directory. I wrote the `c` file. I need to write the
header. I create a new file, write the header, press ctrl-s. The last
saving folder could be anywhere, but I obviously want to save where the `c`
file is.

If that is what you meant, my apologies. I don't have access to past
messages...

Thank you!

**Comment by stebiger** [comment] 2015-07-17 10:55
Similar to my issue #7909 - I support this request

**Comment by renke** [comment] 2015-07-20 20:20
:+1: because this really bugs me…

**Comment by samrayner** [comment] 2015-09-22 16:05
Yes please, I miss this from Sublime!

**Comment by lucentminds** [comment] 2016-01-14 14:24
I also want this feature. While advanced-open-file helps with this, it's just not the same.

**Comment by ashaffer** [comment] 2016-02-04 23:21
+1 on this.

**Comment by pinzer** [comment] 2016-02-13 11:02
+1 on this

**Comment by triklozoid** [comment] 2016-03-22 11:18
+1

**Comment by Zireael07** [comment] 2016-03-22 12:57
Agreed. I hate going to open file and getting some weird folder I opened once but never again...

**Comment by pinzer** [comment] 2016-04-22 07:48
Any news about this? this is the only fix is stopping me migrating from sublime to atom

**Comment by eliseumds** [comment] 2016-05-10 12:32
👍

**Comment by sandrodz** [comment] 2016-05-14 09:45
saving should also be treated the same way. nobody cares about project root.

**Comment by cxshun** [comment] 2016-05-16 12:33
Still the same in Atom 1.7.1. Didn't fixed yet?

**Comment by 50Wliu** [comment] 2016-05-16 20:24
I think this has been fixed in Atom 1.9.0 - can someone please try building from source and confirm?  I for one can't reproduce this anymore on 1.9.0.

**Comment by ajoslin103** [comment] 2016-06-17 15:33
I'm on the 1.9.0-beta0 and it's WORKING !!!! 

I can flip back and forth between files from different folders and the open dialog follows the tab I'm in !!!!

ThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYouThankYou

**Comment by 50Wliu** [comment] 2016-06-18 02:03
Thanks for reporting back @ajoslin103! :sparkles:

**Closed by 50Wliu** 2016-06-18 02:03 UTC
Labels: enhancement, needs-reproduction

**Comment by mercmobily** [comment] 2016-06-18 04:09
Hi,

Yep fixed -- thank you. Huge improvement, this problem drove me seriously
insane on a daily basis...

Merc.
