### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by kudoh104** [atom/atom#5538] opened 2015-02-13 02:58 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:355

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:355:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:332:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:286:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:485:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:412:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
  2x -1:41.5 core:select-down (atom-text-editor.editor)
     -1:40.1 core:backspace (atom-text-editor.editor)
     -1:38.7 core:select-down (atom-text-editor.editor)
     -1:38.1 core:backspace (atom-text-editor.editor)
     -1:37.0 core:move-down (atom-text-editor.editor)
     -1:36.7 core:move-up (atom-text-editor.editor)
  2x -1:36.4 core:select-down (atom-text-editor.editor)
     -1:35.6 core:move-up (atom-text-editor.editor)
  2x -1:34.0 core:move-down (atom-text-editor.editor)
     -1:32.0 core:select-down (atom-text-editor.editor)
     -1:31.7 core:move-up (atom-text-editor.editor)
     -1:31.0 core:save (atom-text-editor.editor)
     -0:04.3 core:move-right (atom-text-editor.editor)
     -0:04.1 core:move-up (atom-text-editor.editor)
  4x -0:03.8 core:select-right (atom-text-editor.editor)
  6x -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.2
gulp-snippets, v0.6.0
language-scala, v1.1.0
linter-javac, v0.1.3
linter-scalac, v0.3.3
scala-format, v0.1.2
script, v2.16.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-02-13 04:44
This question has been asked a ton times :joy: 
Please have a look at #307

**Comment by lee-dohm** [comment] 2015-02-13 05:12
Duplicate of atom/atom#4421 and atom/atom#307. Please subscribe there for updates.

**Closed by lee-dohm** 2015-02-13 05:12 UTC
