### ISSUE TITLE
Atom will be blocked when open the compress js file！！！

### ISSUE THREAD

**Issue by jkiss** [atom/atom#8740] opened 2015-09-10 09:32 UTC
Sometime i will wait a long time, why atom is slow when format compress js file????

**Comment by Zireael07** [comment] 2015-09-10 11:45
How many lines does the file have? Does it have long lines?

**Comment by mnquintana** [comment] 2015-09-10 11:54
This is a duplicate of #979 - please subscribe there for updates.

**Closed by mnquintana** 2015-09-10 11:54 UTC
