### ISSUE TITLE
Atom Consistently Crashes When starting up (Yosemite)

### ISSUE THREAD

**Issue by darkn3rd** [atom/atom#9114] opened 2015-10-11 22:41 UTC
I am not sure of the root cause, but it is 100% crashing.

```
Process:               Atom [65686]
Path:                  /opt/homebrew-cask/*/Atom.app/Contents/MacOS/Atom
Identifier:            com.github.atom
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Atom [65686]
User ID:               135827580

Date/Time:             2015-10-11 15:37:31.587 -0700
OS Version:            Mac OS X 10.10.5 (14F27)
Report Version:        11
Anonymous UUID:        213C8110-8580-7387-3B4B-D2B8C915FFE5

Sleep/Wake UUID:       4C8D6AFE-2219-4E83-B2FA-9303BB9783EF

Time Awake Since Boot: 320000 seconds
Time Since Wake:       2300 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /opt/homebrew-cask/*/Atom.app/Contents/MacOS/Atom
  Reason: no suitable image found.  Did find:
    /opt/homebrew-cask/Caskroom/atom/1.0.15/Atom.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: code signature invalid for '/opt/homebrew-cask/Caskroom/atom/1.0.15/Atom.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework'

Binary Images:
    0x7fff680a5000 -     0x7fff680db887  dyld (353.2.3) <B1B370A5-479F-3533-8AD7-97B687D4F989> /usr/lib/dyld

Model: MacBookPro11,3, BootROM MBP112.0138.B15, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
```

From the command line, I get:

```
LSOpenURLsWithRole() failed for the application /Users/joaquin.menchaca/Applications/Atom.app with error -10810.
```

**Comment by bitwombat** [comment] 2015-11-23 22:44
I can confirm this is happening with packager 5.1.1 and electron 0.34.2.  Happy to try HEAD of either/both if anybody thinks that will work.  Duplicate of bug filed with electron-packager https://github.com/maxogden/electron-packager/issues/117

**Comment by lee-dohm** [comment] 2015-11-25 03:35
It sounds like the issue here is installing Atom from Homebrew since the cask version was built on Linux? If so, the solution is to install the version from [the website](https://atom.io).

**Comment by bitwombat** [comment] 2015-11-25 12:00
Not sure what this means.  Nothing should need to be installed on OSX (via homebrew) since the electon-packaged app is completely self contained, right?

**Comment by lee-dohm** [comment] 2015-11-25 16:16
That's correct ... but look at the path where Atom is executing from in the crash info above:

> /opt/homebrew-cask/*/Atom.app/Contents/MacOS/Atom

This says to me that Atom itself was installed by the Homebrew tool. As far as I know, this isn't an official build of Atom.

**Comment by bitwombat** [comment] 2015-11-26 00:48
Ah, interesting.  Mine is similar but different.
```
Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/Desktop/*/UF.app/Contents/MacOS/Electron
  Reason: image not found
```

**Comment by lee-dohm** [comment] 2015-11-26 02:06
@darkn3rd, can you try installing Atom from the website and see if you continue to have the issue?

**Comment by zcbenz** [comment] 2015-11-26 05:19
> Dyld Error Message:
>   Library not loaded: @rpath/Electron Framework.framework/Electron Framework
>   Referenced from: /opt/homebrew-cask/*/Atom.app/Contents/MacOS/Atom
>   Reason: no suitable image found.  Did find:
>     /opt/homebrew-cask/Caskroom/atom/1.0.15/Atom.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: code signature invalid for '/opt/homebrew-cask/Caskroom/atom/1.0.15/Atom.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework'

It seems that `Electron Framework` is not signed correctly.

**Comment by darkn3rd** [comment] 2015-11-29 23:18
I think I lost the original condition that yielded this result consistently.  I can try to reproduce it on clean virtual images in Virtualbox.

**Comment by bardiharborow** [comment] 2016-12-23 02:47
This is back again. My install is crashing on MacOS Sierra.


```
Process:               Atom [1608]
Path:                  /Applications/Atom.app/Contents/MacOS/Atom
Identifier:            com.github.atom
Version:               1.12.7 (1.12.7)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Atom [1608]
User ID:               503

Date/Time:             2016-12-23 13:43:39.676 +1100
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        CDA75120-76B3-22EF-A7A5-FEF5C4DE5BB6

Sleep/Wake UUID:       05051456-B1A0-42A9-A38F-37388C9D9BAB

Time Awake Since Boot: 17000 seconds
Time Since Wake:       7100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libnode.dylib
  Referenced from: /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found

Binary Images:
       0x10cb17000 -        0x10cb17ff7 +com.github.atom (1.12.7 - 1.12.7) <987AD0DE-F2C8-3A66-A898-8DC87EC8E5D2> /Applications/Atom.app/Contents/MacOS/Atom
       0x10cb23000 -        0x10fec0fcf +com.github.electron.framework (0) <893E15C3-B80D-3B8C-845D-2D4EFA0FCC02> /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x11072e000 -        0x110744fff +com.github.Squirrel (1.0 - 1) <A3768DDA-8D21-3A44-BA9A-1B78C79AF305> /Applications/Atom.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x110763000 -        0x1107c6ff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Applications/Atom.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x110842000 -        0x110856fff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Applications/Atom.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x111bda000 -        0x111c171c7  dyld (421.1) <A525EAEA-AF86-30C2-B360-3D093B4F0828> /usr/lib/dyld
    0x7fff79991000 -     0x7fff79991fff  com.apple.Carbon (154 - 157) <AB71A31F-5B15-3BF5-8532-591EACD07B21> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff7ff52000 -     0x7fff8014cff7  com.apple.QuartzCore (1.11 - 449.39) <B6BEEBAC-2923-3BA6-8DBD-621A2B0E51C1> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff8df00000 -     0x7fff8df01ff3  libSystem.B.dylib (1238) <168B3C56-081B-3998-9A44-681EB4C6828F> /usr/lib/libSystem.B.dylib
    0x7fff8e098000 -     0x7fff8e0eeff7  libc++.1.dylib (307.4) <BEE86868-F831-384C-919E-2B286ACFE87C> /usr/lib/libc++.1.dylib

Model: MacBookPro9,2, BootROM MBP91.00D3.B0D, 2 processors, Intel Core i5, 2.5 GHz, 4 GB, SMC 2.2f38
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80CE, 0x4D34373142353737334448302D434B302020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80CE, 0x4D34373142353737334448302D434B302020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.171.10.1a16)
Bluetooth: Version 5.0.0f18, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS547550A9E384, 500.11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS31N
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by Airhogs777** [comment] 2017-01-03 21:39
I've found a solution to this. You'll want to resolve all of the links, so replace everything in `app/Contents/Frameworks/Electron Framework.framework/` with everything in `app/Contents/Frameworks/Electron Framework.framework/versions/A` and do this for the rest of the frameworks.

**Comment by lee-dohm** [comment] 2017-01-04 00:07
Since this is resolved for @darkn3rd, I'm going to close this. I'm not sure that the problem with crashing that @bardiharborow is having is the same one, so if you would file a new issue @bardiharborow by filling out the template, we can take a look.

**Closed by lee-dohm** 2017-01-04 00:07 UTC
Labels: crash, electron, mac

**Comment by pgoergler** [comment] 2017-05-31 08:24
Hi,

Append this morning:
```
Process:               Atom [54698]
Path:                  /Applications/Atom.app/Contents/MacOS/Atom
Identifier:            com.github.atom
Version:               1.17.2 (1.17.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Atom [54698]
User ID:               502

Date/Time:             2017-05-31 12:22:35.236 +0400
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        DAD046DB-6834-6381-8566-643CD1820FFE

Sleep/Wake UUID:       09842DCB-2F30-4059-BDB4-65147D5FEEDF

Time Awake Since Boot: 170000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libnode.dylib
  Referenced from: /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found

Binary Images:
       0x1043e6000 -        0x1043e6ff7 +com.github.atom (1.17.2 - 1.17.2) <3B90F22A-7F44-31B7-9D4E-1465D91AAC4F> /Applications/Atom.app/Contents/MacOS/Atom
       0x1043f1000 -        0x107731f2f +com.github.electron.framework (0) <FA75BD7B-593B-394F-8D2E-0748483743A8> /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x107cc1000 -        0x107cd7fff +com.github.Squirrel (1.0 - 1) <A3768DDA-8D21-3A44-BA9A-1B78C79AF305> /Applications/Atom.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x107cfb000 -        0x107d5eff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Applications/Atom.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x107dd9000 -        0x107dedfff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Applications/Atom.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x10a7e2000 -        0x10a81fdc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff7e31f000 -     0x7fff7e31ffff  com.apple.Carbon (154 - 157) <69F403C7-F0CB-34E6-89B0-235CF4978C17> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff8490e000 -     0x7fff84b0efff  com.apple.QuartzCore (1.11 - 453.39.3) <AB46D60D-17A8-3122-800E-2A9DA604FCBA> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff92fc5000 -     0x7fff92fc6ffb  libSystem.B.dylib (1238.60.2) <FC9E9F13-3B18-305C-BE0A-97C7843652B0> /usr/lib/libSystem.B.dylib
    0x7fff930ff000 -     0x7fff93155ff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib

Model: MacBookAir6,2, BootROM MBA61.0099.B51, 2 processors, Intel Core i7, 1,7 GHz, 8 GB, SMC 2.13f15
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x02FE, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.171.126.1a2)
Bluetooth: Version 5.0.4f18, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@190,0,0
PCI Card: Apple 57761-B0, Ethernet Controller, Thunderbolt@191,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@194,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@194,0,1
PCI Card: pci12d8,400f, USB Enhanced Host Controller, Thunderbolt@194,0,2
Serial ATA Device: APPLE SSD SM0512F, 500,28 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Magic Trackpad 2
USB Device: FaceTime HD Camera (Display)
USB Device: Apple Thunderbolt Display
USB Device: Display Audio
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6
Thunderbolt Device: Thunderbolt Display, Apple Inc., 1, 26.2

```

**Comment by eelke** [comment] 2017-09-15 09:18
Idem dito.

```Process:               Atom [3541]
Path:                  /Applications/Atom.app/Contents/MacOS/Atom
Identifier:            com.github.atom
Version:               1.20.0 (1.20.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Atom [3541]
User ID:               501

Date/Time:             2017-09-15 11:15:04.297 +0200
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        3A29A879-B264-0BE6-F0BD-4A467FF5D989


Time Awake Since Boot: 640 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libnode.dylib
  Referenced from: /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found

Binary Images:
       0x10b19f000 -        0x10b19fff7 +com.github.atom (1.20.0 - 1.20.0) <CB63147A-C9DC-308B-8CA1-EE92A5042E8E> /Applications/Atom.app/Contents/MacOS/Atom
       0x10b1aa000 -        0x10ee2ff73 +com.github.electron.framework (0) <02EEB879-495F-3A71-9D22-B9C1710D7DC4> /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x10f476000 -        0x10f490fff +com.github.Squirrel (1.0 - 1) <4C459C36-AFB6-3B8A-8FEC-76C192C17E30> /Applications/Atom.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x10f4bc000 -        0x10f51fff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Applications/Atom.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x10f59d000 -        0x10f5b1fff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Applications/Atom.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x113462000 -        0x11349fdc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fffa4dcd000 -     0x7fffa4dcdfff  com.apple.Carbon (154 - 157) <69F403C7-F0CB-34E6-89B0-235CF4978C17> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fffab77b000 -     0x7fffab77bfff  com.apple.quartzframework (1.5 - 21) <09455972-8A33-3D61-B193-BA7E7CF984CA> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fffab77c000 -     0x7fffab97cfff  com.apple.QuartzCore (1.11 - 453.39.4) <A45AFBC4-87D4-3533-A0AC-1D6629C77984> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fffabee3000 -     0x7fffac1e5ff7  com.apple.security (7.0 - 57740.60.18) <005E8C96-40B6-35E3-B58B-888A5F5957C2> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fffac25c000 -     0x7fffac285fff  com.apple.securityinterface (10.0 - 55079.50.4) <C9B0E11A-362B-3C0D-8B2E-B06510BCE20A> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fffb9e48000 -     0x7fffb9e49ffb  libSystem.B.dylib (1238.60.2) <F18AC1E7-C6F1-34B1-8069-BE571B3231D4> /usr/lib/libSystem.B.dylib
    0x7fffb9ffb000 -     0x7fffba051ff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib

Model: MacBookPro8,2, BootROM MBP81.0047.B3A, 4 processors, Intel Core i7, 2,2 GHz, 16 GB, SMC 1.69f3
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In
Graphics: AMD Radeon HD 6750M, AMD Radeon HD 6750M, PCIe, 1024 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x029E, 0x434D5358384758334D314131363030433130
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x029E, 0x434D5358384758334D314131363030433130
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (5.106.98.100.26)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SanDisk Ultra II 960GB, 960,2 GB
USB Device: USB 2.0 Bus
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Hub
USB Device: Hub in Apple Pro Keyboard
USB Device: Apple Pro Keyboard
USB Device: Hub
USB Device: PTK-440
USB Device: USB Laser Mouse
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: iPhone
USB Device: IR Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.1
```
