### ISSUE TITLE
Pasting code often causes cascading pastes

### ISSUE THREAD

**Issue by karai17** [atom/atom#6579] opened 2015-04-30 13:54 UTC
Screenshots below, basically when I copy and paste a line of code, I more-often-than-not get this cascading effect that is quite frustrating as I need to realign lines (or blocks) of code when I deliberately copied a prefixed new line so I could just hold paste.

**COPY**

![](http://puu.sh/hwgQZ/b2f88233bc.png)

**PASTE**

![](http://puu.sh/hwgTu/39d856aa88.png)

**EXPECTED**

![](http://puu.sh/hwh2B/f92d904458.png)

**Comment by izuzak** [comment] 2015-04-30 14:02
I think this is a duplicate of https://github.com/atom/atom/issues/5473 -- please subscribe to that issue for updates and let me know if I misunderstood your report. Thanks!

**Closed by izuzak** 2015-04-30 14:02 UTC
