### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 571Error: Cannot cal...

### ISSUE THREAD

**Issue by xtianXshang** [atom/atom#19884] opened 2019-09-06 08:33 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 571
Error: Cannot call function 'getPosition' on missing remote object 571
    at throwRPCError (C:\Users\roie\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\roie\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\roie\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At C:\Users\roie\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 571
Error: Cannot call function 'getPosition' on missing remote object 571
    at throwRPCError (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:731570)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:731985)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -1:57.9.0 core:save (input.hidden-input)
     -1:57 emmet:insert-formatted-line-break-only (input.hidden-input)
  4x -1:44.2.0 core:backspace (input.hidden-input)
     -1:43 autocomplete-plus:confirm (input.hidden-input)
     -1:43 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -1:42.1.0 core:undo (input.hidden-input)
     -1:40 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:32.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:32.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:30.5.0 core:save (input.hidden-input)
     -1:25.5.0 core:cut (input.hidden-input)
     -1:25.3.0 core:save (input.hidden-input)
 12x -0:34.1.0 core:backspace (input.hidden-input)
     -0:24 autocomplete-plus:confirm (input.hidden-input)
     -0:23.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:20.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
aemi-dark-ui 1.0.3 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
auto-close-html2 0.7.0 
auto-save-on-idle 1.2.1 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
b-bootstrap-autocomplete 0.4.6 
close-tags 0.6.0 
dark-flat-ui-mxml 1.3.0 
dark-one-dark-syntax 2.3.0 
emmet 2.4.3 
fega-high-contrast-syntax 2.0.1 
highlight-selected 0.16.0 
ide-php 0.7.18 
jQuery 1.2.6 
minimap 4.29.9 
nil-syntax 0.1.0 
nv-dark-syntax 1.4.1 
nv-dark-ui 3.0.8 
open-recent 5.0.0 
pacific-dark 0.5.0 
php-hyperclick 1.2.1 
pigments 0.40.2 
rzx-dark-ui 1.1.0 
turbo-javascript 1.4.0 
ubik-gotham-syntax 1.2.0 
zhk-dark-syntax 0.3.1 
```

**Comment by rsese** [comment] 2019-09-06 22:12
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-09-06 22:12 UTC
Labels: duplicate
