### ISSUE TITLE
Uncaught Error: The module '/usr/share/atom/resources/app.asar.unpacked/node_modules/tree-sitter/...

### ISSUE THREAD

**Issue by tlowrimore** [atom/atom#22916] opened 2021-08-31 20:39 UTC
[Enter steps to reproduce:]

1. Create a "New" file
2. Paste valid JSON into the new file
3. Set the grammar for the file to "JSON"
4. Receive the error message below

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Pop!_OS 21.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The module '/usr/share/atom/resources/app.asar.unpacked/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

```
At /usr/share/atom/resources/app.asar/node_modules/tree-sitter/index.js:8

Error: The module '/usr/share/atom/resources/app.asar.unpacked/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149207)
    at /app.asar/node_modules/tree-sitter/index.js:3:13)
    at /app.asar/node_modules/tree-sitter/index.js:757:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at get_Parser (/usr/share/atom/resources/app/static/<embedded>:11:3289020)
    at Function._patchSyntaxNode (/usr/share/atom/resources/app/static/<embedded>:11:3289528)
    at new TreeSitterLanguageMode (/usr/share/atom/resources/app/static/<embedded>:11:3289784)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/usr/share/atom/resources/app/static/<embedded>:11:358401)
    at GrammarRegistry.assignGrammar (/usr/share/atom/resources/app/static/<embedded>:11:357922)
    at Object.didConfirmSelection (/usr/share/atom/resources/app/static/<embedded>:11:830790)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/static/<embedded>:14:733654)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/static/<embedded>:14:728533)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:352326)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1227728)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1223862)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -1:14 application:new-file (input.hidden-input)
     -1:11.3.0 editor:paste-without-reformatting (input.hidden-input)
     -1:10.3.0 grammar-selector:show (input.hidden-input)
     -1:08.2.0 core:confirm (input.hidden-input)
     -0:52 atom-beautify:beautify-editor (input.hidden-input)
     -0:45.8.0 grammar-selector:show (input.hidden-input)
     -0:42.8.0 core:confirm (input.hidden-input)
  2x -0:16.9.0 console:toggle (input.hidden-input)
     -0:08.9.0 grammar-selector:show (input.hidden-input)
     -0:05.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-typescript 14.3.2 
file-types 1.0.1 
ide-svelte 0.1.1 
language-elixir 0.24.0 
language-pug 0.0.22 
language-rust 0.4.12 
```

**Comment by icecream17** [comment] 2021-09-01 15:21
This is kinda related to https://github.com/atom/atom/issues/22129

It just means atom's version of tree-sitter-json is outdated compared to your version of node, and doesn't have to do with the contents of the json file
https://github.com/atom/language-json/blob/master/package.json#L22

**Comment by sadick254** [comment] 2021-09-01 17:39
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/22129. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2021-09-01 17:39 UTC
