### ISSUE TITLE
Shortcut for close file (macOS 10.12)

### ISSUE THREAD

**Issue by pustovalov** [atom/atom#12948] opened 2016-10-11 23:57 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Can't close new file without saving

### Steps to Reproduce

1. Create new file
2. Write something
3. Cmd + W
4. Cmd + D

[Video](https://monosnap.com/file/QV7psgRz1Fb5Z6PhMzmRZXB4ryGCXw)

**Expected behavior:** Close file

**Actual behavior:** Nothing

### Versions

Atom    : 1.11.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by 50Wliu** [comment] 2016-10-12 00:38
This is a duplicate of #12277 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-12 00:38 UTC
