### ISSUE TITLE
Right-to-left text support [enhancement]

### ISSUE THREAD

**Issue by latach** [atom/atom#17276] opened 2018-05-05 00:14 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is a request to provide right to left text support, as in gedit in the following snapshot:
![image](https://user-images.githubusercontent.com/21196400/39657623-9a8ef15e-5001-11e8-9674-4eaa438fbb1a.png)

### Steps to Reproduce

1. Write some text in English.
2. Press enter, and type some text in Arabic/Hebrew/Other-right-to-left-language.
3. The text will be inverted. You won't be able to highlight parts of the written text using the mouse.

**Expected behavior:** 

To invert the writing direction once a right-to-left language is detected. This should be done (as in gedit) on the visual level (i.e. it isn't necessary to modify any data in the saved file).

**Actual behavior:**

A right-to-left language is written on the opposite side of the line.

**Reproduces how often:**

%100

### Versions

Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-05-07 19:45
Thanks for contributing!

We noticed that this is a duplicate of issues like https://github.com/atom/atom/issues/12282 and https://github.com/atom/atom/issues/10132 - you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-07 19:45 UTC
