### ISSUE TITLE
Uncaught Error: ENOENT,  not found in /Applications/Atom.app/Contents/Resources/app.asar

### ISSUE THREAD

**Issue by Mech7** [atom/atom#6576] opened 2015-04-30 10:25 UTC
[Enter steps to reproduce below:]

1. Try to open /Applications/Atom.app/Contents/Resources/app.asar

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT,  not found in /Applications/Atom.app/Contents/Resources/app.asar

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:457

Error: ENOENT,  not found in /Applications/Atom.app/Contents/Resources/app.asar
    at createNotFoundError (ATOM_SHELL_ASAR.js:101:13)
    at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:156:25)
    at ReadStream.open (fs.js:1668:6)
    at new ReadStream (fs.js:1655:10)
    at Object.fs.createReadStream (fs.js:1610:10)
    at File.module.exports.File.read (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:286:27)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:948:61)
    at TextBuffer.module.exports.TextBuffer.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:974:19)
    at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:446:21)
    at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:416:63)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-04-30 11:14
Just to elaborate, did you try opening `/Applications/Atom.app/Contents/Resources/app.asar` inside Atom?

**Comment by 50Wliu** [comment] 2015-04-30 16:49
Looks like it's trying to open a blank file...?  There's no file listed :confused:

**Comment by kevinsawicki** [comment] 2015-04-30 16:56
I think this might be a duplicate of https://github.com/atom/atom/issues/6140

Opening `app.asar` or `atom.asar` in Atom currently has issues.

**Closed by kevinsawicki** 2015-04-30 16:56 UTC
Labels: more-information-needed
