### ISSUE TITLE
Opening big file like jquery-UI.min.js freeze editor

### ISSUE THREAD

**Issue by yihaa5** [atom/atom#7634] opened 2015-07-01 17:51 UTC
Hi Guys,
Not sure if anyone having this issue. I tried to open a jquery-ui.min.js file in the editor. It loaded and hang for like 30++ seconds before i can start editing the file.

**Comment by mnquintana** [comment] 2015-07-01 17:52
This looks like a duplicate of https://github.com/atom/atom/issues/979 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-01 17:52 UTC

**Comment by yihaa5** [comment] 2015-07-01 18:02
Subscribed . Thanks
