### ISSUE TITLE
Git not fetching profile image (Gitlab)

### ISSUE THREAD

**Issue by sebastianks** [atom/atom#19461] opened 2019-06-06 15:34 UTC
When I use the Git tool with a repository on Gitlab, it's showing some default profile image instead of the one I've set on Gitlab.

I've tried to set the `git config` both for global and local without any luck.

In Visual Studio Code it's working as intended, and also if I use the terminal to push.

Versions:

Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by Arcanemagus** [comment] 2019-06-06 16:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/github/issues/1924. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-06-06 16:22 UTC

**Comment by sebastianks** [comment] 2019-06-06 19:26
Hey @arcanemagus

I really don't see how it's a duplicate of the issue you are referring to? Mine is about a profile image (avatar) and not the repo it self. The repo works as it should in Atom - except for the avatar.

**Comment by Arcanemagus** [comment] 2019-06-06 19:38
Avatars are pulled from the GitHub API... which obviously doesn't work for GitLab accounts since they are an entirely different platform. As outlined in that issue somebody _could_ create a GitLab based package, but nobody has done so so far to my knowledge.

**Comment by sebastianks** [comment] 2019-06-07 06:34
@Arcanemagus Hmm, I have two colleagues in my team, and I can see their image on their commits, and they are using Gitlab too, so I don't understand how that's possible?

One colleague might have a Github account on the same e-mail, but the other guy doesn't.
