### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by AVD087** [atom/atom#15837] opened 2017-10-07 12:41 UTC
### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\***\AppData\Local\atom\app-1.22.0-beta0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\***\AppData\Local\atom\app-1.22.0-beta0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.22.0-beta0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -0:54.2.0 editor:select-to-beginning-of-word (input.hidden-input)
  2x -0:53.7.0 editor:select-to-end-of-word (input.hidden-input)
     -0:53.2.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:52.5.0 core:select-right (input.hidden-input)
  2x -0:52.3.0 intentions:highlight (input.hidden-input)
     -0:51.2.0 core:undo (input.hidden-input)
     -0:50.8.0 intentions:highlight (input.hidden-input)
  7x -0:50 editor:move-to-end-of-word (input.hidden-input)
  4x -0:48.6.0 core:move-right (input.hidden-input)
     -0:47.5.0 core:select-right (input.hidden-input)
  2x -0:47.3.0 intentions:highlight (input.hidden-input)
     -0:42.8.0 core:backspace (input.hidden-input)
     -0:40.3.0 intentions:highlight (input.hidden-input)
     -0:39.9.0 core:save (input.hidden-input)
     -0:22.1.0 intentions:highlight (input.hidden-input)
     -0:21.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
apex-ui 1.0.1 
ask-stack 2.2.0 
atom-beautify 0.30.5 
atom-bootstrap4 1.4.0 
atom-clock 0.1.15 
atom-html-preview 0.2.2 
atom-ide-ui 0.4.0 
atom-material-syntax 1.0.6 
atom-minify 0.8.0 
atom-minify-stand-alone 0.2.0 
atom-sort-sass 0.2.1 
autocomplete-nunjucks 0.5.0 
autocomplete-paths 2.11.0 
autoupdate-packages 1.3.1 
best-js-snippets 4.1.0 
bootstrap-sass-snippets 2.1.1 
busy-signal 1.4.3 
cdnjs 1.5.5 
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
css-grid-snippets 1.0.9 
css-snippets 1.1.0 
csscomb 0.3.1 
dash-ui 0.4.3 
emmet 2.4.3 
file-icons 2.1.12 
flexbox-snippets 0.3.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
gulp-control 0.5.0 
hex-to-sass 0.2.0 
html-to-css 0.2.2 
ide-css 0.2.0 
imdone-atom 2.2.7 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-markdown 0.25.1 
language-nunjucks 4.1.0 
language-postcss 1.3.1 
linter 2.2.0 
linter-sass-lint 1.8.2 
linter-ui-default 1.6.10 
loved-syntax 1.0.2 
markdown-pdf 2.1.0 
markdown-preview-plus 2.4.10 
minimap 4.29.7 
pigments 0.40.2 
pure-syntax 0.3.0 
sass-autocompile 0.13.3 
sass-code-kit 0.4.2 
sass-comment 1.4.0 
scroll-through-time 0.2.0 
sync-settings 0.8.3 
tidy-markdown 3.0.1 
v-bootstrap4 0.1.8 
```

**Comment by mpboom** [comment] 2017-10-07 14:52
Could you give a bit more information about this? When does this occur?

Also, you might want to fill out the issue template since that is a requirement for creating issues.

**Comment by rsese** [comment] 2017-10-09 17:36
I think this might be a duplicate of recent issues like https://github.com/atom/atom/issues/15722.  If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled.  If you don't have any anti-virus software, let me know.

**Closed by rsese** 2017-10-09 17:36 UTC
Labels: duplicate
