### ISSUE TITLE
Cannot install Atom on win7

### ISSUE THREAD

**Issue by floriansegginger** [atom/atom#10285] opened 2016-01-05 14:28 UTC
I tried installing Atom using the handy installer (1.3.2.0) but it stops dead in its tracks on my Windows 7 box.

It exits with the "Installation has failed" message.

I've looked around on these "forums" a bit, and I can tell you that:

 * My AntiVirus is Microsoft Security Essentials, with disabled real-time protection
 * I have full administrator rights on this machine
 * I did not previously try to install Atom 

I will install it manually, but I think the devs need to fix this urgently as most people will not have the patience necessary to do that :)

Here is my Setup Log. I "censored" my User directory for security reasons:

	2016-01-05 15:21:04> Program: Starting Squirrel Updater: --install .
	2016-01-05 15:21:04> Program: Starting install, writing to C:\Users\fXXXXXX.XXXXXXXX.XXXXT\AppData\Local\SquirrelTemp
	2016-01-05 15:21:04> Program: About to install to: C:\Users\fXXXXXX.XXXXXXXX.XXXXT\AppData\Local\atom
	2016-01-05 15:21:04> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\fXXXXXX.XXXXXXXX.XXXXT\AppData\Local\atom\packages\RELEASES'.
	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
	   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
	   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3d.MoveNext()
	2016-01-05 15:21:04> CheckForUpdateImpl: Reading RELEASES file from C:\Users\fXXXXXX.XXXXXXXX.XXXXT\AppData\Local\SquirrelTemp
	2016-01-05 15:21:04> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
	2016-01-05 15:21:04> ApplyReleasesImpl: Writing files to app directory: C:\Users\fXXXXXX.XXXXXXXX.XXXXT\AppData\Local\atom\app-1.3.2
	2016-01-05 15:21:09> IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
	   at System.IO.PathHelper.GetFullPathName()
	   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
	   at System.IO.Path.GetFullPathInternal(String path)
	   at System.IO.Path.GetFullPath(String path)
	   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
	   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
	   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a8>d__b8.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
	2016-01-05 15:21:09> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
	   at System.IO.PathHelper.GetFullPathName()
	   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
	   at System.IO.Path.GetFullPathInternal(String path)
	   at System.IO.Path.GetFullPath(String path)
	   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
	   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
	   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a8>d__b8.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__78.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	   at Squirrel.Update.Program.<Install>d__37.MoveNext()
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at System.Threading.Tasks.Task.Wait()
	   at Squirrel.Update.Program.executeCommandLine(String[] args)
	   at Squirrel.Update.Program.main(String[] args)
	---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
	   at System.IO.PathHelper.GetFullPathName()
	   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
	   at System.IO.Path.GetFullPathInternal(String path)
	   at System.IO.Path.GetFullPath(String path)
	   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
	   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
	   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a8>d__b8.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__78.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
	   at Squirrel.Update.Program.<Install>d__37.MoveNext()<---

**Comment by Zireael07** [comment] 2016-01-05 14:57
>System.IO.PathTooLongException

How long is your username? Does it include non-English characters?

**Comment by floriansegginger** [comment] 2016-01-05 15:00
> How long is your username? Does it include non-English characters?

Exactly the amount of characters I replaced with X's

That means 22 characters, and no special ones except the dots.

**Comment by batjko** [comment] 2016-01-05 15:06
Not sure if the dots are a problem. I seem to remember that others have similar usernames and installed just fine.

Is your user directly redirected to a different (network?) location by any chance?

**Comment by floriansegginger** [comment] 2016-01-05 15:08
> Is your user directory redirected to a different (network?) location by any chance?

Nope. It's just a regular old directory.

**Comment by allysonsouza** [comment] 2016-02-02 15:14
Same issue here, Win7 Portuguese-BR. There's some fix for it?

**Comment by 50Wliu** [comment] 2016-02-02 17:05
This is a duplicate of #5109 - please subscribe there for updates.  There's also some workarounds there that you can try.

**Closed by 50Wliu** 2016-02-02 17:05 UTC
