### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by dapperAuteur** [atom/atom#16981] opened 2018-03-19 02:21 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:652

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:652:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:649:43)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:590:18)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:566:18)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:511:20)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:384:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didMouseWheel (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1553:59)
```

### Commands

```
     -7:13 editor:toggle-line-comments (input.hidden-input)
     -7:08.3.0 editor:select-to-end-of-line (input.hidden-input)
     -7:07.5.0 core:copy (input.hidden-input)
     -7:04.1.0 editor:toggle-line-comments (input.hidden-input)
     -7:03.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -7:02.2.0 editor:newline (input.hidden-input)
     -7:01.7.0 core:paste (input.hidden-input)
     -6:57.2.0 core:save (input.hidden-input)
  3x -1:47.1.0 tree-view:toggle (input.hidden-input)
     -0:59.6.0 core:undo (input.hidden-input)
     -0:55.3.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-elixir 0.2.3 
atom-html-templates 0.1.3 
atom-typescript 12.3.7 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.17 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-elixir 0.22.0 
language-elm 1.5.0 
language-vue 0.23.1 
linter 2.2.0 
linter-ui-default 1.7.1 
pigments 0.40.2 
react 0.18.0 
react-snippets 1.0.1 
vim-mode-plus 1.30.1 
```

**Comment by hg42** [comment] 2018-03-19 04:08
I also get this with 1.26.0-beta0

**Comment by rsese** [comment] 2018-03-19 20:45
Thanks for the report - this looks like a duplicate of #16179 so you can subscribe there for updates if you'd like. If you remember what you were doing at the time of the error or if you can reproduce, please let us know in #16179. Also, do you happen to remember if you tabbed out of Atom and then switched back when you saw the error?

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by rsese** 2018-03-19 20:45 UTC
