### ISSUE TITLE
The editor has crashed in all mode

### ISSUE THREAD

**Issue by juvevood** [atom/atom#11507] opened 2016-04-18 02:34 UTC
I tried safe mode and development mode will not work. 
```
/usr/bin/atom: line 123:  1401 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ $ATOM_USER_FLAGS "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 324ms
Failed to get crash dump id.
Report Id: 

```
and my --version:
```
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```
and my system 
```
archlinux 
gnome3.20
```

**Comment by AndreRoehrig** [comment] 2016-04-18 10:31
same issue here with the same versions.

system:
```
archlinux
i3
```

**Comment by ijanos** [comment] 2016-04-18 10:34
Duplicate of #11501

**Closed** 2016-04-18 12:41 UTC

**Comment by 50Wliu** [comment] 2016-04-18 12:43
Actually, I think this is a duplicate of #11198.
