### ISSUE TITLE
Excessive disk reads while Atom is open

### ISSUE THREAD

**Issue by jfsantos** [atom/atom#6571] opened 2015-04-29 17:35 UTC
I'm using Atom on Linux Mint 17. Whenever I open Atom, I noticed my HDD led blinking like crazy. iotop shows atom is doing a lot of disk reads:

```
 5241 be/4 jfsantos    6.48 M/s    0.00 B/s  0.00 % 37.54 % atom --ev~trap.js');
 5242 be/4 jfsantos    5.75 M/s    0.00 B/s  0.00 % 36.67 % atom --ev~trap.js');
 5244 be/4 jfsantos    4.75 M/s    0.00 B/s  0.00 % 32.67 % atom --ev~trap.js');
 5243 be/4 jfsantos    3.83 M/s    0.00 B/s  0.00 % 30.87 % atom --ev~trap.js');
```

As soon as I close Atom, everything gets back to normal (iotop shows 0.00 B/s as total disk reads, as opposed to something around 12 M/s with atom running). I tried disabling all 3rd party plugins I downloaded but it did not help. Is there anything I could do to help investigating this issue?

**Comment by lee-dohm** [comment] 2015-04-30 05:05
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by m1ga** [comment] 2015-04-30 13:44
might be related: https://github.com/atom/atom/issues/5566

**Comment by jfsantos** [comment] 2015-04-30 13:51
I am using 0.194.0. Starting atom with `atom --safe` also triggers the bug, but I found something else: if I start Atom from another folder that's not my home folder (from the command line), this behavior does not happen, even if it's a directory full of "deep" directory trees. I tried disabling the option "follow symlinks" but it does not make any difference.

**Comment by m1ga** [comment] 2015-04-30 13:53
does the disc-access go away after a minute? or is running the whole atom session?

**Comment by jfsantos** [comment] 2015-04-30 14:01
No, I've been running it on safe mode without doing anything and the disc access has been high for the last 4 minutes. There's nothing else running on my computer that would compete "agressively" for resources with Atom, so maybe this is not the same as #5566.

**Comment by kevinsawicki** [comment] 2015-07-21 18:58
I believe this is a duplicate of #5566 since these do look like the processes that Atom spawns at startup that were mentioned as well on that issue.

**Closed by kevinsawicki** 2015-07-21 18:58 UTC
Labels: more-information-needed

**Comment by JamesHealdUK** [comment] 2016-12-28 18:30
The latest Atom 1.12.7 seems to be doing this for me as well on Ubuntu 16.10, makes my entire computer almost unusable after a while. iotop says that its using 99% of my IO, any solutions? I've tried waiting but doesnt do a thing...

It did just stop for a few seconds but its now continued reading like crazy again.

I really want Atom back but its sadly unusable right now.
