### ISSUE TITLE
Blurry text when scrolling down on Windows7 with display scaling for 1.19.0

### ISSUE THREAD

**Issue by blurainer** [atom/atom#15180] opened 2017-08-07 07:56 UTC
This issue is still inside the latest beta7, the text is blurred if scrolled down with mouse on Windows7 with display scaling, and still blurry when stop scrolling. But it will clear again if you scroll up with one step. No issue for static text.
No such issue in 1.18
Scaling: "Control Panel\Appearance and Personalization\Display" to set to 115%

**Comment by redwon** [comment] 2017-08-09 07:00
And other elements are also blurred.
The panels visually become larger.
No such issue in 1.18.
Windows 10. Laptop 15.6' 1920x1080

**Comment by redwon** [comment] 2017-08-09 07:14
1.18 screenshot
![default](https://user-images.githubusercontent.com/16374396/29109297-3c59c9fe-7ceb-11e7-9c57-13ef424aff45.png)
1.19 screenshot
![default](https://user-images.githubusercontent.com/16374396/29109383-78c5fc28-7ceb-11e7-9e75-8c325abbf02b.png)

**Comment by alxio** [comment] 2017-08-09 12:26
Same problem for me,

Maybe I have solution:
In text-editor-component.js there is line 546:
style.transform = `translate(${-this.getScrollLeft()}px, ${-this.getScrollTop()}px)`
I would try rounding this values to whole pixels (with Math.floor() for example)

However don't know how to change it and build Atom to see changes.

**Comment by alexdevero** [comment] 2017-08-10 05:58
This is at least partially related to https://github.com/atom/atom/issues/14824.

**Comment by 50Wliu** [comment] 2017-08-10 12:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14237. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-10 12:52 UTC
