### ISSUE TITLE
Distribute through snaps (no repositories/distro difficulties)

### ISSUE THREAD

**Issue by janat08** [atom/atom#14409] opened 2017-05-13 18:12 UTC
snapcraft.io
"Package any app for every Linux desktop, server, cloud or device, and deliver updates directly."

**Comment by janat08** [comment] 2017-05-13 18:14
#2956 #6509

**Comment by lee-dohm** [comment] 2017-05-13 21:20
Thank you for contributing!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13298, which is also a duplicate of https://github.com/atom/atom/issues/2956. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2017-05-13 21:20 UTC

**Comment by janat08** [comment] 2017-05-13 22:03
It is not closely related, since it is distro agnostic and isn't repository.
