### ISSUE TITLE
Uncaught TypeError: Invalid Point: (17, NaN)

### ISSUE THREAD

**Issue by FabioDa10** [atom/atom#16674] opened 2018-02-02 19:21 UTC
Sorry I didn't follow all the steps in the guide, but I'm working and cannot make much debug.

It's a week or so I'm getting this kind of error:
`Uncaught TypeError: Invalid Point: (?, NaN)`

I'm moving cursor in a PHP file, after a global search (not immediately after), and in **some** files the found words are not correctly highlited (1 to 8 char BEFORE the actual occurrence, with much variance), and the cursor position on **some** lines (not only those with results) is ugly: moving to first char of line gets the cursor "inside" the first tab (i'm using 4 char, HARD tab), moving to last char of line gets the cursor somewhere but NOT on last char.

In the following screenshot, you can see the cursor in both first and last char on line 18: the real char are "18:2" and "18:45", while they should be "18:1" and "18:48", so it looks like the "hard tab" are lost:
![atom_editor_2018-02-02](https://user-images.githubusercontent.com/3191008/35750706-3281ca2a-0856-11e8-9776-3afd8914db33.jpg)

After some cursor moves on those buffers, I get the "Invalid Point" error.
No other messages in the dev tools.

I think that the only "non standard" thing to underline is that the project I'm workin now is in "latin1" using .editorconfig
```
root = true
[*]
end_of_line = crlf
charset = latin1

```
Default "File Encoding" is now set to "UTF-8" but I had same problem when set to ISO-8859-1, and I'm quite sure I had same issue while working on a complete UTF-8 project.

"php-integrator" is linting with last php7.2 binaries on Windows

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version [Actually "Windows 10 Pro x64 build 1709"]
**Thrown From**: Atom Core

### Stack Trace 1

Uncaught TypeError: Invalid Point: (581, NaN)

```
At C:\Program Files\Atom x64\resources\app\node_modules\text-buffer\lib\text-buffer.js:948

TypeError: Invalid Point: (581, NaN)
    at Function.module.exports.Point.assertValid (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-layer.js:347:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-marker.js:154:58)
    at changePosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:68:25)
    at Cursor.changePosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:713:11)
    at Cursor.setScreenPosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:67:16)
    at Cursor.moveLeft (C:/Program Files/Atom x64/resources/app/src/cursor.js:288:18)
    at moveCursors.cursor (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2539:52)
    at Array.forEach (native)
    at transact (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2681:31)
    at TextBuffer.module.exports.TextBuffer.transact (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextEditor.transact (C:/Program Files/Atom x64/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2680:23)
    at TextEditor.moveLeft (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2539:23)
    at TextEditor.core:move-left (C:/Program Files/Atom x64/resources/app/src/register-default-commands.js:324:27)
    at HTMLElement.newCommandListeners.(anonymous function) (C:/Program Files/Atom x64/resources/app/src/register-default-commands.js:665:38)
    at CommandRegistry.handleCommandEvent (C:/Program Files/Atom x64/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:/Program Files/Atom x64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:/Program Files/Atom x64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (C:/Program Files/Atom x64/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:26.8.0 core:paste (input.hidden-input)
  3x -0:25.7.0 intentions:highlight (input.hidden-input)
  2x -0:25.4.0 core:undo (input.hidden-input)
     -0:23.6.0 intentions:highlight (input.hidden-input)
     -0:23.4.0 core:undo (input.hidden-input)
     -0:20.2.0 editor:move-to-first-character-of-line (input.hidden-input)
  3x -0:19.8.0 core:move-up (input.hidden-input)
     -0:19 core:move-right (input.hidden-input)
     -0:18.6.0 core:select-down (input.hidden-input)
     -0:17.6.0 core:move-up (input.hidden-input)
     -0:17.2.0 core:move-right (input.hidden-input)
     -0:16.8.0 core:move-down (input.hidden-input)
 10x -0:16.1.0 core:move-right (input.hidden-input)
     -0:13.2.0 core:move-left (input.hidden-input)
  4x -0:12.8.0 core:move-right (input.hidden-input)
  2x -0:11.2.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.7.2 
atom-minify 0.8.0 
autoclose-html 0.23.0 
autocomplete-ionic2-framework 0.3.2 
busy-signal 1.4.3 
config-import-export 0.3.1 
custom-title 1.0.1 
docblockr 0.13.6 
double-click-tree-view 1.1.0 
editor-settings 1.1.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.16 
git-plus 7.10.0 
grammar-token-limit 0.1.1 
hyperclick 0.0.0 
intentions 1.1.5 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
minimap 4.29.7 
php-debug 0.2.6 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.2 
php-integrator-base 3.1.0 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-integrator-tooltips-legacy-php56 1.1.6 
php-light-syntax 1.0.2 
pigments 0.40.2 
project-manager 3.3.5 
project-plus 1.0.0 
project-sidebar 1.3.0 
remote-sync 4.1.8 
tabs-to-spaces 1.0.3 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.4.0 
```

-----

### Stack Trace 2

Uncaught TypeError: Invalid Point: (17, NaN)

```
At C:\Program Files\Atom x64\resources\app\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: (17, NaN)
    at Function.module.exports.Point.assertValid (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-layer.js:347:17)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.translateScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:163:38)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/display-marker.js:154:58)
    at changePosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:68:25)
    at Cursor.changePosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:713:11)
    at Cursor.setScreenPosition (C:/Program Files/Atom x64/resources/app/src/cursor.js:67:16)
    at Cursor.moveLeft (C:/Program Files/Atom x64/resources/app/src/cursor.js:288:18)
    at moveCursors.cursor (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2539:52)
    at Array.forEach (native)
    at transact (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2681:31)
    at TextBuffer.module.exports.TextBuffer.transact (C:/Program Files/Atom x64/resources/app/node_modules/text-buffer/lib/text-buffer.js:941:24)
    at TextEditor.transact (C:/Program Files/Atom x64/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2680:23)
    at TextEditor.moveLeft (C:/Program Files/Atom x64/resources/app/src/text-editor.js:2539:23)
    at TextEditor.core:move-left (C:/Program Files/Atom x64/resources/app/src/register-default-commands.js:324:27)
    at HTMLElement.newCommandListeners.(anonymous function) (C:/Program Files/Atom x64/resources/app/src/register-default-commands.js:665:38)
    at CommandRegistry.handleCommandEvent (C:/Program Files/Atom x64/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:/Program Files/Atom x64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:/Program Files/Atom x64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (C:/Program Files/Atom x64/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -5:40.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -5:19.6.0 project-find:show (input.hidden-input)
     -5:18.6.0 find-and-replace:show (input.hidden-input)
     -5:17.6.0 core:confirm (input.hidden-input)
     -0:27 core:backspace (input.hidden-input)
  3x -0:25.8.0 core:move-left (input.hidden-input)
     -0:24.9.0 core:delete (input.hidden-input)
     -0:24.3.0 core:move-right (input.hidden-input)
     -0:24 core:delete (input.hidden-input)
     -0:22.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:22.6.0 core:move-right (input.hidden-input)
  7x -0:21.3.0 intentions:highlight (input.hidden-input)
     -0:20.9.0 core:save (input.hidden-input)
     -0:13.8.0 core:confirm (input.hidden-input)
  3x -0:10 core:move-left (input.hidden-input)
 20x -0:08.8.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.7.2 
atom-minify 0.8.0 
autoclose-html 0.23.0 
autocomplete-ionic2-framework 0.3.2 
busy-signal 1.4.3 
config-import-export 0.3.1 
custom-title 1.0.1 
docblockr 0.13.6 
double-click-tree-view 1.1.0 
editor-settings 1.1.3 
editorconfig 2.2.2 
file-icons 2.1.16 
git-plus 7.10.0 
grammar-token-limit 0.1.1 
hyperclick 0.0.0 
intentions 1.1.5 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
minimap 4.29.7 
multirow-tabs 0.3.3 
php-debug 0.2.6 
php-integrator-annotations 1.2.0 
php-integrator-base 3.2.0 
php-integrator-call-tips-legacy-php56 1.2.3 
php-integrator-linter-legacy-php56 1.3.1 
php-integrator-refactoring 1.4.1 
php-integrator-tooltips-legacy-php56 1.1.6 
php-light-syntax 1.0.2 
pigments 0.40.2 
project-manager 3.3.5 
project-plus 1.0.0 
project-sidebar 1.3.0 
remote-sync 4.1.8 
tabs-to-spaces 1.0.3 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.4.0 
```

**Comment by rsese** [comment] 2018-02-05 23:22
Thanks for the report - based on the stack trace I think this is a duplicate of https://github.com/atom/atom/issues/14774.  I'll copy your comment over and you can subscribe there for updates if you'd like.

**Closed by rsese** 2018-02-05 23:22 UTC
