### ISSUE TITLE
'alt-d': 'native!' #doesn't work

### ISSUE THREAD

**Issue by jamesonquinn** [atom/atom#12016] opened 2016-06-21 13:17 UTC
### Description

I set my keymap.cson to include 'alt-d': 'native!' because on my OSX keyboard, option-d is how I type "(". This gets a left paren, but it also deletes from the cursor to the end of the word.

### Steps to Reproduce

1. 'alt-d': 'native!' in keymap
2. go to middle of a word
3. press option-d (on a mac)
4. you get the native character to the left of the cursor as expected, but the rest of the word to the right of the cursor is deleted.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

1.8.0
1.9.0-beta0

**Comment by lee-dohm** [comment] 2016-06-29 23:45
This appears to be a duplicate of atom/atom-keymap#35. You may want to subscribe there for updates. Also, some people have reported success with the [keyboard-localization package](https://atom.io/packages/keyboard-localization) in solving these kinds of issues.

Let me know if I misunderstood and I'll be happy to reopen the Issue!

**Closed by lee-dohm** 2016-06-29 23:45 UTC
