### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/jovanalleyne/Documents/Projects/node-project/project.json'

### ISSUE THREAD

**Issue by jalleyne** [atom/atom#5062] opened 2015-01-14 19:52 UTC
[Enter steps to reproduce below:]

1. close atom
2. open atom

**Atom Version**: 0.172.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/jovanalleyne/Documents/Projects/node-project/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/jovanalleyne/Documents/Projects/node-project/project.json'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs",
      "tree-view"
    ]
  },
  "editor": {
    "fontSize": 11,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.1.3
coffee-compile, v0.8.4
color-picker, v1.2.6
git-log, v0.2.0
highlight-selected, v0.6.3
language-jade, v0.3.0
language-nginx, v0.4.0
linter, v0.9.0
linter-less, v0.3.1
minimap, v3.4.7
minimap-find-and-replace, v3.0.4
minimap-git-diff, v3.0.11
minimap-highlight-selected, v3.0.0
minimap-selection, v3.0.1
pretty-json, v0.3.1
quick-move-file, v0.7.0
recent-files, v0.3.0
save-session, v0.11.0
sublime-tabs, v0.4.8
travis-ci-status, v0.11.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-01-14 19:54
This looks like a duplicate of https://github.com/mpeterson2/save-session/issues/43 which should be fixed if you upgrade the `save-session` package.

**Closed by kevinsawicki** 2015-01-14 19:54 UTC

**Comment by jalleyne** [comment] 2015-01-14 19:57
thanks, was actually doing that when i noticed you closed it.
