### ISSUE TITLE
Question : already install plugin can search and show!

### ISSUE THREAD

**Issue by crperlin** [atom/atom#8910] opened 2015-09-23 16:48 UTC
I found my `settings - >　plugins` have 51 plugins ; but max show 6 plugin .. other plugin can search and  show ~~~ 

OS :  win10
Atom version : 1.0.15

**Comment by mnquintana** [comment] 2015-09-23 17:22
Thanks for the report! This looks like a duplicate of https://github.com/atom/settings-view/issues/591 - please subscribe there for updates.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Closed by mnquintana** 2015-09-23 17:22 UTC
