### ISSUE TITLE
After updating to 1.12.1 the command line binaries were no longer present.

### ISSUE THREAD

**Issue by tedivm** [atom/atom#13204] opened 2016-11-11 23:09 UTC
### Description

After updating to 1.12.1 the command line binaries were no longer present.

Running "Install Shell Commands" returns no errors, but also does not actually install the shell commands.

### Steps to Reproduce

1. Update to 1.12.1
2. Run `Install Shell Commands`

**Expected behavior:** Shell commands should be accessible.

**Actual behavior:** Shell commands are not accessible.

### Versions

atom - 1.12.1
apm - unknown, as it is not in the command line.

This is on OSX 10.10.5.

**Comment by Andrew-Morozko** [comment] 2016-11-21 17:04
This is probably caused by App Translocation: when you launch Atom.app just after unpacking (still in Downloads folder) It's actually moved to special folder with random name to prevent dylib hijacking attack (more on that [here](http://lapcatsoftware.com/articles/app-translocation.html)).
`Install Shell Commands` in this case actually installs symlinks, but they link to Atom.app in that random folder. When atom is closed that folder is wiped, leaving symlinks broken.

### Hack
Move Atom.app from its current location somewhere else and then return it back. This will turn off App Translocation. Then Run `Install Shell Commands`. For some weird reason if you launch Atom.app now it can exhibit some problems with some plugins (in my case linter-pylama fails to lint with no traceback. I suspect that it's caused by external binary dependancy). Everything works fine if you launch atom from Terminal (via `atom` command).

### Solution
After update make appropriate changes to `com.apple.quarantine` extended attribute. [Useful issue](https://github.com/potionfactory/LetsMove/issues/56) for further research.

**Comment by mnquintana** [comment] 2016-11-21 19:19
@tedivm What directory were you running Atom from?

**Comment by 50Wliu** [comment] 2016-12-15 16:09
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13204#issuecomment-262038510. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2016-12-15 16:09 UTC
Labels: mac, more-information-needed, needs-reproduction
