### ISSUE TITLE
Atom Editor Crashes when searching for packages with "keyboard" keyword

### ISSUE THREAD

**Issue by deciorf** [atom/atom#19773] opened 2019-08-10 02:37 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Execute Atom.
2. On menu option **_File_**, click on **_Settings_**.
3. Click on **_Settings_** Tab .
4. Click on **_+Install_** option at right.
5. Write "_keyboard_" in text box "_Search Package_".
6. Scroll down the tab content.

**Expected behavior:**
- To show all the Packages related with "keyboard" keyword

**Actual behavior:**
- Atom Editor Crashes.

**Reproduces how often:**
- Allways. 100%.

### Versions
- MSWindows: 10 HOME ver 1803
- ATOM: 1.39.1 X64
- Electron : 3.1.10
- Chrome: 66.0.3359.181
- Node: v10.2.0

### Additional Information

I searched for others keywords: cat, dog, sweet heart, love, color, sound, sky, car, motor, @#$%^&*, Supercalifragilisticexpialidocious, and there is no issues, but with "keyboard" as keyword,  immediately Atom crashes.
![photo_2019-08-09_22-10-15](https://user-images.githubusercontent.com/27117346/62816427-4d692100-baf5-11e9-8e4b-c949756407d4.jpg)
![photo_2019-08-09_22-27-53](https://user-images.githubusercontent.com/27117346/62816430-522dd500-baf5-11e9-8d33-2e608ed02f3d.jpg)

**Comment by deciorf** [comment] 2019-08-10 13:14
Hello!

I don't know what happened, but this morning Atom didn't give the error described above. 

I forgot to mention before, that I restarted and turned off the computer several times and Atom continued to fail; then, something different from this must have happened so that Atom does not present the problem this morning. 

I wonder if someone will have corrected it.

**Comment by rsese** [comment] 2019-08-12 17:22
Thanks for the report and the update!

> I don't know what happened, but this morning Atom didn't give the error described above.

...

> I wonder if someone will have corrected it.

Hmm, there haven't been any changes on our end since your initial report and you're on the latest stable version of Atom.

Not sure what the issue could be and haven't seen any other reports (also couldn't reproduce on Window 10 with 1.39.1 just now).  Since it doesn't seem to be reproducible anymore, we'll close this for now but can reopen if you start seeing it again.

**Closed by rsese** 2019-08-12 17:22 UTC

**Comment by deciorf** [comment] 2019-08-12 18:36
Thanks for your response.

I don't know what happened, but I wonder if it could be a kind of web cache
error when searching for the keyword "keyboard."
Anyway, the good news is that it is working fine now.
Thanks again.
