### ISSUE TITLE
Scroll feature doesn't work well in preview pane. 

### ISSUE THREAD

**Issue by heefan** [atom/atom#10963] opened 2016-02-25 08:34 UTC
### Description
My preview doesn't work well as it always scroll up.
I took a look at `settings` but didn't find anything about the keyword `scroll` for preview pane.
Since it cannot sync correctly, how do I disable the scroll feature? 

### Steps to Reproduce
1.  I open a markdown file with long content, which is over screen height.
2.  enable and display preview pane on right side. 
3.  if I type anything on the edit pane, and preview panel will scroll up immediately and remain the position on the preview pane, such that I cannot see the live result from preview panel, and I have to scroll down to the page bottom to follow up.

**Expected behavior:** 
The preview content should sync with edit pane. 
**Actual behavior:**
The preview content always scroll up and stop the position. 
I have to manually scroll down to follow edit pane.

### Versions
Atom: 1.5.3
Windows 10.

**Comment by 50Wliu** [comment] 2016-02-25 17:48
This is a duplicate of atom/markdown-preview#178 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-25 17:48 UTC
