### ISSUE TITLE
On reload, window cascades

### ISSUE THREAD

**Issue by benogle** [atom/atom#10648] opened 2016-02-02 00:49 UTC
1. Open an atom window
1. Open another atom window
1. Move the windows so one is on the left of the screen, and one is on the right of the screen
1. Reload _the second window_ via `cmd-option-ctrl-l`
1. Note that it does not retain it's original position, but cascades under the other open window :(

I assume it's related to https://github.com/atom/atom/pull/10236

**Comment by 50Wliu** [comment] 2016-02-02 01:16
I just tried reproducing this on Windows and can't, so labeling this as Mac-only for now.  @benogle did the Atom windows initially overlap in your test or were they snapped to one side of the screen (not sure if that exists on Mac)?

**Comment by benogle** [comment] 2016-02-02 01:21
Just positioned, not snapped. I will make a vid if no one can repro.

**Comment by lee-dohm** [comment] 2016-02-02 05:16
I was unable to reproduce this using Atom v1.4.2 on Mac OS X 10.11.3. Here's what I did:

1. Took my current open instance of Atom (running in Dev Mode) and moved the window to the left side of the screen
1. Opened a second window using <kbd>Shift+Cmd+N</kbd>
1. Moved the second window to the right side of the screen (the two windows overlap partially and are not docked)
1. Made the original window active by clicking on the title bar
1. Reloaded the window using <kbd>Ctrl+Option+Cmd+L</kbd>

Expected and Actual: The window reloaded in the same location

**Comment by MaximSokolov** [comment] 2016-02-02 07:34
OS X 10.11.3, Atom v1.5.0-beta2:
![3hlygotl2z](https://cloud.githubusercontent.com/assets/2943616/12742528/ad23cfc6-c997-11e5-870e-2c354ce85312.gif)
Cannot reproduce this using Atom v1.4.0

**Comment by benogle** [comment] 2016-02-02 19:34
Ok, looks like it's all windows but the 1st window. Thanks @lee-dohm and @MaximSokolov

**Comment by 50Wliu** [comment] 2016-02-02 20:37
Reproduced using the new steps on Windows as well.

**Comment by joshaber** [comment] 2016-02-02 20:46
Yeah, definitely introduced in #10236 and definitely annoying.

**Comment by joshaber** [comment] 2016-02-17 03:38
Looks like this regressed on `master`.

**Comment by joshaber** [comment] 2016-02-18 18:39
Confirmed fixed by https://github.com/atom/atom/pull/10888.

**Closed by joshaber** 2016-02-18 18:39 UTC
Labels: atom, bug
