### ISSUE TITLE
Markdown highlight corrupts after *> 

### ISSUE THREAD

**Issue by sebgymn** [atom/atom#7545] opened 2015-06-29 11:30 UTC
While editing a .md file, the highlight behaves incorrectly after *> occured in text. The whole file is displayed in pink after that. Please see the screenshot. 
v 1.0.0 .deb package (it was also present in 0.188)
![screenshot from 2015-06-29 14 26 58](https://cloud.githubusercontent.com/assets/5337921/8406992/edf2aa1e-1e6a-11e5-9bbd-7150a1b700b0.png)

**Comment by Fank** [comment] 2015-06-29 11:36
I think you should open an issue here https://github.com/atom/language-gfm
Because its an language issue not an general issue in atom.

**Comment by izuzak** [comment] 2015-06-29 11:37
Yeah, I believe this is a duplicate of https://github.com/atom/language-gfm/issues/44. Closing in favor of that issue.

**Closed by izuzak** 2015-06-29 11:37 UTC
