### ISSUE TITLE
1.19.0 版本,当一文件关闭后再打开不能维持之前的折叠状态,1.18.0版本是可以的

### ISSUE THREAD

**Issue by codecools** [atom/atom#15196] opened 2017-08-09 03:07 UTC
版本信息: 1.19.0 x64

**Comment by Zireael07** [comment] 2017-08-09 06:15
Summoning @50Wliu for at least a rough translation before closing (you didn't fill in the issue template @codecools :)

**Comment by Arcanemagus** [comment] 2017-08-09 06:58
Google Translate says:

> Version 1.19.0, when a file is closed and then open can not maintain the previous folding state, 1.18.0 version is possible
>
>Version information: 1.19.0 x64

**Comment by 50Wliu** [comment] 2017-08-09 13:01
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #13258. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-09 13:01 UTC
