### ISSUE TITLE
Everytime I writing something , the markdown preview page go to top

### ISSUE THREAD

**Issue by an15m** [atom/atom#14285] opened 2017-04-24 06:23 UTC
And then I need to roll to bottom

atom version: 1.16.0x64
markdown-preview version:0.159.7

**Comment by Ben3eeE** [comment] 2017-04-24 06:45
Thanks for taking the time to contribute!

We noticed that this is a duplicate of your own issue https://github.com/atom/markdown-preview/issues/483.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-04-24 06:45 UTC
Labels: invalid
