### ISSUE TITLE
bufferRangeForScopeAtCursor counts tabs as spaces

### ISSUE THREAD

**Issue by zboro** [atom/atom#9648] opened 2015-11-17 13:22 UTC
I tried to call editor.bufferRangeForScopeAtCursor(".string") to get range of currently selected string. Then I tried to get that string by calling editor.getTextInBufferRange(range). It works as expected and I get entire string if line is indented with spaces.

If line is indented with tabs, returned string starts several characters to the right, it is the right length (or cropped if there are no more characters). bufferRangeForScopeAtCursor seems to be counting single tab as multiple characters (based on its width), while getTextInBufferRange counts tab as only one character.

For example, if line starts with 2 tabs (4 chars wide) immediately followed by string, start column of range returned from bufferRangeForScopeAtCursor is 8 (or undefined, see below). Since getTextInBufferRange counts tab as one character, it returns string starting with eighth character which is already 6 letters inside of string I was trying to get.

Let's assume this code:

    range = editor.bufferRangeForScopeAtCursor(".string")
    editor.getTextInBufferRange(range)

and this input:

    \t\t"my string", some other text

If cursor is placed before "r", bufferRangeForScopeAtCursor returns undefined. That is because editor.getCursorBufferPosition (used internally by bufferRangeForScopeAtCursor) counts tab as one character and therefore it returns column < 8, which as far as bufferRangeForScopeAtPosition (also used internally by bufferRangeForScopeAtCursor) is concerned is not within any string.

If cursor is placed after "r", it returns "ring", some".

When you look at tokenizedLines in TokenizedBuffer for that line, you see that tags start \[4,4,...\] (4 may be replaced by actual tab width) and as far as I can currently tell this seems to be the problem. I assume that either tokenizer should not count tabs as multiple characters or bufferRangeForScopeAtPosition should not take tags as buffer column numbers.

**Comment by izuzak** [comment] 2015-11-19 14:12
Thanks for the detailed report, @zboro!

@nathansobo @maxbrunsfeld Do you perhaps want to take a look at this one? I was able to reproduce this

**Comment by maxbrunsfeld** [comment] 2015-11-19 17:20
Yeah, the issue here is the difference between 'screen' coordinates and 'buffer' coordinates. The buffer coordinates pretty much map directly to the characters in the underlying file. In particular, tabs are just characters; they are not handled specially. In screen coordinates, however (e.g. `getTextInScreenRange`), tabs are sized according to the `editor.tabLength` setting.

**Comment by maxbrunsfeld** [comment] 2015-11-19 17:33
Ok, I completely misunderstood your comment at first @zboro. I see that bug that you're talking about. `bufferRangeForScopeAtCursor` returns an incorrect range. Its columns are *screen* columns, not buffer columns.

**Comment by maxbrunsfeld** [comment] 2015-11-19 17:37
I also just realized that this is a duplicate of https://github.com/atom/atom/issues/8685. @zboro Please subscribe to that issue for updates. Thanks again for the report!

**Closed by maxbrunsfeld** 2015-11-19 17:37 UTC
Labels: bug, editor-rendering
