### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by petefoth** [atom/atom#10834] opened 2016-02-16 13:50 UTC
[Enter steps to reproduce below:]

1. use sshfs to mount a drive on a remote machine `sshfs -p 20022 local-petefoth@xxx.yyy.zzz.aaa:/ ~/wikitest/
2. Browse to a directory on the mounted drive in Finder
3. Right click on a file then choose Open with | Atom

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Users/pete/Library/Application Support/com.github.atom.ShipIt/update.gSiZmfJ/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "autocomplete-plus"
    ]
  },
  "editor": {
    "showInvisibles": true,
    "preferredLineLength": 79,
    "tabLength": 4,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "invisibles": {},
    "fontSize": 10
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joshaber** [comment] 2016-02-16 14:34
Thanks for the report! This looks like a duplicate of #9559 though – feel free to subscribe there for updates.

**Closed by joshaber** 2016-02-16 14:34 UTC

**Comment by petefoth** [comment] 2016-02-16 14:43
On 16/02/2016 14:35, Josh Abernathy wrote:
> Thanks for the report! This looks like a duplicate of #9559
> <https://github.com/atom/atom/issues/9559> though – feel free to
> subscribe there for updates.
>

My apologies for not checking the outstanding issues first :)

**Comment by joshaber** [comment] 2016-02-16 15:03
No worries!
