### ISSUE TITLE
feature request: add cmd-click to jump to function definition

### ISSUE THREAD

**Issue by chovy** [atom/atom#13463] opened 2016-12-17 08:41 UTC
All the major editors have this feature as a default behavior:

    function foo(){

    }

    foo() // cmd-click here and you jump to the function definition

It's pretty much the only reason I don't use Atom and stick with either Intellij or VS Code.

**Comment by 50Wliu** [comment] 2016-12-17 16:33
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/symbols-view/issues/18. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-17 16:33 UTC
