### ISSUE TITLE
File finder shows 'Project is empty' when parent repository .gitignore targets child repository.

### ISSUE THREAD

**Issue by jisbert** [atom/atom#8726] opened 2015-09-09 10:14 UTC
I have a parent repository within which I have child repositories. This is an example which shows a similar layout:

    C:.
    ├───.git
    ├───.gitignore
    ├───.gitattributes
    ├───README.md
    ├───child-1
    │   ├───.git
    │   ├───.gitignore
    │   ├───.gitattributes
    │   └───README.md
    └───child-2
        ├───.git
        ├───.gitignore
        ├───.gitattributes
        └───README.md

I don't want to track child repository files from parent repository so I have configured the parent repository .gitignore in order to ignore every directory. This is how the .gitignore shows:

    */

Changes in child repositories are tracked as ususal and, when I open a child repository in atom, changes can be seen in atom tree view and status bar. I can also look for changes in git status finder but, when I toggle file finder, it shows 'Project is empty'. If I remove .gitignore from parent repository file finder shows project files as usual.

# Steps to reproduce #

These are the steps to reproduce in Windows with GitHub for Desktop Shell (PowerShell):

```PowerShell
git init parent
cd parent
sc .gitignore '*/' 
ni .gitattributes,README.md
git add -A
git commit -m ':boom:'
git init child-1
cd child-1
ni .gitattributes,.gitignore,README.md
git add -A
git commit -m ':boom:'
atom .
```

And then toggle file finder (Ctrl+P).

**Comment by mnquintana** [comment] 2015-09-09 10:28
Thanks for the report! This looks like a duplicate of https://github.com/atom/fuzzy-finder/issues/111 - closing this out in favor of that issue.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Closed by mnquintana** 2015-09-09 10:28 UTC

**Comment by jisbert** [comment] 2015-09-09 11:02
Thank you for the tip @mnquintana :smiley:
