### ISSUE TITLE
Can't open existing file without open editor window

### ISSUE THREAD

**Issue by cheloya** [atom/atom#13015] opened 2016-10-18 05:09 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Opening an existing file doesn't work if an editing window isn't open already.

### Steps to Reproduce

1. Open Atom (safe mode or normal)
2. Close Atom editor windows, but not Atom itself
3. File > Open...

**Expected behavior:** Finder opens to allow user to browse to the file they want to open.

**Actual behavior:** Nothing happens.

### Versions

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
OS: Mac OS 10.12.

**Comment by Ben3eeE** [comment] 2016-10-18 06:12
This is a duplicate of https://github.com/atom/atom/issues/12508. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-18 06:12 UTC
