### ISSUE TITLE
Uncaught TypeError: r.filter is not a function

### ISSUE THREAD

**Issue by rcrooks** [atom/atom#18194] opened 2018-10-04 16:54 UTC
[Enter steps to reproduce:]

1. wasn't doing anything special -- just searching for a theme to install

**Atom**: 1.32.0-beta1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: r.filter is not a function

```
At /private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/6119AA1E-1C1F-4555-ABF2-6F5D94165C15/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:14

TypeError: r.filter is not a function
    at Request._callback (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/6119AA1E-1C1F-4555-ABF2-6F5D94165C15/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:717266)
    at Request.self.callback (/app.asar/node_modules/settings-view/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /app.asar/node_modules/settings-view/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
 12x -7:28.9.0 editor:indent-selected-rows (input.hidden-input)
     -7:06.0 intentions:highlight (input.hidden-input)
 14x -7:05.6.0 multi-cursor:expandDown (input.hidden-input)
     -6:53.6.0 datatip:toggle (input.hidden-input)
     -6:21.7.0 core:copy (input.hidden-input)
     -6:19.2.0 find-and-replace:show (input.hidden-input)
  2x -6:16.1.0 core:copy (input.hidden-input)
     -5:31.1.0 core:save (input.hidden-input)
  3x -5:25.9.0 core:backspace (input.hidden-input)
  2x -5:01.1.0 core:copy (input.hidden-input)
     -4:59.8.0 core:paste (input.hidden-input)
     -4:32.1.0 core:backspace (input.hidden-input)
  2x -2:43.3.0 core:copy (input.hidden-input)
     -2:40.5.0 core:paste (input.hidden-input)
  4x -0:45 core:copy (input.hidden-input)
     -0:19 core:paste (input.hidden-input)
```

### Non-Core Packages

```
after-dark-syntax 0.1.0 
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-yamljson 0.2.4 
auto-update-packages 1.0.1 
autocomplete-python-jedi 1.10.3-0 
ayu-mirage-ish-syntax 1.1.0 
birds-syntax 0.2.1 
bracket-colorizer 1.2.0 
busy-signal 1.4.3 
darkpython-syntax 0.5.0 
double-tag 1.5.0 
eclectic-syntax 0.3.0 
emmet 2.4.3 
fancy-bracket-matcher 2.1.0 
glazial-syntax-autumn 0.1.0 
gruvbox 1.0.7 
gruvbox-plus-syntax 1.3.1 
ide-css 0.3.0 
ide-html 0.4.2 
ide-python 1.0.0 
ide-yaml 0.4.4 
indent-guide-improved 1.4.13 
intentions 1.1.5 
keyword-pair-matcher 0.2.0 
line-number-color 0.2.0 
linter 2.2.0 
linter-js-yaml 1.3.0 
linter-python 3.1.2 
linter-ui-default 1.7.1 
logo-file-icons 1.13.0 
maersu-blue-syntax 0.2.0 
maersu-nemo-syntax 0.2.2 
minima-gp-ui 0.1.0 
mojave-dark-mode 0.1.1 
monday-syntax 0.1.4 
multi-cursor 2.1.5 
neko-atom-ui 1.3.1 
nemo-blue-syntax 0.2.0 
pigments 0.40.2 
python-debugger 0.2.0 
raischburn-syntax 1.1.0 
resonance-syntax 0.2.0 
rocket-dark-syntax 1.0.0 
tuesday-syntax 0.1.2 
yaml-path 0.1.1 
yaml-sortkey 0.1.0 
```

**Comment by rcrooks** [comment] 2018-10-04 17:02
ps. I *think* this was actually an issue with the package https://atom.io/packages/mojave-dark-mode - I'd just installed that when I saw the error. and after uninstalling the package, it's gone. 

fyi @paysonwallach

**Comment by rsese** [comment] 2018-10-04 17:48
Thanks for contributing!

Based on the stack trace, I think this is a duplicate of https://github.com/atom/settings-view/issues/1052 so you can subscribe there for updates if you'd like.

I'm not sure if  https://atom.io/packages/mojave-dark-mode is related in particular since I can't reproduce the error after installing it and then searching for a package/theme.  

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-04 17:48 UTC
