### ISSUE TITLE
Touchscreen support (with high DPI)

### ISSUE THREAD

**Issue by DickvdBrink** [atom/atom#2209] opened 2014-05-13 17:50 UTC
I have a Microsoft Service tablet and I tried Atom on it. With mouse it works like a charm but when I use the touch screen it doesn't work that well. I think it is something like 100 pixels wrong on the  x-ax and 60 on the y-ax. So the cursor moves 100px more to the left and 60 to the top.
Note: I do have DPI scaling enabled at 150% after changing it to 100% (and logging out) it did work

Note: The menus do work correctly with touch, just the editor (and tabs don't)

I do not know if it is Windows specific because I don't have another OS with touchscreen.

Edit: I changed the issue I didn't logout the first time so my DPI settings didn't change.

**Comment by russlescai** [comment] 2015-05-11 04:15
I have written some CoffeeScript for your init.coffee to enable touch scrolling:

https://github.com/atom/atom/issues/6724

**Comment by russlescai** [comment] 2015-05-12 03:19
There is now a package to handle touch events within Atom https://atom.io/packages/atom-touch-events

It currently supports swipe events, and allows scrolling by swiping up and down.

I plan to implement tap and pinch gestures to zoom and select correctly.

Hopefully you find it useful.

**Comment by russlescai** [comment] 2015-06-06 00:02
The https://atom.io/packages/atom-touch-events package now supports pinch to zoom gestures, and handles tap better (doesn't automatically bring up the soft keyboard, sets cursor, and double tap highlights the word).

**Comment by ParkerK** [comment] 2015-08-07 07:23
@russlescai  thanks so much, that package has saved me so much frustration. 

Is there any way you can get that into the Atom core? It's a shame some people may not know about your fix

**Comment by tgienger** [comment] 2015-09-24 14:10
@russlescai Sorry about the nitpick because this package helps, but this a a long ways from the natural feel of true touch events. Scrolling should feel like it does in VSCode.

**Comment by nzufelt** [comment] 2016-02-15 11:06
@russlescai @DickvdBrink @wilddeer Did atom-touch-events work for the Microsoft Surface users?  I have a SP4, and I can report that atom-touch-events is registering my touch events but it is extremely sluggish and barely moves the screen.  Sadly, it's not usable in its current form for me.

**Comment by DickvdBrink** [comment] 2016-02-15 13:09
@nzufelt, sorry I don't know - I switched to VSCode because of this issue and haven't tried Atom anymore

**Comment by jrajav** [comment] 2016-09-26 13:44
Any progress on this? Is there any possibility of changing the main editor pane to a normal scrolling pane (with CSS overflow) rather than using translate() which breaks touch input?

**Comment by jeredmasters** [comment] 2016-12-21 06:54
I can confirm atom-touch-events works well on the surface pro 4. However the scroll doesn't have momentum and stops scrolling as soon as you take your finger off, this is quite different to basically every other touch-scroll ever

**Comment by jrajav** [comment] 2017-01-31 23:15
Any update on this?! Atom's main text editor pane *still* does not support basic touch events. Why does it still use -webkit-transform instead of a normal overflow?

**Comment by dmig** [comment] 2017-05-12 14:24
This issue should definitely be converted to **bug**...

**Comment by pabloab** [comment] 2017-07-03 19:00
Hoping touchscreen support on Linux also (Ubuntu 16.04 with Asus UX303UB my case). Should I file another issue or _Linux_ label could be added?

**Comment by jrajav** [comment] 2017-07-25 15:48
Yes as @dmig said, why is this labeled an enhancement rather than a bug? Scrolling the editor pane with a primary input device seems like it should be basic functionality.

**Comment by bjorg** [comment] 2017-09-16 14:16
How hard can this be? Tools like the Slack desktop app simply don't work on high DPI screens, because of this issue. Tapping to select a channel is a must have capability!

**Comment by pabloab** [comment] 2017-09-16 23:37
Maybe related to [Electron Issue #8125](https://github.com/electron/electron/issues/8125).
Using atom/now v1.19.7 and slack-desktop v2.8.0 (both amd64) on Ubuntu 16.04.3 LTS over Asus UX303UB. On both now touch and scroll events works fine.

**Comment by dmig** [comment] 2017-09-17 07:41
@pabloab Atom reacts to touch events, also touch scrolling works in most panes -- the only exception is editor.
I'm using atom beta versions since 1.7 or 1.8 under ubuntu (xfce, gnome 3) 15.04-17.04.

**Comment by ccoenen** [comment] 2017-09-17 08:27
@bjorg "how hard can this be" sure sounds like you're about to offer a pull request. Just Sayin'.

**Comment by edit4ever** [comment] 2017-10-27 01:30
same issue here on a dell 5175 tablet running windows 10. no scroll in editor with the touchscreen.  :-(

**Comment by zxol** [comment] 2018-04-29 02:16
Ubuntu 16.04, Microsoft Surface pro 8 - touch position is accurate, but touch scrolling is not working in the editor window.  It would great to have!  (it is forcing me to use more keyboard navigation tricks though, which is kind of cool ^^, maybe I'll try again with VIM soon, haha)

**Comment by xavierfoucrier** [comment] 2018-07-01 13:57
I code sometimes on my Dell **touch laptop** with Windows 7 x64 1920x1080 resolution and I will really appreciate to see this feature integrated in Atom. :+1:

**Comment by fractalbach** [comment] 2018-10-25 14:32
Ubuntu 18.04.1 LTS
GNOME 3.28.2
ATOM 1.32.0 x64

 from the snap store.

Electron: 2.0.9
Chrome: 61.0.3163.100
Node: v8.9.3

* Scrolling is perfect in the Welcome, Settings, etc panes.
* In editor mode: touch click works for placing the cursor at a location.
* In editor mode: *touch scrollling* doesn't work. 

Expected:
* scroll up/down behavior to match the behavior in Welcome, Settings, etc.

**Comment by JulienAramino** [comment] 2019-01-26 14:47
Why this is closed?
The issue is the same on a Chromebook with Linux app. The editor do not scroll with fingers ;-(.
I will try the package describe before ...

**Comment by dmig** [comment] 2019-01-26 14:50
Because noone gives a fuck...
I ditched Atom in favour of VSCode more than a year ago and I'm happy with it.

**Comment by JulienAramino** [comment] 2019-01-26 17:07
The package works pretty well, I'm very happy to have found this thread.
I can now code on my chromebook ;-)
It should be documented somewhere that Atom do not support touch events and that some package for the moment help with this.
Thanks

**Comment by lee-dohm** [comment] 2019-01-29 22:11
Thanks for the interest.

Unfortunately, creating special case code for touch screen support is not something that we're going to be able to prioritize over other functionality. Because of this, after reviewing with the team, we've decided to close this issue as something that we do not intend to work on. Additionally, we won't be accepting a pull request for functionality in this area.

Thanks again.

**Closed by lee-dohm** 2019-01-29 22:11 UTC
Labels: electron, enhancement, windows

**Comment by MarcAnt01** [comment] 2019-03-10 17:16
The future is of touch-screen and convertible PCs, desktop PCs are gonna be less and less in the future. By taking this decision, you want Atom to die and become an old crappy text editor

**Comment by JulienAramino** [comment] 2019-03-11 18:19
the previous comment is not a spam, stop demagogy

**Comment by MarcAnt01** [comment] 2019-03-11 18:22
> the previous comment is not a spam, stop demagogy

I could have understood if it had been marked as off topic, but as spam makes me laugh. I laugh not to cry btw

**Comment by MarcAnt01** [comment] 2019-03-11 18:25
If a software is open source, developers should be happy to see what community thinks about something, but in this case they just seem to ignore them. If you are not gonna implement something, at least leave the community members to implement something.
(mark this comment as spam if you don't agree)

**Comment by lee-dohm** [comment] 2019-03-11 18:58
You're right. All of this conversation is off-topic and the comments have been hidden or re-hidden as such.

However, making accusations such as "you want Atom to die and become an old crappy text editor" is a violation of [Atom's Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. So @MarcAnt01, you may consider this an official warning.

**Comment by MarcAnt01** [comment] 2019-03-11 19:05
> You're right. All of this conversation is off-topic and the comments have been hidden or re-hidden as such.
> 
> However, making accusations such as "you want Atom to die and become an old crappy text editor" is a violation of [Atom's Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. So @MarcAnt01, you may consider this an official warning.

It wasn't meant neither to insult you, but to criticize your decisions. I think as the participation of many users of this issue shows. Your code of conduct states to focus on "What's better for the community", so pls consider the community's ideas and let at least someone try to fix that

**Comment by lee-dohm** [comment] 2019-03-11 19:11
If you wish to discuss this further, since this is still off-topic. Please contact me via email at atom@github.com. For the sake of anyone that is subscribed to this issue, I'm going to go ahead and lock it to prevent further digression.
