### ISSUE TITLE
Dragging Firefox tab over Atom window instantly crashes Atom

### ISSUE THREAD

**Issue by ottobonn** [atom/atom#8193] opened 2015-08-01 22:44 UTC
When dragging a Firefox tab to create a new window or move it to another window, if the pointer crosses over Atom's window, Atom crashes.

Atom 1.0.0
Linux Mint 17.1 x64
Firefox 39.0

Here's a short video of it happening: https://gfycat.com/WearyFatalBumblebee

And the output of running `atom` in the terminal:

```
[10263:0801/155241:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 232ms
[10263:0801/155242:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
[10296:0801/155242:INFO:renderer_main.cc(212)] Renderer process started
[10298:0801/155242:INFO:renderer_main.cc(212)] Renderer process started
[10263:0801/155244:INFO:CONSOLE(56)] "Window load time: 1601ms", source: file:///opt/atom/resources/app.asar/static/index.js (56)
[10263:0801/155244:INFO:CONSOLE(56)] "Window load time: 1771ms", source: file:///opt/atom/resources/app.asar/static/index.js (56)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 517 error_code 5 request_code 20 minor_code 0)
```

**Comment by mnquintana** [comment] 2015-08-01 23:06
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/3593 – please subscribe there for updates.

Also, although this won't fix your issue, you might want to update to the latest version of Atom (1.0.3) as it fixes a number of issues.

**Closed by mnquintana** 2015-08-01 23:06 UTC
