### ISSUE TITLE
Uncaught Error: The specified module could not be found. ... Keyboard-layout

### ISSUE THREAD

**Issue by brianjastram** [atom/atom#19933] opened 2019-09-19 17:47 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\ProgramData\brian.jastram\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:166

Error: The specified module could not be found.
\\?\C:\ProgramData\brian.jastram\atom\app-1.40.1\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:/ProgramData/brian.jastram/atom/app-1.40.1/resources/app/static/<embedded>:1:714332)
    at get_KeyboardLayoutManager (C:/ProgramData/brian.jastram/atom/app-1.40.1/resources/app/static/<embedded>:14:2747069)
    at get_manager (C:/ProgramData/brian.jastram/atom/app-1.40.1/resources/app/static/<embedded>:14:2747171)
    at Object.getCurrentKeyboardLayout (C:/ProgramData/brian.jastram/atom/app-1.40.1/resources/app/static/<embedded>:14:2747297)
    at e.keystrokeForKeyboardEvent (C:/ProgramData/brian.jastram/atom/app-1.40.1/resources/app/static/<embedded>:14:1087835)
    at KeymapManager.keystrokeForKeyboardEvent (C:/ProgramData/brian.jastram/atom/app-1.40.1/resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (C:/ProgramData/brian.jastram/atom/app-1.40.1/resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (C:/ProgramData/brian.jastram/atom/app-1.40.1/resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -0:08.5.0 core:delete (span.syntax--comment.syntax--block)
```

### Non-Core Packages

```
autocomplete-clang 0.12.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.35 
intentions 1.1.5 
language-ini 1.22.0 
linter 2.3.1 
linter-gcc 0.7.1 
linter-ui-default 1.8.0 
minimap 4.29.9 
minimap-split-diff 0.3.7 
platformio-ide 2.4.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.4 
split-diff 1.6.0 
tool-bar 1.1.12 
```
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    X* Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

any keystroke causes the error
### Steps to Reproduce

1.  open atom
2.  press any key
3.  see error

**Expected behavior:**

 characters to appear on my screen when typed

**Actual behavior:**

 error code

**Reproduces how often:**

every keystroke

### Versions

 1.40.1

**Comment by brianjastram** [comment] 2019-09-19 17:50
Error happens in safe mode.

**Comment by rsese** [comment] 2019-09-19 22:48
Thanks for contributing!

We noticed that this looks like a duplicate of #14461 so you can subscribe there for updates if you'd like.

Can you try quitting Atom and reinstalling to see if that helps?  if you have an anti-virus program running try temporarily disabling it before reinstalling.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-09-19 22:48 UTC

**Comment by brianjastram** [comment] 2019-09-20 16:29
rsese,

Thanks. I exited and reinstalled Atom and that helped until I restarted my computer. Then the problem was back. I'm using a dock for my laptop and in the past it helped when I took it off the dock, but I think after a restart then that didn't work.

**Comment by RICKROSSWIFEINGRIDE** [comment] 2019-09-20 16:51
IM INGRID EALY ATOM.IO WHY EVERYONE STALKING MY APPS FROM ATOM.IO

**Comment by rsese** [comment] 2019-09-20 19:36
Did you have any anti-virus program running @brianjastram?

**Comment by brianjastram** [comment] 2019-09-20 19:47
Yes, Cylance Native Agent. this is a work computer so I can't do much for adjusting these types of settings. I can request a change.

**Comment by rsese** [comment] 2019-09-30 16:41
If that doesn't help or isn't possible because it's a work computer, another option is to use the `atom-x64-windows.zip` file from the [releases page](https://github.com/atom/atom/releases/latest).  Extract it to say `C:\atom` and run it from there though this version of Atom doesn't auto-update so you would have to download the latest .zip if there's another release.

**Comment by brianjastram** [comment] 2019-10-02 14:26
rsese,
Thank you. I did that and my problem is solved.
