### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/campbellpryde/Library/Applicatio...

### ISSUE THREAD

**Issue by campbellpryde** [atom/atom#9683] opened 2015-11-18 20:41 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.1
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/campbellpryde/Library/Application Support/com.github.atom.ShipIt/update.FkLKyrF'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/campbellpryde/Library/Application Support/com.github.atom.ShipIt/update.FkLKyrF'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/campbellpryde/Library/Application Support/com.github.atom.ShipIt/update.FkLKyrF/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (module.js:388:19)
```

### Commands

```
     -2:34.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:34.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:21.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:08.2.0 core:save (atom-text-editor.editor.is-focused)
  4x -1:48.1.0 tabs:close-tab (li.tab.sortable.active.right-clicked)
     -1:15.8.0 window:toggle-full-screen (atom-text-editor.editor.is-focused)
     -1:10.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:10.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:56.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:55.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:55.1.0 core:cancel (atom-text-editor.editor.is-focused)
 10x -0:40.6.0 tabs:close-tab (li.tab.sortable.active.right-clicked)
     -0:19.8.0 tree-view:reveal-active-file (li.tab.sortable.active.right-clicked)
     -0:16.5.0 tabs:close-tab (li.tab.sortable.active.right-clicked)
     -0:01.9.0 symbols-view:toggle-file-symbols (atom-pane.pane.active)
     -0:00.0 core:cancel (atom-pane.pane.active)
```

### Config

```json
{
  "editor": {
    "fontSize": 10
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-18 20:54
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-18 20:54 UTC
