### ISSUE TITLE
libcurl.so.4: version `CURL_OPENSSL_3' not found

### ISSUE THREAD

**Issue by wenmingwei** [atom/atom#18154] opened 2018-09-29 01:26 UTC
### Prerequisites

* Using Git PUSH/FETCH function with ATOM 1.31.1 on Ubuntu 18.04

### Description

When using ATOM to git push/fetch in latest Ubuntu 18.04 which upgraded libcurl3 -> libcurl4.
```
/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-http:
 /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found 
(required by /usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-http)
```

### Versions

Atom    : 1.31.1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by amirhfarzaneh** [comment] 2018-10-01 06:54
I have the same problem. Any fix?

**Comment by rsese** [comment] 2018-10-01 17:30
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/github/issues/848 - it's still open so not fixed but you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-01 17:30 UTC
