### ISSUE TITLE
Install fails on Win10

### ISSUE THREAD

**Issue by skeeved** [atom/atom#9583] opened 2015-11-13 22:02 UTC
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

**Comment by 50Wliu** [comment] 2015-11-13 22:22
Duplicate of #5109, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-13 22:22 UTC
