### ISSUE TITLE
Crash on opening html file

### ISSUE THREAD

**Issue by COLABORATI** [atom/atom#9113] opened 2015-10-11 20:13 UTC
Atom can not read html files and crashes. Here is one example page that does make this editor crash (it is the only editor I know that crashes on loading that html):

http://news.google.com/news?cf=all&hl=en&ned=us

**Comment by izuzak** [comment] 2015-10-11 20:25
Thanks for the report -- this seems to be a duplicate of https://github.com/atom/atom/issues/979 because that HTML file contains a super long line.

**Closed by izuzak** 2015-10-11 20:25 UTC
