### ISSUE TITLE
Atom won't copy lines starting with a # at the beginning of a file

### ISSUE THREAD

**Issue by Bengt** [atom/atom#5562] opened 2015-02-14 21:38 UTC

**Comment by lee-dohm** [comment] 2015-02-14 22:02
Can you provide repro steps? I just tried this using Atom v0.180.0-ea38926 on Mac OS X 10.10.2 and could not reproduce. Here is what I tried:

1. Start Atom
1. Open a new file using <kbd>Cmd+N</kbd>
1. Enter the text
    ```
    # blah blah blah
    
    1
    2
    3
    ```
1. Use <kbd>Cmd+Up</kbd> to go to the top of the file
1. Press <kbd>Shift+Cmd+Down</kbd> to select the first line
1. Press <kbd>Cmd+C</kbd> to copy the line
1. Press <kbd>Cmd+Down</kbd> to go to the end of the file
1. Press <kbd>Cmd+V</kbd> to paste the line

**Expected and Actual:** `# blah blah blah` appears at the end of the file

**Comment by izuzak** [comment] 2015-02-17 14:55
@Bengt I can't reproduce this either. If you can share the exact steps which reproduce this in the latest version of Atom in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode), that'd be great. Closing this for now, but happy to reopen if we can reproduce this.

**Closed by izuzak** 2015-02-17 14:55 UTC
Labels: needs-reproduction
