### ISSUE TITLE
Bug-When I paste some files, the folder was nested infinite loop

### ISSUE THREAD

**Issue by johnsonz** [atom/atom#11394] opened 2016-04-07 06:06 UTC
Win 10 x64 
Atom v1.6.2

When I paste some files to my project, I am not sure why this problem happens. There are just limited folders I can list. I really donnot know how many folders were nested. Maybe hundreds, thousands. I googled a lot and found nothing. It crazes me.

It accrued when I click "paste" at a folder. 

![capture](https://cloud.githubusercontent.com/assets/2533629/14341954/a54d5e66-fcc8-11e5-8fc5-510ff3b2f1a8.PNG)

And I could not remove them according to the bug of windows.

![capture1](https://cloud.githubusercontent.com/assets/2533629/14341995/fcbebc80-fcc8-11e5-80cc-f3b0f6da6ece.PNG)

**Comment by kumarharsh** [comment] 2016-04-08 10:34
Use the nodejs module [rimraf](npmjs.org/rimraf) to remove the folder. No idea why this happened though...

**Comment by ZombieHippie** [comment] 2016-04-09 19:47
@johnsonz, you can also use 7Zip `CTRL+SHIFT+DEL` to delete the tree structure and skip the Recycle bin.

Would you provide more detail to the kind of files you pasted? Multiple files, files and directories, single directory, etc?

**Comment by johnsonz** [comment] 2016-04-10 04:33
@ZombieHippie 7Z cannot solve this problem. I have formatted my drive.

I just want to use jquery-ui. You know, there are some subdirectories, and css, js, images in the directory I copied. I right click and select "paste" on the project in Atom tree. Then my computer has no response. I end it by task manager. And this problem happened. I renamed directories to a short name to try to delete them. But failed. It is why the screenshot I uploaded shows the directories named "a".

Another thing, there are nothing after I right click and select "paste" on the project in Atom tree frequently. and I am sure there are files in my clipboard. So I am not sure if it is caused by my OS.

**Comment by kumarharsh** [comment] 2016-04-10 11:55
@johnsonz I'm not sure if you are experiencing the same bug, but there **is** another bug I've encountered with both electron-based editors, atom AND vscode, that when you paste, the tree-view doesn't update. If you collapse/open the folder again, it is pasted. Even sublimetext does this sometimes, but not as frequently.

**Comment by johnsonz** [comment] 2016-04-16 07:40
@kumarharsh #11456

**Comment by Mr-Wallet** [comment] 2016-05-17 14:55
This may be a duplicate of [tree-view #656](https://github.com/atom/tree-view/issues/656).

**Comment by kumarharsh** [comment] 2016-05-17 17:46
@johnsonz I don't get an error, it's just that the list doesn't update at all, even though the file has been successfully moved.

**Comment by 50Wliu** [comment] 2016-05-17 20:10
Closing as a duplicate of atom/tree-view#656, thanks @Mr-Wallet!

**Closed by 50Wliu** 2016-05-17 20:10 UTC
