### ISSUE TITLE
Search in multiple directory containing multiple git repo

### ISSUE THREAD

**Issue by benzen** [atom/atom#14696] opened 2017-06-01 15:11 UTC
Step to reproduce

1.  create a directory (let's call it root)
1.  Inside of it create mutiple git clone ( each in it's own directory)
1.  be sure that each of these repository contains .gitignore, maybe some node_modules
1.  run a search for a file (cmd+t on mac) 
1.  notice that .gitignored files will popup in this search window

The .gitignored files will be ignored in a normal search if the root directory is the git repo.

Using 1.17.2 x64

**Comment by rsese** [comment] 2017-06-01 17:49
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/55. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-01 17:49 UTC
