### ISSUE TITLE
Exceptions in .gitignore are not shown in file tree

### ISSUE THREAD

**Issue by coreyog** [atom/atom#10142] opened 2015-12-21 18:45 UTC
I'm working on a TypeScript project and having all the js files generated alongside the ts files during development. However certain libraries in the project are js files I have in a vendor folder. I have these two lines in my .gitignore so that the generated files don't clutter the repo or the tree view but still allow the vendor js files to be included in the repo:

    *.js
    !**/vendor/

This should exclude all js files but include any and all files in a vendor folder. According to SourceTree, my vendor/*.js files will be checked in however the file tree view in atom will not show anything under it.

![gitignore](https://cloud.githubusercontent.com/assets/2836207/11938394/ce304e4c-a7d7-11e5-8875-c73ec9c6334a.PNG)

You can see that the arrow indicator next to vendor is pointed down so it should  be showing any files in that folder.

I've tried restarting atom and reordering my entries in .gitignore but so far I haven't found anything that works.

**Comment by peteainsworth** [comment] 2016-01-06 11:35
In the tree-view settings there is an option to 'Hide VCS Ignored Files'. 

It must have been toggled on in a recent update.

**Comment by coreyog** [comment] 2016-01-07 15:20
I know of the "Hide VCS Ignored Files" and I do want it checked. However, according to my .gitignore file I do NOT want to ignore files in "vendor" folders. The .gitignore works with git. In the above screenshot, all my js files in app/scripts/vendor are checked into my repository. This is due to the exception in the .gitignore file that atom is not listening to. I would expect that every file that git would ignore to not be present in the tree view but I would also expect every file that git would not ignore to be present.

**Comment by coreyog** [comment] 2016-01-07 16:19
I do have a correction to make, but the bug still happens.

My .gitignore line `!**/vendor/` should have been `!**/vendor/*`

I do want to "Hide VCS Ignored Files." I want to ignore *.js EXCEPT I do not want to ignore any files in a vendor folder (even if they are .js files).

After my correction, I can verify that I am checking in all files in my `vendor/` folders. However, atom continues to hide my vendor/*.js files despite the (now valid) exception in my .gitignore. I would expect that exceptions in my .gitignore means that those files would appear in my tree view.

**Comment by lee-dohm** [comment] 2016-01-12 00:31
I'm pretty certain this is a duplicate of https://github.com/atom/tree-view/issues/196. Please let me know if that is the case. You can subscribe there for updates if so.

**Comment by coreyog** [comment] 2016-01-12 00:41
It is a duplicate of 196.

**Closed** 2016-01-12 00:41 UTC
Labels: more-information-needed

**Comment by lee-dohm** [comment] 2016-01-12 00:46
Thanks for the update!
