### ISSUE TITLE
Cannot open anything in Atom if no windows are already open

### ISSUE THREAD

**Issue by hingeltd** [atom/atom#13427] opened 2016-12-12 10:44 UTC
### Description

When no windows are open I cannot open any folders or files using the File > Open menu. I have to click the Atom icon in the dock and wait for a blank new file to window open to appear before opening via the File -> open menu. I am on a late 2015 iMac running an up to date Sierra.

### Steps to Reproduce

1. [First Step]
Open Atom and close any windows

2. [Second Step]
With no windows open, select File > open

**Expected behavior:** [What you expected to happen]
Finder opens up and I can select a file / project

**Actual behavior:** [What actually happened]
Nothing. This has never worked for me.

### Versions

Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by Ben3eeE** [comment] 2016-12-12 10:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12508. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-12 10:52 UTC
