### ISSUE TITLE
atom version 1.43.0: Typescript syntax highlighting is not working

### ISSUE THREAD

**Issue by felipepalazzo** [atom/atom#20326] opened 2020-01-16 08:58 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

After upgrading to the lastest version (1.43.0), syntax highlithting for `.ts` and `.tsx` files doesn't work. 

### Steps to Reproduce

Open a Typescript file with code on Atom editor

**Expected behavior:**

Syntax highlighting 

**Actual behavior:**

No syntax highliting 

**Reproduces how often:**

Everytime 

### Versions

Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

macOS High Sierra 
version 10.13.6 

### Additional Information

I tested 1.44.0 beta and it has the same issue.

**Comment by felipe-vicente** [comment] 2020-01-16 13:37
same here

```
Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

**Comment by hugo** [comment] 2020-01-16 15:20
I resolved this by enabling **Use Tree Sitter Parsers** under **Core Settings**.

<img width="1792" alt="Screenshot 2020-01-16 at 15 19 31" src="https://user-images.githubusercontent.com/1704089/72537226-a5aa0900-3873-11ea-999d-ab1d04b94acb.png">

<img width="1792" alt="Screenshot 2020-01-16 at 15 19 27" src="https://user-images.githubusercontent.com/1704089/72537234-a8a4f980-3873-11ea-8ad2-6a8aa48d13c9.png">

**Comment by hugo** [comment] 2020-01-16 16:14
I resolved this by enabling **Use Tree Sitter Parsers** under **Core Settings**. However, I am not entirely sure that this is the "correct" fix. I seem to remember having to change that setting in the past because of syntax highlighting being broken.

<img width="1792" alt="Screenshot 2020-01-16 at 15 19 31" src="https://user-images.githubusercontent.com/1704089/72537226-a5aa0900-3873-11ea-999d-ab1d04b94acb.png">

<img width="1792" alt="Screenshot 2020-01-16 at 15 19 27" src="https://user-images.githubusercontent.com/1704089/72537234-a8a4f980-3873-11ea-8ad2-6a8aa48d13c9.png">

**Comment by Arcanemagus** [comment] 2020-01-16 16:53
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-typescript/pull/44. You may want to subscribe there for updates.

In addition, you should be leaving Tree-sitter parsers enabled unless you have a specific issue with how they work, as all development work from the Atom team moving forward will be on Tree-sitter parsers since they are a far more robust solution than the old TextMate grammars.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-01-16 16:53 UTC

**Comment by sirpask** [comment] 2020-01-21 20:31
https://github.com/atom/atom/issues/20330#issuecomment-575848797
