### ISSUE TITLE
New project opens as a new tab instead of a new window

### ISSUE THREAD

**Issue by rastogi-bhavya** [atom/atom#13169] opened 2016-11-09 16:57 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]
![image](https://cloud.githubusercontent.com/assets/17433752/20146940/e9aabbd2-a6cb-11e6-8e4b-9c1f7e34263c.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** The new project should open in a new window as it used to before.

**Actual behavior:** The new project opens as a new tab.

### Versions
atom version 1.11.2

OS: macOS sierra version 10.12.1

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by joseramonc** [comment] 2016-11-11 16:37
This is also happening to me, I can't get old behaviour.

Also tried opening projects with `atom . -n` but can't force it to open in new window.

**Comment by rastogi-bhavya** [comment] 2016-11-11 17:04
@joseramonc since when did you start facing this problem ?

**Comment by joseramonc** [comment] 2016-11-11 18:20
Can't remember if 1 or 2 versions ago

**Comment by galaxy233** [comment] 2016-11-15 10:07
Have you tried updating? I can't seem to reproduce this problem using the latest version.

**Comment by rastogi-bhavya** [comment] 2016-11-15 15:16
@galaxy233 Yes, I am running the latest version i.e. 1.11.2, which version are you running ? It happens with every single time whenever I try to open a new project.

**Comment by Ben3eeE** [comment] 2016-11-15 15:19
@rastogi-bhavya The latest stable version is 1.12.2

**Comment by Ben3eeE** [comment] 2016-11-15 15:22
Closing as a duplicate of https://github.com/atom/atom/issues/12690.

**Closed by Ben3eeE** 2016-11-15 15:22 UTC
Labels: mac, more-information-needed

**Comment by rastogi-bhavya** [comment] 2016-11-15 15:34
@Ben3eeE Thank you.
