### ISSUE TITLE
The default keybindings in core, prevent the use of extended ascii characters. 

### ISSUE THREAD

**Issue by pblanton** [atom/atom#11872] opened 2016-05-31 20:26 UTC
### Prerequisites

* [ X ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?

You can reproduce the issue all day long. I didn't try it in safe mode, because it's irrelevant. If safe mode uses the default keybindings, then it will be broken there too.  

* [ X ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?

I am using the latest version. Version 1.7.3

* [ X ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

Yes

### Description

In an Atom document I should be able to enter extended ascii characters by holding down the alt key and typing the character's value. For instance ...

[alt] 0169 = ©
[alt] 0128 = €
[alt] 0140 = Œ
[alt] 0174 = ®
[alt] 0216 = Ø

etc... However, the default keymappings use [alt] <number> to switch between tabs, so when you have multiple documents open in multiple tabs, typing [alt] 0169 results in the editor switching to the first tab, then the sixth tab, then the ninth one (or the last one if you don't have nine open), then when you release the [alt] key, the desired character is inserted in the wrong document.  

### Steps to Reproduce

1. open the Atom editor with multiple documents in multiple tabs.
2. Choose a document to insert a Ø into.
3. hold the [alt] key down and type 0216 then release the [alt] key.

The tab selection will bounce around as you type the digits, then the character will most likely be inserted into the wrong document.  

**Expected behavior:** [What you expected to happen]

I expect Atom to stay on the document I am Editing. Atom should respect default Windows keystrokes, and not implement breaking behavior.    

**Actual behavior:** [What actually happened]

The tab selection bounces around as you type the digits, then the character will inserted into the wrong document.  

### Versions

Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python
git 2.8.1.windows.1
visual studio

**Comment by 50Wliu** [comment] 2016-05-31 20:40
This is a duplicate of #6788 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-31 20:40 UTC
