### ISSUE TITLE
Markdown preview slows down on larger files

### ISSUE THREAD

**Issue by AwwCookies** [atom/atom#8074] opened 2015-07-25 12:55 UTC
The Markdown preview slows down the editor with more than 5,000 chars.

**Comment by mnquintana** [comment] 2015-07-25 13:32
This seems like a duplicate of https://github.com/atom/markdown-preview/issues/197 – let's keep the discussion there.

(Also for future reference, Atom's Markdown Preview is provided by [atom/markdown-preview](https://github.com/atom/atom), not atom/atom.)

**Closed by mnquintana** 2015-07-25 13:32 UTC
