### ISSUE TITLE
Atom change the projects folder

### ISSUE THREAD

**Issue by jarriztg** [atom/atom#13716] opened 2017-01-30 13:43 UTC
Ex. I have those directories in proyects folder:
latino
latgram
etc..

if I open ex. a file from "Telegram"
now i have;
Telegram Desktop -> atom delete all my projects folders and add that directory

NOTE: This just happens if I have closed Atom and I open a file from other binary

OS: Debian

**Comment by 50Wliu** [comment] 2017-01-30 16:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #9643. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-01-30 16:47 UTC
