### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.27.0\res...

### ISSUE THREAD

**Issue by smartoarif** [atom/atom#17331] opened 2018-05-15 22:49 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\mamun\AppData\Local\atom\app-1.27.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\mamun\AppData\Local\atom\app-1.27.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.27.0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.27.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.27.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:55.1.0 core:copy (div.line)
```

### Non-Core Packages

```
atom-beautify undefined 
atom-html-preview 0.2.5 
atom-knockout 1.0.1 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-bash-builtins 0.3.5 
busy-signal 1.4.3 
gaia-dark-syntax 2.1.0 
github-atom-light-syntax 0.5.0 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.3.2 
linter-ui-default 1.6.4 
php-cs-fixer 4.1.0 
php-debug 0.2.5 
php-integrator-autocomplete-plus 1.6.1 
php-integrator-autocomplete-plus-legacy-php56 1.0.1 
pretty-json 1.6.4 
windows-context-menu 0.3.1 
```

**Comment by supraniti** [comment] 2018-05-16 10:37
+1
Atom: 1.27.0 x64
Electron: 1.7.11
OS: Microsoft Windows 10 Pro

no packages installed
the error message pops when clicking none text keyboard keys (ctrl,backspace,delete etc.)
makes it impossible to use atom

**Comment by rsese** [comment] 2018-05-16 19:20
I think this is a duplicate of issues like #15722. If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled. If you don't have any anti-virus software running or re-installing doesn't help, let me know (it could be a duplicate of https://github.com/atom/atom/issues/14461 as well).

**Closed by rsese** 2018-05-16 19:20 UTC
