### ISSUE TITLE
Uncaught Error: spawn /Users/marcperez/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Con...

### ISSUE THREAD

**Issue by Perezmarc** [atom/atom#11205] opened 2016-03-18 19:51 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/marcperez/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/marcperez/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/marcperez/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/marcperez/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (/Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
    at exports.getWindowLoadSettings (/Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:15:15)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:170:22)
    at /Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at /Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:869:41
    at EventEmitter.<anonymous> (/Users/marcperez/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -3:24 editor:log-cursor-scope (atom-text-editor.editor.is-focused)
     -3:14.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:11.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:11.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:11 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:07.2.0 application:about (atom-text-editor.editor)
     -0:10.2.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by rbottema** [comment] 2016-03-21 11:41
Probably a duplicate of #9559

**Comment by lee-dohm** [comment] 2016-03-21 19:47
Agreed. Thanks @rbottema :grinning:

@Perezmarc you may want to subscribe to the Issue @rbottema linked for updates.

**Closed by lee-dohm** 2016-03-21 19:47 UTC
Labels: duplicate, uncaught-exception
