### ISSUE TITLE
Atom freezes when clicking web links in settings tab without the web browser already open

### ISSUE THREAD

**Issue by andya9** [atom/atom#6320] opened 2015-04-09 12:37 UTC
Atom 0.190.0
Linux.

This happens both in normal, safe and --one mode; it seems to happen only when the browser (I use firefox) is not open yet.

Steps to reproduce: packages > [a package] > settings > view on atom; or release notes > view on atom. If the browser was already open, everything works fine; otherwise, the browser opens but Atom freezes and must be killed from task manager.

**Comment by andya9** [comment] 2015-04-09 18:44
I noticed just now that the exact same thing also happens when clicking on the name of  a package to go to its home page on atom.io

**Comment by flosch** [comment] 2015-04-18 13:19
I can reproduce this was well.

**Comment by Stanzilla** [comment] 2015-06-07 03:46
This might be a Electron issue as it has been happening to me in Slack as well. On Windows.

**Comment by 03juan** [comment] 2015-08-28 10:20
I have a similar issue and partial solution.

My problem occurs when I have the x-scheme-handler/https mime type set to chromium.desktop in ~/.local/share/applications/mimeapps.list. If I change it to firefox.desktop it opens in Firefox even if the browser is not open.

If I remove the mime-type altogether it opens midori, probably because it's the last browser I installed but I'm not too sure about that.

The real issue is that the editor blocks while I have the page open, eventually showing the dialog:
"Editor is not responding.
The editor is not responding. Would you like to force close it or just keep waiting?"

If I click "Keep waiting" with the browser open it stays blocked and then shows the same dialog.
If I close the browser and then click "Keep waiting" the editor returns to normal.

**Comment by Holi0317** [comment] 2015-11-14 06:56
Reproduced with atom-editor-bin@1.2.0-1 from AUR, arch linux, using Firefox

Seems that Firefox does not return (or block) whenever a link is opened.

Try to use Firefox to open a link in terminal. Firefox does not give the shell back for us to use.

However, using chromium/chrome, we can use the shell after a page is opened.

This might be (in fact, I am quite sure) the cause of this issue. We need to async Firefox to fix this.

**Comment by thedanielhanke** [comment] 2016-01-22 12:06
i have the same problem, but using chrome.
its my default browser, using launchy or xdg-open confirms.
```
Distribution: Archlinux
WindowManager: I3
$ google-chrome-stable --version
=> Google Chrome 44.0.2403.157 
$ uname -r
=> 4.3.3-2-ARCH
```

happens also when my browser is opened.

**Comment by sneakypete81** [comment] 2016-04-05 11:53
Same problem: Ubuntu, Firefox, Atom 1.6.1.

@Holi0317's analysis looks sound:
If Firefox is launched with an existing browser window open, it returns immediately.
If Firefox is launched with no existing browser window open, it waits for Firefox to exit before returning.

This happens whenever the browser is launched from Atom. Help->Documentation causes the same issue.

For example, in atom/src/browser/atom-application.coffee:
```
 @on 'application:open-documentation', -> shell.openExternal('https://atom.io/docs/latest/?app')
```
I guess this is assuming that openExternal will return immediately, which doesn't happen if a Firefox window is not already open.

@benogle: are you awaiting any further reproductions?

**Comment by Holi0317** [comment] 2016-04-06 08:55
Thanks for @sneakypete81 for pointing out the location. I have just dug into the electron code and find out the issue.

https://github.com/electron/electron/blob/v0.37.4/atom/common/platform_util_linux.cc#L34

I think that is the cause of this issue. As electron.shell.openExternal tries to get the exit code and return. This blocks the call until process is finished and freeze atom.

**Comment by sneakypete81** [comment] 2016-04-07 16:16
I've had a try at a fix, but Ican't work out how to use a custom build of Electron when building Atom. Any help with this would be appreciated.

**Comment by 50Wliu** [comment] 2016-04-11 19:19
Re-opening until Atom updates to a version of Electron that contains the linked fix.

**Closed** 2016-05-23 09:07 UTC
Labels: bug, electron, linux
