### ISSUE TITLE
Opening HTML file causes editor to freeze

### ISSUE THREAD

**Issue by donald-tt** [atom/atom#10503] opened 2016-01-19 22:12 UTC
Steps to reproduce:

1. curl https://www.levycalculators.acc.co.nz/cpx.jsp > cpx.html
2. Open cpx.html in Atom 1.4

Symptoms after these steps:
* The editor freezes after a few seconds: you can't change cursor position, etc. Eventually a dialog box will appear asking if you want to keep waiting or close the window
* You can still use the menu to bring up the open file dialog
* You can resize the window and it repaints correctly

If the file is renamed to have a .txt extension, everything works just fine.

**Comment by mnquintana** [comment] 2016-01-19 22:51
Thanks for the report! :smile: This looks like a duplicate of #979 – feel free to subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) for a guide on reporting bugs, including searching for duplicates.

**Closed by mnquintana** 2016-01-19 22:51 UTC
