### ISSUE TITLE
Find file is way slower in 1.7 then it was in 1.6

### ISSUE THREAD

**Issue by umpirsky** [atom/atom#11495] opened 2016-04-16 08:45 UTC
After upgrade to 1.7 `Ctrl + P` got way slower on large project. It now takes 2-3 seconds (just to open dialog) on large project where with 1.6 was instant.

Other people complained on Twitter too https://twitter.com/tommy/status/720354578680537089, but I find this issue very important to I am posting it here.

If it can be debugged somehow, I will be happy to do it.

**Comment by 50Wliu** [comment] 2016-04-16 15:30
This is a duplicate of atom/fuzzy-finder#188 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-16 15:30 UTC
