### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Applications/Atom Beta.app/Contents/Res...

### ISSUE THREAD

**Issue by jie** [atom/atom#14637] opened 2017-05-25 06:19 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0-beta1 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Applications/Atom Beta.app/Contents/Resources/app/Applications/Atom Beta.app/Contents/Resources/app/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less'

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/theme-manager.js:323

Error: ENOENT: no such file or directory, open '/Applications/Atom Beta.app/Contents/Resources/app/Applications/Atom Beta.app/Contents/Resources/app/Applications/Atom Beta.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less'
  at Error (native)
  at Object.fs.openSync (fs.js:640:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
  at Proxy.fs.readFileSync (fs.js:508:33)
  at Proxy.fs.readFileSync (ELECTRON_ASAR.js:501:29)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (<embedded>:21010:56)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (<embedded>:20982:27)
  at <embedded>:69272:60
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (<embedded>:69270:65)
  at <embedded>:68864:23
  at Package.module.exports.Package.measure (<embedded>:68826:21)
  at Package.module.exports.Package.finishLoading (<embedded>:68860:25)
  at PackageManager.module.exports.PackageManager.loadAvailablePackage (<embedded>:20367:38)
  at PackageManager.module.exports.PackageManager.loadPackage (<embedded>:20341:27)
  at PackageManager.module.exports.PackageManager.enablePackage (<embedded>:20032:25)
  at HTMLButtonElement.enablementButtonClickHandler (<embedded>:179670:31)

```

### Commands

```
     -0:45.6.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-wx 0.1.1 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
cobalt 0.3.0 
esformatter 2.3.0 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.62.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-nginx 0.8.0 
language-ocaml 1.8.0 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
language-vue 0.21.2 
linter 2.1.4 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-python-pep8 0.2.0 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
monokai 0.20.0 
nuclide 0.229.0 
nuclide-format-js 0.0.36 
pigments 0.39.1 
python-autopep8 0.1.3 
set-syntax 0.3.2 
soda-light-ui 0.2.0 
sort-lines 0.14.0 
terminal-plus 0.14.5 
tool-bar 1.1.0 
vue-format 0.4.0 
```

**Comment by rsese** [comment] 2017-05-25 17:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14500. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-25 17:24 UTC
