### ISSUE TITLE
Claim diff in files (e.g. +99 / -99) and show yellow in tree-view even if no diff present

### ISSUE THREAD

**Issue by HamburgerTS** [atom/atom#9451] opened 2015-11-05 09:41 UTC
Claim diff in files (e.g. "+99, -99" in status-bar) and show yellow in tree-view even if no diff present. 

No diff indication in editor itself for any of these files.
"+n, -n" in status-bar for all of these files.
Git status "clean".

See screenshot:
![atomclaimdiff](https://cloud.githubusercontent.com/assets/5682504/10964556/1ad3561c-83a8-11e5-8973-66a5d9942241.PNG)

Windows10, Atom 1.1.0 (29.10.2015, 23:09:40)

Tried to remove and add the project folder. Did not help. 

Thanks for any suggestions. :-)

**Comment by 50Wliu** [comment] 2015-11-05 14:56
Duplicate of #9424 - please subscribe there for updates.  Basically what you need to do is to set `core.autocrlf` to either `input` or `false`: `git config --global core.autocrlf false`.

**Closed by 50Wliu** 2015-11-05 14:56 UTC

**Comment by HamburgerTS** [comment] 2015-11-05 15:31
Thanks for your help and sorry for the duplicate.
```
git config --global core.autocrlf input 
```
did it for me.
