### ISSUE TITLE
Lose indent when I shift lines around

### ISSUE THREAD

**Issue by corysimmons** [atom/atom#15709] opened 2017-09-21 17:10 UTC
![indent](https://user-images.githubusercontent.com/224636/30708824-21cc25f0-9ece-11e7-966d-4cbba450f5fb.gif)

Been experiencing this forever, but just ignored it. Would love it if shifting blocks of code around didn't lose the indents.

Figured I'd open an issue for it.

**Comment by rsese** [comment] 2017-09-21 19:04
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/10524. You may want to subscribe there for updates.  For future issues, it would also be super helpful if you can fill out the issue template since that gives us a lot of helpful baseline information to work with.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-21 19:04 UTC
