### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'F:/OneDrive\QouittowS front\1 kb 50 kb\...

### ISSUE THREAD

**Issue by QouittowS** [atom/atom#20053] opened 2019-10-24 01:03 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'F:\OneDrive\QouittowS front\1 kb 50 kb\200 kb 300 kb\50 kb - 100 kb\STEVEN RICHARD GIERKE's Notebook.url'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'F:\OneDrive\QouittowS front\1 kb 50 kb\200 kb 300 kb\50 kb - 100 kb\STEVEN RICHARD GIERKE's Notebook.url'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1008510)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1015439)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:989070)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2019-10-26 21:28
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-10-26 21:28 UTC
