### ISSUE TITLE
Linux HiDPI seems to break menus

### ISSUE THREAD

**Issue by Krakitos** [atom/atom#5988] opened 2015-03-16 20:31 UTC
On my Dell XPS 13 9343 (2015) atom's menus are very ... unreadable.
![capture d ecran de 2015-03-16 21 30 49](https://cloud.githubusercontent.com/assets/2241520/6675829/bcf7b43e-cc23-11e4-8363-407d07154211.png)

**Comment by mnquintana** [comment] 2015-03-17 00:42
Duplicate of #5130

**Closed** 2015-03-17 00:49 UTC
