### ISSUE TITLE
Uncaught Error: spawn /Users/sendbest/Desktop/Atom.app/Contents/Frameworks/Atom Helper.app/Conten...

### ISSUE THREAD

**Issue by RubyXiao** [atom/atom#9939] opened 2015-12-04 01:20 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/sendbest/Desktop/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/sendbest/Desktop/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/sendbest/Desktop/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/sendbest/Desktop/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/sendbest/Desktop/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/sendbest/Desktop/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/sendbest/Desktop/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:132:14)
    at /Users/sendbest/Desktop/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:825:44
    at Emitter.module.exports.Emitter.emit (/Users/sendbest/Desktop/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Project.module.exports.Project.addPath (/Users/sendbest/Desktop/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/sendbest/Desktop/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1003:26)
    at EventEmitter.outerCallback (/Users/sendbest/Desktop/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:204:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
  2x -0:44.9.0 core:undo (atom-text-editor.editor.power-mode.is-focused)
  3x -0:43.8.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
  2x -0:43.1.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
  5x -0:42.4.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  2x -0:40.9.0 core:move-up (atom-text-editor.editor.power-mode.is-focused)
     -0:38.7.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:36.9.0 snippets:next-tab-stop (atom-text-editor.editor.power-mode.is-focused)
     -0:36.9.0 snippets:expand (atom-text-editor.editor.power-mode.is-focused)
     -0:36.9.0 editor:indent (atom-text-editor.editor.power-mode.is-focused)
  2x -0:33.8.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:31.1.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -0:30.2.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:30.2.0 snippets:expand (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:20.7.0 application:quit (atom-text-editor.editor.power-mode.is-focused)
     -0:16.6.0 core:select-all (atom-text-editor.editor.power-mode.is-focused)
     -0:15.8.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-04 01:33
This is a duplicate of #9559 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-04 01:33 UTC
