### ISSUE TITLE
Project Folders are Removed When Opening Single File From Outside Project Folders

### ISSUE THREAD

**Issue by dlandis** [atom/atom#12171] opened 2016-07-14 16:38 UTC
### Prerequisites

* [√] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [√] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [N] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [√] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [√] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [√] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom forgets what your project folders are when you open a file outside of those
project folders. This happens to me regularly when I download a file (e.g. to my
Downloads folder) and then open it with Atom. When Atom opens, all my existing
project folders no longer appear in the editor. The downloaded file does get opened...
Then if I close/reopen Atom the project folders are still gone...

### Steps to Reproduce

1. Add some project folders to Atom
2. Close Atom
3. Open file outside of the aforementioned project folders in Atom (e.g. right click
and say open with atom)

**Expected behavior:** I expect my project folders to not get wiped out obviously
**Actual behavior:** Project folders gone and need to be re-added

### Versions
Latest Mac OSX
Darwin 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

atom --version

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm --version

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.9.0

**Comment by Ben3eeE** [comment] 2016-07-14 19:06
Duplicate of https://github.com/atom/atom/issues/9643

**Closed** 2016-07-15 00:30 UTC
Labels: duplicate
