### ISSUE TITLE
Closing a tab and having all tabs reorganize instantly feels weird.

### ISSUE THREAD

**Issue by madprops** [atom/atom#11694] opened 2016-05-04 23:50 UTC
When there are multiple tabs and I close one, the tab disapears and all other ones get reorganized immediately. This is instant and it just feels weird. I'm used to how Chrome and Sublime Text handle this, when you close tab there is an animation as all the other tabs change position, it feels much more natural.

**Comment by mnquintana** [comment] 2016-05-05 00:22
This is a duplicate of https://github.com/atom/tabs/issues/129 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-05-05 00:22 UTC
