### ISSUE TITLE
Editor extremely slow when a single line has many characters.

### ISSUE THREAD

**Issue by Wulf** [atom/atom#10809] opened 2016-02-13 19:12 UTC
I was trying to break apart an HTML line that has over 80,000 characters.

This is the line: [Paste](http://pastebin.com/YYeepsCP)

I pasted the line into atom (v1.5.3), and it's being really slow and hard to work with.
Scrolling horizontally sometimes freezes, adding a letter somewhere in the middle is also a big problem.

**Comment by mnquintana** [comment] 2016-02-14 17:23
Thanks for the report! This looks like a duplicate of #979 – feel free to subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) for a guide on reporting bugs, including searching for duplicates first.

**Closed by mnquintana** 2016-02-14 17:23 UTC
