### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by pangyanjin** [atom/atom#9611] opened 2015-11-16 02:36 UTC
the editor is not responding

**Comment by kkHAIKE** [comment] 2015-11-16 02:40
add more-information please

**Comment by pangyanjin** [comment] 2015-11-16 02:58
一直加载不出来，弹出编辑器未反应。
提示：
deprecationSite.getFileName is not a function
The error was thrown from the nuclide-debugger-atom package.
Create issue on the nuclide-debugger-atom package

**Comment by 50Wliu** [comment] 2015-11-16 03:19
Duplicate of #9350, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-16 03:19 UTC
