### ISSUE TITLE
Versions from 1.28.0 to 1.28.2 do not work on MacOS 10.13.6

### ISSUE THREAD

**Issue by stefanoc** [atom/atom#17698] opened 2018-07-16 11:55 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The application launches fine, but does not respond to any menu selection/keyboard shortcut.

### Steps to Reproduce

Install any version from 1.28.0 onwards on MacOS 10.13.5/10.13.6

**Expected behavior:** [What you expect to happen]

When I select a menu item like "New FIle..." or use a keyboard shortcut like Cmd-N, something should happen.

**Actual behavior:** [What actually happens]

Nothing happens.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always.

### Versions

1.28.0
1.28.1
1.28.2

### Additional Information

Version 1.27.2 works fine.

**Comment by brennenberkley** [comment] 2018-07-16 14:53
I am running Atom 1.28.2 on Mac OS 10.13.5 and could not reproduce the issue. I can open atom, create a new file, and save the file without any problems using the menu or keyboard shortcuts.

**Comment by Aerijo** [comment] 2018-07-16 14:57
@brennenberkley I believe the macOS version 10.13.6 is important. I am also fine on 10.13.5

**Comment by lee-dohm** [comment] 2018-07-16 15:02
Updating to 10.13.6 right now to test this out.

**Comment by stefanoc** [comment] 2018-07-16 15:02
@brennenberkley @Aerijo I updated only this morning to 10.13.6/1.28.2, but the issue started manifesting on Friday when I was on 10.13.5 and I had just updated do 1.28.1
Now that I think about it: I'm not 100% positive, but before Friday version 1.28.0 was working fine. 

Also, the same issue was reported here: #17690

**Comment by lee-dohm** [comment] 2018-07-16 15:21
I was just now able to launch Atom v1.28.1 on Mac OS X 10.13.6. Updating to the latest Atom Stable version now.

**Comment by lee-dohm** [comment] 2018-07-16 15:24
Now running Atom v1.28.2 on Mac OS X 10.13.6. Have you tried running Atom in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? Or [Clearing Saved State](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state)?

**Comment by stefanoc** [comment] 2018-07-17 08:56
Well, this is weird... this morning I reinstalled 1.28.2 and now it's working.

**Comment by lee-dohm** [comment] 2018-07-17 16:59
Glad to hear that things are working for you @stefanoc :grinning: Since we can't reproduce this and it is working for you now, I'm going to go ahead and close this issue for now. If anyone has any questions or more feedback, please let us know!

**Closed by lee-dohm** 2018-07-17 16:59 UTC
Labels: more-information-needed

**Comment by elvinos** [comment] 2018-07-19 10:07
Still having trouble with the issue. It appears all updates after 1.27.2, suffer from these symptons. I have had to downgrade to 1.27.2 to be able to use atom again. The timing of the issue makes me think it is something to do with the macOS 10.13.6 which came out on the 13th of July

**Comment by lee-dohm** [comment] 2018-07-20 03:43
@elvinos Please open a new issue and fill in the issue template. We haven't been able to reproduce this, even on macOS v10.13.6. Also please ensure that you're testing using [Atom v1.28.2](https://github.com/atom/atom/releases/tag/v1.28.2). There were problems with proxies and versions v1.28.0 and v1.28.1 that were resolved in v1.28.2.
