### ISSUE TITLE
Allow Users to Consent to Metrics Data Collection Before Collecting Data

### ISSUE THREAD

**Issue by Buddybenj** [atom/atom#10763] opened 2016-02-10 22:42 UTC
The only thing holding me back from using this editor is the creepy data collection which is not even made clear to the user. I would have no problem with it if Atom didn't send any usage statistics until the user consented to the data collection.

**Comment by lee-dohm** [comment] 2016-02-10 22:55
The data collection is mentioned in the Welcome screen that is shown on first run of Atom. We definitely agree that it could be made more clear.

Additionally, this is a duplicate of https://github.com/atom/atom/issues/4966. You may want to subscribe there for updates as we address people's concerns. Specifically, see the [latest comment](https://github.com/atom/atom/issues/4966#issuecomment-156536721) there for what our current plan is. We do not have an ETA for when this change will be made yet.

Thanks for your interest in Atom!

**Closed by lee-dohm** 2016-02-10 22:55 UTC
Labels: feedback

**Comment by Buddybenj** [comment] 2016-02-10 23:42
On #4966, the latest comment said that it is near the top of their list. However, it has been over a year since the issue was created. Is it actually near the top of their list? Or does GitHub not take the issue seriously?
