### ISSUE TITLE
1.0.5 Error: Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Prometheuser** [atom/atom#8305] opened 2015-08-10 16:37 UTC
That is the detail of the error:

![2ed9262d-82e7-4aad-9f03-c3b0577b13fc](https://cloud.githubusercontent.com/assets/13377095/9176872/4df8a032-3fc0-11e5-97c3-d44ca32adbb1.png)

I'm not sure what occur this, but I'm completely believe it is happening when I update to version 1.0.5.
And flow is not useful, either. I'm sorry that I cannot predicate they are same error.

**Comment by benogle** [comment] 2015-08-10 17:40
What happens when you click the 'create issue' button there? Is that not working? Can you click the copy icon next to the button, and paste it in this issue?

**Comment by Prometheuser** [comment] 2015-08-12 02:55
Sorry for late reply,  it is not working when I click the 'create issue'  button or copy icon.

**Comment by mnquintana** [comment] 2015-08-12 02:56
@Prometheuser What OS are you using?

**Comment by Prometheuser** [comment] 2015-08-12 09:13
@mnquintana 10.10.4  this error always came suddenly,  sorry I can't find the rule.

**Comment by adamjernst** [comment] 2015-08-24 14:58
Same thing:

/Users/adamjernst/.nuclide/11280534/Tools/Nuclide/pkg/nuclide/remote-connection/node_modules/ssh2/lib/client.js:136
Hide Stack Trace
TypeError: undefined is not a function
  at /Users/adamjernst/.nuclide/11280534/Tools/Nuclide/pkg/nuclide/remote-connection/node_modules/ssh2/lib/client.js:136:12


I'm using El Capitan developer beta 7

**Comment by batjko** [comment] 2015-08-24 15:09
@adamjernst Might not be related, looking at the error stack.
In your case, you are probably better off opening an issue on the Nuclide package.

**Comment by kevinsawicki** [comment] 2015-11-11 00:27
I believe this is a duplicate of https://github.com/atom/atom/issues/7987

**Closed by kevinsawicki** 2015-11-11 00:27 UTC
Labels: uncaught-exception
