### ISSUE TITLE
Lost config after opening Atom today

### ISSUE THREAD

**Issue by alexeypetrushin** [atom/atom#14922] opened 2017-06-29 09:17 UTC
Today I launched Atom and it started with dark theme with hello greeting (I had light scheme). I inspected config and it was completely blank.

Version 1.18.0 x64

**Comment by pyromaniac** [comment] 2017-06-29 15:20
The same here

**Comment by rsese** [comment] 2017-06-29 17:42
Thanks for the report @alexeypetrushin - in the future, it would be super helpful if you can completely fill out the issue template since it provides a lot of baseline information and lets you add  additional information that might help us reproduce the problem.

* Is it reproducible e.g. if you change settings now and restart Atom, are the settings lost?
* Please share the output of `atom -v`
* What operating system are you running?
* Was Atom updated to 1.18.0 today or was it already updated?
* Did you just start Atom or was Atom restarting because of package updates?
* Please share which community packages you have installed with `apm ls --installed`

/cc this recent report of settings getting lost (though it was specifically after a package upgrade) https://github.com/atom/atom/issues/14909

**Comment by rsese** [comment] 2017-06-29 17:44
@pyromaniac feel free to share the same information - if your case sounds more like https://github.com/atom/atom/issues/14909, feel free to subscribe to that issue.

**Comment by alexeypetrushin** [comment] 2017-06-29 18:27
not reproducible

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

Mac OS 10.12.4

Have no idea when it updates, I haven't updated it manually

I restarted it

```
├── atom-typescript@11.0.3
├── atom-typescript-beta@11.0.1
├── autocomplete-elixir@1.5.14
├── busy-signal@1.4.3
├── intentions@1.1.2
├── language-elixir@0.19.0
├── language-julia@0.11.0
├── language-matlab@0.2.1
├── latex-completions@0.3.2
├── linter@2.2.0
├── linter-elixirc@1.6.0
├── linter-ui-default@1.6.2
└── toggle-gutter@0.3.3
```

**Comment by rsese** [comment] 2017-06-30 18:53
Thanks for confirming @alexeypetrushin - is it just your config.cson file that's now empty or are other files also empty (e.g. keymaps, snippets, init script, stylesheet)?

**Comment by alexeypetrushin** [comment] 2017-07-01 05:45
I checked only config.cson - it was empty and stylesheet - it was intact

**Comment by runartrollet** [comment] 2017-07-13 16:19
Happened to me too today. Atom was acting a bit slow, which it sometimes does at my old computer. Restarting Atom usually helps, so I did just that and my settings from `config.cson` were gone. 
I am running Atom 1.18 on macOS Sierra.

Installed packages: 
```
├── Sublime-Style-Column-Selection@1.7.4
├── aligner-python@1.1.0
├── atom-alignment@0.13.0
├── atom-beautify@0.30.3
├── atom-clock@0.1.12
├── atom-css-clean@2.21.0
├── atom-dedupe-open-files@0.1.0
├── atom-like-brackets-editor@1.2.0
├── atom-reveal-file-in-finder@1.1.4
├── atom-runner@2.7.1
├── atom-typescript@11.0.6
├── autocomplete-css@0.16.2
├── autocomplete-html@0.8.0
├── autocomplete-json@5.5.0
├── autocomplete-python@1.9.1
├── autoprefixer@3.7.1
├── browser-plus@0.0.97
├── browser-refresh-on-save@0.0.6
├── build-npm-apm@0.12.0
├── busy-signal@1.4.3
├── change-case@0.6.5
├── color-picker@2.2.5
├── colorblind-wombat-dark-syntax@0.6.0
├── cursor-history@0.11.1
├── dash@1.7.1
├── emmet@2.4.3
├── enhanced-tabs@1.7.0
├── expand-region@0.3.0
├── expand-selection-to-quotes@0.11.0
├── file-icons@2.1.8
├── filecolor@0.4.0
├── fold-comments@0.6.0
├── gitignore-snippets@0.2.5
├── golden-ratio@0.3.0
├── goto@1.8.3
├── highlight-line@0.12.0
├── highlight-selected@0.13.1
├── intentions@1.1.2
├── javascript-snippets@1.2.1
├── jumpy@3.1.3
├── kite@0.30.1
├── language-c@0.58.1
├── language-clojure@0.22.3
├── language-csharp@0.14.2
├── language-css@0.42.2
├── language-csv@1.1.2
├── language-django@0.1.1
├── language-gfm@0.89.1
├── language-go@0.44.1
├── language-html@0.47.3
├── language-java@0.27.2
├── language-javascript@0.126.1
├── language-json@0.19.1
├── language-json-comments@0.16.3
├── language-latex@1.0.0
├── language-less@0.32.0
├── language-lua@0.9.11
├── language-make@0.22.3
├── language-markdown@0.23.0
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-pgsql@0.2.3
├── language-php@0.39.0
├── language-python@0.45.3
├── language-restructuredtext@1.1.0
├── language-sass@0.59.0
├── language-sql@0.25.6
├── language-sql-mysql@0.3.1
├── language-xml@0.35.1
├── language-yaml@0.30.0
├── latex-hyperclick@0.2.0
├── latextools@0.8.5
├── linter@2.2.0
├── linter-chktex@1.3.1
├── linter-csslint@1.3.4
├── linter-htmlhint@1.3.3
├── linter-jshint@3.1.5
├── linter-jsonlint@1.3.0
├── linter-pylama@0.9.3
├── linter-python-pep8@0.2.0
├── linter-rst@0.0.3
├── linter-spell@0.14.0
├── linter-spell-latex@0.9.2
├── linter-ui-default@1.6.2
├── lipsum@0.1.0
├── lorem@1.2.1
├── markdown-preview-plus@2.4.10
├── markdown-writer@2.6.5
├── open-in-browsers@0.0.30
├── open-recent@5.0.0
├── pdf-view@0.59.0
├── pigments@0.39.1
├── preview-inline@1.4.7
├── python-indent@1.1.0
├── remove-whitespace@0.2.1
├── rulerz@0.4.3
├── script@3.15.0
├── simply-django-atom@0.0.2
├── sort-lines@0.14.0
├── spell-check@0.72.0
├── split-diff@1.4.3
├── swackets@0.26.0
├── symbols-view@0.116.1
├── sync-settings@0.8.2
├── tab-to-escape@0.1.0
├── tablr@1.8.3
├── tabularize@0.2.5
├── text-pastry@0.6.1
├── todo-show@1.11.0
├── turbo-javascript@1.4.0
├── wakatime@7.0.3
└── zentabs@0.8.8
```

**Comment by mminkoff** [comment] 2017-07-14 15:35
It's happened to me twice in the last day.  Once was in the middle of a session.

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

macOS Sierra 10.12.5

├── Handlebars@1.8.0
├── advanced-open-file
├── aligner@1.2.3
├── aligner-javascript@1.2.0
├── atom-beautify@0.30.4
├── atom-ember-frost-syntax@1.0.0
├── atomic-emacs@0.11.0
├── autoclose-html@0.23.0
├── autocomplete-clang@0.11.3
├── autocomplete-emojis@2.5.0
├── build@0.68.0
├── busy@0.7.0
├── busy-signal@1.4.3
├── case-keep-replace@0.6.0
├── chestnut-light-atom-syntax@0.2.1
├── clipboard-plus@0.5.1
├── coffee-compile@0.26.0
├── color-picker@2.2.5
├── emacs-flow@0.1.2
├── emacs-plus@0.11.1
├── ember-cli-helper@0.9.0
├── ember-tabs@2.4.3
├── file-icons@2.1.8
├── git-blame@1.1.1
├── git-tab-status@1.9.2
├── gruvbox-plus-syntax@1.3.1
├── intentions@1.1.2
├── isotope-light-ui@2.2.7
├── language-ini@1.19.0
├── linter@2.2.0
├── linter-ember-template@0.2.0
├── linter-eslint@8.2.1
├── linter-gcc@0.7.1
├── linter-js-standard@3.9.1
├── linter-jshint@3.1.5
├── linter-ui-default@1.6.2
├── merge-conflicts@1.4.5
├── minimap@4.28.3
├── node-debugger@1.10.1
├── package-list@0.1.2
├── pigments@0.39.1
├── platformio-ide@2.0.0-beta.7
├── platformio-ide-debugger@1.2.3
├── platformio-ide-terminal@2.5.3
├── prettier-atom@0.36.1
├── project-manager@3.3.5
├── sequential-command@0.3.0
├── solarized-dark-apparent-ui-successor@0.2.0
├── solarized-dark-ui@0.3.2
├── solarized-light-ui@0.1.0
├── split-diff@1.4.3
├── text-transformer@0.1.1
├── tool-bar@1.1.0
├── unicorn-light-syntax@3.1.0
├── unicorn-light-ui@2.1.0
├── unicorn-ui@1.2.0
├── zenburn@3.1.0
└── zentabs@0.8.8

though not all packages are enabled.

1.18 was installed some time ago.  One of my packages might have been recently installed but I don't remember which.  When it happened today I was in the middle of editing a file.

**Comment by mminkoff** [comment] 2017-07-14 15:46
Packages I have in common with @runartrollet:

├── busy-signal@1.4.3 (disabled for me)
├── color-picker@2.2.5 
├── file-icons@2.1.8
├── intentions@1.1.2
├── linter@2.2.0
├── linter-jshint@3.1.5
├── linter-ui-default@1.6.2
├── pigments@0.39.1
├── split-diff@1.4.3
└── zentabs@0.8.8

None seem to have been updated in the last few days.

**Comment by rsese** [comment] 2017-07-20 22:56
We brought up this issue with the team and it seems like it'll be tough to track down the problem without steps to reproduce (which might not be easy to come by for this particular issue).  And between this issue and https://github.com/atom/atom/issues/14909, it doesn't seem like there's a common community package across reports.

There was one followup question that was mentioned but there was agreement that we should go ahead and close this as a duplicate of https://github.com/atom/atom/issues/14909 (which I didn't initially tag as a duplicate since it seemed like the report here didn't involve updating packages).

I'll go ahead and copy over comments with packages lists to https://github.com/atom/atom/issues/14909.

**Closed by rsese** 2017-07-20 22:56 UTC
Labels: more-information-needed
