### ISSUE TITLE
Malformed urls in package search

### ISSUE THREAD

**Issue by Krinkle** [atom/atom#7531] opened 2015-06-29 06:58 UTC
* Avatar broken.
* Username is missing first character.
* User link points to 404 Not Found: https://atom.io/users/
* Clicking "Report issues" triggers a dialog about invalid URL with `%@`.

![screen shot](https://cloud.githubusercontent.com/assets/156867/8402616/90a6edf6-1e34-11e5-817b-b6c9658405c3.png)

**Comment by thomasjo** [comment] 2015-06-29 07:19
Are you able to reproduce this in safe mode? `atom --safe`
In addition, what version of OS X are you using?

**Comment by izuzak** [comment] 2015-06-29 07:24
Sounds like a duplicate of https://github.com/atom/settings-view/issues/543

**Closed by izuzak** 2015-06-29 07:24 UTC
Labels: more-information-needed
