### ISSUE TITLE
Uncaught Error: EBUSY, open 'c:\Users\amita\OneDrive - HCL Technologies Ltd- 1\Amit\CloudFormation\Practice\EC2.yml'

### ISSUE THREAD

**Issue by amitdevops** [atom/atom#18965] opened 2019-03-11 07:18 UTC
Uncaught Error: EBUSY, open 'c:\Users\amita\OneDrive - HCL Technologies Ltd- 1\Amit\CloudFormation\Practice\EC2.yml'

**Atom Version**: 0.162.0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At c:\Users\amita\AppData\Local\atom\app-0.162.0\resources\app\node_modules\q\q.js:126

Error: EBUSY, open 'c:\Users\amita\OneDrive - HCL Technologies Ltd- 1\Amit\CloudFormation\Practice\EC2.yml'
  at Error (native)

```

**Comment by rsese** [comment] 2019-03-11 19:25
Thanks for contributing!

Guessing this is specific to files stored with OneDrive?  In any case, we noticed that this looks like a duplicate of https://github.com/atom/atom/issues/3365 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-03-11 19:25 UTC
