### ISSUE TITLE
Disable "Check for updates at startup"

### ISSUE THREAD

**Issue by klaszlo** [atom/atom#7339] opened 2015-06-19 07:30 UTC
I'm often developing en route, that means via tethering my mobile phone internet access.
So I have a pretty limited data access for each month (1GiB in my case).

So I would like to minimize internet usage. So I don't need automatical update checking at each startup.
It consumes about 2MB of data. Since I restart atom a lot, it piles up quickly.

I searched through the forum, looked around settings, but could not find anything similar of disabling update checking.

Can an option be added to the settings page? It would be greatly appreciated. 
Sometimes, when I'm home, does not bother much this additional internet usage.

I hope you appreciate my feature request.

**Comment by lee-dohm** [comment] 2015-07-08 04:48
As a workaround, you can build Atom from source. When you do (even if it is the same commit as a released version), Atom disables update checking.

**Comment by robyoder** [comment] 2015-10-13 04:50
+1, but ooh nice tip, @lee-dohm

**Comment by Zireael07** [comment] 2015-10-13 07:54
I believe this is a dupe of an existing issue, but I can't find the other one atm - I only remember arguments such as being on a shitty modem connection in Indonesia.

**Comment by 50Wliu** [comment] 2015-10-13 11:51
@Zireael07 Found it: #1882.

**Closed by 50Wliu** 2015-10-13 11:51 UTC
Labels: enhancement

**Comment by AnwarShah** [comment] 2016-04-24 13:22
@lee-dohm I built atom from source. But, it is still checking for update from version 1.5.3!

**Comment by Zireael07** [comment] 2016-04-24 15:10
This hasn't been implemented yet.

**Comment by 50Wliu** [comment] 2016-04-24 16:55
@Zireael07 Yes it has - it's been available since Atom 1.5.0.

**Comment by Zireael07** [comment] 2016-04-25 08:59
So why is it still checking for update? I'm on 1.7.x...

**Comment by 50Wliu** [comment] 2016-04-25 16:34
You have to disable the auto-checker in Help->About.

**Comment by AnwarShah** [comment] 2016-04-26 13:02
50Wliu I don't find anything like that in Help -> About

**Comment by robyoder** [comment] 2016-04-26 19:31
On Mac it's in _Atom > About Atom_

<img width="656" alt="screen shot 2016-04-26 at 1 30 42 pm" src="https://cloud.githubusercontent.com/assets/622513/14831465/2a5915c0-0bb3-11e6-84a0-8282b99aecb1.png">

**Comment by liapis** [comment] 2017-12-31 14:56
Settings > Core >  Automatically Update

/home/bduser/Pictures/atom.png

**Comment by stevekm** [comment] 2018-04-10 13:48
This also seems to cause a lot of problems with CyberDuck. Any time Atom is downloading an update, or has a downloaded update ready for installation, CyberDuck is unable to open files for editing in Atom until the update has been resolved. Admittedly, this might be more of a CyberDuck problem, but Atom is the only program I have found that has this issue. Since Atom has monthly releases, it means that with auto-update enabled it breaks every month with CyberDuck.

<img width="608" alt="screen shot 2018-04-10 at 9 40 33 am" src="https://user-images.githubusercontent.com/10505524/38560347-709c1e1a-3ca3-11e8-8c81-7b1c0d0f9ba0.png">
<img width="554" alt="screen shot 2018-04-10 at 9 40 52 am" src="https://user-images.githubusercontent.com/10505524/38560353-73a4f32a-3ca3-11e8-9ab3-742b9f0beb34.png">
