### ISSUE TITLE
editor: escape key no longer consolidates selections

### ISSUE THREAD

**Issue by zmb3** [atom/atom#16188] opened 2017-11-14 23:22 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using multiple cursors, I used to be able to press <kbd>esc</kbd> to go back to a single cursor.

On a recent build from master, pressing the escape key after creating multiple selections has no effect.

Note:  everything works _as expected_ in the 1.23 beta, so this must have been introduced recently.  Everything also works correctly when I use other commands (like `editor:add-selection-below`) to 

Everything also works correctly if I invoke `editor:consolidate-selections` from the command palette, so it appears that for whatever reason the escape key is no longer dispatching that command.

### Steps to Reproduce

1. Open a new editor
2. Create multiple cursors (either by using `editor:add-selection-below` or `find-and-replace:select-next`, for example).
3. Press the escape key

**Expected behavior:** All but one cursor goes away.

**Actual behavior:** Multiple cursors remain active

**Reproduces how often:** Always

### Versions

```
❯ atom -version
Atom    : 1.24.0-dev-a1b09dcf1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by 50Wliu** [comment] 2017-11-14 23:28
Can't reproduce on Atom 1.24.0-dev-4321db050, Windows 10 x64.  What is the Keybinding Resolver reporting?

**Comment by zmb3** [comment] 2017-11-14 23:37
In the broken 1.24 build, when I press escape I see `autocomplete-plus:cancel` as the top of the command stack, then `editor:consolidate-selections` followed by `core:cancel`.

In the beta that's behaving correctly I only see `editor:consolidate-selections` and `core:cancel`.  The autocomplete plus one is further down and greyed out with an X next to it.

**Comment by maxbrunsfeld** [comment] 2017-11-14 23:42
I'm seeing this on master. Looking into it now.

**Comment by 50Wliu** [comment] 2017-11-14 23:56
Looks like this was introduced pretty recently then, as 4321db050 is only four days old.  Between 4321db050 and a1b09dcf1, cb82a4201d87a0b4879f28ab1e74c347cd5cccf4 looks like the most likely culprit.

**Comment by maxbrunsfeld** [comment] 2017-11-15 01:35
I believe this was fixed by https://github.com/atom/autocomplete-plus/commit/767ac6fb9a6b5ae6a6f4ed506b7404351f926b5d.

**Closed by maxbrunsfeld** 2017-11-15 01:35 UTC
Labels: bug, regression, triaged
