### ISSUE TITLE
Is there a way to build atom to run off of a server as a web site. 

### ISSUE THREAD

**Issue by mmiscool** [atom/atom#18454] opened 2018-11-17 21:27 UTC
## Summary
I would like to self host a IDE that i can use from my web browser from any where.
This would make my life supper awesome. And self hosting is really required because I am paranoid. 

## Motivation
Well atom is an awesome IDE but it would be more awesome if i could run it from any where with out installing it from a web browser. 

The ability to self host it would really come in handy and simplify my mobile life style. 

## Describe alternatives you've considered

I thought about making a php page with a large text area but this was not suitable for larger projects. 

## Additional context

![atom example](https://user-images.githubusercontent.com/6439772/48665929-b1d6e280-ea85-11e8-9415-7f85ff80dfa9.png)

**Comment by thomasjo** [comment] 2018-11-18 07:58
This is not currently planned. Closing as duplicate of https://github.com/atom/atom/issues/3088

**Closed by thomasjo** 2018-11-18 07:58 UTC
