### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by huzeyfecoskun** [atom/atom#7241] opened 2015-06-12 00:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\app.asar\src\window-event-handler.js:148:33)
  at HTMLDocument.handler (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\ninesCTwoDuo\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  2x -1:56.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:54.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:47.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:45.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:38.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:37.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:35.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:33.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:32 editor:newline (atom-text-editor.editor.is-focused)
     -1:30.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:24.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:23.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:22.8.0 core:move-up (atom-text-editor.editor.is-focused)
 11x -1:22.1.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:20.9.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -1:18.9.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.5.9
linter, v0.12.7

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-06-12 00:50
Duplicate of #6548, please subscribe there for updates.

**Closed by 50Wliu** 2015-06-12 00:50 UTC
