### ISSUE TITLE
atom编辑的文件不能立即刷新

### ISSUE THREAD

**Issue by phpstudyOne** [atom/atom#14796] opened 2017-06-16 02:42 UTC
我使用 atom 和 sublime 同时打开一个项目，在 atom 编辑了内容能在 sublime里立马看到变化，
但是 在sublime 里编辑文件，无法再atom里看到修改 。

如果使用sublime 和 其他的编辑器  ，比如 phpstorm  , vs code  ,都能 一边修改，另一边立马看到修改的内容 。

**Comment by kkpoon** [comment] 2017-06-16 03:39
Please change the issue subject to:

> Opened file does not update when the file is changed by external parties

**Comment by kkpoon** [comment] 2017-06-16 03:43
I help to translate the issue:

> When I opened a file in atom and another external editor, like sublime, the changes does not sync. When I save a file in atom, sublime aware the file has been changed and auto reload the new content. But Atom does not aware the file has been changed by other parties and auto reload the latest content.

**Comment by 50Wliu** [comment] 2017-06-16 04:32
Thanks for the translation @kkpoon :grinning:.

We noticed that this is a duplicate of #14709. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-06-16 04:32 UTC
