### ISSUE TITLE
Cannot find module '/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/Resources/atom.asar/browser/lib/init.js'

### ISSUE THREAD

**Issue by dcalixto** [atom/atom#9599] opened 2015-11-15 06:00 UTC
sorry, seems that don't have to do with newrelic js. but digging on console shows this:

/Applications/Atom.app/Contents/Frameworks/Atom\ Helper.app/Contents/MacOS/Atom\ Helper ; exit;
module.js:336
    throw err;
          ^
Error: Cannot find module '/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/Resources/atom.asar/browser/lib/init.js'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:125:18)
    at node.js:960:3

**Comment by lee-dohm** [comment] 2015-11-15 06:22
What exactly is the issue here? Are you having trouble with a package? Is Atom crashing? What is going on?

Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by jeancroy** [comment] 2015-11-15 15:26
Issue title should probably be changed.

> Cannot find module '/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/Resources/atom.asar/browser/lib/init.js'

You cannot find a core part of atom, if atom--safe does not help maybe you can try to reinstall.

**Comment by lee-dohm** [comment] 2015-12-17 07:12
Since there hasn't been a response to the request for more information, I'm going to close this. Please let us know if there is more information you can give us to help us understand :grinning:

**Closed by lee-dohm** 2015-12-17 07:12 UTC
Labels: more-information-needed
