### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by lunertexcosmo** [atom/atom#7336] opened 2015-06-19 01:09 UTC
[Enter steps to reproduce below:]

All I did was right click on a folder in the browser.

**Atom Version**: 0.210.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\James\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\James\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  7x -5:55.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:48.3.0 core:save (atom-text-editor.editor.is-focused)
  8x -3:52.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:42.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
latex, v0.24.1
linter, v0.12.7
linter-rubocop, v0.2.7

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-06-19 01:18
Duplicate of #6548, please subscribe there for updates.

**Closed by 50Wliu** 2015-06-19 01:18 UTC
