### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by StevenMichel** [atom/atom#5981] opened 2015-03-16 11:56 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: STEVENMICHEL
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///C:/Users/Steven%20Michel/AppData/Local/atom/app-0.187.0/resources/app/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5CSteven%20Michel%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.187.0%5C%5Cresources%5C%5Capp%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CSteven%20Michel%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.187.0%5C%5Cresources%5C%5Capp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.187.0%22%2C%22shellLoadTime%22%3A4599%2C%22initialPaths%22%3A%5B%5D%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at C:\Users\Steven Michel\.atom\packages\terminal-status\lib\command-output-view.coffee:38:26
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "bootstrap-3-snippetset",
      "atom-csscomb",
      "colorpicker",
      "css-comb",
      "bootstrap3-snippets",
      "livereload",
      "command-toolbar",
      "clipboard-history",
      "html-img",
      "Search",
      "atom-minjs",
      "symbols-view",
      "preview-plus",
      "grunt-runner",
      "php-getters-setters"
    ],
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-backbone, v0.6.0
atom-ctags, v2.6.0
autoclose-html, v0.15.0
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
color-picker, v1.4.4
css-color-underline, v1.0.1
css-snippets, v0.5.0
csslint, v1.0.4
emmet, v2.3.4
file-icons, v1.5.1
file-types, v0.3.0
highlight-line, v0.10.1
html-helper, v0.2.3
html-id-class-snippets, v1.4.1
javascript-snippets, v1.0.0
jsformat, v0.7.18
jshint, v1.3.0
keybinding-cheatsheet, v0.0.8
language-css-plus, v0.3.0
linter, v0.12.0
linter-bootlint, v0.0.3
linter-csslint, v0.0.11
linter-htmlhint, v0.0.8
linter-jscs, v1.9.0
linter-jshint, v0.1.0
linter-php, v0.0.11
linter-phpcs, v0.0.12
linter-phpmd, v0.0.10
linter-tidy, v1.0.0
local-history, v2.2.2
minimap, v4.6.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
phpunit, v1.0.9
phpunit-snippets, v0.1.0
project-manager, v1.15.5
project-palette-finder, v2.4.16
script, v2.18.0
seti-syntax, v0.3.3
symbols-tree-view, v0.6.1
terminal-status, v1.3.5
web-browser, v1.4.2
windows-context-menu, v0.3.1

# Dev
No dev packages
```

**Comment by indcoder** [comment] 2015-03-16 13:18
This occurs while downloading the terminal status package

**Comment by izuzak** [comment] 2015-03-20 19:31
@indcoder Can you reliably reproduce the problem? I just tried installing that package and it installed just fine. Also which OS are you using?

**Comment by kevinsawicki** [comment] 2015-04-28 20:54
I believe this is a duplicate of https://github.com/guileen/terminal-status/issues/40 which had been fixed in that package.

**Closed by kevinsawicki** 2015-04-28 20:54 UTC
Labels: more-information-needed
