### ISSUE TITLE
> 100% cpu (in safe mode)

### ISSUE THREAD

**Issue by AnthonyWC** [atom/atom#14327] opened 2017-04-29 18:21 UTC
Ran atom in safe-mode; on a fresh reboot.

![image](https://cloud.githubusercontent.com/assets/6215805/25557794/f27630b0-2ce6-11e7-8089-a97d4f8913df.png)

Doesn't seem to stabilize (try waiting > 10 min) 

```
atom --version                                                                            
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by rsese** [comment] 2017-05-01 20:34
I just installed 1.16.0 on Ubuntu 16.04 and I don't this issue - did this just start happening recently @AnthonyWC?    And is it always reproducible when you start Atom?

Lastly, do you see the same issue if you temporarily reset to factory defaults [1]?

[1]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults 

---

As a side note, it would be super helpful for us if you can completely fill out the issue template for new issues ✌️

**Comment by AnthonyWC** [comment] 2017-05-02 21:01
Problem seems to have disappeared after I did factory default and revert back (after I did the mv ~/.atom to ~/.atom/backup and then re-copy back the files).  Not sure why; but atom still seems to have fairly high cpu usage but no longer stuck @100%.  I can do a strace if that helps.

**Comment by eboracus** [comment] 2017-06-18 20:17
Are you still seeing this @AnthonyWC, or was there a resolution on your end? @rsese

I am experiencing something very similar with Atom 1.18.0 on Linux (different distribution, Manjaro Linux). For me I see total CPU usage immediately rise to 25% (~100% on one core as shown above, but with only 4 cores here) and remain stable at this value indefinitely.

**Steps to reproduce:**

1. Install/Run atom on Linux
a. Backup `~/.atom` folder for factory reset
b. Startup atom (normal mode & safe mode both see the problem)
3. CPU immediately rises to ~25% after startup (no need to execute any commands) and remains steady indefinitely...

**Occurrence frequency:** 100% of atom startups

Don't recall at all when it first started for me, been positively observing same situation since recent system reinstall a few weeks/month ago at very least.

System activity monitor shows constant CPU usage:
![170618_atom_cpu_usage](https://user-images.githubusercontent.com/11758299/27263786-ba2553a4-5468-11e7-8435-3e5fb21fa717.png)

Though brief CPU profile taken whilst observing this usage on the system didn't seem to show much activity(?)
![170618_atom_cpu_profile](https://user-images.githubusercontent.com/11758299/27263791-cedcfca2-5468-11e7-980f-4dff17614398.png)

CPU Profile info shows `(idle)` for >99% of duration:
![170618_atom_cpu_profile_info](https://user-images.githubusercontent.com/11758299/27263877-e372e7a6-546a-11e7-8dd4-fdff9a6011d0.png)

Atom    : 1.18.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0

**Comment by AnthonyWC** [comment] 2017-06-18 21:34
I actually no longer use atom; also currently using a different computer but I can try on Monday.

**Comment by 50Wliu** [comment] 2017-06-18 22:15
@eboracus Thanks for reaching out!

We've determined that you are using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

**Comment by eboracus** [comment] 2017-07-24 23:15
Thanks for the information @50Wliu, that is certainly a sensible position for the Atom team. I'd tried a few different builds of Atom, including built-in components matching the stable branch as far as I could see to no avail.

It turns out my issue was actually hiding deeper with Electron. Searched high and low for CPU related issues/threads in the Atom-verse, but didn't go look in Electron issues. I've learned my lesson. :disappointed:

For information, for anyone who happens to pass by here suffering a similar problem - the guilty party for me was the combination of using the Global Menu (KDE desktop widget) along with (any) Electron application, as described here [https://github.com/electron/electron/issues/8455](https://github.com/electron/electron/issues/8455). It's currently an unresolved bug and the temporary workaround posted in that thread worked perfectly for me. :+1:

Not sure if this was related to the original issue (given the Ubuntu... would need to have been a KDE version) so can't say this should be closed(?). Would've accounted for the lack of repro though.

**Comment by 50Wliu** [comment] 2017-07-26 03:07
Thanks for the update @eboracus 👍.  Looks like there's an open PR for that issue so hopefully it'll get merged soon :).

It looks like this issue is at a dead-end since it doesn't happen anymore and @AnthonyWC is no longer using Atom.  I'm going to close this but don't hesitate to reach out if you switch back and it starts happening again.

**Closed by 50Wliu** 2017-07-26 03:07 UTC
Labels: linux, more-information-needed
