### ISSUE TITLE
Cannot find atom-shell v0.22.3 from GitHub [Error: Not Found]

### ISSUE THREAD

**Issue by gevero** [atom/atom#6415] opened 2015-04-17 09:26 UTC
Building atom from source
 My system:
```
manjaro-linux 3.16.7.9-1-MANJARO
Node: v0.12.2
npm: v2.7.5
```
when running script/build I get:
```
Cannot find atom-shell v0.22.3 from GitHub [Error: Not Found]
Aborted due to warnings."
```
The install procedure always worked fine, but not today.

**Comment by YuriSolovyov** [comment] 2015-04-17 11:12
could be caused by [renaming atom-shell to electron](https://github.com/atom/electron/pull/1389)

**Comment by gevero** [comment] 2015-04-17 14:51
So I guess that [grunt-download-atom-shell](https://github.com/atom/grunt-download-atom-shell) should be modified?

**Comment by YuriSolovyov** [comment] 2015-04-17 15:00
@gevero maybe [this line](https://github.com/atom/grunt-download-atom-shell/blob/master/tasks/download-atom-shell-task.coffee#L129) ?

**Comment by sclausen** [comment] 2015-04-17 19:46
+1

**Comment by slackmoehrle** [comment] 2015-04-17 21:22
+1

**Comment by 50Wliu** [comment] 2015-04-17 21:56
This is being worked on in atom/grunt-download-atom-shell#23, no need to panic :wink:.

**Comment by ioquatix** [comment] 2015-04-18 08:35
+1

**Comment by sclausen** [comment] 2015-04-18 21:33
@50Wliu maybe we're a bit impatient, but nothing happens... so: PANIC!!!!!!

**Comment by slackmoehrle** [comment] 2015-04-18 21:36
And where is the testing? I understand things happen, but some of us rely on building versus having to update releases by downloading a binary. For me, using the build in update never works.

**Comment by Morgan-Leon** [comment] 2015-04-19 01:53
![screenshot](https://cloud.githubusercontent.com/assets/8945216/7217831/bd922756-e679-11e4-8eeb-4bb0cbe83e62.png)
IOS 10.10.2 has the same problem.

**Comment by slackmoehrle** [comment] 2015-04-19 01:56
What app is that behind the terminal?  @Morgan-Leon

**Comment by ioquatix** [comment] 2015-04-19 02:51
Hey guys, I found a quick fix for arch users

```
pacman -R atom-editor
yaourt -S atom-editor-bin
```

Worked for me just fine.

**Comment by JordiOrlando** [comment] 2015-04-19 03:29
Can confirm @ioquatix's workaround worked for me on Arch

**Comment by auxiliary** [comment] 2015-04-19 06:46
@ioquatix's workaround worked for me on Arch too.

**Comment by tosmarcel** [comment] 2015-04-19 13:52
@ioquatix's method worked for me on Arch too. Thx!

**Comment by sashka** [comment] 2015-04-19 20:36
```
Running "download-atom-shell" task
>> Cannot find atom-shell v0.22.3 from GitHub [Error: Not Found]
Aborted due to warnings.
```
+1

**Comment by aruscher** [comment] 2015-04-20 18:28
should be fixed in the current master release 46f90f09841e220b28a81a5c207421c63c9bc573

**Closed** 2015-04-20 18:29 UTC
Labels: build-error, in-progress

**Comment by SergioScabuzzo** [comment] 2015-04-21 00:56
Node: v0.12.2
npm: v2.7.4


After latest update, now getting past:
 Running "download-atom-shell" task

But fails at next step:
Running "download-atom-shell-chromedriver" task
>> Cannot find atom-shell v0.22.0 from GitHub [Error: Not Found]
Aborted due to warnings.

**Comment by kevinsawicki** [comment] 2015-04-21 00:57
@SergioScabuzzo what command did you run?

**Comment by SergioScabuzzo** [comment] 2015-04-21 01:01
@kevinsawicki  sudo script/build
Followed the build instructions for linux.

**Comment by kevinsawicki** [comment] 2015-04-21 01:03
@SergioScabuzzo what is the SHA-1 of the commit you are trying to build?

**Comment by SergioScabuzzo** [comment] 2015-04-21 01:55
Sorry if I'm kinda dense. 
I think this is it 9a0c3f9

**Comment by SergioScabuzzo** [comment] 2015-04-21 04:01
@kevinsawicki Never mind... I checked out 46f90f0 and it worked fine. Should have done my due dilligence. 

Thanks
