### ISSUE TITLE
incompatible with Microsoft Pinyin

### ISSUE THREAD

**Issue by EMLVIRUS** [atom/atom#15237] opened 2017-08-10 13:30 UTC
With latest update to 1.19.0, ATOM is incompatible with Microsoft Pinyin (the built-in Chinese IME) on Windows 10.15063.540: you can't see what you have typed.

![image](https://user-images.githubusercontent.com/16912240/29172626-0ff5cbdc-7e13-11e7-88e1-c5350b22bfa2.png)

And this is what I have typed:
![image](https://user-images.githubusercontent.com/16912240/29172648-2590d6d0-7e13-11e7-98b7-b7561a1908f3.png)

**Comment by 50Wliu** [comment] 2017-08-10 13:34
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14911. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-10 13:34 UTC
