### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat 'D:/mocha\extensions'

### ISSUE THREAD

**Issue by kot83** [atom/atom#18369] opened 2018-10-31 02:59 UTC
### Reproduction

1. Move/drag a folder into another.

### Notes
- This may be an issue with my disk.

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat 'D:\mocha\extensions'

```
At fs.js:1661

Error: EPERM: operation not permitted, lstat 'D:\mocha\extensions'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:916471)
    at TreeView.t.exports.TreeView.onDrop (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:922260)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:896171)
```

### Commands

```
     -5:19.5.0 core:confirm (input.hidden-input)
  2x -5:11.3.0 core:save (input.hidden-input)
     -1:01.8.0 core:move-left (input.hidden-input)
  3x -1:01.3.0 core:backspace (input.hidden-input)
     -0:58.9.0 core:save (input.hidden-input)
     -0:54.1.0 core:move-left (input.hidden-input)
     -0:53.6.0 editor:newline (input.hidden-input)
  4x -0:53 core:backspace (input.hidden-input)
 17x -0:47.8.0 core:move-left (input.hidden-input)
     -0:46.4.0 core:move-right (input.hidden-input)
     -0:46.1.0 core:backspace (input.hidden-input)
     -0:44.9.0 core:save (input.hidden-input)
     -0:43.8.0 core:backspace (input.hidden-input)
 16x -0:43.3.0 core:move-right (input.hidden-input)
     -0:41.7.0 core:backspace (input.hidden-input)
     -0:40.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.8.4 
```

**Comment by kot83** [comment] 2018-10-31 03:04
Seems like I deleted the folder in the terminal, but atom still had it on the list.

**Comment by rsese** [comment] 2018-10-31 20:09
Thanks for contributing!

We noticed that based on the stack trace, this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

> Seems like I deleted the folder in the terminal, but atom still had it on the list.

Thanks for the detail :+1:

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-31 20:09 UTC
