### ISSUE TITLE
Closing Atom and re-opening doesn't save the files etc. I had open

### ISSUE THREAD

**Issue by theonlygusti** [atom/atom#12418] opened 2016-08-14 16:24 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? _(to the best of my knowledge)_
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? _I think so, but maybe I should see the developers of [save-session](https://atom.io/packages/save-session) as well_
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Whenever I close atom, after working on a project, the project is seemingly "lost."

Upon re-opening of atom, none of the tabs I had open, none of the project folders I had open, are retained.

I made a short 2-minute video to demonstrate: https://sendvid.com/qocn3pz4

As you can see, no matter how I close the editor (via CMD+Q or the Red X) the problem ensues.

### Steps to Reproduce

1. Open atom.
2. Add project folder, open some files, open some tabs, just normal routine.
3. Close and re-open atom.

**Expected behavior:** Atom would remember all the files and folders I had open, and present me with an editor in exactly the same state as when I quit the Application.

**Actual behavior:** Atom opens a blank (empty) editor, without any documents open (I have "Open blank editor on startup" set to false)

### Versions

```
$ atom --version
Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4
```

I am using Mac OSX El Capitan 10.11.6

**Comment by Nikki1993** [comment] 2016-08-14 19:57
I think that was discussed by  @lee-dohm and he mentioned that Atom opens a new instance rather than opening a "previous" one when clicking on a dock bar. That's not necessarily a bug but the way Electron apps work.

**Comment by theonlygusti** [comment] 2016-08-15 09:22
@Nikki1993  I am not clicking on a doc bar, I am launching atom via spotlight or via the terminal, and neither methods preserves the previous state.

**Comment by Nikki1993** [comment] 2016-08-15 11:05
@theonlygusti neither should. As I said, this is not a bug but a "feature" or a way Atom works. It does not preserve application state and opens new instance each time you launch it regardless of the method.

**Comment by yuanwhy** [comment] 2016-08-24 13:23
this PR fix the bug https://github.com/atom/atom/pull/12486

**Comment by andyrichardson** [comment] 2016-09-23 16:43
From what I can tell, you're not closing and re-opening atom. You're merely closing your session window and opening a new one. As you can see from the indicator in the dock, Atom never stops running.

If you were to close atom (finderbar -> Atom -> Quit Atom) I think you'd see that, when reopening, your session is restored. There is no need for any third party packages.

**Comment by theonlygusti** [comment] 2016-09-29 22:49
@andyrichardson  which is exactly what I have been doing.... and it hasn't been working... anyway I don't use atom any more so I don't really care.

**Comment by iolsen** [comment] 2016-10-10 16:49
>From what I can tell, you're not closing and re-opening atom. You're merely closing your session window and opening a new one. As you can see from the indicator in the dock, Atom never stops running.

>If you were to close atom (finderbar -> Atom -> Quit Atom) I think you'd see that, when reopening, your session is restored. There is no need for any third party packages.

There is a similar issue, https://github.com/atom/atom/issues/10474, which will be addressed.

**Closed by iolsen** 2016-10-10 16:49 UTC
