### ISSUE TITLE
Atom and external screens

### ISSUE THREAD

**Issue by patriksvensson** [atom/atom#9079] opened 2015-10-08 07:45 UTC
I don't know how to describe this accurately, but I will give it a try.

**Background**
I use a laptop with a dock at work to use two extra screens. When connected to the dock I use Atom on an external screen and it works great.

**Problem**
The problem is when I close Atom and disconnect the laptop from my dock and later starts Atom again, it thinks that it's still on the external screen. Normally I just use `Windows`+`Left arrow` key to move the window to the laptop screen, but this do not work. Nothing happens.

The only think that do work is going to full screen mode. If I press `F11` then Atom shows up as expected on my laptop screen, but as soon as I exit full screen mode, Atom disappears to the (now non existent) external screen.

**Comment by glangford** [comment] 2015-11-03 19:50
@patriksvensson I am not a Windows user so I can't test it, but does the solution offered here help?

<http://www.howtogeek.com/howto/windows/bring-misplaced-off-screen-windows-back-to-your-desktop-keyboard-trick/>

**Comment by patriksvensson** [comment] 2015-11-03 19:54
@glangford No. I've tried that as well.

**Comment by glangford** [comment] 2015-11-03 20:00
Ok, one more try:

<http://superuser.com/questions/53585/how-to-move-windows-that-open-up-offscreen?rq=1>

**Comment by heennkkee** [comment] 2015-11-08 20:52
I had this problem as well, and I solved it with (the unmarked answer of glangfords post) http://superuser.com/a/55798. Just sharing :)

**Comment by lee-dohm** [comment] 2016-05-03 16:11
This is a duplicate of #6939. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-05-03 16:11 UTC
Labels: bug, duplicate, windows
