### ISSUE TITLE
atom wont quit - only possible via activity dialog

### ISSUE THREAD

**Issue by wagrund** [atom/atom#21593] opened 2020-10-26 17:00 UTC
Hi, i am using a MacBook computer.

Looking for a new text editor,
i thought give atom text editor a try, it ist a good looking tool
with many options. but ...

atom wont quit - only possible via activity dialog

since this problem has not been fixed over a long period,
i'd rather use an other editor. sadly

**Comment by jeff-hykin** [comment] 2020-10-29 12:20
Duplicate I believe 
https://github.com/atom/atom/issues/20831

**Comment by sadick254** [comment] 2020-10-30 11:34
Closing this as duplicate of #20831 as pointed out by @jeff-hykin

**Closed by sadick254** 2020-10-30 11:34 UTC
Labels: triaged
