### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by DeanKamali** [atom/atom#15142] opened 2017-08-02 17:49 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:97

TypeError: validateEventDispatches is not a function
    at Object.executeDispatchesInOrder (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginUtils.js:97:11)
    at executeDispatchesAndRelease (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:43:28)
    at executeDispatchesAndReleaseTopLevel (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:54:16)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/forEachAccumulated.js:24:15)
    at Object.processEventQueue (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/EventPluginHub.js:257:13)
    at runEventQueueInBatch (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:17:24)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventEmitterMixin.js:28:11)
    at handleTopLevelImpl (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:72:30)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/Transaction.js:140:26)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:32)
    at Object.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactUpdates.js:97:33)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/react-dom/lib/ReactEventListener.js:147:26)
```

### Commands

```
     -9:00.1.0 core:move-right (input.hidden-input)
  2x -8:58.7.0 core:save (input.hidden-input)
  2x -3:31.7.0 core:undo (input.hidden-input)
     -3:27.6.0 core:backspace (input.hidden-input)
     -3:27 core:move-down (input.hidden-input)
  2x -3:26.3.0 core:backspace (input.hidden-input)
 22x -3:19.7.0 core:undo (input.hidden-input)
     -3:14.7.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -3:10.4.0 git-revert:revert (input.hidden-input)
     -2:59.8.0 core:save (input.hidden-input)
     -2:47.4.0 core:backspace (input.hidden-input)
     -2:46.2.0 core:save (input.hidden-input)
     -2:27.5.0 core:backspace (input.hidden-input)
     -2:27 core:save (input.hidden-input)
     -1:16.1.0 platformio-ide-terminal:paste (textarea.)
     -0:59.5.0 meteor-helper:toggle (div.)
```

### Non-Core Packages

```
atom-electron-snippets 2.0.3 
atom-git-revert 0.2.5 
autocomplete-ansible 0.1.13 
autocomplete-lodash 0.2.3 
autocomplete-paths 1.0.5 
column-select 0.2.0 
copy-filename 1.1.0 
copy-path 0.4.2 
file-icons 2.1.9 
git-plus 7.9.3 
lodash-snippets 2.0.0 
meteor-helper 0.29.0 
meteorjs-snippets-es6 1.3.0 
platformio-ide-terminal 2.5.3 
react 0.16.2 
regex-filter-and-generator 1.4.2 
tree-view-copy-relative-path 1.2.0 
```

**Comment by rsese** [comment] 2017-08-02 18:51
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15093. You may want to subscribe there for updates - if you have steps to reproduce, please let us know in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-02 18:51 UTC
