### ISSUE TITLE
Uncaught Error: spawn /Users/zhufengyuan/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/C...

### ISSUE THREAD

**Issue by zhufyaxel** [atom/atom#9982] opened 2015-12-08 21:34 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/zhufengyuan/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/zhufengyuan/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:132:14)
    at /Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:825:44
    at Emitter.module.exports.Emitter.emit (/Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Project.module.exports.Project.addPath (/Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at /Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:850:41
    at EventEmitter.<anonymous> (/Users/zhufengyuan/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:37 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:10.9.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joshaber** [comment] 2015-12-08 22:37
Do you know if you happened to move the app from the Downloads directory to somewhere else while it was open?

**Comment by 50Wliu** [comment] 2015-12-08 23:25
Closing this as a duplicate of #9559 - please subscribe there for updates and answer @joshaber's question over on that issue.  Thanks!

**Closed by 50Wliu** 2015-12-08 23:25 UTC

**Comment by zhufyaxel** [comment] 2015-12-09 00:08
Yes I did.Thank you for replying
2015年12月8日 下午6:26，"Wliu" <notifications@github.com>写道：
