### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by kinetoskombi** [atom/atom#11885] opened 2016-06-03 00:06 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: linux 4.5.4-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as getPosition] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:626:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:660:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app.asar/src/window-event-handler.js:182:35)
    at /usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
     -5:47.4.0 core:save (atom-text-editor.editor.is-focused)
     -5:42.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:14.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:13 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 20x -5:12.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -5:11 core:delete (atom-text-editor.editor.is-focused)
  7x -5:10.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:58.3.0 core:delete (atom-text-editor.editor.is-focused)
     -4:48.8.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:39.2.0 tabs:close-other-tabs (li.texteditor.tab.sortable.active.right-clicked)
     -3:48.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -3:47.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:45 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:39.5.0 core:save (atom-text-editor.editor.is-focused)
  5x -2:03.7.0 core:delete (atom-text-editor.editor.is-focused)
 11x -1:52.4.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "editor": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-06-03 16:00
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-03 16:00 UTC
