### ISSUE TITLE
Touch Screen Scrolling Doesn't Work

### ISSUE THREAD

**Issue by c0yote** [atom/atom#14710] opened 2017-06-03 00:39 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Touch screen drag scrolling does not work.

### Steps to Reproduce

1. Open a file in the editor large enough to engage scrollbar.
2. Touch the touchscreen within file to verify that cursor moves to expected location.
3. Attempt to drag-scroll. (Place finger on screen and move finger up or down)
4. Note page scroll does not occur.

**Expected behavior:** [What you expect to happen]

Expected the page to scroll.

**Actual behavior:** [What actually happens]

No scrolling occurs.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

atom 1.17.2

### Additional Information

Tested on Lenova Laptop with Touchscreen on Windows 10.

**Comment by mmarchini** [comment] 2017-06-03 04:05
There's a package that allows you to use touchscreen on atom: [atom-touch-events](https://atom.io/packages/atom-touch-events)

It's a little outdated, but still works. Though it would be nice to have this feature built-in (or at least on a more updated package)

**Comment by rsese** [comment] 2017-06-05 17:47
Thanks for referencing that package @mmarchini :v:

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/2209. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-05 17:47 UTC
