### ISSUE TITLE
HTML script tag comment issue

### ISSUE THREAD

**Issue by mixmatch** [atom/atom#7298] opened 2015-06-16 14:32 UTC
Atom attempts to comment HTML script tags with JavaScript comments:

Example Code: 
```html
<script src="script.js"></script>
```

First toggle comment (Edit > Toggle Comments/ ctrl+/)
```html
// <script src="script.js"></script>
```

Second toggle comment (Edit > Toggle Comments/ ctrl+/)
```html
<!-- // <script src="script.js"></script> -->
```

**Comment by mixmatch** [comment] 2015-06-16 14:39
Only happens if there is an indent before the tag as well.

**Comment by mnquintana** [comment] 2015-06-16 14:45
This is a duplicate of https://github.com/atom/language-html/issues/4 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-16 14:45 UTC
