### ISSUE TITLE
Dock items are allowed to be reopened with cmd-shift-t

### ISSUE THREAD

**Issue by steelbrain** [atom/atom#14200] opened 2017-04-13 19:58 UTC
### Description

When you focus a dock item and press cmd-w to close it and then cmd-shift-t to re-open it, it does  not open correctly.

### Steps to Reproduce

1. Click and focus the tree view
2. Close with cmd-w
3. Reopen with cmd-shift-t

### Versions

I have confirmed this behavior on Atom v1.17-beta0 and v1.17-beta1

### Additional Information

Here's a gif showing the bug in action (Apologize for the low quality, internet uploads are rather slow today)

![kapture](https://cloud.githubusercontent.com/assets/4278113/25021927/6414f3f0-20ad-11e7-9dc0-659c953561dc.gif)

**Comment by ungb** [comment] 2017-04-13 20:10
Thanks for reporting the issue @steelbrain! was able to repro in 1.17.0-beta1

**Comment by ungb** [comment] 2017-04-13 20:37
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14198. You may want to subscribe there for updates.

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed** 2017-04-13 20:37 UTC
Labels: bug, regression

**Comment by steelbrain** [comment] 2017-04-13 20:39
Ha, beat me to it by 2 hours

**Comment by nathansobo** [comment] 2017-04-13 20:41
@ungb I think that issue is related, but I'm not sure it's worthy of being called a duplicate. That's a complaint about the active dock item being something that can be closed with `cmd-w`. This is a complaint about a dock item being *restored* with `cmd-shift-w`. Neither is clearly a bug but a tricky corner of the UX we probably need to iterate on.

**Comment by nathansobo** [comment] 2017-04-13 20:43
I guess the overall issue is do we treat items in docks differently from items in the center of the workspace with respect to a range of concerns?
