### ISSUE TITLE
Conflict with Firefox 38

### ISSUE THREAD

**Issue by vagol942** [atom/atom#6836] opened 2015-05-18 06:27 UTC
Atom running on Manjaro Linux 64bits.

When launching a new Firefox window via dragging an open tab outside the window, if you drag over Atom, the program will shut down.

This is error message displayed on the terminal:
<pre>
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 784 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
</pre>

**Comment by lee-dohm** [comment] 2015-05-18 06:40
This is a duplicate of #3593. Please subscribe there for updates.

Thanks for reporting!

**Closed by lee-dohm** 2015-05-18 06:40 UTC
