### ISSUE TITLE
Opening file from explorer opens new Atom window

### ISSUE THREAD

**Issue by debute** [atom/atom#12606] opened 2016-09-05 10:50 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Whenever I open a file from a folder in Windows, it opens new window of Atom instead of new tab within already opened window. This started to happen after latest update. One week before it was working well. I mean, when I open file in project panel on the left side, it works good. But in explorer, or when I want to fast-edit file from FTP with FileZilla, it opens new window.

### Steps to Reproduce

1. Open Atom and do some work.
2. Now open any file from explorer
3. New Atom window will open

**Expected behavior:** It should open a file in new tab

**Actual behavior:** Ton of windows

### Versions

Atom     : 1.10.0
Electron : 0.37.8
Chrome : 49.0.2623.75
Node     : 5.10.0
OS         : Windows 10, 64-bit

**Comment by pcnate** [comment] 2016-09-06 13:37
I've randomly had the same issue on Windows 7 x64 with chrome 52-53. I end up just dragging and dropping files into atom to avoid the issue altogether.

**Comment by debute** [comment] 2016-09-08 10:50
Yes, I'm doing it almost everytime, but from FileZilla, I cannot just drag it, becuse it is on the server. Hope they fix it.

**Comment by Ben3eeE** [comment] 2016-10-09 19:38
This sounds like a duplicate of https://github.com/atom/atom/issues/12642. Please report back if this has not been resolved after upgrading Atom to 1.11.0 (Stable).

**Closed by Ben3eeE** 2016-10-09 19:38 UTC

**Comment by debute** [comment] 2016-10-17 11:05
Yes, upgrading Atom fixed this issue. I just want to note that I have posted this issue 4 days before #12642

**Comment by debute** [comment] 2016-11-21 12:35
After 3 months I found the reason this happens (also, this is how to reproduce the problem).

When I'm using Atom and new version is released, it will automatically download newest update, but it is not applied on your editor, since you need to restart it. But who is restarting editor, while he is programming? I have tried it today and that's it. Second instance of editor was not opening since new version came like few moment ago. I restarted Atom (and installed update) and it solved the problem. So, my solution to this was: Disable "Automatically download updates" :)

When newest version is installed, then opening something (in my example) from FileZilla, it opens "new instance", which is different from what I'm using right now.

**Comment by godfreap** [comment] 2017-02-13 12:13
Just wanted to pop in - debute seems to be correct. I was having this problem, but restarting the editor fixed it. Perhaps an argument for not leaving the editor open in the background for several days at a time...

**Comment by Ben3eeE** [comment] 2017-02-13 14:52
@ungb Can you reproduce the behavior that @debute is describing in https://github.com/atom/atom/issues/12606#issuecomment-261925330?

**Comment by debute** [comment] 2017-02-23 14:59
How to reproduce this:
1. open Atom editor and pin it into the taskbar
2. wait for an update
3. open Atom from taskbar
4. now open any file from explorer (dont drag&drop it into the editor, just double-click)
5. new instance of Atom will open

I think this is the best way how to reproduce it. Pinned app has file location like "C:\...\atom\app-1.12.5" but new version is in the "C:\...\atom\app-1.12.6" and applications are opening from the new path. Maybe fix would be to make a shortcut, which will point to the latest version, or update Atom's content right in the actual version, so it will not have folders with versions name. But this is not the fix for just users.
