### ISSUE TITLE
Keyboard shortcuts not working and error with Error: Cannot find module '../build/Release/keyboard-layout-manager.node'

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#14859] opened 2017-06-21 10:28 UTC
### Description
```
Error: Cannot find module '../build/Release/keyboard-layout-manager.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/static/index.js:40:43)
    at require (internal/module.js:20:19)
    at customRequire (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:456:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:336:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/home/v3ss/github/atom-master-clean/out/atom-1.20.0-dev-df7f72a3b-amd64/resources/app/src/window-event-handler.js:3:65)
```
### Steps to Reproduce

1. From latest master , open a file in atom.
2. Press Ctrl + C 
3. Cannot copy and paste , error happens.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always
### Versions

Atom    : 1.20.0-dev-df7f72a3b
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Run using --safe

**Comment by rsese** [comment] 2017-06-21 18:27
Thanks for the report!  Looks like basically a dupe of https://github.com/atom/atom/issues/14461 I think?  I'll go ahead and close this and we can continue the conversation there @v3ss0n.   In that issue, can you let us know what operating system you're on and if running `script/clean` before building again helps or not?

**Closed by rsese** 2017-06-21 18:27 UTC

**Comment by v3ss0n** [comment] 2017-06-22 10:48
more related here since i am building from master.
I tried 3rd rebuild and now it is working fine.

**Comment by rsese** [comment] 2017-06-22 23:21
Thanks for confirming @v3ss0n - I'll reference your comment in https://github.com/atom/atom/issues/14843 since I pointed a couple of people to that issue.
