### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:/ProgramData\Rizwan\atom\app-1.55.0\C...

### ISSUE THREAD

**Issue by Alia58** [atom/atom#22155] opened 2021-04-08 07:22 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\ProgramData\Rizwan\atom\app-1.55.0\CSS - My Site Images'

```
At fs.js:126

Error: ENOENT: no such file or directory, lstat 'C:\ProgramData\Rizwan\atom\app-1.55.0\CSS - My Site Images'
    at Proxy.realpathSync (fs.js:1470:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (C:/ProgramData/Rizwan/atom/app-1.55.0/resources/app/static/<embedded>:14:996748)
    at TreeView.onDrop (C:/ProgramData/Rizwan/atom/app-1.55.0/resources/app/static/<embedded>:14:1003938)
    at HTMLDivElement.<anonymous> (C:/ProgramData/Rizwan/atom/app-1.55.0/resources/app/static/<embedded>:14:976910)
```

### Commands

```
     -3:29.7.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -3:25 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
html-tag-auto-complete 2.1.0 
intentions 1.1.5 
language-ejs 0.4.0 
linter 3.3.1 
linter-eslint 8.5.5 
linter-ui-default 3.3.1 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by ThatXliner** [comment] 2021-04-08 17:08
Seems like a duplicate of #22030 . I think we should really check this problem out because there's *a lot* of [similar issues](https://github.com/atom/atom/issues?q=is%3Aissue+is%3Aopen+Uncaught+Error%3A+ENOENT%3A+no+such+file+or+directory%2C+lstat+)

**Comment by sadick254** [comment] 2021-04-08 17:44
@ThatXliner I Am on it. I already have a [PR](https://github.com/atom/atom/pull/22152) to address some of the similar issues.

**Closed** 2021-04-08 21:54 UTC
