### ISSUE TITLE
Code folding broken while using React/JSX

### ISSUE THREAD

**Issue by ianrosedev** [atom/atom#13845] opened 2017-02-18 02:34 UTC
I have stared in safe mode and cleared saved state and the issue persists.

When opening folded code, the code intended to be unfolded will start flashing like it is repeatedly re-rendering. This is only happening with React/JSX code. In the video below, the flashing starts in a JSX part of the code, but the behavior is also happening in other parts of React components. 

![folding_issue](https://cloud.githubusercontent.com/assets/8762358/23089554/a211fc1e-f558-11e6-8ed7-9c17c4b4217f.gif)

Using - 
Mac OSX:  El Capitan 10.11.6
Atom: 1.14.3
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0

**Comment by rsese** [comment] 2017-02-20 19:38
Looks like you found https://github.com/atom/atom/issues/13769 @ianrosedev and this one looks like a dupe of that issue?  Going to go ahead and close but if I mis-understood and you think it's a different issue, let me now :v:

**Closed by rsese** 2017-02-20 19:38 UTC
