### ISSUE TITLE
Only way to set font size to 16 on one-dark-ui theme is with cut/paste

### ISSUE THREAD

**Issue by edreamleo** [atom/atom#16794] opened 2018-02-20 11:02 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Font Size setting for one-dark-ui theme is too quick to check input.

This issue may apply to other themes.

### Steps to Reproduce

1. Open Settings for one-dark-ui theme
2. Type 1 in the Font Size box.
    The text size gets very small. The box contains 8, not 1.
3. Type 6 in the box.  The box contains 20, not 16.

**Expected behavior:**

Imo, the Font Size box should delay evaluation/checking of the font size until, say, the user types <return>.  YMMV. Whatever fix you choose, typing 16 in the text box should "just work". Just as it works for for the Editor: Font Size box.

**Actual behavior:**

See description above.

**Reproduces how often:**

Always

### Versions

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python
git 2.8.2.windows.1
visual studio 2015

**Comment by Aerijo** [comment] 2018-02-20 11:25
The problem is though, that increasing a wait time makes it feel less reponsive. In general, I found I could type a number before it updated. However, there was a really annoying case where I'd type a number from 10 to 19, delete the last digit, and type a different one (say a 2). However, in the process, it would update to font size 8 and the number "I typed" would be interpretted as 82. This would cause it to jump to size 20, which was really jarring.

**Comment by edreamleo** [comment] 2018-02-20 11:43
On Tue, Feb 20, 2018 at 5:25 AM, Benjamin Gray <notifications@github.com>
wrote:

> The problem is though, that increasing a wait time makes it feel less
> reponsive. In general, I found I could type a number before it updated.
> However, there was a really annoying case where I'd type a number from 10
> to 19, delete the last digit, and type a different one (say a 2). However,
> in the process, it would update to font size 8 and the number "I typed"
> would be interpretted as 82. This would cause it to jump to size 20, which
> was really jarring.
>
​The Editor Settings Font Size picker seems to work without fuss.

Edward

**Comment by Aerijo** [comment] 2018-02-20 11:45
@edreamleo The editor font size picker doesn't affect the currently visible pane.

**Comment by edreamleo** [comment] 2018-02-20 14:41
On Tue, Feb 20, 2018 at 5:46 AM, Benjamin Gray <notifications@github.com>
wrote:

> @edreamleo <https://github.com/edreamleo> The editor font size picker
> doesn't affect the currently visible pane.
>
​Sure. Two possible ways forward:

1. Present a drop-down list of the dozen or so alternatives.

2. Check the size and redraw only when the user types <return> or hits a
"do it" button, or some such.​

Edward

**Comment by rsese** [comment] 2018-02-20 21:30
Thanks for the report @edreamleo - this looks like a duplicate of https://github.com/atom/one-dark-ui/issues/213 which Simon closed in favor of https://github.com/atom/one-light-ui/issues/47.  I'll reference your issue there and you can subscribe for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-02-20 21:30 UTC

**Comment by edreamleo** [comment] 2018-02-21 07:45
On Tue, Feb 20, 2018 at 3:31 PM, Robert Sese <notifications@github.com>
wrote:

> Thanks for the report @edreamleo <https://github.com/edreamleo> - this
> looks like a duplicate of atom/one-dark-ui#213
> <https://github.com/atom/one-dark-ui/issues/213> which Simon closed in
> favor of atom/one-light-ui#47
> <https://github.com/atom/one-light-ui/issues/47>. I'll reference your
> issue there and you can subscribe for updates if you'd like.
>
​Thanks for this heads up.

Edward
