### ISSUE TITLE
Add support for asynchronous grammars

### ISSUE THREAD

**Issue by Alxandr** [atom/atom#6585] opened 2015-04-30 21:05 UTC
I'm looking for implementing proper highlighting for C# code using a server that inspects the code, and tokenizes it. The server part is already done, however, it seems that Atom doesn't support asynchronous Grammars (or I'm just not finding any documentation on it).

Please add an API like `highlightFile` or `highlightLines` that accept a `Promise` (or has a callback), so that the tokenization can be asynchronous.

**Comment by lee-dohm** [comment] 2015-05-01 02:39
The [first-mate package](https://github.com/atom/first-mate) is the part of Atom that interprets grammars and performs tokenization.

This is a duplicate of atom/first-mate#34. Please subscribe there for updates.

**Closed by lee-dohm** 2015-05-01 02:39 UTC
