### ISSUE TITLE
Cannot load the system dictionary for zh-CN. Checked the following paths for dictionary files

### ISSUE THREAD

**Issue by caizhengkai** [atom/atom#17301] opened 2018-05-11 06:36 UTC
### Description
My compute is mac and I just download the latest version atom.app and open it ,atom remind me this error.

**Actual behavior:** [Cannot load the system dictionary for zh-CN. Checked the following paths for dictionary files:

/
/System/Library/Spelling
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/spellchecker/vendor/hunspell_dictionaries]

### Versions
Versions=1.26.1

macOS Sierra 10.12.6
China

**Comment by caizhengkai** [comment] 2018-05-11 06:52
In addition，Atom how to set the specified error ignored

**Comment by rsese** [comment] 2018-05-11 17:11
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/spell-check/issues/253 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-11 17:11 UTC
