### ISSUE TITLE
File Scroll while typing (Bug or Feature ?)

### ISSUE THREAD

**Issue by Code-Vortex** [atom/atom#5542] opened 2015-02-13 09:54 UTC
after updating atom to the current version 0.179 , when write a large text, it will be hidden behind the status bar, but i found an option called scroll past end in core settings, after activating it it solved the problem, is this a new feature ? or a bug ? 

check screenshot there is a line behind the status bar
![screenshot from 2015-02-13 11 47 23](https://cloud.githubusercontent.com/assets/4104127/6185443/fcbd5a94-b376-11e4-81f6-36da215bc73d.png)

**Comment by abe33** [comment] 2015-02-13 13:34
Can you confirm this issue when running atom with the `--safe` option? 
Themes may play a role in this kind of problem.

**Comment by izuzak** [comment] 2015-02-13 14:40
@Code-Vortex if you can reproduce this in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode), can you share the exact steps which reproduce the issue for you or record a GIF? I'm having trouble reproducing that.

**Comment by Code-Vortex** [comment] 2015-02-13 15:10
There is no big steps to follow just fill a file with alot of strings if you don't have the same issue so you are good to go.

Well i tried the same version same theme and syntax, but the main difference is the OS 

on fedora 21 i have the submitted issue and also when opening theme settings i see the text is not in the middle of the textbox , maybe its the same issue ? screenshot :
![screenshot from 2015-02-13 16 51 45](https://cloud.githubusercontent.com/assets/4104127/6189400/f56470ee-b3a2-11e4-980c-c9e9389ab665.png)

the screenshot above shows the text is not in the middle of the textbox
on fedora 20 i have no issues.

**Comment by nathansobo** [comment] 2015-02-14 08:36
I think this is fixed on master though I didn't do it intentionally. Can anyone try it and confirm?

**Comment by nathansobo** [comment] 2015-02-17 22:21
I can't reproduce this on master. I made some changes to the scrolling logic addressing other issues, so I think it may be fixed. Please reopen this issue if it isn't working as expected after 0.180.0 is released. Thanks.

**Closed by nathansobo** 2015-02-17 22:21 UTC
Labels: atom, bug
