### ISSUE TITLE
UX: an inactive tab is not draggable at first click

### ISSUE THREAD

**Issue by avatsaev** [atom/atom#12164] opened 2016-07-13 14:00 UTC
### Description

An inactive tab must draggable the first time i click on it. Clicking it once to activate it, and then clicking again to engage the drag is way too frustrating.

### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by damieng** [comment] 2016-07-13 15:29
What operating system are you experiencing this on?  Unable to repro on Windows/master

**Comment by avatsaev** [comment] 2016-07-13 15:33
OS X El Cap

**Comment by thomasjo** [comment] 2016-07-13 16:57
I cannot reproduce either. Currently testing on macOS 10.11.5 (El Capitan).

**Comment by thomasjo** [comment] 2016-07-13 16:59
@avatsaev Can you please try reproducing this in safe mode? I'm guessing this is caused by a community package.

**Comment by avatsaev** [comment] 2016-07-13 17:29
Very well migjt be a community package, i'll try in safe mode as sson as a get home, scrren record and post the video here.

**Comment by lee-dohm** [comment] 2016-07-13 17:31
Also cannot reproduce using Atom v1.8.0 on Mac OS X 10.11.5.

**Comment by avatsaev** [comment] 2016-07-14 09:09
Ok guys so i started the editor in safe mode as you asked, and recorded the behaviour, here is the video https://youtu.be/isG1TT-DfrQ

As you can clearly see in the video, the click events are indicated with an ellipse around the mouse, but even in safe mode the drag doesn't work all the time.

**Comment by thomasjo** [comment] 2016-07-14 09:33
OK, so the crucial piece of missing information, gleaned from watching the video, is that you are using split panes.

I can reproduce this with multiple panes.

**Comment by thomasjo** [comment] 2016-07-14 09:34
@atom/feedback This feels like a duplicate, but I cannot for the life of me find the issue. I might be wrong though.

**Comment by avatsaev** [comment] 2016-07-14 09:48
Well i feel like using tab drags is mainly useful in split panes rather than anything else

**Comment by simurai** [comment] 2016-07-14 23:53
I can reproduce it too. Seems like a pane needs to be **focused** before you can drag any tabs from that pane.

**Comment by Ben3eeE** [comment] 2016-09-26 20:26
Duplicate https://github.com/atom/tabs/issues/190?

**Comment by mnquintana** [comment] 2016-09-26 22:53
Thanks @Ben3eeE! This indeed looks like a duplicate of https://github.com/atom/tabs/issues/190 – closing this out in favor of that issue.

**Closed by mnquintana** 2016-09-26 22:53 UTC
Labels: bug
