### ISSUE TITLE
Changing UI/Syntax theme colors 3 times reverts ALL settings to defaults

### ISSUE THREAD

**Issue by mitterdoo** [atom/atom#8834] opened 2015-09-18 02:14 UTC
I just started using this today, running version 1.0.13 on Windows 10 64-bit. I was messing with the theme settings after I had my other settings (which plugins were enabled, editor settings, etc) configured. I changed the theme three times, then the UI became very screwed up. ![Weird UI](http://i.imgur.com/6xPhzMv.png) It stayed screwed up whenever I changed the theme again, so I tried closing and reopening Atom. Then I was greeted with the welcome screen which I got rid of, and all my tabs were gone. I checked my settings, and sure enough, they were back to the defaults.

**Comment by simurai** [comment] 2015-09-18 03:16
Based on the screenshot, it looks like not all styles got reloaded correctly.

Do you still remember which 3 themes you picked before it reverted your settings? And can you reproduce it again?

**Comment by mitterdoo** [comment] 2015-09-18 03:20
Yes, if I change it from the default "One Dark" theme to "Atom Light", "Atom Dark", "One Dark" again, then "Atom Light", this bug happens. Forgot to add reproduction, my bad.

**Comment by simurai** [comment] 2015-09-18 05:59
Ok, I can reproduce it. After picking the 3rd theme (order doesn't seem to matter), I get this error:

```
Uncaught Error: ENOENT, node_modules\notifications\lib\notifications-element.js not found in C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asarnotFoundError @ ATOM_SHELL_ASAR.js:104fs.readFileSync @ ATOM_SHELL_ASAR.js:416compileFileAtPath @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:64Object.defineProperty.value @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:168Module.load @ module.js:353Module._load @ module.js:308Module.require @ module.js:363require @ module.js:382Notifications.initializeIfNotInitialized @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\notifications\lib\main.…:92Notifications.addNotificationView @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\notifications\lib\main.…:122(anonymous function) @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\notifications\lib\main.…:33module.exports.Emitter.emit @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\event-kit\lib\emitter.js:82module.exports.NotificationManager.addNotification @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\notification-manager.js:54module.exports.NotificationManager.addError @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\notification-manager.js:41module.exports.Config.notifyFailure @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:476module.exports.Config.loadUserConfig @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:447later @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\underscore-plus\node_mo…:724
ATOM_SHELL_ASAR.js:488 Uncaught ReferenceError: retrun is not defined
```

then when picking a 4th theme:

```
Uncaught Error: EMFILE: too many open files, open 'C:\Users\Simu\.atom\compile-cache\less\40e22529c8729b65e1d700a7ae3f73d57ed1288f\imports.json'fs.openSync @ fs.js:549module.(anonymous function) @ ATOM_SHELL_ASAR.js:137fs.writeFileSync @ fs.js:1165fsPlus.writeFileSync @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:279module.exports.LessCache.writeJson @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\less-cache\lib\less-cac…:155module.exports.LessCache.setImportPaths @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\less-cache\lib\less-cac…:113module.exports.LessCompileCache.setImportPaths @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\less-compile-cache.js:32module.exports.ThemeManager.refreshLessCache @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\theme-manager.js:421(anonymous function) @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\theme-manager.js:355(anonymous function) @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:570(anonymous function) @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:587module.exports.Emitter.emit @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\event-kit\lib\emitter.js:82module.exports.Config.emitChangeEvent @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:772module.exports.Config.setRawValue @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:564module.exports.Config.set @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\src\config.js:233module.exports.ThemesPanel.updateThemeConfig @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\theme…:487(anonymous function) @ C:\Users\Simu\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\theme…:494
ATOM_SHELL_ASAR.js:488 Uncaught ReferenceError: retrun is not defined
```

**Comment by 50Wliu** [comment] 2015-09-18 18:01
Refs atom/settings-view#653.

**Comment by onetrev** [comment] 2015-09-20 03:19
Same thing here but on a Windows 10 machine.

Very bad bug for sure. Thank goodness I backup my .atom files with CrashPlan as otherwise all settings would be lost! Things looked pretty wacky when all package and core Atom settings got reset to default setting. This happened because my config.cson file was overwritten with a default config.cson file I believe.

**Comment by rugk** [comment] 2015-09-20 11:02
See https://github.com/atom/atom/issues/8860

**Comment by nathansobo** [comment] 2015-09-21 21:25
I'm having trouble reproducing this. Is everyone else besides @simurai on Windows?

**Comment by nathansobo** [comment] 2015-09-21 21:25
@izuzak Are you able to reproduce this either?

**Comment by izuzak** [comment] 2015-09-22 11:51
@nathansobo No, I haven't been able to reproduce this on OSX. Seems like all reports are from Windows machines -- e.g. also see https://github.com/atom/settings-view/issues/662 and https://github.com/atom/atom/issues/8882 and https://github.com/atom/settings-view/issues/653

**Comment by simurai** [comment] 2015-09-22 13:01
OS X works for me too. I only can reproduce it on Windows. In the meantime I updated to `Win 10`, but still same problem. Also looking at the error when switching a 4th time:

`Uncaught Error: EMFILE: too many open files,`

It might not be related to the themes or the settings, but some kind of (memory?) limit is reached? Also, to note.. my Windows laptop is the cheapest I could find. I just got it to test stuff.

**Comment by kevinsawicki** [comment] 2015-09-23 18:52
<img width="825" alt="screen shot 2015-09-23 at 11 48 36 am" src="https://cloud.githubusercontent.com/assets/671378/10055126/639c222e-61e9-11e5-91e4-0c50991733da.png">

@zcbenz from the screenshot above, I'm seeing that asar is unable to read files after that `retrun` error happens. Any idea if they are related or how `asar` could be get into this state? Thanks.

**Comment by kevinsawicki** [comment] 2015-09-23 23:44
This is being tracked over in the Electron repository as https://github.com/atom/electron/issues/2871

**Comment by izuzak** [comment] 2015-09-24 16:39
Should be fixed with https://github.com/atom/atom/pull/8927

**Closed by izuzak** 2015-09-24 16:39 UTC
Labels: atom, bug, uncaught-exception, windows
