### ISSUE TITLE
Uncaught Error: spawn /usr/local/bin/rebar ENOENT

### ISSUE THREAD

**Issue by andrewvtsk** [atom/atom#4886] opened 2015-01-07 11:26 UTC
Uncaught Error: spawn /usr/local/bin/rebar ENOENT

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At events.js:85

Error: spawn /usr/local/bin/rebar ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by izuzak** [comment] 2015-01-07 16:40
Looks like a duplicate of https://github.com/atom/atom/issues/4728.

**Closed by izuzak** 2015-01-07 16:40 UTC
