### ISSUE TITLE
load loooooong line js file will hang the editor

### ISSUE THREAD

**Issue by davyzhang** [atom/atom#7536] opened 2015-06-29 08:59 UTC
some js min file like this one:

https://raw.githubusercontent.com/select2/select2/master/dist/js/select2.full.min.js

**Comment by izuzak** [comment] 2015-06-29 09:00
Duplicate of https://github.com/atom/atom/issues/979. Please check the [guidelines for submitting issues](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) which suggest that you search existing issues before opening a new one.

**Closed by izuzak** 2015-06-29 09:00 UTC
