### ISSUE TITLE
Uncaught Error: kill ENOENT

### ISSUE THREAD

**Issue by moseschrist** [atom/atom#14374] opened 2017-05-08 15:31 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: kill ENOENT

```
At events.js:160

Error: kill ENOENT
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.kill (internal/child_process.js:392:26)
    at Task.module.exports.Task.terminate (/app.asar/src/task.js:152:25)
    at /app.asar/src/task.js:19:21
    at /app.asar/src/task.js:136:25
    at /app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/task.js:78:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
ambiance-pro-ui 0.4.1 
atom-beautify 0.29.24 
git-history 3.3.0 
git-plus 7.8.0 
git-time-machine 1.5.9 
line-ending-converter 1.3.2 
merge-conflicts 1.4.4 
split-diff 1.3.0 
symbols-tree-view 0.14.0 
```

**Comment by rsese** [comment] 2017-05-09 19:45
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by moseschrist** [comment] 2017-05-10 04:45
opening a project folder seems to cause the problems
even on safe mode.

removing the application and reinstalling it didn't seem to help either.

**Comment by rsese** [comment] 2017-05-10 17:42
Thanks for confirming - after saving any unsaved work, can you try [resetting to factory defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) by moving your `~/.atom` directory and try again?

Also, did this problem start happening randomly recently?

**Comment by moseschrist** [comment] 2017-05-11 05:20
the problems started suddenly, i tried upgrading to the latest stable and it didn't help.
but resetting to defaults fixed to problems.

now everything is ok.

**Comment by rsese** [comment] 2017-05-11 23:14
Thanks for confirming, looks like some saved configuration or setting somewhere was likely causing the problem.  Closing for now but if you run into the same error and can reproduce, please let us know.

**Closed by rsese** 2017-05-11 23:14 UTC
Labels: more-information-needed, uncaught-exception
