### ISSUE TITLE
Editor Keeps Crashing

### ISSUE THREAD

**Issue by bharathyes** [atom/atom#5804] opened 2015-03-01 16:57 UTC
From the time I installed Atom on my Win8 PC it keeps crashing as soon as I open it. An error message said to report the issue here. Please provide some solution to this problem.

**Comment by lee-dohm** [comment] 2015-03-01 17:15
Do you have any more information? Anything special you did when installing? Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by cacois** [comment] 2015-03-08 18:19
I'm seeing the same issue after an update.

With atom open, I selected "Install Update and Restart" from the menu bar. Now, anytime I try to open atom normally, or with --safe, it crashes immediately. atom --version says its 0.186.0. I have no linked packages. The build toolchain is installed correctly (apm install --check confirms). Any of the other debugging steps I can't do, since I can't get the editor to launch. 

How can I get more information to you?

**Comment by kevinsawicki** [comment] 2015-07-21 17:43
Closing this out since more details weren't ever provided.

Please comment back if you can provide the details @lee-dohm mentioned.

**Closed by kevinsawicki** 2015-07-21 17:43 UTC
Labels: more-information-needed

**Comment by facundoq** [comment] 2015-11-02 12:28
I'm having a similar problem after Atom updated itself to 1.1.0 from 1.0.19. Using --safe does not solve the problem. Executing the previous atom.exe (v1.0.19) still works. 

$ apm install --check confirms 
Checking for native build tools done

$ apm list --installed
C:\Users\XXXXX\.atom\packages (12)
├── autocomplete-julia@0.1.0
├── file-icons@1.6.11
├── indent-detective@0.1.0
├── language-elm@1.1.1
├── language-julia@0.4.1
├── language-scala@1.1.3
├── latex-completions@0.3.0
├── linter@1.8.1
├── linter-elm-make@0.3.0
├── linter-scalac@1.1.0
├── save-session@0.15.7
└── script@2.29.0

If after the crash I select the "Keep Open" option, open the developer console, reload and select "Keep Open" again, the console shows a message saying "Inspected Target Disconnected" making it impossible to see what's the problem. 

Is there any log file we can attach?

Windows 7@64, installed through AtomSetup.exe

**Comment by collink** [comment] 2015-11-11 16:41
I was having this issue too.  I happened to open it once from the command line and it seems to have fixed the issue for now?

**Comment by thgie** [comment] 2015-11-12 13:46
I just installed Atom on a fresh Windows 10 and had exactly the same problem. Crash as soon as I wanted to open a file. Fixed when renaming the .git folder (which isn't like a real solution ...)

**Comment by 50Wliu** [comment] 2015-11-12 13:52
@thgie There is a known crash on Windows 10 using Atom 1.1.0 which has been fixed in the Atom 1.2.0 betas.

**Comment by thgie** [comment] 2015-11-12 15:21
@50Wliu: Thanks mate. I could rename the .git folder to it's original label and the project didn't crash upon me.

**Comment by BryanARivera** [comment] 2017-01-14 09:04
Old issue but high rank on google, so for others' benefit:

Try deleting  `~/.atom/blob-store` folder (mac only)

**Comment by nickallevato** [comment] 2017-03-03 02:14
@BryanARivera thanks, helped me on Ubuntu!
