### ISSUE TITLE
Uncaught Error: Requested measurement of a line that is not currently rendered

### ISSUE THREAD

**Issue by jbedette** [atom/atom#15390] opened 2017-08-21 00:59 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2227

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2225:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2218:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:393:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:277:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
  5x -2:13.2.0 core:backspace (input.hidden-input)
     -2:11.6.0 core:save (input.hidden-input)
  2x -2:02.8.0 core:undo (input.hidden-input)
  2x -2:00.0 core:redo (input.hidden-input)
     -1:55.9.0 core:undo (input.hidden-input)
     -1:35.2.0 core:backspace (input.hidden-input)
     -1:34.5.0 core:save (input.hidden-input)
  3x -1:12.8.0 core:undo (input.hidden-input)
     -1:06.2.0 core:save (input.hidden-input)
  5x -0:30.9.0 core:backspace (input.hidden-input)
     -0:28.7.0 core:save (input.hidden-input)
  3x -0:07.6.0 core:move-up (input.hidden-input)
     -0:07.1.0 core:move-right (input.hidden-input)
  2x -0:06.6.0 core:move-up (input.hidden-input)
  2x -0:06.1.0 core:move-right (input.hidden-input)
     -0:05.7.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
atom-shortcuts 0.0.2 
busy-signal 1.4.3 
emmet 2.4.3 
intentions 1.1.5 
learn-ide 2.5.2 
learn-ide-material-ui 1.3.15 
learn-ide-notifications 0.66.5 
learn-ide-tree 1.0.23 
linter 2.0.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.7 
markdown-preview-plus 2.4.0 
markdown-writer 2.6.1 
open-in-browser 0.5.2 
run-in-browser 0.1.3 
```

**Comment by Ben3eeE** [comment] 2017-08-21 07:03
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by Ben3eeE** [comment] 2017-08-22 20:30
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15263. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-22 20:30 UTC
Labels: duplicate
