### ISSUE TITLE
Cannot see Project Tree View

### ISSUE THREAD

**Issue by kjbenk** [atom/atom#10641] opened 2016-02-01 20:43 UTC
This error appears to be related to Nuclide so I am not sure where I should be posting it, but the link from with Atom took me here so there is where I will post it.  Basically after installing and uninstalling Nuclide Atom tends to not perform as well.  This is when I began to not see my tree view of the project even after having restarted Atom multiple times.  This a probably an edge case but now it is documented :)

1. Install Nuclide
2. Add a new project folder
3. Restart Atom
4. Try to add a new project folder and fail
5. Uninstall Nuclide and delete Atom from computer
6. Download Atom again
7. Open a new project

**Atom Version**: 1.4.2
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/Kyle/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/Kyle/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/Kyle/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/Kyle/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/Kyle/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/Kyle/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/Kyle/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/Kyle/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/Kyle/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/Kyle/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/Kyle/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at /Users/Kyle/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:869:41
    at EventEmitter.<anonymous> (/Users/Kyle/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:03.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "nuclide",
      "merge-conflicts",
      "minimap",
      "tool-bar",
      "tool-bar-main",
      "travis-ci-status"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-02-01 21:21
This is a duplicate of #9559 - please subscribe there for updates.  Restarting Atom should fix it.

For the Project Tree View bug, you may want to report that over to https://github.com/facebook/nuclide.

**Closed by 50Wliu** 2016-02-01 21:21 UTC

**Comment by kjbenk** [comment] 2016-02-01 21:26
Thanks for the information :+1:
