### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by EdiwngAlarcon** [atom/atom#6164] opened 2015-03-30 15:08 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Unknown Windows Version
**Thrown From**: [emmet-atom](https://github.com/emmetio/emmet-atom) package, v2.3.4

### Stack Trace

Failed to load the emmet-atom package

```
At Cannot find module 'emmet'

Error: Cannot find module 'emmet'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (C:\Users\Portatil 1050\AppData\Local\atom\app-0.188.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/C:/Users/Portatil%201050/.atom/packages/emmet-atom/lib/emmet.coffee:10:11)
    at Object.<anonymous> (/C:/Users/Portatil%201050/.atom/packages/emmet-atom/lib/emmet.coffee:189:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (C:\Users\Portatil 1050\AppData\Local\atom\app-0.188.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet-atom, v2.3.4

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-03-30 15:13
Looks like a duplicate of https://github.com/emmetio/emmet-atom/issues/238.

**Closed by izuzak** 2015-03-30 15:13 UTC
