### ISSUE TITLE
Uncaught Error: Requested measurement of a line component that is not currently rendered

### ISSUE THREAD

**Issue by cangoektas** [atom/atom#17038] opened 2018-03-27 09:56 UTC
Not really sure what caused this to be honest. Sorry that I can't give more details. 😞 

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line component that is not currently rendered

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2280

Error: Requested measurement of a line component that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2269:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2262:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:401:16)
    at scheduler.readDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:279:20)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:245:13)
```

### Commands

```
     -0:26.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
  9x -0:26.2.0 core:move-down (input.hidden-input)
     -0:25.3.0 core:move-up (input.hidden-input)
  3x -0:24.9.0 core:move-down (input.hidden-input)
     -0:24 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:23.7.0 core:backspace (input.hidden-input)
     -0:23 core:save (input.hidden-input)
     -0:21.7.0 core:move-down (input.hidden-input)
     -0:21.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:20.7.0 core:move-left (input.hidden-input)
     -0:19.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:18.8.0 docblockr:parse-enter (input.hidden-input)
     -0:18.8.0 editor:newline (input.hidden-input)
     -0:17.8.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:17.5.0 core:backspace (input.hidden-input)
     -0:16.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.9.4 
atom-material-syntax 1.0.8 
atom-typescript 12.3.8 
autocomplete-modules 1.12.0 
docblockr 0.13.7 
dracula-syntax 2.0.6 
editorconfig 2.2.2 
file-icons 2.1.18 
highlight-selected 0.13.1 
ide-flowtype 0.22.1 
language-dotenv 1.1.1 
language-graphql 0.9.0 
linter-eslint 8.4.1 
multi-cursor 2.1.5 
my-syntax  
npm-install 4.0.4 
pigments 0.40.2 
prettier-atom 0.53.0 
react-snippets 1.1.0 
record 0.0.0 
sort-lines 0.18.0 
```

**Comment by Ben3eeE** [comment] 2018-03-27 10:32
Thanks for the report!

> Not really sure what caused this to be honest. Sorry that I can't give more details. disappointed

No worries! It looks like this is a duplicate of #15263 and the fix is in 1.26, currently in beta. If you still see this error when you're on 1.26 please let us know.

**Closed by Ben3eeE** 2018-03-27 10:32 UTC
Labels: duplicate
