### ISSUE TITLE
The Atom URL handler notification shows up on every start even when selecting "No, Never"

### ISSUE THREAD

**Issue by segevfiner** [atom/atom#16376] opened 2017-12-13 19:37 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Atom URL handler notification shows up on every start even when selecting "No, Never". Essentially the config doesn't stick.

### Steps to Reproduce

1. Open Atom with the URL handler not registered.
2. Select "No, Never" in the notification.
3. Open and Close Atom.

**Expected behavior:** The notification doesn't show again.

**Actual behavior:** It shows.

**Reproduces how often:** 100%

### Versions

```
Windows 10.0.16299.125 x64

Atom    : 1.23.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.0
python 2.7.14
git 2.15.0.windows.1
visual studio 2015
```

### Additional Information

This is the notification I'm talking about.
![image](https://user-images.githubusercontent.com/24731903/33958476-2da40120-e04d-11e7-8be6-9607cf685f3e.png)

**Comment by KairatKempirbaev** [comment] 2017-12-13 21:59
It has the same root. 
https://github.com/atom/atom/issues/16201

It seems to be still open.

**Comment by rsese** [comment] 2017-12-13 22:15
Thanks @KairatKempirbaev, closing as a duplicate of https://github.com/atom/atom/issues/16201.

**Closed by rsese** 2017-12-13 22:15 UTC
