### ISSUE TITLE
GLIBC_2.27 not supported

### ISSUE THREAD

**Issue by jjmartres** [atom/atom#18170] opened 2018-10-02 08:59 UTC
#### Description

Ubuntu upgraded to version 18.04.1 breaks git support inside Atom

#### Steps to Reproduce

1. Install or upgrade to Ubuntu 18.04.1
2. Lauch atom
3. Edit a file
4. Stage file
5. Commit to branch
6. Pull => Error messages

Here is the error message:

```
/snap/atom/199/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libgnutls.so.30)
/snap/atom/199/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /usr/lib/x86_64-linux-gnu/libp11-kit.so.0)
```

### Versions

```
$ lsb_release -a                                   
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
```
$ ldd --version                                               
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Atom version is 1.31.1 installed from snap

**Comment by mfonville** [comment] 2018-10-02 11:51
Duplicate of https://github.com/electron/electron/issues/13972
And fix is in beta: https://github.com/atom/atom/pull/18012

**Comment by mfonville** [comment] 2018-10-02 11:52
Oh, scratch taht. I Misread, I thought it was an error on 18.10 with glibc 2.28

I hope Electron 2.11 will fix it though

**Comment by daviwil** [comment] 2018-10-02 15:42
Once [this build](https://dev.azure.com/github/Atom/_build/results?buildId=12072&view=logs) completes, we should have a Linux build you can try using Electron 2.0.11 to see if it resolves the issue.

**Comment by maxbrunsfeld** [comment] 2018-10-02 16:31
It looks like it's the git binaries inside of [`dugite`](https://github.com/desktop/dugite) that are not compatible with GLIBC 2.27, not necessarily anything electron-related.

**Comment by sguthals** [comment] 2018-10-09 18:34
Did the update to `dugite` last week potentially help this issue?

**Comment by OsoTranquilo** [comment] 2018-10-15 10:52
Any solution?
I have opened an incidence in https://github.com/desktop/dugite/issues/222 but there is no answer.

**Comment by lee-dohm** [comment] 2018-10-15 17:48
@shiftkey Is this on your radar?

**Comment by shiftkey** [comment] 2018-10-15 19:06
I've been building `dugite-native` against Ubuntu Trusty for ages (to maximise compatibility) and I check to see what shared libraries are needed:

```
$ readelf -d [file] | grep 'Shared library'
 0x0000000000000001 (NEEDED)             Shared library: [libcurl.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

And https://github.com/desktop/dugite-native/pull/121 adds more traceability to required `GLIBC_*` symbols:

```
objdump -T $1 | grep -oEi 'GLIBC_[0-9]*.[0-9]*.[0-9]*'| sort | uniq
GLIBC_2.14 
GLIBC_2.2.5
GLIBC_2.3 
GLIBC_2.3.4
GLIBC_2.4 
```

I'm honestly not sure how `GLIBC_2.25` and `GLIBC_2.26` are now a requirement for you - could something with how the snap package is generated have affected this?

**Comment by lee-dohm** [comment] 2018-10-15 22:33
> could something with how the snap package is generated have affected this?

That's a great point. @jjmartres Can you see if this problem reproduces with the [official Atom distribution](https://github.com/atom/atom/releases/tag/v1.31.2)?

**Comment by drarnau** [comment] 2018-10-17 14:33
I experience the exact same problem with the official Atom distribution:
![screenshot from 2018-10-17 16-32-57](https://user-images.githubusercontent.com/36501920/47093871-603efc00-d22a-11e8-8d65-2dc73e659735.png)

**Comment by lee-dohm** [comment] 2018-10-23 20:31
Could the people affected this try the Beta channel? There is a change in there that we believe fixes this.

Let us know 👍

**Comment by sofixa** [comment] 2018-10-23 21:11
@lee-dohm it's working here - Ubuntu 18.04, Atom installed via snapd 1.31.2 has this bug, but atom-beta 1.32.0-beta3 works fine.

**Comment by maxbrunsfeld** [comment] 2018-10-23 21:14
Ok, we'll be releasing Atom 1.32.0 (stable) shortly, which will contain the same fix.

**Closed** 2018-10-23 21:14 UTC
Labels: more-information-needed

**Comment by fassmann** [comment] 2018-11-03 12:47
I still have the same problem with

![selection_100](https://user-images.githubusercontent.com/13715710/47952387-c2d31000-df2b-11e8-9c73-6919c8cbb2f4.png)


while trying to push with gitplus in atom. Upgraded atom from ppa:webupd8team/atom.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

```
$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by razoons** [comment] 2018-11-15 17:05
I also experience the problem.
![image](https://user-images.githubusercontent.com/44969007/48568871-9abab800-e900-11e8-859e-ed015ef445e2.png)
I just updated the latest release from official repository as described here: https://flight-manual.atom.io/getting-started/sections/installing-atom/
![image](https://user-images.githubusercontent.com/44969007/48569017-0f8df200-e901-11e8-8a5c-9eedb54abbe0.png)

**Comment by 50Wliu** [comment] 2018-11-15 18:16
@razoons it looks like you are using a Snap version of Atom, which is not officially supported. Can you confirm you are using the Packagecloud repository?

**Comment by razoons** [comment] 2018-11-15 19:19
Thanks @50Wliu !! You were right. No problem anymore on my side!
Have all a good day/evening!

**Comment by michalnik** [comment] 2018-12-10 13:16
i'm also unable to fetch (the icon down there at bottom panel).

**Comment by michalnik** [comment] 2018-12-10 13:31
> i'm also unable to fetch (the icon down there at bottom panel).

Finally find solution using this https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt
So, with snap does not work for me but with debian package from PackageCloud is fine...
Atom I am currently using is 1.33.0.
