### ISSUE TITLE
Tree view not refreshed properly

### ISSUE THREAD

**Issue by vincentisambart** [atom/atom#7361] opened 2015-06-22 06:51 UTC
I often get the following display bug in the tree view, with some file names unreadable:
![screen shot](https://cloud.githubusercontent.com/assets/34704/8276774/42068ae2-18f5-11e5-8025-397a7f171172.png)
Using Atom 0.210 on OSX 10.10.3.

I can reproduce it pretty reliably the following way:
- `git clone --depth 1 https://github.com/CocoaPods/CocoaPods.git`
- `atom --safe CocoaPods`
- ensure no folder is expanded. If some are, just close all of them, close the window and Atom, and reopen it with `atom --safe CocoaPods`.
- expand `lib` → `cocoapods` → `installer` → `target_installer`

And I get the screenshot I posted above. Note that it seems to depend partly on the width of the tree view and window.

**Comment by izuzak** [comment] 2015-06-22 07:03
Thanks for the report, @vincentisambart -- this looks like a duplicate of https://github.com/atom/atom/issues/4924. Can you :pray: add a comment there?

**Closed by izuzak** 2015-06-22 07:03 UTC
