### ISSUE TITLE
Unsaved modification will be lost when I close multiple windows 

### ISSUE THREAD

**Issue by chestnutprog** [atom/atom#11293] opened 2016-03-28 17:04 UTC
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)? 
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Open multiple windows will lost unsaved modification.
### Steps to Reproduce

1.Open several Atom Windows.
2.Open a Folder.
3.Write Something and don't save in that window.
4.Close the window that you wrote something.
5.Close the rest of Windows.
6.Open Atom and you will found that the everything has gone.
I found that If you open that folder in the new window, the code will be lost.
![](https://c.hime.io/images/WBqk.gif)
Normally,if you open one window,they won't be lost.
![](https://c.hime.io/images/Y3Qg.gif)
and if you open another folder first,then open that folder,everything will come back.
![](https://c.hime.io/images/Lz6p.gif)
**Expected behavior:** [What you expected to happen]
They should come back.
**Actual behavior:** [What actually happened]
They has gone.
### Versions

1.6.0
You can get this information from executing `atom --version` and `apm --version` at the command line.

**Comment by jeancroy** [comment] 2016-04-01 15:58
Can you try on 1.7 beta ? There was a lot of work on that on the 1.7 branch.

**Comment by chestnutprog** [comment] 2016-04-03 03:59
@jeancroy  I have tried 1.7 beta4.This problem persists

**Comment by Ben3eeE** [comment] 2016-04-14 08:04
Have no problems reproducing this with the provided steps, what I did:

1. Atom open with an added project folder.
2. ctrl-shift-o to open another project folder in a new window.
3. Add an untitled tab to new window and write some text.
4. Close that window.

Now two different steps one working one non working.
* ctrl-shift-o and open same project folder, untitled tab is restored. :+1: 
* ctrl-shift-n before ctrl-shift-o and open the same project folder, untitled tab is lost :bug: 

Conclusion: Saved state for a project folder is only restored when opening a new window and the project folder at the same time.

Windows 7
Atom 1.7.0

**Comment by Ben3eeE** [comment] 2016-06-03 20:43
I just realized that this is the sole reason I am consistently losing project state (Well in combination with another thing). Heres why:
1. Do a fast restart of Atom, close Atom and then reopen right away.
2. Atom opens an empty window because of step 1, maybe not always I don't know, I always thought this was when I lost state and tried to reproduce why it would get lost sometimes when closing.
3. I accepted lost state and reopened project with ctrl-shift-o from the empty Atom window and this is when I actually lost my project state.

I recently randomly thought about this particular issue when I encountered the above opens empty error and did the working steps and my project state was never actually lost.

**Comment by SnoringFrog** [comment] 2016-08-11 15:09
I can reproduce this as well on Windows 10 with Atom 1.9.8. Sadly lost a significant pile of notes to it.
 
Where is the information from unsaved windows saved when Atom is closed? At the very least I'd like to try and restore the files somehow (restoring deleted temp files, finding an old cache of the temp file, etc)

**Comment by Ben3eeE** [comment] 2016-08-12 08:22
My workaround for this issue is to use the [project-plus](https://atom.io/packages/project-plus) package by @mehcode. Opening projects with `project-plus` instead of `Open Project Folder` correctly restores project state.

**Comment by ungb** [comment] 2017-03-13 18:12
Thanks for reporting this issue! I was able to repro the issue and saw that there's multiple issues file from similar scenario.  I'm going to mark this as dup for https://github.com/atom/atom/issues/13873 since that captures the underlying issue.   We take data-loss scenarios very seriously and are actively working on fixing this issue ASAP.  Please subscribe to https://github.com/atom/atom/issues/13873 for more updates.

**Closed** 2017-03-13 18:12 UTC
Labels: bug, data-loss, duplicate
