### ISSUE TITLE
No shortcut in desktop or start menu

### ISSUE THREAD

**Issue by sharduino** [atom/atom#18782] opened 2019-02-04 00:07 UTC
### Description

[I install Atom, I close it and there’s no shortcut.]

### Steps to Reproduce

1. [Install Atom]
2. [Close Atom]
3. [Try to open it again]
4. Look for the shortcut
5. Get confused 

**Expected behavior:** A shortcut

**Actual behavior:** Not a shortcut 

**Reproduces how often this happens [all the time ]

### Versions

Windows 7 64 bit, Atom v1.34.0

**Comment by rsese** [comment] 2019-02-04 23:01
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14020 so you can subscribe there for updates if you'd like.  Also see https://github.com/atom/atom/issues/14020#issuecomment-370261784 for a workaround.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-04 23:01 UTC
