### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by lfkid** [atom/atom#14636] opened 2017-05-25 04:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.1 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (~/AppData/Local/atom/app-1.17.1/resources/app/node_modules/tunnel-agent/index.js:166:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
 30x -3:55.4.0 core:backspace (input.hidden-input)
     -3:33.1.0 core:confirm (input.hidden-input)
 16x -2:56.7.0 core:backspace (input.hidden-input)
     -2:54.5.0 core:confirm (input.hidden-input)
 10x -2:33.3.0 core:backspace (input.hidden-input)
     -2:28.6.0 core:confirm (input.hidden-input)
 12x -2:20 core:backspace (input.hidden-input)
     -2:18.1.0 core:confirm (input.hidden-input)
 17x -2:10.3.0 core:backspace (input.hidden-input)
     -1:53.7.0 core:confirm (input.hidden-input)
 15x -1:18.7.0 core:backspace (input.hidden-input)
  2x -1:14.2.0 core:confirm (input.hidden-input)
 24x -0:45.3.0 core:backspace (input.hidden-input)
  4x -0:31.3.0 core:confirm (input.hidden-input)
 23x -0:10.9.0 core:backspace (input.hidden-input)
  2x -0:07.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.29.24 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
autoclose-html 0.23.0 
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
color-picker 2.2.5 
docblockr 0.10.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.6 
git-plus 7.9.2 
git-time-machine 1.5.9 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
minimap-highlight-selected 4.6.1 
python-tools 0.6.9 
```

**Comment by rsese** [comment] 2017-05-25 18:04
I'll go ahead and close as a dupe of https://github.com/atom/atom/issues/14008 for now (maybe a temporary network issue/issue with your proxy?), but if you have a reproducible problem, please let us know.  Thanks for reporting!

**Closed by rsese** 2017-05-25 18:04 UTC
