### ISSUE TITLE
[Feature request] Text selection: Allow a way to flip the "snap-to-text" behavior of the code editor

### ISSUE THREAD

**Issue by elyran** [atom/atom#17344] opened 2018-05-17 10:38 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Feature request] Text selection: Allow a way to flip the "snap-to-text" behavior of the code editor.

I've already discussed this at the forum:
https://discuss.atom.io/t/text-selection-with-mouse-how-to-disable-snap-to-text/55192

### Steps to Reproduce
Trying to select only a part of the line, but since I start text selection with a double-click, it “snaps” to “as many as possible” characters.
This is counter-productive.
How can I tell atom.io to not behave that way?
I mean, double-clicking should apply “snapping” only on text. Leave the second (third, fourth etc’) brackets out.

Notice it happens only on the second an on.
The first one doesn’t do that. I guess it’s some code compares the previous char and decides if it should auto-select the next one.

Code (JS) in the video:
```
const capitalize = (text) => text.capitalize();

const printMyName = (options) => {
// 1. Double-click on capitalize
// 2. Drap the mouse to the right, trying to select everything
// inside of console.log(…)
console.log(capitalize(options[‘user’][‘firstName’]))
// No success, because there’s a “snap-to-text” to the last bracket

// Trying with SHIFT clicking… But it snaps!

#%@(#&(*&#(%*#!!!)))
Thanks :slight_smile:
}

printMyName({
user: {
firstName: ‘Dan’
}
});
```

![peek 2018-05-15 17-27](https://user-images.githubusercontent.com/2474041/40172373-e9657b7a-59d6-11e8-8fc6-14d7045c36f1.gif)

**Expected behavior:** Don't select a group of braces/brackets, i.e "})))".

**Actual behavior:** It selects all of the group.

**Reproduces how often:** 100%.

Copy/Paste from the linked discussion:

> I wish it was that simple. The thing is, sometimes there are a few brackets, i.e something like “)])))”.
> 
> I think I have an idea for Atom though:
> 
> Look, when I double click a words and then mark text/code, there’s some “snap” flag turning on.
> How do I know about this flag?
> Simple: I release the mouse button, leaving the code selected. Then I Shift+click on the rest of the code I wish to include in the selection, but, it behaves as above - selecting blocks of “similar text”, i.e selecting blocks of brackets (like the above mentioned “)])))”) etc’.
> 
> **Solution**:
> **Check if the Ctrl key is pressed, when utilizing that “snap” flag in order to decide on the required behavior (either select per character or per block of “similar text”).**
> **If Ctrl key is pressed, flip the behavior**.
> 
> This proposed solution doesn’t affect any user and solves it to ones like myself which I’m sure exist but are just too busy debugging :slight_smile:

---

> When I think about it, Ctrl might conflict with the excellent multi-cursor feature.
> **Maybe the Alt key**?
> Maybe check if CAP LOCK is on?
> You get the idea.
> 
> Thanks.
> 
> By the way - excellent work on Atom in general! Much appreciated! :slight_smile:
>

**Comment by rsese** [comment] 2018-05-21 20:36
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/10374 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-21 20:36 UTC
