### ISSUE TITLE
Atom can't rename "root folder" or "project folder"

### ISSUE THREAD

**Issue by Akronix** [atom/atom#15315] opened 2017-08-15 14:55 UTC
### Description

If I right-click on the root directory, or, in the Atom jargon, on the project folder, I get an option to rename that folder; but, if I select it, nothing happens.

### Steps to Reproduce

1. Right click root folder
2. Select "Rename"

**Expected behavior:** Two options:
1. The usual rename modal shows up and I can rename the project folder. Atom updates configuration accordingly to reflect this change.
2. This option, "rename", isn't shown double-clicking the project folder.

**Actual behavior:** Nothing happens

**Reproduces how often:** Always

### Versions

Atom: 1.19.1
Ubuntu 16.04

**Comment by Ben3eeE** [comment] 2017-08-15 15:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/179. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-15 15:29 UTC
