### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\Danilo\AppData\Local\atom\app-0.199.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\Danilo\AppData\Local\atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\Danilo\AppData\Local\atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by Dbuggerx** [atom/atom#6811] opened 2015-05-15 18:39 UTC
1. Go to Settings / Keybindings
2. Right click any option in the table

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\X\AppData\Local\atom\app-0.199.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\X\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:35.2.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -0:25.4.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:04.6.0 fuzzy-finder:toggle-buffer-finder (table.native-key-bindings.table.text)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "open-last-project"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "tabLength": 4,
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.9.3
symbols-tree-view, v0.9.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-05-15 18:54
This is a duplicate of https://github.com/atom/atom/issues/6548 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-15 18:54 UTC

**Comment by Dbuggerx** [comment] 2015-05-18 18:21
Thanks @mnquintana
