### ISSUE TITLE
Selection order changes copy paste order. 

### ISSUE THREAD

**Issue by chick-chains** [atom/atom#3692] opened 2014-10-01 16:52 UTC
If I select multiple lines one at a time using the cursor, when I copy paste those lines they show in the order they were clicked.
So when i choose the following lines one at a time from bottom to top:
1
2
3
When I paste the it shows:
3
2
1

**Comment by izuzak** [comment] 2015-08-10 21:21
I just tried reproducing this and wasn't able to:

![order](https://cloud.githubusercontent.com/assets/38924/9184586/75969662-3fb6-11e5-9075-ec5fe66d024a.gif)

Can anyone still reproduce this?

**Comment by mnquintana** [comment] 2015-08-10 23:56
I can't reproduce this with Atom 1.0.6-24e3ab4

**Comment by izuzak** [comment] 2015-08-11 06:19
Thanks for checking, @mnquintana -- closing this out then. If anyone can still reproduce -- let us know.

**Closed by izuzak** 2015-08-11 06:19 UTC
Labels: needs-reproduction
