### ISSUE TITLE
Release notes in editor not updating

### ISSUE THREAD

**Issue by christianstanfield** [atom/atom#10113] opened 2015-12-17 17:24 UTC
My version of Atom is up to date but the release notes page is stuck on an older version and keeps showing the "restart and update" button which closes Atom but doesn't restart the editor and the button doesn't disappear.

<img width="1237" alt="screen shot 2015-12-17 at 11 20 12 am" src="https://cloud.githubusercontent.com/assets/8076138/11876712/b18bd024-a4b0-11e5-8b5b-8c5efb1763ae.png">

**Comment by mnquintana** [comment] 2015-12-17 17:29
Thanks for the report! This is a duplicate of https://github.com/atom/release-notes/39 - please subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) for a guide on submitting bug reports (including searching for duplicates first).

**Closed by mnquintana** 2015-12-17 17:29 UTC

**Comment by christianstanfield** [comment] 2015-12-17 17:36
Ah, thanks, I didn't see that
