### ISSUE TITLE
Atom 1.18+ token matching behaving strangely

### ISSUE THREAD

**Issue by neumannm** [atom/atom#14982] opened 2017-07-10 14:13 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I noticed a strange behaviour when it comes to syntax highlighting. At first I thought it's a bug in my language package as I developed it myself for a custom language. But then I noticed that the issue only appears when using atom v1.18.0 and above.

By using the development mode I can see that the problem is, that the limits of the structures I have defined via grammar rules are not recognized as expected. Visually, they seem to be "shifted" but I think the problem is more complex.

Here's what some part of a script in this language look like in v1.17.2:

![atom1 17 2-no_error](https://user-images.githubusercontent.com/729045/28021719-275564ce-6589-11e7-830b-767c35c06e39.png)

And here's what the same part of the script look like in v1.18.0 (and above, I also tried 1.19.0-beta3):

![atomv1 18 0-error](https://user-images.githubusercontent.com/729045/28021722-2c9685bc-6589-11e7-880b-57e203f9009e.png)

I think this visual comparison already gives an impression of the problem. I could also provide the relevant snippet of the grammar and a structural comparison of what parts are exactly recognized by atom here, if this would also help.

### Steps to Reproduce

1. Install [my language package](https://atom.io/packages/language-oxpath) in atom version less than v1.18
2. Install my language package in atom version v1.18 or above
3. Create a file with extension .oxp or .oxt with content like this:
  ```
   :<test=string(.)>
   :<test2>
  ```
  and see the difference in rendering.

**Expected behavior:** The token matching / syntax highlighting should work as it did in previous versions of atom.

**Actual behavior:** The matching of tokens and structures seems to have changed from v1.18.0 on. 
Might also be the case that my grammar has its own issues and that some reasonable change in the way atom handles those grammar rules resulted in revealing those flaws. If this is the case, I would like to know what changed and how I could fix my grammar.

**Reproduces how often:** 100%

### Versions

Change resulting in this behaviour seems to have been introduced in 1.18.0 - I have tested on v1.18.0-beta1, -beta2 and -beta3 as well as v1.18.0 (stable) and also 1.19.0-beta3. For comparison I checked v1.17.2 as the most recent version before the issue appeared.
I am running Atom on Linux, Ubuntu 16.04 x64.

### Additional Information
none

**Comment by 50Wliu** [comment] 2017-07-10 21:18
I can confirm this.  The language patterns look correct to me.  Something's wrong with the `[^>]+` section of `OXPathExtractionName`.

**Comment by neumannm** [comment] 2017-08-16 07:49
Thanks @50Wliu for confirming.
Any suggestions for a fix? Although this is clearly some change introduced by Atom's grammar handling, maybe I could adjust my grammar to circumvent the problem?

**Comment by 50Wliu** [comment] 2017-08-17 01:17
I believe when I was investigating the issue I did find an alternative regex that worked.  Unfortunately, that alternative has escaped my brain :/.  If you need help figuring it out I could probably give you some pointers on [the Atom Slack](http://atom-slack.herokuapp.com/) where I'm `@wliu`.

**Comment by neumannm** [comment] 2017-08-21 09:46
Thanks for offering your help. I think I was able to fix the issue by changing both grammar rules (the ones you pointed to in your earlier comment) - the one that captures the whole extraction expression is now with `begin` and `end` instead of `match`, while the `OXPathExtractionName` now also includes the `=` sign to not be overly greedy. 

Still no clue what caused the problem in the first place (I would expect that other grammars may have gotten similar problems as obviously something changed in Atom from v1.17 to 1.18), but my adjustments seem to work for me. Thanks again.

**Comment by lee-dohm** [comment] 2017-08-22 20:03
@50Wliu can you give more details on what the issue is here? I'm not sure what the route to "fixed" would be here.

**Comment by 50Wliu** [comment] 2017-08-22 20:28
I'm not sure either what's happening.  It seems like first-mate is shifting token boundaries, though why this appears to be the only package that's affected I have no idea.

**Comment by lee-dohm** [comment] 2017-08-23 17:21
It looks like v1.18 of Atom shipped with v7.0.4 of [first-mate](https://github.com/atom/first-mate) where previous versions of Atom used v7.0.2 or previous. The difference between v7.0.2 and v7.0.4 is an update of oniguruma from v6.1.0 to v6.2.1. Since oniguruma is the regular expression engine underneath the syntax highlighting in Atom, it is doubtful that we are going to be able to restore things to the way they were in versions of Atom prior to v1.18.

Since the grammar in question was adjusted to fix, I'm going to close this as `wontfix`. Thanks for the report @neumannm :bow:

**Comment by neumannm** [comment] 2017-08-28 12:09
No problem, and thanks for the insight!

**Comment by 50Wliu** [comment] 2017-09-20 09:55
I'm reopening this as I'm running into it with language-html as well.

**Closed** 2017-09-22 17:26 UTC
Labels: regression, triaged
