### ISSUE TITLE
Crash when using "Add File" or "Add Folder"

### ISSUE THREAD

**Issue by celsomiranda** [atom/atom#4921] opened 2015-01-08 15:02 UTC
When trying to create a new file or a new folder from the right-click menu, Atom crashes. 

The bug remains even when Atom is launched with `atom --safe`.

![crash](https://cloud.githubusercontent.com/assets/769237/5664252/dd385d78-9746-11e4-8d41-0151f5761e3a.jpg)

OS: Windows 8.1 x64
Atom Version: 0.168.0

**Comment by Ingramz** [comment] 2015-01-08 16:01
Duplicate of #4904

**Comment by lee-dohm** [comment] 2015-01-08 16:05
Thanks @Ingramz! Yes, this appears to be a duplicate and the fix should be out in the next version of Atom.

/cc @kevinsawicki @zcbenz

**Closed by lee-dohm** 2015-01-08 16:05 UTC
