### ISSUE TITLE
Markdown Table rendered wrong

### ISSUE THREAD

**Issue by NicoHood** [atom/atom#13618] opened 2017-01-14 12:24 UTC
| OK | Package | GPG | HASH | HTTPS | Reproducible | Notes |
|-----------------|-------------------------|-----|--------|-------|---------------|-------|
|  |  |  |  |  |  |  |

The bottom right cell is missing in the markdown preview of atom. If it has content it is shown correct again. Using atom 1.13.0 on Archlinux.

**Comment by 50Wliu** [comment] 2017-01-14 19:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/markdown-preview/issues/206. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-01-14 19:16 UTC
