### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by neoloie** [atom/atom#6883] opened 2015-05-21 04:20 UTC
I had an error below when trying to divide a monitor.
Its error occured after some packages updated.

-----------------------
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.200.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\neoloie\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  4x -6:54.7.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
 76x -0:13.6.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "editor": {
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.3.0
autocomplete-plus-jedi, v0.0.9
autocomplete-ruby, v0.1.0
japanese-menu, v0.6.0
jshint, v1.3.7
linter, v0.12.6
npm-autocomplete, v0.1.2
remember-session, v0.5.1
save-session, v0.15.1
script, v2.23.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-05-21 04:25
This is a duplicate of https://github.com/atom/atom/issues/6548 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-21 04:25 UTC
