### ISSUE TITLE
Cannot search plugins 

### ISSUE THREAD

**Issue by gs-akhan** [atom/atom#7461] opened 2015-06-26 15:04 UTC
Hi, 
After installing a plugin, I cannot search another plugin.  I need to restart ATOM to make this work.

![screen shot 2015-06-26 at 8 31 39 pm](https://cloud.githubusercontent.com/assets/5646166/8380330/c6b4c4b6-1c42-11e5-96bb-a2834ed9f024.png)

**Comment by kubetz** [comment] 2015-06-26 16:46
@gs-akhan: You don't have to restart atom to fix it. Switching to Themes by clicking on the button to the right of the input field and then back to Packages should fix the issue.

I had this problem too few days ago (Windows 8.1). Will try to reproduce it on v1.0 and provide some more details.

**Comment by batjko** [comment] 2015-06-26 17:39
Duplicate of this issue: https://github.com/atom/settings-view/issues/553

...which may be a duplicate of another recently opened issue, but I can't find it.

**Comment by mnquintana** [comment] 2015-06-26 19:16
Thanks @batjko!

This does indeed look like a duplicate of https://github.com/atom/settings-view/issues/553 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-26 19:16 UTC
