### ISSUE TITLE
Failed to load the atom-jshinter package

### ISSUE THREAD

**Issue by alexandermikuta** [atom/atom#8949] opened 2015-09-25 18:42 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.18
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the atom-jshinter package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:4:3
    at Object.<anonymous> (<anonymous>:4:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "css-color-highlight",
      "snippets",
      "policeman-rubocop",
      "tualo-git-context",
      "Atom-Hack",
      "geojson-preview",
      "font-viewer",
      "debugger"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Handlebars, v1.2.1
angularjs, v0.3.0
angularjs-snippets, v0.10.18
atom-alignment, v0.12.1
atom-bootstrap4, v1.2.8
atom-color-highlight, v3.0.9
atom-dart, v0.7.2
atom-handlebars, v1.2.0
atom-jasmine, v0.6.0
atom-jshint, v2.0.0
atom-jshinter, v0.1.3
atom-karma, v0.1.0
atom-ternjs, v0.7.2
atom-typescript, v6.0.18
atom-xsltransform, v0.8.0
atom-yeoman, v0.3.14
auto-indent, v0.5.0
autoclose-html, v0.19.0
autocomplete-angular-material, v0.4.0
autocomplete-modules, v1.1.0
autocomplete-paths, v1.0.2
autocomplete-polymer-project, v0.2.0
better-handlebars, v0.1.1
better-language-dart, v1.0.1
bootstrap-3-snippetset, v0.0.6
bootstrap3-snippets, v0.1.2
bottom-dock, v0.3.5
browser-plus, v0.0.34
change-case, v0.6.0
color-gutter, v0.4.1
coverage, v0.6.1
css-color-underline, v1.0.1
css-snippets, v0.9.0
csslint, v1.1.4
dart-tools, v0.9.23
dartlang, v0.4.6
docblockr, v0.7.3
docs-snippets, v0.8.0
documentation-renderer, v0.2.1
editorconfig, v1.2.0
ember-cli-helper, v0.9.0
ember-snippets, v1.4.0
file-icons, v1.6.9
font-awesome-snippetset, v0.0.6
formatter-coffeescript, v0.1.1
foundation5-snippets, v0.2.2
git-diff, v0.56.0
git-go, v1.0.1
git-log, v0.4.1
git-tab-status, v1.9.2
go-find-references, v1.2.3
go-rename, v0.3.0
go-runtime, v0.2.0
grunt-runner, v0.11.0
gulp-manager, v0.2.10
gulp-snippets, v0.6.2
highlight-column, v0.5.0
highlight-line, v0.11.0
html-entities, v0.4.0
html-id-class-snippets, v1.4.1
htmlhint, v1.1.3
icon-fonts, v1.6.2
javascript-snippets, v1.0.0
js-refactor, v0.6.0
jsformat, v0.9.0
jshint, v1.1.0
json-colorer, v0.3.0
jsonlint, v1.1.2
jsonpp, v0.1.1
language-SCSS, v0.4.0
language-ansible, v0.1.3
language-apache, v1.3.0
language-api-blueprint, v1.0.2
language-babel, v0.15.3
language-bison, v1.0.0
language-chef, v0.7.0
language-cjsx, v0.3.0
language-coffee-script-angular, v2.2.0
language-css-plus, v0.3.0
language-cypher, v0.3.0
language-docker, v1.1.3
language-dockerfile, v0.1.0
language-elm, v1.0.2
language-ember-htmlbars, v0.3.0
language-ember-script, v0.2.0
language-emberscript, v0.1.0
language-erlang, v3.0.0
language-gherkin, v1.0.2
language-gherkin-german, v0.5.2
language-gitignore, v0.2.0
language-gradle, v0.0.3
language-haml, v0.22.2
language-handlebars, v0.2.0
language-hn, v0.2.43
language-html5-subtlegradient, v0.1.0
language-javascript-jsx, v0.3.7
language-javascript-subtlegradient, v0.1.0
language-julia, v2.0.0
language-livescript, v0.0.2
language-livescript-edge, v1.0.2
language-mongodb, v0.2.0
language-nagios, v0.2.0
language-nginx, v0.6.0
language-pgsql, v0.2.0
language-pig, v0.1.0
language-plantuml, v0.1.1
language-protobuf, v0.5.0
language-puppet, v0.14.0
language-r, v0.2.0
language-rdf, v0.2.0
language-rust, v0.4.5
language-salt, v0.4.0
language-scala, v1.1.3
language-scala-plus, v1.2.2
language-smarty-php, v0.5.0
language-sql-mysql, v0.3.1
language-stylus, v0.2.0
language-swift, v0.4.0
language-thrift, v1.0.1
language-tss, v0.4.0
language-twig, v1.6.2
language-typed-coffee-script, v1.0.0
language-typoscript2, v0.2.0
language-varnish, v0.5.0
leanpub-snippets, v0.2.0
linter, v1.6.0
linter-bootlint, v0.0.6
linter-clojure, v1.0.0
linter-coffeelint, v1.1.0
linter-coffeescript, v1.0.0
linter-csslint, v1.0.5
linter-dartanalyzer, v0.3.2
linter-eslint, v3.0.2
linter-flake8, v1.6.1
linter-flow, v3.1.2
linter-gjslint, v0.0.5
linter-golinter, v1.0.0
linter-gotype, v0.1.0
linter-govet, v0.1.5
linter-haml, v1.0.0
linter-handlebars, v2.1.0
linter-hlint, v0.4.2
linter-htmlhint, v0.1.1
linter-javac, v1.2.0
linter-js-yaml, v1.1.2
linter-jscs, v3.0.0
linter-jsonlint, v1.0.1
linter-jsxhint, v0.1.2
linter-lsc, v2.3.0
linter-php, v1.0.3
linter-phpcs, v1.1.1
linter-phplint, v0.1.0
linter-phpmd, v1.2.0
linter-plus-eslint, v0.4.0
linter-pylama, v0.2.0
linter-pylint, v1.0.0
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
linter-rubocop, v0.4.1
linter-scalac, v1.1.0
linter-scss-lint, v2.0.0
linter-stylint, v2.0.1
linter-tslint, v0.4.0
linter-xmllint, v0.0.7
live-editor-reload, v0.1.0
markdown-preview-plus, v2.1.1
meteor-api, v2.20.0
minimap, v4.13.4
mocha, v0.0.7
mocha-runner, v1.1.6
node-debugger, v1.1.8
package-cop, v0.2.10
pretty-json, v0.4.1
project-manager, v2.5.2
racer, v0.17.2
raml, v0.2.0
run-in-browser, v0.1.3
scope-inspector, v1.0.1
tabs-to-spaces, v0.11.1
terminal-plus, v0.6.0
test-status, v0.35.0
trailing-spaces, v0.3.2
travis-ci-status, v0.18.0
tree-view-git-status, v0.2.1
typescript-atomizer, v0.3.1
underscorejs-snippets, v0.2.2
unitjs, v1.0.0
vagrant, v0.1.0
windows-context-menu, v0.3.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-09-26 16:45
Duplicate of gerred/atom-jshinter#4, please subscribe there for updates.

**Closed by 50Wliu** 2015-09-26 16:45 UTC
