### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by supaiku-o** [atom/atom#12252] opened 2016-07-28 13:52 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: linux 4.6.4-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
  7x -2:22.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:21.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:21.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:21 core:backspace (atom-text-editor.editor.is-focused)
     -2:20.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:20.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:18.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:18.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:17.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:15.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:14.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:14.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:03.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -2:02.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:04.6.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "spell-check",
      "tokamak",
      "love-atom"
    ]
  },
  "editor": {
    "fontFamily": "Source Code Pro",
    "fontSize": 15,
    "invisibles": {},
    "tabLength": 4,
    "tabType": "hard"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.10
atom-language-rust, v0.8.1
lang-gdscript, v3.2.0
language-rust, v0.4.6
linter, v1.11.14
linter-rust, v0.4.6
minimap, v4.24.7
racer, v0.20.0
release-notes, v0.53.0
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-07-30 16:13
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-30 16:13 UTC
