### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('s...

### ISSUE THREAD

**Issue by toanchitran** [atom/atom#16305] opened 2017-12-01 17:41 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('system.
For') contains HTML space characters, which are not valid in tokens.

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:401

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('system.
For') contains HTML space characters, which are not valid in tokens.
    at SuggestionListElement.addClassToElement (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:401:50)
    at SuggestionListElement.renderItem (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:453:30)
    at SuggestionListElement.renderItems (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:275:18)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:187:15)
    at /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
  6x -2:46.1.0 core:backspace (input.hidden-input)
     -2:25 editor:newline (input.hidden-input)
     -2:21.6.0 core:backspace (input.hidden-input)
     -2:04.8.0 core:move-down (input.hidden-input)
     -2:03.0 autocomplete-plus:confirm (input.hidden-input)
     -2:00.2.0 intentions:highlight (input.hidden-input)
  2x -1:57.5.0 core:move-right (input.hidden-input)
  2x -1:52.3.0 editor:newline (input.hidden-input)
     -0:57 autocomplete-plus:confirm (input.hidden-input)
 14x -0:56.2.0 core:backspace (input.hidden-input)
     -0:50.7.0 core:move-down (input.hidden-input)
     -0:50.4.0 autocomplete-plus:confirm (input.hidden-input)
  2x -0:49.6.0 editor:newline (input.hidden-input)
  7x -0:21.5.0 core:backspace (input.hidden-input)
  6x -0:16.3.0 core:move-down (input.hidden-input)
     -0:12.5.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
atom-beautify 0.30.9 
atom-nodejs-snippets 2.0.0 
atom-typescript 11.0.10 
autocomplete-python 1.10.5 
autocomplete-python-jedi 1.10.3-0 
busy-signal 1.4.3 
Hydrogen 2.1.1 
ide-css 0.2.0 
ide-html 0.4.1 
ide-json 0.1.0 
ide-python 0.3.0 
intentions 1.1.5 
kite 0.57.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-flake8 2.2.1 
linter-pycodestyle 2.1.3 
linter-python-pep8 0.2.0 
linter-ui-default 1.6.10 
pure-syntax 0.3.0 
python-tools 0.6.9 
script 3.17.3 
turbo-javascript 1.4.0 
```

**Comment by rsese** [comment] 2017-12-01 20:41
Thanks for the report! Can you confirm if the error is reproducible in safe mode (`atom --safe`)?

**Comment by tromik** [comment] 2017-12-17 19:33
@rsese Getting the same issue. Confirmed that it is not reproducible in safe mode.

```
Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('string
This') contains HTML space characters, which are not valid in tokens.
    at SuggestionListElement.addClassToElement (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:401:50)
    at SuggestionListElement.renderItem (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:453:30)
    at SuggestionListElement.renderItems (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:275:18)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:238:13)
```

Community Packages
```
├── atom-beautify@0.30.5
├── autocomplete-python@1.10.3
├── file-icons@2.1.12
├── kite@0.58.0
├── minimap@4.29.7
├── python-indent@1.1.2
└── python-isort@0.0.7
```

```
> atom --version

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

I share three packages with @toanchitran, though we are on different versions. Some of my packages are behind latest, too, so I am going to update everything and report back.

**Comment by rsese** [comment] 2017-12-18 18:04
Thanks @tromik :v:

I thought this sounded familiar, looks like a duplicate of https://github.com/atom/atom/issues/16164 and based on your repro, maybe an issue with one of the Python-related community packages.  You can disable them all and re-enable one at a time to find which package is causing the issue.

**Closed by rsese** 2017-12-18 18:04 UTC
Labels: more-information-needed, uncaught-exception
