### ISSUE TITLE
Japanese charactor is not displayed correctly

### ISSUE THREAD

**Issue by TomKatsuki** [atom/atom#14473] opened 2017-05-18 06:25 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
Japanese charactor is not displayed in atom window correctly.

After auto-update 1.17, I cannot edit text file with Japanese charactor(Shift_JIS),
 because of not displayed correctly.
When I change code type using by "encoding-selector",  the problem is not solved.

In atom 1.16 or former version, this issue was not occured.
Now I get back to version 1.16, 

How about other multi-byte charactor environment?

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment] 2017-05-18 15:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/encoding-selector#48. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-18 15:13 UTC

**Comment by TomKatsuki** [comment] 2017-05-18 18:28
to 50Wliu
Thanks!
Now I tried to update ver1.18beta1.
But I think this issue is not fixed yet.
