### ISSUE TITLE
New update: "Restart and install" button doesn't work

### ISSUE THREAD

**Issue by brunnopleffken** [atom/atom#11662] opened 2016-04-30 18:01 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When an update is available, a blue icon appears in the status bar (which opens the 'About' window). After the update is downloaded, the "Restart and install" button doesn't work BUT the Menu > Atom > Restart and Install Update works correctly.

Of course, I'm not testing this in the latest version of Atom because the latest version is the one I downloaded right now.

![untitled](https://cloud.githubusercontent.com/assets/3427344/14937620/9cb4c744-0ee3-11e6-8c5e-6ad0588eab7a.gif)

### Steps to Reproduce

1. There must be an update available;
2. Click the icon in the status bar to open the 'About' window;
3. Download the update;
4. Click on 'Restart and install';

**Expected behavior:** The same as clicking in Menu: Atom > Restart and Install Update: Atom restarts and the new update is fully functional.

**Actual behavior:** Nothing happens...

### Versions

OS X El Capitan 10.11.4 (MacBook Retina 13" Late-2013)

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by lee-dohm** [comment] 2016-05-01 05:36
This is a duplicate of https://github.com/atom/about/issues/21, which has been fixed. We're just waiting for the fix to bubble up to Stable. The "Restart and Install Update" menu item still works.

**Closed by lee-dohm** 2016-05-01 05:36 UTC
