### ISSUE TITLE
OSX "Open With" context menu shows multiple versions of Atom

### ISSUE THREAD

**Issue by dabvid** [atom/atom#13299] opened 2016-11-22 14:11 UTC
### Prerequisites

* [X ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? No
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
In macOS Finder when I right click a file and hover over "Open With" I get multiple versions of Atom listed even though I only have one version installed.

### Steps to Reproduce

1. Right click file in Finder
2. Hover "Open With"

**Expected behavior:** 
To only see one version of Atom

**Actual behavior:**
I see multiple versions

### Versions
Atom    : 1.12.3
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.8.4

OS X El Capitan 10.11.6

**Comment by eboracus** [comment] 2016-11-22 18:23
I have seen this, specifically after updating atom to a new version. For me the current version was listed as the default application and the new version of atom appeared in the list of alternatives below. Restarting finder after the update is complete updated the "Open With" list to show only the latest version as the default application.

**Comment by auyer** [comment] 2016-12-06 17:44
I've been having this issue since the first time I updated Atom. 
But when I chose the latest version, it crashes. 
The windows shown in the screenshot wont close until you reboot.
![screen shot 2016-12-06 at 15 42 24](https://cloud.githubusercontent.com/assets/12375421/20936696/ad74a6dc-bbca-11e6-8ad8-290fa6b0d6ec.png)

**Comment by 50Wliu** [comment] 2016-12-06 18:58
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1720. There are multiple solutions presented in that issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-06 18:58 UTC
Labels: mac
