### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.48.0\ and sc...

### ISSUE THREAD

**Issue by SakaSal** [atom/atom#20978] opened 2020-06-24 17:01 UTC
[Enter steps to reproduce:]

1. I was just moving files around from one folder to another
2. now i get this error every time i try to move files in my navigation window

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Salvador\AppData\Local\atom\app-1.48.0\ and scope.py'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\Salvador\AppData\Local\atom\app-1.48.0\ and scope.py'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:943665)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:950594)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:924225)
```

### Commands

```
     -4:03.4.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -3:54.6.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:31.5.0 intentions:highlight (input.hidden-input)
     -3:31.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
file-icons 2.1.41 
intentions 1.1.5 
kite 0.185.0 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
platformio-ide-terminal 2.10.0 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
python-autopep8 0.1.3 
python-debugger 0.2.0 
script 3.26.0 
```

**Comment by lkashef** [comment] 2020-06-26 18:24
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lkashef** 2020-06-26 18:24 UTC
