### ISSUE TITLE
Ruby syntax of theme not being applied correctly

### ISSUE THREAD

**Issue by dansteele** [atom/atom#18461] opened 2018-11-19 12:50 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Started Atom yesterday, no [known] changes or updates to any packages, however I did update OSX to 10.14.1

I use the [One Dark syntax](https://github.com/atom/one-dark-syntax), and noticed immediately that all of my method calls were blue, instead of white.

There have been no changes to the One Dark Syntax theme.

<img width="434" alt="screenshot 2018-11-19 at 12 49 34" src="https://user-images.githubusercontent.com/9802420/48708140-9987d480-ebf9-11e8-9a1b-c47ae6acac70.png">

I have tried manually changing my `styles.less` with the following, [using the CSS from the official one-dark-syntax repo ](https://github.com/atom/one-dark-syntax/blob/master/styles/syntax/_base.less)

```css
.syntax--punctuation {
  &.syntax--section {
    &.syntax--method,
    &.syntax--class,
    &.syntax--inner-class {
      color:hsl(220, 14%, 71%) !important;
    }
  }
}
```

This had no impact.

I'm thinking this could be an issue with the way the ruby is being parsed.

### Steps to Reproduce

Unable to test on another device (only have one Mac!), but happens every time no matter what I try, including safe mode and switching to another theme and back again

### Versions

```
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

This screenshot shows what it should look like (from a copycat theme for sublime)
![image](https://user-images.githubusercontent.com/9802420/48708168-b3291c00-ebf9-11e8-9a63-1a6f1d826154.png)

**Comment by rsese** [comment] 2018-11-20 00:31
Thanks for the report!  

This sounds like a duplicate of issues like https://github.com/atom/language-ruby/issues/252 (you can confirm this is related to Tree-sitter by checking/unchecking `Settings > Core > Use Tree Sitter Parsers`) - see this comment for more details https://github.com/atom/language-ruby/issues/252#issuecomment-437099373. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-20 00:31 UTC
