### ISSUE TITLE
Failed to load the linter-ruby package

### ISSUE THREAD

**Issue by Munchery-RyanCrowley** [atom/atom#9801] opened 2015-11-24 19:07 UTC
[Enter steps to reproduce below:]

1. right click on an SVG file, open with Atom

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Failed to load the linter-ruby package

```
At ENOENT: no such file or directory, lstat '/Users/ryan/Library/Application Support/com.github.atom.ShipIt/update.pDrT760'

Error: ENOENT: no such file or directory, lstat '/Users/ryan/Library/Application Support/com.github.atom.ShipIt/update.pDrT760'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at tryFile (module.js:105:22)
    at tryExtensions (module.js:115:20)
    at Function.Module._findPath (module.js:156:20)
    at Module._resolveFilename (module.js:334:25)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-24 20:21
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-24 20:21 UTC
