### ISSUE TITLE
ctrl-cmd-down combo for switching lines produces a sound

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1669] opened 2014-03-03 21:39 UTC
Reported by a few users:
- http://discuss.atom.io/t/audible-bell-sounds-when-moving-text-down/2089
- support/fc6c2ac6a04d11e38e5adef6c2d169fb
- support/25cfbdeca0ad11e389626d489492fcbc
- support/b537abfea0b011e3946f5df3635c9d01

> If you highlight text in Atom and then press CTRL+CMD+DOWN ARROW, the text will move, but you'll get an audible warning bell. This doesn't happen when moving text upwards.

Did a bit of digging, and it seems that [Brackets has the same problem](https://github.com/adobe/brackets/issues/2419).

**Comment by kvz** [comment] 2015-03-02 12:03
Same behavior for me on OSX 10.10.2 and Atom 0.184.0. The same key mapping in SublimeText does not produce a beep on moving a line down. Moving upwards causes no problems in both Sublime/Atom.

**Comment by irisli** [comment] 2015-03-12 21:50
As stated by others, it happens to me too on OSX 10.10.2 with Atom 0.187.0 and happens when `Audio Beep` is turned off in atom's settings. Does not happen in Sublime.

**Comment by svincent** [comment] 2015-03-25 17:38
I'm seeing this in Atom 0.187.0, but not in Sublime Text 2. The sound is starting to get to me :sweat:

**Comment by izuzak** [comment] 2015-03-25 17:46
@svincent That's because Sublime is not based on Chrome, and Atom is. I hear the same sound when I hit `cmd-ctrl-down` in Chrome. 

We'd definitely appreciate if someone from the community wants to work on this and open a pull request.

**Comment by svincent** [comment] 2015-03-25 17:50
@izuzak Thanks for the clarification!

**Comment by nathansobo** [comment] 2015-03-26 01:49
To clarify, the sound only happens in Chrome when a textarea or input is focused.

**Comment by thomasjo** [comment] 2015-03-26 04:41
Seems to still be an [issue in Adobe Brackets](https://github.com/adobe/brackets/issues/2419) as well. Not really sure how to go about fixing this, since it's fired at the OS level.

**Comment by nathansobo** [comment] 2015-03-26 05:28
Even the Twitter app makes a sound when you do this in the text area.

**Comment by lombardi-gux** [comment] 2015-03-26 14:08
However, sublime text 3 does not make the sound.

On Mar 26, 2015, at 1:28 AM, Nathan Sobo <notifications@github.com<mailto:notifications@github.com>> wrote:


Even the Twitter app makes a sound when you do this in the text area.

—
Reply to this email directly or view it on GitHub<https://github.com/atom/atom/issues/1669#issuecomment-86348104>.


________________________________

**Comment by thomasjo** [comment] 2015-03-26 14:21
> However, sublime text 3 does not make the sound.

Why do you keep bringing that up? Considering the vast number of OS X applications that are affected by this, I guess that a fix/workaround is non-trivial. Feel free to open a PR with a fix however. I'm sure someone can provide assistance.

**Comment by lombardi-gux** [comment] 2015-03-26 14:26
I was just saying, as part of the recent thread of it being "universal" in OSX that it is, in fact, not so.  That's all. Maybe someone will figure out why it doesn't happen there and can use that fix for Atom.  Maybe not.


On Mar 26, 2015, at 10:22 AM, Thomas Johansen <notifications@github.com<mailto:notifications@github.com>> wrote:


However, sublime text 3 does not make the sound.

Why do you keep bringing that up? Considering the vast number of OS X applications that are affected by this, I guess that a fix/workaround is non-trivial. Feel free to open a PR with a fix however. I'm sure someone can provide assistance.

—
Reply to this email directly or view it on GitHub<https://github.com/atom/atom/issues/1669#issuecomment-86537440>.


________________________________

**Comment by kvz** [comment] 2015-03-26 14:31
It was mentioned just 21 hours ago in this very issue that this is because Atom (and many other apps on OSX) is Chrome based. Sublime is not.

**Comment by nathansobo** [comment] 2015-03-26 14:39
But it does happen on non-Chrome-based applications as well. Reposting this link: http://apple.stackexchange.com/questions/23981/command-control-arrow-beeps-plays-alert-sound-in-lion

**Comment by paul-howard** [comment] 2015-05-14 19:50
This is one of my biggest pet peeves about Atom (actually, I can't even think of too many others, which is why I chose it over the competition) so I finally sat down and figured out a work-around.

**Comment by paul-howard** [comment] 2015-05-14 20:15
This is one of my biggest pet peeves about Atom (actually, I can't even think of too many others, which is why I chose it over the competition) so I finally sat down and figured out a work-around.

After several unsuccessful attempts to solve the problem with the system-wide Keyboard Shortcuts prefs, I decided to give [BetterTouchTool](http://blog.boastr.net) a go. Bingo.

The BTT UI is kinda all over the place, so I'll try to be as specific as possible:

1. Select "Gestures" from the toolbar
2. Select "Keyboard" from the tab bar just below the toolbar
3. Hit the [+] button under the "Select Application" list on the left
4. Select Atom
5. With Atom still selected from the list on the left, hit "+ Add New Shortcut"
6. Click where it says "Click to record new shortcut" and press `cmd-ctrl-down`
7. Click the "Trigger Predefined Action" dropdown (which actually turns out to be a pop-up)
8. In the "Controlling Other Applications" section, select "Trigger Menu Bar Menu-item"
9. This will trigger a sheet (I told you the UI was nuts); in the sheet's text box, enter "Edit;Lines;Move Line Down" and click Save.
10. There is no Step 10.

Tying  `cmd-ctrl-down` in Atom now results in the current line moving down without triggering the system beep. (Yay!) It does trigger a brief flash of the word "Edit" in the menu bar as BTT works its magic in the background, but I can live with that until someone figures out a less kludgy fix.

**Comment by brandonweiss** [comment] 2015-05-21 16:51
This has been driving me nuts.

**Comment by matejkramny** [comment] 2015-07-03 12:48
Hi Guys, Is there any solution to this aside from installing some tools?

**Comment by maxparm** [comment] 2015-07-03 13:37
+1

**Comment by levity** [comment] 2015-07-03 20:52
+1

**Comment by Decoherence** [comment] 2015-07-13 22:38
+1

**Comment by martimatix** [comment] 2015-07-15 02:15
+1

**Comment by mnquintana** [comment] 2015-07-15 02:16
Thanks for the feedback everyone! However, all these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – we may unlock it once someone starts working on this enhancement to get further feedback.

**Comment by benogle** [comment] 2015-07-20 22:37
@zcbenz can you dig into this? Is it possible to suppress?

**Comment by zcbenz** [comment] 2015-07-21 02:31
@benogle I'll have a deep investigation of this.

**Comment by nathansobo** [comment] 2015-08-27 17:41
I've narrowed the cause of this down in https://github.com/atom/electron/issues/2617, but will need @zcbenz to take it from here.

As a temporary workaround, create the following file at `~/Library/KeyBindings/DefaultKeyBinding.dict` (or add these entries to the existing file):

```plist
{
	"^@\UF701" = "noop:";
	"^@\UF702" = "noop:";
	"^@\UF703" = "noop:";
}
```

**Comment by sadick254** [comment] 2020-08-24 15:47
This [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=916460) was opened on the chromium bug tracker but has since been labeled as a `wontfix` by the chromium team. I am going to close this but happy to reopen when someone has a workable solution that would could include in atom.
Thanks everyone for you contribution towards trying to resolve this issue.

**Closed by sadick254** 2020-08-24 15:47 UTC
Labels: bug, electron, help-wanted, mac, wontfix
