### ISSUE TITLE
Uncaught Error: spawn /Users/jueying/Library/Application Support/com.github.atom.ShipIt/update.mc...

### ISSUE THREAD

**Issue by zichen2011** [atom/atom#9626] opened 2015-11-16 14:15 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/jueying/Library/Application Support/com.github.atom.ShipIt/update.mcM5Ezy/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/jueying/Library/Application Support/com.github.atom.ShipIt/update.mcM5Ezy/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/jueying/Library/Application Support/com.github.atom.ShipIt/update.mcM5Ezy/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/jueying/Library/Application Support/com.github.atom.ShipIt/update.mcM5Ezy/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/jueying/Library/Application Support/com.github.atom.ShipIt/update.mcM5Ezy/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/jueying/Library/Application Support/com.github.atom.ShipIt/update.mcM5Ezy/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "ignoredNames": [
      ".DS_Store",
      ".git",
      ".svn"
    ],
    "projectHome": "/Users/jueying/Code",
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "menlo",
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-16 14:30
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-16 14:30 UTC
