### ISSUE TITLE
atom recognize comments incorrectly

### ISSUE THREAD

**Issue by scotthuang1989** [atom/atom#16291] opened 2017-11-29 01:46 UTC
Here is my python code:

```
def test():
    """
    test doc
    """
    x=1
    y=2

def test2():
    """
    test doc
      ```python
        update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS, clone.scope)
      ```
    """
    x=1
```

if you save this code to a .py file. you will find out that  the last line:
`x=1`
will be recognized as comments. When I run it, it works fine. But I thinks this maybe a bug.

**Comment by rsese** [comment] 2017-11-29 20:50
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/language-python/issues/110. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-29 20:50 UTC
