### ISSUE TITLE
Fonts are rendered cropped

### ISSUE THREAD

**Issue by WestFlame** [atom/atom#15171] opened 2017-08-04 21:41 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Some fonts are rendered cropped when line height set to 1.1 or below. It happens with Iosevka font, Source Code Pro and probably others.

### Steps to Reproduce

1. Just set line height setting in editor section to e.g. `1.1` or `1.0`.
2. Display some symbols with tall characters (especially brackets: [ ] ).

**Expected behavior:** 
![28961886-2d607cf8-7904-11e7-9c93-cf2771c5334a](https://user-images.githubusercontent.com/1949300/28987922-c120e2b6-796d-11e7-8737-e7c9d03fb610.png)

**Actual behavior:** 
![28961877-283cb200-7904-11e7-84d8-419bbec939c3](https://user-images.githubusercontent.com/1949300/28987917-bbe2ac3a-796d-11e7-98b3-8cfb02dccae0.png)

**Reproduces how often:** 100%

### Versions

* 1.18.0
* 1.19.0-beta7

---

Added alternate steps to repro /cc https://github.com/atom/atom/issues/15171#issuecomment-322689734

**Comment by rsese** [comment] 2017-08-05 00:11
Thanks for the report - I installed Source Code Pro and tried to reproduce on macOS 10.12.5 and Atom 1.18.0 but couldn't.   Which operating system are you on?

**Comment by WestFlame** [comment] 2017-08-05 06:26
Well... sorry. I've mistaken that font (I've experimented with several of them and mistaken that one). The correct one is Consolas (and for that it happens only at 1.0 height). But it definitely happens on Iosevka wich is the font I'm regularly using.

It happens on Ubuntu 16.04 and Windows 10. And I forgot to mention that my font size is 13.

**Comment by danielbartsch** [comment] 2017-08-11 12:59
I'm on Ubuntu 16.04, using the default font.

Here's are my underscores with the default line height: `1.5`:
![image](https://user-images.githubusercontent.com/19350749/29213863-5f3057de-7ea5-11e7-8889-b96bf4e66b53.png)

And here are my underscored with my currently used line height: `1.05`:
![image](https://user-images.githubusercontent.com/19350749/29213882-77be0062-7ea5-11e7-9977-40cec17bffed.png)

Same result in safe mode.

**Comment by furai** [comment] 2017-08-11 14:09
I've had this issue since 1.18. Today I've actually sat down to see why it's happening. I'm using the latest version of atom-beta as of the time I'm writing this and it's still happening.
```
$ atom-beta --version
Atom    : 1.20.0-beta1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

I've followed all the debuging steps and found out that it's still happening under certain circumstances in fresh atom environment (after moving .atom folder to somewhere else).
It turns out that combination of some fonts and line heights makes certain characters disappear like for example underscores.

My thread on discuss.atom.io: https://discuss.atom.io/t/missing-underscore-character/44189/

I'm using Ubuntu Gnome 17.04. The font size is default one which is 14px and font family is also default one.
If I set anything below 1.21 for line height - the underscores disappear. 

Before the version 1.18 I'm pretty sure that everything worked with the same settings as it should have.

**Comment by rsese** [comment] 2017-08-16 07:30
Thanks @furai - with Ubuntu 16.04 and Atom 1.20.0-beta2 I can reproduce by changing the line height to 1.15, underscores are no longer visible.  At the default line height of 1.5, they're visible. 

1. `atom --safe`
2. In `Settings > Editor`, change Line Height to `1.15`
3. Create a new file.
4. Type some `_` characters

/cc @as-cii @nathansobo - not sure if this is resolved with all the other regressions y'all have fixed lately?  Added to the project board too 📝

**Comment by nathansobo** [comment] 2017-08-17 15:10
@rsese Is this actually a regression. I read someone saying this was also an issue in 1.18?

**Comment by rsese** [comment] 2017-08-17 17:38
> @rsese Is this actually a regression? I read someone saying this was also an issue in 1.18.

Ahhh sorry I thought mentioned in my comment but I didn't @nathansobo - I had also tested on 1.18 but didn't see the issue there with my steps to repro above:

![1 18-underscore](https://user-images.githubusercontent.com/734194/29425447-e84c401c-8348-11e7-906a-d7b9db57a122.gif)

Then I installed 1.19.2 and the underscores were no longer visible:

![1 19 2-underscore](https://user-images.githubusercontent.com/734194/29425459-ed996f4a-8348-11e7-865b-f14062ea22cb.gif)

**Comment by danielbartsch** [comment] 2017-08-18 06:05
![image](https://user-images.githubusercontent.com/19350749/29446313-d2f93f96-83eb-11e7-8b1a-0aa8e946a736.png)
The git diff marker is cut here too (Atom 1.19.0), I think it's the same issue. Lines do not allow overflow anymore. And because underscores are slightly below lines (with certain line heights), they are not shown.

**Closed** 2017-08-21 08:44 UTC
Labels: bug, regression, triaged
