### ISSUE TITLE
GitHub Markdown syntax highlighting bug for bash codeblocks

### ISSUE THREAD

**Issue by emil-nasso** [atom/atom#9332] opened 2015-10-29 13:36 UTC
It seems like the syntax highlighting for bash code blocks "leaks out" when using the `GitHub Markdown` syntax highlighting.

Seems to be triggered by the keyword `if`.

![https://dl.dropboxusercontent.com/s/u3nhh3tiffs6spc/2015-10-29%20at%2014.33.png?dl=0](https://dl.dropboxusercontent.com/s/u3nhh3tiffs6spc/2015-10-29%20at%2014.33.png?dl=0)

**Comment by thedaniel** [comment] 2015-10-29 13:52
Thanks for the report!

**Comment by 50Wliu** [comment] 2015-10-29 16:22
@emil-nasso Can you please try to reproduce this on Atom 1.1.0-beta1?  The shellscript grammar got a lot of changes between 1.0.19 and 1.1.0.  Thanks.

**Comment by emil-nasso** [comment] 2015-10-30 07:38
I got an upgrade today to 1.1.0 (not the beta, seems like it was released after you wrote that).

The issue is still there.

![https://dl.dropboxusercontent.com/s/lv5wbaicypgmtp7/2015-10-30%20at%2008.37.png?dl=0](https://dl.dropboxusercontent.com/s/lv5wbaicypgmtp7/2015-10-30%20at%2008.37.png?dl=0)

**Comment by emil-nasso** [comment] 2015-10-30 07:41
I noticed one thing though... In the first image, you notice that the first backticks are green, but not on the second image.

That's because `if` as part of another word, got highlighted before but it doesnt anymore. In the first report i had another codeblock containing `--full-if-more-than-n-incrementals=6`

![https://dl.dropboxusercontent.com/s/pcptncila83td5u/2015-10-30%20at%2008.40.png?dl=0](https://dl.dropboxusercontent.com/s/pcptncila83td5u/2015-10-30%20at%2008.40.png?dl=0)

**Comment by emil-nasso** [comment] 2015-10-30 08:14
same issue for `for`

![https://dl.dropboxusercontent.com/s/2fh749rvtau1sfe/2015-10-30%20at%2009.14.png?dl=0](https://dl.dropboxusercontent.com/s/2fh749rvtau1sfe/2015-10-30%20at%2009.14.png?dl=0)

**Comment by kevinsawicki** [comment] 2015-11-02 19:56
I believe this is similar to https://github.com/atom/language-gfm/issues/21 where the parser spills over the triple backtick until the closing pattern (like `fi`) is reached.

**Comment by isiahmeadows** [comment] 2016-10-25 03:59
Still unfixed. It's making documenting optional parameters (e.g. `assert.throws(Type?, callback)`) a bit awkward, and it's not specific to `language-gfm`, either.

JavaScript in GFM: 
![screenshot from 2016-10-24 23-47-59](https://cloud.githubusercontent.com/assets/4483844/19672571/c80f061e-9a45-11e6-90ad-cac61b1ac470.png)

HTML in JavaScript: 
![screenshot from 2016-10-24 23-52-48](https://cloud.githubusercontent.com/assets/4483844/19672582/d8ad3626-9a45-11e6-9776-6367a1546282.png)

**Comment by isiahmeadows** [comment] 2016-10-25 04:00
The first of my examples is from a real OSS project I'm working on.

**Comment by ThomDietrich** [comment] 2017-06-30 00:15
![grafik](https://user-images.githubusercontent.com/2870104/27715758-a26066b2-5d39-11e7-97eb-8a0ad6ed836e.png)

This bug is still available. It's making work with Markdown pretty hard...

The example above is from a non special DSL I'm abusing Java for (which is fine). The code fences should be the clear end of it.
Please prioritize this issue. Thanks!

**Comment by isiahmeadows** [comment] 2017-06-30 23:17
BTW, I located the source of the bug in atom/first-mate#83 (missing feature, actually).

**Comment by harobed** [comment] 2018-05-21 14:50
I have always this error in Atom 1.27.0

**Comment by icecore2** [comment] 2018-08-13 07:31
**2 years** passed, any solution for this highlighting bug?

**Comment by judithpatudith** [comment] 2019-07-26 22:45
Anything to be done about this? I'm having the same problem with ```sh code blocks. Version 1.39.1. Thanks!

**Comment by krishnachaitanya9** [comment] 2020-01-06 08:18
I am still facing the issue. I request the developers to please solve it. It would be of great help. Thanks!

**Comment by belachkar** [comment] 2020-02-16 03:13
I use **nginx** instead

**Comment by Arcanemagus** [comment] 2020-02-18 18:45
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-gfm/issues/21. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2020-02-18 18:45 UTC
Labels: atom, bug
