### ISSUE TITLE
Not able to set Atom as the default text editor on Windows because there's no folder containing the latest binaries

### ISSUE THREAD

**Issue by RockyTV** [atom/atom#9314] opened 2015-10-27 22:47 UTC
Setting up Atom as the default text editor on Windows is a pain in the ass.

The Windows installer installs it to `%LOCALAPPDATA%\atom\`, and there's a bin folder there, which contains nothing less than a command script to run Atom, that is updated everytime a new Atom build is downloaded to your computer.

The issue here is that AtomInstaller does not install Atom in a way that you can easily tell what binary file is the most up-to-date one. For every version downloaded, you just have a folder in the install dir that looks like `app-1.0.19`.

A fix for this would be to have the most up-to-date binaries being installed to a folder on `%LOCALAPPDATA%\atom\` called **current**.

And yes I know I can use the script (atom.cmd) as the default text editor, but me and most of the people wouldn't like our default text editor to be a script.

**Comment by 50Wliu** [comment] 2015-10-27 23:23
This looks like a duplicate of both #4893 and #7205 - please subscribe there for updates.

**Closed by 50Wliu** 2015-10-27 23:23 UTC
