### ISSUE TITLE
Mac OS X Yosemite starting atom with correct path (solution?)

### ISSUE THREAD

**Issue by MarkZander** [atom/atom#7045] opened 2015-06-01 03:18 UTC
When I put Atom in my Apple Dock and clicked on the icon Atom started successfully but couldn't find needed programs in my PATH. I've spent sometime finding a possible solution.

1. Instead of having a binary in the Atom.app/Contents/MacOS use your script Atom.app/Contents/Resources/app/atom.sh.

2. The script needs 2 changes:
    - change for the new location of the binary
    - change the first line of the script from:
#!/usr/bin/env bash
to:
#!/usr/bin/env bash -l

This seems to start Atom from a bash shell that runs the ~/.profile script first allowing all of the environment variables to get set and made visible to Atom.

OS X still does not have shared global environment variables. But it does help establish the login environment variables for atom including PATH.

I've made a new application just for your script as my current work around.

Thanks,
Mark Zander
tarzander@hotmail.com

**Comment by mnquintana** [comment] 2015-06-01 11:21
Thanks for the suggestions! This seems like a duplicate of https://github.com/atom/atom/issues/6956 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-01 11:21 UTC

**Comment by MarkZander** [comment] 2015-06-01 20:59
Yes, same problem but different approach to solving it. Sorry I didn’t add my 2 cents in on the previous submission.

Glad this is being taken care of.

Mark

**Comment by finalclass** [comment] 2015-10-02 17:23
I've created a very simple plugin to solve it. You could try it: https://atom.io/packages/mac-fix-path
