### ISSUE TITLE
Atom restores last session automatically when I open a file

### ISSUE THREAD

**Issue by ntd252** [atom/atom#16662] opened 2018-02-01 01:09 UTC
Hello. I know restore last session is a feature of popular text editor but not good in any case or any user.
When I launch Atom with blank window and open a file for FIRST time (it just happens with the first file), it always open the previous tabs of the last time when I close Atom. If I had opened example.txt and closed Atom, then the next time right after Atom runs, I open that file, then Atom show 2 tabs, both are example.txt.
 I have disable the setting "Restore Previous Windows on Start", but it still happen.

**Comment by rsese** [comment] 2018-02-01 18:22
> If I had opened example.txt and closed Atom, then the next time right after Atom runs, I open that file, then Atom show 2 tabs, both are example.txt.

This sounds like a duplicate of https://github.com/atom/atom/issues/16364 which has been fixed in an upcoming release.

For future issues, please fill out the issue template since it's helpful for us when triaging and investigating issues.

**Closed by rsese** 2018-02-01 18:22 UTC
