### ISSUE TITLE
File system browser has disappeared

### ISSUE THREAD

**Issue by Dubstepper** [atom/atom#5837] opened 2015-03-04 12:14 UTC
I've tried re-installing atom and I've tried looking at various settings but I can't seem to get the file system browser, the thing on the left side where you can browse files back.

**Comment by Jiggins** [comment] 2015-03-04 12:29
Assuming you've tried using the `Toggle Tree View` option, under `View` -> `Toggle Tree View`.  The shortcut is usually `Ctrl + \` or `Cmd + \`

**Comment by izuzak** [comment] 2015-03-04 12:43
@Dubstepper Which version of Atom are you using? Which OS? Can you reproduce the problem in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)? Have you perhaps disabled the Tree View package in Settings? Are you perhaps starting Atom outside of a specific project/folder? (If so, then the tree view isn't shown and can't be shown because you're not within a folder. Try opening a specific folder or file from your disk.)

**Comment by Dubstepper** [comment] 2015-03-04 14:35
@Jiggins That doesn't seem to work.
@izuzak I'm using version 0.186.0 of Atom (I checked by pressing "Help" and looked at the version), and my OS is Windows 8.1 64 bit. 
I'm starting Atom in folders. The tree-view package is enabled, and I actually tried re-enabling the tree-view package just now but it didn't do anything.
However, running Atom in safe mode works fine. I don't know what's causing the Tree View to disappear though. I tried removing everything except README.md from the packages folder and the Tree View isn't showing up still.

**Comment by izuzak** [comment] 2015-03-04 14:39
> However, running Atom in safe mode works fine. 

Seems like this is caused by one of the packages you have installed. Which packages do you have installed? You can get that list by running `apm list`.

Since things work fine in safe mode, I'm going to close this out, but we can discuss this further (and reopen if it does turn out to be a problem in Atom).

**Closed by izuzak** 2015-03-04 14:39 UTC
Labels: more-information-needed

**Comment by Dubstepper** [comment] 2015-03-04 14:41
This is the list I get when running apm list:

Built-in Atom packages (84)
├── archive-view@0.50.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.47.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.41.0
├── autocomplete@0.44.0
├── autoflow@0.22.0
├── autosave@0.20.0
├── background-tips@0.23.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.71.0
├── command-palette@0.34.0
├── deprecation-cop@0.37.0
├── dev-live-reload@0.41.0
├── encoding-selector@0.18.0
├── exception-reporting@0.24.0
├── find-and-replace@0.159.0
├── fuzzy-finder@0.69.0
├── git-diff@0.54.0
├── go-to-line@0.30.0
├── grammar-selector@0.45.0
├── image-view@0.49.0
├── incompatible-packages@0.22.0
├── keybinding-resolver@0.29.0
├── language-c@0.41.0
├── language-clojure@0.13.0
├── language-coffee-script@0.39.0
├── language-csharp@0.5.0
├── language-css@0.28.0
├── language-gfm@0.66.0
├── language-git@0.10.0
├── language-go@0.21.0
├── language-html@0.29.0
├── language-hyperlink@0.12.2
├── language-java@0.14.0
├── language-javascript@0.60.0
├── language-json@0.12.0
├── language-less@0.25.0
├── language-make@0.13.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.11.0
├── language-php@0.21.0
├── language-property-list@0.8.0
├── language-python@0.32.0
├── language-ruby@0.49.0
├── language-ruby-on-rails@0.20.0
├── language-sass@0.35.0
├── language-shellscript@0.12.0
├── language-source@0.9.0
├── language-sql@0.14.0
├── language-text@0.6.0
├── language-todo@0.16.0
├── language-toml@0.15.0
├── language-xml@0.28.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.137.0
├── metrics@0.45.0
├── notifications@0.31.0
├── one-dark-syntax@0.3.0
├── one-dark-ui@0.5.0
├── one-light-syntax@0.4.0
├── one-light-ui@0.4.0
├── open-on-github@0.33.0
├── package-generator@0.38.0
├── release-notes@0.51.0
├── settings-view@0.183.0
├── snippets@0.78.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.55.0
├── status-bar@0.60.0
├── styleguide@0.44.0
├── symbols-view@0.86.0
├── tabs@0.67.0
├── timecop@0.31.0
├── tree-view@0.164.0
├── update-package-dependencies@0.8.0
├── welcome@0.25.0
├── whitespace@0.29.0
└── wrap-guide@0.31.0

C:\Users\Dubsteppers\.atom\packages (0)
└── (empty)

**Comment by Dubstepper** [comment] 2015-03-04 14:44
Wait wow it works again. I re-added the themes I had in the folder and ran apm list again:

C:\Users\Dubsteppers\.atom\packages (4)
├── monokai@0.12.0
├── predawn-syntax@0.1.3
├── predawn-ui@0.3.8
└── seti-ui@0.6.3

**Comment by izuzak** [comment] 2015-03-04 14:45
Thanks. Did you have some packages installed and you didn't restart Atom after that? Some packages do a bad job at cleaning up after themselves. Can you try restarting Atom? 

Also, does removing the `~/.atom` folder help? (Or moving it temporarily to another location)

Is there anything in your config files (Atom -> Open your init script, and Atom -> Open your stylesheet)?

**Comment by izuzak** [comment] 2015-03-04 14:46
Oh, that's strange... how did you remove the themes and how did you add them again?

**Comment by Dubstepper** [comment] 2015-03-04 14:47
Well, I just moved them to another folder I created called "random themes", and then added them back. The problem is back after re-adding the themes

**Comment by izuzak** [comment] 2015-03-04 14:49
> Well, I just moved them to another folder I created called "random themes", and then added them back. The problem is back after re-adding the themes

So, after you removed the themes this way -- the tree view was shown? And after adding them back it wasn't? Which of those themes do you have activated in Settings? Can you try switching to the default theme?

Also, can you try the other things I mentioned above?

**Comment by Dubstepper** [comment] 2015-03-04 14:56
> So, after you removed the themes this way -- the tree view was shown? And after adding them back it wasn't?
Correct. I have Atom Dark activated in settings for both syntax and UI.
I moved the Atom folder to my Desktop and restarted but nothing happened.
There isn't anything in the Atom > Init Script or Atom Stylesheets right now, and I restart every time I've tried something new.
Thank you so much for helping btw :)

**Comment by Dubstepper** [comment] 2015-03-04 15:04
I think I figured out why it doesn't work.
I was opening files in a folder by double clicking on them because I have Atom as the default program to open .js files etc, and I'm used to the tree view showing up when I do this but it doesn't anymore I guess. If I open up a blank patch of Atom and press File > Open Folder and open a folder from here it works fine, even with themes installed.

**Comment by zhaotai** [comment] 2015-12-01 04:03
I have the same problem that the view tree disappeared.
And the situation is that I have installed atom before,but I last time I just removed the application. In my home path, I also had a config folder named .atom. My OS is Mac OS X 10.11 by the way.
And what I did is uninstalling the atom from application folder, and removing the whole .atom folder from home path.Then, reinstall atom.It`s ok.When I opened the atom again,the welcome guide let me choose to open a project.
It`s solved!
Maybe it can help you.

**Comment by thezanke** [comment] 2016-09-16 21:12
I have this problem, I also use Seti UI. When I switch from Seti UI to Atom Dark or One Dark and restart atom my file tree is gone, but if I switch back to Seti UI my file tree returns. When I switch UI themes I see the sidebar of Atom Dark but it vanishes once I reopen Atom... And I am certainly opening it in a way that would include files in a side bar.. and cmd+\ does nothing.

**Comment by daftyw** [comment] 2016-10-28 02:58
@thezanke re-enable tree view package can fix the issue for me

**Comment by shoesandsocks** [comment] 2017-02-08 17:47
If it helps a future searcher... I installed then un-installed Nuclide and my tree-view was gone' cmd-\ no help. After uninstalling Nuclide, one must go back and re-enable tree-view from Settings|Install manually.

**Comment by 50Wliu** [comment] 2017-02-08 17:59
@shoesandsocks Yes, that step is covered in the [Nuclide uninstallation docs](https://nuclide.io/docs/editor/uninstall/).

**Comment by Christo44** [comment] 2017-02-10 08:38
Thanks @shoesandsocks

**Comment by JabariHolder** [comment] 2017-04-12 11:59
Nothing suggested above worked for me but after fiddling around for a while, the following worked:

For anyone experiencing this on a fresh install of Atom after installing packages; simply **create a blank file (file.txt) and then open it using Atom** (Ctrl+O | Cmd + O | File > Open) and tree view should appear. If it doesn't feel free to try the shortcut also (Ctrl + | Cmd + \).

**Comment by scotbond** [comment] 2017-04-16 13:05
The Atom core package 'tree-view' is disabled by installing Nuclide. So if you happen to uninstall Nuclide. tree-view should be re-enabled from Packages -> Core Packages.

**Comment by FerPapi** [comment] 2017-06-16 18:42
Hi there, is there any way to retrieve all the folders that were added to the tree-view before? I guess it should have been saved in some file before...

**Comment by 50Wliu** [comment] 2017-06-17 03:58
@FerPapi try the `application:reopen-project` command.

**Comment by thecosss** [comment] 2017-07-06 10:32
@scotbond Thanks alot! Why the hell they don't restore it themselves?

**Comment by prasanthmurugan** [comment] 2017-08-09 06:13
"packages->settings view ->Manage Packages" scroll and find the tree view under core packages and enable the tree view solved my problem

**Comment by rontodman** [comment] 2017-10-17 04:21
Hi, everyone, I am was experiencing this same issue currently, however, if you goto the HTML project, right click and open with Atom the tree-view shows up. It is enabled in the settings, however it wasn't showing the tree-vew.  So this seems to work for me, for now.

**Comment by NareshMarkus** [comment] 2018-01-01 13:33
Take your mouse cursor towards left edge of display in atom and a arrow icon appears toward the middle left display. click that button and the project explorer will open.  It will disappear in the same way.

**Comment by leob** [comment] 2018-01-25 14:18
Simply removing the .atom folder and restarting Atom did the trick ... and yes I'd uninstalled Nuclide before.

**Comment by ingridzippe** [comment] 2018-03-24 16:26
I clicked a little red bug on the bottom of the Atom window, and I clicked a button that said "Rebuild Packages", and the File Tree came back. I think it was a problem with Atom.
