### ISSUE TITLE
Ligatures do not work with some programming languages

### ISSUE THREAD

**Issue by treppY** [atom/atom#10491] opened 2016-01-19 03:04 UTC
I managed to enable ligatures by using this:

atom-text-editor {
  text-rendering: optimizeLegibility;
}

However, ligatures are automatically turned off when I open VHDL files. VHDL support comes from an optional downloaded package. Is there any way to force ligatures back on?

**Comment by mnquintana** [comment] 2016-01-19 03:06
Thanks for the report! I think this is ultimately a duplicate of https://github.com/atom/atom/issues/9082 though – feel free to subscribe there for updates.

**Comment by treppY** [comment] 2016-01-19 03:09
This is not a duplicate of #9082 at all. I can get ligatures to work with most languages (for example if I force the "C" language in a vhdl file) but for some reason it is disabled in VHDL.

**Comment by mnquintana** [comment] 2016-01-19 03:12
Ah, sorry for misunderstanding – what package provides VHDL support? Is that the only language grammar that seems to disable support for ligatures?

**Comment by treppY** [comment] 2016-01-19 03:16
There seems to be more languages affected by this. I'm using VHDL support from the language-vhdl package. Some out of the box packages are also affected by this issue, such as Less.

**Comment by 50Wliu** [comment] 2016-01-19 03:37
@treppY This is an issue where the ligatures aren't getting tokenized as a single scope.  For example, let's say we have `==`.  The "correct" tokenization of this would be something like `keyword.operator.comparison`, but if it's implemented incorrectly, you may end up with two `keyword.operator.assignments` instead, one for each equals sign.  Usually there's no color difference, but this breaks ligatures.  To confirm that this is the case you can run `Editor: Log Cursor Scope` on the ligatures that aren't working to see if the scopes are indeed different.  If they are, then you should create issues on each language repository that has the incorrect scopes.

**Closed by 50Wliu** 2016-01-19 03:37 UTC
Labels: more-information-needed
