### ISSUE TITLE
Font width is not refreshed on startup

### ISSUE THREAD

**Issue by muchweb** [atom/atom#6596] opened 2015-05-01 09:24 UTC
How to reproduce:

1. Have user stylesheet with custom editor font set
2. Start new editor, previously opened buffers are restored
3. Cursor and selection position does not match rendered text

Way to fix:

1. When I re-open same buffer again, it works OK.

---
I am using Atom `v0.196.0` on GNU Operating System

**Comment by thomasjo** [comment] 2015-05-01 09:30
This is most likely a consequence of https://github.com/atom/atom/pull/6539. Not sure if it can be fixed in a reasonable way, while maintaining the new functionality. Either way, you really shouldn't be setting font size, family, line height, etc in your stylesheet since these are ultimately governed by configuration. Hence there's not really any guarantee that your style will win, since the values governed by configuration might be set directly on the DOM elements, and then you've basically got (almost) no way of winning the specificity battle.

**Comment by mnquintana** [comment] 2015-05-01 10:34
> Either way, you really shouldn't be setting font size, family, line height, etc in your stylesheet since these are ultimately governed by configuration.

Yup, in this case (for font size, family, and line height, etc) you should really be configuring that directly in Settings / config.cson instead of hacking it in styles.less - there's really no reason to, and doing so makes it prone to breakage like this. I think it would be a different story if there were no settings for font, but since there are I'm going to close this.

**Comment by muchweb** [comment] 2015-05-01 11:01
I am using [`fonts`](https://atom.io/packages/fonts) package, because webkit cannot read my all system fonts.

This bug did not happen until the upgrade to the new version.

**Comment by lee-dohm** [comment] 2015-05-01 15:16
@mnquintana I think until atom/settings-view#286 is fixed, it isn't reasonable to just say "you have to set the font in the Settings". Using the `styles.less` is the only way some people have to use the font they need to get their work done. Also, if #6539 breaks the [fonts package](https://atom.io/packages/fonts), I strongly believe we need to step back and reconsider.

**Comment by thomasjo** [comment] 2015-05-01 15:23
> Also, if #6539 breaks the fonts package, I strongly believe we need to step back and reconsider.

I don't understand how it could break the fonts package, since that package does not deal with setting font size. It only triggers measurement by increasing and then decreasing font size, but the font size should still be set in config.

Regardless of setting font family in user styles or not, there's no valid reason for specifying the font size there (at least that I can think of). The issue at hand is **only** related to font size, not family.

**Comment by lee-dohm** [comment] 2015-05-01 15:32
The repro steps above mention only changing the font, not the font size (other than different fonts have different apparent sizes). So I disagree that this is only related to font size.

I will investigate more and nail things down. But the functionality that was introduced in #6539 is a nice-to-have, I don't feel that it was important enough to break rendering ... even in what may well be an edge case.

**Comment by thomasjo** [comment] 2015-05-01 15:40
> The repro steps above mention only changing the font, not the font size

The repro steps don't mention it, that's true, but the title of the issue is "Font width is not refreshed on startup", hence my conclusion that this is related to font size.

I agree that #6539 breaking this edge case is unfortunate, I (personally) don't think it's enough of an issue to worry about since I believe this specific issue can be readily solved by only specifying font width in config. Will try to repro tonight (and check if there are any adverse effects on the fonts package).

**Comment by muchweb** [comment] 2015-05-01 16:45
I have both `font-family` and `font-size` changed. Different fonts have different letter widths, and not all of them are monospace.

1. Just opened the editor:
![2015-05-01-17-43-35](https://cloud.githubusercontent.com/assets/7157049/7433483/a39e2ce6-f029-11e4-947a-1a745ab9712f.png)

2. Closed buffer and re-opened it:
![2015-05-01-17-43-41](https://cloud.githubusercontent.com/assets/7157049/7433488/abe99dea-f029-11e4-9a9c-5cbd3aaaea27.png)

**Comment by mnquintana** [comment] 2015-05-01 17:08
@muchweb Sorry about the confusion on all this - I'll take a closer look at this later today.

**Comment by benogle** [comment] 2015-05-01 17:49
The issue here is with `@font-face` defined fonts. The characters are measured before the browser has a chance to load the fonts. This (from what I've seen) has been an issue for a while. A fix for now would be to install those fonts to your `~/Library/Fonts`, then use the font file name, minus the extension, in the `font-family` property.

**Comment by mnquintana** [comment] 2015-05-01 20:28
@muchweb After talking to @benogle, I think it's extremely unlikely that it was caused by #6539 (I think we sort of jumped the gun there assuming that it was, so I'm sorry about that). #6539 doesn't change anything about how the editor's font is set - it only subscribes to changes in the `editor.fontSize` setting. I think @benogle's explanation is probably what's going on here.

@muchweb Is this the first time you've run into this? This has apparently been an issue for awhile now.

**Comment by mnquintana** [comment] 2015-05-04 13:36
This is a duplicate of #4200 - please subscribe there for updates.

**Closed by mnquintana** 2015-05-04 13:36 UTC
Labels: more-information-needed
