### ISSUE TITLE
Zooming text forces text out of viewable area

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#11062] opened 2016-03-04 20:37 UTC
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Zooming the font size does not keep any portion of the original text on the screen.

### Steps to Reproduce

1. Launch Atom
2. Open a file with at least a couple hundred lines of text
3. Press <kbd>Cmd+=</kbd> repeatedly

**Expected behavior:** Either the top-, bottom- or middle-most line of text to stay within the viewable area

**Actual behavior:** Zoom far enough and none of the top-, bottom- or middle-most lines stay within the viewable area

### Versions

* Atom: 1.7.0-dev-c782bdd
* Electron: 0.36.8
* Chrome: 47.0.2526.110
* Node: 5.1.1
* apm  1.7.1
* npm  2.13.3
* node 0.10.40
* python 2.7.10
* git 2.7.2

**Comment by mnquintana** [comment] 2016-03-04 21:13
This looks like a duplicate of https://github.com/atom/atom/issues/4084 – closing this out in favor of that issue. :smile:

**Closed by mnquintana** 2016-03-04 21:13 UTC
Labels: bug

**Comment by LalaDK** [comment] 2016-03-07 08:39
Thanks so far. 
The duplicate you are refering to is opened in 2014 and as fare as I can read fixed on 6 May 2015.

I've been running both Atom 1.4.3 and Atom 1.6.0-beta7 and I still have this issue. 
I'm using Ubuntu 15.10.

**Comment by mnquintana** [comment] 2016-03-07 17:33
@LalaDK The PR that would've fixed this issue is still a work in progress and hasn't been merged yet, so it's still a known and open issue.
