### ISSUE TITLE
Mouse-wheel text size zoom should be better at retaining the current viewport

### ISSUE THREAD

**Issue by ygra** [atom/atom#11830] opened 2016-05-24 09:01 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? I hope so, if this is, in fact, `atom-core`.
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Turning the mouse wheel while <kbd>Ctrl</kbd> is pressed changes the font size in the editor. This causes the current viewport into longer files to shift drastically. The file I'm testing with has 918 lines, the current viewport is somewhat centered around line 481. Zooming in once shifts the viewport so that it's now centered around line 460, shifted by about half a screen upwards.

### Steps to Reproduce

1. Open a semi-long file
2. Use <kbd>Ctrl</kbd>+mouse wheel to change the font size

**Expected behavior:**

The editor stays roughly at the same file position. Ideally I think the approach from browsers could be adopted which either keeps the first visible line the same (Chrome and Firefox do this, although this shifts most of the viewport in a surprising way just to ease implementation), or is centered around either the mouse pointer (IE and Edge do this) or the caret (if visible on the screen).

**Actual behavior:**

Changing the font size seems to keep the absolute offset from the start of the file _in pixels_ constant, which results in the visible lines shifting by quite a large amount when further down in the file because suddenly *all* lines are larger or smaller.

### Versions

```
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python
git 1.9.5.github.0
visual studio 2013
```

Running on Windows 10.0.10586 x64.

**Comment by 50Wliu** [comment] 2016-05-24 12:15
This is a duplicate of #4084 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-24 12:15 UTC
