### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by haloboy777** [atom/atom#12154] opened 2016-07-12 16:15 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as getPosition] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:626:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:660:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app.asar/src/window-event-handler.js:182:35)
    at /usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
     -7:20.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -7:16.6.0 compare-files:compare (atom-text-editor.editor)
  2x -7:12.7.0 editor:copy-path (atom-text-editor.editor.is-focused)
     -6:08.8.0 compare-files:compare (atom-text-editor.editor.is-focused)
     -5:32.8.0 editor:copy-path (atom-text-editor.editor.is-focused)
  2x -5:27.3.0 compare-files:compare (atom-text-editor.editor.is-focused)
     -5:06.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -4:59.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:59.5.0 compare-files:compare (atom-text-editor.editor)
     -4:46.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -4:39.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:42 core:copy (div.package-detail.panels-item)
     -1:38.8.0 pane:close (li.texteditor.tab.sortable.active.right-clicked)
     -1:35.3.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:19.9.0 compare-files:compare (span.name.icon.icon-file-text)
     -0:01.7.0 application:add-project-folder (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-playground"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "editor": {
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.9
atom-html-preview, v0.1.21
autoclose-html, v0.23.0
autocomplete-clang, v0.9.4
autocomplete-go, v1.1.0
autocomplete-html-entities, v0.1.0
builder-go, v1.0.0
color-picker, v2.2.2
compare-files, v0.6.2
emmet, v2.4.3
go-config, v1.2.1
go-debug, v0.1.16
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
gpp-compiler, v2.3.3
language-cpp14, v0.6.1
linter, v1.11.14
linter-csslint, v1.3.2
linter-htmlhint, v1.2.1
linter-jshint, v2.1.0
linter-python, v2.1.7
minimap-cursorline, v0.2.0
navigator-godef, v1.0.3
rest-client, v1.2.0
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2016-07-12 19:44
Any indication of what you were doing at the time?

**Comment by haloboy777** [comment] 2016-07-12 19:48
I was editing a html document. It really didn't made difference to what was
going on but since it asked should I report this error. So I did.
Please let me know if I can help in anything.
Thanks

**Comment by Ben3eeE** [comment] 2016-07-12 20:24
https://github.com/atom/atom/issues/11692?

**Comment by lee-dohm** [comment] 2016-07-12 20:51
👍 Thanks @Ben3eeE. This is a duplicate of #11692. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-12 20:51 UTC
Labels: more-information-needed, uncaught-exception
