### ISSUE TITLE
auto new line

### ISSUE THREAD

**Issue by krishnaTORQUE** [atom/atom#12602] opened 2016-09-04 08:42 UTC
when saving files, its automatic adding new line.

**Comment by DeanmvSG** [comment] 2016-09-04 11:33
Settings -> Packages -> Whitespace -> turn off "Ensure Trailing Newline"

**Comment by krishnaTORQUE** [comment] 2016-09-04 14:08
thank you so much :+1:

**Comment by thomasjo** [comment] 2016-09-04 14:12
Closing this since this has been resolved (and is also a duplicate of numerous closed issues).

For future reference, consider searching the FAQ category on Discuss. It specifically answers this issue:
https://discuss.atom.io/t/why-is-atom-deleting-trailing-whitespace-why-is-there-a-newline-at-the-end-of-the-file-why-are-there-all-these-changes-in-the-file-diff/19189

**Closed by thomasjo** 2016-09-04 14:12 UTC
