### ISSUE TITLE
"reveal in tree view" does not always put tree view selection on revealed file

### ISSUE THREAD

**Issue by ntuckerxx** [atom/atom#6676] opened 2015-05-07 01:03 UTC
Atom 0.196.0
Mac OS X 10.10.3

"Reveal in tree view" does not always put tree view selection on revealed file.  It seems to depend on the previous selection/collapse state of the tree view.  Here's an example of a repro:

![treeview](https://cloud.githubusercontent.com/assets/80917/7506811/06d06e0c-f41a-11e4-861f-22bfcaa77251.gif)

Note that if you just collapse the tree and then reveal the file, it works fine, but if you change the selection to the other directory, then collapse the tree, then choosing "reveal in treeview" expands the tree to reveal the correct file, but the selection stays on the root directory.

**Comment by 50Wliu** [comment] 2015-05-07 01:23
Duplicate of atom/tree-view#188, please subscribe there for updates and also paste the output of `apm list --installed`.  Thanks!

**Closed by 50Wliu** 2015-05-07 01:23 UTC
