### ISSUE TITLE
unsaved buffer are not kept if there is no project folder

### ISSUE THREAD

**Issue by bitbonk** [atom/atom#15153] opened 2017-08-03 14:16 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I have unsaved buffers but no project folder, those unsaved buffers cannot be kept.

### Steps to Reproduce

1. open atom
2. remove all project folders
3. create a new buffer
4. enter some text
5. close atom

**Expected behavior:** 
I do not get a message box and atom just closes.
When I reopen atom, the unsaved content is still there.

**Actual behavior:**
A messagebox pops up:
> 'untitled' has changes, do you want to save them?
>
> Your changes will be lost if you close this item without saving.
> [Save] [Don't Save] [Cancel]

When I click "Don't Save" and then reopen atom, the content buffer is gone. 

**Reproduces how often:** 
100%
### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by rsese** [comment] 2017-08-03 19:14
Thanks for the report - I'm unable to reproduce though, I'm prompted to save or not after following your steps (I think that's the behavior https://github.com/atom/atom/pull/12922 introduced?).

I tested on macOS 10.12.6, which operating system are you on?

**Comment by bitbonk** [comment] 2017-08-03 20:24
I'm on Windows 10

**Comment by bitbonk** [comment] 2017-08-08 07:54
It looks like that  #12922 is not fixed. At least not on Windows 10, it seems.

**Comment by Ben3eeE** [comment] 2017-08-08 11:00
Duplicate of https://github.com/atom/atom/issues/13318?

**Comment by lee-dohm** [comment] 2017-08-12 19:56
Thank you for contributing!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13318. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2017-08-12 19:56 UTC
Labels: more-information-needed
