### ISSUE TITLE
Issue in markdown syntax

### ISSUE THREAD

**Issue by rugk** [atom/atom#8460] opened 2015-08-20 18:37 UTC
At first: If this should be (again) in the wrong repo I have to apologize, but I just found no atom/language-markdown repo.

So the issue is simple: The markdown syntax highlighting seem to display this something bit broken - and that's Atoms own license file (line 414):
![atomlicense](https://cloud.githubusercontent.com/assets/11966684/9392165/5d068dc4-477b-11e5-97a5-9df6ba46053e.PNG)

UI Theme: Atom Dark
Syntax Theme: One Dark
But that does not seem to matter I've switched both and it was still the same.

**Comment by izuzak** [comment] 2015-08-20 18:40
I believe this is a duplicate of https://github.com/atom/language-gfm/issues/84. Let me know if I've misunderstood.

**Closed by izuzak** 2015-08-20 18:40 UTC

**Comment by izuzak** [comment] 2015-08-20 18:47
Just noticed that issues was closed in favor of https://github.com/atom/language-gfm/issues/44 -- sorry!

**Comment by rugk** [comment] 2015-08-20 18:57
Well... in the Readme I don't see a * which caused this. It's rather _.

**Comment by rugk** [comment] 2015-08-20 19:00
So I've created a new issue there: https://github.com/atom/language-gfm/issues/122
