### ISSUE TITLE
Failed to load the wordpress-api package settings

### ISSUE THREAD

**Issue by ewistrand** [atom/atom#5952] opened 2015-03-12 12:53 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the wordpress-api package settings

```
At unexpected action in C:\Users\Code Local\.atom\packages\wordpress-api\scoped-properties\wordpress.hooks.cson

[stdin]:40:33: error: unexpected action
      'admin_action_{$_REQUEST['action']}'
                                ^^^^^^
  at C:\Users\Code Local\.atom\packages\wordpress-api\scoped-properties\wordpress.hooks.cson:1:1
```

### Commands

```
     -1:21.6 tree-view:toggle (select.form-control)
     -0:54.4 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
wordpress-api, v1.1.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-04-04 16:26
Seems like a duplicate of https://github.com/azizur/atom-wordpress-api/issues/4, which was fixed. If you can still reproduce, open an issue on that package's issue tracker.

**Closed by izuzak** 2015-04-04 16:26 UTC

**Comment by ewistrand** [comment] 2015-04-04 17:18
I apologize for not closing this. I was able to fix by replacing the single quotes with double quotes throughout and it fixed the issue.
