### ISSUE TITLE
can't drag tab to window without anything open.

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#5780] opened 2015-02-27 07:52 UTC
How to reproduce: open two Atom windows, open one or more files in window 1, close all tabs in window 2. Drag a tab from window 1 to window 2. Window 2 doesn't appear to accept this tab. If window 2 does have one or more tabs open, it does accept tabs dragged onto it.

I'm not sure if it's a bug or a feature, but I can't think of a reason why an empty window shouldn't accept tabs dragged onto it.

(I'm on Windows 7 with Atom 0.182.0)

**Comment by izuzak** [comment] 2015-05-27 14:34
@stijnsanders I'm unable to reproduce this on windows 8 -- I can definitely drag tabs from one window to another, even when the destination window has no tabs open. So wanted to double-check if this might be windows7 specific before closing.

**Comment by stijnsanders** [comment] 2015-05-27 20:36
I'm not sure if it's Win7 specific, but I tried again on version 0.201.0. I also notice now, the cursor doesn't change to a 'prohibited' cursor (Ø), but actiually to a 'drop' cursor (arrow with grayed box), but still won't move the tab on drop to the window without tabs open.

**Comment by izuzak** [comment] 2015-07-30 18:36
Can anyone else reproduce this on Windows7? /cc @atom/issue-triage

**Comment by bpinney** [comment] 2017-01-17 20:51
I am experiencing this issue with Atom version 1.13.0 x64 on OS X 10.11.6.

The cursor icon changes to a green circle with a white plus inside when dragging the tab to the new, empty window, but when releasing the mouse button the dragged tab does not appear in the empty window.

I remember Atom behaving as expected in the past, and I think an update caused it to stop.

**Comment by lee-dohm** [comment] 2017-11-13 05:46
We haven't had any reports of this in a while. I just tested using Atom v1.24.0-dev-cb82a4201 on Mac OS X 10.13.1 and it works as long as you hover over the second window until it pops into the foreground, then release the button.

**Closed by lee-dohm** 2017-11-13 05:46 UTC
Labels: enhancement, more-information-needed
