### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by jaideepdas** [atom/atom#7388] opened 2015-06-23 18:38 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\app.asar\src\window-event-handler.js:150:33)
    at HTMLDocument.handler (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\jaideepdas\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -0:36.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:36.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:35.9.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -0:32.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:31.2.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:29.9.0 core:copy (atom-text-editor.editor.is-focused)
  8x -0:29.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:28.1.0 core:paste (atom-text-editor.editor.is-focused)
 17x -0:27.3.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:25.7.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:25.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:24.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:19.9.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.6.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:11 core:undo (atom-text-editor.editor.is-focused)
  3x -0:09.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.5

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-06-23 18:45
This is a duplicate of  https://github.com/atom/atom/issues/6548 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-23 18:45 UTC
