### ISSUE TITLE
Long minified files make it crash!

### ISSUE THREAD

**Issue by abelncm** [atom/atom#9865] opened 2015-11-29 16:48 UTC
Because bootstrap.min.css is long horizontaly, it makes Atom crash everytime.
When I reopen Atom, it crashes again because it opens in that file.

**Comment by abelncm** [comment] 2015-11-29 16:49
Should have a better way to handle crashes, it's really terrible at it!

**Comment by mnquintana** [comment] 2015-11-29 17:05
This is a duplicate of https://github.com/atom/atom/issues/979 – feel free to subscribe there for updates.

**Closed by mnquintana** 2015-11-29 17:05 UTC
