### ISSUE TITLE
Uncaught Error: spawn /Users/omenta/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Conten...

### ISSUE THREAD

**Issue by omenta** [atom/atom#11333] opened 2016-03-31 18:03 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.1
**System**: Mac OS X 10.11.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/omenta/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/omenta/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/omenta/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/omenta/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.setPaths (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:217:27)
    at /Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:185:27
    at Function.module.exports.Emitter.simpleDispatch (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.setPath (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:345:27)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1054:12)
    at TextEditor.module.exports.TextEditor.saveAs (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:635:26)
    at Pane.module.exports.Pane.saveItemAs (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at Pane.module.exports.Pane.saveItem (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:621:21)
    at Pane.module.exports.Pane.saveActiveItem (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:596:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:673:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:205:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/omenta/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
```

### Commands

```
     -0:41.6.0 vim-mode:reverse-search-current-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:40.9.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:39.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:29.3.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:21.7.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:20.6.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:19.7.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:19.7.0 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:19.7.0 editor:indent (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:10 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:05.7.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "softWrap": true,
    "backUpBeforeSaving": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-03-31 19:29
This is a duplicate of #10774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-31 19:29 UTC
