### ISSUE TITLE
Does not successfully autoupdate on OS X El Capitan 

### ISSUE THREAD

**Issue by ryanattrexin** [atom/atom#12468] opened 2016-08-18 23:08 UTC
Version 1.9.6 on OSX 10.11.6
Running as a non-Administrator user
Automatic updates are offered e.g. to 1.9.9. 
When I choose to restart and install updates, the process begins but fails silently. Updates are downloaded but not installed. 

Example, 1.9.9 is downloaded to ~/Library/Application Support/com.github.atom.ShipIt, However, the App is never moved to the Applications folder and the required user prompt for credentials does not happen. In the background the ShipIt process is  - I believe - trying to move the application bundle but fails silently. 

Suggest you prompt the user for credentials if the process does not have the privilege to move the bundle to the application folder.

ErrorLog 

2016-08-18 17:54:25.060 ShipIt[55237:960562] Installation error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSLocalizedDescription=Permission denied}
2016-08-18 17:54:25.060 ShipIt[55237:960562] ShipIt quitting
2016-08-18 17:54:25.097 ShipIt[55257:960615] Resuming installation attempt 3
2016-08-18 17:54:25.118 ShipIt[55257:960619] Couldn't abort install and restore owned bundle to previous location file:///Applications/Atom.app, error NSError { domain: NSPOSIXErrorDomain, code: 2, description: "No such file or directory" }
2016-08-18 17:54:30.817 ShipIt[55257:960621] Installation error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={NSLocalizedDescription=Permission denied}
2016-08-18 17:54:30.817 ShipIt[55257:960621] ShipIt quitting
2016-08-18 17:54:30.852 ShipIt[55275:960661] Too many attempts to install, aborting update
2016-08-18 17:54:30.855 ShipIt[55275:960662] Error aborting installation: Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory" UserInfo={NSLocalizedDescription=No such file or directory}
2016-08-18 17:54:30.910 ShipIt[55275:960662] Application launched at file:///Applications/Atom.app
2016-08-18 17:54:30.910 ShipIt[55275:960662] ShipIt quitting

**Comment by 50Wliu** [comment] 2016-08-19 00:24
This is a duplicate of #2860 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-19 00:24 UTC
