### ISSUE TITLE
Can't exclude folders/filetypes in Search

### ISSUE THREAD

**Issue by JulianJorgensen** [atom/atom#6758] opened 2015-05-12 19:32 UTC
I absolute LOVE atom, but this is the one and only big complaint I have.

My project compiles files to "public/" folder. This folder is not git-ignored, so therefore it shows up when I search my project for anything. This is very annoying as I never need to see results from this folder.

Would be perfect if I could exclude file types/folders. Specially if it was working with "Projects settings".

Thanks guys, you rock!

**Comment by 50Wliu** [comment] 2015-05-12 20:30
Duplicate of atom/find-and-replace#149, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-12 20:30 UTC
