### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\C:\ProgramData\*\atom\app-...

### ISSUE THREAD

**Issue by brucelau-github** [atom/atom#20233] opened 2019-12-12 16:46 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\ProgramData\*\atom\app-1.41.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:160

Error: The specified module could not be found.
\\?\C:\ProgramData\bruce.liu1\atom\app-1.41.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:/ProgramData/bruce.liu1/atom/app-1.41.0/resources/app/static/<embedded>:1:727373)
    at get_KeyboardLayoutManager (C:/ProgramData/bruce.liu1/atom/app-1.41.0/resources/app/static/<embedded>:14:2746273)
    at get_manager (C:/ProgramData/bruce.liu1/atom/app-1.41.0/resources/app/static/<embedded>:14:2746375)
    at Object.getCurrentKeyboardLayout (C:/ProgramData/bruce.liu1/atom/app-1.41.0/resources/app/static/<embedded>:14:2746501)
    at e.keystrokeForKeyboardEvent (C:/ProgramData/bruce.liu1/atom/app-1.41.0/resources/app/static/<embedded>:14:1087039)
    at KeymapManager.keystrokeForKeyboardEvent (C:/ProgramData/bruce.liu1/atom/app-1.41.0/resources/app/static/<embedded>:11:1249633)
    at KeymapManager.handleKeyboardEvent (C:/ProgramData/bruce.liu1/atom/app-1.41.0/resources/app/static/<embedded>:11:1247618)
    at WindowEventHandler.handleDocumentKeyEvent (C:/ProgramData/bruce.liu1/atom/app-1.41.0/resources/app/static/<embedded>:11:284598)
```

### Commands

```
     -0:12.3.0 find-and-replace:show (input.hidden-input)
```

### Non-Core Packages

```
compare-files 0.8.1 
language-batch 0.4.0 
language-powershell 5.0.0 
pretty-json 2.0.3 
xml-formatter 0.13.0 
```

**Comment by sadick254** [comment] 2020-09-16 15:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-16 15:15 UTC
