### ISSUE TITLE
[Suggestion] Autosaves on exit

### ISSUE THREAD

**Issue by ethamitc** [atom/atom#16280] opened 2017-11-28 00:16 UTC
This is a suggestion

Could you implement a system where Atom will save all your open files to a temp location, kinda like Notepad ++. It would be nice to see that feature implemented in Atom!

**Comment by rsese** [comment] 2017-11-28 05:27
Thanks for the suggestion!  I think this is a duplicate of https://github.com/atom/autosave/issues/11 so you can subscribe there if you'd like.

Additionally, it's not enabled by default but there's an autosave function that you can enable at `Settings > Packages > Autosave > Enabled` and there may be a community package with similar functionality:

https://atom.io/packages/search?q=auto+save

**Closed by rsese** 2017-11-28 05:27 UTC
