### ISSUE TITLE
"npm ERR!" when trying to build 1.0.15 (wrong cson-safe version?)

### ISSUE THREAD

**Issue by novirium** [atom/atom#8871] opened 2015-09-21 00:20 UTC
An output excerpt when trying to build Atom from the Arch AUR:

```
Node: v4.1.0
npm: v3.3.3
Installing build modules...
npm ERR! Linux 4.1.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--userconfig=/tmp/pacaurtmp-novirium/atom-editor/src/atom-1.0.15/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code EREADFILE

npm ERR! Error extracting /home/novirium/.atom/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT: no such file or directory, open '/home/novirium/.atom/.npm/cson-safe/1.0.4/package.tgz'
```

The relevant parts of npm-debug.log:

```
28309 verbose addNamed "1.0.5" is a plain semver version for cson-safe
28310 silly cache afterAdd cson-safe@1.0.5
28311 verbose afterAdd /home/novirium/.atom/.npm/cson-safe/1.0.5/package/package.json not in flight; writing
28312 verbose afterAdd /home/novirium/.atom/.npm/cson-safe/1.0.5/package/package.json written
28313 silly rollbackFailedOptional Starting
28314 silly rollbackFailedOptional Finishing
28315 silly runTopLevelLifecycles Starting
28316 silly runTopLevelLifecycles Finishing
28317 silly install printInstalled
28318 verbose stack Error: Error extracting /home/novirium/.atom/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT: no such file or directory, open '/home/novirium/.atom/.npm/cson-safe/1.0.4/package.tgz'
28318 verbose stack     at ReadStream.<anonymous> (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:276:10)
28318 verbose stack     at emitOne (events.js:77:13)
28318 verbose stack     at ReadStream.emit (events.js:169:7)
28318 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:179:14
28318 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
28318 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
28319 verbose cwd /tmp/pacaurtmp-novirium/atom-editor/src/atom-1.0.15/build
28320 error Linux 4.1.6-1-ARCH
28321 error argv "/usr/bin/node" "/usr/bin/npm" "--userconfig=/tmp/pacaurtmp-novirium/atom-editor/src/atom-1.0.15/build/.npmrc" "install" "--loglevel" "error"
28322 error node v4.1.0
28323 error npm  v3.3.3
28324 error code EREADFILE
28325 error Error extracting /home/novirium/.atom/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT: no such file or directory, open '/home/novirium/.atom/.npm/cson-safe/1.0.4/package.tgz'
28326 error If you need help, you may report this error at:
28326 error     <https://github.com/npm/npm/issues>
28327 verbose exit [ 1, true ]
```

I honestly don't know a lot about the npm build process, but this looks like it's downloading cson-safe version 1.0.5, then trying to extract a package named 1.0.4 instead.

**Comment by goggle** [comment] 2015-09-21 02:20
I get exactly the same error when trying to buil Atom 1.0.15.

**Comment by djseng** [comment] 2015-09-21 04:12
same issue... just as lost. http://pastebin.com/uAkYvEpP

**Comment by juvevood** [comment] 2015-09-21 07:08
same issue

**Comment by vdemin** [comment] 2015-09-21 07:27
I think the problem is in grunt-cson that requires cson-safe. Simple reproduce the error:
```bash
% npm install cson-safe
npm ERR! Linux 4.1.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "cson-safe"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code EREADFILE

npm ERR! Error extracting /home/vdemin/.npm/cson-safe/1.0.4/package.tgz archive: ENOENT: no such file or directory, open '/home/vdemin/.npm/cson-safe/1.0.4/package.tgz'
```

**Comment by phw** [comment] 2015-09-21 08:07
Seems to be an issue with npm 3 and the cson-safe package. Downgrading to npm 2 allows you to install the package with `npm install cson-safe` and also perform the atom installation.

I have reported https://github.com/groupon/cson-parser/issues/46

**Comment by claudiutraistaru** [comment] 2015-09-21 14:20
Is there a way to include it in package.json ? I cannot find where cson-safe is put as dependency and maybe changing it`s name would suffice.

**Comment by phw** [comment] 2015-09-21 14:30
An upgrade to the new package name `cson-parser` is probably the way to solve this. But I doubt just exchanging the name in any dependency list will help as the module name has also changed (thus it needs `require('cson-parser')` instead of `require('cson-safe')`

**Comment by DuckThom** [comment] 2015-09-21 15:49
It looks like I've managed to build it successfully on Arch Linux using a modified `grunt-cson` and updated `runas` dependency.

First I've cloned [grunt-cson](https://github.com/kevinsawicki/grunt-cson)
After that was done, I changed all the occurances of `cson-safe` to `cson-parser` in the cloned repository.
I then changed `"grunt-cson": "^0.15.0",` in `build/packages.json` (In the atom repository) to `"grunt-cson": "/home/luna/builds/grunt-cson",` (The path to the cloned grunt-cson directory)

It failed to build the `runas` node module with the following error:

> make: *** [Release/obj.target/runas/src/main.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

 After changing `"runas": "^2"` in `build/packages.json` to `"runas": "^3.0"` Atom started to build. After that was done I was able to run Atom. So far I haven't run into any issues besides the fact that everything is very tiny in Atom on my retina display.

**Comment by vdemin** [comment] 2015-09-21 16:47
https://github.com/atom/atom/commit/4e4b3cef373797227d102baa57d2d5af47064ec4 fixes the issue with cson-safe/cson-parser.

**Comment by 50Wliu** [comment] 2015-09-21 19:54
Since the cson-safe/cson-parser issue seems to have been resolved, I'm going to close this.
If you are still unable to build using Node 0.10/0.12 or io.js 1/2 please create a new issue.  Thanks!

**Closed by 50Wliu** 2015-09-21 19:54 UTC
Labels: build-error

**Comment by pmarcelll** [comment] 2015-09-23 10:26
Hi, i saw d3ac862707361ff9493a99c83d6f50ed9ef68551 on the stable channel, but the new version wasn't actually released. Is there a blocking issue maybe or the team forgot to/didn't want to release it? Thanks!

**Comment by claudiutraistaru** [comment] 2015-09-23 10:46
Already applied that patch , now it passes that checking , now the problems
on my side are that I have latest node and not all packages were updated.
I`ll wait for the  update of packages and retry after.

2015-09-23 13:27 GMT+03:00 Marcell Pardavi <notifications@github.com>:

**Comment by pmarcelll** [comment] 2015-09-23 17:21
Thanks!

**Comment by sjug** [comment] 2015-09-23 17:22
How is this closed 2 days ago but not merged into the release 1 hour ago?

**Comment by t128** [comment] 2015-09-26 08:07
still the same error in ```v1.0.19```

**Comment by 50Wliu** [comment] 2015-09-26 16:55
The latest release does not have this change yet.  Master does however.

**Comment by pagondel** [comment] 2015-09-27 02:15
On Archlinux is compiling without problems in v1.0.19.

**Comment by sjug** [comment] 2015-09-27 03:26
@pagondel, yes it is because I've manually patched the release before it builds. Check the pacakge.patch.
