### ISSUE TITLE
Atom does not move files in project pane when it moves them in the file system

### ISSUE THREAD

**Issue by Alexandria-Davis** [atom/atom#18905] opened 2019-02-25 03:05 UTC
[Enter steps to reproduce:]

1. Open Atom to a project
2. Drag a file from one folder to another
3. An uncaught error exception can be thrown by attempting to drag the file to another location without collapsing the folder the file was previously in.
Error provided by atom: `Uncaught Error: ENOENT: no such file or directory, lstat '~/ThisLifeDev/sfml/src/triggers/trigger...`

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/null/ThisLifeDev/sfml/src/triggers/triggerable.h'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/home/null/ThisLifeDev/sfml/src/triggers/triggerable.h'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:14:916798)
    at TreeView.t.exports.TreeView.onDrop (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:14:922552)
    at HTMLDivElement.<anonymous> (/snap/atom/214/usr/share/atom/resources/app/static/<embedded>:14:897392)
```

### Commands

```
     -3:15.5.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -3:12.4.0 core:backspace (input.hidden-input)
     -3:11.5.0 core:confirm (input.hidden-input)
     -3:08.6.0 core:save (input.hidden-input)
  4x -3:06.1.0 core:backspace (input.hidden-input)
     -2:58.9.0 core:save (input.hidden-input)
     -1:23.6.0 core:copy (input.hidden-input)
     -1:21 core:paste (input.hidden-input)
     -1:20.3.0 core:save (input.hidden-input)
     -0:56.6.0 core:backspace (input.hidden-input)
     -0:56.2.0 core:save (input.hidden-input)
     -0:47.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
  4x -0:43.8.0 core:backspace (input.hidden-input)
     -0:42.2.0 core:cancel (input.hidden-input)
     -0:39.7.0 core:backspace (input.hidden-input)
     -0:39.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
build-cmake 0.12.0 
language-cmake 1.1.0 
```

**Comment by rsese** [comment] 2019-02-25 21:49
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

> 3. An uncaught error exception can be thrown by attempting to drag the file to another location without collapsing the folder the file was previously in.

Can you share a GIF of what you're describing here?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-25 21:49 UTC
