### ISSUE TITLE
Bad Atom editor screen background color painting - tiling in wrong color

### ISSUE THREAD

**Issue by doliver3** [atom/atom#13099] opened 2016-10-29 15:48 UTC
### Prerequisites

* [x ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
Open any file in an editor in Atom
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
The background color of the whole document should stay the same throughout the editing session and regardless of where the cursor is placed.

**Actual behavior:** [What actually happened]
Text has a darker background color in squares around the text while areas without text or current line focus appear in a lighter gray color.  It should not be leaving the areas it did not paint text or cursor lines in a different lighter gray color. The background color of the document should be consistent always no matter what editing or how far the text extends. It is extremely distracting to the point of not being useable to have the background color of the text document different where Atom has not painted the screen recently. 

![image](https://cloud.githubusercontent.com/assets/98346/19830963/49f81ca8-9dcd-11e6-8ca1-2a7dbc04153f.png)

![image](https://cloud.githubusercontent.com/assets/98346/19830966/5e9d12da-9dcd-11e6-9971-fd6e48725f84.png)

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

 atom --version
Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10

MacOS 10.12 (Sierra)

**Comment by mnquintana** [comment] 2016-10-29 16:33
You're running an old version of Atom – can you reproduce this with the latest version? (Atom 1.11.2)

**Comment by Ben3eeE** [comment] 2016-10-29 16:54
https://github.com/atom/atom/issues/12634?

**Comment by 50Wliu** [comment] 2016-10-29 19:06
Yes, this is a duplicate of #12634.  Feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-29 19:06 UTC
Labels: more-information-needed
