### ISSUE TITLE
Close empty staged diff panes

### ISSUE THREAD

**Issue by ggreif** [atom/atom#17939] opened 2018-08-28 19:02 UTC
## Summary

Close _staged git changes_ pane when diff is empty.

## Motivation

Often I check the staged diffs just before I commit. After performing the latter, the diff vanishes, but the empty pane stays in place, blocking interesting content. I have to manually close the pane.

## Describe alternatives you've considered

Automatically close empty staged diffs panes. Or at least send them to the background.

**Comment by Arcanemagus** [comment] 2018-08-28 19:12
Thanks for taking the time to contribute!

We noticed that this looks to be a duplicate of https://github.com/atom/github/issues/1160. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-08-28 19:12 UTC
