### ISSUE TITLE
On MacOS Catalina, Atom doesn't display a window at launch when launched via icon (click on icon) or via launcher (e.g. Alfred or Spotlight) but does produce one when launched via the 'atom' command in a terminal

### ISSUE THREAD

**Issue by gbstan** [atom/atom#21751] opened 2020-11-23 14:26 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

On MacOS Catalina 10.15.7, Atom 1.53 (installed via homebrew) doesn't display a window at launch when launched via icon (click on icon) or via launcher (e.g. Alfred or Spotlight) but does produce one when launched via the 'atom' command in a terminal

### Steps to Reproduce

1. Click on Atom icon or launch via launcher (Spotlight or Alfred)

**Expected behavior:**

Main Atom window created

**Actual behavior:**

No window is created. No window can be opened via keyboard shortcut or by trying to open recent documents.

**Reproduces how often:**

Reproducible 100% of the time

### Versions

atom --version
Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.53.0
python 3.7.9
git 2.29.2

### Additional Information

Behaviour is as expected if atom is launched from the command line via the command 'atom'.

This seems related to issue #21013

**Comment by pricemi115** [comment] 2020-11-24 22:28
I had this problem as well. Very reproducible when letting v1.52 update to v1.53 and/or uninstalling and installing v1.53 from the 'Atom.io' website. However, a friend was able to run v1.53 just fine and we are on the same OS version. 
I tried launching from the command line and it worked just like @gbstan mentions in the report. But after doing this, launching via Spotlight and /Applications/Atom.app works fine. But launching via Keyboard Maestro still fails.

**Comment by pricemi115** [comment] 2020-11-25 02:19
FWIW - when I launch Atom in the "failed" manner, I do not see any instances of 'Atom Helper (Renderer)' running. But when I launch it successfully there are a few of these processes running,

**Comment by JacekKowalczyk-TomTom** [comment] 2020-11-25 16:20
I have the same, after. First time after install I got Atom window opened, but after minimizing it it never got back to me. reinstallation did not help.

**Comment by JacekKowalczyk-TomTom** [comment] 2020-11-25 16:20
It does not work from launcher nor from command line.

**Comment by gianmichelemariani** [comment] 2020-12-01 17:28
Confirming this. Launching from spotlight works, but even right clicking on a file and opening with Atom no window is displayed. Is it getting stuck with the project window?

**Comment by pricemi115** [comment] 2020-12-01 17:49
Seems folks are seeing different behaviors where the "bad" behavior is alway the same. Atom launches but without any windows or ability to open a file (menus all grayed out, other than about and exit). For me...at the present time, I can launch by spotlight and icon and it is ok. But if I launch via keyboard maestro (activate application application) then it fails. Quitting  and relaunching via one of the functional ways is fine. Dropping back a couple of versions makes the problem go away...launching all way is always functional.

**Comment by gianmichelemariani** [comment] 2020-12-01 17:55
True. This is what I get (both with nightly and stable)

<img width="472" alt="Screenshot 2020-12-01 at 17 44 13" src="https://user-images.githubusercontent.com/46694168/100777981-5b376980-33fe-11eb-8a65-80edfbd0f451.png">
 

One thing that I've noticed is that it is also difficult to quit Atom. Most of the times I have to force-quit it (the option in the menu has no effect).

**Comment by KromaticGG** [comment] 2021-01-07 16:33
I've been having the same issue for a few months. Any ideas what's causing this?

**Comment by DeeDeeG** [comment] 2021-01-11 04:26
### Tentative fix in progress

I think I have the fix for this. The cause I'm investigating is related to Gatekeeper.

Let me know if this bug happens for you right when... You are launching Atom and see Gatekeeper pop up with a loading bar and a message 'Verifying "Atom"', or something about "This was downloaded from the internet, are you sure you want to open this?". I believe this bug happens when Gatekeeper itself handles launching the app.

If you see this bug, _**don't quit atom**_, and please see the steps below to help me confirm what the causes is for this issue. Thanks!

### Technical explanation of the buggy startup:

I see a command-line flag `-psn_0_[some six or seven digits here]` (something like `-psn_0_1234567`) applied to the buggy Atom process, when inspecting using [`htop`](https://htop.dev) or `ps -ax`. I have seen reports elsewhere that this flag is added by Gatekeeper. For example: https://github.com/godotengine/godot/pull/37719

Our argument parser library `yargs` thinks this `-psn_0_1234567` flag is a bunch of short flags, equivalent to `-p`, `-s`, `-n`, `-_`, `-0`, `-_`, `-1`, `-2`, `-3`, `-4`, `-5`, `-6`, `-7`. The `-_` are converted to boolean `true`, and then we try to do JS string-only operations on the flags. Doing [`true.startsWith()`](https://github.com/atom/atom/blob/v1.53.0/src/main-process/parse-command-line.js#L190) results in a TypeError ("`path.startsWith` is not a function") very early in our initialization process, leaving the app barely started up at all, and unable to respond to most kinds of input other than quitting.

Quitting and restarting means Gatekeeper is already familiar with the binary, and it won't intervene with launching the app. So the flag doesn't get added, and Atom works fine after a restart.

### Help out with confirming the cause of this issue (if you want)

If you are on macOS and see this bug, and want to help verify what's going on, please follow these steps:

- **_Don't quit Atom!_**
- Open the "Terminal" app
- Run this command: `ps -ax | grep Atom`
  - The long flags on `Atom Helper (GPU).app` are expected, such as `--gpu-preferences=IAAAAAAAAAAgAAAAAAAAAAAA` ..., so you don't need to report that. I'm mostly concerned about flags on the main process.
  - You can try this and see if it gives you just the main Atom process: `ps -ax | grep Atom | head -n 1`

The result may look something like this:

`65336 ??         0:02.25 /Applications/Atom.app/Contents/MacOS/Atom -psn_0_5178608`

Please let me know if you see a flag resembling this in the output: `-psn_0_5178608` (even if the numbers are different).

Or if you want, paste the output. That said, I'm going to be posting a fix as a PR for that particular issue, so if you see the exact same thing (and no other exotic flags), then it should be solved soon. (If you see some other flag, particularly one with an underscore `_` in it, please do post your results!)

**Comment by JacekKowalczyk-TomTom** [comment] 2021-01-11 08:23
Today installed Version 1.53.0 (1.53.0), and again the window is not visible. 

kowalczy@PL1MCL-C02D9G95MD6M ~ % ps -ax |grep Atom
 2677 ??         0:01.36 /Applications/Atom.app/Contents/MacOS/Atom -psn_0_331857
 2678 ??         0:00.15 /Applications/Atom.app/Contents/Frameworks/Atom Helper (GPU).app/Contents/MacOS/Atom Helper (GPU) --type=gpu-process --field-trial-handle=1718379636,1140306022173910659,16622427427775972031,131072 --disable-features=LayoutNG,SpareRendererForSitePerProcess --gpu-preferences=IAAAAAAAAAAgAAAAAAAAAAAAYAAAAAAACAAAAAAAAAAIAQAAIAAAAAABAAAAAAAACAEAAAAAAAAQAQAAAAAAABgBAAAAAAAAIAEAAAAAAAAoAQAAAAAAADABAAAAAAAAOAEAAAAAAABAAQAAAAAAAEgBAAAAAAAAUAEAAAAAAABYAQAAAAAAAGABAAAAAAAAaAEAAAAAAABwAQAAAAAAAHgBAAAAAAAAgAEAAAAAAACIAQAAAAAAAJABAAAAAAAAmAEAAAAAAACgAQAAAAAAAKgBAAAAAAAAsAEAAAAAAAC4AQAAAAAAAMABAAAAAAAAyAEAAAAAAADQAQAAAAAAANgBAAAAAAAA4AEAAAAAAADoAQAAAAAAAPABAAAAAAAA+AEAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAAAAAAcAAAAQAAAAAAAAAAAAAAAIAAAAEAAAAAAAAAAAAAAACgAAABAAAAAAAAAAAAAAAAsAAAAQAAAAAAAAAAAAAAANAAAAEAAAAAAAAAAAAAAADgAAABAAAAAAAAAAAQAAAAAAAAAQAAAAAAAAAAEAAAAGAAAAEAAAAAAAAAABAAAABwAAABAAAAAAAAAAAQAAAAgAAAAQAAAAAAAAAAEAAAAKAAAAEAAAAAAAAAABAAAACwAAABAAAAAAAAAAAQAAAA0AAAAQAAAAAAAAAAEAAAAOAAAAEAAAAAAAAAAEAAAAAAAAABAAAAAAAAAABAAAAAYAAAAQAAAAAAAAAAQAAAAHAAAAEAAAAAAAAAAEAAAACAAAABAAAAAAAAAABAAAAAoAAAAQAAAAAAAAAAQAAAALAAAAEAAAAAAAAAAEAAAADQAAABAAAAAAAAAABAAAAA4AAAAQAAAAAAAAAAYAAAAAAAAAEAAAAAAAAAAGAAAABgAAABAAAAAAAAAABgAAAAcAAAAQAAAAAAAAAAYAAAAIAAAAEAAAAAAAAAAGAAAACgAAABAAAAAAAAAABgAAAAsAAAAQAAAAAAAAAAYAAAANAAAAEAAAAAAAAAAGAAAADgAAAA== --service-request-channel-token=14289878028058802667
 2852 ttys004    0:00.00 grep Atom
kowalczy@PL1MCL-C02D9G95MD6M ~ %
kowalczy@PL1MCL-C02D9G95MD6M ~ %
kowalczy@PL1MCL-C02D9G95MD6M ~ %
kowalczy@PL1MCL-C02D9G95MD6M ~ %
kowalczy@PL1MCL-C02D9G95MD6M ~ % ps -ax |grep Atom|head -n 1
 2677 ??         0:01.36 /Applications/Atom.app/Contents/MacOS/Atom -psn_0_331857
kowalczy@PL1MCL-C02D9G95MD6M ~ %

**Comment by pricemi115** [comment] 2021-01-11 11:55
Yesterday I upgraded to macOS BigSur, installing over the top of my existing Catalina install. Before upgrading I observed the problem. Just checking after the upgrade and I no longer observe the problem. The installation of Atom remained the same (v1.53).

**Comment by DeeDeeG** [comment] 2021-01-11 16:20
@jacekkopecky I see the flag from Gatekeeper again in your results: `-psn_0_331857`

Thank you for helping to confirm.

@pricemi115 I'm not sure if you want to go through the trouble, as I'm getting very confident in what the cause is, but I've found that installing an older version of Atom letting it upgrade itself will usually activate this bug. Or simply downloading any new copy of Atom from the internet and attempting to launch it.

Anything that triggers a dialog from [Gatekeeper](https://support.apple.com/guide/security/gatekeeper-and-runtime-protection-sec5599b66df/web)/[XProtect](https://support.apple.com/guide/security/protecting-against-malware-sec469d47bd8/web).
Like this:

!["Omnifocus 2 " is an application downloaded from the Internet. Are you sure you want to open it? [Cancel] [Show Web Page] [Open]](https://images.techhive.com/images/article/2014/11/gatekeeper-dialog-100530556-large.png)

![Verifying "Microsoft Powerpoint"...](https://appletoolbox.com/wp-content/uploads/2019/10/Verifying-Microsoft-PowerPoint-App-in-macOS-Catalina.jpg)

!["Example-App" is an app downloaded from the Internet. Are you sure you want to open it? [?] [Cancel] [Open]](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/Mojave/macos-mojave-notarized-app-alert-dark.jpg)

And for unsigned builds (such as from CI's "Pull Requests" pipeline):

![macOS cannot verify the developer of "Example-App". Are you sure you want to open it? By opening this app, you will be overriding system security which can expose your computer and personal information to malware what may harm your Mac or compromise your privacy. [?] [Move to Trash] [Open] [Cancel]](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/Catalina/macos-catalina-alert-unsigned-override.jpg)

(More info about Gatekeeper and so on: https://support.apple.com/HT202491)

---

If you are seeing this bug from a _different cause_, then that is very interesting, and it would be good to get any details so I can try to reproduce the issue and find an additional fix, if necessary.

**Comment by DeeDeeG** [comment] 2021-01-11 16:21
If you are seeing this bug from a _different cause_ than Gatekeeper (see comment above), then that is very interesting, and it would be good to get any details so I can try to reproduce the issue and find an additional fix, if necessary.

**Comment by KromaticGG** [comment] 2021-01-11 18:40
> FWIW - when I launch Atom in the "failed" manner, I do not see any instances of 'Atom Helper (Renderer)' running. But when I launch it successfully there are a few of these processes running,

This is what I'm noticing as well. When Atom fails to load a "problematic" file there is no Atom Helper (Renderer) running.

**Comment by KromaticGG** [comment] 2021-01-11 18:50
> ### Help out with confirming the cause of this issue (if you want)
> If you are on macOS and see this bug, and want to help verify what's going on, please follow these steps:
> 
> * **_Don't quit Atom!_**
> * Open the "Terminal" app
> * Run this command: `ps -ax | grep Atom`
>   
>   * The long flags on `Atom Helper (GPU).app` are expected, such as `--gpu-preferences=IAAAAAAAAAAgAAAAAAAAAAAA` ..., so you don't need to report that. I'm mostly concerned about flags on the main process.

Yep I'm confirming that I'm seeing a psn flag as well. Here is the flag that I'm getting on the main process while the application has failed to load a "problematic" file:
37541 ??         0:00.99 /Applications/Atom.app/Contents/MacOS/Atom -psn_0_19620533

**Comment by pricemi115** [comment] 2021-01-12 02:19
@DeeDeeG - I dropped back to v1.52 and let it autoupdate back to v1.53. Still runs fine now that I am on Big Sur. When I tried this exact same thing on this very system running Catalina, I would see the problem upon returning to v1.53. 🤷‍♂️

**Comment by jacekkopecky** [comment] 2021-01-12 11:30
> @jacekkopecky I see the flag from Gatekeeper again in your results: `-psn_0_331857`
> 
> Thank you for helping to confirm.

@DeeDeeG hi, you may have meant @JacekKowalczyk-TomTom there?

**Comment by DeeDeeG** [comment] 2021-01-12 15:24
@pricemi115 maybe they fixed Gatekeeper to not add this strange flag `-psn_0_[1234567]` to apps it launches... Which our command-line argument parser `yargs` sees as a somewhat ludicrous 12 or 13 short flags `-p` `-s` `-n` `-_` `-0` `-_` (again) `-1` ... and so on.

Atom up to this point hasn't been designed to handle command-line arguments like this. The fix I am trying to fanilize at the moment is to allow Atom to handle such inputs.

**Comment by DeeDeeG** [comment] 2021-01-12 15:26
@jacekkopecky yes, you are correct. My apologies for the unrelated mention. Sometimes the @mention autocomplete is very helpful. Other times it's not! I suppose I need to look more carefully.

**Closed** 2021-01-18 16:22 UTC
