### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by gu-ramosp** [atom/atom#14530] opened 2017-05-20 16:10 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\Users\gu_ra\AppData\Local\atom\app-1.17.0\resources\electron.asar\browser\objects-registry.js:41:28)
    at EventEmitter.<anonymous> (C:\Users\gu_ra\AppData\Local\atom\app-1.17.0\resources\electron.asar\browser\rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\gu_ra\AppData\Local\atom\app-1.17.0\resources\electron.asar\browser\api\web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At C:\Users\gu_ra\AppData\Local\atom\app-1.17.0\resources\electron.asar\renderer\api\remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.17.0/resources/app/src/atom-environment.js:663:1)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.17.0/resources/app/src/atom-environment.js:697:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:184:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1
```

### Commands

```
     -2:18.8.0 editor:newline (input.hidden-input)
  4x -2:02.4.0 core:backspace (input.hidden-input)
     -1:27.3.0 core:move-right (input.hidden-input)
     -1:26.7.0 intentions:highlight (input.hidden-input)
     -1:26.5.0 core:save (input.hidden-input)
  5x -1:26.3.0 intentions:highlight (input.hidden-input)
     -1:25.6.0 script:run (input.hidden-input)
     -1:02.7.0 core:delete (input.hidden-input)
     -1:01.1.0 intentions:highlight (input.hidden-input)
     -1:01.0 core:save (input.hidden-input)
     -1:00.2.0 script:run (input.hidden-input)
     -0:52.6.0 editor:newline (input.hidden-input)
     -0:46.5.0 intentions:highlight (input.hidden-input)
     -0:46.4.0 core:save (input.hidden-input)
     -0:20.2.0 editor:newline (input.hidden-input)
     -0:17.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-runner 2.7.1 
atom-webbrowser 2.1.4 
browser-plus 0.0.87 
busy-signal 1.4.1 
dbg 1.6.0 
dbg-gdb 1.7.1 
git-control 0.9.0 
git-plus 7.9.1 
highlight-selected 0.13.1 
Hydrogen 1.13.0 
intentions 1.1.2 
language-matlab 0.2.1 
language-rdf 0.5.0 
linter 2.1.4 
linter-ui-default 1.5.4 
minimap 4.28.2 
nord-atom-syntax 0.9.1 
output-panel 0.1.4 
pdf-view 0.58.0 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
ramda-syntax 1.0.3 
script 3.14.1 
sync-settings 0.8.1 
```

**Comment by vitalkanev** [comment] 2017-05-20 16:42
Duplicate of #11692 **again?**

**Comment by 50Wliu** [comment] 2017-05-20 21:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #11692. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-05-20 21:20 UTC
