### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by masterseeger** [atom/atom#17214] opened 2018-04-25 10:35 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:493

TypeError: Cannot match against 'undefined' or 'null'.
    at TextMateLanguageMode.indentLevelForLine (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:493:38)
    at TextMateLanguageMode.endRowForCodeFoldAtRow (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:677:41)
    at TextMateLanguageMode.endRowForFoldAtRow (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:656:25)
    at TextMateLanguageMode.isFoldableAtRow (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-mate-language-mode.js:380:23)
    at TextEditor.isFoldableAtBufferRow (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-editor.js:3933:63)
    at TextEditorComponent.queryLineNumbersToRender (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-editor-component.js:945:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-editor-component.js:387:16)
    at TextEditorComponent.updateSync (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at etch.getScheduler.updateDocument (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/text-editor-component.js:225:46)
    at ViewRegistry.performDocumentUpdate (/Users/achimseeger/Desktop/sammelordner/programme/Atom.app/Contents/Resources/app/src/view-registry.js:238:13)
```

### Commands

```
```

### Non-Core Packages

```
teletype 0.13.0 
```

**Comment by rsese** [comment] 2018-04-25 17:53
Thanks for contributing!

Closing since this is a duplicate of https://github.com/atom/atom/issues/17155.  Can you reproduce in safe mode (`atom --safe`)?

Also, #17155 was closed because the error was not reproducible in Atom Beta - if you still get the error in safe mode, can you confirm if you can still reproduce in the beta?

https://atom.io/beta

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-25 17:53 UTC
