### ISSUE TITLE
Unable to install 1.40+ on Windows 2012 R2

### ISSUE THREAD

**Issue by Thilas** [atom/atom#19975] opened 2019-09-28 15:22 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I am no longer able to install Atom (x64 or x86) on Windows 2012 R2 starting with version 1.40. There was no problem until version 1.39.

### Steps to Reproduce

1. Download Atom 1.40 installer
2. Start the installer

**Expected behavior:**

Atom to be installed

**Actual behavior:**

I get the following error:
![image](https://user-images.githubusercontent.com/3749820/65818604-3bf9e680-e213-11e9-84e9-26df77b03316.png)

And when I close this window, I get the a new one:
![image](https://user-images.githubusercontent.com/3749820/65818615-5b910f00-e213-11e9-8c98-2d2ea5b21d43.png)

Here is the content of Squirrel-Install.log file:
```
[28/09/19 15:16:19] info: Program: Starting Squirrel Updater: --install .
[28/09/19 15:16:19] info: Program: Starting install, writing to C:\Users\Administrator\AppData\Local\SquirrelTemp
[28/09/19 15:16:19] info: Program: About to install to: C:\Users\Administrator\AppData\Local\atom
[28/09/19 15:16:19] info: CheckForUpdateImpl: Reading RELEASES file from C:\Users\Administrator\AppData\Local\SquirrelTemp
[28/09/19 15:16:19] fatal: Finished with unhandled exception: System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'System.String System.String.Format(System.IFormatProvider, System.String, System.Object)'.
   at NuGet.SemanticVersion.Parse(String version)
   at Squirrel.VersionExtensions.ToSemanticVersion(String fileName)
   at Squirrel.Utility.<>c.<FindCurrentVersion>b__29_0(ReleaseEntry x)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Squirrel.Utility.FindCurrentVersion(IEnumerable`1 localReleases)
   at Squirrel.UpdateManager.CheckForUpdateImpl.determineUpdateInfo(UpdaterIntention intention, IEnumerable`1 localReleases, IEnumerable`1 remoteReleases, Boolean ignoreDeltaUpdates)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.MissingMethodException: Method not found: 'System.String System.String.Format(System.IFormatProvider, System.String, System.Object)'.
   at NuGet.SemanticVersion.Parse(String version)
   at Squirrel.VersionExtensions.ToSemanticVersion(String fileName)
   at Squirrel.Utility.<>c.<FindCurrentVersion>b__29_0(ReleaseEntry x)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Squirrel.Utility.FindCurrentVersion(IEnumerable`1 localReleases)
   at Squirrel.UpdateManager.CheckForUpdateImpl.determineUpdateInfo(UpdaterIntention intention, IEnumerable`1 localReleases, IEnumerable`1 remoteReleases, Boolean ignoreDeltaUpdates)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Reproduces how often:**

Always

### Versions

1.40.0 and above (x86 and x64)

### Additional Information

None

**Comment by rsese** [comment] 2019-10-04 19:53
Thanks for the report - haven't seen these particular errors before, not sure if there were changes in 1.40 that caused this?  Don't have Windows 2012 R2 to try out but since the problem is during installation, I'm assuming that running Atom with the [atom-x64-windows.zip](https://github.com/atom/atom/releases/latest) works fine?

**Comment by Thilas** [comment] 2019-10-05 16:29
I confirm that Atom works just fine when using zip files (I tested both x86 and x64).

**Comment by Thilas** [comment] 2019-10-05 16:32
Some .NET prerequisite may have changed regarding Squirrel. Does that make sense?

**Comment by lee-dohm** [comment] 2019-10-08 20:00
Thanks for reporting this issue.

Given that this is a problem only in the installer, there is a workaround for installation, and that it is exclusive to an older version of Windows Server, this isn't something that we're going to work on fixing. However, it is something that we would be open to reviewing a well-written pull request for. Because of this, I'm going to close the issue and mark it as `help-wanted`.

Let us know if you have any questions.

**Closed by lee-dohm** 2019-10-08 20:00 UTC
Labels: help-wanted, installer, windows

**Comment by Thilas** [comment] 2019-10-08 20:47
FYI, I am the maintainer of the chocolatey package for atom and it happens that Windows Server 2012 is the platform used to validate all new chocolatey packages. And since version 1.40, no new atom packages could be validated (except for the prerelease ones since they are not tested).
