### ISSUE TITLE
Atom autosave opened blank files when a location is mounted

### ISSUE THREAD

**Issue by JacopoGobbi** [atom/atom#11797] opened 2016-05-20 14:28 UTC
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? I tried even in the beta
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? I know exactly what's happening
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? I assume that is not suitable
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? Maybe
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? I tried

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

A file present in a position not mounted get autosaved by a blank file and there is not a possibility to revert.
This bug happens to me since a script automatically mount in a folder my working dir thanks to my `~/.bashrc`. But sometimes it fails, and since I don't realise but I open atom as soon as the system finish boot, once I open up a terminal, bash automatically runs the script and try again to mount my working dir and all my files opened in Atom workspace get automatically saved and replaced with blank files.
**Please help me provide a better title and ask for more information if there is some need for a better understanding.**
### Steps to Reproduce
1. Enable autosave
2. Mount a drive
3. Open a file in the mounted folder
4. Enable the option for atom to save the workspace
5. Close atom
6. Unmount the drive
7. Open atom (Atom opens the file as blank, not finding it)
8. Mount the location

**Expected behavior:** [What you expected to happen]
The file gets reloaded as soon as the mounting point is available or you get prompted regarding that.

**Actual behavior:** [What actually happened]
The file get replaced by atom automatically without options to reverting back (ctrl+z as example).
### Versions

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
and
Atom    : 1.8.0-beta3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by iolsen** [comment] 2017-02-04 00:56
@ungb for repro

**Comment by ungb** [comment] 2017-02-06 20:16
I am seeing this issue where the blank file is showing up when the drive is unmounted.  Instead of showing a blank file when the drive is unmounted, we should warn the user that Atom was unable to load the file since it couldn't find it and open a empty editor in that case.  

If you make edits to the empty file and then mount the drive, the changes are lost.

**Comment by smashwilson** [comment] 2017-09-20 18:54
atom/atom#15681 should make this not happen now, because we no longer open empty TextEditors for buffers that were present on disk but are now missing. @ungb, care to confirm?

**Comment by rsese** [comment] 2018-10-26 23:06
Looking through some older issues - based on the change Ash [referenced](https://github.com/atom/atom/issues/11797#issuecomment-330947405) we're going to go ahead and close this but if anyone can still reproduce, please let us know!

**Closed by rsese** 2018-10-26 23:06 UTC
Labels: bug, data-loss, network, triaged
