### ISSUE TITLE
Cannot delete files through atom on Windows

### ISSUE THREAD

**Issue by elebumm** [atom/atom#10041] opened 2015-12-13 07:55 UTC
I am currently running Windows 7. I am unable to delete files after I am prompted for deletion.

![github](https://cloud.githubusercontent.com/assets/6053155/11766116/e20f9f60-a144-11e5-80a9-cf135b03ea12.PNG)

It just doesn't do anything and won't delete the file.

**Comment by faeliaso** [comment] 2015-12-13 15:20
I am using Win7 and I'm going through the same problem

**Comment by 50Wliu** [comment] 2015-12-13 16:33
This is a duplicate of atom/tree-view#666 and is being tracked upstream at atom/electron#3656, please subscribe there for updates.

**Closed by 50Wliu** 2015-12-13 16:33 UTC
