### ISSUE TITLE
Uncaught Error: spawn /Users/xxxx/Library/Application Support/com.github.atom.ShipIt/update...

### ISSUE THREAD

**Issue by nilseckert** [atom/atom#9844] opened 2015-11-27 10:52 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/xxxx/Library/Application Support/com.github.atom.ShipIt/update.kFSkj5E/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/xxxx/Library/Application Support/com.github.atom.ShipIt/update.kFSkj5E/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/xxxx/Library/Application Support/com.github.atom.ShipIt/update.kFSkj5E/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/xxxx/Library/Application Support/com.github.atom.ShipIt/update.kFSkj5E/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/xxxx/Library/Application Support/com.github.atom.ShipIt/update.kFSkj5E/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.plus.mapObject (/Users/xxxx/Library/Application Support/com.github.atom.ShipIt/update.kFSkj5E/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:287:37)
    at Object.plus.deepClone (/Users/xxxx/Library/Application Support/com.github.atom.ShipIt/update.kFSkj5E/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:130:21)
```

### Commands

```
     -0:03.1.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-edit"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-11-27 13:49
Thanks for the report, @nilseckert. I believe this is a duplicate of #9559 and #7399, so please subscribe there for updates.

**Closed by izuzak** 2015-11-27 13:49 UTC
