### ISSUE TITLE
Atom error failed to load config.cson

### ISSUE THREAD

**Issue by brutalcrozt** [atom/atom#15706] opened 2017-09-21 09:34 UTC
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom error failed to load config.cson, the config.cson unexpectedly contain a lot of white space.
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/0c4uI6D2i6w/0.jpg)](https://www.youtube.com/watch?v=0c4uI6D2i6w)

### Steps to Reproduce

1. Cleanup the config.csom white space.
2. Update atom or atom packages. I am not sure which one i did.
3. Open atom, the config.cson contain white space again.

**Expected behavior:** 
Run atom as usual, then i can write some code.

**Actual behavior:** 
It pop up failed to load config.cson with `stdin:1:1: error: unexpected`

**Reproduces how often:**
100%, i update atom or it's packages twice. It does the same error.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
OS: windows 8 64bit
atom: version 1.20.1 via UI (help-> version)
atom -v: 
```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
apm -v:
```
apm			1.18.1
npm			3.10.10
node		6.9.5  ia32
python	        2.7.11
git			2.14.1.windows.1
visual studio    2015
```
apm ls -i:
```
[36mCommunity Packages (29)[39m C:\Users\x\.atom\packages
├── atom-autocomplete-php@0.25.6
├── atom-beautify@0.30.5
├── atom-ternjs@0.18.3
├── autoprefixer@3.7.1
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── compare-files@0.8.1
├── css-color-underline@1.0.1
├── docs-snippets@0.8.0
├── emmet-atom@2.4.3
├── file-templates@0.2.0
├── hyperclick@0.1.5
├── imdone-atom@2.2.7
├── intentions@1.1.5
├── js-hyperclick@1.11.0
├── language-pug@0.0.21
├── language-typescript-grammars-only@1.6.0
├── linter@2.2.0
├── linter-coffeelint@1.3.1
├── linter-eslint
├── linter-pug-lint@0.2.0
├── linter-ui-default@1.6.10
├── livereload@0.4.4
├── php-hyperclick@1.2.1
├── pigments@0.40.2
├── project-manager@3.3.5
├── rest-client@1.3.1
├── sort-lines@0.15.0
└── split-diff@1.5.1
```
### Additional Information

I am not sure what actually cause that. but before i record that video. I already clean `config.cson` which contain a lot of white space. When i clean up that file, it only contain white space.

**Comment by 50Wliu** [comment] 2017-09-21 09:49
I believe this is a duplicate of #14909.  A potential fix shipped in Atom 1.21.0-beta1.

**Closed by 50Wliu** 2017-09-21 09:49 UTC
