### ISSUE TITLE
Atom hangs when given long, non-standard HTML files

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8154] opened 2015-07-30 05:34 UTC
It's kind of illegal "html" that Honeywell's Experion HMI WebBuilder spits out.

It typically starts out like this:
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML xmlns:v = "urn:schemas-microsoft-com:vml" xmlns:o = 
"urn:schemas-microsoft-com:office:office" xmlns:p = 
"urn:schemas-microsoft-com:office:powerpoint" xmlns:w = 
"urn:schemas-microsoft-com:office:word"><HEAD><TITLE></TITLE>
<META content="text/html; charset=windows-1252" http-equiv=Content-Type>
<META name=DisplayVersion-PS content=6.11>
<META name=HMIWebTemplateDescription content="Create a blank HMIWeb display.">
<STYLE>v\:* {
	BEHAVIOR: url(#default#VML)
}
o\:* {
	BEHAVIOR: url(#default#VML)
}
p\:* {
	BEHAVIOR: url(#default#VML)
}
w\:* {
	BEHAVIOR: url(#default#VML)
}
.shape {
	BEHAVIOR: url(#default#VML)
}
</STYLE>

<OBJECT style="POSITION: absolute; WIDTH: 0px; HEIGHT: 0px; TOP: 0px; LEFT: 0px" 
id=HDXPageBehavior codeBase="" 
classid=clsid:1234ABCD-56EF-1234-5678-90ABCDEF0123></OBJECT>
```

and only goes downhill from there. You'll see about 12000 lines of VBScript tags, which begin like:

```html
<SCRIPT language=VBScript for="" type="" defer event="">'--------------------------------------
'Scada RegCntl - Mode; Hialm Type; EUDesc; 
'--------------------------------------
```

and are only terminated by `</SCRIPT>`. You'll see `id`, `class`, and other custom attributes whose values aren't quoted, despite containing non-alphanumeric characters and punctuation, like `id=shape005 class=hsc.shape.1 tabIndex=-1`. And you'll see other, similar abuses.

Which is fine, but the HTML syntax highlighter should be more accommodating, and more importantly Atom shouldn't hang and crash when scrolling through this.

**Comment by rcharney** [comment] 2015-08-03 03:11
I am having a similar problem. 

I run Ubuntu 14.04 on a 64-bit machine. I just installed Atom v1.0.3 and have not added any packages. I have loaded a dump of our database consisting of 116457 lines (70.1MB) of SQL. It appears to load the complete file. However, when I try to search the file, the program hangs after entering 1 or 2 characters in the search string, My console showed this error:

reg@reg-desktop:~/Downloads$ atom -d c1pro_entrebahn.sql
reg@reg-desktop:~/Downloads$ [18958:0802/230757:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 298ms
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[18991:0802/230757:INFO:renderer_main.cc(212)] Renderer process started
[18958:0802/230801:INFO:CONSOLE(56)] "Window load time: 3632ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (56)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 813 error_code 3 request_code 40 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by benogle** [comment] 2015-08-03 17:56
@alexchandel I assume your issue is one of #979 or #307 

@rcharney your issue is atom/find-and-replace#145

**Comment by benogle** [comment] 2015-08-03 17:56
@alexchandel can you share the file you are having trouble with?

**Comment by alexchandel** [comment] 2015-10-14 20:26
@benogle 

> I assume your issue is one of #979 or #307

That could be part of it, but the thing is, it's not even close to as bad if I set the language to "Plain Text" instead of HTML. I assume it's because there are so many regexes in the HTML package that are failing and backtracking because of the pseudo-HTML garbage that HMI WebBuilder produces.

> can you share the file you are having trouble with?

I can't post it online, but I could share it with one person who works at GitHub.

**Comment by prettydiff** [comment] 2016-03-08 21:58
Here is the problem as I have experienced it.  I am on OSX Yosemite using Atom 1.5.4.

## Steps to reproduce

1. Open https://raw.githubusercontent.com/prettydiff/prettydiff/8cd02e1b1e728a42011abad5a10a098b0a86d334/lib/jspretty.js in Atom as a JavaScript grammar.
2. Go to line 2099 and insert a `(` immediately prior to the opening square brace.

## Perceived problem

It appears the inserted character causes the colors of the code text to change in response to an unclosed paren (broken syntax).  This color change follows through the remainder of the document, but something gets lost in an endless loop.

## Suggested fix

Never change color on character type.  Only change color once all keys are released.  The browser equivalent are the onkeydown and onkeyup events.  Keep a count of all keys that are pressed and decrement each time a key is released.  Once the count returns to 0 (all keys released) then evaluate whether to change code color.

**Comment by 50Wliu** [comment] 2016-03-08 22:32
@prettydiff I can't reproduce this using the sample file on Atom 1.7.0-dev-c8dd4f3, but perhaps that's because the language-javascript package has been updated several times since Atom 1.5.4.

**Comment by alexchandel** [comment] 2016-05-26 23:17
This still happens to me in Atom 1.7.4, but only for large files with syntactic errors.

The root cause of the problem is probably that syntax highlighting work is done on the GUI thread. This should never happen.

**Comment by trusktr** [comment] 2016-06-28 17:51
Tracking all these large-file issues in #12065.

**Comment by mnquintana** [comment] 2016-06-29 00:42
This seems like a duplicate of https://github.com/atom/atom/issues/8864 – let's keep the discussion going there.

**Closed by mnquintana** 2016-06-29 00:42 UTC
Labels: more-information-needed
