### ISSUE TITLE
atom.config.get '<some-color>' doesn't return an instance of Color if set in config.cson

### ISSUE THREAD

**Issue by olmokramer** [atom/atom#5306] opened 2015-01-29 16:54 UTC
When I try to `get` a config value of a setting with the `color` type, and the setting is saved to `config.cson` (so not the default value), I don't get an instance of the `Color` class, but rather just the object/string that was in `config.cson`.

Versions:
Atom: `0.176.0`
OS: Linux Debian 8 (testing)

**Comment by jeromeetienne** [comment] 2015-01-29 17:48
i experience the same under macosx yosemit, atom 0.176.0

**Comment by benogle** [comment] 2015-01-29 18:05
Is this if you `set` and then `get`? Or is this after a reload with just a `get`? 

This might be a dupe of https://github.com/atom/atom/issues/5219

**Comment by olmokramer** [comment] 2015-01-29 20:25
I'm sorry, I was in a hurry when I wrote this. It happens with `observe`. You can find an example of the code where this happens [here](https://github.com/olmokramer/atom-block-cursor/blob/master/lib/block-cursor.coffee). If you add `console.log color` on line 56, I get just an object with 4 properties (`red`, `green`, `blue`, `alpha`)

**Comment by olmokramer** [comment] 2015-01-29 20:34
After testing a bit more, it also seems to happen with `atom.config.get`

**Comment by benogle** [comment] 2015-01-29 21:00
I'm going to assume this is a dupe of #5219

**Comment by olmokramer** [comment] 2015-01-29 21:04
Probably, yes. I now see that it only happens at startup of Atom

**Closed** 2015-01-30 02:06 UTC
Labels: bug, more-information-needed
