### ISSUE TITLE
Preferred line length marker stays the same when changing font.

### ISSUE THREAD

**Issue by stepanbujnak** [atom/atom#6484] opened 2015-04-22 18:09 UTC
When I'm on my laptop I use 13pt Monaco. When I get to work, I change font to 16pt (because of larger screen, higher resolution) and the preferred line length (80 columns) stays the same. I need to close and reopen all files in order to get it to behave correctly.

**Comment by 50Wliu** [comment] 2015-04-22 20:31
Duplicate of atom/wrap-guide#25, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-22 20:31 UTC
