### ISSUE TITLE
Catastrophic backtracking 

### ISSUE THREAD

**Issue by MikeMajara** [atom/atom#15513] opened 2017-08-31 07:48 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When searching for certain regex expressions Atom hangs and does not recover.

### Steps to Reproduce

1. I want to search for ocurrences of the portion in bold within my project
 ```
<table id="tablaAlbaranes" class="table datatable-column-search-inputs-custom">
                            <thead>
                                <tr>
                                    <th style="width: 50px; visibility:hidden;">Selector</th>**
                                    <th>asdf</th>
                                    <th>asdf</th>
```
2. Therefore I search (either in entire project/solution, or in single file) with the following regex expression \<table(.*\s*\n*)*?\<t ... 

3. When I get to this point, Atom stops working and I am forced to reset.

**Expected behavior:** I would expect Atom to halt the execution of a match in case it detected a catastrophic backtracking, should there be one.

**Actual behavior:** Atom stops working and does not recover.

**Reproduces how often:** 100% every time I use a complex search term as \<table(.*\s*\n*)*?\<th.*\>.*\<\/th\>

### Versions
Windows 10 x64 v1607
Atom: 1.19.4
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2017-08-31 17:57
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/571 so you can subscribe there for updates if you'd like.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-31 17:57 UTC
