### ISSUE TITLE
Cannot install packages from keyboard without tabbing

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8760] opened 2015-09-11 22:17 UTC
After typing `install` in the command box and choosing `Install Packages and Themes` (which Atom abysmally ranks *last* in the results), the Install pane opens, but one cannot type immediately because the search box doesn't have keyboard focus. Instead, the "Install" tab on the left pane does, and one must tab over at least twice. The search bar should obtain focus, at least in the case when the `Install Packages and Themes` command is chosen, and possibly in other cases. This is a minor inconvenience.

**Comment by mnquintana** [comment] 2015-09-12 03:10
Thanks for the report! This looks like a duplicate of https://github.com/atom/settings-view/issues/432 though – please subscribe there for updates.

**Closed by mnquintana** 2015-09-12 03:10 UTC
