### ISSUE TITLE
Rounded square app icon on macOS Big Sur

### ISSUE THREAD

**Issue by calintat** [atom/atom#21692] opened 2020-11-13 10:09 UTC
With the release of macOS Big Sur, most app icons have been updated to a rounded square shape. It would be very nice if Atom also did the same for consistency. For example, I have Atom in my dock and right now it's the only app without a rounded square icon.

**Comment by Tony1324** [comment] 2020-11-13 16:59
I have made one, how is it
![atom](https://user-images.githubusercontent.com/61944932/99098836-9258ee80-25a7-11eb-812b-b5408fea9e26.png)

**Comment by thatcomputerguy0101** [comment] 2020-11-15 01:18
Duplicate of #21128

**Comment by jen801** [comment] 2021-08-10 18:43
> Duplicate of #21128

**Closed** 2021-08-21 18:53 UTC
