### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by joostdebruijn** [atom/atom#15298] opened 2017-08-14 12:20 UTC
To be honest, I do not know what happens so I cannot explain how to reproduce this issue. However it seems not very difficult to fix this one (simply check if the variable is not null before continuing) so I share the information below.

The issue repeats itself every few seconds.

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of null

```
At C:\Users\joost_000\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2168

TypeError: Cannot read property 'id' of null
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:2168:73)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:2164:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:385:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:270:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.0/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:06.1.0 docblockr:parse-enter (input.hidden-input)
     -1:06.1.0 editor:newline (input.hidden-input)
     -1:05.3.0 core:move-down (input.hidden-input)
     -1:04.7.0 intentions:highlight (input.hidden-input)
  2x -1:03.1.0 core:backspace (input.hidden-input)
     -1:02.7.0 intentions:highlight (input.hidden-input)
     -1:02.6.0 core:save (input.hidden-input)
  3x -0:59.3.0 core:backspace (input.hidden-input)
     -0:57.4.0 intentions:highlight (input.hidden-input)
     -0:57.3.0 core:save (input.hidden-input)
     -0:44 intentions:highlight (input.hidden-input)
     -0:43.8.0 core:copy (input.hidden-input)
     -0:38.1.0 intentions:highlight (input.hidden-input)
     -0:38 core:paste (input.hidden-input)
     -0:27.8.0 intentions:highlight (input.hidden-input)
     -0:27.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
busy-signal 1.4.3 
docblockr 0.11.0 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.4 
```

**Comment by joostdebruijn** [comment] 2017-08-14 12:22
Maybe related to #15168 and/or steelbrain/linter-ui-default#414.

**Comment by Ben3eeE** [comment] 2017-08-14 12:34
I would say that this is a duplicate of https://github.com/atom/atom/issues/15168. The issue will repeat itself quite often when you get into this state. Try restarting Atom to get rid of the repeated notifications.

We are working on getting a hotfix release out to fix this issue.

**Closed by Ben3eeE** 2017-08-14 12:34 UTC
Labels: duplicate
