### ISSUE TITLE
big files with long lines crashes atom 1.0.0 (in ubuntu at least)

### ISSUE THREAD

**Issue by andersmartini** [atom/atom#7930] opened 2015-07-16 10:01 UTC
basicly seems to be the same issue as #979. supposedly solved in v1.0.0 but it still happens for me on ubuntu 14.04 64-bit. I haven't tried on any other OS.

crash occurs when opening minified js-files

**Comment by mnquintana** [comment] 2015-07-16 10:31
This is a duplicate of #979, which has not been fixed yet - please subscribe there for updates.

**Closed by mnquintana** 2015-07-16 10:31 UTC
