### ISSUE TITLE
Uncaught Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr...

### ISSUE THREAD

**Issue by yesther10** [atom/atom#15700] opened 2017-09-20 15:54 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Debian GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node)

```
At ELECTRON_ASAR.js:173

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/resources/app/node_modules/oniguruma/build/Release/onig_scanner.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/oniguruma/src/oniguruma.js:1:190)
    at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/oniguruma/src/oniguruma.js:105:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at get__ref (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar.js:13:33)
    at get_OnigRegExp (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar.js:17:45)
    at new Grammar (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar.js:58:42)
    at GrammarRegistry.module.exports.GrammarRegistry.createGrammar (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar-registry.js:202:23)
    at /usr/share/atom/resources/app/node_modules/first-mate/lib/grammar-registry.js:121:82
    at parseContents (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:123:13)
    at /usr/share/atom/resources/app/node_modules/season/lib/cson.js:230:26
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-09-20 21:56
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* which Linux distro are you running?

**Comment by rsese** [comment] 2018-01-19 22:13
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15700#issuecomment-330992550. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

As a side note, if you're on RHEL 6 I wonder if this is a duplicate of https://github.com/atom/atom/issues/5172?

**Closed by rsese** 2018-01-19 22:13 UTC
Labels: linux, more-information-needed, uncaught-exception
