### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Ingramz** [atom/atom#19430] opened 2019-06-01 22:11 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at dump (C:\Users\Indrek\Desktop\atom-x64-windows (2) (2)\resources\app.asar\src\file-system-blob-store.js:113:71)
    at FileSystemBlobStore.getDump (C:\Users\Indrek\Desktop\atom-x64-windows (2) (2)\resources\app.asar\src\file-system-blob-store.js:119:9)
    at FileSystemBlobStore.save (C:\Users\Indrek\Desktop\atom-x64-windows (2) (2)\resources\app.asar\src\file-system-blob-store.js:44:21)
    at AtomEnvironment.saveBlobStoreSync (C:\Users\Indrek\Desktop\atom-x64-windows (2) (2)\resources\app.asar\src\atom-environment.js:1093:22)
    at AtomEnvironment.unloadEditorWindow (C:\Users\Indrek\Desktop\atom-x64-windows (2) (2)\resources\app.asar\src\atom-environment.js:1088:10)
    at WindowEventHandler.handleWindowBeforeunload (C:\Users\Indrek\Desktop\atom-x64-windows (2) (2)\resources\app.asar\src\window-event-handler.js:264:26)
```

### Steps to Reproduce

1. Open project find (ctrl+shift+f)
2. Search for something in project folder and have it return the search results
3. Reload the editor using View->Developer->Reload window

*Edit by @rsese: reproduced on macOS 10.12.6 with 1.39.0-nightly19 using atom/atom (searched for "hello" then reloaded the window).*

**Expected behavior:** No error messages

**Actual behavior:** Error message from above is displayed.

**Reproduces how often:** 100%

### Versions

Atom    : 1.39.0-nightly18
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

Windows 10 x64

### Additional Information

https://github.com/atom/atom/blob/a7a70560db1fb9d1529ca5765bf01e68305a0f6c/src/file-system-blob-store.js#L113

**Comment by rsese** [comment] 2019-06-03 19:34
Thanks @Ingramz - I was unable to reproduce with 1.39.0-nightly19 on macOS 10.12.6 and on Windows 10.  Does this reproduce with any project?

**Comment by Ingramz** [comment] 2019-06-04 04:08
Try with this [test.zip](https://github.com/atom/atom/files/3250462/test.zip)

Search for just `d` and when it's done, just ctrl shift f5. "Preserve log" in developer console options is useful too.

**Comment by Ingramz** [comment] 2019-06-04 04:11
![undefined-test](https://user-images.githubusercontent.com/1017132/58850609-e748c380-8697-11e9-811e-0df4fd8dfb30.gif)

**Comment by vbardales** [comment] 2019-06-04 12:24
:+1:

**Comment by rsese** [comment] 2019-06-05 20:51
Ahhh sorry, totally misread this step:

> 3\. Reload the editor using View->Developer->Reload window

For some reason I think I condensed this to toggling devtools.

Reproduced with the test project you shared on Windows and also reproduced on macOS 10.12.6 with 1.39.0-nightly19 using atom/atom (searched for "hello" then reloaded the window).

**Comment by mena99** [comment] 2019-06-09 15:03
that only worked yesterday , when i tried it today in middle of no where the error reemerged and doesnt go  no matter what i do 
i have uninstall it 
sheift deleted the folders 
downloaded the setup file again 

same error .... nothing works

**Comment by rafeca** [comment] 2019-06-11 17:01
Thanks for reporting!

This seems to be caused by the recent Electron v3: now the [returned `cachedData` value](https://github.com/atom/atom/blob/master/src/native-compile-cache.js#L46) when it can't be produced is `undefined` instead of `null`.

This generates invalid data in our persistant cache since we're [only checking for non-null values](https://github.com/atom/atom/blob/master/src/native-compile-cache.js#L105).

I'm gonna send a quick fix for this one

**Closed** 2019-06-12 07:30 UTC
Labels: d ⬇️, i ⬇️, triaged, uncaught-exception, v ⬇️
