### ISSUE TITLE
Atom closes files not present in current branch

### ISSUE THREAD

**Issue by northamerican** [atom/atom#12613] opened 2016-09-06 22:58 UTC
Consider this workflow: I have new files created in a branch. I then stash my unstaged files and checkout another branch to quickly rebase or something. When I return to the original branch, I must reopen my stashed files in Atom because it considered them deleted and closed the tab. In reality they were just in another branch. 

Other editors I've used (Sublime, Coda) keep the tab open. Both of them pretend the file still exists and recreates it if saved. Try saving the deleted or open file from another branch and Coda also warns the user the file does not exist:
![screen shot 2016-09-06 at 6 50 24 pm](https://cloud.githubusercontent.com/assets/6657634/18293814/22e062f8-7463-11e6-94ba-43a5b94bf060.png)

Regardless of the approach, it is a missing functionality in Atom. My workaround is to close Atom, switch branch, `git` whatever i got to, then checkout again and reopen Atom, so it preserves my open, still existent file that was never really deleted.

This issue partially opposes #5394. Keeping deleted files open and showing a warning message like the one in Coda when saving would resolve this issue and would prevent accidental re-saving of truly deleted files.

**Comment by jlwarlow** [comment] 2016-09-12 15:21
This surprised me the other day when trying to fix a conflicting change in TFS, I needed to delete a file to allow me to undo delete so I could save the change (Changing an add new file when I had an existing delete change to an edit change). In notepad++ this isn't an issue, the file remains open (I do have to fake and edit to allow me to save the file). In Atom, the file just disappeared from the editor without a warning.

**Comment by lee-dohm** [comment] 2016-09-14 00:06
It sounds like this is a duplicate of https://github.com/atom/atom/issues/8598 (or one of the many other issues around switching branches). @northamerican did you do a search to see if you were duplicating one of the already open Issues before you opened this one?

**Comment by lemire** [comment] 2016-09-14 14:30
As I understand it, the problem is simpler and more general. When files are deleted, their in-memory buffer gets deleted automagically and surprisingly without giving the user any chance to save their work. 

This is surprising because no other editor or word processor works this way. It is always understood that the in-memory copy is distinct conceptually from the persisted copy on disk.

**Comment by lee-dohm** [comment] 2016-09-15 16:33
Given the title and the description of this Issue, it is a duplicate of #8598. If there is a more general Issue here, please open a new Issue, fill in the template with steps to reproduce the problem so that we can be sure we're on the same page.

Thanks for the feedback!

**Closed by lee-dohm** 2016-09-15 16:33 UTC

**Comment by lemire** [comment] 2016-09-15 17:08
People concerned with this issue should check out https://github.com/atom/tabs/issues/306
