### ISSUE TITLE
Soft-wrapped lines are wrapped in a <span> with the classes of the last element of the previous line

### ISSUE THREAD

**Issue by burodepeper** [atom/atom#8326] opened 2015-08-11 15:01 UTC
While working on a theme, I noticed the following glitch: the color of the variable GRID on line 156 is different from the one on line 157.

When a line is soft-wrapped, the soft-wrapped next line is wrapped with the classes of the last element of the previous line. In the example below, the last character on line 157 is a comma with the classes `meta delimiter object comma coffee`, and the entire rest of the wrapped line is wrapped inside a div with those classes. Notice how the code of the wrapped part of the line is indented one level more.

Top and bottom of the image are the same, I've just highlighted the important areas.

![atom-soft-wrap-error](https://cloud.githubusercontent.com/assets/3703530/9200693/5281dc84-4049-11e5-92d7-e843ade01837.jpg)

While searching for duplicates, I thought #4842 could be similar.

Atom 1.0.5 on Mac OS X
Theme: minimal-syntax

**Comment by benogle** [comment] 2015-08-11 17:10
cc @nathansobo @maxbrunsfeld

**Comment by nathansobo** [comment] 2015-08-11 17:26
This is a duplicate of https://github.com/atom/atom/issues/7068. Looks like we should fix it because we're getting a lot of reports.

**Comment by benogle** [comment] 2015-08-11 17:28
Closing as dupe

**Closed by benogle** 2015-08-11 17:28 UTC
