### ISSUE TITLE
Can't run atom text editor after i install it

### ISSUE THREAD

**Issue by MuhammedKpln** [atom/atom#13559] opened 2017-01-06 16:19 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Install atom edito on my computer
2. trying to open atom editor but nothing happens im getting flat white screen with developer options. (F12 in chrome you know)

**Expected behavior:** Nothing

**Actual behavior:** trying to open atom editor but nothing happens im getting flat white screen with developer options. (F12 in chrome you know). But the portable version works. 

**Reproduces how often:** Always

### Versions

1.12.9

**Comment by 50Wliu** [comment] 2017-01-06 16:26
Please navigate to the console tab and paste the output here.

**Comment by MuhammedKpln** [comment] 2017-01-08 18:57
`index.js:61 Error: Belirtilen modül bulunamadi.
\\?\C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar.unpacked\node_modules\marker-index\build\Release\marker_index.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\marker-index\dist\native\marker-index.js:9:33)
    at Module._compile (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:14:17)
    at Object.<anonymous> (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:434:4)
    at Module._compile (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\text-buffer\lib\history.js:6:17)
    at Object.<anonymous> (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\node_modules\text-buffer\lib\history.js:450:4)
    at Module._compile (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Users\Muhammed\AppData\Local\atom\app-1.12.9\resources\app.asar\src\compile-cache.js:201:21)handleSetupError @ index.js:61`

**Comment by lee-dohm** [comment] 2017-01-28 02:09
Are you still running into this problem? Or has it been resolved?

**Comment by MuhammedKpln** [comment] 2017-01-28 11:07
Still same

28 Oca 2017 03:10 tarihinde "Lee Dohm" <notifications@github.com> yazdı:

**Comment by lee-dohm** [comment] 2017-01-28 22:17
How did you install Atom? Can you try installing the latest Stable version?

**Comment by AndreaGriffiths11** [comment] 2017-02-08 00:54
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13559#issuecomment-275878613. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by AndreaGriffiths11** 2017-02-08 00:54 UTC
Labels: more-information-needed

**Comment by StijnCrul** [comment] 2017-04-13 08:46
I had the same issue after installing windows updates KB890830, KB4018483, KB4015217. Maybe that is not the cause but it is the only thing that changed overnight that I am aware of.
Reinstalling fixed the issue.
