### ISSUE TITLE
Package list shows a `.bin` package.

### ISSUE THREAD

**Issue by alexlur** [atom/atom#7277] opened 2015-06-15 01:13 UTC
**Atom 0.209.0 on OS X Yosemite and El Capitan Beta**
As the title indicates, the Packages list in Atom Settings always show a package named ".bin". No Atom feature is negatively affected by this bug.

![image](https://cloud.githubusercontent.com/assets/8125011/8151361/a2dc64c6-12d9-11e5-9feb-363a2e9a00c0.png)

![image](https://cloud.githubusercontent.com/assets/8125011/8151333/cbeaaebe-12d8-11e5-9bec-8e9d5f05fa0b.png)

#### `atbuild` file content
```javascript
#! /usr/bin/env node
require('./atbuild.js');
```

If you need any information that I can provide, please let me know.

**Comment by mnquintana** [comment] 2015-06-15 01:26
Thanks for the report! This is a duplicate of github.com/atom/settings-view/issues/348 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-15 01:26 UTC
