### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, lstat 'U:/'

### ISSUE THREAD

**Issue by ehargitt** [atom/atom#18474] opened 2018-11-21 14:21 UTC
[Enter steps to reproduce:]

1. Map U:\ to a network drive on a VPN
2. Add a project folder from U:\
3. Do some editing, minding your own business.
4. Have your VPN mysteriously fail.

Sorry this couldn't be more useful.

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, lstat 'U:\'

```
At fs.js:1621

Error: UNKNOWN: unknown error, lstat 'U:\'
    at Proxy.realpathSync (fs.js:1621:13)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at atom.project.getPaths.map.e (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:804080)
    at Array.map (<anonymous>)
    at Object.startTask (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:804071)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:186748)
    at get_process.nextTick (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:184810)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
language-cmake 1.1.0 
language-docker 1.1.8 
linter 2.0.0 
linter-docker 0.3.2 
linter-ui-default 1.7.1 
multi-cursor 2.1.5 
split-diff 1.5.3 
wrap 0.1.0 
```

**Comment by rsese** [comment] 2018-11-21 22:48
Thanks for the report!

We noticed that this is a duplicate of https://github.com/atom/fuzzy-finder/issues/274 so you can  subscribe there for updates if you'd like.  I'll copy over your repro steps, thanks for sharing those :+1:

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-21 22:48 UTC
