### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by Chechare** [atom/atom#11508] opened 2016-04-18 06:20 UTC
[Enter steps to reproduce below:]

1. I just close the tabs of a pane, don't know what did it.
2. ...

**Atom Version**: 1.7.1
**System**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
     -1:05.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  3x -1:04.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:00.7.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:56.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.2.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:48.4.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:47.4.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:45.5.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:44.6.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:43.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:32.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
 12x -0:31.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:28.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:27.4.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:26.7.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:26.2.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.7.3
fonts, v1.2.0

# Dev
No dev packages
```

**Comment by MartinodF** [comment] 2016-04-18 19:13
I just had the same error after switching focus away from Atom. Here's my details:

**Atom Version**: 1.7.1
**System**: linux 4.5.0-1-ARCH
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
     -0:42.7.0 core:move-left (atom-text-editor.editor.is-focused)
  9x -0:42.5.0 core:select-right (atom-text-editor.editor.is-focused)
  5x -0:41.1.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:32.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:31.9.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:31.6.0 core:select-left (atom-text-editor.editor.is-focused)
  4x -0:31.1.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:27.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:23.6.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
  2x -0:21.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:07.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:07.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.5.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:02.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:01.7.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "/home/mart/Repos",
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  },
  "editor": {
    "fontFamily": "Consolas",
    "fontSize": 13,
    "invisibles": {},
    "preferredLineLength": 140,
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "softWrapHangingIndent": 2
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-fusion-syntax, v1.1.0
autocomplete-go, v1.0.6
builder-go, v1.0.0
environment, v1.2.0
file-icons, v1.7.3
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-line, v0.11.1
language-curly, v0.0.2
language-haml, v0.24.0
linter, v1.11.4
linter-erb, v1.0.2
linter-eslint, v7.2.0
linter-golinter, v1.2.0
linter-gotype, v0.1.0
linter-govet, v0.1.5
linter-haml, v1.2.0
linter-ruby, v1.2.2
linter-ruby-reek, v1.5.1
linter-scss-lint, v2.5.1
minimap, v4.22.1
navigator-godef, v1.0.2
nucleus-dark-ui, v0.7.16
pigments, v0.26.0
sort-lines, v0.14.0
symbol-gen, v1.0.0
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-05-12 14:17
Closing as a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-05-12 14:17 UTC
