### ISSUE TITLE
Column select (like Sublime Text)

### ISSUE THREAD

**Issue by tesfabpel** [atom/atom#6358] opened 2015-04-13 11:43 UTC
Please add the feature to select a column of text with the mouse (like Alt + LMB (Left mouse button), or Shit + RMB) like Sublime Text...

There is a package that provides this functionality ([Sublime-Style-Column-Selection] (https://atom.io/packages/Sublime-Style-Column-Selection)), but I think it's better that this feature should be provided by atom itselft

**Comment by izuzak** [comment] 2015-04-13 12:01
Sounds like a duplicate of https://github.com/atom/atom/issues/2306.

**Closed by izuzak** 2015-04-13 12:01 UTC
