### ISSUE TITLE
Easier way to append to default settings

### ISSUE THREAD

**Issue by dmnd** [atom/atom#4967] opened 2015-01-09 23:16 UTC
I'm trying to add a new grammar to spell-check, and I see this:

![image](https://cloud.githubusercontent.com/assets/4427/5688950/436f8744-9812-11e4-8169-f81679ffdd6c.png)

There's no easy way that I know of to append to that list of defaults. Instead I have to track down what the defaults are, paste them in, and append my own grammar. Then I have to hope that the defaults don't change in a future version of Atom, making my copied list of defaults stale.

**Comment by mjrk** [comment] 2015-10-08 18:06
+1

**Comment by mnquintana** [comment] 2015-10-08 18:13
Looking at this again now, I think this is a duplicate of https://github.com/atom/settings-view/issues/243 – let me know if I'm misunderstanding though!

**Closed by mnquintana** 2015-10-08 18:13 UTC
Labels: enhancement
