### ISSUE TITLE
[Linux] Dragging a file or folder into Atom does not work

### ISSUE THREAD

**Issue by mofux** [atom/atom#14401] opened 2017-05-12 15:56 UTC
### Description

Dragging a file or directory from a GVFS share does not open it in atom

### Steps to Reproduce

- Open Nautilus.
- Connect to a remote server through the location bar.
- Drag a folder into Atom.

**Expected behavior:**

Atom should open the folder or file, just like it does with local files and folders.

**Actual behavior:**

Atom does nothing.

**Reproduces how often:** 

Every time.

### Versions

1.16.0 and previous

### Additional Information

This Bug goes back to electron / chromium which does not handle the document drop event correctly. I have created an issue with a detailed bug description there. Unfortunately it did not get much attention yet.

See: https://github.com/electron/electron/issues/9319

**Comment by pabloab** [comment] 2017-06-19 14:34
I reproduced this bug just using a remote sftp URL on Nautilus. Description: Ubuntu 16.04.2 LTS, Atom: 1.13.1, Electron: 1.3.13, Chrome: 52.0.2743.82, Node: 6.5.0.

**Comment by rsese** [comment] 2017-06-19 18:42
Thanks @pabloab @mofux :v:  Any chance you can try to reproduce this one @ungb?  I don't have this particular setup with a remote server that I can test.

**Comment by pabloab** [comment] 2017-06-19 20:17
I just reproduce it with [one of this free sftp servers](http://www.sftp.net/public-online-sftp-servers):

![screen shot](https://user-images.githubusercontent.com/657836/27303987-f22bdb74-5512-11e7-814f-ee2a4acd7a9a.png)

**Comment by mofux** [comment] 2017-06-19 21:12
Thanks for looking at this issue. I have also tested it on KDE using the Dolphin file manager (which uses `KIO` instead of `GVFS` in the background), and it has the same problem.

**Comment by mofux** [comment] 2017-06-20 09:16
For reference, I have just created a chromium issue here:
https://bugs.chromium.org/p/chromium/issues/detail?id=734959#

**Comment by rsese** [comment] 2017-06-20 20:14
Ohh sorry I missed the Electron issue reference in your report @mofux - reading it, it looks like this is a Chromium issue and there's nothing we can do on the Atom/Electron side?

**Comment by ungb** [comment] 2017-06-20 20:37
I'm going to close this out since this issue is due to https://bugs.chromium.org/p/chromium/issues/detail?id=734959#.  Thanks @mofux for reporting this.  Once this is fixed in chromium, it will come upstream in the following order:  

chromium -> electron -> atom.

**Closed by ungb** 2017-06-20 20:37 UTC
Labels: electron, linux, needs-reproduction

**Comment by mofux** [comment] 2017-10-18 16:41
FYI: This issue will be solved with the next gnome release via https://gitlab.gnome.org/GNOME/nautilus/commit/03b540dbe9b59016e4392b710023aa675ffbc382
