### ISSUE TITLE
Uncaught Error: EEXIST, file already exists '/Users/renews/.atom/storage'

### ISSUE THREAD

**Issue by renews** [atom/atom#5434] opened 2015-02-06 13:19 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EEXIST, file already exists '/Users/renews/.atom/storage'

```
At /Users/renews/.atom/packages/auto-update-packages/node_modules/fs-plus/node_modules/mkdirp/index.js:74

undefined
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".vagrant"
    ],
    "disabledPackages": [
      "atom-jshint",
      "vim-mode",
      "terminal"
    ],
    "themes": [
      "spacegray-dark-ui",
      "monokai"
    ],
    "projectHome": "/Users/renews/SkyDrive/projetos"
  },
  "editor": {
    "fontSize": 12,
    "showInvisibles": true,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
ScssBundle, v0.4.0
atom-beautify, v0.3.4
atom-handlebars, v0.4.0
atom-lint, v0.20.0
auto-update-packages, v0.2.1
coffee-compile, v0.8.4
coffee-eval, v0.8.0
coffee-lint, v0.7.3
color-picker, v1.2.6
command-logger, v0.20.0
css-color-highlight, v0.3.0
docs-snippets, v0.8.0
editor-stats, v0.16.0
emmet, v2.2.1
foundation5-snippets, v0.2.0
language-haml, v0.14.0
linter, v0.9.0
meteor-api, v2.9.0
minitest-snippets, v0.2.0
monokai, v0.9.0
open-last-project, v0.1.1
package-sync, v0.1.1
pretty-json, v0.3.1
project-manager, v1.14.1
rspec-snippets, v0.4.0
ruby-define-method, v0.1.0
ruby-strftime-reference, v0.2.0
script, v2.15.1
spacegray-dark-ui, v0.5.0
trailing-spaces, v0.2.3
travis-ci-status, v0.11.0
visual-bell, v0.9.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-02-06 20:53
Duplicate of #4806

**Closed by kevinsawicki** 2015-02-06 20:53 UTC
