### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 34Error: Cannot call...

### ISSUE THREAD

**Issue by EndBug** [atom/atom#17898] opened 2018-08-22 12:56 UTC
1. Just opened Atom normally (this stuff comes directly from the editor build-in bug report)

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 34
Error: Cannot call function 'getPosition' on missing remote object 34
    at throwRPCError (C:\Users\Federico Grandi\AppData\Local\atom\app-1.29.0\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\Federico Grandi\AppData\Local\atom\app-1.29.0\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\Federico Grandi\AppData\Local\atom\app-1.29.0\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At C:\Users\Federico Grandi\AppData\Local\atom\app-1.29.0\resources\electron.asar\renderer\api\remote.js:221

Error: Cannot call function 'getPosition' on missing remote object 34
Error: Cannot call function 'getPosition' on missing remote object 34
    at throwRPCError (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/renderer/api/remote.js:125:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.29.0/resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.29.0/resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.29.0/resources/app/src/window-event-handler.js:191:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.0 
atom-clock 0.1.16 
atom-discord 1.6.1 
atom-easy-jsdoc 4.12.5 
atom-ide-ui 0.13.0 
busy-signal 1.4.3 
file-icons 2.1.24 
hey-pane 1.1.0 
ide-typescript 0.7.6 
intentions 1.1.5 
language-batch 0.4.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-tslint 1.9.1 
linter-ui-default 1.7.1 
remember-folds 0.3.0 
teletype 0.13.3 
toggle-quotes 1.1.1 
```

**Comment by rsese** [comment] 2018-08-22 17:11
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-08-22 17:11 UTC
