### ISSUE TITLE
Atom unexpected exit

### ISSUE THREAD

**Issue by 1969290646** [atom/atom#17108] opened 2018-04-10 08:52 UTC
### Description

Atom unexpected exit

### Steps to Reproduce

1. run the atom
2. run the ShadowsocksX-NG

**Comment by rsese** [comment] 2018-04-10 19:16
Thanks for reaching out!  In addition to filling out the template as mentioned below, this seems like it could be a duplicate of https://github.com/atom/atom/issues/17071, see Lee's comment /cc https://github.com/atom/atom/issues/17071#issuecomment-378274064.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Closed by rsese** 2018-04-10 19:16 UTC
