### ISSUE TITLE
Unable to use Atom with Hungarian keyboard

### ISSUE THREAD

**Issue by fuszenecker** [atom/atom#8965] opened 2015-09-27 17:23 UTC
No { and * can be typed, which are key signs in TypeScript.

**Comment by mnquintana** [comment] 2015-09-27 17:29
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom-keymap/issues/37 and maybe https://github.com/atom/atom-keymap/issues/35 – please subscribe there for updates.

**Closed by mnquintana** 2015-09-27 17:29 UTC
