### ISSUE TITLE
Close button for find tool. feature request

### ISSUE THREAD

**Issue by noah2828** [atom/atom#9273] opened 2015-10-24 06:21 UTC
A button to toggle the find tool when the find tool is open would be very useful. I currently have to hit alt and then find the toggle under the find options.

**Comment by mnquintana** [comment] 2015-10-24 06:48
This looks like a duplicate of https://github.com/atom/find-and-replace/issues/347 – please subscribe there for updates. You can close any panel in Atom by pressing <kbd>Escape</kbd> - no need to click Toggle.

Also take a look at [the Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) for a guide on where to post issues.

**Closed by mnquintana** 2015-10-24 06:48 UTC
