### ISSUE TITLE
Atom not remembering last state

### ISSUE THREAD

**Issue by yeoldelloyd** [atom/atom#13534] opened 2017-01-03 18:02 UTC
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I want that Atom remembers the last opened session. Basically what the package save-session does: https://atom.io/packages/save-session However, it says the package is deprecated since it is already included in core. But the functionality is not working in my Atom version. In this tutorial it seems to work: https://www.youtube.com/watch?v=IgSW1umKrVs&index=7&list=PLYzJdSdNWNqwNWlxz7bvu-lOYR0CFWQ4I However, not on my machine.

### Steps to Reproduce

1. open random file in Atom
2. close Atom
3. Reopen Atom from macOS dock

**Expected behavior:** Atom should reopen the last opened folders and tabs.

**Actual behavior:** New empty tab is opened (if "open empty editor on start" is activated) or nothing is opened at all (else).

**Reproduces how often:**  100 %

### Versions

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

macOS Sierra 10.12.2 (16C67)

**Comment by 50Wliu** [comment] 2017-01-03 18:14
Are you quitting Atom (Application: Quit), or simply pressing the red X button?

**Comment by yeoldelloyd** [comment] 2017-01-04 16:37
Happens with both.

**Comment by vuphan314** [comment] 2017-01-04 17:06
## Issue Reproduced

### Additional Information
- Core package `autosave` enabled.
- Autosave worked on a previous Atom version (can't remember which one)

### Versions
- ```
  Atom    : 1.12.8
  Electron: 1.3.13
  Chrome  : 52.0.2743.82
  Node    : 6.5.0
  ```
- ```
  apm  1.12.9
  npm  3.10.5
  node 4.4.5
  python 2.7.12+
  git 2.9.3
  ```
- 64-bit Ubuntu 16.10

**Comment by vuphan314** [comment] 2017-01-11 08:32
Issue reproduced with `Atom 1.13`.

64-bit Ubuntu 16.10

```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12+
git 2.9.3

```

**Comment by vuphan314** [comment] 2017-01-14 03:45
This issue is **not** present on `64-bit Windows 10` (Atom 1.13).

**Comment by vuphan314** [comment] 2017-01-20 05:04
I have 2 machines on 64-bit Ubuntu 16.10 sharing Atom settings via Dropbox.

[Atom](https://github.com/atom/atom/releases/download/v1.13.0/atom-amd64.deb) remembers opened tabs on 1 machine only.

**Comment by lee-dohm** [comment] 2017-01-28 22:38
@vuphan314 Depending on how you set up your sharing via Dropbox, this isn't surprising. Sharing settings via Dropbox isn't a supported configuration.

@yeoldelloyd Atom does remember the saved state except in [one well-known circumstance](https://github.com/atom/atom/issues/13318). With the steps to reproduce the problem you've given, this is a duplicate of that issue. I'm going to close this and if you have more detailed steps to reproduce a problem that isn't a duplicate of atom/atom#13318, please open a new issue.

**Closed by lee-dohm** 2017-01-28 22:38 UTC
Labels: more-information-needed, needs-reproduction
