### ISSUE TITLE
Atom occupy very high cpu usage.

### ISSUE THREAD

**Issue by liaodalin19903** [atom/atom#15079] opened 2017-07-23 13:00 UTC
===

### Description

https://i.stack.imgur.com/Cdb4G.jpg

When I use Atom to open a file, the cpu usage rise violently.

### Steps to Reproduce

1. In the Finder, I right click the file
2. Open with Atom
3. then the file is opened, but the CPU usage is rise violently.

**Expected behavior:** [I want it is normal]

**Actual behavior:** [but the cpu usage is high, and is get stuck]

**Reproduces how often:** [when open the file, it get stuck]

### Versions

Atom version: 1.18.0 X64
MacOS Serria: 10.12.2 (16C67)

### Additional Information

I find as long as I open the Atom, the CPU usage will get to 100%

**Comment by rsese** [comment] 2017-07-24 08:09
Thanks for reaching out!  Filling out the issue template is super helpful for us - e.g. what version of Atom are you running (`atom -v`)?  Is the error reproducible in safe mode (`atom --safe`)?   What version of macOS are you running? 

If you can create a new issue with the template filled out, we can go from there.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by liaodalin19903** [comment] 2017-08-01 16:44
@rsese I have re-edited my post, please open it.

**Comment by rsese** [comment] 2017-08-01 19:26
Thanks @liaodalin19903 :+1: - it looks like you didn't include the `Prerequisites` section.  That's helpful because it lets us know if you've tried the debugging steps mentioned in the Flight Manual:

http://flight-manual.atom.io/hacking-atom/sections/debugging/

Do you see the same behavior in safe mode (`atom --safe`)?

Also, do you happen to have a `.git` directory in your home directory?

```
ls -ld ~/.git
```

**Comment by hoyhymho** [comment] 2017-08-10 15:28
Having the same problem, safe mode doesn't help and I don't have a git folder in my project

**Comment by rsese** [comment] 2017-08-11 03:20
@hoyhymho - what version of Atom are you running and what operating system are you on?

> and I don't have a git folder in my project

Do you have a `.git/` folder in your home directory (so not your project directory but `~/.git`)?

**Comment by hoyhymho** [comment] 2017-08-11 09:45
@rsese oh sorry misunderstood the question. I do have one, and it looks like it fixes the cpu problem if I move it. There shouldn't be one there right? So can I just delete it?

have atom v1.19.0

**Comment by rsese** [comment] 2017-08-11 21:05
@hoyhymho - ahhh ok 👍   It's likely a mistake (especially if you don't remember doing it on purpose) so you can just delete it but you could also just rename it (`mv ~/.git ~/.git-backup`).

**Comment by rsese** [comment] 2018-03-03 00:19
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15079#issuecomment-319471562. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-03-03 00:19 UTC
Labels: more-information-needed
