### ISSUE TITLE
Failed to compile atom :TypeError: Incorrect value of args option

### ISSUE THREAD

**Issue by leo191** [atom/atom#13134] opened 2016-11-03 03:34 UTC
I'm on arch and I've tried many ways including installing from user repository , removing atom nodejs npm and again installing it, building it from source ,even I reinstalled my os still giving me same error.
first I thought may be node version and atom versions ar conflicting so I downgraded node and rebuild it but did not work.
then I try to build a older version of atom with older version of nodejs and it worked but above 1.11.* are not working.

 Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step] Download source code from https://github.com/atom/atom.git
2. [Second Step] install all the dependencies and Prerequisites
3. [Third Step] try to script/build

**Expected behavior:** [What you expected to happen]
``child_process.js:145
throw new TypeError('Incorrect value of args option');
^

TypeError: Incorrect value of args option
at Object.exports.execFile (child_process.js:145:11)
at Object.exports.exec (child_process.js:108:18)
at Object.<anonymous> (/home/d-leo/gitty/atom/apm/node_modules/atom-package-manager/script/postinstall.js:10:16)
at Module._compile (module.js:573:32)
at Object.Module._extensions..js (module.js:582:10)
at Module.load (module.js:490:32)
at tryModuleLoad (module.js:449:12)
at Function.Module._load (module.js:441:3)
at Module.runMain (module.js:607:10)
at run (bootstrap_node.js:382:7)`

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Ben3eeE** [comment] 2016-11-03 07:21
This looks like a duplicate of https://github.com/atom/apm/issues/636. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-11-03 07:21 UTC

**Comment by leo191** [comment] 2016-11-03 12:11
thankx @Ben3eeE
