### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by vadimsharapov1** [atom/atom#7380] opened 2015-06-23 07:43 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Вадим\AppData\Local\atom\app-0.211.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -1:27.2.0 window:increase-font-size (ul.list-inline.tab-bar.inset-panel)
     -1:10.2.0 command-palette:toggle (atom-pane.pane.active)
     -0:29 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:24.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:24 core:move-up (atom-text-editor.editor.is-focused)
     -0:23.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:21 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:15.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:15 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "editor": {
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-23 08:25
Thanks for the report -- this is a duplicate of https://github.com/atom/atom/issues/6548, so closing this out. :v:

**Closed by izuzak** 2015-06-23 08:25 UTC
