### ISSUE TITLE
Opening a large (many lines) file with PHP code lets Atom really slow

### ISSUE THREAD

**Issue by brunofunny** [atom/atom#11180] opened 2016-03-17 02:22 UTC
Opening a 250KB file with 3992 lines of PHP code lets Atom really slow. The whole interface freezes and take about 1 minute to unfreeze.

Steps to reproduce
1 - Open Atom
2 - Add Project Folder
3 - Open the file
4 - Scroll to the end of file and hit enter (sometimes it's a BIT faster, but always stucking for a while)

The issue can be reproduced if you just copy the bellow code until it passes 3900 lines more or less, of course with complex files it get worse:

public function newAction()
{ 
    $entityManager   = $this->getEntityManager();
    $setupForm = $this->createForm( new SetupType( $var, $var ) );
    return array( 'form_setup' => $setupForm->createView() );
}

**Comment by mnquintana** [comment] 2016-03-17 03:17
Can you reproduce this after quitting Atom completely and restarting it in safe mode? (`atom --safe`)

**Comment by brunofunny** [comment] 2016-03-17 17:23
Using "atom --safe" the problem doesn't occour. 

- So can it be related to some package ?
- Are the packages in safe mode loaded ?

**Comment by amytruong** [comment] 2016-03-17 17:33
When in safe mode, packages are not loaded so this can definitely be related to one or more packages installed.

**Comment by mnquintana** [comment] 2016-06-29 00:38
Since @brunofunny couldn't reproduce this in safe mode, I'm going to close this out. Feel free to comment if you run into this again in safe mode though!

**Closed by mnquintana** 2016-06-29 00:38 UTC
Labels: more-information-needed, performance
