### ISSUE TITLE
a pane is not .active until a second pane exists

### ISSUE THREAD

**Issue by hg42** [atom/atom#14283] opened 2017-04-22 20:03 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In atom 1.16.0 (stable) I created styles to improve visibility of
* active pane (e.g. background of tab-bar)
* active tab in active pane (e.g. background of tab)

I recently switched to atom 1.17.0-beta3.

Now the pane with the active editor tab does not become active after starting atom.

Instead tree view (which is in a tab now) is shown as the active tab in the active pane or no visible pane is active at all (I didn't find an active pane in developer tools either).

When clicking on an editor tab it's surrounding pane does not get active state.

When I drag one of the editor tabs to a new pane it gets the active state and the new pane is also active.

After creating the second pane all works like expected, even when I close the second pane.
So I assume it's an initialization problem, probably related to the tree view being a tab or some thing similar.

### Steps to Reproduce

1. create a style to conveniently see which is the active pane (and it's active tab):
```
.pane.active {
  .tab-bar {
    background-color: #ffff00 !important;
    .tab {
      &.active {
        background-color: #ff00ff !important;
      }
    }
  }
}
```
2. open some files in a single pane
3. close atom
4. open atom again
5. try to activate the editor pane
6. drag a file tab to a new pane

**Expected behavior:**

the editor pane should be active after start

**Actual behavior:**

Either the pane containing the tree view (left dock) is active or no pane is active at all (at least not visible).
The single editor pane cannot get active state by clicking on a tab or similar actions.

**Reproduces how often:**

100%

### Versions

atom-beta --version:
Atom    : 1.17.0-beta3
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm-beta --version:
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.11.0

OS: Linux Debian "testing"
with some packages from unstable and Ubuntu and ppas etc.

note, I have atom and atom-beta installed in parallel, but they shouldn't interfere.

### Additional Information

not necessary but helpful:
a style (as described above) emphasizing the active pane and the active tab in the active pane.

**Comment by hg42** [comment] 2017-04-22 20:46
I tried to influence the state at start in my init.coffee (without knowledge of atom internals), by assigning active and focus state to left pane and back to editor pane:
```
panes = atom.workspace.getPanes()

#console.log panes

setTimeout ->

    for pane in panes
      if pane.activeItem and pane.activeItem.constructor.name == "TreeView"
        console.log pane
        pane.activate()
        pane.focus()
        console.log pane

    for pane in panes
      if pane.activeItem and pane.activeItem.constructor.name == "TextEditor"
        console.log pane
        pane.activate()
        pane.focus()
        console.log pane

  , 10000
```
I see something like this in the console:
```js
Pane {id: 2, activeItem: TreeView, focused: false, applicationDelegate: ApplicationDelegate, notificationManager: NotificationManager…}
Pane {id: 2, activeItem: TreeView, focused: true, applicationDelegate: ApplicationDelegate, notificationManager: NotificationManager…}
Pane {id: 3, activeItem: TextEditor, focused: false, applicationDelegate: ApplicationDelegate, notificationManager: NotificationManager…}
Pane {id: 3, activeItem: TextEditor, focused: true, applicationDelegate: ApplicationDelegate, notificationManager: NotificationManager…}
```
so I can change at least the focus. But the "active" class is not added to the pane.
Any ideas?

**Comment by hg42** [comment] 2017-04-22 20:55
When I click on the Project tab (tree view) the window title changes to "Project..." and when I click an editor tab the title changes to this. But still no pane is activated.

**Comment by hg42** [comment] 2017-04-22 21:14
When I open two editor panes and then close+reopen Atom (with --safe, so no init script executed),
none of the panes is active.
Then I can click on one of the editor tabs and the corresponding pane is activated.

In case of two editor panes my init script is able to activate a pane. So the script works but doesn't help when having only one editor pane.

**Comment by hg42** [comment] 2017-04-22 22:15
I use this as workaround in init.coffee:
```js
setTimeout ->
    #console.log "open another editor pane"
    atom.workspace.open(null, {split: "right"}).then ->
      setTimeout ->
          #console.log "...close"
          atom.workspace.getActiveTextEditor().destroy()
        , 1
  , 1000
```

**Comment by rsese** [comment] 2017-04-24 08:23
> I recently switched to atom 1.17.0-beta3.
> 
> Now the pane with the active editor tab does not become active after starting atom.

Is this issue describing the same regression you mentioned in https://github.com/atom/one-dark-ui/issues/204#issuecomment-296341911 @simurai ❓

**Comment by hg42** [comment] 2017-04-24 10:04
sorry, I'm not @simurai, and "I" didn't write in that issue you mention above.
I searched for similar items before creating this issue, but didn't find any matching. Seems I overlooked that one.

Indeed, @ooJerryLeeoo's issue could have the same reasons.
So, I assume they could be merged.
Mine has more detailed preconditions, so @ooJerryLeeoo's may still differ from that.
He writes "when the window is close by cmd+w", which is no pre-condition for my issue. The way I close the window doesn't seem to matter in my case.

I think, the key is in the set of panes opened after start.

I assume, there are probably two problems:
* activating one of the panes at start
  * may be, it is activated too early before initialization is finished?
  * may be, the last pane is in the right dock and activation fails because it's empty
  * I wonder why in some situations I have the tree view active after start but most of the time no pane is active
* activating another pane, when no pane is active (by clicking on an editor tab, tree view etc.)
  * perhaps, the deactivation fails because there is no active pane and this also stops the activation?
But creating a new editor pane works, which doesn't fit well with that.
  * but why can't I switch the active pane, when tree view is active after start?
  * why does opening a new editor pane (by dragging or by atom.workspace.open) repair the behaviour? the actions taken in this operation might be a key to the problem

Note, I did not have a look at Atom's source code, yet. I should probably debug it myself.
But currently, I am working on improving an Add-On and want to finish that first.
I will also have to figure out how to debug Atom.

I am kind of newbie in this big javascript world (coming from 25 years C++, perl, ruby, python etc.), so the depth of my knowledge varies a lot.

**Comment by hg42** [comment] 2017-04-24 10:08
I wondered why I didn't find the issue with words like "pane" and "active".
The reason is probably because it's not in atom's issue list but in atom/one-dark-ui.

**Comment by hg42** [comment] 2017-04-24 10:14
at the end it's not a critcal issue, at least not deal breaking.
I think, I saw some other issues that might also be caused by missing pane activation.
So this might increase importance.

**Comment by rsese** [comment] 2017-04-24 17:36
> sorry, I'm not @simurai, and "I" didn't write in that issue you mention above.

😄 yeah I was pinging @simurai to take a look here since he replied in that other issue.

> I wondered why I didn't find the issue with words like "pane" and "active".
> The reason is probably because it's not in atom's issue list but in atom/one-dark-ui.

Yes that's right, if you search in this repository only, then only issues from this repository will be searched.

You can specifically search across Atom organization repositories with this syntax [1]:

`user:atom pane active is:issue`

E.g.:

https://github.com/search?utf8=%E2%9C%93&q=user%3Aatom+pane+active+is%3Aissue&type=

[1]: https://help.github.com/articles/searching-issues/#search-within-a-users-or-organizations-repositories

**Comment by hg42** [comment] 2017-04-25 00:54
ok, I would have expected the @... at the beginning of the paragraph...

and thanks for the tip, I should have a look at github's search syntax

**Comment by simurai** [comment] 2017-04-25 03:22
> @rsese Is this issue describing the same regression you mentioned in https://github.com/atom/one-dark-ui/issues/204#issuecomment-296341911

Yes, right. This sounds like it's the same. Let's keep this as the "main" issue. 👍 

So to summarize:

- In `1.16` it was possible to use a `.pane.active` selector to highlight which pane is currently the active one.
- In `1.17` it's not possible anymore because the `.active` class only gets added when there is a split pane. And it doesn't get removed when the focus moves to the tree-view (or any other dock item).

Maybe it's not tree-view related but got introduced with the new [docks](https://github.com/atom/atom/pull/13977). Not sure if it's a regression or just the meaning of "active pane" changed.

Also, `.pane.active` was more a workaround for the questions "is a pane currently focused". Here an issue that describes the problem: https://github.com/atom/atom/issues/10938. Using `.pane:focus` doesn't work because the focus gets immediately transferred to the pane item.

An alternative might be to add a `.tab.is-focused-dock-item` (or similar) class to only the tab associated with the currently focused dock item?

/cc @nathansobo @maxbrunsfeld @matthewwithanm

**Comment by hg42** [comment] 2017-04-25 08:29
I would not summarize it as "only working when there is a split pane".

I think it's an initialization problem.

It all works normally *after* the split pane was openend (and may be closed again like in my workaround).

So it's generally working as expected but needs to be "repaired" first.

I think we should focus on how it might get "repaired" by opening a second editor pane. The split pane does something more or different than clicking on tabs etc.

**Comment by hg42** [comment] 2017-04-25 08:44
To mark the pane .active is more versatile than only marking the focused tab, because you can better highlight the tabbar background or draw a frame.

But if non-editor panes like docks can get active it's less useful. It's not helpful to highlight them. 

So you may be right marking only the focused tab should do.

A criterion should be if there is a user action only working on the active pane, something like a keyboard shortcut switching tabs in the active pane.
Either we need the .active pane to visualize where this action works *or* we should widen the domain of that action to all panes (or all editor panes etc.). I would probably choose the later, because it removes a mode and makes user interaction easier.

**Comment by matthewwithanm** [comment] 2017-04-25 10:47
@simurai My gut reaction:

"Activeness" is a contextual concept, not a global one. Like, at any point in time there are multiple active items and when we talk about _the_ active item what we really mean is "the active pane's active item." The docks feature just adds another level to the hierarchy so it feels like we just need to represent that level's activeness in the DOM too. So if you wanna target _the_ active pane, you'd need to target "the active pane container's active pane," or `atom-workspace-center.active pane.active, atom-dock.active pane.active`. That's a change for anybody who was assuming that "active pane" was a global concept but I think if we did otherwise, "active" would mean different things in the DOM and the model.

There could be a new convenience class that means "the active pane of the active container," though. Also, there should maybe be some class added to the center and dock elements to identify them as containers. But that's a little hairy though because even they _are_ containers in the model vernacular, they're _composing_ `atom-pane-container`s in the DOM vernacular.

**Comment by hg42** [comment] 2017-04-25 11:29
In fact, the global active tab should be sufficient to detect which containers contain it at any level.

**But** unfortunately CSS does not allow this (currently).
You cannot express: "select the container that contains the active tab" (but it should and this is discussed from time to time).
As a workaround, it might be necessary to mark some or all the parent containers as active.

But if the active pane doesn't matter for the user it shouldn't be necessary to mark it at all.

Currently I see no need for an active pane other than visualizing which tab has the real focus.
I think this is very important. I used `.pane.active .tab` only to have different colors for my tabs, because I couldn't decide which one I am writing or referring to, without visually searching for the cursor. This is especially necessary if you have toolbar buttons using the active editor tab. With split panes I cannot see which one I will act upon.

**Comment by hg42** [comment] 2017-04-25 11:44
@matthewwithanm I agree.
It should be made clear, what "active" should mean conceptually.

The main concern for the user is to know where his key bindings will go to.

E.g. you could have locally defined key bindings for the tree view. Then you would have to make it "active" (by clicking on it or a key binding) before using these bindings.
In an editor you would try to keep the focus on the editor tab. But with more global key bindings you get more chances for conflicts and you have to remember them all.
So it might be good to manage activeness.

That said, I still don't see why we need an active pane. If docked tools also live in tabs, then the active tab should be sufficient and much easier to understand and manage by the user than a hierarchical structure with several nested active containers.

But as I said before, commands like switching tabs in the active pane or similar have to be removed then. Otherwise, if they exist, you need a way to communicate which pane is active.

**Comment by simurai** [comment] 2017-04-26 01:18
> @matthewwithanm "Activeness" is a contextual concept, not a global one. Like, at any point in time there are multiple active items and when we talk about the active item what we really mean is "the active pane's active item."

Yeah, using `pane.active` was more a hack/workaround for "which is the pane that contains the focus?". It kinda worked except when the focus moved away from all panes. Editors currently add `editor.is-focused`. Would be great if `.is-focused` can also be added to a parent element. Ideally to `.pane.is-focused`.

![screen shot 2017-04-26 at 8 57 29 am](https://cloud.githubusercontent.com/assets/378023/25413916/f88f7af4-2a68-11e7-9d4f-993621700a9d.png)


> hg42 The main concern for the user is to know where his key bindings will go to.

Yes, exactly. You can tell by the cursor, but its position always changes and sometimes the cursor might also be scrolled out of sight. Having a visual clue that is more permanent would be helpful.

**Comment by nathansobo** [comment] 2017-05-01 16:51
We should add the `is-focused` class to the currently focused pane element. I'll happily review a PR that adds this. Just ping me.

**Comment by simurai** [comment] 2017-05-15 03:01
Good news! :raised_hands:

In Chrome `60` a `:focus-within` pseudo class will get introduced, see this [article](http://www.scottohara.me/blog/2017/05/14/focus-within.html) for details. Then it _should_ be possible to use something like:

```less
.pane:focus-within .tab {
  // style tab to add a is "focused" clue 
}
```

Bad news. Chrome `60` is still a few versions away. Currently Electron is at `56`.

**Comment by nathansobo** [comment] 2017-05-15 20:20
That's gonna be a super useful psuedo-selector in a bunch of ways.

**Comment by simurai** [comment] 2018-05-16 02:20
`:focus-within` seems now (Atom `1.28`) to work. Probably part of the Electron 2.0 update. 🎉

**Closed** 2018-11-02 01:30 UTC
Labels: triaged
