### ISSUE TITLE
When pressing AltGR+] on fr keyboard on windows, the keybinding Ctrl+alt+] is called

### ISSUE THREAD

**Issue by adrien59cadri** [atom/atom#5290] opened 2015-01-28 10:59 UTC
In order to write ']', I need on my french keyboard to type AltGr+° because the ] is made like that.
But this triggers the folding action Alt+Ctr+]...

this is really annoying I can't type] except if I remove the keybinding

**Comment by adrien59cadri** [comment] 2015-01-28 11:01
Sorry it calls the ctrl + Alt + [ shortcut for a strange reason

**Comment by KeitIG** [comment] 2015-01-28 11:14
`ctrl + Alt + [` nor ']' does not trigger anything in Atom for me. Have you installed an extension using this keybinding ?

**Comment by lee-dohm** [comment] 2015-01-28 12:42
This is a duplicate of atom/atom-keymap#35. Please subscribe there for updates.

**Closed by lee-dohm** 2015-01-28 12:42 UTC
