### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by romfrolov** [atom/atom#20514] opened 2020-03-14 19:01 UTC
This error occurred after I updated one module (I believe it was linter, but I'm not sure).

Steps to reproduce:
1. Click on the left bar (projects bar).

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: macOS version 10.15.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ELECTRON_ASAR.js:166

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688158)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744622)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744724)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2744850)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087821)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1246932)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1244917)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284329)
```

### Commands

```
  5x -0:53.2.0 application:add-project-folder (div.tool-panel.tree-view)
```

### Non-Core Packages

```
busy-signal 2.0.1 
docblockr 0.13.7 
git-plus 8.7.1 
intentions 1.1.5 
language-ethereum 0.3.9 
language-graphql 1.0.0 
language-kotlin 0.5.0 
language-pgsql 0.2.3 
language-rust 0.4.12 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
todo-show 2.3.2 
```

**Comment by sadick254** [comment] 2020-09-01 16:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-01 16:20 UTC
