### ISSUE TITLE
Atom launcher showing browser windows

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [atom/atom#21385] opened 2020-09-25 10:11 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

A

1. Right click atom launcher
2. Click "All windows"

B

1. Right click atom launcher
2. Click "New window"

**Expected behavior:**

A. Only seeing atom windows in unity atom launcher.
B. Seeing atom launch with an empty window.

**Actual behavior:**

A. Seeing browser tabs in atom launcher
B. Atom launches into 2 tabs, one labelled ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false on the left and one labelled 'atom' (/usr/bin) next to it.

**Reproduces how often:**

### Versions

1.51.0 x64, running on Ubuntu 20.04.
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.51.0
python 3.8.2
git 2.25.1

### Additional Information

Browser is firefox. Closing browser and all atom windows resolves (A) but not (B).

**Comment by darangi** [comment] 2020-10-15 09:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20997. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2020-10-15 09:16 UTC
