### ISSUE TITLE
Uncaught TypeError: Cannot read property 'priority' of undefined

### ISSUE THREAD

**Issue by tignashchenko** [atom/atom#15883] opened 2017-10-13 04:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'priority' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:55

TypeError: Cannot read property 'priority' of undefined
    at StatusBarView.module.exports.StatusBarView.addLeftTile (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:55:136)
    at ImageEditorStatusView.attach (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor-status-view.js:57:49)
    at new ImageEditorStatusView (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/image-editor-status-view.js:47:16)
    at Object.attachImageEditorStatusView (/Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/main.js:50:39)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/image-view/lib/main.js:23:30
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:339:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:492:27)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:715:25)
```

### Commands

```
     -1:19.2.0 editor:newline (input.hidden-input)
     -1:17.8.0 autocomplete-plus:confirm (input.hidden-input)
     -1:17.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:15.5.0 editor:newline (input.hidden-input)
     -1:11.1.0 core:move-down (input.hidden-input)
     -1:10.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:10.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:09.4.0 editor:newline (input.hidden-input)
  2x -1:08.6.0 core:backspace (input.hidden-input)
     -1:07.4.0 editor:newline (input.hidden-input)
     -1:03.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:03.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:57.3.0 editor:newline (input.hidden-input)
     -0:55.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:55.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:53.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.30.5 
atom-runner 2.7.1 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-modules 1.7.2 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.13 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-docker 1.1.8 
linter 2.2.0 
linter-eslint 8.3.2 
linter-flow 5.6.1 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
motepair 0.24.0 
node-debugger 1.10.1 
open-in-browsers 0.0.30 
platformio-ide-terminal 2.7.0 
prettier-atom 0.40.0 
react 0.16.2 
react-redux-snippets 0.1.6 
react-snippets 1.0.0 
```

**Comment by rsese** [comment] 2017-10-13 05:05
Thanks for the report! Can you re-open this in https://github.com/atom/status-bar/issues/190 so we have it in the right place?  If you can share any details about what you were doing at the tie of the error, that would be super helpful too.

x-refs: https://github.com/atom/status-bar/issues/109, https://github.com/atom/status-bar/issues/190.  I think this might be a duplicate of https://github.com/atom/status-bar/issues/190 but that one has some formatting trouble (I can close that in favor of your issue @tignashchenko).

**Closed by rsese** 2017-10-13 05:05 UTC
