### ISSUE TITLE
IDEA: Synchronized user Accounts

### ISSUE THREAD

**Issue by calvinomiguel** [atom/atom#17164] opened 2018-04-18 12:07 UTC
Hello everyone,

I'm a webdesign, webdevelopment student in Switzerland and I started using Atom prior to Brackets. Atom is great in many ways, but I was wondering if it is possible to add a feature I sincerly think would be of great value to me and other developers as well. 

**The Issue**
I use Atom at school, at home and at work, subsequently I don't always have the same device meaning that I have various instances of Atom installed across multiple devices. Sometimes I need to change my settings or I find a new plugin, and everytime I do that, because I have Atom installed in multiple places, I need to manually change the settings or install each of the plugins on each device again. 

**Solution**
For that reason I think I'd be great if there could be a something like an optional github login or a plugin that offers a login and  stores all of the settings and plugins we use. So if I login in, while being in another device, all my settings and plugins get automatically restored.

I hope there is anyone relating with my struggle. Thanks for your reply.

**Comment by rsese** [comment] 2018-04-18 20:03
Thanks for contributing!

I'm going to close as a duplicate of https://github.com/atom/atom/issues/3572 and you can subscribe there for updates if you'd like.

There have also been other discussions about this on the official message board, for example:

https://discuss.atom.io/t/syncing-settings-packages-between-machines/1385/

And here are a couple of packages that you might find useful:

https://atom.io/packages/sync-settings
https://atom.io/packages/package-sync

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-18 20:03 UTC
