### ISSUE TITLE
Uncaught Error: spawn /Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gy...

### ISSUE THREAD

**Issue by adantra** [atom/atom#10779] opened 2016-02-11 22:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.2
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Users/adantra/Library/Application Support/com.github.atom.ShipIt/update.gyQJTo7/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "editor": {
    "fontSize": 21
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joshaber** [comment] 2016-02-11 22:23
@adantra Any idea how you launched Atom when you got this?

This is a duplicate of #9559, so I'm gonna close it out.

**Closed by joshaber** 2016-02-11 22:23 UTC
Labels: duplicate

**Comment by demhydraz** [comment] 2016-02-11 22:36
@joshaber This seems to be a common issue, do we still not have a clue how it's happening?

**Comment by adantra** [comment] 2016-02-12 00:20
I launched atom from the github desktop application on my Mac

**Comment by joshaber** [comment] 2016-02-12 01:36
@adantra Thanks!

@demhydraz I spent a lot of today working on a theory. The tl;dr version is that when the app is launched using LaunchServices (e.g., when it's launched by GitHub Desktop, or by opening a file for which Atom is the handler, etc.), LaunchServices sometimes decides to open a copy of Atom which was downloaded as an update, instead of opening the copy of Atom the user actually uses. Then, when the update is installed, it deletes the already-open Atom out from under itself.

**Comment by demhydraz** [comment] 2016-02-12 01:41
That's..that's weird. Why would LaunchServices do that?

**Comment by joshaber** [comment] 2016-02-12 01:44
A good question, but it's not the first time LaunchServices has been confused about us: https://github.com/atom/atom/issues/1720
