### ISSUE TITLE
[Linux] Atom crashes when dragging files over the UI

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#9375] opened 2015-10-31 19:43 UTC
Atom will crash every time a file is dragged (just dragged, not dropped) over to the UI.
This happens nearly 100% of the time (maybe 17 out of every 20 tries) on a Linux x64 Debian testing.

Running atom from console outputs this:

```
[5004:1031/204027:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[5004:1031/204027:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
[5004:1031/204028:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[5004:1031/204028:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[5004:1031/204028:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[5004:1031/204028:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[5042:1031/204028:INFO:renderer_main.cc(200)] Renderer process started
App load time: 458ms
[5042:1031/204028:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
[5004:1031/204029:INFO:CONSOLE(719)] "Failed to require the main module of 'terminal-plus' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.", source: /usr/share/atom/resources/app.asar/src/package.js (719)
[5004:1031/204030:INFO:CONSOLE(133)] "Loading Emmet extensions from", source: /home/alexandernst/.atom/packages/emmet/lib/emmet.coffee (133)
[5004:1031/204030:INFO:CONSOLE(150)] "Emmet: no such extension folder:", source: /home/alexandernst/.atom/packages/emmet/lib/emmet.coffee (150)
[5004:1031/204030:INFO:CONSOLE(719)] "Failed to require the main module of 'terminal-plus' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.", source: /usr/share/atom/resources/app.asar/src/package.js (719)
[5004:1031/204030:INFO:CONSOLE(46)] "Window load time: 2423ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (46)
[5004:1031/204031:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[5004:1031/204031:ERROR:accelerator_util.cc(91)] The accelerator string can only contain ASCII characters
[5004:1031/204032:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[5004:1031/204032:ERROR:accelerator_util.cc(91)] The accelerator string can only contain ASCII characters
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 534 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

```

**Comment by alexandernst** [comment] 2015-10-31 23:43
Btw, this also happens with 1.2 beta

**Comment by alexandernst** [comment] 2015-11-01 10:14
I was wrong, this doesn't happen with 1.2 beta.

**Comment by izuzak** [comment] 2015-11-01 17:07
@alexandernst If you can reproduce this on stable, but can't reproduce on beta, then that implies we can close this since it will be fixed as soon as beta is merged into stable on the next release. If I misunderstood, let us know and provide more information.

**Closed by izuzak** 2015-11-01 17:07 UTC
