### ISSUE TITLE
Uncaught Error: Patch does not apply

### ISSUE THREAD

**Issue by jaymjax1** [atom/atom#15827] opened 2017-10-05 20:49 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Patch does not apply

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:68

Error: Patch does not apply
    at exports.patchFromChanges (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:68:17)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1665:68)
    at later (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
  2x -9:45.1.0 core:backspace (input.hidden-input)
  2x -9:43.9.0 core:save (input.hidden-input)
 83x -0:21.7.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.8 
react 0.16.2 
```

**Comment by Ben3eeE** [comment] 2017-10-05 20:55
Thanks for the report! 

Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by jaymjax1** [comment] 2017-10-05 20:58
Hi!

- At the time of the error I was doing a mass ‘ Command + Z’ to undo some changes
- I’m unable to reproduce the error
- N/A

I was prompted to automatically submit the ticket

**Comment by Ben3eeE** [comment] 2017-10-05 21:01
Thank you for the additional information 🙇

**Comment by nathansobo** [comment] 2017-10-05 21:06
@as-cii @jasonrudolph This looks like it could be related to our changes to support custom history providers.

**Comment by nathansobo** [comment] 2017-10-05 21:20
Okay, from my initial investigation it looks like we're attempting an invalid splice into the patch, possibly because the deleted text we're passing is inconsistent with existing changes the splice overlaps. It's strange because `changesSinceLastDidStopChangingTextEvent` array should just accumulate successive changes, and so long as they're sequential these changes should compose cleanly.

**Comment by as-cii** [comment] 2017-10-09 09:00
Thanks for the report, @jaymjax1! ⚡️ We think we may have addressed this as part of https://github.com/atom/text-buffer/pull/266, which will be released in the next stable and beta hotfixes.

I am going to close this for now, but we should re-open it in case the bug can still be reproduced after the new versions are published.

**Comment by mazhigbee** [comment] 2017-11-09 15:59
I just go an error that states the same thing and the error message brought me here. Not sure what information you might want, but at the time of the error I had copy and pasted some code, then went to delete some characters from the middle of a line and the error appeared. 

Atom on Windows_x64: 1.22.0 ia32 

C:\Users\*user*\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\helpers.js:68
Hide Stack Trace
Error: Patch does not apply
    at exports.patchFromChanges (C:\Users\*user*\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\helpers.js:68:17)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (C:\Users\*user*\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1692:68)
    at later (C:\Users\*user*\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\helpers.js:28:13)

**Comment by tellkonkle** [comment] 2017-11-09 23:37
Started coming up for me while I was typing a ternary operator in PHP...

```
Uncaught Error: Patch does not apply

Error: Patch does not apply
    at exports.patchFromChanges (C:\Users\{...}\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\helpers.js:68:17)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (C:\Users\{...}\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1692:68)
    at later (C:\Users\{...}\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\helpers.js:28:13)
```

**Comment by as-cii** [comment] 2017-11-10 09:29
@maxbrunsfeld @nathansobo: did anything change in 1.22 that could have caused this behavior to regress again?

**Comment by nathansobo** [comment] 2017-11-10 15:34
I was about to ask you the same thing. We're going to need to look at collected stack traces. We should probably reopen this.

**Comment by Ryukis** [comment] 2017-11-11 11:16
I had it while typing anything (String, or code do the same)

**Comment by FurrukhJamal** [comment] 2017-11-13 10:15
I also had an error and it brought me here.
I was writing a prepare statement for PDO php

C:\Users\furrukh\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\helpers.js:68
Hide Stack Trace
Error: Patch does not apply
    at exports.patchFromChanges (C:\Users\furrukh\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\helpers.js:68:17)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (C:\Users\furrukh\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1692:68)
    at later (C:\Users\furrukh\AppData\Local\atom\app-1.22.0\resources\app\node_modules\text-buffer\lib\helpers.js:28:13)

**Comment by maxbrunsfeld** [comment] 2017-11-13 17:22
Could everyone who is seeing this report the list of packages that they are using?

**Comment by pigion138138** [comment] 2017-11-14 19:01
activate-power-mode@2.6.0
atom-beautify@0.30.6
autoclose-html@0.23.0
block-comment-plus@0.5.1
build@0.69.0
busy-signal@1.4.3
color-picker@2.2.5
console-log@1.10.0
dark-flat-ui@1.2.4
docblockr@0.12.3
draw-centered@1.0.6
emmet@2.4.3
file-icons@2.1.13
fonts@3.0.3
keyboard-sounds@0.2.0
kyle-dark-syntax@0.0.0
minimap@4.29.7
remember-folds@0.3.0
Remote-FTP@1.3.1
slim-dark-ui@0.12.0
textual-velocity@0.16.0
todo-show@2.1.0
wakatime@7.0.3

**Comment by RichFlavell** [comment] 2017-11-16 16:23
angular-bootstrap@1.0.1
angularjs@0.4.0
atom-beautify@0.30.6
atom-prettify@0.1.3
autoclose-html@0.23.0
highlight-selected@0.13.1
language-javascript-jsx@0.3.7
pretty-json@1.6.4

Uncaught Error: Patch does not apply
`C:\Users\rich\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\helpers.js:68`

```
Error: Patch does not apply
    at exports.patchFromChanges (C:\Users\rich\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\helpers.js:68:17)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (C:\Users\rich\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:1692:68)
    at later (C:\Users\rich\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\helpers.js:28:13)
```

**Comment by maxbrunsfeld** [comment] 2017-11-16 16:54
Hmm, I noticed that both of you have `autoclose-html` installed. I'm going to try installing that in order to reproduce this.

**Comment by Nerdzoskie** [comment] 2017-11-16 18:27
I don't use any packages and I have the same Uncaught Error ..

**Comment by 50Wliu** [comment] 2017-11-16 18:29
@Nerdzoskie some questions for you: what were you doing when you encountered this error?  And what is the output of `apm list --installed`?

**Comment by Nerdzoskie** [comment] 2017-11-16 18:48
I was editing two files without saving one of them when this error happened. 
The output of _apm list --installed_ is "empty".

**Comment by Daotaku** [comment] 2017-11-17 07:06
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Patch does not apply

```
At C:\Users\xx\AppData\Local\atom\app-1.22.1\resources\app\node_modules\text-buffer\lib\helpers.js:68

Error: Patch does not apply
    at exports.patchFromChanges (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/helpers.js:68:17)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1692:68)
    at later (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -4:02.6.0 core:backspace (input.hidden-input)
  4x -4:01.5.0 core:save (input.hidden-input)
     -2:53.2.0 tree-view:remove (span.name.icon.icon-file-text)
     -2:44.5.0 core:move-right (input.hidden-input)
     -2:42.5.0 core:save (input.hidden-input)
 27x -2:41.9.0 core:move-down (input.hidden-input)
 11x -2:40.2.0 core:move-up (input.hidden-input)
     -1:17.2.0 core:move-left (input.hidden-input)
     -1:04.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-html-preview 0.2.2 
atom-monokai 0.10.8 
atom-nodejs-snippets 2.0.0 
atom-sublime-monokai-syntax 0.4.0 
atom-ubuntu-dark-ui 0.37.0 
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
emmet 2.4.3 
git-plus 7.10.0 
git-time-machine 1.5.9 
jquery-snippets 11.0.0 
linter 1.11.18 
linter-php 1.5.1 
monokai 0.19.0 
monokai-ubuntu 0.9.0 
php-cs-fixer 4.1.1 
save-workspace 0.4.0 
sync-settings 0.8.3 
```

I don't know what cause it, but it only happened sometimes... seems like closing and opening it again fix the problem? memory leaks?

**Comment by maxbrunsfeld** [comment] 2017-11-17 19:40
@Ben3eeE I'm having a really hard time reproducing this. Could you take another :eyes: at it when you get a chance?

**Comment by Foggalong** [comment] 2017-11-18 11:37
I just had the same error come when editing a TeX file and was trying to undo a change where I accidentally added a ` \\` to the end of every line in the ~1000 line file rather than just in the selection. The error then appeared every time I tried to undo.

Thankfully I'd not saved the file so could just close and reload. After that the error went away.

**Comment by tobinfekkes** [comment] 2017-11-18 19:01
This just started happening for me today. If it helps debugging at all, it only occurs after typing the third character for me.
![image](https://user-images.githubusercontent.com/6226162/32983787-46f56108-cc4f-11e7-8a86-d4acf4b48229.png)

**Comment by pigion138138** [comment] 2017-11-18 19:04
I'm not sure if this will help anyone or not but since updating all of my packages I haven't seen the error.

**Comment by mikael1000** [comment] 2017-11-21 09:05
I just got this when working in a Laravel project. Was writing a function to have one-to-many relationship in my database. When it started it didn't matter what or where I wrote I got error every second-third keystroke I made. I restarted the editor and now for some minutes it has been working.
**But what does the error mean and is it just to restart and continue working?**

The only enabled dl packages I have is:
-> color-picker 2.2.5
-> simple-drag-drop-text 0.3.6
-> laravel 0.7.1

I have a lot more installed packages but they are disabled. Are they important to list. If so how can I generate a list in Atom that is easy to copy paste in here?

**Comment by andrinheusser** [comment] 2017-11-24 15:40
After opening a file, the error comes up after the third input of an alphanumeric character. After that, an additional error comes up for every non-space character. A space character seems to "reset" the counter, so I can type two non-space characters before I get another error. 
However, space characters after three `:` generate errors.

Atom 1.22.1 ia32

```
├── advanced-open-file@0.16.7
├── aesthetic-ui@4.0.0
├── an-old-hope-syntax@1.0.4
├── api-docs@0.0.6
├── atom-autocomplete-php@0.25.6
├── autocomplete-php@0.3.7 (disabled)
├── block-cursor@0.13.2 (disabled)
├── busy-signal@1.4.3
├── docker@0.8.0
├── editorconfig@2.2.2
├── incremental-search@5.2.2
├── intentions@1.1.5
├── jumpy@4.1.1
├── language-docker@1.1.8
├── language-vue@0.23.1
├── linter@2.2.0
├── linter-php@1.5.1
├── linter-ui-default@1.6.10
├── maximize-panes@0.2.0
├── move-panes@0.2.0
├── nucleus-dark-ui@0.12.3
├── Stylus@3.1.1
└── zentabs@0.8.9
```

**Comment by Ben3eeE** [comment] 2017-11-24 23:36
@andrinheusser @tobinfekkes  if you clear window state does the error still appear after opening files and typing the third character? http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

---

@mikael1000  
> But what does the error mean and is it just to restart and continue working?

You should close Atom and start it again before you continue to work after encountering this error.

> I have a lot more installed packages but they are disabled. Are they important to list. If so how can I generate a list in Atom that is easy to copy paste in here?

Only installed and enabled packages really. If you are unsure you can use `apm list --installed`. I really appreciate the list you provided though. Can you share some information about the edits you made? Like did you drag and drop text, use any snippets? Thank you 🙇 

---

@Foggalong Can you share any information about how you added `\\` to every line?

**Comment by mikael1000** [comment] 2017-12-04 20:46
@Ben3eeE 
I was writing a function in an controller file in my Laravel-project. When the error showed I wrote the connection between Mysql-db-tables (hasMany()-stuff).
Did not use any extensions or did not drag and drop anything. The only thing I can think of that could have been in play when I wrote that is the package:
-> laravel 0.7.1

**Comment by NaveenDA** [comment] 2017-12-09 11:48
In my case, this has happened only when the internet is OFF then ON.

**Comment by taketakeyyy** [comment] 2017-12-12 05:53
It may not be very helpful, but I report it because this symptom has been fixed.

I encounterd the same symptom of @tobinfekkes (occurs after typing the third (or more) consecutive non-space characte).

Atom: 1.22.1 ia32
OS: Microsoft Windows 7

...and, I also use Remote-FTP(I forgot the version). I saw "Available Updates" in Settings, then Remote-FTP was displayed only. So I updated the package (to ver.2.1.1) and restart Atom. Then this symptom was fixed.

**Comment by Ben3eeE** [comment] 2018-01-03 00:42
Thanks everyone for their answers in this issue. It was really helpful 🙇 

Gif of repro in Atom 1.23-beta:

![patch_does_not_apply](https://user-images.githubusercontent.com/1058982/34505502-a860cff0-f025-11e7-9393-89c68285a744.gif)

This is using the `parinfer` package and pressing `a`, `core:undo`, `core:undo` and `core:delete` repeatedly. Unfortunately I don't currently have a gif in a newer version of Atom or one that shows something like keybinding-resolver. It was not easy to reproduce using these steps, maybe showing `fuzzy-finder` that is performed in the gif is important or related? I haven't had time to narrow it down.

The single untitled tab just has the word `aaardvark`.

Pretty sure that this setting is related:
![image_720](https://user-images.githubusercontent.com/1058982/34505621-659c3988-f026-11e7-9d80-9f0dd78f4a9c.png)


/cc: @ungb to help narrow repro down

**Comment by sompylasar** [comment] 2018-01-03 00:59
This happens when a plugin modifies the editor text outside of "the normal flow" (keystrokes), probably disabling the undo for these operations, and then the user tries to apply an undo.

I am regularly hitting this with my plugin https://atom.io/packages/atom-cursor-indent which adds whitespace (indent) in front of empty lines when the input cursor moves to them.

**Comment by maxbrunsfeld** [comment] 2018-01-03 01:07
Yeah, I think it's very likely that the problem comes from calling `setTextInRange` with the `{undo: 'skip'}` option. That option is no longer used by Atom core, and it has never had a very well-though-through behavior, so it's likely that we've overlooked it in some recent change.

I will look into this bug soon. In the meantime, you may be able to avoid using `{undo: 'skip'}` by instead using the [`createCheckpoint`](https://atom.io/docs/api/v1.23.1/TextBuffer#instance-createCheckpoint) and [`groupChangesSinceCheckpoint`](https://atom.io/docs/api/v1.23.1/TextBuffer#instance-groupChangesSinceCheckpoint) APIs.

**Comment by sompylasar** [comment] 2018-01-03 01:28
@maxbrunsfeld I was using `createCheckpoint `/`groupChangesSinceCheckpoint` before. My plugin functionality requires skipping undo, otherwise unnecessary undo history items are created: https://github.com/sompylasar/atom-cursor-indent/issues/1

Maybe we could discuss how this functionality can be implemented differently, or how we can add this functionality into Atom core, with proper handling of virtual characters?

**Comment by maxbrunsfeld** [comment] 2018-01-03 01:47
Yeah, I haven't looked at your package in detail. We should be able to just fix the bug in `{undo: 'skip'}`.

**Closed** 2018-01-03 20:19 UTC
Labels: needs-reproduction, uncaught-exception

**Comment by maxbrunsfeld** [comment] 2018-01-03 21:53
Ok, we have redesigned the way that we handle the `{undo: 'skip'}` option. It no longer has the ability to get the history into an inconsistent state. The fix will go out with Atom 1.25 next month. In the meantime, you can try the new code by downloading a bleeding-edge build of Atom from [here (macOS)](https://6449-3228505-gh.circle-artifacts.com/0/Users/distiller/atom/out/atom-mac.zip).

**Comment by Ben3eeE** [comment] 2018-05-04 19:09
@Kryten0807 You can easily check if it's a community package causing the issues by launching Atom in safe mode by using `atom --safe`.

Also since you are on Linux: Did you install Atom from the official repositories? See https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt

If you can narrow down it down with steps to reproduce can you please open a new issue? It's easier for us to track if it's in a new issue, thank you 🙇

**Comment by alissonpelizaro** [comment] 2018-09-17 19:13
It looks like this was resolved after the last update. This error was no longer displayed here.

Tks for all support
