### ISSUE TITLE
Windows 10 x64 can not move file to trash

### ISSUE THREAD

**Issue by yassersharaf** [atom/atom#11934] opened 2016-06-08 12:18 UTC
Atom version 1.8 on Windows 10 x64 "The following file couldn't be moved to trash" while deleting a file from tree view

**Comment by tjgerot** [comment] 2016-06-08 13:00
I have experienced that same issue on multiple computers running Windows 10

**Comment by Ben3eeE** [comment] 2016-06-08 13:31
Are you deleting from a virtual or network drive or with the recycle bin disabled? Then this is a duplicate of https://github.com/atom/tree-view/issues/856

**Comment by 50Wliu** [comment] 2016-06-08 13:43
Closing in favor of atom/tree-view#856.

**Closed by 50Wliu** 2016-06-08 13:43 UTC

**Comment by yassersharaf** [comment] 2016-06-08 14:03
Recycle bin is enabled and i'm deleting project files from D:\XAMPP\htdocs folder
what is the correct answer please?
