### ISSUE TITLE
Associating Atom with (text) files on Windows is very difficult

### ISSUE THREAD

**Issue by bilderbuchi** [atom/atom#6734] opened 2015-05-11 10:21 UTC
I want to open all my text files with Atom, but I couldn't find a good way to do that, that's not breaking with every Atom update, and I don't get Atom icons.

Did I do something wrong? Is there a way to make the existing "Open with Atom" right-click menu entry "stick"? 
Please tell me there's a more streamlined way to achieve correct file associations on Windows!

Expected behaviour:
Either Atom offers on installation to associate with files typically edited with a text editor, or offers a setting where you can do that post-installation. 
Failing that, the user is given a clear method of associating desired file types with Atom, e.g. using the "open with" dialog like other editors allow.

Observed behaviour:

1. Atom is not associated with any files, and there's no setting to change that. There is a context menu entry, but that requires constant right-clicking for every file you want to open in Atom, so is not really desirable.

2. OK, so I thought I'd manually change the "open With" choice for every file type to a new default setting. (Right click a txt file - open with - set new default application) 
Puzzlingly, Atom is not in the list of proposed applications. O_o

3. Nevermind, let's hit "further applications" and select from there. Huh, Atom is not in C:\Program Files, either, so that didn't work.

4. OK, then let's select the installed desktop link (or start menu entry). Hooray, I could select it. Oh, it just flickers a terminal at you for a split second. Turns out, this just calls some update.exe, and something gets messed up (probably command args?).

5. After some googling, I found out that Atom gets installed in AppData somewhere, so let's search the exe there. Erm, the exe is in a version-specific folder, so I'd have to re-associate all my file bindings after every update. No, thank you :-(

6. the cmd file in the bin directory is an option, but to select that you have to
 * go to the location in a separate Explorer window (to display hidden items to be able to see AppData, which you can't do in the file selection dialog)
 * copy the path to bin
 * navigate the open with dialog until you get to the point where you can select arbitrary files
 * paste the path
 * select atom.cmd

7. Hooray, now I can open files with Atom all the time, but:
 * I got no way to select the Atom icon, I got an empty white rectangle.
 * It flickers the terminal for a split second, which interestingly does not happen when starting atom via the start menu. Annoying, but not vital.
 * It says "atom.cmd" in the relevant dialogs/menus, which is not exactly beautiful/elegant.
 * I can't imagine a normal user to go through this dance to do this, compared to the experience in other editors like Notepad++.

Versions: Windows 8.1, Atom 198; dialog strings translated from German, so may not be identical to an english windows.

**Comment by 50Wliu** [comment] 2015-05-11 11:58
Duplicate of #4893, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-11 11:58 UTC

**Comment by bilderbuchi** [comment] 2015-05-11 12:48
ups, sorry for that. I searched the tracker, but didn't find that other issue (probably because it doesn't use "associate").

**Comment by 50Wliu** [comment] 2015-05-11 13:27
No worries :)
I had some trouble finding it too at first (I knew it existed, but forgot what keywords it included).

**Comment by ShaneGowland** [comment] 2015-12-15 05:24
This problem annoyed me too so I put together this little solution. https://shanegowland.com/tech/2015/atom-editor-open-with-assistant-for-windows/

**Comment by onetrev** [comment] 2015-12-17 05:19
This is awesome Shane! Blow my mind a year later after issue was reported all Windows users are having to right click and open files with Atom. It's starting to wear thin for sure, so this is a great stop gap.

**Comment by mochadwi** [comment] 2016-01-07 10:42
Thank you very much :)

**Comment by htlf** [comment] 2017-01-29 18:20
I have no trouble doing just that on windows10! maybe a fix has been released in the meanwhile...
