### ISSUE TITLE
Syntax parsing long lines in files causes Atom to lockup "not responding"

### ISSUE THREAD

**Issue by crucialfelix** [atom/atom#7444] opened 2015-06-26 08:46 UTC
Opening this file:  https://github.com/espadrine/aulx/blob/master/html/tokenizer.js

Causes the parser to choke and Atom warns several times about not responding. Eventually you have to give up and quit the whole app.

The exact line that is doing it is this: https://github.com/espadrine/aulx/blob/master/html/tokenizer.js#L63

If I remove the line there is no problem.

I notice that when opening the file in Sublime 3 they don't syntax colorize that line at all. For any really long line they just skip it.

Probably related issues: 
https://github.com/atom/atom/issues/6830
https://github.com/atom/atom/issues/5882

The issue was reported by this guy: https://news.ycombinator.com/item?id=9782812

**Comment by izuzak** [comment] 2015-06-26 08:55
I believe this is a duplicate of https://github.com/atom/atom/issues/979.

**Closed by izuzak** 2015-06-26 08:55 UTC

**Comment by crucialfelix** [comment] 2015-06-26 09:14
yep, that one is comprehensive. thanks !

**Comment by shamrin** [comment] 2015-10-10 20:36
I've just opened [tokenizer.js][1] in Atom 1.0.19. It works fine now. The long line no longer locks up Atom.

[1]: https://github.com/espadrine/aulx/blob/b745723680f541353ad5090da16f4f18bc6ecbc0/html/tokenizer.js#L634
