### ISSUE TITLE
Atom Hangs Too Much and at most time shows message box of "KEEP WAITING"...

### ISSUE THREAD

**Issue by Aakash30Sethiya** [atom/atom#12777] opened 2016-09-26 07:24 UTC
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

[Description of the bug or feature]
### Steps to Reproduce
1. [Open Atom]
2. [sometime open properly and sometime hangs and shows message keep waiting]
3. [click on any option]
   4.[Sometime perform proper action and sometimes hangs and shows message keep waiting]

**Expected behavior:** [works without hang and not shows the message keep waiting]

**Actual behavior:** [works without hang and not shows the message keep waiting]
### Versions 1.9.4

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by thomasjo** [comment] 2016-09-26 08:15
You are going to have to provide much more detail than this. There is almost zero information in this bug report, and as such it is not actionable — there is nothing we can attempt to reproduce and that means there's no way we can magically resolve your issue.

Start by carefully filling out the issue with as much detail as possible, and actually take the time to read the template. In particular make sure you read and understand ["How Do I Submit A (Good) Bug Report?"](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report).

Unless my comment is not addressed within a reasonable amount of time, this issue will be closed to manage [the deluge of issues](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

**Comment by Ben3eeE** [comment] 2016-09-26 08:25
Also since you can't reproduce the problem in safe mode that indicates that the problem might be in one of your installed community packages. Try disabling packages in the `settings-view` until the problem disappears and open an issue on that repository. Some people have reported success using the [package-cop](https://atom.io/packages/package-cop) package to find problematic packages.

**Comment by tenaciousRas** [comment] 2016-09-26 18:30
-1.  I'm not keen on the practice of referring users to a wiki page when they encounter unusably slow performance.

**Comment by 50Wliu** [comment] 2016-12-15 15:46
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12777#issuecomment-249506727 or https://github.com/atom/atom/issues/12777#issuecomment-249508720. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2016-12-15 15:46 UTC
Labels: more-information-needed
