### ISSUE TITLE
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.

### ISSUE THREAD

**Issue by op9674a** [atom/atom#17401] opened 2018-05-23 21:06 UTC
Getting this error 
"LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810"
when trying to open from mac terminal, cannot open when clicking on icon either.  Running MacOS High Sierra 10.13.14.

**Comment by rsese** [comment] 2018-05-23 22:15
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/3093 so you can subscribe there for updates if you'd like.

There are a few things in the thread that people tried that might help fix things for you (e.g. [reinstall](https://github.com/atom/atom/issues/3093#issuecomment-329958739), [use plain Terminal instead of tmux if you're using tmux](https://github.com/atom/atom/issues/3093#issuecomment-51080159), etc.).

And for future issues, it would be super helpful for us if you fill out the issue template - the information in the template is super helpful for us when triaging issues.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-23 22:15 UTC
