### ISSUE TITLE
Cannot type opening curly quotes on Mac

### ISSUE THREAD

**Issue by devios1** [atom/atom#12796] opened 2016-09-27 23:52 UTC
### Description

Due to (apparently) how the keybinding engine works and the (imo ludicrous) re-mapping of option-[ and option-] to tab-switching (using the option key alone as a command key is a terrible idea on Mac computers), it is impossible to type a ‘ or “ character. Being a text editor, not being able to type a character in the normal way is a pretty big limitation.

Even worse, if you unbind the mentioned keys, nothing happens at all when they are typed.

### Steps to Reproduce

1. Open a new or existing text file.
2. Try to type an opening single or double curly quote (option-] or option-[).

**Expected behavior:**
The expected character should be typed.

**Actual behavior:**
A list of open tabs appears, or if the keys are unmapped, nothing at all happens.

### Versions

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.8.4

Mac OS X El Capitan 10.11.6 (15G1004)

**Comment by Ben3eeE** [comment] 2016-09-28 04:50
Sounds like a duplicate of https://github.com/atom/atom-keymap/issues/35 which will be fixed in Atom 1.12.

**Closed** 2016-09-28 15:27 UTC
