### ISSUE TITLE
Surrounding multiple lines alter original text

### ISSUE THREAD

**Issue by eduardoleal** [atom/atom#8667] opened 2015-09-03 21:52 UTC
I tried to surround some lines with quotes, using multi selectors (one per line), as result atom replaced the content of all lines with the content of last line. 

![untitled](https://cloud.githubusercontent.com/assets/2083506/9671911/bba3253a-526c-11e5-90b2-51c9a74b6ccd.gif)

**Comment by jeancroy** [comment] 2015-09-04 00:53
Is it possible this is a duplicate of https://github.com/atom/atom/issues/6940?

Do you have a keyboard where you need two step to input `'` ?
For example [US international keyboard](https://support.microsoft.com/en-us/kb/97738) need `'+space`to type `'`

Is it possible this happens on a OS other than windows ?

**Comment by eduardoleal** [comment] 2015-09-04 17:23
My keyboard need two step to input ```' ```.
It happens on OSX Yosemite.
I think it's the same problem of #6940.

**Comment by lee-dohm** [comment] 2015-09-05 16:03
I agree that this is a duplicate of #6940. I'm going to close this as a duplicate. Please add any information you have to the original Issue.

Thanks for reporting!

**Closed by lee-dohm** 2015-09-05 16:03 UTC
Labels: bug
