### ISSUE TITLE
File rename issue

### ISSUE THREAD

**Issue by martinlindhe** [atom/atom#3113] opened 2014-07-29 09:07 UTC
With Atom 0.120.0, on OSX (with case insensitive filesystem).

What I did:
First i left-click the file "test.php" in the Atom editor tree view to open it.
Next I right-click the same file and select "Rename".

What happens:
When i rename "test.php" to "Test.php", the opened file tab label does not update, and still says "test.php".
If I now click this file (to open it, it was already open in a tab) - i end up with two tabs, one "test.php", one "Test.php". Due to the case insensitivity of the file system I use, they happen to point to the same file.

What I expected to happen:
The opened file tab label to change to "Test.php" when i renamed the file.

**Comment by mnquintana** [comment] 2015-04-13 20:45
Still an issue on Atom 0.190.0

**Comment by balexand** [comment] 2015-06-11 18:24
This sounds like a duplicate of https://github.com/atom/autosave/issues/9. To those who are seeing this issue, can you please try disabling the `autosave` module and see if that fixes the issue?

**Comment by kevinsawicki** [comment] 2015-07-28 23:46
Closing this optimistically as fixed by https://github.com/atom/autosave/pull/35 please comment if you still see it happening on Atom 1.0.3+.

**Closed by kevinsawicki** 2015-07-28 23:46 UTC
Labels: bug
