### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked, open 'C:\Users\felipe.caputo\Desktop\Salt Atual\Nonet\casos de uso.pdf'

### ISSUE THREAD

**Issue by felipecaputo** [atom/atom#6377] opened 2015-04-14 17:17 UTC
[Enter steps to reproduce below:]

1. Create a new file with markdown syntax
2. Create a table in GitHub Flavored Markdown ex:
|Title1|Title2|
|:||
|Text1|Text2|

3. Export markdown using "markdown-pdf" package 2 to 5 times

PS.: Maybe the problem is on the package, but, since the problem occurr on Atom Core, I've opened it here.

**Atom Version**: 0.190.0
**System**: Windows 7 Professional
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, open 'C:\Users\felipe.caputo\Desktop\Salt Atual\Nonet\casos de uso.pdf'

```
At fs.js:55

Error: EBUSY: resource busy or locked, open 'C:\Users\felipe.caputo\Desktop\Salt Atual\Nonet\casos de uso.pdf'
  at Error (native)

```

### Commands

```
     -6:03.4 editor:newline (atom-text-editor.editor)
  2x -5:45.3 editor:select-to-beginning-of-word (atom-text-editor.editor)
  2x -5:44.1 core:backspace (atom-text-editor.editor)
  2x -5:24.9 editor:newline (atom-text-editor.editor)
     -3:19.1 core:delete (atom-text-editor.editor)
  6x -3:00.4 core:backspace (atom-text-editor.editor)
  2x -1:06.3 core:move-down (atom-text-editor.editor)
     -1:05.7 editor:newline (atom-text-editor.editor)
     -0:59.4 core:backspace (atom-text-editor.editor)
     -0:58.3 core:move-left (atom-text-editor.editor)
     -0:57.3 editor:move-to-end-of-screen-line (atom-text-editor.editor)
  6x -0:40.2 core:backspace (atom-text-editor.editor)
     -0:27.1 core:save (atom-text-editor.editor)
     -0:22.4 command-palette:toggle (atom-text-editor.editor)
     -0:19.4 core:confirm (atom-text-editor.editor.mini)
     -0:19.2 markdown-pdf:convert (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-angularjs, v0.1.2
atom-beautify, v0.24.0
atom-html-preview, v0.1.6
atom-lint, v0.20.1
autoclose-html, v0.15.0
compare-files, v0.4.1
language-pascal, v0.5.0
linter, v0.12.0
markdown-pdf, v1.3.5
read-only-indicator, v0.1.0
symbols-tree-view, v0.9.2
useful-context-menu, v0.2.1

# Dev
No dev packages
```

**Comment by jugglingnutcase** [comment] 2015-04-15 15:01
Looks like this may be a dupe of #4735.

**Comment by 50Wliu** [comment] 2015-04-15 15:50
Thanks @jugglingnutcase!

**Closed by 50Wliu** 2015-04-15 15:50 UTC
