### ISSUE TITLE
Search doesn't find first hit until Enter or Cmd-G is pressed

### ISSUE THREAD

**Issue by devios1337** [atom/atom#7052] opened 2015-06-01 21:35 UTC
This is a very outdated way to do search. Modern editors will show the first hit starting from the current caret position as you type the search. It feels very odd to type something in the search box, wait for it to do something and have nothing happen. I keep thinking this means it can't find any matches in the document, but just to be safe I hit Cmd-G and lo and behold it finds a bunch of matches.

The explicit "go" command is unnecessary when searching a document. Please implement a modern incremental search.

**Comment by benogle** [comment] 2015-06-01 21:48
Can you elaborate? It does not move the cursor until you hit enter, true. But it does find search results as you type, which are outlined. I am inclined to keep the current behavior, and not move the cursor until you tell it to do so with an enter key press or a cmd-g.

**Comment by devios1337** [comment] 2015-06-01 21:59
To be honest I didn't notice that it was highlighting anything as I was typing, but in large files this is moot because what you are looking for may be well off the current visible page anyway. Having the view jump to the current first match just feels natural as the user's current locus of attention is the fact that they are searching for something, and it makes sense that the app be as responsive as possible to that intent.

After all, once the first hit has left the currently visible view, the user actually has no idea if the app has already found what they are looking for. With a responsive incremental search, the user can immediately stop typing the moment the editor finds what they were looking for. With this method, the user is forced to either complete typing the entire search term, or be constantly pressing enter as they are typing. Neither seems an ideal interface to me.

Pressing Esc or cancelling the search would return you to your original position in the document in case you don't find what you are looking for and don't want to get lost from your original position, but other than that I can't really see any reason for *not* changing the view to show the current best match. Can you explain your logic in preferring not to move the cursor/view?

**Comment by mnquintana** [comment] 2015-06-02 18:21
Thanks for the suggestion! This seems like a duplicate of https://github.com/atom/find-and-replace/issues/367, so I'm going to close this in favor of that one to move the discussion there. Please let me know if I'm misunderstanding, though.

**Closed by mnquintana** 2015-06-02 18:21 UTC
Labels: question

**Comment by devios1337** [comment] 2015-06-02 19:04
That suggestion is similar, but sounds like it's asking for incremental search as *another* find option. I'm asking for this to be the normal behavior of Find (no need for a second command). I'll add a comment to that ticket.
