### ISSUE TITLE
Uncaught Error: Tried to unload active package 'busy-signal'

### ISSUE THREAD

**Issue by rastim** [atom/atom#16982] opened 2018-03-19 06:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Tried to unload active package 'busy-signal'

```
At /usr/share/atom/resources/app/src/package-manager.js:630

Error: Tried to unload active package 'busy-signal'
    at PackageManager.unloadPackage (/usr/share/atom/resources/app/src/package-manager.js:630:19)
    at PackageManager.module.exports.PackageManager.unload (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:458:36)
    at PackageManager.module.exports.PackageManager.install (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:468:18)
    at PackageCard.install (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:825:33)
    at HTMLButtonElement.installButtonClickHandler (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:302:22)
```

### Commands

```
  2x -5:53 core:save (input.hidden-input)
  3x -5:17.8.0 core:backspace (input.hidden-input)
     -5:06.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -5:06.9.0 editor:newline (input.hidden-input)
     -5:05.8.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -5:05.8.0 editor:newline (input.hidden-input)
  2x -4:46.8.0 core:move-right (input.hidden-input)
     -4:36.3.0 core:save (input.hidden-input)
  3x -4:24.4.0 autocomplete-plus:activate (input.hidden-input)
     -3:03.1.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -3:01.6.0 core:undo (input.hidden-input)
     -2:15.4.0 core:confirm (input.hidden-input)
     -0:53.2.0 core:paste (input.hidden-input)
     -0:51.2.0 core:backspace (input.hidden-input)
     -0:18.3.0 core:paste (input.hidden-input)
     -0:17 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.2.0 
linter-ui-default 1.7.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
```

**Comment by rsese** [comment] 2018-03-19 20:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #16873 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by rsese** 2018-03-19 20:54 UTC
