### ISSUE TITLE
HTTPS link to documentation incorrectly configured on server side

### ISSUE THREAD

**Issue by DanielGH** [atom/atom#12802] opened 2016-09-28 07:59 UTC
### Description

The Documentation link from the Help menu "https://flight-manual.atom.io/" is not loading on Firefox. It is reported as being incorrectly configured.

Firefox message: "Your connection is not secure. The owner of flight-manual.atom.io has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website."

### Steps to Reproduce

1. Open Help Menu
2. Click Documentation item

**Expected behavior:** Should be directing to HTTP version of light-manual.atom.io

**Actual behavior:** Being directed to https://flight-manual.atom.io/ which seems incorrectly configured.

### Versions
Atom 1.10.2
Firefox 49.0.1

**Comment by Ben3eeE** [comment] 2016-09-28 08:03
Duplicate of https://github.com/atom/atom/issues/12583

**Closed** 2016-09-28 08:04 UTC
