### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by lxholding** [atom/atom#14084] opened 2017-03-29 06:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
 11x -3:47.8.0 core:backspace (input.hidden-input)
     -3:40.3.0 core:confirm (input.hidden-input)
     -3:34.5.0 tree-view:move (li.file.entry.list-item.status-added.selected)
     -3:33.8.0 core:move-right (input.hidden-input)
     -3:32.4.0 core:confirm (input.hidden-input)
     -3:30.4.0 core:paste (input.hidden-input)
     -3:29.6.0 core:save (input.hidden-input)
     -3:21 core:move-down (input.hidden-input)
     -3:20.7.0 docblockr:parse-enter (input.hidden-input)
     -3:20.7.0 editor:newline (input.hidden-input)
     -3:20.5.0 core:paste (input.hidden-input)
     -3:20.1.0 core:save (input.hidden-input)
  9x -2:44.7.0 core:backspace (input.hidden-input)
     -2:32 core:save (input.hidden-input)
     -2:22.6.0 settings-view:open (input.hidden-input)
  6x -1:31.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.6 
atom-ternjs 0.18.2 
autocomplete-modules 1.6.8 
autocomplete-paths 1.0.5 
block-comment 0.4.3 
busy-signal 1.3.0 
code-peek 1.4.18 
color-picker 2.2.5 
docblockr 0.9.4 
emmet 2.4.3 
file-icons 2.1.1 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.10.1 
language-vue 0.21.2 
linter 2.1.2 
linter-htmlhint 1.3.2 
linter-sass-lint 1.7.4 
linter-ui-default 1.2.1 
minimap 4.26.8 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
react 0.16.2 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.1 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by rsese** [comment] 2017-03-29 17:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14008. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-29 17:38 UTC
