### ISSUE TITLE
Ligatures don't work with certain highlighting

### ISSUE THREAD

**Issue by drewcassidy** [atom/atom#13343] opened 2016-11-28 06:51 UTC
### Description

Fira Code ligatures don't render correctly with syntax highlighting

### Steps to Reproduce

1. use the fira-code font (I haven't tested with other fonts with code ligatures)
2. set syntax to C++ (does not happen without highlighting)

**Expected behavior (from iterm2 nightly and `cat`)**
<img width="328" alt="screen shot 2016-11-27 at 10 48 52 pm" src="https://cloud.githubusercontent.com/assets/3837797/20658707/b803ed70-b4f3-11e6-96cc-59b89d9dfff6.png">

**What I get**
<img width="373" alt="screen shot 2016-11-27 at 10 41 30 pm" src="https://cloud.githubusercontent.com/assets/3837797/20658689/82933de4-b4f3-11e6-9635-fcde50224579.png">

### Versions
```
Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
MacOS 10.12.1 (with a retina screen)

**Comment by thomasjo** [comment] 2016-11-28 13:17
This ends up being dependent upon language/grammar. If the grammar doesn't tokenize "correctly", certain ligatures will not work since the characters that make up the ligature are not enclosed in the same HTML element. In your specific example (which looks like C/C++), the second pointer dereference operator is being tokenized as individual elements. First an operator `-` followed by a binary operator `>`. For it to be a valid "arrow", there needs to be a field/member name on the right hand side of the arrow.

Additionally, there is no triple equals construct in C/C++, so that is tokenized as an equality comparison operator `==`, followed by an assignment operator `=`.

The fact these ligatures don't work in this context is expected, since they do not exist in the language specification, in the manner you've used them in your example.
I suspect that if you switch to e.g. the _plain text_ grammar, the ligatures will work as you expect.

I'm closing this as wontfix, since this is working as intended.

**Closed by thomasjo** 2016-11-28 13:17 UTC

**Comment by drewcassidy** [comment] 2016-11-28 17:16
Should I open an issue on the C++ syntax module, since the dereference operator should be tokenized as a single operator?

**Comment by thomasjo** [comment] 2016-11-28 17:22
`a->` is not valid C/C++, but `a->b` is, so that line is not really a bug. But the first line definitely should work though, so yeah, opening an issue for that (unless one already exists) would be great! 🙇
