### ISSUE TITLE
Copy & pasting a file to the same directory will remove the extension

### ISSUE THREAD

**Issue by DuckThom** [atom/atom#8928] opened 2015-09-24 17:29 UTC
If a file is copy/pasted in the Tree View, the extension will be removed.

Examples: 
`./style.min.css` will create `./style0.min`
`./script.min.js` will create `./script.min`
`./index.blade.php` will create `./index0.blade`
`./index.blade.php` copied to another directory is properly created as `../otherdir/index.blade.php`

Files like `index.html` are properly copied to `index0.html`

`atom --safe` doesn't help either.

Mac OS X 10.11
Atom 1.0.16

**Comment by abe33** [comment] 2015-09-24 18:14
Hi @DuckThom, I can confirm this on latest master. It looks like an issue that only occurs for files with many file extensions and only when pasted in the same directory.

However this issue should have been reported in the atom/tree-view repo, so I took the liberty to create one in the right repo and I'll close this one.

**Closed by abe33** 2015-09-24 18:14 UTC
