### ISSUE TITLE
Allow scrollbar to be moved from the edge of screen

### ISSUE THREAD

**Issue by vlad1777d** [atom/atom#16399] opened 2017-12-17 21:28 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When Atom window is maximized, you drag mouse cursor to the right edge of screen, press it and then drag mouse to top or bottom - nothing happened.
To drag scrollbar you need only to aim directly onto it.
In other software you don't need to aim onto scrollbar, you can just move cursor to right edge of screen and drag it. For example, in Firefox, Xed, Gedit, Gnome-Terminal, Chromium, etc.

### Steps to Reproduce

1. Open in Atom text document to be able scrolling it vertically
2. Maximize Atom window.
3. Move cursor to the right edge of screen.
4. Press left mouse button and try dragging scrollbar. Nothing is happened.

**Expected behavior:**
I expect that on "step 4" scrollbar would be dragged.
For 2 matters: 1. Not to force users aiming on Atom's narrow scrollbar; 2. To be consistent with the majority of applications providing such action.

**Actual behavior:**
On "step 4" scrollbar was not dragged.

**Reproduces how often:** 100%

### Versions

OS: Linux Mint 18.3 Cinnamon x64.
(but this behavior is in Mac and Windows too)

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.12
git 2.7.4

### Additional Information

Video with reproducing the issue on YouTube and commentaries in subtitles (please, turn on them): https://youtu.be/GLXMQFgKJOA
Same video, but in .mkv format: [atom_suggestion-2017-12-16_20.37.09 (1).mkv.zip](https://github.com/atom/atom/files/1566103/atom_suggestion-2017-12-16_20.37.09.1.mkv.zip)

**Comment by 50Wliu** [comment] 2017-12-18 01:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #14803. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-12-18 01:13 UTC

**Comment by vlad1777d** [comment] 2017-12-18 21:50
Sorry, I searched through issues, but didn't found that one.

**Comment by 50Wliu** [comment] 2017-12-18 22:14
No problem :).  There are a lot of issues to go through and sometimes it's hard to find the correct combination of keywords.
