### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/vswamy/Library/Application Suppo...

### ISSUE THREAD

**Issue by vswamy** [atom/atom#9762] opened 2015-11-23 16:23 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/vswamy/Library/Application Support/com.github.atom.ShipIt/update.Y1ly8pA'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/vswamy/Library/Application Support/com.github.atom.ShipIt/update.Y1ly8pA'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/vswamy/Library/Application Support/com.github.atom.ShipIt/update.Y1ly8pA/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
     -0:30.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:25.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:21.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:21.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:21.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:21.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:18.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:11.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:11.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.1.0 editor:indent (atom-text-editor.editor)
  2x -0:07.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:06.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:06.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:04.4.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "fontSize": 15,
    "autoIndent": false
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-23 20:42
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-23 20:42 UTC
