### ISSUE TITLE
Empty Untitled Tabs Remain When Reopening Project

### ISSUE THREAD

**Issue by amayer5125** [atom/atom#7913] opened 2015-07-15 14:32 UTC
If you follow these steps:
1. Open a project (folder)
2. Press [ctrl] + [n] to create a new empty tab
3. Close project/Atom window
4. Reopen project
There will be an empty *untitled tab* open. Im not sure if this is an inteneded behavior or just a by product of session saving.
This behavior happens even with `--safe`

I believe the empty tab should be removed on exit.

Using version 1.0.2 on Fedora (Linux)

**Comment by batjko** [comment] 2015-07-15 14:38
That seems to be standard behavior and I can see how there may be different preferences as to whether the untitled tab should be re-opened with the rest or not - in which case it's probably best to either leave it as it is, or otherwise provide a toggle for this behavior maybe?

**Comment by amayer5125** [comment] 2015-07-15 14:49
Yeah. I wasnt sure if its a *bug* or a *feature*. I just wanted to point it out either way. I dont find it annoying, but opening an empty tab just seems like a bug.
In addition: if you open a new tab, put content in it, and close the project it will prompt to save the empty tab. If you click "dont save" the tab comes back empty. This seems really buggy.

**Comment by batjko** [comment] 2015-07-15 14:59
> if you open a new tab, put content in it, and close the project it will prompt to save the empty tab.

You mean the not-so-empty tab now?

> If you click "dont save" the tab comes back empty. This seems really buggy.
Agreed, that's kinda weird and could use some polishing.

**Comment by amayer5125** [comment] 2015-07-15 15:25
Should have said *untitled tab* instead of *empty tab*

**Comment by izuzak** [comment] 2015-07-15 16:45
@amayer5125 This sounds like a duplicate of https://github.com/atom/atom/issues/3913. Can you take a look and close this if they're similar enough? :eyes:

**Comment by izuzak** [comment] 2015-07-15 23:21
I'm just gonna close this in favor of #3913. Let me know if I misunderstood, @amayer5125.

**Closed by izuzak** 2015-07-15 23:21 UTC

**Comment by amayer5125** [comment] 2015-07-16 00:02
@izuzak You are correct. This is a duplicate. I searched for `untitled tabs` but didnt find anything. Wonder how I missed that one.
