### ISSUE TITLE
Uncaught Error: dlopen(~/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/R...

### ISSUE THREAD

**Issue by helloazmi** [atom/atom#21780] opened 2020-12-03 19:56 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At electron/js2c/asar.js:138

Error: dlopen(/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app/static/<embedded>:1:696929)
    at get_KeyboardLayoutManager (/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app/static/<embedded>:14:2788409)
    at get_manager (/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app/static/<embedded>:14:2788511)
    at Object.getCurrentKeyboardLayout (/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app/static/<embedded>:14:2788637)
    at e.keystrokeForKeyboardEvent (/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app/static/<embedded>:14:1057732)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app/static/<embedded>:11:1227949)
    at KeymapManager.handleKeyboardEvent (/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app/static/<embedded>:11:1225934)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/azmi/Library/Caches/com.github.atom.ShipIt/update.UfSlR4S/Atom.app/Contents/Resources/app/static/<embedded>:11:284919)
```

### Commands

```
     -2:11.4.0 application:reopen-project (div#add-projects-view.)
  4x -1:38.3.0 symbols-view:toggle-file-symbols (atom-pane.pane.active)
  8x -1:03.6.0 editor:consolidate-selections (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-like-brackets-editor 1.2.0 
atom-live-server 2.3.0 
emmet 2.4.3 
html-tag-auto-complete 0.1.1 
platformio-ide-terminal 2.6.0 
terminal-plus 0.14.5 
```

**Comment by darangi** [comment] 2021-08-23 07:57
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2021-08-23 07:57 UTC
