### ISSUE TITLE
Not responding when open minified JS file

### ISSUE THREAD

**Issue by rst0git** [atom/atom#13867] opened 2017-02-23 07:33 UTC
Hello, I am using Atom as web-development and it is really annoying that Atom freeze for a while when I open minified JS file.

The minified JS file is simply one really really long line of javascript code.

Any idea how this could be fixed ?
Perhaps disable the markup ?

**Comment by Ben3eeE** [comment] 2017-02-23 07:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/979.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-02-23 07:54 UTC
