### ISSUE TITLE
Atom 1.12.1 crashes on Ubuntu 16.04.1, refuses to start

### ISSUE THREAD

**Issue by scan** [atom/atom#13192] opened 2016-11-11 10:39 UTC
### Description

I have checked all the ways, started in safe mode, cleared up and removed `~/.atom` and `~/.config/Atom`. Atom crashes in a very early state, the message is:

```
$ atom -f .
[9575:1111/113317:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
```

It crashes right on startup and I cannot get it up and running at all.

### Steps to Reproduce

I did the following:

1. Had Atom already open
2. Update Atom (and Chrome) via the apt channel.
3. Switched back to Atom window.

Then Atom crashed, and refuses to open again.

### Versions

```
$ atom -v
Atom    : 1.12.1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

Edit: In case it is relevant, I also have `google-chrome-stable` installed, version `54.0.2840.100`.

**Comment by scan** [comment] 2016-11-11 10:57
Completely purged the `atom` package, removed the PPA from the sources, and installed the `.deb` from the atom.io page. The problem persists.

**Comment by krishnaraj** [comment] 2016-11-11 11:02
Happens on Ubuntu 14.04 too

```
$ atom -f .
[19171:1111/163018:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
Gtk-Message: Failed to load module "unity-gtk-module"
```

**Comment by egeland** [comment] 2016-11-11 11:37
Linux Mint 18 (KDE) here.
For me, if I use `-f` it will start. If I don't use `-f` it will start several processes and eat all my CPU but no GUI opens.

**Comment by josebailo** [comment] 2016-11-11 12:22
I'm getting the same error @krishnaraj, nothing happens until I close the terminal window and then atom starts...

**Comment by ak0ska** [comment] 2016-11-11 12:40
I have also problems startin Atom 1.12.1 on Xubuntu 14.04 LTS. The process [/bin/bash -ilc command env](https://github.com/atom/atom/blob/v1.12.1/src/update-process-env.js#L66) hangs. If I kill it, Atom starts.

**Comment by scan** [comment] 2016-11-11 12:46
Compiling atom from scratch using the git tag `v1.12.1` also results in the same error message when I try to start.

@josebailo @ak0ska I believe your error is unrelated, unless you can also get that error message about the sandbox?

**Comment by ak0ska** [comment] 2016-11-11 12:52
If I start with -f I get that message too, but atom starts:
`[10346:1111/135007:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.`

**Comment by Ben3eeE** [comment] 2016-11-11 12:55
@ak0ska I believe https://github.com/atom/atom/issues/13084 is the issue you are having.

**Comment by ak0ska** [comment] 2016-11-11 12:56
Indeed, it looks like that one, thanks for the info. :)

**Comment by as-cii** [comment] 2016-11-11 16:44
Closing as duplicate of https://github.com/atom/atom/issues/13084. Thanks!

**Closed by as-cii** 2016-11-11 16:44 UTC
Labels: bug, linux, regression
