### ISSUE TITLE
Huge fonts on HiDPI displays

### ISSUE THREAD

**Issue by jellybob** [atom/atom#3826] opened 2014-10-14 16:37 UTC
I've just installed Atom from a git checkout on Ubuntu 12.10, and the attached screenshot is what I see (I've shrunk the editor font size). I'm assuming that fonts aren't really meant to be that large.

![huge-fonts](https://cloud.githubusercontent.com/assets/362/4632693/3be39dee-53c0-11e4-8e64-4458a73ae4ae.png)

**Comment by samtuke** [comment] 2015-01-09 18:23
Upgraded to Fedora 21, same issue also.

**Comment by JacobHenner** [comment] 2015-02-11 17:30
Same issue on Arch (with the huge menu bar).

**Comment by vks** [comment] 2015-02-21 22:11
I also have huge, unusable menus.

How does Atom decide how large the menu bar is rendered? I have a high dpi display, and increasing `Xft.dpi` in `~/.Xresources` makes Atom's menu huge and unusable. It seems it uses some custom way to draw the menus and screws it up.

**Comment by gausie** [comment] 2015-03-02 15:39
I am having the same problem as vks and LukeCarrier on Ubuntu 14.10 with Gnome 3.14 Shell

**Comment by bjames301** [comment] 2015-03-02 20:23
Same issue here. Huge font on menu bar.

**Comment by vks** [comment] 2015-03-02 21:09
Maybe we should open a new issue for this?

**Comment by bjames301** [comment] 2015-03-02 21:11
I agree because this has made Atom unusable for me.

**Comment by ockham** [comment] 2015-03-09 14:02
Fedora 21, same issue. @zcbenz can you reopen? Or do you want us to file a new issue?

**Comment by mrmylanman** [comment] 2015-03-10 20:05
I am not sure if this helps much, but I use Gentoo Linux. I recently patched `webkit-gtk` (version 2.4.8) to fix some fuzziness in Empathy and Geary and after I did that I noticed Atom has the huge menubars, as shown by @LukeCarrier.

Perhaps Fedora (and others) apply the hidpi patch (or some equivalent) by default?

I have created a [gist](https://gist.github.com/mrmylanman/61a20e14264120f69f0c) with the contents of the relevent patch (which was grabbed from the ArchLinux [AUR](https://aur.archlinux.org/packages/webkitgtk-hidpi/)).

**Comment by mnquintana** [comment] 2015-06-09 02:23
For anyone following this, this is still blocked – [Atom needs to update to a version of Electron built on Chrome 43](https://github.com/atom/electron/issues/1228#issuecomment-105011475), which won't be till after [this PR updating Atom to a version of Electron built on Chrome 42](https://github.com/atom/atom/pull/6877) is merged.

**Comment by Zireael07** [comment] 2015-06-09 11:45
Chrome 43 as I heard had some bugs of its own?

**Comment by batjko** [comment] 2015-06-09 12:29
Yes, 42 is already breaking a few things apparently, which is why upgrading to it for Atom is somewhat delayed.
They are thinking of maybe going straight to 43, once the incompatibilities have been sorted out.

**Comment by blasterbug** [comment] 2015-07-07 20:50
Same problem on debian sid with openbox, whatever I used atom `--force-device-scale-factor=1.4` or `--force-device-scale-factor=0.4`... 
![2015-07-07-22-50-22](https://cloud.githubusercontent.com/assets/891025/8556968/9b9c7470-24fa-11e5-818a-8bb6444abe1f.png)

**Comment by fibasile** [comment] 2015-07-09 14:47
I'm using an HiDpi monitor but set at half the resolution (1920x1080), had this problem too. Solved it with gsettings set org.gnome.desktop.interface scaling-factor 2

**Comment by liaowang11** [comment] 2015-07-09 15:15
Solution  from @fibasile works like a charm. Thanks.

**Comment by blasterbug** [comment] 2015-07-09 16:51
OK, fix perfectly the problem.

**Comment by mrmylanman** [comment] 2015-07-22 15:27
Just to clarify for people who may not be aware, the solution @fibasile is proposing is a workaround that disables Gnome's HiDPI setting (instead, rendering at native resolution). At that point, Atom does look as-expected only because HiDPI is no longer in use.

If you are okay with working at native resolution, you might want to do that anyway for the increased real estate, however it doesn't really solve the root cause. It is a good suggestion in the meantime, though.

**Comment by rfkrocktk** [comment] 2015-07-23 01:59
The solution proposed by @fibasile doesn't correct my problem. My problem is that Atom should be scaling up to 2x on my HiDPI display (on Linux), and it isn't, regardless of whether I pass `--force-device-scale-factor 2` or any other number.

The value of `org.gnome.desktop.interface scaling-factor` is the special value `0`, which means that scaling should be done per monitor. I don't have any external monitors connected presently, but everything else including Google Chrome works properly. Please see these screenshots to see the problem, Atom should be scaling up like everything else, but isn't:

![](https://camo.githubusercontent.com/5b021e9346501e4deae9d450ca2ef6a8762dd95d/68747470733a2f2f692e696d6775722e636f6d2f7250414b4352302e706e67)
![](https://camo.githubusercontent.com/c4fac0df3bb085f377c88462bd53f29ca6f4a886/68747470733a2f2f692e696d6775722e636f6d2f6b77625a34645a2e706e67)

Windows on the left are scaling properly, with Atom on the right not scaling properly. Please see the closed #8035 for my exact setup.

**Closed** 2015-09-08 15:41 UTC
Labels: blocked, bug, linux

**Comment by JacobHenner** [comment] 2015-09-11 15:27
The menus are still way too large in 1.0.11, GNOME, Arch Linux.

**Comment by varemenos** [comment] 2015-09-11 15:31
@JacobHenner afaik, this is not live yet, you will have to build it yourself or wait for the release that uses Electron v0.30.6

**Comment by margaritis** [comment] 2015-12-06 11:08
El Capitan 10.11.1, Ultrawide (2560 x 1080)

![screen shot 2015-12-06 at 13 07 32](https://cloud.githubusercontent.com/assets/5788810/11613017/5c287522-9c1a-11e5-8d14-6e8d2ae5e27b.png)
