### ISSUE TITLE
1.22.1 `.deb` package on website fails to install on Ubuntu

### ISSUE THREAD

**Issue by maxvu** [atom/atom#16281] opened 2017-11-28 03:50 UTC
### Steps to Reproduce

1. From a fresh Ubuntu install, navigate to [atom.io](https://atom.io/) and download the `.deb` package listed (here, retrieved at version 1.22.1).
2. Run the package from the DE shell (here, `thunar`).
3. Be prompted with an Ubuntu Software Center dialog, click **Install**.

**Alternately**

2. Run `dpkg -i ~/Downloads/atom-amd64-.deb`.

### Expected Behavior

A successfully completed Ubuntu Software Center (having gotten required dependencies) dialog, a completed `dpkg` install or an error message indicating the reason for failure. Also, the system package manager is not left in a broken state.

### Actual Behavior

Ubuntu Software Dialog flickers from "Install" button to progress bar installing back to "Install" in less than half-a-second. There is no error message indicating the failure.

With dpkg, the install fails with:

```
max@mycomputer:~$ sudo dpkg -i /home/max/Downloads/atom-amd64.deb 
Selecting previously unselected package atom.
(Reading database ... 190139 files and directories currently installed.)
Preparing to unpack .../max/Downloads/atom-amd64.deb ...
Unpacking atom (1.22.1) ...
dpkg: dependency problems prevent configuration of atom:
 atom depends on python; however:
  Package python is not installed.

dpkg: error processing package atom (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 atom
```

Successive calls to the package manager indicate broken package state:

```
max@mycomputer:~$ sudo apt-get install python
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 python : PreDepends: python-minimal (= 2.7.14-2ubuntu1) but it is not going to be installed
          Depends: python2.7 (>= 2.7.14-1~) but it is not going to be installed
          Depends: libpython-stdlib (= 2.7.14-2ubuntu1) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

### Versions

* 1.22.1

### Additional Information

(none)

**Comment by rsese** [comment] 2017-11-28 05:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14358. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-28 05:28 UTC
