### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectLinesContainingCursors' of undefined

### ISSUE THREAD

**Issue by hitobashira** [atom/atom#12050] opened 2016-06-27 00:09 UTC
[Enter steps to reproduce below:]

1.when , setting - at text area of keybindings (and all setting text area). 
2.using sample command in init.coffee.

[alt-k]  'custom:cut-line2'

init.coffee
-------
atom.commands.add 'atom-text-editor', 'custom:cut-line2', ->
  editor = atom.workspace.getActiveTextEditor()
  editor.selectLinesContainingCursors()
#  editor.selectLine()
  editor.cutSelectedText()

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'selectLinesContainingCursors' of undefined

```
At /home/zish/.atom/init.coffee:18

TypeError: Cannot read property 'selectLinesContainingCursors' of undefined
    at atom-text-editor.<anonymous> (/home/zish/.atom/init.coffee:18:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -9:22 vz-char:vz-char-cut (atom-text-editor.editor.mini.is-focused)
  6x -9:18.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  7x -9:16.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -9:01.1.0 editor:newline (atom-text-editor.editor.mini.is-focused)
 15x -8:55 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -8:51.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -6:09.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:07.9.0 vz-char:vz-char-cut (atom-text-editor.editor.mini.is-focused)
  2x -5:52.2.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -5:48.8.0 custom:cut-line2 (atom-text-editor.editor.mini.is-focused)
  2x -0:25.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 11x -0:21 core:move-left (atom-text-editor.editor.mini.is-focused)
  2x -0:16.9.0 vz-char:vz-char-cut (atom-text-editor.editor.mini.is-focused)
  6x -0:09.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  6x -0:06.5.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:01.0 custom:cut-line2 (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "archive-view",
      "autoflow",
      "language-csharp",
      "language-gfm",
      "language-mustache",
      "language-objective-c",
      "language-sass",
      "language-sql",
      "language-toml",
      "language-yaml",
      "metrics",
      "text-pastry",
      "textmate-clipboard",
      "clip-history",
      "fuzzy-finder",
      "markdown-preview",
      "git-diff",
      "minimap-selection",
      "webbox-color",
      "joe-keybinds",
      "highlight-bad-chars",
      "bookmarks",
      "duplicate-line-or-selection",
      "autocomplete-bash-builtins",
      "atom-terminal",
      "emacs-core-keys",
      "remove-all-keybindings",
      "find-and-replace-fix",
      "revert-buffer",
      "command-executor",
      "smart-cutcopypaste",
      "copy-word",
      "copy-improved",
      "neon-cursor",
      "block-cursor",
      "maximize-panes",
      "reflow-japanese",
      "text-buffer",
      "paste-buffer",
      "atom-beautify",
      "run-command",
      "pigments"
    ],
    "followSymlinks": false,
    "packagesWithKeymapsDisabled": [
      "highlight-line",
      "disable-keybindings",
      "symbols-view",
      "atomic-emacs",
      "shell-it",
      "copy-word",
      "find-selection"
    ],
    "showInvisibles": true,
    "themes": [
      "kobalt-ui",
      "kobalt"
    ]
  },
  "editor": {
    "autoIndent": false,
    "backUpBeforeSaving": true,
    "confirmCheckoutHeadRevision": false,
    "fontFamily": "Ricty",
    "fontSize": 26,
    "invisibles": {
      "space": "⎕"
    },
    "lineHeight": 1.2,
    "nonWordCharacters": "/\\()\"':,.;<>~!$^%#

**Comment by lee-dohm** [comment] 2016-06-29 20:41
This is a duplicate of #12051 in that it has the same bug. Please see my comments there for further details.

**Closed by lee-dohm** 2016-06-29 20:41 UTC

**Comment by hitobashira** [comment] 2016-07-04 09:11
thank you.
