### ISSUE TITLE
Font rendering broken with freetype 2.8.1 and subpixel rendering

### ISSUE THREAD

**Issue by mbiebl** [atom/atom#15929] opened 2017-10-18 16:36 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom version: 1.21.1

Since the update of freetype from 2.8.0 to 2.8.1, font rendering under linux is broken when using subpixel rendering.
- freetype 2.8.0
![freetype2 8 0](https://user-images.githubusercontent.com/3609611/31730691-fbbbd624-b432-11e7-9fb6-d182e8a70163.png)
- freetype 2.8.1
![freetype2 8 1](https://user-images.githubusercontent.com/3609611/31730711-0c4b2742-b433-11e7-8111-5cd49290f2b1.png)

There is a downstream bug report at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878870 with further information. I suspect this ultimately needs to be fixed in electron. I'm still filing this against atom as it will need to be rebuilt against a fixed electron.

**Comment by rsese** [comment] 2017-10-18 20:31
Thanks for the report @mbiebl - is there an Electron issue we can cross-reference here?

**Comment by mbiebl** [comment] 2017-10-18 20:39
hi @rsese, not that I'm aware of. I have to add that I suspect that it's ultimately an electron issue, but I might be wrong.

**Comment by mbiebl** [comment] 2017-10-18 21:01
electron or chromium issue to be precise.

**Comment by mbologna** [comment] 2017-10-19 07:56
Confirmed, I have the same problem.

**Comment by Zireael07** [comment] 2017-10-19 08:18
Is this a dupe of #15737 ?

**Comment by 50Wliu** [comment] 2017-10-19 08:24
Yep, closing in favor of #15737.

**Closed by 50Wliu** 2017-10-19 08:24 UTC
Labels: more-information-needed

**Comment by mbiebl** [comment] 2017-10-19 08:29
@Zireael07 looks like it. Thanks. Could you retitle #15737 to be a bit more descriptive. Maybe I didn't find it because of that.

**Comment by mbiebl** [comment] 2017-10-19 08:34
fwiw, if you are affected by this and you can't easily downgrade freetype, as an alternative you can switch from subpixel to grayscale antialiasing.

**Comment by Ben3eeE** [comment] 2017-10-19 08:35
@mbiebl Changed the title of #15737 to include freetype 2.8.1.

**Comment by mbiebl** [comment] 2017-10-19 08:36
@Ben3eeE thanks a lot

**Comment by Zireael07** [comment] 2017-10-19 08:37
@mbiebl this is an extremely informative issue, though - much more informative than the other one :)

**Comment by rsese** [comment] 2017-10-19 18:41
Totally missed the duplicate thanks @Zireael07 :bow:
