### ISSUE TITLE
Unicode chars broken

### ISSUE THREAD

**Issue by rumpelsepp** [atom/atom#6435] opened 2015-04-19 08:56 UTC
In recent atom releases I have massive problems with unicode chars. Here is a screenshot of atom, below the same file in gedit. I also tried greek letters, they don't work as well. IIRC this regression appeared in 0.190.

```
$ atom --version
0.192.0
```

![screenshot from 2015-04-19 10-53-33](https://cloud.githubusercontent.com/assets/1961699/7218829/7d8535aa-e682-11e4-8d13-bf06f4445951.png)

**Comment by 50Wliu** [comment] 2015-04-19 15:07
Duplicate of #6214, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-19 15:07 UTC
