### ISSUE TITLE
[nightly] Comment highlighting is leaking

### ISSUE THREAD

**Issue by Aerijo** [atom/atom#19582] opened 2019-06-21 05:48 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Comment highlighting is leaking to non comments in latest nightly (and build from master).

![image](https://user-images.githubusercontent.com/22167388/59899751-38e3a300-9439-11e9-82f3-bed4266a7efd.png)

### Steps to Reproduce

1. Use 1.40.0-nightly13, and `atom-one-dark` syntax theme
2. Open the Atom repo
3. Open `/packages/grammar-selector/lib/grammar-list-view.js`
4. Look at something following a comment that should have plain highlighting
5. Make an edit inside a wrongly highlighted word. It should be corrected.
6. Close and reopen the file. The bit that was fixed should be broken again.

**Expected behavior:**

Plain white identifiers

**Actual behavior:**

Comment like identifiers

**Reproduces how often:**

100%

I am 99% sure it's not something I've done to my local Atom build.

Edit: good thing I left that 1% :sweat_smile: 

### Versions

```
15:26 $ atom-nightly -v
Atom    : 1.40.0-nightly13
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

**Comment by Arcanemagus** [comment] 2019-06-21 07:18
I'm unable to reproduce this, tested in both v1.40.0-nightly13 and the current `-nightly14`:
![image](https://user-images.githubusercontent.com/427137/59905110-1494b180-93ba-11e9-8c8f-4917602c041a.png)

Were you seeing this in safe mode? Are you sure it was set to the grammar from `language-javascript`? What OS are you on?

**Comment by Aerijo** [comment] 2019-06-21 08:04
Ahh, safe mode. Turns out it was a `language-todo` replacement with Tree-sitter grammar that was causing the issue. I ran `apm rebuild` on it, and it works now. I don't know if this is going to be an issue for other community packages, but I'll close this issue.

**Comment by Aerijo** [comment] 2019-07-16 05:30
This reproduces in safe mode with version 1.40.0-nightly23

1. Make a new TypeScript file with the following contents
```
/**
 * @param tag
 */
function foo (bar: string) {
  baz()
}
```
2. Run `Editor: Fold At Indent Level 1`
3. See that this happens
![image](https://user-images.githubusercontent.com/22167388/61268372-9243b580-a7de-11e9-9de7-fda0db296b2a.png)

**Comment by rsese** [comment] 2019-07-16 21:11
Thanks for the update @Aerijo, just want to drop what I see based on your last comment - with nightly:

![highlighting-leak-nightly](https://user-images.githubusercontent.com/734194/61329421-df298b00-a7e2-11e9-9d49-eaffe3c60d6c.gif)

and beta:

![highlighting-leak-beta](https://user-images.githubusercontent.com/734194/61329431-e355a880-a7e2-11e9-9298-8e8fd281889d.gif)

So with nightly I see the 2 braces are colored as comments after I paste your snippet though if I paste just:

```typescript
/**
*/
```

and then manually type the braces, I see what you describe where the braces are comment colored after your steps 3 - 5.

Also looks like if I backspace to the brace lines, the coloring changes?

![highlighted like comments](https://user-images.githubusercontent.com/734194/61329962-23695b00-a7e4-11e9-81d2-ba7d66c0bc09.gif)

**Comment by Aerijo** [comment] 2019-08-01 02:18
This still reproduces in JS files with
```
/** @babel */
```
E.g., https://github.com/atom/settings-view/blob/master/lib/package-updates-status-view.js

/cc @nathansobo, @maxbrunsfeld

**Comment by as-cii** [comment] 2019-08-02 09:44
Thanks for the report, @Aerijo!

This should be fixed as of the latest commit on master (https://github.com/atom/atom/commit/b4971d07562b8e759753ecea3fc5b3594b558be6). I'll go ahead and close the issue, but please feel free to reopen it if you encounter other instances of this problem.

**Closed by as-cii** 2019-08-02 09:44 UTC
Labels: d ⬆️, i ⬇️, triaged, v ⬆️
