### ISSUE TITLE
Uncaught Error: error: 126/\?\~\AppData\Local\atom\app-1.39.0\resources\app.asar.unpacked\node_mo...

### ISSUE THREAD

**Issue by Steamarino** [atom/atom#19694] opened 2019-07-23 21:51 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: PC
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 126\\?\C:\Users\trist\AppData\Local\atom\app-1.39.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:166

Error: error: 126\\?\C:\Users\trist\AppData\Local\atom\app-1.39.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:1:725913)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:14:2700917)
    at get_manager (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:14:2701019)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:14:2701145)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:14:1086076)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:1245252)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:1243237)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.39.0/resources/app/static/<embedded>:11:283942)
```

### Commands

```
     -0:40.2.0 core:copy (span.syntax--source.syntax--js)
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-discord 2.0.2 
atom-import-js 0.21.0 
atom-js 1.2.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
Hydrogen 2.10.3 
```

**Comment by rsese** [comment] 2019-07-23 22:02
Thanks for contributing!

We noticed that this looks like a duplicate of #14461 so you can subscribe there for updates if you'd like.  Also, if you have an anti-virus program running you can try temporarily disabling it and then reinstall Atom to see if that helps.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-07-23 22:02 UTC
