### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.47.0\res...

### ISSUE THREAD

**Issue by Axist8** [atom/atom#20757] opened 2020-05-19 20:59 UTC
[Enter steps to reproduce:]

1. Use any key on keyboard and error message pops up.

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Axist\AppData\Local\atom\app-1.47.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At electron/js2c/asar.js:138

Error: The specified module could not be found.
\\?\C:\Users\Axist\AppData\Local\atom\app-1.47.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:735013)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:2676868)
    at get_manager (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:2676970)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:2677096)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:1022283)
    at KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1239133)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1237118)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:284782)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by scott-rosenbalm** [comment] 2020-05-19 21:33
I'm having the same issue, it just started happening mid-programming today.

**Comment by Axist8** [comment] 2020-05-20 14:43
I uninstalled and reinstalled and it fixed the issue.

**Comment by duboloms** [comment] 2020-05-20 15:42
open the directory where your atom is located
**I have this C:\Users\_Your user name_\AppData\Local\atom**
**After that, go to the bin folder and click on the atom.cmd file, just in case, click on apm.cmd.**
Close atom and open it again, it should work.

**Comment by scott-rosenbalm** [comment] 2020-05-20 18:14
> 
> 
> open the directory where your atom is located
> **I have this C:\Users_Your user name_\AppData\Local\atom**
> **After that, go to the bin folder and open the atom.cmd file, just in case, click on apm.cmd.**
> Close atom and open it again, it should work.

I tried this, but I'm still seeing the issue... I may try uninstall and reinstall.

**Comment by tskthomas** [comment] 2020-05-25 08:51
I had this problem with 1.47 but i noticed 1.46 (which is in the same AppData\Local\atom\  folder) running fine. So i closed all running atom and clicked Update.exe, now it runs fine.

**Comment by sadick254** [comment] 2020-09-16 15:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-09-16 15:12 UTC
