### ISSUE TITLE
After opening several, tabs are not all displayed.

### ISSUE THREAD

**Issue by valix** [atom/atom#10429] opened 2016-01-15 10:45 UTC
After opening several tabs (about 18), the tabs are not all displayed. Atom 1.5.0-beta0
![bugtab](https://cloud.githubusercontent.com/assets/296379/12351290/cfdf7f84-bb7c-11e5-85b9-5194fcc053b4.png)

**Comment by ChristianGrech** [comment] 2016-01-16 18:20
+1

**Comment by amytruong** [comment] 2016-03-17 17:46
Dupe of https://github.com/atom/tabs/issues/137

**Closed by amytruong** 2016-03-17 17:46 UTC

**Comment by amytruong** [comment] 2016-03-17 17:47
You can also subscribe to thread :point_up: for updates :smile:
