### ISSUE TITLE
Old app* folders and nupkg files left behind by Atom.

### ISSUE THREAD

**Issue by david-in-perth** [atom/atom#15621] opened 2017-09-12 12:17 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [ ] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [ ] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * (N/A) Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom isn't cleaning up _AppData\Local\atom\app-*_ directories and _AppData\Local\atom\packages\atom-*.nupkg_ files.

### Steps to Reproduce

In short: Install an Atom update.

I only just noticed this, so I'll have to wait until the next Atom release before I can give more info about exactly what happens at update time.

**Expected behavior:** That files relating to old versions of Atom are deleted after update, except perhaps a backup of the most recent pre-update version of Atom (as described in #11586)

**Actual behavior:** None of the old versions of Atom are being deleted, and _nupkg_ files for old versions of Atom also remain. At time of writing, _\AppData\Local\atom_ contains more than 6 GB of files.

**Reproduces how often:** There's an _app-*_ directory and two _atom-*.nupkg_ files for all 1.19.x releases that I've installed (1.19.0 - 1.19.7; 8 in total), and there's also an _app-1.18.0_ directory (but no _nupkg_ files for 1.18.0).

### Versions

Windows 10 (Version 1607 build 14393.693)

Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 ia32
python 3.6.1
git 2.11.0.windows.3
visual studio 2013

### Additional Information

I've attached [AppData\Local\atom\SquirrelSetup.log](https://github.com/atom/atom/files/1295840/SquirrelSetup.log.txt), in case that helps.

**Comment by david-in-perth** [comment] 2017-09-12 13:14
I don't know how to try and reproduce or debug the problem while I'm already on the latest version. 

Maybe if I could work out how to roll back to 1.19.6, I could try running the update again. @50Wliu says in https://github.com/atom/atom/issues/11586#issuecomment-213769304 that the _app-*_ backups exist in case something goes wrong, which implies that it's intended for users to be able to roll back There doesn't seem to be any information on how to roll back though.

**Comment by rsese** [comment] 2017-09-12 23:22
Thanks for taking the time to contribute!  

A more recent issue was opened about this so we'll go ahead and close as a duplicate of https://github.com/atom/atom/issues/15320 - you can subscribe there for updates if you'd like.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-09-12 23:22 UTC
