### ISSUE TITLE
Allow starring of community packages in installed list 

### ISSUE THREAD

**Issue by aioue** [atom/atom#5515] opened 2015-02-12 15:24 UTC
Allow toggling of whether a package is starred on atom.io from inside Atom.

This eases the install of Atom on other computers by using `apm stars --install`.

**Comment by izuzak** [comment] 2015-02-12 16:57
Thanks, @aioue, looks like a duplicate of https://github.com/atom/settings-view/issues/141.

**Closed by izuzak** 2015-02-12 16:57 UTC
