### ISSUE TITLE
Hang on when clicking checking for updates

### ISSUE THREAD

**Issue by forrestchang** [atom/atom#13490] opened 2016-12-22 11:12 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![image](https://cloud.githubusercontent.com/assets/7857126/21423641/22a314e2-c879-11e6-8c5c-18509cf607a6.png)

Can not close the alert window.

### Steps to Reproduce

1. Atom -> Checking for updates
2. Before the alert window appearing, reclick the Atom menu.
3. And then the alert window appeared, but can't be closed. You need to kill atom process manually.

**Expected behavior:** After doing 1 & 2, we can still close the window.

**Actual behavior:** After doing 1 & 2, we can't close window.

**Reproduces how often:** Everytime I test in that behaviour.

### Versions

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Even though this problem doesn't affect using, but still a bug need to be fixed.

**Comment by 50Wliu** [comment] 2016-12-22 17:43
So just to confirm, pressing OK doesn't do anything?

**Comment by forrestchang** [comment] 2016-12-23 00:42
@50Wliu Yes, you need to kill atom process manually.

**Comment by lee-dohm** [comment] 2016-12-23 03:14
@forrestchang I can't reproduce this using Atom v1.12.7 on Mac OS X 10.12.2. I was able to get the alert to not respond once but simply clicking on the window and then clicking the alert freed it up. Every other time I tried it, the problem you mention did not reproduce. Did you try reproducing the problem in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by forrestchang** [comment] 2016-12-23 06:01
@lee-dohm Yes. I have launched Atom in Safe Mode. I tried it a lot of times, and every time the problem reproduced. I am using macOS 10.12.1.

**Comment by lee-dohm** [comment] 2016-12-23 15:08
Can you try updating to 10.12.2 and see. If the problem goes away?

**Comment by Ben3eeE** [comment] 2016-12-23 21:39
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12935. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-23 21:39 UTC
Labels: more-information-needed, needs-reproduction
