### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/frasermacinnes/Library/Applicati...

### ISSUE THREAD

**Issue by frasermac24** [atom/atom#9698] opened 2015-11-19 16:29 UTC
[Enter steps to reproduce below:]

1. I was trying to open preferences from the menu bar

**Atom Version**: 1.2.2
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/frasermacinnes/Library/Application Support/com.github.atom.ShipIt/update.06kHZYC'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/frasermacinnes/Library/Application Support/com.github.atom.ShipIt/update.06kHZYC'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/frasermacinnes/Library/Application Support/com.github.atom.ShipIt/update.06kHZYC/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
```

### Config

```json
{
  "editor": {
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-19 17:44
Duplicate of #9559 and #7399, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-19 17:44 UTC
