### ISSUE TITLE
Cursor positioning on certain Unicode characters

### ISSUE THREAD

**Issue by yongqli** [atom/atom#3498] opened 2014-09-08 17:17 UTC
As a Haskell programmer, I like the ability to use Unicode character in names. However, I've noticed that the character "𝒢" with the default font causes Atom to place the cursor too far to the right, creating a gap.

**Comment by izuzak** [comment] 2015-05-02 08:51
I think this is a duplicate of https://github.com/atom/atom/issues/1849 -- I can still reproduce the strange cursor position with some characters (see https://github.com/atom/atom/issues/1849#issuecomment-50087298). Going to close this in favor of that issue, but let me know if this isn't these aren't the same problems.

**Closed by izuzak** 2015-05-02 08:51 UTC
Labels: bug, editor-rendering, more-information-needed
