### ISSUE TITLE
Command palette search results are poor

### ISSUE THREAD

**Issue by brandonwamboldt** [atom/atom#6461] opened 2015-04-21 23:38 UTC
Bring up the command palette and search "Install". Results:

- Find And Replace: Select All
- Application: Install Update
- Settings View: Uninstall Themes
- Settings View: Uninstall Packages
- Settings View: Install Packages and Themes

![untitled-1](https://cloud.githubusercontent.com/assets/629141/7264772/fab661d6-e865-11e4-95b9-7f0e6993f985.png)

I'd say that we should mirror Sublime's technique, where:

- We only match the action name (or we weight the name higher)
- An exact word match (versus a partial match) should be weighted higher ("**Install** Packages" should be higher than "Un**install** Packages")
- Built in packages should be weighted higher?
- Application: Install Update should probably be intentionally weighted lower, as users will more often want to install packages I imagine

**Comment by 50Wliu** [comment] 2015-04-21 23:52
Duplicate of atom/command-palette#28 and atom/fuzzy-finder#21 (probably more but those are the ones I found the quickest).

**Closed by 50Wliu** 2015-04-21 23:52 UTC
