### ISSUE TITLE
No response when running atom at one side of desktop (Windows)

### ISSUE THREAD

**Issue by bitmingw** [atom/atom#9901] opened 2015-12-02 04:33 UTC
I have a problem with atom (version 1.2.4) on my Windows 10 laptop. In Windows we can split the view and run applications side by side using Win+LEFT or Win+RIGHT key. When we run atom at one side, even if we keep atom at front, typing keyboard won't have any response until the window is restored or maximized.

Here is the way to reproduce the problem.

1. Open atom, maximize the window, type some content.
2. Type Win+RIGHT to set atom to the right of the screen.
3. Keep atom at front, type keyboard (no response this time).
4. Maximize the window, the content will now show up.

**Comment by psallandre** [comment] 2015-12-02 06:24
Same issue for me, Atom 1.2.4, Windows 10 desktop.
Actually all the Atom screen doesn't respond, clicking the tree view has not effect, cannot switch tabs...

**Comment by thedaniel** [comment] 2015-12-02 13:53
cc @zcbenz @raelyard - not sure if this is atom-specific or a general electron issue

**Comment by raelyard** [comment] 2015-12-02 14:44
I can't seem to make this happen, following the same steps.  Win 10 added an extra step after Win+Right where it wants you to pick a windows for the other side of the screen - did you pick something there?  I tried pressing esc there as well as picking a window and not seeing this.

**Comment by psallandre** [comment] 2015-12-02 15:58
The extra step in Win 10 can be disabled in System / Multitasking / 'When I snap a window, show what I can snap next it'. I turned that on and off, I haven't seen any significant difference on issue, I leave it off.
I did some more testing, the problem is not systematic actually. These steps seem to reproduce more often:
- Open Atom
- Maximize the window (Win+Up)
- Click and hold the menu bar and go down a bit with the mouse just to "de-maximize" the window
- Win+Right or click and hold the menu bar and drag to the right border

**Comment by amytruong** [comment] 2015-12-02 17:23
I haven't been able to reproduce this either. Like @raelyard I originally hit that extra step where it wants me to select a window so then I disabled the extra step in System/Multtaking like @psallandre mentioned and tried the alternative steps. Still no dice. :confounded: 

I'll try to take another stab at it later.

**Comment by 50Wliu** [comment] 2015-12-02 20:28
I can't reproduce this on Windows 10 using 1.4.0-dev-f2155fa, and I've always had the extra snap feature disabled.

**Comment by atom-project** [comment] 2015-12-02 22:52
I've the same problem on Win10:

Win + RIGHT -> no draw until window resize

Really annoying bug. Disabling extra snap is not an option.

**Comment by dbruce1990** [comment] 2016-01-01 23:39
I'm having this exact same issue. Also on windows 10.

**Comment by LondonAppDev** [comment] 2016-01-10 09:27
I'm having exact same issues. @50Wliu did you enable the Windows 10 snap feature when you tested?

**Comment by 50Wliu** [comment] 2016-01-10 16:27
Odd, I just managed to reproduce this when testing what @LondonAppDev suggested.
1. Turn on the extra snap feature
2. Win+right Atom, still responsive
3. Maximize Atom
4. Turn off extra snap
5. Win+right Atom, no redraw

Atom 1.5.0-dev-c34ef24.  I can't tell whether this is due to me running Electron 0.36 or not though.  In addition I can't seem to reproduce it reliably.

**Comment by raelyard** [comment] 2016-01-11 19:25
I have not reproduced with any of the steps described here - simply snapping to right or left as half-screen does not exhibit the behavior for me.

I did, though, find steps to reliably reproduce (on my machine - seems pretty inconsistent experiences).  Extra snap enabled/disabled makes no difference - it happens either way.

Also happens reliably in Slack, so must be Electron.

1. Maximize Atom
2. Win+right Atom, still responsive
3. Win+down Atom to make quarter-screen on lower right, still responsive
4. Win+left Atom to move to lower left, no redraw

**Comment by LondonAppDev** [comment] 2016-01-12 07:15
@raelyard try doing it with two instances of Atom. Load the first instance, snap left, then load the second instance and snap right. 100% of the time my right one freezes until I unsnap it.

I am opening a new instance by right clicking a directory and clicking "Open with Atom"

**Comment by raelyard** [comment] 2016-01-13 03:56
@LondonAppDev not getting the same result.  Two instances doesn't seem to matter and I have yet to see the problem with following your steps.

**Comment by Tiin57** [comment] 2016-01-30 03:29
Adding my voice - I can definitely confirm this issue, and it happens when I drag or use WIN+arrow, and I only ever have one instance/window open at a time.

**Comment by MajorBreakfast** [comment] 2016-02-03 09:03
I get this issue all the time (Currently atom@1.5.0-beta3, Windows 10). I think it only happens when the window remains the same size before and after the snapping. Easiest way to get a window of the same size is to snap a window and then use the "Open in Atom" context menu link which opens another window.
@raelyard You should reopen this issue. It is definitly a thing!

**Comment by benogle** [comment] 2016-02-03 19:10
This will likely be fixed in https://github.com/atom/atom/pull/9627

**Comment by MajorBreakfast** [comment] 2016-02-03 20:11
@benogle Nice!

**Closed** 2016-02-16 22:08 UTC
Labels: bug, electron, windows

**Comment by MajorBreakfast** [comment] 2016-02-17 08:59
@maxbrunsfeld Will this change land in `atom@1.6.0-beta4`?

**Comment by lukeapage** [comment] 2016-03-29 04:35
I am getting this problem in 1.6.0
windows 10, side-by-side. I've tried safe mode, no change
can anyone confirm? @maxbrunsfeld will you re-open?

**Comment by MajorBreakfast** [comment] 2016-03-31 09:41
I'm running 1.6.1 and it seems to be working fine now. I'll comment, should I run into the problem again. Everything works now as far as I can tell!

**Comment by lukeapage** [comment] 2016-03-31 12:22
I will upgrade and retest at home to see if there are scenarios (it works fine for me with win7 at work, just win 10). Your earlier comment about it only happening when the window is the same size - thats not the case for me.

**Comment by lukeapage** [comment] 2016-04-03 06:32
No this still happens. As @MajorBreakfast pointed out above it only occurs when the window is not resized. I'll raise a new bug.

**Comment by lukeapage** [comment] 2016-04-03 16:47
This is confirmed fixed in 1.7.0 (& present in 1.6.0,1.6.1, 1.6.2)
