### ISSUE TITLE
how about working on remote ftp file

### ISSUE THREAD

**Issue by tatarespecia** [atom/atom#7271] opened 2015-06-14 02:56 UTC
Please consider adding feature on opening remote/ftp  file like Eclipse does.
Thanks!

**Comment by mark-hahn** [comment] 2015-06-14 04:36
There are three or four packages that provide opening remote files.  Search
on Atom.io.  I happen to use the aptly-named "remote-edit".

**Comment by mnquintana** [comment] 2015-06-14 11:39
Thanks for the suggestion! This is a duplicate of https://github.com/atom/atom/issues/7117.

[There are already quite a few solid community packages for FTP](https://atom.io/packages/search?q=ftp), so it's unlikely that Atom will be adding that to core.

**Closed by mnquintana** 2015-06-14 11:39 UTC
