### ISSUE TITLE
Bracket pairing parses commented lines

### ISSUE THREAD

**Issue by qrawl** [atom/atom#8842] opened 2015-09-18 13:44 UTC
![image](https://cloud.githubusercontent.com/assets/4400408/9960556/7849e476-5e1b-11e5-97f1-e37d4116ac80.png) ![image](https://cloud.githubusercontent.com/assets/4400408/9960595/aed39140-5e1b-11e5-8484-11b8531027be.png) ![image](https://cloud.githubusercontent.com/assets/4400408/9960694/7919b344-5e1c-11e5-87b6-ddc1cb224573.png)
When dropping the cursor next to a bracket, Atom fails highlighting the pairing bracket when a commented one is in the way.

I expected Atom to ignore the commented one.

I'm sorry I can't contribute with a PR with my current level of JavaScript... ehr... expertise.

**Comment by mnquintana** [comment] 2015-09-18 14:14
Thanks for the report! This looks like a duplicate of https://github.com/atom/bracket-matcher/issues/78 though – please subscribe there for updates.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Closed by mnquintana** 2015-09-18 14:14 UTC
