### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 38Error: Cannot call...

### ISSUE THREAD

**Issue by JuliaGerasymenko** [atom/atom#19930] opened 2019-09-19 10:48 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 38
Error: Cannot call function 'getPosition' on missing remote object 38
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:271

Error: Cannot call function 'getPosition' on missing remote object 38
Error: Cannot call function 'getPosition' on missing remote object 38
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705395)
    at AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705810)
    at WindowEventHandler.handleWindowResize (/usr/share/atom/resources/app/static/<embedded>:11:285420)
    at l (/usr/share/atom/resources/app/static/<embedded>:11:1197399)
```

### Commands

```
     -4:11.8.0 tree-view:add-file (span.name.icon.icon-repo)
     -4:05.3.0 core:backspace (input.hidden-input)
     -3:58.6.0 core:move-left (input.hidden-input)
     -3:57.3.0 core:move-right (input.hidden-input)
     -3:54.7.0 core:confirm (input.hidden-input)
     -3:52.6.0 core:paste (input.hidden-input)
     -3:51.2.0 core:save (input.hidden-input)
     -1:47.8.0 settings-view:open (input.hidden-input)
  2x -0:42.4.0 gpp-compiler:compile (input.hidden-input)
     -0:39.9.0 gpp-compiler:gdb (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-storybook 1.3.0 
gpp-compiler 3.0.7 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
prettier-atom 0.57.2 
preview 0.19.0 
```

**Comment by rsese** [comment] 2019-09-19 17:21
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-09-19 17:21 UTC
