### ISSUE TITLE
If you reload the updates page in settings while updating a plugin, it won't show as updating when you come back to it.

### ISSUE THREAD

**Issue by PlanetVaster** [atom/atom#17436] opened 2018-05-30 21:31 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you start updating a plugin (or plugins), then close the settings tab and re-open it or reload it, the plugin(s) won't show as updating and if you restart the update(s) the counter in the bottom right will say a bigger number than the amount of updates (ex. 2/1 updates)

### Steps to Reproduce

1. Start updating some plugins
2. Close the settings page (or even just the updates section of the page)
3. Come back to the updates page in the settings

**Expected behavior:** Plugin(s) are not showing as updating 

**Actual behavior:** They are still updating in the background

**Reproduces how often:** 100% on my machine (Windows 10 (latest) and the latest stable Atom (1.27.1))

### Versions

Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

Windows 10 (1803 build 17134.81)

### Additional Information

This has happened on every version of Atom I've ever used. And while I'm not sure, I believe that if you manually start the update for all your plugins from the settings page, "Update All" is still clickable which could be another bug. (I don't have any plugin updates to test that bug right now though). I don't report bugs often so sorry if I formatted this wrong or something.

**Comment by 50Wliu** [comment] 2018-05-31 00:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/settings-view#901. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2018-05-31 00:12 UTC
