### ISSUE TITLE
Typing goes inside the file content instead Find File Plate(Ctrl+P)

### ISSUE THREAD

**Issue by vafagh** [atom/atom#16355] opened 2017-12-11 03:34 UTC
When I have open file and I try to search for file, Sometime I mistakenly use the Ctrl+Shift+P to search for file than when I find out about that and I use the Ctrl+P to switch to the find plates and start typing, my typing goes inside the file(wherever cursor was in) instead inside the find plates. Also Esc  won't work.

### Steps to Reproduce

1. Open a file
2. Press this key combination: Ctrl+Shift+P
 2.a. Type any thing on  Command plate or don't do any thing
3. Press this key combination: Ctrl+P
4. If you start typing you will see it type inside the file instead in plate
5. You can't close the find plate with Esc key or click outside of fine plate. You have to use mouse and focus inside find plate input box than every things go normal. (You can close plate with Esc or click outside of the plate)

**Expected behavior:** 
On step 4 I expect to typing goes inside the find plate 

**Actual behavior:** 
On step 4 typing goes inside the opened file.
**Reproduces how often:** [What percentage of the time does it reproduce?]
All the times that I try. 100%
### Versions
OS: Fedora 27 4.13.16-302.fc27.x86_64
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by rsese** [comment] 2017-12-11 22:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14325. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-11 22:52 UTC
