### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 113Error: Cannot cal...

### ISSUE THREAD

**Issue by imadtg** [atom/atom#16705] opened 2018-02-09 10:24 UTC
[Enter steps to reproduce:]

1. select content of a file using CTRL + A
2. go to another program
3. go back to atom and do CTRL + C

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 113
Error: Cannot call function 'getPosition' on missing remote object 113
    at throwRPCError (C:\Users\ihaid\AppData\Local\atom\app-1.23.3\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\ihaid\AppData\Local\atom\app-1.23.3\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\ihaid\AppData\Local\atom\app-1.23.3\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At C:\Users\ihaid\AppData\Local\atom\app-1.23.3\resources\electron.asar\renderer\api\remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 113
Error: Cannot call function 'getPosition' on missing remote object 113
    at throwRPCError (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:691:34)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:725:42)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.23.3/resources/app/src/window-event-handler.js:189:32)
```

### Commands

```
     -0:49.5.0 core:select-all (input.hidden-input)
  2x -0:38.7.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
file-icons 2.1.16 
minimap 4.29.7 
teletype 0.6.0 
```

**Comment by rsese** [comment] 2018-02-09 19:21
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.  I also tried your repro steps but wasn't able to reproduce the error.  Just to confirm, can you consistently reproduce with those steps?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-02-09 19:21 UTC

**Comment by imadtg** [comment] 2018-02-09 21:20
apparently, i selected all and did copy but it did not work on the first time because when i went to the other program it pasted the wrong thing so i came back to atom and copied it again and went to the other program, when i went back to atom that happened, sorry if i did not give much detail but that's about what i can do
