### ISSUE TITLE
Uncaught TypeError: r.filter is not a function

### ISSUE THREAD

**Issue by zhangzhijing1995** [atom/atom#18426] opened 2018-11-12 11:12 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: r.filter is not a function

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: r.filter is not a function
    at Request._callback (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:717829)
    at Request.self.callback (/app.asar/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at /app.asar/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at /app.asar/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -8:09.6.0 window:increase-font-size (atom-pane.pane)
     -8:08.7.0 window:decrease-font-size (atom-pane.pane)
     -8:05.4.0 core:close (atom-pane.pane)
  2x -7:47.7.0 core:backspace (input.hidden-input)
     -7:33.1.0 core:confirm (input.hidden-input)
     -4:55.2.0 color-picker:open (input.hidden-input)
  5x -4:46.2.0 core:undo (input.hidden-input)
     -1:49 color-picker:open (span.syntax--constant.syntax--other.syntax--color.syntax--rgb-value.syntax--hex.syntax--css)
 15x -1:24.9.0 core:undo (input.hidden-input)
     -0:52.9.0 core:close (input.hidden-input)
  5x -0:38.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
color-picker 2.3.0 
intentions 1.1.5 
linter 2.2.0 
linter-markdown 5.2.2 
linter-ui-default 1.7.1 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.10.3 
minimap 4.29.9 
platformio-ide-terminal 2.8.4 
ruby-block 0.3.6 
```

**Comment by moeffju** [comment] 2018-11-12 12:52
Also happening with `1.32.2` on Win10 x64 v1803 (Build 17134.286).

**Comment by cachoalbornoz** [comment] 2018-11-12 12:53
Also happening with Ubuntu 18.04

**Comment by nicolasbettag** [comment] 2018-11-12 12:59
Also happening with 1.32.2 on macOS 10.14

**Comment by rsese** [comment] 2018-11-12 21:48
Thanks for contributing!

Based on the stack trace, I think this is a duplicate of https://github.com/atom/settings-view/issues/1052 - that issue has been closed by https://github.com/atom/settings-view/pull/1065 and the fix should be an in an upcoming release.

Also the error should be temporary so if you were having this problem earlier, please try again now.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-12 21:48 UTC

**Comment by berrylaw** [comment] 2019-01-07 08:43
Nice
