### ISSUE TITLE
Can't open the specified path on startup if --disable-gpu is appended 

### ISSUE THREAD

**Issue by harai** [atom/atom#15072] opened 2017-07-22 00:37 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom cannot open the specified path on startup if `--disable-gpu` is appended to the command.  Adding `--safe` to the command doesn't change anything.

![screenshot from 2017-07-22 09-35-06](https://user-images.githubusercontent.com/515636/28486777-1262f068-6ec1-11e7-8067-552b940a3b5d.png)

### Steps to Reproduce

1. Run `atom --disable-gpu .` in a directory.

**Expected behavior:** Atom opens the specified directory on startup.

**Actual behavior:** Atom opens a blank editor on startup.

**Reproduces how often:** everytime

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

`--disable-gpu` is necessary as a workaround for #14776.

**Comment by rsese** [comment] 2017-07-25 08:48
Thanks for the report!  I'm unable to reproduce in Ubuntu 16.04, what operating system are you running?  And just to confirm, without `--disable-gpu`, `atom .` does start Atom with the current directory as a project?

**Comment by harai** [comment] 2017-07-25 11:59
I have two Ubuntu 16.04 machines and both have this issue.  Without `--disable-gpu`, Atom opens the current directory as expected.

How about the following?

```
mkdir a b
cd a
atom --disable-gpu .  # Keep this window open
cd ../b
atom --disable-gpu .
```

In my case, the second one always opens a blank Atom, while the first one sometimes opens unrelated project.

**Comment by awilkins** [comment] 2017-08-02 12:56
Confirmed in 1.18 and 1.19 but they have different behaviours. 

1.18 opens a prior project folder set
1.19 just opens a blankness

Workaround : `--disable-gpu` wants to be the last parameter.

    atom . --disable-gpu  # Works as expected

If you have to clear up "open with" shortcuts use parameter insertion

e.g. for `.desktop` files

    [Desktop Entry]
    Name=Atom Beta
    Comment=A hackable text editor for the 21st Century.
    GenericName=Text Editor
    Exec=/usr/share/atom-beta/atom %F --disable-gpu
    Icon=atom-beta
    Type=Application
    StartupNotify=true
    Categories=GNOME;GTK;Utility;TextEditor;Development;
    MimeType=text/plain;

**Comment by rsese** [comment] 2017-08-02 20:43
I see why I couldn't reproduce before but I can now, thanks @harai for those updated steps.

> Workaround : --disable-gpu wants to be the last parameter.

ahhh thanks @awilkins :+1:  I thought this sounded familiar, looks like a duplicate of https://github.com/atom/atom/issues/14680.  So passing `--disable-gpu` as the last parameter should work @harai.

**Closed by rsese** 2017-08-02 20:43 UTC
Labels: more-information-needed, needs-reproduction
