### ISSUE TITLE
The project window does not open when click on project name

### ISSUE THREAD

**Issue by TonyLianLong** [atom/atom#16430] opened 2017-12-22 09:19 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The project window does not open when click on project name in the Reopen Project menu while no window is currently open.

### Steps to Reproduce

1. Open Atom
2. Close all the windows
3. File->Reopen Project->click on a project

**Expected behavior:** 
the project window opens

**Actual behavior:** 
nothing happens

**Reproduces how often:**
Every time

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

![image](https://user-images.githubusercontent.com/1451234/34292500-23d11ebc-e73c-11e7-8379-c9c309e50eda.png)

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.10
git 2.14.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

I guess it's because the command application:reopen-project [here](https://github.com/atom/atom/blob/11961b09ac492fb02466266241d716e1f9da0dc7/src/reopen-project-menu-manager.js) could not be executed when no window is open.

**Comment by rsese** [comment] 2017-12-22 22:11
Thanks for taking the time to contribute!

This is a duplicate of https://github.com/atom/atom/issues/12508 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-22 22:11 UTC
