### ISSUE TITLE
The "settings" view is named "preferences" in the menu

### ISSUE THREAD

**Issue by rondonjon** [atom/atom#8712] opened 2015-09-08 15:08 UTC
Different names for the same thing aren't intuitive. Could one term be chosen and then be used throughout the user interface?

**Comment by mnquintana** [comment] 2015-09-08 15:52
Thanks for the report! This looks like a duplicate of https://github.com/atom/settings-view/issues/80 – closing out in favor of that issue (which was addressed by https://github.com/atom/atom/pull/7086)

**Closed by mnquintana** 2015-09-08 15:52 UTC
