### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by Neighborwan** [atom/atom#15805] opened 2017-10-04 03:55 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At C:\Users\小帅\AppData\Local\atom\app-1.21.0\resources\app\node_modules\settings-view\lib\package-card.js:248

TypeError: Cannot read property 'version' of undefined
    at ~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/package-card.js:248:40
    at ~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/package-manager.js:333:24
    at exit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.21.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.21.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
  2x -1:45.6.0 markdown-preview:toggle (atom-pane.pane.active)
     -1:05.4.0 core:paste (div.placeholder-text)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-10-04 05:06
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/settings-view/issues/943. You may want to subscribe there for updates and if you have any steps to reproduce you can share, please comment in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-04 05:06 UTC

**Comment by Mangosir** [comment] 2018-01-13 02:36
Uncaught TypeError: Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
    at C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\node_modules\settings-view\lib\package-card.js:248:40
    at C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\node_modules\settings-view\lib\package-manager.js:333:24
    at exit (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
