### ISSUE TITLE
Atom keeps crashing when opening a file or project folder

### ISSUE THREAD

**Issue by CasperHK** [atom/atom#12079] opened 2016-07-01 08:04 UTC
Previously, I have select and want to delete some codes in the editor and it then crashed. If I try to relaunch Atom, it keeps craching. How can I fix the problem?

![2016-07-01 16_00_10-start](https://cloud.githubusercontent.com/assets/6957401/16515607/86c149a6-3fa5-11e6-842a-a725b9e9c57e.png)

**Comment by Ben3eeE** [comment] 2016-07-01 08:41
Please fill out the [provided issue template](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md). As it is now it is not possible to do anything about this because it lacks information.

In addition to this you can also upload the latest crash dump from `%LocalAppData%\Temp\Atom Crashes`.

**Comment by CasperHK** [comment] 2016-07-01 18:09
### Prerequisites

* [] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by CasperHK** [comment] 2016-07-01 18:21
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I have select some codes and want to delete some codes in the editor. The atom editor no response and showing the screen with codes not deleted just like the following.

![2016-07-02 02_13_26-logincard js e__users_user_documents_github_codespace_dev_v1 3_codespace ato](https://cloud.githubusercontent.com/assets/6957401/16530423/9ea20efc-3ffa-11e6-823d-7ac2f044c63f.png)

After a while, the following dialog is shown.

![86c149a6-3fa5-11e6-842a-a725b9e9c57e](https://cloud.githubusercontent.com/assets/6957401/16530473/de61779e-3ffa-11e6-8c68-e0809f5692c0.png)

Then, I open windows' Task Manager and kill the process and want to relaunch the app like this.

![2016-07-02 02_16_29-codespace](https://cloud.githubusercontent.com/assets/6957401/16530509/0bd522f2-3ffb-11e6-9d27-9989c092f39f.png)

But it keep showing me the following.

![86c149a6-3fa5-11e6-842a-a725b9e9c57e](https://cloud.githubusercontent.com/assets/6957401/16530524/1cd04316-3ffb-11e6-9bf6-b70e6ea5c04f.png)

I tried to repeat the step but got the same result.

I search the internet and found that someone may encounter the same error.
Link: https://discuss.atom.io/t/atom-keeps-crashing-when-opening-a-file-or-project-folder/23847

**Expected behavior:** [What you expected to happen]

Relaunch the app with normal function with out the error message.

**Actual behavior:** [What actually happened]

It keep giving me error message if I click `Reload`.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by lee-dohm** [comment] 2016-07-12 23:28
@CasperHK Can you reproduce this when running Atom in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by CasperHK** [comment] 2016-07-14 09:09
I cannot reproduce it in Safe Mode after I run the window installer.

**Comment by lee-dohm** [comment] 2016-07-14 20:43
So it is probably some package that you are running that is causing the initial problem. Additionally, using the Task Manager to kill Atom could be the reason why Atom gets into the wedged state that you're reporting. Instead, you should use the "Close Window" option. This allows Atom to exit cleanly.

See [the instructions on Safe Mode in the Flight Manual](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode) for help on how to track down which package might be causing the freezing problem. Please update us on what you find.

**Comment by eastwood** [comment] 2016-07-23 01:16
@CasperHK Can you provide a list of the packages that you're using?

**Comment by CasperHK** [comment] 2016-07-23 08:16
Here show you all the package I installed.
![2016-07-23 16_16_05-package list c__users_user_ atom atom](https://cloud.githubusercontent.com/assets/6957401/17076899/cd75e9e0-50f0-11e6-9eb3-79324edb4707.png)

**Comment by JoshEngebretson** [comment] 2016-08-01 17:07
1.9 still is a crashfest on Windows, within a couple minutes selecting a folder yields:

![crash](https://cloud.githubusercontent.com/assets/376203/17302170/c812706e-57cf-11e6-9940-4d986877541b.PNG)

**Comment by cbuteau** [comment] 2017-04-05 17:09
I am on 1.15 and experiencing this.
I don't have the hugest list of packages but I do have one that executes internal command line tools.

It is one specific directory that I had a lot of files open when I last closed it.

- [ ] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
 - [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
  - [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
  - [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
- [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

Eventually I went through your debugging manual and tried profiling startup.
I noticed the atom-ctags taking a long time to initialize and remembered I had installed it but it did not work...so I uninstalled it.

The point of my story is if you can get Atom to start elsewhere.  Review your packages and uninstall the ones you actually are not using.

**Comment by lee-dohm** [comment] 2017-04-05 17:25
Since all of these can't be reproduced in Safe Mode, I'm going to recommend that people check out [the section on Safe Mode in the Atom Flight Manual](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) for more information. If anyone runs into a problem like this that they can reproduce in Safe Mode, please open a new issue and fill out the template with all required information.

**Closed by lee-dohm** 2017-04-05 17:25 UTC
Labels: more-information-needed
