### ISSUE TITLE
Failed to spawn command /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper. Make sure /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper is installed and on your PATH

### ISSUE THREAD

**Issue by ericcirone** [atom/atom#7594] opened 2015-06-30 14:24 UTC
When opening Atom 1.0.0 to a new blank window with no project open, then go to preferences, an error occurs:
Failed to spawn command /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper. Make sure /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper is installed and on your PATH

The javascript error is:
Uncaught BufferedProcessError: Failed to spawn command `/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper`. Make sure `/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper` is installed and on your PATH

This is on OSX 10.10.3 and Atom 1.0.0. This has been happening for the past month or so.
![screen shot 2015-06-30 at 10 23 58 am](https://cloud.githubusercontent.com/assets/10419347/8433174/293b106e-1f12-11e5-91da-c48a52cc3447.png)

**Comment by Rulsky** [comment] 2015-07-18 07:08
Same issue for me

**Comment by budda** [comment] 2015-07-18 10:20
I get this when I re-open Atom 1.0.2 and I have some previously opened tabs re-open -- one of them being the settings tab.

```
Failed to spawn command /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper. Make sure /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper is installed and on your PATH
```

Interestingly going to the path i can see Atom Helper exists/installed.

Could it be triggered by any additional packages I've installed?

**Comment by Rulsky** [comment] 2015-07-18 13:05
I think it could be fixed by manual adding variable with this path, but I don`t know name of variable.
If anyone could point that for me I could try and reply with result.

**Comment by mslotema** [comment] 2015-08-07 08:47
I use Atom version 1.0.5 (it just got updated) and this problem arises when I install/enable **atom-ternjs** (currently on version 0.7.1). Disable it, and the error gows away. I've tried several combinations aof enabling and disabling extensions, but **ternjs** is the only one that causes trouble. So it seems.

**Comment by maxbrunsfeld** [comment] 2015-08-12 17:35
@budda @Rulsky Does this still happen if you open Atom with `atom --safe`?

**Comment by budda** [comment] 2015-08-12 23:53
@maxbrunsfeld using --safe does indeed stop the error appearing.

$ ./Atom --safe
2015-08-13 00:52:26.144 Atom[4775:115200] App load time: 651ms
[4775:0813/005228:INFO:CONSOLE(56)] "Window load time: 1452ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (56)
[4775:0813/005228:INFO:CONSOLE(659)] "EACCES: permission denied, symlink '/Applications/Atom.app/Contents/Resources/app/atom.sh' -> '/usr/local/bin/atom'", source: /Applications/Atom.app/Contents/Resources/app.asar/src/atom.js (659)
[4775:0813/005228:INFO:CONSOLE(664)] "EACCES: permission denied, symlink '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm' -> '/usr/local/bin/apm'", source: /Applications/Atom.app/Contents/Resources/app.asar/src/atom.js (664)
2015-08-13 00:52:36.353 Atom[4775:115339] Download completed to: file:///Users/mike/Library/Application%20Support/com.github.atom.ShipIt/update.GeoyEQs/download

**Comment by maxbrunsfeld** [comment] 2015-08-12 23:58
@budda could you report your list of installed packages (`apm list --installed`)? I'm going to close this out since it seems to be due to third-party packages.

**Closed by maxbrunsfeld** 2015-08-12 23:58 UTC
Labels: more-information-needed, uncaught-exception

**Comment by budda** [comment] 2015-08-13 00:05
@maxbrunsfeld no i can't because of #7956 I don't have apm to run without going poking around in the OSX package.

**Comment by maxbrunsfeld** [comment] 2015-08-13 00:06
Ah ok. Well can you run `/usr/local/bin/apm list --installed`?

**Comment by budda** [comment] 2015-08-13 00:07
$ /usr/local/bin/apm list --installed
-bash: /usr/local/bin/apm: No such file or directory

Computer says no.

**Comment by maxbrunsfeld** [comment] 2015-08-13 00:10
Sorry, pasted the wrong thing. Can you run `/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm list --installed`?

**Comment by budda** [comment] 2015-08-13 00:11
/Users/mike/.atom/packages (14)
├── angularjs-styleguide-snippets@0.7.2
├── atom-beautify@0.28.11
├── atom-ternjs@0.7.1
├── git-plus@5.3.4
├── jshint@1.3.10
├── jsonlint@1.1.2
├── linter-csslint@1.0.5
├── linter-php@1.0.3
├── minimap@4.12.3
├── minimap-bookmarks@0.1.0
├── minimap-git-diff@4.1.7
├── project-manager@1.15.11
├── todo-show@0.13.0
└── trailing-spaces@0.3.2

**Comment by maxbrunsfeld** [comment] 2015-08-13 00:13
Great, so there's already an issue reported on `atom-ternjs`. Subscribe to tststs/atom-ternjs#107 for updates.

**Comment by budda** [comment] 2015-08-13 00:20
done, thanks.

On 13 August 2015 at 01:13, Max Brunsfeld <notifications@github.com> wrote:

> Great, so there's already an issue reported on atom-ternjs. Subscribe to
> tststs/atom-ternjs#107 <https://github.com/tststs/atom-ternjs/issues/107>
> for updates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/7594#issuecomment-130487710>.
>



-- 
http://about.me/mike.carter

**Comment by mslotema** [comment] 2015-08-13 07:58
Something weird. I am unable to reproduce it. It had bugged me for a day, but now: nothing.
`atom --safe` works fine too. As far as I can see, I have the same versions of atom and ternjs I had when I reported this bug. 
Can be closed. Sorry to have bothered you with it.

**Comment by psrinivasrao** [comment] 2016-07-30 13:20
I have same issue with Atom 1.8.0. After installing few packages. I am getting error with popup window

Failed to spawn command emcc. Make sure emcc is installed and on your PATH

<img width="463" alt="sc1" src="https://cloud.githubusercontent.com/assets/10720242/17270666/0d5113c4-5686-11e6-9bec-e19b6604e8c7.png">

Uncaught BufferedProcessError: Failed to spawn command `emcc`. Make sure `emcc` is installed and on your PATH

Issue resolved when  i disabled "Linter Emscripten" packages.
