### ISSUE TITLE
Prompts for restart when certain core settings aren't default

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#19323] opened 2019-05-13 16:53 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If one of the core setting that are configured to prompt for a restart are changed from their default value then Atom will prompt for a restart every time it starts up.

### Steps to Reproduce

1. Change a core setting from [the following list](https://github.com/atom/atom/blob/b79d9088e21970f0dd1d05ed0e2a27765d4b6dd4/src/main-process/atom-application.js#L283-L285) to a non-default value:
    * `core.titleBar`
    * `core.colorProfile`
    * `core.fileSystemWatcher`
2. Restart Atom

**Expected behavior:** [What you expect to happen]
No prompt to restart Atom on launch.

**Actual behavior:** [What actually happens]
Prompts to restart Atom on _every_ launch, regardless of how many times you restart it.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time.

### Versions

OS: Windows 10 x64
```
Atom    : 1.39.0-nightly2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.39.0-nightly2
python 2.7.15
git 2.19.1.windows.1
visual studio 2015
```

### Additional Information

N/A

**Comment by nathansobo** [comment] 2019-05-13 21:51
@Arcanemagus hey, do you think you could give this another try once we get a dev build that includes https://github.com/atom/atom/pull/19325?

If you're on Windows, once this [AppVeyor build goes green](https://ci.appveyor.com/project/Atom/atom/builds/24515900) (modulo any flakiness), you should be able to pull down an artifact from the [dev channel](https://atom.io/download/windows_x64_zip?channel=dev). I couldn't reproduce your issues once that fix was in, and I couldn't even *start* Atom before https://github.com/atom/atom/pull/19321 was merged, so I'm curious where the latest fixes leave things for you.

**Comment by Arcanemagus** [comment] 2019-05-13 23:15
I'm still seeing the same thing on that build. Is there any additional information I can provide?

**Comment by nathansobo** [comment] 2019-05-14 23:04
Any better after the latest changes on master?

**Comment by Arcanemagus** [comment] 2019-05-15 16:39
Tested with the `atom-x64-windows.zip` build from [here](https://github.visualstudio.com/Atom/_build/results?buildId=40633) (https://github.com/atom/atom/commit/216404d04323a794fc3b6c3ea97df693e0a1c32d) and I'm still seeing this.

**Comment by 50Wliu** [comment] 2019-05-16 14:58
Can confirm what @Arcanemagus is seeing.

**Comment by nathansobo** [comment] 2019-05-16 18:33
We're not going to take this path and I have changed the default back to `nsfw`.

**Comment by Arcanemagus** [comment] 2019-05-16 18:43
Although the default has been changed back to `native`, this still happens on builds after #19345 was merged.

**Comment by Arcanemagus** [comment] 2019-05-16 21:31
I added some logging to the `onDidChange` binding and it looks like the value is being initialized to the default value (`native`) and _then_ changed to the user's custom value (`atom` in my case), which is triggering the `onDidChange` event.

**Comment by Arcanemagus** [comment] 2019-05-16 21:39
Updated the description: This actually is only tangentially related to the file system watcher changes.

It turns out that _any_ of [these settings](https://github.com/atom/atom/blob/b79d9088e21970f0dd1d05ed0e2a27765d4b6dd4/src/main-process/atom-application.js#L283-L285) will **always** prompt for a restart if they are changed from the default value.

We likely need to put this event subscription to somewhere in the startup process after user settings have first been applied.

**Comment by nathansobo** [comment] 2019-05-17 10:34
I think this was introduced in #19246. On Windows, we're no longer `await`ing loading of the config file for performance reasons since it's really slow on Electron 2. I have a fix in the works, but I need to revert the `@atom/notify` stuff before building on top of it. I'll need to cherry-pick my fix to beta later today.

**Closed** 2019-05-17 15:41 UTC
Labels: bug, regression, triaged
