### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by Garfield-Finch** [atom/atom#14008] opened 2017-03-15 02:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -1:30.6.0 tree-view:remove (div.header.list-item.project-root-header)
     -1:17.6.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
  3x -0:58 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-language-rust 0.12.1 
build 0.67.0 
build-cargo 2.0.0 
busy 0.7.0 
language-rust 0.4.9 
linter 1.11.18 
linter-rust 0.7.2 
minimap 4.25.7 
my-package 0.0.0 
racer 0.20.0 
script 3.14.0 
```

**Comment by rsese** [comment] 2017-03-15 18:21
Can you confirm what you were doing when you saw the error?  Also, is the error reproducible?

**Comment by davidolrik** [comment] 2017-03-21 12:41
@Garfield-Finch Are you by any chance behind a proxy?

**Comment by vtambourine** [comment] 2017-03-22 10:44
I have the similar problem on Mac, while trying to connect to remote host via Nuclide:

> Unable to connect to server
The server successfully started, but we were unable to connect.
Original error message:
 tunneling socket could not be established, statusCode=503

**Comment by ryanerwin** [comment] 2017-04-07 02:58
I am behind a proxy and getting the same error when I open the Settings/Packages screen. "Uncaught Error: tunneling socket could not be established, statusCode = 503.

The error is **not reproducible** for me. After closing Atom and reopening, then going to Settings / Packages, I'm unable to get the same stacktrace.

```Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (C:\Users\ryan\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\tunnel-agent\index.js:165:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by rsese** [comment] 2017-05-04 22:22
> I have the similar problem on Mac, while trying to connect to remote host via Nuclide:

@vtambourine - looks like you have things sorted out for your issue /cc https://github.com/facebook/nuclide/issues/1064#issuecomment-292578726.

> The error is not reproducible for me. After closing Atom and reopening, then going to Settings / Packages, I'm unable to get the same stacktrace.

Thanks for reporting and letting us know you can't reproduce @ryanerwin - if you end up with a reproducible case, let us know.

**Comment by rsese** [comment] 2017-05-04 22:23
Thanks again for your issue @Garfield-Finch!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/14008#issuecomment-286834476. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2017-05-04 22:23 UTC
Labels: more-information-needed, uncaught-exception
