### ISSUE TITLE
Uncaught TypeError: Invalid Point: (1465, NaN)

### ISSUE THREAD

**Issue by SKegler** [atom/atom#18813] opened 2019-02-07 20:39 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (1465, NaN)

```
At C:\Users\Shakeia\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

TypeError: Invalid Point: (1465, NaN)
    at Function.t.exports.Point.assertValid (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:43907)
    at DisplayLayer.translateScreenPosition (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:85014)
    at DisplayMarkerLayer.t.exports.DisplayMarkerLayer.translateScreenPosition (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1092949)
    at DisplayMarker.t.exports.DisplayMarker.setHeadScreenPosition (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:3173826)
    at changePosition (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:521833)
    at Cursor.changePosition (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:530377)
    at Cursor.setScreenPosition (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:521799)
    at Cursor.moveLeft (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:524621)
    at modifySelection (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:534433)
    at Selection.modifySelection (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:547515)
    at Selection.selectLeft (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:534401)
    at Selection.backspace (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:538925)
    at mutateSelectedText.t (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:16061)
    at getSelectionsOrderedByBufferPosition.map (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:491881)
    at TextEditor.transact (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:16113)
    at TextEditor.backspace (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:16037)
    at TextEditor.e.(anonymous function) [as backspace] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:259365)
    at TextEditor.core:backspace (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:302187)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:307928
    at TextBuffer.transact (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:491881)
    at TextEditor.transact (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:24215)
    at HTMLElement.s.(anonymous function) (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:307871)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:350017)
```

### Commands

```
     -4:11.5.0 tree-view:duplicate (span.name.icon.icon-file-text)
     -4:03.0 core:confirm (input.hidden-input)
     -3:53.9.0 tree-view:copy-full-path (span.name.icon.icon-file-text)
  5x -1:02.6.0 core:delete (input.hidden-input)
     -0:43.6.0 core:move-up (input.hidden-input)
  3x -0:42.7.0 core:delete (input.hidden-input)
     -0:40.5.0 core:backspace (input.hidden-input)
     -0:33.4.0 core:undo (input.hidden-input)
     -0:30.2.0 core:delete (input.hidden-input)
     -0:29.8.0 core:backspace (input.hidden-input)
     -0:23.9.0 core:delete (input.hidden-input)
  2x -0:21.7.0 core:move-down (input.hidden-input)
 21x -0:19.1.0 core:move-left (input.hidden-input)
     -0:16.8.0 core:move-right (input.hidden-input)
  4x -0:16.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
teletype 0.13.3 
```

**Comment by rsese** [comment] 2019-02-07 21:49
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/18725 so you can subscribe there for updates if you'd like.  If you have steps to reproduce, please let us know in https://github.com/atom/atom/issues/18725.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-07 21:49 UTC
Labels: duplicate
