### ISSUE TITLE
 Atom API reference - Include class name in title

### ISSUE THREAD

**Issue by nn2242** [atom/atom#7042] opened 2015-05-31 21:36 UTC
Would be nice if the title for the API reference pages gave some context to the class it's referencing. The following is a screenshot of the tabs I see in Firefox (Safari gives even less context because the icon is missing). All of them just say "Atom".

![screen shot 2015-05-31 at 5 29 30 pm](https://cloud.githubusercontent.com/assets/2596124/7904012/f1380a46-07ba-11e5-8fd2-7e8c0f82ac57.png)

The left tab has the API reference for Color, the middle for CommandRegistry, and the right for TextBuffer, but it's unclear without selecting them which one's which. 

Propose something along the lines of "Atom - TextBuffer API" or even just "Atom - TextBuffer" for clarity. 

/cc @thedaniel :memo:

**Comment by mnquintana** [comment] 2015-05-31 21:48
Thanks for the suggestion! This is a duplicate of https://github.com/atom/atom/issues/6624 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-31 21:48 UTC
