### ISSUE TITLE
Unable to disable 80 char guide

### ISSUE THREAD

**Issue by jglovier** [atom/atom#11782] opened 2016-05-18 12:47 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
  - The `atom` command and `apm` doesn't work on my new machine.
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
  - See note below
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I'm getting Atom setup on a new machine. I'm trying to get rid of the 80 character guide, but cannot seem to find a way to disable it. 

I thought it used to be in Settings as a checkbox with a value you could adjust for the length, but either my memory is incorrect, or it has been changed. I also checked under the View menu, but there is no toggle for it there, either.

@shiftkey pointed out that on his machine setting `Preferred Line Length` to `0` seems to be doing it, but for me that doesn't actually work as setting a `0` value results in Atom automatically changing the value to `1`, which just overlays the line at the 1 character column.

Even more strange about the previous point is that I don't even have `Soft Wrap At Preferred Line Length` checked, so if anything I would assume that `Preferred Line Length` should not be in effect until this is checked.

### Steps to Reproduce

1. Download Atom from Atom.io on a new machine.
2. Open a file.
3. Attempt to turn off the 80 character guide.

**Expected behavior:** I expected there to be a checkbox in `Settings` or a toggle option in the `View` menu to allow me to turn the guide on or off.

**Actual behavior:** I found no way to turn it off after quite some time of looking, resorted to Twitter assuming I was Doing It Wrong™, and it was suggested this might be a bug.

### Versions

My Atom build is `1.7.3` and I'm on `OSX 10.11.5`

---

Note: This is technically a dupe of https://github.com/atom/settings-view/issues/790, but @shiftkey pointed out that the code is actually [in this repo](https://github.com/atom/atom/blob/ca041384fecf8a17bae078d2813fc94a90498bb8/src/config-schema.coffee#L174-L178) so opening here too unsure of where this actually belongs. :grin:

**Comment by Ben3eeE** [comment] 2016-05-18 12:53
Duplicate of https://github.com/atom/settings-view/issues/783?

As a temporary workaround maybe you could try an extremely high value like 150000?

**Comment by jdiago** [comment] 2016-05-18 15:29
There's a package called `wrap-guide` that you can disable to make the line disappear.

**Closed** 2016-05-18 15:40 UTC

**Comment by jglovier** [comment] 2016-05-19 21:34
>There's a package called wrap-guide that you can disable to make the line disappear.

@jdiago thanks - yeah @simurai  pointed that out to me on Twitter. To me the issue really though is about how undiscoverable it is to turn it off, even for a seasoned Atom user (who simply happens to be setting up on a new machine). 

It's not clear that the settings where you define the guide are related to a package you need to disable. It would be great to be able to simply turn it off from the Settings view, or at least a hint to let you know if you want to turn it off entirely you need to disable the package.

IMO ideally the wrap guide would be something you can toggle on or off from the View menu, perhaps directly under `Toggle Soft Wrap` as `Toggle Soft Wrap Guide`.

**Comment by simurai** [comment] 2016-05-21 01:33
> or at least a hint to let you know if you want to turn it off entirely you need to disable the package.

There is now a PR to add a note: https://github.com/atom/atom/pull/11804
