### ISSUE TITLE
Atom "reopen project" not working after crash

### ISSUE THREAD

**Issue by Daijobou** [atom/atom#17086] opened 2018-04-05 18:04 UTC
Windows 10
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python
git 2.7.0.windows.1
visual studio

Once atom crashes its destroy my project too. After restart atom (after crash) its open only a new editor with "untitled" file. Go to menu "reopen project" and click on my last project... nothing happen. So I must create a new project with "add project folder". This happen now three times with 1.25.0. :(

With "add project folder" its restore my old project with last opened files, but... I use Vertical Tabs package and have set "right side", but its open it with left side. After go in settings for this package, I uncheck "right side" and set again... working now. maybe thats not a bug in this package, so I report its here too. Bug report exists in package too https://github.com/tiger4th/vertical-tabs/issues/17

**Comment by rsese** [comment] 2018-04-05 19:42
Thanks again for reaching out - without specific steps to reproduce (e.g. what steps cause Atom to crash for you?), it's hard to investigate further.   If you restart Atom in safe mode after it crashes, does that make any difference?

I'm going to go ahead and close the issue since it doesn't seem actionable by the team right now but If you have specific steps to reproduce the crash in safe mode, let me know and we can take a look.

**Closed by rsese** 2018-04-05 19:42 UTC

**Comment by rsese** [comment] 2018-04-05 23:02
> How should I reproduce a completely random crash I not know the reason? That problem is not thats here is a crash. The problem is after a crash the "project" is missing and can't be re-open

Sorry if I wasn't clear but yes, this is what I was trying to say - we can't reproduce the problem either because there are no steps for us to reproduce the crash in the first place, which would then let us see if we can reproduce the problem with reopening a project.

> When you tell me what information can help, I gladly to help here. 

As I mentioned above, specific steps that we can use to reproduce the issue is what would help - so if the problem with reopening a project only reproduces after Atom crashes but the crash is random for you with no steps to reproduce, that's not enough information for us to try and reproduce the problem you're reporting.

**Comment by chefren** [comment] 2018-11-02 00:00
I am seeing a similar issue, and the fix proposed above did not help.

Is there any log from atom that I can put here so someone can see what is happening?

Atom simply shows a black window and is not responsive when trying to reopen an old project. What is the way to "reset" or clear info related to a folder/project, so it would be reloaded?

**Comment by rsese** [comment] 2018-11-02 22:09
> the fix proposed above did not help.

@chefren - feel free to post on the [message board](https://discuss.atom.io/) describing what steps you tried (as well as what version of Atom you're running and what operating system) and what the result is.  You can @ mention me so we can take a look together.

**Comment by mnadolny** [comment] 2019-04-18 21:02
It's been over a week now and i still can't use the reopen project feature. I click the reopen project from file and i get no response. Not sure what started it but i've tried uninstalling and reinstalling plus cleaning out the caches. Please help!

Mac 10.14.4 - Atom 1.36.0

**Comment by wind39** [comment] 2019-04-18 21:55
Hi,

Same here, using Mac 10.14.4 and Atom 1.36.0. "Reopen project" feature does nothing. Tried the fix proposed above but it didn't help.

Regards,

William

**Comment by bdavis-aabo** [comment] 2019-04-18 22:11
I'm experiencing the same issue, the "reopen project" feature doesn't do anything. I'm on Mac OSX 10.14.4 and Atom 1.36.0

**Comment by rsese** [comment] 2019-04-19 00:28
@mnadolny @wind39 @bdavis-aabo - the issue you're seeing is different than this report and is specific to 1.36.0 on macOS and is being tracked here:

https://github.com/atom/atom/issues/19149

The team is investigating but you can downgrade to 1.35.1 for now or manually open projects with <kbd>Cmd+O</kbd> [1].

[1]: https://github.com/atom/atom/issues/19149#issuecomment-482714996

**Comment by wind39** [comment] 2019-04-19 15:47
Hi @rsese ,

Thanks for your response.

I understand this is fixed in 1.37 (beta). I can live with using `Cmd+O` while waiting for 1.37 :)

Best regards,

William

**Comment by Ahmed-Ullah** [comment] 2019-04-20 14:42
I have experienced the problem

**Comment by wind39** [comment] 2019-04-26 11:35
Hi @rsese ,

Just to let you know that I installed 1.36.1 and it completely fixed the problem!

Thank you very much and keep up the good work :)

William
