### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by jplatte** [atom/atom#11935] opened 2016-06-08 12:21 UTC
This just popped up a few minutes after starting and using Atom today, I don't think I did anything special. Feel free to close this if the automatically generated debug info isn't usable on its own.

**Atom Version**: 1.8.0
**System**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
     -0:32.5.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:32.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:25.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:15 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:13.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:10.5.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:08.8.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:08.0 pane:show-next-recently-used-item (atom-text-editor.editor.is-focused)
     -0:07.3.0 pane:move-active-item-to-top-of-stack (atom-text-editor.editor.is-focused)
     -0:04.4.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-pep8",
      "ide-purescript"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 90,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.2.13
autocomplete-clang, v0.9.3
autocomplete-cmake, v0.3.1
build-make, v0.10.0
editorconfig, v1.4.1
ide-haskell-cabal, v1.4.0
language-autotools, v2.0.1
language-capnproto, v0.3.0
language-cmake, v0.1.4
language-cpp14, v0.6.1
language-diff, v0.4.0
language-haskell, v1.7.16
language-nginx, v0.6.1
language-purescript, v0.7.0
language-rust, v0.4.6
linter, v1.11.4
linter-clang, v3.4.4
linter-cppcheck, v0.2.0
linter-jshint, v2.1.0
linter-rust, v0.4.6
merge-conflicts, v1.4.4
racer, v0.20.0
rust-api-docs-helper, v0.5.1
seti-icons, v1.2.1
svg-preview, v0.7.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-06-08 13:38
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-08 13:38 UTC
