### ISSUE TITLE
 File name input in Japanese does not work well

### ISSUE THREAD

**Issue by sinofseven** [atom/atom#13251] opened 2016-11-17 02:33 UTC
## Environment
os: windows 7 
language: Japanese
atom: 1.12.3

## What is going on
If you press the Enter key to confirm the Japanese Kanji conversion by entering the file name, the file name will be confirmed.
Previously I was able to press Enter to confirm kanji conversion.

**Comment by ungb** [comment] 2016-11-21 21:53
Hey @sinofseven,

I tried reproing this in Windows with Atom 1.12.5, and wasn't able to repro the issue, but I wasn't exactly sure the repro steps and which scenario you were seeing this issue in.  

Here's a gif of what I tried, let me know if it's a different scenario you are seeing this issue in.

![windowsjp](https://cloud.githubusercontent.com/assets/5624870/20502170/c3b093e6-aff1-11e6-8c3b-b56d0816950d.gif)

**Comment by sinofseven** [comment] 2016-11-22 06:13
Thanks, @ungb , your replay.

I tried one more today on atom 1.12.4.
It did not reappear then.
It seems to be revised in 1.12.4.

I am sorry to have troubled you.

**Comment by Ben3eeE** [comment] 2016-11-22 07:24
@sinofseven Ah, then this is a duplicate of https://github.com/atom/atom-keymap/issues/172#issuecomment-260595957. Thank you for your report. This has been fixed in Atom 1.12.4.

**Closed by Ben3eeE** 2016-11-22 07:24 UTC
Labels: more-information-needed
