### ISSUE TITLE
Can't install packages: Fails with ssl handshake failure

### ISSUE THREAD

**Issue by maxh65000** [atom/atom#17148] opened 2018-04-16 10:08 UTC
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Installing a package results in the following cryptic SSL error:
```
Request for package information failed: write EPROTO 101057795:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:openssl\ssl\s3_pkt.c:1493:SSL alert number 10
101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
 (EPROTO)
```

### Steps to Reproduce

1. Open settings
2. Install
3. Find a package (official or non-official)
4. Click "Install"

Alternate:

1. Open a terminal
2. `apm install any-package-name-here`

**Expected behavior:**

The package installs successfully.

**Actual behavior:**

A strange error is shown.
```
Request for package information failed: write EPROTO 101057795:error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message:openssl\ssl\s3_pkt.c:1493:SSL alert number 10
101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
 (EPROTO)
```

**Reproduces how often:** 

Every time. I can't install packages.

### Versions

OS: Windows 10 Version	10.0.16299 Build 16299
`atom --version`: 
```
Atom    : 1.25.1
Electron: 1.7.11
Chrome: 58.0.3029.110
Node: 7.9.0
```
`apm --version`
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.1
python 3.6.5
git 2.16.2.windows.1
visual studio
```

### Additional Information

I'm not behind a proxy or VPN of any kind. I have tried:

- Restarting atom
- Rebooting
- Uninstalling atom & reinstalling
- Deleting `.atom` and Atom's AppData folders
- System reset
- Installing atom as a different user not linked to a domain.
- Opening `https://atom.io/api/packages/package-name-here` in a web browser (works fine)
- Installing python, node.js, and visual studio.

**Comment by rsese** [comment] 2018-04-16 18:06
Thanks for the report!

Based on the error message, this looks like a duplicate of https://github.com/atom/atom/issues/16646 (which was closed in favor of https://github.com/atom/settings-view/issues/924).  The workaround for now is to use the 32-bit version of Atom as mentioned in atom/settings-view#924 (comment).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-16 18:06 UTC
