### ISSUE TITLE
Can't Start Atom after package update Ubuntu

### ISSUE THREAD

**Issue by audrummer15** [atom/atom#11263] opened 2016-03-24 16:31 UTC
### Description

After allowing Ubuntu 14 to update a list of packages, Atom no longer succeeds in starting up.

### Steps to Reproduce

1. Install the updates for the following packages.
2. Try to start Atom

Packages updated:
![updatedpackages](https://cloud.githubusercontent.com/assets/1392689/14023749/d6b45826-f1b3-11e5-936d-e1191b77edd5.png)

**Expected behavior:** Atom starts up normally.

**Actual behavior:** The following screen is shown: 
![atomstartup](https://cloud.githubusercontent.com/assets/1392689/14023732/bf9f8980-f1b3-11e5-9bef-7ddc1cf62918.png)

### Versions

atom 1.6.0

**Comment by tachyons** [comment] 2016-03-25 04:42
seems duplicate #10819

**Comment by thomasjo** [comment] 2016-03-25 11:46
Yeah, this seems like a duplicate of #10819.

**Closed by thomasjo** 2016-03-25 11:46 UTC
