### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by busterbeam** [atom/atom#17753] opened 2018-07-27 15:32 UTC
I just opened, it up and then uninstalled linter as it was saying that was the problem.  Please fix

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\buste\AppData\Local\atom\app-1.28.2\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:328

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:328:31)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:140:22)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.28.2/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor-component.js:881:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor-component.js:385:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor-component.js:275:16)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor-component.js:1560:59)
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
build 0.70.0 
busy-signal 1.4.3 
ide-java 0.8.3 
intentions 1.1.5 
script 3.18.1 
```

**Comment by steveward** [comment] 2018-07-27 17:43
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16892 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by steveward** 2018-07-27 17:43 UTC
