### ISSUE TITLE
Bash Completion for Atom Package Manager (apm)

### ISSUE THREAD

**Issue by pabloab** [atom/atom#13826] opened 2017-02-15 18:49 UTC
### Description

Right now fresh install of Atom doesn't give to apm bash autocompletion capabilities.

### Steps to Reproduce

1. Write on terminal ``apm ins``[TAB]

**Expected behavior:** autompleted: ``apm install``

**Actual behavior:** Nothing happens while pressing [TAB].

The good news is [another user had already fix this](https://github.com/vigo/apm-bash-completion).

**Comment by rsese** [comment] 2017-02-16 06:04
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/apm/issues/452. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-02-16 06:04 UTC
Labels: duplicate

**Comment by pabloab** [comment] 2017-02-16 16:38
Sorry I missed that issue. Thanks, I just post a message there, they do it for Mac but still not for Linux.
