### ISSUE TITLE
Jump directly to first result when searching

### ISSUE THREAD

**Issue by jancborchardt** [atom/atom#6417] opened 2015-04-17 14:31 UTC
1. Open a file
2. Use ctrl+f to search
3. Type in your search term

What happens next:
You see `x results found for 'search term'` and need to manually press the find button go to the first result. Or you need to know you can press enter for that.

What I’d expect instead:
While typing, the view automatically jumps to the first result.

**Comment by izuzak** [comment] 2015-04-17 14:35
Thanks for the feedback. :mag: I think this is a duplicate of https://github.com/atom/find-and-replace/issues/329 so I'll close this in favor of that issue. Please subscribe to that other issue for updates.

**Closed by izuzak** 2015-04-17 14:35 UTC

**Comment by jancborchardt** [comment] 2015-04-17 14:42
Thank you! Subscribed there, still need to get accustomed to where which issues are tracked.
