### ISSUE TITLE
Atom does not rembember URI handler setting

### ISSUE THREAD

**Issue by wiggisser** [atom/atom#16404] opened 2017-12-19 12:14 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom does not remember the URI handler setting and keeps asking me if I want to register atom as default uri handler for atom:// uris, despite me always choosing "no, never"

### Steps to Reproduce

1. Start Atom
2. Click "no, never" on the question about registering the URI handler
3. Quit Atom
4. Start Atom again. 

**Expected behavior:** 

If I click "no, never" I don't want to be asked again.

**Actual behavior:** 

It asks with every fresh start of atom

**Reproduces how often:** 

100%

### Versions

Atom 1.23.1 ia32 on Windows 8.1

**Comment by rsese** [comment] 2017-12-19 18:40
Thanks for taking the time to contribute!

This is a duplicate of https://github.com/atom/atom/issues/16201 and fixed in https://github.com/atom/atom/issues/16201 - the fix will be available in a future release.

--- 

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-19 18:40 UTC
