### ISSUE TITLE
node v4

### ISSUE THREAD

**Issue by Zverushko** [atom/atom#8823] opened 2015-09-17 13:50 UTC
hello!
in my arch node version is 4.0
and atom not build

do you plan to support v4? 
thx!

**Comment by Zverushko** [comment] 2015-09-17 14:24
i download node v10.9 and replace /usr/bin/node 
atom build success and get node v10.40 (save in /usr/share/atom/resource/bin)
a remove v10.9 and back v4 in /usr/bin/node

**Comment by 50Wliu** [comment] 2015-09-17 23:49
Duplicate of #8508, please subscribe there for updates.

**Closed by 50Wliu** 2015-09-17 23:49 UTC
