### ISSUE TITLE
Uncaught Error: kill EPERM

### ISSUE THREAD

**Issue by dlewand691** [atom/atom#22033] opened 2021-03-15 15:27 UTC
[Enter steps to reproduce:]

1. Not sure what I did, it just started popping up. Have to quit Atom and restart it.
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: kill EPERM

```
At events.js:177

Error: kill EPERM
    at ChildProcess.kill (internal/child_process.js:479:26)
    at Task.terminate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:44165)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:42537
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43875
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43716
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191622)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:42817)
    at ChildProcess.emit (events.js:200:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

### Commands

```
     -0:08.1.0 editor:consolidate-selections (input.hidden-input)
     -0:08.1.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-scss 1.3.1 
atom-alignment 0.13.0 
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-css-clean 2.24.1 
atom-ftp-editor 0.5.0 
atom-ide-ui 0.13.0 
atom-increment 0.3.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-panda-syntax 0.18.0 
atom-prettify 0.1.3 
atom-snippets 0.1.1 
atom-zurb-foundation 2.2.0 
atom-zurb-foundation-jade 1.2.0 
auto-update-packages 1.0.1 
autocomplete 0.47.0 
autocomplete-paths 2.13.0 
block-selection-mode 0.3.0 
busy-signal 2.0.1 
change-case 0.6.5 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
code-dictation 0.0.13 
color-picker 2.3.0 
column-select 1.0.1 
comment-down 0.1.1 
comment-headers 2.15.0 
copy-path 0.5.1 
counter 0.3.5 
csscomb 0.3.1 
drag-relative-path 1.2.3 
emmet 2.4.3 
expand-region 0.5.0 
expand-selection-to-quotes 0.11.0 
fold-functions 0.11.0 
fold-lines 0.2.2 
ftp-remote-edit 0.18.1 
git-plus 8.7.1 
hey-pane 1.2.0 
highlight-selected 0.17.0 
html2jade-plus 1.0.0 
hyperclick 0.1.5 
ide-css 0.3.5 
incr 0.2.1 
increment-me 0.4.1 
increment-selection 0.3.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
jshint 1.8.6 
language-pug 0.0.22 
line-count-status 0.0.3 
linter 3.3.0 
linter-eslint 8.6.2 
linter-sass-lint 1.9.0 
linter-scss-lint 3.2.1 
linter-stylelint 4.5.1 
linter-ui-default 3.3.0 
lipsum 0.1.0 
local-history 4.3.1 
material 2.2.0 
material-design-syntax 3.1.2 
material-syntax 0.6.1 
min-ui 0.0.4 
minimap 4.39.10 
minimap-codeglance 0.4.7 
minimap-highlight-selected 4.6.5 
minimap-pigments 0.2.2 
minimap-titles 1.15.0 
multi-cursor 3.0.0 
multi-cursor-increment 0.1.1 
multi-cursor-plus 1.2.0 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
northem-atom-ui 2.1.0 
northem-dark-atom-syntax 2.1.0 
northem-dark-atom-ui 2.1.0 
nyan-indent 0.9.8 
pane-layout-plus 0.7.4 
pane-split-moves-tab 0.1.0 
pigments 0.40.6 
prettier-atom 0.60.1 
preview-on-treeview 1.0.0 
project-manager 3.3.8 
release-notes 0.53.0 
remember-folds 0.3.0 
remote-ftp 2.2.4 
remote-sync 4.1.8 
scroll-sync 0.2.4 
scroll-through-time 0.3.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
SFTP-deployment 1.0.2 
simple-align 0.2.0 
smart-quotes-plus 3.0.1 
snippet-generator 0.3.2 
Solis 1.2.0 
sort-css 0.3.0 
sort-lines 0.19.0 
split-diff 1.6.1 
Stylus 3.2.0 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 5.2.7 
TabNine 3.0.2 
teacode-atom-helper 1.2.5 
teletype 0.13.4 
tree-view-copy-relative-path 1.2.0 
tree-view-sort 0.12.1 
underline-trailing-whitespace 1.4.2 
wordcount 3.2.0 
```

**Comment by darangi** [comment] 2021-03-23 11:42
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/7885. You may want to subscribe there for updates - if you have any consistent steps to reproduce in safe mode, please let us know in the issue!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by darangi** 2021-03-23 11:42 UTC
