### ISSUE TITLE
Open folder not shown and text on open files are erased after machine reboot

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [atom/atom#13325] opened 2016-11-25 01:23 UTC
### Description

Open folder not shown and text on open files are erased after machine reboot.
Fortunately when I close the files it prompts to save. I can not save and reopen the files to reload my data.

### Steps to Reproduce

1. reboot the machine while atom is open
2. start atom

**Expected behavior:**  To have the previously open folder to be open

**Actual behavior:** Open folder not shown and text on open files are erased after machine reboot

### Versions
Atom    : 1.12.4
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

OS - Ubuntu 16.04 LTS

**Comment by greenyx** [comment] 2016-12-09 10:57
This occurs when the Linux Drive containing the Files is not yet mount, on mounting it works as expected

**Comment by lee-dohm** [comment] 2017-01-29 05:35
If this is related to a mounted drive as @greenyx says, then this is a duplicate of https://github.com/atom/atom/issues/11797. Was this on a mounted drive @ShanikaEdiriweera?

**Comment by ShanikaEdiriweera** [comment] 2017-01-29 06:09
Yes I run both windows and ubuntu on my machine. I was working with files on a mounted drive.

**Comment by lee-dohm** [comment] 2017-01-29 17:10
Thanks @ShanikaEdiriweera, I'm following up with the dev team on how this could have happened.

**Comment by iolsen** [comment] 2017-01-30 17:51
@ungb can you reproduce this?

**Comment by ungb** [comment] 2017-02-06 20:13
> This occurs when the Linux Drive containing the Files is not yet mount, on mounting it works as expected

@iolsen I can't repro this issue when the drive is mounted.  When it's not mounted I am seeing the issue where it opens atom with all the tabs open but all the files are empty which makes it seem like there's data loss but once you put the drive back in it works.  

When the drive is not mounted we should probably either warn the user that we attempted to open their folder from a location that can't be found, or open a blank editor.  

Open folder from mounted drive and open a few files:
![image](https://cloud.githubusercontent.com/assets/5624870/22664413/72beb17e-ec65-11e6-9be1-62a9bb558f1f.png)


Opening Atom when drive is unmounted
![image](https://cloud.githubusercontent.com/assets/5624870/22664389/57c8bffe-ec65-11e6-8da2-802697a27409.png)

**Comment by lee-dohm** [comment] 2017-02-06 20:17
Thanks for the work reproducing the problem @ungb :bow:

**Comment by killthekitten** [comment] 2017-09-09 16:48
Any progress on this? Need any help? It has wiped my code a minute ago :) @iolsen @lee-dohm

**Comment by iolsen** [comment] 2017-09-11 16:55
Thanks for the reminder. I've bumped the priority on this.

**Closed** 2017-09-20 18:21 UTC
Labels: data-loss, triaged

**Comment by smashwilson** [comment] 2017-09-20 18:36
#15681 addresses this by smoothing some of the rough edges in the project and buffer deserialization process.

Unfortunately I wasn't able to make Atom handle the specific case of having a project root directory on a not-yet-mounted drive; all that we see is an `ENOENT` from the filesystem, so we can't distinguish the cases where we should wait for the file to appear from those where we shouldn't (after an `mv` or an `rm -rf`, say). What I was able to do was improve our handling of attempts to deserialize project directories and buffer paths that were on disk, but aren't any more. Now:

* Any missing root directories are shown in an error notification on launch:

  <img width="583" alt="screen shot 2017-09-20 at 2 24 19 pm" src="https://user-images.githubusercontent.com/17565/30660598-6afdb320-9e0f-11e7-8d3e-3c2220c06dbb.png">

  Hopefully, this should at least clue you in that something happened to your project on disk rather than "silently ignore it."

* TextEditors are no longer created for buffers that used to be backed a file on disk which is now missing. This prevents this panic-attack inducing "hey look all of your files are empty now" behavior from before.

The good news is that this should address a host of issues related to things being done to your files between launches of Atom with serialized state. We'll no longer open a bunch of empty editors if you `git checkout` a different branch, for example.
