### ISSUE TITLE
Atom crashes on long .py file

### ISSUE THREAD

**Issue by sylviaegn** [atom/atom#18996] opened 2019-03-15 14:17 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashes when opening a long .py file

### Steps to Reproduce

1. open atom
2. open file

**Expected behavior:** the file opens in code window

**Actual behavior:**atom crashes

**Reproduces how often:** 100%

### Versions

Atom : 1.35.1
Electron: 2.0.18
Chrome : 61.0.3163.100
Node : 8.9.3
Running on Mac OSX 10.11.6 (El Capitan)

### Additional Information

LOG FILE INFORMATIONS

Process: Atom Helper [4623] Path: /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper Identifier: Atom Helper Version: 1.35.1 (1.35.1) Code Type: X86-64 (Native) Parent Process: Atom [4619] Responsible: Atom [4619] User ID: 501

Date/Time: 2019-03-15 14:47:01.756 +0100 OS Version: Mac OS X 10.11.6 (15G22010) Report Version: 11 Anonymous UUID: 3991DE16-BD30-32E0-AA61-4D5C66CB473D

Time Awake Since Boot: 19000 seconds

System Integrity Protection: enabled

Crashed Thread: 14

Exception Type: EXC_CRASH (SIGABRT) Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information: terminating with uncaught exception of type std::length_error: vector abort() called

**Comment by rsese** [comment] 2019-03-15 19:19
Thanks for the report! 

> Atom crashes when opening a long .py file

How large is the file?  Can you share it so we can try it out?

Also, can you share the full crash log?

Lastly, if you temporarily disable `Settings > Core > Use Tree Sitter Parsers`, does Atom still crash on that file you're using?

**Comment by sylviaegn** [comment] 2019-03-16 16:31
O you're great! Yes, the disabling of Tree Sitter Parser did the job! I can now open and edit my file without crashing atom!

Thank you so much!
Sylvia.

Sylvia Ekström
Tel. direct: +41 22 379 24 50
http://obswww.unige.ch/Recherche/evol/
-------------------------------------------------------
Observatoire astronomique de l'Université de Genève
Maillettes 51 - Sauverny
CH 1290 Versoix
Tel: +41 22 379 22 00
Fax: +41 22 379 22 05
http://www.unige.ch/sciences/astro
-----------------------------------------------

**Comment by rsese** [comment] 2019-03-18 22:20
Thanks for confirming :+1:

Is the file that caused the crash public and something you can share with us so we can try to reproduce?

**Comment by sylviaegn** [comment] 2019-03-19 08:32
It is in an academic private github directory, but I can share it with you if you give me your github username.
Thanks for helping!
Sylvia.

Sylvia Ekström
Tel. direct: +41 22 379 24 50
http://obswww.unige.ch/Recherche/evol/
-------------------------------------------------------
Observatoire astronomique de l'Université de Genève
Maillettes 51 - Sauverny
CH 1290 Versoix
Tel: +41 22 379 22 00
Fax: +41 22 379 22 05
http://www.unige.ch/sciences/astro
-----------------------------------------------

**Comment by rsese** [comment] 2019-03-28 20:27
Ahh ok - if there was a public example you could share with us that would be great but if it's private that's ok.  For now we can close this out and I'll link this issue in https://github.com/atom/atom/issues/18777 which is a report of what seems to be a Tree-sitter crash with a long file as well.

**Closed by rsese** 2019-03-28 20:27 UTC
Labels: crash, tree-sitter

**Comment by sylviaegn** [comment] 2019-03-28 20:59
Perfect, thank you so much for your help!
Cheers,
Sylvia.

Sylvia Ekström
Tel. direct: +41 22 379 24 50<tel:+41%2022%20379%2024%2050>
http://obswww.unige.ch/Recherche/evol/
-------------------------------------------------------
Observatoire astronomique de l'Université de Genève
Maillettes 51 - Sauverny
CH 1290 Versoix
Tel: +41 22 379 22 00<tel:+41%2022%20379%2022%2000>
Fax: +41 22 379 22 05<tel:+41%2022%20379%2022%2005>
http://www.unige.ch/sciences/astro
-----------------------------------------------

Le 28 mars 2019 à 21:29, Robert Sese <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ahh ok - if there was a public example you could share with us that would be great but if it's private that's ok. For now we can close this out and I'll link this issue in #18777<https://github.com/atom/atom/issues/18777> which is a report of what seems to be a Tree-sitter crash with a long file as well.
