### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by sbc2518** [atom/atom#16502] opened 2018-01-06 01:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At C:\Users\sebri\AppData\Local\atom\app-1.23.2\resources\app\node_modules\open-on-github\lib\github-file.js:310

TypeError: Cannot read property 'split' of null
    at GitHubFile.encodeSegments (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/open-on-github/lib/github-file.js:310:28)
    at GitHubFile.shaURL (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/open-on-github/lib/github-file.js:251:35)
    at GitHubFile.copyURL (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/open-on-github/lib/github-file.js:124:41)
    at HTMLElement.open-on-github:copy-url (~/AppData/Local/atom/app-1.23.2/resources/app/node_modules/open-on-github/lib/main.js:81:47)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.2/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.2/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.2/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.2/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  3x -2:34.4.0 core:delete (input.hidden-input)
     -2:33.1.0 core:backspace (input.hidden-input)
  3x -2:23.7.0 autocomplete-plus:activate (input.hidden-input)
     -2:19.2.0 core:delete (input.hidden-input)
  5x -2:18.4.0 autocomplete-plus:activate (input.hidden-input)
     -2:12.3.0 core:undo (input.hidden-input)
  2x -2:06.9.0 core:save (input.hidden-input)
     -1:43.9.0 core:backspace (input.hidden-input)
     -1:32.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:30.2.0 core:save (input.hidden-input)
     -1:19.3.0 core:backspace (input.hidden-input)
  3x -1:17.7.0 core:save (input.hidden-input)
     -0:24.3.0 github:toggle-git-tab (input.hidden-input)
     -0:17.2.0 open-on-github:copy-url (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-01-06 02:31
Thanks for the report!  It looks like this is coming from https://github.com/atom/open-on-github - do you remember what you were using Open on GitHub for @sbc2518 and is the error reproducible for you?

**Comment by rsese** [comment] 2018-03-16 23:14
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16502#issuecomment-355716750. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-03-16 23:14 UTC
Labels: more-information-needed, uncaught-exception

**Comment by adnanmuttaleb** [comment] 2018-07-17 11:33
same issue for me

**Comment by Aerijo** [comment] 2018-07-17 11:36
@adnanmuttaleb Do you have steps that can reproduce the error?
