### ISSUE TITLE
Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog'    at Function.Module._resolveFilename (module.js:351:15)    at Function.Module._load (module.js:293:25)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

### ISSUE THREAD

**Issue by cd10012** [atom/atom#6065] opened 2015-03-23 02:03 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77

Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
    at metaToValue (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77:15)
    at Object.exports.require (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:157:34)
    at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:705:23)
    at /Applications/Atom.app/Contents/Resources/app/src/command-installer.js:73:29
    at /Applications/Atom.app/Contents/Resources/app/src/command-installer.js:102:11
    at FSReqWrap.oncomplete (fs.js:100:15)
```

### Commands

```
     -0:13.3 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:01.2 window:install-shell-commands (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
seti-syntax, v0.2.1
seti-ui, v0.5.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-23 12:41
Duplicate of atom/tree-view#399, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-23 12:41 UTC
