### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1260Error: Cannot ca...

### ISSUE THREAD

**Issue by conbracowebservices** [atom/atom#20028] opened 2019-10-18 16:03 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.15
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1260
Error: Cannot call function 'getPosition' on missing remote object 1260
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 1260
Error: Cannot call function 'getPosition' on missing remote object 1260
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705396)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705811)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -4:23.4.0 editor:newline (input.hidden-input)
     -4:14.7.0 core:paste (input.hidden-input)
  2x -4:13.6.0 core:save (input.hidden-input)
     -4:08.5.0 editor:newline (input.hidden-input)
     -4:03.9.0 core:backspace (input.hidden-input)
     -4:02.5.0 core:save (input.hidden-input)
  2x -3:22.5.0 core:copy (input.hidden-input)
  2x -2:54.7.0 core:paste (input.hidden-input)
     -2:42.3.0 core:undo (input.hidden-input)
     -2:28.9.0 core:copy (input.hidden-input)
     -2:27.5.0 core:paste (input.hidden-input)
  5x -2:26.6.0 core:backspace (input.hidden-input)
     -2:15.9.0 core:save (input.hidden-input)
     -1:26.9.0 core:paste (input.hidden-input)
     -1:25.9.0 core:undo (input.hidden-input)
     -1:23.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-hg 2.0.15 
atom-laravel-log 0.2.3 
atom-meld 0.3.5 
atom-wrap-in-tag 0.6.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-javascript 0.0.2 
autocomplete-json 5.5.2 
autocomplete-modules 2.3.0 
autocomplete-sql 0.5.0 
autocomplete-xml 0.11.0 
blade-spacer 0.4.2 
busy-signal 2.0.1 
double-tag 1.7.0 
file-icons 2.1.35 
highlight-selected 0.16.0 
html-tag-auto-complete 0.1.1 
intentions 1.1.5 
isotope-ui 2.8.5 
language-blade 0.43.1 
lines 0.13.1 
linter 2.3.1 
linter-csslint 2.0.6 
linter-jshint 3.1.17 
linter-less 2.6.0 
linter-php 1.6.1 
linter-tidy 2.4.0 
linter-ui-default 1.8.0 
local-history 4.3.1 
open-in-sourcetree 0.2.0 
php-cs-fixer 4.1.1 
pigments 0.40.2 
platformio-ide-terminal 2.9.4 
project-manager 3.3.8 
tag 0.5.0 
tree-view-filter 0.5.5 
```

**Comment by rsese** [comment] 2019-10-18 19:43
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

If the error is reproducible for you, it would be helpful to know if you can reproduce with the current [Atom beta](https://atom.io/beta) which is running Electron 4.2.7.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-10-18 19:43 UTC
