### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/StephanRaab/Downloads/Atom.app'

### ISSUE THREAD

**Issue by StephanRaab** [atom/atom#9965] opened 2015-12-07 07:14 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/StephanRaab/Downloads/Atom.app'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/StephanRaab/Downloads/Atom.app'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/StephanRaab/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
```

### Commands

```
     -4:53.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:32.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:30.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:26.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:26.1.0 core:paste (atom-text-editor.editor.is-focused)
  3x -2:17.4.0 editor:indent-selected-rows (atom-text-editor.editor.is-focused)
     -2:06.5.0 core:cut (atom-text-editor.editor.is-focused)
     -2:03.7.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:49.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:46.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:45.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:10.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:08.2.0 core:undo (atom-text-editor.editor.is-focused)
  4x -0:55 editor:indent-selected-rows (atom-text-editor.editor.is-focused)
     -0:41.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gruvbox.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "gruvbox"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-12-07 12:52
This is a duplicate of #9813 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-07 12:52 UTC
