### ISSUE TITLE
Formatting Issue with Bold Text in Editor using Markdown 

### ISSUE THREAD

**Issue by Aevyz** [atom/atom#14075] opened 2017-03-28 00:14 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Issue with Bold Text In The Atom-Core section of the Editor. 
![bug](https://cloud.githubusercontent.com/assets/17731961/24382880/8678961a-1359-11e7-9fff-00dbb38409b4.png)

### Steps to Reproduce
Assumes you are already in Github Markdown mode.

1. Write a string, ex. "Hello World"
2. Attempt to make the letters bold that are either at the start of the line of have a space in front of it. However this does not occur when the following character is a space. ex. `"**Hel**lo World", or "Hello **Wor**ld"`
3. Case 1: `"**Hel**lo World"` --> lo World will be in Orange, which should not be the case. <br> `"Hello **Wor**ld"` --> ld and any following text will be in Orange, which should not be the case.

![screenshot from 2017-03-28 02-08-27](https://cloud.githubusercontent.com/assets/17731961/24383210/e34d091e-135b-11e7-9397-b7332cd14768.png)
![screenshot from 2017-03-28 02-08-07](https://cloud.githubusercontent.com/assets/17731961/24383215/e59ac71a-135b-11e7-9560-2d95a94eead2.png)

**Expected behavior:** [What you expect to happen]
See Reproduction 
**Actual behavior:** [What actually happens]
See Reproduction
**Reproduces how often:** [What percentage of the time does it reproduce?]
So far every time
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
```
atom --version
Atom    : 1.15.0
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
```
```
apm --version
(node:6697) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.17.0
npm  4.4.1
node 7.7.3 x64
python 2.7.13
git 2.12.0
```

![image](https://cloud.githubusercontent.com/assets/17731961/24383235/08dcd56a-135c-11e7-82ac-c41009b6cfaf.png)

### Additional Information
If someone can think of a better title for the issue, feel free to suggest it. Brain can't think of any better way of describing it. 

Also this case does not seem to register anything as orange.  
![screenshot from 2017-03-28 02-08-40](https://cloud.githubusercontent.com/assets/17731961/24383141/822d9b8a-135b-11e7-855b-51d221464cbe.png)

I presume this is a regex issue. I'd be willing to look into it if someone can point me in the direction of wherever the code is located for Regex stuff.

**Comment by rsese** [comment] 2017-03-28 05:23
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/language-gfm/issues/117. You may want to subscribe there for updates.  That's also the repository that handles GitHub Flavored Markdown syntax highlighting if you want to take a look.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-28 05:23 UTC

**Comment by 50Wliu** [comment] 2017-03-28 13:30
In addition, you're using an unofficial distribution of Atom.  I would highly recommend uninstalling it and redownloading Atom from https://atom.io.  See https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md for more information.
