### ISSUE TITLE
Atom editor bounces up and down when editing last line

### ISSUE THREAD

**Issue by peterzhu2118** [atom/atom#16828] opened 2018-02-24 14:45 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Atom editor bounces up and down when I try to edit on the last line (see GIF below). It does this for any (and every) file type. This problem only occurs on my laptop and never on my desktop. 

![ezgif-5-97a9bcbab5](https://user-images.githubusercontent.com/15860699/36631497-098c97d8-1947-11e8-96f5-ebbe6c9a5311.gif)

### Versions

OS: Windows 10

```
C:\Users\Peter>atom --version

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
C:\Users\Peter>apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.11
git 2.9.0.windows.1
visual studio 2015
```

**Comment by rsese** [comment] 2018-02-26 19:13
Thanks for contributing!

Based on your description and GIF I think this looks like a duplicate of https://github.com/atom/atom/issues/15786 so you can subscribe there for updates if you'd like.  If you have any other details that you can share (e.g. what video card are you using?), please let us know in https://github.com/atom/atom/issues/15786.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-02-26 19:13 UTC
