### ISSUE TITLE
Atom freezes after starting and can only be started using --clear-window-state

### ISSUE THREAD

**Issue by doberkofler** [atom/atom#16805] opened 2018-02-21 10:00 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Especially since Atom 1.24.0 it happens quite regularly that Atom freezes after starting.
The freeze is not complete but rather the menu partially works but it is not possible to edit any already open files or to open a new file.
It is also impossible to toggle to the developer tools.
After a while Atom reports that it is hung but it is still not possible to close it.
Only closing the running task from the command helps.
Starting in save mode does not help and only starting with the option `--clear-window-state` resolves the problem.
I encountered this problem already in the past but it happened so few times that I assumed some others reasons but starting with Atom 1.24.0 it happens quite (about 30% of the time when closing a reopening Atom) often almost making it hard to work it Atom.

### Steps to Reproduce

1. Close Atom with open file tabs
2. Start Atom again

**Expected behavior:** [What you expect to happen]
Atom to start

**Actual behavior:** [What actually happens]
Atom freezes

**Reproduces how often:** [What percentage of the time does it reproduce?]
~30%

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.3
git 2.12.2.windows.2
visual studio 2013

Windows 7 Professional x84

**Comment by rsese** [comment] 2018-02-21 20:50
Thanks for the report - just to confirm, while you were going through the debugging steps did you also try temporarily resetting to factory defaults to see if that helps? 

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Also, do you see this behavior if you open Atom with a particular project only or with any project?

**Comment by argymeg** [comment] 2018-02-23 10:51
I can't speak for OP, but I just came here to report the same issue and I can confirm resetting to defaults doesn't help, and it happens with any project.

**Comment by doberkofler** [comment] 2018-02-23 12:06
@rsese The problem also seems persists when resetting to defaults but I will have to do some more testing before being 100% sure. It happens with multiple projects.

**Comment by rsese** [comment] 2018-02-23 21:06
Are the projects you've tried with similar e.g. the programming language, size, etc.?  Are they all Git repositories as well?

Lastly, have you also tried starting Atom with just a simple test project that has a single file?  Just trying to narrow down the cases where y'all see this behavior.

**Comment by rsese** [comment] 2018-02-23 21:06
Oh also, does anyone have a public project that we can test with?

**Comment by doberkofler** [comment] 2018-02-24 06:56
@rsese I completely understand how little information I offer and it it is almost impossible to narrow this problem right now. I just hoped, that others might have the same problem and maybe there are ways to better trace this issue.

To your questions:
1) it is one very large project and it is not a Git repository
2) yes smaller repositions often work
3) I forgot to mention that I typically open the project by starting atom from the Windows explorer with a right mouse click on a certain directory but the error also happened when starting Atom from the command line or the application menu.
4) Unfortunately I cannot provide a public project

**Comment by argymeg** [comment] 2018-02-25 17:54
As far as I'm concerned, it's a single small project and Git repository with mostly shell scripts and some Python ones (also not a public one I'm afraid). However, I do often use Atom to open plain .txt files, often in folders by themselves, and it frequently happens then as well, particularly with files larger than a few megabytes (which I never once had a crash with before 1.24.0).

**Comment by zapashcanon** [comment] 2018-02-27 01:53
I can confirm this, with very and small projects, all are git repositories. Running an up-to-date Debian unstable.

**Comment by mmclanerh** [comment] 2018-02-27 22:01
I believe I also have this issue as well in RHEL7 with both stable and beta packages:

atom-beta-1.25.0.beta2-0.1.x86_64
atom-1.23.3-0.1.x86_64

My project tree is a combination of git repos and non-git repos.

**Comment by rsese** [comment] 2018-02-28 06:59
Thanks for the details @doberkofler :+1:

> it is one very large project and it is not a Git repository

How large is the project?  And just to confirm, you mentioned you see the freezing with multiple projects, are they large as well?

If you start Atom in the foreground with `atom --foreground`, are there any error messages?

Lastly, can you install the 1.25 beta and confirm if Atom doesn't freeze in that case?

For anyone else commenting, please check whether safe mode, temporarily resetting to factory defaults, or clearing saved state (you'll lose any unsaved data so save your work first) helps.

**Comment by rsese** [comment] 2018-02-28 07:00
@mmclanerh was that the .rpm from https://atom.io?

Oh also, if anyone has steps to reproduce with a public project they can share, that would be helpful.

**Comment by mmclanerh** [comment] 2018-02-28 07:05
@rsese  Used releases from github repo releases.

Interestingly enough, found gnome-shell had segfaulted shortly before/during atom launch.  Diving deeper.. found that the "timezone" gnome-shell extension was causing the segfault.  I removed that extension and now atom launches.  Weird?  Very...

**Comment by doberkofler** [comment] 2018-02-28 07:25
At least for me the only thing that helps is using `--clear-window-state`

**Comment by mkemkevlla13** [comment] 2018-02-28 07:42
I didnt mean it in a cruel way wether it was you doing the hack or helping the Person responding to what I originally sent out,,  I just want to be left alone

Sent from my HTC

----- Reply message -----

**Comment by lee-dohm** [comment] 2018-02-28 21:02
The steps to reproduce the problem don't describe a single issue. Needing to clear window state can be caused by multiple things. Unfortunately, without a project to reproduce this on or more specific repro steps, this issue is unlikely to be actionable.

**Comment by doberkofler** [comment] 2018-03-04 21:15
@lee-dohm @rsese 

At least for me, the freeze now happens almost each time I start Atom and I basically can no longer use the editor for production purposes.

This is all the information I collected until now:

* At least sometimes, Atom does not completely freeze, but rather takes (2-10 minutes) before the UI responds again.

* Using the `--clear-window-state` option always resolves the freeze problems but after a little while (1hour to 1 day) the freezes start again.

* Resetting to factory defaults does seem to have the same results as when using the `--clear-window-state` option.

* I have not yet been able to test the 1.25.0 Beta Version and wanted to ask if and/or how I can use two Atom versions at the same time?

* Using the `--save` option does not solve the problem.

* When starting Atom with the `--foreground` option and it does not completely freeze the following message is shown:
```
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Object.<anonymous> (C:\Users\doberkofler.LBITS\AppData\Local\atom\app-1.24.0\resources\app.asar\node_modules\github\lib\worker.js:71:22
Remote event names: destroyed, crashed
```

* Using the options `--dev`, `--enable-electron-logging` or  `--log-file=atom.log` does not seem to generate any additional debugging information nor is a log file created.

* I now also have problem in a public GitHub repository but when installing from scratch, it does not seem to freeze as it seems to have something to do with my local configuration.

* How can I provide a reproducible project if it only happens with my existing settings and when clearing the state `--clear-window-state` Atom is starting again and what exactly is `--clear-window-state` doing?

* This is actually how the UI looks when frozen:
![2018-03-04 21_27_55-](https://user-images.githubusercontent.com/1009585/36950403-ae5dacc0-1ff5-11e8-8a11-90b6ce5434c8.png)

* This is what happens after a while:
![image](https://user-images.githubusercontent.com/1009585/36950439-46d6070e-1ff6-11e8-81ed-5bf7e12417db.png)

**Comment by lee-dohm** [comment] 2018-03-04 21:21
@doberkofler Do you have "Use Tree Sitter Parsers" checked in the Core settings page? If so, uncheck it and see if that helps. Also, can you ever reproduce this problem when running Atom using `--safe`?

Clearing the window state deletes any state that was serialized by Atom or any package when Atom exits.

**Comment by doberkofler** [comment] 2018-03-05 07:36
@lee-dohm 
* I cannot find a core setting option named "Use Tree Sitter Parsers". Where should it exactly be?
* Using the `--save`option does not change anything. Only using `--clear-window-state` resolves the freezes.

**Comment by Ben3eeE** [comment] 2018-03-05 08:43
@doberkofler 

> Using the `--save` option does not change anything. Only using --clear-window-state resolves the freezes.

The command line switch is `--safe` not `--save`. Can you please verify that you are using `--safe` and not `--save`?

> I have not yet been able to test the 1.25.0 Beta Version and wanted to ask if and/or how I can use two Atom versions at the same time?

On Windows they can run side by side but they can't be installed side by side. You would need to download the portable version: https://github.com/atom/atom/releases/download/v1.25.0-beta2/atom-windows.zip & https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode

> I cannot find a core setting option named "Use Tree Sitter Parsers". Where should it exactly be?

This option is currently only available in the beta release of Atom so you don't have it checked :slightly_smiling_face:

**Comment by ouatataz** [comment] 2018-03-05 12:47
Dear all.

I have the same issue as @doberkofler.
My project tree is a combination of git repos and non-git repos. I'm on MacOS 10.13.3 with the latest Atom stable release (1.24).

The only thing that helps is using `--clear-window-state`
What does this command do exactly ? Is there a file somewhere that stores the windows state ?

Thx.

**Comment by lee-dohm** [comment] 2018-03-05 15:12
@ouatataz While the symptoms may be the same, I can almost guarantee that the root cause is not the same. Please open a new issue, completely fill in the template and include your entire `config.cson` and a list of the packages you have installed.

You can find out more about `--clear-window-state` in the [Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state). No, there is not a single file somewhere that stores the window state, that's why we have the switch.

**Comment by grtessman** [comment] 2018-05-13 17:27
The "atom --clear-window-state" solved the issue of Atom not opening for me on a Mac.  Was getting Not Responding and wasn't opening.  Stragely, Brackets was doing the same thing.  Neither would open/launch.  Somehow this command also solved the problem in both Atom and Brackets at least for now.

**Closed** 2018-10-02 15:16 UTC
Labels: more-information-needed
