### ISSUE TITLE
Renaming grandparent folders of edited files does not work (Atom Beta)

### ISSUE THREAD

**Issue by johnpyp** [atom/atom#15749] opened 2017-09-26 23:45 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

You cannot rename folders in Atom BETA on at least Windows 10 and Windows 7 when a file in a sub-folder of the targeted folder to be renamed is edited. This also affects windows explorer. It gives an error that the folder cannot be renamed because it is in use by another program.

Steps to reproduce found here: https://github.com/johnpyp/atom-canary-isolation

**Expected behavior:** Folder renames normally even if file is changed

**Actual behavior:** Folder (in Atom) does not have permission to change and (in explorer) doesn't get renamed due to "the folder being open in another program".

**Reproduces how often:** 100% (3 tests so far, fairly thorough in terms of testing order of things and different operations to try to affect it. Two different folder and file structures analyzed to reproduce)

### Versions
Atom    : 1.21.0-beta2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python
git 2.14.1.windows.1
visual studio

Tested on Windows 10 and Windows 7,  not sure what versions.
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Edit:** Seems to be a long-standing bug in normal Atom too, just happens to be a case I have only really run in with using the Beta (though I do remember this error popping up in normal Atom).

**Comment by rsese** [comment] 2017-09-27 06:06
> Edit: Seems to be a long-standing bug in normal Atom too, just happens to be a case I have only really run in with using the Beta (though I do remember this error popping up in normal Atom).

Hmmm, yeah I think maybe a duplicate of https://github.com/atom/node-pathwatcher/issues/101 yeah @50Wliu?

**Comment by 50Wliu** [comment] 2017-09-27 06:26
Yeah that's what I was about to mention.

**Comment by johnpyp** [comment] 2017-09-27 11:00
is there any work to get this fixed? It seems pretty major.

**Comment by rsese** [comment] 2017-09-28 04:07
Thanks for confirming @50Wliu, closing as a duplicate of https://github.com/atom/node-pathwatcher/issues/101.

@johnpyp - I don't believe it's currently prioritized and though we can't make any promises, I'll  bring it up with the team.

**Closed by rsese** 2017-09-28 04:07 UTC
