### ISSUE TITLE
HTML Syntax Colour Bug

### ISSUE THREAD

**Issue by gusbemacbe** [atom/atom#13294] opened 2016-11-22 07:20 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I built an HTML file, contains three longer Javascript scripts, three longer base64 encoded images and two base64 encoded fonts. But everything isn't colourful. I analysed every code and I didn't find any issue. 

In other code editors, everything works and is colourful.

I believed that it is a bug. 

### Steps to Reproduce

1. I copied carefully and correctly base64 codes to img and font and it was still colourful.
2. I copied one or two scripts and it was still colourful. But the second script caused the conflict, not allowing me to fold (hide) the Javascript script tags. I switched to another editor, for fixing an issue and copied the third script. 
3. I open the same file with Atom and I saw that it wasn't colourful. But still colourful in that other editor. 

### Versions
Atom:                 1.12.5
Electron:            1.3.9
Chrome :            52.0.2743.82
Node:                 6.5.0

apm      1.12.9
npm      3.10.5
node     4.4.5
python  2.7.12
git.         2.9.3

macOS Sierra 10.10

![screen shot 2016-11-22 at 05 05 37](https://cloud.githubusercontent.com/assets/2257024/20514490/49a1bb70-b073-11e6-8e46-7c3ca6033021.png)

**Comment by thomasjo** [comment] 2016-11-22 08:46
Can you please share some details about the size of the file, and in particular the length/size of those base64 encoded strings? Based on the steps outlined in your description I'm 99% sure you've hit the file size ceiling upon which we entirely disable syntax highlighting for performance reasons.

**Comment by ruslankonev** [comment] 2016-11-22 10:05
Confirm. After update one-dark-syntax by notification Atom and restart - One Dark theme & syntax will not highlight any language. I think was broken only one-dark theme, but after install Material theme & syntax – highlight not available.
![image](https://cloud.githubusercontent.com/assets/2588730/20519493/36183b92-b0b4-11e6-9ccc-1932779ee509.png)

Issue on one-dark-syntax — https://github.com/atom/one-dark-syntax/issues/82

**Comment by gusbemacbe** [comment] 2016-11-22 13:00
@thomasjo 

## **File detailhes:**
**Size:** 2,3MB
**Lines number:** 12,474 lines

Observe that Atom's syntax was still enabled in that file, but not colourful, I have already done a test in another new file and it was colourful. 

**## 1st Bootstrap Javascript script:**
**Characters number:** 91.749
**Lines number:** 1765

**## 2nd jQuery Javascript script:**
**Characters number:** 141.289
**Lines numbers:** 395

**## 3rd Prism Javascript script:**
**Characters number:** 296.251
**Lines numbers:** 7063

## **1st base64 encoded font:**
**Characters number:** 216.525

## **2nd base64 encoded font:**
**Characters number:** 234.729

## **1st base64 encoded image:**
Characters number: 602.604

## **2nd base64 encoded image:**
Characters number: 593.404

All these base64 encoded fonts and images have only one unbroken line. 

Strange, in Atom, the final part of base64 encoded fonts and images characters was cut, while in another code editor, not cut. I believe that it is due to the limit of characters length.

@ruslankonev 

I'm using Dracula syntax and UI theme. HTML syntax was still enabled.

**Comment by gusbemacbe** [comment] 2016-11-22 13:11
@ruslankonev 

I have just tested, using Material themes and it didn't get colourful.

**Comment by ruslankonev** [comment] 2016-11-22 13:15
https://github.com/atom/one-dark-syntax/issues/82#issuecomment-262231011

**Comment by simurai** [comment] 2016-11-23 03:49
@gusbemacbe If you place your cursor inside the first `html` and press `cmd-alt-p`, what scopes does the notification show? In my case it's:

![screen shot 2016-11-23 at 12 43 03 pm](https://cloud.githubusercontent.com/assets/378023/20550606/d31840ba-b17a-11e6-9d9c-ae8a89cea8be.png)

Also if you don't mind pasting the code here (or gist) to see if we can reproduce it too.

**Comment by gusbemacbe** [comment] 2016-11-23 04:22
Konnichiwa @simurai!

Follow my screenshot, shite kudasai. 

![screen shot 2016-11-23 at 02 12 22](https://cloud.githubusercontent.com/assets/2257024/20551002/8343913c-b122-11e6-91cf-1ef3db7710ce.png)

And you can view and analyse my file. Simurai-san:

[Apresentação de Banco de Dados II.html.zip](https://github.com/atom/atom/files/608097/Apresentacao.de.Banco.de.Dados.II.html.zip)

I'm sorry that it is not in English or Japanese. It is everything in Portuguese. it's my homework for my college. It's an introduction. Before it has 12k lines, now it has 18233 lines, because I built and finished this homework in another code editor, so Atom doesn't recognise the codes. It also crashed a bit when I typed the codes. 

Hey, Simurai-san, are you author of some modified themes for Prism.js, based on Atom themes, right? Can I post your theme bug there in Prism-themes?

**Comment by simurai** [comment] 2016-11-23 13:44
@gusbemacbe Thanks. I can reproduce this with your file too.

There seems to be nothing wrong with the file, but syntax highlighting gets disabled if the file is very large. See https://github.com/atom/atom/pull/7130 for more details.

Gonna close this since it's a duplicate of https://github.com/atom/atom/issues/11232 and probably also https://github.com/atom/atom/issues/1667.

> are you author of some modified themes for Prism.js

I haven't created a theme for prism.js myself, but it's quite possible that somebody ported Atom themes over. Yeah, it's probably best to create an issue in the theme's repo.

**Closed by simurai** 2016-11-23 13:44 UTC
Labels: more-information-needed
