### ISSUE TITLE
Uncaught Error: spawn /opt/atom/atom (deleted) ENOENT

### ISSUE THREAD

**Issue by kateklemp** [atom/atom#4899] opened 2015-01-07 21:23 UTC
[Enter steps to reproduce below:]

1. Clicked on File > Open Folder (from already open project)
2. In file chooser, created a new folder, went inside, and clicked "open"

Opens the folder anyway without any issues.  Clicking "New Window", "New File", all creates the same issue (but new windows, new files are created okay, and I can save new files without issue).  Closing all windows and opening Atom fresh causes the errors to stop.

**Atom Version**: 0.165.0
**System**: linux 3.13.0-43-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /opt/atom/atom (deleted) ENOENT

```
At events.js:85

Error: spawn /opt/atom/atom (deleted) ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-01-08 13:14
This looks like a duplicate of https://github.com/atom/atom/issues/4505 (so I'm closing this in favor of that issue). Can you try the suggestion from https://github.com/atom/atom/issues/4505#issuecomment-66795073?

**Closed by izuzak** 2015-01-08 13:14 UTC
