### ISSUE TITLE
DEB package license is shown as proprietary in Ubuntu GNOME Software Install

### ISSUE THREAD

**Issue by wesinator** [atom/atom#18367] opened 2018-10-30 20:48 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The license type of the official DEB package build is shown as "Proprietary" in Ubuntu gnome-software
![image](https://user-images.githubusercontent.com/5124946/47747379-9fc00c00-dc5e-11e8-9df1-8d2d979c10a6.png)

### Steps to Reproduce

1. Download official atom deb (stable or beta)
2. Open with Software Install (Ubuntu Software)

**Expected behavior:** MIT license ? https://github.com/atom/atom/blob/master/LICENSE.md

**Actual behavior:** License shown as "Proprietary"

**Reproduces how often:** Always

### Versions

atom 1.32.0 and 1.33.0-beta
Ubuntu 18.04
gnome-software 3.28.1

**Comment by rsese** [comment] 2018-10-31 19:47
Thanks for the report!  Reproduced with https://github.com/atom/atom/releases/download/v1.32.0/atom-amd64.deb on Ubuntu 18.04.

Looks like there's a `copyright` file we would need to include but there are also other issues on the Ubuntu side?  x-ref: https://github.com/betaflight/betaflight-configurator/issues/989 and https://github.com/Microsoft/vscode/issues/3321

**Comment by sadick254** [comment] 2021-05-07 17:40
@wesinator I know this has been open for a long time. Indeed there are issues on Ubuntu side on how it handles licenses from apps that are not in the main repositories.
This issue would therefore be outside our scope, as a result, I will have to close this.

**Closed by sadick254** 2021-05-07 17:40 UTC
Labels: d ⬇️, i ⬇️, linux, triaged, v ⬇️
