### ISSUE TITLE
Atom Git UI Commit

### ISSUE THREAD

**Issue by ogawaryu** [atom/atom#15119] opened 2017-07-28 18:45 UTC
Does not allow commit starting with character #

example: #48794 - Some text here

**Comment by avalan4e57** [comment] 2017-07-29 13:03
Hmm. It's not really like that. You can still make a commit starting with "#". But the app shoes an "Aborting commit due to empty commit message." error when commit message consists only one line starting with "#". If you ad some extra lines to your commit then the "#"-line will be just not visible.
The point is that git allows us to make commit messages like "#Strange hash commit" and they are even acceptable to read in log. One can even still read the hashed first line if there're some other lines in commit.
However as I know the famous vim from terminal default also defines hashed lines as those that aren't included in commit message. 
So I think we need further discussion here

**Comment by hultberg** [comment] 2017-07-29 13:09
This should be reported to https://github.com/atom/github, not core.

**Comment by 50Wliu** [comment] 2017-07-29 22:02
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/github#962. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-07-29 22:02 UTC
