### ISSUE TITLE
Atom's package.json should support other npm-style repository formats

### ISSUE THREAD

**Issue by silvenon** [atom/atom#4776] opened 2014-12-27 15:07 UTC
For example, [atom-jshint](https://github.com/sindresorhus/atom-jshint) has `repository` set to `sindresorhus/atom-jshint` in its `package.json`, which should be fine, but Atom seems to default to `git://` when rendering package links.

![screenshot 2014-12-27 16 04 27](https://cloud.githubusercontent.com/assets/471278/5561594/3ae6e12e-8de2-11e4-874f-2320be9ffcd3.png)

**Comment by mnquintana** [comment] 2015-01-04 06:38
This looks like an issue with [atom-jshint](https://github.com/sindresorhus/atom-jshint), not really with Atom – atom-jshint defines its repo url as `git://github.com/sindresorhus/atom-jshint`

![screenshot 2015-01-04 01 37 23](https://cloud.githubusercontent.com/assets/823545/5605021/5020497e-93b2-11e4-8931-6ababc448255.png)

**Comment by lee-dohm** [comment] 2015-01-04 23:53
For additional context:

* https://discuss.atom.io/t/links-in-preferences-packages-go-to-xcode/14050
* sindresorhus/atom-editorconfig#26

Essentially, the problem is that while there is much in common between Atom's `package.json` format and npm's `package.json` format, Atom's `package.json` does not yet support everything that npm's does. I can't speak to whether it is the intention of the Atom team to make Atom's format completely compatible with npm's either, so I'll mark this as an enhancement for now.

**Comment by lee-dohm** [comment] 2015-01-04 23:58
I hope you don't mind that I changed the title @silvenon to be more descriptive of the underlying problem. Thanks so much for reporting the issue!

**Comment by silvenon** [comment] 2015-01-09 13:01
@mnquintana from which file is that code coming from? Isn't [this](https://github.com/sindresorhus/atom-jshint/blob/210c1bed3f7f1d273b8c577f9324574d553e58ee/package.json#L6) the `package.json` from v1.1.3? If indeed there is a `git://` protocol in the `package.json`, then this is not a bug.

> I hope you don't mind that I changed the title @silvenon to be more descriptive of the underlying problem.

No problem, whatever helps :smiley:

**Comment by mnquintana** [comment] 2015-01-09 13:13
@silvenon Well this just got weird. I took this screenshot from my installed version of atom-jshint's package.json, and it still shows `git://` in the latest version, `1.1.4`, even though it doesn't on the package's repo on GitHub. :confused:

Try this to reproduce:
1. Install jshint from Settings > Install
2. Go to jshint > Settings > View Code
3. Take a look at that `package.json`

**Comment by silvenon** [comment] 2015-01-12 08:12
Yep, you're right, I got the same. How does that happen? :smiley:

**Comment by mnquintana** [comment] 2015-06-12 11:23
Closing in favor of https://github.com/atom/settings-view/issues/543

**Closed by mnquintana** 2015-06-12 11:23 UTC
Labels: enhancement
