### ISSUE TITLE
Atom hangs on opening file with very long line

### ISSUE THREAD

**Issue by keegandonley** [atom/atom#8348] opened 2015-08-12 18:47 UTC
I've got a compressed js file that has 1 line which is about about 29,000 columns long. Attempting to open this file freezes the entire UI, but eventually it is able to load. Syntax highlighting also stops at col. 251 on this particular file.

Other files that are much larger (such as jQuery minified javascript) never end up loading properly. After waiting a while, a notice pops up that the editor has stopped responding, and the editor screen reverts back to the file I was viewing previously. Navigating back to that jQuery script shows that it has then loaded, but syntax highlighting still stops, and then becomes very sporadic throughout the rest of the file.

version: 1.0.6
os: Mac OSX 10.10.4

![screen shot 2015-08-12 at 11 45 35 am](https://cloud.githubusercontent.com/assets/12700819/9233418/b1a676fe-40e7-11e5-8ff9-cfc31d95aa97.png)

![screen shot 2015-08-12 at 11 45 00 am](https://cloud.githubusercontent.com/assets/12700819/9233390/93c4bc40-40e7-11e5-8c8a-9dca9641f071.png)

**Comment by mnquintana** [comment] 2015-08-12 20:27
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/979 – please subscribe there for updates.

**Closed by mnquintana** 2015-08-12 20:27 UTC
