### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'    at Function.Module._resolveFilename (module.js:328:15)    at Function.Module._load (module.js:270:25)    at Module.require (module.js:357:17)    at require (module.js:376:17)    at BrowserWindow.<anonymous> (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\app.asar\src\browser\atom-window.js:152:27)    at emitOne (events.js:77:13)    at BrowserWindow.emit (events.js:166:7)    at callFunction (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)    at EventEmitter.<anonymous> (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)    at emitMany (events.js:108:13)

### ISSUE THREAD

**Issue by algaly** [atom/atom#6577] opened 2015-04-30 11:43 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\app.asar\src\window-event-handler.js:149:33)
    at HTMLDocument.handler (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\avi.algaly\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -5:44.2.0 editor:newline (atom-text-editor.editor)
     -5:42.7.0 snippets:next-tab-stop (atom-text-editor.editor)
     -5:42.7.0 snippets:expand (atom-text-editor.editor)
     -5:42.7.0 editor:indent (atom-text-editor.editor)
     -5:42.1.0 snippets:next-tab-stop (atom-text-editor.editor)
     -5:42.1.0 snippets:expand (atom-text-editor.editor)
     -5:42.1.0 editor:indent (atom-text-editor.editor)
     -5:39 core:save (atom-text-editor.editor)
     -5:17.7.0 core:move-to-top (atom-text-editor.editor)
     -5:16.9.0 find-and-replace:show (atom-text-editor.editor)
  4x -5:13.6.0 core:confirm (atom-text-editor.editor.mini)
     -5:09.6.0 project-find:show (atom-text-editor.editor.mini)
     -5:08.8.0 core:confirm (atom-text-editor.editor.mini)
     -4:48.9.0 core:cut (atom-text-editor.editor)
  3x -4:47.1.0 core:save (atom-text-editor.editor)
  4x -4:03.5.0 core:copy (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "autoIndent": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.0

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-04-30 11:53
Thanks for the report -- this looks like a duplicate of https://github.com/atom/atom/issues/6548, please follow that for updates.

**Closed by izuzak** 2015-04-30 11:53 UTC
