### ISSUE TITLE
Release notes don't seem to update properly

### ISSUE THREAD

**Issue by frankhale** [atom/atom#3757] opened 2014-10-08 14:54 UTC
I use Atom on two different machines and I'm seeing anomalies when looking at the release notes. On one of my machines the release notes are always blank with only a button showing to view previous release notes. On the other machine the release notes are old. Here is a current screenshot but keep in mind this isn't the only time the release notes have been outdated compared to the release I was using.

Currently using Atom 0.136 on Windows 8.1 (on two different systems).

![atom-release-notes-problem](https://cloud.githubusercontent.com/assets/190154/4561202/e6b3c3f4-4efa-11e4-917c-87407b1d7419.png)

**Comment by picibucor** [comment] 2015-01-13 11:53
Hi all,

Problem is not solved:

Here's what do I see by clicking on : Help -> Release Notes

![release_notes](https://cloud.githubusercontent.com/assets/1676457/5720329/032d98d8-9b23-11e4-94ea-4a6f7306697a.png)

And here's what my (Win 7) control Panel says:
win_version
![win_version](https://cloud.githubusercontent.com/assets/1676457/5720326/fa4e2d0e-9b22-11e4-86cc-62945b470959.png)

I suppose the versions should be the same....

**Comment by awayken** [comment] 2015-01-14 15:53
+1

I have this same issue. I'm running version 0.172.0 on Windows 8.1, and the release notes only go up to 0.147.0.

**Comment by kevinsawicki** [comment] 2015-01-14 17:46
For people still having this issue, can you run the following from the Console tab of the dev tools?

```
localStorage.getItem('release-notes:version')
```

**Comment by frankhale** [comment] 2015-01-14 17:56
I'm running 0.172 but the output of localStorage.getItem('release-notes:version') says "0.149.0"

**Comment by kevinsawicki** [comment] 2015-01-14 17:58
Great, thanks, that seems to be the issue, for some reason the event that emits the version being downloaded either isn't firing or it is firing with the wrong information.

**Comment by awayken** [comment] 2015-01-14 19:24
When I execute `localStorage.getItem('release-notes:version')` the output says "0.147.0"

**Comment by steveoh** [comment] 2015-02-03 21:22
running `localStorage.setItem('release-notes:version', "0.177.0")` and then viewing the release notes updated them. We'll see what happens with the next update.

**Comment by kevinsawicki** [comment] 2015-02-03 22:59
Just pushed a fix to master for this but because this is auto updater related it will probably take 2 releases to correct itself and show the right version and notes.

**Comment by simonjosefsson** [comment] 2015-02-12 09:06
Updated to 179, release notes is still stuck on 157 for me

**Comment by picibucor** [comment] 2015-02-12 10:25
for me as well

**Comment by steveoh** [comment] 2015-02-12 16:26
he said it might take 2 releases. If it really bothers you run
`localStorage.setItem('release-notes:version', "0.179.0")` in the console.

**Comment by frankhale** [comment] 2015-02-18 03:43
I just updated from 177 to 179 and the release notes updated fine. Thanks for the fix!

**Comment by picibucor** [comment] 2015-02-23 08:32
fixed. Thx :+1:

**Comment by avdg** [comment] 2015-02-23 14:15
Seems like we have consensus, great :-)

**Comment by frankhale** [comment] 2015-03-13 03:59
I'm seeing the problem once again. See screenshot:

![release-notes-not-updating](https://cloud.githubusercontent.com/assets/190154/6632855/d186f95e-c913-11e4-8ad6-2bc546258750.png)

**Comment by zigasaletinger** [comment] 2015-03-21 09:01
hello,

similar situation here:
- version in help menu: 0.187.0
- release notes: 0.165.0

and auto update does not work

best regards,
ziga

**Comment by 50Wliu** [comment] 2015-03-21 13:39
Well isn't this just fantastic :frowning:.
/cc @kevinsawicki

**Comment by zigasaletinger** [comment] 2015-03-21 16:40
Additional info: 
* I had older version before (0.17x.x)
* (re)installation of version 0.187.0 (current) didn't help. 

After following the suggestion and executing `localStorage.setItem('release-notes:version', "0.187.0")` the numbers were adjusted and release notes show as they should. 

Hopefully it will update next time :8ball: 

Noticed one thing (hopefully not related) - solarized light syntax theme lost its current line highlight.

Best regards!

**Comment by llompartg** [comment] 2015-03-25 09:25
I have the same issue.

Version 0.188.0 but release notes displaying 0.184.0 as the last one.

Changing the `localStorage` version did the trick to update them

**Comment by llompartg** [comment] 2015-04-07 15:29
Worked for me on the last update. From 0.188.0 to 0.189.0

**Comment by frankhale** [comment] 2015-04-21 18:49
This has been working for me nicely on 3 machines for a while now.

**Comment by 50Wliu** [comment] 2015-04-21 19:04
Closing once again.  If anyone can still reproduce this on 0.192.0 please comment here.

**Closed by 50Wliu** 2015-04-21 19:04 UTC
Labels: 1.0-roadmap, atom, bug, windows

**Comment by Stanzilla** [comment] 2015-04-21 22:46
So I was impatient and downloaded the Atom installer instead of waiting for the 193 update today and since then Atom thinks it has to update and restart all the time. 
![2015-04-22_00-45-44](https://cloud.githubusercontent.com/assets/75278/7264158/fe5f8a60-e888-11e4-9084-721cb53aec9a.png)

Did it 3 times already, still happening.

**Comment by Stanzilla** [comment] 2015-04-22 06:34
A combination of manually changing the version field in local storage and the update actually being available on the update servers seems to have fixed it. Still a problem someone should look into..

**Comment by Stanzilla** [comment] 2015-04-22 17:12
@kevinsawicki @50Wliu want me to create a new issue for this or?

**Comment by kevinsawicki** [comment] 2015-04-22 17:13
> want me to create a new issue for this or?

Sure, sounds good.

**Comment by Stanzilla** [comment] 2015-04-22 17:16
https://github.com/atom/atom/issues/6482

**Comment by mika76** [comment] 2015-11-17 03:07
This is happening for me now between versions 1.1.0 and 1.2.0 (OSX el capitan)

**Comment by frankhale** [comment] 2015-11-18 02:40
Looks like a regression has popped up with release notes not updating automatically again.

![atom-release-notes-not-updating](https://cloud.githubusercontent.com/assets/190154/11231161/ac9f08fa-8d73-11e5-900c-25b9227fa258.png)

**Comment by Stanzilla** [comment] 2015-11-18 04:05
Can confirm

**Comment by multi** [comment] 2015-11-18 08:22
same here, 1.2.1 El Capitan

**Comment by nickfmc** [comment] 2015-11-18 23:33
Win 10 confirmed issue is back also.

**Comment by Kosyne** [comment] 2015-11-19 07:20
Yep, this problem has returned :(

**Comment by shylor** [comment] 2015-11-19 16:34
I also have this issue.

**Comment by steveoh** [comment] 2015-11-19 16:57
can someone lock this issue please.

**Comment by frankhale** [comment] 2015-11-19 17:13
Please do not lock this issue, please reopen it.

**Comment by benogle** [comment] 2015-11-19 18:28
We're really sorry about this issue. The plan is to remove the release notes package and have all the update logic in the about page similar to chrome. See https://github.com/atom/atom/issues/9164 for more details.
