### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by th3mast3rofshadows** [atom/atom#7550] opened 2015-06-29 13:54 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Adrian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:28.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:27.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.1.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:25.9.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
 19x -0:24.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:23 core:move-right (atom-text-editor.editor.is-focused)
  5x -0:22.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -0:18.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-htmlhint"
    ]
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.1.0
linter-php, v0.0.15
php-twig, v4.0.0
sass-autocompile, v0.7.1
set-syntax, v0.3.0

# Dev
No dev packages
```

tried adding a new file through the navigation menu. this used to work until the 1.0 update.

**Comment by mnquintana** [comment] 2015-06-29 14:19
This is a duplicate of https://github.com/atom/atom/issues/6548 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-29 14:19 UTC
