### ISSUE TITLE
V1.6.0-beta Fails to install on Windows 7

### ISSUE THREAD

**Issue by BrianSidebotham** [atom/atom#10754] opened 2016-02-10 12:30 UTC
See the install log:

Perhaps https://blogs.msdn.microsoft.com/bclteam/2007/02/13/long-paths-in-net-part-1-of-3-kim-hamilton/ can be of some help in solving the problem.

I should say, I'm installing here from AtomSetup.exe

> 2015-10-07 15:47:52> Program: Starting Squirrel Updater: --install .
2015-10-07 15:47:52> Program: Starting install, writing to C:\Users\Brian.sidebotham\AppData\Local\SquirrelTemp
2015-10-07 15:47:52> Program: About to install to: C:\Users\Brian.sidebotham\AppData\Local\atom
2015-10-07 15:47:53> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Brian.sidebotham\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3c.MoveNext()
2015-10-07 15:47:53> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Brian.sidebotham\AppData\Local\SquirrelTemp
2015-10-07 15:47:53> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-10-07 15:47:53> ApplyReleasesImpl: Writing files to app directory: C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\content_resources_200_percent.pak to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\content_resources_200_percent.pak
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\content_shell.pak to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\content_shell.pak
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\atom.exe to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\atom.exe
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\d3dcompiler_47.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\d3dcompiler_47.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\ffmpegsumo.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\ffmpegsumo.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\icudtl.dat to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\icudtl.dat
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\libEGL.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\libEGL.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\libGLESv2.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\libGLESv2.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\LICENSE to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\LICENSE
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\node.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\node.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\msvcr120.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\msvcr120.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\msvcp120.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\msvcp120.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\pdf.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\pdf.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\natives_blob.bin to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\natives_blob.bin
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\squirrel.exe to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\squirrel.exe
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\vccorlib120.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\vccorlib120.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\snapshot_blob.bin to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\snapshot_blob.bin
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\xinput1_3.dll to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\xinput1_3.dll
2015-10-07 15:48:12> ApplyReleasesImpl: Moving file C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\lib\net45\ui_resources_200_percent.pak to C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\ui_resources_200_percent.pak
2015-10-07 15:48:13> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.0.19\atom.exe]
2015-10-07 15:48:17> ApplyReleasesImpl: Starting fixPinnedExecutables
2015-10-07 15:48:17> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2015-10-07 15:48:17> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.19
2015-10-07 15:48:17> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.19
2015-10-07 15:48:26> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__11b.MoveNext()
2016-02-10 12:24:05> Program: Starting Squirrel Updater: --install .
2016-02-10 12:24:05> Program: Starting install, writing to C:\Users\Brian.sidebotham\AppData\Local\SquirrelTemp
2016-02-10 12:24:05> Program: About to install to: C:\Users\Brian.sidebotham\AppData\Local\atom
2016-02-10 12:24:05> Program: Install path C:\Users\Brian.sidebotham\AppData\Local\atom already exists, burning it to the ground
2016-02-10 12:24:05> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Brian.sidebotham\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3d.MoveNext()
2016-02-10 12:24:05> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Brian.sidebotham\AppData\Local\SquirrelTemp
2016-02-10 12:24:05> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-02-10 12:24:05> ApplyReleasesImpl: Writing files to app directory: C:\Users\Brian.sidebotham\AppData\Local\atom\app-1.6.0-beta0
2016-02-10 12:24:23> IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a8>d__b8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
2016-02-10 12:24:24> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a8>d__b8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__37.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassaf.<<installPackageToAppDir>b__a8>d__b8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__54`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__37.MoveNext()<---

**Comment by 50Wliu** [comment] 2016-02-10 14:23
Hi @BrianSidebotham, thanks for reporting!  This looks like a duplicate of #5109 though, so please subscribe there for updates.

**Closed by 50Wliu** 2016-02-10 14:23 UTC
