### ISSUE TITLE
[feature request] [working prototype] Atom repository for Linux RPM and Deb packages

### ISSUE THREAD

**Issue by paulcarroty** [atom/atom#15901] opened 2017-10-16 11:28 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There's [the prototype](https://gitlab.com/paulcarroty/atom-rpm-deb-mirror) of repository. The difference for Github deploy is the file size limitation in 50 MB, therefore Git LFS with enabled tracking for `*.rpm` and `*.deb` is needed. 

Why is it so hard to do it for the Atom Team? ~30 lines of code! Downloading the each update manually is stupid as writing some scripts to automate if the repositories concept is native and working for decades!

**Comment by kuboosoft** [comment] 2017-10-16 19:53
Atom team, you are a sponsored project. Why no put a official repository? here  a [new service with low price](https://www.alibabacloud.com/pricing?spm=a3c0i.7939108.675768.dnavpricing.2fb837e2qMZvst) ;)

**Comment by lee-dohm** [comment] 2017-10-16 19:57
Thanks for the working prototype @paulcarroty! I'll have the team take a look.

Closing as duplicate of https://github.com/atom/atom/issues/2956.

**Closed by lee-dohm** 2017-10-16 19:57 UTC

**Comment by lee-dohm** [comment] 2017-10-16 20:00
I deleted @kuboosoft's comment since it was an advertisement.

**Comment by kuboosoft** [comment] 2017-10-16 20:08
@lee-dohm sure a "advertisement". The Atom project is sponsored aproject. the common pleople can't make your work... I maintain a "rpm" for atom; and I  can deletes it if I want...

**Comment by ASRauliki** [comment] 2017-12-19 08:07
It's been 2 months. It's like 0,5 a line of code daily and still no progress?

**Comment by paulcarroty** [comment] 2017-12-19 13:28
@ASRauliki , are you still waiting? LOL.

**Comment by lee-dohm** [comment] 2017-12-20 03:26
@ASRauliki and @paulcarroty, your comments were deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as they were insulting or derogatory. You may consider this an official warning.

**Comment by ASRauliki** [comment] 2017-12-20 06:43
From Atom Code of Conduct:
Gracefully accepting constructive criticism
Focusing on what is best for the community

That's what my comment was about. If you want to spend time deleting non-offensive comments, that means you don't focus on community. Making repository in what way is offensive to community and doesn't help?

**Comment by ASRauliki** [comment] 2017-12-20 06:55
And could you elaborate what exactly was insulting?
