### ISSUE TITLE
Italic character at end of line is truncated by cursor

### ISSUE THREAD

**Issue by dgraham** [atom/atom#249] opened 2013-02-07 18:10 UTC
The 'f' below is not fully rendered at the end of the line.  I'm not sure if it matters, but this is on a retina display.

![Screen Shot 2013-02-07 at 11 08 00 AM](https://f.cloud.github.com/assets/122102/136614/758abfda-7151-11e2-80c7-dbde104975ee.png)

**Comment by danieldiekmeier** [comment] 2016-02-10 20:50
While the bug is still open in the WebKit tracker (https://bugs.webkit.org/show_bug.cgi?id=12607), the provided test case isn't broken in Chrome anymore. Maybe it was fixed in Blink. (I can still reproduce it in Safari.)

Anyway, everything seems to be working in Atom, the Cursor doesn't cut the end of letters of anymore:

![screen shot 2016-02-10 at 21 49 56](https://cloud.githubusercontent.com/assets/2098462/12961343/4433e8b6-d040-11e5-93a4-5a3a0656fc87.png)

![screen shot 2016-02-10 at 21 45 02](https://cloud.githubusercontent.com/assets/2098462/12961348/48ce6194-d040-11e5-9fd0-7aefee8bfe44.png)

So this can probably be closed?

**Comment by nathansobo** [comment] 2016-02-11 00:50
> So this can probably be closed?

/cc @lee-dohm

**Comment by lee-dohm** [comment] 2016-02-11 01:41
Yep, playing around with this for about five minutes I can't find an easy way to make this bug reproduce. I think it is safe to close it. Thanks @danieldiekmeier :grinning:

**Closed by lee-dohm** 2016-02-11 01:41 UTC
Labels: bug, editor-rendering
