### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by sharonrieger** [atom/atom#17420] opened 2018-05-29 14:50 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:663

TypeError: Cannot read property 'id' of undefined
    at extraRenderedScreenLines.forEach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:663:45)
    at Map.forEach (native)
    at TextEditorComponent.renderLineTiles (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:660:43)
    at TextEditorComponent.renderContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:601:18)
    at TextEditorComponent.renderScrollContainer (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:577:18)
    at TextEditorComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:522:20)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:392:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at didDrag (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1827:20)
    at get_window.requestAnimationFrame (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1902:17)
```

### Commands

```
     -4:33.4.0 core:paste (span.syntax--entity.syntax--name.syntax--function.syntax--ruby)
     -4:05.8.0 core:save (input.hidden-input)
     -3:02.8.0 snippets:next-tab-stop (input.hidden-input)
     -3:02.8.0 snippets:expand (input.hidden-input)
     -3:02.8.0 editor:indent (input.hidden-input)
 10x -2:58 core:backspace (input.hidden-input)
     -2:48 core:save (input.hidden-input)
     -2:26.6.0 snippets:next-tab-stop (input.hidden-input)
     -2:26.6.0 snippets:expand (input.hidden-input)
     -2:26.6.0 editor:indent (input.hidden-input)
     -2:25.1.0 editor:newline (input.hidden-input)
     -2:22.2.0 core:save (input.hidden-input)
  2x -2:11.8.0 core:move-up (input.hidden-input)
     -1:54.5.0 editor:newline (input.hidden-input)
     -1:41.2.0 core:backspace (input.hidden-input)
  2x -1:38 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-sass 0.4.0 
browse 1.10.6 
compare-files 0.8.1 
css-grid-snippets 1.1.0 
css-snippets 1.1.0 
cssbeautify 1.3.0 
local-storage 0.5.0 
open-in-developer-mode 0.3.0 
open-package 0.2.0 
open-recent 5.0.0 
open-terminal-here 2.3.2 
pigments 0.40.2 
ruby-snippets 0.2.1 
satisfy-dependencies 0.4.2 
save-workspace 0.5.0 
scroll-through-time 0.3.0 
teletype 0.13.0 
TerminalColor 1.1.0 
tool-bar 1.1.7 
tree-view-open-files 0.3.0 
```

**Comment by rsese** [comment] 2018-05-29 21:16
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16179 so you can subscribe there for updates if you'd like.  If you remember what you were doing at the time of the error or have steps to reproduce, feel free to let us know in https://github.com/atom/atom/issues/16179.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed** 2018-05-29 21:16 UTC
