### ISSUE TITLE
[UX] Settings pane checkbox not bound to labels (but act as if)

### ISSUE THREAD

**Issue by Krinkle** [atom/atom#7528] opened 2015-06-29 06:18 UTC
Hovering labels in the settings pane results in a pointer cursor. Holding down the cursor results in the checkbox lighting up.

Yet, unless clicking directly on the checkbox, it will not be checked upon clicking.

Clicking the labels should toggle the checkbox. Especially considering the existing hover and mousedown behaviour 

> Version 1.0.0 (1.0.0)
> Mac OS X 10.10.3

**Comment by mnquintana** [comment] 2015-06-29 10:20
Would you mind closing this and reopening on https://github.com/atom/settings-view?

**Comment by batjko** [comment] 2015-06-29 10:31
I agree with that enhancement, though. It's quite common to have the click area extend to the label these days.

**Comment by simurai** [comment] 2015-06-30 04:04
The labels should already be "clickable".

![labels](https://cloud.githubusercontent.com/assets/378023/8423687/3d00b804-1f28-11e5-9d93-d9b75f851b2a.gif)

If it doesn't work in your case, there must be another bug/reason.

**Comment by batjko** [comment] 2015-06-30 06:26
And so it is.
I should have actually tried it myself.

**Comment by izuzak** [comment] 2015-07-29 20:08
I can't reproduce this either. @Krinkle if you can still reproduce in Atom 1.0.3 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) -- please open an issue over at https://github.com/atom/settings-view

**Closed by izuzak** 2015-07-29 20:08 UTC
Labels: wrong-repo

**Comment by Krinkle** [comment] 2015-07-29 20:41
Yeah, I see it too now. Must've been some kind of intermittent issue. It definitely wasn't working that day. I see it in Chrome too sometimes, where the graphic manifestation of the cursor is out of sync with where Chrome thinks the cursor is.
