### ISSUE TITLE
Uncaught TypeError: Invalid Point: (177, NaN)

### ISSUE THREAD

**Issue by mikeybyker** [atom/atom#18818] opened 2019-02-08 13:57 UTC
[Enter steps to reproduce:]

1. Selected 2 lines, hit delete
2. Hit delete once more (to delete the remaining empty line)

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid Point: (177, NaN)

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Invalid Point: (177, NaN)
    at Function.t.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43907)
    at DisplayLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:85014)
    at DisplayMarkerLayer.t.exports.DisplayMarkerLayer.translateScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1093011)
    at DisplayMarker.t.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:3173258)
    at changePosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:521833)
    at Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:530377)
    at Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:521799)
    at Cursor.moveLeft (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:524621)
    at modifySelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:534433)
    at Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:547515)
    at Selection.selectLeft (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:534401)
    at Selection.backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:538925)
    at mutateSelectedText.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16061)
    at getSelectionsOrderedByBufferPosition.map (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16220)
    at Array.map (<anonymous>)
    at transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16209)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:491881)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39529)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16037)
    at TextEditor.e.(anonymous function) [as backspace] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:259365)
    at TextEditor.core:backspace (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:302187)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:307928
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:491881)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at HTMLElement.s.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:307871)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
```

### Commands

```
     -1:42 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -1:33 linter-eslint:fix-file (div.line)
  2x -0:51.6.0 core:backspace (input.hidden-input)
     -0:50.9.0 core:save (input.hidden-input)
     -0:47.5.0 linter-eslint:fix-file (div.line)
  2x -0:41 core:backspace (input.hidden-input)
     -0:39.5.0 core:save (input.hidden-input)
  2x -0:35.8.0 linter-eslint:fix-file (span.syntax--source.syntax--js)
  2x -0:06.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
angularjs 0.5.3 
atom-typescript 12.7.1 
busy-signal 1.4.3 
default-language 0.3.1 
emmet 2.4.3 
intentions 1.1.5 
language-markdown 0.27.0 
language-pug 0.0.22 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
prettier-atom 0.56.0 
react 0.18.0 
react-es6-snippets 0.3.0 
react-snippets 1.1.2 
sublime-block-comment 0.5.1 
```

**Comment by rsese** [comment] 2019-02-08 19:11
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/18725 so you can subscribe there for updates if you'd like. 

And just to clarify about your steps to reproduce, can you still reproduce now or is that what you remember doing when you saw the error (and you can no longer reproduce)?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-02-08 19:11 UTC
