### ISSUE TITLE
Python syntax highlighting can be broken by quoting 'DELETE' in a docstring

### ISSUE THREAD

**Issue by thomir** [atom/atom#12146] opened 2016-07-12 01:36 UTC
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I can cause the python syntax highlighting to render everything as a string (in green, by default) with the following python code:

```
class SomeClass:

    """This is a docstring with 'DELETE' in the first line.

    If the docstring contains another single quote anywhere in the body the
    rest of this file will be highlighted correctly.
    """

    def foo(self):
        pass # this should not be rendered in green!
```

Atom renders this like so:

![broken screenshot](http://static.inky.ws/image/5776/Screenshot%20from%202016-07-12%2013-21-57.png)

The key here seems to be that you need the word `DELETE` in either single quotes, double quotes, or backticks. `DELETE` by itself (i.e.- unquoted) is not enough to break the syntax highlighting. I've not found any other words that seem to produce this behaviour (I thought perhaps it was all HTTP methods, but PUT, GET, HEAD, etc don't trigger the same behaviour).  It's also curious that `DELETE` is rendered as a keyword here, when it probably shouldn't be.

### Steps to Reproduce

1. Copy the above snippet into a file ending in '.py'
2. Open the file in atom.

**Expected behaviour:** 

I expect everything past the first docstring to render correctly (i.e.- not as if it were all one large string).

**Actual behaviour:** 

See screenshot above.

### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11+
git 2.7.4

Operating system is Ubuntu 16.04, with all packages up to date.

**Comment by lee-dohm** [comment] 2016-07-12 06:39
This is a duplicate of https://github.com/atom/language-python/issues/143. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-07-12 06:39 UTC
