### ISSUE TITLE
Color Coding Breaking

### ISSUE THREAD

**Issue by KrunchMuffin** [atom/atom#9542] opened 2015-11-12 14:44 UTC
It's pretty self-explanatory in the image.
This is on Win10.

![image](https://cloud.githubusercontent.com/assets/1037197/11121073/d4b2d386-8921-11e5-917f-8c5e4d9522eb.png)

    <select data-parsley-ui-enabled="false" name="bill-state" id="bill-state" class="form-control input-sm">
        <option value="">State</option><option value="AL">Alabama</option><option value="AK">Alaska</option><option value="AZ">Arizona</option><option value="AR">Arkansas</option><option value="CA">California</option><option value="CO">Colorado</option><option value="CT">Connecticut</option><option value="DE">Delaware</option><option value="DC">District of Columbia</option><option value="FL">Florida</option><option value="GA">Georgia</option><option value="HI">Hawaii</option><option value="ID">Idaho</option><option value="IL">Illinois</option><option value="IN">Indiana</option><option value="IA">Iowa</option><option value="KS">Kansas</option><option value="KY">Kentucky</option><option value="LA">Louisiana</option><option value="ME">Maine</option><option value="MD">Maryland</option><option value="MA">Massachusetts</option><option value="MI">Michigan</option><option value="MN">Minnesota</option><option value="MS">Mississippi</option><option value="MO">Missouri</option><option value="MT">Montana</option><option value="NE">Nebraska</option><option value="NV">Nevada</option><option value="NH">New Hampshire</option><option value="NJ">New Jersey</option><option value="NM">New Mexico</option><option value="NY">New York</option><option value="NC">North Carolina</option><option value="ND">North Dakota</option><option value="OH">Ohio</option><option value="OK">Oklahoma</option><option value="OR">Oregon</option><option value="PA">Pennsylvania</option><option value="PR">Puerto Rico</option><option value="RI">Rhode Island</option><option value="SC">South Carolina</option><option value="SD">South Dakota</option><option value="TN">Tennessee</option><option value="TX">Texas</option><option value="UT">Utah</option><option value="VT">Vermont</option><option value="VA">Virginia</option><option value="WA">Washington</option><option value="WV">West Virginia</option><option value="WI">Wisconsin</option><option value="WY">Wyoming</option>
    </select>

**Comment by AluisioASG** [comment] 2015-11-12 15:05
Duplicate of #1667.

**Comment by 50Wliu** [comment] 2015-11-12 20:20
Thanks @AluisioASG.

**Closed by 50Wliu** 2015-11-12 20:20 UTC
