### ISSUE TITLE
Atom core Deprecated...

### ISSUE THREAD

**Issue by matinkaboli** [atom/atom#14748] opened 2017-06-10 00:00 UTC
How can i fix this = 
![atom](https://user-images.githubusercontent.com/16045374/26998118-6a9fef6c-4d95-11e7-87f4-477894cf33a8.png)

**Comment by ungb** [comment] 2017-06-10 00:39
Hey @matinkaboli,  can you provide more info by filling out the issue template?  

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀




### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-01-26 23:29
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/14748#issuecomment-307530335. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-01-26 23:29 UTC
Labels: more-information-needed

**Comment by Ben3eeE** [comment] 2018-01-29 09:08
This is a duplicate of https://github.com/atom/atom/issues/15734 and fixed in Atom 1.22 :slightly_smiling_face:
