### ISSUE TITLE
Request: Atom package dependencies

### ISSUE THREAD

**Issue by KSXGitHub** [atom/atom#11491] opened 2016-04-16 01:50 UTC
Some atom packages may be plugins of some other atom packages, so I suggest atom to install all packages listed at field `package-dependencies` of file `package.json`, it makes ability to integrate/extend atom packages easier.

At this moment, I can use [atom-package-dependencies](https://www.npmjs.com/package/atom-package-dependencies) to depend on other atom packages, the thing is:
 - Dependencies (which were installed implicitly & automatically) wouldn't be uninstall automatically when their dependents is uninstalled, so users must uninstall them manually & explicitly.
 - Users can disable/uninstall dependencies even when their dependents haven't been disabled/uninstalled, without any warnings or errors, the dependent packages still run without their dependencies.

**Atom Version:** 1.6.2
**OS and Version:** Windows 10 Pro 64-bit (10.0, Build 10586)

**Comment by lee-dohm** [comment] 2016-05-26 19:44
This is a duplicate of #2412. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-05-26 19:44 UTC
Labels: feedback
