### ISSUE TITLE
Atom Saving files but actually not saving ! help please

### ISSUE THREAD

**Issue by uzumakinaruto123** [atom/atom#10120] opened 2015-12-18 13:48 UTC
atom is behaving weirdly since few days ! Everytime i save a file atom is saving it but the changes are not saved.
   What i actually mean is , suppose i make changes to a css file atom saves it but on opening the same css with some other editor the new changes are not seen ! Even browser does not reflect any changes.
     Since last week it was happening only with javascript files , so only for javascript i had to use notepad++ and i ignored the issue !
    Today its happening with css file too ! i dont want to switch the editor since i like atom. 

I googled for the issue  but all were related to atom freezing etc. In my case atom does not freeze or doesn't even throw error ! Its just saving changes for itself....

**Comment by jeancroy** [comment] 2015-12-18 16:35
I've seen report of extension making error in the save event, thus preventing save from happening.

Can you try launching `atom --safe`and see if you can save file from there ?

**Comment by amytruong** [comment] 2015-12-18 19:42
@uzumakinaruto123 yikes, this doesn't sound good. 

Do you think you can give us more information? 
What OS and version of Atom are you on? 

Is it just javascript files or css files now too? Do you get any warning or error message?
Also, it would be great if you could try launching it in safe mode like :point_up: and let us know what happens. Thank you!

**Comment by alexandernst** [comment] 2015-12-19 12:30
@jeancroy No matter how many extensions crash, this should work flawlessly.

**Comment by jeancroy** [comment] 2015-12-19 14:09
And until then it is still useful to identify the source of the problem

**Comment by uzumakinaruto123** [comment] 2015-12-19 18:50
atom version 1.3.2
Windows 10

css files were saved later after restart , i think css was not atom issue ! but its still same with js files...!
i have not tried atom --safe yet !
  I will try it and report back , Thanks !

**Comment by MidGe48** [comment] 2016-02-13 02:17
I have the same problem 
Debian Jessie
Atom 1..4.3

**Comment by astronomersiva** [comment] 2016-02-24 06:45
Happens to me on Mac as well. No sort of error messages but JS files are not getting saved.

**Comment by farhanmannan** [comment] 2016-03-10 17:50
Same on Yosemite with Atom 1.5.4

**Comment by osm3000** [comment] 2016-05-26 12:10
I've the same problem
atom 1.7.4
ubuntu 16.04

**Comment by GHACCT** [comment] 2016-06-01 17:39
Same here. Atom 1.7.4 Mac OS working with React Native 0.24

**Comment by raslanove** [comment] 2016-06-14 13:20
The same problem, except that I'm trying to save a .txt file. Opening the file in Atom shows the file contents, however the file itself is 0 bytes and shows nothing in any other editor.

**Comment by modosc** [comment] 2016-06-14 18:46
i see it as well. if i explicitly close the file it gets flushed.  osx 10.11.15, atom 1.80

**Comment by highfiredanger** [comment] 2016-07-06 19:16
I have the same problem, all of the sudden. OS X 10.11.5, Atom 1.8.0.

**Comment by Bloodskate** [comment] 2016-07-07 14:15
same problem , started today all of a sudden

**Comment by Bloodskate** [comment] 2016-07-07 14:18
nevermind , found my mistake , moved the source files.

**Comment by seanlynch** [comment] 2016-07-11 04:15
Happening to me as well on Arch Linux with Atom 1.8.0. It's not encouraging that this has been open since December.

**Comment by rienk** [comment] 2016-07-19 01:28
This is happening to me also. When navigating the tree it shows my changes, but it doesn't change my js and html files. Don't know why. Lost a lot of time because I assumed at first it was a browser caching issue.

**Comment by Tyguy7** [comment] 2016-07-19 18:18
Bump.  Same here.  Pretty annoying.

**Comment by arslan2012** [comment] 2016-07-23 05:53
Bump. Same here. 
Ubuntu 16.04 with Atom1.10.0-dev-e92e2c0

**Comment by 50Wliu** [comment] 2016-07-23 12:39
Everyone experiencing this issue, please make sure that you can replicate it in safe mode (`atom --safe`) before commenting.

**Comment by dutchauser** [comment] 2016-07-28 07:28
Same here.
Linux Mint 17.2
Atom 1.8.0

Safe mode works fine, I have uninstalled all packages that I have added and the issue persists outside of safe mode.

**Comment by dutchauser** [comment] 2016-07-28 07:48
Ok so for me it is the php-cs-fixer package causing the issue.

**Comment by WoodyWoodsta** [comment] 2016-08-12 20:28
Not entirely sure if this is related: files are saving, but a `babel` watch process is building files as if they were empty at random (ie. build output of a file saved is empty). Often can be fixed by saving the file again. Confirmed that it is not babel itself by testing in `gedit`

**Comment by tkaria** [comment] 2016-09-03 15:49
Exactly the same issue as @WoodyWoodsta with exactly the same setup. Confirmed working in `atom --safe`.

**Comment by Zireael07** [comment] 2016-09-03 17:10
@WoodyWoodsta @tkaria: This means one of your packages is the culprit.

**Comment by tkaria** [comment] 2016-09-03 17:15
So time for process of elimination? Ugh.

Sent from my iPhone

On Sep 3, 2016, at 19:11, Zireael07 <notifications@github.com> wrote:

@WoodyWoodsta <https://github.com/WoodyWoodsta> @tkaria
<https://github.com/tkaria>: This means one of your packages is the culprit.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/atom/atom/issues/10120#issuecomment-244558182>, or mute
the thread

**Comment by 50Wliu** [comment] 2016-09-03 20:13
The general consensus here seems to be that `atom --safe` works, so I'm closing this issue.

**Closed by 50Wliu** 2016-09-03 20:13 UTC
Labels: data-loss, more-information-needed

**Comment by dfrho** [comment] 2016-11-18 01:29
Has anyone figured out which package is the culprit? Closing this issue with the assumption that Atom is 'unsafe' unless we use 'safe' mode seems premature.

**Comment by 50Wliu** [comment] 2016-11-18 01:37
> Closing this issue with the assumption that Atom is 'unsafe' unless we use 'safe' mode seems premature

Nothing was said about Atom being "unsafe" unless safe mode was used: the issue here is that an unknown community package not affiliated with the Atom organization is breaking the save function.  That is the fault of the package, not Atom.

In addition, you are not required to assume that there is a conflicting package if this is happening.  However, the first thing that you should be doing, as per the issue template when filing a new issue, is to check whether the behavior occurs in safe mode.  If it does, then please continue to create the issue so that we can take a look!

**Comment by dfrho** [comment] 2016-11-18 01:42
I said it - It's implied by how 'safe' mode is labeled. So yeah, it's doesn't happen in safe mode and I'd like it not to. Any JS file that's open in the right pane doesn't save when clicking command-S and only saves when closing the file and getting the save prompt. It's ruined several test environments for me and my instructors before realizing what was actually happening.

**Comment by 50Wliu** [comment] 2016-11-18 02:06
Ok, so if the issue is not present in safe mode the best advice that I can give to you is to try using the [package-cop](https://atom.io/packages/package-cop) package to determine which package is causing the issue.

> It's implied by how 'safe' mode is labeled

"Safe" in this context means that Atom is running in the safest-possible environment with as little external interference as possible, not that running normally is "unsafe".  Windows also uses this term.

Also, I noticed you rewrote your comment since my response, and I'll respond to that edited comment below.

> Kind of annoying that I have to use safe mode to make the software work

There are no guarantees that packages will work, and there is inherent risk in installing any software of any kind.

> How about requiring this TDD unit test for all packages submitted?

While a good idea in theory, this would quickly become unsustainable.  In your case, the test would have to enable the `language-javascript` package, open a JavaScript file, copy it to a new split pane on the right, and execute the `core:save` command.  That is an extremely specific test, and if we were to do that for every bug that was caused by a community package, the required maintenance quickly starts to outweigh the possible benefits.

> they told me Atom is FULL of bugs like this.

If you could please ask your "fellow students" to submit issues (if they haven't already), that would be much appreciated 🙇.

**Comment by WoodyWoodsta** [comment] 2016-11-18 07:03
The most that I've been able to narrow this down to is the fact that it is a combination of `babel` (`chokidar` for that matter) and Atom. My workaround was to hack the `chockidar` implementation in `babel` to increase the debounce period.

**Comment by JTMartins** [comment] 2016-11-23 17:54
I have the same problem. Only when I do a SAVE AS it actually saves. I only have ATOM-bootstrapp 3 (1.2.12) and atom-html-preview(0.1.22)

**Comment by Ben3eeE** [comment] 2016-11-23 18:01
@JTMartins if you can reproduce the issue after starting Atom in safe mode `atom --safe` then open a new issue and completely fill out the provided issue template.

**Comment by BangFizz** [comment] 2016-12-16 12:52
I have the same problem with Atom 1.12.7 on macOS Sierra 10.12.2.
All yesterday's work go source files gone. It happened to me before, but figured it was my own fault. This time I saved all the time, yet none of the changes were actually saved.
Ditching Atom for good.

**Comment by 50Wliu** [comment] 2016-12-16 17:45
@BangFizz if you can reproduce the issue after starting Atom in safe mode `atom --safe` then open a new issue and completely fill out the provided issue template.

**Comment by isoceles** [comment] 2017-05-25 16:59
Same issues. on 1.17.1. I just lost about an hour or mores with of work. All the files were saved or else it wouldn't render the changes. Upon restarting the app, half the code I wrote is gone. WTF?

**Comment by 50Wliu** [comment] 2017-05-25 17:08
@isoceles if you can reproduce the issue after starting Atom in safe mode atom --safe then open a new issue and completely fill out the provided issue template.

**Comment by dunkinman** [comment] 2017-07-10 18:12
This problem seems to be happening again?  I haven't tried safe mode...but noticed that CSS updates are being saved in Atom but not in the actual text file on my laptop.

**Comment by ryanaleksander** [comment] 2017-08-15 02:47
Updated to 1.19.1 and got this issue, uninstalled Platform IDE Terminal (which seems to be not working) then everything works fine again

**Comment by philoliver** [comment] 2017-08-15 07:49
Hi @ryanaleksander, I am facing the same problem in 1.19.0, how I install Plattform IDE Terminal?

**Comment by binczakmartin** [comment] 2017-08-18 14:06
atom 1.19.2
windows 10

I have the same issue, I tried to reinstall atom but it's still not working.

**Comment by dunkinman** [comment] 2017-08-18 20:56
For me, I still have issues with CSS from time to time, I've found the best way to resolve the problem is to remove the project folder from Atom and then readd it.  When I do this it seems to resolve the issue.

**Comment by Dylanbauer** [comment] 2017-09-10 07:40
I was just having this issue or one close to it. I was able to fix it by going into my folder with all my files and double checking to see if there were two .css. There was and i just had to delete the old one and make sure when i saved that i saved the right one and deleted the old.

**Comment by keerthi2909** [comment] 2017-09-28 10:13
Hi,
 I am coding in html and css. My content is saved in the file but when i open my browser, it doesn't reflect any changes i have made.. so frustrating...

**Comment by keerthi2909** [comment] 2017-09-28 10:15
i am using atom 1.20.1 in windows 8

**Comment by lutzray** [comment] 2017-11-21 03:15
same problem here (and Atom started in -safe mode): after clicking "Save" the dirty mark doesn't disappear and the file isn't saved (coherent!). Seems to be related to permissions and/or filesystems. Local files are modified and saved OK but not files in a sshfs mounted directory, although permissions, ownership and group of sshfs'd files are OK (set with -o uid=zz,gid=xx)

Atom 1.22.1
Mac OS 10.12.6

**Comment by bulletkid** [comment] 2018-01-22 06:43
This has started happening again on 1.23.3 on Windows 10 platform in both normal and safe mode.

Thanks
Manu

**Comment by QLaille** [comment] 2018-02-07 14:54
as @bulletkid said, it once again occured on 1.23.3 under Ubuntu 16.04
![screenshot from 2018-02-07 15-53-32](https://user-images.githubusercontent.com/24566679/35922907-1b469d3c-0c1f-11e8-880f-4a092a41b3ee.png)

**Comment by Ben3eeE** [comment] 2018-02-08 15:34
@QLaille @bulletkid if you can reproduce the issue after starting Atom in safe mode `atom --safe` then open a new issue and completely fill out the provided issue template.

**Comment by bulletkid** [comment] 2018-03-26 16:01
This is a reproducible issue in safe mode. The problem was that "Setting>File Encoding" was set to Nordic. 
So maybe it was just me being an idiot but I would've thought that this is a catchable error.
@QLaille can you please confirm that your file encoding is set up properly and we can lay this issue to rest

**Comment by Ben3eeE** [comment] 2018-03-26 18:24
@bulletkid Can you please open a new issue about being unable to save when the encoding is set to Nordic? Thank you 🙇!

**Comment by monowm4** [comment] 2018-05-04 15:26
The vast range of configurations postered in this and many other issue reports clearly implies is a **platform-wide flow**, and a HUGE and worrisome one. In the entire business logic of the app, no foreign process should be capable to mess with the core functionality of saving the changes created, that is **BASIC**. Never experienced an issue like this on brackets, and for god sake I'm going back to its polished performance before letting it ruin a project or jeopardize our business operation.  For atom, it should be ABSOLUTE PRIORITY to **publicly warn the development community** this can and might happen in unknown cases or scenarios, because **LOSING JOB DONE AND YOUR JOB IN ACCORDANCE is a possibility at this stage.**

**Comment by crconline** [comment] 2018-06-07 17:14
I can now save in --safe mode... but no installed packages appear in my session, how can I save my files and get all support of my packages, like autocomplete????

**Comment by sfranco1124** [comment] 2018-08-10 11:55
I have only one file that I am not able to save completely. When I press save, I lose half of my text file and it saves like that. If I do redo, the file cames back ok.. The encoding is set to unicode UTF-8. The line from where my text dissapear doesn't has any special character, only end of line. It's a very bad issue! I agree with monowm4, I can't use this sofware for my job. I don't have the issue at home with Linux Mint, but I have the issue at my job using Windows 10.

**Comment by Aerijo** [comment] 2018-08-10 12:00
@sfranco1124 Does it happen in safe mode? (open Atom with `atom --safe`)

If not, you would need to find which community package you have that is causing the issue (or possibly something in your `init` script).

**Comment by sfranco1124** [comment] 2018-08-10 12:37
Hi Aerijo,
I was able to save with notepad++. Also, I use Atom from a week only... It'snot a good excuse, but my hard-drive was full after a fpga simulation. The issue was only because I didn't have any space. Notepad was OK for a few minutes and finally advise me that I don't have any space now.. sorry, but at least it's working!

**Comment by elinorapricot** [comment] 2018-09-16 00:42
Solution:

I get this error after installing several packages. I uninstalled them, and I can save my files after that. I guess one of the installed packages caused this for me.
