### ISSUE TITLE
可不可以统一管理快捷键!!!

### ISSUE THREAD

**Issue by crperlin** [atom/atom#8478] opened 2015-08-22 11:46 UTC
可不可以统一管理快捷键!!!(比如在当前快捷键列表的基础上,增加双击修改,或者取消功能)

各种插件的快捷键,互相覆盖;很乱....

造成各种冲突....下一个版本可以考虑解决这个问题么...

非常感谢!!!!

**Comment by batjko** [comment] 2015-08-22 16:20
If you can, could you please rephrase your issue into English?
As far as I know, none of the maintainers or devs of this repository know how to read this and shouldn't be asked to translate it themselves.

**Comment by lee-dohm** [comment] 2015-08-22 17:16
This is what the automatic Chrome translation came up with:

> Can !!! unified management shortcuts (such as on the basis of the current list of shortcuts on the increase, double-click to modify, or cancel function)
>
> Shortcuts various plug-ins, each covering; mess ....
>
> Cause conflicts .... next version could be considered to solve this problem what ...
>
> Thank you very much!!!!

In which case, I suspect it is a duplicate of https://github.com/atom/atom-keymap/issues/82

**Comment by batjko** [comment] 2015-08-22 18:15
Good guess.

**Comment by tcbbd** [comment] 2015-08-27 21:31
Astonished that there's an issue written in Chinese here. I hope this will not lead to bad impression on us Chinese developers. And I suggest a new title `manage shortcuts in a unified way`.

**Comment by 50Wliu** [comment] 2015-08-27 23:52
So the basic gist here is that he wants a better system to manage key bindings and add/modify/remove them since they currently can conflict with each other, etc.
Then he asks if the next version of Atom can fix this.
And finally, thanks very much.

Therefore I think this is more of a duplicate of atom/settings-view#163 than atom/atom-keymap#82.

**Comment by lee-dohm** [comment] 2015-08-27 23:55
> I hope this will not lead to bad impression on us Chinese developers.

It definitely will not lead to a bad impression. It just makes things a little more time consuming :grinning:

**Comment by batjko** [comment] 2015-08-28 05:15
Thanks, @tcbbd and @50Wliu.

**Comment by crperlin** [comment] 2015-09-20 16:21
thankyou very much，I haven't write english ，because my english  very poor…so sorry😣

**Comment by mnquintana** [comment] 2015-09-20 16:41
No worries @crperlin!

Since this is a duplicate I'm going to close this out in favor of https://github.com/atom/settings-view/issues/163.

**Closed by mnquintana** 2015-09-20 16:41 UTC
Labels: duplicate
