### ISSUE TITLE
Is it called atom because...

### ISSUE THREAD

**Issue by forkoz** [atom/atom#17608] opened 2018-07-01 02:21 UTC
It nukes your hard drive with gigs of dependencies sans user consent? All I wanted to do was compile one project using platformIO.... 

1. Atom installed by itself to wherever it wanted. I ran the executable and went to use the bathroom. I came back to it installed, trying to run github and attempting to connect to the internet.

2. So uhm ok I guess, lets try installing PlatformIO. The module is ~500mb simple enough... nope. Installing dependencies, which ones... what's this thing doing... I see its installing python 2.7; I have both x64 and x32 python 2.7 already. Why is python connecting to the internet? BSOD! But I boot back and platformIO core is installed. Or is it? Since atom is still installing... what I have no idea.

3. The folders in my user directory that I can identify; .atom, atom, .platformio have stopped growing for a while but atom is still downloading something and spawning node.js processes. It has been over 45 minutes.... an hour... an hour and a 1/2... is it compiling? they why does it want internet access and why is it only using 1 of the processes it spawned?

Seems to me I would have been better off installing visual studio or any other solution. I feel totally violated by this software and left wondering just what it did and if it will remove completely when I uninstall it. I've only seen this kind of behavior from malware or windows 10 consumer editions, to see it in an open source project aimed at developers is definitely a shock. If this is the 21st century, I've gotta to start building my time machine.

Update: It went all night and didn't finish. I uninstalled and surprise surprise most of atom doesn't get removed.

**Comment by rsese** [comment] 2018-07-01 21:39
Thanks for reporting and I'm sorry you had a bad experience trying to get up and running with Atom, I'll share some comments below.  One thing to mention is that PlatformIO is community package that we didn't create so we can't answer questions about everything it's doing when you try to install it.  They have their own support community here where it looks like people have asked about installation issues:

https://community.platformio.org/

Of course it's still being installed through Atom so there are things that could be done better on our end if a package install is problematic.  If you want to share specific suggestions, please let us know.

> Atom installed by itself to wherever it wanted. I ran the executable and went to use the bathroom. I came back to it installed, trying to run github and attempting to connect to the internet.

Yes that's correct, the installer framework we use installs Atom to a specific location.  We do provide archive files however that lets people extract Atom where they want:

https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode

> So uhm ok I guess, lets try installing PlatformIO. The module is ~500mb simple enough... nope. Installing dependencies, which ones... what's this thing doing... I see its installing python 2.7; I have both x64 and x32 python 2.7 already. Why is python connecting to the internet? BSOD! But I boot back and platformIO core is installed. Or is it? Since atom is still installing... what I have no idea.
> 
> The folders in my user directory that I can identify; .atom, atom, .platformio have stopped growing for a while but atom is still downloading something and spawning node.js processes. It has been over 45 minutes.... an hour... an hour and a 1/2... is it compiling? they why does it want internet access and why is it only using 1 of the processes it spawned?

Though there are things that Atom could do better here, the details about what the PlatformIO package is doing would best be answered by the PlatformIO maintainers like I mentioned above.

> Update: It went all night and didn't finish. I uninstalled and surprise surprise most of atom doesn't get removed.

Not sure what parts you're referencing here but we do specifically leave the `.atom` directory in the home directory so settings and packages are retained if someone reinstalls later on.  There is feedback though where folks would like this removed as well during uninstall on Windows that's captured in https://github.com/atom/atom/issues/7346.

I'm sorry again for the trouble here and I'll share your feedback with the rest of the team.  We'll also close this since we treat our issues list as [specific individual tasks that need to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), and we close general feedback issues.  But if you have specific reproducible problems that you'd like to report individually in more detail, feel free to open an issue with the issue template filled out and we'll take a look.

**Closed by rsese** 2018-07-01 21:39 UTC
