### ISSUE TITLE
Middle-mouse closing unsaved files locks the desktop environment

### ISSUE THREAD

**Issue by bbb31** [atom/atom#15370] opened 2017-08-17 15:09 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`'untitled' has changes, do you want to save them?` prompt causes my Desktop Environment to freeze.

### Steps to Reproduce

1. Create a new file: File > New file
2. Put some content in this new *unsaved* file
3. **Middle mouse click** to close the file; you will not be able to click anywhere; you need to use ALT+TAB functionality to move to a different window. **If you click the x** of the file tab you will *not* reproduce this issue

**Expected behavior:** I expect it to not freeze my DE

**Actual behavior:** It freezes my DE; forcing me to `killall atom`

**Reproduces how often:** 100% of the time

### Versions

```
$ atom --version
Atom    : 1.19.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
```

This is with XFCE, not Cinnamon.

**Comment by rsese** [comment] 2017-08-17 18:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15197. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-17 18:15 UTC
