### ISSUE TITLE
Opening (and closing) the settings tab resets the "invisibles" configuration

### ISSUE THREAD

**Issue by hmemcpy** [atom/atom#6033] opened 2015-03-19 12:55 UTC
I've customized my `invisibles` to never show `eol` and `cr` characters, by modifying my `config.cson` like this:
```cson
"*":
  editor:
    invisibles:
      eol: ''
      cr: ''
      ...
```

It seems that after installing a package (in my case, I installed `autocomplete-html`), the entries for `eol` and `cr` are removed from the config, and it resets to:
```cson
"*":
  editor:
    invisibles: {}
    ...
```

Am I holding it wrong, or is this a bug?

**Comment by izuzak** [comment] 2015-03-20 14:14
I'm having trouble reproducing this, @hmemcpy -- installing packages doesn't change the `invisibles` hash in config.json for me. 

Questions:
* which version of Atom are you using?
* which OS?
* which other packages do you have installed? `$ apm list --installed`
* can you reproduce this after you uninstall all those other packages and restart Atom?
* can you reproduce this by installing any package?

**Comment by hmemcpy** [comment] 2015-03-22 08:15
Hi @izuzak!
Sorry for the late reply. I wanted to repro this as best as I could - turns out this has nothing to do with installing a plugin, but just opening (and therefore saving) the settings - when opening the settings tab, it resets the invisibles. I made a screencap demonstrating the problem.

OS: Windows 10 build 9926
Atom: 0.187.0
Packages:
```
apm list --installed
C:\Users\Igal\.atom\packages (6)
├── autoclose-html@0.15.0
├── autocomplete-html@0.5.0
├── browser-refresh@0.8.3
├── git-plus@4.4.8
├── monokai@0.12.0
└── open-in-browser@0.4.2
```

Video:
[Imgur](http://i.imgur.com/1WloG8p.gifv)

**Comment by hmemcpy** [comment] 2015-03-22 10:12
Looks like this is a known bug since October 2014: https://github.com/atom/settings-view/issues/237

**Comment by izuzak** [comment] 2015-03-22 11:40
Great -- thanks for investigating this. Yeah, definitely looks like atom/settings-view#237, I'm going to close this then and please subscribe to that issue for updates. :pager:

**Closed by izuzak** 2015-03-22 11:40 UTC
Labels: more-information-needed
