### ISSUE TITLE
Window freeze after moving tabs

### ISSUE THREAD

**Issue by kahmij** [atom/atom#17947] opened 2018-08-29 22:21 UTC
OS: Arch with i3

If i want move a tab it freeze and i have to kill the process to restart atom.

![deepinscreenshot_select-area_20180830001954](https://user-images.githubusercontent.com/36455663/44818759-6af5f100-abea-11e8-84d1-ff3266d26c3a.png)

**Comment by rsese** [comment] 2018-08-30 21:47
Thanks for reaching out!

Besides filing out the template as mentioned below, this sounds like a duplicate of https://github.com/atom/tabs/issues/541 so you can subscribe there if you'd like.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Closed by rsese** 2018-08-30 21:47 UTC
