### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 618Error: Cannot cal...

### ISSUE THREAD

**Issue by okou-joe** [atom/atom#16971] opened 2018-03-17 06:53 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 618
Error: Cannot call function 'getPosition' on missing remote object 618
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 618
Error: Cannot call function 'getPosition' on missing remote object 618
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:691:40)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:728:40)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:191:32)
```

### Commands

```
  4x -1:51.9.0 core:backspace (input.hidden-input)
     -1:50.4.0 core:move-up (input.hidden-input)
     -1:50.1.0 editor:newline (input.hidden-input)
     -1:48.8.0 autocomplete-plus:confirm (input.hidden-input)
     -1:48.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  4x -1:47.2.0 core:move-down (input.hidden-input)
     -1:46.2.0 autocomplete-plus:confirm (input.hidden-input)
     -1:45.7.0 core:save (input.hidden-input)
     -1:31.4.0 core:copy (input.hidden-input)
     -1:29.4.0 core:paste (input.hidden-input)
     -1:28.9.0 core:save (input.hidden-input)
     -0:36.8.0 core:copy (input.hidden-input)
     -0:35.4.0 core:paste (input.hidden-input)
  2x -0:34.9.0 core:save (input.hidden-input)
     -0:17.3.0 core:backspace (input.hidden-input)
     -0:16.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.17 
git-plus 7.10.2 
highlight-selected 0.13.1 
intentions 1.1.5 
japanese-menu 1.14.0 
language-ejs 0.4.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
project-manager 3.3.5 
show-ideographic-space 1.0.2 
tag 0.5.0 
```

**Comment by rsese** [comment] 2018-03-19 19:25
Thanks for the report - this looks like a duplicate of #16630 so you can subscribe there for updates if you'd like.  If you remember what you were doing at the time of the error or if you can reproduce, please let us know in #16630.  Also, do you happen to remember if you tabbed out of Atom  and then switched back when you saw the error?

---

Because we treat our issues list as the Atom team's backlog, we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see the How Can I Contribute? section of the Atom CONTRIBUTING guide.

**Closed by rsese** 2018-03-19 19:25 UTC
