### ISSUE TITLE
Open files from Terminal in new tabs

### ISSUE THREAD

**Issue by yustnip** [atom/atom#8693] opened 2015-09-06 18:37 UTC
When I want to open a file via Terminal it opens in a new window instead a new tab. Example of the command: ```atom index.html```

I've not found any solution to set up such behavior. Atom help on ```atom -h``` suggests to use the flag ```-n``` to open file in a new window but it doesn't have any flag for a new tab.

Linux, Atom version 1.0.11

**Comment by pulvirenti** [comment] 2015-09-07 21:03
Hi, I would like to start contributing to this project and I would like to give a go at providing the feature mentioned above.

**Comment by izuzak** [comment] 2015-09-08 16:14
Strange, I'm unable to reproduce this on OSX. Can someone on Linux reproduce this problem? 

Also, @yustnip -- just to make sure we're doing the same thing as you are, can you please post step-by-step instructions which reproduce the problem for you? Assume I haven't started Atom yet.

+a friendly :bell: to @maxbrunsfeld who likes hearing about these kinds of problems :grin:

**Comment by yustnip** [comment] 2015-09-08 17:34
I'm realy very sorry. Now I've tried to reproduce the problem but now all is correct, new files open in new tabs. I don't know why before was another behavior.

**Comment by mnquintana** [comment] 2015-09-08 19:06
Thanks for the update @yustnip! I'm going to close this out for now - feel free to comment though if you run into this again!

**Closed by mnquintana** 2015-09-08 19:06 UTC
Labels: needs-reproduction
