### ISSUE TITLE
Atom doesn't remember my open folders or files at all

### ISSUE THREAD

**Issue by classicboss302** [atom/atom#7303] opened 2015-06-16 20:50 UTC
If I close Atom with some files and folders open, and then reopen Atom, nothing is remembered. The only thing that is open is a new blank file.

I feel like this worked at some point in the past for me, but I wasn't able to find a version that worked when I tried the specific zip files. I am currently using 0.209.0. I also tried this with --safe and the same thing happens.

I can see that the editor-giberish files are being created in the storage folder, but I never see Atom try to read those files when I launch Atom. I used Procmon to check for this access.

**Comment by mnquintana** [comment] 2015-06-16 20:53
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/7231– this has been fixed already for the next release of Atom 0.210.0.

**Closed by mnquintana** 2015-06-16 20:53 UTC
