### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Projects/iriss-web/client/assets/image...

### ISSUE THREAD

**Issue by danmartens** [atom/atom#14946] opened 2017-07-03 15:31 UTC
[Enter steps to reproduce:]

1. Move an image file (or probably any non-text file) to a new location (e.g. from "forum-welcome.png" to "forum/welcome.png")
2. Open the file via Command + P before Atom has finished reindexing
3. Click on the tab that Atom has opened for the file which no longer exists

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/dan/Projects/iriss-web/client/assets/images/forum-welcome.png'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/Users/dan/Projects/iriss-web/client/assets/images/forum-welcome.png'
  at Error (native)
  at fs.statSync (fs.js:992:18)
  at Proxy.fs.statSync (ELECTRON_ASAR.js:275:16)
  at new ImageEditorView (<embedded>:94758:48)
  at ImageEditor.get (<embedded>:49092:33)
  at ImageEditor.get (<embedded>:49086:24)
  at ViewRegistry.module.exports.ViewRegistry.createView (<embedded>:16995:41)
  at ViewRegistry.module.exports.ViewRegistry.getView (<embedded>:16978:27)
  at atom-pane.PaneElement.itemRemoved (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:186:37)
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63093:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63209:34)
  at Pane.module.exports.Pane.removeItem (<embedded>:26175:26)
  at Pane.module.exports.Pane.destroyItem (<embedded>:26247:22)
  at TabBarView.module.exports.TabBarView.closeTab (<embedded>:59806:32)
  at TabBarView.module.exports.TabBarView.closeOtherTabs (<embedded>:59870:35)
  at Object.TabBarView.addElementCommands.tabs:close-other-tabs (<embedded>:59563:32)
  at HTMLUListElement.commandsWithPropagationStopped.(anonymous function) (<embedded>:59549:42)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (<embedded>:18901:35)
  at CommandRegistry.handleCommandEvent (<embedded>:18639:65)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (<embedded>:18802:25)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (<embedded>:1554:34)
  at EventEmitter.outerCallback (<embedded>:2012:31)
  at emitThree (events.js:116:13)
  at EventEmitter.emit (events.js:194:7)

```

### Commands

```
     -3:11 core:move-left (input.hidden-input)
  3x -3:10.7.0 core:backspace (input.hidden-input)
     -3:10.2.0 core:paste (input.hidden-input)
  4x -3:09.5.0 core:move-down (input.hidden-input)
     -3:08.9.0 core:save (input.hidden-input)
  4x -3:04.0 core:move-up (input.hidden-input)
     -3:03.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:02.8.0 core:move-left (input.hidden-input)
  3x -3:01.5.0 core:move-up (input.hidden-input)
     -3:01.0 core:move-to-top (input.hidden-input)
     -3:00.9.0 core:save (input.hidden-input)
  2x -2:53.4.0 core:backspace (input.hidden-input)
     -2:52 core:save (input.hidden-input)
  2x -2:47.3.0 core:undo (input.hidden-input)
     -2:46.4.0 core:save (input.hidden-input)
     -0:06.3.0 tabs:close-other-tabs (div.title)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-handlebars 1.3.0 
base16-ocean-dark 1.2.0 
base16-ocean-light-syntax 0.3.0 
busy-signal 1.4.3 
docblockr 0.10.5 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.66.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.10 
language-slim 0.5.0 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ruby 1.2.5 
linter-ui-default 1.6.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.236.0 
nuclide-format-js 0.0.36 
prettier-atom 0.35.1 
redux-devtools 0.5.1 
set-syntax 0.3.2 
sort-lines 0.14.0 
spacegray-dark-ui 0.13.0 
tool-bar 1.1.0 
```

**Comment by rsese** [comment] 2017-07-03 21:25
Thanks for the report!

I think this is basically a duplicate of https://github.com/atom/image-view/issues/74 so you may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-03 21:25 UTC
