### ISSUE TITLE
Less optional imports fail to parse in UI and syntax themes

### ISSUE THREAD

**Issue by matthewlucock** [atom/atom#13569] opened 2017-01-08 10:45 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

This issue cannot be reproduced in safe mode, as it concerns external themes. I have met the other prerequisites.

### Description

When a UI or syntax theme which uses a Less file that contains an [optional import](http://lesscss.org/features/#import-options-optional) is selected, the Less file in question fails to parse and the theme fails to activate.

### Steps to Reproduce

1. Clone [atom-community/ui-theme-template](https://github.com/atom-community/ui-theme-template).
2. In `index.less`, change `@import "styles/ui-variables";` to `@import (optional) "styles/ui-variables";`.
3. Run `apm link` in the root of the repository.
4. Navigate to the themes section of the settings screen and select "Ui Theme Template" from the UI themes dropdown list.

It also reproduces with syntax themes.

1. Generate a syntax theme using `package-generator:generate-syntax-theme` from [atom/package-generator](https://github.com/atom/package-generator).
2. In `index.less`, change `@import "./styles/base.less";` to `@import (optional) "./styles/base.less";`.
3. Navigate to the themes section of the settings screen and select the generated theme from the syntax themes dropdown list.

**Expected behavior:** The theme activates successfully.

**Actual behavior:** The theme fails to activate, and a "Error compiling Less stylesheet" notification message is displayed with the message "expected ')' got 'o'".

**Reproduces how often:** Every time.

### Versions

Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Microsoft Windows [Version 10.0.14393]

### Additional Information

Attempting to use an import option that Less does not support (e.g. foobar) yields an error message of the same format e.g. expected ')' got 'f'. [According to the Less changelog](https://github.com/less/less.js/blob/master/CHANGELOG.md#230), optional imports were added in 2.3. At current, [less-cache uses 2.7.1](https://github.com/atom/less-cache/blob/v0.24.0/package.json#L31). I have tested Less 2.7.1 separately, and optional imports parsed without error. Less' other import options seem to parse in themes without any issue.

**Comment by 50Wliu** [comment] 2017-01-08 17:13
The problem is that we use [less-cache@0.23](https://github.com/atom/atom/blob/157e8e1c740c1b4ef90c31325ffd11c9497fa7ab/package.json#L43), which in turn uses [less@1.x](https://github.com/atom/less-cache/blob/v0.23.0/package.json#L30).

However, as there's technically nothing wrong (we aren't using Less 2 at the moment), I'm going to close this issue.  We're working to upgrade less-cache in https://github.com/atom/atom/pull/12176.

**Closed by 50Wliu** 2017-01-08 17:13 UTC
