### ISSUE TITLE
Curly bracket mismatch if string contains it

### ISSUE THREAD

**Issue by klaszlo** [atom/atom#11971] opened 2016-06-13 08:38 UTC
Consider the following code in the text editor:

    var t = function() {
     var str = '{';
     if (true) {
       console.log('hmm');
     }
    };

The '}' highlighting do not find the correspondant opening bracket.

Recently I needed to find { in a string t.indexOf('{'), which is kind of rare usecase. 

atom 1.8, ubuntu linux.

**Comment by hultberg** [comment] 2016-06-13 10:26
Assuming this is javascript, this should be reported to the [atom/language-js](https://github.com/atom/language-javascript) repo.

**Comment by 50Wliu** [comment] 2016-06-13 20:25
This is a duplicate of atom/bracket-matcher#78 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-13 20:25 UTC
