### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 31Error: Cannot call...

### ISSUE THREAD

**Issue by goldtreefrog** [atom/atom#17891] opened 2018-08-21 17:25 UTC
[I do not know if I can reproduce it. I was making many small changes, running 'npm test' after each (using Mocha Chai). I think it happened when I saved the test file, but it did not reoccur the next time I saved it.]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 31
Error: Cannot call function 'getPosition' on missing remote object 31
    at throwRPCError (C:\Users\marga_000\AppData\Local\atom\app-1.29.0\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\marga_000\AppData\Local\atom\app-1.29.0\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\marga_000\AppData\Local\atom\app-1.29.0\resources\electron.asar\browser\api\web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At C:\Users\marga_000\AppData\Local\atom\app-1.29.0\resources\electron.asar\renderer\api\remote.js:221

Error: Cannot call function 'getPosition' on missing remote object 31
Error: Cannot call function 'getPosition' on missing remote object 31
    at throwRPCError (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/renderer/api/remote.js:125:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.29.0/resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.29.0/resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.29.0/resources/app/src/window-event-handler.js:191:32)
```

### Commands

```
  2x -1:59.5.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:58.7.0 core:select-down (input.hidden-input)
     -1:58.3.0 core:delete (input.hidden-input)
     -1:54.1.0 docblockr:parse-enter (input.hidden-input)
     -1:54.1.0 editor:newline (input.hidden-input)
     -1:53.6.0 core:move-up (input.hidden-input)
     -1:52.7.0 docblockr:parse-tab (input.hidden-input)
     -1:52.7.0 snippets:next-tab-stop (input.hidden-input)
     -1:52.7.0 snippets:expand (input.hidden-input)
     -1:52.7.0 editor:indent (input.hidden-input)
  3x -1:29.8.0 core:move-down (input.hidden-input)
     -1:28.5.0 core:move-up (input.hidden-input)
  4x -1:28.2.0 core:move-left (input.hidden-input)
     -1:26.5.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:20.5.0 core:save (input.hidden-input)
     -1:19.1.0 linter:lint (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-bootstrap4 1.4.0 
atom-live-server 2.3.0 
atom-wrap-in-tag 0.6.0 
autocomplete-modules 2.1.0 
block-and-line-comment 0.4.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
chrome-color-picker 0.8.0 
copy-path 0.5.1 
docblockr 0.13.7 
emmet-simplified 2.6.0 
ficus-dark-syntax 2.1.0 
file-icons 2.1.22 
git-diff-details 1.4.0 
git-plus 8.0.0 
intentions 1.1.5 
isotope-ui 2.8.5 
language-babel 2.85.0 
language-haml 0.31.1 
linter 2.2.0 
linter-bootlint 1.1.0 
linter-eslint 8.4.1 
linter-jshint 3.1.8 
linter-ui-default 1.7.1 
open-in-browsers 0.0.30 
open-recent 5.0.0 
open-terminal-here 2.3.2 
open-unsupported-files 1.0.20 
pigments 0.40.2 
prettier-atom 0.54.0 
react 0.18.0 
sorter 1.2.1 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.4 
toggle-quotes 1.1.0 
tree-view-copy-relative-path 1.2.0 
turbo-javascript 1.4.0 
v-bootstrap4 0.2.1 
```

**Comment by rsese** [comment] 2018-08-21 17:45
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-08-21 17:45 UTC
