### ISSUE TITLE
Missing api docs for TextEditorElement

### ISSUE THREAD

**Issue by puranjayjain** [atom/atom#11530] opened 2016-04-19 18:08 UTC
Expected: https://atom.io/docs/api/v1.7.2/TextEditorElement to go to the correct api
Result: a 404 error

**Comment by 50Wliu** [comment] 2016-04-19 19:27
This is a duplicate of atom/flight-manual.atom.io#128 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-19 19:27 UTC

**Comment by puranjayjain** [comment] 2016-04-19 20:10
@50Wliu sorry my bad
