### ISSUE TITLE
Visible lines break on large files

### ISSUE THREAD

**Issue by prosaiccode** [atom/atom#16356] opened 2017-12-11 22:49 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Files with more than 800,000 lines result in a visual error. Atom doesn't display the contents after line 798,915 of a 1,180,094 line file (22 MB). 

### Steps to Reproduce

1. Have file with more than 1,000,000 lines of stuff
2. Open Atom
3. Load File
4. Scroll down

**Expected behavior:** [What you expect to happen]
The file to be readable from lines 798,916 to infinity.

**Actual behavior:** [What actually happens]
You are still able to edit the file past the visual break. Saving works as intended as well.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%, line 798,916 to infinity is not visible.

### Versions
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
Win10

### Additional Information
Atom isn't quite as responsive while the file is opened. Atom takes about 5 seconds to close the file.  Atom's memory spikes almost 5x as much as the file when editing the file. UTF-8, PLAIN TEXT. Opening a project project containing a large file takes a considerable amount of time .(related to: https://github.com/atom/teletype/issues/175). Windows 10.

**Comment by rsese** [comment] 2017-12-12 00:00
Thanks for the report!

> You are still able to edit the file past the visual break

Can you clarify what you mean by "visual break" here?  Also, can you share a screenshot of what the editor looks like at line 798,915 for you?

I created a file with 1,180,094 lines and I also see the content not displaying after a certain line (line 883,011 in my case) and it looks like this:

![no-more-lines](https://github-slack.s3.amazonaws.com/monosnap/test.dat__sandboxmake-test-file_2017-12-11_17-59-23.png)

**Comment by prosaiccode** [comment] 2017-12-12 01:38
That's exactly what I mean by visual break. I didn't think about other systems having different line lengths (this bug needs a new title). 
I figured I was at the max because my system specs are overkill for atom, apparently not, gimme yo pc!

**Comment by rsese** [comment] 2018-01-12 06:16
Sorry just circling back to this - I re-tested on the latest beta (`1.24.0-beta3) and could still reproduce but I noticed on master (`1.25.0-dev-2cb66ae9e`) that I can't reproduce anymore so this should be fixed in the upcoming 1.25 releases.  If not, we can always re-open.

**Closed by rsese** 2018-01-12 06:16 UTC
Labels: editor-rendering, more-information-needed
