### ISSUE TITLE
atom keeps crashing

### ISSUE THREAD

**Issue by NicoleHall** [atom/atom#14996] opened 2017-07-11 23:16 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I uninstalled and reinstalled node and npm. When I did this, it caused atom to keep crashing every time I tried to work on my React project
### Steps to Reproduce

1. I did the safe mode and it still kept crashing
2. I disabled all of my installed packages
3. when I try to open the directory with my react project atom will crash
4. I can however work on a ruby file

**Expected behavior:** I expected to be able to work on my project without atom crashing and enable the packages that I needed and see if they give me trouble

**Actual behavior:** Atom crashed before I could do any work at all
**Reproduces how often: ** 100% of the time while working in a directory that only has a node modules and a package.json file

### Versions
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.9.2

OSX El Capitan
version 10.11.6

**Comment by daylightbrightledlight** [comment] 2017-07-13 02:15
The following is not really a solution, as it will simply reset Atom to use default settings:

1. Quit Atom
2. Open a terminal and enter the following:
```bash
mv ~/.atom ~/.atom-backup
```
3. Open Atom

This will essentially rename your `.atom` folder to `.atom-backup`. This is to keep a backup. Atom should create a new `.atom` folder in your home directory after launching it again. Does that make Atom work again? Hopefully that will get you back up and running if that is the priority.

If you want to revert this, simply rename `.atom-backup` back to `.atom` and relaunch Atom.

**Comment by iconmaster** [comment] 2017-07-14 16:48
Perhaps similarly, Atom is crashing frequently for me today. I did not reinstall npm but I did update from v4 to v5. Crash logs attached here.

[crash-logs.zip](https://github.com/atom/atom/files/1149119/crash-logs.zip)

**Comment by rsese** [comment] 2017-07-14 19:47
> 3. when I try to open the directory with my react project atom will crash

Based on this @NicoleHall, it sounds like the crash happens specifically when opening this project and you can't reproduce with another project?

If you temporarily disable the GitHub package, does Atom still crash for you?

Also, if you can share any crash logs you found like @daylightbrightledlight mentioned (:bow:), that could be helpful.

**Comment by rsese** [comment] 2017-07-14 19:47
@iconmaster - I see an out of memory error in your crash log so I'm wondering if you're hitting:

https://github.com/atom/github/issues/953

Can you confirm if Atom still crashes if you temporarily disable the GitHub package?

**Comment by iconmaster** [comment] 2017-07-14 19:50
Yes -- for me, disabling the `github` package has solved the crashing.

**Comment by rsese** [comment] 2017-07-14 20:16
Thanks for confirming @iconmaster :v:  You can subscribe to https://github.com/atom/github/issues/953 for updates if you'd like, looks like there could be a potential fix /cc https://github.com/atom/github/issues/953#issuecomment-315204783.

**Comment by lee-dohm** [comment] 2017-07-20 23:29
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/14996#issuecomment-315450791. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by lee-dohm** 2017-07-20 23:29 UTC
Labels: crash, more-information-needed
