### ISSUE TITLE
Uncaught Error: spawn mono ENOENT

### ISSUE THREAD

**Issue by stealthkk** [atom/atom#4894] opened 2015-01-07 16:11 UTC
[Enter steps to reproduce below:]

1. ctrl + alt + o to open AtomSharp
2. get exception

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn mono ENOENT

```
At events.js:85

Error: spawn mono ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
     -1:07.9 project-manager:toggle (atom-text-editor.editor.is-focused)
     -1:06.6 core:confirm (atom-text-editor.editor.mini)
 18x -0:36.7 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 omnisharp-atom:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 13,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
jshint, v1.1.3
language-cshtml, v0.1.0
linter, v0.9.1
omnisharp-atom, v0.1.6
project-manager, v1.14.1

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-01-07 16:35
Looks like a duplicate of https://github.com/OmniSharp/omnisharp-atom/issues/42.

**Closed by izuzak** 2015-01-07 16:35 UTC
