### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by maissani** [atom/atom#5159] opened 2015-01-20 14:47 UTC
[Enter steps to reproduce below:]

1.Put some music and devellopers file on a folder
2. Open the folder with atom
3. clic on a music and it will crash atom because atom try to read it.

**Atom Version**: 0.170.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At c:\Users\maissani\AppData\Local\atom\app-0.170.0\resources\app\src\project.js:360

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (c:\Users\maissani\AppData\Local\atom\app-0.170.0\resources\app\src\project.js:360:15)
  at Project.module.exports.Project.bufferForPath (c:\Users\maissani\AppData\Local\atom\app-0.170.0\resources\app\src\project.js:337:63)
  at Project.module.exports.Project.open (c:\Users\maissani\AppData\Local\atom\app-0.170.0\resources\app\src\project.js:291:19)
  at Workspace.module.exports.Workspace.openUriInPane (c:\Users\maissani\AppData\Local\atom\app-0.170.0\resources\app\src\workspace.js:487:29)
  at Workspace.module.exports.Workspace.open (c:\Users\maissani\AppData\Local\atom\app-0.170.0\resources\app\src\workspace.js:414:19)
  at Ipc.<anonymous> (c:\Users\maissani\AppData\Local\atom\app-0.170.0\resources\app\src\window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (c:\Users\maissani\AppData\Local\atom\app-0.170.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-01-20 14:48
Duplicate of #307 

Hopefully coming soon!

**Comment by maissani** [comment] 2015-01-20 14:50
This appear when you have a folder with music and some developpers file.
if you click on music instead of doing nothing atom crash and display the current message.
This is not a duplicate.

**Comment by lee-dohm** [comment] 2015-01-20 17:03
As the issue is currently worded, it is a duplicate. If you feel that Atom shouldn't attempt to load files that aren't text files ... then that is a different issue and the title at least should be rewritten.

Please update the issue with what you feel the problem is and what you think Atom should do differently, @maissani.

**Comment by kevinsawicki** [comment] 2015-01-20 18:17
Closing as duplicate of #307

**Closed by kevinsawicki** 2015-01-20 18:17 UTC
