### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.32.2\res...

### ISSUE THREAD

**Issue by jtackesiii** [atom/atom#18416] opened 2018-11-09 21:12 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\jtack\AppData\Local\atom\app-1.32.2\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:166

Error: The specified module could not be found.
\\?\C:\Users\jtack\AppData\Local\atom\app-1.32.2\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:1:623185)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:3073054)
    at get_manager (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:3073134)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:3073260)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:996407)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1224708)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1222693)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:282763)
```

### Commands

```
     -1:31.1.0 core:save-as (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by vijeth94** [comment] 2018-11-10 00:59
How do you solve the above problem?

**Comment by jtackesiii** [comment] 2018-11-10 02:02
I solved it by uninstalling/reinstalling atom

**Comment by rsese** [comment] 2018-11-12 21:17
Thanks for contributing!

We noticed that this looks like a duplicate of #14461 so you can subscribe there for updates if you'd like.   Reinstalling Atom like you did seems to clear things up though we've also heard that anti-virus might be related based on other people's comments.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-12 21:17 UTC
