### ISSUE TITLE
ENH: Find in find results output

### ISSUE THREAD

**Issue by dbarboza** [atom/atom#10867] opened 2016-02-17 19:33 UTC
In Sublime, you can search in the search results output. This searches the filenames of the results as well as the match text. This is very useful when you have a vague search with many results. I use this a lot for searching for function definitions.

The steps in Sublime are:
ctrl+shift+F > search for stringA > Shows normal search output
ctrl+F > search for stringB > Searches in the search output only

Currently searching Atom search output does not seem to happen, but the "No results for <searchTerm>" is updated.

**Comment by 50Wliu** [comment] 2016-02-17 20:43
@dbarboza This is a duplicate of atom/find-and-replace#133 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-17 20:43 UTC
