### ISSUE TITLE
Add an option to disable "quick jump" between indents

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/atom#3174] opened 2014-08-04 07:09 UTC
In Atom, it's not possible to begin or end a selection at the midpoint of an indent, because the caret can't be jumped there. But as a text editor, I think it should be able to do anything a normal text editor can do, regardless of whether it's meaningful or not.

My suggestion: leave the default "as is", but add an option to disable the "quick jump".

**Comment by marcoms** [comment] 2015-04-13 21:01
Any updates on this issue? This is certainly annoying when, for example, writing multiline strings in Python which have spaces for presentational purposes, whereas source code is indented in tabs. Since tabs and (" " * tab-width) are indistinguishable in the editor, maintaining code like this in Atom is not at all feasible.

**Comment by maxbrunsfeld** [comment] 2015-04-15 18:15
I think the ideal behavior would be to treat spaces as individual characters when inside of a `string` scope , but to otherwise do what we do now. This appears to be what sublime does.

**Comment by Hufschmidt** [comment] 2015-05-07 08:54
Personally I think the best solution would just be to give us an option/setting to make soft-tabs non-atomic. (As suggested by multiple people)
I'd be fine with that.

**Comment by Abdillah** [comment] 2015-07-29 18:01
Note: 
Bug #6048, which more relevant with this comment, has been closed and marked as duplicate with this one.

I feel `core:backspace` command has annoying behaviour in soft-tab mode, if not wrong (It is intended as I see in other comments). This is because it makes spaces with length matching tab-width's will be treated as tab.

Here I have a usecase, showing it is not the "right" behaviour.

### Configuration
+ Soft-tab enabled
+ Tab-width is 4.
+ Show invisible (for demo)

### Case
When we have some function with __first long arguments__ (so it will be multiple lines). Therefore, the next argument (using my style where arguments has the same column on multiline) will be arbitary located on certain column.
```
my_func (first_arg_very_long,
         second_arg_in_tenth_column_is_not_divisible)
```

### Problem
Demo:
![backspace-annoy](https://cloud.githubusercontent.com/assets/3030950/8964822/fc358124-3651-11e5-93e0-9176d5e010b7.gif)

If my first argument start at column which is not divisible by soft-tab width, say 11. Then, I want to indent correctly into exactly under the start of first argument, it makes me press tabs till column 8 beyond that I must pressing spaces till it goes to 11. This is the ideal way.

But sometime, I got excessive key press...

If I get some excessive step, say into 12, I need to press <kbd>Backspace</kbd> first (which delete 4 spaces) then add three spaces after it. __Look!__ 4 steps necessary.
This happened to me so often.

### Expected
I think command `core:backspace` should treating space as it is. So, pressing <kbd>Backspace</kbd> will delete exactly one space. This way, above case can be done exactly in one press.

It will be more flexible and smooth. Moreover, deleting 4 spaces at once has been very good accomplished by `editor:outdent-selected-row` command: <kbd>Shift</kbd>+<kbd>Tab</kbd>. This key is as comfortable to press as <kbd>Tab</kbd> itself.

This expectation is similar to how other text editor behave, which I won't mention them.

__Should I report it as new issue?__

**Comment by jhasse** [comment] 2015-08-03 17:04
@Abdillah I think this should rather be fixed by detecting whether backspace is deleting an indentation (stick with current behaviour) or when deleting formatting spaces (only delete one at a time then).

**Comment by Abdillah** [comment] 2015-08-04 07:35
Yes, If we prefer customizability, it should exist an option (explicit or implicit) to change that..

**Comment by nathansobo** [comment] 2015-08-04 17:44
I'm open to this, but it's not a priority for me. If someone wants to open a PR with tests that makes atomic leading whitespace configurable, I'd be happy to interact with them on it. Check out `TokenIterator.prototype.isAtomic` and play around with opting out for leading whitespace... Not sure what the other implications would be, but that's a place to start.

**Comment by Abdillah** [comment] 2015-08-07 03:07
Thanks for the hint (and warning). 
I'm not yet have time to start on it. 
Will wait for someone instead..

**Comment by ckelner** [comment] 2015-10-19 18:27
:+1: really annoying

**Comment by chris-martin** [comment] 2015-10-23 19:20
This behavior is crazy. Not *every* line in a file must line up with the tab lines.

For example (python):

```python
def foo():
    """
    This thing works like this:

                    a
                   /  \
                 b    c
    """
```

Try playing around with that ascii graph in Atom with indent size set to 4. It's... unnecessarily difficult.

**Comment by eterevsky** [comment] 2015-11-05 10:51
I always thought that I somehow misunderstand the settings. I'm really surprised that it's by design, and that it is impossible to disable this feature in the settings. I would expect that the default behavior should to use indentation length for Tab / Shift-Tab, but to delete single characters by Del / Backspace. Isn't it the default behavior of the absolute majority of code editors?

Could anyone please explain to me the benefit of this design/UX decision?

**Comment by timdiller** [comment] 2015-11-30 17:36
As a Python developer, I'll add my voice to the chorus of requests that leading whitespace not be atomic.  @Abdillah has demonstrated the awkwardness I'm experiencing.  The current behavior in Atom makes it hard to line up code that's not on an existing tab-stop.  Sublime has the behavior I would like of jumping to tab stops with Tab, Shift-Tab, and Backspace, and moving single spaces with the arrow keys and forward delete.

**Comment by mko** [comment] 2016-02-03 19:24
I'll also voice my discomfort at the implementation of this "feature." It really makes editing some files (especially in Python) significantly more complicated than it should be, and it makes cleaning up old files that someone else has written (who didn't use EditorConfig or a linter) much more difficult. Real-world scenarios don't always support a heavy-hand on leading whitespace as "indents" either, especially with differing code styles (some people use comma-first JS where the comma and first space don't count as part of the indent while others use the comma and first space as part of the indent).

IMO, it seems like this should be an option in Settings.

**Comment by adeftu** [comment] 2016-02-10 04:13
+1
Just installed Atom and after 20 min of playing with it, found this incredibly annoying "feature". First editor I encounter that simply doesn't let me place the cursor at any position in the text. After almost 2 years of complaints, this issue is still not high on dev's priority list.

**Comment by craigotis** [comment] 2016-02-24 18:39
+1
I spent a good bit of time trying to figure out (with invisibles turned off) why I couldn't get Atom to insert spaces instead of tabs, even though I triple checked all my settings.

As a last resort, I checked in another editor and found that in fact, they _were_ spaces, but the behavior of my arrow key in Atom made them seem very much like tabs.

This is a very unintuitive feature, and I'd like a way to turn it off.

**Comment by jordwalke** [comment] 2016-04-04 23:41
I have to say - I've never had such difficulty configuring an editor to have an intuitive arrow key behavior. I think the reason _why_ people even prefer soft tabs in the first place, is so that they can later move in between spacings one character width at a time. I've used every popular editor, and none of them seemed to confuse me like Atom's behavior does. There are some comments/alignments that I simply cannot even create/edit without using `atom-vim-mode` shortcuts to operate on individual characters. 

I would propose: Even with soft tabs, the arrow keys (at the very least, but you could also imagine the backspace behaving similarly), will move between individual characters.

**Comment by indigo0086** [comment] 2016-04-05 17:03
+1
I first thought this issue was caused by my vim plugin but sadly it's just a "feature".  Please, Atom evaluate these usability issues that just make it frustrating to code.  I dropped most other IDE's because this had far less nagging issues, but they still exist.

**Comment by elharo** [comment] 2016-04-06 15:20
+1 There's deep wrongness here. Atom's whitespace handling seems seriously broken by design. (This is not the only such issue.)

**Comment by ikari7789** [comment] 2016-04-14 02:32
Personally, I feel it should work like this:

- If soft-tab mode is enabled
    - Treat spaces as spaces in all cases except as noted below
    - between new line and content start
        - tab
            - insert spaces to closest tab stop
        - shift-tab
            - delete X spaces as defined by tab size in settings (does not delete new line)
        - backspace
            - delete to closest tab stop
        - delete
            - delete one character ahead
    - after content start
        - tab
            - insert X spaces as defined by tab size settings
        - shift-tab
            - insert X spaces as defined by tab size settings
        - backspace
            - delete one character behind
        - delete
            - delete one character ahead

- If soft-tab mode is disabled
    - Treat spaces as spaces in all cases.

**Comment by patoezequiel** [comment] 2016-04-19 20:24
+1

This is so annoying when aligning associative arrays in PHP. My config is Hard tabs, auto align.

**Comment by kimsaehun** [comment] 2016-04-21 00:31
+1

I would also like to voice my displeasure with this feature. I would very much like to have an option to disable this 'feature' somehow. Please send help.

**Closed** 2016-05-04 18:46 UTC
Labels: editor-rendering, enhancement

**Comment by 50Wliu** [comment] 2016-05-04 19:42
At the current pace of development this feature should become available starting in Atom 1.9.0.

**Comment by mko** [comment] 2016-05-04 19:53
Is effe882a8d602ad4ab4a5762a772a0a4083c5ecc supposed to resolve this issue? There must be some related commits that actually implement the `atomicSoftTabs` option in order for this to be "Closed".

**Comment by jordwalke** [comment] 2016-05-04 19:56
It looks like some changes might have gotten dropped from that commit accidentally.

**Comment by 50Wliu** [comment] 2016-05-04 21:03
No, it's just that effe882 was part of a much larger PR, #11414.  To make sure I just tested this and it's working fine! :sparkles:

**Comment by mko** [comment] 2016-05-04 21:42
Thanks for the clarification.

**Comment by kimsaehun** [comment] 2016-05-04 21:51
I sincerely thank whoever fixed this issue. This had really bugged me. I will eagerly await the new release.

**Comment by jordwalke** [comment] 2016-05-04 22:48
Can't wait for the next release!

**Comment by mb21** [comment] 2018-01-09 09:53
Fixed for me by turning off "Atomic Soft Tabs" in the "Editor Settings".
