### ISSUE TITLE
Blurry rendering when switching between Retina/Non-retina screens

### ISSUE THREAD

**Issue by kottkrig** [atom/atom#9226] opened 2015-10-20 11:39 UTC
I use Atom on a MBPr (15" Late 2013) plugged into an Apple Thunderbolt Display. When I unplug the external display while Atom is running the editor goes all blurry. And when I plug it back in again I see a weird rendering issue where only the top-left quarter of the editor is rendering.

![skarmavbild 2015-10-20 kl 13 21 35](https://cloud.githubusercontent.com/assets/52966/10605783/77360c78-772e-11e5-93d0-99784452f44e.png)

*Atom running on an Apple Thunderbolt Display.*

![skarmavbild 2015-10-20 kl 13 21 48](https://cloud.githubusercontent.com/assets/52966/10605844/e829cf14-772e-11e5-8c66-06017cadab20.png)

*Atom on retina display after unplugging the Apple Thunderbolt Display. (The blurriness is most noticable when comparing the text in the window bar and the text in the editor)*

![skarmavbild 2015-10-20 kl 13 22 07](https://cloud.githubusercontent.com/assets/52966/10605886/3b5a4498-772f-11e5-8c07-fd549a373452.png)

*Atom running on Apple Thunderbolt Display after being disconnected and then re-connected.*

## Repro Steps

1. Connect external monitor with different dpi than internal monitor
2. Start Atom
3. Disconnect external monitor
4. Connect external monitor

**Expected:** Atom should transition seamlessly between different DPIs.
**Actual:** Editor is blurry when switching from LDPI screen to HDPI screen and fails completely when transitioning back to LDPI again.

## Versions

* **Atom:**       1.0.19
* **OS:**         Mac OS X 10.11

---

**Comment by nathansobo** [comment] 2015-10-20 16:16
This seems like an Electron issue. @jlord have you ever seen this with other Electron apps?

**Comment by jlord** [comment] 2015-10-20 16:23
@nathansobo I've definitely seen it in Atom but haven't intentionally tested with other Electron apps—but I'll do that later today when I'm back at my desk :+1:

**Comment by jlord** [comment] 2015-10-20 17:19
Hmm, trying to force it to happen and it's not, even on Atom. I will keep other Electron stuff open today and periodically check and I move on/off monitor to laptop.

**Comment by billybonks** [comment] 2015-10-20 17:38
i think the blurry effect is a chrome issue, since it happens in chrome as well. but that white block issue seems to be an atom issue. i don't use other electron apps.

**Comment by kottkrig** [comment] 2015-10-21 07:24
If you are having troubles reproducing this issue – is there anything I can do to help? The issue is very consistent on mine and my colleague's setup. It's happening every time.

**Comment by aarfing** [comment] 2015-10-21 18:27
I have the exact same behaviour on a MBPr (15" mid 2012), when plugging in and out of a Thunderbolt Display - just to back @kottkrig up.

**Comment by thomassnielsen** [comment] 2015-10-22 16:17
It seems like Electron doesn't implement `- applicationDidChangeScreenParameters:` in it's application delegate. That might be why this happens. I'm not familiar enough with Electron to try a fix, but what I would suggest is to call the equivalent of `setNeedsDisplay` on the windows when this method is called by the system.

**Comment by jlord** [comment] 2015-10-22 16:31
Blerg, I'm still having trouble purposefully reproducing this in Atom and other Electron apps (have had [Git-it](https://github.com/jlord/git-it-electron) and [Playback](https://github.com/mafintosh/playback) open though I don't think Playback has anything to turn blurry actually)

**Comment by nathansobo** [comment] 2015-10-22 16:46
> It seems like Electron doesn't implement `- applicationDidChangeScreenParameters`: in its application delegate

@zcbenz thoughts on this?

**Comment by brandonb927** [comment] 2015-10-23 05:10
I think I'm experiencing a very similiar issue as @kottkrig which I can reproduce 100% of the time: my setup is a 15" 2015 rMBP + Dell 27" s2715h monitor using mDP->DP connector. Didn't have this issue in the very early version of Atom 1.0, but noticed it around 1.0.6 or so. Problem happens when unplugging my external monitor every time, have to close atom and reopen it to fix the text blurriness.

**Comment by cjolly** [comment] 2015-10-26 22:15
I can confirm this problem as well, MBP 13" -> HDMI External monitor. I've encountered when dragging between full screen hi res to lower res external monitor. 

Problem can be avoided by going out of full screen mode on laptop, dragging to external lower res monitor, then maximizing. Reversing the process if going from the external to the laptop.

Atom 1.0.19
OSX 10.11

**Comment by FrenchBen** [comment] 2015-11-05 21:33
+1 on the same issue. Additionally going from External -> MBP the font loses its crisp semi-antialiasing features. Only a restart of Atom will allow it to be clean again

**Comment by dorkrawk** [comment] 2015-11-05 23:33
I'm also seeing these issues.  The glitchy display is usually fixed by resizing the window or dragging it to another screen.

Atom 1.1.0
OSX 10.11.1

I used to see the blurriness issue in Chrome, but it was fixed a little while ago.

**Comment by driskell** [comment] 2015-11-06 08:53
Reproduced for me 100% of time too. Two issues I think:

With external non-retina monitor attached and lid down on retina laptop, have Atom open.
Disconnect monitors and later on open lid.
Issue 1: Blurry windows - doesn't appear to realise it is now on retina.

Close lid and later on reconnect non-retina monitors and wake laptop without opening lid.
Issue 2: Atom appears but only quarter of the window is rendered

**Comment by brentburg** [comment] 2015-11-11 19:43
This is 100% reproducible for me too. 

- MBP Retina screen -> Lid closed external monitors: only shows a quarter of the window, fixed by resizing the window.
- Lid closed external monitors -> MBP Retina screen: blurry text, fixed by reloading

This is especially annoying for me as I am constantly switching between laptop and external monitors throughout the day.

As for it potentially being an electron issue, I don't get the same behavior with Slack.I am not sure if it is using a different version though.

**Comment by kottkrig** [comment] 2015-11-20 12:06
1.2.0 seems to have completely solved this issue for me.

**Comment by brandonb927** [comment] 2015-11-20 16:22
I've noticed that the issue has become moot as well. Anyone know when this was solved?

**Comment by 50Wliu** [comment] 2015-11-20 16:38
Nice to hear this was resolved!  It was probably through a minor Electron update.

**Closed by 50Wliu** 2015-11-20 16:38 UTC
Labels: bug, mac
