### ISSUE TITLE
Normal mode switches to different keyboard layout

### ISSUE THREAD

**Issue by atd** [atom/atom#8210] opened 2015-08-04 11:10 UTC
I'am using a Spanish keyboard layout. Everything works as it expected. But in normal mode, the keyboard keys are mapped to other layout, which is a QWERTY, but I could not identify the variant (it is not US)

Its a fresh install of Atom (1.0.3) on Debian testing, vim-mode 0.57.0

**Comment by mnquintana** [comment] 2015-08-04 11:28
Thanks for the report! I think this is a duplicate of https://github.com/atom/atom-keymap/issues/37 though – please subscribe there for updates.

**Closed by mnquintana** 2015-08-04 11:28 UTC

**Comment by atd** [comment] 2015-08-04 11:34
Sure! Thank you
