### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1478Error: Cannot ca...

### ISSUE THREAD

**Issue by Saltani** [atom/atom#20091] opened 2019-10-31 16:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1478
Error: Cannot call function 'getPosition' on missing remote object 1478
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /usr/share/atom/resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 1478
Error: Cannot call function 'getPosition' on missing remote object 1478
    at throwRPCError (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705395)
    at AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app/static/<embedded>:1:705810)
    at WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -5:05.6.0 core:copy (input.hidden-input)
     -4:34.7.0 core:save (input.hidden-input)
     -3:34.8.0 tree-view:paste (div.tool-panel.tree-view)
     -3:32.5.0 core:select-all (input.hidden-input)
     -3:30.8.0 core:paste (input.hidden-input)
     -3:21.9.0 core:copy (input.hidden-input)
     -3:01.9.0 core:paste (input.hidden-input)
     -2:54.9.0 core:select-all (input.hidden-input)
     -2:53.4.0 core:copy (input.hidden-input)
     -2:31.6.0 core:paste (input.hidden-input)
     -2:25.9.0 core:select-all (input.hidden-input)
     -2:24.8.0 core:copy (input.hidden-input)
     -2:08.6.0 core:paste (input.hidden-input)
     -2:01.2.0 core:select-all (input.hidden-input)
     -1:59.7.0 core:copy (input.hidden-input)
     -0:13.2.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
jquery-snippets 11.0.0 
```

**Comment by rsese** [comment] 2019-11-04 04:50
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

If the error is reproducible for you, please us know the steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).  It would also be helpful to know if you can reproduce with the current stable [Atom release](https://atom.io/latest) which is running Electron 4.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-04 04:50 UTC
