### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by bnvk** [atom/atom#8652] opened 2015-09-03 10:07 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app.asar/src/pane.js:607

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:607:15)
    at Pane.module.exports.Pane.split (/usr/share/atom/resources/app.asar/src/pane.js:692:15)
    at Pane.module.exports.Pane.splitDown (/usr/share/atom/resources/app.asar/src/pane.js:664:19)
    at atom-pane.atom.commands.add.pane:split-down (/usr/share/atom/resources/app.asar/src/pane-element.js:280:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:156:19)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```

### Commands

```
     -0:31.9.0 markdown-preview:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:13.1.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:00.9.0 pane:split-down (div.markdown-preview.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-09-03 10:09
@bnvk Can you try updating to the latest version of Atom which is 1.0.11? You're still on 1.0.0. 

Let us know if that doesn't help

**Comment by bnvk** [comment] 2015-09-03 10:37
@izuzak yep, that was it, thanks so much! Strange I wasn't prompted to autoupdate!

**Comment by photex** [comment] 2015-09-22 10:56
[Enter steps to reproduce below:]

1. split pane
2. close tab

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:631

Error: Pane has been destroyed
  at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:631:15)
  at Pane.module.exports.Pane.focus (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:209:21)
  at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:59:23)

```

### Commands

```
     -2:29.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:29.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:29.9.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -2:29.2.0 atomic-emacs:previous-line (atom-text-editor.editor.is-focused)
     -2:20.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:18.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -2:16.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:16.3.0 window:save-all (atom-text-editor.editor)
     -0:46 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:31.5.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:30.9.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:28.7.0 pane:split-down (atom-text-editor.editor.is-focused)
     -0:27.1.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:25.2.0 window:focus-next-pane (atom-text-editor.editor.is-focused)
     -0:24.7.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:19.4.0 pane:split-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "projectHome": "/projects",
    "themes": [
      "base-16-ocean-dark-ui-theme",
      "base16-ocean-dark-spacegray"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 100,
    "showIndentGuide": true,
    "lineHeight": 1.25,
    "scrollPastEnd": true,
    "fontFamily": "Source Code Pro"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.13
atomic-emacs, v0.7.3
autocomplete-glsl, v0.2.3
autocomplete-python, v0.5.3
base-16-ocean-dark-ui-theme, v1.5.1
base16-ocean-dark-spacegray, v0.12.0
ionide-fake, v1.0.3
ionide-fsharp, v1.1.1
ionide-fsi, v1.0.4
ionide-installer, v1.2.1
ionide-paket, v2.0.8
ionide-yeoman, v1.0.1
language-cmake, v0.1.4
language-rust, v0.4.5
linter, v1.6.0
racer, v0.17.2

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-09-22 11:54
@photex I'm not able to reproduce that problem using the steps you provided. I noticed that you have a few packages installed. Can you reliably reproduce the problem when those packages are enabled, and can you still reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) (i.e. all packages disabled)? Thanks for adding a comment!

**Comment by photex** [comment] 2015-09-22 13:11
@izuzak looks like an issue with ionide. Was raising and exception during startup in fact about not finding  mono. Somehow that seems to place it into a bad state?
Thanks for the suggestion.

**Comment by AEgan** [comment] 2015-10-07 20:06
Getting this issue now and figured I'd leave a comment

Steps to reproduce:
1. Open markdown file
2. Open markdown preview
3. close all other tabs and panels, so only markdown preview remains open
4. Try to split pane in any direction

All packages are up to date. Could this be a problem with [atom/markdown-preview](https://github.com/atom/markdown-preview)?

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:631

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:631:15)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:722:15)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:686:19)
    at atom-pane.atom.commands.add.pane:split-right (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:273:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)
```

### Commands

```
  2x -0:34.7.0 core:close (atom-text-editor.editor.is-focused)
     -0:32.2.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-nucleus-dark-ui)
     -0:31.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:30.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -0:25.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:24.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:24.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:24.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:21.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -0:14.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:13 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13 markdown-preview:toggle (atom-text-editor.editor)
     -0:09.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:01.1.0 pane:split-right (div.markdown-preview.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "close-tags",
      "autoclose-html",
      "atom-pair",
      "linter-rubocop",
      "linter",
      "vim-mode"
    ],
    "themes": [
      "nucleus-dark-ui",
      "atom-material-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
atom-material-syntax, v0.2.4
color-picker, v2.0.13
editor-stats, v0.17.0
minimap, v4.13.4
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
nucleus-dark-ui, v0.5.14
toggle-packages, v1.0.1

# Dev
toggle-packages, v1.0.1
```

**Comment by izuzak** [comment] 2015-10-08 17:28
Thanks, @AEgan -- I'm seeing that as well, so I'm reopening this.

Even if this is a problem in markdown preview, Atom should be smarter about blaming that package in the exception, instead of Atom core. But I think it

/cc @nathansobo for more :thought_balloon:

**Comment by nathansobo** [comment] 2015-10-19 21:21
Seeing a lot of these exceptions in bugsnag, so I'm going to put this on my list of issues to investigate more deeply this week.

**Comment by 50Wliu** [comment] 2016-02-21 01:11
The Markdown Preview error is due to the original tab that contained the markdown being closed.  When attempting to split the Preview, markdown-preview tries to look for the original tab, and when it can't find it, immediately deletes the pane.  However we're still trying to add the preview over in `pane.coffee` to the (now) deleted pane, which leads to this error.  The other pane-related issues may be better suited over at #10903.

**Comment by yaffeweb** [comment] 2016-03-09 21:26
[Enter steps to reproduce below:]

1. Split a browser plus window down and then close it. 
2. Try and open a new browser plus window. 
This doesn't seem to have any effect if the browser plus is split to the right, only when you close it from the bottom. The pane still stays there but the plugin has closed. When trying to reopen the plugin then this error is thrown.

**Atom Version**: 1.5.4
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Pane has been destroyed

```
At C:\Users\kcrow\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane.js:631

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (C:\Users\kcrow\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane.js:631:15)
    at Pane.module.exports.Pane.focus (C:\Users\kcrow\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane.js:207:21)
    at atom-pane.<anonymous> (C:\Users\kcrow\AppData\Local\atom\app-1.5.4\resources\app.asar\src\pane-element.js:50:23)
```

### Commands

```
     -4:51.4.0 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:51 core:paste (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:50.6.0 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:50.2.0 core:paste (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:49.9.0 editor:newline (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:49.5.0 core:paste (atom-text-editor.editor.autocomplete-active.is-focused)
     -3:15.8.0 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -2:36.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:35.7.0 core:paste (atom-text-editor.editor.is-focused)
     -2:23.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:20.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:58 tabs:split-right (li.tab.sortable.active.right-clicked)
  3x -1:27.5.0 browser-plus:open (atom-text-editor.editor.is-focused)
     -0:47.1.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
  2x -0:25.1.0 pane:close (ul.list-inline.tab-bar.inset-panel)
     -0:11.9.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 100,
    "softWrap": true,
    "softwrap": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-live-server, v1.2.5
autoclose-html, v0.23.0
browser-plus, v0.0.54
open-in-browser, v0.4.6

# Dev
No dev packages
```

**Comment by pythe** [comment] 2016-07-12 01:00
For what it's worth, you may be able to work around this issue by splitting left instead of right. Worked for me in one instance, anyhow.

**Comment by invernizzie** [comment] 2016-09-09 19:33
I see release after release of atom not fixing this... it's so annoying to reload the window every time this happens, how come it's not a priority?

**Comment by nathansobo** [comment] 2016-09-09 20:42
@invernizzie I was under the impression it's a bug in the package. Can you post a full stack trace next time it happens?

**Comment by AEgan** [comment] 2016-09-09 21:01
👋  @nathansobo

same steps as before:
1. Open markdown preview
2. Close tab that the markdown file is in
3. attempt to split pane while focused on the markdown preview

I did some more testing, and figure it's worth noting that I cannot reproduce this with the editor core setting "Remove Empty Panes" __disabled__. My guess would be that splitting a pane with that setting enabled might attempt to generate the preview from the markdown file, which had just been closed, where the disabled option will result in an empty pane and no error. I've never looked at the code for markdown preview, so that's just my guess ¯\\_(ツ)_/¯.

Hope that helps, and thanks for taking a look!

**Atom Version**: 1.11.0-beta5
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Users/distiller/atom/out/app/src/pane.coffee:832

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:832:15)
    at Pane.module.exports.Pane.split (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:928:15)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:884:19)
    at atom-pane.commandRegistry.add.pane:split-right-and-copy-active-item (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:253:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:28.7.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:27.5.0 core:close (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-base16-syntax.theme-nucleus-dark-ui)
  3x -0:27.4.0 blur (div.markdown-preview.native-key-bindings)
     -0:25.5.0 pane:split-right-and-copy-active-item (div.markdown-preview.native-key-bindings)
  2x -0:25.5.0 blur (div.markdown-preview.native-key-bindings)
     -0:23.7.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:23.7.0 blur (atom-pane.pane.active)
     -0:23.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:23.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:23.1.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:18.9.0 settings-view:open (atom-pane.pane.active)
 15x -0:18.8.0 blur (atom-pane.pane.active)
     -0:02.1.0 core:close (div.panels-item)
  4x -0:02.1.0 blur (div.panels-item)
     -0:00.3.0 pane:split-right-and-copy-active-item (div.markdown-preview.native-key-bindings)
  2x -0:00.3.0 blur (div.markdown-preview.native-key-bindings)
```

### Config
<details>
```json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "close-tags",
      "atom-pair",
      "linter-jshint",
      "highlight-line",
      "linter-codeclimate",
      "linter-coffeelint",
      "linter-eslint",
      "emmet",
      "facebook-messenger",
      "autoclose-html",
      "react"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet"
    ],
    "tabs": {
      "usePreviewTabs": true
    },
    "telemetryConsent": "limited",
    "themes": [
      "nucleus-dark-ui",
      "base16-syntax"
    ]
  },
  "editor": {
    "autoIndentOnPaste": false,
    "fontFamily": "SourceCodePro-Regular",
    "fontSize": 15,
    "invisibles": {},
    "showIndentGuide": true
  }
}
```
</details>
### Installed Packages
<details>
```coffee
# User
activate-power-mode, v0.8.1 (active)
aesthetic-ui, v2.0.0 (inactive)
amateur-hour, v0.0.0 (inactive)
an-old-hope-syntax, v0.5.0 (inactive)
ascii-art, v0.0.0 (inactive)
atom-beautify, v0.29.11 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-pair, v2.0.10 (inactive)
autoclose-html, v0.23.0 (inactive)
base16-syntax, v1.7.0 (active)
chester-atom-syntax, v0.1.1 (inactive)
color-picker, v2.2.2 (active)
editor-stats, v0.17.0 (active)
emmet, v2.4.3 (inactive)
facebook-messenger, v0.0.0 (inactive)
file-icons, v1.7.19 (active)
firewatch-syntax, v1.0.1 (inactive)
genesis-ui, v0.5.0 (inactive)
gruvbox-plus-syntax, v1.2.5 (inactive)
highlight-line, v0.11.1 (inactive)
language-elixir, v0.16.0 (active)
language-haml, v0.24.0 (active)
linter, v1.11.16 (active)
linter-codeclimate, v0.1.2 (inactive)
linter-coffeelint, v1.1.2 (inactive)
linter-eslint, v7.3.0 (inactive)
linter-jshint, v2.1.0 (inactive)
linter-rubocop, v0.4.7 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
monokai, v0.18.0 (inactive)
native-ui, v0.18.3 (inactive)
nucleus-dark-ui, v0.9.5 (active)
quick-find-all, v0.0.0 (inactive)
react, v0.16.0 (inactive)
single-click-open, v0.2.1 (active)
slime, v1.6.1 (inactive)
sort-lines, v0.14.0 (inactive)
toggle-packages, v1.1.0 (active)
toggle-quotes, v1.0.0 (active)
unity-ui, v2.1.5 (inactive)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (active)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
</details>

**Comment by 50Wliu** [comment] 2016-09-09 21:16
Yes, this is a known bug in markdown-preview.  I have a PR that fixes it at https://github.com/atom/markdown-preview/pull/375.

**Comment by nathansobo** [comment] 2016-09-09 21:54
Cool, this seems to have slipped through the cracks. Feel free to merge that PR @50Wliu. If you need any additional support ping me in channel.

**Closed** 2016-09-09 22:00 UTC
Labels: bug, uncaught-exception

**Comment by nathansobo** [comment] 2016-09-09 22:06
I just went ahead and merged and published the fix. Thanks @50Wliu!

**Comment by invernizzie** [comment] 2016-09-27 13:54
@nathansobo thanks for your comment. I don't use markdown-preview and am getting this error anyway. Must be another package with a similar bug. I'll try to reproduce later and report back.

**Comment by Ben3eeE** [comment] 2016-09-27 14:00
@invernizzie I believe this error without markdown preview is currently being tracked in https://github.com/atom/atom/issues/12498 which reproduces with the settings view. Are you reproducing with the settings view or do you have separate steps? Seems some are reproducing without the settings-view but we don't have any steps for that.
