### ISSUE TITLE
atom shows nonexistent blank lines at the ends of files

### ISSUE THREAD

**Issue by dylanwinn** [atom/atom#8719] opened 2015-09-08 22:03 UTC
If I have a file with 1 line as shown by wc and vim, atom will display two lines complete with line numbers. All files end in a newline character, but that does not mean there is an actual line there (newlines mark the end of lines, not the beginning). This is annoying and results in weird complaints from Windows users who don't understand the trailing newline convention.

**Comment by mnquintana** [comment] 2015-09-09 02:14
Thanks for the suggestion! I think this is a duplicate of https://github.com/atom/atom/issues/7787 though, so I'm going to close this out in favor of that issue. Would you mind adding your comments from this issue as a comment on that one? Thanks!

**Closed by mnquintana** 2015-09-09 02:14 UTC
