### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by goodleixiao** [atom/atom#4910] opened 2015-01-08 08:44 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.166.0
**System**: linux 3.13.0-35-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /usr/share/atom/resources/app/src/project.js:355

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/usr/share/atom/resources/app/src/project.js:355:15)
  at Project.module.exports.Project.bufferForPath (/usr/share/atom/resources/app/src/project.js:332:63)
  at Project.module.exports.Project.open (/usr/share/atom/resources/app/src/project.js:286:19)
  at Workspace.module.exports.Workspace.openUriInPane (/usr/share/atom/resources/app/src/workspace.js:485:29)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app/src/workspace.js:412:19)
  at Ipc.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:45:32)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-clang"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
minimap, v3.5.2
vim-mode, v0.24.0

# Dev
No dev packages
```

**Comment by hebbet** [comment] 2015-01-08 11:36
Duplicate of #307

**Comment by izuzak** [comment] 2015-01-08 13:12
Closing in favor of https://github.com/atom/atom/issues/4421

**Closed by izuzak** 2015-01-08 13:12 UTC
