### ISSUE TITLE
Atom hangs when text of an open file is changed from another process 

### ISSUE THREAD

**Issue by ibrahmd** [atom/atom#14672] opened 2017-05-29 10:48 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Every time a large text file currently opened by Atom gets updated by another process, Atom hangs. I tested this on Sublime and VS code and both of them update the text quickly without hanging.

### Steps to Reproduce

1. Run `strace gedit &>log.txt`
2. Close gedit 
3. Open log.txt in Atom
4. Run `strace gedit &>log.txt` and close gedit again
5. Switch back to atom and try to access log.txt

**Expected behavior:** [Atom updates the contents of the file immediately]

**Actual behavior:** [Atom hangs]

**Reproduces how often:** [100%]

### Versions

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
Ubuntu: 16.04

**Comment by maxbrunsfeld** [comment] 2017-06-01 17:36
I think this is a duplicate of https://github.com/atom/atom/issues/11012. It will be fixed via https://github.com/atom/atom/pull/14435.

**Closed by maxbrunsfeld** 2017-06-01 17:36 UTC
Labels: needs-reproduction
