### ISSUE TITLE
IDE-UI with Tree-Sitter causes uncaught TypeError (calling getScopeChain on undefined)

### ISSUE THREAD

**Issue by robertrossmann** [atom/atom#17865] opened 2018-08-15 11:58 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

> Cannot reproduce in Safe Mode as it requires Atom-IDE-UI.

### Description

While working on JavaScript code with Atom-IDE-UI and IDE-TypeScript packages installed, and enabling Tree-Sitter parsers, I get the following TypeError in the console every time I hover over a variable/function/other definition which triggers the datatip popup (video attached):

```
commitCommentView_item.graphql.js:112 Uncaught (in promise) TypeError: Cannot read property 'getScopeChain' of undefined
    at TextEditorRegistry.subscribeToSettingsForEditorScope (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-registry.js:251:46)
    at TextEditorRegistry.updateAndMonitorEditorSettings (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-registry.js:221:22)
    at <anonymous>
    at resolve (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/tree-sitter/index.js:296:21)
    at new Promise (<anonymous>)
    at Parser.parseTextBuffer (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/tree-sitter/index.js:295:10)
    at TreeSitterLanguageMode.parse (/Applications/Atom Beta.app/Contents/Resources/app/src/tree-sitter-language-mode.js:103:40)
    at LanguageLayer._performUpdate (/Applications/Atom Beta.app/Contents/Resources/app/src/tree-sitter-language-mode.js:565:48)
    at LanguageLayer.update (/Applications/Atom Beta.app/Contents/Resources/app/src/tree-sitter-language-mode.js:534:47)
    at new TreeSitterLanguageMode (/Applications/Atom Beta.app/Contents/Resources/app/src/tree-sitter-language-mode.js:75:34)
    at GrammarRegistry.languageModeForGrammarAndBuffer (/Applications/Atom Beta.app/Contents/Resources/app/src/grammar-registry.js:172:20)
    at TextEditor.setGrammar (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:3816:48)
    at setupTextEditor (/Users/robert/.atom/packages/atom-ide-ui/modules/nuclide-commons-ui/AtomTextEditor.js:82:16)
    at AtomTextEditor.componentDidMount (/Users/robert/.atom/packages/atom-ide-ui/modules/nuclide-commons-ui/AtomTextEditor.js:113:28)
... (see attached file for full stack trace)
```

I am not seeing any effects of this error on actual functionality.

### Steps to Reproduce

1. Install Atom-IDE-UI, IDE-TypeScript
1. Enable Tree-Sitter
1. Open DevTools
1. Open a JavaScript file and hover over a function or variable declaration/call site/something else which triggers a datatip
1. Observe error in the console

**Expected behavior:** No error in the console

**Actual behavior:** Error in the console

**Reproduces how often:** All the time

### Versions

```
Atom    : 1.30.0-beta1
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0-beta1
python 2.7.15
git 2.18.0
```

### Additional Information

[Full stack trace](https://github.com/atom/atom/files/2290114/error.log)
[Demo video (mov)](https://github.com/atom/atom/files/2290115/Atom.-.Uncaught.Error.zip)

**Comment by Ben3eeE** [comment] 2018-08-15 12:25
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17707. This has been fixed on master and the fix is available in the latest Atom nightly release :sparkles: 

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-08-15 12:25 UTC
Labels: duplicate
