### ISSUE TITLE
Command `atom -a` equivalent to `Add project Folder`

### ISSUE THREAD

**Issue by Fridus** [atom/atom#6906] opened 2015-05-22 12:42 UTC
Hi,
It could be great to have a additional option in command line for add the path to open to the current treeview. Why not `-a` ?
It is currently only possible with the menu `Add project Folder`

**Comment by mnquintana** [comment] 2015-05-22 12:49
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/6097 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-22 12:49 UTC
