### ISSUE TITLE
Unable to install packages behind proxy

### ISSUE THREAD

**Issue by Bjoernsen** [atom/atom#8839] opened 2015-09-18 10:06 UTC
I am behind a corporate proxy.

Since Atom version 1.0.12 (and 1.0.13), I am not able to install or update any atom package.
This problem is related to the already fixed issue https://github.com/atom/apm/issues/322

When I use Atom version 1.0.11, everything works as expected.

My `.apmrc`
```
http-proxy=http://xxx:8080
https-proxy=http://xxx:8080
strict-ssl=false
```

Manual installation of a package with `apm`
```bash
> apm -v
apm  1.0.4
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

> apm install atom-material-ui
Installing atom-material-ui to /home/bjoernsen/.atom/packages 
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.30.6/node-v0.30.6.tar.gz
gyp http 500 https://atom.io/download/atom-shell/v0.30.6/node-v0.30.6.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: 500 response downloading https://atom.io/download/atom-shell/v0.30.6/node-v0.30.6.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1584:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 3.13.0-63-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.30.6" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure" "--proxy=http://xxx:8080/"
gyp ERR! cwd /home/bjoernsen/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

**Comment by mnquintana** [comment] 2015-09-18 11:43
This is a duplicate of https://github.com/atom/apm/issues/322 - closing this out in favor of that issue.

**Closed by mnquintana** 2015-09-18 11:43 UTC

**Comment by Prabhnith** [comment] 2016-02-08 22:48
Request for package information failed: tunneling socket could not be established, cause=140358160631680:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:
 (5 attempts) (ECONNRESET)
