### ISSUE TITLE
Atom crashes when a link is clicked

### ISSUE THREAD

**Issue by dmnd** [atom/atom#5388] opened 2015-02-04 02:04 UTC
The [git-blame package](https://github.com/alexcorre/git-blame) uses an anchor tag to link to a commit on GitHub. It used to work fine, but recently clicking on those links results in Atom crashing to desktop. See alexcorre/git-blame#60.

The package needs some love (its styles haven't been updated for shadow DOM yet), but it still seems like an Atom core bug to me that clicking on a link can crash the editor.

**Comment by kevinsawicki** [comment] 2015-02-04 16:54
The window just closes?

**Comment by dmnd** [comment] 2015-02-04 16:58
Yeah, sorry, crash might be the wrong word here. Atom the process is still running but clicking the link closes the editor Window. Still, though, that seems like a bug?

Maybe links aren't supported but this used to open a new browser window and something recently has changed the behaviour to closing the editor window.

**Comment by kevinsawicki** [comment] 2015-02-04 17:00
Yeah, all links should open externally, there is core code for that here:

https://github.com/atom/atom/blob/dde253160c9043f13ccd0e75d80a0f5ccc689d2f/src/window-event-handler.coffee#L97

https://github.com/atom/atom/blob/dde253160c9043f13ccd0e75d80a0f5ccc689d2f/src/window-event-handler.coffee#L139-L143

**Comment by dmnd** [comment] 2015-02-05 08:28
This only repros when Shadow DOM is enabled.

**Comment by mark-hahn** [comment] 2015-02-05 20:14
What link?

**Comment by dmnd** [comment] 2015-02-05 20:56
In git-blame gutter view, the commit SHA is a link:

![image](https://cloud.githubusercontent.com/assets/4427/6069070/33c11be4-ad36-11e4-8137-12a49e2939e7.png)

I haven't tried to verify if it happens in other contexts yet.

**Comment by mark-hahn** [comment] 2015-02-05 21:07
You should post this as an issue on git-blame:
https://github.com/alexcorre/git-blame/issues

**Comment by dmnd** [comment] 2015-02-05 22:52
> You should post this as an issue on git-blame

As I said above, see alexcorre/git-blame#60. I reported it here because a link in a package causing the editor to appear to crash seems like it should be a core bug (i.e. it should maybe be impossible for a package to do this).

**Comment by mark-hahn** [comment] 2015-02-05 23:01
> . it should maybe be impossible for a package to do this

There is no sand-boxing of packages.  A package can do anything including
crash everything.

**Comment by mark-hahn** [comment] 2015-02-05 23:02
Actually a package can even erase all your disk drives.

**Comment by despairblue** [comment] 2015-03-10 13:22
BTW: atom keeps humming along in the background, refusing to start any new editor from the terminal (`atom .`)  or the desktop file (the linux .desktop links) giving this exception:
```
TypeError: Cannot read property 'substr' of null
    at AtomWindow.module.exports.AtomWindow.getLoadSettings (/usr/share/atom/resources/app/src/browser/atom-window.js:132:69)
    at AtomWindow.module.exports.AtomWindow.containsPath (/usr/share/atom/resources/app/src/browser/atom-window.js:167:27)
    at AtomWindow.module.exports.AtomWindow.containsPaths (/usr/share/atom/resources/app/src/browser/atom-window.js:158:19)
    at /usr/share/atom/resources/app/src/browser/atom-application.js:521:61
    at /usr/share/atom/resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:159:21
    at Array.some (native)
    at _.some._.any (/usr/share/atom/resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:208:59)
    at Object._.find._.detect (/usr/share/atom/resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:158:5)
    at AtomApplication.module.exports.AtomApplication.windowForPaths (/usr/share/atom/resources/app/src/browser/atom-application.js:520:16)
    at AtomApplication.module.exports.AtomApplication.openPaths (/usr/share/atom/resources/app/src/browser/atom-application.js:592:31)
```

Hope that helps. Killing the atom process is the only way to get it to work again.

**Comment by Chotaz** [comment] 2015-04-14 16:57
My Atom crashes whenever I click ANY external link, whether it is through a package, the package viewer or from code itself, it just hangs for a bit then crashes and asks for a window reload. I can't provide more info as I wouldn't know where to look for it. This is on Ubuntu LTS btw.

**Comment by despairblue** [comment] 2015-04-14 17:17
@Chotaz probably this issue: https://github.com/atom/atom-shell/issues/1348

**Comment by despairblue** [comment] 2015-04-14 17:18
[this](https://github.com/atom/atom-shell/issues/1348#issuecomment-91230583) to be exact

**Comment by sharvil** [comment] 2015-05-29 01:52
I'm running into the same issue on Atom 0.204.0. Here's a simple snippet you can run in Atom's developer console to repro the issue.

```
  var d = document.createElement('div');
  d.style.position = 'absolute';
  d.style.background = 'red';
  d.style.zIndex = 1000;
  d.style.top = 0;
  d.createShadowRoot().innerHTML = '<a href="http://www.google.com">Click me to crash</a>';
  document.body.appendChild(d);
```

Removing the `createShadowRoot` call results in Atom being able to complete the open URL request.

**Comment by ackalker** [comment] 2015-08-10 12:43
I've tried the snippet posted by @sharvil with Atom 1.0.5 and am seeing something slightly different:

Testing the snippet with `createShadowRoot()` left in, no webpage is opened, the Atom window disappears, but `atom` processes remain which I have to kill manually.
Testing the snippet without `createShadowRoot()`, no webpage is opened either, but instead of the Atom window disappearing entirely, it becomes unresponsive. Again I have to kill the `atom` processes manually.

What I find interesting is a snippet of the output of `ps xjf` which I ran at the end of the second test:
```
 PPID   PID  PGID   SID TTY      TPGID STAT   UID   TIME COMMAND
  562   592   592   592 ?           -1 Ss    1000   0:00 i3
    1  3962  3961  3961 ?           -1 Sl    1000   0:01 /usr/share/atom/atom
 3962  3964  3961  3961 ?           -1 S     1000   0:00  \_ /usr/share/atom/atom --type=zygote --no-sandbox
 3962  3982  3961  3961 ?           -1 Sl    1000   0:00  \_ /usr/share/atom/atom --type=gpu-process --channel=3962.0.1291906211 --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,24,27,40,48 --disable-accelerated-video-decode --gpu-vendor-id=0x10de --gpu-device-id=0x1381 --gpu-driver-vendor=NVIDIA --gpu-driver-version=352.30
 3962  3989  3961  3961 ?           -1 Sl    1000   0:01  \_ /usr/share/atom/atom --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-image-decoding --lang=en-US --node-integration=true --subpixel-font-scaling=false --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=2 --disable-accelerated-video-decode --channel=3962.1.1440227255
 3989  4008  3961  3961 ?           -1 Sl    1000   0:00  |   \_ /usr/share/atom/atom --no-deprecation /home/miki/.atom/packages/atom-ternjs/node_modules/.bin/tern --persistent --no-port-file --verbose
 3989  4050  3961  3961 ?           -1 S     1000   0:00  |   \_ /bin/sh /usr/bin/xdg-open http://www.google.com/
 4050  4144  3961  3961 ?           -1 Sl    1000   0:00  |       \_ /usr/lib/chromium/chromium --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --ppapi-flash-version=18.0.0.209 http://www.google.com/
 4144  4146  3961  3961 ?           -1 Z     1000   0:00  |           \_ [chrome-sandbox] <defunct>
 3962  4039  3961  3961 ?           -1 Sl    1000   0:01  \_ /usr/share/atom/atom --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-image-decoding --lang=en-US --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=2 --disable-accelerated-video-decode --channel=3962.2.592250611
```

From this, it appears that `xdg-open` and following `chromium` process was run from one of the renderer processes. I'm not an expert on Chromium sandboxing, but I do recall that these renderer processes run with restricted privileges. I would think that the `xdg-open` etc. needs to be run from the 'master' `atom` process for it to not have these restrictions.

**Comment by despairblue** [comment] 2015-08-10 20:22
@ackalker this should be fixed when https://github.com/atom/atom/pull/7877 lands, since it should be fixed in electron, it's just that atom uses an old version of electron.

**Comment by ackalker** [comment] 2015-08-11 00:19
@despairblue Ah, I see. I was wonderring already why I couldn't reproduce this issue with standalone electron.

**Comment by 128keaton** [comment] 2015-12-07 18:54
I get a similar issue using it as a remote editor for Transmit.

**Comment by damieng** [comment] 2016-08-07 02:42
Sounds like this was fixed a while ago when we picked up a new version of Electron. Please feel free to comment if you find this is not the case and we'll re-open.

**Closed by damieng** 2016-08-07 02:42 UTC
Labels: bug, linux
