### ISSUE TITLE
Symbols showing up as squares

### ISSUE THREAD

**Issue by Mayccoll** [atom/atom#6423] opened 2015-04-17 16:00 UTC
Atom 0.192.0 
Linux Mint 17.1

Actual Results:
![squares](https://cloud.githubusercontent.com/assets/2009698/7205557/c8269aca-e4ef-11e4-8f2a-9ea147ce9f5e.png)

Expected Results:
![stars](https://cloud.githubusercontent.com/assets/2009698/7205615/2689080a-e4f0-11e4-96c3-aff28b07692b.png)

```bash
･ ·̩　　 ｡　☆　　　ﾟ｡ ＊ 　 ｡*　　+　 　＊ 　･ ｡☆+　 　＊ 　･ ｡☆
＊ 　 ｡*　　+　 　＊ 　･ ｡☆ 　　　ﾟ･　　｡ﾟ･　　☆ﾟ　+ ｡　☆　　　ﾟ｡･ ·̩　　
　☆　　　*　　　* 　 。 　 ･ ·̩　　 ｡　☆　　　ﾟ｡　☆　　　*　　　* 　　☆ﾟ　+
　　　ﾟ･　　｡ﾟ･　　☆ﾟ　+ 　☆　　　*　　　* 　 。＊ 　 ｡*　　+　 　＊ 　･ ｡☆
```

**Comment by izuzak** [comment] 2015-04-17 16:05
Suspecting this is a duplicate of https://github.com/atom/atom/issues/6214. Can you try switching to a different font and see if that helps (see https://github.com/atom/atom/issues/6214#issuecomment-90792627)? Let me know if you believe this isn't a duplicate.

**Closed by izuzak** 2015-04-17 16:05 UTC

**Comment by Mayccoll** [comment] 2015-04-17 16:32
ok  :+1: 
adding font resolve the problem.
```Droid Sans Mono, Droid Sans Fallback```
![fonts](https://cloud.githubusercontent.com/assets/2009698/7206229/e29c003e-e4f4-11e4-9e04-190599682531.png)
but should render by default :) 
tnks

**Comment by izuzak** [comment] 2015-04-17 16:35
> but should render by default :)

Yeah, I agree -- this is just a workaround until the problem is fixed. Thanks for letting us know.
