### ISSUE TITLE
Atom fails to (adequately check for) update

### ISSUE THREAD

**Issue by MatthijsBlom** [atom/atom#17242] opened 2018-04-28 18:49 UTC
### Prerequisites

* [x] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [ ] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
* [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [ ] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom fails to update on restart. It does not show a squirrel logo to indicate an update, and (falsely) reports that the current version is the most recent one.

### Steps to Reproduce

1. Start Atom.
2. Notice that no update has been carried out.
3. Wait for the action "Check for update" to become available; check for update.
4. Observe Atom report that the current version is the most recent one.

**Expected behavior:**

- Atom updates on restart.
- Atom reports that a newer version is available, if there is one.

**Actual behavior:**

- Atom does not update on restart, even though it is configured to do so.
- Atom falsely reports that the current version is the most recent one.

**Reproduces how often:** 100%

### Versions

Windows 10, version 1709.

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 3.6.4
git 2.17.0.windows.1
visual studio

### Additional Information

At the time of this writing, the most recent version of Atom is 1.26.1.

Previously, Atom updated just fine.

I may not have started Atom while 1.25 was the most recent version: maybe I 'skipped' a version.

**Comment by rsese** [comment] 2018-04-30 20:34
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/8265 so you can subscribe there for updates if you'd like.

Just to test since I haven't tried updating in a while (I usually install specific versions), I installed 1.24.1 and checked for updates and Atom updated to 1.26.1.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-30 20:34 UTC
