### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by Yajo** [atom/atom#11984] opened 2016-06-15 07:16 UTC
I was just switching tabs, and when I chose a `.po` file, this happened.

**Atom Version**: 1.8.0
**System**: linux 4.5.5-201.fc23.x86_64
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/lib64/electron/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/rpc-server.js:300:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)

```
At /usr/lib64/electron/resources/electron.asar/renderer/api/remote.js:178

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/lib64/electron/resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/rpc-server.js:300:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at metaToValue (/usr/lib64/electron/resources/electron.asar/renderer/api/remote.js:178:13)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/lib64/atom/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/lib64/atom/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/lib64/atom/src/atom-environment.js:775:26)
    at /usr/lib64/atom/src/atom-environment.js:984:27
```

### Commands

```
     -5:41.8.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -5:38.7.0 core:save (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -4:54.2.0 core:copy (atom-text-editor.editor.power-mode.is-focused)
     -4:50.3.0 core:paste (atom-text-editor.editor.power-mode.is-focused)
     -4:48.9.0 core:save (atom-text-editor.editor.power-mode.is-focused.mini)
     -4:31.8.0 core:cut (atom-text-editor.editor.power-mode.is-focused.mini)
     -4:25.4.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  3x -4:25.1.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -4:24.2.0 core:paste (atom-text-editor.editor.power-mode.is-focused.mini)
  2x -4:23.2.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  2x -4:18.5.0 core:backspace (atom-text-editor.editor.power-mode.is-focused.mini)
     -4:15.6.0 core:delete (atom-text-editor.editor.power-mode.is-focused.mini)
  2x -4:14.3.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -4:12.8.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -2:39.9.0 tree-view:remove (span.name.icon.icon-file-text)
     -2:32.6.0 tree-view:show-in-file-manager (span.name.icon.icon-file-text)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "editor": {
    "autoIndentOnPaste": false,
    "preferredLineLength": 79,
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
autocomplete-python, v1.8.1
bug-report, v0.7.1
editorconfig, v1.4.1
exception-reporting, v0.38.1
language-docker, v1.1.6
language-restructuredtext, v0.16.0
language-rpm-spec, v0.10.0
linter, v1.11.10
linter-docker, v0.1.2
linter-flake8, v1.13.2
linter-pep8, v1.3.0
linter-php, v1.2.0
linter-xmllint, v1.3.4
metrics, v0.53.1
minimap, v4.24.6
minimap-bookmarks, v0.3.1
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
odoo-snippets, v0.3.0
quick-highlight, v0.5.0
rst-preview-pandoc, v0.1.12
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-06-15 12:58
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-15 12:58 UTC
