### ISSUE TITLE
Symbol character in string resulting incorrect quote pair autocompletion

### ISSUE THREAD

**Issue by rovyko** [atom/atom#18710] opened 2019-01-17 01:53 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When a string is missing a quote character (`` ` ``, `"`, or `'` ) on the left or right side, autocomplete will incorrectly pair a typed quote if a non-alphanumeric is the first or last character respectively.

### Steps to Reproduce

1. Create an empty text file (json, txt or py for example)
2. Type the characters `"a*"`
3. Remove the last character `"`
4. Type the last character `"` again

**Expected behavior:**
The string will be autocompleted as `"a*"`

**Actual behavior:**
An extra quote character is added at the end: `"a*""`

**Reproduces how often:**
Occurs every time given the following conditions:
1. The quote character is one of `` ` ``, `"`, or `'`
2. One of the quote characters is missing
3. The character adjacent to the missing quote character is not alphanumeric

### Versions
1.34.0

### Additional Information

Reproduced on a fresh install of Atom started in safe mode.

**Comment by rsese** [comment] 2019-01-17 18:38
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/bracket-matcher/issues/298 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-01-17 18:38 UTC
