### ISSUE TITLE
Buffer rewrite with beautify completely corrupts mixed-EOL files.

### ISSUE THREAD

**Issue by garretwilson** [atom/atom#15225] opened 2017-08-10 03:44 UTC
I haven't proven this is the culprit, but all signs point to the [new editor backend in v1.19.0](https://github.com/atom/atom/releases/tag/v1.19.0) (or another "improvement" in v1.19.0) getting confused when there are multiple types of line endings in a document and **completely corrupting the file** when you run https://github.com/Glavin001/atom-beautify on it.

I'm using Atom 1.19.0 ia32 with atom-beautify 0.30.4 on Windows 10 Pro 64-bit.

I'm attaching a zipped file that contains mixed LF and CRLF file. (Yes, it's horrible, but it's out of my control; see the end of this message for the back story.)

Earlier editions of Atom would should the LF line endings using a different symbol, but _this version of Atom shows the LF line endings as if they were CRLF endings_ when I turn on invisibles. (The line ending notification at the bottom also says CRLF when the type is really mixed.) This is what tips me off that there is an underlying problem in the buffers, thinking that all the line endings are the same --- and when I went and saw the release notes that Atom updated it buffer implementation, that made it almost certain.

Install the `atom-beautify` package and open the attached archive. (Don't copy and paste, or that will normalize the line endings.) Make sure the `.jsbeatifyrc` file is in the same directory. Then run `atom-beautify` on it. It will turn this:

```html
    <figure> <figcaption>Examples of local time classes.</figcaption>
      <pre class="line-numbers"><code class="language-java">//someone's date of birth: May 30, 1970
final LocalDate dateOfBirth = LocalDate.of(1980, Month.MAY, 30);
//someone's birthday: May 30
final MonthDay birthday = MonthDay.of(Month.MAY, 30);

//a typical end of a workday: 5:00 p.m.
final LocalTime endOfWorkday = LocalTime.of(17, 0);

//current date and time
final LocalDateTime = LocalDateTime.now();</code></pre>
    </figure>
```

into this:

```html
		<figcaption>Examples of local time classes.</figcaption>
		<pre class="line-numbers"><code class="language-java">//someone's date of birth: May 30, 1970
    <p>Local dates and times are relative or <q>floating</q>; they do not provide sufficient information to determine precisely when an event occurred or will occur. Recording the date and time of a birth, for instance, must include the time zone. A journal entry as well would normally indicate the time zone in order to fix the exact moment in an absolute way worldwide: <q>December 11, 2016 10:53 a.m. America/Los Angeles</q>.</p>
```

Yes, basically it just jumps around, drops large sections of content, and copies other pieces of content to other locations.

If I first take the HTML file into another editor (e.g. EmEditor) and normalize the line endings (either all CRLF or all LF), the bug does not occur and `atom-beautify` functions as it usually does. This proves the bug has to do with mixed line endings, and everything about it points to new overhaul in a recent version of Atom.

**This is a huge, breaking, content corrupting bug.**

Yes, I have mixed line endings. No, I didn't want them to begin with. One of the reasons I'm opening them in Atom _is so that `atom-beautify` can normalize them_!!! **No editor should corrupt my content just because my EOLs are not consistent.**

No matter what I do, my toolchain just keeps developing bugs:

* The BlueGriffon HTML editor has a huge [bug](https://github.com/therealglazou/bluegriffon/issues/7) from deep in the Mozilla code, which adds newlines when it shouldn't --- but to make matters worse, it adds an LF in the middle of a file using CRLF on a Windows machine, producing mixed line endings. I have put my money out as a [bounty](https://www.bountysource.com/issues/29803090-line-wrapping-setting-ignored) to get this fixed, but there have been no takers.
* I use `atom-beautify` to attempt to reformat the file: to normalize the line endings, and get rid of the extra newlines. This only halfway works; many of the erroneous newlines remain because of a `js-beautify` [bug](https://github.com/beautify-web/js-beautify/issues/1033). I have also paid my money on a [bounty](https://www.bountysource.com/issues/41908855-not-correctly-joining-lines-for-html) to get this fixed, but no one seems interested.
* Now it would appear that Atom not only can't process EOLs correctly, it also corrupts the files. I can't win for losing.

See https://github.com/beautify-web/js-beautify/issues/1225 and https://github.com/Glavin001/atom-beautify/issues/1802 for further discussion and "bellyaching" as we say.

I need some tequila.

[atom-buffer-mixed-eol-bug.zip](https://github.com/atom/atom/files/1213599/atom-buffer-mixed-eol-bug.zip)

**Comment by maxbrunsfeld** [comment] 2017-08-10 06:28
@garretwilson It sounds like you've had a really rough day, and I really apologize if my text-buffer rewrite is the cause of it. I'm looking into this now.

One relevant piece of information is that there has been one *intentional* change in Atom's behavior that affects this file: Atom no longer considers a single `\r` (carriage return) character to be a line-ending. Those characters are now treated as ordinary whitespace. The only character sequence that we treat as line endings are `\n` (LF) and `\r\n` (CRLF).

Because of this new policy, we display the `CRLF` as the line-ending type for this file. We would only display `Mixed` if the file contained a mixture of `LF` and `CRLF` line endings.

**Comment by maxbrunsfeld** [comment] 2017-08-10 06:29
I installed the `atom-beautify` package and, using Atom 1.19, ran the `Atom Beautify: Beautify Editor` command on that file, and I wasn't able to reproduce the behavior that you reported. No content has been dropped, as far as I can tell. The `figure` tag that you mentioned above now looks like this:

```html
	<figure>
		<figcaption>Examples of local time classes.</figcaption>
		<pre class="line-numbers"><code class="language-java">//someone's date of birth: May 30, 1970
final LocalDate dateOfBirth = LocalDate.of(1980, Month.MAY, 30);
//someone's birthday: May 30
final MonthDay birthday = MonthDay.of(Month.MAY, 30);

//a typical end of a workday: 5:00 p.m.
final LocalTime endOfWorkday = LocalTime.of(17, 0);

//current date and time
final LocalDateTime = LocalDateTime.now();</code></pre>
	</figure>
```

**Comment by maxbrunsfeld** [comment] 2017-08-10 06:29
This might be a Windows-specific bug. Let me fire up my VM.

**Comment by maxbrunsfeld** [comment] 2017-08-10 07:30
@garretwilson Thanks for the detailed report and sorry for all of the misery. I hope that #15228 fixes this. Please let me know if you're able to test with that build.

**Comment by garretwilson** [comment] 2017-08-10 13:27
Good morning, Max. I just got up. Listen, first of all I want to say I appreciate your looking into this so quickly.

About my "misery" as you mentioned --- one thing that made this more exasperating than it would have is that we have one of the simplest things in text file processing, a line ending, and _none_ of the tools in my chain can handle it. Mozilla editing code screws it up. That gets taken up and published in BluGriffon, which they won't fix. So I take it into Atom, and `atom-beautify` has a bug that doesn't fix this. And now... Atom developed a bug that corrupted my file. All of this because of a line ending. That's why it was more frustrating to me that just any old other but.

But again thanks a lot for looking into this. I look into it as soon as I can, but I can't right now --- because I have to go do client work I didn't do because of all the time I took tracking down my file corruption.

Since you know that #15228 fixes "a bug", as you put it, can you just put out a patch version of Atom so that I don't have to jump through hoops just to test this? We don't yet know for sure if it was _this_ bug, but it was a bug in the buffer --- doesn't that warrant a patch release anyway?

**Comment by maxbrunsfeld** [comment] 2017-08-10 17:15
There will probably be other 1.19 bugs to fix, so we'll want to batch them up (and confirm that #15228 fixes your bug) before we publish a new patch version. Because publishing a new patch release requires every Atom user to download a new version, we like to batch up fixes.

**Comment by garretwilson** [comment] 2017-08-10 17:22
On the other hand, there is the concept of a bug that is so onerous it should be patched immediately. Obviously it is for the Atom team to make that call. But sitting from my end, I'm seeing a tool whose job it is to edit text, and this bug results in corruption and loss of the data it's working on. In my biased view, about the only thing that could be worse than that is if the application somehow compromised the security of the system. That's my opinion.

In the meantime I'll open the content in another editor to normalize the line endings before trying to open it in Atom. At least a workaround is known.

I hope you can understand that I can be exasperated at this bug on one hand, yet at the same time grateful that you looked into it so quickly. Not everyone is so mindful of bug reports. Thank you.

**Comment by garretwilson** [comment] 2017-08-10 17:30
And I can't even scroll properly with Atom 1.19.0: https://github.com/callum-ramage/ctrl-dir-scroll/issues/28

It's really frustrating when the editor breaks _core functionality_ all over the place.

**Comment by nathansobo** [comment] 2017-08-10 19:00
@garretwilson Fixed the `ctrl-dir-scroll` issue. That package was using a private field on the editor object. There's no way we can simultaneously make promise and guarantee that no private fields are ever moved. When big changes happen, packages that weren't careful about using public APIs are unfortunately going to break. Luckily in this case we can provide a fallback.

**Comment by garretwilson** [comment] 2017-08-10 19:03
Ah, yeah, I was about to say that I read #15244 and and saw that `ctrl-dir-scroll` was using a non-public API. Naturally semantic versioning doesn't apply to private, unsupported APIs.

So `ctrl-dir-scroll` now uses the public API, and we'll get a fix published soon? If so, that's great news, thank you! I was about to throw Atom away, as I use this feature every day.

**Comment by nathansobo** [comment] 2017-08-10 19:08
It's still not an officially public API but I don't anticipate it changing for a while.

**Comment by garretwilson** [comment] 2017-08-17 01:16
Hi, @maxbrunsfeld . I hope your week is going well.

I notice a couple of new patch versions of Atom 1.19.x are out. Can I confirm that this bug has been fixed? I can't seem to find anything about it in the [release notes](https://atom.io/releases).

Cheers!

**Comment by Ben3eeE** [comment] 2017-08-17 05:36
@garretwilson It has not been released in any of the hotfix releases. The mentioned PR https://github.com/atom/atom/pull/15228 has still not been merged to master.

**Comment by garretwilson** [comment] 2017-08-17 14:11
Amazing that a bug that corrupts and erases data could get so low priority in an editor.

**Comment by lee-dohm** [comment] 2017-08-17 15:09
@garretwilson your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

I can understand that you don't agree with how we've prioritized things. We have had other issues that have had more far-reaching effects than this one that we considered higher priority. We are doing our best to fix this as quickly as we can. If our efforts aren't up to your standards, perhaps another editor would be.

**Comment by garretwilson** [comment] 2017-08-17 15:42
@nathansobo , I confess I just don't have time to go through such procedures to test this fix. If you had a simple executable file for me to replace, it would be one thing. But apparently with this Zip file I have to download my plugins and setup my environment again. I was already behind in my work when this bug hit me, and I already lost a lot of time investigating and reporting it.

If you know that you fixed _some_ bug, what I don't understand is why you don't simply release it and then we can see if it happens to fix _this_ problem. Because you already know the code you fixed was a bug, right?

@nathansobo , I am trying to merely reply to your question. None of this is meant to be a personal attack. @lee-dohm , please do not mark this a a violation of your code of conduct.

**Comment by garretwilson** [comment] 2017-08-17 15:42
I'll be grateful for someone for fixing this. I've opened a bounty for this bug to pay out money to whoever fixes this. If you think this issue deserves more, let me know.

https://www.bountysource.com/issues/48107354-buffer-rewrite-with-beautify-completely-corrupts-mixed-eol-files

**Comment by nathansobo** [comment] 2017-08-17 15:56
No worries. I don't feel attacked. The person in the best position to make these changes has been out and is still catching up with some other stuff. This is on our radar to fix but we haven't gotten to it yet. It sucks when your tools don't work correctly but we're working as hard as we can to make Atom better and sometimes we make mistakes. We'll get to it.

**Comment by nathansobo** [comment] 2017-08-17 15:59
Also don't forget that you can downgrade to 1.18.0 and disable updates until this issue is closed.

**Comment by maxbrunsfeld** [comment] 2017-08-17 16:32
> I confess I just don't have time to go through such procedures to test this fix. If you had a simple executable file for me to replace, it would be one thing. But apparently with this Zip file I have to download my plugins and setup my environment again.

You would just need to download the archive, unzip it, and open the executable inside. You don't need to do anything related to plugins or your environment.

**Comment by garretwilson** [comment] 2017-08-17 17:00
> You would just need to download the archive, unzip it, and open the executable inside. You don't need to do anything related to plugins or your environment.

Oh, OK. I assumed it created another separate installation that I would have to configure.

So I tried the Atom build in the previous Zip file (1.21.0-dev-7413190), and **I can confirm that it fixes this manifestation of the bug**. Upon running `atom-beautify` on the example file, the content was no longer arbitrarily moved around or deleted.

Some related bugs however remain:

* The indicator at the bottom still shows "CRLF" even though the line endings are mixed.
* Atom (when "show invisibles" is enabled) still does not show lines ending in LF correctly. It's showing everything as CRLF --- even for example the line `The latest versions of Java provide built-in libraries for tracking time, located in the <a` . This line ends in LF (you can confirm by opening in another editor such as EmEditor or Notepad++), but Atom erroneously shows a symbol for CRLF.

These bugs may not be of the blocker type, as this one is, which corrupt content; but still they are worrisome, and have the potential for corrupted content.

> I don't think it's necessary to offer a bounty on this bug…

Too late. The money has been paid and is non-refundable. Someone can enjoy a good meal and a few beers.

**Comment by maxbrunsfeld** [comment] 2017-08-17 17:08
Thanks a lot for the information @garretwilson; that's really helpful. The fix will go out in 1.19.3.

Regarding the line endings, I [commented above](https://github.com/atom/atom/issues/15225#issuecomment-321462969) about this. I can't see any single LF line endings in this file, with any tool.

For example, using `grep` to search for lines without a CR at the end:

```sh
$ grep -v '\r$' atom-buffer-mixed-eol-bug.html
# no results
```

and conversely, searching for lines that *do* have a CR at the end:

```sh
$ grep -n '\r$' atom-buffer-mixed-eol-bug.html
# shows every single line of the file
```

So unless I'm missing something, Atom is correct in displaying CRLF for this file's line endings.

**Comment by garretwilson** [comment] 2017-08-17 17:17
> I can't see any single LF line endings in this file, with any tool.

Haha. I'm laughing because this whole situation seems humorous (on some level --- but not on all levels).

Have you considered that `grep` has its own concept of what an "end of line" is, and that perhaps its `$` regular expression matching _also_ gets confused when there are mixed line endings (just like Atom and `atom-beautify` and BlueGriffon and Mozilla and …)? I don't know for certain that is the case, but it does not seem farfetched at all. You see, the particular combination here is actually `LFCRLF`, because one line (incorrectly but unavoidably) ends with `LF`, and then the next (empty) line ends in `CRLF`.

Why not be direct? Grab your favorite text editor that supports "open in hex mode" (EmEditor comes to mind) and look at the actual line endings. Or grab a hex editor.

I personally just downloaded the actual `atom-buffer-mixed-eol-bug.zip` file I attached when I filed this bug. I unzipped it in a separate directory. I opened it with EmEditor 17.0.2 and turned on `View > Marks > CR and LF with Different Marks`. There, plain as day, is an `LF` at the end of line 13.

**Comment by garretwilson** [comment] 2017-08-17 17:21
@maxbrunsfeld , after reviewing your comment above, and looking more closely at the symbols in the editor, the line ending on line 13 is a `CR` (`U+000D)`, so I was said the incorrect line ending. Let me update my previous comment...

**Comment by maxbrunsfeld** [comment] 2017-08-17 17:22
Yeah, exactly like I said above, and in my previous comment, that contains a single CR. Are we ok?

**Comment by lee-dohm** [comment] 2017-08-17 17:25
@garretwilson `CR` by itself is only considered a line ending on versions of the classic Mac operating system (versions prior to OS X). Since that OS hasn't been in common use in approximately 15 years, I don't believe it is unreasonable for Atom to ignore it as a potential line ending character.

**Comment by garretwilson** [comment] 2017-08-17 17:28
> Regarding the line endings, I commented above about this. I can't see any single LF line endings in this file, with any tool.

I was mistaken when I said `LF`. You are correct, the incorrect lines each end in a single `CR`.

With that in mind, I reread your [comment](https://github.com/atom/atom/issues/15225#issuecomment-321462969) above, and your comment now makes more sense to me.

Now I understand that you are saying that Atom will not detect (at least as far as the line indicator goes) when there are erroneous lines ending with a single `CR`. I guess that will have to be. I hope that it doesn't prevent tools like `atom-beautify` from working. (Believe me, I don't want them in the first place. Maybe someone could fix the bounties I've opened for BlueGriffon and the Mozilla code.)

So it seems then, that once this bug is pushed to production, the other behavior is a known and intended change.

> The fix will go out in 1.19.3.

Thank you very, very much! 👍

**Comment by garretwilson** [comment] 2017-08-17 17:32
> Since that OS hasn't been in common use in approximately 15 years, I don't believe it is unreasonable for Atom to ignore it as a potential line ending character.

I don't know what Atom should do about them (except it shouldn't break, of course). I don't want them in the first place. They are only there because BlueGriffon puts them there, from a bug in the Mozilla editing code (so they say), that no one wants to fix. The irony is that after editing in BlueGriffon I bring the files into Atom to "fix" them, etc. etc. (as I explain above).

**Comment by maxbrunsfeld** [comment] 2017-08-17 17:34
We do intend to continue to fully support files with mixed line endings. But we ourselves don't deal with them often, so this bug slipped through; we really appreciate you reporting it and providing the detailed reproduction steps. Let us know if you encounter anything else strange with these sorts of files.

**Closed by maxbrunsfeld** 2017-08-17 17:34 UTC

**Comment by maxbrunsfeld** [comment] 2017-08-22 21:59
1.19.3 is out.
