### ISSUE TITLE
Uncaught Error: ENOENT

### ISSUE THREAD

**Issue by fpcorso** [atom/atom#5746] opened 2015-02-25 19:39 UTC
I received this error message:
Uncaught Error: ENOENT, open 'C:\Users\Frank\Google Drive\My_Local_webstop\Clients\VVIS\1.0\main.less'
C:\Users\Frank\.atom\packages\atom-compile-less\lib\atom-compile-less.coffee:15

Here is the stack trace:
Error: ENOENT, open 'C:\Users\Frank\Google Drive\My_Local_webstop\Clients\VVIS\1.0\main.less'
  at Error (native)

This is what it said:
This is likely a bug in Atom.

So, background:
I installed the package atom-compile-less. I created a .less file. I then saved it and got this error. However, the package did work and create a css file so I do not know if this is an error with the package or with Atom but the error said to post it here.

**Comment by fpcorso** [comment] 2015-02-25 19:42
Hmmm, now the package is throwing its own error :Uncaught Error: Unrecognised input which I created an issue for in its repository.

**Comment by izuzak** [comment] 2015-02-25 19:43
Which version of Atom are you using, @fpcorso, and can you reproduce the problem in the latest version? 0.183.0 -- https://github.com/atom/atom/releases/latest

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues

Can you reproduce the problem in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)? Can you post the full stack trace which you get?

**Comment by fpcorso** [comment] 2015-02-25 19:52
Ah, I should have included much more information indeed.

OS: Windows 7
Atom: 0.182.0 --says latest version when checking for updates
Picture of the error:
![atom_errors](https://cloud.githubusercontent.com/assets/9730040/6379086/8c433ece-bcfd-11e4-9652-578a77d6e848.png)
The only errors listed in the dev tools are the two shown here.
No errors are shown when saving the .less in safe mode

**Comment by fpcorso** [comment] 2015-02-25 19:54
I have already created a separate issue in the package's repository for the error shown underneath which says is from the package.

**Comment by izuzak** [comment] 2015-02-25 19:56
@fpcorso Is there are reason why you didn't use the "Create issue on atom/atom" button to create the issue? That would have included much more debugging information which would be helpful. Can you do that now, please, and close this?

**Comment by fpcorso** [comment] 2015-02-25 20:02
I have tried. I clicked on it and it doesn't do anything.

**Comment by fpcorso** [comment] 2015-02-25 20:02
I tried on numerous instances of this error thinking that perhaps it was one-time not working. It has not worked any time that I have clicked on it.

**Comment by fpcorso** [comment] 2015-02-25 20:03
I have switched packages to less-autocompile instead and the error is no longer shown so it is more than likely a compatibility issue with the original atom-compile-less package that I was using.

**Comment by izuzak** [comment] 2015-02-25 20:29
> > Is there are reason why you didn't use the "Create issue on atom/atom" button to create the issue? 

> I have tried. I clicked on it and it doesn't do anything.

Thanks @fpcorso.

@benogle Why this might happen? Does a user need to set up some token so that it can be used to create an issue?

**Comment by benogle** [comment] 2015-02-25 22:09
I've only seen the buttons-dont-work issue in windows and it was because the URLs were too long. We're using a shortener now, but if the shortener fails, it still uses the long url. 

@fpcorso when you have one of these errors open, can you run this in the command line and paste the output here?

```
document.querySelector('atom-notification .btn-issue').getAttribute('href')
document.querySelector('atom-notification .btn-issue').getAttribute('href').length
```

**Comment by fpcorso** [comment] 2015-02-25 22:46
`
document.querySelector('atom-notification .btn-issue').getAttribute('href');
`
gives me
`
"#"
`
and
`
document.querySelector('atom-notification .btn-issue').getAttribute('href').length;
`
gives me
`
1
`

**Comment by benogle** [comment] 2015-02-26 18:56
Thanks. There is probably an error in either the issue search query or the url shortening. Fixing...

**Closed** 2015-02-26 19:19 UTC
Labels: more-information-needed
