### ISSUE TITLE
Japanase can't input and display on Ubuntu

### ISSUE THREAD

**Issue by cakecatz** [atom/atom#6264] opened 2015-04-06 06:17 UTC
Atom 0.189.0 on Ubuntu.
![screen](https://cloud.githubusercontent.com/assets/6136383/7001235/ad6ab0be-dc6f-11e4-8fba-8d036c5ea30b.png)

Mac version is not happen.

**Comment by izuzak** [comment] 2015-04-06 06:27
This looks like a duplicate of #6214, so I'm closing this in favor of that issue.

**Closed by izuzak** 2015-04-06 06:27 UTC
