### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tywang2006** [atom/atom#15255] opened 2017-08-11 09:43 UTC
[Enter steps to reproduce:]

it is working with previous version, but when I open my existing project, it just keep getting this error. I think my colleague got same issues with his project. so I assume it might be critical issue for atom.
...
...
Atom: 1.19.0-beta4 x64
Electron: 1.6.9
OS: Microsoft Windows 10 Home
Thrown From: linter-ui-default package 1.6.3

Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

`At C:\Users\pipch\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2266

TypeError: Cannot read property 'length' of undefined

**Comment by Ben3eeE** [comment] 2017-08-11 09:53
This sounds like a duplicate of https://github.com/atom/atom/issues/14980 which has been fixed. Please update to the latest version of Atom and let us know if that doesn't help.

**Closed by Ben3eeE** 2017-08-11 09:53 UTC

**Comment by tywang2006** [comment] 2017-08-11 10:07
Sorry, I copy that issue from that ticket. I did use atom 1.19.0 not beta4 vesion
