### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/jeffrey/Library/Application Supp...

### ISSUE THREAD

**Issue by jpgoldberg** [atom/atom#10601] opened 2016-01-27 14:20 UTC
[Enter steps to reproduce below:]

1. Launch Atom

(Presumably I have an interrupted update, leaving things in an incoherent state, but I do not know how to reproduce that.)

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/jeffrey/Library/Application Support/com.github.atom.ShipIt/update.NOoF0Z9/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
```

### Commands

```
  2x -1:01.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:43.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:42.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.9.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-chktex"
    ],
    "themes": [
      "contrast-ui",
      "contrast-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-01-27 14:30
Hi @jpgoldberg, thanks for reporting!  This looks like a duplicate of #7399, so feel free to subscribe there for updates :smile:.

**Closed by 50Wliu** 2016-01-27 14:30 UTC
