### ISSUE TITLE
File system tree does not reflect specific gitignore arrangement 

### ISSUE THREAD

**Issue by xipasduarte** [atom/atom#8584] opened 2015-08-30 23:21 UTC
Consider the following `.gitignore` structure:
```
# Ignore parent folder contents
content/*

# Include selective folders in parent folder
!content/special-child/
!content/special-file.ext
```
In the filesystem tree, on the sidebar, the folders parent (`content/`) and respective children files/folders are marked like untracked because of the first statement.
This becomes quite confusing if the parent folder is populated with several outside dependencies and some specific folders/files with code that are tracked (i.e. their exclusion is denied) while browsing the tree.

**Comment by izuzak** [comment] 2015-08-31 05:45
I believe this is a duplicate of https://github.com/atom/tree-view/issues/196 -- please follow that for updates and let me know if I've misunderstood your report.

**Closed by izuzak** 2015-08-31 05:45 UTC

**Comment by xipasduarte** [comment] 2015-08-31 09:15
Yes, absolutely the same. Sorry I could find it first. Thanks.
