### ISSUE TITLE
Key binding for comments should insert cursor within comment

### ISSUE THREAD

**Issue by caleb531** [atom/atom#8511] opened 2015-08-26 00:33 UTC
Hi,

Apologies for the long title. The bug is actually quite simple: when I prepare to add a comment via Atom's default key binding (`cmd+/` for me), the text cursor is not placed *within* the comment as I would expect (so I can begin typing). Instead, the cursor is placed *after* the comment, which I find rather unintuitive.

*Before:*  
![before](https://cloud.githubusercontent.com/assets/872474/7287217/60d99a18-e907-11e4-9894-b62d177c1303.png)

*After:*  
![after](https://cloud.githubusercontent.com/assets/872474/7287241/88825aa0-e907-11e4-8607-f65423cd5f12.png)

*What I was expecting:*  
![ideal](https://cloud.githubusercontent.com/assets/872474/7287256/b1c6c9f0-e907-11e4-93ea-8b4fe09aafa0.png)

Could this be fixed?

Thanks,
Caleb

*P.S. I first [posted this issue on atom/language-css](https://github.com/atom/language-css/issues/25), but it seems the issue affects all languages with start/end components for comments.*

**Comment by eddiemonge** [comment] 2015-08-26 00:44
duplicate of #4784

**Comment by maxbrunsfeld** [comment] 2015-08-26 00:45
> duplicate of #4784

Yep. @caleb531 Please subscribe there for updates.

**Closed by maxbrunsfeld** 2015-08-26 00:45 UTC
Labels: enhancement

**Comment by 50Wliu** [comment] 2015-08-26 00:51
@caleb531 Sorry for all this inconvenience :grimacing:.  I should have searched here first before asking you to submit a new issue.
