### ISSUE TITLE
About changes when coding in python?

### ISSUE THREAD

**Issue by Hanzhizheng** [atom/atom#15844] opened 2017-10-09 11:42 UTC
```
def f(n,lookup):
    if n==0 or n==1:
        lookup[n]=n
    if lookup[n] is None:
        lookup[n]=f(n-1,lookup=)+f(n-2,lookup=)
    return lookup[n]
```
the auto '=' in params

```
def x(n):
    if n==1:
        return n
```
when you tab it comes out the list like this:  v n, the tab doesn't work.

```
def x(n):
    if n==1:
        return n
else:
```

type ':' the else will auto move to the head.

**Comment by thomasjo** [comment] 2017-10-09 12:23
Closing as duplicate of https://github.com/atom/language-python/pull/204#issuecomment-335135629, and also wrong repo.

**Closed by thomasjo** 2017-10-09 12:23 UTC

**Comment by Ben3eeE** [comment] 2017-10-09 12:47
Duplicate of https://github.com/atom/language-python/issues/209
