### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 76Error: Cannot call...

### ISSUE THREAD

**Issue by liamdbarber** [atom/atom#20118] opened 2019-11-05 15:13 UTC
Steps to reproduce:
1. $ atom file.txt where the file did not already exist.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 76
Error: Cannot call function 'getPosition' on missing remote object 76
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 76
Error: Cannot call function 'getPosition' on missing remote object 76
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705396)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705811)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -1:42.5.0 core:copy (input.hidden-input)
     -1:40 core:paste (input.hidden-input)
     -1:39.4.0 editor:newline (input.hidden-input)
     -1:39.1.0 core:save (input.hidden-input)
     -1:06.9.0 core:close (input.hidden-input)
     -0:43.2.0 core:move-left (input.hidden-input)
  3x -0:42.5.0 core:backspace (input.hidden-input)
     -0:41.8.0 core:move-left (input.hidden-input)
     -0:41.3.0 core:save (input.hidden-input)
     -0:30.9.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.10 
atom-section-divider 1.0.3 
atom-unsaved-changes 0.4.0 
autocomplete-python 1.15.0 
block-select 1.0.0 
highlight-selected 0.16.0 
intentions 1.1.5 
kite 0.171.0 
language-fortran 2.1.9 
language-latex 1.2.0 
latex-wordcount 0.6.0 
linter 2.3.1 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.8.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
script 3.18.1 
simple-drag-drop-text 0.5.0 
```

**Comment by rsese** [comment] 2019-11-11 01:05
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like.

If you can, please let us know in that issue if you consistently see the error with your steps to reproduce and if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).  It would also be helpful to know if you can reproduce with the current [stable release (1.41.0)](https://github.com/atom/atom/releases/tag/v1.41.0) which is running Electron 4.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-11-11 01:05 UTC
