### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by rst0git** [atom/atom#12183] opened 2016-07-16 22:30 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Arch Linux"
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as isFullScreen] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.isWindowFullScreen (/usr/share/atom/resources/app.asar/src/application-delegate.js:103:40)
    at AtomEnvironment.module.exports.AtomEnvironment.isFullScreen (/usr/share/atom/resources/app.asar/src/atom-environment.js:588:39)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:775:26)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```

### Commands

```
  2x -2:23.9.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:21 tree-view:toggle-focus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:16 window:reset-font-size (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:13.8.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:12.9.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:12.3.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:12 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:11.6.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -1:57.2.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:18.4.0 core:close (div.panels)
  2x -1:16.3.0 window:decrease-font-size (input.hidden-input)
     -0:37.9.0 core:close (input.hidden-input)
     -0:36.9.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:33.3.0 core:close (input.hidden-input)
     -0:32.3.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:30.7.0 core:close (input.hidden-input)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "followSymlinks": false,
    "packagesWithKeymapsDisabled": [
      "grammar-selector"
    ],
    "projectHome": "/home/home/Projects/Django/mywebsite",
    "themes": [
      "one-dark-ui",
      "darkpython-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontSize": 12,
    "invisibles": {},
    "useShadowDOM": false,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.8.2
darkpython-syntax, v0.2.0
language-scala, v1.1.6
python-indent, v0.4.3
python-jedi, v0.3.7
python-tools, v0.6.8

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-07-16 22:48
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-16 22:48 UTC
