### ISSUE TITLE
Uncaught RangeError: Invalid string length

### ISSUE THREAD

**Issue by ZenHarbinger** [atom/atom#7417] opened 2015-06-25 17:31 UTC
[Enter steps to reproduce below:]

1. I opened a very large (591.0 MB (591,032,444 bytes)) JSON file.

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Invalid string length

```
At /usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:301

RangeError: Invalid string length
  at Array.join (native)
  at ReadStream.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/file.js:301:43)
  at emitNone (events.js:72:20)
  at ReadStream.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -8:52 editor:select-line (atom-text-editor.editor.is-focused)
     -8:49.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
 22x -8:04.1.0 pane:show-next-item (atom-text-editor.editor.is-focused)
  2x -6:26 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -6:20.3.0 release-notes:show (atom-text-editor.editor.is-focused)
 41x -0:16.5.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 10,
    "tabLength": 4,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-06-25 19:14
Was this a one-line file by any chance? Is there any way you could post this (or a similar file that triggers the same error) as a Gist?

/cc @nathansobo @maxbrunsfeld

**Comment by ZenHarbinger** [comment] 2015-06-25 19:33
It is not all one line.
https://www.dropbox.com/s/2jcdqso36rb014a/large.json.gz?dl=0

Not sure how to get a file like this anywhere except dropbox.  If you need it somewhere else, let me know.

**Comment by 3zzy** [comment] 2015-06-26 00:00
Had the exact same error opening a large (570mb) XML file.

**Comment by robmcl4** [comment] 2015-06-26 01:17
For me this happens with any file above 268,435,440 characters, which is suspiciously close to 2<sup>28</sup> = 268,435,456. Anyway, here's how I reproduce on OS X 10.10.3:

```bash
% python -c "with open('broken.txt', mode='w') as f: f.write('1'*268435441)"
% open Atom.app --args broken.txt
```
Click proceed, and observe error.

**Comment by kubetz** [comment] 2015-06-26 01:21
@robmcl4 thanks for providing an easy way how to reproduce this issue :+1:

I am getting same error also under Windows 8.1 .

**Comment by robmcl4** [comment] 2015-06-26 01:29
I feel like this is related to joyent/node/issues/14170. If so, what this error is really saying is _out of memory_.

**Comment by kubetz** [comment] 2015-06-26 01:43
It seems that the issue is caused by V8 as it is not able to allocate string with given size.

More information in [this V8 issue comment](https://code.google.com/p/v8/issues/detail?id=362#c9):

> This puts a limit on the maximally possible allocation request in 32-bit versions of 2^27-1. The maximal flat string length is ~2^28 (512MB space), and the maximal string length is 2^29-1, so neither of these limits catch the problem (we would throw an Out-Of-Memory exception instead if they did).

**Comment by robmcl4** [comment] 2015-06-26 01:48
👍 That seems to be the problem. Additionally, this seems to be a duplicate of #7210.

**Comment by izuzak** [comment] 2015-06-26 09:29
Yeah, closing in favor of https://github.com/atom/atom/issues/7417. Thanks for the report and the details, everyone.

**Closed by izuzak** 2015-06-26 09:29 UTC
Labels: more-information-needed, needs-reproduction

**Comment by UShan89** [comment] 2016-03-31 04:32
When trying to open large JSON files (Tested on size 262 Megabytes), ATOM throws this error
