### ISSUE TITLE
Atom refocuses the application while starting

### ISSUE THREAD

**Issue by jorangreef** [atom/atom#7166] opened 2015-06-08 06:52 UTC
I noticed this morning, that on OS X, Atom refocuses the application while starting up.

This means that if I CMD+TAB to another application while waiting for Atom to launch, Atom immediately grabs the focus back again.

And if I CMD+TAB again, Atom keeps grabbing it back again.

It would be great if these startup issues could be fixed quickly, especially the issue with Atom opening an untitled window all the time.

**Comment by Zireael07** [comment] 2015-06-08 07:24
Duplicate of #6828

**Comment by izuzak** [comment] 2015-06-08 07:39
Yep, closing in favor https://github.com/atom/atom/issues/6828 -- thanks @jorangreef and @Zireael07. :+1:

**Closed by izuzak** 2015-06-08 07:39 UTC

**Comment by jorangreef** [comment] 2015-06-08 08:28
Thanks @izuzak and @Zireael07.
