### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open $deletedFile

### ISSUE THREAD

**Issue by t128** [atom/atom#6802] opened 2015-05-15 10:46 UTC
[Enter steps to reproduce below:]

1. open $file in atom
2. delete $file

**Atom Version**: 0.199.0-f48351e
**System**: linux 3.13.0-52-generic (Ubuntu 14.04)
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open $deletedFIle

```
At events.js:141

Error: ENOENT: no such file or directory, open $deletedFIle
    at Error (native)
```

### Commands

```
     -4:48.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:47.5.0 core:save (atom-text-editor.editor.is-focused)
     -4:08.9.0 core:cut (atom-text-editor.editor.is-focused)
     -4:08.6.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -4:07.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:05.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:04.8.0 core:paste (atom-text-editor.editor.is-focused)
     -4:02.9.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -4:02.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:59.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -3:57.7.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:17.8.0 core:copy (atom-text-editor.editor.is-focused)
     -1:15.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:14.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:04.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/thomas/ws",
    "disabledPackages": [
      "tree-view",
      "background-tips"
    ],
    "audioBeep": false
  },
  "editor": {
    "fontFamily": "Source Code Pro Medium",
    "fontSize": 14,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-15 12:59
Duplicate of #6210, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-15 12:59 UTC
