### ISSUE TITLE
Double click open file in preview mode (Atom 0.206)

### ISSUE THREAD

**Issue by Santinell** [atom/atom#7111] opened 2015-06-05 05:32 UTC
With option "Use Preview Tabs" single click and double click on file in tree view open preview mode.
Double click in tree view as I understand must open normal tab.
Tested on Ubuntu 15.04 & Windows 8

**Comment by mnquintana** [comment] 2015-06-05 10:20
This is a duplicate of https://github.com/atom/tabs/issues/156 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-05 10:20 UTC
