### ISSUE TITLE
"Double click selection" should stick to the "variable name" pattern

### ISSUE THREAD

**Issue by narf** [atom/atom#6327] opened 2015-04-10 09:06 UTC
My main issue is with the character "$", currently when trying to select $myVar the double click only select myVar.
This is uber annoying since i'm used to call my variable like this.

Moreover when editing php scripts it gets more difficult to avoid this issue.

Overall, the double click selection should stick to the variable name pattern of the current language if possible, or accept the $ in the word, at least.

**Comment by izuzak** [comment] 2015-04-13 12:42
This looks like a duplicate of https://github.com/atom/language-php/issues/43. As mentioned in that issue, you can change the set of non-word characters locally for each language (in your config), and it's possible to change the per-language default (which is what that issue is asking). Can you add a comment there? Thanks!

**Closed by izuzak** 2015-04-13 12:42 UTC
