### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker layer

### ISSUE THREAD

**Issue by orangepizza** [atom/atom#19173] opened 2019-04-16 22:08 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker layer

```
At C:\Users\tempast\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11

Error: Cannot decorate a destroyed marker layer
    at DecorationManager.decorateMarkerLayer (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:519692)
    at TextEditor.decorateMarkerLayer (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:27615)
    at BufferSearch.setEditor (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:723928)
    at ~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:179012
    at refEditor.map.t (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:14:2787015)
    at RefHolder.map (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:14:2737323)
    at Proxy.observeEmbeddedTextEditor (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:14:2787008)
    at ~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:178901
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:1172021)
    at Emitter.emit (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:1173462)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:446819)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:455679)
    at Pane.activateItem (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:457849)
    at TabBarView.t.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:1123108)
```

### Commands

```
     -9:40 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
go-debug 1.6.2 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
pull-request 0.2.1 
```

**Comment by rsese** [comment] 2019-04-17 01:09
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by equals215** [comment] 2019-04-19 22:40
Got the same error right after switching desktop in MacOS, the current page loaded in Atom was a Unstaged Change page with no file selected.
If that can help you.

**Comment by lukeredpath** [comment] 2019-04-23 15:17
Also having the exact same problem. If I open a number of Unstaged Changes tabs when reviewing a commit, then use Cmd+W to close them all the tabs do not close the first time and I get this error.

**Comment by dsmontoya** [comment] 2019-04-25 21:21
I just got this error after clicking a project search result. I can't reproduce it.

**Comment by rsese** [comment] 2019-04-26 22:20
@equals215 @lukeredpath - if you're seeing this error when using the GitHub package, you can subscribe to https://github.com/atom/github/issues/2073.  If you happen to have specific repro steps that work consistently, feel free to share theme in https://github.com/atom/github/issues/2073 (I tried your steps @lukeredpath but couldn't reproduce, maybe I didn't have enough diff tabs open?).

**Comment by misode** [comment] 2019-04-28 18:21
I got this error after closing a project search.

**Comment by dsmontoya** [comment] 2019-04-29 18:12
Now got a similar error every time I started a new comment in Go and then wrote 3 chars (spaces didn't count). For example, this line triggered the error:

```Go
fmt.Println("lol") // 123
```

 Few minutes later the bug just disappeared.

```
Error: Cannot decorate a destroyed marker
    at DecorationManager.decorateMarker (/usr/share/atom/resources/app/src/decoration-manager.js:183:27)
    at TextEditor.decorateMarker (/usr/share/atom/resources/app/src/text-editor.js:2124:41)
    at new Selection (/usr/share/atom/resources/app/src/selection.js:20:41)
    at TextEditor.addSelection (/usr/share/atom/resources/app/src/text-editor.js:3233:27)
    at /usr/share/atom/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:79:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at MarkerLayer.module.exports.MarkerLayer.createMarker (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-layer.js:438:28)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker-layer.js:225:25)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/display-marker-layer.js:105:58)
    at TextEditor.addSelectionForBufferRange (/usr/share/atom/resources/app/src/text-editor.js:2860:38)
    at TextEditor.createLastSelectionIfNeeded (/usr/share/atom/resources/app/src/text-editor.js:3285:18)
    at TextEditor.getLastCursor (/usr/share/atom/resources/app/src/text-editor.js:2652:16)
    at TextEditor.getCursorBufferPosition (/usr/share/atom/resources/app/src/text-editor.js:2435:23)
    at SubsequenceProvider.bufferToSubsequenceMatches (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/subsequence-provider.js:149:60)
    at Array.map (native)
    at SubsequenceProvider.getSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/subsequence-provider.js:271:18)
    at providers.forEach.provider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1699:32)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:966:18)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1826:30)
    at mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:1373:25)
    at TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:3209:26)
    at TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:3180:42)
    at TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:1372:23)
    at TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:1338:23)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:1651:30)
```

Installed packages:

Built-in Atom Packages (92)
├── atom-dark-syntax@0.29.0
├── atom-dark-ui@0.53.1
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.1
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.9
├── one-light-ui@1.10.9
├── one-dark-syntax@1.8.1
├── one-light-syntax@1.8.1
├── solarized-dark-syntax@1.1.3
├── solarized-light-syntax@1.1.3
├── about@1.7.8
├── archive-view@0.64.1
├── autocomplete-atom-api@0.10.6
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.4
├── autocomplete-plus@2.40.0
├── autocomplete-snippets@1.11.2
├── autoflow@0.29.0
├── autosave@0.24.6
├── background-tips@0.27.1
├── bookmarks@0.45.0
├── bracket-matcher@0.88.1
├── command-palette@0.43.3
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.7
├── exception-reporting@0.42.0
├── find-and-replace@0.215.0
├── fuzzy-finder@1.7.3
├── github@0.8.4
├── git-diff@1.3.6
├── go-to-line@0.32.1 (disabled)
├── grammar-selector@0.49.8
├── image-view@0.62.4
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.1
├── line-ending-selector@0.7.4
├── link@0.31.4
├── markdown-preview@0.159.20
├── metrics@1.2.6
├── notifications@0.70.2
├── open-on-github@1.3.1
├── package-generator@1.3.0
├── settings-view@0.253.1-0
├── snippets@1.1.9
├── spell-check@0.72.5
├── status-bar@1.8.15
├── styleguide@0.49.9
├── symbols-view@0.118.1
├── tabs@0.109.1
├── timecop@0.36.2
├── tree-view@0.221.3
├── update-package-dependencies@0.13.0
├── welcome@0.36.6
├── whitespace@0.37.5
├── wrap-guide@0.40.3
├── language-c@0.58.1
├── language-clojure@0.22.5
├── language-coffee-script@0.49.3
├── language-csharp@0.14.3
├── language-css@0.42.8
├── language-gfm@0.90.3
├── language-git@0.19.1
├── language-go@0.44.4
├── language-html@0.48.5
├── language-hyperlink@0.16.3
├── language-java@0.27.6
├── language-javascript@0.127.7
├── language-json@0.19.1
├── language-less@0.34.1
├── language-make@0.22.3
├── language-mustache@0.14.4
├── language-objective-c@0.15.1
├── language-perl@0.38.1
├── language-php@0.43.0
├── language-property-list@0.9.1
├── language-python@0.45.6
├── language-ruby@0.71.4
├── language-ruby-on-rails@0.25.3
├── language-sass@0.61.3
├── language-shellscript@0.25.4
├── language-source@0.9.0
├── language-sql@0.25.9
├── language-text@0.7.3
├── language-todo@0.29.3
├── language-toml@0.18.1
├── language-typescript@0.2.3
├── language-xml@0.35.2
└── language-yaml@0.31.1

Community Packages (8)
├── atom-ide-ui@0.11.2
├── go-debug@1.6.2
├── go-plus@6.1.0
├── go-signature-statusbar@1.2.3
├── go-types@1.2.1
├── language-logstash@0.1.7
├── language-protobuf@0.7.1
└── language-vue@0.24.0

**Comment by nathansobo** [comment] 2019-04-29 18:50
@rsese I've hit this one a few times over the last few days.

Can anyone on the @atom/github-package take a look at some of these stack traces? I'm seeing objects in my stack traces such as `RefHolder` that I know are in that package's code. On the other hand I'm also seeing references to `BufferSearch` which are from find and replace.

@rsese I think we should elevate the priority of this. It may even be a blocking issue if we haven't observed it on stable.

**Comment by smashwilson** [comment] 2019-04-29 19:14
I _think_ atom/github#2105 will take care of these. We'll likely cherry-pick it to the 0.28.0 line as well, especially if we confirm that it's no longer occurring on nightly once that ships.

**Comment by rsese** [comment] 2019-04-29 20:48
Ahh awesome, thanks @smashwilson :+1:  Wasn't sure if a fix for https://github.com/atom/github/issues/2073 might potentially resolve this issue where people see the error when not specifically using the GitHub package.  If people still hit this error with https://github.com/atom/github/issues/2073 resolved, I'll make sure to bring it to the next meeting @nathansobo 👍

**Closed** 2019-05-15 01:27 UTC
Labels: more-information-needed, uncaught-exception
