### ISSUE TITLE
Leaving context menu open causes "editor not responding" window to open

### ISSUE THREAD

**Issue by Ryan1729** [atom/atom#12781] opened 2016-09-26 15:56 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

If the context menu is left open for about 30s or so the "editor not responding" window pops up. After the "Keep waiting" button is clicked, there doesn't appear to be any further problems.

### Steps to Reproduce

1. Open a text file.
2. Right click and hover the mouse over the context menu
3. wait about 30s

**Expected behavior:** the editor/context menu remain available to use.

**Actual behavior:** "editor not responding" window popped up.

### Versions

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Ubuntu 16.04 LTS
kernel version: 4.4.0-38-generic

**Comment by Ben3eeE** [comment] 2016-09-26 16:30
Duplicate of https://github.com/atom/atom/issues/11901

**Closed** 2016-09-26 19:24 UTC
