### ISSUE TITLE
Unable to save Read Only File( EPERM: operation not permitted, open 'E:\NewBranch\ui-src\budgeting\model-builder\model\js\models\model.js')

### ISSUE THREAD

**Issue by vinuuu** [atom/atom#14907] opened 2017-06-28 10:27 UTC
hi,
unable to save Read Only File in atom
Error:

EPERM: operation not permitted, open 'E:\NewBranch\ui-src\budgeting\model-builder\model\js\models\modelTemplatesModel.js'

wheares in other Editors like Visual Studio code
it will prompt with a Message and option of Overwrite and after that saving the File

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2017-06-28 17:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/text-buffer/issues/107. You may want to subscribe there for updates.  Additionally, if you can fill out the issue template completely, that would be super helpful for us.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-28 17:12 UTC
