### ISSUE TITLE
editor folding keybinding & international keyboards

### ISSUE THREAD

**Issue by jeancroy** [atom/atom#8017] opened 2015-07-22 04:15 UTC
On some keyboard locale, one need to use `ctrl-alt` to access bracket & braces.

This mean I cannot type `[` without also typing `ctrl-alt-[`
The following key binding suppress character entry to do some editor-folding action.

````
"ctrl-alt-[": "editor:fold-current-row",
"ctrl-alt-]": "editor:unfold-current-row",
"ctrl-alt-{": "editor:fold-all",
"ctrl-alt-}": "editor:unfold-all",
````

It may be a small user base, but not being able to type `[]{}` in a programing editor is a big usability problem !

**Comment by jeancroy** [comment] 2015-07-22 04:45
Ok it get better

Using this in keymap.cson produce error as this issue
https://github.com/atom/atom/issues/7489
````
'atom-workspace atom-text-editor:not([mini])':
  "ctrl-alt-[": ""
  "ctrl-alt-]": ""
  "ctrl-alt-{": ""
  "ctrl-alt-}": ""
````

Using this in keymap.cson will allow to type a bracket, but will also keep the previous behavior of folding lines.
````
'atom-workspace atom-text-editor:not([mini])':
  "ctrl-alt-[": "native!"
  "ctrl-alt-]": "native!"
  "ctrl-alt-{": "native!"
  "ctrl-alt-}": "native!"
````

**Comment by mnquintana** [comment] 2015-07-22 14:47
This looks like a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-22 14:47 UTC
