### ISSUE TITLE
Null (0x00) characters are hidden even with Show Invisibles

### ISSUE THREAD

**Issue by wesinator** [atom/atom#18734] opened 2019-01-23 19:11 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Null characters are not displayed in file text, even if Show Invisibles setting is enabled.
#1839, #12157

### Steps to Reproduce

1. Open [null_bytes_wide_text.txt](https://github.com/atom/atom/files/2788767/null_bytes_wide_text.txt)
<img width="293" alt="image" src="https://user-images.githubusercontent.com/5124946/51630322-ddf46100-1f17-11e9-92cd-961faa07f7d7.png">

**Expected behavior:** Placeholder for null chars, e.g. <img width="15" alt="image" src="https://user-images.githubusercontent.com/5124946/51630114-4f7fdf80-1f17-11e9-903c-96b56d198551.png">

**Actual behavior:** No placeholder, chars are present but not visible in text. This makes the text look misleadingly normal when it actually has invalid chars that would break code.
<img width="88" alt="image" src="https://user-images.githubusercontent.com/5124946/51630185-7fc77e00-1f17-11e9-853e-3140f37d6e5b.png">

**Reproduces how often:** Always

### Versions
macOS 10.14
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.10
git 2.17.2

**Comment by lee-dohm** [comment] 2019-01-23 19:23
Thank you for contributing!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12157. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2019-01-23 19:23 UTC
