### ISSUE TITLE
Creating a new pane without cloning the current file

### ISSUE THREAD

**Issue by phaazon** [atom/atom#7868] opened 2015-07-13 13:43 UTC
When I create a new pane, it automatically pops with the file of the previous pane I was in. I’d like to pop an empty pane – a bit like in `vim`, because I always load another file and close the duplicated one each time, and that’s boring.

Is there already something to fix that? Thanks.

**Comment by simurai** [comment] 2015-07-14 03:49
@phaazon I'm using https://atom.io/packages/pain-split. Seems not maintained anymore, but still works for me.

**Comment by mnquintana** [comment] 2015-07-14 10:55
This looks like a duplicate of https://github.com/atom/atom/issues/4738 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-14 10:55 UTC
Labels: enhancement
