### ISSUE TITLE
[FeatureRequest] Toggle language

### ISSUE THREAD

**Issue by twifty** [atom/atom#17314] opened 2018-05-13 03:00 UTC
Most of the examples within the docs are written in coffee script. Now, whilst I understand most of the core is also written in coffee script and is second nature to the devs, not everybody uses it.

I for one find coffee script difficult to read (function return values, assigning to this in method parameter list, if .. unless, etc...)

I suggest the feature of having all code samples displayed in such a way the user can toggle between the preferred language (coffee, es6, js).

**Comment by rsese** [comment] 2018-05-14 17:00
Thanks for contributing!

We noticed that this looks basically like a duplicate of https://github.com/atom/flight-manual.atom.io/issues/36 so you can subscribe there for updates if you'd like.  

Also, for future issues please use the issue template as much as possible - the information in the template is helpful for us when triaging issues. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-14 17:00 UTC
