### ISSUE TITLE
File -> Open Folder displays Open File dialog

### ISSUE THREAD

**Issue by hkp-wcd** [atom/atom#18971] opened 2019-03-12 10:17 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

File -> Open Folder no longer shows the dialog for Open Folder instead displays the Open File dialog.
The Open Folder dialog is still accessible via Shortcut Ctrl+Shift+O

### Steps to Reproduce

1. Click File
2. Click Open Folder

**Expected behavior:** Opens Select Folder window

**Actual behavior:** Opens Select File window

**Reproduces how often:** 100%

### Versions

Atom    : 1.35.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

OS: Windows 10

**Comment by bindlock** [comment] 2019-03-12 10:36
The same behavior. Kubuntu 18.04

**Comment by RvZ** [comment] 2019-03-12 10:48
The same behavior on windows 10

**Comment by remyjacobs** [comment] 2019-03-12 10:49
Same here as well, on Win10

**Comment by bloopletech** [comment] 2019-03-12 10:50
Looks like this change https://github.com/atom/atom/pull/17529 introduced the bug via a copy+paste error, and the big was fixed in https://github.com/atom/atom/pull/18855, but that branch/commit didn't make it into 1.35.0: https://github.com/atom/atom/blob/v1.35.0/src/main-process/atom-application.js#L388

**Comment by rsese** [comment] 2019-03-12 17:14
Thanks for the report all :+1:  Reproduced on 1.35.0 with Ubuntu 18.04.

**Comment by jasonrudolph** [comment] 2019-03-12 20:59
It looks like this bug snuck into both Atom 1.35.0 _and_ Atom 1.36.0-beta0. 🙈 We're working on getting the fix from https://github.com/atom/atom/pull/18855 backported for inclusion in Atom 1.35.1 _and_ Atom 1.36.0-beta1. 

Thanks again for reporting this. :bow:

**Comment by Ellip-commerce** [comment] 2019-03-13 15:38
> It looks like this bug snuck into both Atom 1.35.0 _and_ Atom 1.36.0-beta0. 🙈 We're working on getting the fix from #18855 backported for inclusion in Atom 1.35.1 _and_ Atom 1.36.0-beta1.
> 
> Thanks again for reporting this. 🙇
When do you give a better version? I also have this problem

**Comment by Ellip-commerce** [comment] 2019-03-13 15:38
When do you give a better version? I also have this problem

**Comment by jasonrudolph** [comment] 2019-03-13 15:46
[Atom 1.35.1](https://github.com/atom/atom/releases/tag/v1.35.1) is now available with this fix. If you're on the beta channel, [Atom 1.36.0-beta1](https://github.com/atom/atom/releases/tag/v1.36.0-beta1) is now available with this fix as well.

If you continue to experience this issue after upgrading to the latest Atom version, please let us know.

**Closed by jasonrudolph** 2019-03-13 15:46 UTC
Labels: regression, triaged

**Comment by gabriel-tessier** [comment] 2019-03-14 02:02
I experienced the problem after upgrading to 1.35.0 then upgrade to 1.35.1, the window pop-up is correct "Open Folder" but after selecting the folder and click on OK nothing happen.

Upgrading via Kubuntu update.
