### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1756Error: Cannot ca...

### ISSUE THREAD

**Issue by chrispatterson** [atom/atom#19825] opened 2019-08-22 14:07 UTC
[Enter steps to reproduce:]

1. Unclear steps to reproduce, but alert was present when I tabbed back to atom from my browser

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1756
Error: Cannot call function 'getPosition' on missing remote object 1756
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 1756
Error: Cannot call function 'getPosition' on missing remote object 1756
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705396)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:705811)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -3:11.5.0 core:save (input.hidden-input)
     -2:33.6.0 core:cut (input.hidden-input)
     -2:32.1.0 core:paste (input.hidden-input)
     -2:26.5.0 core:backspace (input.hidden-input)
     -2:26.2.0 core:save (input.hidden-input)
     -1:59.4.0 editor:newline (input.hidden-input)
     -1:51.7.0 core:save (input.hidden-input)
     -1:48.5.0 core:backspace (input.hidden-input)
     -1:48 core:save (input.hidden-input)
     -1:34.4.0 core:delete (input.hidden-input)
     -1:32.8.0 core:backspace (input.hidden-input)
     -1:31.4.0 core:save (input.hidden-input)
     -1:13.6.0 core:backspace (input.hidden-input)
     -1:11.4.0 core:delete (input.hidden-input)
  6x -1:07.7.0 core:backspace (input.hidden-input)
     -0:52.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
behave-theme 1.7.0 
busy-signal 2.0.1 
git-blame 1.8.0 
github-atom-dark-syntax 0.5.0 
github-atom-light-syntax 0.5.0 
intentions 1.1.5 
language-slim 1.0.1 
linter 2.3.1 
linter-coffeescript 1.0.0 
linter-js-standard 6.1.2 
linter-js-yaml 1.4.6 
linter-rubocop 2.4.2 
linter-sass-lint 1.9.0 
linter-slim 2.0.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
nucleus-dark-ui 0.12.3 
pigments 0.40.2 
seti-syntax 1.2.0 
seti-ui 1.11.0 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
wordcount 3.1.0 
```

**Comment by rsese** [comment] 2019-08-22 16:21
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-22 16:21 UTC
