### ISSUE TITLE
Self-update has no progress indicator

### ISSUE THREAD

**Issue by atomsymbol** [atom/atom#19164] opened 2019-04-15 13:16 UTC
### Prerequisites

* **[not applicable]** Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* **[not applicable]** Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
* **[no]** Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* **[yes]** Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* **[not applicable]** Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In the Help menu, Atom is claiming that it is updating itself, but:

- There is no corresponding network activity (Windows 10: Ctrl+Shift+Esc)
- There is no progress indicator in Atom indicating how many bytes have been downloaded

*Previous requests to add a progress indicator have been ignored so far:* #4696 #9164 #18414

### Steps to Reproduce

1. Start Atom
2. Go to Help menu and see that Atom is claiming it is updating itself
3. Press Ctrl-Shift-Esc and display network activity
4. Repeat steps 2 and 3

**Expected behavior:** Atom is displaying progress information when updating itself

**Actual behavior:** There is no way to tell from Help menu whether update is actually being downloaded because there is no progress indicator

**Reproduces how often:** 100%

### Versions

1.35.0 1.35.1

### Additional Information

Windows 10 version 1809

**Comment by rsese** [comment] 2019-04-15 22:08
Thanks @atomsymbol - our engineers can't prioritize everything unfortunately but I'll mention this one to them again for you since I know that issues with the update experience can be frustrating.  But since this is a duplicate of https://github.com/atom/atom/issues/9164 we're going to close in favor of that issue for now unless the other maintainers think having this issue open separately is helpful (e.g. because https://github.com/atom/atom/issues/9164 is a higher level issue than specifically adding a progress indicator for update).

**Closed by rsese** 2019-04-15 22:08 UTC
