### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.40.1\ Templa...

### ISSUE THREAD

**Issue by Domaeae** [atom/atom#19889] opened 2019-09-08 05:11 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: DOMINIK-PC
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\WebDeveloper\AppData\Local\atom\app-1.40.1\ Templates usw'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat 'C:\Users\WebDeveloper\AppData\Local\atom\app-1.40.1\ Templates usw'
    at Proxy.realpathSync (fs.js:1744:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:335:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:1009306)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:1016235)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:989866)
```

### Commands

```
     -2:33.6.0 core:backspace (input.hidden-input)
     -2:32.5.0 core:save (input.hidden-input)
     -2:15.9.0 tree-view:remove (div.header.list-item)
     -2:01.6.0 tree-view:duplicate (li.file.entry.list-item.selected)
     -1:58.8.0 core:select-all (input.hidden-input)
     -1:56.2.0 core:confirm (input.hidden-input)
     -1:50.1.0 core:undo (input.hidden-input)
  7x -1:49.4.0 core:close (input.hidden-input)
     -1:35.3.0 core:backspace (input.hidden-input)
     -1:34.4.0 snippets:next-tab-stop (input.hidden-input)
     -1:34.4.0 snippets:expand (input.hidden-input)
     -1:34.4.0 editor:indent (input.hidden-input)
     -1:32.6.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -1:32.1.0 core:backspace (input.hidden-input)
  2x -1:19.9.0 core:save (input.hidden-input)
     -1:01.9.0 tree-view:show-in-file-manager (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-i18n 0.21.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-minify 0.8.0 
atom-path-intellisense 1.1.1 
atom-ternjs 0.20.0 
auto-id-class 0.7.1 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.2 
autocomplete-paths 2.12.2 
autocomplete-project-paths 2.2.0 
bezier-curve-editor 0.7.2 
chrome-color-picker 0.8.0 
css-snippets 1.1.0 
css-spy 0.6.0 
emmet 2.4.3 
file-icons 2.1.35 
hyperclick 0.1.5 
improved-chester-atom-syntax 0.3.0 
jQuery 1.2.6 
jquery-snippets 11.0.0 
jsdelivr 1.0.1 
one-dark-material-syntax 1.0.3 
pigments 0.40.2 
platformio-ide-terminal 2.9.4 
puddletown-css-snippets 1.1.0 
rain-syntax 2.1.2 
rocket-dark-syntax 1.0.0 
snow-dark-material-syntax 0.1.1 
```

**Comment by rsese** [comment] 2019-09-09 17:39
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-09-09 17:39 UTC
