### ISSUE TITLE
Uncaught Error: spawn /Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.v...

### ISSUE THREAD

**Issue by y-okumura** [atom/atom#10553] opened 2016-01-23 04:57 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1029:26)
    at EventEmitter.outerCallback (/Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.voXWRFp/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:244:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2016-01-23 12:44
Thanks for the report! This looks like a duplicate of #9559 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-23 12:44 UTC

**Comment by penbor** [comment] 2016-02-15 07:14
来自我的华为手机-------- 原始邮件 --------主题：[atom] Uncaught Error: spawn /Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.v... (#10553)发件人：Y Okumura 收件人：atom/atom 抄送：[Enter steps to reproduce below:]

1 
2 

Atom Version: 140
System: Mac OS X 10112
Thrown From: Atom Core

Stack Trace

Uncaught Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT

At eventsjs:141

Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT
    at exports_errnoException (utiljs:837:11)
    at ProcessChildProcess_handleonexit (internal/child_processjs:178:32)
    at onErrorNT (internal/child_processjs:344:16)
    at doNTCallback2 (nodejs:441:9)
    at process_tickCallback (nodejs:355:17)
    at EventEmitteripcsendSync (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/ipcjs:21:31)
    at BrowserWindowObjectdefinePropertyget [as loadSettings] (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/remotejs:160:27)
    at ObjectwindowState (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:17:39)
    at Objectstringify (native)
    at exportssetWindowLoadSettings (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:27:52)
    at ApplicationDelegatemoduleexportsApplicationDelegatesetRepresentedDirectoryPaths (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:172:14)
    at /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:844:44
    at FunctionmoduleexportsEmittersimpleDispatch (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:25:14)
    at EmittermoduleexportsEmitteremit (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:125:28)
    at ProjectmoduleexportsProjectaddPath (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/projectjs:255:29)
    at AtomEnvironmentmoduleexportsAtomEnvironmentopenLocations (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:1029:26)
    at EventEmitterouterCallback (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:244:18)
    at emitTwo (eventsjs:92:20)
    at EventEmitteremit (eventsjs:172:7)


Commands


Config

{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true
  }
}

Installed Packages

# User
No installed packages

# Dev
No dev packages

**Comment by penbor** [comment] 2016-02-15 07:14
来自我的华为手机-------- 原始邮件 --------主题：[atom] Uncaught Error: spawn /Users/uokumura/Library/Application Support/com.github.atod的m.ShipIt/update.v... (#10553)发件人：Y Okumura 收件人：atom/atom 抄送：[Enter steps to reproduce below:]

1 
2 

Atom Version: 140
System: Mac OS X 10112
Thrown From: Atom Core

Stack Trace

Uncaught Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT

At eventsjs:141

Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT
    at exports_errnoException (utiljs:837:11)
    at ProcessChildProcess_handleonexit (internal/child_processjs:178:32)
    at onErrorNT (internal/child_processjs:344:16)
    at doNTCallback2 (nodejs:441:9)
    at process_tickCallback (nodejs:355:17)
    at EventEmitteripcsendSync (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/ipcjs:21:31)
    at BrowserWindowObjectdefinePropertyget [as loadSettings] (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/remotejs:160:27)
    at ObjectwindowState (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:17:39)
    at Objectstringify (native)
    at exportssetWindowLoadSettings (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:27:52)
    at ApplicationDelegatemoduleexportsApplicationDelegatesetRepresentedDirectoryPaths (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:172:14)
    at /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:844:44
    at FunctionmoduleexportsEmittersimpleDispatch (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:25:14)
    at EmittermoduleexportsEmitteremit (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:125:28)
    at ProjectmoduleexportsProjectaddPath (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/projectjs:255:29)
    at AtomEnvironmentmoduleexportsAtomEnvironmentopenLocations (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:1029:26)
    at EventEmitterouterCallback (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:244:18)
    at emitTwo (eventsjs:92:20)
    at EventEmitteremit (eventsjs:172:7)


Commands


Config

{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true
  }
}

Installed Packages

# User
No installed packages

# Dev
No dev packages

**Comment by penbor** [comment] 2016-02-15 07:14
来自我的华为手机-------- 原始邮件 --------主题：[atom] Uncaught Error: spawn /Users/uokumura/Library/A&pplication Support/com.github.ato的m.ShipIt/update.v... (#10553)发件人：Y Okumura 收件人：atom/atom 抄送：[Enter steps to reproduce below:]

1 
2 

Atom Version: 140
System: Mac OS X 10112
Thrown From: Atom Core

Stack Trace

Uncaught Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT

At eventsjs:141

Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT
    at exports_errnoException (utiljs:837:11)
    at ProcessChildProcess_handleonexit (internal/child_processjs:178:32)
    at onErrorNT (internal/child_processjs:344:16)
    at doNTCallback2 (nodejs:441:9)
    at process_tickCallback (nodejs:355:17)
    at EventEmitteripcsendSync (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/ipcjs:21:31)
    at BrowserWindowObjectdefinePropertyget [as loadSettings] (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/remotejs:160:27)
    at ObjectwindowState (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:17:39)
    at Objectstringify (native)
    at exportssetWindowLoadSettings (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:27:52)
    at ApplicationDelegatemoduleexportsApplicationDelegatesetRepresentedDirectoryPaths (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:172:14)
    at /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:844:44
    at FunctionmoduleexportsEmittersimpleDispatch (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:25:14)
    at EmittermoduleexportsEmitteremit (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:125:28)
    at ProjectmoduleexportsProjectaddPath (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/projectjs:255:29)
    at AtomEnvironmentmoduleexportsAtomEnvironmentopenLocations (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:1029:26)
    at EventEmitterouterCallback (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:244:18)
    at emitTwo (eventsjs:92:20)
    at EventEmitteremit (eventsjs:172:7)


Commands


Config

{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true
  }
}

Installed Packages

# User
No installed packages

# Dev
No dev packages

**Comment by penbor** [comment] 2016-02-15 12:26
来自我的华为手机!-------- 原始邮件 --------主题：[atom] Uncaught Error: spawn /Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.v... (#10553)发件人：Y Okumura 收件人：atom/atom 抄送：[Enter steps to reproduce below:]

1 
2 

Atom Version: 140
System: Mac OS X 10112
Thrown From: Atom Core

Stack Trace

Uncaught Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT

At eventsjs:141

Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT
    at exports_errnoException (utiljs:837:11)
    at ProcessChildProcess_handleonexit (internal/child_processjs:178:32)
    at onErrorNT (internal/child_processjs:344:16)
    at doNTCallback2 (nodejs:441:9)
    at process_tickCallback (nodejs:355:17)
    at EventEmitteripcsendSync (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/ipcjs:21:31)
    at BrowserWindowObjectdefinePropertyget [as loadSettings] (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/remotejs:160:27)
    at ObjectwindowState (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:17:39)
    at Objectstringify (native)
    at exportssetWindowLoadSettings (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:27:52)
    at ApplicationDelegatemoduleexportsApplicationDelegatesetRepresentedDirectoryPaths (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:172:14)
    at /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:844:44
    at FunctionmoduleexportsEmittersimpleDispatch (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:25:14)
    at EmittermoduleexportsEmitteremit (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:125:28)
    at ProjectmoduleexportsProjectaddPath (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/projectjs:255:29)
    at AtomEnvironmentmoduleexportsAtomEnvironmentopenLocations (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:1029:26)
    at EventEmitterouterCallback (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:244:18)
    at emitTwo (eventsjs:92:20)
    at EventEmitteremit (eventsjs:172:7)


Commands


Config

{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true
  }
}

Installed Packages

# User
No installed packages

# Dev
No dev packages

**Comment by penbor** [comment] 2016-02-15 12:26
！',亅x来自我的华为手机 -----   --- 原始邮件 --------主题：[atom] Uncaught Error: spawn /Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.v... (#10553)发件人：Y Okumura 收件人：atom/atom 抄送：cv,l[Enter steps to reproduce below:]

1 
2 

Atom Version: 140
System: Mac OS X 10112
Thrown From: Atom Core

Stack Trace

Uncaught Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT

At eventsjs:141

Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT
    at exports_errnoException (utiljs:837:11)
    at ProcessChildProcess_handleonexit (internal/child_processjs:178:32)
    at onErrorNT (internal/child_processjs:344:16)
    at doNTCallback2 (nodejs:441:9)
    at process_tickCallback (nodejs:355:17)
    at EventEmitteripcsendSync (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/ipcjs:21:31)
    at BrowserWindowObjectdefinePropertyget [as loadSettings] (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/remotejs:160:27)
    at ObjectwindowState (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:17:39)
    at Objectstringify (native)
    at exportssetWindowLoadSettings (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:27:52)
    at ApplicationDelegatemoduleexportsApplicationDelegatesetRepresentedDirectoryPaths (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:172:14)
    at /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:844:44
    at FunctionmoduleexportsEmittersimpleDispatch (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:25:14)
    at EmittermoduleexportsEmitteremit (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:125:28)
    at ProjectmoduleexportsProjectaddPath (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/projectjs:255:29)
    at AtomEnvironmentmoduleexportsAtomEnvironmentopenLocations (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:1029:26)
    at EventEmitterouterCallback (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:244:18)
    at emitTwo (eventsjs:92:20)
    at EventEmitteremit (eventsjs:172:7)


Commands


Config

{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true
  }
}

Installed Packages

# User
No installed packages

# Dev
No dev packages

**Comment by penbor** [comment] 2016-02-15 14:36
来自我的华为手机-------- 原始邮件 --------主题：[atom] Uncaught Error: spawn /Users/uokumura/Library/Application Support/com.github.atom.ShipIt/update.v... (#10553)发件人：Y Okumura 收件人：atom/atom 抄送：[Enter steps to reproduce below:]

1 
2 

Atom Version: 140
System: Mac OS X 10112
Thrown From: Atom Core

Stack Trace

Uncaught Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT

At eventsjs:141

Error: spawn /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Frameworks/Atom Helperapp/Contents/MacOS/Atom Helper ENOENT
    at exports_errnoException (utiljs:837:11)
    at ProcessChildProcess_handleonexit (internal/child_processjs:178:32)
    at onErrorNT (internal/child_processjs:344:16)
    at doNTCallback2 (nodejs:441:9)
    at process_tickCallback (nodejs:355:17)
    at EventEmitteripcsendSync (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/ipcjs:21:31)
    at BrowserWindowObjectdefinePropertyget [as loadSettings] (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/atomasar/renderer/api/lib/remotejs:160:27)
    at ObjectwindowState (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:17:39)
    at Objectstringify (native)
    at exportssetWindowLoadSettings (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/window-load-settings-helpersjs:27:52)
    at ApplicationDelegatemoduleexportsApplicationDelegatesetRepresentedDirectoryPaths (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:172:14)
    at /Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:844:44
    at FunctionmoduleexportsEmittersimpleDispatch (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:25:14)
    at EmittermoduleexportsEmitteremit (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/node_modules/event-kit/lib/emitterjs:125:28)
    at ProjectmoduleexportsProjectaddPath (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/projectjs:255:29)
    at AtomEnvironmentmoduleexportsAtomEnvironmentopenLocations (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/atom-environmentjs:1029:26)
    at EventEmitterouterCallback (/Users/uokumura/Library/Application Support/comgithubatomShipIt/updatevoXWRFp/Atomapp/Contents/Resources/appasar/src/application-delegatejs:244:18)
    at emitTwo (eventsjs:92:20)
    at EventEmitteremit (eventsjs:172:7)


Commands


Config

{
  "core": {},
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true
  }
}

Installed Packages

# User
No installed packages

# Dev
No dev packages

**Comment by joshaber** [comment] 2016-02-15 14:58
@y-okumura @penbor Thanks! Do you happen to remember how you launched Atom when you got this error?
