### ISSUE TITLE
Update.exe went rogue?

### ISSUE THREAD

**Issue by binaryfunt** [atom/atom#15369] opened 2017-08-17 14:53 UTC
Last night, I was on Atom 1.19.1, Windows 10. Things started to go a bit weird. My Windows `System` process (NT kernel & system) started hogging ~30% of my CPU indefinitely, which I had no reason to believe was anything to do with Atom. However, this morning nothing happened when I tried to open Atom. I noticed 1.19.2 had appeared in my `%LOCALAPPDATA%/atom/` folder, but I could only open 1.19.1, and when I did, it opened without any packages/themes enabled. I tried deleting the 1.19.2 folder (which didn't go to completion as something was using one of the files). Then, Norton flagged up `Update.exe` as acting suspiciously. I let it quarantine `Update.exe`, and then my `System` process stopped hogging the CPU (this could be a coincidence, of course). Anyway, I then successfully deleted 1.19.2 folder, and then downloaded the installer from the atom homepage. Now everything's working fine, I'm on 1.19.2. Not sure what happened there, but I thought I'd open an issue in case anyone else suffers the same fate and comes googling.

**Comment by rsese** [comment] 2017-08-18 01:46
Thanks for the detailed notes/observations :+1:  Agree that it's hard to say what might have happened since it seems like reproducing would be difficult (though I've seen a handful of issues where folks describe how their anti-virus software can sometimes affect updates or installs).  But thanks for sharing how you resolved the issue.

We'll go ahead and close this issue since we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog) for [tasks the need to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), but it'll be available when folks search through issues.

**Closed by rsese** 2017-08-18 01:46 UTC

**Comment by binaryfunt** [comment] 2017-08-29 21:56
Update: This has happened another couple of times. I've decided to stop automatically downloading updates

**Comment by binaryfunt** [comment] 2017-09-06 15:33
Update: currently on 1.19.4, I decided to try checking for updates. The same thing is happening again. `System` is hogging ~30% CPU, no real network or disk activity. I experimentally opened `SquirrelSetup.txt` and this is what it shows:

> 2017-09-06 16:07:53> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.19.4
2017-09-06 16:07:53> Program: Fetching update information, downloading from https://atom.io/api/updates-x64?version=1.19.4
2017-09-06 16:07:53> CheckForUpdateImpl: Using existing staging user ID: <redacted>
2017-09-06 16:07:53> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.19.4
2017-09-06 16:07:53> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.19.4&id=atom&localVersion=1.19.4&arch=amd64
2017-09-06 16:07:54> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.5-delta.nupkg
2017-09-06 16:08:16> UpdateInfo: Couldn't get release notes for:atom-1.19.5-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\<redacted>\AppData\Local\atom\packages\atom-1.19.5-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2017-09-06 16:08:16> Program: Starting Squirrel Updater: --update https://atom.io/api/updates-x64?version=1.19.4
2017-09-06 16:08:16> Program: Starting update, downloading from https://atom.io/api/updates-x64?version=1.19.4
2017-09-06 16:08:16> Program: About to update to: C:\Users\<redacted>\AppData\Local\atom
2017-09-06 16:08:17> CheckForUpdateImpl: Using existing staging user ID: <redacted>
2017-09-06 16:08:17> CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates-x64?version=1.19.4
2017-09-06 16:08:17> FileDownloader: Downloading url: https://atom.io/api/updates-x64/RELEASES?version=1.19.4&id=atom&localVersion=1.19.4&arch=amd64
2017-09-06 16:08:18> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.5-delta.nupkg
2017-09-06 16:09:05> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteEntryToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at SharpCompress.Readers.IReaderExtensions.WriteAllToDirectory(IReader reader, String destinationDirectory, ExtractionOptions options)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()
2017-09-06 16:09:05> CheckForUpdateImpl: Using existing staging user ID: <redacted>

**Comment by rsese** [comment] 2017-09-06 21:41
> 2017-09-06 16:09:05> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

I wonder if this is the problem or at least related?  

There's an issue for this particular error on install though it looks like it was closed as fixed:

https://github.com/atom/atom/issues/5109

Though it does look like a couple of people have reported they're still seeing the same error.

There is a workaround mentioned in https://github.com/atom/atom/issues/5109#issuecomment-153311100 if you want to give it a try but though not ideal, turning off updates and installing new releases from atom.io like you've been doing (and which sounds like it's working) is another workaround.

**Comment by ruv** [comment] 2017-09-10 02:04
I have the same issue regarding `PathTooLongException` in SquirrelSetup.log — this issue occurs on applying updates only and then setup falls back to full updates. This exception was not observed in updating to version 1.19.2.  Also, each delta is downloaded twice because of the same `System.Exception: Invalid 'ReleaseNotes' value in nuspec file`

Extract from `SquirrelSetup.log` for statistics:
```
2017-08-21 15:32:31> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.18.0
2017-08-21 15:32:37> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.0-delta.nupkg
2017-08-21 15:32:37> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.2-delta.nupkg
2017-08-21 15:32:37> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.1-delta.nupkg
2017-08-21 15:36:41> Program: Starting Squirrel Updater: --update https://atom.io/api/updates-x64?version=1.18.0
2017-08-21 15:36:42> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.0-delta.nupkg
2017-08-21 15:36:42> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.2-delta.nupkg
2017-08-21 15:36:42> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.1-delta.nupkg
2017-08-21 15:47:14> Program: Failed to apply updates, falling back to full updates: System.IO.EndOfStreamException: Attempted to read past the end of the stream.
2017-08-21 15:47:16> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.2-full.nupkg
2017-08-25 15:24:47> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.19.2
2017-08-25 15:24:53> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.3-delta.nupkg
2017-08-25 15:25:52> Program: Starting Squirrel Updater: --update https://atom.io/api/updates-x64?version=1.19.2
2017-08-25 15:25:53> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.3-delta.nupkg
2017-08-25 15:26:33> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
2017-08-25 15:26:33> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.3-full.nupkg
2017-08-29 16:51:20> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.19.3
2017-08-29 16:51:26> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.4-delta.nupkg
2017-08-29 16:54:54> Program: Starting Squirrel Updater: --update https://atom.io/api/updates-x64?version=1.19.3
2017-08-29 16:54:56> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.4-delta.nupkg
2017-08-29 16:57:57> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
2017-08-29 16:57:58> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.4-full.nupkg
2017-09-01 19:50:38> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.19.4
2017-09-01 19:50:48> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.5-delta.nupkg
2017-09-01 19:51:37> Program: Starting Squirrel Updater: --update https://atom.io/api/updates-x64?version=1.19.4
2017-09-01 19:51:40> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.5-delta.nupkg
2017-09-01 19:52:20> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
2017-09-01 19:52:21> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.5-full.nupkg
2017-09-09 18:53:36> Program: Starting Squirrel Updater: --download https://atom.io/api/updates-x64?version=1.19.5
2017-09-09 18:53:53> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.6-delta.nupkg
2017-09-09 18:53:53> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.7-delta.nupkg
2017-09-09 18:54:29> Program: Starting Squirrel Updater: --update https://atom.io/api/updates-x64?version=1.19.5
2017-09-09 18:54:31> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.6-delta.nupkg
2017-09-09 18:54:31> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.7-delta.nupkg
2017-09-09 18:55:06> Program: Failed to apply updates, falling back to full updates: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
2017-09-09 18:55:06> FileDownloader: Downloading file: https://atom.io/api/updates-x64/atom-1.19.7-full.nupkg
```

The command to get this extract: `grep -P 'Starting Squirrel Updater|Downloading file:|PathTooLongException|Failed to apply updates' SquirrelSetup.log`

My `%LOCALAPPDATA%` length is 29 bytes.
