### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 134Error: Cannot cal...

### ISSUE THREAD

**Issue by syafiqazizan02** [atom/atom#19958] opened 2019-09-25 06:23 UTC
Help my atom got some problem! Can anybody tell me what wrong is this?

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 134
Error: Cannot call function 'getPosition' on missing remote object 134
    at throwRPCError (C:\Users\User\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.40.1\resources\electron.asar\browser\api\web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

```
At C:\Users\User\AppData\Local\atom\app-1.40.1\resources\electron.asar\renderer\api\remote.js:219

Error: Cannot call function 'getPosition' on missing remote object 134
Error: Cannot call function 'getPosition' on missing remote object 134
    at throwRPCError (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/browser/rpc-server.js:367:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/browser/api/web-contents.js:294:13)
    at WebContents.emit (events.js:182:13)

    at metaToException (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/api/remote.js:123:16)
    at AtomEnvironment.getWindowDimensions (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:731570)
    at AtomEnvironment.storeWindowDimensions (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:731985)
    at WindowEventHandler.handleWindowBlur (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:285354)
```

### Commands

```
     -2:48.1.0 core:backspace (input.hidden-input)
     -2:45.9.0 intentions:highlight (input.hidden-input)
     -2:45.9.0 core:undo (input.hidden-input)
     -2:43.6.0 intentions:highlight (input.hidden-input)
  2x -2:43.2.0 core:save (input.hidden-input)
  2x -2:10.1.0 core:backspace (input.hidden-input)
     -1:03.9.0 intentions:highlight (input.hidden-input)
  2x -1:03.5.0 core:save (input.hidden-input)
     -0:39.8.0 intentions:highlight (input.hidden-input)
  2x -0:39 core:save (input.hidden-input)
     -0:30.6.0 core:backspace (input.hidden-input)
     -0:30 autoclose-html:close-and-complete (input.hidden-input)
     -0:26.6.0 core:backspace (input.hidden-input)
     -0:24.9.0 autoclose-html:close-and-complete (input.hidden-input)
     -0:23.5.0 intentions:highlight (input.hidden-input)
  3x -0:23.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-codesearch 1.4.0 
atom-fuzzy-grep 0.17.2 
atom-ide-ui 0.13.0 
atom-ide-vue 1.1.0 
atom-live-server 2.3.0 
atom-php-navigation 0.7.0 
autoclose-html 0.23.0 
autosave-onchange 1.5.1 
blade-spacer 0.4.2 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.35 
goto-definition 1.3.4 
highlight-selected 0.16.0 
ide-php 0.7.18 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-babel 2.85.0 
linter 2.3.1 
linter-php 1.6.1 
linter-tidy 2.4.0 
linter-ui-default 1.8.0 
multi-cursor 2.1.5 
navigate 0.1.20 
php-cs-fixer 4.1.1 
php-fmt 0.1.2 
pigments 0.40.2 
vue-fmt 0.1.1 
```

**Comment by rsese** [comment] 2019-09-30 20:26
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

> Help my atom got some problem! Can anybody tell me what wrong is this?

Are you seeing this error repeatedly or did you see the error once?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-09-30 20:26 UTC
