### ISSUE TITLE
I lose my place when toggling a pane

### ISSUE THREAD

**Issue by sbrl** [atom/atom#19812] opened 2019-08-18 20:51 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
When toggling a pane when a long document is open, the text view jumps, and I lose my place.

### Steps to Reproduce

1. Open a long document
2. Scroll to somewhere in the middle
3. Toggle a pane (e.g. the Git pane)

**Expected behavior:**

It keeps the same line numbers in view.

**Actual behavior:**

It jumps to some other point in the file.

**Reproduces how often:**

All the time.

### Versions

```
$ atom --version
Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
$ apm --version
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.40.0
python 2.7.16
git 2.20.1
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
$ uname -a
Linux PC_NAME 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Additional Information

I recorded a video to show you what I mean: https://youtu.be/T0BleupDLu4

**Comment by rsese** [comment] 2019-08-19 17:53
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/15830 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-19 17:53 UTC

**Comment by sbrl** [comment] 2019-08-19 18:02
Thanks! That does look like my issue. I couldn't find it when I looked for it.

**Comment by rsese** [comment] 2019-08-20 05:12
No problem, there are quite a few issues, I've definitely missed things too!  But we do appreciate that you took the time to look for similar issues :bow:
