### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu

### ISSUE THREAD

**Issue by JbIPS** [atom/atom#6548] opened 2015-04-28 09:23 UTC
I right-clicked on a folder in the tree view

**Atom Version**: 0.194.0
**System**: Windows 7 Entreprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\jbrichardet\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -4:55.5.0 editor:checkout-head-revision (atom-text-editor.editor.is-focused)
  2x -3:41.6.0 window:focus-pane-on-right (atom-text-editor.editor)
     -3:17.5.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:47.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:38.2.0 core:cut (atom-text-editor.editor)
     -2:36.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:26.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:20.6.0 core:move-down (atom-text-editor.editor)
     -2:20.4.0 autocomplete-plus:confirm (atom-text-editor.editor)
     -2:15.8.0 core:save (atom-text-editor.editor)
     -2:08.7.0 core:copy (atom-text-editor.editor.is-focused)
     -2:01.2.0 core:paste (atom-text-editor.editor.is-focused)
     -1:59.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:52.2.0 core:paste (atom-text-editor.editor.is-focused)
     -1:51.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:30.6.0 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "node_modules"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "Tern"
    ],
    "projectHome": "Y:\\app-tfoumax"
  },
  "editor": {
    "invisibles": {},
    "softWrap": true,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
autocomplete-snippets, v1.2.0
javascript-snippets, v1.0.0
jshint, v1.3.5
language-ejs, v0.1.0
linter, v0.12.1
pretty-json, v0.3.3
save-session, v0.14.0
Search, v0.4.0
seti-syntax, v0.4.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-04-28 11:56
I'm going to keep this one open this time since it's started to come up a lot in 0.194.0-I don't believe that many people have messed up their installations that this specific error keeps appearing.

**Comment by forestjohnsonilm** [comment] 2015-04-28 13:40
this happened to me too -- http://pastebin.com/R5S7cerd

**Comment by mnquintana** [comment] 2015-04-28 14:07
@kevinsawicki Any chance this has to do with Atom updating from a non-asar to an asar release?

**Comment by kevinsawicki** [comment] 2015-04-28 20:15
> Any chance this has to do with Atom updating from a non-asar to an asar release?

It really shouldn't, if one file is in the asar archive then they all should be.

@zcbenz are there any related asar issues you know that might be what is going on here?

**Comment by zcbenz** [comment] 2015-04-29 01:54
It might be caused by the same reason with #6276.

**Comment by kevinsawicki** [comment] 2015-05-12 01:13
@JbIPS does this happen even when you restart Atom?

**Comment by kevinsawicki** [comment] 2015-05-12 01:14
Can anyone on Windows consistently reproduce this or is it intermittent?

**Comment by Rakin05** [comment] 2015-05-12 13:06
I had the same Issue, after i installed "project-manager" and "view-tail-large-files". Restarting the Editor fixed the Issue.

**Comment by JbIPS** [comment] 2015-05-18 14:18
After uninstalling "project-manager" and restarting, I never saw this error again

**Comment by Heather** [comment] 2015-05-18 18:32
@JbIPS same here

**Comment by pmwhite** [comment] 2015-06-22 17:25
I opened another issue about this.  It was closed in favor of this issue.
I had this problem because I had two instances of atom running. I closed down one and right clicked and I still got the error. I closed down the other, restarted atom, and it worked fine.

**Comment by 50Wliu** [comment] 2015-06-23 20:40
I've renamed this issue in an attempt to stop duplicate issues.  If it doesn't work I'll go back to the nicer issue title.

**Comment by izuzak** [comment] 2015-06-26 08:57
This was also reported in https://github.com/atom/atom/issues/7443. In that issue, @janlueders  and @james-Ballyhoo mentioned:

> The Issue can be solved if Atom is started as Administrator on Windows 7. Is it possible to get it run as normal User?

and

> Also experienced this bug (win 8.1).  Starting as Administrator stopped the error.  When I closed it and then started it as a normal user the error didn't re-occur.

cc @kevinsawicki in case this helps track down the problem.

**Closed** 2015-06-29 20:45 UTC
Labels: atom, bug, uncaught-exception, windows
