### ISSUE TITLE
markdown syntax: ** in code block cause blod display

### ISSUE THREAD

**Issue by gjp1120** [atom/atom#6565] opened 2015-04-29 05:58 UTC
![4](https://cloud.githubusercontent.com/assets/1322038/7385395/d581f674-ee77-11e4-9770-3a7f86a2b322.PNG)

**Comment by 50Wliu** [comment] 2015-04-29 12:02
Duplicate of atom/language-gfm#44, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-29 12:02 UTC
