### ISSUE TITLE
Improve tab visualization

### ISSUE THREAD

**Issue by natbraun** [atom/atom#10765] opened 2016-02-10 23:08 UTC
I'd like to add the possibility for the user to choose three characters for tab visualization. Here's the first assumption: a tab is defined by the column it ends at, not the column is starts at. See this example for Notepad++:
![image](https://cloud.githubusercontent.com/assets/12711504/12964971/3c714bba-d053-11e5-9613-9a4d942baaa5.png)

The idea would be to specify two characters:
1. The first character is there to 'fill the gaps'
2. The second character is necessarily put at the end.

Thus, if the tab is 5 characters long and you set the two characters to '-' and '>' respectively, it would display as '---->'. If the tab is only one character long, it would display as '>'

**Comment by benogle** [comment] 2016-02-10 23:34
Related discuss thread: https://discuss.atom.io/t/invisibles-tab-width-of-character/10504

**Comment by alexandernst** [comment] 2016-02-11 18:16
Also my open issue: https://github.com/atom/atom/issues/3051

**Comment by lee-dohm** [comment] 2016-02-11 22:16
Thanks for the pointer @alexandernst. Is this then a duplicate of your Issue?

**Comment by alexandernst** [comment] 2016-02-11 22:19
@lee-dohm Yes, this is a duplicate. If I understand correctly, @natbraun will be working on the issue itself and will be posting on my issue (we already started talking there).

**Comment by lee-dohm** [comment] 2016-02-11 22:20
Thanks for the update. That was my understanding too, I just wanted to be certain :grinning:

**Comment by natbraun** [comment] 2016-02-11 22:20
@lee-dohm @alexandernst Yes, this is a duplicate. We'll continue working on the original one. Thanks.

**Closed by lee-dohm** 2016-02-11 22:20 UTC
Labels: enhancement
