### ISSUE TITLE
Network Proxy Setting is needed

### ISSUE THREAD

**Issue by Loyalsoldier** [atom/atom#8439] opened 2015-08-19 13:32 UTC
I'm living in China, it's very very slow when searching, installing, updating the packages and themes.
**Hope you guys add a network proxy setting feature.**

**Thanks a lot!**

**Comment by kevinsawicki** [comment] 2015-08-19 23:31
I believe this is a duplicate of https://github.com/atom/atom/issues/3119

You can configure `apm` to use a proxy from the command line https://github.com/atom/apm#behind-a-firewall

**Closed by kevinsawicki** 2015-08-19 23:31 UTC

**Comment by Loyalsoldier** [comment] 2015-08-20 15:55
It seems the solution is  out of date. It doesn't work actually……
