### ISSUE TITLE
Opening a pending pane no longer correctly correctly triggers activation

### ISSUE THREAD

**Issue by thomasjo** [atom/atom#14648] opened 2017-05-26 08:46 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Opening a file as a pending pane no longer triggers activation as expected. The end result is that `atom.workspace.getActiveTextEditor` returns `undefined` until the user interacts with the text editor in some manner (e.g. moving the cursor or making the pane non-pending).

### Steps to Reproduce

1. Launch Atom in any folder that contains some files that can be opened.
2. Click on any file in the tree view (ensure it is opened in a pending pane).
3. Open up the developer tools console.
4. Execute `atom.workspace.getActiveTextEditor()`
5. Notice the method returns `undefined`
6. Click anywhere in the (pending) text editor.
7. Execute `atom.workspace.getActiveTextEditor()`
8. Notice the method returns a `TextEditor` object.

**Expected behavior:** Opening a file in a pending pane should immediately mark the text editor as active.

**Actual behavior:** The text editor in the pending pane is not marked as active until the user directly interacts with the pane/editor.

**Reproduces how often:** 100% of the time.

### Versions

Atom v1.7.2, and v1.19.0-dev-85e65ffd1.
Ubuntu 16.04 LTS

### Additional Information

This regression is the cause of the following issues:
* https://github.com/atom/status-bar/issues/194

**Comment by jasonrudolph** [comment] 2017-05-26 20:32
After digging into the code, I think I understand the underlying cause of this regression and the behavior described in https://github.com/atom/status-bar/issues/194. I'll try to explain my findings below.

### Findings

If you have Atom configured to [support pending pane items](http://flight-manual.atom.io/using-atom/sections/pending-pane-items/), and you click on a file in the tree-view, it opens a pending *pane item* in the workspace. That pane item is the text editor for the file that you clicked in the tree view. At this point, the tree view still has focus.

**In Atom 1.16.x and earlier**, the tree-view resided in a [Panel](https://atom.io/docs/api/v1.16.0/Panel). Panels have items, but panels don't have panes. When invoking [`atom.workspace.getActiveTextEditor()`](https://github.com/atom/atom/blob/v1.16.0/src/workspace.js#L830-L833), Atom would would [fetch the workspace's one and only pane container, get the active pane in that pane container, and then get that pane's active item](https://github.com/atom/atom/blob/v1.16.0/src/workspace.js#L816). That  pane item is the editor that got opened when you clicked the file in the tree view.

**Starting with Atom 1.17.0**, the tree-view resides in a [Dock](https://atom.io/docs/api/v1.17.0/Dock). A Dock has a pane container, and that pane container has pane items. When invoking [`atom.workspace.getActiveTextEditor()`](https://github.com/atom/atom/blob/v1.17.0/src/workspace.js#L1285-L1288), Atom [fetches the workspace's _active_ pane container](https://github.com/atom/atom/blob/v1.17.0/src/workspace.js#L1271), which happens to be the Dock. Atom then fetches the active pane item in that container, which happens to be the tree view. Because the active pane item is not a `TextEditor`, [`atom.workspace.getActiveTextEditor()` returns `undefined`](https://github.com/atom/atom/blob/v1.17.0/src/workspace.js#L1287).

Packages like [atom/encoding-selector](https://github.com/atom/encoding-selector/blob/63b3a6ed37f95d2fe7b53a2aa48725e649e01a6a/lib/encoding-status-view.js#L55) and [atom/grammar-selector](https://github.com/atom/grammar-selector/blob/c6894110ed45410afe0eb3bdfd4dcfc60f56166f/lib/grammar-status-view.js#L62) rely on `atom.workspace.getActiveTextEditor()` to populate info about the active text editor in the status bar. Because the behavior of `atom.workspace.getActiveTextEditor()` changed when used in combination with the tree-view and pending pane items, those packages fail to update the status bar when you use the tree-view to open a pending pane item.

---

I'm looking into our options for addressing this issue. So far, this seems similar to https://github.com/atom/find-and-replace/issues/901, and we could consider a similar fix. I'll follow up here once I have more to share.

**Comment by jasonrudolph** [comment] 2017-05-26 21:28
In addition relying on `atom.workspace.getActiveTextEditor()`, the [atom/encoding-selector](https://github.com/atom/encoding-selector/blob/63b3a6ed37f95d2fe7b53a2aa48725e649e01a6a/lib/encoding-status-view.js#L15) and [atom/grammar-selector](https://github.com/atom/grammar-selector/blob/a2d1b40a0763d817f1a5f9919049e45a6731f2a0/lib/grammar-status-view.js#L13) packages also rely on [`atom.workspace.observeActivePaneItem()`](https://github.com/atom/atom/blob/c78ffa2e82fe12b59d7797103dab8a3077ce4ab0/src/workspace.js#L651-L661) to update the status bar as you click on files in the tree-view to open a pending pane item.

**In Atom 1.16.x and earlier**, clicking on a file in the tree-view would open a new pane item in the one and only pane container. That pane item would be the active pane item, and Atom would therefore notify observers of the active pane item. The encoding-selector and grammar-selector packages get this notification and update the status bar to display the file's encoding and grammar respectively.

For the same reasons described in https://github.com/atom/atom/issues/14648#issuecomment-304381899, **starting in Atom 1.17.0**, when you click on a file in the tree-view, it opens a new pane item in the workspace center, but that's just one of four possible pane containers. The dock (containing the tree-view) is the *active* pane container, and the tree-view is the active pane item. As you click on files in the tree-view, the tree-view remains the active pane item. Because the active pane item isn't changing, Atom doesn't trigger any callbacks for observers of the active pane item. Because the encoding-selector and grammar-selector packages don't get notified that a new file is present in the pending pane item, these packages don't update the status bar to display the file's encoding and grammar.

---

 I'll follow up here once I have more to share.

**Comment by jasonrudolph** [comment] 2017-05-30 21:42
After discussing this issue with @maxbrunsfeld, I'm leaning toward the following approach for resolving this issue and https://github.com/atom/status-bar/issues/194:

- Disallow editors in docks. Only allow editors in the workspace center.
- Change `atom.workspace.getActiveTextEditor()` to return the active text editor (if any) in the workspace center. (This is more consistent with the pre 1.17.0 behavior described in https://github.com/atom/atom/issues/14648#issuecomment-304381899.)
- Introduce `atom.workspace.observeActiveTextEditor()` as a means of observing the active text editor. (Packages like encoding-selector and grammar-selector _want_ to observe the active text editor, but currently have to rely on observing the active pane item, which is problematic for the reasons described in https://github.com/atom/atom/issues/14648#issuecomment-304391943.)
- For each of the core packages that currently use `atom.workspace.observeActivePaneItem()` to populate the status bar with file-related info, update those packages to use `atom.workspace.observeActiveTextEditor()` instead.

@matthewwithanm: Given your context on docks, is there anything about this approach that you would change?

**Closed** 2017-06-06 14:09 UTC
Labels: bug, regression, triaged

**Comment by marlazinger200** [comment] 2017-06-19 02:18
1
