### ISSUE TITLE
Opening minified Mathjax.js crashes editor

### ISSUE THREAD

**Issue by mangecoeur** [atom/atom#7931] opened 2015-07-16 14:17 UTC
Opening the minified Mathjax.js file in the editor (https://cdn.mathjax.org/mathjax/latest/MathJax.js) crashes the editor window.

**Comment by izuzak** [comment] 2015-07-16 14:22
Thanks for the report -- I believe this is a duplicate of https://github.com/atom/atom/issues/979.

**Closed by izuzak** 2015-07-16 14:22 UTC
