### ISSUE TITLE
Failed to load the nucleus package

### ISSUE THREAD

**Issue by sopsmattw** [atom/atom#9385] opened 2015-11-01 22:04 UTC
[Enter steps to reproduce below:]

1. Open the application
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the nucleus package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:2
    at Object.<anonymous> (<anonymous>:5:2)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 12,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-printer, vundefined
language-perl-template-toolkit, v0.1.0
lib, vundefined
menus, vundefined
node_modules, vundefined
nucleus, v0.3.0
remote-edit, v1.8.15

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-01 22:47
Duplicate of faceyspacey/nucleus#1, please subscribe there for updates.  In addition, it doesn't seem like `nucleus` has been updated to support the new Atom API, so it might be best for you to find a new package.

**Closed by 50Wliu** 2015-11-01 22:47 UTC
