### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Schrominger** [atom/atom#18413] opened 2018-11-09 04:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Window 10
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\abc\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:14

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:1108088)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:1103798)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:14:89276)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:79025)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:69678)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:67306)
    at visible.suppressUpdates.updatedSynchronously.updateScheduled.i.getScheduler.updateDocument (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:66334)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:323909)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-11-09 20:33
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/18378 so you can subscribe there for updates if you'd like.  If you have steps to reproduce, please let us know in https://github.com/atom/atom/issues/18378!

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-09 20:33 UTC
