### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by Jalarm** [atom/atom#17489] opened 2018-06-08 14:19 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'focus' of null

```
At C:\Users\Sergey\AppData\Local\atom\app-1.27.2\resources\app\node_modules\github\lib\views\commit-view.js:398

TypeError: Cannot read property 'focus' of null
    at CommitView.setState (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/github/lib/views/commit-view.js:398:35)
    at CallbackQueue.notifyAll (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/CallbackQueue.js:74:28)
    at ReactUpdatesFlushTransaction.close (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/ReactUpdates.js:57:30)
    at ReactUpdatesFlushTransaction.closeAll (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/Transaction.js:207:31)
    at ReactUpdatesFlushTransaction.perform (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/Transaction.js:154:22)
    at ReactUpdatesFlushTransaction.perform (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/ReactUpdates.js:87:38)
    at Object.flushBatchedUpdates (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/ReactUpdates.js:170:25)
    at ReactDefaultBatchingStrategyTransaction.closeAll (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/Transaction.js:207:31)
    at ReactDefaultBatchingStrategyTransaction.perform (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/Transaction.js:154:22)
    at Object.batchedUpdates (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:32)
    at Object.batchedUpdates (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/ReactUpdates.js:95:33)
    at dispatchEvent (~/AppData/Local/atom/app-1.27.2/resources/app/node_modules/react-dom/lib/ReactEventListener.js:145:26)
```

### Commands

```
     -4:52.4.0 core:paste (input.hidden-input)
     -4:51.7.0 core:save (input.hidden-input)
     -4:48.8.0 core:move-right (input.hidden-input)
  2x -4:47.9.0 core:backspace (input.hidden-input)
     -4:37.5.0 intentions:highlight (input.hidden-input)
     -4:37.3.0 core:save (input.hidden-input)
     -4:17.2.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:28.6.0 github:co-author:backspace (input.)
     -3:27.1.0 github:co-author:enter (input.)
     -2:44.2.0 github:toggle-github-tab (div.panels-item)
  7x -2:12.5.0 core:copy (atom-pane.pane.active)
     -0:56.1.0 github:co-author:enter (input.)
     -0:44.1.0 core:confirm (input.input-text.github-CoAuthorForm-name)
     -0:40.4.0 line-ending-selector:show (atom-text-editor.editor)
     -0:39.4.0 editor:consolidate-selections (input.hidden-input)
     -0:39.4.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.21 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
react 0.18.0 
react-redux-snippets 0.1.6 
```

**Comment by rsese** [comment] 2018-06-08 17:10
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error (looks like something with the GitHub package)?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment] 2018-07-13 20:21
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17489#issuecomment-395826124. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-07-13 20:21 UTC
Labels: more-information-needed, uncaught-exception
