### ISSUE TITLE
Editor changes screen upon update restart

### ISSUE THREAD

**Issue by ggeldenhuis** [atom/atom#14384] opened 2017-05-10 06:47 UTC
On mac (10.12.4 (16E195) ) when you restart Atom because of plug-in update it does not restore the window into the last position. My editor window is running on a large attached monitor and when I restart it, it opens up a smaller editor window on the laptop screen. 

Atom version: 1.16.0

**Comment by rsese** [comment] 2017-05-10 18:15
Thanks for the report!  Looks like a dupe of https://github.com/atom/atom/issues/12956 though https://github.com/atom/atom/issues/7555 also seems relevant (that issue was closed but a couple of people reported that they could still reproduce).  

Also, we require the issue template to be filled out with new issues so if you can fill out the template for future issues, that would be very helpful for us when triaging issues.

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/12956. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-10 18:15 UTC
