### ISSUE TITLE
Atom crashes when I open large files

### ISSUE THREAD

**Issue by db2k** [atom/atom#6641] opened 2015-05-04 12:29 UTC
Hello,

the only thing keeping me away from atom is the fact that it's crashing everytime I try to open a large file, jquery.min.js for example. In comparision to sublime, this is pretty bad because when atom doesn't crash, it takes up to 10 seconds to load the syntax highlighter.

Is there an issue similar to this or is this already tracked?

I'm using OSX Yosemite and Windows 8.1

**Comment by mnquintana** [comment] 2015-05-04 12:34
Duplicate of #307, #1667, #979 – this is currently being actively worked on in https://github.com/atom/text-document.

**Closed by mnquintana** 2015-05-04 12:34 UTC

**Comment by lance-p** [comment] 2016-06-07 15:10
Any update on this? I'm having this issue where opening a .js file with 3400 lines in it causes atom to hang and won't open the file. I'm using win10, Atom 1.8.0. I tried starting Atom in safe mode, but this doesn't help. Thanks.

**Comment by Nejurgis** [comment] 2017-02-09 22:14
Hello I have the same issue, I've got a looooooong min.js file that makes atom unresponsive once i try to edit it

**Comment by daverickdunn** [comment] 2017-02-13 13:05
This is not a new issue. [See here... ](https://github.com/atom/atom/issues/979) I've been using Atom daily for over a year now, and this is the biggest persistent issue I have had by far.

**Comment by aaadryyy** [comment] 2018-01-31 10:21
Still...

Crashs opening the Bootstrap 4 Source File.
