### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by lukemorel** [atom/atom#7549] opened 2015-06-29 13:52 UTC
[Enter steps to reproduce below:]

1. right click on a directory

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
    at HTMLDocument.handler (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\DimitriSelectif\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -2:52.1.0 core:paste (atom-text-editor.editor.is-focused)
     -2:50.4.0 grammar-selector:show (atom-text-editor.editor)
     -2:35 core:save (atom-text-editor.editor.is-focused)
     -2:19.5.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -2:15.4.0 core:save (atom-text-editor.editor.is-focused)
 13x -1:12 core:backspace (atom-text-editor.editor.is-focused)
     -1:10.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:39.1.0 core:paste (atom-text-editor.editor.is-focused)
  4x -0:37.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:14 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:04.4.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {},
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-06-29 14:19
This is a duplicate of https://github.com/atom/atom/issues/6548 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-29 14:19 UTC
