### ISSUE TITLE
Move-Line-Down doesn't move entire line below last line

### ISSUE THREAD

**Issue by stenverbois** [atom/atom#7653] opened 2015-07-02 12:48 UTC
Selecting an entire line (or lines) prevents `editor:move-line-down` to swap it
with the last line in the editor.

Note: It does work when not selecting the entire line (i.e. not selecting the newline char)

![GIF:](http://media.giphy.com/media/xTiTnoUoSJL5vHiLKw/giphy.gif)

## Repro Steps

1. Open a file in the main editor
2. Select an entire line or lines
3. Use `editor:move-line-down` (or default `Ctrl-Down`)
4. Try to move it below the last line in the editor

**Expected:** The selected line swaps with the last line
**Actual:** It doesn't do anything

## Versions

* **Atom:**       1.0.0
* **Electron:** 0.22.3
* **OS:**         linux 3.19.0-15-generic
* **Misc**
    * apm  1.0.1
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.9
    * git 2.1.4

---

<small>This report was created using the package `bug-report` v0.7.1.</small>

**Comment by kubetz** [comment] 2015-07-02 13:27
I am currently on Windows 7 using Atom 1.0.0 and it is works for me :open_mouth: .

Have you tried closing all instances of atom and running `atom --safe`?

![works](https://cloud.githubusercontent.com/assets/1128248/8477997/c40ad454-20ce-11e5-89b9-77a612bf45ca.gif)

**Comment by kubetz** [comment] 2015-07-02 13:31
Was able to reproduce it on Windows 7 Atom 1.0.0.

Exactly as written above - occurs *only* when whole line is selected.

**Comment by stenverbois** [comment] 2015-07-02 14:34
Nice find, that's indeed the code that is causing this I think. The issue may be that `selection.end` of a fully selected line is on position 0 of the next line? That's where the cursor appears if you press `right` after selecting anyway.

**Comment by kubetz** [comment] 2015-07-02 14:47
@stenverbois Yeah, indeed.

I have no idea if it should fixed in `moveLineDown` directly or deeper in code that is setting `selection.end.row` and if it is fixed deeper then I am not sure if it won't break something else.

That is the reason I am not trying to fix anything :blush: . It also looks like there are no specs for moving lines :cold_sweat: .

**Comment by benogle** [comment] 2016-01-27 20:24
This was fixed by #8232

**Closed by benogle** 2016-01-27 20:24 UTC
Labels: atom
