### ISSUE TITLE
Add signing for linux installer

### ISSUE THREAD

**Issue by ungb** [atom/atom#15509] opened 2017-08-30 21:51 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Add signing for linux package

### Steps to Reproduce

See https://github.com/atom/atom/issues/15418#issuecomment-326072028 for the issue.

Currently on linux we don't sign our packages and it looks like newer package managers are being more strict about this. 

**Expected behavior:** [What you expect to happen]
We should add signing for linux packages(RPM and deb)

**Actual behavior:** [What actually happens]
Currently when installing from Zypper you get an error

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% on latest

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

see https://github.com/atom/atom/issues/15418

**Comment by pejas** [comment] 2017-09-29 10:46
Possible duplicate of #7635

**Comment by 50Wliu** [comment] 2017-10-03 19:58
Thanks @pejas.

**Closed by 50Wliu** 2017-10-03 19:58 UTC
Labels: installer, linux, triaged
