### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 382Error: Cannot cal...

### ISSUE THREAD

**Issue by benyanke** [atom/atom#18578] opened 2018-12-13 16:15 UTC
1. Had an existing project
2. Opened new file.

Not always reproducable, only occurs very occasionally.

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: KDE neon
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 382
Error: Cannot call function 'getPosition' on missing remote object 382
    at throwRPCError (/snap/atom/207/usr/share/atom/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/snap/atom/207/usr/share/atom/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/snap/atom/207/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At /snap/atom/207/usr/share/atom/resources/electron.asar/renderer/api/remote.js:221

Error: Cannot call function 'getPosition' on missing remote object 382
Error: Cannot call function 'getPosition' on missing remote object 382
    at throwRPCError (/snap/atom/207/usr/share/atom/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/snap/atom/207/usr/share/atom/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/snap/atom/207/usr/share/atom/resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at Object.exception (/snap/atom/207/usr/share/atom/resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (/snap/atom/207/usr/share/atom/resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (/snap/atom/207/usr/share/atom/resources/electron.asar/renderer/api/remote.js:125:16)
    at AtomEnvironment.getWindowDimensions (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:1:642179)
    at AtomEnvironment.storeWindowDimensions (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:1:642594)
    at WindowEventHandler.handleWindowBlur (/snap/atom/207/usr/share/atom/resources/app/static/<embedded>:11:286062)
```

### Commands

```
     -0:49.5.0 find-and-replace:show (input.hidden-input)
     -0:49.3.0 core:paste (input.hidden-input)
     -0:49 core:confirm (input.hidden-input)
     -0:47.6.0 pane:show-previous-item (input.hidden-input)
  2x -0:47.1.0 pane:show-next-item (input.hidden-input)
     -0:46.6.0 find-and-replace:show (input.hidden-input)
     -0:46.5.0 core:paste (input.hidden-input)
     -0:46.3.0 core:confirm (input.hidden-input)
  2x -0:40.7.0 pane:show-previous-item (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-12-13 21:32
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-12-13 21:32 UTC
