### ISSUE TITLE
`GLIBC_2.25' not found error

### ISSUE THREAD

**Issue by Und3rCover96** [atom/atom#18319] opened 2018-10-24 20:42 UTC
please fix this:
/snap/atom/204/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libgnutls.so.30)
/snap/atom/204/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /usr/lib/x86_64-linux-gnu/libp11-kit.so.0)

**Comment by rsese** [comment] 2018-10-24 20:55
Thanks for contributing!

Closing as a duplicate of https://github.com/atom/atom/issues/18170 - please install Atom 1.32 or 1.33 beta using one of the official installation methods (the Snap install is unofficial):

https://flight-manual.atom.io/getting-started/sections/installing-atom/

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-24 20:55 UTC
