### ISSUE TITLE
Unsaved, untitled buffers discarded when closing window, without prompting; Atom closes non-project space windows when quitting

### ISSUE THREAD

**Issue by wfdd** [atom/atom#10540] opened 2016-01-21 13:31 UTC
1. Open a new window outside of a project space
2. Write something
3. Quit Atom
4. Reopen Atom
5. It's all gone

And

1. Open a new window in project space
2. Open a new 'untitled' tab
3. Write something
4. Close window
5. It's all gone

Atom should either ask whether you want to save, or keep a backup.  Doing neither is.... simply staggering.

OS X 10.11, Atom 1.4.0.

**Comment by 50Wliu** [comment] 2016-01-21 14:07
@wfdd This seems to be a duplicate of #10474 - please subscribe there for updates.

**Closed by 50Wliu** 2016-01-21 14:07 UTC

**Comment by wfdd** [comment] 2016-01-21 14:13
Thanks, @50Wliu.
