### ISSUE TITLE
UI is rendering with font artifacts.

### ISSUE THREAD

**Issue by hbayindir** [atom/atom#16572] opened 2018-01-16 12:18 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Fonts are rendered with artifacts, code pane and menus are very hard to read and distracting.

### Steps to Reproduce

1. Open Atom

**Expected behavior:**

Fonts are rendered without problems.

**Actual behavior:**

Fonts are rendered with artifacts, regardless of selected font.

**Reproduces how often:**

100%

### Versions

`atom --version` returns the following.

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

- **Operating system:** Debian Testing, updated daily.
- **Installation source:** Official `deb` packages provided by atom.
- **Graphic adapter:** `Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)`
- **Driver version:** `2.99.917+git20161206-1`
- **Kernel version:**  `4.14.0-2-amd64`, as compiled by Debian.

#### Issue Snapshots
![atom-latest-screen-corruption](https://user-images.githubusercontent.com/479423/34988620-5bda132a-fad0-11e7-8b6e-268037b9a881.png)
![atom-latest-screen-corruption-menu](https://user-images.githubusercontent.com/479423/34988621-5c8c9734-fad0-11e7-91a9-2c810ce50dce.png)

**Comment by Zireael07** [comment] 2018-01-16 12:35
Duplicate of #15737?

**Comment by hbayindir** [comment] 2018-01-16 12:58
@Zireael07 Looks like it. I was unable to find it since it was closed. Please close this issue if necessary.

**Comment by Ben3eeE** [comment] 2018-01-16 13:04
@hbayindir Thanks for taking the time to contribute and thanks for filling out the issue template :slightly_smiling_face: We close issues when they are fixed on master. The fix for this issue is currently scheduled to be released in Atom 1.25.

Other users have reported that [downgrading freetype](https://github.com/atom/atom/issues/15737#issuecomment-340522754) or that adding [this style](https://github.com/atom/atom/issues/15737#issuecomment-355936149) to their stylesheet have worked as a workaround. I have not tested either of these methods but you may want to try them while waiting for Atom 1.25 to be released :slightly_smiling_face: 

----

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15737. The fix for this issue is currently scheduled to be released in Atom 1.25.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-01-16 13:04 UTC
Labels: duplicate
