### ISSUE TITLE
Trying to install Atom package.

### ISSUE THREAD

**Issue by z3t0** [atom/atom#5097] opened 2015-01-16 04:25 UTC
Hi, I am trying to install packages for Atom but almost every single time NPM throws an error. Look below. Thank you very much.

Installing “autocomplete-clang@0.6.0” failed.Hide output…

npm http GET https://registry.npmjs.org/atom-space-pen-views
npm http GET https://registry.npmjs.org/underscore-plus
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\Rafi\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Rafi\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Rafi\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\Rafi\\.atom\\.apmrc" "install" "C:\\Users\\Rafi\\AppData\\Local\\Temp\\d-115015-992-1xp8dy5\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115015-992-16a707u
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/atom-space-pen-views
npm http 304 https://registry.npmjs.org/underscore-plus
npm

**Comment by mnquintana** [comment] 2015-01-16 12:40
> npm ERR! Please check if you have git installed and in your PATH.
You need git installed and available in your PATH. It should probably be made clearer that git is an apm dependency (see https://github.com/atom/apm/issues/236)

**Comment by kevinsawicki** [comment] 2015-01-16 17:30
Closing as duplicate of https://github.com/atom/apm/issues/236

**Closed by kevinsawicki** 2015-01-16 17:30 UTC

**Comment by z3t0** [comment] 2015-01-16 18:26
Hi,

I have git installed and can access it from the command line, I am using
windows. Any ideas?
ᐧ

On Fri, Jan 16, 2015 at 11:31 AM, Kevin Sawicki <notifications@github.com>
wrote:

> Closing as duplicate of atom/apm#236
> <https://github.com/atom/apm/issues/236>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/5097#issuecomment-70289690>.
>



-- 
Thanks,
Rafi Khan

**Comment by kevinsawicki** [comment] 2015-01-16 18:29
@z3t0 does `apm install autocomplete-clang` from the command line work for you?

**Comment by z3t0** [comment] 2015-01-16 18:32
I'll let you know once I'm at home, but I have a question. In which
directory do I run that command? Thanks From CMD?
ᐧ

On Fri, Jan 16, 2015 at 12:30 PM, Kevin Sawicki <notifications@github.com>
wrote:

> @z3t0 <https://github.com/z3t0> does apm install autocomplete-clang from
> the command line work for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/5097#issuecomment-70298757>.
>



-- 
Thanks,
Rafi Khan

**Comment by kevinsawicki** [comment] 2015-01-16 18:34
Any directory should be fine to run that command from

**Comment by z3t0** [comment] 2015-01-17 00:05
Hi, Thanks a lot for your help. But that command resulted in a large error.
Here is the output.

C:\Users\Rafi>apm install autocomplete-clang
Installing autocomplete-clang to C:\Users\Rafi\.atom\packages failed

> runas@1.1.0 install
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-38
12-1ub3zxp\node_modules\autocomplete-clang\node_modules\clang-flags\node_modules
\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-3812-1ub3zxp\node_module
s\autocomplete-clang\node_modules\clang-flags\node_modules\pathwatcher\node_modu
les\runas>node
"c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\app\apm\n
ode_modules\atom-package-manager\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
odules\node-gyp\bin\node-gyp.js" rebuild

npm http GET https://registry.npmjs.org/atom-space-pen-views
npm http GET https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/atom-space-pen-views
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/pathwatcher
npm http GET https://registry.npmjs.org/fuzzaldrin
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/pathwatcher
npm http 200 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/fuzzaldrin
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/nan/1.2.0
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/runas
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/coffeestack
npm http 304 https://registry.npmjs.org/event-kit
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/runas
npm http 304 https://registry.npmjs.org/iconv-lite
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/coffeestack
npm http 304 https://registry.npmjs.org/nan/1.2.0
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http 200 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/source-map
npm http 200 https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
gypnpm http 200 https://registry.npmjs.org/mkdirp
npm ERR! Error: ENOENT, lstat
'C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-
115016-3812-1ub3zxp\node_modules\autocomplete-clang\node_modules\atom-space-pen-
views\node_modules\space-pen\node_modules\grim\node_modules\coffeestack\node_mod
ules\coffee-script\node_modules\mkdirp\index.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command
"c:\\Users\\Rafi\\AppData\\Local\\atom\\app-0.174.0\\resources\
\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe"
"c:\\Users\\Rafi
\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-pac
kage-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig"
"c:\\Users\\R
afi\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-
package-manager\\.apmrc" "--userconfig" "C:\\Users\\Rafi\\.atom\\.apmrc"
"instal
l"
"C:\\Users\\Rafi\\.atom\\.node-gyp\\.atom\\.apm\\autocomplete-clang\\0.6.0\\p
ackage.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-3812-1ub3zx
p
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-3812-1ub3z
xp\node_modules\autocomplete-clang\node_modules\atom-space-pen-views\node_module
s\space-pen\node_modules\grim\node_modules\coffeestack\node_modules\coffee-scrip
t\node_modules\mkdirp\index.js
npm ERR! fstream_path
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-38
12-1ub3zxp\node_modules\autocomplete-clang\node_modules\atom-space-pen-views\nod
e_modules\space-pen\node_modules\grim\node_modules\coffeestack\node_modules\coff
ee-script\node_modules\mkdirp\index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack
c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\ap
p\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\li
b\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm http 200 https://registry.npmjs.org/rimraf
npm ERR! Error: ENOENT, lstat
'C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-
115016-3812-1ub3zxp\node_modules\autocomplete-clang\node_modules\clang-flags\nod
e_modules\pathwatcher\node_modules\grim\node_modules\coffeestack\node_modules\so
urce-map\lib\source-map\source-map-generator.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command
"c:\\Users\\Rafi\\AppData\\Local\\atom\\app-0.174.0\\resources\
\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe"
"c:\\Users\\Rafi
\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-pac
kage-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig"
"c:\\Users\\R
afi\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-
package-manager\\.apmrc" "--userconfig" "C:\\Users\\Rafi\\.atom\\.apmrc"
"instal
l"
"C:\\Users\\Rafi\\.atom\\.node-gyp\\.atom\\.apm\\autocomplete-clang\\0.6.0\\p
ackage.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-3812-1ub3zx
p
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-3812-1ub3z
xp\node_modules\autocomplete-clang\node_modules\clang-flags\node_modules\pathwat
cher\node_modules\grim\node_modules\coffeestack\node_modules\source-map\lib\sour
ce-map\source-map-generator.js
npm ERR! fstream_path
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-38
12-1ub3zxp\node_modules\autocomplete-clang\node_modules\clang-flags\node_modules
\pathwatcher\node_modules\grim\node_modules\coffeestack\node_modules\source-map\
lib\source-map\source-map-generator.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack
c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\ap
p\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\li
b\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! Error: ENOENT, lstat
'C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-
115016-3812-1ub3zxp\node_modules\autocomplete-clang\node_modules\clang-flags\nod
e_modules\pathwatcher\node_modules\grim\node_modules\coffeestack\node_modules\co
ffee-script\lib\coffee-script\parser.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command
"c:\\Users\\Rafi\\AppData\\Local\\atom\\app-0.174.0\\resources\
\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe"
"c:\\Users\\Rafi
\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-pac
kage-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig"
"c:\\Users\\R
afi\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-
package-manager\\.apmrc" "--userconfig" "C:\\Users\\Rafi\\.atom\\.apmrc"
"instal
l"
"C:\\Users\\Rafi\\.atom\\.node-gyp\\.atom\\.apm\\autocomplete-clang\\0.6.0\\p
ackage.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-3812-1ub3zx
p
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-3812-1ub3z
xp\node_modules\autocomplete-clang\node_modules\clang-flags\node_modules\pathwat
cher\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\lib\c
offee-script\parser.js
npm ERR! fstream_path
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-38
12-1ub3zxp\node_modules\autocomplete-clang\node_modules\clang-flags\node_modules
\pathwatcher\node_modules\grim\node_modules\coffeestack\node_modules\coffee-scri
pt\lib\coffee-script\parser.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack
c:\Users\Rafi\AppData\Local\atom\app-0.174.0\resources\ap
p\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\li
b\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! runas@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@1.1.0 install script.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command
"c:\\Users\\Rafi\\AppData\\Local\\atom\\app-0.174.0\\resources\
\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe"
"c:\\Users\\Rafi
\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-pac
kage-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig"
"c:\\Users\\R
afi\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-
package-manager\\.apmrc" "--userconfig" "C:\\Users\\Rafi\\.atom\\.apmrc"
"instal
l"
"C:\\Users\\Rafi\\.atom\\.node-gyp\\.atom\\.apm\\autocomplete-clang\\0.6.0\\p
ackage.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd
C:\Users\Rafi\AppData\Local\Temp\apm-install-dir-115016-3812-1ub3zx
p
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm
ᐧ

On Fri, Jan 16, 2015 at 12:34 PM, Kevin Sawicki <notifications@github.com>
wrote:

> Any directory should be fine to run that command from
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/5097#issuecomment-70299531>.
>



-- 
Thanks,
Rafi Khan
