### ISSUE TITLE
The new Atom icon doesn't scale down well on Windows

### ISSUE THREAD

**Issue by Nathan2055** [atom/atom#4997] opened 2015-01-11 19:20 UTC
The new Atom icon looks very blurry and JPEG-y when viewed in cases where it would be shrunk, like in the top-left of a Windows window.

![blurry atom icon](https://cloud.githubusercontent.com/assets/4724556/5696386/ffe6ee4a-999c-11e4-8070-12032325dc0d.png)

**Comment by thedaniel** [comment] 2015-01-11 22:25
cc @simurai

**Comment by lee-dohm** [comment] 2015-01-11 22:55
Duplicate of #4811. @Nathan2055 please subscribe to that issue for updates.

**Closed by lee-dohm** 2015-01-11 22:55 UTC
