### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by geolyth** [atom/atom#7369] opened 2015-06-22 15:56 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Administrator\AppData\Local\atom\app-0.210.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -9:49.3.0 core:copy (atom-text-editor.editor.is-focused)
     -9:44.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -9:44.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:44 core:paste (atom-text-editor.editor.is-focused)
  2x -9:43.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "remote-edit"
    ]
  },
  "editor": {
    "invisibles": {},
    "softWrap": true,
    "preferredLineLength": 120,
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
aligner-css, v1.2.0
atom-color-highlight, v3.0.9
auto-detect-indentation, v0.4.2
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
emmet, v2.3.10
grunt-runner, v0.10.0
linter, v0.12.7
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-jshint, v0.1.6
minimap, v4.10.0
node-debugger, v1.0.5
pigments, v0.7.2
project-manager, v1.15.10
resize-indent, v0.2.1
tool-bar, v0.1.7
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-06-22 16:09
This is a duplicate of https://github.com/atom/atom/issues/6548 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-22 16:09 UTC
