### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getItems' of undefined

### ISSUE THREAD

**Issue by samgamage** [atom/atom#16084] opened 2017-11-02 23:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getItems' of undefined

```
At C:\Users\Sammy\AppData\Local\atom\app-1.21.2\resources\app\node_modules\tabs\lib\tab-bar-view.js:643

TypeError: Cannot read property 'getItems' of undefined
    at TabBarView.module.exports.TabBarView.onDrop (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/tabs/lib/tab-bar-view.js:643:30)
```

### Commands

```
     -2:52.9.0 core:paste (input.hidden-input)
     -2:52.7.0 editor:newline (input.hidden-input)
     -2:52.5.0 core:paste (input.hidden-input)
     -2:52.2.0 core:save (input.hidden-input)
     -2:47.1.0 core:paste (input.hidden-input)
     -2:46.8.0 core:save (input.hidden-input)
  2x -2:43.1.0 core:paste (input.hidden-input)
     -2:38.2.0 core:save (input.hidden-input)
     -0:36.7.0 core:copy (input.hidden-input)
     -0:35.9.0 editor:newline (input.hidden-input)
     -0:35.8.0 core:paste (input.hidden-input)
  2x -0:35.5.0 core:save (input.hidden-input)
     -0:24.6.0 core:copy (input.hidden-input)
     -0:23.8.0 editor:newline (input.hidden-input)
     -0:23.7.0 core:paste (input.hidden-input)
  2x -0:23.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
language-haml 0.25.2 
livereload 0.4.4 
```

**Comment by rsese** [comment] 2017-11-05 03:58
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tabs/issues/257. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-11-05 03:58 UTC
