### ISSUE TITLE
Atom still require "deprecated command-line tools" gvfs-bin, why?

### ISSUE THREAD

**Issue by thomas-nilsson-irfu** [atom/atom#20320] opened 2020-01-15 13:16 UTC
Why does atom still list `gvfs-bin` ("userspace virtual filesystem - deprecated command-line tools") as one of its dependencies for Linux 64b systems? What exactly is it still used for?

Looking through other issues here on github.com/atom/atom, I came across the following comment:
> Atom is using [an electron API](https://electronjs.org/docs/api/shell#shellmoveitemtotrashfullpath) to move items to the trash, this API used to default to `gvfs-trash` but this got changed in electron v3 to default to `gio`.
> 
> We're planning to upgrade to Electron v3 very soon ([WIP PR](https://github.com/atom/atom/pull/18916)), so this issue will get resolved quite soon.
> 
> _Originally posted by rafeca in https://github.com/atom/atom/issues/17452#issuecomment-490037674_

This Electron PR in question appears to have been merged, given that my atom installation now lists the following:
```shell
$ atom --version
Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

// With best regards,
Thomas Nilsson

**Comment by lee-dohm** [comment] 2020-01-15 17:07
Thanks for contributing!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/17452. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2020-01-15 17:07 UTC
