### ISSUE TITLE
[bug][Atom 1.11.2][Linux] Atom scrolls even when not focused

### ISSUE THREAD

**Issue by stlaz** [atom/atom#13129] opened 2016-11-02 12:12 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x]  Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? (hopefully)
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom does not seem to lose scrolling focus upon Alt+Tab to another application and then switching back to Atom.

### Steps to Reproduce

1. Be in Atom and check which line you're on
2. Alt+Tab to another application
3. Scroll up a few times
4. Alt+Tab back to Atom
5. Scroll down once

**Expected behavior:**
The file view scrolls down.

**Actual behavior:**
The current file view jumps up depending on how many scrolls you did.

### Versions
Not sure, been there for quite some time but I was not sure how to reproduce it successfully.

**OS and version**
Fedora 24, Linux 4.7.9-200.fc24.x86_64 GNU/Linux, Gnome 3.20.4

**Comment by Ben3eeE** [comment] 2016-11-02 12:22
This sounds like a duplicate of https://github.com/atom/atom/issues/12591 which has been fixed in Atom 1.12.

**Closed by Ben3eeE** 2016-11-02 12:22 UTC

**Comment by stlaz** [comment] 2016-11-02 12:24
Ah, sorry, there's so many issues it's hard to find anything there.
