### ISSUE TITLE
Uncaught TypeError: e.target.matches is not a function

### ISSUE THREAD

**Issue by abdohz** [atom/atom#16389] opened 2017-12-15 07:09 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: e.target.matches is not a function

```
At C:\Users\abdul\AppData\Local\atom\app-1.23.1\resources\app\node_modules\tree-view\lib\root-drag-and-drop.js:107

TypeError: e.target.matches is not a function
    at RootDragAndDropHandler.module.exports.RootDragAndDropHandler.onDragEnd (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/tree-view/lib/root-drag-and-drop.js:107:27)
    at RootDragAndDropHandler.onDragEnd (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/tree-view/lib/root-drag-and-drop.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```
teletype 0.4.0 
```

**Comment by rsese** [comment] 2017-12-15 18:34
Thanks for taking the time to contribute!

Closing as a duplicate of https://github.com/atom/tree-view/issues/1106, you can subscribe there for updates if you'd like.  If you can share any details in https://github.com/atom/tree-view/issues/1106 like what you were doing at the time of the error and whether you can reproduce, that would be super helpful.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-15 18:34 UTC
