### ISSUE TITLE
Uncaught Error: EACCES, open '/home/joao/.atom/compile-cache/cson/5af7724b023a6274b520f79f04fb798a67319ca7.json'

### ISSUE THREAD

**Issue by Joao-Henrique** [atom/atom#4897] opened 2015-01-07 17:35 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.17.0-031700-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EACCES, open '/home/joao/.atom/compile-cache/cson/5af7724b023a6274b520f79f04fb798a67319ca7.json'

```
At fs.js:75

Error: EACCES, open '/home/joao/.atom/compile-cache/cson/5af7724b023a6274b520f79f04fb798a67319ca7.json'
  at Error (native)

```

### Commands

```
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-01-07 17:52
I believe this is a duplicate of https://github.com/atom/atom/issues/3082

**Closed by kevinsawicki** 2015-01-07 17:52 UTC
