### ISSUE TITLE
paste from finder to file tree

### ISSUE THREAD

**Issue by soulcreate** [atom/atom#13382] opened 2016-12-04 16:36 UTC
### Prerequisites

* [*] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [*] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [-] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [-] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [*] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [*] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When I copy from finder in MacOS El Capitan and paste to Atom file tree, it not paste my file.

### Steps to Reproduce

1. Copy on finder
2. Paste in Atom project file tree

**Expected behavior:** My copy file must paste to Atom file tree

**Actual behavior:** Nothing paste to Atom file tree

### Versions
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.8.4

**Comment by 50Wliu** [comment] 2016-12-04 18:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/569. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-04 18:22 UTC
