### ISSUE TITLE
Uncaught Error: spawn EPERM

### ISSUE THREAD

**Issue by kozlac** [atom/atom#16039] opened 2017-10-30 23:47 UTC
[Enter steps to reproduce:]

1. Enter Settings via ctrl-,
2. Select System

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Windows 7 Enterprise Service Pack 1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn EPERM

```
At internal/child_process.js:313

Error: spawn EPERM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Registry.get (/app.asar/node_modules/winreg/lib/registry.js:616:14)
    at ShellOption.isRegistered (/app.asar/src/main-process/win-shell.js:40:91)
    at new SystemPanel (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/system-windows-panel.js:53:44)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/settings-view.js:220:26
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/settings-view.js:361:25)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/settings-view.js:419:30)
    at HTMLDivElement.clickHandler (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/settings-view/lib/settings-view.js:186:24)
```

### Commands

```
 45x -5:05.7.0 core:backspace (input.hidden-input)
     -3:33.8.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
     -3:03.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -2:53.9.0 core:backspace (input.hidden-input)
     -2:46.4.0 core:confirm (input.hidden-input)
     -2:38.6.0 autocomplete-plus:confirm (input.hidden-input)
  8x -2:37.9.0 core:backspace (input.hidden-input)
     -2:32.3.0 autocomplete-plus:cancel (input.hidden-input)
     -2:31.8.0 editor:newline (input.hidden-input)
  2x -2:08.3.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-10-31 19:29
Thanks for taking the time to contribute!

This looks like a of https://github.com/atom/settings-view/issues/948 - as mentioned in https://github.com/atom/settings-view/issues/948#issuecomment-301192797, do you have any issues running `regedit` on your machine?  If you do, then this error would be expected.

---

We noticed that this is a duplicate of https://github.com/atom/settings-view/issues/948. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-31 19:29 UTC
