### ISSUE TITLE
Ubuntu crash dialog each time I close Atom

### ISSUE THREAD

**Issue by orschiro** [atom/atom#12636] opened 2016-09-08 17:23 UTC
Dear all, 

Each time I close Atom, I receive the following crash dialog. 

Can anyone reproduce this on Ubuntu 16.04 using Atom 1.10.2?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18359289/90dc5d38-75f9-11e6-84a5-867e6f5bb6a6.png)

**Comment by 50Wliu** [comment] 2016-09-08 18:02
This is a duplicate of #12630 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-08 18:02 UTC

**Comment by orschiro** [comment] 2016-09-08 18:04
Thank you for the reference, @50Wliu!

-Robert
