### ISSUE TITLE
Uncaught Error: Unknown system error -69: Unknown system error -69, close

### ISSUE THREAD

**Issue by amithjkamath** [atom/atom#13906] opened 2017-03-01 14:57 UTC
[Enter steps to reproduce:]

1. Open a file from a network location where I have no write permission, and the disk quota is full.
2. Try to save a file (that already exists in that location) with new contents. 

If I touch a new file in that are in the command window, I see this:

$ touch textfile.txt
touch: textfile.txt: Disc quota exceeded

I'm not sure if this is specific to the way disk quota is handled in my network drive, or if it is a generic issue that occurs for such situations. Thanks!

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Unknown system error -69: Unknown system error -69, close

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

Error: Unknown system error -69: Unknown system error -69, close
    at Error (native)
    at Object.fs.closeSync (fs.js:609:18)
    at Object.fs.writeFileSync (fs.js:1361:23)
    at Object.writeFileSync (/app.asar/node_modules/fs-plus/lib/fs-plus.js:281:17)
    at File.module.exports.File.writeFileSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:285:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:463:21)
    at File.module.exports.File.writeSync (/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:380:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1068:19)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:893:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:15 core:save (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-03-03 20:47
Can you confirm if the error is reproducible and if you see the error in safe mode (`atom --safe`)?

**Comment by rsese** [comment] 2017-03-23 18:26
Thanks again for your issue!

We haven't received a response to our question in our comment https://github.com/atom/atom/issues/13906#issuecomment-284065975 yet and since this issue sounds pretty similar to https://github.com/atom/atom/issues/13923, I'm going to go ahead and close this as a duplicate.  Feel free to subscribe there for updates.

**Closed by rsese** 2017-03-23 18:26 UTC
Labels: more-information-needed
