### ISSUE TITLE
Uncaught Error: dlopen(~/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keybo...

### ISSUE THREAD

**Issue by ChrisGuy** [atom/atom#20704] opened 2020-05-07 08:20 UTC
getting this error each time I keydown.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At ELECTRON_ASAR.js:160

Error: dlopen(/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:1:695134)
    at get_KeyboardLayoutManager (/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2781650)
    at get_manager (/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2781752)
    at Object.getCurrentKeyboardLayout (/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:2781878)
    at e.keystrokeForKeyboardEvent (/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:1083882)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1251844)
    at KeymapManager.handleKeyboardEvent (/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1249829)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/chrismorgan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -2:01.4.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -1:17.5.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:49.3.0 tree-view:add-file (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-babel 2.85.0 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by lkashef** [comment] 2020-05-08 18:12
Hey @ChrisGuy, thanks for reaching out

This seems like a duplicate of https://github.com/atom/atom/issues/20401, caused mainly by a faulty installation.

I will go ahead and close this one, feel free to comment or open a new issue if the problem still persists.

**Closed by lkashef** 2020-05-08 18:12 UTC
