### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, open '\\fs\Public\Yanis.Urbis\C#'

### ISSUE THREAD

**Issue by yanis-urbis** [atom/atom#7925] opened 2015-07-16 06:35 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, open '\\fs\Public\Yanis.Urbis\C#'

```
At C:\Users\Yanis.urbis\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace.js:466

Error: UNKNOWN: unknown error, open '\\fs\Public\Yanis.Urbis\C#'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Project.module.exports.Project.open (C:\Users\Yanis.urbis\AppData\Local\atom\app-1.0.2\resources\app.asar\src\project.js:371:27)
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\Yanis.urbis\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace.js:449:31)
  at Workspace.module.exports.Workspace.open (C:\Users\Yanis.urbis\AppData\Local\atom\app-1.0.2\resources\app.asar\src\workspace.js:375:19)
  at EventEmitter.<anonymous> (C:\Users\Yanis.urbis\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:46:25)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-07-16 06:48
Thanks for the report -- this looks like a duplicate of https://github.com/atom/atom/issues/7922. Can you add a comment there and explain what you were doing when this happened, and if you can reliably reproduce this?

**Closed by izuzak** 2015-07-16 06:48 UTC
