### ISSUE TITLE
Tab jumps too far on new line when pervious line has hanging indent

### ISSUE THREAD

**Issue by phillynch7** [atom/atom#17015] opened 2018-03-22 15:53 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tab jumps too far on a new line with a hanging indent. I can already get to the proper indentation on the new line by hitting return from the pervious line. But it's impossible to get to the a single indentation without hitting out 4 spaces.

![atom_tabs](https://user-images.githubusercontent.com/15858076/37781397-012c1a3e-2dc7-11e8-9362-c82949a62cb1.gif)

### Steps to Reproduce

**Expected behavior:** Creates 1 tab.

**Actual behavior:** Jumps to hanging indent.

### Versions

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 3.6.4
git 2.14.3

**Comment by lee-dohm** [comment] 2018-03-22 16:01
Thank you for contributing!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/6655. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2018-03-22 16:01 UTC
