### ISSUE TITLE
(German) Umlauts in file path break file opening

### ISSUE THREAD

**Issue by AragurDEV** [atom/atom#14896] opened 2017-06-26 10:52 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you open a file or a project folder which has (German) umlauts, like Ä, Ö, Ü in it, text files opened will alway be empty

### Steps to Reproduce

1. Create a folder called Bäume (or any other folder containing umlauts).
2. Create test.txt file and open with Editor.
3. Write random word or sentence in it.
4. Open file or folder with Atom
5. File appears empty.

**Expected behavior:** File should be opened correctly

**Actual behavior:** File is empty

**Reproduces how often:** 100%

### Versions

Atom    : 1.19.0-beta1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Atom running on Windows 10 Pro (Creator Update)

**Comment by rsese** [comment] 2017-06-27 05:00
Thanks for taking the time to contribute!

We noticed that looks like a duplicate of https://github.com/atom/atom/issues/14894. You may want to subscribe there for updates but let me know if you think it's a different issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-27 05:00 UTC
