### ISSUE TITLE
Syntax highlighting broken for .gitconfig with escaped quotes

### ISSUE THREAD

**Issue by artagnon** [atom/atom#8883] opened 2015-09-21 19:25 UTC
This should explain the problem sufficiently:

<img width="731" alt="atom-gitconfig-quote-fail" src="https://cloud.githubusercontent.com/assets/37226/10002422/f6a18134-6074-11e5-9a22-cd6aa5b98c36.png">

**Comment by mnquintana** [comment] 2015-09-21 19:28
Thanks for the report! This looks like a duplicate of https://github.com/atom/language-git/issues/4 – please subscribe there for updates.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Closed by mnquintana** 2015-09-21 19:28 UTC
