### ISSUE TITLE
Mac fullscreen broken when switching resultions

### ISSUE THREAD

**Issue by pradeepg26** [atom/atom#9088] opened 2015-10-08 17:49 UTC
I see this problem when I plug-in my external monitors and the screen on which my atom is fullscreened changes (as well as the resolution). The area where atom is rendered is very small (smaller than the original resolution) and there is blank whitespace filling the remainder of the screen. See where the mouse is in the screenshot

![atom rendering broken](https://cloud.githubusercontent.com/assets/546081/10374860/33925bbc-6daa-11e5-8056-94a90b00955f.png)

**Comment by mnquintana** [comment] 2015-10-08 17:50
This looks like a duplicate of https://github.com/atom/atom/issues/8847 - please subscribe there for updates.

**Closed by mnquintana** 2015-10-08 17:50 UTC
