### ISSUE TITLE
[Feature request] Ability to search inside a package's setting page

### ISSUE THREAD

**Issue by chenglou** [atom/atom#12223] opened 2016-07-23 23:00 UTC
Some packages (e.g. Nuclide) have a long setting page. Being able to cmd-f and search through the page would be really helpful.

Thanks!

**Comment by 50Wliu** [comment] 2016-07-23 23:34
Closing as a duplicate of atom/settings-view#394 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-23 23:34 UTC
