### ISSUE TITLE
Right Click throws Error: Cannot find module './context-menu'

### ISSUE THREAD

**Issue by ajweeks** [atom/atom#7242] opened 2015-06-12 00:59 UTC
1. Right Click

**Atom Version**: 0.209.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\app.asar\src\window-event-handler.js:148:33)
  at HTMLDocument.handler (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\Admin\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  2x -1:03.8.0 typescript:go-to-declaration (button.btn.selected)
     -0:57.8.0 typescript:build (button.btn.selected)
     -0:53.2.0 linter:lint (atom-text-editor.editor)
     -0:48.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:46.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:46.9.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:42.6.0 typescript:build (atom-text-editor.editor.is-focused)
     -0:29.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:29.5.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -0:29.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:29.2.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:27.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:27.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:27.3.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:20.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.8.0 linter:lint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 140,
    "softWrap": true,
    "fontSize": 13,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.5.9
last-cursor-position, v0.9.0
linter, v0.12.7

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-06-12 01:01
Duplicate of https://github.com/atom/atom/issues/6548 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-12 01:01 UTC
