### ISSUE TITLE
Open files from browser with atom://

### ISSUE THREAD

**Issue by jaredmoody** [atom/atom#4290] opened 2014-11-23 00:27 UTC
It would be very useful if atom could open files from the browser like `atom://open?URL=/Users/me/myfile.txt.`, like sublime text's `subl://open`

This would be great for people writing/debugging web apps like me :)

**Comment by izuzak** [comment] 2015-01-03 10:36
I think this is a duplicate of https://github.com/atom/atom/issues/2037, so closing this one. :tophat:

**Closed by izuzak** 2015-01-03 10:36 UTC
Labels: enhancement
