### ISSUE TITLE
Add option: auto-update extensions

### ISSUE THREAD

**Issue by andya9** [atom/atom#11682] opened 2016-05-03 18:09 UTC
Currently we miss an option to auto-update user extensions, something like firefox and chromium do.
There is an old proposal [here](https://discuss.atom.io/t/can-i-turn-off-the-notifications/17117/9), but it seems it didn’t gain any attention.

Personally I need to manually update extensions every 1 or 2 days; and the more extensions we have, the more frequent it gets. 
It’s bothersome because we need to:

* click the notification
* wait a bunch for atom to check again for available updates (possibly a bug? it shouldn’t do it twice)
* click update all
* wait again and come back to close the tab; particularly painful with bigger extensions like atom-beautifier, that take ages to download on slower connections. (I had to uninstall it because it updated too much :wink:  world in reverse :smile_cat: )

**Comment by mnquintana** [comment] 2016-05-03 19:23
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/6897 though – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-05-03 19:23 UTC

**Comment by andya9** [comment] 2016-05-04 06:54
sorry, i searched for "autoupdate extensions" so i didn’t find it :smile:
