### ISSUE TITLE
Uncaught Error: dlopen(~/Desktop/CSCI 1133/Atom.app/Contents/Resources/app.asar.unpacked/node_mod...

### ISSUE THREAD

**Issue by ammylin** [atom/atom#21895] opened 2021-01-26 01:32 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: dlopen(/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found

```
At electron/js2c/asar.js:138

Error: dlopen(/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node, 1): image not found
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app/static/<embedded>:1:696987)
    at get_KeyboardLayoutManager (/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app/static/<embedded>:14:2796761)
    at get_manager (/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app/static/<embedded>:14:2796863)
    at Object.getCurrentKeyboardLayout (/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app/static/<embedded>:14:2796989)
    at e.keystrokeForKeyboardEvent (/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app/static/<embedded>:14:1057808)
    at KeymapManager.keystrokeForKeyboardEvent (/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app/static/<embedded>:11:1228079)
    at KeymapManager.handleKeyboardEvent (/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app/static/<embedded>:11:1226064)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/ammylin/Desktop/CSCI 1133/Atom.app/Contents/Resources/app/static/<embedded>:11:284879)
```

### Commands

```
     -1:45.4.0 command-palette:toggle (div.tool-panel.tree-view)
     -1:40.4.0 window:install-shell-commands (div.tool-panel.tree-view)
     -1:06.2.0 command-palette:toggle (div.tool-panel.tree-view)
     -1:01.7.0 window:install-shell-commands (div.tool-panel.tree-view)
```

### Non-Core Packages

```

```

**Comment by darangi** [comment] 2021-01-27 08:53
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/21285. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).a

**Closed by darangi** 2021-01-27 08:53 UTC
