### ISSUE TITLE
Using an apostrophe within a <script> tag while writing an HTML pattern breaks syntax highlighting

### ISSUE THREAD

**Issue by dep** [atom/atom#12895] opened 2016-10-06 17:12 UTC
When using backbone/underscore, I oftentimes need to write HTML within a <script> tag that will then be rendered as a pattern that underscore can use as a template to execute JS against.

Unfortunately, if my string contains an apostrophe, Atom thinks I'm trying to define a string and will trigger an open-ended syntax highlight event.

Here is a screenshot: http://dl.dpeck.net/1j3q6

Any tips to work around this are greatly appreciates.

**Comment by damieng** [comment] 2016-10-06 17:38
Partially complete dupe of #12896

**Closed by damieng** 2016-10-06 17:38 UTC

**Comment by dep** [comment] 2016-10-06 18:30
Apologies for this erroneous post.
