### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by oleggolev** [atom/atom#21496] opened 2020-10-13 20:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Unknown macOS version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Module did not self-register.

```
At electron/js2c/asar.js:138

Error: Module did not self-register.
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at get_KeyboardLayoutManager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2715520)
    at get_manager (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2715622)
    at Object.getCurrentKeyboardLayout (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2715748)
    at e.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1047867)
    at KeymapManager.keystrokeForKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1228180)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1226165)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284829)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-terminal 5.0.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-terminal 0.8.0 
autocomplete-python 1.16.0 
autocomplete-sql 0.5.0 
busy-signal 2.0.1 
ftp-remote-edit 0.18.0 
Hydrogen 2.14.1 
intentions 1.1.5 
kite 0.191.0 
language-ocaml 1.9.5 
language-reason 0.0.7 
language-x86-64-assembly 2.3.0 
linter 2.3.1 
linter-ui-default 1.8.1 
ocaml-indent 0.7.1 
ocaml-merlin 0.14.7 
project-manager 3.3.8 
reason-refmt 0.3.3 
remote-edit-ni 3.6.0 
script 3.25.0 
teletype 0.13.4 
terminal-tab 0.6.0 
```

**Comment by oleggolev** [comment] 2020-10-13 20:06
Using Atom as an OCaml IDE. No changes were made in the past 2 weeks. Atom refuses to edit the files with the "Module did not self-register" error. Is this tracked somewhere else already?

**Comment by darangi** [comment] 2020-10-13 21:26
Hi @oleggolev , could you provide steps to reproduce this issue?

> Using Atom as an OCaml IDE. No changes were made in the past 2 weeks. Atom refuses to edit the files with the "Module did not self-register" error. Is this tracked somewhere else already?

**Comment by sadick254** [comment] 2020-10-19 18:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #20222. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by sadick254** 2020-10-19 18:12 UTC
