### ISSUE TITLE
Unable to open folder - Text-buffer issue

### ISSUE THREAD

**Issue by pink-raks** [atom/atom#17054] opened 2018-03-30 12:51 UTC
Hi,

I am facing issue while opening a folder having nodejs files. Attached is the snapshot of the issue
Please note that I do not have the folder C:\Users\XXX\AppData\Local\atom\app-1.25.0\resources\app\node_modules folder under the app folder.
![atom_issue](https://user-images.githubusercontent.com/20509460/38138230-52a1a164-3447-11e8-8266-ee30b77fe661.png)

Can you investigate this issue.

**Comment by MagicMarvMan** [comment] 2018-03-30 13:56
**Atom probably did not install the required software or had no rights to install it during installation.
Did you install NodeJS?
When did you install Atom?
Has this error ever occurred?

Without further information you can not be helped.**

**Comment by Arcanemagus** [comment] 2018-03-30 16:01
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/16892. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-30 16:01 UTC
