### ISSUE TITLE
White-cursor gone in 1.26.0

### ISSUE THREAD

**Issue by Shu-Wan** [atom/atom#17174] opened 2018-04-19 10:26 UTC
*Edit by @rsese to add template info*

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

As of 1.26, the I-bar cursor is no longer white with a dark syntax theme, the cursor is black.

x-ref: https://github.com/atom/atom/issues/1654, https://github.com/atom/atom/pull/8663

### Steps to Reproduce

As of 1.26:

1. `atom --safe`
2. Set the syntax theme to `One Dark`
3. Observe the I-bar cursor

**Expected behavior:** [What you expect to happen]

Because of https://github.com/atom/atom/pull/8663, expect the I-bar cursor to be white.

**Actual behavior:** [What actually happens]

The I-bar cursor is black.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
$ atom -v
Atom    : 1.28.0-dev-deeed0667
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

macOS 10.12.6

### Additional Information

No screenshots since the cursor doesn't seem to show up on screenshots? 📷 

---

After updated to 1.26.0, cursor in dark theme becomes black again. It makes very hard to track cursor in the dark mode. 

Referencing #8663 and #1654

**Comment by rsese** [comment] 2018-04-19 18:52
Thanks for the report - I can confirm that on 1.25.1 on macOS 10.12.6 the I-bar is white in safe mode with One Dark syntax theme but on 1.26.0-beta2, the I-bar is black.

/cc @simurai?  🎨

Also @Shu-Wan, for future issues please fill out the issue template - the information in the template is super helpful for us when triaging issues.

**Comment by halorium** [comment] 2018-04-19 21:04
I am turning off auto updates. Yeah, dark cursor on dark theme is rough. Is there a temporary fix for this?

**Comment by Shu-Wan** [comment] 2018-04-20 02:28
@rsese Thanks for the editing and your quick attention! My bad not filling up the template.
-------
My workaround right now is to switch to a light theme. If you are a die-hard dark theme user, don't update to 1.26.0 now.

**Comment by vpiskunov** [comment] 2018-04-20 11:51
Same here observed @ 1.26.0, my eyes are dying 🚨😡

**Comment by halorium** [comment] 2018-04-20 16:06
I had to switch to a light theme which also is not ideal but at least I can see the cursor. I also noticed that when I open atom from the terminal, the first time it always opens with the folder side bar not showing. This latest update was buggy.

**Comment by vpiskunov** [comment] 2018-04-20 16:12
Temporary fix I did:
Add this:
`.editor {`
`  cursor: default;`
`}`
to your `.atom/styles.less`

**Comment by bsg62** [comment] 2018-04-21 12:54
## Another temporary solution

If you don't like the default cursor as workaround, you can add the following code to your `styles.less`:

~~~ less
@ibeam-1x: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAL0lEQVQoz2NgCD3x//9/BhBYBWdhgFVAiVW4JBFKGIa4AqD0//9D3pt4I4tAdAMAHTQ/j5Zom30AAAAASUVORK5CYII=');
@ibeam-2x: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAz0lEQVRIx2NgYGBY/R8I/vx5eelX3n82IJ9FxGf6tksvf/8FiTMQAcAGQMDvSwu09abffY8QYSAScNk45G198eX//yev73/4///701eh//kZSARckrNBRvz//+8+6ZohwCzjGNjdgQxkAg7B9WADeBjIBqtJCbhRA0YNoIkBSNmaPEMoNmA0FkYNoFKhapJ6FGyAH3nauaSmPfwI0v/3OukVi0CIZ+F25KrtYcx/CTIy0e+rC7R1Z4KMICVTQQ14feVXIbR695u14+Ir4gwAAD49E54wc1kWAAAAAElFTkSuQmCC');

.editor {
  cursor: -webkit-image-set(@ibeam-1x 1x, @ibeam-2x 2x) 5 8, text;
}
~~~

It's copied from the original pull request in #8663 and restores the white cursor.

**Comment by MohammedEssehemy** [comment] 2018-04-22 10:09
@bsg62 this works. Thanks

**Comment by simurai** [comment] 2018-04-24 03:40
Looks like the `dppx` unit stopped working in a `-webkit-image-set`.

@bsg62's solution to switch to `1x/2x` is now part of PR #17208. 👍

**Closed** 2018-04-24 06:56 UTC
Labels: regression, ui
