### ISSUE TITLE
vertical scroll bars do not work when clicked at the right most pixel column of the editor window

### ISSUE THREAD

**Issue by derMart** [atom/atom#16870] opened 2018-03-01 21:46 UTC
### Steps to Reproduce

1. Open a file in atom.io which is longer than the window to show vertical scroll bars in Windows 7 or Linux
2. Maximize the atom.io window
3. Try to scroll by moving the mouse to the rightmost pixel column of your screen and click -> move the mouse vertically

**Expected behavior:**
The scroll bar should activate and scroll the editor window

**Actual behavior:**
Nothing happens.
(It is quite inconvenient to always move the mouse a few pixels to the left of the border of the screen to activate scrolling)

**Reproduces how often:**
always

### Versions
1.24.0

**Comment by rsese** [comment] 2018-03-01 22:43
Thanks for contributing!

This is a duplicate of https://github.com/atom/atom/issues/14803 and is fixed in the 1.25 beta.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-01 22:43 UTC
