### ISSUE TITLE
Editing Issues on some files

### ISSUE THREAD

**Issue by edgarasf123** [atom/atom#8818] opened 2015-09-17 01:11 UTC
Getting weird editing issues when I try to edit some files.
![](https://copy.com/M0QKWabX6aHy/2015-09-16_18-09-16.gif)
Copying won't work properly, and editor cursor has an offset from mouse cursor .

[File](https://copy.com/CfvNTULiBbzx/nobile.txt) which is being edited.

**Comment by edgarasf123** [comment] 2015-09-25 06:31
I'm guessing its something wrong with a parser.

**Comment by mnquintana** [comment] 2015-09-25 14:06
Can you reproduce this after quitting Atom completely and restarting it in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? (`atom --safe`)

**Comment by edgarasf123** [comment] 2015-09-25 21:48
Hmm, the offset of mouse cursor is now gone, probably something else triggered it. 

But copying/paste issues are still there, even in the safe mode.
![](https://copy.com/NS694UGM7ft9/2015-09-25_14-47-25.gif)

**Comment by edgarasf123** [comment] 2016-04-12 09:08
I forgot to mention, it only happens when you edit that specific file. It works fine with any other files.

**Comment by edgarasf123** [comment] 2016-04-12 09:19
It looks like the file is encoded in `UCS-2 BOM` encoding. Which notepad++ does support it.
![](https://dl.dropboxusercontent.com/u/8081284/ShareX/2016/04/notepad%2B%2B_2016-04-12_02-17-16.png)

I've also made a smaller version of the file. https://dl.dropboxusercontent.com/u/8081284/ShareX/2016/04/weird_file.txt

Hex Dump:
```
file name: weird_file.txt

0000-0010:  ff fe 48 00-65 00 6c 00-6c 00 6f 00-20 00 57 00  ..H.e.l. l.o...W.
0000-001a:  6f 00 72 00-6c 00 64 00-21 00                    o.r.l.d. !.
```

**Comment by Ben3eeE** [comment] 2016-04-12 12:35
I can copy the text in weird_file.txt without error if I change encoding in atom first, without changing encoding I experience the same problems.
To change encoding in atom do the following:
ctrl-shift-u and select "Auto detect" or preferred encoding. Alternatively execute "Encoding Selector: Show" from the command palette and select encoding.

Atom has many open issues about how it handles encoding. https://github.com/atom/atom/issues/11255 mentions some of them.

**Comment by edgarasf123** [comment] 2016-04-12 13:11
Yeah, it should have an option inside the settings to auto detect encoding once file is opened. And maybe turned on by default.
It shouldn't be that hard to implement since the "Auto Detect" feature is already there.

**Comment by edgarasf123** [comment] 2016-04-12 13:29
Also because of the encoding, it seems the text have null bytes between each character, which probably caused the issues with copying and paste. Displaying control characters which are not used by current encoding mode would also have helped.

https://github.com/atom/atom/issues/1839

**Comment by lee-dohm** [comment] 2016-07-12 21:55
I'm going to close this as a duplicate of #1839, since it seems that is what is being requested here.

**Closed by lee-dohm** 2016-07-12 21:55 UTC
Labels: more-information-needed
