### ISSUE TITLE
Merging tabs after splitting panes results in editor crash

### ISSUE THREAD

**Issue by tobypinder** [atom/atom#10301] opened 2016-01-06 09:35 UTC
When merging tabs back into each other after opening the same file twice, the editor becomes non-responsive and has to be closed.

**Reproduction Steps:**
1. Open file.
2. Right click file tab -> Split Right
3. Add a character to one of the two panes, making the file modified. Don't save.
4. Drag right tab on top of left tab.

**Expected behavior:**

Right tab disappears, as the file doesn't need to be open twice.

**Observed behavior:**

Most of the time, the editor will lock up, become unresponsive then present the error dialog allowing me to close it some seconds later.

**Atom version:** 1.3.0
**OS and version:** Linux Mint 17.2

**Installed packages:**

(via `apm list`
/home/toby/.atom/packages (16)
├── coverage@0.6.1
├── file-icons@1.6.13
├── highlight-selected@0.11.1
├── language-haml@0.23.14
├── linter@1.11.3
├── linter-coffeelint@1.1.2
├── linter-haml@1.1.0
├── linter-jshint@1.2.2
├── linter-rubocop@0.4.7
├── linter-ruby@1.2.1
├── merge-conflicts@1.3.7
├── rubocop-auto-correct@1.1.0
├── sync-settings@0.6.0
├── synced-sidebar@0.4.3
├── tasks@2.6.0
└── todo-show@1.3.0

**Other info**
As this is a pane related bug, it may be worth noting that I have the **Destroy empty panes** option **disabled**, although the bug manifests when you have multiple files in each pane open so I can't really imagine it's related to pane destruction (or lack thereof).

**Comments:**

This happens about 80% of the time, other times nothing seems to happen and the right hand tab doesn't disappear (this could be me simply dragging the tab across wrong, haven't had time to exhaustively investigate.

I understand this is a fairly bizarre thing to do in isolation but if you use the split X commands without keeping a close eye on what's open you can naturally end up with multiple copies of the same file open. And then when you intend to "rebalance" what's in each pane you end up performing this and having to reset Atom.

Happy to provide more information if needed, and thanks for reading.

**Comment by pedro-couto** [comment] 2016-01-06 14:17
:+1: This happens the same to me.

One solution proposal would be that after looking up for a file that is already open, it would simply open the tab instead of opening a new tab for the same file. I end up always closing one of them.

**Comment by tobypinder** [comment] 2016-01-06 16:34
I would agree with that proposal. When `right-file` is dragged over `left_file`, my expectation is that it would delete the tab I dragged across and switch focus to the `left_file`, conceptually "merging" the two.

**Comment by morganick** [comment] 2016-01-07 15:27
This happens in OS X as well. Just dragging any tab for a file that is already open in the destination panel causes Atom to lock up. (Doesn't have to be modified either.)

Should just remove that tab from the source panel and focus the tab of that file in the destination panel.

**Comment by mnquintana** [comment] 2016-01-07 16:40
This looks like a duplicate of https://github.com/atom/atom/issues/10109 – this has been fixed for the 1.4 betas, so I'm going to close this out.

**Closed by mnquintana** 2016-01-07 16:40 UTC
Labels: linux, needs-reproduction
