### ISSUE TITLE
Crashes when opening large minified files

### ISSUE THREAD

**Issue by ChrisChiera** [atom/atom#7939] opened 2015-07-16 21:22 UTC
When opening a minified bootstrap javascript file in Sublime or brackets it opens instantly without a problem. And even dreamweaver opens without a problem albeit taking a few extra seconds.

In Atom, on a iMac 5K with 32GB, it opens in about 4 or so seconds but the app becomes unresponsive. In about 10 seconds it asks if you want to close the app or continue since it's not responding.

It seems there have been many issues relating to this all converging on https://github.com/atom/atom/issues/979. That issue says open, but it's closed to the public now, and the last comment was that it should all be resolved in version 1 (which it appears it was not). So opening a new ticket since unable to add a comment to that issue so that users can continue to comment on issues relating to opening large files that Atom has deemed resolved as of 1.0.

Sample bootstrap javascript minified file: https://cl.ly/code/0X34221f2K2R

**Comment by mnquintana** [comment] 2015-07-16 21:30
This is a duplicate of https://github.com/atom/atom/issues/979 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-16 21:30 UTC

**Comment by ChrisChiera** [comment] 2015-07-16 21:34
Right, however as mentioned in my issue I linked to that exact other issue, and noted the reason for opening this one, is that other issue says the issue it seems will be resolved as of version 1.0 but we are now past 1.0 and it still continues on. So I think we need a place to discuss this issue since it continues or Atom needs to update that other thread clarifying that they are aware it is still a known issue past version 1.0.

**Comment by mnquintana** [comment] 2015-07-16 21:45
@ChrisChiera Thanks for that update! However, the reason that issue was locked was because leaving it open was *detracting* from the issue at hand rather than adding anything of value. Take a look at the last several comments for yourself – they are essentially mostly +1s or "me too!"s, which aren't really helpful. The core team is aware that it's still an issue, and adding more comments to the effect of "+1" or "me too" isn't going to make it happen any faster, if that makes sense. Hopefully someone from the core team will post an official update in that issue sometime next week.

It's also worth noting that this issue is *not* deemed "resolved," as it's still an open issue, and the label has been updated to reflect that it's now on the `post-1.0-roadmap`.
