### ISSUE TITLE
Thunderbolt issues after connect/disconnect from Mac

### ISSUE THREAD

**Issue by FrenchBen** [atom/atom#9458] opened 2015-11-05 19:37 UTC
Issue:
- Font/UI is blurry when atom is open onto a Thunderbolt screen
- Atom editor window truncated after reconnect to Thunderbolt screen

Steps to repeat:
1. Connect your Mac to a Thunderbolt display
2. Open Atom in your Thunderbolt display
3. Open a project to have files in your project manager and multiple files open
4. With Atom still open, disconnect your Thunderbolt display
5. Notice that on your Mac your Atom editor has all blurry fonts (If you close and re-open Atom, then all fonts are now clean/sharp again.)
6. Reconnect your Thunderbolt display and notice that your 'larger' Atom editor now has some odd white truncation until the window is resized.

**Comment by 50Wliu** [comment] 2015-11-05 20:50
Duplicate of #9226 - please subscribe there for updates.

**Closed by 50Wliu** 2015-11-05 20:50 UTC
