### ISSUE TITLE
"Add Project Folder" doesn't open when no window present on OS X

### ISSUE THREAD

**Issue by tarciosaraiva** [atom/atom#10597] opened 2016-01-26 21:07 UTC
Steps to reproduce

1. Open Atom
2. If you have any windows open, close them without quitting the application
3. Go to menu File > Add Project Folder
4. Nothing happens
5. Create a new window from menu File > New Window
6. Go to menu File > Add Project Folder
7. Folder picker opens

More annoying than anything. I still can go Cmd + O and open folder I need.

**Comment by mnquintana** [comment] 2016-01-26 21:15
Thanks for the report! :smile:  This looks like a duplicate of https://github.com/atom/atom/issues/6995 – feel free to subscribe there for updates.

Also, please take a look at [the Contributing guide for a guide on reporting bugs](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs), including searching for duplicates first.

**Closed by mnquintana** 2016-01-26 21:15 UTC
