### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by thegoodfellas** [atom/atom#16970] opened 2018-03-17 06:36 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Neeral\AppData\Local\atom\app-1.25.0\resources\app\node_modules\text-buffer\lib\screen-line-builder.js:329

TypeError: Cannot read property 'length' of undefined
    at ScreenLineBuilder.emitText (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:329:30)
    at ScreenLineBuilder.buildScreenLines (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/screen-line-builder.js:141:22)
    at DisplayLayer.getScreenLines (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/display-layer.js:643:41)
    at TextEditorComponent.queryScreenLinesToRender (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:870:57)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:377:16)
    at TextEditorComponent.screenPositionForPixelPosition (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:2392:18)
    at TextEditorComponent.screenPositionForMouseEvent (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:1964:23)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.25.0/resources/app/src/text-editor-component.js:1763:39)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.6 
qolor 0.4.1 
```

**Comment by rsese** [comment] 2018-03-19 19:24
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16892 so you can subscribe there for updates if you'd like.  If you remember what you were doing at the time of the error or if you can reproduce, please let us know in https://github.com/atom/atom/issues/16892.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-19 19:24 UTC
