### ISSUE TITLE
If Atom is open but no window is open, the Apple taskbar options do not work

### ISSUE THREAD

**Issue by elliottmangham** [atom/atom#12955] opened 2016-10-12 09:08 UTC
Hello,

When Atom is running but I do not have a window open, the options in the top Apple task-bar (New Window, New File, Open...etc) do not work.

As a temporary solution, I have to click on the Atom icon in the dock to open a window before any of those options work. This issue is on multiple computers which leads me to believe it is not a local issue.

Kind regards

**Comment by Ben3eeE** [comment] 2016-10-12 09:35
This is a duplicate of https://github.com/atom/atom/issues/12508. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-12 09:35 UTC
