### ISSUE TITLE
Corrupted blob-store (SyntaxError: Unexpected end of input)

### ISSUE THREAD

**Issue by Razum** [atom/atom#10015] opened 2015-12-11 12:15 UTC
Hi Guys.
**OS**: Ubuntu 14.04
**Atom version:** 1.3.0
**Reproducable in safe mode**

After upgrading Atom to 1.3.0 version it has started crashing and throwing the following error on start from command line:

![Error img](http://i.imgur.com/8bcvN6N.png) 

```javascript
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at FileSystemBlobStore.load (/opt/atom/resources/app.asar/src/file-system-blob-store.js:31:31)
    at Function.load (/opt/atom/resources/app.asar/src/file-system-blob-store.js:10:14)
    at window.onload (file:///opt/atom/resources/app.asar/static/index.js:18:39)

handleSetupError @ index.js:61
```

**Config:**

```
"*":
  welcome:
    showOnStartup: false
  core: {}
  editor:
    invisibles: {}
  jshint:
    supportLintingJsx: true
    harmony: true
    esnext: true
  "atom-beautify":
    _analyticsUserId: "bc2b80b6-ea35-44a1-a6d5-4d7c7f1f78a3"
    js_end_with_newline: true
    js_keep_array_indentation: true
    js_keep_function_indentation: true
    js_space_after_anon_function: true
  "one-light-ui": {}
  jsformat: {}

```
**Installed packages:**
```
/home/roman/.atom/packages (10)
├── atom-beautify@0.28.19
├── autocomplete-paths@1.0.2
├── color-picker@2.0.14
├── file-icons@1.6.13
├── highlight-selected@0.11.1
├── jshint@1.8.3
├── linter@1.11.3
├── linter-csslint@1.1.0
├── pigments@0.19.2
└── react@0.12.10

```

**Comment by as-cii** [comment] 2015-12-11 13:59
Hey @Razum, sorry this is causing issues to you! Does deleting the `~/.atom/blob-store` folder solve the issue?

Also, do you happen to know when this started appearing? Right after the upgrade?

Thanks!

**Comment by Razum** [comment] 2015-12-11 15:05
Yeah, Removing ~/.atom/blob-store folder did the trick. Thank you so much!

Atom update came with the other Ubuntu updates. And as soon as I installed it it started crushing.

**Comment by calebmer** [comment] 2016-01-02 15:29
I also got this error on OSX 10.11.2 and Atom 1.3.2

This error was also resolved be deleting `~/.atom/blob-store`.

**Comment by as-cii** [comment] 2016-01-05 09:09
Seems like the file is being corrupted somehow, probably by a concurrency issue. Theoretically, we have a LOCK file that should prevent this sort of problems, so this may have been caused by some other sort of race condition.

I would :heart: to have a look at the corrupted files within the `blob-store` directory: can you post the content of those files in a gist or something? Reopening this as it seems like it's still a problem.

Even if we track down the cause of the problem, it seems reasonable to avoid crashing when parsing an invalid blob store.

**Comment by calebmer** [comment] 2016-01-05 13:04
I'm sorry, I saw another person had posted their invalid files in another PR (#10047) and there was no other indication it was wanted so I just rm'd mine 😐

**Comment by acejam** [comment] 2016-01-08 20:08
This just occurred on my El Capitan machine running 1.3.2. Removing the `~/.atom/blob-store` folder did the trick.

**Comment by vinkla** [comment] 2016-01-19 07:00
Had the same issue as @acejam above running `1.4.0` and solved it by removing the `blob-store` folder.

**Comment by EricMCornelius** [comment] 2016-01-21 15:09
Just saw the same on my Ubuntu 15.04 system after an upgrade to 1.4.0.

**Comment by BlaM** [comment] 2016-01-22 09:35
Same problem just occured here on Windows 8.1 - so it does not seem to be an OS related issue.

Not sure when the last update happened, but I have restarted Atom several times since the update (I'm sure I was on 1.4.0 on my last work day) and it stopped working today (computer has been restarted since then).

Do you still want to see the broken files? I recovered them from my "Recycle Bin" ;)

**Comment by joshaber** [comment] 2016-01-22 18:45
The fix was just merged. It'll be out in 1.4.1.

**Closed by joshaber** 2016-01-22 18:45 UTC
Labels: bug
