### ISSUE TITLE
Uncaught Error: Cannot call function 'emit' on missing remote object 226Error: Cannot call funct...

### ISSUE THREAD

**Issue by Hnailu** [atom/atom#18985] opened 2019-03-14 02:57 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'emit' on missing remote object 226
Error: Cannot call function 'emit' on missing remote object 226
    at throwRPCError (C:\Users\Kid\AppData\Local\atom\app-1.35.1\resources\electron.asar\browser\rpc-server.js:143:17)
    at EventEmitter.<anonymous> (C:\Users\Kid\AppData\Local\atom\app-1.35.1\resources\electron.asar\browser\rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\Kid\AppData\Local\atom\app-1.35.1\resources\electron.asar\browser\api\web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

```
At C:\Users\Kid\AppData\Local\atom\app-1.35.1\resources\electron.asar\renderer\api\remote.js:221

Error: Cannot call function 'emit' on missing remote object 226
Error: Cannot call function 'emit' on missing remote object 226
    at throwRPCError (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/browser/api/web-contents.js:296:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

    at Object.exception (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:221:30)
    at metaToValue (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:225:28)
    at Object.remoteMemberFunction (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/renderer/api/remote.js:125:16)
    at ContextMenuManager.t.exports.ContextMenuManager.showForEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:401003)
    at WindowEventHandler.handleDocumentContextmenu (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:287773)
```

### Commands

```
     -4:15.6.0 core:paste (input.hidden-input)
     -4:14.9.0 core:move-right (input.hidden-input)
     -4:14.1.0 core:save (input.hidden-input)
     -3:37.3.0 core:copy (input.hidden-input)
     -3:36.5.0 editor:newline (input.hidden-input)
     -3:35.3.0 core:paste (input.hidden-input)
     -3:35.1.0 core:move-right (input.hidden-input)
     -3:33.7.0 core:save (input.hidden-input)
     -0:39.4.0 editor:newline (input.hidden-input)
     -0:38.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:35.1.0 core:paste (input.hidden-input)
     -0:34.9.0 core:move-right (input.hidden-input)
  2x -0:33.6.0 core:backspace (input.hidden-input)
     -0:31 editor:move-to-end-of-word (input.hidden-input)
     -0:30.1.0 core:move-right (input.hidden-input)
     -0:29.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
file-icons 2.1.30 
ide-php 0.7.18 
pretty-json 2.0.3 
```

**Comment by rsese** [comment] 2019-03-14 17:42
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade). 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-03-14 17:42 UTC
