### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/nickselimis/Library/Application ...

### ISSUE THREAD

**Issue by nselimis** [atom/atom#11204] opened 2016-03-18 19:45 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:272:24)
    at toRealPath (module.js:109:13)
    at Function.Module._findPath (module.js:149:20)
    at Module._resolveFilename (module.js:334:25)
    at Function.Module._resolveFilename (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Tokenizer.js:3:23)
    at Module._compile (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/Parser.js:1:96)
    at Module._compile (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/htmlparser2/lib/index.js:1:93)
    at Module._compile (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/lib/parse.js:4:18)
    at Module._compile (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/nickselimis/Library/Application Support/com.github.atom.ShipIt/update.mUWm5bD/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
```

### Commands

```
     -0:11.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.2.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:09.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "monokai"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2016-03-23 10:58
Duplicate of https://github.com/atom/atom/issues/9559 ?

**Comment by 50Wliu** [comment] 2016-03-28 17:33
Yep, thanks @Ben3eeE!

**Closed by 50Wliu** 2016-03-28 17:33 UTC
