### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isGreaterThan' of null

### ISSUE THREAD

**Issue by abe33** [atom/atom#13489] opened 2016-12-22 09:10 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When on the first column of an empty line, trying to increment the indentation through the `editor:indent` will raise an exception instead of increasing the indentation. This does not occurs when the cursor is no longer at the beginning of the line nor when the line is not empty.

### Steps to Reproduce

1. Place the cursor at the beginning of an empty line
2. Trigger the `editor:indent` command

**Expected behavior:** [What you expect to happen]

The line should have been indented and the cursor moved to the new position

**Actual behavior:** [What actually happens]

An uncaught exception is raised.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
> atom --version
Atom    : 1.14.0-dev-2958ad2
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

> apm --version
apm  1.15.1
npm  3.10.5
node 4.4.5 x64
python 2.7.11
git 2.10.1
```

### Stack Trace

`Uncaught TypeError: Cannot read property 'isGreaterThan' of null`

<details>

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:825

TypeError: Cannot read property 'isGreaterThan' of null
    at Cursor.module.exports.Cursor.skipLeadingWhitespace (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:406:33)
    at Selection.module.exports.Selection.indent (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:785:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2807:26
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1130:28
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:820:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1547:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1124:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2521:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2487:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1122:19)
    at TextEditor.module.exports.TextEditor.indent (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2806:19)
    at TextEditor.editor:indent (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:594:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:666:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:820:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1547:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:665:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

</details>

### Commands

<details>

```
     -0:24.6.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:24.4.0 core:backspace (input.hidden-input)
     -0:24.1.0 core:save (input.hidden-input)
     -0:04.8.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:04.3.0 docblockr:parse-tab (input.hidden-input)
     -0:04.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:04.3.0 snippets:expand (input.hidden-input)
     -0:04.3.0 editor:indent (input.hidden-input)
     -0:02.5.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:01.9.0 editor:consolidate-selections (input.hidden-input)
     -0:01.9.0 core:cancel (input.hidden-input)
     -0:00.8.0 core:save (input.hidden-input)
     -0:00.1.0 docblockr:parse-tab (input.hidden-input)
     -0:00.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:00.1.0 snippets:expand (input.hidden-input)
     -0:00.1.0 editor:indent (input.hidden-input)
```

</details>

### Config

<details>

```json
{
  "core": {
    "audioBeep": false,
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ruby.rails": [
        "rb"
      ]
    },
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "minimap-symbols",
      "preview-tabs",
      "crosshairs",
      "coffee-compile",
      "enhanced-package-list",
      "themed-settings",
      "smart-tag-cycle",
      "tree-view-open-files",
      "typewriter",
      "travis-ci-status",
      "linter-eslint"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "spacegray-dark-neue-syntax"
    ],
    "useCustomTitleBar": true
  },
  "editor": {
    "autoIndentOnPaste": false,
    "fontFamily": "Monoid",
    "fontSize": 13,
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true
  }
}
```

</details>

### Installed Packages

<details>

```coffee
# User
atom-eco, v0.2.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-ternjs, v0.16.1 (inactive)
bezier-curve-editor, v0.7.2 (active)
caniuse, v0.9.0 (active)
clipboard-plus, v0.5.1 (active)
docblockr, v0.9.1 (active)
duotone-dark-forest-syntax, v2.0.1 (inactive)
duotone-dark-space-syntax, v2.0.1 (inactive)
expose, v0.12.2 (inactive)
figlet, v0.5.4 (active)
github, v0.0.0 (active)
highlight-selected, v0.11.2 (active)
indent-tooltip, v0.2.1 (inactive)
kite, v0.6.1 (active)
language-ejs, v0.4.0 (active)
language-generic-config, v1.3.0 (active)
language-haml, v0.24.1 (active)
language-jade, v0.7.2 (active)
language-sass, v0.57.1 (active)
linter, v1.11.21 (active)
linter-eslint, v8.0.0 (inactive)
linter-js-standard, v3.7.0 (active)
minimap, v4.26.5 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-codeglance, v0.4.5 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
minimap-pigments, v0.2.2 (active)
minimap-selection, v4.4.0 (active)
php-twig, v4.0.0 (active)
pigments, v0.38.0 (active)
process-palette, v0.9.1 (active)
project-palette-finder, vundefined (active)
red-wavy-underline, v0.3.2 (active)
solarized-dark-ui, v0.3.1 (inactive)
sort-lines, v0.14.0 (inactive)
spacegray-dark-neue-syntax, v1.3.0 (active)
spacegray-dark-ui, v0.12.0 (inactive)
Stylus, v3.1.0 (active)
tablr, v1.8.0 (active)
tabs-to-spaces, v1.0.2 (active)
toggle-quotes, v1.0.0 (inactive)
travis-ci-status, v1.3.0 (inactive)
tree-view-breadcrumb, v0.8.1 (active)
tree-view-open-files, v0.3.0 (inactive)
typewriter, v0.4.0 (inactive)
unfancy-file-icons, v0.10.0 (active)
white-cursor, v0.7.0 (active)
Zen, v0.16.4 (inactive)
zentabs, v0.8.7 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.9.0 (active)
one-light-ui, v1.9.0 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.2 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.34.2 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.24.0 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.4 (active)
bracket-matcher, v0.85.2 (active)
command-palette, v0.39.2 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.1 (active)
find-and-replace, v0.204.8 (inactive)
fuzzy-finder, v1.4.1 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.2 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.70.0 (active)
status-bar, v1.7.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.2 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.2 (active)
whitespace, v0.36.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.2 (active)
language-csharp, v0.13.0 (active)
language-css, v0.41.0 (active)
language-gfm, v0.88.0 (active)
language-git, v0.19.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.124.0 (active)
language-json, v0.18.3 (active)
language-less, v0.30.0 (active)
language-make, v0.22.3 (active)
language-mustache, v0.13.1 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.9.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.3 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.1 (active)
language-shellscript, v0.24.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.13 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

</details>

**Comment by 50Wliu** [comment] 2016-12-22 17:43
@nathansobo

**Comment by nathansobo** [comment] 2016-12-24 00:16
I've added the `regression` label to this. We should get in the habit of adding this label for bugs like this so we can make sure not to release to the next channel.

**Comment by maxbrunsfeld** [comment] 2016-12-26 20:18
Looks like another issue with empty matches in `scanInRange`. I'll look into this when I get back.

**Comment by smashwilson** [comment] 2016-12-28 15:28
@maxbrunsfeld Oh, whoops - this was bugging me so I took a stab at it in atom/text-buffer#190.

**Comment by maxbrunsfeld** [comment] 2016-12-29 00:41
Fixed via https://github.com/atom/text-buffer/pull/190.

**Closed by maxbrunsfeld** 2016-12-29 00:41 UTC
Labels: bug, regression, triaged, uncaught-exception
