### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/Downloads/Atom.app/Contents/Resources/...

### ISSUE THREAD

**Issue by gusplayer** [atom/atom#14910] opened 2017-06-28 14:58 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less'

```
At /Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/src/theme-manager.js:323

Error: ENOENT: no such file or directory, open '/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/Users/fosterapps/Downloads/Atom.app/Contents/Resources/app/node_modules/tree-view/styles/tree-view.less'
  at Error (native)
  at Object.fs.openSync (fs.js:640:18)
  at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
  at Proxy.fs.readFileSync (fs.js:508:33)
  at Proxy.fs.readFileSync (ELECTRON_ASAR.js:501:29)
  at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (<embedded>:21053:56)
  at ThemeManager.module.exports.ThemeManager.loadStylesheet (<embedded>:21025:27)
  at <embedded>:69408:60
  at Array.map (native)
  at Package.module.exports.Package.loadStylesheets (<embedded>:69406:65)
  at <embedded>:69000:23
  at Package.module.exports.Package.measure (<embedded>:68962:21)
  at Package.module.exports.Package.finishLoading (<embedded>:68996:25)
  at PackageManager.module.exports.PackageManager.loadAvailablePackage (<embedded>:20410:38)
  at PackageManager.module.exports.PackageManager.loadPackage (<embedded>:20384:27)
  at PackageManager.module.exports.PackageManager.enablePackage (<embedded>:20075:25)
  at HTMLButtonElement.enablementButtonClickHandler (<embedded>:180768:31)

```

### Commands

```
     -2:11 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-fusion-syntax.theme-one-dark-ui)
     -1:45.8.0 settings-view:open (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-dark-fusion-syntax 2.2.0 
file-icons 2.1.7 
language-babel 2.66.0 
nuclide 0.232.0 
pigments 0.39.1 
```

**Comment by rsese** [comment] 2017-06-28 17:27
Closing as a duplicate of https://github.com/atom/atom/issues/14500 - can you confirm if tree-view is listed in the`disabledPackages` of your config.cson file @gusplayer and if you have Nuclide enabled?

**Closed by rsese** 2017-06-28 17:27 UTC
