### ISSUE TITLE
Uncaught Error: Requested measurement of a line that is not currently rendered

### ISSUE THREAD

**Issue by zhuangyin8** [atom/atom#15029] opened 2017-07-15 11:37 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta4 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At C:\Users\zhuan_f\AppData\Local\atom\app-1.19.0-beta4\resources\app\src\text-editor-component.js:2153

Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/text-editor-component.js:2151:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/text-editor-component.js:2144:45)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/text-editor-component.js:380:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/text-editor-component.js:264:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.0-beta4/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -2:53.7.0 editor:newline (input.hidden-input)
  2x -2:52.3.0 core:backspace (input.hidden-input)
     -1:51 markdown-writer:insert-new-line (input.hidden-input)
     -1:51 editor:newline (input.hidden-input)
     -1:50.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:50.8.0 editor:newline (input.hidden-input)
 16x -1:48.8.0 core:backspace (input.hidden-input)
     -1:27.6.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:27.6.0 editor:newline (input.hidden-input)
     -1:27.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:27.4.0 editor:newline (input.hidden-input)
     -1:21.7.0 core:backspace (input.hidden-input)
     -1:05.9.0 core:save (input.hidden-input)
  2x -0:47.2.0 core:move-down (input.hidden-input)
  2x -0:46.3.0 core:move-up (input.hidden-input)
     -0:40.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-html-preview 0.1.22 
atom-monokai 0.10.9 
atom-panda-syntax 0.18.0 
browser-plus 0.0.98 
emmet 2.4.3 
file-icons 2.1.8 
markdown-image-assistant 0.2.0 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.6.5 
open-in-browsers 0.0.30 
pigments 0.39.1 
pure-syntax 0.2.1 
```

**Comment by rsese** [comment] 2017-07-18 08:08
Thanks for the report!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14834. You may want to subscribe there for updates and if you have steps to reproduce in safe mode (`atom --safe`), feel free to share that in the issue.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-07-18 08:08 UTC
