### ISSUE TITLE
atom editor get closed when i drag and drop the image from firefox browser

### ISSUE THREAD

**Issue by shivarajnaidu** [atom/atom#8075] opened 2015-07-25 13:05 UTC
<b>I'm using Atom 1.0 stable on Ubuntu 14.04</b>
here is my system info:
<pre>
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
</pre>
Accidentally ,
Once I drag  and drop  the image  in atom editor  from firefox browser.. after drop the image the atom editor get closed automaticaally.. i didn't notice whether  my files are lost or not..

<pre><b><em>
you can reproduce the same by drag and drop the image from firefox browser into atom editor.</em></b>
</pre>

**Comment by mnquintana** [comment] 2015-07-25 13:12
This looks like a duplicate of https://github.com/atom/atom/issues/3593 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-25 13:12 UTC
