### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by victorFSL** [atom/atom#14493] opened 2017-05-18 22:47 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at undefined.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:663:1)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:697:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:184:1)
    at /Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1
```

### Commands

```
  2x -9:47.9.0 core:backspace (input.hidden-input)
     -9:43.3.0 core:copy (input.hidden-input)
     -9:40.8.0 core:paste (input.hidden-input)
     -9:40.1.0 core:save (input.hidden-input)
  2x -8:30 core:backspace (input.hidden-input)
  2x -8:25.3.0 core:save (input.hidden-input)
     -6:18.4.0 core:paste (input.hidden-input)
  2x -6:17.1.0 core:backspace (input.hidden-input)
     -6:12.5.0 core:save (input.hidden-input)
     -0:59.6.0 core:move-left (input.hidden-input)
     -0:59.3.0 core:move-right (input.hidden-input)
     -0:42 core:save (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.2.5 
firacode 0.3.0 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
git-plus 7.8.1 
highlight-selected 0.13.1 
language-slim 0.5.0 
minimap 4.28.2 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
rails-partials 0.9.2 
seti-icons 1.5.0 
```

**Comment by rsese** [comment] 2017-05-18 23:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #11692. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-18 23:16 UTC

**Comment by ungb** [comment] 2017-05-18 23:59
Hi,  I'm currently trying to get a working repro so we can investigate further.   Are you able to provide any info on repro steps? or any more info on what you were doing when you saw this error?
