### ISSUE TITLE
When opening single file the project folder is the file instead of folder above file

### ISSUE THREAD

**Issue by zacps** [atom/atom#9963] opened 2015-12-07 03:43 UTC
### Steps to reproduce:
1. Remove all project folders.
2. Open a file via: Right click open in atom, Open a file dialog in atom, opening file via command line.

### Observed behavior:
Atom shows the project folder as the file that was opened.

### Expected behavior:
Atom selects the folder above the file and uses it as the project folder.

### Example
Opened file ~/path/index.html
Atom shows index.html as the project folder.
Atom should show ~/path as the project folder.

### Environment
Atom 1.2.4 (Latest as of 07/12/2015
Windows 8.1 64bit
Reproduced in safe mode (atom --safe)

**Comment by Ben3eeE** [comment] 2016-08-18 07:05
This sounds like a duplicate of https://github.com/atom/tree-view/issues/471 which has been fixed already.

**Comment by 50Wliu** [comment] 2016-08-18 14:32
Thanks @Ben3eeE.

**Closed by 50Wliu** 2016-08-18 14:33 UTC
Labels: needs-reproduction
