### ISSUE TITLE
Uncaught Error: ENOENT, open 'c:\code\ta\AboveWebrootDirs\AppConfig\Log4NetConfig\sync.server.log4net.config'

### ISSUE THREAD

**Issue by ronrat** [atom/atom#4976] opened 2015-01-10 06:01 UTC
[Enter steps to reproduce below:]

The editor was idle. When I came back to it, this message was displayed.

**Atom Version**: 0.169.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'c:\code\ta\AboveWebrootDirs\AppConfig\Log4NetConfig\sync.server.log4net.config'

```
At c:\Users\rratzlaff\AppData\Local\atom\app-0.169.0\resources\app\node_modules\q\q.js:126

Error: ENOENT, open 'c:\code\ta\AboveWebrootDirs\AppConfig\Log4NetConfig\sync.server.log4net.config'
  at Error (native)

```

### Commands

```
     -1:23.9 application:new-file (atom-text-editor.editor)
     -1:23.3 core:paste (atom-text-editor.editor)
     -1:21.3 core:move-to-top (atom-text-editor.editor)
     -1:19.8 core:save (atom-text-editor.editor)
     -0:02.5 application:new-file (atom-text-editor.editor)
     -0:01.9 core:paste (atom-text-editor.editor)
     -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
autocomplete-plus-async, v0.22.0
color-picker, v1.2.6
language-csharp, v0.3.0
language-mediawiki, v0.1.0
linter, v0.9.1
minimap, v3.5.4
omnisharp-atom, v0.1.6
project-manager, v1.14.1

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment] 2015-01-13 19:45
I believe this is a duplicate of https://github.com/atom/atom/issues/4850 and will be fixed by #4906

**Closed by kevinsawicki** 2015-01-13 19:45 UTC
