### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by bassdeveloper** [atom/atom#12228] opened 2016-07-25 00:07 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: linux 4.6.4-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/remote.js:170

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/usr/share/atom/resources/atom.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/rpc-server.js:318:31)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:170:13)
    at BrowserWindow.remoteMemberFunction [as getPosition] (/usr/share/atom/resources/atom.asar/renderer/api/remote.js:110:18)
    at AtomEnvironment.module.exports.AtomEnvironment.getWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:626:29)
    at AtomEnvironment.module.exports.AtomEnvironment.storeWindowDimensions (/usr/share/atom/resources/app.asar/src/atom-environment.js:660:36)
    at WindowEventHandler.module.exports.WindowEventHandler.handleWindowBlur (/usr/share/atom/resources/app.asar/src/window-event-handler.js:182:35)
    at /usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61
```

### Commands

```
  4x -6:27.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:18.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:16.7.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -6:10.5.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:09.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -6:08.1.0 core:save (atom-text-editor.editor.is-focused)
     -5:30 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -5:28.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:47.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:35.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:35.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:32.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:24.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:23.3.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:07.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "tabLength": 4,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-java, v1.2.5
minimap, v4.24.7
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-pigments, v0.2.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-07-25 02:04
This is a duplicate of #11692 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-25 02:04 UTC
