### ISSUE TITLE
Uncaught Error: EIO: i/o error, open '/Volumes/DEV - My Staff/system/core.php'

### ISSUE THREAD

**Issue by russellharrower** [atom/atom#7126] opened 2015-06-05 16:20 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EIO: i/o error, open '/Volumes/DEV - My Staff/system/core.php'

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:759

Error: EIO: i/o error, open '/Volumes/DEV - My Staff/system/core.php'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at Object.fsPlus.writeFileSync (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:279:17)
    at File.module.exports.File.writeFileSync (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:264:19)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:362:21)
    at File.module.exports.File.writeSync (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:336:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1016:17)
    at TextBuffer.module.exports.TextBuffer.save (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
```

### Commands

```
  2x -1:51.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:50.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:47.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:46.8.0 core:save (atom-text-editor.editor.is-focused)
  4x -1:36.5.0 core:undo (atom-text-editor.editor.is-focused)
     -1:32.6.0 core:move-up (atom-text-editor.editor.is-focused)
 11x -1:32.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:30.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:30.3.0 core:paste (atom-text-editor.editor.is-focused)
     -1:30 core:save (atom-text-editor.editor.is-focused)
     -1:29.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:28.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:54.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:53.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:04.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-06-17 12:33
Thanks for the report, @russellharrower -- this looks like a duplicate of https://github.com/atom/atom/issues/6348, so I'm closing this in favor of that issue.

**Closed by izuzak** 2015-06-17 12:33 UTC
Labels: error-from-open, uncaught-exception
