### ISSUE TITLE
Please add API to disable IME

### ISSUE THREAD

**Issue by hh9527** [atom/atom#10713] opened 2016-02-06 01:13 UTC
I am a Chinese vim user. Input Chinese text in Atom with vim-mode (or vim-mode-plus) is very inconvenient:

When I do some input in `insert-mode` (or `replace-mode`) and back to `normal-mode`, the IME is not disabled automatically, that means all `normal-mode` command can not be used directly, I have to press additional `Ctrl+Space` to disable IME, and when I enter `insert-mode` (or `replace-mode`) again, I have to press `Ctrl+Space` again to input Chinese text.

All I required is: when I am in `normal-mode` IME should be disabled automatically, and when I enter `insert-mode` again, the IME status should be recovered.

I have submitted a issue in vim-mode-plus: https://github.com/t9md/atom-vim-mode-plus/issues/148 , but the author of vim-mode-plus tell me this feature needs atom-core to provide a new API to disable IME.

I have noticed that there is a related issue already (issue #1092) , but it seemed that issue is caused by MacOSX's special feature and has a workaround already. And for my problem, there is no acceptable workaround, so I submitted this issue. 

P.S: VIM has already support automatic IME disabling for many years. This is a very useful feature for document writing in non-western language.

**Comment by lee-dohm** [comment] 2016-02-06 17:26
This is a duplicate of #1092. Please subscribe there for updates.

**Closed by lee-dohm** 2016-02-06 17:26 UTC
Labels: duplicate

**Comment by lee-dohm** [comment] 2016-02-06 17:28
There is a workaround on OS X, yes. But the underlying issue in both cases is that there should be an API to control this, so the resolution is the same for both.
