### ISSUE TITLE
Perl syntax folding bug

### ISSUE THREAD

**Issue by sardior** [atom/atom#18061] opened 2018-09-16 14:18 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Text folding around perl raw block text format does not work properly.
```
foreach $p (keys(%balances)){
	    $fh->open("$p.memo","w");
	    print $fh <<EOF;
To: $p
Re: Your Account Balance

This memo is to inform you that your account balance is currently
$balances{$p}.  Please send your payment as soon as possible.

Thank you.
EOF
}
```
In this example collapsing the foreach method collapses only the next two lines. While tabulating the raw text fixes this problem, the tabulation will appeare in the printed message, and that might be undesirable.
### Steps to Reproduce

1. Continiously present in any perl file using this syntax.

**Expected behavior:** The block of the method/condition collapses properly.

**Actual behavior:** The block collapses to the begining of the raw text.

### Versions
Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by Arcanemagus** [comment] 2018-09-16 19:16
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-perl/issues/54. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-09-16 19:16 UTC
