### ISSUE TITLE
Package resource profiler / "task manager" view

### ISSUE THREAD

**Issue by saizai** [atom/atom#17158] opened 2018-04-17 11:42 UTC
See Chrome's internal task manager for reference.

I would like to have a live window that shows me, per package, its cpu %, marginal memory usage, (separate) process ID(s), cpu time, disk i/o use, & network i/o use.

Ideally I would like the package list to also aggregate these, together with things like # times used / date of last use.

Would be useful for knowing what to blame for my system getting bogged down; what I installed a while ago but never used; etc.

**Comment by rsese** [comment] 2018-04-17 22:43
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/4168 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-04-17 22:43 UTC
