### ISSUE TITLE
Deleting files on linux, gvfs-trash isn't supported anymore?

### ISSUE THREAD

**Issue by WhiteLeash** [atom/atom#16015] opened 2017-10-27 18:46 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I can't delete file, yes I found many issues about it, but I found new one about gio, and probably replacing this will end problem of many people. 

### Steps to Reproduce

1. Searching about gvfs-trash, and repair problem
2. Do test of gvfs in Atom, got standard red banner about "Is gvfs-trash installed?"
3. Do test in shell, but don't work and got report to use >$ gio, works well with >$ gio trash "file"

**Expected behavior:** Find and replace trash package

**Actual behavior:** Still I can't delete file from ATOM
**Reproduces how often:** 100%

### Versions
atom --version
```
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

apm --version
```
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.1
```

### Additional Information
I run atom on ubuntu budgie.

uname -a
````
Linux UltraInstinct 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rsese** [comment] 2017-10-30 17:09
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15949. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-30 17:09 UTC
