### ISSUE TITLE
Uncaught Error: No line exists for row 10. Last screen row: 9

### ISSUE THREAD

**Issue by wonsikin** [atom/atom#5897] opened 2015-03-08 04:25 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: No line exists for row 10. Last screen row: 9

```
At /opt/app/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:385

Error: No line exists for row 10. Last screen row: 9
  at TextEditorPresenter.<anonymous> (/opt/app/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:385:19)
  at TextEditorPresenter.module.exports.TextEditorPresenter.batch (/opt/app/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:91:12)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateLinesState (/opt/app/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:375:19)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/opt/app/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:123:14)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/opt/app/Atom.app/Contents/Resources/app/src/text-editor-component.js:172:38)
  at /opt/app/Atom.app/Contents/Resources/app/src/text-editor-component.js:280:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/opt/app/Atom.app/Contents/Resources/app/src/view-registry.js:159:9)
  at /opt/app/Atom.app/Contents/Resources/app/src/view-registry.js:3:61

```

### Commands

```
  2x -1:54.8 core:move-left (atom-text-editor.editor.is-focused)
     -1:53.6 core:move-right (atom-text-editor.editor.is-focused)
     -1:53.2 core:select-right (atom-text-editor.editor.is-focused)
     -1:51.5 core:backspace (atom-text-editor.editor.is-focused)
     -1:51.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:50.6 core:backspace (atom-text-editor.editor.is-focused)
 23x -1:50.2 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:47.2 core:backspace (atom-text-editor.editor.is-focused)
 44x -1:44.7 core:move-right (atom-text-editor.editor.is-focused)
     -1:38.9 core:backspace (atom-text-editor.editor.is-focused)
     -1:35.9 editor:newline (atom-text-editor.editor.is-focused)
     -1:35.2 core:move-down (atom-text-editor.editor.is-focused)
     -1:34.8 core:move-right (atom-text-editor.editor.is-focused)
 21x -1:34.4 core:select-right (atom-text-editor.editor.is-focused)
     -1:22.8 core:paste (atom-text-editor.editor.is-focused)
     -1:20.4 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet",
      "autocomplete"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
autocomplete-plus, v2.4.0
color-picker, v1.4.4
file-icons, v1.5.0
go-plus, v3.2.3
highlight-line, v0.10.1
linter, v0.12.0
minimap, v4.5.0
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by Moter8** [comment] 2015-03-08 13:29
@wonsikin Please, reporting issues without typing in what you did is not useful. You are supposed to enter steps so people can try to reproduce the bug.
```
[Enter steps to reproduce below:]

...
...
```

Anyway, it's a duplicate of #5667.

**Closed** 2015-03-08 16:19 UTC
