### ISSUE TITLE
Allow overriding "fn" key

### ISSUE THREAD

**Issue by msmaili** [atom/atom#7761] opened 2015-07-07 15:48 UTC
I'm trying to override the Fn key's functionality but no luck.

Here's what I have:
```
'fn-left': 'editor:move-to-beginning-of-screen-line'
```

I've tried various combinations, like `F`, `f`, `Fn` but none of them seem to work.

**Comment by thomasjo** [comment] 2015-07-07 15:54
Duplicate of https://github.com/atom/atom-keymap/issues/54.

**Closed by thomasjo** 2015-07-07 15:54 UTC
