### ISSUE TITLE
character ">" when colon key typed in a portuguese keyboard

### ISSUE THREAD

**Issue by penafo** [atom/atom#11304] opened 2016-03-29 22:45 UTC
Atom latest version installed an hour ago, on a Win 10 64bit with Portuguese layout keyboard

Typing : displays > on code window

Colon punctuation mark in PT keyboards is SHIFT+period

**Comment by 50Wliu** [comment] 2016-03-29 22:48
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-29 22:48 UTC
