### ISSUE TITLE
markdown highlight broken if a code block contains asterisk or underscore

### ISSUE THREAD

**Issue by fedelibre** [atom/atom#6286] opened 2015-04-07 17:01 UTC
As you can see in the attached image, markdown syntax highlighter takes into account the _ and * present in a code block. I think that it should ignore any of these characters if they are within an indented code block.

![atom-markdown-highlight](https://cloud.githubusercontent.com/assets/1644647/7028774/676c14c4-dd58-11e4-95db-0bd2a122ec42.png)

No problem when I use fenced code blocks. But indented blocks are much easier.

I hope that this is the right place to report it.
I'm using Atom 0.189.0

**Comment by 50Wliu** [comment] 2015-04-07 18:11
Looks like a duplicate of atom/language-gfm#44, please subscribe there for updates.

**Closed by 50Wliu** 2015-04-07 18:11 UTC
