### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Desktop\ModelisationBlocOperatoire'

### ISSUE THREAD

**Issue by TheHaricover** [atom/atom#16958] opened 2018-03-16 08:18 UTC
1. Open a project folder
2. Delete it on Windows Explorer
3. Close Atom
4. Reopen it
5. It should work

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Windows 10 Familial (Version 10.0.16299 Number 16299)
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\rochr\Desktop\ModelisationBlocOperatoire'

```
At fs.js:961

Error: ENOENT: no such file or directory, lstat 'C:\Users\rochr\Desktop\ModelisationBlocOperatoire'
    at fs.lstatSync (fs.js:961:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Proxy.realpathSync (fs.js:1641:21)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at atom.project.getPaths.map (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:73)
    at Array.map (native)
    at Object.startTask (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:16:56)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/fuzzy-finder/lib/main.js:109:43)
    at get_process.nextTick (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/fuzzy-finder/lib/main.js:25:45)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-clock 0.1.16 
atom-ide-ui 0.9.4 
atom-python-run 0.9.6 
autocomplete-python 1.10.5 
autocomplete-xml 0.9.4 
autumn-highlighter-syntax 1.13.0 
busy-signal 1.4.3 
highlight-selected 0.13.1 
Hydrogen 2.3.0 
ide-csharp 0.6.2 
intentions 1.1.5 
kite 0.74.0 
linter 2.2.0 
linter-ui-default 1.7.1 
linter-xmllint 1.4.3 
package-switch 0.5.0 
python-tools 0.6.9 
sync-settings 0.8.5 
webbox-color 0.5.9 
xml-formatter 0.11.0 
```

**Comment by rsese** [comment] 2018-03-16 20:04
Thanks for contributing!

Based on the stack trace I'll go ahead and close as a duplicate of https://github.com/atom/fuzzy-finder/issues/255 so you can subscribe there for updates if you'd like.  

About your repro steps, I gave it a try and I don't see the same error I get https://github.com/atom/atom/issues/16645 which I kinda expect?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-16 20:04 UTC
