### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by chitrangsinghvi** [atom/atom#15088] opened 2017-07-25 13:07 UTC
**Switching between files using control+tab, gives this error**

**Atom**: 1.19.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
  at Object.deprecate (<embedded>:16742:42)
  at Object.path.extname (/Applications/Atom Beta.app/Contents/Resources/app/src/electron-shims.js:20:10)
  at DefaultFileIcons.iconClassForPath (<embedded>:105328:36)
  at MRUItemView.initialize (<embedded>:105930:69)
  at MRUListView.buildListView (<embedded>:60675:24)
  at MRUListView.show (<embedded>:60598:42)
  at MRUListView.choose (<embedded>:60586:18)
  at <embedded>:60556:30
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63246:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63362:34)
  at Pane.module.exports.Pane.activateNextRecentlyUsedItem (<embedded>:28923:28)
  at HTMLElement.pane:show-next-recently-used-item (<embedded>:18539:54)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (<embedded>:21817:35)
  at <embedded>:21555:65
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (<embedded>:66667:22)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (<embedded>:66458:28)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (<embedded>:18158:42)
  at HTMLDocument.<anonymous> (<embedded>:18061:65)

```

### Commands

```
  2x -0:21.5.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:12 pane:show-next-recently-used-item (input.hidden-input)
     -0:11.9.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
```

### Non-Core Packages

```
language-babel 2.68.0 
native-ui 0.21.0 
nuclide 0.241.0 
```

**Comment by rsese** [comment] 2017-07-25 17:04
Thanks for the report!  Can you confirm if the error is reproducible and if so, is it reproducible in safe mode (atom --safe)?

**Comment by chitrangsinghvi** [comment] 2017-07-26 06:00
@rsese After restarting atom beta I am no longer having the same problem, and it was not reproducible in atom --safe

**Comment by rsese** [comment] 2017-07-31 02:56
Thanks @chitrangsinghvi - since it wasn't reproducible in safe mode we'll go ahead and close for now.

**Comment by chitrangsinghvi** [comment] 2017-07-31 06:41
@rsese I was able to reproduce the error. May be you can try following steps to reproduce- 
1. Restart macbook without quiting atom beta
2. Switch to atom-beta, using dock or command+tab
3. Use control+tab to shift between tabs in atom beta

If it doesn't reproduce, pls tell me , may be there can be some problem with my system or setup.

**Comment by rsese** [comment] 2017-08-04 00:05
Thanks for the extra details @chitrangsinghvi - I gave those steps a try but still couldn't reproduce.  I'm on 1.19.0-beta6.

**Comment by andriaripratama** [comment] 2017-08-15 22:40
Same with me. Connect to my server and when open file this error shown up. Already update the Atom to 1.19.1 but still. 

Using:
Atom 1.19.1
Nuclide 0.232.0

**Comment by rsese** [comment] 2017-08-16 01:52
Can you reproduce in safe mode @andriaripratama?

**Comment by jorgebg** [comment] 2017-08-17 13:21
Same with me. Atom 1.19.1

I can't reproduce in safe mode

**Comment by rsese** [comment] 2017-08-17 20:45
Thanks @jorgebg - seems like a community package is likely causing the error then.

@andriaripratama @jorgebg - can you share your installed packages?

```
apm list --installed
```

**Comment by jorgebg** [comment] 2017-09-11 15:00
@rsese

```
$ apm list --installed
Community Packages (37) /Users/jorge/.atom/packages
├── activate-power-mode@2.4.0
├── atom-beautify@0.30.5
├── autocomplete-php@0.3.7
├── autocomplete-python@1.10.2
├── busy-signal@1.4.3
├── django-templates@0.5.0
├── git-time-machine@1.5.9
├── hyperclick@0.1.5
├── imdone-atom@2.2.7
├── intentions@1.1.5
├── language-elm@1.5.0
├── language-restructuredtext@1.1.0
├── language-vue@0.23.1
├── last-cursor-position@0.9.2
├── line-length-break@0.4.0
├── linter@2.2.0
├── linter-elm-make@0.24.3
├── linter-eslint@8.2.1
├── linter-flake8@2.2.1
├── linter-ui-default@1.6.8
├── linter-write-good@0.9.0
├── markdown-pdf@2.0.4
├── markdown-preview-enhanced@0.14.10
├── markdown-toc@0.4.2
├── markdown-writer@2.7.2
├── merge-conflicts@1.4.5
├── meta@0.0.0
├── nuclide-flow@0.0.35
├── nuclide-format-js@0.0.41
├── nuclide-type-hint@0.0.35
├── python-import-magic@1.0.3 (disabled)
├── python-isort@0.0.7
├── python-isort-multipath@0.0.1
├── seti-ui@1.9.0
├── sort-lines@0.15.0
├── symbols-tree-view@0.14.0
└── toggle-quotes@1.0.1
```

**Comment by jorgebg** [comment] 2017-09-11 15:15
FWIW I found it happens when I have an unsaved file along with the tabs and I try to switch tabs.

**Comment by jorgebg** [comment] 2017-09-13 13:21
**The offender was `nuclide-flow`**. I disabled all the packages, then I enabled them one by one, and it started to fail again as soon as I enabled `nuclide-flow`. I also checked the repo and it is gone: https://atom.io/packages/nuclide-flow

**Comment by rsese** [comment] 2017-09-13 21:00
Nice find @jorgebg :+1:  Not sure what happened to the repo, maybe it's just part of the Nuclide package now?   It does look like other folks on this thread have Nuclide installed too so that's something in common.

Since it seems like the error is being caused by Nuclide and not Atom, I'll go ahead and close this issue.   I'd suggest letting the Nuclide folks know about the problem:

https://nuclide.io/support/

It may be that there is still a bug in Atom though and if so, we'll need the maintainer of the package that is causing the problem to help track that down.

**Closed by rsese** 2017-09-13 21:00 UTC
Labels: more-information-needed, uncaught-exception
