### ISSUE TITLE
Cursor behaves strange

### ISSUE THREAD

**Issue by philipgiuliani** [atom/atom#7114] opened 2015-06-05 07:31 UTC
Hi, i just had the following bug but after closing and re-opening the file it is gone... I still wanted to report it, maybe somebody else also saw it. I never saw this before 0.206.0.

![cursor](https://cloud.githubusercontent.com/assets/5446019/8001346/2619128e-0b65-11e5-95af-62533fab2ed4.gif)

Since its not reproducible, i haven't tested it safemode.

My custom packages:
* linter
* linter-rubocop
* color-picker
* file-icons
* pigments

**Comment by textedit** [comment] 2015-06-05 08:22
I can reproduce this by the following actions:

1) Split screen
2) Move the cursor to line number bar (or somewhere in the editor where the cursor changes)
3) Move fast and click to another window
4) Finally, the cursor won't be updated 

Packages:
- linter
- file-icons

**Comment by philipgiuliani** [comment] 2015-06-05 08:28
Cool that im not the only one. For me it happened without split screen.

/cc @as-cii
Could this be (in some way) related to the tiling stuff? :)

**Comment by textedit** [comment] 2015-06-05 08:44
Hmmm, seems you can't reproduce it by the steps before the editor not starts to bug.

So the only clean workaround is to reopen the file.

**Comment by as-cii** [comment] 2015-06-05 08:44
@philipgiuliani: yep, this regression was likely generated by the new tiling mechanism. I am truly sorry this is causing headaches to you guys, I am already investigating what is causing the issue.

Unfortunately, however, I am not able to reproduce it locally (I had no luck with the steps provided by @textedit). I am afraid this may have been caused by a serialized state which doesn't play well with tiling, but I have no way to confirm that.

I'd be super grateful if you guys could help me to reproduce this issue consistently, so that I can, hopefully, find and fix the bug. Thank you!

**Comment by philipgiuliani** [comment] 2015-06-05 08:57
@as-cii No problem, it really happened only once. Maybe its just with the serialized state of 0.205.0? It happened when i opened atom for the first time today (after the update). After restarting it now serval times and trying a lot to reproduce it, im not able to.. :(

I also can't reproduce it with the steps of @textedit 

I'll report it here when i find something.

**Comment by textedit** [comment] 2015-06-05 09:14
I have edited my comment. 
Atom is running with the version ```0.205.0``` and i think i have the issue since then.

**Comment by maxbrunsfeld** [comment] 2015-06-05 16:39
@as-cii This could also be due to [my PR](https://github.com/atom/atom/pull/7023) that landed in 0.205. I have not yet been able to reproduce this.

**Comment by philipgiuliani** [comment] 2015-06-12 08:11
I haven't seen this so far for the last days... Maybe it was really an upgrade issue?

**Comment by as-cii** [comment] 2015-06-14 15:36
> I haven't seen this so far for the last days... Maybe it was really an upgrade issue?

@philipgiuliani: yeah, I suspect that the issues you and @textedit were having weren't quite the same and I have a gut feeling that yours might have been related to some corrupted status.

If @textedit and @maxbrunsfeld agree, I'd say to close this for now. Thoughts? :thought_balloon:

**Comment by maxbrunsfeld** [comment] 2015-06-14 17:24
I think we should close this if nobody's experiencing it currently. We can always reopen it.

**Closed by maxbrunsfeld** 2015-06-14 17:24 UTC
Labels: needs-reproduction
