### ISSUE TITLE
Escape ' in bracket

### ISSUE THREAD

**Issue by captdam** [atom/atom#17491] opened 2018-06-08 19:13 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

See the picture

### Steps to Reproduce

See the picture:
<img width="472" alt="capture" src="https://user-images.githubusercontent.com/24522884/41175831-64f1b22a-6b2c-11e8-811f-eb78eb23891a.PNG">

I am working on a PHP scritp, I have some code like this.
In this line `$SQL .= 'AND Status NOT IN (\'A\',\'P\',\'S\') ';`, the editor cannot see the first `\'` (the color is green), the second and third an other `\'` works fine (the editor has them in blue).
My code works fine in the server, it is just the editor cannot read the code.

**Expected behavior:** [What you expect to happen]

Every line after `$SQL .= 'AND Status NOT IN (\'A\',\'P\',\'S\') '; ` should not be highlighted in green

**Actual behavior:** [What actually happens]

The editor highlights them, the editor thought my string is not finished.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Looks like every time if I have escape character in bracket, the editor cannot see the first `\'`.

### Versions

Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Thanks :)

**Comment by rsese** [comment] 2018-06-08 20:28
Thanks for contributing!

I believe this is a duplicate of https://github.com/atom/language-php/issues/321 and the fix should be in a future release.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-06-08 20:28 UTC
