### ISSUE TITLE
Uncaught TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by rdelpeso** [atom/atom#14073] opened 2017-03-27 15:06 UTC
Hi, there seems to be an error on latest beta when there are packages with native modules compiled for an earlier version of Atom. Let me know if you need me to do any tests or if any extra information may help.

1. Have some package with native module that is incompatible with latest beta of Atom
2. Open Atom
3. Click the red bug looking icon at the bottom right of the status bar

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: "CentOS Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'text' of undefined

```
At /usr/share/atom-beta/resources/app.asar/node_modules/etch/lib/render.js:6

TypeError: Cannot read property 'text' of undefined
    at render (/app.asar/node_modules/etch/lib/render.js:6:18)
    at addChildren (/app.asar/node_modules/etch/lib/render.js:39:24)
    at render (/app.asar/node_modules/etch/lib/render.js:29:21)
    at addChildren (/app.asar/node_modules/etch/lib/render.js:39:24)
    at render (/app.asar/node_modules/etch/lib/render.js:29:21)
    at addChildren (/app.asar/node_modules/etch/lib/render.js:39:24)
    at render (/app.asar/node_modules/etch/lib/render.js:29:21)
    at addChildren (/app.asar/node_modules/etch/lib/render.js:39:24)
    at render (/app.asar/node_modules/etch/lib/render.js:29:21)
    at addChildren (/app.asar/node_modules/etch/lib/render.js:39:24)
    at render (/app.asar/node_modules/etch/lib/render.js:29:21)
    at updateChildren (/app.asar/node_modules/etch/lib/patch.js:94:36)
    at patch (/app.asar/node_modules/etch/lib/patch.js:15:9)
    at updateSync (/app.asar/node_modules/etch/lib/component-helpers.js:108:20)
    at /app.asar/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/app.asar/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
     -0:32.5.0 settings-view:open (atom-pane.pane.active)
     -0:24.9.0 incompatible-packages:view (div.incompatible-packages-status.inline-block.text.text-error)
     -0:24.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
aligner 0.22.3 
atom-alignment 0.12.1 
atom-ctags 5.0.0 
atom-formatter-jsbeautify 1.1.2 
auto-detect-indentation 1.3.0 
auto-reveal-in-sidebar 0.8.0 
autocomplete-ctags 0.4.1 
autocomplete-php 0.3.7 
blame 0.10.2 
build 0.67.0 
busy 0.7.0 
ctags-status 1.3.7 
docblockr 0.9.3 
gherkin-table-formatter 0.0.2 
git-plus 7.3.3 
highlight-selected 0.13.1 
language-docker 1.1.7 
language-gherkin 1.0.4 
language-ini 1.19.0 
language-nim 0.2.2 
last-cursor-position 0.9.2 
line-diff-details 1.6.0 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
permanent-delete 0.1.5 
php-debug 0.2.4 
php-integrator-tooltips 1.1.5 
platformio-ide-terminal 2.5.0 
pretty-json 1.6.1 
run-command 0.3.2 
run-command2 1.12.2 
sort-lines 0.14.0 
tab-control 0.6.9 
toggle-quotes 1.0.1 
trailing-spaces 0.4.0 
tree-view-breadcrumb 0.8.1 
underline-trailing-whitespace 1.4.2 
```

**Comment by rsese** [comment] 2017-03-27 16:43
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/incompatible-packages/issues/19. You may want to subscribe there for updates (it looks like a fix is in https://github.com/atom/incompatible-packages/pull/20 I think).

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-27 16:43 UTC
