### ISSUE TITLE
Comments break code folding

### ISSUE THREAD

**Issue by whoughton** [atom/atom#6664] opened 2015-05-06 03:22 UTC
Code folding seems to break if comments are placed at the very beginning of an indented line, such as:

```ruby
def customized_tools
    require 'uglifier'

    @page_module = "application"
    @page_submodule = "tools"

    @qp_id = current_user.token
    @qp_id = 'ERROR' if !@qp_id

#    qp = ActionController::Base.helpers.asset_path "qp.js"
    qp = "assets/qp.js"
#    Rails.logger.debug "Asset: #{qp}"
    bm = File.read("#{Rails.root}/support/bm.js")
```

Whereas changing the comment start location seems to fix it:

```ruby
def customized_tools
    require 'uglifier'

    @page_module = "application"
    @page_submodule = "tools"

    @qp_id = current_user.token
    @qp_id = 'ERROR' if !@qp_id

    # qp = ActionController::Base.helpers.asset_path "qp.js"
    qp = "assets/qp.js"
    # Rails.logger.debug "Asset: #{qp}"
    bm = File.read("#{Rails.root}/support/bm.js")
```

**Comment by thomasjo** [comment] 2015-05-06 08:07
Folding right now is based on indentation. Regardless, this is a duplicate of https://github.com/atom/atom/issues/3442, so follow that for updates.

**Closed by thomasjo** 2015-05-06 08:07 UTC

**Comment by whoughton** [comment] 2015-05-06 13:24
Bah, should have done the dupe check first. My apologies, and thanks for the heads up.

**Comment by thomasjo** [comment] 2015-05-06 19:07
> My apologies, and thanks for the heads up

No need for apologies, and you're welcome :smiley:
