### ISSUE TITLE
Failed to load the git-grep package

### ISSUE THREAD

**Issue by voylinux** [atom/atom#9410] opened 2015-11-03 09:26 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0-beta1
**System**: Ubuntu 14.04.3
**Thrown From**: Atom Core

### Stack Trace

Failed to load the git-grep package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:8:3
    at Object.<anonymous> (<anonymous>:8:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "mechanical-keyboard-1",
      "symbols-view",
      "metrics",
      "spotify-linux"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "fontSize": 20,
    "showIndentGuide": true,
    "softWrapAtPreferredLineLength": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.3.0
docs-snippets, v0.8.0
emmet, v2.3.13
git-grep, v0.9.0
linter, v1.9.1
linter-php, v1.0.5
minimap, v4.15.0
monokai, v0.18.0
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-03 14:58
Duplicate of mizchi/atom-git-grep#13, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-03 14:58 UTC
