### ISSUE TITLE
Atom constantly freezes

### ISSUE THREAD

**Issue by Brian1111** [atom/atom#10378] opened 2016-01-11 21:42 UTC
I am using Atom for the first time.  It constantly freezes, so I have to restart Atom all the time.  I have added several plugins to Atom, including Emmet (which I customized to work with tab), atom-beautify, etc.  I don't know if they cause Atom to freeze.  However, the menu bar is functioning; I just can't type text or enter the cursor.  The side bar also has been frozen.

**Comment by mnquintana** [comment] 2016-01-11 21:46
Can you try seeing if you can reproduce this after quitting Atom completely and restarting it in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? (`atom --safe`)

Also take a look at the [guidelines for submitting bug reports](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs).

**Comment by Brian1111** [comment] 2016-01-11 21:48
>When I  restart Atom it works well, but after a while it freezes again.

**Comment by 50Wliu** [comment] 2016-01-11 22:19
@Brian1111 That part of the document applies to all OSes.  In this case Window's terminal is `cmd.exe`.  Open it up (by searching for it) and type `atom --safe` in, then press enter.

**Comment by Brian1111** [comment] 2016-01-11 23:10
@50Wliu I just uninstalled all of my installed packages except atom-beautify, which I uninstalled and reinstalled.  So far Atom hasn't frozen.  I may reinstall the packages that I just uninstalled to check for the errors.  Does atom-emmet package interferes with atom preinstalled auto complete packages?

**Comment by 50Wliu** [comment] 2016-01-11 23:52
I don't know too much about Emmet, so I can't answer that question.  In the future you can try using @mark-hahn's [package-cop](https://atom.io/packages/package-cop) package to find which package is causing your issue.

**Comment by Brian1111** [comment] 2016-01-12 01:51
@50Wliu @mnquintana  Still I've got the problem of freezing.  I installed atom-emmet, then I entered a code in key-binding to make emmet expand with a tab.  After a short period, Atom froze again.  I opened Atom from Windows terminal in safe mode, i.e., C:> atom --safe; it didn't show any error.  I also checked the package-cop; it didn't indicate any error.  So far I have installed three packages: (1) package-cop, (2) atom-emmet, (3) atom-beautify.

**Comment by lee-dohm** [comment] 2016-01-12 02:08
@Brian1111 It sounds like either [emmet](https://atom.io/packages/emmet) or [atom-beautify](https://atom.io/packages/atom-beautify) is causing the issue. You should try reproducing the issue with only one or the other installed and then file an Issue on their repository.

**Comment by Brian1111** [comment] 2016-01-12 02:38
@lee-dohm  It seems emmet is causing the issue, so should I make a report specifically for emmet?  But I don't see any error being displayed.

**Comment by lee-dohm** [comment] 2016-01-12 02:41
Yes, if emmet is causing the issue, the emmet maintainers should help track it down. (And, as a package author myself, I would want to know if one of my packages was causing problems.)

**Comment by Brian1111** [comment] 2016-01-12 19:18
@lee-dohm @50Wliu @mnquintana  I uninstalled all of my installed packages, including emmet and atom-beautify, still atom freezes every now and then.  Have you had such a problem with Atom yourself?  How about if I just uninstall Atom and reinstall it again?  When I installed the new version of Atom I already had an older version installed.

**Comment by lee-dohm** [comment] 2016-01-12 19:56
I have not, no. Can you give repro steps for when it happens? Can you give us more information on what kind of system you're running? Can you [profile the problem](https://atom.io/docs/latest/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler)?

**Comment by lee-dohm** [comment] 2016-01-12 21:04
Reopening to see if we can narrow this down.

**Comment by coobstar** [comment] 2016-01-14 16:38
@lee-dohm experiencing this on mavericks as well - will try to glean some more info

**Comment by coobstar** [comment] 2016-01-14 19:34
got two of these bad boys in my mac logs prior to it being frozen: 

```
1/14/16 11:13:48.000 AM kernel[0]: process Atom Helper[7152] caught causing excessive wakeups. Observed wakeups rate (per sec): 392; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 78709
1/14/16 11:13:49.820 AM spindump[62390]: Saved wakeups_resource.spin report for Atom Helper version 1.3.3 (1.3.3) to /Library/Logs/DiagnosticReports/Atom Helper_2016-01-14-111349_COOBTRON-8469.wakeups_resource.spin
```


```
1/14/16 2:01:41.000 PM kernel[0]: process Atom Helper[64215] caught causing excessive wakeups. Observed wakeups rate (per sec): 269; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 96960
1/14/16 2:01:42.077 PM spindump[74316]: Saved wakeups_resource.spin report for Atom Helper version 1.4.0 (1.4.0) to /Library/Logs/DiagnosticReports/Atom Helper_2016-01-14-140142_COOBTRON-8469.wakeups_resource.spin
```

**Comment by demhydraz** [comment] 2016-01-14 19:55
Can't reproduce on Linux x86_64 (1.5.0-beta0)

**Comment by Brian1111** [comment] 2016-01-14 23:07
I cannot install Atom anymore, can anyone help?  After I uninstalled and reinstalled Atom, still it was freezing.  Because of this I uninstalled Atom, then I deleted the ".atom" file in Windows C:/User/Username/.atom.  Then I restarted my computer.  Then I double clicked "AtomSetup.exe" to install Atom, but a message pop up that says: "Installation has failed.  There was an error while installing the application.  Check the setup log for more information and contact the author."   There is an Open Setup Log.

**Comment by Brian1111** [comment] 2016-01-16 03:55
My Atom still constantly freezes.  I uninstalled Atom, then I restarted my computer, then I installed Atom again.  This time, I didn't add any plugins to Atom; I left it as it is.  Still it constantly freezes, so I constantly have to close and open it again, which is inconvenient.  Also, some parts of Atom do not function, e.g., close all tabs.  I don't know why I am the only one who has gotten such a problem.  My operating system is Windows 10.

**Comment by lee-dohm** [comment] 2016-01-16 05:13
Can you give repro steps for when it happens? Can you give us more information on what kind of system you're running (RAM, processor, HDD vs SSD)? Can you [profile the problem](https://atom.io/docs/latest/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler)? Is the code you're working on public so we can see if we can reproduce the issue with the same project and/or environment?

I understand that it freezes and we want to help. We just need as much information as you can give so that we can understand the problem.

**Comment by Brian1111** [comment] 2016-01-16 06:35
@lee-dohm Thank you for help.  Here is my computer info:  Dell Inspiron 3847, Processor: Intel, Core i5-4460; CPU@3.20GHz, 3.20GHz; RAM: 12.0 GB; 64-bit Operating System, x64-based processor.  Hard disk: 1.12 TB free of 1.81 TB.  OS: Windows 10 Home Edition, Version 1511.

I don't know how to produce "repro steps"; can you inform me how to do it?  Also, I don't remember how to upload my codes to GitHub; however, as part of the course that I am taking, i.e., Introduction to Modern Programming with PHP at Udemy, after two sections from now I have to upload my codes to GitHub.  It may take me one full day to get there.

**Comment by buggsdummy** [comment] 2016-02-17 14:32
+1 for Brian1111 for copying and pasting code. I'm on Linux Mint 17.3.

**Comment by darobin** [comment] 2016-03-09 21:01
I have this issue on Mac, with 1.5.4. I can repro under `--safe`. I have just one editor and 1-5 tabs open, nothing scary.

I think I know where it comes from. When an external process modifies one of the files in an open tab (even if it's not the active tab) I get the freeze. It's a long freeze. I haven't timed it but Atom complains about the editor becoming unresponsive 2-3 times before it works again. These are relatively large files, but not huge either (the largest is ~7kloc, ~320k, JSON, well indented). It doesn't do it every time, but pretty often. I'm pretty sure that's the source as I can't seem to repro if I keep the regenerated files closed.

I've made a sample+spindump in the Activity Monitor that I can share if it helps, I can also try to profile it though I'm unclear on how that would work since the editor instance is frozen.

**Comment by tfcdias** [comment] 2016-06-10 15:42
Atom Beautify filename too long on Windows

Without the Atom Beautify works

I don't speak English, I hope you understand

**Comment by niderhoff** [comment] 2016-06-16 09:14
Hey since a couple days i also experience major freezing on ubuntu 16.04. atom becomes completely unresponsive for 5-10 seconds and then works again for a couple seconds to become unresponsive again. I haven't even opened a file, just my home folder in the treeview. this is *with* ``atom --safe``

here is the log i get:

``idf@ubuntu:~$ atom -safe
[6205:0616/111141:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Gtk-Message: Failed to load module "canberra-gtk-module"
[6205:0616/111141:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[6205:0616/111141:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[6205:0616/111141:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[6205:0616/111141:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
App load time: 374ms
[6205:0616/111142:INFO:CONSOLE(52)] "Window load time: 399ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (52)
[6205:0616/111143:INFO:CONSOLE(41)] "keyboard-localization", source: /home/idf/.atom/packages/keyboard-localization/lib/keymap-loader.coffee (41)
[6205:0616/111143:INFO:CONSOLE(116)] "[Package-Deps] Unable to get package info for linter-markdown", source: /home/idf/.atom/packages/linter-flake8/node_modules/atom-package-deps/lib/helpers.js (116)
[6205:0616/111143:INFO:CONSOLE(36)] "linter-chktex loaded", source: /home/idf/.atom/packages/linter-chktex/lib/linter-chktex.coffee (36)
[6205:0616/111143:INFO:CONSOLE(40)] "observe chktex", source: /home/idf/.atom/packages/linter-chktex/lib/linter-chktex.coffee (40)
[6205:0616/111143:INFO:CONSOLE(46)] "observe -wall,-n22,-n30,-e16", source: /home/idf/.atom/packages/linter-chktex/lib/linter-chktex.coffee (46)
[6205:0616/111143:INFO:CONSOLE(52)] "observe false", source: /home/idf/.atom/packages/linter-chktex/lib/linter-chktex.coffee (52)
[6205:0616/111143:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[6205:0616/111143:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[6205:0616/111144:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
Failed to get crash dump id.
Report Id: 
/usr/bin/atom: line 115:  6205 Segmentation fault      (core dumped) "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@"``

**Comment by Jichao** [comment] 2016-08-09 16:35
constant freeze on mac when tab switch to the atom window.

**Comment by DarceyLloyd** [comment] 2016-08-24 00:23
Thought I would give atom a try, fresh download and install, I just got the base of a node.js app using webpack configured and it just locks up every time I open a minified js file with sourceMapping in it, eventually windows asks keep open or close.

I think it freezes because of sourceMappingURL=data:xxxxxxxxxxetc

Win10 x64, atom v1.9

**Comment by 50Wliu** [comment] 2016-08-25 16:18
> every time I open a minified js file

This is a duplicate of #979 - feel free to subscribe there for updates.

**Comment by sompylasar** [comment] 2016-08-25 16:37
Have anyone used the `saveallthetime` plugin? Looks like the frequent auto-saves cause Atom to hang until restarted (from the Task Manager, looks like it waits for something, does not actively use CPU).

**Comment by sompylasar** [comment] 2016-10-21 19:28
> Uninstalling Beautify did the trick for me.
> Dang, it's really good to have a community so open like this one (maybe packages that freezes Atom could be tracked down and their developers should be notified).
> Anyway, thanks for the help.

There is a package called `package-cop` that helps to track down issues by binary search, disabling package by package, each time it asks if that issue reproduces itself, until there is just one package left.

**Comment by sompylasar** [comment] 2016-10-21 19:30
But `package-cop` can't help if the whole Atom platform hangs, because it runs inside the platform along with other packages.

**Comment by JonRoosevelt** [comment] 2016-10-21 21:26
sompylasar that's already a good thing, but I mean a system that wouldn't allow those packages to be installed until it is validated. Anyways, I'm not sure it's the right way to deal with this.

**Comment by DarceyLloyd** [comment] 2016-10-21 22:19
atom, locks up on fresh install for me, not been able to use it for ages. gone alt route.

**Comment by jotasprout** [comment] 2016-10-28 12:31
My two bits: I have no problem with Atom on **Mac** (El Capitan) but on **Ubuntu** (14.04) I can't even use it because it constantly freezes.

**Comment by SjoCi** [comment] 2016-12-08 12:25
Hi, my problem maybe totally different, but the symptoms looks like the same.
I got an **Ubuntu** (**14.04** upgraded to **16.04**), the Atom freezes around once on a day (sometimes more, but 2 or 3 times at max). The freezes were there before the upgrade and after they are still present.  The only package installed is **'atom-typescript'** (and it needed **linter**).
I leave my PC on for days (remote access, ssh) and it never frozen during it's  more passive time (even if the Atom is still running on the GUI tty7). It always happens when I directly use the editor, writing code.
There is only a small amount of loss on the files after the freeze (which is by the way impressive), I never lost a whole line of code, only a few characters.
Also, as far as I have witnessed, it happened while I was waiting a bit will writing, as the 'suggestions' window comes up.
The 'freeze' itself is massive to the point that the whole GUI of the system must be restarted. Nothing is responding in the Unity, I got to go to tty1 and there with 'htop' I kill the Atom, but the Unity still not responding, so I kill it as well. When I go to 'htop' I always see that the RAM is full and the system uses swap, I don't know if it's related or if my problem is truly the same as the others'.
Attached computer specs.
[hwinfo.txt](https://github.com/atom/atom/files/639343/hwinfo.txt)
[swinfo.txt](https://github.com/atom/atom/files/639342/swinfo.txt)

**Comment by stujo** [comment] 2017-01-24 19:17
I share this problem on OSX atom hangs when webpack is running in a background terminal session.
I was able to repro this in atom --safe mode

atom freezes and the close or wait dialog box pops up, if you wait 5 minutes it clears

I put a core sample here:

https://gist.github.com/stujo/02c205ea19b0669b76fccc4e925b71e4

I think it might be because webpack is changing the output bundled file and this could be triggering other updates?

Not sure will post more if I find out

**Comment by jotasprout** [comment] 2017-01-25 14:03
I've never had any problems on Mac. On Linux, where I do have this issue, I've never seen one of those "close or wait" dialogs -- it either just freezes (sometimes everything, not just Atom) or, _after I've quit_ Atom, a message pops up saying "Atom closed unexpectedly" which always amuses me since it wasn't unexpected at all. Atom never actually crashes or quits unexpectedly. It just freezes so I have to quit or it tells me it had to quit when I've intentionally closed it. So, I should explicitly mention that the "closed unexpectedly" message never appears after it actually has frozen to the point of having to be quit (or laptop restarted because it caused the whole system to do a mannequin challenge).

**Comment by nextgenthemes** [comment] 2017-03-07 08:59
Same here on Ubuntu 16.10 **freezes when I open minified files**. Just tried complete clean install, deleted the config folder and the .atom folder. The dialog for close or w8 shows up.

This happened since one of the recent versions, I did not have this issue last year. I think neither in January.

**Comment by Zireael07** [comment] 2017-03-07 12:34
Freezing on minified files is #979 which was fixed and the fix is in beta3.

**Comment by DarceyLloyd** [comment] 2017-03-07 12:36
Switch to VS Code

**Comment by jotasprout** [comment] 2017-03-07 12:54
Okay, I'll try it. I've had it on my Mac and LinLiLinLinux laptop for a while but never tried it.

**Comment by nextgenthemes** [comment] 2017-03-07 14:36
@Zireael07 thanks, installing the beta fixed it.

**Comment by lee-dohm** [comment] 2017-03-07 15:49
@DarceyLloyd your comment was deleted as off-topic and unhelpful.

**Comment by allansson** [comment] 2017-03-24 21:32
I have been experiencing constant freezes, which have forced me to forcibly restart Atom. At times it seemed like it happened whenever I had some minified file open, at other times I was sure the problem was somehow caused by the tree view. I've also suspected the problem to be related to the filesystem, as it seemed to occur whenever I ran `npm install` or `mix phx.server`. I've tried the latest stable and beta version of Atom, with and without additional packages installed and the problem appears regardless.

Atom just froze up on me a few minutes ago and I hopped into `htop` in order to close it down. Looking at the process tree, I figured I could try to shut down some processes in order to see if I could find any which would cause the freeze. Turns out if I killed (SIGTERM) the command `/usr/share/atom-beta/atom --type=gpu-process` the editor unfroze and a new instance of the command was started.

Don't know if it helps anyone else, but it beats having to restart the entire editor. Here is the full command I had to shutdown, for debugging purposes:

```
/usr/share/atom-beta/atom --type=gpu-process --channel=2794.2.705535201 --mojo-application-channel-token=331CBB16D34CB3E8F4293730CD2E71F1 --no-sandbox --window-depth=24 --x11-visual-id=32 --supports-dual-gpus=false --gpu-driver-bug-workarounds=4,5,19,47,55 --disable-gl-extensions=GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_timer_query GL_EXT_imer_query --gpu-vendor-id=0x10de --gpu-device-id=0x139b --gpu-driver-vendor=Mesa --gpu-driver-version=12.0.6 --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x0416 --gpu-active-vendor-id=0x8086 --gpu-active-device-id=0x0416 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
```

**Comment by snwFlake** [comment] 2017-04-01 16:58
Arch linux kernel: 4.9.6 here...same thing. I do use atom-beautify, but I experience crashes/freezes mostly when my javascript autocomplete triggers. Even though atom is running on SSD and autocomplete for minified and node_modules is disabled, it still constantly crashes. Best step to repro is to simply type `console.` -> RIP. 

Running in safe mode works fine, but without plugins, the editor is quite useles to me...back to ST3

**Comment by sompylasar** [comment] 2017-04-01 17:36
I've recently noticed `hyperclick` falls into some infinite loop with error logging to the console which may cause a freeze, but this one may be recoverable. Did not record the exception though, just restarted.

**Comment by snwFlake** [comment] 2017-04-01 21:05
Just checked my .ternjs-project file and it turned out that loadEagerly was including the entire node_modules even though I had it inside dontLoad.   
Last 3h fast and reliable *with* atom-beautify.

**Comment by damieng** [comment] 2017-05-05 21:44
A lot of work has taken place to address performance issues in a variety of scenarios and given the multitude of different scenarios reported under a single issue here it is impossible to work out if there is still more work to do here.  

If you run into any performance problems on Atom 1.17 or later please open a new specific issue with details as to what triggers the performance problem so it can be separately investigated and addressed. Thanks!

**Closed by damieng** 2017-05-05 21:44 UTC
Labels: mac, more-information-needed, windows

**Comment by jotasprout** [comment] 2017-05-11 13:26
Couldn't find 1.17 on Atom website or UbuntuUpdates. When and where will it be available?

**Comment by 50Wliu** [comment] 2017-05-11 15:48
It's currently in beta.  https://atom.io/beta

**Comment by yang83** [comment] 2017-07-01 11:04
I solved my problem.
atom had been freezed repeatatively, even though I use the --safe mode. In my case problem was 'github' packages, it synchronized for about milion of the files so that it cause the problem. Also increase the atomhelper cpu consumption. After disabling the package, atom works fine.

**Comment by waltersol** [comment] 2017-07-10 22:29
Thanks Yang83!! That worked for me

**Comment by angiemarie** [comment] 2017-07-18 17:55
After no issues with Atom I suddenly experienced heavy lag and freezing. Yang83's solution of disabling the 'github' package worked for me. Thank you!

**Comment by Michael-N** [comment] 2017-07-29 17:19
Atom freezes when I save files, while using a watcher in gulp or webpack to transpile those files into a new directory.

**Comment by mhabsaoui** [comment] 2017-08-02 08:24
Hi, juste a feedback as I had atom freezing and solved it :

On Ubuntu 16.04 LTS, after installing atom and two packages (apm install) from shell => atom didn't freez when launched from desktop launcher, but only when launched from shell  => I tested with --safe option from bash and it didn't freez => I removed the packages, reinstalled them from the atom user graphical interface for "packs install" ==> it it didn't freez anymore when launched from anywhere :)

So, maybe is it related to installing packages (apm install) from shell  ??

**Comment by JDias** [comment] 2017-08-05 23:21
Hi,
i have this issue also. atom never clean exit (it keep atom process running and i cant start it before a kill in the process)
im using the git packages (hey, i love this : ) , i kind of miss the gui for history navigate, but that is off-topic, maybe when githubdesktop be avaiable for linux)

i was thinking if was my specs, now im in doubt.

im with an inspiron duo (2Gb of RAM and 2Ghz) is it enough? (maybe the recomended spec and this package issue deserve an entry on faq?)
 
i love atom, please keep up the great work! :)

**Comment by onacit** [comment] 2017-08-07 09:42
I had a same problem on my Windows 10 box.
The `--safe` option nor removing the `github` package didn't help.
I'm sharing my experience for others.

My last window state has `Asciidoc Preview` plugin activated.

I tried with `--clear-window-state` and got a fresh window.
And reloading the documents and previews worked for me.

**Comment by bobyap** [comment] 2017-08-10 15:02
This has been an issue to me since I installed Atom on my windows box. It intermittently freezes when I expand a project folder. It will then give me an option to wait or close the entire application. Waiting doesn't resolve the issue so closing it and reopening the app is my only option.

Is there a fix for this known issue? I love this editor but this issue is really annoying.

**Comment by lee-dohm** [comment] 2017-08-11 13:11
@bobyap There are any number of potential causes for the symptom you're describing. We can't track down the bug, if indeed there is one, from what little information you've given us. And since further comments on this very vague issue isn't going to help anyone, I'm going to lock this issue. 

We do want to help though ...

I would recommend anyone having a problem like this start with the steps in the [Debugging Guide section of the Atom Flight Manual](http://flight-manual.atom.io/hacking-atom/sections/debugging/). Many problems of this type can be resolved with one of the steps in there. If they can't be resolved, then there are steps on how to collect the information we'll need to help diagnose the problem. If you have tried the steps in there and have questions, please see the [support guide](https://github.com/atom/atom/blob/master/SUPPORT.md). If you believe you have found a bug, please open a new issue and fill out all of the required information including a list of steps you've already taken to attempt to correct the problem.

Thanks.
