### ISSUE TITLE
Partial failure when syntax coloring large files

### ISSUE THREAD

**Issue by stavnstrup** [atom/atom#13588] opened 2017-01-11 07:19 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode (except this step)
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Partial failure when syntax coloring large files

### Steps to Reproduce

1. Open a large XML file 2.81 MB (ex.  https://github.com/stavnstrup/nisp-tools/blob/master/src/standards/standards.xml)
2. Split the panel e.g. split right

**Expected behavior:** Both panel are syntax highlighted

**Actual behavior:** Only the right (second panel is syntax highlighted correctly).

**Reproduces how often:** Every time (but not with smaller XML files)

### Versions

Version:  at least 1.10 - 1.14.0-beta0.

Linux ares 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lee-dohm** [comment] 2017-01-28 22:19
The XML file you link to is returning a 404 for me, I assume because it is in a private repository?

**Comment by stavnstrup** [comment] 2017-01-29 19:51
No, it is public. Properly a temporary glitch.

**Comment by lee-dohm** [comment] 2017-01-29 19:54
There was a typo in the URL, I've edited your original post to correct it. I'll try and take a look at this today.

**Comment by AndreaGriffiths11** [comment] 2017-02-08 00:53
@lee-dohm Could you please take a look.

**Comment by lee-dohm** [comment] 2017-02-09 22:03
Sorry it took a bit to get back to this.

We noticed that this is a duplicate of https://github.com/atom/atom/issues/11232. You may want to subscribe there for updates.

**Closed by lee-dohm** 2017-02-09 22:03 UTC
