### ISSUE TITLE
Support block highlighting

### ISSUE THREAD

**Issue by Zectbumo** [atom/atom#11571] opened 2016-04-22 10:58 UTC
### Description

On Mac you can hold Option and click and drag over a block of text to highlight in a rectangle area. You can get a sample of how this should work if you look at the TextEdit.app on OS X. Hold option, click and drag over multiline text. It would be nice if Atom did the same.

### Steps to Reproduce

1. Open text file with multiline text.
2. Hold Option and click and drag over text.

**Expected behavior:**
The highlighted text should be a rectangle from where you started to where you ended the drag.

**Actual behavior:** 
The highligted text includes the rest of the lines between where you started and where you ended the drag.

### Versions
Atom 1.7.2 on OS X 10.11.4

**Comment by 50Wliu** [comment] 2016-04-22 15:28
This is a duplicate of #11031 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-22 15:28 UTC
