### ISSUE TITLE
text gets pasted twice when using kde mouse cache (paste by middle mouse button)

### ISSUE THREAD

**Issue by bugdigger1** [atom/atom#11620] opened 2016-04-27 08:00 UTC
I am using atom on kde5/plasma5 desktop on linux.

When using the mouse cache/clipboard (see below) everything gets pasted double. So for example if the mouse cache contains the text "mouse" it will paste "mousemouse". Using ctrl+z the second "mouse" gets undone and the first remains, so I guess that two paste events are triggered instead of one.

This is happening in Atom 1.6 as well as 1.7 beta versions and is irrespective of the linux distribution used (I tried on opensuse leap and archlinux). Other editors or applications are not effected by this.

For explanation:
By "mouse cache" I mean the kde clipboard function where you just mark a text in any application and can then paste it in any other application by just klicking the middle mouse button (without using ctrl+c and ctrl+v).

The mouse cache is a very convenient feature when developing in kde desktop, so I would love if you could fix this ;-)

**Comment by Ben3eeE** [comment] 2016-04-27 08:50
Duplicate of https://github.com/atom/atom/issues/8648?

**Comment by 50Wliu** [comment] 2016-04-27 14:16
Correct, thanks @Ben3eeE.

**Closed by 50Wliu** 2016-04-27 14:16 UTC
