### ISSUE TITLE
Uncaught Error: spawn /Users/kathyhoang/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Co...

### ISSUE THREAD

**Issue by crispycheeken** [atom/atom#9594] opened 2015-11-14 23:03 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Users/kathyhoang/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

```
At events.js:141

Error: spawn /Users/kathyhoang/Downloads/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at EventEmitter.ipc.sendSync (/Users/kathyhoang/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Users/kathyhoang/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:155:27)
    at Object.windowState (/Users/kathyhoang/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Users/kathyhoang/Downloads/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Users/kathyhoang/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:132:14)
    at /Users/kathyhoang/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:822:44
    at Emitter.module.exports.Emitter.emit (/Users/kathyhoang/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Project.module.exports.Project.addPath (/Users/kathyhoang/Downloads/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (/Users/kathyhoang/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1000:26)
    at EventEmitter.outerCallback (/Users/kathyhoang/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:204:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:54.3.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-11-14 23:49
Duplicate of #9559, please subscribe there for updates.

**Closed by 50Wliu** 2015-11-14 23:49 UTC
