### ISSUE TITLE
racer.racerBinPath is not set in your config.

### ISSUE THREAD

**Issue by Oskuz** [atom/atom#11211] opened 2016-03-19 21:44 UTC
Always when I type something.

**Atom Version**: 1.6.0
**System**: Ubuntu 15.04
**Thrown From**: Atom Core

### Stack Trace

racer.racerBinPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
 26x -5:25.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:13.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:13.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:11.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:46.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:46.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:46.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -4:45.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:41.7.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -2:30.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:30.5.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "northem-light-atom-ui",
      "github-2016-syntax"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "invisibles": {},
    "showIndentGuide": true,
    "tabLength": 4,
    "tabType": "soft"
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.20
atom-htmltidy, v2.3.0
atom-jade, v0.3.0
atom-webbrowser, v2.1.4
autoclose-html, v0.23.0
autocomplete-elixir, v1.5.13
autocomplete-erlang, v1.1.1
autocomplete-html-entities, v0.1.0
build-cargo, v0.13.0
build-tools, v4.3.4
f-lang, v0.0.0
file-header, v1.8.0
github-2016-syntax, v1.2.0
gpp-compiler, v2.0.2
language-cpp14, v0.6.0
language-riot-tag, v0.2.1
language-rust, v0.4.6
linter-coffeescript, v1.0.0
linter-jade, v0.3.2
local-server-express, v0.3.1
northem-light-atom-ui, v0.3.0
racer, v0.18.0
riot, v0.4.1
rust-api-docs-helper, v0.5.1

# Dev
No dev packages
```

**Comment by cheercroaker** [comment] 2016-03-25 22:25
I have just had the same issue on the 1.6.0 version of Atom and version 0.18.0 of the racer package: it seems that the "path to the Racer executable" is not well taken into account when it differs from the default value in the settings (it rather seems to be an issue with the racer package then, not directly Atom, see issue edubkendo/atom-racer#64).

I got it working by creating two symbolic links (one for the path to the racer executable and another one for the path to the Rust source code directory), e.g:
`$ sudo ln -s ~/.cargo/bin/racer /usr/local/bin/racer`
`$ sudo ln -s /usr/local/src/rust/1.7.0/src /usr/local/src/rust/src`

where `~/.cargo/bin/racer` is where cargo automatically installed racer on my machine
and `/usr/local/src/rust/1.7.0/src` is where I manually put the Rust sources

If it still does not work for you after having created the right symbolic links according to your install, check that racer is well installed and configured; you can check from the command line if that command returns some matches:
`$ racer complete std::io::B`

Hope that helps :)

**Comment by mnquintana** [comment] 2016-03-25 23:47
This looks like an issue with racer, rather than Atom core, and looks like a duplicate of https://github.com/edubkendo/atom-racer/issues/61 – closing this out.

**Closed by mnquintana** 2016-03-25 23:47 UTC
