### ISSUE TITLE
Atom lags running on Windows Server 2012 R2

### ISSUE THREAD

**Issue by ZSSchulze** [atom/atom#14296] opened 2017-04-25 12:36 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:

### Description

Atom installed on a Windows Server 2012 R2 4 gigs ram, 2.30GHz Intel Xeon CPU, 64-Bit. Servers only purpose is for Development work. There are no server roles installed. Only thing this server runs is Visual Studio and Java.

### Steps to Reproduce

1. Install Server 2012 R2
2. Install Atom
3. Lag away with Atom

### Versions

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by rsese** [comment] 2017-04-25 17:33
It looks like there's a general issue about performance on Windows at https://github.com/atom/atom/issues/7191.  I'll go ahead and close this as a duplicate so we can keep things together, but in that issue can you share more information about the lag you're seeing?  E.g. is it Atom in general once you start it and everything is slow to respond (e.g. clicking on menus, moving the mouse, etc.) or are you talking about something specific like just typing is slow?

---

Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/7191. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-25 17:33 UTC
