### ISSUE TITLE
New File Dialogue dissapears upon switching full screen apps

### ISSUE THREAD

**Issue by DavidAwad** [atom/atom#7162] opened 2015-06-07 20:12 UTC
If you go to the sidebar, right click, and create a new file, or rename a file etc. The dialogue on the top will disappear if you switch to a different full screen app. 

Is this intentional?

**Comment by mnquintana** [comment] 2015-06-07 20:28
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/1918 - please subscribe there for updates.

**Closed by mnquintana** 2015-06-07 20:28 UTC
