### ISSUE TITLE
Atom could not save file changes

### ISSUE THREAD

**Issue by DonaldKellett** [atom/atom#9140] opened 2015-10-14 13:34 UTC
When I tried to save one of my files today using both the shortcut key `cmd-s` and the long way (File > Save), this error message kept popping up:

![2015-10-14 9 30 04](https://cloud.githubusercontent.com/assets/7777884/10485050/1d84c600-72bb-11e5-9bb7-0f61b6b805d1.png)

I have already uninstalled and re-installed Atom to ensure that I have the package mentioned in the error message but the error still keeps popping up.

Please help me because Atom is the most convenient editor I have ever used.

Thank you.

**Comment by 50Wliu** [comment] 2015-10-14 14:19
Hey @DonaldKellett, this error looks like it's caused by a package called clang format.  Can you please paste the output of `apm list --installed` here so I can direct you to the correct repo?  Thanks!

**Comment by Ben3eeE** [comment] 2016-12-15 14:41
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/9140#issuecomment-148064451. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2016-12-15 14:41 UTC
Labels: more-information-needed, wrong-repo
