### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.38.2\res...

### ISSUE THREAD

**Issue by StepanSS** [atom/atom#19562] opened 2019-06-18 20:42 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version(Windows 10)
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\Step\AppData\Local\atom\app-1.38.2\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:166

Error: The specified module could not be found.
\\?\C:\Users\Step\AppData\Local\atom\app-1.38.2\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:1:688769)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2692775)
    at get_manager (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2692855)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:2692981)
    at e.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1078253)
    at KeymapManager.t.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:1244307)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:1242292)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:283624)
```

### Commands

```
     -0:58.9.0 tree-view:add-file (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-live-server 2.3.0 
color-picker 2.3.0 
emmet 2.4.3 
git-plus 8.6.2 
highlight-colors 0.5.3 
minimap 4.29.9 
platformio-ide-terminal 2.9.1 
```

**Comment by rsese** [comment] 2019-06-18 21:39
Thanks for contributing!

We noticed that this looks like a duplicate of #14461 so you can subscribe there for updates if you'd like.  Also, if you have an anti-virus program running you can try temporarily disabling it and then reinstall Atom to see if that helps.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-18 21:39 UTC
