### ISSUE TITLE
bug  windows 7

### ISSUE THREAD

**Issue by kscorpio** [atom/atom#8406] opened 2015-08-17 07:50 UTC
AppData\Local\atom\app-1.0.7\resources\app.asar\src\lines-tile-component.js:445
Hide Stack Trace

```
TypeError: Cannot read property 'textContent' of null
  at LinesTileComponent.module.exports.LinesTileComponent.measureCharactersInLine (C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\lines-tile-component.js:445:40)
  at LinesTileComponent.module.exports.LinesTileComponent.measureCharactersInNewLines (C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\lines-tile-component.js:403:16)
  at C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\lines-component.js:134:23
  at DisplayBuffer.module.exports.DisplayBuffer.batchCharacterMeasurement (C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\display-buffer.js:574:7)
  at TextEditor.module.exports.TextEditor.batchCharacterMeasurement (C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\text-editor.js:2759:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.batchCharacterMeasurement (C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\text-editor-presenter.js:1292:18)
  at LinesComponent.module.exports.LinesComponent.measureCharactersInNewLines (C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\lines-component.js:128:29)
  at TextEditorComponent.module.exports.TextEditorComponent.readAfterUpdateSync (C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\text-editor-component.js:246:29)
  at C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\text-editor-component.js:3:61
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\view-registry.js:176:9)
  at C:\Users\admin\AppData\Local\atom\app-1.0.7\resources\app.asar\src\view-registry.js:3:61
```

**Comment by thomasjo** [comment] 2015-08-17 12:15
Can you provide some more details about your issue, e.g. how/when it happened? Are you able to consistently reproduce it, and what are the steps to reproduce it? Does it happen in safe mode? Exit Atom completely, and relaunch it by executing the command `atom --safe` in a terminal.

**Comment by kscorpio** [comment] 2015-08-19 03:02
i just open an android project , and open some tabs , then i want to switch the syntax highlight model and back to the tabs to see the  code ， the bug happens.

Now when i open atom it always prompt bugs ：

- AppData\Local\atom\app-1.0.7\resources\app.asar\src\lines-tile-component.js:443
- sometimes the atom can not response and quit

**Comment by rsese** [comment] 2017-03-08 05:04
Trying to go through and cleanup some older issues - it's been a while since this report and Atom is currently at release version 1.14.4. I'll go ahead and close the issue for now but if you're still seeing an error with the latest release version of Atom, please feel free to open a new issue and fill out the issue template @kscorpio ✌️

**Closed by rsese** 2017-03-08 05:04 UTC
Labels: editor-rendering, more-information-needed
