### ISSUE TITLE
Failed to load the mobile-preview package

### ISSUE THREAD

**Issue by vmakhaev** [atom/atom#9357] opened 2015-10-30 17:31 UTC
[Enter steps to reproduce below:]

1. Open Atom

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the mobile-preview package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:5:3
    at Object.<anonymous> (<anonymous>:5:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (<anonymous>:2:21)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "term2",
      "highlight-line",
      "sublime-tabs",
      "preview-tabs",
      "language-javascript-jsx",
      "linter-eslint"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/Users/vmakhaev/projects"
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {},
    "autoIndentOnPaste": false
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
color-picker, v2.0.13
editorconfig, v1.2.0
file-icons, v1.6.11
highlight-selected, v0.10.1
language-babel, v0.15.12
language-clojure, v0.18.0
language-docker, v1.1.3
language-jade, v0.6.2
language-scala, v1.1.4
linter, v1.10.0
minimap, v4.15.0
minimap-highlight-selected, v4.3.1
mobile-preview, v0.4.0
node-resolver, v1.0.1
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-10-30 17:57
Duplicate of kenwheeler/mobile-preview#14 and kenwheeler/mobile-preview#15, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-30 17:57 UTC
