### ISSUE TITLE
Atom hangs when focusing compressed javascript files

### ISSUE THREAD

**Issue by mateogianolio** [atom/atom#10968] opened 2016-02-25 12:11 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom hangs when editing compressed javascript files. Note that files can be opened and closed without Atom hanging, it is focusing the active pane that causes the undefined behaviour.

### Steps to Reproduce

1. Open a minified javascript file
2. Click on the active pane

**Expected behavior:**
I expect the cursor to move to where I click on the active pane.

**Actual behavior:**
Atom hangs, forcing me to ether Force Quit the application or wait until Atom realises it is stuck and then close the application.

### Versions

```bash
$ atom -v
1.5.3
$ apm -v
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.0
```

**Comment by Zireael07** [comment] 2016-02-25 12:47
Duplicate of #979

**Comment by 50Wliu** [comment] 2016-02-25 17:52
Thanks @Zireael07.

**Closed by 50Wliu** 2016-02-25 17:52 UTC
