### ISSUE TITLE
Atom crashing on launch

### ISSUE THREAD

**Issue by Fuzzylr** [atom/atom#13809] opened 2017-02-13 23:42 UTC
Error message:  Editor is not responding  (Close / Keeping waiting)

Atom --version
Atom: 1.14.1
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0

OS:  Fedora 25 (4.9.8-201.fc25)

### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Launch atom (short or shell)
2. Loads to black screen
3. Error message pops up

**Expected behavior:**
I expect to see what happens in this article on Fedora's Magazine.
![atomerror](https://cloud.githubusercontent.com/assets/20960940/22908361/fa04fea2-f21b-11e6-9241-63f94eaf3c45.png)

https://fedoramagazine.org/install-atom-fedora/

**Actual behavior:**
Attached in a picture attachment

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by midhruvjaink** [comment] 2017-02-14 12:47
It is not a bug @Fuzzylr 
Whenever you get such a dialog or popup just click the  ```Keep Waiting``` button Atom will run as usual.

**Comment by AndreaGriffiths11** [comment] 2017-02-14 19:35
Hi thanks for reaching out, we need more information in order to help. Did you try to launch Atom in safe mode, what type of files where you working on, what project did you open? Is there any information you can share that might help.

**Comment by Fuzzylr** [comment] 2017-02-15 01:00
@AndreasGriffiths11 the same exact thing happens.  The screen stays black and then the error pops up.  I left it sit for a sit hoping it will load.

**Comment by 50Wliu** [comment] 2017-02-15 01:18
@Fuzzylr You'll need to keep clicking on the "Keep Waiting" button for it to continue loading.  There's currently a limitation where dialog boxes like those will block the thread until it's closed.

**Comment by ungb** [comment] 2017-02-15 19:59
@Fuzzylr, is this the first time you open Atom?  Also, as @50Wliu pointed out, you do need to click `Keep Waiting` for Atom to keep loading as the dialog blocks Atom from continue loading.

**Comment by Fuzzylr** [comment] 2017-02-15 20:18
This is rather horrible.  I've been waiting now for like 5 mintues.  I've gotten the dialog box once.  I was hoping to use this text editor with a new project I was starting but this a rather long wait time.  I've got the welcome guide but nothing on the screen.
![loadedbutnotloaded](https://cloud.githubusercontent.com/assets/20960940/22993709/f4294886-f391-11e6-9247-393fba7a952a.png)

**Comment by ungb** [comment] 2017-02-15 20:45
@Fuzzylr are you running 64-bit Fedora?  I'm going to try to repro this issue.  Also any chance you can provide your system spec?

**Comment by squarednob** [comment] 2017-02-15 21:08
On Max OSX Sierra, I encounter the similar bug twice. When I tried to close Atom, It show pop up.
And horribly each time when I click keep waiting, new window appear and can't close them.
Even more I could't force-quit Atom by context menu.

**Comment by Fuzzylr** [comment] 2017-02-15 22:35
Little update.  I put it in safe mode.  I left it sit for an hour.  It never did show up.  The entire VM froze and I had to force reboot it.  Upon rebooting and coming up.  I opened a console and started it in safe mode again.  This time the screen is black.  I got 1 pop up for the close or wait.  But now the screen says untitled - Atom.
![safemodeuntitled](https://cloud.githubusercontent.com/assets/20960940/22998520/19bd2dac-f3a5-11e6-8bbb-aef46d1fe72f.png)

**Comment by Fuzzylr** [comment] 2017-02-15 22:40
Additional informaiton
VMware Workstation 12 player
Version: 12.5.2 build-4638234

**Base hardware**
AMD FX9590 5 htz
16 gigs of ram
1 TB SSD

VM settings
2 gigs of ram
2 Processors
20 gig HD
Virtualize Intel vt-x/EPT or AMD-v/rvi

**Comment by 50Wliu** [comment] 2017-02-16 14:42
Can you attempt to start Atom using `atom --disable-gpu`?

**Comment by Fuzzylr** [comment] 2017-02-16 20:48
Using that seems to have worked.  It loaded instantly.
![disablegpu](https://cloud.githubusercontent.com/assets/20960940/23040442/54f2fb8a-f45f-11e6-8388-89a39637f453.png)

**Comment by 50Wliu** [comment] 2017-02-16 22:05
Awesome!  Try to include the fact that you're using a VM next time; that will sometimes help us to pinpoint the issue :).

This is most likely a VM issue, so I'm going to close this.

**Closed by 50Wliu** 2017-02-16 22:05 UTC
Labels: more-information-needed

**Comment by Fuzzylr** [comment] 2017-02-17 00:23
Ok, I thought I had...My bad.
