### ISSUE TITLE
Uncaught Can't find business,customer,product,hsn,utc,qty,mrp,baserate,amount,dis,gst,gstamount,t...

### ISSUE THREAD

**Issue by thescientifichuman** [atom/atom#19049] opened 2019-03-25 17:35 UTC
[Enter steps to reproduce:]

1. ...
$column = array(business,customer,product,hsn,utc,qty,mrp,baserate,amount,dis,gst,gstamount,total,finalrate,invoice,batch);
2. ... Tried to select text from business to batch and pressed Ctrl + '  to auto add group columns  in single quotes and  reached uncaught error. 

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find business,customer,product,hsn,utc,qty,mrp,baserate,amount,dis,gst,gstamount,total,finalrate,invoice,batch file

```
At C:\Users\Username\AppData\Local\atom\app-1.35.1\resources\app\static\<embedded>:11

undefined
```

### Commands

```
     -2:16.4.0 snippets:expand (input.hidden-input)
     -2:16.4.0 editor:indent (input.hidden-input)
  3x -2:15.4.0 core:undo (input.hidden-input)
     -2:13.8.0 core:redo (input.hidden-input)
     -2:13.2.0 core:save (input.hidden-input)
     -1:39.6.0 core:copy (input.hidden-input)
     -1:34.8.0 core:paste (input.hidden-input)
     -1:33.9.0 core:save (input.hidden-input)
     -1:20 core:backspace (input.hidden-input)
  3x -1:19.8.0 core:delete (input.hidden-input)
     -1:18.5.0 core:save (input.hidden-input)
     -0:50.9.0 core:copy (input.hidden-input)
     -0:46.4.0 core:paste (input.hidden-input)
  4x -0:41.3.0 emmet:encode-decode-data-url (input.hidden-input)
     -0:12.1.0 core:undo (input.hidden-input)
     -0:10 emmet:encode-decode-data-url (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.3.0 
emmet 2.4.3 
minimap 4.29.9 
teletype 0.13.3 
todo-show 2.3.2 
wakatime 7.0.9 
```

**Comment by rsese** [comment] 2019-03-25 20:43
Thanks for contributing!

We noticed that this looks like a duplicate of issues like https://github.com/atom/atom/issues/18429 where it seems like the problem was narrowed down to https://atom.io/packages/emmet (/cc https://github.com/atom/atom/issues/18429#issuecomment-439216378).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-03-25 20:43 UTC
