### ISSUE TITLE
Wrong .gitignore path on Windows

### ISSUE THREAD

**Issue by SebastianPozoga** [atom/atom#13706] opened 2017-01-28 10:14 UTC
### Description
When I save .gitignore file I take a fail 

```
Unable to save file 'C:\.\work\src\github.com\goatcms\goatcms.gitignore'
EPERM: operation not permitted, open 'C:\...\work\src\github.com\goatcms\goatcms\.gitignore'
```
![error-atom-gitignore](https://cloud.githubusercontent.com/assets/1093166/22395869/f0839466-e54a-11e6-812b-b7640c4a6c21.png)

[Description of the issue]

### Steps to Reproduce

1. create .gitignore file
2. open it in atom
3. save

**Expected behavior:** 
save file (without errors)

**Actual behavior:** 
it is fail

**Reproduces how often:**
Always

### Versions
Windows 10
atom 1.13.1 ia32

Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python
git 2.11.0.windows.3
visual studio

**Comment by lee-dohm** [comment] 2017-01-28 21:42
The `EPERM` error message means that there is a permissions issue that is preventing saving that file. This isn't a problem with Atom but with the permissions in that directory or on that file.

**Comment by SebastianPozoga** [comment] 2017-01-29 19:28
I have permision to the file

**Comment by lee-dohm** [comment] 2017-01-31 01:18
Is it just `.gitignore` or is it any file in that directory?

**Comment by SebastianPozoga** [comment] 2017-02-01 00:33
Is it just .gitignore (in C:\...\work\src\github.com\goatcms\goatcms\
directory )

2017-01-31 2:19 GMT+01:00 Lee Dohm <notifications@github.com>:

**Comment by lee-dohm** [comment] 2017-02-06 20:11
@ungb Can you reproduce this? I just noticed that the error message is omitting the final backslash before the filename. I don't know if that is just a display bug in the notification or if it is a problem with the underlying code:

* `C:\Users\Sebastian Pożoga\work\src\github.com\goatcms\goatcms.gitignore`
* `C:\Users\Sebastian Pożoga\work\src\github.com\goatcms\goatcms\.gitignore`

Notice also the `ż` in the username. Perhaps that is something to do with the problem?

**Comment by damieng** [comment] 2017-02-14 01:57
I'm also confused about the formatting of that error message.  I can't find a path that puts the phrase 'Unable to save file #filename' without at least a : in the middle.  https://github.com/search?q=org%3Aatom+%27unable+to+save+file%27&type=Code

**Comment by 50Wliu** [comment] 2017-02-14 02:47
@SebastianPozoga Does this happen in safe mode (`atom --safe`)?

**Comment by lee-dohm** [comment] 2017-02-23 17:04
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13706#issuecomment-279592005. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by SebastianPozoga** [comment] 2017-02-23 20:35
sorry for my long time response. I checked it a few seconds ago. It is heppen in safe mode```atom --safe```.
I can edit it by any other editor like notepad etc

**Comment by lee-dohm** [comment] 2017-02-23 22:01
@SebastianPozoga Is `.gitignore` a hidden file on your system? If so, this may be a duplicate of https://github.com/atom/atom/issues/13538.

**Comment by SebastianPozoga** [comment] 2017-02-23 22:54
@lee-dohm Yes, It is. I changed that. It work now. It is a duplicate.
Thank you for help.

**Comment by lee-dohm** [comment] 2017-02-23 22:58
Thank you for the quick response :bow:

**Closed by lee-dohm** 2017-02-23 22:58 UTC
Labels: more-information-needed
