### ISSUE TITLE
Uncaught Error: error: 126/\?\~\AppData\Local\atom\app-1.21.2\resources\app.asar.unpacked\node_mo...

### ISSUE THREAD

**Issue by dattracheparadigma** [atom/atom#16088] opened 2017-11-03 07:28 UTC
1. Open Atom
2. Press any key

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: error: 126\\?\C:\Users\David Attrache\AppData\Local\atom\app-1.21.2\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: error: 126\\?\C:\Users\David Attrache\AppData\Local\atom\app-1.21.2\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.2/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at Object.getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/atom-keymap/lib/helpers.js:201:42)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.2/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.2/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:48.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-beautify 0.30.6 
atom-ternjs 0.18.3 
autocomplete-html-entities 0.2.0 
avocode 0.0.6 
busy-signal 1.4.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.13 
git-time-machine 1.5.9 
intentions 1.1.5 
linter 2.2.0 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
minimap 4.29.7 
pigments 0.40.2 
pretty-json 1.6.4 
```

**Comment by rsese** [comment] 2017-11-05 04:00
I think this might be a duplicate of recent issues like https://github.com/atom/atom/issues/15722.  If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled.  If you don't have any anti-virus software, let me know.

**Closed by rsese** 2017-11-05 04:00 UTC
