### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.33.1\CSS - M...

### ISSUE THREAD

**Issue by shanu25** [atom/atom#18621] opened 2018-12-26 17:30 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Shantanu\AppData\Local\atom\app-1.33.1\CSS - My Site Images'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat 'C:\Users\Shantanu\AppData\Local\atom\app-1.33.1\CSS - My Site Images'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:916493)
    at TreeView.t.exports.TreeView.onDrop (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:922377)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:896158)
```

### Commands

```
     -5:08.9.0 editor:copy-path (input.hidden-input)
  2x -2:33.7.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -2:05.5.0 core:confirm (input.hidden-input)
     -1:57.7.0 tree-view:collapse-directory (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
```

**Comment by rsese** [comment] 2018-12-27 18:17
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/1282 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-12-27 18:17 UTC
