### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 2Error: Cannot call ...

### ISSUE THREAD

**Issue by Dragmon** [atom/atom#17262] opened 2018-05-02 16:18 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 2
Error: Cannot call function 'getPosition' on missing remote object 2
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234

Error: Cannot call function 'getPosition' on missing remote object 2
Error: Cannot call function 'getPosition' on missing remote object 2
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:354:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:234:13)
    at Object.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:118:18)
    at AtomEnvironment.getWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:694:40)
    at AtomEnvironment.storeWindowDimensions (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:731:40)
    at WindowEventHandler.handleWindowBlur (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:191:32)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
color-picker 2.3.0 
compare-files 0.8.1 
emmet 2.4.3 
file-icons 2.1.19 
git-plus 7.10.2 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.2.0 
linter-csslint 2.0.1 
linter-htmlhint 1.4.0 
linter-php 1.5.1 
linter-phpcs 1.6.8 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
php-cs-fixer 4.1.1 
```

**Comment by rsese** [comment] 2018-05-02 16:31
Thanks for the report!

This looks like a duplicate of #16630 so you can subscribe there if you'd like. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-02 16:31 UTC
