### ISSUE TITLE
Cannot uninstall or enable package?

### ISSUE THREAD

**Issue by Voyga** [atom/atom#7478] opened 2015-06-27 08:38 UTC
![snip20150627_4](https://cloud.githubusercontent.com/assets/9929523/8391177/ce97d620-1cea-11e5-8f62-33720df89b92.png)

I cannot uninstall or enable this package.

**Comment by batjko** [comment] 2015-06-27 14:04
What happens when you try, nothing?
Can you run try again in safe mode (`atom --safe`)?

Also open the Dev Tools (`Ctrl-Alt-i`) while you try and see if any errors are shown.

**Comment by izuzak** [comment] 2015-06-27 14:08
I think this is a duplicate of https://github.com/atom/atom/issues/7371 and https://github.com/atom/settings-view/issues/507 (which is the issue used to track this problem). See the advice in those issues to work around this.

**Closed by izuzak** 2015-06-27 14:08 UTC
