### ISSUE TITLE
Problem starting atom after installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by martin-pc** [atom/atom#17302] opened 2018-05-11 08:27 UTC
### Description

I have been trying to install atom on Ubuntu 18.04.
The installing process works fine, but I have been unable to start atom.
If I run atom from the commandline I get the following error:

```
~$ atom
~$ Gtk-Message: 10:17:21.448: Failed to load module "canberra-gtk-module"
pcilib: Cannot open /sys/bus/pci/devices/0000:3b:00.0/resource: No such file or directory
```
```
~$ atom --safe
martin@martin-zbook-sdu:~$ Gtk-Message: 10:19:21.723: Failed to load module "canberra-gtk-module"
pcilib: Cannot open /sys/bus/pci/devices/0000:3b:00.0/resource: No such file or directory
```

I have looked at issue #9386  hoping to the problem, but I think my problem is unrelated.

### Steps to Reproduce

1. Install Ubuntu 18.04 from scratch (x64)
2. Install the Chrome webbrowser deb file
3. install atom using ppa for ubuntu
```
sudo add-apt-repository ppa:webupd8team/atom
sudo apt-get update
sudo apt-get install atom
```
4. Try to run Atom

**Expected behavior:** atom starting up normally for the first time

**Actual behavior:** nothing (I get a few errors in the command line)

**Reproduces how often:** 100%

### Versions
```
~$atom --version
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

```
~$apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.15rc1
git 2.17.0
```

```
~$uname -a
Linux martin-zbook 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
~$cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by isopen** [comment] 2018-05-11 10:04
```
wget https://atom.io/download/deb
dpkg -i atom-amd64.deb
```
maybe a problem in gtk
https://www.linuxquestions.org/questions/linux-software-2/gtk-message-failed-to-load-module-canberra-gtk-module-936168/
Let's wait for the answers of professionals.

**Comment by martin-pc** [comment] 2018-05-11 10:06
This command seems to have solved my problem:

``` 
sudo apt install libcanberra-gtk-module libcanberra-gtk3-module
```

Then I am able to start atom :-)
I think it was the "libcanberra-gtk-module" that was missing, but I would have expect the deb to have this dependency included when I was installing it!

**Comment by rsese** [comment] 2018-05-11 17:40
Thanks for the report:

> sudo add-apt-repository ppa:webupd8team/atom

This is an unofficial distribution, please use one of the supported methods mentioned in the Flight Manual:

https://flight-manual.atom.io/getting-started/sections/installing-atom/

Using the .deb from https://atom.io, you do end up needing to use `sudo apt --fix-broken install` and that issue is captured in https://github.com/atom/atom/issues/14358.  But if you use the official package repository, it seems like all the dependencies are installed and Atom installs fine.  (I just tried both methods on 18.04).

I'll go ahead and close this as a duplicate of https://github.com/atom/atom/issues/14358 since on Ubuntu 18.04, the .deb seems to have the same general issue described there and since the official package repository works ok (if you find differently though, please let us know).

**Closed by rsese** 2018-05-11 17:40 UTC

**Comment by martin-pc** [comment] 2018-05-11 18:11
After following the guide:
https://flight-manual.atom.io/getting-started/sections/installing-atom/

I seem to be back a my starting point
```
$ atom
$ pcilib: Cannot open /sys/bus/pci/devices/0000:3b:00.0/resource: No such file or directory
```

Before following the correct guide I did
```
$ sudo apt purge atom
$ sudo ppa-purge ppa:webupd8team/atom
$ sudo apt update
```

**Comment by rsese** [comment] 2018-05-15 22:26
Which install method did you try @martin-pc?  Did you try both?

> $ pcilib: Cannot open /sys/bus/pci/devices/0000:3b:00.0/resource: No such file or directory

Are you seeing that error with any other applications?

**Comment by juandarr** [comment] 2018-05-20 22:51
I am having the same problem but not with atom (Ubuntu 18.04 , XPS 9560). It happens with VisualCode, hyper and spotify. Atom, Visualcode and hyper are created with electron while spotify uses a lot of JS, but don't know what else they have in common. I have tried with different Kernels (4.13,. 4.15, 4.16) but the problem persists, seems to be a problem specific of ubuntu 18.04. 
![error](https://user-images.githubusercontent.com/749275/40284545-35518520-5c56-11e8-8056-6b1554120efc.png)

**Comment by RDeckers** [comment] 2018-06-02 15:16
+1 I am having the same problem. Strangely enough, running a `sudo update-grub && reboot` seems to fix the issue, temporarily.  The same issue occurs with `lspci` and several other programs.

I am running a Dell XPS 9560, dual-booting Ubuntu and Windows 10.
