### ISSUE TITLE
Uncaught TypeError: el.getAttribute is not a function

### ISSUE THREAD

**Issue by OussamaBouchareb** [atom/atom#14539] opened 2017-05-21 14:20 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: el.getAttribute is not a function

```
At /usr/share/atom/resources/app/src/workspace-element.js:283

TypeError: el.getAttribute is not a function
    at isTab (/usr/share/atom/resources/app/src/workspace-element.js:283:12)
    at atom-workspace.handleDragStart (/usr/share/atom/resources/app/src/workspace-element.js:141:10)
```

### Commands

```
     -1:34.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-05-22 20:02
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14231 (and looks fixed in https://github.com/atom/atom/pull/14485). You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-22 20:02 UTC
