### ISSUE TITLE
Atom not showing on the main monitor when the second one was disconnected

### ISSUE THREAD

**Issue by paul321** [atom/atom#16095] opened 2017-11-03 20:48 UTC
Hey,

If i open Atom and i have 2 monitors setup workstation and i close Atom and disconnect one of the monitors, when i try to open the app is off the screen on Windows 10 and i can't do nothing about it to move it on the main monitor.

**Comment by lee-dohm** [comment] 2017-11-04 23:56
Thank you for your submission!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/6939. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2017-11-04 23:56 UTC
