### ISSUE TITLE
Closing an unsaved tab with middleclick on Linux prevents mouse clicks

### ISSUE THREAD

**Issue by dorian-marchal** [atom/atom#15358] opened 2017-08-17 08:37 UTC
### Prerequisites

* [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [ ] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I close an __unsaved__ tab with __middle click__ on Ubuntu 16.04, the "This file has changes" popup appears and completely blocks my mouse clicks.  
I can't click on anything, not even the "Don't save" button.

I can, however, move to the "Cancel" button with the arrow keys and then close the popup with "Enter".  
As soon as the popup is closed, the problem disappears and I can click where I want.

Note that I don't have this bug when I close an unsaved tab with "Right click > Close tab" or a __saved__ tab with middle click.

### Steps to Reproduce

1. Open a new Atom instance with `atom --safe`
2. Type "test" in the text editor, don't save.
3. Click on the tab with the middle mouse button

**Expected behavior:** A "This file has changes" popup appears, I __can__ close it by clicking on "Cancel".

**Actual behavior:** A "This file has changes" popup appears, I __can't__ click on it with my mouse.

**Reproduces how often:** 100%

### Versions

```
Ubuntu 16.04 LTS

Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
```

### Additional Information

This is a very specific bug and I don't know if it comes from Atom or Ubuntu but I don't recall having this issue on Atom 1.18.

**Comment by Ben3eeE** [comment] 2017-08-17 08:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/15197. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-17 08:38 UTC
