### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'

### ISSUE THREAD

**Issue by AKPWebDesign** [atom/atom#6665] opened 2015-05-06 05:40 UTC
**Steps to reproduce:**

1. Start Atom.
2. Right-click on anything.

**Atom Version**: 0.196.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\app.asar\src\browser\atom-window.js:152:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
  at metaToValue (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\[redacted]\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  2x -0:21.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:16.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ],
    "audioBeep": false
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.1
autocomplete-css, v0.6.0
autocomplete-emojis, v2.2.0
autocomplete-html, v0.6.0
autocomplete-plus, v2.12.1
color-picker, v1.7.0
docblockr, v0.6.3
editor-stats, v0.17.0
emmet, v2.3.8
hashrocket, v0.4.8
hex, v0.6.1
highlight-line, v0.10.2
javascript-snippets, v1.0.0
language-latex, v0.6.1
latex, v0.22.0
linter, v0.12.1
linter-bootlint, v0.0.5
linter-coffeelint, v0.2.2
linter-csslint, v0.0.12
linter-javac, v0.1.3
linter-jshint, v0.1.2
linter-less, v0.3.1
linter-scss-lint, v0.0.14
minimap, v4.8.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
seti-ui, v0.6.3
SFTP-deployment, v1.0.0
terminal-status, v1.6.6

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-06 12:18
Duplicate of #6548, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-06 12:18 UTC
