### ISSUE TITLE
Git push fails

### ISSUE THREAD

**Issue by jano23** [atom/atom#14829] opened 2017-06-19 13:43 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In the new Git panel, after I have successfully created a Commit and when I try a Push I get the following error:
remote: Invalid username or password. If you log in via a third party service you must ensure you have an account password set in your account profile.
fatal: Authentication failed for 'https://****@bitbucket.org/***/***.git/'

### Steps to Reproduce

1. Stage and Commit changes
2. Select Push
3. Enter bitbucket pwd

**Expected behavior:** Expect the Push to complete succesfully 

**Actual behavior:** I get the above error

**Reproduces how often:** 100%

###
 Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python
git 2.10.2.windows.1
visual studio

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

I have made sure that I can login to the bitbucket account with the same pwd. I can succesfully push from other programs and the command line.
Tried on Windows 10 and MacBook (macOS Sierra)

**Comment by ericchernuka** [comment] 2017-06-19 14:10
I'm having the same error connecting to GitHub.  By chance do you have two-factor enabled? I do and I'm wondering if that's causing my issues.

**Comment by jano23** [comment] 2017-06-19 14:28
I do not have two-factor enabled.

**Comment by 50Wliu** [comment] 2017-06-19 15:05
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/github#941. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-06-19 15:05 UTC
