### ISSUE TITLE
Settings keeps appearing every startup.

### ISSUE THREAD

**Issue by badboybruno547** [atom/atom#10935] opened 2016-02-23 04:26 UTC
Everytime the application is opened, it starts with a new document. However once you open the settings menu once, close the tab and close Atom, you reopen it and settings keeps appearing back as a main tab in focus. Atom v1.5.3.0

**Comment by amytruong** [comment] 2016-02-23 20:34
Hi! What OS are you on? 
I'm wondering if this is possibly a regression. :thought_balloon:

**Comment by 50Wliu** [comment] 2016-02-23 22:48
This is most likely a duplicate of #10297, so feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-23 22:48 UTC
Labels: more-information-needed
