### ISSUE TITLE
Uncaught Error: Cannot find module './context-menu'Error: Cannot find module './context-menu'  ...

### ISSUE THREAD

**Issue by simonlayfield** [atom/atom#7642] opened 2015-07-02 01:48 UTC
[Enter steps to reproduce below:]

1. Right-click in Atom.
2. Sad face :(

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)

```
At C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77

Error: Cannot find module './context-menu'
Error: Cannot find module './context-menu'
    at Function.Module._resolveFilename (module.js:328:15)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at BrowserWindow.<anonymous> (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\app.asar\src\browser\atom-window.js:149:27)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:166:7)
    at callFunction (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:116:18)
    at EventEmitter.<anonymous> (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\atom.asar\browser\lib\rpc-server.js:208:14)
    at emitMany (events.js:108:13)
    at metaToValue (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:77:15)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\atom.asar\renderer\api\lib\remote.js:111:26)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
    at HTMLDocument.handler (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
    at HTMLDocument.elemData.handle (C:\Users\CP527926\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)
```

### Commands

```
     -4:08.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:08.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -4:08.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:08.4.0 core:paste (atom-text-editor.editor.is-focused)
     -4:07.1.0 core:save (atom-text-editor.editor.is-focused)
  5x -3:37.7.0 core:delete (atom-text-editor.editor.is-focused)
     -3:34.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:34.4.0 core:copy (atom-text-editor.editor.is-focused)
     -2:22.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:21.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:19.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:19.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  5x -1:18.4.0 core:backspace (atom-text-editor.editor.is-focused)
  6x -1:12.5.0 core:move-left (atom-text-editor.editor.is-focused)
  6x -1:11.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:09.8.0 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by mnquintana** [comment] 2015-07-02 01:52
Duplicate of #6548 - this has been fixed for the next version of Atom.

**Closed by mnquintana** 2015-07-02 01:52 UTC
