### ISSUE TITLE
Opening 'Settings' - 'Packages' takes too long time

### ISSUE THREAD

**Issue by xlaywan** [atom/atom#7034] opened 2015-05-31 06:50 UTC
Even if I want to find specific package, first it lays out all packages.

**Comment by arcticicestudio** [comment] 2015-05-31 08:03
Can you provide some more informations like the version you're using and the os it runs on?
This issue may also be related to your Internet connection, since atom downloads information about the packages and could get stuck when the connection is slow.
Better wait for a reply from a staff member to see if someone reported a similar issue.

**Comment by xlaywan** [comment] 2015-05-31 08:09
win 10; atom 0.204;

UI is freezes until all packages displayed (for about 10-20 sec)

**Comment by mnquintana** [comment] 2015-05-31 10:42
Closing as duplicate of https://github.com/atom/settings-view/issues/291 – please subscribe there for updates.

**Closed by mnquintana** 2015-05-31 10:42 UTC
