### ISSUE TITLE
run nodejs project  raise error: Error: Cannot find module 'threads_a_gogo'

### ISSUE THREAD

**Issue by master-ning** [atom/atom#17754] opened 2018-07-28 02:53 UTC
run my project,raise error:

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir'/usr/local/lib/node_modules/threads_a_gogo/build'
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "-v" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/threads_a_gogo
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! threads_a_gogo@0.1.13 install: `node-gyp -v rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the threads_a_gogo@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/corpize/.npm/_logs/2018-07-28T02_48_19_656Z-debug.log

i fixed it about 3 days,but i did not fix it out 
I saw that 'threads_a_gogo' has been installed successfully，but nodejs likely does not parsed to this library,it does not run successfully

**Comment by rsese** [comment] 2018-07-30 17:54
Duplicate of https://github.com/atom/atom/issues/17747.

**Closed by rsese** 2018-07-30 17:54 UTC
