### ISSUE TITLE
Menu-bar broken handling of alt-key, left-arrow, and right-arrow

### ISSUE THREAD

**Issue by cbuschardt** [atom/atom#9756] opened 2015-11-23 09:59 UTC
It's very common behavior on windows to move between menu's with the left and right arrows.  This is and has been standard behavior for Menu's since before Windows 3.1.  We're used to it, and we love it. This is a by-product of re-implementing the menu bar in CSS.

Reproduction:
   1. Press Alt-F
   2. Press the right arrow
    (you should now be in the edit window)

Additional key related bug:
   1. Press Alt
   (you should now have the file menu selected but not open)
   2. Press F
   (File menu should now be open)

There are several other quibbles.  
    1. The color of the popup menus should match the menu-bar color (not be white!)
    2. The selection color of the menu is wrong.  It doesn't use the theme.

This is a superset of the Linux bug 'Enable jumping between menus using left-right arrow keys #5998'

**Comment by lee-dohm** [comment] 2015-11-25 03:28
Is the expected behavior different between Linux and Windows? If not, then this should be merged with #5998.

**Comment by lee-dohm** [comment] 2016-06-29 20:30
This is a duplicate of #5998 and #4057. You may want to subscribe in both locations for updates.

**Closed by lee-dohm** 2016-06-29 20:30 UTC
Labels: more-information-needed
