### ISSUE TITLE
Pane .addItem throwing error when trying to add text editor to it

### ISSUE THREAD

**Issue by mupchrch** [atom/atom#12963] opened 2016-10-12 20:41 UTC
### Description

My package is broken because it adds a new text editor to a pane by doing something like `atom.workspace.getActivePane().addItem(atom.workspace.buildTextEditor())` but gets an error: `Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method`

### Steps to Reproduce

1. Run `atom.workspace.getActivePane().addItem(atom.workspace.buildTextEditor())` in the console
2. Notice there is an error

**Expected behavior:** I would expect a new text editor to be added to the active pane.

**Actual behavior:** Nothing happens except for an error.

### Versions

Atom v1.11.1 - MacOS

**Comment by quintanar401** [comment] 2016-10-13 06:29
I have this issue too. There is a workaround via textEditorRegistry.build but until pane.addItem is called I can't change the editor's settings like its grammar. The root cause is that workspace.buildTextEditor and workspace.subscribeToAddedItems internal handler share this code:
subscriptions = new CompositeDisposable(
          ....
          @textEditorRegistry.maintainGrammar(item)
          @textEditorRegistry.maintainConfig(item)

textEditorRegistry.maintainGrammar returns undefined on the second call and breaks CompositeDisposable.

**Comment by Ben3eeE** [comment] 2016-10-13 14:24
Refs https://github.com/atom/tabs/issues/377. I thought @maxbrunsfeld fixed this in 1.11 beta. Seems he either didn't or forgot to include the fix in 1.11 stable or this is a different issue with the same steps.

**Comment by maxbrunsfeld** [comment] 2016-10-18 00:02
This is fixed in 1.11.2. Sorry for the delay.

**Closed by maxbrunsfeld** 2016-10-18 00:02 UTC

**Comment by avdg** [comment] 2016-10-18 11:23
Can't reproduce using "steps to reproduce" in 1.12.0-beta2
