### ISSUE TITLE
Uncaught Error: %1 nie jest prawid³ow¹ aplikacj¹ systemu Win32./\?\~\AppData\Local\atom\app-1.2...

### ISSUE THREAD

**Issue by slawek-gonciarz** [atom/atom#15765] opened 2017-09-28 17:58 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: %1 nie jest prawid³ow¹ aplikacj¹ systemu Win32.
\\?\C:\Users\gonciarze\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: %1 nie jest prawid³ow¹ aplikacj¹ systemu Win32.
\\?\C:\Users\gonciarze\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:22.7.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:22.6.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:21.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.1.2 
emmet 2.4.3 
```

**Comment by Zireael07** [comment] 2017-09-28 18:04
For English speakers: %1 is not a valid Win32 application.

**Comment by rsese** [comment] 2017-09-28 20:46
Thanks @Zireael07 :v:

Thanks for the report @slawek-gonciarz - can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

Also, what keyboard layout are you using?

**Comment by 50Wliu** [comment] 2018-01-03 19:38
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/15765#issuecomment-332959067. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this as a duplicate of #14461 but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2018-01-03 19:38 UTC
Labels: more-information-needed, uncaught-exception
