### ISSUE TITLE
Opening multiple instances of atom will move all to same virtual desktop

### ISSUE THREAD

**Issue by RasmusGOlsen** [atom/atom#14839] opened 2017-06-20 08:47 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When opening multiple instances of atom on different virtual desktops, all atom instances are moved to the current desktop.

### Steps to Reproduce

1. Open atom instance either from the menu launcher or from a bash shell.
2. Change to a different virtual desktop.
3. Open a new atom instance from the launcher menu or from a bash shell.

**Expected behavior:** I would expect the first atom instance to stay on the it's virtual desktop and the new instance to appear on the current virtual desktop

**Actual behavior:** All atom instances are moved to the current virtual desktop

**Reproduces how often:** 100% reproducable

### Versions
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

### Additional Information
Running XFCE on Ubuntu 16.04.1 LTS

**Comment by v3ss0n** [comment] 2017-06-20 10:30
Happens on KDE 5 too. on Gentoo Variant (Sabayon Linux)

**Comment by rsese** [comment] 2017-06-20 17:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/11610. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-06-20 17:15 UTC
