### ISSUE TITLE
Release notes after update not up-to-date

### ISSUE THREAD

**Issue by palango** [atom/atom#9998] opened 2015-12-10 10:14 UTC
I already saw this when 1.2 was released, but thought it was only a temporary glitch.

So after an update the release notes are shown, but since 1.2 they aren't updated.
![screen shot 2015-12-10 at 11 13 22](https://cloud.githubusercontent.com/assets/90851/11712735/39331bae-9f2f-11e5-8467-98a37aab7415.png)

**Comment by Maelstrome26** [comment] 2015-12-10 10:24
+1

**Comment by JGiola** [comment] 2015-12-10 10:29
+1

**Comment by 50Wliu** [comment] 2015-12-10 13:55
This is a duplicate of atom/release-notes#39 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-10 13:55 UTC
