### ISSUE TITLE
Deprecation from the atom core

### ISSUE THREAD

**Issue by mohamed-elsabagh** [atom/atom#13639] opened 2017-01-17 11:19 UTC
After I updated to the latest version of atom I keep getting deprecation error this is the message I get

Deprecated calls
atom core (1 deprecation)
Argument to path.dirname must be a string
Object.dirname - C:\Users\delvebyte\AppData\Local\atom\app-1.13.0\resources\app.asar\src\electron-shims.js:9:10
Function.viewNameForPaneItem - C:\Users\delvebyte\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\metrics\lib\reporter.js:96:16
Function.sendPaneItem - C:\Users\delvebyte\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\metrics\lib\reporter.js:133:18
<unknown> - C:\Users\delvebyte\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\metrics\lib\metrics.js:114:27
Function.module.exports.Emitter.simpleDispatch - C:\Users\delvebyte\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14
Emitter.emit - C:\Users\delvebyte\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28

**Comment by 50Wliu** [comment] 2017-01-17 14:56
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/metrics/issues/76. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-01-17 14:56 UTC
