### ISSUE TITLE
Clicking next to the filename triggers "Copied:" without copying it

### ISSUE THREAD

**Issue by AgentME** [atom/atom#9310] opened 2015-10-27 20:01 UTC
At the bottom status bar, the current filename is shown, and if you hover over it, it becomes underlined and the mouse becomes a pointer. If you move the mouse to just above or below the filename but still on the status bar and click, then the "Copied: <filename>" tooltip appears, but without actually copying the filename to the clipboard.

**Comment by mnquintana** [comment] 2015-10-27 20:12
Thanks for the report! This looks like a duplicate of https://github.com/atom/status-bar/issues/106 - feel free to subscribe there for updates.

**Closed by mnquintana** 2015-10-27 20:12 UTC
