### ISSUE TITLE
Deprecated calls | atom core (2 deprecations)

### ISSUE THREAD

**Issue by kirollosmagdy** [atom/atom#6342] opened 2015-04-12 06:35 UTC
Use a config schema instead. See the configuration section of https://atom.io/docs/latest/hacking-atom-package-word-count and https://atom.io/docs/api/latest/Config for more details
Called 3 times
Package.activateConfig - /Applications/Atom.app/Contents/Resources/app/src/package.js:250:11
Package.activateNow - /Applications/Atom.app/Contents/Resources/app/src/package.js:221:14
Use activationCommands instead of activationEvents in your package.json Commands should be grouped by selector as follows:
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
Called 1 time
Package.getActivationCommands - /Applications/Atom.app/Contents/Resources/app/src/package.js:764:9
Package.hasActivationCommands - /Applications/Atom.app/Contents/Resources/app/src/package.js:689:20

**Comment by mnquintana** [comment] 2015-04-12 10:29
Closing as duplicate of #6310

**Closed by mnquintana** 2015-04-12 10:29 UTC
