### ISSUE TITLE
Uncaught AssertionError: 509 == 0 while searching for installed package

### ISSUE THREAD

**Issue by fromthestone** [atom/atom#14077] opened 2017-03-28 04:10 UTC
I was checking installed packages (looking for Python Package if installed) on Atom for Mac, and after i start typing ```py``` and i got the red pop-up that invited me to open this issue:

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught AssertionError: 509 == 0

```
At assert.js:85

AssertionError: 509 == 0
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:159:14)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:38.3.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```

```

I hope can help to solve this issue if is really a Bug...

**Comment by rsese** [comment] 2017-03-28 05:52
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/14074. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-28 05:52 UTC
