### ISSUE TITLE
Scroll isn't updated when using a line number from the command line

### ISSUE THREAD

**Issue by ultramiraculous** [atom/atom#4780] opened 2014-12-27 21:22 UTC
Currently when you open a file from the command line with a line number, i.e.:

    atom ~/cool-thing.js:42

there is a cursor set, but the editor is still scrolled to the top.  Ideally the editor should open up scrolled to the location of the cursor.

**Comment by mnquintana** [comment] 2015-04-26 13:20
I can't reproduce this with Atom 0.195.0-07f80bc and OS X 10.10.3 - have you experienced this with the latest version of Atom (0.194.0)? Does it happen if you try opening in safe mode (`atom --safe ~/cool-thing.js:42`)?

**Comment by dancinglightning** [comment] 2015-05-03 20:48
Doesn't happen on Version 0.196.0 (0.196.0) on mac.
I have another issue to do with opening with line numbers, but since it's different i will open a seperate issue.

**Comment by mnquintana** [comment] 2015-05-03 21:40
@ultramiraculous I'm going to close this for now, but please feel free to reopen if you experience the same issue on Atom >=0.196.0.

**Closed by mnquintana** 2015-05-03 21:40 UTC
Labels: needs-reproduction
