### ISSUE TITLE
When installing updates to non-core packages, UI never advances beyond 'installing' UI

### ISSUE THREAD

**Issue by WalterGR** [atom/atom#10460] opened 2016-01-17 00:30 UTC
Atom 1.3.3 on OS X 10.10.5.

Repro:

1.  Go to Settings -> Updates when updates to non-core packages are available.
2.  Click "Update to \<version\>" button for one of the update(s).
3.  The Update button goes into what I'm assuming is the "downloading and installing" state: vertical pinstripes, scrolling horizontally.

Expected:

When installation is finished, something happens.

Actual:

The UI never changes.  The button continues to scroll.  But the update did finish installing, which can be verified by:

*  Navigating away from Settings -> Updates and then back to Settings -> Updates.  The update that was installed in the repro steps is no longer listed in the available updates.
*  Going to Settings -> Packages and checking the installed version of the package updated in the repro steps.  The most recent version number is listed.

**Comment by WalterGR** [comment] 2016-01-17 00:37
This happened in the first package update I installed just now (out of two) but didn't happen in the second.

While it's theoretically possible that the first update just took a long time to install and then completed immediately after I navigated away from Settings -> Updates, I waited long enough that I doubt that's the explanation.

**Comment by mnquintana** [comment] 2016-01-17 01:08
Thanks for the report! This is a duplicate of https://github.com/atom/settings-view/issues/532 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-17 01:08 UTC
