### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Downloads/Atom.app'

### ISSUE THREAD

**Issue by leey381** [atom/atom#18231] opened 2018-10-15 20:41 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/yeeunlee/Downloads/Atom.app'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/Users/yeeunlee/Downloads/Atom.app'
    at realpathSync (fs.js:1661:15)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:353:24)
    at toRealPath (module.js:163:13)
    at Function.Module._findPath (module.js:212:22)
    at Module._resolveFilename (module.js:541:25)
    at Module._resolveFilename (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (internal/module.js:11:18)
    at customRequire (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at AutocompleteManager.isCurrentFileBlackListed (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:694:85)
    at AutocompleteManager.findSuggestions (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:20)
    at AutocompleteManager.requestNewSuggestions (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:719:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:785:18)
    at Function.module.exports.Emitter.simpleDispatch (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1794:32)
    at TextBuffer.module.exports.TextBuffer.transact (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:998:18)
    at TextEditor.transact (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:2007:30)
    at mergeIntersectingSelections (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1434:25)
    at TextEditor.mergeSelections (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:3421:53)
    at TextEditor.mergeIntersectingSelections (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:3395:42)
    at TextEditor.mutateSelectedText (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1433:23)
    at TextEditor.insertText (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/src/text-editor.js:1386:31)
    at TextEditor.object.(anonymous function) [as insertText] (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didCompositionUpdate (/Users/yeeunlee/Downloads/Atom.app/Contents/Resources/app/src/text-editor-component.js:1746:28)
```

### Commands

```
     -9:59.1.0 core:save (input.hidden-input)
 13x -9:17.5.0 core:backspace (input.hidden-input)
     -9:04.3.0 core:save (input.hidden-input)
     -0:18.5.0 core:copy (input.hidden-input)
     -0:17.5.0 editor:newline (input.hidden-input)
     -0:16.4.0 core:paste (input.hidden-input)
  4x -0:14.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2018-10-15 21:43
Thanks for the report!

We noticed that this looks like a duplicate of #10774, so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-10-15 21:43 UTC
