### ISSUE TITLE
Opening a .xlsx or .pptx results in atom crashing

### ISSUE THREAD

**Issue by FirstWorldSlardar** [atom/atom#17272] opened 2018-05-04 12:35 UTC
### Description

When I click on them in the file menu on the left, atom crashes. The files are 12MB and 5MB respectively.

### Versions

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.12
git 2.7.4

### Additional Information
 On ubuntu 16.04

**Comment by rsese** [comment] 2018-05-04 21:20
Thanks for reaching out - the issue template information is super helpful for us when investigating issues. For example, from the `Prerequisites` section can you confirm if you see the behavior in safe mode (`atom --safe`)?

And are you able to share one of the files you mentioned or is it reproducible with any .xlsx or .pptx file?

**Comment by FirstWorldSlardar** [comment] 2018-05-07 10:17
In fact, Atom is not crashing, but do not respond, for a time proportionnal to the .xlsx or .pptx lenght, which is not the expected behavior ofc. I have reproduced this with any .xlsx or .pptx so far.

**Comment by FirstWorldSlardar** [comment] 2018-05-07 10:27
With that file (4MB) https://www.va.gov/OGC/docs/Vet_Law_Fully_Developed_Claims.pptx  you can check the problem (first duckduckgo .pptx available after a ".pptx" research)

**Comment by rsese** [comment] 2018-06-13 23:17
Thanks @FirstWorldSlardar :+1:

> In fact, Atom is not crashing, but do not respond, for a time proportionnal to the .xlsx or .pptx size,

Thanks for confirming that Atom isn't crashing.  With the example file you linked to, I also see Atom is unresponsive for some amount of time on Ubuntu 18.04 and Atom 1.27.1.  On macOS 10.12.6 the file is responsive fairly quickly though.

I did however notice that after disabling spell-check, the file was responsive pretty quickly on Ubuntu - can you confirm if you see the same behavior?

**Comment by FirstWorldSlardar** [comment] 2018-06-14 10:36
Yes indeed, I can confirm on Ubuntu that disabling spell-check solves the problem

**Comment by rsese** [comment] 2018-06-14 18:50
Thanks for confirming - looks like the .pptx file opens as plain text so it's spell-checked.  There's an 
issue about spell-check lag with large text files if you want to subscribe:

https://github.com/atom/spell-check/issues/37

I'll go ahead and close as a duplicate of that one.

**Closed by rsese** 2018-06-14 18:50 UTC
Labels: more-information-needed
