### ISSUE TITLE
Big white rectangle while dragging a tab or a file (Ubuntu/LXDE)

### ISSUE THREAD

**Issue by pgkos** [atom/atom#9701] opened 2015-11-19 18:29 UTC
There is a strange rendering issue while dragging a tab or a file. The issue occurs since version 1.2.2 (also in 1.3.0-beta4), on Ubuntu 14.04 with LXDE, 4K hidpi Dell monitor (3840x2160), GeForce GTX 660 with nVidia drivers (also in safe mode):
![atom_screen1](https://cloud.githubusercontent.com/assets/11692818/11279808/fd62edda-8ef2-11e5-83c6-e7e3c7e34567.jpg)
![atom_screen2](https://cloud.githubusercontent.com/assets/11692818/11279852/3ef27734-8ef3-11e5-9de0-e4d7a31a656a.jpg)

The rectangle gets larger and larger while moving the mouse pointer.

**Comment by pgkos** [comment] 2015-11-19 19:21
I suspect that the issue may be related to the fact that LXDE does not support transparency. The dragging creates a new window which cannot be semi-transparent because LXDE does not support it. So it is white instead.

Also, the dragged tab or file appears too far to the right and bottom (quite far from the mouse pointer). The coordinates of the dragged file/tab are exactly equal to 2 * [mouse_x, mouse_y] on my hidpi monitor.

**Comment by fiws** [comment] 2015-11-20 12:50
Same problem on gnome 3.18. 
I also have the same problem in chrome 46, while dragging anything in the browser (images, text)

**Comment by 50Wliu** [comment] 2015-11-20 15:39
@simurai Pretty sure you dealt with a similiar issue recently.

**Comment by pgkos** [comment] 2015-11-20 15:44
The issue can be reproduced on any Linux using:
```
atom --force-device-scale-factor=2
```
I have observed the big white rectangle issue only on LXDE, but the problem of wrong positioning (in relation to the mouse pointer) occurs on every Linux desktop environment (e.g. Linux Mint/Cinnamon).

But, as @fiws has written, it looks like it is partly a chromium (version 46) issue (dragged text or image is misplaced in relation to the mouse pointer, no white rectangle problem).

**Comment by simurai** [comment] 2015-11-24 11:21
This sounds similar to https://github.com/atom/atom-dark-ui/issues/47.

> @pgkos I suspect that the issue may be related to the fact that LXDE does not support transparency.

Right, in the issue mentioned above, the "solution" was to try to restyle it so there is no transparency. Like adding a solid `background-color`.

**Comment by pabloab** [comment] 2017-02-14 17:43
Is not just dragging but also while moving around:
![gifrecord_2017-02-14_143304_02](https://cloud.githubusercontent.com/assets/657836/22941084/e82ef2b2-f2c2-11e6-9fb8-611afe836cd7.gif)

**Comment by pabloab** [comment] 2018-02-14 18:24
I can't reproduce this bug anymore: Ubuntu 16.04.3 LTS
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by daviwil** [comment] 2019-01-30 00:41
Looks like this issue has been resolved at some point in 2018 like @pabloab points out.  Here's a screenshot of dragging a tab around in Ubuntu 18.10 with LXDE:

![lxde_drag](https://user-images.githubusercontent.com/79405/51950180-3b8b2080-23e4-11e9-91c4-77522674dc1c.png)

(Ignore the slight graphical artifacts, I was taking this screenshot from a virtual machine display).

I'll close this issue for now but please feel free to comment back here if you still see the issue and we can investigate.  Thanks!

**Closed by daviwil** 2019-01-30 00:41 UTC
Labels: electron, linux, needs-reproduction
