### ISSUE TITLE
Can't open any folders after forced update

### ISSUE THREAD

**Issue by parlayvu** [atom/atom#5621] opened 2015-02-18 20:33 UTC
Whether you open a folder by 1) selecting File -> Open, 2) dragging from Finder to Atom icon or 3) using atom command line, Atom always opens the same folder, even in safe mode. The folder is the site I was working on before Atom auto-updated to 0.180.

There is no error thrown, just the wrong folder opens. (ex: You select folder Banana to open, it opens folder Apple. You select folder Carrot to open, it opens the same folder Apple. You select folder Grape to open, it opens Apple again). Opening single files works, but not folders.

I have a number of other Atom core problems since the update. Never had any of them before. This is exactly why I'm against forced updates. Is there a way to downgrade to 0.179 and disable auto-updates?

I'm on Mac 10.9.5 Atom 0.180.0

**Comment by kevinsawicki** [comment] 2015-02-18 20:57
This seems very similar to https://github.com/atom/atom/issues/5617

@maxbrunsfeld any ideas on this? I'm unable to reproduce on both Mac and Windows

**Comment by kevinsawicki** [comment] 2015-02-18 21:03
> Is there a way to downgrade to 0.179 and disable auto-updates?

There are two ways to do this, one is to clone the repo, check out the `v0.179.0` tag, and run `script/build`.

The other is to download `atom-mac.zip` from https://github.com/atom/atom/releases/tag/v0.179.0 and comment out `setFeedUrl` line from `Atom.app/Contents/Resources/app/src/browser/auto-update-manager.js`:


```js
  AutoUpdateManager.prototype.setupAutoUpdater = function() {
      if (process.platform === 'win32') {
        autoUpdater = require('./auto-updater-win32');
      } else {
        autoUpdater = require('auto-updater');
      }
      // autoUpdater.setFeedUrl(this.feedUrl);
```

**Comment by maxbrunsfeld** [comment] 2015-02-18 21:06
@parlayvu can you try clearing out atom's stored state and trying again? If possible, please keep it around as it might help us debug this issue.

```shell
mv ~/.atom/storage{.bak}
```

**Comment by steelbrain** [comment] 2015-02-18 21:14
I hit a similar issue, and had to downgrade my atom. I am on Ubuntu 14.04

**Comment by maxbrunsfeld** [comment] 2015-02-18 22:20
@steelbrain @parlayvu can you upgrade to Atom v0.181, clear out your `$ATOM_HOME/storage` directory and try again?

**Comment by parlayvu** [comment] 2015-02-18 22:23
@kevinsawicki After these things are sorted out I will try this. Thanks.

@maxbrunsfeld I will try this as well and update on my status. Thanks.

**Comment by maxbrunsfeld** [comment] 2015-02-18 23:15
@parlayvu can you report the output of these commands in the dev console?

```javascript
atom.project.getPaths()
atom.getLoadSettings().initialPaths
```

**Comment by maxbrunsfeld** [comment] 2015-02-18 23:15
Also, is this happening when you start atom with `atom --safe`?

**Comment by parlayvu** [comment] 2015-02-19 05:10
@maxbrunsfeld Yes this happens in safe mode too

atom.project.getPaths() returns an array with 2 strings ["/Fruity/Apple", "/Fruity/Grape"]
First item: the Apple folder thats always shows in treeview
Second item: the folder I wanted to open

atom.getLoadSettings().initialPaths returns an array with 1 string ["/Fruity/Grape"]
First item: the folder I wanted to open

**Comment by Trudko** [comment] 2015-02-19 12:29
Hi:) @maxbrunsfeld , my problem was actually resolved by renaming storage folder and running atom again (from command line at least). I've tried this on Windows 8.

PS: out of curiosity whats storage folder exactly for?

**Comment by skandasoft** [comment] 2015-02-19 23:48
Is there any updates on this

**Comment by maxbrunsfeld** [comment] 2015-02-19 23:55
@skandasoft most users reported that 0.181 in safe mode, plus maybe clearing their storage directory fixed the problem. Does the problem still appear for you? I still would really like to get to the bottom of it, but cannot reproduce the problem.

**Comment by skandasoft** [comment] 2015-02-20 00:27
I am on windows..7 and as mentioned the first time window open with the proper directory..but If another window is opened with another directory it open the atom directory. so to replicate open a folder twice in  2 different windows..and the performance also there is a issue, it takes to put the tab title ..first time atom is loaded

**Comment by hswolff** [comment] 2015-02-20 15:14
So I am encountering this issue as well.  I can't find steps to reproduce this however I did realize that if I cleared my `.atom/storage` folder it fixes the issue.

I then looked inside the files in `storage/` and noticed that out of all the files only one of them had its `project` array with two values:

```
"project":{"paths":["/Users/hswolff/Sites/undesiredRepo","/Users/hswolff/Sites/desiredRepo"]
```

When I removed the path to the undesiredRepo everything started working again.

Hopefully that gives a little bit more focus on where the issue exists.

FWIW I am using the [atom-project-manager](https://github.com/danielbrodin/atom-project-manager) project and I feel like it is responsible for munging that `project` value and getting Atom into this state. I have nothing to validate this other than it is what seems to be responsible.

**Comment by skandasoft** [comment] 2015-02-20 15:28
clear your storage...that worked..:) thanks

**Comment by maxbrunsfeld** [comment] 2015-02-20 17:22
Thanks for the report @hswolff, @skandasoft. Is anyone still experiencing this issue on Atom >= 0.181 with `atom --safe`, after clearing `$ATOM_HOME/storage`?

Sorry for the annoyance; we had to make a change to how we deal with project paths, which apparently caused problems for certain saved editor states.

**Comment by parlayvu** [comment] 2015-02-20 18:41
@maxbrunsfeld It seems to be working now on 0.182 Mac 10.9.5. I haven't had time to fully test but I'll see how it goes the next day or two as I work.

**Comment by fernandopasik** [comment] 2015-02-23 21:40
I'm on 0.182 and cleared `$ATOM_HOME/storage` and still doesn't work.

**Comment by fernandopasik** [comment] 2015-02-24 15:35
If I right-click on the home folder and do "remove root folder" and then I can add any root folder I want.

**Closed** 2015-04-21 23:33 UTC
Labels: more-information-needed
