### ISSUE TITLE
issue in installer handling dates in Microsoft Windows OS

### ISSUE THREAD

**Issue by SpEcHiDe** [atom/atom#10772] opened 2016-02-11 11:39 UTC
I had updated Atom on the last week of January, 2016.
![capture](https://cloud.githubusercontent.com/assets/6317196/12975459/ee0de214-d0e1-11e5-89c4-347f2ec9c061.PNG)
But, when I opened the Programs and Features window, I saw the date as above. (which was funny)

I do not know whether this is a bug with Atom, but since other installed applications do not have this problem I am assuming that it is a bug with atom.

Please fix this as late as possible, as this is not at all urgent.

**Comment by 50Wliu** [comment] 2016-02-11 14:46
This is a duplicate of #6606, please subscribe there for updates!

**Closed by 50Wliu** 2016-02-11 14:46 UTC
