### ISSUE TITLE
Uncaught Error: The specified module could not be found./\?\~\AppData\Local\atom\app-1.21.0\res...

### ISSUE THREAD

**Issue by 2LXG** [atom/atom#15802] opened 2017-10-03 21:03 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: The specified module could not be found.
\\?\C:\Users\djsmith\AppData\Local\atom\app-1.21.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: The specified module could not be found.
\\?\C:\Users\djsmith\AppData\Local\atom\app-1.21.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.21.0/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:31.6.0 find-and-replace:show (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment] 2017-10-03 23:11
I think this is likely a duplicate of recent issues like https://github.com/atom/atom/issues/15722.  If you have any anti-virus software running, please check if there are any messages about quarantining this file and then see if you can restore it, or try to re-install with your anti-virus temporarily disabled.  If you don't have any anti-virus software, let me know.

**Closed by rsese** 2017-10-03 23:11 UTC
