### ISSUE TITLE
atom 1.1.0 crashes upon opening any file

### ISSUE THREAD

**Issue by bzx** [atom/atom#9392] opened 2015-11-02 13:14 UTC
I just updated to 1.1.0 (Win 7 x64), and everytime I want to open any file, the app would crash, asking me to reload window, keep it open or close the window. None of the options make a difference.

I deleted .atom/ directory and launched the app fresh, and also tried launching it from the console using "atom -safe". No luck.

Is this known issue? 
Any tips to troubleshoot it further?

**Comment by johnwalshuk** [comment] 2015-11-02 13:19
Same issue on windows 10

**Comment by leoselig** [comment] 2015-11-02 13:48
+1
This appears to occured via silently forced update - How can this happen? This just cost us half a work day each...

**Comment by albertosantini** [comment] 2015-11-02 13:58
Duplicate #9339

**Comment by bzx** [comment] 2015-11-02 18:33
I didn't have silent update turned on, Atom prompted me to update, so I did. Also in my case, the app crashes when opening any file (via File / Open...), which is not in any repo nor in any project.

**Comment by kempb** [comment] 2015-11-02 22:30
This is happening to me too.  Was working fine, suddenly, opening any document results in insta-crash.

**Comment by sylistine** [comment] 2015-11-03 04:50
@bzx is this happening even when you remove all project folders from tree view?

**Comment by jguzas** [comment] 2015-11-03 10:17
same for me

**Comment by bzx** [comment] 2015-11-03 11:25
@sylistine I just removed the ~/.atom/ dir and launched the app, and opening a file didn't crash it. Then I closed the app, and opened another file, and it crashed it. It's hard to reproduce...

**Comment by ChadLefort** [comment] 2015-11-03 19:01
I'm also having this issue 1.1.0 will crash when I try to open any file, but I installed 1.10.19 and everything worked fine and then it auto updated and I'm still having the same issues.

**Comment by benogle** [comment] 2015-11-04 01:12
Are these files in git repositories? As @albertosantini pointed out, this is probably a dupe of #9339

**Closed by benogle** 2015-11-04 01:12 UTC
