### ISSUE TITLE
Pasting after closing Atom fails

### ISSUE THREAD

**Issue by venatiodecorus** [atom/atom#10324] opened 2016-01-07 16:46 UTC
I copy some text from a buffer in Atom, then close the application. When I go to paste, my clipboard is empty. I tested with content copied from another application, and that works fine, so Atom isn't just clearing the clipboard. But when trying to paste copied text out of Atom after the application is closed, fails.

**Comment by mnquintana** [comment] 2016-01-07 16:47
What OS are you using? What version of Atom?

**Comment by venatiodecorus** [comment] 2016-01-07 18:09
Arch Linux and Atom 1.3.2

**Comment by ricardograca** [comment] 2016-01-19 10:17
Do you have a clipboard manager installed and running? Can you paste something copied from other closed applications or is it just Atom?

**Comment by demhydraz** [comment] 2016-01-29 10:09
Can't reproduce here, Arch Linux and Atom 1.5.0-beta1.

**Comment by venatiodecorus** [comment] 2016-01-29 16:41
Sorry, I tested this and Sublime behaves the same way. Must have something to do with my config and not Atom specific.

**Comment by ricardograca** [comment] 2016-01-29 18:15
You probably don't have a clipboard manager installed.

**Comment by mnquintana** [comment] 2016-02-01 13:47
Thanks for the update @venatiodecorus! Since this sounds like an OS-wide issue, and not Atom-specific, I'm going ti close this out.

**Closed by mnquintana** 2016-02-01 13:47 UTC
Labels: linux, needs-reproduction
