### ISSUE TITLE
Atom crashes on Linux: [26686:0214/075533:INFO:CONSOLE(61)] "Error: Could not create an input method.

### ISSUE THREAD

**Issue by ik5** [atom/atom#13811] opened 2017-02-14 06:05 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On executing atom 1.14.1 on Arch Linux (from official repo), there is a crash reporting: `"Error: Could not create an input method"`.

### Steps to Reproduce

1. Execute atom (UI or CLI)

**Expected behavior:** Atom will run

**Actual behavior:** It crashes:
![screenshot_2017-02-14_07-56-55](https://cloud.githubusercontent.com/assets/73091/22917175/e0b0786c-f28b-11e6-8ce5-3e2f8f49435d.png)
![screenshot_2017-02-14_07-56-16](https://cloud.githubusercontent.com/assets/73091/22917176/e0b3e858-f28b-11e6-9be7-a0393c19fb6b.png)

**Reproduces how often:** It constantly happens. even after removing all of the directories of atom -> $HOME/.atom and $HOME/.config/Atom

### Versions
I'm using Atom 1.14.1 on Arch Linux 64 bit from the official repository of Arch Linux:
- Atom    : 1.14.1
- Electron: 1.4.15
- Chrome  : 53.0.2785.143
- Node    : 6.5.0

- apm  1.15.2
- npm  4.2.0
- node 7.5.0 x64
- python 3.6.0
- git 2.11.1

- Linux - 4.9.8-1-ARCH

**Comment by rsese** [comment] 2017-02-14 06:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/13807. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

Based on https://github.com/atom/atom/issues/13807 and also https://github.com/atom/atom/issues/13743#issuecomment-279376086, I believe this is fixed in Atom 1.14.2, which may be released sometime this week.

**Closed by rsese** 2017-02-14 06:28 UTC
Labels: duplicate

**Comment by 50Wliu** [comment] 2017-02-14 16:07
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.
