### ISSUE TITLE
angular `ng serve` detects change whenever I open the file in Atom Editor

### ISSUE THREAD

**Issue by darron1217** [atom/atom#17592] opened 2018-06-27 09:07 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Angular Cli's `ng serve` detects change whenever I open the file in Atom Editor

### Steps to Reproduce

1. Start Angular project and Run `ng serve`
2. Open file in Atom Editor
3. See browser is reloading...

**Expected behavior:** [What you expect to happen]
Just opening a file should not be treated as a change! (Should not be reloaded!)

**Actual behavior:** [What actually happens]
Detects change and reload browser whenever I open the file in Atom Editor

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
```
Windows 10
@angular/cli@1.7.4
```

```
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python
git 2.17.1.windows.2
visual studio
```

### Additional Information

Related Issue on angular/angular-cli repo
https://github.com/angular/angular-cli/issues/11378

**Comment by rsese** [comment] 2018-06-27 20:21
Thanks for the report - I just installed angular-cli on a Windows 10 machine but I'm unable to reproduce with Atom 1.28.0 (I created a new project with `ng new my-project` and opened `src/index.html`).  So this happens in safe mode as well it looks like?

**Comment by darron1217** [comment] 2018-06-28 00:15
Yes, I tested it on safe mode `atom --safe`

**Comment by 50Wliu** [comment] 2018-06-28 00:35
> Open file in Atom Editor (Preview open)

Can you elaborate what you mean by "preview open" in this step?

**Comment by darron1217** [comment] 2018-06-28 00:37
I meant just one click on file (double click opens file completely, right?)

**Comment by darron1217** [comment] 2018-06-28 00:41
The weird thing is, it stops happening permanently after I save the file.

I guess it is related to file ending.
I set my git on windows to use LF for default
```
git config --global core.autocrlf false
git config --global core.eol lf
```
Can it affect change detecting system?
Atom's File Ending indicator says my opened file's ending is LF. (And it is actually LF)

**Comment by rsese** [comment] 2018-06-28 21:47
Seems like it could be related - do you see the same behavior in a different editor?  If you make a copy of your project but don't make it a git repository so it doesn't use those line ending settings, do you still see the same behavior?

**Comment by rsese** [comment] 2018-07-20 19:39
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/17592#issuecomment-401183559. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by rsese** 2018-07-20 19:39 UTC
Labels: more-information-needed
