### ISSUE TITLE
nginx: 414 Request-URI Too Large

### ISSUE THREAD

**Issue by yvan-sraka** [atom/atom#8807] opened 2015-09-16 10:14 UTC
Bonjour,

I clicked on the `Create issue on the nuclide-flow package` button, but impossible to access Github.
I get the nginx error `414 Request-URI Too Large`, and yes the URL is obviously too long:

https://github.com/facebooknuclideapm/nuclide-flow/issues/new?title=Failed%20to%20activate%20the%20nuclide-flow%20package&body=[Enter%20steps%20to%20reproduce%20below:]%0A%0A1.%20...%0A2.%20...%0A%0A**Atom%20Version**:%201.0.11%0A**System**:%20Debian%20GNU/Linux%0A**Thrown%20From**:%20[nuclide-flow]%28https://github.com/facebooknuclideapm/nuclide-flow%29%20package,%20v0.0.32%0A%0A%0A%23%23%23%20Stack%20Trace%0A%0AFailed%20to%20activate%20the%20nuclide-flow%20package%0A%0A%60%60%60%0AAt%20Cannot%20find%20module%20%27./lib/virtual-types%27%0A%0AError:%20Cannot%20find%20module%20%27./lib/virtual-types%27%0A%20%20at%20Module._resolveFilename%20%28module.js:328:15%29%0A%20%20at%20Function.Module._resolveFilename%20%28/usr/share/atom/resources/app.asar/src/module-cache.js:383:52%29%0A%20%20at%20Function.Module._load%20%28module.js:270:25%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/traversal/path/index.js:16:24%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/traversal/context.js:16:13%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/traversal/index.js:13:16%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/plugin-pass.js:19:18%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/plugin.js:16:19%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/transformer.js:12:15%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/file/plugin-manager.js:20:20%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/pipeline.js:12:26%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/index.js:12:17%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/api/node.js:25:23%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/index.js:1:80%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/nuclide-node-transpiler/lib/babel-cache.js:14:13%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/lib/main.js:17:43%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/lib/service-manager.js:5:29%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/lib/main.js:10:16%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/home/ysr/.atom/packages/nuclide-flow/lib/FlowHyperclickProvider.js:23:22%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20Object.getHyperclickProvider%20%28/home/ysr/.atom/packages/nuclide-flow/lib/main.js:84:34%29%0A%20%20at%20Package.module.exports.Package.activateServices%20%28/usr/share/atom/resources/app.asar/src/package.js:414:69%29%0A%20%20at%20Package.module.exports.Package.activateNow%20%28/usr/share/atom/resources/app.asar/src/package.js:246:16%29%0A%20%20at%20/usr/share/atom/resources/app.asar/src/package.js:224:30%0A%20%20at%20Package.module.exports.Package.measure%20%28/usr/share/atom/resources/app.asar/src/package.js:167:15%29%0A%20%20at%20Package.module.exports.Package.activate%20%28/usr/share/atom/resources/app.asar/src/package.js:216:14%29%0A%20%20at%20PackageManager.module.exports.PackageManager.activatePackage%20%28/usr/share/atom/resources/app.asar/src/package-manager.js:486:21%29%0A%20%20at%20/usr/share/atom/resources/app.asar/src/package-manager.js:469:29%0A%20%20at%20Config.module.exports.Config.transact%20%28/usr/share/atom/resources/app.asar/src/config.js:324:16%29%0A%20%20at%20PackageManager.module.exports.PackageManager.activatePackages%20%28/usr/share/atom/resources/app.asar/src/package-manager.js:464:19%29%0A%20%20at%20PackageManager.module.exports.PackageManager.activate%20%28/usr/share/atom/resources/app.asar/src/package-manager.js:445:46%29%0A%20%20at%20Atom.module.exports.Atom.startEditorWindow%20%28/usr/share/atom/resources/app.asar/src/atom.js:670:21%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8%29%0A%20%20at%20Object.%3Canonymous%3E%20%28/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4%29%0A%20%20at%20Module._compile%20%28module.js:452:26%29%0A%20%20at%20Object.defineProperty.value%20[as%20.js]%20%28/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21%29%0A%20%20at%20Module.load%20%28module.js:347:32%29%0A%20%20at%20Function.Module._load%20%28module.js:302:12%29%0A%20%20at%20Module.require%20%28module.js:357:17%29%0A%20%20at%20require%20%28module.js:376:17%29%0A%20%20at%20setupWindow%20%28file:///usr/share/atom/resources/app.asar/static/index.js:82:25%29%0A%20%20at%20window.onload%20%28file:///usr/share/atom/resources/app.asar/static/index.js:35:9%29%0A%0A%60%60%60%0A%0A%23%23%23%20Commands%0A%0A%60%60%60%0A%60%60%60%0A%0A%23%23%23%20Config%0A%0A%60%60%60json%0A{%0A%20%20%22core%22:%20{%0A%20%20%20%20%22disabledPackages%22:%20[%0A%20%20%20%20%20%20%22tree-view%22%0A%20%20%20%20]%0A%20%20}%0A}%0A%60%60%60%0A%0A%23%23%23%20Installed%20Packages%0A%0A%60%60%60coffee%0A%23%20User%0Afile-icons,%20v1.6.9%0Ahyperclick,%20v0.0.32%0Alinter,%20v1.5.1%0Aminimap,%20v4.13.3%0Anuclide-arcanist,%20v0.0.32%0Anuclide-code-format,%20v0.0.30%0Anuclide-diagnostics-store,%20v0.0.30%0Anuclide-diagnostics-ui,%20v0.0.32%0Anuclide-diff-view,%20v0.0.30%0Anuclide-file-tree,%20v0.0.32%0Anuclide-file-watcher,%20v0.0.30%0Anuclide-find-references,%20v0.0.32%0Anuclide-flow,%20v0.0.32%0Anuclide-hack,%20v0.0.30%0Anuclide-hg-repository,%20v0.0.30%0Anuclide-installer,%20v0.0.32%0Anuclide-language-hack,%20v0.0.30%0Anuclide-ocaml,%20v0.0.30%0Anuclide-quick-open,%20v0.0.30%0Anuclide-remote-projects,%20v0.0.30%0Anuclide-type-hint,%20v0.0.32%0Apigments,%20v0.15.0%0A%0A%23%20Dev%0ANo%20dev%20packages%0A%60%60%60%0A%0A

Maybe it would be a good idea that atom applies a size limit on the traceback sent?

Here's the issue that I finally managed to post https://github.com/facebook/nuclide/issues/195 ; and thank to https://github.com/ZuluPro/ZuluBot/blob/master/core/templatetags/unurlize.py

**Comment by izuzak** [comment] 2015-09-16 10:21
Thanks for the report -- I think this is a duplicate of https://github.com/atom/notifications/issues/89 so I'm going to close this in favor of that issue.

**Closed by izuzak** 2015-09-16 10:21 UTC
