### ISSUE TITLE
Replace in current selection not working very good

### ISSUE THREAD

**Issue by atrandafir** [atom/atom#7027] opened 2015-05-30 12:24 UTC
I also think is a pain-in-the-ass to have to manually click on "Only in selection".

NetBeans handles this quite good, if you had a selection before searching it will automatically activate that for you.

**Comment by izuzak** [comment] 2015-05-30 12:57
Sounds like a duplicate of this request: https://github.com/atom/find-and-replace/issues/384. Please subscribe to that issue for updates! :pager:

**Closed by izuzak** 2015-05-30 12:57 UTC
